### ISSUE TITLE
DJ/station name posted randomly to last played

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#1000]
**Installation method**
Traditional

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
Since commit https://github.com/AzuraCast/AzuraCast/commit/44f8f806d0d7967b6816ed0271f4592781cce0da the Station name and Live Dj name are posted to the last played list multiple times per streaming session (I think sometimes before playing a new song). 

**Expected behavior**
https://github.com/AzuraCast/AzuraCast/commit/44f8f806d0d7967b6816ed0271f4592781cce0da

Edit: OMG Issue 1000, congratulations! 🎉

**Comment by SlvrEagle23** [comment]
@RemBdev This is the direct result of a mitigation made for issue #867. See the last comment in that thread.

An issue reported from the fix attempted for another issue. This is my life now.

I'm not sure what the ideal solution to this is, but let me know your thoughts.

**Comment by RemBdev** [comment]
@SlvrEagle23 Thanks for the fast reactions! I understand it is very frustrating for you when a fix attemted in another issue. 

A few months ago i created an issue where i noticed when a live dj connected to the stream the last played live song was displayed in the  play now metadata. I guess this commit (https://github.com/AzuraCast/AzuraCast/commit/44f8f806d0d7967b6816ed0271f4592781cce0da) also fixed this. But currently also during the live DJ his session the metadata is changing to the station and streamer name. (I think at long playing numbers or when a dj has had a talk)

Maybe (short term) solutions are:
- Hidding "UNKNOWN" from the now_playing;
- Only update when is "UNKNOWN";
- A preference setting were it is possible  to disable this update of the metadata; (We are using Sam Broadcaster and never had UNKNOWN in the metadata)
- Only update when is_live is false;


Maybe it is also possible to hide this from the api/now_playing history so the last played will be clean.

**Comment by Vaalyn** [comment]
As I understand the changes introduced in 44f8f80 the metadata update to station name + streamer name should only happen when the `authenticateStreamer` method is called. This happens (at least as far as I know) when a dj client connects to the stream. Could it be that your DJs are losing the connection to the stream multiple times while streaming? You should be able to see that in the liquidsoap logs. There would be multiple entries for the connecting/authenticating of a DJ.

**Comment by SlvrEagle23** [comment]
@RemBdev I'm reverting the changes that will push the DJ name and station name to the metadata queue every time a DJ connects.

I'll reopen #867 as it is still in need of a solution.
