### ISSUE TITLE
CF-Connecting-IP as listener IP

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#1001]
Hi,

Is it possible to use the CF-Connecting-IP header from CloudFlare for the listener-ip adresses?

**Comment by SlvrEagle23** [comment]
@RemBdev The IP address supplied to us is provided by either SHOUTcast or Icecast, so it's up to their individual settings to determine whether we could support any additional headers.

In the case of the web port proxies, it's possible that we could rewrite the "X-Forwarded-For" header to reflect the CF-Connecting-IP header's contents. I'll need to look into that further.

**Comment by SlvrEagle23** [comment]
@RemBdev After investigating the issue further, I'm actually not sure why this isn't currently working for you. CloudFlare _does_ set the `X-Forwarded-For` header, and our nginx configuration is set up to pass that header on through to the radio service. Thanks to updates we've made, both Icecast and SHOUTcast should support reading from that header out of the box.

**Comment by RemBdev** [comment]
@SlvrEagle23 I'm sorry, i see. It didn't work because i had a wrong setting in my CloudFlare.

**Comment by afonsosantos** [comment]
> @SlvrEagle23 I'm sorry, i see. It didn't work because i had a wrong setting in my CloudFlare.

Hey, i'm suffering from that problem too. Which setting have you changed?

Thanks!

**Comment by ErnestPH** [comment]
In my case, if I connect Cloudflare… only the IP address when connecting live software (BUTT) but when there's no Cloudflare set up, I can connect using the subdomain or IP.
