### ISSUE TITLE
Upload target path is not writable

### ISSUE THREAD

**Issue by mmmnmnm** [AzuraCast/AzuraCast#1002]
Hi, 

I'm trying upload a music file and I get following error message. 

Error: XXX.mp3{"error":{"code":500,"msg":"Upload target path is not writable"}}

The upload folder is /var/azuracast/stations/radioname/media
owned by azuracast (rwx) and the group is www-data (changed to rwx but didn't solve it). 

The error log of azuracast is empty. 

Any idea? 

Peter

**Comment by Vaalyn** [comment]
Does this happen with only one specific file or all files that you try? If this only happens with one specific file what is the name of the file, the size, etc. It could then help if you can upload this file somewhere so that we could test if that happens on other installations as well. That way we can check if this is a problem with the file or the installation.

Have you updated AzuraCast to the newest version?

**Comment by mmmnmnm** [comment]
Just updated to Azuracast v0.9.1, #b1a3473 (2018-11-30 0:02). 
Still not working. The file name doesn't matter.

**Comment by Vaalyn** [comment]
That's strange. What kind of installation is this, a traditional one or docker?

**Comment by mmmnmnm** [comment]
Traditional.

**Comment by Vaalyn** [comment]
Okay can you do a `ls -la` in the terminal while you are in the `/var/azuracast/stations/radioname/media` directory and also one when you are in the `/var/azuracast/stations/radioname/` directory. Maybe the user/usergroup is incorrect.

**Comment by mmmnmnm** [comment]
**/var/azuracast/stations/radioname/media**
drwxrwsr-x 2 azuracast www-data 4096 Nov 30 12:44 .
drwxrwsr-x 5 azuracast www-data 4096 Nov 29 17:37 ..

**/var/azuracast/stations/radioname/**
drwxrwsr-x 5 azuracast www-data 4096 Nov 29 17:37 .
drwxrwxr-- 3 azuracast www-data 4096 Nov 30 09:39 ..
drwxrwsr-x 2 azuracast www-data 4096 Nov 30 12:36 config
drwxrwsr-x 2 azuracast www-data 4096 Nov 30 12:44 media
drwxrwsr-x 2 azuracast www-data 4096 Nov 30 12:36 playlists

**Nginx is running like this**: 
root     26386  0.0  0.1 173972  3140 ?        Ss   09:36   0:00 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
www-data 26392  0.0  0.4 174380  9028 ?        S    09:36   0:01 nginx: worker process

**Comment by Vaalyn** [comment]
Hmm that looks fine to me. The directory has the `www-data` group and the group permissions are `readable`, `writeable` and `executable`. This should theoretically work. When you try to upload a file can you open the browsers web developer tools and see in the network tab in the upload request what URL was used and what parameters got send? Maybe the wrong path got submitted somehow.

**Comment by mmmnmnm** [comment]
Do you mean this? 

**General**
Request URL: https://www.mydomain.com:8083/station/1/files/upload?csrf=x7DjLBOhhv&file=&searchPhrase=&flowChunkNumber=1&flowChunkSize=1048576&flowCurrentChunkSize=1048576&flowTotalSize=14805250&flowIdentifier=14805250-06elvoscamp3&flowFilename=06%20elvosca.mp3&flowRelativePath=06%20elvosca.mp3&flowTotalChunks=14
Request Method: GET
Status Code: 204 No Content
Remote Address: 178.238.217.145:8083
Referrer Policy: no-referrer-when-downgrade
**Response headers**
Cache-Control: private, no-cache, no-store
Connection: keep-alive
Content-Security-Policy: upgrade-insecure-requests; script-src 'self' 'unsafe-eval' 'nonce-OnCYFhHskOTvl7ZuxFxHePr4'
Date: Fri, 30 Nov 2018 12:01:46 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Pragma: no-cache
Referrer-Policy: no-referrer-when-downgrade
Server: nginx
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1
**Request headers**
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,hu;q=0.8,de;q=0.7
Connection: keep-alive
Cookie: _ga=GA1.2.1896321101.1540748759; _octo=GH1.1.1617582902.1540748759; PHPSESSID=qvej9ahrdgek8u3i8snq6dh5li
Host: www.mydomain.com:8083
Referer: https://www.mydomain.com:8083/station/1/files
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
csrf: x7DjLBOhhv
file: 
searchPhrase: 
flowChunkNumber: 1
flowChunkSize: 1048576
flowCurrentChunkSize: 1048576
flowTotalSize: 14805250
flowIdentifier: 14805250-06elvoscamp3
flowFilename: 06 elvosca.mp3
flowRelativePath: 06 elvosca.mp3
flowTotalChunks: 14

**And this is what I see on the console tab:** 
{"error":{"code":500,"msg":"Upload target path is not writable"}} e {flowObj: d, bytes: null, file: File(14805250), name: "elvosca.mp3", size: 14805250, …}averageSpeed: 0bytes: nullchunks: []currentSpeed: 0error: truefile: File(14805250) {relativePath: "elvosca.mp3", name: "elvosca.mp3", lastModified: 1513009087672, lastModifiedDate: Mon Dec 11 2017 17:18:07 GMT+0100 (Central European Standard Time), webkitRelativePath: "", …}flowObj: ddefaults: {chunkSize: 1048576, forceChunkSize: false, simultaneousUploads: 3, singleFile: false, fileParameterName: "file", …}events: {fileadded: Array(1), filessubmitted: Array(1), fileprogress: Array(1), filesuccess: Array(1), fileerror: Array(1), …}files: (2) [e, e]onDrop: ƒ (a)opts: {chunkSize: 1048576, forceChunkSize: false, simultaneousUploads: 3, singleFile: false, fileParameterName: "file_data", …}preventEvent: ƒ (a)support: truesupportDirectory: true__proto__: Objectname: "elvosca.mp3"paused: falserelativePath: "elvosca.mp3"size: 14805250uniqueIdentifier: "14805250-elvoscamp3"_lastProgressCallback: 1543579494446_prevProgress: 0.2124738184090103_prevUploadedSize: 3145728__proto__: Object

**Comment by Vaalyn** [comment]
The request itself looks okay to me but the JavaScript error shouldn't be there. I'm not sure if this JS error is shown because something on the serverside throws the 500 error or if the JS part causes the server error. What browser are you using and what server OS is installed on your server?

**Comment by mmmnmnm** [comment]
Where do you see that it's caused by JavaScript? 

I tried Safari, Edge, Chrome, Firefox, all with the same result. 

I have Ubuntu 16.04 LTS. 

I had a working Azuracast on this server which broke after an update (actually it just broke: the Azuracast web interface was suddenly unreachable) and I had to reinstall. Now everything seems to work except uploads. The installation was successful (no errors).

**Comment by Vaalyn** [comment]
I've not said that it is definitely caused by the JS I just mentioned that it may be the one causing this. This could very well also be just a side effect of the server error and has nothing to do with it.

**Comment by mmmnmnm** [comment]
I see. It doesn't sound very good as the error has no other trace. What do you suggest me to do?

**Comment by Vaalyn** [comment]
Since I'm not that familiar with the traditional installation yet I'd like to get the opinion of @SlvrEagle23 here. Maybe he has an idea why this is happening in your AzuraCast installation. One last thing I'd like to ask would be if you happen to know why or what exactly broke your web interface before you reinstalled AzuraCast? And also if you did a complete clean new install, so without transfering data via a backup to the new installation.

Apart from this issue I'd recommend using the docker installation since this is harder to break and much easier to work with and also replicating issues for us is much easier.

**Comment by mmmnmnm** [comment]
I don't know what happened with the previous installation. It worked well for weeks. Then at some point I couldn't access the web interface of Azuracast. 

We tried the docker version too but it wasn't convenient for us because we need https and we want the web interface to be at some port other than 80 and 443 (we operate our custom radio frontend at default 80 and 443).

**Comment by mmmnmnm** [comment]
And yes, I uninstall and then re-install again.

**Comment by mmmnmnm** [comment]
But I see that these issues are taken care of with docker as well so I will now try to uninstall the traditional instance and try with docker. Thanks for your time!

**Comment by mmmnmnm** [comment]
I installed it via docker and it all works fine. 

One addition to the https set up if one is using custom ports: start Azuracast using default ports, setup LetsEncrypt, change to custom ports. The LetsEncrypt challenge won't work with custom ports. The install instructions (https://www.azuracast.com/docker_sh.html#available-commands) and this note on custom ports (https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#use-non-standard-ports) helped but I had to do some thinking :)

**Comment by SlvrEagle23** [comment]
@mmmnmnm While I'm not sure what in particular caused your problem, and I'm not aware of any widespread issues happening with traditional installations and their permissions, it would be nice if we could've debugged things further and resolved the problem without needing a full reinstall of your installation.

Likewise, with your previous iteration, if the web interface stops responding there are many diagnostic steps that can be taken and reinstalling all of AzuraCast should probably be considered a last resort; based on the information I can gather from GitHub issues, the software's not in a state of instability that requires frequent reinstallation.

In any case, I always recommend the use of the Docker installation version for a number of reasons, and number one among them is the tendency to wipe out entire classes of potential bugs and issues by containing the installation in an image that we can maintain and update frequently. I'm glad you were able to get the custom port mapping to work out.

If you have any further issues, I'd ask for your patience as we work to diagnose and fix them before wiping the installation.

**Comment by mmmnmnm** [comment]
@SlvrEagle23 you're absolutely right. I must say I acted in panic because we had an outage in our radio and I needed a quick fix. I knew that reinstall was brute force but I thought it would fix it. Instead, it brought in additional headache. In the end I'm glad with what happened because I think that the Docker version will be better for us on the long term and the outage forced us to make this step. It would have been nice to found out about the root cause of the original problem (and also of the permission issue) but I think we had a messy state of our server (due to various installations in the past) so I can well imagine that the problem was on our side and not in Azuracast.
