### ISSUE TITLE
Add an API endpoint to retrieve all requestable media at once

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#1005]
**Is your feature request related to a problem? Please describe.**
I'd like to have an API endpoint that can be used to retrieve all requestable media so that external applications can process them without having to call the paginated endpoint multiple times.

**Describe the solution you'd like**
A new API endpoint that returns all requestable media with one request. This endpoint should only be accessable via authentication to prevent abuse.

**Comment by SlvrEagle23** [comment]
@Vaalyn This can now be done by setting `per_page` to -1 as a URL parameter.
