### ISSUE TITLE
Playlist every 2 weeks or once per month 

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#1006]
What if I would like to run a playlist every 2 weeks or once per month?

Thanks

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38780/allow-multiple-schedule-entries-for-a-single-playlist

**Comment by scottallanaz** [comment]
Hello, was this feature ever resolved?

Thanks
