### ISSUE TITLE
Clock with Station time in header

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#1007]
**Having a Clock on top of every page displaying the station time and [date].**
Would be nice to have a clock on top of all pages ( header location ) showing the station/local time

![slack-imgs](https://user-images.githubusercontent.com/7961/49328759-fbd7c200-f575-11e8-9c30-4853fa44ceb1.png)

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39029/show-a-clock-with-station-time-in-the-header
