### ISSUE TITLE
Add an optional POST parameter to the request API for IP addresses

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#1008]
**Is your feature request related to a problem? Please describe.**
The `StationRequestRepository` has the functionality to throttle requests by IP addresses. This feature is only available when using the built-in request form of AzuraCast. When submitting requests via the API this feature is not usable.

**Describe the solution you'd like**
I'd like to be able to optionally submit an IP address as a POST parameter to the API so that external applications can make use of this feature, too.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39028/add-an-optional-post-parameter-to-the-request-api-for-ip-addresses
