### ISSUE TITLE
Message after successful (?) update: "docker rmi" requires at least 1 argument

### ISSUE THREAD

**Issue by mmmnmnm** [AzuraCast/AzuraCast#1009]
Hi, 

I've just run an update on my docker installation and everything looked to be fine. Except that I see following messages which make me feel unsure. I also read this issue https://github.com/AzuraCast/AzuraCast/issues/408

My questions: 

- Is my update correct? 
- Do I need to do any steps after updating (e.g., removing images reported in aforementioned issue)? 

Peter

**The last messages I see after running docker update**: 

[OK] AzuraCast is now updated to the latest version!

2018/12/01 15:06:59 Command finished successfully.
azuracast_influxdb_1 is up-to-date
azuracast_mariadb_1 is up-to-date
azuracast_redis_1 is up-to-date
Creating azuracast_letsencrypt_1 ...
azuracast_stations is up-to-date
Creating azuracast_letsencrypt_1 ... done
Creating azuracast_cli_1         ... done
Creating azuracast_cron          ... done
Creating azuracast_nginx_1       ... done
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images

**Comment by SlvrEagle23** [comment]
@mmmnmnm This is not an error; it just means that you've updated recently enough that Docker has nothing to "clean up", i.e. no old images it needs to remove, because no images have changed in that time period.
