### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by RainbowDash53** [AzuraCast/AzuraCast#101]
TASK [azuracast-radio : Link Fallback Error MP3] *******************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error while linking: [Errno 2] Aucun fichier ou dossier de ce type", "path": "/usr/share/icecast2/web/error.mp3", "state": "absent"}

RUNNING HANDLER [azuracast-user : send user notification] **********************
        to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

The server is empty

**Comment by SlvrEagle23** [comment]
@RainbowDash53 This error ("Aucun fichier ou dossier de ce type") means IceCast 2 didn't install correctly. Do you have any errors farther up in the installation process, specifically relating to IceCast 2's installation, which should be immediately before this section of the script?

Also, which version of Ubuntu are you running?

**Comment by SlvrEagle23** [comment]
Closing as this bug should no longer apply, as IceCast is now built from the KH branch's source code.
