### ISSUE TITLE
Storage Space Restrictions

### ISSUE THREAD

**Issue by WeigandM** [AzuraCast/AzuraCast#1010]
Hello I have a question. 

How can I limit the storage space for a station? For example, Station 1 can only use 5 GB of memory, Station 2 can use 10 GB, etc. ?

**Comment by Vaalyn** [comment]
Currently there is no official way to do this.

I have not tested this but it could theoretically work.

You could mount a separate partition from your host machine that has the limited space to the path of the station media directory. In a docker installation this can be done via the `docker-compose.override.yml` with a `volume` entry. And in a traditional installation you'd need to use the mounting tools that your host OS provides.

**Comment by RemBdev** [comment]
https://github.com/AzuraCast/AzuraCast/issues/368

**Comment by SlvrEagle23** [comment]
@WeigandM This is a long-standing enhancement request (#368); you can follow that issue for further updates.
