### ISSUE TITLE
Unable To Connect To Streaming Server

### ISSUE THREAD

**Issue by ArranLH** [AzuraCast/AzuraCast#1012]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 18.04

**Describe the bug**
Cannot connect to server using Shoutcast or IceCast.

Connect to the server

**Expected behavior**
Connection not establishing

**Relevant Logs**
2018/12/01 23:16:14 [lang:3] Authenticating DJ: shoutcast
2018/12/01 23:16:14 [lang:3] AzuraCast DJ Auth Response: false
2018/12/01 23:16:15 [lang:3] AzuraCast Raw Response: /usr/local/share/icecast/web/error.mp3
2018/12/01 23:16:15 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2018/12/01 23:16:27 [cargofm_next_song:3] Finished with "/usr/local/share/icecast/web/error.mp3".
2018/12/01 23:16:27 [cargofm_next_song:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 6).
2018/12/01 23:16:35 [lang:3] AzuraCast Raw Response: /usr/local/share/icecast/web/error.mp3

**Device(s):**
Windows 10 - BUTT, SAM Broadcaster & Mixxx

**Additional context**
At the moment, it does not establish at all. The right connection details are being used. Still have no clue why it is not working... I have already done ufw disable and added exceptions to the firewall.

**Comment by deinstreamserver** [comment]
Does you have some music in your playlist? 

If not try uploading some files and restart streaming. I looks like only the fallback (error.mp3) is playing, and no Liquidsoap - what's needed to connect to the stream.


--
Sorry for bad english

**Comment by arranh11** [comment]
Since its happened I have added some songs to autodj and it still doesn't work.

**Comment by Vaalyn** [comment]
This line indicates to me that the authentication of the DJ in liquidsoap failed:
`2018/12/01 23:16:14 [lang:3] AzuraCast DJ Auth Response: false`

That means you are connecting on the correct port and liquidsoap tries to verify the user/password but it seems that the provided user/password is incorrect.

**Comment by Vaalyn** [comment]
Then we need to do some research together. Can you try disabling and enabling the Stream Users in the Station Profile under AutoDj and check if the authentication still fails. Then try disabling and enabling the specific Stream User and check again. Then try resetting the passwort and check again.
Let's see if any of these steps resolves the problem or if we need to investigate a bit closer here.

**Comment by arranh11** [comment]
Update:
I have managed to get it working using IceCast.

**Comment by arranh11** [comment]
Shoutcast is still throwing up issues.
(this is a test server so go ham)
https://i.imgur.com/WAwzs9z.png
https://i.imgur.com/WfrDyLD.png

This is after with the Shoutcast config
https://i.imgur.com/QFpECTY.png

**Comment by LordHelmchen666** [comment]
Try arran,arran or arran;arran. I had also problems with : on login. For me it works with , (comma)

**Comment by arranh11** [comment]
Not working still, but at least Icecast works 👍
