### ISSUE TITLE
Timer not counting (nowplaying API)

### ISSUE THREAD

**Issue by mmmnmnm** [AzuraCast/AzuraCast#1016]
Hi, 

I have a short audio file (11sec), which I play over and over between shows. 

On the first play I see the time counting. After that API (nowplaying) is not updating those fields. I see constantly this (while refreshing the API request in a browser):  

elapsed | 11
remaining | 0

As a result, the elapsed time is not moving in the player. 

Any idea? 

Peter

**Comment by SlvrEagle23** [comment]
@mmmnmnm Files shorter than about 15-30 seconds won't properly show duration, as they're shorter than the polling interval that AzuraCast uses when checking what song is playing on the broadcasting software. The duration feature is intended to be a fairly accurate approximation of playback time for longer pieces of audio.
