### ISSUE TITLE
Make backup possible without downtime

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#1019]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to run automatic backups every night without having any downtime of AzuraCast.

**Describe the solution you'd like**
Don't stop all docker containers when doing a backup.

**Describe alternatives you've considered**
If it's not possible to do the backup like it is implemented now without stopping all containers we should write a more sophisticated backup script. This could be a bigger task then.

**Comment by SlvrEagle23** [comment]
@Vaalyn The current backup script actually backs up the full volumes associated with InfluxDB, MariaDB and the stations containers. It would be all but impossible to reliably back those up while they're in the middle of operations using this method.

What we'd need to do is implement a "second generation" backup script that takes advantage of mysqldump and influxdb's dump feature to generate flatfile backups of their running counterparts.

We have the start of something like that in the `./docker-migrate.sh` script, which executes both a MariaDB and InfluxDB dump locally and imports them into the Docker ecosystem.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39027/allow-zerodowntime-backups
