### ISSUE TITLE
Optionally exclude media files from backup

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#1020]
**Is your feature request related to a problem? Please describe.**
When using the backup feature of the `docker.sh` to backup to network storages the backup takes a large amount of time when there are a lot of media files. I want to be able to use AzuraCasts backup feature to make fast backups in order to get the whole stack setup when needing to use a backup.

**Describe the solution you'd like**
To be able to backup AzuraCast regularly to a network storage without having to transfer large amounts of data every time it would be helpful to be able to exclude the media files from the .tar.gz that the backup command generates. Preferably via an optione like `--no-media` or something like that. With this it would be possible to make fast backups of AzuraCast and manually backup the media files via an `rsync` cron that only writes deltas to previously backed up media files.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39026/optionally-exclude-media-files-from-backup
