### ISSUE TITLE
Display current running playlist on profile page

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#1023]
When I login to a station I never know which playlist is currently running.
I need to click on playlist and then on schedule, but when there is no playlist
at that given time, i still don't know from which playlist a song is coming from.

Thanks
![bildschirmfoto von 2018-12-05 09-07-58](https://user-images.githubusercontent.com/7961/49499333-fb894080-f86d-11e8-830d-f8fda26703b1.png)

**Comment by Vaalyn** [comment]
That should be easy to add. The API already tells us which playlist a song is coming from. I'll take care of it after work.

**Comment by macbroadcast** [comment]
Cool, maybe you can check why skip song kills the station in case a remote playlistisrunning

**Comment by Vaalyn** [comment]
Can you open a separate issue for that and inlcude any logs and other information that could help to diagnose that problem? Or is there already an issue for that?

**Comment by macbroadcast** [comment]
I checked the logs,but there is nothing beside the buffer underrun, which is quite disturbing i found just one issue that fits on tradionel installation. https://github.com/AzuraCast/AzuraCast/issues/907#issuecomment-434137979

**Comment by Vaalyn** [comment]
Okay, can you open a new issue since you are experiencing this with the docker installation and a remote playlist. It could be the same cause but it may not. Also I'd need some information on how to reproduce the setup needed to trigger this. I've used multiple playlist and skipped very often but never saw this behaviour so there must be something specific that is triggering the crash.

**Comment by macbroadcast** [comment]
I deleted the playlist in question and i will keep an eye on it, next time it happen i will open an new issue.

**Comment by macbroadcast** [comment]
Cool, thanks for this, should there be something displayed in the field next playlist? @SlvrEagle23 

![bildschirmfoto von 2018-12-05 22-27-40](https://user-images.githubusercontent.com/7961/49545227-4e4e1100-f8dd-11e8-8d13-c9c95606cb80.png)

**Comment by Vaalyn** [comment]
I'm not 100% sure why this is but while implementing this I noticed that not every song that the API returned had the playlist field set. If the field is set the Playlist will be shown so this is actually a new issue that is now showing up.

**Comment by macbroadcast** [comment]
ok,i shut up then :smile:

**Comment by Vaalyn** [comment]
@macbroadcast I've created an issue for this problem: https://github.com/AzuraCast/AzuraCast/issues/1026

**Comment by SlvrEagle23** [comment]
Playlist will only now show up when a playlist is actually set.

#1026 should also be fixed now.
