### ISSUE TITLE
Web Dj CUE lags issue

### ISSUE THREAD

**Issue by alime50** [AzuraCast/AzuraCast#1027]
**Installation method** 
Docker

**Host OS (for Docker installations)** 
Centos 7

**Describe the bug**
When we use CUE to listen what is playing it gives lags and noise.

**To Reproduce**
Select song and press CUE

**Expected behavior**
Should lag and noise free 

**Device(s):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: chrome
 - Version: latest

**Comment by SlvrEagle23** [comment]
@alime50 This is a known issue specifically with the "CUE" buttons for each of the individual playlists. It seems to affect Chrome specifically and not other browsers.

I reported it upstream at webcast/webcaster#9, so hopefully we can figure out what's causing it and get it figured out.

In the meantime, pressing "CUE" next to the "Start Streaming" button on the left will cue up the entire mixed audio and seems to work without any issues.

**Comment by alime50** [comment]
> @alime50 This is a known issue specifically with the "CUE" buttons for each of the individual playlists. It seems to affect Chrome specifically and not other browsers.
> 
> I reported it upstream at [webcast/webcaster#9](https://github.com/webcast/webcaster/issues/9), so hopefully we can figure out what's causing it and get it figured out.
> 
> In the meantime, pressing "CUE" next to the "Start Streaming" button on the left will cue up the entire mixed audio and seems to work without any issues.

thanks i have checked in firefox it is working fine im using azuracast on my [chat](https://livechatzone.com) website from a month.

**Comment by SlvrEagle23** [comment]
@alime50 Good to hear!
