### ISSUE TITLE
All my media files get reprocessed every 5-minutes scan

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#1031]
**Installation method**
Traditional

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
My VPS slows down since it appears that the media files are processed at evrey scan

**To Reproduce**
When I force manually the 5-minutes scan, it will take about 120 seconds (where it takes 5 seconds on a very same VPS with the same files) before it end up with the following information 👍 

Media processed for station "My FM".
total_files
1478
updated
1478
created
0
removed
0

So I am guessing it reindexes all my files at every scan. What would be the way to fix this ?

**Additional context**
When importing the media files, I copied with SCP from another VPS, then I changed the user:group to azuracast-www-data and chmod to 777

**Comment by SlvrEagle23** [comment]
@griffon56 The previous `updated` number didn't take into account whether files were actually reprocessed or just skipped past during the processing steps. I've updated this to have separate `unchanged` and `updated` responses; if you don't mind, can you update and let me know if your records are coming back as unchanged or whether they're actually triggering updates every time?

**Comment by griffon56** [comment]
Thanks you @SlvrEagle23 for your help.
Indeed Azuracast was not reindexing, but skiping.

And the reason for my VPS being slow was because the initial media indexing of azuracast caused high CPU usage and was detected by my VPS host and reduced its speed... this is now fixed.

Media processed for station "My FM".
total_files
1478
unchanged
1478
updated
0
created
0
deleted
0
