### ISSUE TITLE
Can't clone station

### ISSUE THREAD

**Issue by jovadeza** [AzuraCast/AzuraCast#1033]
**Installation method**
Docker method

**Host OS (for Docker installations)**
Ubuntu 18.04 x64 VPS

**Describe the bug**
When I clone a station, share the media folder and copy the playlists, the cloned station won't play. If I try to start Liquidsoap on the cloned station or restart the cloned station I get this error: "SPAWN_ERROR: station_2:station_2_backend".

At first I thought that I needed to change the IceCast port on the cloned station to something else, but that did not made any changes. Unfortunately, I can not find any more information in the log files.

**To Reproduce**
To reproduce, clone a station and try starting it and run standalone from the other station.

**Expected behavior**
I want to run multiple stations, sharing the same media folder and playlists (with some differences in the jingle playlist).

Thanks in advance!

**Comment by Vaalyn** [comment]
I have actually used the `Clone Station` feature to setup 3 additional stations for my radio that share the same media folder without any problems. Can you tell us a bit more about your setup, like what configurations do your stations have (especially the ports)?
I had the problem when manually assigning ports that I accidentally had some features that tried to use the same ports which prevented the station from running. Maybe that's also the case here.
