### ISSUE TITLE
run out of space very quickly

### ISSUE THREAD

**Issue by xanenightwing** [AzuraCast/AzuraCast#1035]
**Installation method**
Docker

**Host OS (for Docker installations)**
Debian 9.6

**Describe the bug**
The space available to upload files (reported at 19.02GB) is used up very quickly with only 10 files (totalling about 2.34 GB in size), and I am unable to determine how to free up extra space. Along with this (though this part may be more of my system than part of Azuracast), a space-monitoring tool I have installed on the system is reporting that "The 19.10 GB filesystem mounted at / has only 81.62 MB of free disk space," which does seem like it could be part of Azuracast.

**Screenshots**
![image](https://user-images.githubusercontent.com/759048/49668736-b3f8e500-fa24-11e8-8f44-f9fc33bceb16.png)
![image](https://user-images.githubusercontent.com/759048/49668766-c4a95b00-fa24-11e8-87ee-150f41400ffa.png)

**Device(s):**
 - Device: Desktop
 - Browser: Chrome
 - Version: Azuracast 0.9.1

**Comment by xanenightwing** [comment]
Just to make an addendum, how would one go about increasing the amount of space that Azuracast uses for storage in the first place?

**Comment by Vaalyn** [comment]
Can you determine what exactly is using the space?
You can start by using `du -hs` on `/var/lib/docker/volumes/azuracast_station_data/_data/<station_name>/config/` this way you can check how much space your log files + some configs use. Maybe you have a lot of logs.

**Comment by SlvrEagle23** [comment]
@xanenightwing I've recently been working to add improvements to log rotation and other temporary file space eaters across the system...are you still seeing large amounts of space being taken up when the system's running idle (i.e. not uploading new songs, etc.)?

The other issue you mentioned, with the "chunks" of uploaded files remaining in the temporary directory after they've been moved to their final destination, appears to be valid and I'm working on improving our cleanup routines to ensure these get handled properly.

**Comment by xanenightwing** [comment]
@SlvrEagle23 I'm not seeing that much anymore, though I've recently re-installed the entire server (that is, the underlying OS and software and such), and then moved the Docker data directories to a different partition on the machine that can hold more data, which has prevented me from running out of space for a while.

**Comment by xtechgamer735** [comment]
![gore](https://user-images.githubusercontent.com/5082164/50576054-6c862e80-0e01-11e9-94bf-769d6d2ab766.png)
Unsure if its related, but I had a little fun with liquidsoap's logs the other day...

**Comment by xtechgamer735** [comment]
I wasn't brave enough to open it to be honest, but its started again since I deleted it and just spams this: `2019/01/01 20:49:49 [lang:3] AzuraCast Raw Response: ` so I assume it had just filled up with that. I'lll make sure to check back occasionally and check what its up to.

I have just updated to the latest version so it might stop, who knows! Let me know if you need any more info :)

**Comment by SlvrEagle23** [comment]
@JDBlackman I'll look into the log rotation rules for our nginx configuration, but if it bloated up to that size in a short period of time, that could either indicate an attack...or immense popularity.

**Comment by JDBlackman** [comment]
@SlvrEagle23 The station can max out around 1k listeners at the best of times.  I haven't cleared the logs in maybe 6months. Log rotation would probably be best to fix this issue.

**Comment by SlvrEagle23** [comment]
@JDBlackman Great numbers for the station! I'm looking into log rotation for nginx; as with many programs it doesn't have its own internal rotator and we'll need to set something custom up to manage it. In our case, that'll also mean putting nginx behind supervisord in Docker so that AzuraCast can send the USR1 log rotate command to it intra-container. Slightly more work than I anticipated, but I'm on it right now.

**Comment by carloshs94** [comment]
> @SlvrEagle23 The station can max out around 1k listeners at the best of times. I haven't cleared the logs in maybe 6months. Log rotation would probably be best to fix this issue.

can i ask, what kind of server do you need to support those numbers?

**Comment by JDBlackman** [comment]
> > @SlvrEagle23 The station can max out around 1k listeners at the best of times. I haven't cleared the logs in maybe 6months. Log rotation would probably be best to fix this issue.
> 
> can i ask, what kind of server do you need to support those numbers?

Feel free to DM me on Twitter @Jhawsh
or Discord Pascal#9999

**Comment by SlvrEagle23** [comment]
I'm closing this issue for now, as a great deal of work has gone into reducing the total burden of log files across the system, and what log files remain should be properly rotated, either by their own parent services, logrotate, or Docker, which has also been configured to use significantly less permanent log storage space for its own logs.

If anyone notices their log size ballooning for seemingly no reason, please feel free to open a new issue and let us know.

**Comment by dev1983** [comment]
below is the another issue. Which is a auto daily backup of azuracast. You need setup a cron job which can run daily to delete and only can keep 7 days backup. Which will solve your issue. 

root@azuraradio:/var/lib/docker/volumes/azuracast_backups# du -sh *
45G     _data
