### ISSUE TITLE
Local stream urls in station profile show proxy url when proxy is disabled and page is accessed via https

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#1036]
**Installation method**
Docker

**Host OS (for Docker installations)**
Debian 9

**Describe the bug**
When accessing the profile page via `https` but with web proxy disabled the local urls on the station profile show up as if the proxy is enabled.

**Expected behavior**
The urls should be shown on the profile page with the normal `https://<url>:<port>` instead of the `https://<url>/radio/<port>` scheme when accessing the page via `https` but with the web proxy disabled.

**Screenshots**
http://prntscr.com/ls6a75
http://prntscr.com/ls69zv

**Additional context**
This is due to [this condition](https://github.com/AzuraCast/AzuraCast/blob/master/src/Radio/Frontend/FrontendAbstract.php#L162) in the `Radio/Frontend/FrontendAbstract.php`

**Comment by SlvrEagle23** [comment]
@Vaalyn This is intentional due to the fact that there are known issues getting SSL to work smoothly with Icecast. Until these issues get worked out, the temporary workaround is to enable the proxy on any SSL page, otherwise the audio won't play or will trigger a mixed content warning.

**Comment by Vaalyn** [comment]
Can you recommend what issues on IceCast / IceCast KH I should follow to understand more about the SSL issues of IceCast?

**Comment by SlvrEagle23** [comment]
@Vaalyn The issue preventing SSL from working on Icecast was caused by the Letsencrypt Certbot container creating certs as the root user, which then couldn't be read by Icecast. The latest updates to the unified Docker container have, in part, also resolved these issues, so the SSL forced proxying for Icecast stations will no longer need to be in effect.
