### ISSUE TITLE
UFW does not seem to set port to enabled in docker

### ISSUE THREAD

**Issue by njmiano** [AzuraCast/AzuraCast#1037]
**Installation method**
Docker 

**Host OS (for Docker installations)**

Ubuntu 16.04.5 LTS
--

**Describe the bug**
I had previously installed the traditional way and I noticed that it altered by UFW settings to include all necessary ports. I uninstalled and followed all of the uninstall extra advice for clean uninstall (deleting DB and files). After installing with docker I notice the UFW ports are not set to enabled. 

**To Reproduce**
See above

**Expected behavior**
All UFW ports needed by Azuracast to be opened during install

**Relevant Logs**

ufw status                                       Status: active                                                                                                                                                    To                         Action      From                                      --                         ------      ----                                      5963                       ALLOW       Anywhere                                  5963 (v6)                  ALLOW       Anywhere (v6)
--

Note: 5963 is a port I leave open for other reasons

**Screenshots**
NA

**Device(s):**
NA

**Additional context**
Can you also mention the ports that are needed so that I can enable them manually?

**Comment by SlvrEagle23** [comment]
@njmiano Docker does not manage or control UFW on the host computer, as it has its own internal port forwarding and filtering mechanism and isn't necessarily aware of the host's configuration. Running UFW is fine, but you'll have to set up your own rules manually.

By default, the ports you'll want to clear through UFW are (all TCP):

- 22 (ssh)
- 80 (http)
- 443 (https)
- 8000-8999 (radio)

**Comment by njmiano** [comment]
Thanks.
