### ISSUE TITLE
😢 WEB DJ not working

### ISSUE THREAD

**Issue by arisgr** [AzuraCast/AzuraCast#1044]
![mstreurs](https://user-images.githubusercontent.com/36816914/49892020-a098b000-fe50-11e8-86d0-2f332fa0fe75.jpg)

😢Unfortunately I have this problem.
I just thought that's just on my server but no.
Apparently the problem is not mine, I tried a Docker installation, but it has the same problem with the Docker installation.

I only tried the Docker installation on the local network on a new VM that I created.

I'm sorry I do not speak English very well and that's why I use the Google translator. 🇩🇪🇬🇷

🤔if you press on the web DJ start stream then nothing happens just this error message comes when you look closely,

I also tried to stream in Firefox but it did not work either

**Comment by mmmnmnm** [comment]
Same here. I can connect via the butt client but not using the web interface. Depending on the browser I see a similar error message "WebSocket Error: Network Error 12045, The certificate authority is invalid or incorrect". Any idea?

**Comment by SlvrEagle23** [comment]
@arisgr There appears to be something wrong with your server's SSL settings, or with the proxy sitting between your server and the web.

This seems to be specific to your installation, so I would need more details about your specific setup to be able to diagnose it further.

**Comment by williambatson** [comment]
I'm connecting OK and do see music playing on my end -  the 2 problems i have are 1. no microphone available to choose/select and 2. when stream connected with no error, it does not actually broadcast - with or without autodj running.   The output played just not being broadcast.   Using SAM, Mixx or VDJ alll connect and broadcast for me fine.   Just with WebDJ nothing seems to happen once connected.  Any ideas?

**Comment by kinghoddy** [comment]
Mine isn't working too
I'm using the digitalocean instalation
In there, i use a load balancer to redirect to https
The wedj works fine on http but dosen'
t work on https through the load balancer

**Comment by mohmafia** [comment]
will this ever get fixed?

**Comment by SlvrEagle23** [comment]
@mohmafia Please reopen a new issue if you're continuing to experience a problem similar to this one, as this issue has been closed for several years.
