### ISSUE TITLE
The radio worked and then stopped working

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#1045]
> 2018/12/13 14:13:01 [switch_6363:3] Switch to random_6353.
2018/12/13 14:13:01 [random_6353:3] Switch to audio_to_stereo_6345.
2018/12/13 14:13:02 [lang:3] AzuraCast Raw Response: 
2018/12/13 14:13:02 [lang:3] AzuraCast Error: Delaying subsequent requests...
2018/12/13 14:13:04 [lang:3] AzuraCast Raw Response: 
2018/12/13 14:13:04 [lang:3] AzuraCast Error: Delaying subsequent requests...
2018/12/13 14:13:06 [lang:3] AzuraCast Raw Response: 
2018/12/13 14:13:06 [lang:3] AzuraCast Error: Delaying subsequent requests...
2018/12/13 14:13:09 [lang:3] AzuraCast Raw Response: 
2018/12/13 14:13:09 [lang:3] AzuraCast Error: Delaying subsequent requests...
2018/12/13 14:13:11 [lang:3] AzuraCast Raw Response: 
2018/12/13 14:13:11 [lang:3] AzuraCast Error: Delaying subsequent requests...
2018/12/13 14:13:14 [lang:3] AzuraCast Raw Response: 
2018/12/13 14:13:14 [lang:3] AzuraCast Error: Delaying subsequent requests...
2018/12/13 14:13:16 [lang:3] AzuraCast Raw Response: 
2018/12/13 14:13:16 [lang:3] AzuraCast Error: Delaying subsequent requests...
2018/12/13 14:13:19 [lang:3] AzuraCast Raw Response: 
2018/12/13 14:13:19 [lang:3] AzuraCast Error: Delaying subsequent requests...
2018/12/13 14:13:21 [lang:3] AzuraCast Raw Response: 
2018/12/13 14:13:21 [lang:3] AzuraCast Error: Delaying subsequent requests...

**Comment by SlvrEagle23** [comment]
@susl16c This is typically resolved by restarting broadcasting via "Utilities" > "Restart Broadcasting" on the station's management sidebar.
