### ISSUE TITLE
Error New Installation

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#1046]
Installation Method: Traditional Method
Host OS: Ubuntu 16.04 64-LTS

After running the installation script this is the error output. Can anyone help to fixed this issue? I try reinstall the OS but still same after running again the install script. Thank you

TASK [ufw : UFW - Enable SSH] ******************************************************************************************************************************************
ok: [localhost]

TASK [ufw : UFW - Turn on Firewall] ************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "ERROR: problem running ufw-init\nmodprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/2.6.32-042stab131.1/modules.builtin.bin'\nmodprobe: FATAL: Module nf_conntrack_ftp not found in directory /lib/modules/2.6.32-042stab131.1\nmodprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/2.6.32-042stab131.1/modules.builtin.bin'\nmodprobe: FATAL: Module nf_nat_ftp not found in directory /lib/modules/2.6.32-042stab131.1\nmodprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/2.6.32-042stab131.1/modules.builtin.bin'\nmodprobe: FATAL: Module nf_conntrack_netbios_ns not found in directory /lib/modules/2.6.32-042stab131.1\niptables-restore: line 4 failed\niptables-restore: line 77 failed\niptables-restore: line 36 failed\nip6tables-restore: line 4 failed\nip6tables-restore: line 138 failed\nip6tables-restore: line 36 failed\nsysctl: permission denied on key 'net.ipv4.tcp_sack'\n\nProblem running '/etc/ufw/before.rules'\nProblem running '/etc/ufw/user.rules'\nProblem running '/etc/ufw/before6.rules'\nProblem running '/etc/ufw/user6.rules'\n\n"}

RUNNING HANDLER [azuracast-user : send user notification] **************************************************************************************************************

RUNNING HANDLER [azuracast-db-install : send mysql notification] *******************************************************************************************************

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=66   changed=53   unreachable=0    failed=1

**Comment by CodeSteele** [comment]
I've seen similar problems where some VPS hosts are modifying the default Ubuntu installs to be missing files/applications/having tweaked kernels.

Which host are you currently on? Have you tried a docker install instead?
