### ISSUE TITLE
File docker-compose.yml

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#1048]
Tell me before it was like this

>     ports:
      - '81:80'
      - '4443:443'
I am changing how you are now in the file

>     ports:
      - '${AZURACAST_HTTP_PORT:-81}:80'
      - '${AZURACAST_HTTPS_PORT:-4443}:443'
And I do the editing as I had before, but I have nothing to work and swears at port 443, which I do not do, I do everything in accordance with what it was before. The fact is that my port 80 is busy and I was forwarding everything to port 81.

**Comment by SlvrEagle23** [comment]
@susl16c The reason these sections were updated is to allow you to customize these ports in the `.env` file. For more information, visit this page: https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#use-non-standard-ports

**Comment by susl16c** [comment]
Thanks really everything works, I also wanted to say that a stable version has already been released PHP 7.3

**Comment by SlvrEagle23** [comment]
@susl16c Yep, I follow PHP's releases very closely. We have no immediate reason to bump to 7.3 (we're already meeting security best practices as it is, for example) but I plan to update as soon as the binaries are available downstream.
