### ISSUE TITLE
Shoutcast relays are not public 

### ISSUE THREAD

**Issue by andrewbritton** [AzuraCast/AzuraCast#1050]
I have a traditional install on Ubuntu 18.04.1 and have the main output stream successfully streaming using auto DJ and it is listed on the shoutcast directory:
My Shoutcast server shows this:
Listeners: 1 of 450Peak: 1 [ kick all ] |   | Status: Public ID: 99411649 |   | Source: v1 [ kick ]
-- | -- | -- | -- | --
However any relays are private:
Listeners: 0 of 3 |   | Status: Private |   | Source: v1 [ kick ]
-- | -- | -- | -- | --
The shoutcast authhash is correct and is the same on the master and relay. 
The master is conficured to allow public relays:

path | "/radio.mp3"
-- | --
relayurl | ""
backupurl | ""
maxlisteners | "maxlisteners"
minbitrate | "minbitrate"
maxbitrate | "maxbitrate"
public | "default"
allowrelay | "1"
publicrelay | "1"

Shoutcast version on master and relays is:  
SHOUTcast Server v2.6.0.750/posix(linux x64)

**Comment by SlvrEagle23** [comment]
@andrewbritton Were you able to resolve this issue? Sorry for the delay in getting back to it; the holiday season had me out of commission for several days and I've been working on some other major issues.

**Comment by andrewbritton** [comment]
Hi there,

The shoutcast Authhash was not being automatically copied over to the new relay server, but manual insertion via shoutcast admin fixed it.

Do you think there is any mileage in a dedicated relay distro? Just bare bones to relay existing streams...

Thanks for all your work on Azuracast. It is a remarkable piece of work.

Andy

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
