### ISSUE TITLE
FTP: Permissions Denied

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#1053]
**Installation method**
Traditional

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
550 Failed to change directory. It seems like no permissions to reach all files at the FTP server. /var/azuracast/stations & /var/azuracast/www_tmp & /var/azuracast/geopip/ & /var/azuracast/servers 

I guess this happens because of the "azuracast" permissions.

I need this to see my .PHP log.

**Comment by CodeSteele** [comment]
As far as I know, we only have instructions on how to set up an FTP server for _docker_ installs, on traditional installs that's kind of going to be entirely determined by how you set up your FTP server and something you do on your own.

To point you in the right direction: make sure your FTP user has access to these directories, which can be done using groups or by changing your FTP config (depending on the FTP server used).

If you're just doing this once it may be easier to upload the files to your FTP home directory then log in via SSH and move the files using an elevated user account.
