### ISSUE TITLE
Adapter "App\Radio\Backend\Liquidsoap" cannot start; was already running.

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#1054]
**Installation method**
Traditional

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
Liquidsoap will not start anymore. If i click on "Start" or "restart" at Liquidsoap i get "Backend started". When i click on stop "Adapter "App\Radio\Backend\Liquidsoap" cannot start; was already running.". But the streams stays silcence and liquidsoap says: "Is not executed".

**To Reproduce**
I don't know. I updated, and restarted. I also had this in the past once and reinstalled everything.

**Relevant Logs**
**app.log**
> [2018-12-21 01:00:02] AzuraCast.INFO: Processing logs for station. {"id":1,"name":"STATION_NAME"} []
> [2018-12-21 01:24:58] AzuraCast.INFO: Adapter "App\Radio\Backend\Liquidsoap" stopped. {"station_id":1,"station_name":"STATION_NAME"} []
> [2018-12-21 01:24:59] AzuraCast.INFO: Adapter "App\Radio\Frontend\Icecast" stopped. {"station_id":1,"station_name":"STATION_NAME"} []
> [2018-12-21 01:25:00] AzuraCast.INFO: Adapter "App\Radio\Frontend\Icecast" started. {"station_id":1,"station_name":"STATION_NAME"} []
> [2018-12-21 01:25:01] AzuraCast.ERROR: SPAWN_ERROR: station_1:station_1_backend {"file":"/var/azuracast/www/src/Radio/AdapterAbstract.php","line":185,"code":0} []
> [2018-12-21 01:25:32] AzuraCast.ERROR: SPAWN_ERROR: station_1:station_1_backend {"file":"/var/azuracast/www/src/Radio/AdapterAbstract.php","line":185,"code":0} []
> [2018-12-21 01:25:34] AzuraCast.INFO: Adapter "App\Radio\Backend\Liquidsoap" stopped. {"station_id":1,"station_name":"STATION_NAME"} []
> [2018-12-21 01:25:38] AzuraCast.ERROR: SPAWN_ERROR: station_1:station_1_backend {"file":"/var/azuracast/www/src/Radio/AdapterAbstract.php","line":185,"code":0} []
> [2018-12-21 01:25:39] AzuraCast.INFO: Adapter "App\Radio\Backend\Liquidsoap" cannot start; was already running. {"file":"/var/azuracast/www/src/Radio/AdapterAbstract.php","line":173,"code":0} []
> [2018-12-21 01:27:37] AzuraCast.INFO: Adapter "App\Radio\Backend\Liquidsoap" cannot start; was already running. {"file":"/var/azuracast/www/src/Radio/AdapterAbstract.php","line":179,"code":0} []
> [2018-12-21 01:28:43] AzuraCast.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded {"file":"/var/azuracast/www/vendor/slim/slim/Slim/Http/Response.php","line":359,"code":5} []
> [2018-12-21 01:30:16] AzuraCast.NOTICE: HTTP client GET call to http://localhost:8000/admin/stats produced response NULL [] {"station":{"id":1,"name":"STATION_NAME"}}
> [2018-12-21 01:30:22] AzuraCast.INFO: Adapter "App\Radio\Backend\Liquidsoap" stopped. {"station_id":1,"station_name":"STATION_NAME"} []
> [2018-12-21 01:30:28] AzuraCast.ERROR: SPAWN_ERROR: station_1:station_1_backend {"file":"/var/azuracast/www/src/Radio/AdapterAbstract.php","line":185,"code":0} []
> [2018-12-21 01:38:01] AzuraCast.INFO: Adapter "App\Radio\Backend\Liquidsoap" started. {"station_id":1,"station_name":"STATION_NAME"} []
> [2018-12-21 01:38:07] AzuraCast.INFO: Adapter "App\Radio\Backend\Liquidsoap" cannot start; was already running. {"file":"/var/azuracast/www/src/Radio/AdapterAbstract.php","line":179,"code":0} []

**php_errors.log**
> [21-Dec-2018 01:38:46 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Return value of NowPlaying\Adapter\Icecast::_getXmlNowPlaying() must be of the type array, null returned in /var/azuracast/www/vendor/azuracast/nowplaying/src/Adapter/Icecast.php:126
Stack trace:
#0 /var/azuracast/www/vendor/azuracast/nowplaying/src/Adapter/Icecast.php(33): NowPlaying\Adapter\Icecast->_getXmlNowPlaying('<?xml version="...', '/radio.mp3')
#1 /var/azuracast/www/src/Radio/Frontend/Icecast.php(44): NowPlaying\Adapter\Icecast->getNowPlaying('/radio.mp3')
#2 /var/azuracast/www/src/Sync/Task/NowPlaying.php(313): App\Radio\Frontend\Icecast->getNowPlaying(Object(App\Entity\Station), NULL, true)
#3 [internal function]: App\Sync\Task\NowPlaying->loadRawFromFrontend(Object(App\Event\Radio\GenerateRawNowPlaying), 'radio-nowplayin...', Object(Azura\EventDispatcher))
#4 /var/azuracast/www/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Array, Array)
#5 /var/azuracast/www/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Slim\DeferredCallable->__invoke(Object( in /var/azuracast/www/vendor/azuracast/nowplaying/src/Adapter/Icecast.php on line 126

**Additional context**
Everything worked after the upate, but after restarting it didn't work anymore.

**Comment by SlvrEagle23** [comment]
@RemBdev Sometimes Supervisord gets confused...typically something like a system restart or going to `Utilities` > `Restart Broadcasting` from the station sidebar should fix it.

**Comment by RemBdev** [comment]
@SlvrEagle23 That didn't work. I had to restore a backup. But this happend for the second time.

**Comment by SlvrEagle23** [comment]
@RemBdev I've made some significant overhauls to the service manager process that will make restarting the station services both easier and less error prone. Let me know if this helps your process.

**Comment by ahzu** [comment]
I am having the same problem. I backed up and ran the updates. All stations are working fine except one. I have tried restarting the backend and starting the auto DJ service but it will not stay running. 

×App\Exception\Supervisor\AlreadyRunningException at /var/azuracast/www/src/Radio/AbstractAdapter.php L257: Liquidsoap cannot start
It is already running.

Above I get this error. It says "It is already running" but it will not start.

**Comment by saidelbehi** [comment]
Hello , i Have the Same Probleme after start new station . the firt station port 8000 the second 8010 the Third **8020 and Nginx 502 :(** and [App\Exception\Supervisor\BadNameException at /var/azuracast/www/src/Radio/AbstractAdapter.php L248: Icecast n'est pas reconnu comme un service.]
@SlvrEagle23 any issue please  my actual version AzuraCast • v0.12 Stable 

best regards

**Comment by cecov74** [comment]
resolved.... I need more HD space because when do update go to error for less space
