### ISSUE TITLE
Getting 500 error while refreshing Now Playing Data.

### ISSUE THREAD

**Issue by NeddyPlays** [AzuraCast/AzuraCast#1058]
Hi there,

Iam getting a 500 error while refreshing the Now Playing Data from the Dashboard:
Started after i updated AzuraCast.

An exception occurred while executing 'SELECT s0_.id AS id_0, s0_.song_id AS song_id_1, s0_.station_id AS station_id_2, s0_.playlist_id AS playlist_id_3, s0_.media_id AS media_id_4, s0_.request_id AS request_id_5, s0_.autodj_custom_uri AS autodj_custom_uri_6, s0_.timestamp_cued AS timestamp_cued_7, s0_.sent_to_autodj AS sent_to_autodj_8, s0_.timestamp_start AS timestamp_start_9, s0_.duration AS duration_10, s0_.listeners_start AS listeners_start_11, s0_.timestamp_end AS timestamp_end_12, s0_.listeners_end AS listeners_end_13, s0_.unique_listeners AS unique_listeners_14, s0_.delta_total AS delta_total_15, s0_.delta_positive AS delta_positive_16, s0_.delta_negative AS delta_negative_17, s0_.delta_points AS delta_points_18, s0_.song_id AS song_id_19, s0_.station_id AS station_id_20, s0_.playlist_id AS playlist_id_21, s0_.media_id AS media_id_22, s0_.request_id AS request_id_23 FROM song_history s0_ WHERE s0_.station_id = ? ORDER BY s0_.timestamp_start DESC LIMIT 1' with params [1]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 's0_.autodj_custom_uri' in 'field list'
AbstractMySQLDriver.php : 60

**Comment by SlvrEagle23** [comment]
@NeddyPlays Your database is out of date with the latest migrations. When you ran the update, did it properly execute the necessary database migrations? You may need to try updating again. Also you should specify (as the bug template suggests) whether you're running a Traditional or Docker installation.

**Comment by NeddyPlays** [comment]
Hi sorry,

iam using the Docker Installation. Tried the update again and get the next error in the database migration:
Migrating up to 20181211220707 from 20181126073334

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
[22-Dec-2018 18:03:58 UTC] PHP Fatal error:  Out of memory (allocated 1130364928) (tried to allocate 299008 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 158
2018/12/22 18:03:59 Command exited with error: exit status 255

**Comment by NeddyPlays** [comment]
There are 2654 songs in the database at the moment.

**Comment by SlvrEagle23** [comment]
@NeddyPlays I had received one other report of larger stations having issues making it through that one heavy album artwork migration, so I've made some optimizations to the media art migration process so it will use significantly less memory and report progress. This should be fixed for subsequent users.
