### ISSUE TITLE
How do I broadcast to a specific mountpoint on Azuracast?

### ISSUE THREAD

**Issue by danielrodrigotest** [AzuraCast/AzuraCast#1059]
HI, dear all.
I have problems broadcasting to a specific mount point. My server has 3 mount points like this
server.com/nationalsignal (default)
server.com/region2(independent)
server.com/region3(independent)
In previous versions, I could only broadcast to a specific version. However, when I send the audio to the server, the 3 mount points have the same audio. I tried many ways to broadcast to an specific mount point and it was impossible. 
I'm using ubuntu with docker. 
I really hope to receive an answer.
Thanks in advanced

**Comment by SlvrEagle23** [comment]
@danielrodrigotest For the purposes of fixing this issue, it's important to understand the distinction between a local mount point (hosted on the same server that AzuraCast is running on) and a remote relay (hosted elsewhere and configured via the Remote Relays) section.

Can you let me know which of these two you are having trouble with, and how you have it configured? There may be some issues with our connection adapters. I'm happy to help resolve the issue if you can provide some more details about how you're using the software.

**Comment by danielrodrigotest** [comment]
Thanks for your reply. I'm using local mount point port with icecast. I configured the first mount point with autoDJ/live dj. The second mount point has another name /region2 (as an example). My idea is that the mountpoint 1 (/nationalwide) would work as independent and /region2 independent. When I try to send the audio, boths mountpoints have the same audio.
