### ISSUE TITLE
Web Dj page only shows background image 

### ISSUE THREAD

**Issue by acerome** [AzuraCast/AzuraCast#1060]
Hello I've run into an issue where the web dj is not loading correctly. I've tried updating and nothing has changed.
![image](https://user-images.githubusercontent.com/9618292/50381435-9777c200-064c-11e9-8a6c-586e6665d6ad.png)

**Comment by LordHelmchen666** [comment]
Had the same issue. I updated my Ubuntu and it worked again.

**Comment by SlvrEagle23** [comment]
@acerome @LordHelmchen666 This issue is very likely caused by our CDNJS issue. You can follow ticket #1066 for updates and more information.
