### ISSUE TITLE
Song is playing while dj stream is active

### ISSUE THREAD

**Issue by mmmnmnm** [AzuraCast/AzuraCast#1061]
Hi, 

when a dj connects (via butt) and starts streaming, scheduled songs continue playing "in the background" (you can see it on now_playing via the API, and also the default player shows the song's data). I say "in the background" because the radio is playing the audio coming from the dj stream, which is good :) Why is that? 

Thanks, 

Peter

**Comment by SlvrEagle23** [comment]
@mmmnmnm Are your DJs connecting to Liquidsoap (i.e. to a port ending in 5 or 6, i.e. 8005/8006) or to Icecast/SHOUTcast (i.e. to a port like 8000/8001)? The latter will always result in the AutoDJ continuing to run in the background, as the AutoDJ isn't aware of any live connection present. The former, connecting to Liquidsoap itself, should result in the AutoDJ signal "pausing" while the live DJ is active.

**Comment by mmmnmnm** [comment]
@SlvrEagle23: DJs are connecting through port 8005. Just checked it, you're right, the Auto DJ signal is pausing but the elapsed time continues running (on the radio's admin interface, on the public page and also on the API). This is what confused me and I thought that song is being played in the background. Is it a bug?

**Comment by SlvrEagle23** [comment]
@mmmnmnm There's a known issue where when DJs connect, it won't pick up their first metadata update, particularly with certain streaming software like BUTT. The solution is to send another metadata update immediately after connecting (i.e. rapidly change the song being played), but that's an issue that is upstream from us.

**Comment by mmmnmnm** [comment]
@SlvrEagle23: can you recommend a reliable streaming software which is not a DJ software (like Mixxx)? What do you mean by sending a metadata update? Our workaround is now that the player checks (using the nowplaying API) the 'live' tag and displays streamer_name if it's true (instead of displaying the song's name). Plus, we removed the elapsed time display. BUTT reliably sends the DJ's account name and Azuracast correctly matches it with the DJ's display name (filled into streamer_name).

**Comment by SlvrEagle23** [comment]
@mmmnmnm Right now, our [list of compatible streaming software](https://github.com/AzuraCast/azuracast.com/blob/master/StreamingSoftware.md) is rather small, as we're working on expanding it and currently I can't afford the licenses for other software to ensure their compatibility with ours, and my requests to the software makers for evaluation copies have largely been rejected.

By "send a metadata update", I mean, in BUTT's case, connect and then manually update the metadata associated with the DJ stream. The AutoDJ will receive and process this second metadata update.

**Comment by mmmnmnm** [comment]
@SlvrEagle23: thanks, I found in BUTT the "Update song" settings under the Stream tab and it indeed updates the song's name in the now_playing tag. 

For the eval copies: that's a shame. Let me know if we can help somehow. We can also contact them saying that our DJs may be using their product and want to stream live shows to a radio based on Azuracast.
