### ISSUE TITLE
Updating Shoutcast Server

### ISSUE THREAD

**Issue by NeddyPlays** [AzuraCast/AzuraCast#1065]
Hi there,

I can't find where i can update my ShoutCast server in Azuracast.

**Comment by SlvrEagle23** [comment]
@NeddyPlays You can now update your installed SHOUTcast version even when another version is already installed. This will let people install the latest 2.6.0 version (not recommended on account of its freemium status) or, better yet, downgrade to 2.5.5 if they can find a downloadable version of it.
