### ISSUE TITLE
CDN Asset CORS Blocking Superissue

### ISSUE THREAD

**Issue by SlvrEagle23** [AzuraCast/AzuraCast#1066]
See: cdnjs/cdnjs#13165

Currently, our upstream host for a number of scripts and stylesheets is experiencing intermittent issues with various scripts failing to serve due to a lack of "Access-Control-Allow-Origin" headers.

We are aware of this issue, and unfortunately there is nothing we can easily do to resolve the issue on our end. We moved away from carrying these assets on every AzuraCast installation to save space and make for easier maintenance, and generally speaking, referring to a global CDN is actually very advantageous, as the CDN is highly available, can set long cache times and you're more likely to have the library already in your browser if it's used somewhere else on the web pointing to the same CDN. The reason we went with CDNJS is because they're backed by CloudFlare, which normally indicates high reliability and stability, but this issue alone has reduced their uptime for 2018 to under "Three Nines" (99.9%) and has caused significant issues for us.

This issue is meant as both an announcement that we are aware of this issue, a pointer to the upstream issue to follow for updates on the situation, and a tracker for progress on our potential resolution for this issue.

The likely resolution will be to bring assets back to being locally hosted again, but instead of committing code directly into the repository, we will bundle NPM and Yarn directly with every installation so that the installation process will fetch the dependencies upon installation/update. This will add some time and size to the install/update process, but will make each AzuraCast instance more resilient against third-party failures.

**Comment by CodeSteele** [comment]
Issue on the CDNJS team here: https://github.com/cdnjs/cdnjs/issues/13165

The weird hot-potatoing of the issue with no real progress towards resolution is pretty worrying.

**Comment by CodeSteele** [comment]
Looking at the upstream issue, there is no ETA on resolving it while they are trying to find out __who can even address the issue__, a bit rough for us because we're just kind of broken until they resolve this or we update our entire pipeline.

**Comment by jimaek** [comment]
You can alway switch to https://www.jsdelivr.com/
Its built for production use and is backed by a company and multiple CDN providers

**Comment by jimaek** [comment]
>and it appears that jsdelivr has had similar issues of cloudflare, and cloudflare alone biting them

That only affected the site and none of our users. Our system would automatically detect downtime and remove Cloudflare from rotation if the same problem happened on the CDN itself. Plus we always have the option of removing/adding CDNs as we see fit. We are the only CDN that has this flexibility.


> If this CDNJS issue ends up being a platform issue -- what prevents jsdelivr having the same issues with its Paris and Amsterdam instances having a bad software bug deployed to them?

The problem they are having is definitely not with CF but with their origin. 
Our code is 100% covered with tests and each merge runs all edge cases and different use-cases possible to verify nothing breaks. Only after that we run manual deploys to our cluster. Reversing to a previous version is also very easy.
In addition we always monitor all of our servers and services and act immediately to any problems.  jsDelivr is operated by https://prospectone.io/ too. It's not a side project so jsDelivr does not suffer from the same problems as cdnjs e.g. trying to figure who has access where to check a bug and then trying to get in contact with him

**Comment by MartinKolarik** [comment]
@CodeSteele those are still valid concerns though and we could probably do a better job addressing them in our documentation.

**Comment by SlvrEagle23** [comment]
@jimaek @MartinKolarik Thank you all for reaching out and offering an alternative service. It appears from your profiles that you work directly with JSDelivr. This might be something worth disclosing from a "responsible disclosures" standpoint when advocating for products.

In this case, regardless of whether we're using CDNJS or JSDelivr or anyone else, the one core argument remains the same: these services represent one singular point of failure (regardless of the number of global high-availability nodes, every installation still refers to a singular fallible external URI) that, when down or malfunctioning, is capable of pulling every individual self-hosted AzuraCast instance across the web down at the exact same time.

Currently, _nothing else_ has that ability. AzuraCast is built to be entirely self-contained in every regard, with all of the software needed available on the same machine as the installation itself. If our update server goes down, the installations all can gracefully handle this and will cache previous successful requests.

I made the decision to move to CDNJS because I was tired of the pain of managing dependencies in the codebase itself. If we pull directly from NPM packages, we wind up with the bloat of a ton of source code files that will never get used on every installation, and if we curate the distributed versions, we have to do a lot of housekeeping work to keep that up-to-date and versioned. It's kind of a pain.

However, the pain of that is far less than the pain of having every single AzuraCast instance across the web become nonfunctional because of something outside my control, particularly something that depends on someone to fix who is off on holiday vacation.

This was an embarrassing and painful lesson in why AzuraCast's decision to be self-contained was a _good_ one and should've remained in place for the static assets, and I apologize to anyone who was inconvenienced by the fact that it didn't.

The assets have been re-localized after a not insignificant amount of work on my part here on Christmas Eve and Christmas day. This resolves the issue in its entirety and all users are encouraged to update ASAP.

Thank you all for your continued patience and support.
