### ISSUE TITLE
station-watcher memory leak?

### ISSUE THREAD

**Issue by Scraticus** [AzuraCast/AzuraCast#1070]
**Installation method**

_Docker_

**Host OS (for Docker installations)**

_Ubuntu Bionic 18.04 latest updates_

**Describe the bug**

_Memory high in station-watcher_

**To Reproduce**
Run station normally, i don't believe i've done anything else

**Expected behavior**

_Reasonable Memory usage_

**Relevant Information**

_When doing my monthly addition of songs and checkups of the server, I have noticed that the 'station-watcher' is consuming a lot (45%) of memory, compared to all of the other modules in AzuraCast.

I am on docker for the moment, but should I set a cron to reset this every so often?

screenshot from top._

![image](https://user-images.githubusercontent.com/11047768/50459364-56d8bb00-0962-11e9-91c6-9b4d26941a5a.png)

**_Happy Holidays_**

**Comment by Vaalyn** [comment]
I've also seen that the memory used by the station watcher will slowly increase over time. This is what my monitoring is showing: https://prnt.sc/mnknfb

When I look at the memory that the processes in the stations container use I saw the station watcher using ~250MB RAM after a few days. I'm also not that versed in Golang but my guess is that this could be memory leaked by the http requests. When I looked at the code I saw that on the response in [this line](https://github.com/AzuraCast/station-watcher-go/blob/master/main.go#L52) we never call `resp.Body.Close()` on it (at least not directly, I'm not sure if anything else indirectly closes the connection). On [StackOverflow I read](https://stackoverflow.com/questions/33238518/what-could-happen-if-i-dont-close-response-body-in-golang) that you should close http connections to avoid memory leaks.

**Comment by SlvrEagle23** [comment]
@Vaalyn You're likely right that this is a contributing factor.

In this case, though, frankly the larger issue is that the little station watcher app presents a larger maintenance headache than the problem it solves of slightly improving the responsiveness of the "Now Playing" API to song/listener count updates. There are other ways we can go about improving that responsiveness (including having Liquidsoap itself send us any metadata changes, which would accomplish the same purpose without running another application and without any polling involved) that we should pursue instead. Also, I never much liked that it was a Docker-only feature that never got rolled out on traditional installs, creating a gap between the user experience on both.

So I'm pulling it entirely for now. The long-running stability of stations is far more important to me as a general priority, and that's endangered by having another process for such a small function.
