### ISSUE TITLE
Song request, no wait times

### ISSUE THREAD

**Issue by stemvantwente** [AzuraCast/AzuraCast#1071]
Auto Dj does allow listeners request instantly, i have it on 1 song per listener (ip) each 15 minutes but does not work anymore, the listeners now can request all they want.

Any ideas?

**Comment by SlvrEagle23** [comment]
@stemvantwente Are you testing this as your own logged-in user account? If you're a logged in user with the appropriate permissions, you won't be subjected to any wait times when submitting requests.

**Comment by stemvantwente** [comment]
@SlvrEagle23  yeah haha didnt know this! thank you for the info, tryed request via my iphone and then the 15 min wait time works.

can be closed
Greets
