### ISSUE TITLE
Thank you. Broadcaster reached 1,000 listeners

### ISSUE THREAD

**Issue by multi023** [AzuraCast/AzuraCast#1072]
Hi,

These Christmas days, our radio station has reached 1,001 listeners. (In that amount, it was cut and fell to 590 listeners), more I imagine it will have been by our structure.

This post is to thank all those who have made it possible for us to enjoy AzuraCast.

Thank you thousands and ...Happy Holidays!

**Comment by SlvrEagle23** [comment]
@multi023 Thank you for the kind words, and I hope you and your listeners had a wonderful holiday season. :)
