### ISSUE TITLE
Hello I need help

### ISSUE THREAD

**Issue by angelpipo1968** [AzuraCast/AzuraCast#1076]
**Installation method**

**Host OS (for Docker installations)**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by angelpipo1968** [comment]
azuracast works perfect Server shoutcast tambienel problem is that when I put Authhash shoutcast notrasnmite that I have to do

**Comment by CodeSteele** [comment]
Not quite sure what your problem is, can you provide some screenshots?

**Comment by JDBlackman** [comment]
This issue seems to be related shoutcast. Shoutcast has been experiencing issues with there DNAS and connecting the public listing directory. If this the case I suggest you take this up on the shoutcast forum.
