### ISSUE TITLE
Crossfade per playlist

### ISSUE THREAD

**Issue by nickdodd25** [AzuraCast/AzuraCast#1077]
Hi there again,

I was curious if it was possible to make the crossfade settings so they could be configurable per playlist?

For example i have my promo playlist setup that just says slogans once every half hour, then it plays music from two other playlists the rest of the time. But would it be possible to make it so there is no crossfading when the promo's are upnext/currently playing but when its jut playing music then crossfade works.

Thanks,
Nick

**Comment by SlvrEagle23** [comment]
@nickdodd25 While this would be nice to have, I'm currently unaware of any way to allow this within the confines of our AutoDJ software, Liquidsoap. Fading is handled once at a global level for the entire station, so any rules overridden on a per-playlist basis would need to be configured somewhere that currently doesn't exist.

If anyone is able to provide details on how we might be able to implement this feature, we'd be happy to entertain it as a possibility, but for now we have to close it as not technically feasible.

**Comment by rubensben** [comment]
To maybe bring a direction about the issue as I'm also looking for this feature : https://github.com/savonet/liquidsoap/issues/1086

**Comment by koningcool** [comment]
I also!
