### ISSUE TITLE
Move music to subfolder

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#1079]
**Is your feature request related to a problem? Please describe.**
It is possible to create new folders in folders, but it isn't possible to move existing music to a subfolder.

**Describe the solution you'd like**
The move button should also show subfolders

**Describe alternatives you've considered**
Re-upload the music. But it would be nice if it is possible.

**Additional context**
Just trying to make it more easy to work with Azuracast.

**Comment by SlvrEagle23** [comment]
Moving files has been implemented!
