### ISSUE TITLE
IS THERE A FIX TO READ THE STATISTICS FROM OUTSIDE AZURACAST?

### ISSUE THREAD

**Issue by AleAmla987** [AzuraCast/AzuraCast#1082]
IS THERE A FIX TO READ THE STATISTICS FROM OUTSIDE AZURACAST?

**Comment by CodeSteele** [comment]
I'm not _quite_ sure what issue you are referring to, can you describe the problem? Provide screenshots or log files?

**Comment by defcon8** [comment]
@AleAmla987, i'm not an Azuracast expert, but if you want to access the statistics from outside Azuracast, the API is probably the way-to-go.

**Comment by AleAmla987** [comment]
> @AleAmla987, i'm not an Azuracast expert, but if you want to access the statistics from outside Azuracast, the API is probably the way-to-go.
