### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by defcon8** [AzuraCast/AzuraCast#1083]
**Is your feature request related to a problem? Please describe.**
One-way factor authentication for the administration panel is unsafe.

**Describe the solution you'd like**
Implement two-factor authentication, for example Google Authenticator. (RFC6238)
https://github.com/PHPGangsta/GoogleAuthenticator

**Describe alternatives you've considered**
Blocking access to the web panel in the firewall.

**Comment by CodeSteele** [comment]
Duplicate of #765
