### ISSUE TITLE
CPU charge

### ISSUE THREAD

**Issue by impli-osx** [AzuraCast/AzuraCast#1084]
**Installation method**
Docker

**Host OS (for Docker installations)**
Debian 9.5

**Describe the bug**
Since the 18 december, the CPU charge is equal to 50%. Since the 22 december, charge is over 100%. Before those dates, charges are under 2%.

**To Reproduce**
Make update & enjoy.

**Expected behavior**
Reduce the CPu charge.

**Relevant Logs**
No logs for this. Seen on the panel of the dedicate server.

**Screenshots**
Not avaible for the moment. But I can take this if necessary.

**Device(s):**
 - Device: Desktop
 - OS: W10/Debian9.5
 - Browser: Firefox 64.0
 - Version: 

**Additional context**
Radio on BETA test. Less than 5 users per day. 49 songs on one playlist. Use a custom webplayer and a cutom webirc bot for request since 5 months.
For logs, request.

Thank's and have a happy new year.

**Comment by CodeSteele** [comment]
Most of the CPU load typically is due to transcoding, and is typically driven by number of stations. However for a single station that's a really high load.

Can you run `docker stats` and show us the output?

**Comment by impli-osx** [comment]
Ok ... New year is a hard moment for me ...

Azuracast is about 7% load on the server. WebIRC bot is about 90% ...
Restart IRC bot and it's all right.


Sorry for the report.
