### ISSUE TITLE
Reorganize the player layout

### ISSUE THREAD

**Issue by joaoherberto** [AzuraCast/AzuraCast#1087]
I understand that there is work in progress to add additional players to the public page, and the current one works just fine, but is a little disordered. I would like to submit the changes below in the images. Also, on long album and song names, the text over flow runs off of the page, especially on mobile devices. 

On mobiles screens, Chrome and Firefox, the player is not centered. 

Also, instead of hiding the volume controls, I think just grey it out until the player starts would look more aesthetically pleasing. 

Before
![player-before](https://user-images.githubusercontent.com/3608446/50695489-b03f8a80-0ff1-11e9-9c7c-b694c5d4dbc4.png)

After
![player_gui](https://user-images.githubusercontent.com/3608446/50695490-b03f8a80-0ff1-11e9-8e6c-150e0be1d274.png)

**Comment by CodeSteele** [comment]
@joaoherberto did you touch the code for this at all or just photoshop this around? If you did code it -- did the fix the mobile issues?

@SlvrEagle23 opinions? I'm kind of mixed between "well the improvement may be sort of _marginal_ all things considering" as far as the layout changes go. I think a larger discussion around player improvements would be nice.

**Comment by joaoherberto** [comment]
> @joaoherberto did you touch the code for this at all or just photoshop this around? If you did code it -- did the fix the mobile issues?
> 
In all honesty, I did look at the code and I just could not find where the player code was so I just ran the old copy and paste.

**Comment by SlvrEagle23** [comment]
@joaoherberto @CodeSteele I like the idea of making the player more intuitively "player-like" in general, though any improvement like this should be bundled into a larger project where we allow users to switch between their available local/remote mount points/relays as well.

**Comment by joaoherberto** [comment]
> @joaoherberto @CodeSteele I like the idea of making the player more intuitively "player-like" in general, though any improvement like this should be bundled into a larger project where we allow users to switch between their available local/remote mount points/relays as well.

Yes, I think that would definitely be a benefit to the user experience. In my current project, giving the user the option to switch between the two different stations would be very convenient.

Would making the default player page a global one make more sense?

**Comment by joaoherberto** [comment]
@SlvrEagle23 Well I can see how in certain circumstances that would be wanted, for sure, but I can also see the need to have them show it.

Is it possible to just have an option to say "enable global player"? If unchecked  it would leave things as they are, if checked it would default to the global player but with the ability to still access individual mounts with player.
Just thinking out loud...

**Comment by AnUnknowsTygerosy** [comment]
Can I ask, where you find code of public page?

**Comment by SlvrEagle23** [comment]
@joaoherberto The current layout of the player has been bothering me for a while, especially since the volume controls only appear when you actually start playing, which doesn't let you change the volume before initially hitting play, which could cause some major problems.

I've restructured the player to look very similar to how you described, with the play button, playback time and volume controls always shown next to each other.
