### ISSUE TITLE
Listeners "graphical view" unable to load historical data

### ISSUE THREAD

**Issue by defcon8** [AzuraCast/AzuraCast#1088]
**Version**
 v0.9.1, #a42ae53 (2019-01-04 17:32)

**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
Listeners "graphical view" unable to load historical data

**To Reproduce**
1. Login to web panel
2. Go to Reports > Listeners
3. Choose any other period/date then "Live Listeners" from the dropdown. In my case "Today". (previous days work fine)
4. Nothing happens (unwanted behaviour)

**Expected behavior**
See update of graphical view

**Screenshots**
<img width="1280" alt="screenshot 2019-01-04 at 19 53 25" src="https://user-images.githubusercontent.com/3636349/50705370-e6fdbb00-105a-11e9-95f5-f8f85fb8ad88.png">

**Device(s):**
Not related to a device.

**Additional context**
It seems to me that somehow today a malformed IP address is written to the database on which the back-end code throws an exception.. is there a workaround, maybe manual removal of this record?

**Comment by defcon8** [comment]
I have been digging a bit further, the screenshot below does "select listener_ip from listener;" on mariaDB and reveals some empty strings and IPv6 adresses as IP. 

<img width="547" alt="screenshot 2019-01-06 at 12 45 42" src="https://user-images.githubusercontent.com/3636349/50735548-32c27880-11b1-11e9-80eb-d02cfb0b1da8.png">

**Comment by SlvrEagle23** [comment]
@defcon8 I'm not sure why you're winding up with empty IP address fields in your database, but I've improved the error handling on the retrieval end to ensure that the results are still visible even if invalid/missing IPs are present in the data set.
