### ISSUE TITLE
See changelog of pending "update"

### ISSUE THREAD

**Issue by defcon8** [AzuraCast/AzuraCast#1089]
Hi,

Is there a way that I can see which commits/bugfixes/features are included in the pending update? Currently only the amount of updates is mentioned. If this information is added I can make a better decision between updating right away, or postponing the updates..

<img width="1160" alt="screenshot 2019-01-06 at 17 33 05" src="https://user-images.githubusercontent.com/3636349/50738966-aed0b680-11d9-11e9-828a-a1b7b3ddac71.png">

**Comment by CodeSteele** [comment]
@defcon8 would this be something that just pulling the git logs seem like a viable solution?

**Comment by defcon8** [comment]
@CodeSteele : Hmm, yes I can work with that, thank you for the workaround. Still I think it would be very useful to see the descriptions of the actual updates in the GUI.

**Comment by CodeSteele** [comment]
Well I'm also pondering if we should just expose that to the new update UI. Those "5 updates" are actually 5 individual git commits.

We'd just see about exposing that on the UI or something, considering we're doing rolling releases we don't really have much of a changelog outside of just git.

**Comment by SlvrEagle23** [comment]
@defcon8 The best way for us to do this would just be to have the update server respond with the specific commit message of the rolling updates between your current version and the latest. It's definitely possible, and for people on the "rolling release" schedule may indeed be very helpful.

**Comment by SlvrEagle23** [comment]
@defcon8 I've updated the central update server to return a list of commit messages along with its update data, which will now be shown if the number of commits is less than 15 between your current version and the latest rolling release (to avoid cluttering the view for more out-of-date installations).
