### ISSUE TITLE
Cant use port 9000 and other

### ISSUE THREAD

**Issue by suricloud** [AzuraCast/AzuraCast#1090]
**Installation method**

Docker
**Host OS (for Docker installations)**

Centos 7 , Debian 9
**Describe the bug**

Hi,

I did 2 new installs on centos7 en debian 9 server. Azuracast installed succesfully.
I want to stream my stations on different port like 9000.
I did put the port 9000:9000 and  9001:9001 in docker-compose.override.yml file.
I updated docker,rebooted the server.But still azuracast doesnt play on the port i put for the station.
The administration link of the station gives me 404 eror page.

What to do?

The administration link of the station gives me 404 eror page.
**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by suricloud** [comment]
I just noticed,when i set no to Always Use HTTPS in system setting.
The stream plays on the port,but when ssl is on it doesnt.
I dont have anything on the server installed only azuracast.

**Comment by CodeSteele** [comment]
> I did put the port 9000:9000 and 9001:9001 in docker-compose.override.yml file.

Have you tried `9000:8000` and `9001:8001` because those are still on port 8000 on the back end IIRC.

**Comment by suricloud** [comment]
I do get this erro when adding those ports:

ERROR: for azuracast_stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (57df5c6b3a2178a9e4cddf3543e871ca8c910fca824a1403ef42e76ae1768109): Bind for 0.0.0.0:9001 failed: port is already allocated

ERROR: for stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (57df5c6b3a2178a9e4cddf3543e871ca8c910fca824a1403ef42e76ae1768109): Bind for 0.0.0.0:9001 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
Starting azuracast_stations ...
azuracast_mariadb_1 is up-to-date
azuracast_influxdb_1 is up-to-date
Starting azuracast_stations      ... error
azuracast_redis_1 is up-to-date

ERROR: for azuracast_stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (1199169aa872bd33adf45602adf073cf3935951a84e87c78c4a035a926b5464e): Bind for 0.0.0.0:9000 failed: pCreating azuracast_letsencrypt_1 ... done

ERROR: for stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (1199169aa872bd33adf45602adf073cf3935951a84e87c78c4a035a926b5464e): Bind for 0.0.0.0:9000 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
Update complete!

**Comment by suricloud** [comment]
I think there is a issue with when ssl enabled it doestn work.

**Comment by SlvrEagle23** [comment]
@suricloud The nginx proxy functionality is hard-coded to only work in the port range from 8000 to 8999. We can't include every arbitrary port that users might want to use, because then it would likely inadvertently allow proxying of important web services that shouldn't be exposed to the web.

You can always upload a custom nginx configuration as a volume mounted to the `nginx` service that overrides the port configuration. The relevant configuration section is here:
https://github.com/AzuraCast/AzuraCast/blob/master/util/ansible/roles/nginx/templates/default.j2#L43-L59
