### ISSUE TITLE
is_live Won't update.

### ISSUE THREAD

**Issue by c0de786** [AzuraCast/AzuraCast#1091]
I have issue with streamer information. When Streamer connects the now playing goes blank and the webhook gives message of Stream is offline.

2019/01/06 16:05:12 [lang:3] Authenticating DJ:rj_demo
2019/01/06 16:05:12 [lang:3] AzuraCast Live Connected Response: ["received"]
2019/01/06 16:05:12 [threads:3] Created thread "harbor source feeding" (2 total).
2019/01/06 16:05:12 [um_247_input_streamer:3] Decoding...
2019/01/06 16:05:12 [lang:3] AzuraCast DJ Auth Response: true
2019/01/06 16:05:12 [um_247_input_streamer:3] New metadata chunk ? --  - .
2019/01/06 16:05:17 [um_247_live_fallback:3] Switch to audio_to_stereo_6261 with transition.
2019/01/06 16:07:53 [um_247_live_fallback:3] Switch to blank_6264 with forgetful transition.
2019/01/06 16:07:53 [dummy:3] Source failed (no more tracks) stopping output...

It happens on Butt Broadcaster, Audiohijack broadcaster as well. Well written meta data provided.

**Comment by SlvrEagle23** [comment]
@c0de786 This is very likely related to #867, a long-running and known issue. You should follow that for updates. The easy resolution for streamers using BUTT is to send a second metadata update immediately after connecting, which will be processed correctly by the stream software.
