### ISSUE TITLE
Liquidsoap error: SPAWN_ERROR: station_2:station_2_backend

### ISSUE THREAD

**Issue by webma5ter23** [AzuraCast/AzuraCast#1092]
Installation method: Docker
Ubuntu 16.04

After editing the playlists, the autodj does not work, it can not be restart.

Log liquidsoap.log file:

`2019/01/07 03:54:23 [main:3] Liquidsoap 1.3.4
2019/01/07 03:54:23 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.3.5 dtools=0.4.1 duppy=0.8.0 cry=0.6.0 mm=0.4.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.3 flac.ogg=0.1.3 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 taglib=0.3.3 ssl=0.5.7 camomile=1.0.1 faad=0.4.0
2019/01/07 03:54:23 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/01/07 03:54:23 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/01/07 03:54:23 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/01/07 03:54:23 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/01/07 03:54:26 >>> LOG START
2019/01/07 03:55:28 >>> LOG START
2019/01/07 03:55:29 >>> LOG START
2019/01/07 03:55:31 >>> LOG START
2019/01/07 03:55:35 >>> LOG START
2019/01/07 04:01:22 >>> LOG START
2019/01/07 04:01:23 >>> LOG START
2019/01/07 04:01:25 >>> LOG START
2019/01/07 04:01:28 >>> LOG START
2019/01/07 04:03:09 >>> LOG START
2019/01/07 04:03:11 >>> LOG START
2019/01/07 04:03:13 >>> LOG START
2019/01/07 04:03:16 >>> LOG START
2019/01/07 04:03:25 >>> LOG START
2019/01/07 04:03:26 >>> LOG START
2019/01/07 04:03:29 >>> LOG START
2019/01/07 04:03:32 >>> LOG START
2019/01/07 04:03:43 >>> LOG START
2019/01/07 04:03:44 >>> LOG START
2019/01/07 04:03:46 >>> LOG START
2019/01/07 04:03:49 >>> LOG START
2019/01/07 04:06:21 >>> LOG START
2019/01/07 04:06:22 >>> LOG START
2019/01/07 04:06:24 >>> LOG START
2019/01/07 04:06:27 >>> LOG START
2019/01/07 04:06:40 >>> LOG START
2019/01/07 04:06:41 >>> LOG START
2019/01/07 04:06:43 >>> LOG START
2019/01/07 04:06:46 >>> LOG START
2019/01/07 04:12:52 >>> LOG START
2019/01/07 04:12:54 >>> LOG START
2019/01/07 04:12:56 >>> LOG START
2019/01/07 04:12:59 >>> LOG START`

**Comment by webma5ter23** [comment]
help please

**Comment by SlvrEagle23** [comment]
@webma5ter23 There's nothing in that log that indicates anything is going wrong. What happens if you just reboot the machine?

**Comment by webma5ter23** [comment]
It works well, also the playlist gives error if I add a remote address.

Example: https://str2.openstream.co/215  or http://str2.openstream.co/215

**Comment by SlvrEagle23** [comment]
@webma5ter23 So the only thing causing Liquidsoap to fail to boot is using a remote URL playlist?

**Comment by NLLucifer** [comment]
Same problem here. Not using an remote URL/file. Do have the option enabled to save the streamed data to an ogg file.
Output from Docker logs:
`
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [threads:3] Created thread "generic queue #1".
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [threads:3] Created thread "generic queue #2".
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [threads:3] Created thread "non-blocking queue #1".
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [threads:3] Created thread "non-blocking queue #2".
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [harbor:3] Adding mountpoint '/' on port 8015
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [playlist_nonstop(dot)m3u:3] Loading playlist...
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [playlist_nonstop(dot)m3u:3] No mime type specified, trying autodetection.
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [playlist_nonstop(dot)m3u:3] Playlist treated as format application/x-mpegURL
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [playlist_nonstop(dot)m3u:3] Successfully loaded a playlist of 55 tracks.
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [entertainmentradio_local_1:3] Connecting mount sid#1 for @127.0.0.1...
stations_1_ec748fd73e05 | 2019-02-06 15:38:52INFO[SRC 127.0.0.1:38044 sid=1] SHOUTcast 1 source connection starting.
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [entertainmentradio_local_1:3] Connection setup was successful.
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [threads:3] Created thread "wallclock_main" (1 total).
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/entertainmentradio/media/Normale Non-Stop/jeckyll_a_hyde_-_freefall.mp3".
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [entertainmentradio_live_fallback:3] Switch to entertainmentradio_playlist_fallback.
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [entertainmentradio_playlist_fallback:3] Switch to blank_6343.
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [playlist_nonstop(dot)m3u:3] Prepared "/var/azuracast/stations/entertainmentradio/media/Normale Non-Stop/jeckyll_a_hyde_-_freefall.mp3" (RID 1).
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [entertainmentradio_playlist_fallback:3] Switch to switch_6342 with transition.
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [dummy:3] Source failed (no more tracks) stopping output...
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [(dot)(dot)/streams/stream_%H%M(dot)ogg:3] Source failed (no more tracks) stopping output...
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [switch_6342:3] Switch to random_6332.
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [random_6332:3] Switch to audio_to_stereo_6330.
stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [main:3] Shutdown started!`
