### ISSUE TITLE
Song Change Problem With 2 or more playlists

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#1093]
**Installation method**
TRADITIONAL

Hello, before I had only one playlist per channel and everything worked fine, since I put a second playlist I noticed that when the song is changed, the songs are cut by removing the effect (fade-in-out and ...) and for a few milliseconds another song is heard.
How do you solve the problem? It is very annoying. I await answers!

**Comment by SlvrEagle23** [comment]
@Ilario42 Does the Liquidsoap log (`liquidsoap.log` in the Log Viewer, under Utilities) indicate anything out of the ordinary? The jumpiness may be concurrent with an error in Liquidsoap fetching the next song from AzuraCast.

**Comment by Ilario42** [comment]
These are my logs. I await your answers @SlvrEagle23 

https://hastebin.com/moragexepe.rb

**Comment by SlvrEagle23** [comment]
@Ilario42 These songs appear to have custom fade-in/out values set via the web interface. You should definitely double-check those to ensure none of them are out of the actual playback range of the song, as this will also cause the jumpiness problem you're reporting.

**Comment by Ilario42** [comment]
Hi @SlvrEagle23 , I did some tests and that was the problem. Now I have a question. For the jingles I do not want there to be effects of previous and subsequent music, so that the jingle does not start over the song that is about to end. How should I set it? The default station has a crossfade of 3.

I'm waiting for your answer. Thank you!

**Comment by SlvrEagle23** [comment]
@Ilario42 The easiest way to implement this would be to set a custom crossfade rule on a per-playlist basis. There's currently no way to do this, so that would be a new enhancement request.

**Comment by Ilario42** [comment]
Hi @SlvrEagle23 ,So currently I can not do anything? I know your software is free and you do not have much time to upload updates. I thank you already for the work you did and you will do, but my question is, if I can not intervene as long as you have to wait to solve this problem?

Thank you for your answers, Best regards.

I await your answers!

**Comment by SlvrEagle23** [comment]
@Ilario42 Currently, crossfades are set globally on a per-station level. You can individually set "overlap" on each song if you want, which will control how much time it actually overlays any other songs. You can't do this on a per-playlist basis, though.

**Comment by Ilario42** [comment]
Hello, thanks again for your help. So which parameters should I go to set on my song from the web panel? Could you get the same problem as before?

![image](https://user-images.githubusercontent.com/22561729/50987299-929a8580-1509-11e9-850a-9237aac34545.png)

**Comment by SlvrEagle23** [comment]
@Ilario42 I don't speak Italian, but the setting is the first one in the "Custom Fading" group, called "Overlap Time (seconds)". It should be set to a low number, ideally either close to the station's global crossfade time or zero to avoid overlapping entirely. As long as it's not a ridiculous number that's longer than the song/jingle itself, it will be fine.

**Comment by Ilario42** [comment]
Hi @SlvrEagle23 , thanks again for your reply. My jingle lasts 7 seconds. The global crossfade lasts 3 seconds. How much should I enter here for not having songs superimposed on my jingle.

Thank you for your kindness and availability
I await your answers, best regards!

**Comment by SlvrEagle23** [comment]
@Ilario42 Enter zero on the jingle itself, to avoid crossfading on top of it.

**Comment by Ilario42** [comment]
Hi @SlvrEagle23  this works at the end of the jingle, but at the beginning the voice starts at the end of the song, is not it possible to solve this?

Thanks for your kindness. I await your answers, Best regards!

**Comment by SlvrEagle23** [comment]
@Ilario42 At the moment, no. A song's annotated crossfade only applies to the transition _to_ the song, not _from_ the song to another one. This is something inherent to how Liquidsoap operates, and I'm not certain that there's even a technical solution for us to resolve it at the moment.

**Comment by Ilario42** [comment]
Hi @SlvrEagle23. So I can not intervene in any way to avoid this?

Thank you for your reply, Best regards!
