### ISSUE TITLE
Unable to clone stations

### ISSUE THREAD

**Issue by andrewbritton** [AzuraCast/AzuraCast#1094]
AzuraCast • v0.9.1, #5680f47 (2019-01-06 12:05) • Traditional • PHP 7.2 Ubuntu 18.04

Cloning station results in 500 error (Screenshot also attached)

500
Argument 1 passed to App\Entity\Station::setNowplaying() must be an instance of App\Entity\Api\NowPlaying or null, array given, called in /var/azuracast/www/vendor/azuracast/azuracore/src/Doctrine/Repository.php on line 406
Station.php : 654

![screen shot 2019-01-08 at 12 38 59](https://user-images.githubusercontent.com/20565847/50831354-7d272f00-1342-11e9-9739-2a76b8d4377e.png)

**Comment by SlvrEagle23** [comment]
@andrewbritton This should be fixed as of the latest commit, which better ensures that fields that shouldn't copy from station to station don't make it over in the cloning process.
