### ISSUE TITLE
Default jingle when station does not have audios

### ISSUE THREAD

**Issue by tonimad** [AzuraCast/AzuraCast#1095]
When I have created a new radio station, I can hear a jingle by default. This jingle disappears when I upload new audios.

My question is: How can I change this default jingle for all radio stations, by one of my own?

**Comment by SlvrEagle23** [comment]
@tonimad Given that most stations only play the error message for a very short period of time before being set up, I can only assume that the main purpose of customizing this would be for the purposes of reselling shared instances of AzuraCast.

Features that are requested specifically for the purpose of commercialization are a very low priority unless sponsored by interested parties, because we do not intend to work for free in order to allow others to make a profit on our work. We're currently working on ways to allow commercial resellers to support AzuraCast development.

**Comment by tonimad** [comment]
Hi @SlvrEagle23 

I do not intend to generate money with this system, but I understand that this audio must be unalterable, and I will respect this.

Let me tell you my goal. I'm a professor of new technologies in my school. I want to create a project for the kids, where they can learn about the world of broadcast radio stations. And of course, they will need to learn and practice, de-evolve with this technology.

I'm seeing a problem with Azurecast, already commented on #368 . As I said earlier, I do not intend to make money with your work. But it is important to limit the disk space in each radio station created: We work with a small server, provided free of charge by a hosting company. Of course, disk space is little. I have 24 students under my responsibility. They can quickly fill the server disk, however, this can be avoided by limiting the disk space for each station (or globally).

I think this request is very important. It is not a request to earn money. I can imagine many situations where this function is very important; Colleges, groups of friends who are fans of broadcasting, etc.

**Comment by CodeSteele** [comment]
> We work with a small server, provided free of charge by a hosting company.

My first concern is running 24 stations requires _a lot_ of CPU power (liquidsoap transcoding, not much we can do about it), if you're not given disk (which is cheap) I doubt you're getting the 8+ cores you need to run that many stations.

The train of thought on this is anything that isn't close friends/students where you can manage your quota manually and you need this automated and to scale, you're typically looking at business applications (and mostly resellers too).

Same with replacing the jingle, usually the only reason to do this is to white-label AzuraCast so people don't know you're running it (again, a reseller feature). Not quite sure why the students can't hear the default AzuraCast jingle.

I would imagine deploying inside of your computer lab (lab, student's laptops, etc.) and not on the cloud would be a better solution anyway, but I'll discuss this with @SlvrEagle23 and see if we can cook up anything else that may work for you.

--

A hacky solution: you can crack open the IceCast docker instance and replace the error.mp3 file with whatever you want. -- Considering it is a school deploying it once, never updating it during the semester and then trashing it/rebuilding it at the end of the semester may be a workable solution for now.

https://github.com/AzuraCast/icecast-kh-ac/tree/master/web

**Comment by CodeSteele** [comment]
Additionally #753 is a feature request for marking a file as a station's jingle, I'll keep this open for any "workaround" discussions we can have that apply to your class though.

**Comment by tonimad** [comment]
Thanks for your answer, @CodeSteele

I'm considering creating five (maybe some more) radio stations. I'll organize this activity in work groups, where each group has several students.

About disk space, I do not understand how I can limit this manually. I think this is very important, perhaps limiting all radio stations with the same amount of space.

I understand your reasoning about the commercialization of the system and I agree on this point. For this reason, I propose a solution to limit the space with the same amount for all radio stations. This is possible?

About the jingle, it's not a problem. I now understand the purpose of this jingle, when a radio station is not started. Azuracast is a project with a lot of effort behind, about ten years of non-profit work. Therefore, it is correct to respect his philosophy. The name of Azuracast is on every page. Keeping this in mind, I can not imagine any reason to convert this audio into a white label audio.

However, I insist on my proposal; Limiting space is disk in some way, it is something important.

**Comment by CodeSteele** [comment]
> I understand your reasoning about the commercialization of the system and I agree on this point. For this reason, I propose a solution to limit the space with the same amount for all radio stations. This is possible?

At that point we might as well just fully implement the feature. We're less worried about commercialization _happening_ (it's going to happen) and more that those features will take priority over features more widely used for the benefit of people profiting off of AzuraCast while not giving anything back (if we were better funded we'd worry way less about this). If we're already investing 90% of the effort it kind of defeats the purpose of staying away from these features unless they're helping support the project (either financially or via pull requests).

An option could be:
 - Create a zeroed file the size of the quota, one for every station.
 - Format these files as EXT3
 - Mount each one of these into the volume of the docker container at the station's music upload location.
 - Users attempting to use more space will be treated to a nice "out of space" error.

Something like this:
https://stackoverflow.com/questions/8148715/how-to-set-limit-on-directory-size-in-linux

Except we won't be bothering with quotas (you could but we'd just let the filesystem manage it's max size).

> However, I insist on my proposal; Limiting space is disk in some way, it is something important.

We had a few people mention they'd contribute to paying for it to be done -- so it _may_ end up getting funded, at this point we'll probably wait and see while other higher priority issues get done.

**Comment by SlvrEagle23** [comment]
@tonimad Thank you for your response, and I appreciate you clarifying your use-case so I can understand it better.

With regard to quotas, there is already an existing issue for setting and managing quotas for stations, and you should move discussion for that subject to that thread (#368).

The original question of this thread was whether it is possible to override the default error message when new stations are created but have no media. The answer to this is "yes", though it requires some manual editing of your Docker configuration file. You can create a new file named `docker-compose.override.yml` which has only this in it:

```yaml
version: '2.2'

services:
 stations:
    volumes:
     - ./your_error.mp3:/usr/local/share/icecast/web/error.mp3
```

This will allow you to override the error message with a custom one from your host.

To reiterate the original point, though, since the error message only has two components (one being that the user is using AzuraCast, and the other being that they have no music on their station), I'm not entirely sure what the need would be to replace it.

That is, unless you don't like my voice. ;)

**Comment by SlvrEagle23** [comment]
However, upon another moment's thought, one thing does stand out as one _very_ valid use-case for wanting to change the "no songs" error message: internationalization. Unlike the rest of the interface, the message is of course always broadcast in English. If your students aren't primarily English speakers, this message will be of little to no use.

Forgive me for not considering this possibility beforehand; it's easy to forget that not everyone speaks your language.

I will reopen this as an enhancement request for future review for that purpose. My workaround above will suffice for now as a way of solving the same problem.

**Comment by CodeSteele** [comment]
That would probably be broken into a few pieces:
- Allow a station to have a default language?
- Store a bunch of language-dependent jingles.
- We'd have to source those too. (@SlvrEagle23 has a nice radio voice so he'll have to pick up some 20+ languages. ;P)

**Comment by tonimad** [comment]
Thank you @CodeSteele & @SlvrEagle23 

Today I started to install Azuracast on the server. But I'm not using Docker, since this installation (docker) generates errors in my installation, and Azuracast is not installed, so I've proceeded with the traditional installation in Ubuntu 16.04 (In Ubuntu 18.04 it has been impossible). I'm assuming it's a problem in the custom versions of the hosting provider. So I think this is a problem with my server, exclusively.

About the audio, yes, it is the language (our preferred language is Spanish). But really, this is not a big problem because the voice of @SlvrEagle23  is very nice :P

I think the idea of audio is very useful, but creating this audio in many languages (through some function to detect the language of the browser) can be an extra effort. But if you need to record the audio in another language, I can help in this. But I insist, this is not a big problem, really.

> An option could be:
> Create a zeroed file the size of the quota, one for every station.
> Format these files as EXT3
> Mount each one of these into the volume of the docker container at the station's music upload location.
> Users attempting to use more space will be treated to a nice "out of space" error.

@CodeSteele This sounds good ... my knowledge is limited in this case. I continue with this discussion in the original thread.

**Comment by CodeSteele** [comment]
@tonimad with a traditional install the above recommendations are even easier because you won't be dancing around the docker containers/volumes/etc.

@SlvrEagle23 is big on internationalization and accessibility though so wouldn't be surprised if he takes that part up sooner.

**Comment by tonimad** [comment]
> CodeSteele referenced this issue 11 minutes ago
> Define size quota for each radio station #368 

Ok  @CodeSteele I'm going to try to do what you recommend. According to the instructions, I must create a file where to specify the maximum size allowed. Considering my programming limitations, I'm going to "take a breath", play zend music on my headphones, and try to follow these steps.

Before, I need some answers;

- Azuracast creates a new folder where to locate all the files of a radio station? Specifically, a folder where the audio of the radio station is stored?

- In the case of developing this solution that you have commented, in what way can this help the other users? I understand that this solution is manual (if I create a radio station, I follow these steps manually to limit the disk space of each radio station). I mean, my programming limitations are not going to allow me to develop something that works automatically. The ideal in this project is to create things that help improve the common project.

**Comment by quydox** [comment]
Hello, 

I want to change default station song, how can I do it?

**Comment by teddiey** [comment]
Hi all, I know this is a bit old. 
This is our case: our internet sometimes can be very unstable hence you can imagine as a listener how annoying it sounds when your music or program keeps being interrupted by the default Azuracast jingle. 
But just wondering would it be possible to change the default 'You are listening to Azuracast' jingle when no audio to a blank audio file. 
As for worries of Azuracast being commercialized, how about you force a 'powered by...' on the 'now playing' meta.

**Comment by SC2Mitch** [comment]
We do have docs on it, if you're unsure post a discussion in the right area.
