### ISSUE TITLE
Song Change Webhook

### ISSUE THREAD

**Issue by JDBlackman** [AzuraCast/AzuraCast#1096]
I am currently writing some socket servers for my radio. I am taking advantage of the "Any time the currently playing song changes" web hook. However I found that when it fires the "song_history" response hasn't updated with the just previously played song.

**Comment by SlvrEagle23** [comment]
@JDBlackman Hmm. The webhooks are triggered after all the other nowplaying updates are made, so that shouldn't ever really be happening. I'll take a look at it.

**Comment by JDBlackman** [comment]
I've figured out this issue on my end. Apologies if you wasted any time on this!
