### ISSUE TITLE
Docker Update ubuntu 18.04 lts

### ISSUE THREAD

**Issue by gothicdude1044** [AzuraCast/AzuraCast#1097]
**Installation method**
Docker

**Host OS (for Docker installations)**
ubuntu 18.04 lts

**Describe the bug**
When i run the ./docker.sh update-self i get error command not found
ive tried with sudo it just goes to next line and nothing happens
When i run the ./docker.sh update
just goes to next line

**To Reproduce**

**Expected behavior**
Some type of Terminal Output saying it was updating
**Relevant Logs**

**Screenshots**
![updatingazuracast](https://user-images.githubusercontent.com/1172741/51024292-22b2ec00-1557-11e9-87f4-e1a7e5778f09.png)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
This could be a permission problem. Can you look if the `docker.sh` has the executable flag set?
This is what `ls -la docker.sh` should show you `-rwxr-xr-x` if the `x` are missing than do a `chmod +x docker.sh` and try to execute the `update-self` again to check if it works now.

**Comment by gothicdude1044** [comment]
No permisson issues

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Vaalyn** [comment]
Have you checked the permission flags?

**Comment by Vaalyn** [comment]
I've tested what happens when I remove the executable flag from my `docker.sh` and when I try to use the `update-self` command the `command not found` message is displayed to me then. When I add the flag back to it it works again.

**Comment by gothicdude1044** [comment]
yes i have no issues with perms
![docker shperms](https://user-images.githubusercontent.com/1172741/51026281-2432e300-155c-11e9-8e6d-6df8594e3ef6.png)

**Comment by mkody** [comment]
That file size is... 0KB?

**Comment by gothicdude1044** [comment]
yeah i was just looking at that
im thinking about snatching the code from the master on git hub and re inserting it back into the script idk why the code didnt save and i downloaded a fresh docker.sh tonight

**Comment by mkody** [comment]
Something might have gone wrong at some point. :man_shrugging: 

```
curl -L https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh
chmod a+x docker.sh
```
and retry to a `./docker.sh update-self` to check if it's good again

**Comment by gothicdude1044** [comment]
i actually just grabbed the code and inserted into script and its actually running now

**Comment by gothicdude1044** [comment]
looks like the script worked now that ive placed the code back into the script

**Comment by gothicdude1044** [comment]
now the shoutcast dnas isnt working after update
Gives me adapter

SPAWN_ERROR: station_1:station_1_frontend
and ive rebooted the os

**Comment by Vaalyn** [comment]
Is there anything in the error log for shoutcast that could indicate why this is happening? You can find the error log at `Tools` -> `Log Viewer`.

**Comment by gothicdude1044** [comment]
looks like i had to reinstall the shoutcast dnas

**Comment by gothicdude1044** [comment]
[2019-01-11 10:20:24] AzuraCast.ERROR: SPAWN_ERROR: station_1:station_1_frontend {"file":"/var/azuracast/www/src/Radio/AbstractAdapter.php","line":185,"code":0} []
thats from the azuracast log

**Comment by Vaalyn** [comment]
That's strange. It's not a `ALREADY_STARTED` or `NOT_RUNNING` error. The error basically says that something went wrong with the supervisor. Can you enter the container via `docker exec -it azuracast_stations bash` and check the output of `cat /var/log/supervisor/supervisord.log` for more specific error messages?

**Comment by gothicdude1044** [comment]
i did fresh install now its working again grr smh
