### ISSUE TITLE
Way to install admin in subdirectory?

### ISSUE THREAD

**Issue by owengot** [AzuraCast/AzuraCast#1099]
Is there a way to install AzuraCast so the admin panel is in a subdirectory (for example /admin)?

I would like to keep the root directory free for a website that will integrate with the radio stream.

Thanks

**Comment by SlvrEagle23** [comment]
@owengot AzuraCast is meant to be installed at the root directory of a domain. If you want to host the AzuraCast panel alongside a web site, using a subdomain is likely the best way to accomplish this at the moment. There may be ways to get AzuraCast to work inside a subfolder but this is unsupported.
