### ISSUE TITLE
Let's Encrypt not working

### ISSUE THREAD

**Issue by BlueskyFR** [AzuraCast/AzuraCast#1100]
**Installation method**

Docker

**Host OS (for Docker installations)**

Ubuntu 18.04.1 LTS

**Describe the bug**

Let's Encrypt is enabled but no certificate is received by the client.

**To Reproduce**
1. Enable/install Let's Encrypt following documentation instructions
2. Try to load root using https
3. You'll get a security warning OR "no data has been sent"

**Expected behavior**

Let's Encrypt should be working for both port 80 and 8000

**Device(s):**
 - Device: PC
 - OS:  Windows 10
 - Browser: Vivaldi/Chrome
 - Version: latest

**Additional context**

**Comment by SlvrEagle23** [comment]
@BlueskyFR The LetsEncrypt process has been completely reworked as of the latest Docker infrastructure update. I'd strongly encourage you to run:

```
./docker.sh update-self
./docker.sh update
./docker.sh letsencrypt-create yourdomainhere.example.com
```

...and let me know if it fixes your issue.

**Comment by br0kenlink** [comment]
It didn't fix my issue, it uses self signed cert
I just updated today, any way to revert, didn't backup before, my bad

**Comment by SlvrEagle23** [comment]
@br0kenlink You are replacing `example.com` with your domain, right? You have to use a domain that actually points to your IP address.

Currently, there is no straightforward way to revert an installation if you haven't backed it up, but I'm pretty confident you can get back up and running quickly.

**Comment by br0kenlink** [comment]
OK, found the reason. Since I'm running docker on ports 81 and 444, Lets Encrypt was failing.
Changed ports to 80  and 443 and everything works.

**Comment by SlvrEagle23** [comment]
@BlueskyFR If you're still experiencing this issue, please let me know. I'm closing it for now as the recent updates to our Docker container infrastructure should have fixed a number of possible LetsEncrypt issues.

**Comment by BlueskyFR** [comment]
@SlvrEagle23 Hi, sorry for being inactive here. I just generated the Let's Encrypt certificate using the commands you gave me, but I am facing a problem:
I am running shoutcast server which I want to disable to be able to use the normal azuracast interface.
How can I disable it? Moreover, how can I edit ports on which azuracast works to make it accessible with https ? Thanks.

**Comment by SlvrEagle23** [comment]
@BlueskyFR I'm not clear what you mean by your question. If you want to switch from SHOUTcast to Icecast, you can do so by editing the station's profile inside AzuraCast. I strongly recommend using Icecast, since you can take advantage of direct HTTPS access using the same certificate you use for AzuraCast itself.
