### ISSUE TITLE
ERROR after update

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#1102]
Installation Method: Traditional Installation
OS: Ubuntu 16.04 LTS

After update i got this error. I tried to ./update --full still have error as shown bellow. How to Fix this error?

TASK [azuracast-setup : Run AzuraCast Setup (Update Mode)] *************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php azuracast:setup --update", "delta": "0:00:00.419304", "end": "2019-01-17 03:25:40.625945", "msg": "non-zero return code", "rc": 1, "start": "2019-01-17 03:25:40.206641", "stderr": "\nIn Database.php line 103:\n                                       \n  Failed to created database stations  \n                                       \n\nIn Client.php line 196:\n                    \n  Query has failed  \n                    \n\nIn CurlFactory.php line 185:\n                                                                               \n  cURL error 7: Failed to connect to localhost port 8086: Connection refused   \n  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)                      \n                                                                               \n\nazuracast:setup [--update] [--load-fixtures] [--release]", "stderr_lines": ["", "In Database.php line 103:", "                                       ", "  Failed to created database stations  ", "                                       ", "", "In Client.php line 196:", "                    ", "  Query has failed  ", "                    ", "", "In CurlFactory.php line 185:", "                                                                               ", "  cURL error 7: Failed to connect to localhost port 8086: Connection refused   ", "  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)                      ", "                                                                               ", "", "azuracast:setup [--update] [--load-fixtures] [--release]"], "stdout": "\nAzuraCast Setup\n===============\n\nWelcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...\n * Environment: Production\n * Installation Method: Traditional\n\n ! [NOTE] Running in update mode.                                               \n\nMigrating Legacy Configuration\n------------------------------\n\nConfiguration already set up.\n\nSetting Up InfluxDB\n-------------------", "stdout_lines": ["", "AzuraCast Setup", "===============", "", "Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...", " * Environment: Production", " * Installation Method: Traditional", "", " ! [NOTE] Running in update mode.                                               ", "", "Migrating Legacy Configuration", "------------------------------", "", "Configuration already set up.", "", "Setting Up InfluxDB", "-------------------"]}

RUNNING HANDLER [azuracast-cron : restart cron] ************************************************************************************************************************

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=67   changed=19   unreachable=0    failed=1

**Comment by SlvrEagle23** [comment]
@reans Were you able to get this issue resolved? It sounds like a problem caused by InfluxDB on your host machine.
