### ISSUE TITLE
Let's Encrypt: install: missing file operand

### ISSUE THREAD

**Issue by oznorts** [AzuraCast/AzuraCast#1103]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 18.04

**Describe the bug**
When trying to install a Let's Encrypt certificate using the docker command, an "install: missing file operand" error gets spit out endlessly.

**To Reproduce**
1. ssh into your command line
2. cd into AzuraCast's folder (e.g. `cd /var/azuracast/`)
3. run the command: `./docker.sh letsencrypt-create mydomain.example.com`
4. See error (install: missing file operand Try 'install --help' for more information.)

**Expected behavior**
Create a Let's Encrypt certificate for the specified domain

**Relevant Logs**
N/A

**Comment by SlvrEagle23** [comment]
@oznorts Did you update both your `docker.sh` script and your `docker-compose.yml`? As in,

```
./docker.sh update-self
./docker.sh update
./docker.sh letsencrypt-create yourdomain.example.com
```

If one or the other is out of date, that could be causing this sort of problem.

**Comment by oznorts** [comment]
@SlvrEagle23 Just running `./docker.sh update-self` returned the same error

**Comment by SlvrEagle23** [comment]
@oznorts Try manually updating the `docker.sh` script then:

```
curl -L https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh
chmod a+x docker.sh
```

**Comment by oznorts** [comment]
@SlvrEagle23 thanks! that worked!

**Comment by SlvrEagle23** [comment]
@oznorts Good to hear! Not sure why it was causing trouble but that's always a possible solution.
