### ISSUE TITLE
Error 500 after update

### ISSUE THREAD

**Issue by kokoloman001** [AzuraCast/AzuraCast#1104]
1. >>> 500
syntax error, unexpected end of file, expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF)

This error show in profile page.

2. >>> 500
syntax error, unexpected 'endforeach' (T_ENDFOREACH), expecting end of file

This error show in run task page.

Thank. for your support

**Comment by SlvrEagle23** [comment]
@kokoloman001 Are you using the "Traditional" or Docker-based installation method?

If you're on Docker, make sure you're running `./docker.sh update-self` before running `./docker.sh update` to avoid any issues with files not updating properly.

**Comment by SlvrEagle23** [comment]
@kokoloman001 This should be fixed now, and I've updated the settings so that our test suite will catch issues like this in the future. Thank you!
