### ISSUE TITLE
Add ability to choose whether a remote relay is public or not?

### ISSUE THREAD

**Issue by Quartizer** [AzuraCast/AzuraCast#1108]
As the title suggests, would it be possible to add the ability to choose whether remote relays are listed in YP directories or not?

Thanks.

**Comment by adwinter** [comment]
Unless I'm missing something here, isn't this controlled by Shoutcast/Icecast itself?

For example, in my situation I have my main station broadcasting to Shoutcast, and then Icecast picks up the broadcast as a relay and lists public on the Icecast Directory (based on the Icecast Settings). I can toggle public/private in the Icecast configuration file (or similarly in the Shoutcast config).

This way I have a public listing on both Icecast & Shoutcast -- but Azuracast only controls the main broadcast - the relays are setup separate.

What's handy about the Remote Relay's function in Azuracast is your relay listener data is included in the station stats, so you don't have to go hunting for what's going on on all your relays - it all displays in one place.  At least that's how I understand it. Sorry if I'm off base.

**Comment by SlvrEagle23** [comment]
@adwinter Whether a stream is public is actually strangely enough dictated partly by Liquidsoap sending over the proper public flag when connecting to the remote relay / local server. This could be a matter of being overridden from the broadcast server's settings only if any flag is specified at all, but as far as I've noticed, Liquidsoap seems to always send a flag, so it's something we'll have to expose on our end.

**Comment by adwinter** [comment]
@SlvrEagle23 thanks for clarifying.  Liquidsoap always was a bit confusing to me.. sure glad Azuracast manages that bit for me. :)

**Comment by SlvrEagle23** [comment]
@Quartizer I've added the ability to select whether a remote relay is public to the relay's edit page. After you update to the latest version, you can turn this flag on for your existing relays.
