### ISSUE TITLE
Give an option to edit order for playlist

### ISSUE THREAD

**Issue by athensguy** [AzuraCast/AzuraCast#111]
I wonder if you could add option to arrange items order on playlists.

**Comment by athensguy** [comment]
Playlist editor might support:

- Drag and drop items from media folder into playlist
- arrange order
- schedule playlist

**Comment by shaundewberry** [comment]
In addition, a "Smart Playlists" feature a la iPod/iTunes could work really cool. 
e.g. create a playlist based on year, or create a playlist for a certain artist, or a combination of attributes - genre & year or other combinations of metadata rule-based criteria.

**Comment by SlvrEagle23** [comment]
I'm consolidating a number of playlist-related enhancements into a more technical-oriented project management issue where I can track the progress on the changes, so feel free to follow that: #480
