### ISSUE TITLE
nginx 500: cannot write to /var/lib/nginx/body/

### ISSUE THREAD

**Issue by jas14** [AzuraCast/AzuraCast#1112]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 16.04.5 LTS

**Describe the bug**
Generic nginx 500 error on file upload attempt

**To Reproduce**
1. Go to https://<site>/station/x/files
2. Click on "browse" to upload file, select a file
3. Observe response: "500 Internal Server Error", full response:
```
<html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Expected behavior**
I expected the file to upload successfully.

**Relevant Logs**
```
web_1       | 2019/01/21 16:02:35 [crit] 45#45: *99 open() "/var/lib/nginx/body/0000000003" failed (13: Permission denied), client: 172.25.0.1, server: localhost, request: "POST /station/1/files/upload HTTP/1.1", host: "xxxxx", referrer: "https://xxxxx/station/1/files"
web_1       | 172.25.0.1 - - [21/Jan/2019:16:02:35 +0000] "POST /station/1/files/upload HTTP/1.1" 500 186 "https://xxxxx/station/1/files" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0" "94.73.49.41"
```

**Comment by jas14** [comment]
FWIW, permissions on `/var/lib/nginx/body/`:
```
$ getfacl /var/lib/nginx/body/
getfacl: Removing leading '/' from absolute path names
# file: var/lib/nginx/body
# owner: www-data
# group: root
user::rwx
group::rwx
other::rwx
```

I changed it to 777 permissions just in case that helped, but alas. I imagine/hope that /var/lib/nginx/body is somewhere within a docker volume, but I can't tell which. Not sure why that folder would have incorrect permissions within the volume though.

Also FWIW, this only happened after the latest upgrade. Does this have to do with the new consolidated `web` container?

**Comment by jas14** [comment]
Did a little more digging here....

Possibly relevant: we're proxying the site via apache; apache's serving our website on the domain, and forwarding requests to a subdomain to Azuracast.

Looks like nginx's default [`proxy_temp_path`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_temp_path) is `/var/lib/nginx/body`.

That's all I've got for now...

**Comment by CodeSteele** [comment]
What version are you on (including the hash)?

**Comment by jas14** [comment]
Not sure about the human-readable version number, but the full hash is `28c72b8201d4a69fce8524bde0777de44cb68c6eb57a6d2450346a1d402da953`.

**Comment by SlvrEagle23** [comment]
@jas14 This seems to have something to do with the proxy you have in front of the service, rather than AzuraCast itself. AzuraCast has no interest in the `/var/lib/nginx/body` path and wouldn't be trying to write to it.

**Comment by jas14** [comment]
@CodeSteele ,  v0.9.1, #c9648df (2019-01-21 15:21).

@SlvrEagle23 this wasn't happening before the consolidation of all the web services onto one phusion image.

Anyway, I just found a fix, which is modifying `client_body_temp_path` in [`nginx.conf`](https://github.com/AzuraCast/docker-azuracast-web-v2/blob/master/nginx/nginx.conf). I'll be submitting a PR to that repo shortly.

**Comment by jas14** [comment]
PR up: https://github.com/AzuraCast/docker-azuracast-web-v2/pull/2

**Comment by SlvrEagle23** [comment]
@jas14 Reviewed and approved. The Docker hub is building the image now, should be up in about 10 minutes.

**Comment by SlvrEagle23** [comment]
@jas14 Verified that the new build seems to be working without any issues in my local and on the demo environment. Should be good now!
