### ISSUE TITLE
Allow retrieval of history beyond the 15 shown in NowPlaying API

### ISSUE THREAD

**Issue by alexhorner** [AzuraCast/AzuraCast#1113]
**Is your feature request related to a problem? Please describe.**
For a list of recently played songs for the last hour and a bit, we need about a history of 30 songs. This allows our DJs to see what has been played and keep in line with the PPL and PRS Radio Broadcasting License which states you cannot play an artist more than once per hour unless it is a featured or multi-artist song.

**Describe the solution you'd like**
Add more options to the list of songs to keep so we could get 30, 60 and 100 songs rather than being limited by the dropdown to 15.

**Comment by JDBlackman** [comment]
I'm sure this could be achieved by creating a plugin, you can check out the example plugin. 

https://github.com/AzuraCast/example-plugin

**Comment by adwinter** [comment]
Hey Everyone. I thought I might be able to help with this -- the level of php programming in Azuracast is a bit beyond my comfort level, but I do however have some skills with mysql. 

I use a traditional install, mostly so I can get access to the mysql database a bit easier than with Docker..

So, if you do have access to the mysql database, you can get all the history you want using an SQL query. If I remember right, the song_history table uses song_ids, so you'll have to do a JOIN to get the actual tracks and artists, but easily done using mysql syntax.

Might be considered a bit of a hack, but if you want I can come up with the SELECT query you need if you want to go that route.

**Comment by SlvrEagle23** [comment]
@alexhorner I have added the `/api/station/{id}/history` API endpoint to the officially documented supported list of API endpoints. Provided the request is properly authenticated, you can fetch history for any date range (by default, the range is from 2 weeks ago to present) with detailed information about each history row.
