### ISSUE TITLE
Public page

### ISSUE THREAD

**Issue by AnUnknowsTygerosy** [AzuraCast/AzuraCast#1116]
This is not issue, but I really dont know, where to ask..

So.. where I can find code of radio's public page? I need to edit something.

Thanks for answers.

**Comment by CodeSteele** [comment]
Public page should be available here: https://github.com/AzuraCast/AzuraCast/blob/master/resources/templates/frontend/public/index.phtml

Be aware -- this _will_ be overwritten when patched from AzuraCast, so you'll have to keep applying your patches.

If you want a significant amount of design work done, we typically recommend you slap some players on a custom site and not rely on AzuraCast's public page.

Also: we do allow you to edit the CSS for more simple style changes.

**Comment by AnUnknowsTygerosy** [comment]
I want to move player on public page to my website. Thats why I need to find code.
Thanks for helping.

**Comment by CodeSteele** [comment]
Ah that's definitely doable and (generally) shouldn't cause any problems with updates (outside of it using some "internal" APIs that aren't guaranteed to not change right now).

What I pointed you at may get you a little started, though the majority of that should actually be `index.js.phtml` in that same folder.

Being as this should kick you in the right direction for accomplishing exactly that, I'm going to close this, let us know if you have anymore questions.

**Comment by AnUnknowsTygerosy** [comment]
Okay.. I copied everything from public folder to my web hosting (and renamed index.phtml to radio.php), but page is now blank. Can you help me with this?

**Comment by CodeSteele** [comment]
Yeah... that's not going to work that way, that's going to take a lot more effort, you have to effectively _port_ the code out of AzuraCast.

If you want low-effort integration, use the `Player Embed Code` on the radio station page under the profile section, that you can paste into any other web page.

**Comment by AnUnknowsTygerosy** [comment]
Ehh.. I wanted to use player embed.. but its without playlist.

**Comment by CodeSteele** [comment]
OK so a few options:

You can build your own small playlist widget using the API here: https://www.azuracast.com/api/index.html# and some javascript. This will be _much_ easier than trying to massage the AzuraCast code into your website.

I've also opened #1117 for more complex player embed widgets

**Comment by AnUnknowsTygerosy** [comment]
Okay.. thanks. And.. I have one more question. Iam trying to get info about current song using my discord bot in discord.js. 
This is my code: https://hastebin.com/eyifipobiv.cs
And this is my error when using np command: 
```
(node:3861) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'song' of undefined
    at Object.exports.run (/home/justwolf/cloudradio-main/src/commands/radio/np.js:28:40)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by CodeSteele** [comment]
Yeah it's not in `body.station.song.text` it's `body.now_playing.song.text`

**Comment by AnUnknowsTygerosy** [comment]
Oh.. thanks! Its working.
