### ISSUE TITLE
Player Embed Widget Builder

### ISSUE THREAD

**Issue by CodeSteele** [AzuraCast/AzuraCast#1117]
There have been requests for more feature-rich players for embed, it would be nice to be able to build a custom one that matches feature parity with the regular player.

- Ability to view playlist
- Ability to make song requests
- Maybe a JS embed instead?
- Maybe the ability to make/share templates?

**Comment by AnUnknowsTygerosy** [comment]
Smooth preview of image, that is on public page player.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39025/player-embed-widget-builder
