### ISSUE TITLE
Copy Playlists

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#1120]
**Is your feature request related to a problem? Please describe.**
Yes, i want to change the Music Style of some Stations and i need to move Playlists and the their Music to another Station.
**Describe the solution you'd like**
A Button to move The Playlist and the Music in it from one Station to another Station.

**Comment by preterive** [comment]
i wish a feature to move the Music too.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38929/clone-playlists
