### ISSUE TITLE
Change mount point AutoDJ bitrate input type

### ISSUE THREAD

**Issue by gr0ebi** [AzuraCast/AzuraCast#1121]
When adding mount points, you have to choose from 8 bitrates for your stream.
It would be great to have another input type then 8 radio buttons since not all bitrates suit every codec

![image](https://user-images.githubusercontent.com/5413526/51778631-14420400-2103-11e9-9616-c9f13669e1b5.png)

thanks

**Comment by SlvrEagle23** [comment]
@gr0ebi What alternative options would you suggest? The current selections include the most popular options for bitrates used by almost all web radio stations.

**Comment by gr0ebi** [comment]
I don't have an exact idea, I would like to see 160kbps(for Vorbis) and VBR

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39024/expand-available-bit-rate-options-for-streams
