### ISSUE TITLE
Weight in station_playlist_media

### ISSUE THREAD

**Issue by adwinter** [AzuraCast/AzuraCast#1126]
Hey Everyone. I've recently moved to AzuraCAST from a commercial package that I should probably not mention here... lol... but one of the things I used to do with the later was a did my own dynamic playlists by interacting directly with the SQL database. I'm quite aware I need to use caution when reverse-engineering this stuff, but I've had some success doing it.

I was hoping someone could give me some insight as to how "weight" is calculated in the station_playlist_media table. I've got a few theories... when I added a single track to a sequential playlist and checked the database, it wrote it in as weight 1. so I'm thinking maybe weight is used in a sequential playlist as order? 1 being played before 2 etc?? Can anyone confirm this for me?

Thanks a lot.

Andrew

**Comment by SlvrEagle23** [comment]
@adwinter To confirm your suspicions, yes, the `weight` field in `station_playlist_media` determines the playback order for sequential playlist items. For "shuffled" playlist items, the weight is randomized once per playback cycle and then the songs are played back in randomly weighted order, then reshuffled once all songs have been played. For random songs, the weight isn't factored into playback at all.

**Comment by adwinter** [comment]
Sweet! Thanks for the help.
