### ISSUE TITLE
Use of WEB DJ without https

### ISSUE THREAD

**Issue by ZapicoGT** [AzuraCast/AzuraCast#1129]
Use of WEB DJ without https

I use azuracast on a vps without https and I can not transmit with WEB DJ.

**Comment by SlvrEagle23** [comment]
@ZapicoGT As Vaalyn said, this is a requirement that's established "upstream" from us, as browsers have started to require HTTPS for pages that ask for audio/microphone access. We'd strongly recommend either using CloudFlare in front of your installation or setting up LetsEncrypt, which now includes automatic renewal for free and easy SSL.
