### ISSUE TITLE
SSL on Webserver

### ISSUE THREAD

**Issue by fiesi** [AzuraCast/AzuraCast#1133]
Hello,

I have installet Apache2 and more on my Server.

i have install the Docker witz Azuracast but i can not install the SSL then Azuracast ist install under Port 800 and 4430 and letsenscypt dont working so (Port 80 and 443 are used by Apache2).

Can i Add the SSL Cert self? and Add my Domain name into azuracast?

**Comment by CodeSteele** [comment]
Yep, when hosting AzuraCast on non-standard ports you'll be responsible for managing your own SSL certs, whether you're going to configure Let's Encrypt yourself or purchase and install the SSL cert manually.

Ideally: you'll just use a reverse proxy on Apache and load Let's Encrypt there by some method similar to this: https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-18-04

Ultimately general Linux administration is outside of our support though.

**Comment by fhazal** [comment]
can u teach how to do this reverse proxy? i try but it's not working, i have a letsencrypt in my server, but don't know how can make it run with azuracast , i have LAMP stack on my server and cannot make it SSL because my port is not normal port i use 81 and 447, can u help ? provide the tutorial.
