### ISSUE TITLE
Sequential Playlists & Repeating

### ISSUE THREAD

**Issue by adwinter** [AzuraCast/AzuraCast#1135]
Hello again, I had an odd thing happen to me last night with my station and Azuracast. I set up a sequential playlist to play at a specific time WED JAN 30 @ 8PM PST. The playlist consisted of a 59:30 radio program and a StationID. I totally understand that the timing is not precise - the program started at about 20:02. The program played, was ending at about 21:01 and then the StationID played... weird thing is, just after 21:00 it queued up the program again. I set the sequential playlist to play on Wednesdays between 8pm and 9pm.

So my thoughts are that when the "next song" queues it was before 9pm (even a second or two before), so it played the next in the sequence which happened to be the hour long program. This got me thinking...

Is there any way to make a playlist play to its end, and not repeat? So I could cue up my program to start at 8pm, knowing it will start roughly at that time, play to completion, and then go back to the general rotations with weighted playlists.

What I'm going to try with my specific situation here is set the playlist to play from 8pm to 8:45, knowing the program is well longer than that... I'm hoping that will force the issue when the program ends and the playlist will not be drawn from again.

I'm hoping someone here could chime in that maybe I'm doing something wrong in scheduling an hour-long pre-recordeded show at a specific time, if my 45min playlist will work, or what they think about having a playlist option to play to the end and then stop playing from the playlist. (no repeating)

Thanks so much for all your help.

Andrew

**Comment by SlvrEagle23** [comment]
@adwinter With regard to your specific situation, I don't think the relevant components are currently precise enough to do this in a way that you would be able to rely on dependably. Our playlist transitions depend on the end time of the song preceding the scheduled time, and as you noticed, there's a few seconds of lead time where Liquidsoap asks AzuraCast what to play next and it returns a result, which could theoretically cause a song to play well into the wrong time bracket, if it's long enough to notice.

I can imagine that the specific scenario you mention, though--having a sequential playlist that you want played at a given scheduled time, but without repeating any tracks--is something that would be of value to several other stations that syndicate content from, say, podcasts or pre-recorded shows.

The only problem is trying to figure out how that would work within the context of AzuraCast's existing AutoDJ tool. It's a bit of an engineering challenge that would require some reworking of the AutoDJ's current logic flow.

Considering the easy solution in this case is just to set the playlist to "Play once per day" at a given time, then moving the station ID/bumpers to a separate "play once per x songs" playlist, it may be more work than it's worth to code around this specific use case.

**Comment by adwinter** [comment]
I can appretiate this. Liquidsoap has given me tons of grief over the years and is why I abandoned customizations using it. 

A quick follow up question if I may.. Any way to set "play once a day" but only a specific day?? 

I think what I might try is setting it to "play once a day" and then simply enabling the playlist only on the day it needs to play, then disabling it after and repeat.  Not a pretty solution, but I think it could work. And once I get a flow worked out I could write a script to handle it automatically. 

Anyway just thinking out loud. Thanks for your reply. I appreciate your thoughts and solutions to my specific circumstances.

Andrew

**Comment by SlvrEagle23** [comment]
@adwinter You can specify the days of the week that you would like the "once per day" playlist to play when creating/editing it. Keep in mind that this corresponds to the day that the given time lands on in the UTC time zone.
