### ISSUE TITLE
Variables and silence detector

### ISSUE THREAD

**Issue by tonimad** [AzuraCast/AzuraCast#1136]
I would like to create a small function in php to indicate if the server is working, or not. I can not find the $variable that indicates the status of the server.

The easy structure is this:

```
if( $running ) {
    echo "Server is on";
} else {
    echo "Server is off"
}
```

OR...

```
if( $status==1 ) {
    echo "Server is on";
} else {
    echo "Server is off"
}
```

The question is, what is the variable "$running" or "$status" in Azuracast?

In another order, I would like to create a silence detector to implement it in the project. Case: If I'm live, but my playout/encoder/ has a failure, this will produce a prolonged silence in the radio broadcast. The idea is to detect this silence and send me an email to notify about this.

To do this, I need some information. If anyone has any suggestions, any comments are welcome. I know PHP and javascript.

**Comment by SlvrEagle23** [comment]
@tonimad AzuraCast is an enterprise-grade object-oriented PHP web application and as such, I'm afraid it's not as simple as just finding a single `$is_running` or `$status` variable in the code and just attaching to it.

There are two ways to go about what you're wanting to do: one is to make an API request to the `/api/station/{station_id}/status` API endpoint, which currently just returns a very simple result in JSON:

```json
{
  "backend_running": true,
  "frontend_running": true
}
```

The other would be to actually inject directly into the AzuraCast code, at which point the process gets somewhat more complicated. I can walk you through it, but honestly the _far_ easier option is to just hit the API above.

As for silence detection, this has been implemented in Liquidsoap before and I can see if I can find some existing documentation on how this works.

**Comment by tonimad** [comment]
Hi @SlvrEagle23 

Thanks for your reply :)

> one is to make an API request...

Great! I understand that many functions can be created; I'm thinking some ideas, lately. So, I'm going to study the documentation about the API; I understand that it is the easiest way and with more options to create new functions.

> As for silence detection, this has been implemented...

Wow! I appreciate any help about this. I think it can be cataloged as an improvement, but if Liquidsoap has any function that helps in the detection of silences, it will solve a need at the moment of having a radio broadcast failure.

**Comment by tonimad** [comment]
@SlvrEagle23 

> one is to make an API request...

I'm studying the API documentation. I want to practice with the functions of the API. For example, I want to get the value of "now_playing", but I think I'm having some error:

```
        $url = $stream.'/api/nowplaying/1';
        $data = json_decode(file_get_contents($url), true);
        echo "Now: ", $data['station']['now_playing'];
```

I'm putting the "station" value first, because "now_playing" is inside "station", but I do not receive the result. If I indicate only the value "now_playing", I still do not receive any results.  Uhm... What am I doing wrong?

**Comment by SlvrEagle23** [comment]
@tonimad You may be misreading the API docs. The `now_playing` property is alongside the `station` one, not inside it. Your song data is available at `$data['now_playing']['song']['title']`, for example. If you want to see the full data set, you can also just `print_r` the entire return statement and see what it contains.

**Comment by Vaalyn** [comment]
@tonimad you can also take a look at the API client library I built for AzuraCast to see how that works: https://packagist.org/packages/vaalyn/azuracast-api-client

**Comment by SlvrEagle23** [comment]
@tonimad Regarding your other question (silence detection), I've officially rolled this into the AzuraCast core, so you can now specify a silence detection buffer in seconds from your station's AzuraCast profile, or disable silence detection entirely.
