### ISSUE TITLE
Requests from channel1 with channel 2 playlists no longer work

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#1143]
**Installation method**
Tradition.

Hi! I had implemented thanks to the songs required, the top 5 voting, everything worked until an update. First, if I voted for the songs to make them play in channel 1, taking them from channel 2, everything worked.

Now the song taken from playlist 2 and played in channel 1 by request no longer works, the song is written in "Playlist_next" but is then skipped.

I'm waiting for your answer! Kind regards!

**Comment by Ilario42** [comment]
I mean that if I make a request from a php file via mysql query and the song is in another station, always in azuracast it is inserted in the station_request but when it is his turn to be played it is skipped. How can I prove you 

@SlvrEage23

**Comment by Vaalyn** [comment]
I think the problem here is that you are trying to submit song request by inserting a record directly into the AzuraCast database and that if you insert a request for station **A** where the song belongs to station **B** that this request will not be played but skipped. Did I understand this correctly?

If that is the case then you should better switch to using the official AzuraCast API to submit requests programmatically. Here you can find the [API documentation](https://demo.azuracast.com/static/api/index.html) and here is a [PHP library](https://packagist.org/packages/vaalyn/azuracast-api-client) that you can use for ease of use.

**Comment by Ilario42** [comment]
Yes @Vaalyn good I meant this!
It took me so long to do everything, I would not throw it all and do it again. Let's see what he says @SlvrEagle23

**Comment by Vaalyn** [comment]
@Ilario42 If you want to keep the workflow of inserting directly into the database then you'll have to make sure that the `song` from the database that you want to request also belongs to the `station` where you want to request that song as it is only supported to request songs from the corresponding `station` in the database.

**Comment by Ilario42** [comment]
Yes @Vaalyn But first it worked, using the get and post requests of the bees will work?

**Comment by Vaalyn** [comment]
@Ilario42 Only if the song also belongs to the station where you want to request that song. You can't request a song from station `A` in station `B`.

**Comment by SlvrEagle23** [comment]
@Ilario42 This is a safety check that exists in our system to prevent users from being able to request songs on one station that actually belong to another.

For the vast majority of cases, this safety check is valid and useful.

I'm inclined to say that I wouldn't even want to add the ability to bypass this, as it would lead to some very bizarre possible errors and would significantly increase our support burden.

**Comment by Vaalyn** [comment]
Is there a specific reason why you want to request a song from one station in another?

**Comment by Ilario42** [comment]
Hello @Vaalyn @SlvrEagle23 

Thanks for your answers. As already said in precedence @Vaalyn  I created the TOP 5 VOTING, in channel A and these songs are in channel A. Only in channel B I would like to make that when the voting starts a jingle "This is the winning song" and part the song of position number 1, which however is in station A. Here's why I'd like to do that

I await a reply :)
Kind regards!

**Comment by SlvrEagle23** [comment]
@Ilario42 I feel like something very similar could easily be accomplished with multiple playlists on the same station. I don't think this use case justifies adding an exception to our safety checks which exist for very good reason in our database.
