### ISSUE TITLE
Album covers doesnt work with Icecast stream at all; Debian 9 docker install

### ISSUE THREAD

**Issue by T3chnoMaciej** [AzuraCast/AzuraCast#1144]
Hi! It's me again. I managed to get my station working with your awesome software, but a big problem for me is fact, that it doesn't read icecast sent album covers. I have legal iTunes donwloaded albums and there's nothing. I tried broadcasting with mixx or with webdj, gave the same results. On the other hand, when I upload theese files to the server and play them laike they were scheduled everuting works like a charm. Can you guys please help me? Here are some screenshots explaining more situation
![error_okladki](https://user-images.githubusercontent.com/20857124/52176737-1a954780-27b7-11e9-91ad-9491c45adf1f.png)
Here are the iTunes album covers

![error_okladki3](https://user-images.githubusercontent.com/20857124/52176744-2f71db00-27b7-11e9-8d5b-1aa05d99176d.png)
Here is the song livestreamed from Mixx/WebDj

![error_okladki4](https://user-images.githubusercontent.com/20857124/52176750-3e588d80-27b7-11e9-9139-8b27fae69a3a.png)
Here's the console log. Translated from Polish : Wrong URI adress. Multimedia content "" not read/loaded(wczytana). And then "Source map error"

![error_okladki5](https://user-images.githubusercontent.com/20857124/52176759-6ea02c00-27b7-11e9-9987-a7949935beca.png)
Here's the api nowplaying log 

![error_okladki6](https://user-images.githubusercontent.com/20857124/52176762-7e1f7500-27b7-11e9-96c2-a003928fafac.png)
And here's the song after programming it to play with scheduled playlist.

Thank you very much for answearing all questions I have and had. You're awesome, helpful community.

Cheers from Poland,
Maciej

**Comment by Vaalyn** [comment]
As for Mixxx this is due to missing support for cover art in the software, see [this page](https://www.mixxx.org/wiki/doku.php/cover_art_support).

For the WebDJ I'm not quite sure if the Wecast protocol or the Webcast.js lib support transmitting album cover art.

**Comment by T3chnoMaciej** [comment]
Okay, thank yoh very much! Would you recommend compiling Mixx version that is working on suporting it (as in your link) or switching to another DJ software? And if the second option which one would you recommend, Traktor? VirtualDJ? I would like to have jingles and mic access like in mixxx. Thank you for your time and help!

**Comment by Vaalyn** [comment]
I've personally never needed to transmit cover art so I'm not sure what to recommend here. Basic access to mic and you song library should be available in most DJ software. For cover art I think you'll need to research a bit about which software supports it and which do you like to work with.

**Comment by SlvrEagle23** [comment]
@T3chnoMaciej AzuraCast currently doesn't try to pull album artwork for the currently playing song from the actual stream of the song. Album artwork is only supported if you're playing a song from your station's media library.
