### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by mlmateos** [AzuraCast/AzuraCast#1145]
**Installation method**: Docker

**Host OS (for Docker installations)**: Debian 9

**Describe the bug**: Just updated and got this warning: "Deprecation warning: Your package name AzuraCast/AzuraCast is invalid, it should not contain uppercase characters. We suggest using azura-cast/azura-cast instead. Make sure you fix this as Composer 2.0 will error."  Which file should I edit and change AzuraCast/AzuraCast for azura-cast/azura-cast?

**To Reproduce**:  ./docker.sh update-self &&  ./docker.sh update

**Expected behavior**

**Relevant Logs**

**Screenshots** :
![azura-cast-update- 2019-02-03 05-48-31](https://user-images.githubusercontent.com/6385699/52177398-e2294580-2785-11e9-9ae5-916f9452d879.png)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@mlmateos This is a relatively minor issue that shouldn't actually stop anyone from properly installing or updating the software, but in preparation for Composer 2 I've updated the package name to be lowercase.
