### ISSUE TITLE
Error while updating on CentOS 7

### ISSUE THREAD

**Issue by afonsosantos** [AzuraCast/AzuraCast#1147]
**Installation method**
Docker

**Host OS (for Docker installations)**
CentOS 7

**Describe the bug**
When updating AzuraCast, as requested in the main web page of the server, it gives the following error (see attachment).
I've tried to reboot the server and try again, but the same happens. The whole installation of AzuraCast is working, except the updating.
![erro](https://user-images.githubusercontent.com/46262740/52179991-7fad6500-27d8-11e9-9af5-9258442ac4a2.PNG)

The installation process itself was a little tricky, and i needed to do some tricks to make it install.

Thanks in advance.

**Comment by SlvrEagle23** [comment]
@afonsosantos Not sure what could be causing this one. Searches elsewhere on the web suggest this is a possible issue with Docker Compose itself not being installed correctly.

**Comment by afonsosantos** [comment]
Hi,

Thanks for the reply!
I've installed Docker Compose using PIP, because AzuraCast installer didn't install Docker Compose by default. I will try to reinstall Docker Compose and see if the problem gets solved.
