### ISSUE TITLE
part of phrases to translate not added

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#1148]
part of phrases to translate not added
![45240](https://user-images.githubusercontent.com/23697714/52195817-82f13100-286a-11e9-980c-0f539315bdfb.png)

**Comment by susl16c** [comment]
it is not in the .pot file, I know that this is a new parameter and I have already been sent to the links and I wrote that I don’t understand anything there.

**Comment by SlvrEagle23** [comment]
@susl16c The translations were out of date and have been updated. Let me know if that covers the appropriate areas.

**Comment by susl16c** [comment]
![542](https://user-images.githubusercontent.com/23697714/52360283-af64a300-2a4c-11e9-9992-5646e11cfce2.png)

**Comment by susl16c** [comment]
![2042](https://user-images.githubusercontent.com/23697714/52360468-2dc14500-2a4d-11e9-89b1-d2e655abf558.png)

**Comment by susl16c** [comment]
![45245](https://user-images.githubusercontent.com/23697714/52360537-5e08e380-2a4d-11e9-95c8-916bf70d0ecb.png)

**Comment by SlvrEagle23** [comment]
@susl16c I have added the strings you pointed out to the translated strings list.

As a courtesy, I would ask that you please not submit any further translation-related issues unless you are willing to contribute your translations to our project's CrowdIn, as this process is placing more work on us without sharing your contributions back with the community.
