### ISSUE TITLE
Error 500 en Add Remote relays

### ISSUE THREAD

**Issue by enigmathion** [AzuraCast/AzuraCast#1149]
**Installation method**

**Host OS (for Docker installations)**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by CodeSteele** [comment]
```Argument 1 passed to App\Entity\StationRemote::setSourcePort() must be of the type integer or null, string given, called in /var/azuracast/www/vendor/azuracast/azuracore/src/Doctrine/Repository.php on line 351
StationRemote.php : 199****```

**Comment by SlvrEagle23** [comment]
@enigmathion Thanks for the report! This was caused by some minor infrastructural changes in our code and required a bit more work to fix than I expected, but it should be fixed now across the site.
