### ISSUE TITLE
Custom URL Streaming (Points)

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#1152]
Normal.

Hello, I added a subdomain that points to azuracast for the custom URLs of the streaming point. But it does not work I get a 404 error. Help please!
![image](https://user-images.githubusercontent.com/22561729/52356050-d367ba80-2a33-11e9-908b-e2f6064b203c.png)

![image](https://user-images.githubusercontent.com/22561729/52356077-de224f80-2a33-11e9-854f-be2d5fd2d029.png)

Best Regards!

**Comment by SlvrEagle23** [comment]
@Ilario42 That field is meant if you want to hard-code in a different URL that AzuraCast should use when listing that mount point's URL (either on the station's profile, in API results, or on the public pages). It doesn't actually make AzuraCast handle requests at that URL if you set it to a URL that AzuraCast manages. That would be a separate feature, and there are not any current plans to add that, as it significantly increases possible URL conflicts between stations and confusion.
