### ISSUE TITLE
Broadcasting stops every now and then (Liquidsoap logs compiled)

### ISSUE THREAD

**Issue by franckalbinet** [AzuraCast/AzuraCast#1153]
Hello, 

We have been using Azuracast for the last 6 months now almost successfully: http://parlementia-records.com 

However, we are experiencing periodic stops of the broadcasting (would say about every 2 weeks more or less) and then need to restart it through `Utilities/Restarting Broadcast` link.

Looking at the Liquisoap logs, we have not managed to identify the source of this problem. In order to share with you enough information, I've done the following:

1. select **all past 20 logs prior to `LOG START`** in the liquidsoap logs **over the last months**;
2. **count** and **sort** them in **descending order**;

Below as .csv (log, count):
```
log,count
radio_out_1:3 Closing connection...,12
radio_out_1:3 Connecting mount sid#1 for @127.0.0.1...,8
radio_out_1:3 Connection setup was successful.,7
clock.wallclock_main:2 Too much latency! Resetting active sources...,7
radio_out_1:3 Will try to reconnect in 3.00 seconds.,5
radio_out_1:2 Error while sending data: could not write data to host: Broken pipe in write()!,5
main:3 Freeing memory...,4
main:3 Threads terminated.,4
main:3 Waiting for threads to terminate...,4
LOG END ,4
clock.wallclock_main:3 Streaming loop stopped.,4
rotate_6060:3 Switch to mksafe with forgetful transition.,4
server:3 Closing socket.,4
smart_crossfade:3 No transition: using default.,4
threads:3 Scheduler shut down.,4
threads:3 Shutting down scheduler...,4
main:3 Cleaning downloaded files...,4
main:3 Shutdown started!,4
"threads:3 Thread ""wallclock_main"" terminated (0 remaining).",4
```
Is there anything you could spot that might have caused these periodic stops?

Thanks a lot for your help.

**Comment by SlvrEagle23** [comment]
@franckalbinet A few elements of concern:

```
clock.wallclock_main:2 Too much latency! Resetting active sources...,7
radio_out_1:3 Will try to reconnect in 3.00 seconds.,5
radio_out_1:2 Error while sending data: could not write data to host: Broken pipe in write()!,5
```

It seems like the frontend (Icecast, Shoutcast, etc) is erroring out and then it's disconnecting Liquidsoap as a source, which is causing some of the shutdowns...and there may also be issues with the server being overloaded.

How many mount points/stations are you hosting on the same server? Are your system resources typically maxed out or do you have ample overhead?

**Comment by franckalbinet** [comment]
Thanks for your quick reply. 

Having checked with the person in charge of the installs, it looks like AzuraCast is indeed currently installed in a shared machine (don't have all the details but looks like the resources are rather minimal and changing -by definition).

What would be the minimal (or ideal) resources required to run AzuraCast smoothly on a dedicated machine?  We will ensure to comply with these requirements.

Thx again for you help
