### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by ZapicoGT** [AzuraCast/AzuraCast#1154]
HTTP ERROR 500

Several days with the vps on and error

Digital Ocean

**Comment by ZapicoGT** [comment]
https://i.imgur.com/ItGhi2b.png

**Comment by CodeSteele** [comment]
Please refer to the instructions you deleted to log this bug, we need logs:

https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#troubleshooting-by-viewing-logs

**Comment by oussamatn** [comment]
Hi,  
Try to reboot you vps. Im having this after any update.

**Comment by ZapicoGT** [comment]
I can not find the logs. Not listed.

**Comment by CodeSteele** [comment]
If the logs are missing from their default locations I'm probably going to suggest something unrelated to AzuraCast has caused some kind of server problem, and recommend a redeploy of the entire Digital Ocean instance.

**Comment by ZapicoGT** [comment]
Okey. Closed.
