### ISSUE TITLE
Proposal for a solution to reduce the memory usage of the Flysystem cache

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#1155]
I've looked into the memory issue reported in the first comment of https://github.com/AzuraCast/AzuraCast/issues/807 and I have an idea for a solution that we could implement to reduce the memory footprint of the Flysystem in-memory cache. I'd like to hear your opinions about this before I implement it.

The main culprit for the memory usage is most likely the `media` cache here https://github.com/AzuraCast/AzuraCast/blob/master/src/Radio/Filesystem.php#L37. The `CachedAdapter` that is initialized here https://github.com/AzuraCast/AzuraCast/blob/master/src/Radio/Filesystem.php#L51 calls the `cache->load()` method in the constructor https://github.com/thephpleague/flysystem-cached-adapter/blob/master/src/CachedAdapter.php#L30. This loads the whole `media` cache data into memory.

To prevent loading all that data into the in-memory cache on initialization I would create an `AzuraCastCachedAdapter` that extends the `CachedAdapter` and overloads the constructor with one that does not call the `cache->load()` method. That way the in-memory cache would only fill up with the data that is explicitly requested from the redis cache and put into it while the application is running.

The methods that we call when we want to work with the Flysystem, execute the `callWithFallback()` method from the `CachedAdapter` here https://github.com/thephpleague/flysystem-cached-adapter/blob/master/src/CachedAdapter.php#L307 which will first try to fetch the data from the in-memory cache and if that results in a miss it will fetch the data from Local and put it into the cache and redis.

To let the Flysystem cache fill up the in-memory cache with the data that is requested we would need to  implement a Flysystem Adapter that extends the `AbstractAdapter` and gets another Adapter injected (for example `Local`) to first try to fetch the requested keys from Redis and on a miss fall back to the methods from the injected Adapter so that it then populates the cache from the injected Adapters filesystem.

For this to work correctly the structure of the media data in the redis cache would need to be changed a bit. Every media file would need to be stored in its own redis entry with their filename as key and the current filesystem keys as prefix for them (`fs_xxxx_<element>`). This will definitely blow up the amount of keys in Redis but performance wise Redis can handle up to ~250 million keys. So that should stay performant even for stations with really big media libraries. In addition to that it will reduce the memory footprint of the in-memory cache dramatically but would also increase the number of calls to the Redis. However I don't think that this would result in problems with the connections count. If a connection to Redis stays open during the runtime and is reused for all calls this increase on connections is neglectable I think.

To get the Flysystem Cache to play nicely with this data structure without initializing a Storage for each file we would also need to implement a Flysystem Cache Storage like the `PhpRedis` Flysystem Storage where the `save()` method needs to be build to not save the whole cache to the `$key` but iterate over the `fs_xxxx_<element>` entries in the in-memory cache and commit them to redis with their respective `fs_xxxx_<element>` keys. This can be done with a loop for every single `$key` with the `Redis::set()` method or in batches via the `Redis::mSet()` method. The `load()` method could be set to throw a `NotImplementedException` then since nothing would use it anymore and would not be needed but the CacheInterface requires the method itself to exist.

The `listContents` method of the AzuraCastCachedAdapter needs to be changed to not check for `$this->cache->isComplete` and always read from the Redis since we can't be sure if the directory is complete. This would need to fetch all Redis entries for the `fs_xxxx` prefix with the generator syntax (`yield`) in order to reduce the used memory. This is possible by first fetching all matching keys with the `Redis::keys()` method and then fetching all the values for the keys in a loop and yielding them. To reduce the amount of calls this could also be done in batches with the `Redis::mGet()` method instead of `Redis::get()`.

The `flushAllCaches` / `flush` methods need to make sure that all redis entries with the `fs_xxxx` prefixes are cleared by also first getting all matching keys and then deleting them with `Redis:: delete()` which can also work with batches of keys.

In the 'Stations/Files/FilesController.php' the `listDirectoriesAction()` method uses the `listContents()` method with `array_filter` and `array_map`, this will not work with the generator syntax so this would need to be changed to a `foreach` loop that does what the current implementation does.

In the `Stations/Files/ListController.php` the `__invoke()` method uses the `listContents()` method and would need to be changed to not loop over the result of the `listContents()` from an assigned variable but directly on the return values from the yield of that method.

In the `Stations/Files/BatchController.php` the `_getMusicFiles()` method uses the `listContents()` method with `array_filter`. This would need to be changed to use a foreach to filter the returned entries.

Implementing this will increase the complexity of the filesystem caching although the implementation should be straight forward and not that big. If there is anything I've missed while researching this please let me know.

**Comment by SlvrEagle23** [comment]
@Vaalyn Considering the Redis cache is only storing a tiny subset of metadata about each file that it manages, how big does someone's media collection need to be before we have to consider this? I've never run into performance issues of this sort with any of the installations I've supported.

If this is something that's likely to be encountered by a large number of stations, then I'd definitely consider implementing the solution as you described it. As it stands, though, it sounds like a fairly large cross-section for potential errors (and increased maintenance burden) with the sole purpose of catering to a very small group of operators of extremely large stations.

**Comment by Vaalyn** [comment]
@SlvrEagle23 Currently I have no number for when this starts to happen. In the thread I linked the station there has around 50-55k files. I'll try to benchmark the memory usage a bit for increasing numbers of files to get a more accurate number of when these memory issues start to happen.

Do you have an average of what is normal for fairly large stations?

**Comment by SlvrEagle23** [comment]
@Vaalyn There's no hard and fast average that I see, but I see a ton of stations operating under 5k (and many under even 1k) and they run extremely smoothly on our current codebase. I even have one example of an installation running multiple stations with 14k songs each with no performance deficit when navigating files.

I'm not entirely confident that, in my entire adult life, I've actually *listened to* 55,000 different songs. Given that web radio is meant to be a curated experience, it's hard to imagine manually reviewing a catalog that big for suitability for playback.

Archival and storage of large libraries of content is a task better suited for the likes of, say, Plex, instead of us.

**Comment by Vaalyn** [comment]
@SlvrEagle23 When 14k songs per Station are working fine then I think it's okay to stay with the standard caching behaviour of the Flysystem cache and recommend to increase the memory limit if you need more than that (which you already made possible). Since this issue would only happen if a single station has an absurd amount of songs this will probably be the most economic solution in terms of maintainability.

You are totally right, a radio should in most normal cases have only a relatively small number of songs in rotation and AzuraCast is definitely not meant for archiving of media libraries.

If the amount of data in the cache becomes exponentially bigger we can always re-evaluate this topic but for now I'll close this issue since this seems unlikely to be needed at the moment.

**Comment by SlvrEagle23** [comment]
Just to document for future posterity: @Vaalyn and I worked to discover just how much memory is being used by the in-memory caching of file and folder contents for a station, and basically it amounts to about 25-30MB for 14,000 files. This is well within our operational limits and a vast majority of stations, especially those operating with fewer than that number of files, will notice no performance issues at all.

There was an issue that could arise where the 5-minute sync process could run out of memory if you had multiple stations that all were piling 25MB a piece onto the pile of currently allocated memory. Some changes to how records are flushed and how garbage collection is handled with the sync task has reduced the sync task's memory used to a stable 4.5MB between sync tasks, allowing very high overhead per-station.
