### ISSUE TITLE
Liquidsoap not starting

### ISSUE THREAD

**Issue by NLLucifer** [AzuraCast/AzuraCast#1157]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**

**To Reproduce**
After an update the Liquidsoap service isn't starting for streams that have the following Liquidsoap configuration:
`output.file(%vorbis, "../streams/stream %H%M.ogg",fallible=true,reopen_when={0m0s}, on_stop=shutdown,live)`
This is used to capture the streamed data.

**Relevant Logs**
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [threads:3] Created thread "generic queue #1".`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [threads:3] Created thread "generic queue #2".`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [threads:3] Created thread "non-blocking queue #1".`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [threads:3] Created thread "non-blocking queue #2".`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [harbor:3] Adding mountpoint '/' on port 8015`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [playlist_nonstop(dot)m3u:3] Loading playlist...`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [playlist_nonstop(dot)m3u:3] No mime type specified, trying autodetection.`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [playlist_nonstop(dot)m3u:3] Playlist treated as format application/x-mpegURL`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [playlist_nonstop(dot)m3u:3] Successfully loaded a playlist of 55 tracks.`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [entertainmentradio_local_1:3] Connecting mount sid#1 for @127.0.0.1...`
`stations_1_ec748fd73e05 | 2019-02-06 15:38:52INFO[SRC 127.0.0.1:38044 sid=1] SHOUTcast 1 source connection starting.`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [entertainmentradio_local_1:3] Connection setup was successful.`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [threads:3] Created thread "wallclock_main" (1 total).`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/entertainmentradio/media/Normale Non-Stop/jeckyll_a_hyde_-_freefall.mp3".`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [entertainmentradio_live_fallback:3] Switch to entertainmentradio_playlist_fallback.`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [entertainmentradio_playlist_fallback:3] Switch to blank_6343.`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [playlist_nonstop(dot)m3u:3] Prepared "/var/azuracast/stations/entertainmentradio/media/Normale Non-Stop/jeckyll_a_hyde_-_freefall.mp3" (RID 1).`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [entertainmentradio_playlist_fallback:3] Switch to switch_6342 with transition.`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [dummy:3] Source failed (no more tracks) stopping output...`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [(dot)(dot)/streams/stream_%H%M(dot)ogg:3] Source failed (no more tracks) stopping output...`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [switch_6342:3] Switch to random_6332.`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [random_6332:3] Switch to audio_to_stereo_6330.`
`stations_1_ec748fd73e05 | 2019/02/06 15:38:52 [main:3] Shutdown started!`

**Screenshots**
![image](https://user-images.githubusercontent.com/37590500/52480219-552e2400-2bab-11e9-8726-ee26126e0dd3.png)
![image](https://user-images.githubusercontent.com/37590500/52480232-5d865f00-2bab-11e9-9649-436d42cb89ad.png)

**Comment by SlvrEagle23** [comment]
@NLLucifer Since this seems to stem directly from custom code you've added to Liquidsoap's configuration, this may be better suited as a question for the Liquidsoap team themselves [on their GitHub](https://github.com/savonet/liquidsoap).

**Comment by NLLucifer** [comment]
@SlvrEagle23 did you add a new liquidsoap version?

**Comment by NLLucifer** [comment]
Update: Since the last update it seems to work. I don't know what changed to be honest.
@SlvrEagle23

**Comment by SlvrEagle23** [comment]
@NLLucifer We reverted some changes to how we do live broadcasting, which may have also fixed your issue in the process.
