### ISSUE TITLE
Unable to clone stations (Options: Mediashare + Copy Playlists)

### ISSUE THREAD

**Issue by ma-vie** [AzuraCast/AzuraCast#1161]
Hello ,  
since last update (0.9.2) i am not able to clone playlists  (with mediashare and copy playlist options)

**Installation method**
Docker 

**Describe the bug**
Getting this Error (500 Rounding is necessary to represent the result of the operation at this scale.
RoundingNecessaryException.php : 17)  when I want to clone a playlist with this options:

(My Options)
![image](https://user-images.githubusercontent.com/45437669/52503966-4ebd9d80-2be7-11e9-9328-2af22697d5b4.png)

(Getting this Error)
![image](https://user-images.githubusercontent.com/45437669/52503935-3483bf80-2be7-11e9-8a4d-b02ca2fa7f4f.png)

Logs from docker 

web_1       | Feb  8 20:21:28 bddca9e4041a php-fpm[50]: [WARNING] [pool www] child 10881 said into stderr: "[2019-02-08 21:21:28] AzuraCast.ERROR: Rounding is necessary to represent the result of the operation at this scale. {"file":"/var/azuracast/www/vendor/brick/math/src/Exception/RoundingNecessaryException.php","line":17,"code":0} []"

**Comment by SlvrEagle23** [comment]
@ma-vie Will look into this error on our end. Just out of curiosity, how large is the media library on the station you're trying to clone?

**Comment by ma-vie** [comment]
@SlvrEagle23  I have about 9gb mp3 files.
![image](https://user-images.githubusercontent.com/45437669/52563898-ec40e900-2e02-11e9-81ab-0ab9046df4a7.png)

**Comment by SlvrEagle23** [comment]
@ma-vie The cause of this issue has been identified and resolved as of the latest update.
