### ISSUE TITLE
Create Dj Account API

### ISSUE THREAD

**Issue by gothicdude1044** [AzuraCast/AzuraCast#1163]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to see an API Feature that can run from website so that djs can create their accounts so they know the passwords and not myself Per station like it pulls all the stations and ask what station would you like to create a dj account for

**Describe alternatives you've considered**
none

**Additional context**

**Comment by SlvrEagle23** [comment]
Streamer/DJ accounts are now an API endpoint. Check out our [API documentation](https://www.azuracast.com/api/#/Stations%3A%2520Streamers%2FDJs) for more information.
