### ISSUE TITLE
Azuracast Login with an Streamer Account

### ISSUE THREAD

**Issue by scysys** [AzuraCast/AzuraCast#1166]
**Is your feature request related to a problem? Please describe.**

When I add an Streamer Account on: "/station/1/streamers/add" it would be great if this User also can Login on Azuracast itself and can handle things based on some Permissions like: AutoDJ Control, Playlist Control etc.

**Comment by JDBlackman** [comment]
I'm sure streamer accounts/azura accounts are different. To create accounts with specific permissions on azura you can use the "/admin/users" page. You can then create custom roles at "/admin/permissions".

**Comment by SlvrEagle23** [comment]
@scysys The answer by @JDBlackman is correct; DJ accounts are solely for authenticating with the radio software when broadcasting, not for logging in to AzuraCast itself.
