### ISSUE TITLE
installation error on scaleway armv8 

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#117]
Hello i do get this error on a fresh installation with ubuntu 16.04 arm version
Please help in this.

TASK [influxdb : Create 'stations' database] ***********************************
failed: [localhost] (item=stations) => {"failed": true, "item": "stations", "msg": ""}

RUNNING HANDLER [azuracast-user : send user notification] **********************
        to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP *********************************************************************
localhost                  : ok=27   changed=21   unreachable=0    failed=1

**Comment by griffon56** [comment]
Hi, I got the same error when I tried to install on a docker container.

**Comment by SlvrEagle23** [comment]
@surihost Can you please include the entire log from the installation process? It seems likely that there's an error in the installation further up. It's also possible that the delay added to the InfluxDB part of the installer isn't sufficient for a slower ARM processor.

I wouldn't normally advise manually messing around in the code, but if you edit line 30 on the file:
`util/ansible/roles/influxdb/tasks/main.yml`
and increase the number from 15 to, say, 30 or more, then try installing again...it might work. Let me know if it does.

@griffon56 Currently we don't support installing AzuraCast inside a Docker container. There have been plenty of requests to implement Docker support, but we would want to "do it right" and actually have multiple docker containers that interact with one another and follow docker's recommended one-process-per-container rules. The reason the main AzuraCast installer fails is because Docker containers have no suitable replacement for an init system, so services like nginx/mysql/influx have no way to register themselves as always-running.

**Comment by surihost** [comment]
I changed it to 90 but still get the same error:

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [init : debug] ************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "Running Ansible on localhost with OS Ubuntu xenial 16.04 aarch64 (pr                                                                                                 oduction)"
}

TASK [init : debug] ************************************************************
skipping: [localhost]

TASK [init : Update apt] *******************************************************
changed: [localhost]

TASK [init : Install system packages] ******************************************
changed: [localhost] => (item=[u'apt-transport-https', u'curl', u'wget', u'tar',                                                                                                  u'build-essential', u'python-software-properties', u'pwgen', u'whois', u'python                                                                                                 -pip', u'lnav'])

TASK [init : Update pip components] ********************************************
changed: [localhost] => (item=pip)

TASK [git : Install Git] *******************************************************
ok: [localhost]

TASK [azuracast-user : (Prod) Generate AzuraCast Password] *********************
changed: [localhost]

TASK [azuracast-user : Create Groups] ******************************************
ok: [localhost] => (item=www-data)
changed: [localhost] => (item=admin)

TASK [azuracast-user : Assign User Password] ***********************************
ok: [localhost]

TASK [azuracast-user : Create AzuraCast User] **********************************
changed: [localhost]

TASK [azuracast-user : Modify www-data User] ***********************************
changed: [localhost]

TASK [azuracast-user : (Dev) Modify vagrant User] ******************************
skipping: [localhost]

TASK [azuracast-user : (Dev) Modify www-data User] *****************************
skipping: [localhost]

TASK [azuracast-user : (Dev) Add azuracast User to vagrant Group] **************
skipping: [localhost]

TASK [azuracast-config : Use Default Configuration Files] **********************
changed: [localhost] => (item=db)
changed: [localhost] => (item=influx)
changed: [localhost] => (item=cache)

TASK [azuracast-config : Write current environment to file.] *******************
changed: [localhost]

TASK [azuracast-config : Touch .deploy_run file] *******************************
changed: [localhost]

TASK [azuracast-config : Set Permissions on Base App Folder] *******************
changed: [localhost] => (item=/var/azuracast)

TASK [azuracast-config : Create System Folders] ********************************
changed: [localhost] => (item=/var/azuracast/www_tmp)
changed: [localhost] => (item=/var/azuracast/www_tmp/cache)
changed: [localhost] => (item=/var/azuracast/www_tmp/sessions)
changed: [localhost] => (item=/var/azuracast/www_tmp/proxies)
changed: [localhost] => (item=/var/azuracast/stations)
changed: [localhost] => (item=/var/azuracast/servers)

TASK [azuracast-radio : Install IceCast2 (14.04)] ******************************
skipping: [localhost]

TASK [azuracast-radio : Install IceCast2 (16.04)] ******************************
changed: [localhost]

TASK [azuracast-radio : Link Fallback Error MP3] *******************************
changed: [localhost]

TASK [azuracast-radio : Remove problematic LiquidSoap plugins] *****************
ok: [localhost] => (item=[u'liquidsoap-plugin-all', u'liquidsoap-plugin-opus'])

TASK [azuracast-radio : Install LiquidSoap] ************************************
changed: [localhost] => (item=[u'liquidsoap', u'liquidsoap-plugin-ogg', u'liquid                                                                                                 soap-plugin-vorbis', u'liquidsoap-plugin-lame', u'liquidsoap-plugin-flac', u'liq                                                                                                 uidsoap-plugin-icecast'])

TASK [azuracast-radio : Download ShoutCast 2 (x86)] ****************************
skipping: [localhost]

TASK [azuracast-radio : Download ShoutCast 2 (x64)] ****************************
skipping: [localhost]

TASK [azuracast-radio : Extract ShoutCast 2 Binary] ****************************
skipping: [localhost]

TASK [influxdb : Add InfluxDB repo file] ***************************************
changed: [localhost]

TASK [influxdb : Add InfluxDB repo key] ****************************************
changed: [localhost]

TASK [influxdb : Update apt cache] *********************************************
changed: [localhost]

TASK [influxdb : Install python-influxdb] **************************************
changed: [localhost] => (item=influxdb)

TASK [influxdb : Install InfluxDB] *********************************************
changed: [localhost] => (item=[u'influxdb'])

TASK [influxdb : restart influxdb] *********************************************
changed: [localhost]

TASK [influxdb : Pause to allow InfluxDB to spin up] ***************************
Pausing for 90 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost]

TASK [influxdb : Create 'stations' database] ***********************************
failed: [localhost] (item=stations) => {"failed": true, "item": "stations", "msg                                                                                                 ": ""}

RUNNING HANDLER [azuracast-user : send user notification] **********************
        to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP *********************************************************************
localhost                  : ok=27   changed=21   unreachable=0    failed=1

**Comment by surihost** [comment]
Hello,

Scaleway increased their core on the  arm8 64bit , so i tried again to install on it.
But still stuck here:

fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for 127.0.0.1:8086"}

**Comment by SlvrEagle23** [comment]
@surihost I still haven't heard back from Influx on why they're spitting out the wrong package for ARM64 architectures. That's what's causing the problem you're seeing there.

For now, sadly the situation's a bit out of our hands, but I'm keeping an eye on it.
