### ISSUE TITLE
Error 500 Now Playing Data

### ISSUE THREAD

**Issue by danielrodrigotest** [AzuraCast/AzuraCast#1171]
Hi everyone. I'm using the new version of azuracast, but when I use the Now Playing Data - Run task I get the same error.
500
Call to a member function text() on null
Icecast.php : 118
![screenshot 2019-02-13 at 13 51 33](https://user-images.githubusercontent.com/40525323/52728701-88e7c000-2f96-11e9-82cf-c6f4fb16fe0c.png)

**Comment by SlvrEagle23** [comment]
@danielrodrigotest We're experimenting with ways to fix some edge case issues we're having with pulling Now Playing data from radio services, and it appears we unintentionally caused an unrelated problem. I've reverted the changes and it should fix the issue on your end if you update to the latest version.

**Comment by danielrodrigotest** [comment]
Thanks for the reply. I finally made an update from ssh docker and works great!!
![screenshot 2019-02-14 at 00 48 05](https://user-images.githubusercontent.com/40525323/52761469-4a7fee80-2ff2-11e9-854c-36b006db2dae.png)
![screenshot 2019-02-14 at 00 48 25](https://user-images.githubusercontent.com/40525323/52761470-4a7fee80-2ff2-11e9-8ba3-5c986202b235.png)

**Comment by SlvrEagle23** [comment]
@danielrodrigotest Good to hear!
