### ISSUE TITLE
Add S3 Spec Support for Station File Storage (S3 DO Spaces, Wasabi, etc.)

### ISSUE THREAD

**Issue by SlvrEagle23** [AzuraCast/AzuraCast#1173]
Over the last few months we've been directly working to build the infrastructure that would allow us to expand out to support greater flexibility in our storage options. We recently completed the transition over to League's Flysystem package, which abstracts out several filesystem operations such that they are identical regardless of whether they're happening locally or remotely. We've also implemented a Redis cache for Flysystem adapters and already included the Amazon S3 connector for Flysystem.

The purpose of this issue is to document the status and completion of the remaining elements needed to allow full S3 bucket support, including support for other services that implement the S3 standard (such as DigitalOcean spaces, Wasabi, etc).

Below are the tasks that I have already outlined for this project:

- [ ] Add the necessary form elements to the `config/forms/station.php` form:
       - Access Key ID
       - Secret
       - Endpoint URI (if different from AWS itself)
       - Region
       - Bucket Name

- [ ] Create a validator for form submission that will check the above settings and ensure that the web app can successfully connect to the bucket as specified before continuing.

- [ ] Disable the "Manual AutoDJ" mode for people using the S3 connector because file URIs will not correctly work when parsed directly by Liquidsoap instead of AzuraCast.

- [ ] Implement a handler in the AzuraCast AutoDJ class that copies requested songs over to a temporary always-local directory (one already exists at `temp://` in Flysystem) and sends the absolute paths from that directory to Liquidsoap as the next playing song.

**Comment by Vaalyn** [comment]
For local development of this feature I'd recommend using [Minio](https://github.com/minio/minio) a S3 protocol compatible object storage server ready to go as docker container. This removes the hassle of setting up an object store on a cloud vendor. I've personally used this for development of features that access S3 buckets in prod environments and really liked it.

**Comment by MrSteelMiner** [comment]
It would be nice to be able to use Nextcloud as external storage 👍

**Comment by internethole** [comment]
Hi guys, has there been any progress on this?

I am eagerly awaiting the completion.  I am contemplating if I should go to Upwork to find someone to create a solution. 


I really need this!

**Comment by SlvrEagle23** [comment]
@internethole Our core developer staff is available to do contractor work if needed, and can be sponsored to build features directly into AzuraCast that wouldn't otherwise be high priorities of ours to implement (like this one). Feel free to contact me via my GitHub e-mail.

**Comment by internethole** [comment]
Ok guys how much would this cost?

**Comment by SlvrEagle23** [comment]
@internethole We don't currently have a "feature bounty" system where we can set a price on a specific feature, but you're always encouraged to [donate to AzuraCast](https://www.azuracast.com/donate.html) either via one-time or ongoing monthly donation to help support our development.

**Comment by trodick** [comment]
What is the progress on this? I can totally see how something like this would benefit people who don't have the financial resources to maintain large amounts of volume/block storage on the server running AzuraCast, but could use something like Backblaze B2 (as that now has S3-compatible APIs and is the cheapest object storage around).

**Comment by internethole** [comment]
Good to know, Maybe we can back on this project.
Thanks for the update.

Victor
    On Monday, July 8, 2019, 11:45:57 AM PDT, SlvrEagle23 <notifications@github.com> wrote:  
 
 
@internethole Our core developer staff is available to do contractor work if needed, and can be sponsored to build features directly into AzuraCast that wouldn't otherwise be high priorities of ours to implement (like this one). Feel free to contact me via my GitHub e-mail.

**Comment by vineettalwar-sm** [comment]
@SlvrEagle23 
Any progress here ?
I have found one link, may be this could be helpful in this case.
https://docs.docker.com/registry/storage-drivers/s3/
