### ISSUE TITLE
Change log

### ISSUE THREAD

**Issue by inetactief** [AzuraCast/AzuraCast#1175]
Hi,

Where can we see the change log of the new version?
We see AzuraCast version 0.9.2 is now available. You are currently running version 0.9.1.

Best regards,
Michel

**Comment by Vaalyn** [comment]
Hey, you can see the changelog for version 0.9.2 [here](https://github.com/AzuraCast/AzuraCast/releases/tag/0.9.2).

For every complete release you can find the changelogs [here](https://github.com/AzuraCast/AzuraCast/releases).

**Comment by inetactief** [comment]
Thank you!

**Comment by SlvrEagle23** [comment]
@inetactief I added a link to the GitHub releases page from the new version notification to help clear up any confusion.
