### ISSUE TITLE
Using same playlist on the same time and weight 

### ISSUE THREAD

**Issue by inetactief** [AzuraCast/AzuraCast#1176]
We use now  AzuraCast • v0.9.1, #8f7d801 (2019-02-06 3:15) • Docker • PHP 7.2

When we have program 2 ore more playlist on the same time the playlist only that have the 
highest weight we hear playing. 

So we only hear the playlist with the highest weight. We want to hear 20% of playlist 1 and 80% playlist 2 for example. How can we do that? Can there play 2 playlist on the same time?

**Comment by SlvrEagle23** [comment]
@inetactief While originally we only applied the "weighting" principle to general rotation playlists, it makes sense to apply it to any scenario when multiple playlists of the same type might overlap one another. I was in the process of refactoring the AutoDJ for other reasons, but I went ahead and included the ability to shuffle between playlists of the same type that should play at the same time.
