### ISSUE TITLE
Web DJ authentication issue

### ISSUE THREAD

**Issue by muppathimoonu** [AzuraCast/AzuraCast#1177]
if password contains special characters, Web DJ authentication returns false. Same username password is working with BUTT.

**Comment by SlvrEagle23** [comment]
@muppathimoonu Which special characters in particular have you tested? The command to authenticate a DJ is escaping most characters, but it might have issues with single quotes.

**Comment by muppathimoonu** [comment]
I've tried @ _.

**Comment by SlvrEagle23** [comment]
@muppathimoonu I've made some recent improvements to how Liquidsoap escapes strings when sending them over for authentication; let me know if this helps in any way.

**Comment by afonsosantos** [comment]
It's now solved after issue #1400 and commit https://github.com/AzuraCast/AzuraCast/commit/eb82cc87b462ff0f1eb00baa3e9f525c73489e06

**Comment by Vaalyn** [comment]
Closing this issue as solved by eb82cc8 and 06a2a5e
