### ISSUE TITLE
RTP Streamin

### ISSUE THREAD

**Issue by darkjedeye** [AzuraCast/AzuraCast#1178]
I am looking for a method to connect and old Ganymed 1002 media player to the stream, but with the mount points being the linking, i am having difficulty, as it wil not accept any alphabetical characters or special characters like /

could i propose maybe a static enabled port such as 8010 or something which could be a static devised port for rtp stream? on shout cast or ice cast? the device i am using apparently requires shout cast.

**Comment by SlvrEagle23** [comment]
@darkjedeye We recently added the ability for you to specify a custom "mount point" name for the incoming DJ connection on Liquidsoap. If you set this mount point name to an empty string, it should allow you to do what you're needing to do.
