### ISSUE TITLE
How to set super administrator from Docker

### ISSUE THREAD

**Issue by danielrodrigotest** [AzuraCast/AzuraCast#1180]
Hi!.
I was adding users to the platform as admin, but I that moment I unchecked my super admin role (I'm the only one super admin in the server). I would like to know how to set me (again) my super admin role through ssh.
Help Please :)
![screenshot 2019-02-16 at 3 59 11 pm](https://user-images.githubusercontent.com/40525323/52903945-d321a900-3203-11e9-8180-688acb6f766d.png)

**Comment by Vaalyn** [comment]
This will require some manual work in the Database via the command line.

Connect to your AzuraCast host machine via ssh, then go into the directory with the `docker-compose.yml`, there you execute this command to enter the mariadb container: `docker exec -it azuracast_mariadb_1 bash` 

In the container execute this command to enter the database: `mysql -hlocalhost -uazuracast -pazur4c457`. Now you can execute SQL commands on the database. First select the azuracast db with `USE azuracast;`. Now execute `SELECT uid, email FROM users;` to get the list of users and use the `uid` of your user and create a new entry in the `user_has_role` table with this command (remember to fill in you users `uid`): `INSERT INTO user_has_role (user_id, role_id) VALUES (<user_id>, 1);`. Now you can exit the db with `exit` and also the container, also with  `exit`. Your user should now have its Super Admin role back.

**Comment by Vaalyn** [comment]
@SlvrEagle23 We may want to also file this as a kind of bug. I think we should disallow users to remove the Super Admin role if the user is the only Super Admin to prevent this situation from occurring in the future.

**Comment by danielrodrigotest** [comment]
how do I get into docker-compose.yml?

**Comment by Vaalyn** [comment]
You do not need to edit the docker-compose.yml. When connected via ssh you need to `cd` into the directory where this file is located at.

**Comment by SlvrEagle23** [comment]
@Vaalyn Agreed, it's a fairly simple validation check to see if you're removing yourself from all roles that would allow you to manage users, which would be unrecoverable by your own account via the web interface.

**Comment by SlvrEagle23** [comment]
@Vaalyn I've implemented several changes in the form handling code for permissions and users that will:
 - Prevent users from deleting their own account
 - Prevent users from changing their own roles to add/remove permissions
 - Prevent admins from modifying the permissions of the global Super Administrator account

@danielrodrigotest To help you (and others) recover from this situation, there's now a new CLI command, which you can access using:

```
./docker.sh cli azuracast:account:set-administrator your-account-email@example.com
```

This will both reset the permissions of the "Super Administrator" account and ensure that the user associated with that e-mail address is assigned to that account, which should repair any permission problems.

You'll have to update to the latest version of the code to access it, but it should still work to recover your account.

**Comment by JCBP1974** [comment]
Please help!

I migrated my Azuracast account from Ansible to Docker but now I can no longer access it with the server link.
What I can do?

**Comment by SC2Mitch** [comment]
You can resolve this by running this command `./docker,sh azuracast:account:set-administrator [email address]`

**Comment by JCBP1974** [comment]
Thank you for helping. I tried using the instrutions but appears ***@***.***:~# ./docker,sh azuracast:account:set-administrator ***@***.***-bash: ./docker,sh: No such file or ***@***.***:~# Enviado desde Correo para Windows De: MitchEnviado: sábado, 11 de junio de 2022 08:05 a. m.Para: AzuraCast/AzuraCastCC: JCBP1974; CommentAsunto: Re: [AzuraCast/AzuraCast] How to set super administrator from Docker (#1180) You can resolve this by running this command ./docker,sh azuracast:account:set-administrator [email address]—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by SC2Mitch** [comment]
Create a new issue then please, this is ancient
