### ISSUE TITLE
nginx proxy manager

### ISSUE THREAD

**Issue by pitsch** [AzuraCast/AzuraCast#1182]
we have a dedicated server running our community radio station which is upgraded from wordpress with centovacast to a docker based setup based on azuracast. there is a staging virtual server for development with the same basic setup but less performance. 

this will enable us to use experimental settings such as stereotool via jackd and Sonerezh for managing the playlist library, or for a libretrime tryout, containerisation will help replacing and incrementally improving the setup. 

there is still an icecast as relay which simply pulls the stream(s), as pushing a relay from azura wasnt stable enough, and to also use the exact same old streaming adress. for higher demand an external icecast relay network is available.  

live sources will preferably broadcast with oggflac, or a high bandwidth mp3. in the future the shows should be available online after live broadcast, with proper id3 tags and auto-added to certain playlists. 

we also run cockpit web panel, a systemd service which uses websockets to keep an overview on backend resources. it also manages the docker containers, which can be  further micromanaged with portainer in an own container if needed. 

finally a local webserver with wordpress and database in a container, which also uses nginx.  with archival and podcast features. this will be a own development process with further needs in special ports and webservices. 

to enable to adapt one nginx reverse proxy to various subdomains, the webserver, including the lets encrypt checkup routine, which is neccessary for webdj, it would be perfect to have nginx more configurable to adapt to changing setups, also to enable a simplified cloudflare caching later on. 

so in any advanced docker setup nginx turns into the plumbing switchboard to redirect subdomains to services.  actively maintained and trending is the nginx proxy manager.  such centralized  docker setup is also more affordable in maintenance compared to renting a bunch of virtual servers to modularize, which is fine for development purposes.

so an addon to the feature wishlist would be adding the project named "nginx proxy manager" as an own container to the azuracast stack, with the current preconfiguration as default for an adaptable advanced nginx setup and the ability to further change and modify nginx in a more secure and comfortable way. 

azuracast 
Is this a way to change Nginx config?
https://github.com/AzuraCast/AzuraCast/issues/941
https://github.com/AzuraCast/AzuraCast/issues/733

cockpit via nginx
https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX
https://gist.github.com/norwat/c3287e023a1be4958f5847331fcbe1b7

nginx proxy manager
https://nginxproxymanager.jc21.com/
https://github.com/jlesage/docker-nginx-proxy-manager

get nginx proxy manager (docker) working with azuracast (docker)
https://github.com/AzuraCast/AzuraCast/issues/453
https://github.com/AzuraCast/AzuraCast/blob/master/util/ansible/roles/nginx/templates/default.j2#L67

**Comment by SlvrEagle23** [comment]
@pitsch The nginx proxy manager is indeed a very nice tool, but my questions are:

- What would be the benefit to the majority of users by including it in the base AzuraCast installation?

- What's stopping you from overriding our current `docker-compose` setup, changing the ports on the `web` container from what they are now to something else, and then spinning this up in its place, then forwarding web traffic over to that modified `web` container? As long as you have a base URL configured properly inside AzuraCast, this should work without issue.

**Comment by pitsch** [comment]
id adds a level of abstraction as well as manageablity in regard to possible setups in terms of hosting contexts. the recommended setup is a dedicated machine, or rather a VM. VMs tend to be unpredictable in cpu usage which is critical for transcoding and resampling. a whole dedicated server might be oversized without using it for other webservices such as the main website, with a cloud backend, recording features etc.  with cdns and relays scalability is handled externally. its good practise to only use one nginx instance and not a cascade of conflicting nginx setups across docker containers, so the moment you scale up the container setup, you either need to repeatedly change and update configurations of nginx within the azuracast stack as the central switchboard, or change the stack and take out nginx into a seperate container, which would fork the codebase.  (current settings could be transfered and locked as default settings for nginx proxy manager, an example the redirect field for the base website, can be simply another subdomain on the same ip, or the useful port 80 stream cache mechanism, reserved streaming ports etc.) such an enhancement would also take the load of nginx related questions away from the azurcacast project, with more than 130 issues relating to nginx. most questions would be redirectable then to another project, and an easier to use setup for many, who rely on finding and modififying the proper nginx recipes, and mix them up with other azuracast settings, which can increase the amount further support requests.
for the moment id be just modify the docker-compose to see how it works indeed. thanks for the prompt reply.

**Comment by SlvrEagle23** [comment]
@pitsch I understand your approach, and I definitely appreciate the suggestion.

AzuraCast is already made up of a _lot_ of different third-party applications that have to mesh and interact together just right to make the finished web radio station operate without issue. I'm always hesitant to add another piece of software to that stack if, for the majority of users of the software, their needs are well served by our current configuration.

With that in mind, currently I don't plan to implement this solution directly into AzuraCast itself.

However, if there are changes that we could make to our existing `web` container that would help make the process of setting this up easier for users who want to, please let me know and I would be happy to work on implementing those. We could also create an instructional guide for any users who are interested in using the nginx proxy manager, as we do indeed get a fair amount of requests about how to make AzuraCast coexist with a web site or other containers.

**Comment by btoplak** [comment]
@pitsch : Those are very good ideas, you inspired me to test some additional approach than I have currently implemented in my lab setup. 
I too have a vision to decouple the Nginx from the rest of those services since it is much more flexible and logical in a microservice concept to have it as a separate entity.

It would be best to start building that in a separate project, to not give unnecessary overhead to AzuraCast main project. If and when this project would have a public testing ready version of additional docker that can seamlessly integrate with the existing AzuraCast cluster of dockerized microservices. If you will start developing something like that let me know, I'd be happy to test and contribute.

**Comment by pitsch** [comment]
tried to not fork and so far have integrated cockpit, fail2ban and a few other things  including cloudflare (sub)domain management. after more testing, especially of the wordpress instance, i can document the steps. it would be much better to have a server wide patchbay for port management of all microservices, instead of tweaking them manually somewhere under the hood and not get it overwritten by updates. still on the to do list is a rock solid integration of stereotool into the liquidsoap backend.

**Comment by btoplak** [comment]
> tried to not fork and so far have integrated cockpit, fail2ban and a few other things including cloudflare (sub)domain management. after more testing, especially of the wordpress instance, i can document the steps.

That sounds interesting, feel free to drop a note when you have it documented. I hope I'll be able to contribute something from my knowledge.

**Comment by colorpride** [comment]
https://docs.azuracast.com/en/administration/docker/multi-site-installation
I use this instruction to work azurecast + nginxproxymanger
Everything is working.

netstat -tnulp
tcp        0      0 0.0.0.0:10080           0.0.0.0:*               LISTEN      azuracast
tcp        0      0 0.0.0.0:10443           0.0.0.0:*               LISTEN      azuracast
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      nginxproxymanager
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      nginxproxymanager

Strange networking logic in the azuracast docker container, don't you think?
why create several brigde networks without logic or am I misunderstanding something?
