### ISSUE TITLE
Cloning a station not possible

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1183]
**Installation method**
Traditional

**Describe the bug**
Clone a station

**To Reproduce**
1. Go to "Manage Stations"
2. Click "Clone" on a station
3. Click the button "CREATE NEW STATION"
→ Error 500

**Expected behavior**
A second station is created with the settings of the original one

**Relevant Logs**
[2019-02-18 13:08:59] AzuraCast.ERROR: Rounding is necessary to represent the result of the operation at this scale. {"file":"/var/azuracast/www/vendor/brick/math/src/Exception/RoundingNecessaryException.php","line":17,"code":0} []

**Screenshots**
![grafik](https://user-images.githubusercontent.com/47743654/52950587-ec4f6480-337f-11e9-9741-6eeff93c4876.png)

**Device(s):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Firefox
 - Version: 60.5.1esr
[access.log](https://github.com/AzuraCast/AzuraCast/files/2875579/access.log)
[app.log](https://github.com/AzuraCast/AzuraCast/files/2875580/app.log)
[error.log](https://github.com/AzuraCast/AzuraCast/files/2875581/error.log)

It's a fresh Ubuntu 18.04, just ran the install.sh
Everything else runs perfectly and smooth.

**Comment by SlvrEagle23** [comment]
@MrSteelMiner What are the settings you're using when cloning the station? I'm having trouble reproducing the issue on my end.

**Comment by SlvrEagle23** [comment]
@MrSteelMiner Was able to find the issue and resolve it in the latest update.

**Comment by ma-vie** [comment]
@SlvrEagle23 @SlvrEagle23  made an update -> now it works perfectly. Thank you 👍
