### ISSUE TITLE
Graphical playlist schedule

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1184]
It would be great to have something like a "drag-and-drop-playlist-schedule". We used the webinterface of "LautFM", a german free-webradio-provider. Their playlist-schedule-interface looks like this:
![grafik](https://user-images.githubusercontent.com/47743654/52952124-f4110800-3383-11e9-8470-1088c16b58cf.png)

So, it's possible to play a playlist more than one time a day

**Comment by SlvrEagle23** [comment]
Merging with #639.
