### ISSUE TITLE
Enable ReplayGain

### ISSUE THREAD

**Issue by rubensben** [AzuraCast/AzuraCast#1187]
Hi AzuraCast team and amazed to see the great work  ! Here Rubens, from the SolarSoundSystem.org (we are building a network of sustainable sound systems) and also have a solar powered radio, Radio3s.org that I'm taking care of. I just switched from Airtime to Azuracast as the airtime dev was pretty dead and could not work on Ubuntu 12+ and realize they are some features that would improve greatly the platform 

Feature #003 : As in Airtime, it would be great to be have the possibility to auto adjust the level of the files in order to have a constant audio level and avoid a too low / too loud audio experience. https://en.wikipedia.org/wiki/ReplayGain

I'm adding other features as independent Issues as I've understood it's more practical development-wize. 
BEST !

**Comment by Vaalyn** [comment]
You can enable replay gain by adding this `enable_replaygain_metadata()` to your stations AutoDJ Advanced Custom Configuration in the station profile editor. See [this page](https://www.liquidsoap.info/doc-1.3.6/replay_gain.html) of the Liquidsoap documentation for further information about replay gain.

**Comment by rubensben** [comment]
Thanks boss
