### ISSUE TITLE
pagination not showing

### ISSUE THREAD

**Issue by rubensben** [AzuraCast/AzuraCast#1189]
Using v0.9.2, #bbcfc05 (2019-02-15 19:13) • Docker • PHP 7.2, the pagination of the Music File Explorer is not working well

![pagination bug](https://user-images.githubusercontent.com/4449630/52972406-7c62cd80-33c3-11e9-99eb-581c3c858d20.JPG)

**Comment by SlvrEagle23** [comment]
@rubensben What do you mean "not working well"?

**Comment by rubensben** [comment]
Hi @SivrEagle23. sorry being not specific enough. I mean that the supposed arrows for next / last / previous / first pages are hidden.  Inspecting the elements tellse that the buttons are here and I can click them but they are hidden. I checked the CSS and I don't believe it comes from there

**Comment by Vaalyn** [comment]
This issue is caused because some icons are referencing icons from the `Material Design Iconic Font` which was removed when we upgraded to Bootstrap 4. I'll look into replacing these icons with icons from the `Material Icons` font we use.

**Comment by SlvrEagle23** [comment]
@rubensben This fix has been merged into the main code. Thanks @Vaalyn for the help!
