### ISSUE TITLE
Send default Artist + Title to Icecast when going live

### ISSUE THREAD

**Issue by rubensben** [AzuraCast/AzuraCast#1190]
Hi AzuraCast team and amazed to see the great work  ! Here Rubens, from the SolarSoundSystem.org (we are building a network of sustainable sound systems) and also have a solar powered radio, Radio3s.org that I'm taking care of. I just switched from Airtime to Azuracast as the airtime dev was pretty dead and could not work on Ubuntu 12+ and realize they are some features that would improve greatly the platform 

Feature #004 : We are doing a lot of lives, and using Mixxx, the metadata are not updated unless we put a song in the application (then it sends the correct static artist + title variable set in the broadcast settings). Would it be possible to set a default artist + title before waiting for the ones of the stream or if no information is sent by the streaming service (mixxx / butt)? This would be much better than having wrong informations (aka the playlisted track or the previous stream informations

I'm adding other features as independent Issues as I've understood it's more practical development-wize. 
BEST + thanks in advance !

**Comment by Vaalyn** [comment]
This seems to be the same feature like this one here #1159. If that is correct I'd close this issue in favor of the other one to keep track of it there.

**Comment by rubensben** [comment]
yes, good eyes ! thanks @Vaalyn you can close this
