### ISSUE TITLE
Cannot make work the Ssl certificate on nginx

### ISSUE THREAD

**Issue by rubensben** [AzuraCast/AzuraCast#1193]
Hi again, I'm using the docker installation (#50f4a1a) and already have a LAMP configuration on my host with Let's encrypt generating the certificates automatically for my host already. So on, I have mapped the certificate dir from my host on the docker and have linked the certificates on both "web" and "stations" service. Then, I have modified the Icecast and nginx conf files in order to link the ssl certificates to the good ones. Everything works great with Icecast but i can't make it work with NGINX : or I have to set the parameter "ssl on" and then I got it work only on the secured connection, or I set the certificate but the ssl connection is not working. I also tried with 2 servers (one on 80 and a redirection http>https), another one on 444 with the ssl on and the cerficiates) Any clues ?

Here are the different versions of the azucaract.conf I have tried :

Https connections not working
```
server {
listen 80;
listen 443 default_server ssl;

    ssl_certificate        /etc/nginx/ssl/ssl.crt;
    ssl_certificate_key    /etc/nginx/ssl/ssl.key;

    ssl_protocols TLSv1.2;
#    ssl_prefer_server_ciphers on;
#    ssl_dhparam /etc/nginx/dhparam.pem;
#    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
#    ssl_ecdh_curve secp521r1:secp384r1:prime256v1;
    ssl_session_timeout  10m;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;

```

Not working on non-https connections (redirection loop)
```
server {
listen 80;
return 301 https://$solarsoundsystem.org:8096$request_uri;
}

server {
listen 443 default_server ssl;

ssl         on;
ssl_certificate        /etc/nginx/ssl/ssl.crt;
ssl_certificate_key    /etc/nginx/ssl/ssl.key;

    ssl_protocols TLSv1.2;
#    ssl_prefer_server_ciphers on;
#    ssl_dhparam /etc/nginx/dhparam.pem;
#    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
#    ssl_ecdh_curve secp521r1:secp384r1:prime256v1;
    ssl_session_timeout  10m;
```

Only SSL working : 
```
server {
listen 80;
listen 443 default_server ssl;

    ssl_certificate        /etc/nginx/ssl/ssl.crt;
    ssl_certificate_key    /etc/nginx/ssl/ssl.key;
ssl         on;
    ssl_protocols TLSv1.2;
#    ssl_prefer_server_ciphers on;
#    ssl_dhparam /etc/nginx/dhparam.pem;
#    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
#    ssl_ecdh_curve secp521r1:secp384r1:prime256v1;
    ssl_session_timeout  10m;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;

```

Thx in advance for the help ! I'm now using stunnel4 but I don't feel it's so clean

**Comment by rubensben** [comment]
any direction to fix that ?

**Comment by RAFAEL454228** [comment]
I was able to solve it with a private ssl of Certified Comodo PositiveSSL in hostinger.com they configure it in your vps

**Comment by rubensben** [comment]
Thanks RAFAEL but the idea here is to make it work with already existing ssl certificate, not to buy new ones
