### ISSUE TITLE
After adding .m4a format recorded file, page freezes, 

### ISSUE THREAD

**Issue by muppathimoonu** [AzuraCast/AzuraCast#1199]
After adding a recorded file in .m4a format WebDJ page Freezes, Songs are playing no issues with broadcast. 
just the playlist Output freezes like this. 
![screenshot 2019-02-20 at 1 12 08 am](https://user-images.githubusercontent.com/13084148/53042760-033fa500-34ad-11e9-8336-0eb39603ee5b.png)

**Comment by Vaalyn** [comment]
Bump, still have to test this

**Comment by ErnestPH** [comment]
ongoing...
