### ISSUE TITLE
Djs Cannot Login to Shoutcast Dj Port with Shoutcast Installed

### ISSUE THREAD

**Issue by gothicdude1044** [AzuraCast/AzuraCast#1204]
Ive Checked the Logs on Azuracast and the Liquid soap configs turns out my djs have to login to the ICE Cast DJ Port 8005 even though i have shout cast v2 server setup how can we get the configuration to update that the shoutcast server is installed and make the ports available

**Installation method**

DOcker

**Host OS (for Docker installations)**

Ubuntu Bionic beaver 18.04 lts

**Describe the bug**

My Djs cannot login to Shoutcast port to DJ Live they have to use the ices cast port for their stream to become live I have Current Installed Version
SHOUTcast version "SHOUTcast DNAS/posix(linux x64) v2.6.0.750 (Dec 7 2018)

**To Reproduce**

**Expected behavior**

I expect my djs to be able to login either in port 8006 or i think is 8004 for the sc v2 clients

**Relevant Logs**

2019/02/21 09:23:01 [lang:3] Authenticating DJ: djdan
2019/02/21 09:23:01 [lang:3] AzuraCast DJ Auth Response: true
2019/02/21 09:23:01 [decoder:3] Method "MAD" accepted "audio/mpeg".
2019/02/21 09:23:01 [lang:3] DJ Source connected! [("icy-name","Dj Dan The Man On Insane Radio"), ("icy-genre","Various"), ("icy-url","http://darkphystgaming.com/insaneradio/night-club"), ("icy-irc","#audiorealm"), ("icy-icq","NA"), ("icy-aim","NA"), ("icy-pub","1"), ("icy-br","192"), ("content-type","audio/mpeg")]
2019/02/21 09:23:01 [lang:3] AzuraCast Live Connected Response: ["received"]
2019/02/21 09:23:01 [threads:3] Created thread "harbor source feeding" (2 total).
2019/02/21 09:23:01 [insane_radio_input_streamer:3] Decoding...
This is NOT an ICECAST CLIENT its supposed to be a Shoutcast v1 client and Shoutcast v2 does
not work
This is Part of the Liquidsoap Config in question
# Live Broadcasting
live = audio_to_stereo(input.harbor("/", id="insane_radio_input_streamer", port=8005, user="shoutcast", auth=dj_auth, icy=true, max=30., buffer=5., icy_metadata_charset="UTF-8", metadata_charset="UTF-8", on_connect=live_connected, on_disconnect=live_disconnected))
ignore(output.dummy(live, fallible=true))
radio = fallback(id="insane_radio_live_fallback", track_sensitive=false, [strip_blank(max_blank=30.,live), radio])

**Screenshots**

![screensambc](https://user-images.githubusercontent.com/1172741/53159711-648e7380-3594-11e9-80f4-3eede028f60a.png)

**Device(s):**
 - Device: 
Desktop 
 - OS: 
Windows 10 / Linux Ubunti 18.04 lts
 - Browser: 
Chrome
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
In the documentation for [`Streaming Software`](https://github.com/AzuraCast/azuracast.com/blob/master/StreamingSoftware.md) in the section `ShoutCast Mode` we mention that the streaming client Butt will increment the port that you enter in the streaming software when using the ShoutCast protocol by 1. This could also be the case for other streaming applications.

I can't identify what software you are using from your screenshot, can you clarify what's the name of it?

> This is NOT an ICECAST CLIENT its supposed to be a Shoutcast v1 client and Shoutcast v2 does
not work

The `DJ Account` feature is implemented in Liquidsoap so when you are connecting to AzuraCast with a DJ Account you will not connect directly to ShoutCast or IceCast but to Liquidsoap and LS only support the ShoutCast v1 protocol. This is not something we can change since LS is upstream software.

**Comment by gothicdude1044** [comment]
I use Sam Broad Caster which Implentens Use of either shoutcast v1 or shoutcast v2 Connection a you see in my screen print port 8006 will not work and the configs for liquidsoap only show port 8005 usable and its only ice cast

**Comment by Vaalyn** [comment]
Thank you for the clarification.

Depending on how tech savvy you are you can check if Sam Broadcaster does the same thing that Butt does by using [Wireshark](https://www.wireshark.org/) to listen to the traffic from your PC to AzuraCast and check which port is really used in the connection.

The ShoutCast v2 protocol will not work. Like I said it's not supported by Liquidsoap so you will have to use ShoutCast v1 protocol for the DJ Accounts.

> then that brings another issue up the server then sometimes does not register that is a shoutcast stream

I'm not sure I understood this issue correctly. Can you explain to me what behaviour your installation is showing you?

**Comment by Vaalyn** [comment]
@gothicdude1044 Is there any update to this issue from your side?

**Comment by gothicdude1044** [comment]
the Djs still have to use the icecast port in my setup it 8005
and according to the azuracast dashboard for that station the djs are supposed to login to 8006 for shoutcast v1 however the live setup is working however it is i have dj streaming to shoutcast using 8005 and it comes over the stream so IDK

________________________________

**Comment by Vaalyn** [comment]
@gothicdude1044 Have you checked if your broadcasting software is internally incrementing the port that your DJs configure in it? If not I think there are easier ways to check this than with Wireshark. [Here](https://stackoverflow.com/questions/48198/how-can-you-find-out-which-process-is-listening-on-a-port-on-windows) is a link to StackOverflow where it's explained on how to check which ports are used by which process on Windows.

**Comment by rolradio** [comment]
It is true that if you stream to azuracast with a shoutcast V1 encoder, you must use the icecast port.
This is indeed incorrectly written in the Dj accounts.
It would be nice if this could be adjusted. (just adjust text)

**Comment by ErnestPH** [comment]
This can be correctly added… But not sure if the developers will agree on it.

**Comment by ErnestPH** [comment]
> It is true that if you stream to azuracast with a shoutcast V1 encoder, you must use the icecast port.
> This is indeed incorrectly written in the Dj accounts.
> It would be nice if this could be adjusted. (just adjust text)

I made a pull request… #1726 for both your request. If approved, the Shoutcast will now show the same port with Icecast to avoid confusion...

**Comment by gothicdude1044** [comment]
It would also be nice if shoutcast v2 was properly working in azuracast I know it can be done centova cast already has that setup using liquid soap and the shoutcast dnas that is downloadable is shoutcast v2 2.**** I cant remember of top of my head

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
