### ISSUE TITLE
Liquidsoap time doesn't apply local time

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1205]
Hi, 

when I set my local time in System Settings (e.g., UTC+1), Liquidsoap seems to use the default time (UTC+0). It can be seen on the timestamps of the Liquidsoap log. Timed Azuracast playlists are time-correct (Azuracast seems to be using the correct local time) but if I use custom Liquidsoap configurations I have to use UTC+0 time.

Is there a way to change Liquidsoap's time? 

Peter

**Comment by SlvrEagle23** [comment]
@gammaw Liquidsoap is configured to use the server's default time zone. When we're writing to Liquidsoap configuration, we always calculate the difference between the time zone set in the web interface and the system's default time zone to allow for that difference.

It's recommended, however, that UTC remain as the system's default time zone.
