### ISSUE TITLE
Cover art not shown for tracks in custom playlists 

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1207]
Hi, 

I'm using a custom Liquidsoap playlist similar to here: https://github.com/AzuraCast/azuracast.com/blob/master/AdvancedPlaylists.md

It seems working in general but the cover art of the current song is not shown. The nowplaying api (/api/nowplaying) also does not contain the URL of the art work (instead, it contains the URL of the default art work). 

After a song from a custom playlist was played the cover art will not be shown for all songs which come after (doesn't matter if it's a standard or a custom playlist). 

Any idea? 

Peter

**Comment by gammaw** [comment]
I guess it's a duplicate. Just found this: https://github.com/AzuraCast/AzuraCast/issues/608

**Comment by SlvrEagle23** [comment]
@gammaw If you're using advanced Liquidsoap playlists, then Liquidsoap doesn't have the proper metadata necessary to send back to AzuraCast to indicate which song is playing, which prevents it from having the "rich metadata" experience that it has when it directly controls the next playing song. This is a known issue that we're working on resolving under the hood, but for now songs played through advanced playlists will be lacking in metadata.

**Comment by gammaw** [comment]
@SlvrEagle23 is there a way to query the cover art's URL based on the song's ID? The song's ID is available via the nowplaying API even for custom playlists.

**Comment by gammaw** [comment]
@SlvrEagle23 wow, since yesterday's update cover art is conveyed in the nowplaying web API also for songs in custom playlists! We built our custom solution but I'm still very happy about it :)

But what happened? Can it be a side effect of a commit you have recently done about the playlists?
