### ISSUE TITLE
Add rate limiting for now playing updates posted to twitter

### ISSUE THREAD

**Issue by NewsUpdate24** [AzuraCast/AzuraCast#1211]
Twitter bloocked my api from posting.

Reason may be to many posts in short time.

When i push test i get; 
Twitter returned code 403
response_body

"{\"errors\":[{\"message\":\"Application cannot perform write actions. Co
Maby set a limit for how offen to post or a minimum duration to post or post every ** min. or post every ** track?
@ScratchRadio_
·
-----------------------------,----
Whats up? @twitter
 will not let us post our #NowPlaying info. You still find now playing on (link: http://Radio.Scratch.DJ) Radio.Scratch.DJ . @AzuraCast
 maby it need the uption of posting every ** min.

@SlvrEagle23
Replying to @ScratchRadio_
 and @AzuraCast
It's possible you're being rate-limited by Twitter for posting too frequently. We can add support for rate limiting, but it's a new enhancement request as the feature doesn't currently exist. Please submit a request for it on our GitHub: (link: https://github.com/AzuraCast/AzuraCast/issues/new/choose) github.com/AzuraCast/Azur…

**Comment by NewsUpdate24** [comment]
@ScratchRadio_
·
Feb 21
Whats up? @twitter
 will not let us post our #NowPlaying info. You still find now playing on (link: http://Radio.Scratch.DJ) Radio.Scratch.DJ . @AzuraCast
 maby it need the uption of posting every ** min?
@SlvrEagle23
Replying to @ScratchRadio_
 and @AzuraCast
It's possible you're being rate-limited by Twitter for posting too frequently. We can add support for rate limiting, but it's a new enhancement request as the feature doesn't currently exist. Please submit a request for it on our GitHub: (link: https://github.com/AzuraCast/AzuraCast/issues/new/choose) github.com/AzuraCast/Azur…

**Comment by Vaalyn** [comment]
Out of curiosity can you tell me a bit about your setup.
How many stations do you have that should post their now playing data to the same twitter account?
How long is the duration of your average songs?

Twitter currently limits status updates / twitter posts over their API to 300 posts in 3 hours per API token (https://developer.twitter.com/en/docs/basics/rate-limits). That would mean you'd need to create a post every ~1,6 minutes to hit this limit.

**Comment by Vaalyn** [comment]
Rate limiting of Webhook calls to twitter was implemented in db95d55
