### ISSUE TITLE
Icecast self-hosted?

### ISSUE THREAD

**Issue by darrennye** [AzuraCast/AzuraCast#1212]
Something I'm not clear on... Icecast is used as a media/audio server for serving multiple feeds (from one source), correct?

So is the Icecast version or components included with AzuraCast, meant for using icecast as the media/audio server for serving multiple feeds from the radio station (assuming one has enough of bandwidth to serve multiple feeds), or are the included icecast components only meant to integrate with an external third party icecast service?

What third party icecast services do you recommend?

**Comment by Vaalyn** [comment]
The streaming servers (IceCast & ShoutCast) from AzuraCast can definitely be used to directly serve your listeners. This is also the default use-case for most station operators. If your bandwidth needs exceed the limits of a single server you can also use AzuraCast as your main audio source and relay the broadcast to an array of external streaming server instances to re-broadcast your stations.

**Comment by SlvrEagle23** [comment]
@darrennye As @Vaalyn said, AzuraCast is meant to be a "web radio station in a box", containing all the necessary software to manage and upload media and broadcast it directly out to your listeners, all from the same server. Our included installation of Icecast is production-ready, and you can direct your listeners to listen to the radio using either the AzuraCast public radio player page or a player of your own, or by supplying them with the stream URL (which you can find on the right side of the station's profile) and letting them use their own software.

The "remote relays" feature is meant for more complicated setups where you're relaying your radio signal to more than one Icecast server, or if you already have an Icecast server set up and don't want to use the AzuraCast built-in one. You can also broadcast to both the local instance _and_ any remote Icecast instances at the same time if you want.
