### ISSUE TITLE
Station restart not working after update

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1213]
**Installation method**

Traditional

**Host OS (for Docker installations)**

Ubuntu 18.04

**Describe the bug**

Station restart is not working from webinterface (Tools/streaming restart)

**To Reproduce**

1. Go to station management
2. click on tools
3. click streaming restart
4. seeing this:
![image](https://user-images.githubusercontent.com/47743654/53302377-e107a780-385d-11e9-8cea-470a602bcaa0.png)

**Expected behavior**

Station restarts

**Relevant Logs**
nothing in log files

**Screenshots**
![image](https://user-images.githubusercontent.com/47743654/53302377-e107a780-385d-11e9-8cea-470a602bcaa0.png)

**Device(s):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 72.0.3626.109

**Comment by SlvrEagle23** [comment]
@MrSteelMiner Thank you for the report! This should be fixed as of the latest update.
