### ISSUE TITLE
Empty media page

### ISSUE THREAD

**Issue by RadiateTC** [AzuraCast/AzuraCast#1214]
**Installation method**

Traditional

**Host OS (for Docker installations)**

Ubuntu 16.04

**Describe the bug**

I've got 4 Media directories, where 2 of the 4 show this no results found!,
if i search for a specific song the music file shows up perfectly fine.

**To Reproduce**

N/A

**Expected behavior**

Show all the songs in media library, which works at 2 dirs

**Relevant Logs**

N/a

**Screenshots**

https://i.imgur.com/EgrfTzI.png

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 
N/a

**Additional context**

**Comment by Vaalyn** [comment]
How were the files that are not showing up when looking at the directories uploaded? Through the web interface or via S/FTP?

When you open the browsers JavaScript console and then open the media page where the files don't show up, can you see any errors? Also take a look at the XHR network requests and the responses and check if the request fails.

Please manually run the media sync and check for any errors there too.

**Comment by RadiateTC** [comment]
We managed to get it fixed by looking in javascript console, Thanks for the help!

**Comment by SlvrEagle23** [comment]
@RadiateTC Care to share what the specific problem was? It may be something we can help with for all installations.
