### ISSUE TITLE
/usr/local/bin/docker-compose: line 1: Not: command not found

### ISSUE THREAD

**Issue by suricloud** [AzuraCast/AzuraCast#1215]
**Installation method**

Docker
**Host OS (for Docker installations)**
Debian9
**Describe the bug**

I tired to install but getting these error:
/usr/local/bin/docker-compose: line 1: Not: command not found
/usr/local/bin/docker-compose: line 1: Not: command not found
/usr/local/bin/docker-compose: line 1: Not: command not found

**Comment by suricloud** [comment]
root@ks:~# ./docker.sh install
Docker is already installed! Continuing...
Docker Compose is already installed! Continuing...
/usr/local/bin/docker-compose: line 1: Not: command not found
/usr/local/bin/docker-compose: line 1: Not: command not found
/usr/local/bin/docker-compose: line 1: Not: command not found

**Comment by CodeSteele** [comment]
_Odd_ I think that would suggest the shebang isn't valid, which for my docker-compose is:
`#!/usr/bin/python`

Do you have python installed? If so where at? Try `which python`, I have no clue how docker install would work correctly without Python though.

If that looks fine, do a ` which docker-compose | xargs head -n 1` let us know what that says.

Where did your Debian9 install come from? An ISO? A cloud provider? Sometimes we've seen some providers strip a lot out of their images causing all sorts of issues.

**Comment by SlvrEagle23** [comment]
@suricloud If you're seeing "Not" as the first line of your shell script, it means that the script that was downloaded was basically the HTTP 404 "Not Found" response.

You should run the following commands from the Docker utility script to manually reinstall Docker Compose:

https://github.com/AzuraCast/AzuraCast/blob/master/docker.sh#L69-L72
