### ISSUE TITLE
General question: fastest way to restore backup (remote server to remote server)

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#1216]
Currently, when restoring Docker backup…
1. Create backup from the old server > Download the backup file to my local machine > Upload the backup file to the new server.

Request:
Is it possible to transfer backup files from one remote server to another?
If yes, how?
wget is what I am thinking but I don't know what should be the correct public folder to add the backup file and what should be the correct URL so copying/downloading is possible.

Thanks!

**Comment by CodeSteele** [comment]
Probably SFTP from server-to-server: https://www.ssh.com/ssh/sftp/

**Comment by ErnestPH** [comment]
Of course, how I could not think about that? Lol. Thanks!
The funny thing, it's what I did when getting the file from the server to my local machine. Dumb me :)
