### ISSUE TITLE
Slack Incoming Webhook Support

### ISSUE THREAD

**Issue by bjarn** [AzuraCast/AzuraCast#1218]
Currently, there are several webhooks available in AzuraCast, like Discord, Twitter etc. 

I would love to see support for a Slack webhook coming in the near future since this is very useful to me and hopefully others, when using Slack instead of Discord, for example.

Documentation on Incoming Webhooks: https://api.slack.com/incoming-webhooks

**Comment by isAAAc** [comment]
same for mattermost  please ! ;)

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39037/add-slack-web-hook
