### ISSUE TITLE
ignore FilePermissions of mediafolder

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1220]
Hey, I'm trying to mount a Nextcloud-folder into station-media-folder. I used sshfs with readonly option, so that nothing can be changed. Is it possible to ignore the folder-permissions on changing in /admin/stations/edit/<station-id>?

Or is the console command "azuracast:media:reprocess" changing files in the media-directory?

**Comment by MrSteelMiner** [comment]
Okay, I've got a workaround. It's working for me now.

**Comment by mtzakris** [comment]
Hello
Can you maybe share some insights on how you managed to mount the nextcloud folder into the media folder?

**Comment by MrSteelMiner** [comment]
I used rsync to copy/sync the media folder of my nextcloud to the AzuraCast media folder. But this is only possible if you haven't encrypted the nextcloud.

**Comment by atomtm** [comment]
> I used rsync to copy/sync the media folder of my nextcloud to the AzuraCast media folder. But this is only possible if you haven't encrypted the nextcloud.
> 
> So it's not mount, it's a workaround to have access to the media files in an automatic way

Are you using docker installation ? If so, how do you point the container to your nextcloud storage?

**Comment by MrSteelMiner** [comment]
No, I've installed the bare-metal/traditional/ansible version. My nextcloud storage is on an other server.
