### ISSUE TITLE
Once per x Songs and Once Per x Minutes does not work

### ISSUE THREAD

**Issue by isaiaswebnet** [AzuraCast/AzuraCast#1221]
The jingles do not stop repeating. Once per x Songs and Once Per x Minutes does not work as before

**Comment by danielrodrigotest** [comment]
I have the same problem. In fact, I used  play once per 2 songs and does not work. It plays 4 to 5 jingles. In some parts, Azura plays all the jingles all time. 
![screenshot 2019-02-27 at 3 48 45 pm](https://user-images.githubusercontent.com/40525323/53514841-6c27ae00-3aa7-11e9-8aad-920af5426283.png)

**Comment by SlvrEagle23** [comment]
Follow issue #1198 for updates on this.
