### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#1222]
My version 0.9.2. didn’t change after the update.

> ERROR: error while removing network: network azuracast_default id ea7a606082aee23b1063fa39f2b5293247154eec601b1a0173b0fd166abbcc0c has active endpoints
It works a little then falls on errors

> 502 Bad Gateway
nginx

**Comment by susl16c** [comment]
I decided to reinstall and restore from a copy as before and I got this

ERROR: for stations  Cannot create container for service stations: open /var/lib/docker/volumes/azuracast_shoutcast2_install/_data: no such file or directory
ERROR: Encountered errors while bringing up the project.
WARNING: Found orphan containers (azuracast_nginx_1, azuracast_cron) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
azuracast_redis_1 is up-to-date
azuracast_mariadb_1 is up-to-date
azuracast_influxdb_1 is up-to-date
Creating azuracast_stations ...
Creating azuracast_stations ... error

ERROR: for azuracast_stations  Cannot create container for service stations: open /var/lib/docker/volumes/azuracast_shoutcast2_install/_data: no such file or directory

ERROR: for stations  Cannot create container for service stations: open /var/lib/docker/volumes/azuracast_shoutcast2_install/_data: no such file or directory
ERROR: Encountered errors while bringing up the project.

**Comment by susl16c** [comment]
After creating the folders manually, everything was established and after restoring from the copy it began to work, thanks, but consider this behavior in future developments.

**Comment by Vaalyn** [comment]
> ERROR: error while removing network: network azuracast_default id ea7a606082aee23b1063fa39f2b5293247154eec601b1a0173b0fd166abbcc0c has active endpoints

This seems to be because of a problem docker can encouter when trying to shutdown a network where some container is still active and can't be removed from the network. In most cases using `docker network inspect` and `docker network disconnect -f` should resolve this.

**Comment by susl16c** [comment]
for other questions, that during installation, folders are not automatically generated and you have to manually create them in the docker to install the product?

**Comment by SlvrEagle23** [comment]
@susl16c That shouldn't be happening. As a reminder, make sure you're updating the Docker script itself during your updates, like:

```
./docker.sh update-self
./docker.sh update
```
