### ISSUE TITLE
 Block audio after scheduled date

### ISSUE THREAD

**Issue by JMultimidia** [AzuraCast/AzuraCast#1223]
Set start and end date of the spot to prevent audio from playing after the period the spot has been sold to the customer.

**Comment by Vaalyn** [comment]
@JMultimidia I'm assuming this is a feature request. Can you describe a little bit more detailed what exactly you envision here? Since AzuraCast has no "sellable spots" I'm not sure what exactly you are asking for.

**Comment by JMultimidia** [comment]
In conventional radio stations, you can register a SPOT with date to end. Example: I register a SPOT (Event that will happen on 03/31/2109) to play the schedule until 03/31/2019. The next day this same SPOT will not play anymore.

**Comment by Vaalyn** [comment]
To make this possible I'd think the easiest and most general way would be to add the possibility of setting a deactivation date / time for playlists. So that AzuraCast automatically disables a playlist at a given date / time.

**Comment by JMultimidia** [comment]
It would not be interesting to expire the playlist of spots, because within it there may be other audios that should still be active. It may be better to add / edit the audio validity field.

**Comment by Vaalyn** [comment]
Closing this issue as we manage feature requests with an external tool.
I've created a feature request for this over there: https://features.azuracast.com/suggestions/47375/disable-playlist-on-specified-date-time
