### ISSUE TITLE
Bad Performance

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#1225]
**Installation method**

I use Traditional
**Host OS (for Docker installations)**

Ubuntu 16.04
**Describe the bug**

I have 5 Stations. Before the Update, everything works fine but now, stations crash and i have 100% cpu every time.

**Comment by Vaalyn** [comment]
Which processes are using up your CPU and what resources does your machine have (CPU & RAM)?

**Comment by preterive** [comment]
![grafik](https://user-images.githubusercontent.com/31483348/53508221-9d10de80-3ab9-11e9-8c67-f3a3f77c294e.png)

**Comment by preterive** [comment]
They only play the Jingle in a loop...

**Comment by preterive** [comment]
![grafik](https://user-images.githubusercontent.com/31483348/53508505-2c1df680-3aba-11e9-832f-8dccecaffe69.png)
System Logs

**Comment by Vaalyn** [comment]
So this load is only on these 2 stations that constantly loop your Jingle?
Is it a Jingle that you added or is this the default AzuraCast Jingle?
Is there anything you manually added to the Liquidsoap configuration?

**Comment by preterive** [comment]
No, 5 Stations constantly loop.
It is a jingle that i added in a Playlist wich come every 5 Tracks.
After a Liquidsoap restart it works for one Track.
It works before the Update without problems.
I added this manually:

full4 = fallback(track_sensitive=false,[request.queue(id="request"), radio])
output.icecast(
%mp3.cbr(bitrate=256, id3v2=true),
  host = "alles-radio2.stream.laut.fm", port = 8080,
  password = "xxxxx", mount = "alles-radio2",
  full4)

**Comment by Vaalyn** [comment]
When you remove this custom configuration does it work normally?

**Comment by preterive** [comment]
I removed the Play every x Track and now it works.

**Comment by JMultimidia** [comment]
The same thing happens to me in the traditional installation. important: I have not added configuration. I simply installed and configured the radios and the htop shows high consumption in the liquidsoap. Load is at 100%.

**Comment by preterive** [comment]
My Problem was fixed there: https://github.com/AzuraCast/AzuraCast/commit/be5c8159d3d7d71b76b51c9be8a23806a2eb8732
