### ISSUE TITLE
Use a custom css code

### ISSUE THREAD

**Issue by Ficreet** [AzuraCast/AzuraCast#1228]
Hello,

Despite my various researches, I can't get my way. I would like to use custom css code, (from the custom branding page), to change the color of the player text and the volume bar. I know you need the "class" of the html page of the player, but despite my search in the github I can't find it.
Can you tell me where the player's web file is, or if you're very nice, tell me what are the " class " to modify to achieve my goals

Thank you in advance to you
Sincerely

**Comment by Vaalyn** [comment]
[Here](https://github.com/AzuraCast/AzuraCast/blob/master/templates/frontend/public/player_component.phtml) is the template for the player component on the public page and [here](https://github.com/AzuraCast/AzuraCast/blob/master/templates/frontend/public/index.phtml) is the template for the public page itself. The classes for the player text should be `.nowplaying-title` and `.nowplaying-artist`. For the volume bar the class should be `.jp-volume-range`

**Comment by Ficreet** [comment]
Thank you very much, this is exactly what I was looking for.

Good continuation to you!
