### ISSUE TITLE
Bug on Playlist (Once per x Songs) - Song is repeating again and again

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#1229]
**Installation method**
Docker Ubuntu latest version of Azuracast

**Describe the bug**
After updating to the latest version, the playlist (Once per x Songs) stucks its song and keeps repeating instead of going back to general rotation playlist. (please see logs)

**To Reproduce**
1. Go to 'Playlist'
2. Click on 'Once per x Songs' and set to 2 per songs
3. wait for the playlist to play the song
4. After the song from the Once per x Songs playlist is done, it just keeps repeating it.
-->

**Expected behavior**
After the x song playlist, it should go back to general rotation

**Relevant Logs**

> > 2019/02/28 01:00:56 [the_blue_pill_next_song:3] Finished with "/var/azuracast/stations/the_blue_pill/media/Station ID/Blue Pill 1.3.mp3".
2019/02/28 01:00:56 [the_blue_pill_next_song:3] Prepared "/var/azuracast/stations/the_blue_pill/media/Station ID/Blue Pill 1.3.mp3" (RID 81).
2019/02/28 01:00:56 [lang:3] AzuraCast Feedback Response: OK
2019/02/28 01:00:56 [lang:3] AzuraCast Raw Response: annotate:playlist_id="13",title="Blue Pill 1.3",artist="",duration="5.",song_id="c3b3be30de3076ac86a3e5623f891e8b",media_id="2784":/var/azuracast/stations/the_blue_pill/media/Station ID/Blue Pill 1.3.mp3
2019/02/28 01:00:56 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/the_blue_pill/media/Station ID/Blue Pill 1.3.mp3".
2019/02/28 01:01:01 [the_blue_pill_next_song:3] Finished with "/var/azuracast/stations/the_blue_pill/media/Station ID/Blue Pill 1.3.mp3".
2019/02/28 01:01:01 [the_blue_pill_next_song:3] Prepared "/var/azuracast/stations/the_blue_pill/media/Station ID/Blue Pill 1.3.mp3" (RID 82).
2019/02/28 01:01:01 [lang:3] AzuraCast Feedback Response: OK

**URL**
https://bluepill.audiogasmradio.com/public/the_blue_pill

**Device(s):**
 All browsers - Mac and Windows

**Comment by ErnestPH** [comment]
Please note:
If I disable the affected playlist (x per song), the radio plays normally again.

**Comment by ErnestPH** [comment]
Please also note that x per minute has the same bug...

**Comment by ErnestPH** [comment]
Solutions I tried:
Cli commands
clear cache, media reprocess and restart to no avail...

**Comment by SlvrEagle23** [comment]
@ErnestPH Follow #1198 for updates on this issue.
