### ISSUE TITLE
Shoutcast as a Remote Relays causing bugs

### ISSUE THREAD

**Issue by rubensben** [AzuraCast/AzuraCast#1236]
This is me again, I noticed that when I'm using shoutcast as a Remote Relay : 
-   I have to put http://127.0.0.1:8005 as a remote base url to work (external ip or name resolved are not connecting to shoutcast.
- It break the "Now Playing Data" task (error curl 500m the server cannot access to 127.0.0.1:8005) so the songs and stats are not updated.

![shoutcast1](https://user-images.githubusercontent.com/4449630/53608282-c5d4c900-3bca-11e9-8b01-d66ced01ccd8.png)
![shoutcast2](https://user-images.githubusercontent.com/4449630/53608288-c705f600-3bca-11e9-926d-cdf2c156ea7a.png)

Exept of that, it connects well to the shoutcast. Any clues ?

**Comment by Vaalyn** [comment]
Is this still happening with the newest version of AzuraCast?
There was an update that fixed a problem that could also have been the same underlying issue. Mentioned in this [issue reply](https://github.com/AzuraCast/AzuraCast/issues/1303#issuecomment-476237123) here.

**Comment by Vaalyn** [comment]
Closing this issue as there has not been an answer after the initial report of the issue and we already implemented a fix for an issue that potentially also caused this.
