### ISSUE TITLE
Upload many tracks

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#1237]
**Installation method**

Traditional
**Host OS (for Docker installations)**

Ubuntu 16.04
**Describe the bug**

The upload process crashes if i want to upload many songs at one time. Browser: Firefox
**To Reproduce**

Upload 20 Songs and after some times, it crashes.
If i only Upload 10 Songs, wait and the upload 10 more songs it works.
**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 
Windows 10 Enterprise
Firefox
**Additional context**

**Comment by SlvrEagle23** [comment]
@preterive You're going to need to be way more specific in describing the phrase "it crashes".

What crashes? Your browser? The entire AzuraCast instance? The nginx server?

Also, for an issue of this complexity, relevant logs are very important and that section should not be left blank. Please supply any logs that demonstrate what kind of problem is happening.

**Comment by preterive** [comment]
There is no error or crash, the Upload process simple Stop. I have to reopen the Page.

**Comment by Vaalyn** [comment]
Can you try this again while having the browsers JavaScript and Networking console open?
When the process stops look for any JS errors and also at the response of the failed XHR request to see what could be the problem. Also please look into the `System Administration` -> `System Logs` -> `AzuraCast Application Logs` and post any errors you find that could be related to this in this issue here so that we have something to debug.

**Comment by preterive** [comment]
I get this after the eight Song.
read error on connection
10.2 MB

The only error i could find: [2019-03-08 16:47:28] AzuraCast.ERROR: read error on connection {"file":"/var/azuracast/www/src/Provider/RadioProvider.php","line":65,"code":0} []

Browser Console:
Relisting for directory: #test files:440:9
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data[Weitere Informationen] files:417:28
{"code":0,"message":"read error on connection","formatted_message":"read error on connection","extra_data":[],"success":false} 
Object { flowObj: {…}, bytes: null, file: File, name: "24 In Control (Edit).m4a", size: 8278423, relativePath: "24 In Control (Edit).m4a", uniqueIdentifier: "8278423-24InControlEditm4a", chunks: [], paused: false, error: true, … }
 
Object { flowObj: {…}, fileObj: {…}, offset: 6, tested: true, retries: 0, pendingRetry: false, preprocessState: 0, readState: 2, loaded: 1988401, total: 1988401, … }
files:426:9
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data[Weitere Informationen] files:417:28
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data[Weitere Informationen]

**Comment by preterive** [comment]
![grafik](https://user-images.githubusercontent.com/31483348/54039307-eb616400-41c2-11e9-84ae-42acdc2963cd.png)

**Comment by preterive** [comment]
#0 /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php(399): Redis->connect('localhost', 6379, 15)
#1 /var/azuracast/www/vendor/pimple/pimple/src/Pimple/Container.php(114): Azura\DefaultServicesProvider->Azura\{closure}(Object(Azura\Container))
#2 /var/azuracast/www/vendor/azuracast/azuracore/src/Container.php(109): Pimple\Container->offsetGet('Redis')
#3 /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php(191): Azura\Container->offsetGet('Redis')
#4 /var/azuracast/www/vendor/pimple/pimple/src/Pimple/Container.php(118): Azura\DefaultServicesProvider->Azura\{closure}(Object(Azura\Container))
#5 /var/azuracast/www/vendor/azuracast/azuracore/src/Container.php(109): Pimple\Container->offsetGet('Doctrine\\Common...')
#6 /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php(210): Azura\Container->offs in /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php on line 399
[08-Mar-2019 16:53:34 Europe/Berlin] PHP Fatal error:  Uncaught RedisException: Connection refused in /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php:399
Stack trace:
#0 /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php(399): Redis->connect('localhost', 6379, 15)
#1 /var/azuracast/www/vendor/pimple/pimple/src/Pimple/Container.php(114): Azura\DefaultServicesProvider->Azura\{closure}(Object(Azura\Container))
#2 /var/azuracast/www/vendor/azuracast/azuracore/src/Container.php(109): Pimple\Container->offsetGet('Redis')
#3 /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php(191): Azura\Container->offsetGet('Redis')
#4 /var/azuracast/www/vendor/pimple/pimple/src/Pimple/Container.php(118): Azura\DefaultServicesProvider->Azura\{closure}(Object(Azura\Container))
#5 /var/azuracast/www/vendor/azuracast/azuracore/src/Container.php(109): Pimple\Container->offsetGet('Doctrine\\Common...')
#6 /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php(210): Azura\Container->offs in /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php on line 399
[08-Mar-2019 16:53:34 Europe/Berlin] PHP Fatal error:  Uncaught RedisException: Connection refused in /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php:399
Stack trace:

I think this is an error with Redis? Is there no retry of the Browser?

**Comment by preterive** [comment]
I just fixed the Redis Server: https://stackoverflow.com/questions/36880321/why-redis-can-not-set-maximum-open-file
