### ISSUE TITLE
SPAWN_ERROR: station_11:station_11_backend

### ISSUE THREAD

**Issue by NadjaNeville** [AzuraCast/AzuraCast#1238]
Creating a new station with a custom port base always gets me a non functional station with liquid soap not running and giving this error code when trying to start it manually. Sometimes it helped to move to a different ports, but only until next station restart, then it gets the same error again. I have checked with netstat that said ports are not used by anything. Even moving ports doesn't help any more now and the other stations run rather fleaky. Checking logs didn't get any hint of what's wrong, it just doesn't want to work.

I am using the traditional install on Ubuntu Server 18.04.2 LTS in the latest update AzuraCast • v0.9.3, #b9231da (2019-02-26 7:41)

[liquid_soap.log](https://github.com/AzuraCast/AzuraCast/files/2921042/liquid_soap.log)

**Comment by MrSteelMiner** [comment]
had the same error. Reboot whole server helped for me :)

**Comment by NadjaNeville** [comment]
It helped once, but I am running 11 stations, I can't reboot the server 11 times each time I update it :/ 

Update: Rebooting server doesn't help.

**Comment by SlvrEagle23** [comment]
@NadjaNeville That log doesn't seem to show any error messages. Is that the log you see directly after starting Liquidsoap, where you see the "SPAWN_ERROR" message?

**Comment by NadjaNeville** [comment]
Yes, that's what I pulled out right after, that's what made me frown. If there were error messages or codes I would have tried to get them done, but I get this error persistently even after server reboots and moving the port base to other ports what helped before, doesn't help there any more. Also what I noticed, when I created a radio station then deleted it, the station ID doesn't get re-used, it counts up. I have 8 stations now and it says 11 in the count.

**Comment by SlvrEagle23** [comment]
@NadjaNeville That blocking happens on the AzuraCast database level, so if the stations don't exist as it's checking for port use, it won't cause any problems.

It's possible that the supervisor is failing to stop a process involved, but that should only happen if you're frequently deleting and recreating stations using the same ports...

**Comment by NadjaNeville** [comment]
Shouldn't this be cleared after restart? And how to clear it up?

**Comment by SlvrEagle23** [comment]
@NadjaNeville Yes, it should be. I'm not sure that this is what's causing the problem in this case, but I'm frankly not sure what is causing the problem at all.

**Comment by NadjaNeville** [comment]
@SlvrEagle23 it was a thought that the ports may be blocked somewhere and not released. Yes, I deleted three stations after a short while and recreated one, still the count could have been reused. Somehow this makes me think there is a remnant somewhere keeping things blocked even through restarts. 
Maybe as a feature request, enter a start port for the auto assignment of Azuracast. presently it starts at 8000 but due to other streams using the same IP I can't run the radio stations that low. Maybe have a starting point to choose, like set 10000 as the start portbase and let Azuracast assign ports automatically starting from there. I don't know how complicated it is.

**Comment by Vaalyn** [comment]
@NadjaNeville The station IDs are defined as the auto incremental primary field of the station table in the AzuraCast database. When designing databases it is not advised to re-assign already used auto increment values and by default the database will prevent this.

You could check if there is any process that is already using a port by starting your AzuraCast installation, then entering the stations container with `docker exec -it azuracast_stations_1 bash` and there use the command `netstat -tulpn`. This should show you which PID is using what port. With that information check with `top` against the running processes if there is anything running on that port that shouldn't.

**Comment by NadjaNeville** [comment]
@Vaalyn As I wrote in my first post, I have checked ports with netstat, just re run it and it shows only the ports assigned to active stations as used. Means the port base for shoutcast, the automatically assigned incremental ports and the ones nginx listens on. None of the ports I tried to assign to the created station are in the list, ergo not used by anything else, yet it won't start up. I reserved the ports 10000 - 11000 for my stations. When I remember now, all the port bases I try to use and which cause errors are ports I used and needed to move away from because the other stations have caused the same error after a station restart. For example, I assigned a port base 10200 to a station. It worked well for a bout a week, then I updated the server and restarted it, the station won't start up with SPAWN_ERROR forcing me to switch the port to 10300, then it worked again until next reboot of the server after update. Since I needed to move one station a couple of times, I am running out of port bases not previously used. Trying to assign one of those I used and swapped for another now causes the error, even the ports are not used by anything when one can believe netstat. So after three weeks of runtime I tried to use the portbase 10200 again for a freshly created station and it gives me the error.

**Comment by SlvrEagle23** [comment]
@NadjaNeville If there aren't any logs in `/var/azuracast/stations/(station_name)/config` that have any errors at all about why this might be happening, it's going to be all but impossible for us to diagnose this remotely.

**Comment by NadjaNeville** [comment]
If there were errors I would have looked into it already. So it means, if I use a custom port base and change a couple of stations then I run into a hard limit of four stations per server in a portbase of 1000 ports available. As for now I can't create another radio station without installing another server and that is quite annoying. Any Idea what I could look for or do, try, whatever, because I like the system but when it restrains me I can't use it the way I wanted. Also, how about the feature to set a starting point for the automatic assignment of ports? It is hard set to start at 8000 but I can't use it. It would be awesome to set a start port somewhere and let AzuraCast assign ports automatically to avoid what I ran into by having to set every port by hand if not using 8000+

**Comment by NadjaNeville** [comment]
Ok, as this thread seems to be abandonned now, I would be thankful for a hint where the starting port for the automatic port assignments is set. Any config file I could change it manually and try building a completely new server? I can't use the software as is blocking me from creating other stations and as you said, you won't be able to get a solution for this so I want to set up a fresh install but still can't use ports 8000-9000 only. I would LOVE to be able to edit something and change the starting port and the range somewhere, any hint for this?

**Comment by Vaalyn** [comment]
I have just tested creating a station with the following ports assigned, then deleting the station and creating a new one with the same ports configured and everything works just fine:

Customize Broadcasting Port: `8020`
Customize DJ/Streamer Port: `8030`
Customize Internal Request Processing Port: `8040`

I did this 6 times in a row and encountered no problems. Keep in mind that I'm using the recommended Docker installation method here instead of the Bare-metal one but the AzuraCast code is the same for both installation methods. As this seems like it's related to something with the Bare-metal installation method and the host machine and is something that has so far never been reported by other users I'd suggest that you switch to using the Docker installation method.

**Comment by NadjaNeville** [comment]
Either this or AzuraCast can't use ports outside the standard range. As I stated in my post, i can't use the range 8000-9000 as it's used by another server already. that's why I am looking for a method to assign ports at 10000-11000. If you could retry the scenario with port numbers above 10000 then I am willing to try the docker installation, although i like "seeing" the directories of the stations via SSH because of backups done via rsync.

**Comment by Vaalyn** [comment]
I'll try with the port range you mentioned and let you know how it goes.

Regarding accessing the directories via SSH you can still do this with Docker. The Docker volumes will be available at `/var/lib/docker/volumes/azuracast_*`. That's what I reference in my rsync scripts too.

**Comment by Vaalyn** [comment]
@NadjaNeville I've tested with the port range 10000 to 11000 now.

First I created the following `docker-compose.override.yml` to make the port range available to the stations container:

```
version: '2.2'

services:
    stations:
        ports:
        - '10000-11000:10000-11000'
```

Then I created 2 stations with the following ports assigned:

`Station 1`:
Customize Broadcasting Port: 10000
Customize DJ/Streamer Port: 10010
Customize Internal Request Processing Port: 10020

`Station 2`:
Customize Broadcasting Port: 10030
Customize DJ/Streamer Port: 10040
Customize Internal Request Processing Port: 10050

Then I edited `Station 1` to have the following ports assigned:
Customize Broadcasting Port: 10005
Customize DJ/Streamer Port: 10015
Customize Internal Request Processing Port: 10025

After restarting `Station 1` I edited `Station 2` to have the following ports assigned:
Customize Broadcasting Port: 10000
Customize DJ/Streamer Port: 10010
Customize Internal Request Processing Port: 10020

Restarted `Station 2` and also assigned the following ports to `Station 1` and restarted it:
Then I edited `Station 1` to have the following ports assigned:
Customize Broadcasting Port: 10030
Customize DJ/Streamer Port: 10040
Customize Internal Request Processing Port: 10050

I did this switching multiple times now and I encountered no errors.

**Comment by NadjaNeville** [comment]
whatever got changed, with the last AzuraCast update the issue vanished. I can create stations again. I guess you used this version to examine the issue Vaalyn. Thanks for keeping up and for the great software.
