### ISSUE TITLE
Remote Relay Problem

### ISSUE THREAD

**Issue by thedavidde** [AzuraCast/AzuraCast#1239]
Hello, If I disable the local Icecast server and only have one remote relay stream under "On The Air", Stream Offline. Even if the Locale Stream is activated, nothing will be transmitted to the Remote Relay Stream. Do I have to stop something or what am I doing wrong?

**Comment by SlvrEagle23** [comment]
@thedavidde After looking through the remote relays section, I realize some of the configuration options can be confusing, so I've tried to update them to clarify what they're looking for.

If you look at the Liquidsoap logs (either through Utilities -> Log Viewer or through `docker-compose logs -f stations`), you should see details on the connection error that may be happening.

**Comment by thedavidde** [comment]
Under Logs I see some errors.

> stations_1  | 2019/03/02 15:55:59 [techliveradio_relay_1:3] Will try again in 3.00 sec.
> stations_1  | strange error flushing buffer ...
> stations_1  | strange error flushing buffer ...
> stations_1  | 2019/03/02 15:56:02 [techliveradio:3] Connecting mount techliveradio for source@techliveradio.stream.laut.fm...
> stations_1  | strange error flushing buffer ...
> stations_1  | strange error flushing buffer ...

 For some reason, I am unable to connect to an external stream via remote relays. What could that be? Do I have to activate something else? An example would be great in which form I have to enter the IceCast data.  Thanks

**Comment by thedavidde** [comment]
The problem has now been resolved. The mistake was due to Liquidsoap. Had to akutalieren Liquapsoap. Now everything works.

**Comment by SlvrEagle23** [comment]
Good to hear everything is resolved!
