### ISSUE TITLE
Customize background/header

### ISSUE THREAD

**Issue by Donokami** [AzuraCast/AzuraCast#124]
Hello,
I would like to have the possibility to customize a little more the interface of Azuracast, modifying for example the logo of Navbar or the background.
Unfortunately, although it is possible to do this manually by modifying the assets, these modifications do not remain after the Azuracast update.
This is why I suggest adding in the interface the possibility of putting its own assets.
Thank you !

**Comment by sdx2tech** [comment]
Hello, first I'll say thank you for the excellent project...AzuraCast is very helpful! I've been streaming for a long time and this tool will make things more enjoyable to manage.

Please allow me to add to this request and indicate that it would be good for these customizations to be on a per-station basis...That is, if one has multiple streams/stations and say one is contemporary music and another is hip-hop, it would be good to have different headers/sub-headers, logos, backgrounds, etc.

Thank you for the consideration.

- Patrick
