### ISSUE TITLE
Jingle repetition

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#1242]
**Installation method**
Docker
**Host OS (for Docker installations)**
Ubuntu 18

**Describe the bug**
Jingles of less than 5 seconds are read twice in a row or more.

**Comment by Vaalyn** [comment]
This issue may be related to #1229. Have you updated to the newest version yet? And how is your Jingle Playlist configured?

**Comment by ckeurk** [comment]
The problem occurred by activating the assignment of the automatic playlist.
The playlist of jingles on random and sequential mode the same problem
