### ISSUE TITLE
Liquidsoap error log on bad configurations

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1245]
Hi, 

I'm using custom Liquidsoap configurations and in case of bad configs this file doesn't tell me what was wrong: /var/azuracast/stations/[station_name]/config/liquidsoap.log

The problem is that I can't debug my configs. Can I see the direct output of Liquidsoap? 

Peter

**Comment by SlvrEagle23** [comment]
@gammaw The main supervisord log can be found at `/var/azuracast/www_tmp/supervisor.log`, and can also be followed via the Log Viewer at the system administration level (not one specific station level). That should tell you anything that's going wrong.

**Comment by gammaw** [comment]
@SlvrEagle23 is it possible that I don't have such a file? I see this: 

![image](https://user-images.githubusercontent.com/28865986/54044777-17cfad00-41d0-11e9-85a2-5a933029e1a6.png)

**Comment by gammaw** [comment]
@SlvrEagle23 I forced an erroneous Liquidsoap configuration and checked the system level log like you said (see picture) but I found no trace of the Liquidsoap output. 

Am I doing something wrong? 

![image](https://user-images.githubusercontent.com/28865986/54083366-9ccadb80-4322-11e9-8cbe-4e36387fbfae.png)

**Comment by SlvrEagle23** [comment]
@gammaw There should be a list of stations directly below that section. If you click each individual station, you can view its logs.

**Comment by gammaw** [comment]
@SlvrEagle23 do you mean the "Liquidsoap Log"? That one I know but it doesn't contain error messages. The following snippet shows what happens after I save a buggy configuration and restart the radio. I see no error messages pointing to what could go wrong. I saw examples somewhere on the Liquidsoap page where the parser outputs verbose information about the possible error. 

![image](https://user-images.githubusercontent.com/28865986/54083461-1fa06600-4324-11e9-9a1b-5cd483e4e0ae.png)

**Comment by SlvrEagle23** [comment]
@gammaw That's just the log for the shutdown. Are you saying you're seeing no log whatsoever for Liquidsoap as it's starting back up? You don't see a section like...

```
2019/03/10 10:26:05 [main:3] Cleaning downloaded files...
2019/03/10 10:26:05 [main:3] Freeing memory...
2019/03/10 10:26:06 >>> LOG START
2019/03/10 10:26:06 [main:3] Liquidsoap 1.3.4
```

I'm not really sure how to answer your question if the logs simply aren't making it into the file at all. This is a very strange edge case scenario that I haven't seen before.

**Comment by gammaw** [comment]
@SlvrEagle23 I see these logs (">>> LOG START" etc.) but only in case of correct configurations. If Liquidsoap doesn't accept the configuration then the radio is not started and there are no logs. Does it make sense?

**Comment by SlvrEagle23** [comment]
@gammaw It does, but in my tests, the error still logs directly out to the file, such as:

```
2019/03/10 09:00:55 [main:3] Freeing memory...
At line 87 char 5 - line 88 char 0: the variable taco used here has not been
  previously defined.
```

**Comment by gammaw** [comment]
@SlvrEagle23 hmm, very strange. This is the output I'm looking for. Here is my workflow: 1) I add the configuration under MyStation -> EDIT -> AUTODJ -> Advanced Custom Configuration and then SAVE CHANGES. 2) Restart the radio under Utilities -> Restart Broadcasting 3) If the radio didn't start (no broadcast) I go the logs and check for errors (but there are no errors in my log).

Is this workflow correct?

**Comment by SlvrEagle23** [comment]
@gammaw Yes it is. Curious to see what the custom configuration that's causing the problem is.

**Comment by gammaw** [comment]
@SlvrEagle23 this is it:

```

# Fade out off air music, play jingle, start playing show
def transition_into_show(j,a,b)
  add(normalize=false,
	  [ sequence([fade.final(a),j,b]) ])
end

# Stop show (not fade out), play jingle, fade in off air music
def transition_into_off(j,a,b)
  add(normalize=false,
	  [ sequence([fade.final(a),j,fade.initial(b)]) ])
end


radio = switch(track_sensitive=false, transitions=[ 
    transition_into_show(playlist_jingle),transition_into_show(playlist_jingle),transition_into_show(playlist_jingle),transition_into_show(playlist_jingle),transition_into_show(playlist_jingle),transition_into_show(playlist_jingle),transition_into_show(playlist_jingle),transition_into_show(playlist_jingle),transition_into_show(playlist_jingle),transition_into_show(playlist_jingle),transition_into_show(playlist_jingle),transition_into_show(playlist_jingle),transition_into_show(playlist_jingle), transition_into_show(playlist_jingle),transition_into_show(playlist_jingle),transition_into_show(playlist_jingle),transition_into_show(playlist_jingle),
transition_into_show(playlist_jingle),
    transition_into_off(playlist_jingle) ], [ 
    #Monday
    ({1w and 17h-18h}, once(playlist_szmti_csrba)),  
    ({1w and 18h-19h}, once(playlist_kezek_a_sebekben)),  
    ({1w and 19h-21h}, once(playlist_earth_oddities__erdenklang)),  
    #Tuesday
    ({2w and 12h-13h30m}, once(playlist_csinltam_neked_egy_vlogats_kazettt)),  
    ({2w and 17h-19h}, once(playlist_mmn_radio)),  
    ({2w and 20h-21h}, once(playlist_turmeric_acid)),  
    #Wednesday
    ({3w and 17h-18h}, once(playlist_wikihow_adventure_cruise)),  
    ({3w and 18h-19h}, once(playlist_geigercounterculture)),  
    #Thursday
    ({4w and 16h-18h}, once(playlist_lazy_calm_raga)),  
    ({4w and 18h-19h}, once(playlist_mt)),  
    ({4w and 20h-22h}, once(playlist_great_galactic_ghoul)),  
    #Friday
    ({5w and 17h-18h}, once(playlist_agybaj)),  
    ({5w and 18h-20h}, once(playlist_mkd_mkd)),  
    #Saturday
    #({6w and 17h-19h}, once(playlist_rnr666_radioshow)),  
    ({6w and 9h20m-9h25m}, once(playlist_rnr666_radioshow)),  
    #Sunday
({7w and 10h10-10h15}, once(playlist_test_showw)),  
    ({7w and 11h-13h}, once(playlist_bambuszrdi)),  
    ({7w and 13h-17h}, once(playlist_donald_kacsa_klub)),  
    ({7w and 19h-20h}, once(playlist_sub_burek)),  
    ({true}, radio) ])
```

**Comment by gammaw** [comment]
@SlvrEagle23 this is a correct configuration and the radio restarts successfully after loading it. If I inject a bug, e.g., deliberately misspelling the name of a playlist, the radio restart will fail (meaning that the broadcast will not work after restart) and I don't see logs in the Liquidsoap Log.

**Comment by SlvrEagle23** [comment]
@gammaw At this point I don't have any further information for you on this issue. When I reproduce the same steps locally, I see an error log detailing the specific line of the error printed in Liquidsoap's log (and shown in the error message if you attempt to restart the backend from the profile).

**Comment by gammaw** [comment]
@SlvrEagle23 FYI: after I updated Azuracast now, I see the logs. No idea what went wrong with the previous state of the server (it was an update from February, the last recommended update). Anyway, thanks a lot for checking!
