### ISSUE TITLE
Public Page | title displayed wrong

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1246]
If a track with a long title is played, it is displayed over the container-border. If you hover the mouse, it is displayed correctly in 2 lines.

![image](https://user-images.githubusercontent.com/47743654/53699658-25112400-3deb-11e9-8db1-968a9248b3db.png)

**Comment by Vaalyn** [comment]
I tested his with the current player and this doesn't happen there anymore.

**Comment by SlvrEagle23** [comment]
@MrSteelMiner This was fixed as of this morning's player updates.
