### ISSUE TITLE
icecast mount on-connect scripts

### ISSUE THREAD

**Issue by emiryapici** [AzuraCast/AzuraCast#1247]
Hi

I'm trying to send email when a mount start or stop streaming. I can do this on my independent icecast server but on AzuraCast's icecast, it doesn't look possible. Anyone can help? Maybe it would be a good feature.

Regards

**Comment by SlvrEagle23** [comment]
@emiryapici Both the Icecast main configuration and the configuration of each mount point has an advanced field called "Custom Configuration", where you can put in any kind of configuration that should be directly merged into the generated Icecast configuration.

In this case, you will likely want to set a custom configuration like this on each mount point:

```xml
<on-connect>/your/script/path</on-connect>
```

Once you save that page and reload the station (you should be prompted to do so on the navigation bar) the new configuration will be loaded, complete with your customizations.
