### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by japanimradio** [AzuraCast/AzuraCast#1248]
Ubuntu 16.04

Bonjour

Comme nous ne parlons pas anglais faite une traduction.
Voici notre problème.
Nous diffusons avec la dernière version de azuracast mais il y'a un problème.
En effet quand on programme une programmations soit on voudrais un passage d'une programmation un exemple lundi entre 18h00 jusqu'à 19h00 on voudrais passé des nouveautés.
La programmation ne joue pas.
Pour que cette programmation joue nous somme obligé de redémarré la station pour que la programmation joue.
Nous somme sur deux serveurs de diffusion un qui tourne avec Ubuntu 16.04 l'autre Ubuntu 18.04
Nous avons les mêmes problèmes.
Comment corrigé cela.

Merci de votre retour
L'équipe Japanimradio

**Comment by MrSteelMiner** [comment]
* translation with google translator *

Hello
As we do not speak English made a translation.
Here is our problem.
We broadcast with the latest version of azuracast but there is a problem.
Indeed when we schedule a program or we would like a passage of a program an example Monday between 18:00 to 19:00 we would have spent novelties.
The programming does not play.
For this programming to play we have to restart the station for the programming to play.
We are on two broadcast servers one that runs with Ubuntu 16.04 the other Ubuntu 18.04
We have the same problems.
How to correct that.

thank you for feedback
The Japanimradio team

**Comment by Vaalyn** [comment]
This seems like normal behavior to me. In order for the liquidsoap autodj to register a new playlist or a change to the playtme of an existing playlist the liquidsoap config needs to be written to disk and liquidsoap needs to read the changed config.

**Comment by SlvrEagle23** [comment]
@japanimradio Is "Manual AutoDJ" turned on for the station? You should turn it off if you are frequently making playlist changes, as Liquidsoap always requires a restart to reload its configuration after any changes.

**Comment by japanimradio** [comment]
Bonjour

Après avoir décoché Manual AutoDj nous avons fais un essais toujours pareil...
Nous somme obligé de redémarré la radio pour que sa joue est ce que sa vous fais sa aussi ?
Merci de votre réponse

**Comment by mkody** [comment]
Salut @japanimradio, ça aiderait pas mal les développeurs si tu peux parler en anglais :P 

Here's the translation @SlvrEagle23 

> Hi  
>   
> After disabling Manual AutoDJ we did a test and it's still the same...  
> We had to restart the radio for it to work - does it happens to you too?  
> Thanks for your reply

**Comment by SlvrEagle23** [comment]
@japanimradio @mkody You will have to restart the radio station right after you turn off Manual AutoDJ, but you shouldn't have to restart it again after that. You may be having trouble with AzuraCast communicating with your AutoDJ. Are you on Docker or Traditional install?
