### ISSUE TITLE
activation-checkboxes are required

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1249]
Since last update, "activate playlist" and "Allow Requests from This Playlist" are checkboxes, but they are required so it is impossible to deactivate requests.

![grafik](https://user-images.githubusercontent.com/47743654/53725455-567e0400-3e6c-11e9-9cb4-be9db5953dab.png)

**Comment by SlvrEagle23** [comment]
@MrSteelMiner This is fixed as of the latest update. Thanks for the report!
