### ISSUE TITLE
Simple question about Darkice

### ISSUE THREAD

**Issue by thepseudophile** [AzuraCast/AzuraCast#1251]
Hi, I already have a Raspberry Pi set up running Darkice and broadcasting to an Icecast server, with a player on a website broadcasting the live audio.
What I am looking for now is just some management software that I can install on the server to be able to have uploaded playlists and shows scheduled to play when there is no live content. Basically an open-source version of Airtime.
Is possible to just add Azuracast to my existing system, or does it have to use your broadcasting software from the raspberry Pi?
Many thanks

**Comment by SlvrEagle23** [comment]
@thepseudophile AzuraCast is basically a "web radio station in a box", so it not only has the web management interface, but it also packages and manages Liquidsoap and Icecast (or SHOUTcast if you install it) instances directly.

It is entirely possible to set up a new AzuraCast instance, use it as a source of AutoDJ music, then broadcast a signal from your Raspberry Pi (or any other source) on top of the mount point that the AutoDJ is using. You can either do this directly through Icecast (which is somewhat more complicated) or use the streamers/DJs tool inside AzuraCast to let Liquidsoap receive the incoming signal and intelligently fade it into the AutoDJ signal.

**Comment by thepseudophile** [comment]
Thanks very much for the detailed answer, I will give it a go this week

**Comment by jimmyq76** [comment]
hi do you have a guide on doing this please as im after the exact same thing i have set up a local connection but unsure hot to put it on my web page so listeners can listen live

**Comment by spenmath** [comment]
I am also struggling to stream from darkice to icecast on AzuraCast. 

There is no option in the darkice config to set an icecast username so I assume that's why icecast is spitting back an error!
