### ISSUE TITLE
Fade from AutoDJ to DJ stream on beginning

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1254]
When a DJ starts streaming, the AutoDJ just cuts its music on start but fades back to music at the end of the livestream. Is it possible to fade at the beginning as well (so that music fades down in about 1 second)?

**Comment by gammaw** [comment]
Strange, I have it the other way around. The music is faded out when a live DJ starts streaming but when the stream ends the music comes back without fading. The corresponding Liquidsoap code should be this, right?   

`
def simple_crossfade(a,b) = add([fade.initial(duration=3.,b),fade.final(duration=3.,a)]) end
radio = switch(id="lahmacun_radio_live_switch", track_sensitive=false, transitions=[simple_crossfade], [({!live_enabled}, live), ({true}, radio)])
`

What do you think why fading in does not happen?

Btw, I'd also like to add jingles in between music and live DJ streams (before and after). Is there any way to do it with Azuracast or do I have to change Azuracast's the Liquidsoap config (which is not recommended)? I guess, adding Liquidsoap code in the Advanced configuration setting would not work here as I would need to change above definition. Is it correct?

**Comment by MrSteelMiner** [comment]
since one of the last updates it IS the other way around. I don't know why but it's not that good :D Fading in and out would be the best way

**Comment by SlvrEagle23** [comment]
@MrSteelMiner @gammaw It's supposed to be smoothly fading on both sides. For the life of me I honestly don't know why it isn't. I'll probably be forwarding this upstream to the Liquidsoap folks to see if I can get any help there.

**Comment by SlvrEagle23** [comment]
@MrSteelMiner @gammaw I've created an upstream ticket with Liquidsoap to see if there's something I'm doing wrong in how I write the Liquidsoap configuration for this process. You can follow that at savonet/liquidsoap#746.

In the meantime, I've removed the custom transition as it seemed to not really resolve the issue and only "reverse" the problem.

**Comment by gammaw** [comment]
@SlvrEagle23 just tried and both fading in and out seem to work for me. I even tried with two transition functions, with yours and with a slightly different one I found in a Liquidsoap cookbook (see below). Both work. 

I'm confused now as it was reported as not working. Did you ever try it again? I can see that this feature is not included in the current Azuracast version. 

```
#Azuracast version (inactive)
def simple_crossfade(a,b) =
  add([fade.initial(duration=3.,b),fade.final(duration=3.,a)])
end
```

```
#my version
def transition(a,b)
  add(normalize=false,
      [ fade.in(duration=3.,b),
        fade.out(duration=3.,a) ])
end
```

**Comment by gammaw** [comment]
@SlvrEagle23 I just updated to 0.9.8 w/ Liquidsoap 1.4 and was hoping that this one will be fixed but I see no difference. What we would like to have is following sequence: 
- Music is playing; 
- Live DJ logs in via Butt; 
- 1\) Music fades out, 2) a jingle is played (from one playlist), 3) live session starts; 
- 4\) Live session ends, 5) jingle is played (from another playlist), 6) music is faded back. 

We have a custom Liquidsoap configuration which does the job but for me it's a temporary solution. Obviously, we'd like to do it via native Azuracast. Do you plan to cover above use case with Azuracast playlists? 

Btw, the upstream issue (Liquidsoap) seems to be closed.

**Comment by gammaw** [comment]
@SlvrEagle23 also, there seems to be an issue with Liquidsoap 1.4 and fading: https://github.com/savonet/liquidsoap/issues/1009

**Comment by SlvrEagle23** [comment]
An update on this issue: we've had several upstream tickets with Liquidsoap, and even checked the configurations of other web radio management software to see how they're going about solving the problem, and the simple answer is that right now live DJ buffers and crossfading simply don't mix in the Liquidsoap ecosystem. Because there isn't enough buffered audio to properly fade into or out of, the crossfade will always either be jittery or will contain the next-to-latest DJ's broadcast carried over into the start of the next signal.

To accommodate this, regardless of the crossfade settings with regular music, we currently don't crossfade the live DJ connecting or disconnecting, and put that function _after_ the fades are already handled.

Even with recent improvements in crossfading on Liquidsoap's end, I don't expect that this will be able to be fixed soon, largely as an infrastructural limitation.
