### ISSUE TITLE
Resampling & Custom biterate configuration

### ISSUE THREAD

**Issue by voipworld** [AzuraCast/AzuraCast#1255]
ello
AzuraCast is so powerfull, we use it for our community radio
Opus have so many diferent level of quality & complexity, including diferent sampling rate
if i want to create a low biterate stream, sampling rate must be lower, like 24khz
can you please implement diferent biterate & sampling rate per codec?
preferably in a dropdown list for samplerate, and a dropdown list with text input for custom biterate
thanks!

**Comment by SlvrEagle23** [comment]
@voipworld There are two feature requests related to this:
https://azuracast.featureupvote.com/suggestions/39032/support-custom-sample-rates
https://azuracast.featureupvote.com/suggestions/39024/expand-available-bit-rate-options-for-streams
