### ISSUE TITLE
Telegram webhook 404 error

### ISSUE THREAD

**Issue by Amitxyz** [AzuraCast/AzuraCast#1256]
I do get this error for telegram webhook.What iam doing wrong?

Webhook Telegram returned code 404
request_url
"https:\/\/api.telegram.org\/mytelegram_bot\/sendMessage"
request_params
{
    "chat_id": "@myusername",
    "text": "Now playing on Radio Shruti: Sheesha Ho ya Dil Hai by Nadeem! Tune in now.",
    "parse_mode": "Markdown"
}
response_body
"{\"ok\":false,\"error_code\":404,\"description\":\"Not Found\"}"

**Comment by SlvrEagle23** [comment]
@amitx11 If you're getting a 404 on the Telegram API URL, that means you don't have the right bot token. You need the bot token to be exactly correct for the URL to work.

**Comment by somesh1515** [comment]
@SlvrEagle23 i am having same issue can you tell me solution 
check this link 
https://t.me/forextrade1/345

it is simple link from channel and it gives 404
