### ISSUE TITLE
Improve composer install performance with parallel downloads

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#1259]
**Is your feature request related to a problem? Please describe.**
I'd like to speed up the installation of composer dependencies.

**Describe the solution you'd like**
I'd like to add [hirak/prestissimo](https://github.com/hirak/prestissimo) as a composer plugin to the AzuraCast project. This composer plugin adds parallel downloads to composer which should speed up the installation of composer dependencies and thus reduce the downtime of an installation when updating.

**Comment by SlvrEagle23** [comment]
@Vaalyn This is implemented in the web container, where Packagist is used for deploys and updates; traditional installs still use regular Git for updates and wouldn't benefit from it.
