### ISSUE TITLE
Duration mp3

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#126]
Hello, I use a lot of club title that lasts 6 minutes or more, is it possible to add the length of the mp3 in the section "Musical files" and in its edition in addition to the fade duration. To make mp3 mixes more flexible? (SoundSoap)
It's an idea that would be really welcome for me;)

Thank you ! And thank you very much for your work

**Comment by SlvrEagle23** [comment]
@ckeurk I'm afraid I don't understand what you mean by your suggestion. Do you mean allowing users to edit the MP3 file's length itself? That would likely involve a lot of complex work and re-encoding of the file, which may be more complicated than we would want in AzuraCast.

**Comment by ckeurk** [comment]
No, just add a duration, a title makes 6 minutes, I want the sound to play that 5 minutes. I do not know if LiquidSoap can do it...
