### ISSUE TITLE
Docker update problem

### ISSUE THREAD

**Issue by webma5ter23** [AzuraCast/AzuraCast#1260]
Wanting to install the latest version of Azuracast the site falls, the strange thing is that it does not show any error, it only stays in one step.

```
Refreshing All Stations
-----------------------

Router cache file cleared.
Local cache flushed.
Restarting all radio stations ...
```
![imagen 1](https://user-images.githubusercontent.com/41419364/53856877-cac2bf80-3fb2-11e9-88da-93c6aeb8ea53.png)

```
Received signal: interrupt
2019/03/06 04:53:49 Command exited with error: signal: interrupt
azuracast_mariadb_1 is up-to-date
azuracast_influxdb_1 is up-to-date
azuracast_stations is up-to-date
azuracast_redis_1 is up-to-date
Creating azuracast_web_1 ... done
Untagged: azuracast/azuracast_web_v2@sha256:75b3b885043ca1172347ead9f4fa03090b83450975993db64c09472c3c7634ab
Deleted: sha256:56179d14e43538dace4c59d872ef1034f92f3c6ec0283eee5451ae693d539189
Deleted: sha256:3035c6b36b4590bde85b6a9b091ae4e97f66d8ba7eb1c4f4791e5ed1a59b163f
Deleted: sha256:4ff7d773d4f2b32337c451e45b7b901a5b77d039abd98c91c747ebe5b262ca2d
Deleted: sha256:cdb7b15e760cc2647cb579c6e95f64f04a37a801174e84a8be7ffa7b900f00f1
Deleted: sha256:cc40e0b5b41ee1a7635a690ae7a2a14f4f850bdde020455c3722ac96fea6fdbc
Deleted: sha256:018341a559e28c42b0c64d6a1f010c09704e40cd11ee100f60a786d7d5704d77
Deleted: sha256:b46c166be5bf34f6840cf585f344d86b531336723d55f0fa7bc93047658614cb
Deleted: sha256:f8c39220c5561c38e3b4983bc7273b3e1dd895aed4443bde83b492b4e7d89a56
Deleted: sha256:2da5cbfca402a342daa92c338329d2221beb1a522bac134e45cc5dbed4895d8e
Deleted: sha256:7f9f2d135b58da21b868c924b189f40058ba7cc9643ce14c9e103a58fe89267f
Deleted: sha256:1bab3978ba24fc2c576b832693a270b54d8f377d6d9169dfeb047126a83bb48d
Deleted: sha256:94134d2e644e9a95a5ce2b0228626dc7cd20add60f88684acad9c769ff1b4078
Deleted: sha256:4f69bca160316663c603c5711db243afefa6fed5076b35396763d99f1e3308f5
Deleted: sha256:efbcdc3c7a525bb948dadf0a17cb354983a6e4670a15db1ca90cbacb13859f0c
Deleted: sha256:54bbfc38cef9f5c5b3e4bd579cb17abef89dd33c43f58968ef6dc50ef98879e9
Deleted: sha256:e5a7f66f5fcc3b84b15a2e80403b246edc8824fee864b052a451ad7dc9168dc7
Deleted: sha256:6f74df490cab1bb47387199aa73e50be8bc4b07b72058b1e0885a33bd9a650e3
Deleted: sha256:c44b480b5ca533e6ba560aa4a5059cda8af4c2acf9af1a2f1b20aec9792d22b4
Deleted: sha256:527259559049fbbbd7937f4710c97dde025b4167d87a1a5dcf3978627bc83969
Deleted: sha256:4a1fa808ea3b62e15735c2c7ab02e326cff01ba0be9368065bd941c9b5b6adfe
Deleted: sha256:5a8252f86e4a6ae11608a4f8d654d4d540d5422ae7082cf3b4fba8a9f69d1e99
Deleted: sha256:5b0c3706b71d6c34bc322b33099579d0da6481aeae828130c3925e7eaeef23e1
Deleted: sha256:ce05117c0bdb5166f49b5b77a58620cd9e8bfdbc9dd91e04aa06c1395cea0c27
Deleted: sha256:c2898262e835d6f08e78b353a9d0c24f3a17aed2964bd45ea1035ed1e8638fcf
Untagged: azuracast/azuracast_radio@sha256:9415cdeccf636716523fc0a2aa71f253324b78e0942b4fd12bff026493abe1b6
Deleted: sha256:1fa52530e83e5baaf0f97d2b5095675df9c0f524b278928605626ef174b8ba7a
Deleted: sha256:915a1dc3ea570022dcc24926558d13412e5d2bd01c6c0fc5b0d41ecedc612c0b
Deleted: sha256:56f7489e4217b66d1d955e038d77dff6a7250a4b7564b3900c7bfdb05938a75d
Deleted: sha256:5718979808e90ec37505a7dfeec5fddf21481220fe45ad8e2fc82ab826f39854
Deleted: sha256:5a94aff70ac59792f71fe4e5434b70870e0e8c2ee24a7fb267ed012278fdf278
Deleted: sha256:73b9e5e63cdfa0e046675ca9b1bcdd8ddab8ba0a335d4caf1a1826a35e285f19
Deleted: sha256:ca420aa016e57ad0855ca361fee87c4ddee72aa2c92cf7b2c88515e2df94c82b
Deleted: sha256:31c22367603782bb2f7308e5e52d2c260968df40c09d46c79c62591c2c653ebe
Deleted: sha256:b0ae0571607ec2c978b8bf4e1bcadc978bc7c595b48ad027a60a4676ed6847f0
Deleted: sha256:81c5e4e6f898c464de0ae4901d4d260c58ad6fbe7d036dcf67de6a3069dc8f8d
Deleted: sha256:5b32db3804b4b2f4d6aa9ff2c62a316f97cabcf9fe01cb47eaa7ae433d48ea46
Deleted: sha256:b5a573bb70041ab5efcf085ed7b8f607fa00017358d93a808542321646c098b7
Deleted: sha256:9c0e9efe5d2b35b5a643820b01bac59a381ff06c9c9f722b47a3875321eba8bd
Deleted: sha256:c39c02bd62afab79a566b05dc3e9af688dfe1c424ed933c7a77572339f091d00
Deleted: sha256:50538f5d7c2aeff4373035577613bff0c4159508e48b4e11552044028e5581f6
Deleted: sha256:3da832d43be7ef9ed5ce2ee198823c8edf45064aa9db957d57af0de4d67db7c4
Deleted: sha256:d8b66c74f5fb0a1c18562c37ae225d0e31b7a38baa27d8d62e686ce121ee955b
Deleted: sha256:d610c3ba36afb925f926a9f81c2b276c4b81a153ec419615dc1c1aebee838f59
Deleted: sha256:1c8cd755b52d6656df927bc8716ee0905853fada7ca200e4e6954bd010e792bb
Deleted: sha256:9203aabb0b583c3cf927d2caf6ba5b11124b0a23f8d19afadb7b071049c3cf26
Deleted: sha256:32f84095aed5a2e947b12a3813f019fc69f159cb5c7eae5dad69b2d98ffbeca4
Deleted: sha256:bc7f4b25d0ae3524466891c41cefc7c6833c533e00ba80f8063c68da9a8b65fe
Update complete!

```

After that, the site is online again but the update message continues to be displayed

![imagen 2](https://user-images.githubusercontent.com/41419364/53857039-7c61f080-3fb3-11e9-8bc0-f72925cb1456.png)

**Comment by SlvrEagle23** [comment]
@webma5ter23 Did you make sure to update the `docker.sh` utility script as well, along with the update, i.e.

```
./docker.sh update-self
./docker.sh update
```

Some changes were made a while back to how the Docker Utility Script handles updates that may be causing your problem.

**Comment by webma5ter23** [comment]
Yes, I always follow these commands. The previous update was made without problems.

**Comment by SlvrEagle23** [comment]
@webma5ter23 If you skipped the updater before it finished restarting stations, then it missed the very last step, which is to mark the update as processed and prevent it from showing up on the dashboard.

The periodic hourly update check should remove the message.

As for why the console hung at restarting the station, I'm honestly not sure, as nothing in the latest few updates has affected that console command.

**Comment by webma5ter23** [comment]
There are problems in the panel, the changes are not updated, the stream works, but the metadata and number of listeners are what it showed before updating.

How can it be fixed without resetting a backup?

**Comment by SlvrEagle23** [comment]
@webma5ter23 Try running the Now Playing sync task from the administration panel by hand. Do you get any sort of error?

**Comment by webma5ter23** [comment]
The synchronization task updates only once and does not make it automatic. The update process continues in "Restarting all radio stations ... "

**Comment by SlvrEagle23** [comment]
@webma5ter23 `docker-compose logs -f web` saying anything useful?

**Comment by webma5ter23** [comment]
I'm not sure, only this, the rest is normal.

web_1       | In Driver.php line 69:
web_1       |
web_1       |   read error on connection
web_1       |
web_1       |
web_1       | queue:process [<runtime>]

**Comment by SlvrEagle23** [comment]
@webma5ter23 Looking into an issue preventing cron tasks from running.

**Comment by webma5ter23** [comment]
I cleaned the cache and it seems to be fixed for the moment
What is the command to see the azuracast version?

**Comment by SlvrEagle23** [comment]
@webma5ter23 The Docker Hub is having some major stability issues tonight, but I'm working on building an updated web container that fixes the cron issues.

**Comment by SlvrEagle23** [comment]
@webma5ter23 We were finally able to get a new build up, which should fix the cron tasks problem.

**Comment by macbroadcast** [comment]
Same problem, while updating to latest azuracast, get stuck at "restarting all stations" no error, increased swap but no change https://paste.ubuntu.com/p/HHRrrvfGhw/

**Comment by SlvrEagle23** [comment]
@macbroadcast Are you updating to the latest release version (with the `--release` flag) or to the latest rolling release update that came out?

**Comment by macbroadcast** [comment]
@SlvrEagle23 Updated to the latest release version. 
![53857039-7c61f080-3fb3-11e9-8bc0-f72925cb1456](https://user-images.githubusercontent.com/7961/53894631-b8876680-4030-11e9-930d-80e028a99bdf.png)

**Comment by SlvrEagle23** [comment]
@macbroadcast You should try updating to the latest rolling release (without the `--release` flag) as we've continued to make changes since 0.9.3's release that should be fixing issues.

**Comment by macbroadcast** [comment]
@SlvrEagle23 Not sure how todo i am mostly using ./docker.sh update-self
./docker.sh update ,but i saw a lot of new stuff which has been implemented lately,is it possible to go back to 0.9.2 ?

**Comment by SlvrEagle23** [comment]
@macbroadcast If you aren't manually adding the `--release` flag, then you are already on the latest rolling release.

Currently, no, there is no way to revert back to a previous tagged release.

In fact, it's somewhat upsetting to hear that. Please bear with me as I work on resolving any newly introduced issues.

**Comment by macbroadcast** [comment]
@SlvrEagle23 ok thanks

**Comment by macbroadcast** [comment]
@SlvrEagle23 Just addet the release tag and its working now !!

**Comment by SlvrEagle23** [comment]
@macbroadcast @webma5ter23 I've made some changes to how the "Restart Stations" CLI command (which is also part of the updater) performs. This should help resolve issues like this in the future.
