### ISSUE TITLE
error self-updating docker.sh

### ISSUE THREAD

**Issue by mlmateos** [AzuraCast/AzuraCast#1261]
**Installation method**

Docker

**Host OS (for Docker installations)**

Debian 9

**Describe the bug**

./docker.sh: line 308: syntax error near unexpected token `('

**To Reproduce**

1.

>  ./docker.sh update-self

Error:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9328  100  9328    0     0  58081      0 --:--:-- --:--:-- --:--:-- 57937
New Docker utility script downloaded.
./docker.sh: line 308: syntax error near unexpected token `('
./docker.sh: line 308: `        echo "  docker stop \$(docker ps -a -q)"'
```

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@mlmateos It seems like the download was interrupted before complete. Maybe try updating again?
