### ISSUE TITLE
Management of the schedules of the taking of direct 

### ISSUE THREAD

**Issue by j2sdwebradio** [AzuraCast/AzuraCast#1263]
**Is your feature request related to a problem? Please describe.**
In order to prevent the hosts from not taking the live outside the hours

**Describe the solution you'd like**
Management of the schedules of the taking of direct Days and hours. In order to prevent the hosts from not taking the live outside the hours

**Describe alternatives you've considered**
When the auth page of liquidsoap answers true or false with the code of the live, it is enough to check that the schedule is good also if the animator stream in the void

**Comment by SlvrEagle23** [comment]
This has already been requested as issue #1241. You can follow that issue for progress.
