### ISSUE TITLE
After Update: "Could not connect to supervisord."

### ISSUE THREAD

**Issue by ma-vie** [AzuraCast/AzuraCast#1265]
**Installation method**
Docker (DigitalOcean)

**Host OS (for Docker installations)**
Ubuntu 18.10 x64

Getting this Error after update:
![image](https://user-images.githubusercontent.com/45437669/53993265-2e71f780-412f-11e9-9ae3-822b1601206c.png)

I have deleted and created a new Droplet(DigitalOcean) but i am getting the same Error again.

docker-compose  down | docker-compose up -d    did not help

**To Reproduce**
1) ./docker.sh update-self
2) ./docker.sh update

**Relevant Logs**
web_1       | Mar  7 22:27:11 e9dd51aec78a php-fpm[50]: [WARNING] [pool www] child 2181 said into stderr: "[2019-03-07 22:27:11] AzuraCast.ERROR: Could not connect to supervisord. {"file":"/var/azuracast/www/config/services.php","line":137,"code":0} []"

**Comment by SlvrEagle23** [comment]
@ma-vie Working on resolving this as we speak.

**Comment by SlvrEagle23** [comment]
@ma-vie This should be fixed as of the latest Docker updates. Re-run your updater script and it should fix everything.

**Comment by ma-vie** [comment]
Made an update -> everything works.  🥇 
Thank you @SlvrEagle23
