### ISSUE TITLE
Liquidsoap Error on New Install - Not built during install

### ISSUE THREAD

**Issue by paulbonass** [AzuraCast/AzuraCast#1266]
**Installation method**

Traditional

**Host OS (for Docker installations)**

Ubuntu

Liquidsoap encountered an error
FATAL ERROR: Log directory "/var/azuracast/.opam/system/lib/liquidsoap/var/log/liquidsoap" does not exist.
To change it, add the following to your script:
set("log.file.path", "")
FATAL ERROR: Log directory "/var/azuracast/.opam/system/lib/liquidsoap/var/log/liquidsoap" does not exist.
To change it, add the following to your script:
set("log.file.path", "")

**Comment by SlvrEagle23** [comment]
@paulbonass This should be fixed as of the latest code update.

**Comment by SlvrEagle23** [comment]
@paulbonass Please reply and let me know if the fixes solved the problem for you.
