### ISSUE TITLE
Play station jingle at the beggining for every new listeners

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#1270]
Checked a few popular radio stations in Germany and some of them play a station jingle
every time you start listening to the radio stream, for example a short introduction combined with an advertisement.

Example http://www.hit104.com/listen.pls

**Comment by williambatson** [comment]
I've tried to find where to drop an intro file as well - does this exist for Azura?

**Comment by Vaalyn** [comment]
IceCast has a mountpoint option called [`intro`](http://icecast.org/docs/icecast-2.3.1/config-file.html#mountsettings) which is used for these intros at the beginning of a stream. Right now there is no directly configurable mountpoint option in AzuraCast to make use of that but you could add this config in the `Advanced Configuration` part of the IceCast mountpoint config.

**Comment by williambatson** [comment]
Thanks for the reply Vaalyn - I tried to experiment some with this at:
Advanced Custom Frontend Configuration
<intro>/intro001.mp3</intro>

After restarting the station it does appear in icecast.xml but I've got it dropped in the media folder so thinking maybe I need to be more specific in the path?  (traditional install) 
Could you elaborate a bit more on this, I'm hoping i just have the syntax of the code incorrect

thanks

**Comment by Vaalyn** [comment]
@williambatson I've tried to test this but I'm having some difficulties getting this to work (see issue #1377). How does your IceCast Configuration look like when you added the `intro` config? And what exactly did you put into the custom config field?

**Comment by williambatson** [comment]
In mount points -  I clicked edit the existing default mount point for that station.
In the section titled:  Advanced Custom Frontend Configuration I have this:
<intro>/intro001.mp3</intro>

My files called intro001.mp3 is uploaded here: /var/azuracast/stations/test/media
Again-  traditional install.
I did open icecastconfig.xml  and did see Azuracast loaded <intro>/intro001.mp3</intro>   into the file, so it's in the icecast config file now for that station.  
This is why my first guess was trying it with a full path like:
<intro>/var/azuracast/stations/test/media/intro001.mp3</intro>
but that didn't work either.    The stream just plays as normal -  as if no change was made.
Each time I change the code entered, I restarted the station -  checked the XML file twice to see the changes are being made...     Just not hearing it before the streaming begins.

**Comment by SlvrEagle23** [comment]
@williambatson The reason we don't support the intro file directly inside AzuraCast is because it's _very_ picky about what file it wants. It wants a file that matches, exactly, the bitrate, format and sample rate of the stream itself.

**Comment by Vaalyn** [comment]
@SlvrEagle23 Just speculating on what would be a theoretical solution to this pickiness of IceCast from our side.

Let's say we add a file upload for intro files to the mount configuration. When a user uploads a file for the intro AzuraCast could check what the streams config is in regards to bitrate, format & sample rate and then let Liquidsoap re-encode the file to that format. This re-encoding would need to happen whenever the mount config changes to make sure the format always matches. That would need a LS script that has the output format configs as input variables to make this easily usable from the PHP application. A basic script of re-encoding a file looks like [this](http://u.delta9.pl/k/liquidsoap/scripts/reencoding.liq).

**Comment by SlvrEagle23** [comment]
@Vaalyn Possible, except on Docker PHP can't initialize Liquidsoap directly because it lives on a different container. That's prevented us from doing a lot of "live transcoding" that we'd otherwise want to do, as Supervisor lets us interact in the long-term but not with short little one-off things.

**Comment by Vaalyn** [comment]
@SlvrEagle23 Ah that makes sense. We would basically need some kind of trancoding microservice in our stack that we could call from the PHP side like for example [imaginary](https://github.com/h2non/imaginary) which provides something like that for images.

**Comment by SlvrEagle23** [comment]
@Vaalyn We could use Liquidsoap itself and just spin up a one-off container, but the problem (that I've been trying to avoid for years now) is that would require PHP having access to the Docker socket, so that it can spin up containers on-demand. That's a big security footprint change that I wouldn't want to add unless absolutely necessary.

**Comment by Vaalyn** [comment]
@SlvrEagle23 That's why I think a really small microservice would make more sense than a one-off container. It would add a little bit to the base footprint of the AzuraCast stack but I think depending on what features we could then add to AzuraCast this could be a good addition. As an example of the memory usage of such a microservice imaginary has a memory footprint of around 5mb according to `docker stats`.

**Comment by SlvrEagle23** [comment]
@Vaalyn Yeah, that makes sense. Might be worth looking into, especially if we want to offer users the ability to transcode media upon upload.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39040/add-stream-intro-file-support
