### ISSUE TITLE
URL Path

### ISSUE THREAD

**Issue by williambatson** [AzuraCast/AzuraCast#1272]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by williambatson** [comment]
Looking for both Docker and traditional paths to drop a folder that's accessible via URL
If my Azuracast is located at xyz.com (xyz.com/login.php) -   I'd like access to xyz.com/myfiles/ 
Where in the install would the path be to drop such a folder/files in order to access them via browser and url? 
Thanks

**Comment by CodeSteele** [comment]
AzuraCast doesn't support side loading files on the same managed instance (we'll likely stomp on any changes you make during an upgrade), and general web server administration is outside of the scope of what support we provide.
