### ISSUE TITLE
Song position with Icecast

### ISSUE THREAD

**Issue by MyTheValentinus** [AzuraCast/AzuraCast#1273]
**Describe the solution you'd like**
With icecast you have the possibility to add meta with the current song timecode, it's ideal for VLC for example. You have the progression of the music.

From stackoverflow:
 Change this:
`StreamTitle='Pink Floyd - Welcome to the Machine';`
to this:
`StreamTitle='Pink Floyd - Welcome to the Machine (0:12/4:02)';`

**Comment by MyTheValentinus** [comment]
Same, i don't know if is possible, but add image in metadata, VLC, do not display image when playing station.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39039/song-position-in-icecast-metadata
