### ISSUE TITLE
Song title renaming: lower-case letter changes ignored

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1274]
Hi, 

I observed a strange behavior. I had a song titled something like "NAME111 morename". I changed the title to "name111 morename", saved it, which all seemed to be fine as the new song title was listed under Music Files. Then when the song was played, Azuracast still showed "NAME111 morename", same for the nowplaying web API. 

It was even more strange when I changed the title to "name111 someothernamehere", which worked (song was played and the correct metadata was shown), but when I changed it back to "name111 morename" it ignored the lower case part and still used the original name. 

Any idea? 

Thanks, 

Peter

**Comment by SlvrEagle23** [comment]
@gammaw Changes made to a media item's casing/punctuation/spacing, etc. that still yield the same "song hash" (which is basically the song artist and title converted to lowercase with punctuation and spacing removed) will still apply to that Song record, which should fix that problem and make sure those changes take effect across the system.
