### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by bubic351** [AzuraCast/AzuraCast#1275]
Hello

I get this error:

root@vps :/var/azuracast/www# ./install.sh
Checking for Ansible: install ok installed
Installing AzuraCast (Environment: production)
ERROR: become is not a legal parameter at this level in an Ansible Playbook

Anyone know how to fix this?

Thank you

**Comment by SlvrEagle23** [comment]
@bubic351 Can you tell me what version of Ansible you're running? I'd assume the command to find out would be something similar to `ansible --version`.

**Comment by bubic351** [comment]
Solved it with Reinstall of Linux system.
Thanks anyway.
