### ISSUE TITLE
Add Streamer/DJ Accounts API Endpoint

### ISSUE THREAD

**Issue by berkaygndzs** [AzuraCast/AzuraCast#1277]
**Is your feature request related to a problem? Please describe.**
Yes, a personal issue though. I want to put DJ account information on a page.

**Describe the solution you'd like**
You can create an API for getting & creating DJ accounts.

**Describe alternatives you've considered**
I thought I could parse the accounts page but, that's not secure.

**Additional context**
None.

**Comment by muppathimoonu** [comment]
But the API already supports for getting DJ account details. Eg. {{ live.streamer_name }} returns the current RJ

**Comment by SlvrEagle23** [comment]
@muppathimoonu That's for retrieving who is currently DJing on the station, not for actually creating/editing/deleting those DJ accounts.

**Comment by muppathimoonu** [comment]
Yes I know.
