### ISSUE TITLE
Azuracast Authentication API

### ISSUE THREAD

**Issue by Weigand-Dev** [AzuraCast/AzuraCast#1278]
Hello, i have a question. How i can get content from the authenticated
API? I want to get the admin users with php for example.

Can you send me the code to get the content with php?

Thanks.

**Comment by Vaalyn** [comment]
To retrieve data from the authenticated API endpoints you need to create a token from the web interface and use that in the requests that you make to the API. See [this part](https://www.azuracast.com/api.html#api-authentication) of our documentation.

I'm currently working on an [API client PHP library](https://packagist.org/packages/vaalyn/azuracast-api-client) for AzuraCast. You can take a look at how the authenticated API calls are done there. Some endpoints are not yet implemented in this library but it should help you figuring out how to use the authenticated API endpoints.
