### ISSUE TITLE
Added a task to improve the randomness of music

### ISSUE THREAD

**Issue by Ficreet** [AzuraCast/AzuraCast#1284]
Hello,

The random of a playlist is only formed when it is saved, but after a while we realize that the titles are in a "random sequence" (And the other random function too often repeats the same titles for my taste).
So is it possible to add a task that, every X times (Defined by the user), will re-perform the random of the playlist?

I think this feature would be very practical within Azura Cast!

Waiting for an answer from you
Sincerely

**Comment by SlvrEagle23** [comment]
I've made a new "super issue" regarding randomness of playlists and steps stations can take to improve this. You should follow that issue at #1285.
