### ISSUE TITLE
Delete Button

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#1286]
I have many large Stations. If i see all song it is not very good to first check one song, scroll up and then delete the Song from all playlists, then search the Song and then add the Song to another playlist. I wish a feature so simple delete the Song from the Playlist i see.
For example a Button next to the Edit Button.

**Comment by SlvrEagle23** [comment]
@preterive The playlist functionality has been greatly simplified to handle situations like this much more easily.
