### ISSUE TITLE
Kick the DJ off air API Endpoint

### ISSUE THREAD

**Issue by berkaygndzs** [AzuraCast/AzuraCast#1287]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I think an API endpoint for kicking the DJ off of air would be nice.
**Describe alternatives you've considered**
I thought about Icecast having this feature, but I don't think that's possible.
**Additional context**
None.

**Comment by SlvrEagle23** [comment]
@berkaygndzs Sorry for the delay in getting back to this, but I just noticed that it was a part of my "API Parity" project, but it actually already exists:

https://www.azuracast.com/api/#/Stations%3A%20Service%20Control/App%5CController%5CApi%5CStations%5CServicesController%3A%3AbackendAction

You can specify the last parameter, `action`, as "disconnect" and it will disconnect the currently active DJ, and time out their reconnection for as long as the reconnect threshold is specified.
