### ISSUE TITLE
Add scheduling option to Once Per x Minutes/Songs playlists

### ISSUE THREAD

**Issue by ma-vie** [AzuraCast/AzuraCast#1289]
Hello,

we want to add some Advert-Spots every 1 hour, but only from Monday to Friday. 
Now we are using the "Once Per x Minutes" Playlist. Which plays every day.

It would be nice when "Once Per x Minutes" and "Once Per x Songs" could get the same options like "Schedule"-Playlist

![image](https://user-images.githubusercontent.com/45437669/54091449-5dcb7300-4380-11e9-9ff1-8ff908d94a34.png)

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39041/make-once-per-x-playlists-schedulable
