### ISSUE TITLE
Update goes wrong

### ISSUE THREAD

**Issue by rolradio** [AzuraCast/AzuraCast#129]
Hey,
Yesterday I found an update for the aac stream updates.
Apparently there was some mistake in installing.
The shoutcast2 folder was empty.
I've put the sc_serv manually into the directory.
The shoutcast server is apparently running now.
But I get an error message in liquidsoap:
NO_FILE: can not find command '/var/azuracast/.opam/system/bin/liquidsoap'

What can I do best here?
Because all of my radio stations I was already working are quiet now.

**Comment by SlvrEagle23** [comment]
@rolradio Can you send me the log of the update? You can try running it again and just paste the part that errors out. Then I can help diagnose the issue.

**Comment by rolradio** [comment]
That is the log from my update i just did.
I see no errors here. but in my azuracast panel the error stay.

root@vmi94402:~# cd /var/azuracast/www
root@vmi94402:/var/azuracast/www# sudo chmod a+x update.sh
root@vmi94402:/var/azuracast/www# sudo ./update.sh
Checking for Ansible: install ok installed
Updating AzuraCast (Environment: production)
HEAD is now at b776c87 Give everything 777 on the testing server because Travis CI is a waking nightmare.
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 22 (delta 17), reused 22 (delta 17), pack-reused 0
Unpacking objects: 100% (22/22), done.
From https://github.com/SlvrEagle23/AzuraCast
   b776c87..cca7e94  master     -> origin/master
Updating b776c87..cca7e94
Fast-forward
 app/config/forms/mount_icecast.conf.php               |  1 +
 app/config/forms/mount_shoutcast2.conf.php            |  1 +
 app/modules/stations/controllers/UtilController.php   | 74 ++++++-------------------------
 app/modules/stations/views/profile/index.phtml        | 40 +++++++++++++++--
 app/modules/stations/views/sidebar.phtml              |  4 --
 app/src/AzuraCast/Radio/Frontend/FrontendAbstract.php |  2 +-
 app/src/AzuraCast/Radio/Frontend/IceCast.php          | 92 +++++++++++++++++++--------------------
 app/src/AzuraCast/Radio/Frontend/ShoutCast2.php       | 57 ++++++++++++++----------
 8 files changed, 132 insertions(+), 139 deletions(-)

PLAY [all] *****************************************************************************************

TASK [Gathering Facts] *****************************************************************************
ok: [localhost]

TASK [init : debug] ********************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "Running Ansible on localhost with OS Ubuntu trusty 14.04 x86_64 (production)"
}

TASK [init : debug] ********************************************************************************
skipping: [localhost]

TASK [init : Update apt] ***************************************************************************
changed: [localhost]

TASK [init : Install system packages] **************************************************************
ok: [localhost] => (item=[u'apt-transport-https', u'curl', u'wget', u'tar', u'build-essential', u'python-software-properties', u'pwgen', u'whois', u'python-pip', u'lnav'])

TASK [init : Update pip components] ****************************************************************
ok: [localhost] => (item=pip)

TASK [azuracast-config : Use Default Configuration Files] ******************************************
ok: [localhost] => (item=db)
ok: [localhost] => (item=influx)
ok: [localhost] => (item=cache)

TASK [azuracast-config : Write current environment to file.] ***************************************
ok: [localhost]

TASK [azuracast-config : Set Permissions on Base App Folder] ***************************************
ok: [localhost] => (item=/var/azuracast)

TASK [azuracast-config : Touch base-level files] ***************************************************
changed: [localhost] => (item=/var/azuracast/.deploy_run)

TASK [azuracast-config : Create System Folders] ****************************************************
ok: [localhost] => (item=/var/azuracast/www_tmp)
ok: [localhost] => (item=/var/azuracast/www_tmp/cache)
ok: [localhost] => (item=/var/azuracast/www_tmp/sessions)
ok: [localhost] => (item=/var/azuracast/www_tmp/proxies)
ok: [localhost] => (item=/var/azuracast/stations)
ok: [localhost] => (item=/var/azuracast/servers)
changed: [localhost] => (item=/var/azuracast/servers/shoutcast2)
ok: [localhost] => (item=/var/azuracast/servers/icecast2)

TASK [azuracast-config : Make App Directory Writeable] *********************************************
skipping: [localhost]

TASK [azuracast-radio : Install IceCast-KH Dependencies] *******************************************
skipping: [localhost] => (item=[])

TASK [azuracast-radio : Download IceCast-KH Source] ************************************************
skipping: [localhost]

TASK [azuracast-radio : Extract IceCast-KH Source] *************************************************
skipping: [localhost]

TASK [azuracast-radio : Build IceCast-KH] **********************************************************
skipping: [localhost]

TASK [azuracast-radio : Link IceCast Resource Files] ***********************************************
skipping: [localhost] => (item={u'dest': u'/usr/local/share/icecast/web/error.mp3', u'src': u'/var/azuracast/www/resources/error.mp3'})
skipping: [localhost] => (item={u'dest': u'/usr/local/share/icecast/web/status-json.xsl', u'src': u'/var/azuracast/www/resources/status-json.xsl'})
skipping: [localhost] => (item={u'dest': u'/usr/local/share/icecast/web/xml2json.xslt', u'src': u'/var/azuracast/www/resources/xml2json.xslt'})

TASK [azuracast-radio : Add OPAM Repository] *******************************************************
skipping: [localhost]

TASK [azuracast-radio : Update apt again] **********************************************************
skipping: [localhost]

TASK [azuracast-radio : Install OPAM] **************************************************************
skipping: [localhost]

TASK [azuracast-radio : Install LiquidSoap Dependencies] *******************************************
skipping: [localhost] => (item=[])

TASK [azuracast-radio : Build LiquidSoap] **********************************************************
skipping: [localhost]

TASK [azuracast-radio : Download ShoutCast 2 (x86)] ************************************************
skipping: [localhost]

TASK [azuracast-radio : Download ShoutCast 2 (x64)] ************************************************
skipping: [localhost]

TASK [azuracast-radio : Extract ShoutCast 2 Binary] ************************************************
skipping: [localhost]

TASK [nginx : Install nginx] ***********************************************************************
skipping: [localhost]

TASK [nginx : Create nginx ssl directory] **********************************************************
skipping: [localhost] => (item=/etc/nginx/ssl)

TASK [nginx : Create self-signed SSL cert] *********************************************************
skipping: [localhost]

TASK [nginx : Remove default nginx site symlink] ***************************************************
skipping: [localhost]

TASK [nginx : Add app-specific nginx site] *********************************************************
skipping: [localhost]

TASK [nginx : Link app-specific nginx site] ********************************************************
skipping: [localhost]

TASK [nginx : Turn sendfile off on nginx for local development] ************************************
skipping: [localhost]

TASK [php : Add PHP PPA repository] ****************************************************************
skipping: [localhost]

TASK [php : Update apt again] **********************************************************************
skipping: [localhost]

TASK [php : Remove Old PHP Libraries] **************************************************************
skipping: [localhost] => (item=[])

TASK [php : Install PHP 7.1] ***********************************************************************
skipping: [localhost] => (item=[])

TASK [php : Remove PHP 7.0] ************************************************************************
skipping: [localhost] => (item=[])

TASK [php : List locales] **************************************************************************
skipping: [localhost]

TASK [php : Create Locales] ************************************************************************

TASK [php : Configure PHP FPM Pool] ****************************************************************
skipping: [localhost]

TASK [php : Configure php-fpm php.ini] *************************************************************
skipping: [localhost] => (item={u'option': u'post_max_size', u'value': u'50M'})
skipping: [localhost] => (item={u'option': u'short_open_tag', u'value': u'On'})
skipping: [localhost] => (item={u'option': u'upload_max_filesize', u'value': u'25M'})

TASK [php : Configure php-cli php.ini] *************************************************************
skipping: [localhost] => (item={u'option': u'short_open_tag', u'value': u'On'})

TASK [influxdb : Add InfluxDB repo file] ***********************************************************
skipping: [localhost]

TASK [influxdb : Add InfluxDB repo key] ************************************************************
skipping: [localhost]

TASK [influxdb : Update apt cache] *****************************************************************
skipping: [localhost]

TASK [influxdb : Install python-influxdb] **********************************************************
skipping: [localhost] => (item=influxdb)

TASK [influxdb : Install InfluxDB] *****************************************************************
skipping: [localhost] => (item=[])

TASK [influxdb : restart influxdb] *****************************************************************
skipping: [localhost]

TASK [influxdb : Pause to allow InfluxDB to spin up] ***********************************************
skipping: [localhost]

TASK [influxdb : Create 'stations' database] *******************************************************
skipping: [localhost] => (item=stations)

TASK [influxdb : Create 'stations' retention policies] *********************************************
skipping: [localhost] => (item={u'duration': u'5d', u'default': True, u'name': u'15s'})
skipping: [localhost] => (item={u'duration': u'2w', u'default': False, u'name': u'1h'})
skipping: [localhost] => (item={u'duration': u'INF', u'default': False, u'name': u'1d'})

TASK [influxdb : Manage continuous queries on 'stations'] ******************************************
skipping: [localhost]

TASK [influxdb : Lock down InfluxDB to localhost requests] *****************************************
skipping: [localhost]

TASK [supervisord : Install supervisord] ***********************************************************
skipping: [localhost]

TASK [supervisord : Change supervisord configuration] **********************************************
skipping: [localhost]

TASK [supervisord : Kill legacy radio processes (if upgrading from older version)] *****************
skipping: [localhost]

TASK [supervisord : Trigger manual restart of supervisord (if not already running)] ****************
skipping: [localhost]

TASK [azuracast-cron : Generate Cron Template] *****************************************************
skipping: [localhost]

TASK [azuracast-cron : Install Cron file] **********************************************************
skipping: [localhost]

TASK [azuracast-cron : Clean up temp Cron file] ****************************************************
skipping: [localhost]

TASK [azuracast-update : Make update script executable again] **************************************
changed: [localhost]

TASK [azuracast-update : Install Composer Dependencies (Development)] ******************************
skipping: [localhost]

TASK [azuracast-update : Install Composer Dependencies (Production)] *******************************
changed: [localhost]

TASK [azuracast-update : Clear AzuraCast Cache] ****************************************************
changed: [localhost]

TASK [azuracast-update : Update Database] **********************************************************
changed: [localhost]

TASK [azuracast-update : Restart Radio Stations] ***************************************************
changed: [localhost]

PLAY RECAP *****************************************************************************************
localhost                  : ok=15   changed=8    unreachable=0    failed=0

root@vmi94402:/var/azuracast/www#

**Comment by rolradio** [comment]
Maybe I can send you my login credentials securely?

**Comment by SlvrEagle23** [comment]
@rolradio Try the latest update. It should force a radio recompilation regardless of previous updates. If you still encounter an issue, be sure to paste that log to me and let me know.

**Comment by rolradio** [comment]
I have done the update with this comando

Cd / var / azuracast / www

Sudo chmod a + x update.sh
Sudo ./update.sh

Is this the right way?

**Comment by SlvrEagle23** [comment]
```
cd /var/azuracast/www
sudo chmod a+x update.sh
sudo ./update.sh
```

Yes this would normally be the update process. Did you run it again?

**Comment by rolradio** [comment]
cd /var/azuracast/www

sudo chmod a+x update.sh
sudo ./update.sh

**Comment by rolradio** [comment]
OK nice
Everything works again.
Thank you for the support!!!
