### ISSUE TITLE
Public Page - Player (Página Publica - Player)

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#1290]
** Does your appeal request relate to a problem? Please describe. **

: In the Public Page, the player in the mobile version is not responsive.

** Describe the solution you would like **

: Image attached.
I would like the text to have scrolling effect when it is large texts. Increase album cover size.

On smartphones when accessed the page publishes, only icons appear instead of the written ones: (Musical request, playlist, music history)

Thank you all for your attention.

Att
Rafael - Brazil

**Comment by SlvrEagle23** [comment]
We have fixed issues with the text being truncated properly on smaller screens, and you can hover over the element to show the full text, but we don't currently have any plans to scroll the text.
