### ISSUE TITLE
Request: Remove track from specific playlist

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1292]
It would be great if you can remove tracks from one specific playlist (not "Clear Playlists", this removes the track from all playlists). Is this possible? 

Thanks for all your work! You're cool!

**Comment by SlvrEagle23** [comment]
@MrSteelMiner This has actually been bugging me for a while as a station operator myself, so I've reworked the playlist management on the Media Files page to be replaced by a single "Set Playlists" feature, which lets you check multiple boxes to assign selected files to the assigned playlists (or just leave all the boxes unchecked to set it to none) or create a new one.
