### ISSUE TITLE
Api (album cover,  recent songs, etc.)

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#1295]
Hello. How do I add the api from you to my app?
I would like to use the album cover, recent songs, music team. It is possible? Do you provide?

Thank you for existing. 🥇 

Att
Rafael - Brasil

**Comment by preterive** [comment]
Wich App?
A Api is aviable under https://your.adress/api , for example https://adress/api/nowplaying/

**Comment by Rafaelrds2017** [comment]
I have a multi-radios app. It uses api last.fm to play album cover. But the quality of AzuraCast's album cover is superior.

If possible, I wanted to use the api of you, AZURACAST to insert in my app, to reproduce the information of the next song, current song, album cover, music time.

Do you share this api? If so, tell me how I can get :)

**Comment by Rafaelrds2017** [comment]
this is my app
https://play.google.com/store/apps/details?id=com.musicandonaweb.radios.xradio

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 Every installation of AzuraCast exposes an API that you can consume from your application. You can visit `http://your-azuracast-address/api` to see the full documentation of all of the available API endpoints.

The most popular endpoint is `/api/nowplaying`, which shows all stations on the installation, what is currently playing, who is listening, what is playing next (if eligible) and what was previously played.

**Comment by preterive** [comment]
Sorry, but i can't use the App on any of my devices. I Come from Germany, have devices with android 9,7,6 .

In wich language do you write your app? I already have a function for this in my cordova app, if you want i can share the Code on Github.

**Comment by Rafaelrds2017** [comment]
Thanks for the information and the attention.

**Comment by JMultimidia** [comment]
@preterive If it is possible to make it available in github. I also use cordova and I was curious.

**Comment by Rafaelrds2017** [comment]
> Sorry, but i can't use the App on any of my devices. I Come from Germany, have devices with android 9,7,6 .
> 
> In wich language do you write your app? I already have a function for this in my cordova app, if you want i can share the Code on Github.

Yes I want. If you can share, thank you.
