### ISSUE TITLE
Add scheduling option to General Rotation Playlists

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1296]
It would be cool to have something like a mix of "Scheduled" and "General Rotation".
For example I want to have 2 playlists mixed (with weight-system) but only between 1 and 3 PM.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39036/make-scheduled-playlists-shuffle-with-weighted-priority
