### ISSUE TITLE
Enhancement of "Scheduled" Playlists

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1297]
I think, it would be nice to have a playlist played multiple times a day and on different times per day.
Example:
- Mondays from 2-7 AM and 5-6 PM
- Tuesdays from 5-7 AM, 1-3 PM and 8-9 PM
- ... and so on

Maybe in the second step like #1184

Greetings from Germany!

**Comment by muppathimoonu** [comment]
Now, Playlist scheduling works on basis of weekdays. I've to recreate playlists for every weeks.
Instead, if it's based on date(1-30/31), we can schedule more programs for whole month.

#1298

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38780/allow-multiple-schedule-entries-for-a-single-playlist
