### ISSUE TITLE
Custom Webhook Trigger

### ISSUE THREAD

**Issue by muppathimoonu** [AzuraCast/AzuraCast#1299]
An option to create custom Webhook Triggers.

**Comment by SlvrEagle23** [comment]
@muppathimoonu What events would you have trigger webhooks? They're currently only used for changes to the "Now Playing" information.

**Comment by SlvrEagle23** [comment]
@muppathimoonu If you have any ideas for situations that should trigger a web hook, please let me know; otherwise, I'm closing this issue as lacking additional information.
