### ISSUE TITLE
Can't log in after update  (database error)

### ISSUE THREAD

**Issue by Zellouser** [AzuraCast/AzuraCast#1307]
![error1](https://user-images.githubusercontent.com/48444758/54417120-8bf2df00-4701-11e9-8d0f-8de1683425d7.PNG)
![error2](https://user-images.githubusercontent.com/48444758/54417150-a1680900-4701-11e9-8718-09d1047a869e.PNG)
![error3](https://user-images.githubusercontent.com/48444758/54417163-a927ad80-4701-11e9-9478-29bf934a1867.PNG)
![error4](https://user-images.githubusercontent.com/48444758/54417698-38819080-4703-11e9-838b-406c148c7f9e.PNG)

**Installation method**
Docker - Installation
**Host OS (for Docker installations)**
Ubuntu 18.04 LTS

**Describe the bug**
these errors appear during the update installation.
rebooting server
I have repeated the update installation for safety
the mistakes do not disappear.
a login to the azurcast website is no longer possible.
Is it possible to repair the database?

Greetings from Germany

**Comment by Vaalyn** [comment]
I'm not sure what caused this but from the errors it seems like your database is missing the `users` table which should not just suddenly vanish. None of the newly added migrations ([1](https://github.com/AzuraCast/AzuraCast/blob/master/src/Entity/Migration/Version20190314074747.php), [2](https://github.com/AzuraCast/AzuraCast/blob/master/src/Entity/Migration/Version20190314203550.php) & [3](https://github.com/AzuraCast/AzuraCast/blob/master/src/Entity/Migration/Version20190315002523.php)) have any operation in them that could lead to a deletion of that table.

To verify if the table is indeed completely missing from your database please execute the following steps and post the output of the last command here:

1. Connect to your AzuraCast server via `ssh`
2. Enter the MariaDB docker container with the following command `docker exec -it azuracast_mariadb_1 bash`
3. Enter the database with the following command `mysql -hlocalhost -uazuracast -pazur4c457`
4. Select the azuracast database with this command `USE azuracast`
5. List all existing tables in the database with this command `SHOW TABLES;`

After you've done that you can `exit` both the database and docker container.

**Comment by SlvrEagle23** [comment]
@Zellouser Just to confirm, when you're updating are you running:

```
./docker.sh update-self
./docker.sh update
```

in that order? This may be caused by the Docker utility script itself being out of date.

**Comment by Zellouser** [comment]
@SlvrEagle23  exactly in this order.

@Vaalyn  I checked, the usertable is missing.
is there a possibility to create the user table manually?
So I could log in and create the user again.

**Comment by Vaalyn** [comment]
I don't have a full SQL command for that at hand but you could rebuilt the table by executing a `CREATE TABLE` command that re-creates the users table structure:
```
+-------------------+--------------+------+-----+---------+----------------+
| Field             | Type         | Null | Key | Default | Extra          |
+-------------------+--------------+------+-----+---------+----------------+
| uid               | int(11)      | NO   | PRI | NULL    | auto_increment |
| email             | varchar(100) | YES  | UNI | NULL    |                |
| auth_password     | varchar(255) | YES  |     | NULL    |                |
| name              | varchar(100) | YES  |     | NULL    |                |
| timezone          | varchar(100) | YES  |     | NULL    |                |
| locale            | varchar(25)  | YES  |     | NULL    |                |
| created_at        | int(11)      | NO   |     | NULL    |                |
| updated_at        | int(11)      | NO   |     | NULL    |                |
| theme             | varchar(25)  | YES  |     | NULL    |                |
| two_factor_secret | varchar(255) | YES  |     | NULL    |                |
+-------------------+--------------+------+-----+---------+----------------+
```

**Comment by Zellouser** [comment]
At the first attempt of the update came an error message that he can not create the two new tables. then I did a reboot of the server.
The second attempt of the updates (screenshots at the top) it then remained with this error.

Okay then I'll spend some time in SQL education. :)
Many Thanks

**Comment by SlvrEagle23** [comment]
@Zellouser If you figure out what caused this issue I would be very curious to know. There's nothing in AzuraCast's code that would be dropping a DB table, especially during routine migrations and updates.

**Comment by Zellouser** [comment]
I try to find LOG-files :)
