### ISSUE TITLE
Error Hide Metadata from Listeners ("Jingle Mode") Not Working

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#1310]
Traditional.

Hi, I installed the new update, and I enabled the jingle option. The problem is that it doesn't work, and continues to write the jingle. I leave the screens

![image](https://user-images.githubusercontent.com/22561729/54436989-ef960000-4733-11e9-972b-1d2c47be5ee9.png)
![image](https://user-images.githubusercontent.com/22561729/54437002-f91f6800-4733-11e9-8f64-7106165bd075.png)
![image](https://user-images.githubusercontent.com/22561729/54437023-03d9fd00-4734-11e9-8482-dff2b7eb4e0d.png)
![image](https://user-images.githubusercontent.com/22561729/54437185-629f7680-4734-11e9-814f-68451b993830.png)

**Comment by SlvrEagle23** [comment]
@Ilario42 The "playing next" field is currently unaffected by jingle mode, but the "now playing" field should always be avoiding those files.

**Comment by Ilario42** [comment]
No, even the track that is playing is shown, could it be because it was requested?

@SlvrEagle23

**Comment by SlvrEagle23** [comment]
@Ilario42 Did you set that playlist to allow requests from it? You probably shouldn't set that for your jingles playlist.

**Comment by Ilario42** [comment]
I need to make requests with jingles for hourly voting, could we fix this problem ????
@SlvrEagle23 

Kind regards
Ilario

**Comment by SlvrEagle23** [comment]
@Ilario42 Requests are not processed in the same way as regular playlists. A song that's in a "jingle mode" playlist but is requested will be processed the same way as all other requests.

This isn't something we expect to be happening very often, as the vast majority of stations don't want their station ID jingles or ads to be requestable songs.
