### ISSUE TITLE
Updating with Docker composer.json problem

### ISSUE THREAD

**Issue by juanamm** [AzuraCast/AzuraCast#1315]
Installation method : Docker
Host OS (for Docker installations): Debian GNU/Linux 9.8 (stretch) x64 bit
VPS: Google Cloud Platform

Describe the bug
Screenshoot:
![composer](https://user-images.githubusercontent.com/48572613/54469010-7ae1b680-4771-11e9-981b-f73a064bc774.png)

I have executed:
```
./docker.sh update-self
./docker.sh update
```
The bug:

> (Environment: development)
> Composer could not find a composer.json file in /var/azuracast/www
> To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
> Could not open input file: bin/azuracast.php
> 2019/03/16 01:42:34 Command exited with error: exit status 1

I am a newbie and I have followed this [guide](https://getcomposer.org/doc/00-intro.md), and I have installed the executable locally and globally, it did not give me any errors.

Maybe I installed it in a wrong path.  :(

Could you explain to me in a simple way (as for a child) how to fix this error?

**Comment by SlvrEagle23** [comment]
@juanamm For some reason, your environment is set to `development`, which expects a local copy of the codebase (since development would mean you have the entire code local to your machine and you're modifying it), but one doesn't exist in this case.

The easy fix would be to open `azuracast.env` on your host and change the environment to `production`.

**Comment by juanamm** [comment]
Thanks SlvrEagle23 fixed!!! :)

Now I have another problem, I'm sure it's from my Google Cloud Platform host.
I am using a free version (trial) that I have not yet verified with my credit card.
I enter the [URL](http://35.231.177.111/) indicated by Azura but nothing happens.

![url](https://user-images.githubusercontent.com/48572613/54469900-cb5f1100-477d-11e9-8d72-09d4ca6017de.png)

Do you have any idea if this can be fixed in any way?

**Comment by Vaalyn** [comment]
When I try to visit that page the site loads for some time and then times out. How much load is on the machine when AzuraCast is running and how much when you try to open that page? On the first look this seems like it could be a resource problem.

**Comment by juanamm** [comment]
Mmm, I'm afraid it's not a resource problem, but I'm using a Google Cloud console that is not associated with any virtual machine.

Until I verify my identity with a credit / debit card I can not use the VM and it only works localhost.

I think we left the subject of the thread, thank you very much and we can consider this bug closed.

Regards,
Juan
