### ISSUE TITLE
certificate and second installation

### ISSUE THREAD

**Issue by Radiopop** [AzuraCast/AzuraCast#1318]
I have 2 questions, should I install a certificate in the vps that is instauraio azuracast ?, How do I do it ?.
The second question is, can a second station be created in the same control panel? Should I do another installation? Should I hire another vps?

**Comment by Vaalyn** [comment]
We'd strongly recommend you to setup SSL certificates in AzuraCast to secure your connection to the web interface. We have a easy to use tool integrated in AzuraCast that you can use to automatically setup and renew the certificate. [Here](https://www.azuracast.com/docker_sh.html#set-up-letsencrypt) is the page from our documentation.

AzuraCast supports setting up multiple stations on the same installation. You can add new stations in the `System Administration` -> `Stations` page.

**Comment by NakedFool** [comment]
Hey @Vaalyn  - This link redirects to 404 for setting up certificate.

Is there any new guide or something like that? I couldn't find it in the readme also

**Comment by ErnestPH** [comment]
@NakedFool Installing a certificate is quite easy, just follow [this](https://www.azuracast.com/developers/docker_sh.html#available-commands)

In the meantime, you can close this already.

**Comment by NakedFool** [comment]
@ErnestPH Thank you man! 

Just one question before it is closed and it may be off-topic but does Docker comes with basic installation following the digitalocean path to install or i need to set it up after basic installation of azurecast?

**Comment by ErnestPH** [comment]
You can use either DO's docker specific droplet or just the uBuntu 18 droplet… All of them will work fine. No need to set them up… Just install Azuracast right away

**Comment by NakedFool** [comment]
I'm using ubuntu droplet. But after installation do i need to install docker utility script as this?

`curl -L https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh
chmod a+x docker.sh
./docker.sh install
`

**Comment by ErnestPH** [comment]
That is the first step of installing Azuracast, just follow the installation process and you will be fine… https://www.azuracast.com/install/#installing

**Comment by SlvrEagle23** [comment]
@NakedFool If you followed the DigitalOcean installation instructions, your instance will be ready to go and you can continue setup using the web interface from there; you shouldn't need to do any further work in the command line to spin it up.
