### ISSUE TITLE
.wav and others extensions support

### ISSUE THREAD

**Issue by jimpy51** [AzuraCast/AzuraCast#132]
Hello,

How it's possible to import .wav song ? Maybe developpe a feature "auto importer" to convert all songs to .mp3 for exemple ?

Regards,

**Comment by rolradio** [comment]
I think you can convert Wav much better to your own PC.
That saves your data traffic. 
And uploading and renaming the mp3 on your server costs much of cpu power.

**Comment by SlvrEagle23** [comment]
@jimpy51 I'll look into WAV support, but for now it may be helpful to know that Flac is fully supported both by the AzuraCast media editor and by LiquidSoap itself, so you can just transcode your files to that and they'll remain lossless while being able to be used with the system.

**Comment by SlvrEagle23** [comment]
I never bothered to actually test this, but WAV is already supported in the version of LiquidSoap that's built for AzuraCast, on both traditional and docker installs.
