### ISSUE TITLE
Considering WEB DJ page as internal page

### ISSUE THREAD

**Issue by muppathimoonu** [AzuraCast/AzuraCast#1320]
Now custom CSS/Javascript changes made for public pages also reflect in WebDj page as well. That is not required. WebDj page can be considered as internal page

**Comment by SlvrEagle23** [comment]
@muppathimoonu The WebDJ page is in a bit of a sticky middle ground. It isn't a "public" page like the others (because the _general_ public shouldn't be using it) but it isn't an internal page, since it has no login gate to access it and it has none of the standard navigation of the internal pages.
