### ISSUE TITLE
Error after updating the docker install ubuntu 18.04

### ISSUE THREAD

**Issue by anducampu** [AzuraCast/AzuraCast#1322]
----------------------------------------------------------
 [OK] AzuraCast is now updated to the latest version!

2019/03/19 13:11:57 Command finished successfully.
azuracast_stations is up-to-date
azuracast_redis_1 is up-to-date
azuracast_influxdb_1 is up-to-date
azuracast_mariadb_1 is up-to-date
Creating azuracast_web_1 ... error

ERROR: for azuracast_web_1  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web_1 (caa7bdf40dac25d3295499365dbea20d490779b77037201dfc4f5f07073409d5): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web_1 (caa7bdf40dac25d3295499365dbea20d490779b77037201dfc4f5f07073409d5): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.
Update complete!
-----------------------------------------

I didn't modify anything... all I did is:  sudo ./docker.sh update-self & sudo ./docker.sh update
All I see in the browser is the default Apache2 Ubuntu Default Page.

Help!

**Comment by Vaalyn** [comment]
If you are seeing a default Apache welcome page on an Ubuntu host and the startup of the AzuraCast web container fails because it can’t bind to port 80 then you have an Apache web server running on the host. Make sure to disable the Apache webserver on the Ubuntu host before starting the docker containers with:

```
sudo systemctl stop apache2
sudo systemctl disable apache2
```

**Comment by anducampu** [comment]
Ahhh! Silly me. That fixed the problem. Thank you so much.
