### ISSUE TITLE
Liquidsoap encountered an error. During Updating

### ISSUE THREAD

**Issue by isaiaswebnet** [AzuraCast/AzuraCast#1323]
Liquidsoap encountered an error
2019/03/19 16:04:05 [threads:3] Thread "generic queue #2" terminated.
2019/03/19 16:04:05 [playlist_default(dot)m3u:3] No mime type specified, trying autodetection.
2019/03/19 16:04:05 [playlist_default(dot)m3u:3] Playlist treated as format application/x-mpegURL
2019/03/19 16:04:05 [playlist_default(dot)m3u:3] Successfully loaded a playlist of 0 tracks.
2019/03/19 16:04:05 [threads:3] Thread "generic queue #1" terminated.
2019/03/19 16:04:05 [main:3] Freeing memory...

**Comment by Vaalyn** [comment]
From the logs you posted it looks like your playlist is empty and liquidsoap has nothing to play and thus terminates. If this is not the case please add some more information to this issue by following the template for creating new bug reports. Without these additional information it can be a lot harder for us to diagnose issues. More specifically we'd need to know: Installation method, Host OS and specifics to how your setup is looking in regards to any manual liquidsoap configuration and your playlists.

**Comment by isaiaswebnet** [comment]
Remote Access Setup: SSH

Type of machine: Ubuntu, 2 vCPUs, 3.75 GB memory, 15 GB disc

LiquidSoap is currently shuffling 783 songs submitted in 7 playlists.

**Comment by SlvrEagle23** [comment]
@isaiaswebnet Are you using the Docker version of AzuraCast (the recommended installation)?

Also, the message you posted is just a standard shutdown message. Have you tried restarting the station via "Utilities" > "Restart Broadcasting"?

**Comment by isaiaswebnet** [comment]
I tried "Restart Broadcasting".

**Comment by SlvrEagle23** [comment]
@isaiaswebnet Please be as descriptive as possible, as it's impossible for us to diagnose issues when we're provided with little information.

Do you see anything else in the logs?

**Comment by isaiaswebnet** [comment]
2019/03/19 16:04:05 [main:3] Threads terminated.
2019/03/19 16:04:05 [threads:3] Shutting down scheduler...
2019/03/19 16:04:05 [threads:3] Scheduler shut down.
2019/03/19 16:04:05 [server:3] Closing socket.
2019/03/19 16:04:05 [main:3] Cleaning downloaded files...
2019/03/19 16:04:05 [threads:3] Thread "non-blocking queue #1" terminated.
2019/03/19 16:04:05 [threads:3] Thread "non-blocking queue #2" terminated.
2019/03/19 16:04:05 [threads:3] Thread "generic queue #2" terminated.
2019/03/19 16:04:05 [playlist_default(dot)m3u:3] No mime type specified, trying autodetection.
2019/03/19 16:04:05 [playlist_default(dot)m3u:3] Playlist treated as format application/x-mpegURL
2019/03/19 16:04:05 [playlist_default(dot)m3u:3] Successfully loaded a playlist of 0 tracks.
2019/03/19 16:04:05 [threads:3] Thread "generic queue #1" terminated.
2019/03/19 16:04:05 [main:3] Freeing memory...

**Comment by isaiaswebnet** [comment]
Use traditional installation method

**Comment by SlvrEagle23** [comment]
@isaiaswebnet Do you have "Manual AutoDJ" mode turned on for this station?

**Comment by isaiaswebnet** [comment]
Yes, Habilitar AutoDJ

**Comment by SlvrEagle23** [comment]
@isaiaswebnet If you turn it off, does it make the station work again?

**Comment by isaiaswebnet** [comment]
Not work

**Comment by isaiaswebnet** [comment]
This warning now appears.

Method not allowed
Method not allowed. Must be one of: POST, OPTIONS

**Comment by SlvrEagle23** [comment]
@isaiaswebnet When doing what? When restarting?

Your Javascript may be messing up on that page. Try reloading and try again.

**Comment by isaiaswebnet** [comment]
Failed to load resource /api/station/3/backend/start:1

**Comment by SlvrEagle23** [comment]
@isaiaswebnet There's no need to be brief in your responses, and in fact I would prefer if you weren't and told me as much as possible about each error, including screenshots of the Chrome web console in this case.

**Comment by isaiaswebnet** [comment]
Thank you. Resolved used ./update.sh --full.

**Comment by SlvrEagle23** [comment]
@isaiaswebnet Glad you were able to resolve the issue.
