### ISSUE TITLE
Discord Webhook - Color Field

### ISSUE THREAD

**Issue by JackKellyBayliss** [AzuraCast/AzuraCast#1324]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
I'd like the customization option to change the Discord Webhook Embed Color.

**Describe alternatives you've considered**
Manually editing the files but that wouldn't be a permanent solution.

**Additional context**
Nope.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39035/add-customizable-color-to-discord-web-hook
