### ISSUE TITLE
Erro LiquidSoap 

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#1325]
I am with my stations off the air, the following error appears:

Liquidsoap encountered an error
2019/03/19 20:20:02 [threads:3] Thread "non-blocking queue #2" terminated.
2019/03/19 20:20:02 [threads:3] Queues shut down
2019/03/19 20:20:02 [server:3] Closing socket.
2019/03/19 20:20:02 [main:3] Cleaning downloaded files...
2019/03/19 20:20:02 [main:3] Freeing memory...
2019/03/19 20:20:02 >>> LOG END

Can someone help me?

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 Based on the information you provided me via e-mail, it appears you are running 52 separate stations on a single AzuraCast instance.

While it's possible that sufficient hardware could handle this, there's almost no VPS out there that could handle 52 separate stations, even with a single mount point each, let alone multiple.

Can you tell me which station is having this problem, and supply me (via e-mail) with administrator credentials for the AzuraCast web UI itself?

**Comment by Rafaelrds2017** [comment]
I created another VPS. And I installed Azura again. Now everything is normal.

But it does not support 50 radios 1 vps?


Att
Rafael
________________________________
De: SlvrEagle23 <notifications@github.com>
Enviado: terça-feira, 19 de março de 2019 22:17
Para: AzuraCast/AzuraCast
Cc: Rafael Rodrigues; Mention
Assunto: Re: [AzuraCast/AzuraCast] Erro LiquidSoap (#1325)


@Rafaelrds2017<https://github.com/Rafaelrds2017> Based on the information you provided me via e-mail, it appears you are running 52 separate stations on a single AzuraCast instance.

While it's possible that sufficient hardware could handle this, there's almost no VPS out there that could handle 52 separate stations, even with a single mount point each, let alone multiple.

Can you tell me which station is having this problem, and supply me (via e-mail) with administrator credentials for the AzuraCast web UI itself?

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 In theory, AzuraCast can run 50 stations, but given that one mount point on one station is anywhere from 5-10% of a single CPU, you would likely run out of resources before you reached the full set of stations. The limit here isn't AzuraCast but simply the CPU resources needed to transcode audio and prepare it for broadcast.

**Comment by Rafaelrds2017** [comment]
Obrigado pela sua atenção. Eu não tenho muito conhecimento técnico. Eu sei o básico.

Ele estava funcionando normalmente com 45 rádios e todos eles suportavam 1 vps. Mas vou reduzir o número de estações. E se precisar de mais, configurarei outra conta.

Eu tenho 2G, 2 cpu e 60 de disco
com o tempo deve falhar novamente?

Obrigado pela sua atenção.

________________________________
De: SlvrEagle23 <notifications@github.com>
Enviado: terça-feira, 19 de março de 2019 22:54
Para: AzuraCast/AzuraCast
Cc: Rafael Rodrigues; Mention
Assunto: Re: [AzuraCast/AzuraCast] Erro LiquidSoap (#1325)


@Rafaelrds2017<https://github.com/Rafaelrds2017> In theory, AzuraCast can run 50 stations, but given that one mount point on one station is anywhere from 5-10% of a single CPU, you would likely run out of resources before you reached the full set of stations. The limit here isn't AzuraCast but simply the CPU resources needed to transcode audio and prepare it for broadcast.

**Comment by Rafaelrds2017** [comment]
Thank you for your attention. I do not have much technical knowledge. I know the basic.

It was running normally with 45 radios and they all supported 1 vps. But I'm going to reduce the number of stations. And if I need more, I'll set up another account.

I have 2G, 2 cpu and 60 disk
in time it should fail again?

Thank you for your attention.

**Comment by Rafaelrds2017** [comment]
Another question;
Is there any way to save CPU?
