### ISSUE TITLE
Installing alongside other software

### ISSUE THREAD

**Issue by andrewfer000** [AzuraCast/AzuraCast#1326]
**Is your feature request related to a problem? Please describe.**
I need to be able to install this application as a web app. For example I run a LAMP stack for my website and I need to keep my site along with other apps online. So basically what I need AzuraCast to not install its own stuff and destroy my Databases and other software.

**Describe the solution you'd like**
A simple complete docker image with all required dependencies that has startup options to change all of the ports etc. So I can create a Apache reverse proxy to point to it and not have to worry about it damaging my main website and databases. Also this will make installation as simple as "docker pull, docker run [options], and reverse proxy"!   

**Describe alternatives you've considered**
None

**Comment by andrewfer000** [comment]
Yes I know Its a docker container already xD.  But how do I set up a working Apache reverse proxy to point to it and ensure it wont touch my main websites LAMP setup? Also how would I change the default ports easily.

**Comment by SlvrEagle23** [comment]
@andrewfer000 You can already change the ports that are used by the main Docker web container: https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#docker-3

**Comment by SlvrEagle23** [comment]
@andrewfer000 Also, you are correct that Docker is indeed the best solution for what you're wanting to do, as our Docker-based installation containerizes all aspects of the application, including its database, cache, and station software. The Docker containers won't interfere with or modify data outside their sandboxes.

If you're running Apache on the host, simply spinning up AzuraCast on a non-standard port and proxying traffic through to it should be sufficient.

**Comment by andrewfer000** [comment]
@SlvrEagle23 Do you know how to create a reverse proxy for AzuraCast with Apache? Reverse Proxy with Docker can be a little complex and varies from program to program.

**Comment by SlvrEagle23** [comment]
@andrewfer000 There are a number of ways of setting up a reverse proxy with Docker containers, but we don't provide support for setting those up as they depend on third-party software that we don't maintain. I would recommend trying this out on a temporary VPS and finding something that works well for your situation.

As for Docker's storage isolation, while I can't guarantee that there won't be any interactions between this software and any others on your server (that would imply liability if it did, and as our Apache license says, the software comes with no warranty), the Docker Compose script that we use for AzuraCast creates dedicated new volumes for its database/cache/etc data. There is no reason those volumes would overwrite or otherwise interfere with things on your host or even other Docker containers.

**Comment by andrewfer000** [comment]
@SlvrEagle23 well thanks for the help and advice I guess I will close this issue now. If my reverse proxy setup works well I will make a post about it. This software looks great and I can't wait to get started!

**Comment by andrewfer000** [comment]
So I tried installing and It seems that no, Its not containerized like I was expecting. I know there is no warranty or anything but just to let you know there is an issue where it will remove my apache2 server. This did not cause any damage but I need really in-depth installation documentation with more than a script. Even the Database is broken because "/root/.my.cnf" doesn't have the right root credentials.

**Comment by Vaalyn** [comment]
@andrewfer000 I'm really surprised that your apache2 was removed while installing AzuraCast via our Docker install script. There is nothing in that script that even remotely touches anything related to apache on the host machine. Also AzuraCast does not care about your existing `/root/.my.cnf`.

I'll post the complete Docker install script code at the bottom of this comment but the general steps of that script are: check if Docker is installed, if not then download the `get-docker.sh` from the official Docker website and install that like you would manually, then it checks / installs docker-compose like you would manually, creates the `.env`, `azuracast.env` and `docker-compose.yml` files and then starts the docker-compose stack.

[This](https://www.azuracast.com/install.html#recommended-installation-method) is our installation documentation and there is nothing more that you need to do that is not mentioned there already.

Here is our [SUPPORT.md](https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#use-non-standard-ports) where we mention how to use custom ports with AzuraCast.

What did you exactly execute and what was printed in the bash when you tried to install AzuraCast and apache2 was removed on your machine?

This is our Docker install script:

```
if [[ $(which docker) && $(docker --version) ]]; then
    echo "Docker is already installed! Continuing..."
else
    if ask "Docker does not appear to be installed. Install Docker now?" Y; then
        curl -fsSL get.docker.com -o get-docker.sh
        sh get-docker.sh
        rm get-docker.sh

        if [[ $EUID -ne 0 ]]; then
            sudo usermod -aG docker `whoami`

            echo "You must log out or restart to apply necessary Docker permissions changes."
            echo "Restart, then continue installing using this script."
            exit
        fi
    fi
fi

if [[ $(which docker-compose) && $(docker-compose --version) ]]; then
    echo "Docker Compose is already installed! Continuing..."
else
    if ask "Docker Compose does not appear to be installed. Install Docker Compose now?" Y; then
        if [[ ! $(which git) ]]; then
            echo "Git does not appear to be installed."
            echo "Install git using your host's package manager,"
            echo "then continue installing using this script."
            exit 1
        fi

        if [[ ! $(which curl) ]]; then
            echo "cURL does not appear to be installed."
            echo "Install curl using your host's package manager,"
            echo "then continue installing using this script."
            exit 1
        fi

        COMPOSE_VERSION=`git ls-remote https://github.com/docker/compose | grep refs/tags | grep -oP "[0-9]+\.[0-9][0-9]+\.[0-9]+$" | tail -n 1`
        sudo sh -c "curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
        sudo chmod +x /usr/local/bin/docker-compose
        sudo sh -c "curl -L https://raw.githubusercontent.com/docker/compose/${COMPOSE_VERSION}/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose"
    fi
fi

if [[ ! -f .env ]]; then
    echo "Writing default .env file..."
    curl -L https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/.env > .env
fi

if [[ ! -f azuracast.env ]]; then
    echo "Creating default AzuraCast settings file..."
    curl -L https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/azuracast.sample.env > azuracast.env
fi

if [[ ! -f docker-compose.yml ]]; then
    echo "Retrieving default docker-compose.yml file..."
    curl -L https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker-compose.sample.yml > docker-compose.yml
fi

docker-compose pull
docker-compose run --user="azuracast" --rm web azuracast_install
docker-compose up -d
```

**Comment by SlvrEagle23** [comment]
@andrewfer000 Simply put, our Docker installation method _does not_ modify packages on your host computer with the sole exception of installing Docker and Docker Compose (if you let it do so).

If you followed the "bare-metal" instructions instead, which are not Docker and thus are not containerized, then yes, it would've tried to mess with the software on your host and caused a fair amount of problems.

We keep those instructions rather far away from the (far more recommended) Docker installation instructions, which are in our 'Recommended Installation' section on our web site and in our documentation.
