### ISSUE TITLE
INFO: Working Apache 2 Reverse Proxy Example

### ISSUE THREAD

**Issue by andrewfer000** [AzuraCast/AzuraCast#1328]
Heres how it is :)

/etc/apache2/sites-available/radio.mydomain.org.conf
----------------------------------------------------------------------------------------------------------
```
<VirtualHost *:80>
    ServerName radio.mydomain.org

    ProxyPreserveHost On
    ProxyRequests Off
    ProxyPass / http://localhost:91/ 
    ProxyPassReverse / http://localhost:91/

    CustomLog /var/log/apache2/discourse_apache_proxy_https_access.log combined
    ErrorLog /var/log/apache2/discourse_apache_proxy_https_error.log
RewriteEngine on
RewriteCond %{SERVER_NAME} =radio.mydomain.org
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```
----------------------------------------------------------------------------------------------------------
Make the port (my example 91) the same as the one in the .env file (NOT THE SSL PORT)
Make sure radio.mydomain.org is your website's domain. 

You can then use Let's Encrypt to use SSL
sudo certbot --apache

(I will test the https in AzuraCast so it can be more secure)

**Comment by andrewfer000** [comment]
I found an issue where if you were to reboot the system the reverse porxy would stop working, The only fix I know is to re-install the docker image. It doesn't affect data on the server so you should be fine if you do it.

**Comment by SlvrEagle23** [comment]
@andrewfer000 By reinstall the docker image do you mean restart the docker containers? It shouldn't be necessary at all to reinstall the Docker images themselves or AzuraCast itself.

**Comment by andrewfer000** [comment]
@SlvrEagle23 I'm not sure. Ill give it a shot and see what will happen. I'm still going through Apache's documentation about reverse proxies to make it work better with HTTPS enabled sites and to fix some delay related issues.
