### ISSUE TITLE
scheduled playlist only works after restart radio?

### ISSUE THREAD

**Issue by stemvantwente** [AzuraCast/AzuraCast#1329]
Hello

I try to explain, I have a scheduled playlist that plays on monday and wednesday, this works perfectly, but if I say in this same playlist play, lets say on friday to then this doesnt work, it works but I need to say restart broadcast before liquadsoap sees I added friday to, I hope you understand me . Now my question is, is there a way to let this work without a restart? 

And is it possible to add more time? I mean like start scheduled playlist at 12:55.

Its Ubuntu 16.04 , traditional installation.
Greets
Roy

**Comment by Vaalyn** [comment]
Advanced playlists go directly through Liquidsoap for their playback and need a restart of Liquidsoap to apply changes. See #1269 for more information about this.

Regarding the question about start times I'm not sure what you mean. You can already say that a scheduled playlist should start at 12:55. Can you clarify what exactly you mean?

**Comment by stemvantwente** [comment]
> Advanced playlists go directly through Liquidsoap for their playback and need a restart of Liquidsoap to apply changes. See #1269 for more information about this.
> 
> Regarding the question about start times I'm not sure what you mean. You can already say that a scheduled playlist should start at 12:55. Can you clarify what exactly you mean?

can only choose per 15 min
![only15min](https://user-images.githubusercontent.com/44572433/54704709-96ffa200-4b3b-11e9-9bcd-db78f3d5341f.jpg)

**Comment by Vaalyn** [comment]
Ah okay, my bad. I thought it was already in 5 minute intervals. Thank you for clarifying 👍

**Comment by Vaalyn** [comment]
For the feature request about selecting more granular intervals please follow issue #568

**Comment by stemvantwente** [comment]
> Ah okay, my bad. I thought it was already in 5 minute intervals. Thank you for clarifying 👍

no problem!

**Comment by stemvantwente** [comment]
> For the feature request about selecting more granular intervals please follow issue #568

oke  👍 so hope this option will come in an update :) and again thank you for all the info! still works awesome this azuracast :D

**Comment by stemvantwente** [comment]
@Vaalyn is see that post is 3 days old, I need to update azuracast to I think I dont have the newest version yet, but can do that later tonight otherwise the listeners dont have music :D haha, I come back with what happens when I update azuracast

Greets
Roy

**Comment by stemvantwente** [comment]
@Vaalyn  Have updated to the new version of azuracast, love this option Apply Compression and Normalization!

But if I change a scheduled playlist I still need to restart radio to get the new times the playlist needs to play.
Not really a big problem, just need to plan a little more and restart the server at a late time in the night so listeners dont hear the restart.

Again thank you guys from azuracast for this awesome work!

**Comment by Vaalyn** [comment]
@stemvantwente You are not using the `Advanced Playlists` but normal `Scheduled Playlists` correct?
Then after a full playthrough of a playlist the playlist should be reloaded. Can you check if this is working for you?

**Comment by stemvantwente** [comment]
@Vaalyn Yes I use the normal Scheduled Playlists.

How can I do this best then? I use allot playlist hihi, maybe best way to add a playlist with 2 songs and let say let that play in the middle of the night so it resets if I say play lets say 3 from that playlist?

I'm not really sure how to do this, here is a screenshot of my playlist ( sorry its in dutch)
![live](https://user-images.githubusercontent.com/44572433/54746323-25bbff80-4bcc-11e9-9761-f967e53bb5cb.jpg)

Greets
Roy

**Comment by Vaalyn** [comment]
I'm not 100% sure on how liquidsoap is doing the reloading internally. There are 2 possibilities that I can imagine how it's working.

1. LS reloads only the playlist that it has played through after it has done so
2. LS reloads all playlists after one of them has been played throug

@SlvrEagle23 Do you know which of these is the case?

**Comment by SlvrEagle23** [comment]
@Vaalyn Currently, LS is set to reload playlists on "watch" mode, i.e. any time it detects that changes are written to disk. In some instances, Docker can prevent this watch mode from working correctly, but the only alternative is to set a fixed time period for reloads (which could interfere with shuffled playlists) or to tell it to reload at the end of every playlist (which, in the event of zero-song playlists, causes it to loop infinitely and consume huge resources).

**Comment by Vaalyn** [comment]
@SlvrEagle23 Ah okay, I didn't see that you changed it back from reload to watch. Thanks for the clarification.

**Comment by stemvantwente** [comment]
@Vaalyn @SlvrEagle23 
Thank you both for the info, I just let this be as it is, I let the server restart @ night so that the new input I made are going true.

Greets
Roy

**Comment by stemvantwente** [comment]
> Advanced playlists go directly through Liquidsoap for their playback and need a restart of Liquidsoap to apply changes. See #1269 for more information about this.
> 
> Regarding the question about start times I'm not sure what you mean. You can already say that a scheduled playlist should start at 12:55. Can you clarify what exactly you mean?

@Vaalyn  By the way is this option coming? that I can choose in 5 min steps? if not can I do this with advanced playlist? looked at Liquadsoap but cant really find how to make a line with direct stream url.

Greets
Roy

**Comment by Vaalyn** [comment]
@stemvantwente We have it on our TODO list for playlist enhancements. It will eventually find its way into the codebase.

You can take a look at the generated liquidsoap.liq to see how scheduled playlists are configured and use that as a template for how to to that manually.

Here is an example from one of my stations:
```
radio = fallback(id="brg_playlist_fallback", track_sensitive = false, [dynamic, switch([ ({ 0h0m-5h0m }, playlist_nightdj), ({ true }, radio) ]), blank(duration=2.)])
```

See the ` switch([ ({ 0h0m-5h0m }, playlist_nightdj)` part, there you could say ` switch([ ({ 0h45m-5h0m }, playlist_nightdj)` for example.

**Comment by stemvantwente** [comment]
@Vaalyn Thank you!,  and where can I find this file liquidsoap.liq ? is it in the /var azuracast map?

**Comment by Vaalyn** [comment]
We have a handy Viewer tool where you can take a look at that file from the web interface. Go to `Utilities` -> `Log Viewer` and select the `Liquidsoap Configuration`

**Comment by stemvantwente** [comment]
@Vaalyn aaah of course totally forgot about that haha thank you! I go try it out have a nice weekend

**Comment by freqmand** [comment]
hey @stemvantwente @Vaalyn @SlvrEagle23 

I'm facing the same restart issue in AzuraCast station (Docker installation). 
every time I made a change in my playlists (schedule new one, add tracks..) I need to restart the broadcast. 
is there any update or a better way to do it ? 

thanks.

**Comment by koningcool** [comment]
@freqmand Not at the moment I think, lets hope!
