### ISSUE TITLE
Username on Icecast admin panel

### ISSUE THREAD

**Issue by ButcherZV** [AzuraCast/AzuraCast#1330]
Sorry if im posting this here, but there is no other board or similar for AzuraCast.
I have installed AzuraCast on Ubuntu and i can't login to Icecast admin panel. I see admin password but there is no username. I have tried my account username, root, admin, station name, etc. Is there any default username or how i can set it?

**Comment by Vaalyn** [comment]
The default username for IceCast pages that are secured via http basic auth is `admin`. I'm not sure which IceCast admin panel you are trying to access so I've just tested this with `/admin/listmounts`.

**Comment by ButcherZV** [comment]
For some reason, now it's working. Can you help me with another thing? I can't find location of Azuracast on hard drive? Where is it installed on Ubuntu 16, since i can't find var/azuracast. Also i tried searching entire hard drive and there is no single folder with azuracast name

**Comment by Vaalyn** [comment]
When installing AzuraCast via our recommended installation method, docker, the volumes of the containers are located at `/var/lib/docker/volumes/azuracast_*`. What are you searching for in the directory of AzuraCast?
