### ISSUE TITLE
Multiple stations sharing the same server-side media folder?

### ISSUE THREAD

**Issue by btoplak** [AzuraCast/AzuraCast#1331]
This is not a feature or a bug, but a question hoping to get a best-practice suggestion. So I'll skip all the questions and make it as short and simple as possible.

What would be the best way to share the same media folder to make it available to several stations (to aviod having multiple copies of the files which several of the stations would use)?

Usually I would solve that by making mount bindings in Fstab. But since I am rather new to Docker usage and the current implementation of the AzuraCast's with several instances, I think that approach wouldn't work since the mounts for Dockers are dynamically (?) created on each restart.

Thanks for any suggestions in advance!

**Comment by SlvrEagle23** [comment]
@btoplak We actually have a feature built right into AzuraCast specifically for this!

Once you've created your first station, from the Administration section's "Stations" page, you can click "Clone" next to the station, where you'll have the option to either duplicate the music collection on that station or share the station's media library between both stations.

Under the hood, it just sets an internal variable on both stations (their media directory) to the same folder.
