### ISSUE TITLE
Error installing Azuracast in Ubuntu 18.04 - InfluxDB

### ISSUE THREAD

**Issue by tonimad** [AzuraCast/AzuraCast#1333]
Ubuntu Bare-metal Installation
OS: Ubuntu 18.04 fresh installation.

I follow the steps of the installation:

```
sudo apt-get update
sudo apt-get install -q -y git

sudo mkdir -p /var/azuracast/www
cd /var/azuracast/www
sudo git clone https://github.com/AzuraCast/AzuraCast.git .

sudo chmod a+x install.sh
./install.sh
```

The installation is started correctly until the process reaches this point:

`TASK [influxdb : Add InfluxDB repo key]`

At this point, the installation is permanently waiting and nothing happens.

Any help is appreciated. Thank you so much.

**Comment by tonimad** [comment]
I have found a solution.

An issue when connecting over IPv6 on some servers causes them to get stuck at this point. The fix is really simple.

Open **/etc/gai.conf** in Ubuntu.

Under the line

`# For sites which prefer IPv4 connections change the last line to`

Uncomment the following line by removing the #

`# precedence ::ffff:0:0/96 100`

This will allow you to still use IPv6 but sets IPv4 as the precedence so that **InfluxDB** won’t get stuck.

**Comment by SlvrEagle23** [comment]
@tonimad Excellent find. I will point any issues that seem to be related to this here, as it's probably something I wouldn't incorporate into the official AzuraCast installer (in case it causes problems) but it would be a good possible solution.
