### ISSUE TITLE
Custom song to a playlist (playing a custom song before each song of a playlist)

### ISSUE THREAD

**Issue by 7miguelsilva7** [AzuraCast/AzuraCast#1334]
Is it possible play a custom song before each song of a playlist?

**Comment by Vaalyn** [comment]
Do you want to play a different song before each song or always the same before playing the one from the playlist?

**Comment by 7miguelsilva7** [comment]
Always the same before playing the one from the playlist.

AutoDJ sample:
**custom song** from playlist 1
a song from playlist 1

**custom song** from playlist 2
a song from playlist 2

a song playlist 3
other song from playlist 3

a song playlist 4
other song from playlist 4

**custom song** from playlist 1
an other song from playlist 1

**custom song** from playlist 2
an other song from playlist 2

Custom song (the same song in the playlist) like a headpiece for a playlist, and have always to play before for each song from the playlist
it is to identify the caracteritics of a playlist

Sorry my english, rsrs
Hope it is clear!

**Comment by Vaalyn** [comment]
I don't think that this is currently possible with the standard playlists. You may be able to do this with [Advanced Playlists](https://github.com/AzuraCast/azuracast.com/blob/master/AdvancedPlaylists.md).
