### ISSUE TITLE
Custom Fade Times Ignored

### ISSUE THREAD

**Issue by paulbonass** [AzuraCast/AzuraCast#1337]
In the latest build the custom fade times set individually on audio files are ignored.

In previous builds I've set everything in the 'jingles' folder a custom fade time of 0 in and 0 out. This ensures that the jingle always plays at full volume from start to finish, but the overlap of 1 second remains.

Song > Full Volume Jingle > Song

In the latest docker build the fade times seem to be ignored in favor of the system default. I've tried all three different modes (Normal, Smart, Off) and with Manual DJ on and off - but still no luck.

**Comment by SlvrEagle23** [comment]
@paulbonass This is a valid issue while I work with the Liquidsoap creators on a better way of handling "jingle mode" than resetting metadata on AzuraCast's end. I will keep this open and update you accordingly.

**Comment by paulbonass** [comment]
If I disable jingle mode should it work as before?

**Comment by paulbonass** [comment]
Just wondering if this was ever resolved?

**Comment by SlvrEagle23** [comment]
@paulbonass This should be resolved, but if it's not, feel free to reopen this issue. The stale bot closed it as having not had any response for a while.
