### ISSUE TITLE
Liquidsoap customization in Advanced Custom section

### ISSUE THREAD

**Issue by tonimad** [AzuraCast/AzuraCast#1339]
I am trying to customize the LiquidSoap config. file via the profile > Advanced Custom Configuration. Specifically, I want to set my own bitrate values.

I want to set the availability of the following bitrate values, only: 48kbps, 64kbps, 128 kbps.

This is possible? What code should I add in this section?

Thanks!

**Comment by SlvrEagle23** [comment]
@tonimad Do you mean you want listeners to be able to connect to 48/64/128kbps streams? That would be configurable via the Mount Points section of the web panel.
