### ISSUE TITLE
Can not connect to the stream domain

### ISSUE THREAD

**Issue by Rootinator** [AzuraCast/AzuraCast#1340]
Hello,
if I enter a stream domain in "Remote Relay", Azuracast can not connect to the stream server.

If I enter the IP instead, a connection is established.

So the domain is not resolved. How can you fix this?

I am using "Ubuntu Server 18.04.2 LTS"

Log:
`Connecting mount /stream for user@stream.domain.tld...`
`Connection failed: Failure("inet_addr_of_string")`

**Comment by Vaalyn** [comment]
This issue is already tracked in #1303 please follow that issue for any updates relating to this problem.
