### ISSUE TITLE
net::err_connection_closed player public

### ISSUE THREAD

**Issue by j2sdwebradio** [AzuraCast/AzuraCast#1342]
**Installation method**
Bare-metal" installation method

**Host OS (for Docker installations)**
Ubuntu 16.04 

**Describe the bug**
the public player page generates an error net::ERR_CONNECTION_CLOSED in the console and the play function does not work

**To Reproduce**
1. Go to public page
2. Click on play

**Comment by Vaalyn** [comment]
I'm assuming that the radio on the website that's linked in your GitHub profile is the AzuraCast installation that is giving you that error. I had a quick look at what I could see from the outside and this is what the `/api/stations` endpoint returns as listen URL: `https://azurcast.kipaza.fr/radio/8000/j2sd.mp3?1553551158` and this is what the website is trying to connect to: `https://azurcast.kipaza.fr:8000/j2sd.mp3?1553551096`.

It seems like the embed widget is using an incorrect stream URL here. I couldn't replicate this error with the demo installation. Is there anything that you customized on your installation or anything that you changed before this started to happen?

**Comment by j2sdwebradio** [comment]
Hello yes url of the server is well azurcast.kipaza.fr/
 I do not change custom url I do not understand this change of address
best regard.

**Comment by j2sdwebradio** [comment]
Hello,
I updated this morning my instance Azuracast always the same worries.
best regard.

**Comment by SlvrEagle23** [comment]
@j2sdwebradio It appears you are behind a proxy service like CloudFlare or something else that is preventing direct access to the 8xxx ports used by the radio software.

There is a setting you can turn on in the System Settings called "Use Web Proxy for Radio" that should help resolve this issue.

**Comment by j2sdwebradio** [comment]
Thanks it works again
