### ISSUE TITLE
Server without stats.xls or other

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#1343]
The statics are already deactiveted.
There is no icecast Server, only a icecast compactible Server without any icecast releated files.
After i started the streaming, azuracast only shows "Stream Offline"
But i can listen the Azuracast Jingle in the Stream.

I really wish a feature to use Servers like this, not icecast but icecast compactible.

**Comment by SlvrEagle23** [comment]
@preterive The way we retrieve the metadata about what's playing from the remote server (and, likewise, who's listening to the station) depends on a very specific set of files to be present. We're already rather flexible about those files in Icecast's case; we can consume either the XML-based internal statistics page that the software provides, or if the remote server is new enough, we can consume the `status-json.xsl` file that's exposed publicly.

I don't know in this case what constitutes "Icecast Compatible", but if it doesn't include providing those same files, then there's not much we can do to build it into our universal Now Playing support.

Anything else would likely be the domain of a custom plugin. Pulling Now Playing data is already an event-driven function that can be overridden by plugins, so this should be quite possible.
