### ISSUE TITLE
Immediate Playlists?

### ISSUE THREAD

**Issue by adwinter** [AzuraCast/AzuraCast#1344]
Wondering if someone could answer a question for me... Back before I discovered and implemented Azuracast I was using a commercial package that had a feature that allowed for a playlist to play immediately if it was active and there was at least one entry in it.

If I remember right, you could set the playlist to "Immediate", and then whatever got dropped in there would play right after the currently playing track. Usually running through that playlist to the end, disabling it, then going back to whatever the rotations were.

Is there any setting similar to this in Azuracast? It was a great way to inject the stream with songs without scheduling them through a "shuffled" rotation system. And it was read multiple times and live.. so you could drop a song in while it was playing, and it would pick it up and play it because list was dynamically loaded.

Anyway, any guidance would be awesome. Thanks for your time.

Andrew

**Comment by SlvrEagle23** [comment]
@adwinter We actually have an existing enhancement request to add something very similar to this, #230. We wouldn't be setting up a new playlist, but actually using the existing requests pipeline to just immediately queue the song as if it had been requested by an external user and passed all the necessary "wait time" thresholds immediately.

**Comment by adwinter** [comment]
Right! That makes perfect sense -- I'm already using the requests pipeline, so I should of thought of that!
Sorry for the duplicate. I'll close this question in favor of the existing enhancement request.
 
Thanks so much @SlvrEagle23 for answering my questions. Azuracast continues to impress me and I'm happy to donate what I was paying for a commercial product to your development. (its not much, but I hope it helps).
