### ISSUE TITLE
Cannot access media directory - Docker

### ISSUE THREAD

**Issue by afonsosantos** [AzuraCast/AzuraCast#1345]
**Installation method**
Docker

**Host OS (for Docker installations)**
CentOS 7 - 32 bits

**Problem**
I need to format the machine that hosts this AzuraCast instance, but I can't seem to find the **media** directory in order to copy my music files. The directory provided in the main page of the web interface doesn't exist.

**Screenshots**
![DSCN0021](https://user-images.githubusercontent.com/46262740/55023528-e1c66180-4ff4-11e9-8f19-b9c1c26d09c3.JPG)

**Comment by SlvrEagle23** [comment]
@afonsosantos By default, at least on Ubuntu installations, the Docker volumes are located at `/var/lib/docker/volumes`.

**Comment by Vaalyn** [comment]
For the media files directory look at `/var/lib/docker/volumes/azuracast_station_data/_data/<station_name>/media`

**Comment by afonsosantos** [comment]
Thanks for your help, but I already managed to copy my media files. I'm now installing AzuraCast on Debian 9, but an error message appears when installind docker-ce:
![image](https://user-images.githubusercontent.com/46262740/55086787-e8aaae00-50a0-11e9-9e37-490b3174e5f1.png)
