### ISSUE TITLE
Playlist being played too much

### ISSUE THREAD

**Issue by JDBlackman** [AzuraCast/AzuraCast#1346]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 18.04

**Describe the bug**
A Playlist is being overplayed despite the weight. I am not using automated assignment.

**Expected behavior**
This is the current setup of my playlists
![image](https://user-images.githubusercontent.com/22846433/55046568-5d023480-5042-11e9-844a-36bdac691735.png)

My aim was to have Throwbacks played maybe once in 6-7 songs.  However I seem to be getting the lower weighted playlist more often. 

**Screenshots**
![image](https://user-images.githubusercontent.com/22846433/55046679-ad799200-5042-11e9-9ef9-c1dc22e4c24d.png)

![image](https://user-images.githubusercontent.com/22846433/55046697-bf5b3500-5042-11e9-9a40-c66571bf83b0.png)

![image](https://user-images.githubusercontent.com/22846433/55046768-ec0f4c80-5042-11e9-809f-0ae0ff3ddfde.png)

I'm not sure if this is an issue with my weightings or if this can be helped at all and its just the "luck". 

EDIT:
Upon reviewing the screenshots it seems to also play the same artist in those blocks, however i think this is unrelated as discussed in previous issue

**Comment by SlvrEagle23** [comment]
@JDBlackman Is this as of the very latest update from today or from a few days ago?

**Comment by JDBlackman** [comment]
I'm currently on 0v0.9.3, #0bb68f7.  I will update and monitor if it still happens. Thanks :) <3
