### ISSUE TITLE
How to use the remote URL playlist

### ISSUE THREAD

**Issue by Ficreet** [AzuraCast/AzuraCast#1348]
Hello,

I would like to know how the Remote URL Playlist works, because despite my research and my various tests I can't get it to work

Thank you in advance for your answers because I am sure that this one will help other people

**Comment by JacobSyndeo** [comment]
+1

**Comment by SlvrEagle23** [comment]
@Ficreet The remote URL playlists are meant to pull their contents from an off-server HTTP URL, and can be in one of two formats:

 - A single audio stream that should be relayed by the AutoDJ, i.e. another radio station's broadcast; or
 - A remote PLS/M3U playlist file that contains several song URIs that should play as though they're a regular local playlist.

The way the system handles either of these cases is different, so you're given the option to select which type of remote URL you're using after you've selected that the playlist is a remote one.

**Comment by Vaalyn** [comment]
@Ficreet Maybe you encountered the same issue with the remote playlists as in issue #1430. Can you try updating to the newest version and check if it works now?
