### ISSUE TITLE
music fading

### ISSUE THREAD

**Issue by stemvantwente** [AzuraCast/AzuraCast#1349]
Hello

I have a problem with scheduled play, I use Bare-metal Installation.

When the scheduled playlist kicks in, it's all good, it streams then a remote url playlist, a direct stream url. This works good but the problem comes after a few minutes, the music then is fading, only thing to do what makes the music play normal again is when I say restart broadcast. And then it just plays fine till the schedule end time.

I made a record so you can hear what I mean with fading. After 30 seconds the broadcast restart comes in and you hear the music play normal again.
[azuracast music lag.zip](https://github.com/AzuraCast/AzuraCast/files/3014668/azuracast.music.lag.zip)

Hope you guys can tell me what this can cause.

Greets
Roy

**Comment by CodeSteele** [comment]
As per #1359, have you tried adjusting your buffer?

**Comment by stemvantwente** [comment]
Mmmm liquadsoap says now 2019/03/28 17:47:54 [http_6434:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!

But where can I increase this buffer?

**Comment by Vaalyn** [comment]
@stemvantwente Currently we have no direct option for increasing this buffer size. You can follow issue #940 for that. There is an issue linked from the Liquidsoap repo where the maintainer explains the error as follows:

> Buffer overrun logs usually happen when the `input.http` source receives too much data. This can have several reasons, such as the sender sending data at a rate above real-time or by bursts, or the two machines having clocks that are slightly out of sync.
> 
> One way to mitigate the issue is to raise the `max` buffer in `input.http`

I'm not sure if it is possible to set this via the advanced Liquidsoap configuration though. @SlvrEagle23 do you think this is possible or is this something that has to be set earlier in the config?

@stemvantwente Is the issue with the audio fading resolved after increasing the `DJ/Streamer Buffer Time`?

**Comment by stemvantwente** [comment]
@Vaalyn No still fading :( have it on 15 now, after 2 restarts the music plays good strange but true, no changes and Liquadsoap keeps saying Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!

**Comment by SlvrEagle23** [comment]
@stemvantwente Yeah, that's a different buffer. Currently it's not configurable from within AzuraCast, but given these issues it probably should be.

**Comment by stemvantwente** [comment]
> @stemvantwente Yeah, that's a different buffer. Currently it's not configurable from within AzuraCast, but given these issues it probably should be.

Thank you for the reply @SlvrEagle23, hope to see this option soon :) but dont reallly get it when its starts play its fine and at start of play liquadsoap starts the error Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size! but music is fine, after few minutes its goes to this fading maybe it consumes allot memory because off the error keeps running all the time and makes this buffer? not sure just a tought because look at the seconds multiple errors in 1 second

2019/03/28 20:25:27 [http_6434:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/03/28 20:25:27 [http_6434:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/03/28 20:25:27 [http_6434:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/03/28 20:25:27 [http_6439:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/03/28 20:25:27 [http_6439:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/03/28 20:25:27 [http_6439:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/03/28 20:25:27 [http_6439:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/03/28 20:25:27 [http_6439:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/03/28 20:25:27 [http_6439:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/03/28 20:25:27 [http_6439:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/03/28 20:25:28 [http_6434:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/03/28 20:25:28 [http_6434:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/03/28 20:25:28 [http_6434:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!

**Comment by SlvrEagle23** [comment]
@stemvantwente As of the latest update, the buffer for remote playlist playback is now configurable on a per-playlist basis. The default is 20 seconds, but if that's not working well I would recommend increasing it until you reach a stable point.

**Comment by stemvantwente** [comment]
@SlvrEagle23 still fading :( I have now done something else to test, I made an Mount point in Azuracast, I relay the stream there and putted the local azuracast ip now in the schedule, playing now for 10 min good no fading! so let's hope this solve the problem.

I checked liquadsoap few hours back and I see all the stations I use playlist with remote url even if the normal playlist are playing liquadsoap keeps spamming
 2019/04/01 18:18:54 [http_6478:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/04/01 18:18:54 [http_6478:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/04/01 18:18:54 [http_6478:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!

One station I use does not have remote url and there I just see normal liquadsoap stuff as in song end new loaded etc.

**Comment by stemvantwente** [comment]
Here another recording, no idea why its buffering this crazy, you can hear when I click restart broadcast then the music is fine.
[bufferstill.zip](https://github.com/AzuraCast/AzuraCast/files/3034862/bufferstill.zip)

**Comment by stemvantwente** [comment]
@SlvrEagle23 Update, can this fading come that there is allot of metadata pushing true when the broadcast starts, allot jingles, commercials etc just a tought.

Greets
Roy

**Comment by stemvantwente** [comment]
@SlvrEagle23 mmmm I putted Advanced Remote Playback Buffer (Seconds) to 60 now and now the Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size! stopped!

No idea why I need to put it so high.

So I hope it is fixet now, can let you know tommorow when the scheduler kicks in again arround 17:45

**Comment by stemvantwente** [comment]
This what happens when I restart now, have Advanced remote playback buffer on 80 now

2019/04/03 00:41:49 [main:3] Shutdown started!
2019/04/03 00:41:49 [main:3] Waiting for threads to terminate...
2019/04/03 00:41:49 [threads:3] Shuting down thread http polling
2019/04/03 00:41:49 [piratenradio_local_2:3] Closing connection...
2019/04/03 00:41:49 [piratenradio_local_1:3] Closing connection...
2019/04/03 00:41:49 [playlist_duitsenengels:3] Finished with "/var/azuracast/stations/piratenradio/media/Duits/Eddie Freytag - An Meiner Seite.mp3".
2019/04/03 00:41:49 [http_6478:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/04/03 00:41:49 [http_6478:2] Feeding stopped: source stopped
2019/04/03 00:41:49 [http_6468:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/04/03 00:41:49 [http_6468:2] Feeding stopped: source stopped
2019/04/03 00:41:49 [threads:3] Thread "http polling" terminated (3 remaining).
2019/04/03 00:41:49 [threads:3] Shuting down thread http polling
2019/04/03 00:41:49 [http_6473:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/04/03 00:41:49 [http_6473:2] Feeding stopped: source stopped
2019/04/03 00:41:49 [threads:3] Thread "http polling" terminated (2 remaining).
2019/04/03 00:41:49 [threads:3] Shuting down thread http polling
2019/04/03 00:41:49 [threads:3] Thread "http polling" terminated (1 remaining).
2019/04/03 00:41:49 [threads:3] Shuting down thread wallclock_main
2019/04/03 00:41:49 [piratenradio_next_song:3] Finished with "/var/azuracast/stations/piratenradio/media/Nederlands/Les Ducs - Sofietje.mp3".
2019/04/03 00:41:49 [clock.wallclock_main:3] Streaming loop stopped.
2019/04/03 00:41:49 [threads:3] Thread "wallclock_main" terminated (0 remaining).
2019/04/03 00:41:49 [main:3] Threads terminated.
2019/04/03 00:41:49 [threads:3] Shutting down scheduler...
2019/04/03 00:41:49 [threads:3] Scheduler shut down.
2019/04/03 00:41:49 [threads:3] Shutting down queues...
2019/04/03 00:41:49 [threads:3] Thread "non-blocking queue #2" terminated.
2019/04/03 00:41:49 [threads:3] Thread "generic queue #2" terminated.
2019/04/03 00:41:49 [threads:3] Thread "non-blocking queue #1" terminated.
2019/04/03 00:41:49 [threads:3] Thread "generic queue #1" terminated.
2019/04/03 00:41:49 [threads:3] Queues shut down
2019/04/03 00:41:49 [server:3] Closing socket.
2019/04/03 00:41:49 [main:3] Cleaning downloaded files...
2019/04/03 00:41:49 [main:3] Freeing memory...
2019/04/03 00:41:50 >>> LOG START
2019/04/03 00:41:49 [main:3] Liquidsoap 1.3.6
2019/04/03 00:41:49 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 taglib=0.3.3 ssl=0.5.7 camomile=1.0.1 faad=0.4.0
2019/04/03 00:41:50 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/04/03 00:41:50 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/04/03 00:41:50 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/04/03 00:41:50 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/04/03 00:41:50 [decoder:3] Method "MAD" accepted "/var/azuracast/www/resources/error.mp3".
2019/04/03 00:41:50 [threads:3] Created thread "generic queue #1".
2019/04/03 00:41:50 [threads:3] Created thread "generic queue #2".
2019/04/03 00:41:50 [threads:3] Created thread "non-blocking queue #1".
2019/04/03 00:41:50 [threads:3] Created thread "non-blocking queue #2".
2019/04/03 00:41:50 [harbor:3] Adding mountpoint '/' on port 8005
2019/04/03 00:41:50 [threads:3] Created thread "http polling" (1 total).
2019/04/03 00:41:50 [threads:3] Created thread "http polling" (2 total).
2019/04/03 00:41:50 [threads:3] Created thread "http polling" (3 total).
2019/04/03 00:41:50 [playlist_polka:3] Loading playlist...
2019/04/03 00:41:50 [playlist_polka:3] No mime type specified, trying autodetection.
2019/04/03 00:41:50 [playlist_polka:3] Playlist treated as format application/x-mpegURL
2019/04/03 00:41:50 [playlist_polka:3] Successfully loaded a playlist of 168 tracks.
2019/04/03 00:41:50 [playlist_jingles:3] Loading playlist...
2019/04/03 00:41:50 [playlist_jingles:3] No mime type specified, trying autodetection.
2019/04/03 00:41:50 [playlist_jingles:3] Playlist treated as format application/x-mpegURL
2019/04/03 00:41:50 [playlist_jingles:3] Successfully loaded a playlist of 4 tracks.
2019/04/03 00:41:50 [playlist_duitsenengels:3] Loading playlist...
2019/04/03 00:41:50 [playlist_duitsenengels:3] No mime type specified, trying autodetection.
2019/04/03 00:41:50 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/piratenradio/media/Polka/The Dick Tady Orchestra - Cjues Mala En Kad Se Cigan Zazeli.mp3".
2019/04/03 00:41:50 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/piratenradio/media/Jingels/Jingle - Hit na hit na hit.mp3".
2019/04/03 00:41:50 [playlist_duitsenengels:3] Playlist treated as format application/x-mpegURL
2019/04/03 00:41:50 [playlist_duitsenengels:3] Successfully loaded a playlist of 1127 tracks.
2019/04/03 00:41:50 [playlist_nederlands:3] Loading playlist...
2019/04/03 00:41:50 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/piratenradio/media/Duits/Philomena Boys - Vorbei.mp3".
2019/04/03 00:41:50 [playlist_nederlands:3] No mime type specified, trying autodetection.
2019/04/03 00:41:50 [playlist_nederlands:3] Playlist treated as format application/x-mpegURL
2019/04/03 00:41:50 [playlist_nederlands:3] Successfully loaded a playlist of 1690 tracks.
2019/04/03 00:41:50 [single_6494:3] "/var/azuracast/www/resources/error.mp3" is static, resolving once for all...
2019/04/03 00:41:50 [playlist_polka:3] Prepared "/var/azuracast/stations/piratenradio/media/Polka/The Dick Tady Orchestra - Cjues Mala En Kad Se Cigan Zazeli.mp3" (RID 2).
2019/04/03 00:41:50 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/piratenradio/media/Nederlands/Hanny - Ga met me mee.mp3".
2019/04/03 00:41:50 [decoder:3] Method "MAD" accepted "audio/mpeg".
2019/04/03 00:41:50 [http_6468:3] Decoding...
2019/04/03 00:41:50 [http_6468:3] New metadata chunk: ? -- .
2019/04/03 00:41:50 [decoder:3] Method "MAD" accepted "audio/mpeg".
2019/04/03 00:41:50 [http_6478:3] Decoding...
2019/04/03 00:41:50 [http_6478:3] New metadata chunk: ? -- .
2019/04/03 00:41:50 [decoder:3] Method "MAD" accepted "audio/mpeg".
2019/04/03 00:41:50 [http_6473:3] Decoding...
2019/04/03 00:41:50 [http_6473:3] New metadata chunk: ? -- .
2019/04/03 00:41:50 [piratenradio_local_1:3] Connecting mount /jukeboxazura for source@127.0.0.1...
2019/04/03 00:41:50 [http_6473:3] New metadata chunk: ? -- Tribute To The Cats Band - Walking In The Rain.
2019/04/03 00:41:50 [http_6478:3] New metadata chunk: ? -- Tribute To The Cats Band - Walking In The Rain.
2019/04/03 00:41:50 [http_6468:3] New metadata chunk: ? -- Tribute To The Cats Band - Walking In The Rain.
2019/04/03 00:41:50 [lang:3] AzuraCast Raw Response: annotate:title="Zij weet van niks",artist="Cees and his Skyliners",duration="174.",song_id="af91126f184a7bd48c62f29bc3def140",media_id="1358",genre="1358",playlist_id="2":/var/azuracast/stations/piratenradio/media/Nederlands/Cees and his Skyliners - Zij weet van niks.mp3
2019/04/03 00:41:50 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/piratenradio/media/Nederlands/Cees and his Skyliners - Zij weet van niks.mp3".
2019/04/03 00:41:50 [piratenradio_local_1:3] Connection setup was successful.
2019/04/03 00:41:50 [piratenradio_local_2:3] Connecting mount /jukeboxazuraaac for source@127.0.0.1...
2019/04/03 00:41:50 [piratenradio_local_2:3] Connection setup was successful.
2019/04/03 00:41:50 [threads:3] Created thread "wallclock_main" (4 total).
2019/04/03 00:41:50 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2019/04/03 00:41:50 [piratenradio_live_switch:3] Switch to switch_6512.
2019/04/03 00:41:50 [switch_6512:3] Switch to fallback_6510.
2019/04/03 00:41:50 [fallback_6510:3] Switch to delay_6508.
2019/04/03 00:41:50 [dummy:3] Source failed (no more tracks) stopping output...
2019/04/03 00:41:50 [lang:3] AzuraCast Feedback Response: OK

2019/04/03 00:42:59 [http_6478:3] Buffer overrun: Dropping 0.01s. Consider increasing the max buffer size!
2019/04/03 00:42:59 [http_6478:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/04/03 00:42:59 [http_6468:3] Buffer overrun: Dropping 0.01s. Consider increasing the max buffer size!
2019/04/03 00:42:59 [http_6468:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/04/03 00:42:59 [http_6468:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/04/03 00:42:59 [http_6468:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/04/03 00:42:59 [http_6468:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/04/03 00:42:59 [http_6468:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/04/03 00:42:59 [http_6468:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/04/03 00:42:59 [http_6478:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/04/03 00:42:59 [http_6473:3] Buffer overrun: Dropping 0.01s. Consider increasing the max buffer size!
2019/04/03 00:42:59 [http_6468:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/04/03 00:42:59 [http_6473:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/04/03 00:42:59 [http_6468:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/04/03 00:42:59 [http_6478:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2019/04/03 00:42:59 [http_6473:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!

Maybe you can see something wrong?

Greets
Roy

**Comment by stemvantwente** [comment]
Hello

This worked for me, using advanced playlist. all Buffer overrun messages disappear.

radio = switch(track_sensitive=false, [ ({ (1w or 2w or 3w or 4w) and 17h59m-22h0m }, playlist_deltalivematotdon), ({ (5w) and 17h59m-0h0m }, playlist_deltalivevrijdag), ({ (6w) and 12h59m-18h0m }, playlist_deltalivezaterdag), ({true}, radio) ])
output.dummy(fallible=true, playlist_deltalivematotdon)
output.dummy(fallible=true, playlist_deltalivevrijdag)
output.dummy(fallible=true, playlist_deltalivezaterdag)

Used a clean install now on Ubuntu 18.04, one problem transitions=[simple_crossfade] worked on my old 16.04 installation but not liquadsoap gives error 
At line 106, char 68: the variable simple_crossfade used here has not been
  previously defined.

**Comment by lramilo** [comment]
When playing a remote URL playlist, I found a workaround using a dummy output, manually adding this to Liquidsoap configuration:

`output.dummy(id="DUMMY_STREAM_OUTPUT", fallible=true, playlist_live)`

Details are explained on [#3701](https://github.com/AzuraCast/AzuraCast/issues/3701)
