### ISSUE TITLE
Bug // restart radio

### ISSUE THREAD

**Issue by jimpy51** [AzuraCast/AzuraCast#135]
Hello,

When i active a some playlist (exept a standard playlist) (for example a jingle playlist/each x songs)..

If i restart my radio, i have an error : 

```
0	At line 48, character 18: The variable playlist_jingles defined here
1	is not used anywhere in its scope. Use ignore(...) instead of
2	playlist_jingles = ... if you meant to not use it. Otherwise,
3	this may be a typo or a sign that your script does not do what you intend.
```

Liquidsoap don't want restart because the playlist is declared in the .liq but not used after....

Regards,

**Comment by rolradio** [comment]
Afther the udate ist running fine now.
Thank you.
