### ISSUE TITLE
Cant't log in after update

### ISSUE THREAD

**Issue by Zellouser** [AzuraCast/AzuraCast#1350]
After the update from v0.9.3, # 2c2d90c (2019-03-17 8:31) to v0.9.4, there is no login to the azucast page.

Host OS: Ubuntu 18.04.2 LTS
Docker installation

![azuracast1](https://user-images.githubusercontent.com/48444758/55103195-4dc5ca00-50c8-11e9-897a-97675a222be7.PNG)
![azuracast2](https://user-images.githubusercontent.com/48444758/55103196-4dc5ca00-50c8-11e9-99bd-ea3e2b94b0b1.PNG)
![azuracast3](https://user-images.githubusercontent.com/48444758/55103197-4e5e6080-50c8-11e9-8ec9-dd0ac4384a79.PNG)
![azuracast4](https://user-images.githubusercontent.com/48444758/55103200-4e5e6080-50c8-11e9-95a6-b9a4cd2d71a7.PNG)

![azuracast5](https://user-images.githubusercontent.com/48444758/55103201-4e5e6080-50c8-11e9-9f96-17d900813fcc.PNG)

Can you help me?

Greetings from Germany

**Comment by SlvrEagle23** [comment]
@Zellouser This should be fixed as of the latest rolling update. If you don't mind updating your installation, it should apply the necessary fix.

**Comment by Zellouser** [comment]
everything is going well now.
Many Thanks
