### ISSUE TITLE
Set duration of each song globally 

### ISSUE THREAD

**Issue by chourmovs** [AzuraCast/AzuraCast#1351]
**Is your feature request related to a problem? Please describe.**
It would be very appreciable to have the ability to set the duration of each song globally in order to provide more dynamical mix in DJ style

**Describe the solution you'd like**
If i set duration of 1mn 30 sec, track will be seeked after that time laps

**Describe alternatives you've considered**
I've Tried to play around liquidsoap advanced configuration without success.

**Additional context**
Sorry for my bad english

**Comment by SlvrEagle23** [comment]
@chourmovs Do you mean you want to be able to set that _all songs_ should be the same length? I wouldn't imagine that to be a very common scenario for radio stations...

**Comment by chourmovs** [comment]
@SlvrEagle23 , I would add more granularity but yes it's the main purpose.
Like Franck Black from the pixies said, " a song should never length more than 1 minute and a half", and more seriously, with cross-fader ability, jingle now working, we're able to turn our station in 24/24 live automated DJ mix. For urban music mixes, you would notice that individual track never length longer than 60 -90 seconds  
Regarding granularity, ideal situation would be a duration bracket (1 - 2) minutes with a random set

Of course We could use per track duration but I've 2000 sound in my database ^!^

**Comment by chourmovs** [comment]
@SlvrEagle23 do you have any starting point for my problem ?
Thank you

**Comment by SlvrEagle23** [comment]
@chourmovs This is not a priority for me to work on, as it doesn't seem that multiple users are trying to do this.

**Comment by chourmovs** [comment]
@SlvrEagle23 I fully understand but i just asked for some general advise that could help me to help you on this topic
I was thinking about  liquidsoap "cueout" or something around liquidsoap advanced playlist script 
Maybe you could share some interesting reading or links regarding liquidsoap, I've difficulties to follow the official documentation that look slightly obscure to me.
