### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by kokoloman001** [AzuraCast/AzuraCast#1352]
An update caused an error.

This is an error that has occurred.
`TASK [composer : Install Composer Dependencies (Production)] *******************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "composer install --no-d                                                                                                             ev", "delta": "0:00:00.150306", "end": "2019-03-28 02:21:51.320346", "msg": "non                                                                                                             -zero return code", "rc": 2, "start": "2019-03-28 02:21:51.170040", "stderr": "L                                                                                                             oading composer repositories with package information\nInstalling dependencies f                                                                                                             rom lock file\nYour requirements could not be resolved to an installable set of                                                                                                              packages.\n\n  Problem 1\n    - The requested PHP extension ext-gd * is missing                                                                                                              from your system. Install or enable PHP's gd extension.\n  Problem 2\n    - The                                                                                                              requested PHP extension ext-intl * is missing from your system. Install or enabl                                                                                                             e PHP's intl extension.\n  Problem 3\n    - The requested PHP extension ext-simp                                                                                                             lexml * is missing from your system. Install or enable PHP's simplexml extension                                                                                                             .\n  Problem 4\n    - The requested PHP extension ext-xml * is missing from your                                                                                                              system. Install or enable PHP's xml extension.\n  Problem 5\n    - The requeste                                                                                                             d PHP extension ext-xmlwriter * is missing from your system. Install or enable P                                                                                                             HP's xmlwriter extension.\n  Problem 6\n    - Installation request for sentry/se                                                                                                             ntry 2.0.1 -> satisfiable by sentry/sentry[2.0.1].\n    - sentry/sentry 2.0.1 re                                                                                                             quires ext-mbstring * -> the requested PHP extension mbstring is missing from yo                                                                                                             ur system.\n  Problem 7\n    - aws/aws-sdk-php 3.87.22 requires ext-simplexml *                                                                                                              -> the requested PHP extension simplexml is missing from your system.\n    - aws                                                                                                             /aws-sdk-php 3.87.22 requires ext-simplexml * -> the requested PHP extension sim                                                                                                             plexml is missing from your system.\n    - Installation request for aws/aws-sdk-                                                                                                             php 3.87.22 -> satisfiable by aws/aws-sdk-php[3.87.22].\n\n  To enable extension                                                                                                             s, verify that they are enabled in your .ini files:\n    - /etc/php/7.3/cli/php.                                                                                                             ini\n    - /etc/php/7.3/cli/conf.d/10-opcache.ini\n    - /etc/php/7.3/cli/conf.d                                                                                                             /10-pdo.ini\n    - /etc/php/7.3/cli/conf.d/20-bz2.ini\n    - /etc/php/7.3/cli/co                                                                                                             nf.d/20-calendar.ini\n    - /etc/php/7.3/cli/conf.d/20-ctype.ini\n    - /etc/php                                                                                                             /7.3/cli/conf.d/20-exif.ini\n    - /etc/php/7.3/cli/conf.d/20-fileinfo.ini\n                                                                                                                 - /etc/php/7.3/cli/conf.d/20-ftp.ini\n    - /etc/php/7.3/cli/conf.d/20-gettext.i                                                                                                             ni\n    - /etc/php/7.3/cli/conf.d/20-iconv.ini\n    - /etc/php/7.3/cli/conf.d/20                                                                                                             -igbinary.ini\n    - /etc/php/7.3/cli/conf.d/20-json.ini\n    - /etc/php/7.3/cli                                                                                                             /conf.d/20-phar.ini\n    - /etc/php/7.3/cli/conf.d/20-posix.ini\n    - /etc/php/                                                                                                             7.3/cli/conf.d/20-readline.ini\n    - /etc/php/7.3/cli/conf.d/20-redis.ini\n                                                                                                                 - /etc/php/7.3/cli/conf.d/20-shmop.ini\n    - /etc/php/7.3/cli/conf.d/20-sockets                                                                                                             .ini\n    - /etc/php/7.3/cli/conf.d/20-sysvmsg.ini\n    - /etc/php/7.3/cli/conf.                                                                                                             d/20-sysvsem.ini\n    - /etc/php/7.3/cli/conf.d/20-sysvshm.ini\n    - /etc/php/7                                                                                                             .3/cli/conf.d/20-tokenizer.ini\n  You can also run `php --ini` inside terminal t                                                                                                             o see which files are used by PHP in CLI mode.", "stderr_lines": ["Loading compo                                                                                                             ser repositories with package information", "Installing dependencies from lock f                                                                                                             ile", "Your requirements could not be resolved to an installable set of packages                                                                                                             .", "", "  Problem 1", "    - The requested PHP extension ext-gd * is missing fr                                                                                                             om your system. Install or enable PHP's gd extension.", "  Problem 2", "    - Th                                                                                                             e requested PHP extension ext-intl * is missing from your system. Install or ena                                                                                                             ble PHP's intl extension.", "  Problem 3", "    - The requested PHP extension ex                                                                                                             t-simplexml * is missing from your system. Install or enable PHP's simplexml ext                                                                                                             ension.", "  Problem 4", "    - The requested PHP extension ext-xml * is missing                                                                                                              from your system. Install or enable PHP's xml extension.", "  Problem 5", "                                                                                                                 - The requested PHP extension ext-xmlwriter * is missing from your system. Insta                                                                                                             ll or enable PHP's xmlwriter extension.", "  Problem 6", "    - Installation req                                                                                                             uest for sentry/sentry 2.0.1 -> satisfiable by sentry/sentry[2.0.1].", "    - se                                                                                                             ntry/sentry 2.0.1 requires ext-mbstring * -> the requested PHP extension mbstrin                                                                                                             g is missing from your system.", "  Problem 7", "    - aws/aws-sdk-php 3.87.22 r                                                                                                             equires ext-simplexml * -> the requested PHP extension simplexml is missing from                                                                                                              your system.", "    - aws/aws-sdk-php 3.87.22 requires ext-simplexml * -> the r                                                                                                             equested PHP extension simplexml is missing from your system.", "    - Installat                                                                                                             ion request for aws/aws-sdk-php 3.87.22 -> satisfiable by aws/aws-sdk-php[3.87.2                                                                                                             2].", "", "  To enable extensions, verify that they are enabled in your .ini fil                                                                                                             es:", "    - /etc/php/7.3/cli/php.ini", "    - /etc/php/7.3/cli/conf.d/10-opcach                                                                                                             e.ini", "    - /etc/php/7.3/cli/conf.d/10-pdo.ini", "    - /etc/php/7.3/cli/conf                                                                                                             .d/20-bz2.ini", "    - /etc/php/7.3/cli/conf.d/20-calendar.ini", "    - /etc/php                                                                                                             /7.3/cli/conf.d/20-ctype.ini", "    - /etc/php/7.3/cli/conf.d/20-exif.ini", "                                                                                                                 - /etc/php/7.3/cli/conf.d/20-fileinfo.ini", "    - /etc/php/7.3/cli/conf.d/20-f                                                                                                             tp.ini", "    - /etc/php/7.3/cli/conf.d/20-gettext.ini", "    - /etc/php/7.3/cli                                                                                                             /conf.d/20-iconv.ini", "    - /etc/php/7.3/cli/conf.d/20-igbinary.ini", "    - /                                                                                                             etc/php/7.3/cli/conf.d/20-json.ini", "    - /etc/php/7.3/cli/conf.d/20-phar.ini"                                                                                                             , "    - /etc/php/7.3/cli/conf.d/20-posix.ini", "    - /etc/php/7.3/cli/conf.d/2                                                                                                             0-readline.ini", "    - /etc/php/7.3/cli/conf.d/20-redis.ini", "    - /etc/php/7                                                                                                             .3/cli/conf.d/20-shmop.ini", "    - /etc/php/7.3/cli/conf.d/20-sockets.ini", "                                                                                                                 - /etc/php/7.3/cli/conf.d/20-sysvmsg.ini", "    - /etc/php/7.3/cli/conf.d/20-s                                                                                                             ysvsem.ini", "    - /etc/php/7.3/cli/conf.d/20-sysvshm.ini", "    - /etc/php/7.3                                                                                                             /cli/conf.d/20-tokenizer.ini", "  You can also run `php --ini` inside terminal t                                                                                                             o see which files are used by PHP in CLI mode."], "stdout": "", "stdout_lines":                                                                                                              []}
`
Thank for support.

**Comment by Vaalyn** [comment]
The errors are a little bit strange to me as they reference PHP 7.3 and complain that several extensions are missing for that version. In our Ansible scripts for the Bare-metal installation we install PHP 7.2 + the necessary extensions for that version. Did you manually update your PHP version to 7.3?

**Comment by Vaalyn** [comment]
Closing this issue as there has not been an answer after the initial report for more than a month.
