### ISSUE TITLE
there are two sounds between auto dj and live broadcast

### ISSUE THREAD

**Issue by istahilagi** [AzuraCast/AzuraCast#1356]
when I use live broadcast (streamer dj), the auto dj song is still heard ... so there are two sounds between auto dj and live broadcast ... How do I make the auto dj song not sound when the live broadcast?

**Comment by muppathimoonu** [comment]
After recent update, same happens with my station as well. Also, WebDJ page freezes some.time.

**Comment by SlvrEagle23** [comment]
@istahilagi @muppathimoonu This should be fixed as of the latest update. Sorry about that!

**Comment by muppathimoonu** [comment]
Waiting ;))

**Comment by istahilagi** [comment]
waiting for him

**Comment by SlvrEagle23** [comment]
What are you waiting for exactly? The update is live; you can update as of when I posted that message.

**Comment by istahilagi** [comment]
can you tell me how to update it

**Comment by SlvrEagle23** [comment]
@istahilagi Just update the same way you would normally update AzuraCast. For Docker, that would be:

```
./docker.sh update-self
./docker.sh update
```

for bare-metal that's `./update.sh`.

**Comment by istahilagi** [comment]
Okay, thank you :)
now I'm updating the process

**Comment by istahilagi** [comment]
I have updated ...
already successful ...
but there is a new problem ... the live broadcast sound is broken up and down

**Comment by SlvrEagle23** [comment]
@istahilagi You're going to have to be more specific about the problem. The original issue you reported should be fixed now. If you're encountering a different issue, that should be created as a new issue to avoid leaving this one open.

**Comment by istahilagi** [comment]
okay sir, maybe I will make a new issue

**Comment by Rafaelrds2017** [comment]
ok, this is also happening in the musical request (Request a song).

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 I just noticed I didn't apply the fix to requests, so that's now done as well. It should be back to normal transitioning.
