### ISSUE TITLE
Sound processing

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#1357]
Is it possible to have Sound processing, automatic volume leveling in the Azuracast?

Att
Rafael

**Comment by bjarn** [comment]
There is! Check out the Edit Station -> Auto DJ and check either **Apply Compression and Normalization** and/or **Replaygain Metadata**. Those options should help you out.

**Comment by Rafaelrds2017** [comment]
Thank You!

> Há sim! Confira a Edit Station -> Auto DJ e marque **Apply Compression and Normalization** e / ou **Replaygain Metadata** . Essas opções devem ajudá-lo.

Thank You!

**Comment by macbroadcast** [comment]
Yes, a long awaited feature, thanks for that, i tried with my station, but there should be a more fine grained controll about the compression, otherwise the music "pumps" too much when you play newer rap music with a lot of bass in it, works fine with older music. :+1:
