### ISSUE TITLE
Automatic silence trimmer

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#1358]
There is the possibility of having automatic silence cut, remove the silence from the beginning and end of the music tracks?

Att
Rafael

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 We had implemented silence removal in our Liquidsoap script, but it was causing CPU load and skipping issues for many users, so we removed it.

**Comment by Rafaelrds2017** [comment]
Better that way! :)

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 Closing this issue as we already had another outstanding enhancement request for silence detection, and we're moving our feature requests over to FeatureUpvote to help clean up our issues section: https://azuracast.featureupvote.com/suggestions/38925/detect-silence-dead-air-in-incoming-streams
