### ISSUE TITLE
Improvement // Use the external Icecast

### ISSUE THREAD

**Issue by jimpy51** [AzuraCast/AzuraCast#136]
Hello,

How it's possible to use an external Icecast or Shoutcast (on a another server for example),
Can you add fields in the "Edit Station" page (hostname, port, user, pass and mountpoint).
If the external server is checked, use these parameters in the .liq :)

PS : i would like help you for the French translate, how can i do ?

Thanks a lot for you work,

**Comment by SlvrEagle23** [comment]
@jimpy51 We use CrowdIn to handle our localization, and we definitely want more help! You can help by signing up on https://crowdin.com/project/azuracast/invite

**Comment by jimpy51** [comment]
Hello,

Do you have any news ? This improvement is important for me.
In my infrastructure, my icecast server is alone on a dedicated server!

Regards,

**Comment by SlvrEagle23** [comment]
@jimpy51 Officially, this isn't currently supported, and it would take a fair amount of work to add full first-class support for external IceCast/ShoutCast servers.

There is, however, a section in the LiquidSoap configuration inside AzuraCast where you can specify custom configuration items. This is an excellent place to add in support for relaying to external IceCast or ShoutCast servers. The line for the broadcast would basically look like:

```
output.icecast(%mp3.cbr(samplerate=44100,stereo=true,bitrate=128), id="radio_out_1", host = "localhost", port = 8000, password = "SourcePass", name = "AzuraTest Radio", description = "", mount = "/radio.mp3", public = false, radio)
```

**Comment by shaundewberry** [comment]
Alternatively one could also setup the external icecast server to just pull from the Azuracast server using the relay directive in icecast2.xml:
```
<relay>
        <server>my.server.com</server>
        <port>80</port>
        <mount>/radio/8000/auto</mount>
        <local-mount>/stream</local-mount>
        <on-demand>0</on-demand>
        <relay-shoutcast-metadata>0</relay-shoutcast-metadata>
</relay>
```
Obviously one loses certain statistical functionality, but I found it a great way to migrate from an old server to a new one.

**Comment by SlvrEagle23** [comment]
@jimpy51 @shaundewberry Update for everyone subscribed to this issue:

I have spent the last few days working on rebuilding the Remote server feature to add support for two big improvements: syndicating multiple streams on a single station and broadcasting from the AzuraCast LiquidSoap instance out to a remote IceCast server.

This new functionality is made possible by adding support for "mount points", which are normally used to distinguish streams/mounts on Icecast/Shoutcast, and are used for a similar purpose here.

This is a new feature and is early in its testing, so please take a look and let me know if you encounter any new issues by creating new tickets.
