### ISSUE TITLE
Clear Playlist

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#1361]
Latest Version of AzuraCast, Docker, Ubuntu 18.04
I can't find "Clear from Playlist" anymore? I want to remove one track from playlist, but there is no option anymore. Is it a bug or i am blind?

**Comment by SlvrEagle23** [comment]
@LordHelmchen666 You're not missing it, it's just that both "Add to Playlist" and "Clear Playlists" have been replaced by the new "Set Playlists". If you set a song as being a part of no playlists, it will remove it from any playlists it's already in.

**Comment by LordHelmchen666** [comment]
I understand. Thank you very much.
