### ISSUE TITLE
Once per X songs  not working after update

### ISSUE THREAD

**Issue by danielrodrigotest** [AzuraCast/AzuraCast#1362]
Daear all, I found amazing your last update and I'm testing in case of bugs. The problem is that when the AutoDJ is working, Jingles (once per x songs) are not working and only music plays all time. 
I would like to find any fix or something like that.
Thanks 
![Screenshot 2019-03-28 at 3 05 55 PM](https://user-images.githubusercontent.com/40525323/55181782-10fedf00-516b-11e9-8a8d-78c1c4bb042f.png)
![Screenshot 2019-03-28 at 3 06 03 PM](https://user-images.githubusercontent.com/40525323/55181783-11977580-516b-11e9-9997-c3720490df53.png)

**Installation method**

**Host OS (for Docker installations)**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by chourmovs** [comment]
confirmed

**Comment by Ficreet** [comment]
I also have the same problem, it's very annoying

**Comment by SlvrEagle23** [comment]
Merging this with #1364.
