### ISSUE TITLE
aac only 64 kb/s

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#1363]
Hello,

i added a aac remote Relay. This only sends in 64 kb/s aac but i set it to 320 kb/s.
Is this a bug?
Please fix

**Comment by SlvrEagle23** [comment]
@preterive Are you using SHOUTcast, and if so, are you using the latest version of the SHOUTcast DNAS software? There are some limitations imposed by the "freemium" license on the latest SHOUTcast, and we don't recommend using it for this reason.

**Comment by preterive** [comment]
No, I use icecast.

**Comment by Vaalyn** [comment]
I just tested this with the demo installation and there this seems to be working. When I opened the IceCast page of the remote mountpoint it showed the stream bitrate as 320kbps. I'll post a sceenshot of how I configured the remote relay. Can you check if there is anything different from your setup?

![azuracast-relay](https://user-images.githubusercontent.com/13745863/55275564-54cb2300-52e8-11e9-95b6-08a6e39543f1.png)

**Comment by preterive** [comment]
Sorry for the late response,

there is no shoutcast working, only icecast.

**Comment by preterive** [comment]
Hello,
i could stream with the local program butt with 320 kb/s aac.

**Comment by preterive** [comment]
Hello,

yes my settings ar the same.
I now see that i only stream with MPEG4 HE-AAC v1 and not with MPEG4 HE-AAC v2 too.

**Comment by preterive** [comment]
okay, the program puts bitrate=96 in the config, without problems. But i only receive 96 kb/s in vlc.

**Comment by preterive** [comment]
I miss the Metadata too.
Do you need More informations? I will try to send with Manual configuration...

Everything works with Butt on my local pc...
