### ISSUE TITLE
Embedded player not playing

### ISSUE THREAD

**Issue by dlucas9** [AzuraCast/AzuraCast#1366]
Hi, I believe a recent update has broken the embedded player links.

"https://{url}:8000/{mount}"
rather than
"https://{url}/radio/8000/{mount}"

**Comment by Vaalyn** [comment]
This could be the same as in issue #1342. Is your AzuraCast installation on a server behind a proxy like CoudFlare? If so then you need to activate the System Setting `Use Web Proxy for Radio`.

**Comment by dlucas9** [comment]
You are indeed correct. I had limited direct access to the ports.
This confused me because it suddenly stopped working after an upgrade.
Also the URL in the manage interface was the web proxy one so it did puzzle me (without web proxy set).
Many thanks for setting me on the right path.
