### ISSUE TITLE
Install IceCast 2.4.2 It's possible?

### ISSUE THREAD

**Issue by LLExclamaniac** [AzuraCast/AzuraCast#1367]
Hello everyone
How can I install IceCast 2.4.2 on AzuraCast?
We do not want to use KH
It's possible?
I want the radio being listed on public lists
And this KH version does not appear
And I can't use mountpoints / live and / stream by default with it TuT

**Comment by LordHelmchen666** [comment]
I've just added this code (Profile - Broadcasting - Custom Configuratin)
`<directory>
    <yp-url-timeout>15</yp-url-timeout>
    <yp-url>http://dir.xiph.org/cgi-bin/yp-cgi</yp-url>
</directory>`
This enables station listing on xiph.org
http://dir.xiph.org/search?search=eisradio
Eisradio is my station.

**Comment by LLExclamaniac** [comment]
This code did not work for me ;~;

> I've just added this code (Profile - Broadcasting - Custom Configuratin)
> `<directory> <yp-url-timeout>15</yp-url-timeout> <yp-url>http://dir.xiph.org/cgi-bin/yp-cgi</yp-url> </directory>`
> This enables station listing on xiph.org
> http://dir.xiph.org/search?search=eisradio
> Eisradio is my station.

**Comment by SlvrEagle23** [comment]
@LLExclamaniac The Icecast-KH fork is highly compatible with the upstream Icecast and should be able to advertise to Yellow Pages directories without any issues.

Along with the instructions above, make sure each mount point on your station has the "Publish to "Yellow Pages" Directories" setting enabled.

**Comment by LLExclamaniac** [comment]
Thank you very much! Now works! *u* 

> @LLExclamaniac O garfo Icecast-KH é altamente compatível com o Icecast upstream e deve ser capaz de anunciar nos diretórios das Páginas Amarelas sem problemas.
> 
> Juntamente com as instruções acima, certifique-se de que cada ponto de montagem em sua estação tenha a configuração "Publicar em" Páginas Amarelas "Diretórios" ativada.
