### ISSUE TITLE
How to edit total listner slot 

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#137]
Hello,

How to edit default listener slot from 500 to more listeners?

**Comment by surihost** [comment]
Hope its possible to edit the total listener value

**Comment by SlvrEagle23** [comment]
@surihost Yes, the commit that closed the issue added the necessary code that makes the total listener count user editable per station.

**Comment by surihost** [comment]
Great its working now.How ever i see the that for unlimited listener we have to leave the field blank.But if i do so it shows 250 on shoutcast page.
