### ISSUE TITLE
Bug in Song History

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#1370]
Song History Source is always showing Live Broadcast.
![Screenshot_20190329_144002](https://user-images.githubusercontent.com/43477041/55236592-99938300-5230-11e9-8904-e316a4a2792b.png)
Updated Azuracast just before i took the screenshot.

**Comment by LordHelmchen666** [comment]
Now it shows playlist: default as it should. Between 13:00 and 17:00 there should have been playlist: Feierabend. On some tracks it is correctly logged, but on most false. Seems it has something to do with that specific playlist. I'll look tomorrow what will be logged.

**Comment by MrSteelMiner** [comment]
same problem here.

Seems to only happen on scheduled playlists

**Comment by SlvrEagle23** [comment]
@LordHelmchen666 @MrSteelMiner This is fixed as of the latest update.
