### ISSUE TITLE
Song Listener Impact empty

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#1371]
AzuraCast latest version, Docker, Ubuntu 18.04
Song Listener Impact says "No result found"
![Screenshot_20190329_144720](https://user-images.githubusercontent.com/43477041/55237123-aebce180-5231-11e9-8f95-bdce48bc7874.png)

**Comment by SlvrEagle23** [comment]
@LordHelmchen666 Thank you for the report. This is fixed as of the latest update.
