### ISSUE TITLE
External playlist with cue points

### ISSUE THREAD

**Issue by jovadeza** [AzuraCast/AzuraCast#1372]
Hi.

I would like to load a remote playlist with audio files each hour. The playlist will include cue points to be followed by Liquidsoap. To my knowledge it is not possible to include cue points in PLS and/or M3U playlist files.

Any other way to accomplish this? I know it is possible to add custom cue points in the AzuraCast filemanager, but the playlist is externally generated so I can't use those fields.

Thanks in advance!

**Comment by SlvrEagle23** [comment]
@jovadeza The way we do it is by using Liquidsoap's annotation format. Liquidsoap understands file URIs in the form `annotate:start_next=2:/file/path.mp3`, which you can use to manually provide annotations directly alongside the files.

We documented all of the available Liquidsoap annotations [in this readme file](https://github.com/AzuraCast/azuracast.com/blob/master/LiquidsoapAnnotations.md).
