### ISSUE TITLE
[BUG] Scheduled Playlists play at wrong time (-1 hour)

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1373]
**Installation method**

Bare-metal

**Host OS (for Docker installations)**

Ubuntu 18.04

**Describe the bug**

The scheduled playlist doesn't play at specified time.
Planned a playlist a couple of weeks ago to play between 23:00 and 0:00 CET, it's 23:19 CET now, still not playing. (Restarted station twice)
In earlier versions it worked, but now it doesn't.

**Expected behavior**

Playlist plays at specific time.

**Relevant Logs**

2019/03/29 22:57:01 [lang:3] AzuraCast Feedback Response: OK
2019/03/29 23:00:22 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/main/media/Musik/Metal/Leo Moracchioli/Born to Be Wild (metal cover by Leo Moracchioli).mp3".
2019/03/29 23:00:32 [playlist_metal:3] Finished with "/var/azuracast/stations/main/media/Musik/Metal/AC DC/AC DC - Stiff Upper Lip .mp3".
2019/03/29 23:00:32 [main_playlist_fallback:3] Switch to main_autodj_fallback with forgetful transition.
2019/03/29 23:00:33 [smart_cross_6505:3] Analysis: -12.687654dB / -13.592269dB (3.02s / 3.02s)
2019/03/29 23:00:33 [smart_crossfade:3] No transition: using default.
2019/03/29 23:00:36 [lang:3] AzuraCast Feedback Response: OK
2019/03/29 23:03:25 [lang:3] AzuraCast Raw Response: annotate:title="Tamam Tamam",artist="Summer Cem",duration="147.",song_id="aa1caf532ac771fe2f835ae7ee5f52d4",media_id="39329",genre="39329",playlist_id="39":/var/azuracast/stations/main/media/Musik/1A Charts/2018-04-27/07. Summer Cem - Tamam Tamam.mp3
2019/03/29 23:03:25 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/main/media/Musik/1A Charts/2018-04-27/07. Summer Cem - Tamam Tamam.mp3".
2019/03/29 23:03:34 [main_next_song:3] Finished with "/var/azuracast/stations/main/media/Musik/1A Charts/2018-08-10/03. Bonez MC & RAF Camora - 500 PS.mp3".
2019/03/29 23:03:34 [main_next_song:3] Prepared "/var/azuracast/stations/main/media/Musik/1A Charts/2018-04-27/07. Summer Cem - Tamam Tamam.mp3" (RID 3).
2019/03/29 23:03:35 [smart_cross_6505:3] Analysis: -49.302773dB / -13.473743dB (3.02s / 3.06s)
2019/03/29 23:03:35 [smart_crossfade:3] No transition: using default.
2019/03/29 23:03:38 [lang:3] AzuraCast Feedback Response: OK
2019/03/29 23:05:52 [lang:3] AzuraCast Raw Response: annotate:title="Hold Back The River",artist="James Bay",duration="240.",song_id="0b9c6d13095231c178c20848bc6986ae",media_id="38294",genre="38294",playlist_id="2":/var/azuracast/stations/main/media/Musik/1A Charts/2015-06-13/35. James Bay - Hold Back The River.mp3
2019/03/29 23:05:52 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/main/media/Musik/1A Charts/2015-06-13/35. James Bay - Hold Back The River.mp3".
2019/03/29 23:06:02 [main_next_song:3] Finished with "/var/azuracast/stations/main/media/Musik/1A Charts/2018-04-27/07. Summer Cem - Tamam Tamam.mp3".
2019/03/29 23:06:02 [main_next_song:3] Prepared "/var/azuracast/stations/main/media/Musik/1A Charts/2015-06-13/35. James Bay - Hold Back The River.mp3" (RID 18).
2019/03/29 23:06:02 [smart_cross_6505:3] Analysis: -66.376530dB / -31.926551dB (3.04s / 3.04s)
2019/03/29 23:06:02 [smart_crossfade:3] new >= old + margin, old <= medium and new <= high.
2019/03/29 23:06:02 [smart_crossfade:3] Do not fade if it's already very low.
2019/03/29 23:06:02 [smart_crossfade:3] Transition: crossed, no fade.
2019/03/29 23:06:02 [lang:3] AzuraCast Feedback Response: OK
2019/03/29 23:09:49 [lang:3] AzuraCast Raw Response: annotate:title="Get Lucky",artist="084 - Daft Punk Feat. Pharrell Williams",duration="248.",song_id="1c7a1bca1fefd0ec64ead1bacb319d04",media_id="38046",genre="38046",playlist_id="38":/var/azuracast/stations/main/media/Musik/1A Charts/2013-12-02/084 - Daft Punk Feat. Pharrell Williams - Get Lucky.mp3
2019/03/29 23:09:49 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/main/media/Musik/1A Charts/2013-12-02/084 - Daft Punk Feat. Pharrell Williams - Get Lucky.mp3".
2019/03/29 23:09:58 [main_next_song:3] Finished with "/var/azuracast/stations/main/media/Musik/1A Charts/2015-06-13/35. James Bay - Hold Back The River.mp3".
2019/03/29 23:09:58 [main_next_song:3] Prepared "/var/azuracast/stations/main/media/Musik/1A Charts/2013-12-02/084 - Daft Punk Feat. Pharrell Williams - Get Lucky.mp3" (RID 6).
2019/03/29 23:09:58 [smart_cross_6505:3] Analysis: -55.360908dB / -12.949255dB (3.03s / 3.05s)
2019/03/29 23:09:58 [smart_crossfade:3] No transition: using default.
2019/03/29 23:10:02 [lang:3] AzuraCast Feedback Response: OK

everything in the log with /var/azuracast/stations/main/media/Musik/Metal/... is correct as content for my scheduled playlist.

**Comment by MrSteelMiner** [comment]
found the bug... azuracast doen't get the time zone. Displays the correct one in playlist-editor and scheduled view, but plays it in UTC. So it plays from 22:00 CET to 23:00 CET.
![image](https://user-images.githubusercontent.com/47743654/55266209-1ac43780-527c-11e9-83c6-ee27dce8a989.png)
![image](https://user-images.githubusercontent.com/47743654/55266214-244d9f80-527c-11e9-9fb3-42e89e53239c.png)


And found another bug:
the wrong timed playlist is shown as live broadcast:
![image](https://user-images.githubusercontent.com/47743654/55266207-14ce5680-527c-11e9-9811-dd79491767e1.png)

**Comment by SlvrEagle23** [comment]
@MrSteelMiner AzuraCast tries to automatically detect the time zone used on the server if it differs from UTC, because Liquidsoap will use the server's time zone to handle any scheduling. If we detect a difference, we apply the offset between UTC and the server time zone.

Sometimes it doesn't properly read the time zone, and some hosts don't properly set the `/etc/timezone` file to the user's time zone. The easy fix for this is to make sure the `/etc/timezone` file matches the time zone you want to use. The other easy fix is to change the server's time zone to UTC, which avoids the offset entirely.

**Comment by MrSteelMiner** [comment]
@SlvrEagle23 my server is configured correctly:
![image](https://user-images.githubusercontent.com/47743654/55266522-b1ddbf00-527d-11e9-97a3-73010643872d.png)
same in /etc/timezone

To change the timezone is very confusing because the time marker (red triangle on scheduled view) is set on the real correct place. The playlist is one hour behind. It's confusing O.o

**Comment by MrSteelMiner** [comment]
> Sometimes it doesn't properly read the time zone, and some hosts don't properly set the `/etc/timezone` file to the user's time zone. The easy fix for this is to make sure the `/etc/timezone` file matches the time zone you want to use. The other easy fix is to change the server's time zone to UTC, which avoids the offset entirely.

Or do you mean changing hosts timezone?

**Comment by MrSteelMiner** [comment]
nevermind. Changed the host-timezone. Now it works. Strange but works

**Comment by SlvrEagle23** [comment]
@MrSteelMiner Your server time zone is CET and Liquidsoap should be writing the times in CET because that's the time Liquidsoap is using. Not sure why it isn't detecting that, given the necessary files are set up correctly.

**Comment by MrSteelMiner** [comment]
no. my server time zone was Europe/Berlin (UTC+1). Now I changed it to UTC and now scheduling works again. I'm shure in earlier releases it worked correctly. Never touched the /etc/timezone again after first install.

**Comment by SlvrEagle23** [comment]
@MrSteelMiner I'm agreeing with you, not contradicting you. When your server time zone was CET, Liquidsoap _should_ have been writing things in CET, not UTC.

There may be an error in how we parse time zones, and I'll look into that.

**Comment by MrSteelMiner** [comment]
oh okay, I got you wrong :D
