### ISSUE TITLE
Custom Cues: Cue-In and Cue-Out Point 

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#1375]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 18.04

**Describe the bug**
Since the last update, whether it is the "Smart Mode
Normal Mode, Disable Crossfading" the time I entered for each track is not taken into account. I even have silence for 2 to 3 seconds between each track. 

The entry and exit points of a song are no longer taken into account
>Custom Cues: Cue-In Point (seconds)
> Custom Cues: Cue-Out Point (seconds)

**Comment by SlvrEagle23** [comment]
@ckeurk It seems in the Liquidsoap transition this was removed and I forgot to actually put it back. It's back now for all playlist types.
