### ISSUE TITLE
Jingle Mode tracks not in Song History?

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#1376]
I have a playlist "Jingles" with setting "Hide Metadata fom listeners" and "once per x songs". They are not shown in Song History. Is it a  feature or bug?

**Comment by SlvrEagle23** [comment]
@LordHelmchen666 This is an intended feature, because hiding a track from metadata also hides it from AzuraCast itself (which would otherwise show it in the "Now Playing" API responses).
