### ISSUE TITLE
Can't add custom frontend configuration for mount

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#1377]
**Installation method**
Docker

**Host OS (for Docker installations)**
Debian 9

**Describe the bug**
When trying to add a configuration like `<mount><intro>/file.mp3</intro></mount>` to the custom frontend config the `src/Xml/Writer.php` will error out with `Mixing of string and numeric keys is not allowed`. Which makes it impossible to add custom configs to a mount in the IceCast config.

**To Reproduce**
Try adding the following to the custom frontend configuration and save it:
```
<mount>
    <intro>{path to file}</intro>
</mount>
```

**Expected behavior**
The custom config should be written to the mount configuration.

**Relevant Logs**
```
AzuraCast.ERROR: Mixing of string and numeric keys is not allowed {"file":"/var/azuracast/www/src/Xml/Writer.php","line":99,"code":0} []
```

**Additional context**
When looking at the `$config` variable given to the writer this is what is specified in the `["mount"]` entry:
```
array(3) {
  [0]=>
  array(7) {
    ["@type"]=>
    string(6) "normal"
    ["mount-name"]=>
    string(12) "/test-stream"
    ["charset"]=>
    string(4) "UTF8"
    ["stream-name"]=>
    string(33) "Brony Radio Germany - Test Stream"
    ["stream-description"]=>
    string(0) ""
    ["stream-url"]=>
    string(33) "https://www.bronyradiogermany.com"
    ["stream-genre"]=>
    string(11) "Brony Musik"
  }
  ["intro"]=>
  string(69) "/var/azuracast/stations/brg/media/TestStream/sia_furler_-_rainbow.mp3"
}
```

The `["intro"]` entry should be inside of the `[0]=> array(7) { ... }`.

**Comment by SlvrEagle23** [comment]
@Vaalyn Gotta add it to the custom mount point config, not the custom frontend config for the whole station, because they're added in at different stages.

**Comment by Vaalyn** [comment]
@SlvrEagle23 Thank you for the clarification. I forgot that there is a custom config for every mount^^
