### ISSUE TITLE
Jingle Mode is not playing

### ISSUE THREAD

**Issue by isaiaswebnet** [AzuraCast/AzuraCast#1378]
Jingle Mode tracks not playing every x songs or x songs minutes.

**Comment by SlvrEagle23** [comment]
@isaiaswebnet Do you mean you don't actually hear it on the station, or you're not seeing it logged in the station playback history? If the latter, that's intentional and part of how "Jingle Mode" works.

**Comment by isaiaswebnet** [comment]
Don't actually hear it on the station.

**Comment by SlvrEagle23** [comment]
@isaiaswebnet I'm not able to reproduce this on my local instances. Is there something unique about your playlists, i.e. do you have any settings checked that aren't their default values? It may be helpful to actually look at your setup (via screenshots or just directly looking at the AzuraCast installation itself) to further diagnose the issue.

**Comment by isaiaswebnet** [comment]
![image](https://user-images.githubusercontent.com/4692453/55293210-76044000-53ca-11e9-8dc5-932c58c09bb3.png)

**Comment by isaiaswebnet** [comment]
![image](https://user-images.githubusercontent.com/4692453/55293219-8f0cf100-53ca-11e9-880e-bf0c8074f797.png)

**Comment by isaiaswebnet** [comment]
![image](https://user-images.githubusercontent.com/4692453/55293234-aa77fc00-53ca-11e9-9324-87bb3c4302e4.png)

**Comment by isaiaswebnet** [comment]
Also has this error of not showing "Play next:" progress time.

![image](https://user-images.githubusercontent.com/4692453/55293598-7acaf300-53ce-11e9-8365-79a6eb2fa94b.png)

**Comment by isaiaswebnet** [comment]
I found this error in "Now Playing".

Error
NowPlaying adapter error: Request returned status 404: The file you requested could not be found

**Comment by Vaalyn** [comment]
@isaiaswebnet Is this problem still occurring on the newest AzuraCast version?

**Comment by netbladenl** [comment]
I also got this problem, one jingle only plays at a restart of broadcast, I don't know what I'm doing wrong.

**Comment by Vaalyn** [comment]
@netbladenl This could be related to #1564

**Comment by fabiocasolari** [comment]
I've just installed docker version and have the same issue....   jingle every x song or every hour at x minute does not work....  simply it do nothing, it continue with the playing playlist

**Comment by fabiocasolari** [comment]
any solution for this?
