### ISSUE TITLE
Web DJ not working - Docker

### ISSUE THREAD

**Issue by afonsosantos** [AzuraCast/AzuraCast#1379]
**Installation method**
Docker

**Host OS (for Docker installations)**
CentOS 7

**Describe the bug**
When using the Web DJ page, after entering the credentials, nothing happens. I'm using Google Chrome.

![image](https://user-images.githubusercontent.com/46262740/55283035-2fbacc80-5349-11e9-9fe5-51a15f6715a7.png)

After checking Chrome's console, I see the following error. It happens when I click on the Start Streaming button.

![image](https://user-images.githubusercontent.com/46262740/55283047-5973f380-5349-11e9-9a9d-6c640d3dbe03.png)

When using butt to connect, everything is working.
What can it be?

Thanks in advance.

**Comment by SlvrEagle23** [comment]
@afonsosantos Many browsers are restricting the web audio APIs to only work with secure (HTTPS) connections. If you try to visit the WebDJ on an insecure connection, the interface will load but it won't be able to actually make the connection under the hood.

Ideally you should set up something like LetsEncrypt (using our [instructions](https://www.azuracast.com/docker_sh.html#set-up-letsencrypt)) so that your connection is both secure and uses a valid certificate.

**Comment by afonsosantos** [comment]
Thanks for the reply!

Do i need to have a SSL certificate in order to use LetsEncrypt?

**Comment by SlvrEagle23** [comment]
@afonsosantos LetsEncrypt is how you get the SSL certificate. It's completely free and super simple to use. We even automate the renewal under the hood so you don't have to worry about it.

**Comment by afonsosantos** [comment]
I've runned the command, I'm checking to see if anything changed...

**Comment by afonsosantos** [comment]
![image](https://user-images.githubusercontent.com/46262740/55283485-4f0f2500-535c-11e9-847d-eea8f00afae9.png)

What's wrong?

**Comment by SlvrEagle23** [comment]
@afonsosantos Have you updated your `docker.sh` script recently? i.e. with `docker.sh update-self`? That could be a problem on our end.

**Comment by afonsosantos** [comment]
I'll try to update.

**Comment by afonsosantos** [comment]
By the way, I'm using a NoIP domain.

**Comment by afonsosantos** [comment]
I've updated AzuraCast and now i've managed to create a LetsEncrypt certificate, but Chrome says me that my website is insecure. What do i need to do next?

**Comment by afonsosantos** [comment]
Oh no, i've mess up... I activated HTTPS for AzuraCast, and now i can't access it's interface. What can I do?

**Comment by SlvrEagle23** [comment]
@afonsosantos You followed the `./docker.sh letsencrypt-create` process, right? That should have put the certificate in the proper location for nginx. Did it throw that same error again?

**Comment by afonsosantos** [comment]
> @afonsosantos You followed the `./docker.sh letsencrypt-create` process, right? That should have put the certificate in the proper location for nginx. Did it throw that same error again?

Yes i have, the website stays insecure. I'm updating AzuraCast to the latest version, as it shows on the home page.

**Comment by afonsosantos** [comment]
> @afonsosantos You followed the `./docker.sh letsencrypt-create` process, right? That should have put the certificate in the proper location for nginx. Did it throw that same error again?

After updating AzuraCast yesterday, the error disapered and the process was sucessful.

**Comment by SlvrEagle23** [comment]
@afonsosantos You mentioned that you're using no-ip, which may be causing the problem. You may not be able to use an SSL certificate served by your computer as a result. The same setup might work better with a dedicated VPS.

**Comment by afonsosantos** [comment]
> @afonsosantos You mentioned that you're using no-ip, which may be causing the problem. You may not be able to use an SSL certificate served by your computer as a result. The same setup might work better with a dedicated VPS.

Oh ok, that's fine. Another question: can butt connect to a specific mount point (like /butt.mp3)? I'm using IceCast and butt doesn't connect.

**Comment by SlvrEagle23** [comment]
@afonsosantos It can, but you would need to use the source password provided on the station's profile. If you're using the "Streamers/DJs" page, those streamers connect directly through Liquidsoap, whose default mount point is `/`.

**Comment by afonsosantos** [comment]
> @afonsosantos It can, but you would need to use the source password provided on the station's profile. If you're using the "Streamers/DJs" page, those streamers connect directly through Liquidsoap, whose default mount point is `/`.

It's not working...
![image](https://user-images.githubusercontent.com/46262740/55293193-cdff6e80-53eb-11e9-81ab-72b3d7216cee.png)
![image](https://user-images.githubusercontent.com/46262740/55293197-deafe480-53eb-11e9-8943-134a0453ca76.png)

**Comment by SlvrEagle23** [comment]
@afonsosantos If you're using AzuraCast's streamers/DJs page, the mount point is `/`, not `/butt.mp3`. Liquidsoap is managing the streaming so it can fade in and out between the AutoDJ and your streamer's audio.

**Comment by afonsosantos** [comment]
> @afonsosantos If you're using AzuraCast's streamers/DJs page, the mount point is `/`, not `/butt.mp3`. Liquidsoap is managing the streaming so it can fade in and out between the AutoDJ and your streamer's audio.

Thanks for your explanation. I will search for a DDNS service that supports Lets Encrypt, and see if that works. Thanks a lot!

**Comment by afonsosantos** [comment]
Another thing: how can i restart the NGINX service? I'm using CentOS 7.

**Comment by SlvrEagle23** [comment]
@afonsosantos If you're on Docker, the letsencrypt commands automatically reload the nginx configuration. To manually restart it, you can run `docker-compose restart web`.

**Comment by afonsosantos** [comment]
> @afonsosantos You mentioned that you're using no-ip, which may be causing the problem. You may not be able to use an SSL certificate served by your computer as a result. The same setup might work better with a dedicated VPS.

Hi, i've managed to use Let's Encrypt with NO-IP domains, now it's working! Now, the Web DJ interface loads, but when I click on **Start Streaming**, nothing happens, but the Chrome's console doesn't show me any errors. What can be happening?

![image](https://user-images.githubusercontent.com/46262740/55514133-40c45000-565f-11e9-9cf4-cb898e61a24b.png)
![image](https://user-images.githubusercontent.com/46262740/55514178-58033d80-565f-11e9-846b-39983f4cbdcf.png)

(I just love the dark theme for the public pages, thanks for this feature!)
