### ISSUE TITLE
Playing "Unknown" After Update

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#1380]
TRADITION

After the azuracast update I noticed a lot of problems, one of them is that with some tracks "In playback: unknow" is displayed while before there was this problem.
@SlvrEagle23 

![image](https://user-images.githubusercontent.com/22561729/55285888-71249980-5394-11e9-9a50-d19e8994a692.png)

**And Cue point starting and Cue point end (secondi) is ignored in some songs!**

**Comment by Ilario42** [comment]
I solved the "Unknow" problem but I still have problems with ....

**Seems like they don't exist "Cue point starting and Cue point end" It's very informative that they work again!**

**Comment by SlvrEagle23** [comment]
@Ilario42 the cue issue was also reported as issue #1375 and is now resolved.
