### ISSUE TITLE
How to configure Opticodec?

### ISSUE THREAD

**Issue by webma5ter23** [AzuraCast/AzuraCast#1386]
I'm using the Butt program, but I've had some connection problems. I would like to use Opticodec but when configuring via Shoucast or Icecast it does not connect to the server.

I appreciate any help

Regards

**Comment by brammittendorff** [comment]
We have the same problem it does not connect with Opticodec!?

**Comment by webma5ter23** [comment]
> 
> 
> We have the same problem it does not connect with Opticodec!?

Only connect with Shoutcast but not IceCast

**Comment by brammittendorff** [comment]
@webma5ter23 the problem with us was a other problem, when you have ipv6 docker wil automaticly bind the ports to ipv6, so when you are behind a ipv4 line it will not work ofc. And a other problem with connecting to a DNS name like `test.com` does not work when you put it behind the service from cloudflare.
