### ISSUE TITLE
Questions about Azuracast

### ISSUE THREAD

**Issue by Rootinator** [AzuraCast/AzuraCast#1387]
Hello,

I have some questions about Azuracast:

* How to decide when which playlist should be played (time)?
* How to move the songs within the playlist?
* What is the difference between "Mixing" and "Random" in the playlist settings?
* How to decide when to play a Jingle / AdTrigger (after X minutes)?
* Can I create a playlist in another music program and import it into Azuracast?

**Comment by Vaalyn** [comment]
- How to decide when which playlist should be played (time)?
    - Use the `Scheduled` playlist schedule and define the time with the options under `Customize Schedule`
- How to move the songs within the playlist?
    - You mean defining the order in a playlist manually?
- What is the difference between "Mixing" and "Random" in the playlist settings?
    - The `Shuffled` shuffles the playlist once according to the scheduling and weights and the generated order will be used every time until it is shuffled again (by adding something to the playlist or deleting something from it). The `Random` will always give you a random song according to the scheduling and weights.
- How to decide when to play a Jingle / AdTrigger (after X minutes)?
    - You can use the  `Once per x Songs` or `Once Per x Minutes` playlist schedule types or you can manually create the Luiquidsoap config for the playlist with the [`Advanced`](https://github.com/AzuraCast/azuracast.com/blob/master/AdvancedPlaylists.md) scheduling
- Can I create a playlist in another music program and import it into Azuracast?
    - You can import PLS und M3U playlists when creating a new playlist in AzuraCast

**Comment by beqabeqa473** [comment]
hi.

how i can schedule a playlist for example to play one track everyday at 15 o'clock

**Comment by SlvrEagle23** [comment]
@beqabeqa473 You should probably post that as a separate issue. It's going to involve custom Liquidsoap coding, but other AzuraCast users may be able to help you out.

**Comment by afonsosantos** [comment]
> hello.
> 
> how i can make a talking clock to announce clock every hour?

I'm wanting that too, could you please fill a new issue? Thanks!

**Comment by Rootinator** [comment]
> How to move the songs within the playlist?
>> You mean defining the order in a playlist manually?

Yes, I would like to know how to move the music tracks to another place within the playlist

Example:
Title 1
Title 7
Title 4
...

Not:
Title 1
Title 2
Title 3
...

**Comment by Vaalyn** [comment]
@Rootinator Set your playlist to the Song Playback Order `Sequential`. Then you can edit the order by clicking on the `more` button of a playlist and drag-and-drop the order how you like.

**Comment by Rootinator** [comment]
Thank you.

1. The playlist "Jingle-Playlist" (example) should be played every 30 minutes (content: 2 jingles), but only one jingle will play instead of the existing 2 jingles.

What do I have to do, that all jingles are played in sequence (without repeat)?

My settings of the playlist "Jingle-Playlist":
https://s16.directupload.net/images/190416/ezncpqr9.png
https://s16.directupload.net/images/190416/xuui2r99.png

2. How can I set to switch from the previously played playlist (Main) to "AdTrigger" without transition?

**Comment by Vaalyn** [comment]
@Rootinator Do you still need help with these playlists or did you figure it out?

**Comment by Rootinator** [comment]
AzuraCast continues to play only one jingle instead of all 2 in a row...

**Comment by Vaalyn** [comment]
It should work when you set your playlist to `Only loop through playlist once.` and `Merge playlist to play as a single track.`

**Comment by Rootinator** [comment]
With "Give list as 1 track again" is badly possible, since the meta-data triggers the advertising on the stream server.  

The first title announces the advertisement (advertisement) and the second one triggers the advertisement.  

Otherwise it is not possible, right?

**Comment by Rootinator** [comment]
Otherwise is it not possible for the meta-data of all titles to be transmitted?

**Comment by Vaalyn** [comment]
`Merge playlist to play as a single track.` should still show the correct meta-data for each song but do exactly what you want, playing all tracks of that playlist after each other as if they were one track.

I've just checked the config generation for Liquidsoap and noticed that you should only use `Merge playlist to play as a single track.` and not `Only loop through playlist once.` as they currently can't be combined.

**Comment by Vaalyn** [comment]
That's good to hear =)

I'll close this issue now as resolved.
