### ISSUE TITLE
Apply Compression and Normalization

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#1388]
Just a quick note about the option of compression and normalization of the sound. It seems to me that you are using the Liquidsoap preset "nrj", the problem with this preset is that it is very poorly adjusted in the compression as well as in the limiter.
In breaks where the music is very quiet, the volume increases all at once and becomes too loud, as soon as the rhythmic arrives everything goes down in volume, it's not really pretty. :(

I just propose you to replace the nrj preset with this simply and I think everyone will be happy
`radio = normalize(target = 0., window = 0.03, gain_min = -16., gain_max = 0., radio)
radio = compress.exponential (radio, mu = 1.0)`
this is the code I use in Advanced Custom Configuration

**Comment by SlvrEagle23** [comment]
@ckeurk I agree, that does sound a lot better, especially at louder volume portions of the songs. I like it.

Code is updated to use that as the replacement for `nrj`.

**Comment by macbroadcast** [comment]
@SlvrEagle23 is this implemented in the current rolling update ?

**Comment by macbroadcast** [comment]
Much better now !!!

**Comment by andrewbritton** [comment]
![Screen Shot 2019-06-13 at 12 17 50](https://user-images.githubusercontent.com/20565847/59429220-3c42b300-8dd7-11e9-8529-7f409abf811e.png)
Hi @SlvrEagle23, Is there any way of making theses settings tweakable by end users? I also agree this preset does sound much better than the original one, however, it would be a really nice feature to make it more adjustable by the end user. As you can see in this screenshot of 25 minutes of audio from my stream there are still a lot of portions where the audio could be louder. A simple optional 6/12/18db boost pre limiter would probably do the job. (All my music files were normalised to 0.1 db before importing into Azuracast). Thank you again for such an awesome piece of software.

**Comment by Vaalyn** [comment]
@andrewbritton Please create a feature request for that over at https://features.azuracast.com/ so that we can keep track of it and other users can signal how important such a feature is to them. This helps us to prioritise new features.
