### ISSUE TITLE
mixing two playlists

### ISSUE THREAD

**Issue by beqabeqa473** [AzuraCast/AzuraCast#1391]
hello.

how i can mix two playlists in a following way.

for example, i have a music (main) playlist
i also have a jingles playlist which is playing eveyr 5 minutes.
i don't want jingles to wait ending a song in music playlist but i want to lower a volume of music playlist and play a jingle and then restore volume of music playlist back when jingle ends.

**Comment by ckeurk** [comment]
To perform this kind of mixing personally, on each track I define the Custom Fading: Fade-Out Time (seconds) on 2 seconds and Custom Cues: Cue-In Point (seconds) 2 or 3 seconds.
Then I enter the duration of the title in the last line Custom Cues: Cue-Out Point (seconds).

If a title makes a total of 5 minutes and 40 seconds, so 324 seconds. 
I shorten the duration by about 5 minutes and 20 seconds, so in seconds 312.

**Comment by beqabeqa473** [comment]
on which tracks are you doing this?

i don't fully understand this technic.

if i have hundreds of songs in music playlist, how can i change all tracks?

On 4/3/19, ckeurk <notifications@github.com> wrote:
> To perform this kind of mixing personally, on each track I define the Custom
> Fading: Fade-Out Time (seconds) on 2 seconds and Custom Cues: Cue-In Point
> (seconds) 2 or 3 seconds.
> Then I enter the duration of the title in the last line Custom Cues: Cue-Out
> Point (seconds).
>
> If a title makes a total of 5 minutes and 40 seconds, so 324 seconds.
> I shorten the duration by about 5 minutes and 20 seconds, so in seconds
> 312.
>
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AzuraCast/AzuraCast/issues/1391#issuecomment-479419951


-- 
with best regards beqa

**Comment by ckeurk** [comment]
On each track you have the possibility to change the parameters 
![Capture d’écran 2019-04-03 à 12 07 58](https://user-images.githubusercontent.com/379099/55471025-23fd2d80-5609-11e9-9985-af420644ab3d.png)

**Comment by beqabeqa473** [comment]
i need to play jingle every 5 minutes with main music as background.

how i can do that?

On 4/3/19, ckeurk <notifications@github.com> wrote:
> On each track you have the possibility to change the parameters

> ![Capture d’écran 2019-04-03 à 12 07
> 58](https://user-images.githubusercontent.com/379099/55471025-23fd2d80-5609-11e9-9985-af420644ab3d.png)

>

>

> --

> You are receiving this because you authored the thread.

> Reply to this email directly or view it on GitHub:

> https://github.com/AzuraCast/AzuraCast/issues/1391#issuecomment-479426071


-- 
with best regards beqa

**Comment by ckeurk** [comment]
You have to see in your playlist
![Capture d’écran 2019-04-03 à 12 36 18](https://user-images.githubusercontent.com/379099/55472742-29f50d80-560d-11e9-81d3-34146e17a172.png)

**Comment by beqabeqa473** [comment]
i am not sure you fully understand me.

i have music playlist, with 500 tracks. i have 10 jingles which should
play every five minutes. it should be a case when track from music is
playing and on every five minutes jingles should turn on and play.
music playlist should be lowered and after playing jingle it should
restore its volume.
jingles should play in any case, if track is in middle state.

On 4/3/19, ckeurk <notifications@github.com> wrote:
> You have to see in your playlist

> ![Capture d’écran 2019-04-03 à 12 36
> 18](https://user-images.githubusercontent.com/379099/55472742-29f50d80-560d-11e9-81d3-34146e17a172.png)

>

>

> --

> You are receiving this because you authored the thread.

> Reply to this email directly or view it on GitHub:

> https://github.com/AzuraCast/AzuraCast/issues/1391#issuecomment-479434676


-- 
with best regards beqa

**Comment by LordHelmchen666** [comment]
You would need ["add"](https://www.liquidsoap.info/doc-1.3.6/reference.html#add) or ["smooth_add"](https://www.liquidsoap.info/doc-1.3.6/reference.html#smooth_add) feature of Liquidsoap. This is not a feature added in AzuraCast. Maybe you can do that in Advanced Configuration.

**Comment by SlvrEagle23** [comment]
@beqabeqa473 The reply by @LordHelmchen666 is correct; this is advanced functionality, because AzuraCast only supports sequential song playback, not overlaying one track on top of another.

You could add your jingle playlist as an "Advanced" playlist, which would add it as a  variable (but not include it in regular playback), which you can then reference in the Advanced Custom Configuration code using code similar to the above example.
