### ISSUE TITLE
For the title editing mode

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#1393]
It's just a small proposal to make it easier to edit the parameters for each title 

![Simple Custom Fade](https://user-images.githubusercontent.com/379099/55473692-8c4f0d80-560f-11e9-956f-ad308877c7fe.jpg)

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39042/add-inline-titleartistetc-editing-to-media-management
