### ISSUE TITLE
standard playlists and scheduled playlists play at the same time

### ISSUE THREAD

**Issue by NadjaNeville** [AzuraCast/AzuraCast#1396]
I use a mixture of standard and scheduled playlists with the scheduled ones setting accents during certain times of day. Usually the scheduled playlist overrides the standard but my stations just play the scheduled playlist additionally on top of the standard playing two songs at once. Restarting the station or rebooting the server doesn't correct this behavior. Standard playlists play all the time, no matter if a scheduled playlist is due.

**Comment by SlvrEagle23** [comment]
@NadjaNeville Are you on the very latest version of the software? Not the latest release version, the latest "rolling release" version.

**Comment by NadjaNeville** [comment]
The version shown in the api is v0.9.4.2, #0a30553

**Comment by SlvrEagle23** [comment]
@NadjaNeville There have been some updates released since then that address this issue. Please update again to the very latest version and let me know if this issue persists.

**Comment by NadjaNeville** [comment]
First tests show issue is gone with the latest update. Thanks for the quick reaction!
