### ISSUE TITLE
Revert to previous commit

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1398]
Is it possible to install a previous release or a state of a specific commit? I see an (erroneous) behaviour I cannot explain and I'd like to test it against a previous release (where it was still good).

**Comment by Vaalyn** [comment]
We do not officially support reverting to a previous version of AzuraCast. Theoretically you could revert to a previous version by entering the docker container and using Git commands to checkout a previous version. I don't want to promote doing this as it is potentially dangerous to do if you don't know what you are doing.
