### ISSUE TITLE
current_song in API is empty, breaks public page and embed

### ISSUE THREAD

**Issue by mkody** [AzuraCast/AzuraCast#140]
The title isn't updated in the public page and embed.
![image](https://cloud.githubusercontent.com/assets/843787/26470620/b09855d4-419e-11e7-99cb-724e9bb4b6f9.png)

In the API, the `current_song` variable is just an empty array. So `row.current_song.title` and `row.current_song.artist` return _undefined_.

---

**Also**, in the embed page, I saw an error on the console.
![image](https://cloud.githubusercontent.com/assets/843787/26470658/cdd43096-419e-11e7-8b64-375ba638d388.png)

In the function `nowPlaying()`, the `$.getJSON` should hit `/api/nowplaying/<STATION ID>` instead of `/api/nowplaying`.

**Comment by SlvrEagle23** [comment]
@mkody I'll definitely fix the embed/public page not using the station-specific nowplaying endpoint, but I'm not seeing any cases on any servers where you would wind up with a blank array for the "current_song" variable. Even if the station is offline, there is a fake placeholder song ("Station Offline") that would fill that gap and make sure the API is consistent.

**Comment by mkody** [comment]
Well that's weird, you can take a look here: https://azura.ponies.fr/api/nowplaying
I updated yesterday and did a reboot of the machine.
