### ISSUE TITLE
Web DJ still not working

### ISSUE THREAD

**Issue by afonsosantos** [AzuraCast/AzuraCast#1400]
**Update to issue #1379** 

@SlvrEagle23 
Hi, i've managed to use Let's Encrypt with NO-IP domains, now it's working! Now, the Web DJ interface loads, but when I click on **Start Streaming**, nothing happens, but the Chrome's console doesn't show me any errors. What can be happening?

![image](https://user-images.githubusercontent.com/46262740/55514133-40c45000-565f-11e9-9cf4-cb898e61a24b.png)
![image](https://user-images.githubusercontent.com/46262740/55514178-58033d80-565f-11e9-846b-39983f4cbdcf.png)

(I just love the dark theme for the public pages, thanks for this feature!)

**Comment by SlvrEagle23** [comment]
@afonsosantos From "Utilities" > "Log Viewer", check to see if Liquidsoap is logging any errors when you try to connect. It may be having trouble validating your DJ credentials.

**Comment by afonsosantos** [comment]
Hi,

Thanks for the reply. Here is my Liquidsoap log:
``
![image](https://user-images.githubusercontent.com/46262740/55586944-1be4e100-5722-11e9-9445-494127794deb.png)

Also the hour in the logs is delayed by 1 hour.

**Comment by radiolize** [comment]
Hello

I had the same problem and checked liquidsoap logs and solved it with turning off cross-fade smart to none.

**Comment by afonsosantos** [comment]
> Hello
> 
> I had the same problem and checked liquidsoap logs and solved it with turning off cross-fade smart to none.

Hi, I will try that.

**Comment by radiolize** [comment]
try deleting streamer/dj and adding streamer/dj again and disable normalize option

**Comment by afonsosantos** [comment]
> try deleting streamer/dj and adding streamer/dj again and disable normalize option

I will do it tomorrow, thanks! Then I'll post here the results.

**Comment by SlvrEagle23** [comment]
@afonsosantos I'm not confident that those other fixes will help you with your issue.

The logs are showing that nothing is going wrong, the AzuraCast service is just returning `false` for your DJ authentication, meaning it thinks the password isn't valid.

If your password has a comma, semicolon or colon in it, you should remove those because some streaming software uses them to join username and password together.

**Comment by afonsosantos** [comment]
> @afonsosantos I'm not confident that those other fixes will help you with your issue.
> 
> The logs are showing that nothing is going wrong, the AzuraCast service is just returning `false` for your DJ authentication, meaning it thinks the password isn't valid.
> 
> If your password has a comma, semicolon or colon in it, you should remove those because some streaming software uses them to join username and password together.

I've deleted the DJ account and created a new one, now it's working! Thanks

**Comment by afonsosantos** [comment]
UPDATE: When the password contains "@", it just doesn't work in the Web DJ.

**Comment by Vaalyn** [comment]
@SlvrEagle23 We should think about adding some password restrictions for the DJ accounts to prevent issues with the Web DJ caused by these characters.

**Comment by SlvrEagle23** [comment]
@Vaalyn Done; I switched the streamer_password filter to be a validator (so it explicitly tells the user to avoid certain characters) and expanded the avoided characters to include `,:@`. If we find any more, we can add them easily.

**Comment by afonsosantos** [comment]
Thanks for the solution!

**Comment by Vaalyn** [comment]
@SlvrEagle23 Nice =)

**Comment by afonsosantos** [comment]
> @Vaalyn Done; I switched the streamer_password filter to be a validator (so it explicitly tells the user to avoid certain characters) and expanded the avoided characters to include `,:@`. If we find any more, we can add them easily.

You should add `#`, it's not acepting that character in the password for the Streamer/DJ.

**Comment by SlvrEagle23** [comment]
@afonsosantos Done!
