### ISSUE TITLE
Stream randomly drops connection

### ISSUE THREAD

**Issue by bjarn** [AzuraCast/AzuraCast#1401]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 18.04

**Describe the bug**
When listening to the stream when the AutoDJ is running, it randomly stops playing. When pausing and starting the stream, it just continues playing. This happens on multiple devices.

What might be useful to know, it happens mostly when you're listening for 30 minutes. But might also occur when you just tuned in.

**To Reproduce**
1. Listen to the stream
2. Wait for it to drop the audio
3. Press pause in the web player
4. Press play in the web player
5. Stream is running fine again, but might stop in the next 30 minutes.

**Expected behavior**
Stream should play fine.

**Relevant Logs**

This is a part of the Liquidsoap log, I added a note where it dropped the connection:
```2019/04/04 19:09:47 [lang:3] AzuraCast Raw Response: annotate:title="The Fire",artist="The Faim",duration="201.",song_id="a387942e02764ce72744a7a7bf1acceb",media_id="4882",genre="4882",playlist_id="7":/var/azuracast/stations/epic/media/Singles/The Faim - The Fire.mp3
2019/04/04 19:09:47 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/epic/media/Singles/The Faim - The Fire.mp3".
2019/04/04 19:09:57 [epic_next_song:3] Finished with "/var/azuracast/stations/epic/media/Singles/Tom Walker - Just You And I.mp3".
2019/04/04 19:09:57 [epic_next_song:3] Prepared "/var/azuracast/stations/epic/media/Singles/The Faim - The Fire.mp3" (RID 9).
2019/04/04 19:09:57 [rotate_6506:3] Switch to map_metadata_6485 with forgetful transition.
2019/04/04 19:09:57 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/epic/media/Imaging/Epic Radio Sweeper 3.mp3".
2019/04/04 19:09:57 [playlist_imaging__sweepers:3] Finished with "/var/azuracast/stations/epic/media/Imaging/Epic Radio Sweeper 3.mp3".
2019/04/04 19:09:57 [playlist_imaging__sweepers:3] Prepared "/var/azuracast/stations/epic/media/Imaging/Epic Radio Sweeper 2.mp3" (RID 7).
2019/04/04 19:09:57 [rotate_6506:3] Switch to epic_autodj_fallback with forgetful transition.
2019/04/04 19:09:57 [smart_cross_6535:3] Analysis: -64.167834dB / -14.105659dB (3.78s / 3.27s)
2019/04/04 19:09:57 [smart_cross_6535:3] Not enough data for crossing.
< IT DROPPED THE CONNECTION SOMEWHERE AROUND HERE >
2019/04/04 19:10:04 [lang:3] AzuraCast Feedback Response: OK
2019/04/04 19:13:11 [lang:3] AzuraCast Raw Response: annotate:title="Without Me",artist="Halsey",duration="202.",song_id="42564751b4af128053bbe4cfef901d8d",media_id="4407",genre="4407",playlist_id="7":/var/azuracast/stations/epic/media/Singles/Halsey - Without Me.mp3
2019/04/04 19:13:11 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/epic/media/Singles/Halsey - Without Me.mp3".
```

Although these are completely different timestamps in the Icecast error log; it might be useful to know:
```[2019-04-04  10:59:27] WARN source/source_set_intro Cannot open intro for /epic.mp3 "/usr/local/share/icecast/web//epic.mp3": No such file or directory
[2019-04-04  10:59:27] WARN source/source_set_intro Cannot open intro for /epic.aac "/usr/local/share/icecast/web//epic.aac": No such file or directory
[2019-04-04  13:50:37] WARN source/source_read Nothing received on /epic.aac for 3 seconds
[2019-04-04  13:50:37] WARN source/source_read Nothing received on /epic.mp3 for 3 seconds
[2019-04-04  13:50:37] WARN source/source_read Nothing received on /epic.aac for 3 seconds
[2019-04-04  13:50:37] WARN source/source_read Nothing received on /epic.mp3 for 3 seconds
[2019-04-04  13:50:37] WARN source/source_read Nothing received on /epic.aac for 3 seconds
[2019-04-04  15:40:36] WARN source/source_read Nothing received on /epic.mp3 for 3 seconds
[2019-04-04  15:40:36] WARN source/source_read Nothing received on /epic.aac for 3 seconds```

**Additional context**
Good to know: I have this compressor running in the custom liquidsoap config:
```radio = compress(attack = 62.2, gain = 4.9, ratio = 4.9, release = 2146.9, threshold = -12.5, radio)```

**Comment by SlvrEagle23** [comment]
@bjarn Are you using the nginx port 80/443 web proxy? You may be running into a timeout issue with that proxy.

**Comment by bjarn** [comment]
@SlvrEagle23 Yes I am indeed! Do you have any suggestions on improving that?

**Comment by radiolize** [comment]
You may try turning off crossfade from stream preferences.

**Comment by SlvrEagle23** [comment]
@radiolize Crossfade has nothing to do with the timeout of the outbound signal.

@bjarn I just checked and the timeout on Docker's nginx configuration is 6 hours, rather than 30 minutes, so it's interesting that the connection would be dropping that quickly. Are you seeing anything in the logs, either on the client-side through the Network inspector panel or in AzuraCast's own `web` container logs, that indicates what's going on?

**Comment by bjarn** [comment]
@SlvrEagle23 I came across this error message in the console when the stream stopped: 
```
station.aac:1 Failed to load resource: net::ERR_CONNECTION_RESET
station.aac:1 Failed to load resource: net::ERR_SSL_VERSION_INTERFERENCE
```

The web logs seemed fine. Just some GET and POST entries and the sync tasks. Seemed fine.

**Comment by bjarn** [comment]
@SlvrEagle23 I think I have identified the issue. Since I disabled Cloudflare proxying the stream, it seems running perfectly fine.

**Comment by SlvrEagle23** [comment]
@bjarn Interesting. we don't seem to have any issues with our proxy via CloudFlare, but if disabling it resolves the issue, then that's good to hear it's not something further down in the infrastructure.
