### ISSUE TITLE
 Scheduler does not work "Once Per x Minutes: Play exactly once every x minutes."

### ISSUE THREAD

**Issue by lymych** [AzuraCast/AzuraCast#1402]
**Installation method**
Ubuntu Bare-metal ("Traditional") Installation

**Host OS (for Docker installations)**
Ubuntu 18.04

**Describe the bug**
Hello! I have a common playlist that is constantly playing and a playlist with ads that should sound every 5 minutes.

In the scheduler, I select the mode "Once Per x Minutes: Play exactly once every x minutes." and specify the function "Interrupt Other Songs". But the main playlist is not interrupted every 5 minutes and the ad starts only after the completion of several songs.

How can this problem be solved?

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**
![1і](https://user-images.githubusercontent.com/42175398/55583856-8f3f2080-572b-11e9-90e6-400480154433.png)
![2](https://user-images.githubusercontent.com/42175398/55583857-8fd7b700-572b-11e9-8d07-2e9e93bd1aab.png)

**Device(s):**
 - Device: Desktop
 - OS: ubuntu 18.04
 - Browser: chrome
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@lymych Thank you for the report. I found the cause of it, and was able to make the necessary changes to how we write Liquidsoap configuration.

"Once per x minutes" playlists that are set to interrupt existing audio should now do so properly.

**Comment by lymych** [comment]
@SlvrEagle23 How can I get the hotfix update?

**Comment by SlvrEagle23** [comment]
@lymych Just run the updater script normally (i.e. without any `--release` flag) and you'll get the latest rolling release version.

**Comment by lymych** [comment]
@SlvrEagle23 Thank you very much, everything works! There is only one problem when the scheduled play starts to start, the first 2 seconds the ad is superimposed on the song. How can this be fixed?

**Comment by SlvrEagle23** [comment]
@lymych I'm working upstream with the Liquidsoap team to figure out what's going on with fades doing that. That's also happening with live broadcasts.
