### ISSUE TITLE
Bandwidth Issue

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#1403]
Hello

I'm using a minimum droplet from digitalocean. This droplet has 1TB transfer. But as AzuraCast uses icecast and shoutcast, I would like to know if listeners' traffic is counting on my droplet. 

And if it's counting, how many total listening hours I can provide with that 1TB transfer limit and 1GB ram and 1vCPU on 128kbps, 192kbps and 320 kbps bitrate options.

thanks!

**Comment by SlvrEagle23** [comment]
@radiolize Listeners directly connecting to your server will count against your bandwidth limits, as they are directly transferring data out of your server across the Internet.

The bitrates are themselves indicative of how much bandwidth they're expected to consume on average: the 128kbps stream consumes 128 kilobits per second, which is 16 kilobytes per second, or 960 KB per minute, or 57.6 MB per listener per hour.

Given a 1TB quota, at 128kbps, one would expect to be able to provide approximately 18,200 listener hours (or 758 listener days) per month. This amounts to roughly an average of 25 listeners at all times of every day for the whole month.

Note that in DigitalOcean's case, bandwidth is pooled across all of the servers that you have, so if you have another server that uses far less load, like a basic web server, you can use its "spare" bandwidth to support the radio server's.
