### ISSUE TITLE
Stream does not start after port 8100

### ISSUE THREAD

**Issue by danielrodrigotest** [AzuraCast/AzuraCast#1404]
Hi, I have problems creating a new station from port 8100 or above. My question is How do I enable these ports?

![Screenshot 2019-04-05 at 9 17 46 AM](https://user-images.githubusercontent.com/40525323/55627105-c3463000-5783-11e9-8835-4e4355799201.png)
![Screenshot 2019-04-05 at 9 17 32 AM](https://user-images.githubusercontent.com/40525323/55627106-c3463000-5783-11e9-9cde-6c6c22d571e6.png)

**Installation method**

**Host OS (for Docker installations)**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
Hey, you can customize the ports exposed to the docker containers by following this [guide](https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#use-non-standard-ports).
