### ISSUE TITLE
Broadcast From Android App Error

### ISSUE THREAD

**Issue by danyalsaleemqureshi** [AzuraCast/AzuraCast#1406]
Hello I am Broadcasting from Android app, which is not showing any error but song play 8 to 10 sec then volume auto drops then again it become normal then again after some 8 to 10 sec same repeats and goes on, any Idea whats happening? Android app is broadcastmyself.

**Comment by Vaalyn** [comment]
Please have a look at your liquidsoap logs and post any errors or warnings here.

**Comment by danyalsaleemqureshi** [comment]
2019/04/05 16:12:20 [dummy:3] Source failed (no more tracks) stopping output...
2019/04/05 16:12:20 [chatcafe_next_song:3] Prepared "/var/azuracast/stations/chatcafe/media/tummile02-28www.songspk.info-29.mp3" (RID 3).
2019/04/05 16:12:20 [chatcafe_autodj_fallback:3] Switch to chatcafe_cue_cut with forgetful transition.
2019/04/05 16:12:20 [lang:3] Authenticating DJ: rj
2019/04/05 16:12:20 [lang:3] AzuraCast Feedback Response: OK
2019/04/05 16:12:20 [lang:3] AzuraCast DJ Auth Response: true
2019/04/05 16:12:21 [decoder:3] Method "MAD" accepted "audio/mpeg".
2019/04/05 16:12:21 [lang:3] DJ Source connected! [("icy-pub","1"), ("icy-name","N/A"), ("icy-notice1","Broadcastmyself/1.0"), ("User-Agent","Broadcastmyself/1.0"), ("icy-genre","N/A"), ("icy-br","128"), ("icy-url","N/A"), ("Content-Type","audio/mpeg")]
2019/04/05 16:12:21 [chatcafe_live_switch:3] Switch to chatcafe_live_fallback with transition.
2019/04/05 16:12:21 [lang:3] AzuraCast Live Connected Response: received
2019/04/05 16:12:21 [threads:3] Created thread "harbor source feeding" (2 total).
2019/04/05 16:12:21 [chatcafe_input_streamer:3] Decoding...
2019/04/05 16:12:21 [chatcafe_live_fallback:3] Switch to blank_6459.
2019/04/05 16:12:21 [lang:3] Authenticating DJ: shoutcast
2019/04/05 16:12:21 [lang:3] AzuraCast DJ Auth Response: true
2019/04/05 16:12:21 [chatcafe_input_streamer:3] New metadata chunk ? -- Rj X.
2019/04/05 16:12:26 [chatcafe_live_fallback:3] Switch to audio_to_stereo_6456 with transition.
2019/04/05 16:12:30 [chatcafe_live_fallback:3] Switch to blank_6459 with forgetful transition.
2019/04/05 16:12:30 [dummy:3] Source failed (no more tracks) stopping output...
2019/04/05 16:12:35 [chatcafe_live_fallback:3] Switch to audio_to_stereo_6456 with transition.
2019/04/05 16:12:40 [chatcafe_live_fallback:3] Switch to blank_6459 with forgetful transition.
2019/04/05 16:12:40 [dummy:3] Source failed (no more tracks) stopping output...
2019/04/05 16:12:45 [chatcafe_live_fallback:3] Switch to audio_to_stereo_6456 with transition.
2019/04/05 16:12:50 [chatcafe_live_fallback:3] Switch to blank_6459 with forgetful transition.
2019/04/05 16:12:50 [dummy:3] Source failed (no more tracks) stopping output...
2019/04/05 16:12:55 [chatcafe_live_fallback:3] Switch to audio_to_stereo_6456 with transition.
2019/04/05 16:13:00 [chatcafe_live_fallback:3] Switch to blank_6459 with forgetful transition.
2019/04/05 16:13:00 [dummy:3] Source failed (no more tracks) stopping output...
2019/04/05 16:13:05 [chatcafe_live_fallback:3] Switch to audio_to_stereo_6456 with transition.
2019/04/05 16:13:10 [chatcafe_live_fallback:3] Switch to blank_6459 with forgetful transition.
2019/04/05 16:13:10 [dummy:3] Source failed (no more tracks) stopping output...
2019/04/05 16:13:15 [chatcafe_live_fallback:3] Switch to audio_to_stereo_6456 with transition.
2019/04/05 16:13:20 [chatcafe_live_fallback:3] Switch to blank_6459 with forgetful transition.
2019/04/05 16:13:20 [dummy:3] Source failed (no more tracks) stopping output...
2019/04/05 16:13:25 [chatcafe_live_fallback:3] Switch to audio_to_stereo_6456 with transition.
2019/04/05 16:13:30 [chatcafe_live_fallback:3] Switch to blank_6459 with forgetful transition.
2019/04/05 16:13:30 [dummy:3] Source failed (no more tracks) stopping output...
2019/04/05 16:13:35 [chatcafe_live_fallback:3] Switch to audio_to_stereo_6456 with transition.
2019/04/05 16:13:40 [chatcafe_live_fallback:3] Switch to blank_6459 with forgetful transition.
2019/04/05 16:13:40 [dummy:3] Source failed (no more tracks) stopping output...
2019/04/05 16:13:45 [chatcafe_live_fallback:3] Switch to audio_to_stereo_6456 with transition.
2019/04/05 16:13:50 [chatcafe_live_fallback:3] Switch to blank_6459 with forgetful transition.
2019/04/05 16:13:50 [dummy:3] Source failed (no more tracks) stopping output...
2019/04/05 16:13:55 [chatcafe_live_fallback:3] Switch to audio_to_stereo_6456 with transition.
2019/04/05 16:14:00 [chatcafe_live_fallback:3] Switch to blank_6459 with forgetful transition.
2019/04/05 16:14:00 [dummy:3] Source failed (no more tracks) stopping output...
2019/04/05 16:14:27 [chatcafe_input_streamer:3] Timeout reached!
2019/04/05 16:14:27 [chatcafe_input_streamer:2] Error while reading from client: Timed out after waiting for 30.00 sec.
2019/04/05 16:14:27 [lang:3] DJ Source disconnected!
2019/04/05 16:14:27 [chatcafe_live_switch:3] Switch to chatcafe_autodj_fallback with transition.
2019/04/05 16:14:27 [lang:3] AzuraCast Live Disconnected Response: received
2019/04/05 16:14:27 [chatcafe_input_streamer:2] Feeding stopped: Mad.End_of_stream.
2019/04/05 16:14:27 [lang:3] DJ Source disconnected!
2019/04/05 16:14:27 [lang:3] AzuraCast Live Disconnected Response: received
2019/04/05 16:14:27 [threads:3] Thread "harbor source feeding" terminated (1 remaining).
2019/04/05 16:14:27 [lang:3] AzuraCast Feedback Response: OK

**Comment by Vaalyn** [comment]
You have a lot of `Source failed (no more tracks) stopping output...` in the log and also `Timeout reached!`. What kind of connection do you use when broadcasting via that app? It looks like your internet connection is really bad which leads to package loss, timeouts and so on.

**Comment by danyalsaleemqureshi** [comment]
Its Dsl Network but Everything Seems fine.

**Comment by Vaalyn** [comment]
DSL is a rather broad term, can you specify what bandwidth you have and maybe check if you have packet loss and what kind of latency you get.

**Comment by danyalsaleemqureshi** [comment]
Vaalyn I guess It was Bitrate Issue on 64 Kbps Its Working fine from mobile device. Thanks for Quick Response :)
