### ISSUE TITLE
Navigation controls not showing up correctly

### ISSUE THREAD

**Issue by afonsosantos** [AzuraCast/AzuraCast#1407]
**Installation method:**
Docker

Hi,

The pagination controls in the requests modal, at the public page, don't show correctly. I'm using Google Chrome.

![image](https://user-images.githubusercontent.com/46262740/55647491-b3efd280-57d5-11e9-9b1b-b877d92f2665.png)

I'm using the latest relase at the date.

**Comment by Vaalyn** [comment]
Still valid.

**Comment by afonsosantos** [comment]
Hey @Vaalyn , thanks for the attention. Since the computer that i was using to host AzuraCast is broken, i cannot tell if this issue is happening.

**Comment by Vaalyn** [comment]
@afonsosantos Don't worry about it, I've just added a comment saying that this issue is still valid so that the bot wont bother the issue again for some time.

**Comment by afonsosantos** [comment]
Thanks!

**Comment by SlvrEagle23** [comment]
I've updated the CSS on the Bootgrid to change the breakpoints so that the pagination will show up on its own dedicated line below a certain width, which should help with this issue significantly.

**Comment by afonsosantos** [comment]
Thanks for the fix, and sorry for the delay in the answer.

**Comment by afonsosantos** [comment]
I think it didn't update, using commit `#4eb2d3b ` and Google Chrome

![image](https://user-images.githubusercontent.com/46262740/62889222-d2904800-bd38-11e9-935b-73a8c2134654.png)
