### ISSUE TITLE
Geoblocking (Docker)

### ISSUE THREAD

**Issue by KuntzeM** [AzuraCast/AzuraCast#1408]
Hi,

is it possible to block countries (geoblocking) with AzuraCast?
I'm using the docker version. Is there an easy way?

Thanks in advanced!

Best regards
Mathias

**Comment by Vaalyn** [comment]
Geoblocking is a relatively hard problem. You need a good database of IP addresses to match against the blocked countries and often times ISPs buy IP addresses from other countries which leads to unintended blocking of legitimate users. Geoblocking can also be easily bypassed by using a VPN so depending on how restrictive you need it to be it can be even harder to implement. You could try using iptables in combination with MaxMinds GeoIP database for this. Here is one [tutorial](https://linoxide.com/linux-how-to/block-ips-countries-geoip-addons/) for something like that. I haven't tested this and can't guarantee that this will work for your use-case or how effective this is.

**Comment by KuntzeM** [comment]
Hi Vaalyn,

thank you for your fast answer!
I will read you linked tutorial.

Cheers
Mathias
