### ISSUE TITLE
How now to delete folders from playlists?

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#1409]
How now to delete folders from playlists?
Previously, the button was cleared and then it was possible to reassign folders to other playlists, now it is not there

**Comment by SlvrEagle23** [comment]
@susl16c The new "Set Playlists" button does both functions of the previous "Add to Playlist" and "Clear Playlists" buttons. If you select a folder, click "Set Playlists" and then leave no playlists checked, it will remove all existing playlists from files in the folder.

**Comment by Vaalyn** [comment]
Closing as the question was answered and acknowledged.
