### ISSUE TITLE
Public Page Not Working

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#1410]
Hello!

Installation method: docker

The public page is not streaming anymore:

https://my.radiolize.com/public/radio_antalya 

as player button's stream link is not accessible too. and that link is: 

https://my.radiolize.com:8000/radio.mp3

I updated the docker and checked encoding. there is no problem on stream at that link:

https://my.radiolize.com/radio/8000/radio.mp3

that links was working until 1 day ago. should I make subdomain settings from terminal? looks like a port problem but i'm not sure...

**Comment by radiolize** [comment]
as the public page is working with "my ip address:8000/radio.mp3" the problem is caused by my subdomain? but it was working until last night, and I was not made any changes on server. what should be happen and any idea how I can solve?

greetings!

**Comment by Vaalyn** [comment]
Hey, from the links you posted I can see that you are using a proxy service in front of your AzuraCast installation (cloudflare). You need to enable the `Use Web Proxy for Radio` option in the system settings.

**Comment by radiolize** [comment]
Thanks! solved. Also sorry for late reply, I was changing city :)
