### ISSUE TITLE
Login page background repeating in mobile devices

### ISSUE THREAD

**Issue by afonsosantos** [AzuraCast/AzuraCast#1414]
Hi!

The background image in the login page is repeating itself in mobile devices. I already discussed with @Vaalyn this matter in the AzuraCast's Slack: the CSS should be preventing this to happen.

```
background-size: cover;
background-attachment: fixed;
```

![screenshot_2019-04-08-14-30-14](https://user-images.githubusercontent.com/46262740/55732414-d838f280-5a13-11e9-8bfc-96bc7b353e5d.png)

I'm using an Android 4.4.2 device and Google Chrome version 73.0.3683.90

**Comment by Vaalyn** [comment]
I don't have an Android device but I've checked this on iOS Safari. There the background is correctly positioned fixed & covered.

**Comment by afonsosantos** [comment]
Just checked on my Android smartphone, and it's exactly like the image above.

**Comment by Vaalyn** [comment]
@afonsosantos This might be a device / browser specific bug. Chrome on macOS also doesn't have this problem neither does Firefox. Does the image still repeat when you switch the device orientation?

**Comment by afonsosantos** [comment]
Now, it repeats to the side

![Screenshot_2019-04-21-22-31-26](https://user-images.githubusercontent.com/46262740/56475799-6cc83980-6485-11e9-8256-9d40c06609f6.png)

**Comment by Vaalyn** [comment]
Can you check if adding a `background-repeat: no-repeat;` to the pages CSS does anything against this?

**Comment by afonsosantos** [comment]
If i pull the page down, to hide the URL field, it repeats the image, just like in the first image.

**Comment by SlvrEagle23** [comment]
There may not be anything we can do about this one, since it seems to be specific to browsers not wanting to do the thing we're telling it to do via CSS.

**Comment by Vaalyn** [comment]
Closing this issue as it seems to be very specific to an OS version + browser, which has no official support anymore. If this issue shows up on devices with an up to date version of Android that is still supported by Google please let us know.
