### ISSUE TITLE
Failed to prepare track: request not ready (Liquidsoap)

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1415]
Hi, 

a custom playlist suddenly failed to start at a specific time. It's been running stable for weeks now. After restarting the station the playlist started all right. This is the corresponding LS log: 

`2019/04/08 16:00:00 [playlist_xyz:1] Failed to prepare track: request not ready.`

Any idea? 

It's Azura 0.9.4.1, docker installation, on Ubuntu 16.

**Comment by SlvrEagle23** [comment]
@gammaw You said restarting fixed it? Did the playlist not have anything in it beforehand?

**Comment by gammaw** [comment]
@SlvrEagle23 the playlist was definitely not empty. The playlist was supposed to start at 4pm, it didn't (see error above). In the LS config the predicate for the playlist says 4-6PM. After radio restart (at around 4:15PM), the playlist started all right.

**Comment by SlvrEagle23** [comment]
@gammaw I have no idea what's causing this particular issue. This may be a question better suited for our friends upstream at Liquidsoap via their repository: https://github.com/savonet/liquidsoap

**Comment by gammaw** [comment]
@SlvrEagle23 FYI: the error happened again. Like you suggested, I posted it to Liquidsoap with a more detailed description: https://github.com/savonet/liquidsoap/issues/756

**Comment by gammaw** [comment]
@SlvrEagle23 this may be relevant for Azuracast too as it also uses `playlist.once` for the "Only Play One Track at Scheduled Time" option: https://github.com/savonet/liquidsoap/issues/735

**Comment by gammaw** [comment]
@SlvrEagle23 I found out what's causing the error: LS doesn't find the file because there has been changes (deletions) in the playlist and the new playlist hasn't been loaded (see https://github.com/AzuraCast/AzuraCast/issues/1269).

**Comment by SlvrEagle23** [comment]
@gammaw The latest update by @Vaalyn should fix that.
