### ISSUE TITLE
"exception is caused by a lack of memory or swap"

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1416]
Hi, 

because of performance inefficiencies (see https://github.com/AzuraCast/AzuraCast/issues/1288) we're experimenting with another VPS provider. Everything seems promising until I ran into this during an update today. It's a 1GB RAM instance which runs (in addition to Azuracast) a simple Wordpress site (also in docker). First, Wordpress was running during the Azura update and this when I got the error on the picture. Then I shut down the Wordpress docker container and the update succeeded. 

Am I on the limit of resources? Top shows (while Acura and Wordpress are both up) that I have around 100MB free memory. Does an update eat a lot of memory?

![image](https://user-images.githubusercontent.com/28865986/55755839-6f23a000-5a50-11e9-8389-a381d5b1772f.png)

![image](https://user-images.githubusercontent.com/28865986/55755930-abef9700-5a50-11e9-80a1-97eaf5a4175f.png)

Peter

**Comment by SlvrEagle23** [comment]
@gammaw The composer installation process is known to consume a fair amount of memory as it's running, but this should be short-lived, and the regular operation of the system shouldn't use as much memory.

You may want to consider setting up a swap space on your VPS using the instructions available here: https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

If this doesn't resolve your issue, then this may again simply be a matter of not having enough physical resources to support the demand you're putting on the VPS.
