### ISSUE TITLE
Cue Point Problem In just one channel

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#1418]
Traditional

Hello.

I noticed that in the new version there are a lot of problems regarding the songs requests by inserting them directly in the database, so I was forced to go back to the previous version 0.9.4

The problem?

Everything works properly, I have 7 channels and they work well, except the 1st. And as if in this channel the option "Cue point Start" and "Cue point End" do not exist, but only in this channel. If I go to change the song the numbers are there, but it's as if they weren't there. Help!

**Comment by SlvrEagle23** [comment]
@Ilario42 Do you mean this is only happening with song requests?

**Comment by Ilario42** [comment]
Hi @SlvrEagle23 

No, this only happens in channel number 1, in the others everything works fine.
I wait your answer

**Comment by SlvrEagle23** [comment]
@Ilario42 What's different about that station? What does its Liquidsoap configuration look like?

**Comment by Ilario42** [comment]
Hi @SlvrEagle23 

There is no difference, this is the problem ... Do you want my login details to check?

**Comment by Ilario42** [comment]
Hi @SlvrEagle23.

After so much head banging in the wall I finally managed to solve the problem.

For the less experienced a problem of these would have led to abandoning everything, but I did not give up, and after having dug a long time in the "config" directory of my station number 1, I noticed that in the "liquidsoap.liq" file there was no piece of code concerning the "cue_cut". I added the missing code and restarting the radio started working by cutting my music just as it used to. Hello :)

**Comment by Vaalyn** [comment]
That's strange. There is no condition surrounding the `cue_cut` generation code which could somehow exclude that from the `liquidsoap.liq` ([First](https://github.com/AzuraCast/AzuraCast/blob/3554d65c756e0bd5201f333e8639a247cdaf2505/src/Radio/Backend/Liquidsoap.php#L215) and [second](https://github.com/AzuraCast/AzuraCast/blob/3554d65c756e0bd5201f333e8639a247cdaf2505/src/Radio/Backend/Liquidsoap.php#L338) LS cue_cut code). How is it possible that everything got generated correctly except this part?

**Comment by Ilario42** [comment]
@Vaalyn I don't know, you should know this. However the strange thing is that in the other 6 channels the "code" was there. This was the missing code:
"dynamic = cue_cut(id="stationname_cue_cut", dynamic)"

Bye Bye

**Comment by Vaalyn** [comment]
@Ilario42 I think I know why this part was missing from your config. When we started a refactoring of the LS playlist config generation the `cue_cut` part was missing for some time and was brought back in 6591066. You would have just needed to trigger the writing of the configuration again to have it automatically brought back.
