### ISSUE TITLE
user accounts per radio station

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#142]
Hello,

Can you make it possible that i create user accounts that i speicify which radio station they can manage?
Like it is on centova cast. So a specific user account will only see the live stats of their radio station and can manage only their radio station.

**Comment by SlvrEagle23** [comment]
@surihost This is actually already possible...just create a new role with permissions only for a single station, then assign the new users to that role. :)

**Comment by surihost** [comment]
Hello,

I saw it, but still if i assign a role per station.After the user is logged in it shows the other stations also?

**Comment by SlvrEagle23** [comment]
@surihost If you don't assign them any global permissions, and only assign station-specific permissions, they can see that other stations exist on the server but they shouldn't be able to manage them at all.

**Comment by surihost** [comment]
Ok, but its always better to keep it seperate and dont let users see what stations i host.
So please make it that only a specific user can see only their radio station and nothing else of others and what i have on the server please.

**Comment by SlvrEagle23** [comment]
@surihost I will work on making AzuraCast friendlier for people hosting multiple stations for different clients. The original idea was that one AzuraCast instance == one group managing either a single or a group of their own stations, but it definitely could also be useful in the way you're using it.

Expect an update along these lines soon.

**Comment by surihost** [comment]
Thank you so much :) looking forward to it.

**Comment by Vicben** [comment]
Hi @SlvrEagle23, I just started working with AzuraCast recently and I'm wondering if this feature has been implemented as I look to put it to use.

**Comment by SlvrEagle23** [comment]
@Vicben Our role and permission management has been improved, but we still don't have a single "provision a station and a user to manage it" function. It's been suggested (as shown in this thread) and it's definitely on our bigger to-do list, but since it's a reseller-specific feature it's a lower priority than functionality that services all of our self-hosted users as well.
