### ISSUE TITLE
Player stops in browser, action needed for stream to continue

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1420]
Hi, 

a recurring issue is that the player (say on the public page, we use pretty much the same code and embed it on our radio website) just stops. One either needs to pause and play again on the player or reload the page and push play again. The error in the browser's console is this (see snapshot). 

Can it be due to some glitch in the network? Is there a way to protect against it? 

![image](https://user-images.githubusercontent.com/28865986/55822838-bd907780-5b00-11e9-9a2d-1b46d76bddfc.png)

**Comment by afonsosantos** [comment]
Yeah, it's happening here also...

![image](https://user-images.githubusercontent.com/46262740/55830918-eb2dee80-5b09-11e9-8817-ab449cef2b1e.png)

**Comment by SlvrEagle23** [comment]
@gammaw @afonsosantos These are issues with your browser and/or host operating system's network connectivity, not with AzuraCast.

We may be able to make some improvements to better handle the issue on our end, but this is just a normal consequence of the way HTML5 audio works; it doesn't have built-in continuity for connectivity errors.

**Comment by bjarn** [comment]
@gammaw @afonsosantos @SlvrEagle23 This issue might be related to mine; see #1401

**Comment by Vaalyn** [comment]
@SlvrEagle23 What I did when building my own player is adding an error handler that basically tries to restart the playback when the stream stopped for any reason. Maybe we can also add something like that in AzuraCasts player too. Maybe with some throttling like retry every 1s so as to not accidentally DoS the server.

**Comment by afonsosantos** [comment]
> @SlvrEagle23 What I did when building my own player is adding an error handler that basically tries to restart the playback when the stream stopped for any reason. Maybe we can also add something like that in AzuraCasts player too. Maybe with some throttling like retry every 1s so as to not accidentally DoS the server.

I think that @Vaalyn suggestion is needed to prevent the player from stopping. It's a cool feature to add to AzuraCast's player.

**Comment by gammaw** [comment]
@Vaalyn is it possible that you share your code to see the solution idea?

**Comment by Vaalyn** [comment]
@gammaw sure but I doubt it will be of much help since I'm using jPlayer for my own player and AzuraCast just uses the HTML5 audio element with some JS code so my code will not be compatible. Here is a [link](https://github.com/Vaalyn/BRG-Panel/blob/master/public/js/player.js#L9) to it anyways.

For AzuraCast we would need to register a listener to the [`<audio>`](https://developer.mozilla.org/de/docs/Web/HTML/Element/audio) elements [`error`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/error) event and trigger the `play()` method of the audio element in a `setTimeout()`.

**Comment by SlvrEagle23** [comment]
@Vaalyn So @CodeSteele and I were talking about this, and there's a valid question here: will browsers try to prevent that second "play" action because it wasn't initiated by a user, the same way they try to prevent autoplaying audio in the first place? Or does the first user interaction that hit "play" count for all future playback attempts on that same source?

I wouldn't want to invest a lot of time into this only to have browsers block it anyway!

**Comment by Vaalyn** [comment]
@SlvrEagle23 After reading some StackOverflow posts, [this](https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide) page from MDN and also from experience with my own player I'm reasonably sure that calling `play()` from the error handler will not be blocked by browsers on account of autoplay. The call to `play()` will be considered by browsers to be autoplay if the user has not interacted with the element before which means that triggering the `play()` from the same stack as the user initiated `play()` will not be blocked and as I understand JS the error handler is still part of that same stack.

**Comment by btoplak** [comment]
@gammaw your error ERR_NETWORK_CHANGED has nothing to do with the server or stream, it's your computer changing the network source/IP during the stream play. The reasons could be eg. that you have WiFi and LAN connection active in the same time, and computer jumps from one network to another. Or when router changes the external IP... 

But still I think it's worth mentioning why I had some issues with stream playing being interrupted: first I tried to proxy my streams through Cloudflare, but I had issues with stream stopping up and there in my desktop players (not browser one). This has definitely a lot to do with the way CF network works, with throwing traffic around his hundreds of datacenters depending of the load in each of them and other routing schemes.
When I turned off the CF and HTTPS on my streams, they work steady.

**Comment by SlvrEagle23** [comment]
I've implemented some changes to the player code that will detect "network changed" disconnections and station restarts and automatically attempt to reconnect the stream. This should help improve reliability of listener experience on the public players.

**Comment by gammaw** [comment]
@SlvrEagle23 we're using the new player now, I haven't seen disconnects in Desktop browsers since then. Thanks! It's different with mobile browsers. There, the player stops from time to time and if you switch to the browser app you see the browser reload (so it makes sense that the player stopped). Do you know why it's happening and how it could be improved? I'm sure it's not an issue with Azuracast (it seems to be an issue with mobile Internet etc.) but you may have a hint for us.

**Comment by ahmadabdolsaheb** [comment]
There seems to be the an issue withe browser throttling audio element in background tabs and it effects[ Azuracast's  default player](https://coderadio-admin.freecodecamp.org/public/coderadio).

Here is a simple html5 player that throttles (~30min) if placed on a chrome background tab depending on the browser's load: https://codepen.io/abdolsa/pen/dyVdgNM

Related Stackoverflow question: https://codepen.io/abdolsa/pen/dyVdgNM
