### ISSUE TITLE
Error after upgrade and upgrade failed

### ISSUE THREAD

**Issue by Marco-LB** [AzuraCast/AzuraCast#1422]
i have azuracast bare metal, and i follow the instruction for upgrade on: https://www.azuracast.com/install_traditional.html:
but the siste stop the update on this point and nothing work.
TASK [azuracast-radio : Clear OPAM directory] ***********************************************************************
ok: [localhost]

TASK [azuracast-radio : Add OPAM/OCaml Repository] ******************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 630F626C9FD811EBC19DF0955B2D0C5561707B09", "msg": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: keyserver receive failed: No keyserver available", "rc": 2, "stderr": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: keyserver receive failed: No keyserver available\n", "stderr_lines": ["Warning: apt-key output should not be parsed (stdout is not a terminal)", "gpg: keyserver receive failed: No keyserver available"], "stdout": "Executing: /tmp/apt-key-gpghome.wDfquhI2lj/gpg.1.sh --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 630F626C9FD811EBC19DF0955B2D0C5561707B09\n", "stdout_lines": ["Executing: /tmp/apt-key-gpghome.wDfquhI2lj/gpg.1.sh --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 630F626C9FD811EBC19DF0955B2D0C5561707B09"]}

RUNNING HANDLER [azuracast-user : send user notification] ***********************************************************

PLAY RECAP **********************************************************************************************************
localhost                  : ok=20   changed=5    unreachable=0    failed=1

**Comment by Vaalyn** [comment]
This seems to be either a DNS or network related problem. Can you ping `keyserver.ubuntu.com`? Is your server located behind a proxy? Is there a firewall that may be blocking the requests to `keyserver.ubuntu.com`?

**Comment by Marco-LB** [comment]
hi, 
thank for the answer, I can ping keyserver.ubuntu.com and i dont have a proxy, in the dedicated server it's installated only azuracast
