### ISSUE TITLE
NRJ indicator

### ISSUE THREAD

**Issue by tonimad** [AzuraCast/AzuraCast#1423]
Hi!

I would like to add indicator on the profile page of the radio station. In particular, I would like to indicate if the audio compressor is activated or deactivated.

Something like this:

```
<?php
if($backend_config_nrj == "1") {
echo 'NRJ is ON';
} else {
echo 'NRJ is OFF';
}
?>
```

How can I do this?

**Comment by Vaalyn** [comment]
There is currently no official way to do this. I think you'd need to write a plugin to do that. You can also create a feature request over at https://features.azuracast.com/ for us to add an indicator to the profile page.
