### ISSUE TITLE
missing url to json filw of now playing

### ISSUE THREAD

**Issue by xakdeveloper** [AzuraCast/AzuraCast#1424]
Hi sir,
I have to thank you for all of your great work, I have a issue to find the direct url pointing to json file of nowplaying, I need to fetch both mp3 and title and lyrics of the song in android app. I don't know where to pick file from http://my-station-url.example.com:8000/status.json ? or 
http://my-station-url.example.com:8000/playing.json.
I can see the json file here http://my-station-url.example.com/api/nowplaying/8 but can not pick it up. I reviewed the php code, but need to grab the json and save it in firebase.
Thanks in advaance

**Comment by SlvrEagle23** [comment]
@xakdeveloper Also, to answer your question further, that URL you're trying to get (`http://my-station-url.example.com/api/nowplaying/8`) is the correct one. That contains the JSON that you can save and use anywhere you want.

Even though the file isn't presented as a downloadable file, most browsers should still let you save it to your local disk, where it will still be fully valid JSON.

**Comment by xakdeveloper** [comment]
Thank you, 
I will find a way to pull lyrics into my app !
your work is a contribution to humanity
