### ISSUE TITLE
Impossible to create new port clone radio

### ISSUE THREAD

**Issue by skoja** [AzuraCast/AzuraCast#1426]
Once CLONE is created, NEW CLONE RADIO will not create a new port.
Create on the same port of the cloned radio.

Is this possible to correct?

**Comment by SlvrEagle23** [comment]
@skoja This is fixed as of the latest update to the codebase.

**Comment by skoja** [comment]
We have fresh VPS and installation from yesterday.

**Comment by Vaalyn** [comment]
@skoja after you've run an update you'll be on the newest version of AzuraCast were this bug is fixed.

**Comment by skoja** [comment]
Dear, 
1.Today we have installed a new version.
Clone radio is not working.Always create the same port.

2.
Playlist with jingle to be played after each song does not work.
