### ISSUE TITLE
Docker installation @Ubuntu 18 LTS not working anymore

### ISSUE THREAD

**Issue by btoplak** [AzuraCast/AzuraCast#1427]
**Installation method**
Docker

**Host O.S (for Docker installations)**
Ubuntu 18.04 LTS

**Describe the bug**
Installation via Docker is unsuccessful.
* During installation the error "Problem with dial: dial tcp 172.20.0.3:3306: connect: connection refused. Sleeping 1s" occurs
* after 10is same lines as above it ends with "Timeout after 20s waiting on dependencies to become available: [tcp://mariadb:3306 tcp://influxdb:8086]"
* after the installation seemingly finishes, the GUI is not accessible via port 80/443
* "docker-compose logs -f" endlessly prints "web_1       |  Problem with dial: dial tcp 172.19.0.2:3306: connect: connection refused. Sleeping 1s"
* the folder /var/azuracast does not exist

**To Reproduce**
By installing with a docker script.

**Expected behavior**
Installation should work

**Relevant Logs**
stations_1  | 2019-04-11 22:45:36,861 CRIT Supervisor running as root (no user in config file)
stations_1  | 2019-04-11 22:45:36,861 WARN No file matches via include "/var/azuracast/stations/*/config/supervisord.conf"
stations_1  | 2019-04-11 22:45:36,861 WARN No file matches via include "/etc/supervisor/conf.d/*"
stations_1  | 2019-04-11 22:45:37,022 INFO RPC interface 'supervisor' initialized
stations_1  | 2019-04-11 22:45:37,023 CRIT Server 'inet_http_server' running without any HTTP authentication checking
stations_1  | 2019-04-11 22:45:37,023 INFO RPC interface 'supervisor' initialized
stations_1  | 2019-04-11 22:45:37,023 CRIT Server 'unix_http_server' running without any HTTP authentication checking
stations_1  | 2019-04-11 22:45:37,023 INFO supervisord started with pid 6
web_1       | 2019/04/11 22:49:04 Problem with dial: dial tcp 172.19.0.2:3306: connect: connection refused. Sleeping 1s
web_1       | 2019/04/11 22:49:05 Problem with dial: dial tcp 172.19.0.2:3306: connect: connection refused. Sleeping 1s
web_1       | 2019/04/11 22:49:06 Problem with dial: dial tcp 172.19.0.2:3306: connect: connection refused. Sleeping 1s
web_1       | 2019/04/11 22:49:07 Problem with dial: dial tcp 172.19.0.2:3306: connect: connection refused. Sleeping 1s
web_1       | 2019/04/11 22:49:08 Problem with dial: dial tcp 172.19.0.2:3306: connect: connection refused. Sleeping 1s
web_1       | 2019/04/11 22:49:09 Problem with dial: dial tcp 172.19.0.2:3306: connect: connection refused. Sleeping 1s
web_1       | 2019/04/11 22:49:10 Problem with dial: dial tcp 172.19.0.2:3306: connect: connection refused. Sleeping 1s

**Screenshots**
https://i.imgur.com/7lI41bI.png

**Comment by afonsosantos** [comment]
Hi,

Create a `docker-compose.override.yml` in the same directory as `docker.sh` and add the following lines to it:

```
version: '2.2'

services:
    web:
        entrypoint:
            - dockerize
            - -wait
            - tcp://mariadb:3306
            - -wait
            - tcp://influxdb:8086
            - -timeout
            - 60s
        command: ["/sbin/my_init"]
```

This will increase the timeout to 60s. It was happening to me also, and with the help of @Vaalyn i solved it using the lines above.

**Comment by SlvrEagle23** [comment]
@btoplak We recently modified our Docker setup to install the AzuraCast DB prior to spinning up the MariaDB container, which makes it sometimes take longer than the previous timeout, particularly on slower computers.

I've rebuilt the `web` container with an updated, longer timeout period. This should help keep this problem from completely stalling the installation process.

**Comment by gammaw** [comment]
@btoplak we had something similar. This thread may help for you too: https://github.com/AzuraCast/AzuraCast/issues/1288

@SlvrEagle23 can you refer to the exact commit?

**Comment by SlvrEagle23** [comment]
@gammaw https://github.com/AzuraCast/docker-azuracast-web-v2/commit/f0dfcf28c7ccd29d17fdee65fefa9ef259235683

**Comment by btoplak** [comment]
**@afonsosantos** Thank you for pointing me out to a right direction. But I had to put the timeout to 360 seconds, it took almost 2 minutes for MariaDB Docker to get ready.

**@SlvrEagle23** FYI: I am installing to a i7 4th generation with 32GB RAM, so I guess that cannot be classified as a slow computer. And it took almost an hour to install the whole database migration (the SQL queries)!
While I had no problem whatsoever to install Azura on a 2-core VPS cheap $4/mth just a month ago. 

So by my example I'd say something has dramatically changed to worse. My feeling is that MariaDB docker has too limited/scarce resources. But I am currently a Docker beginner, so I can't check it more closely.

If you need some more logs, or even an access to the machine just let me know.

**Comment by afonsosantos** [comment]
@btoplak You're welcome!

> While I had no problem whatsoever to install Azura on a 2-core VPS cheap $4/mth just a month ago.

What's the company of this VPS? I'm looking for a cheap hosting for AzuraCast, and as you are providing good feedback about it...

**Comment by Vaalyn** [comment]
@btoplak That's indeed quite strange. With such high specs your installation / db migration should definitely not take THAT long. Do you know how the servers load looked like while this was running? Also are you installing on an SSD or HDD and is something else running on that server?

There are no resource limits on the containers themselves so they can utilize your whole server.

**Comment by SlvrEagle23** [comment]
@btoplak Almost an _hour_? No, that's not normal. I don't know what's gone wrong in your particular setup, but that entire process should take less than a _minute_ to complete on the worst hardware.

That is, unless you have an existing database with a few million records and are running migrations from a version a few years old, but that's about the only thing that would cause that...

**Comment by btoplak** [comment]
Guys. thanks for a fast feedback.

It was a clean Ubuntu 18 LTS install, nothing previously installed on it.
It is a 2x 3TB HDD, with LVM in mdraid soft RAID and btrfs filesystem.

What I'm now noticing, I have deleted the only test station created during the setup wizard, just to realize the CPU load is still over 1.2+, so I was wondering what is still constantly eating one thread. And it is - guess what, MySQL processes. This was captured in "iotop" https://i.imgur.com/kmtcE6e.png and "htop" https://i.imgur.com/lnctEpR.png ... and NO station active whatsoever.

And yes, on the VPS-es I used for testing last few weeks the installation went quick like a breeze. So this situation has left me a bit stunned.

Well, I am ready to delete it all and install again. Maybe some package got corrupted, I don't know...
Now I have to find how to make sure I have deleted everything, even the Docker images. To have a full fresh start. Apart of "./docker.sh uninstall"

**Comment by btoplak** [comment]
> @btoplak You're welcome!
> 
> > While I had no problem whatsoever to install Azura on a 2-core VPS cheap $4/mth just a month ago.
> 
> What's the company of this VPS? I'm looking for a cheap hosting for AzuraCast, and as you are providing good feedback about it...

if you plan to host in Europe it's Scaleway.com. You can't get something better for so cheap. For a decent low-budget I suggest bare-metal model C2S and local SSD nfs-mounted . It's actually a small 4-core Atom machine. But works like a charm, check the screenshot of zeroish load with 4 stations runnung full time on Auto-DJ https://i.imgur.com/YsApUoj.png

And now compare that Atom load with the load on a fresh i7 I uploaded above :sob:

**Comment by afonsosantos** [comment]
> > @btoplak You're welcome!
> > > While I had no problem whatsoever to install Azura on a 2-core VPS cheap $4/mth just a month ago.
> > 
> > 
> > What's the company of this VPS? I'm looking for a cheap hosting for AzuraCast, and as you are providing good feedback about it...
> 
> if you plan to host in Europe it's Scaleway.com. You can't get something better for so cheap. For a decent low-budget I suggest bare-metal model C2S and local SSD nfs-mounted . It's actually a small 4-core Atom machine. But works like a charm, check the screenshot of zeroish load with 4 stations runnung full time on Auto-DJ https://i.imgur.com/YsApUoj.png
> 
> And now compare that Atom load with the load on a fresh i7 I uploaded above 😭

Thanks, their prices are just amazing, i think i'll order a VPS there. I think i'll go  with the Baremetal C1, it's enough for my use.

**Comment by btoplak** [comment]
> > > @btoplak You're welcome!
> > > > While I had no problem whatsoever to install Azura on a 2-core VPS cheap $4/mth just a month ago.
> > > 
> > > 
> > > What's the company of this VPS? I'm looking for a cheap hosting for AzuraCast, and as you are providing good feedback about it...
> > 
> > 
> > if you plan to host in Europe it's Scaleway.com. You can't get something better for so cheap. For a decent low-budget I suggest bare-metal model C2S and local SSD nfs-mounted . It's actually a small 4-core Atom machine. But works like a charm, check the screenshot of zeroish load with 4 stations runnung full time on Auto-DJ https://i.imgur.com/YsApUoj.png
> > And now compare that Atom load with the load on a fresh i7 I uploaded above sob
> 
> Thanks, their prices are just amazing, i think i'll order a VPS there. I think i'll go with the Baremetal C1, it's enough for my use.
You can't use C1, it's ARM arch which isn't supported by AzuraCast yet (AFAIK)... otherwise, their systems and speed are impressive, but the support is poor: be warned. Good luck!

**Comment by afonsosantos** [comment]
> > > > @btoplak You're welcome!
> > > > > While I had no problem whatsoever to install Azura on a 2-core VPS cheap $4/mth just a month ago.
> > > > 
> > > > 
> > > > What's the company of this VPS? I'm looking for a cheap hosting for AzuraCast, and as you are providing good feedback about it...
> > > 
> > > 
> > > if you plan to host in Europe it's Scaleway.com. You can't get something better for so cheap. For a decent low-budget I suggest bare-metal model C2S and local SSD nfs-mounted . It's actually a small 4-core Atom machine. But works like a charm, check the screenshot of zeroish load with 4 stations runnung full time on Auto-DJ https://i.imgur.com/YsApUoj.png
> > > And now compare that Atom load with the load on a fresh i7 I uploaded above sob
> > 
> > 
> > Thanks, their prices are just amazing, i think i'll order a VPS there. I think i'll go with the Baremetal C1, it's enough for my use.
> 
> You can't use C1, it's ARM arch which isn't supported by AzuraCast yet (AFAIK)... otherwise, their systems and speed are impressive, but the support is poor: be warned. Good luck!

Damn, i think i'll choose instead the **Development** servers

**Comment by btoplak** [comment]
> Damn, i think i'll choose instead the **Development** servers
Another suggestion for real cheap servers, those are all full bare metal dedicated ones, just limited to 100Mbit uplink and only one HDD: https://www.kimsufi.com/en/servers.xml ... hope you find something

**Comment by afonsosantos** [comment]
Thanks, i will take a look at that!

**Comment by btoplak** [comment]
> 
> Well, I am ready to delete it all and install again. Maybe some package got corrupted, I don't know...
> Now I have to find how to make sure I have deleted everything, even the Docker images. To have a full fresh start. Apart of "./docker.sh uninstall"

It's the same ... you can check on a screencast I just made https://photos.app.goo.gl/VafCyD9b7HC4HWyG8 ... and the queries are still running. (Btw. why migration since 2016? Can't a much fresher full DB structure dump be added?)

If dev's have the time and wish to check the situation I'd be more than happy to help.

**Comment by btoplak** [comment]
Let me share a post-festum with you.

The repeated try on Friday did not yield any better result, a hour long installation... 

So I decided to make some overall system benchmarks to find out if something is wrong. And the Phorinox test suite gave me a hint - although the HDD speed was within expected values for a rotating disk drive, the CPU was using a kernel governor directive set to "powersave". I changed that to "performance". And voila, installation went through in a minute or so.

That's a hint to others, check if your data center is by default throttling your CPU to save on electric power.

**Comment by Vaalyn** [comment]
Wow interesting. I've never encountered a datacenter that throttles the CPUs by setting it to a powersave mode before.

**Comment by btoplak** [comment]
> Wow interesting. I've never encountered a datacenter that throttles the CPUs by setting it to a powersave mode before.

Uhh do I hate them now. I found they did that to my other dev server I have with them, for more than a year... to whom can I charge this 7ish hours of frustration on testing why...

**Comment by Vaalyn** [comment]
IANAL but you can check if the contract with them includes an SLA. You may be entitled to a refund.

**Comment by btoplak** [comment]
> IANAL but you can check if the contract with them includes an SLA. You may be entitled to a refund.

Hehehehehe ... dear friend, I guess you didn't deal with DCs so much as I did.
It's hard to get refund for much larger issues than this. With some even for issues which are too obvious. Eg. for serveral days we had several servers having 5 Mbps throughput instead of normal 300-400 Mbps. And the reply on a refund request was "well, you know, there was no service interruption".
I am working with data centers around the world for over 15 years now and I can promise you there isn't a single one which would refund for such a thing. They cover themselves with tens of contract articles that entitle them to turn anything off what they like with a pretend it is a risk of some kind.
And on the other hand, the power bills are the biggest costs of operation for any DC, so it's kind of logical such a sneaky approach.

**Comment by afonsosantos** [comment]
@btoplak That's bad... I hope OVH doesn't do that, they are my 1st option for DC.

**Comment by btoplak** [comment]
> @btoplak That's bad... I hope OVH doesn't do that, they are my 1st option for DC.

they're the biggest one in EU, with one of the poorest support I know. If the server works - you have good hardware and stable speed. But when the things don't work - you're on your own for hours or even days without support reply. That's my team's experience working with them for 8 years now...

And you can easily check the frequency governor setting on your machine: `cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor`

**Comment by afonsosantos** [comment]
> > @btoplak That's bad... I hope OVH doesn't do that, they are my 1st option for DC.
> 
> they're the biggest one in EU, with one of the poorest support I know. If the server works - you have good hardware and stable speed. But when the things don't work - you're on your own for hours or even days without support reply. That's my team's experience working with them for 8 years now...
> 
> And you can easily check the frequency governor setting on your machine:
> `cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor` ... it should say "performance" in best case, "powersave" in worst like mine up until now.

Do you know how to check it on Debian?

**Comment by SlvrEagle23** [comment]
> ... and the queries are still running. (Btw. why migration since 2016? Can't a much fresher full DB structure dump be added?)

@btoplak On Docker, we do indeed load a database dump from just a few weeks ago (the latest release build's DB schema), which cuts out something like 3 years of DB migrations. They still exist in the database in step-by-step form because we do indeed have users who have migrated all the way from a 2016 version of AzuraCast to a modern one, and we want that upgrade process to still be smooth.

**Comment by btoplak** [comment]
> > ... and the queries are still running. (Btw. why migration since 2016? Can't a much fresher full DB structure dump be added?)
> 
> @btoplak On Docker, we do indeed load a database dump from just a few weeks ago (the latest release build's DB schema), which cuts out something like 3 years of DB migrations. They still exist in the database in step-by-step form because we do indeed have users who have migrated all the way from a 2016 version of AzuraCast to a modern one, and we want that upgrade process to still be smooth.

@SlvrEagle23 yes, sure, I completely understand the need for migration steps. But those were running when I was making a fresh install (for some reason). Maybe there is a bug on the way it determines if it's a new installation vs an update?
Maybe there are some leftovers after i did `./docker.sh uninstall`

**Comment by btoplak** [comment]
> > > @btoplak That's bad... I hope OVH doesn't do that, they are my 1st option for DC.
> > 
> > 
> > they're the biggest one in EU, with one of the poorest support I know. If the server works - you have good hardware and stable speed. But when the things don't work - you're on your own for hours or even days without support reply. That's my team's experience working with them for 8 years now...
> > And you can easily check the frequency governor setting on your machine:
> > `cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor` ... it should say "performance" in best case, "powersave" in worst like mine up until now.
> 
> Do you know how to check it on Debian?

That one should work on Debian, just have run it on Stretch

**Comment by afonsosantos** [comment]
> > > And you can easily check the frequency governor setting on your machine:
> > > `cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor` ... it should say "performance" in best case, "powersave" in worst like mine up until now.
> > 
> > 
> > Do you know how to check it on Debian?
> 
> That one should work on Debian, I just kicked it on Stretch for test, works

Not working...
![image](https://user-images.githubusercontent.com/46262740/56097899-16418500-5ef2-11e9-85de-ede0eac178c8.png)

**Comment by btoplak** [comment]
> > > > And you can easily check the frequency governor setting on your machine:
> > > > `cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor` ... it should say "performance" in best case, "powersave" in worst like mine up until now.
> > > 
> > > 
> > > Do you know how to check it on Debian?
> > 
> > 
> > That one should work on Debian, I just kicked it on Stretch for test, works
> 
> Not working...
> ![image](https://user-images.githubusercontent.com/46262740/56097899-16418500-5ef2-11e9-85de-ede0eac178c8.png)

Are you in a VPS?
What does `cat /sys/devices/system/cpu/` say?

**Comment by afonsosantos** [comment]
> > > > > And you can easily check the frequency governor setting on your machine:
> > > > > `cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor` ... it should say "performance" in best case, "powersave" in worst like mine up until now.
> > > > 
> > > > 
> > > > Do you know how to check it on Debian?
> > > 
> > > 
> > > That one should work on Debian, I just kicked it on Stretch for test, works
> > 
> > 
> > Not working...
> > ![image](https://user-images.githubusercontent.com/46262740/56097899-16418500-5ef2-11e9-85de-ede0eac178c8.png)
> 
> Are you in a VPS?
> What does `cat /sys/devices/system/cpu/` say?

No, i'm running a VM with Debian x64.
`cat /sys/devices/system/cpu/` shows 
![image](https://user-images.githubusercontent.com/46262740/56098013-8dc3e400-5ef3-11e9-8cd0-37e486970fd7.png)
(it's a directory)

**Comment by btoplak** [comment]
Yeah, with VPS I meant a virtualized system. 
The directory, yes, with each thread as a separate folder etc.... Now it only depends on what kind of virtualization it is that you have, but when virtualized you can't tune much anyway, sorry

**Comment by afonsosantos** [comment]
> Yeah, with VPS I meant a virtualized system.
> The directory, yes, with each thread as a separate folder etc.... Now it only depends on what kind of virtualization it is that you have, but when virtualized you can't tune much anyway, sorry

Fine, i was just curious about changing that to see the result. Thanks anyway!
