### ISSUE TITLE
Language Settings and Turkish Translation

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#1429]
Hey!

It would be nice if we could select station language while creating their stations as admin, so station owner may use the panel with his/her own language if there is translation.

Also, I would love to make Turkish translation at my free times to contribution. If i can, how?

Greetings!

**Comment by Vaalyn** [comment]
We are using [Crowdin](https://crowdin.com/project/azuracast) to translate AzuraCast. If you like to contribute by translating the interface into Turkish just create an account and as soon as we add the language to the Crowdin project you can start suggesting translations. After the translations are approved we can merge them into the project.

**Comment by radiolize** [comment]
Nice! I'll do when I find some break. Thanks.

**Comment by Vaalyn** [comment]
@radiolize Regarding the feature request of chosing the default language for a station, would you mind creating a feature request for that over at https://features.azuracast.com ?

I'll close this issue now as the original question has been answered and feature requests are handled by the site I linked.

**Comment by ogrenci01** [comment]
Hi Bro. I think I translate AzuraCast for Turkish language. Please can you add Turkish language repo? I will translate to it at now. Thanks ;)
