### ISSUE TITLE
Azuracast panel is completely inaccessible

### ISSUE THREAD

**Issue by dereksys** [AzuraCast/AzuraCast#1432]
Traditional installation
Ubuntu 18.04

Hi,

I installed Azuracast a month ago on my server. During today, access to the panel has stopped working. If I try accessing, the website is not available. However, the server responds correctly. If I access via ssh, and I request a "top" command, I can see how liquidsoap is active.

Everything seems to work correctly, but the website is completely inaccessible.

**Comment by dereksys** [comment]
I think I have found the problem.

The panel is visible but after a while, the panel is no longer accessible, and as I said before, the website is no longer available.

I have accessed via ssh to my server. I have restarted the components that Azuracast uses, one by one.

Once Nginx restarts, nothing happens: The problem continues.

But when I try to restart MariaDB:

`service mysql restart`

... then, the website is again accessible.

For some reason, MariaDB is frequently down on my server.

My question is: Is there any way to restart MariaDB automatically if it fails again?

**Comment by SlvrEagle23** [comment]
@dereksys The usual cause for this is because MariaDB is running out of available RAM and being shut down as a result.

One option is to add a swap space to help with memory usage: https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-18-04

Another is to expand your server's resources, particularly overall available RAM, so this isn't necessary to do. This is especially advised on hosting providers that use SSDs, where swap space may cause trouble.

**Comment by btoplak** [comment]
If you're on a system scarce with RAM it is indeed best to fine tune how much RAM the MariaDB (a MySQL fork) could use, to prevent memory overuse. Some hints:
https://tech.labelleassiette.com/how-to-reduce-the-memory-usage-of-mysql-61ea7d1a9bd

The best MySQL and it's fork's tuning script that I know of is http://mysqltuner.pl ... Aside of maximum possible memory usage according your current configuration, it will give you some other useful hints on what else you can tune. But beware, it expects some deeper MySQL internals knowledge, so don't just take all suggestions as granted before doing your own research what each config keyword means....

**Comment by dereksys** [comment]
@SlvrEagle23 @btoplak Thanks for your help.

I suppose this is important for the rest of the user, too. So I would like to determine the source of the problem.

This is an dedicated server, and the characteristics are the following:

Intel Xeon E5-1650V2 (3.50GHz-3.90GHz / 6 cores / Caché 12 MB)
RAM: 64GB DDR3 ECC / HDD: 4TB Enterprise HDD)
Azuracast Bare installation (traditional) with Ubuntu 18.04. It's the only thing on the server.

According to what you are saying, it is a problem of Mysql, which consumes a lot of memory.

If I check the memory: free -h

```
              total        used        free      shared  buff/cache   available
Mem:     62G         39G        9.4G         13M         14G         23G
Swap:     63G          0B         63G
```

How is it possible that is using 39G !!??

Ok, let me execute the command top:

```
top - 19:45:39 up 12:05,  1 user,  load average: 1.51, 1.69, 1.66
Tasks: 1299 total,   1 running, 1217 sleeping,   0 stopped,   0 zombie
%Cpu(s):  8.6 us,  1.5 sy,  0.0 ni, 87.4 id,  2.1 wa,  0.0 hi,  0.3 si,  0.0 st
KiB Mem : 65935288 total,  9773104 free, 41069632 used, 15092552 buff/cache
KiB Swap: 67043324 total, 67043324 free, 0 used. 24184368 avail Mem
```

Process:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 2148 azuraca+  20   0  659544  55688  14000 S   9.2  0.1  58:57.50 liquidsoap
 2184 azuraca+  20   0  733340  53260  14056 S   8.9  0.1  63:45.69 liquidsoap
 2146 azuraca+  20   0  669668  64432  14636 S   8.2  0.1  47:28.26 liquidsoap
 2159 azuraca+  20   0  657300  67136  14516 S   8.2  0.1  59:51.13 liquidsoap (...)
```

And now, inside top: u -> mysql:

```
  PID USER      PR  NI    VIRT    RES         SHR S  %CPU   %MEM     TIME+ COMMAND
  652 mysql     20   0 1801816 115044  18868 S   6.2        0.2           0:00.19 mysqld
```
Mysql memory: 0.2

And now, inside top: SHIFT+m:

```
  PID USER          PR  NI    VIRT    RES       SHR S    %CPU  %MEM     TIME+ COMMAND
 3528 azuraca+  20   0 1223544 901444  23288 S   0.3     1.4            0:20.91 php
21266 azuraca+  20   0  659804 254056  23268 S   0.0     0.4            0:03.86 php
20864 azuraca+  20   0  656580 251392  23512 S   0.0     0.4            0:03.81 php
```

Now, my file my.cnf (mysql config):

```
[client]
default-character-set = utf8mb4

[mysql]
default-character-set = utf8mb4

[mysqld]
bind-address=*
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
```

According to the previous information, I do not understand the origin of the consumption of 39GB of RAM.  According to this information, mysql is not consuming a large amount of RAM. It is right?

I'm a little confused. What is your opinion?

**Comment by dereksys** [comment]
@btoplak 
> If you're on a system scarce with RAM it is indeed best to fine tune how much RAM the MariaDB (a MySQL fork) could use, to prevent memory overuse. Some hints:
> https://tech.labelleassiette.com/how-to-reduce-the-memory-usage-of-mysql-61ea7d1a9bd
> 
> The best MySQL and it's fork's tuning script that I know of is http://mysqltuner.pl ... Aside of maximum possible memory usage according your current configuration, it will give you some other useful hints on what else you can tune. But beware, it expects some deeper MySQL internals knowledge, so don't just take all suggestions as granted before doing your own research what each config keyword means....

If I limit the memory that Mysql can use, then the problem will continue, since the memory used by mysql will not be enough. And again, the panel will not be accessible and I will need to execute the restart command. It is right?

**Comment by btoplak** [comment]
Oh, your machine isn't scarce with RAM. :rofl:  

MariaDB can eat a lot of RAM if you have big datasets. How big is your "azuracast" database now anyway? Do you have a lot of audio files and channels?

Try running  `mysql -u azuracast -p -e 'SHOW ENGINE INNODB STATUS;'` within your DB docker and search for the section “BUFFER POOL AND MEMORY“.

The MySQL Tuner script (I gave you a link to above) should also clearly state what was the max RAM usage of your system, current usage, and possible usage. Can you post that part of the report too?

**Comment by dereksys** [comment]
@btoplak 
> Try running `mysql -u azuracast -p -e 'SHOW ENGINE INNODB STATUS;'` within your DB docker and search for the section “BUFFER POOL AND MEMORY“, you can post it here.

This execution is asking me for a password. Do you know in which Azuracast file this password is located?

**Comment by dereksys** [comment]
@btoplak 
> The MySQL Tuner script (I gave you a link to above) should also clearly state what was the max RAM usage of your system, current usage, and possible usage. Can you post that part of the report too?

I want to do this, but I'm a bit limited with my technical knowledge.

Please, can you tell me, step by step, how should I do with this script? And I will do it on my server.

**Comment by btoplak** [comment]
> @btoplak
> 
> > Try running `mysql -u azuracast -p -e 'SHOW ENGINE INNODB STATUS;'` within your DB docker and search for the section “BUFFER POOL AND MEMORY“, you can post it here.
> 
> This execution is asking me for a password. Do you know in which Azuracast file this password is located?
cat /root/azuracast.env

**Comment by dereksys** [comment]
> > @btoplak
> > > Try running `mysql -u azuracast -p -e 'SHOW ENGINE INNODB STATUS;'` within your DB docker and search for the section “BUFFER POOL AND MEMORY“, you can post it here.
> > 
> > 
> > This execution is asking me for a password. Do you know in which Azuracast file this password is located?
> 
> cat /root/azuracast.env

cat: /root/azuracast.env: No such file or directory

**Comment by btoplak** [comment]
> @btoplak
> 
> > The MySQL Tuner script (I gave you a link to above) should also clearly state what was the max RAM usage of your system, current usage, and possible usage. Can you post that part of the report too?
> 
> I want to do this, but I'm a bit limited with my technical knowledge.
> 
> Please, can you tell me, step by step, how should I do with this script? And I will do it on my server.

https://github.com/major/MySQLTuner-perl
hope that helps

**Comment by btoplak** [comment]
> > > @btoplak
> > > > Try running `mysql -u azuracast -p -e 'SHOW ENGINE INNODB STATUS;'` within your DB docker and search for the section “BUFFER POOL AND MEMORY“, you can post it here.
> > > 
> > > 
> > > This execution is asking me for a password. Do you know in which Azuracast file this password is located?
> > 
> > 
> > cat /root/azuracast.env
> 
> cat: /root/azuracast.env: No such file or directory

then try `cat ~/azuracast.env` with the user you used for the installation

**Comment by dereksys** [comment]
cat: /root/azuracast.env: No such file or directory
(with the installation user)

Remember, my installation is traditional.

I found this file in:

/var/azuracast/www/azuracast.dev.env

Inside:

```
# The password AzuraCast will use to connect to the database.
# By default, the database is not exposed to the Internet at all and this is only
#   an internal password used by the service itself.
# Default: azur4c457
MYSQL_PASSWORD=azur4c457
```
But this password does not seem to be correct. I am going to follow the steps of the recommended script.

**Comment by dereksys** [comment]
@btoplak Thanks! I have this script installed. I will now wait a few hours, before executing it. The developer recommends waiting a few hours.

**Comment by btoplak** [comment]
Yeah, sorry, I oversaw that you're not using dockers.

> @btoplak Thanks! I have this script installed. I will now wait a few hours, before executing it. The developer recommends waiting a few hours.

Yes, if you recently restarted MySQL you have to wait for at least 24hrs to get more realistic usage data for a proper tuning suggestions. Still, you can post the current memory related output.

**Comment by dereksys** [comment]
Perfect, I'll be posting the information in a few hours. Thank you!

**Comment by dereksys** [comment]
@SlvrEagle23 @btoplak 
Here is the result:

![509395](https://user-images.githubusercontent.com/49600256/56102809-b10c8480-5f2f-11e9-8287-b26c2b1851d0.jpg)

**Comment by Vaalyn** [comment]
@dereksys You may want to take a look at the mysql/mariadb error log in `/var/log/mysql/error.log` to check why the database was shutdown.

**Comment by dereksys** [comment]
Hi @Vaalyn 

In /var/log/mysql/ there are no files with the name error.log

**Comment by btoplak** [comment]
According to the mysqltuner report, it seems that the MariaDB didn't use all that much RAM (since last reboot that is). And the various memory usage limits are quite low, they can be tuned up a bit. Max memory usage could be 856.4 MB, and your instance used all of that at some point. 

And your InnoDB dataset is only 80MB, which is not big at all.

You can safely start with the recommended optimizations as listed at the bottom.

As suggested by the script, importing and activating Performance schema could enable you to gather more of the useful data. Feel free to do it if you want more insight.

Your instance has an error log configured "/var/log/mysql/via.err" but it can't write to that file for some reason. You should check that and fix it, so you get all errors logged.

**Comment by dereksys** [comment]
@btoplak 

I'm grateful for your help, really.

I have enabled the mysql error.log file, and after a few seconds, I have had to delete it, because the size of this file is increasing.

I have uploaded the error.log file to Wetransfer:
[https://we.tl/t-BgcfohHA75](https://we.tl/t-BgcfohHA75)

**Comment by Vaalyn** [comment]
@dereksys It seems like you have the [MariaDB Audit Plugin](https://mariadb.com/kb/en/library/mariadb-audit-plugin-log-settings/) installed on your system so it's logging a lot of the queries to the error.log file. Since AzuraCast doesn't install that plugin and it needs to be manually installed and configured I'm assuming that you modified your MariaDB installation. Do you know what you changed from the defaults?

**Comment by dereksys** [comment]
@Vaalyn I have not installed any plugin. The installation of Azuracast is by default. I have only installed a script called "mysqltuner" to check the performance of the database.

Apparently, the database is not causing the increase in RAM. However, the panel is still causing error. Now, every 2-3 minutes, the panel is no longer accessible. and I have to restart mysql for the panel to be operational again.

I have added a script with a cronjob, which checks mysql every minute. If mysql is down, then the script restarts mysql.

About the RAM, it is currently consuming is at the value of **44GB** !!

![1](https://user-images.githubusercontent.com/49600256/56159681-9a187180-5fc5-11e9-86f3-4eb07831bf36.jpg)

**Top**:

![2](https://user-images.githubusercontent.com/49600256/56159843-f9768180-5fc5-11e9-9367-5fb103109af8.jpg)
(...)

**Top ordered by memory usage**:

![3](https://user-images.githubusercontent.com/49600256/56159960-40fd0d80-5fc6-11e9-9795-708c7f38e40a.jpg)
(...)

What else can I do?

**Comment by btoplak** [comment]
> @dereksys It seems like you have the [MariaDB Audit Plugin]

It looks to me like a General Query log.
@dereksys: did you activate general log or error log? Which option did you put in the config file?

**Comment by dereksys** [comment]
@btoplak 

```
[mysqld_safe]
log_error=/var/log/mysql/error.log

[mysqld]
log_error=/var/log/mysql/error.log
```

**Comment by btoplak** [comment]
put
´´´
log_warnings = 2
general_log = 0
´´´
empty error log file, restart mysql and check again

**Comment by dereksys** [comment]
I do not know if this is related to the problem, but the nowplaying task does not work. The last execution was 36 hours ago. if I execute this task manually, the page is in "loading" status for more than 15 minutes and finally a nging error appears: Error 502 Bad Gateway.

**Comment by dereksys** [comment]
> put
> 
> ```
> log_warnings = 2
> general_log = 0
> ```
> empty error log file, restart mysql and check again

Ok, done!:

```
[mysqld_safe]
log_error=/var/log/mysql/error.log

[mysqld]
log_error=/var/log/mysql/error.log

log_warnings = 2
general_log = 0
```

**Comment by dereksys** [comment]
@btoplak @Vaalyn 

Last error log:

[https://we.tl/t-1SKCvPISpX](https://we.tl/t-1SKCvPISpX)

**Comment by btoplak** [comment]
> Last error log:
> 
> https://we.tl/t-1SKCvPISpX

I don't know why your error log is still filling up with verbose notices and queries being run. You might want to check if there isn't any other conf file being loaded too...

Anyway I don't think mysql is your main problem. In my test system the Liquidsoap uses most of the RAM.
How many stations do you have active?
How many media files loaded in all of them?

**Comment by dereksys** [comment]
@btoplak I currently have 32 radio stations, of which 15 are in production (with activity).

> How many media files loaded in all of them?
I do not know that information. Each radio station has its own audio files for autodj. I do not know where I can see the total number of audio files.

**Comment by Vaalyn** [comment]
@dereksys Please run these queries on your DB `SHOW PLUGINS;`, `SHOW VARIABLES LIKE "general_log%";` and post the output here.

To see how many files there are in your installation over all stations you can run a simple `SELECT COUNT(*) FROM azuracast.station_media;`

**Comment by dereksys** [comment]
@Vaalyn How do I access the database? I do not know where the access password is. (My installation is traditional). And these commands must be executed from ssh, correct?

**Comment by dereksys** [comment]
@Vaalyn 

`SHOW PLUGINS;`

![1](https://user-images.githubusercontent.com/49600256/56168506-adced280-5fdb-11e9-98f1-3a90c73cc79b.jpg)

`SHOW VARIABLES LIKE "general_log%";`

![2](https://user-images.githubusercontent.com/49600256/56168521-b7f0d100-5fdb-11e9-8f1e-fd7e212e629f.jpg)

`SELECT COUNT(*) FROM azuracast.station_media;`

![3](https://user-images.githubusercontent.com/49600256/56168543-ca6b0a80-5fdb-11e9-88c6-ea960d9e7093.jpg)

**Comment by Vaalyn** [comment]
@dereksys That's really strange. These outputs look fine to me and the amount of media files is also not that high. I have no idea why your installation is using that much memory and why the DB is logging the queries. 

Normally I'd advise you to look into the DB error.log to find out why the DB is shutting down so frequently but the queries that are logged to the same file make that a bit problematic.

If you want I can take a look at your server / installation directly to see if I can find our more. If that's okay for you, you can send me the SSH connection details to vaalyndev@gmail.com.

**Comment by dereksys** [comment]
Hi @Vaalyn I just sent you an email.
Thank you so much.

**Comment by dereksys** [comment]
The server has stopped consuming memory and is now in a correct state, consuming a more normal memory.

I want to thank @Vaalyn for its initiative to check my server. And also for your advice.

I close this incidence, but first I want to thank everyone for your help.
