### ISSUE TITLE
daily playlist do not play

### ISSUE THREAD

**Issue by inetactief** [AzuraCast/AzuraCast#1437]
Hi,

Afther update to v0.9.4.2, #40a7d5a (2019-04-09 9:13) • Docker • PHP 7.2
The playlist are not play on time. The playlist for every 4 songs are working fine.
I see the time on the server is good. On the log of the radio station is 2 hours behind.
Looks like the radio station have other time than the server.
Is there a timezone for the radio stations? 

Best regards,
Michel

**Comment by SlvrEagle23** [comment]
@inetactief If your host machine is on a different time zone than UTC, this can cause AzuraCast to incorrectly try to "adjust" the time zone to match the system clock.

I'm not sure that there's an easy or elegant solution to this, but it's likely that switch your host machine's time zone to UTC will fix the issue.

**Comment by inetactief** [comment]
Hi,

I thought it was a time issue but I see some log and do this:
Set a "test" playlist  to play daily on 10 AM CET (my log is 2 hours behind)

2019/04/16 07:57:14 [lang:3] AzuraCast Feedback Response: OK
2019/04/16 08:00:00 [playlist_test:3] Prepared "/var/azuracast/stations/synthetic_fm_italo_new_generation/media/sharks_-_i_love_you.wav" (RID 10).
2019/04/16 08:00:00 [switch_6485:3] Switch to synthetic_fm_italo_new_generation_playlist_test_cue with transition.
2019/04/16 08:00:00 [rotate_6489:3] Switch to synthetic_fm_italo_new_generation_playlist_new_italo_cue with forgetful transition.
2019/04/16 08:00:00 [lang:3] AzuraCast Feedback Response: OK

So it look like the time is good. But he not play the wav song:
16 apr. 2019 09:57	1	0	I Can't Get You Out Of My Mind (Dance Version) Stage	Playlist: New Iventi default
16 apr. 2019 10:07	1	0	Synthetic FM Synthetic FM	Playlist: jingles lang en kort
16 apr. 2019 10:00	1	0	Web Kills The Radio (Extended Mix) Nick Festari	Playlist: New italo
16 apr. 2019 10:07	1	0	Synthetic FM Synthetic FM	Playlist: jingles lang en kort

**Comment by SlvrEagle23** [comment]
@inetactief WAV is one of those formats where we don't officially support it, and it doesn't officially work with either our software or AzuraCast, but if you use it and it plays then by all means keep using it. In this case, though, it doesn't seem to work, so you should likely just transcode that file into a different format; even another lossless format like `.flac` is widely accepted and parsed by our software.

**Comment by inetactief** [comment]
Hi,
I test it using a mp3 on a daily cal "test2" on 9 AM CET the log is 2 hours behind

2019/04/17 07:00:00 [playlist_test2:3] Prepared "/var/azuracast/stations/synthetic_fm_italo_new_generation/media/mede_mogelijk.mp3" (RID 10).
2019/04/17 07:00:00 [switch_6485:3] Switch to synthetic_fm_italo_new_generation_playlist_test2_cue with transition.
2019/04/17 07:00:00 [rotate_6489:3] Switch to synthetic_fm_italo_new_generation_playlist_new_italo_cue with forgetful transition.
2019/04/17 07:00:00 [lang:3] AzuraCast Feedback Response: OK
2019/04/17 07:05:46 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/synthetic_fm_italo_new_generation/media/New italo2/italove_-_disco_queen_-28moderno_remix-29-28feat._ken_laszlo-29.mp3".
2019/04/17 07:05:56 [playlist_new_italo:3] Finished with "/var/azuracast/stations/synthetic_fm_italo_new_generation/media/New italo2/fred_ventura_-_all_for_you_.mp3".
2019/04/17 07:05:56 [playlist_new_italo:3] Prepared "/var/azuracast/stations/synthetic_fm_italo_new_generation/media/New italo2/italove_-_disco_queen_-28moderno_remix-29-28feat._ken_laszlo-29.mp3" (RID 1).
2019/04/17 07:05:56 [rotate_6489:3] Switch to rotate_6487 with forgetful transition.

I do not hear the test2 mp3 file. Same problem.

**Comment by inetactief** [comment]
Is there a way to check more log?

**Comment by SlvrEagle23** [comment]
@inetactief In the "Advanced configuration" for Liquidsoap, you can increase the log level by using:

```
set("log.level",5)
```

...then restarting the station. This will greatly increase the size of the logs (so it should only be used for testing) but will provide debug information along with the regular Liquidsoap logging.

**Comment by inetactief** [comment]
It look like the daily playlist work now. 
We have remove on advenced setting this:
`radio = crossfade(start_next=4.,fade_out=2.,fade_in=0.,radio)  `

We use this for better crosfading normal this work fine but the new version it do not work for daily playlist. We like to fade out. But not fade in.

**Comment by SlvrEagle23** [comment]
@inetactief As a general rule-of-thumb, it's a good idea to disable any advanced custom configuration you have and check that this resolves the issue before filing an issue. While we give you the option to customize the Liquidsoap configuration directly, we don't support whatever happens when you do that.

**Comment by inetactief** [comment]
We have again some problems on the daily playlist. The do not play. we use good mp3 files use the debug function but the not play and not in the log about it. Our Synchronization Tasks work fine.
I do not know where to find some log for this..
The Scheduled work good..
