### ISSUE TITLE
AAC files not indexed correctly, how to restart indexing?

### ISSUE THREAD

**Issue by btoplak** [AzuraCast/AzuraCast#1438]
I am now building my server for 20 test channels, and I have a bunch of AAC @64k files.

I've added those files to appropriate /media folders of each station. After the media folder scan script has been through the files, only the Title and Artist have been properly extracted, not the lengths of songs:

```
mysql> SELECT count(*) FROM azuracast.station_media;
+----------+
| count(*) |
+----------+
|     7326 |
+----------+
```
```
mysql> SELECT count(*) FROM azuracast.station_media where length > 0;
+----------+
| count(*) |
+----------+
|       19 |
+----------+
```

Can I rerun the media files scan to get the time properly indexed?

**Comment by afonsosantos** [comment]
I think you can, on the Administration page, at the web interface.

**Comment by btoplak** [comment]
Nope, that one doesn't help, it skips files since they were already added to DB...

I need a way to force it to reanalyze the files.

**Comment by Vaalyn** [comment]
@btoplak Triggering the media processing via the System Administration `Check Media Folders` will run the task with the `force` flag so all media should be re-processed.

[Here](https://github.com/AzuraCast/AzuraCast/blob/master/src/Entity/Repository/StationMediaRepository.php#L101) is the code that is responsible for processing the media.  [Here](https://github.com/AzuraCast/AzuraCast/blob/master/src/Entity/Repository/StationMediaRepository.php#L137) is the part that handles the ID3 tags and [here](https://github.com/AzuraCast/AzuraCast/blob/master/src/Entity/Repository/StationMediaRepository.php#L156) is the part that sets the song length. Probably `getID3` is not able to fetch this information from your files.

How are your files encoded exactly?

**Comment by btoplak** [comment]
@Vaalyn: Thanks for your attention

The format is  aac (LC), 44100 Hz, stereo, fltp, 125 kb/s

I have started a reprocessing with `./docker.sh cli azuracast:media:reprocess` and I finally see some feedback from the app. 
```
[15-Apr-2019 21:07:03 UTC] Warning for uploaded media file "Howlin ' Wolf - Getting Late": ["unable to determine file format"]
Processed: Blues_Rock/Howlin ' Wolf - Getting Late.aac
```
It really seems like it isn't being recognized by some process, could be getID3.

**Comment by SlvrEagle23** [comment]
@btoplak That's definitely the command to reprocess the file, and if it's not parsing it correctly as an AAC then it likely can't pull any of the ID3 metadata. This may be an upstream issue with the getid3 library, or an issue with that specific file.

**Comment by Vaalyn** [comment]
@btoplak Can you send me a file that can not be processed? I'd like to test around with this a bit myself.

**Comment by btoplak** [comment]
Thanks @Vaalyn @SlvrEagle23 for the hints.

It's almost all of my converted files, no need to spend your time to analyze it, but thanks for the kind offer...

The "unable to determine file format" definitely comes from getID3 library. My files are obviously not formatted as the lib would like it.

The "ffprobe" knows better
```
[aac @ 0x55d67ec3e080] Estimating duration from bitrate, this may be inaccurate
Input #0, aac, from 'We_Five_-_You_Were_On_My_Mind.aac':
  Duration: 00:02:34.39, bitrate: 125 kb/s
    Stream #0:0: Audio: aac (LC), 44100 Hz, stereo, fltp, 125 kb/s
```
as does the "mediainfo" tool, although not determining the length
```
General
Complete name                            : We_Five_-_You_Were_On_My_Mind.aac
Format                                   : ADTS
Format/Info                              : Audio Data Transport Stream
File size                                : 2.31 MiB
Overall bit rate mode                    : Variable

Audio
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Format version                           : Version 4
Codec ID                                 : 2
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 2.31 MiB (100%)
```
I've run my files through the ffmpeg to try to fix them if some frame alignment is in work here. Then I'll see if getID3 will like them more.

**Comment by Vaalyn** [comment]
It could make sense to report this problem to the getID3 project with a file as demonstration so that they may find out what the problem is and maybe they'll fix that in the library.

**Comment by btoplak** [comment]
The fix for my files was the magic tool called FFmpeg :-)
`ffmpeg -i old.aac -vn -acodec copy fixed.aac` and now the getID3 has catched up and recognizes the time for most of the songs.

@Vaalyn yup, I'll send them some samples

**Comment by Vaalyn** [comment]
@btoplak Good to hear that it was only a small encoding error on the file and nothing serious with the library =)
