### ISSUE TITLE
Webhook adding username with @

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#1440]
I am using the twitter webhook for displaying the current track in 5-minute intervals and since the space is limited, I wish I could add a twitter username with an @username, would this be easy to implement?

**Comment by SlvrEagle23** [comment]
@macbroadcast What do you mean? You should be able to specify a Twitter username in the message body. Does it not allow you to do that?

**Comment by macbroadcast** [comment]
Sorry @SlvrEagle23 when I was a bit unclear, what I was trying to say is, the space is very limited, Artist Name, Title, Album e.t.c, so  when I try to link to another twitter URL , like in my case 30 characters, it would be very cool and efficent when "@username" is a link on twitter.

**Comment by Vaalyn** [comment]
@macbroadcast Can you give us an example of how you would configure the Webhook now (or a screenshot) and what exactly you want to look differently and how?

**Comment by macbroadcast** [comment]
Sorry, it does exactly what i want allready allready  :smile_cat:
