### ISSUE TITLE
Radio button on the right top doesn't work

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#1441]
That radio button on the right top doesn't work for me. It appeared after latest update.

İnstallation method: docker
Device: macbook / google chrome

And the error when I click it:

`Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'nonce-1AXFGvjawTrqMvG9dh2YqcP2'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

radio.js:112 MEDIA_ELEMENT_ERROR: Empty src attribute`

**Comment by Vaalyn** [comment]
Just to add some context: radio button as in button with a radio icon, not a html radio button. Can be seen in the demo installation too.

**Comment by SlvrEagle23** [comment]
@radiolize @Vaalyn I think when I switched the public radio player to be a standalone Vue component, the inline radio player got jealous. I went ahead and moved the inline player to be its own Vue component too, which also should've fixed several issues that were created with the public radio switch.
