### ISSUE TITLE
Q: server returning listener count.

### ISSUE THREAD

**Issue by muppathimoonu** [AzuraCast/AzuraCast#1442]
Is it necessary?
https://demo.azuracast.com/radio/8000
This url is returning listener details publicly

**Comment by muppathimoonu** [comment]
Why even this page should be public? Instead of showing all these details, we can simply return 404.

**Comment by Vaalyn** [comment]
This is the standard public page of IceCast and the only listener details that are public on that page are the listener count and the listener peak count. For most radio stations the listener count is visible anyways on their radio players so I don't think that there is any harm in having this page. If you want to restrict access to that page you should setup a reverse proxy in front of AzuraCast that disallows access to this page for external IPs.
