### ISSUE TITLE
Sync directory with a playlist

### ISSUE THREAD

**Issue by skoja** [AzuraCast/AzuraCast#1443]
We created a certain base of songs.
A playlist is created from the folder directly.
After that, we added 50 more songs via SFTP and several songs over the web.

The main folder made a refresh and inserted new songs into the database.
However, no new songs were inserted directly on the radio station, although a playlist with that folder was connected.

Is there a possibility to automatically upload new songs from SFTP directly to the playlist?

Thank you.

**Comment by Vaalyn** [comment]
Currently there is no way to automatically sync a directory with a playlist. I'm not entirely sure what you mean with:
> ... a playlist with that folder was connected.

You can assign all songs from a directory to a playlist by selecting the directory and setting that to a playlist but that does not assign directories themselves to a playlist only the content of that directory at that moment.

**Comment by skoja** [comment]
Thank you.
I just meant it automatically sync a directory with a playlist.
It would be an ideal option and at the same time an idea for the development of this option.

I think it is very very useful.

**Comment by Vaalyn** [comment]
@skoja Thank you for clarifying. I've edited the issues title and added the `enhancement` label to it.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38787/automatically-associate-playlists-with-folders
