### ISSUE TITLE
Rotate playlists in order

### ISSUE THREAD

**Issue by Reaktiv4** [AzuraCast/AzuraCast#1445]
How to rotate to take one song from the playlist and playlists go in order? For example - Playlist (rock1), playlist (rock2), playlist (metal1), playlist (rock3), playlist (metal2).

**Comment by SlvrEagle23** [comment]
@Reaktiv4 The easy solution to this is to make your playlists "Advanced" playlists, and then specify the order by hand in your Advanced Liquidsoap configuration, like so:

```
radio = rotate(weights=[1,1,1,1,1], [playlist_rock1, playlist_rock2, playlist_metal1, playlist_rock3, playlist_metal2])
```
