### ISSUE TITLE
error 500 when exporting playlist 

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#1447]
**Installation method**
Docker Installation - Azuracast v0.9.4.2, #6ebb9f8 (2019-04-17 1:12)
**Host OS (for Docker installations)**
Ubuntu 18

**Describe the bug**
Error occurs when exporting M3U or PLS playlist

**To Reproduce**
1. Go to 'Playlist'
2. Click on 'More tab'
3. Scroll down to either EXPORT PLS or EXPORT M3U 
> 500
> Argument 1 passed to App\Controller\Stations\AbstractStationCrudController::_getRecord() must be an instance of App\Entity\Station, string given, called in /var/azuracast/www/src/Controller/Stations/PlaylistsController.php on line 194
> AbstractStationCrudController.php : 76

**Expected behavior**
Exporting playlist will be possible as usual

**Relevant Logs**
SHOUTcast and Liquidsoap log
 - Error: Malformed UTF-8 characters, possibly incorrectly encoded

**Device(s):**
Chrome and Safari on Mac Sierra

**Comment by SlvrEagle23** [comment]
@ErnestPH Fixed per @Vaalyn's latest pull request. :)

**Comment by ErnestPH** [comment]
Thanks @Vaalyn and of course @SlvrEagle23 for verifying it… I was trying to play around, I missed the code :) It was all over there! thanks again!
