### ISSUE TITLE
Song preview stop button doesn't work

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1448]
Bare-Metal

In Music Library: click on Play (Prelisten), click on same button (stop) -> song is restartet but not stopped.
![grafik](https://user-images.githubusercontent.com/47743654/56343359-cd702180-61ba-11e9-9351-4833c4b804ff.png)

**Comment by SlvrEagle23** [comment]
@MrSteelMiner Found the problem: the playback URL is relative, but the URL that the source is actually playing is absolute. When it checks to see if the URL of the button you just clicked is the same as the source URL, this fails, and it won't pause.

The issue should be fixed now. Thanks for your report!
