### ISSUE TITLE
More bitrates to select

### ISSUE THREAD

**Issue by ivellios1988** [AzuraCast/AzuraCast#1452]
There should be more options hen it comes to bitrate selection in mountpoints. For example, my station currently uses mountpoints with bitrates like 24 kbps. I'd like to switch my station to AzuraCast (currently I'm using Centova Cast) but AzuraCast doesn't allow me to select bitrates lower than 32 kbps or higher than 320kbps (which would be useful with using OPUS and AAC).

I even edited PHP files responsible for showing lists of bitrates, but so far with no success, my custom bitrates aren't showing up in the panel.

**Comment by SlvrEagle23** [comment]
@ivellios1988 This is already an existing feature request you can vote on here:
https://azuracast.featureupvote.com/suggestions/39024/expand-available-bit-rate-options-for-streams
