### ISSUE TITLE
Azuracast cant be listed at www.internet-radio.com

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#1454]
hi,
i just had an argument  with the support from internet-radio.com
i wanted to list my station there, but they said, its not icecast or shoutcast
its not compatible duhhhh

Just to let you guys know

Happy easter

**Comment by Vaalyn** [comment]
Hmkay, that's a pretty un-educated repsonse from them. AzuraCast is just a management suite for IceCast / ShoutCast and all the components needed to run a web radio.

**Comment by Vaalyn** [comment]
@macbroadcast It seems like they support listing via IceCasts YP direcotory listing: https://www.internet-radio.com/community/threads/icecast-server-yp-directory-settings.22223/

**Comment by macbroadcast** [comment]
@Vaalyn ,yes i know, set up everything correctly, but they insist it's not icecast or shoutcast, i send them the link 3 or 4 times, got no answer anymore, but i think the support is just clueless :smile:

**Comment by SlvrEagle23** [comment]
@macbroadcast I think you may be right.

AzuraCast isn't itself a broadcasting frontend, we just sit on top of SHOUTcast/Icecast, and if they're trying to pull metadata from either, they will have no difficulty, as the underlying metadata is completely accessible via the radio station's broadcasting port.

If they allow Yellow Pages configuration, then you can specify their YP url in "Advanced frontend configuration" (at least for Icecast) and it should connect without any issue.

It's understandable if they're not compatible with AzuraCast's API, but if you need an official response from the developer of AzuraCast itself, there you go. :)

**Comment by macbroadcast** [comment]
Thanks @SlvrEagle23 i will save the post/email and try in a few weeks again. :+1:

**Comment by macbroadcast** [comment]
Today I tried two other free directories (streema and streamfinder ),but both sites gave me an error message when transmitting the "stream URL", seems there is something special in azuracast, so most streaming directory sites don't support it.

**Comment by Vaalyn** [comment]
@macbroadcast There is probably not much that we can do here without some details from these directories about why their software doesn't like the streaming links. You should first talk to their support and ask them to look into this issue on their side as AzuraCast is just managing IceCast / ShoutCast servers so as long as those are supported by them there should not be a problem.

**Comment by ErnestPH** [comment]
> Today I tried two other free directories (streema and streamfinder ),but both sites gave me an error message when transmitting the "stream URL".
> 

I added in streamfinder and mine was valid - 
http://streamfwd.com/MSrvy

**Comment by macbroadcast** [comment]
@ErnestPH thanks I forgot the /radio.mp3 at the end :blush:

**Comment by ErnestPH** [comment]
Good to know! In some cases, /radio.mp3 is omitted. I had a web player who uses a URL without .mp3, and I literarily was having a hard time trying to add the correct URL to retrieve the data (Title song and Artist's name)… I played around until I got it :)

**Comment by macbroadcast** [comment]
@ErnestPH Yes it seems there is no consistent way. Have you successfully submitting your azuracast station to www.internet-radio.com?

**Comment by ErnestPH** [comment]
Haven't tried it yet because I don't have a station really :). The streamer link is from a friend's station. I asked to set it up so as to try if it's really invalid or not. I am more of a tech support guy. But I will try that one and will update you...

**Comment by ErnestPH** [comment]
Ok I just check internet radio, the URL link (with .mp3) should work but one requirement is you should link their website to your website, otherwise they won't list your station. It's fair enough I guess.

**Comment by macbroadcast** [comment]
Great to know, a silly mistake from me to forget the radio.mp3 at the end.Yes i added the code snippet already to the azuracast custom configuration
`<directory>
    <yp-url-timeout>15</yp-url-timeout>
    <yp-url>http://dir.xiph.org/cgi-bin/yp-cgi</yp-url>
</directory>`
The site looks pretty big, guess its worth the effort to link back. 
Cheers
