### ISSUE TITLE
can't edit some playlists

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#1456]
Hello,
i can't edit playlist settings like shuffle on some playlists. If i create a new playlist with the same songs, i am able to edit it.
I think, this is only for old playlists.
Here are the Settings of one example playlist:
![grafik](https://user-images.githubusercontent.com/31483348/56455622-e4507880-6360-11e9-8943-6265b0c3b407.png)
![grafik](https://user-images.githubusercontent.com/31483348/56455625-eadef000-6360-11e9-9ec0-f63b07286217.png)
![grafik](https://user-images.githubusercontent.com/31483348/56455628-f3cfc180-6360-11e9-9860-b674ba17798d.png)

I use Windows 10 with Firefox 66.

I think this could help:
#0 /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php(399): Redis->connect('localhost', 6379, 15)
#1 /var/azuracast/www/vendor/pimple/pimple/src/Pimple/Container.php(114): Azura\DefaultServicesProvider->Azura\{closure}(Object(Azura\Container))
#2 /var/azuracast/www/vendor/azuracast/azuracore/src/Container.php(109): Pimple\Container->offsetGet('Redis')
#3 /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php(151): Azura\Container->offsetGet('Redis')
#4 /var/azuracast/www/vendor/pimple/pimple/src/Pimple/Container.php(118): Azura\DefaultServicesProvider->Azura\{closure}(Object(Azura\Container))
#5 /var/azuracast/www/vendor/azuracast/azuracore/src/Container.php(109): Pimple\Container->offsetGet('Azura\\Cache')
#6 /var/azuracast/www/config/services.php(277): Azura\Container->offsetGet('Azura\\Cache')
#7 /var/azuracast/www/ve in /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php on line 399

**Comment by SlvrEagle23** [comment]
@preterive What is the actual exception you're running into? It should be there at the very top of the stack trace.

That exception relates to Redis, which suggests there may be something a little messed up with your Redis configuration.

**Comment by preterive** [comment]
Hello,
i get no exception if I simple edit the playlist. In only see errors in the log file.
The Server simple don't save the changes.
I can delete the playlist without problems. I can't edit some songs too.
I think this is only for old playlists and songs, 4-6 Months old.
I will check my redis config.
I will send you a new error log later.

**Comment by preterive** [comment]
Hello,
after a Server restart i can't edit every playlist...
The error from the php Log:
[17-Apr-2019 19:53:21 UTC] PHP Fatal error:  Uncaught RedisException: Connection refused in /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php:399
Stack trace:
#0 /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php(399): Redis->connect('localhost', 6379, 15)
#1 /var/azuracast/www/vendor/pimple/pimple/src/Pimple/Container.php(114): Azura\DefaultServicesProvider->Azura\{closure}(Object(Azura\Container))
#2 /var/azuracast/www/vendor/azuracast/azuracore/src/Container.php(109): Pimple\Container->offsetGet('Redis')
#3 /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php(151): Azura\Container->offsetGet('Redis')
#4 /var/azuracast/www/vendor/pimple/pimple/src/Pimple/Container.php(118): Azura\DefaultServicesProvider->Azura\{closure}(Object(Azura\Container))
#5 /var/azuracast/www/vendor/azuracast/azuracore/src/Container.php(109): Pimple\Container->offsetGet('Azura\\Cache')
#6 /var/azuracast/www/config/services.php(277): Azura\Container->offsetGet('Azura\\Cache')
#7 /var/azuracast/www/ve in /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php on line 399

I restarted the redis Server and this is the log:

320:M 24 Apr 09:04:32.700 # WARNING: The TCP backlog setting of 511 cannot be en                                       forced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
320:M 24 Apr 09:04:32.700 # Server started, Redis version 3.0.6
320:M 24 Apr 09:04:32.700 # WARNING overcommit_memory is set to 0! Background sa                                       ve may fail under low memory condition. To fix this issue add 'vm.overcommit_mem                                       ory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overc                                       ommit_memory=1' for this to take effect.
320:M 24 Apr 09:04:32.702 * DB loaded from disk: 0.002 seconds
320:M 24 Apr 09:04:32.702 * The server is now ready to accept connections on por                                       t 6379
320:M 24 Apr 09:09:33.061 * 10 changes in 300 seconds. Saving...
320:M 24 Apr 09:09:33.063 * Background saving started by pid 1678
1678:C 24 Apr 09:09:33.193 * DB saved on disk
1678:C 24 Apr 09:09:33.194 * RDB: 0 MB of memory used by copy-on-write
320:M 24 Apr 09:09:33.264 * Background saving terminated with success
320:signal-handler (1556090052) Received SIGTERM scheduling shutdown...
320:signal-handler (1556090052) Received SIGTERM scheduling shutdown...
320:M 24 Apr 09:14:12.424 # User requested shutdown...
320:M 24 Apr 09:14:12.424 * Saving the final RDB snapshot before exiting.
320:M 24 Apr 09:14:12.593 * DB saved on disk
320:M 24 Apr 09:14:12.593 * Removing the pid file.
320:M 24 Apr 09:14:12.594 # Redis is now ready to exit, bye bye...


i think i have to do what i see there :)

**Comment by preterive** [comment]
Edit: There is already the vm.overcommit_memory = 1 in the Config...

**Comment by preterive** [comment]
okay, i already tried a few things.
I seems to be a problem by azuracast.
I have no problems if i edit a new playlist. Now i create every playlist new.

**Comment by Vaalyn** [comment]
@preterive is this problem still happening?
