### ISSUE TITLE
Is it possible to display album art in a webhook ?

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#1457]
Hi,
i liked to extent the twitter webhook a little bit, so i try to add `{{ playing_next }}` but it did not work,
and my main question is it possible to display album art in twitter webhook ? Somewhere in the text field? 
![Bildschirmfoto von 2019-04-20 16-18-20](https://user-images.githubusercontent.com/7961/56458539-6902bd00-6388-11e9-880d-6f09472f04bb.png)

Thanks

**Comment by SlvrEagle23** [comment]
@macbroadcast Images (and the URL previews) are processed differently from the rest of the body of Twitter messages, so this would likely be a new feature request.

If you don't mind, could you submit this over on our FeatureUpvote page instead?

https://features.azuracast.com/

**Comment by macbroadcast** [comment]
@SlvrEagle23 i tried several 3rd party services, none of them has a feature where you could extract the photo like on the azuracast page https://stream.iradio.guru/public/iradio , from what i understand a twitter card is just a  reference to this file and render it on twitters backend, 
It works  with youtube and soundcloud, please i want album the art in my twitter card
i am willing to pay :smile_cat:
