### ISSUE TITLE
Only one jingle is played instead of all

### ISSUE THREAD

**Issue by Rootinator** [AzuraCast/AzuraCast#1458]
**Installation method**

- Docker

**Host OS (for Docker installations)**

- Ubuntu 18.04.2 LTS

**Describe the bug**

- The playlist "Jingle-Playlist" (example) should be played every 30 minutes (content: 2 jingles), but only one jingle will play instead of the existing 2 jingles.
What do I have to do, that all jingles are played in sequence (without repeat)?

**To Reproduce**
Create two playlists (/station/1/playlists)

- A playlist of music played randomly and a playlist of only jingles to be played continuously every 30 minutes

- Basic Information:
→ Playlist Name: Jingle Playlist
→ Enable playlist: YES
→ Playlist Weight: 3 - Default

All settings see pictures

**Expected behavior**
It should be interrupted every 30 minutes the music playlist (song ends). This happens.

After that the jingle playlist should start immediately and all jingles should be played one after the other (Jingle1, Jingle2, ...).

Mistake: Jingle playlist starts after 30 minutes, but plays only Jingle1 and after another 30 minutes starts Jingle2.

**Relevant Logs**
```
2019/04/20 12:46:47 [STATION_relay_1:3] Connection setup was successful.
2019/04/20 12:46:47 [threads:3] Created thread "wallclock_main" (1 total).
2019/04/20 12:46:47 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2019/04/20 12:46:47 [fallback_6443:3] Switch to delay_6442.
2019/04/20 12:46:47 [lang:3] AzuraCast Feedback Response: OK
2019/04/20 12:46:49 [playlist_adtrigger:3] Finished with "/var/azuracast/stations/STATION/media/000000__AdTrigger/werbung_anfang.wav".
2019/04/20 12:46:49 [STATION_next_song:3] Prepared "/var/azuracast/stations/STATION/media/MUSICALBUM3/SONG7.m4a" (RID 10).
2019/04/20 12:46:49 [fallback_6443:3] Switch to STATION_autodj_fallback with forgetful transition.
2019/04/20 12:46:49 [STATION_autodj_fallback:3] Switch to STATION_cue_cut.
2019/04/20 12:46:49 [lang:3] AzuraCast Feedback Response: OK
2019/04/20 12:46:54 [clock.wallclock_main:2] We must catchup 1.38 seconds!
2019/04/20 12:47:22 [clock.wallclock_main:2] We must catchup 1.05 seconds!
2019/04/20 12:47:32 [clock.wallclock_main:2] We must catchup 1.11 seconds!
```

**Screenshots**
My settings of the playlist "Jingle-Playlist":
https://s16.directupload.net/images/190416/ezncpqr9.png
https://s16.directupload.net/images/190416/xuui2r99.png

**Comment by Rootinator** [comment]
I would like to ask if and how I can fix the problem? :)

**Comment by Vaalyn** [comment]
I think there is currently no direct way to tell a playlist to do a full playthrough when it's playling. You may have some success by setting the Jingle playlist to a really high priority.

@Rootinator would you mind creating a feature request for an option to let a playlist do a complete playthrough over at https://features.azuracast.com/ ?

**Comment by SlvrEagle23** [comment]
@Rootinator This has been implemented as of the latest update; for a given playlist, choose "Merge playlist to play as a single track" as a scheduling option, and the whole playlist will play as though it's a single track.
