### ISSUE TITLE
/mounts endpoint does not return default mount point

### ISSUE THREAD

**Issue by wokes** [AzuraCast/AzuraCast#1460]
**Installation method**
Bare-metal

**Describe the bug**
`/station/{station_id}/mounts` does not report default endpoint and associated data.
Right now it's impossible to get complete set of data for a broadcaster without crawling the web panel, because you can't get the source password assigned by default. The workaround is to create an additional mount point with desired password, and that's not ideal.

**To Reproduce**
Send a GET request to `/station/{station_id}/mounts` endpoint.

**Expected behavior**
Response body contains data associated with the mount point created by default, when the station is created, including the default source password.

**Additional context**
v0.9.4.2, #8dc072d (2019-04-13 3:27)

**Comment by SlvrEagle23** [comment]
@wokes The source password isn't a per-mount-point thing by default (though it can be overridden per-mount-point, as you're doing), it's typically configured in the frontend ("Broadcasting") tab of the station's profile. To view this data, you'll want to `GET /api/admin/station/{id}`, where you should see it in `frontend_config`.
