### ISSUE TITLE
Connection to Icecast fails - connects than disconnects. Unable to stream music.

### ISSUE THREAD

**Issue by LochStudios** [AzuraCast/AzuraCast#1461]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-142-generic x86_64)

**Describe the bug**
Streaming to Icecast doesn't work. I can stream from my home computer to the Icecast server installed on the box.

**To Reproduce**
1. Start a new radio station
2. Add music files
3. Queue the files with Liquidsoap.
4. Attempt to listen to the music using the Icecast link
5. Observe error: The file you requested could not be found

**Expected behaviour**
The system was able to find the file and stream the music being played.

**Relevant Logs**
In CurlFactory.php line 185:
web_1       |
web_1       |   cURL error 7: Failed to connect to stations port 8000: Connection refused (
web_1       |   see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**--------**

stations_1  | 2019-04-21 13:20:24,509 INFO spawned: 'station_1_backend' with pid 27583
web_1       | 172.18.0.5 - - [21/Apr/2019:13:20:24 +0000] "POST /api/internal/7/nextsong HTTP/1.1" 200 5 "-" "curl/7.58.0" "-"
web_1       | 172.18.0.5 - - [21/Apr/2019:13:20:24 +0000] "POST /api/internal/8/nextsong HTTP/1.1" 200 5 "-" "curl/7.58.0" "-"
web_1       | 172.18.0.5 - - [21/Apr/2019:13:20:24 +0000] "POST /api/internal/9/nextsong HTTP/1.1" 200 5 "-" "curl/7.58.0" "-"
web_1       | 172.18.0.5 - - [21/Apr/2019:13:20:24 +0000] "POST /api/internal/1/nextsong HTTP/1.1" 200 282 "-" "curl/7.58.0" "-"
stations_1  | 2019-04-21 13:20:25,646 INFO success: station_1_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
web_1       | Apr 21 13:20:25 5fd5dcbfc5a3 php-fpm[56]: [WARNING] [pool www] child 9555 said into stderr: "[2019-04-21 23:20:25] AzuraCast.INFO: Adapter "App\Radio\Backend\Liquidsoap" started. {"station_id":1,"station_name":"TheUnDeadStream"} []"
web_1       | 172.69.134.51 - - [21/Apr/2019:13:20:25 +0000] "POST /api/station/1/backend/restart HTTP/1.1" 200 99 "https://cast.musicbots.app/station/1/profile" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36" "**IP REMOVED**"
web_1       | 172.18.0.5 - - [21/Apr/2019:13:20:25 +0000] "POST /api/internal/6/nextsong HTTP/1.1" 200 5 "-" "curl/7.58.0" "-"
web_1       | 172.69.134.51 - - [21/Apr/2019:13:20:26 +0000] "GET /api/nowplaying/1?_=1555852650009 HTTP/1.1" 200 3651 "https://cast.musicbots.app/station/1/profile" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36" "**IP REMOVED**"
web_1       | 172.18.0.5 - - [21/Apr/2019:13:20:29 +0000] "POST /api/internal/7/nextsong HTTP/1.1" 200 5 "-" "curl/7.58.0" "-"
web_1       | 172.18.0.5 - - [21/Apr/2019:13:20:29 +0000] "POST /api/internal/8/nextsong HTTP/1.1" 200 5 "-" "curl/7.58.0" "-"
web_1       | 172.18.0.5 - - [21/Apr/2019:13:20:29 +0000] "POST /api/internal/9/nextsong HTTP/1.1" 200 5 "-" "curl/7.58.0" "-"
web_1       | 172.18.0.5 - - [21/Apr/2019:13:20:30 +0000] "POST /api/internal/6/nextsong HTTP/1.1" 200 5 "-" "curl/7.58.0" "-"
web_1       | [2019-04-21 13:20:31] AzuraCast.INFO: Running Now Playing sync task [] []
web_1       | 172.69.134.51 - - [21/Apr/2019:13:20:33 +0000] "GET /api/station/1/status?_=1555852650010 HTTP/1.1" 200 59 "https://cast.musicbots.app/station/1/profile" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36" "**IP REMOVED**"
web_1       | 172.18.0.5 - - [21/Apr/2019:13:20:34 +0000] "POST /api/internal/8/nextsong HTTP/1.1" 200 5 "-" "curl/7.58.0" "-"
web_1       | 172.18.0.5 - - [21/Apr/2019:13:20:34 +0000] "POST /api/internal/7/nextsong HTTP/1.1" 200 5 "-" "curl/7.58.0" "-"
web_1       | 172.18.0.5 - - [21/Apr/2019:13:20:34 +0000] "POST /api/internal/9/nextsong HTTP/1.1" 200 5 "-" "curl/7.58.0" "-"
web_1       | [2019-04-21 13:20:35] AzuraCast.NOTICE: HTTP client GET call to http://**IP REMOVED**:8000/status-json.xsl produced response NULL [] {"station":{"id":1,"name":"TheUnDeadStream"}
**-------**
I've removed my own IP from the logs for protection.

**Comment by SlvrEagle23** [comment]
@LochStudios On the station's profile, does it show Icecast as running or not running? If it's refusing connections on the Icecast port, this suggests there's an error causing Icecast to fail; you can view Icecast's logs via the log viewer utility on the station's "Utilities" submenu.

**Comment by LochStudios** [comment]
@SlvrEagle23 Icecast is running perfectly. I can connect to it and stream music from my home PC just fine.
