### ISSUE TITLE
Error Tab Music Files

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#1462]
**Installation method**
Docker
**Host OS (for Docker installations)**
Ubuntu
**Describe the bug**

Since the update #d9358b2 the tab does not display the titles unless I put the interface back in English, the error is available on your demo version.

https://193.111.153.40/station/1/playlists

French version
![Capture d’écran 2019-04-22 à 08 50 14](https://user-images.githubusercontent.com/379099/56487489-b2175600-64db-11e9-85a1-78b63366bd26.png)

**Comment by SlvrEagle23** [comment]
@ckeurk Thanks for the report. This should be fixed now, as all translated text is now JS-escaped in the file manager.
