### ISSUE TITLE
Misleading storage units

### ISSUE THREAD

**Issue by wokes** [AzuraCast/AzuraCast#1463]
**Describe the bug**
Azuracast's storage units are simply wrong. E.g. when entering storage allocation for a station, you enter kilobytes (`KB`, 1000 bytes) but it treats it as kibibytes (`KiB`, 1024 bytes).

**Expected behavior**
Entering 1 KB allocates 1000 bytes of storage.

**Comment by SlvrEagle23** [comment]
@wokes Good point. This and the other reported issue are fixed now.
