### ISSUE TITLE
API returns allocated/used storage as string

### ISSUE THREAD

**Issue by wokes** [AzuraCast/AzuraCast#1464]
**Describe the bug**
`api/admin/station/{station_id}` returns `storage_quota` and `storage_used` as a string, e.g. `488.3 MB`. Apart from it using wrong units (https://github.com/AzuraCast/AzuraCast/issues/1463) it isn't very friendly for usage like automation, requiring these values to be parsed to a number.

**Expected behavior**
API returns a number of bytes. To avoid ambiguity it could return `storage_bytes_quota`.

**Comment by SlvrEagle23** [comment]
@wokes Implemented now, both fixing the KiB/KB confusion and adding `storage_quota_bytes` and `storage_used_bytes` with the raw byte count. It's presented as a string instead of an int because PHP isn't very good with big numbers.
