### ISSUE TITLE
fail install bare metal on pip upgrade components

### ISSUE THREAD

**Issue by EBII** [AzuraCast/AzuraCast#1467]
Only this task fail on bare metal install 
made two time with and without pip already install and upgrade. 
TASK [init : Update pip components] **********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["/usr/bin/pip2", "install", "-U", "pip"], "msg": "\n:stderr: Traceback (most recent call last):\n  File \"/usr/bin/pip2\", line 9, in <module>\n    from pip import main\nImportError: cannot import name main\n"}

PLAY RECAP ***********************************************************************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=1 

**Installation method**

**Host OS (for Docker installations)**

**Describe the bug**

install ubuntu 18.04 
install python-pip 
start azuracast install
TASK [init : Update pip components] **********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["/usr/bin/pip2", "install", "-U", "pip"], "msg": "\n:stderr: Traceback (most recent call last):\n  File \"/usr/bin/pip2\", line 9, in <module>\n    **from pip import main\**nImportError: cannot import name main\n"}

**Additional context**

i solve this part of error with edit /usr/bin/pip2 
change 
from pip import main with 
from pip._internal import main 
then ./install again

**Comment by ivellios1988** [comment]
I have the same problem with traditional installation on Ubuntu 16.04:

TASK [azuracast-radio : Initialize OPAM (Xenial) - This takes a while...] **************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "opam init -a --disable-sandboxing --bare && opam switch create 4.05.0", "delta": "0:00:07.861097", "end": "2019-05-02 18:02:37.749018", "msg": "non-zero return code", "rc": 2, "start": "2019-05-02 18:02:29.887921", "stderr": "[NOTE] Will configure from built-in defaults.\n[NOTE] Make sure that ~/.bash_profile is well sourced in your ~/.bashrc.\n\n[ERROR] Compiler selection '4.05.0' is ambiguous. matching packages: { ocaml.4.05.0, ocaml-base-compiler.4.05.0 }", "stderr_lines": ["[NOTE] Will configure from built-in defaults.", "[NOTE] Make sure that ~/.bash_profile is well sourced in your ~/.bashrc.", "", "[ERROR] Compiler selection '4.05.0' is ambiguous. matching packages: { ocaml.4.05.0, ocaml-base-compiler.4.05.0 }"], "stdout": "Checking for available remotes: rsync and local, git, mercurial, darcs. Perfect!\n\n<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>\n[default] Initialised\n\nUser configuration:\n  ~/.bash_profile is already up-to-date.", "stdout_lines": ["Checking for available remotes: rsync and local, git, mercurial, darcs. Perfect!", "", "<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>", "[default] Initialised", "", "User configuration:", "  ~/.bash_profile is already up-to-date."]}

**Comment by SlvrEagle23** [comment]
@ivellios1988 That's not the same problem. You should submit that as a new GitHub issue.

**Comment by Vaalyn** [comment]
As of AzuraCast [0.9.5](https://github.com/AzuraCast/AzuraCast/releases/tag/0.9.5) we are not supporting new installations via Ansible anymore. I recommend you to install AzuraCast via Docker to avoid this kind of issues.

I'll close this issue now. If you encounter any problems with the Docker installation please let us know.
