### ISSUE TITLE
VBR or CBR 

### ISSUE THREAD

**Issue by inetactief** [AzuraCast/AzuraCast#1470]
Is there page where to find the support files for Autodj?

I try to play VBR mp3's on 48khz but the do not play it that correct?
I know not wav files.

**Comment by ivellios1988** [comment]
From what I remember from my own experiences with Liquidsoap, files encoded with variable bit rates tend to be troublesome. Files with VBR were generating errors and in most cases Liquidsoap just skipped them. It was like a russian roulette - a file will either be played correctly or skipped with error message.

It is generally recommended to avoid using MP3s/AACs/OGGs with VBR for AutoDJ.

**Comment by inetactief** [comment]
Okay thank you for the information.
And is there a problem when file are 48Khz on mp3 256k?

**Comment by ivellios1988** [comment]
If it's CBR then it should be OK. In case of any problems, try changing sample rates of your files to 44100 Hz.

**Comment by inetactief** [comment]
Thanks so it must work... or not?

**Comment by SlvrEagle23** [comment]
@inetactief VBR files have been known to cause issues with Liquidsoap, but any CBR file in a format that Liquidsoap can handle should work fine.
