### ISSUE TITLE
Why is the album art API endpoint only available when requests are active?

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#1475]
I was wondering why the `/station/{station_id}/art/{media_id}` endpoint is only available when song requests are enabled for a station. The new `Media` endpoints do not have this restriction so I was asking myself if that is intended or not.

**Comment by SlvrEagle23** [comment]
@Vaalyn As far as I can tell, it doesn't have anything to do with whether requests are enabled, but I did find one problem in the routing config that would've messed it up. Let me know if that fixes it.

**Comment by Vaalyn** [comment]
I've checked my test again and I think the problem I had didn't have anything to do with the art endpoint itself. I forgot that my test actually retrieves a `media_id` by fetching requestable songs and using one of the returned ids to make the test call to the art endpoint (I'll change that to use the new media endpoints now). Which is why this test failed for me and I thought this may be a problem with the art endpoint. It's good to see that my "stupid" question was helpful anyways. =)
