### ISSUE TITLE
MariaDB not installable

### ISSUE THREAD

**Issue by daveevanss** [AzuraCast/AzuraCast#1476]
**Installation method**
Bare-metal

**Describe the bug**
I run into problems installing docker on dell laptop with i386 architecture and a clean install of lubuntu so I tried a bare-metal Installation, which appears to have failed due to issue with with MariaDB, I was following the basic installation instructions. I got the message below in terminal at the end of installation process. 

**Expected behavior**

Basic bare metal installation, with localhost connection at the end.

**Relevant Logs**

```
fatal: [localhost]: FAILED! => {"cache_update_time": 1556199174, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'mariadb-server' 'mariadb-client'' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n mariadb-client : Depends: mariadb-client-10.2 (>= 1:10.2.23+maria~bionic) but it is not installable\n mariadb-server : Depends: mariadb-server-10.2 (>= 1:10.2.23+maria~bionic) but it is not installable\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " mariadb-client : Depends: mariadb-client-10.2 (>= 1:10.2.23+maria~bionic) but it is not installable", " mariadb-server : Depends: mariadb-server-10.2 (>= 1:10.2.23+maria~bionic) but it is not installable"]}
```

**Device(s):**
 - Device: i386 desktop
 - OS: Ubuntu 18.04
 - Browser: firefox
 - Version: ?

**Comment by Vaalyn** [comment]
The main problem seems to be:
```
E: Unable to correct problems, you have held broken packages.
....
The following packages have unmet dependencies:
mariadb-client : Depends: mariadb-client-10.2 (>= 1:10.2.23+maria~bionic) but it is not installable
mariadb-server : Depends: mariadb-server-10.2 (>= 1:10.2.23+maria~bionic) but it is not installable
```

Can you check what mariadb-* packages are available to you via `apt-cache search mariadb-*`?

**Comment by daveevanss** [comment]
This is what I get:

```
dbconfig-common - framework that helps packages to manage databases
default-libmysqlclient-dev - MySQL database development files (metapackage)
apophenia-bin - Apophenia Statistical C Library -- binary package
apophenia-doc - Apophenia Statistical C Library -- reference manual
dbconfig-mysql - dbconfig-common MySQL/MariaDB support
libapophenia2 - Apophenia Statistical C Library -- library package
libapophenia2-dev - Apophenia Statistical C Library -- development package
libaprutil1-dbd-mysql - Apache Portable Runtime Utility Library - MySQL Driver
libhoel-dev - database abstraction library written in C - development
libmariadb-dev - MariaDB Connector/C, development files
libmariadb-dev-compat - MariaDB Connector/C, compatibility symlinks
libmariadbclient-dev - MariaDB database development files
libmariadbclient-dev-compat - MariaDB database development files (libmysqlclient compatibility)
libmariadbclient18 - MariaDB database client library
libmariadbd-dev - MariaDB embedded database, development files
libmariadbd18 - MariaDB embedded database, shared library
libreoffice-mysql-connector - MariaDB/MySQL Connector extension for LibreOffice
libtango-dev - TANGO distributed control system - development library
libtango-doc - TANGO distributed control system - documentation
libtango9 - TANGO distributed control system - shared library
mariadb-client-10.1 - MariaDB database client binaries
mariadb-client-core-10.1 - MariaDB database core client binaries
mariadb-plugin-connect - Connect storage engine for MariaDB
mariadb-plugin-oqgraph - OQGraph storage engine for MariaDB
mariadb-server-10.1 - MariaDB database server binaries
mariadb-server-core-10.1 - MariaDB database core server files
mycli - CLI for MySQL/MariaDB
phpmyadmin - MySQL web administration tool
tango-db - TANGO distributed control system - database server
goiardi - Chef server written in Go
goiardi-doc - Documentation for Goiardi
golang-github-ctdk-goiardi-dev - Golang library to interact with a chef server
golang-gopkg-testfixtures.v2-dev - Rails-like test fixtures for Go
libdbd-mysql-perl - Perl5 database interface to the MariaDB/MySQL database
libhoel1.3 - database abstraction library written in C
libmariadb3 - MariaDB Connector/C
mariadb-plugin-cracklib-password-check - CrackLib Password Validation Plugin for MariaDB
mariadb-plugin-gssapi-client - GSSAPI authentication plugin for MariaDB client
mariadb-plugin-gssapi-server - GSSAPI authentication plugin for MariaDB server
mariadb-plugin-mroonga - Mroonga storage engine for MariaDB
mariadb-plugin-spider - Spider storage engine for MariaDB
libmariadb-java - Java database driver for MariaDB and MySQL
mariadb-client - MariaDB database client (metapackage depending on the latest version)
mariadb-common - MariaDB database common files (e.g. /etc/mysql/conf.d/mariadb.cnf)
mariadb-server - MariaDB database server (metapackage depending on the latest version)
mariadb-test-data - MariaDB database regression test suite - data files
mysql-common - MariaDB database common files (e.g. /etc/mysql/my.cnf)
```

**Comment by Vaalyn** [comment]
Okay all needed package seem to be available. Can you also check what `mariadb` packages you have installed on your system already with `apt list --installed`?

**Comment by daveevanss** [comment]
There are no MariaDB packages, I just checked. The only mention of MariaDB is

`mysql-common/bionic,now 5.8+1.0.4 all [installed,upgradable to: 1:10.3.14+maria~bionic]
`

Am I making a stupid mistake by not having Ubuntu server installed on this machine, and just the xubuntu OS?

**Comment by Vaalyn** [comment]
Ah okay it seems like you have a mysql server currently installed. Do you use that in some way? If not you should remove that and then try the installation again. It's probably this package that is holding back the installation process.

**Comment by daveevanss** [comment]
Great, thanks so much for your help. I don't use the mysql server so I'll give that a go.

**Comment by 440music** [comment]
this is the issue I'm trying to correct and I see Mariadb client and server install
this is reported from apt list --installed regarding Maria and mysql

mariadb-client/unknown,unknown,now 1:10.2.23+mariadb~bionic all [installed]
mariadb-client-10.2/unknown,now 1:10.2.23+mariadb~bionic amd64 [installed,automatic]
mariadb-client-core-10.2/unknown,now 1:10.2.23+mariadb~bionic amd64 [installed,automatic]
mariadb-common/unknown,unknown,now 1:10.2.23+mariadb~bionic all [installed,automatic]
mariadb-server/unknown,unknown,now 1:10.2.23+mariadb~bionic all [installed]
mariadb-server-core-10.2/unknown,now 1:10.2.23+mariadb~bionic all [installed]

mysql-common/bionic,bionic,now 5.8+1.0.4 all [installedupgradable to: 1:10.2.23+mariadb~bionic]

my server is fresh install lemp server with myphpadmin
AMD 3.8ghz cpu
16 gigs of RAM
Ubuntu Bionic Beaver 18.04
PHP7.2
NGINX

I found dockerd running and stopped it
mysql was running prior to stopping dockerd but any attempt to connect, stop, status or start failed
mariadb is install but error when trying to connect, status, start or stop I get the error message Unit mariadb.service could not be found
trying to install I get:
mariadb-client is already the newest version (1:10.2.23+mariadb~bionic)
mariadb-server is already the newest version (1:10.2.23+mariadb~bionic)

apt --fix-broken install seems to complete so I tried to ./install.sh and still failed although this time I got and error about /root/my.cnf  and the file isn't in /root
I also found that mariadb wasn't running and started it systemctl start mariadb and checked the status and got active but there is an error about mysql

I get to TASK [azuracast-db-install : Mariadb Cleanup]failed: [localhost] (item=DELETE FROM mysql.user WHERE User='') => "ansible_loop_var": "item", "changed" ....

the last bit is: 
TAST [azuracast-db-install : Set up AzuraCast database user]
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exceptin message: (1045,\"Access denied for user 'root'@'localhost' (using password: NO)\")"}

**Comment by Vaalyn** [comment]
Closing this issue as there hasn't been any replies for a month.

Furthermore as of AzuraCast [0.9.5](https://github.com/AzuraCast/AzuraCast/releases/tag/0.9.5) we are no longer supporting new installations via the Ansible ("Traditional" or "Bare-metal") installation type.
