### ISSUE TITLE
Update libopus-dev from 1.1.2 to 1.3.1

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#1478]
This issue relates to #1459 of AzuraCast and [this issue](https://github.com/savonet/liquidsoap/issues/759) on the liquidsoap repo. The maintainer of liquidsoap recommends that we try updating the `libopus-dev` library to a newer version and see if that fixes the problem reported in that issue as LS doesn't do much with the OPUS lib it's probably a bug in that lib and not LS itself. They also can't reproduce the issue with that lib version so this is worth trying it out.

The problem I see atm is that in Ubuntu 18.04 (which is what our radio container image uses as base image) the highest available version through apt is 1.1.2. To install 1.3.1 we'd need to either update the base image to a 19.04 image, build it from [source](https://github.com/xiph/opus) or add a PPA where this version is available.

@SlvrEagle23 Which of these options do you think would be preferable for AzuraCast? As Ubuntu 19.04 is not an LTS release I'm not sure if we want to update to it or not.

**Comment by SlvrEagle23** [comment]
@Vaalyn As a matter of principle, I tend to follow these rules:

 - Prefer LTS releases wherever possible
 - Prefer prebuilt binaries (including PPAs) over source compilation unless absolutely necessary

If there's a PPA for a newer libopus-dev library, we can definitely roll it into our setup.

**Comment by Vaalyn** [comment]
@SlvrEagle23 Okay thanks for the explanation on how to handle this.

I've looked for a PPA that has this version of opus and couldn't find any apart from the official ubuntu repo where it is only available for 19.04. We could try to install the 1.3.1 from the Ubuntu 19.04 and see if that works or not.
