### ISSUE TITLE
Media File upload API endpoint fails because of destination path

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#1479]
**Installation method**
Docker

**Host OS (for Docker installations)**
macOS Mojave

**Describe the bug**
When uploading a file via the new `POST` `/station/{station_id}/files` endpoint the upload will fail with the following error:
```
Error: Argument 2 passed to App\Entity\StationMedia::__construct() must be of the type string, null given, called in /var/azuracast/www/src/Entity/Repository/StationMediaRepository.php on line 42 on /var/azuracast/www/src/Entity/StationMedia.php L224
```

I have looked into why this is and could pin the issue down to this [line](https://github.com/AzuraCast/AzuraCast/blob/master/src/Entity/Repository/StationMediaRepository.php#L34). There the `$dest` will be set to the `$path` from the `UploadFile` which looks for example like this: `test/test.mp3`. The code in that line will try to explode a path by `://` which is not something that someone externally would include in the path thus the `$dest_path` will be null and the construction of the `StationMedia` entity will fail.

**Comment by Vaalyn** [comment]
I've tested what happens when you include the `media://` in the path. This works but I think this is not be something that the client should have to handle. The easiest solution to this problem would be to prepend the path from the `UploadFile` with the `media://` prefix in the `FilesController`.

**Comment by Vaalyn** [comment]
I also tested what happens when you put `albumart://` as prefix into the path which results in the file being written to the album art directory.

**Comment by SlvrEagle23** [comment]
PRs merged!
