### ISSUE TITLE
Installing Problem Ubuntu 14.04 amd64 & 16.04 amd64

### ISSUE THREAD

**Issue by Just-In-Web** [AzuraCast/AzuraCast#148]
Hi, 

I can't install Azuracast on my Server.. Here's the error while installing.

TASK [azuracast-radio : Build LiquidSoap] **************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "opam init -y && opam install -y taglib mad faad fdkaac lame vorbis cry flac liquidsoap.1.2.1", "delta": "0:00:17.597169", "end": "2017-05-29 22:26:43.377140", "failed": true, "rc": 4, "start": "2017-05-29 22:26:25.779971", "stderr": "[NOTE] Package taglib is already installed (current version is 0.3.3).\n[NOTE] Package mad is already installed (current version is 0.4.5).\n[NOTE] Package faad is already installed (current version is 0.3.3).\n[NOTE] Package fdkaac is already installed (current version is 0.2.1).\n[NOTE] Package lame is already installed (current version is 0.3.3).\n[NOTE] Package vorbis is already installed (current version is 0.7.0).\n[NOTE] Package cry is already installed (current version is 0.4.1).\n[NOTE] Package flac is already installed (current version is 0.1.2).\n[ERROR] The compilation of liquidsoap failed at \"make\".\n\n#=== ERROR while installing liquidsoap.1.2.1 ==================================#\n# opam-version         1.2.2\n# os                   linux\n# command              make\n# path                 /var/azuracast/.opam/system/build/liquidsoap.1.2.1\n# compiler             system (4.02.3)\n# exit-code            2\n# env-file             /var/azuracast/.opam/system/build/liquidsoap.1.2.1/liquidsoap-14329-e7966f.env\n# stdout-file          /var/azuracast/.opam/system/build/liquidsoap.1.2.1/liquidsoap-14329-e7966f.out\n# stderr-file          /var/azuracast/.opam/system/build/liquidsoap.1.2.1/liquidsoap-14329-e7966f.err\n### stdout ###\n# [...]\n# OCAMLOPT -c encoder/lame_encoder_builtin.ml\n# OCAMLOPT -c encoder/flac_encoder.ml\n# OCAMLOPT -c encoder/fdkaac_encoder_builtin.ml\n# OCAMLOPT -c encoder/taglib_id3v2.ml\n# OCAMLOPT -c ogg_formats/ogg_muxer.mli\n# OCAMLOPT -c ogg_formats/ogg_muxer.ml\n# OCAMLOPT -c encoder/ogg_encoder.ml\n# OCAMLOPT -c ogg_formats/vorbis_encoder.ml\n# make[2]: Verzeichnis »/var/azuracast/.opam/system/build/liquidsoap.1.2.1/src« wird verlassen\n# make[1]: Verzeichnis »/var/azuracast/.opam/system/build/liquidsoap.1.2.1/src« wird verlassen\n### stderr ###\n# [...]\n# File \"encoder/ogg_encoder.ml\", line 235, characters 4-76:\n# Warning 4: this pattern-matching is fragile.\n# It will remain exhaustive when constructors are added to type Encoder.format.\n# File \"ogg_formats/vorbis_encoder.ml\", line 131, characters 23-49:\n# Error: The function applied to this argument has type\n#          unit -> (string * string) list\n# This argument cannot be applied with label ?title\n# make[2]: *** [ogg_formats/vorbis_encoder.cmx] Fehler 2\n# make[1]: *** [all-auto-ocaml-prog] Fehler 2\n# make: *** [all-subdirs] Fehler 2", "stderr_lines": ["[NOTE] Package taglib is already installed (current version is 0.3.3).", "[NOTE] Package mad is already installed (current version is 0.4.5).", "[NOTE] Package faad is already installed (current version is 0.3.3).", "[NOTE] Package fdkaac is already installed (current version is 0.2.1).", "[NOTE] Package lame is already installed (current version is 0.3.3).", "[NOTE] Package vorbis is already installed (current version is 0.7.0).", "[NOTE] Package cry is already installed (current version is 0.4.1).", "[NOTE] Package flac is already installed (current version is 0.1.2).", "[ERROR] The compilation of liquidsoap failed at \"make\".", "", "#=== ERROR while installing liquidsoap.1.2.1 ==================================#", "# opam-version         1.2.2", "# os                   linux", "# command              make", "# path                 /var/azuracast/.opam/system/build/liquidsoap.1.2.1", "# compiler             system (4.02.3)", "# exit-code            2", "# env-file             /var/azuracast/.opam/system/build/liquidsoap.1.2.1/liquidsoap-14329-e7966f.env", "# stdout-file          /var/azuracast/.opam/system/build/liquidsoap.1.2.1/liquidsoap-14329-e7966f.out", "# stderr-file          /var/azuracast/.opam/system/build/liquidsoap.1.2.1/liquidsoap-14329-e7966f.err", "### stdout ###", "# [...]", "# OCAMLOPT -c encoder/lame_encoder_builtin.ml", "# OCAMLOPT -c encoder/flac_encoder.ml", "# OCAMLOPT -c encoder/fdkaac_encoder_builtin.ml", "# OCAMLOPT -c encoder/taglib_id3v2.ml", "# OCAMLOPT -c ogg_formats/ogg_muxer.mli", "# OCAMLOPT -c ogg_formats/ogg_muxer.ml", "# OCAMLOPT -c encoder/ogg_encoder.ml", "# OCAMLOPT -c ogg_formats/vorbis_encoder.ml", "# make[2]: Verzeichnis »/var/azuracast/.opam/system/build/liquidsoap.1.2.1/src« wird verlassen", "# make[1]: Verzeichnis »/var/azuracast/.opam/system/build/liquidsoap.1.2.1/src« wird verlassen", "### stderr ###", "# [...]", "# File \"encoder/ogg_encoder.ml\", line 235, characters 4-76:", "# Warning 4: this pattern-matching is fragile.", "# It will remain exhaustive when constructors are added to type Encoder.format.", "# File \"ogg_formats/vorbis_encoder.ml\", line 131, characters 23-49:", "# Error: The function applied to this argument has type", "#          unit -> (string * string) list", "# This argument cannot be applied with label ?title", "# make[2]: *** [ogg_formats/vorbis_encoder.cmx] Fehler 2", "# make[1]: *** [all-auto-ocaml-prog] Fehler 2", "# make: *** [all-subdirs] Fehler 2"], "stdout": "OPAM has already been initialized.\nIn normal operation, OPAM only alters files within ~/.opam.\n\nDuring this initialisation, you can allow OPAM to add information to two\nother files for best results. You can also make these additions manually\nif you wish.\n\nIf you agree, OPAM will modify:\n\n  - ~/.bash_profile (or a file you specify) to set the right environment\n    variables and to load the auto-completion scripts for your shell (bash)\n    on startup. Specifically, it checks for and appends the following line:\n\n    . /var/azuracast/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true\n\n\n  - ~/.ocamlinit to ensure that non-system installations of `ocamlfind`\n    (i.e. those installed by OPAM) will work correctly when running the\n    OCaml toplevel. It does this by adding $OCAML_TOPLEVEL_PATH to the list\n    of include directories.\n\nIf you choose to not configure your system now, you can either configure\nOPAM manually (instructions will be displayed) or launch the automatic setup\nlater by running:\n\n   opam config setup -a\n\n\nDo you want OPAM to modify ~/.bash_profile and ~/.ocamlinit?\n(default is 'no', use 'f' to name a file other than ~/.bash_profile)\n    [N/y/f] \nGlobal configuration:\n  ~/.opam/opam-init/init.sh is already up-to-date.\n  ~/.opam/opam-init/init.zsh is already up-to-date.\n  ~/.opam/opam-init/init.csh is already up-to-date.\n  ~/.opam/opam-init/init.fish is already up-to-date.\n\n=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n\n1. To configure OPAM in the current shell session, you need to run:\n\n      eval `opam config env`\n\n2. To correctly configure OPAM for subsequent use, add the following\n   line to your profile file (for instance ~/.bash_profile):\n\n      . /var/azuracast/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true\n\n3. To avoid issues related to non-system installations of `ocamlfind`\n   add the following lines to ~/.ocamlinit (create it if necessary):\n\n      let () =\n        try Topdirs.dir_directory (Sys.getenv \"OCAML_TOPLEVEL_PATH\")\n        with Not_found -> ()\n      ;;\n\n=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n\nThe following actions will be performed:\n  ∗  install liquidsoap 1.2.1\n\n=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n[liquidsoap] Archive in cache\n\n=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n[liquidsoap: ./configure] Command started\n[liquidsoap: make] Command started\n[liquidsoap: rm] Command started\n\n\n=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\nThe following actions failed\n  ∗  install liquidsoap 1.2.1\nNo changes have been performed", "stdout_lines": ["OPAM has already been initialized.", "In normal operation, OPAM only alters files within ~/.opam.", "", "During this initialisation, you can allow OPAM to add information to two", "other files for best results. You can also make these additions manually", "if you wish.", "", "If you agree, OPAM will modify:", "", "  - ~/.bash_profile (or a file you specify) to set the right environment", "    variables and to load the auto-completion scripts for your shell (bash)", "    on startup. Specifically, it checks for and appends the following line:", "", "    . /var/azuracast/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true", "", "", "  - ~/.ocamlinit to ensure that non-system installations of `ocamlfind`", "    (i.e. those installed by OPAM) will work correctly when running the", "    OCaml toplevel. It does this by adding $OCAML_TOPLEVEL_PATH to the list", "    of include directories.", "", "If you choose to not configure your system now, you can either configure", "OPAM manually (instructions will be displayed) or launch the automatic setup", "later by running:", "", "   opam config setup -a", "", "", "Do you want OPAM to modify ~/.bash_profile and ~/.ocamlinit?", "(default is 'no', use 'f' to name a file other than ~/.bash_profile)", "    [N/y/f] ", "Global configuration:", "  ~/.opam/opam-init/init.sh is already up-to-date.", "  ~/.opam/opam-init/init.zsh is already up-to-date.", "  ~/.opam/opam-init/init.csh is already up-to-date.", "  ~/.opam/opam-init/init.fish is already up-to-date.", "", "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=", "", "1. To configure OPAM in the current shell session, you need to run:", "", "      eval `opam config env`", "", "2. To correctly configure OPAM for subsequent use, add the following", "   line to your profile file (for instance ~/.bash_profile):", "", "      . /var/azuracast/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true", "", "3. To avoid issues related to non-system installations of `ocamlfind`", "   add the following lines to ~/.ocamlinit (create it if necessary):", "", "      let () =", "        try Topdirs.dir_directory (Sys.getenv \"OCAML_TOPLEVEL_PATH\")", "        with Not_found -> ()", "      ;;", "", "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=", "", "The following actions will be performed:", "  ∗  install liquidsoap 1.2.1", "", "=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=", "[liquidsoap] Archive in cache", "", "=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=", "[liquidsoap: ./configure] Command started", "[liquidsoap: make] Command started", "[liquidsoap: rm] Command started", "", "", "=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=", "The following actions failed", "  ∗  install liquidsoap 1.2.1", "No changes have been performed"]}

RUNNING HANDLER [azuracast-user : send user notification] **********************
        to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP *********************************************************************
localhost                  : ok=23   changed=4    unreachable=0    failed=1

Hope you can help..

Sincerly,
Justin

**Comment by SlvrEagle23** [comment]
@Just-In-Web Seems something new has come down the pipe in OPAM and it's causing LiquidSoap's compilation to fail on all new builds. I'm getting the same problem across the board. Looking into it now and will fix ASAP.

**Comment by SlvrEagle23** [comment]
@Just-In-Web The installation process for new stations should be working as normal now. Thanks for your patience. :)
