### ISSUE TITLE
Issues with external M3U/PLS playlists

### ISSUE THREAD

**Issue by ivellios1988** [AzuraCast/AzuraCast#1480]
There seems to be some issue with playlists downloaded from external servers. I found the 'external playlists' feature to be very useful so I decided to test it on my AzuraCast installation. From what I observed, AzuraCast (or Liquidsoap?) completely ignores M3U playlists and only plays contents of PLS playlists. What's more, only playlists with links to MP3s using HTTP will be played. In case of HTTPS, Liquidsoap says it's unable to determine the MIME type and skips the file.

Steps to reproduce:
1) Create four playlists:
- M3U with links to MP3s starting with HTTP
- M3U with links to MP3s starting with HTTPS
- PLS with links to MP3s starting with HTTP
- PLS with links to MP3s starting with HTTPS
and then place them on your external server and put links to them in Playlists section in your AzuraCast panel.

2) Restart Liquidsoap, play your stream and observe logs of Liquidsoap.

In case of M3U (both with links to MP3s using HTTP as well as HTTPS), no MP3s will be played. Instead, Liquidsoap will skip to the next file and put something like this into the log:

2019/04/26 15:45:00 [lang:3] AzuraCast Raw Response: http://example.com/file.MP3
2019/04/26 15:45:00 [procol.external:3] Failed to fetch mime-type for http://example.com/file.MP3.
2019/04/26 15:45:00 [procol.external:3] No known file extension for mime: 
2019/04/26 15:45:00 [decoder:3] Unable to decode "/tmp/liq-process965100.osb" as {audio=1+;video=0;midi=0}!

So, it looks like the file is downloaded into tmp/ folder, however, for some reason Liquidsoap is unable to decode and play it.

In case of PLS playlists containing links starting with HTTPS, your MP3 files will not be downloaded at all. Here's what Icecast puts in a log file:

2019/04/26 15:51:20 [protocol.process:3] Failed to execute curl -sL "https://example.com/file.MP3" -o "/tmp/liq-process588e06.osb": ("timeout","19.8270530701")
2019/04/26 15:51:20 [lang:3] AzuraCast Raw Response: https://example.com/file.MP3
Certificate[2] subject=/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
Certificate[2] issuer =/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
SSL: rejecting connection - error=20
2019/04/26 15:51:20 [procol.external:3] Failed to fetch mime-type for https://example.com/file.MP3.
2019/04/26 15:51:20 [procol.external:3] No known file extension for mime: 
2019/04/26 15:51:26 [decoder:3] Unable to decode "/tmp/liq-process0ee786.osb" as {audio=1+;video=0;midi=0}!

PLS playlists containing links to MP3s starting with HTTP will be played correctly.

My system: Ubuntu 18.04 LTS
AzuraCast installed using Docker, up-to-date

**Comment by Vaalyn** [comment]
Thank you for testing that functionality so extensively and writing this very detailed report.

I think wile researching a bit about Liquidsoap, remote playlists, HTTPS streams and media players for one of these issues #1435, #1430 I read something about setting the mime-type for remote playlists that I think could be related to the behaviour with HTTPS links here. I'm not completely sure so I'll have to dig through my browser history and see if I can find that page again.

**Comment by ivellios1988** [comment]
I'm doing all these tests with OPUS, playlists, etc. mainly because I'd like to switch from Centova Cast to AzuraCast. Centova Cast is a commercial software but it offers much less functionality than AzuraCast currently does. Not to mention Centova Cast's panel is completely unresponsive and, despite many years of promises, still even using it on a computer can sometimes be a real pain. And no translations to other languages... Centova Cast lacks many things and useful functionalities AzuraCast has to offer.

Right now I detected another issue with PLS playlists that are played correctly. In PLS file we have things like Title1, Title2, Title3... etc. - titles of each MP3. However, those titles are not shown on station's page, and they aren't shown in the title bar in external player as well. Liquidsoap seems to only 'remember' the title of the last MP3 that was played directly from the server containing my AzuraCast installation (in my case it is 'AzuraCast is live!').

What's more, no matter how many MP3s are included in a PLS, AzuraCast seems to be unable to count them and in Playlists section PLS playlists shown as containing 0 songs.

MP3s are played only if the PLS file is placed on an external server. When I upload the PLS file directly in the Playlists section, MP3s are not played at all. Probably AzuraCast can't even download them, since no filenames are put in Liquidsoap's log file.

**Comment by Vaalyn** [comment]
The reason I joined the AzuraCast team was also because I wanted something better than Centova Cast for my radio and I knew the predecessor project of AzuraCast. Then I started testing it found something that was missing and just submitted a PR to add the functionality. Since then I continually contribute stuff, mainly time for issues. 😄 

Can you share some .m3u and .pls files that you know cause these issues, that would help us testing these issues faster and ensures that we use the same setup when trying to reproduce them. I'll try to reproduce them and see where this is coming from then.

**Comment by ivellios1988** [comment]
Yeah, definitely, being available for free is just one of many advantages of AzuraCast :D This suite actually eliminates a lot of costs, including the cost of storage space for AutoDJ, since it's capable of playing MP3s located on external servers. It needs a huge promotion.

I attach all playlists I tested. Only the 'lots-of-mp3s.pls' is played correctly.

[lots-of-mp3s.zip](https://github.com/AzuraCast/AzuraCast/files/3123143/lots-of-mp3s.zip)

**Comment by ivellios1988** [comment]
Another issue with external playlists: mp3's are not removed from the /tmp/ directory after the've been played. Instead, they keep being stored in this directory, which after some time may result in AzuraCast crashing completely because of no space left on the disk.

**Comment by SlvrEagle23** [comment]
@ivellios1988 I've looked through the configuration of Liquidsoap to see if there's a way to customize where it puts its temporary files, and apparently there is no way of customizing that at the moment. This is likely an upstream issue that should be brought up on the [Liquidsoap](https://github.com/savonet/liquidsoap) repository.

**Comment by ivellios1988** [comment]
I'll try to bring it up to them later, for now I temporarily solved the issue by using a Cron task that removes all mp3s from temporary folder every 6 hours.

**Comment by SlvrEagle23** [comment]
@ivellios1988 I've updated the Docker stations container to automatically clean up the /tmp directory every few hours, which should help prevent the system from running out of space over time. I will apply this same fix to the Ansible installations shortly.

**Comment by deepend81** [comment]
I have had the same issues, except even with non-ssl urls curl just comes back when timeout errors. Not sure why.   If I run the exact curl command in the terminal it works just fine.. so I'm at a loss?

**Comment by SlvrEagle23** [comment]
@deepend81 Is this issue with the Docker installation or not? You should make sure you're running the latest version of Liquidsoap as of our newest updates; if you're using Docker, make sure your `docker-compose.yml` is updated to use the latest containers.

**Comment by deepend81** [comment]
@SlvrEagle23
Not using docker.  Thanks for the reply :). And did update everything to current which improved it a bit but still not working reliably.  I can sometimes get it to play 1 song on the remote playlist and then stop working.
