### ISSUE TITLE
Live streaming metadata problem and some more

### ISSUE THREAD

**Issue by br0kenlink** [AzuraCast/AzuraCast#1482]
**Installation method**

Docker
**Host OS (for Docker installations)**

Centos 7
**Describe the bug**

Firstly, 
I have noticed if nobody connects to live stream, and just jingle goes on and on, after some time, not sure how long it takes, when you connect, it shows you are connected in Butt, although Azuracast doesn't show it also when you try to click play on public page it simply don't work. Restart of liquidsoap did seem to fix it. Happened quite few times recently, can't be sure after which update though.
Secondly, 
doing updates regularly. Today noticed, after I connected just to test if it works. It keeps showing metadata even after I disconnect. So like the jingle is playing but metadata stays from my live set title. I send custom metadata from Butt on connection, used to work just fine. Once you were disconnecting, it was showing Stream Offline, while the jingle was playing non stop.

**Relevant Logs**

> 2019/04/26 17:03:17 [lang:3] Jingle mode; stripping metadata...
2019/04/26 17:03:20 [lang:3] Authenticating DJ: binia
2019/04/26 17:03:20 [lang:3] AzuraCast DJ Auth Response: true
2019/04/26 17:03:20 [decoder:3] Method "MAD" accepted "audio/mpeg".
2019/04/26 17:03:20 [lang:3] DJ Source connected! [("Host","broken.radio:8035"), ("icy-name","Binia"), ("icy-genre","techno"), ("icy-pub","1"), ("icy-br","256"), ("content-type","audio/mpeg")]
2019/04/26 17:03:20 [live_live_switch:3] Switch to live_live_fallback with transition.
2019/04/26 17:03:20 [lang:3] Authenticating DJ: shoutcast
2019/04/26 17:03:20 [live_live_fallback:3] Switch to blank_6468 with forgetful transition.
2019/04/26 17:03:20 [lang:3] AzuraCast DJ Auth Response: true
2019/04/26 17:03:20 [live_input_streamer:3] New metadata chunk ? -- binia - testing the soundcard.
2019/04/26 17:03:20 [lang:3] AzuraCast Live Connected Response: received
2019/04/26 17:03:20 [threads:3] Created thread "harbor source feeding" (2 total).
2019/04/26 17:03:20 [live_input_streamer:3] Decoding...
2019/04/26 17:03:30 [live_live_fallback:3] Switch to audio_to_stereo_6465 with transition.
2019/04/26 17:03:31 [lang:3] AzuraCast Raw Response: annotate:title="binia- test",duration="8.",song_id="67881b755a766d0a12f36d18ae909955",genre="41",jingle_mode="true":/var/azuracast/stations/live/media/blr-live-1.wav
2019/04/26 17:03:31 [decoder:3] Method "WAV" accepted "/var/azuracast/stations/live/media/blr-live-1.wav".
2019/04/26 17:05:08 [live_input_streamer:2] Feeding stopped: Mad.End_of_stream.
2019/04/26 17:05:08 [lang:3] DJ Source disconnected!
2019/04/26 17:05:08 [live_live_switch:3] Switch to map_metadata_6448 with transition.
2019/04/26 17:05:08 [lang:3] AzuraCast Live Disconnected Response: received
2019/04/26 17:05:08 [threads:3] Thread "harbor source feeding" terminated (1 remaining).
2019/04/26 17:05:11 [lang:3] AzuraCast Raw Response: annotate:title="testing the soundcard",artist="binia",duration="8.",song_id="67881b755a766d0a12f36d18ae909955",genre="41",jingle_mode="true":/var/azuracast/stations/live/media/blr-liv$
2019/04/26 17:05:11 [decoder:3] Method "WAV" accepted "/var/azuracast/stations/live/media/blr-live-1.wav".
2019/04/26 17:05:12 [live_next_song:3] Finished with "/var/azuracast/stations/live/media/blr-live-1.wav".
2019/04/26 17:05:12 [live_next_song:3] Prepared "/var/azuracast/stations/live/media/blr-live-1.wav" (RID 17).
2019/04/26 17:05:12 [lang:3] Jingle mode; stripping metadata...
2019/04/26 17:05:15 [dummy:3] Source failed (no more tracks) stopping output...
2019/04/26 17:05:17 [live_next_song:3] Finished with "/var/azuracast/stations/live/media/blr-live-1.wav".
2019/04/26 17:05:17 [live_next_song:3] Prepared "/var/azuracast/stations/live/media/blr-live-1.wav" (RID 18).
2019/04/26 17:05:17 [lang:3] Jingle mode; stripping metadata...
2019/04/26 17:05:21 [live_next_song:3] Finished with "/var/azuracast/stations/live/media/blr-live-1.wav".
2019/04/26 17:05:21 [live_autodj_fallback:3] Switch to random_6425 with forgetful transition.
2019/04/26 17:05:25 [decoder:3] Method "WAV" accepted "/var/azuracast/stations/live/media/blr-live-1.wav".
2019/04/26 17:05:26 [playlist_jingle:3] Finished with "/var/azuracast/stations/live/media/blr-live-1.wav".
2019/04/26 17:05:26 [playlist_jingle:3] Prepared "/var/azuracast/stations/live/media/blr-live-1.wav" (RID 16).
2019/04/26 17:05:30 [decoder:3] Method "WAV" accepted "/var/azuracast/stations/live/media/blr-live-1.wav".
2019/04/26 17:05:31 [playlist_jingle:3] Finished with "/var/azuracast/stations/live/media/blr-live-1.wav".
2019/04/26 17:05:31 [playlist_jingle:3] Prepared "/var/azuracast/stations/live/media/blr-live-1.wav" (RID 19).
2019/04/26 17:05:35 [decoder:3] Method "WAV" accepted "/var/azuracast/stations/live/media/blr-live-1.wav".
2019/04/26 17:05:35 [playlist_jingle:3] Finished with "/var/azuracast/stations/live/media/blr-live-1.wav".
2019/04/26 17:05:35 [playlist_jingle:3] Prepared "/var/azuracast/stations/live/media/blr-live-1.wav" (RID 20).
2019/04/26 17:05:39 [decoder:3] Method "WAV" accepted "/var/azuracast/stations/live/media/blr-live-1.wav".
2019/04/26 17:05:40 [playlist_jingle:3] Finished with "/var/azuracast/stations/live/media/blr-live-1.wav".
2019/04/26 17:05:40 [playlist_jingle:3] Prepared "/var/azuracast/stations/live/media/blr-live-1.wav" (RID 21).
2019/04/26 17:05:40 [lang:3] AzuraCast Raw Response: annotate:title="testing the soundcard",artist="binia",duration="8.",song_id="67881b755a766d0a12f36d18ae909955",genre="41",jingle_mode="true":/var/azuracast/stations/live/media/blr-liv$ <

**Comment by Vaalyn** [comment]
If I didn't misunderstood the setup then the AutoDJ only plays playlists with jingles in them and have the `Jingle Mode` active, which will strip their metadata / prevents the metadata from being used. When a DJ disconnects and a jingle mode playlist starts playing the metadata will be updated to the metadata of the last song that was playing which was the last song that the Live DJ played. In this case we should set the metadata back to some default. @SlvrEagle23 Do we have some default metadata that we already use for something? Showing `Stream Offline` seems not correct to me since the stream is still playing something.

**Comment by br0kenlink** [comment]
I have to do some more testing but it seems, I have to literally restart whole Azuracast to get my live stream relayed to public player. If I don't there will be no sound nor metadata shown on public page.
I will disable playlist with a jingle and see if I can get same error. Will post logs later on.
