### ISSUE TITLE
Streamer name in frontend

### ISSUE THREAD

**Issue by cnecrea** [AzuraCast/AzuraCast#1483]
Hi there,

Is any possibility to show on frondend page if there is streaming a DJ and what is his name?

(just like into the photo attached)

![2019-04-27_1-13-01](https://user-images.githubusercontent.com/48139709/56840800-e26b4580-6889-11e9-9f01-19646696e4a5.png)

I was searching into settings but I cannot find.

**Comment by SlvrEagle23** [comment]
@cnecrea Currently the public player view of AzuraCast doesn't show the live DJ's name. This would be a new feature request, which you can submit on https://features.azuracast.com/ .
