### ISSUE TITLE
Autoplay function iframe does not work

### ISSUE THREAD

**Issue by danielrodrigotest** [AzuraCast/AzuraCast#1486]
Hi.
I'm using the iframe player code and I found **/autoplay**. After latest updates, autoplay fuction doesn't work. I would like to know any form to use again autoplay with iframe codes. 
Thanks

**Comment by Vaalyn** [comment]
The autoplay functionality was removed with the changes to the player a while back.
See issue #1355 for further information and a small script to add it back in for your player.
