### ISSUE TITLE
Add validation for all port assignments via the web interface

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#1488]
Since we already had several issues in the past from users who had a problem with stations not starting due to ports already being assigned I think we could improve the UX of AzuraCast by adding a validation wherever a port can be assigned to check if that is already in use and prevent these issues before they can happen.

**Comment by SlvrEagle23** [comment]
@Vaalyn But we do! In fact, I moved it from a form-level validator to a Symfony Validator-level one applied to the Station entity specifically because I wanted even the API calls to get the same validation. I tested it locally and it does appear to be kicking in when you use a duplicate port.

**Comment by Vaalyn** [comment]
@SlvrEagle23 Oh I didn't notice that, when did you add this? It's strange though as issue #1485 and #1469 were both issues were a port was already assigned to something and it didn't look like something was preventing them from using these ports from the web applications side. If that validation is a more recent addition it could be though that the versions of their installations weren't updated to a version with that yet.

**Comment by SlvrEagle23** [comment]
@Vaalyn It's possible the validations aren't working in certain edge cases, but they've been there in some shape or form for many months now. As I was building out the Station management API endpoint, I was also building that validator and moving it over, so it existed the whole time that endpoint was live.

**Comment by Vaalyn** [comment]
I've tested the validator a bit with my local installation and found a few things:

Most important:
- Correctly prevents duplicate usage of the port for the `Broadcasting Port`
- Does not prevent duplicate usage of the ports for `DJ/Streamer Port` and `Internal Request Processing Port`

Bonus:
- Does not prevent setting the `DJ/Streamer Port` to a port that is n-1 of an already used one
  - The `Note` for that field says: `The port after this one (n+1) will automatically be used for legacy connections.` so this should also be prevented
- Does not prevent setting a port to a value that is used by the n+1 for `DJ/Streamer Port`
  - The n+1 ports are not saved to the DB and thus not part of the used ports list
- Does not prevent setting a port to a value that is used in the same station (yes stupid error but can happen)

This is what I did to test the validator:

- Create a station with the ports 8000 (Broadcasting), 8005 (DJ/Streamer), 8004 (Internal)
- Create another station and try to assign the same ports
- This will initially fail because of the duplicate usage of port 8000 for Broadcasting
- After changing the Broadcasting port to 8001 it will save the new station with the duplicate ports 8005/8006 and 8004 assigned to it

I've also looked into why this might be and found that the `$used_ports` only contained this:
```
Array
(
    [8000] => Array
        (
            [id] => 1
            [name] => AzuraTest Radio
        )

)
```

When I looked into the the Radio/Configuration.php to see how the `getUsedPorts()` method works I noticed that the wrong variable is used in [this](https://github.com/AzuraCast/AzuraCast/blob/3554d65c756e0bd5201f333e8639a247cdaf2505/src/Radio/Configuration.php#L338) and [this](https://github.com/AzuraCast/AzuraCast/blob/3554d65c756e0bd5201f333e8639a247cdaf2505/src/Radio/Configuration.php#L342) line. It says `$frontend_*` but it should be `$backend_*`.

I have prepared a PR to fix the variable and add the check for `DJ/Streamer Port`. What's still missing is checking for the n+1 port of other stations and checking for duplicate usage in the station that is currently being validated.

**Comment by SlvrEagle23** [comment]
@Vaalyn Your PR is merged, and in the case of adding port+1 to the list of ports, it really is just as easy as appending another key to that lookup array in that same `getUsedPorts` function. That functionality is solely used for port validation and auto-assignment so there aren't any side effects to doing that. I just implemented that in the latest commit, so overall the process should be more foolproof. :)
