### ISSUE TITLE
Schedule resets at 00UTC on schedules going over midnight.

### ISSUE THREAD

**Issue by Scraticus** [AzuraCast/AzuraCast#1491]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 18.04

**Describe the bug**
When a schedule is set to go over midnight, the liq is not configured to continue the next day. It will fall back to whatever was in the pipe.

**To Reproduce**
Steps to reproduce the behaviour:
1. set a playlist which goes past midnight

**Expected behavior**
the expected behaviour is the playlist continues past midnight, and the .liq is not set for this.

**Relevant Logs**

The liq configuration shows:

radio = switch(track_sensitive=true, [ ({ (6w) and 20h0m-3h0m }, playlist_ponies_at_dawn_skyward_album_release), ({true}, radio) ])

**Screenshots**

radio = switch(track_sensitive=true, [ ({ (6w) and 20h0m-3h0m }, playlist_ponies_at_dawn_skyward_album_release), ({true}, radio) ])

the 7w 0h0m to 3h0m is missing.

**Device(s):**
N/A

**Additional context**

**Comment by SlvrEagle23** [comment]
@Scraticus I've updated the Liquidsoap configuration writing code to properly handle when a scheduled playlist is set to roll into the next day (i.e. has an end time earlier than its start time when converted to UTC). Please let me know if this resolves the issue in your given scenario; in my local tests it should resolve it.

**Comment by SlvrEagle23** [comment]
I'm assuming this is resolved at this point and closing it as such. Let me know if it's still causing any problems.
