### ISSUE TITLE
Station's data is not removed from the server when you remove the station in AzuraCast panel

### ISSUE THREAD

**Issue by ivellios1988** [AzuraCast/AzuraCast#1495]
System: Ubuntu 18.04 LTS
Installation method: Docker

When removing stations, AzuraCast doesn't automatically delete their data from the server.

Steps to reproduce:
1) create some stations in your AzuraCast panel, then put some mountpoints, mp3s, etc.
2) now remove these stations
3) login to your server via SFTP and go to /var/lib/docker/volumes/azuracast_station_data/_data

The removed stations' data (including mp3s, liquidsoap settings, etc.) will still be there; you will need to remove them manually.

**Comment by Vaalyn** [comment]
@ivellios1988 How are the stations set up, are they having their own data directory or do they share one directory?

In general the code for removing the media data directory is [there](https://github.com/AzuraCast/AzuraCast/blob/master/src/Entity/Repository/StationRepository.php#L202). So something must be going wrong here. Are there any errors in the applications log?

**Comment by SlvrEagle23** [comment]
@ivellios1988 Thanks to @Vaalyn who found the problem and has patched a fix in, which is now merged into the main repository and should resolve this issue.
