### ISSUE TITLE
Problems with cloning stations

### ISSUE THREAD

**Issue by ivellios1988** [AzuraCast/AzuraCast#1496]
System: Ubuntu 18.04 LTS
Installation method: Docker

I observed some issues with cloning stations in AzuraCast.

Steps to reproduce (or 'What Ivellios did just a moment ago'):
1) login to your AzuraCast oanel and go to Administration->Stations
2) clone some radio station with the following settings: copy existing media to a new station, copy playlists, copy streamer/DJ account, copy priveleges
3) click 'create new station'

After that, AzuraCast shows the following error:

500
Return value of App\Entity\StationPlaylist::getBackendOptions() must be of the type array, null returned
StationPlaylist.php : 711

4) go to homepage of your AzuraCast panel

The cloned station will, of course, appear on the list, but...

5) click 'Manage' and see if anything is working correctly

Results?
- IceCast and Liquidsoap are 'loading' all the time, restarting them results in errors (they both show: BAD_NAME: station_9:station_9_frontend)
- station's port for broadcasting is set to 8000 (which in my case is the lowest possible), which is already assigned to other station
- the same thing applies to streamer/DJ ports (set to 8005, 8006)
- streamer/DJ accounts have not been copied at all, the list of accounts is empty

**Comment by Vaalyn** [comment]
The same problem is also happening by just trying to create a station. I just found that happening on my local dev installation.

**Comment by SlvrEagle23** [comment]
@ivellios1988 Fixed per @Vaalyn's latest PR, which is merged into the main repository. Update and it should be resolved. Thank you for the report. :)
