### ISSUE TITLE
Use different AAC codec with higher bitrates

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#1499]
Hello,

i found out that Azuracast always want to use the Codec HE-AAC v2 for aac.
But HE-AAC v2 only Supports up to 64 kb/s.
HE-AAC only supports up to 128 kb/s.
AAC-LC Supports up to 320 kb/s.

**Comment by Vaalyn** [comment]
[Here](https://github.com/LibreTime/libretime/blob/dea59558a2047ab21e14278ed7a85e85317614a9/python_apps/pypo/liquidsoap/fdkaac.liq) is a script that LibreTime uses to decide between the codecs for different bitrates. With that we have some guidelines on when to use what. I think we should handle that similar and switch between v2 and LC depending on the chosen bitrate.

**Comment by SlvrEagle23** [comment]
@preterive @Vaalyn This is now implemented in the code. It is likely the cause of some other issues relating to AAC encoding, so I will mark those as most likely resolved as well.
