### ISSUE TITLE
Scheduling (SPOT)

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#1502]
Hello,
Scheduling playlist for commercials. It only plays an audio, instead of playing all in sequence. If I want to play all my commercials, I have to put them together in an audio editing program, to get an audio only and to play the playlist. Can a playlist play multiple audio streams? or does she just play an audio and jump to playlits General Rotation?

I updated, rebooted and nothing. Can someone help me?

**Comment by Vaalyn** [comment]
When you want the complete jingle playlist to play when scheduled you should use the new `"Merge playlist to play as a single track` option. See #1458 for more information.
