### ISSUE TITLE
docker-compose.override.yml is not working?

### ISSUE THREAD

**Issue by dreinn** [AzuraCast/AzuraCast#1504]
Hello, I'm using a docker installation.
I need to change port 80 to 81 and 8000 to 8004.
I changed port 80 to 81 using the .env file and it is working.
Instead, I changed the other port in the docker-compose.yml file, then I take an exact copy and renamed to docker-compose.override.yml, and I have updated the docker-compose.yml to have the latest version.
Unfortunately it seems that the system doesn't use docker-compose.override.yml, since Azuracast want to connect to port 8000.

Is there a manner to force Azuracast to consider that file?

**Comment by SlvrEagle23** [comment]
@dreinn In the case of port mappings, you can only add new port mappings, not remove existing ones via a `docker-compose.override.yml` file. Your initial idea of using the `.env` file to set the custom ports for HTTP/HTTPS is the correct way to do this in a way that makes sure the changes won't be deleted with updates.

**Comment by dreinn** [comment]
Ok, I understand. But can I add the port mapping of port 8000 to 8004 in the .env file?  Is it possible?

**Comment by SlvrEagle23** [comment]
@dreinn Probably not, since there's already a mapping from the guest's port 8000 to the host's port 8000 and it wouldn't override that.

You can always just update the port you're broadcasting from via the AzuraCast web interface, then expose port 8004 directly via a new `8004:8004` port mapping.
