### ISSUE TITLE
Can't connect to my panel with Yandex Browser

### ISSUE THREAD

**Issue by Oldarorn** [AzuraCast/AzuraCast#1508]
**Using Docker installation method**

Yes

**Host Operating System**

Debian 9.8

**Describe the bug**

Well, I've tried with Firefox and Chrome and it works like a charm but when I use Yandex Browser I can't connect to my panel, I write my IDs, press connect, it loads and I'm back on the login page which ask for my IDs. Yandex is known for being a kind of Opera Browser fork, so, maybe we can encounter the same issue with Opera.

**To Reproduce**
The only way to reproduce it is by using Yandex (in my opinion)

**Expected behavior**

I'm supposed to be connected to my panel
**Relevant Logs**

No particular logs, if you which something (browser logs maybe) feel free to ask, I don't know what should I provide right now.

**Comment by Vaalyn** [comment]
Hey, would you mind looking into the browsers JavaScript console, enable preservation of logs so that a page reload doesn't wipe them clean, and post any errors here?

**Comment by Oldarorn** [comment]
Hi,

Here is what I get in my console :

![image](https://user-images.githubusercontent.com/36448848/57248823-abdcba00-7043-11e9-9ed9-1383c53355b7.png)

**Comment by SlvrEagle23** [comment]
@Oldarorn That's a problem with an extension you have enabled, not with AzuraCast in particular...try disabling your extensions to see if that fixes it?

**Comment by Oldarorn** [comment]
@SlvrEagle23 I've disabled everything, now I get no error but I still can't connect, I enter my IDs (and I'm sure I'm not doing any mistake) and nothing happens

**Comment by Vaalyn** [comment]
@Oldarorn @SlvrEagle23 I've downloaded the Yandex Browser and tried to log-in to the demo installation at demo.azuracast.com and I had no problems with that. This seems to not be an issue with the browser itself.

**Comment by Oldarorn** [comment]
Well, I think I have to investigate myself and go deeper, I close the issue then, thanks anyway for your time and sorry !
