### ISSUE TITLE
Only see max 15 stream accounts via API

### ISSUE THREAD

**Issue by pilovali** [AzuraCast/AzuraCast#1509]
**Using Docker installation method**

No. 

**Host Operating System**
 Ubuntu 18.04.2 LTS, 64-bit 

**Describe the bug**

I cannot see more than 15 stream account entries when running https://xxxxx/api/station/2/streamers.

**To Reproduce**
 1. Create more than 15 accounts.
2. Use a GET https://xxxxx/api/station/{ID}/streamers and it should show no more than 15 entries.

**Expected behavior**
 It should show all of the stream accounts.

**Relevant Logs**
 I don't know which logs are related. Can't find any related error messages.

**Screenshots**

API output: https://share.pilovali.nl/1Ga2WTab.png
Webinterface: https://share.pilovali.nl/5Oe7fTdb.png

**Device(s):**
 - Device:  Desktop
 - OS:  Win10
 - Browser:  FF
 - Version: 66.0.3

**Additional context**

Or I'm being stupid again, or theres something wrong.

**Comment by SlvrEagle23** [comment]
@pilovali Do you not see pagination data at the bottom of the API response? By default, responses that are large and thus possibly could bog down the API are paginated. You can specify a `per_page` parameter to customize this, or set that same parameter to `-1` to disable pagination entirely.

**Comment by pilovali** [comment]
> 
> 
> @pilovali Do you not see pagination data at the bottom of the API response? By default, responses that are large and thus possibly could bog down the API are paginated. You can specify a `per_page` parameter to customize this, or set that same parameter to `-1` to disable pagination entirely.

No, I do not see the pagination data (or I don't know how to look for them :P).
Sorry for asking, but where can I set the parameter?

**Comment by SlvrEagle23** [comment]
@pilovali Yep, query string. If you don't see pagination controls that could be an actual bug, you should be seeing the current page number, total pages, etc. along with links to first/prev/next/last page inside the JSON response somewhere.

**Comment by pilovali** [comment]
This is the raw JSON output I get:
`[{"id":1,"streamer_username":"Xander","streamer_password":"xxxx","display_name":"Xander","comments":"","is_active":true,"links":{"self":"https:\/\/azura.xxxx\/api\/station\/2\/streamer\/1"}},{"id":8,"streamer_username":"MgD","streamer_password":"xxxx","display_name":"MgD","comments":"","is_active":true,"links":{"self":"https:\/\/azura.xxxx\/api\/station\/2\/streamer\/8"}},{"id":9,"streamer_username":"MaZika","streamer_password":"xxx","display_name":"MaZika","comments":"","is_active":true,"links":{"self":"https:\/\/azura.xxxx\/api\/station\/2\/streamer\/9"}},{"id":11,"streamer_username":"norman","streamer_password":"xxxx","display_name":"Norman","comments":"","is_active":true,"links":{"self":"https:\/\/azura.xxxx\/api\/station\/2\/streamer\/11"}},{"id":18,"streamer_username":"MicroNano","streamer_password":"xxxx","display_name":"MicroNano","comments":"","is_active":true,"links":{"self":"https:\/\/azura.xxxx\/api\/station\/2\/streamer\/18"}},{"id":22,"streamer_username":"Pilovali","streamer_password":"xxxx","display_name":"TEST DJ","comments":"","is_active":true,"links":{"self":"https:\/\/azura.xxxx\/api\/station\/2\/streamer\/22"}},{"id":24,"streamer_username":"ecel05","streamer_password":"xxxx","display_name":"Ecel05","comments":"","is_active":true,"links":{"self":"https:\/\/azura.xxxx\/api\/station\/2\/streamer\/24"}},{"id":26,"streamer_username":"source","streamer_password":"xxxx","display_name":"Xander","comments":"Legacy DJ account. Please do not remove!","is_active":true,"links":{"self":"https:\/\/azura.xxxx\/api\/station\/2\/streamer\/26"}},{"id":27,"streamer_username":"Shezzar","streamer_password":"xxxx","display_name":"Shezzar","comments":"","is_active":true,"links":{"self":"https:\/\/azura.xxxx\/api\/station\/2\/streamer\/27"}},{"id":29,"streamer_username":"Synax","streamer_password":"xxxx","display_name":"Synax","comments":"","is_active":true,"links":{"self":"https:\/\/azura.xxxx\/api\/station\/2\/streamer\/29"}},{"id":32,"streamer_username":"Jokey","streamer_password":"xxxx","display_name":"Jokey","comments":"","is_active":true,"links":{"self":"https:\/\/azura.xxxx\/api\/station\/2\/streamer\/32"}},{"id":34,"streamer_username":"Suix","streamer_password":"xxxx","display_name":"Suix86","comments":"","is_active":true,"links":{"self":"https:\/\/azura.xxxx\/api\/station\/2\/streamer\/34"}},{"id":37,"streamer_username":"Nexan","streamer_password":"xxxx","display_name":"Nexan","comments":"","is_active":true,"links":{"self":"https:\/\/azura.xxxx\/api\/station\/2\/streamer\/37"}},{"id":38,"streamer_username":"Mora1","streamer_password":"xxxx","display_name":"Mora","comments":"","is_active":true,"links":{"self":"https:\/\/azura.xxxx\/api\/station\/2\/streamer\/38"}},{"id":39,"streamer_username":"jethro","streamer_password":"xxxxx","display_name":"Jethro (Moris)","comments":"","is_active":true,"links":{"self":"https:\/\/azura.xxxx\/api\/station\/2\/streamer\/39"}}]`

Password and servername are changed ofc.

**Comment by SlvrEagle23** [comment]
@pilovali That's probably a bug. Looking into it shortly.

**Comment by SlvrEagle23** [comment]
@pilovali Yep, it was a bug. Updated the azuracore library to properly not attempt to paginate records when pagination is disabled (which it is by default if there are no pagination query parameters specified).

**Comment by pilovali** [comment]
Thanks for squishing the bug. How do I update the Azuracore library?

**Comment by SlvrEagle23** [comment]
@pilovali It's updated when you update AzuraCast itself.

**Comment by Vaalyn** [comment]
As the bug has been resolved I'll close this issue now. If you still encounter this problem after updating feel free to let us know.
