### ISSUE TITLE
Custom Cues: Cue-In and Cue-Out Point

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#151]
Hello Silver Eagle, I have a problem with "Custom Cues: Cue-In and Cue-Out Point" and if I put any value, the mp3 to problems in reading. For example, looping at the beginning of the title ...

I offered you some coffee To thank you for your work 🖖🏽

**Comment by SlvrEagle23** [comment]
@ckeurk Thank you for your help and support! :)

For the cue-in and cue-out values, keep in mind even the cue-out value is relative to the seconds from the *beginning* of the song, so if you enter the seconds from the end, it'll likely cause unexpected problems. If it continues to be an issue despite that, let me know and I'll look into it.

**Comment by SlvrEagle23** [comment]
@ckeurk I had a chance to play with this some more locally, and I think I found the problem...the cue_in and cue_out fields in the database were capped to DECIMAL(3, 1), which would only allow a maximum of 99.9. If you set a value higher than that, it would just constantly repeat that single second of audio over and over as if it was set to cue in and out at exactly 99.9 seconds.

The latest commit updates the database accordingly and should fix it. Sorry about that!
