### ISSUE TITLE
Error 500 - Playlist-view

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1510]
Installation: Ansible

When clicking on playlists an error 500 occurs:
Error 500
Argument 1 passed to App\Utilities::timeToSplitDisplay() must be of the type integer, null given, called in /var/azuracast/www/src/Controller/Stations/PlaylistsController.php on line 74
Utilities.php : 40

This only happens to 2 of my stations. The others are working normally...

Logs:
found nothing... even the php_errors.log isn't showing anything wrong...

**Comment by SlvrEagle23** [comment]
@MrSteelMiner Should be fixed now.

**Comment by MrSteelMiner** [comment]
You're the best! Thank you!
