### ISSUE TITLE
Remove Icecast Streaming site

### ISSUE THREAD

**Issue by Weigand-Dev** [AzuraCast/AzuraCast#1511]
Hello, how can i remove icecast streaming site. This is the status.xsl. I want to deactivate this.

**Comment by SlvrEagle23** [comment]
@Weigand-Dev We don't offer built-in functionality to hide the components of Icecast or SHOUTcast that are exposed to the public by default, as there is no sensitive information contained within these files and they're often used by third-party software (and indeed AzuraCast itself) to determine how to play your radio station or what's currently playing on it.

You could add custom rules to the nginx service to avoid these files from showing up on our HTTP/HTTPS proxy, but this is advanced functionality that requires a strong understanding of nginx's configuration file format and would be unsupported. You should not directly stop these files from being served by Icecast itself, as it would also interfere with AzuraCast's own internal checks.

**Comment by Weigand-Dev** [comment]
Ok thanks for this information.
