### ISSUE TITLE
live_enabled condition

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1512]
I'm studying the condition of switching to a live DJ stream. This is the bit from the Liquidsoap configuration: 

`radio = switch(id="lahmacun_radio_live_switch", track_sensitive=false, [({!live_enabled}, live), ({true}, radio)])`

I don't understand why `!live_enabled` is the condition to switching to live. Isn't it supposed to mean NOT `live_enabled`? I would expect it the other way around. Can anybody enlighten me?

**Comment by gammaw** [comment]
Guys I guess I have the answer. `!` should stand for dereferencing (`live_enabled` is previously defined as a pointer). I found a hint in a [random commit description](https://github.com/savonet/liquidsoap/blob/master/doc/content/language.txt). I didn't find this operator in the [Liquidsoap documentation](https://www.liquidsoap.info/doc-dev/) or elsewhere.

**Comment by SlvrEagle23** [comment]
@gammaw Yeah...I'm not a huge fan of that operator not meaning "not" either. I never found it in the documentation myself, I was just using some of their sample scripts and noticed it was there.

**Comment by Vaalyn** [comment]
@gammaw Maybe you could submit an issue on the liquidsoap repo and ask them to add this to their documentation. It could help others figuring that out in the future too. =)

I'll close this issue now as the questions is solved now.
