### ISSUE TITLE
RESTRICTED TO API READ ACCESS ONLY - Twitter/webhook

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#1514]
not really azuracast related but is this error, something serious or i just need to wait 24hours?
![Bildschirmfoto von 2019-05-08 15-47-36](https://user-images.githubusercontent.com/7961/57380190-ca0ffa80-71a8-11e9-88fe-65cc9ba69c2b.png)

Thanks

**Comment by arthurkieffer** [comment]
@macbroadcast I've got the same issue for a week now, did you manage solve this ? Can't find a solution anywhere.
