### ISSUE TITLE
Code for title and cover of the song

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#1515]
Hello! How do I display album cover and current song name on my site? Which code should I use?

**Comment by Rafaelrds2017** [comment]
In api show me this code:

http://stream.geracaoradios.com/api/station/1

  "shortcode": "radiogeracao", "description": "", "frontend": "shoutcast2", "backend": " liquidsoap "," listen_url ":" http: \ / \ / stream.google.com:8000\/radio?1557332502","is_public":true,"mounts":[{"is_default":true,"name ": "64kbps AAC", "url": "http: \ / \ / stream.geracaoradios.com:8000\/radio?1557332502","bitrate":320,"format":"aac"}],"remotes": []}

**Comment by Vaalyn** [comment]
I'm not entirely sure what you are asking. Do you mean which field of the JSON response you should use or do you look for a JavaScript or PHP snippet for calling the API?

**Comment by Rafaelrds2017** [comment]
> Não tenho certeza do que você está perguntando. Você quer saber qual campo da resposta JSON deve usar ou procura um fragmento JavaScript ou PHP para chamar a API?

I do not know anything about code.

I need a code to display information on my page on my site

**Comment by Rafaelrds2017** [comment]
Can you help me? I needed to show on the page of my radio, the current musical and cover of the album. Provided by the api Azuracast; Can you assemble a code to display this?

I use Wordpress and pro elementor to set up my website.

**Comment by Vaalyn** [comment]
If you know the IDs of the elements where you want to show that information you can use JavaScript to call the API and update the text / src of these elements. I'm assuming that your website uses jQuery so I'll provide some crude generic snippet for that.

```
setInterval(function() => {
	$.get('http://stream.geracaoradios.com/api/nowplaying/1')
		.done(function(data) {
			$('#song-element-id').text(data.now_playing.song.text);
			$('#image-element-id').attr('src', data.now_playing.song.art);
		});
}, 1000);
```

As this is technically not something we offer support for as this is custom work you may want to pay someone to modify your websites code or take a look at learning basic PHP / JS coding.

**Comment by Vaalyn** [comment]
You can also just use the player embed code to include our ready-to-use embed widget. You can find it in you stations profile.

**Comment by Rafaelrds2017** [comment]
> You can also just use the player embed code to include our ready-to-use embed widget. You can find it in your stations profile.

Yes. But in the provided widget, album cover gets smaller, and the player button also

**Comment by Rafaelrds2017** [comment]
> You can also just use the player embed code to include our ready-to-use embed widget. You can find it in your stations profile.

I tried to apply here on my site, but without success.
Well, I'll check what I can do. I'll hire someone to do this. Thank you for your help!

**Comment by Rafaelrds2017** [comment]
> You can also just use the player embed code to include our ready-to-use embed widget. You can find it in your stations profile.

**Comment by Vaalyn** [comment]
You should be able to customize that by providing some custom css in the System Administration `Custom CSS for Public Pages` but yeah it's generally a good idea to let someone implement custom code if you don't know how to do it yourself. CSS should be easier to get started with though so you may want to give it a try to modify the CSS via that field I mentioned.

**Comment by Rafaelrds2017** [comment]
Aplico este código em Html ou shortcode?
________________________________
De: Vaalyn <notifications@github.com>
Enviado: quarta-feira, 8 de maio de 2019 14:56
Para: AzuraCast/AzuraCast
Cc: Rafael Rodrigues; State change
Assunto: Re: [AzuraCast/AzuraCast] Code for title and cover of the song (#1515)


You should be able to customize that by providing some custom css in the System Administration Custom CSS for Public Pages but yeah it's generally a good idea to let someone implement custom code if you don't know how to do it yourself. CSS should be easier to get started with though so you may want to give it a try to modify the CSS via that field I mentioned.

**Comment by Vaalyn** [comment]
The embed widget is not a WordPress shortcode. You'll need to include this as raw HTML.

**Comment by Rafaelrds2017** [comment]
Thank you!

Att

Rafael

________________________________
De: Vaalyn <notifications@github.com>
Enviado: quarta-feira, 8 de maio de 2019 15:02
Para: AzuraCast/AzuraCast
Cc: Rafael Rodrigues; State change
Assunto: Re: [AzuraCast/AzuraCast] Code for title and cover of the song (#1515)


The embed widget is not a WordPress shortcode. You'll need to include this as raw HTML.
