### ISSUE TITLE
Can't save or submit all form in Google Chrome

### ISSUE THREAD

**Issue by kokoloman001** [AzuraCast/AzuraCast#1517]
SS : 
http://prntscr.com/nme5wb

Host : DigitalOcean
Installed by : Docker

I can't save or submit forms, When use Google Chrome.
- Create Station
- Create User
- System Administration
And all forms

But i use Microsoft edge, And it works

Thank for support.

**Comment by Vaalyn** [comment]
For me it works in Google Chrome, could you check if there are any JavaScript errors in your browsers JavaScript console and also if there are any errors in the AzuraCast Application Log?
