### ISSUE TITLE
error when updated to current release

### ISSUE THREAD

**Issue by athensguy** [AzuraCast/AzuraCast#152]
TASK [supervisord : Kill legacy radio processes (if upgrading from older version)] ***
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["killall", "-9", "icecast2", "sc_serv", "liquidsoap"], "delta": "0:00:00.061087", "end": "2017-06-03 12:08:52.650367", "failed": true, "rc": 1, "start": "2017-06-03 12:08:52.589280", "stderr": "icecast2: no process found\nsc_serv: no process found\nliquidsoap: no process found", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

TASK [supervisord : Trigger manual restart of supervisord (if not already running)] ***
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Stopping supervisor: supervisord.\nStarting supervisor: "}
        to retry, use: --limit @/var/azuracast/www/util/ansible/update.retry

PLAY RECAP *********************************************************************
localhost                  : ok=16   changed=7    unreachable=0    failed=1

AzuraCast interface is not accessible and I have restart supervisor

root@radio:# service supervisor restart
Restarting supervisor: supervisord.

When checking AzuraCast url http://azuracast/index page (http://azuracasturl/), I got this

{"status":"error","error":"Station not found!"}

Admin is still accessible via http://azuracasturl/admin 
only admin page and other are down

**Comment by SlvrEagle23** [comment]
@athensguy I'm not sure exactly what's going on here, but I've removed one potential cause of the problem, and added a way to more easily force a "full update" in the event such a problem happens again.

On your AzuraCast instance, try running:

```
cd /var/azuracast/www
git reset --hard && git pull
chmod a+x update.sh
./update.sh --full
```

**Comment by athensguy** [comment]
git reset --hard && git pull
HEAD is now at 57c3017 Split dev stuff in docker into its own compose file to avoid Travis tripping over it.
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 17 (delta 11), reused 13 (delta 7), pack-reused 0
Unpacking objects: 100% (17/17), done.
From https://github.com/SlvrEagle23/AzuraCast
   57c3017..a57e78b  master     -> origin/master
Updating 57c3017..a57e78b
Fast-forward
 update.sh                                     | 8 +++++++-
 util/ansible/roles/supervisord/tasks/main.yml | 4 ----
 2 files changed, 7 insertions(+), 5 deletions(-)

update ended with below error

TASK [azuracast-update : Restart Radio Stations] *******************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php radio:restart", "delta": "0:00:11.123324", "end": "2017-06-03 15:06:47.768172", "failed": true, "rc": 1, "start": "2017-06-03 15:06:36.644848", "stderr": "\n                                                                               \n  [Doctrine\\DBAL\\Exception\\DriverException]                                    \n  An exception occurred while executing 'SELECT s0_.setting_key AS setting_ke  \n  y_0, s0_.setting_value AS setting_value_1 FROM settings s0_ ORDER BY s0_.se  \n  tting_key ASC':                                                              \n  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away              \n                                                                               \n\n                                                                   \n  [Doctrine\\DBAL\\Driver\\PDOException]                              \n  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away  \n                                                                   \n\n                                                                   \n  [PDOException]                                                   \n  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away  \n                                                                   \n\nradio:restart", "stdout": "Restarting all radio stations...\n---------------------------------------------\nRestarting station #3: RadioVOH", "stdout_lines": ["Restarting all radio stations...", "---------------------------------------------", "Restarting station #3: RadioVOH"], "warnings": []}

RUNNING HANDLER [nginx : restart nginx] ****************************************

RUNNING HANDLER [azuracast-cron : restart cron] ********************************
        to retry, use: --limit @/var/azuracast/www/util/ansible/update.retry

PLAY RECAP *********************************************************************
localhost                  : ok=56   changed=15   unreachable=0    failed=1

**Comment by SlvrEagle23** [comment]
Try `sudo supervisorctl restart core:mysql`...seems like mysql got messed up somewhere in the upgrade.

I may need to take a look at your specific server if you're willing to send over the credentials. I can be reached via e-mail at loobalightdark@gmail.com.

**Comment by athensguy** [comment]
well done, it has been fixed now. While with new update missed up dj features. dj user can't stream. I created new Radio and still the same
