### ISSUE TITLE
Request Song Duration blank using API

### ISSUE THREAD

**Issue by adwinter** [AzuraCast/AzuraCast#1523]
**Using Docker installation method**
No (Bare-Metal)

**Host Operating System**
Ubuntu 16.04 LTS Server

**Describe the bug**
When a request plays (requested via the API), the "song duration" field returns 0, instead of the actual remaining time.

**To Reproduce**
Request A Song, wait for it to play, do an API request on now_playing and the song_duration returns 0, instead of the actual number.

**Expected behavior**
Song duration should not be blank for requested songs.. The same song playing using the regular rotations will show up with the song duration correctly.

**Relevant Logs**
Using the "Now Playing" API call, it returns this:

`
array(8) {
  ["elapsed"]=>
  int(20)
  ["remaining"]=>
  int(0)
  ["sh_id"]=>
  int(117378)
  ["played_at"]=>
  int(1557529441)
  ["duration"]=>
  int(0)
  ["playlist"]=>
  string(0) ""
  ["is_request"]=>
  bool(false)
  ["song"]=>
  array(8) {
    ["id"]=>
    string(32) "a8b753c6adad37258302afbd6bc4a956"
    ["text"]=>
    string(34) "Massive Wagons - Under No Illusion"
    ["artist"]=>
    string(14) "Massive Wagons"
    ["title"]=>
    string(17) "Under No Illusion"
    ["album"]=>
    string(0) ""
    ["lyrics"]=>
    string(0) ""
    ["art"]=>
    string(53) "http://play.fusion109.com/static/img/generic_song.jpg"
    ["custom_fields"]=>
    array(2) {
      ["last_moved"]=>
      NULL
      ["screamo"]=>
      NULL
    }
  }
}
`
**notice "remaining" is int(0);**

**Comment by SlvrEagle23** [comment]
@adwinter Thank you for the report! This was indeed an issue with AzuraCast after our switch back to having Liquidsoap handle the majority of the AutoDJ processing work; song requests weren't properly being "annotated" to Liquidsoap with the necessary metadata for AzuraCast to know that the song was a request and that it corresponded with a media library item.

This should be fixed as of the latest update.
