### ISSUE TITLE
Can't use Merge playlist to play as a single track

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#1525]
Ubuntu 16.04 Traditional Install

Error:
At line 37, char 85-91: cannot apply that parameter because the function
(at line 37, char 50) has no argument labeled "reload_mode"!
At line 37, char 85-91: cannot apply that parameter because the function
(at line 37, char 50) has no argument labeled "reload_mode"!
At line 37, char 85-91: cannot apply that parameter because the function
(at line 37, char 50) has no argument labeled "reload_mode"!

Config:
![grafik](https://user-images.githubusercontent.com/31483348/57571271-0c854180-740c-11e9-808c-ba422279771a.png)
![grafik](https://user-images.githubusercontent.com/31483348/57571272-14dd7c80-740c-11e9-9006-3c13cdd69f3d.png)

**Comment by SlvrEagle23** [comment]
@preterive This should be fixed as of the latest update.

**Comment by preterive** [comment]
Thanks! I try it out now.

**Comment by preterive** [comment]
okay, this seems to be working.
But is there no way to Play these Playlist completly at one Time and not
First a Track from this Playlist, than from the other Playlist and then from this Playlist etc. ?
There are 2 jingles who have to be played one after the other

**Comment by SlvrEagle23** [comment]
@preterive That's specifically what "merge" does, it plays the combined playlist as though it's a single track.

**Comment by preterive** [comment]
Yes, thanks i also thought that but it don't worked because i had to restart the Station...
