### ISSUE TITLE
Send Metadata for every Track

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#1526]
Hello,
if the playlist from the other issue( https://github.com/AzuraCast/AzuraCast/issues/1525 ) is playing, Azuracast only send the Metadata of the first Track and not the Data of every 3 Tracks
The first Track is 15 Seconds long. After this, there is a 1 Second long Track who Starts the Ads at the Relay Server.
After This comes a 2 Second Track(Jingle).

**Comment by SlvrEagle23** [comment]
@preterive This is likely an intended consequence of how `playlist.merge` works within Liquidsoap, and there is probably nothing we can do about this from the AzuraCast end.

**Comment by preterive** [comment]
okay, but what does the option Only play one track at scheduled time. ?
Is there no way to play Jingle, Ad, Jingle in this Sequence every 40 Minutes?

**Comment by preterive** [comment]
And why does i hear the complete playlist at one time if i activate interrupt other songs to play at scheduled time?

**Comment by preterive** [comment]
But this make it impossible to create a Pre Recorded Show with Music and Recordings!
Is there no way?
@SlvrEagle23

**Comment by preterive** [comment]
Intresting... now i see that it works an the Metadata Send too... I simple removed the Crossfade from the first song.
