### ISSUE TITLE
Azuracast Jingle after every restart

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#1527]
Hello,
i hear the Azuracast Jingle after every restart of the Station.
Ubuntu 16.04 Traditional Installation
The Log:

2019/05/11 19:27:08 [decoder:3] Method "MP4" accepted "/var/azuracast/stations/allesradiozwei/media/26_superhero_-28extended_mix-29_-28extended_mix-29_-28feat._basst-29.m4a".
2019/05/11 19:27:08 [allesradiozwei_live_switch:3] Switch to map_metadata_6511.
2019/05/11 19:27:08 [fallback_6505:3] Switch to rotate_6502.
2019/05/11 19:27:08 [rotate_6502:3] Switch to switch_6500.
2019/05/11 19:27:08 [switch_6500:3] Switch to allesradiozwei_autodj_fallback.
2019/05/11 19:27:08 [allesradiozwei_autodj_fallback:3] Switch to sequence_6493.
2019/05/11 19:27:08 [dummy:3] Source failed (no more tracks) stopping output...
2019/05/11 19:27:08 [single_6492:3] Prepared "/var/azuracast/www/resources/error.mp3" (RID 1).
2019/05/11 19:27:09 [smart_cross_6541:3] Analysis: -infdB / -21.435607dB (5.00s / 5.00s)
2019/05/11 19:27:09 [smart_crossfade:3] new >= old + margin, old <= medium and new <= high.
2019/05/11 19:27:09 [smart_crossfade:3] Do not fade if it's already very low.
2019/05/11 19:27:09 [smart_crossfade:3] Transition: crossed, no fade.
2019/05/11 19:27:09 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/allesradiozwei/media/25781-1554892204.mp3".

**Comment by SlvrEagle23** [comment]
@preterive This is fairly common as a result of how Liquidsoap's fallback system works; if no audio track is "ready" at the time it's looking for something to initially play (i.e. if the AzuraCast's AutoDJ response is delayed or there are no "general rotation" playlists), it falls back to the AzuraCast error message.

Because this should only be happening at the very beginning of the stream's lifetime, so only when the station has just been restarted, this isn't a particularly high priority for us to fix, especially since I'm not sure what we could do to resolve the situation anyway.

**Comment by MrSteelMiner** [comment]
I don't have this issue. When I restart my stations it plays my own Jingle from my Jingles-Playlist which is configured to play every 30 minutes.

**Comment by mikedorst** [comment]
Got the same issue as #1580 if I can help let me know.

**Comment by SlvrEagle23** [comment]
I have an upstream issue with Liquidsoap (savonet/liquidsoap#803) about the overall tendency of Liquidsoap to trigger the "fallback" to other sources fairly frequently, which is what was causing the AzuraCast error "jingle" to play in a lot of cases.

In the meantime, I've removed the error file entirely from Liquidsoap's rotation, which means skipping songs, restarting the station and cue-out points won't set it off.

**Comment by CouinCouin** [comment]
Hi, 

I get similar thing . 
If I have a player that try to listen while server is booting, when Azura is ready, I get the jingle before the first played track. 

Perhaps a workaround is to replace the jingle file by a "blank" file ? 

Thanks :)
