### ISSUE TITLE
Custom Branding and Dj accounts cannot be adjusted. Cache clear has been executed, but that doesn't help

### ISSUE THREAD

**Issue by rolradio** [AzuraCast/AzuraCast#1528]
**Using Docker installation method**
 Yes

**Host Operating System**
 Ubuntu Linux 18.04.1

**Describe the bug**

Custom Branding and Dj accounts cannot be adjusted. Cache clear has been executed, but that doesn't help

**To Reproduce**

762/5000
I can no longer adjust the DJ account settings.
Apparently I cannot save the data that I am changing.
I adjust it and then I press save.
After changing the page, or refreshing, the old settings remain.

Cache clear is executed with: ./docker.sh cli cache: clear
Everything is going well, the cache has been cleared, as a message at the end.

But the problem with the old data remains.
After cache clear, the old data remains, changing and saving does not help.

The same problem with custom branding ...
I managed to adjust the Custom Branding in azuracast.
But the changes in Custom CSS for Public Pages, I can no longer adjust or delete and save.

What can I do to get this right?
**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser:  Chrome - Firefox 
 - Version: 

**Additional context**

**Comment by rolradio** [comment]
I see: https://github.com/AzuraCast/AzuraCast/issues/1517  same problem..

Save in edge works for me.

Chrome and firefox not.

**Comment by SlvrEagle23** [comment]
@rolradio So I have the same question as mentioned in 1517...does your Javascript console show any errors when submitting the form? We use both Chrome and Firefox every day when developing AzuraCast and we've never run into any issues of this sort, or they would be very promptly fixed!

**Comment by rolradio** [comment]
@SlvrEagle23     Strangely enough, I no longer have this problem.
Probably it would have been a bad code somewhere in the custom branding I made.

After deleting the old data in costum, everything works again.
Thanks.

**Comment by SlvrEagle23** [comment]
@rolradio We've made some improvements that should hopefully help with this issue happening in the future, by explicitly showing what errors prevented the form from saving in a large red alert box at the top of the screen. Glad your current issue is fixed.
