### ISSUE TITLE
Big audio file uploads partly (no error is shown)

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1529]
**Using Docker installation method** Yes
 

**Host Operating System** Linux Ubuntu 18.04

**Describe the bug**

1. I upload a big audio file (500MB/4 hours mp3) via admin interface in browser. 
2. Upload finishes. 
3. The Music Files view shows a much smaller file (around 100-200MB, not deterministic, not even for the same file) and a much smaller length (looks to be in synch with the size). 

**Relevant Logs** No trace of error (in Azuracast log). 

**Device(s):**
 - Device:  Desktop
 - OS:  iOS
 - Browser:  Chrome

**Comment by Vaalyn** [comment]
How long did it take until the upload was finished? Maybe you ran into a timeout. Can you see anything in the logs when you view them via `docker logs azuracast_web_1`?

**Comment by gammaw** [comment]
@Vaalyn: thanks. It turns out that our server simply ran out of space! Which made me wonder: 
- Why does Azuracast show following space stats (see screenshot)? 
- How come Azuracast "cuts" the file (depending on the available space), stores a playable audio, actually uses it as instructed (through playlists etc.) and shows no error? My expected behaviour would be that the upload is unsuccessful and and a not-enough-space error is thrown.

![image](https://user-images.githubusercontent.com/28865986/57587414-d081d780-7504-11e9-98ce-ff67217efa14.png)

**Comment by Vaalyn** [comment]
I'm not sure about the space stats.

Most audio file formats, at least as much as I know, are build to sequentially give you the data that is needed to play them so if the file has 20% correct data of the whole file in the beginning and all the other metadata is intact it will play without problems until it reaches the point of corruption. I agree that there is something strange going on if the reported space usage is incorrect and there is no error shown when that space is too small for a file.
