### ISSUE TITLE
error when start/restart LiquidSoap (AutoDJ Service)

### ISSUE THREAD

**Issue by athensguy** [AzuraCast/AzuraCast#153]
Script fails with below error when attempt to start/restart LiquidSoap (AutoDJ Service)

App \ Exception
ABNORMAL_TERMINATION: station_1:station_1_backend

**Comment by SlvrEagle23** [comment]
@athensguy Does it show you a full error page with additional details?

**Comment by athensguy** [comment]
SlvrEagle23 , this is a clean installation by the way.

I managed to understand cause. There was no default playlist. Once created playlist and added songs it worked.

Just create a normal IceCast radio with autodj and try to start service you will have full error.

**Comment by SlvrEagle23** [comment]
@athensguy I've fixed this issue now...the first time you restart the station, if no default playlist exists, it will create one for you and carry on normally instead of causing this error. This should be a much friendlier process.
