### ISSUE TITLE
SSL renewal

### ISSUE THREAD

**Issue by croner** [AzuraCast/AzuraCast#1530]
So i have a site that's up and running - and had originally implemented ssl as well. I cannot update the docker instance because I get error 500 and I have few thousand songs in the library - which I read could be the problem. But my main problem was renewing certs. So i tried everything, and original cert expired - could not renew it. So I ran  
`docker-compose run --rm letsencrypt certonly --webroot -w /var/www/letsencrypt`

This was successful in obtaining a cert anew, and it reports that it was successful, but I cannot get the public or web interfaces to read this. I assume nginx is not properly updating its links - although I have **not** **modified** anything in the docker-compose.yml page from original installation.

Any pointers on this would be greatly appreciated - since I am relatively new to dockerization
My host is Ubuntu Server 1804 if that matters at all. 

When I run the renew command directly - this is the output. 
`sudo ./docker.sh letsencrypt-renew
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"letsencrypt_renew\": executable file not found in $PATH": unknown`

**Comment by SlvrEagle23** [comment]
@croner You should definitely be updating your Docker instance, since that suggests you have a fairly old AzuraCast installation, and there have been hundreds, if not thousands, of bug fixes since the introduction of our unified web containers.

The approximate command you might want to try given your setup is:

```
docker-compose run --rm letsencrypt renew --webroot -w /var/www/letsencrypt
```

**Comment by croner** [comment]
That WORKED :) Thank you @SlvrEagle23 

now I have to figure out how to update.... my backup file is 20gig - If i have to destroy the library to get it smaller to work, it might be worth the trouble - as long as I don't get the error 500
