### ISSUE TITLE
Creating a Radio Port Problem

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#1531]
Ins. method: docker

Hello!

I've just deleted some radio stations I've created before for trial. I have only 1 radio left and it's working. That working radio is on port 8000. 

Now when I create a radio, AzuraCast automatically assigns 8010 port to it (another station were using it before and were working) but now new radio does not work because of port problem. When I create a radio and manually assign port that did not used before, the station is works. How can I clear the old port data or how can I use 8010, 8020 again?

Also If I can even do this, as you guys now I'm working on this reseller project. Is it possible to create more than 50 radios, if so how it may be?

Greetings!

**Comment by SlvrEagle23** [comment]
@radiolize What is the port problem? Deleting a station should shut down the services that are related to it, which should free up the available ports.

As for the total number of stations, there's nothing stopping you from hosting more than 50 stations on one single AzuraCast instance; you'll just need to manually add the new ports to a custom `docker-compose.override.yml` that expands the ports forwarded to include a greater range. It's not recommended to host anywhere near 50 stations on a single server unless this server is extremely overpowered, however, as audio transcoding per-station represents a significant and steady CPU load, and if the overall CPU of the server is overloaded, it negatively affects the quality of _all_ of the streams on that server.

**Comment by radiolize** [comment]
Deleting a station should shut down the services as I thought but I'm not sure if it does. My system is on the final update. Here are the logs of a station I just create and uses 8010 port:

Icecast Error Logs:

`[2019-05-13  12:15:45] WARN xml/parsing warning: 
[2019-05-13  12:15:45] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2019-05-13  12:15:45] WARN xml/parsing warning: 
[2019-05-13  12:15:45] WARN xml/parsing unknown element "stream-genre" parsing "mount" at line 29
[2019-05-13  12:15:46] WARN xml/parsing warning: 
[2019-05-13  12:15:46] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2019-05-13  12:15:46] WARN xml/parsing warning: 
[2019-05-13  12:15:46] WARN xml/parsing unknown element "stream-genre" parsing "mount" at line 29
[2019-05-13  12:15:49] WARN xml/parsing warning: 
[2019-05-13  12:15:49] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2019-05-13  12:15:49] WARN xml/parsing warning: 
[2019-05-13  12:15:49] WARN xml/parsing unknown element "stream-genre" parsing "mount" at line 29
[2019-05-13  12:15:52] WARN xml/parsing warning: 
[2019-05-13  12:15:52] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2019-05-13  12:15:52] WARN xml/parsing warning: 
[2019-05-13  12:15:52] WARN xml/parsing unknown element "stream-genre" parsing "mount" at line 29
[2019-05-13  12:25:57] WARN xml/parsing warning: 
[2019-05-13  12:25:57] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2019-05-13  12:25:57] WARN xml/parsing warning: 
[2019-05-13  12:25:57] WARN xml/parsing unknown element "stream-genre" parsing "mount" at line 29
[2019-05-13  12:25:59] WARN xml/parsing warning: 
[2019-05-13  12:25:59] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2019-05-13  12:25:59] WARN xml/parsing warning: 
[2019-05-13  12:25:59] WARN xml/parsing unknown element "stream-genre" parsing "mount" at line 29
[2019-05-13  12:26:01] WARN xml/parsing warning: 
[2019-05-13  12:26:01] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2019-05-13  12:26:01] WARN xml/parsing warning: 
[2019-05-13  12:26:01] WARN xml/parsing unknown element "stream-genre" parsing "mount" at line 29
[2019-05-13  12:26:04] WARN xml/parsing warning: 
[2019-05-13  12:26:04] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2019-05-13  12:26:04] WARN xml/parsing warning: 
[2019-05-13  12:26:04] WARN xml/parsing unknown element "stream-genre" parsing "mount" at line 29
[2019-05-13  12:26:06] WARN xml/parsing warning: 
[2019-05-13  12:26:06] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2019-05-13  12:26:06] WARN xml/parsing warning: 
[2019-05-13  12:26:06] WARN xml/parsing unknown element "stream-genre" parsing "mount" at line 29
[2019-05-13  12:26:07] WARN xml/parsing warning: 
[2019-05-13  12:26:07] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2019-05-13  12:26:07] WARN xml/parsing warning: 
[2019-05-13  12:26:07] WARN xml/parsing unknown element "stream-genre" parsing "mount" at line 29
[2019-05-13  12:26:10] WARN xml/parsing warning: 
[2019-05-13  12:26:10] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2019-05-13  12:26:10] WARN xml/parsing warning: 
[2019-05-13  12:26:10] WARN xml/parsing unknown element "stream-genre" parsing "mount" at line 29
[2019-05-13  12:26:13] WARN xml/parsing warning: 
[2019-05-13  12:26:13] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2019-05-13  12:26:13] WARN xml/parsing warning: 
[2019-05-13  12:26:13] WARN xml/parsing unknown element "stream-genre" parsing "mount" at line 29`

Liquidsoap Logs:

`2019/05/13 12:15:45 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/05/13 12:15:45 [main:3] Liquidsoap 1.3.7
2019/05/13 12:15:45 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.7 camomile=1.0.1 faad=0.4.0
2019/05/13 12:15:45 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/05/13 12:15:45 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/05/13 12:15:45 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/05/13 12:15:45 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/05/13 12:15:45 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/05/13 12:15:46 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/05/13 12:15:46 [main:3] Liquidsoap 1.3.7
2019/05/13 12:15:46 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.7 camomile=1.0.1 faad=0.4.0
2019/05/13 12:15:46 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/05/13 12:15:46 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/05/13 12:15:46 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/05/13 12:15:46 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/05/13 12:15:46 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/05/13 12:15:49 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/05/13 12:15:52 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/05/13 12:25:57 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/05/13 12:25:59 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/05/13 12:25:59 [main:3] Liquidsoap 1.3.7
2019/05/13 12:25:59 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.7 camomile=1.0.1 faad=0.4.0
2019/05/13 12:25:59 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/05/13 12:25:59 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/05/13 12:25:59 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/05/13 12:25:59 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/05/13 12:25:59 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/05/13 12:26:01 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/05/13 12:26:05 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/05/13 12:26:12 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/05/13 12:26:14 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/05/13 12:26:16 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/05/13 12:26:19 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/05/13 12:26:19 [main:3] Liquidsoap 1.3.7
2019/05/13 12:26:19 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.7 camomile=1.0.1 faad=0.4.0
2019/05/13 12:26:19 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/05/13 12:26:19 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/05/13 12:26:19 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/05/13 12:26:19 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/05/13 12:26:19 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".`

**Comment by Vaalyn** [comment]
> The new radio station should get id of "2" but it gets "16". Looks like the old stations still counts as I could not use the old id's too.

This is not an error. The station id is automatically generated by the database as the `id` field is an `auto-increment` `primary key` field. In theory you can re-assign these ids but it can cause unnecessary trouble. Just using the next free number is the default when using `auto-increment` primary keys and will not be a problem as a normal `integer` field can go up to the number `2147483647` when using a signed integer.

Regarding the port not being usable. I remember that someone else also encountered that in the past but I wasn't able to reproduce that behaviour or get any information out of their system that would indicate why this isn't working. Can you enter the `azuracast_stations` container and execute `lsof -i -P -n | grep LISTEN` to see which ports are in use?

[This](https://github.com/AzuraCast/AzuraCast/issues/1238) is the issue I remembered this problem from. As you can see in the comments there I've extensively tested everything I could think of but was unable to find any problems with the ports and the user also reported that the problem just vanished without us doing anything after he updated his installation. Have you updated you installation to the newest version or are you using an older version?

**Comment by radiolize** [comment]
I've rebooted the server and ubuntu starting page appeared. Then I updated the AzuraCast and docker. After update, the system still inaccessible and there is error appeared below:

> [OK] AzuraCast is now updated to the latest version!                                                                   
                                                                                                                        

2019/05/13 14:51:00 Command finished successfully.
azuracast_mariadb_1 is up-to-date
azuracast_stations is up-to-date
azuracast_influxdb_1 is up-to-date
azuracast_redis_1 is up-to-date
Creating azuracast_web_1 ... error

ERROR: for azuracast_web_1  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web_1 (fac7289077d2041cfbebc46a5793611e7d23608341ad5485468d340bb2c70d97): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web_1 (fac7289077d2041cfbebc46a5793611e7d23608341ad5485468d340bb2c70d97): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.
Update complete!

**Comment by Vaalyn** [comment]
You most likely have a `httpd` or `apache2` service running on your host machine. Stop that service and remove it from autostart.

**Comment by radiolize** [comment]
Thanks I've deleted apache2 and made update again then it's live again.

Also good news! I've solved the problem. Looks like Ubuntu's Kubernetes 1.14 distributions bypassing Docker and uses containerd directly. 

If anyone ever lives same problem, solved the problem with:

>      snap install microk8s --classic

**Comment by istahilagi** [comment]
> Deleting a station should shut down the services that are related to it, which should free up the available ports.

how to turn off ports on services that have been deleted?

**Comment by SlvrEagle23** [comment]
@istahilagi See issue #1674, this is a known problem we're working on.
