### ISSUE TITLE
Liquidsoap -Azuracast update

### ISSUE THREAD

**Issue by skoja** [AzuraCast/AzuraCast#1532]
I think you need to do update Liquidsoap versions.
The current installed version of Azuracast is 1.3.7.
Liquidsoap already exists in 1.4.0
It probably solves many problems with crosfade, jingle and playlists.

**Comment by SlvrEagle23** [comment]
@skoja Liquidsoap 1.4.0 is currently in alpha pre-release status and is being tested. We're keeping an eye on it, and once a stable release is tagged, we'll update to it immediately.
