### ISSUE TITLE
Hourly playlist only plays sometimes

### ISSUE THREAD

**Issue by Rootinator** [AzuraCast/AzuraCast#1537]
Hello,

 I have 2 playlists to play every hour of the minute in 15 minutes and 45 minutes.

 Unfortunately, playing the playlists for the next hour on time is a coincidence.

 Even setting the tick "Songs Interrupt" does not help.

**Comment by SlvrEagle23** [comment]
@Rootinator Even setting the playlist to "interrupt other songs" and then restarting the station? Changing that mode doesn't take effect immediately, it requires a restart to apply.

**Comment by Rootinator** [comment]
I restarted the stream and even the whole server on which AzuraCast was installed.

**Comment by Rootinator** [comment]
Even after an update that should fix the error of hourly playlists, I still have the flaw that the playlist is only sometimes played.  After 00:00 clock she will not play anymore.

**Comment by Vaalyn** [comment]
Could you post your Liquidsoap configuration here so that we can look if there is an error in it?
You can find it at `Utilities` -> `Log Viewer`.

Don't forget to anonymize it / remove any passwords or tokens from it.

**Comment by Rootinator** [comment]
`Liquidsoap Konfiguration

×

Automatisch nach unten scrollen

# WARNING! This file is automatically generated by AzuraCast. # Do not update it directly! set("init.daemon", false) set("init.daemon.pidfile.path","/var/azuracast/stations/radio/config/liquidsoap.pid") set("log.stdout", true) set("log.file", false) set("server.telnet",true) set("server.telnet.bind_addr","0.0.0.0") set("server.telnet.port", 8004) set("harbor.bind_addrs",["0.0.0.0"]) set("tag.encodings",["UTF-8","ISO-8859-1"]) set("encoder.encoder.export",["artist","title","album","song"]) setenv("TZ", "UTC") # AutoDJ Next Song Script def azuracast_next_song() = uri = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/nextsong --form api_auth="^quote("******")^""), default="") log("AzuraCast Raw Response: #{uri}") if uri == "" or string.match(pattern="Error", uri) then log("AzuraCast Error: Delaying subsequent requests...") system("sleep 5") request.create("") else request.create(uri) end end playlist_radio__main = audio_to_stereo(playlist(id="playlist_radio__main",mode="random",reload_mode="watch","/var/azuracast/stations/radio/playlists/playlist_radio__main.m3u")) playlist_radio__main = cue_cut(id="radio_playlist_radio__main_cue", playlist_radio__main) playlist_werbung15 = audio_to_stereo(playlist.once(id="playlist_werbung15",reload_mode="watch","/var/azuracast/stations/radio/playlists/playlist_werbung15.m3u")) playlist_werbung15 = cue_cut(id="radio_playlist_werbung15_cue", playlist_werbung15) playlist_werbung45 = audio_to_stereo(playlist.once(id="playlist_werbung45",reload_mode="watch","/var/azuracast/stations/radio/playlists/playlist_werbung45.m3u")) playlist_werbung45 = cue_cut(id="radio_playlist_werbung45_cue", playlist_werbung45) # Standard Playlists radio = random(weights=[3], [playlist_radio__main]) dynamic = audio_to_stereo(request.dynamic(id="radio_next_song", timeout=20., azuracast_next_song)) dynamic = cue_cut(id="radio_cue_cut", dynamic) error_song = sequence([blank(duration=5.), single("/usr/local/share/icecast/web/error.mp3")]) requests = audio_to_stereo(request.queue(id="radio_requests")) radio = fallback(id="radio_autodj_fallback", track_sensitive = true, [requests, dynamic, radio, error_song]) # Interrupting Schedule Switches radio = switch(track_sensitive=false, [ ({ 15m }, playlist_werbung15), ({ 45m }, playlist_werbung45), ({true}, radio) ]) # Handle Jingle Mode def handle_jingle_mode(m) = if (m["jingle_mode"] == "true") then log("Jingle mode; stripping metadata...") [] else m end end radio = map_metadata(handle_jingle_mode,update=false,strip=true,insert_missing=false,radio) # Allow for Telnet-driven insertion of custom metadata. radio = server.insert_metadata(id="custom_metadata", radio) # Apply amplification metadata (if supplied) radio = amplify(1., radio) # Normalization and Compression radio = normalize(target = 0., window = 0.03, gain_min = -16., gain_max = 0., radio) radio = compress.exponential(radio, mu = 1.0) radio = crossfade(start_next=4.50,fade_out=3.,fade_in=3.,radio) # Send metadata changes back to AzuraCast def metadata_updated(m) = if (m["song_id"] != "") then ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/feedback --form song="^quote(m["song_id"])^" --form media="^quote(m["media_id"])^" --form playlist="^quote(m["playlist_id"])^" --form api_auth="^quote("******")^""), default="") log("AzuraCast Feedback Response: #{ret}") end end radio = on_metadata(metadata_updated,radio) # Remote Relays output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), id="radio_relay_1", host = "radio.stream.blablabla.tld", port = 8080, user = "user123", password = "qwertz", mount = "/radio", name = "radio", description = "", genre = "", public = false, encoding = "UTF-8", radio)`

**Comment by Vaalyn** [comment]
Please copy only the content of the file and not the whole modal window. Also please make sure that the formatting of that text is not removed. Currently it's too hard to read.

**Comment by Rootinator** [comment]
It is better this way?  :)

```

set("init.daemon", false)
set("init.daemon.pidfile.path","/var/azuracast/stations/radio/config/liquidsoap.pid")
set("log.stdout", true)
set("log.file", false)
set("server.telnet",true)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port", 8004)
set("harbor.bind_addrs",["0.0.0.0"])

set("tag.encodings",["UTF-8","ISO-8859-1"])
set("encoder.encoder.export",["artist","title","album","song"])

setenv("TZ", "UTC")

# AutoDJ Next Song Script
def azuracast_next_song() =
  uri = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/nextsong --form api_auth="^quote("******")^""), default="")
  log("AzuraCast Raw Response: #{uri}")
  
  if uri == "" or string.match(pattern="Error", uri) then
    log("AzuraCast Error: Delaying subsequent requests...")
    system("sleep 5")
    request.create("")
  else
    request.create(uri)
  end
end

playlist_radio__main = audio_to_stereo(playlist(id="playlist_radio__main",mode="random",reload_mode="watch","/var/azuracast/stations/radio/playlists/playlist_radio__main.m3u"))
playlist_radio__main = cue_cut(id="radio_playlist_radio__main_cue", playlist_radio__main)

playlist_werbung15 = audio_to_stereo(playlist.once(id="playlist_werbung15",reload_mode="watch","/var/azuracast/stations/radio/playlists/playlist_werbung15.m3u"))
playlist_werbung15 = cue_cut(id="radio_playlist_werbung15_cue", playlist_werbung15)

playlist_werbung45 = audio_to_stereo(playlist.once(id="playlist_werbung45",reload_mode="watch","/var/azuracast/stations/radio/playlists/playlist_werbung45.m3u"))
playlist_werbung45 = cue_cut(id="radio_playlist_werbung45_cue", playlist_werbung45)

# Standard Playlists
radio = random(weights=[3], [playlist_radio__main])

dynamic = audio_to_stereo(request.dynamic(id="radio_next_song", timeout=20., azuracast_next_song))
dynamic = cue_cut(id="radio_cue_cut", dynamic)

error_song = sequence([blank(duration=5.), single("/usr/local/share/icecast/web/error.mp3")])
requests = audio_to_stereo(request.queue(id="radio_requests"))
radio = fallback(id="radio_autodj_fallback", track_sensitive = true, [requests, dynamic, radio, error_song])

# Interrupting Schedule Switches
radio = switch(track_sensitive=false, [ ({ 15m }, playlist_werbung15), ({ 45m }, playlist_werbung45), ({true}, radio) ])

# Handle Jingle Mode
def handle_jingle_mode(m) =
  if (m["jingle_mode"] == "true") then
    log("Jingle mode; stripping metadata...")
    []
  else
    m
  end
end
radio = map_metadata(handle_jingle_mode,update=false,strip=true,insert_missing=false,radio)

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

# Apply amplification metadata (if supplied)
radio = amplify(1., radio)

# Normalization and Compression
radio = normalize(target = 0., window = 0.03, gain_min = -16., gain_max = 0., radio)
radio = compress.exponential(radio, mu = 1.0)

radio = crossfade(start_next=4.50,fade_out=3.,fade_in=3.,radio)

# Send metadata changes back to AzuraCast
def metadata_updated(m) =
  if (m["song_id"] != "") then
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/feedback --form song="^quote(m["song_id"])^" --form media="^quote(m["media_id"])^" --form playlist="^quote(m["playlist_id"])^" --form api_auth="^quote("*******")^""), default="")
    log("AzuraCast Feedback Response: #{ret}")
  end
end

radio = on_metadata(metadata_updated,radio)

# Remote Relays
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), id="radio_relay_1", host = "radio.stream.bla", port = 8080, user = "user123", password = "qwertz", mount = "/radio", name = "radio", description = "", genre = "", public = false, encoding = "UTF-8", radio)
```

**Comment by Vaalyn** [comment]
@Rootinator yes, that's much better. Thank you. =)

**Comment by SlvrEagle23** [comment]
@Rootinator This seems to be a recurring report we're getting from people...if they have an item set to play at a given time (which is basically one minute wide), and another song is playing during that entire minute, rather than queue up after the current song, it simply skips it.

I'm not sure what the Liquidsoap-y fix is for this, but once we figure it out, we'll apply it immediately to both our "Once per hour" and "Once per day" playlist types.

I will check with the LS folks.

**Comment by Rootinator** [comment]
Is it possible to work with a fallback?

As an example:
`ads_music = fallback([adsmin45,adsmin15,music])`

As I found out, the playlists "adsmin45" and "adsmin15" took precedence over "music".

**Comment by SlvrEagle23** [comment]
@Rootinator I'm merging this issue with several other reports we've received along the same lines. Please follow the super-issue #1564 for updates.
