### ISSUE TITLE
Question: About 500+ Streaming clients

### ISSUE THREAD

**Issue by ma-vie** [AzuraCast/AzuraCast#1538]
Hello  :),

Is there anyone who has about **500+** streaming clients?

If yes:

- Is there any trouble? 

- Does AzuraCast work stable?

- Which kind of Hardware do you use (CPU|RAM)?

- I'm using DigitalOcean, any suggestion which droplet would be the best for 500+ clients?

Thank you in advance

**Comment by SlvrEagle23** [comment]
@ma-vie We use Icecast (or, if you install it, SHOUTcast) as the broadcasting service, so the question of how many listeners it can handle is more a matter of how many listeners Icecast or SHOUTcast can handle, and how much traffic the bandwidth allowances of your server allow for. If Icecast/SHOUTcast have served your station before, it's very likely that AzuraCast will work just as well.

**Comment by Vaalyn** [comment]
> ... and how much traffic the bandwidth allowances of your server allow for

You should calculate how many clients your available network bandwidth can theoretically handle  concurrently and how much that would consume from any limit your hoster might impose upon you. If for example you get a beefy server with 16 cores, 64GB RAM, fast SSD but only 50mbps network you'll be limited to the maximum of that connection and the rest of your resources will idle. Also for IceCast I can say that clients itself will not increase CPU or RAM usage that much. In most cases you are more limited by your network not being able to handle the traffic.
