### ISSUE TITLE
shuflle playlist act like sequential playlist

### ISSUE THREAD

**Issue by radio5050** [AzuraCast/AzuraCast#1540]
Hello,
I have noticed that if i choose the shuffle mode for a playlist it act like a sequential, so i passed in random but i would prefer shuffle.
i don't have tested sequential to see if the fonctions are not just simply inverted.
I never had this problem before, it's like this since 2/3 weeks

i precise that it's in french, so maybe it's just a translation issue.

Also, is it normal that we have to restart the station to apply this kind of change on a playlist?
same thing, i thought it was possible to make this change without restarting the station before

![Capture](https://user-images.githubusercontent.com/50627840/57705429-2f119780-7664-11e9-909e-b50a076d892f.JPG)
thanks for your help and for your  work

**Comment by MyTheValentinus** [comment]
Hello @SlvrEagle23, i'm the tech of this radio, if you need any more technical details i'm listening.
My friend open this request because is the main user of this Azuracast instance, is not a technician, and I did not know how to describe this problem.

Docker install based on master branch
Last update 2 days ago

Thanks

**Comment by btoplak** [comment]
I can confirm that issue on my AC installation. The playlists that were shuffling just fine 2-3 weeks ago, after the update are playing in a sequential alphabetical order. I didn't had the time to look at the Liquidsoap confs, my guess is that a new conf is generated with "sequential" as default, disregarding the settings.

The temporary solution is to go into a playlist settings, change the order to a different setting, save, go back to playlist settings and choose "shuffle" again. Restart the services and it will be back in the shuffle mode.

**Comment by MyTheValentinus** [comment]
@btoplak We already try this hot / temp fix but after some days, the playlist order come back to sequential

**Comment by SlvrEagle23** [comment]
@btoplak @radio5050 @MyTheValentinus I'm looking into this issue, and I just wanted to confirm that you all are using the standard playlist without any of the "advanced" options (i.e. loop playlist once, etc), right?

On a standard playlist, I'm seeing that the shuffle mode is properly being set in the Liquidsoap config:

```
playlist_default = audio_to_stereo(playlist(id="playlist_default",reload_mode="watch",mode="randomize","/var/azuracast/stations/azuratest_radio/playlists/playlist_default.m3u"))
```

the `mode="randomize"` is what we're looking for there.

**Comment by btoplak** [comment]
@SlvrEagle23 : no, nothing special configured in the playlist, just a default playlist with order set to "shuffled"
If I change anything on the settings form and save & reload Liquidsoap, the playback order is fixed

**Comment by radio5050** [comment]
the random mode works well, i'm going to try the sequential to see

**Comment by Vaalyn** [comment]
@radio5050 @btoplak @MyTheValentinus is this issue still valid or is this problem not happening anymore?

**Comment by radio5050** [comment]
yes it's solved.

thank you

________________________________
De : Vaalyn <notifications@github.com>
Envoyé : mardi 9 juillet 2019 13:42
À : AzuraCast/AzuraCast
Cc : radio5050; Mention
Objet : Re: [AzuraCast/AzuraCast] shuflle playlist act like sequential playlist (#1540)


@radio5050<https://github.com/radio5050> @btoplak<https://github.com/btoplak> @MyTheValentinus<https://github.com/MyTheValentinus> is this issue still valid or is this problem not happening anymore?

**Comment by MyTheValentinus** [comment]
Thanks you !
