### ISSUE TITLE
Remote URL does not work

### ISSUE THREAD

**Issue by NurLutix** [AzuraCast/AzuraCast#1541]
Hey,
I'm not using the Docer version and I'm using AzuraCast on Ubuntu 16.04.

I wanted to make a playlist with a remote URL today.
Unfortunately it doesn't play the URL.

![Screenshot_1](https://user-images.githubusercontent.com/35920440/57725930-99d7c880-768e-11e9-84e6-ed9ae2c385bb.png)
![Screenshot_2](https://user-images.githubusercontent.com/35920440/57726006-c986d080-768e-11e9-99fe-cb9cce199d3b.png)
![Screenshot_3](https://user-images.githubusercontent.com/35920440/57726008-cab7fd80-768e-11e9-88ca-b894eb362dee.png)

Could you help me? I guess it's a configuration error. 

Greetings.

**Comment by SlvrEagle23** [comment]
@NurLutix First of all, just out of curiosity, why are you using the non-Docker installation with Ubuntu 16.04? Out of all of our available installation options, that is the least recommended one.

We will need to see your logs. You can view the Liquidsoap logs by visiting "Utilities" on the left sidebar, then "Log Viewer". This log should mention any errors that are occurring.

**Comment by NurLutix** [comment]
I don't know why. I think there was an error when installing with Docker, so I didn't use Docker anymore. So far everything works.

The logs look like this:
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 21:42:56 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!

Greetings

**Comment by SlvrEagle23** [comment]
@NurLutix Based on your having created a GitHub issue, I disagree with your assertion that "everything works" ;)

It appears that your buffer is already set to 120 seconds, which is already rather high, but per the log instructions, try raising it higher and restarting the station to see if that helps.

**Comment by NurLutix** [comment]
Higher than 120 is unfortunately not possible.

**Comment by NurLutix** [comment]
If it helps, the file is about 2.5 minutes long.

**Comment by SlvrEagle23** [comment]
@NurLutix A 120-second buffer is almost the entire length of the song...I think something else is going wrong. Have you updated recently?

**Comment by NurLutix** [comment]
You mean AzuraCast? If yes, I guess not.
If you tell me how to update it, I'll do it. 


> A 120-second buffer is almost the entire length of the song

What should I put the buffers on?

**Comment by SlvrEagle23** [comment]
@NurLutix As a sudo-capable user, run:
```
cd /var/azuracast/www
./update.sh
```

**Comment by NurLutix** [comment]
Downloaded the update.
Now I can't start Liquidsoap anymore. :(

An error has occurred with Liquidsoap.
uffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 22:09:01 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 22:09:01 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 22:09:01 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/05/14 22:09:01 [http_6433:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!

**Comment by NurLutix** [comment]
And other stations make the mistake:

An error has occurred with Liquidsoap.
2019/05/14 22:16:21 [threads:3] Thread "non-blocking queue #1" terminated.
2019/05/14 22:16:21 [threads:3] Thread "generic queue #1" terminated.
2019/05/14 22:16:21 [threads:3] Queues shut down
2019/05/14 22:16:21 [server:3] Closing socket.
2019/05/14 22:16:21 [main:3] Cleaning downloaded files...
2019/05/14 22:16:21 [main:3] Freeing memory.

**Comment by SlvrEagle23** [comment]
@NurLutix The first error you posted is just the one from earlier, and the second one is a normal shutdown of Liquidsoap.

I'm not sure how to fix this issue because I don't have clear enough information on what the problem is.

**Comment by NurLutix** [comment]
What do you need for information?

**Comment by SlvrEagle23** [comment]
@NurLutix I need to know what's not working right now. You're saying Liquidsoap isn't starting on any station? Even if you visit "Utilities" > "Restart Broadcasting"?

**Comment by NurLutix** [comment]
The SHOUTcast server starts. Liquidsoap not. Also when restarting the station.

**Comment by SlvrEagle23** [comment]
@NurLutix Did the update script show any errors, or did it complete normally?

**Comment by NurLutix** [comment]
No mistakes so far. That's why I'm surprised too.

**Comment by SlvrEagle23** [comment]
@NurLutix And the bottom of the error log has no message indicating why it can't start?

If it's not logging the error, and nothing went wrong during the update...well...you can understand how this is basically impossible for us to diagnose.

This may mean that you've broken your installation. This may be a great opportunity to try the Docker installation again.

**Comment by NurLutix** [comment]
But what about my stations? I need them and cannot afford a downtime.
After the update.sh Liquidsoap does not work anymore. Can't I just reinstall it?

I sent you the logs, didn't I?

**Comment by SlvrEagle23** [comment]
@NurLutix Those logs don't indicate any error. That may not be the right part of the logs. Check elsewhere to see if it's giving you an error message.

I understand you want to avoid downtime, but you're using an installation method (Ansible on 16.04) that is specifically not recommended by us for this reason. There's only so much we can provide for free to users of our software, and we're even more limited by the installation method in question.

We can directly log in to your installation and debug the issue, but in any case we would strongly recommend moving your stations over to the Docker installation method.

**Comment by NurLutix** [comment]
So there are two possibilities?
1. I pay you and you look at it?
2. I reinstall the server and use Docker?

How much would it cost?

**Comment by SlvrEagle23** [comment]
@NurLutix You should e-mail me using the contact information I have listed here on GitHub if you're interested in me taking a look at your specific server.

For now, though, please check to verify that there aren't other logs that you haven't attached that are part of the Liquidsoap logs. The relevant error messages may be listed there.

You may also be able to resolve the issue by running:
```
cd /var/azuracast/www
./update.sh --full
```

(this takes a significant amount of time but will perform a "full" reinstallation)

**Comment by NurLutix** [comment]
Now I get the error:

TASK [nginx : Install nginx] ***************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'n                                                                                                                                                             ginx-extras' is available"}

PLAY RECAP *********************************************************************
localhost                  : ok=32   changed=6    unreachable=0    failed=1

**Comment by SlvrEagle23** [comment]
@NurLutix The `nginx-extras` package definitely exists for 16.04. I'm not sure what the problem is that's preventing that from installing.

**Comment by NurLutix** [comment]
When will you be available tomorrow? It is currently 23:26 in Germany. 
Then I would get back to you tomorrow and negotiate an amount with you or go looking for a mistake.

**Comment by NurLutix** [comment]
Well. Still getting the NGINX error.

**Comment by NurLutix** [comment]
Good morning. It's me again. Under Ubuntu 16.04 nginx-extras are no longer available.

root@CT101:/var/azuracast/www# apt install nginx-extras
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package nginx-extras is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  nginx-common

E: Package 'nginx-extras' has no installation candidate

**Comment by SlvrEagle23** [comment]
@NurLutix I'm quite confident that the `nginx-extras` package exists for Ubuntu. It's even in the main "universe" repository, which means it should definitely be showing up there.

Try running:

```
sudo add-apt-repository universe
sudo apt-get update
sudo apt-get install nginx-extras
```

**Comment by NurLutix** [comment]
I have reinstalled the server and will now use the Docker version. If I have any questions, I will get back to you.
