### ISSUE TITLE
How do I call the private API endpoints

### ISSUE THREAD

**Issue by Zenternal** [AzuraCast/AzuraCast#1542]
I know how to grab JSON data for things that don't need to be authorized, but for things such as station/1/history, i'm completely clueless. I'm using PHP, and I've been stuck on this for an hour now. Any help is appreciated.

**Comment by Vaalyn** [comment]
Hey, to access private endpoints you need to send the `Authorization: Bearer your_api_key_here` header with your request to the API.

I'm building an PHP API client for AzuraCast that is still WIP and for that I'm using Guzzle as HTTP request library [here](https://github.com/Vaalyn/azuracast-api-client/blob/master/src/AzuraCastApiClient.php#L1455) is how I setup my http client to be able to call these endpoints and [here](https://github.com/Vaalyn/azuracast-api-client/blob/master/src/AzuraCastApiClient.php#L203) is a call to that endpoint. I hope that I could help you with that.

**Comment by Zenternal** [comment]
I'm not quite sure how to set that up, sorry 😕

**Comment by Vaalyn** [comment]
How are you calling the other non-private endpoints? Are you using an http client library, curl or just `file_get_contents()` ?

If you share how you do it for the other endpoints atm I may be able to help you with it.

**Comment by Zenternal** [comment]
@Vaalyn like so:
$json = json_decode(file_get_contents("https://radio.itspower.net/api/nowplaying/1"), TRUE);
$song = $json["now_playing"]["song"]["text"];
$dj = $json["live"]["streamer_name"];

**Comment by Vaalyn** [comment]
Okay so you are using `file_get_contents` to call the endpoint. [This](https://stackoverflow.com/questions/2107759/php-file-get-contents-and-setting-request-headers) StackOverflow thread will probably help you then. The header should be defined as `Authorization: Bearer xxxxxxxxxxx` where you change the xxxxx to your API key that you generate through the web interface. That would probably be the easiest way were you don't have to change your code much. If you want something more sophisticated you should take a look at [Guzzle](https://packagist.org/packages/guzzlehttp/guzzle) or [cURL](https://php.net/manual/de/book.curl.php).

**Comment by Zenternal** [comment]
I'll keep trying to play around with that. Thanks.
