### ISSUE TITLE
timezone

### ISSUE THREAD

**Issue by Virusjuh** [AzuraCast/AzuraCast#1544]
hello,

today i updated the docker, 
and yesterday after some updates and today the orange dot. in schedule stay 2 hours behind.
the shows has been messed up, (that can i fix by reprogram)
but the utc+2 now working he stays on  UTC (thats 2 hours before my localtime)
how can i change this?

**Comment by SlvrEagle23** [comment]
@Virusjuh We've switched the time zones in AzuraCast to be per-station, so each station has its own time zone and everything in that station uses that time zone.

You can edit the station's profile to change the time zone to UTC+2, and all playlist schedules and other items will work normally.

**Comment by Virusjuh** [comment]
yes i tried that, but the playlist it totaly out of order now. thats not the problem. but the red arrow is 2 hours behind. he is taking UTC while my local time is +2 set on the station. if i look the the logs all got the local timezone except azuracast, Doesnt matter wichtimezone i put the orange arrow of the current time dont change

**Comment by SlvrEagle23** [comment]
@Virusjuh Is your local time zone different from the time zone your station uses?

I will look into this, it sounds like it could definitely be a bug with how the calendar is handling "local" time.

**Comment by Virusjuh** [comment]
im using CET 
[![Screenshot from Gyazo](https://gyazo.com/14f8fb7baa236ead9e745e6a79028931/raw)](https://gyazo.com/14f8fb7baa236ead9e745e6a79028931)
azuracast uses UTC and icecast and liquidsoap as i can see in the logs uses local. 
[![Screenshot from Gyazo](https://gyazo.com/9a1f21e64b7e297a1db3624736e087de/raw)](https://gyazo.com/9a1f21e64b7e297a1db3624736e087de)
[![Screenshot from Gyazo](https://gyazo.com/c10c49c9248dca906bf536fffb06df3e/raw)](https://gyazo.com/c10c49c9248dca906bf536fffb06df3e)

**Comment by griffon56** [comment]
I see the same offset and I believe it is just a display bug only located on the schedule view, since I have the same offset of 2 hours between the red line in "schedule view" and the displayed time in the playlist setting "The current time in the station's time zone is ". The time shown when editing the playlist is correct. The playlist actually played is using also correct.

**Comment by SlvrEagle23** [comment]
@Virusjuh @griffon56 Just pushed out an update that fixes the visual display on the main Playlists page, both of the times on the main playlist listing and of the time zones (and the "now" arrow) on the schedule view.

I also added a note at the top of the page showing what the current station-wide timezone is set to, to avoid any confusion.

**Comment by Virusjuh** [comment]
thanks. its fixed now,
