### ISSUE TITLE
adding my ssl certificate to the nginx docker

### ISSUE THREAD

**Issue by dreinn** [AzuraCast/AzuraCast#1546]
Hello,
since I don't use standard port for now, letsencrypt can't work.
So I'd like to put my ssl certificate in the nginx configuration of docker. I don't know what to modify, I can't see anything in the docker-compose.yml.

For now, if I go to:
nv-radio.it:444

I obtain a terrible:
400 Bad Request
The plain HTTP request was sent to HTTPS port

Any idea?

**Comment by dreinn** [comment]
I created a volume in the docker-compose.yml file to /etc/nginx.
Now I see the ssl directory inside /etc/nginx, but I want to find the nginx.conf... in order to tell nginx to use my ssl certs!
Where is that file?

**Comment by SlvrEagle23** [comment]
@dreinn You're probably better off mapping the SSL files directly into the spot nginx is expecting them to be, i.e.:

```yaml
    volumes:
      - /host/path/to/ssl.crt:/etc/letsencrypt/ssl.crt
      - /host/path/to/ssl.key:/etc/letsencrypt/ssl.key
```

Then it will just read those files instead of using LetsEncrypt.

**Comment by dreinn** [comment]
Thank you SlvrEagle23.
I will try this later!
