### ISSUE TITLE
Android and iOS app

### ISSUE THREAD

**Issue by buhajuj** [AzuraCast/AzuraCast#1547]
Hello,

Please recommend Open Source iOS and Android apps compatible with AzuraCast.

Buhajuj

**Comment by macbroadcast** [comment]
https://coolmic.net/

**Comment by bayubad** [comment]
Coolmic is used to live streaming to Icecast. It's not an App to stream playlists from AzuraCast.

**Comment by macbroadcast** [comment]
@bayubad i don't even know what you try to achieve and what an " App to stream playlists from AzuraCast" is good for :smile:

**Comment by SlvrEagle23** [comment]
@buhajuj One of the most popular programs for playing web radio is TuneIn. You can submit your station to TuneIn via their web site, and then set up a TuneIn web hook inside AzuraCast to make sure they always have the latest "now playing" information.

**Comment by bayubad** [comment]
At present, TuneIn are not accepting new radio station submissions from any provider.

**Comment by SlvrEagle23** [comment]
@buhajuj Really? Oh dear...

**Comment by bayubad** [comment]
Anyone has experience with https://github.com/muhku/FreeStreamer or https://github.com/hamedh/Radio ?

**Comment by ErnestPH** [comment]
@buhajuj I've found a SASS bases on react that can produce unlimited radio apps both identical for iOS and Android. You want to check that out...

**Comment by afonsosantos** [comment]
@ErnestPH Hi!

Can you provide the name of that React-based SASS?

Thanks

**Comment by ErnestPH** [comment]
However, it's not for free and you have to set it up aside from creating the apps. `
React App Builder - SaaS - Unlimited number of apps`

**Comment by afonsosantos** [comment]
Thanks, will check it out!
