### ISSUE TITLE
Where is nginx?

### ISSUE THREAD

**Issue by bayubad** [AzuraCast/AzuraCast#1549]
I could not find where NGINX has been installed by dockers to edit the default page.
It's not on /var/www/ . Where is it?

**Comment by Vaalyn** [comment]
Docker does not install anything on your host machine. Docker works by creating containers for the services defined in the docker-compose.yml and mapping the ports of those containers to the ones of the host machine.

Why do you want to touch the NGINX of AzuraCast?
If you tell us more about what you want to achieve we might be able to give you some directions on how to do what you want. In general you shouldn't need to edit anything manually inside of Docker containers.

**Comment by bayubad** [comment]
I need to edit the domain.com/public/station INDEX page.
Also, can I change the default page address from domain.com/public/station to domain.com/station?

**Comment by Vaalyn** [comment]
What exactly do you want to change in the public station page?

For changing the URL you should probably put AzuraCast behind a reverse proxy and configure that to map calls to `domain.com/station` to internally call `domain.com/public/station`.

We strongly discourage users from changing core files of AzuraCast as any changes to those files will be lost on the next update.

**Comment by bayubad** [comment]
To customized the background image and color and add Station Name for each station.

**Comment by Vaalyn** [comment]
For changes that can be done with pure CSS you should use the `Custom CSS for Public Pages ` in `System Administration` -> `Custom Branding`.

All in all it sounds like you want to use the public page as your main website for the station. It's probably a better idea to just built a small standalone website and use our player embed widget that you can find on the profile page to include the player on your website.

**Comment by Vaalyn** [comment]
Closing as we do not officially support modifying the NGINX configuration and a better solution for the described use-case has been provided.
