### ISSUE TITLE
After update to  v0.9.5 all playlist have moved up 4 hours ?

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#1551]
Or is there any "new" setting that i overlooked?

Thanks

**Comment by Vaalyn** [comment]
This is most likely due to this part of the release update:

> Schedule Overhaul: Previously, each user had their own time zone on their profile, and the system had a default time zone setting, but schedules were based on UTC and constantly had to be converted back and forth from the user's local time. This conversion caused a number of problems. To address them, we completely restructured the time zone system. Now, each station has its own time zone, and all scheduled playlists are based on this time zone. Liquidsoap and Icecast/SHOUTcast are also run in this time zone, so schedule times (and logs) will always be consistent.

You can look at the conversation in #1544 to get more information.

**Comment by SlvrEagle23** [comment]
@macbroadcast You should also try updating to the latest "rolling release" version which was released just after 0.9.5 came out, which fixes an issue with the playlist schedule view not showing the correct time.

**Comment by macbroadcast** [comment]
hi @SlvrEagle23 I just updated with `./docker.sh update-self
./docker.sh update` without the --release flag and I see no change, whats the release after v0.9.5 ?
because it still shows v0.9.5 at the bottom.

**Comment by SlvrEagle23** [comment]
@macbroadcast The release will still show 0.9.5, there isn't a new release out since it was a single fix. You may need to edit your playlists or your station timezone to line things up, especially if you were depending on your user profile's time zone in the previous version.

**Comment by macbroadcast** [comment]
My station timezone is fine, but all playlists are 4 hours to early, so please don't tell me i need to edit all playlists? :crying_cat_face:

**Comment by SlvrEagle23** [comment]
@macbroadcast If you actually go into the station playlist "Edit" page and the scheduled times are still 4 hours off there (instead of just when viewing them on the main page), then yes, it's possible that the converter didn't recognize your specific setup.

**Comment by macbroadcast** [comment]
Never mind wasn't a biggy, fixed already, thanks for all your work, looks much better now. :+1:
