### ISSUE TITLE
Songfiles be part of more then one Playlist ?

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#1552]
I remember a while ago it was possible to add songs to more than one playlist.
This feature disappeared somehow. I have a lot of playlists and music folders, some of them are scheduled playlists, but these songs never appear during normal airtime. Is there any chance to play songs on more than one playlist or play tracks from a scheduled playlist during "normal" airtime ?

Thanks

**Comment by SlvrEagle23** [comment]
@macbroadcast This feature didn't disappear at all. When you select a song, and then click "Set Playlists", you can just check multiple boxes for all of the playlists you want the song to be a part of. We changed the interface around a bit to more logically match how most people did playlist management, but the feature set is exactly the same.

**Comment by macbroadcast** [comment]
But why only one playlist appears on the right side ? Before you saw 2 or more, this is a bit confusing, no ? 
![Bildschirmfoto von 2019-05-17 11-13-34](https://user-images.githubusercontent.com/7961/57917464-04f2ec00-7895-11e9-8922-1d6125572953.png)

**Comment by SlvrEagle23** [comment]
@macbroadcast If a song's in more than one playlist, it will still show the playlists separated with a comma. It appears in this case, neither of those songs are actually in multiple playlists.

**Comment by macbroadcast** [comment]
I see you have to select them both, sorry
