### ISSUE TITLE
playlist rotation rules problem

### ISSUE THREAD

**Issue by emadi78** [AzuraCast/AzuraCast#1554]
hi guys... 

i have problem my in my rotation playlist it's the same time play the song... if i skip song it's change but the same song... please how can fix it?

**Comment by Vaalyn** [comment]
Please use our issue template when creating bug reports as it will help us when trying to reproduce any issues you encounter. We need to know more about your setup to help you identify why your playlist is doing what it does. Copy the template from [here](https://github.com/AzuraCast/AzuraCast/issues/new?template=bug_report.md) and edit this issue and fill in the information requested in the template.
