### ISSUE TITLE
Can't edit playlist (save changes button) doesn't work

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#1555]
Installation
Docker Ubuntu 18

Latest Azuracast build

When editing the playlist's name or weight. The save changes button is not responding when click.
Go to playlist
Edit Playlist
Save playlist -> won't do anything

Creating and deleting a playlist has no problem at all.

Browser is Mac Safari.

Thanks!

**Comment by SlvrEagle23** [comment]
@ErnestPH We just noticed this issue reported by a few other people...try switching your playlist type to "Remote URL" and then back to its original setting. You may see an error message pop up there.

**Comment by SlvrEagle23** [comment]
@ErnestPH We've applied a migration to the database, as well as some improvements that help show errors like that when they pop up. Let me know if this fixes the issue for you!

**Comment by ErnestPH** [comment]
@SlvrEagle23 Unfortunately, the Save changes button is not responsive still when editing a playlist.

Go to Edit Playlist
Change any settings
Click Save changes -> nothing happens

Note: deleting a playlist works…

**Comment by SlvrEagle23** [comment]
@ErnestPH Are you updating to the latest rolling release? We don't tag a new release version every time we fix a single bug, so you'll want to be on the very latest rolling release version (as of right now, it would be 54c9e5) to take advantage of the updates.

**Comment by ErnestPH** [comment]
Yes updated to the latest version - 54c9e5. Issue is still present

**Comment by SlvrEagle23** [comment]
@ErnestPH Since it isn't possible for us to reproduce this issue locally, would you mind e-mailing us with temporary credentials to your AzuraCast installation so we can take a look and see if we can investigate the issue further?

**Comment by ErnestPH** [comment]
@SlvrEagle23 Sorry but when I tested it on Chrome for Mac it worked :) and then I tried it on Safari again and it worked. Probably it was not updated that time when I tested back in Safari. Thanks for the effort!

**Comment by SlvrEagle23** [comment]
@ErnestPH Glad to hear it's resolved!
