### ISSUE TITLE
Live DJ Streamer not detected by Azuracast

### ISSUE THREAD

**Issue by adamderann** [AzuraCast/AzuraCast#1557]
**Using Docker installation method**
Yes, using DigitalOcean installation instructions, with lets encrypt ssl setup. I have not experienced this issue with traditional install.

**Host Operating System**
Ubuntu 18.04 x64 

**Describe the bug**
When a DJ streamer starts streaming to the server from BUTT, Azuracast does not recognise this. The API reports that the user is not live and the front end profile reports Now Playing as Stream Offline.
The on connect webhook and on disconnect webhooks do not fire either - possibly related?
There is only 1 station on this azuracast install.

**To Reproduce**
Start a stream to the azuracast install from BUTT - Icecast not shoutcast. 

**Expected behavior**
Shortly after a stream is started, the API should report that the streamer user is live and Now Playing should report the streamer username as live. 

**Relevant Logs**
See the user 'a' connecting and disconnecting successfully from the icecast logs.
`2019/05/18 17:12:05 [lang:3] AzuraCast Feedback Response: OK
2019/05/18 17:13:58 [lang:3] Authenticating DJ: a
2019/05/18 17:13:59 [lang:3] AzuraCast DJ Auth Response: true
2019/05/18 17:13:59 [decoder:3] Method "MAD" accepted "audio/mpeg".
2019/05/18 17:13:59 [lang:3] DJ Source connected! [("Authorization","Basic YTph"), ("Host","lon1-4.i.polynation.live:8005"), ("User-Agent","butt 0.1.16"), ("Content-Type","audio/mpeg"), ("ice-name","no name"), ("ice-public","0"), ("ice-audio-info","ice-bitrate=320;ice-channels=2;ice-samplerate=44100")]
2019/05/18 17:13:59 [station1_live_switch:3] Switch to station1_live_fallback with transition.
2019/05/18 17:13:59 [lang:3] AzuraCast Live Connected Response: received
2019/05/18 17:13:59 [threads:3] Created thread "harbor source feeding" (2 total).
2019/05/18 17:13:59 [station1_input_streamer:3] Decoding...
2019/05/18 17:13:59 [station1_live_fallback:3] Switch to blank_6470 with forgetful transition.
2019/05/18 17:13:59 [smart_cross_6483:3] Analysis: -9.046993dB / -nandB (3.00s / 0.00s)
2019/05/18 17:13:59 [smart_cross_6483:3] Not enough data for crossing.
2019/05/18 17:14:02 [smart_cross_6483:3] Analysis: -nandB / -infdB (0.00s / 0.04s)
2019/05/18 17:14:02 [smart_crossfade:3] Old <= medium, new <= medium and |old-new| <= margin.
2019/05/18 17:14:02 [smart_crossfade:3] Old and new source are not too loud and close.
2019/05/18 17:14:02 [smart_crossfade:3] Transition: crossed, fade-in, fade-out.
2019/05/18 17:14:02 [smart_cross_6483:3] Analysis: -infdB / -infdB (1.96s / 1.96s)
2019/05/18 17:14:02 [smart_crossfade:3] Old <= medium, new <= medium and |old-new| <= margin.
2019/05/18 17:14:02 [smart_crossfade:3] Old and new source are not too loud and close.
2019/05/18 17:14:02 [smart_crossfade:3] Transition: crossed, fade-in, fade-out.
2019/05/18 17:14:04 [smart_cross_6483:3] Analysis: -infdB / -infdB (0.04s / 0.04s)
2019/05/18 17:14:04 [smart_crossfade:3] Old <= medium, new <= medium and |old-new| <= margin.
2019/05/18 17:14:04 [smart_crossfade:3] Old and new source are not too loud and close.
2019/05/18 17:14:04 [smart_crossfade:3] Transition: crossed, fade-in, fade-out.
2019/05/18 17:14:04 [station1_live_fallback:3] Switch to audio_to_stereo_6467 with transition.
2019/05/18 17:14:04 [smart_cross_6483:3] Analysis: -infdB / -49.838461dB (0.04s / 0.04s)
2019/05/18 17:14:04 [smart_crossfade:3] new >= old + margin, old <= medium and new <= high.
2019/05/18 17:14:04 [smart_crossfade:3] Do not fade if it's already very low.
2019/05/18 17:14:04 [smart_crossfade:3] Transition: crossed, no fade.
2019/05/18 17:26:05 [station1_input_streamer:2] Feeding stopped: Mad.End_of_stream.
2019/05/18 17:26:05 [lang:3] DJ Source disconnected!
2019/05/18 17:26:05 [station1_live_switch:3] Switch to map_metadata_6450 with transition.
2019/05/18 17:26:05 [lang:3] AzuraCast Live Disconnected Response: received`

**Screenshots**

![image](https://user-images.githubusercontent.com/22745345/57973023-2be71600-799a-11e9-8929-49f77d767448.png)
![image](https://user-images.githubusercontent.com/22745345/57973029-3c978c00-799a-11e9-84d2-887b229829c5.png)
^ note the speaker icon indicating sound being output in the next tab which is the audio uploaded through BUTT.

**Comment by adamderann** [comment]
Oh it's probably the same as #1482

**Comment by Vaalyn** [comment]
This is most likely due to the same underlying issue of #867. Please follow that issue for this bug.

**Comment by adamderann** [comment]
@Vaalyn the same happens when I connect and stream using the Web DJ, haven't had this problem on the traditional install.

**Comment by Vaalyn** [comment]
Would you mind testing if the behaviour changes when you connect via Mixxx?
That way we can determine if it's something the client causes or if it is something on the server side.

**Comment by adamderann** [comment]
I already had RocketBroadcaster installed and experienced the same behaviour. Manually setting the meta on the right hand side didn't do anything either.
![image](https://user-images.githubusercontent.com/22745345/57985480-8ea2e500-7a60-11e9-8005-a5f09b7cf37c.png)
![image](https://user-images.githubusercontent.com/22745345/57985564-8e571980-7a61-11e9-87ae-34475c051845.png)


I've noticed that once a dj streamer disconnects, it doesn't go back to the song name and Now Playing remains as 'Stream Offline'. Also, when a streamer disconnects, the mp3 mount ends and autodj doesn't start - only after refreshing the open mp3 mount tab does it go back to the autodj - same for when a streamer connects - the mp3 ends.

**Comment by adamderann** [comment]
@Vaalyn I've created 2 new stations and both worked first of all, streamer name coming in the Now Playing box, and 'disconnect streamer' button appearing, but after the first stream it doesn't seem to work.
