### ISSUE TITLE
Live listener not working

### ISSUE THREAD

**Issue by suricloud** [AzuraCast/AzuraCast#1558]
Hi,

I have the docker verions on debian9,and i just updated to the latest version.
Now i see the live listener report is not working,not showing the listerner ip's anymore,and yes i do have metadata info on the streams.Before the update it was working.

**Comment by SlvrEagle23** [comment]
@suricloud The map was just reimplemented a few minutes ago to use the Leaflet library (for licensing reasons, we couldn't continue to use the Highcharts/Highmaps library we were using before). Update again and it should be back.

**Comment by suricloud** [comment]
Just updated again,and yess its working again:) Looks even better then previous map.Great job!
It woul be nice if the ips were shown of a live radio connection even metadata is not sent.Because some encoders doesnt have the option to send metadata.Hopefully you find a work around,In centova it is working even with no metadata sent.
