### ISSUE TITLE
Azuracast not loading after reboot

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#156]
Hello,

On a fresh installation with the latest azurcast, its not working when the server is rebooted.
Azuracast not loading anymore.

**Comment by surihost** [comment]
Also cant login to ssh anymore, because i already had changend my ssh port.
Is this happening maybe because of ufw  firewall?

**Comment by SlvrEagle23** [comment]
@surihost Yes, the SSH issue is happening because you changed your default SSH port. You'll need to get into the recovery console for your server and `sudo ufw allow {new ssh port}/tcp`.

As for AzuraCast not running at all...did you set it up to proxy through a non-standard port? You may also want to check that supervisord didn't goof up, and make sure it's enabled with `service supervisord enable && service supervisord start`.

**Comment by surihost** [comment]
I tried several times, just installed and see if azuracast was loading.It was loading...didnt go further with the setup..so no proxy settings touched.I rebooted the server and azuracast not loading anymore.

And for supervisord i get this:

service supervisord enable && service supervisord start
supervisord: unrecognized service

**Comment by SlvrEagle23** [comment]
@surihost I've pushed a major update that reverts the previous changes which moved AzuraCast itself (nginx, mysql, php, influx) underneath supervisord's control. If you update your code, you should return back to the normal method of operation.

It appears, especially on 14.04, that supervisord has a number of issues preventing it from being used as the global controller for all core services.

**Comment by surihost** [comment]
I see you updated it, and after the update azurcast is loading  fine now:)
Next problem the ports of of the streams are blocked i think,
Like i assigned port 9035 to station, it isn't showing up although its active and running in azuracast panel.
Maybe ufw again?

**Comment by SlvrEagle23** [comment]
@surihost Yep, that one's UFW again, any time you venture out past the standard ports AzuraCast uses just make sure to `ufw allow newport/tcp`

**Comment by surihost** [comment]
Didn't you allowed ports 8000:9990 to open by default?

**Comment by SlvrEagle23** [comment]
@surihost 8000-8999, since that allows 100 stations. You can always expand the UFW rules, since AzuraCast doesn't overwrite other rules, just adds the exemptions it needs for itself.

**Comment by surihost** [comment]
Great ! All working fine now.
