### ISSUE TITLE
How can I connect to AzuraCast Docker via Telnet?

### ISSUE THREAD

**Issue by Rootinator** [AzuraCast/AzuraCast#1560]
Hello, 

how can I connect to Telnet on AzuraCast Docker?

**Comment by dreinn** [comment]
I think you should look at liquidsoap.liq that you find in the utility section of your station.
The first lines define the liquidsoap environment and you can easily find your telnet port.
DON'T CHANGE THAT FILE DIRECTLY!
So for example you can do:

telnet 127.0.0.1 8003

where 8003 is your defined telnet port and you must replace it with your value.

Then, you can use the liquidsoap appropriate command to issue requests and other.

**Comment by SlvrEagle23** [comment]
@Rootinator Are you trying to connect to Liquidsoap's telnet interface to issue it commands, or are you trying to do something else?

If you're just wanting to access a terminal shell inside the Docker container, you can just run:

```bash
./docker.sh bash
```

...in your base directory.

**Comment by Rootinator** [comment]
> @Rootinator Are you trying to connect to Liquidsoap's telnet interface to issue it commands, or are you trying to do something else?

I would like to move songs or playlists via Telnet to the Liquidsoap queue.
