### ISSUE TITLE
Merge playlist: scheduling is not respected

### ISSUE THREAD

**Issue by dreinn** [AzuraCast/AzuraCast#1561]
**Using Docker installation method** yes
**Host Operating System** ubuntu 16.04
**Describe the bug**
When the following options are combined, the scheduling of the station is broken, a playlist can go for 30/40 minutes out of its range.
In the liquidsoap log, a continous message of main_clock catchup of some seconds appear.

**To Reproduce**
1. Go to playlist settings and open one.
2. Set Interrupt other songs to play at scheduled time to off.
3. set Merge playlist to play as a single track to on.
4. Restart station.
5. Listen to your station, scheduled is not respected.

**Expected behavior**
Scheduling should be regular.

**Relevant Logs**
# At 9 AM classical music should stop after the end of the song; there is a TimeSignal that go over the song in voiceover at 09.00, then, italian music should start; as you can see, classical music continues.

2019/05/20 08:53:36 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/nvradio/media/musica/musica sinfonica/dvorak_op95_hj_01_adagio_al_etc.mp3".
2019/05/20 08:53:47 [playlist_musica_sinfonica:3] Finished with "/var/azuracast/stations/nvradio/media/musica/musica sinfonica/erik_satie._piano._gnossienne_no_1._partitura._audicion.mp3".
2019/05/20 08:53:47 [playlist_musica_sinfonica:3] Prepared "/var/azuracast/stations/nvradio/media/musica/musica sinfonica/dvorak_op95_hj_01_adagio_al_etc.mp3" (RID 8).
2019/05/20 08:53:52 [lang:3] AzuraCast Feedback Response: OK
2019/05/20 08:53:52 [clock.wallclock_main:2] We must catchup 1.24 seconds!
2019/05/20 09:00:00 [playlist_TimeSignal_ore_9:3] Prepared "/var/azuracast/stations/nvradio/media/SegnaliOrario/senzajingle_segnale_orario_ore_9.mp3" (RID 7).
2019/05/20 09:00:00 [fallback_6856:3] Switch to switch_6855 with transition.
2019/05/20 09:00:03 [lang:3] AzuraCast Feedback Response: OK
2019/05/20 09:00:03 [clock.wallclock_main:2] We must catchup 3.06 seconds!
2019/05/20 09:00:03 [fallback_6856:3] Switch to smart_cross_6849 with transition.
2019/05/20 09:00:04 [lang:3] AzuraCast Feedback Response: OK
2019/05/20 09:00:04 [clock.wallclock_main:2] We must catchup 4.17 seconds!
2019/05/20 09:00:05 [clock.wallclock_main:2] We must catchup 3.91 seconds!
2019/05/20 09:00:06 [clock.wallclock_main:2] We must catchup 3.53 seconds!
2019/05/20 09:03:02 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/nvradio/media/musica/musica sinfonica/dvorak_op95_hj_03_scherzo_m_etc.mp3".
2019/05/20 09:03:13 [playlist_musica_sinfonica:3] Finished with "/var/azuracast/stations/nvradio/media/musica/musica sinfonica/dvorak_op95_hj_01_adagio_al_etc.mp3".
2019/05/20 09:03:13 [playlist_musica_sinfonica:3] Prepared "/var/azuracast/stations/nvradio/media/musica/musica sinfonica/dvorak_op95_hj_03_scherzo_m_etc.mp3" (RID 6).
2019/05/20 09:03:18 [lang:3] AzuraCast Feedback Response: OK
2019/05/20 09:10:32 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/nvradio/media/musica/musica sinfonica/giuseppe_verdi_-_rigoletto_-_overture.mp3".
2019/05/20 09:10:43 [playlist_musica_sinfonica:3] Finished with "/var/azuracast/stations/nvradio/media/musica/musica sinfonica/dvorak_op95_hj_03_scherzo_m_etc.mp3".
2019/05/20 09:10:43 [playlist_musica_sinfonica:3] Prepared "/var/azuracast/stations/nvradio/media/musica/musica sinfonica/giuseppe_verdi_-_rigoletto_-_overture.mp3" (RID 4).
2019/05/20 09:10:48 [lang:3] AzuraCast Feedback Response: OK
2019/05/20 09:10:48 [clock.wallclock_main:2] We must catchup 1.00 seconds!
2019/05/20 09:12:54 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/nvradio/media/musica/musica sinfonica/satie___la_belle_excentrique___complete.mp3".
2019/05/20 09:13:04 [playlist_musica_sinfonica:3] Finished with "/var/azuracast/stations/nvradio/media/musica/musica sinfonica/giuseppe_verdi_-_rigoletto_-_overture.mp3".
2019/05/20 09:13:04 [playlist_musica_sinfonica:3] Prepared "/var/azuracast/stations/nvradio/media/musica/musica sinfonica/satie___la_belle_excentrique___complete.mp3" (RID 9).
2019/05/20 09:13:10 [lang:3] AzuraCast Feedback Response: OK
2019/05/20 09:21:10 [decoder:3] Method "MAD" accepted

**Comment by SlvrEagle23** [comment]
@dreinn I'm merging this issue with several other reports we've received along the same lines. Please follow the super-issue #1564 for updates.
