### ISSUE TITLE
Playlist every X minutes plays only one title instead of several

### ISSUE THREAD

**Issue by Rootinator** [AzuraCast/AzuraCast#1562]
Hello,

The playlist "Jingle-Playlist" (example) should be played every 30 minutes (content: 2 jingles), but only one jingle will play instead of the existing 2 jingles.

What do I have to do, that all jingles are played in sequence (without repeat)?

My settings of the playlist "Jingle-Playlist":
https://s16.directupload.net/images/190416/ezncpqr9.png
https://s16.directupload.net/images/190416/xuui2r99.png

I put a checkmark on "only loop playlist once".

Version: 0.9.5

**Comment by SlvrEagle23** [comment]
@Rootinator I'm merging this issue with several other reports we've received along the same lines. Please follow the super-issue #1564 for updates.
