### ISSUE TITLE
I have an error after the update: (

### ISSUE THREAD

**Issue by be2clack** [AzuraCast/AzuraCast#1563]
<img width="498" alt="Снимок экрана 2019-05-20 в 18 07 25" src="https://user-images.githubusercontent.com/1636306/58020507-23bde080-7b2a-11e9-9f75-28e99e170116.png">
<img width="1035" alt="Снимок экрана 2019-05-20 в 18 07 42" src="https://user-images.githubusercontent.com/1636306/58020518-2d474880-7b2a-11e9-9da0-723de00a8890.png">

**Comment by SlvrEagle23** [comment]
@be2clack Your update failed for a reason I've never seen before.

This is yet another reason we highly don't recommend using our Ansible ("Traditional" or "Bare-Metal") installation type, as bizarre errors like this seem to be common on web hosts out there.

I would suggest installing `aptitude`, but it _has_ to have been installed this whole time for your instance to have _ever_ worked.

I have no idea how to fix this one. This may be an issue with your web host.

**Comment by be2clack** [comment]
> @be2clack Your update failed for a reason I've never seen before.
> 
> This is yet another reason we highly don't recommend using our Ansible ("Traditional" or "Bare-Metal") installation type, as bizarre errors like this seem to be common on web hosts out there.
> 
> I would suggest installing `aptitude`, but it _has_ to have been installed this whole time for your instance to have _ever_ worked.
> 
> I have no idea how to fix this one. This may be an issue with your web host.

you can see?

**Comment by SlvrEagle23** [comment]
@be2clack Message me on Slack, I'm not sure I have access to your server, but I do have access to the panel itself.

**Comment by beerlovesme** [comment]
Hi guys, got something like this after update. Systems shows that was no updates installed. Maybe anyone knows what is going on?

`                                                                                                                        
 [OK] AzuraCast is now updated to the latest version!                                                                   
                                                                                                                        

2019/05/22 04:50:16 Command finished successfully.
azuracast_influxdb_1 is up-to-date
azuracast_stations is up-to-date
azuracast_redis_1 is up-to-date
azuracast_mariadb_1 is up-to-date
Creating azuracast_web_1 ... error

ERROR: for azuracast_web_1  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web_1 (9133e4cbad12d0822c13d8e7b621f448b9d708e7c38beaa5ff8602565bff9c65): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web_1 (9133e4cbad12d0822c13d8e7b621f448b9d708e7c38beaa5ff8602565bff9c65): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
ERROR: Encountered errors while bringing up the project.
Update complete!
root@vps-30767:~# `

**Comment by Vaalyn** [comment]
@beerlovesme You most likely have an Apache / httpd process running on your host machine that already uses port 443. Stop that process and remove it from autostart, then restart AzuraCast.

**Comment by MrSteelMiner** [comment]
better restart the whole Server

**Comment by Vaalyn** [comment]
@MrSteelMiner Just restarting the server doesn't solve anything here. The majority issues were the error `bind: address already in use` is thrown is due to having another web server running on the host machine. Most web servers are started automatically on startup of the machine so just restarting the server will also restart Apache / httpd / NGINX. The other service using that port needs to be disabled, have it's port changed or you need to run AzuraCast on a custom port but since most people who encountered this error before were installing AzuraCast on a stock Ubuntu Server they just had the default httpd running on it without intending to host any other websites through it. The best solution for that is to just uninstall that service from the machine.

**Comment by MrSteelMiner** [comment]
@Vaalyn you got me wrong. It was an addition to your solution. On my server, AzuraCast's behaviour is strange sometimes and if it doesn't want to run (not because of a binding error) rebooting the server fixed it in the most situations. 
So: `systemctl disable apache2; reboot` should fix it.

**Comment by Vaalyn** [comment]
@MrSteelMiner Thanks for the clarification but I have to add that in most cases it is not AzuraCast that is behaving strangely but the unusual setup of the server in those cases. With a standard Ubuntu / Debian with a fairly up to date version of the OS you won't need to restart your server for anything related to AzuraCast (apart from the one time setup of Docker when installing AzuraCast).

You also need to differentiate between Docker installations and the legacy Ansible installations. When using Docker the list of things that can actually effect AzuraCast is pretty small and comes down to basically "other software is using the same port", "permission issues" and "other software that is needed is missing or unavailable". With those Ansible installations there can be a myriad of things that can effect AzuraCast which makes those types of installations rather brittle in comparison.

**Comment by Vaalyn** [comment]
@be2clack @SlvrEagle23 Is this issue still valid / ongoing?

**Comment by SlvrEagle23** [comment]
I haven't heard anything from @be2clack via Slack, but I can probably see about helping if you contact me there.

**Comment by Vaalyn** [comment]
@be2clack Please contact us via Slack until the end of the week or I'll close this issue as I assume it to be resolved / invalid then.
