### ISSUE TITLE
PHP Library

### ISSUE THREAD

**Issue by Weigand-Dev** [AzuraCast/AzuraCast#1565]
Hi, i have a question.

How can i use this PHP Library https://github.com/Vaalyn/azuracast-api-client ?

Can you see me a example to use this?

Thanks

Sorry I'm not the best in PHP.

**Comment by Vaalyn** [comment]
Hey, I've donated that library to the AzuraCast project, it's available on [Packagist](https://packagist.org/packages/azuracast/php-api-client) so you can include it in your projects via [Composer](https://getcomposer.org/) and on the [repository](https://github.com/AzuraCast/php-api-client) in the AzuraCast organization.

In the [README.md](https://github.com/AzuraCast/php-api-client/blob/master/README.md) of the library you can find a small snippet that shows you how to use the client and all the currently available endpoints and what they expect as input.

This is what a script could look like to make use of that library:
```
<?php

use AzuraCast\AzuraCastApiClient\AzuraCastApiClient;

$azuraCastApiClient = new AzuraCastApiClient(
	'demo.azuracast.com',
	'1234567890:1234567890'
);

$nowPlaying = $azuraCastApiClient->nowPlaying();

echo $nowPlaying->getCurrentSong()->getSong()->getTitle();
```

The library will always return either a DTO (Data-Transfer-Object), which is just a class that holds the data from the API, or an array of DTOs. You can see what data you can get from each DTO by either looking into them [directly](https://github.com/AzuraCast/php-api-client/tree/master/src/Dto) or by using an IDE that includes autocompletion.

**Comment by Vaalyn** [comment]
Closing this issue as the original question has been answered.
