### ISSUE TITLE
Install.sh issue

### ISSUE THREAD

**Issue by RoxyBoxxy** [AzuraCast/AzuraCast#1567]
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "opam init -a --disable-sandboxing --bare && opam switch create 4.05.0", "delta": "0:00:00.177861", "end": "2019-05-21 06:46:18.686808", "msg": "non-zero return code", "rc": 2, "start": "2019-05-21 06:46:18.508947", "stderr": "[NOTE] Make sure that ~/.profile is well sourced in your ~/.bashrc.\n\n[ERROR] Could not write /home/dev/.opam/opam-init/init.sh\n[ERROR] Could not write /home/dev/.opam/opam-init/init.zsh\n[ERROR] Could not write /home/dev/.opam/opam-init/init.csh\n[ERROR] Could not write /home/dev/.opam/opam-init/init.fish\n[ERROR] Could not write /home/dev/.opam/opam-init/complete.sh\n[ERROR] Could not write /home/dev/.opam/opam-init/complete.zsh\n[ERROR] Could not write /home/dev/.opam/opam-init/env_hook.sh\n[ERROR] Could not write /home/dev/.opam/opam-init/env_hook.zsh\n[ERROR] Could not write /home/dev/.opam/opam-init/env_hook.csh\n[ERROR] Could not write /home/dev/.opam/opam-init/env_hook.fish\n[ERROR] There already is an installed switch named 4.05.0", "stderr_lines": ["[NOTE] Make sure that ~/.profile is well sourced in your ~/.bashrc.", "", "[ERROR] Could not write /home/dev/.opam/opam-init/init.sh", "[ERROR] Could not write /home/dev/.opam/opam-init/init.zsh", "[ERROR] Could not write /home/dev/.opam/opam-init/init.csh", "[ERROR] Could not write /home/dev/.opam/opam-init/init.fish", "[ERROR] Could not write /home/dev/.opam/opam-init/complete.sh", "[ERROR] Could not write /home/dev/.opam/opam-init/complete.zsh", "[ERROR] Could not write /home/dev/.opam/opam-init/env_hook.sh", "[ERROR] Could not write /home/dev/.opam/opam-init/env_hook.zsh", "[ERROR] Could not write /home/dev/.opam/opam-init/env_hook.csh", "[ERROR] Could not write /home/dev/.opam/opam-init/env_hook.fish", "[ERROR] There already is an installed switch named 4.05.0"], "stdout": "\nUser configuration:\n  ~/.profile is already up-to-date.", "stdout_lines": ["", "User configuration:", "  ~/.profile is already up-to-date."]}

Docker: No
OS: Ubuntu 16.04

trying to use install.sh as i don't want the docker

Edit: i also tried opam init -a --disable-sandboxing --bare && opam switch create 4.05.0 it worked but still get the issue

**Comment by Vaalyn** [comment]
As of version [0.9.5](https://github.com/AzuraCast/AzuraCast/releases/tag/0.9.5) we are not supporting new installations via Ansible anymore. See this part of the release notes:

> As of this release, we are no longer supporting new installations via the Ansible ("Traditional" or "Bare-metal") installation type. These installation types have represented a disproportionate amount of support issues, and have put a very heavy toll on our volunteer support team, so we have removed the Ansible installation instructions from our homepage completely. We will continue to distribute updates to existing users, and we will make our best efforts to continue feature parity between both installation types.

I'd recommend you to switch to Docker. If you have any problems with the Docker installer please let us know.
