### ISSUE TITLE
Listerners charts not working

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#157]
Hello,

After the latest major update both listener charts on the  main dashboard is not working anymore.
Please have a look.

**Comment by SlvrEagle23** [comment]
@surihost I've pushed some fixes up to some JavaScript issues in the latest few updates...pull down the newest code and be sure to refresh your cache by shift+refreshing, and that should fix it.

**Comment by surihost** [comment]
Just updated it, now another problem is there.
The live listener trough google map is not working anymore.
On evry station i see i have to enter google maps api key again, while this was already done in the system settings.I did put the api key again but still  live listener stats on google maps not working on any of the stations.

**Comment by SlvrEagle23** [comment]
@surihost The latest update changes the order of the scripts...try it now!

**Comment by surihost** [comment]
Ok i updated again, and its working now,but before loading the google maps i see the the page of entering the google api key showing first.This was not happening in the earlier versions?

**Comment by SlvrEagle23** [comment]
@surihost This shouldn't be happening as of the latest fix, which just removes that section if the API key is supplied.

**Comment by surihost** [comment]
Hello,

I just updated azuracast and see that live listener stats not working anymore all od then showing 0, also the now playing status is not working keep showing " Song Title  Song Artist"
Please have a look what happend

**Comment by surihost** [comment]
in the station/reports/listeners it shows the ip's of the listener, but not on the google map,and as said before on the dashboard  station overview evry station is showing 0 listener.
