### ISSUE TITLE
Cannot enable the SSL via docker

### ISSUE THREAD

**Issue by jokic33** [AzuraCast/AzuraCast#1572]
**Using Docker installation method** YES

**Host Operating System** Linux

**Describe the bug** Domain name xxx is not set up with LetsEncrypt yet. Reverting to self-signed cert...

**To Reproduce**

**Expected behavior** I tried to install Let's Encrypt from docker
./docker.sh letsencrypt-create mydomain.example.com (with my domain), and i received error..here i have to note that i have changed the ports to 8999 and 444..what i have to do?

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  Desktop
 - OS:  Ubuntu
 - Browser:  chrome
 - Version:  18.04
![Screenshot](https://user-images.githubusercontent.com/47450717/58259404-1c424580-7d7d-11e9-995c-2b8481f8d07b.png)

**Additional context**

**Comment by dreinn** [comment]
you absolutely must use port 443 for letsencrypt.
Other ports don't work.

**Comment by jokic33** [comment]
if i change the port to 443 from the .env file i take an error that it's already in use..for this reason i changed to 444 and it works..

**Comment by dreinn** [comment]
yes, 443 is in use by your proxy or webserver.
I have found a stupid solution that works:
- use port 443 with azuracast;
- disable temporarily apache/nginx on my server;
- obtain the certificate with azuracast with the command you typed above;
- rechange port to 444 in Azura;
- Run my normal nginx/apache;
- run azura on port 444.

The downside of this procedure is that every 3 months you must renew the certificate, so you should repeat the procedure, but it is 4 times a year!

**Comment by jokic33** [comment]
i just did that and the installation of ssl completed successfully...but again in admin area when i submit https:// i receive error page..do you know why?

**Comment by jokic33** [comment]
everything is working great..thanks
