### ISSUE TITLE
Twitter Webhook on scheduled playlist display always same song as upcoming

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#1575]
When a scheduled playlist ist running, azuracast display always the same song as upcoming
from the NEXT playlist and not from the current playlist.
I checked the now playing API , displaying the same.
Example: Iggy is the first song of the next playlist

> Song: Chun Swae (feat. Swae Lee) by: Nicki Minaj Album: Queen Playlist: The Babylon Sisters Next: Boom Boom by: Iggy Azalea  Album: Digital Distortion
> 
> Song: La Modelo (feat. Cardi B) by: Ozuna Album: Essentials Playlist: The Babylon Sisters Next: Boom Boom by: Iggy Azalea  Album: Digital Distortion 
> 
> Song: Hard White by: Nicki Minaj Album: Queen Playlist: The Babylon Sisters Next: Boom Boom by: Iggy Azalea  Album: Digital Distortion 
> 
> Song: Realer by: Megan Thee Stallion Album: Fever Playlist: The Babylon Sisters Next: Boom Boom by: Iggy Azalea  Album: Digital Distortion

**Comment by macbroadcast** [comment]
@SlvrEagle23 This is really bothering me, are there any plans to have a look into this?

**Comment by SlvrEagle23** [comment]
@macbroadcast In order to fix some issues we've been having with the AzuraCast AutoDJ, we've temporarily disabled the "next song" functionality, which means it will likely always currently be returning "null". This is a known issue and at the moment there's nothing we can do to resolve it.

**Comment by macbroadcast** [comment]
@SlvrEagle23 ok, good to know that you are aware of this, thanks for the info :smile:

**Comment by Vaalyn** [comment]
I'll close this issue as this is due to an issue we have with Liquidsoap. As soon as we are able to resolve the problem we have with the "next song" functionality the WebHook should also get the correct data again.
