### ISSUE TITLE
Cannot delete a directory

### ISSUE THREAD

**Issue by jokic33** [AzuraCast/AzuraCast#1576]
**Using Docker installation method** Yes

**Host Operating System** Linux

**Describe the bug** Directory cannot be deleted on a music file

**To Reproduce**

**Expected behavior** Delete the directory

**Relevant Logs**

**Screenshots**

**Device(s):** 
 - Device: Desktop
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
Please be more specific with your issue description, include some logs, look into the browser console for any errors and post all of that here.
