### ISSUE TITLE
Custom range calendar option starts at year 1970 without the option to change the year.

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#1578]
**Using Docker installation method**
Yes

**Host Operating System**
uBuntu 18

**Describe the bug**
Custom range calendar option starts at year 1970 without the option to change the year (I click the year but nothing happens). Literally, you have to click the forward icon only.

**To Reproduce**
1. Go to listeners tab
2. Click on custom range
3. No option to change the year faster

**Expected behavior**
When year is click. it should have an option for years only. Expecting a faster year option choice in custom range for listeners.

**Screenshots**

**Device(s):**
 - Device: Mac 
 - OS: Sierra
 - Browser: Safari and Firefox

**Comment by Vaalyn** [comment]
Can confirm this. We should default that selection window to the current year / month and make it possible to quickly select a different year.

**Comment by Vaalyn** [comment]
From the documentation of the daterangepicker component we should add this to the initialization config:
```
`showDropdowns`: (true/false)
Show year and month select boxes above calendars to jump to a specific month and year.
```

**Comment by SlvrEagle23** [comment]
@ErnestPH I've made some changes to both how "Live Listeners" is handled by the dropdowns (it'll list as tomorrow, not 1970, so you'll be much closer to current date in the selector), and also enabled the year dropdowns and set a min/max to 2016-current year.
