### ISSUE TITLE
Listener Map overlays navigation dropdown

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#1579]
It seems fixed when adding  `z-index:0;`  in id="map" in-line style

[https://prnt.sc/nsrpkr](https://prnt.sc/nsrpkr)

**Comment by Vaalyn** [comment]
Can confirm this happening on all Mac browsers and also on Windows. This seems to be a general problem.

**Comment by SlvrEagle23** [comment]
@ErnestPH Confirmed that just setting the z-index fixes it. Updated the code accordingly.
