### ISSUE TITLE
Now playing, coming next,  and played songs...

### ISSUE THREAD

**Issue by rolradio** [AzuraCast/AzuraCast#158]
Would it 
![now playing](https://user-images.githubusercontent.com/28436289/27014034-77560730-4ef0-11e7-833a-15eba6ec53a9.png)
be possible to create an enbeded code to display a list of the currently playing song and a history of, for example, 5 or 10 songs.
This to be used as a code for an external website.
Then make it visible on the azuracast profile page.

It would also be nice if a song is on request, that this is also mentioned after the song played.

For example: the dexis - live is live (Requested)

**Comment by nsystem1** [comment]
I believe most of your requests are already available, but improvement is always welcome

**Comment by rolradio** [comment]
Indeed, the data can be seen on the public page.
But I would like to put this information on my extrene webpage.
I can not find how I can do this.
Therefore, it would be useful to show the Play or History list as Embed Code just like the Player Embed Code and Request Embed Code.

![embeded](https://user-images.githubusercontent.com/28436289/27027153-91d117f6-4f60-11e7-8c06-659c1d0d0011.png)

**Comment by nsystem1** [comment]
You can get the play history from http://**your-ip**/api/nowplaying/**request-station**

**Comment by rolradio** [comment]
Sorry, That is Chinese for me.
Is there an example?
Where can I find more explanation?

**Comment by SlvrEagle23** [comment]
@rolradio The API docs now live at http://azuracast.com/api/

While most of the items you mention are already covered in the API, I am working on enhancing the API's response to include such things as:

* Next playing song (if known)
* Duration of the current song, seconds already played and seconds remaining
* If the song was requested

**Comment by rolradio** [comment]
Thanks for now. 
I take a look for API.

**Comment by rolradio** [comment]
Can anyone give me an example of a nowplaying API.
Unfortunately, I do not know how to use this information to put on a website, for example.
I've been trying for a few days, but I do not know where to start.
I would like to have an example of a working radio.
Thanks in advance.

**Comment by radiowestcz** [comment]
Hello, I have issue with script.
why do not function view next played song in script? On my website radiobrooklin.tk I was using this function for my listeners.

**Comment by SlvrEagle23** [comment]
@rolradio This is a known issue. We are working on a possible solution, but it could be that infrastructural changes will prevent us from showing the next song in future versions.
