### ISSUE TITLE
Azuracast jingle

### ISSUE THREAD

**Issue by ValentinOgier** [AzuraCast/AzuraCast#1580]
**Using Docker installation method**

Yes

**Host Operating System**

Ubuntu 16.04

**Describe the bug**

Azuracast jingle when we click too often on "Skip song"

**To Reproduce**

Go to the profile page, click "skip song" button 2 times with 10s interval, listen the azuracast jingle.
**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
Duplicate of #1527 as the underlying root cause is most likely the same. Please follow that issue.
