### ISSUE TITLE
Private Station

### ISSUE THREAD

**Issue by bayubad** [AzuraCast/AzuraCast#1581]
How can I create Private Station?

**Comment by Vaalyn** [comment]
@bayubad What exactly do you mean, could you describe what a Private Station means in terms of for whom and what exactly is private?

**Comment by ErnestPH** [comment]
I would assume you are talking about creating a station. Here's a video tutorial for it - https://www.youtube.com/watch?v=VLdl2BsekZM

> How can I create Private Station?

I would assume that you are talking about creation a station. If that's the case, here's a video about it, https://www.youtube.com/watch?v=VLdl2BsekZM

**Comment by bayubad** [comment]
I am thinking of creating a restricted station where listeners should login in order to listen to the content.

**Comment by SlvrEagle23** [comment]
@bayubad While this is possible with Icecast itself, it isn't entirely simple to set up and it's not something we support directly in AzuraCast. You could always submit it as a [feature request](https://features.azuracast.com/), but it's currently not a high priority, as most radio is intended for public broadcast. You can disable public pages on any station by editing the station's profile and modifying the "public pages" setting.
