### ISSUE TITLE
Remove volume bottom

### ISSUE THREAD

**Issue by bayubad** [AzuraCast/AzuraCast#1582]
How can I remove volume bottom from default player?

**Comment by Vaalyn** [comment]
The easiest way would be to hide the button via Custom CSS for Public Pages with `display: none;` on the volume element.

**Comment by ErnestPH** [comment]
> How can I remove volume bottom from default player?

Go to custom branding and add this line…

.radio-player-widget i.material-icons {
    display: none;
}

**Comment by bayubad** [comment]
Is there a complete help for Custom Branding (station public pages and login page)?

**Comment by Vaalyn** [comment]
@bayubad If you mean an in-depth tutorial about how to style specific elements of AzuraCast with custom CSS, then no we do not have something like this and I think at the moment there is no priority for us to add that. Custom Branding in AzuraCast is just normal CSS and JS that can be added in that section and if you don't know the class or id of an element it is easy to find it out with the browsers dev tools.

I'll close this issue now as the original question has been answered.
