### ISSUE TITLE
Relaying Another Stream

### ISSUE THREAD

**Issue by bayubad** [AzuraCast/AzuraCast#1586]
While using Remote URL Playlist (Remote URL type: Direct Stream URL), the whole stream is stored on the server and uses huge space on disk.
Any solution to just rebroadcast the direct stream without storing it?

**Comment by bayubad** [comment]
What I need to do is Relaying Another Stream.
By relaying another stream, I am using a remote streaming server as the source for my broadcast, and rebroadcasting that server's stream as my own.

**Comment by SlvrEagle23** [comment]
@bayubad If you're _just_ relaying a remote stream through AzuraCast, you can also do this from the frontend Mount Point, just set the "relay URL" on the mount point to the remote stream URL and it will automatically relay it, without needing Liquidsoap involved in the process at all.

**Comment by bayubad** [comment]
I want to receive the stream on my server and then rebroadcast the stream and not directly rebroadcast the remote stream to listeners.

**Comment by SlvrEagle23** [comment]
@bayubad That's fine, but it's by design that Liquidsoap saves a copy of that stream locally, which can eventually fill up your server if it's a constant ongoing stream that you don't interrupt with other content. This would likely be a question for the `savonet/liquidsoap` repository folks.

**Comment by bayubad** [comment]
Yes, with this method the stream fills up my server very soon.
Is there any solution to only allocate xGB of space for storing the stream and after reaching the threshold to overwrite it?

**Comment by SlvrEagle23** [comment]
@bayubad Again, that's a question for the Liquidsoap team, as your issue is with Liquidsoap, not with how AzuraCast is interacting with Liquidsoap.

**Comment by bayubad** [comment]
I have raised a question to Liquidsoap team on https://github.com/savonet/liquidsoap/issues/797

**Comment by bayubad** [comment]
Replied by: @smimram

I don't think that Liquidsoap stores a significant portion of an http stream by default. Could you share more of your script? Do you have something quite different from something like

output.icecast(input.http(...))
?

@SlvrEagle23 @Vaalyn

**Comment by Vaalyn** [comment]
@bayubad Please copy your Liquidsoap config and post it on the issue in the Liquidsoap repository. Remember to anonymize anything that should not be public from it.

**Comment by bayubad** [comment]
Where can I find my Liquidsoap config?

**Comment by Vaalyn** [comment]
`Utilities` -> `Log Viewer`

**Comment by bayubad** [comment]
# WARNING! This file is automatically generated by AzuraCast.
# Do not update it directly!


set("init.daemon", false)
set("init.daemon.pidfile.path","/var/azuracast/stations/test/config/liquidsoap.pid")
set("log.stdout", true)
set("log.file", false)
set("server.telnet",true)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port", 8004)
set("harbor.bind_addrs",["0.0.0.0"])

set("tag.encodings",["UTF-8","ISO-8859-1"])
set("encoder.encoder.export",["artist","title","album","song"])

setenv("TZ", "Asia/Dubai")

# AutoDJ Next Song Script
def azuracast_next_song() =
  uri = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/nextsong --form api_auth="^quote("90536a2be08d7ebece745a3fd152f816b8e9b3d3c7f205bc11e79eb63bfe4b2b2761eb765aeae25df39e1535ddf6e0371a23")^""), default="")
  log("AzuraCast Raw Response: #{uri}")
  
  if uri == "" or string.match(pattern="Error", uri) then
    log("AzuraCast Error: Delaying subsequent requests...")
    system("sleep 5")
    request.create("")
  else
    request.create(uri)
  end
end

playlist_default = audio_to_stereo(playlist(id="playlist_default",mode="randomize",reload_mode="watch","/var/azuracast/stations/test/playlists/playlist_default.m3u"))
playlist_default = cue_cut(id="music_playlist_default_cue", playlist_default)

# Standard Playlists
radio = random(weights=[3], [playlist_default])

dynamic = audio_to_stereo(request.dynamic(id="music_next_song", timeout=20., azuracast_next_song))
dynamic = cue_cut(id="music_cue_cut", dynamic)

error_song = sequence([blank(duration=5.), single("/usr/local/share/icecast/web/error.mp3")])
requests = audio_to_stereo(request.queue(id="music_requests"))
radio = fallback(id="music_autodj_fallback", track_sensitive = true, [requests, dynamic, radio, error_song])

# Handle Jingle Mode
def handle_jingle_mode(m) =
  if (m["jingle_mode"] == "true") then
    log("Jingle mode; stripping metadata...")
    []
  else
    m
  end
end
radio = map_metadata(handle_jingle_mode,update=false,strip=true,insert_missing=false,radio)

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

# Apply amplification metadata (if supplied)
radio = amplify(1., radio)

radio = crossfade(start_next=1.50,fade_out=1.,fade_in=1.,radio)

# Send metadata changes back to AzuraCast
def metadata_updated(m) =
  if (m["song_id"] != "") then
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/feedback --form song="^quote(m["song_id"])^" --form media="^quote(m["media_id"])^" --form playlist="^quote(m["playlist_id"])^" --form api_auth="^quote("90536a2be08d7ebece745a3fd152f816b8e9b3d3c7f205bc11e79eb63bfe4b2b2761eb765aeae25df39e1535ddf6e0371a23")^""), default="")
    log("AzuraCast Feedback Response: #{ret}")
  end
end

radio = on_metadata(metadata_updated,radio)

# Local Broadcasts
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), id="music_local_1", host = "127.0.0.1", port = 8000, password = "6Pk2fRzR", mount = "/radio.mp3", name = "Test", description = "Test", genre = "Test", url = "https://domain.com", public = false, encoding = "UTF-8", radio)

# Remote Relays

**Comment by bayubad** [comment]
# WARNING! This file is automatically generated by AzuraCast.
# Do not update it directly!


set("init.daemon", false)
set("init.daemon.pidfile.path","/var/azuracast/stations/radio/config/liquidsoap.pid")
set("log.stdout", true)
set("log.file", false)
set("server.telnet",true)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port", 8044)
set("harbor.bind_addrs",["0.0.0.0"])

set("tag.encodings",["UTF-8","ISO-8859-1"])
set("encoder.encoder.export",["artist","title","album","song"])

setenv("TZ", "Asia/Tehran")

# AutoDJ Next Song Script
def azuracast_next_song() =
  uri = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/8/nextsong --form api_auth="^quote("a3a3306abe5342ad6b6aa71952ea0a43efffb1711103daecd0f25b28b33702e74b845097743106823eca960e74ac3e1a15e8")^""), default="")
  log("AzuraCast Raw Response: #{uri}")
  
  if uri == "" or string.match(pattern="Error", uri) then
    log("AzuraCast Error: Delaying subsequent requests...")
    system("sleep 5")
    request.create("")
  else
    request.create(uri)
  end
end

playlist_default = audio_to_stereo(mksafe(input.http(max=10., "http://stream.domain.com")))

# Standard Playlists
radio = random(weights=[3], [playlist_default])

dynamic = audio_to_stereo(request.dynamic(id="radio_next_song", timeout=20., azuracast_next_song))
dynamic = cue_cut(id="radio_cue_cut", dynamic)

error_song = sequence([blank(duration=5.), single("/usr/local/share/icecast/web/error.mp3")])
requests = audio_to_stereo(request.queue(id="radio_requests"))
radio = fallback(id="radio_autodj_fallback", track_sensitive = true, [requests, dynamic, radio, error_song])

# Handle Jingle Mode
def handle_jingle_mode(m) =
  if (m["jingle_mode"] == "true") then
    log("Jingle mode; stripping metadata...")
    []
  else
    m
  end
end
radio = map_metadata(handle_jingle_mode,update=false,strip=true,insert_missing=false,radio)

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

# Apply amplification metadata (if supplied)
radio = amplify(1., radio)

# Send metadata changes back to AzuraCast
def metadata_updated(m) =
  if (m["song_id"] != "") then
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/8/feedback --form song="^quote(m["song_id"])^" --form media="^quote(m["media_id"])^" --form playlist="^quote(m["playlist_id"])^" --form api_auth="^quote("06823eca960ec3e1a15e8")^""), default="")
    log("AzuraCast Feedback Response: #{ret}")
  end
end

radio = on_metadata(metadata_updated,radio)

# Local Broadcasts
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), id="radio_local_1", host = "127.0.0.1", port = 8040, password = "test", mount = "/radio.mp3", name = "Radio", description = "Radio", genre = "Test", url = "https://domain.com", public = false, encoding = "UTF-8", radio)

# Remote Relays

**Comment by bayubad** [comment]
# WARNING! This file is automatically generated by AzuraCast.
# Do not update it directly!


set("init.daemon", false)
set("init.daemon.pidfile.path","/var/azuracast/stations/radio/config/liquidsoap.pid")
set("log.stdout", true)
set("log.file", false)
set("server.telnet",true)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port", 8044)
set("harbor.bind_addrs",["0.0.0.0"])

set("tag.encodings",["UTF-8","ISO-8859-1"])
set("encoder.encoder.export",["artist","title","album","song"])

setenv("TZ", "Europe")

# AutoDJ Next Song Script
def azuracast_next_song() =
  uri = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/8/nextsong --form api_auth="^quote("a3a3306abe5342ad6b6aa71952ea0a43efffb1711103daecd0f25b28b33702e74b845097743106823eca960e74ac3e1a15e8")^""), default="")
  log("AzuraCast Raw Response: #{uri}")
  
  if uri == "" or string.match(pattern="Error", uri) then
    log("AzuraCast Error: Delaying subsequent requests...")
    system("sleep 5")
    request.create("")
  else
    request.create(uri)
  end
end

playlist_default = audio_to_stereo(mksafe(input.http(max=10., "http://stream.domain.com")))

# Standard Playlists
radio = random(weights=[3], [playlist_default])

dynamic = audio_to_stereo(request.dynamic(id="radio_next_song", timeout=20., azuracast_next_song))
dynamic = cue_cut(id="radio_cue_cut", dynamic)

error_song = sequence([blank(duration=5.), single("/usr/local/share/icecast/web/error.mp3")])
requests = audio_to_stereo(request.queue(id="radio_requests"))
radio = fallback(id="radio_autodj_fallback", track_sensitive = true, [requests, dynamic, radio, error_song])

# Handle Jingle Mode
def handle_jingle_mode(m) =
  if (m["jingle_mode"] == "true") then
    log("Jingle mode; stripping metadata...")
    []
  else
    m
  end
end
radio = map_metadata(handle_jingle_mode,update=false,strip=true,insert_missing=false,radio)

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

# Apply amplification metadata (if supplied)
radio = amplify(1., radio)

# Send metadata changes back to AzuraCast
def metadata_updated(m) =
  if (m["song_id"] != "") then
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/8/feedback --form song="^quote(m["song_id"])^" --form media="^quote(m["media_id"])^" --form playlist="^quote(m["playlist_id"])^" --form api_auth="^quote("06823eca960ec3e1a15e8")^""), default="")
    log("AzuraCast Feedback Response: #{ret}")
  end
end

radio = on_metadata(metadata_updated,radio)

# Local Broadcasts
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), id="radio_local_1", host = "127.0.0.1", port = 8040, password = "test", mount = "/radio.mp3", name = "Radio", description = "Radio", genre = "Test", url = "https://domain.com", public = false, encoding = "UTF-8", radio)

# Remote Relays

**Comment by bayubad** [comment]
# WARNING! This file is automatically generated by AzuraCast.
# Do not update it directly!


set("init.daemon", false)
set("init.daemon.pidfile.path","/var/azuracast/stations/radio/config/liquidsoap.pid")
set("log.stdout", true)
set("log.file", false)
set("server.telnet",true)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port", 8044)
set("harbor.bind_addrs",["0.0.0.0"])

set("tag.encodings",["UTF-8","ISO-8859-1"])
set("encoder.encoder.export",["artist","title","album","song"])

setenv("TZ", "Europe")

# AutoDJ Next Song Script
def azuracast_next_song() =
  uri = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/8/nextsong --form api_auth="^quote("TEST")^""), default="")
  log("AzuraCast Raw Response: #{uri}")
  
  if uri == "" or string.match(pattern="Error", uri) then
    log("AzuraCast Error: Delaying subsequent requests...")
    system("sleep 5")
    request.create("")
  else
    request.create(uri)
  end
end

playlist_default = audio_to_stereo(mksafe(input.http(max=10., "http://stream.domain.com")))

# Standard Playlists
radio = random(weights=[3], [playlist_default])

dynamic = audio_to_stereo(request.dynamic(id="radio_next_song", timeout=20., azuracast_next_song))
dynamic = cue_cut(id="radio_cue_cut", dynamic)

error_song = sequence([blank(duration=5.), single("/usr/local/share/icecast/web/error.mp3")])
requests = audio_to_stereo(request.queue(id="radio_requests"))
radio = fallback(id="radio_autodj_fallback", track_sensitive = true, [requests, dynamic, radio, error_song])

# Handle Jingle Mode
def handle_jingle_mode(m) =
  if (m["jingle_mode"] == "true") then
    log("Jingle mode; stripping metadata...")
    []
  else
    m
  end
end
radio = map_metadata(handle_jingle_mode,update=false,strip=true,insert_missing=false,radio)

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

# Apply amplification metadata (if supplied)
radio = amplify(1., radio)

# Send metadata changes back to AzuraCast
def metadata_updated(m) =
  if (m["song_id"] != "") then
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/8/feedback --form song="^quote(m["song_id"])^" --form media="^quote(m["media_id"])^" --form playlist="^quote(m["playlist_id"])^" --form api_auth="^quote("TEST")^""), default="")
    log("AzuraCast Feedback Response: #{ret}")
  end
end

radio = on_metadata(metadata_updated,radio)

# Local Broadcasts
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), id="radio_local_1", host = "127.0.0.1", port = 8040, password = "test", mount = "/radio.mp3", name = "Radio", description = "Radio", genre = "Test", url = "https://domain.com", public = false, encoding = "UTF-8", radio)

# Remote Relays

**Comment by Vaalyn** [comment]
@bayubad Please use the `embed code` feature of GitHub when posting the content of these files (I edited your post as you can see)

Also you are supposed to post that file to the other issue on the Liquidsoap repository, not here.

**Comment by bayubad** [comment]
@Vaalyn I believe there is a misconfiguration with Liquidsoap in AzuraCast.
I just need to receive the stream from a remote server (i.e. https://stream.domain.com:8000) and re-broadcast the same stream from my server as it's my own stream.

**Comment by Vaalyn** [comment]
@bayubad You do not need to tell us this again, you already created this issue with the same information.

When the guys from LS ask for some piece of information, post it to the issue on **their** repository, not here and also please don't post it 4 times in a row just to delete it again 3 times. We get notifications for these things and it's really annoying to get them without a reason.

Make sure to read what we write and do more than just the bare minimum when answering us. We frankly do not have the resources to unnecessary hold hands for filling out issues / providing information to us. If it gets too much we may temporarily block users for disregarding what we write.
