### ISSUE TITLE
Translation into Czech

### ISSUE THREAD

**Issue by davchy** [AzuraCast/AzuraCast#1589]
Hello,
a week ago I joined Crowdin on AzuraCast and offered a translation into Czech. I haven't received an answer yet.

Regards,
David

**Comment by SlvrEagle23** [comment]
@davchy Thank you for offering to translate AzuraCast, and we apologize for the lack of response. I got your messages, but I've been a bit busy with other projects in the last few days (namely the new backup service) and haven't been able to answer translation questions.

In the case of the Czech language, I'm not sure that there are enough users out there who would be native speakers of that language (and _only_ that language, not any of our other localized languages) to support an official translation option for the language.

**Comment by davchy** [comment]
Well, is there any other way to translate at least a public page? So locate the player and the song request form?
The language skills of the population of the Czech Republic are relatively low. Only the next generation can speak English.

**Comment by davchy** [comment]
@SlvrEagle23  I use Poedit editor and I could keep my local translation. But the structure of compiled language files in the resources/locale/compiled directory is special. So it seems that creating a new language cannot be without a Crowdin platform. It is so?

**Comment by SlvrEagle23** [comment]
@davchy If you run the command `./docker.sh cli locale:generate` (or, on Ansible installations, `/var/azuracast/www/bin/azuracast locale:generate`) that will convert the locale file into the PHP file the application needs.

**Comment by davchy** [comment]
@SlvrEagle23 
1. I took the AzuraCast-master/resources/locale/default.pot file
2. In the Poedit editor, I created a translation file for cs_CZ
3. I translated some strings and saved the translation into the default.po file
4. I switched to the container terminal `./docker.sh bash` and created a directory resources/locale/cs_CZ.UTF-8 and inside it the LC_MESSAGES directory. I uploaded a file with the Czech translation default.po to LC_MESSAGES. `curl -L https://www.catplanet.eu/default.po > default.po`
5. After leaving the container terminal, I entered `./docker.sh cli locale: generate`. The result was a "Locales generated."

After this procedure, I expected to create a compiled cs_CZ.UTF-8.php file in the resources/locale/compiled directory, but it didn't.
What am I doing wrong? Thanks

P.S .: In desperation I tried and all relevant files and directories of translation (source and destination) set to chmod 777 - without effect.

**Comment by SlvrEagle23** [comment]
@davchy I apologize, I missed one section that must be changed in order to add a new locale:

https://github.com/AzuraCast/AzuraCast/blob/master/config/settings.php#L17-L32

Add the locale to that list, and then `locale:generate` will include it and it will be selectable in profiles.

**Comment by davchy** [comment]
@SlvrEagle23 Now I have a choice of Czech language in the administration, but the translated strings are still in English. Generation was done, but cs_CZ.UTF-8.php was not created in resources/locale/compiled.
Can you please check my process described above, if I do everything right?

**Comment by SlvrEagle23** [comment]
@davchy Oh, I missed a detail...you shouldn't be editing `default.pot`, you should be creating a `.mo` file inside another directory specific to the locale, in the same way that the existing locales are.

Using POEdit, you can do this from the File menu, using the "Compile to MO" command. Drop the resulting file into a folder named `cs_CZ.UTF-8` in the locales folder.

You may also need to flush your cache to apply the changes, which can be done via `./docker.sh cli cache:clear`.

**Comment by davchy** [comment]
@SlvrEagle23 I followed exactly as you wrote, but without a positive result.
Please, can you really not include the Czech language in the official crowdin translations? I will also give you some gift. In addition, I would like to offer AzuraCast as a "reseller" in the Czech Republic. This would mean profit for you. Unfortunately, I cannot translate this, because, as I wrote, Czechs do not have a great knowledge of foreign languages.

**Comment by SlvrEagle23** [comment]
@davchy Added as a supported language on CrowdIn. I don't want you to have to encounter any further trouble! :)

**Comment by davchy** [comment]
@SlvrEagle23  I will be very grateful for your thoughtfulness :)

**Comment by Vaalyn** [comment]
Closing as resolved.
