### ISSUE TITLE
new installations failing

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#159]
Hello,

New installations are failing at liquid soap section.Please check and fix it:

TASK [azuracast-radio : Install LiquidSoap Dependencies] ***********************
failed: [localhost] (item=[u'libpcre3-dev', u'libfdk-aac-dev', u'libmad0-dev', u'libmp3lame-dev', u'libtag1-dev', u'libfaad-dev', u'libflac-dev', u'pkg-config', u'm4']) => {"failed": true, "item": ["libpcre3-dev", "libfdk-aac-dev", "libmad0-dev", "libmp3lame-dev", "libtag1-dev", "libfaad-dev", "libflac-dev", "pkg-config", "m4"], "msg": "No package matching 'libfdk-aac-dev' is available"}
        to retry, use: --limit @/var/azuracast/www/util/ansible/update.retry

**Comment by nsystem1** [comment]
Try `sudo apt-add-repository multiverse && sudo apt-get update` then retry `sudo ./install.sh`

**Comment by surihost** [comment]
I did it.now getting this errors:

TASK [supervisord : Kill legacy radio processes (if upgrading from older version        )] ***
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "killall -q -9 icecast2         sc_serv liquidsoap", "failed": true, "msg": "[Errno 2] No such file or director        y", "rc": 2}
...ignoring


TASK [influxdb : Create 'stations' database] ***********************************
changed: [localhost] => (item=stations)

TASK [influxdb : Create 'stations' retention policies] *************************
changed: [localhost] => (item={u'duration': u'5d', u'default': True, u'name': u'        15s'})
changed: [localhost] => (item={u'duration': u'2w', u'default': False, u'name': u        '1h'})
changed: [localhost] => (item={u'duration': u'INF', u'default': False, u'name':         u'1d'})

TASK [influxdb : Manage continuous queries on 'stations'] **********************
 [WARNING]: Module did not set no_log for login_password

changed: [localhost]

TASK [influxdb : Lock down InfluxDB to localhost requests] *********************
ERROR! The requested handler 'restart influxdb' was not found in either the main         handlers list nor in the listening handlers list

**Comment by nsystem1** [comment]
Try `sudo service apache2 stop` then retry `sudo ./install.sh`

**Comment by surihost** [comment]
Getting this:

Failed to stop apache2.service: Unit apache2.service not loaded.

**Comment by SlvrEagle23** [comment]
@surihost This is a legitimate issue and I need to push up an update relating to it. Standby.

**Comment by surihost** [comment]
Ok, thnx :)
Dont forget to include the arm version also in it.

**Comment by SlvrEagle23** [comment]
@surihost Try it now.

**Comment by linksilver** [comment]
hello !
i got :
`ERROR! 'update_cache' is not a valid attribute for a Task

The error appears to have been in '/var/azuracast/www/util/ansible/roles/init/tasks/main.yml': line 9, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


  - name: Add multiverse repository
    ^ here
`

**Comment by SlvrEagle23** [comment]
@linksilver Ah, my mistake. Try again :)

**Comment by linksilver** [comment]
it seems to work :)
thank you !

**Comment by surihost** [comment]
Should i run  sudo ./install.sh

or updates command?

**Comment by SlvrEagle23** [comment]
@surihost If the previous installation didn't complete, just run ./install.sh again

**Comment by surihost** [comment]
I am getting this error now on scaleway arm 64 bit sever:

TASK [init : Add multiverse repository] ****************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: E:Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/multiverse/binary-arm64/Packages  404  Not Found [IP: 91.189.88.161 80], E:Some index files failed to download. They have been ignored, or old ones used instead.
failed: [localhost] (item=deb http://archive.ubuntu.com/ubuntu xenial multiverse) => {"failed": true, "item": "deb http://archive.ubuntu.com/ubuntu xenial multiverse", "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_xAJc2M/ansible_module_apt_repository.py\", line 565, in <module>\n    main()\n  File \"/tmp/ansible_xAJc2M/ansible_module_apt_repository.py\", line 553, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 454, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: E:Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/multiverse/binary-arm64/Packages  404  Not Found [IP: 91.189.88.161 80], E:Some index files failed to download. They have been ignored, or old ones used instead.\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: E:Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/multiverse/binary-arm64/Packages  404  Not Found [IP: 91.189.88.152 80], E:Some index files failed to download. They have been ignored, or old ones used instead.
failed: [localhost] (item=deb-src http://archive.ubuntu.com/ubuntu/  xenial multiverse) => {"failed": true, "item": "deb-src http://archive.ubuntu.com/ubuntu/  xenial multiverse", "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_KJMc8Z/ansible_module_apt_repository.py\", line 565, in <module>\n    main()\n  File \"/tmp/ansible_KJMc8Z/ansible_module_apt_repository.py\", line 553, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 454, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: E:Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/multiverse/binary-arm64/Packages  404  Not Found [IP: 91.189.88.152 80], E:Some index files failed to download. They have been ignored, or old ones used instead.\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: E:Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/multiverse/binary-arm64/Packages  404  Not Found [IP: 91.189.88.152 80], E:Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/multiverse/binary-arm64/Packages  404  Not Found [IP: 91.189.88.152 80], E:Some index files failed to download. They have been ignored, or old ones used instead.
failed: [localhost] (item=deb http://archive.ubuntu.com/ubuntu xenial-updates multiverse) => {"failed": true, "item": "deb http://archive.ubuntu.com/ubuntu xenial-updates multiverse", "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_XdB2Sr/ansible_module_apt_repository.py\", line 565, in <module>\n    main()\n  File \"/tmp/ansible_XdB2Sr/ansible_module_apt_repository.py\", line 553, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 454, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: E:Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/multiverse/binary-arm64/Packages  404  Not Found [IP: 91.189.88.152 80], E:Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/multiverse/binary-arm64/Packages  404  Not Found [IP: 91.189.88.152 80], E:Some index files failed to download. They have been ignored, or old ones used instead.\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: E:Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/multiverse/binary-arm64/Packages  404  Not Found [IP: 91.189.88.161 80], E:Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/multiverse/binary-arm64/Packages  404  Not Found [IP: 91.189.88.161 80], E:Some index files failed to download. They have been ignored, or old ones used instead.
failed: [localhost] (item=deb-src http://archive.ubuntu.com/ubuntu/  xenial-updates multiverse) => {"failed": true, "item": "deb-src http://archive.ubuntu.com/ubuntu/  xenial-updates multiverse", "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_5nrjnB/ansible_module_apt_repository.py\", line 565, in <module>\n    main()\n  File \"/tmp/ansible_5nrjnB/ansible_module_apt_repository.py\", line 553, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 454, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: E:Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/multiverse/binary-arm64/Packages  404  Not Found [IP: 91.189.88.161 80], E:Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/multiverse/binary-arm64/Packages  404  Not Found [IP: 91.189.88.161 80], E:Some index files failed to download. They have been ignored, or old ones used instead.\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
        to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1

**Comment by mkody** [comment]
`multiverse` isn't available **at all** for ARM.

**Comment by SlvrEagle23** [comment]
Yeah...I haven't had a chance to test the ARM version in quite a while, and I'm assuming that the "build icecast and liquidsoap from source" processes are totally wrecking it.

This may be a matter of splitting the radio installation into the old style for ARM-based processors and the new style for x86/64 ones.

**Comment by nsystem1** [comment]
TASK [azuracast-db : Apply All DB Migrations] **************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/radiocast/www/util/cli.php migrations:migrate --no-interaction --allow-no-migration", "delta": "0:00:03.627557", "end": "2017-06-12 10:09:56.996600", "failed": true, "rc": 1, "start": "2017-06-12 10:09:53.369043", "stderr": "\n                                                                           \n  [Doctrine\\DBAL\\Exception\\DriverException]                                \n  An exception occurred while executing '':                                \n  SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty  \n                                                                           \n\n                                                                           \n  [Doctrine\\DBAL\\Driver\\PDOException]                                      \n  SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty  \n                                                                           \n\n                                                                           \n  [PDOException]                                                           \n  SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty  \n                                                                           \n\nmigrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--] [<version>]", "stderr_lines": ["", "                                                                           ", "  [Doctrine\\DBAL\\Exception\\DriverException]                                ", "  An exception occurred while executing '':                                ", "  SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty  ", "                                                                           ", "", "                                                                           ", "  [Doctrine\\DBAL\\Driver\\PDOException]                                      ", "  SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty  ", "                                                                           ", "", "                                                                           ", "  [PDOException]                                                           ", "  SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty  ", "                                                                           ", "", "migrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--] [<version>]"], "stdout": "Loading configuration from the integration code of your framework (setter).\n                                                                    \n                    Doctrine Database Migrations                    \n                                                                    ", "stdout_lines": ["Loading configuration from the integration code of your framework (setter).", "                                                                    ", "                    Doctrine Database Migrations                    ", "                                                                    "]}

RUNNING HANDLER [azuracast-user : send user notification] **************************************************************************************************************

RUNNING HANDLER [mariadb : send mysql notification] ********************************************************************************************************************
        to retry, use: --limit @/var/radiocast/www/util/ansible/deploy.retry

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=79   changed=19   unreachable=0    failed=1

**Comment by SlvrEagle23** [comment]
To all: I have pushed up a large codebase update that will differentiate between x86/64 and ARMHF processors, installing IceCast2 and LiquidSoap using the "old-fashioned" way if you're on ARMHF, as this is known to work on a broad variety of ARM processors. I'll be trying it out momentarily and encourage everyone to help test this update.

**Comment by surihost** [comment]
Ok tried again to do a fresh install on scaleway arm 64bit server.

Here it gets stuck now:

TASK [influxdb : Pause to allow InfluxDB to spin up] ***************************
fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for 127.0.0.1:8086"}

RUNNING HANDLER [azuracast-user : send user notification] **********************
        to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP *********************************************************************
localhost                  : ok=33   changed=24   unreachable=0    failed=1

**Comment by SlvrEagle23** [comment]
@surihost Yep, that's the one I'm working on fixing right now

**Comment by SlvrEagle23** [comment]
Update...it appears Scaleway servers don't send the proper architecture headers to let InfluxDB run properly. The binary that apt-get installs doesn't actually run.

Looking into possible workarounds here.

**Comment by surihost** [comment]
Oh ok, no problem.
Thanks for the update :)

**Comment by nsystem1** [comment]
I am getting below error on Ubuntu 16.04
`TASK [azuracast-radio : Install OPAM] **********************************************************************************************************************************
changed: [localhost]

TASK [azuracast-radio : Install LiquidSoap Dependencies] ***************************************************************************************************************
failed: [localhost] (item=[u'libpcre3-dev', u'libfdk-aac-dev', u'libmad0-dev', u'libmp3lame-dev', u'libtag1-dev', u'libfaad-dev', u'libflac-dev', u'pkg-config', u'm4']) => {"failed": true, "item": ["libpcre3-dev", "libfdk-aac-dev", "libmad0-dev", "libmp3lame-dev", "libtag1-dev", "libfaad-dev", "libflac-dev", "pkg-config", "m4"], "msg": "No package matching 'libfdk-aac-dev' is available"}

RUNNING HANDLER [azuracast-user : send user notification] **************************************************************************************************************
        to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=23   changed=18   unreachable=0    failed=1`

**Comment by SlvrEagle23** [comment]
@nsystem1 What architecture are you on?

You may need to do the same "multiverse" update specified above.

**Comment by nsystem1** [comment]
sudo apt-add-repository multiverse && sudo apt-get update
sudo service apache2 stop 

@SlvrEagle23` Actually I made those suggestions and they did fix the above issue. But after your initial fix, it was not necessary to do all that anymore but came back after your later update

**Comment by SlvrEagle23** [comment]
Closing this issue as it's gotten pretty big and deviated a bit from its original purpose.

Recent updates ensure Multiverse is enabled on x86/x64 machines, and bring full support back to ARMHF machines (Scaleway C1 and Raspberry Pi 3). There's still no current support on AARCH64 machines (i.e. Scaleway's new ARM64 VPSes) due to InfluxDB not packaging correctly for that platform.
