### ISSUE TITLE
Missing / invalid value in example data for POST admin/users API endpoint

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#1592]
Hello,

I just want to inform you guys that the Example Value | Schema for creating users has a missing value. Thus having an error when executing the example.
`"formatted_message": "The identifier id is missing for a query of App\\Entity\\Role"`

The example will be successful only if the roles has a "role" id value instead of null
```
"roles": [
    { "id": 4 }
  ]
```

I hope the team can update the example :) Thanks!

**Comment by Vaalyn** [comment]
Thanks for the report, the example should probably show either an empty array without the `null` value or an object like in your example a `null` in that array is definitely not correct.
