### ISSUE TITLE
500 error: Directory <customdir> was not created (cifs 3.0 mount)

### ISSUE THREAD

**Issue by mmacy** [AzuraCast/AzuraCast#1593]
**Using Docker installation method**

Yes.

> AzuraCast • v0.9.5, #5ec1e03 (2019-05-27 14:05) • Docker • PHP 7.2

**Host Operating System**

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

**Describe the bug**

When specifying a custom media directory where the directory is on an existing remote SMB share mount point, a 500 error is encountered when attempting to save the change, and the directory is not updated.

**To Reproduce**

1. Mount SMB share at `/media/azmedia` via /etc/fstab:

  ```
  //windersbox/sharename /media/azmedia cifs nofail,vers=3.0,credentials=/home/username/.smbcredentials,dir_mode=0777,file_mode=0777,serverino
  ```
1. Install AzuraCast via [self-hosted installation method](https://www.azuracast.com/install.html#self-hosted-installation)
1. Complete web-based setup
1. Create a new station
1. Navigate to station, then **Profile** > **ADMINISTRATION** tab
1. Enter local mount path `/media/azmedia` in **Advanced Custom Media Directory**
1. Select **SAVE CHANGES**
1. Result:

> 500
> Directory "/media/azmedia" was not created
> Station.php : 725

**Expected behavior**

The custom media directory setting for the station should be successfully updated, and the user should be able to create playlists and add media files from that custom media directory to those playlists.

**Relevant Logs**

```
web_1       | May 27 15:31:35 9929b18630c6 php-fpm[61]: [WARNING] [pool www] child 4719 said into stderr: "[2019-05-27 15:31:35] AzuraCast.ERROR: Directory "/media/azmedia" was not created {"file":"/var/azuracast/www/src/Entity/Station.php","line":725,"code":0} []"
web_1       | 172.20.0.1 - - [27/May/2019:15:31:35 +0000] "POST /admin/stations/edit/1 HTTP/1.1" 500 2564 "http://localhost/admin/stations/edit/1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "-"
```

App log:

```
[2019-05-27 15:48:14] AzuraCast.ERROR: Directory "/media/azmedia" was not created {"file":"/var/azuracast/www/src/Entity/Station.php","line":725,"code":0} []
```

**Screenshots**

Specifying the Custom Media Directory:

![image](https://user-images.githubusercontent.com/13394541/58429361-7af80f80-805a-11e9-9eb5-f9534b68f7b9.png)

Error thrown on SAVE CHANGES button press:

![image](https://user-images.githubusercontent.com/13394541/58429387-8fd4a300-805a-11e9-9e4e-e20e5e60ed4a.png)

**Device(s):**
 - Device: Desktop
 - OS: Ubuntu 18.04.2 LTS
 - Browser: Google Chrome
 - Version: 74.0.3729.169 (Official Build) (64-bit)

**Additional context**

Confirming mounted SMB share access:

```console
marsh@marsh:~$ ll /media/azmedia/ | head
total 8
drwxrwxrwx 2 root root 4096 May 27 08:22 ./
drwxr-xr-x 3 root root 4096 May 27 06:24 ../
drwxrwxrwx 2 root root    0 Sep  7  2016 alternative/
drwxrwxrwx 2 root root    0 May  5 05:58 ambient/
drwxrwxrwx 2 root root    0 Mar  2  2014 blues/
drwxrwxrwx 2 root root    0 Nov 14  2013 breaks/
drwxrwxrwx 2 root root    0 May  5 05:59 chill/
...
```

**Comment by Vaalyn** [comment]
To me it looks like you only mounted the SMB share on your host machine without also mounting it to your Docker container. Can you clarify if you have also mounted it to your container via a `docker-compose.override.yml`?

**Comment by mmacy** [comment]
Funny, I was filling a water bottle just now thinking about this, walked over to machine to check, and saw your reply. Nope! I had not mounted it to the container. :unamused:  

Thanks for the quick response, @Vaalyn - closing.

**Comment by mmacy** [comment]
For anyone curious, here's the `docker-compose.override.yml` to enable this particular config:

```docker
# docker-compose.override.yml
version: '2.2'

services:
  web:
    volumes:
     - /media/azmedia:/var/azuracast/music

  stations:
    volumes:
     - /media/azmedia:/var/azuracast/music
```
