### ISSUE TITLE
Upload media to docker

### ISSUE THREAD

**Issue by bayubad** [AzuraCast/AzuraCast#1595]
How can I upload media files directly to docker folders?

I normally use wget inside the machine to download media from other servers and then I want to move the files to /var/azuracast/stations/station1/media so the file get appeared in Music Files.

**Comment by SlvrEagle23** [comment]
@bayubad You can follow our [SFTP setup instructions](https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#access-files-via-sftp) if you're using Docker to temporarily set up a server where you can connect and upload files in bulk.
