### ISSUE TITLE
Clarification on Ansible & Docker installs & Updates

### ISSUE THREAD

**Issue by williambatson** [AzuraCast/AzuraCast#1596]
I read and understand the move to Docker only installs -  However, some questions that are not clear....
1. Is it still possible to update an Ansible install and will that continue to be supported with future updates?
(if so - can someone post the Ansible update procedure that used to be posted along side the Docker update commands?

2.   Is it possible or even advisable to modify a live/active system from Ansible to Docker without losing data?   If so - is there a program developed to easily migrate to a Docker install?

I want to stay current with my updates but I don't want to torch my system and start over just for Docker unless there's a way to safely do it.  Any clarification on this would be help or point me in the right direction.

Thanks so much.

**Comment by SlvrEagle23** [comment]
@williambatson Good questions! Happy to answer them. I know you've been a long-time AzuraCast user, perhaps even since before our Docker installation method existed.

1. Yes, it is indeed still possible to update an Ansible installation, and for the foreseeable future we have every intention of keeping both the Ansible installs and Docker installs up to date.

Updating the Ansible installation is the same simple command it used to be:

```
cd /var/azuracast/www
./update.sh
```

2. Not only is it possible to migrate to Docker from Ansible, but our new zero-downtime backup process has made it even safer to do so. The new backups produced by the latest version of AzuraCast are uniform across both Ansible and Docker installs, and thus are portable from one to the other, so moving is as simple as backing up the Ansible installation, then restoring that backup using the Docker utility script.

We even have a little script put together that does exactly that process. If you run `bash docker_migrate.sh`, it will generate a backup of your Ansible installation, uninstall the Ansible components, install the Docker components and then restore that backup into Docker.

It's not particularly well tested (as we don't do the migration that often in our testing environments), but even if the migration doesn't go particularly well, you can always use the backup it generates to restore the installation again.

**Comment by SlvrEagle23** [comment]
@williambatson I just did some snapshotting and testing and can now confirm the Docker migrator is in great shape and should be working fine.

As the root user, you'll want to run on the server:

```
cd /var/azuracast/www
bash update.sh
bash docker-migrate.sh
```

Be sure to watch the terminal and confirm any prompts (you'll be asked to type "y" to confirm the uninstallation), and it'll move you over in just a few quick minutes.

**Comment by williambatson** [comment]
Outstanding -  thank you very much for the answer, info and check - I'll hit it once no one's on it and give a shout out how it went -  thanks again!

**Comment by williambatson** [comment]
** One caveat:   Port assignments did not go smoothly.   Had a few stations appear to be running normally and LiquidSoap processing songs, etc -  but no sound.    Clearing the assigned ports and restarting the stations reset the ports used for that station and the station/music resumed to normal operation.  Just an FYI.

**Comment by williambatson** [comment]
OK maybe I was not 100% -   I'm 50/50 -  Did 2 servers, the first one completed and works.
The 2nd one has half the stations working and half not - clearing the ports does nothing, creating new stations, they all look like they're running and all looks right - but no sound -  not the silver voice of Eagle or songs uploaded.

New Station just created throws this in the Icecast Error log:
[2019-05-29  00:05:11] WARN xml/parsing warning: 
[2019-05-29  00:05:11] WARN xml/parsing skipping element "stream-description" parsing "mount" at line 27
[2019-05-29  00:05:11] WARN xml/parsing warning: 
[2019-05-29  00:05:11] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2019-05-29  00:05:11] WARN xml/parsing warning: 
[2019-05-29  00:05:11] WARN xml/parsing skipping element "genre" parsing "mount" at line 29
[2019-05-29  00:05:11] WARN slave/slave_startup process has 1048576 max file descriptor limit
[2019-05-29  00:05:13] WARN source/source_set_intro Cannot open intro for /radio.mp3 "/usr/local/share/icecast/web//radio.mp3": No such file or directory

Both are on identical servers, identical everything actually - one took the Docker transition fine, the other not.... I also noticed the ./docker.sh file is no long at root but was created now in  var/azuracast/www    so not sure of that was normal or not - but I can't run update or Let's Encrypt with it burried 3 directories deep or I'm too thick to figure out how to add the path into the code. 
Regardless - not sure where to go with it at this point - one up, one down

**Comment by SlvrEagle23** [comment]
@williambatson Wait, was AzuraCast not installed at `/var/azuracast/www` on the second installation? That's the default location where it should be installed, and the migrator is definitely expecting it to be there.

**Comment by williambatson** [comment]
oh yes it was....   I just thought on the docker file was located at root level because you'd usually run ./docker-sh update-self    at root level - and I found the files /var/azuracast/www and did not expect them there.... that's all.    Still trying to figure out out to cure the one upgraded server -  Does that Icecast error log tell you anything?

**Comment by SlvrEagle23** [comment]
@williambatson I don't think the problem in that case is with Icecast but rather with Liquidsoap...does the Liquidsoap log show anything of interest? Those icecast warnings are fine.

**Comment by williambatson** [comment]
Let me paste what I've got on one of the ones that doesnt work -   that last few entries....
2019/05/28 23:06:51 [lang:3] AzuraCast Feedback Response: OK
2019/05/28 23:12:28 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/bubster_box_1/media/simply_red_-_sunrise_-28extended-29.mp3".
2019/05/28 23:12:38 [playlist_new:3] Finished with "/var/azuracast/stations/bubster_box_1/media/simply_red_-_sunrise_-28extended-29.mp3".
2019/05/28 23:12:38 [playlist_new:3] Prepared "/var/azuracast/stations/bubster_box_1/media/simply_red_-_sunrise_-28extended-29.mp3" (RID 1).
2019/05/28 23:12:38 [lang:3] AzuraCast Feedback Response: OK
2019/05/28 23:18:15 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/bubster_box_1/media/simply_red_-_sunrise_-28extended-29.mp3".
2019/05/28 23:18:25 [playlist_new:3] Finished with "/var/azuracast/stations/bubster_box_1/media/simply_red_-_sunrise_-28extended-29.mp3".
2019/05/28 23:18:25 [playlist_new:3] Prepared "/var/azuracast/stations/bubster_box_1/media/simply_red_-_sunrise_-28extended-29.mp3" (RID 2).
2019/05/28 23:18:25 [lang:3] AzuraCast Feedback Response: OK
2019/05/28 23:24:02 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/bubster_box_1/media/simply_red_-_sunrise_-28extended-29.mp3".
2019/05/28 23:24:12 [playlist_new:3] Finished with "/var/azuracast/stations/bubster_box_1/media/simply_red_-_sunrise_-28extended-29.mp3".
2019/05/28 23:24:12 [playlist_new:3] Prepared "/var/azuracast/stations/bubster_box_1/media/simply_red_-_sunrise_-28extended-29.mp3" (RID 3).
2019/05/28 23:24:12 [lang:3] AzuraCast Feedback Response: OK
--------------------------------------------------------------------------
and another one that's not working
2019/05/29 06:17:33 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/williambatson_resident_2/media/simply_red_-_sunrise_-28extended-29.mp3".
2019/05/29 06:17:44 [playlist_default:3] Finished with "/var/azuracast/stations/williambatson_resident_2/media/simply_red_-_sunrise_-28extended-29.mp3".
2019/05/29 06:17:44 [playlist_default:3] Prepared "/var/azuracast/stations/williambatson_resident_2/media/simply_red_-_sunrise_-28extended-29.mp3" (RID 3).
2019/05/29 06:17:44 [lang:3] AzuraCast Feedback Response: OK
2019/05/29 06:23:20 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/williambatson_resident_2/media/simply_red_-_sunrise_-28extended-29.mp3".
2019/05/29 06:23:31 [playlist_default:3] Finished with "/var/azuracast/stations/williambatson_resident_2/media/simply_red_-_sunrise_-28extended-29.mp3".
2019/05/29 06:23:31 [playlist_default:3] Prepared "/var/azuracast/stations/williambatson_resident_2/media/simply_red_-_sunrise_-28extended-29.mp3" (RID 1).
2019/05/29 06:23:31 [lang:3] AzuraCast Feedback Response: OK
2019/05/29 06:29:08 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/williambatson_resident_2/media/simply_red_-_sunrise_-28extended-29.mp3".
2019/05/29 06:29:18 [playlist_default:3] Finished with "/var/azuracast/stations/williambatson_resident_2/media/simply_red_-_sunrise_-28extended-29.mp3".
2019/05/29 06:29:18 [playlist_default:3] Prepared "/var/azuracast/stations/williambatson_resident_2/media/simply_red_-_sunrise_-28extended-29.mp3" (RID 2).
2019/05/29 06:29:18 [lang:3] AzuraCast Feedback Response: OK
-------------------------------------  and the Azuracast Application Log
[2019-05-29 06:30:47] AzuraCast.NOTICE: HTTP client GET call to http://stations:8030/admin/stats produced response NULL [] {"station":{"id":131,"name":"Mx Xaris 1"}}
[2019-05-29 06:30:56] AzuraCast.INFO: New message of type App\Message\UpdateNowPlayingMessage added to queue. [] []
[2019-05-29 06:30:58] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []
[2019-05-29 06:31:01] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-05-29 06:31:01] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-05-29 06:31:02] AzuraCast.NOTICE: HTTP client GET call to http://stations:8030/admin/stats produced response NULL [] {"station":{"id":131,"name":"Mx Xaris 1"}}
[2019-05-29 06:31:16] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-05-29 06:31:16] AzuraCast.NOTICE: HTTP client GET call to http://stations:8030/admin/stats produced response NULL [] {"station":{"id":131,"name":"Mx Xaris 1"}}
[2019-05-29 06:31:31] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-05-29 06:31:32] AzuraCast.NOTICE: HTTP client GET call to http://stations:8030/admin/stats produced response NULL [] {"station":{"id":131,"name":"Mx Xaris 1"}}
[2019-05-29 06:31:46] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-05-29 06:31:46] AzuraCast.NOTICE: HTTP client GET call to http://stations:8030/admin/stats produced response NULL [] {"station":{"id":131,"name":"Mx Xaris 1"}}
[2019-05-29 06:32:02] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-05-29 06:32:02] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-05-29 06:32:02] AzuraCast.NOTICE: HTTP client GET call to http://stations:8030/admin/stats produced response NULL [] {"station":{"id":131,"name":"Mx Xaris 1"}}
[2019-05-29 06:32:17] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-05-29 06:32:17] AzuraCast.NOTICE: HTTP client GET call to http://stations:8030/admin/stats produced response NULL [] {"station":{"id":131,"name":"Mx Xaris 1"}}

**Comment by SlvrEagle23** [comment]
@williambatson But those are all normal...I'm not sure what the problem is. Maybe try restarting the server in case the old port reservations are conflicting with the new Docker ones? You should also do the "Utilities > Restart Broadcasting" thing if you haven't already.

**Comment by williambatson** [comment]
I've restarted the one -  no change, I've had to take it offline until I find a fix...
Now the other identical server that seemed OK is doing the same thing on a newly created station
All set up fine, shows all running, pages all loading - but no sound
other stations on that server are running just fine since the change to Docker
this is the ice log error  for this server:
[2019-06-02  11:14:41] WARN xml/parsing warning: 
[2019-06-02  11:14:41] WARN xml/parsing skipping element "stream-description" parsing "mount" at line 27
[2019-06-02  11:14:41] WARN xml/parsing warning: 
[2019-06-02  11:14:41] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2019-06-02  11:14:41] WARN xml/parsing warning: 
[2019-06-02  11:14:41] WARN xml/parsing skipping element "genre" parsing "mount" at line 29
[2019-06-02  11:14:41] WARN connection/get_ssl_certificate Invalid cert file /etc/nginx/ssl/ssl.crt (system lib)
[2019-06-02  11:14:41] WARN slave/slave_startup process has 1048576 max file descriptor limit
[2019-06-02  11:14:42] WARN source/source_set_intro Cannot open intro for /radio.mp3 "/usr/local/share/icecast/web//radio.mp3": No such file or directory

I only use these 2 servers -  so If I lose this one too, I'm cooked,   Need to find a fix or how can I make a back up copy of a docker install and restore back to the original Ansible install?    Or -   is there a way to back up all -  then wipe the server and install fresh Docker and then load the back up?      I'm running out of ideas.   Thanks

**Comment by SlvrEagle23** [comment]
@williambatson Would you mind joining us on our [Slack channel](https://join.slack.com/t/azuracast/shared_invite/enQtNDgyNzA4NzY2MzU3LWNmZjY3MmZlZGI1NzQ0OWEzMDBlMDk4MWVkMGMwMjAwYWQxZjdjYzRkYmM2NDkwZjc3ODI0N2UxY2M3ZjIxZWI)? I'm having trouble figuring out what's going wrong, and I want to get your setup up and running, but we'll have to take a look directly at the installation at this point.

**Comment by williambatson** [comment]
Not at all -  clicked the link and am waiting on the confirmation email -  did it twice as it wasn't totally instant.

**Comment by williambatson** [comment]
Joined slack as WilliamBatson   Contact me there to swap log in info, etc.   Thanks
