### ISSUE TITLE
AzuraCast jingle plays when cue-out point is set for a song

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#1597]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu 18

Hi,
The error message problem is coming back. The problem comes in the edition of a title, if I add in second for a title of 189 I pass it to 100, then the error message intervenes in the mixing. 
![Capture d’écran 2019-05-26 à 13 31 52](https://user-images.githubusercontent.com/379099/58381318-23a36200-7fbc-11e9-86a4-1b4aed9c539e.jpg)

The same problem is also on the demonstration site, if I do the same manipulation.
![Capture d’écran 2019-05-26 à 13 30 38](https://user-images.githubusercontent.com/379099/58381321-28681600-7fbc-11e9-9dd6-3c4185730e8b.png)

**Comment by SlvrEagle23** [comment]
@ckeurk Can confirm this is happening locally to me as well. Investigating solutions.

**Comment by SlvrEagle23** [comment]
@ckeurk I have an upstream issue with Liquidsoap (savonet/liquidsoap#803) about the tendency for "fallback" to be triggered fairly frequently, which yielded the AzuraCast error "jingle" being played a lot of times when it wasn't supposed to.

In the meantime, I pulled the AzuraCast error file from Liquidsoap entirely, where it's replaced with a short 2-second silence, which should cleanly fade from one song to the next.
