### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by justwolfii** [AzuraCast/AzuraCast#1599]
Hello,
Iam looking for files with CSS in AzuraCast (Ansible version) to change some things..
For example:
**I want to change color of these boxes**
![image](https://user-images.githubusercontent.com/39670563/58506914-cc0a1f80-8190-11e9-86cc-ae6edeb8293e.png)
![image](https://user-images.githubusercontent.com/39670563/58506952-e3e1a380-8190-11e9-9f36-398cc0762d97.png)

**Or change this image**
![image](https://user-images.githubusercontent.com/39670563/58507055-20ad9a80-8191-11e9-8d4d-0d472be3dc04.png)

Thanks for answers.

**Comment by ErnestPH** [comment]
Probably, you can change that in Custom branding internal pages

**Comment by SlvrEagle23** [comment]
@justwolfii We do have a "Custom Branding" section in the global system administration where you can specify any custom CSS or JavaScript that you want, which can override any of our existing styling.
