### ISSUE TITLE
MySQL error when setting Custom Fade-Out

### ISSUE THREAD

**Issue by Denniz** [AzuraCast/AzuraCast#1601]
**Using Docker installation method**
YES

**Host Operating System**
Ubuntu 16.04

**Describe the bug**
MySQL error when setting Custom Fade-Out time 7 seconds before end of song. Song length (by AzuraCast) 227 seconds. Custom Fade-Out time set to 220 seconds. Error when saved:

_An exception occurred while executing 'UPDATE station_media SET lyrics = ?, isrc = ?, mtime = ?, fade_out = ? WHERE id = ?' with params ["", "", 1559133945, "220", 52]: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'fade_out' at row 1
AbstractMySQLDriver.php : 106_

**To Reproduce**
- Search for song
- Edit song parameters
- Set Custom Fade-Out to 220
- Click Save

**Expected behavior**
Expected setting to be saved.

**Comment by Vaalyn** [comment]
The maximum value for the Custom Fade-Out time is `99`. I think you may have misunderstood how that feature works. If you enter a value of `220` for a song with a length of `227` seconds then the song would start fading out after 7s. You need to count from the end of a song not from the beginning for this setting.
