### ISSUE TITLE
Questions about AzuraCast intergration in the internet-in-a-box project

### ISSUE THREAD

**Issue by m-anish** [AzuraCast/AzuraCast#1606]
Hi,

On this website, I see remnants of a legacy install which presumably used ansible to install azuracast. I wanted to know if that is still a supported method. 

Background: I am a volunteer of the internet-in-a-box project - https://github.com/iiab/iiab

We work to provide remote communities with offline media servers and decentralized mesh wifi networks, and would love to have azuracast as a part of the apps that come with iiab.

Our setup is primarily ansible based - so I was wondering what would be the best strategy for me to install azuracast. I am okay with using docker if need be, but would need to modify the default port on which Azuracast is served. Also, I see the docker.sh script does things to the mysql root password which I wont like to touch as part of the install (we do out own mysql installation and configuration). 

Cheers! 
Anish

**Comment by m-anish** [comment]
Hi. @SlvrEagle23 @Vaalyn 

Sorry for my inactivity on this issue request. 

I have an initial role of azuracast docker install working! Thanks to support from @Vaalyn 

https://github.com/iiab/iiab/pull/1733

However, while most features work, there is a UI issue. IIAB often runs in very remote and offline communities, so there is no internet.  When azuracast webpage loads, it tries to load some online elements, which when not available due to lack of internet, result in many icons being shown up with their alt_texts. 

Is there any way I could help to get this resolved, so the icons all load offline. This will add minimal overhead to overall installation size, but solve an annoying UI issue. 

Thanks again for such a wonderful project. I am excited about the possibilities of providing remote communities with their own, self-run, self-maintained radio station.

Please see the screenshot below to see the UI issue:
![Screenshot from 2019-06-19 10-39-27](https://user-images.githubusercontent.com/5288668/59738586-64bb2900-927f-11e9-90b2-ca7b567c1e69.png)

**Comment by SlvrEagle23** [comment]
@m-anish This can be very easily fixed, as we've already localized a vast majority of our assets and can just include our material icons in that local set of packages. I'll get to work on it shortly.

**Comment by m-anish** [comment]
Wonderful!

`https://fonts.googleapis.com/icon?family=Material+Icons` seems to be the call that wants to go online. 

Thank you!

**Comment by SlvrEagle23** [comment]
@m-anish The latest commit moves both the Roboto font and the Material Icons back to the local AzuraCast instance, so the entire UI is served by AzuraCast itself.

**Comment by m-anish** [comment]
Great. So a fresh docker.sh install from scratch should do it?

**Comment by Vaalyn** [comment]
@m-anish Either fresh install or just update the existing installation

**Comment by m-anish** [comment]
Thanks! I'll take it for a spin!

**Comment by holta** [comment]
@Vaalyn & @SlvrEagle23 there are quite a number of very sincere Internet-in-a-Box implementers around the world asking if AzuraCast might be made to work on Raspberry Pi in 2019 &mdash; do you believe this might be viable or at least plausible?

WHhat steps would need to occur if so, in your opinion?

(Or is this just not possible?)

**Comment by m-anish** [comment]
Is the docker install script supposed to work on Debian 10?

We see this issue here -> https://github.com/iiab/iiab/issues/1766

**Comment by Vaalyn** [comment]
@m-anish Debian 10 / Buster is still a testing distribution and not stable. For the installation of Docker we fetch the official Docker installation script [`get-docker.sh`](https://get.docker.com/) and run that. It seems like that script is currently not supporting Debian 10 but that should change when Debian 10 is released.

**Comment by m-anish** [comment]
Sounds good. Thanks for the clarification.

**Comment by SlvrEagle23** [comment]
@holta @m-anish I've done some further testing and I can confirm that AzuraCast's Ansible installation works perfectly with Ubuntu 18.04 installed on a Raspberry Pi 3 or newer.

In the interest of helping our numerous users who have asked us about this, I've updated our documentation to include a specific [guide on installing for ARM64/RPi devices](https://www.azuracast.com/install/install_rpi.html).

I am continuing to investigate Docker's compatibility, but I can already tell that out of the box our Docker utility script installer won't work because Docker Compose does not (and does not _plan to_) release a prebuilt binary for non-x86_64 architectures. There will have to be specialized instructions for Raspbian installations as a result of this.

Beyond that, working on Docker compatibility is still a priority for us and we will continue to look into this.

**Comment by Vaalyn** [comment]
@SlvrEagle23 

> Docker utility script installer won't work because Docker Compose does not (and does not plan to) release a prebuilt binary for non-x86_64 architectures

That can't be correct. Last weekend I've installed Docker and Docker Compose on my old Raspberry Pi 1 to test out `Mycroft`. Docker Compose worked without problems but Docker itself doesn't work in the newest version so I had to install Docker like this: `sudo apt-get install 'docker-ce=18.06.*'` and it worked without a problem. See this issue on [`moby/moby`](https://github.com/moby/moby/issues/38175).

**Comment by SlvrEagle23** [comment]
@Vaalyn See for yourself via [their releases page](https://github.com/docker/compose/releases). Our Docker Compose installer pulls the latest release from this list and then tries to pull the binary from the releases page, and constantly bounces back a "Not Found" on ARM/RPi devices because of this. There are numerous tickets where they've said they won't publish release builds for anything other than x86_64, and instead they recommend installing via `pip`.

We can also recommend the same, but making that cross-platform is not going to be nearly as easy.

**Comment by Vaalyn** [comment]
@SlvrEagle23 Okay, I didn't use the prebuilt binary from their page but just installed it via `sudo apt-get install`.

**Comment by m-anish** [comment]
Wonderful!

**Comment by holta** [comment]
@Vaalyn wrote: (14 days ago)

> @m-anish Debian 10 / Buster is still a testing distribution and not stable. For the installation of Docker we fetch the official Docker installation script [`get-docker.sh`](https://get.docker.com/) and run that. It seems like that script is currently not supporting Debian 10 but that should change when Debian 10 is released.

As Debian 10 was released 24h ago, I though why not give it a shot.  It did not work.  The error message is here: https://github.com/iiab/iiab/issues/1766#issuecomment-509037817

Should I try again in a week?

**Comment by SlvrEagle23** [comment]
@holta Yeah, you might be a little eager on that one. As mentioned in earlier comments, if what you're looking for is Raspberry Pi ARM64 support, our Ansible installation method (usable via `./install.sh` in this repository) supports this without issue and works perfectly now, provided you install the ARM64 build of Ubuntu 18.04.

**Comment by holta** [comment]
AzuraCast would appear to work now, on Debian Buster 10.0.0, when installed as a part of Internet-in-a-Box, as mentioned @ https://github.com/iiab/iiab/issues/1766#issuecomment-517963520

FYI Getting AzuraCast to work on Raspbian on Raspberry Pi is the outstanding challenge here e.g. iiab/iiab#1772

**Comment by m-anish** [comment]
I'll work on the ansible playbook for IIAB when I get to hacking on this. Thanks!

**Comment by m-anish** [comment]
@Vaalyn @SlvrEagle23 

Hello! I just wanted to bring to your notice that the BBC did a small 'radio' show in which the 'internet-in-a-box' we deployed in a remote high altitude himalayan valley (zanskar) got featured, and as part of the show, the radio software (azuracast) also got a mention.

https://www.bbc.co.uk/programmes/w3cszv1s

Hope you enjoy listening. There is another deployment which will happen over the winter in Ladakh in warm -30C weather, and one of the primary points of interest there is ... the radio! So a big thanks to everyone in this community for making this possible.

Have a beautiful day!

**Comment by m-anish** [comment]
For full technical disclosure, in Zanskar's case, azuracast is running as a docker image on an intel i3 NUC x64 mini-pc.

**Comment by SlvrEagle23** [comment]
@m-anish Thank you so much for sharing this with us. We have always been quite happy to be a part of this project, but to actually hear the radio station being used in Zanskar is sincerely very touching to us.
