### ISSUE TITLE
Change reversed proxy url

### ISSUE THREAD

**Issue by TorchwoodPL** [AzuraCast/AzuraCast#1608]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 16.04 LTS

**Describe the bug**
I changed proxy domain for my azuracast instalation and after restartin apache I get login error. It is working on old URL. I also changed site url at AC admin panel.

**Expected behavior**
Accept new URL.

**Relevant Logs**
```
web_1       | 172.23.0.1 - - [30/May/2019:12:26:21 +0000] "POST /login HTTP/1.1" 302 5 "http://radio.vps.expij.pl/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.109" "37.7.88.204"
web_1       | 172.23.0.1 - - [30/May/2019:12:26:21 +0000] "GET /login HTTP/1.1" 200 4291 "http://radio.vps.expij.pl/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.109" "37.7.88.204"
```

**Screenshots**
![151559219498](https://user-images.githubusercontent.com/2800036/58662716-20e19d80-832b-11e9-9c1f-be6558ef09c1.png)

**Device(s):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Opera
 - Version: 60.0.3255.109

**Comment by Vaalyn** [comment]
I'm not sure what error you are experiencing. The screenshot you linked is not working and when I visit the URL from the logs you posted I can't see an error there.

Could you upload the screenshot directly to GitHub and elaborate what error you are seeing exactly?

**Comment by TorchwoodPL** [comment]
http://radio.vps.expij.pl/login - on that url I cannot login and log above shows what is happening when I try
http://radio.expij.h-y.eu/login - this is old url and on that I can log in

Both are pointing to the same AC instance, also radio.vps.expij.pl is url set in AC admin.

**Comment by Vaalyn** [comment]
Thanks for clarifying. Could you check what data is send to the server in the `POST` request when you click on `SIGN IN`? It should send the `username` and `password` form fields in that request and the values should match what you typed in.

You can view this information by opening the browsers develover console, switch to the `Network` tab, check `Preserver Log` in the options, then try to login and after it failed click on the request to the `login` endpoint and scroll down to the `Form Data`. If that looks okay check the logs by running `docker logs azuracast_web_1` after the login to see if there is any error on the server.

**Comment by TorchwoodPL** [comment]
```
172.23.0.1 - - [31/May/2019:05:23:16 +0000] "GET / HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.109" "37.7.88.204"
172.23.0.1 - - [31/May/2019:05:23:17 +0000] "GET /login HTTP/1.1" 200 4035 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.109" "37.7.88.204"
[2019-05-31 05:23:17] AzuraCast.INFO: Running Now Playing sync task [] []
172.23.0.1 - - [31/May/2019:05:23:17 +0000] "GET /static/dist/lib/jquery/jquery-220afd743d.min.js HTTP/1.1" 200 88145 "http://radio.vps.expij.pl/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.109" "37.7.88.204"
172.23.0.1 - - [31/May/2019:05:23:17 +0000] "GET /static/dist/dark-7b523b88ec.css HTTP/1.1" 200 783369 "http://radio.vps.expij.pl/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.109" "37.7.88.204"
172.23.0.1 - - [31/May/2019:05:23:17 +0000] "GET /static/dist/lib/bootstrap-notify/bootstrap-notify-a02f92a499.min.js HTTP/1.1" 200 7934 "http://radio.vps.expij.pl/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.109" "37.7.88.204"
172.23.0.1 - - [31/May/2019:05:23:17 +0000] "GET /static/dist/app-568f64bdd0.js HTTP/1.1" 200 13806 "http://radio.vps.expij.pl/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.109" "37.7.88.204"
172.23.0.1 - - [31/May/2019:05:23:17 +0000] "GET /static/dist/material-c652fed16a.js HTTP/1.1" 200 281120 "http://radio.vps.expij.pl/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.109" "37.7.88.204"
172.23.0.1 - - [31/May/2019:05:23:17 +0000] "GET /static/dist/lib/bootstrap/bootstrap-a454220fc0.bundle.min.js HTTP/1.1" 200 78635 "http://radio.vps.expij.pl/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.109" "37.7.88.204"
172.23.0.1 - - [31/May/2019:05:23:19 +0000] "POST /login HTTP/1.1" 302 5 "http://radio.vps.expij.pl/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.109" "37.7.88.204"
172.23.0.1 - - [31/May/2019:05:23:19 +0000] "GET /login HTTP/1.1" 200 4291 "http://radio.vps.expij.pl/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.109" "37.7.88.204"
```
This is all logs comming from login reguest at new (radio.vps.expij.pl) domain.

**Comment by Vaalyn** [comment]
@TorchwoodPL Strange, I've not seen anything that would indicate an error coming from the application itself so far. Would you mind creating an account for me so that I can test this myself on your installation? If that's okay for you, you can send me the account details to vaalyndev@gmail.com

**Comment by TorchwoodPL** [comment]
What else I should check? Why changing domain cause errors? You dont need to have account on my radio to determine that.

**Comment by Vaalyn** [comment]
@TorchwoodPL I can't tell you the "why" because I can't see any errors in the logs you posted that indicate that something is wrong on the server side. The only thing that I see from your screenshots is that you can't log in. Without any errors to indicate what's wrong I can only tell you to check if you entered your username + password correctly but that will probably not help you much. Furthermore changing domains shouldn't have any impact on just the login process because there is no domain check in the login process, that's also why I find this problem so strange.

**Comment by TorchwoodPL** [comment]
It worked again over night, don't know how or why...
