### ISSUE TITLE
UI questions 

### ISSUE THREAD

**Issue by linksilver** [AzuraCast/AzuraCast#161]
hello !
is there a way to display the next song to be played ?
can we also display the "progression" of the current played song ?
thanks for your work !!

**Comment by SlvrEagle23** [comment]
@linksilver Now you can! The nowplaying API has been updated to include both "playing_next" and the duration/start time of the current song, from which you can build a timer of the song's playback. I've already rolled this exact thing out on the public page.

**Comment by linksilver** [comment]
wonderfull  !!! 
can we get the next 5 music for exemple ?

**Comment by SlvrEagle23** [comment]
@linksilver I'm going to leave it at 1 for now for an important reason: once you've determined what the next x songs _will_ be, you generally can't (or at least shouldn't) change them. So, if we pick the next 5 songs out, and someone adds or removes songs from playlists, it'll take 5 songs before they even notice a change. That also greatly increases the likelihood of us playing a song that's been deleted between the time it was queued up and the time it got played.

**Comment by linksilver** [comment]
oh yeah i see what you mean ! i was thinking about programmed playlist in fact !
btw it (programmed playslist) seems to doesnt work anymore i try since this morning to do some test, wait a specific time but it seems to dont recognize the playlists!
