### ISSUE TITLE
SHOUTcast logs Error: Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by mikedorst** [AzuraCast/AzuraCast#1614]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
SHOUTcast logs keeps erroring on UTF-8 characters. Cleared the logs many times but it keep popping up.

**To Reproduce**
Not sure if this is reproducible on your own environment, contact me if you need login details.

**Expected behavior**
Logs to show

**Relevant Logs**
[shoutcast.log](https://github.com/AzuraCast/AzuraCast/files/3244850/shoutcast.log)

**Screenshots**

![image](https://user-images.githubusercontent.com/27761242/58761992-c9217d00-854a-11e9-9f8d-ae071383067a.png)

**Comment by Vaalyn** [comment]
Would you mind providing us with one of these files so that we can check what characters are causing this problem?

You can copy them with the following command from the container to your host machine:
`docker cp azuracast_stations:/var/azuracast/stations/<your_station_name>/config/<log_file_name> ./<log_file_name>`
(Replace the `<xxxx>` placeholders with the correct values.

**Comment by SC2Mitch** [comment]
Heres the [logs](https://pastebin.com/rk99UVCq) for you, looking at them in notepad++ it returns some error on these lines:
`[0;32m2019-06-13 11:48:46  DEBUG   ident is DIDC-8000, DID is 38dd8971566cea226668ee6f4e11f42fb12451c38a873863384cba362edcc
``[0m2019-06-13 11:48:46 INFO    [MAIN] Starting 3 network threads
`

**Comment by Vaalyn** [comment]
Thank you for the logs. The character that is most likely the problem is the `0x1b` or `ESC` character which is a control. Those are not allowed in JSON which is probably the reason why the logs fail to be displayed.

**Comment by SC2Mitch** [comment]
@Vaalyn Is there anyway we can fix that on our end? We're unable to resolve the issue locally.

**Comment by Vaalyn** [comment]
@SC2Mitch You could manually enter the web container and run the following command on the shoutcast log files to remove all unprintable characters: `tr -cd '\11\12\15\40-\176' < [file-with-binary-chars] > [clean-file]`. I've copied that command from https://alvinalexander.com/blog/post/linux-unix/how-remove-non-printable-ascii-characters-file-unix

Depending on your song titles it could be that characters that don't fall in the range of the specified characters get removed too. I haven't tested this but in theory it should work. You might wanna duplicate the log file and test this first.

**Comment by SC2Mitch** [comment]
Thanks, issue is resolved, can be closed @mikedorst @Vaalyn
