### ISSUE TITLE
Stream goes live but doesn't update "Now Playing"

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#1617]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu 18.4
**Describe the bug**
When you go live the songs don't update the Now Playing tab, it shows Station Offline. The music itself works fine. 
**To Reproduce**
1. Turn on the station.
2. Monitor the "On Air" menu.
3) Restart if needed, it continues to repeat itself.

**Expected behavior**
For the station to show the name of the song playing.
**Relevant Logs**

`2019-06-02 21:42:50	WARN	[ADMINCGI sid=1] Title update rejected - value not allowed: - clubmusic5`
`2019/06/02 21:42:49 [playlist_club:3] Prepared "/var/azuracast/stations/vanilla_unicorn/media/Club Music/clubmusic5.mp3" (RID 2).
2019/06/02 21:42:49 [vanilla_unicorn_autodj_fallback:3] Switch to random_6404 with forgetful transition.
2019/06/02 21:42:49 [random_6404:3] Switch to audio_to_stereo_6402.
2019/06/02 21:42:49 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/vanilla_unicorn/media/Club Music/clubmusic6.mp3".
2019/06/02 21:42:49 [smart_cross_6428:3] Analysis: -infdB / -15.054789dB (2.00s / 2.00s)
2019/06/02 21:42:49 [smart_crossfade:3] new >= old + margin, old <= medium and new <= high.
2019/06/02 21:42:49 [smart_crossfade:3] Do not fade if it's already very low.
2019/06/02 21:42:49 [smart_crossfade:3] Transition: crossed, no fade.
2019/06/02 21:42:50 [lang:3] AzuraCast Feedback Response: OK
`
**Screenshots**
Screenshot of the broken Now Playing text [HERE](https://puu.sh/DAMbS.png)
The song in question [HERE](https://puu.sh/DAM5q.png)
**Device(s):**
 - Device: Desktop 
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest

**Additional context**
I do believe this may be related to #1614 | Also if I click on "Song History" it works fine [HERE](https://puu.sh/DAMk7.png)

**Comment by Vaalyn** [comment]
This is a problem with ShoutCast itself. I've encountered something like this in the past were I was using Centova Cast with ShoutCast and also had some titles rejected. [This](https://centova.com/forums/index.php?topic=3572.msg10648#msg10648) is the thread were I wrote with one of the ShoutCast maintainers about this.

To sum up the reason for rejecting such titles let me quote their response here:

> its intentionally blocked to prevent listeners and the listing details being populated with bad data. as all of the cases of such titles beginning with punctuation that were seen from the information the DNAS provides to the SHOUTcast platform were not of any use, especially as it's generally expected to see an 'artist - title' style of title and not a lot of the abused title updates that have been seen in the system which all begin with random punctuation characters.

> so apologies if it's affecting a few legitimate cases (which will need to be re-worded if needed) but the data that was looked at indicated it was worth doing it vs the small possible side-effects for legitimate cases.

The easiest solution would be to add an Artist to your song.

**Comment by SC2Mitch** [comment]
Thank you for the help, adding Artists have since resolved the problem.
