### ISSUE TITLE
I'm having trouble with Liquidsoap's AutoDj service.

### ISSUE THREAD

**Issue by isaiaswebnet** [AzuraCast/AzuraCast#1618]
Installation method: Traditional

The AutoDj of Liquidsoap stop when it plays 4 to 5 songs and I always have to start manually. I have already done a complete update and even cleared all the cache and continues with this same problem. How can I be solving this error, since I have not found a solution in the similar problems of other members here in Github?

**Comment by Vaalyn** [comment]
Please have a look at the liquidsoap log and post it here.

**Comment by isaiaswebnet** [comment]
http://35.231.227.140/admin/logs/view/3/liquidsoap_log

**Comment by Vaalyn** [comment]
@isaiaswebnet Copy and paste the contents of the logs to GitHub. We cannot access your Log Viewer URL as this is not a public page.

**Comment by isaiaswebnet** [comment]
https://matutodapraia.com.br/liquidsoap_log.json

**Comment by SlvrEagle23** [comment]
@isaiaswebnet I'm not sure if you've had a chance to work on this issue further, but the error logs are showing a fair number of problems with Liquidsoap connecting to something. I'm not sure whether the errors are with connecting to a local streaming source (i.e. Icecast/SHOUTcast) or a remote relay, or playing a remote playlist, but you should ensure that if any of these settings have been changed from their defaults that the new settings are valid and working from your server.
