### ISSUE TITLE
How does mount points work?

### ISSUE THREAD

**Issue by 7miguelsilva7** [AzuraCast/AzuraCast#1619]
How does mount point work?
I add mount points with diferent quality 32bits, 64bits, 128bits
Now I would like to know how does it work, efter add this these points what do I have to do to these points work?
Do users have to select tht desire point or it is selected automatically?

**Comment by Vaalyn** [comment]
See this excerpt from the IceCast documentation:

> Each Icecast server can house multiple broadcasts (or mountpoints) each containing a separate stream of content. A ‘mountpoint’ is a unique name on your server identifying a particular stream - it looks like a filename, such as ‘/stream.ogg’. A listener can only listen to a single mountpoint at a time. This means you can have a single Icecast server contain either multiple broadcasts with different content, or possibly the same broadcast but with streams of different bitrates or qualities. In this case each broadcast or stream is a separate mountpoint.

When using your own media player you'll have to decide which mountpoint to connect to. When using the included player on the public page of a station or the embed widget there is a dropdown where you can choose which mountpoint you want to listen.

**Comment by ErnestPH** [comment]
> How does mount point work?
> I add mount points with diferent quality 32bits, 64bits, 128bits
> Now I would like to know how does it work, efter add this these points what do I have to do to these points work?
> Do users have to select tht desire point or it is selected automatically?

As far as I know, you can play different sounds/music in each mount point.
ex. mount point 1 plays only the AutoDJ songs while mount point 2 can be a live broadcasting relay...

**Comment by 7miguelsilva7** [comment]
Dropdown where you can choose which mountpoint you want to listen it isn't showed on the public page of a station

**Comment by 7miguelsilva7** [comment]
> When using your own media player you'll have to decide which mountpoint to connect to. When using the included player on the public page of a station or the embed widget there is a dropdown where you can choose which mountpoint you want to listen.

Dropdown where you can choose which mountpoint you want to listen it isn't showed on the public page of a station

**Comment by Vaalyn** [comment]
@7miguelsilva7 Yes it is:

http://prntscr.com/ny3wn2
http://prntscr.com/ny3wyx

**Comment by 7miguelsilva7** [comment]
No, in my public page it is not showed
![pontos](https://user-images.githubusercontent.com/16270181/59048546-6a1a7b80-885c-11e9-8b69-96a9215de7bb.png)
![radio](https://user-images.githubusercontent.com/16270181/59048550-6be43f00-885c-11e9-97ae-c97596ed5356.png)

**Comment by Vaalyn** [comment]
@7miguelsilva7 You are not using the newest rolling-release version of AzuraCast. Update your installation and the dropdown will be there.

**Comment by 7miguelsilva7** [comment]
Thanks!

**Comment by Vaalyn** [comment]
> Thanks!

👍 I'll close this issue now. If you have any further questions feel free to ask.
