### ISSUE TITLE
Scheduled playlist requested songs not playing

### ISSUE THREAD

**Issue by Virusjuh** [AzuraCast/AzuraCast#1620]
Hi,

Im playing in a rotation of scheduled playlist only,
Now the request service is not possible.
He is showing all the request songs from the whole station, But the station cant play it because that song is on a other playlist.

Is it possible to show only the current playlist? 
Or to overrule, Like
Playlist a > playing - got request from playlist b > play on a
Or Playlist a > playing - show only songs playlist a

My setup at this moment
Many maps, Almost each hour another playlist.

**Comment by Vaalyn** [comment]
Even if a playlist is not scheduled to play, if the playlist is set to `Allow Requests from This Playlist` you can request songs from it to be played and they will be played according to the configuration for requests of your station. Take a look at `Request Minimum Delay (Minutes)` and `Request Last Played Threshold (Minutes)` in the `Station Profile` -> `AutoDj`

**Comment by Virusjuh** [comment]
Thanks for the answer,
But i tried already
[![Screenshot from Gyazo](https://gyazo.com/eba1fddcbc6864b6deff752783ac047c/raw)](https://gyazo.com/eba1fddcbc6864b6deff752783ac047c)
[![Screenshot from Gyazo](https://gyazo.com/32689bc3be2ee6c963fb3a0937013310/raw)](https://gyazo.com/32689bc3be2ee6c963fb3a0937013310)
Even when i set the limit of played songs to 0 he wont play any

**Comment by Virusjuh** [comment]
Between a couple request this is the log.

2019/06/04 19:08:02 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/gigi_fm/media/love/-28you_make_me_feel_like-29_a_natural_woman_-_aretha_franklin.mp3".
2019/06/04 19:09:19 [playlist_beach_party1:3] Finished with "/var/azuracast/stations/gigi_fm/media/beach party/Krept & Konan (feat. Jeremih) - Freak of the Week.mp3".
2019/06/04 19:09:19 [playlist_beach_party1:3] Prepared "/var/azuracast/stations/gigi_fm/media/beach party/Night Moves Remix - 7 Years.mp3" (RID 65).
2019/06/04 19:09:19 [rotate_6492:3] Switch to map_metadata_6427 with forgetful transition.
2019/06/04 19:09:37 [playlist_jingles:3] Finished with "/var/azuracast/stations/gigi_fm/media/jingle/gigifm_-_main_select.mp3".
2019/06/04 19:09:37 [playlist_jingles:3] Prepared "/var/azuracast/stations/gigi_fm/media/jingle/gigi_fm_-_app.mp3" (RID 16).
2019/06/04 19:09:37 [rotate_6492:3] Switch to gigi_fm_schedule_switch with forgetful transition.
2019/06/04 19:09:37 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/gigi_fm/media/beach party/Micar - Burden Down.mp3".
2019/06/04 19:09:37 [lang:3] AzuraCast Feedback Response: OK
2019/06/04 19:12:34 [playlist_beach_party1:3] Finished with "/var/azuracast/stations/gigi_fm/media/beach party/Night Moves Remix - 7 Years.mp3".
2019/06/04 19:12:34 [playlist_beach_party1:3] Prepared "/var/azuracast/stations/gigi_fm/media/beach party/Micar - Burden Down.mp3" (RID 4).
2019/06/04 19:12:34 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/gigi_fm/media/beach party/Vigiland - Let's Escape (Tom Swoon Remix).mp3".
2019/06/04 19:12:34 [lang:3] AzuraCast Feedback Response: OK


He wont record anything

**Comment by SlvrEagle23** [comment]
@Virusjuh I don't believe that, by default, scheduled playlists are requestable. Are you saying you would want to be able to request songs from that playlist, but only during the time period when it should be playing?

That's possible, but it would be a new feature request that you should submit over at [our features page](https://features.azuracast.com/).

**Comment by Virusjuh** [comment]
No let me explain a bit.
its 20:00 playlist a is playing.
i look for a request over all songs, i pick one, but that song is not on playlist it wont play. 

So for now the requester dont do anything, unless you are lucky and the scheduled media is playing and got a request from the same media map, else he wont do anything. 

Or will be nice if i can load the current media map only on scheduled time, so only the songs avalible for request are shown.

**Comment by Virusjuh** [comment]
Only beach party songs (the media map) [![Screenshot from Gyazo](https://gyazo.com/f29ae6d3b0cb360be5d13c8f354eda6b/raw)](https://gyazo.com/f29ae6d3b0cb360be5d13c8f354eda6b) 
[![Screenshot from Gyazo](https://gyazo.com/1d8d2accf3b666b6f9572a607a1af7af/raw)](https://gyazo.com/1d8d2accf3b666b6f9572a607a1af7af)

You can request from, 
If i pick a request like a disco one its not from the party media then he wont do anything, only say succeed but he isnt

**Comment by SlvrEagle23** [comment]
@Virusjuh If you go to the "Requests" page, do those requests show up as pending or as having been submitted?

**Comment by Virusjuh** [comment]
[![Screenshot from Gyazo](https://gyazo.com/57e6de5814bc6ed47dac8a6c89051c9a/raw)](https://gyazo.com/57e6de5814bc6ed47dac8a6c89051c9a)

But nothing happend

**Comment by SlvrEagle23** [comment]
@Virusjuh No, on the station management page there is a "Requests" page inside the "Utilities" section, that shows both pending requests and ones that have already been played. Let me know what that shows you.

**Comment by Virusjuh** [comment]
[![Screenshot from Gyazo](https://gyazo.com/87a04bd815623f307154242af8c3e031/raw)](https://gyazo.com/87a04bd815623f307154242af8c3e031)

Not played

**Comment by SlvrEagle23** [comment]
@Virusjuh Go to Administration, then manually run the "Every 1 Minute" task, and let me know what the debug information is showing, if anything.

**Comment by Virusjuh** [comment]
[![Screenshot from Gyazo](https://gyazo.com/2050ea0f797d3154e0bca3270e0591c7/raw)](https://gyazo.com/2050ea0f797d3154e0bca3270e0591c7)

on click [![Screenshot from Gyazo](https://gyazo.com/d42f035af4dadd58dfdececde5061cb0/raw)](https://gyazo.com/d42f035af4dadd58dfdececde5061cb0)

**Comment by SlvrEagle23** [comment]
@Virusjuh I was able to figure out the problem. While scheduled playlists are running, requests weren't being processed at all, even if new ones were submitted during that scheduled time.

I've fixed the issue in the latest code update, so if you update your installation, you should see requests start to be processed.

**Comment by Virusjuh** [comment]
i updated it 
when i click now 
[![Screenshot from Gyazo](https://gyazo.com/411dcc79eb73128d60553c879247e945/raw)](https://gyazo.com/411dcc79eb73128d60553c879247e945)

**Comment by SlvrEagle23** [comment]
@Virusjuh That's still okay...it's processing through all of the old requests. You should hear them start to play shortly.

**Comment by Virusjuh** [comment]
yes, the are playing now :) 
so just ignore the message?

**Comment by SlvrEagle23** [comment]
@Virusjuh Yes, it'll go away once the request queue is processed.

**Comment by Virusjuh** [comment]
thank you for the support :)
