### ISSUE TITLE
Liquidsoap erroneously detects moved file

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1621]
> 2019/06/03 16:00:16 [playlist_beck:1] Finished with a non-existent file?! Something may have been moved or destroyed during decoding. It is VERY dangerous, avoid it!

This is what I found in the Liquidsoap log. A custom playlist failed to play the song (the only song in the playlist) at the specified time. The playback started without problems after station restart so it seems that the file is not corrupt. 

Any idea?

**Comment by Vaalyn** [comment]
If the file is not corrupt and wasn't moved, deleted or updated while LS tried to do something with it there could (theoretically) be a hardware issue like a damaged block on the drive that could have caused it (just speculating) or in the case of a networked drive (NFS / SAMBA / etc.) a short network interruption could also cause it.

[This](https://github.com/savonet/liquidsoap/blob/master/src/sources/request_source.ml#L59) is the line from LS where this message is generated.

Did you do anything in AzuraCast while this happened?

**Comment by gammaw** [comment]
@Vaalyn our instance runs on Digital Ocean in a standard droplet. Like I said, the song started playing after station restart so the file should be ok. We weren't using touch Azuracast when this happened. We've never seen something like this before.

**Comment by SlvrEagle23** [comment]
@gammaw I'm changing the subject of this issue since the original text sounds really dire and I don't want to alarm any passersby.

If you weren't directly modifying the currently playing file (and it was already "processed", so there wasn't any work for AzuraCast to do under the hood), then it is indeed a little confusing how it found itself in that sort of limbo state, but I don't suspect that the problem is quite as dire as the error message suggests.

**Comment by gammaw** [comment]
@SlvrEagle23 ok :) It was quite scary though that the show didn't start although the file wasn't corrupt. Instead, the file got just skipped (fallbacking to the first available source), leaving the error message in my first comment. Hopefully it was once in a lifetime behavior.

**Comment by gammaw** [comment]
It occurred again. This time it was even stranger: a playlist is scheduled every Wedn at 3PM. The playlist always has exactly one song. We replaced `song1.mp3` with `song2.mp3` (`song1.mp3` was deleted from Azuracast). What happened is that `song1.mp3` was played at 2PM (why and how?) and nothing was played at 3PM (the Liquidsoap log contained the "VERY dangerous" entry at 3PM). The 2PM playback of `song1.mp3` had no trace in the Liquidsoap log. 

You'll think I'm crazy but this is how it was. Did anybody ever see anything like this?

**Comment by gammaw** [comment]
@SlvrEagle23 @Vaalyn The only thing I can think of now is that adding new playlists somehow confuses things. We use custom playlists. What happens within Azuracast when I create a new custom playlist but I don't yet do anything with it in the Liquidsoap configuration? I'm asking because we did it on the day when the "very dangerous" error happened. 

I know it's a mysterious error but it's critical for us because it causes that scheduled shows won't start and we have no idea why. It seems to be one of those "heisen bugs" because I can't reproduce it at all and it occurs super rarely.

**Comment by gammaw** [comment]
Happened again with a v0.9.9, #ff7e44a installation. The file is apparently not corrupted nor moved, after restart the playback started normally.

**Comment by gammaw** [comment]
Sorry guys, I shouldn't be bombing you with this, it's most probably a Liquidsoap issue. I'll try upstream.

**Comment by Vaalyn** [comment]
Hey, v0.9.9 is relatively old now. With v0.10.2 the newest Liquidsoap version 1.4.2 has been included in AzuraCast. You might want to update to that version first and check if it happens again.

**Comment by gammaw** [comment]
@Vaalyn thanks. We're in the process of updating but it takes a while to validate for regression. AC v0.9.9 has LS v1.4.1 which is not very old, but yes, the new one may not have it hopefully.

**Comment by gammaw** [comment]
Did anyone see this in the log recently (`Finished with a non-existent file?! Something may have been moved or destroyed during decoding. It is VERY dangerous, avoid it!`)? We had it again, after 1 year. We're running LS 1.4.2.
