### ISSUE TITLE
Title en Streamers

### ISSUE THREAD

**Issue by enigmathion** [AzuraCast/AzuraCast#1622]
The metadata in the live broadcast is not updated, the player shows the last song playing and then stalls in the last second!

**Comment by Vaalyn** [comment]
Please include more details in you issue report. Use the issue template for reporting bugs and fill in the requested information.

**Comment by enigmathion** [comment]
Good morning, the problem I told you is this.
When a Streamer is connected through the AutoDJ service, it should change the display name to the configured one (Image 01), but it does not do so, it keeps the last issue that it reproduced without advancing. (Image 02). I take this to tell you that if you need to finish translating into Spanish the system count on me without any kind of interest!
![01](https://user-images.githubusercontent.com/42680070/58892659-01e56180-86c5-11e9-8d16-5ac6c116c238.jpg)
![02](https://user-images.githubusercontent.com/42680070/58892660-01e56180-86c5-11e9-8e87-c55463090e57.jpg)

**Comment by Vaalyn** [comment]
If I didn't misunderstand you then there is already a [feature request](https://features.azuracast.com/suggestions/39891/add-now-streaming-dj-on-the-frontend-player) for showing the currently streaming DJ.

Regarding the song being "stuck" like in your screenshot. When your DJ is connected do you send any metadata to AzuraCast? If there is no metadata from your DJ then this is normal. Also related to #867.

**Comment by Vaalyn** [comment]
Closing the issue as there has been no reply in ~1 month and there is already a feature request for showing the DJ name. Regarding the "stuck songs" this is a known issue please follow the issue I mentioned for further updates to that.
