### ISSUE TITLE
Web API not working correctly

### ISSUE THREAD

**Issue by mikedorst** [AzuraCast/AzuraCast#1623]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
Web API does not seem to function. Only /nowplaying seems to function.

**To Reproduce**
Can be reproduced on your own demo server. 

1. Create an API key (f1dd983b3d925e47:3d11546940d4ea2440f4457e409f12e9)
2. Authorize on the website with the API key created.
3. Try to use any of the calls, all of them do not function except /nowplaying

**Comment by ErnestPH** [comment]
It works ok in my case… how did you send the request?
Should be like this...

GET the URL
X-API-Key: your API Key

**Comment by mikedorst** [comment]
I guess this can be closed? The requests work fine if I call them through a http post/get call. But I was talking about the buttons on the website that don't work.

**Comment by ErnestPH** [comment]
You mean the instructions? #1592
