### ISSUE TITLE
Scrollbar showing / hiding constantly on playlist edit source page in smaller window sizes

### ISSUE THREAD

**Issue by davchy** [AzuraCast/AzuraCast#1625]
This is how the playlist editing page behaves after clock implementation. I haven't noticed it elsewhere yet. Tested at 1280x1024 on a 17-inch monitor; Google Chrome 74.0.3729.169. See video.
https://youtu.be/pE8m-vUif58

**Comment by Vaalyn** [comment]
Could reproduce this with Chrome on macOS 10.14.3 in a smaller browser window. For some reason the scrollbar is showing up when the clock "ticks".

**Comment by SlvrEagle23** [comment]
What even is this?

I'll investigate and get it fixed, it is indeed quite annoying.

**Comment by ErnestPH** [comment]
> This is how the playlist editing page behaves after clock implementation. I haven't noticed it elsewhere yet. Tested at 1280x1024 on a 17-inch monitor; Google Chrome 74.0.3729.169. See video.
> https://youtu.be/pE8m-vUif58

Just curious how to implement the clock? is there a setting for it?

**Comment by SlvrEagle23** [comment]
@ErnestPH Update to the latest rolling-release version to get it :)

**Comment by ErnestPH** [comment]
Oh Thanks @SlvrEagle23
