### ISSUE TITLE
Listeners by station incorrect data (?)

### ISSUE THREAD

**Issue by mikedorst** [AzuraCast/AzuraCast#1628]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
The chart that displays listeners per station seems to display incorrect data for me? I am not sure if I am doing something wrong of if it's working as intended but it looks a bit weird.

**Screenshots**
June 4 says Vanilla Unicorn is 0.88 but in the listeners tab it said 37 unique listeners that day.
![image](https://user-images.githubusercontent.com/27761242/58922516-7a870500-873b-11e9-8cd4-946073e8b562.png)
![image](https://user-images.githubusercontent.com/27761242/58922533-9ab6c400-873b-11e9-95da-0fac0c598c51.png)

I also noticed how "Epic's Station" is not on the chart but on the 4th of June it had 14 unique listeners
![image](https://user-images.githubusercontent.com/27761242/58922550-b1f5b180-873b-11e9-8f2a-d70a1d85db2d.png)

Same for other stations
![image](https://user-images.githubusercontent.com/27761242/58922610-f8e3a700-873b-11e9-9a75-bad4fea59334.png)
![image](https://user-images.githubusercontent.com/27761242/58922621-026d0f00-873c-11e9-8f88-bbcfc14b2fd2.png)
![image](https://user-images.githubusercontent.com/27761242/58922648-1c0e5680-873c-11e9-8930-96915c605746.png)

**Device(s):**
Deskptop
Windows 10
Chrome
74.0.3729.169

**Comment by SlvrEagle23** [comment]
@mikedorst The listener count shown in the statistics is the average listener count across the entire day, as a sum total of each measurement point (15 seconds or less apart from each other) added together and averaged.

I can definitely see the value in tracking the sum total of unique listeners across a day, but our statistics don't currently do this. It may be an excellent candidate for a [new feature request](https://features.azuracast.com/).

**Comment by mikedorst** [comment]
Submitted the request! Thank you for answering.
