### ISSUE TITLE
Song Request Time Incorrect. Showing 4 hours ahead.....

### ISSUE THREAD

**Issue by pwrj** [AzuraCast/AzuraCast#1629]
Song Requests Time Showing 4 hours ahead despite server time being correctly set. Why?

**Additional context**

<img width="1613" alt="Screen Shot 2019-06-04 at 9 01 47 PM" src="https://user-images.githubusercontent.com/7035452/58923108-34667d00-870c-11e9-97e0-e0f80f3b5eb4.png">
<img width="193" alt="Screen Shot 2019-06-04 at 9 01 09 PM" src="https://user-images.githubusercontent.com/7035452/58923109-34667d00-870c-11e9-81c9-eec571d6d05e.png">
<img width="384" alt="Screen Shot 2019-06-04 at 9 00 23 PM" src="https://user-images.githubusercontent.com/7035452/58923110-34667d00-870c-11e9-9e29-dce30c1413f4.png">

**Comment by SlvrEagle23** [comment]
@pwrj Looks like we missed a spot in converting everything over to "Station Time"; that's still showing UTC on the requests themselves. I'll have that fixed shortly.

**Comment by pwrj** [comment]
> @pwrj Looks like we missed a spot in converting everything over to "Station Time"; that's still showing UTC on the requests themselves. I'll have that fixed shortly.

Thanks @SlvrEagle23!!

**Comment by SlvrEagle23** [comment]
@pwrj In the process of investigating this issue, I found a number of other places in station reports that were incorrectly showing UTC time instead of the proper localized station time. This has now been fixed globally for station pages, so you should now see proper times across the board.

**Comment by pwrj** [comment]
> @pwrj In the process of investigating this issue, I found a number of other places in station reports that were incorrectly showing UTC time instead of the proper localized station time. This has now been fixed globally for station pages, so you should now see proper times across the board.

@SlvrEagle23 Yes sir. All fixed and thank you!!
