### ISSUE TITLE
shoutcast registration

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#163]
After the station is registered succesfuly at shoutcast  and is showing  up en public availabe,
this happens when stations are restarted after a update.

 " Listing Status:	Stream is currently up but requires registration in the SHOUTcast Directory.
Listeners are allowed and the stream will act like it is private until resolved "

**Comment by SlvrEagle23** [comment]
@surihost Ah it's not saving the registration key. Will work on that!

**Comment by surihost** [comment]
Hello,

Is this issue already solved?
