### ISSUE TITLE
No more support for UBUNTU

### ISSUE THREAD

**Issue by garfieldoike** [AzuraCast/AzuraCast#1630]
**Using Docker installation method**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by garfieldoike** [comment]
![01](https://user-images.githubusercontent.com/26382849/58962487-a62cde00-8781-11e9-8606-5641aa9a4853.png)
I started using AzuraCast, after many compliments of update, and I migrated. Right now apparently no more fornese more update for UBUNTU

**Comment by Vaalyn** [comment]
Please do not ignore the issue template when submitting issues!
We need that information to be able to effectively help you. We don't have the time to ask for every piece of information that you should just provide in that template separately.

From your screenshot and description I have no idea what the issue could be. When posting such screenshots please make sure to post them in english.

> Right now apparently no more fornese more update for UBUNTU

I don't know what you mean with that. Please clarify.

I'll re-open the issue when after you provided us with the necessary information to proceed with this issue.
