### ISSUE TITLE
Server is stuttering when Presenter connects.

### ISSUE THREAD

**Issue by ItsHarryUK** [AzuraCast/AzuraCast#1634]
**Using Docker installation method**
 Yes

**Host Operating System**
 Ubuntu 18.04, Linux

**Describe the bug**
 I am having problems when a Presenter Connects it makes the audio stutter alot and I go on a test server goes fine I done a server restart and a main vps restart too

**To Reproduce**

**Expected behavior**
 N/A

**Relevant Logs**
 /var/azuracast/stations/tnradio/config/shoutcast.log

**Screenshots**

**Device(s):**
 - Device:  Eveything
 - OS: Eveything
 - Browser:  Everything
 - Version:  All

**Additional context**

**Comment by ItsHarryUK** [comment]
Its my first time doing this sorry if wrong.

**Comment by SlvrEagle23** [comment]
@ItsHarryUK There is a setting called "Advanced: DJ/Streamer Buffer Time" on the "AutoDJ" tab of the station's profile. You should try increasing that setting, then restarting the station to apply changes, until you find a setting that is high enough to prevent the buffering effect.

**Comment by ItsHarryUK** [comment]
Thank You for that it fixed now.
