### ISSUE TITLE
LiquidSoap return ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#1639]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu Linux 18.04.2
**Describe the bug**
Unable to view the logs, returns a error code in the console:
net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)
**To Reproduce**
- Load up a server
- Click on Logs
- View LiquidSoap logs

**Expected behavior**
Logs to show up properly. 
**Relevant Logs**
[Picture of the console error](https://puu.sh/DDoPz.png) 
When checking the line it breaks on, its `            log_modal_contents.text('Error:'+xhr.responseJSON.message);`

**Screenshots**
Check above
**Device(s):**
 - Device: Desktop 
 - OS: Windows 10 
 - Browser: Brave
 - Version: Latest

**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch In a minute, the web containers should update and the issue should be resolved.

**Comment by SC2Mitch** [comment]
Resolved in the last update, thanks @SlvrEagle23
