### ISSUE TITLE
Enable SFTP Access through Docker

### ISSUE THREAD

**Issue by darkjedeye** [AzuraCast/AzuraCast#164]
Hey there... this is a suggestion. Would you be able to allow ssh access and ftp access in the near future, so that those of us who know how, can modify the server a bit ti include a station home page or even include whole separate site to deal with he stations site. I have been trying my damnedest, but have realized that i have quite a bit to learn about docker.... (believe me i am about to start studying....)

**Comment by SlvrEagle23** [comment]
@darkjedeye Here would be the command to run an SFTP server accessible as `sftp://azuracast:azuracast@docker:2222`:

```
docker run --rm \
    -v azuracast_station_data:/home/azuracast/stations \
    -p 2222:22 atmoz/sftp:alpine \
    azuracast:azuracast:::stations
```

I would include this as a utility script, but it's only encouraged to either briefly open the SFTP port to do quick transactions and then immediately remove it, or to assign a more secure, app-specific password (the second "azuracast" in the arguments above).

**Comment by ruLait** [comment]
@SlvrEagle23 probably this is a stupid question, but how to remove SFTP-server?

**Comment by SlvrEagle23** [comment]
If you ran the docker command with the `--rm` flag (as above), just hitting Ctrl+C after you're done should also terminate the container.

If not, you can list all running processes using `docker ps`, find the container ID (the first column) of the sftp container, and run `docker rm containerid` (where containerid is that hash).
