### ISSUE TITLE
Media Upload Error

### ISSUE THREAD

**Issue by danyalsaleemqureshi** [AzuraCast/AzuraCast#1640]
Unable to Update Media, This happen everyday, Need to clear cache, re update , restart then its working fine after 1 day again same issue: I am using Docker in Ubuntu, Please Tell me Permanent Fix

[2019-06-08 20:53:02] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-06-08 20:53:02] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-06-08 20:53:07] AzuraCast.INFO: Running message queue processor for 300 seconds. [] []
203.101.182.110 - - [08/Jun/2019:20:53:11 +0000] "GET /station/8/files/upload?csrf=StnXueZpqK&file=&searchPhrase=&flowChunkNumber=1&flowChunkSize=1048576&flowCurrentChunkSize=1048576&flowTotalSize=3714402&flowIdentifier=3714402-young-desi-paindu-pakium-com-4songs-pkmp3&flowFilename=young-desi-paindu-pakium-com-4songs-pk.mp3&flowRelativePath=young-desi-paindu-pakium-com-4songs-pk.mp3&flowTotalChunks=3 HTTP/1.1" 204 0 "http://ukradio.drifthosters.com/station/8/files" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "-"
203.101.182.110 - - [08/Jun/2019:20:53:11 +0000] "GET /station/8/files/upload?csrf=StnXueZpqK&file=&searchPhrase=&flowChunkNumber=3&flowChunkSize=1048576&flowCurrentChunkSize=1617250&flowTotalSize=3714402&flowIdentifier=3714402-young-desi-paindu-pakium-com-4songs-pkmp3&flowFilename=young-desi-paindu-pakium-com-4songs-pk.mp3&flowRelativePath=young-desi-paindu-pakium-com-4songs-pk.mp3&flowTotalChunks=3 HTTP/1.1" 204 0 "http://ukradio.drifthosters.com/station/8/files" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "-"
203.101.182.110 - - [08/Jun/2019:20:53:11 +0000] "GET /station/8/files/upload?csrf=StnXueZpqK&file=&searchPhrase=&flowChunkNumber=2&flowChunkSize=1048576&flowCurrentChunkSize=1048576&flowTotalSize=3714402&flowIdentifier=3714402-young-desi-paindu-pakium-com-4songs-pkmp3&flowFilename=young-desi-paindu-pakium-com-4songs-pk.mp3&flowRelativePath=young-desi-paindu-pakium-com-4songs-pk.mp3&flowTotalChunks=3 HTTP/1.1" 204 0 "http://ukradio.drifthosters.com/station/8/files" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "-"
2019/06/08 20:53:11 [crit] 61#61: *32236 mkdir() "/tmp/azuracast_nginx_client/4" failed (2: No such file or directory), client: 203.101.182.110, server: localhost, request: "POST /station/8/files/upload HTTP/1.1", host: "ukradio.drifthosters.com", referrer: "http://ukradio.drifthosters.com/station/8/files"
2019/06/08 20:53:11 [crit] 61#61: *32232 mkdir() "/tmp/azuracast_nginx_client/5" failed (2: No such file or directory), client: 203.101.182.110, server: localhost, request: "POST /station/8/files/upload HTTP/1.1", host: "ukradio.drifthosters.com", referrer: "http://ukradio.drifthosters.com/station/8/files"
2019/06/08 20:53:11 [crit] 61#61: *32234 mkdir() "/tmp/azuracast_nginx_client/6" failed (2: No such file or directory), client: 203.101.182.110, server: localhost, request: "POST /station/8/files/upload HTTP/1.1", host: "ukradio.drifthosters.com", referrer: "http://ukradio.drifthosters.com/station/8/files"
203.101.182.110 - - [08/Jun/2019:20:53:12 +0000] "POST /station/8/files/upload HTTP/1.1" 500 588 "http://ukradio.drifthosters.com/station/8/files" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "-"
Jun  8 20:53:12 d7912e4c38bd php-fpm[58]: [WARNING] [pool www] server reached max_children setting (3), consider raising it
203.101.182.110 - - [08/Jun/2019:20:53:12 +0000] "POST /station/8/files/list HTTP/1.1" 200 62 "http://ukradio.drifthosters.com/station/8/files" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "-"
203.101.182.110 - - [08/Jun/2019:20:53:14 +0000] "POST /station/8/files/upload HTTP/1.1" 500 588 "http://ukradio.drifthosters.com/station/8/files" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "-"
root@ukradio:~#

**Comment by SlvrEagle23** [comment]
@danyalsaleemqureshi This should be fixed as of the latest update; run:

```
./docker.sh update-self
./docker.sh update
```

to pull down the latest image.

**Comment by danyalsaleemqureshi** [comment]
Sure Thanks let me try

**Comment by danyalsaleemqureshi** [comment]
whats the method is to update same in tradational bare metal install? I am running 2 servers.

**Comment by SlvrEagle23** [comment]
@danyalsaleemqureshi This error shouldn't have affected non-Docker installations, though the method of updating would be, as a sudo-capable user:

```
cd /var/azuracast/www
./update.sh
```

**Comment by danyalsaleemqureshi** [comment]
> @danyalsaleemqureshi This should be fixed as of the latest update; run:
> 
> ```
> ./docker.sh update-self
> ./docker.sh update
> ```
> 
> to pull down the latest image.

Hello, Dear Same after Update to New version. Please Check

**Comment by danyalsaleemqureshi** [comment]
203.101.182.110 - - [14/Jun/2019:09:25:23 +0000] "GET /static/dist/radio_player-1f9ed56920.js HTTP/1.1" 304 0 "http://ukradio.drifthosters.com/station/1/profile" "Mozilla/5.0 (Windows NT 6.1; Win6$
203.101.182.110 - - [14/Jun/2019:09:25:23 +0000] "GET /static/dist/lib/moment/locales-473153bad8.min.js HTTP/1.1" 304 0 "http://ukradio.drifthosters.com/station/1/profile" "Mozilla/5.0 (Windows NT$
203.101.182.110 - - [14/Jun/2019:09:25:23 +0000] "GET /static/dist/lib/clipboard/clipboard-f06c52bfdd.min.js HTTP/1.1" 304 0 "http://ukradio.drifthosters.com/station/1/profile" "Mozilla/5.0 (Windo$
203.101.182.110 - - [14/Jun/2019:09:25:23 +0000] "GET /static/dist/lib/fancybox/jquery-49a6b4d019.fancybox.min.js HTTP/1.1" 304 0 "http://ukradio.drifthosters.com/station/1/profile" "Mozilla/5.0 ($
203.101.182.110 - - [14/Jun/2019:09:25:23 +0000] "GET /api/nowplaying/1 HTTP/1.1" 200 2405 "http://ukradio.drifthosters.com/station/1/profile" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit$
203.101.182.110 - - [14/Jun/2019:09:25:23 +0000] "GET /api/station/1/status?_=1560504329208 HTTP/1.1" 200 59 "http://ukradio.drifthosters.com/station/1/profile" "Mozilla/5.0 (Windows NT 6.1; Win64$
203.101.182.110 - - [14/Jun/2019:09:25:24 +0000] "GET /static/img/generic_song.jpg HTTP/1.1" 200 827501 "http://ukradio.drifthosters.com/station/1/profile" "Mozilla/5.0 (Windows NT 6.1; Win64; x64$
203.101.182.110 - - [14/Jun/2019:09:25:28 +0000] "GET /api/station/1/status?_=1560504329209 HTTP/1.1" 200 59 "http://ukradio.drifthosters.com/station/1/profile" "Mozilla/5.0 (Windows NT 6.1; Win64$
203.101.182.110 - - [14/Jun/2019:09:25:39 +0000] "GET /api/nowplaying/1 HTTP/1.1" 200 2405 "http://ukradio.drifthosters.com/station/1/profile" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit$
203.101.182.110 - - [14/Jun/2019:09:25:44 +0000] "GET /api/station/1/status?_=1560504329210 HTTP/1.1" 200 59 "http://ukradio.drifthosters.com/station/1/profile" "Mozilla/5.0 (Windows NT 6.1; Win64$
172.69.111.140 - - [14/Jun/2019:09:25:50 +0000] "GET /radio/8000/radio.mp3 HTTP/1.1" 200 295416 "https://all4masti.com/radio.html" "Mozilla/5.0 (Linux; Android 4.4.2; LG-F320K Build/KOT49I.F320K22$
203.101.182.110 - - [14/Jun/2019:09:25:54 +0000] "GET /api/nowplaying/1 HTTP/1.1" 200 2405 "http://ukradio.drifthosters.com/station/1/profile" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit$
203.101.182.110 - - [14/Jun/2019:09:25:55 +0000] "GET /station/1/files HTTP/1.1" 200 41484 "http://ukradio.drifthosters.com/station/1/profile" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit$
203.101.182.110 - - [14/Jun/2019:09:25:55 +0000] "GET /static/js/bootgrid/jquery.bootgrid.min.css HTTP/1.1" 200 3687 "http://ukradio.drifthosters.com/station/1/files" "Mozilla/5.0 (Windows NT 6.1;$
203.101.182.110 - - [14/Jun/2019:09:25:55 +0000] "GET /static/dist/bootgrid-acbc545ec1.js HTTP/1.1" 200 2323 "http://ukradio.drifthosters.com/station/1/files" "Mozilla/5.0 (Windows NT 6.1; Win64; $
203.101.182.110 - - [14/Jun/2019:09:25:55 +0000] "GET /static/dist/lib/flowjs/flow-8c41da7745.min.js HTTP/1.1" 200 15143 "http://ukradio.drifthosters.com/station/1/files" "Mozilla/5.0 (Windows NT $
203.101.182.110 - - [14/Jun/2019:09:25:55 +0000] "GET /static/js/bootgrid/jquery.bootgrid.updated.js HTTP/1.1" 200 70608 "http://ukradio.drifthosters.com/station/1/files" "Mozilla/5.0 (Windows NT $
203.101.182.110 - - [14/Jun/2019:09:25:55 +0000] "POST /station/1/files/directories HTTP/1.1" 200 21 "http://ukradio.drifthosters.com/station/1/files" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) App$
203.101.182.110 - - [14/Jun/2019:09:25:55 +0000] "POST /station/1/files/list HTTP/1.1" 200 639 "http://ukradio.drifthosters.com/station/1/files" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebK$
203.101.182.110 - - [14/Jun/2019:09:25:56 +0000] "GET /api/station/1/art/c2b4b28b1d5e6d70817b2e61.jpg HTTP/1.1" 302 5 "http://ukradio.drifthosters.com/station/1/files" "Mozilla/5.0 (Windows NT 6.1$
203.101.182.110 - - [14/Jun/2019:09:25:59 +0000] "POST /station/1/files/directories HTTP/1.1" 200 21 "http://ukradio.drifthosters.com/station/1/files" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) App$
Jun 14 09:26:01 be6880847156 CRON[39649]: (root) CMD (       sleep 45; /usr/local/bin/cron_task azuracast_cli sync:run nowplaying)
Jun 14 09:26:01 be6880847156 CRON[39650]: (root) CMD (       sleep 15; /usr/local/bin/cron_task azuracast_cli sync:run nowplaying)
Jun 14 09:26:01 be6880847156 CRON[39651]: (root) CMD (       /usr/local/bin/cron_task azuracast_cli sync:run short)
Jun 14 09:26:01 be6880847156 CRON[39658]: (root) CMD (       /usr/local/bin/cron_task azuracast_cli sync:run nowplaying)
Jun 14 09:26:01 be6880847156 CRON[39652]: (root) CMD (       sleep 30; /usr/local/bin/cron_task azuracast_cli sync:run nowplaying)
203.101.182.110 - - [14/Jun/2019:09:26:38 +0000] "GET /station/1/files/upload?csrf=Acn2NcdEbX&file=&searchPhrase=&flowChunkNumber=2&flowChunkSize=1048576&flowCurrentChunkSize=1048576&flowTotalSize$
203.101.182.110 - - [14/Jun/2019:09:26:38 +0000] "GET /station/1/files/upload?csrf=Acn2NcdEbX&file=&searchPhrase=&flowChunkNumber=1&flowChunkSize=1048576&flowCurrentChunkSize=1048576&flowTotalSize$
203.101.182.110 - - [14/Jun/2019:09:26:38 +0000] "GET /station/1/files/upload?csrf=Acn2NcdEbX&file=&searchPhrase=&flowChunkNumber=3&flowChunkSize=1048576&flowCurrentChunkSize=1048576&flowTotalSize$
203.101.182.110 - - [14/Jun/2019:09:26:39 +0000] "POST /station/1/files/list HTTP/1.1" 499 0 "http://ukradio.drifthosters.com/station/1/files" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit$
203.101.182.110 - - [14/Jun/2019:09:26:39 +0000] "POST /station/1/files/list HTTP/1.1" 200 639 "http://ukradio.drifthosters.com/station/1/files" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebK$
203.101.182.110 - - [14/Jun/2019:09:26:41 +0000] "POST /station/1/files/upload HTTP/1.1" 500 588 "http://ukradio.drifthosters.com/station/1/files" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWe$
203.101.182.110 - - [14/Jun/2019:09:26:43 +0000] "POST /station/1/files/upload HTTP/1.1" 500 588 "http://ukradio.drifthosters.com/station/1/files" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWe$
203.101.182.110 - - [14/Jun/2019:09:26:44 +0000] "POST /station/1/files/upload HTTP/1.1" 500 588 "http://ukradio.drifthosters.com/station/1/files" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWe$
Jun 14 09:26:49 be6880847156 php-fpm[58]: [WARNING] [pool www] child 39603 said into stderr: "[2019-06-14 09:26:49] AzuraCast.INFO: New message of type App\Message\UpdateNowPlayingMessage added to$
172.22.0.4 - - [14/Jun/2019:09:26:49 +0000] "POST /api/internal/2/feedback HTTP/1.1" 200 12 "-" "curl/7.58.0" "-"
162.158.150.70 - - [14/Jun/2019:09:26:53 +0000] "GET /radio/8000/radio.mp3 HTTP/1.1" 200 597813 "https://all4masti.com/radio.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KH$
172.69.244.156 - - [14/Jun/2019:09:26:57 +0000] "GET /radio/8000/radio.mp3 HTTP/1.1" 200 1282107 "https://all4masti.com/radio.html" "Mozilla/5.0 (Linux; Android 7.1.1; CPH1729) AppleWebKit/537.36 $
Jun 14 09:27:01 be6880847156 CRON[39755]: (root) CMD (       sleep 15; /usr/local/bin/cron_task azuracast_cli sync:run nowplaying)
Jun 14 09:27:01 be6880847156 CRON[39757]: (root) CMD (       /usr/local/bin/cron_task azuracast_cli sync:run nowplaying)
Jun 14 09:27:01 be6880847156 CRON[39756]: (root) CMD (       sleep 30; /usr/local/bin/cron_task azuracast_cli sync:run nowplaying)
Jun 14 09:27:01 be6880847156 CRON[39758]: (root) CMD (       sleep 45; /usr/local/bin/cron_task azuracast_cli sync:run nowplaying)
Jun 14 09:27:01 be6880847156 CRON[39764]: (root) CMD (       /usr/local/bin/cron_task azuracast_cli sync:run short)

**Comment by danyalsaleemqureshi** [comment]
2019/06/14 09:45:47 [crit] 61#61: *40134 mkdir() "/tmp/azuracast_nginx_client/0" failed (2: No such file or directory), client: 203.101.182.110, server: localhost, request: "POST /station/1/files/upload HTTP/1.1", host: "ukradio.drifthosters.com", referrer: "http://ukradio.drifthosters.com/station/1/files"
2019/06/14 09:45:47 [crit] 61#61: *40153 mkdir() "/tmp/azuracast_nginx_client/1" failed (2: No such file or directory), client: 203.101.182.110, server: localhost, request: "POST /station/1/files/upload HTTP/1.1", host: "ukradio.drifthosters.com", referrer: "http://ukradio.drifthosters.com/station/1/files"
[2019-06-14 09:45:47] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []
2019/06/14 09:45:47 [crit] 61#61: *40167 mkdir() "/tmp/azuracast_nginx_client/2" failed (2: No such file or directory), client: 203.101.182.110, server: localhost, request: "POST /station/1/files/upload HTTP/1.1", host: "ukradio.drifthosters.com", referrer: "http://ukradio.drifthosters.com/station/1/files"
[2019-06-14 09:46:01] AzuraCast.INFO: Running 1-minute sync task [] []
[2019-06-14 09:46:01] AzuraCast.INFO: Running Now Playing sync task [] []

**Comment by danyalsaleemqureshi** [comment]
@SlvrEagle23

**Comment by SlvrEagle23** [comment]
@danyalsaleemqureshi This should be fixed as of the latest Docker image update.

**Comment by danyalsaleemqureshi** [comment]
203.101.182.110 - - [23/Jun/2019:14:15:39 +0000] "GET /station/11/files/upload?csrf=UmD3TVlIw2&file=&searchPhrase=&flowChunkNumber=1&flowChunkSize=1048576&flowCurrentChunkSize=1048576&flowTotalSiz$
203.101.182.110 - - [23/Jun/2019:14:15:39 +0000] "GET /station/11/files/upload?csrf=UmD3TVlIw2&file=&searchPhrase=&flowChunkNumber=3&flowChunkSize=1048576&flowCurrentChunkSize=1048576&flowTotalSiz$
Jun 23 14:15:40 034fa7cb5e9e php-fpm[56]: [WARNING] [pool www] server reached max_children setting (3), consider raising it


@SlvrEagle23 Again Issue, Same unable to upload media.

**Comment by SlvrEagle23** [comment]
@danyalsaleemqureshi That section of the log doesn't really shed much light on the cause of the issue. Are you getting any errors in the web console when uploading files?

**Comment by danyalsaleemqureshi** [comment]
@SlvrEagle23 Check This Hope this works:

[2019-06-24 16:13:16] AzuraCast.INFO: Running Now Playing sync task [] []
2019/06/24 16:13:21 [crit] 59#59: *188910 mkdir() "/tmp/azuracast_nginx_client/3" failed (2: No such file or directory), client: 203.101.182.110, server: localhost, request: "POST /station/2/files/upload HTTP/1.1", host: "ukradio.drifthosters.com", referrer: "http://ukradio.drifthosters.com/station/2/files"
2019/06/24 16:13:21 [crit] 59#59: *188904 mkdir() "/tmp/azuracast_nginx_client/4" failed (2: No such file or directory), client: 203.101.182.110, server: localhost, request: "POST /station/2/files/upload HTTP/1.1", host: "ukradio.drifthosters.com", referrer: "http://ukradio.drifthosters.com/station/2/files"
2019/06/24 16:13:21 [crit] 59#59: *188899 mkdir() "/tmp/azuracast_nginx_client/5" failed (2: No such file or directory), client: 203.101.182.110, server: localhost, request: "POST /station/2/files/upload HTTP/1.1", host: "ukradio.drifthosters.com", referrer: "http://ukradio.drifthosters.com/station/2/files"

**Comment by SlvrEagle23** [comment]
@danyalsaleemqureshi This should have definitely been fixed as of the last Docker image update. You should try running:

```
./docker.sh update-self
./docker.sh update
```

...again just for good measure.

**Comment by danyalsaleemqureshi** [comment]
@SlvrEagle23  I have updated last time as well, can you try to reach on root cause?

**Comment by SlvrEagle23** [comment]
@danyalsaleemqureshi When did you last update? I have already released a patch that addresses the root cause of this problem on the Docker image, which is why I'm asking.

**Comment by danyalsaleemqureshi** [comment]
@SlvrEagle23  10 Days ago, When You asked me to update, I did then I guess after that there was an automated update from azuracast, like 7 8 days ago? Updated that too, but if u updated anything in last 5-6 days, that is not applied by me.

**Comment by SlvrEagle23** [comment]
@danyalsaleemqureshi The last fix was released about 5 days ago. The initial fix didn't quite solve the issue so I had to apply a second one, but once you update it should be resolved.

**Comment by danyalsaleemqureshi** [comment]
aLRIGHT dONE Thanks. and 1 more thing again, this type of issue wont exist on bare metal right?

**Comment by SlvrEagle23** [comment]
@danyalsaleemqureshi This specific issue doesn't, but that's only due to a difference in configuration between the two installation types.
