### ISSUE TITLE
Radio not playing in Public Pages anymore for Safari Mac only

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#1641]
**Using Docker installation method**
Yes latest build #4e11d97

**Host Operating System**
uBuntu

**Describe the bug**
Public radio not plying in Safari. Works ok in Chrome and other Browser. 
However, the embedded web player works in safari…

**To Reproduce**
1. Go to Public page radio on your Safari Mac
2. Won't play. 
Error in console
[Error] Failed to load resource: the server responded with a status of 404 () (bootstrap.bundle.min.js.map, line 0)

**Expected behavior**
Should play the music

**Relevant Logs**
No errors in log

**Device(s):**
 Mac Mojave Safari browser

**Comment by uppula11718700** [comment]
it is also not playing in windows and andriod devices too 
NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable.
The above error is showing up in the console.

**Comment by SlvrEagle23** [comment]
@ErnestPH What is the output format of your mount point? Different browsers have built-in support for different audio formats, which could explain why Safari is having trouble.

**Comment by ErnestPH** [comment]
It's just the default 128kbps MP3… 

It only doesn't work in Safari. It even play in Opera Mac… maybe @Vaalyn can investigate for the Mac? :) Thanks guys!

**Comment by Vaalyn** [comment]
@ErnestPH I tried reproducing the problem on my mac by visiting the public page of the demo installation with Safari 12.0.3 (14606.4.5) but the 128kbps MP3 stream play without any issues for me.

@uppula11718700 Would you mind posting a link to your public page so that I can check with my machine?

**Comment by ErnestPH** [comment]
@Vaalyn I guess this is an issue for the new Mojave safari 12.1.1… But it's ok. I don't use the safari for public pages anyway… thanks!

**Comment by Felix-Kfz24** [comment]
I've updated my Mojave to the newest version so that I could test again with Safari 12.1.1 but I still have no problems playing the 128kbps MP3 stream on the public page.

**Comment by Vaalyn** [comment]
I've updated my Mojave to the newest version so that I could test again with Safari 12.1.1 but I still have no problems playing the 128kbps MP3 stream on the public page.

**Comment by ErnestPH** [comment]
Ok. I tried in again on Mac Safari this time in Private mode… and it's working. So I guess this can be close? Unless @uppula11718700 is still having issues in Windows. Thanks!

**Comment by Vaalyn** [comment]
@uppula11718700 If you still experience this problem please create a new issue with as much information about you OS / Browser and the setup of the stream so that we can try to reproduce the problem.

I'll close this issue now as the streams are working on macOS Safari.
