### ISSUE TITLE
Docker installation error

### ISSUE THREAD

**Issue by NurLutix** [AzuraCast/AzuraCast#1643]
Hey,
I just wanted to install AzuraCast on Ubuntu 16.04 via Docker. However, I get the following error: 

ERROR: for azuracast_mariadb_1  Cannot start service mariadb: OCI runtime create                                                                                                                                                              failed: container_linux.go:345: starting container process caused "process_linu                                                                                                                                                             x.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to r                                                                                                                                                             Creating azuracast_redis_1    ... error
4380bd7ad62f76e616\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unk                                                                                                                                                             nown

ERROR: for azuracast_redis_1  Cannot start service redis: OCI runtime create fai                                                                                                                                                             led: container_linux.go:345: starting container process caused "process_linux.go                                                                                                                                                             :424: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootf                                                                                                                                                             Creating azuracast_influxdb_1 ... error
2e34b166eac71b\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for azuracast_influxdb_1  Cannot start service influxdb: OCI runtime crea                                                                                                                                                             te failed: container_linux.go:345: starting container process caused "process_li                                                                                                                                                             nux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to                                                                                                                                                              rootfs \\\"/var/lib/docker/vfs/dir/becd95c8f82165799243131a41327c3ca305e0b28055                                                                                                                                                             315d990e893fe6ca1cbc\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": u                                                                                                                                                             Creating azuracast_stations   ... error

ERROR: for azuracast_stations  Cannot start service stations: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/77036708597d80b43f98ef1c2c52cd904518d3977c33fb09cda88345f8e0a852\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for mariadb  Cannot start service mariadb: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/69a2c1071112324b045547173371fa8d8e0a1ed35961764380bd7ad62f76e616\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for redis  Cannot start service redis: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/d19afa6fab4b1d55c01acb2c5e75114132c622aa62ebabb0032e34b166eac71b\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for influxdb  Cannot start service influxdb: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/becd95c8f82165799243131a41327c3ca305e0b28055315d990e893fe6ca1cbc\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for stations  Cannot start service stations: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/77036708597d80b43f98ef1c2c52cd904518d3977c33fb09cda88345f8e0a852\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.
Starting azuracast_redis_1    ... error
Starting azuracast_mariadb_1 ...
Starting azuracast_stations  ...
Starting azuracast_influxdb_1 ...

ERROR: for azuracast_redis_1  Cannot start service redis: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to roStarting azuracast_influxdb_1 ... error
Starting azuracast_mariadb_1  ... error
ERROR: for azuracast_influxdb_1  Cannot start service influxdb: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/becd95c8f82165799243131a41327c3ca305e0b28055315d990e893fe6ca1cbc\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

Starting azuracast_stations   ... error
o rootfs \\\"/var/lib/docker/vfs/dir/69a2c1071112324b045547173371fa8d8e0a1ed35961764380bd7ad62f76e616\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for azuracast_stations  Cannot start service stations: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/77036708597d80b43f98ef1c2c52cd904518d3977c33fb09cda88345f8e0a852\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for redis  Cannot start service redis: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/d19afa6fab4b1d55c01acb2c5e75114132c622aa62ebabb0032e34b166eac71b\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for influxdb  Cannot start service influxdb: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/becd95c8f82165799243131a41327c3ca305e0b28055315d990e893fe6ca1cbc\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for mariadb  Cannot start service mariadb: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/69a2c1071112324b045547173371fa8d8e0a1ed35961764380bd7ad62f76e616\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for stations  Cannot start service stations: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/77036708597d80b43f98ef1c2c52cd904518d3977c33fb09cda88345f8e0a852\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.

Could you help me with that?

Greetings.

**Comment by NurLutix** [comment]
Excuse me. I accidentally closed the conversation yesterday. I just reinstalled the server and still get errors.

**Comment by NurLutix** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/35920440/59193428-f9d66780-8b85-11e9-941e-00a2dad488e0.png)
The current mistakes.

**Comment by Chrisx84** [comment]
im getting the same issue, i already have mariadb and nginx installed

**Comment by NurLutix** [comment]
Then luckily I'm not the only one.

**Comment by Vaalyn** [comment]
There are multiple `no space left on device` error messages. Could you execute `df -h` on your server and to check how much space you've left on the machine?

**Comment by NurLutix** [comment]
Two things: 1. 20GB still available. But why does AzuraCast use 25GB of memory? 

![Screenshot_1](https://user-images.githubusercontent.com/35920440/59218167-d8926d00-8bbf-11e9-93a4-da1325d18d88.png)


2. The following errors are currently occurring: https://hastebin.com/nuremecoce.sql

Greetings from Germany.

**Comment by Chrisx84** [comment]
i got a 80GB disk space vps and 8GB ram, barely using 10% of disk space or ram so its not a memory issue for me

**Comment by Vaalyn** [comment]
This could also be a permissions problem.

Could you tell me a bit more about your setup:
Is this a freshly installed machine? 
Did you install Docker by hand or did you let our installer do that for you?
Have you logged off and on after the installer added your user to the Docker group?
Did anything else fail with relation to Docker before these errors?

**Comment by NurLutix** [comment]
Hey,
It's a freshly installed machine. 

Docker was installed by the script.

I couldn't log out because he installed it automatically.

Nothing else failed.

Greetings from Germany
Luca.

**Comment by Vaalyn** [comment]
> I couldn't log out because he installed it automatically.

I should have been a bit more descriptive with what I meant. The script prompts you with the following:
```
You must log out or restart to apply necessary Docker permissions changes.
Restart, then continue installing using this script.
```

Did you do that?

**Comment by NurLutix** [comment]
That didn't come with me. He installed everything and there was no way to restart the server or log out.

**Comment by Vaalyn** [comment]
Then you probably installed AzuraCast when logged in as root which will lead to the script skipping the [part](https://github.com/AzuraCast/AzuraCast/blob/master/docker.sh#L56) where it adds the user to the docker permission group. That shouldn't be a problem then.

Could you tell me which hoster and which product of them you are using for the server?

Also would you mind if I take a look at it directly?
I haven't seen this problem before so I'm a bit unsure what is causing this. Taking a direct look at it could help figuring it out faster than trying to remote debug this issue.
If that's okay for you just send me the SSH connection details to vaalyndev@gmail.com

**Comment by NurLutix** [comment]
Hey,
I own a dedicated server at SoyouStart and created a VPS via Proxmox there. 

You're welcome to take a look. You will receive the login data by e-mail. 

Greetings.

**Comment by Vaalyn** [comment]
@NurLutix This could be the main problem here: `... container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs ...`. I've looked at the permissions for the `/proc` directory on your server and it is set to `nobody:nogroup` the same is set for most of the files in there. On my server the permissions for that directory and most files are `root:root`.

I think there is something wrong with the Ubuntu installation. Did you use the image provided by SoyouStart or did you download the image from the official Ubuntu website and used that to install the server?

**Comment by NurLutix** [comment]
I use the ISO of Proxmox. If you like, I can reinstall the server. Then everything is on default.

**Comment by Vaalyn** [comment]
If you don't mind doing that I'd recommend to do that. As it looks right now there seems to be something wrong with the installation of Ubuntu there and I'm not sure what has caused this so getting it to a default state would be my preferred thing to do right now.
After reinstalling could you go to `cd /` and do a `ls -la` to see if the permissions of `/proc` are correct?

**Comment by NurLutix** [comment]
Proc has no group and no user.

**Comment by Vaalyn** [comment]
I've researched a bit and I think this may be related to this thread on the Proxmox forum: https://forum.proxmox.com/threads/ran-docker-with-namespace-mapping-in-lxc-encountered-permission-error.37608/

What kind of VM do you create for that VPS, KVM or LXC ?

**Comment by NurLutix** [comment]
I always click "Create CT." So I'm thinking LXC.

**Comment by Vaalyn** [comment]
Then this is the problem. As LXC itself is a containerization method without some tinkering you'll not be able to run Docker on it and if you get it to run I'm not sure how stable / secure that would be. Imagine it like running the Docker runtime inside another Docker container.

You should create a real VM with KVM for Docker.

**Comment by NurLutix** [comment]
Okay. Still, thank you and have a nice day.

**Comment by NurLutix** [comment]
I still have one question: Where can I find the files when I install it with Docker? I installed it on another server today and there were only 3 files.

**Comment by Vaalyn** [comment]
Docker creates something that is called a `Volume` for the persistent data of a container. These Volumes will be located at `/var/lib/docker/volumes`. There you'll find directories with the naming like `azuracast_*`. These are the Volumes that are mounted into the containers so that they can persists their data to your filesystem.
