### ISSUE TITLE
AutoDj crash out of memory

### ISSUE THREAD

**Issue by MyTheValentinus** [AzuraCast/AzuraCast#1644]
Hello,
Today, my autodj crash with this message in log and no automatic restart:
Fatal error: out of memory.

My server is not out of ram and no limit on Docker container.

Is out of memory for the disk or ram ?

There no auto memory cleanup on Liquidsoap ?

Thanks

Docker install on trunk master of github, updated some days.

Thanks

**Comment by Vaalyn** [comment]
`Fatal error: out of memory.` refers to the RAM of your machine. How much RAM does your machine have and do you monitor the resource usage? If so was there any noticable spike in RAM usage?

> There no auto memory cleanup on Liquidsoap ?

Normally Liquidsoap does clean up unused memory so that should not happen except if there is a bug in Liquidsoap or if the amount of memory that an operation needs could not be satisfied by the machine.

**Comment by Vaalyn** [comment]
Closing as there hasn't been a reply in ~2 weeks apart from the initial report.

**Comment by MyTheValentinus** [comment]
Hello @Vaalyn,
Sorry for the late reply. You can re-open this issue.
I monitor my server with zabbix, in attchment a graph of ram usage
![image](https://user-images.githubusercontent.com/6104498/60206888-f1a04c80-9854-11e9-95a2-26974e576bf7.png)

Thanks

**Comment by Vaalyn** [comment]
From the screenshot I see that your server has a maximum of 2GB RAM and you are operating pretty much on the edge of that.

Do you have a swap space and if yes how much?
If you don't have swap enabled you should do that as that will prevent you from going out of memory in situations where more RAM is needed than is available.

Is the problem happening more often or was this a one time thing?

**Comment by MyTheValentinus** [comment]
Hello, my server has 4Gb ram now. In the graphic the ram never up to more than 2Gb, that why you dont see 4go in the axis.

**Comment by Vaalyn** [comment]
Short update. I noticed someone reporting the same issue on the Liquidsoap Slack server.

Basically what I got from the discussion over there is that LS failed to allocate some memory via a `malloc` which seems to be a bit hard to debug for them but they are looking into it.

There is now also an issue for that on the LS repo: https://github.com/savonet/liquidsoap/issues/877

**Comment by MyTheValentinus** [comment]
Nice to hear !
Thanks

**Comment by MyTheValentinus** [comment]
Comment to prevent stale to close this issue.
Thanks

**Comment by MyTheValentinus** [comment]
Comment to prevent stale to close this issue.
Thanks
