### ISSUE TITLE
The storage error in stations

### ISSUE THREAD

**Issue by uppula11718700** [AzuraCast/AzuraCast#1645]
I deployed azuracast in UBUNTU LTS server and i created two stations.
The space used by music files sin first station is 1 gb and the total storage is 10 gb the stats bar is good in 1st station but in second station the storage is showing the whole 10 gb which is not displaying the available storage

**Comment by Vaalyn** [comment]
Would you mind taking some screenshots that show the difference between the stations and how they are configured?

**Comment by Vaalyn** [comment]
Closing as there has been no reply apart from the initial report for over 2 weeks.

If this issue is still valid please respond with the requested information and I'll re-open it.
