### ISSUE TITLE
replacing station_data with a host directory on another partition

### ISSUE THREAD

**Issue by Simon818** [AzuraCast/AzuraCast#1646]
I have a dedicated server with a 250 gb boot partition and a 6 TB data partition. Since the data partition is mounted on /home none of the Azuracast files are in this partition, and we need to serve more than 250 gb of music. So I went into the docker-compose.yml and, under services > web > volumes and services > stations > volumes, I replaced the station_data entry with this:

- /home/res/azuracast:/var/azuracast/stations

When I create stations and add music, the files go where they should. I noticed Docker was running everything under the noderig group, so I gave that full reign over the /home/res/azuracast folder. When I add files to a media folder manually, they show up on the "music files" page for the associated station.

The problem seems to be liquidsoap: While the profile page for each station says "on the air", they all say "stream offline" in the now playing section below. Liquidsoap claims to be shuffling from 0 songs despite there being many in the folder.

I know there's more troubleshooting I could and should be doing, but am not sure where I should be doing that. I'm comfortable just running bash on the stations service and poking around if I know where to poke.

Thanks in advance.

[stations.log](https://github.com/AzuraCast/AzuraCast/files/3270099/stations.log)

**Comment by SlvrEagle23** [comment]
@Simon818 Are you adding the songs to a playlist? By default, a single "general rotation" playlist is created, and you have to add any songs you would like to play to this playlist.

**Comment by Vaalyn** [comment]
Closing this issue as there has been no reply for ~1 month.
