### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#1648]
Hello. Currently my panel is in http, I would like to change to https. If I change will I stick with my codes in inactive http?

I have more than 30 radios in http. If the links do not work in http anymore I'll have to change the link of all the radios on the platforms and in the official app.

Is it possible to keep the links in http working? Until I change the new links on https of all radios on tunein and radiosnet platforms.

Att
Rafael

**Comment by Vaalyn** [comment]
The non-https links should still work after enabling https in AzuraCast. I have enabled https for my installation, checked `Use Web Proxy for Radio` and `Always Use HTTPS` and on my website I've included the non-https links and they are working just fine.
