### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#1649]
Hello, I can not update my dashboard anymore. Can you help me with this subject? Before I updated normal with traditional method via command lines that you made available here. Now does not update. these command lines, here does not work nor activate commands.

 NYC3 - Ubuntu 18.04.2 x64

Att
Rafael - Brazil

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 Are you still using the same update command?

```
cd /var/azuracast/www
./update.sh
```

We no longer support new Ansible installations, and we recommend migrating to our Docker installation (using `./docker-migrate.sh`) but you should still be able to update your existing installations using the same command as before.

**Comment by Rafaelrds2017** [comment]
No. I always use the codes available here. He was not using the old one.

If I do the migration, will not I miss anything?

Do I migrate via command lines? How do I upgrade? just by putting the commands: using ./docker-migrate.sh?

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 You use the script I mentioned there: `docker-migrate.sh`. It will go through a series of steps to back up, uninstall the older installation, then move you over to Docker. This is recommended for easier future updates.

**Comment by Rafaelrds2017** [comment]
After the migration is done. What code should I use to upgrade?

Working with Servers and Systems: NYC3 - Ubuntu 18.04.2 x64 - Digital Ocean

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 If you're on Docker, the update command is:

```
./docker.sh update-self
./docker.sh update
```

**Comment by Rafaelrds2017** [comment]
OK thank you! I'll use the command you mentioned to do the migration. Then in the sequence I update the Azura system.

Att
Rafael - Brazil

**Comment by Rafaelrds2017** [comment]
This message appears:


___________________________________

Welcome to Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-51-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 System information disabled due to load higher than 4.0

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

133 packages can be updated.
0 updates are security updates.


root@server3:~#  ./docker-migrate.sh
-bash: ./docker-migrate.sh: No such file or directory
root@server3:~# ^C
root@server3:~#
root@server3:~#

___________________________
what should I do?

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 You can't just run that script from anywhere on the server, you have to run it from where it's actually located. In most cases, the default will be `/var/azuracast/www`, so:

```
cd /var/azuracast/www
bash docker-migrate.sh
```

**Comment by Rafaelrds2017** [comment]
OK thank you.
I could not migrate, and ended up taking the radios out of the air. I had to restore the old droplet.

Can you tell me how many minutes the migration takes?
Which message appears, saying that the migration has been completed?

**Comment by Vaalyn** [comment]
@Rafaelrds2017 The migration time depends on the size of your AzuraCast installation (number of stations, files, size of  the files, etc.) and on the performance of your server.

The last message of the migration script is this:
```
Docker is running. Press any key to continue (cleanup)...
```

After the cleanup is done (which should be quite fast) you'll be back in the normal ssh.

**Comment by burnscm** [comment]
i dont't find docker-migrate.sh  ( i have 2022 Ansible installation) and must migrate
