### ISSUE TITLE
Backup to move?

### ISSUE THREAD

**Issue by darkjedeye** [AzuraCast/AzuraCast#165]
How do i back my current setting up and move the whole system to another server? is there a way i can pull the dockers from one server to another? or do i have to just tar the whole dir and then move it an untar and reload??? not really sure how this will work...

**Comment by SlvrEagle23** [comment]
@darkjedeye This is a question I've had on my own local Docker instances as well, so I've put together two simple scripts, one will spin all the services down, take a backup snapshot of all the important volumes, then spin them back up...the other reverses the process, restoring volumes from that snapshot.
