### ISSUE TITLE
Webserver cannot start

### ISSUE THREAD

**Issue by Luislife2004** [AzuraCast/AzuraCast#1650]
**Using Docker installation method**
Yes

**Host Operating System**
debian 9 64bit

**Describe the bug**
```
Starting 380fb0f3d440_azuracast_web_1 ... error

ERROR: for 380fb0f3d440_azuracast_web_1  Cannot start service web: driver failed programming external connectivity on endpoint 380fb0f3d440_azuracast_web_1 (5b0c0bdc0dbc62127710e10cbe2716e5ea39e650d02d8fe87096d29ef999de57): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint 380fb0f3d440_azuracast_web_1 (5b0c0bdc0dbc62127710e10cbe2716e5ea39e650d02d8fe87096d29ef999de57): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use
ERROR: Encountered errors while bringing up the project.
```

**Comment by Vaalyn** [comment]
`Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use`

You most likely have `apache2` or `nginx` web server installed on the machine which use the same port as AzuraCast. You'll need to disable that software or if you are actually hosting something on the same server via Apache or NGINX you should follow our [guide](https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#use-non-standard-ports) on how to set custom ports for the web container.

**Comment by Vaalyn** [comment]
Closing this issue as there hasn't been a response in ~2 weeks apart from the initial report.

**Comment by feedigital** [comment]
the guid referencing how to run this when you have an apache or NGINX conflict.....must have disappeared because that isn't available and I can't find a resolution to this

**Comment by Extarys** [comment]
I have a similar issue. I followed [this guide](https://www.azuracast.com/help/faq_docker.html#use-non-standard-ports) and ran 
```
sudo docker-compose down
sudo docker-compose up -d
```
Output:
```
azuracast_redis_1 is up-to-date
azuracast_mariadb_1 is up-to-date
azuracast_stations is up-to-date
azuracast_influxdb_1 is up-to-date
Starting azuracast_web ... 
Starting azuracast_web ... error

ERROR: for azuracast_web  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web (7614b33dc2e04640a6b0c784e361f153297cc096c3214a47f4f4c3e9d7730852): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web (7614b33dc2e04640a6b0c784e361f153297cc096c3214a47f4f4c3e9d7730852): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

Any idea?

**Comment by SlvrEagle23** [comment]
@Extarys Make sure you're not editing `azuracast.env` but literally a file named `.env`, with no filename ahead of the period. It's a bit of confusion since both files exist, but it's necessary because of the way Docker works.
