### ISSUE TITLE
Bug JS in modal - Last button in pagination does not work

### ISSUE THREAD

**Issue by fwn0** [AzuraCast/AzuraCast#1652]
**Using Docker installation method**
 No

**Host Operating System**
 Debian 9.7 Stretch

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

![Azuracast _modalbug](https://user-images.githubusercontent.com/35877841/59272261-edb9db00-8c55-11e9-8ce7-e1ae57ae6c98.jpg)

**Device(s):**
 - Device:  Desktop
 - OS:  Linux
 - Browser:  Chromium, Firefox, Opera, Vivaldi
 - Version:  all latest

**Additional context**

Bug JS in modal - Last button in pagination does not work

**Comment by Vaalyn** [comment]
This is most likely due to the same underlying issue of #1407.
Please follow that issue for updates to this problem.
