### ISSUE TITLE
MP3 Art in twitter webhook

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#1654]
Hello peoples,
i investgated a bit about twitter cards, so they can display a referenced image:
This is whats coming from the API:

`"art":"https:\/\/stream.iradio.guru\/api\/station\/1\/art\/f30fc1dc6770513e698462fe.jpg"`

and thats whats needed to display the image inline on Twitter:

`<meta name="twitter:image:src" content=""art":"https://stream.iradio.guru/api/station/1/art\/f30fc1dc6770513e698462fe.jpg",">`

So the `\` have to be removed.

**Comment by macbroadcast** [comment]
Ok, i did some more research, so a "player-card" would do the job, 
https://github.com/twitterdev/cards-player-samples its simply 2 HTML documents with the referenced files, but i can't find information about if it's possible to use an .mp3 file and how would this card works with the twitter webhook in azuracast.
Maybe @SlvrEagle23 or @vaalyn Thanks  :smile_cat

**Comment by Vaalyn** [comment]
Adding a `Twitter Player Card` page would be a feature request that you should create at https://features.azuracast.com

Regarding webhooks this is more or less helpful. In theory you could use a webhook to post the link to the Twitter Player Card every time the song changes and Twitter will show the card in the post then. The thing is that these cards were made for static content and not for always changing content so I'm not sure what happens to old posts with Twitter Player Card links when the song on your station changes. Will they still show the old information (does Twitter cache that and how long?) or will they always point to the newest information?

**Comment by macbroadcast** [comment]
The Cover Art should be the image and an overlay "Azuracast Play Button" , like youtube, should start the stream.
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/player-card

Found a "service" who is offering "embeded player" for audio files , but you have to click twice to start the track, first loading the javascript and second start the player. https://www.chirbit.com/

**Comment by macbroadcast** [comment]
It would be awsome when @SlvrEagle23 could point me to the corresponding file in the azuracast backend, which is displaying the twitter webhook.

**Comment by SlvrEagle23** [comment]
@macbroadcast https://github.com/AzuraCast/AzuraCast/blob/master/src/Webhook/Connector/Twitter.php
