### ISSUE TITLE
Schedule playlist without A.M. and P.M. selection

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#1655]
Hi guys.

My setup is at the final update, docker, ubuntu.

I can not see A.M. and P.M. selection when scheduling a playlist. (If I don't remember wrong, I were able to select A.M. and P.M. before latest update but not sure) When I set a playlist to 12.00 to 02.00, it schedules playlist to overnight even it should be played only 2 hours. 

I guess It would be solved if we could see and select A.M. and P.M. options.

screenshots: 

created new playlist named "Trial Playlist":
https://radiolize.com/uploads/2019/06/Screen-Shot-2019-06-12-at-02.51.25.png

and the result:
https://radiolize.com/uploads/2019/06/Screen-Shot-2019-06-12-at-02.51.42.png

I know about the playlist bugs, also is there any news about scheduling once x per minute, once per x songs and other bugs?

Greetings.

**Comment by Vaalyn** [comment]
That field accepts the 24h format without A.M. and P.M. so for your playlist you need to set it to 12:00 and 14:00.

**Comment by radiolize** [comment]
Yes but what if I would like to stream between 12 and 2?

**Comment by Vaalyn** [comment]
That's not a problem, you again just use the 24h format:
2 AM and 12 PM => 02:00 and 12:00
12 PM and 2:00 PM => 12:00 and 14:00

**Comment by radiolize** [comment]
What if between 12 AM and 2 AM. It should be 12:00 and 02:00 as seen on my first screenshot. But when do, it looks like the playlist will be played 14 hours instead of 2 hours.

**Comment by SlvrEagle23** [comment]
@radiolize 12am would be 00:00, not 12:00.

**Comment by radiolize** [comment]
oh... thanks. I feel as dumb lol.
