### ISSUE TITLE
Hide password in the Web DJ interface

### ISSUE THREAD

**Issue by afonsosantos** [AzuraCast/AzuraCast#1656]
Hi,

Why the input field for entering the password in the Web DJ interface has a type of `text` instead of `password`? Not a big deal, just curious about it...

![image](https://user-images.githubusercontent.com/46262740/59358752-0a711400-8d25-11e9-9520-47e06bb3bf7d.png)

Thanks!

**Comment by Vaalyn** [comment]
I'm not aware of any specific reason for that. Thanks for pointing that out it should really be a password field for security reasons.

**Comment by afonsosantos** [comment]
You're welcome!

**Comment by afonsosantos** [comment]
Thanks @Vaalyn for fixing it! Closing this issue, since it's solved.
