### ISSUE TITLE
Music upload fails/hang and not show in the list

### ISSUE THREAD

**Issue by inetactief** [AzuraCast/AzuraCast#1657]
We have update from v0.9.4 to  v0.9.5.1, #fbaec68 (2019-06-11 11:55) • Docker • PHP 7.2 on CentOS 7 (last update install).

When we try to upload a mp3 file 10,5 mb on the webinterface he do not complete the upload. 
On 30% stop and refresh the screen.. but no file the music dir. 
We try to upload a jingle mp3 its 275kb but he the bar is 100% but nothing happens

Where can we find the log file of this proces? 

We try find the error log in AzuraCast Application Log. But nothing there.

Only some error like:
[2019-06-12 15:30:01] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 404: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found</h1> <p>The requested URL /status-json.xsl was not found on this server.</p> <p>Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.</p> </body></html>  [] {"station":{"id":3,"name":"Radio Assembly of Zion "}}

**Comment by inetactief** [comment]
We use Chrome on Windows 7.. and when we upload i check the java screen.
We see 2 errors:
Failed to load resource: the server responded with a status of 500 ()
VM467:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at d.<anonymous> (files:528)
    at d.<anonymous> (flow-8c41da7745.min.js:2)
    at l (flow-8c41da7745.min.js:2)
    at d.fire (flow-8c41da7745.min.js:2)
    at e.chunkEvent (flow-8c41da7745.min.js:2)
    at g.event (flow-8c41da7745.min.js:2)
    at XMLHttpRequest.doneHandler (flow-8c41da7745.min.js:2)

**Comment by inetactief** [comment]
On AzuraCast Application Logs we do not see any error about the upload

**Comment by inetactief** [comment]
We try a different computer but same problem there..

**Comment by SC2Mitch** [comment]
Confirming this issue on my own server
VM133:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at d.<anonymous> (files:528)
    at d.<anonymous> (flow-8c41da7745.min.js:2)
    at l (flow-8c41da7745.min.js:2)
    at d.fire (flow-8c41da7745.min.js:2)
    at e.chunkEvent (flow-8c41da7745.min.js:2)
    at g.event (flow-8c41da7745.min.js:2)
    at XMLHttpRequest.doneHandler (flow-8c41da7745.min.js:2)

**Comment by fafamonge** [comment]
I can't upload music file through browser, getting in console
```
flow-8c41da7745.min.js:2 POST https://www.hdradiostreaming.com:10443/station/2/files/upload 500
Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at d.<anonymous> (files:528)
    at d.<anonymous> (flow-8c41da7745.min.js:2)
    at l (flow-8c41da7745.min.js:2)
    at d.fire (flow-8c41da7745.min.js:2)
    at e.chunkEvent (flow-8c41da7745.min.js:2)
    at g.event (flow-8c41da7745.min.js:2)
    at XMLHttpRequest.doneHandler (flow-8c41da7745.min.js:2)
```

Docker installation and CentOS 7

**Comment by rolradio** [comment]
Here the same problem.
Has been since the upgrade to the latest version today.

**Comment by SlvrEagle23** [comment]
@rolradio @fafamonge @SC2Mitch I'm in the process of investigating this issue, as it appears a fair number of you are experiencing it, but I can't reproduce it on any of my test instances.

When you experience that error, can you click the "Network" tab on your Chrome inspector (F12) console, then click the latest few responses and look for one that looks out of the ordinary? In particular, you may want to look for a response that is returning HTML when it should be JSON.

It's likely that there's some sort of exception getting thrown but not being elegantly caught, but until I know what that exception text is I can't work to resolve the issue.

In the meantime, if you find that you can't upload via the web interface _at all_ on your installation, you can also upload directly to your station media directories via SFTP by following our [support instructions](https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#access-files-via-sftp).

Thank you all for your patience.

**Comment by ErnestPH** [comment]
Just a note to everyone. This is not an issue For MACOSX browsers build #2022ecf. I just don't want to update first unless this bug is verified non-existing. Thanks!

**Comment by SlvrEagle23** [comment]
It's bizarre to imagine that the latest few commits would have anything to do with this issue, as no modifications have been made to how file uploads are handled, but I'll have to wait to see if I can see any exception data to know.

**Comment by rolradio** [comment]
@SlvrEagle23  I have performed the update again. After that the problem disappeared. I already had this problem with a previous update.
I don't know what caused the problem. It appeared on all 3 of my installed azuracast panels
However, the update was without errors every time.
But for now everything works perfectly again here.

**Comment by SC2Mitch** [comment]
@SlvrEagle23 After deploying the update, it appears to have resolved the issues.

**Comment by SlvrEagle23** [comment]
@rolradio @SC2Mitch The purpose of the latest code change wasn't to resolve the issue but to make error reporting clearer, but if it's resolved the issue in your case then that's good to hear. :)

**Comment by inetactief** [comment]
So when I update the issue is resolved? 
Is there a method to update without the radiostations going offline?

**Comment by radiolize** [comment]
I had the same error 1-2 week ago. Updating was solved it.

**Comment by SlvrEagle23** [comment]
I've figured out the likely cause of why updating seems to fix the issue for people: there's a cron task that cleans out the `/tmp` directory, which can also delete the temporary directory where nginx stores its client upload files. I've explicitly set the Docker image to preserve these folders, which should prevent this from happening in the future.
