### ISSUE TITLE
Can't upload new files, it makes me logout instead

### ISSUE THREAD

**Issue by mkody** [AzuraCast/AzuraCast#166]
When I try to upload one or multiple songs, the upload progress bars make it looks like it worked but the file listing is stuck to a "loading..." message. If I go elsewhere or refresh the page, I'm logged out. And going back to media management shows me that nothing was actually uploaded.  
The media folder in `/var/azuracast/stations/<station>/media` doesn't contain the new files too.  
It looks like it doesn't happen every single time, it might be able to upload one file and stop working right after.

Steps:
- Go to `Media Manager`
- Upload an MP3
  * If you're lucky and it worked, upload an another file
- Click on any link or refresh because nothing happens anymore
- Login again and notice the file wasn't uploaded

I'm running `0.7.0-2017.06`, Debian 7 x64

**Comment by SlvrEagle23** [comment]
@mkody well that stinks...I haven't seen this on any of my installs :(

A question, though...are you behind CloudFlare? I'm thinking CF might be a little upset at having to shuttle the individual little file chunks back and forth that the new uploader uses, and I may need to make the "chunked uploader" feature a selectable setting.

**Comment by mkody** [comment]
Nope, not running behind CF. I have a proxy machine that redirects to the correct LXC container tho, but logs on the upstream doesn't tell anything wrong.

I can give you access to the machine later, if needed

**Comment by SlvrEagle23** [comment]
@mkody I may need that, I keep pumping huge files through the uploader on both my CF and non-CF instances and it's handling them fine

**Comment by SlvrEagle23** [comment]
@mkody I'm closing this issue for now...let me know directly if you continue to have this issue on your installation, I'm not seeing it widespread.
