### ISSUE TITLE
Server Ip address

### ISSUE THREAD

**Issue by uppula11718700** [AzuraCast/AzuraCast#1664]
when i installed azuracast in gcloud an ip was assigned to the server and azuracast stores the ip at the time of installation. But when i restart the server the ip was changed but it was not reflected back in azuracast. Please fix it. The player is also not working, data is displayed about song but song is not being played.

**Comment by Vaalyn** [comment]
Hey, is your AzuraCast set up to only use the ip of the server or do you have a domain pointed to it?
