### ISSUE TITLE
Using LADSPA Plugins with Liquidsoap? Is it available in the current version?

### ISSUE THREAD

**Issue by FarmanX** [AzuraCast/AzuraCast#1665]
I know this is not the right place to request features. But I want to know if this is integrated in the current version or not? If not, I will close this and post a feature request in the right place.

Thanks

**Comment by Vaalyn** [comment]
In the current version we don't install the `ladspa` opam package for Liquidsoap. If you'd like you can create a feature requests for it over at https://features.azuracast.com.

**Comment by houtjetouwtje** [comment]
Hello guys,
Ladspa plugins are supported.
I haven‘t got it running yet.
I am doing something wrong obviously...
Help appreciated.
Thanks!


20 Jan 
Buster Neece Admin
This isn't implemented directly into the system, but on our rolling-release channel, we've updated our Liquidsoap Docker image to include both LADSPA and several plugins, including all of the ones needed to implement this script. I've tested and verified that this script works (provided you use the "radio" variable name instead at top and bottom) and it definitely punches up the audio quality a lot.

**Comment by SlvrEagle23** [comment]
@houtjetouwtje Make sure you're on the "rolling release" channel (not the stable channel, which hasn't updated yet to include these plugins) and that you're on the latest version of either the Docker or Ansible installations.

You will then have access to a multitude of `ladspa` functions inside custom Liquidsoap configuration.

**Comment by houtjetouwtje** [comment]
Mogelijk gemaakt door AzuraCast • Rolling Release #e6cb02e (2021-01-22 22:34) • Docker • PHP 7.4 

This is my actual version.
Pascal wrote a script wich i copied and pasted in my liquidsoap config.
I did a list ladspa plugins.
root@gnoenet:/var/azuracast# liquidsoap -h ladspa.plugin                          no more csLADSPA plugins                 Plugin not found!                        root@gnoenet:/var/azuracast#             # 1980 AMB order 2,1 rotator             > a: In-W      

This is my output.
How do i get pascal script working.
Thanks in advance
Rob

**Comment by SlvrEagle23** [comment]
@houtjetouwtje Liquidsoap is in a container, so you'd actually run something like:

```
docker-compose run --rm --user=azuracast stations liquidsoap --list-plugins
```

In the case of `liquidsoap -h ladspa.plugin` you're meant to replace `plugin` with the specific LADSPA plugin you want to use.

**Comment by houtjetouwtje** [comment]
This is more difficult as i thought...
Docker container contains all of the plugins needed for audioptocessing.
All i have to do is copy the script into the LS config in azuracast? To get this working.
Or is there another step i forgot?
Thanks i.a

Rob

via 
Mobiel

**Comment by houtjetouwtje** [comment]
Test:

root@gnoenet:/var/azuracast# liquidsoap -h ladspa.gate                            no more csLADSPA plugins                                                          Gate by Steve Harris <steve(at)plugin.org.uk>.                                                                             Type: (?id:string,?attack:'a,?decay:'b,?hf_key_filter:'c,                          ?hold:'d,?lf_key_filter:'e,?output_select:int,?range:'f,                          ?threshold:'g,source(audio='#h,video='#i,midi='#j))->                            source(audio='#h,video='#i,midi='#j)     where                                      'a, 'b, 'c, 'd, 'e, 'f, 'g is either float or ()->float                                     

via 
Mobiel

**Comment by houtjetouwtje** [comment]
Thank SLvrEagle,

I know something about linux, and learning about azuracast.
All plugins are in the docker container, so this should work without further installation or compiling.
I want to use the MK pascal script, but what needs to be edit, and where in the liquidsoap(wich field)config should i paste the script for this to work?
Thanks for your help in advance👍

Rob

via 
Mobiel

**Comment by houtjetouwtje** [comment]
Hello Buster,

Im still struggling with ladspa script from Pascal.
I really want this to work here.
What am i doing wrong?
I got this error:

Error 4: Undefined variable default
At line 80, char 20-27:
I know advanced liquidsoap is not supported, but i have waited a long time for this very nice update!
Will this be rolled out in the next stable release?

Thanks i.a
Rob

via 
Mobiel

**Comment by SlvrEagle23** [comment]
@houtjetouwtje I've made a Gist that includes the slightly modified code needed to get this audio processing script to work with AzuraCast, along with instructions on where to put it:

https://gist.github.com/SlvrEagle23/43a06ee6624975273fdc903ba4a39998#file-mkpascal_with_azuracast-liq

**Comment by houtjetouwtje** [comment]
Works like a charm!👍
Thanks SlvrEagle..
I got 1 wrong line:
Process = radio
Instead  radio = process😬

But sound has made a hudge inprovement.
Thanks again.

via 
Mobiel

**Comment by ckeurk** [comment]
Hi, the latest 0.12 stable release contains the following function Ladspa plugins?

**Comment by houtjetouwtje** [comment]
No, till now only on rolling release channel

**Comment by SlvrEagle23** [comment]
> Hi, the latest 0.12 stable release contains the following function Ladspa plugins?

The latest 0.12 release does include the LADSPA plugins, yes.

**Comment by ckeurk** [comment]
Thank you SlvrEagle23

**Comment by ckeurk** [comment]
Two last questions, are the plugins already installed or do they need to be installed in the docker? If not, what is the command to do it in the docker?
Thank you very much for your help

**Comment by SlvrEagle23** [comment]
@ckeurk They're already installed on our Docker images.

**Comment by ckeurk** [comment]
Super thanks

**Comment by houtjetouwtje** [comment]
I still have a question about audioprocessing.
Sound is really a lot better, but i have the idea that there still is variation in the output.
Some tunes are louder than others.
Where can i adjust that?
I suppose it’s a setting in de sc4 ladspa plugin.
I tried a lot of settings but the volume fluctuation is still there.
Thanks for the help👍
