### ISSUE TITLE
How to setup your own SSL if you already have it

### ISSUE THREAD

**Issue by fafamonge** [AzuraCast/AzuraCast#1667]
I have CentOS Web Panel (CWP) so my domain already has a Let's Encrypt SSL certificate issued (AutoSSL).

The procedure is very simple, just point these files from AzuraCast Let's Encrypt folder to the path of your already issued certificate and key

Go to Webserver Settings > Webservers Conf Editor > Apache (Tab) > Virtual Host (Tab) and open te file for your SSL domain, in my case `hdradiostreaming.com.ssl.conf` inside of it you will find the path to your CERT and KEY files.

You could do a symbolic link (soft) directly from the AzuraCast but I prefer copy the files to the AzuraCast folder.

```
Copying files to AzuraCast folder:
#cp /etc/pki/tls/certs/hdradiostreaming.com.cert /var/lib/docker/volumes/azuracast_letsencrypt/_data/hdradio.crt
#cp /etc/pki/tls/private/hdradiostreaming.com.key /var/lib/docker/volumes/azuracast_letsencrypt/_data/hdradio.key

Giving ownership to the user:group (Change for your own)
#chown 1000:1000 hdradio.*

Creating symbolic links with "soft" option:
#ln -s /etc/pki/tls/certs/hdradiostreaming.com.cert ssl.crt
#ln -s /etc/pki/tls/private/hdradiostreaming.com.key ssl.key

Giving ownership to the symbolic links:
#chown -h 1000:1000 ssl.*
```
It's done! Check your domain and no more warnings about the Non Safe domain, instead you will see the padlock icon on the bar.

**Why is this important?**

When you are using SSL in your broadcast but don't have well configured the SSL in AzuraCast, your listeners will get warning about your site is insecure and they should to click on advanced option in the browser (Chrome) and add the exception to continue to your streaming making difficult to reach it. Also if you embed the player in other site probably won't show through the iframe because the protocol is insecured and can cause "Mixed Content" issues.

Hope this be useful for you.

**Comment by SlvrEagle23** [comment]
@fafamonge While this likely works just fine, it's considered a bad practice to manually jump into the Docker volumes and edit them from their location on disk.

The safer option would be to create a `docker-compose.override.yml` file (or add to an existing one) and bind-mount your existing certificates into the necessary spot on the `web` container, like so:

```
version: '2.2'

services:
  web:
    volumes:
      - /local/path/to/ssl.crt:/etc/letsencrypt/ssl.crt
      - /local/path/to/ssl.key:/etc/letsencrypt/ssl.key
```

**Comment by ashah7** [comment]
where is this file kept?  I've created the override file in /root/ (the docker-compose.yml was in here already) and modified the file to point to my certs and rebooted by still showing the cert error....
