### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#1668]
Hello.

I lost all my data trying to do the migration.
I installed a new Azura. But some radios do not come back.
In Tunein, some radios do not work.

By accessing this page: http://stream.geracaoradios.com:8120/radio
error appears: ERR_CONNECTION_REFUSED

Already on this radio: http://stream.geracaoradios.com:8010/index.html?sid=1

it's normal.

Can you help me?

Att
Rafael

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 I don't know why the migration caused you to lose all your data, but if you're having that kind of trouble you should likely join our [Slack channel](https://join.slack.com/t/azuracast/shared_invite/enQtNDgyNzA4NzY2MzU3LWNmZjY3MmZlZGI1NzQ0OWEzMDBlMDk4MWVkMGMwMjAwYWQxZjdjYzRkYmM2NDkwZjc3ODI0N2UxY2M3ZjIxZWI) so we can assist you more directly with that specific issue.

The reason you're unable to connect to your one station is because its port number is above the 8000-8099 range that our Docker installation exposes by default. We have specific instructions for how to handle this situation here: https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#expand-the-docker-radio-station-port-range

**Comment by Rafaelrds2017** [comment]
Okay, I'm a layman. I did not understand much.

For in my past Azura, I created the radios. and automatically generated the doors.

My radios starts at 8000 a 8470

Is there an easier way for me to extend these ports?

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 The instructions I linked in the previous comment are the exact way to extend the ports. You should follow those instructions.

**Comment by Rafaelrds2017** [comment]
OK. I read the article. but I did not understand.

Do I have to use this command?

_____________________________________
version: '2.2'

services:
   stations:
     ports:
       - "8100-8500: 8100-8500"

_________________________________________

Even so

Thank you for your attention.

Att
Rafael - Brazil

**Comment by Rafaelrds2017** [comment]
Sorry for not knowing anything about programming.

Installation is easy as it is well explained.

**Comment by Rafaelrds2017** [comment]
It is in the additional details that I have difficulties.
I do not understand anything about programming. I only know how to copy and paste :(

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 I hesitate to say this to any of our users, but if you aren't comfortable with basic Linux terminal operations, you may not be well suited for using our software. It seems like you've run into data loss issues already as a result of this.

The instructions are telling you to create a file named `docker-compose.override.yml` alongside wherever the `docker-compose.yml` file is (by default, `/var/azuracast`), and in that file you should be pasting those contents.

**Comment by Rafaelrds2017** [comment]
Yes, I do not feel comfortable. For I am a layman.
I'm going to have to pay someone to do this.
I will not abate the azura, it was the best thing that happened to me. and if I lost any data, it was my fault.

**Comment by Rafaelrds2017** [comment]
I love AZURACAST, congratulations for the work.

**Comment by Rafaelrds2017** [comment]
do you have any files to show me how to expand the ports in the Self-Hosted Installation method?
________________________________
De: SlvrEagle23 <notifications@github.com>
Enviado: segunda-feira, 17 de junho de 2019 16:30
Para: AzuraCast/AzuraCast
Cc: Rafael Rodrigues; Mention
Assunto: Re: [AzuraCast/AzuraCast] ERR_CONNECTION_REFUSED (#1668)


@Rafaelrds2017<https://github.com/Rafaelrds2017> I hesitate to say this to any of our users, but if you aren't comfortable with basic Linux terminal operations, you may not be well suited for using our software. It seems like you've run into data loss issues already as a result of this.

The instructions are telling you to create a file named docker-compose.override.yml alongside wherever the docker-compose.yml file is (by default, /var/azuracast), and in that file you should be pasting those contents.

**Comment by Rafaelrds2017** [comment]
do you have any files to show me how to expand the ports in the Self-Hosted Installation method?

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 I have expanded the default port range on Docker to include up to port 8500, so you shouldn't have this problem in the future. Just update your installation and answer "Y" when asked if you want to update your docker-compose.yml file.

**Comment by Rafaelrds2017** [comment]
> @Rafaelrds2017 I have expanded the default port range on Docker to include up to port 8500, so you shouldn't have this problem in the future. Just update your installation and answer "Y" when asked if you want to update your docker-compose.yml file.

great
