### ISSUE TITLE
Playing Next API

### ISSUE THREAD

**Issue by adwinter** [AzuraCast/AzuraCast#1669]
Hey Team,

Forgive me if this has been discussed already, but I just upgraded to the latest version and I seem to have lost the "playing next" section in the API, or maybe the format has changed??

[ from API 'now playing' call ]
-----------------------------------------------------

 "playing_next": null,

-----------------------------------------------------

Any idea whether this was deliberate or not? Anyone know why?
Sorry if I missed  a thread on this earlier -- and personally its no biggie to me -- but I'll remove the line in my script capturing it if its gone for good.

Thanks in advance for your help.

Andrew

**Comment by Vaalyn** [comment]
This is a known issue. We disabled the "next song" functionality as we have some problems with the AutoDJ in that regards so this data is currently always `null`. It's currently unclear if we are able to fix this or if we have to completely remove that functionality as we depend on help from upstream for that.

**Comment by adwinter** [comment]
@Vaalyn Thanks as always for the support.
