### ISSUE TITLE
Playlist failing to add files

### ISSUE THREAD

**Issue by BlazinWings** [AzuraCast/AzuraCast#1670]
For some reason, I am unable to add music files to one playlist in a new station I have created. I have created several similar playlists which all work properly, but the playlist for this particular station does not seem to be pulling files from the specified directory. All files are in MP3 format, and the path of one of the files would appear as: azuracast/Country/media/collection/2010'S/2010/004 - Chris Young - The Man I Want To Be.mp3.
I've tried recreating the playlist, but nothing seems to add the files in this directory to the playlist. Azura shows 0 files added.

**Comment by SC2Mitch** [comment]
Open up the console and see if any issues are there, if not, repeat what you done with the console open, it should show any errors there

**Comment by SC2Mitch** [comment]
Heres some errors on my server after trying to add songs to a playlist. 
Networking tab
```
{code: 0, message: "Telnet failure: Connection refused (111)",…}
code: 0
extra_data: {context: []}
context: []
formatted_message: "Telnet failure: Connection refused (111)"
message: "Telnet failure: Connection refused (111)"
success: false
```
Console error output. 
```
jquery-220afd743d.min.js:2 POST http://5.189.186.220:8080/station/1/files/batch 500 (Internal Server Error)
send @ jquery-220afd743d.min.js:2
ajax @ jquery-220afd743d.min.js:2
k.<computed> @ jquery-220afd743d.min.js:2
(anonymous) @ files:441
dispatch @ jquery-220afd743d.min.js:2
v.handle @ jquery-220afd743d.min.js:2
```

**Comment by SC2Mitch** [comment]
@BlazinWings After speaking with SilverEagle on Slack, make sure your AutoDJ is running when making changes to the playlist. Should fix it

**Comment by SlvrEagle23** [comment]
@SC2Mitch @BlazinWings I've made an update to improve how AzuraCast handles saving playlist changes when your AutoDJ process isn't currently running. It will now log the error in the application log, but not actually stop the process from going through.

**Comment by BlazinWings** [comment]
Thank you so much for all of your work and suggestions. I will investigate tomorrow and be in touch!
