### ISSUE TITLE
Docker install creates br-* subnet which conflicts with our server's subnet

### ISSUE THREAD

**Issue by m-anish** [AzuraCast/AzuraCast#1672]
**Using Docker installation method**

Yes

**Host Operating System**

Ubuntu 18.04.2 LTS

**Describe the bug**

I am a volunteer of the [IIAB project](https://github.com/iiab/iiab) and am currently working on an ansible playbook to [install azuracast](https://github.com/iiab/iiab/pull/1733) as part of IIAB using the docker install method. 

We use `172.18.96.1/19` as our default subnet when the server controls the network. Azuracast docker install creates a bridge with subnet `172.18.0.1/16` which conflicts with our default subnet.

Is there any way I can easily change this? Here are the relevant network details:

**To Reproduce**

**Expected behavior**

Since the bridge (`br-7a3dbeee0d97` in this case) created by docker install conflicts with the base subnet of the IIAB server install, it breaks the setup. 

**Relevant Logs**

[network.zip](https://github.com/AzuraCast/AzuraCast/files/3299711/network.zip)

**Additional context**

I understand this may not be the right forum for the ticket. If so, please direct me to the right place. I would love to have azuracast as part of IIAB server to serve offline community radio over the wifi mesh networks we deploy in very remote areas of the world. Thanks!

**Comment by Vaalyn** [comment]
I think that you have to change the subnet in the config of the Docker daemon itself. You could try doing this: https://support.getjoan.com/hc/en-us/articles/115005951805-Change-the-Docker-default-subnet-IP-address

**Comment by m-anish** [comment]
Hi! 

Thanks for your comment. I tried that and it [seems to work](https://github.com/m-anish/iiab/blob/azuracast/roles/azuracast/templates/docker-compose.override.yml.j2). 

I have another question:

As I understand, in docker-compose.yml, these are the following port ranges. 

```
     - '8000:8000'
     - '8005:8005'
     - '8006:8006'
     - '8010:8010'
     - '8015:8015'
     - '8016:8016'
     - '8020:8020'
     - '8025:8025'
     - '8026:8026'
     - '8030:8030'
     - '8035:8035'
     - '8036:8036'
     - '8040:8040'
     - '8045:8045'
     - '8046:8046'
     - '8050:8050'
     - '8055:8055'
     - '8056:8056'
     - '8060:8060'
     - '8065:8065'
     - '8066:8066'
     - '8070:8070'
     - '8075:8075'
     - '8076:8076'
     - '8090:8090'
     - '8095:8095'
     - '8096:8096'
```

This conflicts with a few ports on our server. Do you think it is possible to use some other ports without delving too deep into the container itself? I tried, using 9xxx:9xxx instead of 8xxx:8xxx and I wasn't able to connect to icecast from a thirdparty app (like mixxx). Then I tried 8000, 8005, 8006, and for the rest 9xxx:9xxx, and that seems to work. However, 8006 also collides with a service on another port. 

So, do you think it's possible for the port numbers to be different?

Thank you very much for your help, and have a great day.

**Comment by Vaalyn** [comment]
Currently it is not possible to remove already mapped ports via a `docker-compose.override.yml` (it's a limitation by Docker / Docker-Compose) so you'll have to manually modify the ports section. So for example if you want to use port 9999 you first need to add `- '9999:9999'` to the ports section.

**Comment by m-anish** [comment]
> Currently it is not possible to remove already mapped ports via a `docker-compose.override.yml` (it's a limitation by Docker / Docker-Compose) so you'll have to manually modify the ports section. So for example if you want to use port 9999 you first need to add `- '9999:9999'` to the ports section and if you need to remove 8006 you just remove that line.

That's fine. I am doing that [here](https://github.com/m-anish/iiab/blob/azuracast/roles/azuracast/tasks/install.yml#L55).

But the issue is even when I changed all the 8xxx ports to 9xxx, in the Streamers section of the Station management console, against icecast and shoutcast, it shows 8005, 8006. Or do you think it might just be something that because I initially installed it with those settings, a `./docker.sh install` run won't override it, and so if I do a fresh install, it will work?

**Comment by Vaalyn** [comment]
Would you mind posting your modified `docker-compose.yml` and/or your `docker-compose.override.yml` and screenshots of the stations and mountpoint configs?
I'd like to have an overview of your setup so I can better understand what might be missing.

**Comment by m-anish** [comment]
Sure. I just wiped clean and redoing from scratch. Will give you something to look at in ~1hr.

**Comment by tim-moody** [comment]
I would stay out of the 8000 and 9000 series of ports. If it's configurable use something higher as everyone loves 8xxx and 9xxx.

**Comment by m-anish** [comment]
@Vaalyn  These are the requisite config files. (There is a hidden .env file in there too)
[azuracast-env.zip](https://github.com/AzuraCast/AzuraCast/files/3301980/azuracast-env.zip)

Below are some screenshots of the azuracast web-interface after installing:
![Screenshot from 2019-06-18 20-03-00](https://user-images.githubusercontent.com/5288668/59693291-46641780-9204-11e9-90be-62054c2be7ea.png)
![Screenshot from 2019-06-18 20-03-20](https://user-images.githubusercontent.com/5288668/59693293-47954480-9204-11e9-8a05-7e00328eeddd.png)

As you can see, in the web interface, the ports advertised are 8000, 8005, 8006 which is not the case in the docker-compose.yml or docker-compose.override.yml

**Comment by Vaalyn** [comment]
Okay, can you also show me the station and mountpoint configs to see how everything is configured?

**Comment by m-anish** [comment]
![Screenshot from 2019-06-18 20-14-36](https://user-images.githubusercontent.com/5288668/59694758-c1c6c880-9206-11e9-9fba-2f1be40518a0.png)
![Uploading Screenshot from 2019-06-18 20-21-55.png…]()

Is this what you're looking for?

**Comment by m-anish** [comment]
![Screenshot from 2019-06-18 20-21-55](https://user-images.githubusercontent.com/5288668/59694759-c1c6c880-9206-11e9-8bce-e9504713cd81.png)

**Comment by Vaalyn** [comment]
Yes. As you can see in the first screenshot your Icecast is configured to use port 8000, you'll need to change that to the port you want it to use. The same has to be done for the AutoDJ ports.

**Comment by m-anish** [comment]
Ok cool! I see it! That should fix it :)

Wonderful!

**Comment by m-anish** [comment]
Here's the screenshot from the auto-dj page. Thank you so much for your help! 

![Screenshot from 2019-06-18 20-24-57](https://user-images.githubusercontent.com/5288668/59695072-3e59a700-9207-11e9-8f41-edb233929c8c.png)
