### ISSUE TITLE
Liquidsoap does not start

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#1673]
Hello, I installed the Self-Hosted version, but I'm having a problem with a radio. Say Address already in use in bind ()

I already deleted it and created the station again on port 8010.
But it does not work. Liquidsoap does not start.

2019/06/18 01:40:46 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:40:48 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:40:50 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:40:53 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:40:53 [main:3] Liquidsoap 1.3.7
2019/06/18 01:40:53 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.7 camomile=1.0.1 faad=0.4.0
2019/06/18 01:40:53 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/06/18 01:40:53 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/06/18 01:40:53 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/06/18 01:40:53 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/06/18 01:40:53 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/06/18 01:41:01 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:41:02 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:41:05 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:41:09 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:41:50 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:41:51 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:41:51 [main:3] Liquidsoap 1.3.7
2019/06/18 01:41:51 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.7 camomile=1.0.1 faad=0.4.0
2019/06/18 01:41:51 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/06/18 01:41:51 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/06/18 01:41:51 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/06/18 01:41:51 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/06/18 01:41:51 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/06/18 01:41:53 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:41:53 [main:3] Liquidsoap 1.3.7
2019/06/18 01:41:53 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.7 camomile=1.0.1 faad=0.4.0
2019/06/18 01:41:53 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/06/18 01:41:53 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/06/18 01:41:53 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/06/18 01:41:53 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/06/18 01:41:53 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/06/18 01:41:57 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:41:58 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:41:58 [main:3] Liquidsoap 1.3.7
2019/06/18 01:41:58 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.7 camomile=1.0.1 faad=0.4.0
2019/06/18 01:41:58 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/06/18 01:41:58 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/06/18 01:41:58 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/06/18 01:41:58 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/06/18 01:41:58 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/06/18 01:42:00 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:42:00 [main:3] Liquidsoap 1.3.7
2019/06/18 01:42:00 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.7 camomile=1.0.1 faad=0.4.0
2019/06/18 01:42:00 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/06/18 01:42:00 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/06/18 01:42:00 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/06/18 01:42:00 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/06/18 01:42:00 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/06/18 01:42:02 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:42:06 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:43:05 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:43:05 [main:3] Liquidsoap 1.3.7
2019/06/18 01:43:05 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.7 camomile=1.0.1 faad=0.4.0
2019/06/18 01:43:05 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/06/18 01:43:05 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/06/18 01:43:05 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/06/18 01:43:05 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/06/18 01:43:05 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/06/18 01:43:06 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:43:06 [main:3] Liquidsoap 1.3.7
2019/06/18 01:43:06 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.7 camomile=1.0.1 faad=0.4.0
2019/06/18 01:43:06 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/06/18 01:43:06 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/06/18 01:43:06 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/06/18 01:43:06 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/06/18 01:43:06 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/06/18 01:43:09 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:43:13 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:43:13 [main:3] Liquidsoap 1.3.7
2019/06/18 01:43:13 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.7 camomile=1.0.1 faad=0.4.0
2019/06/18 01:43:13 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/06/18 01:43:13 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/06/18 01:43:13 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/06/18 01:43:13 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/06/18 01:43:13 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/06/18 01:44:19 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:44:21 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:44:21 [main:3] Liquidsoap 1.3.7
2019/06/18 01:44:21 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.7 camomile=1.0.1 faad=0.4.0
2019/06/18 01:44:21 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/06/18 01:44:21 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/06/18 01:44:21 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/06/18 01:44:21 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/06/18 01:44:21 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/06/18 01:44:23 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
2019/06/18 01:44:26 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 Every version of AzuraCast is a "self-hosted" version. Are you using the Docker version or not?

**Comment by Rafaelrds2017** [comment]
This installation: https://www.azuracast.com/install.html#self-hosted-installation

Via command.
Ubuntu System - DigitalOcean
________________________________
De: SlvrEagle23 <notifications@github.com>
Enviado: terça-feira, 18 de junho de 2019 02:18
Para: AzuraCast/AzuraCast
Cc: Rafael Rodrigues; Mention
Assunto: Re: [AzuraCast/AzuraCast] Liquidsoap does not start (#1673)


@Rafaelrds2017<https://github.com/Rafaelrds2017> Every version of AzuraCast is a "self-hosted" version. Are you using the Docker version or not?

**Comment by Rafaelrds2017** [comment]
This installation: https://www.azuracast.com/install.html#self-hosted-installation

Via command.
Ubuntu System - DigitalOcean

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 This may be caused by an error in how our internal process management works.

On your host server, try running:

```
cd /var/azuracast
docker-compose down
docker-compose up -d
```

which should reset the running programs and make the port available again.

**Comment by Rafaelrds2017** [comment]
root@srv2:/var/azuracast# docker-compose up -d
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

root@srv2:/var/azuracast# login as: root
root@165.22.46.179's password:
Welcome to Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-50-generic x86_64)
________________________________
De: SlvrEagle23 <notifications@github.com>
Enviado: terça-feira, 18 de junho de 2019 02:27
Para: AzuraCast/AzuraCast
Cc: Rafael Rodrigues; Mention
Assunto: Re: [AzuraCast/AzuraCast] Liquidsoap does not start (#1673)


@Rafaelrds2017<https://github.com/Rafaelrds2017> This may be caused by an error in how our internal process management works.

On your host server, try running:

cd /var/azuracast
docker-compose down
docker-compose up -d


which should reset the running programs and make the port available again.

**Comment by Rafaelrds2017** [comment]
The error is:

LOG START
init: exception encountered during start phase:
Address already in use in bind ()

So I can not start this radio, nor even dare other doors. ex 8014 ...

If you need to access my vps, just ask me ..
________________________________
De: Locutor Rafael <rafael_15silva@hotmail.com>
Enviado: terça-feira, 18 de junho de 2019 02:32
Para: AzuraCast/AzuraCast
Assunto: RE: [AzuraCast/AzuraCast] Liquidsoap does not start (#1673)

root@srv2:/var/azuracast# docker-compose up -d
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

root@srv2:/var/azuracast# login as: root
root@165.22.46.179's password:
Welcome to Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-50-generic x86_64)
________________________________
De: SlvrEagle23 <notifications@github.com>
Enviado: terça-feira, 18 de junho de 2019 02:27
Para: AzuraCast/AzuraCast
Cc: Rafael Rodrigues; Mention
Assunto: Re: [AzuraCast/AzuraCast] Liquidsoap does not start (#1673)


@Rafaelrds2017<https://github.com/Rafaelrds2017> This may be caused by an error in how our internal process management works.

On your host server, try running:

cd /var/azuracast
docker-compose down
docker-compose up -d


which should reset the running programs and make the port available again.

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 Where did you put your `docker.sh` utility script? The directions for installation say to put it in `/var/azuracast`, which is why I added that directory. You should change the directory to match whatever directory you actually are using instead.

**Comment by Rafaelrds2017** [comment]
ssh via command line. I only know via commands. because my programmer can only answer in a few weeks or months. I'm without a programmer to help me.
________________________________
De: SlvrEagle23 <notifications@github.com>
Enviado: terça-feira, 18 de junho de 2019 02:42
Para: AzuraCast/AzuraCast
Cc: Rafael Rodrigues; Mention
Assunto: Re: [AzuraCast/AzuraCast] Liquidsoap does not start (#1673)


@Rafaelrds2017<https://github.com/Rafaelrds2017> Where did you put your docker.sh utility script? The directions for installation say to put it in /var/azuracast, which is why I added that directory. You should change the directory to match whatever directory you actually are using instead.

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 That's not what I'm asking you. That's the method of connection, not the directory where you put things once connected.

I understand you're really not familiar with this stuff, but you have to be able to tell me what directory you put things into, otherwise I really can't tell you where to run commands. Basically, run the commands I put above:

```
docker-compose down
docker-compose up -d
```

wherever you put the `docker.sh` file.

**Comment by Rafaelrds2017** [comment]
Ok I'll try.

Can you provide me the previous version?
I already created several vps from scratch and nothing.
I need to create 35 Radios. the doors do not support. In previous versions I had no problems with the ports, and unfortunately I ended up deleting my droplet.

maybe the bug is in ubuntu.
________________________________
De: SlvrEagle23 <notifications@github.com>
Enviado: terça-feira, 18 de junho de 2019 02:52
Para: AzuraCast/AzuraCast
Cc: Rafael Rodrigues; Mention
Assunto: Re: [AzuraCast/AzuraCast] Liquidsoap does not start (#1673)


@Rafaelrds2017<https://github.com/Rafaelrds2017> That's not what I'm asking you. That's the method of connection, not the directory where you put things once connected.

I understand you're really not familiar with this stuff, but you have to be able to tell me what directory you put things into, otherwise I really can't tell you where to run commands. Basically, run the commands I put above:

docker-compose down
docker-compose up -d


wherever you put the docker.sh file.

**Comment by ErnestPH** [comment]
@Rafaelrds2017 It's not downgradable… If your programmer is not around. I can offer help. Just let me know.

**Comment by Rafaelrds2017** [comment]
[cid:8da841ee-ba1c-4c82-a4d6-df6e4544ef37]

________________________________
De: Locutor Rafael <rafael_15silva@hotmail.com>
Enviado: terça-feira, 18 de junho de 2019 02:56
Para: AzuraCast/AzuraCast
Assunto: RE: [AzuraCast/AzuraCast] Liquidsoap does not start (#1673)


Ok I'll try.

Can you provide me the previous version?
I already created several vps from scratch and nothing.
I need to create 35 Radios. the doors do not support. In previous versions I had no problems with the ports, and unfortunately I ended up deleting my droplet.

maybe the bug is in ubuntu.
________________________________
De: SlvrEagle23 <notifications@github.com>
Enviado: terça-feira, 18 de junho de 2019 02:52
Para: AzuraCast/AzuraCast
Cc: Rafael Rodrigues; Mention
Assunto: Re: [AzuraCast/AzuraCast] Liquidsoap does not start (#1673)


@Rafaelrds2017<https://github.com/Rafaelrds2017> That's not what I'm asking you. That's the method of connection, not the directory where you put things once connected.

I understand you're really not familiar with this stuff, but you have to be able to tell me what directory you put things into, otherwise I really can't tell you where to run commands. Basically, run the commands I put above:

docker-compose down
docker-compose up -d


wherever you put the docker.sh file.

**Comment by Rafaelrds2017** [comment]
ok
________________________________
De: ErnestPH <notifications@github.com>
Enviado: terça-feira, 18 de junho de 2019 02:59
Para: AzuraCast/AzuraCast
Cc: Rafael Rodrigues; Mention
Assunto: Re: [AzuraCast/AzuraCast] Liquidsoap does not start (#1673)


@Rafaelrds2017<https://github.com/Rafaelrds2017> It's not downgradable… If your programmer is not around. I can offer help. Just let me know.

**Comment by Rafaelrds2017** [comment]
> @ Rafaelrds2017 Não é degradável ... Se o seu programador não está por perto. Eu posso oferecer ajuda. Apenas me avise.

I accept help. I'm from Brazil.

**Comment by ErnestPH** [comment]
> > @ Rafaelrds2017 Não é degradável ... Se o seu programador não está por perto. Eu posso oferecer ajuda. Apenas me avise.
> 
> I accept help. I'm from Brazil.

Ok please visit my site or email me (check my Github). It's inappropriate to make this support box as a chatbox. And to make it clear. It's free… won't ask anything. thanks!
