### ISSUE TITLE
Known issue: Ports not reopened after deleting stations

### ISSUE THREAD

**Issue by SlvrEagle23** [AzuraCast/AzuraCast#1674]
We are aware of multiple reports that when deleting stations via the web interface or API, the ports assigned to the station aren't "freed" and made available to subsequent stations.

This is possibly caused by the fact that our Supervisor RPC client, which we use to manage the spin-up, spin-down and changing of radio station AutoDJ and broadcasting processes, does not actually wait for a service to terminate before returning to PHP that the process has successfully terminated. It's possible that this creates a race condition with the subsequent removal of the station's `supervisor.conf` file, where it's removed before the services can actually spin down completely.

We are working on a fix for this and will report back shortly.

**Comment by ErnestPH** [comment]
I have manually killed the port using fuser -k 8010/tcp… please try it

**Comment by SlvrEagle23** [comment]
I've made some changes to how processes are spun up and down by Supervisor, and this should help with these types of issues.
