### ISSUE TITLE
Azuracast Auto Update

### ISSUE THREAD

**Issue by sheiyla** [AzuraCast/AzuraCast#1676]
Hello, you must add the command <**echo "y" | ./docker.sh update**> on the documentation to show everyone how to perform an automatic update of azuracast without giving an answer to the question of the prompt !

**Comment by ErnestPH** [comment]
I would prefer to manually update the software… to make sure there's no bugs...

**Comment by sheiyla** [comment]
it's a manual update, it's just to avoid answering the question what will serve the reseller !

**Comment by ErnestPH** [comment]
> it's a manual update, it's just to avoid answering the question what will serve the reseller !

Thanks! This is a cool feature. But this ticket should be closed already :)

**Comment by Vaalyn** [comment]
I'm not sure if that is something that needs to be explicitly mentioned in the documentation as that is just a normal `echo`+ piping in linux.

If you really want to have this added to the docs as an optional "btw. here is how you can avoid having to always answer y to the update" you can send us a PR for the docs on [this repository](https://github.com/AzuraCast/azuracast.com).

**Comment by ErnestPH** [comment]
Thanks @Vaalyn I created a pull request for this. Thanks @sheiyla for starting this...
