### ISSUE TITLE
Unable to add music, returns JSON and Internal Server errors.

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#1678]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu 18.4
**Describe the bug**
Unable to add music and unable to change music settings
**To Reproduce**
Go to your station
Move down to add music
Attempt to add music
Consult the console for an error. 
**Expected behavior**
It to add the music and allow us to edit it. 
**Relevant Logs**
```
VM144:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at d.<anonymous> (files:530)
    at d.<anonymous> (flow-8c41da7745.min.js:2)
    at l (flow-8c41da7745.min.js:2)
    at d.fire (flow-8c41da7745.min.js:2)
    at e.chunkEvent (flow-8c41da7745.min.js:2)
    at g.event (flow-8c41da7745.min.js:2)
    at XMLHttpRequest.doneHandler (flow-8c41da7745.min.js:2)
```
**Screenshots**
[Console Error ](https://i.imgur.com/fgmP7hx.png)
[Networking Tab error](https://i.imgur.com/PqHuFyw.png)
**Device(s):**
 - Device: Deskop 
 - OS: Windows
 - Browser: Chrome
 - Version: Latest

**Additional context**

**Comment by gammaw** [comment]
I have the same.

**Comment by SlvrEagle23** [comment]
@gammaw @SC2Mitch An nginx 500 error should be reporting via stderr into the Docker container, so you can inspect it by running, on the host:

```
docker-compose logs -f web
```

and then attempting to upload again.

We've made some recent changes to our Docker web container in an effort to resolve issues like this, so you may want to make sure you're on the very latest Docker image as well.

**Comment by gammaw** [comment]
@SlvrEagle23 Here is excerpt of the log, the part where the upload is initiated and it runs to some mkdir error: 

```
web_1       | 149.200.1.39 - - [19/Jun/2019:19:00:22 +0000] "GET /station/1/files/upload?csrf=q6NOemHJ9f&file=&searchPhrase=&flowChunkNumber=3&flowChunkSize=1048576&flowCurrentChunkSize=1048576&flowTotalSize=4482611&flowIdentifier=4482611-postapok3mp3&flowFilename=postapok3.mp3&flowRelativePath=postapok3.mp3&flowTotalChunks=4 HTTP/2.0" 204 0 "https://bla.com/station/1/files" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "-"
web_1       | 2019/06/19 19:00:22 [crit] 56#56: *38904 mkdir() "/tmp/azuracast_nginx_client/1" failed (2: No such file or directory), client: 149.200.1.39, server: localhost, request: "POST /station/1/files/upload HTTP/2.0", host: "bla.com", referrer: "https://bla.com/station/1/files"
web_1       | 149.200.1.39 - - [19/Jun/2019:19:00:22 +0000] "POST /station/1/files/upload HTTP/2.0" 500 588 "https://bla.com/station/1/files" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "-"
web_1       | 149.200.1.39 - - [19/Jun/2019:19:00:22 +0000] "GET /api/nowplaying/1 HTTP/2.0" 200 2892 "https://bla.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "-"
web_1       | 2019/06/19 19:00:22 [crit] 56#56: *38904 mkdir() "/tmp/azuracast_nginx_client/2" failed (2: No such file or directory), client: 149.200.1.39, server: localhost, request: "POST /station/1/files/upload HTTP/2.0", host: "bla.com", referrer: "https://bla.com/station/1/files"
```

**Comment by SlvrEagle23** [comment]
@gammaw I suspect `tmpreaper` is being a little eager and trying to 'clean up' the parent nginx temp files directory, which of course causes nginx to fail any time it needs to buffer either responses or incoming requests (i.e. file uploads).

I've just pushed up a new image to the Docker Hub for the `web` container, and that'll take about 10-15 minutes to build. After that point, you can update your installation and it will pull down the new image.

The reason restarting Docker seems to "fix" the issue is likely due to the fact that for the first 12 hours or so of the system's operation, `tmpreaper` won't try to delete any files as they haven't passed the modification-time threshold needed to delete them.

**Comment by SlvrEagle23** [comment]
The new web image has been built and can be pulled down by updating AzuraCast itself via `./docker.sh update`.

**Comment by SC2Mitch** [comment]
After deploying the update it appears to be resolved, all good on your end @gammaw ?

**Comment by gammaw** [comment]
@SlvrEagle23 thanks! I see no new commit on GitHub (last one is no. 1606 22 hours ago), I suppose the new web container doesn't affect the code base, is it like this? I'm asking to understand that an update may not only be effective if I see a new commit on GitHub. 
@SC2Mitch I just did the update and will test it later (probably it makes sense to test after the threshold fired).

**Comment by SlvrEagle23** [comment]
@gammaw The AzuraCast updates also update the Docker container images, which are based on other repositories inside the AzuraCast organization. If you update, both components will update regardless of whether there's a new commit on this repo.

**Comment by ErnestPH** [comment]
> @gammaw The AzuraCast updates also update the Docker container images, which are based on other repositories inside the AzuraCast organization. If you update, both components will update regardless of whether there's a new commit on this repo.

This explains why sometimes, if I updated docker… it fixes some minor bugs even though I didn't see any commits at all. Now I get it. Thanks @SlvrEagle23

**Comment by SC2Mitch** [comment]
Thanks for the fixes, Slvr, will close as it appears to be resolved, will re-open should issue return.

**Comment by gammaw** [comment]
> After deploying the update it appears to be resolved, all good on your end @gammaw ?

@SC2Mitch it seems working fine again. Thanks.
