### ISSUE TITLE
interference during the live broadcast.

### ISSUE THREAD

**Issue by istahilagi** [AzuraCast/AzuraCast#1680]
I have set the "Advanced DJ / Streamer Buffer Time (Seconds)" setting
I fill in the number 10
but there was still interference during the live broadcast.
streaming sound suddenly dies briefly every few seconds
what's the solution?

**Comment by Vaalyn** [comment]
Have you tried to increase this value until it doesn't happen anymore?
Another thing would be to look into the Liquidsoap logs to see if there are any errors.

**Comment by bayubad** [comment]
I have the same problem. Here is the LS log:

2019/06/20 17:30:13 [mksafe:3] Switch to safe_blank with forgetful transition.
2019/06/20 17:30:16 [mksafe:3] Switch to http_6399 with transition.
2019/06/20 17:30:25 [mksafe:3] Switch to safe_blank with forgetful transition.
2019/06/20 17:30:27 [mksafe:3] Switch to http_6399 with transition.
2019/06/20 17:30:39 [mksafe:3] Switch to safe_blank with forgetful transition.
2019/06/20 17:30:42 [mksafe:3] Switch to http_6399 with transition.
2019/06/20 17:31:12 [mksafe:3] Switch to safe_blank with forgetful transition.
2019/06/20 17:31:14 [mksafe:3] Switch to http_6399 with transition.

**Comment by Vaalyn** [comment]
@bayubad same question to you, have you increased the `Advanced DJ / Streamer Buffer Time (Seconds)` gradually to check if that problem stops if the value if high enough?

**Comment by bayubad** [comment]
Yes, from 1 to 120 seconds and the problem persists.

**Comment by istahilagi** [comment]
sometimes one day this problem is over, but another day this problem recurs.

**Comment by mateus007** [comment]
That was just happening to me here. I tried to set 60 seconds, but Liquid Soap does not start... 
After seeing logs, could make it work by setting buffer to 20 seconds:

liquidsoap.log:

    Invalid value at line 68, char 138-140:
      Maximum buffering inferior to pre-buffered data.

config (line 68):

    live = audio_to_stereo(input.harbor("/", id="batistadocalvario_input_streamer", port=8015, user="shoutcast", auth=dj_auth, icy=true, max=30., buffer=60., icy_metadata_charset="UTF-8", metadata_charset="UTF-8", on_connect=live_connected, on_disconnect=live_disconnected))

I guess max define the limit of buffer, so a lower value could be the correct one.
