### ISSUE TITLE
Error Update

### ISSUE THREAD

**Issue by Takumi86ES** [AzuraCast/AzuraCast#1681]
Error update ssh: https://i.gyazo.com/65fb49747e9c3651612b6e54ce05d6ac.png

2019/06/20 16:37:47 Waiting for: tcp://mariadb:3306
2019/06/20 16:37:47 Waiting for: tcp://influxdb:8086
2019/06/20 16:37:47 Connected to tcp://mariadb:3306
2019/06/20 16:37:47 Problem with dial: dial tcp 172.20.0.4:8086: connect: connection refused. Sleeping 1s
2019/06/20 16:37:48 Problem with dial: dial tcp 172.20.0.4:8086: connect: connection refused. Sleeping 1s
2019/06/20 16:37:49 Connected to tcp://influxdb:8086
Updating AzuraCast...
(Environment: production)

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 122683392) (tried to allocate 9437184 bytes) in phar:///usr/bin/composer/src/Composer/Repository/ComposerRepository.php on line 588

Fatal error: Out of memory (allocated 122683392) (tried to allocate 9437184 bytes) in phar:///usr/bin/composer/src/Composer/Repository/ComposerRepository.php on line 588
rsync: change_dir "/var/azuracast/new" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
Composer could not find a composer.json file in /var/azuracast/www
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Could not open input file: bin/azuracast.php
2019/06/20 16:37:57 Command exited with error: exit status 1
azuracast_mariadb_1 is up-to-date
azuracast_redis_1 is up-to-date
azuracast_stations is up-to-date
azuracast_influxdb_1 is up-to-date
Creating azuracast_web_1 ... done
Update complete!

Error Web: https://i.gyazo.com/46891b8e50f20124585c832a9ba8923e.png

**Comment by macbroadcast** [comment]
Same error

**Comment by pabpineda** [comment]
I still report the same error when updating. FIle not found

**Comment by macbroadcast** [comment]
Glad i had automatic backup on Digital Ocean activated :smiley_cat:

**Comment by Takumi86ES** [comment]
I have lost the files on my radio. Thank you.

**Comment by macbroadcast** [comment]
No you havent @Takumi86ES , i did that a month ago, i pulled all my files from the partition and set it up again, but i would just wait till we got a reply from @SlvrEagle23  :sunglasses:

**Comment by Takumi86ES** [comment]
Digitalocean use and I think I lost everything.

**Comment by macbroadcast** [comment]
You lost nothing just take a deep breath

**Comment by Vaalyn** [comment]
I haven't seen composer running out of memory while installing or updating AzuraCast before but this should be easily preventable by adjusting the memory PHP is allowed to use.

You can do this by editing the azuracast.env file and adding the following line (or if the line is already there but commented out, remove the `# ` infront of it and increasing the amount):

```
PHP_MEMORY_LIMIT=256M
```

**Comment by ErnestPH** [comment]
@Takumi86ES I encounter this problem also, you can as well create a swap space- https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-18-04

Once I did that, I just run the update again without any error anymore...

**Comment by SlvrEagle23** [comment]
@Takumi86ES I strongly doubt you lost your station data or anything like that. You should always be sure to back up your station data, especially if it's particularly valuable; it's easier than ever now with our web-based backup panel (accessible from "Administration").

@Vaalyn and @ErnestPH have already provided the two leading instructions: give PHP more memory to access with Vaalyn's change to the environment variables, and create a swap space on your VPS to help prevent the program from running out of memory.

This is especially common if you're using, say, the $5 DigitalOcean VPS with the lowest tier of available memory. In cases like this, the swap space is absolutely essential to preventing services (particularly MariaDB) from running out of memory.

**Comment by Takumi86ES** [comment]
I was able to recover everything. I did the memory tutorial and it worked. Thank you.
