### ISSUE TITLE
Master station

### ISSUE THREAD

**Issue by Conor-Burns** [AzuraCast/AzuraCast#1682]
Is it possible to create multiple stations with different DJs and use the stream urls in a playlist to schedule the program on a master station?

**Comment by ErnestPH** [comment]
As far as I understand the logic, yes it's possible...

**Comment by Conor-Burns** [comment]
Ok tyvm for your fast response!
I have tried it and failed adding the mp3 stream url of one station into a playlist.
If i play that playlist it states that the station is offline.
I have tried m3u, pls and direct stream.
What is the correct way of doing this?

**Comment by afonsosantos** [comment]
@Conor-Burns Hi!

That issue related to m3u playlists may be related to my issue (#1721), but you can use the **Direct Stream** option, and provide a `.mp3` URL to play.
