### ISSUE TITLE
Distributed architecture

### ISSUE THREAD

**Issue by bayubad** [AzuraCast/AzuraCast#1683]
I want to use distributed architecture, separating my station source with the one that is delivered to my listeners.
In this way serve my listeners from multiple locations, taking advantage the capacity of the entire infrastructure I own.

**Comment by Vaalyn** [comment]
You should be able to setup a "master" instance of AzuraCast that does all the playlist management and DJ connections and so on and then create "slave" instances of AzuraCast that just relay the "master" instance.
