### ISSUE TITLE
http docker 

### ISSUE THREAD

**Issue by Luislife2004** [AzuraCast/AzuraCast#1685]
**Using Docker installation method**

**Host Operating System**

**Describe the bug**

**Comment by Luislife2004** [comment]
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by Vaalyn** [comment]
That means that the Docker daemon is not running. Try starting it via `service docker start`. If that fails could you check what kind of server you are using? We had some reports with the same error message where the VPS that was used wasn't a real VM but just a LXC or OpenVZ container.

**Comment by Luislife2004** [comment]
I use a OpenVZ Server

**Comment by Vaalyn** [comment]
Then you'll not be able to run Docker easily on that VPS. You should switch to VPS that is created via KVM, VMWare, Xen, etc.

Running Docker containers in OpenVZ containers can theoretically work if the VPS is correctly configured but I doubt that a generic VPS is configured for that and running AzuraCast in such a special environment is not something that we currently plan on supporting.

**Comment by Luislife2004** [comment]
root@srv52395:/var/azuracast# service docker start
Job for docker.service failed because the control process exited with erro.
See "systemctl status docker.service" and "journalctl -xe" for details.

**Comment by NurLutix** [comment]
> Then you'll not be able to run Docker easily on that VPS. You should switch to VPS that is created via KVM, VMWare, Xen, etc.

**Comment by Vaalyn** [comment]
I'll close this issue now as the problem can only be resolved by switching to a different virtualization technology or by experimental tinkering with Docker to get it running inside a container, but this is outside of the support we offer for AzuraCast.

**Comment by ErnestPH** [comment]
> VPS that is created via KVM, VMWare, Xen, etc.

@Vaalyn This is a bit off topic. But I am planning to have a dedicated server but doesn't know how to configure yet… But based upon your reply above…

I can make a VPS from a dedicated server using KVM without pre partitioning them right? Like create a KVM VPS using Virtualizor interface…?

**Comment by Vaalyn** [comment]
> @Vaalyn This is a bit off topic. But I am planning to have a dedicated server but doesn't know how to configure yet… But based upon your reply above…
> 
> I can make a VPS from a dedicated server using KVM without pre partitioning them right? Like create a KVM VPS using Virtualizor interface…?

I haven't used Virtualizor so I can't say much about it but if you can create KVM VMs with it then yeah that should work.
