### ISSUE TITLE
Storage Display for Admin

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#1687]
Hello guys

This is a feature opinion. It would be good if we could see the storage display on the Admin side. Total MB or GB using of all of our stations. 

Greetings!

**Comment by SlvrEagle23** [comment]
@radiolize When you went to create this issue, there should've been a big giant warning message that literally says:

> **PLEASE DO NOT SUBMIT FEATURE REQUESTS THROUGH GITHUB!**
> 
> We have a special web site dedicated to submitting and voting on new features for completion.
> 
> Submit your feature request at [features.azuracast.com](https://features.azuracast.com/).

If you deleted that template in order to post this issue, you should instead follow its instructions, as feature requests are not processed here.
