### ISSUE TITLE
How to hide any admin information for custom users?

### ISSUE THREAD

**Issue by isBrainDed** [AzuraCast/AzuraCast#1688]
I am hosting several radio stations using AzuraCast and I have tried to setup a custom user, that has access to a page. My only issue is that I don't want to expose the password and username of the Icecast service to the users. I only want the users to be able to manage the Station media and restart the station if needed, but View Station Page shows the Icecast administration password which could be used to grab the IP's of the listeners to the station.

Is there any way to disable that? Or can I change the password for the icecast administration page, so that people can't access those logs.

**Comment by SlvrEagle23** [comment]
@isBrainDed This is a valid point. The credentials for Icecast/SHOUTcast administration should only be available to those with the "Manage Station Broadcasting" permission, as those passwords could give one the ability to kick listeners or otherwise interrupt broadcasting.

I will update this shortly.

**Comment by isBrainDed** [comment]
Just one more question. For the sake of changing the playlist on the fly. Shouldn't the person that is able to manage stations playlist using "Manage Station Media", also be able to restart the AutoDJ without the Manage Broadcast permission? They are already able to wipe the playlist clean, so might as well make it easier for them to apply the changes to the playlists.

**Comment by SlvrEagle23** [comment]
@isBrainDed We automatically tell Liquidsoap to reload playlists after any changes regardless of the permissions the user has, so they don't need to manually run the "Restart AutoDJ" command to trigger that reload.

**Comment by isBrainDed** [comment]
Alright, then that's it from me, thank you for quick response and for patching this.

**Comment by SlvrEagle23** [comment]
@isBrainDed The main profile has been updated to not show the Icecast login credentials to anyone who can view the profile, but rather only to people who have the "Manage Station Broadcasting" permission, as administration of the frontend is technically station broadcasting management.

Sorry for the delay in getting back to this one!
