### ISSUE TITLE
Question: Import multiple backups to one VPS

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#1692]
Hi experts of Azuracast,

Is it possible to migrate multiple backups from multiple VPS to a new VPS?

example… 1st VPS have 2 stations, 2nd VPS have 1 station -> migrate them all to a new VPS. The new VPS will now have 3 stations.

Thanks!

**Comment by Vaalyn** [comment]
I don't think that this is currently possible with the default command without some manual tinkering as the restore operation basically wipes the existing data of the new server.

You could in theory merge the backup files together if you know what should be placed where in the backup. I don't think there is anything preventing this from working but I also don't think anyone of us has tested this yet so there might be some unforseen issues.

**Comment by ErnestPH** [comment]
Yeah. Thanks for the clarification.
