### ISSUE TITLE
2FA not working

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1694]
**Using Docker installation method**
No

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
The 2FA is not working.

**To Reproduce**

1. Go to 'Account'
2. Click on 'Enable 2FA'
4. See problem

**Relevant Logs**
I don't think there is any relevant log

**Screenshots**

![image](https://user-images.githubusercontent.com/47743654/59979979-a3d6da80-95ef-11e9-9adb-4cf416fc68a0.png)

**Device(s):**
 - Device: Desktop
 - OS: Windows 10 1903
 - Browser: Opera (Chrome and Firefox don't work either)
 - Version: latest

**Comment by SC2Mitch** [comment]
Any error appear in the console or network tab? It works fine for me

**Comment by MrSteelMiner** [comment]
no. nothing.

**Comment by SlvrEagle23** [comment]
@MrSteelMiner When you inspect the QR code image area, what are its contents? It should be an SVG graphic.

**Comment by MrSteelMiner** [comment]
@SlvrEagle23
![image](https://user-images.githubusercontent.com/47743654/59993986-89821880-9652-11e9-933d-a2d7e5c1b06b.png)
I would say, it looks good, but it displays nothing

**Comment by SlvrEagle23** [comment]
@MrSteelMiner Yeah, I can't reproduce this at all on any installation or either theme. I'm not sure what's causing this problem on your end...is there any custom CSS or JS you have in use?

**Comment by MrSteelMiner** [comment]
I have some custom CSS so I removed it temporarily but nothing changed on 2FA

**Comment by MrSteelMiner** [comment]
> Any error appear in the console or network tab? It works fine for me

Just found this:
![image](https://user-images.githubusercontent.com/47743654/60207038-565ba700-9855-11e9-892b-3463652b9d76.png)

**Comment by MrSteelMiner** [comment]
I noticed another thing:
![image](https://user-images.githubusercontent.com/47743654/60207464-41334800-9856-11e9-9782-d4bb714c2efe.png)
Shouldn't there better be the Security-key for the Authenticator and not the full otpauth-url? The key is the last part of this url and with it, Google Authenticator was able to generate 2FA-Codes for my installation.

**Comment by SlvrEagle23** [comment]
@MrSteelMiner Including the full otpauth URL means a lot of clients can include the name of the service and the corresponding e-mail for the account along with the listing.

I'm absolutely not sure why the QR codes just aren't visible in your case, especially considering they're rather simple SVG graphics that aren't sourced from outside the server, and on both themes and on multiple installations we can confirm those codes work, but as long as the TOTP URL is still functional for you I suppose the 2FA functionality is still possible in your case.
