### ISSUE TITLE
could someone help set up commercial radio with icecast live

### ISSUE THREAD

**Issue by comerciosite** [AzuraCast/AzuraCast#1698]
I tried using https://demo.azuracast.com the demo using autodj is correct, since for live commercial radio it gives error mainly in the graphics and the player goes offline

![radiolive](https://user-images.githubusercontent.com/22249551/60030104-c6f99c80-9678-11e9-8463-f03f85d9f333.png)

**Comment by ErnestPH** [comment]
@comerciosite Yes I can help you...

**Comment by comerciosite** [comment]
Hello, very grateful to help me.

How could you help with this live commercial radio setup?
What it takes for you to help me

I'm located in Brazil

**Comment by ErnestPH** [comment]
> Hello, very grateful to help me.
> 
> How could you help with this live commercial radio setup?
> What it takes for you to help me
> 
> I'm located in Brazil

I have to check your settings… please email me your server's credentials or visit my site so we can chat properly. thanks!

**Comment by comerciosite** [comment]
PBy the azuracast player does not play
https://streaming.livebroadcast.biz/public/classica

**Comment by comerciosite** [comment]
here it plays normally
https://streaming.livebroadcast.biz/radio/8010/classica

**Comment by comerciosite** [comment]
Acessei o seu site

**Comment by ErnestPH** [comment]
> Issue - Stream is offline when connecting live but is playing actually. AutoDJ is set to off. 


Upon checking this issue is related to #867. This bug has been going on and the devs are fixing it… You can close this one...

**Comment by comerciosite** [comment]
Thank you for your help.
