### ISSUE TITLE
Live Listeners information not working

### ISSUE THREAD

**Issue by floogulinc** [AzuraCast/AzuraCast#170]
The Live Listeners section of the backend shows no listeners and when manually accessing the api at `/api/station/1/listeners` it gives this error:

<blockquote>
<h1>Slim Application Error</h1><p>The application could not run because of the following error:</p><h2>Details</h2><div><strong>Type:</strong> Error</div><div><strong>Message:</strong> Cannot use object of type Entity\Api\Listener as array</div><div><strong>File:</strong> /var/azuracast/www/app/modules/api/controllers/ListenersController.php</div><div><strong>Line:</strong> 63</div><h2>Trace</h2><pre>#0 /var/azuracast/www/app/src/App/Mvc/Controller.php(100): Controller\Api\ListenersController-&gt;indexAction()
#1 /var/azuracast/www/app/src/App/Mvc/Resolver.php(42): App\Mvc\Controller-&gt;dispatch(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#2 [internal function]: App\Mvc\Resolver-&gt;App\Mvc\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /var/azuracast/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#4 /var/azuracast/www/vendor/slim/slim/Slim/Route.php(340): Slim\Handlers\Strategies\RequestResponse-&gt;__invoke(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(122): Slim\Route-&gt;__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#6 /var/azuracast/www/vendor/slim/slim/Slim/Route.php(316): Slim\Route-&gt;callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /var/azuracast/www/vendor/slim/slim/Slim/App.php(476): Slim\Route-&gt;run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /var/azuracast/www/app/bootstrap/services.php(265): Slim\App-&gt;__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 [internal function]: Closure-&gt;{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#10 /var/azuracast/www/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Closure), Array)
#11 [internal function]: Slim\DeferredCallable-&gt;__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#12 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(73): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#13 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(122): Slim\App-&gt;Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#14 /var/azuracast/www/vendor/slim/slim/Slim/App.php(370): Slim\App-&gt;callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /var/azuracast/www/vendor/slim/slim/Slim/App.php(295): Slim\App-&gt;process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /var/azuracast/www/web/index.php(9): Slim\App-&gt;run()
#17 {main}</pre>
</blockquote>

**Comment by SlvrEagle23** [comment]
@floogulinc This one should be fixed by the latest commit.
