### ISSUE TITLE
Songs repeat more often

### ISSUE THREAD

**Issue by NurLutix** [AzuraCast/AzuraCast#1700]
Hey,
I am using AzuraCast via Docker on Ubuntu 16.04.

Since then I have had AzuraCast with the problem that songs are often repeated. I looked at the article to see what you can do about it, but it didn't help me. 
![Screenshot_1](https://user-images.githubusercontent.com/35920440/60078438-354b6700-972c-11e9-810b-f4a804013ee8.png)

Screenshot of the playlist configuration: (They're in German.)
![Screenshot_2](https://user-images.githubusercontent.com/35920440/60078529-6461d880-972c-11e9-9b94-456ca082b81d.png)
![Screenshot_3](https://user-images.githubusercontent.com/35920440/60078533-662b9c00-972c-11e9-9dd4-6c8589e66421.png)

Anybody recognize a mistake? Because it doesn't make much sense for a song to come back within about 10 minutes, because my library contains at least 400 songs. I also get stress with GEMA, because a song can only be played every hour.

Greetings
Luca Stratmann

**Comment by Rafaelrds2017** [comment]
songs are often repeated

**Comment by SlvrEagle23** [comment]
We have made improvements to our AutoDJ's duplicate artist/title prevention which should significantly help with this.
