### ISSUE TITLE
supervisor: couldn't chdir to /var/azuracast/stations/XXXXX/config: EACCES supervisor: child process was not spawned

### ISSUE THREAD

**Issue by j2sdwebradio** [AzuraCast/AzuraCast#1701]
installation method. -->Docker 

**Host Operating System**
-ubuntu 16.04

1. Go to Reload Icecast
2. See error supervisor: couldn't chdir to /var/azuracast/stations/rush/config: EACCES
supervisor: child process was not spawned
-->

**Comment by SlvrEagle23** [comment]
Closing as this was answered in the subsequent #1702.
