### ISSUE TITLE
Permissions Mismatch After Running Ansible-to-Docker Migration

### ISSUE THREAD

**Issue by j2sdwebradio** [AzuraCast/AzuraCast#1702]
None of the 4 radios play! we need urgent support!

**Comment by SC2Mitch** [comment]
You lack so many details, what exactly goes wrong? What do the logs say?

**Comment by j2sdwebradio** [comment]
supervisor: couldn't chdir to /var/azuracast/stations/XXX/config: EACCES
supervisor: child process was not spawned

**Comment by SC2Mitch** [comment]
Any screenshots or ways to replicate this? Everything is working fine on my end.

**Comment by j2sdwebradio** [comment]
https://ibb.co/wp76vzJ

https://ibb.co/tmvX3Lc

**Comment by SC2Mitch** [comment]
AzuraCast fully up to date? I can't replicate this on my own server

**Comment by j2sdwebradio** [comment]
I made a migration from standalone update to docker

**Comment by ErnestPH** [comment]
the best practical way is to fresh install a docker installation… then add your stations and songs to it… using the same ports. IMO

**Comment by j2sdwebradio** [comment]
I already tested deleted and delivered, I do not want to reinstall all the songs!

**Comment by ErnestPH** [comment]
If you have backups you can export it easily or upload songs vis SFTP… otherwise, the issue will take too long and you want some fast solution, right?

**Comment by SC2Mitch** [comment]
You can just backup as ErnestPH said and upload them back via SFTP.

**Comment by j2sdwebradio** [comment]
I do not have the fiber I have only DSL, that's why I want to avoid the upload

**Comment by ErnestPH** [comment]
@j2sdwebradio If you need urgent help, let me see what I can do… - visit my website and let's chat

**Comment by j2sdwebradio** [comment]
i just made an iSCSI target on another server to copy my files

**Comment by SlvrEagle23** [comment]
@j2sdwebradio The issue is likely just a simple permissions problem with your `/var/azuracast/stations` directory on the host. The easiest solution would be to run:

```
chown -R 1001 /var/azuracast/stations
```

This issue is likely caused because your Ubuntu installation already had a "user 1001" prior to installing AzuraCast, which made the `azuracast` user an ID different from 1001, which causes a permissions conflict in Docker. This should fix that issue while allowing your installation to stay in place.

**Comment by SlvrEagle23** [comment]
@j2sdwebradio Correction: it should be UID 1000. See the updated response.
