### ISSUE TITLE
playing_next null on api 

### ISSUE THREAD

**Issue by j2sdwebradio** [AzuraCast/AzuraCast#1703]
**Using Docker installation method**
Docker 

**Host Operating System**
 Ubuntu 18.04

**Describe the bug**
api/nowplaying/1
When I look at API including the branch playing next it to NULL
Can you know the next song?

**Comment by Vaalyn** [comment]
This is a known issue. We disabled the "next song" functionality as we have some problems with the AutoDJ in that regards so this data is currently always null. It's currently unclear if we are able to fix this or if we have to completely remove that functionality as we depend on help from upstream for that.
