### ISSUE TITLE
The server drops and restarts after reaching the limit 1048576, how to solve this problem?

### ISSUE THREAD

**Issue by comerciosite** [AzuraCast/AzuraCast#1704]
The server drops and restarts after reaching the limit 1048576, how to solve this problem?
"WARN slave / slave_startup process has 1048576 max file descriptor limit"

**Comment by Vaalyn** [comment]
Could you post some more detailed logs from your installation? This warning has never been a problem for the installations that I know so I doubt that this is what crashes your instance.

In general you should use the bug reporting issue template to report issues to us as this includes necessary information for to know what kind of environment we are dealing with. Please edit your post to add the information.

**Comment by comerciosite** [comment]
** Using the Docker installation method **
<! - Yes / No (indicate "No" if you are using the Ansible (Bare-metal / Traditional) installation method).

Yes

** Operating system host **
<! - Indicates what is your host operating system (ie Ubuntu 16.04, MacOS High Sierra, Windows 10). ->

Ubuntu 18.04 lts | DigitalOcean

** Describe the bug **
<! - A clear and concise description of what the bug is. ->
"The WARN slave / slave_startup process has a maximum file descriptor limit of 1048576"


**Reproduce**
<! -
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
->
4 -
The WARN slave / slave_startup process has a maximum file descriptor limit of 1048576
WARN source / source_read Nothing received in / classic for 3 seconds


**Expected behavior**
<! - A clear and concise description of what you expected to happen. ->
Let it not restart the server

** Relevant Records **
<! - Paste into any error messages or abnormal entries you see in your logs (see above). ->
The WARN slave / slave_startup process has a maximum file descriptor limit of 1048576
WARN source / source_read Nothing received in / classic for 3 seconds

** Screenshots **
<! - If applicable, add screenshots to help explain your problem. ->

![erro](https://user-images.githubusercontent.com/22249551/60195062-d875ac80-9810-11e9-99a1-340422ae244b.png)

** Device (s): **
- Device: <! - [for example Desktop, iPhone6] ->
- SO: <! - [for example iOS] ->
- Browser: <! - [for example, chrome, safari] ->
- Version: <! - [for example 22] ->
Android device

** Additional Context **
<! - Add another context on the problem here. ->
Send feedback
Historic
Saved
Community

**Comment by comerciosite** [comment]
https://streaming.livebroadcast.biz/radio/8010/classica

**Comment by comerciosite** [comment]
4 GB Memory / 60 GB Disk / NYC1 - Ubuntu 18.04.2 x64

**Comment by SlvrEagle23** [comment]
@comerciosite Icecast has a weird say of flagging certain things as "WARN" level errors that honestly aren't errors at all and don't merit any attention. In this case, they're just informing you of what the file descriptor limit is, not that it reached it.

I would look at Liquidsoap, the AutoDJ, to see about the possible cause of this problem. Icecast is just reporting that it didn't receive any audio, so whatever is broadcasting to it (whether a relay or live DJ or the AutoDJ) is where you should look for troubleshooting.

**Comment by comerciosite** [comment]
I'm just using Live Commercial Radio.
Liquidsoap, AutoDJ are off.
Even on public page does not ring
https://streaming.livebroadcast.biz/public/classica

Tapping this link only
https://streaming.livebroadcast.biz/radio/8010/classica

![erro](https://user-images.githubusercontent.com/22249551/60203475-154a9f00-9823-11e9-9cd6-d3071c8b4324.png)
![erro1](https://user-images.githubusercontent.com/22249551/60203485-1aa7e980-9823-11e9-9077-5684451c9d79.png)

**Comment by comerciosite** [comment]
When mounting /classica.mp3 I shot the end of the .mp3 url, the azuracast graphic and player runs normally.
Other errors appear in the icecast log

**Comment by comerciosite** [comment]
disconnected again and immediately restarteddisconnected again and immediately restarted

![erro](https://user-images.githubusercontent.com/22249551/60213675-62863b00-983a-11e9-94e8-dc77cd1412d1.png)

**Comment by SlvrEagle23** [comment]
@comerciosite It doesn't do us much good to just keep telling us the same problem is happening without providing extra information that may help us diagnose why.

If you're not using the AutoDJ, I'm assuming you're connecting directly to the Icecast source via a DJ/streaming client using its source password? If so, the issue is very likely with that connection timing out periodically, not with Icecast or any other part of the AzuraCast stack.

This is one of many reasons we switched to having our own internal Streamer/DJ setup use Liquidsoap as the handler for incoming DJ connections: because this allows us to fine-tune the buffer settings, avoid listener downtime when a DJ connects or disconnects, allow a smooth transition between the AutoDJ music and the live broadcast, and authenticate each DJ with their own login credentials.

I would strongly recommend trying that option (turning on the AutoDJ and using its internal Streamers/DJs tool) instead.

**Comment by comerciosite** [comment]
oI left only /classica without the url .mp3, player and graph are working normally.
I'll follow the logs
I tested with autodj and did not run live

https://streaming.livebroadcast.biz/public/classica

**Comment by comerciosite** [comment]
I left only /classica without the url .mp3, player and graph are working normally.
I'll follow the logs
I tested with autodj and did not run live

**Comment by SlvrEagle23** [comment]
@comerciosite I'm afraid I really don't understand what you're saying in these replies.

**Comment by comerciosite** [comment]
I'm also afraid of not expressing myself correctly, because I'm in Brazil and I use the Google translator.
Yes it is ok to url

Iin the icecast logs shows other errors, print

![erro1](https://user-images.githubusercontent.com/22249551/60221644-d6334280-9850-11e9-87f4-fb6bfbd6d6e7.png)

**Comment by comerciosite** [comment]
![erro](https://user-images.githubusercontent.com/22249551/60222361-68d4e100-9853-11e9-9789-dd76198d3606.png)

**Comment by SlvrEagle23** [comment]
@comerciosite I don't fully understand what the problem is, but in any case it's very likely this problem isn't with AzuraCast itself, but rather your streaming/DJ client or Icecast.
