### ISSUE TITLE
Liquidsoap sound like an FM station, even though my files are high quality files, what can I do to improve the sound quality? Is it related to liquidsoap or AzuraCast?

### ISSUE THREAD

**Issue by FarmanX** [AzuraCast/AzuraCast#1705]
Liquidsoap sound like an FM station, even though my files are high quality files, what can I do to improve the sound quality? Is it related to liquidsoap or AzuraCast?

**Comment by Vaalyn** [comment]
You need to supply us with more information about your setup. Please take a look at the bug report issue template and use that to edit your post.

**Comment by Vaalyn** [comment]
Closing this issue until further information is provided
