### ISSUE TITLE
icecast.xml

### ISSUE THREAD

**Issue by bayubad** [AzuraCast/AzuraCast#1709]
How can I edit icecast.xml (Icecast configuration file)?

**Comment by Vaalyn** [comment]
When editing the `Station Profile` under the section `Broadcasting` you'll find the text field `Advanced Custom Configuration`. There you can add configurations that will automatically be merged with the `icecast.xml`.

**Comment by Medyatr** [comment]
@Vaalyn Hi,

I want to change root url from index page to stream url like shoutcast style. For example http://1.1.1.1:8000 without any mount point.

I use ubuntu 20 and i installed with docker. When i look in to /var/azuracast, there is no any folder or icecast.xml for stations. 

How can i edit icecast.xml for any stations?

Thanks
