### ISSUE TITLE
Dashboard Update Link Broken

### ISSUE THREAD

**Issue by JDBlackman** [AzuraCast/AzuraCast#1712]
**Using Docker installation method**
Yes (Powered by AzuraCast • v0.9.5.1, #fd01cf7 (2019-06-27 21:09) )

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
The update link is broken on the dashboard

![Image of Dashboard](https://i.imgur.com/tX7ZN7M.png)

The link links to https://www.azuracast.com/install.html

**Expected behavior**
Probably should link to https://www.azuracast.com/install/#updating

**Comment by SlvrEagle23** [comment]
@JDBlackman Good catch. Updated!
