### ISSUE TITLE
Problems playlists

### ISSUE THREAD

**Issue by Manuel19861** [AzuraCast/AzuraCast#1715]
Mixing playlists Does not work Reliably

**Comment by SlvrEagle23** [comment]
@Manuel19861 Please put yourself in our shoes. If you received a number of reports that just said "{x} doesn't work", without any context or explanation of what's not working, what's expected, what your specific setup is, etc...would you be able to fix anything at all?

With your previous issues, we have closed them until you edited them to provide more information, or just to follow the initial error template that you have ignored when you first created the issue. Be aware that we won't accept any new issues written like this.
