### ISSUE TITLE
bitrade

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#1716]
Bitrate is not displayed in the local station and on the public page. How to enable its display?

**Comment by SlvrEagle23** [comment]
@susl16c We now use the mount point name in case you want to customize it (i.e. name it "Mobile" instead of the bitrate), but if you leave the name blank it will automatically fill one in based on the bitrate.

**Comment by susl16c** [comment]
I thought there is the ability to output the bitrate that is used in the radio.

**Comment by ErnestPH** [comment]
Yes there is… you can edit it in the Mount points tab

**Comment by susl16c** [comment]
Created a second point with a large bit rate, everything appeared but the audio does not go by the point it writes
HTTP ERROR 401
/radios.mp3?1562244260
portbase=8000
requirestreamconfigs=1
streamid_1=1
streampath_1=/radio.mp3
streamid_2=2
streampath_2=/radios.mp3

**Comment by susl16c** [comment]
ERROR	[SRC 127.0.0.1:45090 sid=1] SHOUTcast 1 source rejected. A source is already connected.
[0m[01;31m2019-07-04 16:21:17	ERROR	[SRC 127.0.0.1:45124 sid=1] SHOUTcast 1 source rejected. A source is already connected.
[0m[01;31m2019-07-04 16:21:21	ERROR	[SRC 127.0.0.1:45126 sid=1] SHOUTcast 1 source rejected. A source is already connected.
[0m2019-07-04 16:21:21	INFO	[DST 109.195.53.143:47012 (xff) sid=1] HTTP client connection accepted. User-Agent: `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36 OPR/62.0.3331.18', UID: 11, GRID: 11
2019-07-04 16:21:23	INFO	[DST 109.195.53.143:47012 (xff) sid=1] HTTP client connection closed (2 seconds) [Bytes: 287555] Agent: `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36 OPR/62.0.3331.18', UID: 11, GRID: 11
[01;31m2019-07-04 16:21:25	ERROR	[SRC 127.0.0.1:45200 sid=1] SHOUTcast 1 source rejected. A source is already connected.
[0m[01;31m2019-07-04 16:21:26	ERROR	[DST 109.195.53.143:47086 (xff) sid=2] HTTP client connection rejected. Stream not available as there is no source connected. Agent: `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36 OPR/62.0.3331.18'

**Comment by susl16c** [comment]
Tell me you can create 2 identical points with different bitrate?

**Comment by afonsosantos** [comment]
@susl16c Hi!

Sure you can, just use differente bitrates for each one, like `64 kbps` and `128 kbps`.

**Comment by susl16c** [comment]
I get a bitrate, but at the same time the transmission speed does not change, but should increase if the bitrate is greater.

**Comment by susl16c** [comment]
I would like to choose the speed, but when I select, the flow does not increase, so I come to the conclusion that this does not work
