### ISSUE TITLE
Timeout on automatic and manual backup

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#1717]
using Docker installation
OS --> Ubuntu 18.04

Hi,

When using the new automatic backup tool (nice idea BTW!!), it would start at scheduled time but after some time it would just stop and delete the backup file. By looking at the log (see below), it looks like there is a timeout on the process. My database is big and need more than 2hours to get it done. Could you please help ?

[2019-07-02 18:58:29] AzuraCast.ERROR: Exception when processing message type App\Message\BackupMessage: The process "'zip' '-r' '-n' '.tar.gz:.zip:.jpg:.mp3:.ogg:.flac:.aac:.wav' '/var/ [....]   exceeded the timeout of 3500 seconds. [] []

**Comment by Vaalyn** [comment]
Hey, could you provide some information about your installation?
Media count and total size, number of stations, CPU cores, HDD or SSD, RAM.

In general we should make the timeout configurable via en environment variable.

**Comment by griffon56** [comment]
Hi, @Vaalyn !

The total number of media is 12507 using 241,5 GB storage space.
I am running 6 stations.

My configuration is following 👍 

CPU
Intel Core i3-530 - 2.93 GHz - 2 core(s)

RAM
4GB - DDR3

STORAGE
2x 1TB (HDD SATA)

OS
Ubuntu 18.04 LTS (The Bionic Beaver), 64 bits

**Comment by Vaalyn** [comment]
That's quite a bit of data. The zipping already doesn't compress media files to speed up the process but in this case it's just taking longer than anticipated. You could theoretically get an SSD and a faster CPU to speed up the process but I think a good enough solution would be to make the timeout adjustable like I said. Then you can increase the timeout to prevent this issue from happening.

**Comment by griffon56** [comment]
Hi, when running backup from CLI (with docker), I also encounter the timeout error.

```
......
var/azuracast/stations/xxxxx/media/xxxxxx.mp3
var/azuracast/stations/xxxx/media/xxxxx/xxxx.mp3
var/azuracast/stations/xxxxx/media/xxxx/xxxxx.mp3
var/azuracast/stations/xxxx/media/xxxx/xxxx.mp3
var/azuracast/stations/xxxxx/media/xxxx/xxxxx.mp3

In Process.php line 1233:

  The process "'tar' 'zcvf' '/tmp/cli_backup.gz' 'tmp/azuracast_backup_mariad
  b/db.sql' 'tmp/azuracast_backup_influxdb' 'var/azuracast/stations/xxxxx/media' 'var/azuracast/stations/xxxxxx/album_art' 'var/azuracast/s
  tations/xxxxx/media' 'var/azuracast/stations/xxxxxalbum_ar
  t' 'var/azuracast/stations/rxxxxxx/media' 'var/azuracast/stations/xxxxx/album_art' 'var/azuracast/stations/xxxxx/media' 'var/azuracast/st
  ations/xxxxx/album_art' 'var/azuracast/stations/xxxxx/media' 'var/
  azuracast/stations/xxxx/album_art' 'var/azuracast/stations/xxxxx/
  media' 'var/azuracast/stations/xxxxxx/album_art'" exceeded the timeout of 3
  500 seconds.
```
Can this timout be extended to few hour, or be customizable in the settings ?

Thank you

**Comment by SlvrEagle23** [comment]
@griffon56 I've bumped the backup timeout to 4 hours, which should be more than sufficient for basically any backup task.

**Comment by SlvrEagle23** [comment]
Closing this issue as our timeout limits have been sizably increased, and we have introduced a new system that allows backups to run from the background even when triggered from the web.
