### ISSUE TITLE
M3U playlists not working

### ISSUE THREAD

**Issue by afonsosantos** [AzuraCast/AzuraCast#1721]
Hi!

When setting the source of a playlist as a Remote M3U playlist, it just ignores this playlist and does not play it.
I'm entering `http://air.radiorecord.ru:805/synth_128.m3u` in the Remote URL field, but bellow we can see that the URL does not match this one.

This line repeats in the Liquidsoap logs:

`2019/07/04 01:16:23 [protocol.process:3] Failed to execute curl -sL "http://air.radiorecord.ru:805/synth_128" -o "/tmp/liq-process868eeb.mp3": ("timeout","19.4668200016")`

When using the Remote Stream as source, everything works fine.

**Comment by dubloid** [comment]
AzuraCast • v0.9.9, #5903387 (2020-04-07 4:54)

Everything is the same with me! It works a direct way, but does not work through a playlist. =(
