### ISSUE TITLE
Blocking IPs

### ISSUE THREAD

**Issue by bayubad** [AzuraCast/AzuraCast#1722]
I am looking for blocking a single IP or a range of IPs so they will not be able to connect and listen to radio station.

**Comment by RemBdev** [comment]
You can maybe do this with the ubuntu inbuild firewall.

https://www.guyrutenberg.com/2009/11/07/blocking-ip-range-using-ufw/

**Comment by SC2Mitch** [comment]
If you're using ShoutCast, you can ban them via the Admin Panel.

**Comment by adwinter** [comment]
If you are using Icecast, you can still do it, but it takes a few steps. You need to first add this tag in your "Paths" section:

```
<deny-ip>/path_to_ip_denylist</deny-ip>
```

I'd make sure it goes into the root of your icecast installation. Then in the file, specify the IP address(es) you need to deny. This will drop the connection immediately when they connect to your stream.  Even in the Icecast documentation, it recommends a firewall solution is better. But if you do not have firewall access - this will work.

Andrew
