### ISSUE TITLE
Socket timeout when streaming via BUTT

### ISSUE THREAD

**Issue by barbrastreisand** [AzuraCast/AzuraCast#1723]
**Using Docker installation method**

Yes

**Host Operating System**

Ubuntu 18.04

**Describe the bug**

Am able to connect to the server with BUTT, and sound levels show, but nothing is received by Icecast. The connection will last about 30~ seconds before restarting. When recording as well as streaming, the recording has the sound that I'm trying to hear.

**To Reproduce**

I do not use AutoDJ, so use the source name and password from the Icecast details in BUTT. It connects but there seems to be nothing received by Icecast for AzuraCast to play.

**Expected behavior**

A stream with sound.

**Relevant Logs**

This is what happens while connected. It will do these same 4 lines over and over.

[2019-07-05  22:13:42] WARN source/source_read Nothing received on /stream for 3 seconds
[2019-07-05  22:13:42] WARN source/source_read Nothing received on /stream for 3 seconds
[2019-07-05  22:13:42] WARN source/source_read Nothing received on /stream for 3 seconds
[2019-07-05  22:13:50] WARN source/source_read Disconnecting /stream due to socket timeout

**Comment by JDBlackman** [comment]
I would suggest disabled AutoDJ but still using the streamer accounts to broadcast to the server. BUTT tends to work nicer when connecting via Icecast so use those settings.

**Comment by barbrastreisand** [comment]
How can I use a streamer account with AutoDJ turned off? Can't seem to find an area to view/create streamer accounts without AutoDJ enabled.

**Comment by barbrastreisand** [comment]
Have since changed my setup and reinstalled and can now connect.
