### ISSUE TITLE
SSL does not work with Shoutcast

### ISSUE THREAD

**Issue by ismaelazanza** [AzuraCast/AzuraCast#1725]
I have installed SSL, but streaming does not work, I have verified without using direct SSL with the IP and if it connects. The problem arises when SSL is activated when streaming

**Comment by ErnestPH** [comment]
Did you connect your website to any CDN, like Cloudflare? If yes, then live broadcasting using domain name won't work. Only IP addresses will connect it. here's the explanation #1695 from the developer himself.

**Comment by ErnestPH** [comment]
If not, then in your system administration >> System setting… use the domain name instead of the IP address on Site Base URL and then check Use Web Proxy for Radio, Prefer Browser URL (If Available) and Always Use HTTPS.

**Comment by SlvrEagle23** [comment]
@ismaelazanza SHOUTcast is commercial and proprietary software with limited documentation and access to its source code, and so we're limited in the type of integration we can do with it. In particular, unlike our supplied Icecast installation, you can't use the same SSL certificate that works for the main AzuraCast dashboard for directly serving your radio traffic.

It's possible to work around this issue by enabling the HTTP (port 80/443) proxy, which will route all of your traffic through the same web server as your main dashboard.
