### ISSUE TITLE
SSL stream from 1 radio over subdomain via extra ip address.

### ISSUE THREAD

**Issue by rolradio** [AzuraCast/AzuraCast#1727]
Hello everyone,

This is not a bug but a question if this is possible ..

We need the following solution for our radio station that runs on an azuracast panel together with other radio stations
required:

We have 2 ip addresses on our VPS.
1 is used for azuracast and all common stream links.

For that one station we want the stream address: https://azuracast.shoutcaster.eu/radio/8060/radio.mp3?1562575933 .... Redirect so that it is taken via a subdomain where ip address and port are taken together For example: https : //stream.jukeboxoldiesradio.com ...... that immediately lets the stream play.
We wish this because this address is linked everywhere in the radio overview websites.

So https://stream.jukeboxoldiesradio.com ..... replaces https://azuracast.shoutcaster.eu/radio/8060/radio.mp3?1562575933

We want to use the 2nd IP address for this, so that the A can record from that 2nd IP address.

Is this possible with the built-in proy of azuracast?
The 2nd ip address should then lead to the internal ip address and port of that station in SSL.

Or is it already possible with: Advanced Custom Stream URL in the mount point?
Or what is this for?

Does anyone have a solution? I even want to pay a fee for this, because I have no experience with this.

Thank you for reading,
Marc

**Comment by ivellios1988** [comment]
Not sure if this is possible with AzuraCast, but I managed to achieve that on a separate server running Apache. Here's what I put in my .htaccess:

`<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule ^(.*)$ http://YOUR_AZURACAST_SERVER_ADDRESS:PORT/$1 [P,L]
</IfModule>`

The only problem with this solution, at least in my case, is that the connection drops after some unspecified time - I don't know, 15 minutes, maybe 30, maybe longer...?

Another solution which I used for a very long time was this:

I had a VPS server (a very cheap one, with 20 gigabytes of space on SSD) with Apache, PHP, etc. running on it. Of course I had access to php.ini file, so I modified it and set max_execution_time to some very high value, i. e., 36000 (10 hours). VPS was pretty decent, with 2 gigabytes of RAM and was meant solely to serve as a proxy for my radio (to enable my listeners to listen via a subdomain), so I didn't worry about possible performance issues. Then I created a php file with this piece of code:

`<?php
    $server = "YOUR_SERVER_ADDRESS";
    $port = YOUR_PORT_NUMBER;
    $fp = @fsockopen ($server, $port, $errno, $errstr, 120);
    if ($fp)
    {
        // Here set the correct MIME-Type
        header("Content-type: audio/mpeg");
        // This is the HTTP GET request (i.e. open a file/directory on an HTTP server)
        // Format is GET /{folder}/{filename} HTTP/1.0\r\n
        $request = "GET /; HTTP/1.0\r\n";
        $request .= "Host: ".$server."\r\n";
        $request .= "User-Agent: WinampMPEG/5.11\r\n";
        $request .= "Accept: */*\r\n";
        //$request .= "Icy-MetaData:1\r\n";
        $request .= "Connection: close\r\n\r\n";
        fputs ($fp, $request);
        while (!feof($fp))
        {
            $data = fgets($fp,128);
            if (@strpos($data,"icy-") > -1 || @strpos($data,"ICY ") > -1 || @strpos($data,"content-type") > -1)
            {
                //header($data);
            }
            else
            {
                echo $data;
            }
        }
        fclose ($fp);
    }
?>`

Most of the time, conditions were perfect - no DDoS'es, no server overloads, no restarts needed, usually RAM usage was low as well. My listeners didn't complain much, they could listen to my radio via a subdomain and even with HTTPS - no problems!
