### ISSUE TITLE
DJ account priority

### ISSUE THREAD

**Issue by Peterdewith** [AzuraCast/AzuraCast#1728]
Is there a way to give DJ's a priority?

So if DJ 1 is streaming with priority 1 and DJ 2 with priority 2 start streaming DJ 1 is kick out

**Comment by adwinter** [comment]
I don't think this can be done in the framework of Azuracast, but I've been able to duplicate something like this in the "old days" using Icecast 2 (which I'm pretty sure -KH has the same functionality).. You can do it with fallback mounts. So to explain a little bit:

You setup your stream in `icecast.xml` with fallback points to different mounts... 

- Main Stream: DJ with Priority 1 can connect directly to this and broadcast.
- If no connection to main stream, it will fallback to another mount, say "Mount2".
- DJ with priority 2 connects to "Mount2", but wont actually broadcast until Priority 1 DJ disconnects and Icecast "falls back" to Mount2.
- If no connection to "Mount2" either, then it would fall back to the "autoDJ" mount point (which Azuracast would run presumably).

If I'm not mistaken, if Priority 1 DJ re-connects to the main stream, it would essentially stop the Priority 2 DJ and AutoDJ from broadcasting in favor of the Priority 1 DJ. Keep the password to the main stream only for priority 1 dj's, and have priority 2 dj's connect to "Mount 2", and connect Azuracast to broadcast using the AutoDJ mount.

I haven't tested this myself, but I have had a setup similar in the past. Make sure the station people connect to though is the MAIN STREAM and not any of the mounts. Keep the mounts private and the Main Stream public. I have no idea how to make this work in Shoutcast.

Hope this helps.
