### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by Siriusa77II** [AzuraCast/AzuraCast#173]
I get this when i try to update by Update.sh or install.sh...
`TASK [azuracast-radio : Install LiquidSoap Dependencies] ************************************************************************************************************************************************************************************
failed: [localhost] (item=[u'libpcre3-dev', u'libfdk-aac-dev', u'libmad0-dev', u'libmp3lame-dev', u'libtag1-dev', u'libfaad-dev', u'libflac-dev', u'pkg-config', u'm4']) => {"cache_update_time": 1498310767, "cache_updated": false, "failed": true, "item": ["libpcre3-dev", "libfdk-aac-dev", "libmad0-dev", "libmp3lame-dev", "libtag1-dev", "libfaad-dev", "libflac-dev", "pkg-config", "m4"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'libpcre3-dev' 'libfdk-aac-dev' 'libmad0-dev' 'libmp3lame-dev' 'libtag1-dev' 'libfaad-dev' 'libflac-dev' 'm4' -o APT::Install-Recommends=no' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n libpcre3-dev : Depends: libpcre3 (= 2:8.38-3.1) but 2:8.40-5~ubuntu16.04.1+deb.sury.org+1 is to be installed\n                Depends: libpcrecpp0v5 (= 2:8.38-3.1) but 2:8.40-5~ubuntu16.04.1+deb.sury.org+1 is to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " libpcre3-dev : Depends: libpcre3 (= 2:8.38-3.1) but 2:8.40-5~ubuntu16.04.1+deb.sury.org+1 is to be installed", "                Depends: libpcrecpp0v5 (= 2:8.38-3.1) but 2:8.40-5~ubuntu16.04.1+deb.sury.org+1 is to be installed"]}

RUNNING HANDLER [azuracast-user : send user notification] ***********************************************************************************************************************************************************************************
        to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=21   changed=5    unreachable=0    failed=1
`
AzuraCast runbning on:
NitroGroup VPS
2 core
2GB RAM 
![Image of htop using 2.88gb of 2.00 RAM lol ](http://pict.siriushd.net/kitty_2017-06-25_03-51-15.png) lol!
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

**Comment by 24dubstep** [comment]
TASK [influxdb : Install InfluxDB] *********************************************
fatal: [localhost]: FAILED! => {"cache_update_time": 1498669809, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'influxdb'' failed: Failed to issue method call: No such file or directory\ndpkg: error processing package influxdb (--configure):\n subprocess installed post-installation script returned error exit status 1\nErrors were encountered while processing:\n influxdb\nE: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stderr": "Failed to issue method call: No such file or directory\ndpkg: error processing package influxdb (--configure):\n subprocess installed post-installation script returned error exit status 1\nErrors were encountered while processing:\n influxdb\nE: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stderr_lines": ["Failed to issue method call: No such file or directory", "dpkg: error processing package influxdb (--configure):", " subprocess installed post-installation script returned error exit status 1", "Errors were encountered while processing:", " influxdb", "E: Sub-process /usr/bin/dpkg returned an error code (1)"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\ninfluxdb is already the newest version.\nThe following packages were automatically installed and are no longer required:\n  php7.0-json php7.0-opcache php7.0-readline\nUse 'apt-get autoremove' to remove them.\n0 upgraded, 0 newly installed, 0 to remove and 113 not upgraded.\n1 not fully installed or removed.\nAfter this operation, 0 B of additional disk space will be used.\nSetting up influxdb (1.2.4-1) ...\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "influxdb is already the newest version.", "The following packages were automatically installed and are no longer required:", "  php7.0-json php7.0-opcache php7.0-readline", "Use 'apt-get autoremove' to remove them.", "0 upgraded, 0 newly installed, 0 to remove and 113 not upgraded.", "1 not fully installed or removed.", "After this operation, 0 B of additional disk space will be used.", "Setting up influxdb (1.2.4-1) ..."]}
	to retry, use: --limit @/var/azuracast/www/util/ansible/update.retry

PLAY RECAP *********************************************************************
localhost                  : ok=40   changed=4    unreachable=0    failed=1

**Comment by SlvrEagle23** [comment]
@Siriusa77II Try `./update.sh --full` and see if it resets the correct repositories. Also try `sudo apt-get update && sudo apt-get autoremove` to clean up the unused packages.

**Comment by Siriusa77II** [comment]
i'm back sorry i'm late but we get a lot of issue on this node (outgoing DDoS, Network down, etc...)
and actualy i get this after ./update.sh --full

`TASK [azuracast-radio : Install LiquidSoap Dependencies] ************************************************************************************************************************************************************************************
failed: [localhost] (item=[u'libpcre3-dev', u'libfdk-aac-dev', u'libmad0-dev', u'libmp3lame-dev', u'libtag1-dev', u'libfaad-dev', u'libflac-dev', u'pkg-config', u'm4', u'aspcud']) => {"cache_update_time": 1500126971, "cache_updated": false, "failed": true, "item": ["libpcre3-dev", "libfdk-aac-dev", "libmad0-dev", "libmp3lame-dev", "libtag1-dev", "libfaad-dev", "libflac-dev", "pkg-config", "m4", "aspcud"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'libpcre3-dev' 'libfdk-aac-dev' 'libmad0-dev' 'libmp3lame-dev' 'libtag1-dev' 'libfaad-dev' 'libflac-dev' 'm4' -o APT::Install-Recommends=no' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n libpcre3-dev : Depends: libpcre3 (= 2:8.38-3.1) but 2:8.40-5~ubuntu16.04.1+deb.sury.org+1 is to be installed\n                Depends: libpcrecpp0v5 (= 2:8.38-3.1) but 2:8.40-5~ubuntu16.04.1+deb.sury.org+1 is to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " libpcre3-dev : Depends: libpcre3 (= 2:8.38-3.1) but 2:8.40-5~ubuntu16.04.1+deb.sury.org+1 is to be installed", "                Depends: libpcrecpp0v5 (= 2:8.38-3.1) but 2:8.40-5~ubuntu16.04.1+deb.sury.org+1 is to be installed"]}
        to retry, use: --limit @/var/azuracast/www/util/ansible/update.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=15   changed=5    unreachable=0    failed=1

root@VPN01:/var/azuracast/www#
`

**Comment by SlvrEagle23** [comment]
@Siriusa77II I haven't received any other reports of issues similar to this one, and I'm thinking it might possibly be something specific about your instance of Ubuntu, or some specific source that your VPS provider or host is including with Ubuntu that's causing the trouble.

If you're still having the issue, could you run `grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/*` and let me know what it returns? I'm curious if there are any out-of-the-ordinary sources in the list.

Also, if you're using a VPS from a commercial provider and wouldn't mind letting me know which provider that is, that may be helpful for future issues.

**Comment by Siriusa77II** [comment]
` 
root@VPN01:~# grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/*
/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse
/etc/apt/sources.list:# deb http://archive.ubuntu.com/ubuntu xenial-updates main restricted universe multiverse
/etc/apt/sources.list:
/etc/apt/sources.list:deb http://archive.ubuntu.com/ubuntu xenial-security main restricted universe multiverse
/etc/apt/sources.list:
/etc/apt/sources.list.d/ansible-ubuntu-ansible-xenial.list:deb http://ppa.launchpad.net/ansible/ansible/ubuntu xenial main
/etc/apt/sources.list.d/ansible-ubuntu-ansible-xenial.list:# deb-src http://ppa.launchpad.net/ansible/ansible/ubuntu xenial main
/etc/apt/sources.list.d/archive_ubuntu_com_ubuntu.list:deb http://archive.ubuntu.com/ubuntu xenial multiverse
/etc/apt/sources.list.d/archive_ubuntu_com_ubuntu.list:deb-src http://archive.ubuntu.com/ubuntu/ xenial multiverse
/etc/apt/sources.list.d/archive_ubuntu_com_ubuntu.list:deb http://archive.ubuntu.com/ubuntu xenial-updates multiverse
/etc/apt/sources.list.d/archive_ubuntu_com_ubuntu.list:deb-src http://archive.ubuntu.com/ubuntu/ xenial-updates multiverse
/etc/apt/sources.list.d/archive_ubuntu_com_ubuntu.list.save:deb http://archive.ubuntu.com/ubuntu xenial multiverse
/etc/apt/sources.list.d/archive_ubuntu_com_ubuntu.list.save:deb-src http://archive.ubuntu.com/ubuntu/ xenial multiverse
/etc/apt/sources.list.d/archive_ubuntu_com_ubuntu.list.save:deb http://archive.ubuntu.com/ubuntu xenial-updates multiverse
/etc/apt/sources.list.d/archive_ubuntu_com_ubuntu.list.save:deb-src http://archive.ubuntu.com/ubuntu/ xenial-updates multiverse
 `

Actualy, the provider is me, i founded NitroGroup.
if you want any access to the VPS, i can DM you some login, or i can easly reset the VPS, AzuraCast is actually runnin on an other VPS next the this one without any problem.
[http://pict.siriushd.net/chrome_2017-07-24_18-02-36.png](screenshot)

**Comment by SlvrEagle23** [comment]
@Siriusa77II So you've been able to successfully install AzuraCast on this same infrastructure without issue *after* the problem happened?

I think you may have just experienced a dependency problem with the PHP 7.1 repository, and perhaps they later fixed the issue.

**Comment by Siriusa77II** [comment]
@SlvrEagle23 Actualy Yes, Same Host, and no problem after few weeks.
i will try to update the server and re-run the updater.

**Comment by SlvrEagle23** [comment]
@Siriusa77II I'm gonna close this then, since it seems to be a temporary dependency issue with one of Azura's dependencies, and not something we could do anything to fix. If you see the issue pop up again, feel free to make a new ticket.
