### ISSUE TITLE
Error changing default http - https port

### ISSUE THREAD

**Issue by workino** [AzuraCast/AzuraCast#1731]
**Using Docker installation method**

yes by ./docker.sh install

**Host Operating System**

Ubuntu 18.04
**Describe the bug**

is not possible to change default web port and if it's doing trough portainer http://web env is not working anymore

**To Reproduce**

just trying to move from default http/https port to a different one adding 

AZURACAST_HTTP_PORT=8880
AZURACAST_HTTPS_PORT=8443

at the end of the file azuracast.env

If it's doing trough portainer http://web is not working anymore

[workino.zip](https://github.com/AzuraCast/AzuraCast/files/3374325/workino.zip)

**Expected behavior**

**Relevant Logs**

ERROR: for azuracast_web_1  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web_1 (edcc73f9d8caa5413b9af3087c8939c2a8b202a8671cafdd8f67b5fcffeec06c): Bind for 0.0.0.0:443 failed: port is already allocated

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web_1 (edcc73f9d8caa5413b9af3087c8939c2a8b202a8671cafdd8f67b5fcffeec06c): Bind for 0.0.0.0:443 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
You need to change the `.env` file to change the ports. The `.env` file is used to modify values in the `docker-compose.yml` (which is what is needed here) and the `azuracast.env` file is used to modify the environment inside of the containers.

**Comment by workino** [comment]
i did it. u can see in env file attached :)

**Comment by Vaalyn** [comment]
I looked at your attached .zip file and there is just a file called `azuracast.env` but you need a file called `.env` (I'm not shortening the name of the file here, it needs to be just `.env`).

**Comment by pawel06281990** [comment]
Hello,

I have this problem, I have changed the ports at 90 and 440 


The system that I have installed is centos 7

Everything was installed beautifully at the end I got such an error

```
ERROR: container 081d5b6a13c15e3996bf822e2e17ff1610af3732b64d14c1534da7dada44efb5: driver "overlay2" failed toremove root filesystem: remove /var/lib/docker/overlay2/b027fa1eb80f39d065ea78dc0117056bf2469586baa693d6055463a415a2e193/merged: device or resource busy
Removing azuracast_web_1
azuracast_influxdb_1 is up-to-date
azuracast_mariadb_1 is up-to-date
azuracast_stations is up-to-date
azuracast_redis_1 is up-to-date
Recreating fa9b09957848_azuracast_web_1 ... error

ERROR: for fa9b09957848_azuracast_web_1  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web_1 (a33491e24b4253fcbdce2a746c349630eb276d72f5dcd06f14395a3c3e1236f7):  (iptablesfailed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 440 -j DNAT --to-destination 172.18.0.6:440 ! -i br-55954bc45e29: iptables: No chain/target/match by that name.
 (exit status 1))

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web_1 (a33491e24b4253fcbdce2a746c349630eb276d72f5dcd06f14395a3c3e1236f7):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 440 -j DNAT --to-destination 172.18.0.6:440 ! -i br-55954bc45e29: iptables: No chain/target/match by that name.
 (exit status 1))
ERROR: Encountered errors while bringing up the project.
```
What's the problem??
