### ISSUE TITLE
Sending e-mail when mount state changes

### ISSUE THREAD

**Issue by emiryapici** [AzuraCast/AzuraCast#1732]
Hello

How can i send e-mail when icecast mounts on and off? I could doing it on my independent icecast server bu i don't know how can i do this on AzuraCast.

Thanks for this awesome project!

**Comment by SlvrEagle23** [comment]
@emiryapici We already have web hooks for when a DJ connects or disconnects...would that solve your problem? AzuraCast is built so that Icecast mounts don't connect and disconnect when a DJ connects or disconnects, as this interrupts the listener experience.

**Comment by VinylVault** [comment]
@SlvrEagle23 yes there are Webhooks, I wonder if there is an option to expand the ability of the webhooks offers.   Currently there is Discord, Twitter, Facebook posting.  There are 2 other options that I would love to see offered, a simple admin email, when a broadcaster connects and disconnects, and also the ability to offer an email alert when a specific broadcaster connects, to a `per-DJ` subscriber list.

**Comment by SlvrEagle23** [comment]
@VinylVault These things are definitely possible, but you should submit them on our [list of overall requested features](https://features.azuracast.com/), since there's a constant supply of work for us to do and it's really a matter of what we have the time and interest to get to.
