### ISSUE TITLE
Ran out of ports when creating 50th station. Now can't delete station

### ISSUE THREAD

**Issue by kevev** [AzuraCast/AzuraCast#1735]
Similar to this bug: https://github.com/AzuraCast/AzuraCast/issues/1411

I can not delete the 50th station after error on creating stating no ports available.

Now get error when attempting to delete: 500 BAD_NAME: station_51 FaultException.php: 32

Would it be possible to implement a preventive measure to prevent creation of stations when there are no available ports.

**Comment by SlvrEagle23** [comment]
@kevev The initial fix for this, which should allow deletion of stations even if Supervisor doesn't register them as a program group, is live.

**Comment by kevev** [comment]
Thank You! I was able to delete the station after updating Azuracast.  :)
