### ISSUE TITLE
Cant play mono files since i updated to  AzuraCast  v0.9.5.1,

### ISSUE THREAD

**Issue by arnebakken** [AzuraCast/AzuraCast#1737]
Hi,

I updated to  version yesterday v0.9.5.1, and now Liquidsoap cant play monofiles.
I have a mixed music library with both stereo and mono encoded mp3-files. I know that this has been a issued before, and as I can recall there were applied to function "audio_to_stereo" but it dont work since i updated.

Error in Liquidsoap log:
2019/07/11 10:02:19 [decoder:3] Unable to decode "/var/azuracast/stations/fumu_music_bank/media/ORG - Easypop (ORIGINAL)/190430 (with mp3gain)/jessie_ware_-_want_your_feeling_-_easy_pop_-_2016-08.mp3" as {audio=2;video=0;midi=0}!

IDo I need to convert all my monofiles to stereo or is there any easy workaround, all my files worked before I updated to the latest version?

Thanks in advance!
Kind regards, Arne

**Comment by SlvrEagle23** [comment]
@arnebakken Interesting...we still have an `audio_to_stereo` call in our Liquidsoap configuration that's meant to catch those issues. I think our previous option of putting it on literally every function call was actually the way we had to do that...I'll ask upstream and see what's going on there.

**Comment by SlvrEagle23** [comment]
@arnebakken This should be fixed as of the update released a few minutes ago. I spoke with the Liquidsoap folks and they mentioned that there are a number of steps in the configuration process that require that all audio coming in be the same number of tracks, so our previous "put `audio_to_stereo` everywhere" strategy was actually appropriate.

**Comment by arnebakken** [comment]
Thanks! Super!! I will update to the latest release! Again, thanks for all your great work!

**Comment by AmsterdamFM** [comment]
We are now experiencing the exact same issues as mentioned by @arnebakken . It used to work fine. Don't know the exact moment the code broke....

Our version is v0.9.8.1, #1346fa3 (2020-03-11 2:58) • Docker

**Liquidsoap log** shows:

2020/03/12 11:39:22 [decoder.wav/aiff:3] WAV file "/var/azuracast/stations/amsterdamfm/media/news/headlines.wav" has content type {audio=1;video=0;midi=0} but {audio=2;video=0;midi=0} was expected.
2020/03/12 11:39:22 [decoder:3] Unable to decode "/var/azuracast/stations/amsterdamfm/media/news/headlines.wav" as {audio=2;video=0;midi=0}!

These lines ar e repeated hundreds of times in the log files. 6 times per second and there is a break of about 2 seconds.

**The liquidsoap config** shows this for the affected play list.

playlist_news_half__28allways_weight_2_29 = playlist(id="playlist_news_half__28allways_weight_2_29",mode="randomize",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/amsterdamfm/playlists/playlist_news_half_-28allways_weight_2-29.m3u")
playlist_news_half__28allways_weight_2_29 = cue_cut(id="cue_playlist_news_half__28allways_weight_2_29", playlist_news_half__28allways_weight_2_29)
playlist_news_half__28allways_weight_2_29 = audio_to_stereo(id="stereo_playlist_news_half__28allways_weight_2_29", playlist_news_half__28allways_weight_2_29)
playlist_news_half__28allways_weight_2_29 = drop_metadata(playlist_news_half__28allways_weight_2_29)

So it looks like the audio is converted to stereo with 'audio_to_stereo'

**Comment by SlvrEagle23** [comment]
@AmsterdamFM This should be fixed as of the latest update.

**Comment by AmsterdamFM** [comment]
Yes solved! Thank you!
