### ISSUE TITLE
Stream Offline - Remote-Relay

### ISSUE THREAD

**Issue by NurLutix** [AzuraCast/AzuraCast#1738]
Hey,
I'm using AzuraCast for the AutoDJ.
Say: The stream server is from another provider. (Has reasons)

I'm using Docker on Ubuntu 16.04.

My question is now: Why does the overview permanently show Stream Offline? The AutoDJ works great and the music also runs on the other server.

![Screenshot_3](https://user-images.githubusercontent.com/35920440/61068616-bed88580-a40a-11e9-825b-5deedcada70e.png)

Greetings.

**Comment by SlvrEagle23** [comment]
@NurLutix From the system administration page, try running the "Now Playing" synchronization task (at the bottom) manually, and see what kind of result it's producing.

**Comment by yarik2720** [comment]
I have the same issue.
Trying running "Now Playing" task shows responce like that:
```
Info
Running Now Playing sync task
Debug
HTTP client GET call to http://noisefm.ru:8000/status-json.xsl produced response 200
Debug
NowPlaying adapter response
response
{
    "current_song": {
        "artist": "Snapechak",
        "title": "Factory",
        "text": "Snapechak - Factory"
    },
    "listeners": {
        "current": 16,
        "unique": 0,
        "total": 16
    },
    "meta": {
        "status": "online",
        "bitrate": 128,
        "format": "audio\/mpeg"
    }
}
station
{
    "id": 1,
    "name": "Noise FM"
}
Debug
Response for remote relay
remote
"Noise FM - It's Your Lifestyle - 128 kbps MP3"
response
{
    "current_song": {
        "artist": "Snapechak",
        "title": "Factory",
        "text": "Snapechak - Factory"
    },
    "listeners": {
        "current": 16,
        "unique": 0,
        "total": 16,
        "clients": []
    },
    "meta": {
        "status": "online",
        "bitrate": 128,
        "format": "audio\/mpeg"
    }
}
station
{
    "id": 1,
    "name": "Noise FM"
}
```

**Comment by yarik2720** [comment]
@SlvrEagle23 
In additional: there is no info about played tracks in `Song Playback Timeline` and not updating info in `Song Listener Impact`

**Comment by yarik2720** [comment]
Here is bunch of screenshots, there is only tracks, that played after azuracast installation before first restart.
![chrome_2019-08-18_15-48-17](https://user-images.githubusercontent.com/1839978/63224653-0ef7f400-c1d0-11e9-854b-acf39826b867.png)
![chrome_2019-08-18_15-48-50](https://user-images.githubusercontent.com/1839978/63224654-0ef7f400-c1d0-11e9-92c9-9e9466894553.png)
![chrome_2019-08-18_15-49-03](https://user-images.githubusercontent.com/1839978/63224655-0ef7f400-c1d0-11e9-815f-cdcd9db9bda0.png)
![chrome_2019-08-18_15-49-42](https://user-images.githubusercontent.com/1839978/63224656-0f908a80-c1d0-11e9-9cd1-df32e87d14af.png)
![chrome_2019-08-18_15-50-11](https://user-images.githubusercontent.com/1839978/63224657-0f908a80-c1d0-11e9-9129-98d9a98f27d2.png)

**Comment by SlvrEagle23** [comment]
@NurLutix I worked with @yarik2720 to figure out the cause of this issue, and it should be resolved as of the latest code update this afternoon. Update your installation and let me know if the issue persists.

**Comment by radiolize** [comment]
Hello the problem continues at me. The meta says station offline.

**Comment by KoneSV** [comment]
I have the same problem, it happens only with live streaming

**Comment by pitsch** [comment]
hi there, could reproduce the "stream offline" by switching default mount point to opus. mp3 works fine. aacplus as well. 

>>>

Info
Running Now Playing sync task
Debug
AutoDJ queue is already at current max length (3).
Debug
Timer "BuildQueue" completed in 0.004 second(s).
Debug
HTTP client GET call to http://stations:8000/admin/stats produced response 200
Debug
HTTP client GET call to http://stations:8000/admin/listclients?mount=%2Fradio.opus produced response 200
Debug
Response for mount point
mount
"\/radio.opus"
response
{
    "current_song": {
        "text": "",
        "artist": "",
        "title": ""
    },
    "listeners": {
        "current": 1,
        "unique": 1,
        "total": 1,
        "clients": [
            {
                "uid": "1003",
                "ip": "78.54.212.182",
                "user_agent": "VLC\/3.0.8 LibVLC\/3.0.8",
                "connected_seconds": 578
            }
        ]
    },
    "meta": {
        "status": "offline",
        "bitrate": 0,
        "format": "application\/ogg"
    }
}
station
{
    "id": 1,
    "name": "reboot.fm"
}
Debug
HTTP client GET call to http://stations:8000/admin/stats produced response 200
Debug
HTTP client GET call to http://stations:8000/admin/listclients?mount=%2Flofi.aac produced response 200
Debug
Response for mount point
mount
"\/lofi.aac"
response
{
    "current_song": {
        "artist": "Rodrigo Amarante",
        "title": "O Cometa",
        "text": "Rodrigo Amarante - O Cometa"
    },
    "listeners": {
        "current": 0,
        "unique": 0,
        "total": 0,
        "clients": []
    },
    "meta": {
        "status": "online",
        "bitrate": 48,
        "format": "audio\/aac"
    }
}
station
{
    "id": 1,
    "name": "reboot.fm"
}
Debug
HTTP client GET call to http://stations:8000/admin/stats produced response 200
Debug
HTTP client GET call to http://stations:8000/admin/listclients?mount=%2Fhifi.mp3 produced response 200
Debug
Response for mount point
mount
"\/hifi.mp3"
response
{
    "current_song": {
        "artist": "Rodrigo Amarante",
        "title": "O Cometa",
        "text": "Rodrigo Amarante - O Cometa"
    },
    "listeners": {
        "current": 0,
        "unique": 0,
        "total": 0,
        "clients": []
    },
    "meta": {
        "status": "online",
        "bitrate": 256,
        "format": "audio\/mpeg"
    }
}
station
{
    "id": 1,
    "name": "reboot.fm"
}
Debug
Final NowPlaying Response for Station
id
1
name
"reboot.fm"
np
{
    "current_song": {
        "text": "",
        "artist": "",
        "title": ""
    },
    "listeners": {
        "current": 1,
        "unique": 1,
        "total": 1,
        "clients": [
            {
                "uid": "1003",
                "ip": "78.54.212.182",
                "user_agent": "VLC\/3.0.8 LibVLC\/3.0.8",
                "connected_seconds": 578
            }
        ]
    },
    "meta": {
        "status": "offline",
        "bitrate": 0,
        "format": "application\/ogg"
    }
}
station
{
    "id": 1,
    "name": "reboot.fm"
}
Debug
Writing local nowplaying text file...
Debug
Writing static nowplaying text file...
Debug
Dispatching Nchan notification...
Debug
HTTP client POST call to http://localhost:9010/pub/reboot.fm produced response 404
Debug
Timer "NowPlaying" completed in 0.628 second(s).
Debug
Timer "ReactivateStreamer" completed in 0 second(s).

**Comment by patrickvdhoek** [comment]
Problem still here (or returned..)
