### ISSUE TITLE
 How to broadcast live with 2 Dj at the same time?

### ISSUE THREAD

**Issue by jupapeto17** [AzuraCast/AzuraCast#1739]
I want to broadcast a live broadcast with 2 Djs at the same time. How can I achieve it? I have guests in other cities.

-Using AzuraCast v0.9.4.2 on ubuntu 16.04
-Manual installation (No docker)
-Emission Software: Mixxx
- Broadcasting Service: SHOUTcast DNAS 2

Thanks

**Comment by ErnestPH** [comment]
Interesting question but I think it can't be done. However, there is an alternative… Why not the first DJ instead… connect the other DJ via his stream… like talk show or something...

**Comment by Vaalyn** [comment]
I don't think it is currently possible to achieve this with AzuraCast alone. What the DJs on my radio station do when they want to have multiple people on the stream is they connect to a TS3 server and use [Virtual Audio Cable](https://www.vb-audio.com/Cable/) to get the audio output of TS3 to the streaming software. So there is still just one DJ connected to the stream but multiple people are able to talk on the stream through their connection to the server.

**Comment by ErnestPH** [comment]
> I don't think it is currently possible to achieve this with AzuraCast alone. What the DJs on my radio station do when they want to have multiple people on the stream is they connect to a TS3 server and use [Virtual Audio Cable](https://www.vb-audio.com/Cable/) to get the audio output of TS3 to the streaming software. So there is still just one DJ connected to the stream but multiple people are able to talk on the stream through their connection to the server.

This is interesting. Will check this setup. Thanks!

**Comment by afonsosantos** [comment]
@ErnestPH You can also use Discord, it'a easier to setup!

**Comment by ErnestPH** [comment]
@afonsosantos Thanks for the tip!

**Comment by VinylVault** [comment]
Personally, I use Discord, Skype or FaceTime when I have guests on my radio shows.
