### ISSUE TITLE
Creating 2nd mount point (Shoutcast) shows white blank page

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#1741]
**Using Docker installation method**
Docker -  v0.9.5.1, #4c2989e on Ubuntu 18

**Describe the bug**
Shoutcast Mount point URL gives blank white page

NOTE: I can create Icecast mount point without a problem

**To Reproduce**
1. Create mount point in your Shoutcast version
2. Restart Radio
3. GO to Profile
4. Click the newly created mount point
5. Mount is not playing instead showing a white blank page

**Expected behavior**
The newly created mount point should play

**Relevant Logs**
**Liquidsoap logs**

> 2019/07/12 12:12:37 [frequencyshift_local_2:3] Connecting mount sid#1 for @127.0.0.1...
2019/07/12 12:12:37 [frequencyshift_local_2:2] Connection failed: bad answer: Stream In Use
strange error flushing buffer ... 
2019/07/12 12:12:37 [frequencyshift_local_2:3] Will try again in 3.00 sec.
strange error flushing buffer ... 

**Device(s):**
 Safari MacOS Mojave

**Additional context**
NOTE: I can create Icecast mount point without a problem

**Comment by Vaalyn** [comment]
Are there any errors in the AzuraCast Application Log? You can find that in the System Administration.

**Comment by ErnestPH** [comment]
I check it now while playing the affected mount point… These are the only relevant logs

> [2019-07-12 16:37:29] AzuraCast.INFO: New message of type App\Message\UpdateNowPlayingMessage added to queue. [] []
[2019-07-12 16:37:31] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []
[2019-07-12 16:37:31] AzuraCast.INFO: A tweet was sent less than 3600 seconds ago. Skipping... [] {"station":{"id":1,"name":"Frequency Shift "}}
[2019-07-12 16:37:32] AzuraCast.INFO: Running Now Playing sync task [] []
[2019-07-12 16:37:47] AzuraCast.INFO: Running Now Playing sync task [] []

**Comment by Vaalyn** [comment]
Hmm nothing related to an error while creating the mountpoint in there. Anything in the shoutcast logs?

**Comment by ErnestPH** [comment]
Only this…

> Error: Malformed UTF-8 characters, possibly incorrectly encoded

**Comment by ErnestPH** [comment]
Maybe it has something to do with Shoutcast as Icecast is working just fine

**Comment by ErnestPH** [comment]
@SlvrEagle23 Can you confirm about this bug?
When I tried it after the update it's still not working. Thanks

**Comment by ErnestPH** [comment]
To give further info… creating 2nd mount point using mp3 or acc won't work. It shows white blank space only after it's created

**Comment by SlvrEagle23** [comment]
@ErnestPH It's very much not recommended to use SHOUTcast with AzuraCast if you can at all help it, specifically because SHOUTcast is closed-source proprietary software that we can't inspect, can't fix any bugs with, and can't ensure the integrity of. If you're using the latest version of SHOUTcast (2.6.x), you're likely running into a limit of their newly-imposed "freemium" tier, where the software stops working with non-128kbps-MP3 bitrates unless you pay Radionomy directly. There is no reason to do this and you should instead switch to using Icecast.

**Comment by ErnestPH** [comment]
Yes indeed. Thank you
