### ISSUE TITLE
Stop displaying song tile and song artist

### ISSUE THREAD

**Issue by Bouzec** [AzuraCast/AzuraCast#1744]
Can I stop AzuraCast to display Song Title and Song Artist and other meta data information while playing a song?

**Comment by adwinter** [comment]
@Bouzec. I'm pretty sure "jingle mode" does this... put the songs you don't want to display meta data into a playlist and under Source you can check off "Hide Metadata from Listeners (Jingle Mode)".

Everything in that playlist will now not report meta data to the stream.  You can set it in any of your existing playlists too.. so if its all of your music you don't want to report, just check the box for all of your playlists.

I'm not sure if there is a way you can switch it on or off globally.
Hope this helps.

**Comment by Bouzec** [comment]
Thanks.
Is it possible to use this feature i.e. Hide Metadata from Listeners ("Jingle Mode") while using Remote URL Playlist?

**Comment by afonsosantos** [comment]
@Bouzec Hi!

This feature isn't available via the Web Interface, but you can code a custom playlist using Liquidsoap to play a remote URL and hide the metadata.
