### ISSUE TITLE
Problem with azuracast_default

### ISSUE THREAD

**Issue by pawel06281990** [AzuraCast/AzuraCast#1748]
Hello,

Azuracast receives such a message during installation.Hello,
```
Creating network "azuracast_default" with the default driver
ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-5787b98604ef -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))
Creating network "azuracast_default" with the default driver
ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-53eb39e04d00 -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))
[root@vps azuracast]# install.sh
bash: install.sh: command not found
```

My vps has a centOS 7 system

What is wrong ??

Please help.

**Comment by mikedorst** [comment]
Hey I happened to have this issue too.

Let me guess, you have virtualmin installed? @pawel06281990

**Comment by pawel06281990** [comment]
My system is centOS 7 everything worked as I wanted to change its ports for 8080 it got something like that, it has some problem

**Comment by mikedorst** [comment]
Do you have virtualmin installed?

**Comment by pawel06281990** [comment]
I do not have the centos 7 operating system, I have access to WHM and Cpanel

**Comment by ErnestPH** [comment]
> No, I have a centos 7 operating system, I have access to WHM and Cpanel

It would be better if you have installed azuracast only in the server (more like a dedicated server for azuracast only) to avoid errors...

**Comment by pawel06281990** [comment]
But I already installed it, I just wanted to change the port from 80 to 8080 I did the docker-compose down command and it stopped working

**Comment by Vaalyn** [comment]
I'm not sure why that is but I've found some people having the same issue with Docker on CentOS 7 who could solve the problem just by restarting the Docker daemon with `systemctl restart docker`

Some of those have linked to [this Docker issue](https://github.com/moby/moby/issues/16816). Haven't read it yet so I can't say exactly what it is that's going on there but it seems to be a known issue.

**Comment by pawel06281990** [comment]
And now I got such mistakes

```
Starting azuracast_influxdb_1 ...
Starting azuracast_redis_1    ... error
Starting azuracast_influxdb_1 ... error
Starting azuracast_mariadb_1  ...

ERROR: for azuracast_redis_1  Cannot start service redis: container is marked for removal and cannot be started

ERROR: for azuracast_influxdb_1  Cannot start service influxdb: container is marked for removal and cannot be sStarting azuracast_mariadb_1  ... error

Starting azuracast_stations   ... errorrted

ERROR: for azuracast_stations  Cannot start service stations: container is marked for removal and cannot be started

ERROR: for redis  Cannot start service redis: container is marked for removal and cannot be started

ERROR: for influxdb  Cannot start service influxdb: container is marked for removal and cannot be started

ERROR: for mariadb  Cannot start service mariadb: container is marked for removal and cannot be started

ERROR: for stations  Cannot start service stations: container is marked for removal and cannot be started
ERROR: Encountered errors while bringing up the project.
Starting azuracast_mariadb_1  ... error
Starting azuracast_influxdb_1 ...
Starting azuracast_stations   ...

Starting azuracast_influxdb_1 ... errorrted
Starting azuracast_redis_1    ...

ERROR: for azuracast_influxdb_1  Cannot start service influxdb: container is marked for removal and cannot be sStarting azuracast_redis_1    ... error
Starting azuracast_stations   ... error
ERROR: for azuracast_redis_1  Cannot start service redis: container is marked for removal and cannot be started

ERROR: for azuracast_stations  Cannot start service stations: container is marked for removal and cannot be started

ERROR: for mariadb  Cannot start service mariadb: container is marked for removal and cannot be started

ERROR: for influxdb  Cannot start service influxdb: container is marked for removal and cannot be started

ERROR: for redis  Cannot start service redis: container is marked for removal and cannot be started

ERROR: for stations  Cannot start service stations: container is marked for removal and cannot be started
ERROR: Encountered errors while bringing up the project.
```

And when I wanted to delete it, I can not delete it

**Comment by Vaalyn** [comment]
What command are you using when trying to delete them?

**Comment by pawel06281990** [comment]
The command I use to delete ./docker.sh uninstall Because this command is given on the page

**Comment by Vaalyn** [comment]
That command is not just for removing the containers but for completely uninstalling AzuraCast.

You could try removing all containers by force with `docker rm -f <container id>` for all who are stuck and then try starting AzuraCast again.

**Comment by pawel06281990** [comment]
When I used the docker rm -f <container id> I got something like that
bash: syntax error near unexpected token `newline'

a jestem we folderze /var/azuracast

**Comment by Vaalyn** [comment]
Would you mind trying a server reboot?

**Comment by pawel06281990** [comment]
Yes, I can restart the server

**Comment by pawel06281990** [comment]
Ok, restart the server

**Comment by pawel06281990** [comment]
And there is still the same mistake  

bash: syntax error near unexpected token `newline'

**Comment by Vaalyn** [comment]
And when you try to do what you initially wanted to do, does that work now?

**Comment by pawel06281990** [comment]
Ok, I removed everything.

Now I will try to install again

**Comment by pawel06281990** [comment]
I received an error when trying to reinstall

```
docker-compose: error while loading shared libraries: libz.so.1: failed to map segment from shared object: Operation not permitted
Docker Compose does not appear to be installed. Install Docker Compose now? [Y/n] Y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0   1644      0 --:--:-- --:--:-- --:--:--  1645
100 15.4M  100 15.4M    0     0  2494k      0  0:00:06  0:00:06 --:--:-- 3201k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13258  100 13258    0     0  22409      0 --:--:-- --:--:-- --:--:-- 22395
docker-compose: error while loading shared libraries: libz.so.1: failed to map segment from shared object: Operation not permitted
docker-compose: error while loading shared libraries: libz.so.1: failed to map segment from shared object: Operation not permitted
docker-compose: error while loading shared libraries: libz.so.1: failed to map segment from shared object: Operation not permitted
```
Do I have to install something manually?

**Comment by Vaalyn** [comment]
I think I don't know enough about CentOS to really solve this issue. I can only tell you that a lot of times we had issues here regarding running AC on CentOS it had something to do with Docker / Docker-Compose itself. I'd recommend you to run it on something Debian based like Ubuntu 18.04 or Debian 9 itself.

**Comment by pawel06281990** [comment]
But I already installed it, I had a problem with ports :(

**Comment by Vaalyn** [comment]
I'm sorry that I kind really help you solve the problem. If you want to keep running it on your CentOS machine you should try searching for those errors on Google and see if someone has figured out how to solve that. It doesn't seem like an AC specific thing to me so you might find the same problem on other projects.

**Comment by pawel06281990** [comment]
I understend.

**Comment by pawel06281990** [comment]
I have one more question, I have such a mistake regarding the ports as I am not mistaken, what can I do now ??

```
Creating azuracast_web_1 ... error

ERROR: for azuracast_web_1  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web_1 (1a43b1662d53c4a302a131f79d137f8363c5b4d16cc3be1053619c74cc18aa75): Error starting userlandproxy: listen tcp 0.0.0.0:443: bind: address already in use

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web_1 (1a43b1662d53c4a302a131f79d137f8363c5b4d16cc3be1053619c74cc18aa75): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

**Comment by Vaalyn** [comment]
Normally when you want to run AzuraCast on different ports you'd edit the `.env` file (Make sure not to edit the `azuracast.env`, that's a different file.

See: https://www.azuracast.com/help/faq_docker.html#use-non-standard-ports

**Comment by ErnestPH** [comment]
My best advise is to reinstall your CentOS if you insist in using it :)

**Comment by pawel06281990** [comment]
These two ports have to change 
 AZURACAST_HTTP_PORT=80 AZURACAST_HTTPS_PORT=443 

And after the change I have to use docker-compose down and then this docker-compose up -d ?? 

That's how I understood, I do not know what ports I can change

**Comment by Vaalyn** [comment]
That's exactly what you should do.

> That's how I understood, I do not know what ports I can change

Just so I don't misunderstand you, are you talking about what port ranges these 2 support or do you mean what other AzuraCast services can be configured for?
