### ISSUE TITLE
It could not be deleted / Var / lib / docker / overlay2 / 54a8f7b4efbeebc84dd9e93eec8b0fd8053429b1cfc9dc0b8d4c9343cf118ca7

### ISSUE THREAD

**Issue by pawel06281990** [AzuraCast/AzuraCast#1749]
Hello, I tried to delete this file from the server as root but I can not delete it as it can be removed ??

Because I got such a message

ERROR: container bc3d91fb70e2e543fd6715212137351f6a01c6205c64208605bc5700ba2c6887: driver "overlay2" failed toremove root filesystem: remove /var/lib/docker/overlay2/54a8f7b4efbeebc84dd9e93eec8b0fd8053429b1cfc9dc0b8d4c9343cf118ca7/merged: device or resource busy

**Comment by SC2Mitch** [comment]
Is your radio station that uses that file turned on? If so, turn it off and try again

**Comment by pawel06281990** [comment]
No system wanted to delete it but could not delete it and asks me to remove it but I tried to delete it and I can not do it as well ??

**Comment by pawel06281990** [comment]
The panel in full thanked everyone for help
