### ISSUE TITLE
TASK [mariadb : Remove anonymous users] 

### ISSUE THREAD

**Issue by vdjkelly** [AzuraCast/AzuraCast#175]
TASK [mariadb : Remove anonymous users] *******************************************
failed: [localhost] (item=DELETE FROM mysql.user WHERE User='') => {"changed": false, "cmd": ["mysql", "--defaults-extra-file=/root/.my.cnf", "-ne", "DELETE FROM mysql.user WHERE User=''"], "delta": "0:00:00.003577", "end": "2017-06-30 06:40:28.593404", "failed": true, "item": "DELETE FROM mysql.user WHERE User=''", "rc": 1, "start": "2017-06-30 06:40:28.589827", "stderr": "ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)", "stderr_lines": ["ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)"], "stdout": "", "stdout_lines": []}

RUNNING HANDLER [azuracast-user : send user notification] *************************
	to retry, use: --limit @/var/www/azuracast/util/ansible/deploy.retry

PLAY RECAP ************************************************************************
localhost                  : ok=59   changed=11   unreachable=0    failed=1

**Comment by SlvrEagle23** [comment]
@vdjkelly Was MySQL/MariaDB already set up on this box before AzuraCast installation started? You'll only run into this error if MySQL/MariaDB has a root password already assigned to it that isn't stored in /root/.my.cnf, which it won't if installed by AzuraCast itself.

**Comment by vdjkelly** [comment]
@SlvrEagle23  If it was already installed the only solution that I could find was to leave mariaDB without a password because without the password I installed it but there should be a way that this will be installed if the database gesture was already installed.

Sorry, I do not speak English

**Comment by SlvrEagle23** [comment]
@vdjkelly There is a way to install AzuraCast if you have already set up mariadb, just set up a file in `/root/.my.cnf` with the following contents:

```
[client]
default-character-set = utf8mb4
user=root
password=your_mysql_root_password
```

The installation should then continue without any issues.
