### ISSUE TITLE
Icecast configuration file

### ISSUE THREAD

**Issue by Bouzec** [AzuraCast/AzuraCast#1753]
I try to add the following code into icecast.xml file under Advanced Custom Configuration.

         <directory>
                <yp-url-timeout>15</yp-url-timeout>
                <yp-url>http://icecast-yp.internet-radio.com</yp-url>
        </directory>
      <directory>
    <yp-url-timeout>15</yp-url-timeout>
    <yp-url>http://dir.xiph.org/cgi-bin/yp-cgi</yp-url>
</directory>

But when I save and restart the Icecast (and even the server) the new code in config file is not applied.
There is no trace of any error for this code in Icecast Error Log.

**Comment by SlvrEagle23** [comment]
@Bouzec That's invalid XML. There's an extra `<directory>` in there that probably throws off the configuration.
