### ISSUE TITLE
Installation on debian 10 fails

### ISSUE THREAD

**Issue by Amitxyz** [AzuraCast/AzuraCast#1754]
**Using Docker installation method**
Yes

**Host Operating System**
Debian 10

**Describe the bug**

ERROR: for azuracast_mariadb_1  Cannot start service mariadb: AppArmor enabled on system but the docker-default profile could not be loaded: running `/usr/sbin/apparmor_parser apparmor_parser -Kr /var/lib/docker/tmp/docker-default057550522` failed with output: AppArmor parser error for /var/lib/docker/tmp/docker-default057550522 in /etc/apparmor.d/tunables/global at line 17: Could not open 'tunables/proc'
Creating azuracast_influxdb_1 ... error
error: exit status 1

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by suricloud** [comment]
Any update on installation on debian 10 ?

**Comment by parksquare** [comment]
I'm running the latest version on Debian 10 with no issues.

**Comment by suricloud** [comment]
I am installing on ovh kimsufi server, but evry time also do get the same error during installation?

**Comment by parksquare** [comment]
No idea what 'ovh kimsufi server' is I'm afraid, but I have installed AzuraCast twice over the last few weeks on clean Debian 10 installs running as Hyper-V guests, and it completed both times without any issues at all.

**Comment by SlvrEagle23** [comment]
@suricloud @Amitxyz It appears that this is an "upstream" issue with how the Docker installer is working on Debian 10.

We can confirm that for the vast majority of cases, installing Docker on top of Ubuntu 16.04 or 18.04 (preferred) works without any problems. There are known issues with Docker and CentOS as well, likely because of the same limitations.

**Comment by brammittendorff** [comment]
We have the same problem with debian 10 buster @ ovh and kimsufi so this is no stale issue.

```
ERROR: for azuracast_influxdb_1  Cannot start service influxdb: AppArmor enabled on system but the docker-default profile could not be loaded: running `/usr/sbin/apparmor_parser apparmor_parser -Kr /var/lib/docker/tmp/docker-default8941Starting azuracast_redis_1    ... error
nables/global at line 17: Could not open 'tunables/proc'

error: exit status 1

ERROR: for azuracast_redis_1  Cannot start service redis: AppArmor enabled on system but the docker-default profile could not be loaded: running `/usr/sbin/apparmor_parser apparmor_parser -Kr /var/lib/docker/tmp/docker-default083808053` failed with output: AppArmor parser error for /var/lib/docker/tmp/docker-default083808053 in /etc/apparmor.d/tunables/global at line 17: Could not open 'tunables/proc'
Starting azuracast_mariadb_1  ... error
error: exit status 1

ERROR: for azuracast_mariadb_1  Cannot start service mariadb: AppArmor enabled on system but the docker-default profile could not be loaded: running `/usr/sbin/apparmor_parser apparmor_parser -Kr /var/lib/docker/tmp/docker-default603278660` failed with output: AppArmor parser error for /var/lib/docker/tmp/docker-default603278660 in /etc/apparmor.d/tunables/global at line 17: Could not open 'tunables/proc'
```

And so on.

**Comment by Radiozuhause** [comment]
![image](https://user-images.githubusercontent.com/60838195/146685521-d627fc71-c614-44ec-908c-30b0b7033102.png)
it not running, why?

**Comment by SlvrEagle23** [comment]
@Radiozuhause I've made some changes to our installer script, try running:

```
./docker.sh update-self
./docker.sh install-docker-compose
```

then continuing regular installation, and it should work without any issues now.
