### ISSUE TITLE
Question: Remove a song from a playlist is gone? 

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#1756]
I can vaguely remember but removing a song from a playlist was ought to be easy at that time… Is it gone now? Thanks!

**Comment by SC2Mitch** [comment]
@ErnestPH It should be there still? Heres a gif on my end on how to do it
https://gfycat.com/ElementaryMisguidedHornbill

**Comment by ErnestPH** [comment]
Thank you! That quite confused me. It was certainly not like that before :)
