### ISSUE TITLE
Some issues with the Now Playing in the azura panel

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#1759]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu 18.04
**Describe the bug**
1) Theres no longer a play button and a audio slider
2) The next song doesn't appear at all, its blank
**To Reproduce**
1. Click on a radio of your choice
2. Inspect the "On the air"
3. See issues

**Expected behavior**
A play button to be there, along with the audio slider. The next song to appear also. 
**Relevant Logs**
None that I can locate
**Screenshots**
[HERE](https://puu.sh/DUmWP.png)
**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
I can't reproduce this on the demo installation. Are there any errors in the browsers JavaScript console?

**Comment by SC2Mitch** [comment]
None on the errors, after restarting the radio the up coming song thing works, but it still lacks the play button and sliders and all that joys. I believe that it was removed for some reason though?

**Comment by Vaalyn** [comment]
Maybe we are thinking of different play buttons and sliders. This is what I see in the demo:

![image](https://user-images.githubusercontent.com/13745863/61494197-d1782f00-a9b5-11e9-9426-3f195243789b.png)

![image](https://user-images.githubusercontent.com/13745863/61494217-e0f77800-a9b5-11e9-940f-d6e5c35c3684.png)

**Comment by SC2Mitch** [comment]
Oh there it is! It was normally on this button, but all good, thanks! 
![image](https://user-images.githubusercontent.com/29955942/61496009-c53ea280-a9b2-11e9-99bf-1d603628f0e4.png)
