### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by simpsss** [AzuraCast/AzuraCast#1760]
After the last update, the hd was full (no free space).

lots of "liq-process*.mp3"

https://prnt.sc/ogwmqj

update:
https://prnt.sc/ogxws1

update²:
https://prnt.sc/ogxz2k

update³:
https://prnt.sc/ogy210

**Comment by Vaalyn** [comment]
There is a cronjob should be cleaning that up: https://github.com/AzuraCast/docker-azuracast-radio/blob/master/cron/azuracast

How much data is that in terms of MB?
I can't tell from the screenshots if it's big or not.

**Comment by ErnestPH** [comment]
try to execute this commands after the update…

`docker system prune -a -f`
`docker volume rm $(docker volume ls -qf dangling=true)`

**Comment by simpsss** [comment]
> 
> 
> There is a cronjob should be cleaning that up: https://github.com/AzuraCast/docker-azuracast-radio/blob/master/cron/azuracast
> 
> How much data is that in terms of MB?
> I can't tell from the screenshots if it's big or not.

https://prnt.sc/oh13n5

**Comment by simpsss** [comment]
> 
> 
> try to execute these commands after the update…
> 
> `docker system prune -a -f`
> `docker volume rm $(docker volume ls -qf dangling=true)`

(root!play)(azuracast)# docker system prune -a -f
Total reclaimed space: 0B
(root!play)(azuracast)# docker volume rm $(docker volume ls -qf dangling=true)
1a0b1d28b2748289e7730c87668ebb8faf4c25728fa8d2e5f79987fe488a41d0
1a2812767f297373b8752b6c6e43ad9472c8229cc451c916d69e689bfe9bf4e2
7afafb623fc3fbc70ee5d751a068318fd27949a9880347e66ef8744c5ff52781
28a23f398b8f93298a54c4a3207333d87e38f55860e5c446303fe76e7bb69b99
68cd966defc1461278f926d0967171689072a35e95ebcaec73ce1127fb60ba79
153debdba49c3ed6a7c5439f7cf8f6083f8f9f5b913f358c9ed90d03249baf40
946dea185d5e7f4ecf5696dc6e60b713c952a7c669cc10f4ff61c16f0ef749e7
988d71618d229790ca104f97815a486d22c220faaec305951e7f34a6654cf7b6
2057d99f3b1ee154c1e5fb5c7590656234578d481a3d0023ad13d5fe6a90f2cb
a58c92ffdd68af481ec065a1be645505998516060078ec5b8ada736c9bfcc838
e6c20cb92c5e77e59aee08b6e91b9e8f2543193f7a3631dea4a6d40ec633746e
f46772ae8844c029e8832af61b5acd3a5ce16dad1f1cd9bcfe9c695579f84ab0

but that did not solve

**Comment by afonsosantos** [comment]
@simpsss Do you have any Remote URL playlists?

**Comment by simpsss** [comment]
> 
> 
> @simpsss Do you have any Remote URL playlists? Try to enable `Manual Auto DJ` in the Station Profile, and then restart AzuraCast. Worked for me.

Yes!! thanks!! 

its OK now! :D

**Comment by afonsosantos** [comment]
Thanks @SlvrEagle23 for the help @ Slack.

**Comment by SlvrEagle23** [comment]
@simpsss @afonsosantos I'm in the process of investigating this issue with Liquidsoap, as it's happened before and it caused us to automatically turn off the AzuraCast AutoDJ for any stations using "Remote URL" playlist types.

For now, I've reverted to this mode, where the AzuraCast AutoDJ will only work in the event that you have no remote URL playlists installed.

**Comment by afonsosantos** [comment]
Thanks for the quick fix!

**Comment by internethole** [comment]
How can we use Cloud Storage like Wasabi for music archive storage?
