### ISSUE TITLE
"Once-per-X" playlists not properly spaced apart.

### ISSUE THREAD

**Issue by thedavidde** [AzuraCast/AzuraCast#1761]
Hello,

Playlists to be played at a certain distance, in our case every 30 minutes. Repeated every 15 minutes since the last update. I hope the bug will be fixed as soon as possible. Since we have to send an advertising trigger every 30 minutes.

**Comment by SlvrEagle23** [comment]
@thedavidde I've made some changes to how our AutoDJ handles the "once-per-x" playlists, which should help with this. Update and let me know if it's improved at all.

**Comment by thedavidde** [comment]
@SlvrEagle23 Unfortunately the error still exists, now the corresponding playlist is even played after each song.

**Comment by SlvrEagle23** [comment]
@thedavidde Try again with the latest update. Minor error on my part.

**Comment by thedavidde** [comment]
@SlvrEagle23  Unfortunately the problem persists even after the second update. Now the playlist is repeated every 20 minutes and 5 minutes. Although as said 30 minutes is set.

**Comment by SlvrEagle23** [comment]
@thedavidde "Every 20 minutes and 5 minutes"? Every 25 minutes?

**Comment by thedavidde** [comment]
@SlvrEagle23 The distances vary. First 20 min, then 5.

**Comment by SlvrEagle23** [comment]
@thedavidde Can you send me the most recent segment of your Song Playback Timeline so I can take a closer look?

**Comment by thedavidde** [comment]
Unfortunately I can only send the direct history of my station, because AzuraCast does not always display the playlist in the history. But this should hopefully help you anyway. 😀

![playlist  PNG](https://user-images.githubusercontent.com/48140005/61583865-85a4c180-ab3e-11e9-8b25-70f151ff4d59.PNG)

Everything marked red (Start_Ad_Break) comes from the corresponding playlist.

**Comment by SlvrEagle23** [comment]
@thedavidde I just wrote up a unit test suite that specifically checks if this functionality is working, and I can confirm on my end that it is. Can you also post a screenshot of your "Scheduling" tab for that playlist?

**Comment by thedavidde** [comment]
Hier ein Screenshot vom "Scheduling" Tab.

![screen](https://user-images.githubusercontent.com/48140005/61584144-53499300-ab43-11e9-97dd-512fa1de8e3a.PNG)

**Comment by thedavidde** [comment]
Here is a screenshot of the "Scheduling" tab.

![screen](https://user-images.githubusercontent.com/48140005/61584152-63617280-ab43-11e9-98f1-418093bc390d.PNG)

**Comment by SlvrEagle23** [comment]
@thedavidde Those are normal settings. If you update to the very latest version just released, let me know if it still does the same thing, because it really shouldn't be doing it any more.

(Side note: that subtle gradient on the header and buttons looks nice! Now I want the main app to look like that.)

**Comment by thedavidde** [comment]
The bug seems to be fixed now. Many thanks for the help and the quick solution of the problem. I really appreciate the work and will definitely donate for this great work in the future. 

I am happy to read that you like my gradient. I myself like the gradient very much. That would be something if the main app had this.

**Comment by thedavidde** [comment]
I'm afraid I have to write again. Actually I had assumed that the function now works correctly. However, I have now observed this again a little longer and more closely and the playlist is unfortunately still not played every 30 minutes but more often. But the definition is set to every 30 minutes. 
![funktiofehlerhaft](https://user-images.githubusercontent.com/48140005/61643303-d7fef300-aca2-11e9-900d-ceac39c3f536.PNG)

**Comment by SlvrEagle23** [comment]
@thedavidde I would need to see your specific installation in order to diagnose this issue further.

**Comment by thedavidde** [comment]
@SlvrEagle23  Should I send them the URL of my AzuraCast installation and create an admin account there, so they can have a look at it?

**Comment by SlvrEagle23** [comment]
@thedavidde That would work.

**Comment by thedavidde** [comment]
@SlvrEagle23 Can I send them the login data somehow by private message or mail? Because I don't like to post them here publicly.

**Comment by SlvrEagle23** [comment]
@thedavidde You can [join our Slack community](https://join.slack.com/t/azuracast/shared_invite/enQtNDgyNzA4NzY2MzU3LWNmZjY3MmZlZGI1NzQ0OWEzMDBlMDk4MWVkMGMwMjAwYWQxZjdjYzRkYmM2NDkwZjc3ODI0N2UxY2M3ZjIxZWI) or send me an e-mail via my GitHub e-mail address.

**Comment by SlvrEagle23** [comment]
We've discussed this issue further on Slack and figured out the source of the problem in the AutoDJ's "remove duplicates" functionality.
