### ISSUE TITLE
Ubuntu Docker install - Synthax error while updating from 0.9.5

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#1763]
Updating from 0.9.5 on Docker/Ubuntu install gave me this error:

**To Reproduce**
``# ./docker.sh update-self
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11128  100 11128    0     0  62516      0 --:--:-- --:--:-- --:--:-- 62167
New Docker utility script downloaded.
./docker.sh: line 364: syntax error near unexpected token `('
./docker.sh: line 364: `        echo "  docker stop \$(docker ps -a -q)"'

**Using Docker installation method**

**Comment by Vaalyn** [comment]
I have this sometimes too. Not sure what exactly goes wrong but re-downloading the script via `./docker.sh update-self` works for me.
