### ISSUE TITLE
play only once ignored

### ISSUE THREAD

**Issue by Virusjuh** [AzuraCast/AzuraCast#1765]
I have jingles set that play only once for an hour.
But since the last update it looks likes he ignores the setting only once

**Comment by SlvrEagle23** [comment]
@Virusjuh The "loop playlist once" feature is specific to Liquidsoap, and our AzuraCast AutoDJ (that filters out duplicate songs and allows you to see "playing next") doesn't support this feature. You can use this feature again by turning on the "Manual AutoDJ" setting on your station's profile, which will disable the AzuraCast AutoDJ and use Liquidsoap exclusively.
