### ISSUE TITLE
help me pls

### ISSUE THREAD

**Issue by nickloud** [AzuraCast/AzuraCast#1769]
I cannot create a station after installation.

https://ibb.co/s96GM87

**Comment by SlvrEagle23** [comment]
@nickloud This can happen if you spent too long on the form. Resubmitting the form should help.

**Comment by nickloud** [comment]
@SlvrEagle23 it does not help, I have already installed 15 times on different machines

**Comment by SlvrEagle23** [comment]
@nickloud You've tried installing it _15_ different times and had the exact same CSRF validation error on that exact same page?!

I think it may be your browser at that point...what browser/OS are you using? Any plugins?

(We have a template when filling out bug reports and that should've been filled out here.)

**Comment by nickloud** [comment]
@SlvrEagle23 yes, there is always the same error on the same page, nothing can be saved.

i use google chrome, ubuntu os 18.04x64

**Comment by nickloud** [comment]
@SlvrEagle23 I will install it again and give you the address

**Comment by nickloud** [comment]
@SlvrEagle23 I used the opera and it was created) thanks)

**Comment by SlvrEagle23** [comment]
@nickloud Happy you could get it working. It could possibly have to do with any extensions you have installed that are modifying the CSRF field's value (it's a hidden field, so if you're autofilling information, it may be modifying that as well).
