### ISSUE TITLE
Real time bandwith monitor on the dashboard

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#177]
Hello,
Would be nice if you could add real time bandwith monitor on the azuracast dashboard also.
We could  then see the incoming and outgoing traffic.

**Comment by SlvrEagle23** [comment]
@surihost I'm closing this issue for now, as it unfortunately is likely outside of the scope of AzuraCast. In particular, it would be very difficult to implement a solution that could oversee bandwidth usage for both traditional installations and Docker-based ones, where this information may not even be made available to the application.

If anyone has any novel solutions on how to accomplish this in a platform like AzuraCast, please feel free to comment on this thread.
