### ISSUE TITLE
DJ Connect Error

### ISSUE THREAD

**Issue by danyalsaleemqureshi** [AzuraCast/AzuraCast#1770]
Hello, I am Using UBUNTU 16 , and INSTALLATION Method Ansible, I am Creating Radio First of All Normally on DJ Page There will be 2 different ports Like 8065 , 8064, on my Radio's page its showing only 1 on Both Like 8065 for Both, 2nd I am unable to connect via DJ Tested With BroadCast My Self App on android and SAM BC on PC. Here is some collected Logs

2019/07/21 14:02:15 [harbor:3] Adding mountpoint '/' on port 8065
2019/07/21 14:02:15 [playlist_default:3] Loading playlist...
2019/07/21 14:02:15 [playlist_default:3] No mime type specified, trying autodetection.
2019/07/21 14:02:15 [playlist_default:3] Playlist treated as format application/x-mpegURL
2019/07/21 14:02:15 [playlist_default:3] Successfully loaded a playlist of 0 tracks.
2019/07/21 14:02:15 [error_jingle:3] "/var/azuracast/www/resources/error.mp3" is static, resolving once for all...
2019/07/21 14:02:15 [error_jingle:3] Prepared "/var/azuracast/www/resources/error.mp3" (RID 0).
2019/07/21 14:02:15 [jalfm_local_1:3] Connecting mount sid#1 for @127.0.0.1...
2019/07/21 14:02:15 [jalfm_local_1:3] Connection setup was successful.
2019/07/21 14:02:15 [threads:3] Created thread "wallclock_main" (1 total).
2019/07/21 14:02:15 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2019/07/21 14:02:15 [jalfm_live_switch:3] Switch to jalfm_safe_fallback.
2019/07/21 14:02:15 [jalfm_safe_fallback:3] Switch to error_jingle.
2019/07/21 14:02:15 [dummy:3] Source failed (no more tracks) stopping output...
2019/07/21 14:02:15 [lang:3] Authenticating DJ: RJ
2019/07/21 14:02:15 [lang:3] AzuraCast Raw Response: 
2019/07/21 14:02:15 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/07/21 14:02:15 [lang:3] AzuraCast DJ Auth Response: true
2019/07/21 14:02:15 [decoder:3] Method "MAD" accepted "audio/mpeg".
2019/07/21 14:02:15 [lang:3] DJ Source connected! [("icy-pub","1"), ("icy-name","N/A"), ("icy-notice1","Broadcastmyself/1.0"), ("User-Agent","Broadcastmyself/1.0"), ("icy-genre","N/A"), ("icy-br","64"), ("icy-url","N/A"), ("Content-Type","audio/mpeg")]
2019/07/21 14:02:15 [jalfm_live_switch:3] Switch to jalfm_live_fallback with transition.
2019/07/21 14:02:15 [jalfm_live_fallback:3] Switch to blank_6460.
2019/07/21 14:02:16 [lang:3] AzuraCast Live Connected Response: received
2019/07/21 14:02:16 [threads:3] Created thread "harbor source feeding" (2 total).
2019/07/21 14:02:16 [jalfm_input_streamer:3] Decoding...
2019/07/21 14:02:16 [lang:3] Authenticating DJ: shoutcast
2019/07/21 14:02:16 [lang:3] AzuraCast DJ Auth Response: true
2019/07/21 14:02:16 [jalfm_input_streamer:3] New metadata chunk ? --  .
2019/07/21 14:02:17 [lang:3] AzuraCast Raw Response: 
2019/07/21 14:02:17 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/07/21 14:02:20 [lang:3] AzuraCast Raw Response: 
2019/07/21 14:02:20 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/07/21 14:02:20 [jalfm_live_fallback:3] Switch to audio_to_stereo_6457 with transition.
2019/07/21 14:02:22 [lang:3] AzuraCast Raw Response: 
2019/07/21 14:02:22 [lang:3] AzuraCast Error: Delaying subsequent requests...

**Comment by danyalsaleemqureshi** [comment]
This Logs Too


2019/07/21 14:29:07 [main:3] Liquidsoap 1.3.7
2019/07/21 14:29:07 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.1 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.9 camomile=1.0.1 faad=0.4.0
2019/07/21 14:29:07 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/07/21 14:29:07 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/07/21 14:29:07 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/07/21 14:29:07 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/07/21 14:29:07 [decoder:3] Method "MAD" accepted "/var/azuracast/www/resources/error.mp3".
2019/07/21 14:29:07 [threads:3] Created thread "generic queue #1".
2019/07/21 14:29:07 [threads:3] Created thread "generic queue #2".
2019/07/21 14:29:07 [threads:3] Created thread "non-blocking queue #1".
2019/07/21 14:29:07 [threads:3] Created thread "non-blocking queue #2".
2019/07/21 14:29:07 [harbor:3] Adding mountpoint '/' on port 8005
2019/07/21 14:29:07 [playlist_default:3] Loading playlist...
2019/07/21 14:29:07 [playlist_default:3] No mime type specified, trying autodetection.
2019/07/21 14:29:07 [playlist_default:3] Playlist treated as format application/x-mpegURL
2019/07/21 14:29:07 [playlist_default:3] Successfully loaded a playlist of 2 tracks.
2019/07/21 14:29:07 [error_jingle:3] "/var/azuracast/www/resources/error.mp3" is static, resolving once for all...
2019/07/21 14:29:07 [error_jingle:3] Prepared "/var/azuracast/www/resources/error.mp3" (RID 0).
2019/07/21 14:29:07 [a4m_local_1:3] Connecting mount sid#1 for @127.0.0.1...
2019/07/21 14:29:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/a4m/media/-5Bsongspk.info-5D_murder_2_-_01_-_hale_dil.mp3".
2019/07/21 14:29:07 [a4m_local_1:3] Connection setup was successful.
2019/07/21 14:29:07 [threads:3] Created thread "wallclock_main" (1 total).
2019/07/21 14:29:07 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2019/07/21 14:29:07 [a4m_live_switch:3] Switch to a4m_safe_fallback.
2019/07/21 14:29:07 [a4m_safe_fallback:3] Switch to error_jingle.
2019/07/21 14:29:07 [playlist_default:3] Prepared "/var/azuracast/stations/a4m/media/-5Bsongspk.info-5D_murder_2_-_01_-_hale_dil.mp3" (RID 2).
2019/07/21 14:29:07 [a4m_safe_fallback:3] Switch to a4m_radio_cue with transition.
2019/07/21 14:29:07 [dummy:3] Source failed (no more tracks) stopping output...
2019/07/21 14:29:07 [a4m_requests_fallback:3] Switch to a4m_autodj_fallback.
2019/07/21 14:29:07 [a4m_autodj_fallback:3] Switch to a4m_standard_playlists.
2019/07/21 14:29:07 [a4m_standard_playlists:3] Switch to stereo_playlist_default.
2019/07/21 14:29:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/a4m/media/akcent-dilemma-feat.-meriem.mp3".
2019/07/21 14:29:07 [lang:3] AzuraCast Raw Response: annotate:title="Hale Dil - www.SongsPK.info",artist="Harshit Saxena",duration="349.",song_id="9287a25547567ed08e8cb34657da7671",media_id="2",genre="2",playlist_id="1":/var/azuracast/stations/a4m/media/-5Bsongspk.info-5D_murder_2_-_01_-_hale_dil.mp3
2019/07/21 14:29:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/a4m/media/-5Bsongspk.info-5D_murder_2_-_01_-_hale_dil.mp3".
2019/07/21 14:29:07 [lang:3] AzuraCast Feedback Response: OK
2019/07/21 14:32:17 [lang:3] Authenticating DJ: RJ
2019/07/21 14:32:17 [lang:3] AzuraCast DJ Auth Response: true
2019/07/21 14:32:17 [decoder:3] Method "MAD" accepted "audio/mpeg".
2019/07/21 14:32:17 [lang:3] DJ Source connected! [("icy-name","My Station name"), ("icy-genre","Various"), ("icy-url","http://www.audiorealm.com"), ("icy-irc","#audiorealm"), ("icy-icq","NA"), ("icy-aim","NA"), ("icy-pub","1"), ("icy-br","64"), ("content-type","audio/mpeg")]
2019/07/21 14:32:17 [a4m_live_switch:3] Switch to a4m_live_fallback with transition.
2019/07/21 14:32:17 [a4m_live_fallback:3] Switch to blank_6460.
2019/07/21 14:32:17 [lang:3] AzuraCast Live Connected Response: received
2019/07/21 14:32:17 [threads:3] Created thread "harbor source feeding" (2 total).
2019/07/21 14:32:17 [a4m_input_streamer:3] Decoding...
2019/07/21 14:32:31 [lang:3] Authenticating DJ: shoutcast
2019/07/21 14:32:31 [lang:3] AzuraCast DJ Auth Response: true
2019/07/21 14:32:31 [a4m_input_streamer:3] New metadata chunk ? -- Litewolf - In The News Today.
2019/07/21 14:32:45 [lang:3] Authenticating DJ: shoutcast
2019/07/21 14:32:46 [lang:3] AzuraCast DJ Auth Response: true
2019/07/21 14:32:46 [a4m_input_streamer:3] New metadata chunk ? -- Litewolf - SAM Can!.
2019/07/21 14:32:47 [a4m_input_streamer:3] Timeout reached!
2019/07/21 14:32:47 [a4m_input_streamer:2] Error while reading from client: Timed out after waiting for 30.00 sec.
2019/07/21 14:32:47 [lang:3] DJ Source disconnected!
2019/07/21 14:32:47 [a4m_live_switch:3] Switch to a4m_safe_fallback with transition.

**Comment by danyalsaleemqureshi** [comment]
![Capture](https://user-images.githubusercontent.com/49310539/61593452-1b048c00-abf9-11e9-8ff5-218094cf7c7f.PNG)
See the both 2 ports are same, they should be different, on old panels its working fine on this new update facing this error

**Comment by ErnestPH** [comment]
@SlvrEagle23 if the new updates affects this one… then I should add back the port. Please let us know. thanks!

**Comment by SlvrEagle23** [comment]
@ErnestPH The reason I originally listed port+1 is because some clients _do_ manually require entering that port, while some detect that you've input the base port and automatically connect to the correct one under the hood.

The ideal solution here might be to just say "port: 8000 (8001 for some clients)".

**Comment by ErnestPH** [comment]
Thanks for the info! I guess I should add that info

**Comment by danyalsaleemqureshi** [comment]
@slvrEagle23 the Reason I created thread was my own mistake its solved let me clearify, when We add port 8000 for dj it assign 8005 which working on Sam Broadcaster, The issue I was facing for Android Broadcasting app, I still did not get it on android broadcasting app 8006 port is working I am very surprised there was no port in config but its working on 8006.

**Comment by ErnestPH** [comment]
@danyalsaleemqureshi I created a pull request to avoid confusion such as this in the future… https://github.com/AzuraCast/AzuraCast/pull/1773

**Comment by danyalsaleemqureshi** [comment]
Great Thanks (Y)

**Comment by ErnestPH** [comment]
@danyalsaleemqureshi Instructions are added already. Please update your Azuracast to see the changes. You can also close this one now. thanks!
