### ISSUE TITLE
Sheduled Playlist isn`t working after Update

### ISSUE THREAD

**Issue by Skyradio** [AzuraCast/AzuraCast#1771]
Hi
After the last Update, my sheduled Playlist isn`t working correctly. I stream to laut.fm, so i have to put a Advertise trigger every 30 minutes. This is now working again after the last Update, but if a Show is planned with 3 Parts , only the first Part will be played now. And i`m playing only one Playlist. The wight won`t be accepte by azuracast. I put the wight to level one and always this Playlist is running.I know you do a great job but something happened since yesterday..

Mike

**Comment by SlvrEagle23** [comment]
@Skyradio When you say you have a show planned with 3 parts, what do you mean? How are those structured? Is it a sequential playlist or a shuffled one?

I would need more information on the type of playlist you're using and what its settings are (a screenshot of the "Scheduling" tab would be helpful).

**Comment by Skyradio** [comment]
@SlvrEagle23 
![2](https://user-images.githubusercontent.com/53145222/61593633-69f2f700-abe2-11e9-964b-51c4c17217da.PNG)
![1](https://user-images.githubusercontent.com/53145222/61593636-711a0500-abe2-11e9-9e37-ed039237ac52.PNG)
These is my setup. I have several Playlist with one, two or more Tracks in it. Acrtually, azuracast overrides them and just plays the "normal" stream, wich is not planned on fixed times

**Comment by Skyradio** [comment]
@SlvrEagle23 I`ve found something, too: I`ve rescanned my Media via CLI and this Error ocures:  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

**Comment by SlvrEagle23** [comment]
@Skyradio It looks like your playlist is using one of the Liquidsoap-specific configuration options. You can take full advantage of those options by enabling "Manual AutoDJ" on your station's profile (under the AutoDJ tab) and restarting the station.

**Comment by Skyradio** [comment]
@SlvrEagle23
I user Azuracast a very long time and use this setup from the beginning without any problems. The issue came up with the last Update

**Comment by SlvrEagle23** [comment]
@Skyradio Our most recent updates added the AzuraCast AutoDJ back in, as a number of users had requested the return of the "Playing Next" song and better duplicate prevention, both of which our AutoDJ offers.

Please let me know if following my instructions in the previous post (turning on "Manual AutoDJ" and restarting your station) fixes the issue.

**Comment by Skyradio** [comment]
@SlvrEagle23
Its working again. Thank you very much
