### ISSUE TITLE
Embed code and Public page playback not working after switching to SSL

### ISSUE THREAD

**Issue by djariss** [AzuraCast/AzuraCast#1775]
Azuracast is installed on a VPS running minimal Centos7, installed using official guide and Docker.

After trying to play the music on radio station public page using no SSL, just plain HTTP access, the playback works just fine.

I have installed the Let's encrypt following the official install instruction and the SSL is working just fine. But when the radio station public page is accessed in the browser over HTTPS, the playback is not working and there is no sound. The browser reports this JS error in console:

**NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable.
Invalid URI. Load of media resource  failed.**

So, this also affects the player embed code. If you use the embed code on SSL pages, the radio will not work and it will report the same error again.

I'm using the latest Azuracast version updated could of hours ago.

Here is an example URL https://as1.prvihosting.com/public/radio_osmica

If you try to play the radio using HTTP, it will work. **The weird thing is that the radio station plays behind the SSL in the admin area of Azuracast but not on Public page and embed code.**

Anyway, I love Azuracast, so far I haven't seen such a good radio streaming platform especially the Open Source one. Keep up the good work guys ;)

**Comment by pwrj** [comment]
I know this is old, was there ever a solution to this? I'm experiencing the same and I noticed that it happens without shoutcast installation, not on icecast.

**Comment by SlvrEagle23** [comment]
@djariss @pwrj In a majority of cases where you're serving your main site over SSL, you'll want to enable the Radio Web Proxy (in the system-wide settings panel). This will ensure that your radio signal travels over the same secure connection that the web site itself travels over.

Icecast can fortunately be configured to serve the same SSL certificate directly through its connection that is used by nginx, but SHOUTcast cannot do this, and thus the proxy is almost always required.

**Comment by pwrj** [comment]
@SlvrEagle23 That did it! Thank you!!

**Comment by djariss** [comment]
@SlvrEagle23 Thank you! It's working just fine now. I really didn't notice that option, anyway, thanks a bunch. :)

**Comment by djariss** [comment]
@
