### ISSUE TITLE
updating the azura cast error

### ISSUE THREAD

**Issue by djsammy629** [AzuraCast/AzuraCast#1776]
i get this error when updating the azura cast  curl: 
(23) Failed writing body (2192 != 2759)

can u help please im just about to become a reseller partner

**Comment by djsammy629** [comment]
The docker-compose.yml file has changed since your version. Overwrite? This will overwrite any customizations you made to this file? [Y/n] y
[2228] INTERNAL ERROR: cannot create temporary directory!
[2229] INTERNAL ERROR: cannot create temporary directory!
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Failed to write all bytes for _bisect.so
fwrite: No space left on device
[2260] INTERNAL ERROR: cannot create temporary directory!
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Update complete!

**Comment by SlvrEagle23** [comment]
@djsammy629 You must've been cutting it fairly close on disk space usage, as it appears Docker pulling updated images (which uses, at most, an extra 1GB or so briefly, but is usually far less than that) caused you to run out of space. You should free up space on your server and attempt the update again.

**Comment by djsammy629** [comment]
Hello I don’t see how I ran out of storage I have 6tb on that server so it’s not right plus I only have about 16gb of songs?

**Comment by SlvrEagle23** [comment]
@djsammy629 It likely has to do with the way your partitions are arranged, then. Make sure you actually have space in the root directory, not just the `/home` partition (if there is one).

**Comment by djsammy629** [comment]
Should of tho I had 6tb I had to reinstall it I tried to update it and when I put update line it web browser wouldn’t load up at all I’ve had that a cupple of times

**Comment by SlvrEagle23** [comment]
@djsammy629 This issue is clearly more of a Linux system administration issue than an AzuraCast one, as it very likely isn't AzuraCast that has anything to do with your hard drive filling to 6TB capacity. You should check your partitions and make any necessary changes to ensure that the temp directory has the available space.
