### ISSUE TITLE
Bug when changing name of station

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#1778]
**Using Docker installation method**
Docker uBuntu 18  v0.9.5.1, #5d26137

**Describe the bug**
When changing name of station… the public page is not visible in the tab anymore… furthermore, the public url says 500 station not found (since the url is not updated to the new radio name...

**Expected behavior**
When changing station name, it should update the public page url

**Relevant Logs**

**Screenshots**
[screenshot](https://prnt.sc/ojj509)

**Device(s):**
 MacOS

**Comment by SlvrEagle23** [comment]
@ErnestPH Renaming a station shouldn't turn on the "hide from public pages" setting. That's a separate setting on the station's profile, and that's what determines whether the "public" page is shown on the sidebar (and whether it is visible to users).

**Comment by ErnestPH** [comment]
@SlvrEagle23 I just noticed, I didn't tick the enable public page. whew! haha Thanks!
