### ISSUE TITLE
Question: when creating or editing playlist - Will the current song restarts?

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#1779]
Hi guys, just to verify on your end…

Will the song restarts every time we add a new playlist or edit playlists?

I know it will restart during updates and server restarts… but not sure about the editing and creating playlist… Thanks!

**Comment by SlvrEagle23** [comment]
@ErnestPH It should not, no. When you modify a playlist's contents, Liquidsoap is told to "reload" the playlist in memory, but that doesn't actually skip the currently playing song; if you're using the AzuraCast AutoDJ, it always uses the latest version of the playlist anyway so even that "reload" step doesn't happen.
