### ISSUE TITLE
mounted storage error

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#178]
Hello,

 I have mounted and external cloud storage to my vps with my music files.
But on azuracast when accessing /media/music files i get this error : 
{"error":{"code":403,"msg":"Forbidden"}}

This is what i have put in te media directory of the station:	/mnt/mycloudstorage/Music/

**Comment by andbou** [comment]
The user azuracast group www-data must have autorisation to your mount point

**Comment by surihost** [comment]
I also tried that, still not.

**Comment by SlvrEagle23** [comment]
@surihost This has been a known issue for quite a while, any external mounted filesystem (especially with SSHFS or derivative) seems to not work at all with AzuraCast's media management.

Honestly, short of updating the permissions I'm not sure what the issue could be. Barring some external insight on this issue, I would unfortunately have to say that AzuraCast doesn't currently support media directories mounted as external drives or via SSHFS.

**Comment by surihost** [comment]
Hello,

If you get time please try if azuracast can use mounted storage to acces the media library.
i also use via davfs2

**Comment by susl16c** [comment]
help how to specify a storage location by default, only this way works /var/azuracast/stations/. how to specify the path outside the docker?

**Comment by SlvrEagle23** [comment]
@susl16c It looks like you've already created another Github issue with this question, so I will discuss the answer there.
