### ISSUE TITLE
auto dj keep cuttimg off when Publish to "Yellow Pages" Directories ticked 

### ISSUE THREAD

**Issue by djsammy629** [AzuraCast/AzuraCast#1780]
Log: 
019/07/25 09:58:34 [poweradiofm_local_1:2] Error while sending data: could not write data to host: Broken pipe in write()!
2019/07/25 09:58:34 [poweradiofm_local_1:3] Closing connection...
2019/07/25 09:58:34 [poweradiofm_local_1:3] Will try to reconnect in 3.00 seconds.

i have just reinstalled it yesterday and when ever i made this public it starts and plays then stop and when u refresh it come up like this below 
https://djsammy.co.uk/azuracast/shoutcast.PNG

now when i un tick the "Publish to "Yellow Pages" Directories" it works fine but when i tick it again it does it again i also tried to do a relay make main one not public and replay public and still does it on relay now i have this version of shoutcast https://djsammy.co.uk/azuracast/shoutcast%202.PNG

could u help or any one help please

**Comment by SlvrEagle23** [comment]
@djsammy629 We don't officially support the latest version of SHOUTcast (2.6 or higher) because they've introduced some "freemium" changes that make it both incompatible with open-source software like ours and impossible for us to test the full feature set without buying into Radionomy's proprietary system.

**Comment by djsammy629** [comment]
but what ive noticed its the auto dj leaving not the stream the stream is fine it just says no connections

**Comment by afonsosantos** [comment]
@djsammy629 Hi!

Is this issue still valid? There have been some updates related to AutoDJ, that could've help with that specific issue.

**Comment by djsammy629** [comment]
hi i stoped using azuracast due to it not working all the time and moved
back over to centova

**Comment by SlvrEagle23** [comment]
@djsammy629 Sorry to hear that. Best of luck with your station.
