### ISSUE TITLE
Creating azuracast_web_1 ... error

### ISSUE THREAD

**Issue by djsammy629** [AzuraCast/AzuraCast#1781]
i have no logs for this sorry 

i went to update the server and i get this error and now i cant acess azuracast at all 

https://djsammy.co.uk/azuracast/shoutcast%203.PNG

help anyone asap

**Comment by ErnestPH** [comment]
Just run the update again… if it won't help… increase RAM using swap memory

**Comment by djsammy629** [comment]
i have 32 gb of ram on that server is a dedicated server and done that and same issu e

**Comment by Vaalyn** [comment]
It seems like there is something else running on your server that is already using port 80. Please check if you have something like apache2 / httpd / nginx / etc. running on the host machine.

**Comment by djsammy629** [comment]
I would like to say I figured that out like half an hour ago just seen u replayed in my email thanks for help everyone it’s a Apache 2 and nginx
