### ISSUE TITLE
Set Docker port range to 10000-11000 instead of 8000-8500

### ISSUE THREAD

**Issue by NadjaNeville** [AzuraCast/AzuraCast#1784]
Hello, as the other installation method isn't supported any more I changed to the docker installation and hit an issue that I can't change the default port mapping of 8000-8500 by any means. I have followed the "expand port range" and it didn't work, I have changed the docker-compose.yml to reflect my available port range but it still sticks to 8000-8500 no matter what I put into it. I have changed azuracast.env too reflecting the new port range, the system just doesn't care what I do. Also, if I change the station ports manually, the station says it's running but no sound and no access to the shoutcast admin page (404 not found)

Azuracast.env

```
#
# AzuraCast Customization
#

# The application environment.
# Valid options: production, development, testing
APPLICATION_ENV=production

# Prefer release versions over always-updating "rolling" releases.
# Valid options: true, false
PREFER_RELEASE_BUILDS=false

# Enable the composer "merge" functionality to combine the main application's
# composer.json file with any plugins' composer files.
# This can have performance implications, so you should only use it if
# you use one or more plugins with their own Composer dependencies.
# Valid options: true, false
COMPOSER_PLUGIN_MODE=false

# The minimum port number to use when automatically assigning ports to a station.
# By default, this matches the first forwarded port on the "stations" container.
# You can modify this variable if your station port range is different.
# Be sure to also forward the necessary ports via `docker-compose.yml`
# (and nginx, if you want to use the built-in port-80/443 proxy)!
AUTO_ASSIGN_PORT_MIN=10000

# The maximum port number to use when automatically assigning ports to a station.
# See AUTO_ASSIGN_PORT_MIN.
AUTO_ASSIGN_PORT_MAX=10999

#
# Database Configuration
# --
# Once the database has been installed, DO NOT CHANGE these values!
#

# The host to connect to. Leave this as the default value unless you're connecting
#   to an external database server.
# Default: mariadb
MYSQL_HOST=mariadb

# The port to connect to. Leave this as the default value unless you're connecting
#   to an external database server.
# Default: 3306
MYSQL_PORT=3306

# The username AzuraCast will use to connect to the database.
# Default: azuracast
MYSQL_USER=azuracast

# The password AzuraCast will use to connect to the database.
# By default, the database is not exposed to the Internet at all and this is only
#   an internal password used by the service itself.
# Default: azur4c457
MYSQL_PASSWORD=azur4c457

# The name of the AzuraCast database.
# Default: azuracast
MYSQL_DATABASE=azuracast

# Automatically generate a random root password upon the first database spin-up.
#   This password will be visible in the mariadb container's logs.
# Default: yes
MYSQL_RANDOM_ROOT_PASSWORD=yes

#
# Advanced Configuration
#

# PHP's maximum POST body size and max upload filesize.
# PHP_MAX_FILE_SIZE=25M

# PHP's maximum memory limit.
# PHP_MEMORY_LIMIT=128M

# Create additional media sync worker processes.
#   This setting can be used to increase the performance of the media sync process
#   by creating additional worker processes to consume messages
# Default: 0
# ADDITIONAL_MEDIA_SYNC_WORKER_COUNT=0

docker-compose.yml

#
# AzuraCast Docker Compose Configuration File
#
# When updating, you will be prompted to replace this file with a new
# version; you should do this whenever possible to take advantage of
# new updates.
#
# If you need to customize this file, you can create a new file named:
#   docker-compose.override.yml
# with any changes you need to make.
#
version: '2.2'

services:
  web:
    image: azuracast/azuracast_web_v2:latest
    # Want to customize the HTTP/S ports? Follow the instructions here:
    # https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#use-non-standard-ports
    ports:
      - '${AZURACAST_HTTP_PORT:-80}:80'
      - '${AZURACAST_HTTPS_PORT:-443}:443'
    depends_on:
      - mariadb
      - influxdb
      - stations
      - redis
    env_file: azuracast.env
    environment: &default-environment
      AZURACAST_DC_REVISION: 5
    volumes:
      - letsencrypt:/etc/letsencrypt
      - www_data:/var/azuracast/www
      - tmp_data:/var/azuracast/www_tmp
      - station_data:/var/azuracast/stations
      - shoutcast2_install:/var/azuracast/servers/shoutcast2
      - backups:/var/azuracast/backups
    restart: always
    logging: &default-logging
      options:
        max-size: "1m"
        max-file: "5"

  mariadb:
    image: azuracast/azuracast_db:latest
    volumes:
      - db_data:/var/lib/mysql
    env_file: azuracast.env
    environment:
      <<: *default-environment
    restart: always
    logging: *default-logging

  influxdb:
    image: azuracast/azuracast_influxdb:latest
    volumes:
      - influx_data:/var/lib/influxdb
    restart: always
    logging: *default-logging

  redis:
    image: azuracast/azuracast_redis:latest
    restart: always
    logging: *default-logging

  stations:
    container_name: azuracast_stations
    image: azuracast/azuracast_radio:latest
    ports:
    # This default mapping is the outgoing and incoming ports for the first 50 stations.
    # You can override this port mapping in your own docker-compose.override.yml file.
    # For instructions, see:
    # https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#expand-the-docker-radio-station-port-range
     - '10000:10000'
     - '10005:10005'
     - '10006:10006'
     - '10010:10010'
     - '10015:10015'
     - '10016:10016'
     - '10020:10020'
     - '10025:10025'
     - '10026:10026'
     - '10030:10030'
     - '10035:10035'
     - '10036:10036'
     - '10040:10040'
     - '10045:10045'
     - '10046:10046'
     - '10050:10050'
     - '10055:10055'
     
    volumes:
     - station_data:/var/azuracast/stations
     - shoutcast2_install:/var/azuracast/servers/shoutcast2
     - letsencrypt:/etc/nginx/ssl:ro
     - tmp_data:/var/azuracast/www_tmp
    init: true
    restart: always
    logging: *default-logging

volumes:
  db_data: {}
  influx_data: {}
  letsencrypt: {}
  shoutcast2_install: {}
  station_data: {}
  tmp_data: {}
  www_data: {}
  backups: {}

```

**Comment by xewl** [comment]
It's better to use a `docker-compose.override.yml` file to override the ports.
"You can override this port mapping in your own docker-compose.override.yml file."

More documentation regarding this: [Share Compose configurations between files and projects](https://docs.docker.com/compose/extends/)

**Comment by NadjaNeville** [comment]
Well, thank you for the answer but tried that, been there, didn't work. Setting the ports there didn't change anything in the behavior of the system. Also, what is the format of this "override" what means port xxx before the ":" and what the other after? Also the override would only open additional ports, I want to transfer the port base to another range fully. There are other services running at 8000-9000 and azuracast having a hardcoded range always in this range would mess it up.

**Comment by SlvrEagle23** [comment]
@NadjaNeville So you're saying even though you've set those values in `azuracast.env`, when you create a new station, it's still trying to assign it to port 80xx instead?

That could be a bug on our end.

**Comment by NadjaNeville** [comment]
@SlvrEagle23 The port range changed after a database wipe and rebuild. It auto assigned a different port. The system says it's running and there are no log entries, but clicking on the stream admin link and the stream page link returns (not found 404). The ufw is disabled to avoid problems at this end.

**Comment by SlvrEagle23** [comment]
@NadjaNeville I pushed up an update last night that may help with the problem by changing how we check for that min/max port environment variable. Let me know if that helps at all by updating to the latest version and then creating a new station.

**Comment by fast97** [comment]
Hello what is the solution to this problem because I have the same problem. Thank you

**Comment by tanotar** [comment]
I leave you a machete as a gift. I always had that problem for not using the default ports that come in AZURACAST

Everything is a problem with the HTTPS player, in HTTP no problem occurs. For HTTP you only edit the file "docker-compose.yml" the ports and the beginning and end of ports in the file "azuracast.env" found in the path "/ var / azuracast"
For HTTPS you have to do the same process as HTTPS and then you have to search for all the files called "azuracast.conf" executing "find / -name" azuracast.conf "
Once you have found all the files, go one by one and replace
"8 [0-9] [0-9] 0" by "[0-9] [0-9] [0-9] [0-9]" and also "8 [0-9] [0-9 ] 5 "by" [0-9] [0-9] [0-9] [0-9] ". A see finished that Execute the following command "docker-compose down" and "docker-compose up -d".
Ready. In this way, all the ports on the server will work as HTTPS without problems. It is a very good solution
Keep in mind that each update you make in the panel you will have to repeat the process, otherwise you will have the same problem again.
It took me time to fix it in my case but it's perfect!

**Comment by AleeRobles** [comment]
> I leave you a machete as a gift. I always had that problem for not using the default ports that come in AZURACAST
> 
> Everything is a problem with the HTTPS player, in HTTP no problem occurs. For HTTP you only edit the file "docker-compose.yml" the ports and the beginning and end of ports in the file "azuracast.env" found in the path "/ var / azuracast"
> For HTTPS you have to do the same process as HTTPS and then you have to search for all the files called "azuracast.conf" executing "find / -name" azuracast.conf "
> Once you have found all the files, go one by one and replace
> "8 [0-9] [0-9] 0" by "[0-9] [0-9] [0-9] [0-9]" and also "8 [0-9] [0-9 ] 5 "by" [0-9] [0-9] [0-9] [0-9] ". A see finished that Execute the following command "docker-compose down" and "docker-compose up -d".
> Ready. In this way, all the ports on the server will work as HTTPS without problems. It is a very good solution
> Keep in mind that each update you make in the panel you will have to repeat the process, otherwise you will have the same problem again.
> It took me time to fix it in my case but it's perfect!

**Genius! teacher! You saved us, you came at the right time tonight I love you.**

**Comment by aleriera** [comment]
> I leave you a machete as a gift. I always had that problem for not using the default ports that come in AZURACAST
> 
> Everything is a problem with the HTTPS player, in HTTP no problem occurs. For HTTP you only edit the file "docker-compose.yml" the ports and the beginning and end of ports in the file "azuracast.env" found in the path "/ var / azuracast"
> For HTTPS you have to do the same process as HTTPS and then you have to search for all the files called "azuracast.conf" executing "find / -name" azuracast.conf "
> Once you have found all the files, go one by one and replace
> "8 [0-9] [0-9] 0" by "[0-9] [0-9] [0-9] [0-9]" and also "8 [0-9] [0-9 ] 5 "by" [0-9] [0-9] [0-9] [0-9] ". A see finished that Execute the following command "docker-compose down" and "docker-compose up -d".
> Ready. In this way, all the ports on the server will work as HTTPS without problems. It is a very good solution
> Keep in mind that each update you make in the panel you will have to repeat the process, otherwise you will have the same problem again.
> It took me time to fix it in my case but it's perfect!

Thank you very much! You saved my life, everything is working now!
