### ISSUE TITLE
AzuraRelay nodes are counted as listeners in AzuraCast stats.

### ISSUE THREAD

**Issue by kevev** [AzuraCast/AzuraCast#1785]
I think it would be better to exclude the AzuraRelay nodes as listeners in the total listener stats, and on the main AC screen in the Listeners column. Also, maybe a Relay column would be a good idea. This could show how many relays are connected.

**Comment by SlvrEagle23** [comment]
@kevev Relays with user-agents that contain the "Icecast" string will no longer be shown in listener reports or aggregated into listener counts.

**Comment by kevev** [comment]
Thanks! It works! Can we also have the main page updated to not show the relays in the current listeners column?

**Comment by kevev** [comment]
Thanks!
