### ISSUE TITLE
Issue running Skip from outside panel

### ISSUE THREAD

**Issue by Kerneltroll** [AzuraCast/AzuraCast#1787]
I have the latest version of Azura.

This will hopefully be a quick one, after checking the API document i run:
/api/station/1/backend/skip

(Note: this works fine via the Admin panels skip song, however, im building this into a discord bot so i can't do it via the admin). 

However, i get the following: 
Method not allowed
Method not allowed. Must be one of: POST, OPTIONS

I loaded postman and sent it as POST, however i get permission denied:
{
    "code": 403,
    "message": "Permission Denied",
    "formatted_message": "Permission Denied",
    "extra_data": [],
    "success": false
}

Any quick advice on what im missing here?

**Comment by afonsosantos** [comment]
You may need to authenticate using a API key in order to use that endpoint.

**Comment by Kerneltroll** [comment]
That makes sense, however the document doesn't express this, unless I'm too tired! lol

So in postman, i added params api_key=*KEYHERE* but i still get permission denied?

**Comment by Kerneltroll** [comment]
Nevermind:

If anyone else faces this: Header key = X-API-Key and value is your api key

**Comment by afonsosantos** [comment]
Nice that you figured it out!
