### ISSUE TITLE
Problems with Profile On the Air

### ISSUE THREAD

**Issue by Project-Radio** [AzuraCast/AzuraCast#1788]
## Problems with Profile On the Air

Hello i have a problem.

The Module in the Profile "On the Air" is freezed. The same track is display. This is not good for the Nowplaying.

![IMG_20190727_192510](https://user-images.githubusercontent.com/53378277/61997652-da978900-b0a4-11e9-9a73-49c4c2ff8d22.jpg)

**Comment by afonsosantos** [comment]
Hi,

Have you tried restarting the station? (in the side menu, under Utilities)

**Comment by Project-Radio** [comment]
Yes and I reboot the server. The same problem.

**Comment by afonsosantos** [comment]
Anything in the logs?

**Comment by Project-Radio** [comment]
No error in the logs.

**Comment by afonsosantos** [comment]
Sorry but I can't help you with that issue. You may need to wait until a staff member picks this issue.

**Comment by Project-Radio** [comment]
> Sorry but I can't help you with that issue. You may need to wait until a staff member picks this issue.

No problem.

**Comment by SC2Mitch** [comment]
Are you fully updated?

**Comment by Kerneltroll** [comment]
Out of interest, are different songs playing? just the now playing is showing 1 song?

Or is the radio not playing any songs now?

**Comment by SlvrEagle23** [comment]
@Project-Radio What installation method are you using?

If you're using the Ansible ("Traditional") installation method, please update your installation to the latest version released earlier this afternoon. I fixed a few bugs relating to Now Playing data on Ansible installations.
