### ISSUE TITLE
Liquidsoap configuration: custom live source switching

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1789]
It's about following line in the Liquidsoap config. The line is generated by Azuracast if the live DJ source is enabled. 

`radio = switch(id="yourstationname_live_switch", track_sensitive=false, [({!live_enabled}, live), ({true}, radio)])`

Thanks to https://github.com/AzuraCast/AzuraCast/issues/1751 I could experiment with the configuration and it turns out that the line is a problem in case of certain custom Liquidsoap configurations. 

In our case, we would like have: 
- Radio source faded out and in before and after a live DJ connects (see also https://github.com/AzuraCast/AzuraCast/issues/1254). 
- A specific jingle playlist is played before a live DJ connects. 
- A specific jingle playlist is played after  a live DJ disconnects. 

This all can be done easily as a custom Liquidsoap configuration but only if Azuracast does not generate the line above. Basically, the user would have his or her own switch declaration with the specific transitions (for fading and jingles). 

Can I somehow tell Azuracast not to generate that specific line? If not, do you think it's a feature you would consider adding (should I add it at Feature Upvote)? Similar to custom playlists one could define a custom live source where Azuracast sets up the source (called `live` just like now) but it doesn't switch it into the the `radio` source, it lets the user do it.

As a workaround I can mount my own Liquidsoap configuration but it's not something we'd like to do as it can easily cause inconsistencies across Azuracast and the custom configuration file (e.g., in case of new playlists etc.).

**Comment by SlvrEagle23** [comment]
@gammaw Not currently, and honestly that's kind of a really specific advanced configuration. It seems like your current option (of just hard-overwriting the entire Liquidsoap configuration file) is the best bet for now.

**Comment by gammaw** [comment]
@SlvrEagle23 I see. We'll do that I guess. My only concern is, having a custom LS config in use, that we can go out of synch with Azura's generated LS config as Azura develops it further. What do you think is the best way to track if you guys do changes there? Can you point me to the generator code? My strategy would be to check from time to time if you touched the generator and, if yes, we would also make the necessary updates in our custom LS config file.

**Comment by SlvrEagle23** [comment]
@gammaw Here's the [relevant section of our Liquidsoap code](https://github.com/AzuraCast/AzuraCast/blob/master/src/Radio/Backend/Liquidsoap.php#L51-L713) for configuration writing.

**Comment by gammaw** [comment]
Thanks, it's very helpful!
