### ISSUE TITLE
Evaluate building Snap app package

### ISSUE THREAD

**Issue by darkjedeye** [AzuraCast/AzuraCast#179]
Hey man, was just wondering if there will be a snap version of this in the future? As that seems to be foolproof for noobs like me?

**Comment by SlvrEagle23** [comment]
Snap looks pretty neat, seems that it's a way of packaging Docker-like containers for easy cross-platform installation, but it has heavier emphasis on Ubuntu.

Provided it integrates easily enough into our existing build process, it's certainly something worth looking into. I'll flag this as an enhancement and look into it when I have the time available.

**Comment by darkjedeye** [comment]
cool... glad i could make a worthwhile suggestion

**Comment by SlvrEagle23** [comment]
Closing this issue for now. I've been keeping a close eye on the Snap app packaging system and snapd, and it seems that it has extremely close parallels to Docker but with its own proprietary package configuration format, and requires its own special build process that exists separate from the Docker image builds.

For a project of this scale (and especially a solo-developer one like this) it's very difficult to bring on board a new method of deploying the software. Not only does this mean new setup and CI tasks, but it introduces a whole new class of potential bugs or issues that only appear in that format. Emphasizing Docker was specifically meant to _reduce_ the surface area of potential bugs that are unique to a single server or environment (and it has been successful at this), and this might be a step in the opposite direction.

If there's enough desire to see this program packaged as an AppImage or Snap package or deb file or other single-file installer, I would always welcome pull requests to help accomplish those goals.
