### ISSUE TITLE
Radio public page does not work.

### ISSUE THREAD

**Issue by djmuratb** [AzuraCast/AzuraCast#1790]
Ubuntu 18
AzuraCast • v0.9.6, #56d6326 (2019-07-28 3:07) • Ansible • PHP 7.2

Radio public page does not work. I tried every format, but the music won't play. 
http://azuracast.4747.pw/public/test_station_01

Music is playing on the profile page.
http://azuracast.4747.pw:8000

Windows 10
Chrome / Firefox / Opera

**Comment by Kerneltroll** [comment]
So music plays with the pls file. Any errors in the log?

**Comment by SlvrEagle23** [comment]
@djmuratb Figured out the problem. If you're on Ubuntu 18.04, though, it should be enabling the nchan websocket/eventsource broadcaster instead of the standard API endpoint. It should only be disabled if you're on Ubuntu 16.04...

**Comment by SlvrEagle23** [comment]
@djmuratb On your server, if you type `cat /etc/lsb-release` what is shown? Just curious.

**Comment by djmuratb** [comment]
@SlvrEagle23 Thank yo so much!

Ubuntu 
18.04 
bionic 
"Ubuntu 18 .04.2 LTS"

**Comment by SlvrEagle23** [comment]
@djmuratb Figured out the problem: a little trailing whitespace behind the distribution codename in our "should nchan be enabled" check. If you're on 18.04 and update to the newest version, you should now be using the live Websocket/EventSource method of retrieving Now Playing data, which is the fastest and most scalable option.

**Comment by djmuratb** [comment]
@SlvrEagle23 Problem solved, thank you.

Updated.. / AzuraCast • v0.9.6, #8bf6261 (2019-07-28 22:34) • Ansible • PHP 7.2
