### ISSUE TITLE
Language Settings and Turkish Translation

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#1791]
Hi Bro. I think I translate AzuraCast for Turkish language. Please can you add Turkish language repo? I will translate to it at now. Lets Go :) Thanks ;)

I have sent you a private message via Crowdin.

**Comment by ogrenci01** [comment]
@SlvrEagle23 please add repo for Turkish lang. I will translate it. Help me ;)

**Comment by ogrenci01** [comment]
@ SlvrEagle23 I'm waiting for your answer to do the translation. Help me :)

**Comment by ogrenci01** [comment]
I am very sad. Because all my work has been canceled. I have been translating Turkish language into AzuraCast application for a week. The translation was almost over. After the update today, all my works were canceled. I need to recheck the entire translation. Please add the Turkish language to the repo. I share a part of the translation. :-(

`#: /var/azuracast/www/src/Acl.php:183
#: /var/azuracast/www/src/Acl.php:195
msgid "All Permissions"
msgstr "Tüm İzinler"

#: /var/azuracast/www/src/Acl.php:184
msgid "View Administration Page"
msgstr "Yönetici Panelini Görme"

#: /var/azuracast/www/src/Acl.php:185
msgid "View System Logs"
msgstr "Sistem Günlüklerini Görme"

#: /var/azuracast/www/src/Acl.php:186
#: /var/azuracast/www/templates/frontend/public/dj.js.phtml:11
msgid "Settings"
msgstr "Ayarlar"

#: /var/azuracast/www/src/Acl.php:186
#: /var/azuracast/www/src/Acl.php:187
#: /var/azuracast/www/src/Acl.php:188
#: /var/azuracast/www/src/Acl.php:189
#: /var/azuracast/www/src/Acl.php:190
#: /var/azuracast/www/src/Acl.php:191
#: /var/azuracast/www/src/Acl.php:192
msgid "Administer %s"
msgstr "%s Yönetimi"

#: /var/azuracast/www/src/Acl.php:187
#: /var/azuracast/www/config/menus/admin.php:27
#: /var/azuracast/www/templates/admin/api/index.phtml:1
#: /var/azuracast/www/templates/admin/api/index.phtml:5
msgid "API Keys"
msgstr "API Anahtarları"

#: /var/azuracast/www/src/Acl.php:188
#: /var/azuracast/www/config/menus/admin.php:44
msgid "Users"
msgstr "Kullanıcılar"

#: /var/azuracast/www/src/Acl.php:189
#: /var/azuracast/www/config/menus/admin.php:53
#: /var/azuracast/www/templates/admin/permissions/index.phtml:1
#: /var/azuracast/www/templates/admin/permissions/index.phtml:5
#: /var/azuracast/www/templates/admin/permissions/index.phtml:23
msgid "Permissions"
msgstr "İzinler"

#: /var/azuracast/www/src/Acl.php:190
#: /var/azuracast/www/config/menus/admin.php:60
#: /var/azuracast/www/config/menus/admin.php:64
#: /var/azuracast/www/templates/admin/stations/index.phtml:1
msgid "Stations"
msgstr "Radyolar"

#: /var/azuracast/www/src/Acl.php:191
#: /var/azuracast/www/config/forms/media.php:74
#: /var/azuracast/www/config/menus/admin.php:69
#: /var/azuracast/www/templates/admin/custom_fields/index.phtml:1
#: /var/azuracast/www/templates/admin/custom_fields/index.phtml:5
msgid "Custom Fields"
msgstr "Özelleştirme"

#: /var/azuracast/www/src/Acl.php:192
#: /var/azuracast/www/config/menus/admin.php:37
#: /var/azuracast/www/templates/admin/backups/index.phtml:8
#: /var/azuracast/www/templates/admin/backups/index.phtml:82
msgid "Backups"
msgstr "Yedekler"

#: /var/azuracast/www/src/Acl.php:196
msgid "View Station Page"
msgstr "Radyo Sayfasını Görme"

#: /var/azuracast/www/src/Acl.php:197
msgid "View Station Reports"
msgstr "Radyp Raporlarını Görme"

#: /var/azuracast/www/src/Acl.php:198
msgid "View Station Logs"
msgstr "Radyo Günlüklerini Görme"

#: /var/azuracast/www/src/Acl.php:199
#: /var/azuracast/www/config/menus/station.php:34
#: /var/azuracast/www/templates/stations/profile/index.phtml:8
msgid "Profile"
msgstr "Profil"

#: /var/azuracast/www/src/Acl.php:199
#: /var/azuracast/www/src/Acl.php:200
#: /var/azuracast/www/src/Acl.php:201
#: /var/azuracast/www/src/Acl.php:202
#: /var/azuracast/www/src/Acl.php:203
#: /var/azuracast/www/src/Acl.php:204
#: /var/azuracast/www/src/Acl.php:205
#: /var/azuracast/www/src/Acl.php:206
msgid "Manage Station %s"
msgstr "Radyo %s Yönetimi"`

**Comment by ogrenci01** [comment]
@SlvrEagle23 and @Vaalyn help me please.

**Comment by ogrenci01** [comment]
Hello My Friends @SlvrEagle23  and @Vaalyn ;

I have some good news for you. I finished the translation. AzuraCast is now in Turkish! I tested it. I want to share the default.pot file with you and use it for crowdin. Could you please tell me how to do this?

**Comment by ogrenci01** [comment]
**Hello My Friends @SlvrEagle23 and @Vaalyn ;**

I have some good news for you. I finished the translation. AzuraCast is now in Turkish! I tested it. There is not problem. I want to share the default.pot file with you and use it for crowdin. Could you please tell me how to do this?

**Some screenshot for check:**

https://prnt.sc/orlv55

https://prnt.sc/orlv8c

**Comment by ogrenci01** [comment]
@SlvrEagle23 help me?

**Comment by afonsosantos** [comment]
@ogrenci01 Hi!

If you translated using the Crowdin page, the translations should be implemented in AzuraCast.

**Comment by ogrenci01** [comment]
@afonsosantos Hi;

Thank you for your reply.

I didn't use Crowdin to translate. I prepared all the files manually. I expect the Turkish language to add to the repo. I want to translate and share. I'm waiting for a response from the AzuraCast team.

**Comment by afonsosantos** [comment]
Hi!

Can you provide the translation files? Maybe the format is compatible with Crowdin.

**Comment by afonsosantos** [comment]
You can also join our [Slack channel](https://azuracast.com/slack) and share the files there, the staff of AzuraCast could give you a quicker answer there.

**Comment by SlvrEagle23** [comment]
@ogrenci01 I have added the Turkish language support to Crowdin. Please import your translation there and I will get it approved and integrated into the software.
