### ISSUE TITLE
./docker.sh update error

### ISSUE THREAD

**Issue by alutus** [AzuraCast/AzuraCast#1792]
root@cz:~# ./docker.sh update
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.stations.ulimits.nofile.hard contains "65536", which is an invalid type, it should be an integer
services.web.ulimits.nofile.hard contains "65536", which is an invalid type, it should be an integer
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.stations.ulimits.nofile.hard contains "65536", which is an invalid type, it should be an integer
services.web.ulimits.nofile.hard contains "65536", which is an invalid type, it should be an integer
Error: No such volume: azuracast_www_data
Error: No such volume: azuracast_tmp_data
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.stations.ulimits.nofile.hard contains "65536", which is an invalid type, it should be an integer
services.web.ulimits.nofile.hard contains "65536", which is an invalid type, it should be an integer
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.stations.ulimits.nofile.hard contains "65536", which is an invalid type, it should be an integer
services.web.ulimits.nofile.hard contains "65536", which is an invalid type, it should be an integer
Update complete!

i need some help, my radio stations is down :(

**Comment by alutus** [comment]
i solved .

COMPOSE_VERSION=`git ls-remote https://github.com/docker/compose | grep refs/tags | grep -oP "[0-9]+\.[0-9][0-9]+\.[0-9]+$" | tail -n 1`
sudo sh -c "curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
sudo chmod +x /usr/local/bin/docker-compose
sudo sh -c "curl -L https://raw.githubusercontent.com/docker/compose/${COMPOSE_VERSION}/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose"

**Comment by SlvrEagle23** [comment]
@alutus This is actually a valid issue reported with our latest Docker Compose file; your solution of updating Docker Compose manually to a newer version works, but it shouldn't be necessary. I went ahead and pushed up an update that will resolve it without requiring that step.

**Comment by alutus** [comment]
thanks for your support sir.

**Comment by pwrj** [comment]
I'm getting this Azuracast ERROR with the latest install: 

The Compose file is invalid because: Service stations has neither an image nor a build context specified. At least one must be provided.
