### ISSUE TITLE
The playlist don't follow the M3U format from Sam Brodacasting list I have uplaod....

### ISSUE THREAD

**Issue by ApoTHEOSeSBallroom** [AzuraCast/AzuraCast#1794]
**Using Docker installation method**

**Host Operating System**
Windows 10

**Describe the bug**
Lot bugs: don't follow the M3U list version from Sam Broadcasting pro I have import one the Web DJ. When I try to move one song at one other order with the arrow it's move but no have place to save and it all return as before...also, when I try to move with the arrow key or erase one song it not working at all, look I have tick on song to move and one windows come like this and nothing move at all same to try to erase it!! https://gyazo.com/8b7a503786c41c3745d12a8fb8338f0e

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

https://gyazo.com/8b7a503786c41c3745d12a8fb8338f0e
**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by afonsosantos** [comment]
Can you please update your issue and write your question in the correct place?

**Comment by ApoTHEOSeSBallroom** [comment]
Sorry but i am new and need help. I only find this place to receive help for the Web DJ, and when I click on help it's bring me to AzuraCast with millions problem to read it's bloody annoying

**Comment by ApoTHEOSeSBallroom** [comment]
I have notice on Second Life the playlist is not following at all the order I have programming it on the SamBroadcastion Pro tool. as I said was on M3U version. I have bring it to the Web Dj but the system don't respect at all the order I have created. I have try to move one the Web DJ the song on one different rank, when I move them with the arrow it's move up or down but as soon I return to the profil...all return as it was before my changing...also I don't find any place to save my changing.... very disappointed of this system!

**Comment by SlvrEagle23** [comment]
@ApoTHEOSeSBallroom We have a template for the body of the GitHub issue and it appears you left it blank. Please go back and edit the template to provide answers to the questions, as we need that information to be able to diagnose your problem.

You should also move the title of the issue down into the description and use a shorter, more concise title.

**Comment by ApoTHEOSeSBallroom** [comment]
Can you screen shot the place I don't know where is it

**Comment by ApoTHEOSeSBallroom** [comment]
https://gyazo.com/692f9435e1ea4ff796e0688907d176a5 are you talking about it? if yes How I can filled it? never do it

**Comment by SlvrEagle23** [comment]
@ApoTHEOSeSBallroom Click "Edit" there and actually answer the questions in the blank spaces between them.

**Comment by ApoTHEOSeSBallroom** [comment]
Can you tell me what Template are you talking about??? Don’t understand and what you need to know


Provenance : Courrier pour Windows 10

De : SlvrEagle23
Envoyé le :29 juillet 2019 12:08
À : AzuraCast/AzuraCast
Cc : ApoTHEOSeSBallroom; Mention
Objet :Re: [AzuraCast/AzuraCast] When I want move one song from my musiclist or erase it it's won't move or erase. I have upload my own playlist fromSam broadcast in M3U but your system don't follow the order grrrrrrrr I havetry all solution, but it's only follow the base list of music who is uploadto the system?? some body can help me. Thank you. (#1794)

@ApoTHEOSeSBallroom We have a template for the body of the GitHub issue and it appears you left it blank. Please go back and edit the template to provide answers to the questions, as we need that information to be able to diagnose your problem.
You should also move the title of the issue down into the description and use a shorter, more concise title.

**Comment by ApoTHEOSeSBallroom** [comment]
When I edit I can only change the Title...so the little screen with all info as the snap shot, I can't do nothing with it.  https://gyazo.com/2d2ad8ae23767931f5d706c84a733673

**Comment by ApoTHEOSeSBallroom** [comment]
It is a way to make the program follow my own playlist, can you explain step by step the set up to do it. thank you

**Comment by kemecs** [comment]
this is a problem for me too

**Comment by SlvrEagle23** [comment]
@kemecs The original issue didn't provide us with enough information to diagnose the problem, so perhaps you can help us by explaining exactly what isn't working in this case.

Are you trying to import the playlist via the "Edit Playlist" page, and it's not following that order?
