### ISSUE TITLE
Connect Traktor streaming software with Azuracast

### ISSUE THREAD

**Issue by NakedFool** [AzuraCast/AzuraCast#1797]
Hey fellow people,

First of all amazing tool that helped me launch easily radio, some minor issues that i needed to overcome but most important that i can't figure out is streaming with traktor.

Traktor supports IceCast so in theory it is possible, however when i pass data there of server ip adress , mount and password of a dj account created that icon is still blinking and not connected to the server.

Anyone can help me with this? This could be usable for others also as i have not found how to connect with Traktor :)

**Comment by ErnestPH** [comment]
Can you add a screenshot of your setting? That could help. Thanks!

**Comment by NakedFool** [comment]
Sure!

![image](https://user-images.githubusercontent.com/18723426/62086123-b501af80-b25d-11e9-905f-e0b9f9dbdb6f.png)

Basically i just copied from the server field that ip adress and pasted it there ( i don't know due to security reasons if i should share it but if you want it is ok :D ) 

Password in the traktor what is password in the dj field, whatever you need more just ask me i'll do everything i can :)

**Comment by SlvrEagle23** [comment]
@NakedFool We have some stations using Traktor to DJ to AzuraCast and they haven't reported any issues. I'm curious if it's a matter of port availability on your server: are you behind CloudFlare or some other sort of reverse proxy? If so, you should use your direct IP address instead of your domain name.

**Comment by NakedFool** [comment]
@SlvrEagle23 Hey, i believe that people are connecting well but i after hours of googling couldn't find the solution so i figured out if i can ask here.

And yeah, when i set this up i can actually write it in the section for streaming softwares guide for traktor if needed :)

**Comment by NakedFool** [comment]
One more thing to note : 

With Butt i connect successfully - i guess maybe i'm doing something wrong with Traktor but i can't see where i'm wrong there.

**Comment by afonsosantos** [comment]
@NakedFool You are selecting `Ogg Vorbis` in Format. Shouldn't that be MP3?

**Comment by NakedFool** [comment]
@afonsosantos  Traktor can only output Ogg Vorbis as format in broadcasting.

**Comment by SlvrEagle23** [comment]
The AutoDJ streamer input should accept Ogg Vorbis as well.

I've heard some people say that their streaming software requires that the DJ mount point be "", rather than "/"... @NakedFool you can edit that detail in your station profile and see if that helps.

**Comment by NakedFool** [comment]
@SlvrEagle23 Do i assign it as i did here? As i do not if when streamer is connected should i overwrite default mountpoint to listen on .ogg or i can create this second one?

![image](https://user-images.githubusercontent.com/18723426/62117868-0beaa180-b2bd-11e9-83db-70e734e20b5c.png)

**Comment by SlvrEagle23** [comment]
@NakedFool If you use our streamer/DJ system, that is handled through Liquidsoap, not the Icecast mount points. You can broadcast directly to Icecast if you like by setting up something similar to what you already have there: A "live" stream that listeners connect to, and that has a fallback of the regular radio stream.

**Comment by NakedFool** [comment]
@SlvrEagle23 

So maybe by setting through icecast new mountpoint that is not dependable on Liquisoap?

I'll try today with actually players and everything and inform you :)

**Comment by ImaCrea** [comment]
Hey @NakedFool did you find the solution? :)

**Comment by krono86** [comment]
Traktor is able to connect to Icecast v1 servers, AzuraCast (Liquidsoap's harbor source) exposes as Icecast v2 server.
The problem should be fixed on the Traktor side.

**Comment by TimSusa** [comment]
I figured it out Bro! 

Just use USERNAME,PASSWORD (compared to using BUTT for example they want double colon) AND use the IP not the url for the Adress field.. the rest of settings simply just like shown in the first screenshot from above
