### ISSUE TITLE
API: nowplaying

### ISSUE THREAD

**Issue by RabidDog** [AzuraCast/AzuraCast#180]
Hi guys

Is it possible, when live broadcasting, to set a flag indicating it is a live broadcast and not the auto DJ? Having difficulty rendering live broadcast metadata inside custom client.

**Comment by SlvrEagle23** [comment]
@RabidDog Done! The API now includes, for the now playing song, an "is_live" flag will indicate whether the AzuraCast AutoDJ determined the next song or not, which is a reliable indicator for whether the current song is being played live or not.
