### ISSUE TITLE
Nchan websocket spamming status 405 errors

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#1801]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu 18.4
**Describe the bug**

> Error during WebSocket handshake: Unexpected response code: 405

This is being repeatedly spammed in my console and logs
**To Reproduce**
Simple observe network traffic on your web station. 
**Expected behavior**
Not to spam it repeatedly with 405s.
**Relevant Logs**
```
`influxdb_1  | [httpd] 172.31.0.6 - - [31/Jul/2019:02:37:49 +0000] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.3.3 curl/7.58.0 PHP/7.2.19-0ubuntu0.18.04.1" 30322c2a-b33c-11e9-806b-000000000000 2253

web_1       | [2019-07-31 02:37:50] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []

web_1       | [2019-07-31 02:37:50] AzuraCast.INFO: Handling message of type App\Message\NotifyNChanMessage. [] []

influxdb_1  | [httpd] 172.31.0.6 - - [31/Jul/2019:02:37:50 +0000] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.3.3 curl/7.58.0 PHP/7.2.19-0ubuntu0.18.04.1" 30684262-b33c-11e9-806c-000000000000 1061

web_1       | [2019-07-31 02:37:50] AzuraCast.INFO: New message of type App\Message\NotifyNChanMessage added to queue. [] {"station":{"id":20,"name":"Los Santos Underground"}}

web_1       | [2019-07-31 02:37:52] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []

web_1       | [2019-07-31 02:37:52] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []

influxdb_1  | [httpd] 172.31.0.6 - - [31/Jul/2019:02:37:52 +0000] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.3.3 curl/7.58.0 PHP/7.2.19-0ubuntu0.18.04.1" 31b049ba-b33c-11e9-806d-000000000000 848

influxdb_1  | [httpd] 172.31.0.6 - - [31/Jul/2019:02:37:52 +0000] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.3.3 curl/7.58.0 PHP/7.2.19-0ubuntu0.18.04.1" 31b1b917-b33c-11e9-806e-000000000000 868

web_1       | [2019-07-31 02:37:52] AzuraCast.INFO: New message of type App\Message\NotifyNChanMessage added to queue. [] {"station":{"id":21,"name":"Wicked FM"}}
web_1       | [2019-07-31 02:37:52] AzuraCast.INFO: New message of type 
App\Message\NotifyNChanMessage added to queue. [] {"station":{"id":24,"name":"SaintsFM"}}
ERROR: Aborting.
```
**Screenshots**
[Screenshots of the error console](https://puu.sh/DZqMp.png)
[network tab
](https://puu.sh/DZqMU.png)
**Device(s):**
 - Device: Win 10 pc
 - OS: win 10
 - Browser:  Chrome
 - Version: Latest

**Additional context**

**Comment by SC2Mitch** [comment]
Fixed in the latest commit.

**Comment by smilingpeanut** [comment]
I'm getting 405 errors when attempting to use Web Sockets as well, and this is with the latest version [Docker, v0.10.3, #1447c7c (2020-06-23 10:39)].

[Screenshot](https://cloudup.com/cfCQwsiTJN0)
[Public Page](https://stream.noco.fm/public/noco-fm)

**Comment by SlvrEagle23** [comment]
@smilingpeanut It may be a good idea to make a new issue, since this one has already been closed about a year ago. Make sure to include any logs from `docker-compose logs -f web` that may explain what's actually happening.

**Comment by ttodua** [comment]
turned out same fix for me: https://github.com/AzuraCast/AzuraCast/issues/2412
