### ISSUE TITLE
No more songs for request when I update to AzuraCast version 0.9.6 

### ISSUE THREAD

**Issue by stemvantwente** [AzuraCast/AzuraCast#1804]
Installation method
"Traditional" installation method.

Host OS (for Docker installations)
Ubuntu 1804 (VPS)

Describe the bug:

If I update to AzuraCast to version 0.9.6, and I go public page and then song request it says nothing found, all my songs dont show up anymore.

Greets
Roy

**Comment by Rafaelrds2017** [comment]
I can request songs, but they don't play. It stands in line but does not play.

**Instalação Auto-Hospedada - NYC3 - Ubuntu 18.04 x64**

AzuraCast • v0.9.6, #ba0b4f6 (2019-08-08 16:15) • Docker • PHP 7.2
