### ISSUE TITLE
How to run on an existing Nginx

### ISSUE THREAD

**Issue by ErriourRU** [AzuraCast/AzuraCast#1806]
I'm already have on my server nginx for another websites. If I try to run AzuraCast by default, I have an error that port 80 already in use. Of course I can change port to what I want in docker, but then I will have address like https://subdomain.domain.com:port/. It's not beautiful. How can I run engine on my already installed nginx? Or can I redirect on without port?

**Comment by ErnestPH** [comment]
@ErriourRU I believe this is not recommended. The suggested installation is on a server without any other software installed...

**Comment by ErriourRU** [comment]
@ErnestPH It's not recommended but?.. I can't do another way.

**Comment by Vaalyn** [comment]
You can run AzuraCast on a different port and use your existing nginx to reverse proxy it. I have no example configuration at hand for nginx but there is one for apache wich you may be able to adapt to nginx: https://github.com/AzuraCast/AzuraCast/issues/1328

**Comment by ErriourRU** [comment]
@Vaalyn Yes it works. But in this way I can't embed radio in main site by means iframe:
`WebSocket connection to 'wss://subdomain.domain.com/api/live/nowplaying/radio' failed: Error during WebSocket handshake: Unexpected response code: 200`

I'm using SSL created by certbot and this nginx configuration for proxying:
`
proxy_set_header HOST $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    location / {
        proxy_pass http://subdomain.domain.com:port;
    }
`

**Comment by yarik2720** [comment]
I'm running with this configuration:
```
	location / {
		proxy_pass http://127.0.0.1:8080;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection 'upgrade';
		proxy_set_header Host $host;
		proxy_cache_bypass $http_upgrade;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_connect_timeout 240s;
		set_real_ip_from 0.0.0.0/0;
	}
```
But have problem, that client ip is not forwards, such on web logs and on Song requests I see IP from docker subnet, like 192.168.80.1

**Comment by yarik2720** [comment]
Hi! Is there still any solution with proxying from nginx on host machine to azuracast, that it can show real user ip?

**Comment by linjan** [comment]
> Hi! Is there still any solution with proxying from nginx on host machine to azuracast, that it can show real user ip?

Just use this block in your nginx:
```
        # reverse proxy
        location / {
            proxy_pass                         http://127.0.0.1:28080;
            proxy_http_version                 1.1;
            proxy_cache_bypass                 $http_upgrade;

            # Proxy headers
            proxy_set_header Upgrade           $http_upgrade;
            proxy_set_header Connection        "upgrade";
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host  $host;
            proxy_set_header X-Forwarded-Port  $server_port;

            # Proxy timeouts
            proxy_connect_timeout              2400s;
            proxy_send_timeout                 60s;
            proxy_read_timeout                 60s;
        }

```

**Comment by dikkedimi** [comment]
I am facing similar issues. I would like to run my mac mini as a content distribution network AND a local dev server. I intend to use azuracast with liquidsoap and other related apps to push my label's radio to youtube and icecast.

While docker is very easy and portable, these types of issues have always been a reason not to use it. Since Azuracast offers no other install options, I was forced to use this software which I've grown to detest.

From the documentation it was unclear on which port Azuracast listens, but I assume it is port 80, since post-install says to navigate to the servers's adress (automatically being port 80 for HTTP).

I've used the config above with slight modifications:
```
server {
        listen 80;
        listen [::]:80;

        root /;
#        index index.html index.htm index.nginx-debian.html;

#        server_name altruist-rec.com www.altruist-rec.com;

#        location / {
#                try_files $uri $uri/ =404;
#        }

        # Php my admin directory!
#        location ^~ ../phpmyadmin {
#
#        }

 #       location ~ \.php$ {
 #               include snippets/fastcgi-php.conf;
 #               fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
 #       }
        # reverse proxy
        location / {
            proxy_pass                         http://127.0.0.1:80;
            proxy_http_version                 1.1;
            proxy_cache_bypass                 $http_upgrade;

            # Proxy headers
            proxy_set_header Upgrade           $http_upgrade;
            proxy_set_header Connection        "upgrade";
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host  $host;
            proxy_set_header X-Forwarded-Port  $server_port;

            # Proxy timeouts
            proxy_connect_timeout              2400s;
            proxy_send_timeout                 60s;
            proxy_read_timeout                 60s;
        }
}


```


```400 Bad Request
Request Header Or Cookie Too Large
nginx/1.18.0 (Ubuntu)```

error.log shows
```
2023/01/30 13:36:05 [alert] 5736#5736: *1740 768 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: , request: "GET /img/bg.jpg HTTP/1.1", upstream: "http://127.0.0.1:80/img/bg.jpg", host: "10.0.0.253", referrer: "http://10.0.0.253/css/colorscheme.css"
```
