### ISSUE TITLE
SoundExchange Report

### ISSUE THREAD

**Issue by mele-uk** [AzuraCast/AzuraCast#1807]
Hi,

SoundExchange Report feature does not generate a report.
It just generates a HTML file which has the same content as the SoundExchange Report page.

**Comment by SlvrEagle23** [comment]
@mele-uk Are you sure that's not an error message being displayed as full HTML? Check the contents of the file to make sure. The SoundExchange report should be functioning as expected, producing a TXT file that complies with their report style.

**Comment by mele-uk** [comment]
Solved. I tried Firefox and worked.
