### ISSUE TITLE
Total Listening Hours (TLH)

### ISSUE THREAD

**Issue by mele-uk** [AzuraCast/AzuraCast#1808]
Hi,

1) How can I have a TLH (Total Listening Hours) report for a specific period?
2) Is it possible to download generated reports under Reports > Listeners ?

**Comment by SlvrEagle23** [comment]
@mele-uk The latest commit will now show you the unique listener count and the computed Total Listening Hours for the time period you selected in the Listeners report. This is fairly simple to extrapolate given the data the API already returns, so I added it in with few changes to the underlying code. I also added in some code that will ensure that if a listener was connected from before (or until after) the report period, it won't consider the period outside the report in that listener hours calculation.

The other request, to make the listener report downloadable as a CSV or other style report, I believe is an existing request over on our [FeatureUpvote site](https://features.azuracast.com/). If not, you can create it there for us to see when working on new features for the project.

**Comment by mele-uk** [comment]
Thank you!

**Comment by mele-uk** [comment]
I think we describe TLH differently. The report actually does not show THL by my meaning.

By Total Listening Hours (TLH) , I mean the amount of time my station stream is listened to by all of my listeners in total. 
The equation to figure out a station's monthly TLH is as follows: (Number of Listeners Over the Course of a Month x Average Minutes Listened) ÷ Minutes in an Hour = Total Listening Hours

**Comment by SlvrEagle23** [comment]
@mele-uk The way we're calculating Total Listener Hours (a sum of the actual listening seconds of every connected user, divided by the 3600 seconds in an hour) yields the same total as if you took the average and multiplied it by the listener count. They're both referring to the same total but via slightly different means of arriving at the same number.

If you're seeing the number being dramatically off, we may need to correct something in there, but our calculation represents the Total Listener Hours within the time period you select in the report.
