### ISSUE TITLE
"New client: XXX.XXX.XXX.XXX" entry in Liquidsoap log upon playlist update

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1809]
We have a bunch of custom playlists where we add and remove tracks from time to time. In the regular case we see an entry similar to this after such adds and removes: 

`2019/08/01 13:23:38 [playlist_off_air:3] Successfully loaded a playlist of 41 tracks.`

Some other times we see something like this, which I don't really understand (XXX.XXX.XXX.XXX seems to be an IP address, I deleted the real numbers ):  

`2019/08/01 13:24:07 [server:3] New client: XXX.XXX.XXX.XXX.`

Question: will my playlist be properly reloaded? And why do I see different messages?

**Comment by SlvrEagle23** [comment]
@gammaw That's AzuraCast connecting to Liquidsoap via Telnet to issue the "reload this playlist's contents" command. The IP is likely one of Docker's internal IPs (172.x.x.x) if you're using Docker, which means it's just coming from another container. Nothing to worry about there.

**Comment by gammaw** [comment]
@SlvrEagle23 I see. And do you know why I don't see a "Successfully loaded a playlist of XX tracks" log entry in these cases? Does the absence of this entry mean that Azuracast didn't reload the playlist?

**Comment by SlvrEagle23** [comment]
@gammaw I don't know the answer to that question.

**Comment by gammaw** [comment]
@SlvrEagle23 fyi: we tested it and Liquidsoap won't load the playlist if there is no "Successfully loaded a playlist of XX tracks" entry in the log. Do you think it's an issue with Liquidsoap? I'm not sure how to state a question for them because I don't know how the communication between Azuracast and Liquidsoap works exactly. Can you help with this? What worries me is that the behavior is not deterministic (at least I don't know when it is triggered), in most of the cases it works as intended and we can load new playlists on the fly (without restarting Liquidsoap).
