### ISSUE TITLE
No sound on the station's public page after site encoding with let's encrypt

### ISSUE THREAD

**Issue by NadjaNeville** [AzuraCast/AzuraCast#1810]
Using DOCKER install latest build, just updated on Ubuntu 18.04.2

Every other link to play sound on the management page works, just the embed code and public page don't play sound and they are popular features with my stations. Is there any way the "play" button on the public page uses some code that plays music like on the management page?

**Comment by SlvrEagle23** [comment]
@NadjaNeville The public players depend on now-playing data being supplied by the API, and after an update this can take a few minutes to first be delivered. It should start being delivered relatively quickly, though.

Let me look into possible ways we can optimize that.

**Comment by SlvrEagle23** [comment]
@NadjaNeville I've made some updates to how the Now Playing data is loaded into the public players, so they should at least play even if API data isn't pulling through correctly.

There is a system setting you may need to turn off: the "Use Websocket for Now Playing Updates" setting in the system-wide settings page. Turning this off will switch you back to the previous method of pulling now-playing updates which is somewhat slower but quite a bit more reliable.

**Comment by NadjaNeville** [comment]
@SlvrEagle23 Your suggested method didn't bring sound, but ticking the global setting "use web proxy for radio" makes the public page play sound. Thanks for the awesome software! :)

**Comment by SlvrEagle23** [comment]
@NadjaNeville Ah, that's a different issue that is often fixed by restarting the radio services (via "Utilities" > "Restart Broadcasting" on the station menu), but I'm glad you were able to get it working for your scenario!
