### ISSUE TITLE
Azuracast ERROR: The Compose file is invalid because: Service stations has neither an image nor a build context specified. At least one must be provided.

### ISSUE THREAD

**Issue by pwrj** [AzuraCast/AzuraCast#1811]
Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-31-generic x86_64)

I'm getting this Azuracast ERROR with the latest install when I issue the following commands:

./docker.sh update-self
./docker.sh update

**Output:** 
The Compose file is invalid because: Service stations has neither an image nor a build context specified. At least one must be provided.

**Comment by SlvrEagle23** [comment]
@pwrj Our Docker Compose file hasn't changed in a significant way in quite a while. Did you modify or override it via `docker-compose.override.yml`?

**Comment by pwrj** [comment]
@SlvrEagle23  No, this just a new install.

**Comment by SlvrEagle23** [comment]
@pwrj Try running `cat docker-compose.yml` and comparing that against [docker-compose.sample.yml](https://github.com/AzuraCast/AzuraCast/blob/master/docker-compose.sample.yml). It may have cut off in the middle or something else bizarre like that.

**Comment by pwrj** [comment]
**OUTPUT**

root@xxxx:~# cat docker-compose.yml
version: '2.2'

services:
  relay:
    image: azuracast/azurarelay:latest
    env_file: azurarelay.env
    volumes:
      - letsencrypt:/etc/letsencrypt
      - tmp_data:/var/azurarelay/www_tmp
      - station_data:/var/azurarelay/stations
    restart: always
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    ports:
     - '${AZURARELAY_HTTP_PORT:-80}:80'
     - '${AZURARELAY_HTTPS_PORT:-443}:443'
     - '8000:8000'
     - '8010:8010'
     - '8020:8020'
     - '8030:8030'
     - '8040:8040'
     - '8050:8050'
     - '8060:8060'
     - '8070:8070'
     - '8090:8090'
     - '8100:8100'
     - '8110:8110'
     - '8120:8120'
     - '8130:8130'
     - '8140:8140'
     - '8150:8150'
     - '8160:8160'
     - '8170:8170'
     - '8180:8180'
     - '8190:8190'
     - '8200:8200'
     - '8210:8210'
     - '8220:8220'
     - '8230:8230'
     - '8240:8240'
     - '8250:8250'
     - '8260:8260'
     - '8270:8270'
     - '8280:8280'
     - '8290:8290'
     - '8300:8300'
     - '8310:8310'
     - '8320:8320'
     - '8330:8330'
     - '8340:8340'
     - '8350:8350'
     - '8360:8360'
     - '8370:8370'
     - '8380:8380'
     - '8390:8390'
     - '8400:8400'
     - '8410:8410'
     - '8420:8420'
     - '8430:8430'
     - '8440:8440'
     - '8450:8450'
     - '8460:8460'
     - '8470:8470'
     - '8480:8480'
     - '8490:8490'

volumes:
  letsencrypt: {}
  station_data: {}
  tmp_data: {}root@xxxx:~#

**Comment by SlvrEagle23** [comment]
@pwrj But that's AzuraRelay's Docker Compose file, not AzuraCast's....

**Comment by pwrj** [comment]
@SlvrEagle23 - I don't understand. I installed Azuracast and nothing else. This is a new clean reinstall. My station is up and running....just can't update it.

**Comment by SlvrEagle23** [comment]
@pwrj I have no idea how you wound up with AzuraRelay's Compose file instead of the correct one. I'm wondering if when you ran `docker.sh update-self` for some reason it pulled the wrong Docker utility script.

That's really not supposed to happen! I don't even know how it _could_ happen.

**Comment by SlvrEagle23** [comment]
@pwrj The easy solution is to just redownload the utility script (follow that line of the original installation instructions again) and then try updating with it again.

**Comment by pwrj** [comment]
@SlvrEagle23 I'm as puzzled as you are. Will I lose my data if re-download the utility script?
By the way, is that suppose to be the installation path for docker? I'm just curious because I have Auracast here: /var/azuracast/
and docker here: /var/lib/docker/

**Comment by SlvrEagle23** [comment]
@pwrj No, redownloading the utility script shouldn't affect your stations Docker containers. All of your installation paths are normal.

**Comment by pwrj** [comment]
@SlvrEagle23 Thank you. I'll try that.

**Comment by ab5hl** [comment]
Got this error today updating one of my installs.
No way to recover, did a clean install, running from backups, then after troubleshooting some of the shoutcast stations, again same error.

**Comment by christiansacks** [comment]
I just got the same too, upgrading from 2022-01-16 with docker to the today's version caused the same, luckily I cloned the vm prior as it totally whacked the install. Any ideas where the issue is?

**Comment by SlvrEagle23** [comment]
@ab5hl @christiansacks We have a difficult time telling if Docker needs updating in our utility script, but this problem is easily solved by running:

```
./docker.sh update-self
./docker.sh install-docker
./docker.sh install-docker-compose
```

**Comment by christiansacks** [comment]
That's interesting, I did do a full system update prior to running the update script, so I don't think it required updating again.
Maybe there's another issue?

**Comment by SlvrEagle23** [comment]
@christiansacks So, fun fact about this one...docker has actually changed its package name several times in its history, so any sufficiently old installation of Docker would, even with a package update, not update to the newest version as a result of that repeated renaming. That's why using their installer script is basically the only way to ensure you're on the very latest version and to clean out older ones.

**Comment by christiansacks** [comment]
Just doing this now, looks like there's a lot that may have changed with docker ... noticing the new spinner... it's taking a lot longer to extract the images too, so I imagine a lot has changed since Jan.

Okay, that seems to have finished;
```
AzuraCast Updater
=================

 Change installation settings? (yes/no) [no]:
 > 

Writing configuration files...

                                                                                                                        
 [OK] Server configuration complete!                                                                                    
                                                                                                                        

[+] Running 1/1
 ⠿ web Pulled                                                                                                                                                                                              0.6s
[+] Running 1/0
 ⠿ azuracast  Warning: No resource found to remove                                                                                                                                                         0.0s
service "stations" has neither an image nor a build context specified: invalid compose project
service "stations" has neither an image nor a build context specified: invalid compose project
Clean up all stopped Docker containers and images to save space? [Y/n] 
Deleted Networks:
azuracast_installer_default

Total reclaimed space: 0B
Update complete!
```

Looks like it hasn't worked still.

**Comment by christiansacks** [comment]
```
root@radio:~/git/AzuraCast# diff -u docker-compose.yml docker-compose.yml.20220405 
--- docker-compose.yml	2022-04-05 12:27:53.746397397 +0000
+++ docker-compose.yml.20220405	2022-04-05 12:21:12.030316097 +0000
@@ -1,11 +1,113 @@
 services:
-    web:
-        container_name: azuracast
-        image: 'ghcr.io/azuracast/azuracast:${AZURACAST_VERSION:-latest}'
+    nginx_proxy:
+        container_name: nginx_proxy
+        image: 'ghcr.io/azuracast/nginx_proxy:${AZURACAST_VERSION:-latest}'
         ports:
             - '${AZURACAST_HTTP_PORT:-80}:80'
             - '${AZURACAST_HTTPS_PORT:-443}:443'
+        volumes:
+            - 'letsencrypt:/etc/nginx/certs'
+            - 'nginx_proxy_vhosts:/etc/nginx/vhost.d'
+            - 'letsencrypt_html:/usr/share/nginx/html'
+            - '/var/run/docker.sock:/tmp/docker.sock:ro'
+        environment:
+            NGINX_TIMEOUT: '${NGINX_TIMEOUT:-1800}'
+            DEFAULT_HOST: '${LETSENCRYPT_HOST:-azuracast.local}'
+        networks:
+            - frontend
+        depends_on:
+            - web
+        restart: unless-stopped
+    nginx_proxy_letsencrypt:
+        container_name: nginx_proxy_letsencrypt
+        image: 'ghcr.io/azuracast/nginx_proxy_letsencrypt:${AZURACAST_VERSION:-latest}'
+        volumes_from:
+            - nginx_proxy
+        volumes:
+            - 'letsencrypt_acme:/etc/acme.sh'
+            - '/var/run/docker.sock:/var/run/docker.sock:ro'
+        environment:
+            DEFAULT_EMAIL: '${LETSENCRYPT_EMAIL:-}'
+        networks:
+            - frontend
+        restart: unless-stopped
+    web:
+        container_name: azuracast_web
+        image: 'ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}'
+        ports:
             - '${AZURACAST_SFTP_PORT:-2022}:2022'
+        depends_on:
+            - mariadb
+            - stations
+            - redis
+        env_file: azuracast.env
+        environment:
+            LANG: '${LANG:-en_US.UTF-8}'
+            AZURACAST_DC_REVISION: 12
+            AZURACAST_VERSION: '${AZURACAST_VERSION:-latest}'
+            AZURACAST_SFTP_PORT: '${AZURACAST_SFTP_PORT:-2022}'
+            VIRTUAL_HOST: '${LETSENCRYPT_HOST:-azuracast.local}'
+            NGINX_TIMEOUT: '${NGINX_TIMEOUT:-1800}'
+            LETSENCRYPT_HOST: '${LETSENCRYPT_HOST:-}'
+            LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL:-}'
+            PUID: '${AZURACAST_PUID:-1000}'
+            PGID: '${AZURACAST_PGID:-1000}'
+        volumes:
+            - 'letsencrypt:/etc/nginx/certs:ro'
+            - 'www_vendor:/var/azuracast/www/vendor'
+            - 'www_uploads:/var/azuracast/uploads'
+            - 'tmp_data:/var/azuracast/www_tmp'
+            - 'station_data:/var/azuracast/stations'
+            - 'shoutcast2_install:/var/azuracast/servers/shoutcast2'
+            - 'geolite_install:/var/azuracast/geoip'
+            - 'sftpgo_data:/var/azuracast/sftpgo/persist'
+            - 'backups:/var/azuracast/backups'
+        networks:
+            - frontend
+            - backend
+        restart: unless-stopped
+        ulimits:
+            nofile:
+                soft: 65536
+                hard: 65536
+        logging:
+            options:
+                max-size: 1m
+                max-file: '5'
+    mariadb:
+        container_name: azuracast_mariadb
+        image: 'ghcr.io/azuracast/db:${AZURACAST_VERSION:-latest}'
+        volumes:
+            - 'db_data:/var/lib/mysql'
+        env_file: azuracast.env
+        networks:
+            - backend
+        restart: unless-stopped
+        logging:
+            options:
+                max-size: 1m
+                max-file: '5'
+    redis:
+        container_name: azuracast_redis
+        image: 'ghcr.io/azuracast/redis:${AZURACAST_VERSION:-latest}'
+        sysctls:
+            net.core.somaxconn: 1024
+        volumes:
+            - 'redis_data:/data'
+        networks:
+            - backend
+        restart: unless-stopped
+        logging:
+            options:
+                max-size: 1m
+                max-file: '5'
+    stations:
+        container_name: azuracast_stations
+        image: 'ghcr.io/azuracast/radio:${AZURACAST_VERSION:-latest}'
+        environment:
+            PUID: '${AZURACAST_PUID:-1000}'
+            PGID: '${AZURACAST_PGID:-1000}'
+        ports:
             - '8000:8000'
             - '8005:8005'
             - '8006:8006'
@@ -153,27 +255,15 @@
             - '8490:8490'
             - '8495:8495'
             - '8496:8496'
-        env_file: azuracast.env
-        environment:
-            LANG: '${LANG:-en_US.UTF-8}'
-            AZURACAST_DC_REVISION: 14
-            AZURACAST_VERSION: '${AZURACAST_VERSION:-latest}'
-            AZURACAST_SFTP_PORT: '${AZURACAST_SFTP_PORT:-2022}'
-            NGINX_TIMEOUT: '${NGINX_TIMEOUT:-1800}'
-            LETSENCRYPT_HOST: '${LETSENCRYPT_HOST:-}'
-            LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL:-}'
-            PUID: '${AZURACAST_PUID:-1000}'
-            PGID: '${AZURACAST_PGID:-1000}'
         volumes:
-            - 'letsencrypt:/etc/nginx/certs'
-            - 'letsencrypt_acme:/etc/acme.sh'
-            - 'www_uploads:/var/azuracast/uploads'
             - 'station_data:/var/azuracast/stations'
             - 'shoutcast2_install:/var/azuracast/servers/shoutcast2'
-            - 'geolite_install:/var/azuracast/geoip'
-            - 'sftpgo_data:/var/azuracast/sftpgo/persist'
-            - 'backups:/var/azuracast/backups'
-            - 'db_data:/var/lib/mysql'
+            - 'letsencrypt:/etc/nginx/certs'
+            - 'tmp_data:/var/azuracast/www_tmp'
+        networks:
+            - frontend
+            - backend
+        init: true
         restart: unless-stopped
         ulimits:
             nofile:
@@ -183,13 +273,23 @@
             options:
                 max-size: 1m
                 max-file: '5'
+networks:
+    frontend:
+        driver: bridge
+    backend:
+        driver: bridge
 volumes:
+    nginx_proxy_vhosts: {  }
     db_data: {  }
     letsencrypt: {  }
+    letsencrypt_html: {  }
     letsencrypt_acme: {  }
     shoutcast2_install: {  }
     geolite_install: {  }
     sftpgo_data: {  }
     station_data: {  }
+    www_vendor: {  }
     www_uploads: {  }
+    tmp_data: {  }
+    redis_data: {  }
     backups: {  }
```

**Comment by christiansacks** [comment]
Well, I can say that it's royally borked now lol. Glad I cloned the VM =)

**Comment by christiansacks** [comment]
So it installed docker via snap originally, but that command you gave me seems to install it another way, and the two can't live happily together, so... gonna have to stay as I am for now until there's another way to upgrade I guess. :/

**Comment by SC2Mitch** [comment]
I propose creating a new issue as this one is currently 3 years old

**Comment by SlvrEagle23** [comment]
> So it installed docker via snap originally, but that command you gave me seems to install it another way, and the two can't live happily together, so... gonna have to stay as I am for now until there's another way to upgrade I guess. :/

Our instructions assume you followed our instructions to do the initial setup, which is a pretty reasonable assumption on our part generally speaking. We don't recommend using Docker via snapd and we actually have warnings against that now in our documentation.

There's another pinned issue about recent changes to `docker-compose.yml` that require that you update any `docker-compose.override.yml` files you may have. I'd recommend looking at that issue, as we no longer use the "stations" container at all in newer versions.

If you're having further issues, as Mitch mentioned, please create a new GitHub issue for it.
