### ISSUE TITLE
Azuracast Player embed is not working on other sites

### ISSUE THREAD

**Issue by Moderndayfreak** [AzuraCast/AzuraCast#1814]
**Using Docker installation method**

Yes
**Host Operating System**

Ubuntu 18
**Describe the bug**

Azuracast Player embed is not working on other sites
**To Reproduce**

copy and paste embed player iframe code on other site
**Expected behavior**

its doesn't appear
**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 
Coding on a desktop
**Additional context**

**Comment by Vaalyn** [comment]
I've tried to replicate the issue with the embed code of the demo installation. This seems to be working. I've also tried to embed it on GitHub via editing the page and there it failed due to a CSP violation.

Can you see any errors in your browsers JavaScript console?
This would help me to identify where the issue is coming from exactly in your case.

**Comment by SlvrEagle23** [comment]
@Moderndayfreak I've made some updates to our Docker web image so that the radio stream and the websocket updates both send an `Access-Control-Allow-Origin: *` header, which should allow embedding on any pages.

**Comment by Moderndayfreak** [comment]
its still not working. Check out ---> shorturl.at/ceknZ 

I have the iframe code embedded and its not showing up. I also used short url to hide the domain because I dont want it showing up on the search engines.

**Comment by Moderndayfreak** [comment]
Ok I got it to work but every other second the player shows  "Stream Offline". This is another issue.

**Comment by SlvrEagle23** [comment]
@Moderndayfreak Can you link the public player for your AzuraCast instance?

**Comment by Moderndayfreak** [comment]
SlverEagle is there a way I can message you so you can login? I don't have it available on the site because of this error. Thanks

**Comment by SlvrEagle23** [comment]
@Moderndayfreak You can join our [Slack channel](https://azuracast.com/slack) and message me there.

**Comment by gasguti** [comment]
I have the iframe code embedded and its not showing up too, any solution yet?

**Comment by infogatel2** [comment]
I can confirm that the problem is still there. Embed is not working to joomla pages or wordpress.

**Comment by SC2Mitch** [comment]
Create a new issue, this one is 3 years old.
