### ISSUE TITLE
File not found - New

### ISSUE THREAD

**Issue by pwrj** [AzuraCast/AzuraCast#1816]
I updated the software yesterday using the commands on the website. Traditional docker install.

./docker.sh update-self
./docker.sh update
Now when I go to my domain I simply get a File not found message. 

Running tail -f /var/azuracast/www_tmp/php_errors.log outputs:

tail: cannot open '/var/azuracast/www_tmp/php_errors.log' for reading: No such file or directory
tail: no files remaining
Running docker-compose run --rm cli azuracast_update outputs:

ERROR: No such service: cli

**Comment by afonsosantos** [comment]
Hi,

Did you try to update again (`./docker.sh update`)? I had that issue some time ago, and updating again usually solved the issue.

**Comment by pwrj** [comment]
@afonsosantos When I tried updating, nothing happens.
#./docker.sh update
#

**Comment by afonsosantos** [comment]
Hum, not sure what's happening there. You may need to wait until a staff member checks this issue.

**Comment by pwrj** [comment]
@afonsosantos looks like I have to.

**Comment by Vaalyn** [comment]
Have you encountered any errors while executing:
```
./docker.sh update-self
./docker.sh update
```
