### ISSUE TITLE
Letsencrypt does not work

### ISSUE THREAD

**Issue by NurLutix** [AzuraCast/AzuraCast#1819]
Hey,
I'm using Docker on Ubuntu 16.04.

I'm entering the following command:
./docker.sh letsencrypt-create DOMAIN.de

But with Google Chrome I get the following error:

This is not a secure connection
Hackers could try to steal your data from DOMAIN.de, for example passwords, messages or credit card data. 
NET::ERR_CERT_AUTHORITY_INVALID

I have already restarted the server.

Greetings.

**Comment by Vaalyn** [comment]
Have you seen any errors while executing the command?

Also what does your browser tell you about the invalid certificate?
Click on the warning in the URL bar and then on certificate and then look at the details. Is it a LE cert or self-signed?

**Comment by NurLutix** [comment]
Hey,
Look here: http://prntscr.com/ooos77

There was no mistake. The certificate was probably generated successfully.

**Comment by SlvrEagle23** [comment]
@NurLutix That's a self-signed certificate for localhost; it doesn't seem to have picked up the LetsEncrypt cert. You may need to restart Docker via `docker-compose down` and `docker-compose up -d` to have it take effect, but that's not normally the case.

**Comment by Vaalyn** [comment]
It's still serving the certificate self-signed by your AzuraCast installation.

If restarting AzuraCast doesn't work would you mind executing `./docker.sh letsencrypt-create DOMAIN.de` again and posting the output here?

**Comment by NurLutix** [comment]
Hey,
AzuraCast restarts, still the SSL error.

Here is the output of the command:
`IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/ac.germanstation.de/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/ac.germanstation.de/privkey.pem
   Your cert will expire on 2019-11-03. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

Domain name ac.GermanStation.de is not set up with LetsEncrypt yet. Reverting to self-signed cert...
Generating a 2048 bit RSA private key
..........+++++
............................+++++
writing new private key to '/etc/letsencrypt/selfsigned.key'
-----
Self-signed certificate restored.
`

Greetings.

**Comment by SlvrEagle23** [comment]
@NurLutix Ah, the domain name is being converted to lowercase by LetsEncrypt, which then means we're not picking up the proper path. You should use `letsencrypt-create lowercase-domain.example.com` and that should work.

**Comment by NurLutix** [comment]
Hey,
`IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: lowercase-domain.ac.germanstation.de
   Type:   connection
   Detail: dns :: DNS problem: NXDOMAIN looking up A for
   lowercase-domain.ac.germanstation.de
`

**Comment by SlvrEagle23** [comment]
@NurLutix No...I don't mean literally put the word "lowercase-domain" in front of your domain name, I mean specify your domain name IN lower case. It's the case-sensitivity that's throwing it off.

**Comment by NurLutix** [comment]
Works, thanks!
