### ISSUE TITLE
icecast 2.4 not working on Docker installation

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#182]
Hi, 

I successfully installed azuracast on a Ubuntu 16.04 VPS.
When I configure a radio with Icecast 2.4, as soon as I want to start the radio I get an error page.
When I switch the radio to shoutcast, no problem.

fXmlRpc\Exception\FaultException thrown with message "FAILED"

Stacktrace:
#23 fXmlRpc\Exception\FaultException in /var/azuracast/www/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Exception/FaultException.php:32
#22 fXmlRpc\Exception\FaultException:fault in /var/azuracast/www/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Parser/XmlReaderParser.php:373
#21 fXmlRpc\Parser\XmlReaderParser:parse in /var/azuracast/www/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Client.php:156
#20 fXmlRpc\Client:call in /var/azuracast/www/vendor/supervisorphp/supervisor/src/Connector/XmlRpc.php:45
#19 Supervisor\Connector\XmlRpc:call in /var/azuracast/www/vendor/supervisorphp/supervisor/src/Supervisor.php:110
#18 Supervisor\Supervisor:__call in /var/azuracast/www/app/src/AzuraCast/Radio/AdapterAbstract.php:128
#17 AzuraCast\Radio\AdapterAbstract:start in /var/azuracast/www/app/modules/stations/controllers/UtilController.php:21
#16 Controller\Stations\UtilController:restartAction in /var/azuracast/www/app/src/App/Mvc/Controller.php:100
#15 App\Mvc\Controller:dispatch in /var/azuracast/www/app/src/App/Mvc/Resolver.php:42
#14 App\Mvc\Resolver:App\Mvc\{closure} in /var/azuracast/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:41
#13 call_user_func in /var/azuracast/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:41
#12 Slim\Handlers\Strategies\RequestResponse:__invoke in /var/azuracast/www/vendor/slim/slim/Slim/Route.php:340
#11 Slim\Route:__invoke in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:122
#10 Slim\Route:callMiddlewareStack in /var/azuracast/www/vendor/slim/slim/Slim/Route.php:316
#9 Slim\Route:run in /var/azuracast/www/vendor/slim/slim/Slim/App.php:476
#8 Slim\App:__invoke in /var/azuracast/www/app/bootstrap/services.php:294
#7 Closure:{closure} in /var/azuracast/www/vendor/slim/slim/Slim/DeferredCallable.php:43
#6 call_user_func_array in /var/azuracast/www/vendor/slim/slim/Slim/DeferredCallable.php:43
#5 Slim\DeferredCallable:__invoke in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:73
#4 call_user_func in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:73
#3 Slim\App:Slim\{closure} in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:122
#2 Slim\App:callMiddlewareStack in /var/azuracast/www/vendor/slim/slim/Slim/App.php:370
#1 Slim\App:process in /var/azuracast/www/vendor/slim/slim/Slim/App.php:295
#0 Slim\App:run in /var/azuracast/www/web/index.php:9

**Comment by SlvrEagle23** [comment]
@griffon56 The latest push should fix it...give it about 10 minutes for Travis to rebuild the Docker images, then run the Docker update and that should fix everything.

**Comment by griffon56** [comment]
It now works great with icecast. You are doing a fantastic job !
