### ISSUE TITLE
no translation of these phrases

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#1821]
> Use WebSockets for Now Playing Updates
Use WebSockets for Now Playing Updates
Enables or disables the use of the newer and faster WebSocket-based system for receiving live updates on public players. You may need to disable this if you encounter problems with it.

**Comment by susl16c** [comment]
Connected AzuraRelays

**Comment by susl16c** [comment]
API keys can be used to access some system functionality without needing to log in. All of the keys you create share your permissions in the system. For more information, see the API documentation.

**Comment by SlvrEagle23** [comment]
@susl16c I was waiting on our large framework update to regenerate the locale strings. They're updated and the Russian translations are imported.
