### ISSUE TITLE
Station Profile Listeners

### ISSUE THREAD

**Issue by berkaygndzs** [AzuraCast/AzuraCast#1824]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 16.04
**Describe the bug**
Listener count on Station Profile with Shoutcast frontend should be swapped with Unique ones.

**Screenshots**
![Image Pasted at 2019-8-7 20-37](https://user-images.githubusercontent.com/20186439/62644854-c29cf080-b953-11e9-90f1-95b09ae20ce1.png)
![Image Pasted at 2019-8-7 20-36](https://user-images.githubusercontent.com/20186439/62644862-c6c90e00-b953-11e9-8cae-28354264af97.png)

**Comment by SlvrEagle23** [comment]
@berkaygndzs What frontend are you using? It looks like SHOUTcast. That may be the source of the problem, as we don't offer the best support for SHOUTcast (due to it being closed-source and proprietary, and hard for us to inspect and work with).

**Comment by berkaygndzs** [comment]
I'm using SHOUTcast, yes. The error was that unique and current listeners are different, meaning they should swap places.

**Comment by SlvrEagle23** [comment]
@berkaygndzs I can confirm that on our end, our SHOUTcast adapters are properly pulling the "unique" and "current" listener numbers as they're being reported from SHOUTcast. We don't know internally how they determine what a "unique" listener is, or if there are separate ways of tracking total/unique listeners, or if there's an error causing the software to misreport the numbers, but on our end it appears to be working fine.
