### ISSUE TITLE
Can't change the defualt port

### ISSUE THREAD

**Issue by xLivex** [AzuraCast/AzuraCast#1826]
**Using Docker installation method**

yes
**Host Operating System**

Ubuntu 16.04
--
Well i'm trying to change the default port to another but i can't?
i changed it from the .env file
but still i have this error
![image](https://user-images.githubusercontent.com/30420446/62710245-a6568d80-b9ff-11e9-94e7-00f5d202beef.png)

**Comment by SlvrEagle23** [comment]
@xLivex Are you trying to switch the port that AzuraCast's web server serves on to 8000? Port 8000 is already in use by the `stations` container of our same service, so you'll likely have to pick something out of the 8000-8999 range, i.e. 9000 instead.
