### ISSUE TITLE
Search field in the Media List not working

### ISSUE THREAD

**Issue by afonsosantos** [AzuraCast/AzuraCast#1828]
**Using Docker installation method**
Yes

**Commit Number**
#cd7c8e4

**Host Operating System**
Ubuntu Server 18.04

**Describe the bug**
When using the search field in the media list, after entering a search term, the song list updates and the result does not show up. No errors are displayed on the Chrome's console either.

**Screenshots**
![image](https://user-images.githubusercontent.com/46262740/62737337-7327f480-ba27-11e9-9170-b62f602a17d8.png)

**Device(s):**
 - Device: Windows 10 PC
 - Browser: Google Chrome

**Comment by SC2Mitch** [comment]
I'm on #2feeee1 and it happens for me

**Comment by Rafaelrds2017** [comment]
It doesn't work here either.

**Comment by SlvrEagle23** [comment]
@afonsosantos @SC2Mitch @Rafaelrds2017 I found the issue and fixed it in the latest commit. Wait about 5-10 minutes and then update your installations and the issue should be fixed.

**Comment by afonsosantos** [comment]
Working here again, thanks for the fix!
