### ISSUE TITLE
Requestable songs without being in regular rotation

### ISSUE THREAD

**Issue by adwinter** [AzuraCast/AzuraCast#1829]
Hey Team,

I'm hoping you guys know how to make the functionality I'm looking for work... 

I want to be able to have a list of songs that are available to be requested, but NOT scheduled to play otherwise. I thought I could keep the playlist disabled, but check "Requestable", and that would do it.. but apparently it doesn't work like that.. If its disabled, then that's it.

Any idea how to make this work?? I mean I guess I could write a cronjob to keep moving its schedule to tomorrow so it never gets to the time it plays, but that seems like a lot of work and resource intensive to do. LOL

Oh, and I also tried just leaving the track unassigned to a playlist, but it doesn't show up as requestable that way either. 

Any help would be awesome -- thanks guys!

Andrew

**Comment by afonsosantos** [comment]
You may want to move this Feature Request to the AzuraCast's Feature Request page [here](features.azuracast.com), so that the team can dedicate this space to issues.

Thanks

**Comment by adwinter** [comment]
I can do that.. but I wasn't sure its a "feature request", as I thought there might be a way to do it already is all. If its something that can't be done without adding it as a feature, I'd be happy to kick it over there. ;)

**Comment by SlvrEagle23** [comment]
@adwinter It's a fairly minor change, but you should probably add it to our featureupvote site, since it's quite possible that most users don't want disabled playlists showing up as requestable, so we may end up having to add a system-wide setting for whether they appear as requestable or not.

**Comment by adwinter** [comment]
@SlvrEagle23 I've added this to the feature request site. Thanks for your reply.

**Comment by adwinter** [comment]
Hey Guys,

I know this is closed, but if anyone is interested I found an apparent workaround to accomplish this. If you enable the playlist, set it to "custom" and then don't give it any instruction. Liquidsoap ignores it, but Azuracast recognizes the content as "requestable".  At least that's what I'm guessing happens.

If you see any potential problems, please let me know -- otherwise it seems to work! :)

Andrew

**Comment by SlvrEagle23** [comment]
@adwinter That should work just fine as well. The playlist will be ignored by everything in the system, but still be requestable. :)

**Comment by adwinter** [comment]
Sweet! I'll leave it up in the feature list -- you never know -- maybe others will vote for a more "pretty" solution in the future. LOL  Thanks so much for your help @SlvrEagle23.
