### ISSUE TITLE
Azuracast cache error when Docker_update

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#183]
Every time i run a docker update, I get the following non-blocking error :

TASK [azuracast-update : Clear AzuraCast Cache] *****************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php cache:clear", "delta": "0:00:00.944031", "end": "2017-07-11 22:41:57.379056", "failed": true, "rc": 255, "start": "2017-07-11 22:41:56.435025", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/var/azuracast/www/util/ansible/docker_update.retry

**Comment by SlvrEagle23** [comment]
@griffon56 To answer your question from the other thread, you'll want to edit the file `app/env.ini` (relative to the root of the AzuraCast code) and change the line that says `application_env=development` to `application_env=production`. That should fix some of the issues you're seeing.

As for the caching issues, would you mind running the update again with the latest code and pasting back the response you get from that? The cache flushing has changed quite a bit in the last few revisions and I want to make sure I have the latest issue to address.

**Comment by griffon56** [comment]
@SlvrEagle23 sorry, i found no env.ini file in my /docker/app/ folder or any other folder of my VPS. Or should I load a shell in a docker container first ? In addition, it shows 'Updating AzuraCast (Environment: production)' when running the update script.

Here is the latest error code after a docker_update.sh script, it looks like #194.

TASK [azuracast-update : Clear AzuraCast Cache] ********************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php cache:clear", "delta": "0:00:04.375692", "end": "2017-07-21 17:05:14.313736", "failed": true, "rc": 1, "start": "2017-07-21 17:05:09.938044", "stderr": "\n                            \n  [RedisException]          \n  read error on connection  \n                            \n\ncache:clear", "stderr_lines": ["", "                            ", "  [RedisException]          ", "  read error on connection  ", "                            ", "", "cache:clear"], "stdout": "Router cache file cleared.", "stdout_lines": ["Router cache file cleared."]}
        to retry, use: --limit @/var/azuracast/www/util/ansible/docker_update.retry

**Comment by griffon56** [comment]
The update script now updates successfully. The homepage still shows (development) environment , which i do not know how to modify with my docker installation.

**Comment by SlvrEagle23** [comment]
@griffon56 The env.ini file is within the AzuraCast code that you should have on the host machine, not the Docker code or volumes themselves.

If you don't have an env.ini file, you can try running:

```
docker run --rm cli azurcast_cli azuracast:config:migrate
```

That should create one, after which you can update it to indicate that the app is in production mode (if it's not already updated).

**Comment by griffon56** [comment]
It says :
Unable to find image 'cli:latest' locally
docker: Error response from daemon: repository cli not found: does not exist or no pull access.

**Comment by SlvrEagle23** [comment]
Sorry, I meant to say `docker-compose` instead of `docker`, at the doc root where AzuraCast is installed.

You can also just manually create the folder in `app/env.ini`. It looks like:

```ini
;
; AzuraCast Environment Settings
;
; This file is automatically generated by AzuraCast.
;
[configuration]
application_env = development
db_password = azuracast
```

**Comment by griffon56** [comment]
It worked when i created env.ini manually. Docker-compose command did not make the trick.
Many thanks
