### ISSUE TITLE
Im trying to Convert the Json Response into a raw html that i can display a html page

### ISSUE THREAD

**Issue by gothicdude1044** [AzuraCast/AzuraCast#1830]
Im trying to Convert the Json Response into a raw html that i can display a html page.

Do You Guys have a way to do that or Can provide a widget that will be able to be on an html for i dont need and Embedded player already have that just want station info to show up the on air DJ or Auto DJ & song info 
Basically uses the /nowplaying api response into html not just raw json.

**Comment by afonsosantos** [comment]
Hi!

You have some options, described in this [page](https://www.azuracast.com/developers/nowplaying.html). You can use them to build your widgets to then display in a HTML page.

**Comment by ErnestPH** [comment]
@gothicdude1044 You can reference this… similar to what you are asking

https://github.com/AzuraCast/AzuraCast/issues/1699

**Comment by Vaalyn** [comment]
I'm assuming that your website is already using the jQuery JavaScript library while writing this. If this is not the case please let me know.

So in general you want to add this block from the `For Developers` page about the Now Playing API to your sites JavaScript and modify it a bit to fill your HTML elements with the data from the API:
```
var nowPlayingTimeout;
var nowPlaying;

function loadNowPlaying() {
    $.ajax({
        cache: false,
        dataType: "json",
        url: 'http://your-azuracast-site.example.com/api/nowplaying/station_shortcode',
        success: function(np) {
            // Do something with the Now Playing data.
            nowPlaying = np;

            nowPlayingTimeout = setTimeout(loadNowPlaying, 15000);
        }
    }).fail(function() {
        nowPlayingTimeout = setTimeout(loadNowPlaying, 30000);
    });
}

$(function() {
    loadNowPlaying();
});
```

You'll need to change the `url` to the one of your installation:
```
url: 'http://your-azuracast-site.example.com/api/nowplaying/station_shortcode',
```

You see this part here?
```
// Do something with the Now Playing data.
nowPlaying = np;
```

Directly after that you can add the code that takes the data and shows it in your HTML elements. For example let's say you have a `div` with the id `nowplaying-song` which you want to show the currently playing song of your station. You'd add the following line to the JS:
```
$('#nowplaying-song').text(np.now_playing.song.text);
```

The JSON format is quite simple as it is basically just JavaScript objects. When you want to access a specific value of a JSON object you can access it by using `<json-object>.<field>.<sub-field>` if there is an array in there you can also use JS to loop over it via a foreach loop or access one specific entry directly via `<json-object>.<array>[<number>]`.

To know what fields you can use you can access the nowplaying API endpoint with your browser which will show you the raw JSON output. To make that a bit more readable you can use a browser plugin that automatically formats the JSON (I'm using [this one](https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa)).

**Comment by gothicdude1044** [comment]
To be honest im using phpbb3 plus phpbb site builder to make custom blocks that allow raw html their words not mine lol

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Vaalyn** [comment]
I think if it allows custom HTML you should also be able to add a `<script></script>` block that way to add the JS part.

**Comment by gothicdude1044** [comment]
@Vaalyn this the code ive got so far // JavaScript Document
var nowPlayingTimeout;
var nowPlaying;
var live;
var liveTimeout;

function loadNowPlaying() {
    $.ajax({
        cache: false,
        dataType: "json",
        url: 'http://darkphystgaming.com/api/nowplaying/1',
        success: function(np) {
            // Do something with the Now Playing data.
            nowPlaying = np;

            nowPlayingTimeout = setTimeout(loadNowPlaying, 15000);
        }
    }).fail(function() {
        nowPlayingTimeout = setTimeout(loadNowPlaying, 30000);
    });
}

$(function() {
    loadNowPlaying();
});
nowPlaying = np;
$('#nowplaying-song').text(np.now_playing.song.text);


function loadlive() {
    $.ajax({
        cache: false,
        dataType: "json",
        url: 'http://darkphystgaming.com/api/nowplaying/1',
        success: function(np) {
            // Do something with the live data.
            live = live;

            liveTimeout = setTimeout(loadlive, 15000);
        }
    }).fail(function() {
        liveTimeout = setTimeout(loadlive, 30000);
    });
}

$(function() {
    loadlive();
});
live = live;
$('#live-is_live').text(live.is_live); //true or false and if this is true display dj name
$('#live-streamer_name').text(live.streamer_name); //Show Streamer/dj name
and what song they are playing from nowplaying function 
if this is false then show the standard now playing info 

then displaying this into html elements

**Comment by Reaktiv4** [comment]
To display information in the site page, you need to add?

`<div id="nowplaying-song"></div>`

or something else?

It does not show me anything. Styles prescribed for div

**Comment by fidegr** [comment]
Hello,
I have been trying to get this function to work to show the Artist and song information in an html web, but I can't get it to work. Someone could help me?
