### ISSUE TITLE
Ansible | Update not working | E500

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1831]
Ansible-Installation on Ubuntu 18.04 LTS

After updating (./update), the webinterface is not reachable (Error 500). I tried ./update --full, but it doesn't help. After running it, following error is displayed:

TASK [ufw : UFW - Disable all other incoming by default] ****************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "commands": ["/usr/sbin/ufw status verbose", "/bin/grep -h '^### tuple' /lib/ufw/user.rules /lib/ufw/user6.rules /etc/ufw/user.rules /etc/ufw/user6.rules /var/lib/ufw/user.rules /var/lib/ufw/user6.rules", "/usr/sbin/ufw default deny incoming"], "msg": "ERROR: problem running ufw-init\niptables-restore: line 2 failed\nip6tables-restore: line 2 failed\n\n"}

php_errors.log:
[09-Aug-2019 06:58:15 UTC] PHP Fatal error:  Uncaught Error: Class 'Redis' not found in /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php:250
Stack trace:
#0 [internal function]: Azura\DefaultServicesProvider::Azura\{closure}(Object(Azura\Settings))
#1 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Object(Closure), Array)
#2 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call(Object(Closure), Array)
#3 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(64): DI\Definition\Resolver\FactoryResolver->resolve(Object(DI\Definition\FactoryDefinition), Array)
#4 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(380): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\FactoryDefinition), Array)
#5 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(197): DI\Container->resolveDefinition(Object(DI\Definition\FactoryDefinition), Array)
#6 /var/azuracast/www_tmp/CompiledConta in /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php on line 250

What's wrong?

**Comment by SlvrEagle23** [comment]
@MrSteelMiner Interesting that `./update.sh --full` didn't work...it's suggesting that you're missing the `php7.2-redis` package. Maybe manually try reinstalling it? 🤔

**Comment by MrSteelMiner** [comment]
installed it (don't know why it wasn't installed...), now (and after another ./update.sh --full) I get a "visual" error 500:
![image](https://user-images.githubusercontent.com/47743654/62821107-a2e21400-bb6f-11e9-8d45-89bf27df9d20.png)

**Comment by SlvrEagle23** [comment]
@MrSteelMiner Seems like the traditional install may not be flushing the temp cache properly. Try manually running `rm -rf /var/azuracast/www_tmp/*` and seeing if that helps.

**Comment by MrSteelMiner** [comment]
Many thanks! Now it works!
