### ISSUE TITLE
setting up time_display as on azuracast's public player page.

### ISSUE THREAD

**Issue by jbrunno** [AzuraCast/AzuraCast#1832]
Ola wanted help setting up time_display as on azuracast's public player page. with progress bar

**Comment by ErnestPH** [comment]
You can use [js analog clock](https://gist.github.com/ErnestPH/313442dffde0c4321fe32acc9988b02d) on your html?

**Comment by afonsosantos** [comment]
@jbrunno Are you trying to display the elapsed time of a song?

![image](https://user-images.githubusercontent.com/46262740/62780784-669aaf00-baae-11e9-8c4e-e9f8ecd97d8c.png)

**Comment by jbrunno** [comment]
@afonsosantos 
that's right friend

**Comment by afonsosantos** [comment]
You will need to use the API response and compare the timestamps. I've never done that, so I'm afraid I can't help you.

**Comment by SlvrEagle23** [comment]
@jbrunno Here's [how we do it in Vue](https://github.com/AzuraCast/AzuraCast/blob/master/web/static/vue/radio_player.vue#L22-L34). Basically, there is a value in the `now_playing` response called `played_at` which is the UNIX timestamp that the song started playing. You can calculate the time elapsed using something like:

```javascript
let current_time = Math.floor(Date.now() / 1000);
let np_elapsed = current_time - np.now_playing.played_at;
```
