### ISSUE TITLE
Redirect to the port: 80

### ISSUE THREAD

**Issue by Takumi86ES** [AzuraCast/AzuraCast#1833]
I have updated to the latest version and now when I put my domain it doesn't work because it redirects to domain.com:80

**Comment by SlvrEagle23** [comment]
@Takumi86ES This is a known issue that should be fixed as of the very latest update within the last two days.

**Comment by CodeSteele** [comment]
This has been fixed.

**Comment by ErnestPH** [comment]
welcome back @CodeSteele it's been awhile :)
