### ISSUE TITLE
Info Error Now Playing

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#1834]
Info Playing now, not updating. It is in a single song and does not change.

**Self-Hosted Installation - NYC3 - Ubuntu 18.04 x64**

![image](https://user-images.githubusercontent.com/31827151/62786101-5081f400-ba98-11e9-8334-6b8f61f3f97b.png)

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 We've been getting a lot of reports about this. It seems that there are several common causes, like a DJ being connected or the installation being out of date. Try updating your installation to the latest version, which will also restart the stack, and see if that helps.

**Comment by Rafaelrds2017** [comment]
> @ Rafaelrds2017 Temos recebido muitos relatórios sobre isso. Parece que há várias causas comuns, como um DJ sendo conectado ou a instalação desatualizada. Tente atualizar sua instalação para a versão mais recente, que também reiniciará a pilha e verá se isso ajuda.


Is this the recent update? ::
AzuraCast • v0.9.6, #ba0b4f6 (2019-08-08 16:15) • Docker • PHP 7.2

I Updated Today at dawn!

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 Can you link the public player of your installation, or send it to me via direct message on our [Mattermost chat](https://chat.azuracast.com/)? I can't really do much to diagnose it from here otherwise.

**Comment by afonsosantos** [comment]
@Rafaelrds2017 Hi!

If the issue is still valid, please head over to our [Slack channel](https://azuracast.com/slack), instead of the Mattermost server.

**Comment by Rafaelrds2017** [comment]
I'm already there ...

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Afonso Santos <notifications@github.com>
Enviado: Tuesday, August 20, 2019 5:11:15 PM
Para: AzuraCast/AzuraCast <AzuraCast@noreply.github.com>
Cc: Rafael Rodrigues <rafael_15silva@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [AzuraCast/AzuraCast] Info Error Now Playing (#1834)


@Rafaelrds2017<https://github.com/Rafaelrds2017> Hi!

If the issue is still valid, please head over to our Slack channel<https://azuracast.com/slack>, instead of the Mattermost server.

**Comment by afonsosantos** [comment]
@Rafaelrds2017 Please, re-send the details that @SlvrEagle23 asked, now on our Slack channel.

Thanks

**Comment by Rafaelrds2017** [comment]
Later I send, now I have no computer.

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Afonso Santos <notifications@github.com>
Enviado: Wednesday, August 21, 2019 10:40:16 AM
Para: AzuraCast/AzuraCast <AzuraCast@noreply.github.com>
Cc: Rafael Rodrigues <rafael_15silva@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [AzuraCast/AzuraCast] Info Error Now Playing (#1834)


@Rafaelrds2017<https://github.com/Rafaelrds2017> Please, re-send the details that @SlvrEagle23<https://github.com/SlvrEagle23> asked, now on our Slack channel.

Thanks
