### ISSUE TITLE
Only error 500

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#1835]
I use Traditional Install

After a Update i only get
500
Station not found.
RequireStation.php : 27

I already tried to restart the server.

**Comment by preterive** [comment]
Openvz with Ubuntu 16.04

**Comment by preterive** [comment]
I uncommented this and no i get:
![image](https://user-images.githubusercontent.com/31483348/62822441-df1f6f80-bb83-11e9-82cb-f17a3ab868a9.png)

**Comment by preterive** [comment]
2019/08/10 05:28:09 [error] 30641#30641: *24669 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Azura\AppFactory' not found in /var/azuracast/www/src/AppFactory.php on line 12" while reading response header from upstream, client: 162.158.114.103, server: localhost, request: "GET /api/nowplaying HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api2.alles-radio-web.de"
2019/08/10 05:28:14 [error] 30642#30642: *24638 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Azura\AppFactory' not found in /var/azuracast/www/src/AppFactory.php on line 12" while reading response header from upstream, client: 92.116.46.236, server: server2.alles-radio-web.de, request: "GET /api/nowplaying/2?_=1565429217164 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "server2.alles-radio-web.de", referrer: "https://server2.alles-radio-web.de/station/2/profile"
2019/08/10 05:28:19 [error] 30642#30642: *24638 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Azura\AppFactory' not found in /var/azuracast/www/src/AppFactory.php on line 12" while reading response header from upstream, client: 92.116.46.236, server: server2.alles-radio-web.de, request: "GET /api/station/2/status?_=1565429217165 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "server2.alles-radio-web.de", referrer: "https://server2.alles-radio-web.de/station/2/profile"
2019/08/10 05:28:20 [error] 30642#30642: *24590 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Azura\AppFactory' not found in /var/azuracast/www/src/AppFactory.php on line 12" while reading response header from upstream, client: 162.158.114.103, server: localhost, request: "GET /api/nowplaying HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api2.alles-radio-web.de"

**Comment by pilovali** [comment]
You use the old non Docker installer? I get the same error.
I'm going to replace my backup and figure it out again later.

**Comment by preterive** [comment]
Yes, I use the old non docker installer. I still use openvz for the radio...
Is there a complete automatic backup from acuracast in /var/azuracast/Backup?

**Comment by pilovali** [comment]
https://github.com/AzuraCast/AzuraCast/issues/1831
Looks like someone else got this issue as well. I guess it's only with non-docker installations.

I have no idea about the backup in /var/azuracast/Backup, I just created a backup from my VM before upgrading.

**Comment by preterive** [comment]
Yes, a backup is a good idea...
I already also tried ./update.sh --full .

**Comment by preterive** [comment]
i already found Redis in the phpinfo file.

**Comment by SlvrEagle23** [comment]
@preterive What version of AzuraCast are you running right now?

**Comment by SlvrEagle23** [comment]
@preterive If you're on the Traditional installation (which it appears you are), try running `rm -rf /var/azuracast/www_tmp/*`

**Comment by preterive** [comment]
Really thanks, that was the right fix!!

I worked on that think from 14 to 2 o'clock and I don't found a solution.

Really thanks!!
