### ISSUE TITLE
Playlist Enable/Disable

### ISSUE THREAD

**Issue by fafafoya** [AzuraCast/AzuraCast#1837]
Trying to disable/enable a playlist with Remote URL, I get a blank page and nothing happens.

**Comment by fafafoya** [comment]
More info:
After disabling/enabling a playlist, I am redirected to below page which is blank and I need to clickn on back button on browser.
http://myradiostation.ext/station/1/playlists/toggle/10

**Comment by SlvrEagle23** [comment]
@fafafoya This is fixed as of the latest commit. Thank you for letting us know!
