### ISSUE TITLE
Report "Duplicate Songs" shows 500 error

### ISSUE THREAD

**Issue by yarik2720** [AzuraCast/AzuraCast#1839]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu Server 16.04

**Describe the bug**
Opening reports "Duplicate Songs" shows 500 error

**To Reproduce**
1. Go to Reports
2. Click on Duplicate Songs

**Expected behavior**
I expected to see list of duplicated songs

**Relevant Logs**
```
web_1       | Aug 11 11:11:42 bcd3617aef19 php-fpm[58]: [WARNING] [pool www] child 1563 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/azuracast/www/src/Controller/Stations/Reports/DuplicatesController.php on line 66"
web_1       | 2019/08/11 11:11:42 [error] 62#62: *328 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/azuracast/www/src/Controller/Stations/Reports/DuplicatesController.php on line 66" while reading response header from upstream, client: 192.168.64.1, server: localhost, request: "GET /station/1/reports/duplicates HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "cast.noisefm.ru", referrer: "http://cast.noisefm.ru/station/1/automation"
```

**Screenshots**
![chrome_2019-08-11_14-12-25](https://user-images.githubusercontent.com/1839978/71410341-edaf8480-2655-11ea-8808-9f59fed23428.png)

**Comment by SlvrEagle23** [comment]
@yarik2720 How many tracks do you have on your music library?

**Comment by yarik2720** [comment]
4388 files in media folder with subfolders

**Comment by yarik2720** [comment]
After I extended max execution time I see, that all podcasts are marked as dublicates, for example:
![firefox_2019-10-12_21-51-46](https://user-images.githubusercontent.com/1839978/66706392-94b09f80-ed3a-11e9-98f4-9dd2f696bff4.png)

**Comment by yarik2720** [comment]
Also, some files are repeated on report several times:
for example: `monstercat podcast/unknown-Monstercat Podcast Ep. 151-320kbps.mp3` - 11 times

**Comment by SlvrEagle23** [comment]
@yarik2720 Yeah, the duplicates check is not looking for exact matches, it's looking for very close matches that may be duplicates (or may not be). This results in things like podcast episodes, whose only character differences are the episode number, showing up as duplicates.

**Comment by radiolize** [comment]
Hi guys

Some stations shows same error at me too. What can I do to see that page?
