### ISSUE TITLE
Azuracast won't install

### ISSUE THREAD

**Issue by JJK1231** [AzuraCast/AzuraCast#1842]
Hi my Azuracast won't install. I run on Ubuntu 18.04.3 on a Raspberry 3b+. This is the log, and the error:

ubuntu@ubuntu: ~ $ sudo apt-get update 
Hit:1 http://ppa.launchpad.net/ansible/ansible/ubuntu bionic InRelease
Hit:2 http://ppa.launchpad.net/avsm/ppa/ubuntu bionic InRelease                                     
Hit:3 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease                                                                                                                                     
Hit:4 https://repos.influxdata.com/ubuntu bionic InRelease                                                                                                                                            
Hit:5 http://ports.ubuntu.com/ubuntu-ports bionic InRelease                                                                                                     
Hit:6 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease                                         
Hit:7 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease      
Hit:8 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease       
Hit:9 http://ams2.mirrors.digitalocean.com/mariadb/repo/10.2/ubuntu bionic InRelease
Reading package lists... Done                                              
ubuntu@ubuntu:~ $ sudo apt-get install -q -y git 
Reading package lists...
Building dependency tree...
Reading state information...
git is already the newest version (1:2.17.1-1ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.
ubuntu@ubuntu:~ $  
ubuntu@ubuntu:~ $ sudo mkdir -p /var/azuracast/www 
ubuntu@ubuntu:~ $ cd /var/azuracast/www 
ubuntu@ubuntu:/var/azuracast/www$ sudo git clone https://github.com/AzuraCast/AzuraCast.git . 
fatal: destination path '.' already exists and is not an empty directory.
ubuntu@ubuntu:/var/azuracast/www$  
ubuntu@ubuntu:/var/azuracast/www$ sudo chmod a+x install.sh 
ubuntu@ubuntu:/var/azuracast/www$ ./install.sh
Use Docker installation method? (Recommended) [Y/n] n
Checking for Ansible: install ok installed
Installing AzuraCast (Environment: production)

PLAY [all] ********************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************
ok: [localhost]

TASK [init : debug] ***********************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Running Ansible on localhost with OS Ubuntu bionic 18.04 aarch64 (production)"
}

TASK [init : fail] ************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [init : fail] ************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [init : Add multiverse repository] ***************************************************************************************************************************************************************
skipping: [localhost] => (item=deb http://archive.ubuntu.com/ubuntu bionic multiverse) 
skipping: [localhost] => (item=deb-src http://archive.ubuntu.com/ubuntu/  bionic multiverse) 
skipping: [localhost] => (item=deb http://archive.ubuntu.com/ubuntu bionic-updates multiverse) 
skipping: [localhost] => (item=deb-src http://archive.ubuntu.com/ubuntu/  bionic-updates multiverse) 

TASK [init : Update apt] ******************************************************************************************************************************************************************************
 [WARNING]: Could not find aptitude. Using apt-get instead

changed: [localhost]

TASK [init : Install system packages] *****************************************************************************************************************************************************************
ok: [localhost]

TASK [init : Install software-properties (18.04 only)] ************************************************************************************************************************************************
ok: [localhost]

TASK [init : Install python-software-properties (16.04 only)] *****************************************************************************************************************************************
skipping: [localhost]

TASK [init : Update pip components] *******************************************************************************************************************************************************************
ok: [localhost]

TASK [azuracast-user : Generate AzuraCast Password] ***************************************************************************************************************************************************
changed: [localhost]

TASK [azuracast-user : Create Groups] *****************************************************************************************************************************************************************
ok: [localhost] => (item=www-data)
ok: [localhost] => (item=admin)

TASK [azuracast-user : Create AzuraCast User] *********************************************************************************************************************************************************
changed: [localhost]

TASK [azuracast-user : Modify www-data User] **********************************************************************************************************************************************************
ok: [localhost]

TASK [azuracast-config : Write environment configuration file] ****************************************************************************************************************************************
ok: [localhost]

TASK [azuracast-config : Set up environment file] *****************************************************************************************************************************************************
ok: [localhost]

TASK [azuracast-config : Set Permissions on Base App Folder] ******************************************************************************************************************************************
ok: [localhost] => (item=/var/azuracast)

TASK [azuracast-config : Clear temp directory] ********************************************************************************************************************************************************
changed: [localhost]

TASK [azuracast-config : Create System Folders] *******************************************************************************************************************************************************
changed: [localhost] => (item=/var/azuracast/www_tmp)
changed: [localhost] => (item=/var/azuracast/www_tmp/proxies)
ok: [localhost] => (item=/var/azuracast/stations)
ok: [localhost] => (item=/var/azuracast/geoip)
ok: [localhost] => (item=/var/azuracast/backups)
ok: [localhost] => (item=/var/azuracast/servers)
ok: [localhost] => (item=/var/azuracast/servers/shoutcast2)
changed: [localhost] => (item=/var/azuracast/servers/icecast2)

TASK [azuracast-radio : Install IceCast-KH-AC Dependencies] *******************************************************************************************************************************************
ok: [localhost]

TASK [azuracast-radio : Download IceCast-KH-AC Source] ************************************************************************************************************************************************
ok: [localhost]

TASK [azuracast-radio : Extract IceCast-KH-AC Source] *************************************************************************************************************************************************
changed: [localhost]

TASK [azuracast-radio : Build IceCast-KH-AC] **********************************************************************************************************************************************************
changed: [localhost]

TASK [azuracast-radio : Clear OPAM directory] *********************************************************************************************************************************************************
changed: [localhost]

TASK [azuracast-radio : Add OPAM/OCaml Repository] ****************************************************************************************************************************************************
ok: [localhost]

TASK [azuracast-radio : Install Liquidsoap Dependencies] **********************************************************************************************************************************************
ok: [localhost]

TASK [azuracast-radio : Initialize OPAM (Xenial) - This takes a while...] *****************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Initialize OPAM (Bionic)] *****************************************************************************************************************************************************
changed: [localhost]

TASK [azuracast-radio : Build and Install Liquidsoap] *************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "opam install -y samplerate.0.1.4 taglib.0.3.3 mad.0.4.5 faad.0.4.0 fdkaac.0.2.1 lame.0.3.3 vorbis.0.7.1 cry.0.6.1 flac.0.1.4 opus.0.1.2 duppy.0.8.0 ssl liquidsoap.1.3.7", "delta": "0:02:45.590676", "end": "2019-08-12 06:47:36.578014", "msg": "non-zero return code", "rc": 31, "start": "2019-08-12 06:44:50.987338", "stderr": "[ERROR] The compilation of dune failed at \"/usr/bin/ocaml bootstrap.ml\".\n\n#=== ERROR while compiling dune.1.11.1 ========================================#\n# context              2.0.4 | linux/arm64 | ocaml-system.4.05.0 | https://opam.ocaml.org#c17c365b\n# path                 ~/.opam/default/.opam-switch/build/dune.1.11.1\n# command              /usr/bin/ocaml bootstrap.ml\n# exit-code            2\n# env-file             ~/.opam/log/dune-11133-900113.env\n# output-file          ~/.opam/log/dune-11133-900113.out\n### output ###\n# [...]\n# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/stdune/caml/dune_caml.ml > boot-depends.txt\n# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/dune_lang/dune_lang.mli src/dune_lang/dune_lang.ml src/dune_lang/atom.mli src/dune_lang/atom.ml src/dune_lang/combinators.ml src/dune_lang/dune_lexer.mli src/dune_lang/dune_lexer.ml src/dune_lang/escape.mli src/dune_lang/escape.ml src/dune_lang/file_syntax.mli src/dune_lang/file_syntax.ml src/dune_lang/jbuild_lexer.mli src/dune_[...]\n# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/stdune/result/dune_result.ml src/stdune/result/result.mli src/stdune/result/result.ml src/stdune/result/result_compat.ml > boot-depends.txt\n# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/fiber/fiber.mli src/fiber/fiber.ml > boot-depends.txt\n# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' vendor/incremental-cycles/src/incremental_cycles.mli vendor/incremental-cycles/src/incremental_cycles.ml vendor/incremental-cycles/src/incremental_cycles_intf.ml > boot-depends.txt\n# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/memo/memo.mli src/memo/memo.ml src/memo/implicit_output.mli src/memo/implicit_output.ml > boot-depends.txt\n# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/ocaml-config/ocaml_config.mli src/ocaml-config/ocaml_config.ml > boot-depends.txt\n# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/stdune/stdune.ml src/stdune/ansi_color.mli src/stdune/ansi_color.ml src/stdune/appendable_list.mli src/stdune/appendable_list.ml src/stdune/array.ml src/stdune/bin.mli src/stdune/bin.ml src/stdune/bool.mli src/stdune/bool.ml src/stdune/bytes.mli src/stdune/bytes.ml src/stdune/char.ml src/stdune/code_error.mli src/stdune/code_err[...]\n# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/wp/wp.mli src/wp/wp.boot.ml > boot-depends.txt\n# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/xdg/xdg.mli src/xdg/xdg.ml > boot-depends.txt\n# /usr/bin/ocamlc.opt -g -w -40 -o boot.exe -pp './boot-pp.exe -dump-ast' -I +threads unix.cma threads.cma boot.ml\n# Fatal error: exception Out of memory\n\n\nThe former state can be restored with:\n    opam switch import \"/var/azuracast/.opam/default/.opam-switch/backup/state-20190812064451.export\"", "stderr_lines": ["[ERROR] The compilation of dune failed at \"/usr/bin/ocaml bootstrap.ml\".", "", "#=== ERROR while compiling dune.1.11.1 ========================================#", "# context              2.0.4 | linux/arm64 | ocaml-system.4.05.0 | https://opam.ocaml.org#c17c365b", "# path                 ~/.opam/default/.opam-switch/build/dune.1.11.1", "# command              /usr/bin/ocaml bootstrap.ml", "# exit-code            2", "# env-file             ~/.opam/log/dune-11133-900113.env", "# output-file          ~/.opam/log/dune-11133-900113.out", "### output ###", "# [...]", "# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/stdune/caml/dune_caml.ml > boot-depends.txt", "# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/dune_lang/dune_lang.mli src/dune_lang/dune_lang.ml src/dune_lang/atom.mli src/dune_lang/atom.ml src/dune_lang/combinators.ml src/dune_lang/dune_lexer.mli src/dune_lang/dune_lexer.ml src/dune_lang/escape.mli src/dune_lang/escape.ml src/dune_lang/file_syntax.mli src/dune_lang/file_syntax.ml src/dune_lang/jbuild_lexer.mli src/dune_[...]", "# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/stdune/result/dune_result.ml src/stdune/result/result.mli src/stdune/result/result.ml src/stdune/result/result_compat.ml > boot-depends.txt", "# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/fiber/fiber.mli src/fiber/fiber.ml > boot-depends.txt", "# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' vendor/incremental-cycles/src/incremental_cycles.mli vendor/incremental-cycles/src/incremental_cycles.ml vendor/incremental-cycles/src/incremental_cycles_intf.ml > boot-depends.txt", "# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/memo/memo.mli src/memo/memo.ml src/memo/implicit_output.mli src/memo/implicit_output.ml > boot-depends.txt", "# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/ocaml-config/ocaml_config.mli src/ocaml-config/ocaml_config.ml > boot-depends.txt", "# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/stdune/stdune.ml src/stdune/ansi_color.mli src/stdune/ansi_color.ml src/stdune/appendable_list.mli src/stdune/appendable_list.ml src/stdune/array.ml src/stdune/bin.mli src/stdune/bin.ml src/stdune/bool.mli src/stdune/bool.ml src/stdune/bytes.mli src/stdune/bytes.ml src/stdune/char.ml src/stdune/code_error.mli src/stdune/code_err[...]", "# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/wp/wp.mli src/wp/wp.boot.ml > boot-depends.txt", "# /usr/bin/ocamldep.opt -modules -pp './boot-pp.exe -dump-ast' src/xdg/xdg.mli src/xdg/xdg.ml > boot-depends.txt", "# /usr/bin/ocamlc.opt -g -w -40 -o boot.exe -pp './boot-pp.exe -dump-ast' -I +threads unix.cma threads.cma boot.ml", "# Fatal error: exception Out of memory", "", "", "The former state can be restored with:", "    opam switch import \"/var/azuracast/.opam/default/.opam-switch/backup/state-20190812064451.export\""], "stdout": "The following actions will be performed:\n  ∗ install conf-m4         1          [required by ocamlfind]\n  ∗ install dune            1.11.1     [required by ssl]\n  ∗ install conf-pkg-config 1.1        [required by taglib]\n  ∗ install ocamlfind       1.8.1      [required by taglib, opus, liquidsoap, etc.]\n  ∗ install sexplib0        v0.12.0    [required by base]\n  ∗ install jbuilder        transition [required by camomile]\n  ∗ install conf-openssl    1          [required by ssl]\n  ∗ install conf-libpcre    1          [required by pcre]\n  ∗ install taglib          0.3.3\n  ∗ install samplerate      0.1.4\n  ∗ install ogg             0.5.2      [required by opus, flac, liquidsoap, vorbis]\n  ∗ install mad             0.4.5\n  ∗ install lame            0.3.3\n  ∗ install fdkaac          0.2.1\n  ∗ install dtools          0.4.1      [required by liquidsoap]\n  ∗ install base-bytes      base       [required by faad]\n  ∗ install base            v0.12.2    [required by pcre]\n  ∗ install camomile        1.0.1      [required by liquidsoap]\n  ∗ install ssl             0.5.9\n  ∗ install vorbis          0.7.1\n  ∗ install opus            0.1.2\n  ∗ install flac            0.1.4\n  ∗ install mm              0.4.1      [required by liquidsoap]\n  ∗ install faad            0.4.0\n  ∗ install pcre            7.4.1      [required by duppy, liquidsoap]\n  ∗ install cry             0.6.1\n  ∗ install duppy           0.8.0\n  ∗ install liquidsoap      1.3.7\n===== ∗ 28 =====\n\n<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>\n[cry.0.6.1] downloaded from cache at https://opam.ocaml.org/cache\n[base.v0.12.2] downloaded from cache at https://opam.ocaml.org/cache\n[dtools.0.4.1] downloaded from cache at https://opam.ocaml.org/cache\n[camomile.1.0.1] downloaded from cache at https://opam.ocaml.org/cache\n[dune.1.11.1] downloaded from cache at https://opam.ocaml.org/cache\n[duppy.0.8.0] downloaded from cache at https://opam.ocaml.org/cache\n[faad.0.4.0] downloaded from cache at https://opam.ocaml.org/cache\n[fdkaac.0.2.1] downloaded from cache at https://opam.ocaml.org/cache\n[flac.0.1.4] downloaded from cache at https://opam.ocaml.org/cache\n[lame.0.3.3] downloaded from cache at https://opam.ocaml.org/cache\n[mad.0.4.5] downloaded from cache at https://opam.ocaml.org/cache\n[liquidsoap.1.3.7] downloaded from cache at https://opam.ocaml.org/cache\n[mm.0.4.1] downloaded from cache at https://opam.ocaml.org/cache\n[ocamlfind.1.8.1] downloaded from cache at https://opam.ocaml.org/cache\n[ogg.0.5.2] downloaded from cache at https://opam.ocaml.org/cache\n[pcre.7.4.1] downloaded from cache at https://opam.ocaml.org/cache\n[opus.0.1.2] downloaded from cache at https://opam.ocaml.org/cache\n[sexplib0.v0.12.0] downloaded from cache at https://opam.ocaml.org/cache\n[samplerate.0.1.4] downloaded from cache at https://opam.ocaml.org/cache\n[ssl.0.5.9] downloaded from cache at https://opam.ocaml.org/cache\n[taglib.0.3.3] downloaded from cache at https://opam.ocaml.org/cache\n[vorbis.0.7.1] downloaded from cache at https://opam.ocaml.org/cache\n\n<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>\n∗ installed conf-m4.1\n∗ installed conf-pkg-config.1.1\n∗ installed conf-libpcre.1\n∗ installed conf-openssl.1\n∗ installed ocamlfind.1.8.1\n∗ installed base-bytes.base\n∗ installed dtools.0.4.1\n∗ installed fdkaac.0.2.1\n∗ installed lame.0.3.3\n∗ installed mad.0.4.5\n∗ installed ogg.0.5.2\n∗ installed faad.0.4.0\n∗ installed flac.0.1.4\n∗ installed opus.0.1.2\n∗ installed samplerate.0.1.4\n∗ installed taglib.0.3.3\n∗ installed vorbis.0.7.1\n∗ installed mm.0.4.1\n\n\n<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>\n┌─ The following actions failed\n│ λ build dune 1.11.1\n└─ \n┌─ The following changes have been performed (the rest was aborted)\n│ ∗ install base-bytes      base\n│ ∗ install conf-libpcre    1\n│ ∗ install conf-m4         1\n│ ∗ install conf-openssl    1\n│ ∗ install conf-pkg-config 1.1\n│ ∗ install dtools          0.4.1\n│ ∗ install faad            0.4.0\n│ ∗ install fdkaac          0.2.1\n│ ∗ install flac            0.1.4\n│ ∗ install lame            0.3.3\n│ ∗ install mad             0.4.5\n│ ∗ install mm              0.4.1\n│ ∗ install ocamlfind       1.8.1\n│ ∗ install ogg             0.5.2\n│ ∗ install opus            0.1.2\n│ ∗ install samplerate      0.1.4\n│ ∗ install taglib          0.3.3\n│ ∗ install vorbis          0.7.1\n└─ \n# Run eval $(opam env) to update the current shell environment", "stdout_lines": ["The following actions will be performed:", "  ∗ install conf-m4         1          [required by ocamlfind]", "  ∗ install dune            1.11.1     [required by ssl]", "  ∗ install conf-pkg-config 1.1        [required by taglib]", "  ∗ install ocamlfind       1.8.1      [required by taglib, opus, liquidsoap, etc.]", "  ∗ install sexplib0        v0.12.0    [required by base]", "  ∗ install jbuilder        transition [required by camomile]", "  ∗ install conf-openssl    1          [required by ssl]", "  ∗ install conf-libpcre    1          [required by pcre]", "  ∗ install taglib          0.3.3", "  ∗ install samplerate      0.1.4", "  ∗ install ogg             0.5.2      [required by opus, flac, liquidsoap, vorbis]", "  ∗ install mad             0.4.5", "  ∗ install lame            0.3.3", "  ∗ install fdkaac          0.2.1", "  ∗ install dtools          0.4.1      [required by liquidsoap]", "  ∗ install base-bytes      base       [required by faad]", "  ∗ install base            v0.12.2    [required by pcre]", "  ∗ install camomile        1.0.1      [required by liquidsoap]", "  ∗ install ssl             0.5.9", "  ∗ install vorbis          0.7.1", "  ∗ install opus            0.1.2", "  ∗ install flac            0.1.4", "  ∗ install mm              0.4.1      [required by liquidsoap]", "  ∗ install faad            0.4.0", "  ∗ install pcre            7.4.1      [required by duppy, liquidsoap]", "  ∗ install cry             0.6.1", "  ∗ install duppy           0.8.0", "  ∗ install liquidsoap      1.3.7", "===== ∗ 28 =====", "", "<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>", "[cry.0.6.1] downloaded from cache at https://opam.ocaml.org/cache", "[base.v0.12.2] downloaded from cache at https://opam.ocaml.org/cache", "[dtools.0.4.1] downloaded from cache at https://opam.ocaml.org/cache", "[camomile.1.0.1] downloaded from cache at https://opam.ocaml.org/cache", "[dune.1.11.1] downloaded from cache at https://opam.ocaml.org/cache", "[duppy.0.8.0] downloaded from cache at https://opam.ocaml.org/cache", "[faad.0.4.0] downloaded from cache at https://opam.ocaml.org/cache", "[fdkaac.0.2.1] downloaded from cache at https://opam.ocaml.org/cache", "[flac.0.1.4] downloaded from cache at https://opam.ocaml.org/cache", "[lame.0.3.3] downloaded from cache at https://opam.ocaml.org/cache", "[mad.0.4.5] downloaded from cache at https://opam.ocaml.org/cache", "[liquidsoap.1.3.7] downloaded from cache at https://opam.ocaml.org/cache", "[mm.0.4.1] downloaded from cache at https://opam.ocaml.org/cache", "[ocamlfind.1.8.1] downloaded from cache at https://opam.ocaml.org/cache", "[ogg.0.5.2] downloaded from cache at https://opam.ocaml.org/cache", "[pcre.7.4.1] downloaded from cache at https://opam.ocaml.org/cache", "[opus.0.1.2] downloaded from cache at https://opam.ocaml.org/cache", "[sexplib0.v0.12.0] downloaded from cache at https://opam.ocaml.org/cache", "[samplerate.0.1.4] downloaded from cache at https://opam.ocaml.org/cache", "[ssl.0.5.9] downloaded from cache at https://opam.ocaml.org/cache", "[taglib.0.3.3] downloaded from cache at https://opam.ocaml.org/cache", "[vorbis.0.7.1] downloaded from cache at https://opam.ocaml.org/cache", "", "<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>", "∗ installed conf-m4.1", "∗ installed conf-pkg-config.1.1", "∗ installed conf-libpcre.1", "∗ installed conf-openssl.1", "∗ installed ocamlfind.1.8.1", "∗ installed base-bytes.base", "∗ installed dtools.0.4.1", "∗ installed fdkaac.0.2.1", "∗ installed lame.0.3.3", "∗ installed mad.0.4.5", "∗ installed ogg.0.5.2", "∗ installed faad.0.4.0", "∗ installed flac.0.1.4", "∗ installed opus.0.1.2", "∗ installed samplerate.0.1.4", "∗ installed taglib.0.3.3", "∗ installed vorbis.0.7.1", "∗ installed mm.0.4.1", "", "", "<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>", "┌─ The following actions failed", "│ λ build dune 1.11.1", "└─ ", "┌─ The following changes have been performed (the rest was aborted)", "│ ∗ install base-bytes      base", "│ ∗ install conf-libpcre    1", "│ ∗ install conf-m4         1", "│ ∗ install conf-openssl    1", "│ ∗ install conf-pkg-config 1.1", "│ ∗ install dtools          0.4.1", "│ ∗ install faad            0.4.0", "│ ∗ install fdkaac          0.2.1", "│ ∗ install flac            0.1.4", "│ ∗ install lame            0.3.3", "│ ∗ install mad             0.4.5", "│ ∗ install mm              0.4.1", "│ ∗ install ocamlfind       1.8.1", "│ ∗ install ogg             0.5.2", "│ ∗ install opus            0.1.2", "│ ∗ install samplerate      0.1.4", "│ ∗ install taglib          0.3.3", "│ ∗ install vorbis          0.7.1", "└─ ", "# Run eval $(opam env) to update the current shell environment"]}

RUNNING HANDLER [azuracast-user : send user notification] *********************************************************************************************************************************************

PLAY RECAP ********************************************************************************************************************************************************************************************
localhost                  : ok=23   changed=9    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0

**Comment by yehoudatech** [comment]
I've got the same error 😫
