### ISSUE TITLE
Restart to Apply Changes

### ISSUE THREAD

**Issue by fafafoya** [AzuraCast/AzuraCast#1843]
After update to the latest commit and while just toggling between menus, the Restart to Apply Changes option appears without any reason.

**Comment by fafafoya** [comment]
To reproduce the bug, just browse to Playlists menu and stop there for a while then browse to Profile.
You will see Restart to Apply Changes!

**Comment by fafafoya** [comment]
If you don't restart the station, Now Playing will stop updating on Profile/On the Air.

**Comment by StringSurfer** [comment]
Same thing here. No matter where I go on the pages, and no matter how many times I restart to apply changes, it still says, restart to apply changes.. Maybe a bug has slipped in?

**Comment by SC2Mitch** [comment]
Confirming on our machine, ubuntt 18.4

**Comment by SlvrEagle23** [comment]
Oh wow, this one's my bad.

I have a DB listener that flags a station for restart if anything changes on a mount, remote relay, or playlist. Since I started logging unique/total listeners on mount points, those count as DB updates. So, basically, the station constantly gets flagged for restart.

Looking into how to fix that now. :D

**Comment by Inuyashagcn** [comment]
I have the same message my instalation is:
v0.9.6, #1222544 (2019-08-12 5:03) • Ansible (Ubuntu 18.04 Server)

**Comment by SlvrEagle23** [comment]
@Inuyashagcn This should be fixed as of the latest update, released about an hour ago. Update your installations and let me know if the issue persists.

**Comment by Inuyashagcn** [comment]
Well... I already updated but the issue persists

**Comment by SlvrEagle23** [comment]
@Inuyashagcn Changing mount points, remote relays, or some playlists will still trigger the "Restart to Apply Changes" notification. My tests using the latest update show that the issue with the flag being set for now-playing count changes should be fixed. If you updated too quickly to the fix being released, you may need to update again.

**Comment by Inuyashagcn** [comment]
**@SlvrEagle23** 
Understood, I updated 10 minutes ago, I have not made any other changes with mountponits (I only use 2), playlists or relays, I will update later and tell you my results

**Comment by Inuyashagcn** [comment]
**@SlvrEagle23** 
I have updated again and it is already fixed
Thank you!
