### ISSUE TITLE
Publish to "Yellow Pages" Directories

### ISSUE THREAD

**Issue by fafafoya** [AzuraCast/AzuraCast#1844]
To which YP directories Azuracast publishes the station?

**Comment by fafafoya** [comment]
Any idea what is Lavf/57.56.101 (User Agent)?

**Comment by yarik2720** [comment]
> Any idea what is Lavf/57.56.101 (User Agent)?

It is library name in user agent, it can be used in many apps, I saw that on tunein for android

**Comment by fafafoya** [comment]
Any list of YP?

**Comment by afonsosantos** [comment]
@fafafoya Hi!

You can set Icecast to send your station info to their [Streaming Directory](http://dir.xiph.org/). You can always use a custom YP provider by configuring the station with the settings provided.

**Comment by Guldstrand** [comment]
I'm wondering the exact same thing.
What public "yellow pages" get info about the station?

The feature/selection is added to the panel for a reason, right?

**Comment by fafamonge** [comment]
I activate or checked this option to my mount point but the station is not listed in the directory. Any light about how to use this feature?
