### ISSUE TITLE
Error in Request song message

### ISSUE THREAD

**Issue by yarik2720** [AzuraCast/AzuraCast#1847]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 16.04

**Describe the bug**
On public page while making Song request shows notification with successfull or failed song request, but it show only `[object Object]`

In request response from console answer comes:
`{"code":400,"message":"Duplicate request: this song was already requested and will play soon.","formatted_message":"Duplicate request: this song was already requested and will play soon.","extra_data":[],"success":false}`

**Screenshots**
![chrome_2019-08-12_22-44-45](https://user-images.githubusercontent.com/1839978/62893427-450e2180-bd53-11e9-8633-01802b0586f9.png)

**Device(s):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 76.0.3809.100

**Comment by SlvrEagle23** [comment]
@yarik2720 Yeah, I noticed that and meant to get back to it. Thanks for the reminder. Should be fixed now!

**Comment by yarik2720** [comment]
On successfull message there is also [object Object]

**Comment by afonsosantos** [comment]
Same here

![image](https://user-images.githubusercontent.com/46262740/62975485-5a965080-be12-11e9-9fe5-56d55740e101.png)
