### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#1848]
I tried to install on ubuntu 16.04 by ansiable installation, but it gave me this error:
![azuracast_install_error](https://user-images.githubusercontent.com/7109309/62900538-4a1ea100-bd52-11e9-8a50-74b881584810.jpg)

**Comment by ogrenci01** [comment]
Hi ;

I have this problem. Installation fails at Ubuntu 18.04 and 16.04. I have the same problem here. 

If you are looking for an immediate solution, take the older version of Azuracast to 

> /var/azuracast/www

Perform the installation. Complete all installations. Finally, update the new version with 

> sudo ./update.sh

**Comment by ogrenci01** [comment]
Hi ;

I have this problem. Installation fails at Ubuntu 18.04 and 16.04. I have the same problem here. 

If you are looking for an immediate solution, take the older version of Azuracast to 

> /var/azuracast/www

Perform the installation. Complete all installations. Finally, update the new version with 

> sudo ./update.sh --full

**Comment by ogrenci01** [comment]
Hello Everybody;

I want to help you with an immediate solution.

1-) `sudo apt-get update -y`
2-) `sudo apt-get install -q -y git`
3-) `sudo mkdir -p /var/azuracast/www`
4-) `cd /var/azuracast/www`
5-) `sudo git clone https://github.com/AzuraCast/AzuraCast.git .`
6-) `sudo chmod a+x install.sh`
7-) `sudo chmod a+x update.sh`
8-) Download an older version:
**https://github.com/azuracast/azuracast/archive/0.9.6.zip**
9-) Use FTP to upload this archive to the directory "/var/azuracast/www". Accept changes.
10-) `sudo ./install.sh` After completing the installation, start and complete the installation.
11-) Download the latest version after completing the installation.
**https://codeload.github.com/AzuraCast/AzuraCast/zip/master**
12-) Upload this archive to FTP directory "/var/azuracast/www". Accept changes.
13-) `sudo ./update.sh` After the installation is complete, start and complete the update.
14-) After the update is completed, Azuracast will be ready to use.

Enjoy!

**Comment by SlvrEagle23** [comment]
@jonikane We have identified the cause of this problem and released a version update (0.9.7.1) that fixes this issue for traditional installs. Updating is highly recommended.
