### ISSUE TITLE
feature request : new playlists types

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#185]
Feature request : 

scheduled playlist : add the ability to choose which day(s) for a scheduled playlist. I don't want the week-ends to sound like the rest of the week 
NEW : Scheduled broadcast : play a file (or a playlist) at a precise point in time (ex : 2018-12-07 at 3:00PM )

**Comment by griffon56** [comment]
Can I add : when a scheduled playlist is set, there is no possibilly to add jingles every X track or every X minutes. No way to play a jingle when a playlist is played

**Comment by derkalle4** [comment]
Is there any progress on this? If not is it easy to implement something like this myself and make a pull request? I didn't do a dive deep into your code yet. But a feature for setting playlist for a specific day of week (and time + length, e.G. 01-20-2018 from 6pm to 8pm - repeat every day/week) would be great.

**Comment by SlvrEagle23** [comment]
@derkalle4 @griffon56 I have added day-of-week selection to both the "play once a day" and "play scheduled" playlist types, along with adding clarification for the time ranges in scheduled playlists (including both local time and GMT).
