### ISSUE TITLE
Current listeners update issue

### ISSUE THREAD

**Issue by dbeiner** [AzuraCast/AzuraCast#1850]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 10.04.2 LTS

**Describe the bug**
Current listeners **on profile page** are not updated correctly, especially when the number of listeners goes down. He's freezed !

**To Reproduce**
1. Set station max listeners to 3000
2. Run the Icecast load test script (http://icecast.org/loadtest/1/)
3. Wait to get the meter up...
4. Stop script
5. Compare profile and report page current listeners !

**Expected behavior**
A correct update of the current listeners !

**Screenshots**
1. Profile page current listeners (683) :
https://drive.google.com/file/d/1A1gndsKEbHEWY-r99xSniOuDr33f65oO/view?usp=sharing

1. Report page current listeners (0, right value):
https://drive.google.com/file/d/1tpwg_bFARw8bzkFFqsPsNwrBLn61FoPT/view?usp=sharing

**Device(s):**
- Any browsers !

**Additional context**
Thank you so much for your job !

**Comment by fafafoya** [comment]
Same problem here.
Unique Listeners on Profile page and Reports/Listeners page are not synced.
