### ISSUE TITLE
What is the best way to consume Live Websocket now playing data in react native?

### ISSUE THREAD

**Issue by kirankuyate** [AzuraCast/AzuraCast#1851]
**Using Docker installation method**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by afonsosantos** [comment]
@kirankuyate Hi!

If React Native supports the [nChan client](https://www.npmjs.com/package/nchan), you can try that out.
