### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by fafafoya** [AzuraCast/AzuraCast#1852]
How to integrate Google Analytics for whole traffic to the station as an alternative to Reports/Listener feature?

**Comment by yarik2720** [comment]
Double of #601 
Upvote for adding GA analytics support here: 
https://azuracast.featureupvote.com/suggestions/38908/add-support-for-google-analytics

**Comment by gunsar** [comment]
Now Google Analytics To Version 4
