### ISSUE TITLE
Next song on a public page

### ISSUE THREAD

**Issue by YosefAdPro** [AzuraCast/AzuraCast#1853]
Hey,

Is it possible that the next song will appear on a public page?

Thanks!

**Comment by afonsosantos** [comment]
Could you move your feature suggest to the [AzuraCast's Feature Request](https://features.azuracast.com/) page, so that the team can dedicate Github's Issues to issues only?

Thanks

**Comment by YosefAdPro** [comment]
I understand the importance.
Done!
