### ISSUE TITLE
Error while trying to listen big files, like podcasts

### ISSUE THREAD

**Issue by yarik2720** [AzuraCast/AzuraCast#1854]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 16.04

**Describe the bug**
Error 500 while trying to listen podcast file with size more than 130 MB.
Tested files with sizes: 
* played ok: 111.3 MB, 122.5 MB
* failed to play: 134.7 MB, 137.7 MB, 138.0 MB

**To Reproduce**
1. Go to Music files
2. Click on play button on file that have size more than 130 MB
3. In console you'll see 500 error

**Relevant Logs**
```
web_1       | 2019/08/14 08:43:25 [error] 62#62: *13357 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 143226672 bytes) in /var/azuracast/www/vendor/guzzlehttp/psr7/src/Stream.php on line 80" while reading response header from upstream, client: 192.168.80.1, server: localhost, request: "GET /station/1/files/download?file=monstercat+podcast%2Funknown-%23171+-+Monstercat+Call+of+the+Wild-320kbps.mp3 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "cast.noisefm.ru", referrer: "https://cast.noisefm.ru/station/1/files"
```

**Comment by nicolasguzca** [comment]
This is strange, I have files of 350mb or more and they play fine... What type of server are you using?  @SlvrEagle23 Maybe this is server related?

**Comment by SlvrEagle23** [comment]
@yarik2720 I've published a minor update that may help resolve the issue by avoiding a duplicate file metadata check. Update and let me know if it helps at all.

**Comment by yarik2720** [comment]
Updated, still got the same error.
Found, that in `azuracast.env` file there is commented part
```
# PHP's maximum memory limit.
# PHP_MEMORY_LIMIT=128M
```
Should I uncomment it and allow more memory for php?

**Comment by SlvrEagle23** [comment]
@yarik2720 That might be helpful, especially if you're frequently dealing with files that are larger than that memory threshold.

**Comment by yarik2720** [comment]
This configuration helped
