### ISSUE TITLE
How to play a jingle each time before playing a specific playlist ?

### ISSUE THREAD

**Issue by dbeiner** [AzuraCast/AzuraCast#1855]
Hello ! One question :

I would like to schedule jingle playback from a "Jingles" playlist **each time before** playing a specific playlist.

Is it possible or need I to use an another AutoDJ software like RadioDJ ?

Thank you !

David

**Comment by afonsosantos** [comment]
@dbeiner Hi!

If you are scheduling that playlist to play at a specific time (e.g. 10:00), you can schedule the **Jingles** playlist to play at 9:59.
I'm not sure if this setup would work that weel, but you can always give it a try.
