### ISSUE TITLE
Custom port variables are not working

### ISSUE THREAD

**Issue by workino** [AzuraCast/AzuraCast#1857]
Hello,
I tried to customize the http and https port of my installation ( this time was an upgrade ) but who the guide is showing is not working.

This is the error i got because on my docker installation port 80 and 443 are just in use.
```
Creating azuracast_web_1 ... error

ERROR: for azuracast_web_1  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web_1 (6d294da8dc3416960b6a05ea00b63dfd4842d80872a159f0151d26a35374e85a): Bind for 0.0.0.0:443 failed: port is already allocated

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web_1 (6d294da8dc3416960b6a05ea00b63dfd4842d80872a159f0151d26a35374e85a): Bind for 0.0.0.0:443 failed: port is already allocated
```

This is the .env file with the entries:

```
 cat azuracast.env |head
#
# AzuraCast Customization
#

AZURACAST_HTTP_PORT=8880
AZURACAST_HTTPS_PORT=8443
```

The only way to fix it is to hard code the port in the yml file.

Regards

**Comment by Vaalyn** [comment]
You are editing the wrong .env file. There is the `azuracast.env` which you've edited and a file just called `.env` which is the one you need to edit.
