### ISSUE TITLE
web is ... crashing? (502 Bad Gateway)

### ISSUE THREAD

**Issue by Simon818** [AzuraCast/AzuraCast#1858]
**Using Docker installation method**

yes

**Host Operating System**

Debian 10

**Describe the bug**

At some point after running for a while, I'm unable to connect to my azuracast dashboard. Instead I'm immediately greeted with a "502 Bad Gateway". I'm assuming this indicates something crashing, but am not familiar enough with the images to know what. When I look at web logs, I get the log entry below.

*docker-compose restart web* instantly fixed it.
**To Reproduce**

I only wish I knew.

**Expected behavior**

Going to listen.stationname.com should bring up the login prompt.
**Relevant Logs**

web_1       | 2019/08/14 21:34:38 [error] 66#66: *197110 no live upstreams while connecting to upstream, client: 111.11.11.1, server: localhost, request: "POST /api/internal/7/nextsong HTTP/1.1", upstream: "fastcgi://localhost", host: "web"

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 
Server OS: Debian 10
Client OS (my desktop): Windows 10
Browser: Chrome (but also everything)
Version: 76

**Additional context**

**Comment by ivellios1988** [comment]
Not sure if this helps but 502's happen to me when my AzuraCast server is heavily overloaded, i. e. as a result of heavy DDoS.
