### ISSUE TITLE
update issues detected

### ISSUE THREAD

**Issue by hillbilly-mark** [AzuraCast/AzuraCast#1860]
Issue 1.   When the azuracast dashboard informs you an update is available, there is a link for instructions pointing to a 404 error.

Issue 2.  ./docker.sh update-self throws a syntax error about missing brackets.

**Using Docker installation method**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by afonsosantos** [comment]
Hi!

1st Issue: When I click on the link, I get redirected to https://www.azuracast.com/install/#updating, not sure what's the issue.

**Comment by ErnestPH** [comment]
> Issue 2. ./docker.sh update-self throws a syntax error about missing brackets.

You have to run it again making sure the download is successful… This sometimes happen

**Comment by hillbilly-mark** [comment]
For me the link was install.html which is a file that does not exist.  Thus the 404.  I suggest you simply redirect the install.html to you link you mentioned to catch others from landing there.  


---- On Wed, 14 Aug 2019 18:20:19 -0800 notifications@github.com wrote ----



Hi!

1st Issue: When I click on the link, I get redirected to https://www.azuracast.com/install/#updating, not sure what's the issue.

**Comment by afonsosantos** [comment]
@hillbilly-mark That was because you were running a older version, where that link was still valid. In the newer versions, that link is updated.

**Comment by SlvrEagle23** [comment]
@hillbilly-mark This is a known issue. Unfortunately, as a technical limitation of our static site host we couldn't set up redirects. I've moved us over to a different static site host, as this was becoming a bit of a widespread issue, and that fixes the issue.
