### ISSUE TITLE
i don't have sound on my public page

### ISSUE THREAD

**Issue by HiiZun** [AzuraCast/AzuraCast#1861]
**LOGS**
[2019-08-15  12:33:48] WARN xml/parsing warning: 
[2019-08-15  12:33:48] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2019-08-15  12:33:48] WARN connection/get_ssl_certificate Invalid cert file /etc/nginx/ssl/ssl.crt (system lib)
[2019-08-15  12:33:48] WARN slave/slave_startup process has 65536 max file descriptor limit
[2019-08-15  13:09:07] WARN xml/parsing warning: 
[2019-08-15  13:09:07] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28
[2019-08-15  13:09:07] WARN connection/get_ssl_certificate Invalid cert file /etc/nginx/ssl/ssl.crt (system lib)
[2019-08-15  13:09:07] WARN slave/slave_startup process has 65536 max file descriptor limit

**Using Docker installation method**
yes

**Host Operating System**
Ubuntu 19.04 LTS

**Describe the bug**
i can"t listen the music on the public page 
http://<ipadress>/public/<radioname>
but i have the name of music
(http://prntscr.com/ot07ho)

**To Reproduce**

1. it's a fresh install by the docker.sh
2. i have installed musics on the music list and add it on the default playlist

**Device(s):**
 - Device:  desktop 
 - OS:  windows 10 home
 - Browser:  vivaldi  
 - Version:  2.5.1525.40 (Stable channel) (64 bits) 

**Additional context**
it's the second time to i try to install azuracast

**Comment by Moderndayfreak** [comment]
Are you using Digital Ocean?

**Comment by MrSteelMiner** [comment]
The icecast-log you added seems to be normal. What says the liquidsoap-log? And: What happens, when you open the stream-url itself (without the public page)?

**Comment by SlvrEagle23** [comment]
@HiiZun There are a few reasons you may not be able to hear sound on your public pages, and here are some easy fixes to try:

- Try turning on the "Use Web Proxy for Radio" settings on the global Settings page, which will proxy your radio signals through the standard web ports, which is helpful if you're using CloudFlare or other reverse proxies in front of your site.

- Try turning off the "Websocket Now Playing Updates" setting on the global Settings page. This may not work in some circumstances and is meant for high-performance environments but isn't necessary for most stations.

**Comment by ivellios1988** [comment]
Do you use HTTPS on your server? Maybe your browser is blocking 'unsafe' connections? Don't you have a 'disable autoplay' plugin installed?

**Comment by HiiZun** [comment]
so i have switch server but this server has a error when i try to install: 


root@HiiZun /var/azuracast # ./docker.sh install
Docker is already installed! Continuing...
Docker Compose is already installed! Continuing...
Creating default AzuraCast settings file...
Retrieving default docker-compose.yml file...
Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Creating azuracast_mariadb_1 ...
Creating azuracast_influxdb_1 ... error
Creating azuracast_stations   ...
Creating azuracast_mariadb_1  ... error

ERROR: for azuracast_influxdb_1  Cannot create container for service influxdb: error creating overlay mount to /var/lib/docker/overlay2/84acb3b179811579cc77e74b678ebe8da0856c5b98727de14d23e4ddc692ec95-init/merged: permission denied

ERROR: for azuracast_mariadb_1  Cannot create container for service mariadb: error creating overlay mount to /var/lib/docker/overlay2/72535ddf276c39612c0981e4b486cbc6ea2f984c8d27948998e636afebc4af1Creating azuracast_redis_1    ... error

Creating azuracast_stations   ... error
it/merged: permission denied

ERROR: for azuracast_stations  Cannot create container for service stations: error creating overlay mount to /var/lib/docker/overlay2/3cb6027e99075593361640b25666c5342d2c43c32179973f754451341a952720-init/merged: permission denied

ERROR: for influxdb  Cannot create container for service influxdb: error creating overlay mount to /var/lib/docker/overlay2/84acb3b179811579cc77e74b678ebe8da0856c5b98727de14d23e4ddc692ec95-init/merged: permission denied

ERROR: for mariadb  Cannot create container for service mariadb: error creating overlay mount to /var/lib/docker/overlay2/72535ddf276c39612c0981e4b486cbc6ea2f984c8d27948998e636afebc4af14-init/merged: permission denied

ERROR: for redis  Cannot create container for service redis: error creating overlay mount to /var/lib/docker/overlay2/dcc53a688f7949f11fb4c9058b5952fe7ce76b8cd57a4caa63cfb87f57cca327-init/merged: permission denied

ERROR: for stations  Cannot create container for service stations: error creating overlay mount to /var/lib/docker/overlay2/3cb6027e99075593361640b25666c5342d2c43c32179973f754451341a952720-init/merged: permission denied
ERROR: Encountered errors while bringing up the project.
Creating azuracast_influxdb_1 ... error
Creating azuracast_mariadb_1  ...
Creating azuracast_stations   ...
Creating azuracast_redis_1    ...
Creating azuracast_mariadb_1  ... error
ERROR: for azuracast_influxdb_1  Cannot create container for service influxdb: error creating overlay mount to /var/lib/docker/overlay2/c226c5ed77879874fb279fdc9c79e7b26754d7f244d5e164a3e5aee8fc95a55f-init/merged: permission denied

ERROR: for azuracast_mariadb_1  Cannot create container for service mariadb: error creating overlay mount to /var/lib/docker/overlay2/2eba6038b543c1ba8e2aedbcf375148dd17fdfc4a225839cd909871396e7d84Creating azuracast_redis_1    ... error

Creating azuracast_stations   ... error
it/merged: permission denied

ERROR: for azuracast_stations  Cannot create container for service stations: error creating overlay mount to /var/lib/docker/overlay2/07d324060604e65f36e8c1899ae8c311e862833807aa1d5237a6e9164a67de5d-init/merged: permission denied

ERROR: for influxdb  Cannot create container for service influxdb: error creating overlay mount to /var/lib/docker/overlay2/c226c5ed77879874fb279fdc9c79e7b26754d7f244d5e164a3e5aee8fc95a55f-init/merged: permission denied

ERROR: for mariadb  Cannot create container for service mariadb: error creating overlay mount to /var/lib/docker/overlay2/2eba6038b543c1ba8e2aedbcf375148dd17fdfc4a225839cd909871396e7d849-init/merged: permission denied

ERROR: for redis  Cannot create container for service redis: error creating overlay mount to /var/lib/docker/overlay2/fae347f9054dac07fc6ee6685b54025bd974b1ed0fa77231613b53cd6c2efb7d-init/merged: permission denied

ERROR: for stations  Cannot create container for service stations: error creating overlay mount to /var/lib/docker/overlay2/07d324060604e65f36e8c1899ae8c311e862833807aa1d5237a6e9164a67de5d-init/merged: permission denied
ERROR: Encountered errors while bringing up the project.

**Comment by SlvrEagle23** [comment]
@HiiZun That is a Docker-related error. Your Docker installation may not have installed correctly, or you may need to reboot and try installing again. It's also possible your web host doesn't support Docker installations on that level of server.

**Comment by HiiZun** [comment]
the server is a vps with lxc for the virtualisation
lxc is compatible with azuracast ?

**Comment by HiiZun** [comment]
@SlvrEagle23 hello (sorry for the ping) i have re-installed docker but i have again this error :/

**Comment by Psychoses** [comment]
hi
i think lxc is your problem here. You can:

-use docker without lxc
-lxc with traditional azuracast install method
-change vps

https://github.com/AzuraCast/azuracast.com/issues/8
https://github.com/AzuraCast/AzuraCast/issues/1658
