### ISSUE TITLE
Security Controls "Always use HTTPS' is not working

### ISSUE THREAD

**Issue by Moderndayfreak** [AzuraCast/AzuraCast#1863]
**Using Docker installation method**

Yes
**Host Operating System**

Ubuntu 18
**Describe the bug**

Enable the HTTPS and its not working. 
**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 
Desktop
**Additional context**

Enabled the HTTPS option under Security Controls. The site base url is a subdomain from the main site domain that uses VestaCPs SSL option. Could this be the issue in why the Azuracast HTTPS option is not working? It was also brought to my attention that the embedded player will not work on a site that's HTTPS unless the base url is HTTPS.

Thanks

**Comment by danehrlich1** [comment]
Could be something in the Nginx config. Can try to redirect port 80 to port 443 automatically. Also can try some other things like HSTS. Only recently started looking into AzuraCast installation so will let you know what I find.
