### ISSUE TITLE
UTC different in Reports Stats

### ISSUE THREAD

**Issue by detone** [AzuraCast/AzuraCast#1865]
**Using Docker installation method**
No 

**Host Operating System**
Ubuntu 18.04 

**Describe the bug**

I set a radio station to UTC -03 (Sao_Paulo) ... But when I look at the hourly statistics, it displays the UTC time, different from what was set for the station.

What to do?

I am not using a docker.

Thanks.

**Comment by SlvrEagle23** [comment]
@detone You mean specifically the hourly statistics from the Statistics Overview page?

**Comment by detone** [comment]
Hi man!

No... The UTC in Reports > View Statistics.

In UTC (menu) and the graphics is different for the UTC radio station.

try creating a station, set it to UTC Sao_Paulo and then look in the menu> reports> statistics.

**Comment by detone** [comment]
Hello ... I created another VM with Centos 7 and installed Azuracast with
Docker.

Even though everything is OK, at the time of displaying the access report
by day, the time is back to UTC and not to UTC -3 (São_Paulo) as it was set
at the time of creating the station.

Don't I have to change the time zone in Docker either?  What do you think?

Thank you for your support!

David Jill
BestRadio Brasil

Em sex, 16 de ago de 2019 00:17, SlvrEagle23 <notifications@github.com>
escreveu:

**Comment by SlvrEagle23** [comment]
@detone Sorry for the lack of updates...this is likely a bug on our end where some reports don't use the station time zone properly. I'm working on it and will have a fix for you shortly.

**Comment by detone** [comment]
No problems!!

As far as I can help report and suggest improvements to the system, I'm
here.

One suggestion in the reports is that you could have an option to view the
mountpoint reports separately as well.

Example: There are 2 mountpoints in the station.  One is the mount point
that goes to the station's website.  The other is for another partner
site.  I want to know how many listeners I had coming from the partner site
mountpoint.  :)

Thanks for the support and congratulations to the entire developer team.

Em ter, 20 de ago de 2019 21:46, SlvrEagle23 <notifications@github.com>
escreveu:

**Comment by SlvrEagle23** [comment]
@detone The latest update to the code should ensure that the main statistics page properly uses the station's time zone.

For the other request, it's definitely not a bad idea but it's not something our system currently tracks or can track. We have a few improvements we'd like to make to our statistics tracking and that likely would be included. You should make sure that idea is listed on our [FeatureUpvote site](https://features.azuracast.com/).

**Comment by detone** [comment]
Hi @SlvrEagle23

I'll wait for the update and report if it worked or not. :-)
Thanks again.

David Jill
BestRadio Brasil

Em ter, 20 de ago de 2019 às 23:42, SlvrEagle23 <notifications@github.com>
escreveu:
