### ISSUE TITLE
Remove Song History and Playlist

### ISSUE THREAD

**Issue by fafafoya** [AzuraCast/AzuraCast#1866]
Help me to code Custom CSS for removing Song History and Playlist buttons from web player in Public Page.

**Comment by SlvrEagle23** [comment]
@fafafoya As a project, we don't provide CSS or JavaScript tutorials, as there are both tools built into most major browsers and countless web sites out there that supply that information. If the community wants to help out with a code snippet, they're welcome to reply here.

**Comment by parksquare** [comment]
This js will hide all the buttons beneath the player

$(".card-actions").hide()

**Comment by yarik2720** [comment]
In CSS:
to hide all actions
```
.card-actions {
  display: none;
}
```
But users can manage to find this buttons with inspector of elements.
You can delete it with custom JS:
```
$(".card-actions").remove();
```

**Comment by fafafoya** [comment]
Thanks.
