### ISSUE TITLE
Incorrect message displayed when user requests a track

### ISSUE THREAD

**Issue by parksquare** [AzuraCast/AzuraCast#1867]
**Using Docker installation method**

Yes
**Host Operating System**

Debian 10
**Describe the bug**

When a user requests a track, the pop up confirmation displays 'Object Object' instead of the correct message
**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

![image](https://user-images.githubusercontent.com/14939654/63165261-d0710680-c022-11e9-9c93-4e15a4fa3035.png)

**Comment by yarik2720** [comment]
That was fixed in #1847

**Comment by parksquare** [comment]
I'm running that version (#90d0042) which should contain that fix though right?

![image](https://user-images.githubusercontent.com/14939654/63182917-9a944800-c04b-11e9-9dd0-ea3d5f34af36.png)

**Comment by yarik2720** [comment]
That version contains fix only for errors messages and you need to update, to find your version simply use this list: https://github.com/AzuraCast/AzuraCast/commits/master

**Comment by parksquare** [comment]
Sorry I don't follow. The commit mentioned above that fixes issue 1847 is part of the version I have.
