### ISSUE TITLE
Video Streaming

### ISSUE THREAD

**Issue by AleAmla987** [AzuraCast/AzuraCast#187]
Will it be implemented so that video can be transmitted?

**Comment by SlvrEagle23** [comment]
@AleAmla987 At the moment, I have no major plans to expand AzuraCast to include video streaming, as this would significantly expand the bandwidth and storage requirements of the system, and processing video can be a far more processor-expensive task than doing the same for audio.

However, both LiquidSoap and IceCast (to some extent) are capable of streaming video out to the public, so it's possible that such a feature could be developed in the future.

**Comment by AleAmla987** [comment]
I do not think it is necessary that this integrated with AzuraCast, could be a separate project ... for example AzuraVideo, I would love to help but I am a .NET expert.

**Comment by nsystem1** [comment]
I agree it should be separated. I am willing to help in that effort as well

**Comment by Donokami** [comment]
Well, it could be a good idea to stream a video for the radio, on livestreams like Facebook, Twitch, etc...

**Comment by transifex3** [comment]
@Donokami Requested feature like that on [HERE](https://github.com/AzuraCast/AzuraCast/issues/337). Hopefully wanna see that soon!

**Comment by Roforum** [comment]
You can do this with OBS Studio.

**Comment by Donokami** [comment]
Yep, it's the best way to do it.

**Comment by transifex3** [comment]
@Roforum But definitely hard to archive when you wanna do it with VPS.

**Comment by fabriziosalmi** [comment]
I sincerily got a similar solution using ffmpeg (no OBS)

`ffmpeg -loop 1 -i /var/background_image.jpg -thread_queue_size 512 -i https://radio.freeundergroundtekno.org/radio/8000/radio.mp3?1589882348  -c:v libx264 -preset veryfast -x264-params keyint=4:scenecut=0 -b:a 320k -b:v 8192k -minrate 2048k -maxrate 8192k -bufsize 8192k -f flv rtmp://a.rtmp.youtube.com/live2/587t-0t51-kyp2-YYYY-XXXX`

Some additional info:

- output bitrate can be 4500kbps as per YouTube guideline
- thread_queue_size 512 avoid audio drops
- keyint=4 matches YouTube requirements on keyframe interval
- bufsize 8192k can be higher if you still experience drops
- preset veryfast help the cpu load a little bit (avoid iit f u need super video quality)

This works stable (Azuracast to ffmpeg to YouTube live endpoint) with a single cheap 5€/month linux VPS.

**Comment by fabriziosalmi** [comment]
> Well, it could be a good idea to stream a video for the radio, on livestreams like Facebook, Twitch, etc...

It is very popular on 2020. Most of them with a nice animation background loop.
