### ISSUE TITLE
Audit Log text overflowing modal bounds

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#1872]
**Using Docker installation method**
Yes

**Host Operating System**
Debian 9

**Describe the bug**
When updating the custom css (if you have a bit of stuff in there) the Audit Log entry will overflow the bounds of the modal when looking at the specific changes.

**To Reproduce**
1. Add some custom css so that the entry does not fit into the normal width of the Audit Log modal
2. Visit the Audit Log
3. Look at the changes modal

**Expected behavior**
The text should either automatically break into the next line or the modal should be scrollable.

**Relevant Logs**
No logs needed here.

**Screenshots**
![image](https://user-images.githubusercontent.com/13745863/63211682-f4078000-c0fa-11e9-80f7-05a8e264c5bb.png)

**Device(s):**
 - Device: Desktop
 - OS: macOS 10.14.5
 - Browser: Chrome
 - Version: 75.0.3770.142

**Comment by SlvrEagle23** [comment]
@Vaalyn Not sure what the easier solution would be to this one. We could set that text to wrap, but I think that'd mess with the fact that it's a "preformatted" section of text...scrolling horizontally isn't really pretty, but then again this is only one section of one administrative dialog.
