### ISSUE TITLE
Playlist Reorder - Missing "save" button

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1873]
Recent version on Ansible (Ubuntu 18.04 LTS)

I wanted to reorder a playlist, but there is no "save changes" button :(
![image](https://user-images.githubusercontent.com/47743654/63214732-705e8b00-c11c-11e9-8648-ba4091c62d43.png)

**Comment by SlvrEagle23** [comment]
@MrSteelMiner The changes should be saving on-the-fly automatically every time you make an ordering change, but I can see how that's not immediately intuitive from the web interface. I'll see what we can do about improving that.

**Comment by MrSteelMiner** [comment]
I tried it 3 times, but it's not saving on-the-fly.

**Comment by SlvrEagle23** [comment]
@MrSteelMiner Definitely a valid bug, should be fixed as of the latest update this evening. Thanks for letting me know!
