### ISSUE TITLE
Azuracast is not updating after running updates

### ISSUE THREAD

**Issue by Moderndayfreak** [AzuraCast/AzuraCast#1876]
**Using Docker installation method**

Yes
**Host Operating System**

Ubuntu 18
**Describe the bug**

Run the update but it does not update
**To Reproduce**

root@azuracast:~# /var/azuracast/
-bash: /var/azuracast/: Is a directory
root@azuracast:~# ./docker.sh update-self
New Docker utility script downloaded.
root@azuracast:~# ./docker.sh update
Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Stopping root_mariadb_1  ... done
Stopping root_influxdb_1 ... done
Stopping root_redis_1    ... done
Removing root_mariadb_1  ... done
Removing root_influxdb_1 ... done
Removing root_redis_1    ... done
Removing network root_default
Error response from daemon: remove azuracast_www_data: volume is in use - [a1246                                    e7c18734f2d8dead7523a9782906b0d6478e3ff4613d1aa392e3c3ce151]
Error response from daemon: remove azuracast_tmp_data: volume is in use - [a1246                                    e7c18734f2d8dead7523a9782906b0d6478e3ff4613d1aa392e3c3ce151, 061f160f360c0376fb7                                    eaceac4928ec7d932785f8e2a5223546f3a33283d88a5]
Creating network "root_default" with the default driver
Creating azuracast_stations ... error
Creating root_redis_1       ...
Creating root_mariadb_1     ...
Creating root_influxdb_1    ...

ERROR: for azuracast_stations  Cannot create container for service stations: Con                                    Creating root_redis_1       ... done
Creating root_mariadb_1     ... done
Creating root_influxdb_1    ... done

ERROR: for stations  Cannot create container for service stations: Conflict. The container name "/azuracast_stations" is already in use by container "061f160f360c0376fb7eaceac4928ec7d932785f8e2a5223546f3a33283d88a5". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
root_influxdb_1 is up-to-date
root_redis_1 is up-to-date
root_mariadb_1 is up-to-date
Creating azuracast_stations ... error

ERROR: for azuracast_stations  Cannot create container for service stations: Conflict. The container name "/azuracast_stations" is already in use by container "061f160f360c0376fb7eaceac4928ec7d932785f8e2a5223546f3a33283d88a5". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for stations  Cannot create container for service stations: Conflict. The container name "/azuracast_stations" is already in use by container "061f160f360c0376fb7eaceac4928ec7d932785f8e2a5223546f3a33283d88a5". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
Update complete!
root@azuracast:~#

**Expected behavior**

After rebooting the server I still get the:

New AzuraCast Release Version Available
AzuraCast version 0.9.6.1 is now available. You are currently running version 0.9.6. Updating is highly recommended. Follow the update instructions to update your installation.

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 
Desktop
**Additional context**

**Comment by SlvrEagle23** [comment]
@Moderndayfreak You appear to have done something wrong in the Linux terminal at step 1:

```
root@azuracast:# /var/azuracast/
-bash: /var/azuracast/: Is a directory
```

That should be `cd /var/azuracast/`, to change directory to that location.

Running the Docker utility script in a different directory from where it was originally installed, while the original location is still both installed and running, will definitely always cause problems. There's not much we can do about that.
