### ISSUE TITLE
Now playing metadata is not in sync with song playing (audio)

### ISSUE THREAD

**Issue by kirankuyate** [AzuraCast/AzuraCast#1879]
**Using Docker installation method**

**Host Operating System**

**Describe the bug**
We are using all default settings for docker installation but the now playing metadata is not in sync with the audio playing.

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@kirankuyate How far apart are they in synchronization? They should typically only be maybe 15 seconds apart at worst. If you're seeing that the now-playing song isn't updating _at all_, that's a different bug that we can look into.

You also may want to try turning on (or if you have it on, turning off) the "Web Socket Now Playing Updates" setting in the system-wide settings panel.

**Comment by kirankuyate** [comment]
@SlvrEagle23 It is around 14 to 15 seconds.

**Comment by SlvrEagle23** [comment]
@kirankuyate In which direction, 14 seconds too late or too early? This is within normal variation due to the way our system checks the next-playing song. It may also be improved by, as I said, turning on the Web Socket now-playing updates.

**Comment by kirankuyate** [comment]
@SlvrEagle23 Audio is behind the metadata. Now playing metadata is received around 15 seconds earlier.
Also, WS updates did not make any difference.

**Comment by SlvrEagle23** [comment]
@kirankuyate Oh, if the metadata in AzuraCast is updating _before_ the song changes in the actual broadcast, there's nothing we can do about that. Basically, we update our end a few seconds after Liquidsoap notifies us of the metadata change, which is itself a few seconds before the broadcast updates.

The difference in the time we receive it and the time you actually hear the song change is a product of so many factors, including any buffer that may have built up while you were listening, the latency before your server delivers its first, etc. We actually offset the song start time by 5 seconds as a result of these delays.
