### ISSUE TITLE
Shoutcast V1 Needed

### ISSUE THREAD

**Issue by danyalsaleemqureshi** [AzuraCast/AzuraCast#1880]
Hello is there any way for installing shoutcast v1, as its needed badly, my android application is not working without v1 so Thats Why I want to use shoutcast v1, any luck?

**Comment by SlvrEagle23** [comment]
@danyalsaleemqureshi We don't bundle or support SHOUTcast v1 as it's quite out of date at this point and is no longer supported, and is also a part of SHOUTcast's closed-source ecosystem that we can't package with our application while still remaining fully free and open-source.

We have a number of stations using Android apps with our Icecast broadcasting method without any issues at all. Icecast streams the same standard MP3 stream that either version of SHOUTcast broadcasts, and any modern version of Android can handle the stream quite well.

**Comment by ivellios1988** [comment]
Apart from that, Shoutcast v1 uses an outdated version of HTTP protocol which would prevent your radio from being played by modern browsers. Having this in mind, it makes no sense to install Shoutcast v1 anymore.
