### ISSUE TITLE
Playlist configuration. Is this possible?

### ISSUE THREAD

**Issue by fiwus** [AzuraCast/AzuraCast#1882]
Hi I'm a new user od azuracast. I have some problems with create playlist. I need to create playlist with two requests:
- playlist schelude only friday between 10:00 and 12:00
- play songs from this playlist after x5 songs
Is it possible to add few options?

And next problem: is it possible to add connect one jingle with one song (jingle play before this song in rotation)
Pls help

sorry for my english :)

**Comment by dbeiner** [comment]
Hi,

Same request for me ! :)

> And next problem: is it possible to add connect one jingle with one song (jingle play before this song in rotation)

**Comment by afonsosantos** [comment]
@fiwus @dbeiner That feature is already requests in the Feature Upvote page of AzuraCast. You may need to wait until the team implements that feature.
