### ISSUE TITLE
Download ShoutCast

### ISSUE THREAD

**Issue by xXxwalkingDeadxXx** [AzuraCast/AzuraCast#1883]
Is there a possibility to provide different versions of Shoutcast here?
The problem is that the **new version no longer supports AAC** and I do **not want to switch to Icecast** right now.
I'm looking for crazy **version 2.5.5.733** and can only find the latest :/
Here's what to read, what I mean exactly: https://www.rocketbroadcaster.com/help/icecast-vs-shoutcast

Although my concern here is probably wrong, I would be very grateful for your help!

**Comment by ogrenci01** [comment]
Hi;

I have ShoutCast v2.5.5.733 and I use it on AzuraCast.

There is official app. You can use it on your AzuraCast App.
Download link: https://www.arkacadde.org/sc_serv2_linux_x64-latest.tar.gz

**Comment by xXxwalkingDeadxXx** [comment]
Thank, you made my day!
