### ISSUE TITLE
Let's Encrypt problem

### ISSUE THREAD

**Issue by fafafoya** [AzuraCast/AzuraCast#1884]
I have installed Let's Encrypt certificate using ./docker.sh letsencrypt-create subdomain.example.com

And then enabled Always Use HTTPS in Security Controls under System Settings menu.
Now, I am not able to access to the Dashboard and get below error in Chrome:

This page isn’t working 
subdomain.example.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

**Comment by fafafoya** [comment]
When I try to access dashboard using https://IPaddress/login, I get below error message:

Connection not protected
The security of your connection is reduced. Criminals can attempt to steal your data from the website. You are advised to leave this website.

URL:
subdomain.example.com

Reason:
Invalid name of certificate. Either the name is not on the allowed list, or was explicitly excluded. 
View certificate

How can I fix the problem by disabling Always Use HTTPS?
Can I uninstall Let's Encrypt using docker?

**Comment by SlvrEagle23** [comment]
@fafafoya If you're using the "Always use HTTPS" setting, make sure your site's base URL also begins with "https://" or you'll just be redirecting to that same web site over and over.

Also, if you're using a slightly older build of AzuraCast you should update, as we resolved some issues with CloudFlare and HTTPS connections a week or two ago.

**Comment by fafafoya** [comment]
Problem still persists.

1) I am not using Cloudflare
2) I am using latest Azuracast build
3) I set Site Base URL to https:// but when I save, it removes https:// from URL
4) I enabled Use Web Proxy for Radio

**Comment by xXxwalkingDeadxXx** [comment]
Lets check Update
`cd /var/azuracast`
`./docker.sh update-self && echo "y" | ./docker.sh update`

then we check LetsEncrypt
`cd /var/azuracast`
`./docker.sh letsencrypt-create mydomain.example.com`

That's how it worked for me!

**Comment by fafafoya** [comment]
I followed the same but still SSL doesn't work.
