### ISSUE TITLE
error traducion

### ISSUE THREAD

**Issue by webservichost** [AzuraCast/AzuraCast#1885]
I am having trouble translating my azuracast. I read everything in the pt-br / default.po file and didn't find the part that translates
"Request submitted successfully".
This appears when you place a song request.
I don't find a way to translate this to en.

**Comment by MrSteelMiner** [comment]
There is a Crowdin project for AzuraCast where everyone can suggest/contribute translations. After a check they will be added to AzuraCast in the next update.

**Comment by webservichost** [comment]
Thanks for the answer.
I saw the project, but did not attend me, I need to know where I go to update the "Request submitted successfully" myself.
I searched the azuracast translation files and couldn't find the line that said it. I was able to translate a good part but that part there.

**Comment by SlvrEagle23** [comment]
@webservichost Sorry about that. I have updated the application to do a minor overhaul of the localization, so that both API responses and CLI commands will properly be localized.
