### ISSUE TITLE
Forgot password link

### ISSUE THREAD

**Issue by fafafoya** [AzuraCast/AzuraCast#1887]
On Login page to Azuracast Dashboard, the link to Forgot your password is set to: https://www.azuracast.com/help/faq_docker.html#reset-an-account-password

However, it should be re-directed to a page for asking email address of User in order to reset the password.

**Comment by SlvrEagle23** [comment]
@fafafoya The way we have designed our system is on purpose. There are several reasons we don't implement the standard "forgot password" e-mail confirmation method that you might see in other apps:

 - This would require that each self-hosted AzuraCast instance have configured outbound mail delivery, which for most users would require signing up for a third-party transactional e-mail service (i.e. Mailgun), and which would tie us to other servers in a way that isn't self-contained, and

 - In general, the "forgot password" mechanism is a [security hole waiting to happen](https://paragonie.com/blog/2016/09/untangling-forget-me-knot-secure-account-recovery-made-simple). It can be done in a secure way, but that requires significant implementation time on our part and again depends on the first option.

If there was enough demand for us to rework how we handle this, we might look into alternatives in the future. You're welcome to [submit a feature request](https://features.azuracast.com/) if you would like to see this made a priority in our future development.
