### ISSUE TITLE
Wish Box 

### ISSUE THREAD

**Issue by Skyradio** [AzuraCast/AzuraCast#1889]
Hi. After I updated to the last Version, wishe apear in the "playing next" but never will be played. And the Titel won't get away from playing next.

**Comment by SlvrEagle23** [comment]
@Skyradio I'm sorry, I don't understand the problem you're having. Are you saying you're seeing a song in the "playing next" section that never actually plays? Or you're not seeing any song at all in the "playing next" section?

**Comment by Skyradio** [comment]
@SlvrEagle23 I never see a song in the "playing next" except it comes by the wish Box. But this song is not playing and sitting in the "playing next" and never vanishes. I have to erase this song manually.
