### ISSUE TITLE
Cannot add user who isn't super administrator 

### ISSUE THREAD

**Issue by cryptoworksmedia** [AzuraCast/AzuraCast#189]
Hello,

When I try an add a user who isn't a super administrator, i get: 
Error 310 (net::ERR_TOO_MANY_REDIRECTS): There were too many redirects

I've tried everything I can to work out what it may be this end.  Has anyone experienced similar or can advise how to resolve?

Thanks

**Comment by SlvrEagle23** [comment]
@cryptoworksmedia I will look into this and get back with a fix shortly if needed.
