### ISSUE TITLE
Listener Count on Profile Error

### ISSUE THREAD

**Issue by adwinter** [AzuraCast/AzuraCast#1892]
**Using Docker installation method**
No

**Host Operating System**
Ubuntu 16.04 Server LTS

**Describe the bug**
On the profile page, the On The Air box has unique and total listeners backwards.

**To Reproduce**
Play your stream from the same IP address more than once and the Total listeners will be smaller than unique. 

**Expected behavior**
It should be the other way around... Unique should be unique IP addresses and total should be the raw listener count.

**Relevant Logs**
N/A

**Screenshots**
N/A

**Device(s):**
Browser (Chrome if that matters)

**Additional context**

**Comment by SlvrEagle23** [comment]
@adwinter Can you join our [Slack channel](https://azuracast.com/slack) and DM me with your instance information? I'm trying to isolate what's causing this, as a few people have reported it but I can't reproduce it with the standard Icecast frontend.

**Comment by adwinter** [comment]
Ok. Is there a report or something you need me to run to troubleshoot? Or
do you want access to the actual backend of my station?
I'll join the Slack channel and we can talk about it more there. Thanks.

Andrew

**Comment by MrSteelMiner** [comment]
![image](https://user-images.githubusercontent.com/47743654/63431485-355f9e80-c41f-11e9-910e-cf804d5aa620.png)

That's my Listener Counter... I think in my case it's because I turned off the listener stats completely and so AzuraCast cannot isolate the single listener but I don't know.
