### ISSUE TITLE
Checking Media folder high usage cpu

### ISSUE THREAD

**Issue by cristianocarrozzi** [AzuraCast/AzuraCast#1894]
Instalation: Docker version 0.9.6.1 - Ubuntu 18.04

Hello guys!
First of all thank you for this excellent project. Azura is awesome.
But I am having a performance issue.
I use the same Media Directory folder for all radios.
This folder has about 11,000 songs, 80GB.
Every time I create a new radio it runs the process: php /var/azuracast/www/util/cli.php queue:process 300 which is active for a long time, writing the same message to the log "AzuraCast.INFO: Handling message of type App \ Message \ AddNewMediaMessage. [] [] " for all songs.
And every 5 minutes runs Sync Check Media Folders process and the cpu usage goes up a lot.
In an instance of 30 radios on a 4 cpu server, 8 GB of RAM and the processing was all the time at 90-100%. Without shared folders it is 40-50%.
Is there any other way to share music between all radios that do not cause this problem?
Is it possible disable these automatic processes and run manually, running when that high cpu usage will not be relevant?

**Comment by SlvrEagle23** [comment]
@cristianocarrozzi From the Station administration page inside System Administration, if you take an existing station, clone it, and indicate that you want to share the existing media library, it should also copy over all the media records in the database, avoiding the heavy CPU load of processing the new media.

**Comment by cristianocarrozzi** [comment]
@SlvrEagle23 returned HTTP 500 error. If I clone with "Do not share option" works.

**Comment by cristianocarrozzi** [comment]
Log:

web_1       | 2019/08/23 20:11:24 [error] 63#63: *871 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 294912 bytes) in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 677" while reading response header from upstream****

I found UnitOfWork.php file but I have no idea what to do.

**Comment by cristianocarrozzi** [comment]
ok, I found this:
[Song Listener Impact: Allowed memory exhausted #807](url)
Problem solved!
