### ISSUE TITLE
Playlist Issue

### ISSUE THREAD

**Issue by Moderndayfreak** [AzuraCast/AzuraCast#1895]
**Using Docker installation method**

Yes
**Host Operating System**

Ubuntu 18
**Describe the bug**

**Schedule playlists are not playing at all.** There are a total of 9 playlists that are in general rotation. We have 4 additional playlists that are scheduled at set times. The schedule playlists are not working.

Should we use the advanced playlists feature? If so where is the liquid soap config file?

One would think though that the Azuracast dashboard would be able to do this.

Thank you

**To Reproduce**

**Expected behavior**

The schedule should be playing at their set times.
**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 
Desktop
**Additional context**

**Comment by SlvrEagle23** [comment]
@Moderndayfreak Can you send a screenshot of the scheduling tab when editing one of the scheduled playlists? There are a lot of settings on there that could determine how our scheduler would handle the playlist, so that's the easiest way to see them all in one spot.
