### ISSUE TITLE
copy songs name

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#1897]
Is it possible to copy songs name in txt file?

**Comment by MrSteelMiner** [comment]
What do you mean? The song history or the "Now Playing"?

**Comment by afonsosantos** [comment]
@MrSteelMiner I think @jonikane wants to export the song library in a `.txt` file. I don't think that's possible right now, atleast using the web interface.

**Comment by MrSteelMiner** [comment]
It is possible, but not with AzuraCast itself. Just use a find command in the linux shell. 
It should be something like this:
`find / -name "*.mp3" -exec stat --printf="%n\n" {} \; > /path/to/file.txt`

**Comment by jonikane** [comment]
All songs in playlist

**Comment by afonsosantos** [comment]
You can also use SFTP, go into the playlists directory, download the playlist file relative to the playlist you want, and then use a tool like [Playlist Converter](http://www.playlist-converter.net/#/) to get a text file.

**Comment by MrSteelMiner** [comment]
> You can also use SFTP, go into the playlists directory, download the playlist file relative to the playlist you want, and then use a tool like [Playlist Converter](http://www.playlist-converter.net/#/) to get a text file.

Or just download the Playlist via Export button in playlist view (more→export m3u)

**Comment by afonsosantos** [comment]
@jonikane Hi!

Did you manage to get the song names? If so, you can close this issue.
