### ISSUE TITLE
Now Playing to Twitter,Facebook, or whatever

### ISSUE THREAD

**Issue by 24dubstep** [AzuraCast/AzuraCast#190]
twitter from this
https://github.com/dlnetworks/twittercast
or this
https://github.com/search?utf8=%E2%9C%93&q=twitter+icecast&type=

**Comment by treyturner** [comment]
Would love to see Discord webhook support as well.

**Comment by SlvrEagle23** [comment]
@24dubstep @treyturner The new Web Hooks feature built into AzuraCast now supports connections to the TuneIn API, Discord webhooks, Twitter posts, or posts to any user-specified URL. Try it out!

**Comment by treyturner** [comment]
Stellar work, thanks!

**Comment by ErnestPH** [comment]
> Stellar work, thanks!

How did you do it? Any instructions on how it should be done? Thanks!

**Comment by muppathimoonu** [comment]
> > Stellar work, thanks!
> 
> How did you do it? Any instructions on how it should be done? Thanks!

+1

**Comment by SlvrEagle23** [comment]
@muppathimoonu You can use the web hooks from the sidebar of each station's management page, under the "Web Hooks" link.
