### ISSUE TITLE
Liquidsoap: Consider increasing the max buffer size!

### ISSUE THREAD

**Issue by RoyalFM** [AzuraCast/AzuraCast#1900]
Howdy AzuraCast.

First of all, i love AzuraCast. Simply, friendly design and easy to work. Great work! 

**Using Docker installation method**
Yes, latest Version. v0.9.6.1. Updated 23.08.2019

**Host Operating System**
CentOS 7

**Describe the bug**
We use 15 scheduled Playlists. This works good. But here also, if we want in a scheduled Playlist, to play Jingles (seperate Playlist) - it doesnt work. 
After the playlists are running, Liquidsoaps stops after a few hours. When i get to the log files, I can see the following:
2019/08/23 12:01:51 [http_6476:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/08/23 12:01:51 [http_6476:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/08/23 12:01:51 [decoder:3] Method "MP4" accepted "/var/azuracast/stations/royalfm/media/Swiss Made/franzosisch.m4a".
2019/08/23 12:01:51 [http_6476:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!

All our music files are converted in .m4a. 

**Expected behavior**
I tried out to find out with other issues on github to findout any failures. But no success.

**Relevant Logs**
2019/08/23 12:01:51 [http_6476:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/08/23 12:01:51 [http_6476:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2019/08/23 12:01:51 [decoder:3] Method "MP4" accepted "/var/azuracast/stations/royalfm/media/Swiss Made/franzosisch.m4a".
2019/08/23 12:01:51 [http_6476:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: Chrome
 - Version: 

**Additional context**

**Comment by afonsosantos** [comment]
Hi @RoyalFM 

You can try to increase the Max Buffer in the Playlist Settings, under the tab `Source`.

**Comment by RoyalFM** [comment]
> Hi @RoyalFM
> 
> You can try to increase the Max Buffer in the Playlist Settings, under the tab `Source`.

Hi @afonsosantos could you please explain me who it is? Do you mean in Liquidsoap self or in the playlist settings, In the playlist settings I didn't found any settings. Sorry but I'm a new AzuraCaster'er ;-)

**Comment by afonsosantos** [comment]
Hey @RoyalFM that's alright! Here's a step by step guide on how to do it:

With you AzuraCast instace open, go to `Playlists` and select the remote playlist that's causing the issue. With the playlist in `Edit` mode, choose the tab `Source` and then in the `Remote Playback Buffer (Seconds)` increase the value. Note that the max is 120.

![image](https://user-images.githubusercontent.com/46262740/63629307-5683e300-c609-11e9-9d3d-3a80b9af7090.png)

Try with different values, and check the logs for that error message. If the issue remains, report back here so that we can see another solutions.

**Comment by RoyalFM** [comment]
> Hey @RoyalFM that's alright! Here's a step by step guide on how to do it:
> 
> With you AzuraCast instace open, go to `Playlists` and select the remote playlist that's causing the issue. With the playlist in `Edit` mode, choose the tab `Source` and then in the `Remote Playback Buffer (Seconds)` increase the value. Note that the max is 120.
> 
> ![image](https://user-images.githubusercontent.com/46262740/63629307-5683e300-c609-11e9-9d3d-3a80b9af7090.png)
> 
> Try with different values, and check the logs for that error message. If the issue remains, report back here so that we can see another solutions.

Hi @afonsosantos thx for the detailed step by step guide. But I don't use any Remote URL Playlists. I use only the uploaded Music. All Music files are converted in .M4A (320 Kbps).

**Comment by afonsosantos** [comment]
That's strange, because this message usually appears when using Remote URL Playlists (even I experienced them).

In this line you can see the **http** word:
`2019/08/23 12:01:51 [http_6476:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!`

That usually means that you are obtaining information from a HTTP source, just like a remote playlist. Are you sure that no other playlist is set to Remote URL, even if you don't use it?

**Comment by RoyalFM** [comment]
> That's strange, because this message usually appears when using Remote URL Playlists (even I experienced them).
> 
> In this line you can see the **http** word:
> `2019/08/23 12:01:51 [http_6476:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!`
> 
> That usually means that you are obtaining information from a HTTP source, just like a remote playlist. Are you sure that no other playlist is set to Remote URL, even if you don't use it?

Yes @afonsosantos I'm sure that I only use files and no URL remote playlist. Also Liquidsoap interrupts after few hours if I have this failure. I also disabled Streamer/DJs and Music wish.

**Comment by RoyalFM** [comment]
Also strange is the song playback timeline. I only use scheduled playlists (24h) and uploaded Music. 
![image](https://user-images.githubusercontent.com/54402477/63641376-84bafe80-c6ad-11e9-9f6b-6452f93664fe.png)

**Comment by afonsosantos** [comment]
Not sure what's the cause. When `Stream Offline` appears are your station playing music?

**Comment by lramilo** [comment]
When playing a remote URL playlist, I found a workaround using a dummy output, manually adding this to Liquidsoap configuration:

`output.dummy(id="DUMMY_STREAM_OUTPUT", fallible=true, playlist_live)`

Details are explained on [#3701](https://github.com/AzuraCast/AzuraCast/issues/3701)
