### ISSUE TITLE
Host system restart and package updates (Ubuntu)

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1904]
Hi, 

from time to time I see in the console of the Azuracast host machine (Ubuntu) that I need to reboot the server, which I always do via `sudo reboot`. The Azuracast containers seem to be configured with a Docker restart policy that allows them to restart automatically after reboot. It works well.  

After reboot I still see that updates are available (see picture). Does Azuracast recommend updating these packages? I can imagine the the fresh versions of Azuracast have a dependency on the fresh versions of these packages. Is this the case? What command would you recommend to update these packages? FYI: we use the recommended DO Ubuntu server to host Azuracast. 

![image](https://user-images.githubusercontent.com/28865986/63637194-16107d80-c67a-11e9-9e7b-663c4bf9b190.png)

**Comment by afonsosantos** [comment]
Well, whenever I see that packages can be updated, I always update them, even with AzuraCast running. Sometimes, when Docker is updating, the containers will restart. Said that, I never had any problems running the updates.

**Comment by gammaw** [comment]
@afonsosantos thanks! I just updated all packages and the radio is still working :)

**Comment by afonsosantos** [comment]
That's nice to hear!

If your problem is solved and you don't have any more questions, this issue can be closed.
