### ISSUE TITLE
Incorrect Link to Slack on Documentation

### ISSUE THREAD

**Issue by JDBlackman** [AzuraCast/AzuraCast#1906]
Just a small little documentation bug.

Link on the Help page (https://www.azuracast.com/help/#github-issues) links to "https://www.azuracast/com/slack"

**Comment by afonsosantos** [comment]
Created a Pull request to fix that typo [here ](https://github.com/AzuraCast/azuracast.com/pull/29)

**Comment by afonsosantos** [comment]
The pull request was merged, you can close the issue.
