### ISSUE TITLE
Cannot able to hear audio on admin and profile page 

### ISSUE THREAD

**Issue by janoo87** [AzuraCast/AzuraCast#1908]
i recently installed Azuracast 

after create Radio i upload the music on music list and default playlist 

not able to hear audio on admin page and profile page  track is playing but no audio

please help 
http://74.208.27.45/public/paklivefm_radio1

**Comment by MrSteelMiner** [comment]
The stream is running on http://74.208.27.45:8000/radio.mp3
Try to enable the web proxy.

**Comment by MrSteelMiner** [comment]
The stream is running on http://74.208.27.45:8000/radio.mp3. But the connection times out. That could mean that icecast isn't running or a firewall protects access to port 8000. Please check the icecast logs and if you are unsure, post it here.

General question: Have you tried to restart AzuraCast or the whole server?

**Comment by janoo87** [comment]
hi sir thanks for reply 

Please tell me how and where to check the icecast logs?

Have you tried to restart AzuraCast or the whole server?

yes i did that but no result

**Comment by afonsosantos** [comment]
@janoo87 Hi!

To check the logs in AzuraCast, you can use the sidebar menu, when on a Station Profile, and within the **`Utilities`** section, select **`Log Viewer`**. There you can see the logs for the differente services (in this case, you must check the **IceCast Logs**).

**Comment by janoo87** [comment]
hi thanks all 

i just removed everything and re install it by reinstall server image and now running very good with voice

thanks

**Comment by afonsosantos** [comment]
That's nice to hear, if you don't have any more questions, you can close this issue now.
