### ISSUE TITLE
Cannot longer update metadata via admin page.

### ISSUE THREAD

**Issue by stemvantwente** [AzuraCast/AzuraCast#1910]
Installation method
"Traditional" installation method" (v0.9.6.2,)

Host OS (for Docker installations)
Ubuntu 1804 (VPS)

Describe the bug:
Cannot longer update Metadata via admin page, see screenshots.

![icecast metadata 1](https://user-images.githubusercontent.com/44572433/63714487-312de980-c842-11e9-896b-15c902c17ffb.jpg)
![icecast metadata 2](https://user-images.githubusercontent.com/44572433/63714500-37bc6100-c842-11e9-9bfe-4f0fc1b774c3.jpg)

**Comment by stemvantwente** [comment]
Found a way to update:

For anyone who needs this :)

Login to your'e azuracast webpage and use:

http://IP/radio/PORT/admin/metadata?mount=/MOUNTPOINT NAME&mode=updinfo&song=Here the text you need in the metadata

Greets

**Comment by SlvrEagle23** [comment]
@stemvantwente You can also still visit `http://IP:PORT/admin` directly to do administrative functions even if the "Proxy Web Radio" setting is turned on.

**Comment by stemvantwente** [comment]
@SlvrEagle23 If I try to update metadata true List Mountpoints at the admin page, then I get page 404 not found. And if I use the method I mentioned in previous post then it works.
