### ISSUE TITLE
No "playing next" data when using playlist in "jingle mode" 

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#1911]
**Using Docker installation method**

**Host Operating System**
Ubuntu 16.04

**Describe the bug:**
When using multiple playlists and playlist in jingle mode, it blocks the next song data. The "playing next" display nothing when the jingle is up coming. This can cause an error when using the API
Maybe the solution for that is to display the next song that comes right after the jingle instead of empty data.

**Comment by afonsosantos** [comment]
That's a known issue, I also face it. How long are the files in the `Jingle Mode` playlist? The duration is what's causing the issue.
