### ISSUE TITLE
How to connect Azuracast with sam Broadcaster

### ISSUE THREAD

**Issue by janoo87** [AzuraCast/AzuraCast#1912]
can anyone tell me how to connect Azuracast with sam broadcaster

**Comment by rolradio** [comment]
https://www.azuracast.com/help/streaming_software.html#butt-broadcast-using-this-tool

**Comment by janoo87** [comment]
hi sir 

it gives me error please see attachements 
https://prnt.sc/oyb8a0
https://prnt.sc/oyb8v9

**Comment by Inuyashagcn** [comment]
I also had problems like this and my solution was to use Shoutcast v1, fill in the "Server IP" and "Server Port" fields with the IP and Port of your server and enter the password as _user:password_ in the "Password" field, the the rest of the "Station Details" fields may be blank, you shouldn't have a bigger problem with that, Regards...

**Comment by afonsosantos** [comment]
@janoo87 Hi!

Is your issue solved? If so, you can close this issue.

**Comment by williambatson** [comment]
connecting usually seems OK on mine with SAM which I only use for testing purposes - but finding the secret to getting the statistics relays to sync is still an issue - anyone have details on how and what info is needed for this?

**Comment by Inuyashagcn** [comment]
To configure statistics relays in SAM Broadcaster, if your radio is set to Icecast2, add a relay that type and configure using your server's IP, the base port of your radio (the one that connects your listeners, like 8000, 8010, etc) and the passwords can be found in the "Profile" section on the right side in the "Broadcasting Service" section, there will appear 3 passwords, "Admin Password", "Source Password" and Relay Password, in SAM Broadcaster use "Admin Password "," Source Password "is used in RadioBoss
In the case that you have configured Shoutcast2, I don't have much idea, but it must be something very similar.
