### ISSUE TITLE
Connetion to Streamer/DJs Port 8005 not working ? 

### ISSUE THREAD

**Issue by MrMarioMichel** [AzuraCast/AzuraCast#1913]
**Using Docker installation method**
Just download the compose file via the ./docker.sh and changed ports(HTTP, HTTPS, Station Ports). 

**Host Operating System**
Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-58-generic x86_64)

**Describe the bug**
I tried the create a user in the Stream User Tab (/station/1/streamers). Downloaded BUTT and tried to connect but I was not able. Then I saw that docker is not listening on those ports (8005,8006). Is it now a different one? All I can see now when I use the URL given to my by the GUI is this and I have no idea of the login informations of this...
![grafik](https://user-images.githubusercontent.com/30075959/63763119-5feca400-c8c4-11e9-87b3-30992cafbd63.png)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/30075959/63762939-071d0b80-c8c4-11e9-9def-33e0c7292621.png)

If you need more informations please let me know exactly where to find them

**Comment by MrSteelMiner** [comment]
Which Ports did you changed? In general it's not a good idea to change those ports because AzuraCast generates the port numbers itself.

Generell würde ich die Ports von Azura nicht anfassen :D Da reagiert das System ein bisschen seltsam drauf. Ansonsten:
- Wie sieht deine butt config aus?
- Was hast du alles an der Konfiguration innerhalb der Station geändert?
- Sind irgendwelche Firewalls an?
- Hast du den gesamten Server mal neu gestartet? (reboot tut gut und so)

PS: Die Zensierung ist ein bisschen überflüssig, wenn man sowohl in der Adresszeile des Browsers, als auch im butt-Fenster die IP sieht ;)

**Comment by MrMarioMichel** [comment]
@MrSteelMiner 

I needed to chnage it tue to other containers using in the range of 8000-8599 some ports...

Config passt ist na ned viel zu machen ...
Nur user erstellt...
Bei der Firewall ist alles offen 
Ja mehr mals

PS : Sind interne Addresse die man sieht und alles andere sind externe Adressen ;)

**Comment by MrSteelMiner** [comment]
> I needed to chnage it tue to other containers using in the range of 8000-8599 some ports...
Eventuell sind die Ports noch belegt.

> Config passt ist na ned viel zu machen ...
Trotzdem würde es helfen, die zu sehen. Der Fehler liegt meist im Detail. Zum Beispiel vergessen viele, dass der Mountpoint `/` gesetzt sein muss. Dazu kommt, dass viele den obligatorischen Restart im Fall der Fälle vergessen. Könntest du deshalb auch einmal die Icecast-Config & Logs posten? Zu finden in der Station unter Tools/Log Viewer. Darin bitte beide Icecast-Logs und die Config posten. (Bitte Zugangsdaten, etc. zensieren :)

> PS : Sind interne Addresse die man sieht und alles andere sind externe Adressen ;)
Ahhh okay ;)


English:
I asked him for the icecast logs and config.

**Comment by MrSteelMiner** [comment]
> I needed to chnage it tue to other containers using in the range of 8000-8599 some ports...

Eventuell sind die Ports noch belegt? Denke ich aber eher nicht, da sonst auch der Web Proxy nicht funktionieren würde.

> Config passt ist na ned viel zu machen ...

Trotzdem würde es helfen, die zu sehen. Der Fehler liegt meist im Detail. Zum Beispiel vergessen viele, dass der Mountpoint `/` gesetzt sein muss. Dazu kommt, dass viele den obligatorischen Restart im Fall der Fälle vergessen. Könntest du deshalb auch einmal die Icecast-Config & Logs posten? Zu finden in der Station unter Tools/Log Viewer. Darin bitte beide Icecast-Logs und die Config posten. (Bitte Zugangsdaten, etc. zensieren :)

> PS : Sind interne Addresse die man sieht und alles andere sind externe Adressen ;)

Ahhh okay ;)


English:
I asked him for the icecast logs and config. And I asked him to check his local configuration (butt config).

**Comment by MrMarioMichel** [comment]
@MrSteelMiner 

I just checked my docker and saw this... Is that okay ?

![grafik](https://user-images.githubusercontent.com/30075959/63771276-25403700-c8d7-11e9-9afd-5ce56c7428d4.png)

Here is the BUTT conf (also tested with port 8005)

![grafik](https://user-images.githubusercontent.com/30075959/63771407-65071e80-c8d7-11e9-88fd-77b58c2d4f74.png)


[Icecast-Konfiguration.txt](https://github.com/AzuraCast/AzuraCast/files/3546089/Icecast-Konfiguration.txt)
[Icecast Fehlerprotokoll.txt](https://github.com/AzuraCast/AzuraCast/files/3546080/Icecast.Fehlerprotokoll.txt)
[Icecast Zugriffsprotokoll.txt](https://github.com/AzuraCast/AzuraCast/files/3546081/Icecast.Zugriffsprotokoll.txt)

BTW thanks for the help!

**Comment by MrSteelMiner** [comment]
Looks like AzuraCast is opening these ports so it seems to be fine.
Icecast is working fine. Your broadcasting port is 8005. Please also attach the liquidsoap log.

**Comment by MrMarioMichel** [comment]
There you go @MrSteelMiner 

[Liquidsoap Log.txt](https://github.com/AzuraCast/AzuraCast/files/3546299/Liquidsoap.Log.txt)

**Comment by MrSteelMiner** [comment]
For me, it looks like AzuraCast is working well since restart at 02:18:31 this night.

**Comment by MrMarioMichel** [comment]
Okay many thanks @MrSteelMiner for your time and effort !

**Comment by MrSteelMiner** [comment]
Maybe the problem is your client. Maybe butt cannot call outside your computer. The logs seem to be fine, so I would not say, it's a server issue.
