### ISSUE TITLE
Encoding issue when activating/deactivating Public Pages

### ISSUE THREAD

**Issue by ivellios1988** [AzuraCast/AzuraCast#1915]
There's a problem with character encoding when trying to activate/deactivate Public Pages - encoding is messed up in Polish and possibly all other non-English installations.

See the screenshot. It should say "Włączyć publiczne strony?" (Enable public pages?). What it actually says is very hard to read, though...

![Bez tytułu](https://user-images.githubusercontent.com/13646017/63768319-2f126c00-c8d0-11e9-8806-f2cf761208e8.png)

**Comment by Vaalyn** [comment]
Closing as fixed. Can't see this happening in the current version anymore.
