### ISSUE TITLE
500 A new entity was found through the relationship 'App\Entity\StationPlaylistMedia#media' that was not configured to cascade persist operations for entity

### ISSUE THREAD

**Issue by webservichost** [AzuraCast/AzuraCast#1916]
Today an azuracast update has been released that allows you to use ftp through a program.
I did the tests and now presents the following error while trying to run the directory check media folder.

500
A new entity was found through the relationship 'App \ Entity \ StationPlaylistMedia #media' that was not configured to cascade persist operations for entity: App \ Entity \ StationMedia @ 000000007092911a000000001c556963. To solve this issue: Either explicitly call EntityManager # persist () on this unknown entity or configure cascade persist association in the mapping for example @ManyToOne (.., cascade = {"persist"}). If you can't find out which entity causes the problem implement 'App \ Entity \ StationMedia #__ toString ()' to get a clue.
ORMInvalidArgumentException.php: 102

**Comment by It4lik** [comment]
Hi, 

Same here but we **did NOT update** Azura. We also get the error when checking the media folder.
This error pops out **after we modified the music library** (adding some tracks/folders, and move/rename/remove existing tracks/folders). 

The media folder check is loading during a while (~30 seconds, we got a lot of music), and then we got this : 
```
A new entity was found through the relationship 'App\Entity\StationPlaylistMedia#media' that was not configured to cascade persist operations for entity: App\Entity\StationMedia@0000000031f2431f0000000045f96679. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'App\Entity\StationMedia#__toString()' to get a clue.
ORMInvalidArgumentException.php : 102 
```

I tried to fully restart Azura (I'm using a non-conventional setup : Azura is running as Docker Swarm stack) and then I got the same error, with plural this time : 
```
Multiple non-persisted new entities were found through the given association graph: * A new entity was found through the relationship 'App\Entity\StationPlaylistMedia#media' that was not configured to cascade persist operations for entity: App\Entity\StationMedia@00000000677ab66b0000000052bf0253. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'App\Entity\StationMedia#__toString()' to get a clue. * A new entity was found through the relationship 'App\Entity\StationPlaylistMedia#media' that was not configured to cascade persist operations for entity: App\Entity\StationMedia@00000000677ab6750000000052bf0253. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'App\Entity\StationMedia#__toString()' to get a clue.
ORMInvalidArgumentException.php : 105 
```

**Buuuuut, now it's working. I did nothing**. Just the time to search for an existing issue and create this message, it's fully working again without any error (it was bugged for nearly 4 hours).

**Comment by It4lik** [comment]
I noticed that the performance/statistics job ran just before the error disappeared. These two may be related.

**Comment by SlvrEagle23** [comment]
@webservichost @It4lik It appears this has to do with the fact that station media was configured to persist its relationships with playlists, which are now cleared through a different method.

If you had deleted a track from your media that was still associated with a playlist at the time it was deleted, this was the most likely cause of the problem, but could've been caused by other sync-related issues.

I pushed up a small fix that should improve on this, or at the very least tell you specifically what track is causing the problem, so you can do some diagnostics of your own (i.e. if you know you just deleted that file, that can help explain the problem).

**Comment by It4lik** [comment]
@SlvrEagle23 Nice ! Yep, after a deletion but also after moving a track I think.
