### ISSUE TITLE
Bug in "Edit Media"

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#1918]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 16.04

**Describe the bug:**
When trying to edit the song file name, it leads to error 500 and moves the file to new a folder created by the system. Now it's impossible to move back the song to the "root" music files folder
Actually it's impossible to move any song from any folder to the "root" location of the music files.

**Comment by Vaalyn** [comment]
Please add some more information about how to reproduce the error. A step-by-step list would be helpful for us so that we can take the exact exactions that you did when this error happened.

**Comment by eranwo** [comment]
Manage station >> Music Files >> Edit Media 
under: "File Name"
change the "mp3" file name to what ever you want >> Save Changes
 - Error 500 Page -
File not found at path: "The name you changed".mp3
Filesystem.php : 389

**Comment by SlvrEagle23** [comment]
@eranwo The fix should be available now in the AzuraCast code. Thanks @Vaalyn for figuring it out. :)
