### ISSUE TITLE
How to reset or retrieve admin password

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#192]
Hello,

How can i retrieve or reset admin password?

**Comment by SlvrEagle23** [comment]
@surihost If you can access the database (either directly or via SSH tunnel) you can update the password for the user account. Passwords are hashed using PHP's native `password_hash` functionality, so resetting it to something generated by a [http://www.passwordtool.hu/php5-password-hash-generator](password generator) will work as a temporary measure. Of course it's important to not use any password run through a third-party site like that as your permanent password, so be sure to change it as soon as you log in.

**Comment by surihost** [comment]
I dont know how i am unable t login to my admin account.
I have acces to ssh, where can see or change the password for admin?
The full path please ( i am on normal ubuntu installation)

**Comment by SlvrEagle23** [comment]
@surihost Wait, are you talking about the SSH `azuracast` account? Or the admin user for the web interface?

**Comment by surihost** [comment]
the admin user for the web

**Comment by SlvrEagle23** [comment]
@surihost Please update to the latest version of the codebase (`./update.sh`) and execute the following command:

```
php /var/azuracast/www/util/cli.php azuracast:account:reset-password YOURLOGINEMAIL
```

Replace "YOURLOGINEMAIL" with the e-mail address you use to log in to the web panel.

This will generate a new temporary password you can use to log in.

**Comment by surihost** [comment]
I get this:
Account not found.

**Comment by SlvrEagle23** [comment]
@surihost ...did you delete the account? That suggests there's no account in the system with that e-mail address at all.

**Comment by surihost** [comment]
No, this morning i logged in with the same account.
Strange :(

**Comment by SlvrEagle23** [comment]
@surihost Try enclosing the e-mail address in double-quotes? i.e. "youremailaddress@here.com"

**Comment by surihost** [comment]
Didn't helped, i had to reinstall all over again :(

**Comment by SlvrEagle23** [comment]
@surihost Sorry for the trouble there. The account recovery option should help anyone with similar issues, though I'm not sure why your account failed to be located, so I'm closing this ticket for now.
