### ISSUE TITLE
Nach updaten von azuracast eror redis1

### ISSUE THREAD

**Issue by DjSanSanich** [AzuraCast/AzuraCast#1920]
Please help.
here is the error:

Docker is already installed! Continuing...
Docker Compose is already installed! Continuing...
Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Starting azuracast_stations   ... done
Starting azuracast_influxdb_1 ... done
Starting azuracast_redis_1    ... error

ERROR: for azuracast_redis_1  Cannot start service redis: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"write sysctl key net.core.somaxconn: open /proc/sys/net/core/somaxconn: no such file or directory\"": unknown

ERROR: for redis  Cannot start service redis: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"write sysctl key net.core.somaxconn: open /proc/sys/net/core/somaxconn: no such file or directory\"": unknown
ERROR: Encountered errors while bringing up the project.
azuracast_mariadb_1 is up-to-date
azuracast_influxdb_1 is up-to-date
azuracast_stations is up-to-date
Starting azuracast_redis_1 ... error

**Comment by MrSteelMiner** [comment]
try the update with:
`./docker.sh update-self && echo "y" | ./docker.sh update`

**Comment by DjSanSanich** [comment]
> if not already done, try the update with:
> `./docker.sh update-self && echo "y" | ./docker.sh update`

Unfortunately that did not help! :(
