### ISSUE TITLE
Dynamic playlist

### ISSUE THREAD

**Issue by drno88** [AzuraCast/AzuraCast#1921]
Good day.
Is it possible to add a folder to the playlist?
I see that when a folder is added to the playlist, it directly enters the files there.
I plan to copy files by rsynk in automatic mode and I need the playlist to “pick up”.
Any option how to do this?
Thank you in advance and thank you for your work.

**Comment by afonsosantos** [comment]
@drno88 Hi!

This is not possible currently in AzuraCast, but it's already requested in the AzuraCast Feature Upvote page. You can go there and vote on the feature.

**Comment by drno88** [comment]
Ok, thanks for the answer.
I see that in the web interface you can select a folder, select a playlist. He will scan and change the playlist.
I see that it is possible to update the playlist via api, but unfortunately I am weak in programming.
Could you tell me how to send a request to "add folder" to the playlist from the console?

**Comment by afonsosantos** [comment]
After taking a look at the API endpoints available [here](https://www.azuracast.com/api/index.html) I think you can't do that via the API, only using the Web Interface.
