### ISSUE TITLE
Zombie Processes - pure_ftpd

### ISSUE THREAD

**Issue by afonsosantos** [AzuraCast/AzuraCast#1923]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu Server 18.04

**Describe the bug**
This bug is not affecting the functionality of AzuraCast (so far).
The process `pure_ftpd` is becoming zombie.

**To Reproduce**
Login to the server's console and check the message, under the server usage columns.
This command lists those (at least on my host):
```
ps axo stat,ppid,pid,comm | grep -w defunct
```

**Relevant Logs**
Didn't find one so far.

**Screenshots**

![image](https://user-images.githubusercontent.com/46262740/63816682-09697f00-c931-11e9-8967-d7d590fcd527.png)

**Device(s):**
 - Device: PC
 - OS: Windows 10

**Comment by Vaalyn** [comment]
This may have something to do with `runit` and the zombie process reaping. See [this](https://forums.docker.com/t/what-the-latest-with-the-zombie-process-reaping-problem/50758) issue from the Docker community forums and [this](https://github.com/phusion/baseimage-docker/issues/164) issue from the phusion baseimage.
