### ISSUE TITLE
create new page internal azuracast

### ISSUE THREAD

**Issue by webservichost** [AzuraCast/AzuraCast#1925]
I'm new with this panel and wanted to have a way to integrate with the designer of my site as colors and the possibility to create new internal pages in azuracast, but I'm lost.
Does anyone know how to do? Example, I wanted to put a page with code of a player and in this player retrieve the data of the registered station, only I can not at all.

**Comment by Vaalyn** [comment]
Hello, would you mind elaborating a bit on what exactly you want to do?

Do you want to create a custom player that you put on your existing website or do you want to customize the look of our player widget?
You can customize the players look by adding custom CSS in the `System Administration` -> `Custom Branding` -> `Custom CSS for Public Pages`. You can play around with CSS changes in your browsers Developer Console on the public page. As a starting point you can use these classes `.embed .stations`. On the custom branding page you can also add CSS for internal pages.

What kind of internal pages do you want to add to AzuraCasts internal ones?

**Comment by webservichost** [comment]
For example, can I put autoplay?
Another question is, I need to create new internal pages, example I want to create an option in the azuracast menu that leads to a page where I have embed codes from other players.
My doubt is to create new internal pages. I create the option in the menu and point to the pages. There is no manual for this, nor a tutorial in which I can for example create a page and retrieve station data like ip and port and etc .. I have idea to share other models of players to the staff.

**Comment by SlvrEagle23** [comment]
@webservichost This is possible via our plugin architecture, but it's not particularly well documented at the moment. We haven't had a ton of interest in our plugin architecture outside of a select few users.

**Comment by webservichost** [comment]
Thanks for the answer.
I really enjoyed the project and I am very interested in contributing to the community. But at the moment I have this difficulty. I can't create new internal pages with data that azuracast itself offers. For example, I want to put new players, so far so good because I have them ready, but the player needs the ip and port data generated in azuracast and in this issue that I am having problems, I can not retrieve this data.

**Comment by Vaalyn** [comment]
Regarding autoplay, you can do this via custom JavaScript on the `Custom Branding` page.
But be warned that browsers are trying to stop autoplaying media from being a thing so it can be that it stops working. Take a look at the response to #1355 for a small snippet that should get this working for you.

On the topic of new internal pages you would need to write a plugin like mentioned.
Currently AzuraCast is not intended to be a CMS so it is not possible to add custom pages internally or externally through the GUI or CLI.

**Comment by webservichost** [comment]
Many thanks for the reply
put in a custom tag the code

$ (function () {
     $ ('. btn-audio: first'). click ();
});

And yet autoplay didn't work on any public page.

**Comment by Vaalyn** [comment]
I've checked why this isn't working and the snippet is from before the player was reworked so the class is not the same anymore. I've quickly tried to adapt it to the new class/element but couldn't get it to work. From that brief testing I'm not sure if the click is not triggering the play because the browser prevents it or if it's because of the vue.js player itself.

If anyone has this working on the newest version of AzuraCast please let us know.

**Comment by SlvrEagle23** [comment]
@Vaalyn @webservichost Basically all modern browsers deliberately prevent this behavior. There's a specific subset of things that can't happen without actual user interaction, including popping up a new window and playing audio. There's nothing we can do about this, as users tend to _like_ not having autoplaying audio on their web pages, and so every browser wants to implement it.
