### ISSUE TITLE
metadata from songs being streamed to the server doesn't seem to be working

### ISSUE THREAD

**Issue by darkjedeye** [AzuraCast/AzuraCast#193]
I am using the shoutcast serer, and it doesn't seem to send metadata through... are one of my settings wrong? do i need to update the docker?

**Comment by SlvrEagle23** [comment]
@darkjedeye Can you be a little more specific in describing the problem? Are all songs not sending any metadata over, or just one or two songs? Where are you looking for metadata, inside AzuraCast or from ShoutCast itself?

**Comment by darkjedeye** [comment]
None of the songs I steam show any details on the stations public page, or the shout cast server. Just trying to figure out if its and issue with ports on my server, or incorrect setting or even my system.... I use mixxx 2.2 and Sam Broadcaster for testing, and neither worked. Have azuracast running on shout cast.

**Comment by SlvrEagle23** [comment]
@darkjedeye That probably has something to do with your DJ software itself, not the LiquidSoap/ShoutCast stack on the server. If you're connecting to LiquidSoap (which you should be by default on newer Azura installs), you can connect using the IceCast protocol and it will transcode everything to ShoutCast for you.

**Comment by darkjedeye** [comment]
OK, so it pulls properly in winamp and when i log onto the site with the 8000 port, but not in azuracast public/stationnmae space.... is there anyway to correct that?

**Comment by darkjedeye** [comment]
not to worry... cleared cache and refreshed, and now it works
