### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ProxyPing** [AzuraCast/AzuraCast#1930]
Docker is already installed! Continuing...
Docker Compose is already installed! Continuing...
Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Starting azuracast_mariadb_1  ... error
Starting azuracast_redis_1   ...
Starting azuracast_influxdb_1 ...
Starting azuracast_stations   ...

ERROR: for azuracast_mariadb_1  Cannot start service mariadb: OCI runtime create failed: container_linux.go:345: starting container process caused "process_lStarting azuracast_influxdb_1 ... error
4bb19fa68575f6e873e1550e\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

Starting azuracast_redis_1    ... error
_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/25a1a9d073200b781f38e5efadcd06392ccab98e5c3cb5f2286d35f0ff53b0fb\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for azuracast_redis_1  Cannot start service redis: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/fd9c7b366b9c880a1c4fc9c3323097005f1d614392d9Starting azuracast_stations   ... error

ERROR: for azuracast_stations  Cannot start service stations: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/c09999ef2bd466d2601c36cf120fa70aac90e66dd8c7b9800456b4065a74b241\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for mariadb  Cannot start service mariadb: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/81d4458d792f3ac784f8bad510f8c6144aceedd64bb19fa68575f6e873e1550e\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for influxdb  Cannot start service influxdb: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/25a1a9d073200b781f38e5efadcd06392ccab98e5c3cb5f2286d35f0ff53b0fb\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for redis  Cannot start service redis: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/fd9c7b366b9c880a1c4fc9c3323097005f1d614392d9ee846c982437f96425f3\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for stations  Cannot start service stations: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/c09999ef2bd466d2601c36cf120fa70aac90e66dd8c7b9800456b4065a74b241\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.
Starting azuracast_influxdb_1 ... error
Starting azuracast_redis_1    ...
Starting azuracast_mariadb_1  ...
Starting azuracast_stations   ...

Starting azuracast_redis_1    ... error
_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/25a1a9d073200b781f38e5efadcd06392ccab98e5c3cb5f2286d35f0ff53b0fb\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for azuracast_redis_1  Cannot start service redis: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linuxStarting azuracast_mariadb_1  ... error
ee846c982437f96425f3\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for azuracast_mariadb_1  Cannot start service mariadb: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/81d4458d792f3ac784f8bad510f8c6144aceedd6Starting azuracast_stations   ... error

ERROR: for azuracast_stations  Cannot start service stations: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/c09999ef2bd466d2601c36cf120fa70aac90e66dd8c7b9800456b4065a74b241\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for influxdb  Cannot start service influxdb: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/25a1a9d073200b781f38e5efadcd06392ccab98e5c3cb5f2286d35f0ff53b0fb\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for redis  Cannot start service redis: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/fd9c7b366b9c880a1c4fc9c3323097005f1d614392d9ee846c982437f96425f3\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for mariadb  Cannot start service mariadb: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/81d4458d792f3ac784f8bad510f8c6144aceedd64bb19fa68575f6e873e1550e\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for stations  Cannot start service stations: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/c09999ef2bd466d2601c36cf120fa70aac90e66dd8c7b9800456b4065a74b241\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.
root@899 /var/azuracast/www # docker-compose logs -f
Attaching to azuracast_stations, azuracast_redis_1, azuracast_mariadb_1, azuracast_influxdb_1
azuracast_redis_1 exited with code 126
azuracast_mariadb_1 exited with code 126
azuracast_stations exited with code 126
azuracast_influxdb_1 exited with code 126
root@899 /var/azuracast/www # docker.s
docker.s: command not found
root@899 /var/azuracast/www # docker.sh
docker.sh: command not found
root@899 /var/azuracast/www # bash docker.sh
root@899 /var/azuracast/www # bash docker.sh
root@899 /var/azuracast/www # ./docker.sh
root@899 /var/azuracast/www # ./docker.sh  update
Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Removing azuracast_stations   ... done
Removing azuracast_redis_1    ... done
Removing azuracast_mariadb_1  ... done
Removing azuracast_influxdb_1 ... done
Removing network azuracast_default
azuracast_www_data
azuracast_tmp_data
Creating network "azuracast_default" with the default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_www_data" with default driver
Creating azuracast_stations ...
Creating azuracast_mariadb_1 ...
Creating azuracast_redis_1    ... error
Creating azuracast_influxdb_1 ...

ERROR: for azuracast_redis_1  Cannot start service redis: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/d4c7cf6293860b6ceedc869657b04346109954f37dfa1d36afa4064a4fb7e0bf\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown
^CERROR: Aborting.
Starting azuracast_influxdb_1 ...
Starting azuracast_redis_1    ...
Creating azuracast_mariadb_1  ... error
Creating azuracast_stations   ...

ERROR: for azuracast_mariadb_1  Cannot create container for service mariadb: Conflict. The container name "/azuracast_mariadb_1" is already in use by containCreating azuracast_stations   ... error

ERROR: for azuracast_stations  Cannot create container for service stations: Conflict. The container name "/azuracast_stations" is already in use by container "04f33a1170185f59dd53e60bd9dfa97d5e249ab7807d3534ce3e99b219e9a0a4". You have to remove (or rename) that container to be able to reuse that name.
^CERROR: Aborting.
^C
root@899 /var/azuracast/www # ^C
root@899 /var/azuracast/www # ^C
root@899 /var/azuracast/www # ^C
root@899 /var/azuracast/www # ./install.sh
Use Docker installation method? (Recommended) [Y/n] y
Docker is already installed! Continuing...
Docker Compose is already installed! Continuing...
Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Starting azuracast_mariadb_1 ...
Starting azuracast_influxdb_1 ... error
Starting azuracast_stations   ...
Starting azuracast_redis_1    ...

ERROR: for azuracast_influxdb_1  Cannot start service influxdb: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/10278d5a9c224be7b38243d1c3ebdc3cb92b25Starting azuracast_redis_1    ... error
Starting azuracast_mariadb_1  ... error
ERROR: for azuracast_redis_1  Cannot start service redis: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/d4c7cf6293860b6ceedc869657b04346109954f37dfa1d36afa4064a4fb7e0bf\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for azuracast_mariadb_1  Cannot start service mariadb: OCI runtime create failed: container_linux.go:345: starting container process caused "process_lStarting azuracast_stations   ... error
938251eed288cb8631729e88\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for azuracast_stations  Cannot start service stations: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/6657150df97142a08c3b91b66bb98e2a7c9f1e23561deb087ca86d4f7aa14230\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for influxdb  Cannot start service influxdb: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/10278d5a9c224be7b38243d1c3ebdc3cb92b25faac64bc5d35a9582acb18c89d\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for redis  Cannot start service redis: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/d4c7cf6293860b6ceedc869657b04346109954f37dfa1d36afa4064a4fb7e0bf\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for mariadb  Cannot start service mariadb: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/3d71d70926817850aa9065d8b65bc024e003edb8938251eed288cb8631729e88\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for stations  Cannot start service stations: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/6657150df97142a08c3b91b66bb98e2a7c9f1e23561deb087ca86d4f7aa14230\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.
Starting azuracast_influxdb_1 ... error
Starting azuracast_redis_1    ...
Starting azuracast_mariadb_1  ...
Starting azuracast_stations   ...

ERROR: for azuracast_influxdb_1  Cannot start service influxdb: OCI runtime create failed: container_linux.go:345: starting container process caused "processStarting azuracast_mariadb_1  ... error
faac64bc5d35a9582acb18c89d\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

Starting azuracast_redis_1    ... error
inux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/3d71d70926817850aa9065d8b65bc024e003edb8938251eed288cb8631729e88\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for azuracast_redis_1  Cannot start service redis: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/d4c7cf6293860b6ceedc869657b04346109954f37dfaStarting azuracast_stations   ... error

ERROR: for azuracast_stations  Cannot start service stations: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/6657150df97142a08c3b91b66bb98e2a7c9f1e23561deb087ca86d4f7aa14230\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for influxdb  Cannot start service influxdb: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/10278d5a9c224be7b38243d1c3ebdc3cb92b25faac64bc5d35a9582acb18c89d\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for mariadb  Cannot start service mariadb: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/3d71d70926817850aa9065d8b65bc024e003edb8938251eed288cb8631729e88\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for redis  Cannot start service redis: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/d4c7cf6293860b6ceedc869657b04346109954f37dfa1d36afa4064a4fb7e0bf\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for stations  Cannot start service stations: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/vfs/dir/6657150df97142a08c3b91b66bb98e2a7c9f1e23561deb087ca86d4f7aa14230\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.

**Comment by SlvrEagle23** [comment]
@ProxyPing I have definitely not seen this particular error before.

What is your host operating system and version?

This may be caused by an outdated Docker version (which may be fixable by upgrading to a newer version), or by a web host that doesn't allow Docker on some VPS tiers, or some other issue caused by Docker itself. It doesn't appear likely to be caused by AzuraCast.

**Comment by ProxyPing** [comment]
yeah i had it run on an lxc now i have a kvm but it says me ERROR: write /var/lib/docker/tmp/GetImageBlob604914461: no space left on device
i have 50 GB of disk space

**Comment by ProxyPing** [comment]
@SlvrEagle23 and my operating system is debian 9

**Comment by RemBdev** [comment]
@SlvrEagle23 me too

**Comment by SlvrEagle23** [comment]
@ProxyPing "No space left on device" is pretty self-explanatory; it's referring to the partition it's trying to write to being full. It may be because your disk is partitioned to give that section less space, or you may be out of space in general.

@RemBdev Please be more descriptive than just saying "me too". Several errors were reported in this thread.

**Comment by RemBdev** [comment]
@SlvrEagle23 I've got errors like:

> ERROR: failed to register layer: Error processing tar file(exit status 1): write /usr/lib/python3.6/asyncio/protocols.py: no space left on device

But i've a 30GB free space on this VM. (Clean installed)

**Comment by SlvrEagle23** [comment]
@RemBdev Check how your partitions are set up on your server. Every server installation or VPS host is different, and while many will use one single giant `/` partition (which is easiest for our purposes), many will dedicate specific space to `/home` directories, and much smaller space to `/tmp` and other folders. If you're getting "no space left on device" errors, it means the particular partition you're trying to write to is full.

**Comment by RemBdev** [comment]
@SlvrEagle23 Thank you that worked for me!
