### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#1933]
**Hello!
Can anyone help me with this 500 error?
how to solve?**
System Ubuntu 18.04 x64

![image](https://user-images.githubusercontent.com/31827151/64084553-fc6ad800-cd02-11e9-8225-171c9fae2757.png)

**Comment by ErnestPH** [comment]
Should probably be related to your DO server

**Comment by Rafaelrds2017** [comment]
> Provavelmente deve estar relacionado ao seu servidor DO

Maybe not. Because everything is normal. Minus the Azuracast.

**Comment by jayhill90** [comment]
I would check the NGINX or PHP error logs. That might give you a better hint as to what's going on. https://www.azuracast.com/help/logs.html has instructions on how you can get those.

**Comment by Rafaelrds2017** [comment]
exceeded disk limit.
I increased the disk space. however the panel does not open.

the radios continue in the air. but the panel does not load.

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Jay Hill <notifications@github.com>
Enviado: Tuesday, September 3, 2019 8:05:14 PM
Para: AzuraCast/AzuraCast <AzuraCast@noreply.github.com>
Cc: Rafael Rodrigues <rafael_15silva@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [AzuraCast/AzuraCast] Error 500 (#1933)


I would check the NGINX or PHP error logs. That might give you a better hint as to what's going on. https://www.azuracast.com/help/logs.html has instructions on how you can get those.

**Comment by ErnestPH** [comment]
In your SSH, delete some files manually… that would probably help

**Comment by Rafaelrds2017** [comment]
Delete files from
audio?
I increased the space of my server. I doubled its capacity.

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: ErnestPH <notifications@github.com>
Enviado: Tuesday, September 3, 2019 8:50:03 PM
Para: AzuraCast/AzuraCast <AzuraCast@noreply.github.com>
Cc: Rafael Rodrigues <rafael_15silva@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [AzuraCast/AzuraCast] Error 500 (#1933)


In your SSH, delete some files manually… that would probably help

**Comment by Hanner72** [comment]
I have the same problem.
Yesterday evening, everything was fine and today comes the error 500.
Which and where to delete SSH?

System Ubuntu 18.04

Please help!
