### ISSUE TITLE
Syntax Error in line 247

### ISSUE THREAD

**Issue by RoyalFM** [AzuraCast/AzuraCast#1934]
**Using Docker installation method**
 Yes

**Host Operating System**
 Cent OS 7

**Describe the bug**

During the update i received the following message:
./docker.sh: Zeile 247: Syntax Fehler: Unerwartetes Dateiende.
that means Syntax Error on line 247
**To Reproduce**

**Comment by SlvrEagle23** [comment]
@RoyalFM Try re-downloading the script using:
```
./docker.sh update-self
```
