### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by fafafoya** [AzuraCast/AzuraCast#1935]
Any recommendation/suggestion/offer for Android app compatible with Azuracast?

**Comment by afonsosantos** [comment]
@fafafoya Hi!

I use [CustomRadioPlayer](https://play.google.com/store/apps/details?id=de.battlestr1k3.radionerd) when listening to my radio station on my Android phone, but you'll need to configure it manually.
If you want something made for/customized for your radio station, you can take a look at React Native, this is, if you are willing to code it by yourself. The `now_playing` API endpoint can be useful for this, e.g. getting the current song name and artist.

**Comment by fafafoya** [comment]
Hi afonsosantos!

I am looking for an open source Android App to customize for my station and I found https://github.com/fafafoya/Swift-Radio-Pro but it's for iOS. So still looking for Android.

It seems the most important part is the Player and Now Playing component.
Any developer here to help?

**Comment by jayhill90** [comment]
https://www.androidauthority.com/best-radio-apps-for-android-393884/ might have something that allows you to listen to your AzuraCast stream.

**Comment by afonsosantos** [comment]
I think @fafafoya wants to code a custom app for his own radio, but thanks for the suggestion!

**Comment by oussamatn** [comment]
Check out my issue :  #1937

**Comment by fafafoya** [comment]
> I think @fafafoya wants to code a custom app for his own radio, but thanks for the suggestion!

Exactly!

**Comment by var2611** [comment]
https://coolmic.net/

Found open source solution working on it try your side if it can help.
