### ISSUE TITLE
Where do we report typoes in documentation?

### ISSUE THREAD

**Issue by TogarUshindi** [AzuraCast/AzuraCast#1945]
Where can we submit documentation typos and edit suggestions?

Also, can we add error / question / bug tags to github issues ourselves? I can't seem to find an option in the WYSIWYG editor before submitting the issue.

The typo I found is on [this page](https://www.azuracast.com/help/faq_docker.html#customizing-docker):

> When updating (using the docker.sh utility script), it is recommended to run `./docker-sh update-self` before running `./docker.sh update`, to ensure the Docker Utility Script itself is up to date before it updates your Docker installation.

(Should be `./docker.sh` not -sh)

**Comment by afonsosantos** [comment]
@TogarUshindi Hi!

> Where can we submit documentation typos and edit suggestions?

You are welcome to edit the source files for the documentation in [this Github repo](https://github.com/AzuraCast/azuracast.com) (creating a fork, edit the mistake/typo and open a Pull Request).

> Also, can we add error / question / bug tags to github issues ourselves? I can't seem to find an option in the WYSIWYG editor before submitting the issue.

Only the repo owners can add/edit/remove the labels on issues, and not the issue creator.

**Comment by TogarUshindi** [comment]
W00T! First pull request! I AM 1337 MASTA' CODER!
