### ISSUE TITLE
create new pages

### ISSUE THREAD

**Issue by webservichost** [AzuraCast/AzuraCast#1946]
For example, can I put autoplay?
Another question is, I need to create new internal pages, example I want to create an option in the azuracast menu that leads to a page where I have embed codes from other players.
My doubt is to create new internal pages. I create the option in the menu and point to the pages. There is no manual for this, nor a tutorial in which I can for example create a page and retrieve station data like ip and port and etc .. I have idea to share other models of players to the staff.

**Comment by SlvrEagle23** [comment]
Closing as this was intended as a reply to #1925
