### ISSUE TITLE
Song History - Error 500

### ISSUE THREAD

**Issue by callumok2004** [AzuraCast/AzuraCast#1947]
**Using Docker installation method**
Yes

**Describe the bug**
Whenever I try to load the history page from the API ( https://guardi.wearebounce.net/api/station/1/history ), it gives error 500

It is the only page on the API that gives the error, and it seems to work for a split second every so often. 

**Steps to reproduce the behaviour:**
1. Go 'https://guardi.wearebounce.net/api/station/1/history''
2. See error.
(Sometimes it may load, but very rare)

**Expected behaviour**
It should open the history link showing the previous songs played on air.

**Screenshots**
https://gyazo.com/dfb2fe99b8f2a504a5634d0c96b8a3f1

**Device(s):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest stable

**Additional context**
When I load the page, and the error appears, the logs do not give any new output at all, other than the autodj logs.

**Comment by SC2Mitch** [comment]
Are you on the latest version of Azuracast?

**Comment by callumok2004** [comment]
Yes, I am on the latest version of AzuraCast

**Comment by Vaalyn** [comment]
Please include more information in you issue. Just follow the issue template for reporting bugs to us and edit this here to include that information.

Specifically interesting for us would be your AzuraCast Application Log.

**Comment by callumok2004** [comment]
The logs do not give any errors, the only error I get is when loading the webpage,

> This page isn’t working
> guardi.wearebounce.net is currently unable to handle this request.
> HTTP ERROR 500

It also does not work, when trying to use the api to get the song history

**Comment by Vaalyn** [comment]
The error 500 means "Server Error" which in most cases is something going wrong on the PHP side. This will almost always show something in the PHP logs. Please trigger the error again and then post the contents of the `AzuraCast Application Log` here which you can find in the `System Administration` -> `System Logs`.

Also please add the missing information from the issue template to this issue.

**Comment by callumok2004** [comment]
I have updated the initial message for this issue.

**Comment by callumok2004** [comment]
Any idea what is going on?

**Comment by callumok2004** [comment]
Update:
It seems to only be happening after I have this running for a bit:
```
let fetch = require('node-fetch')
  setInterval(songHistory, 180000) 
  function songHistory() {
        fetch(`https://guardi.wearebounce.net/api/station/1/history`, {
      headers: {
        Authorization: `Bearer (my auth token here)`
      }
    })
      .then(res => res.json())
      .then(json => {
```

Any ideas why this causes the error?

**Comment by Vaalyn** [comment]
Please add your `AzuraCast Application Log` to this issue like I mentioned in my last message.

You can also fetch these logs directly from the container via the cli, take a look at [this page](https://www.azuracast.com/help/logs.html#docker-installations) for that.

Make sure that the logs include a time range where the error happened so that we can see what's going on at that moment.
