### ISSUE TITLE
 ecad report

### ISSUE THREAD

**Issue by jbrunno** [AzuraCast/AzuraCast#1948]
Good morning I was wondering if you can adapt azuracast to generate reports in ecad format. and if I have as I can was doing it. I am enclosing the format ecad requires for the reports to be
![Captura de Tela 2019-09-09 às 09 10 30](https://user-images.githubusercontent.com/21052564/64533545-b3f28200-d2e1-11e9-9657-2dcd45be5d7e.png)

**Comment by Vaalyn** [comment]
This would be a new feature. Currently there is only one report for licensing reports which is SoundExchange.

For feature requests please use https://features.azuracast.com/

You should also include more information about the format and what it is used for / where.
A google search shows me it's some kind of licensing program: https://www3.ecad.org.br/eu-uso-musica/servicos-ao-cliente/Paginas/programacao-Musical.aspx

The report they expect is supposed to be in the XLSX format with their supplied template file.
It needs to contain all songs that have been played on the station.
