### ISSUE TITLE
support external mysql server

### ISSUE THREAD

**Issue by derkalle4** [AzuraCast/AzuraCast#195]
Hey,

I use to have only one mysql server instance on an different virtual server on my private environment. That's for backup purpose and performance. Please allow me to declare an own host in the env.ini.

**Comment by SlvrEagle23** [comment]
@derkalle4 I've added support for customizing the other DB connection parameters from inside `env.ini`. I don't plan on advertising these very heavily as both the traditional and Docker installers don't need them, but for your use case they'll certainly solve the problem.

```ini
db_host = localhost
db_port = 3306
db_name = azuracast
```
