### ISSUE TITLE
Azuracast on offline server

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#1950]
How to install azuracast on offline server?

**Comment by radiolize** [comment]
As AzuraCast uses Icecast, I think it's not possible to make it in offline.

**Comment by eranwo** [comment]
I can use Icecast on local network >
My question is how can i install Azuracast from source code (tar.gz file)

**Comment by SlvrEagle23** [comment]
@eranwo It is possible to operate an AzuraCast server on an offline computer with no Internet access, but it is not possible to install our recommended Docker installation without having Internet access, at least during the initial setup process.

You can download release copies of our software via the GitHub Releases page, and install those using the traditional Ansible installer, but that is not recommended, and still requires Internet access to pull down the latest packages as the server updates.
