### ISSUE TITLE
"restart to apply changes" isn't working; mountpoint config isn't updating

### ISSUE THREAD

**Issue by Simon818** [AzuraCast/AzuraCast#1951]
**Using Docker installation method**

yes
**Host Operating System**

Debian 9.9
**Describe the bug**

On only some of our stations, I'm consistently unable to "restart to apply changes", so our mountpoints are out of date. The "restart to apply" link does not stop or restart Liquidsoap, but the "restart" link under the auto-dj profile section will stop it without restarting. I can stop *and then* start Liquidsoap even though the "restart" link does not work, but the liquidsoap.liq file never gets rewritten with the changes I make, so I have to edit the config file by hand before doing this.
**To Reproduce**

1. Change or add a mountpoint on a station.
2. Click "restart to apply changes" in the sidebar.

**Expected behavior**

The configuration file should be written with the new mountpoint(s), and Liquidsoap should be restarted so that it reads this configuration. neither one appears to happen.
**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
Desktop
 - OS: 
Windows 10 (X64)
 - Browser: 
any (Chrome, Firefox)
 - Version: 

**Additional context**

This happens only with some of our stations. I'm not seeing any difference between the configurations that might cause it, but it is consistent: Some stations always restart and others never do. With the problem stations, there's no change to the Liquidsoap configuration files after I change a mountpoint, even if I stop and start Liquidsoap. I have confirmed that if I manually edit them to have the proper bitrate and mountpoint name, I can stop and start liquidsoap from the Auto-DJ section of the profile page. If I click the "stop" link, wait for the confirmation alert, and then click the "start" link, it properly restarts. If I use the "restart" link just above that, it stops but does not restart. If I use the "restart to apply changes" link, it doesn't stop or restart. I'm not sure whether these problems are related.

**Comment by SlvrEagle23** [comment]
@Simon818 When you say the restart button "doesn't work", do you mean it actually returns an error message, or it returns success but doesn't change the actual file on the filesystem?

**Comment by Simon818** [comment]
@SlvrEagle23 The only thing that visibly happens when I hit "restart to apply changes" is that the link changes to "please wait..." There's no change to the config file and nothing vital seems to stop or restart.

**Comment by Hanner72** [comment]
I also have mistakes.
I had previously wanted to change the port and when saving I had error 500. 
Since then, I can not restart.

**Comment by jonikane** [comment]
I have the same problem too.

**Comment by Simon818** [comment]
For what it's worth, I was able to edit auracast.env and uncomment the memory_limit line, changing it to something ridiculous (in this case 4096m). This may entirely address the problem; I have a huge music library that probably takes up more memory than expected, and the variable is there for a reason. I have 32gb of ram on that machine so I'm not worried about running out. I'd appreciate knowing what the recommended fix is, but this is a temporary one if nothing else, and since others are having the issue I thought it might help.

**Comment by Simon818** [comment]
Update to the update: I'm also running into execution time errors (it seems to be set to 30 seconds by default), and this is not editable in the .env. I'll hack around in the web container and see what I can figure out.

**Comment by jonikane** [comment]
same problem too

**Comment by SlvrEagle23** [comment]
@Simon818 I'm thinking the system is somehow running out of memory while trying to write playlist configuration to the flat files. How many tracks do you have in one station?

**Comment by SlvrEagle23** [comment]
@Simon818 I've updated the station restart process to optimize the memory usage, which should prevent some of the out-of-memory issues you might run into when restarting. Let me know if updating to the latest version helps.

**Comment by Simon818** [comment]
@SlvrEagle23 This was excellent news. I've been testing and it seems to be writing out new config files just fine. Some of these stations have thousands of songs, and in total the music collection is almost 800 gb, so perhaps it was just choking on it. I gave it tons of memory and now everything seems to be restarting; I'll keep you posted and let you decide if/when this should be closed.

**Comment by SlvrEagle23** [comment]
@Simon818 Excellent to hear, thank you for the update. I definitely want the "restart broadcasting" process to be as optimized as I can make it, since it's so essential to station operation.

I've also added some environment variables under the hood that will let you control other variables like the execution time. Check out the [azuracast.env](https://github.com/AzuraCast/AzuraCast/blob/master/azuracast.sample.env) file for the new options, which should help you fine-tune the installation for larger servers.

**Comment by Vaalyn** [comment]
Closing as resolved.
