### ISSUE TITLE
Error: 500 Missing data for URL segment: station_id

### ISSUE THREAD

**Issue by Hanner72** [AzuraCast/AzuraCast#1952]
**Using Docker installation method**
[Self hosted Installation](https://www.azuracast.com/install/#self-hosted-installation)

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
AzuraCast works almost perfectly, but when I click on "Mountpoints" or "System-Logs" the page opens with an error:
500
Missing data for URL segment: station_id
RouteParser.php: 91

**Screenshot**
![image](https://user-images.githubusercontent.com/25680545/64651825-a8f33b00-d422-11e9-9555-f2434dfdaa53.png)

**Device(s):**
 - Device: all over
 - OS: all over
 - Browser: all over
 - Version: Powered by AzuraCast • v0.9.6.5, #64984e4 (2019-09-10 4:19) • Docker • PHP 7.2

**Comment by kaster1980** [comment]
I also confirm this error. I get a similar problem. Checked on different operating systems: Ubuntu 16.04, Ubuntu 18.04, Debian-9-x86_64, Debian-10-x86_64. On all the above systems, the error described by the author above.
 I have been using AzuraCast for a long time, before version v0.9.6.5 there was no such error.

**Comment by SlvrEagle23** [comment]
@kaster1980 @Hanner72 This should be fixed as of the latest update. Thanks for letting us know.

**Comment by Hanner72** [comment]
`./docker.sh update`

and it works! Thanks!
