### ISSUE TITLE
Album Art missing from Now Playing

### ISSUE THREAD

**Issue by pwrj** [AzuraCast/AzuraCast#1953]
Not sure if it's a bug or not, but after an update the Album Art missing from Now Playing.

<img width="789" alt="Screen Shot 2019-09-10 at 7 39 32 PM" src="https://user-images.githubusercontent.com/7035452/64657886-52c2cf80-d403-11e9-9e33-95b1d111f914.png">

Digital Ocean - Install (Current installation type is Docker)

**Comment by SlvrEagle23** [comment]
@pwrj Try going to the URL for the album art, and see if any error messages display either in your browser or in the application log.

**Comment by pwrj** [comment]
@SlvrEagle23 - See attached.
<img width="1267" alt="Screen Shot 2019-09-11 at 2 51 43 PM" src="https://user-images.githubusercontent.com/7035452/64727266-78ed7b80-d4a6-11e9-9fc2-083467f6154d.png">

<img width="1143" alt="Screen Shot 2019-09-11 at 2 52 45 PM" src="https://user-images.githubusercontent.com/7035452/64727278-8276e380-d4a6-11e9-92f9-c0470fb1ec1f.png">

**Comment by SlvrEagle23** [comment]
@pwrj The second issue, with the log viewer, should be fixed as of the latest update.

**Comment by pwrj** [comment]
@SlvrEagle23 Thanks!

**Comment by pwrj** [comment]
@SlvrEagle23 Here's log. I see nothing wrong.
<img width="1223" alt="Screen Shot 2019-09-11 at 5 47 51 PM" src="https://user-images.githubusercontent.com/7035452/64738109-61b98880-d4bc-11e9-868e-2ed46eee968f.png">

But link to image is: https://www.iac.fm/api/station/1/art/b0445a0c9050714f5caf1a76.jpg

<img width="1178" alt="Screen Shot 2019-09-11 at 5 50 48 PM" src="https://user-images.githubusercontent.com/7035452/64738243-b78e3080-d4bc-11e9-8b61-17076078b608.png">

**Comment by Psychoses** [comment]
hi

https://www.iac.fm/api/station/1/art/b0445a0c9050714f5caf1a76.jpg
dont work

https://iac.fm/api/station/1/art/b0445a0c9050714f5caf1a76.jpg
without www. work

my 2ct

**Comment by pwrj** [comment]
@Psychoses That did it! Thank you!!
