### ISSUE TITLE
DJ cannot connect to live broadcast

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#1954]
**Using Docker installation method**
No

**Host Operating System**
Ubuntu 16.04 LTS

**Describe the bug**
AutoDJ is working but DJ cannot connect to live broadcast. There was no problem at yesterday. I updated to Azuracast at today.

**To Reproduce**
1. Go to 'Station Profile Page'
2. Click on 'Streamer/DJ Accounts'
3. Click on 'Add Streamer'
4. Fill in the form
5. Try connecting with the broadcast software.

I wrote all connection information correctly but not connected.

**Expected behavior**
DJ connect to live broadcast.

**Liquidsoap Logs**
2019/09/11 12:23:20 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/09/11 12:23:23 [lang:3] AzuraCast Raw Response: 
2019/09/11 12:23:23 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/09/11 12:23:25 [lang:3] AzuraCast Raw Response: 
2019/09/11 12:23:25 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/09/11 12:23:27 [lang:3] AzuraCast Raw Response: 
2019/09/11 12:23:27 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/09/11 12:23:30 [lang:3] AzuraCast Raw Response: 
2019/09/11 12:23:30 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/09/11 12:23:30 [lang:3] Authenticating DJ: bybilal
2019/09/11 12:23:30 [lang:3] AzuraCast DJ Auth Response: 
2019/09/11 12:23:32 [lang:3] AzuraCast Raw Response: 
2019/09/11 12:23:32 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/09/11 12:23:34 [lang:3] AzuraCast Raw Response: 
2019/09/11 12:23:34 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/09/11 12:23:36 [lang:3] AzuraCast Raw Response: 
2019/09/11 12:23:36 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/09/11 12:23:39 [lang:3] AzuraCast Raw Response: 
2019/09/11 12:23:39 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/09/11 12:23:41 [lang:3] AzuraCast Raw Response: 
2019/09/11 12:23:41 [lang:3] AzuraCast Error: Delaying subsequent requests...

**Device(s):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest

**Additional context**
Azuracast updated on 11.09.2019.

Sorry my bad English.

**Comment by radiolize** [comment]
Same problem happens to me. I'm using docker.

**Comment by SlvrEagle23** [comment]
@ogrenci01 This should be fixed for Ansible installs.

@radiolize If you're having the same issue on Docker, that's a different problem. The Docker and Ansible installations go through entirely different means of communicating back and forth between Liquidsoap and the application.

**Comment by radiolize** [comment]
Can't live broadcast me or my users. WebDJ or AudioHijack I could not able to connect even the username and password is correct I'm sure. Let me share with you logs I could found.

Liquidsoap logs:

`2019/09/11 21:08:30 [lang:3] Authenticating DJ: ivan
2019/09/11 21:08:30 [lang:3] AzuraCast DJ Auth Response: false
2019/09/11 21:10:26 [lang:3] Authenticating DJ: ivan
2019/09/11 21:10:26 [lang:3] AzuraCast DJ Auth Response: false
2019/09/11 21:10:48 [lang:3] Authenticating DJ: ivan
2019/09/11 21:10:48 [lang:3] AzuraCast DJ Auth Response: false
2019/09/11 21:10:53 [lang:3] Authenticating DJ: ivan
2019/09/11 21:10:53 [lang:3] AzuraCast DJ Auth Response: false
2019/09/11 21:11:30 [lang:3] Authenticating DJ: testt
2019/09/11 21:11:30 [lang:3] AzuraCast DJ Auth Response: false`

**Comment by radiolize** [comment]
The problem continues on me. Exactly get same logs with @ogrenci01 but I have docker installation. There are a lot of delaying subsequent request logs after false auth response.

**Comment by sheiyla** [comment]
I have the same problem as radiolize

**Comment by ogrenci01** [comment]
Hi My Friends;

I use ansible installation. It is working at now. This issue fix at last update. 

I installed a new server. It is working correctly. I use ansible installation.

Extraly, System logs view correctly at new installation. I saw this problem on already installation.
Issue: #1957

**Comment by SlvrEagle23** [comment]
@radiolize This should be reported as a new issue. The problem causing this issue has been resolved, and was specific to Ansible installations.
