### ISSUE TITLE
Possible Bug with Ubuntu Server 18.04 Subiquity Installer and Docker Snap?

### ISSUE THREAD

**Issue by TogarUshindi** [AzuraCast/AzuraCast#1961]
I just did a clean install of Ubuntu Server 18.04.3 LTS. It uses the using the live Subiquity Installer. During the installation it allows you to select from a number of snaps. One of those is Docker. I figured, why not install it now and get it out of the way?

After getting my system up and running, I followed the docker installation like before, but this time, upon entering `./docker.sh install` it said Docker and Docker Compose were already installed, but then failed to find a suitable configuration file for docker-compose.yml, asked if I was in the right directory. I was (`/var/azuracast`) It would error out three times then dump me back to the command prompt.

I wracked my brain, tried a few things, but then I did `apt install docker-compose` and retried the install process, and it worked!

So... I'm thinking, maybe Subiquity is giving a false-positive on docker-compose being installed, and it fouls up the install script. Just a hunch. I'd have to uninstall everything to play around with it, but just wanted to give you a heads up there might be a reproducible issue.

**Comment by TogarUshindi** [comment]
Still need to know what further information is needed!

**Comment by SlvrEagle23** [comment]
@TogarUshindi I'm not sure that we need more information, but I'm also not sure that there's anything we can do in particular about this issue.

Installing Docker and Docker Compose via snaps likely impacts the level of access they have to the system, and it may install a version of Docker and/or Compose that isn't actually compatible with AzuraCast's Docker infrastructure. By far, the best way to start from a barebones Ubuntu server is to let AzuraCast handle the Docker installation, which pulls the latest version of both Docker and Docker Compose from their servers.
