### ISSUE TITLE
Native Web Radio Player Plugin

### ISSUE THREAD

**Issue by fafafoya** [AzuraCast/AzuraCast#1964]
I have a Native Web Radio Player Plugin and want to display the current song playing.
I have the following ways according to the developer:

1. If you use CorsProxy: php,
- you need this setting in your php.ini: allow_url_fopen = On
- php.ini: disable_functions not have a parameter: CURL or file_get or file_put
- Firewall must be set to allow the cross-scripting

2. If you use CorsProxy: none, your server need enabled CORS: https://enable-cors.org/

3. Or you can use a CORSPROXY SERVER, p.e.: https://cors-anywhere.herokuapp.com/ Look at the documentation for more information.

How can I use these methods with Azuracast?

**Comment by lalafunn** [comment]
Hi @ogrenci01 

I have the same issue with Azuracast.
Could you tell me how you configured the settings?

**Comment by lalafunn** [comment]
How to set allow_url_fopen=on in php.ini inside Azuracast container?

**Comment by ogrenci01** [comment]
Hi @lalafunn ;

There is no need for a special configuration for Azuracast. You should edit on your hosting php.ini file for allow_url_fopen configuration. I can show you examples.

if corsproxy: "php" doesn't work, you should use other methods.
Example: corsproxy: "https://html5radioplayer.herokuapp.com/?q="

Write the IP and port information for you to edit. I want to help you. Sorry my bad English :)

**Comment by lalafunn** [comment]
Is 'allow_url_fopen=on' set in default Azuracast php.ini config?

**Comment by lalafunn** [comment]
> Hi @lalafunn ;
> 
> There is no need for a special configuration for Azuracast. You should edit on your hosting php.ini file for allow_url_fopen configuration. I can show you examples.
> 
> if corsproxy: "php" doesn't work, you should use other methods.
> Example: corsproxy: "https://html5radioplayer.herokuapp.com/?q="
> 
> Write the IP and port information for you to edit. I want to help you. Sorry my bad English :)

Assume IP: 192.168.1.1 and Port: 8000

**Comment by ogrenci01** [comment]
Hi @lalafunn;

You should not make any custom configuration in your Azuracast app.
**_"allow_url_fopen=on"_** configiration should be turned on in php.ini on your **_web hosting,_** not in Azuracast app.

> Is 'allow_url_fopen=on' set in default Azuracast php.ini config?

I have prepared the attachments for you.

You should be careful when applying:

1-) You must type the path of your js file correctly.
2-) You should write your special token code.
3-) "streamurl" code you should write your own radio ip and port information.

[big_with_fallback_php.txt](https://github.com/AzuraCast/AzuraCast/files/3610686/big_with_fallback_php.txt)
[small_with_fallback_php.txt](https://github.com/AzuraCast/AzuraCast/files/3610687/small_with_fallback_php.txt)
[big_with_fallback_usecorsproxy.txt](https://github.com/AzuraCast/AzuraCast/files/3610688/big_with_fallback_usecorsproxy.txt)
[small_with_fallback_usecorsproxy.txt](https://github.com/AzuraCast/AzuraCast/files/3610689/small_with_fallback_usecorsproxy.txt)

If you can't do that, you can visit the following pages.

Fallback PHP: https://tek.link/M80X
Fallback CorsProxy: https://tek.link/M80Y

Sorry my bad English. Good Luck! Enjoy!

**Comment by lalafunn** [comment]
Thanks @ogrenci01 
Now, I seek for advise of Azuracast Team about php.ini settings.

**Comment by lalafunn** [comment]
> Hi @lalafunn;
> 
> > Is 'allow_url_fopen=on' set in default Azuracast php.ini config?
> 
> You should not make any custom configuration in your Azuracast app.
> **_"allow_url_fopen=on"_** configiration should be turned on in php.ini on your **_web hosting,_** not in Azuracast app.
> 
> Also I am using Azuracast Ansible. The installation already makes this setting. I think this is the same for the docker installation.
> 
> I have prepared the attachments for you.
> 
> You should be careful when applying:
> 
> 1-) You must type the path of your js file correctly.
> 2-) You should write your special token code.
> 3-) "streamurl" code you should write your own radio ip and port information.
> 
> [big_with_fallback_php.txt](https://github.com/AzuraCast/AzuraCast/files/3610686/big_with_fallback_php.txt)
> [small_with_fallback_php.txt](https://github.com/AzuraCast/AzuraCast/files/3610687/small_with_fallback_php.txt)
> [big_with_fallback_usecorsproxy.txt](https://github.com/AzuraCast/AzuraCast/files/3610688/big_with_fallback_usecorsproxy.txt)
> [small_with_fallback_usecorsproxy.txt](https://github.com/AzuraCast/AzuraCast/files/3610689/small_with_fallback_usecorsproxy.txt)
> 
> If you can't do that, you can visit the following pages.
> 
> Fallback PHP: https://tek.link/M80X
> Fallback CorsProxy: https://tek.link/M81o
> 
> Sorry my bad English. Good Luck! Enjoy!

I followed the instructions with CorsProxy but no success :(

**Comment by ogrenci01** [comment]
Hi My Friend;

Can you give me real ip and port information? You can contact me at Azuracast slack. ı will do it for you :)

**Comment by lalafunn** [comment]
> Hi My Friend;
> 
> Can you give me real ip and port information?
> You can contact me at Azuracast slack. I will do it for you :)
> 
> And I need more information. Which server do you use IceCast or ShoutCast?
> Based on the information you gave me, I'm going to set up a configuration for you.
> 
> I found a working corsproxy server. Please use it :)
> 
> corsproxy:"https://bypasscors.herokuapp.com/api/?url="

You may use the demo streaming as below:
https://demo.azuracast.com/radio/8000/radio.mp3?1568573763

**Comment by ogrenci01** [comment]
Hi @lalafunn ;

It is working :) You check it :)

Fallback PHP: https://tek.link/M8l7
Fallback CorsProxy: https://tek.link/M8l5

[small_with_fallback_php.txt](https://github.com/AzuraCast/AzuraCast/files/3614193/small_with_fallback_php.txt)
[small_with_fallback_usecorsproxy.txt](https://github.com/AzuraCast/AzuraCast/files/3614192/small_with_fallback_usecorsproxy.txt)

Enjoy!

**Comment by lalafunn** [comment]
It works with Azura Demo Streaming URL but not with my own.
Maybe it is something related to Cloudflare!

**Comment by ogrenci01** [comment]
Hi;

Azuracast Demo Stream is using Cloudflare. I want to help you. Azuracast, Centovacast, Whmsonic etc. works properly. I have tried this configuration.

Also I can give remote support to you with teamviewer, anydesk, alpemix etc.

Enjoy :)

**Comment by lalafunn** [comment]
Are you in Slack?

**Comment by ogrenci01** [comment]
Hi @lalafunn ;

I am online now.

**Comment by lalafunn** [comment]
What's your name on Slack?
