### ISSUE TITLE
AzuraCast shows apache page

### ISSUE THREAD

**Issue by ProxyPing** [AzuraCast/AzuraCast#1965]
Hello, i have a problem, i have just rebooted my Server
and it started again and now is azuracast "gone"
it just shows Apache default page: http://upload.yourmusicbots.de/6966ve5T34q6.png
but if i go to domain.com:8000 icecast is started and liquidsoap too
operating system: Ubuntu 18.04

**Comment by Vaalyn** [comment]
When reporting errors, problems or bugs please use the bug reporting issue template and just fill in the information that we request from you. We need these things to be able to effectively help you without having to waste time chasing that information down.

In your case I'm assuming that you are using the Docker installation method on your Ubuntu.
You most likely have an apache2 or httpd installed that is automatically starting on a reboot.
Disable that and restart AzuraCast via the the docker-compose command and it should start working again.

**Comment by ItsAlwaysRuben** [comment]
how do i disable that? and what is the restart command?

**Comment by ItsAlwaysRuben** [comment]
what command is used to disable that? and what command is used to restart?

**Comment by ItsAlwaysRuben** [comment]
idk whats happening in github but my message's are being deleted

**Comment by ItsAlwaysRuben** [comment]
F

**Comment by Vaalyn** [comment]
You should be able to stop/remove it with the following commands.

Stop Apache2 service:
`sudo systemctl stop apache2`

Uninstall Apache2 service:
`sudo apt-get purge -y apache2*`

Regarding restarting AzuraCast, as you've not supplied us with enough information about your installation I'm giving you the commands for the recommended installation method (Docker):
`docker-compose down` and after that `docker-compose up -d`.
