### ISSUE TITLE
Laut.fm news transmission 

### ISSUE THREAD

**Issue by Manuel19861** [AzuraCast/AzuraCast#1966]
Laut.fm news transmission 
https://[STATIONSNAME]:[LIVE-PASSWORT]@api.radioadmin.laut.fm/news/1
with station name and the live password

**Comment by Vaalyn** [comment]
I'll close this issue until further information is provided.

Please edit your post to add more information about what you want to do or what you are having issues with. As it stands I have no indication of what exactly you want to achieve.

If this is a feature request please use https://features.azuracast.com/ and add a detailed description about what you'd like to have added.
