### ISSUE TITLE
youtube relay

### ISSUE THREAD

**Issue by jbrunno** [AzuraCast/AzuraCast#1967]
Good Morning.
was wondering if somehow to relay a youtube video on azuracast 
https://www.youtube.com/embed/2NPIh7BxDeU?autoplay=1

**Comment by oussamatn** [comment]
You can do this, but you have to go thru FFMPEG.

**Comment by afonsosantos** [comment]
@oussamatn Hi!

You can use [this project ](https://github.com/AzuraCast/radio-video-stream) and configure it in order to stream to YouTube.
