### ISSUE TITLE
Live source goes silent from time to time (w/ Butt)

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1970]
Sometimes the DJ source goes silent without Butt disconnecting. This is what we see in the log: 

```
2019/09/12 19:15:59 [radio_live_fallback:3] Switch to blank_6655 with forgetful transition.
2019/09/12 19:15:59 [dummy:3] Source failed (no more tracks) stopping output...
2019/09/12 19:16:06 [radio_live_fallback:3] Switch to audio_to_stereo_6652 with transition.
```

The corresponding Liquidsoap configuration is this: 

```
live = audio_to_stereo(input.harbor("/", id="radio_input_streamer", port=8005, user="shoutcast", auth=dj_auth, icy=true, max=30., buffer=5., icy_metadata_charset="UTF-8", metadata_charset="UTF-8", on_connect=live_connected, on_disconnect=live_disconnected))
ignore(output.dummy(live, fallible=true))
live = fallback(id="radio_live_fallback", track_sensitive=false, [live, blank(duration=2.)])

```

Does anybody have an idea why it happens? May it be due to bad Internet connection on the Butt user side? Can the Liquidsoap configuration be adjusted to avoid these blank bits? 

Thanks!

**Comment by Vaalyn** [comment]
You can try increasing the `Advanced DJ/Streamer Buffer Time (Seconds)` in the Stations Profile in the Auto DJ section. If the internet connection from the live connection is unreliable this should help to keep enough data in the buffer to prevent that from being issue for the stream.
