### ISSUE TITLE
Broadcasting to RTMP server

### ISSUE THREAD

**Issue by oussamatn** [AzuraCast/AzuraCast#1971]
Hey, 

I would like to know how can I broadcast my station live shows to Twitch. 
I know that there's GUI software named OBS Studio, but I would like to do it remotely so it runs 24/7. I think that its possible with FFMPEG but I don't found any tutorial online. This would be helpful for all Azuracast users.

Best,

**Comment by afonsosantos** [comment]
@oussamatn Hi!

You can use [this project ](https://github.com/AzuraCast/radio-video-stream) and configure it in order to stream to Twitch.
