### ISSUE TITLE
Song Playback Timeline - record label for royalty reports

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#1974]
**Host Operating System**
Ubuntu 16.04

Does azuracast logging more information about songs like "lable" (record label) and how to display it in "Song Playback Timeline" report?

**Comment by eranwo** [comment]
Hi,
Have you had a chance to look at this yet?

**Comment by SlvrEagle23** [comment]
@eranwo You can create custom fields that you can associate with your media, which will then appear in the music files manager. The custom fields can be managed from the system-wide administration page.

Currently, these custom fields don't appear in the royalty reports. You can always [submit a feature request](https://features.azuracast.com/) if you would like to see that included in a future version.

**Comment by eranwo** [comment]
Hi,
Thank you for the reply!
Is it possible to automatically associate the custom fields with the mp3 ID tag in similar as the Song Title, Song Artist ...
