### ISSUE TITLE
Stations: Mount Points - Status 500

### ISSUE THREAD

**Issue by iDJHost** [AzuraCast/AzuraCast#1978]
**Using Docker installation method**
Yes

**Host Operating System**
CentOS 7

**Describe the bug**
(Stream Type is irrelevant: Both SHOUTcast2 & IceCast are affected.)
API - Stations: Mount Points not working

API that Does Work in this section:
GET /station/{station_id}/mounts
POST /station/{station_id}/mounts

API that Does NOT Work in this section:
GET /station/{station_id}/mount/{id}
PUT /station/{station_id}/mount/{id}
DELETE /station/{station_id}/mount/{id}

**To Reproduce**
Using cURL:
curl -X GET "https://your.domain.tld/api/station/1/mount/1 
curl -X PUT "https://your.domain.tld/api/station/1/mount/1  -H "accept: application/json" -H "Content-Type: application/json" -d "{\"name\":\"/streamer\",\"display_name\":\"radio\"}"
curl -X DELETE "https://your.domain.tld/api/station/1/mount/1 

**Expected behavior**
To do exactly what it should do....
GET = Provide the info about the mount id.
PUT = Change the variables declared.
DELETE = Delete the Mount point.

**Relevant Logs**
AzuraCast.ERROR: Unable to invoke the callable because no value was given for parameter 4 ($record_id) {"file":"/var/azuracast/www/vendor/php-di/invoker/src/Invoker.php","line":75,"code":0} []"

**Device(s):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Mozilla
 - Version: AzuraCast • v0.9.6.5

**Additional context**
HTML Body Response: Unable to invoke the callable because no value was given for parameter 4 ($record_id) Invoker.php : 75  

It seems as though every API call ending with an integer gives a Status 500

Unable to invoke the callable because no value was given for parameter # ($record_id)<br>
Invoker.php : 75
Where # = the place it's located in the call - examples:
admin/station/{id}
admin/role/{id}
admin/user/{id}

station/{station_id}/mount/{id} 
(First integer is good, the second integer {id} causes the error)

Tests done in Terminal using cURL, PHP using cURL, browser: Chrome & Mozilla

**Comment by SlvrEagle23** [comment]
@iDJHost Definitely valid. Surprised more people didn't report this...guess we don't have too many API users!

Should be fixed now across all affected endpoints.

**Comment by iDJHost** [comment]
It appears as though the GET/PUT/POST admin/station/{id} in the API don't work still.

**Comment by iDJHost** [comment]
If it helps, the original issue - Stations: Mount Points appears to be fixed 100%, it's the admin calls now, with a different error - 
HTML Response: Method not allowed - RoutingMiddleware.php : 94

**Comment by SlvrEagle23** [comment]
@iDJHost What's the specific endpoint having that problem? I'm not seeing any issues on local tests on `/admin/stations/{id}`

**Comment by iDJHost** [comment]
curl -H "Content-Type: application/json" -H "X-API-Key: your_api_key" -X GET https://your.domain.tld/api/admin/station/42
Working in terminal, but not from PHP
