### ISSUE TITLE
Shoutcast Status Stuck On "Private" - Authhash isn't updating.....

### ISSUE THREAD

**Issue by pwrj** [AzuraCast/AzuraCast#1979]
Why is shoutcast status being private, despite updating my Authhash multiple times. Listing Status: | Stream is currently up and private (not listed) - Please help. See attached, is there somewhere to update Authhash in Azuracast?

<img width="508" alt="Screen Shot 2019-09-17 at 8 07 08 PM" src="https://user-images.githubusercontent.com/7035452/65088337-f6bdf500-d986-11e9-9485-53a040ac29f6.png">
<img width="525" alt="Screen Shot 2019-09-17 at 8 06 16 PM" src="https://user-images.githubusercontent.com/7035452/65088338-f6bdf500-d986-11e9-8bd0-72ad38d838c1.png">
<img width="722" alt="Screen Shot 2019-09-17 at 8 05 55 PM" src="https://user-images.githubusercontent.com/7035452/65088340-f6bdf500-d986-11e9-869d-3633a4292b86.png">

**Comment by iDJHost** [comment]
I am about to test it on my server to see what if get the same thing.
Bit of advice, you should never share your AuthHash.

**Comment by pwrj** [comment]
@iDJHost Thank you for testing it for me. BTW, I changed my Authhash before I posted it here.

**Comment by iDJHost** [comment]
OK, great. Go to "Mount Points" -> "Edit" the mount point you will be using and enable "Publish to "Yellow Pages" Directories" -> Save Changes and Restart your station.

**Comment by pwrj** [comment]
@iDJHost Before posting this here, I looked everywhere but "Mount Points".  Thank you so much!!

**Comment by iDJHost** [comment]
No worries, that should resolve the issue for you.

**Comment by pwrj** [comment]
@iDJHost I appreciate it!
