### ISSUE TITLE
Update today

### ISSUE THREAD

**Issue by rolradio** [AzuraCast/AzuraCast#198]
Hey,

Today I did an update via SSH terminal console.
I did this more often without problems.
Today, however, it went wrong with the update.

I get this error as a whole at the end of the update.
Fatal: [localhost]: FAILED! => {"Changed": false, "failed": true, "msg": "Could not find the requested service redis: host"}

Now nothing works anymore.
Can you please help me further?
I am using azuracast now for 4 months without real problems.

**Comment by SlvrEagle23** [comment]
@rolradio One of the recent updates installed Redis, and it seems your installation didn't make it to that part. Can you try running `./update.sh --full` and seeing if that helps?

**Comment by rolradio** [comment]
@SlvrEagle23 
I did the full update.

Unfortunately, the error persists:

TASK [nginx : Link app-specific nginx site] ********************************************************
ok: [localhost]

TASK [nginx : Turn sendfile off on nginx for local development] ************************************
skipping: [localhost]

TASK [redis : Install Redis] ***********************************************************************
ok: [localhost] => (item=[u'redis-server'])

TASK [redis : Restart Redis service] ***************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service redis: host"}
        to retry, use: --limit @/var/azuracast/www/util/ansible/update.retry

PLAY RECAP *****************************************************************************************
localhost                  : ok=29   changed=2    unreachable=0    failed=1

**Comment by SlvrEagle23** [comment]
@rolradio Ugh it's called `redis-server` on 14.04.

One second, fix coming!

**Comment by SlvrEagle23** [comment]
@rolradio Try it now.

**Comment by rolradio** [comment]
@SlvrEagle23
Yes we run again,
 Thank you!!

**Comment by SlvrEagle23** [comment]
@rolradio Happy to help :)

**Comment by anmiefan** [comment]
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service redis: host"}

i am using 18.04

**Comment by maletazul** [comment]
Same error on 18.04 VM

**Comment by SlvrEagle23** [comment]
@anmiefan @maletazul I've updated Ansible's installation procedure to be a little more tolerant of service name changes. Please update and let me know if the issue persists.

In general, it's not a great idea to revive issues from over 3 years ago if the issue hasn't been ongoing for that whole time; it would be better to make a new issue so we can track it separately in the future.

**Comment by maletazul** [comment]
@SlvrEagle23 you right, let me submit an issue
