### ISSUE TITLE
Error on azurarelay installation

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#1980]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 16.04

**Describe the bug**
when trying to install azurarelay - getting this error:
Fatal error: Uncaught Error: Call to undefined method Azura\App::create() in /var/azurarelay/www/bin/console.php:7
Stack trace:
#0 {main}
thrown in /var/azurarelay/www/bin/console.php on line 7

and in browser:
Fatal error: Uncaught Error: Call to undefined method Azura\App::create() in /var/azurarelay/www/web/index.php:7 Stack trace: #0 {main} thrown in /var/azurarelay/www/web/index.php on line 7

Please see also Here:
https://github.com/AzuraCast/AzuraRelay/issues/6
https://github.com/AzuraCast/AzuraRelay/issues/5

**Comment by SlvrEagle23** [comment]
@eranwo Whoops...looks like I don't have AzuraRelay alerts turned on. Thank you for letting me know.

Will hop over there and get this fixed up today.
