### ISSUE TITLE
default "Now Playing" file

### ISSUE THREAD

**Issue by iDJHost** [AzuraCast/AzuraCast#1984]
Is it possible to change the default "Now Playing" sound file?

If Yes, How & Where?

**Comment by SlvrEagle23** [comment]
@iDJHost You mean the default error song? Currently, no, there's no way to change that short of bind-mounting a replacement into the `stations` container (if you're using the Docker installation).

**Comment by iDJHost** [comment]
The Now playing: AzuraCast.com - AzuraCast is Live!

"The station you are listening to is powered by AzuraCast, The Free and Open-Source software that makes web-radio simple. If you're hearing this message, your station's ready to go, just add new music to your playlist(s). If you need help or to learn more about AzuraCast, visit A_Z_U_R_A_C_A_S_T.com"

Looking into your suggestion, I know nothing about Docker.

**Comment by SlvrEagle23** [comment]
@iDJHost Yeah, that's the default error message.

You'd want to override the Docker volume by creating a new `docker-compose.override.yml` file with contents similar to:

```
version: '2.2'

services:
  stations:
    volumes:
      - ./error.mp3:/usr/local/share/icecast/error.mp3
```

**Comment by iDJHost** [comment]
Other option could be better documentation on how to use the stations built in 
"Remote URL Playlist: A playlist that instructs the station to play from a remote URL."
or something similar? 
There are a lot of "features" I don't fully understand and lack better explanation of it's purpose/use.

**Comment by SlvrEagle23** [comment]
@iDJHost You're welcome to pull-request in any documentation you feel is lacking. The project's run entirely by me and my plate is full. I do the best I can.

**Comment by iDJHost** [comment]
Good to know, I am going to try the override.yml here in a few moments to see if I can get it working like that

**Comment by brammittendorff** [comment]
> @iDJHost Yeah, that's the default error message.
> 
> You'd want to override the Docker volume by creating a new `docker-compose.override.yml` file with contents similar to:
> 
> ```
> version: '2.2'
> 
> services:
>   stations:
>     volumes:
>       - ./error.mp3:/usr/local/share/icecast/error.mp3
> ```

This should now be:

```
version: '2.2'

services:
  stations:
    volumes:
      - ./error.mp3:/usr/local/share/icecast/web/error.mp3
```

**Comment by painor** [comment]
Will there an option to do it from the web in future releases ?

**Comment by brammittendorff** [comment]
> Will there an option to do it from the web in future releases ?
> I really hate touching docker images as I am not that good with them.

You are not touching docker images, because you create a new one, and override it:

```docker-compose.override.yml```
