### ISSUE TITLE
Custom transition script stops working after called twice

### ISSUE THREAD

**Issue by bjarn** [AzuraCast/AzuraCast#1985]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
A custom script I got from the RadioPi project which I updated seems to work, however, it only gets called twice and then stops working.

**To Reproduce**

1. Create a playlist with tracks and a playlist with jingles
2. Add the following custom script to the auto dj:
`# Custom crossfade to deal with jingles..
def smart_crossfade (~start_next=5.,~fade_in=3.,~fade_out=3.,
                     ~default=(fun (a,b) -> sequence([a, b])),
                     ~high=-15., ~medium=-32., ~margin=4.,
                     ~width=2.,~conservative=false,s)
  fade.out = fade.out(type="sin",duration=fade_out)
  fade.in  = fade.in(type="sin",duration=fade_in)
  add = fun (a,b) -> add(normalize=false,[b, a])
  log = log(label="smart_crossfade")

  def transition(a,b,ma,mb,sa,sb)

    list.iter(fun(x)-> log(level=4,"Before: #{x}"),ma)
    list.iter(fun(x)-> log(level=4,"After : #{x}"),mb)

    log('ma genre: #{quote(ma["genre"])} artist #{quote(ma["type"])}, mb genre: #{quote(mb["genre"])} artist #{quote(ma["type"])}')

    if ma["genre"] == "" or mb["genre"] == "" then
      log("Old or new file is a jingle: sequenced transition.")
      sequence([sa, sb])
    elsif
      # If A and B are not too loud and close, fully cross-fade them.
      a <= medium and b <= medium and abs(a - b) <= margin
    then
      log("Old <= medium, new <= medium and |old-new| <= margin.")
      log("Old and new source are not too loud and close.")
      log("Transition: crossed, fade-in, fade-out.")
      add(fade.out(sa),fade.in(sb))

    elsif
      # If B is significantly louder than A, only fade-out A.
      # We don't want to fade almost silent things, ask for >medium.
      b >= a + margin and a >= medium and b <= high
    then
      log("new >= old + margin, old >= medium and new <= high.")
      log("New source is significantly louder than old one.")
      log("Transition: crossed, fade-out.")
      add(fade.out(sa),sb)

    elsif
      # Opposite as the previous one.
      a >= b + margin and b >= medium and a <= high
    then
      log("old >= new + margin, new >= medium and old <= high")
      log("Old source is significantly louder than new one.")
      log("Transition: crossed, fade-in.")
      add(sa,fade.in(sb))

    elsif
      # Do not fade if it's already very low.
      b >= a + margin and a <= medium and b <= high
    then
      log("new >= old + margin, old <= medium and new <= high.")
      log("Do not fade if it's already very low.")
      log("Transition: crossed, no fade.")
      add(sa,sb)

    # What to do with a loud end and a quiet beginning ?
    # A good idea is to use a jingle to separate the two tracks,
    # but that's another story.

    else
      # Otherwise, A and B are just too loud to overlap nicely,
      # or the difference between them is too large and overlapping would
      # completely mask one of them.
      log("No transition: using default.")
      default(sa, sb)
    end
  end

  log("Smart cross passed")

  smart_cross(width=width, duration=start_next, conservative=conservative,
              transition,s)
end

radio = amplify(1.,override="replay_gain", radio)
radio = smart_crossfade(radio)`

**Expected behavior**

The function gets called for every transition.

**Relevant Logs**
When it works; these logs are shown:
`2019/09/19 20:21:57 [xxxx:3] Prepared "/var/azuracast/stations/xxx/media/jingle_2.wav" (RID 22).
2019/09/19 20:21:57 [xxx:3] Switch to audio_to_stereo_6454 with forgetful transition.
2019/09/19 20:21:57 [smart_cross_6510:3] Analysis: -10.560533dB / -10.836774dB (2.28s / 2.32s)
2019/09/19 20:21:57 [smart_crossfade:3] ma genre: "" artist "", mb genre: "" artist ""
2019/09/19 20:21:57 [smart_crossfade:3] Old or new file is a jingle: sequenced transition.
2019/09/19 20:21:57 [lang:3] AzuraCast Feedback Response: OK
2019/09/19 20:21:59 [lang:3] AzuraCast Feedback Response: OK
2019/09/19 20:22:01 [xxx:3] Finished with "/var/azuracast/stations/xxx/media/jingle_2.wav".
2019/09/19 20:22:01 [xxx:3] Prepared "/var/azuracast/stations/xxx/media/xxx - Low Rotation/109 - Hailee Steinfeld - Starving.mp3" (RID 23).
2019/09/19 20:22:01 [smart_cross_6510:3] Analysis: -21.155157dB / -23.024329dB (0.77s / 0.79s)
2019/09/19 20:22:01 [smart_crossfade:3] ma genre: "" artist "", mb genre: "Pop" artist ""
2019/09/19 20:22:01 [smart_crossfade:3] Old or new file is a jingle: sequenced transition.
2019/09/19 20:22:02 [lang:3] AzuraCast Feedback Response: OK
2019/09/19 20:24:53 [lang:3] AzuraCast Raw Response: annotate:title="One More Night",artist="Maroon 5",duration="219.",song_id="52006642dfc1a7d97a344605ddfbb7eb",media_id="385",playlist_id="4":/var/azuracast/stations/xxx/media/xxx - Rare Rotation/025 - Maroon 5 - One More Night.mp3
2019/09/19 20:24:53 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/xxx/media/xxx - Rare Rotation/025 - Maroon 5 - One More Night.mp3".
2019/09/19 20:24:58 [xxx:3] Finished with "/var/azuracast/stations/xxx/media/xxx - Low Rotation/109 - Hailee Steinfeld - Starving.mp3".
2019/09/19 20:24:58 [xxx:3] Prepared "/var/azuracast/stations/xx/media/xx - Rare Rotation/025 - Maroon 5 - One More Night.mp3" (RID 24).
2019/09/19 20:24:58 [smart_cross_6510:3] Analysis: -47.234113dB / -18.341095dB (5.03s / 5.05s)
2019/09/19 20:24:58 [smart_crossfade:3] ma genre: "Pop" artist "", mb genre: "Pop" artist ""
2019/09/19 20:24:58 [smart_crossfade:3] new >= old + margin, old <= medium and new <= high.
2019/09/19 20:24:58 [smart_crossfade:3] Do not fade if it's already very low.
2019/09/19 20:24:58 [smart_crossfade:3] Transition: crossed, no fade.
2019/09/19 20:24:58 [lang:3] AzuraCast Feedback Response: OK`

When it does not work, it shows the following entries:
`2019/09/19 20:28:27 [lang:3] AzuraCast Raw Response: annotate:title="jingle 4",duration="2.",song_id="62933204008d5cb0fede2be7ac815761",media_id="2451",playlist_id="8":/var/azuracast/stations/xxx/media/jingle_4.wav
2019/09/19 20:28:27 [decoder:3] Method "WAV" accepted "/var/azuracast/stations/xxx/media/jingle_4.wav".
2019/09/19 20:28:29 [lang:3] AzuraCast Raw Response: annotate:title="Me Boy",artist="Yes-R and Ali B featuring Lange Frans",duration="202.",song_id="17c76dc3dc480d584f197e5941c96a83",media_id="247",playlist_id="6":/var/azuracast/stations/xxx/media/xxx - Low Rotation/016 - Yes-R and Ali B featuring Lange Frans - Me Boy.mp3
2019/09/19 20:28:29 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/xxx/media/xxx - Low Rotation/016 - Yes-R and Ali B featuring Lange Frans - Me Boy.mp3".
2019/09/19 20:28:32 [xxx:3] Finished with "/var/azuracast/stations/xxx/media/xxx - Rare Rotation/025 - Maroon 5 - One More Night.mp3".
2019/09/19 20:28:32 [xxx:3] Prepared "/var/azuracast/stations/xxx/media/jingle_4.wav" (RID 25).
2019/09/19 20:28:32 [xxx:3] Finished with "/var/azuracast/stations/xxx/media/jingle_4.wav".
2019/09/19 20:28:32 [xxx:3] Prepared "/var/azuracast/stations/xxx/media/xxx - Low Rotation/016 - Yes-R and Ali B featuring Lange Frans - Me Boy.mp3" (RID 26).
2019/09/19 20:28:32 [smart_cross_6510:3] Analysis: -25.878177dB / -10.576498dB (5.02s / 2.45s)
2019/09/19 20:28:32 [smart_cross_6510:3] Not enough data for crossing.
2019/09/19 20:28:37 [lang:3] AzuraCast Feedback Response: OK
2019/09/19 20:28:40 [lang:3] AzuraCast Feedback Response: OK`

**Additional context**
The scripts has been pulled from: http://savonet.sourceforge.net/doc-svn/scripts/users_radiopi.html

**Comment by SlvrEagle23** [comment]
@bjarn Since you're using custom Liquidsoap code, it's likely that the problem is with Liquidsoap specifically and not with AzuraCast. You may want to create an issue [on their GitHub repository](https://github.com/savonet/liquidsoap) for more assistance.

**Comment by bjarn** [comment]
@SlvrEagle23 Great! I have created an issue over there. Will update this ticket to include an answer.
