### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by AlfieJunior** [AzuraCast/AzuraCast#1987]
Hi, 
I keep getting the error 
"502 Bad Gateway
nginx" 
Persistently, Please can i have some form of idea why it is doing this? I have reinstalled on 4 different servers, Not even directed the servers to the URL etc kept it private so only i know this IP so it inst being attacked etc. 
3 Hosts 4 Servers 293820 Attempts and 1 Me Giving Up! 

Kind Regards, 
Alfie

**Comment by AlfieJunior** [comment]
I am using Docker Ubuntu 18.04 LTE

**Comment by KoneSV** [comment]
Try without Docker: https://www.azuracast.com/install/#installing

**Comment by AlfieJunior** [comment]
I have tried doing so from your reply and had no luck. :/ Any more suggestions?

> Try without Docker: https://www.azuracast.com/install/#installing

**Comment by KoneSV** [comment]
Reinstall system to VPS test again

it happened to me once

**Comment by AlfieJunior** [comment]
Hi, 
This is a repetitive issue. 
AlfieJuniorOfficial#9191 feel free to add me on DC to try and resolve quicker.


> Reinstall system to VPS test again
> 
> it happened to me once

**Comment by AlfieJunior** [comment]
Issue still persistently happening, Different DNS, Different Domain, Different Server & Fresh Install... I do not see how it can be happening on multiple servers.

**Comment by SlvrEagle23** [comment]
@AlfieJunior The only thing I can think of is that you're possibly doing something wrong in the setup process, or trying to override something on every installation and it's not working correctly.

Is there anything specific you're doing during your setup process? Are you using the multisite setup, for example? Are you overriding the nginx configuration at all?

**Comment by iDJHost** [comment]
Not sure if it's relevant but might be worth mentioning -
I use CentOS 7 and immediately after I install on a new server i have to "service restart docker"

Fresh Server:
yum -y update
yum -y install git
mkdir -p /var/azuracast
cd /var/azuracast
curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh
chmod a+x docker.sh
./docker.sh install
service docker restart //My added process to the installation

**Comment by AlfieJunior** [comment]
The issue is still happening, It will not allow me to go onto the site to get logs etc, All i can say really is Ubuntu 18.04 > 8GB Ram > 220GB SSD. 

> https://imgur.com/kwd08ji 
Above link for screenshot of error.

**Comment by ErnestPH** [comment]
Is it on a fresh install? Is it also a VPS dedicated for Azuracast installation only? Or it's partition?

**Comment by AlfieJunior** [comment]
hosted from DO and Manually installed Azuracast. 
The site works for about 20 seconds then goes down again then comes back online whenever it wants too.

**Comment by AlfieJunior** [comment]
> Is it on a fresh install? Is it also a VPS dedicated for Azuracast installation only? Or it's partition?


Yes its dedicated to Azuracast, and Yes a Fresh install after many haha!

**Comment by ErnestPH** [comment]
Interesting as I have some DO Azuracast and I never encountered that issue. Can you paste step by step on how you installed Azuracast?

**Comment by AlfieJunior** [comment]
https://discord.gg/NP2JAz Join a group DM and ill explain. 
Otherwise, I followed the tutorial on Azuracast and thats all.

**Comment by ErnestPH** [comment]
How about you join [Azuracast slack channel?](azuracast.slack.com ) and explain there… At least it will be beneficial to everyone who might encounter your same problem.

**Comment by AlfieJunior** [comment]
> How about you join [Azuracast slack channel?](https://azuracast.slack.com) and explain there… At least it will be beneficial to everyone who might encounter your same problem.

Have tried many times however it states invite only.

**Comment by ErnestPH** [comment]
Really? Well, I guess it was not an invitation only before… Sorry I can't help you further
