### ISSUE TITLE
live source password error after AZURACAST update 

### ISSUE THREAD

**Issue by citycomgr** [AzuraCast/AzuraCast#1988]
We are  experiencing a problem with live source

After last update and changes provided by support team , we changed ftp port and assingned all mappings. (it loses after update)
Everything woks fine but live source can’t connect
We always get error Password failed
We checked password in sc_server.conf and it’s same.
The content on sc_server.conf  is 

password=sourcepassword
adminpassword=adminpass
logfile=/tmp/sc_serv.log
w3clog=/var/azuracast/stations/deejayradio/config/sc_w3c.log
banfile=/var/azuracast/stations/deejayradio/config/sc_serv.ban
ripfile=/var/azuracast/stations/deejayradio/config/sc_serv.rip
maxuser=1000
portbase=8000
requirestreamconfigs=1
streamid_1=1
streampath_1=/radio.mp3

On  azuracast  we set ports 
Advanced Customize DJ/Streamer Port  8005 
and 
Advanced Customize Internal Request Processing Port 8004

We always get message Socket connected and after that password Failed… ( we’re using port 8005 to connect with correct credentials)
we have updated to last version of azuracast 
Any other suggestion we can do ?

**Comment by ogrenci01** [comment]
Hello;

If you are using AutoDJ, you should not use "password". Add a streamer from the "Dj/Streamer" tab. Use port 8005. Your password will be "**djusername:password**".

If you don't use AutoDJ, you should use "**sourcepassword**". You must disable AutoDJ. You must use port 8000. Your password will be the value you give for "sourcepassword".

Can you test it for them?

**Comment by citycomgr** [comment]
Hello,
I'm using AutoDj 
I tried with credentials as provided with same error 
password failed

**Comment by ogrenci01** [comment]
Hello;

Would you try that? Please write the result to us.

1-) Go to edit the station radio profile.
2-) Switch to the AutoDJ tab.
3-) "Advanced Customize DJ / Streamer Mount Point" section should be empty. Don't write anything.
4-) Save the changes.
5-) Restart everything.
6-) Try to connect with the DJ account.

**Comment by citycomgr** [comment]
Hello,
We followed all steps , we also restarted all docker containers and restart everything in Azuracast dashboard 
Problem remains: 
Socket connected 
password failed

**Comment by iDJHost** [comment]
Not sure if it helps at all, I've been hosting streams for years and most common issue with the AutoDJ password for clients connecting to SHOUTcast is that for some reason username:password can NOT be Copy and Pasted you literally have to type each character in almost every app/program.

**Comment by citycomgr** [comment]
hello,
I typed correctly many times both with same result.
Somehow it seems that can't read these data to verify 
On logs i get message  
2019/09/20 18:40:30 [lang:3] Authenticating DJ: streamer1  but nothing else just password failed on streaming program i use (edcast).

**Comment by iDJHost** [comment]
> hello,
> I typed correctly many times both with same result.
> Somehow it seems that can't read these data to verify
> On logs i get message
> 2019/09/20 18:40:30 [lang:3] Authenticating DJ: streamer1 but nothing else just password failed on streaming program i use (edcast).

I'm not familiar with edcast personally, took a look at some screenshots though. I would have suggested to use IceCast over SHOUTcast for the DJ connection but it lack the username area therefore forcing you to use shoutcast.

Server Type: Shoutcast
Server IP: URL or IP if your server
Server Port - DJ Port (I think you stated 8005)
Encoder Password: username:password
MountPoint: empty

[![Screenshot from Gyazo](https://gyazo.com/9c3d0a4a393ec172a25e702b2d3dd396/raw)](https://gyazo.com/9c3d0a4a393ec172a25e702b2d3dd396)
