### ISSUE TITLE
Move music files from created folder to root directory

### ISSUE THREAD

**Issue by de-soul** [AzuraCast/AzuraCast#1989]
It's possible to move music files from created directory to default main root directory?

Reproducing the problem:
1) I upload file "song123.mp3" to my music files directory
2) I created a subdirectory called test123
3) I moved "song123.mp3" to the test123 directory via "move" button
4) I go to the test123 directory, try to move the "song123.mp3" file back (one directory up) - there is no such possibility, the button "move" offers file transfer only to the created directories

what to do?

**Comment by Vaalyn** [comment]
This is indeed an oversight on my part.

The `Move` function currently does not provide you with the possibility to move file to the root directory. Thank you for pointing out that this feature is missing that option.

In the meanwhile you can use the built in FTP server to access the media directory and move the files through that.

**Comment by eranwo** [comment]
@de-soul Alternatively, you can go to "Edit Media" and edit the file name by deleting the folder name.

**Comment by SlvrEagle23** [comment]
@de-soul This is now possible as of the latest updates to the media manager.
