### ISSUE TITLE
On the Public page no audio is heard when using the embedded audio player

### ISSUE THREAD

**Issue by eshowman** [AzuraCast/AzuraCast#1990]
**Using Docker installation method**
 Yes

**Host Operating System**
 Ubuntu Server 18.04.03 LTS

**Describe the bug**
 No audio is heard when using the embedded audio player on the Public page, https://138.197.221.5/public/missionradiofm , this issue has been reproduced on different computers and phones

**To Reproduce**
 Go to the following URL, https://138.197.221.5/public/missionradiofm , click the play button in the embedded audio player, audio will not be heard, but the time on the left side of the player indicates a song is being played

**Expected behavior**
 Audio to be heard when the play button is clicked

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version:  This issue has occurred in Firefox, IE and Chrome.  For Firefox and Chrome all browser extensions disabled while testing.

**Additional context**

**Comment by iDJHost** [comment]
I have this issue when using SHOUTcast DNAS 2. 
IceCast 2.4 however the player does work in all browsers. (for me)

**Comment by SC2Mitch** [comment]
My end is returning a SSL Privacy error
NET::ERR_CERT_AUTHORITY_INVALID

**Comment by Vaalyn** [comment]
The problem here is that you are accessing the page over https with a self-signed certificate directly on an ip instead of a domain.

You can either switch to insecure http when accessing the page or setup a domain and use the [Let's Encrypt](https://www.azuracast.com/developers/docker_sh.html#set-up-letsencrypt) integration of AzuraCast to setup a valid certificate for https.

We recommend you to use https and setup a valid certificate for a domain.

**Comment by eshowman** [comment]
Hello,
  Thank you for all the feedback.  The mp3 stream does work correctly with my website (missionradio.fm) which has a valid certificate setup for the domain.  The issue with the Public page is not a deal breaker seeing how people either access the music stream via Radio.net or the MissionRadio.fm website.  
  I will review the settings for the station in the management interface to see if I have something checked that should not be checked.

Thanks again,

Erich S.
