### ISSUE TITLE
Restoring Backup on another server - IP doesn't update (still shows the previous IP add)

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#1992]
**Using Docker installation method**
Latest version of AzuraCast. Docker installation Ubuntu 18

**Describe the bug**
IP address in the Connection Information sidebar is not updating...

**To Reproduce**
1. Backup Azuracast (old IP)
2. Restore on another server (new IP)
3. Go to Streamer/DJ Accounts tab >> Connection iInformation
4. IP address is still from (old IP)

**Expected behavior**
The IP address is dynamic hence, it will show the new IP address

**Device(s):**
All Mac Browsers 10.14 Mojave

**Additional notes:**
I also did empty cache browser, purge in Cloudflare and cache clear in docker cli.

**Comment by ErnestPH** [comment]
Referencing this related issue https://github.com/AzuraCast/AzuraCast/issues/1664

To answer that question. It is set up to point to a domain.

**Comment by Vaalyn** [comment]
The IP is currently only fetched from the cached DB entry. The only place where that cached IP is fetched and updated is when the setup is executed. Ideally the IP should also be updated in the restore command. It would also be a good idea to periodically update the IP to make sure that when AC is hosted on a network with a dynamic WAN IP the cached IP is always correct.

**Comment by ErnestPH** [comment]
Ok thanks for the detailed explanation. `updatedb` didn't work either…

For now I hard-coded the IP addresses temporarily. Until this is worth a fix. Will closed this one now.

**Comment by Vaalyn** [comment]
I'd like to keep this issue open until this is fixed as it is a valid bug that should be fixed.

**Comment by ErnestPH** [comment]
Much better. Thank you

**Comment by SlvrEagle23** [comment]
@ErnestPH This should be fixed as of the latest version, which will clear the cached IP address upon the update that happens immediately after restoring.

**Comment by ErnestPH** [comment]
Thank you! All the best guys
