### ISSUE TITLE
Stream offline

### ISSUE THREAD

**Issue by nicolasdeslilas** [AzuraCast/AzuraCast#1993]
Hi,

I have a problem sometime the stream stop and tell me "stream offline"
I need to reboot the docker for start a new stream.
I think is maybe the end of my playlist, is it possible to "loop" a playlist ?

Cheers
3615 Radio

**Comment by radiolize** [comment]
Sometimes half of my stations go offline immediately. These stations have same liquidsoap logs. I'm writing one of them below when goes offline. I've updated docker now everything seems fine for last 10 minutes.

> 2019/09/22 09:06:28 [gerefnet_next_song:3] Finished with "/var/azuracast/stations/gerefnet/media/4_werke_-_kyk_diep_in_my_oe.mp3".
> 2019/09/22 09:06:28 [gerefnet_autodj_fallback:3] Switch to gerefnet_standard_playlists with forgetful transition.
> 2019/09/22 09:06:28 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/gerefnet/media/4_werke_-_kyk_diep_in_my_oe.mp3".
> 2019/09/22 09:10:09 [lang:3] AzuraCast Raw Response: annotate:title="huistoe",artist="broers",duration="237.",song_id="c93e17b4224c59f36c2011c11f5b1a7a",media_id="2994",playlist_id="228":/var/azuracast/stations/gerefnet/media/broers_-_huistoe.mp3
> 2019/09/22 09:10:09 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/gerefnet/media/broers_-_huistoe.mp3".
> 2019/09/22 09:10:09 [lang:3] AzuraCast Feedback Response: OK
> 2019/09/22 09:10:09 [gerefnet_local_1:3] Metadata update may have failed with error: 400, Bad Request (HTTP/1.0)
> 2019/09/22 09:10:09 [clock.wallclock_main:2] Too much latency! Resetting active sources...
> 2019/09/22 09:10:09 [gerefnet_local_1:3] Closing connection...
> 2019/09/22 09:10:09 [gerefnet_local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
> 2019/09/22 09:10:09 [gerefnet_local_1:3] Connection setup was successful.
> 2019/09/22 09:13:08 [main:3] Shutdown started!
> 2019/09/22 09:13:08 [main:3] Waiting for threads to terminate...
> 2019/09/22 09:13:08 [threads:3] Shuting down thread wallclock_main
> 2019/09/22 09:13:08 [gerefnet_local_1:3] Closing connection...
> 2019/09/22 09:13:08 [error_jingle:3] Finished with "/usr/local/share/icecast/web/error.mp3".
> 2019/09/22 09:13:08 [playlist_gkp:3] Finished with "/var/azuracast/stations/gerefnet/media/4_werke_-_kyk_diep_in_my_oe.mp3".
> 2019/09/22 09:13:08 [clock.wallclock_main:3] Streaming loop stopped.
> 2019/09/22 09:13:08 [threads:3] Thread "wallclock_main" terminated (0 remaining).
> 2019/09/22 09:13:08 [main:3] Threads terminated.
> 2019/09/22 09:13:08 [threads:3] Shutting down scheduler...
> 2019/09/22 09:13:08 [threads:3] Thread "non-blocking queue #2" terminated.
> 2019/09/22 09:13:08 [threads:3] Scheduler shut down.
> 2019/09/22 09:13:08 [threads:3] Thread "generic queue #1" terminated.
> 2019/09/22 09:13:08 [threads:3] Thread "generic queue #2" terminated.
> 2019/09/22 09:13:08 [threads:3] Thread "non-blocking queue #1" terminated.
> 2019/09/22 09:13:08 [threads:3] Shutting down queues...
> 2019/09/22 09:13:08 [threads:3] Queues shut down
> 2019/09/22 09:13:08 [server:3] Closing socket.
> 2019/09/22 09:13:08 [main:3] Cleaning downloaded files...
> 2019/09/22 09:13:08 [main:3] Freeing memory...
> 2019/09/22 09:14:26 >>> LOG START
> 2019/09/22 09:14:26 [main:3] Liquidsoap 1.3.7
> 2019/09/22 09:14:26 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.1 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.9 camomile=1.0.2 faad=0.4.0
> 2019/09/22 09:14:26 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
> 2019/09/22 09:14:26 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
> 2019/09/22 09:14:26 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
> 2019/09/22 09:14:26 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
> 2019/09/22 09:14:26 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
> 2019/09/22 09:14:26 [threads:3] Created thread "generic queue #1".
> 2019/09/22 09:14:26 [threads:3] Created thread "generic queue #2".
> 2019/09/22 09:14:26 [threads:3] Created thread "non-blocking queue #1".
> 2019/09/22 09:14:26 [threads:3] Created thread "non-blocking queue #2".
> 2019/09/22 09:14:26 [harbor:3] Adding mountpoint '/' on port 8155
> 2019/09/22 09:14:26 [playlist_gkp:3] Loading playlist...
> 2019/09/22 09:14:26 [playlist_gkp:3] No mime type specified, trying autodetection.
> 2019/09/22 09:14:26 [playlist_gkp:3] Playlist treated as format application/x-mpegURL
> 2019/09/22 09:14:26 [playlist_gkp:3] Successfully loaded a playlist of 3 tracks.
> 2019/09/22 09:14:26 [error_jingle:3] "/usr/local/share/icecast/web/error.mp3" is static, resolving once for all...
> 2019/09/22 09:14:26 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 0).
> 2019/09/22 09:14:26 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/gerefnet/media/4_werke_-_kyk_diep_in_my_oe.mp3".
> 2019/09/22 09:14:26 [gerefnet_local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
> 2019/09/22 09:14:27 [lang:3] AzuraCast Raw Response: 
> 2019/09/22 09:14:27 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2019/09/22 09:14:27 [gerefnet_local_1:3] Connection setup was successful.
> 2019/09/22 09:14:27 [threads:3] Created thread "wallclock_main" (1 total).
> 2019/09/22 09:14:27 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
> 2019/09/22 09:14:27 [gerefnet_live_switch:3] Switch to gerefnet_safe_fallback.
> 2019/09/22 09:14:27 [gerefnet_safe_fallback:3] Switch to error_jingle.
> 2019/09/22 09:14:27 [playlist_gkp:3] Prepared "/var/azuracast/stations/gerefnet/media/4_werke_-_kyk_diep_in_my_oe.mp3" (RID 2).
> 2019/09/22 09:14:27 [gerefnet_safe_fallback:3] Switch to gerefnet_radio_cue with transition.
> 2019/09/22 09:14:27 [dummy:3] Source failed (no more tracks) stopping output...
> 2019/09/22 09:14:27 [gerefnet_requests_fallback:3] Switch to gerefnet_autodj_fallback.
> 2019/09/22 09:14:27 [gerefnet_autodj_fallback:3] Switch to gerefnet_standard_playlists.
> 2019/09/22 09:14:27 [gerefnet_standard_playlists:3] Switch to stereo_playlist_gkp.
> 2019/09/22 09:14:27 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/gerefnet/media/broers_-_huistoe.mp3".
> 2019/09/22 09:14:29 [lang:3] AzuraCast Feedback Response: 
> 2019/09/22 09:14:29 [clock.wallclock_main:2] We must catchup 1.81 seconds!
> 2019/09/22 09:14:30 [clock.wallclock_main:2] We must catchup 2.34 seconds!
> 2019/09/22 09:14:30 [lang:3] AzuraCast Raw Response: 
> 2019/09/22 09:14:30 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2019/09/22 09:14:31 [clock.wallclock_main:2] We must catchup 2.39 seconds!
> 2019/09/22 09:14:33 [clock.wallclock_main:2] We must catchup 2.31 seconds!
> 2019/09/22 09:14:34 [clock.wallclock_main:2] We must catchup 3.19 seconds!
> 2019/09/22 09:14:35 [lang:3] AzuraCast Raw Response: 
> 2019/09/22 09:14:35 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2019/09/22 09:14:35 [clock.wallclock_main:2] We must catchup 3.61 seconds!
> 2019/09/22 09:14:36 [clock.wallclock_main:2] We must catchup 4.30 seconds!
> 2019/09/22 09:14:37 [clock.wallclock_main:2] We must catchup 5.09 seconds!
> 2019/09/22 09:14:38 [lang:3] AzuraCast Raw Response: 
> 2019/09/22 09:14:38 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2019/09/22 09:14:38 [clock.wallclock_main:2] We must catchup 6.03 seconds!
> 2019/09/22 09:14:39 [clock.wallclock_main:2] We must catchup 6.16 seconds!
> 2019/09/22 09:14:40 [clock.wallclock_main:2] We must catchup 4.51 seconds!
> 2019/09/22 09:14:41 [lang:3] AzuraCast Raw Response: 
> 2019/09/22 09:14:41 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2019/09/22 09:14:42 [clock.wallclock_main:2] We must catchup 4.05 seconds!
> 2019/09/22 09:14:43 [clock.wallclock_main:2] We must catchup 3.22 seconds!
> 2019/09/22 09:14:44 [clock.wallclock_main:2] We must catchup 3.82 seconds!
> 2019/09/22 09:14:44 [lang:3] AzuraCast Raw Response: 
> 2019/09/22 09:14:44 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2019/09/22 09:14:45 [clock.wallclock_main:2] We must catchup 4.10 seconds!
> 2019/09/22 09:14:46 [clock.wallclock_main:2] We must catchup 2.80 seconds!
> 2019/09/22 09:14:47 [clock.wallclock_main:2] We must catchup 2.03 seconds!
> 2019/09/22 09:14:47 [lang:3] AzuraCast Raw Response: 
> 2019/09/22 09:14:47 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2019/09/22 09:14:49 [lang:3] AzuraCast Raw Response: 
> 2019/09/22 09:14:49 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2019/09/22 09:14:52 [lang:3] AzuraCast Raw Response: 
> 2019/09/22 09:14:52 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2019/09/22 09:14:55 [lang:3] AzuraCast Raw Response: 
> 2019/09/22 09:14:55 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2019/09/22 09:14:58 [lang:3] AzuraCast Raw Response: 
> 2019/09/22 09:14:58 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2019/09/22 09:15:01 [lang:3] AzuraCast Raw Response: 
> 2019/09/22 09:15:01 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2019/09/22 09:15:04 [lang:3] AzuraCast Raw Response: 
> 2019/09/22 09:15:04 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2019/09/22 09:15:07 [lang:3] AzuraCast Raw Response: 
> 2019/09/22 09:15:07 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2019/09/22 09:15:10 [lang:3] AzuraCast Raw Response: 
> 2019/09/22 09:15:10 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2019/09/22 09:15:13 [lang:3] AzuraCast Raw Response: 
> 2019/09/22 09:15:13 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2019/09/22 09:15:16 [lang:3] AzuraCast Raw Response: 
> 2019/09/22 09:15:16 [lang:3] AzuraCast Error: Delaying subsequent requests...
> 2019/09/22 09:15:19 [lang:3] AzuraCast Raw Response: 
> 2019/09/22 09:15:19 [lang:3] AzuraCast Error: Delaying subsequent requests...
