### ISSUE TITLE
Statistic Relays using Sam Broadcaster

### ISSUE THREAD

**Issue by williambatson** [AzuraCast/AzuraCast#1995]
Having issues setting up a statistic relay to show the number of listeners while using SAM Broadcaster -  Have heard in the forums it's possible but have tried multiple solutions with no luck.   If you've done this - please post how you created the link - if a relay was needed, etc.

**Using Docker installation method**

**Host Operating System**

**Describe the bug**

**Expected behavior**

Thanks for any input or assistance as always

**Comment by afonsosantos** [comment]
Hi @williambatson ,

As said on Slack, you need to enter the IceCast/SHOUTcast server info and not the AzuraCast DJ info. I can't attach screenshots because I don't have SAMBC anymore.

**Comment by williambatson** [comment]
Ahh -  that's maybe where I misunderstood -  I don't need a screen shot...  If I am using Shoutcast, which server information are you talking about exactly?
This is the info being requested:
https://gyazo.com/70450e0db6fa4209f961fde732e533b6

I've tried a dozen combinations and haven't found the correct info to put in here  - this is where I'm stuck -   thanks

**Comment by afonsosantos** [comment]
Try entering the follwing details:

**Host**: X.X.X.X (ip address, if using ClodFlare or FQDN)
**Port**: 8000 (port for your SHOUTcast server)
**Password:** the ADMIN password for your SHOUTcast server (available in the radio dashboard in AzuraCast).

**Comment by williambatson** [comment]
Thanks Afonso -  Did exactly that -  here's what the status line says when it tries to connect:

Inactive (Error parsing xml document: A string literal was expected, but no opening quote character was found. Line: 1<!DOCTYPE html> <html><head><meta charset)

**Comment by williambatson** [comment]
Think I almost found it -  in port it needs to be
Port: 8000/stats?sid=1
Just gotta figure out the SID for the station I want to use :)     But testing it on a test server with one station   SID 1 worked, linked succcesfully

**Comment by afonsosantos** [comment]
Nice you found it out, I never used SHOUTcast with SAMBC, so I was not quite sure about the correct settings.

**Comment by williambatson** [comment]
Do you know how to find the SID for station in question?  Isn't there a shoutcast page accessable on the server?

**Comment by afonsosantos** [comment]
Yes, you can access it using the `<SHOUTcast_IP>:<PORT>` address, available from the AzuraCast dashboard. There you can login using **admin** and the **admin password**, and see all the stations, including the SID. Usually, if you only have 1 radio station, the SID is `1`

**Comment by williambatson** [comment]
Just to clarify - then I'll close this but is good reference
Older versions of SAM want  Port: 8000/stats?sid=1
The latest SAM 2019 which is subscription based has a lines for 
Port: 8000
SID: 1

So how you set this depends on which version of SAM you are using.   Again thanks Afonso for pointing me in the right direction.   For those wanting listener data to show on their SAM dashboard, this is an extra step needed in the SAM program.

**Comment by afonsosantos** [comment]
Glad I helped, thank you for the guide!
