### ISSUE TITLE
Problem with long track 

### ISSUE THREAD

**Issue by NanoLYC** [AzuraCast/AzuraCast#1996]
Hi, 
Sometimes (sorry), a long track (podcast during 1h ou 2h) of Scheduled playlist don't play or stop playing after 1 minute, 1 hour. 
I've check the logs of liquidsoap but nothing show why. 
Example, saturday night at 9pm, We play a podcast of 2h (dj mix). The track start at 9pm (ok) but at 9:01pm track stop and liquidsoap switch to rotate playlist. 
Any ideas? 
Thanks 
Nano

**Playlist configuration** 
- Priority = 5
- Random (contain 1 track)
- Scheduled = 9pm to 11pm / Saturday
- Advanced options : Interrupt other songs to play at scheduled time.
- Advanced options : Only play one track at scheduled time.

**Relevant Logs**

```
2019/09/21 21:00:00 [goneupradio_interrupt_switch:3] Switch to sequence_6619 with transition.
2019/09/21 21:00:00 [lang:3] AzuraCast Feedback Response: OK
2019/09/21 21:00:02 [clock.wallclock_main:2] We must catchup 1.08 seconds!
2019/09/21 21:00:03 [clock.wallclock_main:2] We must catchup 1.08 seconds!
2019/09/21 21:01:17 [playlist_ronsha_mix:3] Finished with "/var/azuracast/stations/goneupradio/media/Ronsha Mix/ronsha_mix_-23149.mp3".
2019/09/21 21:01:17 [goneupradio_interrupt_switch:3] Switch to goneupradio_autodj_fallback with forgetful transition.
2019/09/21 21:01:18 [lang:3] AzuraCast Feedback Response: OK
2019/09/21 21:05:08 [clock.wallclock_main:2] We must catchup 1.17 seconds!
2019/09/21 21:06:06 [lang:3] AzuraCast Raw Response: annotate:title="Mandatory feat. Royce Da 5’9″ (Prod. Daringer)",duration="21.",song_id="baf028bc7d68b3646a5952abefc39936",artist="Conway",jingle_mode="true":/var/azuracast/stations/goneupradio/media/Jingles_Shows/nextelevelpt2_jingle-rotation.mp3
2019/09/21 21:06:06 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/goneupradio/media/Jingles_Shows/nextelevelpt2_jingle-rotation.mp3".
2019/09/21 21:06:18 [goneupradio_next_song:3] Finished with "/var/azuracast/stations/goneupradio/media/HipHop/_conway_-_mandatory_feat._royce_da_5r9P_-28prod._daringer-29.mp3".
2019/09/21 21:06:18 [goneupradio_next_song:3] Prepared "/var/azuracast/stations/goneupradio/media/Jingles_Shows/nextelevelpt2_jingle-rotation.mp3" (RID 21).
2019/09/21 21:06:18 [lang:3] AzuraCast Feedback Response: OK
```
**Host Operating System**
Ubuntu 18.04

**Using Docker installation method**
Yes

**Comment by SlvrEagle23** [comment]
@NanoLYC The "interrupt other songs" setting applies to both the beginning of the track and the end of the track. Basically, the setting means that it will play _exactly_ within the specified time slot, starting at the exact start and ending at the exact end. This is a setting internal to Liquidsoap, so unfortunately there isn't anything we can do about it from the AzuraCast side.

**Comment by NanoLYC** [comment]
Hi! 
Thanks for your answer. 
But this setting is applied on the long track playlist and not on background rotation. 
The long track length is 2h. Why liquidsoap stop playing while 1h59 remain? He stop because the track who’s playing before ending in background? 
It’s just for understand and search to apply the good settings. Except this small problem azuracast change my life (like J Dilla!) thanks for the work. 
Thank you.
