### ISSUE TITLE
Request Button Cut Out In Portrait

### ISSUE THREAD

**Issue by ItsJamieHosie** [AzuraCast/AzuraCast#1997]
Hey,

Not Really A Major Issue But A Listener I Have Who Listens Via The Public Page Can Only Get The Request Button To Show When They Put There Phone In Landscape They Are On Android But I Have No Issues With It On My iPhone In Landscape Or Portrait Request Button Shows For Me, Just Wondering If There Is Anything They Have To Do Or Something I Need To Do?

Cheers :)

**Comment by biguenique** [comment]
You can insert Custom CSS (for Public Pages) to adjust the display in Administration > Custom Branding.
