### ISSUE TITLE
Normalization and replay gain

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#200]
Hello, just to know if Liquidsoap uses it system and if it is not possible to add it?
http://liquidsoap.fm/doc-dev/replay_gain.html
Why not add an Enhancer / Exciter to have a more FM radio sound : 
http://liquidsoap.fm/doc-dev/reference.html#Source___Sound_Processing

**Comment by SlvrEagle23** [comment]
@ckeurk AzuraCast has support for custom LiquidSoap parameters in the "Advanced: Custom LiquidSoap Configuration" section of the application. You can put any valid .liq code into that section.

The reason we don't automatically add custom sound processing into AzuraCast is twofold:
* Each station will usually want their own equalization settings, and it would be impossible to come up with a standard that would please everyone, and
* Additional audio processing consumes extra CPU cycles, and the stock AzuraCast install is meant to be as lightweight and easy on CPU as possible.

**Comment by ckeurk** [comment]
Ok I understand, but personally I try to put code to precisely have a normalization of the sound  in the "Advanced: Custom LiquidSoap Configuration", but it does not work. I am not very strong in this field.
I think I'm not the only one, It is possible to have a quick example ?

**Comment by rolradio** [comment]
That would also be interesting to me, such an example.

**Comment by SlvrEagle23** [comment]
If you add in custom configuration, it inserts it very close to the bottom of the automatically generated LiquidSoap configuration file. Here's an example file, along with the custom configuration section included:

```ocaml
# WARNING! This file is automatically generated by AzuraCast.
# Do not update it directly!

set("init.daemon", false)
# ...(more settings)...

# AutoDJ Next Song Script
def azuracast_next_song() =
# ...
end

# DJ Authentication
def dj_auth(user,password) =
# ...
end

live_enabled = ref false
# ...live_connected, live_disconnected...

# Fallback Playlists
playlist_default = playlist(reload_mode="watch","/var/azuracast/stations/azuratest_radio/playlists/playlist_default.m3u")

playlists = random(weights=[3], [playlist_default]);
dynamic = request.dynamic(id="azuracast_next_song", azuracast_next_song)
dynamic = cue_cut(id="azuracast_next_song_cued", dynamic)
radio = fallback(track_sensitive = false, [dynamic, playlists, blank(duration=2.)])

live = audio_to_stereo(input.harbor("/", port=8005, user="shoutcast", auth=dj_auth, icy=true, max=30., buffer=5., on_connect=live_connected, on_disconnect=live_disconnected))
ignore(output.dummy(live, fallible=true))
live = fallback(track_sensitive=false, [live, blank(duration=2.)])

radio = switch(id="live_switch", track_sensitive=false, [({!live_enabled}, live), ({true}, radio)])

# Crossfading
radio = crossfade(start_next=3.,fade_out=2.,fade_in=2.,radio)

# Custom Configuration (Specified in Station Profile)
radio = nrj(radio)

# Outbound Broadcast
output.shoutcast(%mp3.cbr(samplerate=44100,stereo=true,bitrate=128), id="radio_out_1", host = "localhost", port = 8000, password = "stream_pw:#1", name = "AzuraTest Radio", url = "docker.local", public = false, radio)
```

By the time you get to the radio customization section, the `radio` variable represents the current stream of audio as it's about to be output to ShoutCast, etc.

In the custom configuration, you can therefore modify the audio by compressing it, equalizing it, normalizing the volume, etc.

One popular function that's included in LiquidSoap is called `nrj`. The function, which I use in the above example, compresses and normalizes the volume, creating a "flatter" sound that is often more pleasing, especially on lower bitrates. To enable this, you would just paste the following into your LiquidSoap custom configuration:

```ocaml
radio = nrj(radio)
```

You can view all of the functions for sound processing (there's a LOT) in the [LiquidSoap reference guide](http://savonet.sourceforge.net/doc-svn/reference.html#Source___Sound_Processing).

Hopefully this helps explain more about this configuration option.

**Comment by ckeurk** [comment]
Thank you very much for enlightening us :)

**Comment by SlvrEagle23** [comment]
Happy to help :)

**Comment by rmacari** [comment]
Guys, 

I know this topic has one year already, and maybe this is why i can't find this Advanced option on my new AzuraCast server. Can i ask some help on how to implement the following option to my liquidsoap? 

# Custom Configuration (Specified in Station Profile)
radio = nrj(radio)

Appreciate the help.
Thanks!

**Comment by SlvrEagle23** [comment]
![2018-11-13 00_08_34- development edit profile - azuracast](https://user-images.githubusercontent.com/6744885/48394234-58af2d80-e6d8-11e8-9e45-df0d4e16a4ff.png)

@rmacari There's an "Advanced: Custom Configuration" section at the bottom of your station's profile. You can put any valid Liquidsoap configuration code you want into that section, including the code you mentioned above. It will merge it into the auto-generated Liquidsoap configuration.
