### ISSUE TITLE
Can´t login

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#2000]
I can´t login, since last update.

Installation: Tradicional

OS: Ubuntu 18

**Comment by rubensben** [comment]
Same here

**Comment by talionwar** [comment]
I've the same problem with ubuntu 18, installation:docker

**Comment by rubensben** [comment]
happened this latest commit version : d4bf8b0 and no problem before abc9930

**Comment by SC2Mitch** [comment]
Same issue here

**Comment by afonsosantos** [comment]
Hi @SC2Mitch , @talionwar , @rubensben , @jonikane 

This issue is known by the lead developer and is going to be fixed ASAP.

Thank you.

**Comment by SC2Mitch** [comment]
now works fine, as per the latest update

**Comment by SlvrEagle23** [comment]
@SC2Mitch @talionwar @rubensben @jonikane This should be fixed as of the latest update to AzuraCast this evening.

We were evaluating switching to a "storageless" way of managing sessions, which relied upon sending signed tokens to your browser, but there was definitely a problem with a number of browsers and installation scenarios where this new method didn't work. This evening we switched back to using Redis as our session manager, but with improvements in place that still help us keep many of the benefits of the new system.
