### ISSUE TITLE
Amazon AWS

### ISSUE THREAD

**Issue by gsarg** [AzuraCast/AzuraCast#2006]
Hello how are you?
Is Azuracast compatible with Amazon vps?

I get the following error when installing.

Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Creating network "azuracast_default" with the default driver
Creating volume "azuracast_db_data" with default driver
Creating volume "azuracast_influx_data" with default driver
Creating volume "azuracast_letsencrypt" with default driver
Creating volume "azuracast_shoutcast2_install" with default driver
Creating volume "azuracast_station_data" with default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_www_data" with default driver
Creating volume "azuracast_redis_data" with default driver
Creating volume "azuracast_backups" with default driver
Creating azuracast_redis_1    ... error
Creating azuracast_influxdb_1 ... 
Creating azuracast_stations   ... 
Creating azuracast_mariadb_1  ... 

ERROR: for azuracast_redis_1  Cannot start service redis: OCI runtime create failed: container_linux.go:348: starting container proCreating azuracast_mariadb_1  ... error
Creating azuracast_influxdb_1 ... error
ERROR: for azuracast_mariadb_1  Cannot start service mariadb: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown

Creating azuracast_stations   ... error
er process caused "process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown

ERROR: for azuracast_stations  Cannot start service stations: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:301: running exec setns process for init caused \"exit status 23\"": unknown

ERROR: for redis  Cannot start service redis: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown

ERROR: for mariadb  Cannot start service mariadb: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown

ERROR: for influxdb  Cannot start service influxdb: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown

ERROR: for stations  Cannot start service stations: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:301: running exec setns process for init caused \"exit status 23\"": unknown
ERROR: Encountered errors while bringing up the project.
Starting azuracast_redis_1    ... error
Starting azuracast_mariadb_1 ... 
Starting azuracast_influxdb_1 ... 
Starting azuracast_stations   ... 
Starting azuracast_mariadb_1  ... error
ERROR: for azuracast_redis_1  Cannot start service redis: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown

Starting azuracast_influxdb_1 ... error
 process caused "process_linux.go:301: running exec setns process for init caused \"exit status 23\"": unknown

ERROR: for azuracast_influxdb_1  Cannot start service influxdb: OCI runtime create failed: container_linux.go:348: starting containStarting azuracast_stations   ... error

ERROR: for azuracast_stations  Cannot start service stations: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:301: running exec setns process for init caused \"exit status 23\"": unknown

ERROR: for redis  Cannot start service redis: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown

ERROR: for mariadb  Cannot start service mariadb: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:301: running exec setns process for init caused \"exit status 23\"": unknown

ERROR: for influxdb  Cannot start service influxdb: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown

ERROR: for stations  Cannot start service stations: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:301: running exec setns process for init caused \"exit status 23\"": unknown
ERROR: Encountered errors while bringing up the project.

**Comment by Vaalyn** [comment]
Hey, can you clarify which AWS product you are using?

It could be that the product you are trying to use is not compatible with the Docker runtime engine.
