### ISSUE TITLE
New installation error

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2007]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
while install getting this error: (at the end)

In RequestException.php line 113:

  Server error: `GET https://php-chronicle.pie-hosted.com/chronicle/lookup/PW9pdgWmCjmswCmDLzJY5
  1ENVdBRcZcJiUwKHBfQc2k=` resulted in a `502 Bad Gateway` response:
  <html>
  <head><title>502 Bad Gateway</title></head>
  <body>
  <center><h1>502 Bad Gateway</h1></center>
  <hr><center>ngin (truncated...)

azuracast:setup [--update] [--load-fixtures] [--release]

2019/09/25 19:41:11 Command exited with error: exit status 255

**Comment by SlvrEagle23** [comment]
@eranwo Thank you for the report. We are aware of some issues with the upstream server that serves our CA (HTTPS security) certificates. We're working on bundling an up-to-date version of the certificates locally so we don't need to worry about fetching them during the install/update process, which is what's causing the problem you're experiencing.

**Comment by eranwo** [comment]
@SlvrEagle23 Thank you for the fast reply. Does it only interfere with the install/update process? Or it also can disrupts the system regularly?

**Comment by SlvrEagle23** [comment]
@eranwo A little of both, depending on what you're doing on the system. I spoke with the upstream maintainer of the `Certainty` CA certificate manager that we use and they're working to improve the overall stability of the remote service.

For now, though, in the interest of making sure new installations work without any issues, I've switched to a different, local method of pulling CA certificates. This will make sure installations (and other instances where the system has to make secure external connections) work without issue.
