### ISSUE TITLE
Question - How to generate missing log files? 

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2008]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.4

**Describe the bug**
Log files are missing, how to generate them? (Missing LS log, Icecast access Log and Icecast Error log
**To Reproduce**
N/A 
**Expected behavior**
N/A
**Relevant Logs**
Error! Log file not found 
**Screenshots**
https://puu.sh/ElkAu/a76b886420.png 

**Device(s):**
Windows 10, Chrome latest version, desktop
**Additional context**
If someone can help me regenerate these files it'd be amazing!

**Comment by SlvrEagle23** [comment]
@SC2Mitch That tends to indicate that nothing has been written to those files yet, so they simply haven't been created. You shouldn't ever need to manually create or update log files.

If you absolutely need to, though, you could run:

```bash
cd /var/azuracast
docker-compose exec --user="azuracast" web bash
```
then, inside the container:
``
cd /var/azuracast/www/stations/(station_name)/config
touch liquidsoap.liq
```

**Comment by SC2Mitch** [comment]
thanks
