### ISSUE TITLE
Changing album artwork width to 150px

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#2009]
Hello!

I've made some CSS changes on custom branding page with doing players artwork size to 150px instead of 75px default and player looks much better for me and feedbacks of 4-5 guys that I asked streaming on my server. For example: https://my.radiolize.com/public/demo

But the only thing is iframe codes on dashboards comes with 150px width and when you copy-paste it directly, player display crashes. If I change 150px to 300px on iframe code it looks well on external players too.

**Request: Display album artworks 150px instead of 75px on both public stream page and external player iframe.**

I think this would be a quickly done visual improvement. Please check the example page and tell what you guys think about it, so developers may decide to make it.

The codes I've used to make it:

Custom CSS for Public Pages:
> .radio-player-widget .now-playing-details .now-playing-art img{
>     width: 150px!important;
>   }

Iframe code for each station:
> min-height: 150px; -> min-height: 250px;

All the best.

**Comment by Vaalyn** [comment]
I looked at the public player of the demo installation and compared the default 75px album cover size vs your proposed 150px version.

In my opinion changing the size to 150px adds a lot of unnecessary white space to the player which gives of a feeling that it's somehow not intended to look like that or is not finished from the design perspective. (See screenshots at the bottom)

In general I'd recommend you to post suggestions for UI/UX improvements in the [Visual / UI / UX improvements](https://github.com/AzuraCast/AzuraCast/issues/1501) issue. I created that issue to aggregate all kinds of suggestions regarding improvements to the UI of AzuraCast which are not classified as bugs or errors.

Comparison screenshots:

![image](https://user-images.githubusercontent.com/13745863/65815102-fb867280-e1ea-11e9-9d99-0dbdbe6dfc5e.png)

![image](https://user-images.githubusercontent.com/13745863/65815098-f1fd0a80-e1ea-11e9-922b-4b9b9bd1809e.png)
