### ISSUE TITLE
Scaleway ARMv8 azuracast installation

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#201]
Hello,

I tried to install azuracast on docker image on the scaleway armv8 server,but still not able to install on it.
I you can look into it?

**Comment by SlvrEagle23** [comment]
@surihost Docker is only currently supported for x86/x64 machines. We currently don't have a build process that can build ARM-friendly Docker images. Only the traditional installation will work with ARMHF servers, and even in that case, Scaleway is not entirely supported.
