### ISSUE TITLE
Question: In Listener's tab - user agent is Empty

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#2011]
Just a general question

Sometimes the user agent says "EMPTY" or sometimes it says "Python script". Usually, the IP is from China or Russia.

Does it mean, a bot is listening to your station?

Thanks guys!

**Comment by SC2Mitch** [comment]
Normally bot IP are still logged, in our cases, they are still okay. And we occasionally get the RU but, not CN tho.

**Comment by yarik2720** [comment]
That bots are usually scans your current playing track. They are used for sites with internet radio catalogue

**Comment by ErnestPH** [comment]
Ahh in short they are harmless… Thanks guys!
