### ISSUE TITLE
Extend Width Size of Player on Public Page to 100% 

### ISSUE THREAD

**Issue by pwrj** [AzuraCast/AzuraCast#2014]
I wonder is it possible to extend Width Size of Player on Public Page to 100% with custom css on the custom branding area. See below:

<img width="1298" alt="Screen Shot 2019-09-28 at 2 45 28 PM" src="https://user-images.githubusercontent.com/7035452/65821078-d7cd2780-e1fe-11e9-92d9-0ebfb9f18873.png">

**Comment by Vaalyn** [comment]
Yes this is possible. The `card` element can be accessed liked this:
```
body.page-minimal .public-page .card {
    ... Custom CSS ...
}
```

You can try playing around with CSS by opening the browsers developer console and adding CSS to elements there to see how it looks like before applying it for everyone.

**Comment by pwrj** [comment]
@Vaalyn Thank you!!
