### ISSUE TITLE
Error posting to twitter

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#2015]
![Bildschirmfoto von 2019-09-29 08-36-00](https://user-images.githubusercontent.com/7961/65827963-077b3e80-e296-11e9-971e-5ed1ef170a2f.png)

**Comment by SlvrEagle23** [comment]
@macbroadcast We've been working on this specific issue over the last few days, and we've worked with the upstream maintainer to help prevent this from happening during regular operation. If you update to the very latest version of the AzuraCast code, it shouldn't have this issue any more.

**Comment by macbroadcast** [comment]
Upstream Maintainer? I am on Version v0.9.5, cant update and it ever happened before, so this is just temporary?

**Comment by Vaalyn** [comment]
@macbroadcast The current version is `v0.9.6.5, #d7819a6`. Is there a specific reason or problem that prevents you from being able to update your installation?

**Comment by macbroadcast** [comment]
The version works perfect on a 5 $ droplet and for the update, i need to update to a 10 $ droplet :smile_cat:

**Comment by SlvrEagle23** [comment]
@macbroadcast I don't understand why updating would require moving from a $5 VPS to a $10 one.

Also, if you don't update your installation to the latest version to apply changes we make that fix the issues you're reporting, there's nothing we can do to fix those issues. We can't retroactively go back and fix code that's already published without a subsequent update.

**Comment by macbroadcast** [comment]
@SlvrEagle23 Wow now my station is completely gone ?   
![Bildschirmfoto von 2019-09-30 08-02-41](https://user-images.githubusercontent.com/7961/65853252-2bec1f00-e359-11e9-8059-bd15bb9c119a.png)


UPDATE:
``root@stream:~# ./docker.sh update-self
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11429  100 11429    0     0  63494      0 --:--:-- --:--:-- --:--:-- 63849
New Docker utility script downloaded.
./docker.sh: line 348: azuracast: command not found
./docker.sh: line 349: syntax error near unexpected token `}'
./docker.sh: line 349: `}'
root@stream:~# 
``

**Comment by SlvrEagle23** [comment]
@macbroadcast Your station isn't gone, there was just an error during the update process.

Try re-pulling down the Docker utility script by hand:
```
cd /var/azuracast
curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh
chmod a+x docker.sh
./docker.sh update
```

This happens from time to time and you can always follow those same instructions for resolving it.

**Comment by macbroadcast** [comment]
@SlvrEagle23 Thanks that method bypassed the "unexpected token" error , BUT

``Installing azuracast/azuracast (dev-master c0d53654077b1158ea36e512eee5e214148cffb7)
  - Installing azuracast/azuracast (dev-master c0d5365): The following exception is caused by a lack of memory or swap, or not having swap configured
Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details

PHP Warning:  proc_open(): fork failed - Cannot allocate memory in phar:///usr/bin/composer/vendor/symfony/console/Application.php on line 952

Warning: proc_open(): fork failed - Cannot allocate memory in phar:///usr/bin/composer/vendor/symfony/console/Application.php on line 952
                                                     
  [ErrorException]                                   
  proc_open(): fork failed - Cannot allocate memory  
                                                     

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

Composer could not find a composer.json file in /var/azuracast/www
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Could not open input file: bin/azuracast.php
2019/09/30 06:44:02 Command exited with error: exit status 1
azuracast_stations is up-to-date
azuracast_influxdb_1 is up-to-date
azuracast_mariadb_1 is up-to-date
azuracast_redis_1 is up-to-date
Creating azuracast_web_1 ... done
Untagged: azuracast/azuracast_radio@sha256:ae1311c494e85b2aca6511ecd7a4d0edcaae17ac3792213255aa4bacf0f22b91
``

I ama little bit concerned to created the swap space once i did and i messed up the whole droplet
so upgrade to bigger droplet, seems my only solution right ?

**Comment by macbroadcast** [comment]
Alright 10 bucks
