### ISSUE TITLE
UPDATE to latest version - Still display wrong next track when playlist runs

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#2019]
I forgot which ticket it was but i raised this issue earlier and i thought there was a liquidsoap rewrite or reintegration? But in the current playlist, it still displays  the next song after the playlist and not the next in the playlist 

During "Babylon Sisters" Playlist there is no Ramstein :joy_cat: 

![Bildschirmfoto von 2019-09-30 20-28-44](https://user-images.githubusercontent.com/7961/65905586-1ca0bc00-e3c1-11e9-8c5d-590e771b43e2.png)

![Bildschirmfoto von 2019-09-30 20-26-35](https://user-images.githubusercontent.com/7961/65905594-21657000-e3c1-11e9-9d4b-36965645b1b6.png)

**Comment by netbladenl** [comment]
Try to restart your station after updating, this seems to solved my problem.
