### ISSUE TITLE
Error upon install (Ubuntu Server 16.04)

### ISSUE THREAD

**Issue by kkraku** [AzuraCast/AzuraCast#202]
```
Creating azuracast_mariadb_1 ... done

ERROR: for azuracast_stations  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for stations  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
azuracast_influxdb_1 is up-to-date
Starting azuracast_stations ... 
azuracast_mariadb_1 is up-to-date
azuracast_redis_1 is up-to-date
Starting azuracast_stations ... error

ERROR: for azuracast_stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (4c8683ea8a3c90f67a3343f888b1683662fc39265c93bb315b985a014d07e5fd): fork/exec /usr/bin/docker-proxy: cannot allocate memory

ERROR: for stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (4c8683ea8a3c90f67a3343f888b1683662fc39265c93bb315b985a014d07e5fd): fork/exec /usr/bin/docker-proxy: cannot allocate memory
ERROR: Encountered errors while bringing up the project.
```

This is from using the guide and doing a docker based install using the script.

**Comment by SlvrEagle23** [comment]
@kkraku It seems that this is an issue with Docker/Compose itself, not AzuraCast. You may want to use the uninstall script and try reinstalling again; it might have been a temporary problem.

**Comment by kkraku** [comment]
I'll give it a try, and report back in a couple minutes.

**Comment by kkraku** [comment]
Unfortunately, with a reinstall the problem persists. I tried navigating to my IP even after the errors and I get a blank page. The log reported connectivity issues which are unlikely as I am on a Microsoft Azure host.
It's a very odd issue, I hope I've provided the right info.

```
Creating azuracast_redis_1 ... 
Creating azuracast_influxdb_1
Creating azuracast_mariadb_1
Creating azuracast_redis_1
Creating azuracast_redis_1 ... done

ERROR: for azuracast_stations  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for stations  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
root@RabidRadio:/home/rabid/AzuraCast# 
```

**Comment by SlvrEagle23** [comment]
@kkraku I'm genuinely not sure what's causing this issue, but I have some measure of confidence that it *isn't* something inside AzuraCast. This seems to be a Docker-based configuration issue. Unfortunately, I'm not in the position to diagnose such issues, as I'm stretched fairly thin just responding to issues specific to the web application itself.

If anyone else has seen this issue and knows of any fixes to it, I'll leave this issue open with the "Help Wanted" tag for a little while.

**Comment by kkraku** [comment]
It was very odd but I never found any reasoning for it. Worked perfectly in my friends box however, very odd issue. 

Was never able to install it on Azure.

Very happy with the software, however! It is working very well for us and we offer our gratitude for your work on it.
