### ISSUE TITLE
Error starting station

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#2020]
Error starting station.
Every time I create a new station, it doesn't work. Points out the following errors:

Icecast encontrou um erro
19-09-30 15:34:19] EROR main/fatal_error FATAL: error parsing config file (/var/azuracast/stations/brega)
[2019-09-30 15:34:19] EROR main/fatal_error XML config parsing error
[2019-09-30 15:48:20] WARN xml/parsing Is a directory
[2019-09-30 15:48:20] WARN xml/parsing /var/azuracast/stations/brega Document is empty
[2019-09-30 15:48:20] EROR main/fatal_error FATAL: error parsing config file (/var/azuracast/stations/brega)
[2019-09-30 15:48:20] EROR main/fatal_error XML config parsing error

_______________

Liquidsoap encontrou um erro
Called from file "main.ml", line 130, characters 16-31
Called from file "arg.ml", line 261, characters 11-20
Called from file "main.ml", line 528, characters 6-35
Called from file "main.ml", line 556, characters 4-94
Called from file "main.ml", line 635, characters 6-16
Called from file "runner.ml", line 30, characters 14-31

**Comment by Rafaelrds2017** [comment]
I tried to update and said that:

no such file or directory

**Comment by SC2Mitch** [comment]
Is this issue still present for you? I've tried it, works fine for me?

**Comment by Rafaelrds2017** [comment]
> Esse problema ainda está presente para você? Eu tentei, funciona bem para mim?

In my self hosted installation this error still continues.
If I create new radios some radios work. But there is no audio.

I can't update my azura either. points out the following error

No such file or directory

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 That sounds like a permissions issue on your station directory. Are you doing anything unusual there, like mounting it to another storage location?

**Comment by Rafaelrds2017** [comment]
> @ Rafaelrds2017 Parece um problema de permissão no diretório da estação. Você está fazendo algo incomum lá, como montá-lo em outro local de armazenamento?

Everything is running normally. Just from today gave this error.

The current radios are still in the air. Only those created from now on will not work.

I use the same services and storage location.

Services.
NYC3 - Ubuntu - digitalocean

_______________________________
Installing

mkdir -p /var/azuracast
cd /var/azuracast

curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh
chmod a+x docker.sh
./docker.sh install

Updating

./docker.sh update-self
./docker.sh update

_______________________________
