### ISSUE TITLE
Forward AzuraCast stream to AzuraCast stream

### ISSUE THREAD

**Issue by Rootinator** [AzuraCast/AzuraCast#2021]
Hi,

How can I forward an AzuraCast stream to an AzuraCast stream?

Both stations run on the same instance.

**Comment by biguenique** [comment]
It's possible to *pull* the stream for station A to station B.

On station A, copy the address of the stream you want to pull into B.

![1  Copy source link](https://user-images.githubusercontent.com/566304/66576472-c57bb380-eb45-11e9-8e9f-9c746bc73d3f.png)

On station B, create a new playlist and give it a name. In the **Source** section:

- Source: select **Remote URL Playlist**
- Remote URL: paste the URL of the stream mountpoint
- Remote URL Type: select **Direct Stream URL**

![2  Configuring remote stream source](https://user-images.githubusercontent.com/566304/66576962-944fb300-eb46-11e9-8f4c-f9dc006a1817.png)

Configure you scheduling and save changes.

You might need to restart Liquidsoad (AutoDJ) for the new playlist to kick in. If you need to troubleshoot, check your logs in Administration > System Logs.

- Check station A's Icecast Access Log to make sure B has access to the stream
- Check station B's Liquidsoap Log to see if there is any error
- Check station B's Liquidsoap Config and make sure your new playlist uses `input.http` (the lines should be around the top of the script).

```
playlist_pull = mksafe(input.http(max=20., "http://azura.radio.fiatlux.tk:8000/premiere.mp3?1570716504"))
playlist_pull = audio_to_stereo(id="stereo_playlist_pull", playlist_pull)
```

**Comment by Rootinator** [comment]
Actually I wanted to capture the stream directly from AzuraCast and not the already sent stream.
