### ISSUE TITLE
Error 500 EntityRepository.php : 235 (edit music)

### ISSUE THREAD

**Issue by thiagocrossman** [AzuraCast/AzuraCast#2022]
500
Undefined method 'fetchArray'. The method name must start with either findBy, findOneBy or countBy!
EntityRepository.php : 235

**Comment by SlvrEagle23** [comment]
@thiagocrossman Thank you for the report. This should be fixed as of the latest update published just a few minutes ago. Please update and verify that everything is working as intended.
