### ISSUE TITLE
ERROR EDIT SONG

### ISSUE THREAD

**Issue by Takumi86ES** [AzuraCast/AzuraCast#2023]
Error edit song.

https://i.gyazo.com/ea857b827195234c0da4d15f4b4b0d90.png

**Comment by SC2Mitch** [comment]
I've tried editing a song and it works fine for me, are you on the latest version?

**Comment by SlvrEagle23** [comment]
@Takumi86ES Please make sure you're on the very latest version of AzuraCast. This error may have appeared for versions released over the last few days, but the latest version should no longer have this issue.

**Comment by Takumi86ES** [comment]
close.
