### ISSUE TITLE
 it doesn't show live listener statistics?

### ISSUE THREAD

**Issue by KoneSV** [AzuraCast/AzuraCast#2024]
Ansible method:

Because if streaming doesn't send the track title playing now, it doesn't show live listener statistics?

1- AzuraCast Perfil Radio: https://ibb.co/DrHZLh4
2- ShoutCast Port: https://ibb.co/pKJNWtT
3- Statistics Listener: https://ibb.co/T4KGF6T

Error happens with all radios that do not send "Playing Now"

**Comment by liloue4** [comment]
hello i have this same problem to , i use centos 7  and docker install

**Comment by liloue4** [comment]
hmm sorry is work now just one error from me

**Comment by KoneSV** [comment]
If the error is in not sending the metadata so that it can be seen Playing Now
