### ISSUE TITLE
"Auto Assign" ID3 attribute in the global Custom Fields <-> nowplaying_api

### ISSUE THREAD

**Issue by kemecs** [AzuraCast/AzuraCast#2025]
I like the new feature

![image](https://user-images.githubusercontent.com/8629116/65971948-56c59880-e469-11e9-9bfb-4cc2cf1877c2.png)

I like the new service!
but it is unfortunate that nowplaying_api still does not write the contents of the custom_field field if you use the advanced special custom setting of AutoDJ

"now_playing":{"elapsed":101,"remaining":0,"sh_id":16239,"played_at":1569938729,"duration":0,"playlist":"","is_request":false,"song":{"id":"fdc4cb18305fa735c31226ec51c50fad","text":"ujelonepzene609 - ujelonepzene609","artist":"ujelonepzene609","title":"ujelonepzene609","album":"","lyrics":"","art":"https:\/\/folktest.folkradio.hu\/static\/img\/generic_song.jpg","custom_fields":{"folkmp3_id":**null**}}},"

Using Docker installation method = Yes
Host Operating System = ubuntu 18.04

**Comment by eranwo** [comment]
@kemecs  I think it works only on new mp3 files - not on the existing files
It's a great feature.

**Comment by kemecs** [comment]
yes i now

![image](https://user-images.githubusercontent.com/8629116/66003648-066d2b80-e4a7-11e9-82e2-c3b2ef887cb8.png)
