### ISSUE TITLE
Please indicate with the time display format

### ISSUE THREAD

**Issue by kaster1980** [AzuraCast/AzuraCast#2026]
Good day. Please tell me how to set the time display format in 24-hour format, so that for example it has a simple look: 22:30, without PM UTC inscriptions? And also how to make the date Oct 1, 2019 look like 1 Oct 2019?Thank you in advance for your help!

**Comment by SlvrEagle23** [comment]
@kaster1980 The fact that the locale didn't update the time format was a bug that should've been fixed with the latest update.
