### ISSUE TITLE
External Server Storage

### ISSUE THREAD

**Issue by Linchen-Online** [AzuraCast/AzuraCast#2027]
Hello, how can i mount an external server and the storage of this to Azuracast storage. 

This is a traditional installation.

The storage server is by another provider as the azuracast instance.

Thanks

**Comment by SlvrEagle23** [comment]
@Linchen-Online The traditional installation is not supported for a majority of cases when using AzuraCast. We recommend using the Docker installation instead.

If you're using the Traditional installation, you can specify a custom media directory that is anywhere on your filesystem. As long as you can mount your external storage as a directory on your server, you can use it as your media directory just by editing the station's profile.
