### ISSUE TITLE
issues if importing mp3 files via webinterface

### ISSUE THREAD

**Issue by derkalle4** [AzuraCast/AzuraCast#203]
You closed the last issue but I did a complete reinstall on my Proxmox Virtual Environment -> even created a completely new virtual machine With Ubuntu 16.04 x64 and used your manual install with "install.sh". And it's just giving me se same error like before. Column count doesn't match... It's very strange. I can't really tell you why. Only other option for me would be to have a test environment outside of Proxmox. But it's a production system with plenty of virtual servers since years (and kept them up to date) and I never have experienced any problems yet.

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

Steps to reproduce:
- created folder "musik"
- created folder "Alle Farben"
- created folder "Live Circus"
- Uploaded 8 mp3 titles successfully
- run the cronjob via http://example.com/admin/sync/medium
- error below pops up:

```
Doctrine \ DBAL \ Exception \ DriverException
An exception occurred while executing 'INSERT INTO station_media (station_id, song_id, title, artist, album, isrc, length, length_text, path, mtime, fade_overlap, fade_in, fade_out, cue_in, cue_out) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "b21aa5e756ad6f9c0e8ccfaf74f8f1f1", "Bad Ideas (Joris Delacroix Extended Remix)", "Alle Farben", "Live Circus", null, 365.6881632653061, "6:05", "musik\/Alle Farben\/Live Circus\/02_bad_ideas_-28joris_delacroix_extend.mp3", 1501445303, null, null, null, null, null]: SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1
```
At least the files do not get moved to another folder. Maybe they'll get processed from time to time (over the next hours). So I will keep an eye on them over the next hours.

**Comment by SlvrEagle23** [comment]
@derkalle4 I'm still entirely unable to reproduce this issue on my local or demo installations. Even using the MP3s you supplied in that exact folder structure, things still import just fine.

There may be some problem caused by the fact that the ID3 inspector is producing a length field that's a float value (365.688...) and trying to write that into a smallint field, so I pushed out a minor update that rounds the value.

That's about the only thing I can think of to address the issue.

**Comment by SlvrEagle23** [comment]
@derkalle4 In the last few weeks I've updated MariaDB to be version 10.2 across all installations, added full support for UTF8MB4 columns in the database, and expanded support for unicode across the application.

Please test the latest version of the AzuraCast application and let me know if you're still encountering the issue.

**Comment by derkalle4** [comment]
Hey @SlvrEagle23 ,

sorry for the late reply. Got a lot of things to do. Somehow your script does not work well with OpenVZ-Containers but with KVM Containers. So Problem wen't away after changing this. I don't know why and I don't know how that could happen... even the integration of an external SQL-Database did not help..

Seems strange but is fixed for me. So thank you for your great support!

**Comment by ma9807** [comment]
I can fix all issues with Azuracast. I CAN FIX ALL ISSUES WITH THE MP3 PLAYLIST ISSUES..EMAIL ME AT PROJECT2138@yahoo.com
