### ISSUE TITLE
The PLAY buttons on "Station Overview" stopped working probably since one of the lately updates

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2032]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
When pressing the PLAY button, nothing happens.

**Screenshots**

![image](https://user-images.githubusercontent.com/2701228/66184808-00817100-e686-11e9-92e1-753e6c3a7ae0.png)

**Comment by SlvrEagle23** [comment]
@eranwo I've figured out the cause of this problem and pushed up a solution a few minutes ago.
