### ISSUE TITLE
Default cover art URL issue

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#2033]
By default the URL of the default Azuracast cover art (the "musical note") is `/static/img/generic_song.jpg` relative to the URL of the Azuracast server. Our frontend makes this assumption (if we see this URL in the API, we do this and that). The issue is that we sometimes see that Azuracast sends a custom URL instead of the above one (the picture is still the generic song cover art), which messes up our frontend. Did anyone ever have it?

**Comment by SlvrEagle23** [comment]
@gammaw You can actually just specify a default album artwork image in the settings field, which will override the image path that's presented to the user in any event that there's no album art.

It's possible we can be more consistent in whether we return an image URL for a piece of media that may not actually have any album art associated with it. I'll look into it and update on this issue.

**Comment by gammaw** [comment]
@SlvrEagle23 ah I see under Custom Branding. Thanks, I didn't know that. 

But yes, the question was more about the consistency so thanks if you can look into that.

**Comment by gammaw** [comment]
@SlvrEagle23 the issue occurred again (with a fresh 0.9.7.1 installation) and this time I copied the URL from the nowplaying API: `https://[RADIO_URL]/api/station/1/art/03c5e7ca21c2aabb4f4fcb27.jpg`
This URL shows indeed to the default image but since we didn't upload a custom image we would expect that the well-formed URL of the the default image appears here. Which is true most of the time but sometimes such a "random" URL shows up.

**Comment by SlvrEagle23** [comment]
@gammaw This is fixed as of the album art update in #2076.
