### ISSUE TITLE
500 No valid bundles were found in the data directory. Fetch.php : 100

### ISSUE THREAD

**Issue by gothicdude1044** [AzuraCast/AzuraCast#2036]
**Using Docker installation method**

Yes
**Host Operating System**

linux ubuntu 18.04 lts
**Describe the bug**

Two of my 3 Webhooks are not working the one that posts to discord and twitter both stopped working 9-27-19
Everytime one of my djs connect my discord goes off and it has not since 9-27 same with the auto tweeter web hook
**To Reproduce**

Ive Went to the Station management page went to webhooks and clicked on test for both of the problem web hooks and it gives me a 500
No valid bundles were found in the data directory.
Fetch.php : 100 error
then i clicked on the working webhook and had no issues.

**Expected behavior**

I expect the webhook to post to my discord and twitter no luck
**Relevant Logs**

Only error i could find is this [2019-10-06T00:41:57.066867+00:00] AzuraCast.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded {"file":"/var/azuracast/www/vendor/slim/http/src/Response.php","line":193,"code":5} []
This is just after the webhook test.

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SC2Mitch** [comment]
To help the developers, can you run `docker-compose logs -f` while doing this? It might show the error that Azuracast Logs wouldn't.

**Comment by gothicdude1044** [comment]
![azuracast error from console](https://user-images.githubusercontent.com/1172741/66262676-d7123380-e7b2-11e9-8aea-44e6f5de9cf3.png)
this is what console after i hit test webhook

**Comment by SlvrEagle23** [comment]
@gothicdude1044 This should've been fixed as of an update a few days ago...can you update to the very latest version and let me know if it resolves it?

**Comment by rmacari** [comment]
The same issue here looks like that stopped working a few days ago.
Used the command docker-compose logs -f but logs show nothing.

**Comment by rmacari** [comment]
Just did a full update and that fixed the issue. :)

cd /var/azuracast/
./docker.sh update-self && echo "y" | ./docker.sh update

**Comment by SlvrEagle23** [comment]
@gothicdude1044 Our latest point releases 0.9.7 and 0.9.7.1 include fixes for this issue. Updating is highly recommended for all users.
