### ISSUE TITLE
Web Image Is Missing /var/azuracast/www/ contents

### ISSUE THREAD

**Issue by TheRevenantStar** [AzuraCast/AzuraCast#2037]
**Using Docker installation method** Yes

**Host Operating System** Ubuntu 18.04

**Describe the bug** 
The latest image azuracast/azuracast_web_v2 is missing data in it's /var/azuracast/www directory

**To Reproduce**
Run the ```docker.sh install``` script

**Expected behavior** Azuracast to come up and be available

**Relevant Logs**
```web_1       | Could not open input file: /var/azuracast/www/util/cli.php```
(This just echoes over and over)

**Screenshots**
(This is a screenshot from Dive to explore the filesystem state at each layer, I am on the final layer)
![image](https://user-images.githubusercontent.com/40784277/66272638-fac88e80-e831-11e9-8fa6-f50265a1fb39.png)

**Device(s):**
 - Device: CiscoMCS 7800 / MacBookPro 2018
 - OS: Ubuntu 18.04
 - Browser: N/A
 - Version: N/A

**Additional context**
I have verified the files are missing even when the image pulled onto other devices.
Additionally, can known working images be archived with a version number to dockerhub?
Since "latest" is the only available tag, we cannot use an older, working, image.

**Comment by SlvrEagle23** [comment]
@TheRevenantStar The installation script should automatically pull down the code from the Composer Packagist repository. The reason we don't populate the code directly in the Docker image is because we want the same image to be usable with multiple versions of the codebase; you can, in fact, install either a release version, the latest rolling-release dev-master version, or any commit you specify into the same web container and it will work without issue.

**Comment by TheRevenantStar** [comment]
If it should auto download, why didn't it? Did I miss a step?

**Comment by SlvrEagle23** [comment]
@TheRevenantStar Did you see any errors in the `./docker.sh install` script? It should specifically pull down the latest version during the installation. If it didn't, you can always just run the installer again and it should work fine.

**Comment by CodeSteele** [comment]
This happened to me when I moved my docker volume directory after finishing the install, obviously trashing the changes made to the containers. May just want to re-run the installer.

**Comment by CodeSteele** [comment]
Nix that -- even after a reinstall I'm having issues, let me check....

**Comment by CodeSteele** [comment]
Running `./docker.sh uninstall` then `./docker.sh install` seems to have fixed it.

**Comment by CodeSteele** [comment]
I did also have an issue where I'd get errors during the application install because the node only had 1GB of RAM and would out of memory.
