### ISSUE TITLE
Songs playback order in speciphic playlist

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2038]
Ubuntu 18.04

Is it possible to add in playlist editor the option to determine the songs playback order?
sequential or random

**Comment by biguenique** [comment]
Playlists > Edit playlist

In source, under *Song Playback Order*, you can select **Sequential**

![Sequential Playlist](https://user-images.githubusercontent.com/566304/66579237-7f751e80-eb4a-11e9-9635-2ab36b9f911e.png)

If you need to change order of a playlist, download the playlist (Export M3U), edit it with a text editor, and upload it back.

**Comment by wmfinck** [comment]
I am trying to migrate from doing liquidsoap scripts by hand to Azuracast, which also has other benefits. But Azuracast keeps randomly changing the order in which recordings are played. This is a deal-breaker for me. Selecting "sequential" and carefully choosing the order of recordings is fruitless.
