### ISSUE TITLE
missing folders in azuracast directory

### ISSUE THREAD

**Issue by streamjamz** [AzuraCast/AzuraCast#2043]
**Using Docker installation method**

YES
**Host Operating System**

Ubuntu 18.04
**Describe the bug**

missing /var/azuracast/www
missing /var/azuracast/stations
**To Reproduce**

**Expected behavior**

well i'm a newbie and i followed the instructions as is stated, it works but i don't see those folders when i go to that directory, not sure if thats what it should look like, also i have a wildcard ssl for the domain i'm using and I've been trying to get ssl running but haven't had any luck

**Relevant Logs**

Station not found. {"file":"/var/azuracast/www/src/Middleware/RequireStation.php","line":26,"code":0}
**Screenshots**

![azura](https://user-images.githubusercontent.com/8143373/66529661-3f725500-ead2-11e9-8914-22cd5d810a4d.PNG)
![Capture2](https://user-images.githubusercontent.com/8143373/66529828-f4a50d00-ead2-11e9-8b58-a97cec59f2d9.PNG)

**Device(s):**
 - Device: 
dekstop
 - OS: 
 - Browser: 
chrome
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@streamjamz The "station not found" error is meant to inform you that you went to a URL that corresponds to a station that doesn't exist. It shouldn't be coming up randomly unless you're actually visiting URLs for stations that don't actually exist in the system.

**Comment by streamjamz** [comment]
so even though the directory doesnt show the www directory its correct, because i only have the page open where the station is playing and the profile page thats it

**Comment by MrSteelMiner** [comment]
The Shorturl isn't working. But you can paste the raw link ^^

**Comment by streamjamz** [comment]
MrSteelMiner here is the url http://cloud.sjamz.com:8888/public/dave_demo_station
its the only station i have setup and thats the only url thats working, but what i was saying is i dont see a www folder in the /var/azuracast/ directory hence why i think the error is there because that folder doesnt exist as seens in screenshot
![azura](https://user-images.githubusercontent.com/8143373/66559710-d6b3c880-eb23-11e9-8d26-5f5beccac3e6.PNG)

**Comment by biguenique** [comment]
I see that you are standing in /var/azuracast on your server's filesystem. The thing is that AzuraCast's www directory is actually *inside* the docker volume.  To open a bash session *into* the docker file system, try the following command:

`sudo docker exec -i -t azuracast_web_1 /bin/bash`

That should open a prompt as root@<volume_hash> in /var/azuracast/www

Works for me!

For more details : https://askubuntu.com/q/505506

**Comment by biguenique** [comment]
You might need this too : instructions to [mount a host directory into a station](https://www.azuracast.com/help/faq_docker.html#mounting-a-directory-into-a-station).

This way you'll be able to expose host files to the station (and vice-versa).

Note that you'll need to duplicate the same directory mapping on both the 'web' and 'stations' services if you want your mapping to work correctly.

**Comment by streamjamz** [comment]
> I see that you are standing in /var/azuracast on your server's filesystem. The thing is that AzuraCast's www directory is actually _inside_ the docker volume. To open a bash session _into_ the docker file system, try the following command:
> 
> `sudo docker exec -i -t azuracast_web_1 /bin/bash`
> 
> That should open a prompt as root@<volume_hash> in /var/azuracast/www
> 
> Works for me!
> 
> For more details : https://askubuntu.com/q/505506

Thank you very much i'm finally understanding more, i gotten it to work, i also got ssl to work as well

**Comment by chosin1ne** [comment]
How did you get the SSL to work on the port? I'm using CentOS 7 - Plesk Onyx and a DV SSL but I can't get the port number for Azuracast to secure.
