### ISSUE TITLE
Error displaying default album art after updating

### ISSUE THREAD

**Issue by biguenique** [AzuraCast/AzuraCast#2045]
Default album art displays as broken image link since last update (anywhere on the site).

Just updated to AzuraCast • v0.9.6.5, #3150531 (2019-10-10 5:20) • Docker • PHP 7.2

![1-now-playing](https://user-images.githubusercontent.com/566304/66564857-0916f300-eb2f-11e9-8bc9-0a31f0e326a6.png)
![2-music-files](https://user-images.githubusercontent.com/566304/66564859-0916f300-eb2f-11e9-8b6d-8ad1086621f8.png)

When clicking broken image, the following message pops up: "The requested content cannot be loaded. Please try again later."

![3-pop-up](https://user-images.githubusercontent.com/566304/66564860-09af8980-eb2f-11e9-8822-347055040234.png)

When right clicking broken image > Open in a new tab, a 500 error page shows up with message: "Call to a member function getDefaultAlbumArtUrl() on null
GetArtAction.php : 62"

![4-500-error](https://user-images.githubusercontent.com/566304/66564861-09af8980-eb2f-11e9-9708-5cad4b413171.png)

Setting a custom default cover doesn't change anything. Songs having a cover display ok. Everything worked well before the update.

Thanks for your help.

**Comment by SlvrEagle23** [comment]
@biguenique This is fixed as of the latest update just a few minutes ago. Thank you for reporting this issue.
