### ISSUE TITLE
Many songs show the wrong duration (too short)

### ISSUE THREAD

**Issue by biguenique** [AzuraCast/AzuraCast#2046]
I have many songs that display the wrong duration (too short).

Possible cause: I recently uploaded many songs by FTP, updating playlists periodically with uploaded folders while it was uploading. I suspect that some durations were calculated on incompletely uploaded files.

When I run a 5-minute sync task to Update Media Folders, all files are marked as unchanged and none is updated.

Is there a way to re-scan the music library to update the tracks with their correct durations? Should I 'touch' every file to update their modified time? Or would just moving them around (rename folders) through FTP be sufficient to cause a re-scan?

**Comment by SlvrEagle23** [comment]
@biguenique We have a CLI command that specifically allows you to do this! You can invoke it from the parent server by running:

```bash
cd /var/azuracast
./docker.sh cli azuracast:media:reprocess
```

**Comment by biguenique** [comment]
Thanks @SlvrEagle23 - you people rock!
