### ISSUE TITLE
Album art disappeared since today update v0.9.6.5, #3150531

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2048]
**Using Docker installation method**
 Yes
**Host Operating System**
Ubuntu 16.04

**Describe the bug*
v0.9.6.5, #3150531

**Screenshots**
![image](https://user-images.githubusercontent.com/2701228/66575688-06dc8500-eb7f-11e9-93a0-2ed52d3bac72.png)

**Comment by SC2Mitch** [comment]
web_1       | Oct 10 21:21:50 e32df4d4ef76 php-fpm[63]: [WARNING] [pool www] child 13752 said into stderr: "[2019-10-10T21:21:50.126049+00:00] AzuraCast.ERROR: Call to a member function getDefaultAlbumArtUrl() on null {"file":"/var/azuracast/www/src/Controller/Api/Stations/Media/GetArtAction.php","line":62,"code":0} []"

Error from `docker-compose logs -f`

**Comment by rmacari** [comment]
Same issue here after update.

link to album art:
http://domain.../api/station/1/art/5c04fa7f677d0cdce378bdd1.jpg
result page:
500

Call to a member function getDefaultAlbumArtUrl() on null
GetArtAction.php : 62

**Comment by SlvrEagle23** [comment]
@eranwo @rmacari @SC2Mitch This should be fixed as of the latest update a few minutes ago.
