### ISSUE TITLE
Playlist content not visible

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#2049]
Ansible installation

Since last(?) update, you cannot list a playlist's content by clicking on the title count.
![image](https://user-images.githubusercontent.com/47743654/66675189-17ffc180-ec65-11e9-9479-55e1b7bcee29.png)

![image](https://user-images.githubusercontent.com/47743654/66675206-22ba5680-ec65-11e9-8042-a5993b21c288.png)

**Comment by SlvrEagle23** [comment]
@MrSteelMiner Figured out the problem and published an update a few minutes ago that should fix it. Thanks for letting me know!
