### ISSUE TITLE
Station Statistics (English/French)

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#205]
A small display bug between the French version and the default version (English) 
(Mac : Safari - Version 10.1.2 (12603.3.8)
![station statistics](https://user-images.githubusercontent.com/379099/28830223-7548fb2e-76d6-11e7-897f-1e2a6d497cf8.png)
![station](https://user-images.githubusercontent.com/379099/28830287-98e4c162-76d6-11e7-91d1-cf901694df24.png)

**Comment by SlvrEagle23** [comment]
@ckeurk Thanks for the report! This one was rather simple: the words for certain items on the chart contained apostrophes in French (but not English) and were throwing off the browser. All translated variables in the charts are now escaped to avoid this being an issue.
