### ISSUE TITLE
Connecting problems

### ISSUE THREAD

**Issue by MilanD-7025** [AzuraCast/AzuraCast#2050]
Hey, I've tried to connect to my AzuraCast radio station, But my "login or password" are incorrect. Even tho its correct. I've tried restarting my station, enable/disable DJ's but nothing seems to be working. Am I doing something wrong?

**Comment by SC2Mitch** [comment]
You running the latest version of Azura?

**Comment by DJAzure** [comment]
I have the latest version of azure. Installed yesterday. @SC2Mitch

**Comment by SlvrEagle23** [comment]
@DJAzure You mean you're trying to connect as a DJ? What connection settings are you using, and what software are you connecting with?

**Comment by DJAzure** [comment]
@SlvrEagle23 
I'm trying to connect as DJ
Here is what MIXXX says when connecting:
https://gyazo.com/47a3c095229744e3d0ee302977590912

The login is correct.

**Comment by DJAzure** [comment]
https://gyazo.com/1488ea43085c0a62f600b3c2d9e51f59

**Comment by DJAzure** [comment]
@SlvrEagle23 You there?

**Comment by SlvrEagle23** [comment]
@DJAzure don't do that. We're on GitHub, not Discord. :P

I'll take a look as soon as I can.
