### ISSUE TITLE
Backup UI Stalls Until Backup is done

### ISSUE THREAD

**Issue by CodeSteele** [AzuraCast/AzuraCast#2051]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 16.04

**Describe the bug**
When you run a manual backup, the UI times out waiting for the backup to complete.

**To Reproduce**
1. Run a manual backup

**Expected behavior**
You're either immediately returned to the backup list page while the backup runs in the background (it currently does anyway), or are returned to a status page that'll tell me when the backup is done.

**Relevant Logs**
N/A

**Screenshots**
N/A

**Device(s):**
N/A

**Additional context**
N/A

**Comment by SlvrEagle23** [comment]
This has been fixed by recent improvements to how backups are handled; they're now a background task that writes its ongoing log to a text file, which you can view in a "log viewer"-style modal dialog box to follow it as it goes, without interrupting your main web request.
