### ISSUE TITLE
i cant hear from public page

### ISSUE THREAD

**Issue by machetedj** [AzuraCast/AzuraCast#2052]
**Using Docker installation method**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@machetedj Please provide some additional information and complete the issue template.
