### ISSUE TITLE
How do I get the source password of the station?

### ISSUE THREAD

**Issue by AleAmla987** [AzuraCast/AzuraCast#2056]
How do I get the source password of the station?

**Comment by SlvrEagle23** [comment]
@AleAmla987 It should be listed on the station's profile on the right side, under the broadcasting software (i.e. Icecast).

**Comment by AleAmla987** [comment]
In the Api Station / id-station does not return the password for the connection or the port, what is the api that is used for that?

**Comment by SlvrEagle23** [comment]
@AleAmla987 The more detailed station information can be obtained via `/api/admin/station/{station_id}`.

**Comment by AleAmla987** [comment]
Sure, but it doesn't have the data like the PORT, PASSWORD, or anything to connect from winamp or another client.

**Comment by SlvrEagle23** [comment]
@AleAmla987 The `/admin/station/{station_id}` endpoint, as opposed to the `/station/{station_id}` endpoint, absolutely does have the necessary information. You can find it inside `frontend_config` and `backend_config`.
