### ISSUE TITLE
Display Name

### ISSUE THREAD

**Issue by jvarweg** [AzuraCast/AzuraCast#2057]
When a DJ are encoding on the stream and a another DJ connect, the encoder gives the code:

"Error $indyThreadSock.Execute: Connection Closed Gracefully. (200)"

But the display names changed to that user that try to connect. 

Do you have a fix?

**Comment by SlvrEagle23** [comment]
@jvarweg This is likely caused by the fact that AzuraCast only updates the currently connected DJ when they successfully authenticate, but in this case Liquidsoap is kicking out the incoming streamer.

I'll have to look into our Liquidsoap integration to see if there's a better way to do that.

**Comment by jvarweg** [comment]
Do you have look to it and fix it in a update? Or not?

**Comment by SlvrEagle23** [comment]
@jvarweg I spoke with the Liquidsoap team about the issue, but it seems that there may not be much we can do within the confines of the Liquidsoap "HTTP Harbor" input that we use for streaming connections.

I will update you if this changes, but this may be a known issue with no current solution.
