### ISSUE TITLE
Cannot install Docker

### ISSUE THREAD

**Issue by clintguy74** [AzuraCast/AzuraCast#2058]
Hello, I was able to install azuracast last week on a docker no problem.

But today, I keep getting the following:

Docker is already installed! Continuing...
Docker Compose is already installed! Continuing...
Pulling mariadb (azuracast/azuracast_db:latest)...
**ERROR: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)**
Pulling mariadb (azuracast/azuracast_db:latest)...
ERROR: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io: No address associated with hostname
Pulling mariadb (azuracast/azuracast_db:latest)...
ERROR: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution

Is anybody else experiencing this issue?

When I go to that address, it says forbidden.

**Comment by SlvrEagle23** [comment]
@clintguy74 This is definitely an issue with the Docker Hub (and not AzuraCast in particular), but if you continue to experience it for more than a few hours please let us know. It could also be something to do with the DNS resolution on your server.

**Comment by clintguy74** [comment]
Thank you, It seems to have been with the service provider ISP, Im very
sorry. Please close the ticket, apologees for the stupidity  Thanks for a
great program. Love it.

Many Thanks

Clinton Bester
Sent from my portable desk..

mobile: 063 483 2448
skype: clintguy74
follow me on twitter : clintguy74

**Comment by SlvrEagle23** [comment]
@clintguy74 No worries at all, glad you were able to get it resolved.
