### ISSUE TITLE
error generating translation

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#2059]
ntend.po
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '../../resources/locale/translations.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Object.<anonymous> (/data/web/static/node_modules/easygettext/src/compile-cli.js:44:6)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! azuracast@ import-locales: `gettext-compile --output ../../resources/locale/translations.json $(find ../../resources/locale/*.UTF-8 -type f -name '*.po')`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the azuracast@ import-locales script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-10-13T15_42_38_372Z-debug.log

**Comment by susl16c** [comment]
_data/web/static/node_modules/easygettext - The script refers to this path, but it does not exist.

**Comment by SlvrEagle23** [comment]
@susl16c I can't reproduce this locally. What platform are you building on?

**Comment by susl16c** [comment]
I have the latest version of the script.

**Comment by susl16c** [comment]
Tell me at least where to look, everything will remain without translation, there is clearly a problem with the paths ?

**Comment by susl16c** [comment]
/var/lib/docker/volumes/azuracast_static_node_modules/_data/easygettext/src/compile-cli - no found

**Comment by SlvrEagle23** [comment]
@susl16c It's possible that because you don't have a file at `/var/azuracast/www/resources/locale/translations.json`. You may be able to fix the issue by running:

```
touch /var/azuracast/www/resources/locale/translations.json
chmod 777 /var/azuracast/www/resources/locale/translations.json
```

**Comment by susl16c** [comment]
There is a file and I already gave him rights 777 - It did not help
I don’t have this way var/lib/docker/volumes/azuracast_static_node_modules/_data/easygettext/src/compile-cli - no found
Although here you refer to this path at Object. (/data/web/static/node_modules/easygettext/src/compile-cli.js:44:6)
