### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by streamjamz** [AzuraCast/AzuraCast#2060]
**Using Docker installation method**

yes
**Host Operating System**

ubuntu 18.04
**Describe the bug**

**To Reproduce**

**Expected behavior**

to play a block with 4 adverts sequential then it goes back to playlist on the hour
**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

so i have created a playlist with commercials/adverts and i would love to have it play on the hour every hour, so far i haven't gotten it to play i have tried it with advanced playlist feature but i'm not sure how to set it up or if i did it correctly this is what i used radio = rotate(weights=[1,4], [playlist_commercials, radio]) any help pointing me in the right direction would be appreciated

**Comment by radiolize** [comment]
You may try to use Manual AutoDJ.

**Comment by streamjamz** [comment]
> You may try to use Manual AutoDJ.

i see the option but how would i configure that to work

**Comment by radiolize** [comment]
You should just go to station settings and enable/disable Manual DJ Mode. You may try both options. I'm not sure if it's gonna solve it but you may give it a shot.

**Comment by biguenique** [comment]
It's MUCH simpler to NOT use *Advanced* scheduling mode. You can already do what you want to achieve using regular scheduling.

- Scheduling : *Play every hour* (you can set the minute of the hour you want it to play) or *Once per x minute* (every 60 minutes)
- AutoDJ Scheduling Options: *Merge playlist to play as a single track.* (will play all your commercials in one go)

If you really want to do your custom scheduling, you should take a look at these:
- [Liquidsoap - Script language - Time intervals](https://www.liquidsoap.info/doc-1.3.7/language.html#time-intervals)
- [Liquidsoap - API Reference - switch](https://www.liquidsoap.info/doc-1.3.7/reference.html#switch)
- [Liquidsoap - API Reference - playlist.merge](https://www.liquidsoap.info/doc-1.3.7/reference.html#playlist.merge)
- [Liquidsoap - API Reference - merge_tracks](https://www.liquidsoap.info/doc-1.3.7/reference.html#merge_tracks)

Liquidsoap is indeed a powerful scripting language, but it is not always easy to grasp.

It is a good idea to first fiddle with the AutoDJ scheduling, and see how it is handled in Liquidsoap by AzuraCast by looking at the generated script in *Administration* > *System Logs* > [station name] > *Liquidsoap Configuration*. You can start from there as a base for your custom script.

As a more complex example, here is a technique I previously used with liquidsoap to schedule jingles and ids at different intervals (assuming you have jingles and ids playllists):

```
# Using a switch, we can control at what time we want jingles and ids triggered.
# Using a triggering window shorter than the applied delay,
# we make sure only one track will be triggered in every window.
# We also need to make sure that the next track will be available at the
# beginning of the next window.
radio = fallback(id="inserts",[switch(id="inserts_switch",[
 ({0m-12m or 30m-42m},delay(720., playlist_jingles)), # once every top half hour (event expires after 12 minutes (720 seconds))
 ({6m-27m or 36m-57m},delay(360., playlist_ids)) # once every other 6 minutes
]),radio]) #works yeah
```
