### ISSUE TITLE
HTTP Error 500 on Duplicate Songs Reports

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#2061]
Using Docker installation method
Yes

Host Operating System
Ubuntu

Describe the bug
Opening reports "Duplicate Songs" shows 500 error

To Reproduce

Go to Reports
Click on Duplicate Songs
Expected behavior
I expected to see list of duplicated songs

Not all stations but some stations give this error.

**Comment by radiolize** [comment]
As I have check, the station that has this error has more than 10 GB songs. And that station may have too much duplicated songs. Is that maybe the reason for this? Other stations don't have this problem only one station gives 500 error and that station is one of who needs that function.

**Comment by Vaalyn** [comment]
Is there anything in the Application Logs?

**Comment by radiolize** [comment]
Sorry for late reply. It was a though week. No, there is not any log as I've seen.

**Comment by radiolize** [comment]
Hi guys. Are there any news about this issue? If so I may update my instance.

**Comment by YosefAdPro** [comment]
i have same problem:

php error:

`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 2097152 bytes) in /var/azuracast/www/templates/stations/reports/duplicates.phtml on line 33
`

`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 2080768 bytes) in Unknown on line 0
`

I don't have a PHP limit:
`php -i | grep memory_limit
memory_limit => -1 =
`

> Is there anything in the Application Logs?

**Comment by Vaalyn** [comment]
> i have same problem:
> 
> php error:
> 
> `PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2097152 bytes) in /var/azuracast/www/templates/stations/reports/duplicates.phtml on line 33 `
> 
> `PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2080768 bytes) in Unknown on line 0 `
> 
> I don't have a PHP limit:
> `php -i | grep memory_limit => -1 = `
> 
> > Is there anything in the Application Logs?

The `php -i |  grep memory_limit` will give you the memory limit for the CLI but not for the PHP-FPM.
As the error message indicates your memory limit is set to 128mb which was the default defined in the `php.ini` until an update on the 24th of August which increased the limit to 256mb.

Are you on the newest version of AzuraCast?

You can also manually increase the memory limit by editing the `azuracast.env` file (take care to not mistakenly edit the `.env` file). There you can remove the `# ` from the line `# PHP_MEMORY_LIMIT=128M` and then increase that value as needed.

**Comment by YosefAdPro** [comment]
> Are you on the newest version of AzuraCast?
Yes
v0.9.7.1, #8e41e44 Ansible

**Comment by Vaalyn** [comment]
@YosefAdPro As you are using the mostly unsupported Ansible installation method the `php.ini` is built a bit differently. I'm not really familiar with the Ansible installation but I can't see any specific memory_limit configuration in the [Ansible tasks](https://github.com/AzuraCast/AzuraCast/blob/master/util/ansible/roles/php/tasks/main.yml#L58) so it's most likely on the default value.

You will have to manually adjust that in the  `/etc/php/7.2/fpm/php.ini`. Look for the option `memory_limit` and increase the value to example given  `256M` and then restart PHP-FPM via `service php7.2-fpm restart`.

**Comment by YosefAdPro** [comment]
> @YosefAdPro As you are using the mostly unsupported Ansible installation method the `php.ini` is built a bit differently. I'm not really familiar with the Ansible installation but I can't see any specific memory_limit configuration in the [Ansible tasks](https://github.com/AzuraCast/AzuraCast/blob/master/util/ansible/roles/php/tasks/main.yml#L58) so it's most likely on the default value.
> 
> You will have to manually adjust that in the `/etc/php/7.2/fpm/php.ini`. Look for the option `memory_limit` and increase the value to example given `256M` and then restart PHP-FPM via `service php7.2-fpm restart`.

I changed memory limit to 1G
But there is still an error

```
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 766385840 bytes) in /var/azuracast/www/vendor/league/plates/src/Template/Template.php on line 155
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 766386176 bytes) in Unknown on line 0
```
