### ISSUE TITLE
How to properly use the WebDJ feature?

### ISSUE THREAD

**Issue by aristosv** [AzuraCast/AzuraCast#2063]
Hello,

I am setting up a new azuracast server for a young journalist who wants to do live interviews, and listeners will be able to listen online. Of course there will also be music between the interviews. I've set up the server and a few stations for testing, and I have a few questions.

The idea is, music will be playing, and at some point the music will faint out, and the interview will start. Maybe low volume music will be playing in the background.

I am assuming the journalist will be using the WebDJ feature to do this?

I tried using WebDJ, but it's not really clear to me how it works. Most probably a DJ will be a lot more familiar with the interface.

When I press the red microphone icon in the microphone box, the music stops and I can hear my voice, but it's breaking. It's not really clear what I'm saying. And what does the Cue button do?

Also I what does the "Start Streaming" button do in WebDJ? The station is already streaming.

Is there a guide that explains what each thing in WebDJ does? Or can someone explain?

I searched for forums but I couldn't find any. So I asked here, I hope its OK.

**Comment by Skreffnet** [comment]
Hello, good morning, I have encountered the same problem.

Create a DJ account to use the WEBDJ but there is no way it works or you may not know how it goes. The thing is that I identify myself and accept the identification but when trying to listen to the player the AUTODJ comes out and not the DJ in broadcast. Can anyone tell me how this option works?
