### ISSUE TITLE
How modify default ports

### ISSUE THREAD

**Issue by rikknet** [AzuraCast/AzuraCast#2066]
**Using Docker installation method**

yes
**Host Operating System**

Ubuntu 18.04.3 (LTS) X64
**Describe the bug**

I want change default ports
**To Reproduce**

**Expected behavior**

use ports 7000-7999
**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

Hello.
I'm new with AZURACAST, I got a droplet with DigitalOcean, I had read how expand ports but not how use any others, for example in my case I want use ports 7000-7999 but I really don't know how do that.
I hope you can explain me how I can do it. (step by step if its possible for me and other that want do this).
Thank you for your help and for your great project.

**Comment by ogrenci01** [comment]
Hello @rikknet;

I am using Ansible but there was already a document for the Docker. Please visit here.

https://www.azuracast.com/help/faq_docker.html#expand-the-docker-radio-station-port-range
