### ISSUE TITLE
Album art cannot be edited (v0.9.7.1)

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#2067]
I'm running Azuracast's latest release (v0.9.7.1) with the following commit: #9bb2545 (2019-10-12 10:10). I cannot update the album art of songs (see screenshot). I have the following problems: 
- Upload new art button doesn't do anything. If I click into the field (No file chosen), the browser window appears. 
- It seems that the picture can be uploaded and saved but it has no effect. All I see is the default picture (see screenshot), even after I save, the window will be closed, refresh the page and reopen the song for edit. 

I know it's a very basic feature so maybe I'm doing something fundamentally wrong. Note: it's not a too big file I want to upload. Even if it was, there is no error message the way I know it in previous versions. 

Can anybody help? 

![image](https://user-images.githubusercontent.com/28865986/66864615-d8ebac00-ef95-11e9-900e-ff2d45f12f7d.png)

**Comment by SlvrEagle23** [comment]
@gammaw Are you selecting the image file, then clicking "Upload new art"? Is that just resetting you back to the default image?

You may need to open the web inspector and look at the network traffic as it's trying to save the image.

**Comment by gammaw** [comment]
@SlvrEagle23 oh I'm sorry, I completely misunderstood the new UI. I thought that "Upload new art" would trigger opening the file browser, closing the browser would select the art work file, and "Save Change" would upload the file. I'm using v0.9.6.5 so often, maybe I was driven by that design logic. Now I have to re-learn but I'll manage :) 

Maybe an improvement could be to somehow highlight that the field is "clickable".

**Comment by SlvrEagle23** [comment]
@gammaw It's hard for me to tell sometimes whether our users are just used to the previous UI, or if we just genuinely don't have an intuitive UI in the new version.

We could just simplify the process to have the upload field by itself, and have it automatically upload once a file is selected. Maybe that would be more intuitive by removing a step?

**Comment by gammaw** [comment]
@SlvrEagle23 yes, for me it would be more intuitive to use the field as display only (to show the uploaded file name, if any), use the Upload New Art button to trigger opening the file browser and to upload the file upon selecting a file (if not too big etc.) and Save Changes to confirm the transaction (Close would mean that the upload is ignored).

**Comment by SlvrEagle23** [comment]
@gammaw Considering that on that very same Media Manager page, selecting a file when you're uploading media automatically uploads it, I'm inclined to agree that having it require a button push when updating the album art is counterintuitive.

In the latest update I've made it so when a file is selected, it'll automatically upload. The "delete album artwork" button has been moved over to just under the existing thumbnail to visually imply association.

I think this should be a much more intuitive look.

**Comment by gammaw** [comment]
@SlvrEagle23 thanks!

**Comment by gammaw** [comment]
@SlvrEagle23 also nice to see that you removed the max 500px limit!

**Comment by SlvrEagle23** [comment]
@gammaw That was never a thing (or at least shouldn't have been). It would always just crop larger images down to the same aspect ratio but within a 1200x1200 square.

**Comment by gammaw** [comment]
@SlvrEagle23 I meant this warning. It's a picture (4032x3024 pixels) I cannot upload with v0.9.6.5 but it works with v0.9.7.1. 

![image](https://user-images.githubusercontent.com/28865986/67156693-6b87a480-f322-11e9-80bb-cd881a15694e.png)

**Comment by SlvrEagle23** [comment]
@gammaw Oh...yeah we switched the underlying functionality of that entirely, so the AzuraForms image size check didn't make it through. Probably for the best, honestly.

**Comment by gammaw** [comment]
@SlvrEagle23 definitely for the best! :) It was a headache for us when artists would send us high-resolution pictures and we had to downscale them first before uploading.

**Comment by gammaw** [comment]
@SlvrEagle23 fyi: a related feature request: https://azuracast.featureupvote.com/suggestions/62728/assign-playlist-within-music-file-editor-window

;)

**Comment by ChandigarIT** [comment]
I have a very similar problem, in Rolling Release #[08de0f9]

I click on the "edit" button for the media file, then the Album Art tab, click on the paper clip. File browser opens, I click on the picture that I want, and then "Open". 

It returns to this screen, but the picture on the left stays the same, previously, the file would upload at this point and the picture on the left would be replaced.  Pressing Save Changes just closes the popup screen with no change to the image.

![Screenshot 2022-12-27 at 09 55 31](https://user-images.githubusercontent.com/108827431/209648889-e8157831-bf52-4f97-af65-bb1b48c28991.png)

**Comment by ItsMitchh** [comment]
Post a new issue that isn't 3 yr old
