### ISSUE TITLE
Problems adding large music library on a playlist

### ISSUE THREAD

**Issue by jolo22** [AzuraCast/AzuraCast#2068]
Hello,

I discovered an issue within AzuraCast that doesn't happen before. When I add all my music from Music Files it will not do a thing but when only one or few is selected its fine. That doesn't happen in the past version of AzuraCast, I just set the Rows Per Page to All and selected all my music and it will be added to the playlist with no problems. 

I also encounter a syncing problem as well, after the 5-Minute Sync has lapsed, my music will not show up on the Music Files page, I need to force update it instead. But the weird thing is if I didn't do the force update every 5-Minute Sync has lapsed my Storage space on my server continues to increase to the point I couldn't login to AzuraCast and shows the 500 error instead that the disk is full. 

Screenshots below are the problem stated above.
![storage-problem](https://user-images.githubusercontent.com/15798127/66900913-3fbda380-f030-11e9-8f90-3c9f1d6e46d9.PNG)

![10GB Music files](https://user-images.githubusercontent.com/15798127/66900882-32a0b480-f030-11e9-98ff-0aab78b6d519.PNG)

and here is the 500 error.
![error-500-azuracast](https://user-images.githubusercontent.com/15798127/66912352-02afdc00-f045-11e9-9e85-aa3bbbd1bdf3.PNG)

**Comment by Simon818** [comment]
This is also happening to me when trying to add large numbers of files to a playlist. Probably the largest station has around 8000 songs in it. This is a very recent problem--or at least, it worked fine when we had 7000. I'm not able to find anything in logs or inspector that looks very relevant. When I press the save button, the popover for selecting playlists closes, but nothing happens. Importing an M3U from another station on the same machine also failed.
