### ISSUE TITLE
Move to Directory not working?

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2069]
Seems that it's not working ( i checked in demo.azuracast.com)
in the previous version was a button to select the directory to move
![image](https://user-images.githubusercontent.com/2701228/66912513-62918d00-f01b-11e9-892e-5e3cdd3484df.png)

**Comment by rmacari** [comment]
Did you try to update the system today? 
https://github.com/AzuraCast/AzuraCast/issues/2062#issuecomment-542608110

**Comment by eranwo** [comment]
Hi @rmacari,
I checked on the demo site again and i see that the "move" works now, but hey, where did the "Select" button gone?

**Comment by rmacari** [comment]
> Hi @rmacari,
> I checked on the demo site again and i see that the "move" works now, but hey, where did the "Select" button gone?


Hey!

It´s gone forever, they changed how that works. 
Update to the latest version, and when moving, select the file, click Move, select the target directory and it´s done. 

I hope it helps. :)

**Comment by eranwo** [comment]
Thank you! @rmacari
