### ISSUE TITLE
Feature Request: Installer for CentOS 7

### ISSUE THREAD

**Issue by SimStm** [AzuraCast/AzuraCast#207]
Is it possible to prepare a version who works with CentOS? (with a install script setting up all the required dependencies, etc)? Haven't tried to set up this manually on CentOS (I don't even know if it's possible because of some dependencies) but shouldn't be tricky to do.

**Comment by SlvrEagle23** [comment]
@SimStm The process of hunting down all the proper versions of each software package for each distribution is a fairly time-intensive one, and currently for AzuraCast this work falls squarely on my solo-developer shoulders. At the moment, it's unlikely that I'll have time in the near future to build out the traditional installer to support more installations.

The good news, however, is that the Docker installation will work on any platform that can run Docker, including CentoOS and even Windows and OSX (it's how I do my local development now, too). The Docker installer will pull down the latest version of the Docker Community Engine (the free version) for your platform, then set up the various components that AzuraCast uses.

For now, I'd highly recommend using the Docker solution if you're on a non-Ubuntu platform.

**Comment by susl16c** [comment]
How can I specify a different port for nginx and other components?

**Comment by XeroMirza** [comment]
> Is it possible to prepare a version who works with CentOS? (with a install script setting up all the required dependencies, etc)? Haven't tried to set up this manually on CentOS (I don't even know if it's possible because of some dependencies) but shouldn't be tricky to do.

hi AzuraCast install for CentOS 7 https://www.youtube.com/watch?v=MnmCZtzFmjw
