### ISSUE TITLE
No audio with ipv4 (docker on beta WSL2)

### ISSUE THREAD

**Issue by flobo09** [AzuraCast/AzuraCast#2072]
Good evening, i'm trying to setup Azuracast with the new (beta) WSL2 for Windows and hitting a blocking issue.

**Using Docker installation method**

Yes
**Host Operating System**

WSL 2 on Windows 10
**Describe the bug**

Azuracast itself seems to work perfectly and people can connect from the network after opening the correct ports. 

However, there is no audio on the public radio page and the stream link doesn't seem to be working. 

After investigation, it seems that it's because the build in Icecast server can only be accessed though localhost or http://[::1]/ (ipv6 localhost). 

The only way i can listen though the stream is at http://[::1]:8000/radio.mp3 or http://localhost:8000/radio.mp3

It can't be reached though the server local network area IP or 127.0.0.1 (unlike the main azuracast app portal which can be accessed though all of those, and even over the internet if ports are open). 

**To Reproduce**

Install on WSL2, set up the server with an IPV4 address .

**Expected behavior**

I should be able to connect to the stream. 

**Relevant Logs**

A few of those : 
 | [2019-10-17T18:06:31.388649+00:00] AzuraCast.INFO: Running Now Playing sync task [] []                                      web_1       | [2019-10-17T18:06:34.572265+00:00] AzuraCast.NOTICE: HTTP client GET call to http://192.168.1.80:8000/status-json.xsl produced response NULL [] {"station":{"id":1,"name":"Radio Twisters"}}

   | [2019-10-17T18:06:01.653058+00:00] AzuraCast.ERROR: cURL error 7: Failed to connect to 192.168.1.80 port 8000: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) {"file":"/var/azuracast/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":185,"code":0} {"station":{"id":1,"name":"Radio Twisters"}}

(Tried it with windows firewall fully disabled, no change)

**Screenshots**

**Device(s):**
Windows 10 18999
Edge chromium

**Comment by SlvrEagle23** [comment]
@flobo09 I'm not sure what specifically is causing this problem, but it's worth pointing out that WSL2 is still in a pre-release state, and we haven't even moved over to it for our own local development work (I'm currently using the standard Docker Desktop for Windows with Hyper-V). We're definitely keeping an eye on it, and once it makes it out into the stable releases and Docker Desktop correspondingly adds stable support for it, we'll switch to using it for local dev work and make sure it is compatible as well.

In the meantime, it's possible that you could use the "Web Radio Proxy" setting in the system-wide settings panel to alleviate some of the issue by having your listening URLs be based on your site's base URL and served via the web ports.
