### ISSUE TITLE
Use Replaygain Metadata / enable_replaygain_metadata is not working.

### ISSUE THREAD

**Issue by biguenique** [AzuraCast/AzuraCast#2074]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Relevant Logs**
No trace of "Replaygain" or related messages in any log.

**Describe the bug**
Enabling *Station Profile* > *Edit Profile* > *AutoDJ* > *Use Replaygain Metadata* has no effect.

**To Reproduce**
Fill your playlists with music with varying levels, check *Station Profile* > *Edit Profile* > *AutoDJ* > *Use Replaygain Metadata*, restart the station and listen.

**Expected behavior**
Enabling Replaygain should make Liquidsoap look up for a `REPLAYGAIN_TRACK_GAIN` metadata entry in each local media file. If missing, it should analyze the media and add the tag to the file. Then it should adjust the volume of the media using this information.

**Version details**
- AzuraCast 0.9.6.2 

Checking *Use Replaygain Metadata* adds a line in the liquidsoap script:
```
# Replaygain Metadata
enable_replaygain_metadata()
```

Notwithstanding this declaration, Liquidsoap silently ignores the existing `REPLAYGAIN_TRACK_GAIN` metadata and fails to compute one. This is pretty obvious on my station since I have a blend of file that were previously processed using `mp3tag` to 89 dB, and newly added (unprocessed) files with a `REPLAYGAIN_TRACK_GAIN` below -10 dB when analyzed using `loudgain` (so they very obviously sound about twice as loud).

Liquidsoap API Reference entry for [enable_replaygain_metadata](https://www.liquidsoap.info/doc-1.3.6/reference.html#enable_replaygain_metadata):

> Enable replay gain metadata resolver. This resolver will process any file decoded by liquidsoap and add a replay_gain metadata when this value could be computed. For a finer-grained replay gain processing, use the replay_gain protocol.
> 
> - `extract_replaygain` (`string` -- defaults to `"/usr/local/lib/liquidsoap/1.3.7/extract-replaygain"`): The extraction program

My guess is the declaration remains effectless since:

- The default value for `extract_replaygain` references a path that doesn't exist in the Docker `stations` container.
- Although *there is* a script named `extract-replaygain`. (`/var/azuracast/.opam/default/lib/liquidsoap/lib/liquidsoap/1.3.7/extract-replaygain`), it relies on command-line tools which *are not* installed in the container: `mp3tag`, `replaygain`, `vorbisgain`, `ogginfo` & `metaflac`.
- So even if we passed the script as `extract_replaygain` argument to `enable_replaygain_metadata` it would not work.

On the other hand, I can see this in the Liquidsoap script:
```
# Apply amplification metadata (if supplied)
radio = amplify(1., radio)
```

Proposed solutions:

- Either fix support for `renable_replaygain_metadata` (in which case I would recommend using `loudgain` instead of Liquidsoap's default `extract-replaygain` script, which relies on multiple command-line tools, some of which are no longer maintained)
- Either drop the `enable_replaygain_metadata()` declaration altogether and let the users deal with planning their file analysis (which is quite heavy on CPU), but change the line `radio = amplify(1., radio)` to `radio = amplify(1., override='REPLAYGAIN_TRACK_GAIN', radio`) to take the existing Replaygain metadata into account.
  - See: [Liquidsoap : Normalization and replay gain](https://www.liquidsoap.info/doc-1.3.7/replay_gain.html)
  - See: [Liquidsoap API Reference : amplify](https://www.liquidsoap.info/doc-1.3.7/reference.html#amplify)

**Comment by biguenique** [comment]
I see [here](https://github.com/savonet/liquidsoap/blob/master/scripts/extract-replaygain) that the `extract-replaygain` was updated to use `ffmpeg` and `gsed` in liquidsoap 1.4.0 (AzuraCast is currently using 1.3.7).

**Comment by SlvrEagle23** [comment]
@biguenique Sorry I haven't revisited this issue in some time. I let it slip down the to-do list and didn't get back to it for quite a while.

Now that we're on LS 1.4.0, am I correct in assuming that if we also package ffmpeg/gsed in our Docker container and Ansible install script, the extract-replaygain function should work as intended with no other modifications?

I have no problem doing that at all.

**Comment by EmpressFiona** [comment]
I was investigating this, on a hunch, and I think I may have figured out the issue. Per the [Liquidsoap documentation](https://www.liquidsoap.info/doc-dev/replay_gain.html), under "Applying replay gain information":

> After fetching or computing the replay gain information, the next step is to use it to correct the source’s volume.
>
> [...]
> 
> For convenience, we added the `replaygain` operator which performs the amplification on the right metadata so that this can further be simplified to
> 
> `enable_replaygain_metadata()`
> 
> `s = replaygain(playlist("~/playlist"))`

This is to say, `enable_replaygain_metadata()` does nothing on its own; you have to add it to the playlist call, otherwise it doesn't get applied to files being played back.

Having reviewed the Liquidsoap `extract-replaygain` script, I think Liquidsoap doesn't modify the source files. This might mean that it's processing the files each time if there's no existing metadata, so computing it once and storing it in the database for application via `lq_amplify` (or some new field) instead might be ideal.
