### ISSUE TITLE
No audio on Public player

### ISSUE THREAD

**Issue by RazielSama** [AzuraCast/AzuraCast#2075]
**Using Docker installation method** Yes

**Host Operating System** Linux debian 9

**Describe the bug** There is no audio from the public player. The title of the song is there, the time either, but there is no audio when you click play.

It is working only if i open the .mp3 in VLC or in the admin panel player.

**To Reproduce** https://srv.dunkerquestreetradio.eu/public/dksr

**Expected behavior**

**Relevant Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/36959038/67115733-27d85200-f1df-11e9-9aa4-18c7d8d99501.png)

**Device(s):**
It tried in Windows 10 [1903 18362.418] on: 
Chromium [77.0.3865.75]
Opera [64.0.3417.61]
Firefox [69.0.3 (64 bits)]
Microsoft Edge [44.18362.387.0]
Internet Explorer [11.418.18362.0]

**Additional context**
AzuraCast is up to date

Hello, You will find above an issue i have with my azura cast. Please help, this is a webradio for a non profit organization.

**Comment by semyonsh** [comment]
Have you tried restarting the station?

**Comment by RazielSama** [comment]
Yes.
I restarted the Station, the autoDJ, The entire Azuracast instance, even the VPS.

**Comment by semyonsh** [comment]
One last suggestion, does creating a new mount point help?

**Comment by RazielSama** [comment]
Nope, i just tried, exact same issue.

**Comment by RazielSama** [comment]
Thanks to an intervention in the slack channel it is solved.
The stream was disturbed because of the SSL feature. I have not activated the option in admin pannel "web proxy". This done, problem solved.

Hope this thread will help anyone who encounter this in the futur.
