### ISSUE TITLE
Skip song won't take effect

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#2077]
Hi, 

I'm on Azuracast v0.9.7.1, #d19e50a and it seems that Skip Song has no effect. This is what I see in the Liquidsoap log: 

```
2019/10/19 18:02:10 [server:3] New client: 172.25.0.6.
2019/10/19 18:02:10 [server:3] Client 172.25.0.6 disconnected.
2019/10/19 18:02:33 [server:3] New client: 172.25.0.6.
2019/10/19 18:02:33 [server:3] Client 172.25.0.6 disconnected.
```

Did anybody see something like this before? 

Thanks

**Comment by SlvrEagle23** [comment]
@gammaw This is unusual and definitely should be working.

What is the audio source of your current broadcast? Just standard playlists (i.e. not advanced or remote URL ones, or a live broadcast)?

The logs there look normal, but I'm not sure they would indicate that anything was wrong even if it was.

**Comment by gammaw** [comment]
@SlvrEagle23 it seems that the problem was on my side. I had an erroneous custom Liquidsoap configuration which interfered with the original `azuracast_next_song()` function. This wrong configuration may have caused this other issue (https://github.com/AzuraCast/AzuraCast/issues/2076) as well, so you may want to close both. Sorry for this!

**Comment by SlvrEagle23** [comment]
@gammaw No worries; glad you were able to get it resolved.
