### ISSUE TITLE
How to adjust the volume?

### ISSUE THREAD

**Issue by JohnJ0ng** [AzuraCast/AzuraCast#2078]
Hi, I am just wondering how I would be able to change the volume as it is very loud at the moment and has to be on like 3% to be at a bearable volume.

Thanks in advance :)

**Comment by SlvrEagle23** [comment]
@JohnJ0ng There are volume controls on all players within the application. In the case of the play buttons used throughout the administrative dashboard, those are controlled via an icon in the top right corner (a radio button); clicking that lets you pause the audio or change the volume. The volume on the public and embedded players is right alongside the play button.
