### ISSUE TITLE
songs title not updated anymore

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#208]
Hello,

I do see the songs title ( from the playlists ) are not updated in the main panel and as well on the shoutcast port page when playing next songs.

**Comment by SlvrEagle23** [comment]
@surihost I'm afraid I don't fully understand what issue you're describing. In any case, can you verify that it continues to be an issue as of the latest version of the code?

**Comment by treyturner** [comment]
I may be seeing this behavior. On the profile page, the 'On The Air' section doesn't display the currently playing song.

<img width="549" alt="azuracast_profile_page" src="https://user-images.githubusercontent.com/1878152/29491776-990fb2ba-852b-11e7-9f12-9e973b23a566.png">

Seems to be missing from the public stream page as well.

<img width="412" alt="azuracast_public_page" src="https://user-images.githubusercontent.com/1878152/29491777-a9cbbefa-852b-11e7-9dd4-c9d5d40cdcf2.PNG">

**Comment by treyturner** [comment]
Ok, I dug this up. I went to System Administration page and clicked on the box to run the Now Playing Data synchronization task. It returned:

```
Error thrown with message "Cannot access protected property Entity\StationMount::$name"

Stacktrace:
#25 Error in /var/azuracast/www/app/src/AzuraCast/Radio/Frontend/IceCast.php:98
#24 AzuraCast\Radio\Frontend\IceCast:_getNowPlaying in /var/azuracast/www/app/src/AzuraCast/Radio/Frontend/FrontendAbstract.php:105
#23 AzuraCast\Radio\Frontend\FrontendAbstract:getNowPlaying in /var/azuracast/www/app/src/AzuraCast/Sync/NowPlaying.php:118
#22 AzuraCast\Sync\NowPlaying:_processStation in /var/azuracast/www/app/src/AzuraCast/Sync/NowPlaying.php:92
#21 AzuraCast\Sync\NowPlaying:_loadNowPlaying in /var/azuracast/www/app/src/AzuraCast/Sync/NowPlaying.php:12
#20 AzuraCast\Sync\NowPlaying:run in /var/azuracast/www/app/src/AzuraCast/Sync.php:73
#19 AzuraCast\Sync:AzuraCast\{closure} in /var/azuracast/www/app/src/App/Debug.php:174
#18 App\Debug:runTimer in /var/azuracast/www/app/src/AzuraCast/Sync.php:74
#17 AzuraCast\Sync:syncNowplaying in /var/azuracast/www/app/modules/admin/controllers/IndexController.php:53
#16 Controller\Admin\IndexController:syncAction in /var/azuracast/www/app/src/App/Mvc/Controller.php:100
#15 App\Mvc\Controller:dispatch in /var/azuracast/www/app/src/App/Mvc/Resolver.php:42
#14 App\Mvc\Resolver:App\Mvc\{closure} in /var/azuracast/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:41
#13 call_user_func in /var/azuracast/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:41
#12 Slim\Handlers\Strategies\RequestResponse:__invoke in /var/azuracast/www/vendor/slim/slim/Slim/Route.php:340
#11 Slim\Route:__invoke in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:122
#10 Slim\Route:callMiddlewareStack in /var/azuracast/www/vendor/slim/slim/Slim/Route.php:316
#9 Slim\Route:run in /var/azuracast/www/vendor/slim/slim/Slim/App.php:476
#8 Slim\App:__invoke in /var/azuracast/www/app/bootstrap/services.php:351
#7 Closure:{closure} in /var/azuracast/www/vendor/slim/slim/Slim/DeferredCallable.php:43
#6 call_user_func_array in /var/azuracast/www/vendor/slim/slim/Slim/DeferredCallable.php:43
#5 Slim\DeferredCallable:__invoke in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:73
#4 call_user_func in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:73
#3 Slim\App:Slim\{closure} in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:122
#2 Slim\App:callMiddlewareStack in /var/azuracast/www/vendor/slim/slim/Slim/App.php:370
#1 Slim\App:process in /var/azuracast/www/vendor/slim/slim/Slim/App.php:295
#0 Slim\App:run in /var/azuracast/www/web/index.php:9
```

**Comment by SlvrEagle23** [comment]
@treyturner Yep, that would do it. Latest code push should fix that as well.

(Background for some of these errors: around 2011 or so, my codebases switched from Doctrine 1 to Doctrine 2, which was a huge paradigm shift from ActiveRecord to Hibernate-esque ORMs. To help ease the transition, I added wrappers to the Doctrine entities that supported the magic `__get`/set/etc, ArrayAccess and more...but these aren't a best practice. A huge commit about a week ago finally got around to removing all of this code...but the still present errors are highlighting missing spots in my unit/functional tests where issues still got through.)

**Comment by treyturner** [comment]
Fixed, thanks so much!
