### ISSUE TITLE
Azurcast is broken after update

### ISSUE THREAD

**Issue by clintguy74** [AzuraCast/AzuraCast#2080]
I did a docker update this morning, went out and nowI just get file cant be found on the web interface.

when I try and install docker in a docker, I get this:

Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

Is there a way just to install Azurcast without docker. ?

Or is there a version on VMs?

**Comment by SlvrEagle23** [comment]
@clintguy74 Try running:

```bash
cd /var/azuracast
cat docker-compose.yml
```

It's possible the update script didn't properly download the updated version of the `docker-compose.yml` file. GitHub has been pretty notorious for sending faulty versions of files over lately, and we're looking for alternatives to deliver updated versions of our code.

Despite the occasional error, Docker is still by far the easiest and most effective way for us to distribute updated versions of our application, since it allows us to pre-configure our entire software stack in a way that we know will work without issue. We do have another installation method, but because of the high risk of conflicting with other software, we don't offer official support for that installation method.

**Comment by h4de5** [comment]
this returns when I run `azuracast_install`:


azuracast_install
```
Installing AzuraCast...
(Environment: production)
Installing azuracast/azuracast (dev-master 17d306b97089003c1e38589b8d5d85b14c358947)
  - Installing azuracast/azuracast (dev-master 17d306b): Cloning 17d306b970 from cache
Created project in /var/azuracast/new
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
[20-Oct-2019 19:36:34 UTC] PHP Fatal error:  Uncaught ReflectionException: Class Azura\Doctrine\RepositoryFactory does not exist in /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php:45
Stack trace:
#0 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(45): ReflectionParameter->getClass()
#1 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(37): DI\Invoker\FactoryParameterResolver->getParameters(Object(ReflectionFunction), Array, Array)
#2 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(65): Invoker\ParameterResolver\ResolverChain->getParameters(Object(ReflectionFunction), Array, Array)
#3 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(116): Invoker\Invoker->call(Object(Closure), Array)
#4 /var/azuracast/www_tmp/CompiledContainer.php(398): DI\CompiledContainer->resolveFactory(Object(Closure), 'SubEntry5d7bf4e...')
#5 /var/azuracast/www_tmp/CompiledContainer.php(408): CompiledContainer->get5d7bf4e937151864798829()
#6 /var/azuracast/www/v in /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php on line 45
azuracast@766f7ac516aa:~/www$ vim /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php
azuracast@766f7ac516aa:~/www$ 2019/10/20 19:38:59 Received signal: terminated
exit
2019/10/20 19:38:59 Command finished successfully.
```

this may be part of the error.

yml-file is more or less default - just adding new volums and removing unused ports.
I tried using azuracast_stations and azuracast_radio image.

**Comment by h4de5** [comment]
same problem with `azuracast_install --update`

**Comment by SlvrEagle23** [comment]
@h4de5 That is likely not the same issue and should probably be its own GitHub issue.

**Comment by h4de5** [comment]
.... ok. `docker.sh update` fixed the issue .. sorry :(
have to check which part I missed in the procedure.

**Comment by jayhill90** [comment]
Seems like this can be closed out.
