### ISSUE TITLE
Music Page - Drag and Drop music doesn't seem to work in subfolders?

### ISSUE THREAD

**Issue by TogarUshindi** [AzuraCast/AzuraCast#2083]
Basically, make a folder, then make a folder within that folder, and the "Drag files here to upload to this folder or..." area ends up loading a blank sound file page and plays the song file locally instead of uploading.

This seems to happen (mostly) in subfolders. There have been occasions where it will happen in a folder, or sometimes even the root directory, but those usually work after clicking the back button and trying again. (In those instances, either it will open a new page and play the file, or it will ignore the drag and drop attempt entirely.)

Additionally, I used to be able to drag and drop multiple files at once, but now only one at a time seem to work, regardless of what folder location I happen to be in.

I just updated Azuracast a few minutes before attempting this.

**Comment by TogarUshindi** [comment]
... and now it appears to be working.

**Comment by SlvrEagle23** [comment]
@TogarUshindi If you continue to encounter this error, please feel free to create a new issue, but it looks like this issue resolved itself on your end.

**Comment by TogarUshindi** [comment]
It's still happening intermittently, but I can't pinpoint when it will or won't happen. I didn't do anything to resolve it. It just works, part of the time. :)
