### ISSUE TITLE
Music Page - Number items?

### ISSUE THREAD

**Issue by TogarUshindi** [AzuraCast/AzuraCast#2089]
Would be a really cool feature if the line items on the music page were numbered. I'm trying to solve a mysterious problem where apparently Azuracast thinks I uploaded 200+ tracks to my station sometime between last night and the current time, whereas yesterday I only had 90+ tracks. I've been uploading today, but I'm pretty sure I didn't upload that many. I'm trying to visually confirm how many I have in a row, but the only way is to manually count and scroll down the page.

**Comment by SlvrEagle23** [comment]
@TogarUshindi Feature requests should be submitted via our [FeatureUpvote page](https://features.azuracast.com/).

Just out of curiosity, how did you make it to the "New Issue" page without seeing that notice posted in the template? I'm noticing a lot of people disregarding the prefilled templates lately, and I'm wondering if it's possible anywhere in the system to get to creating a new issue without seeing them.

**Comment by TogarUshindi** [comment]
Hmm, it's too bad that link on Github can't just forward people to the appropriate page. Or can it?
