### ISSUE TITLE
Playlist Tracks Doubled

### ISSUE THREAD

**Issue by TogarUshindi** [AzuraCast/AzuraCast#2090]
I just encountered a situation where Azuracast said I had 324 tracks in my detault song rotation playlist, but in actuality it was 164. This seems to have occurred when I updated my playlist. The way I've been updating it is by selecting the folder all my songs are in, clicking playlists, selecting the "Default Song Playlist" playlist, and usually it neatly updates it, ignoring already-listed tracks. This time it didn't ignore them.

To resolve this I deleted the entire playlist and recreated it.

**Comment by SlvrEagle23** [comment]
@TogarUshindi It should only double-add to a single playlist if the playlist is sequential. Sequential playlists can have the same file in them twice, but other playlist types can't, as you can't specify the position of each file so it offers no benefit to list the same track twice.

**Comment by TogarUshindi** [comment]
No, it's definitely shuffled. Never changed those settings.
