### ISSUE TITLE
Ctrl+C does not terminate/disconnect temp SFTP session in CLI / Terminal

### ISSUE THREAD

**Issue by TogarUshindi** [AzuraCast/AzuraCast#2092]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu Server 18.04 LTS

**Describe the bug**
CTRL+C does not disconnect temp SFTP session as described in [instructions](https://www.azuracast.com/help/faq_docker.html#access-files-via-sftp).

**To Reproduce**
1. Follow instructions and start server.
2. Type Ctrl+C in terminal window.

**Expected behavior**
SFTP session should end.

**Additional context**
Cannot start new session on top of the old one. Ports are blocked. The terminal window has been closed, hoping that would stop the process but it has not. I'm attempting to find a way to isolate, identify and kill the process manually.

Problem has been mentioned [here](https://github.com/AzuraCast/AzuraCast/issues/857#issuecomment-436337173) and [here](https://github.com/AzuraCast/AzuraCast/issues/483#issuecomment-372518533).

**Comment by TogarUshindi** [comment]
I discovered `sudo docker stop --help` and was able to stop the SFTP server that way.

I ran the temp sftp command again and have it running with a more secure password, but the terminal window is still stuck in a mode that doesn't allow for commands.

Here's the output for the command (the expurgated version for privacy):

```
sudo docker run --rm     -v azuracast_station_data:/home/azuracast/stations     -p 2222:22 atmoz/sftp:alpine     azuracast:4theH0meStone:1000::stations
[/usr/local/bin/create-sftp-user] Parsing user data: "azuracast:password:1000::stations"
Creating mailbox file: No such file or directory
[/usr/local/bin/create-sftp-user] Directory already exists: /home/azuracast/stations
Generating public/private ed25519 key pair.
Your identification has been saved in /etc/ssh/ssh_host_ed25519_key.
Your public key has been saved in /etc/ssh/ssh_host_ed25519_key.pub.
The key fingerprint is:
SHA256:/etcetcetc root@etcetcetc
The key's randomart image is:
+--[ED25519 256]--+
|             ..  |
|     . .    .  E |
|    . o .    .   |
|     . * .  o    |
|      = S .. o   |
|     o + .*+  .  |
|    . ...O=...   |
|      o.+.==..+++|
|     ..+..=**=o+X|
+----[SHA256]-----+
Generating public/private rsa key pair.
Your identification has been saved in /etc/ssh/ssh_host_rsa_key.
Your public key has been saved in /etc/ssh/ssh_host_rsa_key.pub.
The key fingerprint is:
SHA256:etcetcetc root@etcetcetc
The key's randomart image is:
+---[RSA 4096]----+
|                 |
|       .         |
|      . o        |
| ..  . + o       |
|..=o .o S        |
| =.E+o.B         |
|o.ooX.* *        |
|oB+B.= = *       |
|++O.o.. o o      |
+----[SHA256]-----+
[/entrypoint] Executing sshd
Server listening on 0.0.0.0 port 22.
Server listening on :: port 22.
^C
exit
```

And that's about it.. can't escape out of it once it's running.

**Comment by SlvrEagle23** [comment]
@TogarUshindi The SFTP connection method is no longer officially supported (following the addition of our internal FTP service), and was never an internal built-in feature of AzuraCast, but rather a Docker container of its own that wasn't maintained by us.

**Comment by TogarUshindi** [comment]
Before you close the ticket, should we put a note on the help docs then that informs people of this?

**Comment by LordHelmchen666** [comment]
Try &! at the end of your command. For you e.g.
`sudo docker run --rm     -v azuracast_station_data:/home/azuracast/stations     -p 2222:22 atmoz/sftp:alpine     azuracast:4theH0meStone:1000::stations &!`

I can use then Strg+C :)
