### ISSUE TITLE
How to change the media files location to external storage

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2094]
**Using Docker installation method**
 Yes!
**Host Operating System**
Ubuntu 18.04, MacOS High Sierra, Windows 10). -->

**Describe the bug**
Is it possible to change at once ( when installing) the media location of each channel  and point it to nfs mount folder? 
As much as i can see there is only setting of the entire stations location in the yml file.

**Comment by SlvrEagle23** [comment]
@eranwo You can follow the instructions from our [help section](https://www.azuracast.com/help/faq_docker.html#storing-your-station-data-on-the-host-machine) for storing your station data on a host machine to move your entire station media directory to the external directory; if you want to move a single directory within a station's media folders you can follow [these other instructions](https://www.azuracast.com/help/faq_docker.html#mounting-a-directory-into-a-station). You'll notice that they have a common pattern, where you specify the path on the host computer, followed by the "virtual" path that AzuraCast sees inside Docker. You can do the same steps with any host directory and virtual directory.
