### ISSUE TITLE
Web DJ not working

### ISSUE THREAD

**Issue by mariustgv2004** [AzuraCast/AzuraCast#2095]
Hello! I have a problem regarding to Web DJ. The problem is that the interface doesn't see my microphone in the dropdown list below. I am using windows and I tryed it on several browsers. AzuraCast it installed on Ubuntu 18.4.
Can you help me?

**Comment by mariustgv2004** [comment]
Nevermind, I figured it out. Sorry for bothering.

**Comment by yuka0122** [comment]
Como lo hiciste 

> No importa, lo descubrí. Perdón por molestar.
