### ISSUE TITLE
Remote URL does not work on playlists

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#2096]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu

**Describe the bug**
Remote URL on playlists does not work at a scheduled time. Meta shows Station offline and no sound. The source should be played at the applied time range, for example, 11:40 to 11:50.

**Expected behavior**
Remote URL plays on scheduled time.

**Relevant Logs**

> 2019/10/24 11:40:05 >>> LOG START
> 2019/10/24 11:40:05 [main:3] Liquidsoap 1.3.7
> 2019/10/24 11:40:05 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.1 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.9 camomile=1.0.2 faad=0.4.0
> 2019/10/24 11:40:05 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
> 2019/10/24 11:40:05 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
> 2019/10/24 11:40:05 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
> 2019/10/24 11:40:05 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
> 2019/10/24 11:40:05 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
> 2019/10/24 11:40:05 [threads:3] Created thread "generic queue #1".
> 2019/10/24 11:40:05 [threads:3] Created thread "generic queue #2".
> 2019/10/24 11:40:05 [threads:3] Created thread "non-blocking queue #1".
> 2019/10/24 11:40:05 [threads:3] Created thread "non-blocking queue #2".
> 2019/10/24 11:40:05 [harbor:3] Adding mountpoint '/' on port 8415
> 2019/10/24 11:40:05 [threads:3] Created thread "https polling" (1 total).
> 2019/10/24 11:40:05 [playlist_alex_kerr:3] Loading playlist...
> 2019/10/24 11:40:05 [playlist_alex_kerr:3] No mime type specified, trying autodetection.
> 2019/10/24 11:40:05 [playlist_alex_kerr:3] Playlist treated as format application/x-mpegURL
> 2019/10/24 11:40:05 [playlist_alex_kerr:3] Successfully loaded a playlist of 0 tracks.
> 2019/10/24 11:40:05 [error_jingle:3] "/usr/local/share/icecast/web/error.mp3" is static, resolving once for all...
> 2019/10/24 11:40:05 [johnstone_sound_local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
> 2019/10/24 11:40:06 [johnstone_sound_local_1:3] Connection setup was successful.
> 2019/10/24 11:40:06 [threads:3] Created thread "wallclock_main" (2 total).
> 2019/10/24 11:40:06 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
> 2019/10/24 11:40:06 [johnstone_sound_live_switch:3] Switch to johnstone_sound_safe_fallback.
> 2019/10/24 11:40:06 [johnstone_sound_safe_fallback:3] Switch to johnstone_sound_radio_cue.
> 2019/10/24 11:40:06 [johnstone_sound_requests_fallback:3] Switch to johnstone_sound_schedule_switch.
> 2019/10/24 11:40:06 [johnstone_sound_schedule_switch:3] Switch to stereo_playlist_radio_antalya.
> 2019/10/24 11:40:06 [mksafe:3] Switch to safe_blank.
> 2019/10/24 11:40:06 [dummy:3] Source failed (no more tracks) stopping output...

**Comment by ivellios1988** [comment]
Is it an M3U or PLS playlist? Try both formats if possible. From what I've learned, M3Us tend to be troublesome.
