### ISSUE TITLE
error ca-certs.json is not a valid JSON file. Fetch.php : 161

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#2097]
5 minute sync is giving error ca-certs.json is not a valid JSON file. Fetch.php: 161, how can I solve? It has 25 days that does not run.

**Comment by paragonie-scott** [comment]
What's the `ls -lah` output of the directory that contains `ca-certs.json`?

**Comment by Marcioghiraldelli** [comment]
I searched for the file name and found several folders with the file name.
I don't know which one to show and I don't know which one to access.
See attached image please.

Em sex, 25 de out de 2019 às 01:21, Scott <notifications@github.com>
escreveu:

**Comment by Marcioghiraldelli** [comment]
Now another error appears.
No valid bundles were found in the data directory.
Fetch.php: 100


After I recovered the .json file backup

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli This should be resolved as of the most recent updates.
