### ISSUE TITLE
Files not loading after upload

### ISSUE THREAD

**Issue by MBoberski** [AzuraCast/AzuraCast#2098]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 16.04

**Describe the bug**
After adding files via ftp they are shown in file list but not in playlist so I have no music.

**To Reproduce**
1. isntall AC
2. create default station
3. log into ftp and upload somethink
4. try to ad it ino playlist
5. there is only default AC file

**Expected behavior**
Add files to designed playlist

**Screenshots**

![image](https://user-images.githubusercontent.com/2800036/67589387-9f1a6280-f758-11e9-8396-abcfad0e66ac.png)
![image](https://user-images.githubusercontent.com/2800036/67589400-aa6d8e00-f758-11e9-9c41-12e0a6273a57.png)
![image](https://user-images.githubusercontent.com/2800036/67589426-b5c0b980-f758-11e9-9b4d-a2eed96e1204.png)

**Device(s):**
 - Device: Desktop
 - OS: Win10
 - Browser: Chrome
 - Version: 77.0.3865.120

**Comment by SlvrEagle23** [comment]
@MBoberski When you select the files and add them to the playlist, do you see a successful (green) message pop up indicating that they were added, or do you see an error?

If you see an error, we can help diagnose the issue if you visit your browser's inspector console (usually F12 on most browsers), select the "Network" tab, and then attempt to set the playlists again; if you see a request light up in red (or have a 500 error), select that request and paste the error message it shows you here.

**Comment by MBoberski** [comment]
@SlvrEagle23  when I try to add any file I get: 

500
The EntityManager is closed.
ORMException.php : 144

in Chrome console
