### ISSUE TITLE
Unable to activate 2FA with Error 500

### ISSUE THREAD

**Issue by sherifkozman** [AzuraCast/AzuraCast#2099]
Activating 2FA is not working anymore though it was working before.

Upon activatation of 2FA and scanning through the QR code and using the first code to enable the feature, an error 500 with "Field name "secret" not found. AbstractForm.php : 71"

Result : unable to activate 2FA

**Comment by SlvrEagle23** [comment]
@sherifkozman Thank you for the report! This has been ongoing for a while, actually, we just haven't had many folks using 2FA so nobody reported it yet.

This should be fixed as of the latest refactor work done today.
