### ISSUE TITLE
Error Installation anyone can help?

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#210]
Ive try to install via docker installation but there is an error.. bellow. 

=============================

 sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0   1249      0 --:--:-- --:--:-- --:--:--  1248
100 8650k  100 8650k    0     0  3582k      0  0:00:02  0:00:02 --:--:-- 7061k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11955  100 11955    0     0  44819      0 --:--:-- --:--:-- --:--:-- 44943
Pulling stations (azuracast/azuracast_stations:latest)...
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
root@cast:~/AzuraCast#
=================================================

and i tried via traditional installation this is an error also..

TASK [supervisord : Kill legacy radio processes (if upgrading from older version)] *************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["killall", "-q", "-9", "icecast2", "sc_serv", "liquidsoap"], "delta": "0:00:00.003741", "end": "2017-08-14 13:41:05.842243", "failed": true, "rc": 1, "start": "2017-08-14 13:41:05.838502", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
...ignoring

TASK [supervisord : Trigger manual restart of supervisord (if not already running)] ************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/bin/systemctl", "failed": true, "msg": "Failed to connect to bus: No such file or directory", "rc": 1, "stderr": "Failed to connect to bus: No such file or directory\n", "stderr_lines": ["Failed to connect to bus: No such file or directory"], "stdout": "", "stdout_lines": []}
...ignoring

TASK [influxdb : Add InfluxDB repo file] *******************************************************************************************************************************
changed: [localhost]

TASK [influxdb : Add InfluxDB repo key] ********************************************************************************************************************************
changed: [localhost]

TASK [influxdb : Update apt cache] *************************************************************************************************************************************
changed: [localhost]

TASK [influxdb : Install python-influxdb] ******************************************************************************************************************************
changed: [localhost] => (item=influxdb)

TASK [influxdb : Install InfluxDB] *************************************************************************************************************************************
changed: [localhost]

TASK [influxdb : Fix permissions on InfluxDB data folder] **************************************************************************************************************
ok: [localhost]

TASK [influxdb : Lock down InfluxDB to localhost requests] *************************************************************************************************************
changed: [localhost]

TASK [influxdb : Start the InfluxDB service] ***************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/bin/systemctl", "failed": true, "msg": "Failed to connect to bus: No such file or directory", "rc": 1, "stderr": "Failed to connect to bus: No such file or directory\n", "stderr_lines": ["Failed to connect to bus: No such file or directory"], "stdout": "", "stdout_lines": []}

RUNNING HANDLER [azuracast-user : send user notification] **************************************************************************************************************
        to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=37   changed=31   unreachable=0    failed=1

===============================================

anyone can help?

**Comment by mkody** [comment]
It looks like you have an overall problem with your System install (?).

The first error looks related to Docker and not AzuraCast. Did you add yourself properly to the docker group, [like this comment says?](http://bit.ly/2vVWrDb) (You might also try to check out for the other solutions there if that doesn't work.)

For the second part, I don't really know as it's related to your system install again.  
What OS are you using? Is that a fresh install too?  Could you try to run this command before the `install.sh`?
```bash
export XDG_RUNTIME_DIR=/run/user/`id -u`
```

**Comment by reans** [comment]
im using this ubuntu-16.04-x86_64 i installed from root user.

**Comment by reans** [comment]
ive try ubunto 14 with traditional installation method i got this error too.

WARNING: The following packages cannot be authenticated!
  python2.7 libpython2.7 libpython2.7-stdlib python2.7-minimal
  libpython2.7-minimal
E: There are problems and -y was used without --force-yes
Installing AzuraCast (Environment: production)
./install.sh: line 37: ansible-playbook: command not found

**Comment by mkody** [comment]
You could have googled about that warning. https://askubuntu.com/a/75575

```bash
sudo apt-key update
sudo apt-get update
```

What hosting provider do you use for your server? Or are you running this at your home?

**Comment by reans** [comment]
I SWITCH IT BACK TO 16.04 and run this one with vps from vmbox but i always stack in this part.. i always re-try but upto nginx only.

TASK [nginx : Install nginx] *******************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"cache_update_time": 1502953192, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'nginx'' failed: E: Sub-process /usr/bin/dpkg returned an error code (1)\n", "rc": 100, "stderr": "E: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stderr_lines": ["E: Sub-process /usr/bin/dpkg returned an error code (1)"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nnginx is already the newest version (1.10.3-0ubuntu0.16.04.2).\n0 upgraded, 0 newly installed, 0 to remove and 129 not upgraded.\n2 not fully installed or removed.\nAfter this operation, 0 B of additional disk space will be used.\nSetting up nginx-core (1.10.3-0ubuntu0.16.04.2) ...\r\nJob for nginx.service failed because the control process exited with error code. See \"systemctl status nginx.service\" and \"journalctl -xe\" for details.\r\ninvoke-rc.d: initscript nginx, action \"start\" failed.\r\ndpkg: error processing package nginx-core (--configure):\r\n subprocess installed post-installation script returned error exit status 1\r\ndpkg: dependency problems prevent configuration of nginx:\r\n nginx depends on nginx-core (>= 1.10.3-0ubuntu0.16.04.2) | nginx-full (>= 1.10.3-0ubuntu0.16.04.2) | nginx-light (>= 1.10.3-0ubuntu0.16.04.2) | nginx-extras (>= 1.10.3-0ubuntu0.16.04.2); however:\r\n  Package nginx-core is not configured yet.\r\n  Package nginx-full is not installed.\r\n  Package nginx-light is not installed.\r\n  Package nginx-extras is not installed.\r\n nginx depends on nginx-core (<< 1.10.3-0ubuntu0.16.04.2.1~) | nginx-full (<< 1.10.3-0ubuntu0.16.04.2.1~) | nginx-light (<< 1.10.3-0ubuntu0.16.04.2.1~) | nginx-extras (<< 1.10.3-0ubuntu0.16.04.2.1~); however:\r\n  Package nginx-core is not configured yet.\r\n  Package nginx-full is not installed.\r\n  Package nginx-light is not installed.\r\n  Package nginx-extras is not installed.\r\n\r\ndpkg: error processing package nginx (--configure):\r\n dependency problems - leaving unconfigured\r\nErrors were encountered while processing:\r\n nginx-core\r\n nginx\r\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "nginx is already the newest version (1.10.3-0ubuntu0.16.04.2).", "0 upgraded, 0 newly installed, 0 to remove and 129 not upgraded.", "2 not fully installed or removed.", "After this operation, 0 B of additional disk space will be used.", "Setting up nginx-core (1.10.3-0ubuntu0.16.04.2) ...", "Job for nginx.service failed because the control process exited with error code. See \"systemctl status nginx.service\" and \"journalctl -xe\" for details.", "invoke-rc.d: initscript nginx, action \"start\" failed.", "dpkg: error processing package nginx-core (--configure):", " subprocess installed post-installation script returned error exit status 1", "dpkg: dependency problems prevent configuration of nginx:", " nginx depends on nginx-core (>= 1.10.3-0ubuntu0.16.04.2) | nginx-full (>= 1.10.3-0ubuntu0.16.04.2) | nginx-light (>= 1.10.3-0ubuntu0.16.04.2) | nginx-extras (>= 1.10.3-0ubuntu0.16.04.2); however:", "  Package nginx-core is not configured yet.", "  Package nginx-full is not installed.", "  Package nginx-light is not installed.", "  Package nginx-extras is not installed.", " nginx depends on nginx-core (<< 1.10.3-0ubuntu0.16.04.2.1~) | nginx-full (<< 1.10.3-0ubuntu0.16.04.2.1~) | nginx-light (<< 1.10.3-0ubuntu0.16.04.2.1~) | nginx-extras (<< 1.10.3-0ubuntu0.16.04.2.1~); however:", "  Package nginx-core is not configured yet.", "  Package nginx-full is not installed.", "  Package nginx-light is not installed.", "  Package nginx-extras is not installed.", "", "dpkg: error processing package nginx (--configure):", " dependency problems - leaving unconfigured", "Errors were encountered while processing:", " nginx-core", " nginx"]}

RUNNING HANDLER [azuracast-user : send user notification] **************************************************************************************************************
        to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=37   changed=7    unreachable=0    failed=1

**Comment by mkody** [comment]
`nginx depends on nginx-core (>= 1.10.3-0ubuntu0.16.04.2) [...]; however: Package nginx-core is not configured yet.`

Well something went wrong with apt/nginx there. Also I see that
`0 upgraded, 0 newly installed, 0 to remove and 129 not upgraded`

Could you run `sudo apt-get update ; sudo apt-get upgrade -y` to make sure everything is up-to-date?

**Comment by reans** [comment]
root@cast:/var/azuracast/www# journalctl -xet nginx
-- Logs begin at Sun 2017-08-20 10:47:19 EDT, end at Mon 2017-08-21 08:48:48 EDT. --
Aug 21 08:48:46 cast nginx[30300]: nginx: [emerg] listen() to 0.0.0.0:80, backlog 511 failed (98: Address already in use)
Aug 21 08:48:46 cast nginx[30300]: nginx: [emerg] listen() to [::]:80, backlog 511 failed (98: Address already in use)
Aug 21 08:48:46 cast nginx[30300]: nginx: [emerg] listen() to 0.0.0.0:80, backlog 511 failed (98: Address already in use)
Aug 21 08:48:46 cast nginx[30300]: nginx: [emerg] listen() to [::]:80, backlog 511 failed (98: Address already in use)
Aug 21 08:48:47 cast nginx[30300]: nginx: [emerg] listen() to 0.0.0.0:80, backlog 511 failed (98: Address already in use)
Aug 21 08:48:47 cast nginx[30300]: nginx: [emerg] listen() to [::]:80, backlog 511 failed (98: Address already in use)
Aug 21 08:48:47 cast nginx[30300]: nginx: [emerg] listen() to 0.0.0.0:80, backlog 511 failed (98: Address already in use)
Aug 21 08:48:47 cast nginx[30300]: nginx: [emerg] listen() to [::]:80, backlog 511 failed (98: Address already in use)
Aug 21 08:48:48 cast nginx[30300]: nginx: [emerg] listen() to 0.0.0.0:80, backlog 511 failed (98: Address already in use)
Aug 21 08:48:48 cast nginx[30300]: nginx: [emerg] listen() to [::]:80, backlog 511 failed (98: Address already in use)
Aug 21 08:48:48 cast nginx[30300]: nginx: [emerg] still could not bind()

i run everything update... and upgrade...

**Comment by reans** [comment]
mkody thanks for the help i got it. i need to stop the apache2 process run by default to successfully install the ngix. :-) thanks for help.
