### ISSUE TITLE
Queue song not working

### ISSUE THREAD

**Issue by mythevalentinus** [AzuraCast/AzuraCast#2102]
Hello the Team !

**Using Docker installation method**
AzuraCast • v0.9.7.1, #7473a33 • Docker • PHP 7.2

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
When i go to my song files, select song and click on "Queue", sometime song go to the queue but is not play, is skiped. Sometime the song don't go to the queue.

**Relevant Logs**
No logs, no error

Thanks in advance.

**Comment by SlvrEagle23** [comment]
@MyTheValentinus This is likely a byproduct of the way the "queue song" functionality currently works (which is using the Song Requests queue). We're aware of this and working on a better long-term solution, but for now we wanted to ship the feature so people could use it in the meantime.
