### ISSUE TITLE
Could not connect to supervisord.

### ISSUE THREAD

**Issue by callumok2004** [AzuraCast/AzuraCast#2103]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
Whenever I try to visit my radio server (https://server.infiniterad.io), it redirects me to /dashboard and gives me this error:

**To Reproduce**
1. Install and setup azuracast
2. Reboot server
3. Run `docker ps`
4. Go to radio server URL, error appeared

**Expected behavior**
I should be able to access the dashboard like normal

**Screenshots**
![Screenshot1](https://bot.wearebounce.net/f/PUMcZexN.png)

**Device(s):**
 - Device: Laptop
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest

**Comment by callumok2004** [comment]
I have tried messing around to try get it working again, and I noticed it happens after a reboot, when I start azuracast docker by running `docker ps`

**Comment by SlvrEagle23** [comment]
@callumok2004 The `docker ps` command just checks on the running status of the containers; it shouldn't be affecting them by restarting or otherwise messing with them.

It seems like your `stations` container isn't starting up normally. Can you try running:

```bash
cd /var/azuracast
docker-compose up -d stations
```

...and seeing if it's already running?

**Comment by callumok2004** [comment]
I tried reinstalling azuracast and got this error when it tried to start stations
```
ERROR: for stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (cabe95d3ca76e48e677df8133a1de75c15b20e3bc19464936c584a7c346c7bbf): Error starting userland proxy: listen tcp 0.0.0.0:8000: bind: address already in use
ERROR: Encountered errors while bringing up the project.

```
I realised, that every time my server reboots, something loads onto that port, and I do not know what it is, so I ran `fuser -k 8000/tcp` and ran the install command again, and it worked this time!
It would be nice to know why that port gets taken upon every system restart.
