### ISSUE TITLE
UI problem on media files section

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#2104]
**Using Docker installation method**
yes

**Host Operating System**
ubuntu

**Describe the bug**
Search field and UI not good as older versions on Mobile. The mobile users can't search for songs. 
**To Reproduce**

Go to media files section on smartphone.

**Expected behavior**
Clearly search for songs and display buttons nicely.

**Comment by SlvrEagle23** [comment]
@radiolize This issue has been fixed as of the latest update.
