### ISSUE TITLE
Media Directory?

### ISSUE THREAD

**Issue by ArranLH** [AzuraCast/AzuraCast#2107]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04
**Describe the bug**
I can't CD into a stations media directory.

**To Reproduce**
cd /var/azuracast/stations/

**Expected behavior**
cd: /var/azuracast/stations/: No such file or directory

**Device(s):**
N/A

**Additional context**

**Comment by biguenique** [comment]
Your media directory is not on your host server, but inside a Docker volume. To map a directory on your host server to your Docker installation, follow [these instructions](https://www.azuracast.com/help/faq_docker.html#mounting-a-directory-into-a-station).

Alternatively, you can open a shell session inside your Docker environment using the following command:

`docker exec -it azuracast_stations bash
`

**Comment by rmacari** [comment]
@ArranLH You can find the files here: 
/var/lib/docker/volumes/azuracast_station_data/_data/
