### ISSUE TITLE
WEB DJ did not work

### ISSUE THREAD

**Issue by MajNiczek** [AzuraCast/AzuraCast#2108]
I'm doing everything right, but my station is still offline. https://www.youtube.com/watch?v=tHBFO-l7U9o

**Comment by radiolize** [comment]
Hello. Are you using one of our services or send link for reference? Our WebDJ works fine.

**Comment by MajNiczek** [comment]
> Cześć. Czy korzystasz z jednej z naszych usług lub wysłałeś link w celach informacyjnych? Nasz WebDJ działa dobrze.

I didn't find another video on youtube, so I used this guide.

**Comment by ogrenci01** [comment]
Hi @MajNiczek ;

Do you use non-standard ports on your stations? If you are using it, you should make sure that you have configured it correctly. You should give detailed information about your installation.

Web DJ need a valid SSL certificate. You should enable `Always Use HTTPS` and `Use Web Proxy for Radio` on admin page `System Settings` section.

**Comment by ivellios1988** [comment]
Check privileges as well. Web DJ needs a permission to use your microphone.
