### ISSUE TITLE
Wont start after running updater

### ISSUE THREAD

**Issue by shadow257** [AzuraCast/AzuraCast#211]
root@AzuraCast:/var/azuracast/www# ./update.sh --full
Checking for Ansible: install ok installed
Updating AzuraCast (Environment: production)
HEAD is now at 84fe741 Fix bootstrap settings placement.
Already up-to-date.
[DEPRECATION WARNING]: Specifying include variables at the top-level of the task is deprecated. Please see:
http://docs.ansible.com/ansible/playbooks_roles.html#task-
include-files-and-encouraging-reuse

 for currently supported syntax regarding included files and variables.
This feature will be removed in a future release.
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [all] *************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************
ok: [localhost]

TASK [init : debug] ****************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Running Ansible on localhost with OS Ubuntu xenial 16.04 x86_64 (production)"
}

TASK [init : debug] ****************************************************************************************************************************************************
skipping: [localhost]

TASK [init : Add multiverse repository] ********************************************************************************************************************************
ok: [localhost] => (item=deb http://archive.ubuntu.com/ubuntu xenial multiverse)
ok: [localhost] => (item=deb-src http://archive.ubuntu.com/ubuntu/  xenial multiverse)
ok: [localhost] => (item=deb http://archive.ubuntu.com/ubuntu xenial-updates multiverse)
ok: [localhost] => (item=deb-src http://archive.ubuntu.com/ubuntu/  xenial-updates multiverse)

TASK [init : Update apt] ***********************************************************************************************************************************************
changed: [localhost]

TASK [init : Install system packages] **********************************************************************************************************************************
ok: [localhost] => (item=[u'apt-transport-https', u'curl', u'wget', u'tar', u'build-essential', u'python-software-properties', u'pwgen', u'whois', u'python-pip', u'lnav'])

TASK [init : Update pip components] ************************************************************************************************************************************
ok: [localhost] => (item=pip)

TASK [azuracast-config : Write environment configuration file] *********************************************************************************************************
ok: [localhost]

TASK [azuracast-config : Set up environment file] **********************************************************************************************************************
ok: [localhost]

TASK [azuracast-config : Set Permissions on Base App Folder] ***********************************************************************************************************
ok: [localhost] => (item=/var/azuracast)

TASK [azuracast-config : Create System Folders] ************************************************************************************************************************
ok: [localhost] => (item=/var/azuracast/www_tmp)
ok: [localhost] => (item=/var/azuracast/www_tmp/proxies)
ok: [localhost] => (item=/var/azuracast/stations)
ok: [localhost] => (item=/var/azuracast/servers)
ok: [localhost] => (item=/var/azuracast/servers/shoutcast2)
ok: [localhost] => (item=/var/azuracast/servers/icecast2)

TASK [azuracast-config : Make App Directory Writeable] *****************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Install IceCast-KH Dependencies] ***************************************************************************************************************
ok: [localhost] => (item=[u'libxml2', u'libxslt1-dev', u'libvorbis-dev', u'libssl-dev', u'libcurl4-openssl-dev', u'pkg-config'])

TASK [azuracast-radio : Download IceCast-KH Source] ********************************************************************************************************************
ok: [localhost]

TASK [azuracast-radio : Extract IceCast-KH Source] *********************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Build IceCast-KH] ******************************************************************************************************************************
ok: [localhost]

TASK [azuracast-radio : Link IceCast Resource Files] *******************************************************************************************************************
ok: [localhost] => (item={u'dest': u'/usr/local/share/icecast/web/error.mp3', u'src': u'/var/azuracast/www/resources/error.mp3'})
ok: [localhost] => (item={u'dest': u'/usr/local/share/icecast/web/status-json.xsl', u'src': u'/var/azuracast/www/resources/status-json.xsl'})
ok: [localhost] => (item={u'dest': u'/usr/local/share/icecast/web/xml2json.xslt', u'src': u'/var/azuracast/www/resources/xml2json.xslt'})

TASK [azuracast-radio : Add OPAM Repository] ***************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Update apt again] ******************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Install OPAM] **********************************************************************************************************************************
ok: [localhost]

TASK [azuracast-radio : Install LiquidSoap Dependencies] ***************************************************************************************************************
ok: [localhost] => (item=[u'libpcre3-dev', u'libfdk-aac-dev', u'libmad0-dev', u'libmp3lame-dev', u'libtag1-dev', u'libfaad-dev', u'libflac-dev', u'pkg-config', u'm4', u'aspcud'])

TASK [azuracast-radio : Build LiquidSoap] ******************************************************************************************************************************
changed: [localhost]

TASK [azuracast-radio : Download ShoutCast 2 (x86)] ********************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Download ShoutCast 2 (x64)] ********************************************************************************************************************
ok: [localhost]

TASK [azuracast-radio : Extract ShoutCast 2 Binary] ********************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Install IceCast2] ******************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Link Fallback Error MP3] ***********************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Remove problematic LiquidSoap plugins] *********************************************************************************************************
skipping: [localhost] => (item=[])

TASK [azuracast-radio : Install LiquidSoap] ****************************************************************************************************************************
skipping: [localhost] => (item=[])

TASK [supervisord : Install supervisord from repo] *********************************************************************************************************************
ok: [localhost]

TASK [supervisord : Change supervisord configuration] ******************************************************************************************************************
ok: [localhost]

TASK [supervisord : Remove old core supervisord configuration] *********************************************************************************************************
ok: [localhost]

TASK [supervisord : Kill legacy radio processes (if upgrading from older version)] *************************************************************************************
skipping: [localhost]

TASK [supervisord : Trigger manual restart of supervisord (if not already running)] ************************************************************************************
skipping: [localhost]

TASK [nginx : Install nginx] *******************************************************************************************************************************************
ok: [localhost]

TASK [nginx : Create nginx ssl directory] ******************************************************************************************************************************
ok: [localhost] => (item=/etc/nginx/ssl)

TASK [nginx : Create self-signed SSL cert] *****************************************************************************************************************************
ok: [localhost]

TASK [nginx : Remove default nginx site symlink] ***********************************************************************************************************************
ok: [localhost]

TASK [nginx : Add app-specific nginx site] *****************************************************************************************************************************
ok: [localhost]

TASK [nginx : Link app-specific nginx site] ****************************************************************************************************************************
ok: [localhost]

TASK [nginx : Turn sendfile off on nginx for local development] ********************************************************************************************************
skipping: [localhost]

TASK [redis : Install Redis] *******************************************************************************************************************************************
ok: [localhost] => (item=[u'redis-server'])

TASK [redis : Set Redis service name] **********************************************************************************************************************************
ok: [localhost]

TASK [redis : Restart Redis service] ***********************************************************************************************************************************
changed: [localhost]

TASK [php : Add PHP PPA repository] ************************************************************************************************************************************
ok: [localhost]

TASK [php : Remove Old PHP Libraries] **********************************************************************************************************************************
ok: [localhost] => (item=[u'php5-common', u'php5-fpm', u'php5-cli', u'php5-phalcon', u'php7.0-fpm', u'php7.0-cli', u'php7.0-gd', u'php7.0-curl', u'php7.0-xml', u'php7.0-zip', u'php7.0-mysqlnd', u'php7.0-mbstring', u'php7.0-intl', u'php7.0-phalcon'])

TASK [php : Install PHP 7.1] *******************************************************************************************************************************************
ok: [localhost] => (item=[u'php7.1-fpm', u'php7.1-cli', u'php7.1-gd', u'php7.1-curl', u'php7.1-xml', u'php7.1-zip', u'php7.1-mysqlnd', u'php7.1-mbstring', u'php7.1-intl', u'php7.1-redis'])

TASK [php : Install xdebug for testing] ********************************************************************************************************************************
skipping: [localhost] => (item=[])

TASK [php : List locales] **********************************************************************************************************************************************
changed: [localhost]

TASK [php : Create Locales] ********************************************************************************************************************************************
ok: [localhost] => (item=de_DE.UTF-8)
ok: [localhost] => (item=es_ES.UTF-8)
ok: [localhost] => (item=fr_FR.UTF-8)
ok: [localhost] => (item=hu_HU.UTF-8)
ok: [localhost] => (item=pl_PL.UTF-8)
ok: [localhost] => (item=ru_RU.UTF-8)

TASK [php : Configure PHP FPM Pool] ************************************************************************************************************************************
ok: [localhost]

TASK [php : Configure php-fpm php.ini] *********************************************************************************************************************************
ok: [localhost] => (item={u'option': u'post_max_size', u'value': u'50M'})
ok: [localhost] => (item={u'option': u'short_open_tag', u'value': u'On'})
ok: [localhost] => (item={u'option': u'upload_max_filesize', u'value': u'25M'})

TASK [php : Configure php-cli php.ini] *********************************************************************************************************************************
ok: [localhost] => (item={u'option': u'short_open_tag', u'value': u'On'})

TASK [influxdb : Add InfluxDB repo file] *******************************************************************************************************************************
ok: [localhost]

TASK [influxdb : Add InfluxDB repo key] ********************************************************************************************************************************
ok: [localhost]

TASK [influxdb : Update apt cache] *************************************************************************************************************************************
skipping: [localhost]

TASK [influxdb : Install python-influxdb] ******************************************************************************************************************************
ok: [localhost] => (item=influxdb)

TASK [influxdb : Install InfluxDB] *************************************************************************************************************************************
ok: [localhost]

TASK [influxdb : Fix permissions on InfluxDB data folder] **************************************************************************************************************
ok: [localhost]

TASK [influxdb : Lock down InfluxDB to localhost requests] *************************************************************************************************************
ok: [localhost]

TASK [influxdb : Start the InfluxDB service] ***************************************************************************************************************************
changed: [localhost]

TASK [influxdb : Pause to allow InfluxDB to spin up] *******************************************************************************************************************
ok: [localhost]

TASK [influxdb : Create 'stations' database] ***************************************************************************************************************************
ok: [localhost] => (item=stations)

TASK [influxdb : Create 'stations' retention policies] *****************************************************************************************************************
ok: [localhost] => (item={u'duration': u'5d', u'default': True, u'name': u'15s'})
ok: [localhost] => (item={u'duration': u'2w', u'default': False, u'name': u'1h'})
changed: [localhost] => (item={u'duration': u'INF', u'default': False, u'name': u'1d'})

TASK [influxdb : Manage continuous queries on 'stations'] **************************************************************************************************************
 [WARNING]: Module did not set no_log for login_password

changed: [localhost]

TASK [ufw : Install UFW Firewall] **************************************************************************************************************************************
ok: [localhost] => (item=[u'ufw'])

TASK [ufw : UFW - Disable all other incoming by default] ***************************************************************************************************************
ok: [localhost]

TASK [ufw : UFW - Allow all other outgoing by default] *****************************************************************************************************************
ok: [localhost]

TASK [ufw : UFW - Enable AzuraCast TCP Ports] **************************************************************************************************************************
ok: [localhost] => (item=80)
ok: [localhost] => (item=443)
ok: [localhost] => (item=8000:8999)

TASK [ufw : UFW - Enable SSH] ******************************************************************************************************************************************
ok: [localhost]

TASK [ufw : UFW - Turn on Firewall] ************************************************************************************************************************************
ok: [localhost]

TASK [services : Set Redis service name] *******************************************************************************************************************************
ok: [localhost]

TASK [services : Enable and restart all core services] *****************************************************************************************************************
changed: [localhost] => (item=influxdb)
changed: [localhost] => (item=mysql)
changed: [localhost] => (item=php7.1-fpm)
changed: [localhost] => (item=nginx)
changed: [localhost] => (item=redis)

TASK [azuracast-cron : Generate Cron Template] *************************************************************************************************************************
changed: [localhost]

TASK [azuracast-cron : Install Cron file] ******************************************************************************************************************************
changed: [localhost]

TASK [azuracast-cron : Clean up temp Cron file] ************************************************************************************************************************
changed: [localhost]

TASK [azuracast-update : Make update script executable again] **********************************************************************************************************
changed: [localhost]

TASK [azuracast-update : Install Composer Dependencies (Development)] **************************************************************************************************
skipping: [localhost]

TASK [azuracast-update : Install Composer Dependencies (Production)] ***************************************************************************************************
changed: [localhost]

TASK [azuracast-update : Update configuration from legacy] *************************************************************************************************************
changed: [localhost]

TASK [azuracast-update : Clear AzuraCast Cache] ************************************************************************************************************************
changed: [localhost]

TASK [azuracast-update : Update Database] ******************************************************************************************************************************
changed: [localhost]

TASK [azuracast-update : Restart Radio Stations] ***********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php azuracast:radio:restart", "delta": "0:00:01.759599", "end": "2017-08-16 20:23:46.707000", "failed": true, "rc": 255, "start": "2017-08-16 20:23:44.947401", "stderr": "", "stderr_lines": [], "stdout": "Restarting all radio stations...\n---------------------------------------------\nRestarting station #1: PPR", "stdout_lines": ["Restarting all radio stations...", "---------------------------------------------", "Restarting station #1: PPR"]}

RUNNING HANDLER [azuracast-cron : restart cron] ************************************************************************************************************************
        to retry, use: --limit @/var/azuracast/www/util/ansible/update.retry

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=65   changed=16   unreachable=0    failed=1

**Comment by shadow257** [comment]
Have also tried
`service supervisor restart`
and 
`supervisorctl restart core:mysql`
core:mysql: ERROR (no such process)

Any ideas?
- Ubuntu 16.04

**Comment by SlvrEagle23** [comment]
@shadow257 What is the response if you try to execute, in the command line:

```bash
php /var/azuracast/www/util/cli.php azuracast:radio:restart
```

**Comment by shadow257** [comment]
That fixed it, and was able to run update.sh
