### ISSUE TITLE
My commercial spots are not airing

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#2110]
My commercial spots are not airing. Am I setting up correctly?
Image of attached configuration.
I am setting up a playlist to run the commercial at minute 20 and another at minute 55. But it won't air.

I've used these settings before, and it worked. But now it does not work.
Can you help me?! Thank you for your attention.

![image](https://user-images.githubusercontent.com/31827151/67681315-da40af80-f96b-11e9-94c1-02f7ad4f86d1.png)

**Comment by mrnat7471** [comment]
I have same problem sometimes.

**Comment by MrSteelMiner** [comment]
The advanced options are often a problem. Try turning off "playing as one track".

**Comment by Rafaelrds2017** [comment]
I will disable.
but my commercial spots have about 5 files.

if I disable playback as a track, it won't play all files right?

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Marvin <notifications@github.com>
Enviado: Wednesday, October 30, 2019 9:38:33 AM
Para: AzuraCast/AzuraCast <AzuraCast@noreply.github.com>
Cc: Rafael Rodrigues <rafael_15silva@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [AzuraCast/AzuraCast] My commercial spots are not airing (#2110)


The advanced options are often a problem. Try turning off "playing as one track".

**Comment by biguenique** [comment]
Did you restart your station after setting your spots?
What do you have in *Administration* > *System Logs* > *[station name]* > *Liquidsoap Configuration* ?

**Comment by Rafaelrds2017** [comment]
Yes. After all configuration I restart.

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Bigue Nique <notifications@github.com>
Enviado: Wednesday, October 30, 2019 5:50:59 PM
Para: AzuraCast/AzuraCast <AzuraCast@noreply.github.com>
Cc: Rafael Rodrigues <rafael_15silva@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [AzuraCast/AzuraCast] My commercial spots are not airing (#2110)


Did you restart your station after setting your spots?
What do you have in Administration > System Logs > [station name] > Liquidsoap Configuration ?

**Comment by Rafaelrds2017** [comment]
n:2] We must catchup 1.38 seconds!
2019/10/30 18:14:07 [clock.wallclock_main:2] We must catchup 1.14 seconds!
2019/10/30 18:14:08 [clock.wallclock_main:2] We must catchup 1.08 seconds!

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Locutor Rafael <rafael_15silva@hotmail.com>
Enviado: Wednesday, October 30, 2019 6:10:53 PM
Para: AzuraCast/AzuraCast <reply@reply.github.com>; AzuraCast/AzuraCast <AzuraCast@noreply.github.com>
Cc: Author <author@noreply.github.com>
Assunto: Re: [AzuraCast/AzuraCast] My commercial spots are not airing (#2110)

Yes. After all configuration I restart.

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Bigue Nique <notifications@github.com>
Enviado: Wednesday, October 30, 2019 5:50:59 PM
Para: AzuraCast/AzuraCast <AzuraCast@noreply.github.com>
Cc: Rafael Rodrigues <rafael_15silva@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [AzuraCast/AzuraCast] My commercial spots are not airing (#2110)


Did you restart your station after setting your spots?
What do you have in Administration > System Logs > [station name] > Liquidsoap Configuration ?

**Comment by biguenique** [comment]
What you just pasted is from the Liquidsoap *Log*, but do you see your spots in the Liquidsoap *Configuration*?

**Comment by Rafaelrds2017** [comment]
I didn't understand what you meant.

I don't know much about programming.

In this new update, commercials are not playing.

when I turn off playback as a track. It works again. But it does not play all the spot files in the sequence. play only the first file, the others not.

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Bigue Nique <notifications@github.com>
Enviado: Wednesday, October 30, 2019 6:21:18 PM
Para: AzuraCast/AzuraCast <AzuraCast@noreply.github.com>
Cc: Rafael Rodrigues <rafael_15silva@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [AzuraCast/AzuraCast] My commercial spots are not airing (#2110)


What you just pasted is from the Liquidsoap Log, but do you see your spots in the Liquidsoap Configuration?
