### ISSUE TITLE
SHOUTcast second mountpoint returns error 401

### ISSUE THREAD

**Issue by TheChicken14** [AzuraCast/AzuraCast#2112]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.10

**Describe the bug**
When I create a second mount point on a SHOUTcast profile, the SHOUTcast server returns error 401
![image](https://user-images.githubusercontent.com/31771656/67776964-61238400-fa61-11e9-9324-51b7799468c9.png)

**To Reproduce**
1. Make a new station (you don't want to ruin your default station)
2. Make sure it runs the SHOUTcast server
3. Click on "mount points"
4. Click on "add mount point"
5. Set it up correctly (the url, name and quality, see picture) 
6. Apply the changes
7. Click on the mount point you just set up on the main page the profile
![image](https://user-images.githubusercontent.com/31771656/67777260-c4adb180-fa61-11e9-85b8-fa341da2fc2d.png)

**Expected behavior**
I expect it to just play the station on that mount point

**Screenshots**

**Extra information**
I have read in another issue, that from SHOUTcast 2.6 and higher, you cannot make a second mountpoint because SHOUTcast wants you to pay for that. But I have tried using an older version, but that didn't work eiter

**Comment by NationsGlory** [comment]
Yes, i have the same issue, the autodj does not connect to secondary mount points with shoutcast.

**Comment by lefterav** [comment]
I also have the same problem
