### ISSUE TITLE
Playlists with an external URL as a playback source (shoutcast or icecast stream) are not stored on the fly and executed at the set time.

### ISSUE THREAD

**Issue by rolradio** [AzuraCast/AzuraCast#2113]
**Using Docker installation method**
Yes

**Host Operating System**
Unbuntu 10

**Describe the bug**

**To Reproduce**

Playlists with an external URL as a playback source (shoutcast or icecast stream) are not stored on the fly and executed at the set time.
The radio must first be restarted, only then will the playlist with external URL actually be played at the set hour.

From then on, playing next will no longer work either.
Even if the playlist with external URL has stopped playing.

**Expected behavior**

New playlist with external url as stream must be stored on the fly in the playlist and retrieved at the set hour. Without having to restart the station each time.

Playing next should also work back when the playlist has finished playing.
**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@rolradio We're definitely aware of some problems with external URL playlists. The current version of Liquidsoap that we're on has some known issues with handling them.

It's possible that once Liquidsoap 1.4.0 is released and we're upgraded to it, it'll resolve some of the issues we're having with remote URL playlists.

**Comment by rolradio** [comment]
Okay,

Thank you.
I hope for a solution with the next release from liquidesoap.
