### ISSUE TITLE
Raspberry Pi4 / Ubuntu 18.04

### ISSUE THREAD

**Issue by TheRealMakkus** [AzuraCast/AzuraCast#2115]
Hi @ all, 

I would like to install Azuracast on a Raspberry Pi 4 (4 GB). Since Azuracast is not running on Ubuntu 19.10 for the Raspberry, I found a customized 18.04, which now runs on the Raspberry 4.

I downloaded and installed as described on https://www.azuracast.com/install/install_ansible.html. This worked with my Raspberry Pi 3 Model B+ with Ubuntu 18.04 without any problems. Now, on Raspberry Pi 4 i get the following error: 

TASK [azuracast-setup : Run AzuraCast Setup (Install Mode)] ***************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/azuracast.php azuracast:setup", "delta": "0:00:02.544817", "end": "2019-10-30 21:45:59.475936", "msg": "non-zero return code", "rc": 1, "start": "2019-10-30 21:45:56.931119", "stderr": "\nIn Database.php line 103:\n                                       \n  Failed to created database stations  \n                                       \n\nIn Client.php line 196:\n                                                                               \n  Query has failed: cURL error 7: Failed to connect to localhost port 8086: C  \n  onnection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)   \n                                                                               \n\nIn CurlFactory.php line 200:\n                                                                               \n  cURL error 7: Failed to connect to localhost port 8086: Connection refused   \n  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)                     \n                                                                               \n\nazuracast:setup [--update] [--load-fixtures] [--release]", "stderr_lines": ["", "In Database.php line 103:", "                                       ", "  Failed to created database stations  ", "                                       ", "", "In Client.php line 196:", "                                                                               ", "  Query has failed: cURL error 7: Failed to connect to localhost port 8086: C  ", "  onnection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)   ", "                                                                               ", "", "In CurlFactory.php line 200:", "                                                                               ", "  cURL error 7: Failed to connect to localhost port 8086: Connection refused   ", "  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)                     ", "                                                                               ", "", "azuracast:setup [--update] [--load-fixtures] [--release]"], "stdout": "\nAzuraCast Setup\n===============\n\nWelcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...\n * Environment: Production\n * Installation Method: Ansible\n\nSetting Up InfluxDB\n-------------------", "stdout_lines": ["", "AzuraCast Setup", "===============", "", "Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...", " * Environment: Production", " * Installation Method: Ansible", "", "Setting Up InfluxDB", "-------------------"]}

RUNNING HANDLER [azuracast-user : send user notification] *****************************************************************************************************************************************

RUNNING HANDLER [azuracast-db-install : send mysql notification] **********************************************************************************************************************************

PLAY RECAP ****************************************************************************************************************************************************************************************
localhost                  : ok=86   changed=66   unreachable=0    failed=1    skipped=9    rescued=0    ignored=2   

Any Ideas?

**Comment by SlvrEagle23** [comment]
@TheRealMakkus We don't officially support the Raspberry Pi platform for running AzuraCast, but it should be working properly, especially if it works on the 3B devices.

In this case, the error seems to be related to the `influxdb` package. You may want to check to see if that package can install by itself. It's also possible that it just took too long to spin up (which sometimes happens on slower computers) and it wasn't ready by the time the main installer kicked in.

**Comment by TheRealMakkus** [comment]
@SlvrEagle23 thank you for your reply.

I un- and reinstalled infuxdb without errors. I also changed the file in ./util/ansible/roles/influxdb/tasks/main.yml to give influxdb 20 seconds to start. This did not help. 

After that, I tried "service influxdb stop" and "influxd" to get influxdb in foreground. Now the setup runs without errors. Don't know why, but... now everything seems to run perfect. :-)

**Comment by Veolene** [comment]
> @SlvrEagle23 thank you for your reply.
> 
> I un- and reinstalled infuxdb without errors. I also changed the file in ./util/ansible/roles/influxdb/tasks/main.yml to give influxdb 20 seconds to start. This did not help.
> 
> After that, I tried "service influxdb stop" and "influxd" to get influxdb in foreground. Now the setup runs without errors. Don't know why, but... now everything seems to run perfect. :-)

After the installation attempt, the "service influxdb stop" and the "influxd" I tried to install AzuraCast, with no succession. I also tried to apply "sudo influxd", but I get stuck on a query in that command forever. Is there a part I missed or is there something you did I didn't ?
