### ISSUE TITLE
I tried installing Azuracast with Traditional Installation Ubuntu 16.04 LTS and 18.04 LTS but this one gave me an error

### ISSUE THREAD

**Issue by vipercast** [AzuraCast/AzuraCast#2116]
![ok](https://user-images.githubusercontent.com/57198534/67938097-820de580-fbd7-11e9-9efc-2fa61c5f113a.png)
in the past it has been successful..  this has been happening for two days..
(note that it happens in all versions)

**Comment by ermelindonunes** [comment]
Instala novamente

**Comment by vipercast** [comment]
@ermelindonunes I've been trying it on many versions. and nothing. on two servers vps :p

**Comment by drno88** [comment]
I had the same problem.
I circumvented it by installing version 0.9.6.
After that I launched the update.
at that time the latest version was 0.9.6.5

Now when I try to update my version, I get an error ((

**Comment by Veolene** [comment]
> I had the same problem.
> I circumvented it by installing version 0.9.6.
> After that I launched the update.
> at that time the latest version was 0.9.6.5
> 
> Now when I try to update my version, I get an error ((
> 
> I apologize. It was my mistake. The update was successful.

How would you go about installing an older version of AzuraCast?

**Comment by drno88** [comment]
> > I had the same problem.
> > I circumvented it by installing version 0.9.6.
> > After that I launched the update.
> > at that time the latest version was 0.9.6.5
> > Now when I try to update my version, I get an error ((
> > I apologize. It was my mistake. The update was successful.
> 
> How would you go about installing an older version of AzuraCast?

I do not quite understand your question.
How did I guess to install the old version?
Or what version did I install?
