### ISSUE TITLE
Custom Fading: Fade-Out Time (seconds)

### ISSUE THREAD

**Issue by themadcap1976** [AzuraCast/AzuraCast#2117]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04.3 LTS

**Describe the bug**
After saving any song's Custom Fading: Fade-Out Time (seconds) the message "An error occurred and your request could not be completed" is displayed. I've tried using a mm:ss and seconds only and I experience the same.

**Expected behavior**
save the time set and not produce error.

**Relevant Logs**
I don't see anything abmormal

**Screenshots**
![Screen Shot 2019-11-01 at 1 51 52 PM](https://user-images.githubusercontent.com/32073620/68044969-d0da7e80-fcae-11e9-876a-aaa0b6816203.png)
![Screen Shot 2019-11-01 at 1 51 59 PM](https://user-images.githubusercontent.com/32073620/68044976-d3d56f00-fcae-11e9-9c53-0f5c8d0dad66.png)

**Device(s):**
 - Device: Mac mini (Late 2012)
 - OS: MacOS Mojave 
 - Browser: Chrome 
 - Version: Version 78.0.3904.70 (Official Build) (64-bit)

**Additional context**
n/a

**Comment by beaugast** [comment]
You must use seconds. So 7 minutes X 60 seconds = 420. Add the other 29 seconds = 449. Hit save. That should work. Only the song length is in minutes and seconds.

**Comment by themadcap1976** [comment]
I used seconds only and got the same error. I try again.

**Comment by biguenique** [comment]
I think it is meant to be the time of the fade out itself (eg. 5 seconds) before cue-out or end-of-song. If you want to cut off the end of the song, use the Cue-Out Point.

**Comment by themadcap1976** [comment]
that works! user error then, we can close this.

**Comment by SlvrEagle23** [comment]
@themadcap1976 I wanted to make this easier for users, so I've gone ahead and added in special parsing on the application side, so if you enter a time in the format "MM:SS" (or "HH:MM:SS" for the cue points) it'll convert it to seconds for you instead of just outright rejecting it. :)

**Comment by themadcap1976** [comment]
Thank you!
