### ISSUE TITLE
Installation error on Ubuntu 16.4/18.4 Ansible

### ISSUE THREAD

**Issue by beastieboy** [AzuraCast/AzuraCast#2118]
**Using Docker installation method**

No

**Host Operating System**
Ubuntu 16.04 server x64
Ubuntu 18.04 server x64

**Describe the bug**
At the very end of the istallation I experience the same error like many other people before me:

TASK [azuracast-setup : Run AzuraCast Setup (Install Mode)] ***************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/azuracast.php azuracast:setup", "delta": "0:00:02.544817", "end": "2019-11-02 21:45:59.475936", "msg": "non-zero return code", "rc": 1, "start": "2019-11-02 21:45:56.931119", "stderr": "\nIn Database.php line 103:\n \n Failed to created database stations \n \n\nIn Client.php line 196:\n \n Query has failed: cURL error 7: Failed to connect to localhost port 8086: C \n onnection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) \n \n\nIn CurlFactory.php line 200:\n \n cURL error 7: Failed to connect to localhost port 8086: Connection refused \n (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) \n \n\nazuracast:setup [--update] [--load-fixtures] [--release]", "stderr_lines": ["", "In Database.php line 103:", " ", " Failed to created database stations ", " ", "", "In Client.php line 196:", " ", " Query has failed: cURL error 7: Failed to connect to localhost port 8086: C ", " onnection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) ", " ", "", "In CurlFactory.php line 200:", " ", " cURL error 7: Failed to connect to localhost port 8086: Connection refused ", " (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) ", " ", "", "azuracast:setup [--update] [--load-fixtures] [--release]"], "stdout": "\nAzuraCast Setup\n===============\n\nWelcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...\n * Environment: Production\n * Installation Method: Ansible\n\nSetting Up InfluxDB\n-------------------", "stdout_lines": ["", "AzuraCast Setup", "===============", "", "Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...", " * Environment: Production", " * Installation Method: Ansible", "", "Setting Up InfluxDB", "-------------------"]}

**Temporary solution**
Launch another ssh session and issue: "service influxdb stop" and then "influxd" to get influxdb in foreground. Now repeat the setup: "/var/azuracast/www/install.sh".

**Comment by ogrenci01** [comment]
Hi @beastieboy;

Please review here once: - #2035 -

It was solved by this and similar problems. Ansible installation is not recommended. You can try Docker installation if you don't have to.

I want to help you with an immediate solution.

1-) `sudo apt-get update -y`
2-) `sudo apt-get install -q -y git`
3-) `sudo mkdir -p /var/azuracast/www`
4-) `cd /var/azuracast/www`
5-) `sudo git clone https://github.com/AzuraCast/AzuraCast.git .`
6-) `sudo chmod a+x install.sh`
7-) `sudo chmod a+x update.sh`
8-) Download an older version:
**https://github.com/azuracast/azuracast/archive/0.9.6.zip**
9-) Use FTP to upload this archive to the directory "/var/azuracast/www". Accept changes.
10-) `sudo ./install.sh` After completing the installation, start and complete the installation.
11-) Download the latest version after completing the installation.
**https://codeload.github.com/AzuraCast/AzuraCast/zip/master**
12-) Upload this archive to FTP directory "/var/azuracast/www". Accept changes.
13-) `sudo ./update.sh` After the installation is complete, start and complete the update.
14-) After the update is completed, Azuracast will be ready to use.

Enjoy!

**Comment by radioservicios** [comment]
Hello

Some error after step 6 and 7 (such a file not found) Fix with

1-) sudo apt-get update -y
2-) sudo apt-get install -q -y git
3-) sudo mkdir -p /var/azuracast/www
4-) cd /var/azuracast/www
5-) sudo git clone https://github.com/AzuraCast/AzuraCast.git .

6-) cd /var/azuracast/www/AzuraCast

7-) sudo chmod a+x install.sh
8-) sudo chmod a+x update.sh
9-) Download an older version:
https://github.com/azuracast/azuracast/archive/0.9.6.zip
10-) Use FTP to upload this archive to the directory "/var/azuracast/www". Accept changes.
11-) sudo ./install.sh After completing the installation, start and complete the installation.
12-) Download the latest version after completing the installation.
https://codeload.github.com/AzuraCast/AzuraCast/zip/master
13-) Upload this archive to FTP directory "/var/azuracast/www". Accept changes.
14-) sudo ./update.sh After the installation is complete, start and complete the update.
15-) After the update is completed, Azuracast will be ready to use.

Enjoy!

**Comment by Veolene** [comment]
> 9-) Download an older version:
> https://github.com/azuracast/azuracast/archive/0.9.6.zip
> 10-) Use FTP to upload this archive to the directory "/var/azuracast/www". Accept changes.
> 12-) Download the latest version after completing the installation.
> https://codeload.github.com/AzuraCast/AzuraCast/zip/master
> 13-) Upload this archive to FTP directory "/var/azuracast/www". Accept changes.


Is there a possibility for you to elaborate the way you can copy over those file through ftp?

**Comment by radioservicios** [comment]
you can use a SCP client and loggin with ssh credentials of your internet provider or server. i use WinSCP and replace the files of AzuraCast directory.

**Comment by ogrenci01** [comment]
Hi;

Up to step 8 is the AzuraCast normal installation. What we need to do here is to clone the AzuraCast installation via github. You can get up-to-date updates without problems. The next step is to start the installation with an old AzuraCast copy installed without any problem. You can connect to your server's root information using FTP programs. I am using FileZilla. Once the installation is complete, download the latest version of AzuraCast from the github and again upload it to the AzuraCast directory via FTP. Be sure to overwrite files in both processes. You will have the latest version of AzuraCast with the update commands.

I'm talking about is a temporary solution. The AzuraCast team will help you with the problem.

**Comment by SlvrEagle23** [comment]
@ogrenci01 I have no idea why any of these steps are necessary. We haven't changed the Ansible installation in quite a while, and none of these things should be required.

If there is a problem with the new installer, please submit a pull request with the necessary changes to our installer instead of recommending that users use older versions of the software.

**Comment by ogrenci01** [comment]
@SlvrEagle23 

I don't install often. I'm saying a temporary suggestion. I'm not an advanced coder.

I want to help users. Azuracast is a great project. Thank you for Azuracast.
