### ISSUE TITLE
Installed Successfully but The Web won't work!

### ISSUE THREAD

**Issue by DJDylanP** [AzuraCast/AzuraCast#2119]
http://prntscr.com/prnz8g

Everything was fine just then the web didn't work

**Comment by SC2Mitch** [comment]
Have you tried restarting Azuracast?

**Comment by DJDylanP** [comment]
Yes. Just did @SC2Mitch

**Comment by NationsGlory** [comment]
Did you change the port on the .env settings in the azuracast directory ?

**Comment by DJDylanP** [comment]
I did not touch it. It said it was successful and I tried loading it and it
didn’t work

**Comment by NationsGlory** [comment]
Well, i see u are in google machine, right ? By default the port 820 is blocked, did u open it ?

**Comment by DJDylanP** [comment]
How do you unblock via a command? Through website is a bit difficult

**Comment by NationsGlory** [comment]
U cant do it with commands, u have to use the console

**Comment by DJDylanP** [comment]
I’ll do it on computer and get back to you tomorrow thanks for the advice
so far!
