### ISSUE TITLE
Error 500 or nginx 502 Bad Gateway when collect history data

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2123]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu 18.04

(Azuracast ver.  v0.9.7.1, #52e3d86)

**Describe the bug**
When i'm trying to collect history data via the api for range of more than 10 days, i'm getting error 500 or nginx 502 Bad Gateway.
I tried to increase the php memory limit to 1024 but it not solved the issue.
I've checked web and stations logs while it happened and didn't see anything special. 
Please advice how to debug and solve the issue.
Thank You.

**Comment by eranwo** [comment]
Any idea how to optimize it? This problem occurs only by the api. When collecting playback timeline statistics by the web panel, it works well and display the data on screen, but when trying to download the csv it leads to an error (nginx 502 Bad Gateway or error 500)

**Comment by Vaalyn** [comment]
I can replicate this issue and these are the errors I get from it via `docker-compose logs web`:
```
[WARNING] [pool www] child 51334 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 51"
[WARNING] [pool www] child 51334 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 32768 bytes) in /var/azuracast/www/vendor/sentry/sentry/src/Exception/FatalErrorException.php on line 1"
[error] 71#71: *912734 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 51
PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 32768 bytes) in /var/azuracast/www/vendor/sentry/sentry/src/Exception/FatalErrorException.php on line 1" while reading response header from upstream, client: xx.xx.xx.xx, server: localhost, request: "GET /api/station/1/history?format=csv&start=2019-05-01&end=2019-11-30 HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "radio.bronyradiogermany.com", referrer: "https://radio.bronyradiogermany.com/station/1/reports/timeline"
```

Seems like it's just too much data that's fetched at once and which will be converted from an array to a CSV file completely in memory until the file is complete and then send to the client.

The memory usage might be reduced by taking advantage of Doctrines [`Query#iterate`](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/batch-processing.html#iterating-large-results-for-data-processing) method and by writing the CSV to a temp file and then streaming that temp file to the client so that it is never completely loaded into memory.

**Comment by eranwo** [comment]
So basically it's server memory issue?
The issue is happening not just in csv case but also when trying to get the data via API like this:
/history?start=2019-10-12&end=2019-11-10

Is there a way to avoid this ?

**Comment by Vaalyn** [comment]
> So basically it's server memory issue?

Yes, this seems like the culprit here.

> Is there a way to avoid this ?

You wrote that you `tried to increase the php memory limit to 1024` which did not help, would you mind showing me what you did to increase the memory limit? It happened a few times that people mistakenly edited the wrong environment file to do this. You have to edit the `azuracast.env` file not the `.env` file and then restart AzuraCast.

**Comment by eranwo** [comment]
azuracast.env

#
# Advanced Configuration
#

# PHP's maximum POST body size and max upload filesize.
# PHP_MAX_FILE_SIZE=64M

# PHP's maximum memory limit.
 PHP_MEMORY_LIMIT=1048M

# PHP's maximum script execution time (in seconds).
 PHP_MAX_EXECUTION_TIME=120

# Maximum number of PHP-FPM worker processes to spawn.
 PHP_FPM_MAX_CHILDREN=10

# Create additional media sync worker processes.
#   This setting can be used to increase the performance of the media sync process
#   by creating additional worker processes to consume messages
# Default: 0
# ADDITIONAL_MEDIA_SYNC_WORKER_COUNT=0

Maybe it's possible to optimise also the nginx?

**Comment by Vaalyn** [comment]
The config seems to be fine and should work.

Can you try to download the CSV again so that it fails and then use `docker-compose logs web` to view all logs of the web container. Search for something similar to what I posted above to see how much memory AC tries to allocate.

> Maybe it's possible to optimise also the nginx?

In theory we can expose all sorts of options via the environment (if it makes sense) although I wouldn't add stuff without having someone with a use-case that justifies the addition of a specific setting. So until we hit an error / warning from nginx we shouldn't prematurely optimise that part of the stack.

**Comment by eranwo** [comment]
here the log ( got nginx 502 Bad Gateway)

1       | 2019/11/10 15:02:35 [warn] 67#67: *127676 upstream server temporarily disabled while reading response header from upstream, client: x.x.x.x, server: localhost, request: "GET /api/station/8/history?start=2019-10-01&end=2019-11-10 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "x.x.x.x"
web_1       | Nov 10 15:02:35 3d4e63fe47cc php-fpm[62]: [WARNING] [pool www] child 404 exited on signal 9 (SIGKILL) after 538.116522 seconds from start
web_1       | Nov 10 15:02:35 3d4e63fe47cc php-fpm[62]: [NOTICE] [pool www] child 1816 started
web_1       | [2019-11-10T15:02:36.113617+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"st ation":{"id":5,"name":"heb1"}}
web_1       | 2019/11/10 15:02:38 [error] 67#67: *127676 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: x.x.x.x, server: localhost, request: "GET /api/station/8/history?start=2019-10-01&end=2019-11-10 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host:  "x.x.x.x"
web_1       | 2019/11/10 15:02:38 [warn] 67#67: *127676 upstream server temporarily disabled while reading response header from upstream, client: x.x.x.x, server: localhost, request: "GET /api/station/8/history?start=2019-10-01&end=2019-11-10 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "x.x.x.x"
web_1       | Nov 10 15:02:38 3d4e63fe47cc php-fpm[62]: [WARNING] [pool www] child 1344 exited on signal 9 (SIGKILL) after 183.487153 seconds from start
web_1       | Nov 10 15:02:38 3d4e63fe47cc php-fpm[62]: [NOTICE] [pool www] child 1824 started
web_1       | 2019/11/10 15:02:38 [error] 67#67: *127682 no live upstreams while connecting to upstream, client: 172.26.0.5, server: localhost, request: "POS T /api/internal/3/nextsong HTTP/1.1", upstream: "fastcgi://localhost", host: "web"
web_1       | 2019/11/10 15:02:39 [error] 67#67: *127683 no live upstreams while connecting to upstream, client: 172.26.0.5, server: localhost, request: "POS T /api/internal/3/nextsong HTTP/1.1", upstream: "fastcgi://localhost", host: "web"
web_1       | 2019/11/10 15:02:39 [error] 67#67: *127684 no live upstreams while connecting to upstream, client: 172.26.0.5, server: localhost, request: "POS T /api/internal/3/nextsong HTTP/1.1", upstream: "fastcgi://localhost", host: "web"
web_1       | 2019/11/10 15:02:39 [error] 67#67: *127685 no live upstreams while connecting to upstream, client: 172.26.0.5, server: localhost, request: "POS T /api/internal/3/nextsong HTTP/1.1", upstream: "fastcgi://localhost", host: "web"
web_1       | 2019/11/10 15:02:41 [error] 67#67: *127686 no live upstreams while connecting to upstream, client: 172.26.0.5, server: localhost, request: "POS T /api/internal/3/nextsong HTTP/1.1", upstream: "fastcgi://localhost", host: "web"
web_1       | 2019/11/10 15:02:42 [error] 67#67: *127687 no live upstreams while connecting to upstream, client: 172.26.0.5, server: localhost, request: "POS T /api/internal/3/nextsong HTTP/1.1", upstream: "fastcgi://localhost", host: "web"
web_1       | 2019/11/10 15:02:42 [error] 67#67: *127688 no live upstreams while connecting to upstream, client: 172.26.0.5, server: localhost, request: "POS T /api/internal/3/nextsong HTTP/1.1", upstream: "fastcgi://localhost", host: "web"
web_1       | 2019/11/10 15:02:42 [error] 67#67: *127689 no live upstreams while connecting to upstream, client: 172.26.0.5, server: localhost, request: "POS T /api/internal/8/feedback HTTP/1.1", upstream: "fastcgi://localhost", host: "web"
web_1       | 2019/11/10 15:02:42 [error] 67#67: *127690 no live upstreams while connecting to upstream, client: 172.26.0.5, server: localhost, request: "POS T /api/internal/3/nextsong HTTP/1.1", upstream: "fastcgi://localhost", host: "web"
web_1       | 2019/11/10 15:02:44 [error] 67#67: *127691 no live upstreams while connecting to upstream, client: 172.26.0.5, server: localhost, request: "POS T /api/internal/3/nextsong HTTP/1.1", upstream: "fastcgi://localhost", host: "web"
web_1       | 2019/11/10 15:02:45 [error] 67#67: *127692 no live upstreams while connecting to upstream, client: 172.26.0.5, server: localhost, request: "POS T /api/internal/3/nextsong HTTP/1.1", upstream: "fastcgi://localhost", host: "web"
web_1       | 2019/11/10 15:02:45 [error] 67#67: *127693 no live upstreams while connecting to upstream, client: 172.26.0.5, server: localhost, request: "POS T /api/internal/3/nextsong HTTP/1.1", upstream: "fastcgi://localhost", host: "web"
web_1       | 2019/11/10 15:02:45 [error] 67#67: *127694 no live upstreams while connecting to upstream, client: 172.26.0.5, server: localhost, request: "POS T /api/internal/3/nextsong HTTP/1.1", upstream: "fastcgi://localhost", host: "web"

**Comment by eranwo** [comment]
Hi, any thoughts about this bug?
Does the log I provided help to understand the source of the problem?

**Comment by eranwo** [comment]
This issue still exist also on the latest version

v0.9.8, #225981f (2019-11-30 20:15) • Docker • PHP 7.4

**Comment by eranwo** [comment]
Hi @Vaalyn,
This issue still exist also on the latest version
v0.9.8, #225981f (2019-11-30 20:15) • Docker • PHP 7.4
