### ISSUE TITLE
Programming playlist/calander

### ISSUE THREAD

**Issue by regionradio** [AzuraCast/AzuraCast#2125]
Does anyone have a video on how to program the playlist?  I want to create blocks such as pic 2 song from folder A, one song from folder b, 2 songs from folder c, one from sweeper, one from commercial.  

I would also like to be able to program it to play 1 file from folder z at 7pm every sunday at 7pm.

I can not figure any of this out!

Please help, Thanks

**Comment by rmacari** [comment]
@regionradio I don´t know if I understood your first question, but the second one is simple:

First, you have to understand that the system use files, not directories, you can and probably should create directories to organize better your station, but the playlist system works just pointing in the playlist to a file.  In my case, I´ve created directories for jingles, spots, types of music and etc.

Start by creating a playlist (Add Playlist) and use my example to create a playlist that will play a file every Sunday at 10 AM.

![Screen Shot 2019-11-09 at 09 02 33](https://user-images.githubusercontent.com/5432270/68526059-c718d280-02cf-11ea-89f9-efc1a699afaa.png)
![Screen Shot 2019-11-09 at 09 02 45](https://user-images.githubusercontent.com/5432270/68526060-c718d280-02cf-11ea-9dda-062ddc0737c3.png)
![Screen Shot 2019-11-09 at 09 02 51](https://user-images.githubusercontent.com/5432270/68526061-c718d280-02cf-11ea-8756-d7f8f1cb5256.png)

Click Save Changes to finish creating the playlist.

After this, you will have to tell the system where is the files that you want to play on that playlist. Go to Music Files, Select the file or the entire directory where you keep just those files for this playlist, ATOP40 in my case, Click Playlists on the top blue button, select the playlist and click Save. That is it, you are done. 

![Screen Shot 2019-11-09 at 09 06 29](https://user-images.githubusercontent.com/5432270/68526123-7c4b8a80-02d0-11ea-82ee-96133ccbdcd9.png)
![Screen Shot 2019-11-09 at 09 06 51](https://user-images.githubusercontent.com/5432270/68526124-7c4b8a80-02d0-11ea-8f53-c56d6bcbf417.png)
![Screen Shot 2019-11-09 at 09 07 05](https://user-images.githubusercontent.com/5432270/68526125-7ce42100-02d0-11ea-96cb-294aa9db225d.png)

**Comment by regionradio** [comment]
Ok this helps.  Right now what I use is sam broadcaster cloud. 
I have several folders country gold, 80s,90s,00s,10s, local, and game show, station ID etc. 
I have a block set like this..

90s
Gold
10s
Station ID
80s
00s
90s
Gold
Station I'd
Etc.

Then I have set at :15 and :45 after each hr it randomly loads a local sweeper then a local artist.

Sundays at 7pm it pulls 1 track from the 1hr show I created.

This can be done here from what I can tell?

**Comment by rmacari** [comment]
> Ok this helps. Right now what I use is sam broadcaster cloud.
> I have several folders country gold, 80s,90s,00s,10s, local, and game show, station ID etc.
> I have a block set like this..
> 
> 90s
> Gold
> 10s
> Station ID
> 80s
> 00s
> 90s
> Gold
> Station I'd
> Etc.
> 
> Then I have set at :15 and :45 after each hr it randomly loads a local sweeper then a local artist.
> 
> Sundays at 7pm it pulls 1 track from the 1hr show I created.
> 
> This can be done here from what I can tell?

Azuracast use playlists instead of blocks like Sam, it´s way different and you will have a learning curve here, but I´ve managed to create almost like what you are doing right now, but you will have to be creative, it´s easy to have your station running with Azuracast but it´s not easy if you think in blocks.

**Comment by regionradio** [comment]
The blocks are just a list that runs. The important part to me the the
local slots orgramed at :15 and ;45 and the show going in at 7pm

**Comment by rmacari** [comment]
@regionradio Maybe i can help you directly to build this, if you wish that you can contact me directly, use the contact button at our radio http://radiolivre95.com. (I hope this is ok with the admins)(Not SPAM) :)
