### ISSUE TITLE
Playlists not playing at the scheduled time and station time zone not correct after update

### ISSUE THREAD

**Issue by rmacari** [AzuraCast/AzuraCast#2127]
**Using Docker installation method**

yes

**Host Operating System**

Mac OS 
**Describe the bug**

After update to the latest release, my scheduled playlists don´t play anymore also the Station Time Zone has changed to -2 in the station clock although it is set to -3 (Sao Paulo). I´ve had to set up to Buenos Aires to get the correct time. The schedule view shows the correct time and playlist in the correct scheduled time. 

**To Reproduce**

**Expected behavior**

**Relevant Logs**

No errors in logs.

**Screenshots**

![Screen Shot 2019-11-08 at 12 24 16](https://user-images.githubusercontent.com/5432270/68476663-371d4f00-0223-11ea-8dec-51e55601448e.png)
![Screen Shot 2019-11-08 at 12 24 24](https://user-images.githubusercontent.com/5432270/68476664-37b5e580-0223-11ea-9362-074b103e9b9e.png)
![Screen Shot 2019-11-08 at 12 24 31](https://user-images.githubusercontent.com/5432270/68476665-37b5e580-0223-11ea-897e-87deecd9ce47.png)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

I don´t know what else shows and send, but please make questions and look into this issue. 

Thank you.

**Comment by themadcap1976** [comment]
I'm having the same issue.

**Comment by rmacari** [comment]
> I'm having the same issue.

I´m using the new feature of multiple schedules for the same playlist. I´ve disabled that and the playlist is working again. Try removing the extra schedules and keep just one.

**Comment by themadcap1976** [comment]
I did that and also forced it to interrupt and it doesn't work.

**Comment by SlvrEagle23** [comment]
@rmacari The recent update didn't change station time zones in any way, so I'm not sure why it would've changed, other than possibly Daylight Saving Time causing a shift in what time a given zone is using.

Also, you can't really "disable" the multiple schedule entries feature, so are you saying the first scheduled listing works fine but other ones don't?

**Comment by themadcap1976** [comment]
In my case, I can't pin point when the scheduled playlists stopped working.
I m going to reboot the host tonight just to clear anything up there. I
will update accordingly.

**Comment by rmacari** [comment]
> @rmacari The recent update didn't change station time zones in any way, so I'm not sure why it would've changed, other than possibly Daylight Saving Time causing a shift in what time a given zone is using.

 @SlvrEagle23 I think that is something related to the DST, but the station clock goes down one hour and with DST it should go up (+1 hour). My setup was set to Sao Paulo (-3) and the station clock shows -2, to fix that I´ve had to change my station time zone to Buenos Aires to get the clock at -3 again, but that is a temp fix. 
> 
> Also, you can't really "disable" the multiple schedule entries feature, so are you saying the first scheduled listing works fine but other ones don't?

Sure, that was a poor choice of words, by "disable" I mean not using the feature, not using the multiple entries feature. Again, when I try to use the multiple entries the playlist won´t play. Also, I´ve had to put every playlist on a time schedule, because they won´t stop playing when the timed one is in place, that is just different I know but this also made the Schedule View a nightmare. 

![Screen Shot 2019-11-09 at 08 52 03](https://user-images.githubusercontent.com/5432270/68525906-47d6cf00-02ce-11ea-9b5c-aa64a05fa619.png)

Thank you for your help. :)

**Comment by rmacari** [comment]
> I did that and also forced it to interrupt and it doesn't work.

 @SlvrEagle23  I think I still have the same issue, even after removing the multiple scheduling. I also tried deleting the playlist and starting from scratch. I have 4 playlists having the same issue, they are 2 playlists duplicated to play the same files at different times on the same day when the new update was installed with the new multiple schedule feature I deleted the duplicated and used the new feature since then I have the issue.

**Comment by SlvrEagle23** [comment]
@rmacari I understand there may be a language barrier here, but I really don't understand how I can reproduce your issue for local testing. I would need to know the specific settings of your playlists in order to test things locally.

One important thing to note is that if you have _any_ of the "Advanced" playlist settings checked (i.e. "interrupt other songs"), this will trigger the use of Liquidsoap's AutoDJ instead of our own, which will yield less predictable results, so you should start by disabling those options first if they're enabled.

**Comment by rmacari** [comment]
@SlvrEagle23 It´s ok, I understand the limitations here. But since I´m not the only having the same issue there is definitely something here right? Maybe if I give access to our server that could help you to try to figure it out this. Please let me know, send me a message and I´ll send the details.

**Comment by rmacari** [comment]
@themadcap1976 Did you manage to fix this or are you still having the same problem?

**Comment by themadcap1976** [comment]
> @themadcap1976 Did you manage to fix this or are you still having the same problem?
I deleted the playlist, re-created it and it's working. I haven't set the multiple schedules on it. 
I will delete another playlist, re-create it and set to multiple schedules and see if that fixes it.

**Comment by cristianocarrozzi** [comment]
@SlvrEagle23  I need use "Advanced" playlist settings checked (i.e. "interrupt other songs") . It's possible to fix or  have another solution? Advanced Playlists maybe?

**Comment by rmacari** [comment]
> > I deleted the playlist, re-created it and it's working. I haven't set the multiple schedules on it.
> > I will delete another playlist, re-create it and set to multiple schedules and see if that fixes it.
@themadcap1976 I did the same here and after several tests, the playlist will run normal but only if you don´t use the multiple schedule option. @SlvrEagle23 This information helps you?

**Comment by cristianocarrozzi** [comment]
I created a new playlist and use AutoDJ Scheduling Options, put many schedules, restart the station and its working now!
![image](https://user-images.githubusercontent.com/53878223/68789426-366e2980-0624-11ea-975d-49996ba736f8.png)
The Scheduling with dates or no dates works!
![image](https://user-images.githubusercontent.com/53878223/68789497-569de880-0624-11ea-9cc4-80e59faf1446.png)

**Comment by rmacari** [comment]
> I created a new playlist and use AutoDJ Scheduling Options, put many schedules, restart the station and its working now!


@cristianocarrozzi Sorry, but I don´t think the way you programed the playlist is actually working. I noticed that you used the option that enforces the playlist (interrupt other songs) that is awful for the listener as it breaks the music, but scheduling with a 5 min a part sounds odd. Is this just for testing? And you don´t need to set the date, you can leave it blank.

**Comment by cristianocarrozzi** [comment]
@rmacari It's just a test. Thats why I used different ways to schedule.

**Comment by rmacari** [comment]
@cristianocarrozzi Got it, I thought that was a test. :)

**Comment by rmacari** [comment]
I´m still having all the issues reported here, to have the radio up and running as it should  I'm doing a lot of workarounds. 

@SlvrEagle23 I´m ready to give you access to our server and radio, this way you can investigate the matter. Please let me know. Thanks.

**Comment by SlvrEagle23** [comment]
@rmacari These schedule issues should be addressed by the recent updates from #2132. Closing this in favor of having one ticket to follow.
