### ISSUE TITLE
Playlist creation error

### ISSUE THREAD

**Issue by rmacari** [AzuraCast/AzuraCast#2128]
**Using Docker installation method**

yes

**Host Operating System**

Mac OS

**Describe the bug**

When trying to create a new playlist I receive a generic error message, the error only happens when trying to create a playlist with a time schedule. 

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

![Screen Shot 2019-11-08 at 17 13 22](https://user-images.githubusercontent.com/5432270/68497423-6ac09f00-024c-11ea-9061-512b987483fc.png)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@rmacari Thank you for the report. This should now be fixed as of the latest update.

**Comment by rmacari** [comment]
Thank you, my pleasure to help you build this great system.
