### ISSUE TITLE
Port change does not work!

### ISSUE THREAD

**Issue by Luislife2004** [AzuraCast/AzuraCast#2129]
**Using Docker installation method**
<Yes>

**Host Operating System**
<Linux Debian 10 64bit>

**Describe the bug**
<Hello ,
my azuracast server is installed on debian 10 .
Server : Dedicated 
My problem is i can`t  find this directory to change the port: 
/etc/nginx/sites-available/00-azuracast
You see that on the help page 
Link : https://www.azuracast.com/help/faq_ansible.html#use-non-standard-ports
Please help me 
Thank you :)>

**Comment by ogrenci01** [comment]
Hi @Luislife2004;

You may edit `00-azuracast` file in directory `/etc/nginx/sites-available`.  This guide is ansible installation way. 

Check it for Docker installation
Link: https://www.azuracast.com/help/faq_docker.html#use-non-standard-ports

Which ports do you want to change? You must write your request using Github template.
