### ISSUE TITLE
Request Embed Code

### ISSUE THREAD

**Issue by williambatson** [AzuraCast/AzuraCast#2130]
Maybe just a simple question - hoping so....

When accessing my request page thru the public page, it looks proper and matches the web page.

If I enter direct it's mess - example https://gyazo.com/01e6c3353ac8dbc18607808e2af7a10b

Bright white background with light grey text - very difficult to read.
Is there a simple way to format to be either look better or customize it all without going thru the public page and opening a frame?

Thanks if anyone has an easy fix -  not a bug or program issue.

**Comment by SlvrEagle23** [comment]
@williambatson The embeds are meant to have transparent backgrounds so they can "blend in" with whatever parent site is being used...by default, that will match the theme you have set for public pages, so in this case if that theme is dark, you'll see light text on top of the light background (which will be replaced with the site's background when it's actually embedded).

If I recall correctly, you can add `?theme=light` to the query parameters of the embeds to switch which theme is in use.
