### ISSUE TITLE
up next not showing after latest update

### ISSUE THREAD

**Issue by streamjamz** [AzuraCast/AzuraCast#2131]
**Using Docker installation method**

yes
**Host Operating System**

ubunut 18.04
**Describe the bug**

since i did the update tonight to the latest release the up next has stopped showing in dashboard and also doesnt show in my twitter anymore
**To Reproduce**

**Expected behavior**

expect up next to show on dashboard and when i set up webhooks for twitter
**Relevant Logs**

**Screenshots**

![screenshot-cloud sjamz com_4433-2019 11 11-23_14_59](https://user-images.githubusercontent.com/8143373/68641596-53e2ac80-04d9-11ea-809e-3a5c6559689f.png)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@streamjamz I would need to see logs from the AutoDJ to know what's causing this particular problem. You can find AutoDJ logs from the log viewer inside the system administration panel. You should see error messages indicating what's going wrong.
