### ISSUE TITLE
Restore from backup faild

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2133]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**

When trying to restore a backup to new server (both servers has the same Azuracast version - v0.9.7.1, #fe09b2c) getting :

 **[ERROR] Backup path /tmp/cli_backup.zip not found!**

After it, Azuracast (in the new server) fail to log in and it goes to setup/register.
Getting this error :
500
An exception occurred while executing 'INSERT INTO audit_log (timestamp, operation, class, identifier, target_class, target, changes, user) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [1573553854, 1, "Role", "Super Administrator", null, null, "a:1:{s:4:\"name\";a:2:{i:0;N;i:1;s:19:\"Super Administrator\";}}", null]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.audit_log' doesn't exist
AbstractMySQLDriver.php : 42

Azuracast_station_data folder is empty.

**Comment by griffon56** [comment]
Hi, maybe you should try to update your installation of azuracast.

**Comment by eranwo** [comment]
Hi,
It's on the latest version.
As i can see, the program delete the backup.zip file at the beginning of the restore process.

**Comment by eranwo** [comment]
Ok, I found out that the problem is where I uploaded the backup.zip. It should not be in the azuracast backup directory because during the restore process, the program deletes this folder. So it should be somewhere outside, for example in /root directory.

Now I don't get cli restore errors, but **still the restore doesn't work**.
**Here's what I get:**

 /var/azuracast # ./docker.sh restore /root/acast.zip
Restoring will remove any existing AzuraCast installation data, replacing it with your backup. Continue? [Y/n] y
Stopping azuracast_web        ... done
Stopping azuracast_stations   ... done
Stopping azuracast_mariadb_1  ... done
Stopping azuracast_influxdb_1 ... done
Stopping azuracast_redis_1    ... done
Removing azuracast_web        ... done
Removing azuracast_stations   ... done
Removing azuracast_mariadb_1  ... done
Removing azuracast_influxdb_1 ... done
Removing azuracast_redis_1    ... done
Removing network azuracast_default
Removing volume azuracast_db_data
Removing volume azuracast_influx_data
Removing volume azuracast_letsencrypt
Removing volume azuracast_shoutcast2_install
Removing volume azuracast_station_data
Removing volume azuracast_tmp_data
Removing volume azuracast_www_data
Removing volume azuracast_redis_data
Removing volume azuracast_backups
Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Creating network "azuracast_default" with the default driver
Creating volume "azuracast_db_data" with default driver
Creating volume "azuracast_influx_data" with default driver
Creating volume "azuracast_letsencrypt" with default driver
Creating volume "azuracast_shoutcast2_install" with default driver
Creating volume "azuracast_station_data" with default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_www_data" with default driver
Creating volume "azuracast_redis_data" with default driver
Creating volume "azuracast_backups" with default driver
Creating azuracast_redis_1    ... done
Creating azuracast_influxdb_1 ... done
Creating azuracast_stations   ... done
Creating azuracast_mariadb_1  ... done
Creating azuracast_web        ... done
Restoring AzuraCast...
(Environment: production)
Stopping azuracast_web        ... done
Stopping azuracast_stations   ... done
Stopping azuracast_influxdb_1 ... done
Stopping azuracast_mariadb_1  ... done
Stopping azuracast_redis_1    ... done
Removing azuracast_web        ... done
Removing azuracast_stations   ... done
Removing azuracast_influxdb_1 ... done
Removing azuracast_mariadb_1  ... done
Removing azuracast_redis_1    ... done
Removing network azuracast_default
Creating network "azuracast_default" with the default driver
Creating azuracast_influxdb_1 ... done
Creating azuracast_redis_1    ... done
Creating azuracast_stations   ... done
Creating azuracast_mariadb_1  ... done
Creating azuracast_web        ... done

**Comment by medialeakz** [comment]
Hello when I installed AzuraCast and try to register up at signing. I’m getting the following  error. 

An exception occurred while executing 'INSERT INTO audit_log (timestamp, operation, class, identifier, target_class, target, changes, user) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [1585714889, 1, "Role", "Super Administrator", null, null, "a:1:{s:4:\"name\";a:2:{i:0;N;i:1;s:19:\"Super Administrator\";}}", null]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.audit_log' doesn't exist
AbstractMySQLDriver.php : 42

Any solution?

**Comment by SlvrEagle23** [comment]
@medialeakz Try running an update after the initial installation.

**Comment by medialeakz** [comment]
It worked. Thank you.

**Comment by medialeakz** [comment]
Hey on the shoutcast admin page, there’s a player. The player doesn’t play. What could be the reason ?
