### ISSUE TITLE
AzuraCast playback has damaged before last update

### ISSUE THREAD

**Issue by petrix** [AzuraCast/AzuraCast#2134]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 16.04.6 LTS

**Describe the bug**

my 'AzuraServer' has damaged before last update
I think, the problem in LiquidSoap engine, they hasn't create mountpoints at :8000 icecast frontend,
and then I'm trying to start AutoDJ Service, I had that error - "Liquidsoap encountered an error
At line 99, char 29-31:
Error 6: Cannot apply that parameter because the function at line 99, char 8-18
has no argument labeled "start_next"!
At line 99, char 29-31:
Error 6: Cannot apply that parameter because the function at line 99, char 8-18
has no argument labeled "start_next"!"

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

https://ex-cast.tk/download/0/sh/4f0ad9a4183d821930af000ab45d66f7
**Device(s):**
 - Device:  
 - OS:  Ubuntu 16.04.6 LTS
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@petrix Make sure you're on the very latest version of the AzuraCast codebase, because we had to make some configuration changes to support the latest version of Liquidsoap.

**Comment by petrix** [comment]
I've run './docker.sh update-self' and './docker.sh update' just now, and have no changes, LiquidSoap are not starting yet

**Comment by petrix** [comment]
I've already trying at another VM with clean Ubuntu 16.04.6 LTS and clean docker installation and had the same result, LiquidSoap are not starting, and at :8000 is empty, zero mountpoints are created.

**Comment by SlvrEagle23** [comment]
@petrix Do you have a setting to prefer release versions? If you're downloading a release version, that will be out of date relative to the latest changes.

**Comment by SlvrEagle23** [comment]
@petrix I found the source of the problem -- I hadn't pushed the latest update that added compatibility with Liquidsoap 1.4.0. This has been pushed now; in about 5 minutes you should be able to update and everything will return to normal functioning.

**Comment by petrix** [comment]
Thank you very much! 
All stations started, and stable playing!
