### ISSUE TITLE
import translation

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#2137]
![56](https://user-images.githubusercontent.com/23697714/68789164-f9bb2600-0655-11ea-94d1-b567c8578c8b.png)
After importing a translation, the data in the interface of the radio station is not updated, although the import passes without errors.

**Comment by SlvrEagle23** [comment]
@susl16c For the new Vue components, you have to run:

```
npm run import-locales
npm run build
```

...to rebuild the assets using the updated translations.

**Comment by susl16c** [comment]
./docker.sh static npm run import-locales
./docker.sh static npm run build

I understand you correctly?

**Comment by SlvrEagle23** [comment]
@susl16c This is the same permissions issue you ran into with the translation files. Make sure the `web/static` folder is set to more permissively so you can write to it (you may need to run `chmod -R 775 web/static`

**Comment by susl16c** [comment]
> azuracast@ build /data/web/static
> gulp

[10:01:11] Using gulpfile /data/web/static/gulpfile.js
[10:01:11] Starting 'default'...
[10:01:11] Starting 'clean'...
[10:01:11] 'clean' errored after 58 ms
[10:01:11] Error: EACCES: permission denied, unlink '/data/web/static/dist/app-e71c721caa.js'
[10:01:11] 'default' errored after 60 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! azuracast@ build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the azuracast@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-11-17T10_01_11_338Z-debug.log
**nothing has changed the error remains anyway**

**Comment by susl16c** [comment]
[easygettext] extracting: './vue/webcaster/settings.vue
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '../../resources/locale/frontend.pot'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Object.<anonymous> (/data/web/static/node_modules/easygettext/src/extract-cli.js:81:6)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! azuracast@ generate-locales: `gettext-extract --attribute v-translate --keywords '$gettext' --output ../../resources/locale/frontend.pot $(find ./vue -type f -name '*.vue')`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the azuracast@ generate-locales script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-11-29T16_48_44_419Z-debug.log

**Comment by SlvrEagle23** [comment]
@susl16c I understand that you're having trouble building static assets and handling translations locally on your computer, but I don't know enough about your development environment to be able to help you.

The error is clearly a permissions one, so I would advise you to look into setting more open permissions in your environment for the files that are causing those errors.

**Comment by susl16c** [comment]
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '../../resources/locale/translations.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Object.<anonymous> (/data/web/static/node_modules/easygettext/src/compile-cli.js:44:6)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! azuracast@ import-locales: `gettext-compile --output ../../resources/locale/translations.json $(find ../../resources/locale/*.UTF-8 -type f -name '*.po')`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the azuracast@ import-locales script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-01-12T14_36_59_875Z-debug.log

**Comment by SlvrEagle23** [comment]
@susl16c Per the release notes in the latest version, static assets were moved over to the `frontend` folder.

Now, from the base of the installation, you'll want to run:

```bash
cd frontend
docker-compose run --rm frontend npm run import-locales
```

**Comment by susl16c** [comment]
And where is it all to read, I do not have time for changes, it seems to me more and more difficult

**Comment by susl16c** [comment]
cd /var/www/halk/data/www/AzuraCast
cd frontend
docker-compose run --rm frontend npm run import-locales

I have generated a translation in /var/www/halk/data/www/AzuraCast/resources/locale and in docker, nothing changes for me. If I move the file to docker /var/lib/docker/volumes/azuracast_www_data/_data/resources/locale and in this file I see translated phrases, but in **AzuraCast** they are not displayed

**Comment by SlvrEagle23** [comment]
@susl16c You shouldn't need to copy anything directly into the Docker volumes unless you're editing on a production-mode installation of AzuraCast instead of a developer mode one.

You should be using `docker-compose.dev.yml` as a basis for your Docker Compose file if you're wanting to use developer mode. That should reflect changes much more quickly.

Also, with regard to not having time for changes or making things more difficult, I don't have much to say about that. I am not making these changes to deliberately make things more difficult; in this case, pulling uncompiled raw assets out of the web root simply makes sense and has been a _long_ time coming.

**Comment by susl16c** [comment]
Then I can’t understand why I translate everything, I generate a translation, but it only changes in the folder AzuraCast but it’s not added to the docker and as a result, nothing changes, with failures I decided the question goes away, maybe you can write a sequence of commands, how should everything be done?

**Comment by SlvrEagle23** [comment]
@susl16c Basically here are the commands to import locales across the board:

```
# change to your home directory, which may be this:
cd /var/azuracast/www 

docker-compose exec --user="azuracast" web azuracast_cli locale:import
cd frontend
docker-compose build
docker-compose run --rm frontend npm run import-locales
docker-compose run --rm frontend npm run build
```

**Comment by susl16c** [comment]
After executing the command: docker-compose run --rm frontend npm run build

> azuracast@ build /data/frontend
> gulp

[11:42:23] Using gulpfile /data/frontend/gulpfile.js
[11:42:23] Starting 'default'...
[11:42:23] Starting 'clean'...
[11:42:23] 'clean' errored after 68 ms
[11:42:23] Error: EACCES: permission denied, unlink '/data/web/static/dist/app-e71c721caa.js'
[11:42:23] 'default' errored after 71 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! azuracast@ build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the azuracast@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-01-16T11_42_23_153Z-debug.log

**Comment by SlvrEagle23** [comment]
@susl16c I can't reproduce this error locally. All of our development processes are working without any error on my local installation.

There is something wrong in how you've set up AzuraCast locally for development, and you are going to have to be resourceful and try to resolve the problem yourself.

I'm sorry but I can't help you further on this subject. This isn't a deliberate effort on our part to make things difficult for you, but there is a limit to how much support we can provide with limited information and resources.
