### ISSUE TITLE
Liquidsoap not starting

### ISSUE THREAD

**Issue by sheiyla** [AzuraCast/AzuraCast#2139]
Error 6: Cannot apply that parameter because the function at line 126, char 10-16
has no argument labeled "rms_window"!
At line 126, char 86-90:
Error 6: Cannot apply that parameter because the function at line 126, char 10-16
has no argument labeled "rms_window"!
At line 126, char 86-90:
Error 6: Cannot apply that parameter because the function at line 126, char 10-16
has no argument labeled "rms_window"!
At line 126, char 86-90:
Error 6: Cannot apply that parameter because the function at line 126, char 10-16
has no argument labeled "rms_window"!
At line 126, char 86-90:
Error 6: Cannot apply that parameter because the function at line 126, char 10-16
has no argument labeled "rms_window"!
At line 126, char 86-90:
Error 6: Cannot apply that parameter because the function at line 126, char 10-16
has no argument labeled "rms_window"!
At line 126, char 86-90:
Error 6: Cannot apply that parameter because the function at line 126, char 10-16
has no argument labeled "rms_window"!
At line 126, char 86-90:
Error 6: Cannot apply that parameter because the function at line 126, char 10-16
has no argument labeled "rms_window"!

**Comment by rmacari** [comment]
Same here:

Liquidsoap encountered an error
At line 168, char 125-128:
Error 6: Cannot apply that parameter because the function at line 168, char 8-17
has no argument labeled "rms_window"!
At line 168, char 125-128:
Error 6: Cannot apply that parameter because the function at line 168, char 8-17
has no argument labeled "rms_window"!

**Comment by SlvrEagle23** [comment]
@rmacari @sheiyla Our configuration doesn't write `rms_window` anywhere in the Liquidsoap configuration.

Using the log viewer utility, please look at what is generating line 168. It's possible that you're using custom Liquidsoap code that contains that line, and that was made incompatible by our recent update to Liquidsoap 1.4.0.

**Comment by rmacari** [comment]
@sheiyla You are probably using a code in the Advanced configuration (Auto DJ), like the one i´m using: 

# Normalization and Compression for FM audio
radio = sky(radio)
radio = compress(radio, attack = 4.0, gain = 7.0, knee = 10.0, ratio = 5.0, release = 100.0, threshold = -18.0, **rms_window** = 0.7)
radio = normalize(radio, target = -1.0, threshold = -65.0)
radio = limit(radio, threshold = -0.2, attack = 2.0, release = 25.0, **rms_window** = 0.02)

If that is right, you will have to remove the code to get the Auto DJ working again or like me don´t update to the latest version to keep this code working to have sound quality for your radio as i want for my.  You could join me asking @SlvrEagle23 to give us the option to keep using the Liquidsoap version that works for us. :)

**Comment by eranwo** [comment]
Hi @sheiyla @rmacari ,
"**rms_window**" parameter has been changed in Liquidsoap 1.4.0 to "**window**". It should work fine.

**Comment by rmacari** [comment]
@sheiyla Thanks! I´ll give it a try. :)

**Comment by Xara** [comment]
Here is a regression in liquidsoap, smart fader don't work anymore, is an old bug,.

**Comment by SlvrEagle23** [comment]
@Xara Our latest update also updates the syntax of our generated code to make proper use of the new syntax in Liquidsoap 1.4.0. As long as you update your full installation, it should fix the issue.
