### ISSUE TITLE
Update User via API failed: The identifier id is missing for a query of App\\Entity\\Role

### ISSUE THREAD

**Issue by ilhamrizqi** [AzuraCast/AzuraCast#2140]
Hello,

I am developing WHMCS Module for Azuracast. I found that Update User API function always return error: **The identifier id is missing for a query of App\\Entity\\Role**

This is the input data

```
{
  "id": 13,
  "email": "ilhamrizqi@gmail.com",
  "auth_password": "12345678",
  "name": "Ilham Rizqi Sasmita",
  "locale": "en_US",
  "theme": "dark",
  "two_factor_secret": "A1B2C3D4",
  "created_at": 1573704205,
  "updated_at": 1573704205,
  "roles": [
    null
  ]
}
```

CURL request

`curl -X PUT "https://apl-audio.com/api/admin/user/13" -H "accept: application/json" -H "X-API-Key: b1045446fae17e16:413165444cb9435982e43823e6063100" -H "Content-Type: application/json" -d "{\"id\":13,\"email\":\"ilhamrizqi@gmail.com\",\"auth_password\":\"12345678\",\"name\":\"Ilham Rizqi Sasmita\",\"locale\":\"en_US\",\"theme\":\"dark\",\"two_factor_secret\":\"A1B2C3D4\",\"created_at\":1573704205,\"updated_at\":1573704205,\"roles\":[null]}"`

Here's the response

```
{
  "code": 0,
  "message": "The identifier id is missing for a query of App\\Entity\\Role",
  "formatted_message": "The identifier id is missing for a query of App\\Entity\\Role",
  "extra_data": [],
  "success": false
}
```

**Using Docker installation method**
No

**Host Operating System**
Linux (I don't have access to client's server)

**To Reproduce**
1. Go to http://hostname/api
2. Click on PUT /admin/user/
3. Scroll down to send request json

**Expected behavior**
Return success

**Screenshots**
![Screenshot from 2019-11-14 17-35-36](https://user-images.githubusercontent.com/624618/68850417-9210e380-0706-11ea-88f9-c4422efa6a51.png)
![Screenshot from 2019-11-14 17-36-20](https://user-images.githubusercontent.com/624618/68850423-95a46a80-0706-11ea-96fa-163fc396e6d7.png)
![Screenshot from 2019-11-14 17-37-23](https://user-images.githubusercontent.com/624618/68850434-9c32e200-0706-11ea-9c28-b81c0ebb9557.png)

Any details i am missing?

**Comment by SlvrEagle23** [comment]
@ilhamrizqi You shouldn't be passing:

```json
"roles": [
    null
  ]
```

You should pass either `"roles": null` or an array of IDs (i.e. `"roles": [1, 2]`), not an array containing null itself.

**Comment by ilhamrizqi** [comment]
I have changed the request json, the API response is "Changes saved successfully." But, the admin (frontend) said "Login unsuccessful Your credentials could not be verified." Please take a look at the screenshots.

![Screenshot from 2019-11-16 11-36-03](https://user-images.githubusercontent.com/624618/68988194-30678b00-0866-11ea-8c80-3811b2e9b531.png)
![Screenshot from 2019-11-16 11-36-26](https://user-images.githubusercontent.com/624618/68988195-3493a880-0866-11ea-8d43-19f720103a91.png)
![Screenshot from 2019-11-16 11-36-39](https://user-images.githubusercontent.com/624618/68988197-38bfc600-0866-11ea-851c-980548da7c31.png)
![Screenshot from 2019-11-16 11-40-05](https://user-images.githubusercontent.com/624618/68988200-3cebe380-0866-11ea-9681-64aa870d67da.png)

**Comment by SlvrEagle23** [comment]
@ilhamrizqi I will take a look to see what's causing that.

Just out of curiosity, you're building a WHMCS AzuraCast module, right?

I've received no less than about 15 or 20 e-mails asking me for such a thing...are you planning on releasing this anywhere?

**Comment by SlvrEagle23** [comment]
@ilhamrizqi The correct parameter to send when setting a new password is `new_password`, not `auth_password`. I realize our documentation states the latter, and this is an error that I'll work on correcting, but if you send `new_password`, that will properly set and store it.

**Comment by ilhamrizqi** [comment]
> @ilhamrizqi The correct parameter to send when setting a new password is `new_password`, not `auth_password`. I realize our documentation states the latter, and this is an error that I'll work on correcting, but if you send `new_password`, that will properly set and store it.

Thank you, the `new_password` parameter works for changing password.

Btw, i found new issue when creating new user.

I was using this json as request parameter

```
{
  "email": "ilhamrizqi@gmail.com",
  "auth_password": "12345678",
  "name": "Ilham Rizqi Sasmita",
  "locale": "en_US",
  "theme": "dark",
  "two_factor_secret": "",
  "roles": [13]
}
```

The response was successful

```
{
  "id": 15,
  "email": "ilhamrizqi@gmail.com",
  "name": "Ilham Rizqi Sasmita",
  "locale": "en_US",
  "theme": "dark",
  "two_factor_secret": "",
  "created_at": 1574755246,
  "updated_at": 1574755246,
  "roles": [],
  "api_keys": [],
  "links": {
    "self": "https://apl-audio.com/api/admin/user/15"
  }
}
```

But when i use the username and password to login to, the server said "Login Unsuccessful. Your credentials could not be verified"

Here's the screenshots

![Screenshot from 2019-11-26 15-01-10](https://user-images.githubusercontent.com/624618/69610551-9b7f4180-105e-11ea-80d8-6ec189024e02.png)
![Screenshot from 2019-11-26 15-01-28](https://user-images.githubusercontent.com/624618/69610559-9e7a3200-105e-11ea-9688-5d857a632cf5.png)
![Screenshot from 2019-11-26 15-01-46](https://user-images.githubusercontent.com/624618/69610566-a0dc8c00-105e-11ea-8acf-f7cdc93e6e4c.png)
![Screenshot from 2019-11-26 15-02-51](https://user-images.githubusercontent.com/624618/69610571-a33ee600-105e-11ea-9503-c6508800ca31.png)
![Screenshot from 2019-11-26 15-03-07](https://user-images.githubusercontent.com/624618/69610579-a89c3080-105e-11ea-9adc-e7292754ecc8.png)
![Screenshot from 2019-11-26 15-03-23](https://user-images.githubusercontent.com/624618/69610585-ab972100-105e-11ea-9b37-c7913317f201.png)
