### ISSUE TITLE
Liquid Soap Log Errors

### ISSUE THREAD

**Issue by themadcap1976** [AzuraCast/AzuraCast#2142]
seeing this error on the liquidsoap logs, over and over.
2019/11/15 08:41:00 [lang.deprecated:2] WARNING: "quote" is deprecated! Please use "string.quote".
2019/11/15 08:41:00 [lang:3] AzuraCast Raw Response: 
2019/11/15 08:41:00 [lang:3] AzuraCast Error: Delaying subsequent requests...

**Comment by SlvrEagle23** [comment]
@themadcap1976 This should be fixed now. Thank you for the report!
