### ISSUE TITLE
Song interrupts in the middle

### ISSUE THREAD

**Issue by PINKfm** [AzuraCast/AzuraCast#2144]
Hello y'all

I have a small problem since a few days. I have a newsservice running, which is uploading the Newsfile on the server. One Playlist is scheduled, that everytime at minute 55 this file has to be played. But in the middle of the played file the stream is going into the next song. But I want - of course - the full file to be played.

Do you have a idea about it? I would give you screenshots, but I have the german translation on it..

**Comment by SlvrEagle23** [comment]
@PINKfm Unfortunately, with "interrupt other songs", the rule is that the playlist in question will start playing exactly at the start of the minute, and then stop playing exactly at the end of the minute.

Granted, as a result of that it's not particularly useful for things that are longer than a minute, but this a limitation of the upstream AutoDJ software we use, and currently we're not aware of any other way to work around it.

**Comment by PINKfm** [comment]
Thanks for the quick response!

Well the option "interrupt other songs is not activated", I just changed my default language into "english", that you can see what I mean.

In the meanwhile I _think_ I found the issue: It had the playlist weight of 2, the rotation which I have used had the weight of 10. I will response if this was the thing what interrupt the newsfile (the newsfile is about 3 minutes long).

![image](https://user-images.githubusercontent.com/57815496/69010679-3d69a480-0962-11ea-82d2-2246a3fb1855.png)
![image](https://user-images.githubusercontent.com/57815496/69010681-48243980-0962-11ea-876b-87d68d2b16c9.png)
![image](https://user-images.githubusercontent.com/57815496/69010684-52dece80-0962-11ea-8fbc-1cee485b7614.png)

**Comment by PINKfm** [comment]
Issue was solved. It seems that sometimes the file was broken from our distributor - my fault. Im Sorry for any inconvinience!

**Comment by AmsterdamFM** [comment]
We have exactly the same issue. We want to play a +/- 2-3 minute news item exactly at the top of the hour. But after one minute it stops.  Log shows:

`2019/12/30 15:01:00 [amsterdamfm_interrupt_switch:3] Switch to amsterdamfm_autodj_fallback with transition.`

Is there any way or workaround to play a full news file exactly at the top of the hour followed by a commercial and a jingle?

**Comment by SlvrEagle23** [comment]
@AmsterdamFM Currently, you can't schedule a file to play exactly at the top of the hour without setting up the "Interrupt Other Tracks" function, which also will cut off the end of the file if it overruns the scheduled time.

We've asked about this kind of thing a few times with the Liquidsoap folks, and as far as we know there's no better way of handling this. Admittedly, despite years of working with it even I'm not really a Liquidsoap expert, and I don't get as much help from them as I'd like.
