### ISSUE TITLE
Errors when updating to newest version ; web server unreachable.

### ISSUE THREAD

**Issue by TogarUshindi** [AzuraCast/AzuraCast#2145]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu Server 18.04.3 LTS

**Describe the bug**
Updated Azuracast to latest version and web server no longer reachable. Errors occurred during the update.

**To Reproduce**

```
$ sudo ./docker.sh update-self
$ sudo ./docker.sh update
```

**Expected behavior**

**Relevant Logs**
```
Pulling mariadb (azuracast/azuracast_db:latest)...
latest: Pulling from azuracast/azuracast_db
Digest: sha256:999334c338fc7af15c15742b78d87b65b2742d91de0551d3ce82801724e6578e
Status: Image is up to date for azuracast/azuracast_db:latest
Pulling redis (azuracast/azuracast_redis:latest)...
latest: Pulling from azuracast/azuracast_redis
Digest: sha256:d784c6b697c515bd1d6fa6da385d9523400c97804b4babc4992696c8fcffb913
Status: Image is up to date for azuracast/azuracast_redis:latest
Pulling influxdb (azuracast/azuracast_influxdb:latest)...
latest: Pulling from azuracast/azuracast_influxdb
Digest: sha256:6a1cff6ef67d4f9c415c04692511d281569097c0510da3c3be7e3a814800b0a4
Status: Image is up to date for azuracast/azuracast_influxdb:latest
Pulling stations (azuracast/azuracast_radio:latest)...
latest: Pulling from azuracast/azuracast_radio
c64513b74145: Already exists
01b8b12bad90: Already exists
c5d85cf7a05f: Already exists
b6b268720157: Already exists
e12192999ff1: Already exists
d39ece66b667: Already exists
65599be66378: Already exists
0e4ef92b4a8b: Already exists
4dc4f0d92188: Already exists
db3db3cf316f: Already exists
276c5ecf4d55: Already exists
f2e814ef99ae: Already exists
fb70426541a2: Already exists
9884b5b3aef3: Pull complete
48d6f91a5917: Pull complete
b52b05df473d: Pull complete
52d20cf1ef30: Pull complete
3e0eb93c9fcd: Pull complete
Digest: sha256:00674db7d8ec3ab53e0df02fd290c286c021d14e47e416769152074a0cf50169
Status: Downloaded newer image for azuracast/azuracast_radio:latest
Pulling web (azuracast/azuracast_web_v2:latest)...
latest: Pulling from azuracast/azuracast_web_v2
Digest: sha256:39d7cb225a7565d8a5caa8bd69f78c3f2ba04ffe3e99c247dd8314f3a1accbfb
Status: Image is up to date for azuracast/azuracast_web_v2:latest
Stopping azuracast_web        ... done
Stopping azuracast_stations   ... done
Stopping azuracast_influxdb_1 ... done
Stopping azuracast_redis_1    ... done
Stopping azuracast_mariadb_1  ... done
Removing network azuracast_default
Error response from daemon: remove azuracast_www_data: volume is in use - [2cdc7d878a735b65b0662d56d686082e4468fd9659defd2c3fa03531d9e32d4c]
Error response from daemon: remove azuracast_tmp_data: volume is in use - [4190acdd6c2036fef17ed00b052dd1b5d8728b6aa6e28b01d466727d9f68f333, 2cdc7d878a735b65b0662d56d686082e4468fd9659defd2c3fa03531d9e32d4c]
Creating network "azuracast_default" with the default driver
Starting azuracast_mariadb_1 ... 
Starting azuracast_influxdb_1 ... 
Starting azuracast_influxdb_1 ... done
Starting azuracast_stations ... done
ERROR: Cannot start service web: all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: permission denied": unavailable
azuracast_redis_1 is up-to-date
azuracast_mariadb_1 is up-to-date
Recreating azuracast_stations ... 
azuracast_influxdb_1 is up-to-date
Recreating azuracast_stations ... error

ERROR: for azuracast_stations  sandbox 1aaf57541e71ce926fd14ec45f86006d04d37574865ed2aa53c6db054939a50d not found

ERROR: for stations  sandbox 1aaf57541e71ce926fd14ec45f86006d04d37574865ed2aa53c6db054939a50d not found
ERROR: Encountered errors while bringing up the project.
Update complete!
```

**Comment by TogarUshindi** [comment]
Something that's concerning me is that it seems my docker machines have all ... disappeared? Not sure what this means.

```
/var/azuracast$ ./docker.sh cli
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.

$ docker-machine start default
Docker machine "default" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

$ docker-machine ls
NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS

$
```

Did I lose all my stations and data? Or is this happening because docker can't start up after the update failure? I'm clueless and I'm afraid to even touch it until I have an understanding what went wrong.

**Comment by SlvrEagle23** [comment]
@TogarUshindi The Docker updater script just runs very routine Docker commands that pull down the newer images, turn off the existing ones and replace them with the updated ones.

This suggests that something went wrong with your Docker installation itself on your server. I don't know what would've caused that problem but this particular issue is not something I've ever seen before with Docker.

I'm classifying this error as "upstream" as it is a problem with Docker (which we don't maintain) and not with AzuraCast, and is very unlikely to have been caused by anything specific to AzuraCast's updater.

**Comment by TogarUshindi** [comment]
Right, but just to note, everything was working and streaming until I attempted the update. So that could only mean something got triggered by the act of updating.

**Comment by SlvrEagle23** [comment]
@TogarUshindi I understand, but if you look at [what the update command is doing](https://github.com/AzuraCast/AzuraCast/blob/master/docker.sh#L131-L169), it's really just executing simple command-line Docker commands that are extremely common for Docker installation users.

It's possible that the Docker engine ran out of hard drive space in the update process, or some other instability only popped up during the update.

**Comment by TogarUshindi** [comment]
Hrrrmmm...

So... if I were to attempt to back up the station (which I hope it will since Docker isn't working) and reinstall Docker (which I haven't changed any settings so I don't know why all this would be happening in the first place, and I still have plenty of HDD left), could I somehow recover and get my stations working again that way?

I mean I hate to say it, but since the Docker install is the only version supported, docker problems inherently become Azuracast's problems... I have no idea how Docker works, never used it directly, just installed Azuracast and let it run, and update whenever an update is posted. I have no idea how to begin troubleshooting. :(

**Comment by TogarUshindi** [comment]
I don't believe it. I think I actually (accidentally, with luck) figured this out.

Uh... can we change the update instructions to say `sudo ./docker.sh update`?

What happened was is I ran the update in user mode the first time without adding sudo, and it apparently got confused on what folder to put things in. I just happened to notice this when I saw a snap folder installed in the home directory.

Then, it had turned off the daemon, so I had to restart that manually, performed the update as root, and it worked.

**Comment by TogarUshindi** [comment]
Uh oh... all is not well yet. All my stations are not showing up on the dashboard now. All of the music content is gone. I need to find out where Azuracast puts all the media files to check to see if everything's there. If so, I'll try rebooting the server and see if it comes up working.

**Comment by TogarUshindi** [comment]
Couldn't find out where Azuracast was/is storing media files, but I tried searching for an mp3 file that I uploaded as a test, couldn't find it, so I'm assuming the place the media files are being stored is in a secret location that isn't accessible through `locate`, so I went and rebooted, and even more interesting is once the machine is rebooted, the dashboard is not reachable again, so I'm guessing the daemon did not restart during bootup, which is odd considering that I saw references to it in systemd.

**Comment by SlvrEagle23** [comment]
@TogarUshindi If you like, you can join us [in our Slack](https://azuracast.com/slack) to discuss this issue further. It's hard to know what to advise you to do next without having more information about your setup.

**Comment by TogarUshindi** [comment]
Cool, thanks :)

**Comment by TogarUshindi** [comment]
@SlvrEagle23 after our conversation on Slack, I have a high suspicion what caused all of this mess.

Do you remember [this thread](https://github.com/AzuraCast/AzuraCast/issues/1961)?

I never removed the `snap` version of Docker. It was lingering on my machine.

I discovered this when I was having trouble purging Docker to reinstall Azuracast. I ended up successfully ridding myself of the fouled docker installation(s) when I tried the `sudo snap remove docker` on [this thread](https://askubuntu.com/questions/935569/how-to-completely-uninstall-docker).

So...

I believe what triggered all this was when I ran `./docker.sh update-self` and `./docker.sh update` without `sudo`. I am willing to bet that without the `sudo`, my machine somehow referenced the `snap` version and attempted to update _**it**_ instead of the `curl` version that installed with Azuracast's `docker.sh` installation script. It fouled up Azuracast and docker's configuration, and inserted those weird volumes that had my username on it. Do you remember the lines you pointed out to me during our convo?

```
Deleted Volumes:
username_shoutcast2_install
azuracast_db_data
username_backups
username_letsencrypt
azuracast_redis_data
username_www_data
azuracast_influx_data
username_station_data
username_tmp_data
```

This is further supported by the way that the update script failed, and when:

```
Removing network azuracast_default
Error response from daemon: remove azuracast_www_data: volume is in use
```

"Volume in use..."

It couldn't remove the needed volumes because they were still running. Because my machine attempted to update using the wrong Docker installation.

I betcha. I betcha.

So... I know this is technically an upstream issue that has no baring on the development of Azuracast itself, but, could we put out a warning to those with `snap` installations of Docker to make sure they do NOT use the `snap` version, and to make sure that they uninstall it completely from their machine before installing Azuracast? Or else, they are putting themselves in a precarious situation...

**Comment by SlvrEagle23** [comment]
@TogarUshindi I don't think it merits a dedicated _warning_, especially since most users wouldn't understand what the snap version of Docker is in the first place, and it would honestly be more confusing than anything.

Instead, I just added a tip to the installer that instructs users to let AzuraCast's installer do the Docker and Docker Compose installation too, since it'll pull the latest version. It also has a minor note about the Snap version:

https://www.azuracast.com/install/#installing
