### ISSUE TITLE
Streams interrupting and now playing does not work

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#2146]
Hi

_docker, ubuntu_

Last 1-2 days streams are interrupting and metadatas are not coming on random radios at my instance.

Everything was fine 1-2 days ago. I did update just 1 hour ago and it did not fix it. My average CPU usage is 48 as azuracast admin panel displays but it was maximum 5-10 before as I remember. 

Looks like something weird corrupts my CPU and probably that's why my stations are interrupting. you may check this station as how it's interrupting and displays station offline even some tracks are playing: https://my.radiolize.com/public/radio_antalya

Check this please:
https://pasteboard.co/IGXDR3N.png

Everything was fine before 1-2 days as I said and suddenly this happen.

there are hundreds of this log at liquidsoap logs:

> decoder:3] Unable to decode "/var/azuracast/stations/radio_antalya/media/media:/TUESDAY MIX / SALI 12:00 - 14:00" as {audio=1+;video=0;midi=0}!
> 2019/11/16 17:12:38 [clock.wallclock_main:2] We must catchup 15.95 seconds!
> 2019/11/16 17:12:39 [clock.wallclock_main:2] We must catchup 16.40 seconds!
> 2019/11/16 17:12:40 [decoder:3] Unable to decode "/var/azuracast/stations/radio_antalya/media/media:/TUESDAY MIX / SALI 12:00 - 14:00" as {audio=1+;video=0;midi=0}!
> 2019/11/16 17:12:40 [decoder:3] Unable to decode "/var/azuracast/stations/radio_antalya/media/media:/TUESDAY MIX / SALI 12:00 - 14:00" as {audio=1+;video=0;midi=0}!
> 2019/11/16 17:12:40 [decoder:3] Unable to decode "/var/azuracast/stations/radio_antalya/media/media:/TUESDAY MIX / SALI 12:00 - 14:00" as {audio=1+;video=0;midi=0}!
> 2019/11/16 17:12:40 [decoder:3] Unable to decode "/var/azuracast/stations/radio_antalya/media/media:/TUESDAY MIX / SALI 12:00 - 14:00" as {audio=1+;video=0;midi=0}!
> 2019/11/16 17:12:40 [clock.wallclock_main:2] We must catchup 17.42 seconds!
> 2019/11/16 17:12:42 [clock.wallclock_main:2] We must catchup 18.35 seconds!
> 2019/11/16 17:12:42 [decoder:3] Unable to decode "/var/azuracast/stations/radio_antalya/media/media:/TUESDAY MIX / SALI 12:00 - 14:00" as {audio=1+;video=0;midi=0}!
> 2019/11/16 17:12:42 [decoder:3] Unable to decode "/var/azuracast/stations/radio_antalya/media/media:/TUESDAY MIX / SALI 12:00 - 14:00" as {audio=1+;video=0;midi=0}!
> 2019/11/16 17:12:42 [decoder:3] Unable to decode "/var/azuracast/stations/radio_antalya/media/media:/TUESDAY MIX / SALI 12:00 - 14:00" as {audio=1+;video=0;midi=0}!
> 2019/11/16 17:12:42 [decoder:3] Unable to decode "/var/azuracast/stations/radio_antalya/media/media:/TUESDAY MIX / SALI 12:00 - 14:00" as {audio=1+;video=0;midi=0}!
> 2019/11/16 17:12:43 [clock.wallclock_main:2] We must catchup 18.91 seconds!
> 2019/11/16 17:12:44 [clock.wallclock_main:2] We must catchup 19.71 seconds!

**Comment by radiolize** [comment]
here are htop command screenshots: 

https://pasteboard.co/IH1MiZc.png
https://pasteboard.co/IH1MZPH.png

**Comment by YosefAdPro** [comment]
+1
