### ISSUE TITLE
Liquidsoap wont run after update

### ISSUE THREAD

**Issue by adwinter** [AzuraCast/AzuraCast#2148]
Ran the update.sh script, and now liquidsoap fails to start:
it shows this:
Liquidsoap encountered an error
2019/11/17 14:24:07 [threads:3] Thread "generic queue #2" terminated.
2019/11/17 14:24:07 [threads:3] Thread "non-blocking queue #1" terminated.
2019/11/17 14:24:07 [threads:3] Queues shut down
2019/11/17 14:24:07 [server:3] Closing socket.
2019/11/17 14:24:07 [main:3] Cleaning downloaded files...
2019/11/17 14:24:07 [main:3] Freeing memory...

Can I force a recompile of liquidsoap or something?

**Comment by SlvrEagle23** [comment]
@adwinter Are you on an Ansible install? You can run `./update.sh --full` to force a rebuild of Liquidsoap if so.

If you're on Docker, the build comes from our image and is known to be stable.

**Comment by adwinter** [comment]
@SlvrEagle23 I'm on Ansible and that did the trick... Liquidsoap appears to be recompiling but its taking a long time at the OPAM step... I'll just leave it alone to see if it finally works... been 10+ mins already though.... Might just take this as a sign and upgrade to the docker version. :)

**Comment by adwinter** [comment]
Ok so it was successful. It recompiled liquidsoap and I was back in business. Not sure what happened the first time.. but ./update.sh --full fixed it.

On another note I think I'm going to upgrade to the docker version. I think j read someplace that you guys were moving away from ansible support anyway. 

Anyway, thanks for helping. Issue closed.
