### ISSUE TITLE
SSL Error 404 - The page you requested was not found.

### ISSUE THREAD

**Issue by JMultimidia** [AzuraCast/AzuraCast#2150]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**

The player displays the information of the song you are playing but has no audio. In the chrome console I noticed the following message:

GET https://stream.jmhost.com.br/radio/8042/radio?1574106445 404

**NOTE**
I even turned off the firewall to test it.

**Comment by SlvrEagle23** [comment]
@JMultimidia The system shouldn't be automatically putting any station on port 8042. It's a nonstandard port (the standard ports for stations served by AzuraCast end in -0, i.e. 8040), which is also how our proxy rules are configured. They won't forward the ports between those, because those are reserved for internal purposes (i.e. inbound DJ connection, the Liquidsoap telnet connection, etc).

**Comment by JMultimidia** [comment]
I'm migrating radios from another server using azuracast in non-docker mode and it would be interesting if I could use the same ports I used before so I didn't have to change the settings on my clients' players and apps. For example I used ports 8042, 8044 and for auto dj I manually and respectively configured ports 9043 and 9044, 9045 and 9046.

**Comment by ogrenci01** [comment]
Hİ @JMultimidia ;

I use a configuration similar to yours but I use ansible installation. I have to use it.

I configured the port numbers for my stations. Read the following document for Docker. A valid SSL certificate will resolve your issue. It will be help to you.

https://www.azuracast.com/help/faq_docker.html#expand-the-docker-radio-station-port-rang

**Comment by KoneSV** [comment]
Using Docker installation method
NO

Host Operating System
Ubuntu 16.04

I have problem with port 8022 and SSL, 404 error in Radio (Streaming) and Public Page

Radio (Streaming): https://server1.watahosting.com/radio/8022/radio.mp3
Public Page: 404 Not found.
The requested resource could not be found. Please verify the URI and try again.

Any solution? Ansible Installation
