### ISSUE TITLE
I Expanded ports and after install SSL the stations don't work

### ISSUE THREAD

**Issue by cristianocarrozzi** [AzuraCast/AzuraCast#2151]
**Using Docker installation method**

Yes

**Host Operating System**

Ubuntu 18.04.3 LTS

**Describe the bug**

I expanded my instalation of Azura to 100 stations. I followed the instructions, created a new file docker-compose.override.yml and edit azuracast.env to 
AUTO_ASSIGN_PORT_MAX=8999. The stations did work well but when I created a SSL key with Letsencrypt I have no sound in stations in ports between 8500:8999. Streaming returns 404 error. I'm using proxy and CloudFlare.
Have another configuration to do?

**Comment by SlvrEagle23** [comment]
Closed as port range has been expanded on the `web` container to 8000-8999, the full 8000 port range.
