### ISSUE TITLE
API directory in Docker Install

### ISSUE THREAD

**Issue by adwinter** [AzuraCast/AzuraCast#2152]
Hey Guys,

Not sure if this is a bug, or just me doing something stupid, but I installed a fresh new version of Azuracast on a Docker installation. Figured I'd better get with the times and use what is preferred around here. Only one thing seemed to go off the rails... When I go to my /api path it opens SwaggerUI just fine, but then give me a whole bunch of errors that it couldn't load files. The first of the series I've attached here. 

What's strange here is that I can use the api just fine.. I can call the api using my own endpoints and get responses back, but the test environment I used to have when I went to <my instance>/api doesn't seem to work anymore.

What do you think this is?
I'm not really worried about it -- as the end result still works, but it would be nice to test my API calls like I used to is all.

Thanks as always for all of your help.
Talk Soon.

![2019-11-19_12-53-18](https://user-images.githubusercontent.com/20404986/69185591-e5e74800-0acb-11ea-8579-b8ff3e053e68.png)

**Comment by SlvrEagle23** [comment]
@adwinter If you directly visit `/api/openapi.yml` do you get a 404 or is there some other error?

**Comment by adwinter** [comment]
When I put in /api/openapi.php I get the following error:


500
The "/var/azuracast/www/util/openapi.php" directory does not exist.
Finder.php : 601

**Comment by SlvrEagle23** [comment]
@adwinter Not `.php`, `.yml`

**Comment by adwinter** [comment]
I typed in the .yml in the address bar and it gave me the same exact error.

**Comment by Viducius** [comment]
Experiencing the same error, I'm currently running on a DigitalOcean droplet so everything was pre-installed.
