### ISSUE TITLE
No audio on public page player

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2153]
**Using Docker installation method**
 Yes

**Host Operating System**
18.04

**Describe the bug:**

**No audio sound** on "public page" player and also in the main page - "station overview" - since the latest version (**v0.9.7.1, #85808f3 (2019-11-16 22:56)** ).

Checked on desktop computer with Chrome latest version .
On mobile Android+Chrome it's playing well.

**Comment by CodeSteele** [comment]
I'm currently on v0.9.7.1, #85808f3 (2019-11-16 22:56) on my instance and don't have this issue on neither page, can we have a link to the instance?

**Comment by eranwo** [comment]
Are you in "proxy mode" ?
The stream url playing well on chrome, the issue is only while playing via the web player.
Chrome console not indicate on any problem
![image](https://user-images.githubusercontent.com/2701228/69245987-8c0c7e00-0bb0-11ea-90e0-f00f8d83cfcb.png)

**Comment by CodeSteele** [comment]
@eranwo the web proxy? Yep.

I'd definitely have to take a look at the actual radio station to confirm it isn't some weird issue with your browser -- have you tried other browsers on your desktop?

**Comment by eranwo** [comment]
@CodeSteele It seems that it was a specific computer bug.
Thank you for trying to help!
