### ISSUE TITLE
Mount Point and WebDJ

### ISSUE THREAD

**Issue by stevenaj** [AzuraCast/AzuraCast#2155]
**Using Docker installation method**

Yes
Latest version v0.9.7.1, #85808f3 (2019-11-16 22:56)
**Host Operating System**

Debian 10
**Describe the bug**

When the mount point is changed from PORT:/ to PORT:/mountname then WebDJ no longer works.  Looks like it needs to use the default "/" blank mountpoint
**To Reproduce**

Change the mount point in Station WebDJ tab from default to a mount name i.e. stream

**Expected behavior**

Would have expected WebDJ to use the mount mount as setup.  Other encoders can use the new mount point name.  The reason we noticed this as we had one encoder in the workflow that would not use a blank mount point so we changed it.  The encoder worked fine but WebDJ no longer did.  When restoring to the default mount point then WebDJ worked fine again.

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@stevenaj I assume you're referring to when changing the streaming/incoming HTTP mount point name on Liquidsoap, right? Changing the outbound mount point(s) or adding new ones shouldn't affect the WebDJ, but changing the incoming one definitely could. I'll see if there's any way we can work around that.

**Comment by stevenaj** [comment]
Yes in deed thanks - it is the inbound to Liquidsoap that if changed stops WebDJ from working.
Nothing wrong with the outbound - all perfect.
Awesome product though!

Andy

**Comment by SlvrEagle23** [comment]
@stevenaj The latest update should make the WebDJ handle modified DJ harbor mount point names better. Give it about 10 minutes and update your installation and let me know if it helps.

**Comment by stevenaj** [comment]
Thanks so much. Will try and advise.

**Comment by stevenaj** [comment]
I have the latest update - changed the moutpoint to /studio-a - checked WebDJ but at the moment it appears not to update the autoDJ.  If I stream from another encoder to the new inbound mount point then it correctly interrupts the audodj

I tried in new browser private session to make sure of any cache issues but still can not get WebDJ to work when the inbound mount has been changed.

I will try different syntax in case it does not like the “-“ in “studio-a”

Andy

**Comment by Vaalyn** [comment]
Closing this issue since there have been no further reports regarding this problem for a long time.

If this is still happening please create a new issue and link to this one here.
