### ISSUE TITLE
Music Not Processed

### ISSUE THREAD

**Issue by ItsJamieHosie** [AzuraCast/AzuraCast#2156]
Hey,

I Uploaded My Songs Via FTP And Noticed Some Of The Songs Were Showing "Not Processed" I Let Digital Ocean Set The Server Via The One Click Setup. But Just Wondering How I Could Get The Files To Process ?
![Annotation 2019-11-21 014014](https://user-images.githubusercontent.com/54157291/69293143-eed93600-0bff-11ea-9a93-cb44bd043274.png)

**Comment by SlvrEagle23** [comment]
@ItsJamieHosie If you visit the System Administration page and manually run the "5-minute sync" task, do you get any errors?

It's possible the system thinks the files in question are corrupt or otherwise can't process them.

**Comment by ItsJamieHosie** [comment]
just checked the now this is what i get when running the task
![Screenshot_2019-11-21 Sync Task Output - AzuraCast](https://user-images.githubusercontent.com/54157291/69302961-2ef5e400-0c13-11ea-9c97-10b828ac784d.png)

**Comment by SlvrEagle23** [comment]
@ItsJamieHosie So this suggests that it's successfully queueing the file for processing...from that same System Administration page, go to the Log Viewer, then look at the application log (the top item) and see if it's reporting any errors around the same time as that processing step (you can manually trigger it again if you want).

**Comment by ItsJamieHosie** [comment]
All Is Good Now When You Said About The System Thinking File Is Corrupt I Downloaded A Couple Of Songs Again And Uploaded And Now Everything Is Working Great, Cheers For The Help :)

**Comment by SlvrEagle23** [comment]
@ItsJamieHosie Good to hear!
