### ISSUE TITLE
Liquidsoap: There are currently 400 RIDs, possible request leak! 

### ISSUE THREAD

**Issue by themadcap1976** [AzuraCast/AzuraCast#2157]
AzuraCast • v0.9.8, #440687e (2019-11-26 3:25) • Docker • PHP 7.2

Seeing this message in Liquidsoap log over and over:
2019/11/20 21:36:10 [request:2] There are currently 400 RIDs, possible request leak! Please check that you don't have a loop on empty/unavailable requests, or creating requests without destroying them. Decreasing request.grace_time can also help.
2019/11/20 21:36:12 [lang:3] AzuraCast Raw Response: 
2019/11/20 21:36:12 [lang:3] AzuraCast Error: Delaying subsequent requests...

**Comment by SlvrEagle23** [comment]
@themadcap1976 That's very strange. Did you recently switch "Manual AutoDJ mode" on or off? If so, you should restart your station (via Utilities > Restart Broadcasting) to make the changes take effect.

**Comment by themadcap1976** [comment]
I don't recall changing that setting, I was fiddling with the playlists however. I no longer see the leak erros I'm just seeing after restart:
 2019/11/20 21:36:12 [lang:3] AzuraCast Raw Response:
2019/11/20 21:36:12 [lang:3] AzuraCast Error: Delaying subsequent requests..

I'll restart tonight when listeners are low and see if it clears.

**Comment by themadcap1976** [comment]
after reboot.. I see this in the Liquidsoap Error log over and over:
2019/11/20 21:36:12 [lang:3] AzuraCast Raw Response:
2019/11/20 21:36:12 [lang:3] AzuraCast Error: Delaying subsequent requests..

**Comment by themadcap1976** [comment]
I'm not sure if this issue is related to #2160 ?

**Comment by SlvrEagle23** [comment]
@themadcap1976 From the system-wide Administration panel, check the AzuraCast application log, and see if it's returning any errors when AutoDJ tries to find the next song. That would cause issues like that.

**Comment by themadcap1976** [comment]
I'm seeing this in the logs.
[2019-12-02T03:53:47.590432+00:00] AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... [] {"station":{"id":1,"name":"Yacht Rock Miami"}}
[2019-12-02T03:53:47.596882+00:00] AzuraCast.ERROR: No playable tracks were found. [] {"station":{"id":1,"name":"Yacht Rock Miami"}}
[2019-12-02T03:53:49.648793+00:00] AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... [] {"station":{"id":1,"name":"Yacht Rock Miami"}}
[2019-12-02T03:53:49.657194+00:00] AzuraCast.ERROR: No playable tracks were found. [] {"station":{"id":1,"name":"Yacht Rock Miami"}}
[2019-12-02T03:53:51.707524+00:00] AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... [] {"station":{"id":1,"name":"Yacht Rock Miami"}}
[2019-12-02T03:53:51.713687+00:00] AzuraCast.ERROR: No playable tracks were found. [] {"station":{"id":1,"name":"Yacht Rock Miami"}}

**Comment by themadcap1976** [comment]
Liquidsoap Log: 
2019/12/01 22:54:32 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/12/01 22:54:35 [lang:3] AzuraCast Raw Response: 
2019/12/01 22:54:35 [lang:3] AzuraCast Error: Delaying subsequent requests...

**Comment by SlvrEagle23** [comment]
@themadcap1976 If you're constantly getting "no playable tracks" errors, you should check your playlist configuration to make sure it doesn't have times when there are no playlists that could actually play in that given time slot.

Even if it only has a "filler" song in it, you should always have a default playlist that can play at all times, so that the system won't throw errors like this, which will pile up and cause problems for both Liquidsoap and the AzuraCast next-song processor.

**Comment by themadcap1976** [comment]
I wish I would've have taken note of this, I was seeing an error of some directory making a call connecting to an Icecast mount point on the server. I was switched from Southcast to Icecast and the logs are clean once more. Still having scheduling issues with the playlists, but that's a different issue. I will close this.
