### ISSUE TITLE
Top of the hour jingle issue

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#2158]
**Using Docker installation method**
yes
**Host Operating System**
Ubunti 18.04
**Describe the bug**
With the new scheduling engine, I cannot find the way to correctly set a 'top of the hour jingle'.
My jingle announces the time.
In the past, I would create playlist for each hour, and set a "play only once", with a schedule between H:00 to H:05 so that, when the end of the previous song is reachedn the ToH jingle is played once. Today, with the recent changes, it would play the jingle for 5 minutes, even tough "play only once" is selected. What would be a good way of programming this ?

Thanks

**Comment by rmacari** [comment]
Same issue here, everything that should play ONLY ONCE doesn´t work anymore.

**Comment by biguenique** [comment]
Anyone had any progress on this?

**Comment by rmacari** [comment]
@biguenique It seems fixed by the last update.
