### ISSUE TITLE
Next artist not showing up anymore.

### ISSUE THREAD

**Issue by themadcap1976** [AzuraCast/AzuraCast#2160]
In the past, I would see the upcoming artist on the "on the air" screen. No longer is this happening.

![Screen Shot 2019-11-21 at 8 13 59 AM](https://user-images.githubusercontent.com/32073620/69341205-1ac3de00-0c37-11ea-8cd8-7ee5836b3f69.png)

**Comment by themadcap1976** [comment]
I don't have this enabled.
![Screen Shot 2019-11-21 at 8 25 40 AM](https://user-images.githubusercontent.com/32073620/69341977-92ded380-0c38-11ea-9794-877ed337cf70.png)

**Comment by CodeSteele** [comment]
![image](https://user-images.githubusercontent.com/31152835/69343602-ebfc3680-0c3b-11ea-822d-21dc8cce61c4.png)
Hmm, my instance is fine, will have to dig further.

**Comment by CodeSteele** [comment]
@themadcap1976 can you confirm you're on the latest version? I do know "playing next" was unavailable for a period, off the top of my head I can't nail down when though.

**Comment by themadcap1976** [comment]
I should've added my version, I apologize. 
v0.9.7.1, #e15ed0d (2019-11-21 2:06) • Docker • PHP 7.2

**Comment by themadcap1976** [comment]
I applied the latest updates, rebooted the host and I still have this issue.

**Comment by themadcap1976** [comment]
Examining the Liquidsoap logs, it loads up the next song there. 
2019/11/22 09:07:46 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/11/22 09:07:48 [lang:3] AzuraCast Raw Response: 
2019/11/22 09:07:48 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/11/22 09:07:50 [lang:3] AzuraCast Raw Response: annotate:title="Goin' Downtown",artist="Chris Latul",duration="343.",song_id="cae7f845034805a8af22c5bcd9908e5e",media_id="618",playlist_id="13":/var/azuracast/stations/yacht_rock_miami/media/Songs/chris_latul_-_goin__downtown.mp3
2019/11/22 09:07:50 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/yacht_rock_miami/media/Songs/chris_latul_-_goin__downtown.mp3".
2019/11/22 09:09:39 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/yacht_rock_miami/media/Songs/boz_scaggs_-_look_what_you_ve_done_to_me.mp3".
2019/11/22 09:09:50 [playlist_1lb_anchor:3] Prepared "/var/azuracast/stations/yacht_rock_miami/media/Songs/boz_scaggs_-_look_what_you_ve_done_to_me.mp3" (RID 926).
2019/11/22 09:09:50 [yacht_rock_miami_next_song:3] Prepared "/var/azuracast/stations/yacht_rock_miami/media/Songs/chris_latul_-_goin__downtown.mp3" (RID 1497).

**Comment by themadcap1976** [comment]
I'm closing this at it seems to have resolved "itself"
