### ISSUE TITLE
I need help with azuracast ip

### ISSUE THREAD

**Issue by monomusika** [AzuraCast/AzuraCast#2161]
hello finally install azuracast and docker on a computer that I will use as a server.  but I find some inconveniences that I detail and share in images.  At the end of the installation I get the following IP to manage the radio station: 83.56.128.99.  I try to open that ip and it gives me an error.  searching and searching I found how to access with the following IP: 192.168.1.65 which is a public IP.  (outside the home network I cannot access the azuracast panel with that IP).  At the time of configuring the radio, it gives me as IP to broadcast: 192.168.1.84 but obviously with that IP I could not broadcast to the world.  Does anyone know how I can change the IP of the azuracast panel to manage from outside the home network?  Does anyone know how to change the IP for my private IP to broadcast to everyone?  (Ports open: 8000 to 8005 / 80/22)

![Screenshot_2019-11-21-01-48-05-000_com miui videoplayer](https://user-images.githubusercontent.com/58057788/69394013-b0f91200-0cd2-11ea-837a-f73a103ce647.png)
![IMG_20191120_174614](https://user-images.githubusercontent.com/58057788/69394047-c706d280-0cd2-11ea-86d6-3c05803085a2.jpg)

**Comment by ogrenci01** [comment]
Hi @monomusika ;

This is definitely not recommended. It is not wise to do so. To do this, you must purchase a VPS or VDS.

Your IP is not a static IP. You should have got a static IP for internet connection. You should discuss this with your Internet service provider. After you have got a Static IP, you must open ports on your modem device. This is simplest logic and this is similar to have a mini data center.

**Comment by monomusika** [comment]
> Hi @monomusika ;
> 
> This is definitely not recommended. It is not wise to do so. To do this, you must purchase a VPS or VDS.
> 
> Your IP is not a static IP. You should have got a static IP for internet connection. You should discuss this with your Internet service provider. After you have got a Static IP, you must open ports on your modem device. This is simplest logic and this is similar to have a mini data center.

ok that is azuracast is designed only to be installed on servers in the cloud and not in a domestic environment (Old computer hear Raspberry pi) as if for example "Libretime"?  Suppose you can have a static IP, would it be possible?

**Comment by ogrenci01** [comment]
> ok that is azuracast is designed only to be installed on servers in the cloud and not in a domestic environment (Old computer hear Raspberry pi) as if for example "Libretime"? Suppose you can have a static IP, would it be possible?

It is possible but not safe. This is definitely not recommended. AzuraCast supports Raspberry PI.

**Comment by SlvrEagle23** [comment]
@monomusika The other comments here are correct, AzuraCast is meant to be installed on a dedicated server or VPS (virtual private server) that is hosted in a datacenter and has its own static IP address.

The only scenario where we use local connections is during development of the software, but we don't recommend using that setup to actually serve your station to the web, especially because many ISPs restrict incoming traffic (particularly on ports 80/443, the HTTP ports that we use by default).
