### ISSUE TITLE
500 error when trying to enable 2FA

### ISSUE THREAD

**Issue by EramsorGR** [AzuraCast/AzuraCast#2162]
**Using Docker installation method** 
Yes

**Host Operating System** 
Ubuntu 18.04

**Describe the bug** 
Getting a 500 error when trying to enable 2FA

**To Reproduce**
1. Go to My Account.
2. Enable 2FA
3. Click on Verify Authentication 
4. You will get a 500 error page.

**Expected behavior**
You should be able to save the 2FA details. 

**Relevant Logs**
[2019-11-22T12:46:29.759149+00:00] AzuraCast.ERROR: Field name "secret" not found. {"file":"/var/azuracast/www/vendor/azuracast/azuraforms/src/AbstractForm.php","line":71,"code":0} []

**Screenshots**
https://xyz.ends-in.xyz/e/Crimson_Northernfurseal-4031.png

**Device(s):**
 - Device:  Desktop
 - OS: Windows 10
 - Browser:  Brave
 - Version: 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)

**Additional context**
None

**Comment by EramsorGR** [comment]
Forgot to mention, running on v0.9.7.1

**Comment by SlvrEagle23** [comment]
@EramsorGR This was fixed as of a recent update. Could you update your installation to the latest version?

**Comment by EramsorGR** [comment]
> @EramsorGR This was fixed as of a recent update. Could you update your installation to the latest version?
Which version exactly?

**Comment by EramsorGR** [comment]
Updated to v0.9.7.1, #c7edc13 (2019-11-22 23:20). 2FA works now.
