### ISSUE TITLE
Help me pls! ShoutCast does not work

### ISSUE THREAD

**Issue by nickloud** [AzuraCast/AzuraCast#2163]
The server has ShoutCast latest version installed. I can’t connect to it. I opened the admin panel in the browser and saw that the ip address was not registered in the config. It shows where this file is located, but it doesn’t exist in this way.

**Comment by SlvrEagle23** [comment]
@nickloud Which version of SHOUTcast do you have installed? We have some known issues with the new "Freemium" version of SHOUTcast (2.6.x).

**Comment by nickloud** [comment]
SHOUTcast "Shoutcast DNAS/posix(linux x64) v2.6.0.753 (Apr 25 2019)

**Comment by nickloud** [comment]
I tried installing ShoutCast, which I installed in a previous docker. This does not work either. But then he worked
