### ISSUE TITLE
Restoring MariabDB backup fails after 60 secs

### ISSUE THREAD

**Issue by sherifkozman** [AzuraCast/AzuraCast#2166]
Hello, 

Upon trying to restore a fairly not large backup from one AzuraCast Server to the other. Restore ususally fails during the DB restore process as it exceeds 60 seconds.

It would generate an error for process.php upon reaching the 60 seconds limit then completes the restore process without importing the rest of data.

**Comment by SlvrEagle23** [comment]
@sherifkozman I've increased the timer in the latest version of the codebase; in about 10 minutes after this post it should have propagated out to the Packagist repository, so it will be available to update to.
