### ISSUE TITLE
Error appears when deleting a music file

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#2167]
Installation type: ubuntu, docker.

Hello.

I have installed AzuraCast on a new VPS. When deleting a song from music files, the song is successfully deleting but there is an error appearing on the right top that says "The request could not be processed." even the song is deleted. I could not find any logs.

**Comment by rmacari** [comment]
Same error here, the error message shows up when dealing with Music Files: setting file on a playlist, Moving Files and Deleting Files.

**Comment by SlvrEagle23** [comment]
@radiolize @rmacari To help us diagnose this issue, can you open your browser's inspector panel (using the F12 key usually), then switch to the "Network" tab, then make the same web request again. You should see a request that comes back and is highlighted in red; select that line and click "Response", and then paste that here.

**Comment by rmacari** [comment]
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). preload.js:169:52
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). onloadwff.js:71:803563
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). preload.js:169:52
Source map error: Error: request failed with status 404
Resource URL: http://studio.radiolivre95.com/static/dist/lib/bootstrap/bootstrap-a454220fc0.bundle.min.js
Source Map URL: bootstrap.bundle.min.js.map

Source map error: Error: request failed with status 404
Resource URL: http://studio.radiolivre95.com/static/dist/lib/bootstrap-vue/bootstrap-vue-1eded317c5.min.js
Source Map URL: bootstrap-vue.min.js.map

Source map error: Error: request failed with status 404
Resource URL: http://studio.radiolivre95.com/static/dist/lib/bootstrap-vue/bootstrap-vue-d02588705d.min.css
Source Map URL: bootstrap-vue.min.css.map

Error while fetching an original source: request failed with status 404
Source URL: <unknown>
