### ISSUE TITLE
installation of azurcast along with with a hosting panel.

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#217]
Hello,

How can i install azuracast on a server with vestacp or centos-webpanel installed already?
Make it possible to use azuracast another port rather then 80

**Comment by SlvrEagle23** [comment]
@surihost It's probably not a very wise idea to do that, unless you're running AzuraCast inside Docker containers. The software that AzuraCast installs is very, very likely to overlap with any control panel (particularly PHP, Apache/nginx, and MySQL). Moreover, the control panel versions are likely to be quite a bit older than the AzuraCast versions, which may cause major problems with Azura's operation.

**Comment by susl16c** [comment]
I installed everything in the docker on the hosting panel, everything works, but would like to configure nginx on the hosting and install the database too, is this possible?

**Comment by SlvrEagle23** [comment]
@susl16c This question is not related to the original ticket, and the original ticket has already been closed. Please create a new ticket for this issue.

**Comment by susl16c** [comment]
Maybe someone will need my help, I want to write that I delete everything with the isp manager panel and configure the proxy and the ssl process was not a legacy of course.

**Comment by pitsch** [comment]
cockpit is written and c,, relies on systemd data and is already part of ubuntu installs, its websocket answers on port 9090 and it would need an extra nginx rule,
