### ISSUE TITLE
Error Connecting to FTP Server On Private Networks

### ISSUE THREAD

**Issue by CodeSteele** [AzuraCast/AzuraCast#2170]
```
Response:	227 Entering Passive Mode (68,169,171,223,117,57)
Command:	MLSD
Error:	The data connection could not be established: ECONNREFUSED - Connection refused by server
```

117+57 = 30009, which is within our port range, so whats up?

**Comment by CodeSteele** [comment]
Oh that external IP is wrong in relation to what I'm connecting to (a local IP) hmm...

**Comment by CodeSteele** [comment]
This is because AzuraCast is "discovering" the public IP, and doing that poorly.

Hmm...

**Comment by CodeSteele** [comment]
Setting `ForcePassiveIP` in `/etc/pure-ftpd.conf` fixes it, but this is kind of a short-term solution, hmm...

**Comment by CodeSteele** [comment]
WinSCP supports forcing the passive IP address, fixing this issue. Filezilla does _not_. Maybe we should recommend not using Filezilla....

**Comment by CodeSteele** [comment]
@SlvrEagle23 pointed out Filezilla does but that setting didn't work for me 😠 I'll investigate further as I work on the docs.

**Comment by SlvrEagle23** [comment]
I've added a new environment variable, `FTP_PASV_IP`, that if set in `azuracast.env` will override our automatic discovery of an external IP address and use the one provided instead for PASV connections.

As @CodeSteele mentions, some clients are aware of the difficulty that FTP servers have when sending back PASV IPs and will "correct" for it automatically, so this shouldn't be necessary except in the case that you're both using a NATted IP address _and_ your FTP client isn't correcting for it itself.
