### ISSUE TITLE
 liquidsoap doesn't start if there are non-English playlist names (for example, Hebrew)

### ISSUE THREAD

**Issue by YosefAdPro** [AzuraCast/AzuraCast#2173]
**Using Docker installation method**

NO
**Host Operating System**

Ubuntu 18.04
**Describe the bug**

After upgrading to version 0.9.8 liquidsoap doesn't start if there are non-English playlist names (for example, Hebrew)

**Relevant Logs**

Liquidsoap encountered an error
Line 24, char 0:
Warning 4: Unused variable playlist_
No output defined, nothing to do.

**Screenshots**

![image](https://user-images.githubusercontent.com/11810187/69504736-14cb4700-0f2e-11ea-8bb6-25bdde13286b.png)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@YosefAdPro I've switched how we do station/playlist short name calculations to use the more UTF-8 friendly sanitization process that we use for our filename sanitization, which should also work without any issues for Liquidsoap variable names.

**Comment by YosefAdPro** [comment]
@SlvrEagle23 Indeed the problem was solved.
Thanks
