### ISSUE TITLE
default radio public page not work : NotSupportedError: 

### ISSUE THREAD

**Issue by EBII** [AzuraCast/AzuraCast#2176]
Hello it is about default public page for each radio in azuracast. 
click on play produce error in javascript console.. 

NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable.

url in nowplaying is a malformed Url 
this is this url from  nowplaying saw in https://xxx.com/api/nowplaying/Y
https://xxx.com:8000/radio.mp3?1574772542

this is the flux url is working good from admin radio page
https://xxx.com/radio/8000/radio.mp3?1574772625

I use nginx proxy so no need :8000 

**Using Docker installation method**

Traditionnal install 
**Host Operating System**

Ubuntu 18.04
**Describe the bug**

defautl page can not play music
**To Reproduce**

create radio 
got to public page 
open javascript console 
click on play 
NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable.

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

Regards for you work ..

**Comment by SlvrEagle23** [comment]
@EBII This is likely because you're behind a service like CloudFlare, so you should turn on the "Enable Web Proxy" setting in your system-wide settings. This will force the entire system to use the proxied `/radio/8000` URLs, which should connect properly despite any issues.
