### ISSUE TITLE
don't let me install shoutcast

### ISSUE THREAD

**Issue by Radiopop** [AzuraCast/AzuraCast#2177]
don't let me install shoutcast

<img width="988" alt="Captura de pantalla 2019-11-27 a las 12 35 50" src="https://user-images.githubusercontent.com/47224463/69721407-14d96b80-1115-11ea-95e4-8d03f7ae5c33.png">

**Comment by SlvrEagle23** [comment]
@Radiopop The error message suggests that file is an invalid format. Make sure you're uploading a proper .tar.gz file; if you continue to get errors with the official version supplied by SHOUTcast, feel free to upload an example here and we can take a look at it.
