### ISSUE TITLE
Update error on my azuracast on unbutu

### ISSUE THREAD

**Issue by rolradio** [AzuraCast/AzuraCast#218]
Hi,
i have done an update for the latetst version of azuracst.

But u have this error.
also when i do the full update.
Hope you can help.
Thanks

TASK [azuracast-update : Update Database] ******************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php migrations:migrate --no-interaction --allow-no-migration", "delta": "0:00:00.484780", "end": "2017-08-24 00:30:56.735787", "failed": true, "rc": 1, "start": "2017-08-24 00:30:56.251007", "stderr": "\n                                                                               \n  [Doctrine\\DBAL\\Exception\\DriverException]                                    \n  An exception occurred while executing 'ALTER TABLE listener CHANGE listener  \n  _user_agent listener_user_agent VARCHAR(191) NOT NULL':                      \n  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'listener_user_age  \n  nt' at row 1697                                                              \n                                                                               \n\n                                                                               \n  [Doctrine\\DBAL\\Driver\\PDOException]                                          \n  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'listener_user_age  \n  nt' at row 1697                                                              \n                                                                               \n\n                                                                               \n  [PDOException]                                                               \n  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'listener_user_age  \n  nt' at row 1697                                                              \n                                                                               \n\nmigrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--] [<version>]", "stderr_lines": ["", "                                                                               ", "  [Doctrine\\DBAL\\Exception\\DriverException]                                    ", "  An exception occurred while executing 'ALTER TABLE listener CHANGE listener  ", "  _user_agent listener_user_agent VARCHAR(191) NOT NULL':                      ", "  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'listener_user_age  ", "  nt' at row 1697                                                              ", "                                                                               ", "", "                                                                               ", "  [Doctrine\\DBAL\\Driver\\PDOException]                                          ", "  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'listener_user_age  ", "  nt' at row 1697                                                              ", "                                                                               ", "", "                                                                               ", "  [PDOException]                                                               ", "  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'listener_user_age  ", "  nt' at row 1697                                                              ", "                                                                               ", "", "migrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--] [<version>]"], "stdout": "Loading configuration from the integration code of your framework (setter).\n                                                                    \n                    Doctrine Database Migrations                    \n                                                                    \n\nMigrating up to 20170803050109 from 20170719045113\n\n  ++ migrating 20170803050109\n\n     -> ALTER TABLE listener CHANGE listener_user_agent listener_user_agent VARCHAR(191) NOT NULL\nMigration 20170803050109 failed during Execution. Error An exception occurred while executing 'ALTER TABLE listener CHANGE listener_user_agent listener_user_agent VARCHAR(191) NOT NULL':\n\nSQLSTATE[01000]: Warning: 1265 Data truncated for column 'listener_user_agent' at row 1697", "stdout_lines": ["Loading configuration from the integration code of your framework (setter).", "                                                                    ", "                    Doctrine Database Migrations                    ", "                                                                    ", "", "Migrating up to 20170803050109 from 20170719045113", "", "  ++ migrating 20170803050109", "", "     -> ALTER TABLE listener CHANGE listener_user_agent listener_user_agent VARCHAR(191) NOT NULL", "Migration 20170803050109 failed during Execution. Error An exception occurred while executing 'ALTER TABLE listener CHANGE listener_user_agent listener_user_agent VARCHAR(191) NOT NULL':", "", "SQLSTATE[01000]: Warning: 1265 Data truncated for column 'listener_user_agent' at row 1697"]}

RUNNING HANDLER [azuracast-cron : restart cron] ************************************************************************************************************************
        to retry, use: --limit @/var/azuracast/www/util/ansible/update.retry

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=70   changed=15   unreachable=0    failed=1_

**Comment by SlvrEagle23** [comment]
@rolradio The latest update should fix this issue. Most tables don't have trouble with their strings being somewhere in the 191-255 character length range, but it's very likely that the Listeners User Agent field could be that long.

I added a step to truncate that field prior to the conversion, that should fix things.

**Comment by rolradio** [comment]
@SlvrEagle23 I have this error now:

TASK [azuracast-update : Update Database] **********************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php migrations:migrate --no-interaction --allow-no-migration", "delta": "0:00:58.875029", "end": "2017-08-24 09:57:53.773233", "failed": true, "rc": 1, "start": "2017-08-24 09:56:54.898204", "stderr": "\n                                                                               \n  [Doctrine\\DBAL\\Exception\\DriverException]                                    \n  An exception occurred while executing 'ALTER TABLE `station_media` ADD CONS  \n  TRAINT FK_32AADE3AA0BDB2F3 FOREIGN KEY (song_id) REFERENCES songs (id) ON D  \n  ELETE SET NULL':                                                             \n  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away              \n                                                                               \n\n                                                                   \n  [Doctrine\\DBAL\\Driver\\PDOException]                              \n  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away  \n                                                                   \n\n                                                                   \n  [PDOException]                                                   \n  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away  \n                                                                   \n\nmigrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--] [<version>]", "stderr_lines": ["", "                                                                               ", "  [Doctrine\\DBAL\\Exception\\DriverException]                                    ", "  An exception occurred while executing 'ALTER TABLE `station_media` ADD CONS  ", "  TRAINT FK_32AADE3AA0BDB2F3 FOREIGN KEY (song_id) REFERENCES songs (id) ON D  ", "  ELETE SET NULL':                                                             ", "  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away              ", "                                                                               ", "", "                                                                   ", "  [Doctrine\\DBAL\\Driver\\PDOException]                              ", "  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away  ", "                                                                   ", "", "                                                                   ", "  [PDOException]                                                   ", "  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away  ", "                                                                   ", "", "migrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--] [<version>]"], "stdout": "Loading configuration from the integration code of your framework (setter).\n                                                                    \n                    Doctrine Database Migrations                    \n                                                                    \n\nMigrating up to 20170823204230 from 20170719045113\n\n  ++ migrating 20170803050109\n\n     -> UPDATE listener SET listener_user_agent=SUBSTRING(listener_user_agent, 1, 190)\n     -> ALTER TABLE listener CHANGE listener_user_agent listener_user_agent VARCHAR(191) NOT NULL\n     -> ALTER TABLE station CHANGE url url VARCHAR(191) DEFAULT NULL, CHANGE radio_media_dir radio_media_dir VARCHAR(191) DEFAULT NULL, CHANGE radio_base_dir radio_base_dir VARCHAR(191) DEFAULT NULL\n     -> ALTER TABLE station_media CHANGE path path VARCHAR(191) DEFAULT NULL\n     -> ALTER TABLE station_mounts CHANGE relay_url relay_url VARCHAR(191) DEFAULT NULL, CHANGE authhash authhash VARCHAR(191) DEFAULT NULL\n     -> ALTER TABLE users CHANGE auth_password auth_password VARCHAR(191) DEFAULT NULL\n     -> ALTER TABLE app_migrations CHANGE version version VARCHAR(191) NOT NULL\n     -> ALTER DATABASE `azuracast` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci\n     -> ALTER TABLE `song_history` DROP FOREIGN KEY FK_2AD16164A0BDB2F3\n     -> ALTER TABLE `station_media` DROP FOREIGN KEY FK_32AADE3AA0BDB2F3\n     -> ALTER TABLE `analytics` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n     -> ALTER TABLE `api_keys` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n     -> ALTER TABLE `app_migrations` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n     -> ALTER TABLE `listener` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n     -> ALTER TABLE `role` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n     -> ALTER TABLE `role_permissions` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n     -> ALTER TABLE `settings` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n     -> ALTER TABLE `song_history` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n     -> ALTER TABLE `songs` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n     -> ALTER TABLE `station` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n     -> ALTER TABLE `station_media` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n     -> ALTER TABLE `station_mounts` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n     -> ALTER TABLE `station_playlist_has_media` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n     -> ALTER TABLE `station_playlists` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n     -> ALTER TABLE `station_requests` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n     -> ALTER TABLE `station_streamers` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n     -> ALTER TABLE `user_has_role` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n     -> ALTER TABLE `users` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci\n     -> ALTER TABLE `song_history` ADD CONSTRAINT FK_2AD16164A0BDB2F3 FOREIGN KEY (song_id) REFERENCES songs (id) ON DELETE CASCADE\n     -> ALTER TABLE `station_media` ADD CONSTRAINT FK_32AADE3AA0BDB2F3 FOREIGN KEY (song_id) REFERENCES songs (id) ON DELETE SET NULL\nMigration 20170803050109 failed during Execution. Error An exception occurred while executing 'ALTER TABLE `station_media` ADD CONSTRAINT FK_32AADE3AA0BDB2F3 FOREIGN KEY (song_id) REFERENCES songs (id) ON DELETE SET NULL':\n\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away", "stdout_lines": ["Loading configuration from the integration code of your framework (setter).", "                                                                    ", "                    Doctrine Database Migrations                    ", "                                                                    ", "", "Migrating up to 20170823204230 from 20170719045113", "", "  ++ migrating 20170803050109", "", "     -> UPDATE listener SET listener_user_agent=SUBSTRING(listener_user_agent, 1, 190)", "     -> ALTER TABLE listener CHANGE listener_user_agent listener_user_agent VARCHAR(191) NOT NULL", "     -> ALTER TABLE station CHANGE url url VARCHAR(191) DEFAULT NULL, CHANGE radio_media_dir radio_media_dir VARCHAR(191) DEFAULT NULL, CHANGE radio_base_dir radio_base_dir VARCHAR(191) DEFAULT NULL", "     -> ALTER TABLE station_media CHANGE path path VARCHAR(191) DEFAULT NULL", "     -> ALTER TABLE station_mounts CHANGE relay_url relay_url VARCHAR(191) DEFAULT NULL, CHANGE authhash authhash VARCHAR(191) DEFAULT NULL", "     -> ALTER TABLE users CHANGE auth_password auth_password VARCHAR(191) DEFAULT NULL", "     -> ALTER TABLE app_migrations CHANGE version version VARCHAR(191) NOT NULL", "     -> ALTER DATABASE `azuracast` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci", "     -> ALTER TABLE `song_history` DROP FOREIGN KEY FK_2AD16164A0BDB2F3", "     -> ALTER TABLE `station_media` DROP FOREIGN KEY FK_32AADE3AA0BDB2F3", "     -> ALTER TABLE `analytics` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", "     -> ALTER TABLE `api_keys` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", "     -> ALTER TABLE `app_migrations` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", "     -> ALTER TABLE `listener` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", "     -> ALTER TABLE `role` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", "     -> ALTER TABLE `role_permissions` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", "     -> ALTER TABLE `settings` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", "     -> ALTER TABLE `song_history` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", "     -> ALTER TABLE `songs` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", "     -> ALTER TABLE `station` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", "     -> ALTER TABLE `station_media` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", "     -> ALTER TABLE `station_mounts` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", "     -> ALTER TABLE `station_playlist_has_media` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", "     -> ALTER TABLE `station_playlists` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", "     -> ALTER TABLE `station_requests` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", "     -> ALTER TABLE `station_streamers` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", "     -> ALTER TABLE `user_has_role` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", "     -> ALTER TABLE `users` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", "     -> ALTER TABLE `song_history` ADD CONSTRAINT FK_2AD16164A0BDB2F3 FOREIGN KEY (song_id) REFERENCES songs (id) ON DELETE CASCADE", "     -> ALTER TABLE `station_media` ADD CONSTRAINT FK_32AADE3AA0BDB2F3 FOREIGN KEY (song_id) REFERENCES songs (id) ON DELETE SET NULL", "Migration 20170803050109 failed during Execution. Error An exception occurred while executing 'ALTER TABLE `station_media` ADD CONSTRAINT FK_32AADE3AA0BDB2F3 FOREIGN KEY (song_id) REFERENCES songs (id) ON DELETE SET NULL':", "", "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away"]}

RUNNING HANDLER [azuracast-cron : restart cron] ****************************************************
        to retry, use: --limit @/var/azuracast/www/util/ansible/update.retry

PLAY RECAP *****************************************************************************************
localhost                  : ok=70   changed=16   unreachable=0    failed=1

**Comment by SlvrEagle23** [comment]
@rolradio That usually means the query timed out...does the exact same thing happen if you run the update script again?

**Comment by rolradio** [comment]
@SlvrEagle23 
I have done the update now 3 times again.

This error keeps comming back:

TASK [azuracast-update : Update Database] **********************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php migrations:migrate --no-interaction --allow-no-migration", "delta": "0:00:01.754659", "end": "2017-08-24 16:17:49.544743", "failed": true, "rc": 1, "start": "2017-08-24 16:17:47.790084", "stderr": "\n                                                                               \n  [Doctrine\\DBAL\\Exception\\DriverException]                                    \n  An exception occurred while executing 'ALTER TABLE `song_history` DROP FORE  \n  IGN KEY FK_2AD16164A0BDB2F3':                                                \n  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN   \n  KEY `FK_2AD16164A0BDB2F3`; check that it exists                              \n                                                                               \n\n                                                                               \n  [Doctrine\\DBAL\\Driver\\PDOException]                                          \n  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN   \n  KEY `FK_2AD16164A0BDB2F3`; check that it exists                              \n                                                                               \n\n                                                                               \n  [PDOException]                                                               \n  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN   \n  KEY `FK_2AD16164A0BDB2F3`; check that it exists                              \n                                                                               \n\nmigrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--] [<version>]", "stderr_lines": ["", "                                                                               ", "  [Doctrine\\DBAL\\Exception\\DriverException]                                    ", "  An exception occurred while executing 'ALTER TABLE `song_history` DROP FORE  ", "  IGN KEY FK_2AD16164A0BDB2F3':                                                ", "  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN   ", "  KEY `FK_2AD16164A0BDB2F3`; check that it exists                              ", "                                                                               ", "", "                                                                               ", "  [Doctrine\\DBAL\\Driver\\PDOException]                                          ", "  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN   ", "  KEY `FK_2AD16164A0BDB2F3`; check that it exists                              ", "                                                                               ", "", "                                                                               ", "  [PDOException]                                                               ", "  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN   ", "  KEY `FK_2AD16164A0BDB2F3`; check that it exists                              ", "                                                                               ", "", "migrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--] [<version>]"], "stdout": "Loading configuration from the integration code of your framework (setter).\n                                                                    \n                    Doctrine Database Migrations                    \n                                                                    \n\nMigrating up to 20170823204230 from 20170719045113\n\n  ++ migrating 20170803050109\n\n     -> UPDATE listener SET listener_user_agent=SUBSTRING(listener_user_agent, 1, 190)\n     -> ALTER TABLE listener CHANGE listener_user_agent listener_user_agent VARCHAR(191) NOT NULL\n     -> ALTER TABLE station CHANGE url url VARCHAR(191) DEFAULT NULL, CHANGE radio_media_dir radio_media_dir VARCHAR(191) DEFAULT NULL, CHANGE radio_base_dir radio_base_dir VARCHAR(191) DEFAULT NULL\n     -> ALTER TABLE station_media CHANGE path path VARCHAR(191) DEFAULT NULL\n     -> ALTER TABLE station_mounts CHANGE relay_url relay_url VARCHAR(191) DEFAULT NULL, CHANGE authhash authhash VARCHAR(191) DEFAULT NULL\n     -> ALTER TABLE users CHANGE auth_password auth_password VARCHAR(191) DEFAULT NULL\n     -> ALTER TABLE app_migrations CHANGE version version VARCHAR(191) NOT NULL\n     -> ALTER DATABASE `azuracast` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci\n     -> ALTER TABLE `song_history` DROP FOREIGN KEY FK_2AD16164A0BDB2F3\nMigration 20170803050109 failed during Execution. Error An exception occurred while executing 'ALTER TABLE `song_history` DROP FOREIGN KEY FK_2AD16164A0BDB2F3':\n\nSQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_2AD16164A0BDB2F3`; check that it exists", "stdout_lines": ["Loading configuration from the integration code of your framework (setter).", "                                                                    ", "                    Doctrine Database Migrations                    ", "                                                                    ", "", "Migrating up to 20170823204230 from 20170719045113", "", "  ++ migrating 20170803050109", "", "     -> UPDATE listener SET listener_user_agent=SUBSTRING(listener_user_agent, 1, 190)", "     -> ALTER TABLE listener CHANGE listener_user_agent listener_user_agent VARCHAR(191) NOT NULL", "     -> ALTER TABLE station CHANGE url url VARCHAR(191) DEFAULT NULL, CHANGE radio_media_dir radio_media_dir VARCHAR(191) DEFAULT NULL, CHANGE radio_base_dir radio_base_dir VARCHAR(191) DEFAULT NULL", "     -> ALTER TABLE station_media CHANGE path path VARCHAR(191) DEFAULT NULL", "     -> ALTER TABLE station_mounts CHANGE relay_url relay_url VARCHAR(191) DEFAULT NULL, CHANGE authhash authhash VARCHAR(191) DEFAULT NULL", "     -> ALTER TABLE users CHANGE auth_password auth_password VARCHAR(191) DEFAULT NULL", "     -> ALTER TABLE app_migrations CHANGE version version VARCHAR(191) NOT NULL", "     -> ALTER DATABASE `azuracast` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci", "     -> ALTER TABLE `song_history` DROP FOREIGN KEY FK_2AD16164A0BDB2F3", "Migration 20170803050109 failed during Execution. Error An exception occurred while executing 'ALTER TABLE `song_history` DROP FOREIGN KEY FK_2AD16164A0BDB2F3':", "", "SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_2AD16164A0BDB2F3`; check that it exists"]}

RUNNING HANDLER [azuracast-cron : restart cron] ****************************************************
        to retry, use: --limit @/var/azuracast/www/util/ansible/update.retry

PLAY RECAP *****************************************************************************************
localhost                  : ok=70   changed=15   unreachable=0    failed=1

**Comment by SlvrEagle23** [comment]
@rolradio I reverted the change to the code, try executing this manually before you update the database:

```
php /var/azuracast/www/util/cli.php orm:run-dql "UPDATE Entity\Listener l SET l.listener_user_agent=SUBSTRING(l.listener_user_agent, 1, 190)"
```

**Comment by rolradio** [comment]
I have executing the code manual.
Unfortunately, this error persists

TASK [azuracast-update : Update Database] **********************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php migrations:migrate --no-interaction --allow-no-migration", "delta": "0:00:00.846312", "end": "2017-08-24 23:21:36.022653", "failed": true, "rc": 1, "start": "2017-08-24 23:21:35.176341", "stderr": "\n                                                                               \n  [Doctrine\\DBAL\\Exception\\DriverException]                                    \n  An exception occurred while executing 'ALTER TABLE `song_history` DROP FORE  \n  IGN KEY FK_2AD16164A0BDB2F3':                                                \n  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN   \n  KEY `FK_2AD16164A0BDB2F3`; check that it exists                              \n                                                                               \n\n                                                                               \n  [Doctrine\\DBAL\\Driver\\PDOException]                                          \n  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN   \n  KEY `FK_2AD16164A0BDB2F3`; check that it exists                              \n                                                                               \n\n                                                                               \n  [PDOException]                                                               \n  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN   \n  KEY `FK_2AD16164A0BDB2F3`; check that it exists                              \n                                                                               \n\nmigrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--] [<version>]", "stderr_lines": ["", "                                                                               ", "  [Doctrine\\DBAL\\Exception\\DriverException]                                    ", "  An exception occurred while executing 'ALTER TABLE `song_history` DROP FORE  ", "  IGN KEY FK_2AD16164A0BDB2F3':                                                ", "  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN   ", "  KEY `FK_2AD16164A0BDB2F3`; check that it exists                              ", "                                                                               ", "", "                                                                               ", "  [Doctrine\\DBAL\\Driver\\PDOException]                                          ", "  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN   ", "  KEY `FK_2AD16164A0BDB2F3`; check that it exists                              ", "                                                                               ", "", "                                                                               ", "  [PDOException]                                                               ", "  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN   ", "  KEY `FK_2AD16164A0BDB2F3`; check that it exists                              ", "                                                                               ", "", "migrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--] [<version>]"], "stdout": "Loading configuration from the integration code of your framework (setter).\n                                                                    \n                    Doctrine Database Migrations                    \n                                                                    \n\nMigrating up to 20170823204230 from 20170719045113\n\n  ++ migrating 20170803050109\n\n     -> ALTER TABLE listener CHANGE listener_user_agent listener_user_agent VARCHAR(191) NOT NULL\n     -> ALTER TABLE station CHANGE url url VARCHAR(191) DEFAULT NULL, CHANGE radio_media_dir radio_media_dir VARCHAR(191) DEFAULT NULL, CHANGE radio_base_dir radio_base_dir VARCHAR(191) DEFAULT NULL\n     -> ALTER TABLE station_media CHANGE path path VARCHAR(191) DEFAULT NULL\n     -> ALTER TABLE station_mounts CHANGE relay_url relay_url VARCHAR(191) DEFAULT NULL, CHANGE authhash authhash VARCHAR(191) DEFAULT NULL\n     -> ALTER TABLE users CHANGE auth_password auth_password VARCHAR(191) DEFAULT NULL\n     -> ALTER TABLE app_migrations CHANGE version version VARCHAR(191) NOT NULL\n     -> ALTER DATABASE `azuracast` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci\n     -> ALTER TABLE `song_history` DROP FOREIGN KEY FK_2AD16164A0BDB2F3\nMigration 20170803050109 failed during Execution. Error An exception occurred while executing 'ALTER TABLE `song_history` DROP FOREIGN KEY FK_2AD16164A0BDB2F3':\n\nSQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_2AD16164A0BDB2F3`; check that it exists", "stdout_lines": ["Loading configuration from the integration code of your framework (setter).", "                                                                    ", "                    Doctrine Database Migrations                    ", "                                                                    ", "", "Migrating up to 20170823204230 from 20170719045113", "", "  ++ migrating 20170803050109", "", "     -> ALTER TABLE listener CHANGE listener_user_agent listener_user_agent VARCHAR(191) NOT NULL", "     -> ALTER TABLE station CHANGE url url VARCHAR(191) DEFAULT NULL, CHANGE radio_media_dir radio_media_dir VARCHAR(191) DEFAULT NULL, CHANGE radio_base_dir radio_base_dir VARCHAR(191) DEFAULT NULL", "     -> ALTER TABLE station_media CHANGE path path VARCHAR(191) DEFAULT NULL", "     -> ALTER TABLE station_mounts CHANGE relay_url relay_url VARCHAR(191) DEFAULT NULL, CHANGE authhash authhash VARCHAR(191) DEFAULT NULL", "     -> ALTER TABLE users CHANGE auth_password auth_password VARCHAR(191) DEFAULT NULL", "     -> ALTER TABLE app_migrations CHANGE version version VARCHAR(191) NOT NULL", "     -> ALTER DATABASE `azuracast` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci", "     -> ALTER TABLE `song_history` DROP FOREIGN KEY FK_2AD16164A0BDB2F3", "Migration 20170803050109 failed during Execution. Error An exception occurred while executing 'ALTER TABLE `song_history` DROP FOREIGN KEY FK_2AD16164A0BDB2F3':", "", "SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_2AD16164A0BDB2F3`; check that it exists"]}

RUNNING HANDLER [azuracast-cron : restart cron] ****************************************************
        to retry, use: --limit @/var/azuracast/www/util/ansible/update.retry

PLAY RECAP *****************************************************************************************
localhost                  : ok=70   changed=15   unreachable=0    failed=1

**Comment by SlvrEagle23** [comment]
@rolradio It appears that the update has you stuck somewhere in mid-migration. Normally, this shouldn't happen as the migrations are transactional (so if one portion fails, the whole process rolls back), but it seems this isn't always the case.

I can get your database updated and back to a fully working state if you're willing to send me the credentials needed to access the server via SSH. I can be reached at buster@busterneece.com.

Note that there may be some delay in getting back to you, as here in Texas we're dealing with the remnants of Hurricane Harvey, and that may result in disruptions and power outages.

**Comment by SlvrEagle23** [comment]
Issue resolved via manual drop and rebuild of the database; MariaDB's internal record of the database had fallen out of alignment with the database itself, so a dump of existing data, drop and rebuild, and reimport of data was the easiest solution. No data lost in the process.
