### ISSUE TITLE
Error "add scheduled item" button (Solved)

### ISSUE THREAD

**Issue by webma5ter23** [AzuraCast/AzuraCast#2181]
Installation: Docker latest version
Browser: Chrome and Firefox

The button is inactive and cannot be clicked

![Imagen 2](https://user-images.githubusercontent.com/41419364/69895966-276fc280-1318-11ea-8888-6996e3a16b9e.png)

**Comment by webma5ter23** [comment]
This option is very important for me, I appreciate you helping me

**Comment by webma5ter23** [comment]
Fix a CSS error that causes the button error

**Comment by SlvrEagle23** [comment]
@webma5ter23 Are you telling us to do that, or are you telling us that you did that?

If so, what is the CSS error that caused the problem? Was it custom CSS? If so, we can close this issue.
