### ISSUE TITLE
liquidsoap error after latest update

### ISSUE THREAD

**Issue by alutus** [AzuraCast/AzuraCast#2183]
Howdy,
after the last update the radio no longer starts, I mention that I did not modify any file, I only executed the command
`./docker.sh update
The docker-compose.yml file has changed since your version. Overwrite? This will overwrite any customizations you made to this file? [Y/n] y`

after entering the administration area it is seen that AutoDJ Service Not Running
Liquidsoap has not started
`×Liquidsoap encountered an error
At line 29, char 26:
Error 3: Syntax error!
At line 29, char 26:
Error 3: Syntax error!
At line 29, char 26:
Error 3: Syntax error!`

**Comment by yarik2720** [comment]
for me it shows:
`At line 44, char 29:
Error 3: Syntax error!`
and in liquidsoap.liq file it is line:
```
playlist_semi-low_autoassign = playlist(id="playlist_semi-low_autoassign",mode="randomize",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/noise_fm/playlists/playlist_semi-low_autoassign.m3u")
```

**Comment by alutus** [comment]
I'm sorry but I don't know how to fix this problem, can someone guide me with steps to repair it?

**Comment by yarik2720** [comment]
Rename your playlist if it have hyphen on its name or some other symbols. Make name simple

**Comment by alutus** [comment]
> Rename your playlist if it have hyphen on its name or some other symbols. Make name simple

I did this, I renamed Winter 2019-2020 in Winter, nothing happens.

**Comment by yarik2720** [comment]
Try press button restart broadcasting in section Utilities

**Comment by tatojo** [comment]
I have this message:
Liquidsoap encountered an error
At line 23, char 20:
Error 3: Syntax error!
At line 23, char 20:
Error 3: Syntax error!
At line 23, char 20:
Error 3: Syntax error!

**Comment by tatojo** [comment]
> Rename your playlist if it have hyphen on its name or some other symbols. Make name simple

Same thing, I renamed Rotation-78 to Rotation78, updated again and everything is OK. Thanks!!

**Comment by rmacari** [comment]
Same error here after the latest update:

Liquidsoap encountered an error
At line 36, char 154-165:
Error 3: Syntax error!
At line 36, char 154-165:
Error 3: Syntax error!
At line 36, char 154-165:
Error 3: Syntax error!

**Comment by alutus** [comment]
> Same error here after the latest update:
> 
> Liquidsoap encountered an error
> At line 36, char 154-165:
> Error 3: Syntax error!
> At line 36, char 154-165:
> Error 3: Syntax error!
> At line 36, char 154-165:
> Error 3: Syntax error!

Rename your playlist from "your-playlist" to "yourplaylist" and then reboot broadcast services

**Comment by SlvrEagle23** [comment]
It appears this is caused by dashes in the names of playlists. I've added in a small bit of code to replace those with underscores, which should fix the issue.
