### ISSUE TITLE
Mixed-content while editing or deleting playlists

### ISSUE THREAD

**Issue by yarik2720** [AzuraCast/AzuraCast#2184]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 16.04

**Describe the bug**

Trying to delete playlist or making editing nothing does. Browser console shows errors:
`Заблокирована загрузка смешанного активного содержимого «http://cast.noisefm.ru/api/station/1/playlist/5»`

**To Reproduce**

1. Open admin panel with https proto
2. Go to playlists
3. Try to edit or delete playlist
4. See error in console

**Screenshots**

![firefox_2019-12-01_10-54-08](https://user-images.githubusercontent.com/1839978/69911204-237f9580-1429-11ea-9d0a-549ee5122a07.png)

**Device(s):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Firefox
 - Version: 70.0.1

**Comment by yarik2720** [comment]
Addition: I'm using proxy_pass from http://0.0.0.0:8080

**Comment by SlvrEagle23** [comment]
@yarik2720 You can fix this one of two ways: by either requiring HTTPS across the entire site, or by enabling the "Prefer Browser URL" setting, which will automatically update URLs in the API endpoints to match the URL you're coming from.

**Comment by yarik2720** [comment]
Prefer browser URL is enabled, but issue still present

**Comment by SlvrEagle23** [comment]
@yarik2720 Per the newer issue, try setting:

```
proxy_set_header X-Forwarded-Proto $scheme;
```

in your upstream nginx proxy's configuration. That will ensure that we receive and parse the correct HTTP scheme (http/https).

**Comment by yarik2720** [comment]
That worked!
