### ISSUE TITLE
Scheduled playlists are not playing correctly

### ISSUE THREAD

**Issue by PINKfm** [AzuraCast/AzuraCast#2185]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
If you schedule a playlist with more then one scheduled time, it ignores all other schedules and just plays the first one. You see it in the graphical timetable, but it seems that liquidsoap is ignoring that.

**To Reproduce**
Create two playlists with 2 or more scheduled times.

**Expected behavior**
If I schedule a playlist with 2 or more times, I would like to hear it to the scheduled times.

**Device(s):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: n/a

**Comment by yarik2720** [comment]
I have the same issue. Scheduled playlist never played. In liquidsoap logs scheduled playlist with tracks was loaded

**Comment by SlvrEagle23** [comment]
@yarik2720 @PINKfm Do either of you have the "Manual AutoDJ" mode turned on?

Also, just to be clear, you're saying that you _do_ hear the playlist at its first scheduled time, but not at any other scheduled times, if it has multiples?

I will look into this on our end.

**Comment by lewispmcadam** [comment]
I have the same issue as well.

**Comment by yarik2720** [comment]
Manual AutoDJ is turned off. For me I have several scheduled playlists during week and after update found that it didn't played even during this day

**Comment by SlvrEagle23** [comment]
@yarik2720 @lewispmcadam @PINKfm I have found the source of the problem and pushed a minor update out to the codebase.

You should be able to update within the next 5-10 minutes to receive the updated version, which should fix the issue and properly play all scheduled time slots for a given playlist.

**Comment by lewispmcadam** [comment]
@SlvrEagle23 does it update automatically or do I have to push it through.

Only recently started ti use azurecast

**Comment by SlvrEagle23** [comment]
@lewispmcadam The system doesn't automatically update, but you can update easily using our [update instructions](https://www.azuracast.com/install/#updating).

**Comment by yarik2720** [comment]
@SlvrEagle23 
After update at the morning I was waiting for scheduled playlist will play at the evening. But it is not played

![firefox_2019-12-03_22-43-26](https://user-images.githubusercontent.com/1839978/70083908-5b9bf980-161e-11ea-9a88-a2a3c47a716a.png)

**Comment by webma5ter23** [comment]
#2181 My problem is also in this part of the panel

**Comment by themadcap1976** [comment]
I'm having the same issue.

**Comment by yarik2720** [comment]
This is totally broken. One pf playlist have two schedule time in one day. Start time set in 00:00, end time in 00:00, second one in 20:00 - 20:00. There were one hour podcast in playlist, but it was never stopped, played this podcast again and again

**Comment by SlvrEagle23** [comment]
@yarik2720 I think the issue you're having is specifically with playlists that are scheduled to play once-per-day (i.e. the same start and end time), which are handled differently internally from ones that are normal scheduled ones.

I will look into this.

**Comment by SlvrEagle23** [comment]
@yarik2720 After further investigation, I discovered the problem: in our transition to supporting multiple schedule entries for a single playlist, I forgot to move over some of the corresponding code for the "play once per day" playlist mode (where the start and end times are equal).

This code has been ported over again, so if you update to the latest version released just a few moments ago, it should fix the issue.

Thank you for your patience.

**Comment by yarik2720** [comment]
Thanks!
