### ISSUE TITLE
How to show nowplaying when live

### ISSUE THREAD

**Issue by julianborghuis** [AzuraCast/AzuraCast#2187]
Hello,

How can i setup nowplaying if i am using encoders (live)?
Because theres now standing the latest number of the autodj before the streamer is going live. (i am using sam broadcaster)

**Comment by SlvrEagle23** [comment]
@julianborghuis You may be running into the problem described by issue #867. This is a known problem that we unfortunately can't fix, but switching the metadata just after connecting as a live DJ should trigger a refresh that updates your now-playing information appropriately.
