### ISSUE TITLE
ERROR - Using AzuraCast installation method

### ISSUE THREAD

**Issue by abdisoftware** [AzuraCast/AzuraCast#2189]
I cannot install AzuraCast. I tested from three different servers with Centos 7, Ubuntu 16.04 and Debian 10 and the same thing happens. It fails to connect to localhost and cannot create database tables, cannot connect, my site's index shows "File not found." ". On Friday morning I installed it without problem but on Saturday I could no longer install it again. I've been trying everything yesterday, but unlucky. 

I followed all the steps, (https://www.azuracast.com/install/#post-installation-setup) on Friday I was able to install it, but as of Saturday I can no longer do it. 

Excuse me if I have an error writing using google translator.

--------------------

root@demo:/var/azuracast# ./docker.sh update-self && echo "y" | ./docker.sh update
New Docker utility script downloaded.
Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Stopping azuracast_web        ... done
Stopping azuracast_stations   ... done
Stopping azuracast_redis_1    ... done
Stopping azuracast_influxdb_1 ... done
Stopping azuracast_mariadb_1  ... done
Removing azuracast_web        ... done
Removing azuracast_stations   ... done
Removing azuracast_redis_1    ... done
Removing azuracast_influxdb_1 ... done
Removing azuracast_mariadb_1  ... done
Removing network azuracast_default
azuracast_www_data
azuracast_tmp_data
Creating network "azuracast_default" with the default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_www_data" with default driver
Creating azuracast_mariadb_1  ... done
Creating azuracast_influxdb_1 ... done
Creating azuracast_stations   ... done
Creating azuracast_redis_1    ... done
2019/12/01 20:44:08 Waiting for: tcp://mariadb:3306
2019/12/01 20:44:08 Waiting for: tcp://influxdb:8086
2019/12/01 20:44:08 Connected to tcp://mariadb:3306
2019/12/01 20:44:08 Connected to tcp://influxdb:8086
Updating AzuraCast...
(Environment: production)
Installing azuracast/azuracast (dev-master 225981feef9f55061541b9d857118505bd783d22)
  - Installing azuracast/azuracast (dev-master 225981f): Cloning 225981feef from cache
Created project in /var/azuracast/new
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 0 installs, 14 updates, 0 removals
  - Updating ocramius/package-versions (1.4.2 => 1.5.1): Downloading (100%)
  - Updating aws/aws-sdk-php (3.121.1 => 3.123.0): Downloading (100%)
  - Updating cakephp/chronos (1.2.8 => 1.3.0): Downloading (100%)
  - Updating doctrine/cache (1.9.1 => 1.10.0): Downloading (100%)
  - Updating symfony/service-contracts (v2.0.0 => v2.0.1): Downloading (100%)
  - Updating symfony/polyfill-php73 (v1.12.0 => v1.13.1): Downloading (100%)
  - Updating mnapoli/silly (1.7.1 => 1.7.2): Downloading (100%)
  - Updating ocramius/proxy-manager (2.2.3 => 2.5.0): Downloading (100%)
  - Updating symfony/polyfill-ctype (v1.12.0 => v1.13.1): Downloading (100%)
  - Updating sentry/sentry (2.2.4 => 2.2.5): Downloading (100%)
  - Updating symfony/translation-contracts (v2.0.0 => v2.0.1): Downloading (100%)
  - Updating zircote/swagger-php (3.0.2 => 3.0.3): Downloading (100%)
  - Removing azuracast/azuracore (dev-master ebe0d99)
  - Installing azuracast/azuracore (dev-master d6716a2): Downloading (100%)
  - Removing james-heinrich/getid3 (dev-master 383dbec)
  - Installing james-heinrich/getid3 (dev-master 75454e8): Downloading (100%)
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class

AzuraCast Setup
===============

Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...
 * Environment: Production
 * Installation Method: Docker

 ! [NOTE] Running in update mode.

Setting Up InfluxDB
-------------------

Database created.
Retention policies updated.
Continuous queries created.
InfluxDB databases created.

Running Database Migrations
---------------------------

In AbstractMySQLDriver.php line 106:

  An exception occurred in driver: SQLSTATE[HY000] [1130] Host '172.21.0.6' i
  s not allowed to connect to this MariaDB server

In PDOConnection.php line 31:

  SQLSTATE[HY000] [1130] Host '172.21.0.6' is not allowed to connect to this
  MariaDB server

In PDOConnection.php line 27:

  SQLSTATE[HY000] [1130] Host '172.21.0.6' is not allowed to connect to this
  MariaDB server

azuracast:setup [--update] [--load-fixtures] [--release]

2019/12/01 20:49:16 Command exited with error: exit status 1
ERROR: Cannot kill container: d0218bacc47840e7cdfac273df327dca4ed6aabb5e2484110a845f2392d5a878: Container d0218bacc47840e7cdfac273df327dca4ed6aabb5e2484110a845f2392d5a878 is not running
azuracast_mariadb_1 is up-to-date
azuracast_stations is up-to-date
azuracast_redis_1 is up-to-date
azuracast_influxdb_1 is up-to-date
Creating azuracast_web ... done
Update complete!

root@demo:/var/azuracast#

-----------------------------------------

restart docker... And then...

-----------------------------------------

root@demo:/var/azuracast# ./docker.sh install
Docker is already installed! Continuing...
Docker Compose is already installed! Continuing...
Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Starting azuracast_influxdb_1 ... done
Starting azuracast_stations   ... done
Starting azuracast_redis_1    ... done
Starting azuracast_mariadb_1  ... done
2019/12/01 20:54:44 Waiting for: tcp://mariadb:3306
2019/12/01 20:54:44 Waiting for: tcp://influxdb:8086
2019/12/01 20:54:44 Connected to tcp://influxdb:8086
2019/12/01 20:54:44 Connected to tcp://mariadb:3306
Installing AzuraCast...
(Environment: production)
Installing azuracast/azuracast (dev-master 225981feef9f55061541b9d857118505bd783d22)
  - Installing azuracast/azuracast (dev-master 225981f): Cloning 225981feef from cache
Created project in /var/azuracast/new
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class

AzuraCast Setup
===============

Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...
 * Environment: Production
 * Installation Method: Docker

Setting Up InfluxDB
-------------------

Database created.
Retention policies updated.
Continuous queries created.
InfluxDB databases created.

Running Database Migrations
---------------------------

In AbstractMySQLDriver.php line 106:

  An exception occurred in driver: SQLSTATE[HY000] [1130] Host '172.21.0.7' is not allowed to connect to this Mar
  iaDB server

In PDOConnection.php line 31:

  SQLSTATE[HY000] [1130] Host '172.21.0.7' is not allowed to connect to this MariaDB server

In PDOConnection.php line 27:

  SQLSTATE[HY000] [1130] Host '172.21.0.7' is not allowed to connect to this MariaDB server

azuracast:setup [--update] [--load-fixtures] [--release]

2019/12/01 21:00:03 Command exited with error: exit status 1
azuracast_mariadb_1 is up-to-date
azuracast_influxdb_1 is up-to-date
azuracast_redis_1 is up-to-date
azuracast_stations is up-to-date
azuracast_web is up-to-date

--------------------------------------------------

root@demo:/var/azuracast/AzuraCast# docker-compose logs -f web
Attaching to azuracast_web
web_1       | 2019/12/01 21:17:24 Waiting for: tcp://mariadb:3306
web_1       | 2019/12/01 21:17:24 Waiting for: tcp://influxdb:8086
web_1       | 2019/12/01 21:17:24 Connected to tcp://influxdb:8086
web_1       | 2019/12/01 21:17:24 Connected to tcp://mariadb:3306
web_1       | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
web_1       | *** Running /etc/my_init.d/10_syslog-ng.init...
web_1       | Dec  1 21:17:27 c97a9a8c1f21 syslog-ng[21]: syslog-ng starting up; version='3.13.2'
web_1       | *** Running /etc/my_init.d/php.sh...
web_1       | 2019/12/01 21:17:29 Command finished successfully.
web_1       | *** Running /etc/my_init.d/php_workers.sh...
web_1       | Adding 0 additional workers
web_1       | Done
web_1       | *** Running /etc/my_init.d/touch_cron.sh...
web_1       | *** Booting runit daemon...
web_1       | *** Runit started as PID 42
web_1       | Spinning up FTP upload handler process...
web_1       | Dec  1 21:17:33 c97a9a8c1f21 cron[56]: (CRON) INFO (pidfile fd = 3)
web_1       | Dec  1 21:17:34 c97a9a8c1f21 cron[56]: (CRON) INFO (Running @reboot jobs)
web_1       | Dec  1 21:17:35 c97a9a8c1f21 php-fpm[58]: [NOTICE] fpm is running, pid 58
web_1       | Dec  1 21:17:35 c97a9a8c1f21 php-fpm[58]: [NOTICE] ready to handle connections
web_1       | Dec  1 21:17:35 c97a9a8c1f21 php-fpm[58]: [NOTICE] systemd monitor interval set to 10000ms
web_1       | [2019-12-01T21:17:49.391271+00:00] AzuraCast.INFO: Running message queue processor for 300 seconds. [] []
web_1       |
web_1       | In AbstractMySQLDriver.php line 106:
web_1       |
web_1       |   An exception occurred in driver: SQLSTATE[HY000] [1130] Host '172.21.0.6' i
web_1       |   s not allowed to connect to this MariaDB server
web_1       |
web_1       |
web_1       | In PDOConnection.php line 31:
web_1       |
web_1       |   SQLSTATE[HY000] [1130] Host '172.21.0.6' is not allowed to connect to this
web_1       |   MariaDB server
web_1       |
web_1       |
web_1       | In PDOConnection.php line 27:
web_1       |
web_1       |   SQLSTATE[HY000] [1130] Host '172.21.0.6' is not allowed to connect to this
web_1       |   MariaDB server
web_1       |
web_1       |
web_1       | azuracast:internal:ip
web_1       |
web_1       | Dec  1 21:18:03 c97a9a8c1f21 CRON[99]: (root) CMD (       sleep 45; /usr/local/bin/cron_task azuracast_cli sync:run nowplaying)
web_1       | Dec  1 21:18:03 c97a9a8c1f21 CRON[102]: (root) CMD (       sleep 30; /usr/local/bin/cron_task azuracast_cli sync:run nowplaying)
web_1       | Dec  1 21:18:03 c97a9a8c1f21 CRON[104]: (root) CMD (       sleep 15; /usr/local/bin/cron_task azuracast_cli sync:run nowplaying)
web_1       | Dec  1 21:18:03 c97a9a8c1f21 CRON[105]: (root) CMD (       /usr/local/bin/cron_task azuracast_cli sync:run nowplaying)
web_1       | Dec  1 21:18:03 c97a9a8c1f21 CRON[106]: (root) CMD (       /usr/local/bin/cron_task azuracast_cli sync:run short)
web_1       |
web_1       | In AbstractMySQLDriver.php line 106:
web_1       |
web_1       |   An exception occurred in driver: SQLSTATE[HY000] [1130] Host '172.21.0.6' i
web_1       |   s not allowed to connect to this MariaDB server
web_1       |
web_1       |
web_1       | In PDOConnection.php line 31:
web_1       |
web_1       |   SQLSTATE[HY000] [1130] Host '172.21.0.6' is not allowed to connect to this
web_1       |   MariaDB server
web_1       |
web_1       |
web_1       | In PDOConnection.php line 27:
web_1       |
web_1       |   SQLSTATE[HY000] [1130] Host '172.21.0.6' is not allowed to connect to this
web_1       |   MariaDB server
web_1       |
web_1       |
web_1       | sync:run [<task>]
web_1       |
web_1       |
web_1       | In AbstractMySQLDriver.php line 106:
web_1       |
web_1       |   An exception occurred in driver: SQLSTATE[HY000] [1130] Host '172.21.0.6' i
web_1       |   s not allowed to connect to this MariaDB server
web_1       |
web_1       |
web_1       | In PDOConnection.php line 31:
web_1       |
web_1       |   SQLSTATE[HY000] [1130] Host '172.21.0.6' is not allowed to connect to this
web_1       |   MariaDB server
web_1       |
web_1       |
web_1       | In PDOConnection.php line 27:
web_1       |
web_1       |   SQLSTATE[HY000] [1130] Host '172.21.0.6' is not allowed to connect to this
web_1       |   MariaDB server
web_1       |
web_1       |
web_1       | sync:run [<task>]
web_1       |

web_1       |
web_1       | In AbstractMySQLDriver.php line 106:
web_1       |
web_1       |   An exception occurred in driver: SQLSTATE[HY000] [1130] Host '172.21.0.6' i
web_1       |   s not allowed to connect to this MariaDB server
web_1       |
web_1       |
web_1       | In PDOConnection.php line 31:
web_1       |
web_1       |   SQLSTATE[HY000] [1130] Host '172.21.0.6' is not allowed to connect to this
web_1       |   MariaDB server
web_1       |
web_1       |
web_1       | In PDOConnection.php line 27:
web_1       |
web_1       |   SQLSTATE[HY000] [1130] Host '172.21.0.6' is not allowed to connect to this
web_1       |   MariaDB server
web_1       |
web_1       |
web_1       | sync:run [<task>]

---------------------------------------

root@demo:/var/azuracast/AzuraCast# docker-compose logs -f mariadb
Attaching to azuracast_mariadb_1
mariadb_1   | 2019-12-01 21:16:41 139753103652160 [Note] mysqld (mysqld 10.2.23-MariaDB-1:10.2.23+maria~bionic) star                  ting as process 1 ...
mariadb_1   | 2019-12-01 21:16:41 139753103652160 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1   | 2019-12-01 21:16:41 139753103652160 [Note] InnoDB: Uses event mutexes
mariadb_1   | 2019-12-01 21:16:41 139753103652160 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1   | 2019-12-01 21:16:41 139753103652160 [Note] InnoDB: Using Linux native AIO
mariadb_1   | 2019-12-01 21:16:41 139753103652160 [Note] InnoDB: Number of pools: 1
mariadb_1   | 2019-12-01 21:16:41 139753103652160 [Note] InnoDB: Using SSE2 crc32 instructions
mariadb_1   | 2019-12-01 21:16:41 139753103652160 [Note] InnoDB: Initializing buffer pool, total size = 256M, instan                  ces = 1, chunk size = 128M
mariadb_1   | 2019-12-01 21:16:41 139753103652160 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1   | 2019-12-01 21:16:41 139752381667072 [Note] InnoDB: If the mysqld execution user is authorized, page cl                  eaner thread priority can be changed. See the man page of setpriority().
mariadb_1   | 2019-12-01 21:16:41 139753103652160 [Note] InnoDB: Highest supported file format is Barracuda.
mariadb_1   | 2019-12-01 21:16:41 139753103652160 [Note] InnoDB: The log sequence number 1620663 in the system table                  space does not match the log sequence number 1620691 in the ib_logfiles!
mariadb_1   | 2019-12-01 21:16:48 139753103652160 [Note] InnoDB: 128 out of 128 rollback segments are active.
mariadb_1   | 2019-12-01 21:16:48 139753103652160 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
mariadb_1   | 2019-12-01 21:16:48 139753103652160 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_1   | 2019-12-01 21:16:48 139753103652160 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically w                  riting the file full; Please wait ...
mariadb_1   | 2019-12-01 21:16:48 139753103652160 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb_1   | 2019-12-01 21:16:48 139753103652160 [Note] InnoDB: Waiting for purge to start
mariadb_1   | 2019-12-01 21:16:48 139753103652160 [Note] InnoDB: 5.7.25 started; log sequence number 1620691
mariadb_1   | 2019-12-01 21:16:48 139752212764416 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffe                  r_pool
mariadb_1   | 2019-12-01 21:16:48 139753103652160 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1   | 2019-12-01 21:16:48 139753103652160 [Note] Recovering after a crash using tc.log
mariadb_1   | 2019-12-01 21:16:48 139753103652160 [Note] Starting crash recovery...
mariadb_1   | 2019-12-01 21:16:48 139753103652160 [Note] Crash recovery finished.
mariadb_1   | 2019-12-01 21:16:48 139753103652160 [Note] Server socket created on IP: '::'.
mariadb_1   | 2019-12-01 21:16:48 139752212764416 [Note] InnoDB: Buffer pool(s) load completed at 191201 21:16:48
mariadb_1   | 2019-12-01 21:16:48 139753103652160 [Warning] 'user' entry 'root@2f1eb3b811bd' ignored in --skip-name-                  resolve mode.
mariadb_1   | 2019-12-01 21:16:48 139753103652160 [Warning] 'proxies_priv' entry '@% root@2f1eb3b811bd' ignored in -                  -skip-name-resolve mode.
mariadb_1   | 2019-12-01 21:16:49 139753103652160 [Note] Reading of all Master_info entries succeded
mariadb_1   | 2019-12-01 21:16:49 139753103652160 [Note] Added new Master_info '' to hash table
mariadb_1   | 2019-12-01 21:16:49 139753103652160 [Note] mysqld: ready for connections.
mariadb_1   | Version: '10.2.23-MariaDB-1:10.2.23+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306                    mariadb.org binary distribution

**Comment by abdisoftware** [comment]
I first install azuracast and then try to upgrade. Finally restart the operating system and try again.... I've been trying since Saturday afternoon with no favorable results. I've tried from at least 3 different servers

**Comment by SlvrEagle23** [comment]
@abdisoftware I'm not sure what has happened with your MariaDB container, but it's not accepting connections from other Docker containers. We haven't updated the MariaDB container in quite some time, so this appears to be a configuration error specific to your installation.

Are you making any changes or customizing the `docker-compose.yml` file in any way?

If your database configuration is causing trouble, there are some possible ways to resolve it, but without being able to see your specific installation I wouldn't know which one of them would be the most appropriate.

If you're willing to share your installation details and work with us to diagnose the issue further, you can join us on our [Slack](https://azuracast.com/slack) or [Discord](https://azuracast.com/discord).

**Comment by abdisoftware** [comment]
I don't make any changes... I'm just following in the footsteps of the guide...

I formatted the operating system from scratch.

It is very strange that I cannot install it on the same server where I previously was able to do it. 

I have no problem collaborating and solving this detail.
