### ISSUE TITLE
Process Failure (Run Azuracast Setup (Install Mode))

### ISSUE THREAD

**Issue by hisetake** [AzuraCast/AzuraCast#2190]
I have a Raspberry PI 3B and when running the installation in Ansible mode I get an error in one of the steps called "Run AzuraCast Setup (Install Mode)" as the image below.

![totermw_AeNeyBI3Cb](https://user-images.githubusercontent.com/58446599/69996892-5d37c580-1529-11ea-9ec4-c3437f177d75.png)

I transferred the console error to an external file if I have trouble viewing the image.

https://pastebin.com/jTsX68db

**Comment by SlvrEagle23** [comment]
@hisetake I believe with the Raspberry Pi, this is caused by InfluxDB taking a little too long to "spin up" after it's installed and the service is started. You may want to try running `service influxdb start`, then re-running the installer and it should make it past that part.

**Comment by hisetake** [comment]
@SlvrEagle23  I tried but to no avail. The installer itself stops and starts InfluxDB again.

**Comment by hisetake** [comment]
@SlvrEagle23  I tried but to no avail. It still has the same error.

**Comment by hisetake** [comment]
@SlvrEagle23 InfluxDB has trouble connecting to port 8086 or sometimes takes longer than usual. Could you put something that can verify that Influx has started and responds on port 8086 and only then proceed with the installation? Or at least add an interrupt before performing the "Perform Azuracast Installation" step to allow the InfluxDB time to be fully initialized.

My timer indicated an average of 1 minute for InfluxDB to boot completely.

Thanks for the amazing work you have done so far.

**Comment by hisetake** [comment]
My God, I found that all the errors were occurring because of me. I was running an armv7l version of Ubuntu 18.04 all this time thinking it was arm64.

After running the installation on an Ubuntu 18.04 arm64 it ran smoothly! Sorry for my mistake.

**Comment by SlvrEagle23** [comment]
@hisetake Ahhh yes, both will run just fine on the same units. It can get confusing. Glad you got it figured out.

**Comment by aslak01** [comment]
> My God, I found that all the errors were occurring because of me. I was running an armv7l version of Ubuntu 18.04 all this time thinking it was arm64.
> 
> After running the installation on an Ubuntu 18.04 arm64 it ran smoothly! Sorry for my mistake.

I've just realised I was making the exact same mistake. Hope it'll work smoothly for me too now.
