### ISSUE TITLE
Liquidsoap encountered an error after update

### ISSUE THREAD

**Issue by irodionas** [AzuraCast/AzuraCast#2191]
After the latest 2 updates Liquidsoap encountered an error and will not start if your Playlists are named in other language than english (in my station was Greek) ... so i had to disable any greek titled playlist and then the Liquidsoap will work or renamed with English title

**Comment by SlvrEagle23** [comment]
@irodionas We've updated how we handle UTF-8 playlists, so this shouldn't still be a problem...if you pull up your liquidsoap configuration (from Utilities > Log Viewer), could you let me know what it's actually renaming the playlists to?

**Comment by irodionas** [comment]
@SlvrEagle23, I had closed every English title playlist and open one Greek title Αρμόνικα (img.1) , then reboot broadcast and Liquidsoap was not started (stream offline img.2). After pressing the Start button error messages (img.3) and if I try to press Next song Telnet error (img.4) ...Then by renamimg the Playlist and reboot ..every is back to normal!

2019/12/04 10:25:33 [lang:3] AzuraCast Feedback Response: OK
2019/12/04 10:27:54 [lang:3] AzuraCast Raw Response: annotate:title="Αγιάτρευτος καημός",artist="Περπινιάδης Στελλάκης",duration="194.",song_id="de2ab8bf80bfb46f5cda4d773a8aaa95",media_id="106",playlist_id="20":/var/azuracast/stations/grammofono/media/SkarvelisKostas/agiatreftos-kaimos-3.mp3
2019/12/04 10:27:54 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/grammofono/media/SkarvelisKostas/agiatreftos-kaimos-3.mp3".
2019/12/04 10:27:59 [main:3] Shutdown started!
2019/12/04 10:27:59 [main:3] Waiting for main threads to terminate...
2019/12/04 10:28:00 [grammofono_local_1:3] Closing connection...
2019/12/04 10:28:00 [clock.wallclock_main:3] Streaming loop stopped.
2019/12/04 10:28:00 [main:3] Threads terminated.
2019/12/04 10:28:00 [threads:3] Shutting down scheduler...
2019/12/04 10:28:00 [threads:3] Scheduler shut down.
2019/12/04 10:28:00 [threads:3] Waiting for queue threads to terminate...
2019/12/04 10:28:00 [threads:3] Queues shut down
2019/12/04 10:28:00 [server:3] Closing socket.
2019/12/04 10:28:00 [main:3] Cleaning downloaded files...
2019/12/04 10:28:00 [main:3] Freeing memory...
2019/12/04 10:28:00 >>> LOG END
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
At line 21, char 94-99:
Error 3: Syntax error!
2019/12/04 10:32:25 >>> LOG START
2019/12/04 10:32:25 [main:3] Liquidsoap 1.4.0
2019/12/04 10:32:25 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.3 sedlex=2.1 menhirLib=20190924 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.5.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.3 mad=0.4.5 flac=0.1.5 flac.ogg=0.1.5 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.3.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.9 camomile=1.0.2 faad=0.4.0
2019/12/04 10:32:25 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/12/04 10:32:25 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/12/04 10:32:25 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/12/04 10:32:25 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/12/04 10:32:25 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/12/04 10:32:25 [sandbox:3] Running inside a docker container, disabling sandboxing..
2019/12/04 10:32:25 [video.converter:3] Couldn't find preferred video converter: gavl.
2019/12/04 10:32:25 [audio.converter:3] Using samplerate converter: libsamplerate.
2019/12/04 10:32:25 [playlist_armonika:3] Loading playlist...
2019/12/04 10:32:25 [playlist_armonika:3] No mime type specified, trying autodetection.
2019/12/04 10:32:25 [playlist_armonika:3] Playlist treated as format application/x-mpegURL
2019/12/04 10:32:25 [playlist_armonika:3] Successfully loaded a playlist of 35 tracks.
2019/12/04 10:32:25 [playlist_todo:3] Loading playlist...
2019/12/04 10:32:25 [playlist_todo:3] No mime type specified, trying autodetection.
2019/12/04 10:32:25 [playlist_todo:3] Playlist treated as format application/x-mpegURL
2019/12/04 10:32:25 [playlist_todo:3] Successfully loaded a playlist of 0 tracks.
2019/12/04 10:32:25 [error_jingle:3] "/usr/local/share/icecast/web/error.mp3" is static, resolving once for all...
2019/12/04 10:32:25 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 0).
2019/12/04 10:32:25 [grammofono_local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2019/12/04 10:32:25 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/grammofono/media/0-Armonika/vlachiko-armonika.mp3".
2019/12/04 10:32:25 [lang:3] AzuraCast Raw Response: annotate:title="Φτώχεια μαζί με την τιμή",artist="Ρίτα Αμπατζή",duration="205.",song_id="89425fc45a6c425e4767024857701dfc",media_id="57",playlist_id="2":/var/azuracast/stations/grammofono/media/TountasPanagiotis/ftwxeia-mazi-me-tin-timi.mp3
2019/12/04 10:32:25 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/grammofono/media/TountasPanagiotis/ftwxeia-mazi-me-tin-timi.mp3".
2019/12/04 10:32:25 [grammofono_local_1:3] Connection setup was successful.
2019/12/04 10:32:25 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2019/12/04 10:32:25 [grammofono_safe_fallback:3] Switch to error_jingle.
2019/12/04 10:32:25 [grammofono_next_song:3] Prepared "/var/azuracast/stations/grammofono/media/TountasPanagiotis/ftwxeia-mazi-me-tin-timi.mp3" (RID 4).
2019/12/04 10:32:25 [grammofono_safe_fallback:3] Switch to grammofono_radio_cue with transition.
2019/12/04 10:32:25 [grammofono_requests_fallback:3] Switch to grammofono_autodj_fallback.
2019/12/04 10:32:25 [grammofono_autodj_fallback:3] Switch to audio_to_stereo_7658.
2019/12/04 10:32:25 [cross_7685:3] Analysis: -134.190311dB / -187.239671dB (0.04s / 0.04s)
2019/12/04 10:32:25 [crossfade:3] No transition: using default.
2019/12/04 10:32:25 [lang:3] AzuraCast Feedback Response: OK
2019/12/04 10:35:07 [lang:3] AzuraCast Raw Response: annotate:title="Εργάτης",artist="Κώστας Ρούκουνας",duration="192.",song_id="5a4810a1ce105908d1e7293b2596ca2a",media_id="14",playlist_id="2":/var/azuracast/stations/grammofono/media/0-Armonika/ergatis-timimenos.mp3
2019/12/04 10:35:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/grammofono/media/0-Armonika/ergatis-timimenos.mp3".
2019/12/04 10:35:48 [grammofono_next_song:3] Prepared "/var/azuracast/stations/grammofono/media/0-Armonika/ergatis-timimenos.mp3" (RID 5).
2019/12/04 10:35:48 [cross_7685:3] Analysis: -87.718269dB / -18.079893dB (2.98s / 2.98s)
2019/12/04 10:35:48 [crossfade:3] new >= old + margin, old <= medium and new <= high.
2019/12/04 10:35:48 [crossfade:3] Do not fade if it's already very low.
2019/12/04 10:35:48 [crossfade:3] Transition: crossed, no fade.
2019/12/04 10:35:48 [lang:3] AzuraCast Feedback Response: OK
![1](https://user-images.githubusercontent.com/58291183/70126613-13aebe00-1682-11ea-8314-757ffdae3b5f.png)
![2](https://user-images.githubusercontent.com/58291183/70126614-13aebe00-1682-11ea-83ed-320165027a3c.png)
![3](https://user-images.githubusercontent.com/58291183/70126616-13aebe00-1682-11ea-9f2d-aa6a00f5c589.png)
![4](https://user-images.githubusercontent.com/58291183/70126617-14475480-1682-11ea-8211-aa3f5509eb48.png)
![5](https://user-images.githubusercontent.com/58291183/70126619-14475480-1682-11ea-99e5-c6e14051b593.png)
![6](https://user-images.githubusercontent.com/58291183/70126620-14475480-1682-11ea-9fd4-b3fd78148c72.png)

**Comment by SlvrEagle23** [comment]
@irodionas Thank you for the detail, but that actually wasn't the log I was talking about...I was wondering if you could make a playlist with the Greek name, save it, and then if you see an error with Liquidsoap check the actual Liquidsoap _configuration_ (i.e. `liquidsoap.liq`) and see what it named the `playlist_` variable as.

I will try that myself shortly and see what the results are.

**Comment by SlvrEagle23** [comment]
@irodionas Testing locally, it appears my most recent fixes do already resolve this issue. You should update your installation to the latest version.
