### ISSUE TITLE
Error red ticker The request could not be processed

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2193]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04
( v0.9.8, #7fea11f (2019-12-03 0:46) • Docker • PHP 7.4)

**Describe the bug**
1. When doing actions such as add song to playlist or clear playlist from song
i'm getting orange ticker with "**Applying changes...**" and also blank red ticker
2. When deleting songs i'm getting  orange ticker with "Applying changes..." and red ticker with 
    "**The request could not be processed.**"
![image](https://user-images.githubusercontent.com/2701228/70163956-010ba780-16c9-11ea-8dcb-c459bf7e499a.png)

![image](https://user-images.githubusercontent.com/2701228/70163792-b5f19480-16c8-11ea-8704-caaaa64f19f9.png)

**Comment by SC2Mitch** [comment]
I've searched within the error logs, here we are

> web_1       | 2019/12/04 20:43:34 [error] 75#75: *29378 open() "/var/azuracast/www/web/static/dist/lib/bootstrap/bootstrap.bundle.min.js.map" failed (2: No such file or directory), client: PersonalIP, server: localhost, request: "GET /static/dist/lib/bootstrap/bootstrap.bundle.min.js.map HTTP/1.1", host: "hostIP"
> web_1       | 2019/12/04 20:43:34 [error] 75#75: *29378 open() "/var/azuracast/www/web/static/dist/lib/bootstrap-vue/bootstrap-vue.min.js.map" failed (2: No such file or directory), client: PersonalIP, server: localhost, request: "GET /static/dist/lib/bootstrap-vue/bootstrap-vue.min.js.map HTTP/1.1", host: "hostIP"
> web_1       | 2019/12/04 20:43:34 [error] 75#75: *29457 open() "/var/azuracast/www/web/static/dist/lib/bootstrap-vue/bootstrap-vue.min.css.map" failed (2: No such file or directory), client: PersonalIP, server: localhost, request: "GET /static/dist/lib/bootstrap-vue/bootstrap-vue.min.css.map HTTP/1.1", host: "hostIP"

But after some checking, the file does indeed be deleted after a refresh.

**Comment by themadcap1976** [comment]
One difference is that I don't see a "request could not be processed message" just the pink box on issue #2195

**Comment by yarik2720** [comment]
"Request could not be processed" shows only when you schedule track, but in this times it scheduled successfully

**Comment by SlvrEagle23** [comment]
@eranwo When you run into that error, the best way for us to diagnose it is to open your inspector console (in most browsers, it's F12), click the "Network" tab, then attempt to make the request again; you'll likely see a request that shows up in red or has a 500 error code. Click that request and view its response, and you should see an error message. Let us know what that error message says.

**Comment by yarik2720** [comment]
@SlvrEagle23 I have the same error, when I set track in playlist, there is no text in red error, but track applies to playlist. Screenshots:
![firefox_2019-12-05_23-17-41](https://user-images.githubusercontent.com/1839978/70270606-d64b4d00-17b5-11ea-833b-f4f39c630c7c.png)
![firefox_2019-12-05_23-18-23](https://user-images.githubusercontent.com/1839978/70270612-d9463d80-17b5-11ea-8d8c-dda13d850e5b.png)

When I trying to Queue track it shows error, but track successfully puts in queue, screenshots:
![firefox_2019-12-05_23-18-50](https://user-images.githubusercontent.com/1839978/70270690-0266ce00-17b6-11ea-81f3-d708e547633d.png)
![firefox_2019-12-05_23-18-59](https://user-images.githubusercontent.com/1839978/70270691-0266ce00-17b6-11ea-9b18-727fc9759278.png)

**Comment by SlvrEagle23** [comment]
@yarik2720 That is related to a different issue, which I fixed just a few minutes ago.

**Comment by eranwo** [comment]
The last update fixed the issue. Thank you.
