### ISSUE TITLE
Installing Lets Encrypt - but how?

### ISSUE THREAD

**Issue by HSoeren** [AzuraCast/AzuraCast#2194]
I want to use SSL / HTTPS on my instance but i dont know how to add a certificate (Lets Encrypt with Certbot or acme). I searched the Help Pages and the issues here but did not find anything helping. Is there any guide to this?

**Comment by HSoeren** [comment]
For technical information, OS:
```No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```
"v0.9.8, #7fea11f (2019-12-03 0:46) • Docker • PHP 7.4"

just installed this morning, via the script in Docker Mode i think.

**Comment by AshleyinSpain** [comment]
@HSoeren Try here - https://www.azuracast.com/developers/docker_sh.html#set-up-letsencrypt

**Comment by HSoeren** [comment]
> @HSoeren Try here - https://www.azuracast.com/developers/docker_sh.html#set-up-letsencrypt

Thank you very much. My instance has now working SSL. Thanks
