### ISSUE TITLE
QUESTION: Re-Shuffle?

### ISSUE THREAD

**Issue by adwinter** [AzuraCast/AzuraCast#2196]
Hey Guys, was hoping someone could answer a question for me... I'm wondering if there is a way to force a re-shuffle of a playlist? When I was using the "traditional" install, I was able to do use an SQL query to accomplish this, but now that I'm on the Docker version -- I don't have easy access to the database. 

I understand that if I restart the station it will reset the "cache", but I don' think that's what I want.. I want it to re-shuffle. I move songs in and out of playlists fairly often, so if there is a way to force a new shuffle, it would be awesome.

Anyway, thanks in advance for any advice.

Andrew

**Comment by rmacari** [comment]
@adwinter That´s a good question and you probably should ask for a new feature: https://features.azuracast.com

When i need a reshuffle i just add a new file to the playlist, as i noted this reshuffle the playlist. Hope it helps while this feature is not available.

**Comment by adwinter** [comment]
@rmacari Thanks for the reply. This definitely does help awaiting a possible future enhancement. I honestly didn't know it re-shuffled each time a new file was added --- that means my playlists are re-shuffling a lot more than I thought they were. LOL  I move files around into different playlists all the time-- so each time I'm moving a file its gonna re-shuffle -- which is great news. 

Thanks again for the help.

Andrew

**Comment by rmacari** [comment]
@adwinter Happy to help. :)
