### ISSUE TITLE
Can't edit playlists

### ISSUE THREAD

**Issue by schakoska** [AzuraCast/AzuraCast#2197]
Hi,

I want to edit my playlist, but Ican't because the window doesn't show up. Also my friend has the same problem on his server.

The log said this when I clicked the Edit button:
[2019-12-07T06:20:52.057358+00:00] AzuraCast.INFO: Permission denied. {"file":"/var/azuracast/www/src/Middleware/Permissions.php","line":47,"code":0} []

I'm not the server administrator so I can't check this file, but I asked the administrator and he said there is no file named "Permission.php".

Host Operating System:
Linux, Debian

Video about the problem: https://youtu.be/1ezmePddC2c

Device:
 - Device: Desktop 
 - OS: Windows 10 Pro 1903
 - Browser: Google Chrome
 - Version: 78.0.3904.108

I tried other devices, but I got the same result.

**Comment by blindndangerous** [comment]
I'm having the same issue here, running the Ansible installation. I can make the playlists, and the first one I made shows up in playlists both on the webpage and in the playlists directory of my station, but after that, I can't edit it's details or delete it, and if I delete it from the pi itself, it doesn't update on the webpage.  The only thing I can think of is permissions, but I'm really not sure.  I don't see anything that I can find in logs, unless I'm looking in the wrong places.

**Comment by SlvrEagle23** [comment]
One important thing to check for is whether the "Prefer Browser URL" setting is turned on. It should definitely be turned on to avoid problems like this.

**Comment by blindndangerous** [comment]
That was exactly it, turning that back on fixed it.  Can I ask why that is?  New to all of this, so love to learn.

**Comment by SlvrEagle23** [comment]
@blindndangerous This is embarrassing but I have no idea. It *shouldn't* be affecting that page but it seems to affect our new Vue components more than older ones. I'm still looking into why that is.

**Comment by SlvrEagle23** [comment]
@blindndangerous I've made some changes to the application that will prevent this setting from causing trouble in the future. In fact, with the modern setup of the application, the setting is no longer even needed at all, so I've removed it from the settings panel, as setting it to "off" caused a number of problems with pages that called API endpoints (namely the media manager, playlist manager, etc).
