### ISSUE TITLE
Icecast not publishing to directories.

### ISSUE THREAD

**Issue by themadcap1976** [AzuraCast/AzuraCast#2198]
I'm have configured icecast to publish to 2 directories and nothing is coming up. What am I missing here? 

I set the directory settings on the main broadcasting page and not under the mount, not sure if that's what I'm supposed to do?

![Screen Shot 2019-12-07 at 9 51 33 AM](https://user-images.githubusercontent.com/32073620/70376478-6cc35f80-18d7-11ea-9fe0-47592a42fedf.png)
![Screen Shot 2019-12-07 at 9 42 35 AM](https://user-images.githubusercontent.com/32073620/70376485-76e55e00-18d7-11ea-914a-0a817d891eeb.png)

**Comment by SlvrEagle23** [comment]
@themadcap1976 When you view your Icecast configuration (which can be done via `Utilities` -> `Log Viewer`, then selecting "Icecast configuration")...does it reflect both directory entries being listed in the resulting XML?

I'm not sure that the custom code processor can handle multiple entries with the same tag like that...though it's worth noting it does also accept JSON, which means you could type something to the effect of:

```json
{
  "directory": [
    { "yp-url-timeout": 15, "yp-url": "http://icecast-yp.internet-radio.com" },
    { "yp-url-timeout": 15, "yp-url": "http://dir.xiph.org/cgi-bin/yp-cgi" }
  ]
}
```

...and that might work better.

**Comment by themadcap1976** [comment]
Changed to json and it seems to like it now, both directory entries are reflected in the XML (they were there previously). Closing.
