### ISSUE TITLE
update.sh error

### ISSUE THREAD

**Issue by linksilver** [AzuraCast/AzuraCast#220]
#i tried ./update.sh and ./update.sh -full

Migrating up to 20170823204230 from 20170719045113

`fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php migrations:migrate --no-interaction --allow-no-migration", "delta": "0:00:01.792124", "end": "2017-08-28 21:06:10.165097", "failed": true, "rc": 1, "start": "2017-08-28 21:06:08.372973", "stderr": "\n                                                                               \n  [Doctrine\\DBAL\\Exception\\DriverException]                                    \n  An exception occurred while executing 'ALTER TABLE listener CHANGE listener  \n  _user_agent listener_user_agent VARCHAR(191) NOT NULL':                      \n  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'listener_user_age  \n  nt' at row 433                                                               \n                                                                               \n\n                                                                               \n  [Doctrine\\DBAL\\Driver\\PDOException]                                          \n  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'listener_user_age  \n  nt' at row 433                                                               \n                                                                               \n\n                                                                               \n  [PDOException]                                                               \n  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'listener_user_age  \n  nt' at row 433                                                               \n                                                                               \n\nmigrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--] [<version>]", "stderr_lines": ["", "                                                                               ", "  [Doctrine\\DBAL\\Exception\\DriverException]                                    ", "  An exception occurred while executing 'ALTER TABLE listener CHANGE listener  ", "  _user_agent listener_user_agent VARCHAR(191) NOT NULL':                      ", "  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'listener_user_age  ", "  nt' at row 433                                                               ", "                                                                               ", "", "                                                                               ", "  [Doctrine\\DBAL\\Driver\\PDOException]                                          ", "  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'listener_user_age  ", "  nt' at row 433                                                               ", "                                                                               ", "", "                                                                               ", "  [PDOException]                                                               ", "  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'listener_user_age  ", "  nt' at row 433                                                               ", "                                                                               ", "", "migrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--] [<version>]"], "stdout": "Loading configuration from the integration code of your framework (setter).\n                                                                    \n                    Doctrine Database Migrations                    \n                                                                    \n\nMigrating up to 20170823204230 from 20170719045113\n\n  ++ migrating 20170803050109\n\n     -> ALTER TABLE listener CHANGE listener_user_agent listener_user_agent VARCHAR(191) NOT NULL\nMigration 20170803050109 failed during Execution. Error An exception occurred while executing 'ALTER TABLE listener CHANGE listener_user_agent listener_user_agent VARCHAR(191) NOT NULL':\n\nSQLSTATE[01000]: Warning: 1265 Data truncated for column 'listener_user_agent' at row 433", "stdout_lines": ["Loading configuration from the integration code of your framework (setter).", "                                                                    ", "                    Doctrine Database Migrations                    ", "                                                                    ", "", "Migrating up to 20170823204230 from 20170719045113", "", "  ++ migrating 20170803050109", "", "     -> ALTER TABLE listener CHANGE listener_user_agent listener_user_agent VARCHAR(191) NOT NULL", "Migration 20170803050109 failed during Execution. Error An exception occurred while executing 'ALTER TABLE listener CHANGE listener_user_agent listener_user_agent VARCHAR(191) NOT NULL':", "", "SQLSTATE[01000]: Warning: 1265 Data truncated for column 'listener_user_agent' at row 433"]}
`

**Comment by SlvrEagle23** [comment]
@linksilver I've updated the database migrations so that they won't try to truncate the VARCHAR fields down to 191 characters from 255; since all MariaDB installs will be stabilized on 10.2 now, which supports VARCHAR(255) on UTF8MB4.

Try running update again, and it should work properly. You may get an issue about foreign key constraints not existing, and you may need to run one (or both) of these commands to resolve that:

```
php /var/azuracast/www/util/cli.php dbal:run-sql "ALTER TABLE song_history ADD CONSTRAINT FK_2AD16164A0BDB2F3 FOREIGN KEY (song_id) REFERENCES songs (id) ON DELETE CASCADE"

php /var/azuracast/www/util/cli.php dbal:run-sql "ALTER TABLE station_media ADD CONSTRAINT FK_32AADE3AA0BDB2F3 FOREIGN KEY (song_id) REFERENCES songs (id) ON DELETE SET NULL"
```
