### ISSUE TITLE
Delete a song while it is playing

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2201]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
Hi,

What happens if i accidentally delete a song while it is playing?  As i can see the system allows this but the song keep playing until it end. Is it possible to add a protection against accidentally delete of songs while they playing ?

**Comment by SC2Mitch** [comment]
If a song is deleted while playing, it'll continue to play (possibly due to caching?) and it does give you a warning before you delete. 
![%pn_62WlNs1Rg7](https://user-images.githubusercontent.com/29955942/70382577-58727780-1956-11ea-899d-e15c291a049c.png)

**Comment by SlvrEagle23** [comment]
@eranwo Liquidsoap maintains an internal cache of a song's contents and will play through that, and if that includes the rest of the file then it won't have any issues.

If it detects that a file was moved or deleted while it's actively playing, it'll throw a very angry exception message in the logs (indicating something to the effect of "don't ever do this") and abruptly transition to the next song.

As far as I can tell, it doesn't cause any long-term damage, though.
