### ISSUE TITLE
Docker update error

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#2202]
Hi,

I already solved and managed to install with the docker, but now I can not update.

OS: Ubuntu 16.04

Commands Used:

./docker.sh update-self
./docker.sh update

or

./docker.sh update-self && echo "y" | ./docker.sh update

and returned this error:

-bash: ./docker.sh: No such file or directory

Thank you

**Comment by SlvrEagle23** [comment]
@jonikane You need to change into the directory where you put those scripts when you followed the installation. Most of the time, this will be `/var/azuracast`, so just run:

```bash
cd /var/azuracast
./docker.sh update-self
./docker.sh update
```

**Comment by jonikane** [comment]
Done.

Its ok now.

Thank you
