### ISSUE TITLE
.

### ISSUE THREAD

**Issue by InstabilSpielt** [AzuraCast/AzuraCast#2204]
.

**Comment by CookieFromGermany** [comment]
> 
> 
> **Using Docker installation method**
> Yes
> 
> **Host Operating System**
> Debian 9
> 
> **Describe the bug**
> The last step from the installation don't work,
> and the installation stopped.
> 
> **Screenshot**
> https://de.share-your-photo.com/784e79544d
> 
> **Relevant Logs**
> Starting azuracast_web ...
> Starting azuracast_web ... error
> 
> ERROR: for azuracast_web Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web (ce1b960f9d112884627265162db67e4af897af172004e6d40a05df1b5a75befe): Error starting userland proxy: listen tcp 0.0.0.0:30033: bind: address already in use
> 
> ERROR: for web Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web (ce1b960f9d112884627265162db67e4af897af172004e6d40a05df1b5a75befe): Error starting userland proxy: listen tcp 0.0.0.0:30033: bind: address already in use

**Comment by CookieFromGermany** [comment]
Opened

**Comment by CookieFromGermany** [comment]
> 
> 
> **Using Docker installation method**
> Yes
> 
> **Host Operating System**
> Debian 9
> 
> **Describe the bug**
> The last step from the installation don't work,
> and the installation stopped.
> 
> **Screenshot**
> https://de.share-your-photo.com/784e79544d
> 
> **Relevant Logs**
> Starting azuracast_web ...
> Starting azuracast_web ... error
> 
> ERROR: for azuracast_web Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web (ce1b960f9d112884627265162db67e4af897af172004e6d40a05df1b5a75befe): Error starting userland proxy: listen tcp 0.0.0.0:30033: bind: address already in use
> 
> ERROR: for web Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web (ce1b960f9d112884627265162db67e4af897af172004e6d40a05df1b5a75befe): Error starting userland proxy: listen tcp 0.0.0.0:30033: bind: address already in use

**Comment by SlvrEagle23** [comment]
@CookieFromGermany There's some other process on your computer using the same port range that our built-in FTP server's passive (PASV) connection ports are using.

On most OSes you can run `sudo netstat -pna | grep 30033` to see what program is currently using the port. You may need to edit that program's configuration or stop the service.

**Comment by CookieFromGermany** [comment]
Is it possible to change the port from Azuracast?,
because Teamspeak is using this port already for tcp.

**Comment by SlvrEagle23** [comment]
@CookieFromGermany Which port? If it's one of the standard web ports, you can follow our guide for [using non-standard ports](https://www.azuracast.com/help/faq_docker.html#use-non-standard-ports); if it's another one of our reserved ports, it may be more difficult.

**Comment by CookieFromGermany** [comment]
It are more ports. i changed some and then are coming more ports which i have to change.
Is it possible to give Azuracast an own Ip-Adress in the Docker-Installation progress?

**Comment by mgiannelis** [comment]
Hello.

I have been trying to get Auzracast Installed for days now and I have spent over 70Hours trying to get this to work.
Background. I am trying to install this with a fresh install of Ubuntu 18.4 server
I have a windows 2012 R2 server running HyperV and I am installing/running the Unbuntu Server ISO setup file and run as a virtual machine.
I have been unable to get the docker install type to work. Or Ansible And I know nothing about docker or even what it actually is. I'm just trying to follow instructions I believe that I am missing something or not doing something correctly. There has to defiantly be some kind of missing step in the install instructions.
I have also followed the Ansible instructions which seem to be more simple absolutely step by step several times. And each time on a new fresh install of ubuntu. However I keep getting an error at the end of the install. I need to take a screen shot of this and add it to this post. (Stand By) Ill put it up on my next install attempt.
This is starting to drive me crazy! Now I know there is nothing wrong or any incompatibility issues with hardware or the fact that I am using a HyperV virtual machine as I had an old friend install and get it up and running for me in the past on the same platform without issue. However my attempts at trying to replicate his success has failed over and over again. I'am trying to reinstall it and get it back up and running in a fresh ubuntu install. However time and time again it fails with some errors at the end.
Also. While following the instructions here. https://www.azuracast.com/install/ansible.html#installing
The URL describes the whole install process to be between 10 to 15 minutes.,
I have a 100Mpbs internet connection. And this install process seems to take over 45 minutes.
It never took my friend that long to install it on my server.

I have no idea whats going on. I am a newbie to linux and installing applications. However I have followed all the install instructions step by step. Both using the ansible and docker methods.
I have a feeling that there is something missing in the instructions. Perhaps some steps that are not in there. I am basing my issues/complaint on the fact that I am following the instructions step by step as set out in the URL above.
Can you someone please indicate. Are there steps missing from the instructions? I have no idea. I'm not a linux person.

I am hoping. That someone who is reading this might be a pro. And upon me giving a pro access via SSH to help me set this up and get it back up and running for me.

I messed up my installation when I was trying to work out how to enable SSL. I should have taken a backup of my VM before I started messing around with it.

When it was working. I was totally amazed with how cool AzuraCast was. I loved it and loved playing around with it. I was using it to run a Flight Simulator radio station.
I really want this back up and running. I hope someone here can help me with this.
As I mentioned. I will post the image of the error that I get when the ansible install finishes.

Please. Is there someone out there that would be kind enough to SSH into my ubuntu fresh server install and get this up and running for me.
The documentation on the internet for installing the package is very limited. There is hardly anything out there at all!
All I can find is instructions on to how to actually use Azuracast. But there is pretty much nothing out there for help with installing and installations issues and support.

I look forward to hearing from anyone that will be willing to help me install this via an SSH connection for me.

Even happy to pay up to $20 Australian Dollars to assist me. I am desperate to get this running.

Thank you for reading.

Matthew

**Comment by SlvrEagle23** [comment]
@mgiannelis Please do not spam the same request across multiple issues. Many of us get e-mails with every update to every GitHub issue, and I've seen the same body of text about 4 or 5 times this morning.
