### ISSUE TITLE
mp3 + OPUS ogg cannot run autoDJ

### ISSUE THREAD

**Issue by zeLostchild** [AzuraCast/AzuraCast#2206]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
When running a station with an opus and mp3 mount point simultaneously the autoDJ liquid soap Will not run 

**To Reproduce**

1. Go to stations 
2. Create a mp3 mountpoint
3. Create a ogg Opus mountpoint
4. Try to start server
System Message says backend started and autoDJ remains not running

**Expected behavior**
AutoDJ to be running

**Device(s):**
 - Device:  
 - OS: MacOS
 - Browser: safari
 - Version: 13.03

**Additional Information**
OGG Vorbis will run with mp3 mountpoints. That was my solution.

**Comment by ivellios1988** [comment]
I did an update yesterday and it looks like Liquidsoap stopped working completely. Each time I try to launch Liquidsoap, it shows a message that frontend has been successfully started, however, it goes down immediately afterwards.

Tried with MP3 and OPUS on mountpoints, however, results are always the same.

Here's what log says:

2019/12/09 22:49:38 >>> LOG START
2019/12/09 22:49:38 [main:3] Liquidsoap 1.4.0
2019/12/09 22:49:38 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.3 sedlex=2.1 menhirLib=20190924 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.5.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.3 mad=0.4.5 flac=0.1.5 flac.ogg=0.1.5 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.3.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.9 camomile=1.0.2 faad=0.4.0
2019/12/09 22:49:38 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/12/09 22:49:38 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/12/09 22:49:38 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/12/09 22:49:38 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/12/09 22:49:38 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/12/09 22:49:38 [sandbox:3] Running inside a docker container, disabling sandboxing..
2019/12/09 22:49:38 [video.converter:3] Couldn't find preferred video converter: gavl.
2019/12/09 22:49:38 [audio.converter:3] Using samplerate converter: libsamplerate.
2019/12/09 22:49:38 [playlist_default:3] Loading playlist...
2019/12/09 22:49:38 [playlist_default:3] No mime type specified, trying autodetection.
2019/12/09 22:49:38 [playlist_default:3] Playlist treated as format application/x-mpegURL
2019/12/09 22:49:38 [playlist_default:3] Successfully loaded a playlist of 0 tracks.
2019/12/09 22:49:38 [error_jingle:3] "/usr/local/share/icecast/web/error.mp3" is static, resolving once for all...
2019/12/09 22:49:38 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 0).
2019/12/09 22:49:38 [opus2_local_1:3] Connecting mount /opusiara for source@127.0.0.1...
2019/12/09 22:49:39 [lang:3] AzuraCast Raw Response: 
2019/12/09 22:49:39 [lang:3] AzuraCast Error: Delaying subsequent requests...
2019/12/09 22:49:39 [opus2_local_1:3] Connection setup was successful.
2019/12/09 22:49:39 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2019/12/09 22:49:39 [opus2_safe_fallback:3] Switch to error_jingle.
2019/12/09 22:49:39 [clock.wallclock_main:2] Source opus2_local_1 failed while streaming: Failure("Unknown opus error")!
2019/12/09 22:49:39 [clock.wallclock_main:3] Raised by primitive operation at file "opus.ml", line 181, characters 34-63
2019/12/09 22:49:39 [clock.wallclock_main:3] Called from file "ogg_formats/opus_encoder.ml", line 61, characters 9-108
2019/12/09 22:49:39 [clock.wallclock_main:3] Called from file "ogg_formats/opus_encoder.ml", line 66, characters 14-24
2019/12/09 22:49:39 [clock.wallclock_main:3] Called from file "ogg_formats/ogg_muxer.ml", line 217, characters 10-41
2019/12/09 22:49:39 [clock.wallclock_main:3] Called from file "encoder/ogg_encoder.ml", line 171, characters 27-50
2019/12/09 22:49:39 [clock.wallclock_main:3] Called from file "list.ml", line 110, characters 12-15
2019/12/09 22:49:39 [clock.wallclock_main:3] Called from file "encoder/ogg_encoder.ml", line 173, characters 8-26
2019/12/09 22:49:39 [clock.wallclock_main:3] Called from file "outputs/output.ml", line 254, characters 24-44
2019/12/09 22:49:39 [clock.wallclock_main:3] Called from file "outputs/output.ml", line 181, characters 8-24
2019/12/09 22:49:39 [clock.wallclock_main:3] Called from file "clock.ml", line 160, characters 17-25
2019/12/09 22:49:39 [opus2_local_1:3] Closing connection...
2019/12/09 22:49:41 [clock.wallclock_main:3] Streaming loop stopped.
2019/12/09 22:49:41 [main:3] Shutdown started!
2019/12/09 22:49:41 [main:3] Waiting for main threads to terminate...
2019/12/09 22:49:41 [main:3] Threads terminated.
2019/12/09 22:49:41 [threads:3] Shutting down scheduler...
2019/12/09 22:49:41 [threads:3] Scheduler shut down.
2019/12/09 22:49:41 [threads:3] Waiting for queue threads to terminate...
2019/12/09 22:49:41 [threads:3] Queues shut down
2019/12/09 22:49:41 [server:3] Closing socket.
2019/12/09 22:49:41 [main:3] Cleaning downloaded files...
2019/12/09 22:49:41 [main:3] Freeing memory...

**Comment by Vaalyn** [comment]
I can see the same happening with one of my stations.

Here is the LiquidSoap log from that station:
```
2019/12/12 14:05:29 >>> LOG START
2019/12/12 14:05:29 [main:3] Liquidsoap 1.4.0
2019/12/12 14:05:29 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.3 sedlex=2.1 menhirLib=20190924 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.5.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.3 mad=0.4.5 flac=0.1.5 flac.ogg=0.1.5 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.3.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.9 camomile=1.0.2 faad=0.4.0
2019/12/12 14:05:29 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/12/12 14:05:29 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/12/12 14:05:29 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/12/12 14:05:29 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/12/12 14:05:29 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/12/12 14:05:29 [sandbox:3] Running inside a docker container, disabling sandboxing..
2019/12/12 14:05:29 [video.converter:3] Couldn't find preferred video converter: gavl.
2019/12/12 14:05:29 [audio.converter:3] Using samplerate converter: libsamplerate.
2019/12/12 14:05:29 [harbor:3] Adding mountpoint '/' on port 8010
2019/12/12 14:05:29 [playlist_jingles:3] Loading playlist...
2019/12/12 14:05:29 [playlist_jingles:3] No mime type specified, trying autodetection.
2019/12/12 14:05:29 [playlist_jingles:3] Playlist treated as format application/x-mpegURL
2019/12/12 14:05:29 [playlist_jingles:3] Successfully loaded a playlist of 25 tracks.
2019/12/12 14:05:29 [playlist_blackys_jingles:3] Loading playlist...
2019/12/12 14:05:29 [playlist_blackys_jingles:3] No mime type specified, trying autodetection.
2019/12/12 14:05:29 [playlist_blackys_jingles:3] Playlist treated as format application/x-mpegURL
2019/12/12 14:05:29 [playlist_blackys_jingles:3] Successfully loaded a playlist of 3 tracks.
2019/12/12 14:05:29 [playlist_nightdj:3] Loading playlist...
2019/12/12 14:05:29 [playlist_nightdj:3] No mime type specified, trying autodetection.
2019/12/12 14:05:29 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/brg/media/Jingles/katrina_hadley_-_brg_jingle_-28w_big_jim-29.mp3".
2019/12/12 14:05:29 [playlist_nightdj:3] Playlist treated as format application/x-mpegURL
2019/12/12 14:05:29 [playlist_nightdj:3] Successfully loaded a playlist of 608 tracks.
2019/12/12 14:05:29 [playlist_daydj:3] Loading playlist...
2019/12/12 14:05:29 [playlist_daydj:3] No mime type specified, trying autodetection.
2019/12/12 14:05:29 [lang:3] AzuraCast Raw Response: annotate:title="I Am No Hero [Remastered]",artist="MandoPony",duration="272.",song_id="3b34245825ef0769a38a1a05374418e2",media_id="20978",playlist_id="1":/var/azuracast/stations/brg/media/DayDj/mandopony_-_i_am_no_hero_-5Bremastered-5D.mp3
2019/12/12 14:05:29 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/brg/media/Jingles/peter_new_-_brg_jingle.mp3".
2019/12/12 14:05:29 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/brg/media/Jingles/brg_-_sendeplan.mp3".
2019/12/12 14:05:29 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/brg/media/DayDj/mandopony_-_i_am_no_hero_-5Bremastered-5D.mp3".
2019/12/12 14:05:29 [playlist_daydj:3] Playlist treated as format application/x-mpegURL
2019/12/12 14:05:29 [playlist_daydj:3] Successfully loaded a playlist of 2686 tracks.
2019/12/12 14:05:29 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/brg/media/NightDj/luna_jax_-_starry_starry_night_-28vincent_parody-29.mp3".
2019/12/12 14:05:29 [error_jingle:3] "/usr/local/share/icecast/web/error.mp3" is static, resolving once for all...
2019/12/12 14:05:29 [brg_next_song:3] Prepared "/var/azuracast/stations/brg/media/DayDj/mandopony_-_i_am_no_hero_-5Bremastered-5D.mp3" (RID 7).
2019/12/12 14:05:29 [brg_local_1:3] Connecting mount /stream for source@127.0.0.1...
2019/12/12 14:05:29 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/brg/media/DayDj/spectra_-_peace_at_last..._-28neverlaststanding_remix-29.mp3".
2019/12/12 14:05:29 [brg_local_1:3] Connection setup was successful.
2019/12/12 14:05:29 [brg_local_2:3] Connecting mount /mobile for source@127.0.0.1...
2019/12/12 14:05:30 [brg_local_2:3] Connection setup was successful.
2019/12/12 14:05:30 [brg_local_3:3] Connecting mount /opus for source@127.0.0.1...
2019/12/12 14:05:30 [brg_local_3:3] Connection setup was successful.
2019/12/12 14:05:30 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2019/12/12 14:05:30 [brg_live_switch:3] Switch to brg_safe_fallback.
2019/12/12 14:05:30 [brg_safe_fallback:3] Switch to brg_radio_cue.
2019/12/12 14:05:30 [brg_requests_fallback:3] Switch to brg_autodj_fallback.
2019/12/12 14:05:30 [brg_autodj_fallback:3] Switch to audio_to_stereo_7689.
2019/12/12 14:05:30 [lang:3] AzuraCast Feedback Response: OK
2019/12/12 14:05:30 [clock.wallclock_main:2] Source brg_local_3 failed while streaming: Failure("Unknown opus error")!
2019/12/12 14:05:30 [clock.wallclock_main:3] Raised by primitive operation at file "opus.ml", line 181, characters 34-63
2019/12/12 14:05:30 [clock.wallclock_main:3] Called from file "ogg_formats/opus_encoder.ml", line 61, characters 9-108
2019/12/12 14:05:30 [clock.wallclock_main:3] Called from file "ogg_formats/opus_encoder.ml", line 66, characters 14-24
2019/12/12 14:05:30 [clock.wallclock_main:3] Called from file "ogg_formats/ogg_muxer.ml", line 217, characters 10-41
2019/12/12 14:05:30 [clock.wallclock_main:3] Called from file "encoder/ogg_encoder.ml", line 171, characters 27-50
2019/12/12 14:05:30 [clock.wallclock_main:3] Called from file "list.ml", line 110, characters 12-15
2019/12/12 14:05:30 [clock.wallclock_main:3] Called from file "encoder/ogg_encoder.ml", line 173, characters 8-26
2019/12/12 14:05:30 [clock.wallclock_main:3] Called from file "outputs/output.ml", line 254, characters 24-44
2019/12/12 14:05:30 [clock.wallclock_main:3] Called from file "outputs/output.ml", line 181, characters 8-24
2019/12/12 14:05:30 [clock.wallclock_main:3] Called from file "clock.ml", line 160, characters 17-25
2019/12/12 14:05:30 [brg_local_3:3] Closing connection...
2019/12/12 14:05:30 [main:3] Shutdown started!
2019/12/12 14:05:30 [main:3] Waiting for main threads to terminate...
2019/12/12 14:05:30 [brg_local_2:3] Closing connection...
2019/12/12 14:05:30 [brg_local_1:3] Closing connection...
2019/12/12 14:05:30 [clock.wallclock_main:3] Streaming loop stopped.
2019/12/12 14:05:30 [main:3] Threads terminated.
2019/12/12 14:05:30 [threads:3] Shutting down scheduler...
2019/12/12 14:05:30 [threads:3] Scheduler shut down.
2019/12/12 14:05:30 [threads:3] Waiting for queue threads to terminate...
2019/12/12 14:05:30 [threads:3] Queues shut down
2019/12/12 14:05:30 [server:3] Closing socket.
2019/12/12 14:05:30 [main:3] Cleaning downloaded files...
2019/12/12 14:05:30 [main:3] Freeing memory...
```

**Comment by SlvrEagle23** [comment]
We'll keep an eye on the upstream progress of this issue as it's handled by Liquidsoap and as soon as they have information on configuration changes, or a fixed version, we will update ASAP.

**Comment by ivellios1988** [comment]
Definitely an upstream issue. It's present on my installation of AzuraCast and yesterday it appeared in my installation of Centova Cast, as well. Liquidsoap doesn't start when I create some mountpoints with OPUS.

By the way, is it possible to downgrade Liquidsoap to some earlier version inside an AzuraCast installation? Or we have to wait until Liquidsoap developers solve the problem?

**Comment by SlvrEagle23** [comment]
@ivellios1988 It's not easy, unfortunately, as even minor releases of Liquidsoap are known to break back compatibility on the scripting language API, which means we have to lock our code generation to a specific minor version (which we then also ship with the app itself).

**Comment by ivellios1988** [comment]
Well, Centova Cast support department just told me a very upsetting fact: they say support for OPUS was removed from Liquidsoap as of version 1.3.7. If it's true, then it's very, very bad.

**Comment by SlvrEagle23** [comment]
@ivellios1988 This is inaccurate; Liquidsoap announced improvements to their OPUS support in the 1.4.0 release, so they haven't dropped support for it at all.

It's possible Centova is suggesting that _they_ no longer support OPUS in newer versions, but Liquidsoap absolutely still does.

**Comment by JackCrispy** [comment]
Any update on this? Still can't get my Opus with OGG working.

**Comment by Vaalyn** [comment]
We've got [confirmation](https://github.com/savonet/liquidsoap/issues/1051#issuecomment-601551595) from the Liquidsoap team that the newest libopus version 1.1.2 in Ubuntu 18.04 is too old and that 1.3 should be the minimum required version of that library.

On April 23, 2020 Ubuntu 20.04 LTS will be released which would be the version we'd update the containers to which has the required 1.3.x version of libopus.

We could wait until that is released to get the updated libopus version or we could pull the 1.3.x version from the 19.04 repositories like we did for a different issue some time back and when we update to 20.04 LTS we remove that again.

@SlvrEagle23 what do you think, should I send a PR to pull the version from 19.04?

**Comment by SlvrEagle23** [comment]
@Vaalyn No PPA for the new one I'm assuming?

If not, I'd take a PR for the 19.04 version just to hold us over for the next month, then we can bump straight up to 20.04 for our Docker images.

**Comment by Vaalyn** [comment]
@SlvrEagle23 well, at the moment there is a deb source from the LS team but they do not recommend it to be used in production yet: https://www.liquidsoap.info/doc-dev/install.html#debianubuntu

Also I'm not sure what packages are available through that. When trying to open the repo in the browser I only get an `AccessDenied` error.

I'll send you a PR later today.

**Comment by CicoZhang** [comment]
Is there a quick fix now? :-)

**Comment by SlvrEagle23** [comment]
Quick fix has been applied, leaving this issue open until Ubuntu 20.04 is out so we can upgrade directly to that on our Docker containers.

**Comment by SlvrEagle23** [comment]
The long-term fix has been applied now as of our upgrade to Ubuntu 20.04 on our Docker containers. This issue should no longer be a problem with recently updated installations.

**Comment by CicoZhang** [comment]
Ubuntu 18.04 LTS Linode server, jut updated the container to v.0.10.2 (the container should be 20.04, right?), enable OPUS at Mount Points, after restarting, the radio is off the air, if I click "skip song", I would receive such a message : "Telnet failure: Connection refused (111)"

```
2020/05/15 16:49:17 [clock.wallclock_main:2] Source en_local_2 failed while streaming: Failure("Unknown opus error")!
2020/05/15 16:49:17 [clock.wallclock_main:3] Raised by primitive operation at file "opus.ml", line 181, characters 34-63
2020/05/15 16:49:17 [clock.wallclock_main:3] Called from file "ogg_formats/opus_encoder.ml", line 61, characters 9-108
2020/05/15 16:49:17 [clock.wallclock_main:3] Called from file "ogg_formats/opus_encoder.ml", line 66, characters 14-24
2020/05/15 16:49:17 [clock.wallclock_main:3] Called from file "ogg_formats/ogg_muxer.ml", line 217, characters 10-41
2020/05/15 16:49:17 [clock.wallclock_main:3] Called from file "encoder/ogg_encoder.ml", line 171, characters 27-50
2020/05/15 16:49:17 [clock.wallclock_main:3] Called from file "list.ml", line 110, characters 12-15
2020/05/15 16:49:17 [clock.wallclock_main:3] Called from file "encoder/ogg_encoder.ml", line 173, characters 8-26
2020/05/15 16:49:17 [clock.wallclock_main:3] Called from file "outputs/output.ml", line 254, characters 24-44
2020/05/15 16:49:17 [clock.wallclock_main:3] Called from file "outputs/output.ml", line 181, characters 8-24
2020/05/15 16:49:17 [clock.wallclock_main:3] Called from file "clock.ml", line 160, characters 17-25
2020/05/15 16:49:17 [en_local_2:3] Closing connection...
2020/05/15 16:49:17 [en_requests_fallback:3] Switch to en_autodj_fallback.
2020/05/15 16:49:17 [main:3] Shutdown started!
2020/05/15 16:49:17 [main:3] Waiting for main threads to terminate...
2020/05/15 16:49:17 [en_autodj_fallback:3] Switch to en_cue_next_song.
2020/05/15 16:49:17 [lang:3] AzuraCast Feedback Response: OK
2020/05/15 16:49:17 [en_local_1:3] Closing connection...
2020/05/15 16:49:17 [lang:3] DJ Source disconnected! Current live DJ: 
2020/05/15 16:49:17 [server:3] New client: 172.19.0.6.
2020/05/15 16:49:17 [server:3] Client 172.19.0.6 disconnected.
2020/05/15 16:49:17 [lang:3] AzuraCast Live Disconnected Response: true
2020/05/15 16:49:17 [harbor:3] Removing mountpoint '/' on port 8015
2020/05/15 16:49:17 [harbor:3] Nothing more on port 8015: closing sockets.
2020/05/15 16:49:17 [clock.wallclock_main:3] Streaming loop stopped.
2020/05/15 16:49:17 [main:3] Threads terminated.
2020/05/15 16:49:17 [threads:3] Shutting down scheduler...
2020/05/15 16:49:17 [threads:3] Scheduler shut down.
2020/05/15 16:49:17 [threads:3] Waiting for queue threads to terminate...
2020/05/15 16:49:17 [threads:3] Queues shut down
2020/05/15 16:49:17 [server:3] Closing socket.
2020/05/15 16:49:17 [main:3] Cleaning downloaded files...
2020/05/15 16:49:17 [main:3] Freeing memory...
```

```
# Local Broadcasts
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=64, id3v2=true), id="en_local_1", host = "127.0.0.1", port = 8010, password = "(PASSWORD)", mount = "/radio.mp3", name = "", description = "Meditation Live Session via audio streaming.", genre = "", url = "", public = false, encoding = "UTF-8", radio)
output.icecast(%opus(samplerate=48000, bitrate=128, vbr="none", application="audio", channels=2, signal="music", complexity=10, max_bandwidth="full_band"), id="en_local_2", host = "127.0.0.1", port = 8010, password = "(PASSWORD)", mount = "/radio-192.mp3", name = "", description = "Meditation Live Session via audio streaming.", genre = "", url = "", public = false, encoding = "UTF-8", radio)
```
