### ISSUE TITLE
station/1/reports/duplicates

### ISSUE THREAD

**Issue by Takumi86ES** [AzuraCast/AzuraCast#2208]
Error 500 -> /station/1/reports/duplicates

**Comment by Takumi86ES** [comment]
?

**Comment by SlvrEagle23** [comment]
@Takumi86ES We need a little more information about the error you're encountering. Do you see an error message under the 500 error that displays on the page?

**Comment by Takumi86ES** [comment]
When I try to access "duplicate songs"

https://i.gyazo.com/41328e12b885f4756b99ea5076816d90.png

**Comment by Takumi86ES** [comment]
?

**Comment by yarik2720** [comment]
Looks like related to #1839
