### ISSUE TITLE
Scheduled Playlist not playing

### ISSUE THREAD

**Issue by linksilver** [AzuraCast/AzuraCast#221]
I tried several kind of configurations to make Scheduled Playlist work but i cant schedule any playlist, playlist are saved but never played, anyone has the same issue ?

**Comment by linksilver** [comment]
i tried on Ubuntu as in Docker, nothing is playing

**Comment by SlvrEagle23** [comment]
@linksilver Keep in mind that both the playlist scheduled time and days are based on UTC/GMT time, so as to be standard across all servers and users.

If you update your profile and set your local timezone, you will see both the local time and the GMT time when selecting time ranges.

**Comment by linksilver** [comment]
so i finally made it work, i  had to stop my containers, then restart them and my playlists are played, still no issue for the ubuntu version, i'll try some more during the day (here its 3:51 AM) :D 

@SlvrEagle23 yeah i know i made several playlist which should play all day long

**Comment by SlvrEagle23** [comment]
@linksilver That's strange! Maybe the station just needed a restart.

**Comment by linksilver** [comment]
i got it in fact i had to do a `git reset --hard cbefa9e35ee0ca0432a98c97d69cfcd8233d0a2b` to make it works sorry i forgot to write it 
probably there is a bug somewhere in the last Scheduled playlist with days
so i decided to try to the last commit before you changed scheduled playlist
does scheduled playlist works for you with current master ?

**Comment by SlvrEagle23** [comment]
@linksilver When you get a chance, check to see if that latest commit fixed it.

**Comment by linksilver** [comment]
it seems to work :)

**Comment by linksilver** [comment]
it seems to play only one track then it stops playing anything (tested on ubuntu)

**Comment by linksilver** [comment]
still the same issue, i dont understand from where does it comes, i reinstall it on a clean ubuntu system at least 5 time
