### ISSUE TITLE
problem after server reboot

### ISSUE THREAD

**Issue by vipercast** [AzuraCast/AzuraCast#2210]
# instal docker
# ubuntu 16
i did a restart on the server  and azura cast never opened.. can you help me please?

**Comment by SlvrEagle23** [comment]
@vipercast We need some more information about your installation. What errors are you encountering?

If you try running:

```
cd /var/azuracast
docker-compose up -d
```

...do you run into any issues?

**Comment by vipercast** [comment]
@SlvrEagle23 the problem has been fixed.. I had a problem with the server.. azuracast had no problem. thank you for your reply :)
