### ISSUE TITLE
fix AzuraCast.ERROR: File not found at path: 

### ISSUE THREAD

**Issue by echickenpl** [AzuraCast/AzuraCast#2213]
Hi 

I have this message in my new installation on Ubuntu

_AzuraCast.ERROR: Exception when processing message type App\Message\AddNewMediaMessage: Media path "media://PopRock Jamendo/1473724-1473724-Taylor Clark-Im So Blessed.mp3" not found. [] []_

in the panel I cannot enter the folder with this file

how to fix it help me please

**Comment by SlvrEagle23** [comment]
@echickenpl Did you upload the file via FTP? If you upload via the web panel it should strip the unusual characters like the one you're seeing there instead of the apostrophe. If you uploaded it via FTP, you can just reconnect via FTP again and rename the file to something more OS compliant.
