### ISSUE TITLE
Incorrect time stamp on API

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2214]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
The time stamp on the API is incorrect and always display the GMT time zone
regardless the channel profile setting

**Comment by SlvrEagle23** [comment]
@eranwo Do you mean the UNIX timestamps? Those are always meant to be in UTC, regardless of the current localized time zone for the station. It's the job of the rendering client (i.e. in AzuraCast's case, the JavaScript frontend) to handle the time zone localization from that timestamp.
