### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#222]
Hello,

I am  getting this error when updating on a traditional  ubuntu 16 installation.

TASK [azuracast-radio : Install LiquidSoap Dependencies] ***********************
failed: [localhost] (item=[u'libpcre3-dev', u'libfdk-aac-dev', u'libmad0-dev', u'libmp3lame-dev', u'libtag1-dev', u'libfaad-dev', u'libflac-dev', u'pkg-config', u'm4', u'aspcud']) => {"cache_update_time": 1504305305, "cache_updated": false, "failed": true, "item": ["libpcre3-dev", "libfdk-aac-dev", "libmad0-dev", "libmp3lame-dev", "libtag1-dev", "libfaad-dev", "libflac-dev", "pkg-config", "m4", "aspcud"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'libpcre3-dev' -o APT::Install-Recommends=no' failed: E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. \n", "rc": 100, "stderr": "E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. \n", "stderr_lines": ["E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. "], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/var/azuracast/www/util/ansible/update.retry

PLAY RECAP *********************************************************************
localhost                  : ok=15   changed=1    unreachable=0    failed=1

**Comment by SlvrEagle23** [comment]
@surihost Okay, so what happens when you run `sudo dpkg --configure -a`?

**Comment by surihost** [comment]
Yes worked now :)
