### ISSUE TITLE
Can you track DJ connection times?

### ISSUE THREAD

**Issue by JoshRiley** [AzuraCast/AzuraCast#2220]
Loving the software so far after a move from CentovaCast! 

Is it possible to track how long a DJ has been connected for automatically? Is it possible to track the times they connect/disconnect at without scanning through the logs daily?

TIA

**Comment by SlvrEagle23** [comment]
@JoshRiley This isn't currently possible, but it's a very reasonable request and is one that we could definitely consider implementing in the software later.

You should submit this request over on our [feature request system](https://features.azuracast.com/).
