### ISSUE TITLE
Please see older issue 2132

### ISSUE THREAD

**Issue by hottweelz** [AzuraCast/AzuraCast#2221]
**Using Docker installation method**
YES

**Host Operating System**

UBUNTU 18.04

**Describe the bug**
Please see older issue 2132

**Expected behavior**
Scheduled Show should play accordingly.

We are experiencing this exact issue, however, if we update a show in the playlist, we have to "restart" autodj for it to work.... everyone else has confirmed that this is fine?

Restarting AUTODJ is not good. We are on the latest version

**Comment by SlvrEagle23** [comment]
@hottweelz Please provide some additional details about your setup, including screenshots of your playlist configuration. You should comment as a reply to issue #2132 itself.

**Comment by hottweelz** [comment]
I did reply to issue #2132 and I'm not sure what "additional details" you'd need.

With all due respect the statement "this exact issue" kind of speaks for itself.

You want a screenshot of a scheduled playlist?  

Also, again, with all due respect, don't close out tickets because you believe they're not priority.
<img width="837" alt="Screen Shot 2019-12-27 at 3 04 48 PM" src="https://user-images.githubusercontent.com/52544955/71530910-55fea000-28ba-11ea-8687-5483950d90fa.png">
<img width="826" alt="Screen Shot 2019-12-27 at 3 04 32 PM" src="https://user-images.githubusercontent.com/52544955/71530911-55fea000-28ba-11ea-9844-b012c05e3647.png">

**Comment by SlvrEagle23** [comment]
@hottweelz I didn't close this ticket because it isn't a priority, I closed it because it is entirely a duplicate of an existing issue, which should be used to track progress on fixing the issue.

I need screenshots of the scheduling panel to see what (if any) custom settings you may have enabled for the playlist, as those may have impacted the scheduling. Settings like "Manual AutoDJ Mode" on the station also may affect this.

**Comment by hottweelz** [comment]
2132 is closed... you currently have NO OPEN ISSUE for this ISSUE... if that makes any sense.

**Comment by biguenique** [comment]
@hottweelz As stated in the notice below them _AutoDJ Scheduling Options_ are handled by Liquidsoap, thus they require an AutoDJ restart for the Liquidsoap script to be updated and the changes to be taken into account. If you want to avoid restarting your AutoDJ, you have to design your scheduling without relying on any of those options.
