### ISSUE TITLE
We want to create an azuracast German-speaking forum

### ISSUE THREAD

**Issue by Radio-Quergedacht** [AzuraCast/AzuraCast#2222]
We want to create an azuracast German-speaking forum and want to ask if you can use the logo for it

Link forum https://azuracast-deutschland.info/

**Comment by SlvrEagle23** [comment]
@Radio-Quergedacht You can use the logo anywhere you want. :)

Basically, our brand rules are about the same as most open-source projects: you can use our name and logo anywhere you want, but you can't claim to be AzuraCast yourselves (or make a copy of AzuraCast and distribute it as the same thing).

**Comment by ETChatSmileyBox** [comment]
Thank you

**Comment by Radio-Quergedacht** [comment]
Thank you
