### ISSUE TITLE
Incorrectly parsing hypens/dashes in song titles

### ISSUE THREAD

**Issue by smilingpeanut** [AzuraCast/AzuraCast#2223]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04.3 LTS

**Describe the bug**
When streaming from a live source, hyphens/dashes (-) in the song title are being parsed in such a way that the last word of the title is set as the title, and the artist name is actually set as [ARTIST] - [FIRST PART OF SONG TITLE]. In this example, the track is:

Artist: Hot Chip
Title: Hungry Child - Edit

AzuraCast is seeing this as:

Artist: Hot Chip - Hungry Child
Title: Edit

**To Reproduce**
1. Stream a song with a dash in the title.
2. Check the Song Playback Timeline to see how the track is parsed. This is also reflected in the Icecast now-playing display.

**Expected behavior**
I'm expecting for the song title to be parsed appropriately for accurate SoundExchange reporting.

**Relevant Logs**
2019/12/16 10:27:02 [lang:3] Authenticating DJ: source
2019/12/16 10:27:02 [lang:3] AzuraCast DJ Auth Response: true
2019/12/16 10:27:02 [camomile:3] Failed to convert "Hot Chip - Hungry Child - Edit": unknown input encoding UTF8
2019/12/16 10:27:02 [camomile:3] Failed to convert "song": unknown input encoding UTF8
2019/12/16 10:27:02 [noco-fm_input_streamer:3] New metadata chunk ? -- Hot Chip - Hungry Child - Edit.

**Screenshots**
[Screenshot of Song Playback Timeline entry](https://cloudup.com/ibtY99aMDgE)

**Device(s):**
 - Device: Desktop
 - OS: macOS Catalina
 - Browser: Chrome 
 - Version: 78.0.3904.108

**Additional context**
Streaming to AzuraCast server is coming from Nicecast for macOS.

**Comment by biguenique** [comment]
Yes, I agree that title parsing from a live source could be improved -- maybe customized?

**Comment by biguenique** [comment]
Devs: this is the sign of a 'greedy' regular expression that could be made 'ungreedy': is there any known band or artist out there that has <space>+<hyphen>+<space> in its name?

**Comment by SlvrEagle23** [comment]
@smilingpeanut So I've investigated this, and I want to share some additional information about this situation.

AzuraCast uses a standalone library that we also create and maintain called NowPlaying, to parse the JSON/XML feeds coming from SHOUTcast/Icecast. Depending on how metadata is sent over to Icecast, it's possible that a separate `artist` and `title` can be sent over (as we do with our own AutoDJ's media); if we detect that, we'll always use those fields directly instead of trying to parse the artist and title from a single string.

In some cases, though, some broadcasting software only sends over a single string in the form of "Artist - Title". We parse that using this section of code: https://github.com/AzuraCast/nowplaying/blob/master/src/Adapter/AdapterAbstract.php#L165-L196

Since we have no way of knowing which hyphen is the one separating Artist and Title, and which ones are separators within the artist/title, we assume that any extra hyphens are part of the artist, since this seems to happen a lot more often than the opposite.

I'm going to keep this issue open to see about refining this a bit.

**Comment by smilingpeanut** [comment]
@SlvrEagle23 This is really good information to know. Thank you for following up. Do you by chance know which broadcasting software sends over a single string vs. a full set of metadata?

**Comment by SlvrEagle23** [comment]
@smilingpeanut I'm afraid I don't really know, as I haven't experimented with this property on streaming software before.

**Comment by smilingpeanut** [comment]
@SlvrEagle23 I've been doing some research, and it seems that every streaming client available for macOS sends metadata as a single string. Haven't tested Windows yet. That said, is there or can there be a way to update the now playing data via the API? I don't see a route that exists currently for this. Ideally, it would be something that could be passed via a GET request, ie.

> https://hostname.tld/api/station/1/update_now_playing?title=Title&artist=Artist&album=Album&year=2019&label=Whatever%20Records

I'd be happy to work on this as a PR if needed.

**Comment by SlvrEagle23** [comment]
@smilingpeanut I have no problem with that idea at all. Since it's modifying something with the station, and to comply with RESTful standards, ideally it would be an authenticated POST/PUT request, but under the hood it should be entirely possible.

**Comment by smilingpeanut** [comment]
@SlvrEagle23 Yeah, that makes sense. I only suggested a GET request due to the fact that many radio automation apps (such as Radiologik DJ, which we use for our station) support passing a GET request. Perhaps this could authenticate using an API key as a parameter in the request.

**Comment by SlvrEagle23** [comment]
@smilingpeanut We already do support API key authentication via URL parameter specifically for compatibility purposes, so I'd be OK with adding a GET endpoint strictly to make this available to as much software as possible.

Perhaps this issue should be reopened or a new one should be created to track this separate item.

**Comment by smilingpeanut** [comment]
@SlvrEagle23 Done! #2249.

Also, I see that there's a feature for getting the ISRC from Spotify's API but that it's currently disabled. We could also look and re-enabling this feature to get ISRC data, which might reduce the need for the new API endpoint. What is needed for that? Would each AzuraCast installation need a Spotify API key to make requests? If that's the case, we could add a configuration option to store Spotify authentication data.

**Comment by SlvrEagle23** [comment]
@smilingpeanut It's possible that we could make that a user-configurable setting. I don't like having to rely on third party services that are proprietary like that, but I'm not sure there's any better ISRC lookup tool than that (and there's no neutral official one).

**Comment by smilingpeanut** [comment]
> @smilingpeanut It's possible that we could make that a user-configurable setting. I don't like having to rely on third party services that are proprietary like that, but I'm not sure there's any better ISRC lookup tool than that (and there's no neutral official one).

I'm not crazy about that either, but it's probably the best solution, at least until SoundExchange provides an API for their ISRC database. Apple Music's API also provides ISRC data, but you have to be an Apple developer to use it.

**Comment by biguenique** [comment]
@SlvrEagle23 
> Since we have no way of knowing which hyphen is the one separating Artist and Title, and which ones are separators within the artist/title, we assume that any extra hyphens are part of the artist, since this seems to happen a lot more often than the opposite.

Yes, hyphens are common in artist names, but the sequence SPACE + HYPHEN + SPACE is not really common, but is more likely to happen in titles. Note that 'Artist - Title' are always shown separated by this very sequence.

Changing `$delimiter = '-'` to `$delimiter = ' - '` in function `getSongFromString` would prevent matching a single hyphen (not surrounded by spaces) in the artist name.

You can then change the code to only feed the artist name with the first part and re-assemble the song title correctly with the remaining parts :
`
        // Artist is the first element, title is all other elements (artists are not likely to have hyphens surrounded by spaces).
        $artist = trim(array_shift($string_parts));
        $title = trim(implode($delimiter, $string_parts));
`

That would likely solve the issue.

**Comment by SlvrEagle23** [comment]
@biguenique On Icecast, we can safely assume " - " is the delimiter, but on SHOUTcast we actually can't, as several SHOUTcast versions return "-" instead of " - " when separating title and artist. This is why we originally had this set up the way we did.

Of course, this issue is a nonissue on Icecast installations for the same reason you mentioned: because " - " is much less likely to happen inside either an artist or title name, we end up with fewer confusing situations.

**Comment by biguenique** [comment]
Mmh, I see.... Any point in the code where we can discriminate Icecast from Shoutcast?

**Comment by SlvrEagle23** [comment]
@biguenique We already do. The Icecast adapters calling that code pass a delimiter of " - " instead.
