### ISSUE TITLE
Meta info not displaying on stream

### ISSUE THREAD

**Issue by JCLIMMA** [AzuraCast/AzuraCast#2225]
So I hate writing issue problems and never do... That said, I have searched for days now, deleted my DO droplet and reinstalled, but I am still having the same issue.

When using any of the streaming links, none of the metadata will display. No errors, just blank. 
![WMS local stream](https://user-images.githubusercontent.com/48605896/70961796-83d91e80-2048-11ea-99f4-debcf3a6a2e9.png)
![WMS icecast stream](https://user-images.githubusercontent.com/48605896/70961806-8f2c4a00-2048-11ea-9ee4-61925674464d.png)

I also know it is not an issue with how I uploaded the files because it displays fine in the public page.
![WMS public page](https://user-images.githubusercontent.com/48605896/70961835-abc88200-2048-11ea-93bd-73dc60074dd1.png)

Any help would be appreciated. My eyes are starting to bleed...

**Comment by yarik2720** [comment]
Chrome browser doesn't shows icy-metadata itself. Try to play your stream on media player, like Aimp

**Comment by JCLIMMA** [comment]
> Chrome browser doesn't shows icy-metadata itself. Try to play your stream on media player, like Aimp

That's for replying, but that isn't working either.
![Screenshot_20191217-080319](https://user-images.githubusercontent.com/48605896/71001989-04793880-20a4-11ea-92b5-59b71c460dfa.png)

**Comment by yarik2720** [comment]
I meant player AIMP for PC, not phone. I'm not sure if Android version can play icecast streams

**Comment by JCLIMMA** [comment]
> I meant player AIMP for PC, not phone. I'm not sure if Android version can play icecast streams

The PC version was unable to load as well unfortunately.

**Comment by smilingpeanut** [comment]
Your metadata is displaying just fine in players that support it...

![Screen Shot 2019-12-18 at 11 14 01 AM](https://user-images.githubusercontent.com/1864093/71111930-b473a200-2187-11ea-9354-28cf117a9493.png)

**Comment by yarik2720** [comment]
I also tested your stream, and it shows metadata well:
![AIMP_2019-12-18_21-18-28](https://user-images.githubusercontent.com/1839978/71112181-07774480-21dc-11ea-8997-94b913a769ac.png)

**Comment by JCLIMMA** [comment]
Thank you both for the help.
