### ISSUE TITLE
Does AzuraCast support Shoutcast v2

### ISSUE THREAD

**Issue by radio2019** [AzuraCast/AzuraCast#2226]
It seems as if Winamp doesn't accept the test stream of AzuraCast (I know Winamp is outdated, but still a lot of people use it).
That's why I would like to ask if AzuraCast accepts Shoutcast v2 or only outdated v1?

**Comment by jayhill90** [comment]
Did you already manually install the Shoutcast 2 binary as per https://github.com/AzuraCast/AzuraCast/blob/1b0e7cdde6b1415828b0435e8fb3acca38e68923/config/forms/install_shoutcast.php#L14

**Comment by radio2019** [comment]
Thanks for asking.
To be honest: We are still in search of a cheap hosting provider where we
can rent a VPS with 200 GB storage.

**Comment by jayhill90** [comment]
Digital Ocean has 4GB Memory and 2 core server with 80 gb of storage + an additional 250gb of block storage for $45 a month.

**Comment by jayhill90** [comment]
@SlvrEagle23 I think this can be closed. Shoutcast v2 is supported, and @radio2019 is just looking for hosting providers at this point.
