### ISSUE TITLE
Raspberry PI 4

### ISSUE THREAD

**Issue by NetroxCr4fter** [AzuraCast/AzuraCast#2227]
Hello,
i wanna install but i dont find the right Ubuntu version. I hvae a Raspberry PI 4 with 4 GB Ram and i tested Ubuntu 19.10, 18.04 and 16.04. Can someone send me a direkt Link to download the right version of Ubuntu?

**Comment by jayhill90** [comment]
It runs fine on my server with Ubuntu 18.04. Installation is easily handled by following the guide. https://www.azuracast.com/install/#installing

**Comment by NetroxCr4fter** [comment]
Yes, gut I need a Download link for Ubuntu 18.04 which works on my Raspberry PI

**Comment by jayhill90** [comment]
https://wiki.ubuntu.com/ARM/RaspberryPi

**Comment by SlvrEagle23** [comment]
@NetroxCr4fter 

Specifically, this is the version that works with AzuraCast:
http://cdimage.ubuntu.com/releases/bionic/release/ubuntu-18.04.3-preinstalled-server-arm64+raspi3.img.xz

It says it only works with Raspberry Pi up to 3, so I'm not sure if it'll work with the 4. I need to investigate that (though I don't have a RPi 4 of my own).

**Comment by ogrenci01** [comment]
@NetroxCr4fter 

It is here and check it

https://ubuntu.com/download/raspberry-pi
