### ISSUE TITLE
Error Brazilian language

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#2231]
After the last azuracast update the panel is not showing the language correctly. This changed functions such as playlist management and file name editing in file manager. Even editing the country language file correctly does not correct.

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli I believe the strings have changed in small ways that make it so that the existing translations may not work exactly. The easiest route would be to submit updated strings through [CrowdIn](https://translate.azuracast.com/), where we can approve them and then officially get them integrated into the app.

If you're editing the strings locally, there are a few steps you have to go through to convert the translation files into files that are usable by our software. You can find some more information on the subject here: https://www.azuracast.com/developers/#setting-up-a-local-environment

**Comment by Marcioghiraldelli** [comment]
I could not be able to understand these issues.
I translated the configuration file normally, before it worked, I just inserted the existing file changes and the system does not accept. stay english yet. I ran the command

# Backend
./docker.sh cli locales: import

# Frontend
./docker.sh static npm run import-locales

And the error and nothing happens.
Please can you explain me better how to fix this already with azuracast installed on my server?

**Comment by Marcioghiraldelli** [comment]
Hello,
Today I woke up early to perform this task of translating to PT, I made a large part of the translation file. I hope my work has been satisfactory and whatever I can contribute to the system I will do!
If you can check this question I appreciate it immensely.

https://translate.azuracast.com/translate/azuracast/8/enus-ptbr

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli I discovered the problem: we had an issue with our automatic updates on CrowdIn, so we were using an out-of-date version of our original translation strings. This is why so many strings weren't translated in the application.

I've resolved the issue and updated our automatic integration, so it will now properly update as new versions are added. If you don't mind submitting new translations for the added strings, I will get them approved and added to the application as soon as possible.

**Comment by Marcioghiraldelli** [comment]
Hello,
I do the translation yes!
Whatever I can do to help with the project I will do!
Great end of year for you and your family.

Em dom., 29 de dez. de 2019 às 12:08, SlvrEagle23 <notifications@github.com>
escreveu:

**Comment by Marcioghiraldelli** [comment]
Hello,
It took me a little longer to do almost 100% of the translation. I tried to
make the best of the translation. I hope to please everyone. If you need
more help you can count on me. I have finished all the translation.
Big hug and good new year.

Em dom., 29 de dez. de 2019 às 12:08, SlvrEagle23 <notifications@github.com>
escreveu:

**Comment by Marcioghiraldelli** [comment]
Hello,
It took me a little longer to do almost 100% of the translation. I tried to make the best of the translation. I hope to please everyone. If you need more help you can count on me. I have finished all the translation.
Big hug and good new year.

**Comment by Marcioghiraldelli** [comment]
Please just let me know when I can update my azuracast. Good sunday.

Em dom., 29 de dez. de 2019 às 12:08, SlvrEagle23 <notifications@github.com>
escreveu:

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli I have added the full PT_BR frontend translations to the app. Update and you should see them take effect.

**Comment by Marcioghiraldelli** [comment]
Hello,
In this update there are still things that do not work correctly. For
example, where it says that This station's time zone is currently, does not
show the chosen time zone and is only% s.

In the Music Files part, When you click on EDIT on a song, much information
there does not translate and remains in English.

Example below, none have been translated:
File Name
Song artist
Song Lyrics
Song title
Song Album
ISRC
and the text below that is
International Standard Recording Code, used for licensing reports.

In Album Art
Replace Album Cover Art (Not translated)

In advanced playback settings
No options have been translated.

I remember you translated all these parts, but did not enter the
translation. I didn't get to update my azuracast, I'm following the example
on page https://demo.azuracast.com/station/1/files

On this page: https://demo.azuracast.com/station/1/playlists
in Music 16 (42.1 minutes) and not translated instead of minutes is minutes
or hours in en

In the same page above
If disabled, the playlist will not be included in radio playback, but can
still be managed.
Not translated.

Control how this playlist is handled by AutoDJ.
Warning: <b> Warning: </b> These functions are built into Liquidsoap and
will affect how AutoDJ works.
Translated, but <b> Warning: </b> is appearing <b> and does not bring any
effect.

If auto-assignment is enabled, use this playlist as one of the targets for
songs to be redistributed into. This will overwrite the existing contents
of this playlist.
(Not translated)

In source
Song-Based Playlist
Song Playback Order
Shuffled
Random
Sequential
Not translated

If requests are enabled for your station, users will be able to request
media that is on this playlist.
Not translated

Enable this setting to prevent metadata from being sent to the AutoDJ for
files in this playlist. This is useful if the playlist contains jingles or
bumpers.
Not translated

In Schedule
This station's time zone is currently% s.
Also the error and does not show time zone getting only% s

Start time
To play once per day, set the start and end times to the same value.

End time
If the end time is before the start time, the playlist will play overnight.

Start Date
To set this schedule to run only within a certain date range, specify a
start and end date.

End Date
In scheduling, all of the above were not translated.

Scheduled Play Days of Week
Leave blank to play on every day of the week.
The one above didn't go either.

I also noticed that at the end of each page also does not translate
Showing 1 to 1 of 1 entries
It's in English too.

Em seg., 30 de dez. de 2019 às 01:50, SlvrEagle23 <notifications@github.com>
escreveu:

**Comment by Marcioghiraldelli** [comment]
Hello @SlvrEagle23 SlvrEagle23
In this update there are still things that do not work correctly. For example, where it says that This station's time zone is currently, does not show the chosen time zone and is only% s.

In the Music Files part, When you click on EDIT on a song, much information there does not translate and remains in English.

Example below, none have been translated:
File Name
Song artist
Song Lyrics
Song title
Song Album
ISRC
and the text below that is
International Standard Recording Code, used for licensing reports.

In Album Art
Replace Album Cover Art (Not translated)

In advanced playback settings
No options have been translated.

I remember you translated all these parts, but did not enter the translation. I didn't get to update my azuracast, I'm following the example on page https://demo.azuracast.com/station/1/files

On this page: https://demo.azuracast.com/station/1/playlists
in Music 16 (42.1 minutes) and not translated instead of minutes is minutes or hours in en

In the same page above
If disabled, the playlist will not be included in radio playback, but can still be managed.
Not translated.

Control how this playlist is handled by AutoDJ.
Warning: <b> Warning: </b> These functions are built into Liquidsoap and will affect how AutoDJ works.
Translated, but <b> Warning: </b> is appearing <b> and does not bring any effect.

If auto-assignment is enabled, use this playlist as one of the targets for songs to be redistributed into. This will overwrite the existing contents of this playlist.
(Not translated)

In source
Song-Based Playlist
Song Playback Order
Shuffled
Random
Sequential
Not translated

If requests are enabled for your station, users will be able to request media that is on this playlist.
Not translated

Enable this setting to prevent metadata from being sent to the AutoDJ for files in this playlist. This is useful if the playlist contains jingles or bumpers.
Not translated

In Schedule
This station's time zone is currently% s.
Also the error and does not show time zone getting only% s

Start time
To play once per day, set the start and end times to the same value.

End time
If the end time is before the start time, the playlist will play overnight.

Start Date
To set this schedule to run only within a certain date range, specify a start and end date.

End Date
In scheduling, all of the above were not translated.

Scheduled Play Days of Week
Leave blank to play on every day of the week.
The one above didn't go either.

I also noticed that at the end of each page also does not translate
Showing 1 to 1 of 1 entries
It's in English too.
