### ISSUE TITLE
Audio Headache in PC advanced config

### ISSUE THREAD

**Issue by thiagocrossman** [AzuraCast/AzuraCast#2234]
PC with 4gb memory distorted audio causing a headache when listening..

Have a solution?

**Comment by biguenique** [comment]
@thiagocrossman Any actual stream we can listen to?

**Comment by thiagocrossman** [comment]
> @thiagocrossman Any actual stream we can listen to?

200.187.173.73:8000

**Comment by thiagocrossman** [comment]
> @thiagocrossman Any actual stream we can listen to?

http://200.187.173.73:8000/on

**Comment by biguenique** [comment]
@thiagocrossman I can't hear anything wrong with the stream. Can you describe the problem?

It seems to me that your stream is heavily compressed, giving it a 'commercial' tone, is this your issue? You can try disabling _Apply Compression and Normalization_ in _Edit Profile_ > _AutoDJ_ and see if it solves your issue.

**Comment by thiagocrossman** [comment]
> @thiagocrossman I can't hear anything wrong with the stream. Can you describe the problem?
> 
> It seems to me that your stream is heavily compressed, giving it a 'commercial' tone, is this your issue? You can try disabling _Apply Compression and Normalization_ in _Edit Profile_ > _AutoDJ_ and see if it solves your issue.

It worked, thanks very much.

**Comment by thiagocrossman** [comment]
> @thiagocrossman I can't hear anything wrong with the stream. Can you describe the problem?
> 
> It seems to me that your stream is heavily compressed, giving it a 'commercial' tone, is this your issue? You can try disabling _Apply Compression and Normalization_ in _Edit Profile_ > _AutoDJ_ and see if it solves your issue.

Is compression similar to loudness using in tv?

**Comment by thiagocrossman** [comment]
> > @thiagocrossman I can't hear anything wrong with the stream. Can you describe the problem?
> > It seems to me that your stream is heavily compressed, giving it a 'commercial' tone, is this your issue? You can try disabling _Apply Compression and Normalization_ in _Edit Profile_ > _AutoDJ_ and see if it solves your issue.
> 
> It worked, thanks very much.

Is Compression and Normalization similar to loudness using in tv

**Comment by biguenique** [comment]
Normalization tries to 'normalize' the overall loudness of the signal around a certain level. In Liquidsoap, it works more like an AGC (Automatic Gain Control), raising and lowering the gain depending on the current sound level to get a more uniform loudness between songs. It is not ideal since it also changes the gain _within_ the songs.

Compression basically cranks up the softer sounds to bring a louder perceptual sound within a limited dynamic band. This gives the typical sound of commercial FM stations, but it kills dynamic range when overused. It works well for pop music, but not so well for more 'subtle' music.

And yes, compression is the main explanation for TV commercials souding so loud, as well as the _loudness war_ for music recordings released in the '90s and later.

**Comment by thiagocrossman** [comment]
> Normalization tries to 'normalize' the overall loudness of the signal around a certain level. In Liquidsoap, it works more like an AGC (Automatic Gain Control), raising and lowering the gain depending on the current sound level to get a more uniform loudness between songs. It is not ideal since it also changes the gain _within_ the songs.
> 
> Compression basically cranks up the softer sounds to bring a louder perceptual sound within a limited dynamic band. This gives the typical sound of commercial FM stations, but it kills dynamic range when overused. It works well for pop music, but not so well for more 'subtle' music.
> 
> And yes, compression is the main explanation for TV commercials souding so loud, as well as the _loudness war_ for music recordings released in the '90s and later.

thanks very much. you are awesome

**Comment by SlvrEagle23** [comment]
Thank you @biguenique for the detailed explanation, which is entirely correct. :)
