### ISSUE TITLE
Install SSL on Non 443 port - Centos web panel - Vestacp

### ISSUE THREAD

**Issue by onlinegill** [AzuraCast/AzuraCast#2240]
Hi, I am banging my head.  i am able to run azuracast on SSL port 4432  because 443 i used by Centos web panel /  web server. is there anyway i can use SSL on 4432 port so i would use  host.mydomain.com:4432.
or https://demo.azuracast.com/  and https://azuracast.com/   works ?
I tried all methods such as moving ssl certificates to azuracast dir.

Thank you

**Comment by SlvrEagle23** [comment]
@onlinegill If you're using the Docker installation method, you can follow our instructions for [using non-standard ports](https://www.azuracast.com/help/faq_docker.html#use-non-standard-ports) from our web site.

Our web server will still serve SSL over whatever port you specify for HTTPS, though LetsEncrypt automatic setup won't work on non-standard ports.

**Comment by onlinegill** [comment]
> @onlinegill If you're using the Docker installation method, you can follow our instructions for [using non-standard ports](https://www.azuracast.com/help/faq_docker.html#use-non-standard-ports) from our web site.
> 
> Our web server will still serve SSL over whatever port you specify for HTTPS, though LetsEncrypt automatic setup won't work on non-standard ports.

I am running docker installation everything works fine with NON SSL port but webdj need real SSL certificate. due to 443 is used by main server i am not able to setup SSL on port 4432. i tried with stunnel but still can't broadcast through webdj because on playlist 1 i cant upload any music file or it wont show and in playlist 2 sound quality is very poor and i also can not connect to stream even its shows broadcasting . there should be solution because most of people are running websites on server and using host name as there streaming URL such host.mywebsite.com:8000  and this url is in hundreds of phone apps created by people.

**Comment by SlvrEagle23** [comment]
@onlinegill You can absolutely install your own SSL certificate, but LetsEncrypt, the free SSL certificate provider, requires (as a rule) that your service be available on the primary HTTPS port 443.

As a workaround, you can briefly turn off the 443 service, switch your ports out so that AzuraCast uses port 443, generate your SSL certificates, then switch back to using the nonstandard port and restart the normal port 443 service.

This is a limitation that is "upstream" from AzuraCast; that is, we're not deciding to add that limitation ourselves, we're just providing ways to work around the issue when possible.

**Comment by onlinegill** [comment]
> @onlinegill You can absolutely install your own SSL certificate, but LetsEncrypt, the free SSL certificate provider, requires (as a rule) that your service be available on the primary HTTPS port 443.
> 
> As a workaround, you can briefly turn off the 443 service, switch your ports out so that AzuraCast uses port 443, generate your SSL certificates, then switch back to using the nonstandard port and restart the normal port 443 service.
> 
> This is a limitation that is "upstream" from AzuraCast; that is, we're not deciding to add that limitation ourselves, we're just providing ways to work around the issue when possible.

Thank you!!  i am able to get SSL working by switching SSL port as you said but i still can't load music files to webdj and cant broadcast live from there after entering correct user name password it does not go live. any suggestion ?

**Comment by SlvrEagle23** [comment]
@onlinegill You may want to close this issue and make a new one for that. In the new issue, be sure to open your web console (F12 on most browsers) and include any errors that appear.
