### ISSUE TITLE
Engine faild flom last update

### ISSUE THREAD

**Issue by petrix** [AzuraCast/AzuraCast#2241]
Hi at a good time,

From last update I had a problem with web access to admin panel, liquidsoap still working, and playing a good music)) I've trying <./docker update-self&& update> the process catching an error on copriled php file:

![Capture](https://user-images.githubusercontent.com/625733/71539033-8ee05880-293e-11ea-91e1-212b34b6be0b.PNG)

Then I'm trying clean install based on Ubuntu 18.04 and watching those errors:

![Capture-sc2](https://user-images.githubusercontent.com/625733/71539077-889eac00-293f-11ea-9702-4a9723fb2d3b.PNG)

![Capture-sc3](https://user-images.githubusercontent.com/625733/71539098-da473680-293f-11ea-8fa0-e007b059756e.PNG)

Hi catching an error then trying to pool a web image in docker image-file at /var/lib/docker.... because had no space...

Thank you wery mutch!
Merry Crystmass anyone!

**Comment by SlvrEagle23** [comment]
@petrix I'm not sure what would've caused the first error. Sometimes updating again can resolve the issue.

The second issue is fairly self-explanatory: one of your partitions on your system is out of space. Depending on your host (or how you installed Ubuntu if you did it yourself), a lot of space is allocated to the `/home` directory as a separate partition, and the rest of the system is given very little space. To resolve this, you should update your partitions to give more space to the system partition. Many VPSes these days, for the sake of convenience, use a single partition for the entire hard drive, which means whatever space you have available will all be usable to you; this is perfectly fine and is how AzuraCast is often run.
