### ISSUE TITLE
Webdj does not load music files

### ISSUE THREAD

**Issue by onlinegill** [AzuraCast/AzuraCast#2242]
Using docker installation. i am able to go live by entering dj user and password but cant upload music files to playlist 1 and playlist 2. 
I also notice if you use $  in password it wont connect to liquid soap stream.

**Comment by SlvrEagle23** [comment]
@onlinegill Are you seeing any errors via your web console (F12 on most browsers)? If so, include screenshots of those errors here too.

**Comment by onlinegill** [comment]
Browser chrome

```
vue-17e942ea08.min.js:6 TypeError: Cannot read property 'title' of undefined
    at webcaster-137f49b033.js:1
    at a.vt [as _l] (vue-17e942ea08.min.js:6)
    at a.v (webcaster-137f49b033.js:1)
    at a.e._render (vue-17e942ea08.min.js:6)
    at a.r (vue-17e942ea08.min.js:6)
    at fn.get (vue-17e942ea08.min.js:6)
    at fn.run (vue-17e942ea08.min.js:6)
    at un (vue-17e942ea08.min.js:6)
    at Array.<anonymous> (vue-17e942ea08.min.js:6)
    at qe (vue-17e942ea08.min.js:6)
```

**Comment by SlvrEagle23** [comment]
@onlinegill Thank you, that gives us the information we need to look into the issue.

**Comment by onlinegill** [comment]
> @onlinegill Thank you, that gives us the information we need to look into the issue.

No problem please let  me know if there is any solution.

**Comment by SlvrEagle23** [comment]
@onlinegill This should be improved as of the latest update. Try it again and let me know if it helps at all.

**Comment by onlinegill** [comment]
> @onlinegill This should be improved as of the latest update. Try it again and let me know if it helps at all.

Yeah!!! I am able to load files. Is there anyway to keep or show song name there (file name) ? I have to remove to id3 tags due to websites URLs in those file. 
![15787832430353838248699079287111](https://user-images.githubusercontent.com/1947686/72211562-0364dc80-3493-11ea-925e-c90c4a279680.jpg)

**Comment by SlvrEagle23** [comment]
@onlinegill Glad it works now. The error was caused by a title/artist not being present on the file to begin with. You can always use an ID3 editor (even your operating system) to supply an alternate artist/title, and it will use that when you upload it to the WebDJ.
