### ISSUE TITLE
Help Me pls!!!

### ISSUE THREAD

**Issue by nickloud** [AzuraCast/AzuraCast#2244]
How to register a certificate in docker?

**Comment by onlinegill** [comment]
> How to register a certificate in docker?

Did you use docker installation?
Do you have just azuracast on server or any another server also running? Such as Apache etc?
Do you have domain or host name pointing to server or IP?

**Comment by nickloud** [comment]
yes everything is there. I install the certificate and still shows "not protected"

**Comment by onlinegill** [comment]
> yes everything is there. I install the certificate and still shows "not protected"

I had same issue. here is temporary solution for people who uses centos web panel or vestacp etc.

shutdown Apache or whatever web server you have as main webserver.
shutdown docker / azuracast with following command
`Run docker-compose down`
Go to azuracast folder and edit .env  file NOTE it may be hidden file just run following command nano .env  
change http and https ports to default 80 and 443.
save .env file.
Run following 
`docker-compose up -d `
than run following command ( change domain name)

`./docker.sh letsencrypt-create mydomain.example.com`
so till now you should get correct  ssl certificate for Azuracast.
shutdown azuracast again chnage .env file ports to non standard ports 
save .env file and start azuracast docker-compose up -d
now you can start your main webserver. 




than again shutdown

**Comment by Xara** [comment]
Also flush your browser navigation data!
