### ISSUE TITLE
High CPU load and increasing Swap / IO usage

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#2245]
**Using Docker installation method**
Yes

**Host Operating System**
Debian 9

**Describe the bug**
I'm not sure since when this is happening exactly. After some time the `azuracast_web_1` container starts using up more and more IO performance until the CPU get's bogged down with IO wait time.

Here is a screenshot from my Grafana Dashboard showing the Swap Usage over the last 2 days:

![image](https://user-images.githubusercontent.com/13745863/71550424-1b872700-29d0-11ea-90f8-46bd6ffc49b7.png)

and here a screenshot showing the increasing memory usage over the last 2 days:

![image](https://user-images.githubusercontent.com/13745863/71550438-8e909d80-29d0-11ea-9f4a-cb99bab3e9fb.png)

I haven't been able to extract any info about the processes that were running 2 days ago when my installation crumbled on the load. I had to restart the VM since any command got processed extremely slowly if at all.

Liquidsoap and IceCast are showing nothing unusual in their logs apart from some `must catchup` messages due to the load.

Right now my CPU load is showing huge numbers at around `1130` while the CPU usage percentages per core in `htop` look relatively normal varying at around 20-40% each.

The load monitoring in AzuraCast also shows this high load:

![image](https://user-images.githubusercontent.com/13745863/71550484-a4eb2900-29d1-11ea-9886-244a081dfa85.png)

The process list in `htop` shows a lot of `php bin/azuracast.php syn:run long` processes at the moment which is rather strange I think. Normally there should only be one of those, right?
Those processes show with the Status `D` in `htop`, so they are un-interruptible.

See the following screenshot:

![image](https://user-images.githubusercontent.com/13745863/71550493-44102080-29d2-11ea-86b4-952750649012.png)

There are also some pure-ftpd zombie processes:

![image](https://user-images.githubusercontent.com/13745863/71550508-85a0cb80-29d2-11ea-844b-836067403752.png)

Here is the output of `iostat` to see a bit more about the IO statistics:

![image](https://user-images.githubusercontent.com/13745863/71550518-bed93b80-29d2-11ea-905c-b47b3e7bdb0a.png)

The only errors that seem related to that are some timeouts on `php-fpm` processes. There are also some errors in the web container that are complaining about 2 mountpoints which I think are my 2 OPUS mountpoint which I've disabled due to the bug we have with OPUS streams at the moment. But I don't think they are related to this issue.

```
web_1       | Dec 28 23:46:52 6d38c27b63a8 php-fpm[64]: [NOTICE] [pool www] child 19124 exited with code 0 after 580.248992 seconds from start
web_1       | Dec 28 23:46:52 6d38c27b63a8 php-fpm[64]: [NOTICE] [pool www] child 20433 started
```

```
AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>
```

**To Reproduce**
I'm currently not sure how to actually reproduce this.

**Expected behavior**
There shouldn't be such an increase in Swap usage and cpu load.

**Relevant Logs**
[Container Logs.zip](https://github.com/AzuraCast/AzuraCast/files/4007577/Container.Logs.zip)

**Comment by SlvrEagle23** [comment]
@Vaalyn You've got a ton of processes listed as uninterruptably delayed, which is generally due to an IO wait condition.

It seems like stuff is getting backed up waiting for IO, but then more and more tasks keep piling right on top of the existing waiting ones, until things just fail.

I'd worry about whatever disk is running that VM/VPS.

**Comment by SlvrEagle23** [comment]
@Vaalyn it could also be that you're just out of RAM in general, and it's swapping out and causing an IO pileup...you have 3GB of RAM on that box though and that should be plenty sufficient for any standard AzuraCast installation. Really not sure what's causing this one. Could be a memory leak somewhere.

**Comment by Vaalyn** [comment]
> @Vaalyn it could also be that you're just out of RAM in general, and it's swapping out and causing an IO pileup...you have 3GB of RAM on that box though and that should be plenty sufficient for any standard AzuraCast installation. Really not sure what's causing this one. Could be a memory leak somewhere.

The machine has 4GB of RAM so that's even more strange.

Hardware Config in VMWare:
![image](https://user-images.githubusercontent.com/13745863/71551189-69f0f180-29e1-11ea-8521-5d3bb621cfcd.png)

Here is a screenshot of the IOPS Usage of the containers which shows the `web` container using quite a lot. Not sure what it's doing though.

![image](https://user-images.githubusercontent.com/13745863/71551207-dec42b80-29e1-11ea-80bd-c4cd703d3191.png)

**Comment by SC2Mitch** [comment]
I think I faintly recall a similar issue we had on our VPS where Azuracast would just chew through so much CPU load it crippled our VPS and needed us to contact our service provider for remedies, in the end they had to help us directly to fix the problem. (Picture from old logs) 
![image](https://user-images.githubusercontent.com/29955942/71607274-dd286e00-2b6f-11ea-8e2b-946ed4115338.png)

**Comment by Vaalyn** [comment]
The issue seems to be resolved although I'm still not sure what was responsible for it.

My current monitoring:

![image](https://user-images.githubusercontent.com/13745863/75177423-673b2000-5736-11ea-9611-66f5a704de5d.png)
