### ISSUE TITLE
Automated Assignment doesn't starts every n-days

### ISSUE THREAD

**Issue by yarik2720** [AzuraCast/AzuraCast#2246]
**Using Docker installation method**

Yes

**Host Operating System**

Ubuntu 16.04

**Describe the bug**

I have set-up automated autoassignment for every 7 days. But it doesn't updates playlist after 7 days (and even two weeks).
I need to fire manually "Run automated assignment", only after that playlists updates

**Comment by SlvrEagle23** [comment]
@yarik2720 I've improved how automated assignment handles logging in the latest update; you should be able to update and get more information about why automated assignment isn't running normally on your installation.

**Comment by yarik2720** [comment]
```web_1       | 2020/01/11 19:53:43 [error] 78#78: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 286720 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 121" while reading response header from upstream, client: 95.29.183.197, server: localhost, request: "GET /station/1/automation/run HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "noisefm.ru:8443", referrer: "https://noisefm.ru:8443/station/1/automation"
```
Ok, manual Automated Playlist Assignment also fails, now it limits mine `PHP_MEMORY_LIMIT=1024M`.
I have 3 playlists:
1 - weight 5 - 291 tracks
2 - weight 4 - 281 tracks
3 - weight 3 - 2108 tracks

**Comment by yarik2720** [comment]
Manual Automated Playlist Assigment worked after update with fix of #2003 issue. I'll reopen it if not work automatically after a week
