### ISSUE TITLE
High Availability architecture for Azuracast 

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2248]
Is it possible to build a system with 2 or more servers with docker + azuracast that will always be synchronized so that if one server goes down the other server is still alive.

The question is how to perform real-time synchronization between all servers.

**Comment by lalafunn** [comment]
Same question for me.

**Comment by SlvrEagle23** [comment]
@eranwo @lalafunn

Currently, the infrastructure of AzuraCast (in either its Ansible or Docker forms) is basically the setup depicted by this chart:

![AppInfrastructure](https://user-images.githubusercontent.com/6744885/71641355-2bb53580-2c60-11ea-88b7-661a0ac1b6d8.png)

If you wanted to, it's absolutely possible to scale certain components of this setup (namely the mariadb, redis and influxdb databases could be clustered and made highly available), but other components don't currently scale as well.

The web component (that is, the combination of nginx and PHP-FPM) could also be separated, but it would require some additional code on our part to ensure that only one of those containers was the "master" one (handling things like cron tasks as the authoritative instance).

Currently, one of the best ways we have to handle scaling AzuraCast up to handle larger listener volumes is to use [AzuraRelay](https://github.com/AzuraCast/AzuraRelay), which you can install on any number of VPSes, and which will automatically connect back to the "parent" AzuraCast instance and relay one or multiple of its streams. That's an easy way of scaling up without having to deal with the complications introduced by HA scaling.

**Comment by lalafunn** [comment]
Do you recommend to install AzuraRelay on the same machine that Azuracast is installed or to be installed on another one?

**Comment by SlvrEagle23** [comment]
@lalafunn Definitely a different one, as that's the whole idea with high availability: multiple locations around the world allowing for both higher speed and greater redundancy. A lot of people set up a relay on an unmetered provider (like OVH) and then direct all their listener traffic through that relay so they don't rack up bandwidth charges on the main box.

**Comment by eranwo** [comment]
@SlvrEagle23 Thanks for the detailed answer.
Indeed, aururelay is a very good solution for covering a large number of listeners.
But this is only part of the solution because if the primary server falls for some reason or a corrupted database, the relays will stop working as well.
Maybe for not too complicated solution, it's possible to install 2 identical Azuracast servers, one for master server (active server) and the second will be the backup server. All we need now is a script to syncronize the database and the files in real time between the servers.
Then if the primary server goes down, we can switch the DNS to the other server and the system is back online without losing data and at minimizing downtime.
What do you think?

**Comment by SlvrEagle23** [comment]
@eranwo It's definitely possible, though of course those two AzuraCast installations aren't exactly synchronized with one another, but you can always have another one as a failover for the first one.

Currently, since that's the only real answer to the high-availability question, I'm closing this issue as this is as much information as I can provide at the moment. :)
