### ISSUE TITLE
New DNAS Version Available: 2.5.5.732

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#225]
Hello,

Please update the Shoutcast DNAS to the latest.

**Comment by surihost** [comment]
I just updated to the latest version of azuracast.I notice now the total listener showing 0 all the time.
Only on the listener map it show the total listener.Please fix it.

**Comment by SlvrEagle23** [comment]
@surihost All installs of AzuraCast should now use the latest version of the ShoutCast DNAS. Please make a new issue if you're having any other issues with the current codebase.
