### ISSUE TITLE
bug tranlation pt-br

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#2252]
Hello,
In this update there are still things that do not work correctly. For example, where it says that This station's time zone is currently, does not show the chosen time zone and is only% s.

In the Music Files part, When you click on EDIT on a song, much information there does not translate and remains in English.

Example below, none have been translated:
File Name
Song artist
Song Lyrics
Song title
Song Album
ISRC
and the text below that is
International Standard Recording Code, used for licensing reports.

In Album Art
Replace Album Cover Art (Not translated)

In advanced playback settings
No options have been translated.

I remember you translated all these parts, but did not enter the translation. I didn't get to update my azuracast, I'm following the example on page https://demo.azuracast.com/station/1/files

On this page: https://demo.azuracast.com/station/1/playlists
in Music 16 (42.1 minutes) and not translated instead of minutes is minutes or hours in en

In the same page above
If disabled, the playlist will not be included in radio playback, but can still be managed.
Not translated.

Control how this playlist is handled by AutoDJ.
Warning: <b> Warning: </b> These functions are built into Liquidsoap and will affect how AutoDJ works.
Translated, but <b> Warning: </b> is appearing <b> and does not bring any effect.

If auto-assignment is enabled, use this playlist as one of the targets for songs to be redistributed into. This will overwrite the existing contents of this playlist.
(Not translated)

In source
Song-Based Playlist
Song Playback Order
Shuffled
Random
Sequential
Not translated

If requests are enabled for your station, users will be able to request media that is on this playlist.
Not translated

Enable this setting to prevent metadata from being sent to the AutoDJ for files in this playlist. This is useful if the playlist contains jingles or bumpers.
Not translated

In Schedule
This station's time zone is currently% s.
Also the error and does not show time zone getting only% s

Start time
To play once per day, set the start and end times to the same value.

End time
If the end time is before the start time, the playlist will play overnight.

Start Date
To set this schedule to run only within a certain date range, specify a start and end date.

End Date
In scheduling, all of the above were not translated.

Scheduled Play Days of Week
Leave blank to play on every day of the week.
The one above didn't go either.

I also noticed that at the end of each page also does not translate
Showing 1 to 1 of 1 entries
It's in English too.

**Comment by Marcioghiraldelli** [comment]
any prediction for correction?
Because the translation of the files is 100% and no azuracast appears. It has errors in en

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli I have found and resolved the cause of this problem across the new Vue components. They should all be translating correctly as of the latest update released a few minutes ago.
