### ISSUE TITLE
PLEASE DO NOT CLOSE THIS ONE: There is currently NO OPEN TICKET for a scheduling bug

### ISSUE THREAD

**Issue by hottweelz** [AzuraCast/AzuraCast#2253]
**Frustrating that you are closing the tickets without the actual repair.  Work with us.  Please and thank you.**

**Using Docker installation method**

**YES**

**Host Operating System**

**Ubuntu 18.04 Server LTS**

**Describe the bug**

**Creating a new scheduled playlist (without advanced options checked) will NOT take effect until / unless you "Restart" services such as AutoDJ and Shoutcast. (not tested with Icecast)**

**To Reproduce**

**1. Go to "Add Playlist"
2. Click on "Schedule"
3. Create a "Schedule"
4. Check "Interrupt other songs to play at scheduled time."
5. Click "Save Changes"**

**Expected behavior**

**The playlist should play at the scheduled time.  However, in the logs, the schedule doesn't update in the system and fails to play... you MUST restart the services for the playlist to be presented.**

**Relevant Logs**

2019/12/31 13:17:13 [main:3] Shutdown started!
2019/12/31 13:17:13 [main:3] Waiting for main threads to terminate...
2019/12/31 13:17:13 [clock.wallclock_main:3] Streaming loop stopped.
2019/12/31 13:17:13 [main:3] Threads terminated.
2019/12/31 13:17:13 [threads:3] Shutting down scheduler...
2019/12/31 13:17:13 [threads:3] Scheduler shut down.
2019/12/31 13:17:13 [threads:3] Waiting for queue threads to terminate...
2019/12/31 13:17:13 [threads:3] Queues shut down
2019/12/31 13:17:13 [server:3] Closing socket.
2019/12/31 13:17:13 [main:3] Cleaning downloaded files...
2019/12/31 13:17:13 [main:3] Freeing memory...
2019/12/31 13:17:13 >>> LOG END
2019/12/31 13:17:14 >>> LOG START
2019/12/31 13:17:14 [main:3] Liquidsoap 1.4.0
2019/12/31 13:17:14 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.3 sedlex=2.1 menhirLib=20190924 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.5.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.3 mad=0.4.5 flac=0.1.5 flac.ogg=0.1.5 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.3.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.9 camomile=1.0.2 faad=0.4.0
2019/12/31 13:17:14 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/12/31 13:17:14 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/12/31 13:17:14 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/12/31 13:17:14 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/12/31 13:17:14 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/12/31 13:17:14 [sandbox:3] Running inside a docker container, disabling sandboxing..
2019/12/31 13:17:14 [video.converter:3] Couldn't find preferred video converter: gavl.
2019/12/31 13:17:14 [audio.converter:3] Using samplerate converter: libsamplerate.
2019/12/31 13:17:14 [harbor:3] Adding mountpoint '/' on port 8005
2019/12/31 13:17:14 [playlist_new_years_fun:3] Loading playlist...
2019/12/31 13:17:14 [playlist_new_years_fun:3] No mime type specified, trying autodetection.
2019/12/31 13:17:14 [playlist_new_years_fun:3] Playlist treated as format application/x-mpegURL
**_2019/12/31 13:17:14 [playlist_new_years_fun:3] Successfully loaded a playlist of 2 tracks._**
**_2019/12/31 13:17:14 [playlist_default:3] Loading playlist..._**
2019/12/31 13:17:14 [playlist_default:3] No mime type specified, trying autodetection.
2019/12/31 13:17:14 [playlist_default:3] Playlist treated as format application/x-mpegURL
2019/12/31 13:17:14 [playlist_default:3] Successfully loaded a playlist of 2 tracks.
2019/12/31 13:17:14 [error_jingle:3] "/usr/local/share/icecast/web/error.mp3" is static, resolving once for all...
2019/12/31 13:17:14 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 0).
2019/12/31 13:17:14 [cyberfm_test_local_1:3] Connecting mount sid#1 for @127.0.0.1...
2019/12/31 13:17:14 [cyberfm_test_local_1:3] Connection setup was successful.
2019/12/31 13:17:14 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2019/12/31 13:17:14 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/cyberfm_test/media/New Years Fun/in_the_air_tonight.mp3".
2019/12/31 13:17:14 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/cyberfm_test/media/Mainstream/Christian/Contemporary Christian August 2019/for KING & COUNTRY - God Only Knows.mp3".
2019/12/31 13:17:14 [cyberfm_test_live_switch:3] Switch to cyberfm_test_safe_fallback.
2019/12/31 13:17:14 [cyberfm_test_safe_fallback:3] Switch to error_jingle.
2019/12/31 13:17:14 [playlist_default:3] Prepared "/var/azuracast/stations/cyberfm_test/media/Mainstream/Christian/Contemporary Christian August 2019/for KING & COUNTRY - God Only Knows.mp3" (RID 4).
2019/12/31 13:17:14 [cyberfm_test_safe_fallback:3] Switch to cyberfm_test_radio_cue with transition.
2019/12/31 13:17:14 [cyberfm_test_requests_fallback:3] Switch to cyberfm_test_interrupt_switch.
2019/12/31 13:17:14 [cyberfm_test_interrupt_switch:3] Switch to cyberfm_test_autodj_fallback.
2019/12/31 13:17:14 [cyberfm_test_autodj_fallback:3] Switch to cyberfm_test_standard_playlists.
2019/12/31 13:17:14 [cyberfm_test_standard_playlists:3] Switch to stereo_playlist_default.
2019/12/31 13:17:14 [lang:3] AzuraCast Raw Response: annotate:title="joy. (Single)",artist="for KING & COUNTRY",duration="233.",song_id="96ffcc80d2b3c89083ac1ec11a7a1723",media_id="246",playlist_id="1":/var/azuracast/stations/cyberfm_test/media/Mainstream/Christian/Contemporary Christian July 2018/for KING & COUNTRY - joy.mp3
2019/12/31 13:17:14 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/cyberfm_test/media/Mainstream/Christian/Contemporary Christian July 2018/for KING & COUNTRY - joy.mp3".
2019/12/31 13:17:14 [cross_7721:3] Analysis: -134.190311dB / -30.462648dB (0.04s / 0.04s)
2019/12/31 13:17:14 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2019/12/31 13:17:14 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/cyberfm_test/media/Mainstream/Christian/Contemporary Christian July 2018/for KING & COUNTRY - joy.mp3".
2019/12/31 13:17:14 [lang:3] AzuraCast Feedback Response: OK
**_2019/12/31 13:19:00 [playlist_new_years_fun:3] Prepared "/var/azuracast/stations/cyberfm_test/media/New Years Fun/in_the_air_tonight.mp3" (RID 3).
2019/12/31 13:19:00 [cyberfm_test_interrupt_switch:3] Switch to stereo_playlist_new_years_fun with transition.
2019/12/31 13:19:00 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/cyberfm_test/media/New Years Fun/lea_michele_-_auld_lang_syne.mp3".
2019/12/31 13:19:00 [cross_7721:3] Analysis: -7.110038dB / -41.006945dB (2.96s / 2.96s)_**
2019/12/31 13:19:00 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2019/12/31 13:19:00 [lang:3] AzuraCast Feedback Response: OK
2019/12/31 13:24:26 [playlist_new_years_fun:3] Prepared "/var/azuracast/stations/cyberfm_test/media/New Years Fun/lea_michele_-_auld_lang_syne.mp3" (RID 7).
2019/12/31 13:24:26 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/cyberfm_test/media/New Years Fun/in_the_air_tonight.mp3".
2019/12/31 13:24:26 [cross_7721:3] Analysis: -103.420281dB / -25.667387dB (2.98s / 3.02s)
2019/12/31 13:24:26 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2019/12/31 13:24:26 [lang:3] AzuraCast Feedback Response: OK
**Screenshots**

<img width="830" alt="Screen Shot 2019-12-31 at 1 38 55 PM" src="https://user-images.githubusercontent.com/52544955/71630864-6ae97500-2bd3-11ea-8426-f5905d283693.png">
<img width="828" alt="Screen Shot 2019-12-31 at 1 38 42 PM" src="https://user-images.githubusercontent.com/52544955/71630865-6ae97500-2bd3-11ea-93b5-95f3ac28827d.png">

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@hottweelz I was being diplomatic with the last few responses, but I'm going to put this simply: your attitude with regard to how you're working with this project is unacceptable.

I can appreciate that you're frustrated here, but you've ignored my responses, responded with obvious anger and hostility, and basically treated us as though we are a corporate organization providing you with support for something you paid highly for. We are not that. We are volunteers depending on donations to make any money at all off of what is free (both as in libre and as in beer) software.

In the case of this issue, you are doubly mistaken:

 - I did not close #2132, the original issue you wanted me to look at in the first place. That issue is currently, and remains, open.

 - I actually responded to you in issue #2132 and mentioned you directly (which means you should've been notified by GitHub of this) explaining why this is happening to you in your specific case. Long story short: having the "Interrupt other songs" setting turned on means AzuraCast is relying solely on Liquidsoap to manage that playlist, which means a reload every time you make any changes, unlike playlists managed by AzuraCast's AutoDJ.

I don't ask for much in return for having devoted thousands of hours to building this software and giving it away to the public, but the least I ask is that interactions with me include kindness, respect and patience.

I expect that it will anger you further that I'm closing this issue itself, but to reiterate, issue #2132 is both open and has a response informing you of exactly why you're experiencing what you are.

**Comment by hottweelz** [comment]
Thank you.  Two things:

Azuracast GitHub is being sent to my spam folder in gmail. (Not sure why) that is why I’m not seeing your replies in a timely manner. 

This answer: “Long story short: having the "Interrupt other songs" setting turned on means AzuraCast is relying solely on Liquidsoap to manage that playlist, which means a reload every time you make any changes, unlike playlists managed by AzuraCast's AutoDJ.” Is logical to me, but it’s the first time you said it.  

I would not have been as frustrated if you explained it that way last time.  

Thanks again.
