### ISSUE TITLE
AzuraCast API - 500 Internal server error

### ISSUE THREAD

**Issue by callumok2004** [AzuraCast/AzuraCast#2254]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
Whenever I send a POST request to https://radio.wearebounce.net/api/station/1/streamers I receive error code 500

**Expected behavior**
It should send the request successfully and create the new encoder!

**Screenshots**

This is the code I am using:
![image](https://user-images.githubusercontent.com/35779365/71632579-07793a80-2c07-11ea-8cce-b57a04a44cc4.png)

**Device(s):**
 - Device: HP Laptop
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by SlvrEagle23** [comment]
@callumok2004 We would need the actual text of the HTTP 500 error, one way or another: either you can post the error message you get from the response body (if it includes the error details) or you can check the system's logs via the system-wide Log Viewer, looking particularly at the AzuraCast application log as you make the request.

**Comment by callumok2004** [comment]
[2020-01-01T19:03:18.826870+00:00] AzuraCast.ERROR: Could not parse input data. {"file":"/var/azuracast/www/src/Controller/Api/AbstractApiCrudController.php","line":118,"code":0} []

**Comment by callumok2004** [comment]
@SlvrEagle23 
After some more testing, I made a few requests with the same code and looked at the log to see what error appeared multiple times, and this is the error I get!
```
AzuraCast.ERROR: Could not parse input data {"file":"/var/azuracast/www/src/Controller/Api/AbstractApiCrudController.php","line":118,"code":0} []
```

**Comment by SlvrEagle23** [comment]
@callumok2004 I think this has to do with your coding on your end. Try adding `dataType: "json"` to the AJAX call.

**Comment by callumok2004** [comment]
Ok, I added that and the request responded with status 200, but the encoder was never created!

**Comment by SlvrEagle23** [comment]
@callumok2004 Are you not seeing the record in the DB itself, or not on a subsequent GET of the `/streamers` endpoint? That will be much harder to diagnose remotely.

**Comment by callumok2004** [comment]
I have a page with a GET requests of all streamers in a list, and when I view the page, the created streamer does not appear.

**Comment by callumok2004** [comment]
There are also no logs in the azuracast logs section

**Comment by callumok2004** [comment]
I Sent you a private message on slack with more information
