### ISSUE TITLE
Please increase the maximum number of files

### ISSUE THREAD

**Issue by radio2019** [AzuraCast/AzuraCast#2255]
If you upload more than 5000 MP3s additional ones can't be found by AzuraCast, even if they are put into separate folders.
Please fix this bug.
Thank you.

**Comment by SlvrEagle23** [comment]
@radio2019 We don't have a fixed limit on the number of files that can be uploaded to AzuraCast, especially across multiple folders.

**Comment by radio2019** [comment]
We did that.
The problem  accours when you upload the MP3s with FileZilla.
It doesn't matter if you put them all in one or (like we did) into separate folders.
I guess this is due to a bug in AzuraCast's FTP client.

**Comment by SlvrEagle23** [comment]
@radio2019 We have switched to a SFTP-based mass upload solution in the latest version of the application; please update to this version and the issue should be fixed.
