### ISSUE TITLE
Geolocation Block system

### ISSUE THREAD

**Issue by legendskyk** [AzuraCast/AzuraCast#2258]
Hello,
How we block countries on azuracast panel?? isnt there a way to block through geolocation? and add only those countries which we want to work our radio stream? because now days radio stream being ddos with different ips via http flood request which halt the listeners peak. is there any solution?

**Comment by SlvrEagle23** [comment]
@legendskyk AzuraCast has no internal solution to automatically block listeners from either certain locations or IP ranges, but both Icecast and SHOUTcast have options inside their administration panels to do that. You should visit the administration panel (you'll see details for it under the "Broadcasting" section of the station's main profile page) to see what options you have for your given frontend.

**Comment by legendskyk** [comment]
But thats not work, because whenever server got restarted then shoutcast panel removed banlist autmoatically.

**Comment by SlvrEagle23** [comment]
@legendskyk That's the only option we have available for right now. If you'd like to request a new feature for AzuraCast, you're welcome to submit a [feature request](https://features.azuracast.com/).

**Comment by legendskyk** [comment]
as i seen /var/auzracast dont appear www folder, just tell me how could i configure .htaccess file to access the azuracast panel??, my panel being ddos attack by http flood i want to block countries IP range, can you guide me how it can be possible?

**Comment by legendskyk** [comment]
as i seen /var/auzracast dont appear www folder, just tell me how could i configure .htaccess file to access the azuracast panel??, my panel being ddos attack by http flood i want to block countries IP range, can you guide me how it can be possible?

**Comment by biguenique** [comment]
@legendskyk I'm affraid your specific issue is not directly related to AzuraCast. You might want to look around the web for a solution to your specific problem on a VPS and the Docker environment.
