### ISSUE TITLE
Subdomain installation?

### ISSUE THREAD

**Issue by legendskyk** [AzuraCast/AzuraCast#2260]
how can we install azuracast through root but panel should be open with subdomain address instead of main domain address??

**Comment by SlvrEagle23** [comment]
@legendskyk Whether your AzuraCast installation lives on a subdomain or a main domain is a matter of how you configure your DNS to point to your server. AzuraCast has no trouble at all being hosted on either a subdomain of its own, or on the main domain of the site, as long as it's in the root directory (`/`) of whatever domain you assign it to.

If you're asking about running multiple sites on the same server, and having AzuraCast be on a subdomain while you have your main site on the same server, you can do this by [following our multi-site installation guide](https://www.azuracast.com/developers/multisite.html).

**Comment by legendskyk** [comment]
I have wordpress installed on my main domain address and i want to configured azuracast main panel to subdomain? if i do installation on root that will doesnt affect my wordpress site you mean right?

**Comment by SlvrEagle23** [comment]
@legendskyk Correct, your AzuraCast installation can be on a subdomain completely separate from the main Wordpress site. They shouldn't interfere with each other at all.

**Comment by ttodua** [comment]
> @legendskyk Whether your AzuraCast installation lives on a subdomain or a main domain is a matter of how you configure your DNS to point to your server. AzuraCast has no trouble at all being hosted on either a subdomain of its own, or on the main domain of the site, as long as it's in the root directory (`/`) of whatever domain you assign it to.
> 
> If you're asking about running multiple sites on the same server, and having AzuraCast be on a subdomain while you have your main site on the same server, you can do this by [following our multi-site installation guide](https://www.azuracast.com/developers/multisite.html).

that link doesnt work. 404
