### ISSUE TITLE
After successful restart of server the "Please wait..." message won't disappear

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#2262]
After successful restart of server on admin page, the "Please wait..." message won't disappear. See screenshot. 

After changing the page things will look normal again. So it's not a big deal but I thought I post it anyway in case you're not aware of it. 

Sorry if it's a duplicate. I remember a similar issue but couldn't find it now. I even remembered that it was reported as fixed but maybe not, I'm not sure. 

Installation (Docker): v0.9.8, #c72be08 (2019-12-15 8:53)

Ah, and happy new year everyone! Let's have another wonderful Azura-year! :)

![image](https://user-images.githubusercontent.com/28865986/71764862-cd9d8200-2eed-11ea-9dbf-17e58cbe4c61.png)

**Comment by SlvrEagle23** [comment]
@gammaw What page were you on when it did that? It should refresh the page you're on, unless you're on a form page where that would mess with the submission, in which case it should just return to saying "Restart Broadcasting".

**Comment by gammaw** [comment]
@SlvrEagle23 it occurs for me on the "Music Files" sub page of the station (URL slug: `/station/1/files`). There the display never returns to "Restart Broadcasting". If I'm on "Profile" it works as expected.

**Comment by SC2Mitch** [comment]
Yeah having the same issue if it's within `/station/%/files`

**Comment by SlvrEagle23** [comment]
Fixed as of latest update. Thanks for the report!
