### ISSUE TITLE
Shoutcast streamauthhash

### ISSUE THREAD

**Issue by ValentinOgier** [AzuraCast/AzuraCast#2265]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 16,04

**Describe the bug**
Every time I restart my station I need to find the streamauthhash and add it manually into the server admin.

**Expected behavior**
Please add a custom field during the install or modifying a station "streamauthhash" that add a line into sc_serv.conf file.

**Comment by Radio-Quergedacht** [comment]
Ubuntu 16,04 is too old

**Comment by SlvrEagle23** [comment]
@Radio-Quergedacht We do still support Ubuntu 16.04, as it's a long-term-support release that is still within its support range. Once 20.04 is released, we will phase out support for 16.04.

**Comment by biguenique** [comment]
@ValentinOgier I have no experience with SHOUTcast on AzuraCast, but I know you can modify Icecast settings by putting JSON in _Edit Profile_ > _Broadcasting_ > _Advanced Custom Configuration_. Maybe you can try adding something there, such as:

```
{ { "streamauthhash" : "YOUR_HASH_HERE" } }
```
And restart your station with fingers crossed, hoping that AzuraCast will add a line to sc_serv.conf.

@SlvrEagle23 Any idea if that would be taken into account?

**Comment by SlvrEagle23** [comment]
@biguenique I think the problem is caused by the fact that the "advanced custom configuration" isn't present on SHOUTcast mount points. This is definitely something we need to look at on our end, and I will do so as soon as I can.

**Comment by vamaresh** [comment]
I'm having the same issue. I tried updating the AuthHash directly logging into the shoutcast admin page from Azuracast still not being reflected.

**Comment by SlvrEagle23** [comment]
@vamaresh You should be able to specify the authhash for a given stream via the "Mount Points" configuration for each mount point in the station administration. This will make sure it persists across reloads on SHOUTcast.
