### ISSUE TITLE
Restore from backup into new container - Permisison denied

### ISSUE THREAD

**Issue by mikeopensauce** [AzuraCast/AzuraCast#2268]
Hi all
I've got a running Azuracast server on one of my virtual servers and all is good. I have created a backup using the web gui tool.

I have created a Digital Ocean Azuracast droplet and uploaded the backup file.
When I run:
./docker.sh ~/oldstream.zip
It gives me:
./docker.sh: line 378: /root/oldstream.zip: Permission denied

I am running as root in the droplet and the backup file (oldstream.zip) is owned by root.
I can't see any log that tells me what the problem is and I'm not sure what to do next.

Does anyone have any pointers please?

Many thanks
Mike

**Comment by SC2Mitch** [comment]
You tried running in Sudo?

**Comment by mikeopensauce** [comment]
Thanks for the suggestion.

Tried with and without sudo but with same error.

Mike

Mike Cox
Managing Director
Open Sauce Systems Ltd.
part of The Rosetta Group<http://rosetta.group>

Tel: 01983 229 229
Email: mike@opensauce.systems<mailto:mike@opensauce.systems>
Web: www.opensauce.systems<http://www.opensauce.systems>

Software and phone systems for business
[https://www.rosetta.group/wp-content/uploads/2019/06/osslogo.png]<http://www.opensauce.systems>
Have a look at our new cloud phone system at www.rosettatelecom.com<http://www.rosettatelecom.com>
On 06/01/2020 16:10, SC2Mitch wrote:

You tried running in Sudo?

**Comment by SC2Mitch** [comment]
That's weird, are you running the latest version of AzuraCast? If so, can you double check your using the most up-to-date backup.

**Comment by mikeopensauce** [comment]
Old server is v0.9.8, #c72be08 (2019-12-15 8:53) • Docker • PHP 7.4

New server is VERSION 0.9.7.1 OS Ubuntu 18.04 according to Digital Ocean although I can't check that yet as I can't get in to the web interface.

Mike

Mike Cox
Managing Director
Open Sauce Systems Ltd.
part of The Rosetta Group<http://rosetta.group>

Tel: 01983 229 229
Email: mike@opensauce.systems<mailto:mike@opensauce.systems>
Web: www.opensauce.systems<http://www.opensauce.systems>

Software and phone systems for business
[https://www.rosetta.group/wp-content/uploads/2019/06/osslogo.png]<http://www.opensauce.systems>
Have a look at our new cloud phone system at www.rosettatelecom.com<http://www.rosettatelecom.com>
On 06/01/2020 16:36, SC2Mitch wrote:

That's weird, are you running the latest version of AzuraCast? If so, can you double check your using the most up-to-date backup.

**Comment by mikeopensauce** [comment]
tried uninstall and install in case it is a problem with the Digital Ocean version and I can now restore the backup although the web interface now says "File not found" but at least I have solved the original issue!
Thanks for your suggestions SC2Mitch

**Comment by mikeopensauce** [comment]
Ran ./docker.sh update and I can now get to the web interface but the restore hasn't worked as my stations are not shown. Slowly getting there!

**Comment by mikeopensauce** [comment]
Restored again and it seems to be OK.
This suggests it could be an issue with the Digital Ocean Azuracast container.

My process that works has been:
1. Install Digital Ocean Azuracast container.
2. Uninstall Azuracast
3. Install Azuracast
4. Update Azuracast
5. Restore backup

Thanks for your suggestions.
