### ISSUE TITLE
Update Metadata (Song Info)

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#2269]
Hi all friends.

I would need to receive the metadata of the next song 15/10 seconds before the end of the current one. Can this be possible? even making some changes in the code? I would have so much need.

Thank you. A good and happy day

**Comment by SlvrEagle23** [comment]
@Ilario42 Our API already includes the `next_song` field alongside the `now_playing` field that you could use ahead of time if needed.
