### ISSUE TITLE
how to change SSL port after installation

### ISSUE THREAD

**Issue by Gujalls** [AzuraCast/AzuraCast#2270]
Hi,

I have installed the Azuracast as per the instructions provided. While installation I forgot to change the port for SSL however changed the HTTP port.
Now the Azuracast runs in HTTP - 8080 & SSL - 443.

How can I change the SSL port from 443 to say 80443? 
Does this require a new installation? 

I changed the port from 443 to 80443 as I did for the port 80 to 8080 and restarted the docker. But didn't see that change happening. 

Please can you help me - as I will need the port 80 and 443 for the site default website.

Thanks very much for your help.

**Comment by SlvrEagle23** [comment]
@Gujalls We have a special guide section for using non-standard ports with AzuraCast. Just follow these steps and you should be all set: https://www.azuracast.com/help/faq_docker.html#use-non-standard-ports

**Comment by Gujalls** [comment]
Hi,

Thanks for the response.
I updated the .env file to change the HTTP port to 8080 and missed to update the HTTPS port during installation of azuracast.
Now azuracast is installed and my radio stations are running. I realized that I missed to update the HTTPS port. When I now update the .env to change the HTTPS port to '80443' I don't see any change taking place. Tried restarting the docker as well but the change is not seen.

Please can you help me on what / how I can change the HTTPS port without re-installing the azuracast again.

**Comment by SlvrEagle23** [comment]
@Gujalls Make sure you're updating a file called `.env` (as in, with no name, just the .env extension) instead of the file `azuracast.env`, which is used for different purposes.

**Comment by Gujalls** [comment]
Hi,

I did the following steps:

1. vi /var/azuracast/.env
2. Changed the SSH port 
AZURACAST_HTTPS_PORT=7443
3. service docker restart

But the port has not changed :(

Please can you let me know how to fix it. This is hindering the actual website.

**Comment by SlvrEagle23** [comment]
@Gujalls Try:

```bash
cd /var/azuracast
docker-compose down
docker-compose up -d
```

**Comment by chapuawe2** [comment]
Just to add, SSL won't work if you change the port from installation.
First you have to use the common ports (80, 443) then let let's encrypt create the certificate for the domain or subdomain, and after that you can freely change the ports (Tested)

**Comment by alencarwell** [comment]
for me, dont working...

vi /var/azuracast/.env
Changed the SSH port
AZURACAST_HTTPS_PORT=7443
service docker restart

cd /var/azuracast
docker-compose down
docker-compose up -d

Helpme plase?

**Comment by veerabiz1** [comment]
> Hi,
> 
> Thanks for the response. I updated the .env file to change the HTTP port to 8080 and missed to update the HTTPS port during installation of azuracast. Now azuracast is installed and my radio stations are running. I realized that I missed to update the HTTPS port. When I now update the .env to change the HTTPS port to '80443' I don't see any change taking place. Tried restarting the docker as well but the change is not seen.
> 
> Please can you help me on what / how I can change the HTTPS port without re-installing the azuracast again.

The HTTPS port should be 8443 Not 80443
