### ISSUE TITLE
Playlists created for commercial do not air.

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#2274]
Playlists created for commercial do not air.

![image](https://user-images.githubusercontent.com/31827151/72123458-15823600-3340-11ea-8ba2-04415c892105.png)
![image](https://user-images.githubusercontent.com/31827151/72123471-1f0b9e00-3340-11ea-9a60-63f82e3c9523.png)
![image](https://user-images.githubusercontent.com/31827151/72123483-2a5ec980-3340-11ea-8702-c07bb3ae948d.png)
Am I setting it wrong?

**Comment by biguenique** [comment]
@Rafaelrds2017 I can't test it right now, but have you tried checking both _Only play one track at scheduled time_ and _Merge playlist to play as a single track_ under _AutoDJ Scheduling Options_?
