### ISSUE TITLE
id3 customfield variable lengh

### ISSUE THREAD

**Issue by ecutsa** [AzuraCast/AzuraCast#2277]
a long (more than 256 character) in id3tag is not read well inside customfield 
i did the test with TIT3 (subtitle) id3, my id3 is well written inside mp3 but truncated inside azura
maybe a variable to change inside the db ?

**Comment by SlvrEagle23** [comment]
@ecutsa It's fairly standard for fields in databases like ours to be 255 characters long, as earlier versions of the MySQL database limited variable character (varchar) fields to that length. They've since significantly increased the available length, but I'm not sure if we should expand the length of these fields, and if so to what length.

It's fair to assume that a vast majority of represented custom field metadata can fit within 255 characters, other than perhaps song lyrics, but those are already stored as a TEXT field with indeterminate length.

**Comment by SlvrEagle23** [comment]
@ecutsa Just curious, how big is the data you're trying to put into the field, i.e. how many characters long is it?

**Comment by ecutsa** [comment]
> It's fair to assume that a vast majority of represented custom field metadata can fit within 255 characters, other than perhaps song lyrics, but those are already stored as a TEXT field with indeterminate length.

what is the correct id3v2 of lyrics you use as TEXT ? i couldnt figure out to insert data inside the lyrics filed (i tried TEXT, USLT cf http://id3.org/id3v2.4.0-frames)

i try to put around 1000 characters, it depends of each tracks, i try to put podcast description from data i grab over the web with the id3v2 tool (https://packages.debian.org/fr/buster/id3v2)

**Comment by SlvrEagle23** [comment]
@ecutsa It should be USLT, unsynchronized lyrics, that correspond to our internal lyrics field.

**Comment by ecutsa** [comment]
when i push USLT as 
> id3v2 --USLT "":"this is some unsynchronized lyrics":"eng" test.mp3 
i can get the lyrics in the customfield USLT but not in "Lyrics"

**Comment by SlvrEagle23** [comment]
@ecutsa Ah, good catch; I was trying to set from "unsynchronized" lyrics, which is the US regional spelling of the phrase, but the ID3 tag uses another spelling, "unsynchronised". I've fixed our code so it should properly set the one with the S instead of the Z.

**Comment by ecutsa** [comment]
@SlvrEagle23 nice, now i can get the data i pushed inside USLT but it is still limited to 588 characters, i wish i could use 1000 or more (cause some descriptions are larger)

**Comment by SlvrEagle23** [comment]
@ecutsa I'm not sure that that limitation is coming from us...that field is a TEXT field on our end which should not be limited.

**Comment by ecutsa** [comment]
yep i deleted my post because i realized the tool i used (id3v2) was buggy (it doesnt handle ":" character) and is using it as a separator for USLT options
so i did the test with an other tool and it works great !
thanks :)
<3
