### ISSUE TITLE
Media changes ignored by Azuracast 

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#2278]
Something strange happened today. We changed the title and cover art of a music file in the Azuracast admin interface (in browser). The changes were visible on the admin page (expected behavior). When the file was scheduled later the day, the old title and the default art work were  displayed (and sent in the nowplaying API). Azura seemed to be in a corrupt state. Normally, we can even change things on the fly and Azura will send the new data in couple of seconds. I didn't see any trace of it in the log (in general, there is no trace of editing meta data in the log). I can only think of one unusual thing about the file: the original title included quotation mark and a dash character. 

Any idea? 

We have following Docker installation: v0.9.8, #c72be08 (2019-12-15 8:53)

**Comment by SlvrEagle23** [comment]
@gammaw Normally it writes the ID3 metadata back to the file, which should persist any changes even if Liquidsoap's reading the file directly (or if AzuraCast is re-processing the file later).

Interesting problem, I'll look to see if I can help fix this process before the next point release.

**Comment by gammaw** [comment]
@SlvrEagle23 thanks. Just checked, the ID3 metadata have been changed correctly in the file. It seems that Azuracast didn't read the updated data and transferred the old data via the nowplaying API. I think it was not only wrong in the JSON message, also the admin page (Profile) showed the old data. Does it make any sense to you?
