### ISSUE TITLE
Problems Translation PT-BR

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#2279]
Hi, some time ago I did 100% of the translation of the program and in azuracast is not in. There are still several parts in English and the time zone part no longer shows the selected time zone. Follows images of the error.
correcting these errors will be 100% in Portuguese

![download](https://user-images.githubusercontent.com/48635610/72211975-0f609680-34b3-11ea-838f-562ded1e5b49.png)
![Screenshot_15](https://user-images.githubusercontent.com/48635610/72211979-2901de00-34b3-11ea-8bb2-a0f505a22eb7.png)
![Screenshot_16](https://user-images.githubusercontent.com/48635610/72211987-45057f80-34b3-11ea-86c6-8fd5dece45e5.png)
![Screenshot_17](https://user-images.githubusercontent.com/48635610/72211991-58b0e600-34b3-11ea-87b7-e78025dc0a7d.png)
![Screenshot_18](https://user-images.githubusercontent.com/48635610/72211993-69615c00-34b3-11ea-9bc7-5ea999d13fc5.png)

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli Update on these:

 - I've fixed "Search" on data tables, that was an omission on my part.
 - Several of these are marked as untranslated because the previous version (that you had translated) had line breaks in it; those line breaks were an error on our part due to my IDE adding line wraps where it shouldn't have. I've since fixed this, but that means that the translation software considers those un-line-broken strings as _new_ strings that need re-translation; if you visit CrowdIn you should see those ready for addition.
 - The `O fuso horário desta estação está atualmente %s.` error appears to be on your part...the original translated string says `%{tz}`, not `%s`, so it should exactly match the original format or the translation software won't know what to do with it.

**Comment by Marcioghiraldelli** [comment]
Hello,
I made the correction of the translation system.
Taking advantage, I found another problem in the translation that I attached to the image.
Correcting these problems, it seems to be close in Portuguese from Brazil.

**Comment by Marcioghiraldelli** [comment]
Hello,
I made the correction of the translation system.
Taking advantage, I found another problem in the translation that I attached to the image.
Correcting these problems, it seems to be close in Portuguese from Brazil.
![Screenshot_19](https://user-images.githubusercontent.com/48635610/72283499-af3a3380-361d-11ea-8ab1-65889346dec4.png)

**Comment by Marcioghiraldelli** [comment]
Hello,
I made the correction of the translation system.
Taking advantage, I found another problem in the translation that I
attached to the image.
Correcting these problems, it seems to be close in Portuguese from Brazil.


Em dom., 12 de jan. de 2020 às 17:07, SlvrEagle23 <notifications@github.com>
escreveu:

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli Unfortunately, we can't fix that one as it's with our older jQuery Bootgrid library; we're in the process of migrating everything over to our newer Vue components, at which point that won't be an issue.

Otherwise, I believe we're fully localized at this point.

**Comment by Marcioghiraldelli** [comment]
Alright, but what about the new translations I did?
You didn't tell me if you updated and made the corrections for me to test.

**Comment by Marcioghiraldelli** [comment]
Alright, but what about the new translations I did?
You didn't tell me if you updated and made the corrections for me to test.

Em seg., 13 de jan. de 2020 às 18:51, SlvrEagle23 <notifications@github.com>
escreveu:

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli I understand this is really important to you, but please be patient. I appreciate that you've been aggressively pursuing this issue, but we will get to those things as soon as we can.

**Comment by Marcioghiraldelli** [comment]
appreciate.,
I'm sorry if I'm being boring. I just want to help.

Em seg., 13 de jan. de 2020 às 19:00, SlvrEagle23 <notifications@github.com>
escreveu:

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli The translations have been updated.

**Comment by Marcioghiraldelli** [comment]
Perfect!
did you update the example azuracast?
https://demo.azuracast.com/
Well, it seems that nothing has changed.
Forgive me if I'm being boring.
I just want to contribute to a functional tool for all countries.

Em seg., 13 de jan. de 2020 às 19:21, SlvrEagle23 <notifications@github.com>
escreveu:

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli Again, patience!!! The demo updates every hour at the top of the hour. Please don't expect turnarounds in the order of a few minutes from volunteers!

**Comment by Marcioghiraldelli** [comment]
Thanks a lot and sorry.

Em seg., 13 de jan. de 2020 às 19:36, SlvrEagle23 <notifications@github.com>
escreveu:

**Comment by Marcioghiraldelli** [comment]
Hello,
Now it looks good, only the time zone part, even with my correction he did
not enter.
This station's time zone is currently UTC and does not show the chosen UTC.

Em seg., 13 de jan. de 2020 às 19:38, Webservic Host <
webservichost@gmail.com> escreveu:
