### ISSUE TITLE
AzuraCast behind NGINX Proxy

### ISSUE THREAD

**Issue by derkalle4** [AzuraCast/AzuraCast#228]
Hey,

I have to use AzuraCast behind an nginx proxy because I've not enough IP addresses. So I used to have some kind of server virtualization (and of course one master nginx server that acts as an reverse proxy). 

So I've got an Hostname / IP <-> NGINX Reverse Proxy (VM1) <-> AzuraCast Installation (VM2)

So far AzuraCast only sees the IP of the NGINX Reverse Proxy (e.G. 192.168.0.1) instead of an real IP.

Could you add an check for the HEADER "HTTP_X_FORWARDED_FOR" in PHP so that it will fall back to use the reverse IP instead of "REMOTE_ADDR" if the header exists?

**Comment by SlvrEagle23** [comment]
@derkalle4 I'm assuming by this you mean that you're using the nginx radio proxy that AzuraCast provides (i.e. `/radio/8000/etc`) followed by another proxy in front of that?

That would be one too many layers of abstraction for the current nginx proxying setup, which is defined [here](https://github.com/AzuraCast/AzuraCast/blob/master/util/ansible/roles/nginx/templates/default.j2#L67).

We get similar issues to this from CloudFlare sitting in front of that nginx proxying setup, and I'm looking into the best way to resolve it. From CloudFlare's perspective, the answer is to use the nginx `realip` module to pull down the real IP and reassign the X-Forwarded-For variable to it. I'll have to experiment with that.

For now, if it's possible, you should be able to use that same configuration I'm using on my nginx, except use it on the "outer" nginx layer to proxy directly into the radio stations while passing them the necessary port, in a sense skipping the "internal" nginx proxy layer.

**Comment by linksilver** [comment]
maybe this can help you:
https://www.nginx.com/resources/admin-guide/proxy-protocol/

**Comment by SlvrEagle23** [comment]
In this case, I don't think it's practical for AzuraCast itself to implement any proxy-specific code, as even with the PROXY protocol, the settings differ depending on both:

* Whether or not a proxy is actually in use, and
* What the IP range of the proxy is

These are factors we don't know on our end when generating the nginx configuration. Even with the support of the proxy protocol, it would be presumptuous for us to turn it on for everyone, considering many of our users _wouldn't_ be using a proxy, and would thus be set up for one for no good reason.

**Comment by linksilver** [comment]
+1
this solution is only for systems which are behind a reverse proxy
