### ISSUE TITLE
Number of students

### ISSUE THREAD

**Issue by KulibibK** [AzuraCast/AzuraCast#2280]
Hello, tell me how to bring the number of listeners to a third-party site?

**Comment by SlvrEagle23** [comment]
@KulibibK Can you clarify your question? What are you trying to do exactly?

**Comment by onlinegill** [comment]
If your using shoutcast than you can use folliwng php code in your file or use iframe code 

`<?php

$sc_ip = 'serverip';
$sc_port = '8000';
$sc_sid = 1;

$xml = @simplexml_load_file('http://' . $sc_ip . ':' . $sc_port . '/stats?sid=' . $sc_sid);

if ($xml === FALSE) {
    $count_current = '0';
    $status = '0';
    $current_title = 'no title available';
} else {
    $count_current = $xml->CURRENTLISTENERS; # counting current listeners
    $status = $xml->STREAMSTATUS; # stream status
    $current_title = $xml->SONGTITLE; # current stream-title
}

echo 'Listeners: ' . $count_current . '<br />';
echo 'Current Song: ' . $current_title . '';

?>`

**Comment by KulibibK** [comment]
Thanks, but I use icecast. I would like it for icecast. Thanks in advance.
