### ISSUE TITLE
Multiple playlists with the same name (Bug)

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2281]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
Azuracast allows user to create multiple playlists with the same name for example "default". In this case liquidsoap will fail to start the stream after restarting.

**Comment by SlvrEagle23** [comment]
@eranwo Should be fixed as of the latest update a few moments ago.
