### ISSUE TITLE
Connection attempt failed with "ECONNREFUSED - Connection refused by server"

### ISSUE THREAD

**Issue by dannyodj** [AzuraCast/AzuraCast#2286]
@SlvrEagle23 Thank you for this great work i have installed azuracast in my server and i Love it,
i have donated and i will support you guys this is very blessed project.
I need your support in this:
i just updated azuracast yesterday in lasted version 13 January 2020, 
i try now to get acces with ftp but filezilla its showing me this message
Status:	Waiting to retry...
Status:	Resolving address of az1.sednastream.com...
Status:	Connecting to 136.243.19.165:21...
Status:	Connection attempt failed with "ECONNREFUSED - Connection refused by server".
i tryed to connect in the server with root password with sftp its working i have acces in root.

do i have to do an restart server? after updatin Azuracast?
what to do in this case?
also when i create sftp for any of the radios m when i try to connect i see this error

Disconnected from server
Status:	Connecting to az1.sednastream.com...
Response:	fzSftp started, protocol_version=9
Command:	open "arten.rio@gmail.com@az1.sednastream.com" 22
Command:	Trust new Hostkey: Once
Command:	Pass: *************
Error:	Authentication failed.
Error:	Critical error: Could not connect to server
whats your sugesstion please!

**Comment by SC2Mitch** [comment]
Yeah same issue here, ROOT works, email account doesn't.

**Comment by dannyodj** [comment]
> Yeah same issue here, ROOT works, email account doesn't.
Ok i found how to get access in every radio station , 
i read change log for new update of azuracast and thay switched from FTP to SFTP
i will make right now a video tutorial and i will paste the link here and you can watch how to do!

**Comment by dannyodj** [comment]
> Yeah same issue here, ROOT works, email account doesn't.

https://www.youtube.com/watch?v=9Usjmrz4jtc

**Comment by SlvrEagle23** [comment]
@dannyodj As of version [0.9.8.1](https://github.com/AzuraCast/AzuraCast/releases/tag/0.9.8.1), we now use standalone SFTP credentials that are managed on a per-station basis. You can no longer use your AzuraCast e-mail address to connect via FTP or the new SFTP. There are a number of technical reasons behind this change, some of which are explained in our release notes.

**Comment by dannyodj** [comment]
> 
> 
> @dannyodj As of version [0.9.8.1](https://github.com/AzuraCast/AzuraCast/releases/tag/0.9.8.1), we now use standalone SFTP credentials that are managed on a per-station basis. You can no longer use your AzuraCast e-mail address to connect via FTP or the new SFTP. There are a number of technical reasons behind this change, some of which are explained in our release notes.

yes i figure out and i did video tutorial for that :D 
https://www.youtube.com/watch?v=9Usjmrz4jtc
