### ISSUE TITLE
Public Player

### ISSUE THREAD

**Issue by Richard399** [AzuraCast/AzuraCast#2288]
Hi,

Love AzuraCast but still learning ...
 
I have noticed that when a track is playing in the public profile, the progress bar shows the track time at both the beginning and at the end.  Should this not show the actual countdown of the track and progress of it on the play bar?

Many Thanks

Richard

**Comment by SlvrEagle23** [comment]
@Richard399 It should be showing the elapsed time on the left, and the total song length on the right, like so:

![2020-01-13 17_05_48-(Development) AzuraTest Radio - AzuraCast](https://user-images.githubusercontent.com/6744885/72299619-f842b580-3626-11ea-83f4-1c1fc9a557a1.png)

**Comment by Richard399** [comment]
Hi,

Thank you for that,

Sure, I understand that but it does not show the progress on the bar, just grey and on occasion, does not show the elapsing time?

Thank you for responding, appreciated

Richard

**Comment by SlvrEagle23** [comment]
@Richard399 I'd need to see your specific installation to know why it's doing that.

**Comment by Richard399** [comment]
Hi @SlvrEagle23

Many Thanks, I have resolved it ;-)
