### ISSUE TITLE
Azura blocking all API requests

### ISSUE THREAD

**Issue by SanderCC** [AzuraCast/AzuraCast#2290]
I can't manage to get any response from the azura API. (the if statement returns false all the time)

Our header: https://i.imgur.com/BMBHABk.png
This is our code:
`<?php
$apikey = 'ourapi';
$opts = [
	"http" => [
		"method" => "GET",
		"header" => "X-API-Key: $apikey",
		'timeout' => 5
	]
];
$context = stream_context_create($opts);
if($file = file_get_contents('https://azura.ourdomain.net/api/nowplaying', false, $context)){
	echo "works";
} else {
	echo "try again";
}
?>`

**Comment by xewl** [comment]
Is [allow_url_fopen](https://www.php.net/manual/en/filesystem.configuration.php#ini.allow-url-fopen) set to `true`?

I'd "show all errors" to see if it gives a warning for it;
Or, preferrably, use [cURL](https://www.php.net/manual/en/book.curl.php) instead.

**Comment by SlvrEagle23** [comment]
@SanderCC I prefer when possible to use an abstraction library like [Guzzle](http://docs.guzzlephp.org/en/stable/), it really makes these kinds of requests easier by navigating all the low-level setup for you.

With Guzzle, the request would look like:

```php
$apikey = 'ourapi';
$client = new GuzzleHttp\Client();
$res = $client->request('GET', 'https://azura.ourdomain.net/api/nowplaying', [
    'headers' => ['X-API-Key' => $apikey],
    'timeout' => 5,
]);

if ($res->getStatusCode() === 200) {
    $file = (string)$res->getBody();
    $contents = json_decode($file);
} else {
    echo 'HTTP Error: '.(string)$res->getBody();
}
```
