### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by Richard399** [AzuraCast/AzuraCast#2291]
Hi,

My Hosting provider, when asking to migrate my website to the same VPS, tells me that they cannot install 'cPanel' alongside AzuraCast and go on to say that IceCast runs independently on a separate port for its web/streaming service?

In addition, they tell me that AzuraCast takes over the main port and assumes the whole server is under its control. So I'm not sure if AzuraCast will allow me to host my website through it?

So does this now mean I have to now have 2 servers - one for Icecast and AzuraCast and another for my website?

I hope someone is able to clarify, please?

Many Thanks

Richard :-(

**Comment by onlinegill** [comment]
> Hi,
> 
> My Hosting provider, when asking to migrate my website to the same VPS, tells me that they cannot install 'cPanel' alongside AzuraCast and go on to say that IceCast runs independently on a separate port for its web/streaming service?
> 
> In addition, they tell me that AzuraCast takes over the main port and assumes the whole server is under its control. So I'm not sure if AzuraCast will allow me to host my website through it?
> 
> So does this now mean I have to now have 2 servers - one for Icecast and AzuraCast and another for my website?
> 
> I hope someone is able to clarify, please?
> 
> Many Thanks
> 
> Richard :-(
First install WHM on fresh server and once website is up and running than install Azuracast on non standard port. So your whm URL would be IP:2087 and azuracast will be ip:4432 etc and icecast or shoutcast can be on 8000 or any port which is free.

**Comment by SlvrEagle23** [comment]
@Richard399 Your host is correct in that, by default, AzuraCast assumes it's the only thing hosted on your server and it occupies the main web ports (80, 443) and also a large range of ports (from 8000-8500) for Icecast stations.

You do not need a separate server for Icecast; we include Icecast in our software package.

You can also change the default ports that AzuraCast uses by [following this guide](https://www.azuracast.com/help/faq_docker.html#use-non-standard-ports). You can update the ports to be any unused number, then AzuraCast will be available via that port, and you can install whatever else you want on the server.

Note that it is recommended, for stability, to keep AzuraCast on its own server to avoid conflicts with other software. It is definitely widespread (and possible) to run it alongside other software, though.

**Comment by Richard399** [comment]
@SlvrEagle23 @onlinegill 

Thank you both for your response.

Most grateful! :-)
