### ISSUE TITLE
Dashboard frozen

### ISSUE THREAD

**Issue by rdr-dev** [AzuraCast/AzuraCast#2293]
My dashboard appears to have frozen, it doesn't seem to be playing the current track, next song or pull my listener stats. 

I've restarted liquidsoap and the server in the hope to kick start it but sadly failed. 

Any ideas?  I've attached a screenshot. 
![azurerdr](https://user-images.githubusercontent.com/59894454/72383266-079f2d00-3713-11ea-9877-d4b2b13483a4.PNG)

**Comment by SlvrEagle23** [comment]
@rdr-dev You should check and make sure that your relays are broadcasting correctly. The system may be picking one of those up and overriding the main "now playing" for the station.

**Comment by rdr-dev** [comment]
I've done this with three seperate icecast services, and each time it knocks out the on air information. 

Is this a known bug?  or am i doing some drastically wrong? 

The local streams do connect and stream the audio....
