### ISSUE TITLE
"remote" database

### ISSUE THREAD

**Issue by Terramoto** [AzuraCast/AzuraCast#2295]
Hello,

I'm not familiar with Docker and i'm attempting to setup AzuraCast under a CPanel server. CPanel runs most services required by AzuraCast and i was wondering how i can make it so AzuraCast uses the Database service on CPanel.

I've attempted to use the server public IP and bridge IP but i'm getting the:
```
In AbstractMySQLDriver.php line 106:
  An exception occurred in driver: SQLSTATE[HY000] [2006] MySQL server has gone away

In PDOConnection.php line 31:
  SQLSTATE[HY000] [2006] MySQL server has gone away

In PDOConnection.php line 27:
  SQLSTATE[HY000] [2006] MySQL server has gone away

In PDOConnection.php line 27:
  Packets out of order. Expected 0 received 1. Packet size=69



```
During the "Running Database Migrations"

All the db host, username, db name and password settings were adjusted in azuracast.env

**Comment by onlinegill** [comment]
Azuracast cast use own web server and mysql server so you dont need to create separate database on cpanel server as long as your edit .env file and update non standard ports.

**Comment by Terramoto** [comment]
> 
> 
> Azuracast use own web server and mysql server so you dont need to create separate database on cpanel server as long as your edit .env file and update non standard ports in order to install azuracast on top of WHM.

Thank you!
