### ISSUE TITLE
error install maxmind geolite

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#2296]
At the time of installing this error 500 below.

The command "'tar' 'xvzf' '/var/azuracast/geoip/geolite.tar.gz' '--strip-components=1'" failed. Exit Code: 2(Misuse of shell builtins) Working directory: /var/azuracast/geoip Output: ================ Error Output: ================ gzip: stdin: not in gzip format tar: Child returned status 1 tar: Error is not recoverable: exiting now
Process.php : 254

**Comment by onlinegill** [comment]
Try later it should work I had to try couple times.
