### ISSUE TITLE
Can't install MaxMind Geolite

### ISSUE THREAD

**Issue by roverradio** [AzuraCast/AzuraCast#2299]
Digital Ocean 1-click install. Can't install MaxMind Geo db.

Get a 500 error after pasting key.

The command "'tar' 'xvzf' '/var/azuracast/geoip/geolite.tar.gz' '--strip-components=1'" failed. Exit Code: 2(Misuse of shell builtins) Working directory: /var/azuracast/geoip Output: ================ Error Output: ================ gzip: stdin: not in gzip format tar: Child returned status 1 tar: Error is not recoverable: exiting now
Process.php : 254

**Comment by bjarn** [comment]
Update to the latest version, it fixed the issue for me. :-)

**Comment by Guldstrand** [comment]
I have the same problem and i use the latest version.

**Comment by SlvrEagle23** [comment]
@Guldstrand The latest version doesn't install the MaxMind database directly, it just asks for your license key and then automatically downloads the database internally.

What error are you experiencing?

**Comment by roverradio** [comment]
I had the "latest" version, but had to remove the --release when upgrading to get it to work. As documented here if you're on D.O.

https://marketplace.digitalocean.com/apps/azuracast

**Comment by Guldstrand** [comment]
> @Guldstrand The latest version doesn't install the MaxMind database directly, it just asks for your license key and then automatically downloads the database internally.
> 
> What error are you experiencing?

I hade problem when adding the licence key.
But it finally worked earlier today. Strange!
