### ISSUE TITLE
Make options more visible

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#2301]
Before updating Playlist I was able to modify View Schedule and All Playlists.
I found it very interesting because I put more visible!
How can I do to make these options more visible?

![Screenshot_6](https://user-images.githubusercontent.com/48635610/72539829-b56b2280-385e-11ea-9569-a6a3ecb2848f.png)

**Comment by SlvrEagle23** [comment]
Feature requests should be posted to https://features.azuracast.com/ so we can keep this repository's issues section clear for critical bugs and errors.
