### ISSUE TITLE
M3U

### ISSUE THREAD

**Issue by Richard399** [AzuraCast/AzuraCast#2302]
Hi,

I need to find the /status-json.xsl from the M3U file to add to a webpage field called 'IceCast json URL'

When I download this from the dashboard and read it, all that's in there is the url of the stream?

Am I looking at the correct file to find the /status-json.xsl url?

Many Thanks

Richard

**Comment by SlvrEagle23** [comment]
@Richard399 If your station is on port 8000, then your JSON URL is `http://your-azuracast-url:8000/status-json.xsl`.

**Comment by Richard399** [comment]
HI @SlvrEagle23 

Thank you for responding, I appreciated it.

Okay, here's my stream url :

https://MY-URL.CO.UK:445/radio/8010/radio.mp3

So should this be : 

https://MY-URL.CO.UK:445/radio/8010/status-json.xsl

Many Thanks

Richard

**Comment by SlvrEagle23** [comment]
@Richard399 That should work, but if it doesn't you can also use:

`http://my-url.co.uk:8010/status-json.xsl`

**Comment by Richard399** [comment]
Hi @SlvrEagle23 

Good of you helping ...

I have tried both suggested ways without any success.

On the user AzuraCast dashboard, the url is made up like this :

https://vps.MYWEBSITE.co.uk:445/radio/8010/radio.mp3

So on my webpage in the field called : MP3 Stream URL - I'm using this for the stream :

https://vps.MYWEBSITE.co.uk:445/radio/8010/radio.mp3?1579187361

And it plays/works.

Now ...

I have a field on the webpage called :  MP3 Stream URL and using https://vps.MYWEBSITE.co.uk:8010/status-json.xs

But this is not importing the playlist?

Maybe I'm looking in the wrong place on the dashboard or, the port is not set correctly?

Is there a specific port required as this may have been changed since adding cpanel?

Again, my thanks :-)

Richard

**Comment by SlvrEagle23** [comment]
@Richard399 The plugin you're using isn't really clear on what each of these terms means, or what an example of each one would be. It appears this plugin is just built for generic web radio rather than AzuraCast in particular.

Your "stream URL" should be the one you're using that's working. I'm not sure what other fields you're missing if that one is working?

**Comment by Richard399** [comment]
Hi @SlvrEagle23

Thank you for your assistance with this,

Appreciated :-)
