### ISSUE TITLE
Geolite DB from db-ip.com

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#2303]
Hello, can we use db-ip.com instead of maxmind.com?
https://db-ip.com/db/download/ip-to-city-lite
Direct download would be https://download.db-ip.com/free/dbip-city-lite-2020-01.mmdb.gz

**Comment by SlvrEagle23** [comment]
@LordHelmchen666 It's a valid question, but I'm waiting a bit to see if the policy change enacted by MaxMind (which was, per their legal team, driven by a desire to comply with GDPR and California's privacy act) causes the other IP geolocation providers to scramble to make similar changes.

IP2Location, another large supplier of this type of information, is also already behind a login-wall.

If they do decide to keep theirs more accessible, we may be able to "modularize" how we look for IP geolocation data, and update our attribution message on each page that uses it based on which source we actually found installed.

**Comment by dawibe5626** [comment]
I am not able to create an account on MaxMind due to the following error:
Sorry, we were not able to create your account. Please ensure that you are using an email that is not disposable, and that you are not connecting via a proxy or VPN.

Please introduce an alternative method.

**Comment by SlvrEagle23** [comment]
@dawibe5626 Note that this wasn't _our_ decision to implement the account requirement for MaxMind; we're trying to work around a restriction that was put upon us with very little notice.

Because license keys are standalone from the account that creates them, you can share license keys across multiple installations of AzuraCast. If you can't create an account yourself for whatever reason, you can always ask a friend to create a license key for you (or send you theirs).

**Comment by LordHelmchen666** [comment]
> @LordHelmchen666 It's a valid question, but I'm waiting a bit to see if the policy change enacted by MaxMind (which was, per their legal team, driven by a desire to comply with GDPR and California's privacy act) causes the other IP geolocation providers to scramble to make similar changes.
> 
> IP2Location, another large supplier of this type of information, is also already behind a login-wall.
> 
> If they do decide to keep theirs more accessible, we may be able to "modularize" how we look for IP geolocation data, and update our attribution message on each page that uses it based on which source we actually found installed.

I agree with you. Modularize this would be a nice thing.

**Comment by dawibe5626** [comment]
If anyone could share his/her license key, I would appreciate.
Email: dawibe5626@it-smart.org
