### ISSUE TITLE
Migrate server

### ISSUE THREAD

**Issue by webma5ter23** [AzuraCast/AzuraCast#2304]
Installation: Docker

Hello, I ask to be sure and not to make mistakes, I want to know the best way to migrate Azuracast to another VPS provider, I consider DigitalOcean that you recommend.

But I don't want to lose the settings and radio, statistics and all the work done so far.

Ideally, make a clean installation and then pass the data, I don't know if this can be done.

I appreciate the information.

**Comment by ErnestPH** [comment]
Just use the backup feature... and all you stated will happen

**Comment by webma5ter23** [comment]
> Just use the backup feature... and all you stated will happen

I made the copy, but how do I add the path to reset on the new server?

`./docker.sh restore path-to-backup.zip`
