### ISSUE TITLE
Shoutcast Port re-direction to port 80

### ISSUE THREAD

**Issue by Gujalls** [AzuraCast/AzuraCast#2305]
Hi,

I have seen in other places where the shoutcast stream can be heard in port 80
eg:
http://my-website.com:8020/radio1   -> http://my-website.com/radio1 
http://my-website.com:8030/radio2   -> http://my-website.com/radio2
http://my-website.com:8040/radio3   -> http://my-website.com/radio3
http://my-website.com:8050/radio4   -> http://my-website.com/radio4
http://my-website.com:8060/radio5   -> http://my-website.com/radio5

I'm sure there must be a way to do but don't know how.

Please can you help me how to achieve this in azuracast. 

Many thanks

**Comment by SlvrEagle23** [comment]
@Gujalls This is possible via AzuraCast by enabling the system-wide settling "Use Web Proxy". This will update all of the station listening URLs to a format that looks like `yoursite.com/radio/8000/station.mp3`.

**Comment by Gujalls** [comment]
The Web Proxy is enabled but i dont get the stream as mentioned in your
reply. Changed the number 8000 to the port no where my radios are running.
But didn't work. Am i missing something?
The standard Azurcast is installed in Port 7080 rather than 80. Will it
cause any difference.

Thanks for your help

**Comment by SlvrEagle23** [comment]
@Gujalls Oh, you're trying to actually map port 8000 to port 80. That would be the job of a `docker-compose.override.yml` file with contents similar to:

```yaml
version: '2.2'

services:
  stations:
    ports:
      - '80:8000'
```

**Comment by Gujalls** [comment]
Thanks for the response. As mentioned in my above/below example.
eg:
http://my-website.com:8020/radio1 -> http://my-website.com/radio1
http://my-website.com:8030/radio2 -> http://my-website.com/radio2
http://my-website.com:8040/radio3 -> http://my-website.com/radio3
http://my-website.com:8050/radio4 -> http://my-website.com/radio4
http://my-website.com:8060/radio5 -> http://my-website.com/radio5

Should my docker-composer.override.yml look like below

> version: '2.2'

services:
  stations:
    ports:
      - '80:8020'
      - '80:8030'
      - '80:8040'
      - '80:8050'
      - '80:8060'

Please can you confirm. I also have my main website running at port 80 - believe the above configuration doesn't cause problem.

**Comment by xewl** [comment]
@Gujalls No, you can only do 80:* once, that won't work.
Also, when your site is already on :80 this won't work at all, because it's already used by your own nginx/apache installation.

You will have to proxy the ports in your own nginx/apache configs.
As you have Azura on 7080, the proxy set in the docker image is probably now doing:
`domain:7080/radio/{port}/mount.ext` instead

Thus, if you'd want to proxy the stations, keep the original port range of docker-compose.
Given that your site is ran by nginx, you'll probably need to add the following in that very server {} block.

```
location /radio1 {
    proxy_pass http://127.0.0.1:8000;
}
```
