### ISSUE TITLE
Incorrect host when using Cloudflare and a reverse proxy

### ISSUE THREAD

**Issue by bjarn** [AzuraCast/AzuraCast#2306]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu Server 18.04

**Describe the bug**
Since the change introduced in b6f558eb5478766036531a4ffa88cd014e84c116, the internal IP address is being used as hostname instead of the 'browser url'.

This happens when using Cloudflare and a reverse proxy. This is needed since I am hosting a small private station at home on a server. Won't get into the details, but to provide more servers access to port 80, I use a reverse Nginx proxy for that. In order to hide my IP to the outside world, I put Cloudflare in front of it. This works just fine.

However, as mentioned, since the latest change, something goes wrong and is now using the private IP of the server, as hostname. This breaks cover arts and stream links.

**To Reproduce**
See bug description.

**Expected behavior**
The correct hostname should be used.

**Comment by SlvrEagle23** [comment]
@bjarn While this shouldn't happen if _only_ CloudFlare is in front of your installation, if you're double-proxying like that, then I can see how that would absolutely become a problem.

I've reverted the subset of previous changes that removed the "Prefer Browser URL" setting, so in specific cases like this where it's absolutely necessary to disable it, it can be disabled. It will still be enabled by default and is generally recommended for all users.
