### ISSUE TITLE
Letsencrypt in DigitalOcean App

### ISSUE THREAD

**Issue by webma5ter23** [AzuraCast/AzuraCast#2309]
Installation: Docker in DigitalOcean 

Error when entering commands: 

`./docker.sh letsencrypt-create mydomain.example.com`

![2020-01-18](https://user-images.githubusercontent.com/41419364/72673126-dc834900-3a44-11ea-8162-344369ad9d7f.png)

Missing files?

**Comment by oussamatn** [comment]
Hi, 
Make sure that you have the .env file and the docker-compose.yml in the same directory as you docker.sh

**Comment by SlvrEagle23** [comment]
@webma5ter23 Make sure you're in the `/var/azuracast` directory. By default, there should definitely be a `docker-compose.yml` file in that same directory.

**Comment by webma5ter23** [comment]
Thanks @SlvrEagle23 I didn't realize it and it was in root, I use Putty and I couldn't see the directory where it was.

Please, I need an answer here, I want to migrate a backup to another server but I don't know how to do it.  #2304

Thank you.
