### ISSUE TITLE
Synchronise Azuracast between servers

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2311]
**Using Docker installation method**
 Yes

**Host Operating System**
Ubuntu 18.04

Is there another way to create duplicate "on the flay" for working server? (other than the built in backup option)
I'm looking  for a solusion to synchronise docker between 2 servers in order to keep always one active server and identical copy on backup server that ready to use if the active server will fail

**Comment by dawibe5626** [comment]
I have the same question.

**Comment by SlvrEagle23** [comment]
@eranwo @dawibe5626 Currently, there is no simple way to replicate an existing AzuraCast installation across to a different one. The closest thing we have for redundancy is [AzuraRelay](https://github.com/AzuraCast/AzuraRelay), which adds redundancy to the endpoints your listeners can connect to, but doesn't impact the AutoDJ side.

**Comment by dawibe5626** [comment]
Could you help me how to config AzuraRelay?
