### ISSUE TITLE
Installation failed | Failed to created database stations

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#2316]
Hello guys,
I tried to install AzuraCast to a server behind a corporate http-proxy, so I configured apt, docker and curl to use this proxy, but I was not able to install. Not in docker-mode and not in ansible too (with the same error message)

Information about the system:
ESXi 6.7U3 Host
VM has Ubuntu 18.04.3 LTS installed (AMD64)

btw: the solution in e.g. this thread: https://github.com/AzuraCast/AzuraCast/issues/2035#issuecomment-538614518 does not resolve it.

```
/var/azuracast/www# ./install.sh
Use Docker installation method? (Recommended) [Y/n]
Docker is already installed! Continuing...
Docker Compose is already installed! Continuing...
Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Starting azuracast_mariadb_1  ... done
Starting azuracast_influxdb_1 ... done
Starting azuracast_stations   ... done
Starting azuracast_redis_1    ... done
2020/01/22 08:45:30 Waiting for: tcp://mariadb:3306
2020/01/22 08:45:30 Waiting for: tcp://influxdb:8086
2020/01/22 08:45:30 Connected to tcp://mariadb:3306
2020/01/22 08:45:30 Connected to tcp://influxdb:8086
Installing AzuraCast...
(Environment: production)

AzuraCast Setup
===============

Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...
 * Environment: Production
 * Installation Method: Docker

Setting Up InfluxDB
-------------------


In Database.php line 103:

  Failed to created database stations


In Client.php line 196:

  Query has failed: Invalid JSON


In ResultSet.php line 36:

  Invalid JSON


azuracast:setup [--update] [--load-fixtures] [--release]

2020/01/22 08:45:31 Command exited with error: exit status 1

```

**Comment by MrSteelMiner** [comment]
Information about the system:
ESXi 6.7U3 Host
VM has Ubuntu 18.04.3 LTS installed (AMD64)

**Comment by MrSteelMiner** [comment]
with CentOS 7 as VM-OS, I got the same error...
I think, the corporate proxy is the problem... Any advises?

```
./docker.sh install
Docker is already installed! Continuing...
Docker Compose is already installed! Continuing...
Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Creating volume "azuracast_db_data" with default driver
Creating volume "azuracast_influx_data" with default driver
Creating volume "azuracast_letsencrypt" with default driver
Creating volume "azuracast_shoutcast2_install" with default driver
Creating volume "azuracast_geolite_install" with default driver
Creating volume "azuracast_sftpgo_data" with default driver
Creating volume "azuracast_station_data" with default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_www_data" with default driver
Creating volume "azuracast_redis_data" with default driver
Creating volume "azuracast_backups" with default driver
Creating azuracast_mariadb_1  ... done
Creating azuracast_stations   ... done
Creating azuracast_redis_1    ... done
Creating azuracast_influxdb_1 ... done
2020/01/23 07:55:00 Waiting for: tcp://mariadb:3306
2020/01/23 07:55:00 Waiting for: tcp://influxdb:8086
2020/01/23 07:55:00 Connected to tcp://mariadb:3306
2020/01/23 07:55:00 Connected to tcp://influxdb:8086
Installing AzuraCast...
(Environment: production)

AzuraCast Setup
===============

Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...
 * Environment: Production
 * Installation Method: Docker

Setting Up InfluxDB
-------------------


In Database.php line 103:

  Failed to created database stations


In Client.php line 196:

  Query has failed: Invalid JSON


In ResultSet.php line 36:

  Invalid JSON


azuracast:setup [--update] [--load-fixtures] [--release]

2020/01/23 08:00:01 Command exited with error: exit status 1
azuracast_influxdb_1 is up-to-date
azuracast_redis_1 is up-to-date
azuracast_stations is up-to-date
azuracast_mariadb_1 is up-to-date
Creating azuracast_web ... done

```

**Comment by EthanB-Dev** [comment]
Does it have permission to write databases?

**Comment by MrSteelMiner** [comment]
I think so. It's a blank/default install. 




Mit freundlichen Grüßen


Lee Marvin Stüwe







On Sat, Jan 25, 2020 at 6:38 PM +0100, "EthanB-Dev" <notifications@github.com> wrote:












Does it have permission to write databases?

**Comment by SlvrEagle23** [comment]
@MrSteelMiner This is very bizarre, because the connection between the web application and influxdb is governed by Docker itself and is entirely internal to Docker (or, if you're on Ansible, it's entirely a localhost connection). Nothing outside the server should be interfering with that, unless you've set up iptables rules in such a way that it ends up actually blocking the influxdb connection by accident.

**Comment by MrSteelMiner** [comment]
You're right, it IS very bizarre...

I will check it tomorrow, but i think in the default installation of CentOS 8 and Ubuntu 18.04.3 LTS the iptables are not set by default. 

@SlvrEagle23 is the database-initialising-process accessing/downloading some external ressources from the internet like .sql-files? If yes, there could be the problem. As said, there is a corporate proxy between the ac-installation and the internet.

**Comment by SlvrEagle23** [comment]
@MrSteelMiner Nope, once you're at the Setup step where the database migrations are running (including the InfluxDB migration), there are no external requests being made. The only requests are going back and forth between AzuraCast and its local dependencies (the database and influxdb containers).

**Comment by MrSteelMiner** [comment]
Okay, I've set up a working docker-installation on a KVM-vm on a proxmox host. Then I cloned / converted it to ESXi which is the hypervisor in my company. It seems that ESXi-vms are not compatible with docker. So the problem is not AzuraCast, it's ESXi...
