### ISSUE TITLE
after update all i get is a blank page instead of login page.

### ISSUE THREAD

**Issue by psduk1** [AzuraCast/AzuraCast#2318]
after latest update all i get is a blank page instead of the login page.

**Comment by LordHelmchen666** [comment]
Same here.
docker-compose logs -f
`web_1       | Could not open input file: /var/azuracast/www/util/cli.php
influxdb_1  | [httpd] 172.25.0.6 - - [22/Jan/2020:13:17:18 +0000] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.5.1 curl/7.58.0 PHP/7.4.1" 83c5e591-3d19-11ea-8020-000000000000 1105
web_1       | Could not open input file: /var/azuracast/www/util/cli.php
web_1       | Could not open input file: /var/azuracast/www/util/cli.php
web_1       | Could not open input file: /var/azuracast/www/util/cli.php
web_1       | Could not open input file: /var/azuracast/www/util/cli.php
web_1       | Could not open input file: /var/azuracast/www/util/cli.php
web_1       | Could not open input file: /var/azuracast/www/util/cli.php
web_1       | Could not open input file: /var/azuracast/www/util/cli.php
web_1       | Could not open input file: /var/azuracast/www/util/cli.php
web_1       | Could not open input file: /var/azuracast/www/util/cli.php
web_1       | Could not open input file: /var/azuracast/www/util/cli.php
web_1       | Could not open input file: /var/azuracast/www/util/cli.php
web_1       | Could not open input file: /var/azuracast/www/util/cli.php
web_1       | Could not open input file: /var/azuracast/www/util/cli.php
web_1       | [2020-01-22T13:17:32.416985+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
web_1       | Could not open input file: /var/azuracast/www/util/cli.php
influxdb_1  | [httpd] 172.25.0.6 - - [22/Jan/2020:13:17:32 +0000] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.5.1 curl/7.58.0 PHP/7.4.1" 8c904c0c-3d19-11ea-8021-000000000000 1584
web_1       | Could not open input file: /var/azuracast/www/util/cli.php
web_1       | Could not open input file: /var/azuracast/www/util/cli.php
web_1       | Could not open input file: /var/azuracast/www/util/cli.php
`

**Comment by ernie96** [comment]
I also get that in my own loggs and useing brave i get the this sight isn't working page. On android only the station loads but no other device can load the station or config dashbord

**Comment by WellnessWayUSA** [comment]
Same here

**Comment by SC2Mitch** [comment]
Same issue on our end, exact same errors as Lord, unable to pass through.

**Comment by miguelacjardim** [comment]
Same problem over here with same errors.

**Comment by SlvrEagle23** [comment]
@psduk1 @LordHelmchen666 @ErnestPH @SC2Mitch @miguelacjardim 

I have pushed an update to our Docker Hub that will fix this issue. Please update again and it should resolve the issue. Sorry for the inconvenience!

**Comment by WellnessWayUSA** [comment]
Thank you! Update fixed the issue, appreciate it!!

**Comment by psduk1** [comment]
Thanks, The issue is now fixed and everything is working great again :-)
