### ISSUE TITLE
Jingles

### ISSUE THREAD

**Issue by Richard399** [AzuraCast/AzuraCast#2319]
Hi,

I have created a 4 playlists called 'Jingles' i.e. 'Jingles - M', 'Jingles - A'.

In the 'Music Files' section, I then created a 'Directory' called 'Jingles' in which I have added my jingles files.

With each file, I have added it to say 'Jingles - M' playlist so that it plays that particular file after each song. The Play List 'Jingles - M' has been set as a 'Jingle' using the 'Hide Metadata from Listeners ("Jingle Mode")

However, I think I have a setting wrong as the jingle is not playing at the appropriate time i .e after each song?

Would appreciate some guidance on this as I have been trying for a while now using various settings in trying to get this to work i .e after each song without success.

Hope this made sense :-)

In advance, many thanks

**Comment by Richard399** [comment]
Hi,

Here is an image example of a jingle in 'Playing Next'

Whilst it appears as being 'cued' it does not get played and is skipped to the next song track?

https://imgur.com/TyEtNLi

Playlist Edit Screens :

https://imgur.com/sIgxhw3

https://imgur.com/qKTewl7

https://imgur.com/Ykr4HuJ

I hope this helps working ou why it does not cue and play the jingles; it must be something I have set incorrectly.

Many Thanks 

Many Thanks

**Comment by Richard399** [comment]
I have it :-)

**Comment by diego-vieira** [comment]
@Richard399 care to share what you did?
I'm having the same issue.

I have `Playlist A` that has only music and `Playlist B` which have 3 jingles and I want to play one of the jingles after every song.

Thanks
