### ISSUE TITLE
Nginx Failed

### ISSUE THREAD

**Issue by wilz7** [AzuraCast/AzuraCast#232]
Hi
i get this error can you tell what to do here
`
failed: [localhost] (item=nginx) => {"failed": true, "item": "nginx", "msg": "Unable to start service nginx: Job for nginx.service failed because the control process exited with error code. See \"systemctl status nginx.service\" and \"journalctl -xe\" for details.\n"}
`
Thanks

**Comment by SlvrEagle23** [comment]
@wilz7 Does running `sudo systemctl status nginx.service` return any useful information?

Also, if you haven't done so recently, I'd recommend running the update script, as it should force the correct version of nginx to be installed if it isn't already.

**Comment by wilz7** [comment]
@SlvrEagle23 after running that  i get
`● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2017-09-20 07:47:50 EDT; 3min 16s ago
     Docs: man:nginx(8)
  Process: 15987 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=1/FAILURE)
  Process: 15984 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)

Sep 20 07:47:47 4428.s.time4vps.cloud nginx[15987]: nginx: [emerg] listen() to 0.0.0.0:80, backlog 511 failed (98: Address already in use)
Sep 20 07:47:48 4428.s.time4vps.cloud nginx[15987]: nginx: [emerg] listen() to 0.0.0.0:80, backlog 511 failed (98: Address already in use)
Sep 20 07:47:48 4428.s.time4vps.cloud nginx[15987]: nginx: [emerg] listen() to 0.0.0.0:80, backlog 511 failed (98: Address already in use)
Sep 20 07:47:49 4428.s.time4vps.cloud nginx[15987]: nginx: [emerg] listen() to 0.0.0.0:80, backlog 511 failed (98: Address already in use)
Sep 20 07:47:49 4428.s.time4vps.cloud nginx[15987]: nginx: [emerg] listen() to 0.0.0.0:80, backlog 511 failed (98: Address already in use)
Sep 20 07:47:50 4428.s.time4vps.cloud nginx[15987]: nginx: [emerg] still could not bind()
Sep 20 07:47:50 4428.s.time4vps.cloud systemd[1]: nginx.service: Control process exited, code=exited status=1
Sep 20 07:47:50 4428.s.time4vps.cloud systemd[1]: Failed to start A high performance web server and a reverse proxy server.
Sep 20 07:47:50 4428.s.time4vps.cloud systemd[1]: nginx.service: Unit entered failed state.
Sep 20 07:47:50 4428.s.time4vps.cloud systemd[1]: nginx.service: Failed with result 'exit-code'.`

i used the script as per your instructions bud.

**Comment by wilz7** [comment]
@SlvrEagle23 Managed to solve it
By removing Apache service first.
and then installed the script 
Followed this tutorial to remove apache
[https://community.time4vps.eu/discussion/259/ubuntu-16-04-how-to-install-linux-nginx-mysql-php-lemp-stack/p1](url)

Might be helpful for anyone

**Comment by wilz7** [comment]
Thank you for your help as well

**Comment by petrix** [comment]
Hi everyone,
I'm executed the sudo shell script with this commands:
################
apt-get update
apt-get install -q -y git
mkdir -p /var/azuracast/www
cd /var/azuracast/www
git clone https://github.com/AzuraCast/AzuraCast.git
chmod a+x install.sh
./install.sh
#################

and receive those errors:

TASK [nginx : Install nginx/nchan from deb packages] *********************************************************************************************************
changed: [localhost] => (item=https://nchan.io/download/nginx-common.ubuntu.deb)
failed: [localhost] (item=https://nchan.io/download/nginx-extras.ubuntu.deb) => {"changed": false, "failed": true, "item": "https://nchan.io/download/nginx-extras.ubuntu.deb", "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'liblua5.1-0'' failed: E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).\n", "rc": 100, "stderr": "E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).\n", "stderr_lines": ["E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution)."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nYou might want to run 'apt --fix-broken install' to correct these.\nThe following packages have unmet dependencies:\n nginx-common : Depends: sysv-rc (>= 2.88dsf-24) but it is not installable or\n                         file-rc (>= 0.8.16) but it is not installable\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "You might want to run 'apt --fix-broken install' to correct these.", "The following packages have unmet dependencies:", " nginx-common : Depends: sysv-rc (>= 2.88dsf-24) but it is not installable or", "                         file-rc (>= 0.8.16) but it is not installable"]}

RUNNING HANDLER [azuracast-user : send user notification] ****************************************************************************************************
	to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=40   changed=9    unreachable=0    failed=1   
##########################
What I need to do, guys?

**Comment by SlvrEagle23** [comment]
@wilz7 I wasn't aware that there were web hosts out there that installed Apache2 out of the box. I guess they're expecting most of the hosting traffic to be web-server related.

I pushed an update out to the traditional installer that will uninstall Apache or Lighttpd if either exists on the server prior to the clean installation. Since AzuraCast should always be installed on a clean box (or using Docker), this is generally safe to do.

**Comment by SlvrEagle23** [comment]
@petrix You should make a new issue on the issue tracker for this, since it's not related to the original issue posted here. Also be sure to include what server OS you're using.

**Comment by chubbynugly** [comment]
I have the same issue @petrix  and @SlvrEagle23
