### ISSUE TITLE
Playlist - Total Play Time

### ISSUE THREAD

**Issue by Richard399** [AzuraCast/AzuraCast#2320]
Hi,

Loved learning to use this, such a great project!

So my question :

In order to work out when to 'slot in' a playlist at a particular time, I need to work out the total duration of each list is to ensure that there are enough playing for a specific slot period i.e X tunes for 1 hour

I can see that in each playlist, each tune has total time, but it possible to have a 'Playlist Total Play Time' indicator?

Hope that makes sense?

In advance, my thanks :-)

P.S I can see I can make a donation to the project - may I ask what is a typical / average donation so that I may contribute to this wonderful project?

**Comment by SlvrEagle23** [comment]
@Richard399 Playlists show their total length on the main playlists page on the farthest right column, though it's somewhat approximated for display purposes.

**Comment by Richard399** [comment]
Hi @SlvrEagle23,

Obliged, I was sure it was there somewhere ;-)

Again, my thanks :-)

P.S I can see I can make a donation to the project - may I ask what is a typical / average donation so that I may contribute to your efforts of this wonderful project?

**Comment by SlvrEagle23** [comment]
@Richard399 Our donations vary widely from donor to donor, but our Patreon tiers give you some idea of the kind of donations we recommend based on how heavily you use the software. In the end, it's completely up to you, and any donations of any size are greatly appreciated!

**Comment by Richard399** [comment]
Hi @SlvrEagle23 

Thank you, leave that with me, I'll send it over when I'm all done ;-)
