### ISSUE TITLE
Hide Metadata from Listeners ("Jingle Mode")

### ISSUE THREAD

**Issue by Richard399** [AzuraCast/AzuraCast#2321]
Hi,

Whilst I have been trying to get the jingles to work these past two days ...

I have noticed that :

'Hide Metadata from Listeners ("Jingle Mode")'

When checked, this not only hides it from the 'Listens' page, it also hides it from the 'Admin Dashboard' as well - so you can't tell if the 'Jingles' are scheduled to play correctly.

Not a big problem, just an observation :-)

Regards

**Comment by robz0** [comment]
does wontfix, mean really won't fix or just 'stale'? 
It would be good to see how the jingles and bumpers are doing from the admin pov. 
However I guess with good organisation of labelling etc of playlists, it can work how it is.
