### ISSUE TITLE
Upgraded and Platform is inaccessible

### ISSUE THREAD

**Issue by dawibe5626** [AzuraCast/AzuraCast#2322]
I just upgraded to the last release (a few minutes ago) and the platform is totally inaccessible !!!

**Comment by dawibe5626** [comment]
I am not able to browse https://azuracast.domain.com/login after upgrade.
Get this error:

This page isn’t working azuracast.domain.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by SlvrEagle23** [comment]
I am pushing an update to the Docker Hub that will fix this. Docker Hub is currently taking quite a long time to build the updated version. I will update once it has pushed.

**Comment by dawibe5626** [comment]
I tried to re-install, but I get this error at the end.

Reload System Data
------------------


In ClearCacheCommand.php line 12:

LOADING Redis is loading the dataset in memory
azuracast:setup [--update] [--load-fixtures] [--release]
2020/01/22 20:03:05 Command exited with error: exit status 1

**Comment by SlvrEagle23** [comment]
@dawibe5626 You should now be able to update again and it will resolve the issue.

**Comment by dawibe5626** [comment]
Solved.
