### ISSUE TITLE
Uploaded files with Filezilla not found

### ISSUE THREAD

**Issue by radio2019** [AzuraCast/AzuraCast#2323]
Why does Azurcast don't find a lot of files uploaded with Filezilla?
They are not even shown in the "Music files" section.

In order to let you know what I mean, please take a look at the following screenshots:

https://prnt.sc/qrgqxm
https://prnt.sc/qrgr8s
https://prnt.sc/qrgrno

I have addressed these issues a while ago.
A lot of updates have been made since then, but this problem hasn't been fixed so far. :-/

Can you please take a look at it again and finally fix it in an update?

Thank you.

**Comment by SlvrEagle23** [comment]
@radio2019 Are you using our built-in SFTP service via the Docker installation? That includes a notifier for our main web application that should be preventing that from happening.

**Comment by radio2019** [comment]
Thanks for your question.

The idea behind the RetoSonic Radio was born by some record collectors out of the frustraction that most oldie stations play the same songs on and on again.
That's why we wanted to make a difference by featuring all those forgotten gems from the past which you can't normally hear on the radio.
AzuraCast seems to be a perfect software for that purpose: It's free, open source and offers the possibility to run more than one station on a single server.

RetroSonic Mix, the one with the lagest playlist, already managed to upload more than 14.000 songs in 3 folders: https://prnt.sc/qroejh
The emphasis of that station lies on various genres: http://31.132.36.35:8000

RetroSonic Groove features only R&B from the late 70' and early 80's, it especially covers the disco eara: http://31.132.36.35:8010
RetroSonic Groove should contain a rotation between 10.000 und 11.000 songs after it's finished.

RetroSonic Now, a third station run by a 17-year-old student who thankfully helped us to setup the server and install AzuraCast on it, plays more modern songs and has a smaller playlist of appx. 800 songs: http://31.132.36.35:8020

The problem is that AzuraCast simply doesn't show more than appx. 4000 songs uploaded to the directory of RetroSonic Groove with Filezilla.
Another 6000 MP3 need to be uploaded.

SlvrEagle23, I'll send you our login crendetials (AzuraCast + VPS) to buster[at]busterneece.com from the address bookreader1971[at]gmail.com.
Please help us to fix this issue so that we can bring forward our ambitious project by uploading futher songs to the diretory of RetroSonic Groove with Filezilla. We already spend hours of our leisure time on it. All we want it that AzuraCast finds these songs.

BTW: Thank you very much for launching AzuraCast!
