### ISSUE TITLE
Ansible fresh config error 500

### ISSUE THREAD

**Issue by Xara** [AzuraCast/AzuraCast#2325]
When performing first login, impossible to finish configuration as getting this under 500:
Undefined class constant 'ENABLE_FTP_SERVER'
settings.php : 203

**Comment by Xara** [comment]
P.S. docker is not an option as it mess all my network and add own firewall rules conflicting with mines, previous installation worked fine, after moving to new server, I have this error when finished setup the station and system go to server setup.

**Comment by ogrenci01** [comment]
Hello Everyone;

I have the same problem for Ansible installation. System settings cannot be accessed. It is a problem with the last update.

https://prnt.sc/qrl0im

**Comment by SlvrEagle23** [comment]
@Xara @ogrenci01 This is fixed as of the latest update.
