### ISSUE TITLE
Role back to DB-IP

### ISSUE THREAD

**Issue by dawibe5626** [AzuraCast/AzuraCast#2326]
Is it possible to role back from MaxMind to DB-IP?

**Comment by SlvrEagle23** [comment]
@dawibe5626 Previously, no, but it makes sense that if we're going to have multiple ways of pulling IP geolocation data, that we should allow uninstallation of those same databases.

I've added an "Uninstall GeoLite Database" option to the "Install GeoLite Database" page.
