### ISSUE TITLE
URGENT - Port change applied but not working on control panel

### ISSUE THREAD

**Issue by alexhorner** [AzuraCast/AzuraCast#2327]
**Using Docker installation method**

Yes

**Host Operating System**

Ubuntu 18.04.3 LTS

**Describe the bug**

After changing the Icecast port for the station from 8000 to 8002, the URL for the web proxied stream updated as expected (http://our.server.com/radio/8002/stream), however the URL returns 404 when accessed. The old URL which had the default port 8000 (http://our.server.com/radio/8000/stream) returns a 502 error. When accessing the port directly, everything operates as expected, only the proxy is broken.

If we switch it back to 8000 everything works.

**To Reproduce**

1. Set up a clean install of Azura Docker on Ubuntu 18.04.3 LTS
2. Change the port of the Icecast server from 8000 to 8002
3. Attempt to use the new URL on the profile of the server
4. Attempt to use the old URL

**Expected behavior**

The new URL should work after a port change

**Relevant Logs**

Cannot see any abnormalities within the Event Viewer

**Screenshots**

Old URL:
![image](https://user-images.githubusercontent.com/33007665/73021184-fd6de480-3e1e-11ea-9291-9dc344a2a4d4.png)

New URL:
![image](https://user-images.githubusercontent.com/33007665/73021226-137ba500-3e1f-11ea-9126-cd4382ecbb76.png)

**Device(s):** (shouldn't be applicable but included anyway)
 - Device: Desktop PC
 - OS: Windows 10 Home 1903
 - Browser: Firefox
 - Version: 72.0.1 64 Bit

**Additional context**

If you need additional information, including IP addresses or URLs to see yourself, please DM a developer in the Simulator Radio Discord https://discord.simulatorradio.com/, or reply here for non-private information

**Comment by SlvrEagle23** [comment]
@alexhorner I believe we spoke about this one in person already and have figured it out. If you still have any further questions on this issue just let me know.

**Comment by fast97** [comment]
hello i have the same problem who can help me? thank you
