### ISSUE TITLE
Lag when DJ connect 

### ISSUE THREAD

**Issue by onlinegill** [AzuraCast/AzuraCast#2328]
Docker installation.
Tried to change buffer numbers but when DJ gets contacted radio start lagging or scraching.

**Comment by EthanB-Dev** [comment]
Add a larger buffer size (Go in increments of 5) until it stops lagging.
If it doesn't stop, your VPS/Dedi may need better system requirements, or the DJ has a bad connection to the internet.

If none of the above, you may need to update Azuracast or reinstall it entirely.

I had a similar issue, however, it included AutoDJ lagging. A reinstall fixed it entirely.
