### ISSUE TITLE
ShoutCast DNAS issue

### ISSUE THREAD

**Issue by sahebsharmarbn** [AzuraCast/AzuraCast#2329]
Hello there, please excuse me if I am bothering without any point. I just installed AzuraCast on my Digital Ocean droplet and not found the shoutcast integration. Even I cannot download the specified file on the internet as well as in the shoutcast radio manager. Please guide.

**Comment by ogrenci01** [comment]
Hi @sahebsharmarbn;

It is official Shoutcast. Please check it:

V2.5: https://www.arkacadde.org/sc_serv2_linux_x64-latest.tar.gz

V2.6:
http://download.nullsoft.com/shoutcast/tools/sc_serv2_linux_x64-latest.tar.gz

**Comment by sahebsharmarbn** [comment]
@ogrenci01 thank you so much. It worked so well. Thanks once again.
