### ISSUE TITLE
FTP doesn't work anymore

### ISSUE THREAD

**Issue by PINKfm** [AzuraCast/AzuraCast#2330]
Hello all together,

I have a issue: weeks and months ago it was possible to access the server with the dj accounts via FTP to upload for example new shows and mixes. With the latest updates it doesn't work anymore!

Unfortunately many syndicasters don't use SFTP, so this is not a solution for me. I'm using AzuraCast via the Dockers installation.

**Comment by psduk1** [comment]
Having the same issues, ftp was possible but not its sftp only its difficult for dj's to upload files easily.

**Comment by SlvrEagle23** [comment]
@PINKfm we had a number of technical reasons for switching from FTP to SFTP. We encountered a significant number of problems with serving FTP that are inherent problems with the protocol itself and thus couldn't be easily worked around.

If it's absolutely necessary that you use FTP to accept incoming connections, you can also configure a third-party FTP service that attaches to your `azuracast_station_data` volume. One popular example is this library: https://github.com/stilliard/docker-pure-ftpd
