### ISSUE TITLE
Random but plenty forgetful transitions when Live

### ISSUE THREAD

**Issue by xewl** [AzuraCast/AzuraCast#2332]
**Using Docker installation method**
Yes, v0.9.7.1, #85808f3 (2019-11-16 22:56)

**Host Operating System**
Ubuntu 18.04.2 LTS

**Describe the bug**
At random intervals, Liquidsoap seems to fade out and fade back in a live stream. (~2sec interruptions)

**To Reproduce**
Not sure yet, it runs on 2 different servers, only 1 has had this phenomenon for a few weeks on hand.
Both servers get the same input from the studio. It's behavior is occurring seemingly at random. It could go 2 hours unnoticed, and 3 times in 5 minutes.

I'm not able to see if the source is actually disconnecting (According to the studio PC, it's not), but it "seems to be" disconnecting, and restarting. A second Azuracast server handles the exact same stream, but does not show this behavior. The specs are identical.

**Expected behavior**
A smooth live-stream without random hick-ups, or at least a logged reason why it is happening /s

**Relevant Logs**
Snippet of one instance (Normal):
```
2020/01/24 18:24:44 [REDACTED_live_fallback:3] Switch to blank_7715 with forgetful transition.
2020/01/24 18:24:44 [dummy:3] Source failed (no more tracks) stopping output...
2020/01/24 18:24:44 [cross_7724:3] Analysis: -11.297403dB / -infdB (2.98s / 2.90s)
2020/01/24 18:24:44 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/01/24 18:24:47 [cross_7724:3] Analysis: -infdB / -infdB (1.98s / 2.00s)
2020/01/24 18:24:47 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/01/24 18:24:49 [REDACTED_live_fallback:3] Switch to audio_to_stereo_7712 with forgetful transition.
2020/01/24 18:24:49 [cross_7724:3] Analysis: -nandB / -20.638237dB (0.00s / 0.02s)
2020/01/24 18:24:49 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
```

Somewhat more recent, longer hickup (Smart):
```
2020/01/24 19:36:13 [cross_7724:3] Analysis: -infdB / -infdB (0.04s / 0.04s)
2020/01/24 19:36:13 [crossfade:3] Old <= medium, new <= medium and |old-new| <= margin.
2020/01/24 19:36:13 [crossfade:3] Old and new source are not too loud and close.
2020/01/24 19:36:13 [crossfade:3] Transition: crossed, fade-in, fade-out.
2020/01/24 19:36:13 [cross_7724:3] Analysis: -infdB / -infdB (1.96s / 1.96s)
2020/01/24 19:36:13 [crossfade:3] Old <= medium, new <= medium and |old-new| <= margin.
2020/01/24 19:36:13 [crossfade:3] Old and new source are not too loud and close.
2020/01/24 19:36:13 [crossfade:3] Transition: crossed, fade-in, fade-out.
2020/01/24 19:36:15 [REDACTED_live_fallback:3] Switch to audio_to_stereo_7712 with transition.
2020/01/24 19:36:15 [cross_7724:3] Analysis: -infdB / -6.701512dB (0.04s / 0.04s)
2020/01/24 19:36:15 [crossfade:3] No transition: using default.
```

**Screenshots**
N/A

**Device(s):**
N/A (Any that receive the stream)

**Additional context**
Cross-fade mode from normal to smart makes the hickups worse (they're not gone, just not smoothed out anymore).
Streaming is done to `source`, thus not via a specific DJ Account
Auto-DJ is on & _no_ fall-back mount was set on the mount points.
There are no custom configs set for Liquidsoap.
Listener count not a variable (happens regardless of 5 or 50 listeners)

Thinking: is it analyzing the stream being quiet (dB)?
I'm mostly posting this to see if I'm still sane, and if other people are having this occur.

**Comment by ismaelazanza** [comment]
I'm also experiencing the same problem, I still can't solve it even though I've used some options. I hope it can be corrected

**Comment by ismaelazanza** [comment]
2020/01/24 11:04:34 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/01/24 15:36:11 [pasin_ecuatoriana_live_fallback:3] Switch to blank_7693 with forgetful transition.
2020/01/24 15:36:11 [dummy:3] Source failed (no more tracks) stopping output...
2020/01/24 15:36:11 [cross_7706:3] Analysis: -15.878761dB / -infdB (3.00s / 1.96s)
2020/01/24 15:36:11 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/01/24 15:36:14 [cross_7706:3] Analysis: -infdB / -infdB (1.96s / 2.00s)
2020/01/24 15:36:14 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/01/24 15:36:16 [pasin_ecuatoriana_live_fallback:3] Switch to audio_to_stereo_7690 with forgetful transition.
2020/01/24 15:36:16 [cross_7706:3] Analysis: -nandB / -15.139399dB (0.00s / 0.00s)
2020/01/24 15:36:16 [crossfade:3] Simple transition: crossed, fade-in, fade-out.

**Comment by EthanB-Dev** [comment]
I don't know the answer, but it might be worth adding a larger buffer to see if that helps.

**Comment by xewl** [comment]
It could be buffer-related, but the thing is....

I've rebooted the server, it went on doing it for about the first 20 minutes, though;
I haven't noticed any drops for a week now. x)

It's not really identifiable outside of the logs I did get (op).
