### ISSUE TITLE
unable to connect in SFTP mode to upload files 

### ISSUE THREAD

**Issue by psduk1** [AzuraCast/AzuraCast#2333]
Installation method
Docker

Host OS (for Docker installations)
Ubuntu 18.04

since last update users are unable to connect in SFTP mode to upload files to there radio station media folders.
Filezilla shows 
Error:        	Authentication failed.
Error:        	Critical error: Could not connect to server

Thank you
Please help

**Comment by SlvrEagle23** [comment]
@psduk1 Are you connecting with the new SFTP usernames/passwords? We no longer use your account credentials when connecting to the built-in SFTP service.

If you're on an installation of AzuraCast powered by our DigitalOcean marketplace template, you may also need to enable the SFTP port in the host server's firewall, via:

```
ufw allow 2022
ufw enable
```

**Comment by psduk1** [comment]
new SFTP usernames/passwords and on own server with 2022 allowed but still get this error on every account.
Normal FTP was working fine with no issues at all.

**Comment by dannyodj** [comment]
@SlvrEagle23 
hello i have the same problem , i was able to get connected with sftp with no problem ,but after update azuracast yesterday now im not able to get access with sftp in any account. im getting this message in filezilla:

Status:	Disconnected from server
Status:	Connecting to 136.243.19.165:2022...
Response:	fzSftp started, protocol_version=9
Command:	open "daniel@136.243.19.165" 2022
Command:	Trust new Hostkey: Once
Command:	Pass: ********
Error:	Authentication failed.
Error:	Critical error: Could not connect to server
----------
Its the same thing for all users in all radios no one can get acess with sftp anymore!
what do i need to do? 
please help

**Comment by SC2Mitch** [comment]
```
Response:	fzSftp started, protocol_version=8
Command:	open "mitch@5.189.186.220" 2022
Command:	Trust new Hostkey: Once
Command:	Pass: ****
Error:	Authentication failed.
Error:	Critical error: Could not connect to server

```
Same issues on our end.

**Comment by psduk1** [comment]
Still can't get sftp working, tried it now on 2 different servers both on different networks too.
with default port:2022 i get 
Error:	Authentication failed.
Error:	Critical error: Could not connect to server
in filezilla, and if i add an alternative port in .env and then restart docker, is exactly the same.
Do we have any ideas on how to solve the problem, or is there a way to revert back to ftp ? as this worked without any issues.

**Comment by dannyodj** [comment]
yep we are waiting for this fix

**Comment by SlvrEagle23** [comment]
We are not planning to go back to supporting FTP. There were a number of technical reasons why we switched away from FTP to SFTP, which we outlined in the 0.9.8.1 release notes and elsewhere online, and those issues are still valid.

I'm unfortunately unable to reproduce this error locally; on my local installation, sftp works without any issues at all and successfully authenticates.

In order for me to more accurately diagnose what's going on, there are two logs that could be checked:

1) The main `web` container log (from the host, `docker-compose logs -f web`)
2) The SFTPgo log itself (from the host, `docker-compose exec --user=azuracast web tail -f ~/sftpgo/sftpgo.log`)

Check both of these logs as you're trying to connect to see if there's any obvious answer as to why it's not connecting.

**Comment by SC2Mitch** [comment]
> We are not planning to go back to supporting FTP. There were a number of technical reasons why we switched away from FTP to SFTP, which we outlined in the 0.9.8.1 release notes and elsewhere online, and those issues are still valid.
> 
> I'm unfortunately unable to reproduce this error locally; on my local installation, sftp works without any issues at all and successfully authenticates.
> 
> In order for me to more accurately diagnose what's going on, there are two logs that could be checked:
> 
> 1. The main `web` container log (from the host, `docker-compose logs -f web`)
> 2. The SFTPgo log itself (from the host, `docker-compose exec --user=azuracast web tail -f ~/sftpgo/sftpgo.log`)
> 
> Check both of these logs as you're trying to connect to see if there's any obvious answer as to why it's not connecting.

I've attempted to locate the log itself but on my instance it returns a file not found 
![image](https://user-images.githubusercontent.com/29955942/73354174-f9155180-428c-11ea-9f83-fecc9e026351.png)

But from trying the web container logs it doesn't provide a valid response.  (Yes I've attempted with the direct IP as well) 
![image](https://user-images.githubusercontent.com/29955942/73354220-1518f300-428d-11ea-8a72-72fbe2a2da3f.png)

**Comment by jayhill90** [comment]
@SC2Mitch try putting sftp:// in front of your IP address or hostname.

**Comment by SC2Mitch** [comment]
> @SC2Mitch try putting sftp:// in front of your IP address or hostname.

Tried, still results in same error
![image](https://user-images.githubusercontent.com/29955942/73400018-2fc88780-42e0-11ea-8be3-00ff09640938.png)

**Comment by psduk1** [comment]
I have checked both of the logs listed above (docker-compose logs -f web) does not show anything obvious or anything related to "sftp"
The log command (docker-compose exec --user=azuracast web tail -f ~/sftpgo/sftpgo.log) for sftpgo.log returns an error that the log does not exist.
I have tried everything I can think of, restarted docker and even tried different ports but nothing seems to work.

**Comment by SlvrEagle23** [comment]
@psduk1 @SC2Mitch Let's try splitting that second command into two steps:

```
docker-compose exec --user=azuracast web bash
```
then, in the shell it gives you:
```
tail -f ~/sftpgo/sftpgo.log
```

**Comment by SC2Mitch** [comment]
Here we are @SlvrEagle23 all the logs. 

```
{"level":"debug","time":"2020-01-29T23:16:40.049","sender":"connection_failed","client_ip":"86.2.124.42","username":"mitchtest","login_type":"password","error":"External auth error: exit status 1"}
{"level":"warn","time":"2020-01-29T23:16:40.108","sender":"sftpd","connection_id":"","message":"failed to accept an incoming connection: [ssh: no auth passed yet, Authentication error: could not validate password credentials: External auth error: exit status 1]"}

```

**Comment by SC2Mitch** [comment]
Sorry for the many edits, me and some users was testing it and ran into this error.

**Comment by SlvrEagle23** [comment]
@SC2Mitch ah perfect, that's the log entry I was looking for. Just pushed an update up, update and let me know if it helps.

**Comment by psduk1** [comment]
sftp working great now, but after update i'm now getting multiple lists of stations on the dashboad, as though its cloned a station multiple times, but unable to delete any of them as if i try `i get a 500 error.

**Comment by SC2Mitch** [comment]
> @SC2Mitch ah perfect, that's the log entry I was looking for. Just pushed an update up, update and let me know if it helps.

It works like a charm now.

**Comment by dannyodj** [comment]
> @SC2Mitch ah perfect, that's the log entry I was looking for. Just pushed an update up, update and let me know if it helps.

After update the server , SFTP work great
