### ISSUE TITLE
Music File Structure

### ISSUE THREAD

**Issue by Richard399** [AzuraCast/AzuraCast#2336]
Hi,

Just checking that I have the structure correct in terms of how and where I store music files in the dashboard :

In the main dashboard, I have created subdirectories to each play period i.e. MORNING, AFTERNOON ETC, placing the applicable tracks within each and then, assign them to a playlist.

I have also done this for the Jingles, placing them inside this folder and then assign each jingle to the respective playlist period .i.e. Jingles - Morning, Jingles - Afternoon

Is this correct, please?

Many Thanks

**Comment by SlvrEagle23** [comment]
@Richard399 This sounds fine based on your description.

Many of these questions you're posting aren't really issues that merit the attention of the AzuraCast team ourselves. They would likely be answered just as well by joining our [Slack](https://azuracast.com/slack) or [Discord](https://azuracast.com/discord) communities, perhaps more quickly as well.

**Comment by Richard399** [comment]
Hi SlvrEagle23,

Oh, I see, my apologies,

I will do that.

Many Thanks

**Comment by SlvrEagle23** [comment]
@Richard399 It's not a major problem, it would just likely be a better experience for you, and would help us keep our GitHub issues section cleaner.
