### ISSUE TITLE
Issues installing AzuraCast

### ISSUE THREAD

**Issue by EthanTK** [AzuraCast/AzuraCast#2337]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04.3 (LTS) x64

**Describe the bug**
I'm getting an error when installing AzuraCast. The error is:
```
curl:  (22) The requested URL returned error: 404 No Found
chmod: cannot access '/usr/local/bin/docker-compose': No such file or directory
./docker.sh: line 119: docker-compose: command not found
./docker.sh: line 120: docker-compose: command not found
./docker.sh: line 121: docker-compose: command not found
```

**To Reproduce**
Install AzuraCast with Docker Compose. 

**Expected behavior**
It to complete the install.

**Comment by EthanB-Dev** [comment]
Have you made sure Docker and Docker-Compose has been installed to your VPS/Dedicated Server?

**Comment by SlvrEagle23** [comment]
@EthanTK This may be resolved as of the latest version of the Docker utility script. Try running:

```bash
./docker.sh update-self
./docker.sh install
```

**Comment by DamonOnYT** [comment]
I experienced the same issue when installing. I ended up running a manual install of docker-compose https://docs.docker.com/compose/install/
