### ISSUE TITLE
Scheduling Per Songs/Per Minute doesn't trigger the Song, it ignores the playlist

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2338]
**Using Docker installation method**

Yes
**Host Operating System**

CentOS
**Describe the bug**

We have two playlists currently running, One that has the music, one that has a bunch of advertisements, Azuracast is for some reason ignoring the Advertisement playlist and continues to run the main one, I've listened to it and it never triggers the songs. 
**To Reproduce**

**Expected behavior**

It to play the songs on time. 
**Relevant Logs**

**Screenshots**
Current Playing Next
![image](https://user-images.githubusercontent.com/29955942/73125802-f2dc5800-3fa2-11ea-9e54-f8b2aae908d1.png)
Our Playlist configurations
![image](https://user-images.githubusercontent.com/29955942/73125824-25865080-3fa3-11ea-87b9-70403d544ae3.png)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 
Windows 10, Chrome latest. 
**Additional context**

**Comment by SC2Mitch** [comment]
Closing, restarting the station should wake the station up to new playlist changes.

**Comment by SC2Mitch** [comment]
This issue has since returned, no matter what I do, it'll continues to play one playlist.

**Comment by EthanB-Dev** [comment]
Doesnt seem to be happening with me. I have a sweep playlist that plays a sweep after every song, then 2 advertisement playlists that play 1 ad at x:15 and x:45.
![image](https://user-images.githubusercontent.com/60297469/73133656-c583be80-4023-11ea-849d-a2dbb332cc85.png)
What I have noticed is that scheduling it at a time will wait until the song is over. With this in mind, try making sure that "Merge playlist to play as a single track." is turned off for the main song playlist as it will think it is one song.
![image](https://user-images.githubusercontent.com/60297469/73133670-f49a3000-4023-11ea-9f11-34bb615e6bef.png)

**Comment by jdrodriguez** [comment]
I am having the same issue with playlist scheduled for a specific minute or scheduled to play after a specific amount of songs. They are either just skipping the playlist all together and then when it actually plays, sometimes it plays 2 tracks from the playlist even when I have it set to play only 1 track at scheduled time.

**Comment by SC2Mitch** [comment]
After tinkering within the playlists I was able to kinda fix this
