### ISSUE TITLE
Cron tabs not created in ansible install

### ISSUE THREAD

**Issue by Xara** [AzuraCast/AzuraCast#2339]
Well issue is that cron tables are not created and all and   the link from www/config/cli.php to www/utils/cli.php is not created

**Using Docker installation method**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@Xara This should be fixed as of the latest update.
