### ISSUE TITLE
Metadata not displayed on azuracast admin interface

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#234]
SInce I added a second station to my azuracast (docker installation), the metadata display is not updated anymore. It shows only the default title (title of music - artist name). On my browser debug tool, I see that the API is called and gets answered with correct values. on the Js view, there is following error 
```
Uncaught TypeError: Cannot read property 'id' of undefined
    at NchanSubscriber.<anonymous> ((index):310)
    at NchanSubscriber.Emitter.emit (nchan.js?c512cda73ce7b123:65)
    at WSWrapper.<anonymous> (nchan.js?c512cda73ce7b123:629)
```
Clicking on the index:310 line, I get following error :

22 (and increasing)  Uncaught TypeError: Cannot read property 'id' of undefined 
on following line:
`var station_row = $('#station_' + row.station.id);`

**Comment by SlvrEagle23** [comment]
@griffon56 Good catch, should be fixed now. Thanks :D

**Comment by griffon56** [comment]
indeed, the bug is fixed many thanks!
BTW  the docker update now runs smoothly without error on my low-power VPS and it is a pleasure to use your project.

**Comment by griffon56** [comment]
I think the fix had a side effect on the hourly cleanup task which is longer performed. When forcing it I get following error :

An exception occurred while executing 'INSERT INTO analytics (station_id, type, timestamp, number_min, number_max, number_avg) VALUES (?, ?, ?, ?, ?, ?)' with params ["14", "day", 1506556800, 0, 1, 0]: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`azuracast`.`analytics`, CONSTRAINT `FK_EAC2E68821BDB235` FOREIGN KEY (`station_id`) REFERENCES `station` (`id`) ON DELETE CASCADE)

**Comment by SlvrEagle23** [comment]
@griffon56 It turns out this was a bug affecting anyone with a deleted station. It's not a major issue, as the `analytics` table is mostly intended as a backup for InfluxDB, which actually does the heavy lifting of statistics, so `analytics` is never referenced directly in the code (other than in that one spot).

Should be fixed now in any case. :)

**Comment by griffon56** [comment]
I confirm the latter bug is also fixed :)
