### ISSUE TITLE
Relay from schoutcast v2 not working

### ISSUE THREAD

**Issue by Xara** [AzuraCast/AzuraCast#2340]
Hello, first, thank you for great stuff that you give to us, great work!

**Using Docker installation method**

No
**Host Operating System**

Ubuntu 18.04
**Describe the bug**

The relay from sc v.2 working partially, I am getting current title/time/listeners but stream is empty
**To Reproduce**
Set a relay from a sc server V2 Windows sid1 (not tested other sids but with or without here is no output stream)

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@Xara How are you setting up the relay? You're saying the metadata is being sent over correctly, but the audio itself isn't?

**Comment by Xara** [comment]
Hello
I set to simple relay in administration, I am getting metadata but here is no stream in output, or more correct, here is an empty stream
