### ISSUE TITLE
Metadata update may have failed with error / Too much latency! Resetting active sources

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#2342]
Hi, 

anybody an idea what could have caused this? A scheduled show started all right, then five minutes into it this happened (see Liquidsoap log excerpt).  

Installation: v0.9.8, #c72be08 (2019-12-15 8:53)

```
2020/01/27 17:05:23 [lang:3] AzuraCast Feedback Response: OK
2020/01/27 17:05:23 [radio_local_1:3] Metadata update may have failed with error: 400, Bad Request (HTTP/1.0)
2020/01/27 17:05:23 [clock.wallclock_main:2] Too much latency! Resetting active sources...
2020/01/27 17:05:23 [radio_local_1:3] Closing connection...
2020/01/27 17:05:23 [radio_local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2020/01/27 17:05:23 [radio_local_1:3] Connection setup was successful.
```

**Comment by SC2Mitch** [comment]
System specs? It might be related to memory usage, it can't keep up.

**Comment by gammaw** [comment]
@SC2Mitch 2GB memory, out of which usually 10% is free. It's a server hosting a single Azuracast instance (Docker). Is it normal?

**Comment by SC2Mitch** [comment]
I'd personally advise upping to 4GB, to hopefully clear this issue up.

**Comment by gammaw** [comment]
Yeah, I see it in the system reqs that >2GB may be necessary (https://www.azuracast.com/install/). Thanks for the hint.

**Comment by gammaw** [comment]
@SC2Mitch one more thing. Any argument against upgrading to 3GB first? The 4GB tier comes with 2 vCPU instead f 1, but it's also more expensive. Can a dockerized Azuracast instance benefit from 2 vCPU?

**Comment by SC2Mitch** [comment]
> @SC2Mitch one more thing. Any argument against upgrading to 3GB first? The 4GB tier comes with 2 vCPU instead f 1, but it's also more expensive. Can a dockerized Azuracast instance benefit from 2 vCPU?

No real argument there, just 4 is the sweet spot for us personally.

**Comment by gammaw** [comment]
I see. And how about the vCPU utilization? Would it make a difference giving it more than one vCPU?

**Comment by SC2Mitch** [comment]
> I see. And how about the vCPU utilization? Would it make a difference giving it more than one vCPU?

Azuracast is really light on the CPU workload, it's not that demanding, unless it's under extreme loads such as large scale backups (20GB++) or other things, if anything it just needs a bit more memory overhead.

**Comment by gammaw** [comment]
I see, thanks. Strange, we upgraded from 2 to 3GB and Azuracast seems to use all additional memory. Before and after the upgrade it's still around 200K free memory the system has. What do you think?
