### ISSUE TITLE
Some problems (current song, WebDJ and public station page)

### ISSUE THREAD

**Issue by addictif80** [AzuraCast/AzuraCast#2344]
Hello,
new user of AzuraCast, I find this tool great, however, I encounter some problems.

The "On air" frame on the station's "profile" page is only updated if I click "Execute the task" in the "Current track data" frame from the administration.
The same is true for monitoring the number of listeners.

In addition, when I click on WebDJ, fill in the identifiers of a streamer and click on "Start broadcasting", nothing happens on the air, the playlist is still being played.

Finally, when I go to the public page of the station, the title is displayed well (provided that you have executed the task "Data of the current title") but no sound comes out, and the history of the titles does not work not, displaying a simple "1. Music title / Music artist".

If you have ideas to correct this problem, I will be interested.

System info:
Linux : Ubuntu Server 18.04.3 LTS
Arch : x64
AzuraCast : v.0.9.8.1

**Comment by SC2Mitch** [comment]
Web DJ has some significant issues, when I attempted to even load it, I get flooded with error logs, over 1000 of them. It doesn't go 'on air' at all, the logs doesn't even say it was attempted.

**Comment by SlvrEagle23** [comment]
@addictif80 Hello!

As a request, we ask that you limit GitHub issues to "one issue per issue"; that is, one problem or error report per GitHub issue, so we can actually track the progress of that issue as it's resolved or worked on by our team.

Also, some of these problems have been reported by other users, so you may be able to find solutions within existing issues that are already posted here on GitHub.
