### ISSUE TITLE
Scheduled Time

### ISSUE THREAD

**Issue by Radio-Quergedacht** [AzuraCast/AzuraCast#2345]
I cannot save scheduled time
Image link https://radio-quergedacht.fm/bild.png

**Comment by SlvrEagle23** [comment]
@Radio-Quergedacht It doesn't appear that the link you provided is valid. You can attach images directly to GitHub comments by clicking and dragging them into the message itself.

Any log information you can provide (either from your console or from the server side, via the Log Viewer on the system administration page) would also be helpful in diagnosing the issue.
