### ISSUE TITLE
Failed to load API definition 

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2347]
**Using Docker installation method**

Yes
**Host Operating System**

Centos7
**Describe the bug**

Unable to retrieve my API definitions
**To Reproduce**

Go to `radio.domain.com/api` and see the error
**Expected behavior**

Show the API and its definitions
**Relevant Logs**

Internal Server Error /api/openapi.yml

**Screenshots**

![image](https://user-images.githubusercontent.com/29955942/73234333-79e72700-4181-11ea-80dd-487bdf20a00d.png)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 
win10, chrome latest. 
**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch Should be fixed as of the latest update.
