### ISSUE TITLE
LIVE DJ Mode

### ISSUE THREAD

**Issue by Richard399** [AzuraCast/AzuraCast#2349]
Hi,

Moving to learn about the 'LIVE DJ Mode' of this excellent system.

I looked on YouTube for some instructional guidance on how best to use it but nothing worthy of note.

Does anyone have or made one, please?

Many Thanks :

**Comment by SC2Mitch** [comment]
Hi!

You can view a few guides for DJ mode here
https://www.azuracast.com/help/streaming_software.html

**Comment by Richard399** [comment]
Hi @SC2Mitch

Thank you for that :-)

**Comment by SC2Mitch** [comment]
Oh I see, I believe that system is fairly basic, you'd be better off using one of the 3rd party programs and 'hooking' into the station. I can look into making a guide for the built in station.

**Comment by Richard399** [comment]
Hi




I would appreciate that very much as I'm not a DJ, just developer :-)




On Tue, Jan 28, 2020 at 1:48 PM +0000, "SC2Mitch" <notifications@github.com> wrote:












Oh I see, I believe that system is fairly basic, you'd be better off using one of the 3rd party programs and 'hooking' into the station. I can look into making a guide for the built in station.

**Comment by SC2Mitch** [comment]
A guide on how to do this shall be completed later this evening.

**Comment by Richard399** [comment]
Hi,

That's very helpful of you, many thanks!

I will, when getting more familiar,  make some videos on various aspects and post to YouTube to help others :-)

**Comment by EthanB-Dev** [comment]
There are a bunch of third party programs that allow you to broadcast live. Some of which can be found on the Acuracast website.
A bunch of programs I would recommend follow:
SAM Broadcaster
Mixxx
VirtualDJ
Etc.
