### ISSUE TITLE
chooser destination folder of Docker Volume Backup

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#235]
The docker backup script creates an archive in the app folder of the machine with all media files. Hence my understanding is that the host machine needs to have **twice** free space of all the media files if we want to backup.
Would it be possible to set the destination folder of the docker backup such as /mnt folder ? The user could mount this to a sshfs, or attach a volume (digitaloceanà and would not need to double the stage space?

**Comment by SlvrEagle23** [comment]
@griffon56 Definitely a valid point, especially considering the possible number of people using lower-cost VPSes that are already low on storage.

I've updated both the `docker-backup.sh` and `docker-restore.sh` scripts to accept a fully arbitrary path as their optional first argument.

**Comment by griffon56** [comment]
many thanks for the quick implementation !
