### ISSUE TITLE
Streamer profiles with same name can be created multiple times

### ISSUE THREAD

**Issue by pvj** [AzuraCast/AzuraCast#2351]
**Using Docker installation method**

Yes

**Host Operating System**

ubuntu 16.04

**Describe the bug**

It is possible to add streamer accounts with the same unique key (and then different passwords) multiple times. 

**To Reproduce**

1. Go to streamer/dj profiles tab
2. then add new user with any name key
3. add again new user -- this time same name key as previously in step 2.

**Expected behavior**

At step 3. an error message. No new user is created (or if it is permitted on purpose because of different backends such as shoutcast / icecast, scope it to same backend or produce warning).

**Relevant Logs**

n/a

**Screenshots**

<img width="968" alt="Screenshot 2020-01-28 at 21 31 04" src="https://user-images.githubusercontent.com/2641791/73303123-1824cc80-4216-11ea-84bd-c7a2c32ef1d3.png">
<img width="995" alt="Screenshot 2020-01-28 at 21 31 18" src="https://user-images.githubusercontent.com/2641791/73303124-18bd6300-4216-11ea-99d4-f9e4d71f5d91.png">

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 
Firefox 68-esr

**Additional context**

n/a

**Comment by SlvrEagle23** [comment]
@pvj This has been fixed in our latest update from this evening, which introduces live broadcast history tracking and broadcast recording.

**Comment by pvj** [comment]
@SlvrEagle23 Thank you. You're good.
