### ISSUE TITLE
Merge playlist to play as a single track.

### ISSUE THREAD

**Issue by Rafaelrds2017** [AzuraCast/AzuraCast#2352]
Merge playlist to play as a single track.

THAT OPTION ABOVE. IS NOT WORKING. PROBABLY THEREFORE MY COMMERCIAL WILL NOT GO TO AIR
![20200128_220227](https://user-images.githubusercontent.com/31827151/73319121-3391d680-421a-11ea-8515-b0be62f7c38a.jpg)

**Comment by Rafaelrds2017** [comment]
Anyone else with this problem in AutoDj?

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 for these settings, as the label suggests, we depend on Liquidsoap to make these functions work. In a lot of cases, the results are unpredictable as a result of issues beyond our control. We've reached out to their team before for assistance with figuring these things out, but it isn't a really high priority for them at the moment.

**Comment by Rafaelrds2017** [comment]
> @ Rafaelrds2017 para essas configurações, como sugere o rótulo, dependemos do Liquidsoap para que essas funções funcionem. Em muitos casos, os resultados são imprevisíveis como resultado de problemas fora do nosso controle. Já contatamos a equipe deles antes para obter ajuda para descobrir essas coisas, mas não é uma prioridade muito alta para elas no momento.

OK thank you. another mistake is in repetition. many repetitions, several equal audios playing in the sequence.
