### ISSUE TITLE
Is it possible to use SHOUTcast ads

### ISSUE THREAD

**Issue by FLAME878** [AzuraCast/AzuraCast#2355]
I was wondering if the SHOUTcast ads could work, I have had the station playing for a while and have not seen any metadata adverts. On the admin panel, it has the "$" next to the station so it says it's being monetized.

**Comment by SC2Mitch** [comment]
Do you have your Shoutcast AuthHash assigned properly?

**Comment by FLAME878** [comment]
Yes its correct, and it didn't come up with any errors.

**Comment by SC2Mitch** [comment]
Anything of relevence in your Station Logs files? If not, then I'm at a loss, it's probably Shoutcast doing proprietary things, which makes my support beyond limited.

**Comment by FLAME878** [comment]
Other than my website logo, no, all that is a square "S"
