### ISSUE TITLE
Song Duplicates

### ISSUE THREAD

**Issue by Richard399** [AzuraCast/AzuraCast#2357]
Hi,

Looking in the 'Reports' section, I can see a few 'Song Duplicates' which are stored in their own 'Music Directories' such as 'MORNING' and as such, each are assigned to separate 'Playlists'.

Maybe I have the structure incorrect as I wanted the same 'Track 1' to play for more than one 'Playlist'?

As an example :

MORNING > Track 1
EVENING > Track 1

If I were to just place all the tracks in one area, it would prove to be difficult identifying which track to play for what Playlist and Genre.

I hope that makes sense?

Many Thanks :-)

**Comment by SlvrEagle23** [comment]
@Richard399 Playlists aren't associated specifically with folders (at least this isn't a currently available feature), so you can have the same file in more than one playlist if you want. Just check both playlist checkboxes when setting the playlists for that file.

**Comment by Richard399** [comment]
Hi SlvrEagle23,

In MUSIC FILES I have created Sub Directories like this :

MORNING
AFTERNOON
EVENING

In each, placed tracks related to that part of the day so the MORNING is Upbeat, the EVENING is Downbeat, I then selected say MORNING and assign all the tracks within it to the MORNING PLAYLIST

Hope that makes sense :-)

Regards

**Comment by SlvrEagle23** [comment]
@Richard399 That makes sense...but I'm not sure what the problem is.

If the duplicate report finds songs in multiple folders, it doesn't mean you have to do anything about it, as it isn't a problem, it's just helping you identify potential duplication in case this is undesirable.

**Comment by Richard399** [comment]
Hi,

Thanks for that,

I was thinking more about the 'disk space' as I am trying to preserve as much as I can.

Obliged :-)

**Comment by Richard399** [comment]
Now on SLACK :-)
