### ISSUE TITLE
cannot stat ‘docker-compose.new.yml’: No such file or directory - Command not found

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2358]
**Using Docker installation method**
Yes
**Host Operating System**
CentOS7
**Describe the bug**
Unable to conduct a update today, returns docker command not found errors
**To Reproduce**
Use puTTY to connect to your machine, go to cd /var/azuracast and try `./docker.sh update-self` and then `./docker.sh update`
**Expected behavior**
A update to occur
**Relevant Logs**
```[mitch@dashboard azuracast]$ sudo ./docker.sh update-self
New Docker utility script downloaded.
[mitch@dashboard azuracast]$ sudo ./docker.sh update
[mitch@dashboard azuracast]$ ./docker.sh update
curl: (23) Failed writing body (0 != 1874)
The docker-compose.yml file has changed since your version. Overwrite? This will overwrite any customizations you made to this file? [Y/n] y
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose.new.yml'
cp: cannot create regular file ‘docker-compose.backup.yml’: Permission denied
mv: cannot stat ‘docker-compose.new.yml’: No such file or directory
```
**Screenshots**
normal ./docker.sh update
![image](https://user-images.githubusercontent.com/29955942/73359716-63cc8a00-4299-11ea-8b50-50f27cc0967e.png)
sudo ./docker.sh update
![image](https://puu.sh/F4WM2/6e56db2604.png)
**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch I'm a little worried you messed with the permissions by running `sudo ./docker.sh update`. You may need to manually delete the `docker-compose.new.yml` file (if it exists).

**Comment by SC2Mitch** [comment]
> You may need to manually delete the `docker-compose.new.yml` file (if it exists).
Where can that generally be found, `/var/azuracast`?

**Comment by SlvrEagle23** [comment]
@SC2Mitch Yeah, it should be created by the utility script on the host machine.

**Comment by SC2Mitch** [comment]
![image](https://user-images.githubusercontent.com/29955942/73408945-a8860e80-42f5-11ea-9bce-a55acc2ac2f9.png)
Taking a glance inside and it's not in here, for some reason

**Comment by SlvrEagle23** [comment]
@SC2Mitch Could've just been a temporary curl error too. Is it still doing it on subsequent attempts?

**Comment by SC2Mitch** [comment]
> @SC2Mitch Could've just been a temporary curl error too. Is it still doing it on subsequent attempts?

I've tried it but I think you nailed it, when I tried Sudo it got really angry, I'll fix the permissions tomorrow and update. 
`
[mitch@dashboard azuracast]$ ./docker.sh update-self
curl: (23) Failed writing body (0 != 1870)
chmod: changing permissions of ‘docker.sh’: Operation not permitted
New Docker utility script downloaded.
`
