### ISSUE TITLE
Installation Fine, upload music failed

### ISSUE THREAD

**Issue by Makunia** [AzuraCast/AzuraCast#2361]
Hey, i have install all the software and would now upload music. 
First i used the sftp and uploaded all my music. but if i go to the musiclist its just loaded. I deleted all , still loading, i load on page music, the list is still loading. i restart server... still loading :( what i have doing false?

![image](https://i.gyazo.com/a5783df32161996a3379c0929baba58a.png)

this picture is from the winscp first file is uploaded with page, second with sftp
![image](https://user-images.githubusercontent.com/39903499/73483918-a927af00-43a0-11ea-9dc0-84e4fbbbfc30.png)

**Comment by SC2Mitch** [comment]
This might be related to #2360 with stations going a bit insane.

**Comment by Makunia** [comment]
issue is now selffixed :D after 20h waiting :x
