### ISSUE TITLE
Attempting to create duplicate SFTP users results in error 500 Integrity constraint violation

### ISSUE THREAD

**Issue by ItsMitchh** [AzuraCast/AzuraCast#2363]
**Using Docker installation method**
Yes
**Host Operating System**
CentOS
**Describe the bug**
Creating a SFTP user with the same name as someone else, such as John and John will result in a Error 500 error occurring. 
**To Reproduce**
Go to SFTP users
Create a user called John and give a password
Attempt to create another user called John
See the error
**Expected behavior**
Possibly a red warning saying that this user already exists instead of a 500 page? 
**Relevant Logs**
`
An exception occurred while executing 'INSERT INTO sftp_user (username, password, public_keys, station_id) VALUES (?, ?, ?, ?)' with params ["christmas", "$argon2id$v=19$m=65536,t=4,p=1$NEh3WW5oVUQ1QXJoL0NYMw$j2RxMe43vs24G78gJxj7YW60H9JcWAXJZfmWnnwe\/wI", "", 37]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'christmas' for key 'username_idx'
AbstractMySQLDriver.php : 55
`

**Screenshots**
GIF
https://streamable.com/0nol7
**Device(s):**
WIN10, Chrome, Latest, Desktop
**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch This isn't really a bug, just more of a "this could be done in a friendlier way" thing. I agree, though I'd rather put off any changes to that form until I can move it over to be a Vue component.
