### ISSUE TITLE
After the last update, azuracast  will continue clone stations.

### ISSUE THREAD

**Issue by rolradio** [AzuraCast/AzuraCast#2364]
After the last update, azuracast stations will continue to clone.
The stations are cloned every X minutes.
The CPU runs up to 100 percent.
The 8 stations on the server have increased to almost one hundred.
I'm going to stop the VPS now to prevent worse.

On Docker

**Comment by SlvrEagle23** [comment]
@rolradio The very latest update as of about an hour ago? This should have been fixed across the board.

**Comment by dannyodj** [comment]
Please Help , i have the same issue , after update before 20 minutes , i had the problem with geting acess to sftp , it fixed but look 760 radio cloned now i dont know what to do , please help , what do i have to do!
i have 12 radio stations and all ar cloned and i see liquidsoap error
Liquidsoap is not recognized as a service.
It may not be registered with Supervisor yet. Restarting broadcasting may help.
how do i have to delte the radios?

**Comment by dannyodj** [comment]
@SlvrEagle23 please help please , what to do?

**Comment by SlvrEagle23** [comment]
@dannyodj Please contact me via our [Slack](https://azuracast.com/slack) or [Discord](https://azuracast.com/discord). Fixing this issue requires administrative access to your machine, but I can take care of it rather quickly on my end.

**Comment by stemvantwente** [comment]
Same problem here, on bare-metal installation on Unbuntu 18.04. I did the update 1 hour ago.

Greets

**Comment by SlvrEagle23** [comment]
@stemvantwente The latest update won't remove duplicate stations that were created earlier in the day, just prevent new ones from being created.

If you have a number of stations that you can't clear our yourself, feel free to message us on Slack or Discord and we can get it fixed quite quickly.
