### ISSUE TITLE
time limit per ip for Song Requests

### ISSUE THREAD

**Issue by onlinegill** [AzuraCast/AzuraCast#2365]
I see people can request unlimited songs which mean others songs will be not played so there should be time limit for per ip. lets say the person who requested song than system should  not let him request song  for couple minutes so others songs can be played.

**Comment by FLAME878** [comment]
It is already a feature (of sorts), @onlinegill. 
![Screenshot_1](https://user-images.githubusercontent.com/52174090/74210395-d1d56180-4c48-11ea-9e04-1c81e34be8b1.png)
Edit Profile (station profile) -> AutoDJ -> Request Last Played Threshold (Minutes)

**Comment by SlvrEagle23** [comment]
@onlinegill: @FLAME878 is correct in that we already attempt to internally rate-limit by the requester's remote IP, provided that there is a delay threshold set in the station profile.
