### ISSUE TITLE
Unable To Delete Playlists

### ISSUE THREAD

**Issue by zonkersradio** [AzuraCast/AzuraCast#2366]
I am trying To clear Up Playlists And delete unneeded playlists and or edit existing and when trying they do not open as a pop up it just flashes i have tried in both firefox and Crome browser and can see the following in the logs 
AzuraCast.INFO: Permission denied. {"file":"/var/azuracast/www/src/Middleware/Permissions.php","line":45,"code":0}

I have also tried on another computer as well with the same issue

**Comment by zonkersradio** [comment]
Have also just done the update today to see if that would resolve the issue however it has not

**Comment by zonkersradio** [comment]
Any help Please would be Gratefully Received

**Comment by SC2Mitch** [comment]
@zonkersradio docker or ansible? And did you update to the latest version?

**Comment by SlvrEagle23** [comment]
@zonkersradio Make sure you have the "Prefer Browser URL" setting enabled on the system-wide settings page. This often causes this issue.

**Comment by zonkersradio** [comment]
Hi Sorry i should have mentioned i followed the docker instructions as per requirements as its installed on digital ocean and i used the following 
cd /var/azuracast
./docker.sh update-self
./docker.sh update

**Comment by zonkersradio** [comment]
Thank you i will give that a try "Prefer Browser URL"  and let you know

**Comment by zonkersradio** [comment]
Thank You So much that seems to have Solved the Issue :-)
