### ISSUE TITLE
SFTP isnt working

### ISSUE THREAD

**Issue by Skyradio** [AzuraCast/AzuraCast#2367]
Hi,
after my last update I found that the Music upload is changed from FTP to SFTP. 
I have a script running every hour to upload News to a special Folder.
So I have created a SFTP user to upload but Im not able to login. Always I have a Password Failure.
I changed Username and PW several times with the same Result. Please help me.

Mike

**Comment by SC2Mitch** [comment]
Try these commands within the Azuracast folder and it should return some errors / shed some light on what's going wrong. 

> docker-compose exec --user=azuracast web bash

> tail -f ~/sftpgo/sftpgo.log

**Comment by SlvrEagle23** [comment]
@Skyradio A similar issue was reported recently and fixed, and this may fix your installation as well, so you should update to the latest available version and see if the issue persists.

**Comment by Skyradio** [comment]
Working again. Thanks
