### ISSUE TITLE
Api page error

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2373]
**Using Docker installation method**

Ubuntu 18.04

**Describe the bug**

The API page stopped working
https://demo.azuracast.com/static/api/index.html

![image](https://user-images.githubusercontent.com/2701228/73570233-a9917a00-4474-11ea-83e9-5dd783015947.png)

**Comment by mikedorst** [comment]
#2347

**Comment by SlvrEagle23** [comment]
@eranwo Fixed on the demo and in the latest update.
