### ISSUE TITLE
Thanks for resolving issues over the last few days.

### ISSUE THREAD

**Issue by psduk1** [AzuraCast/AzuraCast#2374]
Hi @SlvrEagle23 , I would just like to say a massive thanks for all your hard work over the last few days.
After updating my install earlier in the week I experienced various issues and problems.

- SFTP wouldn't work - This was resolved, but the update caused my install to start duplicating stations at random, in a matter of hours I had over 15,000 duplicate stations which eventually caused my server to show a constant 500 error.
- I found the easiest option was to reinstall the server and start again which i did late last night as well as running the update to fix the station duplication problem.
I am happy to say that after a few headaches over the last few days I am impressed at how you swiftly released updates and worked tirelessly to resolve the problems.
May I just say THANKS !
p.s I'll be donating to your cause soon as I appreciate all your hard work

**Comment by SlvrEagle23** [comment]
@psduk1 Thank you very much for your kind words. It's true, the last few days have been a bit of a scramble to fix issues, make sure everyone is up and running still, while adding new features in there as well.

Your support (both in the kind words and in any donations you decide to make) are greatly appreciated. :)
