### ISSUE TITLE
Liquidsoap Not Starting - CentOS 7

### ISSUE THREAD

**Issue by ChisdealHDYT** [AzuraCast/AzuraCast#2375]
Liquidsoap Not Starting because this Error

Using Cent OS 7 Server do this and pre installed as fresh copy and only i changed is  Port of AzuraCast HTTP and SSL because other Server using already using Port 80 and 443

and Works fine i can access it just fine just Liquidsoap Refused start up when have 1-0 NCS music in there

`stations_1                 | 2020-02-01 12:58:38,620 INFO spawned: 'station_1_backend' with pid 79
stations_1                 | 2020-02-01 12:58:38,866 INFO exited: station_1_backend (exit status 0; not expected)
stations_1                 | 2020-02-01 12:58:39,869 INFO spawned: 'station_1_backend' with pid 80
stations_1                 | 2020-02-01 12:58:40,102 INFO exited: station_1_backend (exit status 0; not expected)
stations_1                 | 2020-02-01 12:58:42,119 INFO spawned: 'station_1_backend' with pid 81
stations_1                 | 2020-02-01 12:58:42,373 INFO exited: station_1_backend (exit status 0; not expected)
stations_1                 | 2020-02-01 12:58:46,357 INFO spawned: 'station_1_backend' with pid 82
stations_1                 | 2020-02-01 12:58:46,585 INFO exited: station_1_backend (exit status 0; not expected)
stations_1                 | 2020-02-01 12:58:46,846 INFO gave up: station_1_backend entered FATAL state, too many start retries too quickly`

**Comment by ChisdealHD** [comment]
![image](https://user-images.githubusercontent.com/18028479/73592746-4f84c900-44f5-11ea-890d-4a34a2e524b1.png)
i give you this too what says when press start

**Comment by SlvrEagle23** [comment]
@ChisdealHD Before Liquidsoap will run, you have to provide it with somewhere to broadcast first. It appears that you disabled the broadcasting (Icecast/SHOUTcast) frontends and don't have any remote relays set up. Try editing your station profile to re-enable broadcasting (we recommend using Icecast) and then restarting your station.

**Comment by ChisdealHD** [comment]
got pass that line, now gives me this

`Liquidsoap encountered an error
2020/02/07 10:03:08 [threads:3] Waiting for queue threads to terminate...
2020/02/07 10:03:08 [threads:3] Queues shut down
2020/02/07 10:03:08 [server:3] Closing socket.
2020/02/07 10:03:08 [main:3] Cleaning downloaded files...
2020/02/07 10:03:08 [main:3] Freeing memory...
2020/02/07 10:03:08 >>> LOG END`

**Comment by ChisdealHD** [comment]
and has 4 music .mp3 files

**Comment by SlvrEagle23** [comment]
@ChisdealHD Are you using any custom Liquidsoap configuration? That's a fairly vague error and the logs there don't give us any information as to why it isn't starting correctly.

You may want to use Utilities > Restart Broadcasting instead of clicking "Restart" on the Liquidsoap service by itself on the profile; that forces a rewrite of _all_ configuration on the station and can often fix issues like that.

**Comment by ChisdealHD** [comment]
its not using  custom Liquidsoap and all files are pre-setup for example no changes part ports of servers
