### ISSUE TITLE
Where can streaming files be located? 

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2376]
How can we locate the Streamers mp3/ogg/etc files? We're trying to delete them to clear up space but Azuracast doesn't have that feature in yet. And can we delete them safely without causing issues?

**Comment by SC2Mitch** [comment]
Located the files. 
`/var/lib/docker/volumes/azuracast_station_data/_data/{station}/recordings/{Web DJ username}`

**Comment by SlvrEagle23** [comment]
@SC2Mitch You can now also delete recordings from directly within the web interface.
