### ISSUE TITLE
Queued up songs aren't playing accurately 

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2378]
**Using Docker installation method**
Yes

**Host Operating System**
CentOS 7 
**Describe the bug**
When we queue up songs, it doesn't queue up instantly, it takes several songs to even play, the logs don't show that the song was queued. 
**To Reproduce**
Queue up a song and monitor your station for the played song. 
**Expected behavior**
The song to ideally play on `Playing Next` and for the logs to accurately track when the song was requested. 
**Relevant Logs**
```
REQUESTED SONG HERE Blur - Parklife. 
[Now Playing] 2020-02-01 18:56:29    INFO    [ADMINCGI sid=1] Title updated [Tamia, Fabolous - Into You (feat. Fabolous)]
[Playing Next] 2020-02-01 18:56:29    INFO    [ADMINCGI sid=1] Title updated [Tamia, Fabolous - Into You (feat. Fabolous)]
2020-02-01 18:56:32    INFO    [ADMINCGI sid=1] Title updated [Billie Ray Martin - Your Loving Arms]
2020-02-01 19:03:03    INFO    [ADMINCGI sid=1] Title updated [Blur - Parklife]
```
**Screenshots**
None. 

**Device(s):**
Win10, Chrome, Latest, Desktop
**Additional context**
We have over 700 songs in our station, unsure if this may cause this unexpected behaviour?

**Comment by mikedorst** [comment]
When I put the song "parklifie" into the que it took liquidsoap 3 songs before it played mine. I guess liquidsoap auto ques 3 songs and then a manual que would be the 4th song? Maybe its possible to make the requested song a higher priority.

**Comment by mikedorst** [comment]
I've also noticed that the "Upcoming Song Queue" does not update with the requested song.

The current song in it is "Playing Next" song.

![image](https://user-images.githubusercontent.com/27761242/73937940-7755a180-48e6-11ea-90d8-5e4ad87f7d98.png)
