### ISSUE TITLE
Cany you modify the landing radio page?

### ISSUE THREAD

**Issue by FoxyWhite2541** [AzuraCast/AzuraCast#238]
Greetings.

I just wanna know, is there any possible way of modyfying the landing page. 

I like the clean, sleek look of it but i would change few stuff soo if there is a way to change it, wohoooo xD

Kind regards,
Rok

**Comment by SlvrEagle23** [comment]
@FoxyWhite2541 There's actually a rather new feature that was just added to AzuraCast a week or two ago: the ability to specify custom CSS stylesheets for your public landing pages and for your internal administration pages.

While you can't change the HTML on the landing page itself (if you need to make changes that significant, you're always welcome to pull the source code of the public page and repurpose it as part of your own station site), changing the CSS gives you a significant amount of creative leeway.

Also, if you prefer to avoid the styling altogether and instead just have an embeddable radio player that you can drop into your existing site, on your station's profile you will see the embed code, which uses a fully transparent background and blends seamlessly into your existing page.

**Comment by ErnestPH** [comment]
The transparent background for the embedded web player by the way is not working anymore...

**Comment by SlvrEagle23** [comment]
@ErnestPH You should file this as a new bug report instead of a comment to a previous question.

**Comment by ErnestPH** [comment]
Understood. Thanks!

**Comment by ErnestPH** [comment]
I reference it to the new Ouse I opened. #875
