### ISSUE TITLE
Music scheduling stopping after 24h

### ISSUE THREAD

**Issue by wagnerfs7** [AzuraCast/AzuraCast#2382]
Hello!
I am having a problem. I play a playlist to play every hour, but I noticed that about 24 hours later it stops playing at the scheduled times. I also checked the options to play every day of the week. Any suggestions of what it could be? Anyone who can help me will be very grateful.

The example below is one that I did for each schedule.

![image](https://user-images.githubusercontent.com/32310006/73778268-adb9e200-4769-11ea-9cac-26a9f60d25a6.png)

![image](https://user-images.githubusercontent.com/32310006/73777974-29675f00-4769-11ea-8409-c2e025cfa018.png)

**Comment by SlvrEagle23** [comment]
@wagnerfs7 If you uncheck all the dates, it should also play every day. Have you tried that to see if it works any better?

**Comment by wagnerfs7** [comment]
Yes, I tried.

**Comment by wagnerfs7** [comment]
Unfortunately it didn't work. I left all options unchecked, and it would be played every hour in sequence. Does anyone have another alternative?

**Comment by wagnerfs7** [comment]
> @wagnerfs7 If you uncheck all the dates, it should also play every day. Have you tried that to see if it works any better?

Unfortunately it didn't work. I left all options unchecked, and it would be played every hour in sequence. Does anyone have another alternative?

**Comment by wagnerfs7** [comment]
![image](https://user-images.githubusercontent.com/32310006/74667895-e9e63d00-5182-11ea-9bda-f6817a681358.png)

**Comment by wagnerfs7** [comment]
What to do for a playlist to be reloaded automatically? If this is possible, the problem is solved.

**Comment by cristianocarrozzi** [comment]
@wagnerfs7 
I had the same isue and the solution is to schedule in Crontab to restart the station every night, use this command:

./docker.sh cli azuracast:radio:restart radio_id (enter your station ID here)

**Comment by wagnerfs7** [comment]
@cristianocarrozzi ,thanks for the tip. I made the appointment. I'll watch. The ideal would be something automatic in Azuracast.
