### ISSUE TITLE
Unique Listener Counter Not Working - IceCast

### ISSUE THREAD

**Issue by alexhorner** [AzuraCast/AzuraCast#2383]
**Using Docker installation method**

Yes

**Host Operating System**

Ubuntu 18.04.3 LTS

**Describe the bug**

The control panel after clicking manage on a station does not show a unique listener count. I am assuming this is because IceCast does not provide a Unique Listener count in its status-json.xsl

**To Reproduce**

1. Install AzuraCast Docker with IceCast
2. Get a few unique listeners
3. Look at the station manage page

**Expected behavior**

The Unique listener count counts the unique listeners like a unique listener counter should count the unique listeners

**Relevant Logs**

Should not be relevant

**Screenshots**

![image](https://user-images.githubusercontent.com/33007665/73777596-ab638200-4781-11ea-8da1-32d260d0996f.png)

**Device(s):** (shouldn't be applicable but included anyway)
 - Device: Desktop PC
 - OS: Windows 10 Home 1903
 - Browser: Firefox
 - Version: 72.0.1 64 Bit

**Additional context**

If you need additional information, including IP addresses or URLs to see yourself, please DM a developer in the Simulator Radio Discord https://discord.simulatorradio.com/, or reply here for non-private information.

This was discussed with SilverEagle in DMs

**Comment by AmsterdamFM** [comment]
I have the exact same problem. The number of unique listeners is always 0 even with 1 listener.

**Comment by SlvrEagle23** [comment]
@alexhorner @AmsterdamFM We've made some recent updates that should have improved the way unique listeners are displayed on the sidebar. Let me know if this issue persists in the latest version of the application.

**Comment by AmsterdamFM** [comment]
@SlvrEagle23 updated to AzuraCast • v0.9.8.1, #49a6268 (2020-02-24 20:39) • Docker • PHP 7.4

Problem still exists. No matter how many people listen, unique is always 0. Listener count updates fine. We are using a Remote Relay that uses HTTP. Our interface is in HTTPS. Might this be the problem?

**Comment by SlvrEagle23** [comment]
@AmsterdamFM From the main system administration panel, try running the "Now Playing" synchronization. It should post some information about the Now Playing retrieval process, which may be helpful for diagnostics.

**Comment by AmsterdamFM** [comment]
@SlvrEagle23 Thanks for pointing us out. I hope the information is of more value to you than it is to me:

Our streaming provider uses Icecast 2.4.2 BTW.

Debug
NowPlaying adapter response
response
{
    "current_song": {
        "text": "Phil Collins - Do you remember",
        "artist": "Phil Collins",
        "title": "Do you remember"
    },
    "listeners": {
        "current": 2,
        "unique": 0,
        "total": 2
    },
    "meta": {
        "status": "online",
        "bitrate": null,
        "format": "audio\/mpeg"
    }
}
clients
null
station
{
    "id": 1,
    "name": "AmsterdamFM"
}
Debug
Response for remote relay
remote
"128kbps MP3"
response
{
    "current_song": {
        "text": "Phil Collins - Do you remember",
        "artist": "Phil Collins",
        "title": "Do you remember"
    },
    "listeners": {
        "current": 2,
        "unique": 0,
        "total": 2,
        "clients": []
    },
    "meta": {
        "status": "online",
        "bitrate": null,
        "format": "audio\/mpeg"
    }
}
station
{
    "id": 1,
    "name": "AmsterdamFM"
}
Debug
Final NowPlaying Response for Station
id
1
name
"AmsterdamFM"
np
{
    "current_song": {
        "text": "Phil Collins - Do you remember",
        "artist": "Phil Collins",
        "title": "Do you remember"
    },
    "listeners": {
        "current": 2,
        "unique": 0,
        "total": 2,
        "clients": []
    },
    "meta": {
        "status": "online",
        "bitrate": null,
        "format": "audio\/mpeg"
    }
}
station
{
    "id": 1,
    "name": "AmsterdamFM"
}

**Comment by alexhorner** [comment]
I am guessing unique listener counts for external relays will require a configuration change on said relays for this to work?

**Comment by danielpilot** [comment]
Hello,

I am having the exact same issue right now only when the relay is IceCast, if I use ShoutCast there is no problem at all.

There is a field listeners in the Icecast response but no field unique listeners is found, maybe it's because of that.

If I go to /admin/listclients, I correctly find a list of listeners with different IPs connected, but the result of unique is always 0

**Comment by gasguti** [comment]
I have the same issue, also I can't login in the admin page of Icecast
