### ISSUE TITLE
letsencrypt_renew script needs to also reload NGINX

### ISSUE THREAD

**Issue by kevev** [AzuraCast/AzuraCast#2384]
I have noticed that every time my letsencrypt cert expires, NGINX still serves up the old expired cert.

I believe that /usr/local/bin/letsencrypt_renew script needs to be updated to gracefully reload NGINX:

```
#!/usr/bin/env sh

if [ `whoami` != 'azuracast' ]; then
    echo 'This script must be run as the "azuracast" user. Rerunning...'
    sudo -E -u azuracast letsencrypt_renew $@
    exit 1
fi

certbot renew --webroot -w /var/www/letsencrypt $*

service nginx reload
```

**Comment by kevev** [comment]
Scratch that. The new way according to https://certbot.eff.org/docs/using.html is to create a script /etc/letsencrypt/renewal-hooks/post/reload-nginx.sh

`#!/bin/bash

service nginx reload`

Then do:

`chmod 755 /etc/letsencrypt/renewal-hooks/post/reload-nginx.sh`

**Comment by kevev** [comment]
I found that the service command needs to run as root. Updated to use sudo:

root@azuracast: cat: /var/azuracast/letsencrypt/renewal-hooks/post/reload-nginx.sh
```#!/bin/bash

sudo /usr/sbin/service nginx reload```

As a temp fix:

root@azuracast: cat /var/azuracast/docker-compose.override.yml

```version: '2.2'

services:
    web:
        volumes:
                - /var/azuracast/letsencrypt/renewal-hooks/post/reload-nginx.sh:/etc/letsencrypt/renewal-hooks/post/reload-nginx.sh```

**Comment by SlvrEagle23** [comment]
@kevev We actually already have this hook in place (and rather than using `service`, which expects something like systemd to be present, which isn't on Docker, it sends a "HANGUP" signal to nginx which triggers a graceful reload), it may just be that our permissions aren't quite right on that file. I updated our permissions, so that may help with the issue.

**Comment by SlvrEagle23** [comment]
New Docker infrastructure makes this a non-issue.
