### ISSUE TITLE
Jinglemode not working

### ISSUE THREAD

**Issue by Skyradio** [AzuraCast/AzuraCast#2388]
Hi,
after installing the latest Update (with Docker) the Jinglemod is not hiding the Track information.
It show " Unknown - null" in my Track History.
Or do i have to use a special name for my Jingle to get rid of this fault??

Greeting Mike

**Comment by SlvrEagle23** [comment]
@Skyradio Normally it should just be removing the metadata and showing the same metadata as the track before it. If this keeps repeatedly happening, check the logs (from the Utilities > Log Viewer page) and let me know if there's anything that might help explain it.

**Comment by Skyradio** [comment]
@SlvrEagle23 The Liquidsoap Log says this when it comes to a Jingle:

``2020/02/06 07:06:15 [playlist_jingles:3] Prepared "/var/azuracast/stations/skyradiofm/media/Jingles/SKY RADIO FM SKY RADIO FM MEDIUM1ENJOYTHEMUSIC-FULLMIX  .mp3" (RID 2481).
2020/02/06 07:06:15 [fallback_7848:3] Switch to delay_7847 with forgetful transition.
2020/02/06 07:06:15 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Jingles/SKY RADIO FM SKY RADIO FM TRANSSLOWTOFAST3ENJOYTHEMUSIC-FULLMIX  .mp3".
2020/02/06 07:06:15 [cross_7898:3] Analysis: -32.403306dB / -19.557149dB (2.98s / 3.02s)
2020/02/06 07:06:15 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/02/06 07:06:26 [fallback_7848:3] Switch to fallback_7845 with forgetful transition.
2020/02/06 07:06:26 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/90s/VA-90s_Eurodance_2-3CD-2014-MTC - DeoTester/Club House feat. Carl - Light My Fire (Capella R.A.F. Zone Mix).mp3".
2020/02/06 07:06:26 [cross_7898:3] Analysis: -67.347057dB / -53.177240dB (2.98s / 2.98s)
2020/02/06 07:06:27 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/02/06 07:06:27 [lang:3] AzuraCast Feedback Response: OK
