### ISSUE TITLE
Insecure connections

### ISSUE THREAD

**Issue by innotkauker** [AzuraCast/AzuraCast#2390]
**Using Docker installation method**

Yes

**Host Operating System**

Debian 10

**Describe the bug**

I'm running AzuraCast behind an nginx reverse proxy which manages ssl and redirects http to https. It mostly works fine, however some requests are sent over http and either fail or give browser warnings. Some such requests I noticed:
- When I click on Edit playlist
- When I click on Delete playlist
- All album cover images
Cover images are loaded successfully after the requests are redirected to https, however edits and deletes don't go through.

I have the "Prefer Browser URL" checkbox set as suggested in similar questions.
The problem doesn't go away after "docker self-update && docker-update".

**Expected behavior**

All requests should be sent over https.

**Device(s):**
Chromium and Firefox on desktop linux.

**Comment by SC2Mitch** [comment]
Yup, we're having this, they completely outright fail for us.

**Comment by SlvrEagle23** [comment]
@innotkauker Depending on what headers the nginx proxy sends back to the application, it may not be possible for the app itself to detect whether it's being served via HTTP or HTTPS.

There are some settings you can change on the global settings form that may remedy this issue:
 - Turn off "prefer browser URL" to force the base URL you specify to always be used for API responses (i.e. Edit playlist, Add playlist, etc)
 - Turn on "always use HTTPS", though again if the application doesn't detect that it's being served over HTTPS this may lead to infinite redirects.

**Comment by innotkauker** [comment]
@SlvrEagle23 thanks for help!

1) Disabling "prefer browser URL" doesn't change anything, and if I add "https://" to the base URL, it gets chopped off when i save.
2) Yes, this leads to infinite redirects outside the proxy and a warning about self-signed cert on the inside.

Perhaps there's anything I can add to the proxy configuration? Currently I have the following
```
  location / { 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://azuracast;
  }
```

Though I thought it would be possible to fix this the code somehow, as other requests go over https..

**Comment by yarik2720** [comment]
I have the same issue. Also reported that earlier #2184

**Comment by SlvrEagle23** [comment]
@innotkauker Try proxy_pass'ing over to `https://azuracast`?

**Comment by SlvrEagle23** [comment]
@innotkauker After doing some research internally, it appears the easy solution to this is to set:

```
proxy_set_header X-Forwarded-Proto $scheme;
```

in your upstream nginx proxy's configuration. That will ensure that we receive and parse the correct HTTP scheme (http/https).

**Comment by innotkauker** [comment]
@SlvrEagle23 confirming, setting this header fixes the issue. Thanks a lot!
