### ISSUE TITLE
AutoDJ

### ISSUE THREAD

**Issue by KulibibK** [AzuraCast/AzuraCast#2391]
Hello! When auto-DJ broadcasts, can the display be displayed in the player? To display in the player who is currently on the air or is it an auto DJ or live stream.

**Comment by SlvrEagle23** [comment]
@KulibibK In our built-in public and embeddable players, we automatically show when a live DJ is connected, but we don't show any special status when the AutoDJ is controlling the radio.

If you wanted to, in your own custom player, you could detect if a live DJ is on by the [Now Playing API](https://www.azuracast.com/developers/nowplaying.html)'s response in the `live` section. If there is no value specified in that section, then it's the AutoDJ broadcasting.
