### ISSUE TITLE
Can't login after restore from backup "Login unsuccessful Your credentials could not be verified."

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2392]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu 18.04

**Describe the bug**
After restoring from full backup into new server,
can't login, and getting :"**Login unsuccessful
Your credentials could not be verified.**"

**when trying to reset admin password' getting this:**

Starting azuracast_redis_1 ... done
Starting azuracast_mariadb_1  ... done
Starting azuracast_stations   ... done
2020/02/06 11:30:26 Waiting for: tcp://mariadb:3306
2020/02/06 11:30:26 Waiting for: tcp://influxdb:8086
2020/02/06 11:30:26 Connected to tcp://influxdb:8086
2020/02/06 11:30:26 Connected to tcp://mariadb:3306

Reset Account Password
======================

 [ERROR] Account not found.

2020/02/06 11:30:26 Command exited with error: exit status 1

- **when trying to update getting this:**

Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Stopping azuracast_web        ... done
Stopping azuracast_stations   ... done
Stopping azuracast_mariadb_1  ... done
Stopping azuracast_redis_1    ... done
Stopping azuracast_influxdb_1 ... done
Removing azuracast_web        ... done
Removing azuracast_stations   ... done
Removing azuracast_mariadb_1  ... done
Removing azuracast_redis_1    ... done
Removing azuracast_influxdb_1 ... done
Removing network azuracast_default
azuracast_www_data
azuracast_tmp_data
Creating network "azuracast_default" with the default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_www_data" with default driver
Creating azuracast_influxdb_1 ... done
Creating azuracast_redis_1    ... done
Creating azuracast_mariadb_1  ... done
Creating azuracast_stations   ... done
2020/02/06 11:32:04 Waiting for: tcp://mariadb:3306
2020/02/06 11:32:04 Waiting for: tcp://influxdb:8086
2020/02/06 11:32:04 Connected to tcp://mariadb:3306
2020/02/06 11:32:04 Connected to tcp://influxdb:8086
Updating AzuraCast...
(Environment: production)

AzuraCast Setup
===============

Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...
 * Environment: Production
 * Installation Method: Docker

 ! [NOTE] Running in update mode.

Setting Up InfluxDB
-------------------

Database created.
Retention policies updated.
Continuous queries created.
InfluxDB databases created.

Running Database Migrations
---------------------------

                    Doctrine Database Migrations

No migrations to execute.

Generating Database Proxy Classes
---------------------------------

 Processing entity "App\Entity\Settings"
 Processing entity "App\Entity\StationWebhook"
 Processing entity "App\Entity\StationPlaylistSchedule"
 Processing entity "App\Entity\StationPlaylist"
 Processing entity "App\Entity\StationRequest"
 Processing entity "App\Entity\AuditLog"
 Processing entity "App\Entity\StationMedia"
 Processing entity "App\Entity\ApiKey"
 Processing entity "App\Entity\StationMount"
 Processing entity "App\Entity\Analytics"
 Processing entity "App\Entity\SongHistory"
 Processing entity "App\Entity\SftpUser"
 Processing entity "App\Entity\StationPlaylistFolder"
 Processing entity "App\Entity\User"
 Processing entity "App\Entity\StationStreamer"
 Processing entity "App\Entity\StationMediaCustomField"
 Processing entity "App\Entity\StationPlaylistMedia"
 Processing entity "App\Entity\RolePermission"
 Processing entity "App\Entity\Song"
 Processing entity "App\Entity\Listener"
 Processing entity "App\Entity\Station"
 Processing entity "App\Entity\CustomField"
 Processing entity "App\Entity\Relay"
 Processing entity "App\Entity\StationRemote"
 Processing entity "App\Entity\Role"
 Processing entity "App\Entity\StationStreamerBroadcast"

 Proxy classes generated to "/var/azuracast/www_tmp/proxies"

Reload System Data
------------------

Local cache flushed.

Refreshing All Stations
-----------------------

Restarting all radio stations...
--------------------------------

In AbstractMySQLDriver.php line 60:

  An exception occurred while executing 'SELECT s0_.id AS id_0, s0_.name AS name_1, s0_.short_name AS short_name_2, s0_.is_enabled AS is_enabled_3, s0_.frontend_type AS frontend_type_4, s0_.fronte
  nd_config AS frontend_config_5, s0_.backend_type AS backend_type_6, s0_.backend_config AS backend_config_7, s0_.adapter_api_key AS adapter_api_key_8, s0_.description AS description_9, s0_.url AS
   url_10, s0_.genre AS genre_11, s0_.radio_base_dir AS radio_base_dir_12, s0_.radio_media_dir AS radio_media_dir_13, s0_.nowplaying AS nowplaying_14, s0_.nowplaying_timestamp AS nowplaying_timest
  amp_15, s0_.automation_settings AS automation_settings_16, s0_.automation_timestamp AS automation_timestamp_17, s0_.enable_requests AS enable_requests_18, s0_.request_delay AS request_delay_19,
  s0_.request_threshold AS request_threshold_20, s0_.disconnect_deactivate_streamer AS disconnect_deactivate_streamer_21, s0_.enable_streamers AS enable_streamers_22, s0_.is_streamer_live AS is_st
  reamer_live_23, s0_.enable_public_page AS enable_public_page_24, s0_.needs_restart AS needs_restart_25, s0_.has_started AS has_started_26, s0_.api_history_items AS api_history_items_27, s0_.stor
  age_quota AS storage_quota_28, s0_.storage_used AS storage_used_29, s0_.timezone AS timezone_30, s0_.current_streamer_id AS current_streamer_id_31, s0_.current_streamer_id AS current_streamer_id
  _32 FROM station s0_ ORDER BY s0_.name ASC':

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 's0_.timezone' in 'field list'

In PDOConnection.php line 80:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 's0_.timezone' in 'field list'

In PDOConnection.php line 75:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 's0_.timezone' in 'field list'

azuracast:setup [--update] [--load-fixtures] [--release]

2020/02/06 11:32:04 Command exited with error: exit status 1
azuracast_influxdb_1 is up-to-date
azuracast_redis_1 is up-to-date
azuracast_mariadb_1 is up-to-date
azuracast_stations is up-to-date
Creating azuracast_web ... done
Update complete!

**Comment by SlvrEagle23** [comment]
@eranwo How old is the backup you're restoring? It looks like it may be a bit out of date, which is fine because we typically migrate the database up to the latest version immediately afterward, but for some reason it marked your installation as having "no migrations to execute".

**Comment by eranwo** [comment]
@SlvrEagle23 Indeed the backup was from older version ( v0.9.8, #c72be08).
I solved this by backup and restore the database only . But after doing this it deleted all channels and mp3 filse on the new server ( the files which i restoed with the corrapt backup) so, i copied all channels from the old server to the new server and now everything works fine.
I don't know why the full backup failed, but I suggest adding the option of database-only restoring without deleting the channels and music files in the destinsion.

**Comment by SlvrEagle23** [comment]
@eranwo I would need more information on why this is happening in the first place, but it's true that if you do a backup while excluding media, then restoration also excludes media and you can separately restore media on your own.
