### ISSUE TITLE
Setting a playlist on a folder bugs out sequential playlists

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2394]
**Using Docker installation method**
Yes
**Host Operating System**
CentOS
**Describe the bug**
If a playlist is in Sequential, it can bug out and cause it to make Liquidsoap run in a really weird manner, it 10xs the songs for no apparent reason and causes the Playlist tab to duplicate multiple times within `files`
**To Reproduce**
Make a playlist, run it in Sequential. 
**Expected behavior**

**Relevant Logs**
None 
**Screenshots**
![image](https://user-images.githubusercontent.com/29955942/73996609-ee754f00-4953-11ea-97ea-0ad465e28aac.png)
 ![image](https://cdn.discordapp.com/attachments/647149735991443467/675161698000175125/unknown.png)
**Device(s):**
Win10 latest, Chrome latest, desktop
**Additional context**
Posted at the request of SilverEagle.

**Comment by SlvrEagle23** [comment]
@SC2Mitch This should be fixed as of the latest update.
