### ISSUE TITLE
Wrong database name

### ISSUE THREAD

**Issue by Xara** [AzuraCast/AzuraCast#2395]
**Using Docker installation method**
 No

**Host Operating System**
Ubuntu 18.04 LTS

**Describe the bug**

during update message about no granted access to database "app" for azuracast user, after creating such database and grant privileges, system is not operational,  dump azuracast database and copy to app make system operational again. Is just wrong database name.
**To Reproduce**
run ./update.sh from /var/azuracast/www/

**Expected behavior**

Update without error
**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Xara** [comment]
It can explain that error with login impossible, Is what I get before copying azuracast to app database.

**Comment by SlvrEagle23** [comment]
@Xara This should be fixed as of the latest update; one of the codebase changes changed the assumed default database name to `app` instead of `azuracast` for Ansible installations, and the latest update changes that back.

**Comment by Xara** [comment]
Thank you
