### ISSUE TITLE
AzuraCast and OpenVZ

### ISSUE THREAD

**Issue by radio2019** [AzuraCast/AzuraCast#2397]
Just out of interest: Does AzuraCast work on VPS with OpenVZ virtualization?

**Comment by SC2Mitch** [comment]
@radio2019 It's not fully supported, but it may work with a Docker (official) / Ansible (Unsupported)

**Comment by Vaalyn** [comment]
@radio2019 You can refer to my answers on this issue: https://github.com/AzuraCast/AzuraCast/issues/1685

In general running Docker containers inside OpenVZ containers may require some tinkering to get it working at all. In most cases it's not worth the hassle when you can just get a normal VM VPS.
