### ISSUE TITLE
Listeners Maps for all stations

### ISSUE THREAD

**Issue by Gujalls** [AzuraCast/AzuraCast#2398]
Hi,

In the Dashboard I could see the no of listeners for all stations. Cannot drill-down though - I need to visit to individual manage station to see the details. My query is.

1) Is there a way that I can see the world map for all the stations in one place? Where they are all listening from. This seems to be available inside each station not sure how to see the cumulative of them all.
2) Is it possible for me to see these map view / stats outside the azuracast dashboard. Like a json file that can be used to populate a table/graph or leaflet (Map) so that these can be showed in webpages / facebook etc.

Please let you let me know how to get this.

Thanks very much.

**Comment by SlvrEagle23** [comment]
@Gujalls To answer your questions:

1) This is currently not a feature in AzuraCast, but you are welcome to request it for inclusion over at https://features.azuracast.com

2) If you open your inspector window (F12 on most browsers) and click the "Network" tab, you will see that the Listeners report is actually just making API calls to the AzuraCast API, which return JSON data that your browser then renders into the listener map and table. You can make those same API calls yourself (either with your logged-in session or with an API key) and get the same return data, which you can then do whatever you want with. I would caution you not to include the full data feed from the Listeners report on any public page, as it includes information that many would consider private.
