### ISSUE TITLE
 Song order

### ISSUE THREAD

**Issue by KulibibK** [AzuraCast/AzuraCast#2399]
Is it possible to somehow implement the order of songs of this kind as a screen shot? 
Screen: http://freenet74.ru/Screen.png
The site on which this is implemented(Scroll down): http://radioprovince.ru/

**Comment by mikedorst** [comment]
@KulibibK you can probably play around with Azuracast's API to create a webpage like that yourself, there's a queue system in place.

![image](https://user-images.githubusercontent.com/27761242/74424705-bdfd4b80-4e52-11ea-851c-df40969001a2.png)
