### ISSUE TITLE
mp3 streaming not working anymore on ios 11

### ISSUE THREAD

**Issue by parcle** [AzuraCast/AzuraCast#240]
im currently running Azuracast without any problem. on ios 10 mp3 mount point is working properly but on ios 11 seems broken. Not many information around this issue but seems apple on ios 11 has dropped mp3 support.
Possible workaround ? setting a new mount point with different encoding ? maybe flac ?

**Comment by griffon56** [comment]
Hi parcle, On my ios 11, the mp3 streaming works fine. I just entered the streaming URL in safari.

**Comment by parcle** [comment]
uhm i think is related to last icecast like reported here https://github.com/karlheyes/icecast-kh/issues/172 i post here to prevent someone else getting trouble with this issue again and close ;)

**Comment by andrew867** [comment]
@parcle AzuraCast has been updated to include a version of Icecast-kh that fixes the iOS 11 problem.
