### ISSUE TITLE
MariaDB Won't start?

### ISSUE THREAD

**Issue by NotifiedGaming** [AzuraCast/AzuraCast#2401]
Hey there. So last night i uploaded songs for Liquid soap, when I checked on the progress this morning Azuracast was no longer accessible (http error 500). I restarted the machine and now when going to either the ip, host name, or https://hostname it refuses to connect.

After running `docker-compose logs -f` It seems as though MariaDB is failing to start. Here's a screenshot of the logs:

![putty_0tXHmS3VMk](https://user-images.githubusercontent.com/20782042/74109791-6757ef00-4b7e-11ea-9b6d-982bfaf689da.png)

It mentions running out of tablespace How do i increase this and will it fix the issue?

**Comment by SlvrEagle23** [comment]
@NotifiedGaming You may be out of disk space on your host machine. Try clearing up space if possible.

**Comment by NotifiedGaming** [comment]
I'm only using 88.94% of my storage.

https://i.imgur.com/GANvnPF.png
