### ISSUE TITLE
Web

### ISSUE THREAD

**Issue by itsFabiDev** [AzuraCast/AzuraCast#2403]
Hey, guys since 2 Days the last update I had done I can't connect to my Web panel and I can't configure it anymore. There is no Error message

**Comment by SC2Mitch** [comment]
@itsFabiDev We need more details here, system specs, docker ansible, and any `docker-compose logs -f` logs would be great.

**Comment by itsFabiDev** [comment]
[docker-compose log.txt](https://github.com/AzuraCast/AzuraCast/files/4187237/docker-compose.log.txt)
Here is the Docker log. 
My System: 
4 Cores
8 GB Ram
200 GB full SSD

What do you mean with Docker Ansible?

**Comment by itsFabiDev** [comment]
@SC2Mitch the problem is since the last update

**Comment by SC2Mitch** [comment]
> @SC2Mitch the problem is since the last update

Have you tried to run a `./docker.sh update-self` then a `./docker.sh update` ?

**Comment by itsFabiDev** [comment]
Yes I tried and its the same like before

**Comment by itsFabiDev** [comment]
Is there a way to look at the docker Documents?
So i mean the Folders and something like this?

**Comment by itsFabiDev** [comment]
@SC2Mitch @SlvrEagle23 this is my Stream URL panel.fffradio.live maybe this helps you.

**Comment by itsFabiDev** [comment]
I reinstalled it completely and now it looks like it funcs. Thank you very much!
