### ISSUE TITLE
Song History Code

### ISSUE THREAD

**Issue by queer-webtechnik** [AzuraCast/AzuraCast#2404]
Hello, i need help to create a Song History Code for me.

**Comment by FLAME878** [comment]
What do you mean by this? @queer-webtechnik

**Comment by queer-webtechnik** [comment]
A script which shows the last played titles either via Javascript or PHP selected from the api

**Comment by SlvrEagle23** [comment]
@queer-webtechnik Here are some examples of how to use our Now Playing API with JavaScript:
https://www.azuracast.com/developers/nowplaying.html

**Comment by queer-webtechnik** [comment]
I have testing this script here `<script>
var nowPlayingTimeout;
var nowPlaying;

function loadNowPlaying() {
  $.ajax({
      cache: false,
      dataType: "json",
      url: 'https://azs1.quueer-webtechnik.de/api/nowplaying/teststream',
      success: function(np) {
          // Do something with the Now Playing data.
          nowPlaying = np;

          nowPlayingTimeout = setTimeout(loadNowPlaying, 15000);
      }
  }).fail(function() {
      nowPlayingTimeout = setTimeout(loadNowPlaying, 30000);
  });
}

$(function() {
  loadNowPlaying();
});
</script>
` and this give me not output for the current song

**Comment by xewl** [comment]
`// Do something with the Now Playing data.`

You have to do something with the data inside `np` of course ;)
Your output, in that script, will just be saved to the `nowPlaying` var.

**Comment by queer-webtechnik** [comment]
It's beyond me, I can't handle it. I don't know where to put things. 

Actually I just wanted to have a display of the last songs, but I didn't think it would be so complicated.

**Comment by ogrenci01** [comment]
Hi @queer-webtechnik ;

You can use these codes written in PHP for your website. I think it is simpler for you. I am using to it. Please try it.

Download: http://mixstream.net/streaming/resources/allinone
