### ISSUE TITLE
Audit Log incorrectly logs blank streams. 

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2406]
**Using Docker installation method**
Yes 
**Host Operating System**
CentOS
**Describe the bug**
In the audit logs, if theres no streamer or the streamer disconnected, it'll be incorrectly flagged as NULL NULL 
**To Reproduce**
Unknown way to reproduce, if a streamer disconnects, it may appear. 
**Expected behavior**
To not show the log erroneously 
**Relevant Logs**
```
2020/02/11 21:57:57 [lang:3] Authenticating DJ: robin
2020/02/11 21:57:58 [lang:3] AzuraCast DJ Auth Response: true
2020/02/11 21:57:58 [decoder:3] Method "MAD" accepted "audio/mpeg".
2020/02/11 21:57:58 [lang:3] DJ Source connected! Last authenticated DJ: robin
```
**Screenshots**
Correct Response
![image](https://user-images.githubusercontent.com/29955942/74290857-07eb1200-4d2b-11ea-83b3-a9e49dc8bbe0.png)
Incorrect
![image](https://user-images.githubusercontent.com/29955942/74290887-176a5b00-4d2b-11ea-8b1c-aadad001e5f3.png)

**Device(s):**
 - Device: Desktop 
 - OS: Win10
 - Browser: Chrome
- Version: Latest

**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch This should be fixed as of the latest commit.
