### ISSUE TITLE
Maybe Apache2 ?

### ISSUE THREAD

**Issue by LazosPlaying** [AzuraCast/AzuraCast#241]
Hello, when testing this software in a VM hosted on my PC, i saw that the installer had issue with NGIX not being installed.

On the VPS i am going to host the radio on, i have Apache2 (since i am pretty used to it) and i do not want to start switching to any other software, since i am also hosting some websites for other people on that OS.

So is there any other way, so i can use apache, or is NGIX providing some features, that this software needs in order to run, that Apache does not ?

Thank you in advance.

**Comment by SlvrEagle23** [comment]
@LazosPlaying To answer your question: yes, nginx is currently providing a lot of functionality that AzuraCast depends on to function, namely two big features:

- The port 80/443 web proxy for radio stations, allowing you to serve your stations over HTTPS if necessary. The regular expressions allowing this are somewhat complex, and currently only work in nginx, and aren't simple to implement in Apache or even possible in other alternatives like Caddy.

- Recent updates have introduced a new, significantly faster "live" API endpoint for station song and listener count changes. This endpoint uses the nchan module for nginx to deliver updates via websockets, HTTP long polling, etc. with automatic graceful degradation in the event a browser doesn't support the newer technology.

Note that with the right setup, you could indeed use _both_ nginx and apache on the same server. Typically, this would be done by having one of them sit on a nonstandard port and having the other proxy all requests for relevant domains through to it. In this instance, I would highly recommend that nginx occupies the main ports 80/443 and proxies out to Apache (a rather common setup) than vice versa, as it's unknown if features like nchan will forward properly through Apache.
