### ISSUE TITLE
Error viewing public pages: Error during WebSocket handshake: Unexpected response code: 405

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2412]
**Using Docker installation method**
Yes
**Host Operating System**
CentOS
**Describe the bug**
When viewing a specific public page [LINK ](https://radio.crosshosting.tk:4430/public/ighouls_g-funk_vibes)the error logs and `docker-compose logs -f` spam a bunch of errors relating to files missing / not found and Websocket related errors. 
**To Reproduce**
It appears after creating a station past `59` it appears to break something, we're still testing this however. 

**Expected behavior**

**Relevant Logs**
`docker-compose logs -f` logs 
> web_1       | 2020/02/14 02:29:36 [error] 56#56: *36405 open() "/usr/share/nginx/html/pub/ighouls_g-funk_vibes" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "POST /pub/ighouls_g-funk_vibes HTTP/1.1", host: "localhost:9010"

Chrome debug browser logs 

>WebSocket connection to 'wss://radio.crosshosting.tk:4430/api/live/nowplaying/ighouls_g-funk_vibes' failed: Error during WebSocket handshake: Unexpected response code: 405
t.SubscriberClass.websocket.u.listen @ radio_player-4c86c8d744.js:1
t.start @ radio_player-4c86c8d744.js:1
(anonymous) @ radio_player-4c86c8d744.js:1

Clicking in network tab 

`Error during WebSocket handshake: Unexpected response code: 405`

**Screenshots**
Debug Tab
![image](https://user-images.githubusercontent.com/29955942/74497104-a1a1f300-4ed4-11ea-82db-426a55ab3c67.png)

Network Tab
![image](https://user-images.githubusercontent.com/29955942/74497076-8f27b980-4ed4-11ea-81ae-56724078266d.png)

**Device(s):**
 - Device: Desktop
 - OS: <win10
 - Browser:. chrome
 - Version: latest

**Additional context**

**Comment by SC2Mitch** [comment]
Fixed, Azuracast / Icecast / The Web Socket didn't like a `-` in the station name / Station URL. When it got removed the errors stopped.

**Comment by siderissym** [comment]
I had the same problem and figured out that I had a dot (.) in my station url. When I removed the dot the problem solved!
