### ISSUE TITLE
Unable to clone a station, Cloning a station results in: * A new entity was found through the relationship 'App\Entity\StationMedia#playlists' that was not configured to cascade persist operations for entity

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2413]
**Using Docker installation method**
Yes
**Host Operating System**
CentOS
**Describe the bug**
Attempting to Clone a station via the Adminstration Panels results in a duplication error and 10+ repeated Entity errors (I cloned with Station Media, Playlists)
**To Reproduce**
Go to Administration Panel
Clone Station
See error
**Expected behavior**
It to clone the station 
**Relevant Logs**
Note that these logs go on for hundreds, if not thousands of lines 
` Multiple non-persisted new entities were found through the given association graph: * A new entity was found through the relationship 'App\Entity\StationMedia#playlists' that was not configured to cascade persist operations for entity: App\Entity\StationPlaylistMedia@000000000dd1990400000000729d91b5. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'App\Entity\StationPlaylistMedia#__toString()' to get a clue. * A new entity was found through the relationship 'App\Entity\StationMedia#playlists' that was not configured to cascade persist operations for entity: App\Entity\StationPlaylistMedia@000000000dd1996300000000729d91b5. 
`

**Screenshots**
Clone Settings
![image](https://user-images.githubusercontent.com/29955942/74540078-0ee67000-4f37-11ea-9111-33b2dd0875e9.png)
Error page
![image](https://user-images.githubusercontent.com/29955942/74540200-405f3b80-4f37-11ea-8034-6d4137cccebd.png)

**Device(s):**
 - Device:  Desktop
 - OS:  Win 10
 - Browser:  Chrome
 - Version:  Latest

**Additional context**

**Comment by pavlos-theodorou** [comment]
I encountered the same issue

**Comment by SlvrEagle23** [comment]
@SC2Mitch Should be fixed as of the latest update which is deploying currently.
