### ISSUE TITLE
Playlist playing problem

### ISSUE THREAD

**Issue by mariustgv2004** [AzuraCast/AzuraCast#2414]
I have a radio station with multiple playlists based on different music genres. The automation works well untill I wanted to create a playlist for radio jingles, that would play "once x songs". There is no way this playlist will work above other playlists, as it should do.
What can I do? I reinstalled AzuraCast today, my current version is  v0.9.8.1, using PHP 7.4.
Any help .. please?

**Comment by SC2Mitch** [comment]
Raise the playlist priority, or force it to play

**Comment by mariustgv2004** [comment]
I really don't know how to do that.. I tryed to change its weight, but no luck..

**Comment by SC2Mitch** [comment]
![image](https://user-images.githubusercontent.com/29955942/74561479-8977b580-4f60-11ea-8a56-fda51700aaf5.png)
You can force it to play via this 'interrupt songs'

**Comment by mariustgv2004** [comment]
Already tryed that with no luck :(

**Comment by mariustgv2004** [comment]
As I looked closer to this problem, it seems that there is the "next song" that either is not playing ori remains stuck. I saw this happening even in one single playlist. What could be the problem?

**Comment by SC2Mitch** [comment]
> As I looked closer to this problem, it seems that there is the "next song" that either is not playing ori remains stuck. I saw this happening even in one single playlist. What could be the problem?

Are you using the AutoDJ or is it disabled? I'm wondering if Azura's DJ system is fighting against Liquidsoap. 
![image](https://user-images.githubusercontent.com/29955942/74587743-57149980-4fee-11ea-965c-271176fc2f07.png)

**Comment by mariustgv2004** [comment]
I managed to resolve the issue by activating the option you told me in the jingle playlist and disableing it on all other playlists. This thread can be closed now. Thanks

**Comment by SC2Mitch** [comment]
Glad to hear, you can close the issue at the bottom 
![image](https://user-images.githubusercontent.com/29955942/74588206-5c73e300-4ff2-11ea-95c5-292614560793.png)
