### ISSUE TITLE
30-second promo clip

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2415]
What's the meaning of new update - "30-second promo clip"?

**Comment by Vaalyn** [comment]
AzuraCast now includes a small promo audio clip that can be found at `resources/30_second_promo.mp3` that you can use to promote AzuraCast (if you decide to add the clip to your station).

This update only adds the file to the resources of AzuraCast. It will **not** suddenly play a promo on your station or anything like that.

**Comment by theblindadvocacyradio** [comment]
Where can I find the resources on my server? I looked everywhere. Or, is it on the web interface?

**Comment by SlvrEagle23** [comment]
@theblindadvocacyradio It may not be included with most Docker image builds any more to reduce size, but you can still access and download the file here: https://github.com/AzuraCast/AzuraCast/blob/main/resources/30_second_promo.mp3

**Comment by theblindadvocacyradio** [comment]
Thank you @SlvrEagle23!
