### ISSUE TITLE
Change the meta tags and titles of the radio homepage

### ISSUE THREAD

**Issue by UmitAltun** [AzuraCast/AzuraCast#2416]
Hello, endless thanks for this great software. We use it with pleasure.
I have to change some parts about homepage page favicon and metatags. How can I do it? I did setup as a docker.

Thanks in advance for the answers.

**Comment by ogrenci01** [comment]
Hi @UmitAltun ;

Welcome to the Azuracast family. You can make these changes from the Custom Branding page.

Note: Please write your problems in English, including titles.

Not: Lütfen başlıklar da dahil sorunlarınızı İngilizce olarak yazınız.

**Comment by UmitAltun** [comment]
@ogrenci01 Thank you for your warning. In the brand settings section, I could not see a setting related to metatags.

**Comment by Gujalls** [comment]
Have a look at the below link
https://github.com/AzuraCast/AzuraCast/issues/2257
