### ISSUE TITLE
Can't install. port 8080 in use

### ISSUE THREAD

**Issue by dreinn** [AzuraCast/AzuraCast#242]
Hello,
I'd like to give a try to AzuraCast. Currently I am using a Debian Jessie system, with nginx like proxy and a liquidsoap webstation running properly.
I want to use the docker install, so no conflicts with my existing station and configuration.

When attempting to install, I receive this:

 ERROR: for azuracast_stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (32ff008b12338a38f309a2f0ec6d48c41b105b0623c5e3573b5bd3f312ca48e9):
Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use                                                                                                                                                             

Where is the problem? Is it my nginx system? How can I change the port 8080 to, for example, 8081?

**Comment by dreinn** [comment]
I modified the port 80 with 81, 443 with 444, 8080 with 8081, and 8000 to 8004.
The file is docker-compose.yml

**Comment by SlvrEagle23** [comment]
@dreinn Since this is a common request, I have added a section in the support file with specific instructions on how to customize the Docker Compose file to change port mappings:
https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#change-port-mappings-docker-installations
