### ISSUE TITLE
Creating 2nd Station

### ISSUE THREAD

**Issue by Skyradio** [AzuraCast/AzuraCast#2421]
Hi,
I tried to create a second Station. I changed the media directory to my other Station to share the music for both Stations. But when I restart the Stream,only one Station is able to start. The other one is stopping.

Im using Ansible now. ( I used Docker before but with the same issue)

Mike

**Comment by SC2Mitch** [comment]
What does the logs say?

**Comment by Skyradio** [comment]
Wich logs should I Post? Liquidsoap or icecast?

**Comment by Skyradio** [comment]
`2020/02/17 18:48:06 [main:3] Liquidsoap 1.4.1
2020/02/17 18:48:06 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.3 sedlex=2.1 menhirLib=20200211 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.5.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.3 mad=0.4.5 flac=0.1.5 flac.ogg=0.1.5 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.3.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.9 camomile=1.0.2 faad=0.4.0
2020/02/17 18:48:07 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2020/02/17 18:48:07 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2020/02/17 18:48:07 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2020/02/17 18:48:07 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/www/resources/error.mp3".
2020/02/17 18:48:07 [sandbox:3] Sandboxing disabled
2020/02/17 18:48:07 [video.converter:3] Couldn't find preferred video converter: gavl.
2020/02/17 18:48:07 [audio.converter:3] Using samplerate converter: libsamplerate.
2020/02/17 18:48:07 [harbor:3] Adding mountpoint '/' on port 8005
2020/02/17 18:48:07 [playlist_werbung:3] Loading playlist...
2020/02/17 18:48:07 [playlist_werbung:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_werbung:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_werbung:3] Successfully loaded a playlist of 1 tracks.
2020/02/17 18:48:07 [playlist_jingles:3] Loading playlist...
2020/02/17 18:48:07 [playlist_jingles:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_jingles:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_jingles:3] Successfully loaded a playlist of 77 tracks.
2020/02/17 18:48:07 [playlist_durch_den_morgen:3] Loading playlist...
2020/02/17 18:48:07 [playlist_durch_den_morgen:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/=== sky - Jingles ===/SKY RADIO FM JINGLE 12.mp3".
2020/02/17 18:48:07 [playlist_durch_den_morgen:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_durch_den_morgen:3] Successfully loaded a playlist of 1023 tracks.
2020/02/17 18:48:07 [playlist_mahlzeit:3] Loading playlist...
2020/02/17 18:48:07 [playlist_mahlzeit:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_mahlzeit:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_mahlzeit:3] Successfully loaded a playlist of 0 tracks.
2020/02/17 18:48:07 [playlist_in_the_mix_odc:3] Loading playlist...
2020/02/17 18:48:07 [playlist_in_the_mix_odc:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_in_the_mix_odc:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_in_the_mix_odc:3] Successfully loaded a playlist of 1 tracks.
2020/02/17 18:48:07 [playlist_lovetime:3] Loading playlist...
2020/02/17 18:48:07 [playlist_lovetime:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_lovetime:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_lovetime:3] Successfully loaded a playlist of 1 tracks.
2020/02/17 18:48:07 [playlist_oldschool_radio:3] Loading playlist...
2020/02/17 18:48:07 [playlist_oldschool_radio:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_oldschool_radio:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_oldschool_radio:3] Successfully loaded a playlist of 1 tracks.
2020/02/17 18:48:07 [playlist_quantum_kultur:3] Loading playlist...
2020/02/17 18:48:07 [playlist_quantum_kultur:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_quantum_kultur:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_quantum_kultur:3] Successfully loaded a playlist of 6 tracks.
2020/02/17 18:48:07 [playlist_radiohits_jukebox:3] Loading playlist...
2020/02/17 18:48:07 [playlist_radiohits_jukebox:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_radiohits_jukebox:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_radiohits_jukebox:3] Successfully loaded a playlist of 1 tracks.
2020/02/17 18:48:07 [playlist_re_21mix:3] Loading playlist...
2020/02/17 18:48:07 [playlist_re_21mix:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_re_21mix:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_re_21mix:3] Successfully loaded a playlist of 6 tracks.
2020/02/17 18:48:07 [playlist_schlager_rallye:3] Loading playlist...
2020/02/17 18:48:07 [playlist_schlager_rallye:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_schlager_rallye:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_schlager_rallye:3] Successfully loaded a playlist of 6 tracks.
2020/02/17 18:48:07 [playlist_schlager_boulevard:3] Loading playlist...
2020/02/17 18:48:07 [playlist_schlager_boulevard:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_schlager_boulevard:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_schlager_boulevard:3] Successfully loaded a playlist of 3 tracks.
2020/02/17 18:48:07 [playlist_seebes_welt:3] Loading playlist...
2020/02/17 18:48:07 [playlist_seebes_welt:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_seebes_welt:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_seebes_welt:3] Successfully loaded a playlist of 3 tracks.
2020/02/17 18:48:07 [playlist_startracks:3] Loading playlist...
2020/02/17 18:48:07 [playlist_startracks:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_startracks:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_startracks:3] Successfully loaded a playlist of 5 tracks.
2020/02/17 18:48:07 [playlist_nightline:3] Loading playlist...
2020/02/17 18:48:07 [playlist_nightline:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_nightline:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_nightline:3] Successfully loaded a playlist of 0 tracks.
2020/02/17 18:48:07 [playlist_nightline_weekend:3] Loading playlist...
2020/02/17 18:48:07 [playlist_nightline_weekend:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_nightline_weekend:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_nightline_weekend:3] Successfully loaded a playlist of 0 tracks.
2020/02/17 18:48:07 [playlist_80er_dancemix:3] Loading playlist...
2020/02/17 18:48:07 [playlist_80er_dancemix:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_80er_dancemix:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_80er_dancemix:3] Successfully loaded a playlist of 1 tracks.
2020/02/17 18:48:07 [playlist_beatclub:3] Loading playlist...
2020/02/17 18:48:07 [playlist_beatclub:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_beatclub:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_beatclub:3] Successfully loaded a playlist of 3 tracks.
2020/02/17 18:48:07 [playlist_bergecho:3] Loading playlist...
2020/02/17 18:48:07 [playlist_bergecho:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_bergecho:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_bergecho:3] Successfully loaded a playlist of 3 tracks.
2020/02/17 18:48:07 [playlist_c_60:3] Loading playlist...
2020/02/17 18:48:07 [playlist_c_60:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_c_60:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_c_60:3] Successfully loaded a playlist of 3 tracks.
2020/02/17 18:48:07 [playlist_charts:3] Loading playlist...
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:07 [playlist_charts:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_charts:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_charts:3] Successfully loaded a playlist of 0 tracks.
2020/02/17 18:48:07 [playlist_countrytime:3] Loading playlist...
2020/02/17 18:48:07 [playlist_countrytime:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_countrytime:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_countrytime:3] Successfully loaded a playlist of 5 tracks.
2020/02/17 18:48:07 [playlist_downloadcharts:3] Loading playlist...
2020/02/17 18:48:07 [playlist_downloadcharts:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_downloadcharts:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_downloadcharts:3] Successfully loaded a playlist of 6 tracks.
2020/02/17 18:48:07 [playlist_euro_top40:3] Loading playlist...
2020/02/17 18:48:07 [playlist_euro_top40:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_euro_top40:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_euro_top40:3] Successfully loaded a playlist of 6 tracks.
2020/02/17 18:48:07 [playlist_funkytown:3] Loading playlist...
2020/02/17 18:48:07 [playlist_funkytown:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_funkytown:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_funkytown:3] Successfully loaded a playlist of 2 tracks.
2020/02/17 18:48:07 [playlist_ganorium_voyage:3] Loading playlist...
2020/02/17 18:48:07 [playlist_ganorium_voyage:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_ganorium_voyage:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_ganorium_voyage:3] Successfully loaded a playlist of 3 tracks.
2020/02/17 18:48:07 [playlist_girlpower:3] Loading playlist...
2020/02/17 18:48:07 [playlist_girlpower:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_girlpower:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_girlpower:3] Successfully loaded a playlist of 3 tracks.
2020/02/17 18:48:07 [playlist_happy_days:3] Loading playlist...
2020/02/17 18:48:07 [playlist_happy_days:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_happy_days:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_happy_days:3] Successfully loaded a playlist of 6 tracks.
2020/02/17 18:48:07 [playlist_herms_promicorner:3] Loading playlist...
2020/02/17 18:48:07 [playlist_herms_promicorner:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_herms_promicorner:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_herms_promicorner:3] Successfully loaded a playlist of 1 tracks.
2020/02/17 18:48:07 [playlist_gutes_von_gestern:3] Loading playlist...
2020/02/17 18:48:07 [playlist_gutes_von_gestern:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_gutes_von_gestern:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_gutes_von_gestern:3] Successfully loaded a playlist of 3 tracks.
2020/02/17 18:48:07 [playlist_klangwald:3] Loading playlist...
2020/02/17 18:48:07 [playlist_klangwald:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_klangwald:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_klangwald:3] Successfully loaded a playlist of 3 tracks.
2020/02/17 18:48:07 [playlist_soundtrack_dl:3] Loading playlist...
2020/02/17 18:48:07 [playlist_soundtrack_dl:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/=== sky - Jingles ===/SKY RADIO FM JINGLE 25.mp3".
2020/02/17 18:48:07 [playlist_soundtrack_dl:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_soundtrack_dl:3] Successfully loaded a playlist of 6 tracks.
2020/02/17 18:48:07 [playlist_news:3] Loading playlist...
2020/02/17 18:48:07 [playlist_news:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_news:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_news:3] Successfully loaded a playlist of 1 tracks.
2020/02/17 18:48:07 [playlist_teaser:3] Loading playlist...
2020/02/17 18:48:07 [playlist_teaser:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_teaser:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_teaser:3] Successfully loaded a playlist of 0 tracks.
2020/02/17 18:48:07 [playlist_freizeit:3] Loading playlist...
2020/02/17 18:48:07 [playlist_freizeit:3] No mime type specified, trying autodetection.
2020/02/17 18:48:07 [playlist_freizeit:3] Playlist treated as format application/x-mpegURL
2020/02/17 18:48:07 [playlist_freizeit:3] Successfully loaded a playlist of 593 tracks.
2020/02/17 18:48:07 [error_jingle:3] "/var/azuracast/www/resources/error.mp3" is static, resolving once for all...
2020/02/17 18:48:07 [playlist_werbung:3] Prepared "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3" (RID 3).
2020/02/17 18:48:07 [skyradiofm_local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/90s/VA-Club_Sounds_90s-3CD-2015-VOiCE - DeoTester/Snap! - Rhythm Is A Dancer.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial In the Mix ODC/ThomasWendel_-_InTheMix_ODC.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Lovetime/lovetime.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Oldschool Radio/Sendematerial_12022020.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Quantum Kultur/quantumkultur_01.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Radiohits Jukebox/radiohits_jukebox.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Re!Mix/re!mix_01.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Schlager Rallye/schlager_rallye_01.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Schlagerboulevard/schlagerbvd_01.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Seebes Welt/SeebesWeltTeil1.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Startracks/startracks_part04.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial 80er Dancemix/ThomasWendel_-_Der_80er_DanceMix.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Beatclub/beatclub1.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Bergecho/bergecho_01.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial C-60/sendematerial_c-60_hour01_01.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Klangwald/sendematerial_klangwald_01.mp3".
2020/02/17 18:48:07 [skyradiofm_local_1:3] Connection setup was successful.
2020/02/17 18:48:07 [skyradiofm_relay_1:3] Connecting mount /skyradiofm for source@skyradiofm.stream.laut.fm...
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Gutes v Gestern/gutes_von_gestern_Teil1.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Herms Promi/sendematerial_hermspromicorner.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Happy Days/sendematerial_happydays_hour01_01.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Girlpower/sendematerial_girlpower_01.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Ganorium Voyage/ganoriumvoyage_01.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Funkytown/funkytown01.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Euro Top 40/eurotop40_01.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Downloadcharts/sendematerial_downloadcharts_hour01_01.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Countrytime/countrytime_01.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial Soundtrack DL/soundtrack_01.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/News/Nachrichten.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Dance/dream dance 51-59/Dream Dance Vol. 55/Punk Freakz - The Beat Is Rockin - 140.00 Bpm.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/=== sky - Jingles ===/SKY RADIO FM JINGLE 20.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:07 [skyradiofm_relay_1:3] Connection setup was successful.
2020/02/17 18:48:07 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:07 [skyradiofm_live_switch:3] Switch to skyradiofm_safe_fallback.
2020/02/17 18:48:07 [skyradiofm_safe_fallback:3] Switch to skyradiofm_radio_cue.
2020/02/17 18:48:07 [skyradiofm_requests_fallback:3] Switch to fallback_7872.
2020/02/17 18:48:07 [fallback_7872:3] Switch to delay_7871.
2020/02/17 18:48:07 [playlist_jingles:3] Prepared "/var/azuracast/stations/skyradiofm/media/=== sky - Jingles ===/SKY RADIO FM JINGLE 12.mp3" (RID 5).
2020/02/17 18:48:07 [fallback_7872:3] Switch to fallback_7869 with forgetful transition.
2020/02/17 18:48:07 [fallback_7869:3] Switch to delay_7868.
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/=== sky - Jingles ===/SKY RADIO FM JINGLE 58.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:07 [cross_7922:3] Analysis: -95.384196dB / -14.944128dB (0.99s / 1.01s)
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:07 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:08 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:08 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:08 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:08 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Werbung/start_ad_break.mp3".
2020/02/17 18:48:19 [playlist_c_60:3] Prepared "/var/azuracast/stations/skyradiofm/media/Sendematerial C-60/sendematerial_c-60_hour01_01.mp3" (RID 54).
2020/02/17 18:48:19 [fallback_7869:3] Switch to skyradiofm_schedule_switch with forgetful transition.
2020/02/17 18:48:19 [skyradiofm_schedule_switch:3] Switch to stereo_playlist_c_60.
2020/02/17 18:48:19 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/skyradiofm/media/Sendematerial C-60/sendematerial_c-60_hour01_02.mp3".
2020/02/17 18:48:19 [cross_7922:3] Analysis: -61.326408dB / -16.403611dB (2.98s / 2.98s)
2020/02/17 18:48:19 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/02/17 18:48:19 [lang:3] AzuraCast Feedback Response: OK

`

Also es funktioniert wenn ich die original angelegten Musikverzeichnisse benutze habe ich festgestellt. Aber DAS ist ja genau was ich eigentlich nicht möchte....
