### ISSUE TITLE
per x Songs & Once per x Minutes playlists do not play

### ISSUE THREAD

**Issue by psduk1** [AzuraCast/AzuraCast#2426]
I have set playlist to play 'per x Songs & Once per x Minutes' but neither playlists play.
I have tried various options and settings including setting the playlists to 'Interrupt other songs to play at scheduled time.' as well as setting the playback weight to highest setting, but still nothing.

Can you help ?

**Comment by UmitAltun** [comment]
Hi, After setting your playlist, you need to restart the broadcast from the tools section.

**Comment by psduk1** [comment]
I have restarted several times but the playlist still doesnt play after x songs
