### ISSUE TITLE
Error to clone station

### ISSUE THREAD

**Issue by cristianocarrozzi** [AzuraCast/AzuraCast#2427]
**Using Docker installation method**
Yes

**Host Operating System**

Ubuntu 18.04.2 LTS
**Describe the bug**

When I try clone any station with the option to share the directory, show this error:

A new entity was found through the relationship 'App\Entity\StationMedia#custom_fields' that was not configured to cascade persist operations for entity: App\Entity\[email protected] To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'App\Entity\StationMediaCustomField#__toString()' to get a clue.

**Additional context**

I created a Custom Field and associated with id3v2 tag, after that I can't clone anymore.

**Comment by SC2Mitch** [comment]
Yeah same issue here, it's incredibly annoying.

**Comment by SC2Mitch** [comment]
After testing on my local machine, it breaks after you attempt to copy media and playlists at the same time, cloning the station itself works, just you can't do the media.

**Comment by SlvrEagle23** [comment]
@cristianocarrozzi This should be fixed as of the latest update which is deploying now.
