### ISSUE TITLE
DJ scheduler shows "tz" in stead of of the real time zone.

### ISSUE THREAD

**Issue by AmsterdamFM** [AzuraCast/AzuraCast#2428]
Found a small bug in the new DJ scheduler:

```
Station Time Zone
This station's time zone is currently tz.
```
So tz is displayed instead of the real time zone.

In the playlist scheduler this problem is not present.

**Comment by SlvrEagle23** [comment]
@AmsterdamFM Fixed as of the latest update. Thanks for the report!
