### ISSUE TITLE
PHP imgae is missing

### ISSUE THREAD

**Issue by Mehdouch777** [AzuraCast/AzuraCast#243]
Hi, 

 curl -s http://164.132.45.30:60000/
<br />
<b>Fatal error</b>:  require(): Failed opening required '/var/azuracast/www/vendor/autoload.php' (include_path='.:/usr/share/php') in <b>/var/azuracast/www/app/bootstrap.php</b> on line <b>56</b><br />

php image is messing or something like that ?

**Comment by SlvrEagle23** [comment]
@Mehdouch777 Did you run the installer script as well? The `vendor/autoload.php` file is created during the installation process.

If you're running via Docker, the installer script would be:
```
docker-compose run --rm cli azuracast_install
```
