### ISSUE TITLE
Port SSL 404 Not found in Port Non-Standart (Ansible)

### ISSUE THREAD

**Issue by KoneSV** [AzuraCast/AzuraCast#2430]
**Using Docker installation method**
NO

**Host Operating System**
Ubuntu 16.04

I have problem with port 8022 and SSL, 404 error in Radio (Streaming) and Public Page

Radio (Streaming): https://server1.watahosting.com/radio/8022/radio.mp3
Public Page: 404 Not found.
The requested resource could not be found. Please verify the URI and try again.

Any solution? Ansible Installation

**Comment by ogrenci01** [comment]
Hi @KoneSV ;

You should enable to "Use Web Proxy for Radio" on "System Settings" page. This will solve your problem.

**Comment by SlvrEagle23** [comment]
@KoneSV Port 8022 is not one of our default ports used for radio stations. Our default ports are on the 10s from 8000 up, i.e. 8000, 8010, 8020... (except 8080).

If you want to use nonstandard ports, that's possible but the nginx proxy that relays them through the main web port won't work with those ports by default; the configuration needed to override this is rather advanced and not recommended for most users, so it's recommended to use our standard radio ports instead whenever possible.

**Comment by KoneSV** [comment]
@SlvrEagle23 Can you help me or explain where I do that, the problem that from the beginning of port 8022 and will be great work changes the client, I will have to make the necessary configuration to operate

**Comment by ogrenci01** [comment]
@KoneSV 

You should edit file "**00-azuracast**" in directory "**/etc/nginx/sites-available**" and edit lines 63 and 82 for your customization.

I use a configuration similar to yours. I use ansible installation. It is 9998, 9996, 9994, 9992, etc. for stream and 5940, 5938, 5936, 5934, etc. for dj port. I have not any problem.

**Comment by KoneSV** [comment]
@ogrenci01 
You help me by sharing your 00-azuracast file, to get an idea of how it is edited, since in my file line 63 and 82 are blank

**Comment by ogrenci01** [comment]
@KoneSV 

Configuration files may be different. Would you like to share it with me?

**Comment by KoneSV** [comment]
Yes,
`
server {
    listen 80;
    listen 443 default_server ssl;
    listen [::]:80;
    listen [::]:443 default_server ssl;

    ssl_certificate    /etc/nginx/ssl/server.crt;
    ssl_certificate_key    /etc/nginx/ssl/server.key;

    root /var/azuracast/www/web;
    index index.php;

    server_name localhost;

    add_header X-XSS-Protection 1;
    add_header X-Content-Type-Options nosniff;
    add_header Referrer-Policy no-referrer-when-downgrade;

    access_log /var/azuracast/www_tmp/access.log;
    error_log /var/azuracast/www_tmp/error.log;
    
    client_max_body_size 50M;

    # Serve a static version of the nowplaying data for non-PHP-blocking delivery.
    location /api/nowplaying_static {
        expires 10s;
        add_header Access-Control-Allow-Origin *;

        alias /var/azuracast/www_tmp/nowplaying;
        try_files $uri =404;
    }

    location / {
        try_files $uri @clean_url;
    }

    location @clean_url {
        rewrite ^(.*)$ /index.php last;
    }

    # Set up caching for static assets.
    location /static {
        add_header Access-Control-Allow-Origin *;
    }

    location /static/dist {
        expires 365d;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/azuracast/www/web$fastcgi_script_name;
        include fastcgi_params;

        fastcgi_read_timeout 1800;
        fastcgi_buffering off;
    }

    # Reverse proxy all possible radio listening ports (8000, 8010...8480, 8490)
    location ~ ^/radio/(8[0-4][0-9]0)(/?)(.*)$ {
        proxy_buffering           off;
        proxy_ignore_client_abort off;
        proxy_intercept_errors    on;
        proxy_next_upstream       error timeout invalid_header;
        proxy_redirect            off;
        proxy_connect_timeout     60;
        proxy_send_timeout        21600;
        proxy_read_timeout        21600;

        proxy_set_header Host localhost:$1;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;

        proxy_pass http://127.0.0.1:$1/$3?$args;
    }

    # Reverse proxy the Liquidsoap harbor inputs to allow for streaming.
    location ~ ^/radio/(8[0-4][0-9]5)(/?)(.*)$ {
        proxy_buffering           off;
        proxy_ignore_client_abort off;
        proxy_send_timeout        21600;
        proxy_read_timeout        21600;

        proxy_pass http://127.0.0.1:$1/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    
    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    location ~ /\.ht {
        deny all;
    }
}

server {
    listen 80;
    listen 443  ssl;
    listen [::]:80;
    listen [::]:443  ssl;
    ssl_certificate /etc/letsencrypt/live/server1.watahosting.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/server1.watahosting.com/privkey.pem; # managed by Certbot

    root /var/azuracast/www/web;
    index index.php;
    server_name club.watahosting.com yxy.watahosting.com server1.watahosting.com scan.watahosting.com; # managed by Certbot

    add_header X-XSS-Protection 1;
    add_header X-Content-Type-Options nosniff;
    add_header Referrer-Policy no-referrer-when-downgrade;

    access_log /var/azuracast/www_tmp/access.log;
    error_log /var/azuracast/www_tmp/error.log;
    
    client_max_body_size 50M;

    # Serve a static version of the nowplaying data for non-PHP-blocking delivery.
    location /api/nowplaying_static {
        expires 10s;
        add_header Access-Control-Allow-Origin *;

        alias /var/azuracast/www_tmp/nowplaying;
        try_files $uri =404;
    }

    location / {
        try_files $uri @clean_url;
    }

    location @clean_url {
        rewrite ^(.*)$ /index.php last;
    }

    # Set up caching for static assets.
    location /static {
        add_header Access-Control-Allow-Origin *;
    }

    location /static/dist {
        expires 365d;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/azuracast/www/web$fastcgi_script_name;
        include fastcgi_params;

        fastcgi_read_timeout 1800;
        fastcgi_buffering off;
    }

    # Reverse proxy all possible radio listening ports (8000, 8010...8480, 8490)
    location ~ ^/radio/(8[0-4][0-9]0)(/?)(.*)$ {
        proxy_buffering           off;
        proxy_ignore_client_abort off;
        proxy_intercept_errors    on;
        proxy_next_upstream       error timeout invalid_header;
        proxy_redirect            off;
        proxy_connect_timeout     60;
        proxy_send_timeout        21600;
        proxy_read_timeout        21600;

        proxy_set_header Host localhost:$1;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;

        proxy_pass http://127.0.0.1:$1/$3?$args;
    }

    # Reverse proxy the Liquidsoap harbor inputs to allow for streaming.
    location ~ ^/radio/(8[0-4][0-9]5)(/?)(.*)$ {
        proxy_buffering           off;
        proxy_ignore_client_abort off;
        proxy_send_timeout        21600;
        proxy_read_timeout        21600;

        proxy_pass http://127.0.0.1:$1/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    
    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    location ~ /\.ht {
        deny all;
    }








}`

**Comment by ogrenci01** [comment]
@KoneSV 

find: **location ~ ^/radio/(8[0-4][0-9]0)(/?)(.*)$ {**

replace: **location ~ ^/radio/(8[0-4][0-9]0-9])(/?)(.*)$ {**

You should restart nginx for changes.

**Comment by KoneSV** [comment]
> 
> 
> @KoneSV
> 
> find: **location ~ ^/radio/(8[0-4][0-9]0)(/?)(.*)$ {**
> 
> replace: **location ~ ^/radio/(8[0-4][0-9]0-9])(/?)(.*)$ {**
> 
> You should restart nginx for changes.

Does this work with SSL Cert?

**Comment by ogrenci01** [comment]
@KoneSV 

Yes. It works.

**Comment by KoneSV** [comment]
@ogrenci01 
still the same:
https://server1.watahosting.com/radio/8022/radio.mp3?1582218278
https://server1.watahosting.com/radio/8022/admin.cgi

**Comment by KoneSV** [comment]
@ogrenci01 
Today they all give me trouble after the change does not work nor the standard ports:

https://server1.watahosting.com/radio/8000/radio.mp3
https://server1.watahosting.com/radio/8012/radio.mp3
https://server1.watahosting.com/radio/8020/radio.mp3
https://server1.watahosting.com/radio/8022/radio.mp3

**Comment by KoneSV** [comment]
@ogrenci01 If I am not mistaken the error is: ^/radio/(8[0-4][0-9]0-9**]**)(/?)(.*)$ {

**Comment by ogrenci01** [comment]
@KoneSV 

I am so sorry. I wrote wrong. It is true:

find: location ~ ^/radio/(8[0-4][0-9]0)(/?)(.*)$ {

replace: location ~ ^/radio/(8[0-4][0-9][0-9])(/?)(.*)$ {

You should restart nginx for changes.

**Comment by KoneSV** [comment]
@ogrenci01 Thanks friend, it worked!

**Comment by ogrenci01** [comment]
@KoneSV  No problem bro. Please close this issue.

**Comment by tanotar** [comment]
I was working with this change on my server to have https in other port ranges. Today update the panel and this modification stopped working. Does anyone know about the subject why the modification does not take more?
