### ISSUE TITLE
ls not recording when using alternative authentication format

### ISSUE THREAD

**Issue by joshms123** [AzuraCast/AzuraCast#2432]
**Using Docker installation method**

Yes
**Host Operating System**

Debian
**Describe the bug**

When broadcasting with the icecast2 protocol to the harber mount, using the "username,password" format does not seem to create recordings. However, when using a client with both a username and password field, this works fine.

**To Reproduce**

Broadcast to the streamer mount with "source" as the username and "username,password" as the password.
**Expected behavior**

The stream should be recorded.
**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by joshms123** [comment]
Update:
When using this alternative format, the player does not show who's live, and the disconnect streamer button does not show on the station profile.

**Comment by SlvrEagle23** [comment]
@joshms123 I've done some work to refactor how the special login formats (i.e. with passwords split by `:` or `,`) are handled, so now they're handled before the authentication step, which should fix a number of issues that have been caused by the authentication not quite handling them correctly.
