### ISSUE TITLE
Unable to download backups, Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2434]
**Using Docker installation method**
Yes 
**Host Operating System**
CentOS7
**Describe the bug**
We're unable to pull any backups from our VPS, because it runs into errors with exceeding maximum execution time
**To Reproduce**
Attempt to download a large backup (20+gb) 
**Expected behavior**
It to download and not run into errors. 
**Relevant Logs**
`web_1       | 2020/02/20 18:59:39 [error] 58#58: *102 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/azuracast/www/vendor/guzzlehttp/psr7/src/Stream.php on line 225" while sending to client, client: %%%, server: localhost, request: "GET /admin/backups/download/dGVzdC56aXA= HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "radio.crosshosting.tk:4430"
`
**Screenshots**
None. 
**Device(s):**
win10, desktop, chrome, latest 
**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch Serving files directly through PHP has worked well for us for most files (little media files, album art, etc.) but as we scale into larger files like backup downloads, it really stops working well at all and just ends up consuming an insane amount of memory.

I've updated both our nginx configuration and various parts of the application to use nginx's built-in `X-Accel-Redirect` functionality, which will put nginx in charge of managing serving the download to your browser, which not only uses far less resources but is far faster. This is now applied to media downloads, album art, DJ broadcasts, and backup downloads.

Hopefully this improves the system performance at large.

**Comment by SC2Mitch** [comment]
Thank you, we'll give it a blast and let you know if any issues come up.

**Comment by r1ckross** [comment]
I have a backup of approximately 14Gb that I have tried several times to download, and somewhere about 10-12 Gb into the download it fails with "network error" (client-side message, may not originate from the server at all.)

I have located the file in my /var/lib/docker dir and am downloading it via sftp as root, but it is way slower than the nginx web download was. Is there any way to adjust something so that this larger web backup download can complete successfully?

**Comment by Vaalyn** [comment]
@r1ckross Without having any error messages / logs that's not a question that we can answer.

**Comment by rickross** [comment]
@Vaalyn here you go... these are 3 separate instances of the same fail from this morning:

web_1                      | 2020/11/29 14:48:33 [error] 41#41: *422 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/azuracast/www/vendor/guzzlehttp/psr7/src/Stream.php on line 228" while sending to client, client: 172.29.0.4, server: localhost, request: "GET /admin/backups/download/MXxhenVyYWNhc3RfYmFja3VwXzIwMjAxMTI5 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "amazinggrace.us", referrer: "https://amazinggrace.us/admin/backups"

web_1                      | 2020/11/29 14:53:32 [error] 41#41: *452 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/azuracast/www/vendor/slim/slim/Slim/ResponseEmitter.php on line 118" while sending to client, client: 172.29.0.4, server: localhost, request: "GET /admin/backups/download/MXxhenVyYWNhc3RfYmFja3VwXzIwMjAxMTI5 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "amazinggrace.us", referrer: "https://amazinggrace.us/admin/backups"

web_1                      | 2020/11/29 15:04:47 [error] 41#41: *523 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/azuracast/www/vendor/guzzlehttp/psr7/src/Stream.php on line 228" while sending to client, client: 172.29.0.4, server: localhost, request: "GET /admin/backups/download/MXxhenVyYWNhc3RfYmFja3VwXzIwMjAxMTI5 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "amazinggrace.us", referrer: "https://amazinggrace.us/admin/backups"

**Comment by Vaalyn** [comment]
@rickross could you answer some questions for me, which version are you currently on and are you using an S3 storage or 
a local storage location for backups?

**Comment by rickross** [comment]
Version is "Rolling Release #6183870 (2020-11-29 10:26) • Docker • PHP 7.4"
Backups on local storage
