### ISSUE TITLE
Playlist play "once at specific time / once per day" not working

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#2437]
**Using Docker installation method**
No

**Host Operating System**
Ubuntu 18.04 LTS

**Describe the bug**
I tried to create a playlist which plays one song at a specific time (it is a preproduces show which is ~ an hour long), so I planned it with a lengh of 45 minutes to have some buffer. But the track is played twice each time. If I set the playlist start and end time to the same time, it won't play.

With this settings, the track is played twice:

![image](https://user-images.githubusercontent.com/47743654/75093731-b8a3ad80-5584-11ea-8f87-cda0e5c1e48e.png)
![image](https://user-images.githubusercontent.com/47743654/75093739-c35e4280-5584-11ea-9513-94b9ba4cc15a.png)

With this settings it will skip the song completely:

![image](https://user-images.githubusercontent.com/47743654/75093765-002a3980-5585-11ea-93dd-799c19a8cf1c.png)
![image](https://user-images.githubusercontent.com/47743654/75093771-07514780-5585-11ea-8acb-047a9832e028.png)

Same for this setting:

![image](https://user-images.githubusercontent.com/47743654/75093786-2cde5100-5585-11ea-98df-aa6f19ebc382.png)
![image](https://user-images.githubusercontent.com/47743654/75093793-349df580-5585-11ea-800f-3f48099a3971.png)

**Interesting information**
With AutoDJ in manual mode the one-time-playing of the playlist works great.

**Expected behavior**

Every Saturday on 9 pm (+- some minutes to let the playing song end) AC should play one track of the playlist. (in this example there is just one song in the playlist)

**Solution idea**
How about an "event manager", so that there is another type of schedule-option.
The scheduler will send e.g. a track directly to the "Upcoming song queue". So for example one-time-shows can the planned e.g. 2 weeks or more in the future. This would make it easier to plan preproduced radio shows.

**Comment by bjarn** [comment]
I can approve this issue; the same issue is happening to me. Tried to debug it without any success. Worked fine ~1 month ago.

**Comment by MrSteelMiner** [comment]
Since the update, it worked again, so it isn't playing twice anymore, BUT the scheduled time and the real played time are different. I planned the Track "Blind Dance Radio" to 9 pm, but it was played at 8:48 pm. I tested the scheduling with a testing track and everytime I scheduled it, it was played round about 12-14 minutes before the scheduled time. 
See:
![image](https://user-images.githubusercontent.com/47743654/75616553-af04e180-5b52-11ea-926e-f002da659697.png)
![image](https://user-images.githubusercontent.com/47743654/75616558-b4fac280-5b52-11ea-93f7-e3a21b3e7d68.png)

**Comment by SlvrEagle23** [comment]
@MrSteelMiner Sounds like your server's clock might be off a bit...you may want to check up on that end and make sure it's up to date. You may not notice it from the browser-facing times, since those are localized to your time zone (and often handled by JavaScript).

**Comment by MrSteelMiner** [comment]
I checked it, it is up to date.
