### ISSUE TITLE
Cant install SSL 

### ISSUE THREAD

**Issue by zeoz** [AzuraCast/AzuraCast#2440]
Hello

After installing AzuraCast through Linode docker image, I'm trying to install LetsEncrypt into my server the way installation instructions say (./docker.sh letsencrypt-create mydomain.example.com) 

though im getting the error 
-bash: ./docker.sh: No such file or directory

Any idea how to solve that?

Thanks in advance!

**Comment by MrSteelMiner** [comment]
You have to be in the same directory like the docker.sh file

**Comment by zeoz** [comment]
Thanks for the reply, though the problem was on linode's interface. Nothing to do with the azuracast.
Thank you!
