### ISSUE TITLE
Editing the embed player.

### ISSUE THREAD

**Issue by NotifiedGaming** [AzuraCast/AzuraCast#2441]
Hey there. 

So i'm trying to edit the embed player, in which I have successfully edited the song title and song author's text color, however i'm having difficulty changing the colour of the play button?

I've managed to edit it on chrome through F12, but can't seem to find the ID's to edit the default color and the mouse over color for the custom css.

What're the ID's? .a doesn't seem to be working.

**Comment by HowardCrane** [comment]
Hi,
I took a look and found that the following CSS in the "Custom CSS for Public Pages" field on "Custom Branding" page has the desired effect
`.radio-control-play-button a {
color:#fff !important;
}`

For some CSS hierarchy reason I don't understand, the player's CSS can't be overridden with another style sheet. So this solution changes the style of the player for all stations.

**Comment by NotifiedGaming** [comment]
Cheers! :D

**Comment by Vaalyn** [comment]
Closing the issue as resolved

PS: You should also be able to restrict the styling to only one stations public page when using the station specific class on the `<body>` tag in your CSS. For example on the AC demo public page you'd use this CSS path:
```
.station-azuratest_radio .radio-control-play-button i.material-icons.lg {
    // CSS goes here
}
```
