### ISSUE TITLE
ERROR in my Latest Update

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#2444]
**Using Docker installation method**

NO

**Host Operating System**

Ubuntu 16.04

**Describe the bug**

I updated my azuracast ansible installation to the latest update when i update with ./update command only it shows no error but when i tried to visit in my login URL nothing page display. I try to hit back the update with ./update.sh --full theirs an error after here is the error..

TASK [azuracast-radio : Initialize OPAM - This takes a while...] ****************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "opam init -a --disable-sandboxing --bare && opam switch create 4.08.0", "delta": "0:00:00.447219", "end": "2020-02-24 15:23:30.164308", "msg": "non-zero return code", "rc": 2, "start": "2020-02-24 15:23:29.717089", "stderr": "[NOTE] Make sure that ~/.bash_profile is well sourced in your ~/.bashrc.\n\n[ERROR] There already is an installed switch named 4.08.0", "stderr_lines": ["[NOTE] Make sure that ~/.bash_profile is well sourced in your ~/.bashrc.", "", "[ERROR] There already is an installed switch named 4.08.0"], "stdout": "\nUser configuration:\n  ~/.bash_profile is already up-to-date.", "stdout_lines": ["", "User configuration:", "  ~/.bash_profile is already up-to-date."]}

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=19   changed=4    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0

**Comment by SlvrEagle23** [comment]
@reans Were you able to get this fixed?
