### ISSUE TITLE
Erreur 500 after update

### ISSUE THREAD

**Issue by j2sdwebradio** [AzuraCast/AzuraCast#2446]
**Using Docker installation method**
This Installations witch Docker 

**Host Operating System**
Ubuntu 16.04 

**Describe the bug**
After an update, the dashboard and the public pages display
500
Property App\Entity\Station::$sftpUsers does not exist
RuntimeReflectionService.php : 75

**Device(s):** 
 - Device: Desktop Windows 10
 - OS: Windows 10
 - Browser: Chrome 80

**Comment by haantje72** [comment]
same problem here... station not exists and other errors

**Comment by j2sdwebradio** [comment]
Resolved 

`./docker.sh cli cache:clear`

**Comment by SlvrEagle23** [comment]
@j2sdwebradio You can often avoid issues like this by making sure to update the Docker Utility Script itself along with your AzuraCast update, i.e.:

```bash
./docker.sh update-self
./docker.sh update
```

**Comment by tatojo** [comment]
Didn't work for me!! :(
