### ISSUE TITLE
Can't connect with web panel after docker installation

### ISSUE THREAD

**Issue by dreinn** [AzuraCast/AzuraCast#245]
After docker installation, unfortunately I'm not able to connect with the web panel.-
If I go to:
http://localhost:8081

I obtain a blank page if accessing with w3m, and with Firefox instead "connection aborted".
I modify the 8080 standard port because I already have nginx and apache2 running on my machine. I try also to kill all nginx and apache, restore standard port of Azuracast, but nothing, the result is the same.
How can I have some logs of what is happening?

**Comment by SlvrEagle23** [comment]
@dreinn Did you make sure to only modify the first item in the `docker-compose.yml` port mappings? Nginx will only respond on port 80, so the port mapping should be `8081:80`.

**Comment by dreinn** [comment]
Thank you! Yes now it is solved and I can access the setup using localhost:81
Still thank you!
