### ISSUE TITLE
Listener count 0 in Dashboard on page load

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#2451]
**Using Docker installation method**
Yes

**Host Operating System**
Debian 9

**Describe the bug**
When opening the station profile page the listener counts first show as 0 and are updated a few seconds later with a call to the `/api/station/<id>` API endpoint.

**To Reproduce**
1.  open the station profile
2. look a the listener counts shown on the right side
3. watch them update after a few seconds

**Expected behavior**
The listener count should be available on page load so we should use that data to prefill those values correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/13745863/75364809-967b9980-58bc-11ea-97eb-fde7bd3aafaf.png)

**Additional context**
This issue might seem related to #2383 but I think this is an unrelated issue because the listener counts are correctly shown in the API response, the NowPlaying update log and the stations overview.

**Comment by SlvrEagle23** [comment]
@Vaalyn Yep, noticed this too in my usage. I believe it's a simple fix, just a matter of updating the initial object that populates Vue on the profile page.

**Comment by SlvrEagle23** [comment]
@Vaalyn Should be fixed now!
