### ISSUE TITLE
#Help Impossible to play 1 radio jingle between each song.

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [AzuraCast/AzuraCast#2452]

**Comment by RazielSama** [comment]
Hi, i am the technician in charge of the VM that is running the azuracast instance mentionned here.







**Using Docker installation method**  Yes


**Host Operating System**  Debian GNU/Linux 9.9 (stretch) Kernel: Linux 4.9.0-9-amd64


**Describe the bug**


When the station manager program a jingle to be played between each songs, it does not work anymore. Jingle is played after 2 or 3 songs, and not between each.

Also, now, if a DJ user set a song to be played 19:00 to 20:00 for example, and his song is ending with few minutes late, the song programmed to be played at 20:00 does not start after the previous one, like it does before.

Also, the random playing is now not very random, even if a playlist is set to random, some seems to play in the very same order.

**To Reproduce**   I don't know how to reproduce such troubles.


**Expected behavior**


**Relevant Logs** I do not see any error in logs, but here is what i get in log console


```
web_1       | [2020-02-27T20:57:02.721489+00:00] AzuraCast.INFO: Running 1-minute sync task [] []
web_1       | [2020-02-27T20:57:02.726165+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
influxdb_1  | [httpd] 172.25.0.6 - - [27/Feb/2020:20:57:03 +0000] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.5.1 curl/7.58.0 PHP/7.4.3" b48c2f85-59a3-11ea-99d0-000000000000 3854
web_1       | [2020-02-27T20:57:16.899505+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
influxdb_1  | [httpd] 172.25.0.6 - - [27/Feb/2020:20:57:17 +0000] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.5.1 curl/7.58.0 PHP/7.4.3" bcee5789-59a3-11ea-99d1-000000000000 4622
web_1       | [2020-02-27T20:57:31.866777+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
influxdb_1  | [httpd] 172.25.0.6 - - [27/Feb/2020:20:57:32 +0000] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.5.1 curl/7.58.0 PHP/7.4.3" c5d81459-59a3-11ea-99d2-000000000000 6242
web_1       | [2020-02-27T20:57:46.898398+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
influxdb_1  | [httpd] 172.25.0.6 - - [27/Feb/2020:20:57:47 +0000] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.5.1 curl/7.58.0 PHP/7.4.3" ced023c0-59a3-11ea-99d3-000000000000 4126
stations_1  | 2020-02-27 20:57:50,662 INFO exited: tmpreaper (exit status 0; expected)
stations_1  | 2020-02-27 20:57:51,672 INFO spawned: 'tmpreaper' with pid 7227
stations_1  | 2020-02-27 20:57:52,682 INFO success: tmpreaper entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
web_1       | [2020-02-27T20:57:56.754283+00:00] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []
influxdb_1  | [httpd] 172.25.0.6 - - [27/Feb/2020:20:57:57 +0000] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.5.1 curl/7.58.0 PHP/7.4.3" d4c3af7a-59a3-11ea-99d4-000000000000 5100
web_1       | [2020-02-27T20:58:02.449357+00:00] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []
web_1       | [2020-02-27T20:58:02.816350+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
web_1       | [2020-02-27T20:58:02.916867+00:00] AzuraCast.INFO: Running 1-minute sync task [] []
influxdb_1  | [httpd] 172.25.0.6 - - [27/Feb/2020:20:58:02 +0000] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.5.1 curl/7.58.0 PHP/7.4.3" d829dfcb-59a3-11ea-99d5-000000000000 8567
influxdb_1  | [httpd] 172.25.0.6 - - [27/Feb/2020:20:58:03 +0000] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.5.1 curl/7.58.0 PHP/7.4.3" d83cd8f7-59a3-11ea-99d6-000000000000 3036
web_1       | [2020-02-27T20:58:04.955886+00:00] AzuraCast.INFO: Handling message of type App\Message\UpdateNowPlayingMessage. [] []
web_1       | [2020-02-27T20:58:05.190041+00:00] AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... [] {"station":{"id":1,"name":"Dunkerque Street Radio Jeune"}}
web_1       | [2020-02-27T20:58:05.202314+00:00] AzuraCast.INFO: Playable playlists of type "once_per_x_songs_unscheduled" found. {"103":3} {"station":{"id":1,"name":"Dunkerque Street Radio Jeune"}}
web_1       | [2020-02-27T20:58:05.205412+00:00] AzuraCast.WARNING: No way to avoid same title OR same artist; using least recently played song. {"media_id":1320} {"station":{"id":1,"name":"Dunkerque Street Radio Jeune"}}
web_1       | [2020-02-27T20:58:05.220744+00:00] AzuraCast.INFO: Playable track found and registered. [] {"station":{"id":1,"name":"Dunkerque Street Radio Jeune"}}
influxdb_1  | [httpd] 172.25.0.6 - - [27/Feb/2020:20:58:05 +0000] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.5.1 curl/7.58.0 PHP/7.4.3" d99456a6-59a3-11ea-99d7-000000000000 2710


```

Can someone please assist us ?

Regards,

**Comment by SlvrEagle23** [comment]
@RazielSama In my local tests, I was able to create a playlist of the "Once per x songs" type and it played once every 1 song (i.e. between every song) on my local installation and it worked without issue.

It's possible that our latest changes to how the AutoDJ calculates playback has helped this issue quite a lot (in fact, it's likely), so you may want to update to the very latest version of the code as of this week and let me know if the issue persists.

**Comment by TechComputerServiceDunkerque** [comment]
Hello, the problem with the jingles has been solved, but the problem comes from the Scheduled. I do program the mixes at 9pm, but if the 8pm mix is a bit longer than 5 minutes, at 9:05pm, it puts another mix in the 8pm playlist instead of the 9pm one. I have to do the following twice for the 9pm mix to be programmed. Same for the 10pm mix, otherwise he puts the 9pm mix in repeat. I don't understand why it does this, but the problem becomes urgent because we are a professional French webradio and because of these numerous bugs, some listeners complain... Thank you for your understanding 

Translated with www.DeepL.com/Translator (free version)

**Comment by emiryapici** [comment]
Hello, i have the same problem with my station. 

I've made jingle playlist as "Once per x songs" and typed 1 below box. Also my ls config looks like:

# Standard Playlists
radio = random(id="azuratest1_standard_playlists", weights=[3], [playlist_a___category])

# Once per x Songs Playlists
radio = rotate(weights=[1,1], [playlist_jingles, radio])

but jingles not playing exact between each song. Sometimes it plays three jingles or two songs in a row.

**Best regards.**

**Comment by TechComputerServiceDunkerque** [comment]
> Hello, i have the same problem with my station.
> 
> I've made jingle playlist as "Once per x songs" and typed 1 below box. Also my ls config looks like:
> 
> # Standard Playlists
> radio = random(id="azuratest1_standard_playlists", weights=[3], [playlist_a___category])
> 
> # Once per x Songs Playlists
> radio = rotate(weights=[1,1], [playlist_jingles, radio])
> 
> but jingles not playing exact between each song. Sometimes it plays three jingles or two songs in a row.
> 
> **Best regards.**

I gave up Azuracast, I took a new cheap radiomanager because it's bugs all the time, it's getting weary, if you're interested. here's the link: https://conceptradio.fr/radio-manager/

**Comment by SlvrEagle23** [comment]
@TechComputerServiceDunkerque Please do not talk about a project we work extremely hard on and pour a lot of time and love into like that on our own repository, and please do not use this as a platform for promoting other software, especially if it's intended to replace this one.
