### ISSUE TITLE
Admin Panel Current CPU Load is very inaccurate

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2458]
**Using Docker installation method**
yea
**Host Operating System**
CentOS7
**Describe the bug**
Admin Panel is very inaccurate on current CPU loads and CPU average

**To Reproduce**
Check via `Top` or some other software, or even a web panel you have for the exact specifics. 

**Expected behavior**
It to show the exact CPU usage of the full Azuracast instance, not one station. 

**Relevant Logs**
None
**Screenshots**
Web Panel CPU usage - 
![image](https://puu.sh/FfwWl/d768afd51f.png)
Azura's panel - 
![image](https://user-images.githubusercontent.com/29955942/75594909-5ebe4e80-5a82-11ea-9f20-03797f986721.png)

**Device(s):**
win10, chrome, latest, desktop
**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch How does it compare to the actual numeric CPU load value seen on, say, `top` or `htop`?

The CPU load value is based on 1.00 being 100% of a single processing unit (i.e. core) so if you had 8 cores in your machine, a load of 5 would be about 60% or so.

**Comment by SC2Mitch** [comment]
> @SC2Mitch How does it compare to the actual numeric CPU load value seen on, say, `top` or `htop`?
> 
> The CPU load value is based on 1.00 being 100% of a single processing unit (i.e. core) so if you had 8 cores in your machine, a load of 5 would be about 60% or so.

That makes a lot of sense, kinda? The UI is a bit weird, but we can see a lot more clearly what you mean.

**Comment by SlvrEagle23** [comment]
@SC2Mitch It's a pretty common Unix type thing to show load that way.

**Comment by SC2Mitch** [comment]
Yeah, we understand, thank you for explaining! Issue closed.
