### ISSUE TITLE
Trying to use Apache on same server

### ISSUE THREAD

**Issue by HowardCrane** [AzuraCast/AzuraCast#2460]
Hi. AzuraCast was the first thing I put on this fresh Ubuntu VPS I purchased and all of this is very new to me. I installed Apache to serve podcast/archive downloads to the public, changing ports.conf and VirtualHost so it works on a separate port - won't play ball. I'd like to know what else I'm missing, because I've been troubleshooting and Googling my way into a deep depression for the past 3 days lol
I've learned that AzuraCast runs on Nginx, thus the conflict. I also learned it's more suited to static files, which is great for my purpose, but I can't find it in my installed packages list.

There's nothing I dislike more than being a noob and having to crowd your github board with my noob questions, so I appreciate any kindness you can show me.

**Comment by SC2Mitch** [comment]
Hi there @HowardCrane Have you tried the Multi-Site setup? It might help you out here. https://www.azuracast.com/extending/multisite.html#azuracast-multi-site-docker-installation

**Comment by HowardCrane** [comment]
@SC2Mitch I believe this is the magic I've been looking for. I've followed the instructions without a hitch, but the link to the nginx proxy repo doesn't make sense to me. AzuraCast still has the top-level domain, so do I interact with nginx via docker to create a subdomain? Is this my aim going forward?
Thanks. You're a star

**Comment by SC2Mitch** [comment]
On our end, our Azuracast Instance runs through a subdomain and it works fine for us ™️ such as `sub.domain.com` and have you tried disabling Cloudflare and trying it again?

**Comment by HowardCrane** [comment]
Interesting development. It may have taken a while for the DNS to catch up, and now the subdomain container is mirroring AzuraCast. Have I configured the container wrong or is this DNS magic?

**Comment by Asthriona** [comment]
If you need it, Apache have it own proxy system, you can redirect it to the port 80.
Here is a config example of mine.
```
<VirtualHost *:80>
        ServerAdmin contact@animefm.co
        ServerName broadcaster.animefm.co
        ProxyPass / http://localhost:3500/
        ProxyPassReverse / http://localhos:3500/
        ProxyPreserveHost On
</VirtualHost>
```
Azuracast running on port 3500 but Apache redirect it to 80 with the subdomain.
[here is a link to Digital ocean that can help you if you didn't already check this.](https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension)
Also, it works with Cloudflare, since my station uses it.
