### ISSUE TITLE
Stopping azuracast_web 

### ISSUE THREAD

**Issue by superboys2017** [AzuraCast/AzuraCast#2461]
Online dj wil not start a stream

**Comment by superboys2017** [comment]
or how can i change the port 8080 to 8880 it wil not work

**Comment by SlvrEagle23** [comment]
@superboys2017 We need way more information than this in order to help us diagnose issues. Please follow the template that you see when creating a new issue.

**Comment by superboys2017** [comment]
https://i.gyazo.com/thumb/1200/0438bae3aa2452e0b0cfd3b618172eac-png.jpg
i get this error whit auto player an when i try to start a stream it won`t start

**Comment by superboys2017** [comment]
http://prntscr.com/r9spyq
http://prntscr.com/r9sq37
see this

**Comment by superboys2017** [comment]
http://prntscr.com/r9szbq
