### ISSUE TITLE
CHROME 80 BLOCKS UNSECURED STREAMS

### ISSUE THREAD

**Issue by YosefAdPro** [AzuraCast/AzuraCast#2462]
Google Chrome starts with version 80 blocking non-HTTPS streaming.
By default, Google Chrome will attempt to auto-upgrade http:// links to https:// with no fallback to http://. 

I tried to change these lines in Icecast Configuration to my certificate:
`<ssl-private-key>/etc/nginx/ssl/ssl.key</ssl-private-key>
        <ssl-certificate>/etc/nginx/ssl/ssl.crt</ssl-certificate>
        `
But after restarting the station, it loses the SSL manual settings.
Manual settings must be enabled for ICECAST / SHOUTCAST.

However to use SSL with SHOUTCAST is required to pay for version 2.6

**Comment by SlvrEagle23** [comment]
@YosefAdPro Icecast by default points to the same certificate used by the web container's nginx server, so if you set up LetsEncrypt on one, it also works directly via the Icecast servers. Our built-in "web proxy" feature is meant to work around this problem by serving the radio stream directly via the web port through an nginx proxy.

Unfortunately, there's nothing we can do about SHOUTcast's business decisions. In general, we highly recommend against using SHOUTcast whenever possible with AzuraCast, as Icecast integration is much stronger and better documented.

**Comment by YosefAdPro** [comment]
I'm not using LetsEncrypt. I have a COMODO certificate.

I stayed with the original settings and just placed the certificate + key :
/etc/nginx/sites-available/00-azuracast
```
 /etc/nginx/ssl/server.crt
 /etc/nginx/ssl/server.key
```
NGINX works great, but ICECAST doesn't open a station with SSL.

Icecast Error Log:
`> [2020-03-01  09:35:50] WARN connection/get_ssl_certificate Invalid cert file /etc/nginx/ssl/ssl.crt (system lib)`

**Comment by scysys** [comment]
`/etc/nginx/ssl/server.crt`

Look at the other files from Comodo. On Letsencrypt you need the "fullchain" and "privkey" file for Icecast. If Comodo does not have an ready file for it you should copy the cert and chain into on file.

**Comment by viaricardo** [comment]
You need to append both in one file to Icecast read it correctly. First certificate, then public key.

**Comment by viaricardo** [comment]
But, how to solve the manual configuration persistence?
You need to update few sub-keys on xml config file, it's not easy as append a few lines...

**Comment by YosefAdPro** [comment]
According to the ICECAST documentation there should be a PEM file.
Containing the certificate + key in one file.
![image](https://user-images.githubusercontent.com/11810187/76264462-8f646c00-626a-11ea-9486-9b36b3389bbf.png)

**Comment by SlvrEagle23** [comment]
@YosefAdPro Note that we're using Icecast-KH, which sometimes differs from Icecast and in this case differs in that we expect both `server.crt` and `server.key`.

**Comment by YosefAdPro** [comment]
desperate :(
We'll use Proxy.
Thank you to everyone who offered help.

**Comment by master-magic** [comment]
@YosefAdPro I use the same server like you and have lets encrypt running but it gives me also error in chrome that the SSL link of the stream is not safe, have you find already a solution of that problem??????
my azuracast works perfectly for what I want, except the SSL is not working good, it says it is an US file and it's not accepted as SSL file :(

**Comment by YosefAdPro** [comment]
@master-magic My SSL works well on the nginx.
My problem was with icecast SSL.

I didn't get along and I'm working with a proxy to stream icecast with SSL.

**Comment by master-magic** [comment]
@YosefAdPro ow ok, i have noticed that I have the server SSL files and lets encrypt running for SSL on my comodo VPS server, I think that is my problem, 
have you only your server SSL or also like me server SSL and lets encrypt ????

**Comment by YosefAdPro** [comment]
Comodo only.

**Comment by master-magic** [comment]
@YosefAdPro thanks for your reaction, now I have to find out to let this work so the SSL is working good on chrome and firefox and the whole site also where the system is running on.
strange that I have so much problem, my SSL says in firefox that it is a file in the US, but the server is in Germany, maybe that give the problem???

**Comment by master-magic** [comment]
ok after 30 minutes searching and changing I have it worked under lets encrypt only the whole system, also the streams working onder that option, 
I used certbot and lets encrypt in my VPS server and now everything works under Chrome (new version tested).
for me it work now perfectly.
i have to reboot the system also to let this work.....
