### ISSUE TITLE
SSL Shoutcast, together we will be able to

### ISSUE THREAD

**Issue by tanotar** [AzuraCast/AzuraCast#2463]
Hi. As almost everyone knows, today browsers are requesting the use of "HTTPS". I was investigating the use of ssh in shoutcast and alone and found a couple of guides, creating a php file but most throw error. Someone who understands better in php could help us to be able to use SSL in Shoutcast. I leave some guides that can improve and together we can solve this case.

https://stackoverflow.com/questions/59737108/restream-a-shoutcast-icecast-stream-using-php
https://www.svnlabs.com/blogs/radio-icecast-shoutcast-php-proxy-to-re-stream-radio-stream-on-https/
https://stackoverflow.com/questions/7998773/is-it-possible-to-restream-an-internet-radio-using-php-php-guru-needed
https://stackoverflow.com/questions/36306457/read-mp3-stream-and-echo-back-to-client-in-php

**Comment by SlvrEagle23** [comment]
@tanotar AzuraCast already has a built-in web proxy that uses our primary nginx web server to forward traffic back to either the Icecast or SHOUTcast frontend of the given station. It just has to be turned on in the System Settings panel and will be enabled for all stations.

**Comment by tanotar** [comment]
With Icecast and perfect the use of SSL. But Shoutcast doesn't work at all.
Run this guide on my server.
"./docker.sh letsencrypt-create mydomain.example.com"
Then activate in "Settings" "Always use HTTPS"
Restart the station that uses "Shoutcast" and the use of "https://" does not work, throw error 404. In "http: //" it works perfect.

**Comment by SlvrEagle23** [comment]
@tanotar The setting you're looking for is "Enable Web Proxy", which will update the URLs to use the proxied URL, which should have your LetsEncrypt certificate applied.

**Comment by tanotar** [comment]
I have activated "Enable Web Proxy" in the configuration, restart the station started with Shoutcast and continue throwing "Error 404"

**Comment by tanotar** [comment]
Found the problem. I use the IP ranges from "9200" onwards with my clients. In the file "/var/azuracast/docker-compose.yml" these ranges are configured to make the ports work. But for SSL it seems that it doesn't take those IP ranges. Create an account with port "8010" and the Shoutcast in SSL work perfect.
How do I solve my problem because of the port range I use?

**Comment by SlvrEagle23** [comment]
@tanotar Fixing that requires overriding your nginx configuration to add the ports, which is an advanced process that requires some understanding of nginx. You can follow our instructions [here](https://www.azuracast.com/extending/modifying_docker.html#common-examples) for a guide on how to get started.

It's recommended for ease of use that you stick to our auto-assigned port ranges (i.e. 8000-8999 in increments of 10).
