### ISSUE TITLE
Banning an IP doesn't restrict them in some cases

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2467]
**Using Docker installation method**
yes

**Host Operating System**
centos7

**Describe the bug**
when banning a single IP it sometimes doesn't work

**To Reproduce**
ban just one IP and attempt to listen to the station 

**Expected behavior**
 The ban to work fully

**Relevant Logs**
 No logs, Buster is aware of this

**Screenshots**

**Device(s):**
 - Device:  desktop
 - OS:  win10
 - Browser:  chrome
 - Version:  latest

**Additional context**

Banning multiple IPS appears to bypass this issue and is a workaround for now

**Comment by SlvrEagle23** [comment]
@SC2Mitch This may be caused by Icecast itself...see upstream issue: karlheyes/icecast-kh#286
