### ISSUE TITLE
500  Station not found. PublicController.php : 28 

### ISSUE THREAD

**Issue by tatojo** [AzuraCast/AzuraCast#2469]
**Using Docker installation method**
Yes

**Host Operating System**
Debian 9

**Describe the bug**

Public page send error:
500
Station not found.
PublicController.php : 28 
**To Reproduce**

1. Go to 'Profile'
2. Click on 'Public page'
3. See the error

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SC2Mitch** [comment]
@tatojo are you running the latest update?

**Comment by tatojo** [comment]
Yes, I am.
I just update again but have the same error.

**Comment by SlvrEagle23** [comment]
@tatojo We aren't having this issue locally, or on our demo installation: https://demo.azuracast.com/public/azuratest_radio

Do you have your station listed as "hidden" from public pages? This will also cause any attempt to view the public pages to return a "Station Not Found" error.

**Comment by tatojo** [comment]
Hi @SlvrEagle23 , nice to see you!
Indeed, I have two radio stations deployed, but disabled the public page of one. Actually, before a couple of updates, I was able to have one public page enable and the other disabled. But since a week or so, both are disable. Now I enable both and the public pages are ok.
I wonder if in the future I could have some public pages disabled (for maintenance) and others enbled!
So, no more error 500!
Thanks!
