### ISSUE TITLE
Welcome to nginx!

### ISSUE THREAD

**Issue by rolradio** [AzuraCast/AzuraCast#247]
Good day

Today I did an update to the latest version of azuracast.
After that, the number of listeners and the titles of the songs were no longer visible.

I also did the full update.

![afbeelding](https://user-images.githubusercontent.com/28436289/31569813-434c7b0a-b07e-11e7-98c0-8ea489d27a60.png)

TASK [azuracast-update : Regenerate Doctrine Proxies] **********************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php orm:generate-proxies", "delta": "0:00:01.145933", "end": "2017-10-14 01:10:12.354423", "failed": true, "rc": 255, "start": "2017-10-14 01:10:11.208490", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

RUNNING HANDLER [azuracast-cron : restart cron] ****************************************************
        to retry, use: --limit @/var/azuracast/www/util/ansible/update.retry

PLAY RECAP *****************************************************************************************
localhost                  : ok=77   changed=26   unreachable=0    failed=1

**Comment by SlvrEagle23** [comment]
@rolradio If you manually execute
```
php /var/azuracast/www/util/cli.php orm:generate-proxies
```
in your terminal, what happens?

**Comment by rolradio** [comment]
@SlvrEagle23 
Sorry for the late reply.
This command does not give a result.
I notice that the first 4 stations will show the title and the performer but the next 3 will not.
Probably a cause of removal and a name change of a radio station. The 5th radio station has changed its name in the panel.
It also strikes me that if a radio is cleared by the azuracast panel, this on the server is not removed.
All folders with config, media and playlist will remain.

**Comment by rolradio** [comment]
@SlvrEagle23 On your recommendation,i decided to create a new Azuracast installation on another better server.
This time via docker.
This seems safer if something goes wrong.
After some searching, I managed to get azuracast working.
Unfortunately, I note that songs in the media folder can not be linked to a playlist at once.
After the first 20, you must add each song one by one to the playlist.
Otherwise they will be checked and will not appear in the playlist.
Where could the error be?

**Comment by rolradio** [comment]
Problem is solved.

**Comment by curchunflo** [comment]
> Problem is solved.

hi! could you please tellme how did you resolve it? I made a fresh install and only get the nginx welcome page when I go to localhost

**Comment by SchattenWolf2008** [comment]
SAME FOR ME
I hate it when people just say issue solved and not tell how they did it.
Because you can help many people and save their time.
