### ISSUE TITLE
#idea: Develop an option that increases the bpm of the songs. 

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [AzuraCast/AzuraCast#2471]
Bonjour l'équipe Azuracast, 

I have an idea for azuracast, why not develop an option for the speed of the tracks, having the possibility to increase the bpm of the tracks (pitch) like a French radio does (Skyrock). I think it's not bad and it gives another image of the radio that puts the option in operation.

**Comment by SlvrEagle23** [comment]
@TechComputerServiceDunkerque Hello! We handle new feature requests through a separate web site, https://features.azuracast.com/, so that we can limit GitHub to critical issues that need our response. You're welcome to submit this idea there for consideration.
