### ISSUE TITLE
 LOADING Redis is loading the dataset in memory IN UPGRADE

### ISSUE THREAD

**Issue by pabpineda** [AzuraCast/AzuraCast#2475]
I updated and threw that error at me.

Ubuntu 18.04 with Docker

Reload System Data
------------------

In ClearCacheCommand.php line 12:

  LOADING Redis is loading the dataset in memory

azuracast:setup [--update] [--load-fixtures] [--release]

2020/03/05 03:11:46 Command exited with error: exit status 1
azuracast_redis_1 is up-to-date
azuracast_stations is up-to-date
azuracast_mariadb_1 is up-to-date
azuracast_influxdb_1 is up-to-date
Creating azuracast_web ... done
Update complete!

**Comment by pabpineda** [comment]
![azuraerrorredis](https://user-images.githubusercontent.com/42784360/75944644-dd8a0180-5e5d-11ea-85a8-0636e6cebfb1.jpg)

**Comment by pabpineda** [comment]
![azuraerrorredis2](https://user-images.githubusercontent.com/42784360/75945153-12e31f00-5e5f-11ea-9509-9432aa44a443.jpg)

**Comment by pabpineda** [comment]
![azuraerrorredis2](https://user-images.githubusercontent.com/42784360/75945207-327a4780-5e5f-11ea-9799-6fa954ac36e5.jpg)

**Comment by SlvrEagle23** [comment]
I haven't seen this error before and don't know what's causing it.

**Comment by pabpineda** [comment]
In some moments it throws this error
![azuraerrorredis3](https://user-images.githubusercontent.com/42784360/75945985-6bb3b700-5e61-11ea-9d47-31a385056503.jpg)


In CompiledContainer.php line 227:

  Connection refused

**Comment by Hanner72** [comment]
The same for me! :-(

**Comment by SlvrEagle23** [comment]
@Hanner72 We've made some significant changes to the codebase, and this should no longer be happening in newer versions of the application. Are you running the latest version?

**Comment by Hanner72** [comment]
I have an update with
```
cd /var/azuracast
./docker.sh update-self
./docker.sh update
```
made and during this the mistake comes.

Sorry for my english.

![azuracast_update_error](https://user-images.githubusercontent.com/25680545/78931854-db434480-7aa6-11ea-8d65-df7467c7fbd8.PNG)

**Comment by Hanner72** [comment]
HTTP ERROR 500

**Comment by SlvrEagle23** [comment]
@pabpineda Check your Docker logs via:

```bash
cd /var/azuracast
docker-compose logs -f redis
```

and let us know if there are any obvious errors.

**Comment by Hanner72** [comment]
This is my
```
redis_1     | 1:M 10 Apr 2020 07:57:51.892 * Reading RDB preamble from AOF file...
redis_1     | 1:M 10 Apr 2020 07:57:51.899 * Reading the remaining AOF tail...
redis_1     | 1:M 10 Apr 2020 07:57:52.783 # Bad file format reading the append only file: make a backup of your AOF file, then use ./redis-check-aof --fix <filename>
redis_1     | 1:C 10 Apr 2020 07:58:54.265 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 1:C 10 Apr 2020 07:58:54.265 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1     | 1:C 10 Apr 2020 07:58:54.265 # Configuration loaded
redis_1     | 1:M 10 Apr 2020 07:58:54.268 * Running mode=standalone, port=6379.
redis_1     | 1:M 10 Apr 2020 07:58:54.268 # Server initialized
redis_1     | 1:M 10 Apr 2020 07:58:54.268 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 1:M 10 Apr 2020 07:58:54.268 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 1:M 10 Apr 2020 07:58:54.268 * Reading RDB preamble from AOF file...
redis_1     | 1:M 10 Apr 2020 07:58:54.276 * Reading the remaining AOF tail...
redis_1     | 1:M 10 Apr 2020 07:58:55.081 # Bad file format reading the append only file: make a backup of your AOF file, then use ./redis-check-aof --fix <filename>
```

**Comment by Hanner72** [comment]
Hello,

I was able to correct the errors using the information in the logs. But how can I fix the AOF error?

Unfortunately I cannot find any information on this on the Internet. Unfortunately I'm not a professional either. :-(

Here is my new LOG of

```
cd / var / azuracast
docker-compose logs -f redis
```


```
redis_1 | 1: C Apr 11, 2020 19: 22: 36.954 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1 | 1: C 11 Apr 2020 19: 22: 36.954 # Redis version = 5.0.5, bits = 64, commit = 00000000, modified = 0, pid = 1, just started
redis_1 | 1: C Apr 11, 2020 7:22 pm: 36,954 # Configuration loaded
redis_1 | 1: M 11 Apr 2020 19: 22: 36.956 * Running mode = standalone, port = 6379.
redis_1 | 1: M 11 Apr 2020 19: 22: 36.956 # server initialized
redis_1 | 1: M Apr 11, 2020 19: 22: 36.956 * Reading RDB preamble from AOF file ...
redis_1 | 1: M Apr 11, 2020 19: 22: 36.962 * Reading the remaining AOF tail ...
redis_1 | 1: M 11 Apr 2020 19: 22: 37.781 # Bad file format reading the append only file: make a backup of your AOF file, then use ./redis-check-aof --fix <filename>
```

I am asking you for help. My internet radio is in operation. The music is on, but I can't administer anything.

Thanks.

**Comment by SlvrEagle23** [comment]
@Hanner72 I have published a small update that should help resolve this issue. In order to take advantage of the update, you should run:

```bash
cd /var/azuracast
./docker.sh update-self
./docker.sh update
```

...which will flush the Redis cache file during the routine update process, which will alleviate any issues of this nature.

**Comment by Hanner72** [comment]
Yeeees! Perfect! You are my Hero! 👍
