### ISSUE TITLE
Error 500 on GeoLite/MaxMind License Key

### ISSUE THREAD

**Issue by pavlos2** [AzuraCast/AzuraCast#2482]
**Using Docker installation method**

YES

**Host Operating System**

Ubuntu 18.04 LTS

**Describe the bug**

Hi, I tried twice to save the MaxMind License Key and got the following error:

![Annotation 2020-03-07 144430](https://user-images.githubusercontent.com/39927643/76143774-ea3b6f00-6082-11ea-954e-461284d90ad0.jpg)

**Comment by viaricardo** [comment]
**Using Docker installation method**

YES

**Host Operating System**
CentOS 7

**Comment by viaricardo** [comment]
**Using Docker installation method**
YES

**Host Operating System**
CentOS 7

I have the same issue... There is any way to download manually the free database?

**Comment by SlvrEagle23** [comment]
@viaricardo @pavlos2 I've updated the GeoLite update script to provide more information in the event that the original file download fails for whatever reason. It's likely that there's an HTTP connection error happening between you and the MaxMind servers which is causing the problem. The latest update will actually show that error in a red popup message, which should help further diagnose things.

**Comment by pavlos2** [comment]
Thanks a lot Buster! I managed to get the database.
