### ISSUE TITLE
Can’t connect from VirtualDj to WebRadio via CloudFlare

### ISSUE THREAD

**Issue by DaniloL88** [AzuraCast/AzuraCast#2483]
**Using Docker installation method**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

Hello,
I’ve installed AzuraCast into my Linux VPS and I just turn on my VirtualDj to do some live.
If I put my domain protected by cloudflare live didn’t start but if I put the source ip (of my VPs) live starts.
I’ve set Web Proxy on the settings page.
What’s the problem?

**Comment by Vaalyn** [comment]
Because CloudFlare blocks any incoming connections that aren't on the standard web ports you'll have to use the IP of your VPS to connect as streamer.

You can read more about this [here](https://www.azuracast.com/extending/cloudflare.html#incoming-dj-connections)

**Comment by DaniloL88** [comment]
So, is there any way to don’t show up my original VPS IP to my DJ/Speaker?

**Comment by Vaalyn** [comment]
Maybe this entry from the CloudFlare support site can help you there https://support.cloudflare.com/hc/en-us/articles/200169156-Identifying-network-ports-compatible-with-Cloudflare-s-proxy

I haven't used CloudFlare yet so I'm not really sure what can be done there.
