### ISSUE TITLE
Import playlist is missing in  v0.9.8.1

### ISSUE THREAD

**Issue by solucionescol** [AzuraCast/AzuraCast#2489]
Hi:

i just installed a new server with  v0.9.8.1 and i dont dind the way to import playlists

thankyou in advance for your atention.

is it removed ?

is it in another place?

do i have an error in my installation?

**Comment by SlvrEagle23** [comment]
@solucionescol It was temporarily removed until it can be replaced with an API-powered solution in the newer version. There's nothing wrong with your installation, its replacement is just still under development.

**Comment by SlvrEagle23** [comment]
@solucionescol I've moved this request over to our Feature Upvote page, where you can follow its progress for future updates: https://azuracast.featureupvote.com/suggestions/82891/add-import-playlists-feature-back-to-playlist-management
