### ISSUE TITLE
improvement : ability to change azuracast landing page port number

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#249]
I host my radio website on the same VPS as the azuracast docker installation. Since Azuracast is using port 80 I cannot put both of them on the same port.

Would it be possible to choose the port during the installation process (or later in the setttings) instead of using the default port 80 ?

**Comment by SlvrEagle23** [comment]
@griffon56 You actually can change your AzuraCast docker port mappings as you need to, by making your own custom copy of the `docker-compose.yml` file with the changes you need:
https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#change-port-mappings-docker-installations

**Comment by griffon56** [comment]
Many thanks @SlvrEagle23 this is even very good documented
