### ISSUE TITLE
I have a error

### ISSUE THREAD

**Issue by JoschiTom** [AzuraCast/AzuraCast#2490]
Hello I got an error while installing, but I don't know what that means?

fatal: [localhost]: FAILED! => {"changed": true, "cmd": "opam init -a --disable-sandboxing --bare && opam switch create 4.08.0", "delta": "0:00:00.219703", "end": "2020-03-08 20:30:51.193713", "msg": "non-zero return code", "rc": 2, "start": "2020-03-08 20:30:50.974010", "stderr": "[NOTE] Make sure that ~/.bash_profile is well sourced in your ~/.bashrc.\n\n[ERROR] There already is an installed switch named 4.08.0", "stderr_lines": ["[NOTE] Make sure that ~/.bash_profile is well sourced in your ~/.bashrc.", "", "[ERROR] There already is an installed switch named 4.08.0"], "stdout": "\nUser configuration:\n  ~/.bash_profile is already up-to-date.", "stdout_lines": ["", "User configuration:", "  ~/.bash_profile is already up-to-date."]}

If someone would help me it would be great

**Comment by SlvrEagle23** [comment]
@JoschiTom This should be fixed as of the latest update.
