### ISSUE TITLE
Add option Remember this device for 30 days to Two-Factor

### ISSUE THREAD

**Issue by YosefAdPro** [AzuraCast/AzuraCast#2491]
Hi,

I think it would be nice to have the Remember this device option for Two-Factor, for familiar devices.

Thanks

**Comment by SlvrEagle23** [comment]
@YosefAdPro Hello! This is not a bad idea at all, but you should make new feature suggestions over at https://features.azuracast.com/ so we can keep GitHub cleaner for active issue tracking.
