### ISSUE TITLE
Error while update

### ISSUE THREAD

**Issue by alime50** [AzuraCast/AzuraCast#2492]
![Capture](https://user-images.githubusercontent.com/31132956/76245592-f92a4900-625d-11ea-85a9-df393d1bfc55.PNG)

Getting this error and unable to use we panel showing error 500 any fix?

**Comment by SlvrEagle23** [comment]
@alime50 Per Twitter, this migration is supposed to have a process that runs before it that deduplicates existing streamer accounts, which would allow that migration to happen without issue.

I will look into whether this migration is working correctly.

**Comment by SlvrEagle23** [comment]
@alime50 From the host computer, you can attempt running:

```
cd /var/azuracast
docker-compose run --rm --user=azuracast web bash
```

This will put you inside the `web` container, where you can then run:

```
php bin/console orm:run-dql "DELETE FROM App\Entity\StationStreamer str WHERE str.station_id = 7"
```

This should return a response like `int(x)`, indicating how many records were removed.

You can then type `exit` to go back to your main console, then run the update again:

```
./docker.sh update-self
./docker.sh update
```
