### ISSUE TITLE
How to set listeners time limit in Icecast?

### ISSUE THREAD

**Issue by hecgua** [AzuraCast/AzuraCast#2493]
Hello.-

Is there a way to set a listeners time limit in Icecast? For example, I want listeners get disconnected every 24 hours. 

If so, this time limit can be set by every mount point or this has to be the same value for all the mount  points?

Regards.-
Hecgua

**Comment by Vaalyn** [comment]
You can set a maximum duration that a listener can stay connected by adding the following to a mountpoints `Advanced Custom Frontend Configuration`:

You can change the number to the amount of seconds you want to allow people to stay connected.
```
<max-listener-duration>36000</max-listener-duration>
```

This will disconnect a listener after exceeding that duration but a lot of players like for example VLC will just happily automatically reconnect to the stream.
