### ISSUE TITLE
Unable to skip current playing song after update?

### ISSUE THREAD

**Issue by GerritS76** [AzuraCast/AzuraCast#2494]
Looks like it's impossible to skip the current playing song since the latest update.

- Using the AutoDJ (no relay etc).
- Using the Ansible one (non-docker).

Seems the GUI does connect however it doesnt look like it's sending a command to LiquidSoap

```
2020/03/10 18:51:58 [server:3] New client: 127.0.0.1.
2020/03/10 18:51:58 [server:3] Client 127.0.0.1 disconnected.
```
However it looks like it's not executed, as soon as I connect via telnet and execute; xxxxxxxxx_local_1.skip the current playing song will be skipped.

**Comment by SC2Mitch** [comment]
Having the same issues on our machine, I've tested it, it successfully hits the API, but nothing happens. 
![image](https://user-images.githubusercontent.com/29955942/76342272-40fcaf00-62f6-11ea-8508-f2f399be12d8.png)

**Comment by SC2Mitch** [comment]
I was able to replicate this on our machine, 
![image](https://user-images.githubusercontent.com/29955942/76342423-7dc8a600-62f6-11ea-96ba-37669e975e9b.png)

**Comment by GerritS76** [comment]
Seems the GUI does send out a command to LiquidSoap

```
2020/03/10 18:51:58 [server:3] New client: 127.0.0.1.
2020/03/10 18:51:58 [server:3] Client 127.0.0.1 disconnected.
```
However it looks like it's not executed, as soon as I connect via telnet and execute; nachtpiraat_local_1.skip the current playing song will be skipped.

**Comment by GerritS76** [comment]
Seems the GUI does connect however it doesnt look like it's sending a command to LiquidSoap

```
2020/03/10 18:51:58 [server:3] New client: 127.0.0.1.
2020/03/10 18:51:58 [server:3] Client 127.0.0.1 disconnected.
```
However it looks like it's not executed, as soon as I connect via telnet and execute; xxxxxxxxx_local_1.skip the current playing song will be skipped.

**Comment by SlvrEagle23** [comment]
@GerritS76 @SC2Mitch This should be fixed as of the latest update.
