### ISSUE TITLE
Visual Cue Editor - load audio file only when using the editor

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#2496]
I was playing around with the new Visual Cue Editor and noticed that when opening the modal for editing a file the audio file for the cue editor will directly be requested from the server. I think this is a bit early to load the audio file as this data is only needed when actually using the Visual Cue Editor and is otherwise just needlessly loaded data.

When using a wired connection this is not really much of an issue but on mobile or metered connections this could be a problem. This could possibly also be an issue for stations with rather big files like podcasts, audiobooks or something like that.

**Comment by SlvrEagle23** [comment]
@Vaalyn it appears the fix for this one was easy enough, just mark the tabs as lazy-loading so they won't initialize until they're selected.
