### ISSUE TITLE
Skip function bug

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2498]
**Using Docker installation method**
 Yes
**Host Operating System**
Ubuntu 18.04

v0.9.8.1, #1346fa3 (2020-03-11 2:58)

**Describe the bug**
There is a bug in the "skip" function - it does not skip to the next song (Playing Next) as expected but to other song from the playlist

**Comment by SlvrEagle23** [comment]
@eranwo This is a known issue we've had for quite a while unfortunately. I'll continue to look into ways to resolve it, but it isn't a new issue as of the latest few updates.
