### ISSUE TITLE
Playlist scheduling not working

### ISSUE THREAD

**Issue by mattosem** [AzuraCast/AzuraCast#250]
Hi!
I have two playlists. One from 11AM to 11PM and another one from 11PM to 11AM.
I've created a third playlist, a "once per x minutes" for a jingle, but it doesn't play.
What can I check?

**Comment by bzzrd** [comment]
Hello,

I experience the same behavior in the following conditions:

I have a default playlist, several scheduled playlist for different moments of the day and a playlist with jingles playing every 30 minutes
when running the default playlist jingles are correclty queued every 30 minutes, but when any other playlist than the default is playing Azuracast stop adding jingles to the queue.

![lufffm](https://user-images.githubusercontent.com/16000863/31652357-1c0ad43a-b31f-11e7-908e-d672e9b87afa.jpg)

Cheers !

**Comment by bzzrd** [comment]
@mattosem as a workaround I've switched position of the song selector code in app/models/Repository/StationMediaRepository.php by putting the "once per x minutes" and "once per x songs" on top of the time block selector. it seems to work alright and doesn't seem to break anything but I can't test it enough to submit a pull request for now.

Cheers.

**Comment by mattosem** [comment]
@bzzrd thank you! I'll give it a try!

**Comment by SlvrEagle23** [comment]
@bzzrd Good catch on where to find the relevant code. Always relieving to know someone else understands my codebase. :P

@mattosem No need to update the code manually; I just committed an update that makes the changes specified by @bzzrd, prioritizing the "once per x" playlists to play on their regular cues even when scheduled playlists are running underneath them. This is much more likely to be intuitive to people's expectations in any case, so it's a good change to make.

**Comment by mattosem** [comment]
Thank you so much!
