### ISSUE TITLE
specific radio port edition (8002,8004,8008,8009)

### ISSUE THREAD

**Issue by fast97** [AzuraCast/AzuraCast#2501]
**Using Docker installation method**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

hello I would like to know how used for example the port 8002 or 8009 for stations because it will be years that I have radios which use these ports. your help will be invaluable to me.

**Comment by SlvrEagle23** [comment]
@fast97 You can specify custom ports that stations can run on by editing their profiles, but be aware that we don't officially support using ports that are different from our auto-assigned ones (8000, 8010, 8020, etc) and some features like our web proxy won't work correctly out of the box and will require advanced modifications to get them working.

**Comment by fast97** [comment]
if it requires advanced modifications of the proxi and it works i am ok because on 17 radios that i have there are only 3 which are on 8xx0 ports.
thank you for your precious help

**Comment by ogrenci01** [comment]
@fast97 

You should edit file "00-azuracast" in directory "/etc/nginx/sites-available". Customize nginx configuration file for web proxy to work properly.

**find:** location ~ ^/radio/(8[0-4][0-9]0)(/?)(.*)$ {

**replace:** location ~ ^/radio/(8[0-4][0-9][0-9])(/?)(.*)$ {

I use a configuration similar to yours. I use ansible installation. It is 9998, 9996, 9994, 9992, etc. for stream and 5940, 5938, 5936, 5934, etc. for dj port. I have not any problem.

**Comment by fast97** [comment]
thanks ... what linux you used i have ubuntu 18 there is no nginx folder in etc? Thank you for your help

**Comment by ogrenci01** [comment]
@fast97 

I have Ansible installation on Ubuntu 16.04 LTS. I don't know how to do this for Docker setup. You should edit your nginx configuration file according to my message above and web proxy will work fine.

**WARNING: This is never recommended for any installation.**

**Comment by fast97** [comment]
ok i will install ubuntu 16 and redo an Ansible install to see if it works thanks.

**Comment by ogrenci01** [comment]
@fast97 

Before doing this, would you try to access this directory with console over SSH?

WARNING: This is never recommended for any installation.

**Comment by fast97** [comment]
I tried everything this directory is not in the server will need to install nginx?

**Comment by ogrenci01** [comment]
@fast97 

Azuracast installation already includes nginx and all necessary applications. Azuracast prepares for you in installation. Please wait for the response of an expert to find out answer to how it is done for Docker.

**Comment by fast97** [comment]
https://www.azuracast.com/install/ansible.html#installing 
I follow this link for ansible installation but he wants to install docker ... which method or link for ansible installation?

**Comment by ogrenci01** [comment]
@fast97 

When the installation starts, please answer no to the docker installation question. Ansible installation is not supported. We strongly recommend installing Docker.

**Comment by ogrenci01** [comment]
@fast97 

I found out how to do it!

Follow me:

1-) Go to the directory with SSH: **/var/azuracast**

2-) Run on SSH: **docker cp azuracast_web:/etc/nginx/conf.d/azuracast.conf /var/azuracast/azuracast-nginx.conf**

3-) Edit file "**azuracast-nginx.conf**" in directory "**/var/azuracast**".

3.a-) find: **location ~ ^/radio/(8[0-9][0-9]0)(/?)(.*)$ {**

3.b-) replace: **location ~ ^/radio/(8[0-9][0-9][0-9])(/?)(.*)$ {**

and save it.

4-) Run on SSH: **nano docker-compose.override.yml**

5-) Add on SSH: 

```
version: '2.2'

services:
  stations:
    ports:
      - "8000-8999:8000-8999"

version: '2.2'

services:
  web:
    volumes:
     - /var/azuracast/azuracast-nginx.conf:/etc/nginx/conf.d/azuracast.conf:ro
```

and save it.

6-) **docker-compose down**

7-) **docker-compose up -d**

It is working now :)

**Comment by fast97** [comment]
hello thank you for the answer i will test this immediately and make you a return here

**Comment by fast97** [comment]
Huge ..... super it works very well ... thank you very much .... question after an update it will move? will it be necessary to redo the manipulation?

**Comment by ogrenci01** [comment]
@fast97 

No. It is not necessary.

References:

1-) https://www.azuracast.com/help/docker/#expand-the-docker-radio-station-port-range

2-) https://www.azuracast.com/extending/modifying_docker.html#common-examples

**Comment by fast97** [comment]
Thanks for the info I have a problem radios without auto dj for direct encoding does not work on the ports ending with 2,4,6,8 I had to make an error?

**Comment by ogrenci01** [comment]
@fast97 

I know that. I have tried many scenarios. I have tested. Not working. It works flawlessly for live broadcasting, but broadcasters with auto dj can't connect. I don't know how to do this. It works by changing the values ​​here and restarting everything. Other scenarios did not work.

1-) Go to the directory: **/var/azuracast**
2-) Edit: **docker-compose.yml** rows: **87 to 233**

**Comment by fast97** [comment]
ok I made a mistake by executing "iptables -P INPUT DROP" and suddenly more access to ssh or ftp nothing works the site by functioning account.
I come back to you to tell you if it worked with your minipulation.

**Comment by fast97** [comment]
so I don't know what happened but I no longer have the azuracast site the start-up script this goes well everything is green but no site

**Comment by fast97** [comment]
Probleme ?

Proxy classes generated to "/var/azuracast/www_tmp/proxies"

Reload System Data
------------------


In CompiledContainer.php line 227:
                                                                           
  php_network_getaddresses: getaddrinfo failed: Name or service not known  
                                                                           

azuracast:setup [--update] [--load-fixtures] [--release]

2020/03/19 16:15:50 Command exited with error: exit status 1
^CERROR: Aborting.

**Comment by fast97** [comment]
I was forced to reinstall. I did not understand for the manipulation how to do it?

1-) Allez dans le répertoire: / var / azuracast
2-) Edit: docker-compose.yml rangées: 87 à 233

**Comment by fast97** [comment]
all works a little better thanks for the help.

**Comment by ogrenci01** [comment]
@fast97 

I spent all my day looking for a solution. I have installed a server many times. I try all the scenarios one by one. Now I can't install Docker normally. This is very interesting. I'm looking for a solution.

**Comment by fast97** [comment]
hello me too spend time finding a solution.  I am still searching .  thanks also for the helping hand

**Comment by fast97** [comment]
thanks also for the helping hand

**Comment by gunsar** [comment]
> @fast97
> 
> I found out how to do it!
> 
> Follow me:
> 
> 1-) Go to the directory with SSH: **/var/azuracast**
> 
> 2-) Run on SSH: **docker cp azuracast_web:/etc/nginx/conf.d/azuracast.conf /var/azuracast/azuracast-nginx.conf**
> 
> 3-) Edit file "**azuracast-nginx.conf**" in directory "**/var/azuracast**".
> 
> 3.a-) find: **location ~ ^/radio/(8[0-9][0-9]0)(/?)(.*)$ {**
> 
> 3.b-) replace: **location ~ ^/radio/(8[0-9][0-9][0-9])(/?)(.*)$ {**
> 
> and save it.
> 
> 4-) Run on SSH: **nano docker-compose.override.yml**
> 
> 5-) Add on SSH:
> 
> ```
> version: '2.2'
> 
> services:
>   stations:
>     ports:
>       - "8000-8999:8000-8999"
> 
> version: '2.2'
> 
> services:
>   web:
>     volumes:
>      - /var/azuracast/azuracast-nginx.conf:/etc/nginx/conf.d/azuracast.conf:ro
> ```
> 
> and save it.
> 
> 6-) **docker-compose down**
> 
> 7-) **docker-compose up -d**
> 
> It is working now :)

I tried to change the station port: 8142, it got an error of 502 nginx

**Comment by tanotar** [comment]
@gunsar @ogrenci01 I found the new solution to work on HTTPS ports :D. Search in ssh  find  / -name "azuracast.conf.tmpl". 
And replace location ~ ^/radio/([0-9][0-9][0-9][0-9])(/?)(.*)$ {  
 I use that configuration since it covers 100% of all ports
