### ISSUE TITLE
Shoutcast2 Multi-Mountpoint doesnt work

### ISSUE THREAD

**Issue by PB-SF** [AzuraCast/AzuraCast#2502]
Hey there,

I have a test server with Azuracast. There I tried to create a setup with 4 mount points (/stream1 .. 4) on Shoutcast2.

There is the problem that Liquidsoap tries to connect all 4 mount points to the first point (/stream1).

Error in the shoutcast log:
`ERROR [SRC 127.0.0.1:50520 sid = 1] SHOUTcast 1 source rejected. A source is already connected.`

The Azuracast code in Liquidsoap is currently (for /stream2):
`output.icecast (% mp3 (samplerate = 44100, stereo = true, bitrate = 96, id3v2 = true), id = "local_2", host = "127.0.0.1", port = 8000, password = "***** ", mount =" / stream2 ", name =" Name ", description =" Desc ", genre =" Pop ", url =" https://foo-bar.com ", public = false, encoding =" UTF- 8 ", protocol =" icy ", radio)`

So far I have been using Liquidsoap without Azuracast. I used the following working code there:
```
output.icecast (% mp3 (samplerate = 44100, internal_quality = 0, id3v2 = true, bitrate = 96),
id = "stream2",
host = "localhost",
port = 8000,
icy_id = 2,
icy_metadata = "true",
password = "*****: # 2",
name = "name",
url = "https://foo-bar.com",
genre = "Pop", radio)
```

The important difference to Icecast is that the code for Shoutcast2 does not have a `mount` in connection code.

`icy_id` is used for this and the password with the SID Number (Shoutcast Mountpoint) uses:
`hackme:#2`

Maybe you can change it accordingly so that a multi-mountpoint stream is also possible with Shoutcast?

Thank you very much

P.S. Is there someone from the German-speaking world at the developers of Azuracast?

**Comment by Vaalyn** [comment]
Thank you for including the correct options that need to be set.
If I see that correctly the `icy_id` seems to be different from the value of `id`, should this be the AzuraCast id of the mountpoint or is this something else?

I'm from Germany btw. but we communicate in english on the public support channels so I'm only writing in english here.

### For documentation:

These [lines](https://github.com/AzuraCast/AzuraCast/blob/master/src/Radio/Backend/Liquidsoap.php#L1086-L1090) would need to be changed to fix this.

To check if Shoutcast is used a call to `$mount->getAutodjShoutcastMode()` can be used.

**Comment by PB-SF** [comment]
Hi Vaalyn,

Thank you for the fast answer. I am happy to help if possible.

SHOUTcast uses so-called SIDs (StreamIDs) and streampaths (e.g. /stream1) as mount points. These are specified in the `.conf` of the SHOUTcast.

The `icy_id` in Liquidsoap is then simultaneous to the SID of the SHOUTcast server.

Since the streamid is already written in Azuracast's SHOUTcast `.conf`, I think the number(s) should be available. SHOUTcast Conf looks like:
```
streamid_1 = 1
streampath_1 = /stream1
streamid_2 = 2
streampath_2 = /stream2
...
```

I have been working with Multi-Mountpoint SHOUTcast servers for many years. If I can help further, I would be happy to.

P.S. I only asked for German developers because my English is sometimes a bit rusty :p But everything works very well.

Greetings PB-SF
