### ISSUE TITLE
IP Geolocation DB-IP

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#2503]
Please add IP Geolocation feature by DB-IP to Ansible installation.

**Comment by stardevelop** [comment]
By default, there is not Geolocation service and I should install MaxMind which requires a license.
I'd like to use DB-IP service.

**Comment by SlvrEagle23** [comment]
@stardevelop This should be working in the latest update. Try updating your Ansible installation and let me know how it works; we don't have as many opportunities for testing out our Ansible features, so you may run into issues; just copy/paste any error messages over to us.
