### ISSUE TITLE
When broadcasting, metadata still showing last autodj status

### ISSUE THREAD

**Issue by panospet** [AzuraCast/AzuraCast#2506]
Hello guys,
I'm pretty new to the AzuraCast environment, so thank you in advance for your patience, in case I'm missing something here.

**Using Docker installation method**
Yes, by using the [DigitalOcean 1-click auto-deploy droplet](https://marketplace.digitalocean.com/apps/azuracast), running AzuraCast version 0.9.8.1

**Host Operating System**
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

**Describe the bug**
I can successfully connect to Icecast service and broadcast regularly, by using either the WebDj feature of AzuraCast or a custom broadcasting tool, e.g. [Butt](https://danielnoethen.de/butt/). When I don't broadcast, there is music playing via the "AutoDJ Service", using a playlist with uploaded .mp3 files.

Possible bug: when broadcasting (via WebDj or other Icecast software) the song metadata at the web radio page, are stuck at the last status they were before the boadcast started, which are, the metadata of the last song of AutoDJ. Even if I update metadata manually and get the success message "metadata updated!", they are not.

**To Reproduce**

1. Start to play songs from a playlist via the "AutoDJ" feature.
2. Go to WebDj page, login and play a song there 
3. Notice that metadata is stuck to their previous values.
4. Update metadata manually via the WebDj page, and notice that you get the "metadata updated" status message.
5. Go again to 3 :) 

**Expected behavior**
Metadata should be updated accordingly.

**Relevant Logs**
I wasn't able to notice any relevant logs via the `docker-compose logs` command. The only thing that seems "abnormal", is this (I'm not really confident that this is related to my problem though)
```
web_1       | Setup not complete; halting synchronized task.Setup not complete; halting synchronized task.Setup not complete; halting synchronized task.Setup not complete; halting synchronized task.Setup not complete; halting synchronized task.Mar 14 11:03:01 2266e4dcd0b9 CRON[7463]: (root) CMD (       /usr/local/bin/cron_task azuracast_cli sync:run nowplaying)
web_1       | Mar 14 11:03:01 2266e4dcd0b9 CRON[7465]: (root) CMD (       /usr/local/bin/cron_task azuracast_cli sync:run short)
web_1       | Mar 14 11:03:01 2266e4dcd0b9 CRON[7468]: (root) CMD (       sleep 30; /usr/local/bin/cron_task azuracast_cli sync:run nowplaying)
web_1       | Mar 14 11:03:01 2266e4dcd0b9 CRON[7466]: (root) CMD (       sleep 15; /usr/local/bin/cron_task azuracast_cli sync:run nowplaying)
web_1       | Mar 14 11:03:01 2266e4dcd0b9 CRON[7471]: (root) CMD (       sleep 45; /usr/local/bin/cron_task azuracast_cli sync:run nowplaying)
web_1       | [2020-03-14T11:03:02.467835+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
```

**Screenshots**
All three screenshots are taken at the same time.
![Live radio web page](https://i.imgur.com/M2WiI8b.png)
![azura  cast backend](https://i.imgur.com/lDeXA5i.png)
![webdj is streaming](https://i.imgur.com/SsbCv8z.png)

- Am I doing something wrong? Misconfiguration or something?
- Is anyone else having the same problem?
Thank you in advance.

**Comment by Vaalyn** [comment]
I think there went something wrong while installing AzuraCast.
This error message is generated because the setup is not marked as completed:
```
web_1       | Setup not complete; halting synchronized task
```

Try visiting `your-ac-domain/setup` and see if it wants you to complete any steps, please complete those steps then. Make sure to not skip the last one where you confirm settings.

**Comment by panospet** [comment]
wow, I was expecting that to be so simple. Thanks a lot!
