### ISSUE TITLE
Audio keeps fading in and out - DJ on air

### ISSUE THREAD

**Issue by kaneipod** [AzuraCast/AzuraCast#2507]
Hi,

We are having an issue when a dj is on air. Every so often the audio would fade out to dead air for a few seconds then fade back in. It works fine when its just auto dj.

We are hosting with Digital Ocean using Docker.

Here is the Logs:

> 
2020/03/14 16:32:51 [cross_7748:3] Analysis: -84.233647dB / -20.094526dB (2.98s / 2.98s)
2020/03/14 16:32:51 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:32:51 [lang:3] AzuraCast Feedback Response: OK
2020/03/14 16:34:05 [lang:3] Authenticating DJ: kane
2020/03/14 16:34:05 [lang:3] AzuraCast DJ Auth Response: true
2020/03/14 16:34:05 [decoder:3] Method "MAD" accepted "audio/mpeg".
2020/03/14 16:34:05 [lang:3] DJ Source connected! [("Upgrade", "websocket"), ("Connection", "Upgrade"), ("Host", "stations:8005"), ("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"), ("Accept", "*/*"), ("Accept-Language", "en-GB,en;q=0.5"), ("Accept-Encoding", "gzip, deflate, br"), ("Sec-WebSocket-Version", "13"), ("Origin", "https://live.madnessfm.com"), ("Sec-WebSocket-Protocol", "webcast"), ("Sec-WebSocket-Extensions", "permessage-deflate"), ("Sec-WebSocket-Key", "l2RXH1FkN6JcRa6UFUHNEQ=="), ("Cookie", "azura_session=8f7ec74f20cca7e123a0c2882a42271f"), ("Pragma", "no-cache"), ("Cache-Control", "no-cache")]
2020/03/14 16:34:05 [madness_fm_live_switch:3] Switch to madness_fm_live_fallback with transition.
2020/03/14 16:34:05 [lang:3] AzuraCast Live Connected Response: received
2020/03/14 16:34:05 [madness_fm_input_streamer:3] Decoding...
2020/03/14 16:34:05 [madness_fm_live_fallback:3] Switch to blank_7739.
2020/03/14 16:34:05 [cross_7748:3] Analysis: -8.534780dB / -infdB (2.96s / 2.96s)
2020/03/14 16:34:05 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:34:06 [madness_fm_input_streamer:3] New metadata chunk P!nk -- Can We Pretend (feat. Cash Cash).
2020/03/14 16:34:08 [cross_7748:3] Analysis: -infdB / -infdB (1.04s / 1.04s)
2020/03/14 16:34:08 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:34:09 [cross_7748:3] Analysis: -infdB / -infdB (0.96s / 0.96s)
2020/03/14 16:34:09 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:34:10 [cross_7748:3] Analysis: -infdB / -infdB (1.04s / 1.04s)
2020/03/14 16:34:10 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:34:11 [madness_fm_live_fallback:3] Switch to audio_to_stereo_7736 with transition.
2020/03/14 16:34:11 [cross_7748:3] Analysis: -infdB / -infdB (0.04s / 0.04s)
2020/03/14 16:34:11 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:37:43 [madness_fm_live_fallback:3] Switch to blank_7739 with forgetful transition.
2020/03/14 16:37:43 [dummy:3] Source failed (no more tracks) stopping output...
2020/03/14 16:37:43 [cross_7748:3] Analysis: -6.287180dB / -infdB (2.99s / 2.89s)
2020/03/14 16:37:43 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:37:46 [cross_7748:3] Analysis: -infdB / -infdB (1.97s / 2.00s)
2020/03/14 16:37:46 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:37:48 [cross_7748:3] Analysis: -nandB / -infdB (0.00s / 0.01s)
2020/03/14 16:37:48 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:37:48 [cross_7748:3] Analysis: -infdB / -infdB (1.96s / 1.96s)
2020/03/14 16:37:48 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:37:50 [madness_fm_live_fallback:3] Switch to audio_to_stereo_7736 with transition.
2020/03/14 16:37:50 [cross_7748:3] Analysis: -infdB / -6.708516dB (0.04s / 0.04s)
2020/03/14 16:37:50 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:37:50 [madness_fm_input_streamer:3] New metadata chunk Sigrid  -- Don’t Feel Like Crying (Lyric Video).
2020/03/14 16:37:59 [madness_fm_live_fallback:3] Switch to blank_7739 with forgetful transition.
2020/03/14 16:37:59 [dummy:3] Source failed (no more tracks) stopping output...
2020/03/14 16:37:59 [cross_7748:3] Analysis: -12.725653dB / -infdB (2.98s / 1.98s)
2020/03/14 16:37:59 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:38:02 [cross_7748:3] Analysis: -infdB / -infdB (1.98s / 2.00s)
2020/03/14 16:38:02 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:38:04 [cross_7748:3] Analysis: -nandB / -infdB (0.00s / 0.02s)
2020/03/14 16:38:04 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:38:04 [cross_7748:3] Analysis: -infdB / -infdB (1.96s / 1.96s)
2020/03/14 16:38:04 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:38:06 [cross_7748:3] Analysis: -infdB / -infdB (0.04s / 0.04s)
2020/03/14 16:38:06 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:38:06 [cross_7748:3] Analysis: -infdB / -infdB (1.96s / 1.96s)
2020/03/14 16:38:06 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:38:08 [madness_fm_live_fallback:3] Switch to audio_to_stereo_7736 with transition.
2020/03/14 16:38:08 [cross_7748:3] Analysis: -infdB / -17.200348dB (0.04s / 0.04s)
2020/03/14 16:38:08 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:38:11 [madness_fm_live_fallback:3] Switch to blank_7739 with forgetful transition.
2020/03/14 16:38:11 [dummy:3] Source failed (no more tracks) stopping output...
2020/03/14 16:38:11 [cross_7748:3] Analysis: -11.544750dB / -infdB (3.00s / 1.96s)
2020/03/14 16:38:11 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:38:14 [cross_7748:3] Analysis: -infdB / -infdB (1.96s / 2.00s)
2020/03/14 16:38:14 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:38:16 [cross_7748:3] Analysis: -nandB / -infdB (0.00s / 0.00s)
2020/03/14 16:38:16 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:38:16 [cross_7748:3] Analysis: -infdB / -infdB (1.96s / 1.96s)
2020/03/14 16:38:16 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:38:18 [madness_fm_live_fallback:3] Switch to audio_to_stereo_7736 with transition.
2020/03/14 16:38:18 [cross_7748:3] Analysis: -infdB / -14.382244dB (0.04s / 0.04s)
2020/03/14 16:38:18 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:40:29 [madness_fm_input_streamer:3] New metadata chunk Black Eyed Peas -- Where Is the Love.
2020/03/14 16:42:19 [madness_fm_live_fallback:3] Switch to blank_7739 with forgetful transition.
2020/03/14 16:42:19 [dummy:3] Source failed (no more tracks) stopping output...
2020/03/14 16:42:19 [cross_7748:3] Analysis: -17.502982dB / -infdB (2.98s / 1.98s)
2020/03/14 16:42:19 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:42:22 [cross_7748:3] Analysis: -infdB / -infdB (1.98s / 2.00s)
2020/03/14 16:42:22 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:42:24 [cross_7748:3] Analysis: -nandB / -infdB (0.00s / 0.02s)
2020/03/14 16:42:24 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:42:24 [cross_7748:3] Analysis: -infdB / -infdB (1.96s / 1.96s)
2020/03/14 16:42:24 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:42:26 [cross_7748:3] Analysis: -infdB / -infdB (0.04s / 0.04s)
2020/03/14 16:42:26 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:42:26 [cross_7748:3] Analysis: -infdB / -infdB (1.96s / 1.96s)
2020/03/14 16:42:26 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:42:28 [cross_7748:3] Analysis: -infdB / -infdB (0.04s / 0.04s)
2020/03/14 16:42:28 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:42:28 [cross_7748:3] Analysis: -infdB / -infdB (1.96s / 1.96s)
2020/03/14 16:42:28 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/14 16:42:30 [madness_fm_live_fallback:3] Switch to audio_to_stereo_7736 with transition.
2020/03/14 16:42:30 [cross_7748:3] Analysis: -infdB / -18.675030dB (0.04s / 0.04s)
2020/03/14 16:42:30 [crossfade:3] Simple transition: crossed, fade-in, fade-out.

**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu
Using Shoutcast + Auto DJ

**Comment by hecgua** [comment]
Hello.-

Try this: If the issue is with Live Dj, go to your Station Profile>Edit Profile>AutoDj>Crossfade Duration (Seconds) and lower the value to 1 or 2 seconds.

**Comment by SlvrEagle23** [comment]
@kaneipod More often than not, this is caused by your connection buffer being too low. Try setting the buffer to a higher value (you can set it in your station's profile, under "AutoDJ").

**Comment by kaneipod** [comment]
> 
> 
> Hello.-
> 
> Try this: If the issue is with Live Dj, go to your Station Profile>Edit Profile>AutoDj>Crossfade Duration (Seconds) and lower the value to 1 or 2 seconds.



> 
> 
> @kaneipod More often than not, this is caused by your connection buffer being too low. Try setting the buffer to a higher value (you can set it in your station's profile, under "AutoDJ").


While i was waiting for a reply i decieded to redeploy the server as im using Digital Occean, Which seams to have fixed the issue for now. but i will keep the comments in mind if it happens again. Thank you both. @SlvrEagle23 @hecgua
