### ISSUE TITLE
Listener countries

### ISSUE THREAD

**Issue by KoneSV** [AzuraCast/AzuraCast#2508]
Could you make a graph of the Listener countries with the same data from GeoLite 2?

**Comment by aniphreak** [comment]
i would like to see this feature as well.
or at least a country flag beside the ip address is a faster solution.

**Comment by SlvrEagle23** [comment]
@KoneSV @aniphreak Hello! Would you mind submitting this as a new feature request over at https://features.azuracast.com/ ? We use that system to track feature requests to keep our GitHub reserved strictly for bugs.

**Comment by KoneSV** [comment]
It is not a bug, I made the topic so that we all help each other to create that just like the footer, line, etc ... using the same GeoLite2 data, to create a listener by country
