### ISSUE TITLE
AutoPlay code on AzuraCast embedded player

### ISSUE THREAD

**Issue by aniphreak** [AzuraCast/AzuraCast#2509]
We would like the embedded player to have an 
optional AutoPlay feature on the code. I have seen lots of modern html5 icecast/shoucast players and its working as promoted in year 2020 browsers.

Best example is the [Muses player](https://www.muses.org/) that is working using AzuraCast itself.

**Comment by Vaalyn** [comment]
AzuraCast once had the option to add autoplay to the player but we removed this feature as browsers have began to block autoplaying audio around 2 years ago. For reference you can read [this](https://github.com/AzuraCast/AzuraCast/issues/1355) AzurCast issue from back then. You can also find a small JS snippet there with which you can get autoplay back for browsers that don't block this.

More about the "browsers blocking autoplay" thing can be found on the Google blog post about those changes: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

Short list of changes (copied from [here](https://stackoverflow.com/a/50490453/3292313)):
```
As of April 2018, Chrome's autoplay policies changed:

"Chrome's autoplay policies are simple:

- Muted autoplay is always allowed.
- Autoplay with sound is allowed if:
    - User has interacted with the domain (click, tap, etc.).
    - On desktop, the user's Media Engagement Index threshold has been crossed, meaning the user has previously play video with sound.
    - On mobile, the user has added the site to his or her home screen.
```
