### ISSUE TITLE
Upgrade Icecast-kh when using Docker

### ISSUE THREAD

**Issue by andrew867** [AzuraCast/AzuraCast#251]
Is it possible to upgrade Icecast-kh to the master GitHub branch when using AzuraCast through Docker?

**Comment by SlvrEagle23** [comment]
@andrew867 You can always build your own copy of the docker image; the dockerfile and supporting files are located in this repo: https://github.com/AzuraCast/docker-azuracast-stations

Out of curiosity, though...is there some new feature the master branch of KH has that you're looking for in particular? It might behoove us to upgrade the actual dockerfile for everyone.

**Comment by andrew867** [comment]
The latest KH7 fixes an iOS11 stream issue (HTTP range request that wasn’t being ignored). I’ve observed it myself and KH7 fixes the issue. 

https://github.com/karlheyes/icecast-kh/issues/172
https://github.com/AzuraCast/AzuraCast/issues/240

**Comment by andrew867** [comment]
It’d be awesome to have the official docker image updated as I lack the time and knowledge to do it myself. I’ve just straight up installed Icecast-KH7 on a Debian box for now.

**Comment by SlvrEagle23** [comment]
@andrew867 I've updated both the Docker file and the traditional installation to use IceCast-KH7, as my local tests showed no issues with it compared to KH5.

The Docker registry's build server will be popping out a new Docker image in about 20 minutes (it's a little slow), at which point you can run `docker-update.sh` and pull down the new image complete with KH7.

**Comment by andrew867** [comment]
Awesome, thanks so much!

**Comment by andrew867** [comment]
@SlvrEagle23 Looks like it's built, I'll test it out tonight :)

https://hub.docker.com/r/azuracast/azuracast_stations/builds/br4jue7ogluym9vgfmi7cu5/

**Comment by andrew867** [comment]
@SlvrEagle23 Looks like everything is working as expected, thanks again!

**Comment by smilingpeanut** [comment]
@SlvrEagle23 I just updated our installation (traditional rather than Docker), and I'm still seeing KH5. Is there something I need to do other than running the `update.sh` script?

**Comment by SlvrEagle23** [comment]
@smilingpeanut You may need to run `./update.sh --full` to cause the Icecast to rebuild, as I haven't yet flagged it as a required update for traditional install cases.

**Comment by smilingpeanut** [comment]
@SlvrEagle23 Will that erase any settings for our existing installation?

**Comment by SlvrEagle23** [comment]
@smilingpeanut All the `--full` flag does is execute a update of all requisite components of AzuraCast (i.e. nginx, php, mariadb, the radio station software, etc), rather than just what is flagged as required by the difference between your most recent update and the current one.

It won't result in any data loss (at least, it _shouldn't_ ), and is often recommended in the event that an update fails for some reason, but always make sure your music files are redundantly stored elsewhere just as a good practice.

**Comment by smilingpeanut** [comment]
@SlvrEagle23 Cool. I just want to make sure it doesn't wipe out the database. Thanks!

**Comment by smilingpeanut** [comment]
@SlvrEagle23 Ran `./update.sh --full` and the version of Icecast-KH that's installed is still `2.4.0-kh5`. I verified this from the Icecast status page and via the changelog located at `/var/azuracast/servers/icecast2/NEWS`. Any thoughts?
