### ISSUE TITLE
Streamer Password in Debug Logs breaks UI Box and reveals password hash

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2511]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu Linux 18.04.4
**Describe the bug**
Within the Audit Logs, whenever you view a field where a user has created a streamer account, the hashed password appears to break the UI, and it now reveals the Argon hash? Unknown if that's intended or not, unsure if it poses a security risk. 
**To Reproduce**
Make a streamer account, add a password on it.
Go to Debug Logs
View the streamer log, view issue
**Expected behavior**
Don't extend over the box, or just delete the field completely if it poses a possible risk. 
**Relevant Logs**
none
**Screenshots**
![image](https://user-images.githubusercontent.com/29955942/76694673-b0173200-666d-11ea-99ce-b94a57cc4051.png)

**Device(s):**
win 10, chrome, latest, desktop. 
**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch Should be fixed now.
