### ISSUE TITLE
Ansible update error

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#2512]
During update with Ansible, I get the following error (All in Red) and admin dashboard becomes inaccessible:

TASK [azuracast-setup : Run AzuraCast Setup (Update Mode)] *************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/console azuracast:setup --update", "delta": "0:0              0:00.639920", "end": "2020-03-15 07:49:42.295948", "msg": "non-zero return code", "rc": 1, "start": "2020-03-15 07:49:41.656028", "s              tderr": "\nIn AbstractMySQLDriver.php line 93:\n                                                                              \n  An               exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused  \n                                                                                            \n\nIn PDOConnection.php line 31:\n                                             \n  SQLSTATE[HY000] [2002] Con              nection refused  \n                                             \n\nIn PDOConnection.php line 27:\n                                                           \n  SQLSTATE[HY000] [2002] Connection refused  \n                                             \n\nazuracast:setup [--upd              ate] [--load-fixtures] [--release]", "stderr_lines": ["", "In AbstractMySQLDriver.php line 93:", "                                                                                            ", "  An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused  ", "                                                                                            ", "", "In PDOConnection.php line 31:", "                                                           ", "  SQLSTATE[HY000] [2002] Connection refused  ", "                                             ", "              ", "In PDOConnection.php line 27:", "                                             ", "  SQLSTATE[HY000] [2002] Connection refused  "              , "                                             ", "", "azuracast:setup [--update] [--load-fixtures] [--release]"], "stdout": "\nAzu              raCast Setup\n===============\n\nWelcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...\n * Enviro              nment: Production\n * Installation Method: Ansible\n\n ! [NOTE] Running in update mode.                                                             \n\nMigrating Legacy Configuration\n------------------------------\n\nConfiguration already set up.\n\nSetting Up InfluxDB\n------              -------------\n\nDatabase created.\nRetention policies updated.\nContinuous queries created.\nInfluxDB databases created.\n\nRunning               Database Migrations\n---------------------------", "stdout_lines": ["", "AzuraCast Setup", "===============", "", "Welcome to Azura              Cast. Please wait while some key dependencies of AzuraCast are set up...", " * Environment: Production", " * Installation Method: An              sible", "", " ! [NOTE] Running in update mode.                                               ", "", "Migrating Legacy Configuration"              , "------------------------------", "", "Configuration already set up.", "", "Setting Up InfluxDB", "-------------------", "", "Data              base created.", "Retention policies updated.", "Continuous queries created.", "InfluxDB databases created.", "", "Running Database M              igrations", "---------------------------"]}

**Comment by ogrenci01** [comment]
@SlvrEagle23 

I have the same problem right now. I'm using Ansible. Azuracast gives 500 error. Can you help me?

**Comment by SlvrEagle23** [comment]
@ogrenci01 Are you seeing the exact same error message with your update script as is listed above? Attempting to update again may remedy the issue; if not, you can create a new GitHub issue with the specific details of your problem.
