### ISSUE TITLE
No title display if hidestats=all set in SHOUTcast

### ISSUE THREAD

**Issue by PB-SF** [AzuraCast/AzuraCast#2515]
Similar to Icecast, the SHOUTcast2 DNAS server also has the option of hiding the server's website so that unauthorized persons cannot access sensitive data `hidestats=all`

If this option is set, Azuracast no longer shows artist/title. The display then shows Stream Offline.

I think the SHOUTcast API in Azuracast is addressed without or with the standard `password` of the server?

Depending on which URL is used for the query with SHOUTcast, the API should work again if this is done with the `adminpassword`.

I use the "Page7" of the SHOUTcast with XML output.
`http://url:port/admin.cgi?sid=1&mode=viewxml&page=7&pass=ADMINPASSWORT`

Maybe I just missed a suitable function in Azuracast?

Thanks and best regards.

**Comment by Vaalyn** [comment]
I've looked into this and found that the [azuracast/nowplaying](https://github.com/AzuraCast/nowplaying) library which interacts with the stream server APIs has a method to set the admin password and that this password is set by AzuraCast when using the library. In the library though the Shoutcast2 adapter is currently not using the password when building the query to the API. The IceCast adapter is using a password if it's set so this should be a rather simple fix.

I've created an [issue](https://github.com/AzuraCast/nowplaying/issues/7) on the libraries repository and will look into it later.

For documentation:

- The admin password for the Shoutcast nowplaying is already set in the [frontend adapter](https://github.com/AzuraCast/AzuraCast/blob/81fbf023b0dc67c3ae0d4ad2b3672b85c40f06aa/src/Radio/Frontend/SHOUTcast.php#L59)
- The [azuracast/nowplaying](https://github.com/AzuraCast/nowplaying) library is currently not making use of the password [here](https://github.com/AzuraCast/nowplaying/blob/master/src/Adapter/SHOUTcast2.php#L14)
- In the IceCast adapter if a password is set it is used [here](https://github.com/AzuraCast/nowplaying/blob/master/src/Adapter/Icecast.php#L25)

**Comment by PB-SF** [comment]
Hey there, 
is there any news about this?

Greetings

**Comment by SlvrEagle23** [comment]
@PB-SF If we have any updates, we will update this thread accordingly.

SHOUTcast isn't a high priority for our development, as it is proprietary, closed-source (and, at this point, freemium) software that we have little ability to inspect or repair. We don't ship SHOUTcast by default with our installations and don't recommend it in a majority of cases.

**Comment by SlvrEagle23** [comment]
@PB-SF we have added support for using the authenticated `/admin.cgi` SHOUTcast 2 DNAS endpoint for now-playing data if the administrator password is provided in the latest update.
