### ISSUE TITLE
Ban IP address

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#2519]
Advanced Banned IP Addresses feature does not work as it should.
Although, I ban an IP address and restart the station but still the IP is listening to the stream.

**Comment by stardevelop** [comment]
I need to stop some streamrippers that use Winamp plugin to rip.

**Comment by YosefAdPro** [comment]
I think it's the same as

https://github.com/AzuraCast/AzuraCast/issues/2467

**Comment by SlvrEagle23** [comment]
Closing as a likely duplicate of #2467.
