### ISSUE TITLE
Problem Media Manager

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#252]
The pages do not open after the last update. 😣
![2017-10-18 11_42_21](https://user-images.githubusercontent.com/379099/31711758-716cc57a-b3f9-11e7-887f-a6b71104c2c5.gif)

**Comment by SlvrEagle23** [comment]
@ckeurk Wow, my mistake there. Accidentally omitted one too many lines in the previous fix. Should be resolved now.
