### ISSUE TITLE
Update stream metadata upon editing song on admin page

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#2522]
When a song is updated on the admin page (e.g., artist name), it seems that the info is not updated in the stream. At least the display won't change on the Icecast admin page and I see no `updinfo` entry in the Icecast log. Is it intended? 

This is not a problem for our frontend because it's polling AC's API but external applications (internet radio devices, mobil apps etc.) are fetching the info from the stream and they won't learn about the changes. Does it make sense? 

We're running AC v0.9.8.

Thanks,

Peter

**Comment by SlvrEagle23** [comment]
@gammaw So you're saying even when Liquidsoap is updating its metadata, it's not sending it down the stream to Icecast?

That's interesting...haven't seen that one before as an issue. Wondering if it has something to do with the encoding set on the station profile.

**Comment by gammaw** [comment]
@SlvrEagle23 it seems to me, but I might be wrong, that when a song is playing and its metadata is changed via the admin page of Azuracast (e.g., the name of the artist), the change is not propagated to Liquidsoap and Icecast. You can check the behavior by opening the admin page of Icecast and/or opening the Icecast log while a song is playing: change the song's name in Azuracast, save it, and there will be no change on Icecast's admin page and there will be no update request in the Icecast log. The update will take effect in the Azuracast API though. Does it make sense? 

Speaking of encoding. We have an issue now with an internet radio app (called Receiver Radio) which fails to displays song metadata if the song name or the artist name contain special characters (e.g., ä). Do you think the ISO setting might fix this?

**Comment by SlvrEagle23** [comment]
@gammaw Wait, do you mean you edit the metadata of the file _while it's playing_? That will always be cached data, there's no way to modify that once it's "in-flight" so to speak.

**Comment by gammaw** [comment]
@SlvrEagle23 I see. Since the on-the-fly change takes effect on the Azuracast API (and so our frontend sees the change) I expected that the effect is visible in the stream too. Wouldn't it be possible to issue an `updinfo` HTTP request for Icecast for the change to take effect there too?

**Comment by SlvrEagle23** [comment]
@gammaw Possibly, but it's a very edge-case thing...I'd rather just implement a "globally give station admins the ability to set metadata for the stream directly from the web" thing.

**Comment by gammaw** [comment]
@SlvrEagle23 That's a good idea. 

By the way, for live streams the metadata change takes effect on-the-fly as the client (e.g., Butt) directly changes the stream metadata. I think at least.
