### ISSUE TITLE
Ubuntu 18.04: Error in install.sh

### ISSUE THREAD

**Issue by Jdbye** [AzuraCast/AzuraCast#2528]
**Using Docker installation method**

No

**Host Operating System**

Ubuntu 18.04

**Describe the bug**

It errors in the middle of installation.

**To Reproduce**

1. Mirror the git to a local directory
2. Run install.sh
3. Enter password

**Expected behavior**

Expected behavior is for it to work as according to the instructiions that I followed.

**Relevant Logs**

Error in install.sh:
TASK [azuracast-radio : Add OPAM/OCaml Repository] ******************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "apt-key adv --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 630F626C9FD811EBC19DF0955B2D0C5561707B09", "msg": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: keyserver receive failed: No keyserver available", "rc": 2, "stderr": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: keyserver receive failed: No keyserver available\n", "stderr_lines": ["Warning: apt-key output should not be parsed (stdout is not a terminal)", "gpg: keyserver receive failed: No keyserver available"], "stdout": "Executing: /tmp/apt-key-gpghome.PYUWNzbTxS/gpg.1.sh --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 630F626C9FD811EBC19DF0955B2D0C5561707B09\n", "stdout_lines": ["Executing: /tmp/apt-key-gpghome.PYUWNzbTxS/gpg.1.sh --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 630F626C9FD811EBC19DF0955B2D0C5561707B09"]}

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@Jdbye This is not an error we've seen before, and it is likely to do with the connection between your server and Ubuntu's servers, and not AzuraCast itself in particular.

We strongly recommend using the Docker installation method to avoid needing to go through the process of installing the constituent components one by one.
