### ISSUE TITLE
Installing on Rasberry Pi 2

### ISSUE THREAD

**Issue by aldorr** [AzuraCast/AzuraCast#253]
Hi, I was wondering if someone has had any success installing on a RasPi 2?
After a fresh install of Ubuntu 16.04 LTS, and going through the steps for installation (as root) as described on the main page, it installs and updates, and everything seems to be going fine.
But then after "`TASK [nginx : Run apt-get install -f]`", there is a fatal error.
It gets a "`non-zero return code`" and then proceeds to try to uninstall dependencies that were just installed for nginx.
I'm assuming that the process is a little different for the Raspberry Pi, but I can't find any other info about it.
If I try to install nginx (and specifically nginx-extras) manually with apt-get, then it says all the dependencies are amd64 architecture. That can't be right. Is there not an armhf version?
Thanks for your help.

**Comment by aldorr** [comment]
It seems that the Raspberry Pi 2 is not supported. But does anyone know if there is any way I can get it to install. Or does it just not make sense to use this hardware for AzuraCast?

**Comment by SlvrEagle23** [comment]
@aldorr The traditional install method should work with a Raspberry Pi 3 or above (though I haven't tested it too recently), but currently the RPi2 and below aren't supported, as the full stack of AzuraCast software isn't expected to perform well on that grade of hardware.

**Comment by aldorr** [comment]
@SlvrEagle23 Thanks for the answer. Then I guess we'll have to get a RPi3 and start over. 👍
