### ISSUE TITLE
Different listeners count due Icecast 2 restreams

### ISSUE THREAD

**Issue by yarik2720** [AzuraCast/AzuraCast#2531]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 16.04

**Describe the bug**
I found that Azuracast ignores in counting listeners and listeners reports clients with useragent `Icecast`, that can be from external server.
for example I can see on icecast2 admin panel this clients:
```
109.254.xxx.xxx | 85368 | Icecast 2.3.3
2a05:dfc7:8:2:xxxx:xxxx:xxxx:xxxx | 85365 | Icecast 2.4.2
```
but can't see on listeners reports any with Icecast useragent or this IP's

**Expected behavior**
Wanted to see the same listeners value and listeners list as on icecast2 page

**Comment by SlvrEagle23** [comment]
@yarik2720 We don't include listeners with the "Icecast" user-agent as those are broadcast software relaying your signal to another location; even our own AzuraRelay uses the same user-agent.
