### ISSUE TITLE
Disabled playlists still continue to play, despite being disabled. 

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2533]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu 18.4
**Describe the bug**
When a Playlist is disabled (Playlist One) and Playlist Two is enabled, Azura won't recognize Playlist One has been disabled without a restart, nor does it prompt a restart. In some cases, it doesn't even play songs from Playlist Two 

**To Reproduce**
Disable Playlist One
Enable Playlist Two
Watch the Now Playing tab
Watch as it doesn't play Playlist Two songs, only playlist one. 
**Expected behavior**
Playlist One songs to be disabled and Playlist Two songs to only play. 
**Relevant Logs**
Debug Log, but that's not clear why this is occurring
![image](https://puu.sh/Fmdrl/604b317b45.png)
**Screenshots**
![image](https://user-images.githubusercontent.com/29955942/77019463-7ea5ab80-6978-11ea-81b8-179d5e1d049c.png)

Belly Dance is disabled, yet with the 'skip song' it continues to play Belly Dance playlists.
![image](https://puu.sh/Fmdpa/8f3dd80f2b.png)
**Device(s):**
win10, chrome, latest, desktop. 
**Additional context**

**Comment by SC2Mitch** [comment]
![image](https://user-images.githubusercontent.com/29955942/77019463-7ea5ab80-6978-11ea-81b8-179d5e1d049c.png)

Belly Dance is disabled, yet with the 'skip song' it continues to play Belly Dance playlists.
![image](https://puu.sh/Fmdpa/8f3dd80f2b.png)

**Comment by Vaalyn** [comment]
In general you'll have to restart Liquidsoap in order for the new playlist configuration to be written to disk and for Liquidsoap to pick it up. We currently have no way of reloading the configuration while LS is running.

I think this might be an issue with the [`StationRequiresRestart`](https://github.com/AzuraCast/AzuraCast/blob/8e08b7b798070c0c720ce10e0c56624bd29ed48f/src/Doctrine/Event/StationRequiresRestart.php) Doctrine EventSubscriber. The subscriber should listen to all `flush` operations from Doctrine (the ORM we use) to listen for changes that need the station to be restarted. On properties of our entities we can chose to ignore them for this via a `@AuditLog\AuditIgnore` annotation which is not set on the `$is_enabled` property of StationPlaylists so a change to this property should trigger a restart notification.

**Comment by SlvrEagle23** [comment]
This is a known and intentional functionality: if "Manual AutoDJ mode" is turned off, we don't flag playlist changes as needing a restart, because the AzuraCast AutoDJ _doesn't_ need a system restart to apply playlist changes.

The only reason this was still noticeable when skipping songs is because Liquidsoap had a known issue where it skipped out of the AzuraCast AutoDJ's queue for a single song when skipping songs; I've made some changes to how this skip-song functionality works that should fix this issue.
