### ISSUE TITLE
3rd party radio app fails to display some special characters

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#2538]
We'd like to provide our listeners with a list of apps and Internet radio devices that can be used to listen to our radio so that they have a more convenient way for it than going to our website. We're now testing a popular app called Receiver Radio and it looks good in general. Well, almost. We discovered that for certain special characters in the song title or in the artist name, e.g., é and ä, the app will fail to display the song (nothing will be displayed instead). Strangely, it works well for a bunch of special characters, e.g., á or ü (the examples I'm mentioning are Hungarian or German characters). 

I checked the Icecast settings in the Liquidsoap config, it's a UTF-8 encoding there. When I tried to change it to "ISO-8859-1" (via `encoding="ISO-8859-1"` in the `output.icecast` line) Azuracast started to show strange characters. I know that Azuracast is polling the `stats` HTTP interface of Icecast and probably this encoding caused a confusion in Azuracast. 

Any other idea? Maybe some adjustment in the Icecast settings which won't disturb Azuracast either?

**Comment by SlvrEagle23** [comment]
@gammaw I'm not sure that there's a solution to this that both allows us to properly retrieve data from Icecast while avoiding issues with players that can't handle UTF-8 characters.
