### ISSUE TITLE
playlist.once + playlist.merge

### ISSUE THREAD

**Issue by pavlos2** [AzuraCast/AzuraCast#2539]
Hi,

At Edit Playlist and under AutoDJ Scheduling Options one can select both playlist.once + playlist.merge. Is this valid? The Liquidsoap configuration file shows only the playlist.once function when both features are selected.

**Comment by pavlos2** [comment]
Thanks Buster

**Comment by SlvrEagle23** [comment]
@pavlos2 I'm actually not sure how to fix this problem other than to make the `playlist.once` and `playlist.merge` options mutually exclusive via a radio button. You can't use both functions on a single playlist, so that's about the only way we could work around the issue.

**Comment by pavlos2** [comment]
@SlvrEagle23 Thanks for the response. Indeed, both functions cannot be used on a single playlist. So users can get confused, I fully support your approach to make those options mutually exclusive via a radio button. I also posted this as an operational enhancement  https://features.azuracast.com/suggestions/84536/playlist-types-autodj-scheduling-options

Thanks for the support and keep on this GREAT project!

**Comment by SlvrEagle23** [comment]
@pavlos2 Bumping the suggestion over on FeatureUpvote to "Planned" status as these are all correct observations about the interactions between these settings, and at some point I want to get them all fixed in some manner in the playlist editor.

**Comment by pavlos2** [comment]
Thanks a lot Buster!
