### ISSUE TITLE
Fixed an error with hash

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#254]
Sorry, but the display always, even after several updates.
![capture](https://user-images.githubusercontent.com/379099/31776623-57fd2866-b4ec-11e7-860a-bb06bbf16d4f.png)

**Comment by SlvrEagle23** [comment]
@ckeurk If you're pulling now-playing information directly from Shoutcast/Icecast, this will now appear as part of the now playing information. If you use the AzuraCast now playing API, this will not appear.

Unfortunately, this is a necessary side effect of both Icecast and Shoutcast having significant trouble conveying song titles that use UTF-8 characters. Both are frequently shown to mangle the data, producing characters that don't make sense at all.

AzuraCast's solution to this is to generate, from the original UTF-8, a unique song identifier hash, and then pass that along to Shoutcast/Icecast. When AzuraCast checks the now-playing data, regardless of how messed up the rest of the string got, the hash will be at the end of it, which it can then use to match the song back up with the proper one in its own database, and then return that information in its full UTF-8 glory.

Admittedly, this will look a little weird to anyone listening in VLC or some other client that pulls nowplaying info directly from the MP3 stream, but to my knowledge there's no other way of ensuring full international UTF-8 compliance in both the radio software and Liquidsoap.

**Comment by SlvrEagle23** [comment]
@ckeurk Disregard the previous message; after further investigation into the issues preventing Icecast and Shoutcast from properly showing UTF-8, other workarounds have been found that resolve the issue without needing to append the song ID directly to the song titles.

**Comment by ckeurk** [comment]
Thank you very much :)
