### ISSUE TITLE
Error response from daemon: Error processing tar file(exit status 1): write /tmp/cli_backup.zip: no space left on device

### ISSUE THREAD

**Issue by liloue4** [AzuraCast/AzuraCast#2542]
hello everyone, i have a problem with azuracast i have my backup and i need to restore and when i restore
   five minutes later, I have this message: Error response from the daemon: Error processing the tar file (quit status 1): write /tmp/cli_backup.zip: more space on the device
i don't understand i have 2TO disk space 

sorry my english is not good

**Comment by liloue4** [comment]
i have test to restore exclude media and put all media file to the good folder and i have a white page when i go to my url , so i have test to type ./docker.sh update and i have this :

<img src="https://heberge-images.com/images/2020/03/21/12.png" alt="12.png" border="0" />

**Comment by liloue4** [comment]
i see for me is a broken backup or other ??? my backup is creat to the admin interface.. so  because i have test one other backup and is fully work , the good question is why my olds backup is work and my all other backup recently is not work .? thanks all for answer

**Comment by SlvrEagle23** [comment]
@liloue4 It sounds like you're running into a resource limitation on your server that may not be related to your total available disk space. You may also have partitions set up on the host computer such that the Docker volumes (which are usually in `/var/`) are running out of space on that partition even though the rest of the hard drive has ample space.

**Comment by liloue4** [comment]
hi SlvrEagle23 thanks for your answer , in var i have 4% used and my backup work use (9GO) and is:  AzuraCast • v0.9.9, #b4ab445 (2020-03-21 2:54) • Docker • PHP 7.4  
and backup not work is ;  AzuraCast • v0.9.9, #6f7cf4d (2020-03-17 8:21) • Docker • PHP 7.4
(#6f7cf4d)

you see #6f7cf4d and #b4ab445 ?
