### ISSUE TITLE
CSS files of the embed player

### ISSUE THREAD

**Issue by Octavelscx** [AzuraCast/AzuraCast#2543]
Hi, I'm sorry to post here but I don't really know where can I get help.

I use the embedded player on external server and I want to modify the CSS of the embedded player but I don't know how I can get the CSS files.

I know the embed player code is at server/public/station_name/embed but I can't access this via FTP, I emulated a FTP server to go through Docker install and access to config, media, playlists...directories but I can't find embed files. 

Maybe I don't use the correct method but I read that is not recommended to overwrite CSS of <iframe> in html so I would like to modify it directly on the server...

Thank's in advance and sorry for my English, I'm french.

**Comment by Vaalyn** [comment]
You can add custom CSS for the player (and all other public pages) via the `Administration` -> `Custom Branding` -> `Custom CSS for Public Pages` field.

**Comment by Octavelscx** [comment]
I tried, didn't work for the embed player, that's why I'm posting here

**Comment by Octavelscx** [comment]
Ok sorry it works, I didn't know why it didn't
