### ISSUE TITLE
From Webhook to Mysql Database

### ISSUE THREAD

**Issue by techbloglinux** [AzuraCast/AzuraCast#2544]
Hi, i have a question. How can i create an webhook it's insert the current song in a mysql database?

Sorry for my bad english.

**Comment by SlvrEagle23** [comment]
@techbloglinux That would be up to you to set up on your end. You can create a small PHP script that connects to your MySQL database and inserts the record it receives from AzuraCast's dispatched webhook.

**Comment by techbloglinux** [comment]
I would be create on the database my own history. How I get the informations from the webhook.

**Comment by Vaalyn** [comment]
You create the PHP script somewhere on a web server and put the URL of the script in the `Web Hook URL` field when creating the webhook. In your script you should get the contents of the POST body, for example `$webhookJson = file_get_contents('php://input')`.

**Comment by techbloglinux** [comment]
I'm testing not working with database insert

Here the code: [https://pastebin.com/R7MLGnDM](https://pastebin.com/R7MLGnDM)
Here the screenshot from the database.

![Auswahl_005](https://user-images.githubusercontent.com/62470074/77257013-fffb8780-6c71-11ea-871d-2e39698a1436.png)
