### ISSUE TITLE
Timeout after 40s waiting on dependencies to become available: [tcp://mariadb:3306 tcp://influxdb:8086]

### ISSUE THREAD

**Issue by suricloud** [AzuraCast/AzuraCast#2545]
Hi,
On fresh debian 10  i get this issue when installing azurast.
How to fix this?

2020/03/21 15:57:39 Waiting for: tcp://mariadb:3306
2020/03/21 15:57:39 Waiting for: tcp://influxdb:8086
2020/03/21 15:57:39 Connected to tcp://influxdb:8086
2020/03/21 15:57:39 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:40 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:41 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:42 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:43 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:44 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:45 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:46 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:47 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:48 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:49 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:50 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:51 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:52 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:53 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:54 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:55 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:56 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:57 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:58 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:57:59 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:00 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:01 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:02 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:03 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:04 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:05 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:06 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:07 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:08 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:09 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:10 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:11 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:12 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:13 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:14 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:15 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:16 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:17 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:18 Problem with dial: dial tcp 172.18.0.2:3306: connect: connection refused. Sleeping 1s
2020/03/21 15:58:19 Timeout after 40s waiting on dependencies to become available: [tcp://mariadb:3306 tcp://influxdb:8086]

**Comment by Vaalyn** [comment]
You can increase the timeout temporarily by creating a `docker-compose.override.yml` with the following content:
```
version: '2.2'

services:
    web:
        entrypoint:
            - dockerize
            - -wait
            - tcp://mariadb:3306
            - -wait
            - tcp://influxdb:8086
            - -timeout
            - 60s
        command: ["/usr/local/bin/my_init"]
```

You can also increase the timeout value even further if it still times out. In general it shouldn't take that long to startup all the components but this should help you get it installed.

Would you mind sharing what hardware you are installing AzuraCast on?

**Comment by davy39** [comment]
Hi,
I'm trying to install Azuracast in a Nethserver (Centos7) sever. I get a similar problem no matter how long I wait :

```
web_1       | 2020/04/21 08:50:16 Problem with dial: dial tcp 172.17.0.3:8086: connect: connection refused. Sleeping 1s
web_1       | 2020/04/21 08:50:16 Problem with dial: dial tcp 172.17.0.4:3306: connect: connection refused. Sleeping 1s
```
Here are [Mariadb & Influxdb logs](https://gist.githubusercontent.com/davy39/1847fd2afeb5660695007733929e6032/raw/2cdad3387ffb19562552f9c4ed699354ce5e8487/azuracast.log), can someone tell me what's going wrong ?
Thanks
