### ISSUE TITLE
change listening link

### ISSUE THREAD

**Issue by fast97** [AzuraCast/AzuraCast#2546]
hello I have another problem, all radio referencing was http: ip: 8000 and azuracat requires https:// ip/radio/8000/radio.mp3 . how to modify this listening link?
Thank you

**Comment by hecgua** [comment]
Hello fast97.-

From your Profile page got to Mount Points>Actions>Edit>Mount Point URL and there you can edit your mount point name. For example: /stream , /listen, /radio.mp3, /autodj.mp3 or /whatever. The result will be http://ip/8000/yournewmountpointname

Regards.-

**Comment by fast97** [comment]
this is not the result http://IP/radio/port/point I am looking for but http://IP: port/point. I advance a little on my research. thank you

**Comment by hecgua** [comment]
The result in your profile will be like http://IP/radio/port/point?123456789 but you can use http://IP: port/point. It's like a reduced link. It will work for many players and web pages.  Test the reduced link with some players like Winamp, VLC or Media Classic Player.

**Comment by fast97** [comment]
it works in reduced link in https with icecast and not shoutcast. is there a solution to it?

**Comment by SlvrEagle23** [comment]
@fast97 We don't support SSL via SHOUTcast as this was only ever added as a "Freemium" feature in the latest version, which we don't support.

**Comment by hecgua** [comment]
You can use one system for every radio station, Icecast or Shoutcast. You can't use both systems in the same profile for one station. If you want to have the two systems for one station, you can do a Relay Account (new profile) with differents systems on each one.

**Comment by fast97** [comment]
ok thank you for these details
