### ISSUE TITLE
Wider support for mobile media player display (navigator.mediaSession)

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#2547]
I just discovered a nice feature of the Azuracast player that it updates song metadata for mobile media players. I was testing it on various mobile devices, it seemed to work well on Android with Chrome but no luck on iPhone (tried with Safari and Chrome). 

I found the corresponding code:

https://github.com/AzuraCast/AzuraCast/blob/b4ab44580db7607608db1e948cfe4dd58aaa02b5/frontend/vue/RadioPlayer.vue#L483-L492

and found this (see compatibility): https://developer.mozilla.org/en-US/docs/Web/API/Navigator/mediaSession

Apparently, the feature is not supported by iOS. Is there a way to extend this nice feature for iOS devices too?

**Comment by SlvrEagle23** [comment]
@gammaw Not really sure that there's much we _can_ do to supply this same kind of metadata with browsers that don't support it via the mediaSession API. Would be happy to review any pull requests to that effect if anyone discovers ways to accomplish this.

**Comment by gammaw** [comment]
@SlvrEagle23 thanks. I see. Well, at the moment we plan to add a [rather trivial workaround](https://github.com/mmmnmnm/lahmacun/commit/9f0ec113957eb7dfc1f0bc08eee4300006783b86) where we update the document title, which the iPhone media players seem to be reading. Obviously, the mediaSession solution is much more sophisticated. Plus, we would encourage our mobile listeners to listen via apps (see this related issue https://github.com/AzuraCast/AzuraCast/issues/2538) also because they have better control there. 

Another related issue is that re-play doesn't seem to be working via the mobile media player after a playing stream has been stopped. To reproduce: 1) on mobile start stream on public player, 2) lock the screen of the mobile device, 3) pause the player, 4) play won't start the stream. Can you confirm this behavior?

**Comment by Vaalyn** [comment]
@SlvrEagle23 @gammaw I've found out how you can do this correctly for Safari. If you set/update the `title` attribute of an `audio` tag the iPhone will display that in the lockscreen and audio controls. This will not look completely native since it will display the artist and title in one line but it's better than nothing I think.

**Comment by gammaw** [comment]
Thanks @Vaalyn! We'll check it out.
