### ISSUE TITLE
Can't enable HTTPS with LetsEncrypt

### ISSUE THREAD

**Issue by hecgua** [AzuraCast/AzuraCast#2548]
Hello.-

I tried to enable the HTTPS with the Azuracast's LetsEncrypt service but can't do it.

I want to know if this is a problem with Ubuntu, my host server or it is an Azuracast issue.

Any help will be much appreciated. Thanks in advance.-

FYI: I have no coding experience nor am I a computer technician. I have only been the owner of some online radios for many years and, after having struggled with countless streaming providers and streaming systems, I became to know Azuracast and to have my own dedicated Ubuntu server.

**Using Docker installation method**
Yes 

**Host Operating System**
Ubuntu 16.04

**Describe the bug**
Can't enable HTTPS with LetsEncrypt for my server domain.

**To Reproduce**
1. Connect to my host server via SSH
2. cd /var/azuracast
3. ./docker.sh letsencrypt-create mydomain.example.com (mydomain.example.com was replaced with my own domain)
4. error

**Expected behavior**
Enable HTTPS with Azuracast's LetsEncrypt for my domain and my listeners.

**Relevant Logs**
```
root@s357:~# cd /var/azuracast
root@s357:/var/azuracast# ./docker.sh letsencrypt-create mydomain.example.com (mydomain.example.com was replaced with my own domain)
The following error was encountered:
[Errno 13] Permission denied: '/var/log/letsencrypt/letsencrypt.log'
Either run as root, or set --config-dir, --work-dir, and --logs-dir to writeable paths.
Domain name mydomain.example.com is not set up with LetsEncrypt yet. Reverting to self-signed cert...
Can't load /var/azuracast/.rnd into RNG
139812978917824:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/var/azuracast/.rnd
Generating a RSA private key
..............................+++++
..................+++++
writing new private key to '/etc/letsencrypt/selfsigned.key'
-----
Self-signed certificate restored.
root@s357:/var/azuracast#
```

**Device(s):**
 - Device: Desktop
 - OS: W10
 - Browser: Chrome
 - Version: 80

**Comment by Seathre** [comment]
I have also encountered this issue with a docker installation, on an Ubuntu 18.04 machine. Happy to provide whatever information I can to help resolve.

**Comment by hecgua** [comment]
I was thinking to upgrade Ubuntu to 18.04 but now I see upgrading Ubuntu wiil not solve the issue.

**Comment by hecgua** [comment]
@Seathre I have reported the issue twice to my server provider and they can't find a solution. Have you had any progress with your problem?

**Comment by hecgua** [comment]
Issue solved by my server provider.
