### ISSUE TITLE
Azuracast serves local lan content instead of FQDN/public content

### ISSUE THREAD

**Issue by aujawindar** [AzuraCast/AzuraCast#2549]
**Using Docker installation method**
Yes

**Host Operating System**
Debian Buster

**Describe the bug**
My Azuracast machine is a laptop with a local IP. Its connection to the internet is reverse proxied by another PC on the LAN, and is reachable to the public. The connections are SSL via Let's encrypt.
However, portions of the content is served from the local IP, and is thus not available to the public. Among the local content is: 
- The actual radio stream, whether served from the web DJ or from another machine running butt. Example: http://192.168.X.X/radio/8000/radio.mp3?1584825227 
- Other local files. Example: Example: http://192.168.X.X/static/img/generic_song.jpg

**To Reproduce**
1. Go to the radio site from an IP outside the LAN
2. The page loads, except the mentioned portions. That means I can't serve radio outside the LAN.

**Expected behavior**
I would expect the pages to be served in full, or not at all. I don't expect this mix of locally and publicly available content.
Azuracast works well on the LAN.

**Relevant Logs**
I have logs available, but I don't see any relevant error messages in them.

**Device(s):**
Tried on several browsers on Linux and Windows from the public-facing side. 

**Additional info**
The Azuracast box sits on its own subdomain. The proxying machine sits on the main domain, and has its own services running, hence the proxying. This machine has the SSL sertificates, so I have not attempted to create certificates on the Azuracast box. As portions of the content are available publicly, I think I can rule out that SSL, domains or routing are the problem.

**Comment by aujawindar** [comment]
[azuralogs.txt](https://github.com/AzuraCast/AzuraCast/files/4364271/azuralogs.txt)

Full logs attached.

**Comment by aujawindar** [comment]
Additional info: I have not set up Let's encrypt on the Azuracast box, as it's done on the reverse proxy machine, which already runs its own services. The Azuracast box works on a subdomain, hence the proxying.

**Comment by aujawindar** [comment]
The problem might be that nginx is redirecting (307 temporary).

**Comment by SlvrEagle23** [comment]
@aujawindar If you have a reverse proxy in front of AzuraCast itself, it can't automatically detect this, so your best option is to disable the "Prefer Browser URL" setting in the system-wide settings, then make sure the "Base URL" in that same settings page is properly set to the public-facing WAN URL.

That should fix things.

**Comment by aujawindar** [comment]
@SlvrEagle23 Thank you. The base URL has always been set to the fully qualified domain name, but I have now disabled the "prefer browser URL" checkbox. 
Also, enabling "Always use HTTPS" has created problems, I assume because Azuracast only has self-certified HTTPS and so redirects to the local IP. Not having all content served by HTTPS might be problematic, because most browsers now warn against mixed content (and some will not display it), Also, the main domain forces HTTPS.

Thanks to the disabling of "prefer browser URL", it is now possible to listen from the public side. However, there are other strange effects to this: I can upload songs, create playlists, but not add songs to playlists and hence not play them out either. I have seen error messages about port 8004 (Liquidsoap telnet) that might have to do with it.
