### ISSUE TITLE
Custom branding

### ISSUE THREAD

**Issue by wilz7** [AzuraCast/AzuraCast#255]
Hi mate
Just a quick question. Do you allow to custom branding of the theme and name "azuracast " to anything else?

**Comment by SlvrEagle23** [comment]
@wilz7 I don't mind modifying the header, provided the footer attribution isn't removed as well. Given the asking price, I think the little bit of promotional credit from the footer is a fair compromise. :)

**Comment by wilz7** [comment]
sound good mate thank you
