### ISSUE TITLE
Messed up with the Custom Branding

### ISSUE THREAD

**Issue by aniphreak** [AzuraCast/AzuraCast#2551]
I was playing on how the site will look, accidentally hid something and now i cant access the custom branding page. I cant even go to the backup page to go restore because i accidentally add hidden on a certain element.

Is there an alternative to alter or reset those fields, or at least download the backup through ftp?

**Comment by SC2Mitch** [comment]
You can deploy a backup through a SSH client, putty works fine

**Comment by SlvrEagle23** [comment]
@aniphreak You can reset your internal custom CSS by running, on the host computer:

```bash
cd /var/azuracast
./docker.sh cli azuracast:settings:set custom_css_internal null
```

**Comment by aniphreak** [comment]
@SlvrEagle23  it works. thank you, your a lifeserver!

@SC2Mitch hard to access docker contents though ssh alone. I hope the newly-made SFTP accesses also contents the azuracast directory itself, not only the media files, so we can also grab the backup files in the server.
