### ISSUE TITLE
Stop AutoDJ for Several Live Broadcasts

### ISSUE THREAD

**Issue by Kulcanhez** [AzuraCast/AzuraCast#2552]
**Using Docker installation method**
Yes.

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
Hello Team. First of all, really thank you for all the time and love that you put on this project. Really appreciated!
At the moment we have a small project that's expanding. Once in a while, we have live broadcasts.

These broadcasts are composed by the following:
 - One person connects to the server and starts talking and then disconnects
 - The DJ connects to the server to play the music and at the end, he disconnects 
 - The same person connects to the server to start talking again

The problem here is that every time they disconnect the server the auto DJ comes and is not a good experience for the listener to hear these bumps.

I tried to stop the auto DJ but doing so I can't connect to the server. I tried to disable the playlists but doing so I need to restart the auto DJ, it worked but then the system creates another empty playlist automatically.

What's the best way to accomplish this? I already searched a lot on the issues here on Github but couldn't find it.

**Comment by SlvrEagle23** [comment]
@Kulcanhez Hello and thank you for the kind words!

Right now, I'm not aware of a simple way to accomplish what you're looking for, which would basically be to avoid fading to a few seconds of the AutoDJ's song between DJs broadcasting. You could introduce some silence after a DJ broadcast, but then even fading back to the AutoDJ would have that same period of silence in it, which probably wouldn't be particularly desirable.

**Comment by Kulcanhez** [comment]
> @Kulcanhez Hello and thank you for the kind words!
> 
> Right now, I'm not aware of a simple way to accomplish what you're looking for, which would basically be to avoid fading to a few seconds of the AutoDJ's song between DJs broadcasting. You could introduce some silence after a DJ broadcast, but then even fading back to the AutoDJ would have that same period of silence in it, which probably wouldn't be particularly desirable.

Really thank you for your fast reply! Hmmm, there's no way that I can disable auto DJ before the live and turn it on the end or almost at the end?

**Comment by SlvrEagle23** [comment]
@Kulcanhez In this case, not easily, because the AutoDJ (Liquidsoap) is in charge of managing the live connection itself. We use this setup intentionally to allow us more flexibility in authenticating live DJs and keeping track of who the live DJ is during a broadcast.

**Comment by Kulcanhez** [comment]
> @Kulcanhez In this case, not easily, because the AutoDJ (Liquidsoap) is in charge of managing the live connection itself. We use this setup intentionally to allow us more flexibility in authenticating live DJs and keeping track of who the live DJ is during a broadcast.

Hmm yes and that is well thought. So, in that case, how could I introduce a silence after a transmission as you mentioned?
