### ISSUE TITLE
Read this

### ISSUE THREAD

**Issue by 0x416c69** [AzuraCast/AzuraCast#2554]
You kids seriously need to stop using Docker or making a simple PHP project so much dependant on different stuff and drop all the old operating systems support just because you think it's the "professional way"

I am disappointed.

As a fucking programmer who has been doing it for a decade, I cannot fucking install your shit on my Ubuntu 14.04

**Comment by SC2Mitch** [comment]
Ubuntu 14.04 is in End of Life, Docker is the easiest solution for most people, as it's simple to do. 

Your hostile attitude is not needed in this Repository.

**Comment by SlvrEagle23** [comment]
@0x416c69 I am impressed and disappointed that you edited this issue from what was a simple unprofessional and impolite complaint to a profanity-laden mini-tirade. Why you would _edit an issue's description_ to be even more terrible is truly beyond me.

Our reasons for using Docker are well enumerated in various places across our documentation and here on GitHub. Basically it summarizes to: we are a very small team having to manage a complex interconnection of a number of dependencies (all of which are necessary to deliver the experience we offer out of the box) and Docker makes that a manageable task.

On even a normal day, your commentary here would violate just about every tenet of our Code of Conduct.

On a day when our very small team is scattered around various pandemic hotspots around the planet, sheltering in place and trying to protect ourselves and our loved ones (who we worry about greatly), struggling to manage basic needs like groceries and keeping bills and rent paid, while weathering the constant societal anxiety we're all suffering through with no end in sight...only to _show up here and pour our free time and energy into a project that we do for FREE just to try to make the world an ever-so-slightly better place_...

You make it very hard to want to keep doing that.

**Comment by determin1st** [comment]
That's an OKay issue, really. Just laughted. That's about selecting a "big gun" or small, i mean a light tool wont ever have such issue because of it's low dependencies. So just move on, choice what fits better your project.
