### ISSUE TITLE
Exception when updating from Redis: "LOADING"

### ISSUE THREAD

**Issue by KulibibK** [AzuraCast/AzuraCast#2555]
Error updating
LOADING Redis is loading the dataset in memory
[Screenshot](http://freenet74.ru/errorazura.png)

**Comment by j2sdwebradio** [comment]
I have the same error

**Comment by KulibibK** [comment]
Queue error after update
[Screen](https://yadi.sk/i/EK7JhpYKmFcS6A)

**Comment by Vaalyn** [comment]
@KulibibK This looks like the error reported in #2556. Can you try clearing the metadata cache via `./docker.sh cli cache:clear`?

**Comment by KulibibK** [comment]
> @KulibibK Это похоже на сообщение об ошибке в [# 2556](https://github.com/AzuraCast/AzuraCast/issues/2556) . Можете ли вы попробовать очистить кеш метаданных через `./docker.sh cli cache:clear`?
Thanks, it helped

**Comment by bilkill** [comment]
LOADING Redis, this problem persists

**Comment by SlvrEagle23** [comment]
@bilkill I've published an update to AzuraCast that should help avoid Redis not being ready when the container spins up. In subsequent updates, hopefully this problem won't be present.

**Comment by KulibibK** [comment]
> @bilkill Я опубликовал обновление для AzuraCast, которое должно помочь избежать того, что Redis не будет готов, когда контейнер раскрутится. В последующих обновлениях, надеюсь, эта проблема не будет присутствовать.

Не могу обновиться из-за  LOADING Redis is loading the dataset in memory
