### ISSUE TITLE
Add to queue fails

### ISSUE THREAD

**Issue by bjarn** [AzuraCast/AzuraCast#2556]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu Server 18.04

**Describe the bug**
Adding a track to the queue from the admin panel throws a MySQL error.

**To Reproduce**
1. Go to media library
2. Select a track
3. Add to queue

**Expected behavior**
It should show a success message that it added the track to the queue.

**Relevant Logs**
An exception occurred while executing 'INSERT INTO station_requests (station_id, track_id, timestamp, played_at, ip) VALUES (?, ?, ?, ?, ?)' with params [1, 3849, 1584953678, 0, "IPADDRESS MASKED"]: SQLSTATE[HY000]: General error: 1364 Field 'skip_delay' doesn't have a default value

**Device(s):**
 - Device: Macbook Pro
 - OS: MacOS
 - Browser: Chrome
 - Version: 80

**Comment by SlvrEagle23** [comment]
@bjarn You may need to clear your metadata cache. Easiest way is via the CLI by running `cache:clear`.

**Comment by bjarn** [comment]
Manually added a default value as a hotfix, seems to work just fine even after undoing the hotfix and doing a cache clear.
