### ISSUE TITLE
Fallback file add azuracast

### ISSUE THREAD

**Issue by rafkos5889** [AzuraCast/AzuraCast#2558]
hello if there is a possibility to add options to the panel : The fallback file is an audio file that is played in a loop if the source stream disconnects. Note that this file must match the bit rate, sample rate, and number of channels configured for your stream. ???????
![Screenshot_7](https://user-images.githubusercontent.com/45500615/77353963-3d2f4a80-6d42-11ea-9c19-11af5b70694c.png)

**Comment by SlvrEagle23** [comment]
@rafkos5889 This is not currently supported by AzuraCast directly. You can specify a fallback for any mount point via the Mount Point editor page, but you can't directly upload a fallback file via the web interface.

If you'd like to suggest this as a new feature, you're welcome to submit it [on our FeatureUpvote page](https://features.azuracast.com/).
