### ISSUE TITLE
Icecast is not recognized as a service

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#2559]
I renamed a station name and created a new one. 
Now only one station can work at the same time and the other one is offline and when I try to restart Icecast or AutoDJ, I get the above error.

**Icecast is not recognized as a service.
It may not be registered with Supervisor yet. Restarting broadcasting may help.**

I believe it relates to a duplicate station name that has not been deleted from the platform correctly.
Updating of Azuracast did not help

**Comment by SlvrEagle23** [comment]
@stardevelop Are you trying to run both stations on the same port, or share the same port for any of the internal ports (i.e. Telnet, etc.)?

Normally we have internal controls that should protect against that, but you should always run each station on its own port range (i.e. 8000, 8010, 8020).

If you have deleted a station previously and are trying to reuse its port assignment, usually restarting the Docker containers (restarting the host server or updating will both do this) should be sufficient to fix the issue.

**Comment by stardevelop** [comment]
@SlvrEagle23 
I renamed Advanced URL Stub of StationName1 to test2 (test2 changed to test1) and then created a new station with the name of StationName2 and Advanced URL Stub test1.
I see that port range of both stations are different but only one works at the same time.

**Comment by SlvrEagle23** [comment]
@stardevelop You're using the same URL stub (short name) as another station that previously existed?

That might cause trouble, but you should be able to resolve it via `Utilities` -> `Restart Broadcasting`, which rewrites all the relevant configuration in the station directory.

**Comment by stardevelop** [comment]
The problem persisted and I had no choice but to delete both stations and re-created them.

Now, can I change the station number? 
I need to change https://s1.radio.com/station/5/ to https://s1.radio.com/station/3/

**Comment by SlvrEagle23** [comment]
@stardevelop You can't; it's automatically assigned as an auto-incrementing ID in the database. For public pages, the URL stub will be used instead.
