### ISSUE TITLE
Live function always disappears and returns

### ISSUE THREAD

**Issue by rolradio** [AzuraCast/AzuraCast#256]
Hey,
There is a problem with the live fuction in the docker version.
We've had this point before: https://github.com/AzuraCast/AzuraCast/issues/115

after the update then, it was okay.
Today I notice that the live stream is coming and falling away. then back and forth.
So there are short interruptions.

**Comment by rolradio** [comment]
You can here listen to the problem.

http://stream.shoutcastsolutions.com/public/drivers_night_club

**Comment by SlvrEagle23** [comment]
@rolradio I recently updated LiquidSoap to the latest version (1.3.3) to resolve some significant performance and stability issues; this may have caused problems with live DJing.

I will test as soon as possible and update accordingly.

**Comment by rolradio** [comment]
@SlvrEagle23 Thank you for that.
I hope you wil find the solution soon.

**Comment by rolradio** [comment]
@SlvrEagle23 Is there any solution to the live function in azuracast?
The problem looks a lot like this:  https://github.com/AzuraCast/AzuraCast/issues/115
I can not say if this problem is only in the docker version.
Previously I had the default installation.

**Comment by SlvrEagle23** [comment]
@rolradio Sorry, I haven't had enough time to test the DJ process out locally, since my local development environment doesn't lend itself well to testing that particular feature. I'm definitely aware of the issues there and will be testing and trying out some fixes ASAP.

**Comment by rolradio** [comment]
@SlvrEagle23 Hello,
Because of this problem, I did an extra installation without a docker, because I could then intervene in liquid soap. (unfortunately I do not know the docker) Here I have solved the live problem by bringing the buffer from 5 to 10.
if you could also include this in the next update of the docker version, then this problem is solved again.

Thank you 

live = audio_to_stereo(input.harbor("/", port=8005, user="shoutcast", auth=dj_auth, icy=true, max=30., **buffer=10**., icy_metadata_charset="UTF-8", metadata_charset="UTF-8", on_connect=live_connected, on_disconnect=live_disconnected))
ignore(output.dummy(live, fallible=true))
live = fallback(track_sensitive=false, [live, blank(duration=2.)])

**Comment by SlvrEagle23** [comment]
@rolradio I have updated the main Liquidsoap configuration writer for both traditional and Docker installs to increase the buffer to 10 seconds. Sorry for the delay!
