### ISSUE TITLE
Now Playing and Streamer

### ISSUE THREAD

**Issue by CouinCouin** [AzuraCast/AzuraCast#2560]
Hi, 

We are looking for a CentovaCast replacement solution to selfhost server. 
So I found and try AzuraCast on a Oracle Virtual Machine for tests. 
OS is Ubuntu 19.10 Server.
If results looks good, we plan to install it on a SSD1 OVH VPS.

As well as we have a PC with RadioDJ software to manage songs, jingles, podcasts etc etc, this PC is always live connected to the (actually Centova) server via Sound Empire Caster.
We have some podcsasts onto Centova server in case of link fail between RadioDJ PC and Centova, so to stil get music.

With Azura, we I connect the RadioDJ PC, but "Now Playing" still displaying the track that was playing with AutoDJ. Next track displays the live stream. 
It results that any player or Public Player Page of Azura, displays the last Azura track instead of live stream.

Is there a way to make streamer recognized as "Now playing" , or did I miss something ? I tried to find some infos in other threads but without success :(

Thanks a lot for your help :) 
Couin

**Comment by SlvrEagle23** [comment]
@CouinCouin This is a known issue with certain DJ software connecting to AzuraCast's DJ input (which is managed by Liquidsoap); the first metadata sent by the broadcasting client seems to be ignored, and the only update that triggers the system to detect a change in metadata (and thus detect a live broadcast) is the _second_ metadata update.

Some software automatically works around this issue by repeatedly sending metadata updates (which appears to work fine), and it also is possible to work around it by sending a metadata update immediately after establishing a connection, so the "second" song you play is just a few seconds after the connection is made.

**Comment by CouinCouin** [comment]
Hi, 
Thanks for your answer. 
Effectively, the sent tags appears when "RadioDJ" plays another track. 
I was testing with a podcast so as well as the tags was not changing, it was stuck on Azura track that was playing.
For our application, it looks se minor bug (not important if the track that RadioDJ is playing when link retablished, is not displayed), dio you know if it's planned to fix it ?  

Thanks :) 
Couin
