### ISSUE TITLE
Problems with update

### ISSUE THREAD

**Issue by ismaelazanza** [AzuraCast/AzuraCast#2563]
In my case I had problems with the most recent update, the autodj stopped working, after trying to restart the transmission, I managed to connect, but a few minutes passed and it just stopped working again, currently I returned to the old version through a backup you make.

**Comment by SlvrEagle23** [comment]
@ismaelazanza We need some more information about what's causing this issue on your installation. In particular, logs would be very helpful; you can view the Liquidsoap (the AutoDJ) logs via `Utilities` > `Log Viewer` on the station's sidebar menu.
