### ISSUE TITLE
 Azura v.0.9.9 Stream retransmission URL at the mount point does not work.

### ISSUE THREAD

**Issue by maikocosta** [AzuraCast/AzuraCast#2565]
Stream retransmission URL at the mount point is not working.
I've tried it all, but it won't.

**Comment by SlvrEagle23** [comment]
@maikocosta Please provide more details to explain the error. If possible, please include logs (visible from `Utilities` -> `Log Viewer` in the station menu, or at the global System Administration area).

**Comment by maikocosta** [comment]
Problem solved.
