### ISSUE TITLE
About Current CPU Load

### ISSUE THREAD

**Issue by CouinCouin** [AzuraCast/AzuraCast#2566]
Hi, 

A very small question. 
**_Current CPU Load_** (and **_15-Minute CPU Load Average_**) , for example 0,68 , is 0,68% of CPU , or 0,68 of 1 ( = 68%)  ? 

We plan to install Azura on a OVH SSd1 VPS. 

Thanks :)
Couin

**Comment by Vaalyn** [comment]
The `Current CPU Load` shows you the load as reported by the server in the unix [load](https://en.wikipedia.org/wiki/Load_(computing)) format.

This means that for every core/thread you have `1.0` load available without overloading the CPU so in general you can multiply the load value by 100 and divide that by your CPU core count for a percentage value.

### Single Core Example:
Load = `0.68`
CPU Cores = `1`
Load % = `68%`

### Multicore Example:
Load = `1.68`
CPU Cores = `2`
Load % = `84%`

**Comment by CouinCouin** [comment]
Hi , 

Thanks for explanation (I did not understood all the wiki page lol , sorry, I'm french ;) ).

The VM is set on 1 CPU core, set to 100% allocated ressource.
The host machine has a i7 3,4 GHz CPU. 

There was only one (me) listeners conencted to Azura, is it normal , 68% ? 

Also, I got a CPU Load over than 1 (something like 5.xx and progressivly return bat under 1) , it should not goes over 1 , normally , because of 1 core VM CPU ? 

Also, will CPU Load increase a lot with 150 or 200 listeners ? 

Thanks 
Couin

**Comment by Vaalyn** [comment]
Most of the CPU load is generated by the audio transcoding which is being done by Liquidsoap. New listeners hardly consume any additional resources apart from bandwidth.

If your CPU has 1 core and has a load of 5.xx it means that the processes running on the machine are trying to do too much work at once. You can look at the output of the [`htop`](https://wiki.ubuntuusers.de/htop/) command to see which process is generating how much load.

**Comment by CouinCouin** [comment]
Hi Dear, 

Thanks for precisions. 

I ran htop and I have 2 commands that use between 14 and 20% CPU each : 
**_/usr/local/bin/liquidsoap /var/azuracast/stations/eurodance_90/config/liquidsoap.liq_**

Sometimes I have **_php bin/console sync:run nowplaying that takes_** 100% CPU during 1 second.
Sometimes, but more spaced in time, I have some others sync (short and medium) that takes some CPU %. I think that these syncs are of Administration panel .

Can we set interval of syncs ? And disable **_Song Requests Queue_** sync ,as well as we'll never user this feature ? 

The values looks same if I have no listener or 7 listeners (unrevealant of course...  I can't simulate more on my network, not enough PC's for connecting more).
During test, no audio cuts or dropouts. 

Perhaps it's a bad measurement because of virtual machine ? 

Thanks for your help :)
Couin

**Comment by Vaalyn** [comment]
The processes with `.../liquidsoap.liq` are the audio transcoding processes. Those will make up most of your CPU usage overall. Then there are those `php bin/console sync:run xxx` processes which are doing different kinds of tasks for AzuraCast. You can see a list of all the tasks that are registered to be run by AC here: https://github.com/AzuraCast/AzuraCast/blob/master/config/services.php#L429-L453

There is no way to disable certain sync tasks at the moment and the intervals are also not changeable be the user/administrator. You can however manually trigger them via the administration page if you need to execute one of those tasks before the next regular execution.

As for your question about the `Song Requests` sync, when you do not use this feature the only thing that the sync task will do is check if any station has a request and basically does nothing for stations where no requests are found: https://github.com/AzuraCast/AzuraCast/blob/master/src/Sync/Task/RadioRequests.php#L40-L58

In most cases you'll probably run out of network bandwidth before you really notice a difference in your CPU / RAM usage when your listener count increases. I've found a `Load Test` page on the IceCast website (although I'm not sure how old that test is) which shows you a comparison between IceCast and SHOUTcast when connecting ~14k listeners: https://icecast.org/loadtest/3/

What you should keep in mind is that most VPS hosters use so called `CPU credits` which are used up when you run tasks on the CPU and they will throttle your VPS dynamically when you have no credits left. In general this happens faster on the cheaper plans than on the ones were you get more CPU cores allocated to your VPS. For most hosters this is nowhere mentioned on their web page but most hosters I know of use this to ensure that no single user is hogging all the resources all the time.

**Comment by CouinCouin** [comment]
Hi Dear, 

Thanks for explanations : )

We are so far from 14k listener on our radio, near from 150 to 200 ahah :)

**Comment by CouinCouin** [comment]
Hi :) 

We finally took an OVH SSD1 VPS for testing. 
For the moment only few listenerds because we modified the stream URL only on the website (because not yet https, I have to search how to change it before modifying relays like Tune-In etc etc), but CPU load values seems to be more coherent than on my VM. 
We are now between 0,19 and 0,45 .
