### ISSUE TITLE
Stations not running

### ISSUE THREAD

**Issue by Skyradio** [AzuraCast/AzuraCast#2568]
Hi
I have 3 different Stations put to my Azuracast instance. Now I have the problem when I start the first stream, it is running. Starting the next one, the first one stops.
It doesn`t matter which Station is starting first, I`m only able to stream only one Station.

Hope someone can help. Using the latest Docker Version.

Mike

**Comment by Skyradio** [comment]
Where can I find them?

**Comment by SC2Mitch** [comment]
Go through a PuTTY client `cd /var/azuracast` or wherever you put it, then `docker-compose logs -f` you may need to `sudo` it

**Comment by Skyradio** [comment]
n refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [] {"station":{"id":1,"name":"SKYRADIOFM"}}
web_1       | [2020-03-24T18:23:17.858580+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 401: You need to authenticate  [] {"station":{"id":1,"name":"SKYRADIOFM"}}
web_1       | [2020-03-24T18:23:18.060071+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 401: You need to authenticate  [] {"station":{"id":2,"name":"SKYRADIOFM Schlager"}}
web_1       | [2020-03-24T18:23:18.084876+00:00] AzuraCast.NOTICE: HTTP client GET call to http://stations:8020/admin/stats produced response NULL [] {"station":{"id":3,"name":"HITRADIO-LÜDENSCHEID"}}
web_1       | [2020-03-24T18:23:18.085182+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to stations port 8020: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [] {"station":{"id":3,"name":"HITRADIO-LÜDENSCHEID"}}
web_1       | [2020-03-24T18:23:18.493609+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 404:  [] {"station":{"id":3,"name":"HITRADIO-LÜDENSCHEID"}}
web_1       | [2020-03-24T18:23:32.905217+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
web_1       | [2020-03-24T18:23:33.047681+00:00] AzuraCast.NOTICE: HTTP client GET call to http://stations:8000/admin/stats produced response NULL [] {"station":{"id":1,"name":"SKYRADIOFM"}}
web_1       | [2020-03-24T18:23:33.051592+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to stations port 8000: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [] {"station":{"id":1,"name":"SKYRADIOFM"}}
web_1       | [2020-03-24T18:23:33.103850+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 401: You need to authenticate  [] {"station":{"id":1,"name":"SKYRADIOFM"}}
web_1       | [2020-03-24T18:23:33.334835+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 401: You need to authenticate  [] {"station":{"id":2,"name":"SKYRADIOFM Schlager"}}
web_1       | [2020-03-24T18:23:33.365260+00:00] AzuraCast.NOTICE: HTTP client GET call to http://stations:8020/admin/stats produced response NULL [] {"station":{"id":3,"name":"HITRADIO-LÜDENSCHEID"}}
web_1       | [2020-03-24T18:23:33.366425+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to stations port 8020: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [] {"station":{"id":3,"name":"HITRADIO-LÜDENSCHEID"}}
web_1       | [2020-03-24T18:23:33.695190+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 404:  [] {"station":{"id":3,"name":"HITRADIO-LÜDENSCHEID"}}
influxdb_1  | [httpd] 172.18.0.6 - - [24/Mar/2020:18:23:33 +0000] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.5.1 curl/7.58.0 PHP/7.4.4" 92054ba0-6dfc-11ea-94dc-000000000000 10678
web_1       | [2020-03-24T18:23:47.900251+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
web_1       | [2020-03-24T18:23:48.049449+00:00] AzuraCast.NOTICE: HTTP client GET call to http://stations:8000/admin/stats produced response NULL [] {"station":{"id":1,"name":"SKYRADIOFM"}}
web_1       | [2020-03-24T18:23:48.053677+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to stations port 8000: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [] {"station":{"id":1,"name":"SKYRADIOFM"}}
web_1       | [2020-03-24T18:23:48.097390+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 401: You need to authenticate  [] {"station":{"id":1,"name":"SKYRADIOFM"}}
web_1       | [2020-03-24T18:23:48.301839+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 401: You need to authenticate  [] {"station":{"id":2,"name":"SKYRADIOFM Schlager"}}
web_1       | [2020-03-24T18:23:48.336279+00:00] AzuraCast.NOTICE: HTTP client GET call to http://stations:8020/admin/stats produced response NULL [] {"station":{"id":3,"name":"HITRADIO-LÜDENSCHEID"}}
web_1       | [2020-03-24T18:23:48.337036+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to stations port 8020: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [] {"station":{"id":3,"name":"HITRADIO-LÜDENSCHEID"}}
web_1       | [2020-03-24T18:23:48.463593+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 404:  [] {"station":{"id":3,"name":"HITRADIO-LÜDENSCHEID"}}
influxdb_1  | [httpd] 172.18.0.6 - - [24/Mar/2020:18:23:48 +0000] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.5.1 curl/7.58.0 PHP/7.4.4" 9ad21bf3-6dfc-11ea-94dd-000000000000 3349
web_1       | [2020-03-24T18:24:03.076601+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
web_1       | [2020-03-24T18:24:03.102973+00:00] AzuraCast.INFO: Running 1-minute sync task [] []
web_1       | [2020-03-24T18:24:03.312035+00:00] AzuraCast.NOTICE: HTTP client GET call to http://stations:8000/admin/stats produced response NULL [] {"station":{"id":1,"name":"SKYRADIOFM"}}
web_1       | [2020-03-24T18:24:03.314601+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to stations port 8000: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [] {"station":{"id":1,"name":"SKYRADIOFM"}}
web_1       | [2020-03-24T18:24:03.361425+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 401: You need to authenticate  [] {"station":{"id":1,"name":"SKYRADIOFM"}}
web_1       | [2020-03-24T18:24:03.557916+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 401: You need to authenticate  [] {"station":{"id":2,"name":"SKYRADIOFM Schlager"}}
web_1       | [2020-03-24T18:24:03.582482+00:00] AzuraCast.NOTICE: HTTP client GET call to http://stations:8020/admin/stats produced response NULL [] {"station":{"id":3,"name":"HITRADIO-LÜDENSCHEID"}}
web_1       | [2020-03-24T18:24:03.582802+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to stations port 8020: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [] {"station":{"id":3,"name":"HITRADIO-LÜDENSCHEID"}}
web_1       | [2020-03-24T18:24:04.059329+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 404:  [] {"station":{"id":3,"name":"HITRADIO-LÜDENSCHEID"}}
influxdb_1  | [httpd] 172.18.0.6 - - [24/Mar/2020:18:24:04 +0000] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.5.1 curl/7.58.0 PHP/7.4.4" a41ec427-6dfc-11ea-94de-000000000000 8236
web_1       | [2020-03-24T18:24:17.260782+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
web_1       | [2020-03-24T18:24:17.339708+00:00] AzuraCast.NOTICE: HTTP client GET call to http://stations:8000/admin/stats produced response NULL [] {"station":{"id":1,"name":"SKYRADIOFM"}}
web_1       | [2020-03-24T18:24:17.340019+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to stations port 8000: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [] {"station":{"id":1,"name":"SKYRADIOFM"}}
web_1       | [2020-03-24T18:24:17.378748+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 401: You need to authenticate  [] {"station":{"id":1,"name":"SKYRADIOFM"}}
web_1       | [2020-03-24T18:24:17.576078+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 401: You need to authenticate  [] {"station":{"id":2,"name":"SKYRADIOFM Schlager"}}
web_1       | [2020-03-24T18:24:17.610168+00:00] AzuraCast.NOTICE: HTTP client GET call to http://stations:8020/admin/stats produced response NULL [] {"station":{"id":3,"name":"HITRADIO-LÜDENSCHEID"}}
web_1       | [2020-03-24T18:24:17.610647+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to stations port 8020: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [] {"station":{"id":3,"name":"HITRADIO-LÜDENSCHEID"}}
web_1       | [2020-03-24T18:24:18.037105+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 404:  [] {"station":{"id":3,"name":"HITRADIO-LÜDENSCHEID"}}
influxdb_1  | [httpd] 172.18.0.6 - - [24/Mar/2020:18:24:18 +0000] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.5.1 curl/7.58.0 PHP/7.4.4" ac7503b7-6dfc-11ea-94df-000000000000 1434

**Comment by SC2Mitch** [comment]
Have you restarted the Azuracast instance recently?

**Comment by Skyradio** [comment]
Yes I did. This issue I had some months ago, too and I can`t remember how I`ve fixed that. I know this works.....
