### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#2569]
I have 3 stations and I created a new custom field as "cat_id" but when I check https://my radio.com/api/nowplaying, I just can see cat_id has been added for 2 stations and some songs.
It means Custom Fields has not been added and applied to all songs.

**Comment by stardevelop** [comment]
Can I add a custom field to Station Profile? 
For example, a field as 'Station Category' ?

**Comment by SlvrEagle23** [comment]
@stardevelop Please limit GitHub issues to "one issue per issue", and add new feature requests to our FeatureUpvote site (https://features.azuracast.com/) and additional bugs/errors to GitHub as new issues.

If you see a song entry in our Now Playing API that doesn't have custom fields, that means it wasn't detected as a file uploaded into the Music Files management section (i.e. it's a live broadcast, or Icecast did not properly translate the metadata over from Liquidsoap). This happens from time to time.
