### ISSUE TITLE
icecast status page rows remover

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#257]
Hello,

I know in icecast you can remove / hide some information from the public in the status page: like the listeners.
I've already tried removing some lines from the icecast status page but they still appear on the page: http://myserver:port

I went on this path:
/var/azuracast/servers/icecast2/web

Can you help me please?

Greetings,
Thank you

**Comment by SlvrEagle23** [comment]
@jonikane One of the philosophies I've always had with AzuraCast is that any one instance of AzuraCast should openly expose enough information that any _other_ instance of AzuraCast could properly pick up the station's now playing and listener data for statistics and management. I don't want there to be any confusion about whether one AzuraCast-hosted station can communicate with another server, so by default this data is always supplied on public-facing pages.

If you're using the Docker installation, you can override the Docker file's build process by forking and customizing this repo: https://github.com/AzuraCast/docker-azuracast-stations - You can change the included files and their contents, then rebuild the Docker image (making sure to name it the same name, `azuracast/azuracast_stations`) on your local machine. You can then spin up the Docker containers (using `docker-compose up`) and it'll detect the new customized image and use it instead.

If you're using the Traditional installation, you can manually update the files shared by Icecast by editing them directly in their main directory: `/usr/local/share/icecast/web`
