### ISSUE TITLE
Remote URL Playlist 

### ISSUE THREAD

**Issue by jbsix** [AzuraCast/AzuraCast#2570]
**Using Docker installation method**

Yes
**Host Operating System**

Ubuntu 
**Describe the bug**

With latest update, Remote URL Playlist no longer works.
**To Reproduce**

Edit playlist, source, remote URL playlist

**Expected behavior**

Play from remote source, direct or playlist.

**Relevant Logs**

Tried experimenting with buffer, received error: Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by jbsix** [comment]
temporary work around was to point to server ip address, as seems to be as other's have reported, a bug with https.

**Comment by stardevelop** [comment]
I have the same problem with Remote URLs with https.

**Comment by jbsix** [comment]
Even with workaround using IP with HTTP still throwing buffer timeout errors. 

Liquidsoap Log:

2020/03/27 17:59:58 [http_7664:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!

**Comment by mrdavi5** [comment]
I also have the same issues. I've tried direct and playlist streams both do not work.
If this is fixed this will be the perfect solution.
