### ISSUE TITLE
Playlist copy

### ISSUE THREAD

**Issue by Skyradio** [AzuraCast/AzuraCast#2572]
Hi,
I´m running 3 Stations with different Genres. But some Playlists are always the same. Is there a way to copy the complete Playlist with Headline and settings to an other station??

thx Mike

**Comment by SlvrEagle23** [comment]
@Skyradio Hello and thank you for your suggestion. As this is a new feature request, we would like to ask that you please submit it over at https://features.azuracast.com/, so we can keep this GitHub issues board separate for bugs and errors only.

**Comment by Vaalyn** [comment]
I think there is already a feature request for this: https://features.azuracast.com/suggestions/38929/clone-playlists
