### ISSUE TITLE
Schedule not launching at time set 

### ISSUE THREAD

**Issue by rdr-dev** [AzuraCast/AzuraCast#2574]
I'm loving Azuracast - Works perfectly, other than launching playlists at a set and play at a set time.  No error logs in the log file, the playlists for some reason do not trigger, is this a known fault?  I've attached some files. 
![Capture](https://user-images.githubusercontent.com/59894454/77594259-0433d900-6eee-11ea-9440-6523322fca66.PNG)
![Capture2](https://user-images.githubusercontent.com/59894454/77594265-06963300-6eee-11ea-8fcd-064bbdc47364.PNG)
![Capture3](https://user-images.githubusercontent.com/59894454/77594272-09912380-6eee-11ea-8acc-e8e2ec4ead0e.PNG)

**Comment by SlvrEagle23** [comment]
Closing in favor of a single super-issue to discuss these types of problems: #2631
