### ISSUE TITLE
What to do with AzuraRelay

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#2575]
I need to know the concept of adding an AzuraRelay. 

For making High Availability for my station, I installed AzuraRelay on another server successfully and connected it to main Azuracast platform.

Now, I have two streaming URLs:
Azuracast Local Stream: https://stream1.radio.com/radio/8000/radio.mp3
Remote Relay: https://relay1.radio.com/radio/8000/radio.mp3

Which URL should I use for streaming in my Web and Mobile apps?
How to make use of HA in this case?

**Comment by stardevelop** [comment]
1) What to do if I have three relay servers (R1, R2, R3) and want to make Load Balancing between them?
2) How can I distribute listeners between relay servers evenly?
3) Can I have a single Streaming URL like https://stream.radio.com/radio/8000/radio.mp3 for using in web and mobile players and Azuracast could detect which relay server has free resources and then redirect listeners to that one automatically?

For example, if the R1 is overloaded (CPU, Memory, Bandwidth), then the rest of listeners automatically are redirected to 2nd relay server and then the 3rd one.

**Comment by stardevelop** [comment]
@SlvrEagle23 
I believe the AzuraRelay should work differently.
When I add two AzuraRelay to Azuracast, it should only display AzuraRelay streaming URLs in .pls and .m3u files. But it also displays Azuracast streaming URL (main platform) and listeners can connect to all there servers.
The concept of having AzuraRelay should be like this that listeners are re-directed only to AzuraRelay servers and not Azuracast itself.

**Comment by Youssef-Harby** [comment]
I have the same questions? 
Any one can help ?

**Comment by quydox** [comment]
You should use relay url. If you have many relay urls you can use Haproxy in front of all. Just test it
