### ISSUE TITLE
Azuracast Install Instructions. Help

### ISSUE THREAD

**Issue by mgiannelis** [AzuraCast/AzuraCast#2579]
Hello.

I have been trying to get Auzracast Installed for days now and I have spent over 70Hours trying to get this to work.
Background. I am trying to install this with a fresh install of Ubuntu 18.4 server
I have a windows 2012 R2 server running HyperV and I am installing/running the Unbuntu Server ISO setup file and run as a virtual machine.
I have been unable to get the docker install type to work. Or Ansible And I know nothing about docker or even what it actually is. I'm just trying to follow instructions  I believe that I am missing something or not doing something correctly. There has to defiantly be some kind of missing step in the install instructions.
I have also followed the Ansible instructions which seem to be more simple absolutely step by step several times. And each time on a new fresh install of ubuntu. However I keep getting an error at the end of the install. I need to take a screen shot of this and add it to this post. (Stand By) Ill put it up on my next install attempt.
This is starting to drive me crazy! Now I know there is nothing wrong or any incompatibility issues with hardware or the fact that I am using a HyperV virtual machine as I had an old friend install and get it up and running for me in the past on the same platform without issue. However my attempts at trying to replicate his success has failed over and over again. I'am trying to reinstall it and get it back up and running in a fresh ubuntu install. However time and time again it fails with some errors at the end.
Also. While following the instructions here.  https://www.azuracast.com/install/ansible.html#installing
The URL describes the whole install process to be between 10 to 15 minutes.,
I have a 100Mpbs internet connection. And this install process seems to take over 45 minutes.
It never took my friend that long to install it on my server.

I have no idea whats going on. I am a newbie to linux and installing applications. However I have followed all the install instructions step by step. Both using the ansible and docker methods.
I have a feeling that there is something missing in the instructions. Perhaps some steps that are not in there. I am basing my issues/complaint on the fact that I am following the instructions step by step as set out in the URL above.
Can you someone please indicate. Are there steps missing from the instructions? I have no idea. I'm not a linux person.

I am hoping. That someone who is reading this might be a pro. And upon me giving a pro access via SSH to help me set this up and get it back up and running for me.

I messed up my installation when I was trying to work out how to enable SSL. I should have taken a backup of my VM before I started messing around with it.

When it was working. I was totally amazed with how cool AzuraCast was. I loved it and loved playing around with it. I was using it to run a Flight Simulator radio station.
I really want this back up and running. I hope someone here can help me with this.
As I mentioned. I will post the image of the error that I get when the ansible install finishes.

Please. Is there someone out there that would be kind enough to SSH into my ubuntu fresh server install and get this up and running for me.
The documentation on the internet for installing the package is very limited. There is hardly anything out there at all! 
All I can find is instructions on to how to actually use Azuracast. But there is pretty much nothing out there for help with installing and installations issues and support.

I look forward to hearing from anyone that will be willing to help me install this via an SSH connection for me.

Even happy to pay up to $20 Australian Dollars to assist me. I am desperate to get this running.

Thank you for reading.

Matthew

**Comment by mgiannelis** [comment]
So.
I think I have found something that has actually been missing from the install instructions.
I found that at the end of the install. Part of the error message seemed to included something about permissions.

The instructions on the auzracast site was meant to be followed easy by anyone.
What I think has been missing the whole time.....

The fact that the install needs to be run as a root user.
So I had to enable the root account in ubuntu which is NOT active by default.
If this fixes my problem. I would suggest that this is added to the instructions.
Will let you know if this solves my problem.

So far from my understanding now. The fact that I am now logged in as root# I dont need to put in sudo at the start of each command as stated below. Am I correct?Or do I still have to type sudo?

This is confusing. Please update the URL https://www.azuracast.com/install/ansible.html#installing with this information. If this is correct and was added to the site/url this would have saved me from days and days of trying to figure this out.

So now that I am logged in as #. Do I still need to type sudo in front of the commands?

sudo apt-get update
sudo apt-get install -q -y git

sudo mkdir -p /var/azuracast/www
cd /var/azuracast/www
sudo git clone https://github.com/AzuraCast/AzuraCast.git .

sudo chmod a+x install.sh
./install.sh

Can I also add.
The site URL indicates a 10 to 15 minute install time.
I am now running the install and commands as # but the install has still be running now for over 30 minutes on a 100mbps connection.

**Comment by SC2Mitch** [comment]
I'll do a pull to adjust the documentation @mgiannelis

**Comment by mgiannelis** [comment]
Thanks. Is this where I have been going wrong?
I have been creating fresh installs of unbuntu server.
Then once the OS install finishes. I reboot.
Then I have been following the instructions using to be what seems to most simple (Ansible)
So once the reboot completes. I have just been following the instructions and writing every command with sudo in front of it. And I did not enable to root account in ubuntu first???

I'm not sure if this is going to work. I am still waiting for the very long install to complete.
Its been sitting on initialize OPAM now for over 15 minutes.

**Comment by mgiannelis** [comment]
Its now been over an hour! And the install is still running!!!!!
Why does this take so long?

**Comment by SlvrEagle23** [comment]
@mgiannelis If you use our (unsupported, non-recommended) Ansible installation, the Ansible script installs everything by hand, which unfortunately includes a Liquidsoap installation and compilation step that is known to take upwards of 20-30 minutes even on powerful hardware, and longer on less powerful hardware.

This is one of _many_ reasons why we recommend using the Docker installation. While I appreciate that you're having significant difficulty installing AzuraCast, you are attempting to use an unsupported method of installation, which is something we note on that page and many others throughout our install instructions.

We are a very small team, and it's specifically because of the increased support burden that our Ansible installation creates that we can't afford to support it as heavily as we do our Docker installations.

**Comment by mgiannelis** [comment]
Oh okay. Thanks for for letting me know.
The only reason I am using the Ansible method is due to it being the only method I can work out and get the install running.

is there any chance you could write a step by step (From fresh install for the other methods) I have no idea about docker.
When I have tried the docker install. At a point it comes up with a need to reboot.
I reboot. But the installation does not start off again. I have to run the install again and then just come back to the part of the installation where it asks me to reboot again. So I am in a loop. No idea of what to do.

**Comment by mgiannelis** [comment]
For people like me. There needs to be much clearer information and instructions.

**Comment by mgiannelis** [comment]
For a small team. You are doing an amazing job with creating such an amazing application!
I fell in love with it when I had it installed and working (Installed by an old friend)
That's why I have been trying for days and days on end to try and get it working again,

**Comment by SlvrEagle23** [comment]
@mgiannelis You may need to install Docker yourself on your server. You can follow Docker's instructions here: https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-engine---community-1

We do provide a step-by-step installation, and in 99% of cases this should work without issue. There is a specific problem with your setup that is causing trouble, but otherwise following our installation steps is not a problem.

**Comment by mgiannelis** [comment]
I had a look at it.
I have no idea. There are steps there. But there are also options.
I have no idea which options I should be using.

**Comment by mgiannelis** [comment]
This is what the simple bare metal installation says for Ansible.
The document advises this is all that needs to be done in order to get Azuracast up and running

Installing
Execute these commands as a user with sudo permissions (or root) to set up your AzuraCast server:

sudo apt-get update 
sudo apt-get install -q -y git 
 
sudo mkdir -p /var/azuracast/www 
cd /var/azuracast/www 
sudo git clone https://github.com/AzuraCast/AzuraCast.git . 
 
sudo chmod a+x install.sh 
./install.sh 
The installation process will take between 5 and 15 minutes, depending on your Internet connection.

Once the terminal-based installation is complete, follow the initial setup instructions.

After this. I should simply be able to access the Azuracast initial setup and crate the user name and passwords via a web browser using localhost or the direct IP.

However it has turned out that there is so much information actually missing.

**Comment by SC2Mitch** [comment]
To install via Docker, you can follow this guide
https://www.azuracast.com/install/docker.html

**Comment by mgiannelis** [comment]
I just completed the Ansible install.
Now when I go to the server IP in my web browser. Azuracast is not coming up.

instead i get this

Welcome to nginx!
If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx.

**Comment by mgiannelis** [comment]
I have tried to follow that method.

However it gets confusing

curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh
chmod a+x docker.sh
./docker.sh install

Is this meant to be all in one line
curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh
What is the > docker.sh
is it docker.sh >docker.sh

Or is it on a different line ???
curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh
Docker.sh

**Comment by SlvrEagle23** [comment]
@mgiannelis It's not supposed to be confusing. You type it into your terminal exactly as written. You can even copy/paste it in if needed.

**Comment by FlorianGoetze** [comment]
> Hello.
> 
> I have been trying to get Auzracast Installed for days now and I have spent over 70Hours trying to get this to work.
> Background. I am trying to install this with a fresh install of Ubuntu 18.4 server
> I have a windows 2012 R2 server running HyperV and I am installing/running the Unbuntu Server ISO setup file and run as a virtual machine.
> I have been unable to get the docker install type to work. Or Ansible And I know nothing about docker or even what it actually is. I'm just trying to follow instructions I believe that I am missing something or not doing something correctly. There has to defiantly be some kind of missing step in the install instructions.
> I have also followed the Ansible instructions which seem to be more simple absolutely step by step several times. And each time on a new fresh install of ubuntu. However I keep getting an error at the end of the install. I need to take a screen shot of this and add it to this post. (Stand By) Ill put it up on my next install attempt.
> This is starting to drive me crazy! Now I know there is nothing wrong or any incompatibility issues with hardware or the fact that I am using a HyperV virtual machine as I had an old friend install and get it up and running for me in the past on the same platform without issue. However my attempts at trying to replicate his success has failed over and over again. I'am trying to reinstall it and get it back up and running in a fresh ubuntu install. However time and time again it fails with some errors at the end.
> Also. While following the instructions here. https://www.azuracast.com/install/ansible.html#installing
> The URL describes the whole install process to be between 10 to 15 minutes.,
> I have a 100Mpbs internet connection. And this install process seems to take over 45 minutes.
> It never took my friend that long to install it on my server.
> 
> I have no idea whats going on. I am a newbie to linux and installing applications. However I have followed all the install instructions step by step. Both using the ansible and docker methods.
> I have a feeling that there is something missing in the instructions. Perhaps some steps that are not in there. I am basing my issues/complaint on the fact that I am following the instructions step by step as set out in the URL above.
> Can you someone please indicate. Are there steps missing from the instructions? I have no idea. I'm not a linux person.
> 
> I am hoping. That someone who is reading this might be a pro. And upon me giving a pro access via SSH to help me set this up and get it back up and running for me.
> 
> I messed up my installation when I was trying to work out how to enable SSL. I should have taken a backup of my VM before I started messing around with it.
> 
> When it was working. I was totally amazed with how cool AzuraCast was. I loved it and loved playing around with it. I was using it to run a Flight Simulator radio station.
> I really want this back up and running. I hope someone here can help me with this.
> As I mentioned. I will post the image of the error that I get when the ansible install finishes.
> 
> Please. Is there someone out there that would be kind enough to SSH into my ubuntu fresh server install and get this up and running for me.
> The documentation on the internet for installing the package is very limited. There is hardly anything out there at all!
> All I can find is instructions on to how to actually use Azuracast. But there is pretty much nothing out there for help with installing and installations issues and support.
> 
> I look forward to hearing from anyone that will be willing to help me install this via an SSH connection for me.
> 
> Even happy to pay up to $20 Australian Dollars to assist me. I am desperate to get this running.
> 
> Thank you for reading.
> 
> Matthew

Unfortunately, I get this error: 
TASK [init : Update pip components] ************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named pkg_resources
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (setuptools) on localhost.localdomain's Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}.

PLAY RECAP *********************
localhost : ok=6 changed=0 unreachable=0 failed=1 skipped=4 rescued=0 ignored=0

And here again as a screenshot: 
https://prnt.sc/wr67q6

Best Regards
Florian
