### ISSUE TITLE
where do i put files?!

### ISSUE THREAD

**Issue by Gartral** [AzuraCast/AzuraCast#258]
Where do i put music files? I want to know where I upload my music too!

**Comment by SlvrEagle23** [comment]
@Gartral You can always use the web interface to upload files, particularly the Media page. You can click and drag files onto this page, or browse for files on your computer to upload.

If you want to do a bulk upload via SFTP, it depends on whether you installed AzuraCast using the traditional method or the Docker method. If you installed using the traditional method, you can connect via SFTP onto your server and access `/var/azuracast/stations` (then, within that, the station name and the `media` directory). If you installed with Docker, instructions are here for setting up a temporary SFTP server for bulk uploads: https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#access-files-via-sftp-docker-installations

**Comment by Gartral** [comment]
but I can't, I get a JSON file in return, it reads 


  |  
-- | --
error |  
code | 404
msg | "File or Directory Not Found"

but I hear the "This radio Server is powered by AzuraCast, but it has no music....
 on endless loop

**Comment by Gartral** [comment]
your "fix" broke it more, now I can't do anything, it complains about "unsaved changes" abd there's no "Save Changes" button

**Comment by SlvrEagle23** [comment]
@Gartral Can you send a screenshot of the page you're looking at? Also, what's the URL of the page where you're seeing that error?

**Comment by Gartral** [comment]
@SlvrEagle23 of course, the URL is here https://znc.kitsunet.info/station/1/files#playlist:Nexscape+Radio

![mozilla firefox_111](https://user-images.githubusercontent.com/649782/31865087-66d53102-b736-11e7-81f7-0be86c3d1d8a.png)

**Comment by SlvrEagle23** [comment]
@Gartral Is this a traditional installation (using `install.sh`) or a Docker install?

I'm not seeing this same issue on any of my installations of either type. The main files page should return a full HTML page (or, if it couldn't be found, a fully styled 404 page), so there's something wrong here at a different level.

If you're using any sort of reverse proxy service (like Cloudflare) you may want to try disabling any optimization tools they have on their end, as it may be messing with AzuraCast's ability to serve results.

**Comment by Gartral** [comment]
nope, not using a reverse proxy or load balancer, this is a docker deployment on a DO droplet. Ubuntu 16.04, and as for the SFTP thing I think I discovered a bug, as ctrl-c isn't killing the minissh instance and it's appearently interfering with the website side of AzuraCast.

**Comment by Gartral** [comment]
welll... debugged through lobotomy by shotgun.. I wiped out the azuracast install and reinstalled it annnd now it works... go figure

**Comment by surihost** [comment]
Help needed,

with this method, where should i put my station name?
still cant find where to upload music to a specific station

docker run --rm \
    -v azuracast_station_data:/home/azuracast/stations \
    -p 2222:22 atmoz/sftp:alpine \
    azuracast:azuracast:::stations
