### ISSUE TITLE
Same Artist within 1 hour (UK Radio Licensing Compliance)

### ISSUE THREAD

**Issue by alexhorner** [AzuraCast/AzuraCast#2585]
**Using Docker installation method**

Yes

**Host Operating System**

Ubuntu 18.04.4 LTS Minimal

**Describe the bug**

AutoDJ requests are not preventing the playing of the same artist within the same hour (UK Radio licensing issue). As discussed on Discord in DMs, this is an issue.

**To Reproduce**

Have two people request two different songs from the same artist

**Expected behavior**

The request would be rejected just like requesting the same song within an hour would (non 200 status code on API)

**Relevant Logs**

N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/33007665/77828609-68d07d00-7114-11ea-89a8-ebcb86df687a.png)
![image](https://user-images.githubusercontent.com/33007665/77828613-6cfc9a80-7114-11ea-872c-3e1602eada23.png)

**Device(s):**
N/A

**Additional context**

Reference #181

**Comment by SlvrEagle23** [comment]
@alexhorner I've updated the request "already played" detection to apply the same duplicate artist/title prevention that happens with our own AutoDJ, so it should be in full compliance with regulations.
