### ISSUE TITLE
Live stop for a few seconds

### ISSUE THREAD

**Issue by ismaelazanza** [AzuraCast/AzuraCast#2588]
Greetings, we have installed version 0.9.9, on a new Ubuntu 18.04 (64 Bit) server, with the Docker installation, however we see a problem. When we connect a live DJ for a few seconds it disconnects, we have tried icecast and shoutcast with the same result.

2020/03/28 17:59:38 [lang:3] Authenticating DJ: ismael
2020/03/28 17:59:39 [lang:3] AzuraCast DJ Auth Response: true
2020/03/28 17:59:39 [electrofactory_input_streamer:3] New metadata chunk ? -- cyndi lauper - Time After Time (Extended Ver.
2020/03/28 17:59:42 [dummy:3] Source failed (no more tracks) stopping output...
2020/03/28 17:59:42 [electrofactory_live_fallback:3] Switch to cross_7716 with forgetful transition.
2020/03/28 17:59:42 [lang:3] AzuraCast Feedback Response: OK
2020/03/28 17:59:47 [electrofactory_live_fallback:3] Switch to audio_to_stereo_7739 with transition.
2020/03/28 18:02:15 [electrofactory_live_fallback:3] Switch to cross_7716 with forgetful transition.
2020/03/28 18:02:15 [lang:3] AzuraCast Feedback Response: OK
2020/03/28 18:02:15 [dummy:3] Source failed (no more tracks) stopping output...
2020/03/28 18:02:20 [electrofactory_live_fallback:3] Switch to audio_to_stereo_7739 with transition.
2020/03/28 18:04:40 [electrofactory_live_fallback:3] Switch to cross_7716 with transition.
2020/03/28 18:04:40 [dummy:3] Source failed (no more tracks) stopping output...
2020/03/28 18:04:40 [lang:3] AzuraCast Feedback Response: OK
2020/03/28 18:04:45 [electrofactory_live_fallback:3] Switch to audio_to_stereo_7739 with transition.
2020/03/28 18:05:00 [lang:3] Authenticating DJ: ismael
2020/03/28 18:05:01 [lang:3] AzuraCast DJ Auth Response: true
2020/03/28 18:05:01 [electrofactory_input_streamer:3] New metadata chunk ? -- 065. Hot Stuff - Donna Summer.

Shoutcast registration

2020-03-28 17:55:51	INFO	[ADMINCGI sid=1] Title updated [35 Scorpions - When The Smoke Is Going Down]
2020-03-28 17:57:10	INFO	[ADMINCGI sid=1] Title updated [armin van buuren a bt feat. nation of one - always]
2020-03-28 17:57:15	INFO	[ADMINCGI sid=1] Title updated [35 Scorpions - When The Smoke Is Going Down]
2020-03-28 17:59:39	INFO	[ADMINCGI sid=1] Title updated [cyndi lauper - Time After Time (Extended Ver]
2020-03-28 17:59:42	INFO	[ADMINCGI sid=1] Title updated [armin van buuren a bt feat. nation of one - always]
2020-03-28 17:59:48	INFO	[ADMINCGI sid=1] Title updated [cyndi lauper - Time After Time (Extended Ver]
2020-03-28 18:02:15	INFO	[ADMINCGI sid=1] Title updated [armin van buuren a bt feat. nation of one - always]
2020-03-28 18:02:20	INFO	[ADMINCGI sid=1] Title updated [cyndi lauper - Time After Time (Extended Ver]
2020-03-28 18:04:40	INFO	[ADMINCGI sid=1] Title updated [armin van buuren a bt feat. nation of one - always]
2020-03-28 18:04:45	INFO	[ADMINCGI sid=1] Title updated [cyndi lauper - Time After Time (Extended Ver]
2020-03-28 18:05:06	INFO	[ADMINCGI sid=1] Title updated [065. Hot Stuff - Donna Summer]

**Comment by SlvrEagle23** [comment]
@ismaelazanza Have you tried increasing the DJ broadcast buffer in the station's profile? This controls how long the server will hold an audio feed before disconnecting; if your connection is less than stable, increasing this number will help avoid that problem.

**Comment by ismaelazanza** [comment]
Thanks for the help I have placed it in 20 seconds, I will try it that way. I appreciate your response

**Comment by ismaelazanza** [comment]
Greetings we have followed your advice, unfortunately the inconvenience continues, we have tested you for up to 60 seconds, however we see that the autodj continues interrupting the live DJ.

2020/03/31 17:22:16 [lang:3] Authenticating DJ: ismael
2020/03/31 17:22:17 [lang:3] AzuraCast DJ Auth Response: true
2020/03/31 17:22:17 [electrofactory_input_streamer:3] New metadata chunk ? -- UB40 - Kingston Town.
2020/03/31 17:24:40 [dummy:3] Source failed (no more tracks) stopping output...
2020/03/31 17:24:40 [electrofactory_live_fallback:3] Switch to cross_7714 with forgetful transition.
2020/03/31 17:24:40 [lang:3] AzuraCast Feedback Response: OK
2020/03/31 17:25:01 [electrofactory_live_fallback:3] Switch to audio_to_stereo_7737 with transition.
2020/03/31 17:26:01 [lang:3] Authenticating DJ: ismael
2020/03/31 17:26:02 [lang:3] AzuraCast DJ Auth Response: true
2020/03/31 17:26:02 [electrofactory_input_streamer:3] New metadata chunk ? -- 024. - Michael Jackson - Billy Jean.
2020/03/31 17:30:58 [lang:3] Authenticating DJ: ismael
2020/03/31 17:30:58 [lang:3] AzuraCast DJ Auth Response: true
2020/03/31 17:30:58 [electrofactory_input_streamer:3] New metadata chunk ? -- Santana y mana - corazon espinado.
2020/03/31 17:34:57 [dummy:3] Source failed (no more tracks) stopping output...
2020/03/31 17:34:57 [electrofactory_live_fallback:3] Switch to cross_7714 with forgetful transition.
2020/03/31 17:34:57 [lang:3] AzuraCast Feedback Response: OK
2020/03/31 17:35:17 [electrofactory_live_fallback:3] Switch to audio_to_stereo_7737 with transition.
2020/03/31 17:35:32 [lang:3] Authenticating DJ: ismael
2020/03/31 17:35:33 [lang:3] AzuraCast DJ Auth Response: true
2020/03/31 17:35:33 [electrofactory_input_streamer:3] New metadata chunk ? -- Artista - 050 Boat on the river.
