### ISSUE TITLE
Playlist Not Playing at Scheduled Time

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#2589]
Hello, 

There is a playlist between 12:00 and 12:06 and including 2 audio files 5.5 Min long. Looks like this playlist is not played and the logs are below.

Docker, ubuntu, Manual AutoDJ Mode On

What could be the reason and what means "Failed to prepare track: request not ready"?

> **2020/03/29 12:00:00 [playlist_sunset_daily_bbc_world_news_reports:1] Failed to prepare track: request not ready.**
> 2020/03/29 12:00:00 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/live_jam_107/media/Live Jam 107/poi_dog_pondering_-_everybody_s_trying_on_letterman.mp3".
> 2020/03/29 12:00:01 [cross_7838:3] Analysis: -37.469744dB / -13.216546dB (17.46s / 17.50s)
> 2020/03/29 12:00:01 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
> 2020/03/29 12:00:01 [lang:3] AzuraCast Feedback Response: OK
> 2020/03/29 12:03:40 [playlist_live_jam_107:3] Prepared "/var/azuracast/stations/live_jam_107/media/Live Jam 107/poi_dog_pondering_-_everybody_s_trying_on_letterman.mp3" (RID 0).

**Comment by radiolize** [comment]
Some screenshots:
https://pasteboard.co/J1mjOs3.png
https://pasteboard.co/J1mkaXR.png

The all playlists set right by station's user as I see.

**Comment by SlvrEagle23** [comment]
Closing for a super-issue: #2631
