### ISSUE TITLE
Error in UPDATE please help.

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#259]
I updated my azuracast installed but this is the error at the end of the update process. Any one can help to resolve the issue?

TASK [azuracast-radio : Build LiquidSoap] ******************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "opam init -y && opam install -y taglib.0.3.3 mad.0.4.5 faad.0.3.3 fdkaac.0.2.1 lame.0.3.3 vorbis.0.7.0 cry.0.6.0 flac.0.1.2 liquidsoap.1.3.3", "delta": "0:00:02.007308", "end": "2017-10-23 01:23:09.618611", "failed": true, "rc": 66, "start": "2017-10-23 01:23:07.611303", "stderr": "[ERROR] No package matches liquidsoap.1.3.3.\n[ERROR] No package matches cry.0.6.0.", "stderr_lines": ["[ERROR] No package matches liquidsoap.1.3.3.", "[ERROR] No package matches cry.0.6.0."], "stdout": "OPAM has already been initialized.\nIn normal operation, OPAM only alters files within ~/.opam.\n\nDuring this initialisation, you can allow OPAM to add information to two\nother files for best results. You can also make these additions manually\nif you wish.\n\nIf you agree, OPAM will modify:\n\n  - ~/.bash_profile (or a file you specify) to set the right environment\n    variables and to load the auto-completion scripts for your shell (bash)\n    on startup. Specifically, it checks for and appends the following line:\n\n    . /var/azuracast/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true\n\n\n  - ~/.ocamlinit to ensure that non-system installations of `ocamlfind`\n    (i.e. those installed by OPAM) will work correctly when running the\n    OCaml toplevel. It does this by adding $OCAML_TOPLEVEL_PATH to the list\n    of include directories.\n\nIf you choose to not configure your system now, you can either configure\nOPAM manually (instructions will be displayed) or launch the automatic setup\nlater by running:\n\n   opam config setup -a\n\n\nDo you want OPAM to modify ~/.bash_profile and ~/.ocamlinit?\n(default is 'no', use 'f' to name a file other than ~/.bash_profile)\n    [N/y/f] \nGlobal configuration:\n  ~/.opam/opam-init/init.sh is already up-to-date.\n  ~/.opam/opam-init/init.zsh is already up-to-date.\n  ~/.opam/opam-init/init.csh is already up-to-date.\n  ~/.opam/opam-init/init.fish is already up-to-date.\n\n=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n\n1. To configure OPAM in the current shell session, you need to run:\n\n      eval `opam config env`\n\n2. To correctly configure OPAM for subsequent use, add the following\n   line to your profile file (for instance ~/.bash_profile):\n\n      . /var/azuracast/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true\n\n3. To avoid issues related to non-system installations of `ocamlfind`\n   add the following lines to ~/.ocamlinit (create it if necessary):\n\n      let () =\n        try Topdirs.dir_directory (Sys.getenv \"OCAML_TOPLEVEL_PATH\")\n        with Not_found -> ()\n      ;;\n\n=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=", "stdout_lines": ["OPAM has already been initialized.", "In normal operation, OPAM only alters files within ~/.opam.", "", "During this initialisation, you can allow OPAM to add information to two", "other files for best results. You can also make these additions manually", "if you wish.", "", "If you agree, OPAM will modify:", "", "  - ~/.bash_profile (or a file you specify) to set the right environment", "    variables and to load the auto-completion scripts for your shell (bash)", "    on startup. Specifically, it checks for and appends the following line:", "", "    . /var/azuracast/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true", "", "", "  - ~/.ocamlinit to ensure that non-system installations of `ocamlfind`", "    (i.e. those installed by OPAM) will work correctly when running the", "    OCaml toplevel. It does this by adding $OCAML_TOPLEVEL_PATH to the list", "    of include directories.", "", "If you choose to not configure your system now, you can either configure", "OPAM manually (instructions will be displayed) or launch the automatic setup", "later by running:", "", "   opam config setup -a", "", "", "Do you want OPAM to modify ~/.bash_profile and ~/.ocamlinit?", "(default is 'no', use 'f' to name a file other than ~/.bash_profile)", "    [N/y/f] ", "Global configuration:", "  ~/.opam/opam-init/init.sh is already up-to-date.", "  ~/.opam/opam-init/init.zsh is already up-to-date.", "  ~/.opam/opam-init/init.csh is already up-to-date.", "  ~/.opam/opam-init/init.fish is already up-to-date.", "", "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=", "", "1. To configure OPAM in the current shell session, you need to run:", "", "      eval `opam config env`", "", "2. To correctly configure OPAM for subsequent use, add the following", "   line to your profile file (for instance ~/.bash_profile):", "", "      . /var/azuracast/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true", "", "3. To avoid issues related to non-system installations of `ocamlfind`", "   add the following lines to ~/.ocamlinit (create it if necessary):", "", "      let () =", "        try Topdirs.dir_directory (Sys.getenv \"OCAML_TOPLEVEL_PATH\")", "        with Not_found -> ()", "      ;;", "", "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="]}

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=16   changed=1    unreachable=0    failed=1

**Comment by SlvrEagle23** [comment]
@reans Try the latest codebase update; it has a fix that should resolve the issue. You may need to run `./update.sh --full` if you already ran it once.

**Comment by reans** [comment]
working good now. thanks for quick respond @SlvrEagle23
