### ISSUE TITLE
Cannot find Enable Recording of Live Broadcasts option anywhere...

### ISSUE THREAD

**Issue by sr8087as** [AzuraCast/AzuraCast#2591]
There is no option to enable recording of live broadcasts.  I feel like I remember one but now I have scoured every tab of the Edit Station Profile section multiple times, I feel like I'm losing my mind.  Shouldn't it be right after the Allow Streamers / DJs option in the AUTODJ tab of the Edit Profile section for the Station?  That's where it is in the demo.  It's simply not there.  I've looked everywhere else in the settings as well.  Please put me out of my misery lol.

**Comment by SlvrEagle23** [comment]
@sr8087as Are you on a new enough version of AzuraCast to have the recording feature?

Recording is only enabled if you're using the Liquidsoap AutoDJ backend, but if you see the "Enable Streamers/DJs" setting it should already be switched to that.

**Comment by sr8087as** [comment]
Yeah I just installed azuracast yesterday through Digital Ocean/Docker.  I'm using Liquidsoap AutoDJ backend.  I swear I saw the option & may have disabled it thinking I'd look into it later but didn't want to worry about auto-recording while I was just testing it out.  Now I can't find the option to enable it, it's just not there.  At least from what you're saying I am looking at the right place then?  Was there a sort of Post-Install setup on first login that I may have denied auto-recording option?

**Comment by SlvrEagle23** [comment]
@sr8087as The version in our DigitalOcean one-click install is a few months out of date; you can update your installation by following our standard [updating instructions](https://www.azuracast.com/administration/system/updating.html).

**Comment by sr8087as** [comment]
You're right, thanks.  I didn't realize it wouldn't grab the newest version.

**Comment by SlvrEagle23** [comment]
@sr8087as I've been meaning to update the DigitalOcean version, but I'm waiting on a minor point release (0.9.9.1) to do so, to make sure we include any important bug fixes.

**Comment by sr8087as** [comment]
Really cool software btw!  I've been meaning to look at it for awhile & have wanted to try out some broadcasting tools.  Really enjoying it :)

**Comment by pierluigi** [comment]
I just finished an installation via ansible on my Raspberry Pi and while I see the Dj/Streamers accounts I can't find the option to enable automatic recording anywhere...

**Comment by SlvrEagle23** [comment]
@pierluigi It's in the station's profile edit page, under the "AutoDJ" tab (this may not be the most intuitive place, but it's because our Streamer/DJ accounts are actually managed by our underlying AutoDJ software, so whether you can record broadcasts depends on whether you have the AutoDJ enabled or not).

**Comment by pierluigi** [comment]
@SlvrEagle23 thanks! however this is all I see... 

<img width="477" alt="image" src="https://user-images.githubusercontent.com/1078545/83622138-7f1d0e00-a587-11ea-866f-98d7ecc10b74.png">


`Powered by AzuraCast • v0.10.2, #854dd51 (2020-06-01 10:03) • Ansible • PHP 7.4`

**Comment by SlvrEagle23** [comment]
@pierluigi No, on the *edit* version of that page, i.e. by clicking the "Edit Profile" button from that profile page.

**Comment by pierluigi** [comment]
Apologies... I just realized you wrote "Profile EDIT" page! My bad. Now I see it – thank you!
