### ISSUE TITLE
Old IP in 'Connection Information' after migrating server to other VM

### ISSUE THREAD

**Issue by pilovali** [AzuraCast/AzuraCast#2594]
**Using Docker installation method**
Yes

**Host Operating System**
Debian 9

**Describe the bug**

I moved my server to an other VM that has a different public IP, but the 'Streamer/DJ Accounts' page still shows the old IP address of the previous VM.

**To Reproduce**

- Create backup on old machine
- Restore backup on new machine
- Go to 'Streamer/DJ Accounts' page

**Expected behavior**

It should how the wrong IP.

**Relevant Logs**

**Screenshots**

https://share.pilovali.nl/7o94GT0b.png

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@pilovali This should actually be fixed during the initial update process...try updating again and see if it resets the IP to be the correct new one; it definitely should.

**Comment by pilovali** [comment]
I'm sorry for the late response, but it seems to be working after an update. Thanks.

**Comment by SlvrEagle23** [comment]
@pilovali Yep, update flushes the cache and should fix it.
