### ISSUE TITLE
Problem with Docker while installing Azuracast

### ISSUE THREAD

**Issue by jpprofer** [AzuraCast/AzuraCast#2595]
Hey there,
so, I have two machines. One is always on and stays on my office.
The other is my personal computer, both with Linux Mint 19.

Yesterday I installed on my personal computer and it worked beautifully, so now I'm trying to install on my office pc.

The Docker installation was fine yesterday, but today something is happening, there a lot of errors, here is my terminal:
(note: I have uninstalled it and installed it again, but docker has continued to run)

root@gagarin-MW-G41T-M7:/var/azuracast# cd /var/azuracast
root@gagarin-MW-G41T-M7:/var/azuracast# ./docker.sh update-self && echo "y" | ./docker.sh update
New Docker utility script downloaded.
Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Stopping azuracast_web        ... done
Stopping azuracast_stations   ... done
Stopping azuracast_redis_1    ... done
Stopping azuracast_influxdb_1 ... done
Stopping azuracast_mariadb_1  ... done
Removing azuracast_web        ... done
Removing azuracast_stations   ... done
Removing azuracast_redis_1    ... done
Removing azuracast_influxdb_1 ... done
Removing azuracast_mariadb_1  ... done
Removing network azuracast_default
azuracast_www_data
azuracast_tmp_data
Creating network "azuracast_default" with the default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_www_data" with default driver
Creating azuracast_mariadb_1  ... done
Creating azuracast_influxdb_1 ... done
Creating azuracast_stations   ... done
Creating azuracast_redis_1    ... done
2020/03/30 20:28:53 Waiting for: tcp://mariadb:3306
2020/03/30 20:28:53 Waiting for: tcp://influxdb:8086
2020/03/30 20:28:53 Waiting for: tcp://redis:6379
2020/03/30 20:28:53 Connected to tcp://redis:6379
2020/03/30 20:28:53 Connected to tcp://influxdb:8086
2020/03/30 20:28:53 Connected to tcp://mariadb:3306
Updating AzuraCast...
(Environment: production)

AzuraCast Setup
===============

Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...
 * Environment: Production
 * Installation Method: Docker

Waiting for dependent services to go online...
 0/3 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
 [ERROR] Error encountered: An exception occurred in driver: SQLSTATE[HY000]    
         [2006] MySQL server has gone away                                      
         (/var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Abstr
         actMySQLDriver.php L106)                                               

 ! [NOTE] Running in update mode.                                               

Setting Up InfluxDB
-------------------

Database created.
Retention policies updated.
Continuous queries created.
InfluxDB databases created.

Running Database Migrations
---------------------------

In AbstractMySQLDriver.php line 106:
                                                                               
  An exception occurred in driver: SQLSTATE[HY000] [2006] MySQL server has go  
  ne away                                                                      
                                                                               

In PDOConnection.php line 31:
                                                     
  SQLSTATE[HY000] [2006] MySQL server has gone away  
                                                     

In PDOConnection.php line 27:
                                                     
  SQLSTATE[HY000] [2006] MySQL server has gone away  
                                                     

In PDOConnection.php line 27:
                                                               
  Packets out of order. Expected 0 received 1. Packet size=69  
                                                               

azuracast:setup [--update] [--load-fixtures] [--release]

2020/03/30 20:29:24 Command exited with error: exit status 1
azuracast_mariadb_1 is up-to-date
azuracast_stations is up-to-date
azuracast_redis_1 is up-to-date
azuracast_influxdb_1 is up-to-date
Creating azuracast_web ... done
Update complete!
________________________________________________

So, the first time, the error looks to be here in:
AzuraCast Setup
===============

And when I try to connect to localhost, the web panel is simply blank! No error codes, nothing, just a blank page.
I really need help on this, tried searching all the forum and didn't found nothing, that's why I'm posting here. Thanks!

**Comment by jpprofer** [comment]
this is the full installation, from the beginning to the update:

root@gagarin-MW-G41T-M7:/home/gagarin# mkdir -p /var/azuracast
root@gagarin-MW-G41T-M7:/home/gagarin# cd /var/azuracast
root@gagarin-MW-G41T-M7:/var/azuracast# curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh
root@gagarin-MW-G41T-M7:/var/azuracast# chmod a+x docker.sh
root@gagarin-MW-G41T-M7:/var/azuracast# ./docker.sh install
Docker is already installed! Continuing...
Docker Compose is already installed! Continuing...
Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Starting azuracast_mariadb_1  ... done
Starting azuracast_redis_1    ... done
Starting azuracast_influxdb_1 ... done
Starting azuracast_stations   ... done
2020/03/30 22:54:37 Waiting for: tcp://mariadb:3306
2020/03/30 22:54:37 Waiting for: tcp://influxdb:8086
2020/03/30 22:54:37 Waiting for: tcp://redis:6379
2020/03/30 22:54:37 Connected to tcp://influxdb:8086
2020/03/30 22:54:37 Connected to tcp://redis:6379
2020/03/30 22:54:37 Connected to tcp://mariadb:3306
Installing AzuraCast...
(Environment: production)

AzuraCast Setup
===============

Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...
 * Environment: Production
 * Installation Method: Docker

Waiting for dependent services to go online...
 0/3 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
                                                                                
 [ERROR] Error encountered: An exception occurred in driver: SQLSTATE[HY000]    
         [2006] MySQL server has gone away                                      
         (/var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Abstr
         actMySQLDriver.php L106)                                               
                                                                                

Setting Up InfluxDB
-------------------

Database created.
Retention policies updated.
Continuous queries created.
InfluxDB databases created.

Running Database Migrations
---------------------------


In AbstractMySQLDriver.php line 106:
                                                                               
  An exception occurred in driver: SQLSTATE[HY000] [2006] MySQL server has go  
  ne away                                                                      
                                                                               

In PDOConnection.php line 31:
                                                     
  SQLSTATE[HY000] [2006] MySQL server has gone away  
                                                     

In PDOConnection.php line 27:
                                                     
  SQLSTATE[HY000] [2006] MySQL server has gone away  
                                                     

In PDOConnection.php line 27:
                                                               
  Packets out of order. Expected 0 received 1. Packet size=71  
                                                               

azuracast:setup [--update] [--load-fixtures] [--release]

2020/03/30 22:55:06 Command exited with error: exit status 1
azuracast_stations is up-to-date
azuracast_influxdb_1 is up-to-date
azuracast_redis_1 is up-to-date
azuracast_mariadb_1 is up-to-date
azuracast_web is up-to-date
root@gagarin-MW-G41T-M7:/var/azuracast# cd /var/azuracast
root@gagarin-MW-G41T-M7:/var/azuracast# ./docker.sh update-self
New Docker utility script downloaded.
root@gagarin-MW-G41T-M7:/var/azuracast# ./docker.sh update
Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Stopping azuracast_web        ... done
Stopping azuracast_stations   ... done
Stopping azuracast_influxdb_1 ... done
Stopping azuracast_mariadb_1  ... done
Stopping azuracast_redis_1    ... done
Removing azuracast_web        ... done
Removing azuracast_stations   ... done
Removing azuracast_influxdb_1 ... done
Removing azuracast_mariadb_1  ... done
Removing azuracast_redis_1    ... done
Removing network azuracast_default
azuracast_www_data
azuracast_tmp_data
Creating network "azuracast_default" with the default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_www_data" with default driver
Creating azuracast_influxdb_1 ... done
Creating azuracast_stations   ... done
Creating azuracast_redis_1    ... done
Creating azuracast_mariadb_1  ... done
2020/03/30 22:56:07 Waiting for: tcp://mariadb:3306
2020/03/30 22:56:07 Waiting for: tcp://influxdb:8086
2020/03/30 22:56:07 Waiting for: tcp://redis:6379
2020/03/30 22:56:07 Connected to tcp://influxdb:8086
2020/03/30 22:56:07 Connected to tcp://redis:6379
2020/03/30 22:56:07 Connected to tcp://mariadb:3306
Updating AzuraCast...
(Environment: production)

AzuraCast Setup
===============

Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...
 * Environment: Production
 * Installation Method: Docker

Waiting for dependent services to go online...
 0/3 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
                                                                                
 [ERROR] Error encountered: An exception occurred in driver: SQLSTATE[HY000]    
         [2006] MySQL server has gone away                                      
         (/var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Abstr
         actMySQLDriver.php L106)                                               
                                                                                

 ! [NOTE] Running in update mode.                                               

Setting Up InfluxDB
-------------------

Database created.
Retention policies updated.
Continuous queries created.
InfluxDB databases created.

Running Database Migrations
---------------------------


In AbstractMySQLDriver.php line 106:
                                                                               
  An exception occurred in driver: SQLSTATE[HY000] [2006] MySQL server has go  
  ne away                                                                      
                                                                               

In PDOConnection.php line 31:
                                                     
  SQLSTATE[HY000] [2006] MySQL server has gone away  
                                                     

In PDOConnection.php line 27:
                                                     
  SQLSTATE[HY000] [2006] MySQL server has gone away  
                                                     

In PDOConnection.php line 27:
                                                               
  Packets out of order. Expected 0 received 1. Packet size=71  
                                                               

azuracast:setup [--update] [--load-fixtures] [--release]

2020/03/30 22:56:37 Command exited with error: exit status 1
azuracast_stations is up-to-date
azuracast_influxdb_1 is up-to-date
azuracast_redis_1 is up-to-date
azuracast_mariadb_1 is up-to-date
Creating azuracast_web ... done
Update complete!
root@gagarin-MW-G41T-M7:/var/azuracast# cd /var/azuracast
root@gagarin-MW-G41T-M7:/var/azuracast# ./docker.sh update-self && echo "y" | ./docker.sh update
New Docker utility script downloaded.
Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Stopping azuracast_web        ... done
Stopping azuracast_stations   ... done
Stopping azuracast_mariadb_1  ... done
Stopping azuracast_influxdb_1 ... done
Stopping azuracast_redis_1    ... done
Removing azuracast_web        ... done
Removing azuracast_stations   ... done
Removing azuracast_mariadb_1  ... done
Removing azuracast_influxdb_1 ... done
Removing azuracast_redis_1    ... done
Removing network azuracast_default
azuracast_www_data
azuracast_tmp_data
Creating network "azuracast_default" with the default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_www_data" with default driver
Creating azuracast_mariadb_1  ... done
Creating azuracast_influxdb_1 ... done
Creating azuracast_stations   ... done
Creating azuracast_redis_1    ... done
2020/03/30 22:57:16 Waiting for: tcp://mariadb:3306
2020/03/30 22:57:16 Waiting for: tcp://influxdb:8086
2020/03/30 22:57:16 Waiting for: tcp://redis:6379
2020/03/30 22:57:16 Connected to tcp://redis:6379
2020/03/30 22:57:16 Connected to tcp://mariadb:3306
2020/03/30 22:57:16 Connected to tcp://influxdb:8086
Updating AzuraCast...
(Environment: production)

AzuraCast Setup
===============

Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...
 * Environment: Production
 * Installation Method: Docker

Waiting for dependent services to go online...
 0/3 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
 [ERROR] Error encountered: An exception occurred in driver: SQLSTATE[HY000]    
         [2006] MySQL server has gone away                                      
         (/var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Abstr
         actMySQLDriver.php L106)                                               

 ! [NOTE] Running in update mode.                                               

Setting Up InfluxDB
-------------------

Database created.
Retention policies updated.
Continuous queries created.
InfluxDB databases created.

Running Database Migrations
---------------------------


In AbstractMySQLDriver.php line 106:
                                                                               
  An exception occurred in driver: SQLSTATE[HY000] [2006] MySQL server has go  
  ne away                                                                      
                                                                               

In PDOConnection.php line 31:
                                                     
  SQLSTATE[HY000] [2006] MySQL server has gone away  
                                                     

In PDOConnection.php line 27:
                                                     
  SQLSTATE[HY000] [2006] MySQL server has gone away  
                                                     

In PDOConnection.php line 27:
                                                               
  Packets out of order. Expected 0 received 1. Packet size=72  
                                                               

azuracast:setup [--update] [--load-fixtures] [--release]

2020/03/30 22:57:46 Command exited with error: exit status 1
azuracast_mariadb_1 is up-to-date
azuracast_redis_1 is up-to-date
azuracast_influxdb_1 is up-to-date
azuracast_stations is up-to-date
Creating azuracast_web ... done
Update complete!


please help! :)

**Comment by jpprofer** [comment]
after around 23 tries it worked.
But I hope it don't happen with anyone else, so the secret will be stay calm and wait.

also I heard this erros is someway connected to a timeout of tries, so you must try it a lot of times.

**Comment by SlvrEagle23** [comment]
@jpprofer Usually the "MySQL has gone away" is the result of memory being exhausted, which causes the parent computer to "out-of-memory" kill the MySQL process, which causes it to "go away" mid-connection.

Setting up swap memory in addition to your physical memory usually helps to resolve the problem.
