### ISSUE TITLE
Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused.

### ISSUE THREAD

**Issue by ebinvthomas** [AzuraCast/AzuraCast#2597]
Hello,

when I was installing,i get the error "2020/03/31 09:24:57 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s" 
then installation completed , but. the AzuraCast web page not opening ?

![Screenshot 2020-03-31 at 2 59 03 PM](https://user-images.githubusercontent.com/46584302/78010619-33b86a80-7360-11ea-8464-3b146d9a8a79.png)

**Using Docker installation method**

**Host Operating System**

**Describe the bug**

**To Reproduce**

[Untitled.txt](https://github.com/AzuraCast/AzuraCast/files/4408025/Untitled.txt)

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

I was using cents 7.5 64 bit and tried to check everything , but failed

**Additional context**

**Comment by SlvrEagle23** [comment]
@ebinvthomas What hardware are you using? Usually that indicates an error with mariadb spinning up...either it's just taking too long (which is possible with slower hardware) or it's actually encountering an error, which you can view from the host via `docker-compose logs -f mariadb`.

**Comment by koficypher** [comment]
I have a similar issue and these are the logs....
`Attaching to azuracast_mariadb_1
mariadb_1      | 2020-04-01 08:16:42+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.4.12+maria~bionic started.
mariadb_1      | 2020-04-01 08:16:43+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mariadb_1      | 2020-04-01 08:16:43+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.4.12+maria~bionic started.
mariadb_1      | 2020-04-01  8:16:43 0 [Note] mysqld (mysqld 10.4.12-MariaDB-1:10.4.12+maria~bionic-log) starting as process 11 ...
mariadb_1      | 2020-04-01  8:16:43 0 [Note] InnoDB: Using Linux native AIO
mariadb_1      | 2020-04-01  8:16:43 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1      | 2020-04-01  8:16:43 0 [Note] InnoDB: Uses event mutexes
mariadb_1      | 2020-04-01  8:16:43 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1      | 2020-04-01  8:16:43 0 [Note] InnoDB: Number of pools: 1
mariadb_1      | 2020-04-01  8:16:43 0 [Note] InnoDB: Using SSE2 crc32 instructions
mariadb_1      | 2020-04-01  8:16:43 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
mariadb_1      | 2020-04-01  8:16:44 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
mariadb_1      | 2020-04-01  8:16:44 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1      | 2020-04-01  8:16:44 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_1      | 2020-04-01  8:16:45 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mariadb_1      | 2020-04-01  8:16:45 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_1      | 2020-04-01  8:16:45 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb_1      | 2020-04-01  8:16:45 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb_1      | 2020-04-01  8:16:45 0 [Note] InnoDB: 10.4.12 started; log sequence number 284974; transaction id 165
mariadb_1      | 2020-04-01  8:16:45 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mariadb_1      | 2020-04-01  8:16:45 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1      | 2020-04-01  8:16:46 0 [Note] Server socket created on IP: '::'.
mariadb_1      | 2020-04-01  8:16:46 0 [Warning] 'proxies_priv' entry '@% root@075a13db12ae' ignored in --skip-name-resolve mode.
mariadb_1      | 2020-04-01  8:16:46 0 [Note] Reading of all Master_info entries succeeded
mariadb_1      | 2020-04-01  8:16:46 0 [Note] Added new Master_info '' to hash table
mariadb_1      | 2020-04-01  8:16:46 0 [Note] mysqld: ready for connections.
mariadb_1      | Version: '10.4.12-MariaDB-1:10.4.12+maria~bionic-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
mariadb_1      | 2020-04-01  8:16:48 0 [Note] InnoDB: Buffer pool(s) load completed at 200401  8:16:48
mariadb_1      | 2020/04/01 08:23:15 Received signal: terminated
mariadb_1      | 2020-04-01  8:23:15 0 [Note] mysqld (initiated by: unknown): Normal shutdown
mariadb_1      | 2020-04-01  8:23:15 0 [Note] Event Scheduler: Purging the queue. 0 events
mariadb_1      | 2020-04-01  8:23:15 0 [Note] InnoDB: FTS optimize thread exiting.
mariadb_1      | 2020-04-01  8:23:15 0 [Note] InnoDB: Starting shutdown...
mariadb_1      | 2020-04-01  8:23:15 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
mariadb_1      | 2020-04-01  8:23:15 0 [Note] InnoDB: Buffer pool(s) dump completed at 200401  8:23:15
mariadb_1      | 2020-04-01  8:23:17 0 [Note] InnoDB: Shutdown completed; log sequence number 284983; transaction id 166
mariadb_1      | 2020-04-01  8:23:17 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
mariadb_1      | 2020-04-01  8:23:17 0 [Note] mysqld: Shutdown complete
mariadb_1      | 
mariadb_1      | 2020/04/01 08:23:17 Command finished successfully.
`
From the looks of it, mariadb is shutting down

**Comment by davy39** [comment]
Hi,
Similar problem for me with [these  #logs](https://gist.githubusercontent.com/davy39/1847fd2afeb5660695007733929e6032/raw/2cdad3387ffb19562552f9c4ed699354ce5e8487/azuracast.log), as I've mentioned here : #2545 
Any clue on what's wrong ?

**Comment by RazielSama** [comment]
I have the same issue but i don't have any docker.conf file in that location.

**Comment by Hairrison** [comment]
In my case i just install Lets Encrypt
./docker.sh letsencrypt-create

**Comment by Hairrison** [comment]
Add on Host File 

172.18.0.3      localhost
