### ISSUE TITLE
AzuraCast not showing artist in "now playing" 

### ISSUE THREAD

**Issue by Gartral** [AzuraCast/AzuraCast#260]
how do I make Azuracast show artists in the now playing metadata stream going out to clients? as of right now it shows the track titles.

**Comment by SlvrEagle23** [comment]
@Gartral AzuraCast currently, by design, always sends at least the song title and artist out via the metadata sent to listeners. If calling the AzuraCast API directly, the album, duration and other details should also be included.

If you're not seeing the song artist, this may be an isolated incident to the music files you're using. Verify that the ID3 metadata on the files is correct before uploading them; alternatively, you can edit the media on the station's "Media" page to update any missing metadata.

**Comment by Gartral** [comment]
there are a bunch of files that don't have proper ID3 tags... but even ones that do aren't showing /at times/ it's kinda odd.... might be something with my server though.

**Comment by coreybobco** [comment]
I'm having the same issue--double checked the ID3 tags & also manually edited the song artists and titles. . . I noticed after my initiall Docker installation that /var/azuracast/ was empty, and I had to manually create folders there to initially upload media files. Could it be that other subfolders and files failed to install?

**Comment by SlvrEagle23** [comment]
I'm having trouble tracking down this bug, as none of my servers seem to be showing the same problem.

When the issue happens, can you send me a copy of what appears when you call `http://your-azuracast-url/api/nowplaying` ?

**Comment by coreybobco** [comment]
[{"station":{"id":1,"name":"93 to Y2K","shortcode":"93_to_y2k","description":"IDM, Jungle, Techno, Electro, Ghetto Tech","frontend":"icecast","backend":"liquidsoap","listen_url":"http://radmin.setspy.fm:8000/radio.mp3?1512181936","is_public":true,"mounts":[{"name":"/radio.mp3","is_default":true,"url":"http://radmin.setspy.fm:8000/radio.mp3?1512181936","bitrate":128,"format":"mp3"}]},"listeners":{"current":1,"unique":1,"total":1},"now_playing":{"is_live":false,"elapsed":186,"remaining":172,"sh_id":5,"played_at":1512181755,"duration":358,"is_request":false,"song":{"id":"91ccbc409efa7def0ad8ad1936800ab4","text":"Baby Pop - Gary In","artist":"Baby Pop","title":"Gary In","album":"Deep Techno (RR 737)","lyrics":"","art":""}},"playing_next":{"sh_id":7,"played_at":0,"duration":355,"is_request":false,"song":{"id":"b02ff9d548bb7647780fc7f880d11ba4","text":"baby pop - deep techno","artist":"baby pop","title":"deep techno","album":"","lyrics":"","art":""}},"song_history":[{"sh_id":6,"played_at":1512181753,"duration":0,"is_request":false,"song":{"id":"7a1230502efebe8990578f71285bcf46","text":"Stream Offline","artist":"","title":"","album":"","lyrics":"","art":""}},{"sh_id":4,"played_at":1512181686,"duration":399,"is_request":false,"song":{"id":"1dc0adb61a9ece660fe54577b081fd92","text":"Baby Pop - Dik Juice","artist":"Baby Pop","title":"Dik Juice","album":"Deep Techno (RR 737)","lyrics":"","art":""}},{"sh_id":3,"played_at":1512181598,"duration":0,"is_request":false,"song":{"id":"dfaf3809b3dd1f90e73a25a2cebcde72","text":"AzuraCast - AzuraCast Is Live!","artist":"AzuraCast","title":"AzuraCast Is Live!","album":"","lyrics":"","art":""}},{"sh_id":2,"played_at":1512181596,"duration":0,"is_request":false,"song":{"id":"7a1230502efebe8990578f71285bcf46","text":"Stream Offline","artist":"","title":"","album":"","lyrics":"","art":""}},{"sh_id":1,"played_at":1512180830,"duration":0,"is_request":false,"song":{"id":"dfaf3809b3dd1f90e73a25a2cebcde72","text":"AzuraCast - AzuraCast Is Live!","artist":"AzuraCast","title":"AzuraCast Is Live!","album":"","lyrics":"","art":""}}],"cache":"hit"}]

**Comment by coreybobco** [comment]
So I'm not sure why it's showing as "Song Artist" on my public page -- I tried reinstalling from Git today because I noticed you made a commit that might have addressed this issue

**Comment by SlvrEagle23** [comment]
@coreybobco That's very interesting, because that nowplaying API response _does_ have an artist name in every section that should have one...but for whatever reason, on the public page Vue isn't showing the artist name.

If you look at the public page, do you see any sort of error in the web dev console that might suggest what's going on?

**Comment by coreybobco** [comment]
So before I had altered the docker-compose.yml so that my Azuracast instance was running on port 7900 and then had nginx proxy that to a subdomain on a URL -- while that technically also meant the API would show via URL redirection on that subdomain, I think that is the source of the issue.
