### ISSUE TITLE
How can I change the background image on my station?

### ISSUE THREAD

**Issue by giorgosn** [AzuraCast/AzuraCast#2600]
I would like to change the background image  to my station?
Is it possible from the UI?
How can programmatically change it?

Thanks.

**Comment by dvdokkum** [comment]
@giorgosn if you search through some of the closed issues you'll see this has been answered previously. check out: https://github.com/AzuraCast/AzuraCast/issues/724

**Comment by ErnestPH** [comment]
I found a way how to add different background images for each station. jQuery code

`$('.page-minimal.station-name').css('background-image','url(link-to-image.png)');
`
Hope that helps!

**Comment by webafrancois** [comment]
> I found a way how to add different background images for each station. jQuery code
> 
> `$('.page-minimal.station-name').css('background-image','url(link-to-image.png)'); `
> 
> Change the following:
> 
>     * station-name
> 
>     * link-to-image.png
> 
> 
> Hope that helps!
@ErnestPH 
Where should I insert the line in the azura code ?
Should I insert this line for each webradio ?
Thanks.
