### ISSUE TITLE
Scheduled playlists starts early

### ISSUE THREAD

**Issue by yarik2720** [AzuraCast/AzuraCast#2601]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu 16.04

**Describe the bug**
I have scheduled playlist to run once and play one track, start time 8:00 pm, and time 8:00 pm. But it starts earlier than that time, usually it is 7:52 pm, today it started at 7:50pm

**Relevant Logs**
```
2020/03/31 19:45:24 [lang:3] AzuraCast Feedback Response: OK
2020/03/31 19:45:32 [lang:3] AzuraCast Feedback Response: OK
2020/03/31 19:48:51 [lang:3] AzuraCast Raw Response: annotate:title="Trap Nation Radio Episode 121",artist="Trap Nation",duration="3550.",song_id="00d2b7e938aab347a1dce7db50a189b3",media_id="4976",playlist_id="7":/var/azuracast/stations/noise_fm/media/trap nation podcast/trap_nation_radio_episode_121_-5Bstandard-5D.mp3
2020/03/31 19:48:51 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/noise_fm/media/trap nation podcast/trap_nation_radio_episode_121_-5Bstandard-5D.mp3".
2020/03/31 19:49:31 [noise_fm_next_song:3] Prepared "/var/azuracast/stations/noise_fm/media/trap nation podcast/trap_nation_radio_episode_121_-5Bstandard-5D.mp3" (RID 2).
2020/03/31 19:49:31 [cross_7803:3] Analysis: -76.987956dB / -13.341636dB (8.99s / 9.01s)
2020/03/31 19:49:31 [crossfade:3] No transition: using default.
2020/03/31 19:49:31 [lang:3] AzuraCast Feedback Response: OK
2020/03/31 19:49:40 [lang:3] AzuraCast Feedback Response: OK
```

**Screenshots**
![firefox_x0AaVWDGIM](https://user-images.githubusercontent.com/1839978/78053756-ba357200-7389-11ea-8263-6b4705347286.png)
![firefox_hSY1JLrUEv](https://user-images.githubusercontent.com/1839978/78054034-2021f980-738a-11ea-88ce-ee03737a3e48.png)
![firefox_VhfpZ57KKn](https://user-images.githubusercontent.com/1839978/78054038-231cea00-738a-11ea-949d-572cb803705e.png)
![firefox_c0pfknebFh](https://user-images.githubusercontent.com/1839978/78054045-257f4400-738a-11ea-831b-ac05edfddafa.png)

**Comment by yarik2720** [comment]
Even more..
I have playlist that should start to play one track at Thursday 12AM, but it didn't. It started to play at Thursday 11:52PM.
![firefox_0EwGxoJ1Va](https://user-images.githubusercontent.com/1839978/78301323-91f07380-7541-11ea-92ff-e62ca09193c0.png)

![firefox_kSSJYR3hK9](https://user-images.githubusercontent.com/1839978/78301095-450c9d00-7541-11ea-87d0-1389a50b9fa5.png)

**Comment by SlvrEagle23** [comment]
@yarik2720 I'm merging all of these similar issues into a single one. Follow #2631 for updates.
