### ISSUE TITLE
Error 500 after update

### ISSUE THREAD

**Issue by danielrodrigotest** [AzuraCast/AzuraCast#2605]
Dear  Azuracast, after the update sent I made an update, but I got the error 500 and I cannot access to the dashboard. It shows **error 500 Typed property App\Entity\Api\NowPlayingCurrentSong::$elapsed must be int, null used**
Thanks
![Screenshot 2020-04-01 at 01 17 50](https://user-images.githubusercontent.com/40525323/78099258-b3255880-73b7-11ea-929b-83afff6f170b.png)

Restarting all radio stations...
--------------------------------

[01-Apr-2020 04:15:48 UTC] PHP Fatal error:  Uncaught TypeError: Typed property App\Entity\Api\NowPlayingCurrentSong::$elapsed must be int, null used in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php:51
Stack trace:
#0 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php(51): unserialize()
#1 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(316): Doctrine\DBAL\Types\ArrayType->convertToPHPValue()
#2 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(331): Doctrine\ORM\Internal\Hydration\AbstractHydrator->gatherRowData()
#3 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(162): Doctrine\ORM\Internal\Hydration\ObjectHydrator->hydrateRowData()
#4 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(153): Doctrine\ORM\Internal\Hydration\ObjectHydrator->hydrateAllData()
#5 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/ in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 51
2020/04/01 04:15:48 Command exited with error: exit status 255
azuracast_mariadb_1 is up-to-date
azuracast_stations is up-to-date
azuracast_redis_1 is up-to-date
azuracast_influxdb_1 is up-to-date
Creating azuracast_web ... done
Update complete!

**Comment by SlvrEagle23** [comment]
@danielrodrigotest Thank you for the detailed error report. I was able to work on a solution for this, and if you update again to the latest version it should be resolved.
