### ISSUE TITLE
Auto DJ Liquidsoap Error Line 137

### ISSUE THREAD

**Issue by D3TR3S** [AzuraCast/AzuraCast#2606]
Very new to this and I'm having an error when attempting to start Auto Dj. The DJ reads as follows:
Liquidsoap encountered an error
Line 137, char 0:
Warning 4: Unused variable radio
No output defined, nothing to do.
Line 137, char 0:
Warning 4: Unused variable radio
No output defined, nothing to do.

If possible please explain the solution for dummies. Thanks!

**Comment by SlvrEagle23** [comment]
@D3TR3S You should have at least one location for AzuraCast to broadcast your stream to. Usually, out of the box, we support Icecast as a built-in broadcasting option, which will automatically create a standard 128kbps MP3 "mount point" for listeners to connect to. If you have set your station to only broadcast to remote broadcasting software, you must configure at least one remote relay for the AutoDJ to work.

**Comment by D3TR3S** [comment]
Thanks a lot. I end up deleting it and open a created a new one, it worked this time.
