### ISSUE TITLE
Liquidsoap error on "Rotate" operator

### ISSUE THREAD

**Issue by pavlos2** [AzuraCast/AzuraCast#2607]
Following this issue. Could it be a bug?

https://github.com/savonet/liquidsoap/issues/1108

**Comment by SlvrEagle23** [comment]
@pavlos2 We've updated our Docker installation to include the fixes applied in the issue you mentioned, so any downstream problems should also be resolved.

**Comment by pavlos2** [comment]
Thanks a lot Buster!!
