### ISSUE TITLE
"Playing Next" display incorrect song data

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2608]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu 18.04

**Describe the bug**
When working with multiple playlists, the "Playing Next" function display incorrect song data. It display the first song of the next playlist instead of the next song in the existing playlist.

**Comment by eranwo** [comment]
@SlvrEagle23 It only happens when some playlists set to "**Interrupt other songs to play at scheduled time**." And some not . On this situasion the "Playing Next" display songs from the next playlist that does not set to "Interrupt other songs to play at scheduled time". 

When all playlists sets to "Interrupt other songs to play at scheduled time" - there in no  "Playing Next" display at all.

**Comment by SlvrEagle23** [comment]
@eranwo This is intentional and there isn't much we can do about it; playlists that have the "interrupt other songs" flag set on them are managed by Liquidsoap directly, not AzuraCast, so we can't include them in our determination of what song will play next.
