### ISSUE TITLE
Media files in additional disk/volume (?)

### ISSUE THREAD

**Issue by EfraimGENC** [AzuraCast/AzuraCast#2611]
Hi,

I want to store all music files on an additional disc. How can I do that?
Like: /dev/disk/sdb/all-tracks

**Using Docker installation method**
Yes, standard installation.

**Host Operating System**
Ubuntu 18.04 Server

Regards

**Comment by pavlos2** [comment]
Hi, you can change the media directory at: station -> edit profile -> administration -> Advanced Custom Media Directory

**Comment by ogrenci01** [comment]
Hi @EfraimGENC ;

Please can you try it: https://www.azuracast.com/help/docker/#mounting-a-directory-into-a-station

Aramıza hoşgeldiniz :-)
Welcome to AzuraCast.

**Comment by EfraimGENC** [comment]
> Hi, you can change the media directory at: station -> edit profile -> administration -> Advanced Custom Media Directory

I got this error:

Directory "/mnt/disk/muzikler" was not created
Station.php : 663

**Comment by EfraimGENC** [comment]
> Hi @EfraimGENC ;
> 
> Please can you try it: https://www.azuracast.com/help/docker/#mounting-a-directory-into-a-station
> 
> Aramıza hoşgeldiniz :-)
> Welcome to AzuraCast.

Merhaba! :)

I just this but it's didn't work:

`
version: '2.2'

services:
  web:
    volumes:
      - /path/on/host/computer:/var/azuracast/stations/media/mnt/disk/muzikler

  stations:
    volumes:
      - /path/on/host/computer:/var/azuracast/stations/media/mnt/disk/muzikler
`

**Comment by EfraimGENC** [comment]
> Hi @EfraimGENC ;
> 
> Please can you try it: https://www.azuracast.com/help/docker/#mounting-a-directory-into-a-station
> 
> Aramıza hoşgeldiniz :-)
> Welcome to AzuraCast.

Hi @ogrenci01 ;

I just did but it doens't work. There is no file in /mnt/disk/muzikler

`
version: '2.2'

services:
  web:
    volumes:
      - /mnt/disk/muzikler:/var/azuracast/stations/media/

  stations:
    volumes:
      - /mnt/disk/muzikler:/var/azuracast/stations/media/
`

**Comment by Reaktiv4** [comment]
I have the same problem.

**Comment by SlvrEagle23** [comment]
@EfraimGENC Make sure to fully restart your AzuraCast installation using:

```
cd /var/azuracast
docker-compose down
docker-compose up -d
```

**Comment by Reaktiv4** [comment]
On a clean primary installation, the folder does not change

**Comment by EfraimGENC** [comment]
> @EfraimGENC Make sure to fully restart your AzuraCast installation using:
> 
> ```
> cd /var/azuracast
> docker-compose down
> docker-compose up -d
> ```

Yes, I also did
