### ISSUE TITLE
Error 500 on loading album art

### ISSUE THREAD

**Issue by RadiateTC** [AzuraCast/AzuraCast#2614]
**Using Docker installation method**
no

**Host Operating System**
ubuntu 16.04
**Describe the bug**

rewrite or internal redirection cycle while processing "/index.php", client: 1.bla.bla.bla, server: radio.blabla.net, request: "GET /api/station/1/files/download?file=chill%2F11+11+-+You+%28Sevnth+Remix%29.mp3 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "radio.blabla.net" 

**Additional context**

I've been messing around with nginx config but couldn't get it fixed help would be appreciated :)!

**Comment by preterive** [comment]
How do you fixed it?
Same problem here.

**Comment by preterive** [comment]
2020/04/07 20:26:36 [error] 4254#4254: *2 rewrite or internal redirection cycle while processing "/index.php", client: xxxxxxxx, server: localhost, request: "GET /api/station/xxxxx/art/a12635dc0ef0e8d0bc0abfb1-1573313725.jpg HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxxxxxxxxxx", referrer: "https://xxxxxxxxxxxxxxxxxxxx/station/xxxxx/profile"
