### ISSUE TITLE
Web DJ : WebSocket problem

### ISSUE THREAD

**Issue by kahuitel** [AzuraCast/AzuraCast#2616]
Hello,

I'm discovering AzuraCast, it is really amazing.

Everything is working quite well. I'm using it with docker on port http 10080 and https 10443 using a reverse proxy on my ISPConfig Ubuntu server.
I'm using this in ISPConfig options :
`ProxyPass /.well-known/ !
SSLProxyEngine On
SSLProxyVerify none
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
SSLProxyCheckPeerExpire off
ProxyPass / https://127.0.0.1:10443/
ProxyPassReverse / https://127.0.0.1:10443/`

So I can enable "always https://" and generate my Letsencrypt certificate thru ISPConfig.

The only problem is when I'm using Web DJ : I'm getting the following errors in the console when I'm connecting to the page  : 
`--------init----------- https://azuracast.domain.org/public/dj_test/dj
DevTools failed to parse SourceMap: https://azuracast.domain.org/static/dist/lib/bootstrap/bootstrap.bundle.min.js.map
2webcast-75f3ecd006.js:395`

And this one when I'm turning streaming on : 

`WebSocket connection to 'wss://azuracast.domain.org/radio/8015/' failed: Error during WebSocket handshake: Unexpected response code: 404
Webcast.Socket @ webcast-75f3ecd006.js:395
node.connectSocket @ webcast-75f3ecd006.js:139
startStreaming @ webcaster-23f4c0f3cf.js:1
He @ vue-6c81f02ad0.min.js:6
n @ vue-6c81f02ad0.min.js:6
Yr.o._wrapper @ vue-6c81f02ad0.min.js:6`

Note : I'm not using the dash or any other char that may corrupt generated url.

Please could you give me a hand on this, I'd be very grateful!

Regards,

FX de France

**Comment by SlvrEagle23** [comment]
@kahuitel It sounds like your "upstream" web server (the one you have running on 80/443, likely managed by ISPConfig) doesn't have its proxy configuration set up to properly handle websockets if they exist. Adding support for websockets varies by hosting software, but you should look into that and make sure it's working properly.

**Comment by kahuitel** [comment]
Hi @SlvrEagle23 !
Thank you for your help, I've been checking this out all week-end long, but I couldn't manage for it to work, I still have 404 errors with websockets.

Here are my apache directives :

`ProxyPass /.well-known/ !
SSLProxyEngine on
ProxyPreserveHost On
ProxyRequests Off
SSLProxyVerify none
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
SSLProxyCheckPeerExpire off
ProxyRequests Off
RewriteEngine on
RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
RewriteRule .* wss://127.0.0.1:10443%{REQUEST_URI} [P]
ProxyPass / https://127.0.0.1:10443/
ProxyPassReverse / https://127.0.0.1:10443/`

Everything is working except Web DJ. If anyone could help me to perform further tests, I'd be glad to do so. I've been checking: all required apache modules are loaded.

Sincerely,

FX

**Comment by kahuitel** [comment]
Hello,

I've made some progress, hoping to fix this before the end of the confinement ;-)

Adding the following apache directives allows websocket connection on the public radio page https://mydomain.xyz/public/leclectic_webradio (I've turned on websockets for "Now Playing updates"), I could check it out with google chrome console (101 status) : 

```
#Necessary for letsencrypt renewal with ISPConfig
ProxyPass /.well-known/ !
# Use RewriteEngine to handle websocket connection upgrades
RewriteEngine On
RewriteCond %{HTTP:Connection} Upgrade [NC]
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteRule /(.*) ws://127.0.0.1:10080/$1 [P,L]  
# preserve Host header to avoid cross-origin problems
ProxyPreserveHost on
ProxyPass / http://127.0.0.1:10080/
ProxyPassReverse / http://127.0.0.1:10080/
```

Unfortunately, I still have a 404 error within Web DJ when I'm enabling streaming on https://mydomain.xyz/public/leclectic_webradio/dj .
`webcast-75f3ecd006.js:395 WebSocket connection to 'wss://mydomain.xyz/radio/8005/' failed: Error during WebSocket handshake: Unexpected response code: 404`
Are websockets handled differently for webcasting? Am I missing something ?

Thanks for your tips.

**Comment by kahuitel** [comment]
OK, using https://mydomain.xyz:10080/public/{radio_name}/dj , everything works. Will probably forward this specific page to port 10080 and ask for some help on ISPConfig forums.

Azuracast is amazing !

**Comment by davy39** [comment]
Hi, I'm having the same issue here : I cannot find a way to configure apache properly to get a working WebDJ... Would you have an update to deal with wss ?
