### ISSUE TITLE
Now Playing Task Scheduler issues

### ISSUE THREAD

**Issue by pascalla** [AzuraCast/AzuraCast#2617]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
Now Playing scheduler task is very delayed, or doesn't seem to run at all. I believe this is a scaling issue with Remote Relays. The "Now Playing task" faces a few errors causing metadata to not be updated. 

Sometimes the execution will time out, saying it timed out after 30 seconds (I have azuracast.env file set to 240s). 

I have also received PHP errors which seem related to database. (below)

This behaviour coincides with a large listener increase over the past 3/4 days. I notice that every "Now Playing task" also records listeners of all the relays, in which we have 5 which could be causing the longer execution time.

**To Reproduce**
No special behaviour to reproduce

**Expected behavior**
Run Now Playing Scheduler Task normally and in a timely manner

**Relevant Logs**
Liquidsoap shows metadata coming in properly
![image](https://user-images.githubusercontent.com/22846433/78292978-c7846500-751f-11ea-96cf-bae30c96c12a.png)

Running manual scheduler:
![image](https://user-images.githubusercontent.com/22846433/78292929-b89db280-751f-11ea-9413-b354b1389be6.png)

```
The query returned multiple rows. Change the query or use a different result function like getScalarResult().
SingleScalarHydrator.php : 47

```

**Additional context**
I have also noticed higher CPU usage from what I believe to be the mysql container for Azura.

**Comment by pascalla** [comment]
Note: I want to confirm the "Remote Relay" theory by removing off Azura and seeing the problem goes away, however wont be able to for a little bit cause I believe it requires a station restart.

**Comment by pascalla** [comment]
@SlvrEagle23 Still seeing an issue, my guess is that the initial listener checking is still timing out. I can't seem to get a now playing task to run. I currently only have one remote relay registered and it still times out. 
![image](https://user-images.githubusercontent.com/22846433/78412017-d0e9fc00-7609-11ea-80b2-fdbc904c013c.png)

![image](https://user-images.githubusercontent.com/22846433/78411988-b7e14b00-7609-11ea-9b9b-c9935460c42c.png)

sanity check: 
![image](https://user-images.githubusercontent.com/22846433/78411997-c0d21c80-7609-11ea-98ea-d6c5b8a54f34.png)

**Comment by SlvrEagle23** [comment]
@pascalla Yep, I suspect you're still overrunning that initial mutex lock, and that if that was allowed to complete without overlapping on top of other tasks, everything else would be just fine.

I will look into how to handle that mutex lock situation.

**Comment by SlvrEagle23** [comment]
@pascalla Yep...the current way we're handling the mutex is basically every subsequent process that attempts to acquire the lock simply sits there and waits for the lock to expire before running its own process, rather than just simply not trying to run "on top of" the existing item if the lock already exists and hasn't expired.

It's very easy to imagine that this creates a "runaway process" situation where each subsequent now-playing task (every subsequent 15 seconds) just lines up behind the existing ones in an orderly queue, instead of failing gracefully.

I'm going to rework how this works entirely so that if an existing task is running, subsequent tasks will simply defer to the existing running one up to a given timeout.

**Comment by SlvrEagle23** [comment]
@pascalla I basically rewrote our mutex handling to largely prevent the deadlock between multiple overlapping synchronized tasks via a lock that won't wait and will instead just throw an exception immediately, preventing the runaway CPU backup that happens in cases like this.

Update and let me know if it helps with this situation at all. Granted, the first few runs of the Now Playing process may be slower than normal, but it should stabilize quite quickly.

**Comment by pascalla** [comment]
@SlvrEagle23 I have updated but still seeing strange behaviour, not getting any timeout errors in logs. I actually dont see anything out of ordinary in logs, but still getting very delayed metadata (this is without any remote relays even added).

It seems the Playback Timeline seems to get the information.

![image](https://user-images.githubusercontent.com/22846433/78514573-fa418e00-77a9-11ea-8a9c-2edf50f2402f.png)

![image](https://user-images.githubusercontent.com/22846433/78514577-01689c00-77aa-11ea-929f-e7c223ce047e.png)

Tasks running

![image](https://user-images.githubusercontent.com/22846433/78514592-10e7e500-77aa-11ea-8e36-47c7276b2657.png)

Also still seeing high load on mysql process
![image](https://user-images.githubusercontent.com/22846433/78514612-2b21c300-77aa-11ea-87d8-bb005b4e2282.png)

(excuse the do-agent)

I have a feeling i'm going to need a fresh install to fix this out, i'm really lost on this one.

**Comment by SlvrEagle23** [comment]
@pascalla I think my previous attempt to rewrite the locking mechanism just simply didn't work very well at all, so I've partially reverted to our previous mutex method, except with some added code to ensure it doesn't just endlessly queue up sync tasks one after the other.

This should offer the same relative stability of the previous mechanism, but with better prevention of overlapping sync tasks.

**Comment by pascalla** [comment]
As of commit https://github.com/AzuraCast/AzuraCast/commit/7ee32936da48693b3374a61129a508aaae3b425e the time taken to complete NowPlaying scheduler is down to a whopping 2.6s! Back to speedy metadata at higher listener counts! <3 love to azuracast team
