### ISSUE TITLE
Flooding the server

### ISSUE THREAD

**Issue by Mrdevy** [AzuraCast/AzuraCast#2620]
Hello,

We've recently been hit with a lorry load of attacks onto our radio of people using bots to flood our stream with listeners in the end effectively crashing it or maxing out our listeners so nobody can tune in. Does anyone have a configuration or suggestions to block this?

thanks

**Comment by SC2Mitch** [comment]
You could possibly try IP banning or range banning, bit that may take some backend work

**Comment by stardevelop** [comment]
Sometimes, I have the same issue. Azuracast has no solution for this yet.
