### ISSUE TITLE
An AzuraCast Community Forum

### ISSUE THREAD

**Issue by andrewfer000** [AzuraCast/AzuraCast#2621]
Honestly this isn't a feature request or a bug so I rolled a dice and decided to post it here.

So, AzuraCast has gotten much bigger since I first started using the project at the end of 2017 and there are many more users and listeners than I ever imanginend. I think that all of AzuraCast's users and listeners should have a place to talk about the project, view and discuss updates, share stations and ideas, show off configurations and plugins, and allow users to help one another without being restricted to the topics of being a feature request or bug report. Let me know what you all think. I think this project is awesome and can really benifit from a community forum.

**Comment by SC2Mitch** [comment]
So far azuracast has a Discord which is kind of like a community place for people to talk, or a slack if you prefer that. But I highly doubt buster will want to invest in another platform to watch

**Comment by andrewfer000** [comment]
W8 whats the discord?

**Comment by SlvrEagle23** [comment]
@andrewfer000 We've actually had quite a few requests for a forum, mostly as a way to preserve knowledge and allow communication back and forth between community members without depending on some form of real-time communication and without clogging our GitHub up with more traffic.

I'm looking into some options to see if it would be something we could accomplish without too heavy of an administrative burden.

In the meantime, as Mitch mentioned, you can join our [Slack](https://azuracast.com/slack) and [Discord](https://azuracast.com/discord) communities.

**Comment by andrewfer000** [comment]
There are some great forum software out there such as SMF Forum, Discourse, PHPBB, and more. You can install and set them up right on any web server with PHP support and have a working secure forum in hours.

**Comment by Vaalyn** [comment]
Closing this as resolved since[ GH Discussions](https://github.com/AzuraCast/AzuraCast/discussions) is available for AzuraCast for quite some time already and fulfils the role of a community focused area / forum.
