### ISSUE TITLE
Change in the metadata title field.

### ISSUE THREAD

**Issue by sonidoretro** [AzuraCast/AzuraCast#2622]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu Linux 18.04.4

**Bug**
Change in the metadata title field.
Since a past update, the following is happening:
When I play the music from Azuracast
You stopped submitting the artist in the metadata title field that Icecast submits.
Previously, you sent "artist - song", now only the song title is sent.
Sending the title as: "artist - song" helps applications and players to display the information correctly. This has always been normal behavior.
This does not happen when I connect a live stream. This proves that it is a mistake.

**Expected behavior**
Sending the title as: "artist - song" 

**Relevant Logs**

**Screenshots
Now from AzuraCast music
![image](https://user-images.githubusercontent.com/63079315/78309815-addc2100-7511-11ea-9686-e947c4632c7e.png)

Expected behavior - From live stream
![image](https://user-images.githubusercontent.com/63079315/78310294-18da2780-7513-11ea-8aff-7419d155592c.png)

**

**Additional context**

**Comment by SlvrEagle23** [comment]
@sonidoretro This should not be happening, but it's not exactly clear _why_ it's happening for your installation. Our test installations (and my local one) aren't demonstrating this behavior.

If you're able to discover any underlying cause or any setting that is non-default that may be contributing to this, let us know and we can investigate further.
