### ISSUE TITLE
Not able to log in..

### ISSUE THREAD

**Issue by adonmedias** [AzuraCast/AzuraCast#2624]
Hi, Greetings.
I am trying azuracast for more than a week. I am using digitalocean droplets as server for azuracast. it was working fine for last two weeks, and all of a sudden i am not able to login today. when i login, it takes me to dashboard and i shows an error.

the following is the error.
500
Query has failed: cURL error 7: Failed to connect to influxdb port 8086: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
Client.php : 196

this is the screenshot..
![Screenshot 2020-04-03 at 14 42 32](https://user-images.githubusercontent.com/63096774/78344061-6f9a3c80-75b9-11ea-924d-772954a664d7.png)

**Comment by SlvrEagle23** [comment]
@adonmedias This error indicates that your `influxdb` service on your local machine has shut down for some reason. You may be able to connect to your server via SSH and run:

```
cd /var/azuracast
docker-compose down
docker-compose up -d
```

to restart the necessary services, which should typically resolve the problem.

If InfluxDB still won't restart, you can check its logs by running:

```
cd /var/azuracast
docker-compose logs -f influxdb
```

...and pasting any noteworthy log entries here for us to review.

**Comment by adonmedias** [comment]
@SlvrEagle23  after running the following code. i am not able to connect to my server ip address in browser...

```
cd /var/azuracast
docker-compose down
docker-compose up -d
```

![Screenshot 2020-04-03 at 15 19 56](https://user-images.githubusercontent.com/63096774/78347792-9f980e80-75be-11ea-8b56-d96f561a2a5f.png)

**Comment by adonmedias** [comment]
@SlvrEagle23 thank you for your time. I restarted the server, now it works fine.
