### ISSUE TITLE
Playlist and AutoDJ Problems

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#2627]
Hello,

Ubuntu, Docker, Updated to latest version instance.

Same on both Manual AutoDJ and other AutoDJ:

- A playlist set for yesterday, (set for 02.04.2020 - 02.04.2020) plays also today at that hour, not selected any days from the right side. (UTC of station time checked)

- if it's scheduled for "certain time and date", you can see the playlist will be played in a minute in the scheduled box but it doesn't start and shows it as played already when the time has come and another song plays from general rotationed default playlist. Also playing next don't displays a song in that playlist too. Sometimes the playlist starts with delay somehow, mostly don't start.

I'm not sure which logs to give about it. Anyone can try it at their instances too.

**Comment by SlvrEagle23** [comment]
@radiolize Closing in favor of a super-issue to discuss these types of things: #2631
