### ISSUE TITLE
Hundreds of ERROR: Attribute station must be of type App\Entity\Station errors

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2628]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu 18.4
**Describe the bug**
Our system logs are filled with hundreds of errors, we're unable to locate the exact source of the problem or station
**To Reproduce**
We're exactly unsure of how to reproduce this, we can possibly provide Admin level access to a developer to troubleshoot further, should they need it
**Expected behavior**
Show the exact station that's causing the issue or debug it further to the exact problem. 

EDIT: We might of found the exact cause,a permission error for some reason? 
**Relevant Logs**
```
[2020-04-04T01:10:56.363416+00:00] AzuraCast.INFO: Permission denied. {"file":"/var/azuracast/www/src/Middleware/Permissions.php","line":45,"code":0} []
[2020-04-04T01:10:56.949010+00:00] AzuraCast.ERROR: Attribute station must be of type App\Entity\Station. {"file":"/var/azuracast/www/src/Http/ServerRequest.php","line":186,"code":0} []
```
**Screenshots**
N/A
**Device(s):**
Windows 10, Chrome, latest. 
**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch I suspect that your installation is getting crawled by some sort of bot...while this exception sounds a little scary, it's basically just saying that the `station_id` parameter provided in a URL isn't actually a valid station. As long as you aren't seeing it yourself as a user, it's probably nothing to worry about.

**Comment by SC2Mitch** [comment]
> @SC2Mitch I suspect that your installation is getting crawled by some sort of bot...while this exception sounds a little scary, it's basically just saying that the `station_id` parameter provided in a URL isn't actually a valid station. As long as you aren't seeing it yourself as a user, it's probably nothing to worry about.

Is there any ways to protect ourselves from the constant bot crawls? Because it's coming at the thousands of errors on a almost hourly basis, making logging impossible.

**Comment by SC2Mitch** [comment]
fixed ages ago by Silver
