### ISSUE TITLE
 Music Files not loading

### ISSUE THREAD

**Issue by jbsix** [AzuraCast/AzuraCast#2629]
**Using Docker installation method**

yes

**Host Operating System**

AzuraCast 0.9.8.1 on Ubuntu 18.04

**Describe the bug**

Music files are not loading on web interface. 

**To Reproduce**

From station, music files menu: no music files displayed, only perpetual loading. 

**Expected behavior**

A few thousand files uploaded via SFTP (13 GB) which do not display on browser (tried both Chome, and Firefox) for one station (other stations work as expected) and expected behavior would be to be able to manage files from web interface, add to playlists, etc. 

**Relevant Logs**

Not sure how to identify logs...

**Screenshots**

![error-loading](https://user-images.githubusercontent.com/9286189/78417882-b95c4480-7604-11ea-949e-b6cd466b1362.jpg)

**Device(s):**
 - Browser: 
Version 80.0.3987.149 (Official Build) (64-bit)

**Additional context**

All other stations work as expected. Thanks for the help, any suggestions on how to debug?

**Comment by jbsix** [comment]
firefox web developer console: TypeError: e.data is undefined station_media-539908ba2c.js:1:225333

chrome web developer console: 
﻿
/api/station/9/files…0&current=1&file=:1 Failed to load resource: the server responded with a status of 500 ()
station_media-539908ba2c.js:1 Uncaught (in promise) TypeError: Cannot read property 'message' of undefined
    at station_media-539908ba2c.js:1

**Comment by jbsix** [comment]
FIXED BY CLEAR CACHE DOCKER COMMAND

**Comment by jbsix** [comment]
Still having issues uploading via SFTP client, files not displaying from web interface so reopening.

**Comment by m333w** [comment]
Hi,

I have the same problem 

![N|Solid](https://images2.imgbox.com/cb/1c/IdzTU7xX_o.png)

I have try to incrase the php memory limit and execution_time. Any help would be appreciated :)

I have 1325 mp3 in my `/var/azuracast/stations/../media` We can use the cli comand and import all media from the folder ? 

Something like `php /var/azuracast/www/config/cli.php azuracast:media:import` and i will import all the file in the `/var/azuracast/stations/name-of-station/media`

Best regards.

**Comment by SlvrEagle23** [comment]
@jbsix @m333w We need some log information in order to help us diagnose this issue further.

You may be able to see the logs for this issue by opening your web inspector (F12), clicking the "Network" tab in the inspector, then reloading the Music Files page and looking for a red line in the list of responses. The response should provide you with some sort of error message.

You can alternately use the System Log Viewer from the System Administration page, then view the AzuraCast application log for similar error reports.
