### ISSUE TITLE
Icecast 2.4.2 not working

### ISSUE THREAD

**Issue by Donokami** [AzuraCast/AzuraCast#263]
Hello,
I successfully installed AzuraCast with the traditionnal method, but when i tried to launch the station, i got an error:
`icecast: error while loading shared libraries: libssl.so.1.0.2: cannot open shared object file: No such file or directory`
In fact, the version of Icecast used by default on Ubuntu 16.04 LTS, is not working with libssl-dev 1.1.0f or 1.0.2g, only with 1.0.2d.
On the other hand, i compiled icecast-kh from [the github](https://github.com/karlheyes/icecast-kh), and it worked successfully.

**Comment by SlvrEagle23** [comment]
@Donokami I just did a manual traditional install, and it appears icecast is building just fine from source using the latest KH branch. It's possible that the recent switch to the newer icecast-KH branch resolved some of these issues. Are you still experiencing trouble with icecast?

**Comment by Donokami** [comment]
What do you mean by the latest Icecast-KH branch? The kh8 branch?
I've recently compiled and updated my Icecast to 2.4.0-kh8-0-g6142c43 which actually works.
Have you got a version more recent than 2.4.2?
Thanks.

**Comment by SlvrEagle23** [comment]
@Donokami I suppose what I'm asking is...is this an issue with AzuraCast itself? If you're installing an updated version of Icecast that isn't the Icecast-KH build that comes with the software, that may break critical functionality with AzuraCast and I don't recommend it.
