### ISSUE TITLE
Passing Azuracast to HTTPS

### ISSUE THREAD

**Issue by CouinCouin** [AzuraCast/AzuraCast#2630]
Hi, 

Very sorry to ask but I encounter some difficulties to reliably get the right informations to do it and it's a very unknow area for me :( 
AzuraCast "Docker" installation, on SSD1 OVH VPS, Ubuntu 18.04 Server.
We have a domain name linked to the server.

If I understand, I have to install Cerbot on the server. 

Certbot's website purpose to choose Software and System to give instructions. 

I think I should set Software to "Nginx" ? 
For the System, it purpose Ubuntu 18.04 LTS, are the instrinctions will compatible withUbuntu 18.04 Server ? 

Should I choose "default" or "Wildcard" tab ? 

Thanks for your help :) 
Couin

**Comment by Vaalyn** [comment]
The easiest way to setup HTTPS with AzuraCast Docker is the included commands to setup Let's Encrypt automatically. Take a look at [this guide](https://www.azuracast.com/developers/docker_sh.html#set-up-letsencrypt) on the website.

**Comment by CouinCouin** [comment]
Hi Dear, 

Thanks for your answer !
It was just that !
I was previously fall on a page with a link to Cerbot , which making confusing me :( 

HTTPS is enabled well now :) 

Thanks !
Couin

**Comment by CouinCouin** [comment]
Hi Dear, 

In a case of VPS reinstallation, is it needed to backup the certificate or I do nothing, and just re-create once Ubuntu + Azura installed on the new installation ? 

Thanks :)

**Comment by CouinCouin** [comment]
Hi Dear, 

I request some info's too from Let's encrypt forum, it appears that I have to backup the certificate outside from VPS before reinstall, but I don't know how to find it ?  

Do you have some tip for this ?  

Thanks :)

**Comment by Vaalyn** [comment]
You do not have to backup the cert or other parts of the Let's Encrypt files.

When setting up AzuraCast on a new VPS you just request a new cert via the command that AzuraCast provides.

**Comment by CouinCouin** [comment]
Hi, 

If "Let's encrypt" organism doesn't see it as a duplaicate (because the domain name will be the same), so it's good :) 

Thanks :)

**Comment by Vaalyn** [comment]
In general when you try to request a cert from a server that has not been authorized yet for the domain Let's Encrypt will require your server to pass a test where either you have to place a file with a specific name and content (which is generated by the tool that's interfacing with their API) in a specific publicly accessible path or create a specific DNS record. Then LE will query that path/DNS entry to check if you indeed control that domain. If everything passes the server is allowed to request new certificates. This is done automatically when using the LE command AzuraCast provides.

**Comment by CouinCouin** [comment]
Thanks for precisions :) 
Have a nice day :)

**Comment by CouinCouin** [comment]
:( Let's encrypt still disagree :( 

I have to reinstall the VPS but I'm blocked between "Nothing needed to backup" and "Wrong, it will hit the limit" 

 :(

**Comment by CouinCouin** [comment]
Hi , 

Tested this night on a second VPS + domain name . 

Ok after reinstall and re-create certificate . 

Thanks for your help :)
