### ISSUE TITLE
AutoDJ crossfade duration setting ignored/not working. 

### ISSUE THREAD

**Issue by davidkamp** [AzuraCast/AzuraCast#2632]
I noticed that the whatever I set the crossfade duration to it is still doing a much shorter crossfade.
All my tracks for testing are 60 seconds, none of them have custom crossfade (or any other) settings per track. I only have one playlist and all files within that playlist fade in roughly 1 seconds even though it is set to "crossfade duration" 20 seconds under profile/autoDJ. 

Setting the checkmark at "Advanced Manual AutoDJ Mode" (Manual AutoDJ Mode) makes all tracks crossfade according to the global setting. But I need all the other Playlist functionality of Azuracast so I can not use that setting.

Can this be fixed?

**Comment by davidkamp** [comment]
In  a nutshell the crossfade duration when using azuracast is broken - is this being looked into?
It is a major issue.

**Comment by dbeiner** [comment]
Same issue here !

**Comment by SlvrEagle23** [comment]
@davidkamp AzuraCast is following the appropriate documented API from Liquidsoap with regard to crossfade duration, fade-in and fade-out times, and it should be working as expected. If it isn't, this may be an upstream issue with Liquidsoap itself.

You may want to inquire over at the [Liquidsoap GitHub repository](https://github.com/savonet/liquidsoap/issues) and see if they're aware of any fixes for this issue. If it's something we need to change in our code, we can definitely do so.

**Comment by davidkamp** [comment]
Thanks, I just posted it in the liquidsoap github here: 
https://github.com/savonet/liquidsoap/issues/1152
Let's see if they have any ideas what the issue might be.

**Comment by davidkamp** [comment]
dear azuracast devs, one of the devs of liquidsoap asked a question for you here: 
https://github.com/savonet/liquidsoap/issues/1152

**Comment by davidkamp** [comment]
@SlvrEagle23 @dbeiner there is some prgoress on this in the thread over at the liquidsoap github: 
https://github.com/savonet/liquidsoap/issues/1152
