### ISSUE TITLE
Is there a problem with the Linode Docker image ?

### ISSUE THREAD

**Issue by WestExpress** [AzuraCast/AzuraCast#2633]
Azuracast doesn't seem to be loaded on the image

**Comment by SlvrEagle23** [comment]
@WestExpress Which image do you mean? There is a community-supported installer script, but that just installs the regular Docker installation of AzuraCast, which isn't specific to Linode.

**Comment by WestExpress** [comment]
Yes, I used the community-supported installer. But the Docker.sh and other install files did not seem to be present. I tried to manually install the AzuraCast but the script reported that it could not find a suitable configuration file - docker-compose.yml which does exist in \var\azuracast. Are there any other dependencies such as MYSQL or Apache which may need to be installed?

**Comment by WestExpress** [comment]
> Yes, I used the docker community-supported installer. But the Docker.sh and other install files did not seem to be present. I tried to manually install the AzuraCast but the script reported that it could not find a suitable configuration file - docker-compose.yml which does exist in \var\azuracast. Are there any other dependencies such as MYSQL or Apache which may need to be installed?

**Comment by WestExpress** [comment]
Resolved - reinstalled with community-supported non docker installer and manually installed AzuraCast with docker. Working fine now.
