### ISSUE TITLE
Pages Load With SSL, But Audio Doesnt Play.

### ISSUE THREAD

**Issue by ZandercraftGames** [AzuraCast/AzuraCast#2636]
**Using Docker installation method**

No

**Host Operating System**

Ubuntu 16.04

**Describe the bug**
Audio will not play over SSL, but works with plain http.

**To Reproduce**
1. Setup SSL using LetsEncrypt with NGINX/Apache2 ReverseProxy (Whatever one you use, or both)
2. Set "Enforce HTTPS" to true
3. Save Settings
4. Go to radio stations
5. Click play button
6. No audio will play

**Expected behavior**
Audio should play when using SSL.

**Device(s):**
 - Device: Desktop PC
 - OS: Windows 10 OS Version 1909 (Build 18363.752)
 - Browser: Chrome
 - Version: 80.0.3987.149 (Official Build) (64-bit) (cohort: Stable)

**Comment by ZandercraftGames** [comment]
Visiting the mount points pages over SSL returns an error 404 page:
![image](https://user-images.githubusercontent.com/28664144/78466564-65b72d00-76d0-11ea-9d52-72ffee606f5e.png)

**Comment by ogrenci01** [comment]
Hi @ZandercraftGames ;

They reported the same problem before. Please check here: #2430  #2501
