### ISSUE TITLE
"Could not parse input data." Error

### ISSUE THREAD

**Issue by callumok2004** [AzuraCast/AzuraCast#2639]
```js
var fetch = require("node-fetch")
let data = {
    streamer_username: "dj_test",
    streamer_password: "testPass",
    display_name: "Test DJ",
    comments: "testPass"
  }
await fetch("http://presenter.boun.cc/api/station/1/streamers", {
     headers: {
          "Content-Type": "application/json",
          Authorization: "Bearer hidden"
     },
     body: data,
     method: "POST"
}).then(res => res.text())
```
500
Could not parse input data.
AbstractApiCrudController.php : 137
```

**Comment by pascalla** [comment]
I am able to send the request just fine using Postman.

 This is an issue with your code, you may need to setup your javascript request with FormData.

**Comment by callumok2004** [comment]
How would I accomplish that through node-fetch? I am using NodeJS for this

**Comment by pascalla** [comment]
I'll refer you to the nodejs-fetch documentation.

https://www.npmjs.com/package/node-fetch#post-with-form-parameters
