### ISSUE TITLE
There is no editor function

### ISSUE THREAD

**Issue by livejam107** [AzuraCast/AzuraCast#2640]
Does anyone know why the edit function to be able to fade in and fade out in songs is NOT included with the AzuraCast 1-Click App at DigitalOcean. Does anyone know how to get the more up to date version with that tab available? Thanks

**Comment by SlvrEagle23** [comment]
@livejam107 We only periodically update the DigitalOcean one-click install tool, and will be updating it again shortly.

You can always follow our standard update instructions here: https://www.azuracast.com/administration/system/updating.html

**Comment by livejam107** [comment]
Damn. OK. I need it right away. I'll try with another host. Thanks

**Comment by SlvrEagle23** [comment]
@livejam107 Wait, you don't need to switch away from DigitalOcean...just update the installation that's already installed there. It's about three lines of shell code to do so, and it works just fine. See the instruction link for more info.
