### ISSUE TITLE
Is the AUTO DJ enabled to Record live broadcasts required?

### ISSUE THREAD

**Issue by AleAmla987** [AzuraCast/AzuraCast#2641]
Is the AUTO DJ enabled to Record live broadcasts required?

**Comment by SlvrEagle23** [comment]
@AleAmla987 Yes, you must have the AutoDJ enabled to record live broadcasts, because we use the AutoDJ both to handle incoming streamer connections using individual streamer/DJ accounts, and because the AutoDJ handles the broadcast recording step.
