### ISSUE TITLE
How to add tag Google Analytcs in public page of AzuraCast?

### ISSUE THREAD

**Issue by 7miguelsilva7** [AzuraCast/AzuraCast#2643]
I would like to know how to add tag Google Analytcs in public page of AzurCast?
What file have I to add tag?

**Comment by pascalla** [comment]
You can probably add them to the custom JS section on azuracast. 

System Settings > Customers Branding > Custom JS for Public Pages

**Comment by 7miguelsilva7** [comment]
> You can probably add them to the custom JS section on azuracast.
> 
> System Settings > Customers Branding > Custom JS for Public Pages

I'll try it, thanks.

**Comment by paulinhopt** [comment]
https://your-site/admin/branding

Change XXXXXXXX-X

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-xxxxxxxx-x']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

**Comment by 7miguelsilva7** [comment]
> https://your-site/admin/branding
> 
> Change XXXXXXXX-X
> 
> var _gaq = _gaq || [];
> _gaq.push(['_setAccount', 'UA-xxxxxxxx-x']);
> _gaq.push(['_trackPageview']);
> 
> (function() {
> var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
> ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
> var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
> })();

Thanks!

**Comment by 7miguelsilva7** [comment]
> https://your-site/admin/branding
> 
> Change XXXXXXXX-X
> 
> var _gaq = _gaq || [];
> _gaq.push(['_setAccount', 'UA-xxxxxxxx-x']);
> _gaq.push(['_trackPageview']);
> 
> (function() {
> var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
> ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
> var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
> })();

Thanks, it worked.
