### ISSUE TITLE
Allow DJ to connect before his show

### ISSUE THREAD

**Issue by Conor-Burns** [AzuraCast/AzuraCast#2644]
How do I enable a DJ to connect before his show starts? 

I've tried to set up two backends ( A and B ) without public interface and plugged the stream urls into a playlist for the frontend. 
This way a Dj with a program at 12:00 can connect to A at 11:30 and the playlist switches to A on 12:00. 
The second DJ then uses B to connect at 12:30 and the playlist grabs that stream at 13:00, while the first DJ disconnects somewhere between 13:00 and 14:00. 

Alternating this pattern would result in a seamless live show with alternating DJs - Where is the error in my thought process?

**Comment by Conor-Burns** [comment]
bump?

**Comment by SlvrEagle23** [comment]
@Conor-Burns Please be patient with our support team, as we are a very small team working very hard to provide support to a huge number of people in the middle of very trying times.

I'm not certain that what you're wanting to do is directly possible within AzuraCast itself without connecting directly to Icecast/SHOUTcast, which would prevent you from taking advantage of having multiple DJ accounts, determining which DJ is connected at the moment in the AzuraCast web interface, and recording/tracking live broadcasts.
