### ISSUE TITLE
Google Analytics/Tag Manager in Azuracast

### ISSUE THREAD

**Issue by aniphreak** [AzuraCast/AzuraCast#2645]
Is it possible to put Google Analytics or Google Tag Manager tag though custom branding? 
Does anyone here made this?

**Comment by aniphreak** [comment]
It kinda does work :-)

The only issue is i have duplicate tags on all external pages that Azuracast is embedded.

**Comment by paulinhopt** [comment]
go to --> https://your-site/admin/branding

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-xxxxxxx-x']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
