### ISSUE TITLE
SFTP Problem

### ISSUE THREAD

**Issue by webma5ter23** [AzuraCast/AzuraCast#2647]
Docker Installation

I made the username and password but at the time of connecting it tells me "Network error session expired to the ip" I put port 2022 and all the correct data.

Neither with the SSH Public Key

**Comment by SlvrEagle23** [comment]
@webma5ter23 From your host connection, try running:
```bash
cd /var/azuracast
docker-compose logs -f web
```
...while connecting via SFTP to try to identify any potential issues. If you see any error messages, paste them here so we can diagnose things more easily.

**Comment by webma5ter23** [comment]
No, I get some connection errors from a test radio that I have turned off, but nothing on the server.

**Comment by Vaalyn** [comment]
Are you connecting via a domain name or directly to the IP?
If you are connecting via a domain name, are you perhaps using Cloudflare?

**Comment by webma5ter23** [comment]
Yes, but I don't use Cloudflare

**Comment by webma5ter23** [comment]
Fixed, the firewall was blocking the port 2022

Thanks for your time
