### ISSUE TITLE
enhancement: add volume slider to public page on stations

### ISSUE THREAD

**Issue by Gartral** [AzuraCast/AzuraCast#265]
so while I was testing with some friends I was told "Hey, there's no volume slider on this" while they were listening to the public page. just a thought.

**Comment by SlvrEagle23** [comment]
@Gartral There actually _is_ a volume slider on the public pages; it's under the little "radio" icon that pops up at the top right once a song starts playing. This isn't as intuitive as it could be on the public page, but it mirrors the same functionality on the actual AzuraCast admin pages.
