### ISSUE TITLE
Error 500 on loading album art

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#2650]
**Using Docker installation method**

I used aunsible

**Host Operating System**

Ubuntu 16.04
**Describe the bug**

**To Reproduce**

I have the same problem like this: https://github.com/AzuraCast/AzuraCast/issues/2614

Error log:
2020/04/07 20:26:36 [error] 4254#4254: *2 rewrite or internal redirection cycle while processing "/index.php", client: xxxxxxxx, server: localhost, request: "GET /api/station/xxxxx/art/a12635dc0ef0e8d0bc0abfb1-1573313725.jpg HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxxxxxxxxxx", referrer: "https://xxxxxxxxxxxxxxxxxxxx/station/xxxxx/profile"

**Comment by SlvrEagle23** [comment]
@preterive You may need to run `./update.sh --full` to get the updated nginx configuration, but this shouldn't be a problem as long as you have the latest config file.
