### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Skyzurio** [AzuraCast/AzuraCast#2651]
Hello !

When I tried to install the module, it tells me full of error that it would not have sufficient permissions: "permission denied" as soon as it starts "azuracast_redis_1" in the docker :

![image](https://user-images.githubusercontent.com/63373376/78832818-32381380-79ec-11ea-81e2-bb8735da6a4c.png)

I tried to update all the modules of the VPS a little and nothing changes, I don't really know how to solve this problem ... Could you help me?

Cordially,

**Comment by SlvrEagle23** [comment]
@Skyzurio During the installation process, our installer will mention that if you aren't running as the `root` user, you should add your current user to the Docker group, i.e. with a command such as:

```bash
usermod -aG docker yourusername
```

...you'll then need to reboot to apply those changes before continuing with the installation process.

**Comment by medialeakz** [comment]
Hey  does anyone know what could
Be the issue the Media player on shoutcast administrator page is not Playing and how to fix it ? 

Thanks.
