### ISSUE TITLE
Possible Memory Leak?

### ISSUE THREAD

**Issue by JanieUwU** [AzuraCast/AzuraCast#2653]
**Using Docker installation method**
Yes

**Host Operating System**
Debian 10

**Describe the bug**
Memory bug, system memory seems to slowly be used up after 6-10 hours and eventually the system crashes.

**To Reproduce**
Leave server running for a few hours.

**Expected behavior**
Server to run fine with no listeners, memory use stay stable.

**Relevant Logs**
I'm not too good with Linux and used the log command, didn't really see what the error was.

**Screenshots**

https://imgur.com/GseD1Qj
https://imgur.com/g6ZtFSG

**Device(s):**
 - Device:  Desktop
 - OS: Windows10
 - Browser: Chromse
 - Version: Latest version from website using docker.

**Additional context**

**Comment by preterive** [comment]
Same Problem here

**Comment by Vaalyn** [comment]
From the `top` screenshot it looks like you have 2GB allocated for `buffer/cache` purposes. In general you can view this as memory that will be freed up if a process needs it and there is no `free` memory available. This is mostly used up by the audio files being cached by the kernel.

Have you encountered any specific error messages regarding out of memory errors?

**Comment by JanieUwU** [comment]
> From the `top` screenshot it looks like you have 2GB allocated for `buffer/cache` purposes. In general you can view this as memory that will be freed up if a process needs it and there is no `free` memory available. This is mostly used up by the audio files being cached by the kernel.
> 
> Have you encountered any specific error messages regarding out of memory errors?

Nothing so far but I tought it might because I had issues when I tried running it on a 1gb server. Ram got close to being used up and then it would crash so I thought it was going to do the same when it gets close to having no memory left.

**Comment by ogrenci01** [comment]
Hello everyone;

I have been using Ansible with Ubuntu 16.04 for a long time. It was the first time I had the same problem. RAM suddenly exhausted. I could not understand what caused this.

**Comment by Xara** [comment]
I have found a leaker but not in Azura itself but in  FTP/SFTP, it not release memory once goes inactive.
