### ISSUE TITLE
Port assignment documentation unclear

### ISSUE THREAD

**Issue by ducdigital** [AzuraCast/AzuraCast#2656]
**Using Docker installation method**
Yes

**Host Operating System**
Linux 5.6 Arch

**Describe the bug**
The nginx proxy for streaming / webdj port only accept port ending with 5 (ie. 8505, 8495). 
If the port assign for streaming (Customize DJ/Streamer Port) not ending with 5, the webDJ will not function. 

This also happen to people who enable "Use Web Proxy for Radio" without putting their port ending with 5.

This also happen if Shoutcast/Icecast not running with port ending with 5, the admin interface of ice/shoutcast is inaccessible and will result in a 404 error.

**To Reproduce**
- Activate: Use Web Proxy for Radio
- Change the DJ Stream port to 8499
- Change Shoutcast / Icecast port to 8498
- Now shoutcast/icecast in inaccessible
- WebDJ will not function

**Expected behavior**
- I think this need to be clear in the documentation of the technical choice to limit since I have to look into the nginx configuration to figure this part out.

- Any port should work in my opinion.

**Relevant Logs**
- None

**Screenshots**
- None

**Comment by ogrenci01** [comment]
Hi @ducdigital ;

The explanation about the subject is clearly stated for both installation methods. Please check it:

Docker: https://www.azuracast.com/help/docker/#use-non-standard-ports

Ansible: https://www.azuracast.com/help/ansible/#use-non-standard-ports

You can browse similar topic to use custom ports: #2430 #2501
