### ISSUE TITLE
How to change site favicon?

### ISSUE THREAD

**Issue by JanieUwU** [AzuraCast/AzuraCast#2658]
How do I change the site favicon? I'm new to using Linux, running this on a server and everything. Help is appreciated :(

Using Docker installation.

**Comment by SC2Mitch** [comment]
@JanieUwU You can change it through the `docker` containers, check this GitHub issue for more details.
https://github.com/AzuraCast/AzuraCast/issues/786

**Comment by jbsix** [comment]
@JanieUwU alternative simplified option on Admin Page / Custom Branding, copy and paste the following Custom JS for Public Pages:

```
function change_favicon(img) {
    var favicon = document.querySelector('link[rel="shortcut icon"]');
    
    if (!favicon) {
        favicon = document.createElement('link');
        favicon.setAttribute('rel', 'shortcut icon');
        var head = document.querySelector('head');
        head.appendChild(favicon);
    }
    
    
    favicon.setAttribute('type', 'image/ico');
    favicon.setAttribute('href', img);
}

change_favicon('http://pathtoimage.png');

```

**Comment by JanieUwU** [comment]
> @JanieUwU alternative simplified option on Admin Page / Custom Branding, copy and paste the following Custom JS for Public Pages:
> 
> ```
> function change_favicon(img) {
>     var favicon = document.querySelector('link[rel="shortcut icon"]');
>     
>     if (!favicon) {
>         favicon = document.createElement('link');
>         favicon.setAttribute('rel', 'shortcut icon');
>         var head = document.querySelector('head');
>         head.appendChild(favicon);
>     }
>     
>     
>     favicon.setAttribute('type', 'image/ico');
>     favicon.setAttribute('href', img);
> }
> 
> change_favicon('http://pathtoimage.png');
> ```

I tried that and changed the "change_favicon" link at the bottom to the one I want to use but it did not work?

**Comment by JanieUwU** [comment]
@jbsix did I do something wrong?

**Comment by jbsix** [comment]
to change media permanently, on docker install locate your www/web folder with .ico and navigate the path for web data: /var/lib/docker/volumes/

**Comment by SlvrEagle23** [comment]
@JanieUwU Right now, there isn't a very easy way to permanently change your favicon.ico file across your entire AzuraCast instance. This is something that's been requested as a feature and that we do plan to eventually work on.

In the meantime, you can upload your favicon file(s) onto your host machine, and then create a new file in your AzuraCast installation (likely `/var/azuracast`) named `docker-compose.override.yml` with the following contents:

```yaml
version: 2.2

services:
  web:
    volumes:
      - ./favicon.ico:/var/azuracast/www/web/favicon.ico:ro
```

You'll then need to restart your web containers (you can run `docker-compose down` and `docker-compose up -d` to do this, or just restart the entire server).

Again, this is rather complicated and we plan to have a better solution available for this at some point later.
