### ISSUE TITLE
Access to SQL

### ISSUE THREAD

**Issue by RainbowDash53** [AzuraCast/AzuraCast#266]
Hi I need to access to the SQL, can you give me a way to get the host, port, username and password please?

**Comment by SlvrEagle23** [comment]
AzuraCast uses MariaDB, which can be connected to with any common MySQL tools. For added security, MySQL doesn't expose its ports directly to the web, so an SSH tunnel into the server itself is required.

If you're using the **traditional installation**, you can connect to MariaDB using these steps:

- Username: `azuracast`
- Password can be found in `/var/azuracast/app/env.ini`
- Database: `azuracast`
- SSH tunnel into your server using your root credentials or using the `azuracast` account. The password to the latter was provided at the end of the installation. Once tunneled in, the MySQL host will be `localhost` (relative to the tunnel).

If you're using the **Docker installation**, by default Docker doesn't open up _any_ access ports to MariaDB for high security. You can spin up a "debug" instance of MariaDB for the purpose of making changes to the database using these commands in the main AzuraCast folder:

```
docker-compose down
docker-compose -f docker-compose.yml -f docker-compose.debug.yml up -d
```

Once MariaDB has spun back up, it will be available to connect via an SSH tunnel. The instructions are the same as above, except the password is hard-coded as `azur4c457`. (Yes, I know this seems insecure, but it's a product of how Docker is designed, and unless you're explicitly in this debug mode, MariaDB is inaccessible to anything except AzuraCast itself.)

**Comment by SlvrEagle23** [comment]
@RainbowDash53 Hopefully the answer above resolves your question. If you have any further questions, please feel free to create a new issue. :)

**Comment by quydox** [comment]
Password via docker installation is random for root and azuracast user :D 

You can get it by

Go to your docker container of web: via docker exec

Vim src/Environment.php

go to function getDatabaseSettings(), try to var_dump this one then die.

Then go to your admin dashboard, you will see connection. 

Remove var_dump debug.

If you want to use via phpmyadmin, you can download adminer to your web docker container

/var/azuracast/www/web => download to here, then you can access via public url

root@01121806741d:/var/azuracast/www/web# wget https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php -O db.php

then vim /etc/nginx/conf.d/azuracast.conf

add above line "location ~ ^/index\.php(/|$) {"

```
location ~ db.php$ {
                fastcgi_pass localhost:9000;
                fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $request_filename;
            include        fastcgi_params;
                fastcgi_split_path_info       ^(.+\.php)(.*)$;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PATH_INFO       $fastcgi_path_info;
fastcgi_buffers 16 16k;
fastcgi_buffer_size 32k;
    }
```

Try to kill nginx and start it
```
   86  ps aux | grep nginx
   87  killall -9 nginx
   88  ps aux | grep nginx
```

nginx will auto start again ( I think maybe a process auto start it, maybe supervisor)

Then you can access from your server, in my test is my laptop

http://localhost:8888/db.php

Thanks for azuracast :))

**Comment by SlvrEagle23** [comment]
Just as a note for @quydox and anyone else who is wanting to jump into the DB console in Docker for any reason, you can easily do so via the command line by running:

```
./docker.sh db
```

This will pull the username, password and other credentials from the environment variables and automatically launch you into the database console.

**Comment by quydox** [comment]
> Just as a note for @quydox and anyone else who is wanting to jump into the DB console in Docker for any reason, you can easily do so via the command line by running:
> 
> ```
> ./docker.sh db
> ```
> 
> This will pull the username, password and other credentials from the environment variables and automatically launch you into the database console.

Thanks, it is cool, but I think my way is cool with UI
