### ISSUE TITLE
Audio amplification applies to next audios too

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#2662]
So we have a track, I've set the amplification at 6dB to boost the track sound but when the following track plays, it automatically continues at 6dB higher instead of going back to 0dB on the next track. When you set it to 6db or made changes for some tracks and restart, still boosted tracks' settings override next songs.

Ubuntu 18, Docker

**Comment by SlvrEagle23** [comment]
@radiolize I think this may be shedding some light on some other issues we're having...it's possible that if Liquidsoap doesn't receive a new annotation for a specific value, it just uses the previous one, which causes some problems.

In the specific case of amplification, we can safely assume that 0.0 is the default, so we just send that annotation with every track to ensure Liquidsoap resets correctly.

If this same bug applies to crossfades and such, it would definitely explain some things.

Let me know if this improves the amplification issue at least.
