### ISSUE TITLE
Error when creating new Playlist

### ISSUE THREAD

**Issue by rmacari** [AzuraCast/AzuraCast#2666]
**Using Docker installation method**

yes

**Host Operating System**

Ubuntu 
**Describe the bug**

Whey i try to create a new playlist i receive an error message:
An error occurred and your request could not be completed.
After the message the playlist is created but doesn´t work and if restart the Auto DJ it will prevent the auto DJ to restart and gives the error:

Liquidsoap encountered an error
Line 22, char 0:
Warning 4: Unused variable playlist_newtestplaylist
No output defined, nothing to do.
Line 22, char 0:
Warning 4: Unused variable playlist_newtestplaylist
No output defined, nothing to do.

**To Reproduce**

**Expected behavior**

**Relevant Logs**

No error in logs

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by rmacari** [comment]
One note: If I try to modify any existent playlist it gives the same error.

**Comment by SC2Mitch** [comment]
What version are you on?

**Comment by rmacari** [comment]
updated to the last one, always.
Powered by AzuraCast <https://www.azuracast.com/> • v0.9.9, #f331a3e
(2020-04-11 4:18) • Docker • PHP 7.4

Ricardo Macari

**Comment by rmacari** [comment]
And today after updating to the newest release, I've tried again and got the error again, but tried again and it worked but the playlist doesn´t work. I ended up on that super issue too.

**Comment by SC2Mitch** [comment]
@rmacari delete the playlist and re-create it under the same name `newtestplaylist`, and make sure it's not using any Advanced settings.

**Comment by rmacari** [comment]
> @rmacari delete the playlist and re-create it under the same name `newtestplaylist`, and make sure it's not using any Advanced settings.

@SC2Mitch Did that, as i mentioned, the playlist it´s not working. :(

**Comment by SlvrEagle23** [comment]
@rmacari Is the playlist type an "Advanced" type playlist, or general rotation?

If this continues to be an issue, I'd be very curious to see what configuration is being generated by our system. You can view this via Utilities > Log Viewer > Liquidsoap Configuration.

**Comment by rmacari** [comment]
> @rmacari Is the playlist type an "Advanced" type playlist, or general rotation?
> 
> If this continues to be an issue, I'd be very curious to see what configuration is being generated by our system. You can view this via Utilities > Log Viewer > Liquidsoap Configuration.

Hello @SlvrEagle23, I´ve tried both, same output. Also, I´m trying to set a playlist to stream a direct link URL, same error, it doesn´t play at the specified time. The problematic playlist I have to remove otherwise the radio won´t start, you won´t see in the conf.  

I´m attaching the conf.

Thanks. 
[liquidsoapconf95.txt](https://github.com/AzuraCast/AzuraCast/files/4493018/liquidsoapconf95.txt)

**Comment by SlvrEagle23** [comment]
@rmacari I can't really figure out what's going wrong there...it looks to me like every playlist listed is represented in the switches farther down in the configuration.

It's possible that some of the playlist variables having names that end in underscores may be a problem, but I'm not sure if that's the case or not. You may want to try renaming every playlist that the system is currently converting into having an underscore at the end, but I'm not sure if that would help.

There are also some custom advanced Liquidsoap configuration sections in your code, and I don't know if those are contributing to the problem or not just from looking at them.
