### ISSUE TITLE
I installed azuracast today, and playlist doesn't play

### ISSUE THREAD

**Issue by darkjedeye** [AzuraCast/AzuraCast#2671]
I install azuracast, and the playlist we created, whic was just updating the default playlist, won't play at all... keeps playing the error.mp3, weather i set it to schedule or not.. i have even restarted the entire vps to check...

Please help me to fix this.

**Comment by fast97** [comment]
hello, if the error file is playing make sure the playlists are programmed if there is not a clock on it.

**Comment by darkjedeye** [comment]
hey there... i have tried it scheduled, unscheduled, have even reinstalled os fro ubuntu 18.04 back to 16.04 and having the same issue... I upload music, i enable the playlist, leave scheduling empty, and nothing... fill in the scheduling... nothing.. even changed the weight of the playlist, and nothing... only plays the error.mp3 file

**Comment by darkjedeye** [comment]
it picks up there is music... and this is how it sits. 
![Issue](https://user-images.githubusercontent.com/29452733/79139357-76456280-7db6-11ea-91c2-a29cd9e05abc.PNG)

**Comment by fast97** [comment]
try changing the port of liquidsoap or redo the account to see. as soon as the error file is read there is no reason why the playlist does not start

**Comment by darkjedeye** [comment]
hi there... i have done a fresh install on both ubuntu 16.04 and 18.04 using docker... so changing the ports is a mission and a half... this issue has been happening on 2 separate install with no firewalls in place or any iptable confilicts, all this server does is run azuracats.... has been for the past 4 years.

**Comment by fast97** [comment]
ok it's been 1 month that I use azuracast and I use debian 10 which works very well. I make all the updates available to stay up to date. I don't know how you help. how many radio you hosted on this server?

**Comment by darkjedeye** [comment]
> ok it's been 1 month that I use azuracast and I use debian 10 which works very well. I make all the updates available to stay up to date. I don't know how you help. how many radio you hosted on this server?

i have used this on a few servers... all have worked perfectly up and until now... i am affraid to update them... seems that it gets stuck on the error.mp3, is someone able to help please? if iu have to i will give admin access to system i need this fixed...

**Comment by darkjedeye** [comment]
Never mind... i messed around  bit and found  that in the logs it was havong issues with decoding the files, so i managed to replace the mp3 decoder and now working... also removed the wma files that somehow got in there too... May i ask if you guys can please add support for wma aswell...

**Comment by fast97** [comment]
I had a similar problem following an addition of music folder which had files not mp3 and which had not the good owners I modified via ftp all its and it was gone. azuracast reads wav format too.

**Comment by SC2Mitch** [comment]
> I had a similar problem following an addition of music folder which had files not mp3 and which had not the good owners I modified via ftp all its and it was gone. azuracast reads wav format too.

AzuraCast can have issues reading / playing .wave format files, due to Microsoft's proprietary software

**Comment by fast97** [comment]
> > J'ai eu un problème similaire suite à l'ajout d'un dossier de musique qui avait des fichiers non mp3 et qui n'avait pas les bons propriétaires que j'ai modifiés via ftp tout son et c'était parti. azuracast lit également le format wav.
> 
> AzuraCast peut avoir des problèmes de lecture / lecture de fichiers au format .wave, en raison du logiciel propriétaire de Microsoft

Ok but for me the waves play normally
