### ISSUE TITLE
"Advanced: Custom Liquidsoap Configuration" field in station profile missing

### ISSUE THREAD

**Issue by andrewbritton** [AzuraCast/AzuraCast#2672]
Station profile > Auto DJ tab no longer has the Custom Liquidsoap Configuration field. Has this been removed / moved?

![Screen Shot 2020-04-13 at 21 55 42](https://user-images.githubusercontent.com/20565847/79160618-ff1dc780-7dd1-11ea-9695-1b078380fc04.png)

**Comment by SlvrEagle23** [comment]
@andrewbritton Not removed, vastly expanded in fact! It's now replaced with the Liquidsoap Configuration Editor under the "Utilities" submenu, where you can view the full automatically-generated Liquidsoap configuration along with several new editable areas.

**Comment by andrewbritton** [comment]
Thanks!
