### ISSUE TITLE
Visual Cue Editor 

### ISSUE THREAD

**Issue by ghost** [AzuraCast/AzuraCast#2673]
Hey there and thanks for everything. My station is rolling like a machine and I am also now a reseller so again, thanks! Question though with regard to the edit function. I know its in beta but how can we best get it to work now? Some songs it works. Some songs it blows through and it plays the entire music file. No matter where you set the edit up. Is there or there some protocols or things I am supposed to do regarding the autoDJ? Do I trigger anything? Do I do anything after say adding songs? And, what is the best way to get the edit thing to work more than not? thanks again! Oh and also, the ONLY times it ever blows through the edit is the outro. the intro always gets met. That always works. Its only the edit outs.

**Comment by patrickvdhoek** [comment]
Are you using variable bit rate files?

**Comment by livejam107** [comment]
I should be using constant. Let me try to find that in the system admin.

**Comment by mkbradio** [comment]
Is there instructions for this and how it works I would like to try it but a bit scared to use it .

**Comment by livejam107** [comment]
I am not sure where this function is at or how I can tell. I am still searching for it and honestly, I agree..I dont wanna trip anything up on my thing too or either...But I dont think there is any instruction BTW. I am gonna make one for my new site though I am not sure how effective or great it will..flying by seat of pants in that regard....

**Comment by mkbradio** [comment]
If you go to music files and click on a show then click the blue edit button at the right hand side a box opens for you to add artwork Custom Fields etc its there

**Comment by mkbradio** [comment]
I really think an instruction video would be very useful to demonstrate exactly how to work it . I am going to try  You have to schedule a show first to get to it so i will try that but not sure about what it does my djs sometimes send shows that are overtime and if i could use it to clip them it would be great  Fade in and out and overlap im not sure how that would work ?

**Comment by livejam107** [comment]
I have this Custom Fading: Overlap Time field but its blank in the one file i opened. I never set overlapping. Just fade ins and fade outs. I do NOT see where it says whether its variable bit rate and/or a constant bit rate or how to check that on or off.

**Comment by livejam107** [comment]
For a show? You would have to go into playlist edit and then in the 4th tab, it says whether to interrupt the other playlist or show. Have you seen that function. Otherwise you would have to fade out of the last song played in that playlist into the next song in other play list. Every song in my system has edits. Its live material. we only play live music. So I have to cut out crowd noise and the artist hooting and hollering and thanking people...I want my songs to blend into each other too. For me,its hit or miss. Some songs it works. Some it does not.

**Comment by livejam107** [comment]
Regardless and overall, it kind of defeats the purpose of having an editor function if the editing feature will not work. Or, maybe its a crap shoot whether it works.

**Comment by SC2Mitch** [comment]
I believe @bjarn made this feature, might be in his area of expertise to see what might of gone wrong.

**Comment by SlvrEagle23** [comment]
Closing per #2678.
