### ISSUE TITLE
Changing custom branding breaks UI Box in Debug Logs

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2676]
**Using Docker installation method**
 Yes

**Host Operating System**
 Ubuntu 18.04

**Describe the bug**
 When you change Custom Branding CSS or any other options, it logs it successfully, but it goes outside the bounds of the box, breaking it. 

**To Reproduce**
Make a change to custom branding, check to debug logs, see the error. 

**Expected behavior**
It to remain in the box. 

**Relevant Logs**
 None

**Screenshots**
![image](https://user-images.githubusercontent.com/29955942/79234206-db09c700-7e61-11ea-9a06-5acca418d219.png)

**Device(s):**
 - Device:   Desktop
 - OS:  Win10
 - Browser:  chrome
 - Version:  latest

**Additional context**

**Comment by Vaalyn** [comment]
Closing this issue in favor of https://github.com/AzuraCast/AzuraCast/issues/1872 as duplicate.
