### ISSUE TITLE
Set up azuracast with different unused mariadb port

### ISSUE THREAD

**Issue by Panagiotis-Kontopoulos** [AzuraCast/AzuraCast#2677]
Hello,

The issue I am currently facing (searching didn't show any results) is that I am trying to install azuracast using the docker method and change the default ports for the web and mariadb (because I am having another database listening to port 3306) using the three available files .env, docker-compose.yml and azuracast.env. The docker runs on a  **Ubuntu Server 18.04** machine with **Docker Version 1.25.3**.

The changes in the files is as follows:
For the docker-compose.yml -> 
[docker-compose.yml.txt](https://github.com/AzuraCast/AzuraCast/files/4476436/docker-compose.yml.txt)

For the .env ->
[env.txt](https://github.com/AzuraCast/AzuraCast/files/4476441/env.txt)

For the azuracast.env -> 
[azuracast.env.txt](https://github.com/AzuraCast/AzuraCast/files/4476444/azuracast.env.txt)

I run the commants from the docker.sh file:
docker-compose pull
docker-compose run --user="azuracast" --rm web azuracast_install $*
On the second commant I get the error message

> Creating network "azuracast_default" with the default driver
> Creating azuracast_stations   ... done
> Creating azuracast_redis_1    ... done
> Creating azuracast_mariadb_1  ... done
> Creating azuracast_influxdb_1 ... done
> 2020/04/14 16:04:40 Waiting for: tcp://mariadb:3306
> 2020/04/14 16:04:40 Waiting for: tcp://influxdb:8086
> 2020/04/14 16:04:40 Waiting for: tcp://redis:6379
> 2020/04/14 16:04:40 Connected to tcp://influxdb:8086
> 2020/04/14 16:04:40 Connected to tcp://redis:6379
> 2020/04/14 16:04:40 Connected to tcp://mariadb:3306
> Installing AzuraCast...
> (Environment: production)
> 
> AzuraCast Setup
> ===============
> 
> Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...
>  * Environment: Production
>  * Installation Method: Docker
> 
> Waiting for dependent services to go online...
>  0/3 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
> 
>  [ERROR] Error encountered: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused
>          (/var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php L93)
> 
> 
> Setting Up InfluxDB
> -------------------
> 
> Database created.
> Retention policies updated.
> Continuous queries created.
> InfluxDB databases created.
> 
> Running Database Migrations
> ---------------------------
> 
> 
> In AbstractMySQLDriver.php line 93:
> 
>   An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused
> 
> 
> In PDOConnection.php line 31:
> 
>   SQLSTATE[HY000] [2002] Connection refused
> 
> 
> In PDOConnection.php line 27:
> 
>   SQLSTATE[HY000] [2002] Connection refused
> 
> 
> azuracast:setup [--update] [--load-fixtures] [--release]
> 
> 2020/04/14 16:05:10 Command exited with error: exit status 1

The connection to the mariadb is going through port 3306 again instead of the 3307 set in azuracast.env file and the connection is refused with the given settings. Is there a way to change the database's port or a work around for this kind of issue?

Thank you in advance!

**Comment by Vaalyn** [comment]
When using the Docker installation method you don't have to change the port mariadb runs on to be able to also install you own mariadb using the same port. This is possible because the mariadb container from AzuraCast only listens to port 3306 on the internal Docker network of AzuraCast which is not exposed to the outside.

**Comment by Panagiotis-Kontopoulos** [comment]
I tried to the same command with 3306 port and received another error. (I have another container listening to that port.)
After I run the same command I receive the same error

> Waiting for dependent services to go online...

>  0/3 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
> 
>  [ERROR] Error encountered: An exception occurred in driver: SQLSTATE[HY000] [2006] MySQL server has gone away
>          (/var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php L106)
> 
> 
> Setting Up InfluxDB
> -------------------
> 
> Database created.
> Retention policies updated.
> Continuous queries created.
> InfluxDB databases created.
> 
> Running Database Migrations
> ---------------------------
> 
> 
> In AbstractMySQLDriver.php line 106:
> 
>   An exception occurred in driver: SQLSTATE[HY000] [2006] MySQL server has gone away
> 
> 
> In PDOConnection.php line 31:
> 
>   SQLSTATE[HY000] [2006] MySQL server has gone away
> 
> 
> In PDOConnection.php line 27:
> 
>   SQLSTATE[HY000] [2006] MySQL server has gone away
> 
> 
> In PDOConnection.php line 27:
> 
>   Packets out of order. Expected 0 received 1. Packet size=72
> 
> 
> azuracast:setup [--update] [--load-fixtures] [--release]
> 
> 2020/04/16 14:15:54 Command exited with error: exit status 1

**Comment by Vaalyn** [comment]
Could you run `docker-compose logs mariadb` in the AzuraCast directory?

This will give us the log entries for the mariadb container and should give us a hint why the mariadb container is dying.

**Comment by Panagiotis-Kontopoulos** [comment]
I have uploaded the file with the output of the above command. For some reason cannot connect a user, maybe there are more settings to be configured?

[docker-compose logs mariadb.txt](https://github.com/AzuraCast/AzuraCast/files/4509666/docker-compose.logs.mariadb.txt)

**Comment by BillMeyerRSA** [comment]
I experienced a similar problem. I had another MySQL / MariaDB docker running exposing port 3306. The Azuracast Docker kept on getting stuck on the install. Disabled the other MariaDB on port 3306 and the install completed even though on the ports list the Azuracast is not exposing 3306. Guess it is a problem only during install that the port 3306 from another MySQL confuses it.
