### ISSUE TITLE
Why do you have an editor function that does NOT fade in or fade out

### ISSUE THREAD

**Issue by Dees-nutz** [AzuraCast/AzuraCast#2679]
The editor feature or fade in and fade out function never fades in or out. Whats the deal with that? that is when it works and if it works. The editor function does not work. I am NOT sure how else to say that sentence but it does not work. It some times edits out a song but it always defaults back to it not working after a few songs tops. And, the so called fade out and fade in function are non existant. That should not even be a term. There has never been a song that has ever faded in or faded out in any way using this hack of a program or what they call 'fade in' and 'fade out'...lol..its funny that it does not even fade in or fade out...but yeah, you should take down the work in progresses for gods sakes. Its a crap shoot what works and what doe snot work. The editing feature does not work. I do NOT know why its even there. take it down. It does not work. And, it never fades in or out so take out that term. its non existent.

**Comment by SlvrEagle23** [comment]
Closing per #2678 .
