### ISSUE TITLE
Passwords not work..

### ISSUE THREAD

**Issue by Berttas** [AzuraCast/AzuraCast#268]
Passwords will not work if you upgrade your passwords again .. Ubuntu 16.04 LTS and Docker

**Comment by SlvrEagle23** [comment]
@Berttas I don't understand what you mean. Do you mean the passwords to log in to the actual AzuraCast web site stopped working?

**Comment by Berttas** [comment]
The password does not work if it is updated through AzuraCast management and then notifies you that "Your credentials could not be verified."

**Comment by SlvrEagle23** [comment]
@Berttas If you still have shell access to the server and you're having trouble accessing a specific account, you can generate a new password via the command line by executing the following commands:

**For Docker installations:**

```
docker-compose run --rm cli azuracast_cli azuracast:account:reset-password your-email-address@example.com
```

**For Traditional installations:**

```
php /var/azuracast/www/util/cli.php azuracast:account:reset-password your-email-address@example.com
```

**Comment by Berttas** [comment]
Thanks.. i try that...

**Comment by SlvrEagle23** [comment]
@Berttas Did that resolve your issue?

**Comment by Berttas** [comment]
Yes this is solved...

**Comment by RadioSB2020** [comment]
Dear Sir, I have a same problem. I can log in https://a2.siar.us/login. Is my email suspend or banned? please help me, thanks

**Comment by izobretatel88** [comment]
Hello!

`docker-compose run --rm cli azuracast_cli azuracast:account:reset-password your-email-address@example.com`

When I apply the command I get "no configuration file provided: not found"

**Comment by adoboligh1** [comment]
Do you have STMP setup?

If not it means you can't use this method.

**Comment by ItsMitchh** [comment]
Open a new issue please, not one that's years old.
