### ISSUE TITLE
The Fade In and Fade Out feature Never fades in or fades out; The Editing feature DOES NOT WORK

### ISSUE THREAD

**Issue by Hugo-Fuguselev** [AzuraCast/AzuraCast#2680]
You offer this interrupt check off thing that only interrupts. It has never ever in the history of life start after the so called song or track near the start of the play list time. Why have it it if does not work? The ONLY times playlists ever work at the scheduled time is oif you check off that box and like an amateur it has to interrupt the song instead of waiting intil the end of the song to be able to start the next playlist. Again, why have it it? It does notwork.' The ONLY way to schedule anything is to interrupt the song,. say that sentence. Thats how your system works. You are trying to dodge everything when that the only way the scheduling function works. You must interrupt whatever song for any scheduled event to work. Get a grip. U R keeping everybody hanging when thats the ONLY fix. Which you know too.' say the words. It does notwork. Its pretty much a crap shoot as to work work using this acuracast thing.

**Comment by SlvrEagle23** [comment]
Closing per #2678.
