### ISSUE TITLE
How to program in a specific order several mixes on the same playlist? 

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [AzuraCast/AzuraCast#2683]
Bonjour, 

former user of centovacast servers in radio fm, I'm looking to program several mixes in a single playlist, for example, put mix 1 at 9pm, mix 2 at 10pm etc... I can see that in the playlist option, I can add a programmed schedule, but how do I program the mixes ? I can't find an option to add a song in this parameter, I hope I have explained my problem well and have an answer from you. 

![2020-04-15 18 43 29 srv dunkerquestreetradio eu cc347c56782b](https://user-images.githubusercontent.com/42807552/79365034-65c5f100-7f4a-11ea-996b-e06445675599.jpg)

Sincerely yours, 

Jordan for Dunkerque Street Radio Jeune

**Comment by SlvrEagle23** [comment]
@TechComputerServiceDunkerque You should make sure the playlist's order is specified as "Sequential", then when you click the "More" dropdown next to the playlist, you'll see a button labeled "Reorder", which will let you change the order of any tracks you've added to it so they follow a specific order, which we will then follow when playing them.

**Comment by TechComputerServiceDunkerque** [comment]
Thank you. I'm testing it now.
