### ISSUE TITLE
Implementing Multi-Site server

### ISSUE THREAD

**Issue by krono86** [AzuraCast/AzuraCast#2687]
Hello guys!
I've just realized I can use my own VPS for both azuracast and my web site.
I've already read [this](https://www.azuracast.com/extending/multisite.html#enter-azuracast-base-directory) and I understood this is feaseable in such a way.
Reading [this](https://www.azuracast.com/extending/modifying_docker.html#how-azuracast-s-docker-installation-works) I understood that nginx and mariadb are included in my docker installation.
Now the question: How can I add to nginx a new web site instance and to mariadb my own database (mysql) backup?
Thank you.

Ivan

**Comment by Xara** [comment]
Use  ansible install? huh?

**Comment by SlvrEagle23** [comment]
@krono86 Just as a minor update to your question, the "multi-site" configuration for AzuraCast has been merged into the core configuration, so now all AzuraCast installations are multi-site capable out of the box thanks to the addition of the nginx proxy.

Your question isn't a problem, it's just outside the scope of the support we provide officially for the project, so I'm leaving it open in case the community wants to assist with things.
