### ISSUE TITLE
Issue with listeners count with shoutcast

### ISSUE THREAD

**Issue by MisterSandFR** [AzuraCast/AzuraCast#2688]
Hi,

I currently have an issue with the listeners count on the api with shoutcast.

When my shoutcast server say : 1400 of 10000 listeners (213 unique)

The API only print the "unique" : "listeners":{"current":213 ,"unique":213 ,"total":213 }

Can we get the "1400listeners" in "current" like shoutcast ?

Thanks

**Comment by SlvrEagle23** [comment]
@MisterSandFR I'm investigating this and it seems that this may be caused by SHOUTcast returning this information in the API information it returns to us. Our NowPlaying adapter and the SHOUTcast frontend adapter seem to be working as intended.
