### ISSUE TITLE
Schedule Playlist Looping

### ISSUE THREAD

**Issue by sjradmin** [AzuraCast/AzuraCast#2689]
Hi,

I need to play one file at certain times of specific days and the rest of the day nothing to be played.

1- I created a playlist with the song want to play
2- Source type is "General Rotation"
3- Configured the schedule with start and end time as my start time based on this guide > "To play once per day, set the start and end times to the same value." 

It starts at the time scheduled but once finished it plays again.

Am I doing anything wrong or it's a bug?

Regards

**Comment by SlvrEagle23** [comment]
@sjradmin I've identified a possible problem that may be causing this issue and fixed it as of the latest update to the AzuraCast code base. You can update your installation and the issue should now be resolved for once-per-day playlists.

**Comment by sjradmin** [comment]
Hi,

Would you please advise on how to update to the new code? 

Just a regular update process on the guide?

Regards

**Comment by SlvrEagle23** [comment]
@sjradmin Yes, just a regular update via the instructions listed in our guide:
https://www.azuracast.com/administration/system/updating.html

**Comment by sjradmin** [comment]
Just updated and testing, now its not even playing the file on scheduled time.

**Comment by sjradmin** [comment]
it certainly not working tried few times. Do I need to restart any service after update?

**Comment by SlvrEagle23** [comment]
@sjradmin This is likely related to the super-issue of #2631 then. You'll want to reply in that thread instead.

We will need quite a bit of information to diagnose this issue, as it has been very difficult for us to reproduce on our end. Screenshots of your playlist settings are helpful, and make sure that all of the conditions listed at the top of the form are met.
