### ISSUE TITLE
Installer Issue: E:  --allow-unauthenticated

### ISSUE THREAD

**Issue by nomadturk** [AzuraCast/AzuraCast#269]
Ubuntu 16.04 LTS, 
Clean install with only SSH selected.
After and apt update && apt upgrade I tried installing AzuraCast

Right after that I was greeted with:

```
WARNING: The following packages cannot be authenticated!
  ansible
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
```

When you put --allow-unauthenticated to the second apt-get command, this fixes the problem.

**Comment by SlvrEagle23** [comment]
@nomadturk Closing this issue, as I believe it was a temporary issue with the key security for Ansible, and I haven't seen any subsequent issues relating to this after multiple installs using 16.04.
