### ISSUE TITLE
how to get the streams in the yellow directory????

### ISSUE THREAD

**Issue by master-magic** [AzuraCast/AzuraCast#2699]
my streams working very good, so now I want to put the streams on the yellow directory list, I have clicked the option in every stream to on so it may go in the yellow directory, but I don't see them in the list, do I have to do something extra to have this option working????
or do I have to wait some time to see it????

I hope someone can help, 
thanks in advance for the help with this very good project, I love it (y)

**Comment by SC2Mitch** [comment]
Yellow Directory is a Shoutcast thing, you need a YP code. Support is tricky, since it's ShoutCast.
Mount settings > 
![image](https://user-images.githubusercontent.com/29955942/79676867-1695ef80-81da-11ea-96d2-358224ac8ec0.png)

**Comment by adwinter** [comment]
@master-magic  You need to start an free account with shoutcast at https://shoutcast.com.
Once you've done that, start a new station, and once you have that setup, go into "Settings" and you will get a authorization-hash-tag, copy everything in that window (see attached screenshot).

Now that you have that, go into your Mount Point for your station in Azuracast, and EDIT it.  Check the box under *Publish to "Yellow Pages" Directories*, and then paste the autorization-hash-tag into the field called *YP Directory Authorization Hash* (see second screenshot).

Once this is done, it will take a while for Shoutcast to find it. I had to wait almost 12hrs before it got listed properly.. but if you follow the steps above -- it will become public within a day.

Support is pretty crappy -- I sent a question to those guys when I was going through this and never did get a response... Unfortunately, you do need to be patient once these settings are done -- it really is not immediate.

Hope this helps.


![shoutcast_screen](https://user-images.githubusercontent.com/20404986/79677229-d451bb80-81a3-11ea-9ea9-d2e07a212f4c.png)

![azuracast_screen](https://user-images.githubusercontent.com/20404986/79677243-0c58fe80-81a4-11ea-88cb-612e7e6e4319.png)

**Comment by master-magic** [comment]
thanks for the simpel and very good information on how to do it.
I try it if it's work here.
very very many thanks.

**Comment by adwinter** [comment]
Glad to help. Let me know if you're successful in getting it working.

**Comment by master-magic** [comment]
i have now an auth hash for my stream, but I see in AzuraCast not the option in the mount of that yellow pages to fill in the auth hash, is that because I work with Icecast and not with Shoutcast ?????

**Comment by adwinter** [comment]
Yes. That's exactly why.  If you want to make sure you are listed on Icecast, just make sure that "Publish to Yellow Pages Directories" is checked. It still will not be listed on Shoutcast.com... They only list Shoutcast streams... You will be listed however on the Icecast list here: http://dir.xiph.org/

It shouldn't take to long to get listed there... usually within 20 minutes or so.

If you really want to be listed on Shoutcast, you need to have a Shoutcast stream to connect.

Good luck.

**Comment by master-magic** [comment]
on Shoutcast I'm listed now for my 2 streams I have live, but it was strange that when it was under Icecast the streams nog been find in the Icecast yellow pages, even after 4 days, that's why I started this question here.
now it is on Shoutcast I don't change nothing anymore, that is now how I wanted it for 5 days when I started the stream.
I learn every time still :-P

**Comment by ErnestPH** [comment]
@adwinter Is it possible for a free SHOUTcast radio station to still have the auth hash? Thanks

**Comment by master-magic** [comment]
@ErnestPH i have it now for 3 free shout casts that I host by myself and it works for the 3 streams ;-)

**Comment by adwinter** [comment]
#ErnestPH Yes. I don't pay for my station at all and I'm listed no problem with an auth hash.

**Comment by adwinter** [comment]
@master-magic When I was checking my installation, I realized I wasn't listed on the Icecast directory either... I did some investigating yesterday and found that the "default" icecast.xml file that Azuracast uses lacks the necessary tags to be listed.  If you want your Icecast mount to be listed, you need to.

1. Log in to Azuracast, and click "Edit Profile".

2. Go to the "Broadcasting" Tab and enter the following under "Advanced Custom Configuration":

<location>British Columbia, Canada</location> 
<admin>somebody@somewhere.com</admin>
<directory>
<yp-url-timeout>15</yp-url-timeout>
<yp-url>http://dir.xiph.org/cgi-bin/yp-cgi</yp-url>
</directory>

Replace whats inside <location> with your location, and <admin> must contain a VALID EMAIL ADDRESS..  then make sure the directory section is copied as it is above.

3. Restart your Station.

Now I'm successfully listed using these settings. It took 10 minutes to populate onto the icecast directory list.  Hope this helps.

**Comment by adwinter** [comment]
One more thing:  Here is the page from the Icecast documentation that explains the steps and troubleshooting being listed with Icecast.  https://www.icecast.org/docs/icecast-trunk/yp/

**Comment by master-magic** [comment]
ok thanks for the info, i change it and put it in the stream page where it must been put, I gonna wait and see if it's work ;) 
fingers crossed.

**Comment by master-magic** [comment]
and after 7 min I have news, it works, now I can Shoutcast streams put in the list and Icecast streams, I still learn everyday, that makes me so happy, thanks guys for the help, it was very simple but I din't do I before so I need to learn a little.
but it works now ;)

**Comment by adwinter** [comment]
Great to hear @master-magic.  You'll never stop learning -- its kind of the nature of the beast I'm afraid. Good luck with your streams.

**Comment by master-magic** [comment]
thanks, I see now other things that not good work when I am testing, but I open therefore an other topic ;) thanks for the help here, I appreciate it.
