### ISSUE TITLE
TuneIn radio partner API

### ISSUE THREAD

**Issue by voipworld** [AzuraCast/AzuraCast#270]
Hi Azura team

we use Azura cast for a blind users community radio, its pretty accessible and a lot easyer thant others like AirTime!

can you please implement the TuneIn metadata submition API?
it should be in the station profile, to auto submit metadata to the TuneIn station profile
thanks

**Comment by daniel-j** [comment]
I have this in my radio (Liquidsoap-based like AzuraCast)
@SlvrEagle23 can use this code: https://github.com/daniel-j/parasprite-radio/blob/master/liq/tunein.liq

**Comment by voipworld** [comment]
@daniel-j awesome!
so i just insert it in my mountPoint config in azura?

**Comment by SlvrEagle23** [comment]
@voipworld First of all, thank you for using AzuraCast! Accessibility is a big concern of mine, and though I haven't had as much time to devote to improving the program's accessibility as I would like, it's great to know your community finds it useful.

For now, you can use @daniel-j's solution verbatim (he's very good at this kind of stuff) by pasting it into the "Advanced: Custom Configuration" field inside the "Configure LiquidSoap" section of the main station profile. You will also need to call that function with an `on_metadata` event, though I'm not sure the exact way to word that (maybe @daniel-j can help there).

I definitely want to support the TuneIn API. I will be working to integrate this into AzuraCast itself, so you can expect that to be implemented shortly.

**Comment by daniel-j** [comment]
I have it set to `on_track`:
```ruby
def scrobble_nowplaying(m)
  tunein.nowplaying(partner_id="PARTNER_ID", partner_key="PARTNER_KEY", station_id="STATION_ID", m)
end
source = on_track(scrobble_nowplaying, source)
```
You should put the TuneIn credentials in variables though (my radio uses a config system instead).

**Comment by SlvrEagle23** [comment]
@voipworld Update time! The new station web hook system has been built out, and the first connector to test out this new system is the TuneIn AIR API.

From any user account with the new "manage station webhooks" permission, you can visit a station's management page, click the "Web Hooks" link on the left, then create a new web hook that will automatically notify TuneIn any time your station's metadata changes.

Right now, I'm "pilot testing" this feature with the TuneIn connector, but the goal is to enable all sorts of new web hooks, like Twitter posting, Discord integration, and much more.

Try it out!

**Comment by voipworld** [comment]
gonna tryit out right now!!!!!!!!!!!!!!!!

**Comment by voipworld** [comment]
Hey..., the TuneIn Air API is fully functional!!!!!!!!!
thanks a lot dude for this greatest concept ever
now we can hook to any pipline...!

**Comment by wxmradio** [comment]
> @voipworld First of all, thank you for using AzuraCast! Accessibility is a big concern of mine, and though I haven't had as much time to devote to improving the program's accessibility as I would like, it's great to know your community finds it useful.
> 
> For now, you can use @daniel-j's solution verbatim (he's very good at this kind of stuff) by pasting it into the "Advanced: Custom Configuration" field inside the "Configure LiquidSoap" section of the main station profile. You will also need to call that function with an `on_metadata` event, though I'm not sure the exact way to word that (maybe @daniel-j can help there).
> 
> I definitely want to support the TuneIn API. I will be working to integrate this into AzuraCast itself, so you can expect that to be implemented shortly.

como lo instalo en sonicpanel
