### ISSUE TITLE
Stations going on Loop and also Stopping Streaming 🚨URGENT🚨

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [AzuraCast/AzuraCast#2700]
![image](https://user-images.githubusercontent.com/63973045/79695752-9a85c100-8246-11ea-8037-884bc487da8f.png)

**Comment by LATINMIXMASTERS** [comment]
![image](https://user-images.githubusercontent.com/63973045/79695855-20097100-8247-11ea-91ee-443c67d4bba2.png)

**Comment by SlvrEagle23** [comment]
@LATINMIXMASTERS Per our conversations on Slack, it appears this issue is largely resolved by recent updates.

**Comment by LATINMIXMASTERS** [comment]
Yes thank you lets hope continue good

Team LMM

www.latinmixmasters.com
Instagram - Latinmixmasters
Twitter- Latinmixmasters
Facebook - Latinmixmasters
Office: 908.768.0301
