### ISSUE TITLE
I don't use your software but windows wants to!

### ISSUE THREAD

**Issue by vazome** [AzuraCast/AzuraCast#2704]
When I click on controller information in Windows it leads me on your website, not the official Realtek one.
![image](https://user-images.githubusercontent.com/46573198/79733966-9ddc8380-82fe-11ea-8f4b-5c9efc6d8bd4.png)

More info in this Reddit post (video inside)
[Link to the Reddit post](https://www.reddit.com/r/Dell/comments/g4p8ba/realteks_official_link_is_unofficial/)

I use laptop DELL Latitude E7240

**Comment by Vaalyn** [comment]
I don't think there is anything we can do here.

I've tried visiting the URL from your screen capture video but only get a `ERR_NAME_NOT_RESOLVED` page. This is most likely a DNS issue on your computer or with your internet provider.
When I use `ping realtek.com.tw` to see what IP hosts the domain I get a `cannot resolve realtek.com.tw: Unknown host`.

**Comment by vazome** [comment]
> I don't think there is anything we can do here.
> 
> I've tried visiting the URL from your screen capture video but only get a `ERR_NAME_NOT_RESOLVED` page. This is most likely a DNS issue on your computer or with your internet provider.
> When I use `ping realtek.com.tw` to see what IP hosts the domain I get a `cannot resolve realtek.com.tw: Unknown host`.

I tried it with different network connections and result still the same. I will mail RealTek about this situation.

**Comment by sudofox** [comment]
Hey, I'm trying to download updated drivers for my sound card but keep ending up on azuracast's website. What's going on here?

www.realtek.com.tw resolves to 104.237.139.64 which shows an azuracast webpage

**Comment by Vaalyn** [comment]
@sudofox There is nothing that we can do for you.

The domain is registered by `Realtek Semoconductor Co., Ltd` and points to the IP you mentioned. The server using that IP seems to have our software installed which is why you see it there.

This is an issue with Realtek probably not updating their DNS entry for that domain. I can only recommend you to contact them directly about this.
