### ISSUE TITLE
A channel with one mp3 file stops streaming

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2707]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu 18.04
**Describe the bug**
I'm using a channel with only 1 short mp3 file (error message ) that should run in loop. Since the upgrade i made on Saturday (v0.9.9, #25e1ce4), i'm getting stream offline  every couple of hours. 
**On System Debugger i can see:**
Info
1 playable playlist(s) of type "default_unscheduled" found.
playlists
[
    {
        "id": 61,
        "name": "default",
        "weight": 3
    }
]
Warning
Duplicate prevention yielded no playable song; resetting song queue.
Warning
No way to avoid same title OR same artist; using least recently played song.
media_id
28539
Info
Playable track found and registered.
next_song
"StationMedia 2d807ed439a38a0ef9ed3cb6:  - error"

**and on System Logs :**
2020/04/20 04:38:01 [lang:3] AzuraCast Raw Response: 
2020/04/20 04:38:01 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/04/20 04:38:03 [playlist_default:3] Prepared "/var/azuracast/stations/c49/media/error.mp3" (RID 297).
2020/04/20 04:38:03 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/c49/media/error.mp3".
2020/04/20 04:38:03 [lang:3] AzuraCast Raw Response: 
2020/04/20 04:38:03 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/04/20 04:38:03 [lang:3] AzuraCast Feedback Response: OK
2020/04/20 04:38:05 [lang:3] AzuraCast Raw Response: annotate:title="error",duration="3.",song_id="cb5e100e5a9a3e7f6d1fd97512215282",media_id="28539",playlist_id="61":/var/azuracast/stations/c49/media/error.mp3
2020/04/20 04:38:05 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/c49/media/error.mp3".
2020/04/20 04:38:06 [lang:3] AzuraCast Raw Response: annotate:title="error",duration="3.",song_id="cb5e100e5a9a3e7f6d1fd97512215282",media_id="28539",playlist_id="61":/var/azuracast/stations/c49/media/error.mp3
2020/04/20 04:38:06 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/c49/media/error.mp3".
2020/04/20 04:38:06 [lang:3] AzuraCast Raw Response: annotate:title="error",duration="3.",song_id="cb5e100e5a9a3e7f6d1fd97512215282",media_id="28539",playlist_id="61":/var/azuracast/stations/c49/media/error.mp3
2020/04/20 04:38:06 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/c49/media/error.mp3".
2020/04/20 04:38:06 [lang:3] AzuraCast Raw Response: 
2020/04/20 04:38:06 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/04/20 04:38:06 [playlist_default:3] Prepared "/var/azuracast/stations/c49/media/error.mp3" (RID 299).
2020/04/20 04:38:06 [c49_next_song:3] Prepared "/var/azuracast/stations/c49/media/error.mp3" (RID 454).
2020/04/20 04:38:06 [c49_autodj_fallback:3] Switch to c49_cue_next_song with forgetful transition.
2020/04/20 04:38:07 [lang:3] AzuraCast Feedback Response: OK

**Comment by SlvrEagle23** [comment]
@eranwo I've updated the sync code to build the queue a little more often, which should help with problems you're having where the queue runs out because the tracks are too short.
