### ISSUE TITLE
NowPlaying API changed without notice

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#2709]
I made a mobile application which supports multiple stations and I designed it to work dynamically.
But after latest update, it seems that NowPlaying API (https://radio.com/api/nowplaying/) structure has changed so my app doesn't work anymore!
NowPlaying API used to return ArrayList from stations but now it returns Objects. 

However, the structure for /stations (https://radio.com/api/stations) works fine.
Please check and return to the previous structure.

**Comment by Vaalyn** [comment]
The JSON that the API returns does not like it has changed recently.

Can you tell us more about the structure that your app expects and where it currently differs from that? In the JSON it's returning an array of stations. How are you decoding the JSON? In PHP for example you can specify if it should be decoded as associative array or as an object.

Also what version of AzuraCast where you using when your app worked and to which version did you update?

**Comment by stardevelop** [comment]
Please compare JSON returns of https://domain.com/api/nowplaying and https://domain.com/api/stations
/stations is fine with me.

I regularly update (daily) and the current one is v0.9.9, #fb88476 (2020-04-20 6:05) • Docker • PHP 7.4

**Comment by stardevelop** [comment]
@SlvrEagle23 
My mobile application stopped working because of this change.
To reproduce the problem you need to have multiple stations.

**Comment by SlvrEagle23** [comment]
@stardevelop We haven't actually changed the NowPlaying API in quite a bit of time, but over a year ago we did change the API from something akin to:

```
{
  1: {
     station: 'blah'
   }
}
```

to

```
[
  {
    station: 'blah'
   }
]
```

...but any changes in recent months shouldn't have affected your API responses at all. If anything, we've become stricter about enforcing the proper types on the data structures represented in the API.

**Comment by stardevelop** [comment]
NowPlaying API returns:

It was until last week:
[{"station":{"id":1,"name":

But now, it is:
{"0":{"station":{"id":1,"name"

**Comment by SlvrEagle23** [comment]
@stardevelop Like I said, we haven't used the latter format (where the parent listing is an object) in many years now. If you're seeing that in your API response, then that's an error that we need to look into.

Are you hitting the standard `/api/nowplaying` endpoint?

**Comment by stardevelop** [comment]
Yes, https://stream.radio.com/api/nowplaying
It's interesting that it was working as fine  as Array but suddenly changed to object.

**Comment by SlvrEagle23** [comment]
@stardevelop I've discovered one potential case where this could happen: if you have a station that is not listed as public, it can trigger the nowplaying array to mistakenly be treated as an object instead of a numeric array.

I've fixed this as of the latest update. Update and let me know if the issue persists.

**Comment by stardevelop** [comment]
Much appreciated. Bug fixed.
