### ISSUE TITLE
Unable to launch liquidsoap

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [AzuraCast/AzuraCast#2710]
Hi, I can't start the server in DJ mode, it tells me it's running when it's not, I get the following error message: 

and it's been since the last update

Liquidsoap a rencontré une erreur
Re-raised at file "lang/lang_errors.ml", line 155, characters 48-55
Called from file "lang/lang.ml", line 671, characters 8-163
Called from file "lang/lang.ml", line 678, characters 4-76
Called from file "main.ml", line 125, characters 34-40
Called from file "main.ml", line 668, characters 6-16
Called from file "runner.ml", line 30, characters 14-31

I did a Debug: 
NowPlaying adapter error: cURL error 7: Failed to connect to stations port 8000: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

Thanks for your answer, the server administrator of our radio should add more information on the ticket.

**Comment by RazielSama** [comment]
Hi, i'm the administrator.

We are running dockerized instance on a VPS with debian 9.

**Comment by RazielSama** [comment]
You can close the issue.
I resolved it by reinstalling a bare new server and Azuracast instance.
