### ISSUE TITLE
High CPU Usage From Deleted Station

### ISSUE THREAD

**Issue by djanthonystyles** [AzuraCast/AzuraCast#2712]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04.4 LTS / 4 VCPU /16 GB RAM / 280 GB HD

**Describe the bug**
Noticed the stations "now playing" was no longer working and when all the stations crashed I took a look. Had my friend who knows more about Linux take a look. Found that azuracast_mariadb_1 was averaging constantly around 180% and 215%. Further investigation shows a station I deleted still running even tho it's not on the front end of the azuracast web. He added a max_statement_time=10 to kill slow-query over 10. This provided temporary relief but will return when I stop azuracast docker and start it back up.

**To Reproduce**
Delete a radio station and recreate it again with the same name.

**Expected behavior**
Thought when I deleted a station it's gone. Noticed when you create another station it skips a number. So if the station I deleted was 10 and create a new one it goes to 11. Station 10 seems to hang out in the database even tho its been requested to delete.

**Relevant Logs**
|  21 | azuracast | 172.18.0.6:51332 | azuracast | Query   |   70 | Sending data | SELECT COUNT(DISTINCT l0_.listener_hash) AS sclr_0 FROM listener l0_ WHERE l0_.station_id = 6 AND l0_.timestamp_start <= 1587455487 AND l0_.timestamp_end >= 1587455360 |    0.000 |
| 101 | azuracast | 172.18.0.6:52212 | azuracast | Query   |   38 | Sending data | SELECT COUNT(DISTINCT l0_.listener_hash) AS sclr_0 FROM listener l0_ WHERE l0_.station_id = 6 AND l0_.timestamp_start <= 1587455519 AND l0_.timestamp_end >= 1587455360 |    0.000 |
| 109 | azuracast | 172.18.0.6:52278 | azuracast | Query   |    6 | Sending data | SELECT COUNT(DISTINCT l0_.listener_hash) AS sclr_0 FROM listener l0_ WHERE l0_.station_id = 6 AND l0_.timestamp_start <= 1587455550 AND l0_.timestamp_end >= 1587455360 |    0.000 |
| 110 | azuracast | 172.18.0.6:52302 | azuracast | Sleep   |   20 |              | NULL                                
3 query for same station that not exist

I noticed this slow_query:
| azuracast | Query   |   55 | Sending data | SELECT COUNT(DISTINCT l0_.listener_hash) AS sclr_0 FROM listener l0_ WHERE l0_.station_id = 6 AND l0_.timestamp_start <= 1587455298 AND l0_.timestamp_end >= 1587455063 |    0.000 |

| 7237 | azuracast | 172.18.0.6:49562 | azuracast | Query   |    1 | Updating     | UPDATE listener SET timestamp_end = 1587454778 WHERE station_id = 6 AND timestamp_end = 0 AND id NOT IN (0, 3231697, 3231215, 3231699, 3231219, 3233753, 3233834, 3233955, 3233959, 3234321, 3234351, 3234362, 3234412, 3234469, 3234666, 3234972, 3235199, 3234991, 3235023, 3235037, 3235118, 3235215, 3235218, 3235290, 3235528, 3235571, 3235646, 3235755, 3235758, 3235837, 3235841, 3235850, 3235857, 3235860, 3235861, 3235876, 3235939, 3235963, 3235976, 3235989, 3236155, 3236159, 3236161, 3236162, 3236166, 3236168, 3236172, 3236175, 3236183, 3236198, 3236202, 3236208, 3236210, 3236212, 3236214, 3236221, 3236224, 3236228, 3236234, 3236237, 3236248, 3236249, 3236255, 3236273, 3236275, 3236290, 3236289, 3236293, 3236317, 3236321, 3236322, 3236333, 3236340, 3236347, 3236349, 3236479, 3236478, 3236480, 3236482, 3236484, 3236486, 3236487, 3236489, 3236492, 3236494, 3236496, 3236497, 3236499, 3236501, 3236502, 3236504, 3236503, 3236506, 3236508, 3236509, 3236512, 3236511, 3236513, 3236519, 3236514, 3236515, 3236516, 3236517, 3236518, 3236520, 3236533, 3236521, 3236522, 3236535, 3236523, 3236524, 3236525, 3236526, 3236527, 3236538, 3236528, 3236529, 3236530, 3236531, 3236532, 3236534, 3236536, 3236537, 3236539, 3236540, 3236541, 3236542, 3236543, 3236552, 3236554, 3236544, 3236545, 3236546, 3236558, 3236547, 3236548, 3236549, 3236550, 3236551, 3236553, 3236562, 3236555, 3236556, 3236557, 3236559, 3236560, 3236561, 3236563, 3236568, 3236570, 3236571, 3236564, 3236565, 3236566, 3236567, 3236569, 3236572, 3236573, 3236574, 3236575, 3236577, 3236576, 3236578, 3236580, 3236582, 3236584, 3236587, 3236586, 3236589, 3236591, 3236593, 3236592, 3236594, 3236596, 3236598, 3236600, 3236601, 3236599, 3236597, 3236602, 3236603, 3236604, 3236606, 3236607, 3236609, 3236611, 3236613, 3236614, 3236615, 3236619, 3236616, 3236617, 3236622, 3236618, 3236620, 3236621, 3236623, 3236627, 3236624, 3236630, 3236628, 3236629, 3236631, 3236632, 3236633, 3236636, 3236634, 3236635, 3236637, 3236639, 3236640, 3236641, 3236642, 3236644, 3236643, 3236646, 3236648, 3236647, 3236650, 3236649, 3236651, 3236652, 3236653, 3236655, 3236657, 3236654, 3236658) |    0.000 |
| 7255 | azuracast | 172.18.0.6:49736 | azuracast | Query   |    0 | Updating     | UPDATE listener SET timestamp_end = 1587454778 WHERE station_id = 6 AND timestamp_end = 0 AND id NOT IN (0, 3231697, 3231215, 3231699, 3231219, 3233753, 3233834, 3233955, 3233959, 3234321, 3234351, 3234362, 3234412, 3234469, 3234666, 3234972, 3235199, 3234991, 3235023, 3235037, 3235118, 3235215, 3235218, 3235290, 3235528, 3235646, 3235755, 3235758, 3235837, 3235841, 3235850, 3235857, 3235860, 3235861, 3235876, 3235939, 3235963, 3235976, 3235989, 3236155, 3236159, 3236161, 3236162, 3236168, 3236172, 3236175, 3236183, 3236198, 3236210, 3236212, 3236214, 3236221, 3236224, 3236228, 3236234, 3236237, 3236248, 3236249, 3236255, 3236273, 3236275, 3236290, 3236289, 3236293, 3236317, 3236321, 3236322, 3236340, 3236347, 3236349, 3236478, 3236480, 3236481, 3236483, 3236485, 3236488, 3236490, 3236491, 3236493, 3236495, 3236498, 3236500, 3236501, 3236502, 3236503, 3236505, 3236507, 3236510, 3236511, 3236513, 3236514, 3236515, 3236516, 3236517, 3236518, 3236520, 3236521, 3236522, 3236523, 3236524, 3236525, 3236526, 3236527, 3236528, 3236529, 3236530, 3236531, 3236532, 3236534, 3236536, 3236537, 3236539, 3236540, 3236541, 3236542, 3236543, 3236544, 3236545, 3236546, 3236547, 3236548, 3236549, 3236550, 3236551, 3236553, 3236555, 3236556, 3236557, 3236559, 3236560, 3236561, 3236563, 3236564, 3236565, 3236566, 3236567, 3236569, 3236572, 3236573, 3236574, 3236575, 3236576, 3236578, 3236579, 3236581, 3236583, 3236585, 3236586, 3236588, 3236590, 3236592, 3236594, 3236595, 3236597, 3236599, 3236602, 3236603, 3236605, 3236608, 3236610, 3236612, 3236614, 3236615, 3236616, 3236617, 3236618, 3236620, 3236621, 3236623, 3236624, 3236625, 3236626, 3236628, 3236629, 3236631, 3236632, 3236633, 3236634, 3236635, 3236637, 3236638, 3236640, 3236641, 3236643, 3236642, 3236645, 3236647, 3236649, 3236651, 3236652, 3236654, 3236656, 3236658, 3236659, 3236660, 3236661, 3236662, 3236663, 3236664, 3236665, 3236666, 3236667, 3236668, 3236669, 3236670, 3236671, 3236672, 3236673, 3236674, 3236675, 3236676, 3236677, 3236678, 3236679, 3236680, 3236681, 3236682) |    0.000 |

**Screenshots**
![6DQZUl](https://user-images.githubusercontent.com/64068105/79844370-931b0080-8389-11ea-978c-51acdbc8d14d.png)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@djanthonystyles I've made a minor code change that should improve how deleted stations are removed properly from the system, but in the meantime, restarting your `stations` container should resolve this issue for you. The easiest way is to restart all containers via the host with this command:

```bash
cd /var/azuracast
docker-compose down
docker-compose up -d
```

...a routine update will also accomplish this.

**Comment by djanthonystyles** [comment]
@SlvrEagle23 Thank you! That seems to work.
