### ISSUE TITLE
If a playlist X interrupts a normal playlist A, the last played track of playlist A will play again after X has elapsed.

### ISSUE THREAD

**Issue by rolradio** [AzuraCast/AzuraCast#2713]
**Using Docker installation method**

Yes
**Host Operating System**

Ubuntu 18
**Describe the bug**

**To Reproduce**

1291/5000
I am testing the playlist functions and trying to describe the things that don't work well.

If a playlist (X) with the option to interrupt the current song from a regular rotation playlist (A) has no advanced options, after the time for playlist X has elapsed, the song that was interrupted by playlist X will always be played first.

Further options for playlist X
- Sequential order
- Start time: every day from 4:00 pm to 4:59 pm
- Advanced options: interrupt the song at the time, and play playlist only once.
Playlist X has 2 songs, a short station ID of 28 seconds and a program of 46 minutes and 34 seconds
The playlist time of X is therefore 2 minutes longer than the 2 MP3 that are in the playlist.

Those 2 minutes should therefore be filled by the next playlist (A) whatever he does, but he will therefore play the last song played before playlist X was started.

**Expected behavior**

Here the interrupted song (from playlist A) should be considered played and removed from the songs azuracast will play next.
For clarity After playlist X, the normal playlist A returns. As it is meant to be.
**Relevant Logs**

I hope I have outlined the situation clearly.

**Comment by rolradio** [comment]
Nobody using this feature apparently?

**Comment by rolradio** [comment]
@SlvrEagle23 
Hello Sir,
This problem has not yet been looked at unfortunately.
Is this correct, or am I doing something wrong?

**Comment by SlvrEagle23** [comment]
@rolradio This is a very specific scenario that only happens when you have one playlist using Liquidsoap's scheduling and another using AzuraCast's. I'm aware of this issue, but in the grand scheme of "triage" it ranks low in priority as this isn't expected to be a widespread use case.

**Comment by rolradio** [comment]
@SlvrEagle23
 Unfortunately, this description is more common than expected.
Just think of a short news update to be played on the hour, with the option interrupt the previous playlist.
If the message is then played, it is of course very annoying that the last played song before the news update comes back after the news.

But I understand that this is not the top priority at the moment.
But it is the only way to get a certain program to start at the right time, and not to wait for the playing MP3 to finish.

Or am I seeing that wrong?

**Comment by rolradio** [comment]
@SlvrEagle23    I'll repeat where we left off in a previous conversation.
Hi,

I will try to put Mary's problem here on my side.
The problem is that many pre-recorded programs are played on certain hours
and certain days, with the advanced option interrupt the previous current
playlist.
That usually goes well, but sometimes it does not.
But very often, and that is perhaps the biggest problem, the name of that
program as mp3 is not displayed in azuracast, while it does play the
program.
This usually remains the name of the last MP3 played.

A second problem is that Mary has many playlists, with external source url
as playlist.
Dropouts often occur here, even though the buffer time is set at 120
seconds.

I understand that this is annoying, as a small host we are powerless.
I have been using azuracst for several years now, and I see it more and
more as a great panel, which leaves other stream panels far behind.

Unfortunately, the extensive scheduled playlists cannot be used optimally
now.

I would like to continue working to solve the problem, by describing things
well. So that it can be further investigated.

**Comment by SlvrEagle23** [comment]
@rolradio If you have a playlist that interrupts other tracks, that's where you go "off the rails" so to speak with regard to the AzuraCast AutoDJ. It has no idea that the interrupting track is coming, and doesn't really know how to handle it since it isn't a playlist that it manages.

I'm curious to discover that these problems are only starting now, as our issues with remote URLs (which we are working upstream with Liquidsoap to resolve) and with interrupting playlists have both existed for quite a long time now.

If you're using a multitude of Liquidsoap AutoDJ features, you may want to enable "Manual AutoDJ Mode" which will put Liquidsoap in charge of the entire process, at the expense of losing the "next song" capability and having to reload Liquidsoap any time playlists are added/removed.

**Comment by rolradio** [comment]
@SlvrEagle23 
Indeed, the problem with playlists with an external source as URL has been around for some time.
But I did not know if this was already known to you, so I reported it again.

I try to follow the forum well, but sometimes I miss something.

I'm going to run some tests with the AutoDj on manuel.
Not really aware of this, but I'll try to figure that out.

Thanks for the message.

**Comment by rolradio** [comment]
@SlvrEagle23 

Hi Sir,
In many cases interrupt a playing song is very important. Think of an hour-long pre-recorded show.
It should start exactly at the hour and not let the playing song play until the end. Because then, in a bad case, the show would start 3 minutes late.

Now my question is, can't the interrupt function just be done by azuracast AutoDj, without having to use the Advanced function? These functions do not work in combination with the azuracast AutoDJ.

In Mary's case, disabling those advanced features has brought some peace of mind with the azuracast panel.
Only the problem above remains.
