### ISSUE TITLE
Password prompt for sftp user with public key 

### ISSUE THREAD

**Issue by atomtm** [AzuraCast/AzuraCast#2715]
Hello ! 
using `sshfs -p 2022 -o allow_other,default_permissions,IdentityFile=/home/atomtm/.ssh/id_rsa.pub atomtm@mystation.org:/ /home/atomtm/sftp.mystation` I am trying to mount the station's media folder. 
I have set up the public keys for the user `atomtm` however , whenever I try to mount I get the password prompt . Is there something I can do about this ?
I am using the Docker installation on Ubuntu Server 18.04.4

**Comment by SlvrEagle23** [comment]
@atomtm On the connecting end, you authenticate with the private key, not the public key. The public key is the one that the receiving server has and uses to validate your private key.

**Comment by atomtm** [comment]
Same happens when I provide the private key @SlvrEagle23. Again the password prompt appears. 
I have also restart the ssh service with same results

**Comment by esturniolo** [comment]
Hi guys. Sorry for bring to life an old issue, but I've the same problem here.
I create my SFTP user in the web front and I put my public key. However it forces me to put a password when I created it.

So, the I try to connect:
`sftp -P 2022 -i .ssh/my_private_key user@123.123.123.123`
`user@123.123.123.123's password:`

It has no sense...
