### ISSUE TITLE
Nginx reverse proxy

### ISSUE THREAD

**Issue by john-Azura** [AzuraCast/AzuraCast#2718]
Hi All,

My current setup consists of a nginx reverse proxy that serves nextcloud and plex media server.
In a ubuntu docker I have installed azuracast which for some reason refuses, probably do not know how to configure it properly, to work with reverse proxy. I can see the site and the stream working in my internal network but it does not work from when I try to connect from my external ip(via reverse proxy). 

It seems that the site loads without 'static' images and scripts.

I would appreciate any thoughts or working configs.

Kind Regards,
John

**Using Docker installation method**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by CodeSteele** [comment]
Currently AzuraCast actually sits behind an Nginx reverse proxy by default, we base our nginx proxy off of jwilder's nginx-proxy container for managed reverse proxy services.

https://github.com/AzuraCast/docker-azuracast-nginx-proxy

It's hard to tell _exactly_ what is missing but adding a 2nd nginx proxy hop should not be a problem. I'd say to start by checking traffic between your reverse proxy and jwilder's nginx proxy that we use.

Ideally the best setup would be to use a multi-site install setup here: https://www.azuracast.com/extending/multisite.html
