### ISSUE TITLE
AzuraCast accessibility report

### ISSUE THREAD

**Issue by voipworld** [AzuraCast/AzuraCast#272]
hello Azura team

the following report detail the accessibility status of the AzuraCast playout platform web ui, and its usage with screen readers
1. there's a header on top of the page containing what i called the global navbar
that's a good job, so no need to logout & logoff or go to home page to administer the global system, but you need to put your <ul> element in a <nav> element, and give it "role=navigation"
2. after the header, there's an aside
this aside contain the radio channel administration navbar, it must be similar to the one on top (in header), and should be inside the aside if you want to keep it
3. the main view, that contain  the requested page like media Manager
that should be inside of a "main" element, with role="main"
note
a page like "settings" or channel profile that contain several section, should better be devided by several "asides", every one of them contain the part and with a title (header1,2,3,4,5./...) on top of the aside.
if the main view header is "2", then the next headers all should be 3

side note
reason for using this layout is to facilitate keyboard navigation for screen reader users, for example
if i am in home page, and want to switch to the main view to read channel status
all i do is to press the "R" 3 times
1. baner.
2. nav
3. main view
in this case "R" stand for "region"
done
or simply press the "T" one time, to go to the title "header" of the main view
i can do html, but not well in css. otherwise i would be pretty glad to have a pull request...
thanks guys for this powerfull software!

**Comment by SlvrEagle23** [comment]
@voipworld Thank you for taking the time to write this up. Fortunately, our stylesheet is quite flexible with these types of things, so switching to the HTML5 elements for `<section>` and `<nav>` and adding HTML5 `role` attributes is actually quite simple.

I've added the various semantic roles to the global template and to the pages that have multiple panels in them (and thus multiple regions). Please let me know if this helps!

**Comment by voipworld** [comment]
Hello
If i upgrade using docker, will i have any issue?
I have it runing in a digitalOcean droplet, i can upgrade it right now...

**Comment by voipworld** [comment]
Update:
HTML5 is pretty awesome in the pages now, working perfectly
now there's i think one issue only, in the pages that manage
MountPoints & users, playlist, and anywhere we can "Add", the "Add
button" is not labeled
the screen reader see sometime a link without label, and sometime a
link with something like "MountPoint/Edit",  "Playlist/Edit"
thanks for the modification!

**Comment by SlvrEagle23** [comment]
@voipworld This should now be fixed as well. I have added the button role to all of the button-like links you mentioned, along with title attributes that indicate they add a new item.

**Comment by voipworld** [comment]
hello,

i can ensure you tyhat everything is accessible now

there's no single issue detected at all

buttons working, the pages is panelised


thanks a lot !

**Comment by SlvrEagle23** [comment]
@voipworld Excellent! Thank you for letting me know what I can do to help improve accessibility. If you encounter any specific issues in the future, feel free to create new issues here on the repo.
