### ISSUE TITLE
Can i change the fallback time?

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#2721]
Hi,

When a DJ is streaming live and there is no output from the live DJ, the autodj kicks in automatically with an fade. Is it possible to chagne somewhere the time (in ms for example) before the autodj takes it over?

**Comment by lovelaced** [comment]
I'm wondering this as well - is there a configuration option that can be set somewhere for this? Some of my DJs don't have pristine connections and it's really jarring to listeners.
