### ISSUE TITLE
Error 500 : Installation was successful but account creation failed.

### ISSUE THREAD

**Issue by esmondgh** [AzuraCast/AzuraCast#2722]
**Using Docker installation method:**
Yes

**Host Operating System:**
Ubuntu 18.04

**AzuraCast Version:**
0.9.9

**Error Description:**
After a successful fresh installation, I try to create a Super Administrator account. I entered my E-mail Address and Password and when I hit the CREATE ACCOUNT button, I got the below error.

![azuracast_error](https://user-images.githubusercontent.com/42568091/80078126-ff3e6580-853d-11ea-96c3-0a5d7093b953.jpg)

**Comment by CouinCouin** [comment]
Hi, 
I already got the same thing. 
Ok after runing again 
./docker.sh install
