### ISSUE TITLE
Web DJ Not Working

### ISSUE THREAD

**Issue by mevaka** [AzuraCast/AzuraCast#2723]
Can you look at demo page, because Web Dj is not working. I tried it on my own server too but not working. 2 days ago , it was working but now , not. Do you know why ? To see what, you can look at demo page here https://demo.azuracast.com/station/1/profile

**Comment by davy39** [comment]
Hello, 
I cannot connect nether like I've reported here #2616 .
I cannot connect to webDJ or connect Mixxx to port 8005, to my own install or the demo done.
I'm free to help debugging, but actually don't know where to start.
Thanks for your time.

**Comment by CodeSteele** [comment]
By default the demo has the streamer system disabled, with the streamer system disabled WebDJ is also disabled (kind of makes sense).
