### ISSUE TITLE
Bug: Playlist Enable/Disable

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#2724]
When I change Playlist type from Remote URL to Song-based, normally I restart Liquidsoup to get the change applied.
But it's a few day that when I try to restart LS, I get the following error and the station goes offline.

Liquidsoap encountered an error
st be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2020/04/23 16:47:57 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2020/04/23 16:47:57 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2020/04/23 16:47:57 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
init: exception encountered during start phase:
Error while trying to bind server/telnet socket: Address already in use in bind()

----------
Restarting the station doesn't get the station back online.
I just need to restart the server to fix the problem.

**Comment by stardevelop** [comment]
It seems that the problem relates to any type of Playlist.
If I Enable/Disable a Playlist then LS can't be restarted and the station goes offline.

**Comment by stardevelop** [comment]
@SlvrEagle23 
Still the problem persists.
While restarting LS after enabling/disabling a Playlist, I get this error and Stream goes offline:

Liquidsoap encountered an error
st be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2020/04/26 21:53:11 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2020/04/26 21:53:11 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2020/04/26 21:53:11 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
init: exception encountered during start phase:
Error while trying to bind server/telnet socket: Address already in use in bind()

**Comment by SlvrEagle23** [comment]
@stardevelop I'm not able to reproduce this issue locally. No matter how I restart the station (either via Restart Broadcasting or via the Restart button on the station's profile) it doesn't leave the station with a reserved port.

Are you on the Docker installation or Ansible?

**Comment by stardevelop** [comment]
I am on Docker installation.

To reproduce the problem:
1) Create two Playlists. One Playlist with a Remote URL and another one a Song-based Playlist.
2) Make sure Remote URL Playlist is Enabled and the other one is Disabled.
3) Restart AutoDJ Service (Liquidsoup) to make sure the station is playing Remote URL Playlist.
4) Now, disable Remote URL Playlist and Enable Song-based Playlist.
5) Restart AutoDJ Service (Liquidsoup) and you will see this error:

Liquidsoap encountered an error
st be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2020/04/26 21:53:11 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2020/04/26 21:53:11 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2020/04/26 21:53:11 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
init: exception encountered during start phase:
Error while trying to bind server/telnet socket: Address already in use in bind()

The station goes offline and you need to manually restart Docker-compose or restart host server.

**Comment by stardevelop** [comment]
@SlvrEagle23 
I updated to v0.10.1, #bc34f02 (2020-04-28 0:43) • Docker • PHP 7.4 but this issue is very critical and persists.

**Comment by stardevelop** [comment]
Still the problem persists.

**Comment by SlvrEagle23** [comment]
Testing this locally since it seems like a quite bizarre issue that I'm having trouble reproducing...it seems that when Liquidsoap shuts down in some circumstances, it's leaving an active connection open on its telnet port that's a process running under `sh`.

This is the output of `netstat -tulpn` after Liquidsoap is shut down, but while it's failing to spin back up because the port's already in use:

```
tcp        0      0 0.0.0.0:8014            0.0.0.0:*               LISTEN      1000       5003/sh
```

I can confirm that after some timeout period the above connection finally terminates and the Liquidsoap station can be restarted after that period.

**Comment by SlvrEagle23** [comment]
Filed upstream as savonet/liquidsoap#1192 so we can investigate further.

**Comment by ttodua** [comment]
Recently faced the same issue. As SlrvEagle23 said, I confirm. When editing any LQ config and "Restart station to apply changes", then if i restart LQ also (from profile) within several seconds, then it gives that error. If i wait a while, the manual restart works.
