### ISSUE TITLE
Custom JS does not accept html tags ? 

### ISSUE THREAD

**Issue by CouinCouin** [AzuraCast/AzuraCast#2726]
Hi :) 

As well as I would curious visitors been redirected automaticly to the webradio website, I add some code in CSS and JS areas of System Administration / Custom Branding

CSS : 
```
#modalContainer {
    background-color:rgba(0, 0, 0, 1);
    position:absolute;
    width:100%;
    height:100%;
    top:0px;
    left:0px;
    z-index:10000;
    background-image:url(tp.png); /* required by MSIE to prevent actions on lower z-index elements */
}

#alertBox {
    position:relative;
    width:560px;
    border:1px solid #666;
    background-color:#fff;
}

#modalContainer > #alertBox {
    position:relative;
}

#alertBox h1 {
    margin:0;
    font:bold 0.9em verdana,arial;
    background-color:#3073BB;
    color:#FFF;
    border-bottom:1px solid #000;
    padding:2px 0 2px 5px;
}

#alertBox p {
	font-family: Verdana, sans-serif; 
    height:25px;
    padding-top:10px;
	text-align:center;
}

#login-form {
	visibility:hidden;
}
```

JS : 
```
var annul = 0;

if(document.getElementById) {
    window.alert = function(title,txt) {
        createCustomAlert(title,txt);
    }
}

function createCustomAlert(title,txt) {
    d = document;

    if(d.getElementById("modalContainer")) return;

    mObj = d.getElementsByTagName("body")[0].appendChild(d.createElement("div"));
    mObj.id = "modalContainer";
    mObj.style.height = d.documentElement.scrollHeight + "px";

    alertObj = mObj.appendChild(d.createElement("div"));
    alertObj.id = "alertBox";
    if(d.all && !window.opera) alertObj.style.top = document.documentElement.scrollTop + "px";
    alertObj.style.left = (d.documentElement.scrollWidth - alertObj.offsetWidth)/2 + "px";
    alertObj.style.top =  -50 +(d.documentElement.scrollHeight - alertObj.offsetHeight)/2 + "px";
    alertObj.style.visiblity="visible";

    h1 = alertObj.appendChild(d.createElement("h1"));
    h1.appendChild(d.createTextNode(title));

    msg = alertObj.appendChild(d.createElement("p"));
    msg.innerHTML = txt;

    alertObj.onclick = function() { removeCustomAlert();return false; }

    alertObj.style.display = "block";
}

function removeCustomAlert() {
	annul = 1;
    document.getElementsByTagName("body")[0].removeChild(document.getElementById("modalContainer"));
	document.getElementById('login-form').style.visibility = 'visible';
}

function gotosite() {
	if (annul == 0 ) {
	window.location.replace("https://eurodance90.fr");
	}
}

alert('Accès privé','Vous allez être redirigé vers le site de la radio dans quelques secondes...');
setTimeout(gotosite, 3000); 
```

Works fine. If no clic on the advert, visitors is redirected to the radio website

I would change my message ('Vous allez ... seccondes...') for a table with the website logo and message, JS modification, at the end :  
`
alert('Accès privé','<table border="0" cellpadding="0" cellspacing="0"><tr><td><img src="https://eurodance90.fr/img/logos/logo.png" height="50" width="auto"></td><td>Vous allez être redirigé vers le site de la radio dans quelques secondes...</td></tr></table>');`

I save changes, and I still get :
`alert('Accès privé','Vous allez être redirigé vers le site de la radio dans quelques secondes...');`

(If a change the message, the message is saved well but not the table/tr/td/img tags).

Any idea ?  
Thanks :)
Couin

**Comment by CodeSteele** [comment]
Putting HTML into an alert popup is not valid JavaScript.

You can generate HTML using jQuery and embed it, something like:

```javascript
$(function() {
$(".public-page")
	.empty()
	.text("Vous allez être redirigé vers le site de la radio dans quelques secondes...");
});
```


And you get something like this:

![image](https://user-images.githubusercontent.com/31152835/80340702-20999d00-882f-11ea-8477-cd835ea86298.png)


Basic, but easy.

**Comment by CouinCouin** [comment]
Hi Dear, 

The "alert" function of the code I put is not the classic JS alert function but replaced by a nicer pop up :)
Here is the actual result :
![alert](https://user-images.githubusercontent.com/62549730/80365890-9847e600-8888-11ea-808b-2a4ae17307ae.jpg)
I would just add the radio website logo :)

Thanks
