### ISSUE TITLE
Play 1 song from each playlist in a rotation

### ISSUE THREAD

**Issue by painor** [AzuraCast/AzuraCast#2727]
Hey, so let's say I have 3 playlists A, B, C ideally I'd want to play one song from A then one from B then one from C and then loop back to A forever (shuffling each time from the playlists) 

A and B and C don't need to have the same number of songs.

I've tried various combos like having play every 1 song or 2 songs or 3 songs and tried putting all playlists to the same weight but when checking the Song Playback Timeline it's obvious that the order is random (for my case it was A, A, B, A, C, C. playlist A had the most songs in it)

Editing Liquidsoap Configuration might help but I didn't want to touch that and break stuff before asking for help.

**Comment by SlvrEagle23** [comment]
@painor The easiest solution to accomplishing this would be to make all of the playlists advanced playlists (see our [Advanced Playlists guide]() for more info), then using the `Utilities` > `Edit Liquidsoap Configuration` section to add custom configuration, add something like:

```
special_playlists = rotate(weights=[1,1,1], [playlist_a, playlist_b, playlist_c])
fallback(track_sensitive=false, [special_playlists, radio])
```
