### ISSUE TITLE
NGINX proxy and cache

### ISSUE THREAD

**Issue by sognev** [AzuraCast/AzuraCast#2729]
Using Docker installation method
Host Operating System: Debian 10

Device(s):

Hi there. 
I have a few questions. I have a website on my web server. Wordpress is running on this server and running Azurecast on another port (8080). Through the NGINX proxy server, I transmit requests that come to the specified address and everything works. But I have a problem with displaying information about the playing composition and its cover. They are not updated. The song reaches the end, another starts to play (the stream does not stop), but the information, time and cover remain different until I reload the page. Help configure through a proxy server. 
PS. I use Cloudflare for the site, but I turned off proxying through it but it did not help.

**Comment by CodeSteele** [comment]
Ideally the supported configuration we suggest is to stick that Wordpress site in a docker container and follow the AzuraCast multi-site docker installation setup: https://www.azuracast.com/extending/multisite.html
