### ISSUE TITLE
azuracast docker wants to open all ports 8000-8999. how do i not have it do that?

### ISSUE THREAD

**Issue by MothGirlMusic** [AzuraCast/AzuraCast#2732]
**Using Docker installation method**
yes

**Host Operating System**
ubuntu

**Describe the bug**
launching the web app container attempts to tell iptables to open all ports 8000-9001 and then fails when it can't do that and simply just doesnt spin up as a result.

**To Reproduce**
1. install using script
2. launch.

**Expected behavior**
one or two ports would be expodsed for a stream and web app.

**Screenshots**
<img width="880" alt="Screen Shot 2020-04-24 at 11 44 49" src="https://user-images.githubusercontent.com/1746550/80231228-16a24f00-8621-11ea-8beb-cd2e22b78286.png">

**Device(s):**
 - Device: server 
 - OS: ubuntu server edition

**Comment by pascalla** [comment]
I believe you can modify the docker-compose.yml file to reduce the amount of ports to open.

**Comment by MothGirlMusic** [comment]
That’s reasonably done but still begs the question which ones do I “need” open? I’d imagine port 80 but that’s not even being allocated. 8080? It seems to complain about a random port every time it’s booted. Does the software choose a port at random? I’m sorry I’m just so confused by this and why something like this would be in the litteral official repository

**Comment by pascalla** [comment]
Azuracast is a suite built to run multiple stations. To my knowledge each stations can use upto 3 ports just for broadcasting one station.

- DJ/Streamer Port
- Internal Request Processing Port
- Broadcasting Port

At a minimum you would need Port 80, and a port for each of these. Even then i'm not too sure what other networking may happened behind the scenes.

I am unfamiliar with the interface you are seeing and have ever done installation via CLI.

**Comment by MothGirlMusic** [comment]
This is all CLI. The GUI is just portainer web end to let me view stuff. I’m installing through cli proper though.

**Comment by SlvrEagle23** [comment]
@MothGirlMusic To answer your question, the following ports are used for the following purposes:

- 80 and 443 (by default), required for web interface
- 2022, optional for accepting incoming SFTP connections for media management

Stations are provisioned with a 10-port range for each station. Not all 10 ports are currently in use, but this gives a wider availability for future internal use. You'll notice a repeating pattern of ports per station:
 - 8xx0 is the listener connection endpoint
 - 8xx5 is the incoming DJ connection endpoint for newer DJ software
 - 8xx6 is the incoming DJ connection endpoint for SHOUTcast 1 DJ software compatibility

All of the 8xx0 ports are also mirrored on 80/443 via our "Web Proxy" feature, which relays all traffic from the radio broadcast ports through the main web port to avoid firewall and SSL certificate issues.

If you don't have DJs connecting to your station and are just broadcasting through the web proxy feature, then _none_ of the ports that are opened are needed other than 80, 443, and optionally 2022 for SFTP.

@pascalla is correct that you can just edit your main `docker-compose.yml` file and remove those port assignments if they aren't useful in your scenario.

**Comment by MothGirlMusic** [comment]
Wow! That was exceedingly helpful and informative. Thank you so much! That clears up all the questions I had!!

**Comment by SlvrEagle23** [comment]
Happy to help!
