### ISSUE TITLE
Proxy Stream

### ISSUE THREAD

**Issue by andrewyv** [AzuraCast/AzuraCast#2733]
Hi

The stream for proxy is in this layout: ip/radioname/8000
Because i use AzuraCast for one station, i was wondering it possible to have the link without the station port, only the radio name, like that: ip/radioname

**Comment by pascalla** [comment]
This would require changing the nginx config yourself. However I believe this would get overwritten everytime you update Azuracast. 

I found some similar issue that may be able to help you

https://github.com/AzuraCast/AzuraCast/issues/1727

**Comment by CodeSteele** [comment]
Closing this being as the provided information should stick you on the right path.
