### ISSUE TITLE
Trying to get file path from the API

### ISSUE THREAD

**Issue by Octavelscx** [AzuraCast/AzuraCast#2735]
Hi, I'm trying to get the full path of the current file playing with the API.

I'm not sure how to do but I first tried from the api interface at the
**"GET /station/{station_id}/files"** line with the _Execute_ command but nothing's happening.
I tried with the **" GET /station/{station_id}/file/{id}"** line too with the ID of a file that I get from the now_playing json file but same, nothings happen.
(I created and logged with my API key before click on execute.)
Please excuse my english I tried my best.

Thanks a lot.

**Comment by Octavelscx** [comment]
Ok I find the solution, sorry

**Comment by Octavelscx** [comment]
I'm reopenning issue because I would like to know the best way the get the path of current file playing.

I know that I can get the path from _/api/station/{station id}/files_ or _/api/station/{station id}/files/{id}_ but my problem is the **id** of the song, _/nowplaying/_ isn't returning this **id**.

So the only solution I found is to get the song name currently playing from _/nowplaying/_ or the song_id (the long one) and make a research with this name or **id** in _/api/station/{station id}/files_ to get the right id and then the path.
Is there a simpler way to get the path ?
Thank you

**Comment by SlvrEagle23** [comment]
@Octavelscx As of the latest update, you can now directly locate a file with a specific media unique identifier or song ID by using the same `GET /api/station/(id)/file/(file_id)` endpoint. This should solve the problem you're looking to solve without resulting in any additional changes to the largely stable NowPlaying API.
