### ISSUE TITLE
buffer stops loading

### ISSUE THREAD

**Issue by diaverso** [AzuraCast/AzuraCast#2736]
**Using Docker installation method**

Yes
**Host Operating System**

Ubuntu 18.04 Server
**Describe the bug**

When you are playing the music with the link https://grupodeasalto.com/radio/8000/radio.mp3?1587126739/
In the forum, after a while the buffer stops

Video link: https://www.youtube.com/watch?v=uz03FWGVwSU
Forum Link: https://plataoplomo.es/foro/index.php
**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by CodeSteele** [comment]
Going to need logs from your browser at the very least, due to the lack of required information I'm going to close this for now.
