### ISSUE TITLE
Stream interruptions

### ISSUE THREAD

**Issue by Zcarx** [AzuraCast/AzuraCast#2738]
Hello dear Azuracast team and all forum members,

I've been doing several Azuracast installations these days. All of them on different hosters, different VPS etc, but unfortunately I have the same problem on all of them. 

When live streaming (no AutoDJ), the connection is disconnected at irregular intervals for all listeners. Then you either have to press stop and start again or reload the page.

I've already tried to fix the problem with different settings (no HTTPS, web proxy on/off etc), but without success. 

In Chrome, in the browser console the following error is displayed when the connection is interrupted:
Failed to load resource: net::ERR_CONNECTION_CLOSED
With other settings the error changes to
GET net::ERR_CONNECTION_CLOSED 200

There are no errors in the icecast logs.

Can anyone help me with this problem?

Best wishes and thank you for your time and effort
Marvin 

**Using Docker installation method**
Yes

**Host Operating System**
Debian 10

**Describe the bug**
Failed to load resource: net::ERR_CONNECTION_CLOSED
GET net::ERR_CONNECTION_CLOSED 200

**Comment by SlvrEagle23** [comment]
@Zcarx Are you using CloudFlare in front of your installation? It's a known issue that CloudFlare doesn't like long-running HTTP connections to stay open indefinitely as it's a drain on their resources, so they'll frequently set timeouts that cut listeners off.

**Comment by Zcarx** [comment]
> @Zcarx Are you using CloudFlare in front of your installation? It's a known issue that CloudFlare doesn't like long-running HTTP connections to stay open indefinitely as it's a drain on their resources, so they'll frequently set timeouts that cut listeners off.

Hey SlvrEagle23, thank you for your reply.
I am not using Cloudflare in front of my installation.

**Comment by CodeSteele** [comment]
I had a host complained of the same issue when demoing AzuraCast and doing some DJing himself, couldn't reproduce it on my system though, tried to chalk it up to some problem on his end causing AzuraCast to think the DJ session ended.

@Zcarx do you have any logs from Icecast and Liquidsoap around these times? Is this happening to multiple DJs? What software are they DJing with?

The 200 connection closed suggests that a TCP connection is closed, probably on the end of IceCast, but we'd have to know why.

Can you also try the latest version (0.10) where we updated to the latest IceCast upstream.

Thanks

**Comment by Zcarx** [comment]
Hey @CodeSteele, thank you for your reply!

 I'm sorry, I don't have any more log files from that time because somewhere in the internet it said that you should delete too big log files to fix problems :'D after I deleted the docker log the errors seemed to be fixed at least on one of my instances. But because the next live stream was one day later, a network problem at my hosts site can't be excluded.

For DJing the programs LadioCast, Butt and Mixxx are used.

Thanks for the hint with the update, I will try to update my instances. 

At this point I would like to thank you for your work on Azuracast. Nice that you developers can be reached here so uncomplicated. The software helps us all to stay connected despite Corona. When this is all over I will see if I can organize an appropriate donation.

Many greetings
Marvin

**Comment by polp6880** [comment]
@Zcarx I'm facing the same exact issue. Did updating to the latest version solve it for you please?

@SlvrEagle23 I am running behind CloudFlare but I'm only using them for DNS management - the proxy status is turned off. Would this also produce the timeouts mentioned?

Thanks!

**Comment by Zcarx** [comment]
@polp6880  At least the error occurs less frequently now.  Unfortunately I can't determine exactly what the reason for this is (updates, deleting logs, larger VPS), because I made all these changes at the same time.  However, because of the big irregularity I guess that it is due to the host.  One Saturday evening I had the problem 5 times within one hour.  The following Sunday I had no problems for 4 hours although I hadn't changed anything at all.

**Comment by polp6880** [comment]
@Zcarx thanks for replying. I decided to go ahead and update to v0.10.2 and that seems to solve the disconnecting issue I was having, which is exactly the same as you describe above.

**Comment by CodeSteele** [comment]
The thing that gets me: I don't remember anything in any recent changes to change any of that, @SlvrEagle23 you know of any changes?

I'm pondering if it's just a fluke and people are having some possible issues with their VPSes/traffic/low tolerance for drops (that was a major difference I've had with my tests, I'm on a local net with my instance).


Can anyone reproduce this with a local instance? Or only remote ones?

**Comment by polp6880** [comment]
@CodeSteele I don't have a local instance I can test. The only remote instance I have is installed on a DigitalOcean droplet. When I was monitoring the streams before the update, I used to get drops every 3 - 6 minutes so they were easy to spot. 

I did the update 2 days ago and immediately noticed that the drops did not happen at all. I spent all day monitoring the streams again yesterday, playing for as long as 4 hours straight and the drop did not happen once.

It should not make any difference but just in case it does, I was doing my tests directly from TuneIn - both app and web page.

**Comment by radiolize** [comment]
Same issue happens here too. Dropouts happens once-twice in a day. I am also running behind CloudFlare but only using for DNS management, the proxy status is turned off.

**Comment by polp6880** [comment]
@radiolize are you running the latest version? As mentioned above, I saw a big difference after upgrading.

**Comment by radiolize** [comment]
Will be running an update this night, the instance is very close to latest update but will give it a try, thank you.

**Comment by polp6880** [comment]
@radiolize happy to help ;) v0.10.2 solved the obvious disconnects that I was getting every few minutes.

**Comment by andrescerda1979** [comment]
Hi, sorry my bad english.
Look configuration Icecast : 
<paths>
        <alias source="/" dest="/status.xsl"/>
        <ssl-private-key>/etc/nginx/ssl/ssl.key</ssl-private-key>
        <ssl-certificate>/etc/nginx/ssl/ssl.crt</ssl-certificate>
 </paths>
Looking at the log and following the route, I realized that it did not exist : /etc/nginx/ssl/ssl.key.
looking at the azuracast certificate paths for the domain associated with my installation 👍 
/var/lib/docker/volumes/azuracast_letsencrypt/_data/ssl.key
and /var/lib/docker/volumes/azuracast_letsencrypt/_data/ssl.crt.

replace that parameter by adding it in : Azuracast : Administration -> Station-> Edit ->transmition -> Custom advanced personalized  add :
<paths>
<ssl-private-key>/var/lib/docker/volumes/azuracast_letsencrypt/_data/ssl.key</ssl-private-key>
<ssl-certificate>/var/lib/docker/volumes/azuracast_letsencrypt/_data/ssl.crt</ssl-certificate>
</paths>

Momentary solution, but it works for now.

**Comment by s7ntax** [comment]
I have found this issue only seems to affect ios listeners in the browser. I'm wondering if it's an ios or browser issue. No problems on laptops. I was listening to other users on my setup play live on my iphone and it was disconnecting, but on my mac, no problem at all. Sometimes on ios though it is solid, it seems to be hit and miss. strange and difficult to diagnose.
