### ISSUE TITLE
After latest update to support Ubuntu 20.04: setrlimit(RLIMIT_CORE): Operation not permitted 

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2740]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu 18.04 
**Describe the bug**
Docker logs after the latest patch seem to be producing Operation Not Permitted related errors, this is only happening on the latest update, I've searched around and it may be related to this? https://github.com/sudo-project/sudo/issues/42
**To Reproduce**
Run on the latest patch https://github.com/AzuraCast/AzuraCast/commit/e47c8f91c11884e010a8fde7fee169026b412f97 and check over your docker container logs `docker-compose logs -f`
**Expected behavior**
The operation to be permitted, or to ignore the error entirely. 
**Relevant Logs**
web_1       | sudo: setrlimit(RLIMIT_CORE): Operation not permitted

**Screenshots**
None. 

**Device(s):**
 - Device:  Desktop
 - OS:  Windows 10
 - Browser:  Chrome
 - Version:  Canary. 

**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch Should be fixed as of latest update.
