### ISSUE TITLE
Code nowplaying

### ISSUE THREAD

**Issue by Reaktiv4** [AzuraCast/AzuraCast#2741]
To display information in the site page, you need to add?

```html
<script>
var nowPlayingTimeout;
var nowPlaying;

function loadNowPlaying() {
    $.ajax({
        cache: false,
        dataType: "json",
        url: 'http://your-azuracast-site.example.com/api/nowplaying/station_shortcode',
        success: function(np) {
            // Do something with the Now Playing data.
            nowPlaying = np;

            nowPlayingTimeout = setTimeout(loadNowPlaying, 15000);
        }
    }).fail(function() {
        nowPlayingTimeout = setTimeout(loadNowPlaying, 30000);
    });
}

$(function() {
    loadNowPlaying();
});
$('#nowplaying-song').text(np.now_playing.song.text);
</script>
````

Page
`<div id="nowplaying-song"></div>`

or something else?

It does not show me anything. Styles prescribed for div

**Comment by SlvrEagle23** [comment]
@Reaktiv4 This example code is incomplete. You should still implement extra code to display the results in your web page, and update the URL to reflect your installation and your station's "short name" (which is just the name in lower case and with underscores instead of spaces, like `test_station`).

**Comment by Reaktiv4** [comment]
URL of course I enter my shortcode. But what other additional code is coming? Maybe there are examples?

**Comment by CodeSteele** [comment]
I mean that's going to vary depending on your site/needs/etc. it's a very open-ended operation so it's hard to give _useful_ examples. 

The bit of code at the bottom: 

`$('#nowplaying-song').text(np.now_playing.song.text);`

Is an example of how to take an element with the ID `nowplaying-song` and put the song text into the element.
