### ISSUE TITLE
redis (azuracast_redis) container won't start: can't open docker-entrypoint.sh: Permission denied

### ISSUE THREAD

**Issue by emmanuelproulx** [AzuraCast/AzuraCast#2744]
**Using Docker installation method**
Yes

**Host Operating System**
CentOS 8 running on Google Cloud VM.

**Describe the bug**
I've installed Azuracast with Docker 2 weeks ago.

I must say that I'm quite surprised this stopped working. It was working very well. All I did was reboot the host after adding a user to a Linux group.

After restarting, two docker containers stopped working. One of them is redis (image azuracast/azuracast_redis:latest). 

I googled this issue and the only thing I found is to check for this file's permissions. So I sh'd into the instance and looked at the permissions on this file, and they have executable permissions for all:

`$ docker-compose run redis sh
/data # ls -l /usr/local/bin/docker-entrypoint.sh
-rwxrwx--x    1 root     1002           377 Aug  2  2019 /usr/local/bin/docker-entrypoint.sh`
which looks fine to me.

**To Reproduce**
1. Install Azuracast with Docker.
2. Reboot the host with `sudo shutdown -r 0`
3. Look at the logs for the redis container

Alternatively, you can run the service manually with:
`sudo docker-compose up redis`

**Expected behavior**
The redis container should start without error.

**Relevant Logs**
```
redis_1     | /bin/sh: can't open '/usr/local/bin/docker-entrypoint.sh': Permission denied
```

**Screenshots**
None

**Device(s):**
Irrelevant

**Additional context**
I noticed that the Docker image did not change for a long time so this isn't due to a recent change. I also tried deleting the image and recreating it. I'm at a loss wrt the cause of the error.

**Comment by CodeSteele** [comment]
My recommendation would be to start with destroying/recreating the container:

```
docker-compose stop redis
docker-compose rm redis
docker-compose up -d
```

The last Redis image update was 8 months ago so I doubt it's that.

**Comment by emmanuelproulx** [comment]
Unfortunately, I had already tried that and it didn't work. I tried it again today and it still didn't work.

**Comment by CodeSteele** [comment]
Hmm try this:

```
docker-compose stop redis
docker-compose rm redis
docker image prune
docker-compose up -d
```

That should prune the redis image and re-pull it, if that works, do the same for MariaDB.

**Comment by emmanuelproulx** [comment]
I've just tried this now, and got the same result. If you want I can grant you access for you to have a look. I can contact you directly?

**Comment by emmanuelproulx** [comment]
If you want to check it out directly on my machine, contact me at:
proulxemmanuel at g mail

**Comment by emmanuelproulx** [comment]
Today I did a docker-compose pull (which downloaded the latest version) and all of a sudden this started working again. No idea what was changed. Mariadb was still broken (issue #2734). So in the end it was not a duplicate issue.
