### ISSUE TITLE
What is "unique" in the number of listeners?  

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#2745]
It's really just a question. Sorry if it's a duplicate or obvious. In this example, 9 listeners out of which 7 are unique. What makes a listener unique? 

![image](https://user-images.githubusercontent.com/28865986/80285904-6f104400-8728-11ea-8004-8f6c5d5af9df.png)

**Comment by SC2Mitch** [comment]
Unique listeners are ones that are connected through different IPs / different machines. Two listeners are listening to the same stream.

**Comment by SlvrEagle23** [comment]
@gammaw In our case, it's a combination of listening IP and user agent.

There are cases where one IP is shared among many users, so we don't just want to count the IP as a unique listener, but since User Agent strings are often just slightly different from user to user (and they're about the only other identifier we have for listeners), we hash the two together and use that to determine a listener's 'uniqueness'.

**Comment by gammaw** [comment]
@SlvrEagle23 thanks. What exactly is a user agent and what is the user agent string? When I test it by listening to the stream on two devices from behind the same router/modem, the unique count is incremented by two. I cannot reproduce incrementing only the listeners count where  the unique remains the same.

**Comment by SlvrEagle23** [comment]
@gammaw It's a unique identifier for a specific browser on a specific version and platform. It varies from device to device and browser to browser. A lot of good information about it is available here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

**Comment by gammaw** [comment]
@SlvrEagle23 sorry to bother you with this again but I still don't quite get what this all mean in practice. I guess I get the theory part but can you name one or two situations where there are two listeners but only one is counted as unique? 
We see very often that the unique listener count is considerably lower than the total number of listeners but I can't imagine what user situations can lead to this.

**Comment by Vaalyn** [comment]
@gammaw Take for example 2 people listening to a stream from their work computers. Both are setup exactly the same way for example via group policies so they have the exact same browser version and OS. Let's take Chrome 74 which has the User-Agent string `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36` this string will be the same for both listeners so the resulting hash from their work IP address + User-Agent will be the same so they are not unique and should be counted as 1 unique listener.

**Comment by gammaw** [comment]
@Vaalyn thanks! That was kind of my guess, but the naming of the two counters confused me. Ideally, unique would mean for me the number of "real" listeners. For example, if I stream from my phone and also from my desktop machine, that would be 2 listeners but only 1 unique. But I see that it's impossible/not easy to implement.
