### ISSUE TITLE
Station Suddenly Started To Seem Offline But It's Actually Streaming

### ISSUE THREAD

**Issue by radiolize** [AzuraCast/AzuraCast#2747]
Hello

Docker, Ubuntu

One of our stations suddenly seems like not broadcasting both icecast and autodj but it's actually streaming. Only users can't see it, both superadmin and permitted user.

The error at browser's inspect:

> GET https://s31.radiolize.com/api/station/17/profile?_=1587888517036 500
> send @ jquery-220afd743d.min.js:2
> ajax @ jquery-220afd743d.min.js:2
> loadProfileData @ profile:400
> (anonymous) @ profile:413
> e @ jquery-220afd743d.min.js:2
> t @ jquery-220afd743d.min.js:2
> setTimeout (async)
> (anonymous) @ jquery-220afd743d.min.js:2
> c @ jquery-220afd743d.min.js:2
> fireWith @ jquery-220afd743d.min.js:2
> fire @ jquery-220afd743d.min.js:2
> c @ jquery-220afd743d.min.js:2
> fireWith @ jquery-220afd743d.min.js:2
> ready @ jquery-220afd743d.min.js:2
> B @ jquery-220afd743d.min.js:2

Error when you click it and same as seen on Azuracast Logs:

> Unexpected data found. Unexpected data found. Trailing data
> FactoryTrait.php : 214

**Comment by Reaktiv4** [comment]
I confirm, there is no sound. Same problem.

**Comment by Reaktiv4** [comment]
It seems to work, in itself .. A strange glitch ..

**Comment by CodeSteele** [comment]
Is that the entire log? I'm missing context, as far as I can tell `FactoryTrait.php` isn't our code, that's from Chronos, a time management lib we rely on. Let me know if you can reproduce this on 0.10.

**Comment by cristianocarrozzi** [comment]
Same issue here. I opened that issue a couple days ago with no answer.  #2610

**Comment by CodeSteele** [comment]
@cristianocarrozzi looks like possibly a different issue, this is a 500 error being thrown by some server-side code where as #2610 looks like some kind of mixture of a status check mismatch and the scan taking the server offline for some reason.
