### ISSUE TITLE
Missing file ? RoutingMiddleware.php

### ISSUE THREAD

**Issue by CouinCouin** [AzuraCast/AzuraCast#2749]
Hi, 

I'm curiously looking logs and I see sometimes in /var/azuracast/www_tmp/app.log :

> AzuraCast.WARNING: Not found. {"file":"/var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php","line":93,"code":404} []

But I don't know what it is. 

I have the same error on another VPS/AzuraCast .

Thanks :)
Couin

**Comment by CodeSteele** [comment]
Technically just some log cleanup, expected behavior, _maybe_ a warning is a bit high (maybe an INFO log?), tossing to @SlvrEagle23 to review/change as he sees fit.

**Comment by CodeSteele** [comment]
@SlvrEagle23 took a look at it and is happy with the warning log, so we're good.

**Comment by CouinCouin** [comment]
Hi Dear, 

I I have not to warning about this, no problem so :) 

Cheers !
