### ISSUE TITLE
Changing http port breaks liquidsoap logs

### ISSUE THREAD

**Issue by replayfactory** [AzuraCast/AzuraCast#275]
Hi there, 

I need to move AzuraCast HTTP port to host a website. I changed nginx config to listen port 81 intead of 80 and open it in ufw. Azuracast fontend works great on a different port but liquidsoap log is now only flooded with same entry :

`2017/11/08 18:10:41 [lang:3] AzuraCast Raw Response:`
`2017/11/08 18:10:41 [lang:3] AzuraCast Raw Response:`
`2017/11/08 18:10:41 [lang:3] AzuraCast Raw Response:`
`2017/11/08 18:10:42 [lang:3] AzuraCast Raw Response:`
`2017/11/08 18:10:42 [lang:3] AzuraCast Raw Response:`

Is there any configuration to do to fix this issue ?
Many Thanks

note : Traditional Installation on Fresh Ubuntu server 16.04 LTS

**Comment by SlvrEagle23** [comment]
@replayfactory That's definitely valid. I missed it being an issue on traditional installs because Docker installs always still offer an "internal" connection using the same ports, no matter what your external port mapping is. I'll work on a fix and have it published shortly. :)

**Comment by SlvrEagle23** [comment]
@replayfactory The URL that Liquidsoap uses when making API calls will now take into account any custom port specified for the system's base URL. Try that out and let me know how it works for your situation.

**Comment by replayfactory** [comment]
@SlvrEagle23 Thanks for your blazing fast reply! I just updated AzuraCast but unfortunally, it still not working in my case. Just to be sure, by "system's base URL" you mean the _Station Web Site URL_ variable located in _Station Profile_ page setup ?

Here is my azuracas setup :
• Station Web Site URL : test.dev:81
• nginx block : listen 81; server_name test.dev;

Website setup:
• only a test index.php echoing an 'it works!'
• nginx block : listen 80; server_name test.dev

Liquidsoap log :
`2017/11/09 10:05:53 [decoder:3] Method "MAD" accepted "/home/replay/radio/music/testsong...`
`2017/11/09 10:05:53 [lang:3] AzuraCast Raw Response: it works!`
`2017/11/09 10:05:53 [request:3] Nonexistent file or ill-formed URI "it works!"!`
`2017/11/09 10:05:53 [lang:3] AzuraCast Raw Response: it works!`
`2017/11/09 10:05:53 [request:3] Nonexistent file or ill-formed URI "it works!"!`

I also tried the same setup with subdomains instead of changing ports with the same results.
• azuracast.test.dev azuracast
• test.dev for the website

Am I missing something ?

**Comment by SlvrEagle23** [comment]
@replayfactory Sorry, I mean the system base URL as set in the "System Settings" page from the Administration section of the page. That refers to the base URL of azuracast itself, whereas the station's URL is a public-facing URL you can advertise on station broadcasts.

**Comment by replayfactory** [comment]
@SlvrEagle23 Works Perfectly! on differents ports and differents subdomains. Thanks for this great project !
