### ISSUE TITLE
Multiple Domain Support (Let's Encrypt)

### ISSUE THREAD

**Issue by vincentsalim** [AzuraCast/AzuraCast#2750]
hello I have a problem with ssl azurcast i want to install ssl for 3 domains for example the first domain abcd.com domain 2 is bcde.com and domain 3 is ghi.com but why only the last domain created can be accessed with ssl while domains 1 and 2 cannot be accessed

I really hope that this problem can be solved
best regard's
vincent salim

**Comment by CodeSteele** [comment]
This isn't actually a configuration we currently support, so logged as an enhancement.

**Comment by CodeSteele** [comment]
Added here: https://features.azuracast.com/suggestions/90707/multiple-domain-support-lets-encrypt

Closing here
