### ISSUE TITLE
🚨🚨STATIONS ALL DOWN 🚨🚨

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [AzuraCast/AzuraCast#2753]
**Using Docker installation method**
 YES 

**Host Operating System**
 UBUNTU 18.04.2

**Describe the bug**
 ALL STATIONS DOWN SERVER IS UP BUT NOTHING RUNNING AND NOT RESPONDING 

**To Reproduce**

**Expected behavior**

**Relevant Logs**

Last login: Sun Apr 26 11:23:00 2020 from 162.212.159.12                                                     
entered into CT                                                                                              
root@LMMRADIOS:/# lsb_release -a                                                                             
No LSB modules are available.                                                                                
Distributor ID: Ubuntu                                                                                       
Description:    Ubuntu 18.04.2 LTS                                                                           
Release:        18.04                                                                                        
Codename:       bionic                                                                                       
root@LMMRADIOS:/# cd /var/azuracast                                                                          
root@LMMRADIOS:/var/azuracast# ./docker.sh update                                                            
curl: (6) Could not resolve host: raw.githubusercontent.com                                                  
The docker-compose.yml file has changed since your version. Overwrite? This will overwrite any customizations
 you made to this file? [Y/n] y                                                                              
./docker.sh: line 139: docker-compose: command not found                                                     
./docker.sh: line 140: docker-compose: command not found                                                     
mv: cannot stat 'docker-compose.new.yml': No such file or directory                                          
Error response from daemon: remove azuracast_www_data: volume is in use - [42adbed2ea5f438ad350439fd0ad10067b
70eb424f2634cd69fd7d3c1ec0eb44]                                                                              
Error response from daemon: remove azuracast_tmp_data: volume is in use - [42adbed2ea5f438ad350439fd0ad10067b
70eb424f2634cd69fd7d3c1ec0eb44, 231532bdfe49f8f4afc0af79354777136bbe15788b1c7506a0019e4d56133ceb]            
Error response from daemon: remove azuracast_redis_data: volume is in use - [a94398d6f7faf7fb4e0315211c03d3e9
0fd19e4d18e31da071fcaebe4473a6e5]                                                                            
./docker.sh: line 160: docker-compose: command not found                                                     
./docker.sh: line 161: docker-compose: command not found                                                     
Update complete!                                                                                             
root@LMMRADIOS:/var/azuracast# ./docker.sh restore path-to-backup.zip                                        
Restoring will remove any existing AzuraCast installation data, replacing it with your backup. Continue? [Y/n
] Y                                                                                                          
./docker.sh: line 239: docker-compose: command not found                                                     
./docker.sh: line 240: docker-compose: command not found                                                     
./docker.sh: line 241: docker-compose: command not found     

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by LATINMIXMASTERS** [comment]
![IMG_20200426_120714](https://user-images.githubusercontent.com/63973045/80313228-9104d780-87b7-11ea-9e74-992fc73addff.jpg)

**Comment by LATINMIXMASTERS** [comment]
![15879180378708180937634091817150](https://user-images.githubusercontent.com/63973045/80313350-69fad580-87b8-11ea-9f7a-4efd094aaff4.jpg)

**Comment by SC2Mitch** [comment]
Can you at least bother to fill out the format to give me some information at least

**Comment by LATINMIXMASTERS** [comment]
Sorry did not see that form when putting the items... i only see to put the
issue so thats what i did.. i cannot even see anything i try to put as much
info llease check again.

UBUNTU 18.04.2
Docker
Please help nothing responding

Team LMM

www.latinmixmasters.com
Instagram - Latinmixmasters
Twitter- Latinmixmasters
Facebook - Latinmixmasters
Office: 908.768.0301

**Comment by SlvrEagle23** [comment]
@LATINMIXMASTERS This is entirely caused by something going wrong on your server's end. Did you recently attempt a different update (not of AzuraCast, but of your operating system itself)?

The system's reporting that `docker-compose` isn't installed at all, which means something happened to it, since we definitely install it during our installation process.

You can try manually re-downloading it:
```bash
curl -fsSL https://github.com/docker/compose/releases/download/1.25.3/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
curl -fsSL https://raw.githubusercontent.com/docker/compose/1.25.3/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose
```

...then run the routine update again.

**Comment by LATINMIXMASTERS** [comment]
Thank you i fond out was an Dos Attacks and server was blocked so the issue
gkt resolved. Thank you again.

Team LMM

www.latinmixmasters.com
Instagram - Latinmixmasters
Twitter- Latinmixmasters
Facebook - Latinmixmasters
Office: 908.768.0301

**Comment by SlvrEagle23** [comment]
@LATINMIXMASTERS That doesn't make any sense at all, that a DoS attack would cause `docker-compose` to fail to resolve correctly on your host, but okay!

As a note for future issues, you absolutely must refrain from using this 🚨🚨🚨 emoji and the words "URGENT" in your issues, then approaching us on multiple social channels simultaneously and essentially demanding that we drop what we're doing to help resolve your issue.

We are not here to provide personal tech support for your AzuraCast installation. I realize this sounds unkind, but it's true; I cannot be fielding emergencies from every station that uses AzuraCast or I will have no time whatsoever to work on the actual software, or to have a personal life at all. This is not fair to me as a developer, and not a good use of my time.

Always make sure to back up your installation before running large updates, and preferably enable VPS/VM level backups of your entire machine for easier restoration.

**Comment by LATINMIXMASTERS** [comment]
Well i have contacted the server provider tbey told me tbe blocked server
to prevent more attacks after they unblocked started working fine and
docker started working again i am not expert on this if you can help me to
prevent this from happening again will be awesome.

Team LMM

www.latinmixmasters.com
Instagram - Latinmixmasters
Twitter- Latinmixmasters
Facebook - Latinmixmasters
Office: 908.768.0301

**Comment by LATINMIXMASTERS** [comment]
I put the emoji not for me just for you to look i taught somethjng happened
bigger i know you guys are busy , i dont expect to drop anything for no one
, if you see alert emojis make you eye look at that post easily but ok wont
put them. Hope i get more information about the attacks and how to prevent
this things from happening again.

Team LMM

www.latinmixmasters.com
Instagram - Latinmixmasters
Twitter- Latinmixmasters
Facebook - Latinmixmasters
Office: 908.768.0301

**Comment by SlvrEagle23** [comment]
@LATINMIXMASTERS Again, we can't provide you with any information on how to stop DDoS attacks from happening on your server because we aren't your server administrators or hosting provider. We don't know what your infrastructure is set up like beyond AzuraCast.

For this issue, you created an "URGENT" GitHub issue with flashing light emojis, you DM'ed me on Twitter, and you directly mentioned me on Slack. You interrupted what I was doing and made my phone go off multiple times, so yes, you absolutely were insisting that I drop what I was doing and assist you right that moment.

For future issues, do not do ANY of that.
