### ISSUE TITLE
IceCast becomes frozen after AutoDJ is shut down, stuck in a Freeing Memory state

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2755]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
 Liquidsoap or AzuraCast cannot shut down IceCast properly after AutoDJ is shut down, it runs into a constant Freeing Memory state

**To Reproduce**
Shut down AutoDJ then IceCast | Monitor Liquidsoap Logs | Check `docker-compose logs -f`

**Expected behavior**
IceCast to be fully shutdown and not be stuck in a Freeing Memory state

**Relevant Logs**
FROZEN STATE
```2020/04/26 21:36:06 [35mm_station_local_1:3] Closing connection...
2020/04/26 21:36:07 [clock.wallclock_main:3] Streaming loop stopped.
2020/04/26 21:36:07 [main:3] Threads terminated.
2020/04/26 21:36:07 [threads:3] Shutting down scheduler...
2020/04/26 21:36:07 [threads:3] Scheduler shut down.
2020/04/26 21:36:07 [threads:3] Waiting for queue threads to terminate...
2020/04/26 21:36:07 [threads:3] Queues shut down
2020/04/26 21:36:07 [server:3] Closing socket.
2020/04/26 21:36:07 [main:3] Cleaning downloaded files...
2020/04/26 21:36:07 [main:3] Freeing memory...
```
Docker Container Logs
```
web_1       | [2020-04-26T21:45:33.629359+00:00] AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... [] {"station":{"id":101,"name":"Rex's Diner"}}
web_1       | [2020-04-26T21:45:33.630838+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":101,"name":"Rex's Diner"}}
```
**Screenshots**

Services shut down 
![image](https://user-images.githubusercontent.com/29955942/80320694-ce954f00-880f-11ea-9a8d-e45ae3be739c.png)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by CodeSteele** [comment]
Investigating if it's a known upstream issue.

**Comment by CodeSteele** [comment]
This looks fine, the logs typically show this when stopping/starting LiquidSoap:

```
2020/04/27 05:06:01 [main:3] Freeing memory...
2020/04/27 05:09:12 >>> LOG START
2020/04/27 05:09:12 [main:3] Liquidsoap 1.4.1
```

The last log is memory being freed, then the application exits, let me know if any other logs from other versions or behaviors suggest that LiquidSoap isn't properly shutting down.
