### ISSUE TITLE
Fix Auto-building on Docker Image Upstream Updates

### ISSUE THREAD

**Issue by CodeSteele** [AzuraCast/AzuraCast#2757]
Found this while snooping around an issue with Redis in #2744, image hadn't updated in 8 months, talked to @SlvrEagle23 about it and he said that Docker Hub is set to rebuild on upstream changes, but wasn't, he triggered a job manually, we'll want keep an eye on it.

**Comment by Vaalyn** [comment]
Closing this issue since Docker images are built by GitHub Actions instead of Docker Hub now and the overall container architecture has been changed dramatically.
