### ISSUE TITLE
AutoDJ / Schedule issue.

### ISSUE THREAD

**Issue by Paulio759** [AzuraCast/AzuraCast#2758]
**Using Docker installation method**
Yes
**Host Operating System**
Debian buster
**Describe the bug**
Auto Dj does not play the scheduled playlists. The 'Scheduled' section of the profile page shows the scheduled playlists as scheduled but the 'On Air' does not update and continues to play from the Music Files. Have tried basic & advanced setings but nothing changes. I am not able to schedule a playlist at all.

**To Reproduce**

**Expected behavior**

**Relevant Logs**

[2020-04-27T18:23:02.338470+00:00] AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... [] {"station":{"id":2,"name":"TEST STATION"}}
[2020-04-27T18:23:02.339338+00:00] AzuraCast.ERROR: No playable tracks were found. [] {"station":{"id":2,"name":"TEST STATION"}}

2020/04/27 19:23:39 [lang:3] AzuraCast Raw Response: 
2020/04/27 19:23:39 [lang:3] AzuraCast Error: Delaying subsequent requests...

**Screenshots**

**Device(s):**
 - Device:  Desktop
 - OS: iOS
 - Browser:  Safari
 - Version: 12.1.2

**Additional context**

**Comment by master-magic** [comment]
you have to put also the link to the media map in your schedule so it is been seen ;) 
now it's look to files in your schedule and don't find anything ;)

**Comment by SlvrEagle23** [comment]
@Paulio759 Does your scheduled playlist have any media in it? If you have properly set up the playlist, you should check issue #2631, which also has instructions for common things to check.
