### ISSUE TITLE
Only 2 People can connect to 1 Mountpoint?

### ISSUE THREAD

**Issue by DomeMilch** [AzuraCast/AzuraCast#2760]
**Using Docker installation method**
YES

**Host Operating System**
local:iso/debian-9.11.0-amd64-DVD-3.iso,media=cdrom,size=4569124K

**Describe the bug**

There are 2 different listeners on the stream; [http://prntscr.com/s6xuip](http://prntscr.com/s6xuip)
As soon as a third person wants to connect to the stream, this error occurs: [http://prntscr.com/s6xvmx](http://prntscr.com/s6xvmx)

If one disconnects from the stream, another can connect .. So only 2 people can hear at the same time. The switch-on limit is standard with approx. 250 listeners.

I have not found a solution on the Internet and have already tried to fix it somehow ..? i need help.

**To Reproduce**
 i have no ideaa..

**Expected behavior**

please help me to fix that error, so that more people can connect to the mount point (the Stream)

**Relevant Logs**

"no data avaible"

**Screenshots**

[http://prntscr.com/s6xuip](http://prntscr.com/s6xuip)
[http://prntscr.com/s6xvmx](http://prntscr.com/s6xvmx)
**Device(s):**
 - Device:  Iphone, Desktop, Android Phone
 - OS: IOS, Windows10
 - Browser: Chrome, Safari, Firefox, Opera,..
 - Version: latest

**Additional context**

**Comment by DomeMilch** [comment]
i am using Icecast

**Comment by DomeMilch** [comment]
I didn't do anything and suddenly everything goes back to normal .. so it will definitely be a bug .. I still don't know where and how?

**Comment by SlvrEagle23** [comment]
@DomeMilch Really not sure what would be causing this. There's nothing internal in our setup that would limit listeners to _two_ per station.

I'd be interested in seeing your station's Icecast Error Log, visible from `Utilities` > `Log Viewer`, around the time when the incident happens.
