### ISSUE TITLE
Request song error

### ISSUE THREAD

**Issue by julianborghuis** [AzuraCast/AzuraCast#2761]
https://hastebin.com/areterelij.coffeescript

**Using Docker installation method**

yes

**Host Operating System**

ubuntu server 18.04

**Describe the bug**

cant request songs anymore
Get this error: ×Error: An exception occurred while executing 'INSERT INTO station_requests (station_id, track_id, timestamp, played_at, ip) VALUES (?, ?, ?, ?, ?)' with params [1, 1935, 1588052179, 0, "(MY IP)"]: SQLSTATE[HY000]: General error: 1364 Field 'skip_delay' doesn't have a default value

**To Reproduce**

1. go to public page
2. click request song
3. click a song.
4. get the error

**Expected behavior**

a song been requested

**Relevant Logs**

 ×Error: An exception occurred while executing 'INSERT INTO station_requests (station_id, track_id, timestamp, played_at, ip) VALUES (?, ?, ?, ?, ?)' with params [1, 1935, 1588052179, 0, "(MY IP)"]: SQLSTATE[HY000]: General error: 1364 Field 'skip_delay' doesn't have a default value

**Screenshots**

https://gyazo.com/0707f9817735c853e9eebf2f0fd11c3e

**Device(s):**
 - Device:  desktop
 - OS: windows 10
 - Browser:  chrome
 - Version:  newest

**Additional context**

this happens when i updated my azuracast to the latest version

**Comment by CodeSteele** [comment]
Can't reproduce on `v0.10.1, #bc34f02 (2020-04-28 0:43)`, what version are you running?

**Comment by CodeSteele** [comment]
Looking into it: Skip Delay was added back in March 21st here: fc70b139511c97d8c437efba95fd1844dd42efdd

**Comment by julianborghuis** [comment]
> Can't reproduce on `v0.10.1, #bc34f02 (2020-04-28 0:43)`, what version are you running?

how can i check

**Comment by julianborghuis** [comment]
https://gyazo.com/7dd081037ed782d519245641e86c28a5

**Comment by CodeSteele** [comment]
@julianborghuis at the bottom of every page in the administration dashboard. says this:

`Powered by AzuraCast • v0.10.1, #bc34f02 (2020-04-28 0:43) • Docker • PHP 7.4`

**Comment by julianborghuis** [comment]
Oww sorry.

Powered by AzuraCast • v0.9.9, # c7f4ce9 (2020-04-27 2:17) • Docker • PHP 7.4
Do you like our software? Donate to support AzuraCast!

**Comment by julianborghuis** [comment]
btw i have yesterday updated

**Comment by CodeSteele** [comment]
Re-run the update process to get on 0.10 so that it re-purges stuff like the Redis cache, may fix the issue.

**Comment by julianborghuis** [comment]
I am now do that wait

**Comment by julianborghuis** [comment]
It works so thanks!
