### ISSUE TITLE
Playlist don't play at scheduled time

### ISSUE THREAD

**Issue by kgguru** [AzuraCast/AzuraCast#2763]
**Describe the bug**

TESTED ON YOUR DEMO SERVER VERSION 0.10.1.
 Today I've created playlist "TEST" with only one music title. Scheduled to play on 10.30-10.35 UTC. 
And the playlist did not happened.

**Comment by kgguru** [comment]
![obraz](https://user-images.githubusercontent.com/6872090/80478272-972cbc80-894d-11ea-8401-da65e980adf1.png)

**Comment by rquara** [comment]
Same problem here

AzuraCast • v0.10.1, #bc34f02 (2020-04-28 0:43) • Docker • PHP 7.4

If I restart everything it properly read the schedule and works. Without restarting it doesn't play at the scheduled time

**Comment by pascalla** [comment]
This is a very well documented that is known. #2631
