### ISSUE TITLE
Playlist from remote url

### ISSUE THREAD

**Issue by BlackOssian** [AzuraCast/AzuraCast#2764]
Hi there
i have a new azuracast server, no access to administrator panel.

i'm trying to use playlist with remote url, but it seems it doesn't work at all. i can see the playlist on the waiting list from dashboard.
the remote url is working.

this is the error on my log
2020/04/29 12:48:23 [procol.external:3] Failed to fetch mime-type for https://******/live-dj-moon-vandalic-acts-of-b3auty2020-04-21-roman-invasions/listen.mp3.
2020/04/29 12:48:23 [procol.external:3] No known file extension for mime: 

2020/04/29 12:56:03 [decoder:3] Unable to decode "/tmp/liq-process8efac3.osb" as {audio=1+;video=0;midi=0}!

thanks for your help

**Comment by jbsix** [comment]
Several reports of the remote Playlist not working at all including #2570 #2486

**Comment by dxf** [comment]
This issue is not stale. Seriously Azura has had this issue for months and months. Someone ask stalebot to remove the wontfix tag,
