### ISSUE TITLE
Bulk upload image

### ISSUE THREAD

**Issue by BlackOssian** [AzuraCast/AzuraCast#2767]
Hi
it's very odd to upload a single file for every single song
it could be good to select an image from the upload folder, or upload 1 file for more songs. If i have 3 song from the same album, why should i upload the same image 3 times?

thanks for your help

**Comment by ayalavalva** [comment]
Yes, same applies to all metadata tags.

**Comment by CodeSteele** [comment]
Feel free to submit the enhancement to https://features.azuracast.com/
