### ISSUE TITLE
restor  account for a station?

### ISSUE THREAD

**Issue by fast97** [AzuraCast/AzuraCast#2769]
Hello HOW TO RESTOR AN ACCOUNT for a RADIO station FROM THE BACKUP?
THANK YOU

**Comment by JanieUwU** [comment]
If I wasn't mistaken, when you restore from a back up it restores everything including the super user account and such. Though keep in mind it will erase everything that was added after the backup was made.

**Comment by fast97** [comment]
Thanks for the reply it would be good to provide a system of restoration by account if possible. I have a station that has a liquidsoap and impossible restore problem.
