### ISSUE TITLE
Wrong time range local naming in scheduled playlist

### ISSUE THREAD

**Issue by replayfactory** [AzuraCast/AzuraCast#277]
Assuming all time range are displayed in 24h format,
'AM' and 'PM' are unnecessary and make time difficult to understand for 24h users.
Furthermore, there are some time range missing (nothing after 22:45 and before 11:00

Example with the folowwing server config : 
`Local time: dim. 2017-11-12 02:17:19 NCT`
`Universal time: sam. 2017-11-11 15:17:19 UTC`
`RTC time: sam. 2017-11-11 15:17:19`
`Time zone: Pacific/Noumea (NCT, +1100)`

__________________________________________________
12:00 AM (11:00 AM Local)  ----> 00:00 (11:00 Local)
12:15 AM (11:15 AM Local)  ----> 00:15 (11:15 Local)
12:30 AM (11:30 AM Local)
12:45 AM (11:45 AM Local)
01:00 AM (12:00 PM Local)  ----> 01:00 (12:00 Local)
01:15 AM (12:15 PM Local)
01:30 AM (12:30 PM Local)
01:45 AM (12:45 PM Local)
02:00 AM (01:00 PM Local)  ----> 02:00 (13:00 Local)
02:15 AM (01:15 PM Local)
02:30 AM (01:30 PM Local)
02:45 AM (01:45 PM Local)
03:00 AM (02:00 PM Local)  ----> 03:00 (14:00 Local)
03:15 AM (02:15 PM Local)
03:30 AM (02:30 PM Local)
03:45 AM (02:45 PM Local)
04:00 AM (03:00 PM Local)  ----> 04:00 (15:00 Local)
04:15 AM (03:15 PM Local)
04:30 AM (03:30 PM Local)
04:45 AM (03:45 PM Local)
05:00 AM (04:00 PM Local)  ----> 05:00 (16:00 Local)
05:15 AM (04:15 PM Local)
05:30 AM (04:30 PM Local)
05:45 AM (04:45 PM Local)
06:00 AM (05:00 PM Local)  ----> 06:00 (17:00 Local)
06:15 AM (05:15 PM Local)
06:30 AM (05:30 PM Local)
06:45 AM (05:45 PM Local)
07:00 AM (06:00 PM Local)  ----> 07:00 (18:00 Local)
07:15 AM (06:15 PM Local)
07:30 AM (06:30 PM Local)
07:45 AM (06:45 PM Local)
08:00 AM (07:00 PM Local)  ----> 08:00 (19:00 Local)
08:15 AM (07:15 PM Local)
08:30 AM (07:30 PM Local)
08:45 AM (07:45 PM Local)
09:00 AM (08:00 PM Local)  ----> 09:00 (20:00 Local)
09:15 AM (08:15 PM Local)
09:30 AM (08:30 PM Local)
09:45 AM (08:45 PM Local)
10:00 AM (09:00 PM Local)  ----> 10:00 (21:00 Local)
10:15 AM (09:15 PM Local)
10:30 AM (09:30 PM Local)
10:45 AM (09:45 PM Local)
11:00 AM (10:00 PM Local)  ----> 11:00 (22:00 Local)
11:15 AM (10:15 PM Local)
11:30 AM (10:30 PM Local)
11:45 AM (10:45 PM Local)
12:00 PM (11:00 PM Local)  ----> 12:00 (23:00 Local)
12:15 PM (11:15 PM Local)
12:30 PM (11:30 PM Local)
12:45 PM (11:45 PM Local)
01:00 PM (12:00 PM Local)  ----> 13:00 (00:00 Local)
01:15 PM (12:15 PM Local)
01:30 PM (12:30 PM Local)
01:45 PM (12:45 PM Local)
02:00 PM (13:00 PM Local)  ----> 14:00 (01:00 Local)
02:15 PM (13:15 PM Local)
02:30 PM (13:30 PM Local)
02:45 PM (13:45 PM Local)
03:00 PM (14:00 PM Local)  ----> 15:00 (02:00 Local)
03:15 PM (14:15 PM Local)
03:30 PM (14:30 PM Local)
03:45 PM (14:45 PM Local)
04:00 PM (15:00 PM Local)  ----> 16:00 (03:00 Local)
04:15 PM (15:15 PM Local)
04:30 PM (15:30 PM Local)
04:45 PM (15:45 PM Local)
05:00 PM (16:00 PM Local)  ----> 17:00 (04:00 Local)
05:15 PM (16:15 PM Local)
05:30 PM (16:30 PM Local)
05:45 PM (16:45 PM Local)
06:00 PM (17:00 PM Local)  ----> 18:00 (05:00 Local)
06:15 PM (17:15 PM Local)
06:30 PM (17:30 PM Local)
06:45 PM (17:45 PM Local)
07:00 PM (18:00 PM Local)  ----> 19:00 (06:00 Local)
07:15 PM (18:15 PM Local)
07:30 PM (18:30 PM Local)
07:45 PM (18:45 PM Local)
08:00 PM (19:00 PM Local)  ----> 20:00 (07:00 Local)
08:15 PM (19:15 PM Local)
08:30 PM (19:30 PM Local)
08:45 PM (19:45 PM Local)
09:00 PM (20:00 PM Local)  ----> 21:00 (08:00 Local)
09:15 PM (20:15 PM Local)
09:30 PM (20:30 PM Local)
09:45 PM (20:45 PM Local)
10:00 PM (21:00 PM Local)  ----> 22:00 (09:00 Local)
10:15 PM (21:15 PM Local)
10:30 PM (21:30 PM Local)
10:45 PM (21:45 PM Local)
11:00 PM (22:00 PM Local)  ----> 23:00 (10:00 Local)
11:15 PM (22:15 PM Local)
11:30 PM (22:30 PM Local)
11:45 PM (22:45 PM Local)  ----> 23:45 (10:45 Local)
__________________________________________________

In my opinion, `<input id="time" type="time">` should be easier to use than a html select multiple

Cheers!

**Comment by SlvrEagle23** [comment]
@replayfactory You are correct about this request; this feature is a very early one in AzuraCast, before the project became popular with a broader audience and localization became a concern. It was long overdue for an update to a newer format.

I have converted the time selectors on the playlist editor to use the HTML5 time element, which allows the free selection of any time (not just 15-minute increments), and will automatically convert from your local time to the server's UTC time without the confusing part of having both listed.

I have also updated the time display on the playlists homepage (i.e. where a playlist says `Will play between 3:30AM and 5:30AM`) to be localized to your region, which will also update the 12/24 hour display according to the selected locale.

**Comment by replayfactory** [comment]
@SlvrEagle23 I just tested this, the playlist editor is much easier to use with Html5 time input and the playlists homepage easy to read! 

A little issue on the playlist editor page, `Your current local time` displays UTC time instead of local time.

my server times : 
`$ timedatectl`
`  Local time: lun. 2017-11-13 08:22:45 +11`
`  Universal time: dim. 2017-11-12 21:22:45 UTC`
`  RTC time: dim. 2017-11-12 21:22:44`
`  Time zone: Pacific/Noumea (+11, +1100)`

playlist editor page : 
`  Your current local time is 9:22pm.`

Thanks again for this great project!
Cheers

**Comment by replayfactory** [comment]
@SlvrEagle23 Oops! My mistake, `Your current local time` returns correct local time.
My php.ini and server time zones was different....

**Comment by SlvrEagle23** [comment]
@replayfactory The local time, in this case, is actually the time zone set on your account's profile. If you click the menu at the top right, then "My Account", you can change it as needed.

The actual timestamps used by the AzuraCast software are in UTC for standards purposes, but the time displayed in that helper tip is based on your localized profile time.
