### ISSUE TITLE
Cannot connect source shoutcast v1

### ISSUE THREAD

**Issue by duduws** [AzuraCast/AzuraCast#2771]
**Using Docker installation method**

Yes
**Host Operating System**

Debian 9
**Describe the bug**

when try to connect in shoutcast source, get disconnect (10061) error, but all infos its all ok, checked 100 times. 
![image](https://user-images.githubusercontent.com/64056323/80619030-80a06700-8a1a-11ea-9045-a6b7764ba4ab.png), 
![image](https://user-images.githubusercontent.com/64056323/80619091-91e97380-8a1a-11ea-9061-ae5c8b18b1bc.png)

PS: Im trying kick the liquidsoap auto dj, and then connect with my sam, but comes with error 10061 all time, but i think its all right with my config.

**To Reproduce**

Configured 1 stream with SHOUTcast Server v2.5.5.733, and trying to access source to stream with sam broadcaster 4.2.2, with v1 source, cant connect.
**Expected behavior**

expected connection success 
**Relevant Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/64056323/80619276-dffe7700-8a1a-11ea-9d1b-246330090410.png)
![image](https://user-images.githubusercontent.com/64056323/80619300-eab90c00-8a1a-11ea-966b-da0bde8d348b.png)

**Device(s):**
 - Device:   Desktop, SAM Broadcaster 4.2.2
 - OS:  Windows 10
 - Browser:  Chrome
 - Version:  Latest

**Additional context**

**Comment by duduws** [comment]
any solution for this? help me pls

**Comment by nickrobillard** [comment]
Just a guess here but are you sure 8010 is the broadcasting port and not the listening port? If you used the default station port, the broadcast port should end in "5". Go to your station profile page in AzuraCast and click on the Streamers/DJ "Manage" link (make sure Streamers/DJs is enabled). This path should look like `/station/1/streamers`. Look at the right sidebar and check the connection info. Here is what it should look like:
<img width="355" alt="azuracast-station-connection-info" src="https://user-images.githubusercontent.com/135516/81451163-bb9c4c00-9138-11ea-8f46-64a3750dc9eb.png">

**Comment by duduws** [comment]
im not have access to this path, im using docker installation, and im "kicking" the liquid soap auto dj, to connected with the dj source, in my panel say 8010 port... 
![image](https://user-images.githubusercontent.com/64056323/81456849-59f4d580-916a-11ea-9cc8-eb886727a0c2.png)

**Comment by xewl** [comment]
Regardless of being able to access the AzuraCast panel, please try `8015` (or `8016`) instead.
Based on the port SHOUTcast shows (8010) and given it's not changed by the administrator who has access, it will most probably be set up at 8015"+1". (That 1 port thing is a perk of SHOUTcast, but /most/ clients do this automatically, )

The General Settings that SHOUTcast shows (portbase) is the listening port of the SC-server itself.

You will also need to set the password to `djname:djpass`, also something you should receive from the AzuraCast user in question. I'm not sure if setting the source password will be sufficient.
Please refer to @nickrobillard 's screenshot.

**Comment by duduws** [comment]
Thanks xewl, but i don't using the liquid soap ports to connect, im kicking the liquid soap from shoutcast panel, and trying to connect with another source, this source is my dj source btw, how can i create djname:pass without the liquid soap, its inside shoutcast config?

**Comment by xewl** [comment]
You shouldn't kick Liquidsoap (I don't even think you properly can).
Using the correct endpoint will result in LS properly dividing your incoming stream to whatever endpoints are linked to that server.

The DJ credentials are inside Azura.

**Comment by duduws** [comment]
i dont using liquidsoap dj ports, im trying to access from source, trying to access without liquidsoap autodj, directly in shoutcast port
