### ISSUE TITLE
Extending AutoDJ Queue Length provokes delay on song request

### ISSUE THREAD

**Issue by yarik2720** [AzuraCast/AzuraCast#2772]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 16.04

**Describe the bug**
If I set too much Queue Length any requested song will be placed after that filled queue. Even if on my setting there set "Request Minimum Delay" to 10 minutes it can play even after hour

**To Reproduce**
1. Go to Edit Station
2. Set "Request Minimum Delay" to 10
3. Set "AutoDJ Queue Length" to 10
4. Save
5. Make song request
6. Watch on track queue

**Expected behavior**
Track should be placed on the queue after "request minimum delay" without shifting other scheduled tracks (like scheduled jingles and podcasts)

**Comment by SlvrEagle23** [comment]
@yarik2720 Definitely a valid issue with the queue builder. I'm now passing it the correct timestamp, so it should be delaying requests the proper amount of time now.

**Comment by yarik2720** [comment]
Sorry for mentioning this, I updated to the latest release (Rolling Release #a33a84d (2020-10-10 7:18)) and issue still persists
