### ISSUE TITLE
Automatically Adjust Quality streaming

### ISSUE THREAD

**Issue by YosefAdPro** [AzuraCast/AzuraCast#2773]
Hi,

Is supported automatically adjust the quality based on connection speed if there are two mountpoints?

**Comment by CodeSteele** [comment]
Nope, this is typically up to the media player to determine which mountpoint to connect to, the built in web player doesn't have such functionality. You _can_ select the mountpoint from the player though, it's just not  automatic.

Feel free to request it at https://features.azuracast.com/.
