### ISSUE TITLE
Buffer overrun

### ISSUE THREAD

**Issue by ismaelazanza** [AzuraCast/AzuraCast#2774]
Sorry for the question, but I want to increase the buffer because I have this error. Where can it be done?

2020/04/29 19:10:29 [electrofactory_input_streamer:3] New metadata chunk ? -- 086. Tarzan Boy - Baltimora.
2020/04/29 19:11:40 [electrofactory_live_fallback:3] Switch to cross_7715 with forgetful transition.
2020/04/29 19:11:40 [dummy:3] Source failed (no more tracks) stopping output...
2020/04/29 19:11:45 [electrofactory_live_fallback:3] Switch to audio_to_stereo_7738 with transition.
2020/04/29 19:11:55 [dummy:3] Source failed (no more tracks) stopping output...
2020/04/29 19:11:55 [electrofactory_live_fallback:3] Switch to cross_7715 with forgetful transition.
2020/04/29 19:12:02 [electrofactory_live_fallback:3] Switch to audio_to_stereo_7738 with transition.
2020/04/29 19:12:06 [electrofactory_input_streamer:3] Buffer overrun: Dropping 0.01s. Consider increasing the max buffer size!
2020/04/29 19:12:06 [electrofactory_input_streamer:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2020/04/29 19:12:06 [electrofactory_input_streamer:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2020/04/29 19:12:06 [electrofactory_input_streamer:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2020/04/29 19:12:06 [electrofactory_input_streamer:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!

**Comment by CodeSteele** [comment]
Duplicate of #1900

**Comment by ismaelazanza** [comment]
I have opened this question since in # 1900, they do not provide a solution to the problem presented

**Comment by CodeSteele** [comment]
I re-opened #1900, not sure when someone will have the chance to look into it though.

**Comment by lramilo** [comment]
When playing a remote URL playlist, I found a workaround using a dummy output, manually adding this to Liquidsoap configuration:

`output.dummy(id="DUMMY_STREAM_OUTPUT", fallible=true, playlist_live)`

Details are explained on [#3701](https://github.com/AzuraCast/AzuraCast/issues/3701)

**Comment by julianodls** [comment]
Error
As I resolve, my radio is crashing
2021/03/16 13:37:40 [input_streamer:3] Buffer overrun: Dropping 0.05s. Consider increasing the max buffer size!
