### ISSUE TITLE
Not able to mount to a specific mount, stream appears offline, meta-data doesn't update.

### ISSUE THREAD

**Issue by ParkerSm1th** [AzuraCast/AzuraCast#2775]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
Meta-Data does not appear as expected, Not able to broadcast to a specific mount, and stream appears offline.

**To Reproduce**
1. Create multiple mounts
2. Try to connect to one
3. Fails to connect
4. Put "/" as the mount
5. Connects and starts broadcasting but stream appears offline even though audio is playing through the stream link. 
6. Genre & Station Name don't update.

**Expected behavior**
The meta-data should update & I should be able to mount to a specific mount along with the stream not appearing offline.

**Device(s):**
 - Browser: Chrome
 - Version: 81

**Additional context**
Hi there! 

I am able to connect to the icecast server although only on one mount ("/") and I would like to be able to connect to specific mounts. My stream also appears offline in the AzuraCast panel but says there is a DJ connected. I also set the Station Name & Genre from inside of my encoder but it doesn't go to the AzuraCast API or the Icecast site, it just shows up as "various" for the genre and the station name from AzuraCast. I plan on using the genre as a way to see which user is connected and the Station Name set in my encode as the name of the connected user. 

I also so the default mount as /stream which is what the users will be listening on and I want my DJs to connect to /live which is where all the meta-data should go & the listeners on /stream should be hearing /live because nothing places on /stream and /live is the fallback. 

I'm sorry if this was confusing to read, please ask clarifying questions.

**Comment by CodeSteele** [comment]
The streaming details are listed under the "Streamer/DJ Accounts" page, there is no currently supported way to expose custom streaming mounts to send streams *to*, you can set a mount called /stream for your users though.

> I also set the Station Name & Genre from inside of my encoder but it doesn't go to the AzuraCast API or the Icecast site

That suggests an issue with your client, what client are you using?

> My stream also appears offline in the AzuraCast panel but says there is a DJ connected.

This may be related to the above issues with your client.
