### ISSUE TITLE
Ubuntu 20 installation probem

### ISSUE THREAD

**Issue by suricloud** [AzuraCast/AzuraCast#2777]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 20

**Describe the bug**

On a fresh ubuntu 20 vps i get this error?How to fix this ?
root@rs:/var/azuracast# ./docker.sh install
Docker does not appear to be installed. Install Docker now? [Y/n] Y
# Executing docker install script, commit: 442e66405c304fa92af8aadaa1d9b31bf4b0ad94
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
E: The repository 'https://download.docker.com/linux/ubuntu focal Release' does not have a Release file.
Docker Compose does not appear to be installed. Install Docker Compose now? [Y/n] Y
Writing default .env file...
Creating default AzuraCast settings file...
Retrieving default docker-compose.yml file...
ERROR: Couldn't connect to Docker daemon. You might need to install Docker:

https://docs.docker.com/engine/installation/
ERROR: Couldn't connect to Docker daemon. You might need to install Docker:

https://docs.docker.com/engine/installation/
ERROR: Couldn't connect to Docker daemon. You might need to install Docker:

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by radiolize** [comment]
Same error appears.

**Comment by CodeSteele** [comment]
Yep, as far as I know (checked a couple days ago) the multi-platform install script that Docker provides hasn't been updated to support 20.04 yet (or more accurately their repos don't have 20.04 builds available).

**Comment by SlvrEagle23** [comment]
@suricloud @radiolize There's a simple current workaround for installing AzuraCast on Ubuntu 20.04 LTS. Just before running the AzuraCast installer, run:

```bash
sudo apt-get install docker.io
```

This will install the (still up-to-date) version of Docker from the Ubuntu repository instead of using Docker's automated installer; when you continue to the AzuraCast installer, it will detect that Docker's already installed and continue without issue.

**Comment by suricloud** [comment]
> @suricloud @radiolize There's a simple current workaround for installing AzuraCast on Ubuntu 20.04 LTS. Just before running the AzuraCast installer, run:
> 
> ```shell
> sudo apt-get install docker.io
> ```
> 
> This will install the (still up-to-date) version of Docker from the Ubuntu repository instead of using Docker's automated installer; when you continue to the AzuraCast installer, it will detect that Docker's already installed and continue without issue.

I did this sudo apt-get install docker.io and after that installation went succesfull and all setup.
But after 10 min aprox it crashes,i used docker update command.It brings there after again evrything up and then again after 10 min so it crash??

Hope you can have a look on this ?

**Comment by suricloud** [comment]
i also see this error:

ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it runn                                                      ing?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environ                                                      ment variable.
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it runn                                                      ing?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environ                                                      ment variable.
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docke                                                      r daemon running?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docke                                                      r daemon running?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docke                                                      r daemon running?
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it runn                                                      ing?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environ                                                      ment variable.
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it runn                                                      ing?

**Comment by SlvrEagle23** [comment]
@suricloud Normally we'd show a warning during the installer about this, but with the workaround, that warning isn't shown. Basically, you need to ensure your main running user account is in the `docker` user group so it has permission to manage the Docker socket. The easiest way to do this is to run something like:

```bash
sudo usermod -aG docker "$(whoami)"
```

**Comment by suricloud** [comment]
Hi,

sudo usermod -aG docker "$(whoami)"

in the (whoami) what should i fill in ?
If i put root  i get this;

root@rs:~# sudo usermod -aG docker "$(root)"

Command 'root' not found, did you mean:

  command 'toot' from snap toot (0.26.0)
  command 'roo' from snap roo (2.0.3)
  command 'toot' from deb toot (0.25.2-1)
  command 'rott' from deb rott (1.1.2+svn287-3)
  command 'rootv' from deb xawtv (3.106-1)
  command 'proot' from deb proot (5.1.0-1.3)

See 'snap info <snapname>' for additional versions.

usermod: user '' does not exist

**Comment by SlvrEagle23** [comment]
@suricloud You're not supposed to fill anything in there...that's actually a terminal command that returns your current user. Just paste the command in as I wrote it.

**Comment by suricloud** [comment]
i did, and rebooted.
After reboot azuracast didnt start?

**Comment by suricloud** [comment]
I rebooted again,ran the docker update script.
Azuracast is running till now,i will monitor and let you know .

**Comment by suricloud** [comment]
Azuracast went down again now, after about 30 min.
What to do now?

**Comment by CodeSteele** [comment]
Run these:

`docker-compose ps`

`docker ps -a`

**Comment by suricloud** [comment]
root@rs:~# cd /var/azuracast
root@rs:/var/azuracast# docker-compose ps
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
root@rs:/var/azuracast# docker ps -a
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
root@rs:/var/azuracast#

**Comment by CodeSteele** [comment]
`sudo usermod -aG docker "$(whoami)"`

^ You'll need to run this prior to those two commands I gave you, or run them with `sudo` before.

**Comment by suricloud** [comment]
root@rs:/var/azuracast# sudo usermod -aG docker "$(whoami)"
root@rs:/var/azuracast# docker-compose ps
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
root@rs:/var/azuracast# docker ps -a
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
root@rs:/var/azuracast#

**Comment by adoboligh1** [comment]
Azuracast usually works well when you update ubuntu 18.04 LTS to ubuntu 20. Mine Still works Well

**Comment by CodeSteele** [comment]
Just did a clean install on Ubuntu 20.04 as part of #2731, everything looks good now.
