### ISSUE TITLE
Mounted folder with sshfs not accessible by media

### ISSUE THREAD

**Issue by mtzakris** [AzuraCast/AzuraCast#2778]
-Docker installation-
I have mounted an external folder with sshfs into the host machine where azuracast is installed
Then I mounted the directory  into my stations media folder by following the instructions of customising docker.

My files are not read. I ve read in older posts that there was an issue with sshfs, is this the case or I should keep looking into permissions and other stuff to identify the problem?

**Comment by kemecs** [comment]
sshfs

-o allow_other 

parameter does not help?

**Comment by mtzakris** [comment]
no it doesn't
