### ISSUE TITLE
URGENTE

### ISSUE THREAD

**Issue by Brunomartinez95** [AzuraCast/AzuraCast#2779]
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for radio.vivocanal3.com.uy
Using the webroot path /var/www/letsencrypt for all unmatched domains.
Waiting for verification...
Challenge failed for domain radio.vivocanal3.com.uy
http-01 challenge for radio.vivocanal3.com.uy
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: radio.vivocanal3.com.uy
   Type:   dns
   Detail: DNS problem: NXDOMAIN looking up A for
   radio.vivocanal3.com.uy - check that a DNS record exists for this
   domain
Domain name radio.vivocanal3.com.uy is not set up with LetsEncrypt yet. Reverting to self-signed cert...
Generating a RSA private key
...................+++++
.....................+++++
writing new private key to '/etc/letsencrypt/selfsigned.key'
req: Can't open "/etc/letsencrypt/selfsigned.key" for writing, Permission denied
Self-signed certificate restored.

**Comment by Brunomartinez95** [comment]
Hola estoy teniendo ese problema al trasladar a un sub dominio

**Comment by CodeSteele** [comment]
Where are you seeing this log? Is there anything else? The image should continue to boot fine and you can follow the Let's Encrypt steps from there: https://www.azuracast.com/extending/letsencrypt.html
