### ISSUE TITLE
driver failed programming external connectivity on endpoint azuracast_stations 

### ISSUE THREAD

**Issue by manugut** [AzuraCast/AzuraCast#2780]
Hello,
after Update I get this Error.

ERROR: for azuracast_stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (e7f53d34a54f34650b12d3aa31987ee76df52553215a28f51f54c525d5352765): Error starting userland proxy: listen tcp 0.0.0.0:8000: bind: address already in use

Using on Ubuntu 18 with Docker Installation.

Error in Log:
mariadb_1   | 2020-05-01 06:10:41+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mariadb_1   | 2020-05-01 06:10:41+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.4.12+maria~bionic started.
mariadb_1   | 2020-05-01  6:10:42 0 [Note] mysqld (mysqld 10.4.12-MariaDB-1:10.4.12+maria~bionic) starting as process 11 ...
mariadb_1   | 2020-05-01  6:10:42 0 [Note] InnoDB: Using Linux native AIO
mariadb_1   | 2020-05-01  6:10:42 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1   | 2020-05-01  6:10:42 0 [Note] InnoDB: Uses event mutexes
mariadb_1   | 2020-05-01  6:10:42 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1   | 2020-05-01  6:10:42 0 [Note] InnoDB: Number of pools: 1
mariadb_1   | 2020-05-01  6:10:42 0 [Note] InnoDB: Using SSE2 crc32 instructions
mariadb_1   | 2020-05-01  6:10:42 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
mariadb_1   | 2020-05-01  6:10:42 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
mariadb_1   | 2020-05-01  6:10:42 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1   | 2020-05-01  6:10:42 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_1   | 2020-05-01  6:10:42 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mariadb_1   | 2020-05-01  6:10:42 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_1   | 2020-05-01  6:10:42 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb_1   | 2020-05-01  6:10:42 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb_1   | 2020-05-01  6:10:42 0 [Note] InnoDB: 10.4.12 started; log sequence number 312649678801; transaction id 41718950
mariadb_1   | 2020-05-01  6:10:42 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mariadb_1   | 2020-05-01  6:10:42 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1   | 2020-05-01  6:10:42 0 [Note] Server socket created on IP: '::'.
mariadb_1   | 2020-05-01  6:10:42 0 [Warning] 'proxies_priv' entry '@% root@733a0a59f2ad' ignored in --skip-name-resolve mode.
mariadb_1   | 2020-05-01  6:10:42 0 [ERROR] Incorrect definition of table mysql.event: expected column 'sql_mode' at position 14 to have type set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','IGNORE_BAD_TABLE_OPTIONS','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_ALL_TABLES','NO_ZERO_IN_DATE','NO_ZERO_DATE','INVALID_DATES','ERROR_FOR_DIVISION_BY_ZERO','TRADITIONAL','NO_AUTO_CREATE_USER','HIGH_NOT_PRECEDENCE','NO_ENGINE_SUBSTITUTION','PAD_CHAR_TO_FULL_LENGTH','EMPTY_STRING_IS_NULL','SIMULTANEOUS_ASSIGNMENT'), found type set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','IGNORE_BAD_TABLE_OPTIONS','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_VALU
mariadb_1   | 2020-05-01  6:10:42 0 [ERROR] mysqld: Event Scheduler: An error occurred when initializing system tables. Disabling the Event Scheduler.
mariadb_1   | 2020-05-01  6:10:42 0 [Note] Reading of all Master_info entries succeeded
mariadb_1   | 2020-05-01  6:10:42 0 [Note] Added new Master_info '' to hash table
mariadb_1   | 2020-05-01  6:10:42 0 [Note] mysqld: ready for connections.
mariadb_1   | Version: '10.4.12-MariaDB-1:10.4.12+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
mariadb_1   | 2020-05-01  6:10:43 0 [Note] InnoDB: Buffer pool(s) load completed at 200501  6:10:43

So what can i do? Reboot, New start docker ... nothing help.
Thanks & greetings
manu

**Comment by CodeSteele** [comment]
>  Error starting userland proxy: listen tcp 0.0.0.0:8000: bind: address already in use

This message suggests you have other things running, what is the output of `docker ps`?

Also try running this: `ss -ptulwn | grep 8000`

**Comment by manugut** [comment]
Hi, thank you so much. After reboot maschine, an old icecast2 start up. This was not in my mind/memory. 
`tcp    LISTEN   0        5                 0.0.0.0:8000           0.0.0.0:*      users:(("icecast2",pid=1083,fd=4))      `

**Comment by silvanildocosta** [comment]
Pessoal estou encontrando este problema ao instalar o AzuraCast. Alguem poderia me ajudar por? 

root@hostssv:~# mkdir -p /var/azuracast
root@hostssv:~# cd /var/azuracast
root@hostssv:/var/azuracast# curl -fsSL https://raw.githubusercontent.com/AzuraC                                                                                                                                                             ast/AzuraCast/main/docker.sh > docker.sh
root@hostssv:/var/azuracast# chmod a+x docker.sh
root@hostssv:/var/azuracast# ./docker.sh install
Checking installation requirements for AzuraCast...
[PASS] Operating System: Linux
[PASS] Architecture: x86_64
[PASS] Command Present: curl
[PASS] Command Present: awk
[PASS] User Permissions
[PASS] Installation Directory
[PASS] All requirements met!
Docker does not appear to be installed. Install Docker now? [Y/n] Y
# Executing docker install script, commit: 93d2499759296ac1f9c510605fef85052a2c3                                                                                                                                                             2be
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-http                                                                                                                                                             s ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | gpg --dearmo                                                                                                                                                             r --yes -o /usr/share/keyrings/docker-archive-keyring.gpg
+ sh -c echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyri                                                                                                                                                             ng.gpg] https://download.docker.com/linux/ubuntu focal stable" > /etc/apt/source                                                                                                                                                             s.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recom                                                                                                                                                             mends  docker-ce-cli docker-scan-plugin docker-ce >/dev/null
+ version_gte 20.10
+ [ -z  ]
+ return 0
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-ce-rootless-extras >/dev/null
+ sh -c docker version
Client: Docker Engine - Community
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:37:06 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

================================================================================

To run Docker as a non-privileged user, consider setting up the
Docker daemon in rootless mode for your user:

    dockerd-rootless-setuptool.sh install

Visit https://docs.docker.com/go/rootless/ to learn about rootless mode.


To run the Docker daemon as a fully privileged service, but granting non-root
users access, refer to https://docs.docker.com/go/daemon-access/

WARNING: Access to the remote API on a privileged Docker daemon is equivalent
         to root access on the host. Refer to the 'Docker daemon attack surface'
         documentation for details: https://docs.docker.com/go/attack-surface/

================================================================================

Docker Compose does not appear to be installed. Install Docker Compose now? [Y/n] Y
curl: (23) Failed writing body (0 != 855)
Prefer stable release versions of AzuraCast? [y/N] N
Pulling installer ... done
Creating network "azuracast_default" with the default driver
Creating azuracast_installer_run ... done

 Select Language [English (Default)]:
  [en_US] English (Default)
  [cs_CZ] čeština
  [de_DE] Deutsch
  [es_ES] Español
  [fr_FR] Français
  [el_GR] ελληνικά
  [it_IT] Italiano
  [hu_HU] magyar
  [nl_NL] Nederlands
  [pl_PL] Polski
  [pt_PT] Português
  [pt_BR] Português do Brasil
  [ru_RU] Русский язык
  [sv_SE] Svenska
  [tr_TR] Türkçe
  [zh_CN] 簡化字
  [ko_KR] 한국어
 > Português do Brasil

Instalador do AzuraCast
=======================

 Bem-vindo ao AzuraCast! Complete a configuração inicial do servidor respondendo algumas perguntas.

O AzuraCast está configurado para ser ouvido nas seguintes portas:
 * Porta HTTP: 80
 * Porta HTTPS: 443
 * Porta SFTP: 2022
 * Portas de Rádio: 8000,8005,8006,8010,8015,8016,8020,8025,8026,8030,8035,8036,8040,8045,8046,8050,8055,8056,8060,8065,8066,8070,8075,8076,8090,8095,8096,8100,8105,8106,8110,8115,8116,8120,8125,8126,8130,8135,8136,8140,8145,8146,8150,8155,8156,8160,8165,8166,8170,8175,8176,8180,8185,8186,8190,8195,8196,8200,8205,8206,8210,8215,8216,8220,8225,8226,8230,8235,8236,8240,8245,8246,8250,8255,8256,8260,8265,8266,8270,8275,8276,8280,8285,8286,8290,8295,8296,8300,8305,8306,8310,8315,8316,8320,8325,8326,8330,8335,8336,8340,8345,8346,8350,8355,8356,8360,8365,8366,8370,8375,8376,8380,8385,8386,8390,8395,8396,8400,8405,8406,8410,8415,8416,8420,8425,8426,8430,8435,8436,8440,8445,8446,8450,8455,8456,8460,8465,8466,8470,8475,8476,8480,8485,8486,8490,8495,8496

 Personalizar portas usadas para o AzuraCast? (yes/no) [no]:
 > yes

 Porta HTTP - A porta principal do AzuraCast das conexões HTTP inseguras. [80]:
 > [8010]

 Porta HTTPS - A porta principal do AzuraCast para conexões HTTPS seguras. [443]:
 > [8020]

 Porta SFTP - A porta AzuraCast para as conexões de gerenciamento de arquivos SFTP. [2022]:
 >

 Porta mínima para atribuição da porta da estação [8000]:
 >

 Porta máxima para atribuição da porta da estação [8499]:
 > [8550]

 Configurar o LetsEncrypt? (yes/no) [no]:
 > yes

 Nome de domínio (exemplo.com) ou nomes (exemplo.com,foo.bar) a serem usados com o LetsEncrypt. []:
 > ^[radioroga.com]

 Opcionalmente, forneça um endereço de e-mail para atualizações do LetsEncrypt. []:
 > [silvanildocostadesouza@gmail.com]

Criando arquivos de configuração...


 [OK] Configuração do servidor completa!


Pulling mariadb                 ... done
Pulling redis                   ... done
Pulling stations                ... done
Pulling web                     ... done
Pulling nginx_proxy             ... done
Pulling nginx_proxy_letsencrypt ... done
Creating network "azuracast_backend" with driver "bridge"
Creating network "azuracast_frontend" with driver "bridge"
Creating volume "azuracast_nginx_proxy_vhosts" with default driver
Creating volume "azuracast_db_data" with default driver
Creating volume "azuracast_letsencrypt" with default driver
Creating volume "azuracast_letsencrypt_html" with default driver
Creating volume "azuracast_letsencrypt_acme" with default driver
Creating volume "azuracast_shoutcast2_install" with default driver
Creating volume "azuracast_geolite_install" with default driver
Creating volume "azuracast_sftpgo_data" with default driver
Creating volume "azuracast_station_data" with default driver
Creating volume "azuracast_www_vendor" with default driver
Creating volume "azuracast_www_uploads" with default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_redis_data" with default driver
Creating volume "azuracast_backups" with default driver
Creating azuracast_redis    ... done
Creating azuracast_mariadb  ... done
Creating azuracast_stations ...
Creating azuracast_stations ... error

ERROR: for azuracast_stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (a690807547522e529c4cc5ea66ca0dc9159de9e1b6321953ebb826473d8862ad): Error starting userland proxy:

ERROR: for stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (a690807547522e529c4cc5ea66ca0dc9159de9e1b6321953ebb826473d8862ad): Error starting userland proxy:
ERROR: Encountered errors while bringing up the project.
azuracast_redis is up-to-date
Starting azuracast_stations ...
azuracast_mariadb is up-to-date
Starting azuracast_stations ... error

ERROR: for azuracast_stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (3f312ef5a074dbb46d57382690452c4aed434df646f21bfb2618ce9314a16897): Error starting userland proxy:

ERROR: for stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (3f312ef5a074dbb46d57382690452c4aed434df646f21bfb2618ce9314a16897): Error starting userland proxy:
ERROR: Encountered errors while bringing up the project.
root@hostssv:/var/azuracast#
