### ISSUE TITLE
Liquidsoap invisible decoding failure

### ISSUE THREAD

**Issue by loics2** [AzuraCast/AzuraCast#2783]
**Using Docker installation method**
Yes

**Host Operating System**
 Ubuntu 18.04 (LTS), AzuraCast v0.9.9, #ef6393e (2020-03-22 22:40)

**Describe the bug**
Liquisoap sometimes fails to decode some files, and there's almost no way to know when this happens.

The only way to know what's happening is to check Liquidsoap's logs at the time the file has been uploaded, which can be difficult to find.

"undecodable" files can be added to scheduled playlists, and when it's time to play, nothing happens and it fails silently. These files also cannot be added to the queue, and  trying to do so also fails silently.

I don't really know what kind of files cannot be decoded (I don't think you care here, I'll check with Liquidsoap's folks), but it happened to me  with at least two `WAV 32-bit float` files.

**To Reproduce**

  1. Upload a file Liquidsoap cannot decode (`WAV 32-bit float` for example, either through SFTP or via the web interface)
  2. Try to add it to the queue or in any kind of playlist (with or without advanced configuration)
  3. The file is not played and there's no way to know why

**Expected behavior**

An error is shown somewhere : maybe in the "AutoDJ Service" section, or the file browser.

**Relevant Logs**
```
2020/05/01 12:12:22 [decoder:3] Unable to decode "/var/azuracast/stations/ebull_radio/media/FeteAuBlacon/Sust (Point76) - djset.wav" as {audio=1+;video=0;midi=0}!
```

**Device(s):**
 All platforms

**Comment by loics2** [comment]
I've checked with the Liquidsoap team, and doesn't seem to be a requirement issue, `ffmpeg` should be able to handle correctly WAV decoding. I'll continue to investigate.

In parallel, I'm trying to add  an Elastic Search  container to centralize and analyze the logs of all the containers. This could be useful to avoid this kind of subtle errors. @SlvrEagle23 if you're interested, I can open a pull request when it's done.

**Comment by hillbilly-mark** [comment]
Is there a good reason to use wav?   I can think of a few reasons not to.   If there is no reason you use wav, you could just convert them to mp3, opus, or flak, with something like Goldwave.

I don't recall ever having this issue, though docker would restart everything after any crash.  Perhaps, it has happened and I just didn't see it.

**Comment by loics2** [comment]
> I can think of a few reasons not to

I don't really, maybe the size of the file, but that's not really a concern for me.

> you could just convert them to mp3, opus, or flak

It adds unnecessary steps in my workflow. If I can just give access to the SFTP server to the DJs and don't have to worry about converting the files, I'm happy. And I don't really know what software my DJs use to record their sets, but it seems that the default output format is WAV 32bit, and once again, I don't want to worry about their setup, I don't have the time to be the IT guy for everybody.

> though docker would restart everything after any crash

Nothing crashes, Liquidsoap just ignores the file silently. And if it's scheduled to be played at a certain time, it won't be and there's almost no information about the reason it's not playing.

The merge request  AzuraCast/docker-azuracast-radio#9 fixes the issue (but not the error reporting when something like this happens, I'm working on something for this)
