### ISSUE TITLE
How To Change Icecast Settings Programmatically

### ISSUE THREAD

**Issue by mevaka** [AzuraCast/AzuraCast#2785]
Hi, 
Firstly thank you so much for make Azuracast open source.
We are using Azuracast in our schools, and this saved our classes. 

We build a system with azuracast but , I have a question about Icecast settings.

I need to change Icecast '**Source Password**' and listener '**Mount Point**' _programmatically_. 

What I need to change :
1.  Broadcasting 'Source Password' : [Here In Demo Page](https://demo.azuracast.com/station/1/profile/edit)  > **Broadcasting** > '_Advanced Customize Source Password_'  
2. Mount Point : [Here In Demo Page](https://demo.azuracast.com/station/1/mounts/edit/1) > '**Mount Point URL**'

How I need to change :
- I am using Azuracast stations in a _Django_ project, so I want to change '**Source Password**' and '**Mount Point**' parameters via our Django project with Python

Scenario :  
-  In my Django project, when I click 'Change Source' , my Python code must go Azuracast server and change them. Yes , this :)

I tried to figure out how you are changing them **[HERE](https://demo.azuracast.com/station/1/profile/edit)** with code, but couldn't find a way. I don't know php well. 

But I ned to change them with my python code .

Maybe can change them on Icecast **DB** directly, but I even couldnt find where the DB :(

Sorry for my poor explanation but this is what I want.

How can I change them with my python code ? 

Thank you for helps.

**Comment by mevaka** [comment]
#266 I think I am talking about this. But couldn't access DB ;

I found DB info in '/var/azuracast/azuracast.env' file

and run :
`docker-compose -f docker-compose.yml -f docker-compose.yml up -d`

after tried to connect DB like that :
`mysql -h localhost -P 3306 -u azuracast`

and _ERROR_ :
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")

I thought maybe I can do sth here but couldn't.

Also , even it works, this is not exactly what I want ; because I want to change a specific thing REMOTELY (from a different server) .

Also even I found these fields in DB maybe it is not enough to change them only in DB , because I need to change some different parameters too. 

Our school is using Azuracast for online classes but we need to change mount points and source passwords after each lesson. 
It is so hard to change every time manually, so we need to change them with Python , from a different server., remotely.

I need a python code to do this :

1. Connect Azuracast server DB
2. Change Icecast Source Password
3. Change listener mount pont 
4. change additional parameters to work properly (if needed)
finish.

How can I do this.
Really we need this to save all our lessons.
Thnx a lot for helps.

**Comment by mevaka** [comment]
Or Is there an API to change them ?

**Comment by mevaka** [comment]
Found sth :

> ./var/lib/docker/volumes/azuracast_station_data/_data/deneme/config/icecast.xml

There is a field named` <source-password>` , and `<mount-name>` 

I changed them, but unfortunately , not worked :( 

Hey is there someone to help me tehere please!!!!!

**Comment by pascalla** [comment]
I'm struggling to follow the need to change the source password. You could take advantage of the "Streamer Accounts" via the API. You can also manage mountpoints via API.

However streamer accounts wouldnt be exclusive to a mount point.
