### ISSUE TITLE
High Memory and CPU Utilization

### ISSUE THREAD

**Issue by blindgeek** [AzuraCast/AzuraCast#2786]
Let me start by thanking the lone developer for this very wonderful, accessible software, Azuracast! I hinted accessibility because I am blind and find Azuracast very accessible particularly its web interface although I have a few observations I would like to state regarding that matter in my future posts - would be more like a review. But for now, I want to ask if if a 200 MB spike in memory utilization is normal every time I launch it via docker-compose up -d. And then one evening the server crashed because the CPU reached 100% after I created more than five stations. I notice that if a single station is streaming, the CPU runs in the range of 10-20%. Does this mean it is not advisable for Azuracast to be run on the smallest VPS plan with 1 GB RAM and 1 VCPU? I want to have an idea how much at least in average, one station can consume in terms of system resources. Because of this, I formed a routine that whenever I restart Azuracast docker-compose up -d, I would quickly login to the web interface and stop those stations that are not streaming to avoid the CPU spike. In line with this, is there a way to prevent Azuracast to automatically start every station upon restart? Again, great work you have there.

**Comment by CodeSteele** [comment]
OK, so there are a few things at play here:

> And then one evening the server crashed because the CPU reached 100% after I created more than five stations. I notice that if a single station is streaming, the CPU runs in the range of 10-20%. 

AzuraCast has to spend CPU time transcoding music, this can be relatively CPU intensive, 5-6 stations a CPU isn't exactly a surprising amount (my Epic processors can do maybe like 8-12?)

> I want to have an idea how much at least in average, one station can consume in terms of system resources. 

This can vary a lot depending on your host and CPU type, so your baseline does sound to be about 20% resorucse per station with your host.

> I formed a routine that whenever I restart Azuracast docker-compose up -d, I would quickly login to the web interface and stop those stations that are not streaming to avoid the CPU spike.

![image](https://user-images.githubusercontent.com/31152835/80858971-4eb21f00-8c2b-11ea-9edb-1c3591c88079.png)

This under the station should persist through a restart.

> Does this mean it is not advisable for Azuracast to be run on the smallest VPS plan with 1 GB RAM and 1 VCPU?

You _can_ squeeze AzuraCast on the smallest instance, but sometimes you can run into annoyances, we generally recommend you size your instance according to your needs, if you want to do one or two smaller stations, a small 1GB/1vCPU instance may be good enough. If you want to run a lot of stations you'll want more CPU and RAM.

**Comment by SlvrEagle23** [comment]
@blindgeek Thank you for the kind words! I sincerely hope that AzuraCast helps make the web radio experience easier and more accessible.

**Comment by blindgeek** [comment]
Thank you very much - closing this as I got my answers already.
