### ISSUE TITLE
Heply to Netlify

### ISSUE THREAD

**Issue by scara78** [AzuraCast/AzuraCast#2787]
Please help me to deploy to Netlify
I got some errors while running php 5.6 and require version is 7+.
Thanks in advance

**Comment by pascalla** [comment]
I don't believe you will be able to host Azuracast on Netlify. 

Azuracast is more than just a website, and spins up radio servers and many other processes.

**Comment by SlvrEagle23** [comment]
@scara78 You can't build AzuraCast into a static web site that would be hosted on Netlify. You need to host it on an always-running VPS or virtual machine; we personally recommend DigitalOcean as they have a one-click installer for AzuraCast.

The actual homepage for your radio station absolutely can be a static Netlify page, however, using the embedded player code from AzuraCast.
