### ISSUE TITLE
auto dj liquipsoap problem

### ISSUE THREAD

**Issue by fast97** [AzuraCast/AzuraCast#2789]
Hello, I have small cuts in live mode the autodj liquidsoap takes control of the live about 1 second and the connection immediately. who would have this problem?
Thank you

**Comment by SlvrEagle23** [comment]
@fast97 This is usually caused by your buffer setting being too low for the latency of the connecting broadcasters. Try updating the DJ connection buffer setting in your station profile, then restarting the station, to see if it helps the issue.

**Comment by fast97** [comment]
ok i will test this is good on my screenshot this parameter in question has changed?
Thank you for your help
![AUTO](https://user-images.githubusercontent.com/51033222/80917620-92f30b80-8d60-11ea-8642-24b9403253e7.png)

**Comment by rolradio** [comment]
I set the buffer time to 10 seconds by default.
5 seconds is too low in my experience.

**Comment by fast97** [comment]
Merci.
