### ISSUE TITLE
better scheduling principles

### ISSUE THREAD

**Issue by voipworld** [AzuraCast/AzuraCast#279]
Hello Azura Team

i am back to you with another idea, for better scheduling

for example let's say we have a web radio, that do some regular radio shows from time to time, let's say weekly, ok?

we must be able to create the show, and schedule it to run weekly, in a specific timefram
for example, every monday at 7PM, the end time should be also specified, but should not be truely respected in case of a file based show

then, inside of that show, we must be able to insert like Playlist, file, webStream, anything

the playlist could be a ad, followed by the show id, then we do the show file, or the live stream

the more important feature is to be able to specify the file for each schedule, (here come the trick)

no need to schedule a regular playlist only, then come to it weekly and update it

this feature would let radios to better manage there schedule in a bigger time frame

if you need any explanation i am ready to talk...

btw, this is not a urjant feature, but at i am a new commer from (AIRTIME),  i would be glad to share  some ideas from time to time

thanks!

**Comment by amavarick** [comment]
Please advise if I should add this to a new enhancement request but really would love to have as stated above a calendaring or advanced solution for scheduling.  **Specifically I'd like to see scheduling playlists by day of month**.

Liquidsoap has been updated to incorporate a far more expanded time functionality in Liquidsoap version 1.3.3:

> A couple of new time-related functions have been added to help writing time-based predicates, namely: time, localtime and gmtime.  They follow the POSIX semantics: http://pubs.opengroup.org/onlinepubs/009695399/basedefs/time.h.html

This was based on their github request:
[https://github.com/savonet/liquidsoap/issues/481](https://github.com/savonet/liquidsoap/issues/481)

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38780/allow-multiple-schedule-entries-for-a-single-playlist
