### ISSUE TITLE
image embed player no click

### ISSUE THREAD

**Issue by Reaktiv4** [AzuraCast/AzuraCast#2791]
How to disable the player clicking on the image? So that the image is simply displayed without the possibility of transition.
What should I prescribe CSS?

**Comment by Reaktiv4** [comment]
if you insert
`.now-playing-art img {visibility:hidden !important; }`
then this completely hides the image, but how to make it not clickable?

**Comment by Sim7b** [comment]
I'm interrested too

**Comment by ITC-Media** [comment]
To make album art non-clickable just insert following CSS to your custom CSS field in public pages:

`.now-playing-art {pointer-events: none; !important; }`
