### ISSUE TITLE
sistema lixo, so funciona em vps, não da certo instala em maquina local

### ISSUE THREAD

**Issue by ramonigo** [AzuraCast/AzuraCast#2792]
sistema lixo, so funciona em vps, não da certo instala em maquina local

**Comment by ramonigo** [comment]
garbage system, only works on vps, not sure install on local machine

**Comment by Vaalyn** [comment]
Please refrain from creating issues just to insult the software. If you have a problem with installing AzuraCast via our [recommended installation method](https://www.azuracast.com/install/docker.html) you can create an issue where you describe what problems you encountered and what error messages you get.
