### ISSUE TITLE
Websocket message is not sent

### ISSUE THREAD

**Issue by ahmaxed** [AzuraCast/AzuraCast#2793]
**Using Docker installation method**

Yes

**Host Operating System**

Ubuntu 18.04 (LTS) x64

**Describe the bug**

Although the standard now playing api and static now playing JSON file work, the client stops receiving Websocket messages. 

There are no errors on the browser console.

The issue has been resolved by clearing the cache and updating; however, since I have experienced this issue for the second time in the past couple of months, I was wondering if there is a way to prevent it from happening in the future. 

**Relevant Logs**

https://gist.github.com/ahmadabdolsaheb/3cced2dbdce8ede3826058f6cbe1e3d0

**Device(s):**
The device should be irrelevant since I could see the number of listeners drop to near zero from the dashboard.

**Comment by SlvrEagle23** [comment]
@ahmadabdolsaheb This isn't actually the first report of this, and now I'm wondering if nchan is rejecting an invalid input from our websocket dispatcher and then not letting subsequent inputs through, or something else like that.

Frustratingly, based on your logs it appears it's not actually logging the source of the problem (which would be with nginx, and thus on the `web` container). If we can learn more about what's causing this, we can diagnose it further.

**Comment by stardevelop** [comment]
I have also problem with connecting socket to my address.

**Comment by ahmadabdolsaheb** [comment]
The issue reoccured on our instance every couple of months.
here are the logs: https://gist.github.com/ahmadabdolsaheb/71d2ef35050f0f45c917759b8da23c1a
I believe this is the related log item that also appeared in the previous logs linked above in the issue: 
`web_1       | 2020/09/13 15:32:42 [warn] 53#53: *4151306 nchan: Missed message for websocket subscriber: previous message id times don't match. The message probably expired., client: 162.158.63.250, server: localhost, request: "GET /api/live/nowplaying/coderadio?last_event_id=1600009997%3A0 HTTP/1.1", host: "coderadio-admin.freecodecamp.org"`

**Comment by ahmadabdolsaheb** [comment]
I am considering to use Static Now Playing JSON File to avoid this issue. Are there any known issues that I need to take into account?

**Comment by ahmadabdolsaheb** [comment]
Additionally, websocket seem to stop on some browsers if it is used in a background tab for 30+ min approx;
https://github.com/freeCodeCamp/coderadio-client/issues/80#issuecomment-729654904
