### ISSUE TITLE
Fails to save Liquidsoap Configuration

### ISSUE THREAD

**Issue by pavlos2** [AzuraCast/AzuraCast#2796]
Hi, I tried many times to save the Liquidsoap Configuration file, it fails. I have updated/restarted azuracast and server. Anyone else encountering the same issue?

**Comment by SlvrEagle23** [comment]
@pavlos2 I looked into this issue and was able to reproduce it locally. I figured out what was causing it (a recent change we made to improve type safety for backend/frontend settings) and it should now be resolved as of the latest update.

**Comment by pavlos2** [comment]
Thanks a lot Buster! Great support!
