### ISSUE TITLE
Enabling Let's Encrypt SSL https://

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#2799]
Hello,

I can´t enable LetsEncrypt https:// on ip with Azuracast:

Ubuntu 16 ou 18

Installation: Ansible

Can you help me please?

Thank you

**Comment by SC2Mitch** [comment]
Hi, you can use CertBot for SSL certificates, 

https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx

**Comment by xewl** [comment]
For a certificate, you need a domain name.

**Comment by CodeSteele** [comment]
Yep, as @xewl said, you have to have a domain name to get an SSL cert from Let's Encrypt.
