### ISSUE TITLE
Error generating certificate with Let's encrypt

### ISSUE THREAD

**Issue by starfrosch** [AzuraCast/AzuraCast#2800]
I run
./docker.sh letsencrypt-create my.domain.com
as root and get the following erros on Ubuntu 20 LTS with the latest Azuracast Docker install with self signed certificate.

Domain name my.domain.com is not set up with LetsEncrypt yet. Reverting to self-signed cert...
Generating a RSA private key
.......+++++
..............................................................................+++++
writing new private key to '/etc/letsencrypt/selfsigned.key'
req: Can't open "/etc/letsencrypt/selfsigned.key" for writing, Permission denied
kill: (45): No such process
Self-signed certificate restored.

Any ideas?

**Comment by SC2Mitch** [comment]
Hi, if you have an SSL on your base domain, you can customize Docker to help you. 

https://www.azuracast.com/extending/modifying_docker.html#common-examples

**Comment by starfrosch** [comment]
It's on a fresh installed Digitalocean server with no other services running than Azuracast.

**Comment by starfrosch** [comment]
Just for the records. I had to update Docker manualy with

apt update
apt upgrade

When you run into an error updating Docker on Ubuntu 20 see
https://forums.docker.com/t/cant-install-docker-on-ubuntu-20-04/93058/3ö

**Comment by zatanax** [comment]
i have the same error 
writing new private key to '/etc/letsencrypt/selfsigned.key'
req: Can't open "/etc/letsencrypt/selfsigned.key" for writing, Permission denied
Self-signed certificate restored.

just update  upgrade linux ,
apt update
apt upgrade
update dockers ,
https://www.azuracast.com/administration/system/updating.html#docker-installations
 update azuracast and rut the script and work
https://www.azuracast.com/extending/letsencrypt.html#important-considerations
