### ISSUE TITLE
Playlists Issue

### ISSUE THREAD

**Issue by arusi01** [AzuraCast/AzuraCast#2802]
I cannot add more playlists or schedule because liquidsoap stop working and get this error:

Liquidsoap encountered an error
Re-raised at file "lang/lang_errors.ml", line 155, characters 48-55
Called from file "lang/lang.ml", line 671, characters 8-163
Called from file "lang/lang.ml", line 678, characters 4-76
Called from file "main.ml", line 125, characters 34-40
Called from file "main.ml", line 668, characters 6-16
Called from file "runner.ml", line 30, characters 14-31

I´ve 11 playlist with the Only loop through playlist once and Only play one track at scheduled time checked and all have 4 schedules of one hour each enabled
AzuraCast  v0.10.1

**Comment by SlvrEagle23** [comment]
@arusi01 This should be fixed as of the very latest version of AzuraCast. How recently have you updated your installation?

**Comment by arusi01** [comment]
I´m using the latest version

**Comment by SlvrEagle23** [comment]
@arusi01 Are you on Docker or Ansible?

**Comment by arusi01** [comment]
Docker

**Comment by SlvrEagle23** [comment]
@arusi01 Hmm...this issue should've been expressly fixed as of this weekend, as long as your Docker containers have been updated within the last day. Our stock DigitalOcean one-click image doesn't have the fix in place yet if you're using that.

**Comment by arusi01** [comment]
im not using DigitalOcean

**Comment by SlvrEagle23** [comment]
@arusi01 What is your full version string (in the footer of the application), including commit hash?

**Comment by arusi01** [comment]
Powered by AzuraCast • v0.10.1, #3656165 (2020-04-26 13:44) • Docker • PHP 7.4

**Comment by SlvrEagle23** [comment]
@arusi01 That is not the latest rolling update; even though you're on 0.10.1 and that's still our latest release version, we have several updates that have been released since then.

Update your installation with:
```
cd /var/azuracast
./docker.sh update-self
./docker.sh update
```
and let me know if the issue persists with a newer update version.

**Comment by arusi01** [comment]
ok thanks

**Comment by arusi01** [comment]
thanks how its fixed

Powered by AzuraCast • v0.10.1, #5203e8d (2020-05-05 4:47) • Docker • PHP 7.4
