### ISSUE TITLE
Can't start Liquid Soap. Source fallible

### ISSUE THREAD

**Issue by radiorueda** [AzuraCast/AzuraCast#2805]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu 20.04

**Describe the bug**
Can't start Liquid Soap.
Error 7: Invalid value: That source is fallible

**Device(s):**
 - Device: Mac 
 - OS: High Sierra
 - Browser: Firefox
 - Version: 75.0

**Comment by mevaka** [comment]
Same error With Ubuntu 18.04

Digital Ocean Docker installation.

```
Liquidsoap encountered an error
At line 141, char 8-43:
Error 7: Invalid value: That source is fallible
```

**Comment by SlvrEagle23** [comment]
@mevaka @radiorueda Updating your installation via SSH should fix this:

```
cd /var/azuracast
./docker.sh update-self
./docker.sh update
```

**Comment by radiorueda** [comment]
@SlvrEagle23 dear, already updated via ssh but error stills here.

> At line 271, char 8-43:
Error 7: Invalid value: That source is fallible

is there any other place where I could check in order to give you more information?
Thank you very much for your efforts.

**Comment by SlvrEagle23** [comment]
@radiorueda From `Utilities` > `Log Viewer`, view the Liquidsoap configuration (`liquidsoap.liq`) file...you can copy/paste that into a text editor or just paste it here (remove any passwords, though) so we can find line 271.

**Comment by radiorueda** [comment]
# WARNING! This file is automatically generated by AzuraCast.
# Do not update it directly!


set("init.daemon", false)
set("init.daemon.pidfile.path","/var/azuracast/stations/radiorueda/config/liquidsoap.pid")
set("log.stdout", true)
set("log.file", false)
set("server.telnet",true)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port", 8004)
set("harbor.bind_addrs",["0.0.0.0"])

set("tag.encodings",["UTF-8","ISO-8859-1"])
set("encoder.encoder.export",["artist","title","album","song"])

setenv("TZ", "Europe/Bratislava")


playlist_1_music = playlist(id="playlist_1_music",mode="randomize",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_1_music.m3u")
playlist_1_music = audio_to_stereo(id="stereo_playlist_1_music", playlist_1_music)
playlist_1_music = cue_cut(id="cue_playlist_1_music", playlist_1_music)

playlist_club_gabou = playlist(id="playlist_club_gabou",mode="randomize",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_club_gabou.m3u")
playlist_club_gabou = audio_to_stereo(id="stereo_playlist_club_gabou", playlist_club_gabou)
playlist_club_gabou = cue_cut(id="cue_playlist_club_gabou", playlist_club_gabou)

playlist_el_adn_sonoamericano = playlist(id="playlist_el_adn_sonoamericano",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_el_adn_sonoamericano.m3u")
playlist_el_adn_sonoamericano = audio_to_stereo(id="stereo_playlist_el_adn_sonoamericano", playlist_el_adn_sonoamericano)
playlist_el_adn_sonoamericano = cue_cut(id="cue_playlist_el_adn_sonoamericano", playlist_el_adn_sonoamericano)

playlist_el_ruido_es_el_mensaje = playlist(id="playlist_el_ruido_es_el_mensaje",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_el_ruido_es_el_mensaje.m3u")
playlist_el_ruido_es_el_mensaje = audio_to_stereo(id="stereo_playlist_el_ruido_es_el_mensaje", playlist_el_ruido_es_el_mensaje)
playlist_el_ruido_es_el_mensaje = cue_cut(id="cue_playlist_el_ruido_es_el_mensaje", playlist_el_ruido_es_el_mensaje)

playlist_en_dos_ruedas = playlist(id="playlist_en_dos_ruedas",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_en_dos_ruedas.m3u")
playlist_en_dos_ruedas = audio_to_stereo(id="stereo_playlist_en_dos_ruedas", playlist_en_dos_ruedas)
playlist_en_dos_ruedas = cue_cut(id="cue_playlist_en_dos_ruedas", playlist_en_dos_ruedas)

playlist_kayak_big_25 = playlist.merge(id="playlist_kayak_big_25","/var/azuracast/stations/radiorueda/playlists/playlist_kayak_big_25.m3u")
playlist_kayak_big_25 = audio_to_stereo(id="stereo_playlist_kayak_big_25", playlist_kayak_big_25)
playlist_kayak_big_25 = cue_cut(id="cue_playlist_kayak_big_25", playlist_kayak_big_25)

playlist_la_mar_en_coche = playlist(id="playlist_la_mar_en_coche",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_la_mar_en_coche.m3u")
playlist_la_mar_en_coche = audio_to_stereo(id="stereo_playlist_la_mar_en_coche", playlist_la_mar_en_coche)
playlist_la_mar_en_coche = cue_cut(id="cue_playlist_la_mar_en_coche", playlist_la_mar_en_coche)

playlist_limbo = playlist(id="playlist_limbo",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_limbo.m3u")
playlist_limbo = audio_to_stereo(id="stereo_playlist_limbo", playlist_limbo)
playlist_limbo = cue_cut(id="cue_playlist_limbo", playlist_limbo)

playlist_live_show = playlist(id="playlist_live_show",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_live_show.m3u")
playlist_live_show = audio_to_stereo(id="stereo_playlist_live_show", playlist_live_show)
playlist_live_show = cue_cut(id="cue_playlist_live_show", playlist_live_show)

playlist_magnetik_sounds = playlist(id="playlist_magnetik_sounds",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_magnetik_sounds.m3u")
playlist_magnetik_sounds = audio_to_stereo(id="stereo_playlist_magnetik_sounds", playlist_magnetik_sounds)
playlist_magnetik_sounds = cue_cut(id="cue_playlist_magnetik_sounds", playlist_magnetik_sounds)

playlist_metal = playlist(id="playlist_metal",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_metal.m3u")
playlist_metal = audio_to_stereo(id="stereo_playlist_metal", playlist_metal)
playlist_metal = cue_cut(id="cue_playlist_metal", playlist_metal)

playlist_musica_cretina = playlist(id="playlist_musica_cretina",mode="randomize",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_musica_cretina.m3u")
playlist_musica_cretina = audio_to_stereo(id="stereo_playlist_musica_cretina", playlist_musica_cretina)
playlist_musica_cretina = cue_cut(id="cue_playlist_musica_cretina", playlist_musica_cretina)

playlist_netfliz = playlist(id="playlist_netfliz",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_netfliz.m3u")
playlist_netfliz = audio_to_stereo(id="stereo_playlist_netfliz", playlist_netfliz)
playlist_netfliz = cue_cut(id="cue_playlist_netfliz", playlist_netfliz)

playlist_one_world = playlist(id="playlist_one_world",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_one_world.m3u")
playlist_one_world = audio_to_stereo(id="stereo_playlist_one_world", playlist_one_world)
playlist_one_world = cue_cut(id="cue_playlist_one_world", playlist_one_world)

playlist_paul_vens = playlist(id="playlist_paul_vens",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_paul_vens.m3u")
playlist_paul_vens = audio_to_stereo(id="stereo_playlist_paul_vens", playlist_paul_vens)
playlist_paul_vens = cue_cut(id="cue_playlist_paul_vens", playlist_paul_vens)

playlist_random_cabeza = playlist(id="playlist_random_cabeza",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_random_cabeza.m3u")
playlist_random_cabeza = audio_to_stereo(id="stereo_playlist_random_cabeza", playlist_random_cabeza)
playlist_random_cabeza = cue_cut(id="cue_playlist_random_cabeza", playlist_random_cabeza)

playlist_sinthetica_radio = playlist(id="playlist_sinthetica_radio",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_sinthetica_radio.m3u")
playlist_sinthetica_radio = audio_to_stereo(id="stereo_playlist_sinthetica_radio", playlist_sinthetica_radio)
playlist_sinthetica_radio = cue_cut(id="cue_playlist_sinthetica_radio", playlist_sinthetica_radio)

playlist_sudestada_stream_radio = playlist(id="playlist_sudestada_stream_radio",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_sudestada_stream_radio.m3u")
playlist_sudestada_stream_radio = audio_to_stereo(id="stereo_playlist_sudestada_stream_radio", playlist_sudestada_stream_radio)
playlist_sudestada_stream_radio = cue_cut(id="cue_playlist_sudestada_stream_radio", playlist_sudestada_stream_radio)

playlist_the_music_of_the_year_of_your_birth = playlist(id="playlist_the_music_of_the_year_of_your_birth",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_the_music_of_the_year_of_your_birth.m3u")
playlist_the_music_of_the_year_of_your_birth = audio_to_stereo(id="stereo_playlist_the_music_of_the_year_of_your_birth", playlist_the_music_of_the_year_of_your_birth)
playlist_the_music_of_the_year_of_your_birth = cue_cut(id="cue_playlist_the_music_of_the_year_of_your_birth", playlist_the_music_of_the_year_of_your_birth)

playlist_transmisiones_oceanicas = playlist(id="playlist_transmisiones_oceanicas",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_transmisiones_oceanicas.m3u")
playlist_transmisiones_oceanicas = audio_to_stereo(id="stereo_playlist_transmisiones_oceanicas", playlist_transmisiones_oceanicas)
playlist_transmisiones_oceanicas = cue_cut(id="cue_playlist_transmisiones_oceanicas", playlist_transmisiones_oceanicas)

playlist_xp = playlist(id="playlist_xp",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_xp.m3u")
playlist_xp = audio_to_stereo(id="stereo_playlist_xp", playlist_xp)
playlist_xp = cue_cut(id="cue_playlist_xp", playlist_xp)

playlist_mensajes_de_oyentes = playlist(id="playlist_mensajes_de_oyentes",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_mensajes_de_oyentes.m3u")
playlist_mensajes_de_oyentes = audio_to_stereo(id="stereo_playlist_mensajes_de_oyentes", playlist_mensajes_de_oyentes)
playlist_mensajes_de_oyentes = cue_cut(id="cue_playlist_mensajes_de_oyentes", playlist_mensajes_de_oyentes)

playlist_escuchas = playlist(id="playlist_escuchas",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_escuchas.m3u")
playlist_escuchas = audio_to_stereo(id="stereo_playlist_escuchas", playlist_escuchas)
playlist_escuchas = cue_cut(id="cue_playlist_escuchas", playlist_escuchas)

playlist_llenemos_el_aire_de = playlist(id="playlist_llenemos_el_aire_de",mode="randomize",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_llenemos_el_aire_de.m3u")
playlist_llenemos_el_aire_de = audio_to_stereo(id="stereo_playlist_llenemos_el_aire_de", playlist_llenemos_el_aire_de)
playlist_llenemos_el_aire_de = cue_cut(id="cue_playlist_llenemos_el_aire_de", playlist_llenemos_el_aire_de)

playlist_radio_calle = playlist(id="playlist_radio_calle",mode="randomize",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_radio_calle.m3u")
playlist_radio_calle = audio_to_stereo(id="stereo_playlist_radio_calle", playlist_radio_calle)
playlist_radio_calle = cue_cut(id="cue_playlist_radio_calle", playlist_radio_calle)

playlist_semilleros_creativos = playlist(id="playlist_semilleros_creativos",mode="randomize",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/radiorueda/playlists/playlist_semilleros_creativos.m3u")
playlist_semilleros_creativos = audio_to_stereo(id="stereo_playlist_semilleros_creativos", playlist_semilleros_creativos)
playlist_semilleros_creativos = cue_cut(id="cue_playlist_semilleros_creativos", playlist_semilleros_creativos)

# Standard Playlists
radio = random(id="radiorueda_standard_playlists", weights=[3], [playlist_1_music])

# Standard Schedule Switches
radio = switch(id="radiorueda_schedule_switch", track_sensitive=true, [ ({ (1w or 2w or 3w or 4w or 5w) and 18h0m }, once(playlist_club_gabou)), ({ (6w or 0w) and 13h0m }, once(playlist_el_adn_sonoamericano)), ({ (1w or 2w or 3w or 4w or 5w) and 4h0m }, once(playlist_el_ruido_es_el_mensaje)), ({ 14h0m }, once(playlist_en_dos_ruedas)), ({ (3w or 5w) and 23h0m }, playlist_kayak_big_25), ({ (1w or 2w or 3w or 4w or 5w) and 12h0m }, once(playlist_la_mar_en_coche)), ({ (2w or 3w or 4w or 5w or 6w) and 3h0m }, once(playlist_limbo)), ({ (6w or 0w) and 20h0m }, once(playlist_live_show)), ({ (6w or 0w) and 6h0m }, once(playlist_magnetik_sounds)), ({ (1w or 0w) and 3h0m }, once(playlist_metal)), ({ (1w or 2w or 3w or 4w or 5w) and 22h0m }, once(playlist_musica_cretina)), ({ (2w) and 23h0m }, once(playlist_netfliz)), ({ 10h0m }, playlist_one_world), ({ (6w or 0w) and 12h0m }, once(playlist_paul_vens)), ({ (1w or 4w) and 23h0m }, once(playlist_random_cabeza)), ({ (0w or 6w) and 4h0m }, once(playlist_sinthetica_radio)), ({ (6w or 0w) and 16h0m-16h50m }, once(playlist_sudestada_stream_radio)), ({ (1w or 2w or 3w or 4w or 5w) and 16h0m }, once(playlist_the_music_of_the_year_of_your_birth)), ({ (6w) and 23h0m }, once(playlist_transmisiones_oceanicas)), ({ (2w or 4w) and 5h0m }, once(playlist_xp)), ({true}, radio) ])

# Once per x Songs Playlists
radio = rotate(weights=[1,50], [once(playlist_escuchas), radio])
radio = rotate(weights=[1,25], [once(playlist_llenemos_el_aire_de), radio])
radio = rotate(weights=[1,100], [once(playlist_radio_calle), radio])
radio = rotate(weights=[1,80], [playlist_semilleros_creativos, radio])

# Once per x Minutes Playlists
radio = fallback(track_sensitive=true, [delay(36000., playlist_mensajes_de_oyentes), radio])

# AutoDJ Next Song Script
def azuracast_next_song() =
    uri = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/nextsong --form api_auth="^string.quote("2403f4903e1f5e9ce34411651377973654fab62c5d4059c689d0f6618d4d3e08203279e0c50ba007209a269bc2ab8ec09ae7")^""), default="")
    log("AzuraCast Raw Response: #{uri}")
    
    if uri == "" or string.match(pattern="Error", uri) then
        log("AzuraCast Error: Delaying subsequent requests...")
        system("sleep 2")
        request.create("")
    else
        request.create(uri)
    end
end

dynamic = request.dynamic(id="radiorueda_next_song", timeout=20., azuracast_next_song)
dynamic = audio_to_stereo(id="radiorueda_stereo_next_song", dynamic)
dynamic = cue_cut(id="radiorueda_cue_next_song", dynamic)
radio = fallback(id="radiorueda_autodj_fallback", track_sensitive = true, [dynamic, radio])

requests = request.queue(id="radiorueda_requests")
requests = audio_to_stereo(id="radiorueda_stereo_requests", requests)
requests = cue_cut(id="radiorueda_cue_requests", requests)
radio = fallback(id="radiorueda_requests_fallback", track_sensitive = true, [requests, radio])

add_skip_command(radio)

radio = fallback(id="radiorueda_safe_fallback", track_sensitive = false, [radio, single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")])

radio = crossfade(smart=true, duration=1.50,fade_out=1.,fade_in=1.,radio)

# DJ Authentication
live_enabled = ref false
last_authenticated_dj = ref ""
live_dj = ref ""

def dj_auth(auth_user,auth_pw) =
    user = ref ""
    password = ref ""
  
    if (auth_user == "source" or auth_user == "") and (string.match(pattern="(:|,)+", auth_pw)) then
        auth_string = string.split(separator="(:|,)", auth_pw)
        
        user := list.nth(default="", auth_string, 0)
        password := list.nth(default="", auth_string, 2)
    else
        user := auth_user
        password := auth_pw
    end
    
    log("Authenticating DJ: #{!user}")
    
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/auth --form dj-user="^string.quote(!user)^" --form dj-password="^string.quote(!password)^" --form api_auth="^string.quote("2403f4903e1f5e9ce34411651377973654fab62c5d4059c689d0f6618d4d3e08203279e0c50ba007209a269bc2ab8ec09ae7")^""), default="")
    log("AzuraCast DJ Auth Response: #{ret}")
    
    authed = bool_of_string(ret)
    if (authed) then
        last_authenticated_dj := !user
    end
    
    authed
end

def live_connected(header) =
    dj = !last_authenticated_dj
    log("DJ Source connected! Last authenticated DJ: #{dj} - #{header}")
    
    live_enabled := true
    live_dj := dj
    
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/djon --form dj-user="^string.quote(dj)^" --form api_auth="^string.quote("2403f4903e1f5e9ce34411651377973654fab62c5d4059c689d0f6618d4d3e08203279e0c50ba007209a269bc2ab8ec09ae7")^""), default="")
    log("AzuraCast Live Connected Response: #{ret}")
end

def live_disconnected() = 
    dj = !live_dj
    
    log("DJ Source disconnected! Current live DJ: #{dj}")
    
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/djoff --form dj-user="^string.quote(dj)^" --form api_auth="^string.quote("2403f4903e1f5e9ce34411651377973654fab62c5d4059c689d0f6618d4d3e08203279e0c50ba007209a269bc2ab8ec09ae7")^""), default="")
    log("AzuraCast Live Disconnected Response: #{ret}")
    
    live_enabled := false
    last_authenticated_dj := ""
    live_dj := ""
end 

# A Pre-DJ source of radio that can be broadcast if needed
radio_without_live = radio
ignore(radio_without_live)

# Live Broadcasting
live = audio_to_stereo(input.harbor("/", id = "radiorueda_input_streamer", port = 8005, auth = dj_auth, icy = true, icy_metadata_charset = "UTF-8", metadata_charset = "UTF-8", on_connect = live_connected, on_disconnect = live_disconnected, buffer = 5., max = 10.))
ignore(output.dummy(live, fallible=true))

radio = fallback(id="radiorueda_live_fallback", replay_metadata=false, track_sensitive=false, [live, radio])

# Record Live Broadcasts
stop_recording_f = ref (fun () -> ())

def start_recording(path) =
    output_live_recording = output.file(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), fallible=true, reopen_on_metadata=false, "#{path}", live)
    stop_recording_f := fun () -> source.shutdown(output_live_recording)
end

def stop_recording() =
    f = !stop_recording_f
    f ()
    
    stop_recording_f := fun () -> ()
end

server.register(namespace="recording", description="Start recording.", usage="recording.start filename", "start", fun (s) -> begin start_recording(s) "Done!" end)
server.register(namespace="recording", description="Stop recording.", usage="recording.stop", "stop", fun (s) -> begin stop_recording() "Done!" end)

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

# Apply amplification metadata (if supplied)
radio = amplify(override="liq_amplify", 1., radio)

# Normalization and Compression
radio = normalize(target = 0., window = 0.03, gain_min = -16., gain_max = 0., radio)
radio = compress.exponential(radio, mu = 1.0)

# Send metadata changes back to AzuraCast
def metadata_updated(m) =
    if (m["song_id"] != "") then
        ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/feedback --form song="^string.quote(m["song_id"])^" --form media="^string.quote(m["media_id"])^" --form playlist="^string.quote(m["playlist_id"])^" --form api_auth="^string.quote("2403f4903e1f5e9ce34411651377973654fab62c5d4059c689d0f6618d4d3e08203279e0c50ba007209a269bc2ab8ec09ae7")^""), default="")
        log("AzuraCast Feedback Response: #{ret}")
    end
end

radio = on_metadata(metadata_updated,radio)

# Local Broadcasts
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), id="radiorueda_local_1", host = "127.0.0.1", port = 8000, password = “xxxxxxxxxxx:#1”, icy_id = 1, name = "RADIORUEDA.COM", description = "control panel", genre = "InterPermaCultural, Experimental, Bilingual, Artivist & Humana", url = "www.radiorueda.com", public = false, encoding = "UTF-8", protocol="icy", radio)

# Remote Relays

**Comment by mevaka** [comment]
By the way;
@SlvrEagle23 
My server is Ubuntu 18.04 (From Digital Ocean Azura MarketPlace)
And update worked for me.
Now , there is no error after update.

@radiorueda 
Maybe its about Ubuntu 20.04

**Comment by SlvrEagle23** [comment]
@radiorueda If your AzuraCast code was on the latest rolling-release version as of this week, you would have a section of configuration just after the crossfade that was basically a fallback, which would  fix the issue. Please try updating your installation again to the latest version.

**Comment by radiorueda** [comment]
@SlvrEagle23 ok! done and fixed. but i have the setting PREFER_RELEASE_BUILDS=true and i don't know if i am in the latest version (0.10.2) because i don't see that section.  anyway is working now, thank you very much águila plateada :)
![Screen Shot 2020-05-07 at 05 35 31](https://user-images.githubusercontent.com/60315802/81251891-b77f0a00-9024-11ea-92da-9b154c81d49b.png)

**Comment by dbeiner** [comment]
@radiorueda How do you do to fix this issue ? Thank you !

**Comment by radiorueda** [comment]
@dbeiner i solved it just updating azuracast


  
www.radiorueda.com

**Comment by dbeiner** [comment]
Thank you for your reply.

Strange, it doesn't work for me... :(

I've open a case #2858 @SlvrEagle23
