### ISSUE TITLE
Can't access to some API Endpoint which need Api Key on Postman

### ISSUE THREAD

**Issue by navalex** [AzuraCast/AzuraCast#2806]
**Using Docker installation method**

Yes

**Host Operating System**

Ubuntu 20.04 Server

**Describe the bug**

When, in Postman, i call for example "http://serverip/api/station/{stationid}/files" GET method, with my API Token put in Bearer auth field, it redirect me to the login page.

**To Reproduce**

I created my API key with my Super Admin account, tried it in Bearer field, API key field, and I also did it by adding the header X-API-key on my request, and it always redirect me to the login page.

**Expected behavior**

I expected to logged in to my API and got my response

**Relevant Logs**

I checked logs, i got nothing about the api

**Device(s):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81

**Additional context**
My Azuracast installation is on a VPS, so it's across domain calling. I tried to do the same call in a local reactjs app with Axios, and got a CROS domain error, but I not sure if it's the actual problem.

**Comment by pascalla** [comment]
I have just taken the same steps and was able to retrieve all files.

**Comment by navalex** [comment]
Well, sorry, i just stupid... i forgot to add /api in my URL...
I close
