### ISSUE TITLE
Quantity of songs differes between Liquid Soap and Music Files folder

### ISSUE THREAD

**Issue by radiorueda** [AzuraCast/AzuraCast#2808]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.2, Release build

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
**Screenshots**

**Device(s):**
Mbp
High Sierra
Firefox 75.0
![Screen Shot 2020-05-07 at 06 06 44](https://user-images.githubusercontent.com/60315802/81254485-7b9b7300-902b-11ea-8761-c2a4730274b8.png)
![Screen Shot 2020-05-07 at 06 07 09](https://user-images.githubusercontent.com/60315802/81254487-7ccca000-902b-11ea-8b7c-2230a9476df4.png)

**Comment by Alias1975** [comment]
Hi,
this is the number of songs selected in the playlist (37) and not the total of the songs in the archive

**Comment by radiorueda** [comment]
hi riccardo, thanks for your time. i still dont understand, could you explain me how is possible that there are more songs in the playlists than in the music file folder? thanks again

**Comment by Alias1975** [comment]
on the left menu "media file" are stored all mp3.
you can select part of them in one or more playlists.
example
media folder 
a.mp3
b.mp3
c.mp3
playlist
a.mp3
b.mp3

the number of songs in the playlist can be smaller than in the archive.

![image](https://user-images.githubusercontent.com/28431738/81400114-b33e1400-912c-11ea-94d0-42239182dac5.png)
this is the number of mp3 inside playlist

**Comment by radiorueda** [comment]
yes @Alias1975  but the thing is that there are more songs in the playlists than uploaded to media files. i mean, the number of songs in the playlist are bigger than in the archive. (1943 in music files, 2108 in the playlists). i feel a little fool about it but also scared because like 3 months ago one provider deleted all the files in the server because he said that there started to auto-duplicate. i want to avoid that kind of issue. thank you

**Comment by Alias1975** [comment]
well now i understand... 
try this attemp:
export all playlists as m3u and check for duplicates.
if you find identical duplicates then the root of the song is the same therefore not physically duplicated.
if instead you have 2 different roots for the same song then it is possible that duplicates have been created.

**Comment by radiorueda** [comment]
ok @Alias1975 something weird happened. i re-check the music files menu and one folder was checked to 2 playlists. the curious thing is that before it was not appearing at that way. thank you for your help dear
