### ISSUE TITLE
Better widget concept

### ISSUE THREAD

**Issue by voipworld** [AzuraCast/AzuraCast#281]
Hi Azura Team,

i would be glad to propause a better widget concept, to be used in diferent web sites & hibrid mobile apps for radios that use AzuraCast

personaly, i dont like the concept of a public page because it uses iframe
the best way is to implement a JS code that push the HTML code in a specific div
with this concept, we can introduce diferent widget, and the owner can put the widgets wherever he want
for example we can implement a widget for a player only, with another display that display the currently playing song
another widget that could display scheduling up on the completion of the scheduling concept, and so on
what do you think guys?

**Comment by SlvrEagle23** [comment]
@voipworld I don't personally intend to spend that much time building support for custom widgets in AzuraCast, as this is a largely solved problem in the form of many other embeddable radio players:

 - https://www.muses.org/setup
 - http://jplayer.org/

...and many others.

The purpose of the existing public page is to serve as an easy embeddable thing for stations wanting something out of the box, and also providing code examples for the more common scenario of users wanting to build the radio player directly into an existing website.

**Comment by rolradio** [comment]
I have already asked that question, especially for an embedded version of what is playing now and what songs have played there. see this point https://github.com/AzuraCast/AzuraCast/issues/158
All these data can be found via the station api.    
Unfortunately, I do not come here to expand it into a presentable whole for my website. Are there people here who already use this on their website? And should we have a few examples of this? Thank you in advance
