### ISSUE TITLE
docker-compose.override.yml error path media external

### ISSUE THREAD

**Issue by Alias1975** [AzuraCast/AzuraCast#2810]
Hello, i tried to change folder media through a mount cifs.
Ubuntu 18.04 
when i call the command line in ubuntu 
`cd /home/liquidisoap/rep
ls -a`
i see all media.

so I followed the guide:
`docker-compose down`

and i make docker-compose.override.yml with follow parameters:

`# docker-compose.override.yml
version: '2.2'

services:
  web:
    volumes:
     - /home/liquidisoap/rep:/var/azuracast/stations/archivio/media

  stations:
    volumes:
     - /home/liquidisoap/rep:/var/azuracast/stations/archivio/media`

when i launch:
`docker-compose up -d`

the error that i see is:
"yaml.scanner.ScannerError: while scanning for the next token found character '\t' that cannot start any token in ./docker-compose.override.yml, line 4, column 1

surely I make some mistakes but I don't understand where.
NB archivio is a new station previously created by the azuracast panel,

thanks in advice for the support.

**Comment by SlvrEagle23** [comment]
@Alias1975 The `\t` character is the character that's entered when you press the "Tab" key. You probably have a tab in there where it should be indented with spaces. You can usually determine this by moving your cursor over the empty spaces: where it jumps over more than one space at a time, that's where you have a tab and should replace it with spaces.

**Comment by Alias1975** [comment]
Thanks a lot SlvrEagle23...
now i have another problem...
when i restart 
'docker-compose up -d'
i see this mistake:
**service must be mapping, not a NoneType**

I think i need to take action on the .env file, but i don't know how
