### ISSUE TITLE
Playlist's Not playing at the correct time.

### ISSUE THREAD

**Issue by adavenport-ops** [AzuraCast/AzuraCast#2812]
I have an issue that the playlists are not playing at the correct time. We will have a show that should play at 6 pm but does not queue or play. I have Created 2nd station for testing and I am unable to get a show to queue with General, Advanced settings. I have also tried to Interrupt and without that setting. 

**Using Docker installation method**

**AzuraCast version**

v0.10.2, #1229f2b (2020-05-07 0:05)
**Host Operating System**

Ubuntu 20.04 LTS
**Describe the bug**

Failure to play the song at the selected time
**To Reproduce**

Create a station and attach a playlist of a show.

**Expected behavior**

[Liquidsoap Log.log](https://github.com/AzuraCast/AzuraCast/files/4594531/Liquidsoap.Log.log)
[Liquidsoap Configuration.log](https://github.com/AzuraCast/AzuraCast/files/4594532/Liquidsoap.Configuration.log)

**Screenshots**

![Screen Shot 2020-05-07 at 9 02 04 AM](https://user-images.githubusercontent.com/43224322/81323310-0be8b080-904a-11ea-96a5-dab8e842be4d.png)
![Screen Shot 2020-05-07 at 9 02 16 AM](https://user-images.githubusercontent.com/43224322/81323325-1014ce00-904a-11ea-9372-c766ed75e95b.png)
![Screen Shot 2020-05-07 at 9 02 26 AM](https://user-images.githubusercontent.com/43224322/81323331-12772800-904a-11ea-89b8-412da25c61cb.png)
![Screen Shot 2020-05-07 at 9 02 34 AM](https://user-images.githubusercontent.com/43224322/81323335-1440eb80-904a-11ea-8639-668056aa3a9c.png)

All Devices see the issue

**Comment by SlvrEagle23** [comment]
@adavenport-ops I appreciate the detail added to the issue, but this is almost word-for-word the title of our pinned issue for this exact same problem, #2631. Please contribute to that issue's thread instead.

**Comment by AmsterdamFM** [comment]
This is probably easily solved by using the highest priority and not pri 1.

**Comment by adavenport-ops** [comment]
@AmsterdamFM I have tried this at a higher rate, and the same issue comes about. We also don't want this within the general rotation, so a lower weight it best if we are forced to use General instead of advanced.
