### ISSUE TITLE
Cannot join to the MariaDB and Redis

### ISSUE THREAD

**Issue by jardaskera** [AzuraCast/AzuraCast#2813]
**Using Docker installation method** Traditional

**AzuraCast version** Latest 5.8.2020

**Host Operating System** Tried Ubuntu 16.04 and 18.04

**Describe the bug** When i complete the fresh install, it will timeout the mariadb and redis. _Sorry for bad english_

**Relevant Logs** 
2020/05/08 08:46:25 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:26 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:27 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:28 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:29 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:30 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:31 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:32 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:33 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:34 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:35 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:36 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:37 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:38 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:39 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:40 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:41 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:42 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:43 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:44 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:45 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:46 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:47 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:48 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:49 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:50 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:51 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:52 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:53 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:54 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:55 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:56 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:57 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:58 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:46:59 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:47:00 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:47:01 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:47:02 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:47:03 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:47:04 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/05/08 08:47:05 Timeout after 40s waiting on dependencies to become available: [tcp://mariadb:3306 tcp://influxdb:8086 tcp://redis:6379]
azuracast_mariadb_1 is up-to-date
azuracast_influxdb_1 is up-to-date
azuracast_stations is up-to-date
azuracast_redis_1 is up-to-date
Creating azuracast_web ... done

**Screenshots**
![image](https://user-images.githubusercontent.com/48823563/81389640-75d08b00-911a-11ea-96c3-0c8099080f8a.png)

**Device(s):**
 - Device:
 - OS:
 - Browser:
 - Version:

**Comment by Alias1975** [comment]
hi,

do not block the process, after a few minutes it connects and completes the installation without errors.

for restart service:
docker-compose down
docker-compose up -d

**Comment by jardaskera** [comment]
> hi,
> 
> do not block the process, after a few minutes it connects and completes the installation without errors.
> 
> for restart service:
> docker-compose down
> docker-compose up -d

Hello, thanks for the quick answer. It works, thank you!
