### ISSUE TITLE
Wrong URL for default album art on public page

### ISSUE THREAD

**Issue by mellis85** [AzuraCast/AzuraCast#2814]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.2, #cadb119 (2020-05-08 6:46)

**Host Operating System**
Debian 10.3

**Describe the bug**
Then you first enter the public page is show correct Default Album Art-image. But when is "updates" is try to open URL: "src="https://localhost/static/img/generic_song.jpg".

**Screenshots**

![image](https://user-images.githubusercontent.com/18250650/81397154-10cf6200-9127-11ea-8499-d25adc6e87d0.png)

**Device(s):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: chrome
 - Version: 81.0

**Comment by SlvrEagle23** [comment]
@mellis85 Do you have a "Base URL" set in your system settings panel? That should fix it in the immediate term. I'll look into fixing it in the longer term.

**Comment by mellis85** [comment]
Yes, i have set a "Base URL". When enter the page is shows the right "Base URL". But when it updates replaces my "Base URL" to "localhost".

**Comment by SlvrEagle23** [comment]
@mellis85 Trying to reproduce this issue on my local installation and I'm having trouble.

Are the following settings checked or unchecked in your installation?

 - Prefer Browser URL
 - Force HTTPS
 - Use Websocket for Now Playing Updates

**Comment by SlvrEagle23** [comment]
@mellis85 This issue should now be fixed as of the latest update published this evening.
