### ISSUE TITLE
URLs

### ISSUE THREAD

**Issue by Richard399** [AzuraCast/AzuraCast#2816]
Hi,

I have a site on a separate shard server and azuracast on its own VPS

My site theme allows me to create a playlist where I can add the url of an mp3

Of those tracks that I have uploaded to a playlist on AzurCastI; I cannot find the relative link url to any of the tracks uploaded to use on the website?

Any ideas please?

Many Thanks

**Comment by SlvrEagle23** [comment]
@Richard399 We don't provide public download links for any of the tracks in your music library. You can internally retrieve any of the tracks by clicking their filenames on the music files manager (or downloading them via SFTP), but the public can't download the files directly.

**Comment by Richard399** [comment]
Hi @SlvrEagle23,

My apologies, perhaps I wasn't clear.

I have a website that I run the live stream through.

I also have a page that features albums of artists of which I want people to be able to play their track - the problem I'm having is finding the track url in which to add to the player so visitors can click to play.

Does that make more sense? :-)

Regards

**Comment by SlvrEagle23** [comment]
@Richard399 My same answer applies. AzuraCast doesn't have any built-in way for you to provide on-demand listening or streaming to your users. That's not a radio station, that's something else.

**Comment by Richard399** [comment]
Hi,

Understood

Thank you :-)
