### ISSUE TITLE
Play Times

### ISSUE THREAD

**Issue by Richard399** [AzuraCast/AzuraCast#2817]
Hi,

Something weird is going on?

The scheduled programs are playing at the wrong times and, the azuracast dashboard is showing as being one hour behind?

The server time is correct?

Many Thanks

**Comment by SlvrEagle23** [comment]
@Richard399 Are you sure your station's time zone is correct, including to the region you're in with its DST settings? You may be experiencing a shift of time because of DST, and where your previous timezone lined up on standard time it doesn't line up during DST.

**Comment by Richard399** [comment]
Hi @SlvrEagle23

Thanks for responding,

To be honest, I'm a little lost in finding this setting, where do I find the setting you refer please?

Many Thanks :-)

**Comment by SlvrEagle23** [comment]
@Richard399 In the station's profile, the field is named "Time Zone".

**Comment by Richard399** [comment]
Hi

Many Thanks ;-)
