### ISSUE TITLE
remove all files

### ISSUE THREAD

**Issue by RealPwned** [AzuraCast/AzuraCast#2818]
Hi,
how to remove/uninstall all files from AzuraCast?

there is still a bit ram usage from AzuraCast after uninstall

**Comment by Alias1975** [comment]
cd /var/azuracast
sudo docker ps -q
for each id_container that you see 
sudo docker stop <id_container>
sudo docker rm <id_container>

at end of id container type:
sudo docker volume prune -f


bye

**Comment by pitsch** [comment]
`/docker.sh uninstall `
