### ISSUE TITLE
Docker-update not working, interface not reachable 

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#282]
I launched a docker-update today, which ended up in following screen : 
![image](https://user-images.githubusercontent.com/25333002/32826794-1510ac68-c9ea-11e7-8a9e-8a943bb2edcf.png)

Now the interface is not reachable and radios are not streaming, only icecast instances can be reached, but empty.
rebooting server, lauching docker-update.sh would end up in the same screen.
Could you please fix this ?

**Comment by SlvrEagle23** [comment]
@griffon56 I'm not sure what's causing this issue. I'll take a look, but in the meantime can you try running

```
git reset --hard && git pull
```

manually in the docker project root, then running `docker-update.sh` again? That might fix it for your present situation.

**Comment by griffon56** [comment]
sorry same error

**Comment by SlvrEagle23** [comment]
@griffon56 I have pushed a small fix that should help push through that error. You'll likely need to manually run the `git reset --hard && git pull` first to resolve the issue.

**Comment by griffon56** [comment]
Unfortunately, still stuck

![image](https://user-images.githubusercontent.com/25333002/32858701-a6fe6d1a-ca4c-11e7-89cc-bfb245fd49f9.png)

**Comment by SlvrEagle23** [comment]
@griffon56 I'm not seeing this at all on my setups, and I'm not sure what would be causing it. The Docker images, by default, should always allow the azuracast user to write to the /tmp dir.

**Comment by griffon56** [comment]
Sorry for wsasting your time here - there was not a single bit free on my VPS storage ... hence the error

**Comment by SlvrEagle23** [comment]
@griffon56 Aha! That'll do it! The error certainly is cryptic for something like that...no worries. Glad it's fixed. :)
