### ISSUE TITLE
connection problem x times same ip

### ISSUE THREAD

**Issue by fast97** [AzuraCast/AzuraCast#2821]
hello I have a problem with a station which statistics false because there is an ip address which this connects several times.
It is a local ip 168.2xx.x
Thank you for your help

![23](https://user-images.githubusercontent.com/51033222/81452613-9e429e80-9187-11ea-8891-75512fc9444e.png)

**Comment by pascalla** [comment]
Are you upto to date on your Azurcast installation, I believe I saw something recently in an update which would fix this. Please use the correct template when reporting issues!

cf6a3e02aab51f8e72bbc0b063dab48cb37afd8d

**Comment by fast97** [comment]
hello before my request my version was up to date v0.10.2, # 1229f2b (2020-05-07 0:05) thank you.
I'm going to do an update tonight because I saw new repair provided on a new version.
Thank you

**Comment by Jam-Mc** [comment]
Good day
I still have the problem after various updates.

What do I have to do to fix the problem?

**Comment by nknikolay** [comment]
Hello!
I have the same problem. 

All connected listeners have the same ip address, and the delay in ordering songs works as if the order is coming from the same ip (when ordering from different ip, the error "you have already ordered the track before").

I read this ssue, I decided to completely reinstall the docker and AzuraCast - it did not help.

(sorry for my english, this is google translator)

**Comment by Jam-Mc** [comment]
Good Morning

I was able to solve the problem myself and I would have to adjust the player link on the homepage.

Test it when you log into azuracast and start the player from there. I suspect that the players on the left have changed since the update
