### ISSUE TITLE
Live stream - if disconnected first part of recording is missing in admin view

### ISSUE THREAD

**Issue by pixel-paul** [AzuraCast/AzuraCast#2823]
**Using Docker installation method**
Yes

**AzuraCast version**
Powered by AzuraCast • v0.10.2, #d5322de (2020-05-09 0:53) • Docker • PHP 7.4

**Host Operating System**
CentOS 8

**Describe the bug**
Live stream recording, Rekordbox crashed, so was restarted. Butt 0.1.19 may have been restarted too (unhelpfully). Only recording available in admin is the second section of the recording, so first part is missing. Live stream continued ok.

**To Reproduce**
not attempted as of yet

**Expected behavior**
both recordings would appear in the broadcast list.

**Relevant Logs**
none yet

**Screenshots**
n/a

**Device(s):**
 - Device: Desktop
 - OS: Win 10
 - Browser: n/a
 - Version: n/a

**Additional context**
The only recording in the *admin* is the second part of the live stream. The initial recording may be present on the file system.

Very new to this software and interested in the project. Keen to be involved further!

Thanks,

Paul

**Comment by pixel-paul** [comment]
Looking at this further, it seems that Azuracast thinks that the recording is the 60 minutes or so:

May 9, 2020 11:21 PM --> May 10, 2020 12:19 AM

However the recording that is downloaded (recording is set to 320 opus) is only 17 minutes long, which was the length of the second section.

**Comment by pascalla** [comment]
Although this is not a fix for the issue, you can view the recordings with docker

```
docker exec -it webcontainerid bash
cd /var/azuracast/station/stationname/recordings/
```

you can get the id of the web container using ```docker ps```

you can get these recordings off the docker file system with [docker cp](https://docs.docker.com/engine/reference/commandline/cp/)

**Comment by pixel-paul** [comment]
Thanks @pascalla, I can see that there is only one recording present in the folder (so same as in admin).

Therefore, for some reason the recording for the first section did not happen, or was deleted when the reconnection happened. 

The filename for the recording is 20200509-232135.opus, which matches the time that the recording _started_, so perhaps what has happened is that when recornnection occured, the file was overwritten as the same name was used by the recording.

**Comment by Vaalyn** [comment]
Closing this issue since there have been no recent reports of something like this happening.

If someone is still experiencing this problem please let me know so I can re-open this.
