### ISSUE TITLE
Latest docker update broke my station

### ISSUE THREAD

**Issue by davidkamp** [AzuraCast/AzuraCast#2824]
Latest update broke my docker installation and took down two of my stations. (not available anymore)
I followed these instructions: https://www.azuracast.com/administration/system/updating.html

Some screenshots attached. Any ideas what Is happening?
What should I try to fix this?

For some reason I also don't get any error log files.

![Screenshot 2020-05-10 at 11 11 59](https://user-images.githubusercontent.com/7592127/81509894-1935c180-930e-11ea-9ce2-1d49c24f6718.jpg)
![Screenshot 2020-05-10 at 11 28 37](https://user-images.githubusercontent.com/7592127/81509888-15a23a80-930e-11ea-96cc-61f979b3c276.jpg)
![Screenshot 2020-05-10 at 11 24 15](https://user-images.githubusercontent.com/7592127/81509890-16d36780-930e-11ea-9b12-89adf11612d0.jpg)
![Screenshot 2020-05-10 at 11 16 23](https://user-images.githubusercontent.com/7592127/81509891-18049480-930e-11ea-8b5d-b33c677e32c4.jpg)
![Screenshot 2020-05-10 at 11 14 51](https://user-images.githubusercontent.com/7592127/81509892-189d2b00-930e-11ea-9c40-21f993d0b5e7.jpg)
![Screenshot 2020-05-10 at 11 12 10](https://user-images.githubusercontent.com/7592127/81509893-1935c180-930e-11ea-999e-4766a38304a4.jpg)

**Comment by SlvrEagle23** [comment]
@davidkamp We fixed this before releasing version 0.10.2, by changing how we handled our Liquidsoap configuration generation.

Make sure you're on the very newest version of AzuraCast, and then try rewriting each station's configuration via `Utilities` > `Restart Broadcasting` if all else fails.

**Comment by arusi01** [comment]
I think this problem is related to this one too: https://github.com/AzuraCast/AzuraCast/issues/2811

**Comment by SlvrEagle23** [comment]
@arusi01 I don't think they are actually related.

**Comment by davidkamp** [comment]
Here is what solved it for me: 
-Creating a new station with exactly the same files and  settings (station profile, playlist, autodj etc)  as the one I had before the update.
This newly created one works, the station created on the previous azuracast did not work no matter the settings.

Also it seems the crossfade duration now works as expected which is great!
