### ISSUE TITLE
Noob Issue - Public Page - 500 Attribute "station" is required and is empty in this request ServerRequest.php : 184

### ISSUE THREAD

**Issue by JCDavie** [AzuraCast/AzuraCast#2827]
**Using Docker installation method**

**AzuraCast version**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@JCDavie Please remember to actually fill out the issue template when creating a new issue. We don't have any information about your installation or the specific problem you're having.

Based on the title, that error typically appears when you've specified a station ID that doesn't exist, or that has "Hide Public Pages" enabled.

**Comment by JCDavie** [comment]
@SlvrEagle23 apologies, I think its a half noob/half bug issue.   My station was named "205" so it didn't like the numeric value (maybe a URL routing issue).  When I changed the name to "the station" it worked.
