### ISSUE TITLE
Auto Sync Every 5 minutes died

### ISSUE THREAD

**Issue by Siriusa77II** [AzuraCast/AzuraCast#283]
hey! 
I have a issue with the media file check sync
it has not run for more than 17 hours and when I try to run it manually I have a 500 error.
I already try to update via
```./update and ./update -full. and clear cache```
The problem occurred while I uploaded about 3k music. 
only one of the 3 stations is impacted (i cant see music and folder of one of these station).

**Comment by SlvrEagle23** [comment]
@Siriusa77II What are the contents of the error when you attempt to run it manually?

**Comment by Siriusa77II** [comment]
@SlvrEagle23 
```This page isn’t working

diffusion.cloudsdaleradio.com is currently unable to handle this request.
HTTP ERROR 500```
If you need logs tell me where, I dont know where to store the Ngnix logs.

**Comment by SlvrEagle23** [comment]
@Siriusa77II Try manually running:

```
php /var/azuracast/www/util/cli.php sync:run medium
```

...and let me know what it says.

**Comment by Siriusa77II** [comment]
@SlvrEagle23 
```
root@CR-Diffusion-1:~# php /var/azuracast/www/util/cli.php sync:run medium
Running Medium (5-minutes) Sync...

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 69632 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 105
root@CR-Diffusion-1:~#
```

**Comment by SlvrEagle23** [comment]
@Siriusa77II ...that's a new one! How big is your music library exactly?

**Comment by Siriusa77II** [comment]
@SlvrEagle23 2801 files so something like 30Gb
and i have 18K files to upload x) (111Gb)

**Comment by SlvrEagle23** [comment]
@Siriusa77II I have updated the media batch processor to be far more conscious of memory usage, clearing itself out every few songs that get processed. The sync process should run to completion now; let me know if you encounter any issues with the updated code.

**Comment by Siriusa77II** [comment]
@SlvrEagle23 no change, i try update -full look like i had to reinstall every things.
i can try on a test node.
```root@CR-Diffusion-1:/var/azuracast/www# php /var/azuracast/www/util/cli.php sync:run medium
Running Medium (5-minutes) Sync...

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 69632 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 105
root@CR-Diffusion-1:/var/azuracast/www#
```

**Comment by SlvrEagle23** [comment]
@Siriusa77II I've added some more debugging to the CLI script...can you try updating again and letting me know what it says?

I'm also a little worried that your updates aren't picking up changes to the code, as the changes I rolled out earlier this week should absolutely help with that issue. Can you manually run `git reset -hard && git pull` in the AzuraCast root just to make sure it's pulling correctly?

**Comment by Siriusa77II** [comment]
@SlvrEagle23 same...
but i see smth not normal with ram... i will try to upgrade this VPS.
![royalts_2017-11-22_03-29-37](https://user-images.githubusercontent.com/16348488/33107051-a5f869e6-cf35-11e7-8972-e337c9f3f090.png)

**Comment by SlvrEagle23** [comment]
@Siriusa77II Even with the very latest codebase you're not seeing any improvement? You should definitely be seeing more log messages in the command line regarding memory usage if you're on the newest version of the code, as I added in those log messages specifically to help diagnose this type of issue.

**Comment by Siriusa77II** [comment]
Oh! i got somethings new! 
```bash
root@CR-Diffusion-1:/var/azuracast/www# php /var/azuracast/www/util/cli.php sync:run medium
Running Medium (5-minutes) Sync...


  [Doctrine\ORM\ORMInvalidArgumentException]
  A new entity was found through the relationship 'Entity\StationMediaArt#media' that was not configured to cascade persist operations for entity: Entity\StationMedia@000000005e45e300000000007456dc5e. To solve this issue: Either e
  xplicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem i
  mplement 'Entity\StationMedia#__toString()' to get a clue.


sync:run [<task>]

root@CR-Diffusion-1:/var/azuracast/www#
```
error message on red background.

**Comment by SlvrEagle23** [comment]
@Siriusa77II Turns out this issue was more complicated than I expected...I've reworked the album art database tables, and set media to reprocess automatically. Try updating again (it'll also involve a database update) and let me know how it goes.

**Comment by Siriusa77II** [comment]
Look like It's ok, i guess i juste have to reupload everythings. (all song backup on 1Gbps Node)

![2017-11-28_13-35-51](https://user-images.githubusercontent.com/16348488/33320073-47fa4f38-d441-11e7-9592-2fdb9f730883.png)

**Comment by SlvrEagle23** [comment]
@Siriusa77II Good to hear, closing this for now, if you run into any other problems feel free to make a new issue.

**Comment by christiansacks** [comment]
Hey, I'm getting the 5 minutes sync thing not working still, I just upgraded to the latest (docker) version (I was 161 updates behind o.O and I finally decided to upgrade in the hopes to get rid of this 5 minute sync error, but no still the same. in the debug window I can see this;

`[2021-04-09T10:18:05.050930+00:00] AzuraCast.CRITICAL: Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 716800 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 112 [] []
`
Please can anyone give me a nudge in the right direction to fix this?
