### ISSUE TITLE
Raspi / Ansible | Old download url DBIP

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#2830]
There is a wrong/old dbip-url in `/util/ansible/roles/dbip/tasks/main.yml`

correct one:
`    url: https://download.db-ip.com/free/dbip-city-lite-2020-05.mmdb.gz`

**Comment by SlvrEagle23** [comment]
@MrSteelMiner The latest update should fix this by switching to using the current year/month in the URL.

**Comment by MrSteelMiner** [comment]
So it works again. 
/close
