### ISSUE TITLE
Darkice streaming to iceCast

### ISSUE THREAD

**Issue by spenmath** [AzuraCast/AzuraCast#2831]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.2

**Host Operating System**
Ubuntu 18.10

**Describe the bug**
We're currently streaming from a raspi 3b using darkice to another server, trying to move everything over to a self hosted VPS running Azuracast. I can stream to azuracast using BUTT on my mac but when I try to configure Darkice on the raspi there is no option to set a username.

**Additional context**
http://manpages.ubuntu.com/manpages/cosmic/man5/darkice.cfg.5.html

**Queries** 
Is there a setting I can't find in icecast that relaxes the streaming auth settings?

**Comment by pascalla** [comment]
Have you tried connecting with "username:password" format. You can also connect to Azura via Shoutcast which also uses the "username:password" format.

**Comment by spenmath** [comment]
I have tried that, it doesn't work sadly

**Comment by LordHelmchen666** [comment]
Try "username,password" this is working with my Sam Broadcaster.

**Comment by spenmath** [comment]
Amazing! Think that's done it! Many thanks!

**Comment by spenmath** [comment]
Sorry, I thought that had fixed it but I was testing it with shoutcast and not icecast, so problem still exists.

**Comment by spenmath** [comment]
Have drawn a line under this for now and I am streaming quite successfully using shoutcast credentials in darkice.
