### ISSUE TITLE
Corrupted Docker- Help!

### ISSUE THREAD

**Issue by r0nd0n** [AzuraCast/AzuraCast#2832]
My installation had to go through a hard reboot, and now I'm getting:
`./docker.sh: line 3: /bd_build/buildconfig: No such file or directory`
when I try to perform anything. 

Inside this docker installation is a thousands of crowd sourced music files, and several backups, but now I can't access any of it. Even if I could just get access to the music files and start over, that would put me way ahead.

Currently running:
Ubuntu 18.04
And not sure of the exact Azuracast version, but it's been updated a month ago at latest.

I will check this often. please advise if anything can be done. Thank you.

**Comment by SC2Mitch** [comment]
You can still access your backups if you have root access to the VPS under this directory `var/lib/docker/volumes/azuracast_backups/_data` it's strongly recommended to pull those backups and download them locally before resuming with my steps.

While in the terminal, try running `docker version` to see what version it's pulling, if that's broken, reinstall docker, and try to restart the services. 

Worst case is to fully restart and deploy the backup.

**Comment by SlvrEagle23** [comment]
@r0nd0n It seems like you had a failed download of the Docker utility script and need to download a new version of it.

You should follow these commands in your SSH terminal:

```bash
cd /var/azuracast
curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh
chmod a+x docker.sh

./docker.sh update
```

**Comment by r0nd0n** [comment]
Thanks to the help I was able to get all the files backed up, but after curl'ing the docker.sh and running it, I'm getting:
`/var/azuracast# ./docker.sh update
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Update complete!
`

`docker version` returns fine, so that seems to be in order, but it seems my installation is borked. 

Is there anymore steps I can take, or should I just reinstall azuracast and restore from backup?

**Comment by SC2Mitch** [comment]
Try `systemctl restart docker` and see if that allows you to run the update

**Comment by r0nd0n** [comment]
Docker was showing version, but was completely corrupted, along with many many other crucial files, so I've taken what I could and will reinstall. Thanks for the help.
