### ISSUE TITLE
Since last update AutoDJ is bugged or something

### ISSUE THREAD

**Issue by SubwooferNL** [AzuraCast/AzuraCast#2833]
Hello,
i use Azuracast on a VMWare vps.
i was using azuracast version 0.9.8 or 9.9 and i had no issues.
so i was deciding to update to a new release 0.10.2 but now i have all kinds of problems.
i use azuracast to relay to another shoutcast instance(host)
my problem at this moment
AutoDJ is working.
Metadata is updating to the shoutcast server (relay)
but in the on air card its saying its offline
this is why azuracast cant handle requests ?
becaus its not working

here is the liquidsoap log

2020/05/14 12:51:33 >>> LOG START

2020/05/14 12:51:33 [main:3] Liquidsoap 1.4.2
2020/05/14 12:51:33 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.3 sedlex=2.1 menhirLib=20200211 dtools=0.4.2 duppy=0.8.0 cry=0.6.1 mm=0.5.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.3 mad=0.4.5 flac=0.1.5 flac.ogg=0.1.5 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.3.1 ffmpeg=0.4.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.9 camomile=1.0.2 faad=0.4.0
2020/05/14 12:51:33 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2020/05/14 12:51:33 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2020/05/14 12:51:33 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2020/05/14 12:51:33 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2020/05/14 12:51:33 [decoder:3] Method "FFMPEG" accepted "/usr/local/share/icecast/web/error.mp3".
2020/05/14 12:51:33 [sandbox:3] Running inside a docker container, disabling sandboxing..
2020/05/14 12:51:33 [video.converter:3] Couldn't find preferred video converter: gavl.
2020/05/14 12:51:33 [audio.converter:3] Using samplerate converter: ffmpeg.
2020/05/14 12:51:33 [harbor:3] Adding mountpoint '/' on port 8005
2020/05/14 12:51:33 [playlist_gigant_van_de_week:3] Loading playlist...
2020/05/14 12:51:33 [playlist_gigant_van_de_week:3] No mime type specified, trying autodetection.
2020/05/14 12:51:33 [playlist_gigant_van_de_week:3] Playlist treated as format application/x-mpegURL
2020/05/14 12:51:33 [playlist_gigant_van_de_week:3] Successfully loaded a playlist of 0 tracks.
2020/05/14 12:51:33 [playlist_nonstop_muziek:3] Loading playlist...
2020/05/14 12:51:33 [playlist_nonstop_muziek:3] No mime type specified, trying autodetection.
2020/05/14 12:51:33 [lang:3] AzuraCast Raw Response: annotate:title="Eens Gaat De Zon Weer Schijnen",artist="Henk Bernard",duration="252.",song_id="d5a8761ef708cdb91231d367d957484e",media_id="68907",liq_amplify="0.dB",playlist_id="10":/var/azuracast/stations/de_piraten_gigant/media/Muziek 2020/Henk Bernard - Eens Gaat De Zon Weer Schijnen.mp3
2020/05/14 12:51:33 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/de_piraten_gigant/media/Muziek 2020/Henk Bernard - Eens Gaat De Zon Weer Schijnen.mp3".
2020/05/14 12:51:34 [playlist_nonstop_muziek:3] Playlist treated as format application/x-mpegURL
2020/05/14 12:51:34 [playlist_nonstop_muziek:3] Successfully loaded a playlist of 30117 tracks.
2020/05/14 12:51:34 [playlist_muziek_2020:3] Loading playlist...
2020/05/14 12:51:34 [playlist_muziek_2020:3] No mime type specified, trying autodetection.
2020/05/14 12:51:34 [playlist_muziek_2020:3] Playlist treated as format application/x-mpegURL
2020/05/14 12:51:34 [playlist_muziek_2020:3] Successfully loaded a playlist of 207 tracks.
2020/05/14 12:51:34 [error_jingle:3] "/usr/local/share/icecast/web/error.mp3" is static, resolving once for all...
2020/05/14 12:51:34 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/de_piraten_gigant/media/Muziek 2020/Henk Bernard - Aan Het Eind Van Al Jouw Tranen Wacht De Liefde.mp3".
2020/05/14 12:51:34 [de_piraten_gigant_next_song:3] Prepared "/var/azuracast/stations/de_piraten_gigant/media/Muziek 2020/Henk Bernard - Eens Gaat De Zon Weer Schijnen.mp3" (RID 3).
2020/05/14 12:51:34 [de_piraten_gigant_relay_1:3] Connecting mount sid#1 for @server-24.stream-server.nl...
2020/05/14 12:51:34 [de_piraten_gigant_relay_1:3] Connection setup was successful.
2020/05/14 12:51:34 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2020/05/14 12:51:34 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/de_piraten_gigant/media/Muziek Nonstop/D/De Willyjo's - N Meisje Zoals Jij.mp3".
2020/05/14 12:51:34 [de_piraten_gigant_live_fallback:3] Switch to de_piraten_gigant_safe_fallback.
2020/05/14 12:51:34 [de_piraten_gigant_safe_fallback:3] Switch to cross_7781.
2020/05/14 12:51:34 [de_piraten_gigant_requests_fallback:3] Switch to de_piraten_gigant_autodj_fallback.
2020/05/14 12:51:34 [de_piraten_gigant_autodj_fallback:3] Switch to de_piraten_gigant_cue_next_song.
2020/05/14 12:51:34 [lang:3] AzuraCast Feedback Response: OK
2020/05/14 12:55:02 [lang:3] AzuraCast Raw Response: annotate:title="Als Je Lacht",artist="Jan Smit",duration="237.",song_id="971a4d67869c457cfc8f43e8199f2494",media_id="154744",liq_amplify="0.dB",playlist_id="17":/var/azuracast/stations/de_piraten_gigant/media/Muziek Nonstop/J/Jan Smit - Als Je Lacht.mp3
2020/05/14 12:55:02 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/de_piraten_gigant/media/Muziek Nonstop/J/Jan Smit - Als Je Lacht.mp3".
2020/05/14 12:55:41 [de_piraten_gigant_next_song:3] Prepared "/var/azuracast/stations/de_piraten_gigant/media/Muziek Nonstop/J/Jan Smit - Als Je Lacht.mp3" (RID 7).
2020/05/14 12:55:42 [cross_7781:3] Analysis: -63.279416dB / -16.610065dB (4.49s / 4.51s)
2020/05/14 12:55:42 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/05/14 12:55:42 [lang:3] AzuraCast Feedback Response: OK
2020/05/14 12:58:54 [lang:3] AzuraCast Raw Response: annotate:title="Tarzan Van Het Zwarte Woud ( Vinyl )",artist="De Zingende Tarzan",duration="187.",song_id="8db10a480e6256c96d7a01dab0a7de76",media_id="148610",liq_amplify="0.dB",playlist_id="17":/var/azuracast/stations/de_piraten_gigant/media/Muziek Nonstop/D/De Zingende Tarzan - Tarzan Van Het Zwarte Woud ( Vinyl ).Mp3
2020/05/14 12:58:54 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/de_piraten_gigant/media/Muziek Nonstop/D/De Zingende Tarzan - Tarzan Van Het Zwarte Woud ( Vinyl ).Mp3".
2020/05/14 12:59:34 [de_piraten_gigant_next_song:3] Prepared "/var/azuracast/stations/de_piraten_gigant/media/Muziek Nonstop/D/De Zingende Tarzan - Tarzan Van Het Zwarte Woud ( Vinyl ).Mp3" (RID 8).
2020/05/14 12:59:34 [cross_7781:3] Analysis: -151.623614dB / -28.120502dB (4.45s / 4.47s)
2020/05/14 12:59:34 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/05/14 12:59:34 [lang:3] AzuraCast Feedback Response: OK
2020/05/14 13:01:57 [lang:3] AzuraCast Raw Response: annotate:title="Met Het Anker In Het Water",artist="De Mixers",duration="176.",song_id="0a3ddab86a6374129fdbf551817cfa81",media_id="146534",liq_amplify="0.dB",playlist_id="17":/var/azuracast/stations/de_piraten_gigant/media/Muziek Nonstop/D/De Mixers - Met Het Anker In Het Water.mp3
2020/05/14 13:01:57 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/de_piraten_gigant/media/Muziek Nonstop/D/De Mixers - Met Het Anker In Het Water.mp3".
2020/05/14 13:02:37 [de_piraten_gigant_next_song:3] Prepared "/var/azuracast/stations/de_piraten_gigant/media/Muziek Nonstop/D/De Mixers - Met Het Anker In Het Water.mp3" (RID 1).
2020/05/14 13:02:37 [cross_7781:3] Analysis: -24.874454dB / -20.817101dB (4.46s / 4.46s)
2020/05/14 13:02:37 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/05/14 13:02:37 [lang:3] AzuraCast Feedback Response: OK
2020/05/14 13:04:49 [lang:3] AzuraCast Raw Response: annotate:title="De Jaankende Hond",artist="Dj Rubin",duration="138.",song_id="e9dba91e8015e2b5fd64107b2cd096ce",media_id="149630",liq_amplify="0.dB",playlist_id="17":/var/azuracast/stations/de_piraten_gigant/media/Muziek Nonstop/D/Dj Rubin - De Jaankende Hond.mp3
2020/05/14 13:04:49 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/de_piraten_gigant/media/Muziek Nonstop/D/Dj Rubin - De Jaankende Hond.mp3".
2020/05/14 13:05:29 [de_piraten_gigant_next_song:3] Prepared "/var/azuracast/stations/de_piraten_gigant/media/Muziek Nonstop/D/Dj Rubin - De Jaankende Hond.mp3" (RID 2).
2020/05/14 13:05:29 [cross_7781:3] Analysis: -28.411022dB / -14.175376dB (4.47s / 4.49s)
2020/05/14 13:05:29 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/05/14 13:05:29 [lang:3] AzuraCast Feedback Response: OK
2020/05/14 13:07:02 [lang:3] AzuraCast Raw Response: annotate:title="Meissie Meissie",artist="Alex",duration="215.",song_id="c3775759d5c214e566726dc8d66f29e2",media_id="139262",liq_amplify="0.dB",playlist_id="17":/var/azuracast/stations/de_piraten_gigant/media/Muziek Nonstop/A/Alex - Meissie Meissie.mp3
2020/05/14 13:07:02 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/de_piraten_gigant/media/Muziek Nonstop/A/Alex - Meissie Meissie.mp3".
2020/05/14 13:07:42 [de_piraten_gigant_next_song:3] Prepared "/var/azuracast/stations/de_piraten_gigant/media/Muziek Nonstop/A/Alex - Meissie Meissie.mp3" (RID 3).
2020/05/14 13:07:42 [cross_7781:3] Analysis: -91.004373dB / -17.569999dB (4.49s / 4.51s)
2020/05/14 13:07:42 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/05/14 13:07:42 [lang:3] AzuraCast Feedback Response: OK

**Comment by SubwooferNL** [comment]
Screens of my Azuracast
https://gyazo.com/9195558158b593015c3f07577d7e9196
https://gyazo.com/6edf3fdb2d5bbce6c57d001444b8e65f
https://gyazo.com/68d148e36b3aded6762226ec4d088216
https://gyazo.com/4c10bb61dbfe797a55d98ca9860c863f
https://gyazo.com/91bc631f00d291c8a84b35604b5365a1
https://gyazo.com/64ff0736c6080d9dbe38d7e7e80691a6
https://gyazo.com/c3db02e399f1dd379ccfa0f8356f092e
https://gyazo.com/d373b4b3d9fee5d8d60c1d829670e1cc
https://gyazo.com/2b48bcf179f3f1f1c987e92c3fa5351c
https://gyazo.com/38c96585afec043d111f1aa2c263e5f1

**Comment by SlvrEagle23** [comment]
@SubwooferNL Try manually running the "Now Playing" synchronization task from your system administration main page and see what debug information it logs. The issue is likely with it failing to connect to your remote relay to retrieve statistics on what's playing, which it depends on regardless of whether Liquidsoap is functioning properly on the broadcasting end.

**Comment by SubwooferNL** [comment]
Oke i get this 
![](https://i.gyazo.com/b53464dde98cfaa571c61e719784ec50.png)
![](https://i.gyazo.com/bf4d7dcc0dee2f805f58f78a841c948d.png)
![](https://i.gyazo.com/1a85b1cd5e1c9004f1ef5b6ff59e58b7.png)
![](https://i.gyazo.com/7488c3b16f47c4f8c1eb5758dcf69fa8.png)

**Comment by SubwooferNL** [comment]
[2020-05-16T09:39:47.931158+00:00] AzuraCast.ERROR: NowPlaying adapter error: XML parsing errors: AttValue: " or ' expected , attributes construct error , Couldn't find end of Start Tag meta line 1 , Opening and ending tag mismatch: link line 1 and head , Opening and ending tag mismatch: wbr line 1 and a , Opening and ending tag mismatch: wbr line 1 and td , Opening and ending tag mismatch: a line 1 and tr , Opening and ending tag mismatch: img line 1 and a , Opening and ending tag mismatch: a line 1 and div , Opening and ending tag mismatch: img line 1 and a , Opening and ending tag mismatch: a line 1 and div , Opening and ending tag mismatch: img line 1 and a , Opening and ending tag mismatch: a line 1 and div , Opening and ending tag mismatch: img line 1 and a , Opening and ending tag mismatch: a line 1 and div , Opening and ending tag mismatch: div line 1 and td , Opening and ending tag mismatch: div line 1 and tr , Opening and ending tag mismatch: div line 1 and table , Opening and ending tag mismatch: wbr line 1 and a , Opening and ending tag mismatch: a line 1 and b , Opening and ending tag mismatch: b line 1 and td , Opening and ending tag mismatch: td line 1 and tr , Specification mandates value for attribute controls , attributes construct error , Couldn't find end of Start Tag audio line 5 , Opening and ending tag mismatch: source line 1 and audio , Opening and ending tag mismatch: tr line 1 and table , Opening and ending tag mismatch: table line 1 and body , Opening and ending tag mismatch: br line 1 and html , EndTag: '</' not found  [] {"station":{"id":1,"name":"De Piraten Gigant"}}
