### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by jopara** [AzuraCast/AzuraCast#2834]
Hello, The password does not work if it is updated through AzuraCast management and then notifies you that "Your credentials could not be verified."
any solution?

**Comment by SC2Mitch** [comment]
Hello, can you use the format next time, what version of AzuraCast are you on?

**Comment by jopara** [comment]
Hello,  v0.9.8.1, (2020-02-26 19:19) • Docker • PHP 7.4

**Comment by pdlexx** [comment]
php /var/azuracast/www/config/cli.php azuracast:account:reset-password my@email.com
Does not work on v0.9.9, Ansible

**Comment by jopara** [comment]
Hello again.
I have tried as pdlexx says: `php /var/azuracast/www/config/cli.php azuracast: account: reset-password my@email.com`
And it gives me this error: Command 'php' not found, but can be installed with:
apt install php7.2-cli
apt install hhvm

Also with this other: `./docker.sh cli azuracast: account: reset-password my@email.com`
And it tells me this: Starting azuracast_redis_1 ... done
Starting azuracast_redis_1 ...
Starting azuracast_stations ... done
Starting azuracast_mariadb_1 ... done
Starting azuracast_influxdb_1 ... done
2020/05/25 15:04:07 Waiting for: tcp: // mariadb: 3306
2020/05/25 15:04:07 Waiting for: tcp: // influxdb: 8086
2020/05/25 15:04:07 Connected to tcp: // mariadb: 3306
2020/05/25 15:04:07 Connected to tcp: // influxdb: 8086

Reset Account Password
======================


 [ERROR] Account not found.


2020/05/25 15:04:07 Command exited with error: exit status 1

I am already desperate. I need to enter the control panel where I have about 25 stations and I need to create one more. I DO NOT want to format the server. Please.

Thank you

**Comment by SlvrEagle23** [comment]
@pdlexx That is for Ansible installations; this error was regarding a Docker installation. However, to correct you for Ansible installations, the updated command would be:

```bash
php /var/azuracast/www/bin/console azuracast:account:reset-password
```

@jopara If the AzuraCast CLI can't find the account, then it's possible that e-mail address doesn't exist in the system. Currently there's no way to create a new user account with a given e-mail address via the CLI alone. You would need to look into your database directly and determine what user accounts exist, and what e-mail address is associated with your administrator account. This is an advanced process that is beyond the scope of the support we provide on here.

**Comment by jopara** [comment]
Hi. Thanks for all this help. If you could tell me in which directory or how to access the database, maybe you could look at the users of the system.
The sierto is that entered by Filezilla through SFTP I do not know where to locate it (I do not know if it is the most correct method)
Thank you

**Comment by SlvrEagle23** [comment]
@jopara If you're on Docker, here's a quick way to get the current account e-mail addresses in the system:

```bash
./docker.sh cli orm:run-dql "SELECT u.email FROM App\Entity\User u"
```

**Comment by pdlexx** [comment]
> @pdlexx That is for Ansible installations; this error was regarding a Docker installation. However, to correct you for Ansible installations, the updated command would be:
> 
> ```shell
> php /var/azuracast/www/bin/console azuracast:account:reset-password
> ```
> 

Thank you. It's work. Mауbe you need to upgrade this page https://www.azuracast.com/help/ansible/#reset-an-account-password

**Comment by jopara** [comment]
Hello, after applying that command it tells me this:

Starting azuracast_mariadb_1 ... done
Starting azuracast_stations  ... done
Starting azuracast_redis_1   ... done
Starting azuracast_influxdb_1 ... done
2020/05/26 07:47:51 Waiting for: tcp://mariadb:3306
2020/05/26 07:47:51 Waiting for: tcp://influxdb:8086
2020/05/26 07:47:51 Connected to tcp://influxdb:8086
2020/05/26 07:47:51 Connected to tcp://mariadb:3306


  Too many arguments, expected arguments "command" "dql".


orm:run-dql [--hydrate HYDRATE] [--first-result FIRST-RESULT] [--max-result MAX-RESULT] [--depth DEPTH] [--show-sql] [--] <dql>

**Comment by SlvrEagle23** [comment]
@jopara Update the Docker utility script by running `./docker.sh update-self`, then try again.

**Comment by SlvrEagle23** [comment]
@pdlexx Updated the docs to reflect the updated console path.

**Comment by jopara** [comment]
241/5000
Ok, it's already solved.
One more question, if I change that new password for another one within the system, is it possible that the new password works or should I just leave, from now on, the random one that is given to me by the system?

Thank you very much for your help.

**Comment by SlvrEagle23** [comment]
@jopara You should be able to change the password any time you want from within the system. I believe in this case you may have also changed the e-mail and that caused the problem.
