### ISSUE TITLE
Noob question: PHP access to POST

### ISSUE THREAD

**Issue by krono86** [AzuraCast/AzuraCast#2835]
Hello,
I'm a noob with PHP, and I'd like to implement an example php page on my web server that print (echo) a phrase when DJ start streaming to my azuracast server (it's not the same machine of the web server).
I've seen Azuracast can send POST to an url when DJ connects, but which is the format of the url I have to insert?
Can you suggest me a php code to read the "is_live" information from POST.
Thanks so much.

Ivan

**Comment by MrSleeps** [comment]
https://github.com/AzuraCast/php-api-client

Might be what you are looking for.

**Comment by Vaalyn** [comment]
You create the PHP script somewhere on a web server and put the URL of the script (just like you would open it in a browser) in the Web Hook URL field when creating a new webhook. In your script you should get the contents of the POST body like this: `$webhookJson = file_get_contents('php://input');`

`$webhookJson` will contain a JSON string that you'll have to `json_decode` and can then use the content of it how you like.

**Comment by krono86** [comment]
It seems that Azuracast is sending an empty POST request. Is it possible?
I set webhook:
![Screenshot from 2020-05-15 16-40-41](https://user-images.githubusercontent.com/121834/82105781-5e4a6100-971d-11ea-920f-4d5363e4e233.png)

And I'm trying to run the simple script:

```
<?php
$webhookJson = file_get_contents('php://input');
var_dump($webhookJson);
?>
```

but in the browser I always obtain:

`string(0) "" `

What's going on?
Thanks so much.

Ivan

**Comment by SlvrEagle23** [comment]
@krono86 when you look at the script in your browser, you're not sending any POST data in that particular request, so it (correctly) shows an empty string.

When the web hook itself dispatches, it's receiving a POST body from that request, but you have to persist it somewhere (i.e to the filesystem or to a database) for you to be able to see it when you make your own requests to that same server.

**Comment by krono86** [comment]
Uhm, let me understand..
- AzuraCast sends POST via web hook;
- my PHP script has to receive POST, decode and save it, e.g., on the file system;
- the resource on the file system can be now used by other php or js scripts.
Is it correct?
Thanks so much!

Ivan

**Comment by SlvrEagle23** [comment]
@krono86 Correct. That's also how you can inspect the webhook's contents, since you won't be able to see exactly what the webhook's processing script is doing exactly as it's doing it.

**Comment by krono86** [comment]
It works!
Thanks so much.

Ivan
