### ISSUE TITLE
Can't set correct System URL

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#2839]
v0.10.2, #bd6d320 (2020-05-15 10:13) • Docker • PHP 7.4

I can not set correct system URL under System Settings.
mystream.domain.com gives me "Please enter URL"
http://mystream.domain.com or https://mystream.domain.com works, but then Icecast Config would be wrong.
e.g. 

listenurl | http://http://mystream.domain.com:8000/radio.aac

**Comment by SlvrEagle23** [comment]
@LordHelmchen666 Fixed in the latest commit. Thanks for the report!
