### ISSUE TITLE
WHMCS Integration

### ISSUE THREAD

**Issue by RainbowDash53** [AzuraCast/AzuraCast#284]
Hi, can you integrated the WHMCS Integration for the automatic delivery and auto set-up, thank's in advance

**Comment by FrBillyD** [comment]
👍

**Comment by SlvrEagle23** [comment]
Closing as I have no current plans to implement WHMCS integration, as the publicly available documentation is sparse and it seems that their marketplace requires very special configuration that would require significant development effort on my part.

If anyone is particularly passionate about the idea of integrating AzuraCast into WHMCS and would like to do some further research on the necessary changes in the system, or even make a pull request to that effect, that would be just fine.
