### ISSUE TITLE
Can i change the time before autoDJ kicks in

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#2841]
Hi,

Can i change the time before the autoDJ kicks in to take over the live DJ when a silence occures?

Greetings,
RemBDev

**Comment by SlvrEagle23** [comment]
@RemBdev if you're referring to when a DJ disconnects, that's usually controlled by the buffer setting, which gives you a specified number of seconds of buffered audio that the AutoDJ has to play from the DJ even if they disconnect. Increasing that can help prevent those gaps in playback from happening.
