### ISSUE TITLE
ERROR: Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by suricloud** [AzuraCast/AzuraCast#2842]
**Using Docker installation method**
Yes

**AzuraCast version**

**Host Operating System**
Debian 9

**Describe the bug**

Hi just did a update for azuracast and get this error?Azuracast is not starting anymore?
Please help!

**To Reproduce**

root@rs:/var/azuracast# ./docker.sh update-self && echo "y" | ./docker.sh update
New Docker utility script downloaded.
Pulling mariadb  ... done
Pulling influxdb ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Stopping azuracast_mariadb_1  ... done
Stopping azuracast_redis_1    ... done
Stopping azuracast_influxdb_1 ... done
Removing azuracast_stations   ... done
Removing azuracast_mariadb_1  ... done
Removing azuracast_redis_1    ... done
Removing azuracast_influxdb_1 ... done
Removing network azuracast_default
azuracast_www_data
azuracast_tmp_data
azuracast_redis_data
Creating network "azuracast_default" with the default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_www_data" with default driver
Creating volume "azuracast_redis_data" with default driver
Creating azuracast_influxdb_1 ...
Creating azuracast_redis_1    ...
Creating azuracast_mariadb_1  ...
Creating azuracast_stations   ... error
WARNING: Host is already in use by another container
Creating azuracast_influxdb_1 ... done
Creating azuracast_redis_1    ... done
dpoint azuracast_stations (f312efa5b3aa36df7be7620162f4fdd9301d1d3f6af782b8037adc46b80473be): Bind for 0.0.0.0:8496Creating azuracast_mariadb_1  ... done

ERROR: for stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (f312efa5b3aa36df7be7620162f4fdd9301d1d3f6af782b8037adc46b80473be): Bind for 0.0.0.0:8496 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
Starting azuracast_stations ...
azuracast_redis_1 is up-to-date
azuracast_influxdb_1 is up-to-date
azuracast_mariadb_1 is up-to-date
Starting azuracast_stations ... error

ERROR: for azuracast_stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (1a6e8bcf3405cb257cfc63b53665b8e878dca52d28167c50ae3f7f8ba67609d2): Bind for 0.0.0.0:8496 failed: port is already allocated

ERROR: for stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (1a6e8bcf3405cb257cfc63b53665b8e878dca52d28167c50ae3f7f8ba67609d2): Bind for 0.0.0.0:8496 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
Update complete!

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@suricloud It appears port 8496 is in use by something else on your server. You should run something like `netstat -tulpn` and see what's listening on various ports on your host computer, and either disable, modify or uninstall the program listening on that port.

**Comment by suricloud** [comment]
Yes that seems to happen.I only run azuracast on the server nothing else.I had created a station and assigend the port 8140.I thing that causes this problem.Where i can the list of ports to assign to the stations? And may be you can add list of availabe ports to choose for a station when creating that.So this will not lead to port conflicts.

**Comment by SlvrEagle23** [comment]
@suricloud Because of the way Docker works on AzuraCast, we preassign the port clearance for a large number of stations, so we can't just explicitly change the port mappings ahead of time.
