### ISSUE TITLE
El paquete «docker-ce» no tiene un candidato para la instalación

### ISSUE THREAD

**Issue by tecasires** [AzuraCast/AzuraCast#2844]
![01](https://user-images.githubusercontent.com/65423899/82120886-07767300-9781-11ea-8302-00cd501c5576.PNG)

**Using Docker installation method**

Yes, using docker method.

**AzuraCast version**

Powered by AzuraCast • v0.10.2, #b86d6a5 (2020-05-16 8:35) • Docker • PHP 7.4

**Host Operating System**

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

**Describe the bug**

+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
E: El paquete «docker-ce» no tiene un candidato para la instalación

**To Reproduce**

Normal install

**Expected behavior**

**Relevant Logs**

Attached
[azuracast.txt](https://github.com/AzuraCast/AzuraCast/files/4638438/azuracast.txt)

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@tecasires If you're using Ubuntu 20.04, you will need to manually install Docker first before running the regular installer:

```bash
sudo apt-get install docker.io
sudo usermod -aG docker `whoami`
```

...then reboot, then run `./docker.sh install` again.
