### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by webma5ter23** [AzuraCast/AzuraCast#2845]
docker installation
azurcast: 0.10.2

When updating to the new version all radios fell, apparently liquidsoap fails.

The worst thing is that you cannot go back to the old version :(

`2020/05/17 04:16:14 [tacuatec_safe_fallback:3] Switch to cross_7745 with transition.
2020/05/17 04:16:14 [clock.wallclock_main:2] We must catchup 1.97 seconds!
2020/05/17 04:16:14 [tacuatec_requests_fallback:3] Switch to tacuatec_autodj_fallback.
2020/05/17 04:16:14 [tacuatec_autodj_fallback:3] Switch to tacuatec_standard_playlists.
2020/05/17 04:16:14 [tacuatec_standard_playlists:3] Switch to cue_playlist_oldies.
2020/05/17 04:16:14 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/tacuatec/media/Oldies/1_-_boney_m._-_daddy_cool.mp3".
2020/05/17 04:16:15 [lang:3] AzuraCast Feedback Response: OK
2020/05/17 04:16:15 [clock.wallclock_main:2] We must catchup 2.78 seconds!
2020/05/17 04:16:16 [clock.wallclock_main:2] We must catchup 3.12 seconds!
2020/05/17 04:16:17 [clock.wallclock_main:2] We must catchup 3.33 seconds!
2020/05/17 04:16:18 [clock.wallclock_main:2] We must catchup 3.82 seconds!
2020/05/17 04:16:19 [clock.wallclock_main:2] We must catchup 4.40 seconds!
2020/05/17 04:16:20 [clock.wallclock_main:2] We must catchup 4.66 seconds!
2020/05/17 04:16:21 [clock.wallclock_main:2] We must catchup 4.75 seconds!
2020/05/17 04:16:22 [clock.wallclock_main:2] We must catchup 4.98 seconds!
2020/05/17 04:16:23 [clock.wallclock_main:2] We must catchup 4.96 seconds!
2020/05/17 04:16:24 [clock.wallclock_main:2] We must catchup 4.97 seconds!
2020/05/17 04:16:25 [clock.wallclock_main:2] We must catchup 4.90 seconds!
2020/05/17 04:16:26 [clock.wallclock_main:2] We must catchup 4.98 seconds!
2020/05/17 04:16:27 [clock.wallclock_main:2] We must catchup 5.28 seconds!
2020/05/17 04:16:28 [clock.wallclock_main:2] We must catchup 5.23 seconds!
2020/05/17 04:16:29 [clock.wallclock_main:2] We must catchup 5.39 seconds!
2020/05/17 04:16:30 [clock.wallclock_main:2] We must catchup 5.56 seconds!
2020/05/17 04:16:31 [clock.wallclock_main:2] We must catchup 5.74 seconds!
2020/05/17 04:16:32 [clock.wallclock_main:2] We must catchup 5.94 seconds!
2020/05/17 04:16:33 [clock.wallclock_main:2] We must catchup 6.32 seconds!
2020/05/17 04:16:34 [clock.wallclock_main:2] We must catchup 6.65 seconds!
2020/05/17 04:16:35 [clock.wallclock_main:2] We must catchup 6.96 seconds!
2020/05/17 04:16:36 [clock.wallclock_main:2] We must catchup 6.83 seconds!
`

Help me please

**Comment by SC2Mitch** [comment]
This appears to be a problem on your end, not AzuraCast. Your systems are running slower than expected and cannot keep up with the music. Check your resources, see what's hogging it up, it's mostly related to CPU / MEM.

**Comment by webma5ter23** [comment]
> This appears to be a problem on your end, not AzuraCast. Your systems are running slower than expected and cannot keep up with the music. Check your resources, see what's hogging it up, it's mostly related to CPU / MEM.

I'm on Linode,  Ubuntu 18.04 LTS, Dedicated 4GB: 2 CPU, 80GB Storage, 4GB RAM

Before updating everything was normal.

**Comment by SlvrEagle23** [comment]
@webma5ter23 Always make sure to take a backup before updating your installation, just in case you encounter any issues like this!

The "we must catchup" error is specifically related to Liquidsoap being strained for resources and struggling to keep its internal clocks lined up in such a way that it can maintain a smooth stream.

It's unlikely that updating alone caused this issue to appear out of the blue, as our recent updates to Liquidsoap have fixed a huge number of bugs but haven't introduced any performance deficits that we're aware of.

Rebooting your server and/or restarting broadcasting on each station manually (via Utilities > Restart Broadcasting) may assist with the issue.
