### ISSUE TITLE
Permission denied while trying to add music to playlist

### ISSUE THREAD

**Issue by HSAK5G** [AzuraCast/AzuraCast#2847]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.2, #109b65e (2020-05-12 10:49)

**Host Operating System**
Linux Mint MATE 19.3 Tricia

**Describe the bug**
Failed to read file: /var/azuracast/stations/hsak_radio_station_random_genre/media/Tobu - Colors.mp3 Permission denied

**To Reproduce**
Go to music files.
Add songs to playlist

**Expected behavior**
I want to add songs to my playlist but I am not able to. I keep getting a permission denied error. Please help.

**Relevant Logs**
web_1       | [2020-05-17T10:00:05.835525+00:00] AzuraCast.ERROR: Warning for uploaded media file "Tobu - Colors": ["Could not open \"\/var\/azuracast\/stations\/hsak_radio_station_random_genre\/media\/Tobu - Colors.mp3\" (!is_readable)"] [] []
web_1       | [2020-05-17T10:00:05.862134+00:00] AzuraCast.ERROR: Exception when processing message type App\Message\ReprocessMediaMessage: The command "'audiowaveform' '-i' '/var/azuracast/stations/hsak_radio_station_random_genre/media/Tobu - Colors.mp3' '-o' '/tmp/awfsrUJl1.json' '--pixels-per-second' '20' '--bits' '8'" failed.  Exit Code: 1(General error)  Working directory: /etc/runit/runsvdir/default/php-worker  Output: ================   Error Output: ================ Failed to read file: /var/azuracast/stations/hsak_radio_station_random_genre/media/Tobu - Colors.mp3 Permission denied [] []

**Screenshots**
<img width="1280" alt="Screen Shot 2020-05-17 at 8 02 22 pm" src="https://user-images.githubusercontent.com/44635763/82141496-7cc56f00-9879-11ea-81d0-e85fd6369502.png">
<img width="1280" alt="Screen Shot 2020-05-17 at 8 02 40 pm" src="https://user-images.githubusercontent.com/44635763/82141499-8058f600-9879-11ea-869d-2f04f0ae0311.png">

**Device(s):**
 - Device: Laptop Lenovo
 - OS: Linux Mint MATE
 - Browser: Chrome
 - Version: 19.3 Tricia

**Additional context**
To add the songs i used a docker-compose.override.yml file. Below are the contents of the file.

version: '2.2'

services:
  web:
    volumes:
      - /home/hsak/hsak_radio_station_random_genre:/var/azuracast/stations/hsak_radio_station_random_genre/media/

  stations:
    volumes:
      - /home/hsak/hsak_radio_station_random_genre:/var/azuracast/stations/hsak_radio_station_random_genre/media/

**Comment by SC2Mitch** [comment]
Are you able to update to the latest version of Azura and check again? #2c51463

**Comment by HSAK5G** [comment]
I already updated to the latest version today.

**Comment by SlvrEagle23** [comment]
@HSAK5G Inside the Docker container, the AzuraCast user is UID 1000. Make sure that your permissions on the host device's folder are set in such a way that this user can read/write to those directories. In a lot of cases, UID 1000 is the first user account on the OS.

**Comment by HSAK5G** [comment]
I tried using this tutorial to give permission: [https://stackoverflow.com/questions/44436259/how-to-give-folder-ownership-to-user-with-uid-1000](url). Did not work. Did I type the command wrong?

**Comment by HSAK5G** [comment]
I am closing this issue. I finally got it to work. I updated to the latest version and it workes.

**Comment by harryfear** [comment]
Had the same issue and fixed with:

`sudo chown -R docker:docker media`

Where media is the child directory whose ownership/permissions need fixing.

Just FYI for anyone facing this issue.

**Comment by cybercuate** [comment]
> Had the same issue and fixed with:
> 
> `sudo chown -R docker:docker media`
> 
> Where media is the child directory whose ownership/permissions need fixing.
> 
> Just FYI for anyone facing this issue.

got error: invalid user docker:docker
