### ISSUE TITLE
Streamer Broadcast timestamps shows UNIX timestamp 

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2848]
**Using Docker installation method**
Yes 

**AzuraCast version**
Powered by AzuraCast • v0.10.2, #2c51463 (2020-05-16 21:53) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 20.04
**Describe the bug**

**To Reproduce**
Create a streamer profile, connect as normal, check the connection dates and times.

**Expected behavior**
It to correctly display HH:MM or DD:MM:YY | HOUR:MINUTE
**Relevant Logs**
None

**Screenshots**
![image](https://user-images.githubusercontent.com/29955942/82162821-32ef7f80-989f-11ea-9b10-06f68279c0e9.png)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch Our frontend Moment library should be converting these timestamps into date/times. Check the browser console; are you seeing any console errors on that page?

**Comment by SC2Mitch** [comment]
No console errors, only warnings about missing files. 
![image](https://user-images.githubusercontent.com/29955942/82200457-efc0fb00-98f6-11ea-8abd-36e3b477eafe.png)
No error logs are appearing in Docker logs.

**Comment by SlvrEagle23** [comment]
@SC2Mitch Fixed as of latest update, and as an added bonus I added in-browser playback to broadcasts. :)
