### ISSUE TITLE
iframe

### ISSUE THREAD

**Issue by huhas12** [AzuraCast/AzuraCast#2849]
**Using Docker installation method**

**AzuraCast version**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by huhas12** [comment]
I deployed digitalocean and I used iframe to embed the player in my website, though I getting the following error in the web browser when trying to access my site. 

the web page htttps://165.22.81.227/public/just4music.live/embed might be temporarily down or it may have moved to a new web address. 

Show's up as security issue from chrome, mozilla, opera...

**Comment by spenmath** [comment]
Have you installed an SSL Certificate on your server? https://www.azuracast.com/extending/letsencrypt.html

If you can provide some more installation information in the template then you may get more direct response as we don't know your current installation method.

**Comment by LordHelmchen666** [comment]
Your server not reachable?!
```
guest@dnstools.ch:~> ping 165.22.81.227 
PING 165.22.81.227 (165.22.81.227) 56(84) bytes of data. 
 
--- 165.22.81.227 ping statistics --- 
16 packets transmitted, 0 received, 100% packet loss, time 7619ms 
```

**Comment by huhas12** [comment]
stream seems to be playing https://165.22.81.227/public/just4music.live but I cant ping server either.
