### ISSUE TITLE
Title of the currently playing song does not appear. Old title remains

### ISSUE THREAD

**Issue by rolradio** [AzuraCast/AzuraCast#2850]
**Using Docker installation method**

**AzuraCast version**

v0.10.2, #7c7f974 (2020-05-16 3:23) 

**Host Operating System**

Unbuntu 8

**Describe the bug**

Title of the currently playing song does not appear.
Old title remains

**To Reproduce**

We have some pre-recorded shows that we want to play punctually at a certain hour.
That's why we disabled the Azuracast Autodj. So we can use the advenced setting interrupt.

Unfortunately, we continue to have the problem that the title of the program will not appear ... if there was a planned show before.
The show now starts on time.

A 2-hour pre-recorded show starts at 5:00 PM
(before there was music rotation)
Timetable:
Starts at 5:00 PM and ends at 7:00 PM. With the interrupt function checked.
Show starts perfectly on time and the title of the show is visible.

Another pre-recorded 2-hour program starts at 7:00 PM.

Timetable:
Starts at 7:00 PM and ends at 9:00 PM. With the interrupt function checked.
Show starts perfectly on time but the title of the show is not visible.
The title of the show between 17Pm and 19PM just remains.

Where does azuracst get its title information from?
How can we solve such a thing?
Wouldn't a manual update or a push be a solution?

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@rolradio I don't know what would be causing an issue like this, and it may very likely have something to do with how Liquidsoap is arranging the tracks. I will keep this open for now in case we have any further insights into the issue.

**Comment by rolradio** [comment]
Okay.

Thank you.
