### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by ismaelazanza** [AzuraCast/AzuraCast#2853]
Excuse the question, I have tried to update to the latest version of Azuracast, however, this error appears when loading the panel. The installation in root completes successfully, but it gives me the error. Maybe someone has happened to him and can explain some reason.

<img width="1122" alt="Captura de Pantalla 2020-05-19 a la(s) 02 16 26" src="https://user-images.githubusercontent.com/50606824/82296526-ec6d5400-9976-11ea-8373-479fb46332c9.png">

**Comment by SlvrEagle23** [comment]
@ismaelazanza Try running the updater again:

```
cd /var/azuracast
./docker.sh update-self
./docker.sh update
```

...and if that doesn't help anything, let me know if you see any errors when you run `docker-compose logs -f nginx_proxy` or `docker-compose logs -f nginx`.

**Comment by SlvrEagle23** [comment]
@ismaelazanza Hello, please try updating to the latest version again and let me know if the issue is still present.

**Comment by LordHelmchen666** [comment]
```
docker-compose logs -f nginx
WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
ERROR: No such service: nginx
```

**Comment by rolradio** [comment]
Hi,

Maybe the same problem here: 
https://github.com/AzuraCast/AzuraCast/issues/2852
View the latest messages, that was the solution for me.

**Comment by SlvrEagle23** [comment]
Check out issue #2855 for full instructions on how to resolve this issue.

**Comment by ismaelazanza** [comment]
Thanks for the help, with this guide it was updated and there is no error
https://github.com/AzuraCast/AzuraCast/issues/2855
