### ISSUE TITLE
Custom SSL not functioning after recent changes, SSL in docker-compose.override

### ISSUE THREAD

**Issue by mikedorst** [AzuraCast/AzuraCast#2854]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.2, #f1b37e4 (2020-05-19 10:35) 

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
After the SSL changes, the custom SSL certifcates are not functioning anymore. Maybe I need to change the code up but I'm not sure what to modify. My azuracast is not running on default 80 and 443 ports, it's 8080 and 4430.

![image](https://user-images.githubusercontent.com/27761242/82329474-aa2d2c80-99e1-11ea-8b33-65e8103d95a4.png)

I did try `./docker.sh letsencrypt-create` but I expected no change as I think the documentation said it only  works on port 80 and 443. I did manage to get a signed certificate but it's not recognizing on my domain.

![image](https://user-images.githubusercontent.com/27761242/82329735-0c862d00-99e2-11ea-833f-f50dc398741d.png)

![image](https://user-images.githubusercontent.com/27761242/82330057-9b934500-99e2-11ea-96e9-c09665b3f1b5.png)

**To Reproduce**
Use a custom SSL certficate with the code above, it'll tell you that 

**Expected behavior**
SSL should pick the custom one and the site should function properly with a signed certificate.

**Comment by SlvrEagle23** [comment]
@mikedorst Hello! Sorry for the inconvenience; we've made some infrastructural changes that require a slight modification of where you mount your custom certificates. I've added these instructions to the pinned issue at #2855, so please refer to that thread for help. Thank you for your patience!

**Comment by kemecs** [comment]
I set up my own certificate here
Docker-compose.override.yml

version: '2.2'
services:
  nginx_proxy:
    volumes:
     - /var/azuracast/wildcard_folkradiohu.crt:/etc/nginx/certs/folktest.folkradio.hu.crt:ro
     - /var/azuracast/wildcard_folkradio_hu.key:/etc/nginx/certs/folktest.folkradio.hu.ssl.key:ro

was to restart the dock

yet localhos is the certificate

**Comment by mikedorst** [comment]
Did you run `./docker.sh letsencrypt-create`? @kemecs

**Comment by kemecs** [comment]
Why you should be letsencrypt-create?

i have my own certificate!

- /var/azuracast/wildcard_folkradiohu.crt:/etc/nginx/certs/folktest.folkradio.hu.crt:ro
- /var/azuracast/wildcard_folkradio_hu.key:/etc/nginx/certs/folktest.folkradio.hu.ssl.key:ro

**Comment by SlvrEagle23** [comment]
@kemecs Minor correction on your file: it shouldn't be `.ssl.key:ro` at the end of the second line, just `.key:ro`, so it's basically `domain.crt:ro` and `domain.key:ro`.

**Comment by kemecs** [comment]
I updated a few hours ago
(v0.10.2, #ee997ef (2020-05-22 5:35) • Docker • PHP 7.4)
and
yes fixed, that's okay

thanks

**Comment by kemecs** [comment]
> @kemecs Minor correction on your file: it shouldn't be `.ssl.key:ro` at the end of the second line, just `.key:ro`, so it's basically `domain.crt:ro` and `domain.key:ro`.

I updated a few hours ago
(v0.10.2, #ee997ef (2020-05-22 5:35) • Docker • PHP 7.4)
and
yes fixed, that's okay

thanks
