### ISSUE TITLE
Getting a HTTP 500 or "Insecure Site" error on HTTPS after the latest update? See here for instructions!

### ISSUE THREAD

**Issue by BusterNeece** [AzuraCast/AzuraCast#2855]
Last night, we pushed out a release that has some very important infrastructural changes for us. Namely, it merges our previous "Multi-site" Docker configuration with the core AzuraCast configuration, so now no additional work is needed to support multiple Docker containers on the same server via the proxy service. Second, the proxy service is very well-suited at handling LetsEncrypt certificate registration and renewal, including adding support for multiple domain names, which is something we've never had before. All around, it's a big improvement!

Because the new infrastructure handles LetsEncrypt differently, however, your settings for LetsEncrypt didn't carry over to the new setup. Fortunately, we have a handy-dandy helper tool just like the previous version to make it very easy to set up.

---

### Using LetsEncrypt

First, make sure both your AzuraCast and Docker Utility Script are updated by running:

```
cd /var/azuracast
./docker.sh update-self
./docker.sh update
```

**If you're prompted to update your `docker-compose.yml` file, you should choose "Y" (Yes) to do so.** Any changes you've made to the original file will be backed up in a file called `docker-compose.backup.yml`, so you can reapply any customizations you've made.

Then run the new LetsEncrypt set up tool:

```
./docker.sh letsencrypt-create
```

You will be prompted for domain name(s) to register. If you want to register multiple, just separate them with commas ("example.com,foo.bar"). You can now also optionally specify an e-mail address to be notified in the event that certificate auto-renewal fails for any reason.

If you've run this process and you're still seeing an HTTP 500 error, it means that the LetsEncrypt auto-reservation process didn't work correctly for some reason, likely because the DNS for your domain name doesn't point to your server's IP address yet, or you're using a service like CloudFlare that sits in front of your server (in which case they supply the HTTPS certificate, not LetsEncrypt).

Just like before, the container will automatically update your LetsEncrypt certificate periodically (they expire after about 90 days) and reload the nginx server to apply the new certificate.

---

### Using Custom Certificates

Previously, if you had a custom SSL certificate, you would mount it to the `web` container. Using the new infrastructure, you just need to modify this code slightly. Your `docker-compose.override.yml` should now look more like:

```yml
version: '2.2'

services:
  nginx_proxy:
    volumes:
      - /path/on/host/to/ssl.crt:/etc/nginx/certs/yourdomain.com.crt:ro
      - /path/on/host/to/ssl.key:/etc/nginx/certs/yourdomain.com.key:ro
```

Note that unlike before, you should specify which domain the SSL certificate is for in its filename. If it's for "example.azuracast.com", it should be named `example.azuracast.com.crt` in the container; if it's a wildcard for all "azuracast.com" domains, it should be named `azuracast.com.crt`.

---

Thank you for your patience!

**Comment by ckeurk** [comment]
for a VPS server how to do with an IP address ?

**Comment by SlvrEagle23** [comment]
@ckeurk You can't register a LetsEncrypt certificate for an IP address, only for a domain name. This has always been a limitation of the SSL certificate system.

**Comment by ckeurk** [comment]
I don't have a domain name but I have a VPS server

**Comment by manugut** [comment]
Hello, nothing works. 
Error: NET::ERR_CERT_INVALID

`Subject | localhost                                  
Fingerprint xxx                
Pin xxx
-- | --
Common names | localhost
Alternative names | -    INVALID
Serial Number | xxx
Valid from | Tue, 19 May 2020 10:38:39 UTC
Valid until | Wed, 19 May 2021 10:38:39 UTC (expires in 11 months and 29 days)
Key | RSA 2048 bits                 (e 65537)
Weak key (Debian) | No
Issuer | localhost   Self-signed
Signature algorithm | SHA256withRSA
Extended Validation | No
Certificate Transparency | No
OCSP Must Staple | No
Revocation information | None
DNS CAA | No (more info)
Trusted | No   NOT TRUSTED 						    (Why?) 	` 			                                    

I make the Azuracat Update like everytime and your instruction.
I make `./docker.sh letsencrypt-create`again.

Interesting: Adminpanel didn't work with https, but the stream work with https://

**Comment by andrewyv** [comment]
Me too, still insecure and I did  ./docker.sh letsencrypt-create
The problem is that I'm losing listeners because my stream is with https://

**Comment by SlvrEagle23** [comment]
@manugut @andrewyv If running the LetsEncrypt create tool doesn't yield a secure connection, check the logs by running `docker-compose logs -f nginx_proxy_letsencrypt`. It should tell you what the problem is.

Note that when entering a domain, you don't need to include the "http://" or "https://" portion, and also SSL certificates can't be provided for IP addresses alone, only domain names.

**Comment by manugut** [comment]
Hi @SlvrEagle23,
a long time it works (with domain names), but when I running `docker-compose logs -f nginx_proxy_letsencrypt` in `cd /var/azuracast` i get `ERROR: No such service: nginx_proxy_letsencrypt`.
I don't know why.

**Comment by SlvrEagle23** [comment]
@manugut Make sure that when it prompts you to update your `docker-compose.yml` file you choose "Y", because otherwise you won't have the necessary components.

**Comment by manugut** [comment]
> @manugut Make sure that when it prompts you to update your `docker-compose.yml` file you choose "Y", because otherwise you won't have the necessary components.

But one, question. I use same streaming ports like 8011. When I override this, what about my ports? Thanks.

**Comment by SlvrEagle23** [comment]
@manugut That's a different problem unrelated to the SSL certificate; it's likely that you have some other service running or listening on port 443 (i.e. an nginx or apache server on the host computer itself). Running `netstat -tulpn` can help identify what's listening on that port.

**Comment by manugut** [comment]
@SlvrEagle23 > netstat -tulpn says: 
`tcp6       0      0 :::443                  :::*                    LISTEN      19385/docker-proxy `

**Comment by SlvrEagle23** [comment]
@manugut Try restarting the server, and if that doesn't work create another issue here on GitHub. I want to avoid too many side issues on this pinned thread.

**Comment by manugut** [comment]
> @manugut Try restarting the server, and if that doesn't work create another issue here on GitHub. I want to avoid too many side issues on this pinned thread.

Ok, thanks. 
Didn't work. I make a new issue in evening.

**Comment by andrewyv** [comment]
@SlvrEagle23 I tried to move AzuraCast from server A to server B
I changed the DNS to server B IP, I did command for SSL Let's Encrypt and i get error 500 from Nginx on server B.

**Comment by cmarina** [comment]
![D10E29F7-D7C3-4244-BE1A-8C720532AE19](https://user-images.githubusercontent.com/36649555/82737759-a5df7700-9d33-11ea-88e0-1111be47b7f8.jpeg)

Did all requested steps.

Updated, installed new certificate, rebooted.

Certificate shows localhost instead of the domain and email I entered.

See attached image.

**Comment by manugut** [comment]
> ![D10E29F7-D7C3-4244-BE1A-8C720532AE19](https://user-images.githubusercontent.com/36649555/82737759-a5df7700-9d33-11ea-88e0-1111be47b7f8.jpeg)
> 
> Did all requested steps.
> 
> Updated, installed new certificate, rebooted.
> 
> Certificate shows localhost instead of the domain and email I entered.
> 
> See attached image.
> 
> https://cast.hidden-affairs.com

That is exactly my problem. I spend hours and hours. Nothing worked.
I give up.

**Comment by cmarina** [comment]
Got it to work again, here’s how:

you have to include the qualified host and domain for the certificate to get issued correctly:

In my case the VPS is cast.hidden-affairs.com

Entering not only the domain, but including the host name fixed it for me. 

In addition I did another update after that and rebooted.

Now everything works like before.

Hope that helps!

host.domain.xyz

**Comment by TenGbps** [comment]
Due to the 'too many certificates already issued' error, we have apply this workaround : 

`services:
  nginx_proxy:
    volumes:
      - /var/azuracast/ssl/ssl.crt:/etc/nginx/certs/default.crt:ro
      - /var/azuracast/ssl/ssl.key:/etc/nginx/certs/default.key:ro
  web:
    volumes:
      - /var/azuracast/ssl/ssl.crt:/etc/letsencrypt/selfsigned.crt:ro
      - /var/azuracast/ssl/ssl.key:/etc/letsencrypt/selfsigned.key:ro

  stations:
    volumes:
      - /var/azuracast/ssl/ssl.crt:/etc/nginx/ssl/ssl.crt:ro
      - /var/azuracast/ssl/ssl.key:/etc/nginx/ssl/ssl.key:ro
`

**Comment by AmsterdamFM** [comment]
During the update we got the error or warnig that no email and domain were set. After the update we ran `./docker.sh letsencrypt-create` and all was fine.

**Comment by arusi01** [comment]
How do I fix the localhost certifacate problem?
![cert](https://user-images.githubusercontent.com/51458416/82839226-0b9f4080-9ea5-11ea-9e27-37a783775566.jpg)

**Comment by ericmil87** [comment]
Everything is working fine here BUT the webplayer is not playing on HTTPS only on HTTP.  I debug and found that the url http://radio.inovaway.org:8010/radio.mp3 is working and the SSL url https://radio.inovaway.org:8010/radio.mp3?1593546947 is not working. By the way, others https links are working just fine. Just that one link https://radio.inovaway.org:8010/radio.mp3?1593546947 i cannot access over https.

Can you please tell me how to fix it?

Besides that azuracast is awesome. Thx

**Comment by ericmil87** [comment]
> Everything is working fine here BUT the webplayer is not playing on HTTPS only on HTTP. I debug and found that the url http://radio.inovaway.org:8010/radio.mp3 is working and the SSL url https://radio.inovaway.org:8010/radio.mp3?1593546947 is not working. By the way, others https links are working just fine. Just that one link https://radio.inovaway.org:8010/radio.mp3?1593546947 i cannot access over https.
> 
> Can you please tell me how to fix it?
> 
> Besides that azuracast is awesome. Thx

Here is the public webplayer link https://radio.inovaway.org/public/legal

**Comment by ericmil87** [comment]
I followed everything here and here https://github.com/AzuraCast/AzuraCast/issues/2947 and nothing worked

**Comment by ericmil87** [comment]
[
<img width="427" alt="Captura de Tela 2020-06-30 às 17 36 56" src="https://user-images.githubusercontent.com/1230921/86174611-5c373880-baf8-11ea-9bcc-de74169238ef.png">
](url)

**Comment by hillbilly-mark** [comment]
> 
> 
> for a VPS server how to do with an IP address ?
Thank you so much..  I had not considered using the IP to prevent SSL on all the wrong ports.  I think you solved my problem.  Awesome!

**Comment by ericmil87** [comment]
Did you solve it? How was it?

**Comment by siderissym** [comment]
> How do I fix the localhost certifacate problem?
> ![cert](https://user-images.githubusercontent.com/51458416/82839226-0b9f4080-9ea5-11ea-9e27-37a783775566.jpg)

I have the same issue. Any ideas? I am searching the last 2 months....
