### ISSUE TITLE
Problem, HELP ME!

### ISSUE THREAD

**Issue by AleAmla987** [AzuraCast/AzuraCast#2856]
Hello! I use the zararadio, but when I add the streaming URL xxx.com/radio/xxx/radio.mp3 to the playlist, the zararadio never plays it, just skip it. How can i fix this?

**Comment by zivanovicMilan** [comment]
ZaraRadio probably doesn't support https streams as a receiver.

**Comment by fast97** [comment]
I also said to myself that if azuracast could generate the pls, asx m3u and mp3 files in http://ip:port/mount also https://ip:port/mount and as currently proposed: https://ip/radio/port/mount would be great because most readers like itunes do not read https streams.

**Comment by fast97** [comment]
Try it like its: https: // ip: port / mount or http: // ip: port / mount it's working for me with icecast

**Comment by Xara** [comment]
I have simply two subdomains pointing to radio, as Opensim don't accept  HTPPs, one is certified, other is not , http on second work fine, I redirect all to HTPPs on first.

**Comment by fast97** [comment]
I also use it like that but for some clients it is not easy especially to generate lives files like pls m3u
