### ISSUE TITLE
API "is_live" not changing to true when connected

### ISSUE THREAD

**Issue by mikeopensauce** [AzuraCast/AzuraCast#2857]
**Using Docker installation method**
Yes

**AzuraCast version**
 v0.10.2, #f1b37e4 (2020-05-19 10:35) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 18.04.4

**Describe the bug**
The API is not returning the Live status correctly. API shows 
live
is_live | false
streamer_name | ""

When it should be showing true.

**To Reproduce**
Connected stream using BUTT. Stream plays out, autodj stops and also Now and Next info is shown correctly but "is_live" flag is not set to true.

**Expected behavior**
is_live should be set to true and streamer_name should be populated

**Relevant Logs**
None

**Screenshots**
Partial 
![Screenshot_2020-05-20 https stream rosettaradio co uk](https://user-images.githubusercontent.com/7012099/82436080-2892d880-9a8d-11ea-9057-4f495da2b9b2.png)
API output attached

**Device(s):**
None

**Additional context**
This does not interfere in anyway with the operation of Azuracast but it prevents us checking to see if we are on air using the API.

**Comment by dvdred** [comment]
it happened to me too. i don't know if it is correlated but I have activated the "WebSocket" from the settings menu in the general administration panel and for now it has not happened anymore

**Comment by mikeopensauce** [comment]
Well I don't know why that did it but it worked! Many thanks.
Mike
