### ISSUE TITLE
Unaccessible time selector

### ISSUE THREAD

**Issue by voipworld** [AzuraCast/AzuraCast#286]
Hello guys,
the time selector for the playlist schedule, become unaccessible, and that after the last commit with change to the time selector

**Comment by voipworld** [comment]
for your info, the issue tyhat made it unaccessible is #277
thanks.

**Comment by SlvrEagle23** [comment]
@voipworld Unaccessible in what way? The new element is just an HTML5 `time` input selector. Do screen readers not handle that properly?

**Comment by voipworld** [comment]
Hey,
Yes, not handled at all
Screen reader cant find it on screen

**Comment by SlvrEagle23** [comment]
@voipworld Ah, that's very unfortunate...I had figured that by this point, HTML5 custom input types would be supported broadly enough that it would be safe to use them. At this point, about 80% of the world's browser share fully supports them.

Is your screen reader attached to one particular browser, like IE?

**Comment by SlvrEagle23** [comment]
@voipworld I have reverted the time selector that uses the HTML5 time element until we can figure out why screen readers aren't handling it correctly. The previous method worked fine (albeit with less flexibility) and if it's more accessible, that's a priority.

**Comment by voipworld** [comment]
yes, tested it even in iOS, no luck...
i will pull & retry and fidback again
thanks!

**Comment by voipworld** [comment]
hello,
befaure i did a pull, i tryed it both in chrome & Firefox, no luck
so it should be a screen reader issue
i can confirm that the time selector is doing his right job right now
thanks a lot dude
