### ISSUE TITLE
AutoDJ stops sometimes, plays randomly, not according th order

### ISSUE THREAD

**Issue by EuropeanManager** [AzuraCast/AzuraCast#2868]
**Using Docker installation method**

Yes

**AzuraCast version**

v0.10.2, #f1b37e4

**Host Operating System**

ubuntu 18.04 TLS

**Describe the bug**

It doesn't play according the plan despite the fact that I've removed all the advanced features from the playlist. The timer of the song stops on my end after the playback. In the server it replays it over and over again. However, I see that in station management, in autodj tab I've chosen 'use liquidsoap on this server'. 

Should I choose 'Do not use an AutoDJ service' to shut down liquidsoap auto dj for good? Maybe that's the solution to my problem? 

and another thing, base station directory is shown /var/azuracast/stations/My_station_name. However, I cannot find this path on my mashine. Why?

**Expected behavior**

I need the specific playlists would start on specific time and would play songs according the sequence I've provided. different jingles, day times (morning, day, evening, night) and few extra playlists for different podcasts.
**Relevant Logs**

**AzuraCast application log**
`23T09:24:47.168924+00:00] AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... [] {\"station\":{\"id\":1,\"name\":\"* Radio\"}}\n[2020-05-23T09:24:47.171313+00:00] AzuraCast.ERROR: No playable tracks were found. [] {\"station\":{\"id\":1,\"name\":\"* Radio\"}}","position":3770051,"eof":false}`
**liquidsoap log**
![image](https://user-images.githubusercontent.com/65809016/82727130-27fa7c00-9cf1-11ea-9adf-771de03eb75b.png)

**Screenshots**
Rebuild AutoDJ queue
![image](https://user-images.githubusercontent.com/65809016/82727196-ab1bd200-9cf1-11ea-87b5-5a1bec81708b.png)
history is shown everything looks decent but no files to play. few playlists enabled with right time selected.

**Now playing debugger**
![image](https://user-images.githubusercontent.com/65809016/82727222-e0c0bb00-9cf1-11ea-9295-60b7f1f12ce6.png)

**Additional context**

tracks are in different names with some parts sometimes simillar. tired to restart it multiple times and after the installation. ran through the debuggers multiple times also. My time zone is ok and I did everything according the super issue here about the scheduled playbacks. It doesn't play even if I force the file to 'queue' with the button..

**Comment by ungaro** [comment]
any pointers on this, having related issues.
