### ISSUE TITLE
Change API/Cover URL

### ISSUE THREAD

**Issue by ZocherHD** [AzuraCast/AzuraCast#2869]
Hello, can i change the API/Cover url? 
The api to api.domainname.eu/ and the Cover to cdn.domainname.eu/coverpicture/

**Comment by SlvrEagle23** [comment]
@ZocherHD If you have global administrative access, there is a page called "Custom Branding" where you can specify a custom URL for the default album artwork cover. You can also specify this at a per-station level by editing the station's profile and specifying a default album art URL.
