### ISSUE TITLE
Embedded player doesn't work on custom website

### ISSUE THREAD

**Issue by addictif80** [AzuraCast/AzuraCast#2873]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.2, #954b4d7 (2020-05-23 1:28)

**Host Operating System**
 Ubuntu 18.04.3 LTS

**Describe the bug**
I have 2 servers at home
1. AzuraCast server : https://ac.myradio.tld
2. Web server for webradio website hosting : https://myradio.tld

Ports 80 & 443 redirect to the webserver directly from my router
The webserver redirect the ac.myradio.tld requests to the AzuraCast server (proxy_pass)
Ports 8000 & 8005 redirect to the AzuraCast server directly from my router
AzuraCast panel & public station page and https://ac.myradio.tld/public/myradio/embed are working
But when i use the embedded player code on my website, the code show "refused connection by ac.myradio.tld

**Screenshots**
![refused connection](https://user-images.githubusercontent.com/60296519/82741008-49d61c00-9d4e-11ea-9a34-c570e36411c1.png)

**Comment by SlvrEagle23** [comment]
@addictif80 This is very likely a product of your custom setup and not something necessarily wrong with AzuraCast itself. In particular, I would ensure that your SSL certificate for the AzuraCast domain is active and valid and isn't self-signed, as many browsers will allow you to manually override certificate warnings for whole page loads while refusing them in other scenarios.

**Comment by addictif80** [comment]
Hello, thanks for your reply :)
The SSL certificate for AzuraCast is managed by WebServer, but if it's necessary to setting up directly in AzuraCast Server, i don't know how to make it.
I've found that : https://www.azuracast.com/extending/modifying_docker.html#common-examples
But i don't know how to make it :/
