### ISSUE TITLE
Fatal Issue: Cannot find Audiowaveform package during Ansible Installation 

### ISSUE THREAD

**Issue by radioguy0** [AzuraCast/AzuraCast#2874]
**Using Docker installation method**
 No

**AzuraCast version**
 Latest Ansible release as of this post

**Host Operating System**
 Ubuntu 18.04 ARM64

**Describe the bug**
 At the point where OPAM and Liquidsoap have already been installed during the initial installation, a single fatal error appears beside the install of the ‘audiowaveform’ package. Upon researching this in more depth it would seem that a software version 1.4.1.1 that is similarly named was recently flagged as ‘out of date’ on the aur.archlinux.org website. The project in specific was github.com/bbc/audiowaveform which seemed to crosscheck with the title of this software. Upon checking the Github link, it seems that the ‘audiowaveform’ software has recently updated to 1.4.2

**To Reproduce**
 Run Ansible install using clone of the currently available source files. 

**Expected behavior**
 A clean and functional install of the software. Up until this point the Ansible install has worked normally without issue.

**Device(s):**
 - Device:  Raspberry Pi 4B 4GB RAM with 128GB internal flash storage. Also attempted on Raspberry Pi 3B, which produced the same error. Will attempt this on a laptop Ubuntu install and a VM to see if this is applicable to all installs or limited to ARM and/or other specific system types.

**Comment by SlvrEagle23** [comment]
@radioguy0 We use the audiowaveform library for generating the waveform that's used in the visual cue editor on the music manager page. Apparently they don't publish arm64 builds, which we just haven't noticed yet since a rather small number of folks use Raspberry Pi's for their radio stations.

Will flag this for further investigation...it may just be a feature we have to disable for ARM CPU users.

**Comment by radioguy0** [comment]
> @radioguy0 We use the audiowaveform library for generating the waveform that's used in the visual cue editor on the music manager page. Apparently they don't publish arm64 builds, which we just haven't noticed yet since a rather small number of folks use Raspberry Pi's for their radio stations.
> 
> 
> 
> Will flag this for further investigation...it may just be a feature we have to disable for ARM CPU users.

Thanks @SlvrEagle23 for the quick response! The waveform was apparently working prior to doing the most recent update, during which the device had frozen, resulting in having to re-flash the system. 

I had been trying to do backups every couple of days but evidently this didn’t work properly using the Ansible setup with the Pi, meaning there was nothing left to restore it back to, nor could I roll back to a prior version from here. When using the backup interface, it would display a normal pop up dialog going through each of the steps, acting as if the backup had worked correctly, but it appears from my issue here that this wasn’t the case. 

It’s definitely an interesting issue, because I was previously able to experiment with the visual editor somehow on the same device. It rolled in as part of one of your previous updates and even permitted changes using the ARM64 system. 

I would probably disable the feature for now, so it doesn’t wipe out the entire ARM64 audience for your software. I can drop the ‘audiowaveform’ devs a note on here as an enhancement suggestion, but like any new type of system, it can take a long time for people to adopt / incorporate it into their builds.

Right now, I have some older machines which I was thinking of trialling with Ubuntu 18 and running Azuracast through the Docker build, but this would be an optimal affordable setup if it worked with your Docker build in future. 

Would you have any recommendations of good computers for installing the software to and self-hosting? The bandwidth here is excellent and it is a great way to save on expensive plans with hosting, when you’re on a budget. Thanks for all your work!

**Comment by SlvrEagle23** [comment]
@radioguy0 The reason the waveform feature previously worked despite the audiowaveform library not being installed is because out of the box and by default, the Wavesurfer JS library will attempt to automatically create its own waveform from the file if the server doesn't give it one. This is much less reliable than having the server generate one, however, so we switched to preferring that whenever possible, which involved us adding audiowaveform to our package list.

I just pushed a patch that will disable the installation of the audiowaveform library on non-x86_64 architectures, which should prevent it from being a problem on Raspberry Pi devices.

**Comment by radioguy0** [comment]
Thanks for the follow up. It seems that it surpassed this step successfully, however the PHP 7.4 install had a fatal error which stopped the completion of the installation process. 

I reattempted the entire process then again for a second time and it somehow cleared, however, I encountered other minor errors which did not inhibit the install completion. Would you like me to share those error descriptions with you? 

The waveform editing seemed to work well on the previous version using the Pi. Is there any way of allowing that previous / alternative type of installation for ‘ARM systems only’, so those users can continue to make use of the new feature?

**Comment by SlvrEagle23** [comment]
@radioguy0 That's basically what I just did...I'm not sure what other errors will be happening with ARM64 installs but feel free to share them.

**Comment by radioguy0** [comment]
This is an error which occurs now when trying to add files into playlist... Nothing can air on the live feed at present as a result.

Array: The command “‘audiowaveform’ ‘-i’ ‘/my/path/to/file.mp3’ ‘-o’ ‘/tmp/awfwSXzz8.json’ ‘—pixels-per-second’ ‘20’ ‘—bits’ ‘8’” failed. Exit code: 127(Command not found) Working directory: /var/azuracast/www/web Output: ================ Error Output: ================ sh: 1: exec: audiowaveform: not found

During install on the CLI there were a couple red flags... None of which seem to have stopped the system installing at least.

MariaDB Cleanup: 
Failed: [localhost] (item=DROP DATABASE test) ... Can’t drop database ‘test’ ; database doesn’t exist ...

Set up AzuraCast database user:
[Warning]: Module did not set no_log for update_password

UFW - Enable AzuraCast TCP Ports: 
[Warning]: The value 80 & 443 (type int) in a string field was converted to  u’80’ & u’443’ (type string). 

I also get a deprecation notification for folder migration to /usr/bin/python3 from /usr/bin/python which will be deprecated in a future version, 2.12. The reason it says it is using the old system, is for backward compatibility with prior Ansible releases. It does state that it will default to using the discovered platform python for this host in the future release mentioned above.

**Comment by radioguy0** [comment]
@SlvrEagle23 As a positive addendum to this topic, the developer for ‘audiowaveform’ has now created an ARM compatible version for Ubuntu. Any chance we could update the Ansible script of AzuraCast again to install that version for ARM systems? Let me know if you need me to link it here.

**Comment by SlvrEagle23** [comment]
@radioguy0 Since they added ARM64 support to the PPA, then we can just re-enable the previous code and it should work fine on Raspberry Pi devices. I've done that as of the latest commit, which should put you back at feature parity with standard installs.
