### ISSUE TITLE
Web DJ link to 404 page not found

### ISSUE THREAD

**Issue by pwrj** [AzuraCast/AzuraCast#2876]
When I click on the Web DJ link it takes me to 404 page not found.

<img width="648" alt="Screen Shot 2020-05-24 at 8 55 58 PM" src="https://user-images.githubusercontent.com/7035452/82769191-75fea500-9e01-11ea-9082-8d1e824558d6.png">

**Comment by SlvrEagle23** [comment]
@pwrj I'm unable to reproduce this issue locally on my machine. Make sure that both the public pages and streamer/DJ accounts are enabled.

**Comment by pwrj** [comment]
@SlvrEagle23 I checked and both are enabled. I ran ./docker.sh update-self && echo "y" | ./docker.sh update and everything works again. Not sure why?
