### ISSUE TITLE
Unable to Save Changes in System Settings

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#2877]
It is not possible to Save Changes in System Settings page from the last update.

It always asks "Please enter a URL" in Site Base URL field. 
Although, URL is already entered and even not changed.

v0.10.2, #954b4d7 (2020-05-23 1:28) • Docker • PHP 7.4

**Comment by SlvrEagle23** [comment]
@stardevelop Try adding "http://" (or "https://" if you're on a secure page) in front of the URL. Previous versions of the system didn't require this but now we require that all URLs be fully-qualified.
