### ISSUE TITLE
Auto dj crossfade setup but in separate parameters (cross + fade)

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2879]
**Using Docker installation method**
 Yes

**AzuraCast version**
v0.10.2, #0babf87 (2020-05-25 8:31)

**Host Operating System**
 Ubuntu 18.04

**Describe the bug**
Can the auto dj crossfade be configured in separate parameters for cross and fade on GUI ? Often the cross between two songs sounds  unnatural especially when the song starts or ends with a cut. But just crossing + the original song fade, will sound much better.

**Comment by SlvrEagle23** [comment]
@eranwo Not currently via the web UI, but you can manually specify a crossfade in the custom Liquidsoap configuration (just make sure the safety fallback happens _after_ the crossfade, or else it won't launch correctly).

I don't consider this all that high of a priority for implementing in the web UI, but you're welcome to [submit a feature request](https://features.azuracast.com/) to have it added.
