### ISSUE TITLE
audio effects, dynamics

### ISSUE THREAD

**Issue by sorinszucsik** [AzuraCast/AzuraCast#288]
Hello, first let me say that AzuraCast is by far a pretty awesome toolfor radio enthusiasts and more. I am in radio broadcasting for about 17 years and wright now I have an onlina radio project called SZalt.stream and I'm using AzuraCast for that. I have 3 questions:
1. The sound is pretty flat. For a more radio like sound, it could be just fine to use some audio effects. I've tried to install ladspa for liquidsoap but I do not have that much skills to manipulate them. If some of ladspa plugins or other should e integrated in the web interface that would be pretty awesome.
2. We have to export the csv file of play history. It could be possible to select a period of time like monthly or so? 
3. When making a new radio it could be possible to have media folder limit? I see that If I've created 5 radio they all have the total space of the server. I want to allocate space individually for the radios.

Thank you in advance. I'm not an expert in coding but for management and administration of radio in general, if u want I can help with ideas.

**Comment by ckeurk** [comment]
it would be really nice if we could use ladspa plugins with liquidsoap. Then we have to see if SlvrEagle23's okay with it.

**Comment by SlvrEagle23** [comment]
@sorinszucsik @ckeurk In the interest of making sure Github issues are easy to follow for both users visiting this section and me as a developer, each issue should reflect one specific request for enhancement or a single report of a bug with the system.

I'll rename this enhancement request to be along the lines of item 1 on your list, but if you don't mind, could you add the other items as separate requests? Thank you!

**Comment by mickaelmonsieur** [comment]
indeed, a treatment on the sound still lacks a lot.
liquidsoap offers that it be implementable with a function, I have already tested "nrj" in the past.

**Comment by ckeurk** [comment]
After a long search!
Small contribution for better sound uniformity, at the bottom of the station profile page:

```
def nrj(s)
  compress(threshold=-15.,ratio=3.,gain=3.,normalize(s))
end

def sky(s)
  low = filter.iir.eq.low(frequency = 160.)
  mh = filter.iir.eq.high(frequency = 100.)
  mid = filter.iir.eq.low(frequency = 1800.)
  high = filter.iir.eq.high(frequency = 1366.)

add(normalize = false,
      [ compress(attack = 100., release = 200., threshold = -20.,
                 ratio = 6., gain = 6.7, knee = 0.3,
                 low(s)),
        compress(attack = 100., release = 200., threshold = -20.,
                 ratio = 6., gain = 6.7, knee = 0.3,
                 mid(mh(s))),
        compress(attack = 100., release = 200., threshold = -20.,
                 ratio = 6., gain = 6.7, knee = 0.3,
                 high(s))
      ])
end
```

**Comment by ckeurk** [comment]
LADSPA is now obsolete and superseded by the [LV2 format](http://lv2plug.in).
Also works with:
[Calf Studio Gear](http://calf-studio-gear.org)

**Comment by ckeurk** [comment]
Another solution that I think is really nice.
[stereotool.com](https://www.stereotool.com)

**Comment by SlvrEagle23** [comment]
We've already added support for basic compression and leveling (essentially a cleaned-up version of Liquidsoap's own `nrj` function) to AzuraCast itself, but for the request to allow custom equalization/dynamics beyond advanced configuration:

We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38784/support-custom-equalizer-configuration-inside-the-app
