### ISSUE TITLE
How to normalize audio?

### ISSUE THREAD

**Issue by 7miguelsilva7** [AzuraCast/AzuraCast#2880]
I had seen a code/script to normalize audio but can't find more, anyone can help me?

**Comment by SpeedyCharly** [comment]
All of my media is set to 128kbps (smaller size) AND normalized with MP3Gain prior to being uploaded to the server.. Allows me to have more titles in playlists while saving drive space and ensures constant volume to stream output at all times...

**Comment by zivanovicMilan** [comment]
Use the Thimeo WatchCat to normalize all audio in order to sound more professional.

**Comment by SlvrEagle23** [comment]
@7miguelsilva7 AzuraCast has a built-in setting called "volume normalization and equalization" that you can enable. It will apply a reasonable and not-too-powerful effect to keep everything level.

If you want to truly fine-tune your audio processing, as others have mentioned in this thread your best bet is to process your audio files before uploading them. You can also take that opportunity to convert them to, say, 128Kbps MP3 files (or whatever bitrate your station operates at) to lessen the transcoding load.

**Comment by zivanovicMilan** [comment]
@SlvrEagle23 Since it's better to use the same bitrate of MP3 files as on output stream, which is the best practice for live streaming? Higher bitrate or the same as output stream? Thanks!

**Comment by SpeedyCharly** [comment]
> @SlvrEagle23 Since it's better to use the same bitrate of MP3 files as on output stream, which is the best practice for live streaming? Higher bitrate or the same as output stream? Thanks!

I believe that was answered... same as output reduces the workload on the Azura server.  Another thing to consider is the fact that most listeners don't have their puter connected to high-end audio equipment, so, anything above 128Kbps is wasted on them.  Futhermore, I have enabled dual streams on my Azura installation one at 128 and another at 64kbps, to reduce the load for cells & tablettes...

**Comment by zivanovicMilan** [comment]
@SpeedyCharly Yes, it's obvious that the same input and output bitrate result in lower cpu usage on server, but I think that Liquidsoap does decode and than encode the stream, so maybe the higher input bitrate will brought a slightly better quality.
