### ISSUE TITLE
HTML Player on Public Page as an Iframe else were

### ISSUE THREAD

**Issue by moran1804** [AzuraCast/AzuraCast#2881]
**Using Docker installation method**

**AzuraCast version**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

Hi Guys, 

I have azure cast all working fine, but wondered is it possible to have the same player on the public page as a responsive Iframe on another page?

the issue is the one provided on the dashboard doesn't have the playlist or request features.

Thanks
Mike M

**Comment by SlvrEagle23** [comment]
@moran1804 Currently this isn't possible (unless you just directly embed the entire public radio player as an iframe, which is possible though not particularly attractive), but we have existing feature requests to add a feature akin to a "widget builder" that would let you build your own custom embeddable widgets.
