### ISSUE TITLE
Doctrine Database Migrations (Error)

### ISSUE THREAD

**Issue by dubloid** [AzuraCast/AzuraCast#2884]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.2, #c4e482c (2020-05-25 5:23)

**Host Operating System**
Ubuntu 18.04.4 LTS

**To Reproduce**
During update.

**Relevant Logs**

```
cd /var/azuracast
sudo ./docker.sh update
Pulling mariadb                 ... done
Pulling influxdb                ... done
Pulling redis                   ... done
Pulling stations                ... done
Pulling web                     ... done
Pulling nginx_proxy             ... done
Pulling nginx_proxy_letsencrypt ... done
Stopping azuracast_nginx_proxy_letsencrypt_1 ... done
Stopping azuracast_nginx_proxy_1             ... done
Stopping azuracast_web                       ... done
Stopping azuracast_stations                  ... done
Stopping azuracast_influxdb_1                ... done
Stopping azuracast_redis_1                   ... done
Stopping azuracast_mariadb_1                 ... done
Removing azuracast_nginx_proxy_letsencrypt_1 ... done
Removing azuracast_nginx_proxy_1             ... done
Removing azuracast_web                       ... done
Removing azuracast_stations                  ... done
Removing azuracast_influxdb_1                ... done
Removing azuracast_redis_1                   ... done
Removing azuracast_mariadb_1                 ... done
Removing network azuracast_default
azuracast_www_data
azuracast_tmp_data
azuracast_redis_data
Creating network "azuracast_default" with the default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_www_data" with default driver
Creating volume "azuracast_redis_data" with default driver
Creating azuracast_mariadb_1  ... done
Creating azuracast_influxdb_1 ... done
Creating azuracast_stations   ... done
Creating azuracast_redis_1    ... done
2020/05/26 19:13:23 Waiting for: tcp://mariadb:3306
2020/05/26 19:13:23 Waiting for: tcp://influxdb:8086
2020/05/26 19:13:23 Waiting for: tcp://redis:6379
2020/05/26 19:13:23 Connected to tcp://influxdb:8086
2020/05/26 19:13:23 Connected to tcp://redis:6379
2020/05/26 19:13:23 Connected to tcp://mariadb:3306
Updating AzuraCast...
(Environment: production)

AzuraCast Setup
===============

Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...
 * Environment: Production
 * Installation Method: Docker

Waiting for dependent services to go online...
 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ! [NOTE] Running in update mode.                                                                                       

Setting Up InfluxDB
-------------------

Database created.
Retention policies updated.
Continuous queries created.
InfluxDB databases created.

Running Database Migrations
---------------------------

                                                                    
                    Doctrine Database Migrations                    
                                                                    

WARNING! You have 1 previously executed migrations in the database that are not registered migrations.
    >> 2020-05-14 06:10:04 (20200514061004)
No migrations to execute.

Generating Database Proxy Classes
---------------------------------


 Processing entity "App\Entity\Settings"
 Processing entity "App\Entity\Song"
 Processing entity "App\Entity\SongHistory"
 Processing entity "App\Entity\CustomField"
 Processing entity "App\Entity\StationMedia"
 Processing entity "App\Entity\Station"
 Processing entity "App\Entity\StationPlaylistMedia"
 Processing entity "App\Entity\StationMediaCustomField"
 Processing entity "App\Entity\StationPlaylist"
 Processing entity "App\Entity\StationStreamer"
 Processing entity "App\Entity\RolePermission"
 Processing entity "App\Entity\StationMount"
 Processing entity "App\Entity\StationRemote"
 Processing entity "App\Entity\StationWebhook"
 Processing entity "App\Entity\SftpUser"
 Processing entity "App\Entity\StationSchedule"
 Processing entity "App\Entity\ApiKey"
 Processing entity "App\Entity\StationStreamerBroadcast"
 Processing entity "App\Entity\Analytics"
 Processing entity "App\Entity\User"
 Processing entity "App\Entity\Role"
 Processing entity "App\Entity\StationPlaylistFolder"
 Processing entity "App\Entity\StationRequest"
 Processing entity "App\Entity\Listener"
 Processing entity "App\Entity\AuditLog"
 Processing entity "App\Entity\Relay"

 Proxy classes generated to "/var/azuracast/www_tmp/proxies"

Reload System Data
------------------

Local cache flushed.

Refreshing All Stations
-----------------------


Restarting all radio stations...
--------------------------------

 0/1 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%[2020-05-26T19:13:24.047051+00:00] AzuraCast.INFO: Writing playlist file to disk... {"station":"STATION_NAME","playlist":"xxxxxx"} []
[2020-05-26T19:13:24.058722+00:00] AzuraCast.INFO: Writing playlist file to disk... {"station":"STATION_NAME","playlist":"xxxxxxxxx"} []
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


                                                                                                                        
 [OK] AzuraCast is now updated to the latest version!                                                                   
                                                                                                                        

2020/05/26 19:13:26 Command finished successfully.
azuracast_stations is up-to-date
azuracast_mariadb_1 is up-to-date
azuracast_redis_1 is up-to-date
azuracast_influxdb_1 is up-to-date
Creating azuracast_web ... done
Creating azuracast_nginx_proxy_1 ... done
Creating azuracast_nginx_proxy_letsencrypt_1 ... done
Update complete!
```

**Device(s):**
 - Device: macbook
 - OS: macOS Catalina

**Additional context**
Hello!

Tell me, please, what actions can I remove this error? Preferably in steps. Thank you very much in advance!

WARNING! You have 1 previously executed migrations in the database that are not registered migrations.
     >> 2020-05-14 06:10:04 (20200514061004)

**Comment by SlvrEagle23** [comment]
@dubloid Were you on the latest rolling-release version before setting "prefer release versions" and then updating again? That's likely the cause of this issue, because the latest rolling-release has database migrations that aren't present in the latest stable release version. It's recommended to only switch to a stable release version when new versions are released, or to create a new installation that is already on the latest stable release version and stays on it.

**Comment by kamalne** [comment]
zuracast:setup [--update] [--load-fixtures] [--release]

2020/05/28 20:39:43 Command exited with error: exit status 1
Removing azuracast_nginx_proxy_1
azuracast_stations is up-to-date
Recreating azuracast_mariadb_1 ...
azuracast_influxdb_1 is up-to-date
Recreating azuracast_mariadb_1 ... done
Recreating azuracast_web       ... done
Recreating 6a5c757561ed_azuracast_nginx_proxy_1 ...
Recreating 6a5c757561ed_azuracast_nginx_proxy_1 ... error

ERROR: for 6a5c757561ed_azuracast_nginx_proxy_1  Cannot start service nginx_proxy: driver failed programming external connectivity on endpoint azuracast_nginx_proxy_1 (fee48a1956f3dbaa81357b8b46d5356d72962f42af42e0f3e3e181c962238ccb): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for nginx_proxy  Cannot start service nginx_proxy: driver failed programming external connectivity on endpoint azuracast_nginx_proxy_1 (fee48a1956f3dbaa81357b8b46d5356d72962f42af42e0f3e3e181c962238ccb): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.
root@radio:/var/azuracast/www#

**Comment by kamalne** [comment]
Hello my friend, I had a problem with the possible setup help

programming external connectivity on endpoint azuracast_nginx_proxy_1 (fee48a1956f3dbaa81357b8b46d5356d72962f42af42e0f3e3e181c962238ccb): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for nginx_proxy Cannot start service nginx_proxy: driver failed programming external connectivity on endpoint azuracast_nginx_proxy_1 (fee48a1956f3dbaa81357b8b46d5356d72962f42af42e0f3e3e181c962238ccb): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by dubloid** [comment]
> @dubloid Were you on the latest rolling-release version before setting "prefer release versions" and then updating again? That's likely the cause of this issue, because the latest rolling-release has database migrations that aren't present in the latest stable release version. It's recommended to only switch to a stable release version when new versions are released, or to create a new installation that is already on the latest stable release version and stays on it.

Yes! Just as you said. Thank you, I will try to remove everything cleanly and reinstall it. Thanks for the answer!

**Comment by kamalne** [comment]
Firstly, prove me how to solve this problem

**Comment by dubloid** [comment]
> Firstly, prove me how to solve this problem

Based on the error log, there is only one option - your port "80" is used by some application, so nginx cannot start on this port.
