### ISSUE TITLE
After Livestream, music playing is recognized as "Unknown" - Working in the previous version

### ISSUE THREAD

**Issue by Kulcanhez** [AzuraCast/AzuraCast#2885]
**Using Docker installation method**
Yes.

**AzuraCast version**
v0.10.2

**Host Operating System**
Ubuntu 18.04 with latest updates

**Describe the bug / To Reproduce**
1. Music is playing and the Title and the Artist is showing up nicely.
2. I start the live stream and I stop the live stream.
3. It continues to play the latest music but now without any metadata, showing "Unknown".

**Expected behavior**
It is expected after the end stream for it shows the metadata correctly. I'm using the Azuracast embed player. It was working well in the previous versions.

**Relevant Logs**
```
2020/05/22 20:52:58 [lang:3] DJ Source disconnected! Current live DJ: bernardo
2020/05/22 20:52:58 [lang:3] AzuraCast Live Disconnected Response: true
2020/05/22 20:53:14 [dummy:3] Source failed (no more tracks) stopping output...
2020/05/22 20:53:14 [ecstatic_dance_radio_live_fallback:3] Switch to ecstatic_dance_radio_safe_fallback with forgetful transition.
2020/05/22 22:27:40 [lang:3] AzuraCast Raw Response: annotate:title="ED Utrecht LIVE (21/03/2020)",artist="Nykkyo Energy DJ",duration="7443.",song_id="b2da31e61f79e51bfe31ea24072f635b",media_id="4",liq_amplify="0.dB",playlist_id="8":/var/azuracast/stations/ecstatic_dance_radio/media/ed_utrecht_live_-_nykkyo_energy_dj.mp3
2020/05/22 22:27:40 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/ecstatic_dance_radio/media/ed_utrecht_live_-_nykkyo_energy_dj.mp3".
2020/05/22 22:28:20 [ecstatic_dance_radio_next_song:3] Prepared "/var/azuracast/stations/ecstatic_dance_radio/media/ed_utrecht_live_-_nykkyo_energy_dj.mp3" (RID 1).
2020/05/22 22:28:20 [cross_7804:3] Analysis: -101.481183dB / -48.625229dB (2.98s / 3.02s)
2020/05/22 22:28:20 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/05/22 22:28:20 [lang:3] AzuraCast Feedback Response: OK
```

```
[2020-05-22  18:23:20] WARN xml/parsing warning: 
[2020-05-22  18:23:20] WARN xml/parsing skipping element "stream-description" parsing "mount" at line 27
[2020-05-22  18:23:20] WARN slave/slave_startup process has 65536 max file descriptor limit
```

**Additional context**
Really thank you for the love and time that you all put in this amazing project ❤️

**Comment by Kulcanhez** [comment]
Yesterday, I restarted the server and I noticed the first mix was showing without the cover art, but the next one was already showing nicely.

**Comment by SlvrEagle23** [comment]
@Kulcanhez In the process of fixing #2728, it appears we inadvertently caused a problem with other playlists, and metadata "replaying" (which is necessary if switching back to a song from a live broadcast) was also disabled.

I've reopened the other issue and will follow up with the Liquidsoap team to see if there is a way to solve both problems elegantly without messing one or the other up.
