### ISSUE TITLE
docker installation error

### ISSUE THREAD

**Issue by kashifchat** [AzuraCast/AzuraCast#2887]
i am facing this issue in installation help me 

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.web.ports is invalid: Invalid port "y:2022", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.nginx_proxy.ports is invalid: Invalid port "y:443", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.nginx_proxy.ports is invalid: Invalid port "y:80", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.web.ports is invalid: Invalid port "y:2022", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.nginx_proxy.ports is invalid: Invalid port "y:443", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.nginx_proxy.ports is invalid: Invalid port "y:80", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.web.ports is invalid: Invalid port "y:2022", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.nginx_proxy.ports is invalid: Invalid port "y:443", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.nginx_proxy.ports is invalid: Invalid port "y:80", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
root@vmi391509:/var/azuracast#

**Comment by SlvrEagle23** [comment]
@kashifchat Did you try to run the installer by piping "yes" or something else through it, just answering "y" to all the questions?

You should not do that, because you will end up answering "y" to what ports you want to use, and other settings. AzuraCast will try to serve itself on port "y" and other very wrong things.

You can fix this by running:

```bash
./docker.sh change-ports
```
