### ISSUE TITLE
Failed to acquire the lock / possibly timeout related

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2888]
**Using Docker installation method**
Yes

**AzuraCast version**
 v0.10.2, #df80edc (2020-05-27 7:57)

**Host Operating System**
Ubuntu 20.04 LTS

**Describe the bug**
When a sync check is performed, it sometimes fails to acquire the Lock properly, from looking a bit deeper it may be related to timeout issues exceeding 30 seconds? 
**To Reproduce**
I'm unable to reproduce this error. 
**Expected behavior**
It to fully complete the sync task as normal. I'm currently doing some internal tests of extending the timeout to 45 seconds, to see if anything changes. 
**Relevant Logs**
```
web_1                      |  AzuraCast.INFO: Running Now Playing sync task [] []
web_1                      |
web_1                      | In Lock.php line 63:
web_1                      |
web_1                      |   Failed to acquire the lock.
web_1                      |
web_1                      |
web_1                      | sync:run [<task>]
```
**Screenshots**

**Device(s):**
Desktop / Chrome / Windows 10 / latest across all fronts. 
**Additional context**

**Comment by aconitumnapellus** [comment]
Im having this error while doing the 5-minute task
Could you resolve this @SC2Mitch and can you share your possible solution?
