### ISSUE TITLE
Can't dj stream with butt

### ISSUE THREAD

**Issue by ImaCrea** [AzuraCast/AzuraCast#2889]
Hello all,
ImaCrea here from MailTape collective. I've stumbled upon your work and it's stunning. I've worked in a radio in the past and if we had that we would have been so happy. I'm so glad to see such software exist in open source. Thank you for this amazin work.

So I'm trying to make it work. All seems good but I can't manage to stream live mixing from my computer to Azuracast. It's on a VPS (scaleway). More details below :

**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.2, #c4e482c (2020-05-25 5:23) • Docker • PHP 7.4

**Host Operating System**
Debian Buster (GNU/Linux 4.19.0-6-amd64 x86_64 )

**Describe the bug**
- BUTT seem to no be able to connect to the instance. Show "connecting" and that's all. Butt is trying to connect from a Mac 10.14.5

- I tried trough Icecast and Shoutcast. Nothing appears in Azuracast log, seems that connection doesn't get there for some reason. 

- Using a VPS (scaleway). Opened inbound and outbound connection for port 8005 tcp and udp.

**Comment by SC2Mitch** [comment]
Hi @ImaCrea 

Did you follow the guide on the AzuraCast website to use BUTT? 

https://www.azuracast.com/station-management/djs/streaming_software.html#butt-broadcast-using-this-tool

**Comment by ImaCrea** [comment]
Yes :)

- Here look, I created a streamer account:
![Capture d’écran 2020-05-28 à 09 59 51](https://user-images.githubusercontent.com/764332/83115030-0ff87300-a0ca-11ea-9ff2-157555cb27c9.png)

- Didn't touch its settings:
![Capture d’écran 2020-05-28 à 09 59 45](https://user-images.githubusercontent.com/764332/83115092-2acae780-a0ca-11ea-9220-837ffe0812f5.png)

- Then on Butt:
![Capture d’écran 2020-05-28 à 10 01 39](https://user-images.githubusercontent.com/764332/83115147-42a26b80-a0ca-11ea-9a9b-3883f2e86607.png)
With login:pass in password field

- And then stuck here:
![Capture d’écran 2020-05-28 à 10 09 05](https://user-images.githubusercontent.com/764332/83115862-497dae00-a0cb-11ea-84d9-1c38f358b9bd.png)

- I tried Icecast and Shoutcast:
![Capture d’écran 2020-05-28 à 10 07 54](https://user-images.githubusercontent.com/764332/83115892-54d0d980-a0cb-11ea-82c2-93f53e9bcc8c.png)
![Capture d’écran 2020-05-28 à 10 01 39](https://user-images.githubusercontent.com/764332/83115917-5a2e2400-a0cb-11ea-8401-2ac7f17a12cc.png)

If I try to check if 8005 port is open with https://www.yougetsignal.com/tools/open-ports/ it says it's **closed**. 
> Since I set "accept" on 8005 port tcp/udp inbound/outbound on my VPS settings (does it pose a security threat?), I guess there's an issue with Docker not able to properly expose this port?

**Comment by ImaCrea** [comment]
Ok I just tried to do `./docker.sh update` and for some reasons I ignore it solved the issue.

**Comment by ImaCrea** [comment]
Quick recap, I tried after having it worked :

- Deleted out inbound/outbound tcp/udp rules I opened on 8005 on my VPS
- `./docker.sh uninstall`
- `.docker.sh install`
- Tried to connect with BUTT, same error as previous : can't connect to it.
- `./docker.sh update`
- Now it's connecting!

Hope it helps for you to find where this issues comes from. Cheers ^^
