### ISSUE TITLE
INSTALL ERROR

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#289]
anyone can help to solve the issue?

TASK [ufw : UFW - Turn on Firewall] ************************************************************************************************************************************
changed: [localhost]

TASK [composer : Install Composer] *************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer", "delta": "0:03:02.136145", "end": "2017-11-21 10:31:27.496895", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2017-11-21 10:28:25.360750", "stderr": "", "stderr_lines": [], "stdout": "All settings correct for using Composer\nDownloading...\nThe \"https://getcomposer.org/versions\" file could not be downloaded: failed to open stream: Connection timed out\nRetrying...\nThe \"https://getcomposer.org/versions\" file could not be downloaded: failed to open stream: Connection timed out\nRetrying...\nThe \"https://getcomposer.org/versions\" file could not be downloaded: failed to open stream: Connection timed out\nThe download failed repeatedly, aborting.", "stdout_lines": ["All settings correct for using Composer", "Downloading...", "The \"https://getcomposer.org/versions\" file could not be downloaded: failed to open stream: Connection timed out", "Retrying...", "The \"https://getcomposer.org/versions\" file could not be downloaded: failed to open stream: Connection timed out", "Retrying...", "The \"https://getcomposer.org/versions\" file could not be downloaded: failed to open stream: Connection timed out", "The download failed repeatedly, aborting."]}

RUNNING HANDLER [azuracast-user : send user notification] **************************************************************************************************************

RUNNING HANDLER [azuracast-db-install : send mysql notification] *******************************************************************************************************

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=88   changed=70   unreachable=0    failed=1

**Comment by dennybrandes** [comment]
Heyo, how did you tried to install AzuraCast? Via Docker? Maybe you can provide us some system information like Docker(Compose) Version, your is etc.

**Comment by SlvrEagle23** [comment]
@reans Based on the error, this looks like a temporary timeout related to Composer's web site having issues (or your server having connectivity trouble to their server). If you try again later, it may resolve itself.

**Comment by SlvrEagle23** [comment]
@reans Did this issue resolve itself after repeated install attempts? The composer servers are up and running normally now, and installation should be working as expected. If so, please feel free to close this issue.
