### ISSUE TITLE
Issues setting up playlist interaction (clockwheel) 

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#2894]
My station uses multiple playlists -  Main Music - Secondary Music - Featured Artist - Jingles - Radio IDs etc... 
I want songs to be pulled from different playlists in different ways, example;
Main music > heavy rotation (Set as General Rotation - weight = 15) 
Secondary music > once every 5 songs
Featured Artist > once every 10 songs
Jingles > once every 15 songs (Set as **Jingle Mode**)
Radio IDs > once every 5 songs (Set as **Jingle Mode**) etc...

Problem is I can't get this to work properly because Jingles - Radio IDs and whatever else may be set to **jingle mode** ends up being counted as a song in the rotation. Therefore I might end up with less than 5 from the Main playlist in between songs from Secondary and less than 10 between selections from Featured Artist.

What needs to happen to fix this is that selections from playlist set to **jingle mode** must not be counted as songs so that, as in my example, 5 songs would be pulled from the Main playlist in between selections from the Secondary and 10 from both Main and Secondary in between Featured Artist selections, regardless of how many selections are pulled from **jingle mode** playlists in the meanwhile.

Another nice touch that should be added to **jingle mode** is that selections from such playlists shouldn't be cross-faded as they are usually short soundbites of 90 seconds or less and content gets lost in the cross-fading...

Thank you for reading me and keep up the GREAT work ♫

SpeedyCharly

**Comment by SpeedyCharly** [comment]
Hi again - seeing no action on this since May 29 - is the issue dead or waiting to be resolved in some way?

**Comment by SlvrEagle23** [comment]
@SpeedyCharly I would've responded to your issue earlier, but I've been sidetracked with lots of side issues. Important to remember we're still in the middle of a global pandemic, after all.

If you come across an item that you would consider "nice to have", it's likely that it can instead be submitted as a new feature request over on our [FeatureUpvote](https://features.azuracast.com/) site, where people vote on new features to be implemented.

**Comment by SpeedyCharly** [comment]
Danke Mein Herr; Issue added to Feature Requests - Guess it can be closed on this side...

**Comment by SpeedyCharly** [comment]
Something funy happened here  i had transferred this to the suggestion page a per your suggestion and it disappeared into thin air.... what gives?

**Comment by theblindadvocateproject** [comment]
I agree. I would like to see a feature like Clockwheels. Here is a link to my feature request. https://features.azuracast.com/suggestions/124222/clockwheels-a-very-important-feature-for-a-radio-station

**Comment by SpeedyCharly** [comment]
> I agree. I would like to see a feature like Clockwheels. Here is a link to my feature request. https://features.azuracast.com/suggestions/124222/clockwheels-a-very-important-feature-for-a-radio-station

We already do have something approaching SAM's clockwheel feature on Azura; it just needs a bit of tweaking to be fully functional
