### ISSUE TITLE
embed player configuration

### ISSUE THREAD

**Issue by Reaktiv4** [AzuraCast/AzuraCast#2896]
A few examples, a couple of questions may come in handy.

In the embedded code, increase the minimum height to 300px

We insert on the server - https://myazuraserver.com/admin/branding

`.stations nowplaying {font-size: 35px !important; }
.now-playing-art {min-width: 40% !important; }
.now-playing-art img {min-width: 90% !important; }
.now-playing-title {font-size: 25px !important; }
.now-playing-artist {font-size: 20px !important; }
.time-display-played {font-size: 20px !important; }
.time-display-progress { display:none !important; }
.progress { display:none !important; }
.progress-bar bg-secondary { display:none !important; }
.time-display-total { display:none !important; }
.radio-controls { display:none !important; }
.radio-control-play-button { display:none !important; }
.radio-control-volume-slider input.custom-range { display:none !important; }`

We get the font and the image more, remove everything else.
![azura](https://user-images.githubusercontent.com/49731123/83280634-a10d3e00-a1df-11ea-9172-05318c9f99dd.JPG)

`.stations nowplaying {font-size: 35px !important; }
.now-playing-art img {display:none !important; }
.now-playing-title {font-size: 25px !important; }
.now-playing-artist {font-size: 20px !important; }
.time-display-played {font-size: 20px !important; }
.time-display-progress { display:none !important; }
.progress { display:none !important; }
.progress-bar bg-secondary { display:none !important; }
.time-display-total { display:none !important; }
.radio-controls { display:none !important; }
.radio-control-play-button { display:none !important; }
.radio-control-volume-slider input.custom-range { display:none !important; }`

We also remove the image. 
![azura 2](https://user-images.githubusercontent.com/49731123/83280629-9f437a80-a1df-11ea-8a07-5c856508d8cb.JPG)
Changing all these settings, you can adjust the player for yourself.

Two questions for developers.
1. Why is there no list of lost songs in the player?
2. How to make the image in the player not clickable?

Please, help

**Comment by Kulcanhez** [comment]
@Reaktiv4 for making the image in the player not clickable you just need to add a CSS property to it `pointer-events: none;` 🙂

**Comment by Reaktiv4** [comment]
Thanks, you really helped! In the future, developers can embed a list of lost tracks or even make embedding separately. The topic is often raised on the forum.
