### ISSUE TITLE
Ansible Restore Fails on InfluxDB Import

### ISSUE THREAD

**Issue by alaryn** [AzuraCast/AzuraCast#2897]
**Using Docker installation method**
No

**AzuraCast version**
AzuraCast • v0.10.2 Release Build • Ansible

**Host Operating System**
Ubuntu 18.04.3 LTS

**Describe the bug**
(Just to preface this ahead of time, I understand that the Ansible installation method is no longer supported officially and if I'm SOL then I entirely understand.  However, considering this issue occurs after a successful installation, I thought it was worth mentioning.)

- I was moving my Azurcast server from one host to another as the original host server was being shut down.
- I performed manual backup (both with and without media) and brought it over to the new host. 
- Ansible installation succeeded on new host with zero issues.
- Attempts to restore the backup using 'console azuracast:restore' have failed using both the full media and non-media versons of the backup.  I have tried on both a completely clean install, and also after running the update.sh script after the install script.

**To Reproduce**
The only command run was - 
/var/azuracast/www/bin/console azuracast:restore /root/backup-azuracast.zip

**Expected behavior**
Expected previous installation and all server settings to be restored.

**Relevant Logs**

No log file was found in /var/log/influxdb

The primary error message appears to be: 
**error updating meta: DB metadata not changed. database may already exist restore: DB metadata not changed. database may already exist**

I tried hunting around via google and found that this error shows up quite a bit.  Most people also reference using 'legacy restore' as an alternative but I'll fully admit that I'm not savvy enough to figure out if there's a manual database restore solution here.  

Here is the full output given on using the console restore command:

```
root@live:/tmp# /var/azuracast/www/bin/console azuracast:restore /root/backup-azuracast.zip

AzuraCast Restore
=================

Please wait while the backup is restored...

Extracting backup file...
-------------------------

Archive:  /root/backup-azuracast.zip
  inflating: tmp/azuracast_backup_mariadb/db.sql
   creating: tmp/azuracast_backup_influxdb/
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s496.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s148.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s503.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s170.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s478.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s509.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s505.tar.gz
  inflating: tmp/azuracast_backup_influxdb/20200524T192900Z.manifest
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s390.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s500.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s516.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s493.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s499.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s82.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s477.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s434.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s324.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s302.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s506.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s508.tar.gz
  inflating: tmp/azuracast_backup_influxdb/20200524T192900Z.meta
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s487.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s104.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s512.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s481.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s511.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s518.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s368.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s490.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s474.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s60.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s16.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s38.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s280.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s346.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s192.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s214.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s456.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s502.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s484.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s236.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s515.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s517.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s126.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s258.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s412.tar.gz
 extracting: tmp/azuracast_backup_influxdb/20200524T192900Z.s7.tar.gz

Importing database...
---------------------


2020/05/29 17:04:16 error updating meta: DB metadata not changed. database may already exist
restore: DB metadata not changed. database may already exist

In Process.php line 256:

  The command "'influxd' 'restore' '-portable' '-host' 'localhost:8088' '/tmp/azuracast_backup_influxdb'" failed.

  Exit Code: 1(General error)

  Working directory: /tmp/azuracast_backup_influxdb

  Output:
  ================


  Error Output:
  ================
  2020/05/29 17:04:16 error updating meta: DB metadata not changed. database may already exist
  restore: DB metadata not changed. database may already exist


azuracast:restore [--restore] [--release] [--] <path>
```

Any help would be appreciate, but as I said before, I know I'm being naughty by using the ansible installation, so I am ready to rebuild all of my stations from scratch if need be. ;) 

Thanks!

**Comment by SlvrEagle23** [comment]
@alaryn It appears the error in this case is valid, because when you run the initial installation on Ansible, it sets up an InfluxDB database that the restore then thinks it can't replace because one already exists.

In Docker, we remove all of the associated volumes during the restore process, which gives us a "clean slate" when doing the restore. It's likely that doing something similar (removing the InfluxDB databases from wherever they're stored on Ansible, which I don't actually recall off the top of my head), then restarting the service, then running the restore...should fix things right up.
