### ISSUE TITLE
Internal IP addresses being shown interspersed with public IPs

### ISSUE THREAD

**Issue by pixel-paul** [AzuraCast/AzuraCast#2898]
**Using Docker installation method**
Yes

**AzuraCast version**
Powered by AzuraCast • v0.10.2, #a10e161 (2020-05-28 6:30) • Docker • PHP 7.4

**Host Operating System**
CentOS 8.1

**Describe the bug**
Internal IP addresses are being detected on certain connections.

For example:
`
192.168.16.6 | 61 | desktop_windows Desktop Device                             Mozilla/5.0 (Macintosh; Intel Mac OS X  10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139  Safari/537.36 | Internal/Reserved IP
`

However this is interspersed with public IP addresses (in the listener logs).

**To Reproduce**
View listeners - internal IP address is shown

**Expected behavior**
Public IP addresses should be shown

**Relevant Logs**
Is it possible to see which updates have been applied, similar to a git log?

**Screenshots**
![Screenshot_2020-05-29 Listeners(1)](https://user-images.githubusercontent.com/389303/83292870-c8193f00-a1e2-11ea-8bb7-ae8f211d2fa3.png)

**Additional context**
This is since a recent update (in the past 2 days).

**Comment by arulvakku** [comment]
Yes, having the same problem here too. Unable to get the public IP.

**Comment by pixel-paul** [comment]
I've found a bit of time to dig a bit deeper into this issue. 

In my case, the server is behind a firewall, so the stack is as follows:

Firewall -> 1:1 NAT -> Server (192.168.0.10) -> Docker (192.168.16.1)

Interestingly, if connecting through TuneIn (which connects to a legacy mount point /tunein.pls), the correct IP address is passed through. The remote IP address from Tunein connecting to Icecast through their python lib in icecast.log:

`49.12.37.152 - - [13/Jul/2020:16:33:25 +0100] "GET /tunein.pls HTTP/1.0" 200 32399 "-" "Python-urllib/3.5" 1`

Then my external IP address (which must be passed through following connection) appears in Azuracast. 

However, if connecting through my external website (which uses the default Azuracast mount point /radio.mp3) and howler.js to connect to the mount point, no IP is recorded in Icecast and the internal Docker IP address appears in Azuracast.

**Comment by TA1USA** [comment]
Hi
I have the same problem, what's the solution?
![Annotation 2020-09-05 210215](https://user-images.githubusercontent.com/33510791/92312730-8f47ed80-efbb-11ea-9886-a56cf78f3c0d.png)

**Comment by M0IZH** [comment]
I made an update this morning, it has improved.

Powered by AzuraCast • v0.10.3, #de74d50 (2020-09-05 22:00) Rolling • Docker • PHP 7.4

**Comment by TheRealMakkus** [comment]
Same problem here. Without changing anything in the system - apart from Azuracast Updates... :-(

**Comment by pavel-kirpikau** [comment]
I'm not sure if that is connected, but the problem with internal IPs started after I set up a relay. I removed it later, did the full update and restart, but still stack with Internal IPs. 
My version: Rolling Release #991465d (2021-01-05 11:02) • Docker • PHP 7.4

Any solution to fix that?

**Comment by christiansacks** [comment]
I have just updated to the latest version and now I am seeing this too.
![image](https://user-images.githubusercontent.com/40481087/106219500-60801d00-61d1-11eb-8485-577f2a0de962.png)

**Comment by SlvrEagle23** [comment]
We've reverted some optimizations made to our software stack (in particular, how our nginx servers interact with one another) and this appears to have fixed a majority of the "internal IP showing" issues. We also applied another fix to the outermost of our nginx servers (the `nginx_proxy` service) that was already applied to the nginx server on the `web` container, which appears to have fixed a fair amount of the other issues. A majority of users, especially those on Icecast, should be having no trouble with internal IP addresses showing up now.

**Comment by paulsoler** [comment]
Hello, I have the same problem, it is solved then with an update from azuracast???

**Comment by pavel-kirpikau** [comment]
> Hello, I have the same problem, it is solved then with an update from azuracast???

I'm on AzuraCast • Rolling Release #283946e (2021-01-26 11:21) on Docker and it's fine again. I used to have that issue but seems that it was fixed. Check @SlvrEagle23 message above.

**Comment by paulsoler** [comment]
> > Hello, I have the same problem, it is solved then with an update from azuracast???
> 
> I'm on AzuraCast • Rolling Release #283946e (2021-01-26 11:21) on Docker and it's fine again. I used to have that issue but seems that it was fixed. Check @SlvrEagle23 message above.

Ok ! i will update then on Docker

**Comment by Jaadoo13** [comment]
Hello. I got the same Problem. Also im on the actually docker version. So, how can i fix this?
v0.12.2 Stable • Docker • PHP 7.4
172.19.0.1 is the IP for all Listeners.
Thx for help...

**Comment by paulsoler** [comment]
I effectively solved this problem by updating

**Comment by Jaadoo13** [comment]
@paulsoler thx. But as you saw, I already have the actually stable version. And have also tried to reinstall. But it does not helped. 

So what Else...
