### ISSUE TITLE
Update to specific commit

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#2901]
Hi, 

is it possible to update Azuracast on a specific commit? 

The background of my question: we've been doing extensive testing with 0.10.2 (on a test server) before we can update on our live radio server. As far as I know, an update always uses the master head commit, which can cause inconsistencies (we test with a commit and update with another one).

Thanks

**Comment by SlvrEagle23** [comment]
@gammaw We now maintain a second Docker image for all of our containers that's tagged "stable". For the web container, this is always the latest tagged release version of the application. If you're using the latest `docker-compose.yml` and `docker.sh` files, then you can run:

```
./docker.sh setup-release
```

to switch to the stable builds for all images.

**Comment by gammaw** [comment]
@SlvrEagle23 thanks, that's great effort!
