### ISSUE TITLE
Adding a station on these ports: 8080, 8085 and 8086

### ISSUE THREAD

**Issue by esmondgh** [AzuraCast/AzuraCast#2907]
Using Docker installation method:
Yes

Host Operating System:
Ubuntu 18.04

AzuraCast Version:
0.10.2

Question:
Nothing is sitting on these ports on my server, but I'm unable to add a station.
Is there a way to add a station on these free ports on my server?.

**Comment by SlvrEagle23** [comment]
@esmondgh We deliberately avoid assigning a station in the range of port 8080 as it's so frequently used by web servers and other debug tools that port conflicts are _much_ more likely to happen with it than with any of the other ports we clear.

Currently there is no way to instruct the system to go ahead and use port 8080 in its assignment range.
