### ISSUE TITLE
Links are not supported

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#2908]
**Using Docker installation method**
No

**AzuraCast version**
v0.10.2, #f44261b (2020-05-30 1:36)

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
500 Internal Server Error
(Links are not supported, encountered link at /var/azuracast/stations/radio_club-bg/media/Music
NotSupportedException.php : 21)

**To Reproduce**
1. Mount NAS to the server.
2. Link the mounted folder to the "/var/azuracast/stations/<station>/media/" folder.
3. Open the Music Files page or more specific: http://Localhost/api/station/1/files/list?internal=true&rowCount=10&current=1&file=

**Expected behavior**
I expect to read the folder as real folder and choose the songs from that Symbolic linked folder.

**Device(s):**
 - Device: Raspberry Pi 3b+
 - OS: Ubuntu LTS 18.04
 - Browser: Safari/Chrome

**Additional context**
Well, many of you will know that the raspberry pi have lacking on space.
Thats why i use NAS storage and have like 600-700GB of music.
So instead of reuploading all songs to the radio server, its cool to be mounted to the server and symbolic linked to the media folder.
Actually, the first time that i create the folder i saw all folders from the NAS drive. Than i refresh the page and start giving this 500 Internal Server Error with the api, that have to read the folders and files.

In addition, as i saw how the system works, you have to create playlists and select the songs for that playlists. What i was thinking is better to can use realtime folder as playlist.
Let me give you example as this will be advantage:
So you have stored music into your NAS drive. (lets say the mounted folder works) And you select all songs from one folder to be in your playlist. OK, but if you add another songs to the NAS drive, they wouldn't be in the playlist. And you have to go to the playlist, and click the new songs to add them. It will be much easier and faster, if the realtime playlist/folder read all the files from this folder right before it starts. In this case, you'll be sure that all songs in your NAS will be played over the radio :)

**Comment by SlvrEagle23** [comment]
@NicoxDJ This is a limitation with our filesystem abstraction library that we use (Flysystem), and it's not something they intend to support in the immediate future. See thephpleague/flysystem#599 for more information.

Apparently one solution is to have the root of the filesystem be a symlink (i.e. your entire media directory, not just a subfolder under it), which seems to work without issue; it only fails when a folder _within_ that library is a symlink.

**Comment by NicoxDJ** [comment]
> Apparently one solution is to have the root of the filesystem be a symlink (i.e. your entire media directory, not just a subfolder under it)

Thanks @SlvrEagle23 ! This seems to work well!
Only something else is bothering me now. When i added a folder with 240 songs to playlist, they are adding really slow. Like 1 song per 10-15 seconds. Is that normal? Probably its processing for tags, etc?

**Comment by SpeedyCharly** [comment]
Had similar limitations with my previous host server... limited to 1500 tunes @128kbps (about 5G) So I circumvented the problem by turning Liquidsoap off and creating a robot with clockwheel an PAL scripts on SAM locally.  Only problem was that I had to provide the DJs with a manual means of kicking me whenever they needed to get on air...  but it works fine without any constraints whatsoever...

**Comment by NicoxDJ** [comment]
I just found one problem that might cause the scan abortion:
`Array: An exception occurred while executing 'INSERT INTO station_media (station_id, song_id, title, artist, album, lyrics, isrc, length, length_text, path, mtime, amplify, fade_overlap, fade_in, fade_out, cue_in, cue_out, art_updated_at, unique_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, null, "Remember Me (Sure Is Pure Edit)", "The Blue Boy", "Remember Me (CD, Single)", null, "051628-2,0516282", 230, "3:49", "2 Da Club\/Club\/The Blue Boy - Remember Me (Sure Is Pure Edit).mp3", 0, null, null, null, null, null, null, 1591042929, "3ac890f7077db92e390514b1"]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'isrc' at row 1`
I will edit the field in mysql and keep you updated.

**Comment by NicoxDJ** [comment]
So basically its all about "audiowaveform". Is there anyway to skip these waveforms? I want to use my m4a songs in my station. I'm trying now to ignore the error from "audiowaveform" but will see whats will happen :(

**Comment by NicoxDJ** [comment]
QuickFix:
You open `azuracast/www/src/Service/AudioWaveform.php`
And add this line:
```
return $input['data'] = [];
```
under:
```
public static function getWaveformFor(string $path): array
    {
```

More strange is, that after you hit "Edit" button on any m4a file, and go to the "Visual Cue Editor" the waveform shows again... even after you disable JSON waveform generation...

Now i hope the devs make another solution for that :)

**Comment by SlvrEagle23** [comment]
@NicoxDJ I've updated the application to more gracefully handle errors when attempting to process new media when it can't generate a waveform for a given file. It will now just log the error in the system log, store an empty waveform in the system cache, and then the client side will attempt to manually generate a waveform if it can (which is what you're seeing in the instances where it has already failed to render properly).
