### ISSUE TITLE
Lopping audio track

### ISSUE THREAD

**Issue by demil** [AzuraCast/AzuraCast#291]
How hard is to implemet looping options for certain audio tracks in playlists?

For example we could set some track do loop every 60 minutes etc.

**Comment by SlvrEagle23** [comment]
@demil The easiest solution to this is to create a playlist that's scheduled to play every 60 minutes, then add the track to that playlist. By default, all playlists will shuffle their contents and play one random song from their contents when their scheduled time comes up, so if a playlist only has one file in it, it'll always play that file on schedule.
