### ISSUE TITLE
Could not create a playlist: An error occurred and your request could not be completed.

### ISSUE THREAD

**Issue by aripisprecer** [AzuraCast/AzuraCast#2910]
**Using Docker installation method**
Yes

**AzuraCast version**
AzuraCast • v0.10.2, #c4e482c (2020-05-25 5:23) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 20.04 x64 LTS

**Describe the bug**
It is not possible to create a new playlist

**To Reproduce**

**Expected behavior**
The playlist with the given name should be created

**Relevant Logs**

After i click on save, i get the following error:
An error occurred and your request could not be completed.

**Comment by SlvrEagle23** [comment]
@aripisprecer We need the full body of the error message you're encountering. This can be found one of two ways:

 - In your browser, open the inspector (usually by hitting F12), click the "Network" tab, then try to save your changes again; you'll see a request that shows up in red with a 500 error; click that and look at its response body, which should be an error message that you can then paste here; or
 - Using the system-wide Log Viewer (from System Administration) you should also see an error in the AzuraCast application log.

**Comment by aripisprecer** [comment]
Sorry for my late reply.
After spending some time with this, i decided to reinstall Azuracast. It seems something was wrong with my installation.

After the reinstall, i am able to create new playlists.

Thank you!
