### ISSUE TITLE
Uploading music to new server quietly fails

### ISSUE THREAD

**Issue by shagia** [AzuraCast/AzuraCast#2911]
**Using Docker installation method**

Yes

**AzuraCast version**

v0.10.2, #bb1188e (2020-05-18 7:03)

**Host Operating System**

Debian 10.3

**Describe the bug**

After installing a new Azuracast instance with Docker on a Proxmox shell, you can't seem to upload music. You can set up, edit settings it seems, but uploading music through the GUI seems to either
A. upload, but disappear, with no new file
or if the file is small, B. upload, but by the end of the file, the word "true" in red pops up under the upload bar and freezes right there. 

**To Reproduce**

Maybe you'd have to setup an environment where Azuracast is being proxied by a shell with Nginx (refer to additional context), but
1. Install Debian 10.3
2. Install using the root user
3. Make an account
4. Go to Music Files
5. Upload a song
6. Either the progress fails silently or you get 'true' under the progress bar

**Expected behavior**

It should upload the music and be ready to add to a playlist, I've used Azura on another shell before (granted, I installed it as a normal user without issue) and I've never experienced something like this.

**Relevant Logs**

Influxdb_1 consistently brings back:

> influxdb_1  | ts=2020-06-01T07:45:01.827663Z lvl=info msg="Executing query" log_id=0MrcrNo0000 service=query query="SHOW DATABASES"
influxdb_1  | [httpd] 172.18.0.6 - - [01/Jun/2020:07:45:01 +0000] "GET /query?q=SHOW+DATABASES HTTP/1.1" 200 122 "-" "GuzzleHttp/6.5.3 curl/7.68.0 PHP/7.4.5" ccdac1ae-a3db-11ea-861b-000000000000 577

stations_1 consistently reports:

> stations_1  | 2020-06-01 07:46:01,110 INFO exited: tmpreaper (exit status 0; expected)
stations_1  | 2020-06-01 07:46:02,117 INFO spawned: 'tmpreaper' with pid 29752
stations_1  | 2020-06-01 07:46:03,555 INFO success: tmpreaper entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

and when attempting to upload music, the js console brings back:
> SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Screenshots**

https://i.imgur.com/f2tkneS.png Just this when a small upload fails

**Device(s):**
I've attempted this on both latest desktop versions of Chrome and Firefox under macOS Catalina, same issue.

**Additional context**

Maybe it's relevant that the Azura shell is being pointed to another shell hosting nginx that pushes the browser to the Azura shell, but I'm not entirely sure. To add on, I also installed as a root user due to strange permission issues I couldn't figure out attempting to install it as a 'normal' user. Could this be a permission issue itself?

Thank you!

**Comment by SlvrEagle23** [comment]
@shagia If, while you're uploading something, you open your browser's inspector console (usually F12 key), and click the "Network" tab, then try the upload again...you may see a request that lights up in red with an error message. If you click that request, you may see an error message that could help us diagnose the problem. If so, please paste it here.

**Comment by shagia** [comment]
I get a 413 Request Entity Too Large. I'm assuming this is server side?
[](https://i.imgur.com/uyOdGac.png)

**Comment by SlvrEagle23** [comment]
@shagia How big are the tracks you're uploading?

**Comment by shagia** [comment]
It could range from a simple megabyte song to just any size. I asked my host if my nginx config could be my problem, I'll be testing that tonight.

**Comment by shagia** [comment]
It was the Nginx config! Sorry for your time, setting up this time's just been wonky so I thought it might have been related to the software...

Thank you!
