### ISSUE TITLE
docker.sh.update(): Failed attempt of trying to remove azuracast_www_data volume

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#2912]
Is it a legacy volume that you try to remove if an old Azuracast version is being updated? On newer installation it's a non-existing volume. The error doesn't look harmful but users (like me) are always worried to see errors during an update :)

![image](https://user-images.githubusercontent.com/28865986/83398014-db085b00-a3fe-11ea-8df8-c0407edb66a5.png)

**Comment by SlvrEagle23** [comment]
@gammaw Missed that in the latest updates...we no longer use the `azuracast_www_data` volume so this isn't necessary any more. Should be fixed in the latest update for `docker.sh`.
