### ISSUE TITLE
Cant configure to access with external sources in SHOUTCAST

### ISSUE THREAD

**Issue by duduws** [AzuraCast/AzuraCast#2917]
![image](https://user-images.githubusercontent.com/64056323/82107273-8f666980-96fc-11ea-8d9d-4ac4125540ec.png)

Only accept liquidsoup source, but i want to connect without source from remote host, but how can i configure it? im using latest docker version. i want to stream music with another liquidsoap host, like from my computer. but i cant find the shoutcast file to change localhost to accept all 0.0.0.0

**Comment by aripisprecer** [comment]
Hi!

you don't  have to configure shoutcast manuall, just go into azurcast, station, manage -> edit profile.

Than go to Broadcasting and set a port which is already configured on the docker-compose file (for example 8000). Also please make sure to select shoutcast dnas 2 server as broadcasting service.

If you want to broadcast only from an external source, go to auto dj and select "do not user autodj service".

If you want bot auto dj and external source, than leave autodj on and select the allow streams/dj option, than configure the Dj/Streamer port and Internal requests port.

Click on Save changes.

Go to Streamer/Dj Accounts on the lest menu and create a dj account. Save the config.
Use this dj account to connect to azuracast from an external source. (you will get the connect details on the Stremeamer/DJ accounts page).

It should work but you have to be sure that there is no firewall which could block this ports
