### ISSUE TITLE
shoutcast AAC+ v2 streaming 32-64 kbps: buffering every 0.5s

### ISSUE THREAD

**Issue by aripisprecer** [AzuraCast/AzuraCast#2918]
**Using Docker installation method**
Yes

**AzuraCast version**
AzuraCast • v0.10.2, #c4e482c (2020-05-25 5:23) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 20.04 LTS amd64

**Describe the bug**
* When using the AAC+ v2 codec with profies 32-64 kbps, the sound is droping/buffering every 0.2-0.5s

* When using the 96-320kbps profile, it works without any problem.
* Also when i deactivate AutoDJ and i am streaming from an external source directly to Shoutcast (any AAC bitrate), it works normally.

* I am using SHOUTcast Server v2.5.5.733/posix(linux x64)

**To Reproduce**

1. I have Activated AutoDJ for my station and created an AAC+ v2 mountpoint (32-64 kbps profile)
2. Stream from the liquidsoap to the AAC mountpoint

**Expected behavior**
The stream should work normally

**Relevant Logs**

**Comment by adoboligh1** [comment]
Shoutcast 2.6 does not support AAC streams.
