### ISSUE TITLE
SSL problem using docker and letsencrypt on centos VPS

### ISSUE THREAD

**Issue by s7ntax** [AzuraCast/AzuraCast#2920]
I have installed azuracast using docker onto my domain arpradio.com and when I view the public page using https I get the following message from firefox.

Warning: Potential Security Risk Ahead

When I click on the lock it says:
Connection not secure
Your connection to this site is not secure

Clicking More information:
Owner: This website does not supply ownership information.
Verified by: IT
Expires: 30 May 2021

Technical Details:
Connection Not Encrypted
The website arpradio.com does not support encryption for the page you are viewing.

So I did the following over ssh

```
./docker.sh change-ports
Port to use for HTTP connections [8080]: 
Port to use for HTTPS connections [8081]:
Port to use for SFTP connections [8082]:
docker-compose: error while loading shared libraries: libz.so.1: failed to map segment from shared object: Operation not permitted
docker-compose: error while loading shared libraries: libz.so.1: failed to map segment from shared object: Operation not permitted
```

So I had to issue 

`mount /tmp -o remount,exec`

Then I was able to re-run ./docker.sh change-ports and i set them to the default

http 8080
https 8081
sftp 8082

The output from that was 

```
Stopping azuracast_nginx_proxy_letsencrypt_1 ... done
Stopping azuracast_nginx_proxy_1             ... done
Stopping azuracast_web                       ... done
Stopping azuracast_stations                  ... done
Stopping azuracast_influxdb_1                ... done
Stopping azuracast_redis_1                   ... done
Stopping azuracast_mariadb_1                 ... done
Removing azuracast_nginx_proxy_letsencrypt_1 ... done
Removing azuracast_nginx_proxy_1             ... done
Removing azuracast_web                       ... done
Removing azuracast_stations                  ... done
Removing azuracast_influxdb_1                ... done
Removing azuracast_redis_1                   ... done
Removing azuracast_mariadb_1                 ... done
Removing network azuracast_default
Creating network "azuracast_default" with the default driver
Creating azuracast_mariadb_1  ... done
Creating azuracast_stations   ... done
Creating azuracast_redis_1    ... done
Creating azuracast_influxdb_1 ... done
Creating azuracast_web        ... done
Creating azuracast_nginx_proxy_1 ... done
Creating azuracast_nginx_proxy_letsencrypt_1 ... done
```

So then I issued the following and got the output

```
./docker.sh letsencrypt-create arpradio.com
Stopping azuracast_web ... done
Going to remove azuracast_web
Removing azuracast_web ... done
azuracast_stations is up-to-date
azuracast_mariadb_1 is up-to-date
azuracast_redis_1 is up-to-date
azuracast_influxdb_1 is up-to-date
Creating azuracast_web ... done
azuracast_nginx_proxy_1 is up-to-date
azuracast_nginx_proxy_letsencrypt_1 is up-to-date
```

Still I am getting the same error when I go to the public page
https://arpradio.com:8081/public/arp_radio

So I tried the following and got the output

```
docker-compose down
Stopping azuracast_web                       ... done
Stopping azuracast_nginx_proxy_letsencrypt_1 ... done
Stopping azuracast_nginx_proxy_1             ... done
Stopping azuracast_stations                  ... done
Stopping azuracast_influxdb_1                ... done
Stopping azuracast_mariadb_1                 ... done
Stopping azuracast_redis_1                   ... done
Removing azuracast_web                       ... done
Removing azuracast_nginx_proxy_letsencrypt_1 ... done
Removing azuracast_nginx_proxy_1             ... done
Removing azuracast_stations                  ... done
Removing azuracast_influxdb_1                ... done
Removing azuracast_mariadb_1                 ... done
Removing azuracast_redis_1                   ... done
Removing network azuracast_default

docker-compose up -d
Creating network "azuracast_default" with the default driver
Creating azuracast_mariadb_1  ... done
Creating azuracast_stations   ... done
Creating azuracast_redis_1    ... done
Creating azuracast_influxdb_1 ... done
Creating azuracast_web        ... done
Creating azuracast_nginx_proxy_1 ... done
Creating azuracast_nginx_proxy_letsencrypt_1 ... done
```

Still the same issue. I'm at a loss as to why it isn't properly adding the letsencrypt cert and can only assume that it's reverting back to the self signed cert but I don't know why or how to fix it.

**Comment by s7ntax** [comment]
Just to add more problems, I decided to uninstall azuracast and reinstall it, i tried to do this in a sub domain as i thought this was the issue. It wouldn't install, so I uninstalled docker and reinstalled docker but now I get this error when installing azuracast.

```
Creating azuracast_nginx_proxy_1 ... 
Creating azuracast_nginx_proxy_1 ... error

ERROR: for azuracast_nginx_proxy_1  Cannot start service nginx_proxy: driver failed programming external connectivity on endpoint azuracast_nginx_proxy_1 (41318f9168b5982ac845c7854ec00ed03b094a1a4f0918aa77eeae2e5fbc4fae): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use

ERROR: for nginx_proxy  Cannot start service nginx_proxy: driver failed programming external connectivity on endpoint azuracast_nginx_proxy_1 (41318f9168b5982ac845c7854ec00ed03b094a1a4f0918aa77eeae2e5fbc4fae): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

**Comment by SlvrEagle23** [comment]
@s7ntax A number of people have reported issues getting things to run properly on CentOS. We're not exactly sure what's causing these things, since there's nothing about our setup that is particular to a certain host platform (and it's known to work on several Linux distros, Windows and MacOS).

Of particular note, though: LetsEncrypt won't set up and automatically provision an SSL certificate if you're using nonstandard web ports, i.e. 8080/8081. Your connection must be on ports 80 for HTTP and 443 for HTTPS to LetsEncrypt to properly register.

**Comment by s7ntax** [comment]
Thanks for your reply. 

I wasn’t aware I had set it up on non standard ports as I typed N when it asked me whether I wanted to use custom ports and the docker installer chose those ports for me. 

So I’ve been in touch with my host and asked about using a different Linux distribution which they say is no problem so I need to backup some configs and hose the thing and get another distribution installed. 

Which distribution would you recommend?

**Comment by s7ntax** [comment]
Just so I can do this only once and not have to hose my server a 3rd time can you please advise. 

I think the problem I had with the ports was due to ports 80/443 being in use by the main site as I did try the change ports command in docker but it said ports in use and wouldn’t set them and reverted back to 8080/8081 etc. 

So what I want to do is wipe my server, install a better Linux distribution that will work better with Azuracast. Admin on my hosting say they will do this. I just need to choose which distribution is best. 

Then I want to create a sub domain say radio.arpradio.com and install Azuracast in there so that I can access it on the standard ports. 

I also plan to install a wordpress site on another sub domain say main.arpradio.com and then setup a redirect from the arpradio.com url to the main.arpradio.com sub domain. So visitors can just go to the main url and find themselves on my wordpress site and I can go to the sub domain for Azuracast and login to the admin. 

When I installed Azuracast I did so in /var/azuracast and this doesn’t ask me where I wish to install it, so could I create the docker.sh install script in the sub domain where I want Azuracast to live or will this not work. This is what I tried last night after uninstalling Azuracast and it wouldn’t work, so I messed around deeper and broke more stuff so now I can’t even install it in /var/azurcast 

So how is it possible to have the setup I described with everything in its own sub domain and the correct ports assigned. 

I don’t know how I ended up with ports 8080/8081 as I didn’t assign my own ports so docker must have done this on the initial install due to 80/443 not being available or in use.

**Comment by SlvrEagle23** [comment]
@s7ntax I'd recommend using Ubuntu 20.04 if possible, or 18.04 as a backup option. Both have excellent track records supporting AzuraCast.

You can run your main web site on the same server that hosts AzuraCast since we now package a reverse proxy as the primary web server that can handle domain names and LetsEncrypt certificates for any number of containers. Our [guide for setting up multi-site installations](https://www.azuracast.com/extending/multisite.html) is a little sparse at the moment, but it links over to the nginx proxy documentation that can be of some assistance in this regard.

**Comment by s7ntax** [comment]
Thanks again for your help, I will request that my provider install the distribution you recommend and start over tomorrow. 

I need a break and also a drink :)

**Comment by aripisprecer** [comment]
@s7ntax :

We are using CentOS in our company and i personally don't like it (not the Versions 6+).
I would recommend you to set selinux at permissive and also deactivate it and tray again.
Also please disable Apparmor and i am pretty sure it will work.

After that, you will have to configure selinux and apparmor correctly, which is not that easy :)

**Comment by s7ntax** [comment]
I've worked out how to get around my problem regarding ports.

I had to trick let's encrypt and it's probably a bit unorthodox but hey, it worked.

I uninstalled azuracast, went into my whm and changed the default ports to some random ports, this broke the rest of my site but made the standard ports available. I then installed azuracast on standard ports, setup let's encrypt and everything went smoothly. Then I changed the azuracast ports using docker to 8080 and 8443 and went back into whm and changed the ssl settings back to standard 80/443 ports so now the main site works again and i can get to my public page in azuracast using the url https://arpradio.com:8443/public/arp_radio without any error messages from the browser.

I will have to repeat this process every time I need to update the certificate but at least now I can iframe the public player into my wordpress site without any issues, hopefully... Not got to that yet.

Now time for that drink.

**Comment by SlvrEagle23** [comment]
@s7ntax It's precisely for situations like this that we added multi-site support into the core AzuraCast installation, but I admit that we haven't done enough to document how that works, because it seems there is a fundamental misunderstanding of it from many users. The one "problem", if you will (not a problem to us dev folks but perhaps to users) is that to take full advantage of our multi-site setup, _all_ of your sites must be Docker containers, not just AzuraCast.
