### ISSUE TITLE
SSL Certificate issue with 2 subdomains

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#2922]
I try to install Let's Encrypt certificate for 2 subdomains on a single server with the below command.

./docker.sh letsencrypt-create
and I enter both subdomains when asked:
Domain name (example.com) or names (example.com,foo.bar) to use with LetsEncrypt                                                                 [stream1.domain.com,stream2.domain.com]: stream1.domain.com,stream2.domain.com

Everything goes fine and I get:
azuracast_nginx_proxy_1 is up-to-date
azuracast_nginx_proxy_letsencrypt_1 is up-to-date

But certificate is just installed for stream1.domain.com and I get error message in the browsers for stream2.domain.com

Both subdomains points to a single IP address and I want to be able to access the platform from both host names.
https://stream1.domain.com (Set as Site Base URL)
https://stream2.domain.com (Points to the platform IP address)

**Comment by SlvrEagle23** [comment]
@stardevelop Both should be valid HTTPS certs, though the second domain will be a SAN certificate added onto the first domain.

For more information, see [this page](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Let's-Encrypt-and-ACME.md#multi-domains-certificates) which explains how our nginx proxy's letsencrypt companion works.

**Comment by stardevelop** [comment]
@SlvrEagle23 Yes, I need exactly to do so. The first domain certificate works fine but the second certificate is invalid.
How can create separate certificates for each domain using Azuracast docker command?

**Comment by SlvrEagle23** [comment]
@stardevelop Well, by default the SAN certificate it serves for the multiple sites should be perfectly valid, so I'm curious why your browser isn't considering that cert valid for the other hostnames. You appear to have set it up correctly too.

As an experiment, you can try creating a `docker-compose.override.yml` file with these contents:

```
version: '2.2'
services:
  nginx_proxy_letsencrypt:
    environment:
      LETSENCRYPT_SINGLE_DOMAIN_CERTS: true
```

then restart your services via running `docker-compose down` and `docker-compose up -d`.

**Comment by stardevelop** [comment]
After latest update (No longer generate self-signed cert on nginx), the problem solved.
