### ISSUE TITLE
how to undo the dashboard changes through command-line

### ISSUE THREAD

**Issue by Gujalls** [AzuraCast/AzuraCast#2923]
Dear Team,

The issue is a simple one.

This morning while I was in my dashboard under settings. I saw an option which mentioned 'Always HTTPS On' or sort.. and i enable this option and clicked save.
After that I'm not able to access my dashboard - I get the below error

**SSL received a record that exceeded the maximum permissible length.
Error code: SSL_ERROR_RX_RECORD_TOO_LONG**

Please can you let me know which file I should edit in the command line to disable this option so that I can get my dashbaord working again on http rather than https. I can see lot of files under this directory /var/lib/docker/volumes/azuracast_www_data/_data
Or if the above error can be a simple fix from my end - then what should I go to get the SSL working.

Thanks for your response.

**Comment by SlvrEagle23** [comment]
@Gujalls The command to run if you're on a Docker installation is:

```bash
./docker.sh cli azuracast:settings:set always_use_ssl false
```

**Comment by Gujalls** [comment]
Thanks for your response.
I followed the above instruction. 

cd /var/azuracast
./docker.sh cli azuracast:settings:set always_use_ssl false
Starting azuracast_influxdb_1 ... done                                                                                  Starting azuracast_mariadb_1  ... done                                                                                  Starting azuracast_redis_1    ... done                                                                                  Starting azuracast_stations   ... done                                                                                  2020/06/05 16:19:01 Waiting for: tcp://mariadb:3306
2020/06/05 16:19:01 Waiting for: tcp://influxdb:8086
2020/06/05 16:19:01 Connected to tcp://mariadb:3306
2020/06/05 16:19:01 Connected to tcp://influxdb:8086

AzuraCast Settings
==================


 [OK] Setting "always_use_ssl" updated.

sudo systemctl restart docker

Is there anything that I'm missing coz the URL is still automatically being redirected to https :( and so the same error and not able to login to the dashboard?

Please can you help.

Best regards

**Comment by SlvrEagle23** [comment]
@Gujalls Now your browser's caching the HSTS setting, because it's told to do so. Resetting this varies depending on the browser, and in some cases I'm not sure it's possible at all.

Try loading the page with a different browser at this point, and it shouldn't have the HSTS settings turned on (alternatively you can also try Private Browsing or Incognito mode to achieve the same result).

Ideally, you could just finish setting up your HTTPS connection with LetsEncrypt so you will have a valid HTTPS connection, which will avoid this issue being a problem in the first place.

**Comment by Gujalls** [comment]
Thanks for your responses.

I tried in different browsers and machines but no use. Finally I identified the issue. 
My HTTPS port was configured to use different port and changing it in the URL worked.

Currently I'm able to access it over https. 

Thank You.
