### ISSUE TITLE
Advanced Playlists Question

### ISSUE THREAD

**Issue by graemetadata** [AzuraCast/AzuraCast#2925]
Hi - I'm trying to implement the "Case Study: Side-by-side Playlists" solution to "fix" jingles to either side of a news bulletin; however, I can't see anywhere to add backend code at the bottom of the Profile>autoDJ in the same way that there is a way to add code to the frontend broadcasting section.

Is this solution now obsolete?

Thanks

Graeme

**Comment by SlvrEagle23** [comment]
@graemetadata This feature is considered advanced and is now hidden from the UI by default after we received a huge flood of new issues from users who weren't comfortable with advanced functionality and yet enabled it anyway, then broke their installations.

You can follow [this guide](https://www.azuracast.com/extending/advanced-features.html) to enable the advanced functionality.
