### ISSUE TITLE
No sound from the player on the public page or <iframe> player

### ISSUE THREAD

**Issue by s7ntax** [AzuraCast/AzuraCast#2928]
So I managed to iron out all the issues in my previous post and everything is working apart from, there is no sound from the player on the public page or <iframe> embed player. 

I know there is sound at the mount points as I have opened the url to those directly and i can hear sound on my phone in the browser, so somehow the mountpoints are not sending audio to the public page player or the url set to this player is wrong. Is it possible to check this and edit the url to the mountpoint that the player will use. 

You can see that the metadata is coming through, just no sound.
I'm sure I could hear sound on a previous installation on my iphone so I know it's not an ios issue.

https://i.imgur.com/sw6GtxD.png

Other than this issue, this is now functioning brilliantly and I suppose I could always use a different embed player but it would be nice to have this public page player working properly as well.

**Comment by SlvrEagle23** [comment]
@s7ntax I suspect this has something to do with how it's generating the listen URL for your stream. If you look at the station's profile, is the listen URL there actually correct? (i.e. if you click it, does it open an audio player in your browser?)

This could also be a product of HTTPS certificate issues.

You may be able to find out more by opening your browser's inspector console (usually F12) and looking at either the Console or Network tab for errors as you click play.

**Comment by s7ntax** [comment]
These work in the box to the right on the station admin page.
https://i.imgur.com/R5MQspn.png

However when I go to the public page and open the console I get these errors.

Some cookies are misusing the recommended “sameSite“ attribute 21
Cookie “app_session” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable.

Invalid URI. Load of media resource  failed.

**Comment by SlvrEagle23** [comment]
@s7ntax Is it trying to load a different URI than the one you see on the play page? It should be using the exact same one, which if it works on that one end should work on the other.

I'll also create another GH issue for the sameSite attribute.

**Comment by s7ntax** [comment]
OK yes is it looking at a slightly different url, the port is wrong so changing the ports has not updated the main player url

The one that works is https://arpradio.com:8443/radio/8000/arp.mp3?1591362471

The player is looking at https://arpradio.com:8000/arp.mp3?1591362332

So it's throwing up an error, i need to change the port in the station to 8443?

**Comment by SlvrEagle23** [comment]
@s7ntax You may need to enable the "Use Web Proxy" setting at the system level, because it's possible the system doesn't think it needs to be enabled when generating the URLs for the NowPlaying API but it does when you're pulling it from the profile page.

**Comment by s7ntax** [comment]
Thanks, that has fixed it.

**Comment by ryanginnelly252** [comment]
Hi I'm getting the same - do I just update SSL?
