### ISSUE TITLE
disallow old insecure ciphers for nginx

### ISSUE THREAD

**Issue by christiansacks** [AzuraCast/AzuraCast#2931]
**Using Docker installation method**

Yes

**AzuraCast version**

Powered by AzuraCast • v0.10.2, #109b65e (2020-05-12 10:49) • Docker • PHP 7.4
Like our software? Donate to support AzuraCast!

**Host Operating System**

$ lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Describe the bug**

Some older browsers can't connect and complain that an insecure cipher (RC4) is present so refuse to connect - ref; https://cier.tech/blog/tech-tutorials-4/post/how-to-disable-rc4-using-nginx-32

**To Reproduce**

Launch AzuraCast website with Opera 36.0 System: Windows XP 32-bit

**Expected behavior**

When viewing the public page, should be able to listen to music

**Relevant Logs**

domain.com uses an unsupported protocol.

The client and server don't support a common SSL protocol version or
cipher suite. This is likely to be caused when the server needs RC4,
which is no longer considered secure.

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 
Device: Laptop - Lenovo G530
OS: Windows XP 32-bit
Browser: Opera
Version: 36.0.2130.80 (current latest)

**Additional context**

**Comment by christiansacks** [comment]
I got a shell in the web container, and manually added the following lines in the /etc/nginx/sites-available/default config file;

ssl_ciphers RC4:HIGH:!aNULL:!MD5;
ssl_prefer_server_ciphers on;

This seems to allow SSL Labs at least to see it and give it now an A for security.

**Comment by SlvrEagle23** [comment]
@christiansacks Your `docker-compose.yml` file may be out of date. Make sure when you're updating that you run both:

```
./docker.sh update-self
./docker.sh
```

and answer "yes" when prompted to update your `docker-compose.yml` file. The `web` container is no longer the front-facing container of the AzuraCast installation; we've added a reverse proxy in front of it that supports running multiple applications on the same VPS as an AzuraCast installation.

**Comment by christiansacks** [comment]
ok I have folowed this all and now the site won't load at all.
when i load the public page, I see my background that I customized and this is inside the box instead of the media player buttons and information;

500
An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.short_name AS short_name_3, t0.is_enabled AS is_enabled_4, t0.frontend_type AS frontend_type_5, t0.frontend_config AS frontend_config_6, t0.backend_type AS backend_type_7, t0.backend_config AS backend_config_8, t0.adapter_api_key AS adapter_api_key_9, t0.description AS description_10, t0.url AS url_11, t0.genre AS genre_12, t0.radio_base_dir AS radio_base_dir_13, t0.radio_media_dir AS radio_media_dir_14, t0.nowplaying AS nowplaying_15, t0.nowplaying_timestamp AS nowplaying_timestamp_16, t0.automation_settings AS automation_settings_17, t0.automation_timestamp AS automation_timestamp_18, t0.enable_requests AS enable_requests_19, t0.request_delay AS request_delay_20, t0.request_threshold AS request_threshold_21, t0.disconnect_deactivate_streamer AS disconnect_deactivate_streamer_22, t0.enable_streamers AS enable_streamers_23, t0.is_streamer_live AS is_streamer_live_24, t0.enable_public_page AS enable_public_page_25, t0.enable_on_demand AS enable_on_demand_26, t0.needs_restart AS needs_restart_27, t0.has_started AS has_started_28, t0.api_history_items AS api_history_items_29, t0.storage_quota AS storage_quota_30, t0.storage_used AS storage_used_31, t0.timezone AS timezone_32, t0.default_album_art_url AS default_album_art_url_33, t0.current_streamer_id AS current_streamer_id_34, t0.current_streamer_id AS current_streamer_id_35 FROM station t0 WHERE t0.short_name = ? LIMIT 1' with params ["subspace"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.enable_on_demand' in 'field list'
AbstractMySQLDriver.php : 60

**Comment by christiansacks** [comment]
I had to dun ./docker.sh letsencrypt-create as initially it wouldn't load as the certs were missing.

**Comment by christiansacks** [comment]
ah I fixed it I think, rebooted and re-ran ./docker update and all seems well now.

**Comment by christiansacks** [comment]
Thank you for your help with the other stuff. Going to test it all now

**Comment by SlvrEagle23** [comment]
@christiansacks That error indicates the latest update didn't run correctly; try running the update again and see if it resolves the issue.
