### ISSUE TITLE
invalid value "TLSv1.3"

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#2933]
**Using Docker installation method**
No

**AzuraCast version**
v0.10.2 - #c0faf65

**Host Operating System**
Ubuntu 16.04 LTS

**Describe the bug**
With the last update, nginx does not start.
Error log: invalid value "TLSv1.3"

**Relevant Logs**
`invalid value "TLSv1.3" in /etc/nginx/sites-enabled/00-azuracast:10`

**Additional context**
The problem is fixed when we remove the newly added SSL protocols.

**Comment by SlvrEagle23** [comment]
@ogrenci01 This should be fixed now.

**Comment by ogrenci01** [comment]
Yes. It is working correctly for Ubuntu 16.04 LTS. Thanks a lot.
