### ISSUE TITLE
Bug and few little fixes request

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#2940]
Hello! Everything with the system is fine. It's working, but i've notice few minor things that it's great to be fixed and added.

1. There is a bug with the now_playing and playing_next with the API, when you set Advanced AutoDJ Queue Length in AutoDJ over 1 (i set it as 3). I expected the 3 songs will came to the API, and i can see the next 3 songs, but instead of that there is only one in playing_next, and it was like randomly showed. So its 3 songs in the queue, but you see only one, and it might not be actually the next one. Like its wrong ORDER BY.
PS: Actually this is happen with Queue Length 1 too: https://imgur.com/a/qrWAGK8 (3 Photos)

2. It's cool in the Music Files to add new field with "Genre". For example i have now playlist with 2500 songs, and i want to remove all Country music. It will be hard find search it by names, length or album. But i can order it by Genre, and select it more easily.

3. If you remember, i made another issue, with the scanning files for waveforms. Right now i'm still keeping `return []` in the beginning of the whole file. Could you please make setting, to be checked do you want waveforms or no. This is life saver. Like 2500 songs in folder, would be scanned for days. And i have to restart the scans again and again (even that i set max_execution_time to 500 secs). Right now this 2500 songs were scanned with 3 rescans.

4. Speaking of Genre, could you please add this field in the `/api/nowplaying/`, and as i mention on another post here, it will be great if you can manipulate the genre with the DJ app, like here in the picture: https://imgur.com/a/9y8bIWy

5. There is something wrong with the external playlist when using "Direct Stream URL". For current song is displaying "Unknown". I don't know what is trying to get to display, but can you change it to show the playlist name instead Unknown. Like if you connecting to another station just for the news, it can display "NEWS" for current song.

6. Can the DJ's have specific artwork too? For example, when live DJ is playing to show his logo or photo instead of station default photo? Would be great! :)

7. There is something that already made by myself, and i will share it. It will be great to add it to the API. So basically the idea is to have external link to the recorded live sets, so if you have section in the website "listen on demand" or "listen what you miss", you can give the ability of the users to download or listen online the recorded sets. Right now, i gave access for the files via the static folder. I made symbolic link there of the recordings folder. `recordings -> /var/azuracast/stations/club-bg/recordings`and than i create one php file that i will use it as API:
```
$it = new RecursiveDirectoryIterator("static/recordings");
$display = Array ('mp3','wav');
$temp = [];
foreach(new RecursiveIteratorIterator($it) as $file)
{
    if (in_array(strtolower(array_pop(explode('.', $file))), $display)) {
        $parts = explode('/', $file);
        $time = $parts[3][0].$parts[3][1].$parts[3][2].$parts[3][3].
                '-'.$parts[3][4].$parts[3][5].
                '-'.$parts[3][6].$parts[3][7].
                ' '.$parts[3][9].$parts[3][10].
                ':'.$parts[3][11].$parts[3][12].
                ':'.$parts[3][13].$parts[3][14];
        $utime = strtotime($time);
        $temp[$utime]['path'] = 'http://'.$_SERVER['HTTP_HOST'].'/'.(string)$file;
        $temp[$utime]['dj'] = $parts[2];
        $temp[$utime]['time'] = $time;
    }
}
krsort($temp);
echo json_encode($temp);
```
Everything in all folders (all DJs) is sorted by unix timestamp. Its more easy to manipulate the array in this way.

Best regards

**Comment by SlvrEagle23** [comment]
@NicoxDJ I received an e-mail from you earlier this week asking why I hadn't looked at this issue.

Please understand that submitting a big long list of things, some of which are enhancement requests (which shouldn't actually be posted here at all, but rather [here](https://features.azuracast.com/) and bug reports can be not only overwhelming to see but very difficult to properly classify and keep track of in GitHub, which is oriented toward tracking the progress and status of singular issues instead of large groups of them.

Please submit items 2, 3 and 6 as feature requests on the FeatureUpvote site linked above.

For the remaining issues, please submit them individually as single bugs with appropriate additional details. Based on a cursory glance, these may not all be bugs but perhaps misunderstandings of how the API responds in given circumstances.
