### ISSUE TITLE
DELETED

### ISSUE THREAD

**Issue by menjilx** [AzuraCast/AzuraCast#2942]
Hi,
What is the right settings to show "Song Title" from MIXXX to Public Page?
![image](https://user-images.githubusercontent.com/14908836/84052563-55c70c80-a9e3-11ea-969f-2a95f44c07f9.png)

Currently, it will just show "unknown".

TIA

**Comment by Vaalyn** [comment]
You can refer to this part of the Mixxx documentation: https://mixxx.org/manual/latest/en/chapters/livebroadcasting.html#live-broadcasting-preferences

In the screenshot you'll see the `Custom metadata` section which will allow you to set your own metadata.
