### ISSUE TITLE
SSL On Ansible Installation

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#2943]
Hello,

How i add SSL on ansible installation Ubuntu 18.04?

Thank you

**Comment by SlvrEagle23** [comment]
@jonikane Follow the Certbot instructions on their web site to set up LetsEncrypt on nginx on Ubuntu: https://certbot.eff.org/lets-encrypt/ubuntuxenial-nginx.html

**Comment by jonikane** [comment]
i must do anything on domain panel?
