### ISSUE TITLE
playlist fonction suggest

### ISSUE THREAD

**Issue by sidney65** [AzuraCast/AzuraCast#2944]
Hi , 

I don't know if i’m in the right place . 
I noted the absence of a function in the playlists;
For some shows, I manually build a playlist. I noticed that we can add a title; change position; but if you mistakenly put a track you don't want, you can't remove it from this playlist. 
You have to start over !
It can be a feature to include in a future update.
Thanks for this great soft and the work to do.
Best Regards

**Comment by SlvrEagle23** [comment]
@sidney65 You don't have to start over with creating the playlist...just select the file you want to remove, click "set playlists", leave all of the playlists unchecked and click "Save", which will remove it from all existing playlists it's in.

**Comment by sidney65** [comment]
@SlvrEagle23 Thanks for your help and the job you do in this soft !
