### ISSUE TITLE
Localized strings view is broken in station profile page popup windows

### ISSUE THREAD

**Issue by vitoyucepi** [AzuraCast/AzuraCast#2945]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.2, #9a956b4 (2020-06-08 0:27)

**Host Operating System**
Debian 9, reproducible in demo

**Describe the bug**
`/station/1/profile` page toggle requests/streamers popup window text contains unicode escaped sequences like `\u041e`.

**To Reproduce**
1. Login to admin interface.
1. Set ru_RU(Russian) locale.
1. Go to `/station/1/profile` like https://demo.azuracast.com/station/1/profile
1. Press Enable/Disable(Включить/Выключить) button in Song Reuests/Streamers/DJs
1. You will see a popup window with escaped unicode sequences.

**Expected behavior**
Escaped unicode characters such as `\u041e` should be displayed as symbols.

**Screenshots**
![Popup window](https://i.imgur.com/X0NwNIo.png)

**Device(s):**
 - Device: Desktop
 - OS: Linux
 - Browser: Chromium/Chrome
 - Version: 83

**Additional context**
1. Popup window problem exists in other languages - tr_TR, cs_CZ and other with non-ascii symbols.

**Comment by SlvrEagle23** [comment]
@vitoyucepi Thank you for the report. This should be fixed as of the latest update.
