### ISSUE TITLE
Liquidsoap config editor view header is broken in Russian locale

### ISSUE THREAD

**Issue by vitoyucepi** [AzuraCast/AzuraCast#2946]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.2, #9a956b4 (2020-06-08 0:27)

**Host Operating System**
Debian 9

**Describe the bug**
`/station/1/ls_config` page contains broken encoded strings.
  Instead of
  ```
# Добро пожаловать в редактор [cuted]
  ```
  I get
  ```
# Доб�
[break line]
о пожаловать в �
[break line]
едакто�
[cuted]
  ```
  Every letter `р` - `\xd180` becomes `�` - `\xefbfbd`

**To Reproduce**
1. Login to admin interface
1. Set ru_RU(Russian) locale.
1. Go to `/station/1/ls_config` like https://demo.azuracast.com/station/1/ls_config (not available in demo)
1. You will see broken header.

**Expected behavior**
Broken header in liquidsoap config editor should contain letter `р` and not split into multiple lines.

**Screenshots**
![Liquidsoap config](https://i.imgur.com/5xkqJgb.png)

**Device(s):**
 - Device: Desktop
 - OS: Linux
 - Browser: Chromium/Chrome
 - Version: 83

**Additional context**
Only ru_RU localized header of config editor is broken

**Comment by dubloid** [comment]
Забудьте про русский язык в опенсурсе =)

**Comment by SlvrEagle23** [comment]
@vitoyucepi Thank you again for the report. This is fixed as of the latest version.
