### ISSUE TITLE
nginx/nchan error

### ISSUE THREAD

**Issue by chubbynugly** [AzuraCast/AzuraCast#295]
Hi everyone,
I'm executed the sudo shell script with this commands:
################
apt-get update
apt-get install -q -y git
mkdir -p /var/azuracast/www
cd /var/azuracast/www
git clone https://github.com/AzuraCast/AzuraCast.git
chmod a+x install.sh
./install.sh
#################

and receive those errors:

TASK [nginx : Install nginx/nchan from deb packages] *********************************************************************************************************
changed: [localhost] => (item=https://nchan.io/download/nginx-common.ubuntu.deb)
failed: [localhost] (item=https://nchan.io/download/nginx-extras.ubuntu.deb) => {"changed": false, "failed": true, "item": "https://nchan.io/download/nginx-extras.ubuntu.deb", "msg": "'/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" install 'liblua5.1-0'' failed: E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).\n", "rc": 100, "stderr": "E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).\n", "stderr_lines": ["E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution)."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nYou might want to run 'apt --fix-broken install' to correct these.\nThe following packages have unmet dependencies:\n nginx-common : Depends: sysv-rc (>= 2.88dsf-24) but it is not installable or\n file-rc (>= 0.8.16) but it is not installable\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "You might want to run 'apt --fix-broken install' to correct these.", "The following packages have unmet dependencies:", " nginx-common : Depends: sysv-rc (>= 2.88dsf-24) but it is not installable or", " file-rc (>= 0.8.16) but it is not installable"]}

RUNNING HANDLER [azuracast-user : send user notification] ****************************************************************************************************
to retry, use: --limit @/var/azuracast/www/util/ansible/deploy.retry

PLAY RECAP ***************************************************************************************************************************************************
localhost : ok=40 changed=9 unreachable=0 failed=1
##########################

**Comment by SlvrEagle23** [comment]
@chubbynugly First question: what version of Ubuntu are you installing AzuraCast on? Currently, due to issues with package compatibility, only 16.04 LTS is supported.

Second, if you manually run `apt-get install liblua5.1-0` does it specify a dependency that's missing?

**Comment by SlvrEagle23** [comment]
@chubbynugly Closing this issue as it hasn't been updated in quite some time. Currently, the nginx/nchan libraries are not supported on ARM-based computers, and until they update their end, we won't be able to offer ARM support for our whole software suite.

If you're still having issues installing nginx/nchan on Ubuntu 16.04 on an x86/x64 CPU, please feel free to reopen this issue if needed.
