### ISSUE TITLE
How to configure Authhash for Shoutcast

### ISSUE THREAD

**Issue by sahebsharmarbn** [AzuraCast/AzuraCast#2952]
As all of you probably aware that Shoutcast requires an authhash to be configured with the stream wanting to list on their platform. How can I edit the config file of a shoutcast stream to put the authhash generated from shoutcast radio manager?

**Comment by SlvrEagle23** [comment]
@sahebsharmarbn This should be something you see when configuring individual Mount Points if your station is set to use SHOUTcast 2 as its broadcasting server.
