### ISSUE TITLE
Stream with no MeataData shows "Stream offline

### ISSUE THREAD

**Issue by suricloud** [AzuraCast/AzuraCast#2955]
**Using Docker installation method**
YES

**AzuraCast version**

**Host Operating System**
Debian 9

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

Hi,if metadata is not sent by an encoder to the live stream,on azuracast it shows the status offline and no listener data is then showed.How can i manualy edit or set a metadata for that station like " Live Stream" ?

**Comment by SlvrEagle23** [comment]
@suricloud We've looked into this before, and unfortunately there isn't much we can do about it from our end. AzuraCast sees an empty string as your nowplaying song as the station being offline because that's exactly the same response it gets if the station _is_ offline and not broadcasting.
