### ISSUE TITLE
translate PT-BR

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#2957]
hello, I completed the translation of PT-BR in the crowndin, but it still doesn't appear in azuracast this correction.
There are some parts of the panel that I couldn't find to translate in the crowndin.

![Screenshot_75](https://user-images.githubusercontent.com/48635610/84580129-807de000-adaa-11ea-9d0a-48b5e2065f8e.png)

**Comment by Marcioghiraldelli** [comment]
![Screenshot_76](https://user-images.githubusercontent.com/48635610/84595887-cc736800-ae30-11ea-99a3-24fd8a33c908.png)

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli I've made some changes to catch some strings that weren't properly included for translation before.

**Comment by Marcioghiraldelli** [comment]
hello I did the translation.

Em dom., 21 de jun. de 2020 às 13:34, SlvrEagle23 <notifications@github.com>
escreveu:
