### ISSUE TITLE
Synchronization Tasks not working. No songs on Upcoming Songs Queue

### ISSUE THREAD

**Issue by hecgua** [AzuraCast/AzuraCast#2958]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.2, #c4e482c (2020-05-25 5:23) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
"Synchronization Tasks" not working automatically. No songs on "Upcoming Songs Queue" list and is not showing the "next song" on the "Station Profile" page.

**To Reproduce**
If I click run on any of the manual "Synchronization Tasks", the next page shows: Setup not complete; halting synchronized task.
If I run a manual synchronization task for one station it works fine, the "Upcoming Song Queue" list shows the number of songs determined on the "Advanced AutoDJ Queue Length" but no more new songs will be added to the queue list.
I have tried changing the config options on the "System Settings" page without success.

**Expected behavior**
Synchronization Tasks  and "Upcoming Song Queue" list works properly

**Relevant Logs**
Part of the Liquidsoap log
2020/06/14 02:34:47 [lang:3] AzuraCast Raw Response: 
2020/06/14 02:34:47 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/06/14 02:34:49 [lang:3] AzuraCast Raw Response: 
2020/06/14 02:34:49 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/06/14 02:34:52 [lang:3] AzuraCast Raw Response: 
2020/06/14 02:34:52 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/06/14 02:34:54 [lang:3] AzuraCast Raw Response: 
2020/06/14 02:34:54 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/06/14 02:34:56 [lang:3] AzuraCast Raw Response: 
2020/06/14 02:34:56 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/06/14 02:34:58 [lang:3] AzuraCast Raw Response: 
2020/06/14 02:34:58 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/06/14 02:35:00 [lang:3] AzuraCast Raw Response: 
2020/06/14 02:35:00 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/06/14 02:35:02 [lang:3] AzuraCast Raw Response: 
2020/06/14 02:35:02 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/06/14 02:35:04 [lang:3] AzuraCast Raw Response: 
2020/06/14 02:35:04 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/06/14 02:35:06 [lang:3] AzuraCast Raw Response: 
2020/06/14 02:35:06 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/06/14 02:35:08 [lang:3] AzuraCast Raw Response: 
2020/06/14 02:35:08 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/06/14 02:35:10 [lang:3] AzuraCast Raw Response: 
2020/06/14 02:35:10 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/06/14 02:35:12 [lang:3] AzuraCast Raw Response: 
2020/06/14 02:35:12 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/06/14 02:35:15 [lang:3] AzuraCast Raw Response: 
2020/06/14 02:35:15 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/06/14 02:35:17 [lang:3] AzuraCast Raw Response: 
2020/06/14 02:35:17 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/06/14 02:35:19 [lang:3] AzuraCast Raw Response: 
2020/06/14 02:35:19 [lang:3] AzuraCast Error: Delaying subsequent requests...
2020/06/14 02:35:21 [lang:3] AzuraCast Raw Response: 
2020/06/14 02:35:21 [lang:3] AzuraCast Error: Delaying subsequent requests...

**Screenshots**
![Screenshot_7](https://user-images.githubusercontent.com/58102945/84588459-3bc76880-aded-11ea-836a-3c2922bfe8a0.png)

![Screenshot_8](https://user-images.githubusercontent.com/58102945/84588464-3ec25900-aded-11ea-8aa1-36cbf446b2e0.png)

![Screenshot_9](https://user-images.githubusercontent.com/58102945/84588567-23a41900-adee-11ea-9045-31d4587aebbe.png)

**Device(s):**
Desktop 
W10
Chrome
Version: 22

**Additional context**
When I run a manual Synchronization Tasks for one station, the next page shows a Debug message that saids: "Current queue cleared" like if the station have pending requests even that the songs request on the profile of the stations is not enabled. I think this is related with the attached images where the log shows a error message saying: Delaying subsequent requests.
This instance of Azuracast is new and was installed on June 11 and updated minutes ago. This issue was present since the first start of this new installation, I thought that this issue could be solved with an update but no.
I chose stable versions on the new install.

**Comment by hecgua** [comment]
I just realized that the IDs and Promos of the stations are not being played. There are no problems with the files, folders or with the playlist configs, everything is ok with it. 

Any help?

**Comment by hecgua** [comment]
How can I disable stable versions while updating? I mean, want to update to the newest version to see if a new version fix the issue. 

About the issue posted here, do you need more info to see what's happening?

**Comment by SlvrEagle23** [comment]
@hecgua You can run:
```bash
./docker.sh setup-release
```

to change the release versions, then update again to use the latest version after switching.

**Comment by hecgua** [comment]
thank you @SlvrEagle23

**Comment by hecgua** [comment]
@SlvrEagle23 

I just updated to the newest version and the reported issue has not been fixed. The update process didn't show any error.

Any help with this bug will be much appreciated.

**Comment by SlvrEagle23** [comment]
@hecgua It appears you skipped saving your settings page when doing the initial setup. Visit `your-domain.com/setup` and it should redirect you through the remaining setup process; once this is complete, tasks should run normally.

**Comment by hecgua** [comment]
@SlvrEagle23 It worked! Thanks a lot!

One last question: The your-domain.com/setup page and the your-domain.com/admin/settings page are not the same settings page? They look the same. I tried several setup combinations in the /admin/settings page and they never worked.

**Comment by SlvrEagle23** [comment]
@hecgua They are indeed the same form and are rendered using much of the same code, but one is part of the initial setup process and thus sets a flag in the system that the setup was completed successfully, thus allowing synchronized tasks and other internal processes to run without issue.

I've added an additional safety check to the application so that if you log in while setup is still incomplete, it will immediately direct you back into the setup process to complete it, which should cut down significantly on this type of error going unnoticed.
