### ISSUE TITLE
Edit Media Metadata Error

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#296]
Small problem in editing (ex: Custom Cues: Cue-In Point (seconds))
![media](https://user-images.githubusercontent.com/379099/33256701-7cf86bf0-d353-11e7-86dc-2bdbc2214b6f.png)

**Comment by SlvrEagle23** [comment]
@ckeurk Please update to the latest version of the codebase and try this again. This issue was likely related to #283, which has involved some database changes to resolve the issue.

**Comment by ckeurk** [comment]
👍
