### ISSUE TITLE
SSL ansible installation and domain

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#2960]
Hello,

To add SSL on ansible installation Ubuntu 18.04, i must do anything on domain panel?

Thank you

**Comment by ogrenci01** [comment]
Hi;

I use Ansible. Follow me for SSL:

1 -) `sudo service nginx stop`

2-)
`sudo wget https://dl.eff.org/certbot-auto -O /usr/sbin/certbot-auto`
`sudo chmod a+x /usr/sbin/certbot-auto`
`sudo certbot-auto certonly --standalone -d yourdomain.com`

3-) You must accept the license terms during installation. You should provide your e-mail address for update information. If you want to be notified, you should say yes finally.

4-) You need to set up the NGNiX configuration file. Edit `00-azuracast` file in `/etc/nginx/sites-available` directory.

`ssl_certificate    /etc/letsencrypt/live/yourdomain.com/fullchain.pem;`
`ssl_certificate_key    /etc/letsencrypt/live/yourdomain.com/privkey.pem;`

and save it.

5-) `sudo service nginx start`

Enjoy :)

**Comment by jonikane** [comment]
ok,

but i must do anyting on domain cpanel side?
like dns setting?

**Comment by NicoxDJ** [comment]
@ogrenci01 it aborting, because it's returning 404 for "http://domainname/.well-known/acme-challenge/BnxDeLj6juVjsygyj2ngTCTh0CBZ8P1WCPj8XU1WpGk". How can i skip checking on .well-known?

**Comment by ogrenci01** [comment]
> ok,
> 
> but i must do anyting on domain cpanel side?
> like dns setting?

You have to point the domain to the Azuracast server IP. You should then follow the above steps. If you have a domain like sub.domain.com, you should do the same with it.

**Comment by ogrenci01** [comment]
> @ogrenci01 it aborting, because it's returning 404 for "http://domainname/.well-known/acme-challenge/BnxDeLj6juVjsygyj2ngTCTh0CBZ8P1WCPj8XU1WpGk". How can i skip checking on .well-known?

If your domain name is announced on another IP, it is normal to get this error. Your Azuracast domain name and IP address must match. Installation of "cert-bot" for Ubuntu has changed in recent days. Is your setup Ansible?

**Comment by NicoxDJ** [comment]
@ogrenci01 Yes, i'm using Ansible. And yes, the subdomain is pointing to the server, but is trying to load .well-known/acme-challenge/BnxDeLj6juVjsygyj2ngTCTh0CBZ8P1WCPj8XU1WpGk which is not existing. Thats why its returning 404. I'm trying another method instead http-01 to use dns-01 challenge. But it still can't read my domain records.
