### ISSUE TITLE
Cannot delete the recorded file in broadcast section

### ISSUE THREAD

**Issue by rexya2017** [AzuraCast/AzuraCast#2961]
hello ...
I get a problem in the broadcast section. if I activate the recording life feature in the auto dj page section, the recording file results cannot be deleted from the broadcast section.
I use centos 7 operating system, and azuracast is installed with a docker.
thank you.

**Comment by SlvrEagle23** [comment]
@rexya2017 If you don't see a "Delete" option, then I'm assuming you also don't see a "Download" option for that entry, right?

If you can't delete or download an entry, it means it wasn't successfully recorded for some reason internally. We'd need to see the Liquidsoap/AzuraCast logs to investigate why, in this case, it didn't record properly.

**Comment by madbeyk** [comment]
Same issue, set is downloadable, but can't be deleted ...

**Comment by SlvrEagle23** [comment]
This should definitely be fixed at this point, as of our latest Filesystem changes.

If you're still experiencing these issues on the latest Rolling Release version, feel free to reopen this issue or make a new one. Thanks!
