### ISSUE TITLE
Strange error after the latest update

### ISSUE THREAD

**Issue by andrewfer000** [AzuraCast/AzuraCast#2962]
I do not know how to describe this problem but it just started after this new update. After trying to restart and rebuild the containers many times I just wiped everything out with the ./docker.sh uninstall command, deleted everything, and then reinstalled using a freshly downloaded docker.sh script and I still get the same error.

Here's the terminal output.

ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
azuracast_mariadb_1 is up-to-date
azuracast_redis_1 is up-to-date
azuracast_influxdb_1 is up-to-date
azuracast_stations is up-to-date
Creating azuracast_web ... 

ERROR: for azuracast_web  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for web  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

This error makes no sense, since its on localhost.

There are no logs this is all I can give

I am running Ubuntu 20.04 LTS for my server and desktop.

**Comment by SlvrEagle23** [comment]
@andrewfer000 You are correct, this error doesn't make any sense, unless the error is with Docker compose trying to pull down the latest images from the Docker hub, but then you wouldn't see those errors when trying to spin up the new images locally. The error might be between Docker Compose and your connection to the Docker daemon on the computer.

I'd check to make sure the docker service is enabled, running, and up to date; a reboot may also help the situation.

**Comment by andrewfer000** [comment]
I run other docker software such as Mailcow Dockerized so I do not think its docker itself but my VPS itself has been a little slow latley so I think its because Azuracast is not starting up in the 60 seconds before docker times out. I will try to increse the timeout and ill get update if anything happens.

**Comment by andrewfer000** [comment]
Also I am getting this

ERROR: for a358b2dd751a_azuracast_web  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web (456e07e3aa6fd1a4e8618b4adb385419cddda7e67572aa0ae78f45f0b8fdb2c8): Error starting userland proxy: listen tcp 0.0.0.0:2022: bind: address already in use

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web (456e07e3aa6fd1a4e8618b4adb385419cddda7e67572aa0ae78f45f0b8fdb2c8): Error starting userland proxy: listen tcp 0.0.0.0:2022: bind: address already in use
ERROR: Encountered errors while bringing up the project.

I have nothing running on port 2022 and even changed it in the setup script and it changed nothing.

**Comment by SlvrEagle23** [comment]
@andrewfer000 See our help section for info on the "bind" error: https://www.azuracast.com/help/docker/#bind-address-already-in-use
