### ISSUE TITLE
cant login after upgrading to latest

### ISSUE THREAD

**Issue by voipworld** [AzuraCast/AzuraCast#2966]
**Using Docker installation method**

yes
**AzuraCast version**

unable to login and see it
**Host Operating System**

Ubuntu 16.04
**Describe the bug**

can't login after using docker.sh upgrade.
error log from the web page:
An exception occurred while executing 'SELECT t0.uid AS uid_1, t0.email AS email_2, t0.auth_password AS auth_password_3, t0.name AS name_4, t0.locale AS locale_5, t0.theme AS theme_6, t0.two_factor_secret AS two_factor_secret_7, t0.created_at AS created_at_8, t0.updated_at AS updated_at_9 FROM users t0 WHERE t0.email = ? LIMIT 1' with params ["tayeb.meftah@gmail.com"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.two_factor_secret' in 'field list'
AbstractMySQLDriver.php : 60
**To Reproduce**

i didnt upgrade for one year maybe, so i am not sure on how to reproduce it, i just did ./docker.sh update
**Expected behavior**

must be able to login to dashboard.
**Relevant Logs**

An exception occurred while executing 'SELECT t0.uid AS uid_1, t0.email AS email_2, t0.auth_password AS auth_password_3, t0.name AS name_4, t0.locale AS locale_5, t0.theme AS theme_6, t0.two_factor_secret AS two_factor_secret_7, t0.created_at AS created_at_8, t0.updated_at AS updated_at_9 FROM users t0 WHERE t0.email = ? LIMIT 1' with params ["tayeb.meftah@gmail.com"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.two_factor_secret' in 'field list'
AbstractMySQLDriver.php : 60
**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 
Windows 10
Google Chrome version 83.0.4103.106
**Additional context**

**Comment by SlvrEagle23** [comment]
@voipworld You hadn't updated for about a year? That's a pretty significant update, but it should actually still go through without any issues.

I would need to know if your update script itself is encountering any errors when it runs. Try running:

```
./docker.sh update-self
./docker.sh update
```

and if you encounter any errors (particularly related to "database migrations") then please paste those here.

**Comment by voipworld** [comment]
hello,
please kindly close this issue at i was fast to reinstall & replan my station
thanks and sory for taking your time ;)
