### ISSUE TITLE
Installation Error cannot connect nginx

### ISSUE THREAD

**Issue by obedr123** [AzuraCast/AzuraCast#2968]
**Using Docker installation method**

**Host Operating System**
 Ubuntu 20.04

When trying to finish installation of Azuracast in my sever, everything runs well except the nginx. Already restarted nginx and set the default ports but still can't finish the installation process. 

This is the error message that is shown. 
<pre>Creating azuracast_nginx_proxy_1 ... 
Creating azuracast_nginx_proxy_1 ... <font color="#CC0000">error</font>

ERROR: for azuracast_nginx_proxy_1  Cannot start service nginx_proxy: driver failed programming external connectivity on endpoint azuracast_nginx_proxy_1 (5bcfe4c9c18f93e71fceec20837e408ae6640b0eeb994dd9ee9116b2f6ae7691): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
</pre>

**Comment by SlvrEagle23** [comment]
@obedr123 This means some other service on your server is running on port 80 already.

To figure out what process that is, you can use something like `netstat -tulpn` to view programs listening across ports currently. You can then disable or uninstall whatever service is causing the conflict.

**Comment by paulsoler** [comment]
uninstaller nginx: https://qastack.mx/ubuntu/235347/what-is-the-best-way-to-uninstall-nginx 
and update docker azuracast
