### ISSUE TITLE
Liquidsoap memory leak?

### ISSUE THREAD

**Issue by stimpy23** [AzuraCast/AzuraCast#2970]
Hi!
First of all: Thank you so very much for this project! I'm writing a similar, yet waaaayyyy less advanced tool for our station since more than 10 years and seeing azuracast makes me wanna stop development on mine and start helping this project, if I even can..

But first, I need some more help from you.. ;)

I'm currently in the process of transferring all mp3s and our schedule to azuracast. Tried it two time already and it's always looking good at first, but then, "all of a sudden", liquidsoap starts leaking memory.

Azuracast is running in a LXC container, Ansible installation on Ubuntu bionic. Normally, said container has 4GB RAM and 2 CPUs, but I tried increasing RAM to up to 32GB and up to 4 CPUs.
Liquidsoap just eats up all the ram it gets, then starts swapping. Up to 2 more gigs. Never more, but it keeps reading/writing these 2 gigs constantly.

I do have a pretty large media library (500Gigs. More than half of it are archive recordings of 1 or 2 hours length, the rest are single tracks.).
In my first try, I just added everything: All the files, all the playlists, all the schedule. Most of the schedule was using Azura for management, some had the special attributes "Play only one track" and "Stop previous track to start on time" (Sorry, I'm translating back from the german version, here.. ;) ) so management was done by liquidsoap itself.
Everything looked fine until I restarted the container, then the leakage began.

I had to completely remove ALL the playlists and schedule to make the leakage stop.

Next time, I didn't use these special attributes, so all the playlists were managed by Azuracast. I also did little steps, rebooting the container every 10 playlists created and waiting for it to bail out. It didn't.
Last step was adding replays from the archive to the schedule, which, at first, also worked just fine, even after rebooting. But then again, "all of a sudden" (I don't think, but am not 100% sure, it corresponds with the cronjobs..) it started leaking memory again.
So I removed the archive playlists again, but it doesn't stop.
Looks, like I have to remove EVERYTHING first, again.

I didn't, yet, instead I tried some more steps: Editing the liquidsoap.liq file to not look for these playlists anymore (it didn't get updated automatically) - nothing. Clearing chache, reprocessing all mediafiles (took all night..) - still nothing.
I have to stop station_1:station_1_backend via supervisorctl for this, otherwise, the container is too ocupied with swapping..

I've attached all log files asked, but trunkated some to a reasonable size. If you need the complete logs (8MB), just tell me... Also included my liquidsoap.liq, renamed to .txt, so github accepts the upload..
The Liquidsoap log stops the moment, the leakage begins. No logs from when leaking. The errors at the end are me trying to delete the liquidsoap.liq config for making azuracast recreate it. It didn't, so I copied it back and removed the archive playlists manually.
Running strace on the liquidsoap process doesn't give me anything, but this, every few minutes:
`mmap(NULL, 737374208, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa6d2da3000`

I do understand, you're not the developer of liquidsoap and maybe can't help, but you're my first try, since you're the developer of the program, I'm actually using.. ;) Maybe, you could at least give me some hints, how to continue my investigation..

Cheers and thanks in advance,
  Philipp

[liquidsoap.log](https://github.com/AzuraCast/AzuraCast/files/4803237/liquidsoap.log)
[php_errors.log](https://github.com/AzuraCast/AzuraCast/files/4803238/php_errors.log)
[redis-server.log](https://github.com/AzuraCast/AzuraCast/files/4803239/redis-server.log)
[supervisord.log](https://github.com/AzuraCast/AzuraCast/files/4803240/supervisord.log)
[access.log](https://github.com/AzuraCast/AzuraCast/files/4803241/access.log)
[app.log](https://github.com/AzuraCast/AzuraCast/files/4803242/app.log)
[error.log](https://github.com/AzuraCast/AzuraCast/files/4803243/error.log)
[icecast.log](https://github.com/AzuraCast/AzuraCast/files/4803244/icecast.log)
[liquidsoap.txt](https://github.com/AzuraCast/AzuraCast/files/4803246/liquidsoap.txt)

**Comment by SlvrEagle23** [comment]
@stimpy23 Unfortunately, I don't develop or have anything to do with the development of Liquidsoap. It's just another dependency that our software integrates together into a web radio management suite.

If there is a memory leak issue with it, I would encourage you to submit your generated Liquidsoap configuration (along with any errors) to the Liquidsoap team directly through their repository: https://github.com/savonet/liquidsoap/issues

**Comment by arusi01** [comment]
https://github.com/AzuraCast/AzuraCast/issues/2811

**Comment by arusi01** [comment]
The fix has been identified here: savonet/liquidsoap#1272 as an exponential increase in the list of sub-clocks associated with a given unknown clock.

**Comment by SlvrEagle23** [comment]
@stimpy23 AzuraCast has finished building an updated stations image with this update pulled from the 1.4.3 development branch of Liquidsoap. You can now update your installations to take advantage of the updated code.

**Comment by stimpy23** [comment]
Thanks again..! I'm kinda afraid to say, I'm using the NOT OFFICIALLY SUPPORTED ansible installation method, not docker..
Is this supposed to work with this, too, already? I've tried running update.sh with and without the "--full" option, but after both, my problem remains and liquidsoap --version still says, it's v1.4.2..
Even though, it's not officially supported anymore, maybe you could tell me if it's supposed to work already (and I'm doing something wrong..) or if I need to wait for an update of update.sh? ;)

**Comment by SlvrEagle23** [comment]
@stimpy23 Unfortunately, for Ansible you'll have to wait until they tag a new full release version, since we use OPAM directly on the Ansible installation. It's only through our Docker build process that we are able to pull and "pin" specific versions (i.e. the one that fixes the memory leak issue). Once 1.4.3 is released, we'll update the Ansible installation as well.

**Comment by stimpy23** [comment]
Thanks for the answer - that's no problem, I'll wait..
