### ISSUE TITLE
Name during external playlist with Direct Stream URL

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#2971]
Hello! There is something wrong with the external playlist when using "Direct Stream URL". For current song is displaying "Unknown". I don't know what is trying to get to display, but can you change it to show the playlist name instead Unknown. Like if you connecting to another station just for the news, it can display "NEWS" for current song.

**Comment by pawelzet** [comment]
Hello, it is a good question. I have a python script which is downloading newest podcasts from rss feed and saves them into .m3 or .pls playlist with artist and title. When playing it in Azuracast this fields (tags) are empty - in the next playing songs I can only see url of .mp3 file which is saved in .pls playlist. Is it a known workaround for that or a possibility to hardcode Artist and title for romote URL playlists? 
![image](https://user-images.githubusercontent.com/46452256/227316604-d0d7e908-b97b-4a2b-9bf1-65fef63309e3.png)
