### ISSUE TITLE
Wrong Play Next songs.

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#2972]
Hello! There is a bug with the now_playing and playing_next with the API, when you set Advanced AutoDJ Queue Length in AutoDJ over 1 (i set it as 3). I expected the 3 songs will came to the API, and i can see the next 3 songs, but instead of that there is only one in playing_next, and it was like randomly showed. So its 3 songs in the queue, but you see only one, and it might not be actually the next one. Like its wrong ORDER BY. It's not happening all the time, but its very common. And its happening to the "On the Air" box in the dashboard too.
PS: Actually this is happen with Queue Length 1 too: https://imgur.com/a/qrWAGK8 (3 Photos)

**Comment by SlvrEagle23** [comment]
@NicoxDJ Do you have any playlists that use advanced features? If a playlist is controlled by Liquidsoap directly, then AzuraCast can't tell that it will be about to play and it will mess with the "Playing Next" feature.

**Comment by NicoxDJ** [comment]
Yes, i've got one that is connecting to another stream.
Ive checked: `Interrupt other songs to play at scheduled time` and `Merge playlist to play as a single track`
but it's disabled till the fix with the Playing now name. And sometimes i'm seeing this: https://imgur.com/a/AZU9HNI

**Comment by SlvrEagle23** [comment]
@NicoxDJ Any advanced settings will interrupt the "Playing Next" functionality from working normally, because those playlists are controlled by the Liquidsoap AutoDJ and not the AzuraCast AutoDJ. It's part of the reason we now hide that functionality for new users, because of the high likelihood of confusion. There is currently nothing we can do to resolve this situation due to the fundamental technical differences between the two.

**Comment by NicoxDJ** [comment]
OK, i will disable these two advanced settings (even the playlist is already disabled), and restart the server. I will observe few hours, and post again the results.

**Comment by NicoxDJ** [comment]
Nope. Still like that. And its completely random. After server restart its working fine. Than after 10 songs, it became buggy (as i explained above). i.e. you're not seeing the play next song, you're seeing the play next after next song. Than only one song is left in the queue: https://imgur.com/a/C55VuN3 and the play next is empty. After that, the playlist restart and its back to correctly working mode. The next cycle was like 3-4 songs working normally and than start displaying wrong info. Its completely random.

**Comment by SlvrEagle23** [comment]
@NicoxDJ Really not sure what's going on there. The queue should be filling itself back up every 15 seconds if it notices it's running low on tracks.

**Comment by NicoxDJ** [comment]
@SlvrEagle23 Well, i din't want to give url, but you can see it here:
http://stream.club-bg.org:85/api/nowplaying/1 (please after you see it, delete the url from the comment)
You can see the queue is always only 1 track. And sometimes is not the real one.
