### ISSUE TITLE
Problems.

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#2974]
Today I was trying to put the communication chat tawk.to on the azuracast panel and I couldn't. I put the code in main.phtml and the code does not execute. I have an online radio and with local problems the people who are part are far away and the way I found to communicate with the announcer was this chat. so that does not work can someone help me?

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli We don't officially support modifying our internal HTML templates to add external functionality to them, as there are a huge number of possible problems that could be causing your issue and we are not a large enough team to provide support for every possible scenario.

Perhaps it would be better to build a small static page that includes both the radio player and your custom components but is hosted independently from AzuraCast itself.

**Comment by Marcioghiraldelli** [comment]
@SlvrEagle23  I understand now.
In fact I just wanted to put this chat to communicate with my speakers who are many. It would help me. I put the chat script and it doesn't work. blocks.

**Comment by Marcioghiraldelli** [comment]
it simply blocks the external script that would be the tawk chat. It is a common chat I wanted to communicate with my DJs when they were live. Is it just a link in .js if I host directly in the azuracast directory and link as local file can solve?
