### ISSUE TITLE
Incorrect URL for YP Listing

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#2976]
I use the following code to list my stations on YP directories:

{
  "directory": [
    { "yp-url-timeout": 25, "yp-url": "http://icecast-yp.internet-radio.com" },
    { "yp-url-timeout": 25, "yp-url": "http://dir.xiph.org/cgi-bin/yp-cgi" }
  ]
}

My stream URL is https://radio.station.com/radio/8000/radio.mp3 but it gets listed on the directory as https://radio.station.com:8000/radio.mp3 which can't be played.
It happens on both icecast-yp.internet-radio.com and dir.xiph.org so it means that Icecast sends incorrect URL.

**Comment by stardevelop** [comment]
@SlvrEagle23 
Could you please fix this bug?

**Comment by SkeletorMonkey** [comment]
@stardevelop I found a workaround for this issue.  It might work for you too.

Edit Profile -> Broadcasting -> Advanced Custom Configuration

Add to the top:
`<hostname>0.0.0.0</hostname>`

Replace **0.0.0.0** with your server IP address.

It would be nice to use the DNS name and SSL but it does not work when the :port is added.  Seems OK when bypass DNS and use the IP:port
