### ISSUE TITLE
500 error Can anyone help?

### ISSUE THREAD

**Issue by maikocosta** [AzuraCast/AzuraCast#2979]
Server updated to version 10.03, I did procedure #2855 but the 500 error on the access panel continues. I ask for help.

**Comment by maikocosta** [comment]
![Screenshot_20200622-215324~2](https://user-images.githubusercontent.com/52087033/85352544-9e4ef180-b4dc-11ea-9d27-8d1b8777efa7.png)

**Comment by maikocosta** [comment]
![Screenshot_20200622-215324~3](https://user-images.githubusercontent.com/52087033/85352678-e0783300-b4dc-11ea-9769-da9ab627b001.png)

**Comment by maikocosta** [comment]
Can anyone help?

Running the coma I have these errors and alerts

docker-compose logs -f web

web_1                      | [2020-06-23T15:54:17.242826+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":1,"name":"xxxxxxx"}}
web_1                      | [2020-06-23T15:54:17.771122+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":2,"name":"xxxxxxx"}}
web_1                      | [2020-06-23T15:54:19.135254+00:00] AzuraCast.ERROR: NowPlaying adapter error: Request returned status 400: <b>mount does not exist</b>  [] {"station":{"id":4,"name":"xxxxxxx"}}


docker-compose logs -f nginx_proxy


nginx_proxy_1              | nginx.1    | 2020/06/23 15:58:13 [alert] 133#133: 1024 worker_connections are not enough
nginx_proxy_1              | nginx.1    | 2020/06/23 15:58:13 [alert] 133#133: 1024 worker_connections are not enough
nginx_proxy_1              | nginx.1    | 2020/06/23 15:58:13 [alert] 133#133: 1024 worker_connections are not enough
nginx_proxy_1              | nginx.1    | 2020/06/23 15:58:13 [alert] 133#133: 1024 worker_connections are not enough
nginx_proxy_1              | nginx.1    | 2020/06/23 15:58:13 [alert] 133#133: 1024 worker_connections are not enough
nginx_proxy_1              | nginx.1    | 2020/06/23 15:58:13 [alert] 133#133: 1024 worker_connections are not enough
nginx_proxy_1              | nginx.1    | 2020/06/23 15:58:13 [alert] 133#133: 1024 worker_connections are not enough
nginx_proxy_1              | nginx.1    | 2020/06/23 15:58:13 [alert] 133#133: 1024 worker_connections are not enough
nginx_proxy_1              | nginx.1    | 2020/06/23 15:58:13 [alert] 133#133: 1024 worker_connections are not enough
nginx_proxy_1              | nginx.1    | 2020/06/23 15:58:13 [alert] 133#133: 1024 worker_connections are not enough

**Comment by SlvrEagle23** [comment]
@maikocosta I'm really not sure what's going on in your case, though it seems you're being hit with a ton of web traffic possibly.

The "mount does not exist" error is not an error in the code but rather it's stating exactly the problem it is observing: that the mount point you specified doesn't exist, which means your URL may be out of date or the mount point may have been deleted.

**Comment by maikocosta** [comment]
Thank you very much for the fantastic work with AzuraCast.
I was not successful in solving the problem, my solution was to reinstall Centos 7 and AzuraCast from scratch on my dedicated server.
Now everything seems to be working.
