### ISSUE TITLE
Matadata on iTunes

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#298]
Hi SlvrEagle23,
My radio is on iTunes, unlike other radio stations, Azuracast doesn't show the title and artist.

My Radio (AzuraCast)
![itunes](https://user-images.githubusercontent.com/379099/33359778-0725cdf8-d4d1-11e7-8330-5971e83399de.png)
Other radio on iTunes
![other](https://user-images.githubusercontent.com/379099/33359798-21a7ab42-d4d1-11e7-9a19-04380aff3312.png)

**Comment by SlvrEagle23** [comment]
@ckeurk Were you able to resolve this issue?

**Comment by ckeurk** [comment]
Hello, Neece,
No, not at all.
I don't understand, if I go through this SHOUTtcast address:
http://listen.shoutcast.com/radiodeepunderground--
Information circulates correctly

On the other hand nothing goes through this address (for iTunes)
http://217.182.128.137:8000/rdu.mp3

So I closed down because I don't know if I'm the one who's screwing up or iTunes.
