### ISSUE TITLE
The player stops continuously, and the browser console shows the same error repeatedly

### ISSUE THREAD

**Issue by nielmurillo7** [AzuraCast/AzuraCast#2980]
First of all, I want to thank you for all the work and contribution you make in each of your projects.
God bless you.

**Using Docker installation method**

**AzuraCast version**

**Describe the bug**
While the radio is playing, after a few minutes it stops, and apparently delays broadcasting on that device.
In addition, when checking the browser console, an error occurs almost every 30 seconds, the error is the same evrytime, and appears recurrently. (you can check it in my radio station: http://radio.ensupunto.org)

**To Reproduce**
The error is occuring all the time while the radio is playing. 

**Expected behavior**
The radio player It's not supposed to stop continiously

**Relevant Logs**
radio_player-f88abea4e8.js:1 Error: Network Error
    at t.exports (radio_player-f88abea4e8.js:1)
    at XMLHttpRequest.o.onerror (radio_player-f88abea4e8.js:1)
checkNowPlaying @ radio_player-f88abea4e8.js:1
setTimeout (async)
(anonymous) @ radio_player-f88abea4e8.js:1
radio_player-f88abea4e8.js:1
GET https://radio.ensupunto.org/api/nowplaying/1 net::ERR_TOO_MANY_REDIRECTS

**Screenshots**

![image](https://user-images.githubusercontent.com/67110360/85357601-ab211480-b4df-11ea-94bf-e45088d7c2a1.png)

![image](https://user-images.githubusercontent.com/67110360/85357631-bc6a2100-b4df-11ea-9103-06a5cfeadc65.png)

![image](https://user-images.githubusercontent.com/67110360/85357685-df94d080-b4df-11ea-9168-ce8482e5acd9.png)

**Device(s):**
 - Device: Mobile Devices (every mobile device we use to hear the radio station)

**Comment by SlvrEagle23** [comment]
@nielmurillo7 You're also getting an "error: too many redirects" message that suggests that there's something misconfigured with your AzuraCast installation, either via something in front of it (i.e. a reverse proxy or Cloudflare) configured to redirect, or the base URL is misconfigured inside the application itself. You may want to check that, as it could be causing some trouble in general.

**Comment by nielmurillo7** [comment]
> @nielmurillo7 You're also getting an "error: too many redirects" message that suggests that there's something misconfigured with your AzuraCast installation, either via something in front of it (i.e. a reverse proxy or Cloudflare) configured to redirect, or the base URL is misconfigured inside the application itself. You may want to check that, as it could be causing some trouble in general.

@SlvrEagle23 I checked Cloudflare settings and realized I had changed my DNS from Cloudflare to Google's. I removed the domain from Cloudflare and I'm just using Google DNS now. It work's fine!
Thanks for answering, I'm so thankful for all the contribution.
God bless you.
