### ISSUE TITLE
Icecast M3U and XSPF File Error (404)

### ISSUE THREAD

**Issue by BeyondChrispy** [AzuraCast/AzuraCast#2981]
**v0.10.3, #2093d49 (2020-06-22 4:36) • Docker • PHP 7.4**

When going to a station's Icecast Status or Admin page (e.g. 'https://domain.name/radio/8000') I can see all the relevant stats, but if I click on the 'M3U' or 'XSPF' links for each mount point I get a '404 Not Found' error from AzuraCast (URL the links point to are 'https://domain.name/mountpoint.m3u').

If I manually try 'https://domain.name/radio/8000/mountpoint.m3u' it downloads an M3U file, but with 'http://localhost:8000/mountpoint?' in the file.

Have I configured something incorrectly here?

**Comment by SlvrEagle23** [comment]
@BeyondChrispy This is a known issue, and is due to how Icecast generates that status page; there's nothing we can do about it from our end since it isn't compatible with how our web proxy works.

We do, however, offer direct M3U/PLS playlist downloads inside AzuraCast itself that have the correct URLs listed; you can find these on your station profile under the list of streams.

**Comment by twit-russell** [comment]
The nginx web proxy should be able to handle doing a redirect from the specific mount point m3u extension under the /radio/8000 path to the azuracast served valid m3u file with the right regex in the rewrite statement though, right?  It would be really nice to have this fixed 👍

**Comment by BeyondChrispy** [comment]
Can this be reopened?  It would make some things a lot easier from our end if this could be fixed.

**Comment by BeyondChrispy** [comment]
> 
> 
> @BeyondChrispy This is a known issue, and is due to how Icecast generates that status page; there's nothing we can do about it from our end since it isn't compatible with how our web proxy works.
> 
> We do, however, offer direct M3U/PLS playlist downloads inside AzuraCast itself that have the correct URLs listed; you can find these on your station profile under the list of streams.

The issue is that I need a direct link to an m3u or pls playlist for certain tasks like creating an Alexa skill.  I have currently worked around this by creating dummy '*.mp3' mount points that failover to our actual mount points.  The Alexa skill needs either a '.m3u' or '.pls' link or a stream URL with the format on the end ('.mp3' for instance).  We keep our mount points ambiguous ('/low', '/med', '/high') in case we ever change the format of the stream.

**Comment by SlvrEagle23** [comment]
@BeyondChrispy We can reopen this issue, but as I had mentioned this is an upstream issue with Icecast itself, so if there is an upstream fix in the Icecast-KH branch that allows their software to generate URL-dependent M3U playlists, then we can incorporate that into our code.

In the meantime, does our playlist generation (that creates the M3U/PLS files with the correct URLs added) not work correctly for your purposes?

**Comment by BeyondChrispy** [comment]
@SlvrEagle23 The playlist generation works when you need to download a playlist file to open in a player but there is no actual URL ending with '.m3u' that I can use (a hosted m3u or pls file if you will).

**Comment by SlvrEagle23** [comment]
@BeyondChrispy That's something we can rather easily fix. In the latest version, I've switched the URL routing so the path for downloading playlist M3U or PLS files looks like:

```
https://azuracast.url/public/{station_id}/playlist.m3u
https://azuracast.url/public/{station_id}/playlist.pls
```

...so the extension in the URL matches the resulting file format.

**Comment by BeyondChrispy** [comment]
@SlvrEagle23 Well that's just superb! Thanks!
