### ISSUE TITLE
Azuracast Auto DJ (Liquidsoap) Repeating artist Problem

### ISSUE THREAD

**Issue by NightDJ** [AzuraCast/AzuraCast#2982]
I know this problem has been brought up a lot, I have searched and searched for a answer but am unsuccessful finding a answer. Also If I am posting this in the wrong place let me know as this is my first post ever on github.

The auto DJ, Liquidsoap keeps repeating the same artist multiple times an hour and I need to fix that as of licencing issues. Any Suggestions?

One of my ideas was to upload every artist to it's own folder (playlist) and get the playlist rules to play  once an hour. The only problem with that is it will be super time consuming and I really don't want to do that.

Let me know. Thanks

**Comment by SlvrEagle23** [comment]
@NightDJ Make sure all of your playlists have the "avoid duplicates" setting checked and aren't using any advanced settings (from the "Advanced" tab, if you can see it on your installation). While our system will aggressively avoid artists where it can, if there's no way for it to play an upcoming song _without_ duplicating the artist then it will do so. There also may be issues with artist strings being slightly different, though we do filter for artists separated by commas and other strings.

**Comment by NightDJ** [comment]
@SlvrEagle23 where is the "avoid duplicates" tick box? sorry for the dumb question.

**Comment by SlvrEagle23** [comment]
@NightDJ It should be visible on the main panel of the playlist edit dialog box.
![2020-06-24 12_40_49-(Development) Playlists - AzuraCast](https://user-images.githubusercontent.com/6744885/85605697-06562280-b618-11ea-8526-382b59e7a166.png)

**Comment by NightDJ** [comment]
I don't have that setting @SlvrEagle23. Is that because my playlist is to small? it has 237 songs. Also hi I reconize you. I am DJ Eclips formerly at SR.

**Comment by SlvrEagle23** [comment]
@NightDJ Hello! :)

What version of AzuraCast are you on? That setting is reasonably new but not _super_ new.

**Comment by NightDJ** [comment]
v0.10.2

**Comment by SlvrEagle23** [comment]
@NightDJ You should update; version 0.10.3 was released earlier this week and we continue to make updates even after that release.

**Comment by NightDJ** [comment]
I am very sorry for asking such stupid questions as I am very new. How do I update my sever?

**Comment by SlvrEagle23** [comment]
@NightDJ https://www.azuracast.com/administration/system/updating.html

**Comment by NightDJ** [comment]
Thanks @SlvrEagle23  how do I run that command prompt thing? I am the manager and did not set up the sever, Do I have to install something on my pc?

**Comment by NightDJ** [comment]
Never Mind I am fixing I figured it out sorr @SlvrEagle23

**Comment by NightDJ** [comment]
Ok, I got it updated. Now I have made sure that the "avoid duplicate" box is checked. I s there anything else I can do to ensure that it dose not duplicate artists @SlvrEagle23 P.S sorry for being a noob.

**Comment by NightDJ** [comment]
Sorry again to bother you @SlvrEagle23  It is still playing duplicates
![Annotation 2020-06-24 145140](https://user-images.githubusercontent.com/67376369/85615461-42927e80-b62a-11ea-8768-973bf485436a.png)

**Comment by SlvrEagle23** [comment]
@NightDJ Currently we don't separate by ampersands in artist names, so it doesn't consider those the same artist. This could possibly use some additional work on our end, I will look into it.

**Comment by NightDJ** [comment]
Thank you

**Comment by SlvrEagle23** [comment]
@NightDJ I've published an update to the code that will expand the strings that we use to separate artist names, so the ampersand (along with "feat", another common separator) will be detected and split. If you run the update process again it should update to this version of the code.

**Comment by NightDJ** [comment]
Thanks

**Comment by NightDJ** [comment]
SO after a few weeks of monitoring after turning on the setting you recommended @SlvrEagle23 the auto DJ is still repeating some artists.

**Comment by SlvrEagle23** [comment]
@NightDJ There isn't anything we can do about this without a lot more information, particularly logs from the "Rebuild Queue" functionality in the System Debugger page.

**Comment by NightDJ** [comment]
v0.10.3

**Comment by SlvrEagle23** [comment]
@NightDJ That is the latest stable version, yes. Newer versions will still say 0.10.3 in the footer, but will have "Rolling" after the version number (to indicate that they're rolling-release development branch updates).
