### ISSUE TITLE
Error setup

### ISSUE THREAD

**Issue by RazielSama** [AzuraCast/AzuraCast#2984]
**Using Docker installation method** Yes

**AzuraCast version** lastest (fresh install)

**Host Operating System** Debian 10

**Describe the bug**

I just finished install. I go on the web page to set up admin account and i get this error: 

`500
An exception occurred while executing 'INSERT INTO audit_log (timestamp, operation, class, identifier, target_class, target, changes, user) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [1593025509, 1, "Role", "Super administrateur", null, null, "a:1:{s:4:\"name\";a:2:{i:0;N;i:1;s:20:\"Super administrateur\";}}", null]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.audit_log' doesn't exist
AbstractMySQLDriver.php : 42`

I just noticed during install there war an error message: 

> Pulling mariadb                 ... done
> Pulling influxdb                ... done
> Pulling redis                   ... done
> Pulling stations                ... done
> Pulling web                     ... done
> Pulling nginx_proxy             ... done
> Pulling nginx_proxy_letsencrypt ... done
> Creating network "azuracast_backend" with driver "bridge"
> Creating network "azuracast_frontend" with driver "bridge"
> Creating volume "azuracast_nginx_proxy_vhosts" with default driver
> Creating volume "azuracast_db_data" with default driver
> Creating volume "azuracast_influx_data" with default driver
> Creating volume "azuracast_letsencrypt" with default driver
> Creating volume "azuracast_letsencrypt_html" with default driver
> Creating volume "azuracast_shoutcast2_install" with default driver
> Creating volume "azuracast_geolite_install" with default driver
> Creating volume "azuracast_sftpgo_data" with default driver
> Creating volume "azuracast_station_data" with default driver
> Creating volume "azuracast_tmp_data" with default driver
> Creating volume "azuracast_redis_data" with default driver
> Creating volume "azuracast_backups" with default driver
> Creating azuracast_influxdb_1 ... done
> Creating azuracast_stations   ... done
> Creating azuracast_mariadb_1  ... done
> Creating azuracast_redis_1    ... done
> 2020/06/24 18:37:40 Waiting for: tcp://mariadb:3306
> 2020/06/24 18:37:40 Waiting for: tcp://influxdb:8086
> 2020/06/24 18:37:40 Waiting for: tcp://redis:6379
> 2020/06/24 18:37:40 Connected to tcp://redis:6379
> 2020/06/24 18:37:40 Problem with dial: dial tcp 172.18.0.4:3306: connect: connec                                                                                                                                                             tion refused. Sleeping 1s
> 2020/06/24 18:37:40 Connected to tcp://influxdb:8086
> 2020/06/24 18:37:41 Problem with dial: dial tcp 172.18.0.4:3306: connect: connec                                                                                                                                                             tion refused. Sleeping 1s
> 2020/06/24 18:37:42 Problem with dial: dial tcp 172.18.0.4:3306: connect: connec                                                                                                                                                             tion refused. Sleeping 1s
> 2020/06/24 18:38:20 Timeout after 40s waiting on dependencies to become availabl                                                                                                                                                             e: [tcp://mariadb:3306 tcp://influxdb:8086 tcp://redis:6379]
> azuracast_stations is up-to-date
> azuracast_mariadb_1 is up-to-date
> azuracast_redis_1 is up-to-date
> azuracast_influxdb_1 is up-to-date
> Creating azuracast_web ... done
> Creating azuracast_nginx_proxy_1 ... done
> Creating azuracast_nginx_proxy_letsencrypt_1 ... done
> 

Can anyone help me please ?

**Comment by SlvrEagle23** [comment]
@RazielSama Did your installation have any errors? That error indicates that your database wasn't created correctly.

**Comment by ITC-Media** [comment]
Same error here

**Comment by SlvrEagle23** [comment]
@ITC-Media Same question, then...did your installation have any errors? This error indicates your database wasn't created correctly during the installation process, which would have produced an error message if so.

**Comment by SlvrEagle23** [comment]
@ITC-Media Try running an update (`./docker.sh update`) then...apparently your database didn't get created correctly initially, and if this didn't display an error then that's a pretty notable problem...

**Comment by ITC-Media** [comment]
This was very helpful, thank you! No errors any more!
After I run the Update Process via

./docker.sh update

with full root privilege (sudo su) there was no more errors during install process. Maybe it is a problem with privileges.
