### ISSUE TITLE
Azuracast does not detect live streamer

### ISSUE THREAD

**Issue by Vierii** [AzuraCast/AzuraCast#2985]
Hi!
We regularly have the problem that if a DJ disconnects from the stream and a new streamer immediately connects to the stream, Azuracast does not detect it in the api as in azuracast itself.

So it is not possible to kick the streamer off the stream if necessary.

However, I have no idea if this has already been passed on, or if the problem might be on our side. If its not a problem by our side, can this be fixed please?

Thanks in advance

**Comment by SC2Mitch** [comment]
Hi, in your Station Settings you can edit the `Deactivate Streamer on Disconnect (Seconds)` field to mitigate this issue.

**Comment by Vierii** [comment]
It is currently set to 6 seconds. 
Is this so good? Or should it be set even lower/higher?

**Comment by SC2Mitch** [comment]
6 seconds gives you 6 seconds to reconnect to the DJ software, it should be okay.

**Comment by Vierii** [comment]
Okay great. But it's when the next DJ/streamer goes live and the transition is good without the Auto DJ intervening that he doesn't always detect the streamer. But it is not fixable?
