### ISSUE TITLE
Always Use HTTPS option

### ISSUE THREAD

**Issue by CouinCouin** [AzuraCast/AzuraCast#2986]
Hi, 

Bug or ?  

The Always Use HTTPS  is not checked but http links still redirected to https. 
In some cases of referencing the webradio on somes websites, , we need to keep http url and not https.

Turning ON or OFF this option doesn't change anything.

Version v0.9.9, #835968d (2020-04-25 7:28) on Ubuntu 16.04 Server / VPS OVH. 

Any idea ?  
Thanks :)

**Comment by SlvrEagle23** [comment]
@CouinCouin Is your base URL prefixed with `https`? If so, it will prefer HTTPS URLs, but it won't force them or enforce HTTP strict transport security (HSTS), which are what the "Always Use HTTPS" setting is toggling.

**Comment by CouinCouin** [comment]
Hi Dear, 

If for example I put in my browser : 
http://stream-eurodance90.fr:8000/128.mp3 or stream-eurodance90.fr:8000/128.mp3  it is redirected to https://stream-eurodance90.fr:8000/128.mp3 and I get the error described here : https://github.com/AzuraCast/AzuraCast/issues/2969#issuecomment-649523268

If http://stream-eurodance90.fr/radio/8000/128.mp3 , it is redirected to https://stream-eurodance90.fr/radio/8000/128.mp3 .

Perhaps I miss something ?

**Comment by SlvrEagle23** [comment]
@CouinCouin Did you have "Always Use HTTPS" turned on at some point in the past? It's possible your browser is remembering the HSTS setting and applying it, even though it's not currently being enforced.

**Comment by CouinCouin** [comment]
Hi, I don' remember had turned it ON  , but even, I cleared cookies, cache etc etc of my browsers before opening the thread :)

**Comment by MrSleeps** [comment]
Check the response from this site: https://gf.dev/hsts-test because I can access the http version without it redirecting to https just fine.

**Comment by CouinCouin** [comment]
Hi MrSleeps :) 

For an unkown reason, it's ok since I did this test :)

So, it's finally fine ! 

Thanks for support ! :)

**Comment by pitsch** [comment]
sorry for reopening this, lately tried to do the following as default setting: 
https:// for the administration interface
http:// for streams (reducing overload)
barebone IP:PORT/mountpoint for the links provided by the adminstration interface. (replacing a redundant m3u link)
then putting this together for: 
one plain ascii page with of all relevant links, accounts, live stream info & credentials, "main" sftp and dj account, similar to centovacast. only available to admin roles.
still fiddling to put it into a workable docker-compose override...
