### ISSUE TITLE
Remote URL's return errors: No valid playlist detected

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2987]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.3, #0dea2de

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
If you have a Remote URL on a playlist and it plays accordingly, error logs will still be produced stating no valid playlist. Audio works but AutoDJ still believes it's not a valid playlist. (I'm also unsure why it prints the error 3 times instead of 1? )

**To Reproduce**
Make a playlist, set it to Remote URL, have no other playlists running, check Docker logs

**Expected behavior**
No error messages to be printed in the Docker logs. 

**Relevant Logs**
``` YML
web_1                      | [2020-06-25T17:25:48.027940+00:00] AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... [] {"station":{"id":29,"name":"LAFD Radio Scanner"}}
web_1                      | [2020-06-25T17:25:48.029119+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":29,"name":"LAFD Radio Scanner"}}
web_1                      | [2020-06-25T17:25:48.029518+00:00] AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... [] {"station":{"id":29,"name":"LAFD Radio Scanner"}}
web_1                      | [2020-06-25T17:25:48.029591+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":29,"name":"LAFD Radio Scanner"}}
web_1                      | [2020-06-25T17:25:48.029898+00:00] AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... [] {"station":{"id":29,"name":"LAFD Radio Scanner"}}
web_1                      | [2020-06-25T17:25:48.030015+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":29,"name":"LAFD Radio Scanner"}}
```
**Screenshots**
Error logs
https://puu.sh/G0pb1/3e4e675c95.png
Playlist Settings
https://puu.sh/G0pcm/08badb8a64.png

**Device(s):**
Edge, Windows 10, latest, Desktop.
**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch Remote URL playlists are handled exclusively by the Liquidsoap AutoDJ, so AzuraCast doesn't see them as a valid playlist to play from its own rotation. It's up to Liquidsoap to cue the playlist up and play it properly.

**Comment by aristosv** [comment]
> @SC2Mitch Remote URL playlists are handled exclusively by the Liquidsoap AutoDJ, so AzuraCast doesn't see them as a valid playlist to play from its own rotation. It's up to Liquidsoap to cue the playlist up and play it properly.

Is there a way to configure autodj, so the errors are not produced in the log file?
