### ISSUE TITLE
Shoutcast v1 remote relay connection refused after update

### ISSUE THREAD

**Issue by varrodani** [AzuraCast/AzuraCast#2989]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.3, #85991b7 (2020-06-25 18:44) Rolling • Docker • PHP 7.4

**Host Operating System**
Ubuntu 18.04

**Describe the bug**

I had a previous version of AzuraCast, but I must update because I had a redis error. After that the shoutcast v1 remote relay doesn't connect. In my liquidsoap.log showed these lines:
Connecting mount sid#1 for @XX.XX.XX.XX...
Connection failed: bad answer: invalid password

It's horrible, beacuse the password is correct!

Please tell me, if I need some new settings to connect shoutcast v1 remote relay

Thanks.

**Comment by SlvrEagle23** [comment]
This should now be fixed as of the latest update; we were appending the SID to the password as is standard for SHOUTcast 2, but shouldn't be doing that for SHOUTcast 1, which is now fixed.
