### ISSUE TITLE
{"error":{"code":404,"msg":"File or Directory Not Found"}}

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#299]
How to solve the problem when specifying a directory outside the docker?

**Comment by SlvrEagle23** [comment]
@susl16c If you're using Docker, the paths inside the containers are strictly set, and you should continue to use the existing paths, because these paths correspond to persistent volumes that will be saved even when the Docker containers are turned off.

**Comment by susl16c** [comment]
But how can you specify a path outside the docker? Can symlinks?

**Comment by SlvrEagle23** [comment]
@susl16c Currently, using the Docker installation, all station media and database files are stored inside Docker volumes. You can create your own version of `docker-compose.yml` (in the project root) that points those volumes to other locations if you like.

**Comment by susl16c** [comment]
Can you write me an example how to do this? I'm not a great dock expert.

**Comment by SlvrEagle23** [comment]
@susl16c Using the current `docker-compose.yml` file, it's pretty easy:

 - Inside the `services` section, look for all of the `volumes:` sections, and if you see any item that starts with `db_data:`, replace that with `/your/dbdata/path:` instead. Do the same for `station_data`.

 - At the bottom of the file, in the `volumes:` section that is by itself at the end, remove the line that you replaced with your own local path. For example, if you used a custom path for `station_data`, then remove the line that says `station_data: {}`.

Once you've updated the Docker file, you will need to run `docker-compose down` and `docker-compose up` to update the containers to use the new paths.
