### ISSUE TITLE
nginx_proxy_1 ... error

### ISSUE THREAD

**Issue by sidney65** [AzuraCast/AzuraCast#2990]
**Using Docker installation method**
Yes

**AzuraCast version**
in progress ...

**Host Operating System**
 Ubuntu 18.04.4 LTS

**Describe the bug**

after re installing vps and azuracast , I've got this message : 

Creating azuracast_nginx_proxy_1 ... error

ERROR: for azuracast_nginx_proxy_1  Cannot start service nginx_proxy: driver failed programming external connectivity on endpoint azuracast_nginx_proxy_1 (de9ea9d859d519b05bb320e2f45f5e8fc2e6a07f66244eae785b5c58b44e5205): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

**To Reproduce**
install or update azuracast is the same

**Expected behavior**

please, a solution to run azuracast ...

**Device(s):**
 - Device: pc
 - OS: window 10
 - Browser: opera
 
**Additional context**
I try to Re install Azuracast after a bad parameter of vps firewall ; I do a re install vps with my provider panel and follow instruction for installing azuracast. For info : no firewall activated when i installing it .
when I do the command: netstat -tulpn i've got:

tcp6       0      0 :::80                   :::*                    LISTEN      820/apache2

Please help me . 
Thanks for advance

**Comment by SlvrEagle23** [comment]
@sidney65 This means you have Apache 2 installed on your host computer, and you should either:
 - Modify the port it listens to,
 - Modify the port AzuraCast uses (via `./docker.sh setup-ports`), though this is not recommended, or
 - Uninstall or disable Apache 2 on the host computer (which depends on your host computer, so we can't provide instructions on how to do this universally).

**Comment by sidney65** [comment]
@SlvrEagle23 thanks ! 
I have disable Apache 2 ; reboot vps ; try to re install azuracast and now it's work . 
Hope this post help other...
Thanks for your help and the great job you do on this soft !
Have a good day.
