### ISSUE TITLE
music gets stuck when i reopen the page

### ISSUE THREAD

**Issue by rodmark** [AzuraCast/AzuraCast#2991]
Hello, I installed azura cast and on all radios it works ok, but when I close the tab and reopen it again, the music gets stuck, I think it is from the cache because in the private browser this problem does not occur. How can I solve?

**Comment by SlvrEagle23** [comment]
@rodmark If you're using our players, they very deliberately clear the cache (even going so far as to remove the actual audio element itself) when you pause and resume a radio station, so you'll always be on the live signal and not on a previous version. This is something we've worked on quite a bit. If you could clarify what's going wrong in your scenario, we may be able to help further.
