### ISSUE TITLE
Scheduled playlist did not play

### ISSUE THREAD

**Issue by cpeter1207** [AzuraCast/AzuraCast#2992]
**Using Docker installation method**

yes

**AzuraCast version**

v0.10.3, #9811fbb (2020-06-22 4:38) • Docker • PHP 7.4

**Host Operating System**

Linux (Ubuntu 18.04)

**Describe the bug**

The playlist "Dirk Gently Earth Search and SpaceForce" was scheduled to play between 7:30 PM and 7:53 PM. It didn't play. Instead, a track from the "Scifi OTR" playlist, which is scheduled for 8:00 PM to 8:19 PM played instead.

The schedule view on the "profile" page showed that the "Dirk Gently" playlist was scheduled for the correct time. It has 44 tracks loaded into it, so I'd've expected the first track in the playlist to be played.

The azuracast application log and liquidsoap logs do not show any errors, or any evidence of why this occurred. Are there other logs I should be checking for this?

**Comment by SlvrEagle23** [comment]
@cpeter1207 We have a super-issue for scheduled playlist problems; please contribute to issue #2631 instead.
