### ISSUE TITLE
Issue pulling artwork from API

### ISSUE THREAD

**Issue by biulas** [AzuraCast/AzuraCast#2993]
Hi guys!

I'm not code expert but I do work around on my issues whenever I have a problem.

For the love of my life, I can't understand why the plugin is not pulling the info about the cover art, though the API is with information up to date. I can get the info on the artist and track, but no artwork.

Any suggestions?

Thanks for the amazing plugin.

**Comment by SlvrEagle23** [comment]
@biulas What plugin do you mean? Our API should be properly displaying whatever album art is set for any given song.

**Comment by biulas** [comment]
@SlvrEagle23 thanks for your answer! The website is https://umt.radio. I mean your wordpress plugin Azuracast Playing now. :)

**Comment by biulas** [comment]
https://pasteboard.co/JfkVPoI.jpg -  here my config...

**Comment by SlvrEagle23** [comment]
@biulas That plugin isn't actually developed by us, it's made by a community member. You can find more information at the plugin's homepage: https://wordpress.org/plugins/now-playing-widget-fuer-azuracast-stationen/
