### ISSUE TITLE
ERROR: for azuracast_nginx_proxy_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

### ISSUE THREAD

**Issue by suricloud** [AzuraCast/AzuraCast#2995]
**Using Docker installation method**

Yes
**AzuraCast version**

**Host Operating System**

Ubuntu 20.04
**Describe the bug**

ERROR: for azuracast_nginx_proxy_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
How to fix this ?
**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@suricloud Not sure what's causing this. May need to just try restarting the containers directly:

```bash
cd /var/azuracast
docker-compose down
docker-compose up -d
```
