### ISSUE TITLE
Web DJ Not Start Streaming Does Noting.

### ISSUE THREAD

**Issue by saikiran91** [AzuraCast/AzuraCast#2996]
I have a station where AutoDJ has a playlist of songs and it is live.
I want to interrupt AutoDJ with Web DJ and start playing custom music or my voice in my live station.

1. I went to Streamer/DJ Accounts enabled it and created a streamer account
2. https://www.radio.mywebsite.com/public/radio-h/dj added a few songs in the playlist hit play and hit "START STREAMING" with exact username and password that I created in step one.

Now I expect to listen to the Web DJ songs on my public radio, but I listen to the AudoDJ playlist.
I have enabled SSL by default, is that an issue?

<img width="1363" alt="Screenshot 2020-06-29 at 4 37 27 PM" src="https://user-images.githubusercontent.com/3991577/85997423-1b232380-ba27-11ea-8ef6-add7757e188c.png">

**Comment by DWAMTV** [comment]
Same issue here with a fresh install (but no SSL certificate yet)
It runs locally at the moment for testing in an Ubuntu 16.04 server Virtualbox VM. Everything seems to work but this...

**Comment by SlvrEagle23** [comment]
@DWAMTV If you haven't already, make sure to set up an SSL certificate, since streaming via the Web DJ requires a secure chain of communication between you and the server (and in many cases, browsers won't accept self-signed certificates for this purpose).

**Comment by LordRampantHump** [comment]
Same here, using cloudflare for ssl
