### ISSUE TITLE
Listeners statistics - Audience - I don't understand???

### ISSUE THREAD

**Issue by radiograndparis** [AzuraCast/AzuraCast#2997]
Hello everyone, who could explain to me how the audience statistics are calculated? I see 0.85 listeners / hour ... that doesn't match live listeners. I do not understand???
Thank you very much for your help!

**Comment by ITC-Media** [comment]
Same to me, that statistics graphic makes no sense to me.

**Comment by MrSleeps** [comment]
If my understanding is correct it's the mean listeners, influx is a time series database. Just round up or down accordingly..

**Comment by ITC-Media** [comment]
![Screenshot](https://user-images.githubusercontent.com/13119092/86917095-de40e600-c124-11ea-8234-13459ee71ce8.png)

This Statistics makes no sense to me. Maybe this error is only in the german language, because in Demo Website is correct.

**Comment by CodeSteele** [comment]
This is a duplicate of #2748
