### ISSUE TITLE
Random error 500 nginx_proxy

### ISSUE THREAD

**Issue by morielreitz** [AzuraCast/AzuraCast#3000]
I 
I use Azuracast in the docker version in Ubuntu with Custom Let's Encrypt SSL.

This works, but "error 500 nginx" and "connection refused" are happening randomly.
![WhatsApp Image 2020-06-30 at 10 11 40](https://user-images.githubusercontent.com/66798804/86130253-44d95a80-baba-11ea-816e-7b772c3e0349.jpeg)

**Comment by SlvrEagle23** [comment]
@morielreitz Can you check your application logs via:

```
cd /var/azuracast
docker-compose logs -f web
```

and see if any further information is popping up?

**Comment by morielreitz** [comment]
many errors like:

nginx_proxy_1              | nginx.1    | 2020/06/30 10:49:07 [alert] 113#113: 1024 worker_connections are not enough

**Comment by morielreitz** [comment]
how to increase this limit?

**Comment by SlvrEagle23** [comment]
@morielreitz This limit is set quite high in order to handle rather substantial traffic, and isn't something that can easily be changed without overwriting the entire nginx configuration file.

I'm curious why your nginx instance is so overloaded. Do you have a lot of listeners looking at your station via our embedded public player?

**Comment by morielreitz** [comment]
[atual.zip](https://github.com/AzuraCast/AzuraCast/files/4852271/atual.zip)
Our config files, inside this folder there are "ssl" folder including ssl certif.

**Comment by SlvrEagle23** [comment]
@morielreitz Oh, you're already overriding the nginx config then. You should be able to just add `worker_connections 2048` near the top of `azuracast-nginx.conf` and then restart the web container and that may help.

**Comment by morielreitz** [comment]
"Do you have a lot of listeners looking at your station via our embedded public player?"

Yes. This embedded public player is used within the mobile web browser application.
Example:
https://play.google.com/store/apps/details?id=com.youngarts.Morradium&hl=pt_BR

**Comment by morielreitz** [comment]
"Oh, you're already overriding the nginx config then. You should be able to just add worker_connections 2048 near the top of azuracast-nginx.conf and then restart the web container and that may help."


How do I do this?

I did not find this parameter in the documentation.

**Comment by SlvrEagle23** [comment]
@morielreitz https://nginx.org/en/docs/ngx_core_module.html#worker_connections

**Comment by morielreitz** [comment]
Like this, before server settings?

events {
    worker_connections  2048;
}

 server{
        ....
}

**Comment by morielreitz** [comment]
502 Bad Gateway
after include 

events {
  worker_connections 2048;
}

**Comment by morielreitz** [comment]
Error 502 after include parameter worker_connections, testing in other domain and server too.

![502ngix](https://user-images.githubusercontent.com/66798804/86167196-75d28300-baec-11ea-8330-2565e940d82c.png)

**Comment by morielreitz** [comment]
I'll wait for your answer ...

And I thank you for your attention.

Sorry my english, I'm from Brazil :)

**Comment by morielreitz** [comment]
Error again, 

I haven't managed to increase the nginx settings yet.

nginx_proxy_1              | nginx.1    | 2020/07/01 11:24:31 [alert] 111#111: *38721 1024 worker_connections are not enough while connecting to upstream, client: 179.184.19.184, server: cast.youngtech.radio.br, request: "GET /radio/8270/radio HTTP/1.1", upstream: "http://192.168.80.3:80/radio/8270/radio", host: "cast.youngtech.radio.br"
