### ISSUE TITLE
I can not install my old used subdomains on the new server. (letsecrypt)

### ISSUE THREAD

**Issue by rolradio** [AzuraCast/AzuraCast#3001]
Hello team,
Hello @SlvrEagle23

I moved my azuracast to a larger server and therefore a different IP address

Now I want to use the same subdomain on the new server
The DNS has already been converted and is active
But letsencrypt no longer create the certificates.
I had created 3 subdomains on the old server.

I can no longer install this on the new server.
With the assignment:
./docker.sh update-self
./docker.sh letsencrypt-create

I do not get an error, everything runs normally.
What can I do?

**Using Docker installation method**

Yes

**AzuraCast version**

**Host Operating System**

Ubuntu 18

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by rolradio** [comment]
@SlvrEagle23 ,
Dear Sir,

Is there a solution for this?
Can I copy certain files from the old server to the new one? So that I can use the subdomain again and let letsecrypt secure it again?

Best Regards,
Marc

**Comment by SlvrEagle23** [comment]
@rolradio LetsEncrypt should be automatically setting up; it's possible that DNS hasn't propagated enough to let the LetsEncrypt servers connect to the new address, in which case the certificates should register the next time you restart your services.

You can see if there are specific issues by running `docker-compose logs -f nginx_proxy_letsencrypt` in your AzuraCast host install directory.

**Comment by rolradio** [comment]
@SlvrEagle23 
Thank you.
I have now waited 24 hours and after the update of azuracast the subdomains are working perfectly on the new server.
Everything runs perfectly.
Kind Regards,
Marc
