### ISSUE TITLE
Issue after update - Letsencrypt / HTTPS on docker install

### ISSUE THREAD

**Issue by dadadadaka** [AzuraCast/AzuraCast#3002]
I updated docker to the most recent release today - and now the station works when playing on the azuracast installation (radio.studiokamp.com)
It does however not play when I embed my players on my website: https://www.studiokamp.com/rainforest-radio/

It did before, without problems.

After the update I got a message in chrome that the Letsencrypt certificate (NET::ERR_CERT_INVALID) and I can only login to my station via safari, not chrome.

I then renewed the certificate following these instructions:
https://www.azuracast.com/extending/letsencrypt.html#important-considerations

No error messages, installed fine.

But my embedded players still won't play, and I still can't login to my azuracast install using chrome

Any ideas what is going on?

**Comment by dubloid** [comment]
Hi, dadadadaka!
Wait a day - everything should work. I had a similar case.

**Comment by xewl** [comment]
A good way to check, is opening an Incognito window and trying there.
There's nothing wrong if it works then. Some things behind the scenes are still to be catching up (discrepancies in cache)

**Comment by dadadadaka** [comment]
Thanks - I'll wait another day, right now it still does not work (tried the incognito window)

**Comment by dadadadaka** [comment]
These settings are correct, right?
![Screenshot 2020-07-01 at 23 52 22](https://user-images.githubusercontent.com/66950204/86295035-0648ba80-bbf6-11ea-9a1b-cd69f85400d9.jpg)

**Comment by xewl** [comment]
Looks fine to me. If the Let's Encrypt renewal fails, you could toggle off "Always Use HTTPS"
Though that the newer version works quite a bit better with the separate LE docker image/proxy.

**Comment by dadadadaka** [comment]
Hmmm. seems waiting was not the solution. 
the embeds still do not work here: https://www.studiokamp.com/rainforest-radio/
I tried disabling "Always Use HTTPS" no difference.
Any ideas what I should try so my radios work again?

Thanks a lot!

**Comment by xewl** [comment]
I'd try updating AzuraCast in its entirety 
- https://www.azuracast.com/administration/system/updating.html
then, redo the Let's Encrypt set-up: (as you did before)
- https://www.azuracast.com/extending/letsencrypt.html

**Comment by dadadadaka** [comment]
So strange. did all of that. no difference.
I can't log into my station using https or play any of my mountpoints on my website.
I tried my html with the http version of the stream, and the http version of the stream.
Both work fine when opening the mount point link directly in chrome, but none work when using my audio tag html.

**Comment by xewl** [comment]
> That is the latest, right?
Yeah, you're on par

I dm'd you on le tweeter. This shouldn't be such a pita, so I'm willing to check it out with you.

**Comment by kdizzay** [comment]
I am running into this issue on a fresh install of Ubuntu 18.04, running as per the install instructions as sudo and a single domain and when I access the web URL it shows no certificate and only localhost. I had re-installed, updated, pulled the latest code multiple times. This is not supposed to be this difficult and I have an understanding of Docker but no idea where this is breaking.

**Comment by xewl** [comment]
Hi @kdizzay

please create a fresh issue.
Notably, it would also help to use some of the formatting options so we can make sense of all that text.

**Comment by oliverneedham** [comment]
> Looks fine to me. If the Let's Encrypt renewal fails, you could toggle off "Always Use HTTPS"
> Though that the newer version works quite a bit better with the separate LE docker image/proxy.
> 
> Looking at your URL there, though. It's not secure because it still uses "localhost".
> Doesn't look like it's set up correctly.
> 
> Are you sure you are on the latest version of AzuraCast?

I had this issue with the Let's Encrypt certbot appearing to create a 'localhost' certificate. I'll create a separate issue and mention this one in passing.
