### ISSUE TITLE
ich möchte gerne in player Footer bereich datenschutz und impressum hinzufügen da es in Deutschland Flicht ist

### ISSUE THREAD

**Issue by Radio-Quergedacht** [AzuraCast/AzuraCast#3006]
ich möchte gerne in player Footer bereich datenschutz und impressum hinzufügen da es in Deutschland Flicht ist

**Comment by LordHelmchen666** [comment]
I try to translate.
He wants to be able to put Links in the Footer of the Public Player. He needs to link to Imprint and Privacy because of GDPR law in Germany / Europe.

**Comment by Radio-Quergedacht** [comment]
@LordHelmchen666  Danke

**Comment by ITC-Media** [comment]
Vielleicht hilft dir unter "System Administration" und dann "Benutzerdefiniertes Branding" und dann "Benutzerdefinierte JS für öffentliche Seiten" etwas. Das ist zwar für JavaScript gedacht, aber mit JavaScript kann natürlich auch auf eine HTML-Seite gezeigt werden die dann Informationen und/oder Links zu Datenschutz und Impressum enthält.

**Comment by Radio-Quergedacht** [comment]
@ITC-Media    wie kann ich denn per  JavaScript was anzeigen lassen denn so  <p><a title="test" href="#">test</a></p> geht es leider nicht

**Comment by ITC-Media** [comment]
Beispielsweise so:

`<script type="text/javascript" src="http://www.DEINLINK.de/DEIN-Impressum.html"></script>`

**Comment by Radio-Quergedacht** [comment]
Danke geht wie bekomme ich das ins Footer

**Comment by ITC-Media** [comment]
Da musst du selbst ein bisschen rumexperimentieren. Aber so könnte es geht. Probiert hab ich es nicht. War nur eine Idee ....

**Comment by Vaalyn** [comment]
Here is an example for anyone looking to do something like this. Since the `Custom JS for Public Pages` field is processed via the `strip_tags` function it's not possible to put html directly in that text field (for example `<a href="url">test</a>` will end up as just `test`).

```
$(document).ready(function() {
    /* Create footer HTML elements */
    let newPublicPageFooter = document.createElement('footer');
    let newPublicPageFooterButton1 = document.createElement('a');
    let newPublicPageFooterButton2 = document.createElement('a');

    /* Add ids & classes to new elements */
    newPublicPageFooter.id = 'footer';
    newPublicPageFooterButton1.className = 'btn btn-sm btn-outline';
    newPublicPageFooterButton2.className = 'btn btn-sm btn-outline';
  
    /* Set text of new buttons */
    newPublicPageFooterButton1.text = 'Datenschutzerklärung';
    newPublicPageFooterButton2.text = 'Impressum';
  
    /* Set URL of new buttons */
    newPublicPageFooterButton1.href = 'https://example.com/datenschutz';
    newPublicPageFooterButton2.href = 'https://example.com/impressum';
  
    /* Set new buttons to open in new tab */
    newPublicPageFooterButton1.target = '_blank';
    newPublicPageFooterButton2.target = '_blank';
    
    /* Add button elements to footer element */
    newPublicPageFooter.appendChild(newPublicPageFooterButton1);
    newPublicPageFooter.appendChild(newPublicPageFooterButton2);

    /* Put footer into page */
    $('body.station-STATION_NAME_CLASS .public-page').append($(newPublicPageFooter));
});
```

You need to replace `STATION_NAME_CLASS` with the one from your stations public page body element. Just use your browsers dev tools to look at the body tag to find the correct class.

**Comment by radio-schlauti** [comment]
so far everything goes 
I just want you to be able to see where azuracast comes from 
and unfortunately that doesn't work so well, you can see it here
https://listen.schlauti.media/public/radio_schlautis
