### ISSUE TITLE
Install Error on Ubuntu 20.04 LTS x64

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#3010]
**Using Docker installation method**
No

**AzuraCast version**
Latest

**Host Operating System**
Ubuntu 20.04 LTS x64

**Describe the bug**
Install Error

**Expected behavior**
Setup is not complete. After getting AzuraCast login we get 500 error.

**Relevant Logs**
`fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/console azuracast:setup", "delta": "0:00:00.748462", "end": "2020-07-04 10:04:05.555239", "msg": "non-zero return code", "rc": 1, "start": "2020-07-04 10:04:04.806777", "stderr": " 0/3 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%\n 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%[error] Migration App\\Entity\\Migration\\Version20170803050109 failed during Post-Checks. Error: \"An exception occurred while executing 'SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'':\n\nSQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.\"\n\nIn AbstractMySQLDriver.php line 106:\n                                                                               \n  An exception occurred while executing 'SHOW FULL TABLES WHERE Table_type =   \n  'BASE TABLE'':                                                               \n                                                                               \n  SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unb  \n  uffered queries are active.  Consider using PDOStatement::fetchAll().  Alte  \n  rnatively, if your code is only ever going to run against mysql, you may en  \n  able query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attr  \n  ibute.                                                                       \n                                                                               \n\nIn PDOConnection.php line 83:\n                                                                               \n  SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unb  \n  uffered queries are active.  Consider using PDOStatement::fetchAll().  Alte  \n  rnatively, if your code is only ever going to run against mysql, you may en  \n  able query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attr  \n  ibute.                                                                       \n                                                                               \n\nIn PDOConnection.php line 78:\n                                                                               \n  SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unb  \n  uffered queries are active.  Consider using PDOStatement::fetchAll().  Alte  \n  rnatively, if your code is only ever going to run against mysql, you may en  \n  able query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attr  \n  ibute.                                                                       \n                                                                               \n\nazuracast:setup [--update] [--load-fixtures] [--release]", "stderr_lines": [" 0/3 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%", " 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%[error] Migration App\\Entity\\Migration\\Version20170803050109 failed during Post-Checks. Error: \"An exception occurred while executing 'SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'':", "", "SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.\"", "", "In AbstractMySQLDriver.php line 106:", "                                                                               ", "  An exception occurred while executing 'SHOW FULL TABLES WHERE Table_type =   ", "  'BASE TABLE'':                                                               ", "                                                                               ", "  SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unb  ", "  uffered queries are active.  Consider using PDOStatement::fetchAll().  Alte  ", "  rnatively, if your code is only ever going to run against mysql, you may en  ", "  able query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attr  ", "  ibute.                                                                       ", "                                                                               ", "", "In PDOConnection.php line 83:", "                                                                               ", "  SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unb  ", "  uffered queries are active.  Consider using PDOStatement::fetchAll().  Alte  ", "  rnatively, if your code is only ever going to run against mysql, you may en  ", "  able query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attr  ", "  ibute.                                                                       ", "                                                                               ", "", "In PDOConnection.php line 78:", "                                                                               ", "  SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unb  ", "  uffered queries are active.  Consider using PDOStatement::fetchAll().  Alte  ", "  rnatively, if your code is only ever going to run against mysql, you may en  ", "  able query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attr  ", "  ibute.                                                                       ", "                                                                               ", "", "azuracast:setup [--update] [--load-fixtures] [--release]"], "stdout": "\nAzuraCast Setup\n===============\n\nWelcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...\n * Environment: Production\n * Installation Method: Ansible\n\nWaiting for dependent services to go online...\n\n\nSetting Up InfluxDB\n-------------------\n\nDatabase created.\nRetention policies updated.\nContinuous queries created.\nInfluxDB databases created.\n\nRunning Database Migrations\n---------------------------\n\n[notice] Migrating up to App\\Entity\\Migration\\Version20200604075356", "stdout_lines": ["", "AzuraCast Setup", "===============", "", "Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...", " * Environment: Production", " * Installation Method: Ansible", "", "Waiting for dependent services to go online...", "", "", "Setting Up InfluxDB", "-------------------", "", "Database created.", "Retention policies updated.", "Continuous queries created.", "InfluxDB databases created.", "", "Running Database Migrations", "---------------------------", "", "[notice] Migrating up to App\\Entity\\Migration\\Version20200604075356"]}`

**Screenshots**
![500_error](https://user-images.githubusercontent.com/24523085/86507155-921d3b00-bdde-11ea-90cc-99a392139b8f.jpg)

**Additional context**
Ansible installation will not happen using a clean operating system.

**Comment by lcslex** [comment]
Getting same error on Ubuntu 18.04 LTS and 20.04 LTS, clean install, tried this several times... any solution ?

**Comment by ogrenci01** [comment]
@loics2 ;

You can fix the problem by installing the old version. I opened a record to report a problem.

**Comment by loics2** [comment]
What can I do for you? 

I'm on Ubuntu 18.04 (LTS) too but I used the Docker method, which is more reliable and depends less on your OS. The Ansible method is deprecated, you shouldn't use it.

**Comment by SlvrEagle23** [comment]
@ogrenci01 @lcslex This has been fixed as of the latest commit; this was an unexpected bug in the Doctrine Migrations library, but it has an easy workaround that we've applied.
