### ISSUE TITLE
Disable next song feature

### ISSUE THREAD

**Issue by morielreitz** [AzuraCast/AzuraCast#3012]
I don't use next song feature.
There is a way to disable this feature?

**Comment by SlvrEagle23** [comment]
@morielreitz While it's not possible to disable this one function, it is possible to enable "Manual AutoDJ Mode" (if you have advanced settings turned on) which will no longer display the next playing track.

If you would like to add this feature, you can submit it to our FeatureUpvote site here: https://features.azuracast.com/
