### ISSUE TITLE
Renewing LE certificate

### ISSUE THREAD

**Issue by radiorueda** [AzuraCast/AzuraCast#3013]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.3, #9811fbb (2020-06-22 4:38)

**Host Operating System**

Ubuntu 20.04

**Describe the bug**

I received the aware of letsencrypt renew. From the command line in the folder /var/azuracast I typed
./docker.sh letsencrypt-renew
and the answer was:
./docker.sh: line 625: letsencrypt-renew: command not found

How can I solve it?
Thank you guys.

**Comment by MrSteelMiner** [comment]
That command does not exist. Try `./docker.sh letsencrypt-create`. This should force a renew if it's neccessary

**Comment by radiorueda** [comment]
hi @MrSteelMiner 
ok, i did it, hitting enter twice when prompted

Domain name (example.com) or names (example.com,foo.bar) to use with LetsEncrypt [my.domain.com]: 

Optional e-mail address for expiration updates [my@email.com]: 

which one is the command to check the state of the certificate?

thank you very much

**Comment by MrSteelMiner** [comment]
what do you mean with "state of the certificate"? You mean the "valid until" date? You can see it in your browser by clicking on the lock symbol (I don't know your browser).

**Comment by radiorueda** [comment]
yes, exactly. i did it (firefox) but it seems that wasn't renewed... (will expire in 21st august)... any clue?

**Comment by MrSteelMiner** [comment]
21st august is full in time. So no renew is neccessary. Letsencrypt renews certificates when they need to and nearly 7 weeks are more than enough for a LE certificate (which "lives" just 3 months). 

Mails from LetsEncrypt can safely be ignored if the expire date in the mail does not match the expire date of the certificate itself. So don't worry :)

**Comment by radiorueda** [comment]
ah ok! great. i tried it because of the warning email.
Vielen Dank Kumpel. Bleib sicher!

**Comment by MrSteelMiner** [comment]
No problem :) Stay safe and healthy, too :)

**Comment by MrSteelMiner** [comment]
ah and btw: you can close the issue now.
