### ISSUE TITLE
No Listeners Count on dashboard and no Now Playing Data after updating, it shows Stream Offline

### ISSUE THREAD

**Issue by hecgua** [AzuraCast/AzuraCast#3014]
**Using Docker installation method**
18.04

**AzuraCast version**
v0.10.3, #e104205 (2020-07-06 2:37) Rolling • Docker • PHP 7.4

**Host Operating System**
Windows 10

**Describe the bug**
I just updated Azuracast and Now Playing Data and Listeners Count on Dashboard is not working. The dashboard shows "Stream Offline" on the stations.

**To Reproduce**
This happen after I updated Azuracast.

**Expected behavior**
Now Playing Data and Listeners Count works properly.

**Relevant Logs**
[AzuraCast Application Log 07-06-2020.txt](https://github.com/AzuraCast/AzuraCast/files/4877083/AzuraCast.Application.Log.07-06-2020.txt)

**Screenshots**
This image is when trying to run the " Now Playing Data" on "Synchronization Tasks" on the admin page.
![Screenshot_12](https://user-images.githubusercontent.com/58102945/86562128-c2bcbc00-bf27-11ea-84d6-ced80be70f48.png)

![Screenshot_13](https://user-images.githubusercontent.com/58102945/86562189-de27c700-bf27-11ea-9b97-c0e140e8a494.png)

![Screenshot_14](https://user-images.githubusercontent.com/58102945/86562193-e08a2100-bf27-11ea-9ef6-d6f8f1f02b5c.png)

**Additional context**
No errors found when updating. I don't have any kind of special config on any Azuracast file.

**Comment by bjarn** [comment]
Ah you were quicker than I was :-)

I am experiencing the same issue over here after updating. It is also not possible to manually run the task.

Worth to note; the 1-Hour Sync also shows this error but just for the 'Error updating GeoLite database.' task.

**Comment by SlvrEagle23** [comment]
@bjarn @hecgua This should be fixed as of the latest update.

**Comment by bjarn** [comment]
That was fast, seems alright now! Thanks a lot @SlvrEagle23
