### ISSUE TITLE
Song Request

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#3016]
In the option to request music I configured it for 20 minutes between one request and another, in version 0.10.2 azuracast normally respected this time, preventing from requesting a new request until the configured time was over, in version 0.10.3 this function does not seem to work , you can order multiple times regardless of the waiting time.

**Comment by SlvrEagle23** [comment]
@roger-net Are you testing this via your logged-in administrator account? We added some exemptions in place so that system administrators can submit their requests with no limitations (allowing for them to set up API keys that they control, which can run things like request bots on Discord, etc), but the limitations should still exist for the general public.

**Comment by roger-net** [comment]
No, the final listener is able to request, for example, 10 requests in the same sequence configured to wait 10, 20 or even 30 minutes. In version 0.10.2 this function was working perfectly.

**Comment by LordHelmchen666** [comment]
@SlvrEagle23 
There are wrong (internal) IPs in Request Queue. Maybe this is related to this issue.

> Wunsch Datum | Wiedergabe Datum | Song-Titel | Hörer-IP | Aktionen
> -- | -- | -- | -- | --
> 10. Juli 2020 20:19 | 10. Juli 2020 21:11 | Blinding Lights                         The Weeknd | 172.25.0.4 |  
> 1. Juli 2020 20:19 | 1. Juli 2020 21:16 | Blinding Lights                         The Weeknd | 172.21.0.4 |  
> 22. Juni 2020 21:55 | 22. Juni 2020 22:56 | Spanish Eyes                         Al Martino | 172.18.0.7 |  
> 22. Juni 2020 21:54 | 22. Juni 2020 22:57 | Der Himmel soll warten (Studio Version)                         Adel Tawil, Sido | 172.18.0.7 |  
>

**Comment by SlvrEagle23** [comment]
@roger-net @LordHelmchen666 I've updated the code to pass the IP address that's being used for the duplicate-IP check to the StationRequest database itself, so both will match regardless of what they're set to. This should help fix the issue.
