### ISSUE TITLE
merge files into playlist

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#3017]
Hello,
I have a little difficulty in the playlist, it doesn't seem to work well., How do I set up a playlist that plays two files in sequence and then move on to other playlist?
In the way that azuracast manages he only plays a song or else he doesn't play the sequence I want.

I just wanted to merge the two files as if it were the same as in the managed mode by liquidsoap.

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli Without using Liquidsoap directly, the only way to accomplish this is to merge both the audio files into another file and play that. We don't have the functionality inside the AzuraCast AutoDJ to handle this at the moment.

**Comment by Marcioghiraldelli** [comment]
I can only do this if I leave the management of the auto dj manual, that way I mark in advanced the merge as a single file and it works, now if you let azuracast command it no longer works.

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli I don't completely understand your last response, but yes, if you are using advanced AutoDJ features, then the AzuraCast AutoDJ can't do its job as well and it will ignore that playlist, instead letting Liquidsoap handle it. Running in fully "Manual AutoDJ" mode will alleviate that issue.

These are all advanced functions that are don't currently natively support in AzuraCast, and are intended solely for power users doing very specific scenarios, so I unfortunately don't have any further support that I can provide for this question.
