### ISSUE TITLE
Ubuntu 18 ansible update error

### ISSUE THREAD

**Issue by maletazul** [AzuraCast/AzuraCast#3018]
Ubuntu 18 ansible update error

Any feedback on this update error?

fatal: [localhost]: FAILED! => {"changed": true, "cmd": "composer install --no-dev --optim
ize-autoloader", "delta": "0:00:00.338200", "end": "2020-07-08 12:23:08.281959", "msg": "n
on-zero return code", "rc": 1, "start": "2020-07-08 12:23:07.943759", "stderr": "Loading c
omposer repositories with package information\nInstalling dependencies from lock file\nPac
kage operations: 0 installs, 5 updates, 0 removals\n  - Downgrading zircote/swagger-php (d
ev-master e61cfa2 => 3.0.4): \n                                                           
                                \n  [RuntimeException]                                    
                                   \n  Source directory /var/azuracast/www/vendor/zircote/
swagger-php has uncommitted changes.  \n                                                  
                                         \n\ninstall [--prefer-source] [--prefer-dist] [--
dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--n
o-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap
-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...", "stder
r_lines": ["Loading composer repositories with package information", "Installing dependenc
ies from lock file", "Package operations: 0 installs, 5 updates, 0 removals", "  - Downgra
ding zircote/swagger-php (dev-master e61cfa2 => 3.0.4): ", "                              
                                                             ", "  [RuntimeException]     
                                                                  ", "  Source directory /
var/azuracast/www/vendor/zircote/swagger-php has uncommitted changes.  ", "               
                                                                            ", "", "instal
l [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers
] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-
o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platf
orm-reqs] [--] [<packages>]..."], "stdout": "", "stdout_lines": []}

**Comment by SlvrEagle23** [comment]
@maletazul This should be fixed as of the latest update; try updating again and it should resolve itself.
