### ISSUE TITLE
"Cronjob" media scan runs into a timeout

### ISSUE THREAD

**Issue by aconitumnapellus** [AzuraCast/AzuraCast#3020]
Hi,

I use azuracast since a couple months and we are not able to scan the medialibrary since 3 months.
The only logs related to this are the ones i found in docker-compose logs -f below (censored because they contain sensitive information:

**Using Docker installation method**
Yes

**AzuraCast version**
 v0.10.3, #0dea2de (2020-06-25 8:47) 

**Host Operating System**
Debian Buster

**Describe the bug**
The recurring media scan cronjob does not run, if manually executed, it runs into a 504 or a 502.
If executed in the container with curl, it runs into a 500 after some time (3minutes)

**To Reproduce**
1. Go into the azuracast administration
2. click "run task" on the "5-min task"
3. wait
4. See 502/504 error

**Expected behavior**
Recurring media scan should work out of the box

**Relevant Logs**
`nginx_proxy_1              | nginx.1    | 2020/07/10 13:09:18 [warn] 5024#5024: *148575 upstream server temporarily disabled while reading response header from upstream, client: 10.1.1.3, server: azuracast.local, request: "GET /admin/debug/sync/medium HTTP/2.0", upstream: "http://172.27.0.3:80/admin/debug/sync/medium", host: "vm-azuracast-01.local", referrer: "https://vm-azuracast-01.local/admin"`

`nginx_proxy_1              | nginx.1    | 2020/07/10 13:09:18 [error] 5024#5024: *148575 no live upstreams while connecting to upstream, client: 10.1.1.3, server: azuracast.local, request: "GET /admin/debug/sync/medium HTTP/2.0", upstream: "http://azuracast.local/admin/debug/sync/medium", host: "vm-azuracast-01.local", referrer: "https://vm-azuracast-01.local/admin"`

`nginx_proxy_1              | nginx.1    | vm-azuracast-01.local 10.1.1.3 - - [10/Jul/2020:13:09:18 +0000] "GET /admin/debug/sync/medium HTTP/2.0" 502 150 "https://vm-azuracast-01.local/admin" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"`

**Screenshots**

**Device(s):**
 - Device: Desktop
 - OS: ArchLinux
 - Browser: FIrefox
 - Version: 78.0.1

**Additional context**

**Comment by SlvrEagle23** [comment]
@aconitumnapellus How many media files do you have in your library overall? Were they all modified or uploaded fairly recently, so the media processing task would handle them all at once?

We recently made some changes to our message queue processing, and I think that may be what's causing this issue. I'll be looking into further improvements we can make on that front.

**Comment by SlvrEagle23** [comment]
@aconitumnapellus I've updated our Message Queue to prevent "stacking" the message queue and over-queueing tracks repeatedly, which should help fix this issue.

**Comment by aconitumnapellus** [comment]
> @aconitumnapellus How many media files do you have in your library overall? 
Amount of mediafiles: 116723

> Were they all modified or uploaded fairly recently, so the media processing task would handle them all at once?
No, they are available on a FUSE mount and were not modified recently.

> We recently made some changes to our message queue processing, and I think that may be what's causing this issue. I'll be looking into further improvements we can make on that front.
Okay, im upgrading and testing it out once i have time (probably this friday)

**Comment by aconitumnapellus** [comment]
Hi, i updated it today and checked if your commit has been applied.
I think it solved issues with the other recurring tasks, but not the "media scan"
It still runs into a 502.

Further info i got while debugging:
i tried to manually execute the API call with this:
`curl --insecure --connect-timeout 600 --cookie "app_session=XXX" http://azuracast_web/admin/debug/sync/medium`
I cant execute this while "redirect everything to 443" is active, as it tries to redirect to azuracast_web 443, which is not available.

**Comment by aconitumnapellus** [comment]
Could this be related? https://github.com/AzuraCast/AzuraCast/issues/3011
We use the docker installation tho and not the ansible method in the issue mentioned

**Comment by aconitumnapellus** [comment]
We migrated our broken docker azuracast install to a pure ansible one and some problems resolved themselves, others not.
We are still running into `PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes)`.
Ive adjusted /etc/php/7.4/fpm/php.ini and /etc/php/7.4/cli/php.ini to use more than 2GB of RAM but it still fails at allocating more than 256M...
Is there an internal memory limit inside azuracast for this?
Can we adjust this to finally resolve this issue?

**Comment by SlvrEagle23** [comment]
@aconitumnapellus I'm not sure why your Docker installation was "broken" but migrating from Docker to Ansible is actually migrating to a _less_ supported and more difficult-to-maintain installation format. While this may provide short-term resolution of issues I doubt it is the ideal decision in the long term.

The way your installation is set up, with over 100,000 media files being accessed over a FUSE mount, is not a standard means of using AzuraCast and may be introducing these problems, which we don't design for because we simply don't expect this configuration to be that common. Even so, we have optimizations to our media batch processing to allow for it to continue with a low level of memory, so if you're exhausting the memory available I'd be interested to know how your files are structured folder-wise and how large the largest one is.

**Comment by aconitumnapellus** [comment]
> @aconitumnapellus I'm not sure why your Docker installation was "broken" but migrating from Docker to Ansible is actually migrating to a _less_ supported and more difficult-to-maintain installation format. While this may provide short-term resolution of issues I doubt it is the ideal decision in the long term.
> 
> The way your installation is set up, with over 100,000 media files being accessed over a FUSE mount, is not a standard means of using AzuraCast and may be introducing these problems, which we don't design for because we simply don't expect this configuration to be that common. Even so, we have optimizations to our media batch processing to allow for it to continue with a low level of memory, so if you're exhausting the memory available I'd be interested to know how your files are structured folder-wise and how large the largest one is.

Im know that the ansible installation is less supported and i know its more difficult to maintain, but we run into very docker specific problems (only partially azuracast related) so we decided to end the pain and switched to the ansible installation (We are doing daily snapshots of the VM + backups of azuracast itself, so even if it fucks up, we can just roll back.)

Would it be a "solution" to increase the available memory for azuracast to something like 512M?

FUSE Mount 1 has somewhat this directory structure:
`/mount/ROCK/Artist/Album/01 - Example - Track 01.mp3`

FUSE Mount 2 has somewhat this directory structure:
`/mount2/Artist/Album/01 - Example.mp3`
or
`/mount2/Artist/01 - Example.mp3`

When i was debugging this, i noticed that azuracast tries to scan the PNG album files lying beneath the MP3 files for music.
Is this expected behaviour? May this exhausting the memory available?

Most files are in the 3-30MB range (MP3 and FLACs) but ive found some (maybe 5-10) very huge files (500MB+).
Should i delete / move them?

**Comment by SlvrEagle23** [comment]
@aconitumnapellus We definitely aren't built around having files in the 500MB+ range, and that's very likely the issue you're running into.

For Docker installations, we do have an environment variable you can modify in the [azuracast.env](https://github.com/AzuraCast/AzuraCast/blob/master/azuracast.sample.env#L93) file. If you change that line, then restart the Docker containers (either via `docker-compose down` and `docker-compose up -d` or by just restarting) it will give it the higher memory and should help.

For Ansible installations, modifying the available memory is a manual task that's done by editing the `php.ini` configuration, which I believe is located at `/etc/php/7.4/cli/php.ini`.

**Comment by Vaalyn** [comment]
Closing this issue since there have been a lot of optimisations with the media processing since the last comment on this thread.
