### ISSUE TITLE
Question About Multi Site Installation

### ISSUE THREAD

**Issue by emiryapici** [AzuraCast/AzuraCast#3021]
**Using Docker installation method**

Yes
**AzuraCast version**

v.0.10.3 #e850aa1
**Host Operating System**

Ubuntu 18.04.4

Hello team! Thanks for this awesome broadcasting system, I have a question about multi site installation.
I will have 4 computers running azuracast each have 10 stations inside. I want to manage whole stations from one control panel. Is it possible? How can i do this?

**Comment by SlvrEagle23** [comment]
@emiryapici At the moment, I don't suspect it's possible to use a single web interface to manage multiple separate AzuraCast instances.

**Comment by ogrenci01** [comment]
**English**:
Hi @emiryapici ;

Welcome to AzuraCast. This seems unlikely. AzuraCast contains **"Role-based User Management"**. It supports multiple users and stations.

**Turkish**:
Merhaba @emiryapici ;

Aramıza hoşgeldin. Bu pek mümkün görünmüyor. AzuraCast içinde **"Rol Tabanlı Kullanıcı Yönetim"** barındırıyor. Birden fazla kullanıcıyı ve istasyonu destekler.
