### ISSUE TITLE
Adding extra storage to droplet at Digital Ocean.

### ISSUE THREAD

**Issue by JohnKoumpouras** [AzuraCast/AzuraCast#3025]
**Using Docker installation method**
Yes (Digital Ocean Droplet) - 1vcpu-2gb-50Gbdisk

**AzuraCast version**
v0.10.3, #2abb8bf (2020-07-08 7:03) Rolling • Docker • PHP 7.4

**Host Operating System**
Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-109-generic x86_64)

**Describe the bug**
I have mounted a storage volume of 30Gb to my droplet with the traditional method
with the following commands
1. sudo fdisk /dev/sda giving the parameters n,p,w.
2. sudo mkfs.ext4 /dev/sda1
3. sudo mkdir /mnt/vol30
4. sudo mount /dev/sda1 /mnt/vol30
5. I inserted the following line in /etc/fstab : UUID=9fe70e50-ab67-4f6b-a88d-bb45bf678e61 /mnt/vol30 ext4 defaults 0 2

The volume succesfully mounted after reboot.

Giving the "lsblk" command i have the following on my screen :

loop0 7:0 0 97M 1 loop /snap/core/9289
loop1 7:1 0 96.5M 1 loop /snap/core/9436
loop2 7:2 0 9.1M 1 loop /snap/canonical-livepatch/95
sda 8:0 0 30G 0 disk
└─sda1 8:1 0 30G 0 part /mnt/vol30
vda 252:0 0 50G 0 disk
├─vda1 252:1 0 49.9G 0 part /
├─vda14 252:14 0 4M 0 part
└─vda15 252:15 0 106M 0 part /boot/efi

**To Reproduce**
I want to add more storage space to Azuracast platform to upload more audio tracks for auto-DJ
I have created a "docker-compose.override.yml" file with the following contents:

version: '2.2'

services:
web:
volumes:
     - /mnt/vol30:/var/azuracast/stations/my_radio_station/media/

stations:
volumes:
    - /mnt/vol30:/var/azuracast/stations/my_radio_station/media/

My advanced base station directory is : /var/azuracast/stations/my_radio_station
My advanced custom media directory is : /var/azuracast/stations/my_radio_station/media

I have given the following commands: "docker-compose down" and "docker-compose up -d"

**Expected behavior**
Everything goes well with no message errors but the Azuracast platform does not recognize the added storage space of 30gb from the /mnt/vol30 directory when I log in to the platform

Please, someone, help me if I have made a mistake with the above.

**Comment by SlvrEagle23** [comment]
@JohnKoumpouras This is a known issue; we check the available storage against `/var/azuracast/stations`, not the individual media directories, so if you mount extra storage only to a station-specific media directory it won't be recognized by the system.

**Comment by JohnKoumpouras** [comment]
What changes i must make to "docker-compose.override.yml" file?
Thanks for your support @SlvrEagle23.
