### ISSUE TITLE
Album art only displays default image

### ISSUE THREAD

**Issue by pixel-paul** [AzuraCast/AzuraCast#3027]
**Using Docker installation method**
Yes
**AzuraCast version**
Powered by AzuraCast • v0.10.3, #23af29f (2020-07-12 23:33) Rolling • Docker • PHP 7.4

**Host Operating System**
CentOS 8

**Describe the bug**
Album art that has been assigned to a track doesn't appear - the default album art is shown instead

**To Reproduce**
On dashboard, album art for now playing or next shows default.

The API (now_playing.song.art) returns default.

**Expected behavior**
Ablum art assigned to track should display

**Device(s):**
Firefox 79 // MacOS X

**Comment by JohnKoumpouras** [comment]
I having the same problem some time ago.
Try the following: If you update with the "./docker.sh update" command
change to "./docker.sh update --release"
and make a reboot of your server
Look here at Digital Ocean: https://marketplace.digitalocean.com/apps/azuracast
Hope that helps @pixel-paul

**Comment by pixel-paul** [comment]
Hi @JohnKoumpouras,

That would put me on the 'release' tag. 

I believe this is a bug introduced to the 'rolling' branch (so bleeding edge). 

Thanks,

Paul

**Comment by pixel-paul** [comment]
Interestingly, this may just be an edge case bug, as the album art is now appearing correctly. I updated the software this morning, so perhaps this arises whilst a cache is being built?
