### ISSUE TITLE
docker.sh restore fails with mysql error

### ISSUE THREAD

**Issue by jeremyn54** [AzuraCast/AzuraCast#3031]
**Using Docker installation method**

Yes

**AzuraCast version**

v0.10.3, #9811fbb (2020-06-22 4:38) 

**Host Operating System**

CentOS 7

**Describe the bug**

When attempting to run ./docker.sh restore backup.zip, I get ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb' (115)

**To Reproduce**

1. Performed manual backup via System Administration -> Backups
2. Docker Self-Installation on new CenOS 7 host
3. Did not setup a user via web interface (clean database)
4. Ran `./docker.sh restore backup.zip` from inside the /var/azuracast directory.

**Expected behavior**

Successful restore of InfluxDB and MariaDB

**Relevant Logs**

I went line-by-line from the restore function in docker.sh to get the same result:

`root@server [azuracast]# docker-compose down -v`
`root@server [azuracast]# docker-compose pull`
`root@server [azuracast]# docker-compose up -d web`
`root@server [azuracast]# docker cp "./backup.zip" "azuracast_web:tmp/cli_backup.zip"`
`MSYS_NO_PATHCONV=1 docker exec --user="azuracast" azuracast_web azuracast_restore "/tmp/cli_backup.zip" "$@"`

And then the script bailed at:

> Importing database...
>
>---------------------
>
>ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb' (115)
>
>In Process.php line 256:
>                                                                               
>  The command "mysql --host=$DB_HOST --user=$DB_USERNAME --password=$DB_PASSW  
>  ORD $DB_DATABASE < $DB_DUMP" failed.                                         
>                                                                               
>  Exit Code: 1(General error)                                                  
>                                                                               
>  Working directory: /tmp/azuracast_backup_mariadb                             
>                                                                               
>  Output:                                                                      
>  ================                                                             
>                                                                               
>                                                                               
>  Error Output:                                                                
>  ================                                                             
>  ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb' (115)         
>                                                                               
>
>azuracast:restore [--restore] [--release] [--] <path>

**Screenshots**

**Device(s):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**

I managed to perform a successful restore by getting a shell directly into the web container, and now I have a fully functional server:

`root@server [azuracast]# docker exec -it azuracast_web /bin/bash`
`root@5a90e411c107:/var/azuracast/www# su azuracast`
`azuracast@5a90e411c107:~/www$ cd /tmp`
`azuracast@5a90e411c107:/tmp$ rm -rf azuracast_backup_*`
`azuracast@5a90e411c107:/tmp$ azuracast_restore /tmp/cli_backup.zip`
`azuracast@5a90e411c107:/tmp$ exit`
`root@5a90e411c107:/var/azuracast/www# exit`
`root@server [azuracast]# docker-compose down`
`root@server [azuracast]# docker-compose up -d`

I can provide additional logs or verbosity if required, I was able to reproduce this twice. The second time I completely erased docker packages and /var/lib/docker directory. I realise there is still some development going on with the Backup/Restore features, but I thought it was worth noting in case anyone has missed it. Thanks.

**Comment by ericrbg** [comment]
Can confirm this issue still exists, and the workaround also worked for me. I installed this on Ubuntu Server 20.04.

**Comment by SlvrEagle23** [comment]
I looked into this and the reason the workaround works while the original doesn't is because the restore script didn't have a proper "wait for the services to spin up" timer built into it. I've added a basically no-op cache clear call to happen directly before the restore starts, so that things will start up prior to running that task, which should fix this issue.

**Comment by houndbee** [comment]
This issue still seems to exist. While trying to restore a backup to a fresh Azuracast install. Both instances, old and new are running v0.11 Stable and are using the latest docker.sh.

`````
Importing database...
---------------------

ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb' (115)

In Process.php line 257:
                                                                               
  The command "mysql --host=$DB_HOST --user=$DB_USERNAME --password=$DB_PASSW  
  ORD $DB_DATABASE < $DB_DUMP" failed.                                         
                                                                               
  Exit Code: 1(General error)                                                  
                                                                               
  Working directory: /tmp/azuracast_backup_mariadb                             
                                                                               
  Output:                                                                      
  ================                                                             
                                                                               
                                                                               
  Error Output:                                                                
  ================                                                             
  ERROR 2002 (HY000): Can't connect to MySQL server on 'mariadb' (115)
