### ISSUE TITLE
Fallback System not respected

### ISSUE THREAD

**Issue by DamonOnYT** [AzuraCast/AzuraCast#3041]
**Using Docker installation method**
Yes
**AzuraCast version**
Powered by AzuraCast • v0.10.3, #9811fbb (2020-06-22 4:38) • Docker • PHP 7.4

**Host Operating System**
Ubuntu

**Describe the bug**
The fallback system is not working properly from what I can see. Using a remote shoutca.st, when it goes down It is not sending users over to /fallback and /radio.mp3 shows a 404 error

**To Reproduce**
Create a mount point with a relay to a shoutca.st stream
Create a /fallback mountpoint with autodj
Using a remote shoutca.st stream, stop the remote server
Stream will then cut out, wont auto swap and /radio.mp3 gets stuck on a 404 error.

**Expected behavior**
I would expect it to move all clients to /fallback and the /radio.mp3 to automatically send over to fallback and new users trying to go to /radio.mp3 takes them to fallback

**Comment by xewl** [comment]
Question: Do you have Auto DJ enabled?
