### ISSUE TITLE
Clone Station Error

### ISSUE THREAD

**Issue by emiryapici** [AzuraCast/AzuraCast#3043]
**Using Docker installation method**

Yes
**AzuraCast version**

v0.10.3, #ffa6d6b
**Host Operating System**

Ubuntu  Mate 20.04
**Describe the bug**

Hello! I'm trying to clone one of my stations with all data inside it. I'm selecting "Copy the existing station's media to the new station" and "copy playlists -> yes" but none of the songs and playlists were copied. It was running perfect on "v0.10.3, #4c825f7"

**Comment by emiryapici** [comment]
I think it was caused by my hardware. It's now working with another computer.

**Comment by triangle-stream** [comment]
Unfortunately issue is still present and tried with several machines and Ubuntu versions (18.04 - 20.04).

I've opened a new [issue](https://github.com/AzuraCast/AzuraCast/issues/3958).
