### ISSUE TITLE
Question related to playlists and AutoDJ

### ISSUE THREAD

**Issue by samkitk** [AzuraCast/AzuraCast#3046]
If I have a single song in a playlist and it is scheduled to run from 10:00AM to 10:15AM but the song is shorter than that. Let's say 10 minutes. What happens is that the song repeats itself which messes up the future scheduled playlists from 10:15AM since I am not using advanced settings from LiquiqSoap's AutoDJ(which enable you to interrupt a current playing song to play according to schedule) and Azuracast's AutoDJ won't interrupt an existing song. So, is there any setting in Azuracast's AutoDJ that enables you to not repeat the same audio but rather play a generic message? (error.mp3 or something that I can choose) so my schedule is not disturbed and playlists don't repeat

**Comment by pavlos2** [comment]
Hi Sam, if none of the edit/playlist/basic options is suitable then you must use an advanced playlist.
