### ISSUE TITLE
Kicking streamers

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#3048]
Docker install
AzuraCast version - v0.10.3, #9811fbb (2020-06-22 4:38) • Docker • PHP 7.4 
Host Operating System - Ubuntu 20.04
Running ShoutcastV2
Single source on dual output streams 128kbps & 64kbps
Liquidsoap autoDJ on

As we did with the old Shoutcast servers, it is possible when running a local robot as source (with LiquidSoap off) to kill the source with the Shoutcast kill code issued from any browser, without accessing the server directly and then to log on as source.  

Kicking the autoDJ is never an issue, but my question; is there a way, with LiquidSoap running, to remotely kill a live stream without accessing the Azuracast server directly, then log in to stream in his stead (provided he hasn't set his auto-reconnect to 0) ? 
I have already tried different ways to remotely issue the Azuracast kill backend command, but without any success. Guess I haven't hit on the right syntax to append the admin credentials into the command, if such is at all possible...  
Sending the Shoutcast kill command will kill the source for either one of the streams, but can both be killed in one go without issuing 2 kill commands?  Or is there a better way of doing all this?

**Comment by SlvrEagle23** [comment]
@SpeedyCharly If you just broadcast directly to the AutoDJ (Liquidsoap) using our Streamers / DJs support, it will automatically disconnect the existing audio to play the incoming audio source; this may avoid you having to manually kick the AutoDJ from SHOUTcast to allow for another input.

**Comment by SpeedyCharly** [comment]
Guess I wasn't clear - you misunderstood the problem.  If AutoDJ is on air when we start a stream, there isn't a problem. it will yield and the live stream will broadcast fine.  What I would like to have is an easy means to kick a live stream that has overstayed his welcome without having to actually access the dashboard and use the kill back end command.  On old servers without AutoDJ we did it with a command such as this (http://ip/radio/port/admin.cgi?sid=1&mode=kicksrc) that we could issue from any navigator.  

I want to give such a command to my radio announcers so that they may be able to remove another who forgot to log off and prevents them logging in.  All this without me giving universal access to the server console...
