### ISSUE TITLE
backups errors

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#305]
on two servers when performing backups, writes
/usr/bin/docker-current: Error response from daemon: create .: "." includes i    nvalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" a    re allowed.

**Comment by SlvrEagle23** [comment]
@susl16c I can confirm that if the path was left as the default, the backup script wouldn't work because "." is an invalid volume path. I have pushed a fix that will resolve relative paths, which should fix this issue.
