### ISSUE TITLE
Shoutcast Install - 502 Bad Gateway

### ISSUE THREAD

**Issue by radioguy0** [AzuraCast/AzuraCast#3051]
**Using Docker installation method**

Yes
**AzuraCast version**

v0.10.3, #9811fbb (2020-06-22 4:38)
**Host Operating System**

Ubuntu 18.04 (x64)
**Describe the bug**

Shoutcast Admin panel not connecting with AzuraCast via the Nginx configuration properly
**To Reproduce**
 1. Upload Shoutcast using the built in installer
2. Edit station in System Admin interface
3. Activate Shoutcast DNAS 2
4. Enter the station management 
5. Click the link for the Shoutcast Admin.cgi 
6. 502 Bad Gateway occurs

**Expected behavior**

Server admin page should load normally
**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@radioguy0 Do you have the "Use Web Proxy" feature turned on? It's possible that SHOUTcast isn't fully compatible with that (from solely an administrative standpoint; from a broadcasting one it is known to work with it just fine). You may want to try visiting `your-azuracast-url:8xxx/admin.cgi` directly and that may help.

**Comment by radioguy0** [comment]
Hey @SlvrEagle23, dug a little deeper into this and found that web proxy was previously enabled. 

However, after disabling this feature, the web address (IP):8xxx/admin.cgi now showed a generic unloaded page error i.e. "server not responding". 

Out of curiosity, I followed up by trying the URL (IP)/radio/8xxx/admin.cgi (as is the case with Icecast) and got the original error like before (a 502 Bad Gateway with nginx). Any ideas on this one? 

At a bit of a loss as to why we could have this problem since the SC Serv file was loaded correctly and fully up to date and there are no other glaringly obvious server issues, besides this matter appearing at the surface for now.

Thanks again!
