### ISSUE TITLE
Store album art on website

### ISSUE THREAD

**Issue by andrewyv** [AzuraCast/AzuraCast#3052]
Hi,

How can i store the album art of songs on my website and not on azuracast instance?

Thank you.

**Comment by SlvrEagle23** [comment]
@andrewyv If you want to change where album art is stored, you may be able to follow something similar to [this guide](https://www.azuracast.com/help/docker/#mounting-a-directory-into-a-station), but specifically with the `/var/azuracast/stations/(station_name)/albumart` directory.

Serving that directory via the web server would be rather simple to do if you needed to.
