### ISSUE TITLE
Skip Song & Play Next Not Working

### ISSUE THREAD

**Issue by thexfilesnetwork** [AzuraCast/AzuraCast#3053]
We have noticed that when we skip to the next audio it will not play what's coming up next. It is often playing the same ones over and over again even though we have about 30 to choose from. Please help us fix this.

**Comment by SlvrEagle23** [comment]
@thexfilesnetwork Can you provide more information about what installation type you're using (Docker or Ansible), and if the skip functionality is showing you any error messages?
