### ISSUE TITLE
API issue found(+ fix) /web/static/api/openapi.yml

### ISSUE THREAD

**Issue by Makunia** [AzuraCast/AzuraCast#3054]
Hey, we worked on a Second-Life ->AzuraCast API and found a issue

/web/static/api/openapi.yml
---------------------------
issue
1398 schema:
1399 type: int64

fix
1398 schema:
1399 type: integer
1400 format: int64

---------------------------
issue
2984 schema:
2985 type: int64
2986 example: 1

fix
2984 schema:
2985 type: integer
2986 format: int64                           
2987 example: 1

---------------------------
issue
2929 type: object
2930 ' ':                                        <-----?      Reference?
2931 properties:

fix?

**Comment by SlvrEagle23** [comment]
@Makunia Our OpenAPI spec document is automatically generated by a tool that analyzes our code and auto-builds the YML file, so I need to check with them to see about fixing this.

**Comment by SlvrEagle23** [comment]
@Makunia This should now be fixed as of the latest OpenAPI spec doc.
