### ISSUE TITLE
Build an image with latest Liquidsoap 1.4.3 pre-release

### ISSUE THREAD

**Issue by bjarn** [AzuraCast/AzuraCast#3055]
Liquidsoap fixed some issues with the crossfade method which were caused by incorrect buffering.

https://github.com/savonet/liquidsoap/issues/1074 (https://github.com/savonet/liquidsoap/milestone/7?closed=1)

If you could build an image with the latest commit from the pre release branch that would be great for testing purposes.

This fix makes it possible to make even better transitions using your radio imaging, so that's a must have for any radio station I suppose :)

Thanks!

**Comment by SlvrEagle23** [comment]
@bjarn Latest image is built!

**Comment by bjarn** [comment]
Thanks a lot! Running smoothly :-)
