### ISSUE TITLE
Requesting a single Song from Playlist  or an mp3-file on an Azuracast Server via URL ! Help Needed

### ISSUE THREAD

**Issue by Torraner** [AzuraCast/AzuraCast#3056]
Since about two month i use Azuracast. And i like it very much. I use it
as a soundsource for a Fan-Site for a musician made with wordpress. Now
i´m starting to publish song-posts with lyrics and if available videos.

Now i have two questions.

Is there a possibility to request one specific song out of a playlist ?

For Example
(imagine/some/url/playlist/request?mp3filename)

Or is there a possibility to request the mp3-files on the radioserver
(Radioserver:strangeportnumber/path/to/the/mp3/files/song.mp3)

via URL. 
(I ask for the second example, because the Azurucast Installation uses its own Webserver, and it is installed on a server which does not use any other webserver. The dedicated machine is used for azuracast only) 

Both would be very nice to implement the songs into the wordpress
songposts with lyrics via an WordpressAudioplayer. Because the soundquality of youtube isn´t realy
great.

It would be also very intresting to know, wether and when yes how, it is possible to install other things on the Azuracast-Webserver. 
Greets from Germany

Jan

**Comment by Warlkar** [comment]
Ich antworte hier mal in Deutsch.
via URL (also einfach im browser) geht es nicht. du kannst ein Musikwunsch via API senden musst aber dafür im Header ein API Key mitsenden (du müsstest dir also ne PHP oder ähnliches basteln) selbst dann würdest du nur den Musikwunsch einreihen nicht direkt im Radio abspielen lassen.
deine 2. frage ob man die MP3 direkt laden kann, kann ich auch nur mit nein, direkt ist das nicht möglich beantworten, da die MP3's Standardmäßig nicht im Webverzeichnis gespeichert/hochgeladen werden.
allerdings ist es möglich On-Demand Media zu aktivieren und darüber dann die MP3's zu laden. Du müsstest vorher in dein Stationsprofil On-Demand Media aktivieren und dann die betreffende Playlist bearbeiten und dort auch On-Demand Media aktivieren. dann kannst du über die On-Demand Media seite dir die MP3 raussuchen und via rechtsklick auf die download wolke die linkadresse kopieren. diese solltest du dann für dein Wordpress Audioplayer einbauen.

Gruß aus Deutschland
auch ein Jan xD

**Comment by Torraner** [comment]
@Warlkar 
Danke für den Tip mit der "On demand Media" Funktion. Wo genau kann man die finden. Ich bin die ganze Zeit am suchen. Ist die Funktion womöglich neu ? Ich habe version 9.9 auf dem Server.

Gruss
Jan

**Comment by Warlkar** [comment]
Ja das ist eine der neueren Funktionen, bitte einmal updaten ^^

**Comment by Torraner** [comment]
@Warlkar 
Ich habe jetzt mal ein Update gemacht. Und die Funktion auch gefunden. Was ich vorhatte funktioniert zwar immer noch nicht so ganz, weil der download-link nicht direkt auf einen datei-namen verweist sondern auf etwas wie /stell/dir/einen/pfad/vor/download/655321862. Wenn man den link im browser aufruft, dann lässt sich die datei auch sauber runterladen. Sogar mit ihrem echten Namen. Aber wenn ich den Link im wordpress audio-player angebe funktioniert es nicht.

Und der link des Playbuttons auf der on demand media Seite ist für jeden Song der gleiche. Mal sehen. Wenigstens bin ich mal einen schritt weiter. Ich bin aber auf jeden fall für jede Idee dankbar.

**Comment by Torraner** [comment]
@Warlkar 
Ist es vielleicht irgendwie möglich einer Playlist url  Anweisungen mit zu geben, also zu sagen "Spiele song 3 bis 5" oder spiele von Minute 40 bis 90. So wie man es etwa bei Youtube-URLS kennt ?

**Comment by Warlkar** [comment]
> @Warlkar
> Ich habe jetzt mal ein Update gemacht. Und die Funktion auch gefunden. Was ich vorhatte funktioniert zwar immer noch nicht so ganz, weil der download-link nicht direkt auf einen datei-namen verweist sondern auf etwas wie /stell/dir/einen/pfad/vor/download/655321862. Wenn man den link im browser aufruft, dann lässt sich die datei auch sauber runterladen. Sogar mit ihrem echten Namen. Aber wenn ich den Link im wordpress audio-player angebe funktioniert es nicht.
> 
> Und der link des Playbuttons auf der on demand media Seite ist für jeden Song der gleiche. Mal sehen. Wenigstens bin ich mal einen schritt weiter. Ich bin aber auf jeden fall für jede Idee dankbar.

ja das ist die song_id, die wird beim Abspielen per Javascript auch genutzt, kA wie WordPress Audioplayer damit umgeht, eventuell müsstest du entsprechende header dateien mitsenden.


> @Warlkar
> Ist es vielleicht irgendwie möglich einer Playlist url Anweisungen mit zu geben, also zu sagen "Spiele song 3 bis 5" oder spiele von Minute 40 bis 90. So wie man es etwa bei Youtube-URLS kennt ?

Das weiss ich leider nicht, Es gibt die Möglicheit eigene LiquidSoap (der AutoDJ) Scripte einzubinden die das eventuell könnten, aber damit hab ich mich Persönlich noch gar nicht befasst.
und nicht das es falsch rüber kommt, ich bin auch nur Nutzer und kein Supporter aber versuche zu helfen wo man kann ^^

Grüße
