### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#306]
When translating data phrases into Russian
**Process stopped.
Process was not running!
Process is already running!
%s Daily Average
Automated assignment complete!
Media metadata updated!
Song skipped.
<b>Apply Pending Changes</b><br>Click to Restart Station
Song Listener Impact
Average Listeners
Station Playback Timeline**
The entire language of the site becomes an English language, why?
Not all phrases have been added for translation, especially errors when authorizing and on the main page.

**Comment by SlvrEagle23** [comment]
@susl16c Translations have been updated, so more strings should be properly translated.

Our translations are managed through CrowdIn. You can see the progress of translation or submit your own at https://crwd.in/azuracast

**Comment by susl16c** [comment]
and here translations? I do not need them. I translated everything myself, I say that when translating these phrases the web language becomes English, why?
