### ISSUE TITLE
Features and Improvements page [Comment]

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#3064]
As per suggestions, I have posted a few issues on the Features and Improvements page but, after weeks, they still are awaiting approval which makes me wonder about the actual usefulness of that page...

What is the use of having a tool if it is left sitting at the bottom of the toolbox and not used as it should?

**Comment by SlvrEagle23** [comment]
@SpeedyCharly Believe it or not, almost every aspect of this project is managed and written by one person. I have to juggle a lot of responsibilities, from triaging GitHub issues to handling upstream dependency updates to providing support on our social media, Slack and Discord channels.

On top of that, I'm also just a regular guy who has to not run out of money in the middle of a pandemic. As AzuraCast donations are very nice but , I've been working on some paid projects on the side, which is what I've been up to this last week or so.

I promise I will get back to the new feature requests as soon as I can.
