### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by AaronUnmuted** [AzuraCast/AzuraCast#3065]
**Using Docker installation method**
Yes

**AzuraCast version**
Latest Docker

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
We are attempting to install AzuraCast via Docker on our brand new OVH Advance-2 dedicated server. However, the installation does not complete and will show errors associated with dependencies being offline. I have encountered this before, and running the Docker update tool seems to resolve. However when running this, more errors are shown, please see here: http://prntscr.com/tt8tl0

**Expected behavior**
Installation/upgrade should complete as normal. 

**Relevant Logs**
http://prntscr.com/tt8tl0

**Device(s):**
 - Device:  Desktop
 - OS:  Windows 10
 - Browser:  Chrome

**Comment by AaronUnmuted** [comment]
**When running Docker update tool:** 

Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...
 * Environment: Production
 * Installation Method: Docker

Waiting for dependent services to go online...
 0/3 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%

 [ERROR] Error encountered: An exception occurred in driver: SQLSTATE[HY000] [2006] MySQL server has gone away
         (/var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php L106)


 ! [NOTE] Running in update mode.

Setting Up InfluxDB
-------------------

Database created.
Retention policies updated.
Continuous queries created.
InfluxDB databases created.

Running Database Migrations
---------------------------


In AbstractMySQLDriver.php line 106:

  An exception occurred in driver: SQLSTATE[HY000] [2006] MySQL server has gone away


In PDOConnection.php line 31:

  SQLSTATE[HY000] [2006] MySQL server has gone away


In PDOConnection.php line 27:

  SQLSTATE[HY000] [2006] MySQL server has gone away


In PDOConnection.php line 27:

  Packets out of order. Expected 0 received 1. Packet size=69

**Comment by SlvrEagle23** [comment]
@AaronUnmuted Usually the "MySQL server has gone away" error means that the MySQL process ran out of memory and was shut down by the parent OS. You may want to create some swap space on your hosted server just so MySQL is less likely to run out of memory like that.

**Comment by AaronUnmuted** [comment]
@SlvrEagle23 Hey! Thanks for your reply. Unfortuntely we're not having much luck with this one. I've created a swap file but still running into issues. I've tried a completely clean install too.

`Timeout after 40s waiting on dependencies to become available: [tcp://mariadb:3306 tcp://influxdb:8086 tcp://redis:6379]`

The above is shown when trying to install Azura. Running 'swapon' shows the below output:
`
NAME      TYPE      SIZE USED PRIO
/swapfile file        5G   0B   -2
/dev/sdb3 partition 511M   0B   -3
/dev/sda3 partition 511M   0B   -4
`

Any ideas?

**Comment by SlvrEagle23** [comment]
@AaronUnmuted I think I have a potential idea on what might be causing this...if the installer process overruns a timeout internally, it can drop the MariaDB connection in a way that it would only notice when executing the next command.

For the setup process I've added some interstitial "ping" commands between the other tasks, which should help a little in alleviating this problem.
