### ISSUE TITLE
Problem with scheduling

### ISSUE THREAD

**Issue by president-2020** [AzuraCast/AzuraCast#3066]
Recently, I installed your software through digital ocean on a vps. I have one playlist that I want to play at a specific time. I have it scheduled and it is enabled. I also have another playlist that is supposed to rotate throughout the day. On the playlist I want to play, I have it set to interrupt the playing songs to broadcast at that time. No matter what I do, it NEVER broadcasts at the right time. It doesn't even seem to queue it for the next song. What are your thoughts?

**Comment by SlvrEagle23** [comment]
@president-2020 Please see #2631.
