### ISSUE TITLE
live stream problems

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#3068]
I'm having a problem that happens with both icecast and shoutcast. I am broadcasting live and suddenly the broadcast of the auto dj takes me down and enters and soon after the live returns, and this happens several times in a live broadcast. Is there any configuration for this not to happen? Because my internet is very good and it always happens.

**Comment by Radio-Quergedacht** [comment]
Which version of azuracast are you using Because we don't have the problems

**Comment by Marcioghiraldelli** [comment]
I am using the latest stable version.
This problem has been happening for a long time, even using icecast or shoutcast. Is it possible to adjust? Because it keeps coming out live and entering auto dj always.

**Comment by emilio-pro** [comment]
I experienced the samen issue yesterday Durlinger my live show. Upgrading fixed the issue. In fact, it might have something to do with this action ‘ Temporarily revert live DJ crossfading ‘

**Comment by Radio-Quergedacht** [comment]
Wir Verwenden Version  v0.9.9, #767fb5d (2020-04-13 6:49) • Ansible • PHP 7.4 bei uns Geht alles

**Comment by diego-vieira** [comment]
@Marcioghiraldelli if your issue is resolved with the latest version, please consider closing the issue. Thanks

**Comment by picpakdog** [comment]
I have had this same issue with multiple servers, on the latest version. I've tried changing every setting I can think of to no avail, any ideas?

**Comment by SlvrEagle23** [comment]
@picpakdog I believe the original issue here was actually resolved, so this issue should likely be closed already but just hasn't been yet.

If you're having issues broadcasting to an AzuraCast instance, the one setting you should look into adjusting is the "DJ/Streamer buffer time" setting on the station profile, under the "AutoDJ" tab:

<img width="347" alt="2020-10-23 03_53_10-Edit Profile - AzuraCast" src="https://user-images.githubusercontent.com/6744885/96977899-54eecd00-14e3-11eb-95c1-9c52aa641ea4.png">

Note that when you change this, in order for the new setting to take effect you have to restart your station; you should see a "Restart Broadcasting" notification in the station's sidebar indicating that this needs to be done.

**Comment by picpakdog** [comment]
I've adjusted the buffer, I've disabled anything that could impact CPU (processing, crossfading, recording, etc) and it has had absolutely zero effect. And this has been after trying it on two separate servers, one slightly more powerful than the other. I'm at my wit's end on how to actually fix this. Here's what happens in the log when it drops:

```
2020/10/23 07:28:28 [m4bcc_radio_live_fallback:3] Switch to m4bcc_radio_requests_fallback with forgetful transition.
2020/10/23 07:28:28 [dummy:3] Source failed (no more tracks) stopping output...
2020/10/23 07:28:53 [m4bcc_radio_live_fallback:3] Switch to audio_to_stereo_7809 with transition.
```
