### ISSUE TITLE
how to setup program schedule in Azura

### ISSUE THREAD

**Issue by ssoseun** [AzuraCast/AzuraCast#3069]
Gooday, 
I started using Azura, i do real like it but the only thing i  couldn't do with is it to get the schedule program work. I will schedule and it will show but won't play the schedule playlist or program.
Can anyone show me steps to schedule 
Thanks

**Comment by dheatovwil** [comment]
So far the only way to make it works deterministically:

- Setup schedule item as usual
- At the advanced tab, tick the `Interrupt other songs to pay at scheduled time`
- Restart broadcast

The interrupt function won't let the current song by AutoDJ finish, and crossfade to your playlist right away.  I guess it's the only way to make it break the `default` playlist loop?

I suppose if there's another schedule item that ends precisely at `hh:mm`, you should be able to schedule another at `hh:mm+1` without the interruption.  I will try it out in a few days and update.
