### ISSUE TITLE
Local Development Environment Issues

### ISSUE THREAD

**Issue by bjarn** [AzuraCast/AzuraCast#3070]
**Using Docker installation method**
Yes

**AzuraCast version**
51a2292 

**Host Operating System**
MacOS Catalina

**Describe the bug**
Previously I was able to get the development environment running according to the docs. Sadly, this time it fails.
The setup script throws the following error:
`Directory "/var/azuracast/stations/azuratest_radio" was not created`
Also the Nginx container does not run correctly, it throws the following error:
`req: Can't open "/etc/nginx/certs/default.key" for writing, Read-only file system`

**To Reproduce**
1. Clone repositories:
```
git clone https://github.com/AzuraCast/AzuraCast.git
git clone https://github.com/AzuraCast/docker-azuracast-nginx-proxy.git
git clone https://github.com/AzuraCast/docker-azuracast-db.git
git clone https://github.com/AzuraCast/docker-azuracast-influxdb.git
git clone https://github.com/AzuraCast/docker-azuracast-redis.git
git clone https://github.com/AzuraCast/docker-azuracast-radio.git
```
2. Copy default files:
```
cp azuracast.dev.env azuracast.env
cp docker-compose.dev.yml docker-compose.yml
```
3. Modify the Environment File
4. docker-compose build
5. Spin up containers: docker-compose up -d (devdocs say to run in-container install first, but this does not work since mariadb, redis etc. are not running yet)
6. Run the install inside docker-compose run --user="azuracast" --rm web bash

**Expected behavior**
The development environment should boot successfully with the fixtures.

**Comment by K0FT3** [comment]
@bjarn ,I have same issue and I am using ubuntu droplet. I managed to make nginx work with deleting 

>       - ./util/local_ssl:/etc/nginx/certs:ro

from docker-compose.yml file that I copied from docker-compose-dev.yml file. But there is another issues after that.

I keep getting this error output from docker_web container logs

> In DoctrineReceiver.php line 62:
>                                                                                
>   An exception occurred while executing 'SELECT m.* FROM messenger_messages m  
>    WHERE (m.delivered_at is null OR m.delivered_at < ?) AND (m.available_at <  
>   = ?) AND (m.queue_name = ?) ORDER BY available_at ASC LIMIT 1 FOR UPDATE' w  
>   ith params ["2020-08-06 18:22:56", "2020-08-06 19:22:56", "default"]:        
>                                                                                
>   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.messen  
>   ger_messages' doesn't exist                                                  
>                                                                                
> 
> In AbstractMySQLDriver.php line 42:
>                                                                                
>   An exception occurred while executing 'SELECT m.* FROM messenger_messages m  
>    WHERE (m.delivered_at is null OR m.delivered_at < ?) AND (m.available_at <  
>   = ?) AND (m.queue_name = ?) ORDER BY available_at ASC LIMIT 1 FOR UPDATE' w  
>   ith params ["2020-08-06 18:22:56", "2020-08-06 19:22:56", "default"]:        
>                                                                                
>   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.messen  
>   ger_messages' doesn't exist                                                  
>                                                                                
> 
> In PDOStatement.php line 129:
>                                                                                
>   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.messen  
>   ger_messages' doesn't exist                                                  
>                                                                                
> 
> In PDOStatement.php line 127:
>                                                                                
>   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.messen  
>   ger_messages' doesn't exist                                                  
>                                                                                
> 
> queue:process [<runtime>]

I checked sql files to see if there is a messenger table etc but there is not. and I am using same version as yours completely.
Can someone refer to a working version of azuracast? or how can we solve this issue?

**Comment by SlvrEagle23** [comment]
@K0FT3 Have you run the setup process inside the container? As in, something like:

```bash
docker-compose run --user=azuracast --rm web azuracast_cli azuracast:setup --load-fixtures
```

...that should run DB migrations as well which will create the necessary tables.

**Comment by K0FT3** [comment]
@SlvrEagle23, yes I have done it but without load fixtures. And other steps like composer install. I can try it with load fixtures later on.

**Comment by K0FT3** [comment]
@SlvrEagle23 , When I try 

`azuracast_cli azuracast:setup --load-fixtures`

I am getting ok results until radio_stations section  And logs still show same errors. --load-fixtures option doesn't work.


```
Waiting for dependent services to go online...
 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

Setting Up InfluxDB
-------------------

Database created.
Retention policies updated.
Continuous queries created.
InfluxDB databases created.

Running Database Migrations
---------------------------


                                                                                
 [OK] Already at the latest version                                             
      ("App\Entity\Migration\Version20200711002451")                            
                                                                                


Generating Database Proxy Classes
---------------------------------


 Processing entity "App\Entity\Settings"
 Processing entity "App\Entity\Song"
 Processing entity "App\Entity\SongHistory"
 Processing entity "App\Entity\CustomField"
 Processing entity "App\Entity\StationMedia"
 Processing entity "App\Entity\Station"
 Processing entity "App\Entity\StationPlaylistMedia"
 Processing entity "App\Entity\StationMediaCustomField"
 Processing entity "App\Entity\StationPlaylist"
 Processing entity "App\Entity\StationStreamer"
 Processing entity "App\Entity\RolePermission"
 Processing entity "App\Entity\StationMount"
 Processing entity "App\Entity\StationRemote"
 Processing entity "App\Entity\StationWebhook"
 Processing entity "App\Entity\SftpUser"
 Processing entity "App\Entity\StationStreamerBroadcast"
 Processing entity "App\Entity\AuditLog"
 Processing entity "App\Entity\StationSchedule"
 Processing entity "App\Entity\Relay"
 Processing entity "App\Entity\StationPlaylistFolder"
 Processing entity "App\Entity\User"
 Processing entity "App\Entity\Listener"
 Processing entity "App\Entity\Analytics"
 Processing entity "App\Entity\ApiKey"
 Processing entity "App\Entity\MessengerMessage"
 Processing entity "App\Entity\Role"
 Processing entity "App\Entity\StationRequest"

 Proxy classes generated to "/var/azuracast/www_tmp/proxies"

Installing Data Fixtures
------------------------


In Station.php line 33:
                                                                       
  Directory "/var/azuracast/stations/azuratest_radio" was not created 
```


Here is the result of  setup without `--load-fixtures`

```
AzuraCast Setup
===============

Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...
 * Environment: Production
 * Installation Method: Docker

Waiting for dependent services to go online...
 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

Setting Up InfluxDB
-------------------

Database created.
Retention policies updated.
Continuous queries created.
InfluxDB databases created.

Running Database Migrations
---------------------------

[notice] Migrating up to App\Entity\Migration\Version20200711002451
[notice] finished in 98.9ms, used 24M memory, 1 migrations executed, 1 sql queries


Generating Database Proxy Classes
---------------------------------


 Processing entity "App\Entity\Settings"
 Processing entity "App\Entity\Song"
 Processing entity "App\Entity\SongHistory"
 Processing entity "App\Entity\CustomField"
 Processing entity "App\Entity\StationMedia"
 Processing entity "App\Entity\Station"
 Processing entity "App\Entity\StationPlaylistMedia"
 Processing entity "App\Entity\StationMediaCustomField"
 Processing entity "App\Entity\StationPlaylist"
 Processing entity "App\Entity\StationStreamer"
 Processing entity "App\Entity\RolePermission"
 Processing entity "App\Entity\StationMount"
 Processing entity "App\Entity\StationRemote"
 Processing entity "App\Entity\StationWebhook"
 Processing entity "App\Entity\SftpUser"
 Processing entity "App\Entity\StationStreamerBroadcast"
 Processing entity "App\Entity\AuditLog"
 Processing entity "App\Entity\StationSchedule"
 Processing entity "App\Entity\Relay"
 Processing entity "App\Entity\StationPlaylistFolder"
 Processing entity "App\Entity\User"
 Processing entity "App\Entity\Listener"
 Processing entity "App\Entity\Analytics"
 Processing entity "App\Entity\ApiKey"
 Processing entity "App\Entity\MessengerMessage"
 Processing entity "App\Entity\Role"
 Processing entity "App\Entity\StationRequest"

 Proxy classes generated to "/var/azuracast/www_tmp/proxies"

Reload System Data
------------------

Local cache flushed.

Refreshing All Stations
-----------------------


Restarting all radio stations...
--------------------------------

    0 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]


                                                                                
 [OK] AzuraCast installation complete!                                          
                                                                                
      Visit http://164.90.218.195 to complete setup.    
```

**Comment by bjarn** [comment]
@K0FT3 This seems like a different issue than I experience. Could you create a new one? Otherwise it gets bloated and hard to keep track on for Buster :-)

**Comment by SlvrEagle23** [comment]
@K0FT3 @bjarn I think you both might actually be dealing with the same issue, and I think the issue may be permissions-based.

Generally speaking, though, volumes created by Docker itself have the appropriate permissions set. I'm not sure why, in the case of either MacOS or Ubuntu, it's not doing that, especially since it does it for production AzuraCast instances without any issue.

As I mentioned in the other issue (#3074), the primary user operating within the Docker container has the username `azuracast` and UID `1000`, which typically corresponds to the first non-root user created on the Linux systems we use. It's possible that the issue here is caused by permissions not being set correctly, and simply chowning the respective directories would fix the issue.

I can likely test with Ubuntu 20.04 as a host OS later on (though we already do that on countless production instances, and those work fine), but I can't unfortunately test on MacOS as I don't have one.

**Comment by bjarn** [comment]
The issues have been resolved by using the latest commit https://github.com/AzuraCast/AzuraCast/commit/047ffd6eca042daeeb025d2555d4463d51586d03. 

Developer documentation was outdated and has been updated by @SlvrEagle23, when following these, my local environment started to work :-)
