### ISSUE TITLE
Question about icecast number of listeners unlimited

### ISSUE THREAD

**Issue by Radio-Quergedacht** [AzuraCast/AzuraCast#3071]
Azuracast Icecast number of listeners unlimited how to get that

**Comment by Vaalyn** [comment]
At the moment I think it's not possible to remove the `Maximum Listeners` setting from the IceCast config so the best way to achieve "unlimited" listeners would be to set the value of that setting to something like 9999999. While it's technically not unlimited in practice it's very unlikely that someone reaches a listener count that high.

**Comment by Radio-Quergedacht** [comment]
Thank you very much for this info
