### ISSUE TITLE
error during new installation of azuracast

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#3072]
**Using Docker installation method**

NO - (Ansible)
**AzuraCast version**

**Host Operating System**

Ubuntu 16.04

**Describe the bug**

newly installed AzuraCast Ansible installation but after the installation their is an error.  how to fixed this error please.

**To Reproduce**

**Expected behavior**

**Relevant Logs**

TASK [redis : Add Redis PPA repository] *****************************************************************************************************************************************************
ok: [localhost]

TASK [redis : Install Redis] ****************************************************************************************************************************************************************
ok: [localhost]

TASK [redis : Restart Redis service] ********************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service redis: host"}

RUNNING HANDLER [azuracast-user : send user notification] ***********************************************************************************************************************************

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=50   changed=24   unreachable=0    failed=1    skipped=8    rescued=0    ignored=0

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Radio-Quergedacht** [comment]
i visit them to use ubuntu 04/18 or debian 10 
Which server provider are you with?
