### ISSUE TITLE
Local Development Initial Setup Issues

### ISSUE THREAD

**Issue by K0FT3** [AzuraCast/AzuraCast#3074]
**Using Docker installation method**
Yes

**AzuraCast version**
https://github.com/AzuraCast/AzuraCast/commit/a283f7d5ef9fdb6cb2d8eaac93e376f17cf6e099

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
The setup script throws the following error:

```
Installing Data Fixtures
------------------------


In Station.php line 33:
                                                                       
  Directory "/var/azuracast/stations/azuratest_radio" was not created  
                                                                       
```
Before this I wasn't able to start nginx server and that issue can be seen on #3070 .

**To Reproduce**
I did everything what [wiki](https://www.azuracast.com/developers/#setting-up-a-local-environment) says and I was able to make it work until code:
`azuracast_cli azuracast:setup --load-fixtures`

before this I needed to delete  code:
 `- ./util/local_ssl:/etc/nginx/certs:ro`
from docker-compose.yml to avoid nginx read-only filesystem error referenced at #3070 .

**Expected behavior**
Start live development server and see initialization page via browser

**Comment by SlvrEagle23** [comment]
@K0FT3 I do project development on Windows, but we run a huge number of production instances on Ubuntu servers, so I'm not sure why the development environment wouldn't be working correctly.

Generally in cases like this I suspect it's a permissions error. The `azuracast` user inside the Docker container is user ID `1000`, i.e. the first non-root user inside the container; for single-user desktop Linux installations, your user ID should be the same, which should prevent any problems from happening, but if you aren't UID 1000, you may need to chown any respective directories.

**Comment by SlvrEagle23** [comment]
@K0FT3 I believe this is resolved as of our updated development instructions.
