### ISSUE TITLE
Embed Player error

### ISSUE THREAD

**Issue by Reaktiv4** [AzuraCast/AzuraCast#3079]
The console shows an error
![embed player](https://user-images.githubusercontent.com/49731123/89838238-66c30400-db73-11ea-8653-2917d4f48188.JPG)
Although everything works on the site, but what caused the error?

**Comment by SlvrEagle23** [comment]
@Reaktiv4 I'm not seeing this error locally, and I think it might've been fixed in a recent version of AzuraCast. What version are you running (and are you using Ansible or Docker)?

**Comment by Reaktiv4** [comment]
Docker - v0.10.3
Is this the latest version?

**Comment by SlvrEagle23** [comment]
@Reaktiv4 It is, but if you're on the 0.10.3 release version, you don't have the latest fixes we've incorporated into the "rolling release" versions. You may still benefit from updating.

**Comment by Reaktiv4** [comment]
Updated, did not help. Strange error ..
