### ISSUE TITLE
How to make CSS background image redirect to home page

### ISSUE THREAD

**Issue by pawelzet** [AzuraCast/AzuraCast#3080]
Hello,

Im new in azuracast. I would like to make my background image a clickable link and possible to redirect to my homepage of azuracast station. I know it is possible with html and css with sth like this:
`
<a class="photo" href="website.net/link" title="photo" id="photo">photo</a>`

but i have access to .html only via docker exec, which would be changed after next compose of a container. Is it possible in custom branding with JS ans CSS? 
My CSS:
```
body.page-minimal {
    background: #edecec url('https://i.imgur.com/LEHsuAp.png') center center;
    background-repeat: no-repeat;
    background-color: white;
    background-size: contain;

```
}

**Comment by YosefAdPro** [comment]
@pawelzet 
It's possible
System Administration  > Custom Branding....
