### ISSUE TITLE
Icecast Header/Banner

### ISSUE THREAD

**Issue by DamonOnYT** [AzuraCast/AzuraCast#3081]
Hello,

I'm looking to bring back the banner/header normally seen on Icecast if you were to run it by itself. Is there any modifications I can make to have it back?

**Comment by SlvrEagle23** [comment]
@DamonOnYT As far as I know, this has always been an issue with our fork of Icecast (the KH branch); it doesn't come with the Icecast logo or branding. I'm not really sure why.

Theoretically it would be possible to get it back via mounting the missing files via Docker Compose, but I would think the effort involved would be somewhat greater than the resulting benefit.

I can see about adding the logo and branding back in our own "downstream" build of Icecast-KH.

**Comment by Radio-Quergedacht** [comment]
That has to do with the SSL. If you call up the stream without SSL, everything is there in Dan you have to call ip: port like this The reason that SSL does not work is that KH-Icecast is not officially SSL-capable
