### ISSUE TITLE
Liquidsoap not running and unable to update azuracast

### ISSUE THREAD

**Issue by s7ntax** [AzuraCast/AzuraCast#3082]
Last weekend Azuracast crashed, actually I think systemd crashed as the ircd i run also stopped. 

I did a sudo reboot of my VPS and when it restarted i also had to manually restart docker daemon. 

I have also updated Azuracast successfully to the latest version.

Liquidsoap was running ok but then I tried to restart liquidsoap in Azuracast get the following error and now i cannot get it to start at all.

```
Liquidsoap encountered an error
2020/08/12 23:21:13 [threads:3] Waiting for queue threads to terminate...
2020/08/12 23:21:13 [threads:3] Queues shut down
2020/08/12 23:21:13 [server:3] Closing socket.
2020/08/12 23:21:13 [main:3] Cleaning downloaded files...
2020/08/12 23:21:13 [main:3] Freeing memory...
2020/08/12 23:21:13 >>> LOG END
```

I'm unsure if this is a docker issue, liquidsoap or even something deeper ie systemd.

Any ideas whats wrong here?

Another error i've seen pop up when skipping a song is `Telnet failure: Connection refused (111)`

**Comment by s7ntax** [comment]
I worked it out, i made a playlist with a remote URL mp3 file, disabled the other playlists and enabled the new one. Then liquidsoap wouldn't play it so when i restarted liquidsoap it failed to restart giving the errors. So it didn't like the remote mp3 file in the playlist, not sure why as i've done it before and it worked.

**Comment by SlvrEagle23** [comment]
@s7ntax That's been known to happen with remote URL playlists, but should've been fixed in more recent revisions. What version of AzuraCast are you running, and are you using the Docker or Ansible install type?

**Comment by s7ntax** [comment]
I am running Docker version 19.03.12, build 48a66213fe and i have Azuracast updated to v0.10.3, #9811fbb (2020-06-22 4:38)
