### ISSUE TITLE
Waiting List does not show the right time "planned at"

### ISSUE THREAD

**Issue by nicolas5296** [AzuraCast/AzuraCast#3083]
Hey there,

today we find a problem with the waiting list. The waiting list plan every song on the 12. August at 13:09 - thats the time of our installation. But now we have the 13. August and 10 o' clock. Have a look at my screenshot.

https://prnt.sc/tytvhm

How can we fix that error? It seems that this is the problem for our server. We have 6 playlists but they won't shuffle. Our Jingles were playing 24/7. Thats an error because we take the settings to play every 3 songs.

Docker Version on Debian 10

Do you have an idea?
Best regards from germany,
Nicolas

**Comment by SlvrEagle23** [comment]
@nicolas5296 As this is an issue with the scheduler, it is likely covered under #2631.
