### ISSUE TITLE
Problem with dial: dial tcp IP:8086 Connect Resufsed is sleeping 1s

### ISSUE THREAD

**Issue by danielrodrigotest** [AzuraCast/AzuraCast#3084]
O<!--
Docker Version:
Dear Azuracast, the purpose of this issue is to inform that I got many Problem with dial(s) and timeout after 1 minute. After that update, the website wasn't working or loads too slow. Any help, would be great 
Thanks for all Azuracast :)

**AzuraCast version**

**Host Operating System**
Ubuntu 20.4

**Describe the bug**
2020/08/14 04:27:51 Problem with dial: dial tcp 172.18.0.3:8086: connect: connection refused. Sleeping 1s
2020/08/14 04:27:52 Problem with dial: dial tcp 172.18.0.3:8086: connect: connection refused. Sleeping 1s
2020/08/14 04:27:53 Problem with dial: dial tcp 172.18.0.3:8086: connect: connection refused. Sleeping 1s
2020/08/14 04:27:54 Problem with dial: dial tcp 172.18.0.3:8086: connect: connection refused. Sleeping 1s
2020/08/14 04:27:55 Problem with dial: dial tcp 172.18.0.3:8086: connect: connection refused. Sleeping 1s
2020/08/14 04:27:56 Problem with dial: dial tcp 172.18.0.3:8086: connect: connection refused. Sleeping 1s
2020/08/14 04:27:57 Problem with dial: dial tcp 172.18.0.3:8086: connect: connection refused. Sleeping 1s
2020/08/14 04:27:58 Problem with dial: dial tcp 172.18.0.3:8086: connect: connection refused. Sleeping 1s
2020/08/14 04:27:59 Problem with dial: dial tcp 172.18.0.3:8086: connect: connection refused. Sleeping 1s
2020/08/14 04:27:59 Timeout after 1m30s waiting on dependencies to become available: [tcp://mariadb:3306 tcp://influxdb:8086 tcp://redis:6379]
azuracast_mariadb_1 is up-to-date
azuracast_stations is up-to-date
azuracast_redis_1 is up-to-date
azuracast_influxdb_1 is up-to-date
Creating azuracast_web ... done
Creating azuracast_nginx_proxy_1 ... done
Creating azuracast_nginx_proxy_letsencrypt_1 ... done
Update complete!
**To Reproduce**

**Comment by nicolas5296** [comment]
This message is usually not an error. It's the result of a safety check we add into the Docker images, so they won't start up fully until other services (in this case, MariaDB, InfluxDB and Redis) are fully started and ready to accept connections. The "web" container periodically pings those services until they're fully started up, and if the service is still starting up, it will produce this "connection refused" error message, then retry again a second later.

If your "web" container never starts up, this could mean there is an error with one of your other containers
(mariadb, influxdb, or redis). You can see what may be causing the problem by running 

`docker-compose logs -f servicename `

where servicename is one of the services listed in the previous sentence.
