### ISSUE TITLE
After the following song

### ISSUE THREAD

**Issue by Radio-Quergedacht** [AzuraCast/AzuraCast#3085]
Because that's how I get the current song

`<?php
	$station = "2";

	$json_station = file_get_contents("https://domain.eu/api/nowplaying/".$station);

	$obj_station = json_decode($json_station);

	echo   $obj_station->now_playing->song->text
?>`

How do I get the next song  display

**Comment by Vaalyn** [comment]
To access the text of the next song you'd need to access `$obj_station->playing_next->song->text` instead of `$obj_station->now_playing->song->text`.

**Comment by Radio-Quergedacht** [comment]
`<?php
	$station = "2";

	$json_station = file_get_contents("https://domain.eu/api/nowplaying/".$station);

	$obj_station = json_decode($json_station);

	echo $obj_station->play_next->song->text	
?>
`
everything stays white, see link https://radio-quergedacht.fm/wp-content/plugins/azuracast/main/nexttietel.php here

**Comment by Vaalyn** [comment]
Look at your code `$obj_station->play_next...` and what I wrote: `$obj_station->playing_next...`

**Comment by Radio-Quergedacht** [comment]
Thank you very much, now it worked
