### ISSUE TITLE
Admin account is lost?

### ISSUE THREAD

**Issue by Pascal-Kusters** [AzuraCast/AzuraCast#3086]
**Using Docker installation method**

Yes

**AzuraCast version**

latest release

**Host Operating System**

Ubuntu 18 

**Describe the bug**

When logging in with my administraor account, I got a password error message "password" incorrect on all my devices.

I gave a docker command via SSH to reset a password, then I got the message "[error account not found]".

I do have a user account with a different email address, but it does not have admin rights.

1. How can I regain access to my admin account?

2. How can I convert my user account to admin rights?

I have a recent backup, but don't want to use it right away.

**Comment by Vaalyn** [comment]
You could first check if the admin user account exists in the database by entering the DB container and doing a select on the DB table:

1. `docker exec -it azuracast_mariadb_1 bash`
2. `mysql -uazuracast -pazur4c457`
3. `USE azuracast;`
4. `SELECT * FROM users;`

That should give you a list of all the entries in the users table. You can then check if the e-mail of your admin account matches the e-mail that you entered into the password reset command.

To answer your 2. question you can use the `azuracast:account:set-administrator <email>` command to promote your other account to an admin account.
