### ISSUE TITLE
Is possible to install AzuraCast with another icecast and spip in the same server?

### ISSUE THREAD

**Issue by kehuelga** [AzuraCast/AzuraCast#3089]
Hi,

We have a server with icecast and spip (it uses mariadb).

Now we want to install AzuraCast but it replace my original icecast.

Thanks!

kehuelga

**Comment by Radio-Quergedacht** [comment]
you have to install AzuraCast on a different server

**Comment by kehuelga** [comment]
How can I install another server? You mean another virtual server?
