### ISSUE TITLE
Top listners by country, by browser, by os

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#309]
Hello,

It is possible to add a feature in listners stats like:
Top listners by country, by browser, by os

Thank you

**Comment by jonikane** [comment]
And by top city, and player too

**Comment by surihost** [comment]
Yes would like to see this option how it is done on centovacast statistics.

**Comment by jonikane** [comment]
It is possible this feature request?

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38782/show-top-listeners-by-countrybrowseros-where-possible
