### ISSUE TITLE
Myself and my Station Presenters can not go live..

### ISSUE THREAD

**Issue by KylePython** [AzuraCast/AzuraCast#3090]
Hello, I done an update early hours this morning,
since then it seems like I can't go live on my radio.
I own an online radio station and it's crucial that me and my team can get on air.

This is the error I'm getting

2020/08/17 16:46:09 [lang:3] AzuraCast DJ Auth Response: Error: Typed property App\Entity\Repository\StationStreamerRepository::$scheduler must not be accessed before initialization on /var/azuracast/www/src/Entity/Repository/StationStreamerRepository.php L50
2020/08/17 16:46:33 [lang:3] Authenticating DJ: kyle

Hope to hear back.
TIA

**Comment by ogrenci01** [comment]
Hi @KylePython ;

I have same issue. #3088 

There is no solution I have found yet. I am sorry. I'm waiting for AzuraCast Team.

**Comment by KylePython** [comment]
@ogrenci01 damn -

It won't even let me restore any of my previous back ups..

I've also noticed that I can actually connect to the Source Password.
But the personal Streamer accounts cannot connect.

**Comment by ogrenci01** [comment]
Hi @KylePython ;

I have more than one station. We have not been able to broadcast live for about 11 hours. We just have to wait.

**Comment by SlvrEagle23** [comment]
@ogrenci01 @KylePython This should be fixed as of the latest update pushed a few minutes ago. Thank you for the report.

**Comment by ogrenci01** [comment]
Hi @SlvrEagle23 ;

Nice work bro. A lot of thanks. You're great.

**Comment by KylePython** [comment]
@SlvrEagle23 You're a diamond, it's all working again now.
Thank you for working on the fix!
