### ISSUE TITLE
Metadaten WebHooks für Radio.de

### ISSUE THREAD

**Issue by Radio-Quergedacht** [AzuraCast/AzuraCast#3091]
`
# Den aktuellen Track Ihres Senders in unserem System aktualisieren
# Method GET
http://api.radio.de/info/v2/pushmetadata/playingsong?broadcast=<bro
adcastsubdomain>&title=Song+Title&artist=Song+Artist&album=Album+Ti
tle&apikey=<ihrApiKey>
 Sollte der aktuelle Track ein Werbespot sein, bitte als solchen
kennzeichnen
Method GET
http://api.radio.de/info/v2/pushmetadata/playingsong?broadcast=<bro
adcastsubdomain>&commercial=true&apikey=<ihrApiKey>

`

**Comment by SlvrEagle23** [comment]
@Radio-Quergedacht Can you explain the nature of this problem in English please?

**Comment by Radio-Quergedacht** [comment]
Meta Data Push API
You can interpret your new title information via this API interface
The song title of the currently played title) is transmitted to our system in time for your listener
on radio.de you can always see the song you are playing.
Would radio.de be using the audio stream metadata?
The purpose of using your metadata is to inform the user that your
Listen to senders via radio.de products. We offered the service to the user
The following points show you see the song he is currently listening to recognize stations:
● In the player on the website
● In the station lists on the website and in the apps
● In the playlist (history of the songs played)
Such as. from iTunes) such as Albums
Cover and store links, songs on iTunes, Amazon
etc. etc. to look for. This is how we create an even more useful user experience.
Access for senders when using the M eta Dat a Push API
- Your current song will also be correct and heard in sender lists,
if your sender is not currently in the radio.de player.
- Our Push API enables the sophisticated display of the songs using
of different dates like album covers.
- The playlists displayed belong to the titles being played. Metadata, die
must be heard as advertising blocks, so can from the history displayed
of the songs played can be filtered out.
If we don't have any metadata from the push API available, we'll die
Read metadata directly from the audio stream. But we don't have any this fall
Certainty about the content of the metadata of the various senders as they are
are not uniformly formatted and we are unable to hear them correctly
will be

**Comment by Radio-Quergedacht** [comment]
How-To

Implementation is very simple:
# Update the current track of your station in our system
# Method GET
`
http://api.radio.de/info/v2/pushmetadata/playingsong?broadcast=<bro
adcastsubdomain>&title=Song+Title&artist=Song+Artist&album=Album+Ti
tle&apikey=<ihrApiKey>
`

# If the current track is a commercial, please as such
mark
# Method GET

`
http://api.radio.de/info/v2/pushmetadata/playingsong?broadcast=<bro
adcastsubdomain>&commercial=true&apikey=<ihrApiKey>

`

The broadcast subdomain is the subdomain of your radio station on radio.de. Example:
http://ihrsender.radio.de - “Ihrsender” is your subdomain on radio.de.
Details
Input
Parameter description
title The song name
artist The interpreter
album The album
Please use the "+" sign instead of spaces.
Special characters must be transmitted URL encoded.

**Comment by Radio-Quergedacht** [comment]
can you integrate that into azuracast?

**Comment by LordHelmchen666** [comment]
Hi @SlvrEagle23,
it is similar to TuneIN http://air.radiotime.com/Playing.ashx?partnerId=xxx&partnerKey=xxx&id=s116534&title=Bad+Romance&artist=Lady+Gaga

**Comment by Radio-Quergedacht** [comment]
is not from TuneIN is from Radio.de
Here the link to PDF sory is unfortunately in German
https://radio-quergedacht.fm/radio.de-MDPAPI_v3_deutsch.pdf

**Comment by sidney65** [comment]
Hi @SlvrEagle23 , (and all),

Yes is similar to TuneIn directory . 
Radio.de is a directory for radio of the world ; for display title track of station , they send a api key and the method to use it ; Radio-Quergedacht have copy here the pdf method they send . 
I think @Radio-Quergedacht want a web hook to send meta data to radio.de .
I have try to do it with general web hook but it's don't work . I think it's a good idea and not difficult to set up from the existing web hooks but i'm not a programmer ;-).
If someone have do it and can send it the solution ; or if you can implement in a update ...
Thanks

**Comment by Radio-Quergedacht** [comment]
@sidney65  Yes, we would like a web hook to send metadata to radio.de. no unfortunately it is not possible with the existing web hooks

**Comment by SlvrEagle23** [comment]
@Radio-Quergedacht Seems simple enough to integrate on our end...is this a popular service?

It may be an excellent candidate for a plugin-based webhook system.

**Comment by Radio-Quergedacht** [comment]
@SlvrEagle23 Radio.de is very popular and a lot of radio stations are tuned into no more radio stations would be nice if there would be a webhook, please call me as a test person

**Comment by Moonbase59** [comment]
@BusterNeece Confirming both TuneIn.com and Radio.de are extremely popular in Germany.

**Comment by LordHelmchen666** [comment]
@BusterNeece 
Based on your TuneIn Webhook i changed for radio.de. Can you take a look and then maybe add it when its ok? And where is the form i have to change?
```
<?php

declare(strict_types=1);

namespace App\Webhook\Connector;

use App\Entity\Api\NowPlaying\NowPlaying;
use App\Entity\Enums\WebhookTriggers;
use App\Entity\Station;
use App\Entity\StationWebhook;

final class RadioDe extends AbstractConnector
{
    public const NAME = 'radiode';

    protected function webhookShouldTrigger(StationWebhook $webhook, array $triggers = []): bool
    {
        return in_array(WebhookTriggers::SongChanged->value, $triggers, true);
    }

    /**
     * @inheritDoc
     */
    public function dispatch(
        Station $station,
        StationWebhook $webhook,
        NowPlaying $np,
        array $triggers
    ): void {
        $config = $webhook->getConfig();

        if (empty($config['broadcastsubdomain']) || empty($config['apikey'])) {
            throw $this->incompleteConfigException(self::NAME);
        }

        $this->logger->debug('Dispatching RadioDe AIR API call...');

        $response = $this->httpClient->get(
            'https://api.radio.de/info/v2/pushmetadata/playingsong',
            [
                'query' => [
                    'broadcastsubdomain' => $config['broadcastsubdomain'],
                    'apikey' => $config['apikey'],
                    'id' => $config['station_id'],
                    'title' => $np->now_playing?->song?->title,
                    'artist' => $np->now_playing?->song?->artist,
                    'album' => $np->now_playing?->song?->album,
                ],
            ]
        );

        $this->logger->debug(
            sprintf('RadioDe returned code %d', $response->getStatusCode()),
            ['response_body' => $response->getBody()->getContents()]
        );
    }
}
```
