### ISSUE TITLE
Problem at installation of AzuraCast with Ansible on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by adx74** [AzuraCast/AzuraCast#3093]
Hello, i try to install AzuraCast with Ansible because Docker doesn't work, and i have this problem.
I'm on Ubuntu 16.04 LTS.
Thanks by advance

root@euve270551:~# cd /var/azuracast/www
root@euve270551:/var/azuracast/www# ./install.sh
Checking for Ansible: install ok installed
Installing AzuraCast (Environment: production)

PLAY [all] *************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
[DEPRECATION WARNING]: Distribution Ubuntu 16.04 on host localhost should use /usr/bin/python3, but is using
/usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using
the discovered platform python for this host. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This feature
 will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
ok: [localhost]

TASK [init : debug] ****************************************************************************************************
ok: [localhost] => {
    "msg": "Running Ansible on localhost with OS Ubuntu xenial 16.04 x86_64 (production)"
}

TASK [init : fail] *****************************************************************************************************
skipping: [localhost]

TASK [init : fail] *****************************************************************************************************
skipping: [localhost]

TASK [init : Add multiverse repository] ********************************************************************************
ok: [localhost] => (item=deb http://archive.ubuntu.com/ubuntu xenial multiverse)
ok: [localhost] => (item=deb-src http://archive.ubuntu.com/ubuntu/  xenial multiverse)
ok: [localhost] => (item=deb http://archive.ubuntu.com/ubuntu xenial-updates multiverse)
ok: [localhost] => (item=deb-src http://archive.ubuntu.com/ubuntu/  xenial-updates multiverse)

TASK [init : Update apt] ***********************************************************************************************
ok: [localhost]

TASK [init : Install system packages] **********************************************************************************
ok: [localhost]

TASK [init : Install Focal Packages (20.04)] ***************************************************************************
skipping: [localhost]

TASK [init : Install Bionic Packages (18.04 only)] *********************************************************************
skipping: [localhost]

TASK [init : Install Xenial Packages (16.04 only)] *********************************************************************
ok: [localhost]

TASK [init : Update pip components] ************************************************************************************
ok: [localhost]

TASK [azuracast-user : Generate AzuraCast Password] ********************************************************************
changed: [localhost]

TASK [azuracast-user : Create Groups] **********************************************************************************
ok: [localhost] => (item=www-data)
ok: [localhost] => (item=admin)

TASK [azuracast-user : Create AzuraCast User] **************************************************************************
changed: [localhost]

TASK [azuracast-user : Modify www-data User] ***************************************************************************
ok: [localhost]

TASK [azuracast-config : Write environment configuration file] *********************************************************
ok: [localhost]

TASK [azuracast-config : Set up environment file] **********************************************************************
ok: [localhost]

TASK [azuracast-config : Set Permissions on Base App Folder] ***********************************************************
ok: [localhost] => (item=/var/azuracast)

TASK [azuracast-config : Clear temp directory] *************************************************************************
changed: [localhost]

TASK [azuracast-config : Create System Folders] ************************************************************************
changed: [localhost] => (item=/var/azuracast/www_tmp)
changed: [localhost] => (item=/var/azuracast/www_tmp/proxies)
ok: [localhost] => (item=/var/azuracast/stations)
ok: [localhost] => (item=/var/azuracast/geoip)
ok: [localhost] => (item=/var/azuracast/dbip)
ok: [localhost] => (item=/var/azuracast/backups)
ok: [localhost] => (item=/var/azuracast/servers)
ok: [localhost] => (item=/var/azuracast/servers/shoutcast2)
changed: [localhost] => (item=/var/azuracast/servers/icecast2)

TASK [azuracast-radio : Install IceCast-KH-AC Dependencies] ************************************************************
ok: [localhost]

TASK [azuracast-radio : Download IceCast-KH-AC Source] *****************************************************************
ok: [localhost]

TASK [azuracast-radio : Extract IceCast-KH-AC Source] ******************************************************************
changed: [localhost]

TASK [azuracast-radio : Build IceCast-KH-AC] ***************************************************************************
changed: [localhost]

TASK [azuracast-radio : Clear OPAM directory] **************************************************************************
changed: [localhost]

TASK [azuracast-radio : Add OPAM/OCaml Repository] *********************************************************************
ok: [localhost]

TASK [azuracast-radio : Install Liquidsoap Dependencies] ***************************************************************
ok: [localhost]

TASK [azuracast-radio : Initialize OPAM - This takes a while...] *******************************************************
changed: [localhost]

TASK [azuracast-radio : Initialize OPAM (Focal)] ***********************************************************************
skipping: [localhost]

TASK [azuracast-radio : Build and Install Liquidsoap] ******************************************************************
changed: [localhost]

TASK [azuracast-radio : Link Liquidsoap binary (Xenial/Bionic)] ********************************************************
ok: [localhost]

TASK [azuracast-radio : Link Liquidsoap binary (Focal)] ****************************************************************
skipping: [localhost]

TASK [azuracast-radio : Add Audiowaveform PPA] *************************************************************************
ok: [localhost]

TASK [azuracast-radio : Install Audiowaveform] *************************************************************************
ok: [localhost]

TASK [Install supervisord from repo] ***********************************************************************************
ok: [localhost]

TASK [Change supervisord configuration] ********************************************************************************
ok: [localhost]

TASK [Remove old core supervisord configuration] ***********************************************************************
ok: [localhost]

TASK [supervisord : Kill legacy radio processes (if upgrading from older version)] *************************************
skipping: [localhost]

TASK [Trigger manual restart of supervisord (if not already running)] **************************************************
skipping: [localhost]

TASK [Uninstall web server packages that may conflict with nginx] ******************************************************
ok: [localhost]

TASK [Unhold nginx-related packages for updates] ***********************************************************************
ok: [localhost] => (item=nginx)
ok: [localhost] => (item=nginx-common)
ok: [localhost] => (item=nginx-extras)

TASK [Remove any older nginx] ******************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "'apt-get remove 'nginx' 'nginx-common' 'nginx-extras'' failed: E: Sub-process /usr/bin/dpkg returned an error code (1)\n", "rc": 100, "stderr": "E: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stderr_lines": ["E: Sub-process /usr/bin/dpkg returned an error code (1)"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following packages were automatically installed and are no longer required:\n  libluajit-5.1-2 libluajit-5.1-common\nUse 'apt autoremove' to remove them.\nThe following packages will be REMOVED:\n  nginx* nginx-common* nginx-extras*\n0 upgraded, 0 newly installed, 3 to remove and 0 not upgraded.\n1 not fully installed or removed.\nAfter this operation, 2100 kB disk space will be freed.\n(Reading database ... \r(Reading database ... 5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ... 20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ... 35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ... 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database ... 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database ... 95%\r(Reading database ... 100%\r(Reading database ... 39369 files and directories currently installed.)\r\nRemoving nginx (1.10.3-0ubuntu0.16.04.5) ...\r\nRemoving nginx-extras (1.10.3-0ubuntu0.16.04.5) ...\r\nRemoving nginx-common (1.10.3-0ubuntu0.16.04.5) ...\r\nPurging configuration files for nginx-common (1.10.3-0ubuntu0.16.04.5) ...\r\ndpkg: warning: while removing nginx-common, directory '/var/www/html' not empty so not removed\r\nProcessing triggers for man-db (2.7.5-1) ...\r\nSetting up docker-ce (5:19.03.12~3-0~ubuntu-xenial) ...\r\nJob for docker.service failed because the control process exited with error code. See \"systemctl status docker.service\" and \"journalctl -xe\" for details.\r\ninvoke-rc.d: initscript docker, action \"start\" failed.\r\n* docker.service - Docker Application Container Engine\r\n   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)\r\n   Active: activating (auto-restart) (Result: exit-code) since Tue 2020-08-18 16:03:04 UTC; 6ms ago\r\n     Docs: https://docs.docker.com\r\n  Process: 20125 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock \u001b[0;1;31m(code=exited, status=1/FAILURE)\u001b[0m\r\n Main PID: 20125 (code=exited, status=1/FAILURE)\r\ndpkg: error processing package docker-ce (--configure):\r\n subprocess installed post-installation script returned error exit status 1\r\nErrors were encountered while processing:\r\n docker-ce\r\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following packages were automatically installed and are no longer required:", "  libluajit-5.1-2 libluajit-5.1-common", "Use 'apt autoremove' to remove them.", "The following packages will be REMOVED:", "  nginx* nginx-common* nginx-extras*", "0 upgraded, 0 newly installed, 3 to remove and 0 not upgraded.", "1 not fully installed or removed.", "After this operation, 2100 kB disk space will be freed.", "(Reading database ... ", "(Reading database ... 5%", "(Reading database ... 10%", "(Reading database ... 15%", "(Reading database ... 20%", "(Reading database ... 25%", "(Reading database ... 30%", "(Reading database ... 35%", "(Reading database ... 40%", "(Reading database ... 45%", "(Reading database ... 50%", "(Reading database ... 55%", "(Reading database ... 60%", "(Reading database ... 65%", "(Reading database ... 70%", "(Reading database ... 75%", "(Reading database ... 80%", "(Reading database ... 85%", "(Reading database ... 90%", "(Reading database ... 95%", "(Reading database ... 100%", "(Reading database ... 39369 files and directories currently installed.)", "Removing nginx (1.10.3-0ubuntu0.16.04.5) ...", "Removing nginx-extras (1.10.3-0ubuntu0.16.04.5) ...", "Removing nginx-common (1.10.3-0ubuntu0.16.04.5) ...", "Purging configuration files for nginx-common (1.10.3-0ubuntu0.16.04.5) ...", "dpkg: warning: while removing nginx-common, directory '/var/www/html' not empty so not removed", "Processing triggers for man-db (2.7.5-1) ...", "Setting up docker-ce (5:19.03.12~3-0~ubuntu-xenial) ...", "Job for docker.service failed because the control process exited with error code. See \"systemctl status docker.service\" and \"journalctl -xe\" for details.", "invoke-rc.d: initscript docker, action \"start\" failed.", "* docker.service - Docker Application Container Engine", "   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)", "   Active: activating (auto-restart) (Result: exit-code) since Tue 2020-08-18 16:03:04 UTC; 6ms ago", "     Docs: https://docs.docker.com", "  Process: 20125 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock \u001b[0;1;31m(code=exited, status=1/FAILURE)\u001b[0m", " Main PID: 20125 (code=exited, status=1/FAILURE)", "dpkg: error processing package docker-ce (--configure):", " subprocess installed post-installation script returned error exit status 1", "Errors were encountered while processing:", " docker-ce"]}

RUNNING HANDLER [azuracast-user : send user notification] **************************************************************

PLAY RECAP *************************************************************************************************************
localhost                  : ok=33   changed=9    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0

**Comment by Radio-Quergedacht** [comment]
16.04 
is also very old

**Comment by adx74** [comment]
> 16.04
> is also very old

yup but is the most recent version on my VPS, i can't set a most recent version. @Radio-Quergedacht

**Comment by SlvrEagle23** [comment]
@adx74 Ansible is not officially supported because of the wide variety of configurations of servers that are shipped by VPS/hosting providers. In your case, it appears your existing nginx installation is having a problem with being uninstalled by the AzuraCast installer, and just looking at the error message doesn't give me enough information to know exactly why that's happening.

I would recommend, if it's at all possible, for you to consider using a different host or using the Docker installation method.
