### ISSUE TITLE
I have no file called: /var/azuracast/www/util/cli.php

### ISSUE THREAD

**Issue by Crafteri** [AzuraCast/AzuraCast#3095]
How am I supposed to control the command line interface if it didn't make that file? How can I fix this?

Also, when does the Ansible version start up? At system startup or a command?

**Comment by Crafteri** [comment]
I heard that `node-sass` does not publish arm64 releases yet. That explains it since I am using a Raspberry Pi 3. I am missing all the .php -files.

This thread might give some answers in a while:
https://github.com/AzuraCast/AzuraCast/issues/3028

**Comment by SlvrEagle23** [comment]
@Crafteri Are you seeing a reference in our documentation that points to that path? That's an outdated path that we no longer use. The new path to performing CLI updates on Ansible installations is:

```
php /var/azuracast/www/bin/console [command-name]
```
