### ISSUE TITLE
Let's encrypt not showing SSL

### ISSUE THREAD

**Issue by themadcap1976** [AzuraCast/AzuraCast#3099]
**Using Docker installation method**
yes

**AzuraCast version**
v0.10.3, #9811fbb (2020-06-22 4:38) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
ran ./docker.sh letsencrypt-create, it runs but site doesn't show ssl

**Relevant Logs**
Attaching to azuracast_nginx_proxy_letsencrypt_1
nginx_proxy_letsencrypt_1  | Info: Custom Diffie-Hellman group found, generation skipped.
nginx_proxy_letsencrypt_1  | Reloading nginx proxy (2e8d6c08f7271a3032d3dd03cf8837742274f3400b8b0bd53914711098cce215)...
nginx_proxy_letsencrypt_1  | 2020/08/20 14:25:21 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx_proxy_letsencrypt_1  | 2020/08/20 14:25:21 [notice] 36#36: signal process started
nginx_proxy_letsencrypt_1  | 2020/08/20 14:25:21 Generated '/app/letsencrypt_service_data' from 10 containers
nginx_proxy_letsencrypt_1  | 2020/08/20 14:25:21 Running '/app/signal_le_service'
nginx_proxy_letsencrypt_1  | 2020/08/20 14:25:21 Watching docker events
nginx_proxy_letsencrypt_1  | 2020/08/20 14:25:21 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
nginx_proxy_letsencrypt_1  | /etc/nginx/certs/sail.yachtrockmiami.com /app
nginx_proxy_letsencrypt_1  | Reloading nginx proxy (2e8d6c08f7271a3032d3dd03cf8837742274f3400b8b0bd53914711098cce215)...
nginx_proxy_letsencrypt_1  | 2020/08/20 14:25:21 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx_proxy_letsencrypt_1  | 2020/08/20 14:25:21 [notice] 56#56: signal process started
nginx_proxy_letsencrypt_1  | Creating/renewal sail.yachtrockmiami.com certificates... (sail.yachtrockmiami.com)
nginx_proxy_letsencrypt_1  | Enter PEM pass phrase:
nginx_proxy_letsencrypt_1  | simp_le couldn't load a key from key.pem; the file might be empty or corrupt.
nginx_proxy_letsencrypt_1  |
nginx_proxy_letsencrypt_1  | Debugging tips: -v improves output verbosity. Help is available under --help.
nginx_proxy_letsencrypt_1  | /app
nginx_proxy_letsencrypt_1  | Sleep for 3600s
nginx_proxy_letsencrypt_1  | /etc/nginx/certs/sail.yachtrockmiami.com /app
nginx_proxy_letsencrypt_1  | Creating/renewal sail.yachtrockmiami.com certificates... (sail.yachtrockmiami.com)
nginx_proxy_letsencrypt_1  | Enter PEM pass phrase:
nginx_proxy_letsencrypt_1  | simp_le couldn't load a key from key.pem; the file might be empty or corrupt.
nginx_proxy_letsencrypt_1  |
nginx_proxy_letsencrypt_1  | Debugging tips: -v improves output verbosity. Help is available under --help.
nginx_proxy_letsencrypt_1  | /app
nginx_proxy_letsencrypt_1  | Sleep for 3600s
nginx_proxy_letsencrypt_1  | /etc/nginx/certs/sail.yachtrockmiami.com /app
nginx_proxy_letsencrypt_1  | Creating/renewal sail.yachtrockmiami.com certificates... (sail.yachtrockmiami.com)
nginx_proxy_letsencrypt_1  | Enter PEM pass phrase:
nginx_proxy_letsencrypt_1  | simp_le couldn't load a key from key.pem; the file might be empty or corrupt.
nginx_proxy_letsencrypt_1  |
nginx_proxy_letsencrypt_1  | Debugging tips: -v improves output verbosity. Help is available under --help.
nginx_proxy_letsencrypt_1  | /app
nginx_proxy_letsencrypt_1  | Sleep for 3600s

What am I missing?

**Comment by xifi-kif** [comment]
` nginx_proxy_letsencrypt_1 | simp_le couldn't load a key from key.pem; the file might be empty or corrupt.`

I would search for the key.pem file and rename it. Then run again the letsencrypt docker command.

**Comment by themadcap1976** [comment]
> ` nginx_proxy_letsencrypt_1 | simp_le couldn't load a key from key.pem; the file might be empty or corrupt.`
> 
> I would search for the key.pem file and rename it. Then run again the letsencrypt docker command.

I have a countless number of key.pem files in the system. What would I rename it to?

**Comment by SlvrEagle23** [comment]
@themadcap1976 The system expects the certificates/keys to be named `domain.com.crt` and `domain.com.key` respectively.

**Comment by themadcap1976** [comment]
> @themadcap1976 The system expects the certificates/keys to be named `domain.com.crt` and `domain.com.key` respectively.

What directory should they live in?

**Comment by themadcap1976** [comment]
I'm going crazy with this issue:
Which names would you like to activate HTTPS for?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: sail.yachtrockmiami.com
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel): 1
Cert not yet due for renewal

You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry.
(ref: /etc/letsencrypt/renewal/sail.yachtrockmiami.com.conf)

What would you like to do?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Attempt to reinstall this existing certificate
2: Renew & replace the cert (limit ~5 per 7 days)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1
Keeping the existing certificate
Deploying Certificate to VirtualHost /etc/nginx/sites-enabled/default
nginx: [error] invalid PID number "" in "/run/nginx.pid"

Please choose whether or not to redirect HTTP traffic to HTTPS, removing HTTP access.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: No redirect - Make no further changes to the webserver configuration.
2: Redirect - Make all requests redirect to secure HTTPS access. Choose this for
new sites, or if you're confident your site works on HTTPS. You can undo this
change by editing your web server's configuration.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Congratulations! You have successfully enabled https://sail.yachtrockmiami.com

You should test your configuration at:
https://www.ssllabs.com/ssltest/analyze.html?d=sail.yachtrockmiami.com
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/sail.yachtrockmiami.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/sail.yachtrockmiami.com/privkey.pem
   Your cert will expire on 2020-11-28. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot again
   with the "certonly" option. To non-interactively renew *all* of
   your certificates, run "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le


Sleep for 3600s
nginx_proxy_letsencrypt_1  | 2020/09/17 16:51:47 Received signal: terminated
nginx_proxy_letsencrypt_1  | 2020/09/17 16:51:47 Received signal: terminated
nginx_proxy_letsencrypt_1  | Info: Custom Diffie-Hellman group found, generation skipped.
nginx_proxy_letsencrypt_1  | Reloading nginx proxy (5cbccec92b5a1cf6bcbe067549761514ac81ca8b9c72e468b2387934980905a6)...
nginx_proxy_letsencrypt_1  | 2020/09/17 16:54:10 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx_proxy_letsencrypt_1  | 2020/09/17 16:54:10 [notice] 38#38: signal process started
nginx_proxy_letsencrypt_1  | 2020/09/17 16:54:11 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
nginx_proxy_letsencrypt_1  | 2020/09/17 16:54:11 Watching docker events
nginx_proxy_letsencrypt_1  | 2020/09/17 16:54:11 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
nginx_proxy_letsencrypt_1  | /etc/nginx/certs/sail.yachtrockmiami.com /app
nginx_proxy_letsencrypt_1  | Reloading nginx proxy (5cbccec92b5a1cf6bcbe067549761514ac81ca8b9c72e468b2387934980905a6)...
nginx_proxy_letsencrypt_1  | 2020/09/17 16:54:12 Generated '/etc/nginx/conf.d/default.conf' from 10 containers
nginx_proxy_letsencrypt_1  | 2020/09/17 16:54:12 [notice] 58#58: signal process started
nginx_proxy_letsencrypt_1  | Creating/renewal sail.yachtrockmiami.com certificates... (sail.yachtrockmiami.com)
nginx_proxy_letsencrypt_1  | Enter PEM pass phrase:
nginx_proxy_letsencrypt_1  | simp_le couldn't load a key from key.pem; the file might be empty or corrupt.

**Comment by SlvrEagle23** [comment]
@themadcap1976 Are you trying to use a custom SSL certificate or just use standard LetsEncrypt?

Make sure you've updated both your `docker.sh` script (via `./docker.sh update-self`) and your `docker-compose.yml` file (via answering "Y" to the prompt in `./docker.sh update`) and all of the LetsEncrypt storage should be set up properly without any issues.

By default, the certificates are managed internally in volumes that Docker controls.

**Comment by themadcap1976** [comment]
I will try that and provide an update here.

**Comment by themadcap1976** [comment]
I ran the utility..
/docker.sh letsencrypt-create
Domain name (example.com) or names (example.com,foo.bar) to use with LetsEncrypt [sail.yachtrockmiami.com]:
Optional e-mail address for expiration updates [info@yachtrockmiami.com]:
Stopping azuracast_web ... done
Going to remove azuracast_web
Removing azuracast_web ... done
azuracast_redis_1 is up-to-date
azuracast_stations is up-to-date
azuracast_mariadb_1 is up-to-date
azuracast_influxdb_1 is up-to-date
Creating azuracast_web ... done
Recreating azuracast_nginx_proxy_1 ... done
Recreating azuracast_nginx_proxy_letsencrypt_1 ... done

![Screen Shot 2020-09-23 at 7 17 28 AM](https://user-images.githubusercontent.com/32073620/94005875-f2cc6c00-fd6c-11ea-9c51-1933648026ad.png)

docker-compose logs -f nginx_proxy_letsencrypt
Attaching to azuracast_nginx_proxy_letsencrypt_1
nginx_proxy_letsencrypt_1  | Info: Custom Diffie-Hellman group found, generation skipped.
nginx_proxy_letsencrypt_1  | Reloading nginx proxy (0f1dbde43a5ed75b25566c20d871feb73124c7a249b06cd60864d409439aa036)...
nginx_proxy_letsencrypt_1  | 2020/09/23 11:16:08 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx_proxy_letsencrypt_1  | 2020/09/23 11:16:08 [notice] 40#40: signal process started
nginx_proxy_letsencrypt_1  | 2020/09/23 11:16:09 Generated '/app/letsencrypt_service_data' from 10 containers
nginx_proxy_letsencrypt_1  | 2020/09/23 11:16:09 Running '/app/signal_le_service'
nginx_proxy_letsencrypt_1  | 2020/09/23 11:16:09 Watching docker events
nginx_proxy_letsencrypt_1  | 2020/09/23 11:16:09 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
nginx_proxy_letsencrypt_1  | /etc/nginx/certs/sail.yachtrockmiami.com /app
nginx_proxy_letsencrypt_1  | Reloading nginx proxy (0f1dbde43a5ed75b25566c20d871feb73124c7a249b06cd60864d409439aa036)...
nginx_proxy_letsencrypt_1  | 2020/09/23 11:16:10 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx_proxy_letsencrypt_1  | 2020/09/23 11:16:10 [notice] 61#61: signal process started
nginx_proxy_letsencrypt_1  | Creating/renewal sail.yachtrockmiami.com certificates... (sail.yachtrockmiami.com)
nginx_proxy_letsencrypt_1  | Enter PEM pass phrase:
nginx_proxy_letsencrypt_1  | simp_le couldn't load a key from key.pem; the file might be empty or corrupt.
nginx_proxy_letsencrypt_1  |
nginx_proxy_letsencrypt_1  | Debugging tips: -v improves output verbosity. Help is available under --help.
nginx_proxy_letsencrypt_1  | /app
nginx_proxy_letsencrypt_1  | Sleep for 3600s

**Comment by SlvrEagle23** [comment]
@themadcap1976 It appears this error is specific to your setup. If you're using a custom certificate, it's possible that it has a passkey set, which the LetsEncrypt automatic container handler can't handle.

If you're not using a custom certificate, you can run something like this to clear the certificates:

```bash
cd /var/azuracast
docker-compose down
docker volume rm azuracast_letsencrypt
docker-compose up -d
```

**Comment by themadcap1976** [comment]
Thank. you @SlvrEagle23 that solved the problem !
