### ISSUE TITLE
What is the best way to name music files?

### ISSUE THREAD

**Issue by danielloretti** [AzuraCast/AzuraCast#3104]
I am importing my songs in the format: Song Artist - Song Name.mp3. Often they are being replaced with all lowercase letters, or the Song Artist field is empty. I wish to maintain the default Song Artist - Song Name. How do I achieve this? Thank you!

**Comment by dvdokkum** [comment]
I'm pretty sure Azuracast is going to use the metadata tags on the files you are uploading, not the file names.

You can either:

a) upload into Azuracast and then edit the metadata tags by clicking on the edit button 
or....
b) make sure your metadata fields are set correctly prior to uploading

You can use a batch tag editor to set your fields based on a common file name schema. Here's an example of some software that can do this (provided simply as an example.... I haven't used this software personally): https://www.mp3tag.de/en/

**Comment by diego-vieira** [comment]
@danielloretti if your issue is resolved, please consider closing the issue. Thanks

**Comment by danielloretti** [comment]
thank you guys!
