### ISSUE TITLE
Listener report only shows internal IP addresses

### ISSUE THREAD

**Issue by bjarn** [AzuraCast/AzuraCast#3108]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.3, #672467d

**Host Operating System**
Ubuntu Server 18.04

**Describe the bug**
On the Listener Report page only internal IP addresses are being shown. Before it showed the public IP addresses from the listeners. Because of this, location reporting is broken too and it is possible that listeners are squashed together even though it are 2 different listeners because the internal IP address for every listener is the same, in my case 192.168.192.6.

I am not using Cloudflare so this seems like a bug in the Nginx proxy or Azuracast itself.

**To Reproduce**
Go to listeners report, e.g. https://domain/station/1/reports/listeners

**Expected behavior**
It shows the actual public IP address of the listener.

**Device(s):**
 - Device: Desktop 
 - OS: MacOS 10.15.16
 - Browser: Chrome
 - Version: 84

**Comment by pixel-paul** [comment]
I've raised the same issue here: #2898 

Can you look at this comment and see if you have different images installed please?

 https://github.com/AzuraCast/AzuraCast/issues/2898#issuecomment-678673397

**Comment by bjarn** [comment]
I indeed see multipe images regarding the letsencrypt companion, however this shouldn't mean they are actually in use:
`# docker images --digests
REPOSITORY                               TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
azuracast/azuracast_web_v2               latest              sha256:d9179b5ff391ebfbf61ea706171e19c1ea6f5825d8bdaeb4934c660a0c6d8d41   8856f0916c52        17 hours ago        694MB
azuracast/azuracast_web_v2               <none>              sha256:5a417c7b22a58425ddaa02bcd24509de5841d56e3255eee4cfbb6eef20911da5   a44f19c65823        6 days ago          695MB
azuracast/azuracast_radio                latest              sha256:aded9d5b7c553be7330977a9e364b1e8f9a53473720902d47455e51ff8741a28   b648e6a86b07        4 weeks ago         1.25GB
azuracast/azuracast_web_v2               <none>              sha256:a48f353bc313e60c43b4cd50f2fd4bf637963d9f3af9ac7121a55d2877ff0a4d   796adbfd3281        4 weeks ago         694MB
azuracast/azuracast_radio                <none>              sha256:45359857bae5f6fae5b3f378f4162926c45fc11595e289f5d55099696dd03067   c0e7b4abf746        4 weeks ago         1.25GB
azuracast/azuracast_web_v2               <none>              sha256:e3ead84b5e58d79eeec53818f03bbc326693cebbe6644bbdf125f501cec97e23   c27128ace8fa        5 weeks ago         694MB
jrcs/letsencrypt-nginx-proxy-companion   latest              sha256:9b35085cc08a8eb7070df74a17e53cda5ec2ce220e6610239da9c06d36ae3495   574784c34954        5 weeks ago         95.1MB
azuracast/azuracast_web_v2               <none>              sha256:8b54ee5bb8073aea4e894e6a6c15be46444923f2d82a87d480989e69043e7aa9   24a9771bb447        6 weeks ago         694MB
azuracast/azuracast_db                   latest              sha256:46b1526f387454d99a938f43c60d577dad1e033171735742942d8fc45405424e   5830ba28a7af        6 weeks ago         401MB
azuracast/azuracast_web_v2               <none>              sha256:f8dc79a7f469c698d5bce7053405b6091dbb7acaafa18a4fca03b0586d8dbf52   cba45fb33357        7 weeks ago         689MB
azuracast/azuracast_web_v2               <none>              sha256:b697255bdec4dba7c24bf47a409ccbfd3c29352c350f8451d0c98113c1a57ace   a6cf03a7b089        7 weeks ago         689MB
azuracast/azuracast_influxdb             latest              sha256:51613b5d2395322f1e3b9aa916a2a4409968e9f59342cde5365454970494bd9b   424d148f2fb8        7 weeks ago         183MB
azuracast/azuracast_radio                stable              sha256:a60bf45ad27b387f20a1402ff4da99db661155dc123fe3481579de2ee896f9da   11ddb8790170        7 weeks ago         1.24GB
azuracast/azuracast_radio                <none>              sha256:eec3b0a70c56ec4073fbb87610c5e56e6169bf5f4724add2c165c5770a4e6a27   c3467d1656e9        7 weeks ago         1.24GB
azuracast/azuracast_web_v2               <none>              sha256:551c3c63a5a64e2ef945450bf89ef922ca2511d57f94e5c044f5e12778096a0b   fff3ea547985        8 weeks ago         687MB
azuracast/azuracast_web_v2               <none>              sha256:c11fa0c2cdedac75d6c6907c9fec090c946083aa9fc71bac85bd2e7ff7922bc9   2ec8bb25f32f        2 months ago        692MB
jrcs/letsencrypt-nginx-proxy-companion   <none>              sha256:014ace33aef0602061a9165fcad3a442445acc544ff1c6c1e32709018e231b21   7534af005483        2 months ago        93.8MB
azuracast/azuracast_web_v2               <none>              sha256:8a8c7c02baa5cbde9b7d982ebf8a337c3b849b12068d138ac1671f13e562d7cb   89ba8a63dbb8        2 months ago        696MB
azuracast_videostream                    latest              <none>                                                                    c1e312094abf        2 months ago        460MB
azuracast/azuracast_web_v2               <none>              sha256:be43d94ae90b8bb19315ebb5f209ad75208ce395dc3de82d41f8e53b2f1ee59b   83c69bc289ee        3 months ago        689MB
azuracast/azuracast_radio                <none>              sha256:9c0370b42d3bfda35fa25555b8eb7a1199f0509f5c4ea2e1400e6fddcc202ea8   8a76e8341f86        3 months ago        1.12GB
azuracast/azuracast_influxdb             <none>              sha256:1e385a4c0087fb25f017890ec4df94511fe312ed41c0fccae110d78deb1b75d4   9a83b8ec6ae7        3 months ago        92.6MB
azuracast/azuracast_nginx_proxy          latest              sha256:6e8b4728c391cf85f0bf1ba7ac249b5e07af63419174c41967e02ea976392fd8   2a15adcf63be        3 months ago        54.6MB
azuracast/azuracast_db                   <none>              sha256:9f2166d7edd645ca45c63d3dbc72fb800b094db1094dc4f68b8b2f8fae31a0b3   548d4aa8710b        3 months ago        401MB
azuracast/azuracast_web_v2               <none>              sha256:ab41880285940ace11965e86a0b03005915d905898accd1b650eef7dd77c8fa3   70c9ef934fa8        3 months ago        700MB
jrcs/letsencrypt-nginx-proxy-companion   <none>              sha256:3785c437d6dec8d1d180756c02d3e6322eed548069c57b87d715cae5533426a2   890c9ade6c79        3 months ago        93.8MB
azuracast/azuracast_radio                <none>              sha256:d9083c8b433f0b991c989630c995f1b2165e7aefe272679f98cd8a3db61c885c   689a3c4726d7        3 months ago        1.12GB
azuracast/azuracast_redis                latest              sha256:128ff32da3df4e3e503d87024e389b2902e7f032d5ba8af5e5944ad51914c137   053d6e2e0c9f        3 months ago        29.8MB
azuracast/azuracast_db                   <none>              sha256:d044003cb63d480228dc8158ee0ef7f183a126c64a40a38eeb9117dd2005b767   a141bbaccbb2        6 months ago        398MB
azuracast/azuracast_influxdb             <none>              sha256:6a1cff6ef67d4f9c415c04692511d281569097c0510da3c3be7e3a814800b0a4   be894f602c9a        15 months ago       91.2MB
phusion/baseimage                        0.11                sha256:6ba22a31a809de669243b79f982f7b2df733ead1ec45becff401b4d5d79150bb   14e6c478b00a        2 years ago         183MB`

**Comment by pixel-paul** [comment]
You have the same image versions as I do and your rolling version is later than the one where this issue was resolved for me so #e9c79f2).

REPOSITORY     |                          TAG            |                                            IMAGE ID            |CREATED      |       SIZE
--|--|--|--|--|
azuracast/azuracast_web_v2      |         latest              |  f67864322212    |    8 hours ago     |    693MB|
azuracast/azuracast_radio     |           latest                | b648e6a86b07  |      4 weeks ago      |   1.25GB|
jrcs/letsencrypt-nginx-proxy-companion|   latest          |  574784c34954      |  5 weeks ago     |    95.1MB|
azuracast/azuracast_db      |             latest         |      5830ba28a7af    |   6 weeks ago  |       401MB|
azuracast/azuracast_influxdb     |        latest                | 424d148f2fb8   |     7 weeks ago    |     183MB|
azuracast/azuracast_nginx_proxy    |      latest     |           2a15adcf63be  |      3 months ago   |     54.6MB|
azuracast/azuracast_redis           |     latest               |  053d6e2e0c9f    |    3 months ago |       29.8MB|

However, I am seeing the external IP addresses as of this commit:
`**#e9c79f2 (2020-08-18 4:16)**`

It is therefore still unclear why the external IP addresses are appearing correctly for my instance, however not yours.

Does your host sit behind a firewall (so the docker host has a private IP)?

**Comment by bjarn** [comment]
Nope, no Firewall nor Cloudflare. The instance has a public IP. It worked before too.

**Comment by pixel-paul** [comment]
If you try and connect to a station via TuneIn does the external IP address appear? (ref: https://github.com/AzuraCast/AzuraCast/issues/2898#issuecomment-657640846)

**Comment by bjarn** [comment]
Nope, does not make a difference sadly. Icecast sees it as a seperate listener but in Azura it gets merged into an existing listener with the same user agent.

**Comment by emilio-pro** [comment]
I had the same problem, but i fixed it by creating a custom nginx file, as described here:
https://www.azuracast.com/extending/modifying-docker.html#custom-nginx-configuration

Next I replaced these lines (starting at line 38)
# proxy_set_header X-Real-IP $proxy_x_forwarded_for;
# proxy_set_header X-Forwarded-For $proxy_x_forwarded_for;
# proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header  X-Real-IP $remote_addr;
proxy_set_header  X-Forwarded-Proto https;
proxy_set_header  X-Forwarded-For $remote_addr;
proxy_set_header  X-Forwarded-Host $remote_addr;

And added these lines to the server block (near line 75)
    set_real_ip_from 192.168.0.0/16;
    real_ip_header X-Real-IP;
    real_ip_recursive on;

Based on the tutorial here
https://calvin.me/forward-ip-addresses-when-using-nginx-proxy

I couldn't find the /etc/nginx/conf.d/azuracast.conf file for docker in the repo, otherwise I could have made a pull request.

Hopefully this helps you out.

**Comment by bjarn** [comment]
@emilio-pro Smart move! That one did the trick. Thanks. Sounds great if that indeed could be added to the default image.

**Comment by pixel-paul** [comment]
The file exists here I believe:

https://github.com/AzuraCast/AzuraCast/blob/7340f349ddc4e2940a59daa4d5e85f2e5e886602/util/docker/web/nginx/azuracast.conf#L38

I'm still don;t understand why mine _wasn't_ working and now is.

**Comment by emilio-pro** [comment]
I'm not sure either.
Maybe the problem starts here:

    map $http_x_forwarded_for $proxy_x_forwarded_for {
      default $http_x_forwarded_for;
      ''      $remote_addr;
    }

if $http_x_forwarded_for is not empty,  $remote_addr will never be set. That is why it has to be set at line 38. 
But maybe it would be better to move it up to the top, not sure how yet.

The second part is required, but should probably be something like:

    set_real_ip_from 192.168.0.0/16;
    set_real_ip_from  10.0.0.0/8;
    set_real_ip_from  172.0.0.0/24;
    real_ip_header X-Real-IP;
    real_ip_recursive on;

Do I make any sense?

**Comment by moran1804** [comment]
Hi Guys,

I have this:
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Forwarded-Host $remote_addr;

server {
    listen 80;
    listen 443 ssl;
    root /var/azuracast/www/web;
    index index.php;
    server_name mystation.micast.media;
    ssl_certificate /ect/nginx/mystation.micast.media.chained.crt;
    ssl_certificate_key /ect/nginx/mystation.micast.media.key;
    ssl_protocols TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
    add_header X-XSS-Protection 1;
    add_header X-Content-Type-Options nosniff;
    add_header X-Robots-Tag none;
    add_header Referrer-Policy no-referrer-when-downgrade;
    set_real_ip_from 192.168.0.0/16;
    set_real_ip_from  10.0.0.0/8;
    set_real_ip_from  172.0.0.0/24;
    real_ip_header X-Real-IP;
    real_ip_recursive on;

and its still not dragging through the IP Addresses :( still always internal ones.
any idea? been bugging me for ages this.

i dont use lets encrypt i use standard paid certs.

**Comment by emilio-pro** [comment]
@moran1804 Maybe add an extra header to the server block to test if the proper configuration is loaded?

Like
add_header X-Azur Works

And test with
$ curl -I example.com
Sample outputs:

HTTP/1.1 200 OK
Server: nginx
Date: Mon, 26 aug 10:40:58 GMT
Content-Type: text/html; charset=ISO-8859-1
Connection: keep-alive
X-Azur : Works

If it works and you still only get local addresses my fix is not working.

**Comment by moran1804** [comment]
@emilio-pro can you send my your NGINX config file? i can change the SSL bits and see if that works?
maybe ive been using the same NGINX config file for a while and thats what is causing the issues.

**Comment by moran1804** [comment]
Also can you show me you Docker compose and docker compose override? 
just want to see if im doing something wring there also. 

im desperate to fix this issue fed up with internal IPs

**Comment by emilio-pro** [comment]
My docker-compose is just the default.
My override consists of nothing more than:

> version: '2.2'
> 
> services:
>   web:
>     volumes:
>       - /volume/audio/Folders:/var/azuracast/stations/proper_radio/media/
>       - /volume/audio/conf/azuracast/azuracast-nginx.conf:/etc/nginx/conf.d/azuracast.conf:ro

I've added my file. But I it is just a copy of the regular file with the lines named earlier.
[azuracast-nginx-example.txt](https://github.com/AzuraCast/AzuraCast/files/5130443/azuracast-nginx-example.txt)

Also: I'm on  v0.10.3, #19122eb (2020-08-25 16:20) Rolling • Docker • PHP 7.4

**Comment by pixel-paul** [comment]
@emilio-pro what I find strange is that only some of the IPs were internal - was it the same for you?

@moran1804 can you confirm that you are on the rolling release? I had this problem and it miraculously went away, following an update last week.

**Comment by moran1804** [comment]
Does the rolling release automatically update? does it do that in Docker?

**Comment by pixel-paul** [comment]
There isn't an automatic update (that I know of). 

Here are the docs for updating:

https://www.azuracast.com/administration/system/updating.html#docker-installations

And you can check your version (whether on rolling or stable) in the footer of the control panel.

So mine is currently:

`Powered by AzuraCast • v0.10.3, #8398261 (2020-08-24 4:07) Rolling • Docker • PHP 7.4 `

**Comment by emilio-pro** [comment]
@pixel-paul No, all my ip's were local.

**Comment by bjarn** [comment]
Sad news; the custom nginx configuration seems to have stopped working too, getting private IP addresses once again.

**Comment by hecgua** [comment]
I just updated my Azuracast installation a few moments ago and it looks like the public IP address issue has been fixed.

v0.10.3, #f8c04b4 (2020-09-01 0:54) Rolling • Docker • PHP 7.4

**Comment by pixel-paul** [comment]
This issue is disparate, so I'm unsure if a recent commit has fixed the problem. External IPs started appearing again for me from this commit: #e9c79f2 (2020-08-18 4:16). I had suspected that this was an issue with the upstream nginx containers, however there have been no commits relating to this issue (from what I could see).

It could be happening: 

1. At the nginx level, where (for some reason) the forwarded IP address is lost (bug in one of the nginx containers perhaps)
2. At the application level where the header is being misread or not being read, e.g. src/Middleware/ApplyXForwardedProto.php. This is the only reference I've found in the application referring to the IP headers.

**Comment by bjarn** [comment]
IP addresses in the Icecast Admin panel are also private addresses which means it seems to be non-related to Azuracast itselt and therefore it has to be something to do with the Nginx image or config. Will look into it more when I got time.

**Comment by M0IZH** [comment]
Hi
I have the same problem, what's the solution?
![Annotation 2020-09-05 210215](https://user-images.githubusercontent.com/33510791/92312817-6f64f980-efbc-11ea-9906-2ed2e3627afc.png)

**Comment by LordHelmchen666** [comment]
I have the same problem after updating Azuracast (Docker Install) sometimes. When i restart Docker service completely like this 
`sudo systemctl restart docker`
then it works correct and get the correct listener IPs again.

**Comment by bjarn** [comment]
Restarting the docker process seems to be the most effective way to (temporarily) work around this issue.

**Comment by moran1804** [comment]
Quick question do you all use the free certs (lets encrypt)? im not using free certs so have the proxy servers disabled and run directly to NGINX. 

nothing ive tried fixes mine

**Comment by pixel-paul** [comment]
I've just updated to this commit https://github.com/AzuraCast/AzuraCast/commit/f8770145ece4ea563a3108e2aa74ad08e2904141 and I'm back to internal IPs.

**Comment by hecgua** [comment]
> I just updated my Azuracast installation a few moments ago and it looks like the public IP address issue has been fixed.
> 
> v0.10.3, #f8c04b4 (2020-09-01 0:54) Rolling • Docker • PHP 7.4

The internal IP address issue is back in my installation.

I do not have any special configuration, nor have I altered my Azuracast installation in any way. 

Is there a solution for this problem?

Rolling Release #428021b (2020-11-24 7:55) • Docker • PHP 7.4

**Comment by bjarn** [comment]
It definitely looks like a Docker issue. Restarting your docker service (not the containers) solves the issue for now @hecgua

**Comment by christiansacks** [comment]
Gah, I have docker installed for some reason as a snap, and doing a `snap restart docker.dockerd` didn't resolve the IP address thing.

Weird thing is that in the log for the nginx proxy container, the IP addresses are showing fine.

Please help us fix the Internal/non public IP addresses.

nginx.1    | radio.erb.pw 86.aaa.bbb.247 - - [29/Jan/2021:10:30:07 +0000] "GET /api/nowplaying/subspace HTTP/1.1" 200 7119 "-" "Python-urllib/3.6"
nginx.1    | radio.erb.pw 86.aaa.bbb.247 - - [29/Jan/2021:10:30:18 +0000] "GET /api/nowplaying/subspace HTTP/1.1" 200 7114 "-" "Python-urllib/3.6"
nginx.1    | radio.erb.pw 86.aaa.bbb.247 - - [29/Jan/2021:10:30:29 +0000] "GET /api/nowplaying/subspace HTTP/1.1" 200 7114 "-" "Python-urllib/3.6"
nginx.1    | radio.erb.pw 86.aaa.bbb.247 - - [29/Jan/2021:10:30:40 +0000] "GET /api/nowplaying/subspace HTTP/1.1" 200 7114 "-" "Python-urllib/3.6"

**Comment by SlvrEagle23** [comment]
I've looked into it, and this appears to be caused by an oddity in the Docker networking stack; the `nginx-proxy` service's internal network seems to have IPs that are in the `192.x.x.x` range, where most Docker internally assigned IPs are within the `172.x.x.x` range.

I've expanded the range that Icecast will accept the `X-Forwarded-For` header from to include the wider IP address range. Hopefully this will result in more accurate IP addresses for listeners.

This update has just been pushed to the Rolling Release channel. Along with some other minor fixes, if users can update and confirm that this is fixed, we'll get it pushed up to stable ASAP.

**Comment by christiansacks** [comment]
Just updated, and still get the same thing....
![image](https://user-images.githubusercontent.com/40481087/106367639-0c457c00-633c-11eb-9a1f-3a88d99eea55.png)

**Comment by coolmusicradio** [comment]
Updated and remains the same.
Restarting Do.cker doesn't fix it either.
Shoutcast also does not resolve the ip.

if the listener enters the server directly with "ip:port/mount" if the ip is resolved and the public one is seen (in http, without using the sll of the certificate).
without going through "/ radio".

**Comment by SlvrEagle23** [comment]
I've reverted a change on the rolling release branch; try updating again and see if it helps the issue.

**Comment by coolmusicradio** [comment]
Okay!
I am testing with Tunein and the "public web" player and it is resolving the public ip's.

**Comment by LordHelmchen666** [comment]
It is working for me. Thank you SlvrEagle23!

**Comment by hecgua** [comment]
Worked for me too. Thank you SlvrEagle23!

**Comment by Lokke** [comment]
> I've reverted a change on the rolling release branch; try updating again and see if it helps the issue.



> 
> 
> I've looked into it, and this appears to be caused by an oddity in the Docker networking stack; the `nginx-proxy` service's internal network seems to have IPs that are in the `192.x.x.x` range, where most Docker internally assigned IPs are within the `172.x.x.x` range.
> 
> I've expanded the range that Icecast will accept the `X-Forwarded-For` header from to include the wider IP address range. Hopefully this will result in more accurate IP addresses for listeners.
> 
> This update has just been pushed to the Rolling Release channel. Along with some other minor fixes, if users can update and confirm that this is fixed, we'll get it pushed up to stable ASAP.

sadly no changes in my case.
**Rolling Release #3ca0986 (2021-02-03 21:23) • Docker • PHP 7.4** 

![Screenshot 2021-02-04 171310](https://user-images.githubusercontent.com/6406275/106921686-872bdf80-670c-11eb-814b-ca70bc5bf683.png)

**Comment by hecgua** [comment]
Worked for me too. Thank you @SlvrEagle23

**Comment by SlvrEagle23** [comment]
@Lokke Unfortunately, I'm not sure that SHOUTcast properly handles the `X-Forwarded-For` header, but since it's proprietary and closed-source software, there's no way for us to inspect, or better yet improve, it.

Since the issue appears to be fixed for our Icecast users, I'm closing this ticket for now.

**Comment by coolmusicradio** [comment]
Hi
.I use Shoutcast 2.6 with premium account and yes I solved the problem.

**Comment by Jaadoo13** [comment]
Okay, as there are many threads with this topic, is there a solution, now? i use the newest 0.12.2 azuracast and ubuntu 20.04. but i got only the internal IPs. thats really really bad. as i cant block bad listeners anymore. ;( 
A i have the newest version, there is no update. but a reinstall also does not helped. And a nginx config i cant find, to make a forward test....

**Comment by Jaadoo13** [comment]
> I had the same problem, but i fixed it by creating a custom nginx file, as described here:
> https://www.azuracast.com/extending/modifying-docker.html#custom-nginx-configuration
> 
> Next I replaced these lines (starting at line 38)
> # proxy_set_header X-Real-IP $proxy_x_forwarded_for;
> # proxy_set_header X-Forwarded-For $proxy_x_forwarded_for;
> # proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header X-Forwarded-Proto https;
> proxy_set_header X-Forwarded-For $remote_addr;
> proxy_set_header X-Forwarded-Host $remote_addr;
> 
> And added these lines to the server block (near line 75)
> set_real_ip_from 192.168.0.0/16;
> real_ip_header X-Real-IP;
> real_ip_recursive on;
> 
> Based on the tutorial here
> https://calvin.me/forward-ip-addresses-when-using-nginx-proxy
> 
> I couldn't find the /etc/nginx/conf.d/azuracast.conf file for docker in the repo, otherwise I could have made a pull request.
> 
> Hopefully this helps you out.

And where i can find this file on Ubuntu 20.04 with azuracast 0.12.2 ?

**Comment by emilio-pro** [comment]
The new documentation is here:
https://docs.azuracast.com/en/administration/docker
However.
My fix wasn't fixing. It only appeared to fix because of the restarts, as Bjarn mentioned:
https://github.com/AzuraCast/AzuraCast/issues/3108#issuecomment-685734529
And Lordhelm explained:
https://github.com/AzuraCast/AzuraCast/issues/3108#issuecomment-689001546

Haven't come across the problem since I switched back to the stable release some months ago, though.
