### ISSUE TITLE
Directory /x/xx/x was not created Station.php : 703

### ISSUE THREAD

**Issue by nashosted** [AzuraCast/AzuraCast#3109]
Standard docker install when setting up a new station under Administration I add my own Advanced Custom Media Directory and it gives a 500 error Directory "/home/jeremy/Music" was not created
Station.php : 703

If this is a permission error, how can I resolve this? It is installed on the same machine my music is on.

**Comment by bjarn** [comment]
Have you followed the developer instructions? In case you did, please read them again. @SlvrEagle23 just updated them and fixes issues like yours mentioned in #3070 #3074
