### ISSUE TITLE
Error in profile when playing the player

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#311]
VM6190:164 WebSocket connection to 'wss://xxx.ru/api/live/nowplaying/1' failed: Error during WebSocket handshake: Unexpected response code: 200
Tell me how to get rid of this error? When playing the player, errors are typed.
`    var sub = new NchanSubscriber('/api/live/nowplaying/<?=$station->getId() ?>');`

**Comment by susl16c** [comment]
Help me please in solving this problem.

**Comment by SlvrEagle23** [comment]
@susl16c Are you using the traditional installation or Docker?

Also, if you visit the Administration page, when was the "Now Playing Synchronization" task last run? Try running it manually and let me know if any errors occur.

**Comment by susl16c** [comment]
![dfbdb](https://user-images.githubusercontent.com/23697714/33764776-06e3a2e0-dc27-11e7-8999-85031b48a704.png)
Did all the possible synchronization manually as you wrote all the same on the genre page there are constant mistakes and songs are not yet displayed, but you have already written to mine, but I just attached a screenshot, thank you very much.

**Comment by SlvrEagle23** [comment]
@susl16c What are you using to provide the SSL for your AzuraCast instance? Do you have Cloudflare or something else in front of the server, or did you provide it with a custom SSL certificate?

If you access AzuraCast without HTTPS, does this same issue still happen?

**Comment by susl16c** [comment]
I have an isp manager I set up a nginx to work as a proxy and redirected to the local address of your project, it works in the docker.
how everything works I gave you access in the previous message where no songs are displayed. If your project does not work through a proxy, then the songs are displayed and there are no errors with the player.

**Comment by SlvrEagle23** [comment]
@susl16c If you're proxying to AzuraCast, you need to make sure that your proxying service has proper configuration for the `/api/live` URLs, and handles them as websockets, not as regular requests.

If you can't customize the configuration to do so, I would recommend using a service like Cloudflare instead, which will automatically support web sockets while still providing reliable SSL connections to your users.

Closing this issue as it's not an actual limitation of AzuraCast's, but rather of the configuration of a third-party proxy that isn't part of this software suite.

**Comment by susl16c** [comment]
/api/live And why does she need this service? Can I disable it if I do not use it?
