### ISSUE TITLE
Azuracast Forum/Subreddit

### ISSUE THREAD

**Issue by nashosted** [AzuraCast/AzuraCast#3112]
I know a forum has been talked about for several months but I went ahead and created a subreddit here for people who want to share their knowledge and help other people with Azuracast. https://www.reddit.com/r/Azuracast. I'd love to pass it over to Mitch or Buster if they'd like to control it.

**Comment by nashosted** [comment]
Closing because it's not an issue but more of a statement.

**Comment by SlvrEagle23** [comment]
@nashosted I wouldn't mind making the Subreddit an official one for us. It would be kind of nice to have an alternate discussion format where longer-term discussions can happen outside the context of Discord/Slack.

Feel free to reach out to me on our existing Discord/Slack channels for my details. On Reddit I'm SlvrEagle23.
