### ISSUE TITLE
error during installation on centos 7 with docker

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#312]
Hello,

I am getting this error during installation with docker:

Pulling stations (azuracast/azuracast_stations:latest)...
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by susl16c** [comment]
do you even have a docker at all?
`sudo systemctl status docker`

**Comment by SlvrEagle23** [comment]
@surihost If you just installed the Docker client on your server, and/or just added your username to the `docker` group, you may need to restart to continue installation. This happens if you aren't running the Docker installation as root.

**Comment by surihost** [comment]
[root@ls ~]# sudo systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: https://docs.docker.com

I am running as root for the installation .

**Comment by SlvrEagle23** [comment]
@surihost Try `systemctl enable docker` and then `systemctl start docker`

**Comment by surihost** [comment]
Yes now it installed :)
Thanks
