### ISSUE TITLE
No available ports

### ISSUE THREAD

**Issue by ubookeditora** [AzuraCast/AzuraCast#3120]
Dear, even after increasing the port range of my docker installation, I am getting this error when creating a new station. "This installation has no available ports for new radio stations"
<img width="1256" alt="Captura de Tela 2020-08-26 às 14 02 25" src="https://user-images.githubusercontent.com/69636139/91343580-268a9500-e7b3-11ea-95c1-1328e847692b.png">

**Comment by SlvrEagle23** [comment]
@ubookeditora Sorry for the delay in getting back to this. There's a step in our documentation that we forgot to include, which is that you should update `azuracast.env` to modify the port range it uses when auto-assigning station ports.

We've updated [our documentation](https://www.azuracast.com/help/docker/#expand-the-docker-radio-station-port-range) to include these instructions.
