### ISSUE TITLE
Two-Factor not working

### ISSUE THREAD

**Issue by nashosted** [AzuraCast/AzuraCast#3121]
When trying to setup two-factor using the Authy app, I get this error.

![image](https://user-images.githubusercontent.com/57927413/91345515-82521f80-e7ad-11ea-96ff-d7e80d2e18bb.png)

I tried it both with and without a space between the 3 numbers.

Using docker installed on Ubuntu with latest build.

**Comment by SlvrEagle23** [comment]
@nashosted This can be caused by either your server's time being inaccurate or your authenticating device's time being inaccurate. We have a fairly wide window of accepted codes to help prevent this issue, but you should check both to make sure everything is normal.

**Comment by nashosted** [comment]
> @nashosted This can be caused by either your server's time being inaccurate or your authenticating device's time being inaccurate. We have a fairly wide window of accepted codes to help prevent this issue, but you should check both to make sure everything is normal.

How can I check the server time and change it if necessary?

Thanks for the timely response.

**Comment by SlvrEagle23** [comment]
@nashosted If your host OS is Ubuntu, a guide like this might help: https://www.atlantic.net/vps-hosting/how-to-set-up-time-synchronization-with-ntp-on-ubuntu-18-04/

**Comment by nashosted** [comment]
This was due to machine/server time being wrong. Fixed and resolved. Thanks @SlvrEagle23
