### ISSUE TITLE
Restore other VPS stations

### ISSUE THREAD

**Issue by henlinea** [AzuraCast/AzuraCast#3122]
Hello, how are you? I have the need to migrate two stations that are running on a VPS to another VPS that currently has 12 stations, if I perform a restore, the 12 stations that I have are deleted, right? There is a possibility of doing it without losing any data ?

Greetings and thanks

**Comment by SlvrEagle23** [comment]
@henlinea Restoration currently clears out the existing databases and stations in an installation. Currently there is no easy way to merge two separate installations.

**Comment by nashosted** [comment]
If it's only 2 stations, why not just add them manually to the server with 12 stations? It's pretty simple and doesn't take long to add stations.
