### ISSUE TITLE
Backup failed

### ISSUE THREAD

**Issue by KoneSV** [AzuraCast/AzuraCast#3123]
Ansible:

Backup failed

The process "mysqldump --host=$DB_HOST --user=$DB_USERNAME --password=$DB_PASSWORD --add-drop-table --default-character-set=UTF8MB4 $DB_DATABASE > $DB_DEST" exceeded the timeout of 60 seconds.
Process.php : 1239

**Comment by nashosted** [comment]
Am I the only one here using Proxmox to manage backups and snapshots? ;)

**Comment by diego-vieira** [comment]
@KoneSV are you running the latest AzuraCast version? (you haven't provided that).

@nashosted the default backup from AzuraCast installation using docker works pretty well.
https://www.azuracast.com/administration/system/backup.html#backing-up
