### ISSUE TITLE
Maxminnd geolite db

### ISSUE THREAD

**Issue by tsisma** [AzuraCast/AzuraCast#3124]
v0.10.3, #d0ab57a (2020-08-26 16:36) Rolling • Docker • PHP 7.4
the Maxmind db is giving me wrong data.
example:

192.168.144.6 | 934 | desktop_windows Desktop DeviceMozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36 | Internal/Reserved IP
-- | -- | -- | --

 this is because the reverse proxy?

**Comment by SlvrEagle23** [comment]
@tsisma That IP address actually is an internal IP address, typically one of a router or switch or other piece of networking tech between AzuraCast and the Internet. There are a number of existing discussions about how to resolve this in this GitHub issues section, so I'm closing this one as a duplicate.
