### ISSUE TITLE
Docker Compose Override File.

### ISSUE THREAD

**Issue by adoboligh1** [AzuraCast/AzuraCast#3126]
Hello, Please Is The a way to use multiple comands on this file,

like using Nginx Web proxy for http websites alongside with mounting a directory to a station all on the same file?

**Comment by nashosted** [comment]
It's possible but I am not too sure of you question as a whole. You can edit the file if you chmod the install folder to 777 and any mounted directories you bind.

**Comment by adoboligh1** [comment]
Understood but I'm not talking about how to mount the directory, all am
asking is can I put different tasks on the docket compose override.yml file.

Like Mounting a directory to a station and Using Nginx proxy to serve
subdomain webpages.
