### ISSUE TITLE
 An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by suricloud** [AzuraCast/AzuraCast#3127]
**Using Docker installation method**

Yes
**AzuraCast version**

**Host Operating System**

Debian 10
**Describe the bug**

Installation stuck.
**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

AzuraCast Setup
===============

Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are s                                                                                                 et up...
 * Environment: Production
 * Installation Method: Docker

Waiting for dependent services to go online...
 0/3 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%

 [ERROR] Error encountered: An exception occurred in driver: SQLSTATE[HY000]
         [2002] Connection refused
         (/var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Abstr
         actMySQLDriver.php L93)

Setting Up InfluxDB
-------------------

Database created.
Retention policies updated.
Continuous queries created.
InfluxDB databases created.

Running Database Migrations
---------------------------

In AbstractMySQLDriver.php line 93:

  An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused

In PDOConnection.php line 31:

  SQLSTATE[HY000] [2002] Connection refused

In PDOConnection.php line 27:

  SQLSTATE[HY000] [2002] Connection refused

azuracast:setup [--update] [--load-fixtures] [--release]

**Comment by SlvrEagle23** [comment]
@suricloud This should be helped by the latest update.

**Comment by diego-vieira** [comment]
@suricloud can you reinstall AzuraCast on a fresh OS install and see if that resolves your issue?

**Comment by suricloud** [comment]
Yes i reinstalled and its fine now.

**Comment by diego-vieira** [comment]
@suricloud feel free to close this issue. Thanks
