### ISSUE TITLE
Greek language

### ISSUE THREAD

**Issue by webalphatv** [AzuraCast/AzuraCast#3129]
Greetings,i have made a translation to Greek language,i can send it to sumbit to your panel.I see you have many language and it would be nice to add the Greek language

**Comment by SC2Mitch** [comment]
Hey!

AzuraCast's translations are handled through https://crowdin.com/project/azuracast

Post them there and I'm sure Buster will get around to approving it

**Comment by SlvrEagle23** [comment]
@webalphatv Hello! I have added Greek as a targeted language in our CrowdIn, as well as adding support for it in the AzuraCast application itself. Once your translations are submitted, we will get them automatically included in our build process.
