### ISSUE TITLE
Radio Station Name: short simple URL vs User Friendly Readability

### ISSUE THREAD

**Issue by amavarick** [AzuraCast/AzuraCast#313]
Just want to say how impressed I am with your product.  I've used centovacast, libretime and also direct icecast/liquidsoap server installs and have got to say your product is very well designed and it seems to just work.  Your development process ie the tools you use are still ahead of the curve and well respected.  AWESOME.  Thank you.

Please consider incorporating this enhancement request...

Currently when you create a radio you can define the name of the radio:

![stationtitleinprofile](https://user-images.githubusercontent.com/20918832/33625738-92285598-d9c6-11e7-80b8-2428f29ca123.png)

The title looks great in the GUI of the program and on the website.  The only problem is that the URL is not a user friendly URL as shown below.  After someone enters a title name, spaces and special characters are replaced with underscores and if a long title is given, a long URL is made:

![url](https://user-images.githubusercontent.com/20918832/33625787-bf69390a-d9c6-11e7-8fff-77f920333343.png)

Could we get a field such as "URL Title" to define a URL title associated with that particular radio?
**Radio Title**:
Test Station With Spaces In The Name Isn't A Friendly URL
**URL Title**:
teststation

![url1](https://user-images.githubusercontent.com/20918832/33626024-779cf1c4-d9c7-11e7-961d-17bcdad986ca.png)

This way the web page will have a user friendly title but the URL will have something easy to type in?  

Maybe rather than undoing the original title, it could be like a permalink to the actual title so both work simultaneously?  Thank you so much for your time.

**Comment by SlvrEagle23** [comment]
@amavarick First of all, thank you very much for the kind words. I'm very happy you find AzuraCast to be a useful contribution in the world of web radio, as it's been a labor of love of mine for some time now.

Your enhancement brings up a very valid point, since the "stub" URL for a station is used much more now than it originally was when I conceived the idea. Adding the ability to customize it is fairly low complexity, but will involve a minor change to the database, so expect that change to be incoming in the next few days.

**Comment by susl16c** [comment]
I also join the words written above and very very grateful to you for your brilliant work. I've been looking for something similar for a long time but could not find it, your product is almost the ideal solution for creating onlan radio. You have made a huge contribution. Thank you very much, health to you and do not give up your work.

**Comment by SlvrEagle23** [comment]
@amavarick The station's "short code", the shortened URL for public links and API referencing, has been moved into the database and is now a user-editable field in the station profile.

Give it a try!
