### ISSUE TITLE
Now Playing in public/embed page not working

### ISSUE THREAD

**Issue by YosefAdPro** [AzuraCast/AzuraCast#3132]
**Using Docker installation method**

No
**AzuraCast version**

0.10.3
**Host Operating System**

Ubuntu 18.4

**Describe the bug**

It shows the song that is playing at the entrance to the page, and is no longer updated.

**To Reproduce**

**Expected behavior**

**Relevant Logs**

I do not see in logs as an error or anything out of the ordinary

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by diego-vieira** [comment]
You didn't fill in the device you are using. If you are using Chrome, have a look at the console to see if there is nothing wrong there.

**Comment by YosefAdPro** [comment]
@diego-vieira 
I use chrome.
In console i have this error:

```
WebSocket connection to 'ws://DOMAIN/api/live/nowplaying/STATION' failed: Connection closed before receiving a handshake response

e.SubscriberClass.websocket.l.listen @ vendor-68e9c936eb.js:1
e.start @ vendor-68e9c936eb.js:1
checkNowPlaying @ RadioPlayer-a472c79a52.js:1
```

On the server open ports 443/80

**Comment by diego-vieira** [comment]
Go to System Administration > System Settings and disable this setting - see if the issue persists.

![image](https://user-images.githubusercontent.com/930792/92638672-8bc1a880-f2d2-11ea-96e4-f01c9d3ee9bb.png)

**Comment by YosefAdPro** [comment]
In this method it works.
What could be that WebSocket is not working?

**Comment by diego-vieira** [comment]
I do not know for sure.

There are other issues on the subject though

https://github.com/AzuraCast/AzuraCast/search?q=websocket&type=Issues

**Comment by YosefAdPro** [comment]
After a deep study of logs I saw this error:
`Lost connection to redis at redis://localhost:6379: Server closed the connection.`

And I understood what was causing the problem.
The NGINX used ports 6XXX and not from 8000.

Thanks @diego-vieira
