### ISSUE TITLE
stream offline: strange error flushing buffer

### ISSUE THREAD

**Issue by jbsix** [AzuraCast/AzuraCast#3136]
**Using Docker installation method**

Yes

**AzuraCast version**

 v0.10.3, #f8c04b4 (2020-09-01 0:54) Rolling • Docker • PHP 7.4 

**Host Operating System**

Ubuntu 18.04

**Describe the bug**

Receiving the Liquidsoap log error: Connection failed: 403, Mountpoint in use (HTTP/1.0) when using the 'Fallback' mount point feature of Azuracast. The use case is simply the need for two streams, two Icecast2 servers: one with the Azuracast install and Auto DJ feature and another with different IP address as a Relay stream. 

**To Reproduce**

1. Go to Mount Points
2. Add Relay Stream URL to mount point A: /stream-a.mp3
3. Add Fallback mount point B: /stream-b.mp3

**Expected behavior**

This might be a user error, with configuration of Azuracast (if anyone has ideas to reconfigure in a better way based on use case please help) although the expected behavior would be that when mount point A (stream-a.mp3) is not playing, Azuracast would 'fallback' to mount point B (stream-b.mp3) and therefore seems there is a possibility of a bug. From admin side, on the Azuracast interface Mount Point B is playing Auto DJ with files on same server. However, Mount Point A is not playing fallback when there is no audio from relay stream and instead does not update meta data: "**stream offline**" and stream is playing fine on stream B although not on stream A). Expected behavior would be that when there is no audio on steam A the user would hear stream B and this only happens when there is no audio being sent from A, when there is no audio playing from remote URL the system does not work as expected. Works OK when there is audio being sent from the remote URL, thank you for any help and keep up the good work.

The use case is that when not playing audio from remote URL (another icecast2 server) that the expected behavior would 'fallback' to the Auto DJ feature of Azuracast (playlists features, etc.) and the user would hear stream-b.mp3 playing on the default mount point.

**Relevant Logs**

2020/09/01 13:58:06 [audio_local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
strange error flushing buffer ... 
2020/09/01 13:58:06 [audio_local_1:3] Will try again in 3.00 sec.
strange error flushing buffer ... 
2020/09/01 13:58:10 [audio_local_1:3] Connecting mount /stream-a.mp3 for source@127.0.0.1...
2020/09/01 13:58:10 [audio_local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
strange error flushing buffer ... 
2020/09/01 13:58:10 [audio_local_1:3] Will try again in 3.00 sec.
strange error flushing buffer ... 
2020/09/01 13:58:14 [audio_local_1:3] Connecting mount /stream-a.mp3 for source@127.0.0.1...
strange error flushing buffer ... 
strange error flushing buffer ... 
2020/09/01 13:58:14 [audio_local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2020/09/01 13:58:14 [audio_local_1:3] Will try again in 3.00 sec.
2020/09/01 13:58:18 [audio_local_1:3] Connecting mount /stream-a.mp3 for source@127.0.0.1...
strange error flushing buffer ... 
strange error flushing buffer ... 
2020/09/01 13:58:18 [audio_local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2020/09/01 13:58:18 [audio_local_1:3] Will try again in 3.00 sec.
2020/09/01 13:58:22 [audio_local_1:3] Connecting mount /stream-a.mp3 for source@127.0.0.1...
2020/09/01 13:58:22 [audio_local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
strange error flushing buffer ... 
2020/09/01 13:58:22 [audio_local_1:3] Will try again in 3.00 sec.
strange error flushing buffer ... 
2020/09/01 13:58:26 [audio_local_1:3] Connecting mount /stream-a.mp3 for source@127.0.0.1...
strange error flushing buffer ... 
strange error flushing buffer ... 
2020/09/01 13:58:26 [audio_local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2020/09/01 13:58:26 [audio_local_1:3] Will try again in 3.00 sec.
2020/09/01 13:58:30 [audio_local_1:3] Connecting mount /stream-a.mp3 for source@127.0.0.1...
strange error flushing buffer ... 
strange error flushing buffer ... 
2020/09/01 13:58:30 [audio_local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2020/09/01 13:58:30 [audio_local_1:3] Will try again in 3.00 sec.
2020/09/01 13:58:34 [audio_local_1:3] Connecting mount /stream-a.mp3 for source@127.0.0.1...
strange error flushing buffer ... 
strange error flushing buffer ... 
2020/09/01 13:58:34 [audio_local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2020/09/01 13:58:34 [audio_local_1:3] Will try again in 3.00 sec.

**Screenshots**

![mount-1](https://user-images.githubusercontent.com/9286189/91892732-2aaa2d00-ec61-11ea-91c4-de6329debe27.jpg)
![mount-2](https://user-images.githubusercontent.com/9286189/91892727-28e06980-ec61-11ea-9924-bccae712f9bb.jpg)
![mount-3](https://user-images.githubusercontent.com/9286189/91892713-24b44c00-ec61-11ea-8edc-b412ae51df86.jpg)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 
All devices impacted.

**Additional context**

**Comment by jbsix** [comment]
After further testing, seems the issue is perhaps also related to reports of metadata not working #3142 #1397 and similarly when checking Icecast, the metadata is correct, however on Azuracast displays "stream offline". Also when attempting to connect via streamer account, connects however again metadata does not update.

**Comment by jbsix** [comment]
Issue seems metadata not updating and stuck on 'STREAM OFFLINE" as soon as I add relay stream url on mountpoint A - if anyone in the Azuracast community could try to reproduce based on steps outlined above to help determine if bug or issue with system latency and/or low disks space. If simply removing the REMOTE STREAM URL on the mount point admin page, the metadata works again. Anyone have any thoughts? @deepend-tildeclub @Xara

**Comment by jbsix** [comment]
EXPECTED BEHAVIOR: when the 'relay stream' is not playing azuracast would default to fallback mount and display metadata

**Comment by Xara** [comment]
I will create very low vps in my host and see if can reproduce it but some time ago that errors was  made by bad network disks configuration in my vps, now I have checked logs, is true that it seems, when you have the relays errors are showing up more frequently ....

**Comment by jbsix** [comment]
In the event this experimental setup is helpful to anyone, my solution has been to avoid using the relays (results unstable) and instead connect to a streamer account to achieve similar objective. When not live (playing from another icecast server) system fallbacks to the Azuracast install. Works as expected.

**Comment by adelynx** [comment]
I have the same issue, I just installed a new was instance and used the Docker installation and I have opened the port from aws firewall but it's not working I got `The file you requested could not be found` error if I try to hit directly the endpoint.

**Comment by kemecs** [comment]
here is the bug since yesterday's latest update:

2021/07/20 09:46:51 [local_1:3] Will try again in 3.00 sec.
2021/07/20 09:46:55 [local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
strange error flushing buffer ...
2021/07/20 09:46:55 [local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/07/20 09:46:55 [local_1:3] Will try again in 3.00 sec.
2021/07/20 09:46:59 [local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/07/20 09:46:59 [local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
strange error flushing buffer ...
