### ISSUE TITLE
Log shoutcast does not match the station.

### ISSUE THREAD

**Issue by radiobellissima** [AzuraCast/AzuraCast#3137]
I have found that I have a problem with shoutcast logs. In practice, by accessing the shoutcast administration page and requesting the log, the log of the last restarted station is displayed. How could I solve this annoying problem?

**Comment by Vaalyn** [comment]
I've looked into why this is and found that we are not configuring the `logfile` parameter for shoutcast which is why all shoutcast logs are going to the default `/tmp/sc_serv.log` location.
