### ISSUE TITLE
Please Add Song Album field to Media Manager column options

### ISSUE THREAD

**Issue by amavarick** [AzuraCast/AzuraCast#314]
**Please add an "Album" field to the media manager column options**.  Currently there are the following columns to show in the media manager page:

![mediamanager1](https://user-images.githubusercontent.com/20918832/33627086-6de8a904-d9ca-11e7-8bcb-ea600758f284.png)

The song album metadata is already captured from the files:

![songmetadata1](https://user-images.githubusercontent.com/20918832/33627110-821df672-d9ca-11e7-8a7f-20f201fb4fe7.png)

Adding this feature would be especially helpful when working with larger stations advanced or multiple playlists.  As always, thank you so much for your time.

Please consider adding the album column to the, "Request a Song" page as well.

**Comment by SlvrEagle23** [comment]
@amavarick Excellent idea, and an easy one to implement behind the scenes. Done and done!
