### ISSUE TITLE
shuffle mode don't work properly

### ISSUE THREAD

**Issue by habib1228** [AzuraCast/AzuraCast#3140]
I've been testing for several days, and the shuffle mode really repeat the same music frequently. For example, when music X plays now, after some hours it plays again. This happen several times in a day with several music files. 

Meanwhile, 'Rebuild AutoDJ Queue' works without issues. 

'Avoid duplicate artists' are enable.

Obs.: the main playlist (named 'principal') contain 781 music files, separated in several folders = **2.1 days with no need to repeat a single song!**

For test purposes again, in 2 september at 9:50 AM -03 the station was restarted and 'Rebuild AutoDJ Queue' was run again (without issues) -- since then nothing else has been modified or songs has been added,  but some "bugs" have occurred!

(i dont speak english very well, sorry!)

![Captura de tela de 2020-09-02 20-15-40](https://user-images.githubusercontent.com/70642841/92047354-4d207100-ed5b-11ea-8026-54cbefbc35d1.png)
![Captura de tela de 2020-09-02 20-15-53](https://user-images.githubusercontent.com/70642841/92047355-4db90780-ed5b-11ea-9a42-c795cbd2ba0f.png)
![Captura de tela de 2020-09-02 20-16-52](https://user-images.githubusercontent.com/70642841/92047356-4db90780-ed5b-11ea-9a04-1d54caff6a1c.png)
![Captura de tela de 2020-09-02 20-16-57](https://user-images.githubusercontent.com/70642841/92047357-4e519e00-ed5b-11ea-9dd1-0176753be75d.png)
![Captura de tela de 2020-09-02 20-17-05](https://user-images.githubusercontent.com/70642841/92047359-4eea3480-ed5b-11ea-9425-70d93ccdbc89.png)
![Captura de tela de 2020-09-02 20-17-07](https://user-images.githubusercontent.com/70642841/92047362-4eea3480-ed5b-11ea-84b5-e6640f38bdb9.png)
![Captura de tela de 2020-09-02 20-17-42](https://user-images.githubusercontent.com/70642841/92047363-4f82cb00-ed5b-11ea-8478-1a5f530a6beb.png)
![Captura de tela de 2020-09-02 20-17-53](https://user-images.githubusercontent.com/70642841/92047366-501b6180-ed5b-11ea-8b09-e54188d04377.png)
![Captura de tela de 2020-09-02 20-18-06](https://user-images.githubusercontent.com/70642841/92047368-50b3f800-ed5b-11ea-9f9b-79399c21c1b4.png)

and only this are "duplicated" songs:

![Captura de tela de 2020-09-02 20-43-22](https://user-images.githubusercontent.com/70642841/92048018-059ae480-ed5d-11ea-9ede-e87e30cfeacd.png)
![Captura de tela de 2020-09-02 20-43-26](https://user-images.githubusercontent.com/70642841/92048020-06cc1180-ed5d-11ea-8f37-22def531fd3a.png)

**Comment by SlvrEagle23** [comment]
@habib1228 Are you modifying the playlists in any way (adding to, or removing from, them) while the station is running? Any modifications trigger a "reshuffle" of the entire playlist so the new tracks can be included (or removed ones can be excluded). You may be noticing this instead of a more fundamental failure of the shuffling system.

**Comment by habib1228** [comment]
@SlvrEagle23 as I say, no, absolutely not.

**Comment by habib1228** [comment]
@SlvrEagle23 you can verify it yourself: folders and timeline shows date and hours

**Comment by habib1228** [comment]
hmmmm

maybe this "once per" playlist is the key for this error. This appears also here: [2669](https://github.com/AzuraCast/AzuraCast/issues/2669) and this guy also have a playlist with rule "once per". So, every time a song in playlist with that rule plays, the another playlist comes back and reshuffled.
