### ISSUE TITLE
Where is the php.ini file, I would need to make changes there!?

### ISSUE THREAD

**Issue by RememberForgottenHits** [AzuraCast/AzuraCast#3145]
It's not ISSUE but I can't find a way to change the php.ini file!?

The server is running Ubuntu 20.04 and I installed AzuraCast with docker installation method and also installed wordpress with docker installation method. I would like to change the upload_max_file_size and post_max_size in the php.ini file but I can't find the right place where located this php.ini file. It would be necessary to allow 2MB upload size to 50MB in wordpress.
As I understand it, all system files are hidden! I have found such a location but there are so many of these files and don't know which one is correct.
About here they are all located /var/lib/docker/overlay2/48d07e7e2a412037f61bee7a4a0594a5fe2200f8823dc0ece854a65b1e8839aa

**Comment by RememberForgottenHits** [comment]
What is right path? 
`~# locate php.ini
/var/lib/docker/overlay2/0bae4ba2eed8306a12ed244178f0c0e819f53da04a47020402f4542671b0a452/merged/etc/php/7.4/cli/php.ini
/var/lib/docker/overlay2/0bae4ba2eed8306a12ed244178f0c0e819f53da04a47020402f4542671b0a452/merged/etc/php/7.4/fpm/php.ini
/var/lib/docker/overlay2/0bae4ba2eed8306a12ed244178f0c0e819f53da04a47020402f4542671b0a452/merged/usr/lib/php/7.4/php.ini-development
/var/lib/docker/overlay2/0bae4ba2eed8306a12ed244178f0c0e819f53da04a47020402f4542671b0a452/merged/usr/lib/php/7.4/php.ini-production
/var/lib/docker/overlay2/0bae4ba2eed8306a12ed244178f0c0e819f53da04a47020402f4542671b0a452/merged/usr/lib/php/7.4/php.ini-production.cli
/var/lib/docker/overlay2/0bae4ba2eed8306a12ed244178f0c0e819f53da04a47020402f4542671b0a452/merged/var/azuracast/www/util/docker/web/php/php.ini.tmpl
/var/lib/docker/overlay2/2f940898f95df3db7da4a2e38dfe74cf436ac92e7503c00756294a7222969b03/diff/etc/php/7.4/cli/php.ini
/var/lib/docker/overlay2/2f940898f95df3db7da4a2e38dfe74cf436ac92e7503c00756294a7222969b03/diff/etc/php/7.4/fpm/php.ini
/var/lib/docker/overlay2/2f940898f95df3db7da4a2e38dfe74cf436ac92e7503c00756294a7222969b03/diff/usr/lib/php/7.4/php.ini-development
/var/lib/docker/overlay2/2f940898f95df3db7da4a2e38dfe74cf436ac92e7503c00756294a7222969b03/diff/usr/lib/php/7.4/php.ini-production
/var/lib/docker/overlay2/2f940898f95df3db7da4a2e38dfe74cf436ac92e7503c00756294a7222969b03/diff/usr/lib/php/7.4/php.ini-production.cli
/var/lib/docker/overlay2/392d9abbc8744fa5648c41c50338acd5b1ea836baa6763cef9f5b5d9843c0ce7/diff/var/azuracast/www/util/docker/web/php/php.ini.tmpl
/var/lib/docker/overlay2/9ac03b51727f49763c204d49ef9eb86706e73efc703ade00ec37cd8add29b4fa/diff/bd_build/php/php.ini.tmpl
/var/lib/docker/overlay2/c900c5910ee92587c6141773428938e95d4a2f7e8ba98234d474a019745c7dc4/diff/usr/local/etc/php/php.ini-development
/var/lib/docker/overlay2/c900c5910ee92587c6141773428938e95d4a2f7e8ba98234d474a019745c7dc4/diff/usr/local/etc/php/php.ini-production
/var/lib/docker/overlay2/f45a4ea1c8a6c6586e7be50f985863ef848f93488e7c6b53ad2fd3e2019b5dce/merged/usr/local/etc/php/php.ini-development
/var/lib/docker/overlay2/f45a4ea1c8a6c6586e7be50f985863ef848f93488e7c6b53ad2fd3e2019b5dce/merged/usr/local/etc/php/php.ini-production
`

**Comment by RememberForgottenHits** [comment]
It would be necessary to get this upload amount larger in wordpress. Currently it is 2MB but I would like to get it 50MB so that listeners can send me music files through the website.
![media-upload-wordpress](https://user-images.githubusercontent.com/34457020/92325516-4a23ca00-f054-11ea-901d-2bc3538c82ad.png)

**Comment by SC2Mitch** [comment]
AzuraCast does not operate WordPress nor own it, you'll need to contact your host to change this setting for you. 

If you are the hoster, you'll need to refer to several guides on how to change the default upload size.

**Comment by diego-vieira** [comment]
@RememberForgottenHits it's not a good idea to run AzuraCast along side another app.

**Comment by RememberForgottenHits** [comment]
> AzuraCast does not operate WordPress nor own it, you'll need to contact your host to change this setting for you.

I have my own personal VPS
 
> If you are the hoster, you'll need to refer to several guides on how to change the default upload size.
I used the tutorial on how to install wordpress on the azuracast --> https://www.azuracast.com/extending/multisite.html#how-it-works

Can you give me some tutorials that I should follow to edit the php.ini file?


> it's not a good idea to run AzuraCast along side another app.
They are in separate containers. Why developers then do such a tutorial, consequently they can be used together!?.

**Comment by ttodua** [comment]
Have anyone found how to edit `php.ini` for AzuraCast? Moreover, azuracast has multi-install mode, where wordpress is installed along it, however, i dont care about wordpress, i want to edit `php.ini` for AzuraCast .php plugins.

**Comment by Vaalyn** [comment]
Regarding overriding the `php.ini` of the WordPress Docker container you'll need to add a volume mount to the `docker-compose.override.yml` with the following `volumes` section and place a `php.ini` (would recommend using [this one](https://github.com/php/php-src/blob/master/php.ini-production) as the base for you own customizations) in the same directory as the `.yml` file:
```
...

services:
    wordpress:
        ...
        volumes:
            - ./php.ini:/usr/local/etc/php/conf.d/php.ini

...
```

----

We do not support directly editing the `php.ini` file of AzuraCast. If there is an option of the `php.ini` that is currently not changeable via the `azuracast.env` and that someone would like to have please let us know about it.

**Comment by ttodua** [comment]
@Vaalyn the PHP errors in wordpress container (which is installed according to the azuracast multi-instance tutorial), the errors (i.e. shell_exec or alike) are not outputed to browser. Only visible in php-error logs (called with `docker logs -f --details wordpress_wordpress_1`) . 

I've tried to include everything in php file, i.e.:
```
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

die( shell_exec("INEXISTENT COMMAND") );
```
nothing happens when page is visited, but the logs show that `inexistent command` had failure.
