### ISSUE TITLE
SSL/HTTPS not working on Icecast using web proxy

### ISSUE THREAD

**Issue by Jessydev01** [AzuraCast/AzuraCast#3147]
I have some issues with HTTPS/SSL on a fresh (Docker) AzuraCast install.
I enabled Web Proxy but unfortunately the direct Icecast stream doesn't have a SSL certifcate.
https://stream.domain.com/radio/8000 is working with SSL but https://stream.domain.com:8000 isn't.

What I have done so far:
- Fresh install VPS and AzuraCast
- Tried multiple Ubuntu versions, 16.04, 18.04 and 20.04.
- Enabled Web proxy + force to HTTPS in settings
- Multiple times `./docker.sh letsencrypt-create`
- Cheked if port 443 is attached to "docker-proxy"
- rebooted server multiple times

I'm running some older installations/updates without any problems on different servers and never had this issue before.

**Comment by SlvrEagle23** [comment]
@Jessydev01 After you've set up LetsEncrypt, try rewriting the station's configuration file via the station's management page, then `Utilities` in the left sidebar, then `Restart Broadcasting`. This should auto-detect the presence of the SSL certificates and point Icecast at the correct one.

**Comment by Jessydev01** [comment]
Unfortunately not working.

**Comment by cpeter1207** [comment]
@SlvrEagle23 I have also experienced this issue. The icecast config points at default.crt rather than my letsencrypt-generated cert. I've worked around it for now by copying my domain-specific cert and private key to default.crt...etc. I haven't taken time to investigate this further.

**Comment by Jessydev01** [comment]
@cpeter1207 Could you please share your workaround?
