### ISSUE TITLE
dj web page problem

### ISSUE THREAD

**Issue by fast97** [AzuraCast/AzuraCast#3150]
**Host Operating System**

**To Reproduce**

**Describe the bug**
Hello, the dj web page already encodes well and displays the live icon for a few seconds then disappears and also no live sound on the air.
Thank you

**Relevant Logs**
2020/09/07 16:24:49 [cross_7766:3] Analysis: -14.881016dB / -17.032903dB (2.98s / 3.02s)
2020/09/07 16:24:49 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/09/07 16:24:50 [lang:3] AzuraCast Feedback Response: OK
2020/09/07 16:25:54 [lang:3] Authenticating DJ: moimoi
2020/09/07 16:25:55 [lang:3] AzuraCast DJ Auth Response: true
2020/09/07 16:25:55 [decoder:3] Method "MAD" accepted "audio/mpeg".
2020/09/07 16:25:55 [lang:3] DJ Source connected! Last authenticated DJ: moimoi - [("Host", "live.streamantille.com"), ("Upgrade", "websocket"), ("Connection", "upgrade"), ("X-Real-IP", "81.194.19.36"), ("X-Forwarded-For", "81.194.19.36"), ("X-Forwarded-Proto", "https"), ("X-Forwarded-Ssl", "off"), ("X-Forwarded-Port", "443"), ("Origin", "https://live.streamantille.com"), ("Sec-WebSocket-Protocol", "webcast"), ("Pragma", "no-cache"), ("Cache-Control", "no-cache"), ("Sec-WebSocket-Key", "NK2cACKfIqUD9txyYNkNXw=="), ("Sec-WebSocket-Version", "13"), ("Sec-WebSocket-Extensions", "x-webkit-deflate-frame"), ("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15")]
2020/09/07 16:25:55 [lang:3] AzuraCast Live Connected Response: true
2020/09/07 16:25:55 [aor_input_streamer:3] Decoding...
2020/09/07 16:26:09 [aor_input_streamer:3] New metadata chunk ? -- ENTREE.
2020/09/07 16:26:12 [lang:3] Authenticating DJ: moimoi
2020/09/07 16:26:13 [lang:3] AzuraCast DJ Auth Response: true
2020/09/07 16:26:39 [aor_input_streamer:3] Timeout reached!
2020/09/07 16:26:39 [aor_input_streamer:2] Error while reading from client: Timed out after waiting for 30.00 sec.
2020/09/07 16:26:39 [lang:3] DJ Source disconnected! Current live DJ: moimoi
2020/09/07 16:26:42 [lang:3] AzuraCast Live Disconnected Response: true
2020/09/07 16:26:42 [aor_input_streamer:2] Feeding stopped: Mad.End_of_stream.
2020/09/07 16:26:42 [lang:3] DJ Source disconnected! Current live DJ: 
2020/09/07 16:26:42 [lang:3] AzuraCast Live Disconnected Response: true
2020/09/07 16:27:18 [lang:3] AzuraCast Raw Response: annotate:playlist_id="265",title="Djadja ",artist="Aya Nakamura",duration="175.07",song_id="25b5041a377bc5cec3b594014bb49529",media_id="12566",liq_amplify="0.00dB":/var/azuracast/stations/radio_demo/media/All musique/aya_nakamura_-_djadja.mp3
2020/09/07 16:27:18 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/radio_demo/media/All musique/aya_nakamura_-_djadja.mp3".

**Screenshots**

**Device(s):**

 - OS: 
 - Browser:  chrome, safari] 

**AzuraCast version**
 - Version: v0.10.3, #f8c04b4 (2020-09-01 0:54)

**Comment by diego-vieira** [comment]
@fast97 your bug report is spot on.

Did you install AzuraCast in a fresh server install? 
If so, what's what server version? Ubuntu 18, 20? Debian?

Looks like you've used Safari to connect to the Web DJ, have you tried Chrome or Firefox?

**Comment by fast97** [comment]
Hello,
I have debian as linux and its still working well, the installation is not new. I have used browsers, safari and chrome. the problem is the same.
thank you
________________________________
De : Diego Vieira <notifications@github.com>
Envoyé : mercredi 9 septembre 2020 22:23
À : AzuraCast/AzuraCast <AzuraCast@noreply.github.com>
Cc : fast97 <thierry.fast@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [AzuraCast/AzuraCast] dj web page problem (#3150)


@fast97<https://github.com/fast97> your bug report is spot on.

Did you install AzuraCast in a fresh server install?
If so, what's what server version? Ubuntu 18, 20? Debian?

Looks like you've used Safari to connect to the Web DJ, have you tried Chrome or Firefox?

**Comment by fast97** [comment]
269/5000
Hello, I did a new installation with ubuntu 20 and always the same the dj web page shows the dj connected for 30 seconds and no sound then cuts.  there are backups which are made automatically every 2 hours. I still don't understand. thank you
