### ISSUE TITLE
Docker - Errore nelle play list

### ISSUE THREAD

**Issue by radiocampania** [AzuraCast/AzuraCast#3153]
Errore nelle PlayList URL Remoto non vanno in onda 

**Using Docker installation method**

**AzuraCast version**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by diego-vieira** [comment]
@radiocampania please write your questions in English.

Also you didn't provide any screenshot or the details of the error.
Could you please fix your bug report?

Thank you
