### ISSUE TITLE
#1862  cant install

### ISSUE THREAD

**Issue by Dancbeunny98** [AzuraCast/AzuraCast#3154]
#1862
![image](https://user-images.githubusercontent.com/37336183/92546568-92f99f80-f25b-11ea-84d1-a8fc43c130d0.png)

**Comment by SlvrEagle23** [comment]
@Dancbeunny98 Can you tell me how you went through the process of installing? Did you encounter any errors before this?

This type of error definitely shouldn't appear with our Docker images, since the vendor dependencies are all built into the image itself before it ships.

**Comment by Dancbeunny98** [comment]
I have vestacp set, but it does not affect in any way. tested it on a clean system.

**Comment by Dancbeunny98** [comment]
There are no other errors.

**Comment by Dancbeunny98** [comment]
![image](https://user-images.githubusercontent.com/37336183/92595307-d4ff0180-f2ac-11ea-9d44-f66d6fcfa265.png)

**Comment by Dancbeunny98** [comment]
![image](https://user-images.githubusercontent.com/37336183/92595473-14c5e900-f2ad-11ea-963c-46a9306211a7.png)

**Comment by Dancbeunny98** [comment]
![image](https://user-images.githubusercontent.com/37336183/92641274-29bf6e00-f2e7-11ea-904c-12b317c89b87.png)
![image](https://user-images.githubusercontent.com/37336183/92641292-2f1cb880-f2e7-11ea-9e1f-44bfaa97fe60.png)

**Comment by Dancbeunny98** [comment]
![image](https://user-images.githubusercontent.com/37336183/92675321-c144b100-f327-11ea-9ca3-e8bea8e8dd20.png)

how fix????? im reinstall system again)

**Comment by SlvrEagle23** [comment]
@Dancbeunny98 what install commands are you running? This definitely shouldn't be happening with the Docker installation.

**Comment by Dancbeunny98** [comment]
I am using the standard installation. As written in the instructions. And I don't do anything else.


```
mkdir -p /var/azuracast
cd /var/azuracast
```

```
curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh
chmod a+x docker.sh
./docker.sh install
```

**Comment by Dancbeunny98** [comment]
I really want to fix this. But the problem remains the same. Either the problem is with the database, or this one.

**Comment by Dancbeunny98** [comment]
I am using a clean system with only SSH installed and system utilities. Nothing more.

**Comment by Dancbeunny98** [comment]
HOW FIX???

**Comment by stemvantwente** [comment]
@Dancbeunny98 you sure ur host support docker 100%? seems you have the same problem I have my host doesnt support docker fully :(  So I use the ansible installation on my clean server thats working 100% for me.
