### ISSUE TITLE
/var/azuracast/www/util/ansible/roles/azuracast-build/tasks/main.yml': line 29, column 3

### ISSUE THREAD

**Issue by j2sdwebradio** [AzuraCast/AzuraCast#3156]
Hello 

Hit:2 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Hit:3 http://ams2.mirrors.digitalocean.com/mariadb/repo/10.2/ubuntu bionic InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
Hit:5 http://ppa.launchpad.net/avsm/ppa/ubuntu bionic InRelease
Hit:6 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
Hit:7 https://repos.influxdata.com/ubuntu bionic InRelease
Hit:8 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
Hit:9 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu bionic InRelease
Hit:10 http://ppa.launchpad.net/chris-needham/ppa/ubuntu bionic InRelease
Hit:11 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
Reading package lists... Done
Reading package lists...
Building dependency tree...
Reading state information...
python-mysqldb is already the newest version (1.3.10-1build1).
ansible is already the newest version (2.9.13-1ppa~bionic).
The following packages were automatically installed and are no longer required:
  libjemalloc1 linux-raspi2-5.3-headers-5.3.0-1019 linux-raspi2-5.3-headers-5.3.0-1021 linux-raspi2-5.3-headers-5.3.0-1022 linux-raspi2-5.3-headers-5.3.0-1023 linux-raspi2-5.3-headers-5.3.0-1026 linux-raspi2-5.3-headers-5.3.0-1027
  linux-raspi2-5.3-headers-5.3.0-1028 linux-raspi2-5.3-headers-5.3.0-1030
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 115 not upgraded.
Updating AzuraCast (Environment: production, Update revision: 57)
HEAD is now at e60c2bc03 #3042 -- Update Nowplaying library to incorporate a minor JSON fix.
Already up to date.
ERROR! unexpected parameter type in action: <type 'bool'>

The error appears to be in '/var/azuracast/www/util/ansible/roles/azuracast-build/tasks/main.yml': line 29, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Set permissions of generated frontend content
  ^ here

**Comment by seasharp76** [comment]
I have the exact same error, using install.sh on Ubuntu 16.04 and 18.04.   Please help!

**Comment by diego-vieira** [comment]
did you tried in a fresh install?

**Comment by seasharp76** [comment]
Brand new install.  the only item I installed was "unzip" in order to unzip the archive.

**Comment by diego-vieira** [comment]
I have deployed a few using Docker and Ubuntu/CentOS without issues using a fresh install.

Just make sure you have at least 2GB, meaning if you use DigitalOcean's droplet use the second option, not the first.

**Comment by SlvrEagle23** [comment]
@j2sdwebradio Apparently the "warn" flag isn't present in older Ansibles and is causing a problem. I went ahead and reverted it and that should bring things back to normal for the older Ubuntus.

**Comment by j2sdwebradio** [comment]
Hello,
@SlvrEagle23  Thanks for your speed, this is resolved.

**Comment by seasharp76** [comment]
With Docker it installed properly.  Thank you!
