### ISSUE TITLE
Ubuntu 20.04.1 Docker Question: Storage Space

### ISSUE THREAD

**Issue by Nightmare-Night** [AzuraCast/AzuraCast#3157]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.3, #e60c2bc (2020-09-09 4:06) Rolling • Docker • PHP 7.4 

**Host Operating System**
Ubuntu 20.04.1

**Describe the question**
Being a first time user of AzuraCast, I've absolutely loved the experience I've had with it. Starting out with a docker image on Digital Ocean, I've now been wanting to head over to my own dedicated server with it. However, I've been experiencing one problem. I purposely gave the machine I'm running AzuraCast on a large amount of storage space for the purpose of media storage, however, I'm running into one issue. The docker image isn't using all that space it can within the machine.

What I'm wondering is if there is a quick and simple guide that could either be added to the wiki or just in this issue on how to increase the amount of storage AzuraCast sees for media storage.

**Comment by diego-vieira** [comment]
Do you mean here?

What's the amount of storage you've got vs what AzuraCast sees?

![image](https://user-images.githubusercontent.com/930792/92654612-faf5c780-f2e7-11ea-9c74-34eb511accac.png)

**Comment by Nightmare-Night** [comment]
Yeah, just the overall "Server Status" storage space amount.
![image](https://user-images.githubusercontent.com/19337788/92655006-f01e4100-f2ad-11ea-9205-c14396d9e43e.png)


This is what cfdisk shows me _is available_:
![image](https://user-images.githubusercontent.com/19337788/92655027-fa403f80-f2ad-11ea-8ad5-25c353084226.png)

**Comment by diego-vieira** [comment]
That storage number comes from this line https://github.com/AzuraCast/AzuraCast/blob/63e0040e8f6b657e627d61378c5944df4cace086/src/Entity/Station.php#L1008 which is default from PHP.

I think that @SlvrEagle23 could provide some insight as it might have to do with how docker filesystem works.


Mine looks spot on - DigitalOcean, 55GB droplet.

![image](https://user-images.githubusercontent.com/930792/92656701-69885480-f2eb-11ea-835c-9e026adc030c.png)
![image](https://user-images.githubusercontent.com/930792/92656735-773dda00-f2eb-11ea-96a0-e3edb794bc66.png)

**Comment by Nightmare-Night** [comment]
Think there is anyway I could override this or verify that it is grabbing the whole drive?

This is a fresh install of Ubuntu with a fresh install of Azuracast.

**Comment by SpeedyCharly** [comment]
Do you have a value set here?
![Azur](https://user-images.githubusercontent.com/66107794/93221897-47a02f00-f73c-11ea-976f-f9fee1c755ff.jpg)

**Comment by Nightmare-Night** [comment]
I do not have anything set in that area.

**Comment by pimjansen** [comment]
Are you using a partioned filesystem? The default configuration is using the docker filesystem for all.the volumes which default to /var/lib/docker.

So technically not the location of your install. Can you confirm the storage spaces on the machine?
