### ISSUE TITLE
OpenApi docs generated are not to spec - api requests an `int64` where the schema only has `number`

### ISSUE THREAD

**Issue by jasikpark** [AzuraCast/AzuraCast#3158]
unknown

**Using Docker installation method**

yes.
**AzuraCast version**

v0.10.3, #9811fbb (2020-06-22 4:38) • Docker • PHP 7.4

**Host Operating System**

unknown
**Describe the bug**

**To Reproduce**

**Expected behavior**

Interacting with the swagger ui works -- the "demo this endpoint" behavior where you enter a parameter works.

**Relevant Logs**

**Screenshots**

<img width="562" alt="Screen Shot 2020-09-09 at 7 38 27 PM" src="https://user-images.githubusercontent.com/10626596/92668434-69c92580-f2d4-11ea-805c-1bcdeaf2fc83.png">

**Device(s):**
 - Device:  
Desktop
 - OS: 
macOS
 - Browser: 
Firefox
 - Version: 
80.0.1

**Additional context**

Here's a few options for OpenApi linting that look good to me:
- https://nordicapis.com/8-openapi-linters/
- https://github.com/IBM/openapi-validator
- https://openapi.tools/

I was able to find the reason for my screenshot via the vscode extension for OpenApi linting by 42crunch.

**Comment by SlvrEagle23** [comment]
@jasikpark I believe we fixed this as of a recent update...are you on the latest rolling-release version of 0.10.3?

**Comment by jasikpark** [comment]
0.10.3, yes, rolling-release i'm not sure

**Comment by jasikpark** [comment]
v0.10.3, #9811fbb (2020-06-22 4:38) • Docker • PHP 7.4

**Comment by jasikpark** [comment]
mentioned in #3054, fixed in https://github.com/AzuraCast/AzuraCast/commit/391702bfe91794cc7f33a38e2d8972abb29face8?

**Comment by jasikpark** [comment]
So it seems to not be fixed in 0.10.3, which is what we're running: 9811fbbcb2c7facbf4c53c6b58feb660ba2a675d

**Comment by SlvrEagle23** [comment]
@jasikpark If the update was published after the version you're on, just update to the newer version. That's how our rolling-release model works.

**Comment by jasikpark** [comment]
Ah. Apparently I will have to wait for them to update to the next tagged release. :/

thanks for the help

**Comment by jasikpark** [comment]
The newer version doesn't exist, i.e.

**Comment by SlvrEagle23** [comment]
@jasikpark I think numbering the rolling-release versions along with the latest stable release version they're associated with has caused some confusion here. You should update to the latest rolling-release version; we do not have a stable release yet with the incorporated fixes, as we haven't released a new version since then.
