### ISSUE TITLE
Is there a specific reverse proxy script that I need to use for Azuracast? If so, where do I get it?

### ISSUE THREAD

**Issue by klebdotio** [AzuraCast/AzuraCast#3159]
Hi, I have just setup AzuraCast on my Server, however the builtin way of enabling HTTPS and it's reverse proxy aren't working. I suspect this is due to my configuration, as I have other sites running on port 80 and 443, but is there a specific script I should add to my NGINX to get AzuraCast working correctly? If so, where do I get it/what is it. 

Thanks

**Comment by Vaalyn** [comment]
If you want to run the web interface of AzuraCast on other ports check out this guide: https://www.azuracast.com/help/docker/#use-non-standard-ports

The command will prompt you for the ports that you want to use for http/https and ssh.

**Comment by klebdotio** [comment]
Thank you.
