### ISSUE TITLE
24 hour time format

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#316]
can I make the time format 24 hours, when choosing the work of a playlist? Just in this format it is not clear how to choose and not convenient, thank you.

**Comment by mickaelmonsieur** [comment]
Exact! It's hard to know if it's AM or PM because the hours are duplicate in the drop-down list.

**Comment by SlvrEagle23** [comment]
I have published an update to the code that will change the way time is formatted based on whether the locale uses 24-hour or 12-hour formatting by default. Interestingly enough, out of our currently supported locales, only English (en_US.UTF-8) uses a 12-hour clock by default, so the others just default to using a 24-hour clock.

This should fix any issues with time not formatting properly when creating playlists.

**Comment by mickaelmonsieur** [comment]
Hi,
Thanks for update.

`From https://github.com/AzuraCast/AzuraCast
   ee0d814..b8a7498  master     -> origin/master
Updating ee0d814..b8a7498
Fast-forward
 app/bootstrap/settings.php                        |  6 ++++++
 app/config/forms/playlist.conf.php                | 11 +++++++++--
 app/models/StationPlaylist.php                    | 16 +++++++++++++++-
 app/modules/stations/views/playlists/index.phtml  |  4 ++--
 app/modules/stations/views/reports/timeline.phtml |  2 +-
 app/src/AzuraCast/Customization.php               | 63 +++++++++++++++++++++++++++++++++++++++++++++------------------
 6 files changed, 78 insertions(+), 24 deletions(-)`

Now, the drop-down is understandable. 👍 
But now, in the playlists list, the time is not correct.

In drop-down:  10:00 CET (09:00 UTC)
In the list: "Une fois par jour Joue à 01:00"
