### ISSUE TITLE
Question: Using local M3U.

### ISSUE THREAD

**Issue by joshms123** [AzuraCast/AzuraCast#3165]
Hi there,
I was just wondering if there is a way to use a local M3U playlist within azuracast?
I have generated an M3U playlist from the media/music directory with a query in the beets software. The new playlist is now located in the stations playlists folder. All paths are the same as what azuracast can access for the music files.
Is there a way of using this M3U in a new playlist?
Thanks for any help in advanced.

**Comment by Vaalyn** [comment]
I haven't used this myself yet but if you want to create a playlist from the M3U I think the `Import from PLS/M3U` function in the Playlists management should do the trick. You will have to create a new playlist first and then use the button that I've marked on the following screenshot:

![image](https://user-images.githubusercontent.com/13745863/92976697-6e840a00-f48b-11ea-88f5-3f8cddae96a0.png)
