### ISSUE TITLE
let's encrypt self signed certificate

### ISSUE THREAD

**Issue by DomeMilch** [AzuraCast/AzuraCast#3166]
**Using Docker installation method**

yes
**AzuraCast version**
 latest

**Host Operating System**

Debian 10 
**Describe the bug**

renew letsencrypt certificate and the system self signed it. 
**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

[http://prntscr.com/ug0iyh](http://prntscr.com/ug0iyh)
**Device(s):**
 - Device:  Desktop
 - OS:  Windows 10
 - Browser:  Chrome
 - Version:  *

**Additional context**

I am using everytime the standart commands like:
cd /var/azuracast
./docker.sh update-self
./docker.sh letsencrypt-create

but now it doesen't work and  it self signed the certificate.. 
i looked up for a solution, But I didn't find anything that could help me.

**Comment by picpakdog** [comment]
I'm having a similar issue, I was following this guide by mistake until I realized I needed to use LE: https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-nginx-in-ubuntu-18-04

I removed the files it created (/etc/ssl/private/nginx-selfsigned.key, /etc/ssl/certs/nginx-selfsigned.crt, /etc/nginx/dhparam.pem) but I'm still stuck with the self-signed certificate, and when I run ./docker.sh letsencrypt-create, it doesn't even attempt to create a certificate:

```
Domain name (example.com) or names (example.com,foo.bar) to use with LetsEncrypt [mydomain.com]: mydomain.com
Optional e-mail address for expiration updates [my@email.com]: my@email.com
Stopping azuracast_web ... done
Going to remove azuracast_web
Removing azuracast_web ... done
azuracast_influxdb_1 is up-to-date
azuracast_redis_1 is up-to-date
azuracast_mariadb_1 is up-to-date
azuracast_stations is up-to-date
Creating azuracast_web ... done
azuracast_nginx_proxy_1 is up-to-date
azuracast_nginx_proxy_letsencrypt_1 is up-to-date

```

**Comment by gunsar** [comment]
> **Using Docker installation method**
> 
> yes **AzuraCast version**
> 
> latest
> **Host Operating System**
> 
> Debian 10 **Describe the bug**
> 
> renew letsencrypt certificate and the system self signed it. **To Reproduce**
> 
> **Expected behavior**
> 
> **Relevant Logs**
> 
> **Screenshots**
> 
> http://prntscr.com/ug0iyh **Device(s):**
> 
> * Device:  Desktop
> * OS:  Windows 10
> * Browser:  Chrome
> * Version:  *
> 
> **Additional context**
> 
> I am using everytime the standart commands like: cd /var/azuracast ./docker.sh update-self ./docker.sh letsencrypt-create
> 
> but now it doesen't work and it self signed the certificate.. i looked up for a solution, But I didn't find anything that could help me.

I tried Using Custom Certificates like the instructions on azuracast.com didn't work, then tried to replace it as you said replacing it with default.crt and defalut.key so I can use paid ssl, still not working well.
after checking in SSL Checker, still what is detected Let's Encrypt
I'm confused with this problem
