### ISSUE TITLE
Unsecure

### ISSUE THREAD

**Issue by jaco45** [AzuraCast/AzuraCast#3169]
Since 5 days ago listening on chrome it blocks the site saying it is not secure. Since then I have not had a single listener. This is a serious problem!

**Comment by SC2Mitch** [comment]
Have you tried running the let's encrypt command?

**Comment by jaco45** [comment]
I have no idea what that is or how to do it. Strange  as for months it was fine and out of the blue everyone visiting my radio link gets blocked by chrome and Edge.

**Comment by SlvrEagle23** [comment]
@jaco45 If you've recently updated from a somewhat older version of AzuraCast, you may be running into issue #2855, and can follow the instructions on how to fix the issue in the top post on that thread.

**Comment by Velozo192** [comment]
If you have a SSL Cloudflare connected domain name, you can redirect it through a .htaccess file. Currenty I did this, and the site is running secured.
