### ISSUE TITLE
Music Files - play a single file changes the Icon for all others

### ISSUE THREAD

**Issue by YosefAdPro** [AzuraCast/AzuraCast#3170]
**Using Docker installation method**

NO
**AzuraCast version**

0.10.3
**Host Operating System**

Ubuntu 18.4
**Describe the bug**

When you play one playback file, the icon of the other files changes

**To Reproduce**

 Go to > Music Files > Play singel file....

**Expected behavior**

Only the file being played will appear with the Play icon

**Relevant Logs**

**Screenshots**

![ezgif-7-73f68eb1f6a0](https://user-images.githubusercontent.com/11810187/93018280-3ab5fb00-f5d7-11ea-93e0-1fad91878a37.gif)

**Device(s):**
 - Device:  
 - OS:  windows 10
 - Browser:  Chrome
 - Version:  Last

**Additional context**

**Comment by SlvrEagle23** [comment]
@YosefAdPro Thank you for the report. This is fixed in the latest rolling release.
