### ISSUE TITLE
Server Load Issue

### ISSUE THREAD

**Issue by danyalsaleemqureshi** [AzuraCast/AzuraCast#3171]
**Using Docker installation method**
No

**AzuraCast version**
Latest

**Host Operating System**
Ubuntu

**Describe the bug**
Running 10 Stations on 64 KBPS With AutoDJ enabled, Issue is PHP Process is taking a lot of load, 90% to 95% Every Sec, Anyway to Reduce?

**Comment by adoboligh1** [comment]
Server Loads Are Even Higher On Docker.
