### ISSUE TITLE
[not an issue] Random / Shuffle

### ISSUE THREAD

**Issue by eskapiste** [AzuraCast/AzuraCast#3173]
hey, guys, go a question. 
whats the difference between random and shuffle playback of tracks in playlist?

as i understand it now, when shuffle is selected, autodj will shuffle playlist once and play this tracks in this shuffled order.
and if “random” is selected - it will always randomise next track.

is it correct?

**Comment by SlvrEagle23** [comment]
@eskapiste Correct. I've updated the text so that in the latest version it properly explains this directly inside the application, since we seem to get a lot of questions about it.
