### ISSUE TITLE
Custom SSL Certificate showing up as signed by "localhost"

### ISSUE THREAD

**Issue by klebdotio** [AzuraCast/AzuraCast#3175]
Due to the setup of my network, I cannot put Azuracast on port 80, which means I cannot use http-01 for ACME verification, so instead, I generate my certificates with dns-01 via cloudflare's API, I generated my certificate, converted it to .crt and added it to my docker-compose.override.yml, however my SSL is coming up as signed by "localhost" I am not familiar with how docker really works, so I have no idea on how to identify a problem like this.

I read the issue that said to set the certificate name to the website, and I did this, but it still doesn't work. Also, if I add :ro to the end, it doesn't even start. I am using port 8082 for http, and 8082 for https, do I need to add these ports somewhere other than in the Azuracast change-ports thing?

my override:
services:
  web:
    volumes:
      - /etc/letsencrypt/live/azuracast.****.net/azuracast.****.net.crt
      - /etc/letsencrypt/live/azuracast.****.net/azuracast.****.net.key

**Comment by Vaalyn** [comment]
Take a look at the `Using Custom Certificates` section posted in this issue here: https://github.com/AzuraCast/AzuraCast/issues/2855 that should get this working with your custom cert.
