### ISSUE TITLE
External MP3 Trips and stutters

### ISSUE THREAD

**Issue by RosiersRobin** [AzuraCast/AzuraCast#3176]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.3, #9811fbb (2020-06-22 4:38) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
I have an external .mp3 in a playlist to be triggered at 0 minutes every hour. The file is perfectly playable in the browser, thes are my settings:

https://i.imgur.com/24UnveP.png
https://i.imgur.com/pP37iWo.png (Yes the buffer is 600 seconds, but at 5 or so, it also doesn't work)
https://i.imgur.com/XlDJ4va.png
https://i.imgur.com/GamkOSC.png

**To Reproduce**

**Expected behavior**
Just playing the whole mp3 file to have  'news'.

**Screenshots**
Se above

**Device(s):**
 - Device: PC  
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 85.0.4183.102 

**Additional context**

The file I want to play is the following:
https://progressive-audio.lwc.vrtcdn.be/content/fixed/11_11niws-snip_hi.mp3

**Comment by ITC-Media** [comment]
Same problem here
