### ISSUE TITLE
Stream metadata stops updating after a few hours

### ISSUE THREAD

**Issue by Velozo192** [AzuraCast/AzuraCast#3178]
Hello there,

Currently my streaming server and everything are set-up perfectly and everything works great, only I have one issue with the metadata. In the beginning it updates it, but after a few hours it won't update it anymore and is just stuck on 1 artist/title.

Liquidsoap log:
https://gyazo.com/632c26d1386eef0526095bf79c038ca7

Shoutcast log:
https://gyazo.com/06d1f5c15f7ea6593c378e56468147ce

System Debug Error:
https://gyazo.com/2a0317c682900b479c29b8590a4df6a9

I hope that someone can help me to fix this problem and that I gave enough information.

With kind regards,
Velozo

**Comment by Velozo192** [comment]
Someone that can help me?

**Comment by AaronUnmuted** [comment]
I can confirm that we are also experiencing this issue, alongside no listener statistics, on the latest build: Rolling Release #f62a04c

**Comment by Velozo192** [comment]
Alright, currently I have found a solution for this problem, apparently it was the extern relay option. I have removed the extern relay connection and removed the ports in the system settings, which automatically generates newer ports. The stream does still have audio output and the error is gone.
