### ISSUE TITLE
A Message from the AzuraCast Developer: PLEASE READ THIS before creating new issues!

### ISSUE THREAD

**Issue by SlvrEagle23** [AzuraCast/AzuraCast#318]
Hello all,

My name is Buster Neece (or "Silver Eagle" online), and I am the lead and sole developer of this project, AzuraCast. I created this project as an open-source alternative to the existing large, monolithic radio broadcast tools that was more agile, more nimble and used newer technologies to make life easier. I'm very happy to discover that so many people have found AzuraCast useful, and use it every day in their radio stations.

Unfortunately, AzuraCast doesn't pay the bills. In fact, these days, nothing does. I have spent the better part of the last two years struggling with a disability that leaves me largely unemployable in the traditional sense, and has robbed me of my life's savings and threatens to leave me homeless and unable to receive proper medical care in the coming year.

I'm not saying that to elicit sympathy, but rather to explain that AzuraCast is my pleasant escape from the troubles that haunt me in my everyday life. Working on this project has helped keep me mentally sharp, and has given me an incubator to test cutting-edge technology. In this way, AzuraCast is invaluable, as it frankly helps me from going nuts from boredom or lack of purpose.

However, lately I've noticed a trend toward pushier, more aggressive tickets being created by newer users who don't understand that this is a one-developer project meant as a fun hobby, not a big business enterprise with the fiscal latitude to handle technical support and a flood of new feature requests. In some cases, when I fail to respond for a day or two on here, people will crawl the web looking for my personal e-mail address, using it to send the same rude requests directly to my inbox. The tone of these issues, frankly, hasn't been appropriate for this software, and has pushed me away from working on it almost entirely.

In the coming weeks, I'm going to try to refocus my efforts on this project toward the respectful, supportive people with great ideas that keep me going. If I don't respond to a ticket at all, please don't take it personally, and **please** don't e-mail me on my personal e-mail accounts to complain further. In the absence of more direct assistance, this is the only way I can continue this project and maintain some semblance of pride and happiness in doing it.

Thank you all for your patience and support.

(This isn't the point of this message, but if you're interested in supporting me this holiday season, any help would be greatly appreciated: https://ko-fi.com/SilverEagle )

**Comment by StreamDude** [comment]
Well said ! 
People need to realize that this great piece of software is all for free.
They can't keep dropping requests time after time and demand that these things will be implemented/solved within a few hours.
Respect the maker and his product !

**Comment by amavarick** [comment]
I just donated to your ko-fi account.  I hope you can buy yourself dinner somewhere.  Buster, outside of my day job, most of my online work deals with projects for non-profits free of charge as a labor of love.  My spouse and I teach childbirth education as well and do so for the underprivileged too.  I find that people that don't pay for a product/service often don't respect the work that goes into it.  That's very sad but not reflective of what I hope to be the greater majority.

My point is that there are plenty of people who really do appreciate your work for what it is and respect the quality and attention to detail required to even attempt such a project.  PLEASE don't let the few rude loudmouths ruin the enjoyment and satisfaction that you should get for creating such a great product.

Maybe a suggestion... Creating a forum to move the how to questions and general BS involved with user error over to the forum so the GitHub requests are left largely to actual bug fix and feature requests.  I think other users are more likely to contribute in a forum than in the GitHub issues tab.

Your product maturity seems to be at the point where you are finished with major bug fixes and most of the minor bug fixes and the rest focusing more on general product direction.  Maybe feature requests could go over to the forum or at least listed there to show requested, approved, planned and rejected?  This would give us users an idea of general product direction and allow us to see what was previously requested/rejected and not clog up your GitHub "issues" tab.

Another thought, if someone poses a feature request, what's wrong with placing a price tag on it and allow people to donate to a certain level before beginning development of that feature?  This would help your employment status and really see what features are most important to people?  I don't think OpenSource is intended to deny the author from being able to be remunerated for their work!  Please take these suggestions above as an attempt to brainstorm to lighten your load and not to increase the work load!

**Comment by susl16c** [comment]
This bad person was me. How can you know how many people are developing a product. I just asked a question
> Tell me please when will the next release of AzuraCast where you correct all the errors?
I asked the author for forgiveness by mail. I did not know that such a question could bring grief to the author. Forgive me once again.

**Comment by kbysfm** [comment]
@SlvrEagle23 thanks for the hard work and dedication. You're an amazing developer! I will talk to my CIO about supporting you this amazing solution.

**Comment by SlvrEagle23** [comment]
@amavarick 

> I just donated to your ko-fi account.

I saw your donation, and thank you very much. :)

> Maybe a suggestion... Creating a forum to move the how to questions and general BS involved with user error over to the forum so the GitHub requests are left largely to actual bug fix and feature requests.

I like where you're going with this idea, but I think the reality would be that a forum would be both more maintenance work on my end (in terms of spinning up a server that can run them, and keeping that secure and up to date) and moderation work as well. My current plans are to work on drafting a Code of Conduct for how tickets should be structured on here, and to have more clear guidelines, so that I have something to point to if I think people are being unruly or just rude.

> Your product maturity seems to be at the point where you are finished with major bug fixes and most of the minor bug fixes and the rest focusing more on general product direction. 

This is generally how I see it right now...the project's settled into its niche in the world, and all that remains is to make little improvements here and there, to keep it secure and up-to-date. That's still pretty formidable work, but it's not as big of an undertaking as it was two years ago!

> Another thought, if someone poses a feature request, what's wrong with placing a price tag on it and allow people to donate to a certain level before beginning development of that feature? This would help your employment status and really see what features are most important to people? I don't think OpenSource is intended to deny the author from being able to be remunerated for their work!

I fully agree with you, but there's a story about this subject that I haven't shared here on Github with anybody, and it relates directly to this project.

Earlier this year, I was approached by a person who claimed that they were interested in using AzuraCast in a commercial setting. Basically, it was meant to replace a far more expensive set of infrastructure with commodity hardware and FOSS software, so it sounded like a win-win to me.

The person offered to sponsor my development in the same way that major companies sponsor FOSS projects: by paying for the time of the developers to add/fix certain priority features, while ensuring their contributions still remain out in the open. This was exactly what I had dreamed of for AzuraCast, and I eagerly accepted the fairly short initial task list they provided.

Just over two weeks of extremely hard work later, the work was done, the project items were checked off, and I reported back to the person for an update and for the first round of payment. Nothing. I e-mailed and followed up week after week, month after month, contacting them via every medium I could, and they were gone. They had taken the improvements to the code and run, leaving me without any compensation at all.

If this had been back when I was a gainfully employed senior developer, I'd have shrugged my shoulders and said "oh well" and gone back to my day job. For it to happen now, though...it cut deep. AzuraCast was my pride and joy, the product of untold hours of love and passion for what I do, and my passion for it had been sapped entirely dry by someone taking advantage of a developer who was, and is, already at rock bottom. I considered deprecating the project and never working on it again, but I couldn't bring myself to do it.

All that to say...I've considered, and even attempted, to make a livable income out of AzuraCast while maintaining it as the free and open-source project it is now, and I've been burned so badly I don't know that I can bear to do it again. Any more of that would break me.

**Comment by SlvrEagle23** [comment]
@susl16c To directly answer your question, there is a Contributors page for every repository, which you can use to view overall statistics about how many people are involved in a project. Here's this project's contributors page: https://github.com/AzuraCast/AzuraCast/graphs/contributors

**Comment by SlvrEagle23** [comment]
@kbysfm Thank you :)

**Comment by nsystem1** [comment]
@SlvrEagle23 Thank you for creating this amazing project and for inspiring all of us. I am sorry that you are being attacked for doing such a beautiful job. I want you to know that there are more of us who greatly appreciate the work you have done here.

THANK YOU

**Comment by nsystem1** [comment]
@SlvrEagle23 secondly i want to help as a developer. Please let me know how i can help or join your team

**Comment by ckeurk** [comment]
Hi,
I have already made a donation and I will continue to do so, because your work is really good. I really hope that you will find a way to make your life much more enjoyable for the coming year. Thanks again

**Comment by jonikane** [comment]
436/5000
Hello .. Good evening,

@ SlvrEagle23, thanks for the fantastic work with this great project.

This is a project that takes a lot of work and has costs to develop and people should contribute instead of judging and making requests and more requests and pressuring.

I have already made a donation to help him develop and I will continue to do so.
Nothing negative has to say. And whatever I can help, I'll be available.

Thank you

**Comment by Gartral** [comment]
@SlvrEagle23 I thank you, from the bottom of my heart for what  you're doing, as a disabled person myself I understand the woes of trying too eek out a living doing what you love and trying to help others.. with that said I will be dropping you a personal invite to talk, one to another and show you what i've been doing with your product. You've done a downright fantastic job with azuracast and I've enjoyed seeing it evolve in the past few months! I look forward to hearing more about you and showing you what i've been doing with this wonderful platform!

**Comment by voipworld** [comment]
First of all, at you can see we both have some kind of disability
you know i'm blind, but your disability is also mine and i can feel the env that you live on when you get lot of issues on your project without any return from people
donation is not so easy here due to market restriction, credit card owning, qurensy convertion and lot of issues
but, when i get a chanse i dont mind donating to a developer like you who helped me get my community radio up and runing in no time, ignoring other inaccessible projects like airtime
except of the installation, i was unable to use any alternative project till i surprisingly found AzuraCast in github
i greatly thank you for your best effort you're having in this open source projects
Tayeb.

**Comment by griffon56** [comment]
You do an amazing job ! Azurcast is the best free webradio automation streamer I found so far.
I would really like to contibute but until now I don't really understand how it works. I know liquidsoap, icecast and a bit of docker but I  don't understand how you control these pieces of software (with composer ?). If you have a bit of documentation about this, please point it to me.

**Comment by HiseEiichi** [comment]
@SlvrEagle23 I'm Brazilian and I'm a big fan of yours. This suite you built is excellent. Here in Brazil, tools and suites of the type end up having a high cost, and to get them you need to have a good income and many people who dream of having a web radio do not have a good income for this.

Thank you on behalf of the majority that I know and that uses your tool here in the country.

And good luck, I hope you can improve your situation.

**Comment by jonikane** [comment]
Hello,

Like I said before. I have already donated and will do more.
And everyone who uses this platform should do the same. Even a small donation.

If you need my help, I'll give you something. For example Portuguese translation from Portugal.

Thank you

**Comment by amavarick** [comment]
@jonikane If I could suggest, taking the initiative by looking at previous commits to create your own pull request translating into Portuguese.  @SlvrEagle23  can then take that pull request and approve, modify or deny the request but the bulk of your translation work would save him time.  Here is an example of the files that may need to be updated to add a translation.

https://github.com/AzuraCast/AzuraCast/commit/dcba6c2bd7e9977eade37bf022515f87232b53a4

**Comment by Donokami** [comment]
When i found your project, i thought,"Wow, this is the first time in a long time that I've enjoyed a FOSS project so much."
For 2 years now, you have been doing an incredible job on this project, and you are always very attentive to the requests we make, with a lot of kindness and patience.
I'm 16 years old, I'm still in high school, and this project fascinated me and reinforced me in the idea that people are doing little things every day that we don't pay attention to and that are positively affecting our way of life.
I sincerely hope that you will always manage to escape from your problems,
I can't thank you enough.
Thank you very much.
<3

**Comment by SlvrEagle23** [comment]
@Donokami That's really beautiful to hear. :') Thank you very much for sharing that.

I hope, as a young person, that what you take from projects like this one is that there are a lot of passionate, devoted people out there working to create things just for the sake of the greater good. The FOSS community isn't always perfect, but it is a kind of humble, selfless service that should be celebrated by everyone. 

I may fight my own struggles, but don't let that discourage you from pursuing a career in software development if you're so inclined; it's a wonderfully rewarding profession where it's possible to do a lot of good for a lot of people.

Your contributions here on the AzuraCast repository have always been of the type that I like: friendly, encouraging, well-documented and well-communicated. I'm honored to be a part of making something you consider to be meaningful and useful in your life. Thank you :)

**Comment by multi023** [comment]
@SlvrEagle23 

Thank you very much for all your time and the great development.
We have to contribute a little between all so that the good things, continue better :)

Happy New Year!

**Comment by mkbradio** [comment]
I pay £10 50 a month to use this product to run my radio station, so I am more than a bit confused by this post? I have this as part of my package with Shout cast I have had very bad issues with it the last few weeks and sent several screenshots and emails. As I write this the last program that was on my station is still showing up in the player. and this is happening all the time, the next program still plays but the one before it shows it's like its stuck. I was initially very happy with Azuracast but that has changed over the last few weeks I am constantly stressed out because I never know what is going to happen or not happen next, yet I see all these new features appearing?. I think the fundamental thing here is this panel reliable? why is more developments happening and the issues not being resolved that have to be to run a radio station being addressed and resolved? and why am I paying a monthly subscription for something that is not working right, and losing me listeners?  I am also disabled and find running my station very cathartic but I cannot relax anymore and am not getting the support I have been asking for weeks. I also recommended Azuracast to other stations who are now also struggling with it .

**Comment by SlvrEagle23** [comment]
@mkbradio AzuraCast is given away for free, period. If you are paying someone to host an AzuraCast instance, that's a third-party reseller, and you're likely paying them for the hosting resources and support of managing the installation, not for AzuraCast itself. NONE of that money that they collect is sent to me, unless they decide to donate to the project out of the goodness of their own hearts, so none of that money addresses the problems I mentioned in this post, and none of it motivates us to more actively develop the software.

Nonetheless, we continue to roll out not only new features but a LOT of bug fixes. You'll notice our last few releases have been heavily oriented toward stabilizing and improving the software. Many of the new features introduced have actually been secondary to bug fixes, and have been meant to make diagnostics and troubleshooting even easier. Without a doubt, there's a ton of work going both into our own project and our upstream dependencies to improve how they operate on a day-to-day basis.

I want to correct your perception of how open-source software is. This isn't some sort of "I'm paying you, so fix it already" arrangement. This code is fully open specifically to allow multiple contributors. If you see that it's broken, you can investigate why that is, fix it in your own branch, then pull request it into our main repository. That way you become a part of the solution yourself.

It is also myopic and inaccurate to say "this team isn't fixing _my_ bugs, so they clearly aren't fixing _any_ bugs." If we knew more about your bugs and had a clear path toward a solution for them, then they would be on our list to fix alongside all the others.

Please do not become yet another one of our users who has this strongly adversarial, entitled stance about our software. We deal with a whole lot of that already, and it's really kind of awful.

**Comment by soatok** [comment]
@mkbradio 

>  I am also disabled and find running my station very cathartic but I cannot relax anymore and am not getting the support I have been asking for weeks.

I'd love to help you gain some catharsis in your life again. Can you file a new Github issue with the technical details? I'll see if I can reproduce it (unless @SlvrEagle23 beats me to it).

> I pay £10 50 a month to use this product to run my radio station, so I am more than a bit confused by this post?

I'm confused why the company you're paying to host your radio station isn't, in turn, supporting AzuraCast's development. That seems like a bad business move on their part. (Please mention that in your complaint to the hosting provider you're paying £10 50 a month to.)

**Comment by CodeSteele** [comment]
> and why am I paying a monthly subscription for something that is not working right, and losing me listeners?

@mkbradio Like with other software out there, for systems that you depend on for reliability we don't recommend updating to every new feature release, and to test new releases before deploying them. Is the company you're paying for forcing updates on you without you doing those yourself?

Given the following circumstances I got some solutions:

*You're applying updates that introduce new issues*

Generally we recommend that systems that require stability do not upgrade unless necessary, upgrades should be tested, and when you upgrade to have a roll-back plan in place. Part of a managed platform should include some level of backups/restoration available (talk to your vendor about that). Get them to roll-back to the last known good state and keep you on that version at least for the time being.

*Your vendor is applying updates for you*

I'll see about drafting up a "Stable AzuraCast Build Best Guidelines" document that you can give to your vendor (we'll have it in our docs) that suggests better practices instead of just forcing the latest updates on all of their consumers.

Ultimately -- if you're paying a vendor for hosting though and they're blindly upgrading you to the latest bleeding-edge and breaking your system, that's something _they_ need to fix and to stop doing to you (sadly though that's between you and them, we have zero leverage with vendors and our software is generally geared through self-hosting).

---

As @SlvrEagle23 pointed out though, we're volunteers on this project and mostly have day jobs (since this pays nothing), so while we make some headway over here, it's not quite the same as what you can expect from someone that is selling a product.

**Comment by mkbradio** [comment]
> @mkbradio
> 
> > I am also disabled and find running my station very cathartic but I cannot relax anymore and am not getting the support I have been asking for weeks.
> 
> I'd love to help you gain some catharsis in your life again. Can you file a new Github issue with the technical details? I'll see if I can reproduce it (unless @SlvrEagle23 beats me to it).
> 
> > I pay £10 50 a month to use this product to run my radio station, so I am more than a bit confused by this post?
> 
> I'm confused why the company you're paying to host your radio station isn't, in turn, supporting AzuraCast's development. That seems like a bad business move on their part. (Please mention that in your complaint to the hosting provider you're paying £10 50 a month to.)

Hi there, Thank you for responding to my post. I now have some clarity on what's what and what way this works I did genuinely think I was paying Azuracast but obviously it is my vendor at shout cast solutions and it is him that is adding the upgrades. I have no idea of the technical side of things but I assumed that Azuracast were making the upgrades to my panel. I also don't know if they contribute to Azuracast but that is something I will ask. I am so stressed out the panel was working fine with an odd thing going wrong but these last couple of weeks has been a total nightmare. Shows sticking in the player and still showing up even when the next show is playing. Scheduled shows not coming on, it really has and still is a nightmare I have 16 presenters to look after, and I am getting so many complaints in spite of me doing everything in the panel that I have always done when you say. "Can you file a new GitHub issue with the technical details? I'll see if I can reproduce it " What would I need to send you? I did send several screenshots and reports to my vendor who said he was sending them on to Azuracast. I just want it all to work as it did before. Don't get me wrong many of the changes were great , like being able to add more scheduled days and times with ease , adding presenters pictures in the metadata which I continue to do sadly they don't show up in the player. Thank you for your offer to help me and I hope I can find a way to provide you with the info you need.

**Comment by mkbradio** [comment]
> @mkbradio AzuraCast is given away for free, period. If you are paying someone to host an AzuraCast instance, that's a third-party reseller, and you're likely paying them for the hosting resources and support of managing the installation, not for AzuraCast itself. NONE of that money that they collect is sent to me, unless they decide to donate to the project out of the goodness of their own hearts, so none of that money addresses the problems I mentioned in this post, and none of it motivates us to more actively develop the software.
> 
> Nonetheless, we continue to roll out not only new features but a LOT of bug fixes. You'll notice our last few releases have been heavily oriented toward stabilizing and improving the software. Many of the new features introduced have actually been secondary to bug fixes, and have been meant to make diagnostics and troubleshooting even easier. Without a doubt, there's a ton of work going both into our own project and our upstream dependencies to improve how they operate on a day-to-day basis.
> 
> I want to correct your perception of how open-source software is. This isn't some sort of "I'm paying you, so fix it already" arrangement. This code is fully open specifically to allow multiple contributors. If you see that it's broken, you can investigate why that is, fix it in your own branch, then pull request it into our main repository. That way you become a part of the solution yourself.
> 
> It is also myopic and inaccurate to say "this team isn't fixing _my_ bugs, so they clearly aren't fixing _any_ bugs." If we knew more about your bugs and had a clear path toward a solution for them, then they would be on our list to fix alongside all the others.
> 
> Please do not become yet another one of our users who has this strongly adversarial, entitled stance about our software. We deal with a whole lot of that already, and it's really kind of awful.

Hello and thank you for your response which has brought me some understanding of the situation at Azuracast.  My vendor told me he was passing all of my reports about my issues onto Azuracast but nothing has changed, so I think there has been a misunderstanding and I apologize If my post upset you or anyone I needed answers as all of this has indeed affected my listenership. You created Azuracast. I created my own radio station using the software but via Shout cast solutions which I pay £10.50 per month for after weeks of telling my vendor and sending reports every day and screenshots he told me these had been passed on to you. So excuse my ignorance I don't have the knowledge to fix it at my branch. Now that I have established who is who and what is what it does change my perception but I hope also you understand the dilemma I have been in and mistakenly believing that my reports of issues were not being addressed. Some days I log on and all these new features are there with no notification. Now from other replies, I have received here it appears my vendor has been doing all this. I didn't know it could be rolled back and that's what I will be asking him to do.

**Comment by SlvrEagle23** [comment]
@mkbradio I'm glad to hear we could shed some light on the arrangement between our resellers and AzuraCast itself. It's been a source of frustration for us and many other open-source projects, since our resellers contribute overall to the number of users who file complaints and issues, but they don't also have to contribute to help fund us or help us code the actual project.

I want to help get your station up and running like normal again, though part of this will be determining what's being changed at the reseller level and what's actually being caused by our software itself.

Normally you are entirely correct, that if you are paying for AzuraCast from a host you should reach out to them for support and they can work with us directly. In this case, since I don't know specifically which GitHub issue (if any) corresponds to the reseller relaying those problems to us, you may be better off creating your own GitHub issue so that we can troubleshoot and diagnose things directly.

I understand your frustration with this situation, and we will do the best we can to help.

**Comment by rolradio** [comment]
Hi,

I will try to put Mary's problem here on my side.
The problem is that many pre-recorded programs are played on certain hours
and certain days, with the advanced option interrupt the previous current
playlist.
That usually goes well, but sometimes it does not.
But very often, and that is perhaps the biggest problem, the name of that
program as mp3 is not displayed in azuracast, while it does play the
program.
This usually remains the name of the last MP3 played.

A second problem is that Mary has many playlists, with external source url
as playlist.
Dropouts often occur here, even though the buffer time is set at 120
seconds.

I understand that this is annoying, as a small host we are powerless.
I have been using azuracst for several years now, and I see it more and
more as a great panel, which leaves other stream panels far behind.

Unfortunately, the extensive scheduled playlists cannot be used optimally
now.

I would like to continue working to solve the problem, by describing things
well. So that it can be further investigated.

Lucas

Op di 12 mei 2020 om 21:03 schreef SlvrEagle23 <notifications@github.com>:

**Comment by SlvrEagle23** [comment]
@rolradio Wait, so _you're_ the reseller and the issue you reported earlier is the one causing this problem?

Okay, let's move over to that other issue then for further discussion, since this is all resurrecting a very old thread that doesn't relate to this problem at all.

See issue #2713.
