### ISSUE TITLE
WANTED:  Christian programmer to install Azuracast | Support

### ISSUE THREAD

**Issue by tpwradio** [AzuraCast/AzuraCast#3181]
Good evening,

I represent non-profit Christian Radio Stations.  We are in search of a person who can help up re-install Azuracast.  It was recently installed and being used successfully but due to a change in personnel, it was "deleted" from the computer prior to their departure.  Unfortunately, no one was trained on how to setup and maintain the system.  This system is vital for importing in audio feeds from different sources and sending them out to our tower sites.

If you are interested, qualified and knowledgeable of Azuracast, please send your contact information and cost per hour to tpwradio@outlook.com. 

Thank you.

**Comment by SlvrEagle23** [comment]
@tpwradio I want to point out two important points:

 - Our GitHub issues section is typically not used for users looking to hire an installer for AzuraCast, and should be focused instead on errors and bug reports with the software itself, and

 - While there is nothing wrong with the majority of your post, the subject heading stating that you are seeking specifically a Christian programmer violates our [Code of Conduct](https://www.azuracast.com/code-of-conduct.html) which prohibits discriminating based on religion, among other factors.
