### ISSUE TITLE
Jingle Mode not applying

### ISSUE THREAD

**Issue by pascalla** [AzuraCast/AzuraCast#3182]
**Using Docker installation method**
Yes

**AzuraCast version**
#f88a1e4 (2020-09-11 0:22) 

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
Playlists that are in "Jingle Mode" still showing up on NowPlaying/Song History. I've tried recreated a new playlist but issue still persistent.

**To Reproduce**
1. Create a playlist with "Jingle Mode" enabled
2. Assign songs
3. Wait for play

**Expected behavior**
Do not show up

**Relevant Logs**
`2020/09/17 05:44:56 [lang:3] AzuraCast Raw Response: annotate:title="ID1",artist="31-YourDestination",media_id="7197",jingle_mode="true",duration="11.00",song_id="b7659ce56747c8ffe275630231889a7c",liq_amplify="0.00dB",liq_cue_out="8.10":/var/azuracast/stations/**/media/AutoDJ/Imaging/31-YourDestination-ID1.wav
2020/09/17 05:44:56 [decoder:3] Method "WAV" accepted "/var/azuracast/stations/**/media/AutoDJ/Imaging/31-YourDestination-ID1.wav".`

**Screenshots**
![image](https://user-images.githubusercontent.com/22846433/93506982-f303dc00-f914-11ea-91d6-0f172e69e465.png)
![image](https://user-images.githubusercontent.com/22846433/93507415-8c32f280-f915-11ea-92ee-88de59233007.png)

**Comment by SlvrEagle23** [comment]
@pascalla Fixed as of latest commit. Thanks for the report!
