### ISSUE TITLE
DJ/Streamer Account Can't connect to the Stream after I update my AzuraCast

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#3184]
**Using Docker installation method**

YES
**AzuraCast version**

 v0.10.3, #e60c2bc (2020-09-09 4:06) Rolling •

**Host Operating System**

Description:    Ubuntu 18.04.4 LTS

**Describe the bug**

After my recent update of my docker installed AzuraCast the DJ/Streamer account can't connect to the stream anymore using the shoutcast client format " dj_username:dj_password " . Any one knows about the problem? 

**To Reproduce**

**Expected behavior**

**Relevant Logs**

2020/09/19 22:19:35 [ffmpeg:3] [mp3float @ 0x7f97d80a7140] Could not update timestamps for skipped samples.
2020/09/19 22:19:35 [cross_7822:3] Analysis: -18.879838dB / -26.293613dB (2.97s / 2.99s)
2020/09/19 22:19:35 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/09/19 22:19:35 [lang:3] AzuraCast Feedback Response: OK
2020/09/19 22:20:25 [lang:3] Authenticating DJ: reans
2020/09/19 22:20:26 [lang:3] AzuraCast DJ Auth Response: true
2020/09/19 22:20:55 [lang:3] Authenticating DJ: reans
2020/09/19 22:20:56 [lang:3] AzuraCast DJ Auth Response: true

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@reans The log saying "DJ Auth response: true" suggests that it's actually working as intended and should be letting DJs connect normally. This may be an issue with your DJ software, or it may be caused by our recent upgrade to 1.4.3.

**Comment by reans** [comment]
before i update my AzuraCast it was working fine and i have another AzuraCast runing in ubuntu 20.0 and i update also same issue i cant login using the username:password format even the logs shows ok.

**Comment by reans** [comment]
upto this update (Rolling Release #d5a7817 (2020-09-14 4:11) • Docker • PHP 7.4) is working fine. but after i grab the update below no DJ can connect anymore.

================================
New AzuraCast Updates Available

The following improvements have been made since your last update:

    Fix jingle mode order of operations.
    Update to use official release version of Influxdb-PHP
    Update application dependencies.
    Implement improved var dumping on dev instances.
    Update Nowplaying library to apply fixes.
    Extend Doctrine redeliver timeout.

**Comment by pascalla** [comment]
I am also seeing this issue with the latest update, can't connect via shoutcast, only icecast.

**Comment by reans** [comment]
did you find a workaround @pascalla while waiting for the update? thanks

**Comment by SlvrEagle23** [comment]
@reans @pascalla I reverted the recent update to the production version of Liquidsoap 1.4.3 to see if that resolves the issue. Update your installations and let me know if it helps resolve the issue.

**Comment by reans** [comment]
@SlvrEagle23 thank you so much the latest update worked like a charmed. 
More power to AzuraCast

**Comment by fast97** [comment]
Hello, for me I always have the problem with the webdj page which connects for a few seconds without sound and then cuts off. I do not understand this problem that occurs with all browsers. My azura version is: Rolling Release # f3626dc (2020-09-21 16:28) • Docker • PHP 7.4
Thanks.
