### ISSUE TITLE
Twitter webhook now publishes station idents

### ISSUE THREAD

**Issue by graemetadata** [AzuraCast/AzuraCast#3186]
Hi - my AzuraCast host carried out an "emergency" software upgrade earlier this week.

Now my station's twitter feed has started including station idents, if one happens to be playing at the time a tweet is created.

The "Hide metadata" tick box prevented this happeing before, but although it remains selected, the twitter feed now contains runs of up to four idents in a row.

Is this a known bug, and can it be resolved?

Thanks

**Comment by sidney65** [comment]
hi @graemetadata ,
the bug has been fixed in the new version; just updated azuracast.
Have a good day.

**Comment by graemetadata** [comment]
Many thanks, much appreciated.
I'll pass this to the service provider for action.
