### ISSUE TITLE
Media Manager and free space

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#319]
I mounted a separate disk to the folder var/lib/docker and when I look how much it takes place
![dfbngfbn](https://user-images.githubusercontent.com/23697714/33718063-386fe6a8-db6d-11e7-9add-57ef5fe73ba4.png)
And in Media Manager very different is displayed
![453543](https://user-images.githubusercontent.com/23697714/33718091-4f542d3e-db6d-11e7-9f7a-819d32ca8525.png)
How to fix it to the right value?

**Comment by SlvrEagle23** [comment]
Closing as PHP's built in disk space usage functionality is about as accurate as we can get from within the interpreted PHP environment without having more detailed knowledge of the host environment.
