### ISSUE TITLE
Identified a problem with the playlist the scheduled time

### ISSUE THREAD

**Issue by Kaiserhm** [AzuraCast/AzuraCast#3194]
Hello we have identified a problem with the playlist

if we select once per hour and expand under
put a tick on other songs to play at the scheduled time

then the track only runs for 54 seconds and then accesses the other playlist again

but this function is very important to us

is this error known?

https://www.youtube.com/watch?v=mhva99LGqek

**Comment by btoplak** [comment]
I am experiencing the same issue.
I opened a bug report #3254
