### ISSUE TITLE
Hide volume slider for iOS devices / Audio element volume property not writeable on iOS

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#3195]
**Using Docker installation method**
Yes

**AzuraCast version**
All versions

**Host Operating System**
Debian 9

**Describe the bug**
iOS does not support write access to an audio elements `volume` property, just read access. This means that the volume slider on the public page (and other parts where an audio player is available) is not of any use to iOS users and potentially confusing since it has no actual impact for those users.

**Expected behavior**
The volume slider should be hidden for iOS devices.

**Device(s):**
 - Device: iPhone / iPad Pro
 - OS: iOS 12.4.8 / 14.0
 - Browser: Safari

**Additional context**
See https://caniuse.com/audio under `Known Issues`:

> Volume is read-only on iOS.

**Comment by BusterNeece** [comment]
@Vaalyn Somewhere I saw suggested that volume control is no longer read-only as of iOS 13?

**Comment by Vaalyn** [comment]
Nope, when I reported this I was already testing this with an iOS 14 device.

caniuse.com also shows it as still being read-only on iOS 18.2:

<img width="1468" alt="image" src="https://github.com/user-attachments/assets/2f02a5fe-01f7-4dcb-bda2-64eb8a3edfc1">

**Comment by BusterNeece** [comment]
Ah, okay. Bummer but yeah still a thing. I've seen one JS trick used is to create a new empty audio element, set its volume to anything other than 1, and then immediately check if its volume actually changed, and that's a pretty foolproof way of identifying any environments with read-only audio volume. We could implement something like that fairly easily.
