### ISSUE TITLE
AzuraCast Hacktoberfest Participation Ideas

### ISSUE THREAD

**Issue by BusterNeece** [AzuraCast/AzuraCast#3196]
This year, the team at AzuraCast wants to participate in [Hacktoberfest](https://hacktoberfest.digitalocean.com/) which is put on by our friends at DigitalOcean and is a community-wide celebration of open-source code, collaboration and contribution.

We're seeking feedback from the community on things we could possibly work on during the month. Good candidates for suggestions would be ideas that:
 - Are reasonable for us to fully implement within the month of October (factoring in delays in productivity due to any personal issues or pandemic stress),
 - Are specific in scope and aren't overly broad (i.e. "Redo the whole AutoDJ") or vague (i.e. "make things prettier"), and
 - Are items that other developers could rather easily contribute into the application.

Some of the ideas our team has been discussing so far include:

 - Adding a webhook that will publish listener counts and updates to Google Analytics (or other third-party analytics tool)
 - Include recorded broadcasts in on-demand downloads
 - Create a simple, initial customizable embeddable radio player widget
 - Add support for SMTP mail delivery and an in-system "forgot password" functionality
 - Support a custom favicon in custom branding
 - Allow some reports to be isolated to specific countries or mount points
 - Add basic system resource (i.e. CPU load, RAM use, disk space use) monitoring to the application via our existing InfluxDB database
 - Make "genre" a first-class metadata entry that is displayable/sortable in the media editor
 - Add "Remember me" checkbox to login page

Submit your ideas in this thread and we'll evaluate them for inclusion!

**Comment by tbcool31** [comment]
Add an option to add all songs to a playlist in 1 click instead of going to pages and all and selecting them all

**Comment by DamonOnYT** [comment]
Would love to be able to lock the whole API down to only keys / being authenticated.

**Comment by MegaJoshy** [comment]
> Add an option to add all songs to a playlist in 1 click instead of going to pages and all and selecting them all

If you add all your songs to a folder you can add the playlist to folder instead and will set the playlist for everything in the folder. Do correct me if I'm wrong.

**Comment by SC2Mitch** [comment]
I'd love to see viewer statistics from **all** stations in one simple page in the Admin Panel.

**Comment by AaronUnmuted** [comment]
Minor issue - it would be great to make a simple change to move the "Advanced Maximum Listeners" field from the Broadcasting tab to the Administration tab - therefore making this changable only by administrators and not the user themselves. 

It would also be great to see a bandwidth limit field - though again, a fairly minor issue. 

Keep up the great work.

**Comment by DamonOnYT** [comment]
Permission system for API Keys, so things such as permissions to do stuff on stations, being able to read streamers, delete/edit streamers, restart backend/frontend etc.

**Comment by YosefAdPro** [comment]
Improve the embeddable radio player.

**Comment by Vaalyn** [comment]
Improve styling of the `Song History` modal on the public page.

At the moment the modal just shows the history as a simple ordered list with the title and artist.
I think this could be improved by adding the album cover of the song, the time when the song started playing and maybe if it was a request or not.

Maybe this bootstrap component could be used for this instead of the ordered list: https://getbootstrap.com/docs/4.5/components/media-object/

**Comment by stardevelop** [comment]
Remote Download!
Downloading a song file from a remote URL to a specific folder.

**Comment by dvdred** [comment]
First of all, thank you developers of the project for joining this initiative. it would be nice to have:

- An image to associate with the dj streamer to display it in the player when it is live (I managed to do it through an ugly and hackish integration with the api, changing the image on the fs....)
- A better view of the ondemand page, especially from mobile
- Show the link of the ondemand page in the player
- Enter useful metadata on automatic live recordings (artist = dj name, title = timestamp)

**Comment by Vaalyn** [comment]
Apply the dark theme to these action modals too.

Having them be completely white when using the dark theme is a bit inconsistent.

![image](https://user-images.githubusercontent.com/13745863/94380080-4e637480-0134-11eb-9582-02e7481ca56c.png)

**Comment by dvdokkum** [comment]
+1 to making recorded broadcasts downloadable. even just having a publicly accessible url for those recordings would be helpful. even better if the url is predictable: i.e. `/[dj_name]/recordings/[start_time]

**Comment by tbcool31** [comment]
Add an option to make custom user fields and have them appear on api

**Comment by esmondgh** [comment]
Replace **Local Streams URLs** and  **Administration URL** with a button.
This will allow Listeners counts for each stream URL to appear without the bottom scroll bar

![urls](https://user-images.githubusercontent.com/42568091/94912810-bea52980-0497-11eb-9dd5-8ad84a46e343.png)

**Comment by sidney65** [comment]
Hi all,
for next update , it's a good idea to do a webhook for send metadata to radio.net directory .
You have all info in this is issues [#3091](https://github.com/AzuraCast/AzuraCast/issues/3091)
Thank to the team for all your work.
Have a good day.

**Comment by Xara** [comment]
As I told somewhere, already, I have a common pool for all stations and users (save space), would been nice to disable in admin panel possibility to delete songs for non admins but also to remove double tracks globally, from admin panel, been able to see in how many playlists songs are affected for ALL stations and ALL playlists then decide what to kick from server ...

**Comment by gammaw** [comment]
I'm new to Hacktoberfest but I'm interested. How exactly would Azurcast's participation look like?

**Comment by Vaalyn** [comment]
> I'm new to Hacktoberfest but I'm interested. How exactly would Azurcast's participation look like?

We have a list of features/improvements that are relatively small in scope so that they can be done in a reasonable amount of time. You can find this list by filtering the GitHub issues by the `Hacktoberfest` label, here is a link with pre-selected filtering: https://github.com/AzuraCast/AzuraCast/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest

When you see something that you want to work on just add a comment to that issue that you will start working on that so that other people who are also interested in that might offer you to help you with it.

After setting up the local development environment you create a new git branch on your machine where you will commit your changes.

When you've finished working on the feature on your local development environment you push the branch to your GitHub account and send us a Pull-Request where you mention the issue number so that we can easily see that it belongs to a Hacktoberfest issue.

Then we will review it and if it looks fine to us it will be merged.

General information about Hacktobfest stuff can be found on the page that was linked in the thread at the start.

**Comment by gammaw** [comment]
> **dvdred commented 16 days ago**
> An image to associate with the dj streamer to display it in the player when it is live (I managed to do it through an ugly and hackish integration with the api, changing the image on the fs....)

+1

**Comment by zivanovicMilan** [comment]
Please, consider improving 7-days and monthly reports. It doesn't work now.

**Comment by Vaalyn** [comment]
> Please, consider improving 7-days and monthly reports. It doesn't work now.

@zivanovicMilan As far as I can see it with my own station those reports are working fine for me. If you are experiencing an issue with a feature please create a bug report for it and include a description about what exactly is not working and also provide all the additional information that we ask for in the bug report issue template.

**Comment by zivanovicMilan** [comment]
> > Please, consider improving 7-days and monthly reports. It doesn't work now.
> 
> @zivanovicMilan As far as I can see it with my own station those reports are working fine for me. If you are experiencing an issue with a feature please create a bug report for it and include a description about what exactly is not working and also provide all the additional information that we ask for in the bug report issue template.

Thanks!

**Comment by silfversound** [comment]
1. Schedule a specific file on a specific time and date without creating a playlist.

2. Month view in schedule.
