### ISSUE TITLE
No listener statistics 

### ISSUE THREAD

**Issue by AaronUnmuted** [AzuraCast/AzuraCast#3197]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #f62a04c

**Host Operating System**
 Ubuntu 

**Describe the bug**
Stream servers are receiving no statistics via AzuraCast. The live listener page does not update and remains at 0 even when there are listeners tuned into the stream. 

**Screenshots**

Live Listeners - http://prntscr.com/umngul
Stream playing - http://prntscr.com/umnh0v

**Additional context**

This problem started as we updated our AzuraCast installation on Sunday. 
Web sockets are NOT being used. 

Any help would be hugely appreciated.

**Comment by SlvrEagle23** [comment]
@AaronUnmuted Can you confirm if this still happens in the latest version?

**Comment by AaronUnmuted** [comment]
@SlvrEagle23 this issue disappeared recently, though we are now back on Rolling Release #06808d0 (2020-10-19 11:00) and the issue has reappeared. Have tried with web-sockets enabled and disabled.
