### ISSUE TITLE
Google reCAPTCHA on login page

### ISSUE THREAD

**Issue by ruLait** [AzuraCast/AzuraCast#320]
This enhancement can increase security. I think Invisible reCAPTCHA is the best choice, but it's up to you.
https://developers.google.com/recaptcha/intro

**Comment by SlvrEagle23** [comment]
@ruLait I agree that improving the security of the login page is important, but one of the problems with services like reCAPTCHA is that they require an API key for each instance that uses them. That means it would have to be an optional feature that was only enabled once you supplied a custom API key for your instance of AzuraCast.

If at all possible, I like to use more "self-contained" methods that don't depend on third-party services. For example, the password hashing mechanism used by AzuraCast is a "slow hash" that deliberately takes about 100ms to compute a hash, which isn't slow enough to bother users but is slow enough to limit the rate of brute-forcing attacks significantly. If I do end up adding anything to the login page, it'll likely be a local rate limit enforced through the Redis cache, that will offer significant added safety without a huge performance drag.

**Comment by SlvrEagle23** [comment]
Closing this issue as rate limiting was just implemented on the login page, and this should resolve a large set of brute-forcing issues without relying on a third party dependency.
