### ISSUE TITLE
Album artworks are not deleted when media file is removed

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#3203]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.3, #22851cc (2020-09-27 03:24)

**Host Operating System**
Debian 9

**Describe the bug**
While looking at the code for the `delete` batch action for the media files I noticed that the album artwork for a media file is not removed from the filesystem when that action runs. I've checked if that might be done via one of the sync tasks but couldn't find anything that looks like it touches those artworks.

I've used the steps described below to test if the media artwork is removed at any point and it is indeed not cleaned up.
This means that those artwork files will keep using up space while never being deleted.

**To Reproduce**
(I've tested this on my local dev installation with a completely cleared media library so that it is easier to see if a file is removed)

1. Enter the `web` container and `cd` into `/var/azuracast/stations/<station_name>/album_art`
2. Run `ls -la` to see all album artwork files
3. Upload a media file with an album artwork
4. Run `ls -la` to see the new album artwork in the filesystem
5. Delete the media file via the `Delete` button on the `Music Files` page
6. Run `ls -la` to see the new album artwork still being in the filesystem
7. Run all sync tasks via the `/admin` page
8. Run `ls -la` to see the new album artwork still being in the filesystem

**Expected behavior**
When a media file is removed from the filesystem the artwork file should also be removed.

**Additional context**
There is a method on the `StationMediaRepository` called `removeAlbumArt()` that can remove the album artwork for a media file but this method is only called from the `DeleteArtAction` which is for the DELETE call to the `/api/station/{station_id}//art/{media_id:[a-zA-Z0-9]+}` API endpoint.

**Proposal for a solution**
Add `$mediaRepo->removeAlbumArt($media);` before removing the media from the database here: https://github.com/AzuraCast/AzuraCast/blob/master/src/Controller/Api/Stations/Files/BatchAction.php#L75-L77

This also needs to be added to the Sync task like this `$this->mediaRepo->removeAlbumArt($media_row);` before this line here: https://github.com/AzuraCast/AzuraCast/blob/master/src/Sync/Task/Media.php#L168

**Comment by SlvrEagle23** [comment]
@Vaalyn We definitely need a new sync task to clean up the filesystem of album art (and waveforms) for media that isn't present any more. Could be a simple cross-check between the media unique identifiers in a given station and the filesystem's contents.

**Comment by SlvrEagle23** [comment]
@Vaalyn Added in "related media" deletion on both the music manager's delete call and the batch sync delete call, as well as a "cleanup" hourly task that cross-checks the IDs in the related directories and cleans up any missing files.
