### ISSUE TITLE
Implement Google Analytics Support via Web Hook

### ISSUE THREAD

**Issue by SlvrEagle23** [AzuraCast/AzuraCast#3206]
Our Web Hook system is capable of connecting to a wide number of sources, but one of the most common requests we get is to connect to Google Analytics and send listener counts for a given station to that software, so it can be tracked alongside other web site analytical data.

Important places to look in the code when implementing a new web hook:
 - `/src/Webhook/Connector`: The directory where new webhooks should be located
 - `/config/webhooks.php`: Where webhooks are configured and injected into the web hook dispatcher
 - `/config/forms/webhook/`: Where existing custom web hook forms are located

**Comment by Vaalyn** [comment]
Closing as resolved
