### ISSUE TITLE
Add Support for SMTP Mail Delivery for "Forgot Password" Functionality

### ISSUE THREAD

**Issue by SlvrEagle23** [AzuraCast/AzuraCast#3209]
Currently, AzuraCast does not have any e-mail delivery support built into it at all.

One of the biggest areas this impacts is our ability to implement a "Forgot Password" functionality.

This issue isn't necessarily to implement that entire functionality itself, but rather to get us to a state where we can much more easily implement it in a secure way ourselves.

This includes:
 - Adding support for a popular PHP mailer library (i.e. Swiftmailer) in our `composer.json` dependencies
 - Adding the corresponding settings into `src/Entity/Settings.php` and into the settings form in `config/forms/settings.php`

**Comment by Vaalyn** [comment]
Closing as resolved
