### ISSUE TITLE
Error on Media-Upload

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#321]
Hello!

Media-files don't upload well.
![image](https://user-images.githubusercontent.com/29834979/33733481-35c7ecd0-db8a-11e7-8ff0-ebed33e9d730.png)
![image](https://user-images.githubusercontent.com/29834979/33733489-3e45b766-db8a-11e7-9860-2ad772f0bc04.png)
![image](https://user-images.githubusercontent.com/29834979/33733500-461c5012-db8a-11e7-9ca0-e460cb598adc.png)
![image](https://user-images.githubusercontent.com/29834979/33733506-499fafae-db8a-11e7-8e82-44fab3d76114.png)
![image](https://user-images.githubusercontent.com/29834979/33733569-70d4d130-db8a-11e7-9320-06f322f3dc12.png)

**Comment by SlvrEagle23** [comment]
@RemBdev I'm closing this issue for now, as it has been quite some time and I haven't heard any other reports or details that would explain why the file uploader is having issues in general. If you're still having this issue, please feel free to reopen this ticket.
