### ISSUE TITLE
Implement "Remember Me" Login Functionality

### ISSUE THREAD

**Issue by SlvrEagle23** [AzuraCast/AzuraCast#3215]
In implementing this functionality, we don't want to reinvent any wheels, we want to use current secure best practices for implementing this functionality, which is effectively setting a cookie on the user's computer that will allow their session to persist longer than a single in-browser session.

There is an existing library we can take advantage of here, and I strongly recommend this implementation does so:
https://github.com/paragonie-scott/rememberme

**Comment by iqbalnur32** [comment]
hello @SlvrEagle23  maybe this https://stackoverflow.com/questions/34651823/how-implement-remember-me-in-laravel-5-1 can help you thank you
