### ISSUE TITLE
Allow Backing Up to S3/SFTP/etc. Remote Location

### ISSUE THREAD

**Issue by SlvrEagle23** [AzuraCast/AzuraCast#3216]
AzuraCast is meant to be installed on commodity VPS providers, which often don't have a lot of storage available for things like backups. For many installations, one or two backups is all it takes to fill up the server they're hosted on, causing problems down the line.

This feature request is to implement the ability to write backup files to S3, SFTP or some other remote sources. The process of producing the backup file would still need to take place locally, but the finished file could then immediately be uploaded to a remote source and then deleted from the local disk to reclaim the available space.

**Comment by r1ckross** [comment]
This is a great idea. It would also be very useful to make backups visible in the sftp system used for media files.

**Comment by SlvrEagle23** [comment]
Version 0.11 stable launched with support for storage locations, which can now use remote S3 locations.

**Comment by abuharsky** [comment]
If i run backup locally - backup.zip is about 20gb, but in S3 its only 5,2GB and S# not showing any files, just used space
