### ISSUE TITLE
Show Rich Media Information in "Song History" Player Modal

### ISSUE THREAD

**Issue by SlvrEagle23** [AzuraCast/AzuraCast#3218]
Currently, the song history modal is just an unordered list of track names and artist names, even if we have much richer metadata about each of the tracks (including album art and when the track was played).

We could expand the data to look much more engaging and to match the styling of how we show the currently playing track in the application.

**Comment by thicolares** [comment]
Hi @SlvrEagle23! I'm taking this one. Could you assign this to me?
