### ISSUE TITLE
The idea is to make several options for the players

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#322]
I had the idea to make several options for displaying the players, which you can then insert users on the site. For example, one classic version, the second option with the display of songs that are played and for example the following 5 songs that should be played, add the ability to change the look of the players. Thank you for your understanding.
![bdfb](https://user-images.githubusercontent.com/23697714/33765601-af5cdab0-dc2a-11e7-849a-8a8b88a80052.png)

**Comment by peppinoita** [comment]
Go here https://www.muses.org/setup and grab your preferred player.
This is useless to add in the Azuracast code.

**Comment by susl16c** [comment]
Why it's useless, it's convenient when it would all be in one place.

**Comment by SlvrEagle23** [comment]
@susl16c Closing this, as it's already an existing request #281. My response as to why this isn't a higher priority for my development is also included as a comment there.
