### ISSUE TITLE
Symfony Lock floods logs upon Now_Playing sync. 

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#3220]
**Using Docker installation method**

**AzuraCast version**
ac0dc6e (2020-09-29 - 16:59) 
**Host Operating System**
Ubuntu 20.04 

**Describe the bug**
Added in the https://github.com/AzuraCast/AzuraCast/commit/7bac35b2ff0c3a12ba73bcc50fd69dc0040334c3 update, the Symfony Lock replaced the old Lock system, while it's doing a good job, it's being a nuisance on the logs by flooding it every time a Sync Now_Playing is ran, making it almost impossible to conduct proper log inspections. 

**To Reproduce**
Spin up an AzuraCast instance, make a few stations, make sure music is in each of the stations, consult the Docker logs, see the flood. 

**Expected behavior**
The messages to be placed behind "debug" instead of INFO, or it to not flood the logs this badly.

**Relevant Logs**
```
web_1                      | [2020-09-30T01:38:46.834998+00:00] AzuraCast.INFO: Expiration defined for "{resource}" lock for "{ttl}" seconds. {"resource":{"Symfony\\Component\\Lock\\Key":"sync_nowplaying"},"ttl":600.0} []
web_1                      | [2020-09-30T01:38:46.997959+00:00] AzuraCast.INFO: Successfully acquired the "{resource}" lock. {"resource":{"Symfony\\Component\\Lock\\Key":"autodj_queue_5"}} []
```
**Screenshots**
https://puu.sh/GxOKT/a5c2c78058.mp4

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch I noticed that too...seems like Symfony libraries lean somewhat heavily on "info" (which, for a lot of debugging, so do we), but our production instances are set to echo everything from "info" up, which could lead to log floods of largely uninteresting information.

I bumped our log level on production instances to "notice", which is one notch higher but still includes all critical errors.
