### ISSUE TITLE
'station_requests.ip' column too short for IPv6 clients

### ISSUE THREAD

**Issue by Metal-Mighty** [AzuraCast/AzuraCast#3222]
**Using Docker installation method**

Yes

**AzuraCast version**

v0.10.3, #f8c04b4 (2020-09-01 0:54)

**Host Operating System**

Debian 10 Buster

**Describe the bug**

When making a song request or queueing a song in the station's Music Files, an SQL error pops up indicating that the data is too long for column 'ip'

**To Reproduce**

1. Go to the public page with song requests enabled
2. Request a song

or

1. Go to your station's Music Files screen
2. Select a song
3. Click on "Queue"

**Expected behavior**

The selected song must be queued and played next, and IPv6 IPs stored like IPv4

**Relevant Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/5247527/94743783-3d0aaa00-0378-11eb-9903-dbd42a84e61d.png)

**Device(s):**
 - Device:  Desktop
 - OS:  Windows 10
 - Browser:  Firefox
 - Version:  81

**Additional context**

**Comment by SlvrEagle23** [comment]
This is caused by us not expecting the IP field to arrive as a comma-separated value in `ipv6, ipv4` format. I was not aware this was a thing that ever happened with that header, but I can update the code to accommodate it.
