### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by DigitalBeatsFi** [AzuraCast/AzuraCast#3225]
Hi guys!

I know that this might be the wrong place to ask for this kind of help but I'm out of options. I've installed Azuracast to subdomain and Wordpress to top domain. My problem is that when I try to upload the wordpress theme, I get 413 error. I have hunted highs and lows throughout the whole internet and no success. I am total newbie when comes to Docker, so any help would be greatly appreciated.

**Comment by pascalla** [comment]
This isn't really related to Azuracast, but i'd say you need to up the limits for posting/upload in your php.ini

https://www.tecmint.com/increase-file-upload-size-in-php/

**Comment by SlvrEagle23** [comment]
@DigitalBeatsFi This is likely not related to AzuraCast itself.

If you're using our built-in reverse proxy to host multiple sites on your AzuraCast server, you can find additional documentation for it here:
https://github.com/nginx-proxy/nginx-proxy
