### ISSUE TITLE
Azuracast API used for cookies?

### ISSUE THREAD

**Issue by Radio-Quergedacht** [AzuraCast/AzuraCast#3227]
Azuracast API used for cookies?

**Comment by Radio-Quergedacht** [comment]
We need to know what kind of cookies the API uses in order to include it in our privacy policy

**Comment by Vaalyn** [comment]
The API (for example a call to `/api/nowplaying`) is setting the `__cfduid` cookie which is a simple session cookie. Apart from that the API does not set any other cookies.

You can check this by for example opening https://demo.azuracast.com/api/nowplaying with your browser, then open the Developer Console (in Chrome that's F12), going to the `Application` tab, in the left sidebar of the Console you can see under `Storage` the entry `Cookies`. Click on the arrow to open all domains with cookies for that page. Select the URL that's showing there and the panel on the right shows all cookies for that page.

**Comment by Radio-Quergedacht** [comment]
many thanks for the help
