### ISSUE TITLE
App\Entity\Api\NowPlaying::$playing_next must be an instance of App\Entity\Api\StationQueue or null, App\Entity\Api\SongHistory used

### ISSUE THREAD

**Issue by callumok2004** [AzuraCast/AzuraCast#3228]
**Using Docker installation method**
Yes

**AzuraCast version**
0.10.4 Stable

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
A few pages are throwing the same error
```
Typed property App\Entity\Api\NowPlaying::$playing_next must be an instance of App\Entity\Api\StationQueue or null, App\Entity\Api\SongHistory used
ArrayType.php : 52
```
**Relevant Logs**
Unable to provide, logs page also gives above error.

**Additional context**
N/A

**Comment by Xara** [comment]
I had similar error after OS update, restarting server then complete update with databases restore fixed it, is not a fix but is what worked for me.

**Comment by K0FT3** [comment]
> I had similar error after OS update, restarting server then complete update with databases restore fixed it, is not a fix but is what worked for me.

I also have a similar issue. can you explain what you did detailed? What do you mean by 'complete update with databases restore'?

**Comment by SlvrEagle23** [comment]
@callumok2004 The update process should be clearing all cached "Now Playing" data from the system, which should also be flushing any older entries from the individual stations that may be causing this error.

You should try updating again to see if it clears the respective caches and restarts the stations properly.

If you still encounter the error even when viewing the log page, you can still view it by running, from the host:

```bash
cd /var/azuracast
docker-compose logs -f web
```

**Comment by Vaalyn** [comment]
Closing as resolved since there have been no further replies.
