### ISSUE TITLE
Errors after fresh install Ubuntu Server

### ISSUE THREAD

**Issue by StreamDude** [AzuraCast/AzuraCast#323]
I don't know if there are others that encounter this problem?
After a fresh install of AzuraCast on Ubuntu Server 16.04 there are a lot of functions not working as they should. When I try to view the profile page I get an error, this also happens when I want to activate the station.

Here is the output:

fXmlRpc\Exception\FaultException: BAD_NAME: station_3:station_3_backend in file /var/azuracast/www/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Exception/FaultException.php on line 32
Stack trace:
  1. fXmlRpc\Exception\FaultException-&gt;() /var/azuracast/www/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Exception/FaultException.php:32
  2. fXmlRpc\Exception\FaultException-&gt;fault() /var/azuracast/www/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Parser/XmlReaderParser.php:373
  3. fXmlRpc\Parser\XmlReaderParser-&gt;parse() /var/azuracast/www/vendor/lstrojny/fxmlrpc/src/fXmlRpc/Client.php:156
  4. fXmlRpc\Client-&gt;call() /var/azuracast/www/vendor/supervisorphp/supervisor/src/Connector/XmlRpc.php:45
  5. Supervisor\Connector\XmlRpc-&gt;call() /var/azuracast/www/vendor/supervisorphp/supervisor/src/Supervisor.php:110
  6. Supervisor\Supervisor-&gt;__call() /var/azuracast/www/vendor/supervisorphp/supervisor/src/Supervisor.php:162
  7. Supervisor\Supervisor-&gt;getProcess() /var/azuracast/www/app/src/AzuraCast/Radio/AdapterAbstract.php:74
  8. AzuraCast\Radio\AdapterAbstract-&gt;isRunning() /var/azuracast/www/app/modules/stations/controllers/ProfileController.php:13
  9. Controller\Stations\ProfileController-&gt;indexAction() /var/azuracast/www/app/src/App/Mvc/Controller.php:100
 10. App\Mvc\Controller-&gt;dispatch() /var/azuracast/www/app/src/App/Mvc/Resolver.php:42
 11. App\Mvc\Resolver-&gt;App\Mvc\{closure}() /var/azuracast/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:41
 12. call_user_func() /var/azuracast/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:41
 13. Slim\Handlers\Strategies\RequestResponse-&gt;__invoke() /var/azuracast/www/vendor/slim/slim/Slim/Route.php:340
 14. Slim\Route-&gt;__invoke() /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:117
 15. Slim\Route-&gt;callMiddlewareStack() /var/azuracast/www/vendor/slim/slim/Slim/Route.php:316
 16. Slim\Route-&gt;run() /var/azuracast/www/vendor/slim/slim/Slim/App.php:479
 17. Slim\App-&gt;__invoke() /var/azuracast/www/app/bootstrap/services.php:343
 18. Closure-&gt;{closure}() /var/azuracast/www/vendor/slim/slim/Slim/DeferredCallable.php:43
 19. call_user_func_array() /var/azuracast/www/vendor/slim/slim/Slim/DeferredCallable.php:43
 20. Slim\DeferredCallable-&gt;__invoke() /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:70
 21. call_user_func() /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:70
 22. Slim\App-&gt;Slim\{closure}() /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:117
 23. Slim\App-&gt;callMiddlewareStack() /var/azuracast/www/vendor/slim/slim/Slim/App.php:370
 24. Slim\App-&gt;process() /var/azuracast/www/vendor/slim/slim/Slim/App.php:295
 25. Slim\App-&gt;run() /var/azuracast/www/web/index.php:9

**Comment by SlvrEagle23** [comment]
@StreamDude That's an error with the application communicating with supervisord.

Did you do the "traditional" install with `install.sh`? If so, you may need to restart or start the supervisord service. There's a known issue with supervisord reporting itself as spun up before it actually is, causing a great deal of trouble on our end.

**Comment by StreamDude** [comment]
@SlvrEagle23 Wow that was quick ! :-)
Yes I did the traditional install, no docker install.
I restarted the supervisor service (service supervisor restart) but no luck for me.

**Comment by SlvrEagle23** [comment]
@StreamDude Is there a file at the path: `/var/azuracast/stations/(whatever station 3 is called)/config/supervisord.conf`? If not, you may need to delete and recreate the station. Also, if you assigned a custom URL for that station, make sure it's also a valid folder name.

**Comment by StreamDude** [comment]
@SlvrEagle23 
The file was not there. I deleted station 3 and created a new station called test.
I did not create a custom URL for it. This also doesn't solve my problem.
I think I will need to delete AzuraCast and try to make a docker install.

The strange thing is that it worked fine before on Ubuntu Server with a regular install

**Comment by SlvrEagle23** [comment]
@StreamDude I'm not sure why it happened with the third station but not the first two. That's what's got me confused.

In either case, I'd still highly recommend using the Docker install to avoid this whole class of errors that depend on the manually installed software.

**Comment by StreamDude** [comment]
@SlvrEagle23 
Station 1 and 2 also had these errors that's why I deleted them as well :-)
I made the install on a fresh install of Ubuntu Server.

It's weekend so I got plenty of time. I will make another fresh install of Ubuntu server and then go for the Docker install

Thank's for your help and have a great weekend !

**Comment by SlvrEagle23** [comment]
@StreamDude Just found an issue with the code where if a station is newly created _without_ a custom station URL, the default station URL is set to an empty string, which causes this problem.

Update and try it out, and your traditional install should be working fine. Sorry about that!

**Comment by StreamDude** [comment]
@SlvrEagle23 
Ahhh just too late :( I did already hit the button for a fresh Ubuntu install.

Nice that you found the error ! 

Thank's again for your time
