### ISSUE TITLE
Update fail, then database restore fail, stations still operational. 

### ISSUE THREAD

**Issue by Xara** [AzuraCast/AzuraCast#3234]
Hello, again me with an update issue, this time

**Using Docker installation method**

No
**AzuraCast version**

Powered by AzuraCast • v0.10.4, #f09023e (2020-10-05 0:13) • Ansible • PHP 7.4
**Host Operating System**

Ubuntu 20.04 Focal
**Describe the bug**

Update fail, databases restore fail 
**To Reproduce**

Perform standart update with cd /var/azuracast/www && ./update.sh
**Expected behavior**

An update
**Relevant Logs**

TASK [azuracast-setup : Run AzuraCast Setup (Update Mode)] *****************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/console azuracast:setup --update", "delta": "0:00:01.121816", "end": "2020-10-05 16:24:03.081915", "msg": "non-zero return code", "rc": 1, "start": "2020-10-05 16:24:01.960099", "stderr": " 0/3 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%\n 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%[error] Migration App\\Entity\\Migration\\Version20201003021913 failed during Execution. Error: \"An exception occurred while executing 'ALTER TABLE station_media ADD text VARCHAR(150) DEFAULT NULL AFTER song_id, CHANGE title title VARCHAR(150) DEFAULT NULL, CHANGE artist artist VARCHAR(150) DEFAULT NULL':\n\nSQLSTATE[01000]: Warning: 1265 Data truncated for column 'artist' at row 9357\"\n\nIn AbstractMySQLDriver.php line 128:\n                                                                               \n  An exception occurred while executing 'ALTER TABLE station_media ADD text V  \n  ARCHAR(150) DEFAULT NULL AFTER song_id, CHANGE title title VARCHAR(150) DEF  \n  AULT NULL, CHANGE artist artist VARCHAR(150) DEFAULT NULL':                  \n                                                                               \n  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'artist' at row 93  \n  57                                                                           \n                                                                               \n\nIn Exception.php line 18:\n                                                                               \n  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'artist' at row 93  \n  57                                                                           \n                                                                               \n\nIn PDOConnection.php line 51:\n                                                                               \n  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'artist' at row 93  \n  57                                                                           \n                                                                               \n\nazuracast:setup [--update] [--load-fixtures] [--release]", "stderr_lines": [" 0/3 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%", " 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%[error] Migration App\\Entity\\Migration\\Version20201003021913 failed during Execution. Error: \"An exception occurred while executing 'ALTER TABLE station_media ADD text VARCHAR(150) DEFAULT NULL AFTER song_id, CHANGE title title VARCHAR(150) DEFAULT NULL, CHANGE artist artist VARCHAR(150) DEFAULT NULL':", "", "SQLSTATE[01000]: Warning: 1265 Data truncated for column 'artist' at row 9357\"", "", "In AbstractMySQLDriver.php line 128:", "                                                                               ", "  An exception occurred while executing 'ALTER TABLE station_media ADD text V  ", "  ARCHAR(150) DEFAULT NULL AFTER song_id, CHANGE title title VARCHAR(150) DEF  ", "  AULT NULL, CHANGE artist artist VARCHAR(150) DEFAULT NULL':                  ", "                                                                               ", "  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'artist' at row 93  ", "  57                                                                           ", "                                                                               ", "", "In Exception.php line 18:", "                                                                               ", "  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'artist' at row 93  ", "  57                                                                           ", "                                                                               ", "", "In PDOConnection.php line 51:", "                                                                               ", "  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'artist' at row 93  ", "  57                                                                           ", "                                                                               ", "", "azuracast:setup [--update] [--load-fixtures] [--release]"], "stdout": "\nAzuraCast Setup\n===============\n\nWelcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...\n * Environment: Production\n * Installation Method: Ansible\n\nWaiting for dependent services to go online...\n\n\n ! [NOTE] Running in update mode.                                               \n\nMigrating Legacy Configuration\n------------------------------\n\nConfiguration already set up.\n\nSetting Up InfluxDB\n-------------------\n\nDatabase created.\nRetention policies updated.\nContinuous queries created.\nInfluxDB databases created.\n\nRunning Database Migrations\n---------------------------\n\n[notice] Migrating up to App\\Entity\\Migration\\Version20201003023117", "stdout_lines": ["", "AzuraCast Setup", "===============", "", "Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...", " * Environment: Production", " * Installation Method: Ansible", "", "Waiting for dependent services to go online...", "", "", " ! [NOTE] Running in update mode.                                               ", "", "Migrating Legacy Configuration", "------------------------------", "", "Configuration already set up.", "", "Setting Up InfluxDB", "-------------------", "", "Database created.", "Retention policies updated.", "Continuous queries created.", "InfluxDB databases created.", "", "Running Database Migrations", "---------------------------", "", "[notice] Migrating up to App\\Entity\\Migration\\Version20201003023117"]}

PLAY RECAP *****************************************************************************************
localhost                  : ok=21   changed=10   unreachable=0    failed=1    skipped=78   rescued=0    ignored=0
**Screenshots**

n/a
**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by JP-FOURNIER** [comment]
same

**Comment by SlvrEagle23** [comment]
@Xara The latest update should fix this issue during the migration process.

**Comment by JP-FOURNIER** [comment]
Thanks it work for me

**Comment by Xara** [comment]
Great, super support and very fast fix, you are the best guys, well just after me, of course :) huggs! thank you.
