### ISSUE TITLE
Update Fail, clear install on clear os Fail.

### ISSUE THREAD

**Issue by tick-hack** [AzuraCast/AzuraCast#3235]
**Using Docker installation method**

Yes
**AzuraCast version**

Latest
**Host Operating System**

Ubuntu 20.04
**Describe the bug**

After clear install on clear os and input radio name and url i get this
![image](https://user-images.githubusercontent.com/72400959/95097077-bbc76480-0735-11eb-89a4-1dcbd98b9f03.png)

``
**To Reproduce**

**Expected behavior**

**Relevant Logs**

https://dropmefiles.com/si9yg

Can`t copy\paste here, too long

**Screenshots**

**Device(s):**
 - Device: all 
 - OS: all
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@tick-hack Try running the installation again after this morning's fixes. It should resolve any issues that are present.
