### ISSUE TITLE
Can't upload songs

### ISSUE THREAD

**Issue by Noxero** [AzuraCast/AzuraCast#3237]
I try to upload songs to the autodj but gets following message;

Argument 1 passed to App\Entity\StationMedia::setSong() must implement interface App\Entity\SongInterface, instance of NowPlaying\Result\CurrentSong given, called in /var/azuracast/www/src/Entity/Repository/StationMediaRepository.php on line 268

**Comment by SC2Mitch** [comment]
I reported this a little bit ago in the AzuraCast discord, here's my logs. 

`
{"code":0,"message":"Argument 1 passed to App\\Entity\\StationMedia::setSong() must implement interface App\\Entity\\SongInterface, instance of NowPlaying\\Result\\CurrentSong given, called in /var/azuracast/www/src/Entity/Repository/StationMediaRepository.php on line 268","formatted_message":"Argument 1 passed to App\\Entity\\StationMedia::setSong() must implement interface App\\Entity\\SongInterface, instance of NowPlaying\\Result\\CurrentSong given, called in /var/azuracast/www/src/Entity/Repository/StationMediaRepository.php on line 268","extra_data":[],"success":false} 
`
