### ISSUE TITLE
Missing metadatas in the API

### ISSUE THREAD

**Issue by Donokami** [AzuraCast/AzuraCast#324]
Hello,
Earlier i reported a bug in #246 where [the cover and the duration of a song where not reported](https://github.com/AzuraCast/AzuraCast/issues/246#issuecomment-343733133) in the API.
At this moment, i was using a playlist with only 2 songs, so this behaviour was expected;
But now, i use one playlist with 490 songs, and this bug has come back.
Here is what i mean:
```
  "now_playing": {
    "is_live": true,
    "elapsed": 102,
    "remaining": 0,
    "sh_id": 12342,
    "played_at": 1512907547,
    "duration": 0,
    "is_request": false,
    "song": {
      "id": "76d6261f0d21715089acae1f49b6205a",
      "text": "soulostar - Sunset Flow",
      "artist": "soulostar",
      "title": "Sunset Flow",
      "album": "",
      "lyrics": "",
      "art": ""
    }
  },
  "playing_next": {
    "sh_id": 12340,
    "played_at": 0,
    "duration": 110,
    "is_request": false,
    "song": {
      "id": "30abcaed6943bc81985c8407ee3179f8",
      "text": "[offbeatninja] - Force Of Nature [心の平穏]",
      "artist": "[offbeatninja]",
      "title": "Force Of Nature [心の平穏]",
      "album": "Fuyu vol. 1",
      "lyrics": "",
      "art": "http://nyan.cat/api/station/1/art/ef1f47f15a7eff9a359dfb76"
    }
```
The remaining and the duration are set to 0 for now_playing, the cover url is not shared, but playing_next works correctly.
I think i used to correct this issue before, with a trick but i don't remember how.
Thanks :)
(I use Version v0.7.1-2017.08 Alpha, PHP 7.1.11-1+ubuntu16.04.1+deb.sury.org+1, SlimPHP 3, Icecast 2.4.0-kh7-2-g7d9cec1, nginx/1.10.1 and Liquidsoap 1.1.1)

**Comment by SlvrEagle23** [comment]
@Donokami This usually happens when LiquidSoap goes "off the rails" and stops depending on what next song AzuraCast provides it.

If you have filesystem access, try this (or run it inside `docker-compose run --rm cli`):
```
tail -f /var/azuracast/stations/your_station_name/config/liquidsoap.log
```

Sometimes the quick fix is to just go to Utilities > Restart Broadcasting and see if that fixes it.

**Comment by Donokami** [comment]
The only log i have in this file is this:
```
2017/12/10 15:29:13 [lang:3] AzuraCast Raw Response: <html>
2017/12/10 15:29:13 [request:3] Nonexistent file or ill-formed URI "<html>\r"!
```
I already tried to restart the broadcasting/restart icecast/restart liquidsoap and reboot my vps, with no better result;
I didn't mentionned that, but i use the traditionnal installation !

**Comment by SlvrEagle23** [comment]
@Donokami That actually tells us a lot about the problem...try logging in, then manually visiting:
http://your.azuracast.site/api/internal/1/nextsong (where 1 is your station ID)

**Comment by Donokami** [comment]
I have this on this page:
`annotate:title="Grown Kids",artist="Giorgio Oehlers":/var/azuracast/stations/oldoak/media/Fuyu vol. 1/Giorgio Oehlers - Grown Kids.mp3`

**Comment by SlvrEagle23** [comment]
@Donokami Huh, but that's normal :/ not sure how to figure out what the problem is, then...

**Comment by Donokami** [comment]
I've updated Azuracast, then the time metadatas re-appeared (but without song's album covers).
After that, i did a `php /var/azuracast/www/util/cli.php azuracast:media:reprocess` and the api broke one more time.

**Comment by SlvrEagle23** [comment]
@Donokami This one's probably one of those "x only happens when Y and Z are the case" bugs, which are incredibly hard to track down.

If you notice the API is saying "is_live" is `true` when it isn't, check the logs and that internal `nextsong` URL and see if it says anything different from normal.

**Comment by Donokami** [comment]
Okay, so i did some tests, like updating Icecast-kh or checking what says my API when i stop Icecast and/or Liquidsoap. Here are the results:
In `http://my.azuracast.site/api/station/1/nowplaying` i got this:
```
"now_playing": {

    "is_live": true,
    "elapsed": 6,
    "remaining": 0,
    "sh_id": 13234,
    "played_at": 1513065016,
    "duration": 0,
    "is_request": false,
    "song": {
        "id": "7a1230502efebe8990578f71285bcf46",
        "text": "Stream Offline",
        "artist": "",
        "title": "",
        "album": "",
        "lyrics": "",
        "art": ""
    }

},
"playing_next": {

    "sh_id": 13229,
    "played_at": 0,
    "duration": 300,
    "is_request": false,
    "song": {
        "id": "be199a0f29c595ad010d5559f718e18b",
        "text": "DJ CAM & DJ CAM QUARTET(official) - Rebirth Of Cool",
        "artist": "DJ CAM & DJ CAM QUARTET(official)",
        "title": "Rebirth Of Cool",
        "album": "Fuyu vol. 1",
        "lyrics": "",
        "art": "http://my.azuracast.site/api/station/1/art/ece3311a962b549f505f1112"
    }

},
```
In `http://my.azuracast.site/api/internal/1/nextsong` i got this:
`annotate:title="Nitsua - Lost In Translation [Premiere]",artist="Chillhop Music":/var/azuracast/stations/oldoak/media/Fuyu vol. 1/Chillhop Music - Nitsua - Lost In Translation [Premiere].mp3`

So, I don't understand when does "is_live: false" is triggered, as I couldn't find out how to trigger it.
Thanks.

**Comment by SlvrEagle23** [comment]
@Donokami Sorry, I meant to mention earlier that if it does the "is_live: true" thing again, check the PHP error logs via `docker-compose logs -f web` and see if they pop anything up...that could be the key to fixing it

**Comment by Donokami** [comment]
Since i'm not on a docker installation, i tried checking `/var/log/php7.1-fpm.log` and `/var/log/nginx/error.log`, and i didn't found any errors. :/

**Comment by SlvrEagle23** [comment]
@Donokami Have recent updates made any progress on this? There was an issue a few weeks ago with HTTPS installations that might've been causing the problems on this.

**Comment by Donokami** [comment]
Updated using update.sh, still the same issue. :/

**Comment by SlvrEagle23** [comment]
@Donokami No! :(

Can I see your AzuraCast install and see if I can get it fixed? I'm curious if this is a widespread problem and I want to see what's causing it in your case. If you don't mind that, send me an e-mail at loobalightdark@gmail.com.

**Comment by Donokami** [comment]
My VPS has important and private information, so i'm trying to find a solution to get a test installation with the same configuration as my main server.
I will contact you when I find a solution, but thanks for your help ! :)

**Comment by SlvrEagle23** [comment]
@Donokami Any update on this? Just checking up, since it's been a while.
