### ISSUE TITLE
Running Database Migrations error

### ISSUE THREAD

**Issue by danielrodrigotest** [AzuraCast/AzuraCast#3240]
Dear azuracast, the reason of this report is that failed during update in special with the database migrations. 

> 
Running Database Migrations
---------------------------

[notice] Migrating up to App\Entity\Migration\Version20201003023117
[error] Migration App\Entity\Migration\Version20201003023117 failed during Execution. Error: "An exception occurred while executing 'ALTER TABLE song_history DROP FOREIGN KEY FK_2AD16164A0BDB2F3':

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_2AD16164A0BDB2F3`; check that it exists"

In AbstractMySQLDriver.php line 128:
                                                                                                                              
  An exception occurred while executing 'ALTER TABLE song_history DROP FOREIGN KEY FK_2AD16164A0BDB2F3':                      
                                                                                                                              
  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_2AD16164A0BDB2F3`; check that it exists  
                                                                                                                              

In Exception.php line 18:
                                                                                                                              
  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_2AD16164A0BDB2F3`; check that it exists  
                                                                                                                              

In PDOConnection.php line 51:
                                                                                                                              
  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_2AD16164A0BDB2F3`; check that it exists  
 > 
![Screenshot 2020-10-06 at 11 00 53](https://user-images.githubusercontent.com/40525323/95211680-41ddbc80-07c3-11eb-96da-86ef8fdc28e3.png)

**Comment by SlvrEagle23** [comment]
@danielrodrigotest You appear to have wound up with your database in a strange state, perhaps because an update previous to this one didn't go through completely successfully.

I've made some minor changes to the migration that should help push it along in your case, but if that doesn't help you may need to look into restoring from a backup or working with us more directly to fix your specific database state.

**Comment by danielrodrigotest** [comment]
Is there a change for repairing the database or i will have to reinstall azuracast from zero?

**Comment by SlvrEagle23** [comment]
@danielrodrigotest Try re-running the update process and see if it resolves the issue for you. If not, we may need to look at your specific installation to figure out how it got into a broken state.

**Comment by danielrodrigotest** [comment]
I have the same problem :/
![Screenshot 2020-10-07 at 17 02 06](https://user-images.githubusercontent.com/40525323/95381655-d5e07e80-08be-11eb-8819-48a9976904f8.png)

**Comment by SlvrEagle23** [comment]
@danielrodrigotest Try updating again; if that doesn't work, we will need to work via Slack or Discord to recover your instance.

**Comment by fast97** [comment]
Hello I have the same problem on the new update. Thank
![cap21](https://user-images.githubusercontent.com/51033222/95419631-4c6e9200-093a-11eb-9dfc-633d68388806.png)

**Comment by SlvrEagle23** [comment]
@fast97 That should be fixed as of the latest update I just published.

**Comment by fast97** [comment]
> @ fast97 Cela devrait être corrigé à partir de la dernière mise à jour que je viens de publier.
hello solved for me
