### ISSUE TITLE
Station cannon be restarted and error 500

### ISSUE THREAD

**Issue by danielrodrigotest** [AzuraCast/AzuraCast#3241]
The second issue found refers to **Return value of App\Entity\StationMedia::getSongId()** must be of the type string, null returned. I tried to restart the station and I get the error previously mentioned, the same case when I try to restart the AutoDj. In fact, in some cases the playlist (jingle mode) repeats itself with no chances to play any song. To this, I tried to change to icecast, but it's the same case.

![Screenshot 2020-10-06 at 12 21 00](https://user-images.githubusercontent.com/40525323/95221977-68edbb80-07ce-11eb-8394-375066cb1d33.png)

![Screenshot 2020-10-06 at 12 17 16](https://user-images.githubusercontent.com/40525323/95221506-e238de80-07cd-11eb-80bb-b106bee1fb0e.png)

![Screenshot 2020-10-06 at 12 19 22](https://user-images.githubusercontent.com/40525323/95221823-3b087700-07ce-11eb-8466-de5ea892e42e.png)

Here's the log:

> 2020/10/06 12:17:10 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/fm_97_chile/media/DJ RD DJVIRTUAL /DJ RD DJ VIRTUAL/MIX  VARIOS  DJ RD .mp3".
2020/10/06 12:17:10 [playlist_programa_classic_de_rock:3] Playlist treated as format application/x-mpegURL
2020/10/06 12:17:10 [playlist_programa_classic_de_rock:3] Successfully loaded a playlist of 279 tracks.
2020/10/06 12:17:10 [playlist_presentacion_2B_tema_recuerdo_sotano_1:3] Loading playlist...
2020/10/06 12:17:10 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_presentacion-2B_tema_recuerdo_sotano_1.m3u"!
2020/10/06 12:17:10 [playlist_presentacion_2B_tema_recuerdo_sotano_1:2] Failed when resolving playlist URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_presentacion-2B_tema_recuerdo_sotano_1.m3u"!
2020/10/06 12:17:10 [playlist_presentacion_2B_tema_recuerdo_sotano_1:3] Successfully loaded a playlist of 0 tracks.
2020/10/06 12:17:10 [playlist_cuNa_apoyo_radios(dot)cl_:3] Loading playlist...
2020/10/06 12:17:10 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_cuNa_apoyo_radios.cl_.m3u"!
2020/10/06 12:17:10 [playlist_cuNa_apoyo_radios(dot)cl_:2] Failed when resolving playlist URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_cuNa_apoyo_radios.cl_.m3u"!
2020/10/06 12:17:10 [playlist_cuNa_apoyo_radios(dot)cl_:3] Successfully loaded a playlist of 0 tracks.
2020/10/06 12:17:10 [playlist_pop_sensation_2020:3] Loading playlist...
2020/10/06 12:17:10 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_pop_sensation_2020.m3u"!
2020/10/06 12:17:10 [playlist_pop_sensation_2020:2] Failed when resolving playlist URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_pop_sensation_2020.m3u"!
2020/10/06 12:17:10 [playlist_pop_sensation_2020:3] Successfully loaded a playlist of 0 tracks.
2020/10/06 12:17:10 [playlist_cuNa_clasico_voz_mujer:3] Loading playlist...
2020/10/06 12:17:10 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_cuNa_clasico_voz_mujer.m3u"!
2020/10/06 12:17:10 [playlist_cuNa_clasico_voz_mujer:2] Failed when resolving playlist URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_cuNa_clasico_voz_mujer.m3u"!
2020/10/06 12:17:10 [playlist_cuNa_clasico_voz_mujer:3] Successfully loaded a playlist of 0 tracks.
2020/10/06 12:17:10 [playlist_cuNa_locucion_new_fm97_:3] Loading playlist...
2020/10/06 12:17:10 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_cuNa_locucion_new_fm97_.m3u"!
2020/10/06 12:17:10 [playlist_cuNa_locucion_new_fm97_:2] Failed when resolving playlist URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_cuNa_locucion_new_fm97_.m3u"!
2020/10/06 12:17:10 [playlist_cuNa_locucion_new_fm97_:3] Successfully loaded a playlist of 0 tracks.
2020/10/06 12:17:10 [playlist_dance_gold_varios_:3] Loading playlist...
2020/10/06 12:17:10 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_dance_gold_varios_.m3u"!
2020/10/06 12:17:10 [playlist_dance_gold_varios_:2] Failed when resolving playlist URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_dance_gold_varios_.m3u"!
2020/10/06 12:17:10 [playlist_dance_gold_varios_:3] Successfully loaded a playlist of 0 tracks.
2020/10/06 12:17:10 [playlist_cuNa_cambio_estilo:3] Loading playlist...
2020/10/06 12:17:10 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_cuNa_cambio_estilo.m3u"!
2020/10/06 12:17:10 [playlist_cuNa_cambio_estilo:2] Failed when resolving playlist URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_cuNa_cambio_estilo.m3u"!
2020/10/06 12:17:10 [playlist_cuNa_cambio_estilo:3] Successfully loaded a playlist of 0 tracks.
2020/10/06 12:17:10 [playlist_promo_de_rock_latino_:3] Loading playlist...
2020/10/06 12:17:10 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_promo_de_rock_latino_.m3u"!
2020/10/06 12:17:10 [playlist_promo_de_rock_latino_:2] Failed when resolving playlist URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_promo_de_rock_latino_.m3u"!
2020/10/06 12:17:10 [playlist_promo_de_rock_latino_:3] Successfully loaded a playlist of 0 tracks.
2020/10/06 12:17:10 [playlist_soft_rock_seleccion_:3] Loading playlist...
2020/10/06 12:17:10 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_soft_rock_seleccion_.m3u"!
2020/10/06 12:17:10 [playlist_soft_rock_seleccion_:2] Failed when resolving playlist URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_soft_rock_seleccion_.m3u"!
2020/10/06 12:17:10 [playlist_soft_rock_seleccion_:3] Successfully loaded a playlist of 0 tracks.
2020/10/06 12:17:10 [playlist_promo_clasicc_rock:3] Loading playlist...
2020/10/06 12:17:10 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_promo_clasicc_rock.m3u"!
2020/10/06 12:17:10 [playlist_promo_clasicc_rock:2] Failed when resolving playlist URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_promo_clasicc_rock.m3u"!
2020/10/06 12:17:10 [playlist_promo_clasicc_rock:3] Successfully loaded a playlist of 0 tracks.
2020/10/06 12:17:10 [playlist_promo_fm97_new_2020:3] Loading playlist...
2020/10/06 12:17:10 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_promo_fm97_new_2020.m3u"!
2020/10/06 12:17:10 [playlist_promo_fm97_new_2020:2] Failed when resolving playlist URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_promo_fm97_new_2020.m3u"!
2020/10/06 12:17:10 [playlist_promo_fm97_new_2020:3] Successfully loaded a playlist of 0 tracks.
2020/10/06 12:17:10 [playlist_90_seleccion_gold_:3] Loading playlist...
2020/10/06 12:17:10 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_90_seleccion_gold_.m3u"!
2020/10/06 12:17:10 [playlist_90_seleccion_gold_:2] Failed when resolving playlist URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_90_seleccion_gold_.m3u"!
2020/10/06 12:17:10 [playlist_90_seleccion_gold_:3] Successfully loaded a playlist of 0 tracks.
2020/10/06 12:17:10 [playlist_70_seleccion:3] Loading playlist...
2020/10/06 12:17:10 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_70_seleccion.m3u"!
2020/10/06 12:17:10 [playlist_70_seleccion:2] Failed when resolving playlist URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_70_seleccion.m3u"!
2020/10/06 12:17:10 [playlist_70_seleccion:3] Successfully loaded a playlist of 0 tracks.
2020/10/06 12:17:10 [playlist_musica_disco_:3] Loading playlist...
2020/10/06 12:17:10 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_musica_disco_.m3u"!
2020/10/06 12:17:10 [playlist_musica_disco_:2] Failed when resolving playlist URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_musica_disco_.m3u"!
2020/10/06 12:17:10 [playlist_musica_disco_:3] Successfully loaded a playlist of 0 tracks.
2020/10/06 12:17:10 [playlist_apoyo_streamchileno(dot):3] Loading playlist...
2020/10/06 12:17:10 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_apoyo_streamchileno..m3u"!
2020/10/06 12:17:10 [playlist_apoyo_streamchileno(dot):2] Failed when resolving playlist URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_apoyo_streamchileno..m3u"!
2020/10/06 12:17:10 [playlist_apoyo_streamchileno(dot):3] Successfully loaded a playlist of 0 tracks.
2020/10/06 12:17:10 [playlist_historial_de_fm97radios_:3] Loading playlist...
2020/10/06 12:17:10 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_historial_de_fm97radios_.m3u"!
2020/10/06 12:17:10 [playlist_historial_de_fm97radios_:2] Failed when resolving playlist URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_historial_de_fm97radios_.m3u"!
2020/10/06 12:17:10 [playlist_historial_de_fm97radios_:3] Successfully loaded a playlist of 0 tracks.
2020/10/06 12:17:10 [playlist_80_seleccion_:3] Loading playlist...
2020/10/06 12:17:10 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_80_seleccion_.m3u"!
2020/10/06 12:17:10 [playlist_80_seleccion_:2] Failed when resolving playlist URI "/var/azuracast/stations/fm_97_chile/playlists/playlist_80_seleccion_.m3u"!
2020/10/06 12:17:10 [playlist_80_seleccion_:3] Successfully loaded a playlist of 0 tracks.
2020/10/06 12:17:10 [error_jingle:3] "/usr/local/share/icecast/web/error.mp3" is static, resolving once for all...
2020/10/06 12:17:10 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/fm_97_chile/media/PRESENTACION ROCK LATINO /presentacion_rock_latino.mp3".
2020/10/06 12:17:10 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/fm_97_chile/media/ROCK GOLD LUZ DE LUNA /baladas_del_rock_4.mp3".
2020/10/06 12:17:10 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/fm_97_chile/media/CLASICOS DEL ROCK PROG/10 - Open Arms.mp3".
2020/10/06 12:17:10 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 6).
2020/10/06 12:17:10 [fm_97_chile_local_1:3] Connecting mount sid#1 for @127.0.0.1...
2020/10/06 12:17:10 [fm_97_chile_local_1:3] Connection setup was successful.
2020/10/06 12:17:10 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2020/10/06 12:17:10 [fm_97_chile_safe_fallback:3] Switch to error_jingle.
2020/10/06 12:17:11 [lang:3] AzuraCast Raw Response: annotate:title="Stream Offline",duration="34.01",song_id="6df358ac88f97383a59096472a43a8d4",liq_amplify="0.00dB",jingle_mode="true":/var/azuracast/stations/fm_97_chile/media/CUÑA APOYO RADIOS /cuna_promo_comerciales-2.mp3
2020/10/06 12:17:11 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/fm_97_chile/media/CU\195\145A APOYO RADIOS /cuna_promo_comerciales-2.mp3".
2020/10/06 12:17:11 [fm_97_chile_next_song:3] Prepared "/var/azuracast/stations/fm_97_chile/media/CU\195\145A APOYO RADIOS /cuna_promo_comerciales-2.mp3" (RID 33).
2020/10/06 12:17:11 [fm_97_chile_safe_fallback:3] Switch to compress_8191 with transition.
2020/10/06 12:17:11 [fm_97_chile_requests_fallback:3] Switch to fm_97_chile_interrupt_switch.
2020/10/06 12:17:11 [fm_97_chile_interrupt_switch:3] Switch to fm_97_chile_autodj_fallback.
2020/10/06 12:17:11 [fm_97_chile_autodj_fallback:3] Switch to fm_97_chile_cue_next_song.
2020/10/06 12:17:11 [lang:3] AzuraCast Raw Response: annotate:title="Stream Offline",duration="7.00",song_id="3219f812693b73ff9068361c0032acda",liq_amplify="0.00dB",jingle_mode="true":/var/azuracast/stations/fm_97_chile/media/CUÑA NEW FM97/fm_97_-_027.mp3
2020/10/06 12:17:11 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/fm_97_chile/media/CU\195\145A NEW FM97/fm_97_-_027.mp3".
2020/10/06 12:17:11 [lang:3] AzuraCast Raw Response: annotate:title="promo clasicos del rock fm 97",duration="28.00",song_id="b2f1469692f4061e2a9726eef84e64f1",media_id="68287",liq_amplify="0.00dB",playlist_id="381":/var/azuracast/stations/fm_97_chile/media/Promo Clasicc Rock/promo_clasicos_del_rock_fm_97
2020/10/06 12:17:11 [decoder:3] Unable to decode "/var/azuracast/stations/fm_97_chile/media/Promo Clasicc Rock/promo_clasicos_del_rock_fm_97" as {audio=1+;video=0;midi=0}!
2020/10/06 12:17:11 [lang:3] AzuraCast Feedback Response: OK
2020/10/06 12:17:11 [lang:3] AzuraCast Raw Response: annotate:title="Stream Offline",duration="121.55",song_id="b4c2775328152ef25f5a192fa4701e04",liq_amplify="0.00dB",jingle_mode="true":/var/azuracast/stations/fm_97_chile/media/HISTORIAL DE LA FM97RADIOS /promo_radio_fm97_03092020.mp3
2020/10/06 12:17:11 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/fm_97_chile/media/HISTORIAL DE LA FM97RADIOS /promo_radio_fm97_03092020.mp3".
2020/10/06 12:17:14 [main:3] Shutdown started!
2020/10/06 12:17:14 [main:3] Waiting for main threads to terminate...
2020/10/06 12:17:14 [fm_97_chile_local_1:3] Closing connection...
2020/10/06 12:17:14 [clock.wallclock_main:3] Streaming loop stopped.
2020/10/06 12:17:14 [main:3] Threads terminated.
2020/10/06 12:17:14 [threads:3] Shutting down scheduler...
2020/10/06 12:17:14 [threads:3] Scheduler shut down.
2020/10/06 12:17:14 [threads:3] Waiting for queue threads to terminate...
2020/10/06 12:17:14 [threads:3] Queues shut down
2020/10/06 12:17:14 [server:3] Closing socket.
2020/10/06 12:17:14 [main:3] Cleaning downloaded files...
2020/10/06 12:17:14 [main:3] Freeing memory...

**Comment by danielrodrigotest** [comment]
Liquidsoap may be in conflict...After the last update, my station is with the same problem! :(

**Comment by SlvrEagle23** [comment]
@danielrodrigotest From your host server, try running:

```bash
cd /var/azuracast
./docker.sh cli orm:run-dql 'DELETE FROM App\Entity\StationMedia sm WHERE sm.song_id IS NULL'
```

I have included this in the database migration for subsequent users, but you will need to manually run it to remove these media files that don't properly have Song IDs associated with them.

**Comment by Vaalyn** [comment]
Closing as resolved since there have been no recent reports of this happening.
