### ISSUE TITLE
API - now_playing.song.text is empty

### ISSUE THREAD

**Issue by pixel-paul** [AzuraCast/AzuraCast#3244]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #ea19b97 (2020-10-07 8:50)

**Host Operating System**
CentOS 7

**Describe the bug**
From the api, the following variable is now empty: now_playing.song.text

Previously this was a concatenated string of artist - title

**To Reproduce**
Query this end point: https://your-stream.fm/api/nowplaying/your_stream

song |  
-- | --
id | "343d5d7ab2686e3a3bda41dd92308a3a"
text | ""
artist | "My Arists"
title | "Song 123"
album | "Blah"
lyrics | ""

**Expected behavior**
a concanated string of artist - title

**Additional context**
Work around is to concatenate the string yourself using now_playing.song.artist + ' - ' +  now_playing.song.title :)

**Comment by Vaalyn** [comment]
Can't see that as a general issue on the demo installation.

Would you mind providing us with some information about the songs where this is happening for you?
Anything in the logs that might indicate an error?

**Comment by SlvrEagle23** [comment]
@pixel-paul This is a valid issue for tracks that were processed before the restructuring of our song data that just happened a few days ago. The latest update should fix this issue by restoring the "text" property to Station Media fields.
