### ISSUE TITLE
Under specific circumstances, a station can be stuck on 'Fatal error: Uncaught TypeError: Argument 1' Argument 1 passed to App\Entity\Repository\SongHistoryRepository::register() must implement interface App\Entity\SongInterface

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#3245]
**Using Docker installation method**
Yep! 

**AzuraCast version**
Rolling Release #7de1012

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
In very rare circumstances a station can become locked up and in a state of unavailability as the system gets 'confused' in what it's trying to do, Liquidsoap completely stops responding along with IceCast. The video I've provided shows it better. 
**To Reproduce**
Spin up a new station, run it in either IceCast or ShoutCast and restart the station, refresh the page once again and review the logs. 
**Expected behavior**

**Relevant Logs**
Exact logs can be found here: https://pastebin.com/dzt6ikwz

**Screenshots**
https://streamable.com/8c74q3

**Device(s):**
Edge, latest, windows desktop. 

**Additional context**
My titles suck, I'm sorry

**Comment by SlvrEagle23** [comment]
@SC2Mitch Thanks for the report and the error log. My IDE actually warned me this one could be a problem and silly me ignored it; turns out it's definitely a real possibility to happen with newly created stations. Latest commit fixes it.
