### ISSUE TITLE
New intermittent error happening at random in stream....

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#3249]
See screenshot below;

These warnings are happening at random during live feeds.  Wondering exactly what is being flagged as I haven't seen anything about these in the documentation...

My web site radio player sometimes stops and has to be restarted manually by the auditors on these occurrences, but not always.  Also, I'm using SAM Broadcaster and nothing shows in the Event Log...seems to be streaming without delay or interruption.
What's up with that, anyone knows?

![Image3](https://user-images.githubusercontent.com/66107794/95431335-01915200-091b-11eb-9581-4f9d0950735c.jpg)

**Comment by btoplak** [comment]
Hi @SpeedyCharly ,

that icons mark how many listeners have joined the stream or left the stream.  You can see that in the second column, where count of listeners of the track is listed.

Regarding your issues with stream player, I'd say it's probably related to some network issues. Try to compare playing in parallel on a different internet connection.
I hope that helps!
