### ISSUE TITLE
Manage media via sFTP

### ISSUE THREAD

**Issue by bebjakub** [AzuraCast/AzuraCast#325]
Hello, 
Thanx for your great app!
I'm just starting using your app and I would like to manage audio files via sftp (I have over 4000 tracks)...

Is it possible? Or I have to use your Media Manager only...

Thank you!

**Comment by voipworld** [comment]
hello,
yes, you can manage it 100% with any file transfer protocol you want
i upload mine using sftp and it get auto processed
all you have to do is to locate the media folder of your station
if you use normal install that should be easyer
but if you use the DOCKER install (recomanded), you need to locate it
with some very long path and create a synlink to it in a short path,
mine is /opt/station_name
work 100%, thank to our dear developer..........

**Comment by SlvrEagle23** [comment]
@bebjakub You can upload files in bulk by following the instructions listed here: https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#access-files-via-sftp-docker-installations

We get this question a lot, so to make it easier for folks, I've updated the media manager to show a little informational box at the top of the page for Docker users with a direct link to those instructions.

**Comment by bebjakub** [comment]
Instance is running with Docker. I used your script: 

`docker run --rm \
    -v azuracast_station_data:/home/azuracast/stations \
    -p 2222:22 atmoz/sftp:alpine \
    azuracast:azuracast:::stations`

But I got just empty stations folder, although I had uploaded files via Media Manager. So I created station_name folder and uploaded mp3 files in two folders. I waited for few minutes, but nothing changed.

What I'm doing wrong? thank you!
