### ISSUE TITLE
 Azura does not install on any version of ubuntu, help.

### ISSUE THREAD

**Issue by maikocosta** [AzuraCast/AzuraCast#3250]
It always happens

root@c2:~# mkdir -p /var/azuracast
root@c2:~# cd /var/azuracast
root@c2:/var/azuracast# curl -fsSL https://raw.githubusercontent.com/AzuraCast/A                                                                                                                                                             zuraCast/master/docker.sh > docker.sh
root@c2:/var/azuracast# chmod a+x docker.sh
root@c2:/var/azuracast# ./docker.sh install
Docker does not appear to be installed. Install Docker now? [Y/n] Y
# Executing docker install script, commit: 26ff363bcf3b3f5a00498ac43694bf1c7d9ce16c
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ [ -n  ]
+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
+ sh -c docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
Docker Compose does not appear to be installed. Install Docker Compose now? [Y/n] Y
Writing default .env file...
Creating default AzuraCast settings file...
Retrieving default docker-compose.yml file...
Prefer stable release versions of AzuraCast? [y/N] Y
Customize AzuraCast ports? [y/N]
Set up LetsEncrypt? [y/N]
WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
Pulling mariadb                 ... done
Pulling redis                   ... done
Pulling stations                ... done
Pulling web                     ... done
Pulling nginx_proxy             ... done
Pulling nginx_proxy_letsencrypt ... done
WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
Creating network "azuracast_backend" with driver "bridge"
Creating network "azuracast_frontend" with driver "bridge"
Creating volume "azuracast_nginx_proxy_vhosts" with default driver
Creating volume "azuracast_db_data" with default driver
Creating volume "azuracast_letsencrypt" with default driver
Creating volume "azuracast_letsencrypt_html" with default driver
Creating volume "azuracast_shoutcast2_install" with default driver
Creating volume "azuracast_geolite_install" with default driver
Creating volume "azuracast_sftpgo_data" with default driver
Creating volume "azuracast_station_data" with default driver
Creating volume "azuracast_www_vendor" with default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_redis_data" with default driver
Creating volume "azuracast_backups" with default driver
Creating azuracast_redis_1   ... done
Creating azuracast_mariadb_1 ... done
Creating azuracast_stations  ... done
2020/10/08 15:41:18 Waiting for: tcp://mariadb:3306
2020/10/08 15:41:18 Waiting for: tcp://influxdb:8086
2020/10/08 15:41:18 Waiting for: tcp://redis:6379
2020/10/08 15:41:18 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/10/08 15:41:18 Connected to tcp://redis:6379
2020/10/08 15:41:18 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:19 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/10/08 15:41:19 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:20 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/10/08 15:41:20 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:21 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/10/08 15:41:21 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:22 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/10/08 15:41:22 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:23 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/10/08 15:41:23 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:24 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/10/08 15:41:24 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:25 Problem with dial: dial tcp 172.18.0.3:3306: connect: connection refused. Sleeping 1s
2020/10/08 15:41:25 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:26 Connected to tcp://mariadb:3306
2020/10/08 15:41:26 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:27 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:28 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:29 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:30 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:31 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:32 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:33 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:34 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:35 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:36 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:37 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:38 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:39 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:40 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:41 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:42 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:43 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:44 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:45 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:46 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:47 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:48 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:49 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:50 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:51 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:52 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:53 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:54 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:55 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:56 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:57 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:58 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:59 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:42:00 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:42:01 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:42:02 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:41:26 Connected to tcp://mariadb:3306
2020/10/08 15:41:26 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:42:03 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:42:04 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:42:05 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
2020/10/08 15:42:06 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: no such host. Sleeping 1s
^CWARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
azuracast_mariadb_1 is up-to-date
azuracast_redis_1 is up-to-date
azuracast_stations is up-to-date
Creating azuracast_web ... done
Creating azuracast_nginx_proxy_1 ... done
Creating azuracast_nginx_proxy_letsencrypt_1 ... done
root@c2:/var/azuracast#

**Comment by SC2Mitch** [comment]
It's strange that it's trying to find `influxdb` when that was completely removed in the last commit, I'll have a look.

**Comment by Vaalyn** [comment]
> Prefer stable release versions of AzuraCast? [y/N] Y

@SC2Mitch When installing the last stable release `influxdb` will still be installed since we removed it after that release.

There have been a few updates to the `docker.sh` script to pull stuff for the stable release from the `stable` branch. I'd recommend updating the `docker.sh` and then try running it again.

**Comment by SC2Mitch** [comment]
Very good point; missed that part!

**Comment by WesllenMatias** [comment]
I'm having the same problem...

**Comment by SlvrEagle23** [comment]
@WesllenMatias This should be fixed as long as you make sure to update the latest `docker.sh` script during your update process, i.e.:

```bash
cd /var/azuracast
./docker.sh update-self
./docker.sh update
```

**Comment by AngeliqueDawnbringer** [comment]
Please note that the influx system still remains with the current scripts. To get rid of this issue 
WARNING: Found orphan containers (azuracast_influxdb_1) 

running 
docker-compose up --remove-orphans
did the trick.

After that run docker update once more, and all the migration scripts are running.

@SlvrEagle23: Mind adding this to the up and down script so it gets removed automatically when you remove or add a component? This will ensure, that when you are updating a clean version, you don't run in such problems.

**Comment by maikocosta** [comment]
This process solved the problem.

cd /var/azuracast
./docker.sh update-self
./docker.sh update

Thank you.

**Comment by SlvrEagle23** [comment]
@AngeliqueDawnbringer We actually specifically run `docker-compose down` with the _old_ version of the Docker Compose file to avoid orphans being left detached, but we can probably add that as a just-in-case measure for people who wind up out of date one way or another.

Since this issue is fixed, closing this ticket for now.

**Comment by ttodua** [comment]
Today, i've been installing new (fresh) install on fresh ubuntu, and it still mentions fluxdb:   https://i.imgur.com/xr7LGOf.png

**Comment by Vaalyn** [comment]
@ttodua When installing the 0.10.4 stable version this is totally normal since that version was released before we removed influxdb.
