### ISSUE TITLE
files in mounted folder is not processed

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#3252]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.4 Stable 

**Host Operating System**
Debian 10.3

**Describe the bug**
After updating to the latest stable version the files that have been downloaded in mounting directories are not recognized and appear with the message "file not processed".

I'm trying to run the sync task by hand, and it doesn't recognize it either.

**Comment by themadcap1976** [comment]
If I try to move/delete a file, I get "file not processed"
AzuraCast • v0.10.4 Stable • Docker • PHP 7.4 

![Screen Shot 2020-10-08 at 2 56 12 PM](https://user-images.githubusercontent.com/32073620/95501605-8fe6f180-0976-11eb-9379-e79bb67b7459.png)

**Comment by btoplak** [comment]
I am experiencing the same issue here.

**Comment by fidegr** [comment]
I tell you an example of the failure.

A couple of hours ago a new episode of a podcast was downloaded via podget and it has been successfully saved in its folder.

The file still appears raw in Azuracast, even though I have manually run the sync media task.

![image](https://user-images.githubusercontent.com/16152034/95574298-047c6780-0a2d-11eb-8d81-e6b7fe32a669.png)

This is the message I find after executing the task:

![image](https://user-images.githubusercontent.com/16152034/95574385-283fad80-0a2d-11eb-8f6f-87dd7e3cfffb.png)

Any idea where the problem may be?

**Comment by SlvrEagle23** [comment]
@btoplak @fidegr I'm uploading files locally via SFTP and it seems to not be having any problems, but you can force manual reprocessing of your media by running:

```bash
cd /var/azuracast
./docker.sh cli azuracast:media:reprocess
```

**Comment by themadcap1976** [comment]
Forced the reprocess and still experiencing the issue.

**Comment by themadcap1976** [comment]
I'm also getting this...
![Screen Shot 2020-10-13 at 8 35 43 AM](https://user-images.githubusercontent.com/32073620/95861392-5d9b1280-0d2f-11eb-81cf-9c070140ba17.png)

**Comment by fidegr** [comment]
Given the impossibility of playing the podcasts that are downloaded to the shared folder, we have returned to version 10.3 of azuracast and everything works correctly again. We will wait to update until the problem is solved.

**Comment by themadcap1976** [comment]
How can I revert?

**Comment by SlvrEagle23** [comment]
@fidegr @themadcap1976 It may be worthwhile for you to look into switching to the Rolling Release channel for a moment, as I'm not able to reproduce this issue as of our current rolling release build.

Once we've stabilized our most recent changes, we can plan for an 0.10.5 release that will include those fixes.

**Comment by themadcap1976** [comment]
How do I switch to a rolling release? I really don't want to rebuild the station. I'm still having the issue.

**Comment by Vaalyn** [comment]
First run `./docker.sh update-self` to make sure you have the newest script then `./docker.sh setup-release()`, tell it to not use the stable version, then run `./docker.sh update`
