### ISSUE TITLE
"Interrupt other songs to play at scheduled time" abruptly cuts playback after cca 50 sec

### ISSUE THREAD

**Issue by btoplak** [AzuraCast/AzuraCast#3254]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.4 Stable • Docker • PHP 7.4

**Host Operating System**
Debian 10.6

**Describe the bug**
A playlist configured with Advanced Manual AutoDJ scheduling option **"Interrupt other songs to play at scheduled time"** is not being played until the end. The playback of the song from the interrupting playlist is simple being stopped after about 50-55 seconds, and the interrupted main song continues where it stopped.

**To Reproduce**
1. Create a new playlist = Type: Once per hour; Song-Based; Shuffled
2. On "Advanced" tab choose "Interrupt other songs to play at scheduled time"
3. Add one or more songs, at least 1 minute long
4. When the playlist interrupts the currently running song, the songs from the playlist will abruptly stop after about 50 sec.

**Expected behavior**
Expected is that all songs/jingles on the playlist play until the end. 
Only thereafter should the interrupted song resume playback. Or even better, start with a new song. (not sure which variant is expected behaviour).

**Additional context**
That behaviour wasn't observed before v.0.10.4 release and the work on AutoDJ and the scheduler.

**Comment by Kaiserhm** [comment]
dear team i would be happy if you would solve this problem soon

**Comment by Kaiserhm** [comment]
what's new ?
