### ISSUE TITLE
Can't get 'Rolling Release' after reverting to 'Stable Releases'

### ISSUE THREAD

**Issue by spenmath** [AzuraCast/AzuraCast#3259]
**Using Docker installation method**
Yes

**AzuraCast version**
0.10.4

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
I updated our server to find that it was on 'Rolling Updates', as we're a live station I decided that wasn't the best option so [following instructions](https://www.azuracast.com/administration/system/updating.html#switching-update-release-preference) I opted for stable releases, but now I've got a station that works but the server admin doesn't show any song data. 

Have commented out the added code to azuracast.env to try and get rolling release back but can't seem to get the latest code which should fix issues I've got based on other bug reports.

**Screenshots**
![image](https://user-images.githubusercontent.com/33485275/95637221-1be93e00-0a89-11eb-8e27-d8fb5c0bb55c.png)

**Comment by spenmath** [comment]
Have fixed this by running 'docker.sh setup-release', perhaps an update to docs needed?

**Comment by SlvrEagle23** [comment]
@spenmath Turns out our docs don't discuss the intricacies of the release channel model at all, so I created a new page explaining it and the update process:

https://www.azuracast.com/administration/system/release-channels.html
