### ISSUE TITLE
Fatal error after upgrade from v0.10.2 to v0.10.4

### ISSUE THREAD

**Issue by aripisprecer** [AzuraCast/AzuraCast#3264]
**Using Docker installation method**
Yes/

**AzuraCast version**
v0.10.4

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
I have upgraded from v0.10.2 to v0.10.4 and i cannot access the web interface anymore.

**To Reproduce**

cd /var/azuracast
./docker.sh update-self
./docker.sh update

**Expected behavior**
The web interface should work correctly after upgrade

**Relevant Logs**
`Fatal error: Uncaught Error: Class 'App\Collection' not found in /var/azuracast/www/src/Settings.php:6 Stack trace: #0 /var/azuracast/www/vendor/composer/ClassLoader.php(444): include() #1 /var/azuracast/www/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile() #2 [internal function]: Composer\Autoload\ClassLoader->loadClass() #3 /var/azuracast/www/web/index.php(8): spl_autoload_call() #4 {main} thrown in /var/azuracast/www/src/Settings.php on line 6`
`

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@aripisprecer This suggests you have either outdated code in your Docker volume, or you're overriding the AzuraCast code in a way that is no longer supported by the newer codebase.

When you're prompted to update, make sure to answer "Y" when asked to update `docker-compose.yml` if it's newer than your version (if you have any custom changes you've made to it, you can usually move those to a separate `docker-compose.override.yml` file that isn't changed by our updates).

**Comment by aripisprecer** [comment]
@SlvrEagle23 I did updated the docker-compose.yml file but i've got the same error.
I have to mention that i did not changed anything to the source code

**Comment by SlvrEagle23** [comment]
@aripisprecer Is there anything customized about your installation? Do you have a `docker-compose.override.yml` file on your host?

When you run the update script, do you run into any errors during the update?

It shouldn't be possible to get into the state your code is in, so we need some additional information to help diagnose things.

**Comment by aripisprecer** [comment]
@SlvrEagle23 

Please excuse my late replay.

I have managed to update to the last version. The only difference from the last time is stat I've deleted the docker-compose.yml file (backed it up before deleting to docker-compose.override.yml).
It warned me that the file does not exist but the update process finished without errors and the docker-compose was recreated.

I've started azuracaste using the backup file, not using the new docker-compose.yml (before starting i did a diff to see the diffrences between the two files and the only difference was the ports i have choosen for streaming):

`docker-compose -f docker-compose.override.yml up -d`

It seems that the update script was not able to overwrite (I have answered with Y to the overwrite message) the docker-compose.yml altought i ran the command as root user.

Thank you for your support and for this great software!

**Comment by Vaalyn** [comment]
Closing as resolved
