### ISSUE TITLE
Liquidsoap vs AutoDJ plans 

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#3265]
Can you remind me where I can find the information regarding the Liquidsoap version in the current Azuracast release? Specifically, I'd like to know if Azuracast 0.10.4 has updated to Liquidsoap 1.4.3.

Another more general question is how you guys at Azuracast think about your AutoDJ feature and Liquidsoap. My simplified understanding of the separation is that "AutoDJ tells Liquidsoap what to play" while (as a fallback) "Liquidsoap tells Azuracast what to play". Do you in the longterm plan to replace AutoDJ for Liquidsoap completely (at least for the main show programming features of Azuracast)?

I'm asking because our show programming is currently completely based on custom Liquidsoap playlists and we don't use Azuracast's AutoDJ at all. We're not super happy with Liquidsoap though, mainly because of reliability (not always reliable) and the ease of programming (not always easy), so we would be interested in switching to an easier-to-use solution. 

Looking forward to reading your thoughts on this.

**Comment by bjarn** [comment]
The Liquidsoap version indeed is the latest (1.4.3 at time of writing). You can see it here: https://github.com/AzuraCast/docker-azuracast-radio/blob/master/Dockerfile

**Comment by SlvrEagle23** [comment]
> Can you remind me where I can find the information regarding the Liquidsoap version in the current Azuracast release? Specifically, I'd like to know if Azuracast 0.10.4 has updated to Liquidsoap 1.4.3.
> 
> Another more general question is how you guys at Azuracast think about your AutoDJ feature and Liquidsoap. My simplified understanding of the separation is that "AutoDJ tells Liquidsoap what to play" while (as a fallback) "Liquidsoap tells Azuracast what to play". Do you in the longterm plan to replace AutoDJ for Liquidsoap completely (at least for the main show programming features of Azuracast)?
> 
> I'm asking because our show programming is currently completely based on custom Liquidsoap playlists and we don't use Azuracast's AutoDJ at all. We're not super happy with Liquidsoap though, mainly because of reliability (not always reliable) and the ease of programming (not always easy), so we would be interested in switching to an easier-to-use solution.
> 
> Looking forward to reading your thoughts on this.

The first question was already answered (we're on LS 1.4.3), but to answer your other one about our long-term goals:

It's complicated. Our original ideal goal was to let Liquidsoap handle it all itself, but there are things it simply can't do at the moment (namely updating playlist settings without a reload and keeping track of the next playing song or any sort of upcoming queue), so we've kept working on refining our own AutoDJ to do as much as LS can do.

Nowadays, well, I think we'd be better suited by continuing to polish our own AutoDJ and make it as feature-rich and reliable as we can. Being dependent on a piece of third-party software for something as essential to the software as the AutoDJ puts us in a hard position with regard to bug fixes, implementing new features in a timely fashion, etc., and it also ruins our whole idea of modularity that was built into our support for multiple broadcasting frontends (but that we've never expanded upon for AutoDJ backends, though we definitely could and have looked into ices-cc).

**Comment by gammaw** [comment]
Wow! Thanks a lot for sharing this! I totally agree with you points. Looking forward to checking the new 0.10.4 release and seeing if and how we can move towards using AutoDJ. 

Another question I thought of is how you plan to deal with "audio manipulation" such as fading out/in. Do you plan to continue to rely on Liquidsoap for that?
