### ISSUE TITLE
Scheduled playlist not playing on time!

### ISSUE THREAD

**Issue by jovemac** [AzuraCast/AzuraCast#3267]
Dear Azura cast!

I've installed and configured Azuracast in Digital Ocean.  Tried scheduling a playlist which is not playing on time.  It should countdown and finally it says its already started. But the default playlist keeps on playing. It could be great if you can help me to fix this issue.

![1](https://user-images.githubusercontent.com/13369591/95684107-e40b0380-0c0c-11eb-9097-5e0680cdde70.jpg)
![2](https://user-images.githubusercontent.com/13369591/95684109-e5d4c700-0c0c-11eb-902d-a03fcd8d74c6.jpg)
![3](https://user-images.githubusercontent.com/13369591/95684110-e66d5d80-0c0c-11eb-89d8-a7abd10483a2.jpg)
![4](https://user-images.githubusercontent.com/13369591/95684111-e705f400-0c0c-11eb-8b0c-70caadde3eac.jpg)
![5](https://user-images.githubusercontent.com/13369591/95684112-e705f400-0c0c-11eb-8848-4b64a0b341de.jpg)
![6](https://user-images.githubusercontent.com/13369591/95684114-e79e8a80-0c0c-11eb-845c-6f72a61b0f3c.jpg)
![7](https://user-images.githubusercontent.com/13369591/95684115-e8372100-0c0c-11eb-98de-9d2588e1ba8c.jpg)
![8](https://user-images.githubusercontent.com/13369591/95684262-1a954e00-0c0e-11eb-9221-151c5e72d6f8.jpg)
![9](https://user-images.githubusercontent.com/13369591/95684263-1bc67b00-0c0e-11eb-8175-c1cd3e6c0ecc.jpg)
![10](https://user-images.githubusercontent.com/13369591/95684264-1c5f1180-0c0e-11eb-8bf6-0f2411c02424.jpg)

Please let me know if you need any other details in this regard.

**Comment by s7ntax** [comment]
I have had this issue since the start of using Azuracast and never been able to solve the problem. Updated many times, still the same issue. Ubuntu 20.04 Docker.
