### ISSUE TITLE
Cleanup of unused Docker images not working correctly

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#3269]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.4 Rolling Release #ca38bea (2020-09-22 20:47)

**Host Operating System**
Debian 9

**Describe the bug**
The command `docker rmi "$(docker images | grep "none" | awk '/ / { print $3 }')" 2>/dev/null` at the end of the update script seems to have an issue on my server where it retrieves the list of unused images, then tries to remove them and fails because the first one on that list leads to the error `Error: No such image: 0e5b4003ec73`.

I'm currently investigating why that might be since the `docker images` command lists that image it's rather strange to see the `docker rmi` command saying that the image does not exist.

**To Reproduce**
Currently no idea if this is something that can be reproduced.

Would like some input from other users if they can see the same error when they execute `docker rmi "$(docker images | grep "none" | awk '/ / { print $3 }')"` manually (without the `2>/dev/null` at the end)

**Expected behavior**
Unused images should be correctly cleaned up.

**Relevant Logs**
See screenshots.

**Screenshots**
![image](https://user-images.githubusercontent.com/13745863/95752696-b374a980-0ca0-11eb-81ac-c0158766d22b.png)

![image](https://user-images.githubusercontent.com/13745863/95752788-dd2dd080-0ca0-11eb-9c79-76d74e464476.png)

**Comment by SlvrEagle23** [comment]
@Vaalyn We actually built that command out back before `docker system prune` was widespread...I'd be completely okay with us running something like that instead, as it would likely be more effective and "future-proof".

**Comment by Vaalyn** [comment]
The cleanup is now running successfully.

Good job and thank you 👍
