### ISSUE TITLE
I can't move music files to other folders

### ISSUE THREAD

**Issue by habib1228** [AzuraCast/AzuraCast#3270]
AzuraCast version
Rolling Release #2e6cfee (2020-10-12 22:20)

reproducing: https://cloud.disroot.org/s/8TYxbFeQBSwRtRn

**Comment by SlvrEagle23** [comment]
@habib1228 Thank you for the report and the video. This should be fixed as of the latest update; please update your installation when convenient and let me know if the issue is resolved.

**Comment by habib1228** [comment]
@SlvrEagle23 Perfect! I got it!
