### ISSUE TITLE
Modify the aesthetics

### ISSUE THREAD

**Issue by enigmathion** [AzuraCast/AzuraCast#3274]
Good morning, I need to make an inquiry. Is it possible to modify the aesthetics of Azuracast installed from docker? Thank you very much!

**Comment by Madpeterz** [comment]
You can make some changes via admin/branding
good for changing the backgrounds and tweaking some colors

**Comment by Vaalyn** [comment]
In `Administration` go to `Custom Branding`, there you can use the `Custom CSS for Public Pages` and `Custom JS for Public Pages` text fields to write your own CSS styles and JS scripts for all public pages and for the internal pages you can use the `Custom CSS for Internal Pages`.
