### ISSUE TITLE
Album art not shown (sometimes)

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#3275]
We noticed an unexpected behaviour (we didn't do any apparent change to our setup, update etc.): although a (non-default) album art is configured for a file, it won't be displayed when playing it. The nowplaying API also reports the default album art (in the JSON response). It happens sporadically and so far we could not recognise a pattern when it happens. 

Also, it may be related, sometimes when we try to change metadata of a file (e.g., song title, artist), it doesn't take effect while the file is being played (although it worked on other occasions and we were very happy to see how agile Azuracast is able to react to changes of the media). 

Any idea? 

Our server is running Azuracast v0.10.3, #9811fbb (2020-06-22 4:38).

**Comment by SlvrEagle23** [comment]
@gammaw Usually if you see a track in the API that has no rich metadata (i.e. album art, etc) this can happen if Liquidsoap is playing a track where there's no way for it to tie the track to the media entry in AzuraCast (and thus pull the rich metadata).

I'm not sure that it would be related to changing a file's metadata _as it's playing_, which is definitely an edge case where it likely depends on whether the encoder in Liquidsoap detects the change on-the-fly.

**Comment by gammaw** [comment]
@SlvrEagle23 thanks. I'm not sure I fully get it. It's Azuracast who sends the rich metadata (via the nowplaying API). If I change the file's metadata in Azuracast, why would Azuracast not know that the data have been changed? The tracking across LS and AZ seemed to be fine in this particular case.
