### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by mosplaceradio** [AzuraCast/AzuraCast#3277]
Hello,

Can someone please explain to me why some people can make requests, while others just see a blank page?
www.bostonsbestradio.com

**Using Docker installation method**

**AzuraCast version**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by radiobellissima** [comment]
It could be the browser's fault. Your site does not allow a secure connection so it may be blocked.
![Test](https://user-images.githubusercontent.com/57127248/96032106-81a94180-0e5e-11eb-8cd7-389c0fd1d982.png)

**Comment by mosplaceradio** [comment]
That's what I am thinking, but that url is generated from Azuracast itself? not sure how to fix it.. also, is there a max number of songs that you can have available for requests? It seemed I could add no more requests after 4,800

**Comment by radiobellissima** [comment]
For the number of songs I would not know how to answer you I do not use that function. To solve the SSL problem you need to have a registered domain, maybe yours is fine, see if your hosting is able to provide a certificate maybe free. After that find the guide on the azura site for installation.
[https://www.azuracast.com/extending/letsencrypt.html#important-considerations](url)

**Comment by SlvrEagle23** [comment]
@mosplaceradio We recently found and fixed a bug with the requests modal dialog box not appearing correctly; you may need to update your installation to get the fixed version.

**Comment by mosplaceradio** [comment]
Looks like I’m 219 updates behind the current! I am not using the docker version, any idea how to update?   Tune in and Tune Out! Ernie Houleinfo@mosplaceradio.comwww.mosplaceradio.com(978) 833-2164 From: SlvrEagle23Sent: Wednesday, October 14, 2020 3:59 PMTo: AzuraCast/AzuraCastCc: mosplaceradio; MentionSubject: Re: [AzuraCast/AzuraCast] Requests (#3277) @mosplaceradio We recently found and fixed a bug with the requests modal dialog box not appearing correctly; you may need to update your installation to get the fixed version.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by SpeedyCharly** [comment]
The amount of songs you may place in the list are only limited by the storage space available on the server - your hard drive may be full

**Comment by SpeedyCharly** [comment]
As for the listing not showing up properly - it is most likely a navigator issue... most navigators now actively block mixed content sites and will not allow http content to appear on https sites. Short of getting a SSL cetificate for your server you can instruct your viewers to click on the 'Not secured' thingamajig, shown above, then select Sute preferences and at the bottom of the resulting page set the 'Unsecured content' switch to allow...
