### ISSUE TITLE
Remote URL Playlist

### ISSUE THREAD

**Issue by torontocast** [AzuraCast/AzuraCast#3278]
It appears that Remote URL Playlists is not working correctly.  I am trying to play https://www.voanews.com/mp3/voa/english/nnow/NNOW_HEADLINES.mp3 once an hour at :55 without success.
![image](https://user-images.githubusercontent.com/72706468/96021726-d7112e80-0e1d-11eb-8124-38a5e5709fb9.png)
![image](https://user-images.githubusercontent.com/72706468/96021948-28b9b900-0e1e-11eb-97c5-68de896784b9.png)

The file is never played. Am I configuring something incorrectly?

**Comment by themadcap1976** [comment]
I'm having the same issue, I've tried several combinations, using https/http and it doesn't work.

**Comment by silvaalex2021** [comment]
I have a similar problem here. The remote MP3 file will eventually play at the right time, but it will play back and forth, as well as some parts that will play at a very fast speed. unfortunately I am not the server administrator and I have no access to the logs, I am just guessing what could be the problem.

Playlist setup:

Type: once per X minutes (90 in my case)
URL: https://audio.climatempo.com.br/radios/br.mp3
URL type: direct stream url
buffer: 30
advanced options: no

any help will be appreciated!
