### ISSUE TITLE
Question: Setting up jingles

### ISSUE THREAD

**Issue by IdkWhosThis** [AzuraCast/AzuraCast#3279]
I need some help with setting up jingles correctly since I seem like not doing it right.
When I mark a playlist as Jingle mode, set "Once per x Songs" and set it to play after 1 song, it simply doesn't play. It plays it only at the beginning of the station restart and then never again.
Can anyone please help me with setting up jingles correctly?

**Comment by SpeedyCharly** [comment]
Can you supply us with a screenshot of your playlist settings? As is we don't have enough info to guess at what is wrong and offer solutions

**Comment by dubloid** [comment]
> I need some help with setting up jingles correctly since I seem like not doing it right.
> When I mark a playlist as Jingle mode, set "Once per x Songs" and set it to play after 1 song, it simply doesn't play. It plays it only at the beginning of the station restart and then never again.
> Can anyone please help me with setting up jingles correctly?

Hello!
You need to prioritize the jingle playlist above the priority of the main playlist.

Your question has already been discussed earlier.

**Comment by SpeedyCharly** [comment]
> > I need some help with setting up jingles correctly since I seem like not doing it right.
> > When I mark a playlist as Jingle mode, set "Once per x Songs" and set it to play after 1 song, it simply doesn't play. It plays it only at the beginning of the station restart and then never again.
> > Can anyone please help me with setting up jingles correctly?
> 
> Hello!
> You need to prioritize the jingle playlist above the priority of the main playlist.
> 
> Your question has already been discussed earlier.

Sorry, but that seems nonsense to me - my 2 main playlists are set at 15 while the 5 jingle playlist are set at 3 and the whole shebang works like a charm... 

Could you be speaking of older versions as I am on 10.3?

**Comment by bjarn** [comment]
Have you selected the 'Only play one track at scheduled time' option? This might cause issues with it only playing once until the service is restarted.
![CleanShot 2020-10-21 at 08 58 38](https://user-images.githubusercontent.com/14638441/96684332-b7c55480-137b-11eb-9da2-97cd905dda77.png)
