### ISSUE TITLE
Upcoming Song Queue empty

### ISSUE THREAD

**Issue by pixel-paul** [AzuraCast/AzuraCast#3284]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #089775c (2020-10-16 9:53)

**Host Operating System**
CentOS 7

**Describe the bug**
Upcoming song queue is empty. Dashboard does show correct playlist entries and next song

**To Reproduce**
Click on upcoming song queue

**Expected behavior**
Song queue to appear

**Relevant Logs**
Inspecting the page the response is a 500 error:

`message: Return value of App\Controller\Api\Stations\QueueController::viewRecord() must be an instance of App\Entity\Api\QueuedSong, instance of App\Entity\Api\StationQueue returned`

**Screenshots**
Upcoming Song Queue screen:
![Screenshot_2020-10-16 Upcoming Song Queue](https://user-images.githubusercontent.com/389303/96287182-70387480-0fd9-11eb-8fff-6d0041e584f4.png)
Dashboard:
![Screenshot_2020-10-16 Profile](https://user-images.githubusercontent.com/389303/96287299-a1b14000-0fd9-11eb-8504-d93bc595477e.png)

**Additional context**

**Comment by SlvrEagle23** [comment]
@pixel-paul The latest commit from @Vaalyn fixes this issue and has been merged into the main repository.

**Comment by pixel-paul** [comment]
Many thanks @Vaalyn !
