### ISSUE TITLE
Bug page streamer / dj

### ISSUE THREAD

**Issue by fast97** [AzuraCast/AzuraCast#3285]
Hello, the streamer dj account creation page does not work with the last update. page error
thank you

**Comment by Vaalyn** [comment]
I can not reproduce this on the demo installation nor my local dev environment. The DJ account page is loading up fine, I can successfully create new accounts, I can edit them and the list is also loading.

Please fill out the bug report template to provide us with all the information that we need to diagnose this. Especially include all error messages that you see in when opening that page, JavaScript errors from your browsers console and logs.

**Comment by fast97** [comment]
I am on a new installation of new server can be on my side that it does not go. I review my install. Can you tell me if it is still possible for azuracast files to be placed like this /var/ lib/docker/volumes/azuracast_www_data/_data /
thank you

**Comment by fast97** [comment]
after re-installing azuracast I confirm that the Rolling Release version # 089775c of azuracast that my streamer/dj page is in error. the stable version and the Rolling Release version # fb4f7de
System ubuntu (20.04_LTS-server) (64BITS)
Thank you

**Comment by Vaalyn** [comment]
Please provide us with the debug information that we ask from you (see the second paragraph of my last message).

I can not debug something that I can‘t reproduce and just saying „there is an error“ without actually posting that error or any details about it is not really helpful.

**Comment by fast97** [comment]
console google chrome :
DevTools failed to load SourceMap: Could not load content for https://station.streamantille.com/static/dist/lib/bootstrap/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by fast97** [comment]
Resolved with update : Rolling Release #97293da 
Thanks
