### ISSUE TITLE
Installer does not test if mariaDB conf exists

### ISSUE THREAD

**Issue by replayfactory** [AzuraCast/AzuraCast#329]
Hi SlvrEagle23 :-)
 
Looks like your ansible role [azuracast-db-install] does not check if root .my.cnf exists.

` - name: Add empty root .my.cnf (if none exists)`
`   become: true`
`   template: src=root_empty_my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600`

should be

` - name: Add empty root .my.cnf (if none exists)`
`   become: true`
`   template: src=root_empty_my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600 force=no`

Cheers

**Comment by SlvrEagle23** [comment]
@replayfactory Good catch! Updated :)
