### ISSUE TITLE
Nginx failed

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#3295]
During the update (Rolling version), I get this error and the station is offline:

[OK] AzuraCast is now updated to the latest version!

azuracast_redis_1 is up-to-date
azuracast_stations is up-to-date
azuracast_mariadb_1 is up-to-date
Creating azuracast_web ... done
Creating azuracast_nginx_proxy_1 ...
Creating azuracast_nginx_proxy_1 ... error

ERROR: for azuracast_nginx_proxy_1  Cannot start service nginx_proxy: driver fai                                                                         led programming external connectivity on endpoint azuracast_nginx_proxy_1 (76d44                                                                            a924004d1d6bd628cee203bdf3a488386ae0bbbad570a60028b12e0a35f): Error starting use                                                                            rland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for nginx_proxy  Cannot start service nginx_proxy: driver failed programm                                                                            ing external connectivity on endpoint azuracast_nginx_proxy_1 (76d44a924004d1d6b                                                                            d628cee203bdf3a488386ae0bbbad570a60028b12e0a35f): Error starting userland proxy:                                                                             listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by Vaalyn** [comment]
The error `listen tcp 0.0.0.0:80: bind: address already in use` indicates that some other software on the server is already listening on that port. In most cases that is an Apache2 or NGINX server on the host. You need to check if you have one of those running and stop/remove it from the server.

**Comment by stardevelop** [comment]
I removed Nginx on host machine and updated AzuraCast and the issue resolved. Thanks.

**Comment by Keepshango** [comment]
Hello,

I am also **trying to get rid of the same error**, but I do need apache2 for other webapps on my server !

**I then changed ports 80 and 443 that apache2 was listening to by default**, with new ports that I previously allowed from my Cpanel (ISP config). **But the error remains !** 

Shall I uninstall and re-install AzuraCast for such these changes to be logged, and to get the error solved ?

Regards
