### ISSUE TITLE
Custom URL Streaming

### ISSUE THREAD

**Issue by xxdjbobbyxx** [AzuraCast/AzuraCast#3302]
Hello,

How do I enable Custom URL Streaming for a station? So for example live.example.com would be the .mp3 of that actual radio station.

**Comment by adoboligh1** [comment]
> Hello,
> 
> How do I enable Custom URL Streaming for a station? So for example live.example.com would be the .mp3 of that actual radio station.

This Actually Has A weird way, youll need to remove azuracast from port 80 and install nginx on port 80 and use a reverse proxy.

example below




server {
        listen 80;
        listen [::]:80;
  server_name  edificeradio.ghanacloud.live;
        access_log /var/log/nginx/reverse-access.log;
        error_log /var/log/nginx/reverse-error.log;
        location / {
                    proxy_pass http://localhost:8160/radio.mp3;
}
}

**Comment by xxdjbobbyxx** [comment]
It worked!

Thanks for your help!

**Comment by adoboligh1** [comment]
Welcome
