### ISSUE TITLE
Song Request API

### ISSUE THREAD

**Issue by HuckinB** [AzuraCast/AzuraCast#3303]
Hi there,

So I'm trying to make a custom song request feature for our Station. 
However when I do the post request to "/station/{station_id}/request/{request_id}"
(Station ID being the station and request ID being the song_id) it returns
"The song ID you specified could not be found in the station."

I have also tried using the unique_id but that returns the same error.

What is the ID required for the post?

Regards
Brandon

[CC @KylePython]

**Comment by SlvrEagle23** [comment]
@HuckinB When submitting a request, the `request_id` should be the unique identifier for the `StationMedia` entity. You should see it in the "List Requestable Songs" API endpoint call (`GET /station/{id}/requests`) as the `request_id`.

**Comment by HuckinB** [comment]
Much appreciated, everything is working now.

Thanks for the quick response!

Regards
