### ISSUE TITLE
Song played twice in a row

### ISSUE THREAD

**Issue by bjarn** [AzuraCast/AzuraCast#3304]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #415c24c

**Host Operating System**
Ubuntu Server 18.04

**Describe the bug**
On a rare occasion, but at least once or twice a day (as far as I am aware), a song plays itself twice in a row. It is also visible in the 'Playing Next' section on the dashboard and in the Upcoming Song Queue.

However, Liquidsoap just plays it, no errors are logged. So I believe it might have something to do with the Auto DJ.

As of writing I don't have any logs available from the last time it happened. Will try my best to get some good ol' log entries.

**To Reproduce**
1. Create a playlist
2. Add some music
3. Wait? Not really sure, it happens at random times.

**Expected behavior**
Song should only play once and then go on to the next one, but it's played twice in a row instead.

**Relevant Logs**
Hopefully coming soon, none available as of writing.

**Screenshots**
Hopefully coming soon, none available as of writing.

**Device(s):**
 - Device: Macbook Pro
 - OS: MacOS
 - Browser: Chrome
 - Version: 86

**Comment by bjarn** [comment]
It just happened again, my feelings say it happens more often now:
![CleanShot 2020-10-22 at 09 32 49](https://user-images.githubusercontent.com/14638441/96839513-97fc6200-1449-11eb-9f56-6a5527673bb3.png)

These are some logs of the event, nothing special I believe:
```
2020/10/22 09:24:53 [lang:3] AzuraCast Raw Response: annotate:title="In Your Head",artist="Mohombi",duration="192.73",song_id="8a441c0cc4ace26b8df1fe82a033dd69",media_id="4089",liq_amplify="-4.80dB",liq_cross_duration="0.30",liq_cue_in="0.00",liq_cue_out="192.70",playlist_id="37":/var/azuracast/stations/xxx/media/Muziek/mohombi_-_in_your_head.mp3
2020/10/22 09:24:53 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/xxx/media/Muziek/mohombi_-_in_your_head.mp3".
2020/10/22 09:25:29 [xxx_cue_next_song:3] Cueing out...
2020/10/22 09:25:29 [xxx_next_song:3] Prepared "/var/azuracast/stations/xxx/media/Jingles/2020/xxx - Non Stop/xxx - Nonstop_2.mp3" (RID 2).
2020/10/22 09:25:29 [cross_7980:3] Analysis: -35.544484dB / -16.681105dB (1.48s / 1.48s)
2020/10/22 09:25:29 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/10/22 09:25:29 [crossfade:3] cross duration: 1.5, after duration: 3.03
2020/10/22 09:25:29 [lang:3] AzuraCast Feedback Response: OK
2020/10/22 09:25:31 [xxx_next_song:3] Prepared "/var/azuracast/stations/xxx/media/Muziek/mohombi_-_in_your_head.mp3" (RID 6).
2020/10/22 09:25:31 [cross_7980:3] Analysis: -22.146964dB / -32.777504dB (0.99s / 1.01s)
2020/10/22 09:25:31 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/10/22 09:25:31 [crossfade:3] cross duration: 1.0, after duration: 192.73
2020/10/22 09:25:31 [lang:3] AzuraCast Feedback Response: OK
2020/10/22 09:28:04 [lang:3] AzuraCast Raw Response: annotate:title="Poison",artist="RITA ORA",duration="202.92",song_id="176e670a63c3e1a28ce40b4ce62aed27",media_id="814",liq_amplify="-5.70dB",liq_cross_duration="1.50",liq_fade_out="1.50",liq_cue_in="0.30",liq_cue_out="201.40",playlist_id="37":/var/azuracast/stations/xxx/media/Muziek/RITA ORA - Poison.mp3
2020/10/22 09:28:04 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/xxx/media/Muziek/RITA ORA - Poison.mp3".
2020/10/22 09:28:44 [xxx_cue_next_song:3] Cueing out...
2020/10/22 09:28:44 [xxx_next_song:3] Prepared "/var/azuracast/stations/xxx/media/Muziek/285 - RITA ORA - Poison.mp3" (RID 4).
2020/10/22 09:28:44 [xxx_cue_next_song:3] Cueing in...
2020/10/22 09:28:44 [cross_7980:3] Analysis: -18.122833dB / -47.511045dB (0.30s / 0.30s)
2020/10/22 09:28:44 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/10/22 09:28:44 [crossfade:3] cross duration: 0.3, after duration: 202.92
2020/10/22 09:28:44 [lang:3] AzuraCast Feedback Response: OK
2020/10/22 09:31:25 [lang:3] AzuraCast Raw Response: annotate:title="Poison",artist="RITA ORA",duration="202.92",song_id="176e670a63c3e1a28ce40b4ce62aed27",media_id="814",liq_amplify="-5.70dB",liq_cross_duration="1.50",liq_fade_out="1.50",liq_cue_in="0.30",liq_cue_out="201.40",playlist_id="37":/var/azuracast/stations/xxx/media/Muziek/RITA ORA - Poison.mp3
2020/10/22 09:31:25 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/xxx/media/Muziek/RITA ORA - Poison.mp3".
2020/10/22 09:32:03 [xxx_cue_next_song:3] Cueing out...
2020/10/22 09:32:03 [xxx_next_song:3] Prepared "/var/azuracast/stations/xxxx/media/Muziek/RITA ORA - Poison.mp3" (RID 3).
2020/10/22 09:32:03 [xxx_cue_next_song:3] Cueing in...
2020/10/22 09:32:03 [cross_7980:3] Analysis: -30.283013dB / -26.308381dB (1.50s / 1.50s)
2020/10/22 09:32:03 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/10/22 09:32:03 [crossfade:3] cross duration: 1.5, after duration: 202.92
2020/10/22 09:32:03 [lang:3] AzuraCast Feedback Response: OK
```

**Comment by SlvrEagle23** [comment]
@bjarn I'm assuming you have the "Prevent duplicate" setting enabled for that playlist? We left that as an opt-in setting for playlists since sometimes you _want_ duplicates played close to each other (i.e. station IDs, ads, or sequential playlists with duplicate entries).

**Comment by bjarn** [comment]
@SlvrEagle23 I indeed do have it enabled for this playlist. I however do not have it enabled for my imaging playlist. So ID's etc. are in a seperate playlist without the 'Prevent Duplicate' option enabled.

**Comment by DJMike67** [comment]
Hi @SlvrEagle23 and @bjarn 

I am experiencing this too. My host is on: Rolling Release #bc307d2 (2020-10-21 12:52) • Docker • PHP 7.4

I have 2 radio stations running Azuracast. One is being used for testing so here's the situation... I uploaded 2 short MP3 files (each around 20 seconds) and added both to a playlist (I only have 1 playlist). When I listen to the station I get something along these lines...

Song 1 plays
Song 1 plays
Song 2 plays
Song 1 plays
Song 2 plays
Song 2 plays
Song 1 plays
Song 2 plays
Song 1 plays
Song 2 plays
Song 1 plays
Song 1 plays
Song 1 plays
Song 2 plays
Song 2 plays
Song 1 plays
Song 2 plays

So as you can see sometimes it works, sometimes it doesn't. Sometimes it plays the same track twice in a row. Sometimes it plays the same track 3 times in a row. Sometimes it works as it should

It is the only playlist
It is General Rotation
It has a Weight of 3
Avoid Duplicate Artists/Titles is TICKED
Song Order is set to Sequential
None of the Advanced options are ticked

The Upcoming Song Queue shows the order correctly (ie song1, song2, song1, song2 etc) 

I have attached the Liquid Soap Log for you. I have only included the most recent 10 minutes to save you wading through a load of stuff. The 2 tracks to look for are : stuart_1.mp3 
[Liquid Soap Log.txt](https://github.com/AzuraCast/AzuraCast/files/5434316/Liquid.Soap.Log.txt)
and b196_ident.mp3

Many thanks

**Comment by DJMike67** [comment]
@SlvrEagle23 @bjarn I have replaced the 2 files with 2 other files and cannot now replicate this issue. Well actually that isn't true. I just spent 10 minutes listening to the output of the station and it was working as expected then suddenly it started doing the same song twice in a row

Updated log file attached


[Liquid Soap Log.txt](https://github.com/AzuraCast/AzuraCast/files/5434352/Liquid.Soap.Log.txt)

**Comment by DJMike67** [comment]
@SlvrEagle23 @bjarn Further update. I just went out for a 30 minute walk and listened whilst I was out. I cannot now reproduce the problem with the files from test 2. Only difference is files in test 2 are slightly bigger and have more metadata (Artist, Title and Artwork). Would that make a difference?

**Comment by Vaalyn** [comment]
I've tried to replicate this by copying what @DJMike67 did and have been running 2 media files with 12s and 16s length for around 1h now on my local dev installation. The 2 media files only have title and artist metadata, no artwork.

Those have not once been played twice in a row, always `A, B, A, B, A, B` never `A, A, B, A, B, B, B` or anything like that.

This is the only playlist I have running there:

![image](https://user-images.githubusercontent.com/13745863/97112218-54bd2000-16e3-11eb-97eb-5db316a152fd.png)
![image](https://user-images.githubusercontent.com/13745863/97112229-5f77b500-16e3-11eb-8901-4c6a7d1405fc.png)
![image](https://user-images.githubusercontent.com/13745863/97112233-68688680-16e3-11eb-98f9-a1bc50458965.png)

This is the song history of the last 50 songs:

![image](https://user-images.githubusercontent.com/13745863/97112191-32c39d80-16e3-11eb-932f-207c35e5ea64.png)

**Comment by bjarn** [comment]
I am unable to reproduce it either. It just happens at random times. Could be hours between them.

**Comment by burnin-hell** [comment]
We have the same problem with rolling release #b207017 (2020-09-16 17:01) 
![IMG_20201015_154330](https://user-images.githubusercontent.com/61932963/98441625-d491b400-20ff-11eb-887f-e070bdc41b17.jpg)

**Comment by walterdevos** [comment]
I can confirm we have the same issue, but we are on the Stable edition ( v0.10.4 Stable / Docker install ).
We have the avoid duplicates **off** , but in the Song Playback Timeline, the song is listed only once though.

I have done the same tests DJMike67 did.  Short files did play twice to three times in a row A,A,B,C,B,A,A,B,C,C, even though the playlist is A,B,C...

**Comment by walterdevos** [comment]
Update:  I think this ticket is related.
https://github.com/AzuraCast/AzuraCast/issues/3467
It could even be the root cause for this behavior.

**Comment by walterdevos** [comment]
For those who experience this problem, I work around this problem by using a webhook that points to a php script that checks if the playing_next is the same as playing now, and when it is, deletes the offending track from the queue. ( 3 api calls )

1. Create a webhook that is for new songs and point it to a php script
2. Get the now playing via API ( /nowplaying )
3. Get the next playing via the API ( /queue )  <-- Use the queue, because it also returns a link to the queued entry itself (nowplaying doesn't).
4. If now playing and next paying have the same song id, use that link  (  "links":{"self":"https://radio1.streamserver.link/api/station/2/queue/269624"}  )  to feed it to a DELETE curl. 

So far this works for us.

**Comment by Vaalyn** [comment]
@walterdevos have you noticed any changes to this problem after the issue you linked to previously had been fixed?
