### ISSUE TITLE
Now Playing Data Sync Does Not Work

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#3305]
**Using Docker installation method**
Ansible

**AzuraCast version**
v0.10.4, #06808d0

**Host Operating System**
Ubuntu 18.04 LTS

**Describe the bug**
Now Playing Data Sync does not work

**To Reproduce**
1. Go to 'Administration'
2. Scroll down to 'Now Playing Data'
3. Click on 'Run Task'
4. See error 'https://prnt.sc/v3o2tl'

**Expected behavior**
Now playing data information should be updated.

**Relevant Logs**
`[Semantical Error] line 0, col 163 near 'timestamp_start': Error: Class App\Entity\StationStreamerBroadcast has no field or association named timestamp_start
QueryException.php : 65`

**Screenshots**
https://prnt.sc/v3o2tl

**Comment by SlvrEagle23** [comment]
@ogrenci01 Thank you for the report! This is fixed as of the latest update (see #3306).

**Comment by YosefAdPro** [comment]
Hi @SlvrEagle23 
 i have other error by click on "Now Playing Data"
![image](https://user-images.githubusercontent.com/11810187/96751090-71044880-13d5-11eb-93db-1f0a74701021.png)


`AzuraCast.NOTICE: Failed to acquire the "{resource}" lock. Someone else already acquired the lock. {"resource":{"Symfony\\Component\\Lock\\Key":"sync_nowplaying"}} [] `

`AzuraCast.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded {"file":"/var/azuracast/www/src/ViewFactory.php","line":76,"code":5} []`
