### ISSUE TITLE
PHP Fatal error found later last update

### ISSUE THREAD

**Issue by FiloSpaTeam** [AzuraCast/AzuraCast#3307]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #bc307d2 (2020-10-21 12:52)

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
```
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 520192 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 141

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 520192 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 141
```

**To Reproduce**
Spawn inside logs

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**

**Additional context**

**Comment by SlvrEagle23** [comment]
@FiloSpaTeam When you see that error message, where are you on the application and what are you attempting to do?

Is that error preventing anything from running?

**Comment by FiloSpaTeam** [comment]
Mmmh actually webhooks doesn't works.

https://radio.unitoo.it:8005 should work from browser?

**Comment by FiloSpaTeam** [comment]
I inspected docker logs for 20minutes and seems related to some automatic process

**Comment by dvdred** [comment]
I don't know if it is related, but **i updated to the same version and now my azuracast webhook are not more auto triggered**, but using the "test" button works! I found this issue cause i'm trying to see the process queue with `./docker.sh cli queue:process` but i get this error:
`PHP Fatal error:  Uncaught TypeError: Argument 6 passed to App\Console\Command\MessageQueue\ProcessCommand::__invoke() must be of the type int, null given in /var/azuracast/www/src/Console/Command/MessageQueue/ProcessCommand.php:17`

**Comment by FiloSpaTeam** [comment]
Looking at docker's logs i can see that every X minutes there is a PDOException. This can be related to song change and webhook trigger.

Can be?

**Comment by TheRealMakkus** [comment]
> I don't know if it is related, but **i updated to the same version and now my azuracast webhook are not more auto triggered**, but using the "test" button works!

Same here. :-(

**Comment by SC2Mitch** [comment]
> Looking at docker's logs i can see that every X minutes there is a PDOException. This can be related to song change and webhook trigger.
> 
> Can be?

Can you provide the full PDOExeption error / logs before the error pops up?

**Comment by SlvrEagle23** [comment]
The webhook issue has been fixed as of the most recent updates to the code. Update and you should have working webhooks again.

If there's another DB error popping up, please create a new issue with the full details of that error message so we can diagnose and fix that separately.

**Comment by christiansacks** [comment]
Im getting this too, it's for the 5 minute sync job - I've had this since the last 161 updates (I was 161 updates behind until this morning - hoped it would be fixed but not)
