### ISSUE TITLE
Cant connect to stream

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#331]
Hello,

I just updated the docker version and now i see my radio stations cant connect anymore with butt and winamp to the shoutcast stream.
Please  fix it

**Comment by SlvrEagle23** [comment]
@surihost I'd love to fix it, but you're not giving me a lot of information to go on here.

First of all, did you update Docker itself, or run the AzuraCast update script? There haven't been any new image pushes lately, so Docker should be working exactly as it was before.

Are you seeing some sort of error when trying to connect? If you manually run `docker-compose down`, then `docker-compose up -d`, does it still have problems?

**Comment by surihost** [comment]
I updated azuracast with the update script.
On the client side on winamp it keeps connecting but is not connecting,was working fine for days before the update i just did? No errors 

root@ks:~/ac# docker-compose down
Stopping azuracast_cron       ... done
Stopping azuracast_nginx_1    ... done
Stopping azuracast_web_1      ... done
Stopping azuracast_stations   ... done
Stopping azuracast_redis_1    ... done
Stopping azuracast_mariadb_1  ... done
Stopping azuracast_influxdb_1 ... done
Removing azuracast_cli_1      ... done
Removing azuracast_cron       ... done
Removing azuracast_nginx_1    ... done
Removing azuracast_web_1      ... done
Removing azuracast_stations   ... done
Removing azuracast_redis_1    ... done
Removing azuracast_mariadb_1  ... done
Removing azuracast_influxdb_1 ... done
Removing network azuracast_default

root@ks:~/ac# docker-compose up -d
Creating network "azuracast_default" with the default driver
Creating azuracast_stations ...
Creating azuracast_mariadb_1 ...
Creating azuracast_redis_1 ...
Creating azuracast_influxdb_1 ...
Creating azuracast_mariadb_1
Creating azuracast_redis_1
Creating azuracast_influxdb_1
Creating azuracast_stations ... done
Creating azuracast_web_1 ...
Creating azuracast_web_1 ... done
Creating azuracast_nginx_1 ...
Creating azuracast_cron ...
Creating azuracast_cli_1 ...
Creating azuracast_nginx_1
Creating azuracast_cron
Creating azuracast_nginx_1 ... done

**Comment by SlvrEagle23** [comment]
Try running `docker-compose logs -f stations`, and see if it posts any log entries when you try to connect.

**Comment by surihost** [comment]
stations_1  | 2017-12-13 00:59:37       ERROR   Source responded with error [HTTP/1.1 404 Not Found]
stations_1  | 2017-12-13 00:59:38       ERROR   [DST 83.84.65.23:63271 sid=1] SHOUTcast 1 client connection rejected. Stream not available as there is no source connected. Agent: `Lavf/57.25.100'
stations_1  | 2017-12-13 00:59:38       ERROR   [DST 83.84.220.3:47821 sid=1] SHOUTcast 1 client connection rejected. Stream not available as there is no source connected. Agent: `Lavf/57.25.100'
stations_1  | 2017-12-13 00:59:39       ERROR   [DST 83.84.220.3:47822 sid=1] SHOUTcast 1 client connection rejected. Stream not available as there is no source connected. Agent: `Lavf/57.25.100'
stations_1  | 2017-12-13 00:59:39       ERROR   [DST 83.84.65.23:63272 sid=1] SHOUTcast 1 client connection rejected. Stream not available as there is no source connected. Agent: `Lavf/57.25.100'

stations_1  | 2017-12-13 00:54:17       ERROR   Source responded with error [HTTP/1.1 404 Not Found]
stations_1  | 2017-12-13 00:54:17       ERROR   [DST 83.84.220.3:47573 sid=1] SHOUTcast 1 client connection rejected. Stream not available as there is no source connected. Agent: `Lavf/57.25.100'
stations_1  | 2017-12-13 00:54:17       ERROR   [DST 83.84.65.23:63044 sid=1] SHOUTcast 1 client connection rejected. Stream not available as there is no source connected. Agent: `Lavf/57.25.100'
stations_1  | 2017-12-13 00:54:19       ERROR   [DST 83.84.220.3:47574 sid=1] SHOUTcast 1 client connection rejected. Stream not available as there is no source connected. Agent: `Lavf/57.25.100'
stations_1  | 2017-12-13 00:54:19       ERROR   [DST 83.84.65.23:63045 sid=1] SHOUTcast 1 client connection rejected. Stream not available as there is no source connected. Agent: `Lavf/57.25.100'
stations_1  | 2017-12-13 00:54:20       ERROR   [DST 83.84.220.3:47575 sid=1] SHOUTcast 1 client connection rejected. Stream not available as there is no source connected. Agent: `Lavf/57.25.100'
stations_1  | 2017-12-13 00:54:20       ERROR   [DST 83.84.65.23:63046 sid=1] SHOUTcast 1 client connection rejected. Stream not available as there is no source connected. Agent: `Lavf/57.25.100'
stations_1  | 2017-12-13 00:54:21       ERROR   [DST 83.84.220.3:47576 sid=1] SHOUTcast 1 client connection rejected. Stream not available as there is no source connected. Agent: `Lavf/57.25.100'

**Comment by SlvrEagle23** [comment]
@surihost Did you update your station to be listed as "public", but without providing it an authhash? That will cause that error.

**Comment by surihost** [comment]
the stations i do stream connecting butt has authhash so it is saved there

**Comment by SlvrEagle23** [comment]
@surihost Visit the station's shoutcast admin page and see what it's saying, because it likely is the cause of the problem here.

**Comment by surihost** [comment]
station admin page cant be reached :(
Can i email you, so can check with my logins?

**Comment by surihost** [comment]
I found the cause, i am using expanded port range and weird that after the update and reboot it didn't get it self.

I run this again : docker-compose -f docker-compose.yml -f docker-compose.stationports.yml up -d
And now all works fine again.
