### ISSUE TITLE
Imported M3U or PLS is sorted by artist after import

### ISSUE THREAD

**Issue by walterdevos** [AzuraCast/AzuraCast#3310]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.4 Stable

**Host Operating System**
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"

**Describe the bug**
Not sure if it's a bug or just the way it works.

First, wow, this product is awesome. It's so clean and professional looking. Better than most commercial products I've seen. gj!

I have a few servers running just liquid soap processes and I feed them playlists ( one for each day ). I have installed Azuracast in to relay these stations on a high bandwidth server. 
But I was wondering, since liquid soap is already part of Azuracast, why not use that in stead. So I can use all the many neat features (like cue points, managing/uploading media. 

So I moved the playlists to Azuracast. 

**To Reproduce**

Problem is when I create a playlist, General Rotation, Source song based and sequential (nothing else) and then **import**  a PLS or M3U with the filenames of the media that is on the server, It seems to immediately order the playlist by artist. 

Imagine 4 files on the server:
file1 - artist - title
file2 - zartist - title
file3 - otherartist - title

the PLS (or m3u ) looks like:
file 3
file 1
file 2

After importing, the order in the playlist is ( you can check this by clicking re-order )
artist (file1)
otherartist (file3)
zartist (file2)

and Azuracast plays the files in that order. 

**Expected behavior**

As we create these playlist with another playlist generator, they are meant to be played in that exact order. 
The order of the tracks should not be alphabetically reordered after the import.

**Relevant Logs**
I don't think there are relevant logs.

**Additional context**

This is how we schedule playlists on the other liquidsoap instances:

sun = playlist(mode='normal',reload_mode="watch",mime_type="audio/mpeg","/home/radio/hra/playlist/HRA-Sunday.txt")
mon = playlist(mode='normal',reload_mode="watch",mime_type="audio/mpeg","/home/radio/hra/playlist/HRA-Monday.txt")
tue = playlist(mode='normal',reload_mode="watch",mime_type="audio/mpeg","/home/radio/hra/playlist/HRA-Tuesday.txt")
wed = playlist(mode='normal',reload_mode="watch",mime_type="audio/mpeg","/home/radio/hra/playlist/HRA-Wednesday.txt")
thu = playlist(mode='normal',reload_mode="watch",mime_type="audio/mpeg","/home/radio/hra/playlist/HRA-Thursday.txt")
fri = playlist(mode='normal',reload_mode="watch",mime_type="audio/mpeg","/home/radio/hra/playlist/HRA-Friday.txt")
sat = playlist(mode='normal',reload_mode="watch",mime_type="audio/mpeg","/home/radio/hra/playlist/HRA-Saturday.txt")

radio = fallback(track_sensitive=false,[switch(track_sensitive=false,[
           ({ (0w) }, sun),
            ({ (1w) }, mon),
            ({ (2w) }, tue),
            ({ (3w) }, wed),
            ({ (4w) }, thu),
            ({ (5w) }, fri),
            ({ (6w) }, sat),])
])

So we just replace the playlist in time to be picked up by LS. It would be great if we could just import them and let Azuracast ( AutoDJ ) play them. 

( extra bonus question ) Could we import them using the API? I can create playlists, but how to fill them with tracks using the API?

Thanks for your time and effort. Greatly appreciated.

**Comment by walterdevos** [comment]
I've actually been so frank as to look in the source code where this "sorting" is happening, and I think I found the culprit.

In the Controller/Api/Stations/PlaylistsController.php  line 300+ where the import happens.
Basically you match hashed version of the paths in the playlist , to hashed versions of dB entries form StationMedia table which is filtered by a "WHERE IN" the list id's from the matches found. 

By adding **order by FIELD(sm.id, :matched_ids) ;** it should then sort the query in the same order as the id's are stored in the array. So when you add the weights++ in line 379 , the distribution of weigths matches the order of the playlist.

I'm going to attach to the docker where NGNIX resides, in the hope to find the controller and make the change, to see if it works.  I'm not sure mysql accepts a parameter like this in FIELD(sm.id, :matched_ids). It's might be necessary to expand.

I'm also looking into why it should do that last query in the first place. I'm going to try and put everything we need in the result $media_info_raw of the first query and see if we can go from there. 

I'll keep you posted.
;-)

**Comment by walterdevos** [comment]
That won't work, it seems the doctrine2 extention for FIELD is not supported in ORDER BY.  
Even with adding $config->addCustomStringFunction('FIELD', DoctrineExtensions\Query\Mysql\Field::class);  to services.php doesn't help. Always get 
```
500
[Syntax Error] line 0, col 148: Error: Expected known function, got 'FIELD'
QueryException.php : 54
```
And also, all multiple entries in a playlist will be ignored. ( which we don't want ).
I now see why the last query is done, to weed out the duplicated. ( clever ;-) )

Going another route. Keep you posted ;-)

**Comment by walterdevos** [comment]
OK, 
I have been so frank as to dive into the code. 
I found src/Controller/Api/Stations/PlaylistsController.php to be responsible for importing.

I tried a few things, but I'm not familiar with doctrine, suffice to say may solution is dirty, but you'll get the gist of it.

What this method does is matching every line in the playlist with an entity in the music database, by comparing the paths (filenames) stored in the db with the paths (filenames) listed in the pls (or m3u). It ends up with an array where the hashed paths are index (key) and the corresponding id's of the music database is the value.

It then goes on to fetch all the instances of the entities in the music database by id and puts them one by one in a playlist.

I changed the way it collects these instances. 

Originally it does one query like this:

```
$matched_media = $this->em->createQuery(/** @lang DQL */ 'SELECT sm
--
  | foreach ($matches as $single_match){ |   |  
  | $media_proxy = $this->em->createQuery(/** @lang DQL */ 'SELECT sm |   |  
  | FROM App\Entity\StationMedia sm |   | FROM App\Entity\StationMedia sm
  | WHERE sm.station = :station AND sm.id = :id') |   | WHERE sm.station = :station AND sm.id IN (:matched_ids)')
  | ->setParameter('station', $station) |   | ->setParameter('station', $station)
  | ->setParameter('id', $single_match ) |   | ->setParameter('matched_ids', $matches)
  | ->execute(); |   | ->execute();
```

For my purpose, I changed it to this:


```
foreach ($matches as $single_match){ |   |  
-- | -- | --
  | $media_proxy = $this->em->createQuery(/** @lang DQL */ 'SELECT sm |   |  
  | FROM App\Entity\StationMedia sm |   | FROM App\Entity\StationMedia sm
  | WHERE sm.station = :station AND sm.id = :id') |   | WHERE sm.station = :station AND sm.id IN (:matched_ids)')
  | ->setParameter('station', $station) |   | ->setParameter('station', $station)
  | ->setParameter('id', $single_match ) |   | ->setParameter('matched_ids', $matches)
  | ->execute(); |   | ->execute();
  |   |   |  
  |   |   | $weight = $playlistMediaRepo->getHighestSongWeight($playlist);
  |   |   |  
  |   |   | foreach ($matched_media as $media) {
  | $weight++; |   | $weight++;
  |   |   |  
  | /** @var Entity\StationMedia $media */ |   | /** @var Entity\StationMedia $media */
  | $playlistMediaRepo->addMediaToPlaylist($media_proxy[0], $playlist, $weight); |   | $playlistMediaRepo->addMediaToPlaylist($media, $playlist, $weight);
  |   |   |  
  | $foundPaths++; |   | $foundPaths++;
  |   |   |  
  | }
```

This is of course BAD, and I'm sure with doctrine ( as far as I have looked ) there is a better way. But at least, for now, the PLS is exactly imported in the same order and any double tracks are included. 

I will continue looking for a way to have this as an extra option in the menu. As it is now, it replaces the import function.

**Comment by SlvrEagle23** [comment]
@walterdevos Thank you for looking into this and for your findings.

It turns out the solution I'd prefer is really just as simple as using a temporary filler array to hold the media entities, then looping back through the original array to get the order. Same complexity and number of queries, just with the order maintained. The fix has been published to the rolling release branch.

**Comment by walterdevos** [comment]
Excellent 👍 and thank _you_ for looking at it and adapting it so quickly. :)

**Comment by Vaalyn** [comment]
Closing as resolved
