### ISSUE TITLE
Is it me OR?

### ISSUE THREAD

**Issue by pwrj** [AzuraCast/AzuraCast#3311]
Azuracast hasn't released an update in a while. I used to be like a kid anticipating presents the night before Christmas, but lately there has been no update, which has prompted to ask the question: Is it me?

**Comment by SC2Mitch** [comment]
What branch are you on, stable or rolling-release? Rolling has updates near constantly.

**Comment by pwrj** [comment]
> What branch are you on, stable or rolling-release? Rolling has updates near constantly.

Stable.

**Comment by pwrj** [comment]
> > What branch are you on, stable or rolling-release? Rolling has updates near constantly.
> 
> Stable.

My selection is: "All Updates: Include all announcements and minor updates."

**Comment by SC2Mitch** [comment]
Ah, rolling release includes every single commit, while it's not 'recommended' for production instances, its heavily updated every few times a week. 

If you wanna switch you can do it here: https://www.azuracast.com/administration/system/release-channels.html#switching-release-channels

Obvious disclaimer, **TAKE SNAPSHOTS BEFORE UPDATES** :)

**Comment by pwrj** [comment]
> Ah, rolling release includes every single commit, while it's not 'recommended' for production instances, its heavily updated every few times a week.
> 
> If you wanna switch you can do it here: https://www.azuracast.com/administration/system/release-channels.html#switching-release-channels
> 
> Obvious disclaimer, **TAKE SNAPSHOTS BEFORE UPDATES** :)

Thank you. I'll try it.

**Comment by pwrj** [comment]
Success! Thanks again!
