### ISSUE TITLE
Could not find the requested service redis: host

### ISSUE THREAD

**Issue by InstabilSpielt** [AzuraCast/AzuraCast#3313]
**Using Docker installation method**
No

**AzuraCast version**
Latest stable version.

**Host Operating System**
Ubuntu 18.04 & 16.04

**Describe the bug**
When I try to install Azuracast the installer prints the following: 
**fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service redis: host"}**
and cancels the installation.

**Screenshots**
https://s12.directupload.net/images/201022/58kcdeeh.png

**Comment by Xara** [comment]
Hello. What is your PHP version? some servers force update to 8.0, then you need set it to 7.4 ....

**Comment by InstabilSpielt** [comment]
I install AzuraCast normal using the installation script @Xara, with the default PHP version.

**Comment by Xara** [comment]
I ask as I got that error, it was system updating to 8.0 without me asking for, after downgrade to 7.4 all ran fine again.
