### ISSUE TITLE
Needing to extract metadata from music that playing.

### ISSUE THREAD

**Issue by rleiman** [AzuraCast/AzuraCast#3319]
Greetings,

I've been asked to create a B4A (Basic4Android) app to extract metadata from the song that's currently playing. I used the following B4A coding to extract the metadata.

`
	Dim jo As JavaObject = player1
	Dim TrackGroups As JavaObject = jo.GetFieldJO("player").RunMethod("getCurrentTrackGroups", Null)
	For i = 0 To TrackGroups.GetField("length") - 1
		Dim TrackGroup As JavaObject = TrackGroups.RunMethod("get", Array(i))
		For j = 0 To TrackGroup.GetField("length") - 1
			Dim Format As JavaObject = TrackGroup.RunMethodJO("getFormat", Array(j))
			Dim Metadata As JavaObject = Format.GetField("metadata")
			If Metadata.IsInitialized Then
				Label1.Text = "Data Found at: " & DateTime.Time(DateTime.Now) _
					& Chr(10) & Chr(10) & Metadata
			End If
		Next
	Next
`

The coding extracts the metadata from the server but it's very limited. The metadata that's returned is:

`
(Metadata) entries=[IcyHeaders: name="VIFM", genre="Easy Listening", bitrate=320000, metadataInterval=16000]
`

What I need for the app is:
Song title
Artist's name
Length of song
Current song playhead position

Can you tell me how to add that to my B4A coding?

Thanks in advance.

Truly,
Emad

**Comment by SlvrEagle23** [comment]
@rleiman Rather than rely on the in-stream metadata supplied through the MP3 stream, we recommend using our [Now Playing data APIs](https://www.azuracast.com/developers/nowplaying.html), which are available for any AzuraCast installation.

**Comment by rleiman** [comment]
Greetings,

I’m now using the API to download JSON I can use.

I have a question. The radio station wants me to add notifications to my app in the same way my app is displaying the song and artist name. Is it possible for the radio station administrator to add a key to the JSON file that the API downloads? I would like the key to be called “notifications” and the station administrator to be able to maintain what the value is for the key is.

Thanks.

Truly,
Emad

**Comment by SlvrEagle23** [comment]
@rleiman This is possible on a per-media-file basis using custom fields, but is not currently possible on a per-station basis.

**Comment by rleiman** [comment]
Hi,

I’m doing it for someone who just has 1 station they are streaming. When you say per-media, do you mean for the whole system setup? They will be giving me a login to there system so if you can give me directions on setting up the custom field, that will be greatly appreciated. I would also like to know how to populate the values that go into the custom field.

Thanks in advance.

Truly,
Emad
