### ISSUE TITLE
Problem for discord error 204

### ISSUE THREAD

**Issue by guillaumed24** [AzuraCast/AzuraCast#3321]
Hello

I have error on discord webhook. 

Error 204.

Can you help me ? Thank.

**Comment by Vaalyn** [comment]
I've created a discord webhook on my local test installation to check if there are any errors but everything seems to be working fine.

Please explain what exactly is not working and include any logs with errors for the issue you are experiencing.

The status code `204` does not represent an error code.

**Comment by guillaumed24** [comment]
Here the info when i test webhook :

Some data are blank *********


Debug
Dispatching connector "discord".
Debug
Dispatching Discord webhook...
Debug
HTTP client POST call to https://discord.com/api/webhooks/************************** produced response 204
Debug
Webhook discord returned code 204
message_sent

{
    "content": "Maintenant on joue sur Radio Dunes 104.4 FM - Bassin D'Arcachon :",
    "embeds": [
        {
            "title": "Le journal des associations",
            "url": "https:\/\/****************.fr\/radio\/8000\/radio.aac?1603476257",
            "color": 2201331,
            "author": {
                "name": "Radio Dunes DAB"
            },
            "thumbnail": {
                "url": "https:\/\/stream.radiosystem.fr\/static\/img\/generic_song.jpg"
            },
            "footer": {
                "text": "Propuls\u00e9 par AzuraCast"
            }
        }
    ]
}

response_body

""

**Comment by Vaalyn** [comment]
I can't see any errors in that response. Is the message shown in Discord?

**Comment by guillaumed24** [comment]
Ooohhh sorry....
Message are on discord this is not error message.

Sorry sorry sorry......
