### ISSUE TITLE
the SSL cert. form adm. panel is expired and not the same with Icecast certs

### ISSUE THREAD

**Issue by petrix** [AzuraCast/AzuraCast#3322]
**Using Docker installation method**

With Icecast certs all done. 
I'm to do update once at month,
this'one bug i'm receive at one of last updates,
Thanx a lot for Your attention)
**AzuraCast version**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by petrix** [comment]
![Screen Shot 2020-10-24 at 12 29 10](https://user-images.githubusercontent.com/625733/97078468-219c6300-15f5-11eb-9a77-c0aac6849d00.png)
![Screen Shot 2020-10-24 at 12 25 43](https://user-images.githubusercontent.com/625733/97078469-219c6300-15f5-11eb-91b2-ddbc1c43319e.png)
![Screen Shot 2020-10-24 at 12 20 49](https://user-images.githubusercontent.com/625733/97078470-219c6300-15f5-11eb-822c-a11c05c955b4.png)
![Screen Shot 2020-10-24 at 12 17 56](https://user-images.githubusercontent.com/625733/97078471-2234f980-15f5-11eb-8060-c106d5b82481.png)

**Comment by SlvrEagle23** [comment]
@petrix You may need to restart broadcasting on the station to have it update its SSL certificate to match your latest LetsEncrypt certificate.

**Comment by petrix** [comment]
Hi there,
The cert. on icecast server is valid & i don't think what the "restarting
broadcasting" is neded. I have a problem with cert. on adm. panel and with
/api dir. when i trying to fetch some metadata from frontend-app behind
https rules.

сб, 24 окт. 2020 г., 15:08 SlvrEagle23 <notifications@github.com>:
