### ISSUE TITLE
AzuraCast on Windows Server

### ISSUE THREAD

**Issue by dvbtrecorder** [AzuraCast/AzuraCast#3324]
When will AzuraCast be available on Windows Server?

**Comment by SlvrEagle23** [comment]
@dvbtrecorder We currently have no plans to distribute production images of AzuraCast for Windows Server, as we have no infrastructure available to test for that platform and it wouldn't fit in with a fully-open-source software stack anyway.

It is possible to follow our [developer guide](https://www.azuracast.com/developers/), which allows AzuraCast to run on most Windows and MacOS hosts.
