### ISSUE TITLE
Music uploaded through FTP does not refresh the table properly causing "hidden" files. 

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#3325]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #c955f4a

**Host Operating System**
Ubuntu 20.04 

**Describe the bug**
When you upload music through SFTP to a station it does not immediately appear, the file manager correctly counts the number of files, but the table does not load the required songs. The only fix for this is to create a folder which seems to refresh the table completely. 

**To Reproduce**
Load up a FTP client of your choice (Mine was Filezilla) and connect to a station using your FTP credentials. 
Upload some music to the station (Ideally when the station has no music
Watch the uploads complete and the server to correctly allocate the storage and count the number of files but not show the music files. 
-- TO FIX --
Create a folder inside the music files, the table refreshes correctly. 

**Expected behavior**
The table to properly refresh and to view the songs you uploaded through FTP. 

**Relevant Logs**
I cant see any error logs, nor browser errors. 

**Screenshots**
A video of the bug in full. - https://puu.sh/GGt9i/afa94f0eff.mp4

Music Files page correctly counting the songs, but not refreshing the table.  - https://puu.sh/GGte3/f1ae7ad5b3.png

FTP showing the uploaded files - https://puu.sh/GGtlw/34060c3dc9.png

The table correctly refreshing when a new folder is created - https://puu.sh/GGtif/b071d9da75.mp4

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
@SC2Mitch I've done some veeeery basic investigation and this seems to be a cache thing. The frontend is calling the following API endpoint:
```
http://localhost/api/station/7/files/list?internal=true&rowCount=50&current=1&file=
```

When I add `&flushCache=true` to the API call to force it to clear the filesystem cache the via SFTP uploaded file (that has not been processed yet) is shown. See [this part](https://github.com/AzuraCast/AzuraCast/blob/master/src/Controller/Api/Stations/Files/ListAction.php#L31-L33) of the Controller for reference.

In general when a file is uploaded via SFTP the filesystem cache should be cleared but for some reason this seems to not be working as intended. See [this part](https://github.com/AzuraCast/AzuraCast/blob/master/src/Console/Command/Internal/SftpUploadCommand.php#L46) of the internal SftpUploadCommand.

I can see the `AzuraCast.NOTICE: SFTP file uploaded` log entry and the `AzuraCast.INFO: Sending message {class} with {alias} sender using {sender} {"message":{"App\\Message\\AddNewMediaMessage"...` so I'm assuming that the command is not producing an error (can't see one).

**Comment by SlvrEagle23** [comment]
Yep, it's very likely this is a cache issue. No doubt, the file's already there (and should even be processed already), it's just not showing up in the media manager.

Will investigate whether this command is being invoked properly.

**Comment by SlvrEagle23** [comment]
Pretty sure I figured this one out...we disabled several Redis caches on the CLI level because we didn't want Doctrine's metadata cache being used there, because you could get the cache out of sync and then the CLI commands to fix that wouldn't themselves work right.

It turns out we were a little overzealous in that, disabling Redis caching on _anything_ that used Redis, including the filesystem cache, so when our sync tasks processed media changes (or SFTP uploads) it didn't use the correctly cached filesystem, so it never actually flushed the cache that's used by the frontend displays.

It's likely this was causing all of the filesystem sync problems we've been having. This has been fixed in the latest version.

**Comment by SC2Mitch** [comment]
Fixed! Thanks.
