### ISSUE TITLE
Add playlist schedule not working

### ISSUE THREAD

**Issue by netbladenl** [AzuraCast/AzuraCast#3326]
**Using Docker installation method**
yes

**AzuraCast version**
#f4ee441 

**Host Operating System**
Ubuntu 20.04 LTS

**Describe the bug**
Started off with a fresh installation of ubuntu lts server and the latest rolling update of azuracast.
Since then I can't schedule any playlist to play on a selected time, I can make a selection when to play but it doesn't save on close and it doesn't show up at the Schedule View.

**To Reproduce**
Create a new playlist or edit an existing one and go to schedule, try to schedule something and then click on ok. It won't save and it doesn't show up in the scheldule view

**Expected behavior**
Saving the scheduled times in every playlist

**Relevant Logs**
No logs or error messages

**Comment by SlvrEagle23** [comment]
@netbladenl Thank you for the report. I have identified the cause of this and fixed it as of the latest update. You should be able to update in just a few minutes to restore functionality to the playlist modal.
