### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by DJMike67** [AzuraCast/AzuraCast#3327]
Hi

Could anyone please tell me what a "Slim Application Error" is please

It appeared last week in both the embedded player on my website and also when I tried to get to the "dashboard login page" on my host's site: https://azura.shoutca.st/login

When I reported it to the hosting company, they told me that it was due to the "emergency update" which they had to deploy

Today it has appeared again which means my embedded player is out of action and I can't get to the dashboard but it has been like this for the past 6 hours. The host doesn't provide weekend support

I'm not looking to blame anyone (I love Azuracast despite me submitting several issues here in the past couple of weeks). I'm simply trying to understand what is causing the problem and whether it is my hosting company or the Azuracast software

The full message that appears is...
Slim Application Error. A website error has occurred. Sorry for the temporary inconvenience.

I can't even provide any logs because I can't get to my dashboard!!

Many thanks as always

Mike

**Comment by SC2Mitch** [comment]
This issue needs to be resolved through your hosting company, without logs we're unable to see what's gone wrong. My local machines are spinning up fine without any issues nor am I encountering any `slim application errors`

**Comment by dev1983** [comment]
I am also facing the same issue when I try to login to dashboard but No logs found? What is the fix please. I am using docker based installation vaerion version 0.140. Does upgrading to version to version 0.14.1, fixes the issue? help pls.
