### ISSUE TITLE
How to install an older version

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#3328]
What is the command to install an older version of Azuracast on a clean vps?

**Comment by Madpeterz** [comment]
Are you going to be using docker and the auto installer script?

**Comment by roger-net** [comment]
> Are you going to be using docker and the auto installer script?

Yes, I will use the docker method.

**Comment by roger-net** [comment]
I would like to install version 0.10.2 on a clean vps. How do I do that?

**Comment by YosefAdPro** [comment]
Try this
./docker.sh install 0.12.0

**Comment by YosefAdPro** [comment]
Try this
./docker.sh install 0.10.2

**Comment by roger-net** [comment]
> Try this
> ./docker.sh install 0.10.2

I've tried this command and it didn't work
