### ISSUE TITLE
Translation into another language

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#333]
> You can also upload files in bulk via SFTP by following these instructions. Newly uploaded files will automatically be processed within a few minutes.

You added new phrases but did not add them to the translation file. Please make them into the file.

**Comment by susl16c** [comment]
You sent me before on the website with a translation, but there you can not download the .po file, how do I download the translation, so I do not drive it through the lines?

**Comment by susl16c** [comment]
When you include a translation into my native language, the main page remains in your language.
https://radio.izones.ru/login

**Comment by SlvrEagle23** [comment]
@susl16c All translation work is done through CrowdIn: https://crwd.in/azuracast

I don't regenerate the language files after every single change, as that takes a prohibitive amount of time. I'll do it again prior to the next release, but please don't push for more frequent updates.

**Comment by susl16c** [comment]
When you include a translation into my native language, the main page remains in your language.
https://radio.izones.ru/login

**Comment by ivellios1988** [comment]
I just wanted to let you know that Polish translation is 100% ready. I translated all the remaining messages.
