### ISSUE TITLE
Shoutcast v2 installed but not running

### ISSUE THREAD

**Issue by radioutopia** [AzuraCast/AzuraCast#3332]
Hello.
I have installed the shoutcast v2 DNA, but he´s not running. No errors appeared, nothing... just the radio don´t start.
What can be? some help, please.

Thanks

Powered by AzuraCast • v0.10.4, #b31f892 (2020-10-13 4:50) • Ansible • PHP 7.4
VPS on google cloud with Ubuntu 20.04

**Comment by SC2Mitch** [comment]
Hi @radioutopia ! 
Let's go through some debug logs and have a look at this issue. 

When you try and start the station with the ShoutCast configuration check the logs at `/var/azuracast/www_tmp/app.log`
Along with this, you can try checking the ShoutCast logs itself in the browser, video attached: https://puu.sh/GH6zQ/689c6c0fe7.mp4

**Comment by radioutopia** [comment]
Hello @SC2Mitch 

Thanks a lot for your help.
This appens because i have the same password for the same fields, Source and Administrator.

best regards
