### ISSUE TITLE
MP3 Metadata being stripped out on upload

### ISSUE THREAD

**Issue by DJMike67** [AzuraCast/AzuraCast#3335]
Rolling Release #bc307d2 (2020-10-21 12:52) • Docker • PHP 7.4

I have an issue with several MP3 files losing part of the "song title" metadata after being uploaded and processed.

Today I uploaded about 25 MP3 files. Three of them had a Title of "Marooned at MacBites HQ - Day XXX" where XXX is a 3 digit number (all the MP3's are podcast episodes)
<img width="1097" alt="Screenshot1" src="https://user-images.githubusercontent.com/72672017/97216697-2102f880-17be-11eb-9749-063524f0a20d.png">

The metadata was added to the files in the audio editing software as usual. The audio was exported as normal. 

The files were then uploaded via the web interface. They uploaded fine, they processed fine. 

But when I look at them in the file list (see screenshot) the XXX is missing from the end of the Song Title in the Name column

I deleted them and re-uploaded using FTP - same result

I have checked the metadata of the MP3 files that were exported from the audio editor using a Mac app called Yate (but any MP3 checker would work I guess) and the metadata is correct

I know that I can click Edit and manually add the XXX to the Song Title field and it accepts it. But to have to do this for a large number of files is time consuming

Also it was only 3 files that had the problem. 

The other files that I uploaded (from a different podcast) have a much shorter Song Title (MacBites_XXXX) and were OK

The odd thing is that the back in June this year I uploaded an older episode of the podcast with the same characters in the Song Title and had no problem

I've copied the output from the browser Network console

The last-but-one entry is...

{"current":1,"rowCount":10,"total":1,"rows":[{"mtime":1603738412,"size":53250468,"name":"Test/marooned-at-macbites-hq-day-0222.mp3","path":"Test/marooned-at-macbites-hq-day-0222.mp3","text":"marooned-at-macbites-hq-day-0222.mp3","is_dir":false,"can_rename":true,"rename_url":"/api/station/8/files/rename?file=Test%2Fmarooned-at-macbites-hq-day-0222.mp3","media_is_playable":true,"media_length":"3319.93","media_length_text":"55:19","media_artist":"Elaine Giles and Mike Thomas","media_title":"Marooned at MacBites HQ - Day","media_album":"MacBites","media_genre":"Podcast","media_name":"Elaine Giles and Mike Thomas - Marooned at MacBites HQ - Day","media_art":"/api/station/8/art/e91741983ff6c9fab3bb1da6-1603738405.jpg","media_art_url":"/api/station/8/art/225743","media_waveform_url":"/api/station/8/waveform/e91741983ff6c9fab3bb1da6-1603738405.json","media_can_edit":true,"media_edit_url":"/api/station/8/file/225743","media_play_url":"https://azura.shoutca.st/api/station/8/download/225743","media_playlists":[]}]}

 
<img width="1097" alt="Screenshot1" src="https://user-images.githubusercontent.com/72672017/97216731-2c562400-17be-11eb-88ea-aad14221496b.png">

**Comment by Vaalyn** [comment]
This is Most likely due to a bug that was already fixed by my PR https://github.com/AzuraCast/AzuraCast/commit/ef1933789c8bae629f26911e2a30be19a88a5e68 from 23.10.2020.

Due to some changes to the metadata parsing the ID3v1 tags where accidentally preferred when reading metadata instead of the ID3v2 tags. That PR reverses that so that v2 is used first and v1 only as fallback if v2 is empty.

**Comment by DJMike67** [comment]
Thanks @Vaalyn ill see if it’s fixed when my host updates

**Comment by Vaalyn** [comment]
I'm closing this issue since the underlying bug has been fixed.

If you still experience this after your host has updated please let me know.

**Comment by DJMike67** [comment]
@Vaalyn My host has updated to  Rolling Release #1f79f86 (2020-10-30 19:10) and I can confirm that this has fixed the problem. Many thanks as always
