### ISSUE TITLE
Manual backup in loop - unstoppable  ## HELP! ##

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#3336]
**Using Docker installation method**
 Yes

**AzuraCast version**
 v0.10.3, #ffa6d6b (2020-07-15 8:00) Rolling

**Host Operating System**
 Ubuntu 18.04

**Describe the bug**
Today I started a full manual backup but after the task ended it started all over again. Same task, same backup with same file name over and over.
Even after restarting the server or deleting the file did not remove the issue.
How do I stop the backup task from running?

Thanks.

**Comment by SC2Mitch** [comment]
If your on the rolling branch, you need to update your system. It'll come with a fix to resolve this issue.

**Comment by eranwo** [comment]
To be honest, I'm afraid to upgrade
This version has been very stable for me so far

**Comment by eranwo** [comment]
Is this a known issue?

**Comment by SC2Mitch** [comment]
No, this issue was fixed a month ago. 
https://github.com/AzuraCast/AzuraCast/issues/3096

Run a update on your machine. 
```
cd /var/azuracast
./docker.sh update-self
./docker.sh update
```

**Comment by Vaalyn** [comment]
Closing this issue since this issue is already fixed for quite some time and we don't backport fixes to old versions.
