### ISSUE TITLE
Displays the song / artist name   "??? ?????"

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#3337]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #7fa7ca7 (2020-10-22 7:18)

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
I'm having a problem with displaying the song name /artist (non English language) . It displays "??? ????" instaed of the song/aritst name.
That issue was not exist in previous versions

**Comment by SC2Mitch** [comment]
What song is it exactly? Copy and paste it here and I'll take a look when I can

**Comment by eranwo** [comment]
@SC2Mitch I updated to the latest version and it seems to be ok now
Thanks!

**Comment by SC2Mitch** [comment]
Perfect! Feel free to close the issue then, have a lovely day.
