### ISSUE TITLE
Editing Footer and or Logo

### ISSUE THREAD

**Issue by spacejankey** [AzuraCast/AzuraCast#3338]
Hi everyone I know you're not to keen on removing the azuracast logo or footer but It's possible, I'd like to know if donate would the steps or a tutorial be facilitated to me? 

There's YouTube videos on people using azuracast with there logos but no one seems to have a concrete guide out there.

I'd appreciate it 

Thanks

**Comment by jaleeldgk** [comment]
Hi, yes there are many ways for doing this.
Legally you can't (shouldn't) do that.

But still you want to modify it you can do that using CSS/js code, that you can put through admin panel.

If above solution is not working you can always modify code from docker
Thanks

**Comment by spacejankey** [comment]
> Hi, yes there are many ways for doing this.
> Legally you can't (shouldn't) do that.
> 
> But still you want to modify it you can do that using CSS/js code, that you can put through admin panel.
> 
> If above solution is not working you can always modify code from docker
> Thanks

Hi Jaleel, do you have the css code I'd use to edit the footer via the admin panel?

**Comment by jaleeldgk** [comment]
Actually not.
I tested it some months ago, related code was also published on this GitHub.
Hopefully you'll find it.

For modification on docker installation, you have to modify code using docker ssh

Thanks

**Comment by Vaalyn** [comment]
There is currently no plan on offering a white-labeled version or offering any options to remove our branding.
