### ISSUE TITLE
Swagger seems to be broken on demo

### ISSUE THREAD

**Issue by Madpeterz** [AzuraCast/AzuraCast#3344]
**Using Docker installation method**
Docker • PHP 7.4

**AzuraCast version**
Rolling Release #02b92bf

**Host Operating System**
Unknown Demo

**Describe the bug**
Most requests fail with: 
"TypeError: NetworkError when attempting to fetch resource."

**To Reproduce**

1. goto https://www.azuracast.com/api/#/Stations%3A%20General/App%5CController%5CApi%5CStations%5CIndexController%3A%3AlistAction
2. login and set the api key (found in demo portal)
3. select an api action (example: [GET] /admin/permissions)
4. click Execute
5. see error message

**Expected behavior**
expect response like [GET] "/stations"

**Device(s):**
 - Device: Desktop
 - OS: Windows10
 - Browser: Firefox
 - Version: 82.0

**Additional context**
thanks for the hard work

**Comment by SlvrEagle23** [comment]
@Madpeterz It's functioning just fine now; I think you tried to hit the API at the top of the hour, when the demo installation is resetting. It won't work for a few minutes at the top of every hour, but it'll be working as normal after that.

**Comment by Madpeterz** [comment]
Issue continues

Commands failing (maybe others)
/station/{station_id}/request/{request_id}  [args: 1,1] {post} {12:48}
/station/{station_id}/status {get} {12:50}

will retry at 10 past
