### ISSUE TITLE
WebDJ doesn't give notification or error

### ISSUE THREAD

**Issue by jaleeldgk** [AzuraCast/AzuraCast#3346]
Hi,
Thank You for this wonderful software. I just checked every aspect of this software and tested alot of things on it. 
Well, it have some minor bugs but I'm sharing an important bug in here...

On WebDJ once we enter our credentials it shows nothing.
No error 
No success
No notification
Nothing

Even we enter wrong credentials it showed nothing and on clicking start streaming it does nothing.

This is important bug.

**Using Docker installation method**

It doesn't show either it's streaming, wrong credentials or any other info.

This should give notification for success or error etc..

**AzuraCast version**

Hopefully you will do it in future...
**Host Operating System**

I tried to modify it but I don't know vue as it's developed in vuejs.
**Describe the bug**

**To Reproduce**

It's common and will be reproduced easily.
**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
This seems to be related / the same issue as #3323.

For further updates regarding this problem please follow that issue.
