### ISSUE TITLE
When song title is changed Playlist & Album art not returned by API

### ISSUE THREAD

**Issue by Paulio759** [AzuraCast/AzuraCast#3347]
**Using Docker installation method**
Yes

**AzuraCast version**
AzuraCast 0.10.4
Rolling Release #02b92bf (2020-10-25 14:09)

**Host Operating System**
Debian 10 x86_64

**Describe the bug**
When media information (eg Song title) is modified on audio files from the admin interface the API's nowplaying endpoint returns default the generic album art url and an empty playlist name while the media is playing.
This behaviour has been replicated on the demo site.

**To Reproduce**
Edit song title to cause problem
Revert song title to resolve

**Expected behavior**
Song title changes but not art or playlist field.

**Device(s):**
Win7

**Comment by Vaalyn** [comment]
I have been able to reproduce this on my test installation.

Not sure yet where this is coming from since the media file still has all those fields defined after editing it so it's not an issue of writing the changes to the file.

**Comment by Paulio759** [comment]
@Vaalyn 
This has been consistent now on every track that plays (each track has its own playlist, I upload the MP3, edit title and add image).  I noticed yesterday a track playing and the API was displaying the image & playlist correctly but the track Title was displayed in the Artist field. This seems to have been a one-off as the following tracks returned to original issue. Not sure if this helps at all?

**Comment by Paulio759** [comment]
Is there likely to be a fix for this soon please? There seems to be a number of related issues posted now also.
Thanks.

**Comment by SlvrEagle23** [comment]
@Paulio759 This has been a long-standing issue with AzuraCast, and in a majority of cases it isn't caused by AzuraCast itself but rather the underlying software (SHOUTcast or Icecast) being unable to send better metadata along with the stream than just a single "Title" or Title/Artist combination.

This is often caused when the metadata we're seeing via Icecast doesn't match, for one reason or another, the metadata that we _sent_ to the AutoDJ when cueing the song.

Diagnosing and fixing issues like this is always notoriously difficult for us, which is why we still struggle with it after all these years.

You may notice that there's a pattern to the tracks that aren't loading rich metadata, i.e. they're all named a certain way, or they have unicode characters, or something of the sort. Finding that pattern can sometimes help us figure out the problem.

Unfortunately, this isn't something we can just quickly patch out or fix, though we will gladly accept any pull requests from the community that can help refine how we handle this situation.

**Comment by markus-dark-green** [comment]
In case you need a live environment to analyze the problem. Please contact me. Due to the fact that i am doing svelte frontend dev i can show you the resulting issue.

**Comment by Paulio759** [comment]
@SlvrEagle23 Thankyou for the response. What I find when testing now is that most mp3 files are returning a single "Title" or Title/Artist combination. This is regardless to whether the metadata has been added via Azuracast or the mp3 is a purcased release with full metadata already there. Sometimes randomly an MP3 will display full metadata including image, the same MP3 will then not show the image when played again later. It would suggest that the MP3 metadata isnt the issue, the display results apear to be more random.

**Comment by beefour** [comment]
> 
> 
> I have been able to reproduce this on my test installation.
> 
> Not sure yet where this is coming from since the media file still has all those fields defined after editing it so it's not an issue of writing the changes to the file.

It looks like the "text" field is not being updated, just the title and artist, so when it looks up the media it doesn't match the song_id derived from artist and title:

```
docker exec -it azuracast_mariadb_1 /bin/bash

mysql -hlocalhost -uazuracast -pazur4c457 azuracast

 SELECT song_id,
        text,
        MD5(REPLACE(REPLACE(LOWER(text),'-',' '),' ','')),
        CONCAT(artist,' - ',title),
        MD5(LOWER(REPLACE(REPLACE(CONCAT(artist,' - ',title),'-',''),' ','')))
   FROM station_media
  WHERE id=883\G

Before update:
*************************** 1. row ***************************
                                                               song_id: 5d6685f9c56cdd04d635c7cbed612db3
                                                                  text: Test - Testing
                     MD5(REPLACE(REPLACE(LOWER(text),'-',' '),' ','')): 5d6685f9c56cdd04d635c7cbed612db3
                                            CONCAT(artist,' - ',title): Test - Testing
MD5(LOWER(REPLACE(REPLACE(CONCAT(artist,' - ',title),'-',''),' ',''))): 5d6685f9c56cdd04d635c7cbed612db3

After edit:
*************************** 1. row ***************************
                                                               song_id: 5d6685f9c56cdd04d635c7cbed612db3
                                                                  text: Test - Testing
                     MD5(REPLACE(REPLACE(LOWER(text),'-',' '),' ','')): 5d6685f9c56cdd04d635c7cbed612db3
                                            CONCAT(artist,' - ',title): Test - Testing2
MD5(LOWER(REPLACE(REPLACE(CONCAT(artist,' - ',title),'-',''),' ',''))): 939bde4406fa3deddcd0118f38fc47ad
```

**Comment by markus-dark-green** [comment]
I can reproduce this issue with the query. so how can we fix the update form the text field? Looks like the text field contains the meta data when you upload a file and does not update when you manually correct the attriibutes (overwrite) in the media repository (Music Files)

**Comment by SlvrEagle23** [comment]
I've figured out the cause of this problem and have published two commits that should completely resolve the issue:
 - Updates to the `HasSongFields` trait so if the artist or title are changed, it automatically updates the text and regenerates the appropriate song ID, and
 - A database migration to apply this same fix to any existing records that are out of date, avoiding the need to manually re-edit those files.

This one was difficult to figure out, so I appreciate everyone's patience as we got it worked out.

**Comment by markus-dark-green** [comment]
After update via docker script do i need to run any command to fix the database?

**Comment by beefour** [comment]
@markus-dark-green, it looks like the commit includes an update in the migration scripts:

https://github.com/AzuraCast/AzuraCast/commit/1fbb7a85cd40200eed433062b9c6b1c0a6b80b56

Artwork still behaves mysteriously in the short term but seemed to sort its self out, not sure how its looked up as the unique_id doesn't seem to change

**Comment by Paulio759** [comment]
@SlvrEagle23 The API now returns the correct playlist data but the image is still returning generic_song.jpg"

**Comment by markus-dark-green** [comment]
Since last updates it looks better. In my case only when the playlist is switched i have the same. behavior is constant
