### ISSUE TITLE
Language changes

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#335]
If you change the language to Russian, you do not translate page log in. Why? 
I made a complete translation, but not completely all in my own language?
https://radio.izones.ru/login
Now Russian is installed, but the main page in English.

**Comment by fafamonge** [comment]
I have the same question. I don't know how to change my default language. I want it in english but it is in spanish.

**Comment by SlvrEagle23** [comment]
@fafamonge The default language is determined by what your browser sends to the AzuraCast application, so if you have selected in your browser's preferences to receive English language pages as your first preference, it will serve in English by default. You can always change which language AzuraCast displays in from your personal profile page.
