### ISSUE TITLE
Creating and populating a custom field.

### ISSUE THREAD

**Issue by rleiman** [AzuraCast/AzuraCast#3353]
Greetings,

I wrote and streaming app for a customer and they will be giving me an account on their computer that has AzuraCast on it. My app reads the JSON output of your API.

Can you tell me how to create a custom field and populate it so I can read the value from that field from the API that contains the JSON output?

Thanks in advance.

Truly,
Emad

**Comment by Vaalyn** [comment]
For creating Custom Fields take a look a the entry for Custom Fields on the Swagger API page [from the demo installation](https://demo.azuracast.com/static/api/index.html#/Administration%3A%20Custom%20Fields/post_admin_custom_fields).

You can also take our PHP API client library as an example: https://github.com/AzuraCast/php-api-client/blob/master/src/Admin/CustomFieldsClient.php#L59-L71

Regarding populating them for media files that's done via the `PUT` method for media files: https://azuracast.vaachar.de/static/api/index.html#/Stations%3A%20Media/put_station__station_id__file__id_

via the `custom_fields` field in the JSON that you send with that request, for example if you have a custom field called `test_custom_field`:

```
{
  "id": 1,
  "album": "Test Album",
  "genre": "Rock",
  "lyrics": "...Never gonna give you up...",
  "isrc": "GBARL0600786",
  "length": 240,
  "length_text": "4:00",
  "path": "test.mp3",
  "mtime": 1603976232,
  "amplify": -14,
  "fade_overlap": 2,
  "fade_in": 3,
  "fade_out": 3,
  "cue_in": 30,
  "cue_out": 30,
  "art_updated_at": 1603976232,
  "playlists": [
    null
  ],
  "custom_fields": {
    "test_custom_field": "Test Value"
  }
}
```

**Comment by rleiman** [comment]
Hi,

Unfortunately, I don’t know PHP nor does my customer who needs the custom field. I wrote the app that reads the JSON output in Basic4Android. Creating and populating the custom field needs to be done from inside the AzuraCast software by a non-programmer.

How do I create it from inside the software and how do I populate it also from inside the software?

Truly,
Emad

**Comment by SlvrEagle23** [comment]
@rleiman Custom fields can be managed via System Administration > Custom Fields. Once you've created a custom field, it is available globally across all stations, and will appear when editing any media.

**Comment by rleiman** [comment]
Hi,

Thanks for the info.

While I’m waiting for my customer to grant me a login to his AzuraCast, can you tell me if I can also populate the custom field with a value also from  System Administration > Custom Fields?

Truly,
Emad

**Comment by rleiman** [comment]
Assalam alaikum wr. wb.

AzuraCast confirmed that Custom Fields can be created by going to System Administration > Custom Fields. Can you go to that location and create a custom field called

notifications

and also see if the software will allow you to put a value into that new custom field? When you put a value in there please let me know so I can see if the API will show me the new custom field.

At the time of writing this email to you, the app is still under review. I will check again later tonight.

Wasalam,
Emad

> Begin forwarded message:
> 
> From: Emad-ud-deen Leiman <emadleiman47@gmail.com>
> Subject: Re: [AzuraCast/AzuraCast] Creating and populating a custom field. (#3353)
> Date: 1 November 2020 at 17:15:54 GMT-5
> To: AzuraCast/AzuraCast <reply@reply.github.com>
> 
> Hi,
> 
> Thanks for the info.
> 
> While I’m waiting for my customer to grant me a login to his AzuraCast, can you tell me if I can also populate the custom field with a value also from  System Administration > Custom Fields?
> 
> Truly,
> Emad
>
