### ISSUE TITLE
Regression? Issue known from KH Icecast

### ISSUE THREAD

**Issue by Deiiji** [AzuraCast/AzuraCast#3354]
Hello, again me, this time problem with relays

**Using Docker installation method**

No
**AzuraCast version**

AzuraCast • Rolling Release #02b92bf (2020-10-25 14:09) • Ansible • PHP 7.4
**Host Operating System**

Ubuntu Focal
**Describe the bug**

Azura set as slave/slave relay don't work, stream showing offline or no broadcast at all
**To Reproduce**

Set  azuracast as slave relay to another slave relay (Icecast)
**Expected behavior**

Station relayed
**Relevant Logs**

slave/slave_startup process has 524288 max file descriptor limit

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

There is also an warn about XML parsing:
[2020-10-30  03:37:21] WARN xml/parsing warning: 
[2020-10-30  03:37:21] WARN xml/parsing skipping element "stream-url" parsing "mount" at line 28

**Comment by SlvrEagle23** [comment]
@Xara You mentioned this is known from Icecast-KH...is there a corresponding GitHub issue on the Icecast-KH repo, and have they patched it in a recent version?

**Comment by Xara** [comment]
Yes there is a patch from February, I need to search, later in day I will send link
