### ISSUE TITLE
Songs being played after being unassigned from playlist

### ISSUE THREAD

**Issue by pascalla** [AzuraCast/AzuraCast#3356]
**Using Docker installation method**
Yes

**AzuraCast version**
 Rolling Release #02b92bf (2020-10-25 14:09) 

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
Song is being played even though has been unassigned from the playlist.

**To Reproduce**
1) Upload song
2)  Assign to playlist
3) Unassign from playlist

**Expected behavior**
Never to be played

**Relevant Logs**
2020/10/30 14:24:57 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/***/media/General Rotation/Oasis/Oasis - Wonderwall (Remastered).mp3".
2020/10/30 14:25:37 [truckersfm_next_song:3] Prepared "/var/azuracast/stations/**/media/General Rotation/Oasis/Oasis - Wonderwall (Remastered).mp3" (RID 1).

**Screenshots**
![image](https://user-images.githubusercontent.com/22846433/97721541-77737e00-1ac1-11eb-9e15-fee5c1a75bd0.png)

![image](https://user-images.githubusercontent.com/22846433/97721551-7b9f9b80-1ac1-11eb-8a12-953e5833d482.png)

**Additional context**
The playlists were mass assigned by folder, rather than individually. Not sure if this has an effect.

**Comment by Vaalyn** [comment]
I suspect that the song might have been queued already before you unassigned it from the playlist. How long after you've unassigned the song from the playlist was it played?

**Comment by pascalla** [comment]
> I suspect that the song might have been queued already before you unassigned it from the playlist. How long after you've unassigned the song from the playlist was it played?

I believe these were removed from the playlist earlier this month, longer than the 4-5 song queue (I think this is correct)

**Comment by Vaalyn** [comment]
Do you have any of the `Advanced Manual AutoDJ Scheduling Options` activated on the playlist?

**Comment by pascalla** [comment]
Nope, very simple weighted playlist. I want to try provide more information but struggling to find any relevant logs. 

I'm going to keep an eye on the songs removed from playlists and periodically check song history to ensure this is a current bug. Will update ticket with findings over the coming days/weeks

**Comment by Vaalyn** [comment]
Could you check if the `.m3u` file that AzuraCast generated for your playlist still contains the song?

You can find the playlist files here:
```
/var/lib/docker/volumes/azuracast_station_data/_data/<YOUR_STATION_NAME>/playlists/
```

**Comment by Vaalyn** [comment]
Closing this issue as resolved
