### ISSUE TITLE
Avoid Duplicate Artist won't work with many songs from the same artist in huge playlist

### ISSUE THREAD

**Issue by paratz** [AzuraCast/AzuraCast#3358]
**Using Docker installation method**
Yes

**AzuraCast version**
 Rolling Release #63a2aea (2020-09-14 0:03) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
First of all thanks to the AzuraCast team for such a great tool

I have a playlist called "Mainstream" which hast 1800 songs associated.  The list has the "Avoid Duplicate Artist" enabled, and the song playback order is "Random" (the same problem happens with "Shuffle". 
The playlist has a schedule everyday from 8 to 6, and it will play a lot of songs of the same artist. We can see that this will happen with those artists that have many songs associated. For instance AC/DC hast 30 songs in this playlist, and in a single day it will play 6 different songs, I mean, we love ACDC, but that's too much :)

AzuraCast log will just show the track being selected:

[2020-10-30T20:17:15.710908+00:00]   AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... []   {"station":{"id":2,"name":"Big Sur"}}
--
[2020-10-30T20:17:15.764658+00:00]   AzuraCast.INFO: 1 playable playlist(s) of type "default_scheduled"   found.   {"playlists":[{"id":5,"name":"08a18_0_Mainstream","weight":3}]}   {"station":{"id":2,"name":"Big Sur"}}
[2020-10-30T20:17:15.779893+00:00]   AzuraCast.INFO: Found track that avoids duplicate title and artist.   {"media_id":7842}   {"station":{"id":2,"name":"Big Sur"}}
[2020-10-30T20:17:15.795596+00:00]   AzuraCast.INFO: Playable track found and registered.   {"next_song":"StationMedia 4517df75b68860f1a241263e: AC/DC -   Moneytalks"}   {"station":{"id":2,"name":"Big Sur"}}

I don't see any relevant error or problem in this station.

**To Reproduce**
I don't think any step needs to follow, it just happens on our configuration:

- We've tried re-shuffling the playlist
- change from shuffle to random
- disable the avoid duplicate artists for another playlist with jingles that has the same schedule

**Expected behavior**
Have multiple songs of the same artist and avoid that artist to be played that many times.

**Relevant Logs**
I Don't see any errors in the logs.

**Screenshots**
![image](https://user-images.githubusercontent.com/22793342/97764681-347bcf80-1aee-11eb-9df5-f543b3b1c8bf.png)

![image](https://user-images.githubusercontent.com/22793342/97764706-452c4580-1aee-11eb-8cff-998e93f0cd53.png)

![image](https://user-images.githubusercontent.com/22793342/97764716-4d848080-1aee-11eb-98ad-200305df5fcf.png)

![image](https://user-images.githubusercontent.com/22793342/97764729-59704280-1aee-11eb-9872-b60a87e67f08.png)

![image](https://user-images.githubusercontent.com/22793342/97764738-62f9aa80-1aee-11eb-911f-b33985176bab.png)

for instance, this is the report for today october 30th

![image](https://user-images.githubusercontent.com/22793342/97764771-7c9af200-1aee-11eb-941b-124c6e4bd296.png)

this is the report for October 29th:

![image](https://user-images.githubusercontent.com/22793342/97764797-94727600-1aee-11eb-81ec-2029d94978cd.png)

**Additional context**
I'm not sure where else to check, also I'm not sure if there's a problem with how long the playlist is or the amount of songs for these artist.

Thanks for your help.

**Comment by Vaalyn** [comment]
By default the duplicate prevention is looking at the last 120 minutes.

This timerange is configurable for each station in the `Station Profile` -> `AutoDJ` -> `Duplicate Prevention Time Range (Minutes)` and can currently be set to a maximum of 1440 minutes (which equals 24h).

I'll close this issue since this does not look like it is a bug but just a configuration thing.
If you still see duplicate artists in the timerange after increasing it as necessary please let me know and I'll re-open the issue.

**Comment by paratz** [comment]
Hello @Vaalyn, I'm reaching you because we are still facing this issue.

We've configured the "Duplicate Prevention Time Range (Minutes)" to ~11.5 hours:

![image](https://user-images.githubusercontent.com/22793342/100602825-2e426400-32e3-11eb-8cba-c196b4b8a03b.png)

for instance, we have a list, that will shuffle 84 songs:

![image](https://user-images.githubusercontent.com/22793342/100603030-5e8a0280-32e3-11eb-9021-c5c852ec7a1b.png)

this playlist will run weekly for 2 hours, but during this time it will play 3 songs of the same artist (within those 2 hours):

![image](https://user-images.githubusercontent.com/22793342/100603233-8d07dd80-32e3-11eb-8556-1b10d1a64fac.png)

this is the report for another day:

![image](https://user-images.githubusercontent.com/22793342/100603453-e6700c80-32e3-11eb-8cd5-2f2aaf1c9545.png)

any idea how I can troubleshoot this? 

Thanks for your help,

**Comment by Vaalyn** [comment]
@paratz is this the only playlist configured to play at that time?

When you look at the songs in the playlist, are there enough songs to play 2h without repeating an artist?
I'm asking because when the algorithm can't find a non-duplicate title/artist it will take the least recently played one and play it to avoid dead air if nothing else can be played.

You should be able to see either one or both of the following messages in the `AzuraCast Application Log` when it's not possible to find a song without repeating title or artist and duplicate prevention is activated for all eligible playlists:

- `Duplicate prevention yielded no playable song; resetting song queue.`
- `No way to avoid same title OR same artist; using least recently played song.`

**Comment by paratz** [comment]
Hello @Vaalyn here are my answers:

is this the only playlist configured to play at that time?

**No, we also have 2 other "jingles" playlist that will play evry 4 songs... we've disable the "Avoid duplicate Artist" on this playlist. Las weekend I disabled both jingles playlist, and the same problem happened (repeating artistst)**

When you look at the songs in the playlist, are there enough songs to play 2h without repeating an artist?

**Yes, in this case "RockThe80s" the playlist is 5.7 hours, 2.5 hours are songs that wont repeat an artist, the rest of the songs (49) are distributed amongst 21 other artist... but as you can see... in this case we have one artist with one 3 songs, and it will play all of its songs...**

I'm asking because when the algorithm can't find a non-duplicate title/artist it will take the least recently played one and play it to avoid dead air if nothing else can be played.

You should be able to see either one or both of the following messages in the AzuraCast Application Log when it's not possible to find a song without repeating title or artist and duplicate prevention is activated for all eligible playlists:

Duplicate prevention yielded no playable song; resetting song queue.
No way to avoid same title OR same artist; using least recently played song.

**I'm just checking the logs for the last time, and I don't see any entry like the ones you mentioned, however, if I check the song report, for the last 12 hours... we see that for another playlist, it played 6 songs of the same artist. I have the logs to share if you consider so...**

![image](https://user-images.githubusercontent.com/22793342/100998315-1b759c80-353a-11eb-89df-4db478761c4d.png)


Thanks for your help,
