### ISSUE TITLE
Duplicate Accounts Allowed

### ISSUE THREAD

**Issue by amavarick** [AzuraCast/AzuraCast#336]
The GUI allows for multiple accounts created with the same user name and email address.

Recommend establishing validation for non-duplicate email address either upon completion of the email address field or upon clicking "save changes." to ensure a duplicate value does not already exist in the database before creating the account.

![duplicateaccountemails](https://user-images.githubusercontent.com/20918832/33949177-de7032f0-dff6-11e7-8496-adc79c0f45fa.png)

**Comment by SlvrEagle23** [comment]
@amavarick That's not supposed to be able to happen...e-mail address is supposed to be a unique constraint in the database, and that should throw an exception.

Will look into why it's not enforcing that properly.

**Comment by amavarick** [comment]
I'm using the Ubuntu traditional OS method of install.  Below is background info for you, please advise if you need any additional files/info.

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

Here are the exact commands I use on a base VPS Ubuntu 16.04 OS for installing AzuraCast.

```
passwd
apt install -y sudo nano locales debconf
sudo apt-get update && sudo apt -y upgrade
sudo reboot
sudo apt-get update && sudo apt -y upgrade
sudo apt-get -y autoremove && sudo apt-get -y autoclean
#sudo reboot
sudo dpkg-reconfigure locales
sudo reboot
sudo locale-gen --purge en_US.UTF-8
sudo locale-gen en_US.UTF-8
sudo update-locale LANGUAGE="en_US.UTF-8"
sudo update-locale LANG="en_US.UTF-8"
#sudo update-locale LC_CTYPE="en_US.UTF-8"
#sudo update-locale LC_NUMERIC="en_US.UTF-8"
#sudo update-locale LC_TIME="en_US.UTF-8"
#sudo update-locale LC_COLLATE="en_US.UTF-8"
#sudo update-locale LC_MONETARY="en_US.UTF-8"
#sudo update-locale LC_MESSAGES="en_US.UTF-8"
#sudo update-locale LC_PAPER="en_US.UTF-8"
#sudo update-locale LC_NAME="en_US.UTF-8"
#sudo update-locale LC_ADDRESS="en_US.UTF-8"
#sudo update-locale LC_TELEPHONE="en_US.UTF-8"
#sudo update-locale LC_MEASUREMENT="en_US.UTF-8"
sudo update-locale LC_IDENTIFICATION="en_US.UTF-8"
sudo update-locale LC_ALL=en_US.UTF-8
sudo reboot

############# End Server Pre-Reqs #############################
#Disable IPv6 in /etc/hosts leaving IPv6 loopback
#sudo sed -e 's/^::1/#::1/g' -i /etc/hosts
sudo sed -e 's/^fe/#fe/g' -i /etc/hosts
sudo sed -e 's/^ff/#ff/g' -i /etc/hosts
#sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
#sudo sed -i '/net.ipv6.conf.all.disable_ipv6/d' /etc/sysctl.conf && sudo sed -r "$ a\net.ipv6.conf.all.disable_ipv6 = 1" -i /etc/sysctl.conf
#sudo sysctl -p

#Set SSHD to only listen to IPv4
sudo sed -i 's/^.*ListenAddress 0.0.0.0/ListenAddress 0.0.0.0/' /etc/ssh/sshd_config
sudo sed -i 's/^.*ListenAddress ::/#ListenAddress ::/' /etc/ssh/sshd_config
sudo sed -i 's/^.*Protocol 2/Protocol 2/' /etc/ssh/sshd_config
sudo sed -i 's/^.*ListenAddress ::/#ListenAddress ::/' /etc/ssh/sshd_config
sudo service sshd restart
#End Set SSHD to only listsen to IPv4

#Install automatic Updates
sudo apt -y install unattended-upgrades

#Install Azuracast
apt-get install -q -y git
mkdir -p /var/azuracast/www
cd /var/azuracast/www
git clone https://github.com/AzuraCast/AzuraCast.git .
chmod a+x install.sh
./install.sh
```

**Comment by SlvrEagle23** [comment]
@amavarick It appears somewhere in the `User` model's history, the unique constraint for e-mail address was removed. I'm not sure where, but it definitely needed to be there still!

I've pushed a new commit that will clear out duplicate accounts (with the oldest one surviving), then re-establish the unique constraint so duplicate e-mails can't be used in the future. I've also added exception handling to the Manage Users page to indicate this case in a pretty error.

**Comment by SlvrEagle23** [comment]
(Also, don't mind the Travis tests failing right now, that's a product of the `php7.2-xdebug` package not being out yet.)

**Comment by amavarick** [comment]
I updated the AzuraCast instance, went into user management and the newest duplicate account was removed.  I then attempted to create a duplicate account and it properly flagged.  This appears to be working properly on the traditional Ubuntu install.

```
#Update Azuracast
cd /var/azuracast/www
sudo chmod a+x update.sh
sudo ./update.sh
#End Update Azuracast
```

![duplicateuserexists](https://user-images.githubusercontent.com/20918832/33993805-16c56d78-e0a6-11e7-99ec-e2b9cd80dcb2.png)

**Comment by SlvrEagle23** [comment]
@amavarick Excellent :) Thanks for the report.
