### ISSUE TITLE
Log shoutcast

### ISSUE THREAD

**Issue by radiobellissima** [AzuraCast/AzuraCast#3360]
Hi, I had opened a report some time ago because the shoutcast logs did not correspond to the stations. Closed with no feedback or answers. I wanted to point out that after updating to the latest version the logs are no longer visible with a file not found message.

**Comment by Vaalyn** [comment]
Hey, I've looked into this just now and have removed the `wontfix` label from the original issue and added the `bug` label there. To prevent duplicate issues I'll close this one here and post my findings in the other one.
