### ISSUE TITLE
"Station Overview" and "Listeners Per Station" graph on main Dashboard not updating automatically

### ISSUE THREAD

**Issue by btoplak** [AzuraCast/AzuraCast#3362]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #1f79f86 (2020-10-30 19:10) • Docker • PHP 7.4

**Host Operating System**
Debian 10

**Describe the bug**
UPDATE: After more investigation I found that different issue is with ShoutCast live streams, and another case with the Icecast+AutoDJ. This one describes Shoutcast live streaming issues.

* The number of listeners is not updating on "Station Overview". 
* In the top right corner of station Profile page - Listener count OK.
* In Reports > Listeners report page  - listener count OK

I tried to run the synchronisation task manually `./docker.sh cli sync:run`, then I get an error with call stack, listed below.

**To Reproduce**
Directly visible on Dashboard

**Expected behavior**
Correct numbers of listeners on each page that should display it.

**Relevant Logs**
[01-Nov-2020 22:49:22 UTC] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to App\Console\Command\SyncCommand::__invoke() must be of the type string, null given in /var/azuracast/www/src/Console/Command/SyncCommand.php:10
Stack trace:
#0 [internal function]: App\Console\Command\SyncCommand->__invoke()
#1 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(83): call_user_func_array()
#2 /var/azuracast/www/vendor/mnapoli/silly/src/Application.php(95): Invoker\Invoker->call()
#3 /var/azuracast/www/vendor/symfony/console/Command/Command.php(256): Silly\Application->Silly\{closure}()
#4 /var/azuracast/www/vendor/symfony/console/Application.php(920): Symfony\Component\Console\Command\Command->run()
#5 /var/azuracast/www/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand()
#6 /var/azuracast/www/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun()
#7 /var/azuracast/www/bin/console(18): Symfony\Component\Console\Application->run()
#8 {main}
  thrown in /var/azuracast/www/src/Console/Command/SyncCommand.php on line 10

**Screenshots**
![Dashboard - Correct count](https://i.imgur.com/jkXnEMc.png)
![Stream 3 - Profile page: Correct no. listeners](https://i.imgur.com/rr43x0O.png)
![Stream 3 - Listerners Report page: Correct no. listeners](https://i.imgur.com/bfj5Dru.png)

**Comment by SlvrEagle23** [comment]
@btoplak The command you'd want to run would be `./docker.sh cli sync:run long` to run the one-hour synchronization (which includes analytics loading).

If you see an error when manually running it, paste that here and we can investigate.

**Comment by btoplak** [comment]
> ./docker.sh cli sync:run long

Hi @SlvrEagle23 Tnx for the headsup.

```
/var/azuracast # ./docker.sh cli sync:run long
Starting azuracast_mariadb_1 ... done
Starting azuracast_redis_1   ... done
Starting azuracast_stations  ... done
Starting up AzuraCast services...
Services started up and ready!
[2020-11-12T20:09:58.178403+00:00] AzuraCast.NOTICE: Running sync task: 1-Hour Sync [] []
```
I've done that, but to not avail
No errors. But also no changes in listeners count.

**Comment by kloudxyz** [comment]
I do have the same issue too.

**Comment by SlvrEagle23** [comment]
@btoplak @kloudxyz We need vastly more information than we have right now to be able to fix this issue.

If your statistics or some other part of your system isn't updating, that suggests there's a problem with a sync task not running correctly.

In the latest rolling release version, you should see a notification on your dashboard about this, along with a direct link to run the sync task manually. Manually running the task should inform you of any errors that are encountered.

**Comment by btoplak** [comment]
@SlvrEagle23, thanks for the reply.
Thanks mate, let me upgrade it to the latest one and try to get some more information.

**Comment by btoplak** [comment]
The **AzuraCast Application Log** is being flooded with this error for the "Station 3" in my example - which works Shoutcast remote streamer, which means AutoDJ is not needed, as is disabled in the channel setting.

`[2020-11-29T21:14:16.723504+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":5,"name":"Radio XY"}}
[2020-11-29T21:14:16.724455+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":5,"name":"Radio XY"}}
[2020-11-29T21:14:16.725230+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":5,"name":"Radio XY"}}
`
