### ISSUE TITLE
Shoutcast station with source connected and streaming shows Now Playing as "Stream Offline"

### ISSUE THREAD

**Issue by btoplak** [AzuraCast/AzuraCast#3363]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #1f79f86 (2020-10-30 19:10) • Docker • PHP 7.4

**Host Operating System**
Debian 10

**Describe the bug**
With an MP3 stream source connected and streaming, AzuraCast panel shows in Now Playing field as "Stream Offline"

**To Reproduce**
1. Install and configure Shoutcast.
2. Connect MP3 source and start streaming.
3. Check "Playing Now" field

**Expected behavior**
Either a static text "Station Streaming, but no information sent" or any other suitable text indicating that Stream is Live although without proper metadata.

**Screenshots**
!["Stream Offline" text while source is sending and streaming](https://i.imgur.com/m1l25MM.png)

**Comment by YosefAdPro** [comment]
I also experienced a similar problem.
What client are you working with to connect to sc?

**Comment by btoplak** [comment]
> I also experienced a similar problem.
> What client are you working with to connect to sc?

Winamp plugin

**Comment by reans** [comment]
same problem i countered too. got offline when live DJ connected to the stream.

**Comment by fritexvz** [comment]
Same issue, I was testing it on Ubuntu, using Icecast and streaming via source of my computer through Sound Empire Caster.
While, autodj/streamers and playlists are disabled.

It shows "stream online" only when using autodj/playlists (enabled).
