### ISSUE TITLE
Listener count incorrect on station Profile page and Listener Report page (IceCast + AutoDJ)

### ISSUE THREAD

**Issue by btoplak** [AzuraCast/AzuraCast#3367]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #1f79f86 (2020-10-30 19:10) • Docker • PHP 7.4

**Host Operating System**
Debian 10

**Describe the bug**
This report seems similar to the previos one, but this one describes Icecast + AutoDJ combination with almost inverse bugs in listeners count display.

The correct counts are as follows: 35 listeners total, with all listeners being behind the same router, but two different User-Agent strings. This means one unique IP and 2 different User-Agents, so A.C. counts them as "2 unique". Is that working as intended?

* The number of listeners is updating correctly on "Station Overview" page. (Image 1)
* In the top right corner of station Profile page the total listeners count is wrong. It shows unique listeners count in both fields. (Image 2)
* In Reports > Listeners report page the count of total listeners is also wrongly displayed, it shows only unique count.  (Image 4)
* In Reports > Song Playback Timeline the total count is updated correctly  (Image 4)

I tried to run the synchronisation task manually `./docker.sh cli sync:run`, then I get an error with call stack, listed below.

**To Reproduce**
Icecast + AutoDJ channel
Directly visible on Dashboard

**Expected behavior**
Correct numbers of listeners on each page that should display it.

**Relevant Logs**
[01-Nov-2020 22:49:22 UTC] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to App\Console\Command\SyncCommand::__invoke() must be of the type string, null given in /var/azuracast/www/src/Console/Command/SyncCommand.php:10
Stack trace:
#0 [internal function]: App\Console\Command\SyncCommand->__invoke()
#1 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(83): call_user_func_array()
#2 /var/azuracast/www/vendor/mnapoli/silly/src/Application.php(95): Invoker\Invoker->call()
#3 /var/azuracast/www/vendor/symfony/console/Command/Command.php(256): Silly\Application->Silly\{closure}()
#4 /var/azuracast/www/vendor/symfony/console/Application.php(920): Symfony\Component\Console\Command\Command->run()
#5 /var/azuracast/www/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand()
#6 /var/azuracast/www/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun()
#7 /var/azuracast/www/bin/console(18): Symfony\Component\Console\Application->run()
#8 {main}
  thrown in /var/azuracast/www/src/Console/Command/SyncCommand.php on line 10

**Screenshots**
![Dashboard - Correct count](https://i.imgur.com/X6EKfMF.png)
![Stream 1 - Profile page: Incorrect no. of listeners](https://i.imgur.com/X05Fp39.png)
![Stream 1 - Listerners Report page: Incorrect no. listeners](https://i.imgur.com/NUAWaOw.png)
![Stream 1 - Song Playback Timeline: Correct no. listeners](https://i.imgur.com/IIjZrJs.png)

**Comment by trentnetau** [comment]
This hasn't been solved, the most recent update.

Since updating my Docker to v0.18.5 Stable my stream keeps showing numbers of over 20+ when there is actually only 8-13 listening.
