### ISSUE TITLE
No file artwork while Manual AutoDJ ON

### ISSUE THREAD

**Issue by kgguru** [AzuraCast/AzuraCast#3368]
Ubuntu 19

Installation Docker.

AzuraCast Rolling Release #4f994ed (2020-11-02 1:41)

When Auto DJ is in Manual mode the file artwork is getting the Azuracast "Blue Note" and the file timer is not visible. Everything goes to normal when AutoDJ Manual mode is off.

**Comment by ErnestPH** [comment]
I can verify that this is happening...
