### ISSUE TITLE
(Feature Request) Streaming to Youtube Live

### ISSUE THREAD

**Issue by ghost** [AzuraCast/AzuraCast#337]
Would be better to stream with their thumbnails too.
I tried to use ffmpeg to make it done but it's quite buggy and unstable.
Hope this can be default feature in AzuraCast!

**Comment by ckeurk** [comment]
I also look forward to seeing this function in Azuracast 👍

**Comment by dagors** [comment]
Maybe this example can help, use ffmpeg:

`avconv -loop 1 -i /MUSIC/xt-hd.png -i http://localhost:8080/mp3 -r 30 -acodec aac -strict -2 -c:v libx264 -strict experimental -b:a 128k -pix_fmt yuvj444p -b:v 256k -minrate 128k -maxrate 512k -bufsize 768k -f flv rtmp://a.rtmp.youtube.com/live2/[KEY]`

http://akos.me/2017/stream-icecast-stream-to-youtube/

**Comment by SlvrEagle23** [comment]
Building in streaming to YouTube live would require that AzuraCast supports video, which it currently does not. 

I have one radio station I've worked with that uses a rather simple shell script along with ffmpeg to include a repeating video and the now-playing text from AzuraCast's API. I've created a Gist with the code we use to do this:
https://gist.github.com/SlvrEagle23/17b2b550f9340c9dd32f4bcd5b128442
