### ISSUE TITLE
Adding a custom value to a custom field within AzuraCast

### ISSUE THREAD

**Issue by rleiman** [AzuraCast/AzuraCast#3371]
Greetings,

I created a custom field within AzuraCast but I did not see any entry field on that screen to put a value into the field. The only thing I saw was a dropdown list that puts metadata information from the song mp3 file into the field.

Where in AzuraCast can a DJ or the Administrator of the radio station put a value into the custom field. The solutions can't have anything to do with programming languages. This needs to be populated by people who are not programmers.

Here's what we want to do with the custom field. The custom field is called Notifications and it shows up in the now playing API. As an example, we want to put the line of words shown after this paragraph into the custom field:

This is a test notification.

This needs to all be done only within AzuraCast by a DJ or the Administrator.

Please let me know what area within AzuraCast this can be done.

Thanks in advance.

**Comment by rleiman** [comment]
<img width="1280" alt="Screenshot 2020-11-03 at 11 56 16" src="https://user-images.githubusercontent.com/73354593/98018655-cf1a2e00-1dce-11eb-8b8a-52dd0e15d0b7.png">

**Comment by SlvrEagle23** [comment]
@rleiman Custom fields are associated with media. Once you've added a custom field, it will show up in the "Edit Media" dialog box that appears when clicking "Edit" next to any media in any station's media manager.

As we've said before, there is currently no way inside the AzuraCast UI to set a custom API value on a per-station basis, only on a per-media-file basis. To add this functionality would require custom code using a plugin, which would not be something we could assist with directly via this GitHub.

There is no need to continue opening up GitHub issues regarding this. Based on some of your replies, I suspect you're working with a customer who has a specific requirement that doesn't exist in AzuraCast currently, and this should be your responsibility via custom code (not ours as the project maintainers) to implement for them.

**Comment by rleiman** [comment]
Hi,

Looking at the menus on the left I don’t see the Media Manager listed. How do I navigate to it or how do I get it listed in the menu? I also checked under Utilities and it wasn’t there either.

All help will be appreciated.

Thanks in advance.

Truly,
Emad

**Comment by SlvrEagle23** [comment]
@rleiman It is the "Music Files" section under each station. When editing any specific track, you will see the custom fields you've created.

As I've said before, though, this does not let you create station-wide custom fields that appear in API calls. This is not a currently implemented feature.

**Comment by rleiman** [comment]
Hi,

Thanks. Found it.

It doesn’t matter about the station by station bases as long as we can access that dialog so we can populate that field when the song plays is perfect for us.

Truly,
Emad
