### ISSUE TITLE
Setting up my VPS

### ISSUE THREAD

**Issue by giovanni256** [AzuraCast/AzuraCast#3372]
Hi there. 
I want to run my webradio through Azura Cast on a VPS, but I need to know some information about how much space Azura Cast requires. 

First of all, since I want to run only one station on my VPS, I'm looking for a cheap solution with a space of 20GB SSD a 1vCPU 1 RAM or 2 RAM.

Is it enough?
I will run the AutoDJ with about 5GB of tracks. 

I'm sorry for the tag "idea", but I tried to search these information via Google.

Thanks in advance!

**Comment by SC2Mitch** [comment]
hello @giovanni256 

System Requirements are: 
A 64-bit x86 (x86_64) CPU
2GB or greater of RAM
20GB or greater of hard drive space
A computer/server capable of running Docker

Generally a 50gb SSD should be okay

**Comment by ErnestPH** [comment]
It's here - https://www.azuracast.com/install/ a one click install using Digital Ocean and Linode are also available...
