### ISSUE TITLE
to improof auto dj request song.

### ISSUE THREAD

**Issue by aimanlinux180203** [AzuraCast/AzuraCast#3374]
Hi. I want to ask why when many songs request at auto dj like over 20 request, the jingles play list cannot be played. So how can i solve this problem like make the jingles can be played while many request is queuing. I hope some one can help me to solve this problem. One more think I want to ask, how can I creat my own link at the azuracast public page at my radio station like I want to put my facebook link at the web page. Some one whoo can help me can contact me using the email aimannizam41@gmail.com thanks alots.

**Comment by aimanlinux180203** [comment]
@

**Comment by officialgamerfm** [comment]
i am having the same problem. is there a workaround?

**Comment by aimanlinux180203** [comment]
yes. It's work, but just only for if the request less than 10 songs,
but if the request more than 10 songs, it will block the jingles to be
play. I hope you can help me to solve this problem. thank you

**Comment by officialgamerfm** [comment]
> yes. It's work, but just only for if the request less than 10 songs, but if the request more than 10 songs, it will block the jingles to be play. I hope you can help me to solve this problem. thank you
> […](#)
> On 06/11/2020, officialgamerfm ***@***.***> wrote: i am having the same problem. is there a workaround? -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#3374 (comment)](https://github.com/AzuraCast/AzuraCast/issues/3374#issuecomment-723103967)

mine jingles arent even playing when its less then 10.

**Comment by officialgamerfm** [comment]
can anyone provide any workaround for this? to force the jingles to play inbetwen requests.

**Comment by aimanlinux180203** [comment]
it's not work. I hope you can fix this problem
