### ISSUE TITLE
Clearing cache through CLI while viewing a station page floods logs / doesn't send them back to /login

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#3376]
**Using Docker installation method**
Yes

**AzuraCast version**
Tested on both #deb5ecd and #1f79f86 Rolling Releases. 

**Host Operating System**
Ubuntu 20.04 

**Describe the bug**
Whenever a administrator clears AzuraCast's cache and users are still viewing a station Profile `domain.com/{station_code}/name` it sends the nginx_proxy a bit insane in the brain, causing a overwhelming log flood because of the cleared cache, the exact cause of this issue was easily located, thankfully. (Please note this was not caused by a bot, but a user) 

This is because when a cache is cleared and a user is viewing the page a `NowPlaying` sync runs, when this happens it seems to tag the user with the out of date cache and attempts to force it back to the `/login` page, but this obviously isnt working as intended. As shown in the logs, the API runs on the station, then it picks it up with a out of date cache (assuming thats how its causing the spam) 

**To Reproduce**
-View a station
 -Clear the cache through CLI `./docker.sh cli clear:cache` (Keep a page or two of any station in a browser) 
-Review log flood

**Expected behavior**
Not such a huge log flood upon clearing a cache or better ways to handle the cache being cleared. 

**Relevant Logs**
Consider this, but at a huge volume per second.
```
nginx_proxy_1              | nginx.1    | crosshost.ml snip - - [05/Nov/2020:01:57:58 +0000] "GET / HTTP/2.0" 302 0 "https://crosshost.ml/station/59/profile" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0"
nginx_proxy_1              | nginx.1    | crosshost.ml snip - - [05/Nov/2020:01:57:58 +0000] "GET /login HTTP/2.0" 200 1503 "https://crosshost.ml/station/59/profile" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0"
nginx_proxy_1              | nginx.1    | crosshost.ml snip - - [05/Nov/2020:01:57:58 +0000] "GET /api/station/59/profile HTTP/2.0" 302 0 "https://crosshost.ml/station/59/profile" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.
```
**Screenshots**
Video of the issue - https://puu.sh/GKbOg/de98cc7e18.mp4
**Device(s):**
 - Device: Desktop
 - OS: Windows 10 
 - Browser: Edge
 - Version: Latest version. 

**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch Recent updates to the code have improved how errors are returned from API calls, including preventing users from being redirected to the `login` page if they're making XMLHttpRequests.

After the cache is cleared, the API call will still fail with a 403, but it should fail gracefully without a redirect to the `/login` endpoint, thus avoiding a log flood.
