### ISSUE TITLE
AzuraCast CPU 

### ISSUE THREAD

**Issue by NurKai3** [AzuraCast/AzuraCast#3377]
Hello,
i have installed AzuraCast on a KVM server (ubuntu-20.04), which has 4 vCores, 4 GB Ram and 50 GB SSD with one station, which should be enough However, when the station updates the title, the CPU on all 4 cores goes up to 30-60% for no apparent reason. I have already reinstalled the KVM server several times and AzuraCast, unfortunately nothing helped.

**Comment by SC2Mitch** [comment]
When a now playing runs it generally is fairly CPU intensive, I'll look into why it requires that much power however

**Comment by NurKai3** [comment]
Thank you

**Comment by NurKai3** [comment]
https://imgur.com/hIzdPEd this is from htop. It is a moment of it, the whole VPS then lies in the 1-2s.

**Comment by YosefAdPro** [comment]
As it seems your host computer is weak.
