### ISSUE TITLE
SSL problems with EMBEDs

### ISSUE THREAD

**Issue by ttodua** [AzuraCast/AzuraCast#3379]
AzuraCast gives us player embed code, with custom port:
`<iframe src="http://example.com:8123/public/myRR/embed" frameborder="0" allowtransparency="true" style="width: 100%; min-height: 150px; border: 0;"></iframe>`

However, when we embed that in our website, it doesn't show up, because our website is in HTTPS:// and browsers say (in console errors) that `http://` iframes are not allowed on `https` websites. So, the problem is that radio link are not able to have `HTTPS` at **8123** custom ports (because of LetsEnctypt only works on 80/443 ports). So, what are solutions in such cases?

I've heard somewhere on forums how to "trick" to allow letsencrypt work on custom ports, however, it turnes out much techsavy implementation.  Can you implement something, that will deal with this problem, that many people might be facing?

**Comment by ErnestPH** [comment]
Solution. Install a Azuracast droplet in Digital Ocean one click install. Then add SSL. That should fix your problem...

**Comment by ttodua** [comment]
> Solution. Install a Azuracast droplet in Digital Ocean one click install. Then add SSL. That should fix your problem...

Can you give a bit more details? Only part of people use DigitalOcean. We don't use. So, what should we do?

**Comment by YosefAdPro** [comment]
If you install LetsEncrypt on the server, the icecast will use the same certificate.

If you are using Docker below is a guide
(https://www.azuracast.com/extending/letsencrypt.html#using-a-custom-certificate) 

You can also work with NGINX proxy and then you will not need SSL on ICECAST.

**Comment by Vaalyn** [comment]
Not being able to use non-ssl iframes on HTTPS websites is a browser restriction so there is nothing that we can do to circumvent this.

As the Let's Ecrypt ACME protocol also only works on the default ports 80/443 there is not really something we can do there to enable LE certificates on non-standard ports.

If you are not able to use the standard ports for AzuraCast you will have to use your own SSL certificate: https://www.azuracast.com/extending/modifying-docker.html#common-examples
