### ISSUE TITLE
No conect demo

### ISSUE THREAD

**Issue by vdjkelly** [AzuraCast/AzuraCast#338]
No se si me entienda el idioma pero llevo rato tratando de conectar el demo y no contecta cree la cuenta para dj y probar el stream y no conecta 

![noconect](https://user-images.githubusercontent.com/5873347/33997223-14aa0364-e0ba-11e7-8022-452c23f6f67b.png)
![nocomnect2](https://user-images.githubusercontent.com/5873347/33997267-3427d0e0-e0ba-11e7-97ff-b7b22f4789db.png)

**Comment by SlvrEagle23** [comment]
@vdjkelly Hello! The demo site is just for exploring the web interface of AzuraCast; it's not actually intended to accept incoming broadcasts, and the ports that would allow that are locked down on the box, to avoid someone being able to take over the demo radio stream entirely.

**Comment by vdjkelly** [comment]
![whatsapp image 2017-12-14 at 11 35 53 am](https://user-images.githubusercontent.com/5873347/34000320-55d2c336-e0c3-11e7-9135-c344e40640b0.jpeg)
@SlvrEagle23 En realidad tengo un proyecto montado en amazon y tampoco me conecta y los puertos están abiertos 
![whatsapp image 2017-12-14 at 11 35 20 am](https://user-images.githubusercontent.com/5873347/34000316-522f5b0e-e0c3-11e7-83af-83862c9b872d.jpeg)
