### ISSUE TITLE
artist & song titles reset during cover upload

### ISSUE THREAD

**Issue by InstabilSpielt** [AzuraCast/AzuraCast#3382]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #02b92bf

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
Since a short time the artist & song title are deleted when I upload a cover.

**To Reproduce**
1. go to music files
2. then click on edit
3. upload album cover

If you try to download the song now, the meta data will be completely reset.

**Comment by Vaalyn** [comment]
Closing as fixed per my PR.
