### ISSUE TITLE
There is a problem adding music to the playlist

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#3384]
**Using Docker installation method**
Ansible

**AzuraCast version**
#deb5ecd

**Host Operating System**
Ubuntu 18.04 LTS

**Describe the bug**
There is a problem adding music to the playlist. Nothing is visible when the insert is confirmed. CPU is used too much.

**To Reproduce**
1. Go to 'Music Files'
2. Select All Music Files
3. Click on 'Save'
4. Nothing happens

**Relevant Logs**
I don't know which records to add.

**Device(s):**
 - Device: PC
 - OS: Window 10
 - Browser: Chrome
 - Version: Latest

**Additional context**
I know there is no official support for Ansible. A similar issue may apply to Docker. Thanks for everything.

**Comment by YosefAdPro** [comment]
After step 2 you need to choose which playlist to add the files to.
Did you do that?

**Comment by ogrenci01** [comment]
@YosefAdPro 

I have been using AzuraCast for more than two years. Of course I did.

**Comment by h4de5** [comment]
same problem here. 
when selecting a directory to a playlist the `api/station/1/files/batch` is called - which results in this error:

```
{"code":0,"message":"The EntityManager is closed.","formatted_message":"The EntityManager is closed.","extra_data":[],"success":false}
```

Request data:
```
{"do":"playlist","playlists":[21],"new_playlist_name":"","files":["downloads/2020"],"file":"downloads"}
```

**Comment by SlvrEagle23** [comment]
@ogrenci01 I recently rewrote the batch processor to be significantly more memory-efficient with large volumes of records and to improve the error reporting and reliability of the batch functions. This should resolve this issue completely. Please update to the latest rolling-release version and let me know.
