### ISSUE TITLE
Duplicate Songs page doesn't load

### ISSUE THREAD

**Issue by officialgamerfm** [AzuraCast/AzuraCast#3385]
**Using Docker installation method**
yes

**AzuraCast version**
latest as of november 8th 2020 #deb5ecd

**Host Operating System**
ubuntuy i think , using shoutca.st as host

**Describe the bug**
Duplicate songs page fails to load when i upload muitple large folders to via sftp. only way to fix it is to delete the WHOLE library and upload one folder at a time. But even then at some point it stops working properly. 

1. go to sftp client
2. upload 40+ large folders
3. refresh page 
4. click on duplicate songs 

**Expected behavior**
expect to be able to see all duplicate songs in library

I believe this issue has been reported in the passed but still seeems to be an issue.

**Comment by SC2Mitch** [comment]
Will be testing in a moment.

**Comment by officialgamerfm** [comment]
cool thanks

**Comment by Vaalyn** [comment]
If you are still experiencing this issue could you post you `AzuraCast Application Log` from the time where you have seen that error. This might be a resource problem that can be fixed by tuning some environment variables.

**Comment by SlvrEagle23** [comment]
The duplicate songs report has been folded into the main Media Manager (to allow you to directly edit metadata, view custom fields, and do the other things that are only possible via the main Media Manager while managing duplicate tracks), so this issue should no longer apply as the standalone page no longer exists.
