### ISSUE TITLE
ERROR 500 on download large Playback Timeline report.

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#3389]
**Using Docker installation method**
Yes

**AzuraCast version**
 Rolling Release #02b92bf (2020-10-25 14:09)
Rolling Release #7fa7ca7 (2020-10-22 7:18)

**Host Operating System**
Ubuntu 16.04
Ubuntu 20.04
Ddedicated (not vps) server with 12 cpu cores and 64G ram.

**Describe the bug**

When trying to download the playback report of 14 days (via API) i'm  getting error 500. Also when trying to get the report on screen receiving error 500 or nginx time out. (../api/station/01/history)

**Comment by SC2Mitch** [comment]
Hi @eranwo 

Can you check your docker logs when you try to download the files and paste the error or WARN log in here? 

A successful connection would return something like this:
```
nginx_proxy_1              | nginx.1    | radio.crosshosting.tk IP REDACTED- - [10/Nov/2020:01:49:03 +0000] "GET /api/station/37/history HTTP/2.0" 200 581148 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36 Edg/86.0.622.63"
```

Errors are fairly clear, they have [ERROR] or `web_1 |  Error`

**Comment by walterdevos** [comment]
Same here
I get this message in LOG:
`web_1                      | 2020/12/01 20:14:26 [error] 59#59: *4911081 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 32768 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 129" while reading response header from upstream, client: 172.21.0.4, server: localhost, request: "GET /api/station/13/history HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "radio.xxxxredactedxxxxxx.link"`

( Docker install , stable version v0.10.4 Stable • Docker • PHP 7.4 )

I ran the 1 hour sync. But that did not resolve the issue.

There are 698 songs in that station.

**Comment by walterdevos** [comment]
The error goes away if I add a rowcount parameter like this:
api/station/13/history**?rowCount=50**

**Comment by Vaalyn** [comment]
Regarding the `Allowed memory size of 268435456 bytes exhausted` error, you can increase the allowed memory for PHP via the following environment variable in the `azuracast.env`:

```
# PHP's maximum memory limit.
# PHP_MEMORY_LIMIT=128M
```

**Comment by SlvrEagle23** [comment]
This should now be resolved as of the latest rolling release update, which significantly improves this report's ability to handle large datasets without running out of memory.
