### ISSUE TITLE
new install azuracast  transmission does not listen to the transmission

### ISSUE THREAD

**Issue by linuxserver501** [AzuraCast/AzuraCast#339]
greetings I hope everything can help me I have made a new installation in a digital vps eleven azuracast manages to install everything without errors is created everything I put to transmit but not heard only leaves the letter or the tag of the subject but the audio does not come out should

**Comment by ismail00b** [comment]
The issue is produced if you install ssl, try to access your station by using only http:// ...
@SlvrEagle23 Th icecast server is not checking if the ssl is enabled or not, so is always on normal http, try to fix this. thanks for your great work

**Comment by SlvrEagle23** [comment]
@linuxserver501 @ismail00b If you're using a secure connection and using an Icecast server, ideally the server would use the same SSL configuration as the host. For some reason, this isn't working correctly in our system, and we're unsure of why.

For now, I've reverted to the previous setting, where AzuraCast will automatically proxy Icecast stations through its own SSL webserver (guaranteeing that the SSL information matches).

This should fix any issues related to being on a secure connection and using Icecast.
