### ISSUE TITLE
Problems with autodj playlists

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#3391]
I set up a playlist to play every 2 songs and the second playlist to play every 10 songs is no longer following this rule, the second playlist is playing every 2 songs like the first one and no matter what value is entered. The third playlist I put to play every hour more plays every 2 songs just like the first one and no matter what value is inserted.

Ubuntu 20.04
Version 0.10.4

**Comment by RossFlys** [comment]
Hi @roger-net,

Can you provide the logs for the station please. This will give myself and @Azuracast a understanding of what is happening and why your station's output is not following the rules.

Thanks,

Ross

**Comment by roger-net** [comment]
> Hi @roger-net,
> 
> Can you provide the logs for the station please. This will give myself and @AzuraCast a understanding of what is happening and why your station's output is not following the rules.
> 
> Thanks,
> 
> Ross

Hello Ross, in my tests I just discovered that when I activate the "manual autodj" function the problem goes down well but some mistakes still happen, if the "manual autodj" is disabled, as is standard, the playlist is all messed up.

**Comment by RossFlys** [comment]
If you have activated the manual AutoDJ, and you have replicated the same issue as before, the I would suggest using the ./docker.sh self_update function. 

If you are still experiencing problems, try to restart LiquadSoap. 

-Ross

**Comment by roger-net** [comment]
> If you have activated the manual AutoDJ, and you have replicated the same issue as before, the I would suggest using the ./docker.sh self_update function.
> 
> If you are still experiencing problems, try to restart LiquadSoap.
> 
> -Ross

I already did that and it didn't solve the problem. Autodj has a bug.

**Comment by roger-net** [comment]
I realized that when the short jingles he plays two in the sequence and when the jingles are bigger he plays one that would be right, I have jingles that I put between the songs and these are the ones that he plays two and the normal would be just one.
