### ISSUE TITLE
5 minute sync throws a [Semantical Error] line 0, col 87 near 'station = :station ': Error: Class App\Entity\StationMedia has no field or association named station

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#3395]
**Using Docker installation method**
Yes 

**AzuraCast version**
Rolling Release #9348f84 (2020-11-10 15:07

**Host Operating System**
Ubuntu 20.04 

**Describe the bug**
When a 5 minute sync is ran, a Semantical error is thrown in the logs, making the task unable to complete. I've noted also that several stations appear to restart when the check is ran, unsure of the reason why. Logs and pictures are provided. 

Also along with this, a 1 hour sync is unable to be completed. I did not note any of this during live testing this release. 

**To Reproduce**
Go to Admin Settings
Run a 5 minute sync
Review the error and logs. 

**Expected behavior**
The sync to complete accordingly, the error to not be thrown. 
**Relevant Logs**
```
web_1                      | In QueryException.php line 65:
web_1                      |
web_1                      |   [Semantical Error] line 0, col 87 near 'station = :station
web_1                      |   ': Error: Class App\Entity\StationMedia has no field or association named s
web_1                      |   tation
web_1                      |
web_1                      |
web_1                      | In QueryException.php line 43:
web_1                      |
web_1                      |   SELECT
web_1                      |               sm
web_1                      |               FROM App\Entity\StationMedia sm
web_1                      |               WHERE sm.station = :station
web_1                      |               AND sm.path LIKE :path
web_1                      |
web_1                      |
web_1                      | sync:run [<task>]
```
**Screenshots**
![image](https://user-images.githubusercontent.com/29955942/98697786-330f9a00-236d-11eb-8d60-eb45858dd0f0.png)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch Found the error (has to do with playlists being assigned to folders); should be fixed once the latest update rolls up.
