### ISSUE TITLE
Update Failing

### ISSUE THREAD

**Issue by AaronUnmuted** [AzuraCast/AzuraCast#3397]
Hello,

We are attempting to process an update on our server for the latest rolling release, though the following errors are displayed via SSH: http://prntscr.com/vgx62z

This is met by errors when trying to access some stations via AzuraCast: http://prntscr.com/vgx6tc

Any ideas as to what may be causing the update to fail? We initially attempted an update due to receiving "Slim Application Error" repeatedly. 

Huge thanks for your hard work & continued help.

**Comment by SlvrEagle23** [comment]
@AaronUnmuted It appears the database migration for our latest update failed on your installation. If possible, we'd like to take a look at your installation and see what could be causing the problem. The process of investigating database migrations is a fairly complex and involved one, so it will be quite a lot easier if we can just look at the installation directly. So far, this is the first instance that has encountered an error when updating to the latest version.

You can reach out to our team on [Discord](https://azuracast.com/discord) for assistance.

**Comment by rolradio** [comment]
Same problem here unfortunately.
Also the same error message.

**Comment by SlvrEagle23** [comment]
@rolradio Try running:

```
./docker.sh cli dbal:run-sql "INSERT INTO app_migrations SET version='App\\\\Entity\\\\Mig
ration\\\\Version20201010170333', executed_at='2020-11-11 00:00:00', execution_time=0"
```

...and then updating again.

**Comment by rolradio** [comment]
@SlvrEagle23 
Okay that solved the problem. After this command I first got the message: -bash: cd: too many arguments
I just renamed the media folder to a different name. (the media folder contains huge amount of files 950GB) ... restart
And executed the command again, without an error message.
Then the update without error message.
Then rename the file folder, restart everything and after processing the files everything works perfectly again.
Thank you very much.

**Comment by SlvrEagle23** [comment]
It appears the limited number of installations that have had problems are fixed at this point, and the migrations have been tweaked to ensure more stability for future updaters.

As a note, I want to emphasize that anyone with an exceptionally large media library should always make sure to keep regular backups of their AzuraCast configuration (preferably at the whole-server/VPS level), especially if you're on our "rolling release" channel.

**Comment by williambatson** [comment]
Hello Buster - Hate to re-open such an old thread but I've got the same/similar issue with a server you helped me migrate from to Docker last year - is not taking an update and stalling out  or failing at the same Running Database Migrations point in Update
https://gyazo.com/5431e43a6598b8dd88b18662617c08bc

https://gyazo.com/65f0c23b51b9ed86fc98838e41c3a658  <-- any attempt to run any of these manually crashes the server and it shuts down.

I'm afraid to do more at this point on my own as I don't want to lose the stations or data.
