### ISSUE TITLE
Create station with user in few steps

### ISSUE THREAD

**Issue by gabrielgraff** [AzuraCast/AzuraCast#3398]
Hi!

I think AzuraCast is growing a lot and I will be happy to help with donations.

Is there an easy way to create stations and users, without having to assign roles?

For example, create the station and with its user. In few steps.

Like other similar panels.

Thank you!

**Comment by SlvrEagle23** [comment]
@gabrielgraff I believe we've mentioned this on another communications channel, but this is a feature request that would be well-suited for https://features.azuracast.com/ rather than our GitHub issues section here.
