### ISSUE TITLE
Update failed on ansible (table already exist)

### ISSUE THREAD

**Issue by Xara** [AzuraCast/AzuraCast#3400]
Hello, , today some problems with update (streams work PHP gives 500 error of course)

**Using Docker installation method**

No
**AzuraCast version**

Latest rollong
**Host Operating System**

**Describe the bug**

Update fail resulting in streams running but PHP  errors
**To Reproduce**

TASK [azuracast-setup : Run AzuraCast Setup (Update Mode)] *****************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/console azuracast:setup --update", "delta": "0:00:00.373101", "end": "2020-11-11 10:07:25.792932", "msg": "non-zero return code", "rc": 1, "start": "2020-11-11 10:07:25.419831", "stderr": "[error] Migration App\\Entity\\Migration\\Version20201027130404 failed during Execution. Error: \"An exception occurred while executing 'CREATE TABLE storage_location (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(50) NOT NULL, adapter VARCHAR(50) NOT NULL, path VARCHAR(255) DEFAULT NULL, s3_credential_key VARCHAR(255) DEFAULT NULL, s3_credential_secret VARCHAR(255) DEFAULT NULL, s3_region VARCHAR(150) DEFAULT NULL, s3_version VARCHAR(150) DEFAULT NULL, s3_bucket VARCHAR(255) DEFAULT NULL, s3_endpoint VARCHAR(255) DEFAULT NULL, storage_quota BIGINT DEFAULT NULL, storage_used BIGINT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'storage_location' already exists\"\n\nIn AbstractMySQLDriver.php line 57:\n                                                                               \n  An exception occurred while executing 'CREATE TABLE storage_location (id IN  \n  T AUTO_INCREMENT NOT NULL, type VARCHAR(50) NOT NULL, adapter VARCHAR(50) N  \n  OT NULL, path VARCHAR(255) DEFAULT NULL, s3_credential_key VARCHAR(255) DEF  \n  AULT NULL, s3_credential_secret VARCHAR(255) DEFAULT NULL, s3_region VARCHA  \n  R(150) DEFAULT NULL, s3_version VARCHAR(150) DEFAULT NULL, s3_bucket VARCHA  \n  R(255) DEFAULT NULL, s3_endpoint VARCHAR(255) DEFAULT NULL, storage_quota B  \n  IGINT DEFAULT NULL, storage_used BIGINT DEFAULT NULL, PRIMARY KEY(id)) DEFA  \n  ULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB':     \n                                                                               \n  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'storage_loc  \n  ation' already exists                                                        \n                                                                               \n\nIn Exception.php line 18:\n                                                                               \n  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'storage_loc  \n  ation' already exists                                                        \n                                                                               \n\nIn PDOConnection.php line 51:\n                                                                               \n  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'storage_loc  \n  ation' already exists                                                        \n                                                                               \n\nazuracast:setup [--update] [--load-fixtures] [--release]", "stderr_lines": ["[error] Migration App\\Entity\\Migration\\Version20201027130404 failed during Execution. Error: \"An exception occurred while executing 'CREATE TABLE storage_location (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(50) NOT NULL, adapter VARCHAR(50) NOT NULL, path VARCHAR(255) DEFAULT NULL, s3_credential_key VARCHAR(255) DEFAULT NULL, s3_credential_secret VARCHAR(255) DEFAULT NULL, s3_region VARCHAR(150) DEFAULT NULL, s3_version VARCHAR(150) DEFAULT NULL, s3_bucket VARCHAR(255) DEFAULT NULL, s3_endpoint VARCHAR(255) DEFAULT NULL, storage_quota BIGINT DEFAULT NULL, storage_used BIGINT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB':", "", "SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'storage_location' already exists\"", "", "In AbstractMySQLDriver.php line 57:", "                                                                               ", "  An exception occurred while executing 'CREATE TABLE storage_location (id IN  ", "  T AUTO_INCREMENT NOT NULL, type VARCHAR(50) NOT NULL, adapter VARCHAR(50) N  ", "  OT NULL, path VARCHAR(255) DEFAULT NULL, s3_credential_key VARCHAR(255) DEF  ", "  AULT NULL, s3_credential_secret VARCHAR(255) DEFAULT NULL, s3_region VARCHA  ", "  R(150) DEFAULT NULL, s3_version VARCHAR(150) DEFAULT NULL, s3_bucket VARCHA  ", "  R(255) DEFAULT NULL, s3_endpoint VARCHAR(255) DEFAULT NULL, storage_quota B  ", "  IGINT DEFAULT NULL, storage_used BIGINT DEFAULT NULL, PRIMARY KEY(id)) DEFA  ", "  ULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB':     ", "                                                                               ", "  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'storage_loc  ", "  ation' already exists                                                        ", "                                                                               ", "", "In Exception.php line 18:", "                                                                               ", "  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'storage_loc  ", "  ation' already exists                                                        ", "                                                                               ", "", "In PDOConnection.php line 51:", "                                                                               ", "  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'storage_loc  ", "  ation' already exists                                                        ", "                                                                               ", "", "azuracast:setup [--update] [--load-fixtures] [--release]"], "stdout": "\nAzuraCast Setup\n===============\n\nWelcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...\n * Environment: Production\n * Installation Method: Ansible\n\n ! [NOTE] Running in update mode.                                               \n\nMigrating Legacy Configuration\n------------------------------\n\nConfiguration already set up.\n\n\nRunning Database Migrations\n---------------------------\n\n[notice] Migrating up to App\\Entity\\Migration\\Version20201109203951", "stdout_lines": ["", "AzuraCast Setup", "===============", "", "Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...", " * Environment: Production", " * Installation Method: Ansible", "", " ! [NOTE] Running in update mode.                                               ", "", "Migrating Legacy Configuration", "------------------------------", "", "Configuration already set up.", "", "", "Running Database Migrations", "---------------------------", "", "[notice] Migrating up to App\\Entity\\Migration\\Version20201109203951"]}
**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Xara** [comment]
Frontend give:
Property App\Entity\Station::$radio_media_dir does not exist
RuntimeReflectionService.php : 75

**Comment by SlvrEagle23** [comment]
@Xara This error is likely caused because this is the second update attempt after a failed first migration. If we had the details of the first migration log, we could probably help diagnose the issue, but as it is the only way we could fix the installation would be to directly access it and examine the state of the database versus where it should be.

We only have two reports of failed migrations so far from this update, but until we can do this more detailed investigation with one of the stations we can't fix whatever is causing it. If you're okay with us taking a look at your particular installation, please reach out to us via [Discord](https://azuracast.com/discord) and let us know.

**Comment by Xara** [comment]
I have joined discord,  message me your public key (openssh format) and I will add you to access file...

**Comment by SlvrEagle23** [comment]
@Xara Try running:

```
php /var/azuracast/www/bin/console dbal:run-sql "INSERT INTO app_migrations SET version='App\\Entity\\Mig
ration\\Version20201010170333', executed_at='2020-11-11 00:00:00', execution_time=0"
```

and then updating.

**Comment by Xara** [comment]
Still same error but you can see it now

**Comment by SlvrEagle23** [comment]
Worked with the initial reporter to resolve this issue individually for their instance.
