### ISSUE TITLE
docker.sh backup --exclude-media 

### ISSUE THREAD

**Issue by modularstation** [AzuraCast/AzuraCast#3402]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.4 Stable

**Host Operating System**
Ubuntu 20.04.1

**Describe the bug**
docker.sh script does not take into account the --exclude-media argument in the backup command.

**Comment by SlvrEagle23** [comment]
@modularstation I looked into it, and there's a weird problem with the order of operations in the backup command, so it *has* to be in this order:

```
./docker.sh backup path.zip --exclude-media
```

...otherwise it won't parse correctly.

**Comment by Vaalyn** [comment]
Updated the command on the docs page about backups.

Closing as resolved
