### ISSUE TITLE
Sound Proccesing

### ISSUE THREAD

**Issue by Xhyt777** [AzuraCast/AzuraCast#3403]
Can Someone explain me Sound Processing with Stereo Tool?
(I´am new at AzuraCast)

thank you!

**Comment by Vaalyn** [comment]
As StereoTools is a proprietary third-party software that we don't ship with AzuraCast we are not providing any support for it.

There has been a thread about StereoTools from 2019 though where you can see how to pipe the signal through StereoTools and some discussion about this topic (no guarantee that this works properly though): https://github.com/AzuraCast/AzuraCast/issues/1570

There is also a feature request for StereoTool support here https://features.azuracast.com/suggestions/111122/stereotool-integration
