### ISSUE TITLE
Boxbilling-Modul

### ISSUE THREAD

**Issue by Radio-Quergedacht** [AzuraCast/AzuraCast#3405]
Module for auto creation service through Boxbilling billing system
Link https://www.boxbilling.com/

**Comment by Vaalyn** [comment]
This is neither a feature request (which would have to go to https://features.azuracast.com/) nor a bug/issue report.

Please don't create issues asking for developing a completely new software/plugin/module for a software that is not related to this project in our GitHub issues.
