### ISSUE TITLE
How to hide mount points?

### ISSUE THREAD

**Issue by grupoexperiencia** [AzuraCast/AzuraCast#3409]
**I would like to know how I can hide the mountpoints page in azuracast, that is if for example you put IP: 8020 you get all the mountpoints, audiences and others, and I would like to hide that page or at least show other content such as an image or text .

Thanks in advance, regards.**

**Comment by Vaalyn** [comment]
Edit the mount point you want to hide and add the following config to the `Advanced Custom Frontend Configuration`:
```
<hidden>1</hidden>
```

This will hide the mount point on the IceCast status page.
