### ISSUE TITLE
Ansible Composer 2 conflict with wikimedia/composer-merge-plugin on stable branch

### ISSUE THREAD

**Issue by webafrancois** [AzuraCast/AzuraCast#3411]
**Using Docker installation method**
No, using in a VM in Proxmox VE

**AzuraCast version**
stable with the install doc with ansible

**Host Operating System**
Ubuntu server 20.04 

**Describe the bug**
In the ./install.sh , I've got this error in red.

> fatal: [localhost]: FAILED! => {"changed": true, "cmd": "composer install --no-dev --optimize-autoloader", "delta": "0:00:00.136685", "end": "2020-11-13 14:09:41.977258", "msg": "non-zero return code", "rc": 2, "start": "2020-11-13 14:09:41.840573", "stderr": "Installing dependencies from lock file\nVerifying lock file contents can be installed on current platform.\nYour lock file does not contain a compatible set of packages. Please run composer update.\n\n  Problem 1\n    - wikimedia/composer-merge-plugin is locked to version v1.4.1 and an update of this package was not requested.\n    - wikimedia/composer-merge-plugin v1.4.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.\n\nYou are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.", "stderr_lines": ["Installing dependencies from lock file", "Verifying lock file contents can be installed on current platform.", "Your lock file does not contain a compatible set of packages. Please run composer update.", "", "  Problem 1", "    - wikimedia/composer-merge-plugin is locked to version v1.4.1 and an update of this package was not requested.", "    - wikimedia/composer-merge-plugin v1.4.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.", "", "You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2."], "stdout": "", "stdout_lines": []}

**To Reproduce**

```
sudo apt-get update 
sudo apt-get install -q -y git 
 
sudo mkdir -p /var/azuracast/www 
cd /var/azuracast/www 
sudo git clone https://github.com/AzuraCast/AzuraCast.git . 

# Want only stable "release" builds? Run this code here:
# git checkout -q -f stable
 
sudo chmod a+x install.sh 
./install.sh 
```

**Expected behavior**

```
PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=75   changed=29   unreachable=0    failed=1    skipped=15   rescued=0    ignored=1  
```

**Device(s):**
 - Device: Linux OS with ssh connexion

**Comment by Vaalyn** [comment]
Can confirm this happening on the `stable` branch for Ansible.

This is due to the release of Composer 2 which is automatically installed and conflicts with the version of the composer plugin on the stable branch. In general this is already fixed in the rolling-release (and due to the already existing Docker image also for stable Docker) and would be fixed for Ansible by the next stable release.

At the moment I think you should go with the rolling-release instead of the stable version on Ansible.

**Comment by webafrancois** [comment]
I just should try :
 ```
mkdir-p /var/azuracast/www
cd /var/azuracast/www 
sudo git clone https://github.com/AzuraCast/AzuraCast.git . 
sudo chmod a+x install.sh 
./install.sh 
```
?
It make some trouble too : 

> .../... Upgrading voku/portable-utf8 (5.4.47 => 5.4.50)", "", "                                                                                ", "  [ErrorException]                                                              ", "  file_put_contents(./composer.lock): failed to open stream: Permission denied  ", "                                                                                ", "", "install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]..."], "stdout": "ocramius/package-versions: Generating version class...\nocramius/package-versions: ...done generating version class", "stdout_lines": ["ocramius/package-versions: Generating version class...", "ocramius/package-versions: ...done generating version class"]}

I had remove all my previous /var/azuracast directory before my reinstall and only use root.

I try to launch install another time and it works !

```
PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=92   changed=41   unreachable=0    failed=0    skipped=16   rescued=0    ignored=1   

```

Thanks !

**Comment by Vaalyn** [comment]
With the new `v0.11` release the issue with the conflicting `wikimedia/composer-merge-plugin` is now also resolved on Ansible stable installations.
