### ISSUE TITLE
Music upload via SSH

### ISSUE THREAD

**Issue by Takumi86ES** [AzuraCast/AzuraCast#3412]
I'm not sure if this can be done or not.

I would like to know if music can be uploaded through PuTTY. If the answer is yes, how can I?

Upload via SFTP (filezilla or winscp is VERY slow)

I would like to use wget.

**Comment by Vaalyn** [comment]
You can find the Docker volumes for your station data at `/var/lib/docker/volumes/azuracast_station_data/_data/<your_station>/media`.

Connect with PuTTY to your server, go to that directory (replace `<your_station>` in the path) and there you can use wget to download files directly onto the server.

**Comment by quydox** [comment]
> You can find the Docker volumes for your station data at `/var/lib/docker/volumes/azuracast_station_data/_data/<your_station>/media`.
> 
> Connect with PuTTY to your server, go to that directory (replace `<your_station>` in the path) and there you can use wget to download files directly onto the server.

I known this one, but I need create unique id for this song for request queue. and it will show on Music files section
