### ISSUE TITLE
Looking how to set is_live to true from inside the AzuraCast user interface.

### ISSUE THREAD

**Issue by rleiman** [AzuraCast/AzuraCast#3414]
Greetings,

I noticed on the now playing API that there is a field under live -> is_live  that indicates that the DJ is live or not live. Can you tell me where and what the DJ needs to do in the AzuraCast software in order for that API field to become "true"?

live
   is_live: false
   broadcast_start: null
   streamer_name:

Thanks in advance.

Truly,
Emad

**Comment by Vaalyn** [comment]
This is automatically set by the AutoDJ when a DJ connects to the stream through the DJ Accounts feature (the AutoDJ manages the connections of DJs). When a DJ connects to the stream the Liquidsoap AutoDJ calls this [internal only API](https://github.com/AzuraCast/AzuraCast/blob/master/src/Controller/Api/InternalController.php#L101-L122) which set's that field to true. There is no method to set that field manually.

**Comment by rleiman** [comment]
Hi Vaalyn,

Thanks so much for the reply. So does that mean all the DJ has to do is go to the Web DJ page, log in and click the Start Streaming button to get the API to populate is_live with true? I'm only asking because the people who are running the station asked me to find out. I will also assume that just logging out will populate it with false.

Truly,
Emad

**Comment by Vaalyn** [comment]
Yes, that's exactly how that's supposed to work. When someone connects via a DJ Account (regardless of which streaming software) this is set to `true` and on disconnect it's set to `false`.

**Comment by rleiman** [comment]
Hi Vaalyn,

Thanks so much.
