### ISSUE TITLE
Getting Users to the Public Pages - Easily

### ISSUE THREAD

**Issue by martynjsimpson** [AzuraCast/AzuraCast#3416]
Running in Docker on Ubuntu 18.04.

It would be nice if there was a way to configure AzuraCast to redirect to a Public Station Page rather than the Logon page. That way the sub.domain.com URL could be shared wth users (the majority), and Admin's/ broadcasters etc would know to use /login.

Is there a native function to redirect users who hit the / (root) page of the Web Server to the public page of a specific station? (rather than the Logon).

If not would there be any issues you could see with putting a redirect into the nginx.conf file?

I am worried that doing this might affect the IceCast connections since they appear to hit root as well.

Any suggestions welcome.

Maybe even just a Button/ Link on the Logon Page "Click Here for Station X" or whatever.

(Of course, an alternative would be to use a URL shortener service and share that).

**Comment by Vaalyn** [comment]
You can do this by going to the `Administration` -> `Custom Branding` page and adding a URL to the `Homepage Redirect URL` setting. For example setting it to `https://demo.azuracast.com/public/azuratest_radio` would redirect to the public page of the demo installation.
