### ISSUE TITLE
Release #2eb3d4b (2020-11-13 20:51) • Docker • PHP 7.4

### ISSUE THREAD

**Issue by radiobellissima** [AzuraCast/AzuraCast#3417]
Error?
![Test](https://user-images.githubusercontent.com/57127248/99144005-a57cc480-2662-11eb-9ffc-9e26084c2df8.png)

**Comment by SC2Mitch** [comment]
This isn't an error, run the sync task manually to remove it / check for errors.

**Comment by radiobellissima** [comment]
I had already done so and this is the answer. The error always remains there.
![Test](https://user-images.githubusercontent.com/57127248/99149390-fe158700-268d-11eb-9869-66e7e1e2644c.png)
