### ISSUE TITLE
Have account active but saying No available station after I renewed Subscription

### ISSUE THREAD

**Issue by Kronixknight** [AzuraCast/AzuraCast#3418]
I renewed my subscription after it expired, tried to get in to manage my station and after I log in I get this " Your account is active, but is not currently associated with any stations. If you believe this is an error, please contact this server's administrator." I know I have a station, where did it go?

**Comment by SC2Mitch** [comment]
AzuraCast is not responsible for third party hosts, you'll need to talk with them about this issue.

**Comment by Vaalyn** [comment]
You need to contact the hoster that you are paying since we are not affiliated with any hoster nor do we control what they do on their servers. We are not paid by them for any licenses and we are not the first level support for their customers.
