### ISSUE TITLE
Stuck running Database Migrations

### ISSUE THREAD

**Issue by adoboligh1** [AzuraCast/AzuraCast#3421]
Running Database Migrations
---------------------------

[notice] Migrating up to App\Entity\Migration\Version20201109203951

STUCK FOREVER!!!

**Comment by Vaalyn** [comment]
What was the version you were on before updating?
How many stations do you have?
How much media files?

Depending on which version you were on before there are some rather big changes that just take a long time on installations with big media libraries / many stations.
