### ISSUE TITLE
Need help fetching song_history api with JS

### ISSUE THREAD

**Issue by HowardCrane** [AzuraCast/AzuraCast#3422]
Hi folks,
I've never really learned JSON and I'm using someone else's js snippet to get values from the API. Works fine for things like streamer_name, playlist, now_playing etc., but I'm confused by the song_history tree. See a sample of my code below.

`var url = 'http://111.90.150.133/api/nowplaying/1'
fetch(url)
  .then(function (request) {
    return request.json()  
  })
  .then(function (json) {
    var streamer = json.live.streamer_name`

After this I thought I'd like to get data for the recently played songs. The only way I can think of identifying them is something like this: `song_history.0.song.title` but that just breaks my code. I know this has nothing to do with Azuracast, but other users unfamiliar with JSON and Javascript may also benefit from any help I receive.

Thanks!

**Comment by Vaalyn** [comment]
In order to access an array element you need to use `[0]` instead `.0` to refer to it like this: `json.song_history[0].song.title`
