### ISSUE TITLE
Backblaze problem

### ISSUE THREAD

**Issue by Takumi86ES** [AzuraCast/AzuraCast#3424]
I want to connect the Backblaze storage but I have errors.

https://i.gyazo.com/b81aac6d913c7ebab6dd356e073889cc.png

I try to fill in "endpoint" with the address they provide me. (s3.us-west-000.backblazeb2.com) but it doesn't work. I always get that error.

Other error "Unauthenticated requests are not allowed for this api"

Can you teach me step by step?

Thanks

**Comment by Vaalyn** [comment]
Try entering the endpoint like this: `https://s3.us-west-000.backblazeb2.com`

**Comment by Takumi86ES** [comment]
> Try entering the endpoint like this: `https://s3.us-west-000.backblazeb2.com`

I already tried but it didn't work...

Try to test yourself....

**Comment by Vaalyn** [comment]
> > Try entering the endpoint like this: `https://s3.us-west-000.backblazeb2.com`
> 
> I already tried but it didn't work...
> 
> Try to test yourself....

I just did that. I followed the instructions that Backblaze provides you with at https://help.backblaze.com/hc/en-us/articles/360047425453 to find out what values to use for what.

To get to that page I clicked on the `B2 Starter Guide` on the Buckets page and on that starter guide page I clicked on `Getting Started with the S3 Compatible API`.

![image](https://user-images.githubusercontent.com/13745863/99190894-9af92280-2769-11eb-97ed-9aaf0b9854e3.png)

![image](https://user-images.githubusercontent.com/13745863/99190928-c7ad3a00-2769-11eb-9242-bb66f227b4e9.png)

**Comment by Takumi86ES** [comment]
> > > Intente ingresar el punto final de esta manera: `https://s3.us-west-000.backblazeb2.com`
> > 
> > 
> > Ya lo intenté pero no funcionó ...
> > Intenta ponerte a prueba ...
> 
> Solo hice eso. Seguí las instrucciones que te proporciona Backblaze en https://help.backblaze.com/hc/en-us/articles/360047425453 para averiguar qué valores usar para qué.
> 
> Para llegar a esa página, hice clic en `B2 Starter Guide`en la página de Buckets y en esa página de la guía de inicio hice clic `Getting Started with the S3 Compatible API`.
> 
> ![imagen](https://user-images.githubusercontent.com/13745863/99190894-9af92280-2769-11eb-97ed-9aaf0b9854e3.png)
> 
> ![imagen](https://user-images.githubusercontent.com/13745863/99190928-c7ad3a00-2769-11eb-9242-bb66f227b4e9.png)

[https://i.imgur.com/zckGqbw.jpg](url)

**Comment by Vaalyn** [comment]
Did you create an `Application Key` for your bucket on the `Application Keys` page?

The Key you entered there looks much shorter than what my key looks like.

**Comment by Takumi86ES** [comment]
Create a new one. New error

![Inked88ec3367d2e4e5c6f5b3be89f47c068f_LI](https://user-images.githubusercontent.com/52046665/99191433-f973d000-276c-11eb-86a0-073043dd0d17.jpg)

**Comment by Takumi86ES** [comment]
Done, it works.
Secret key = application Key

**Comment by Vaalyn** [comment]
> Done, it works.
> Secret key = application Key

That's what the guide I posted says:

![image](https://user-images.githubusercontent.com/13745863/99191563-afd7b500-276d-11eb-92a4-aecce55131ef.png)

Good to see that it's working now.
Will close this issue then.

**Comment by kofyebs** [comment]
I've been able to connect my S3 to my Azuracast but playlist is not playing.
