### ISSUE TITLE
Song Play Count

### ISSUE THREAD

**Issue by eskapiste** [AzuraCast/AzuraCast#3428]
**Using Docker installation method**
Yes

**AzuraCast version**
0.10.3

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
Hello there! 
got a question. Is there any possibility to see if any song in my playlist had been played at all?
I got one playlist with  1070 songs in it,  playback set to Random.
I ve noticed, that if you go to Song Listener Impact section, there is Plays column.
I wonder, what it reflects? A number of times this song was fully listened by a listener or an amount of times it was played at all?
And in case of second, it seems that some of the songs from my playlist had never been played. Why is that?
Thanks in advance.
Cheers!

![image](https://user-images.githubusercontent.com/69782953/99200127-2a272a00-27ac-11eb-800e-d9a384db63d5.png)

**Comment by eskapiste** [comment]
so?

**Comment by SlvrEagle23** [comment]
@eskapiste It's possible that there is something wrong with the file metadata (i.e. it has illegal characters in it, or something else is wrong with it) that is causing it to actually not be played by the system, even though it's in one or more playlists.

The "played" count in that report should indeed show the number of total plays for the track.
