### ISSUE TITLE
Add admin-editable "Buy This Song" link for station media

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#343]
Here are some humble ideas that I propose to you in pictures.

**Song Requests**
![demande](https://user-images.githubusercontent.com/379099/34067991-1b480966-e234-11e7-9ad4-ae87e699b43a.png)

**Edit Media Metadata**
![edit media](https://user-images.githubusercontent.com/379099/34068144-2c148f0a-e237-11e7-9eaf-1720701c833a.jpg)

**Player Embed** 
![player embed](https://user-images.githubusercontent.com/379099/34068123-e0b4a446-e236-11e7-9a0c-67c2890f2b1f.jpg)

To finish with the logo
![azuracast-noback](https://user-images.githubusercontent.com/379099/34068007-ad17b954-e234-11e7-85c3-1543654abc6e.png)

😓

**Comment by SlvrEagle23** [comment]
@ckeurk Thank you for the ideas, but every Github issue should represent a single, completable request for an enhancement. There's no way to track multiple requests inside a single issue, so there's no way to properly handle that without ignoring the other requests in that same issue.

I'm gathering from the screenshots that the biggest request you're making is for adding support for a "Buy this song" link, with an admin-editable store URL and corresponding buttons on the public request and embed pages. I'll update this issue to specifically relate to that one issue; you can create new issues for any other requests.

As for a logo, AzuraCast already has a logo, and it's the one included on the project's readme:
https://github.com/AzuraCast/AzuraCast/raw/master/resources/azuracast.png

**Comment by RainbowDash53** [comment]
I think add a single link for each music could be long, so why don't use an API like iTunes ?

**Comment by SlvrEagle23** [comment]
This will be folded into the feature request associated with ticket #214. Follow it there!
