### ISSUE TITLE
Docker installation fails on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by onyxcode** [AzuraCast/AzuraCast#3430]
**Using Docker installation method**
Yes

**AzuraCast version**
Can't tell

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
Installation fails with error
```
ERROR: for azuracast_stations  Cannot create container for service stations: unknown log opt 'max-size' for journald log driver

ERROR: for influxdb  Cannot create container for service influxdb: unknown log opt 'max-size' for journald log driver

ERROR: for mariadb  Cannot create container for service mariadb: unknown log opt 'max-size' for journald log driver

ERROR: for redis  Cannot create container for service redis: unknown log opt 'max-file' for journald log driver

ERROR: for stations  Cannot create container for service stations: unknown log opt 'max-size' for journald log driver
```

**To Reproduce**
`sudo bash ./docker.sh install`

**Expected behavior**
Finish installation

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by Vaalyn** [comment]
By default Docker should use the `json-file` logging driver.
Have you manually installed Docker or changed the default logging driver?

You can check what driver your Docker installation is configured to use via `docker info --format '{{.LoggingDriver}}'` (from your error this seems to be set to journald and I'd like to verify this)

**Comment by eddriesen** [comment]
Hi there, same here.
Default installed docker on ubuntu 20.04 server

I'm afraid changing the logging options for docker might break other things.
