### ISSUE TITLE
automated backups are overwriting themselves even if I have number of backups set properly..

### ISSUE THREAD

**Issue by stickbear2015** [AzuraCast/AzuraCast#3431]
**Using Docker installation method**

yes
**AzuraCast version**

Rolling Release #4007db1 (2020-11-17
**Host Operating System**

debian 10
**Describe the bug**

Backups are overwriting themselves even if I set the number of backups to 0.
From the backup configuration page, it says
Copies older than the specified number of days will automatically be deleted. Set to zero to disable automatic deletion.
**To Reproduce**

1. go to admin/backups/configure backups.
2. set Number of Backup Copies to Keep to zero, or any number for that matter, but I use zero because I'm a backup hog.
3. Let it run one, if not two backups.
4. note the first backup zip file it creates.
5. on second run, note that the file is named exactly the same, overwriting your previous backup.
**Expected behavior**

The files should be timestamped during automatic backups to prevent the backup system from overwriting itself.
**Relevant Logs**

nothing logged abnormally.
**Screenshots**

none.
**Device(s):**
 - Device: desktop/laptop.  
 - OS: Windows 10 
 - Browser: chrome, firefox 
 - Version: latest stable as of the date of this issue. 

**Additional context**

None apply.

**Comment by krakenfury** [comment]
I'm seeing the same thing.
@stickbear2015 are you backing up to the default location (Local: /var/azuracast/backups)?

**Comment by stickbear2015** [comment]
Hello @krakenfury,
I am backing up to the default location.
:)

**Comment by krakenfury** [comment]
OK I'm using s3, so same behavior for either

**Comment by krakenfury** [comment]
my guess is that it's just a bug in whatever script performs the backup... that might be in docker.sh, but idk i'm totally new here :)
@SlvrEagle23 any insight to where this lives?

**Comment by krakenfury** [comment]
this looks like the code which does the thing:
https://github.com/AzuraCast/AzuraCast/blob/master/src/Console/Command/Backup/BackupCommand.php
i don't really know php, but i'll take a look in there and see if i can figure it out.

**Comment by krakenfury** [comment]
@stickbear2015 this appears to be fixed now. i'm not sure which update it was, though.

**Comment by SlvrEagle23** [comment]
A recent commit rewrote how we handle automated backup naming and rotation and added support for rotating out old backups on remote filesystems, which should fix this issue entirely.
