### ISSUE TITLE
Can't move or delete files from web interface

### ISSUE THREAD

**Issue by dturrina** [AzuraCast/AzuraCast#3432]
**Using Docker installation method**

Yes

**AzuraCast version**

#e1e8a7b

**Host Operating System**

Debian 10

**Describe the bug**

From web interface, can't do anything by flagging single files or even folders, just as nothing was selected

**To Reproduce**

1. Go to "Music files"
2. Select a single or multiple file(s) or folder(s)
3. Click "Move"
4. Select an appropriate destination folder
5. Click "Move"
... nothing happens

**Expected behavior**

The file(s) should be moved to the selected folder

**Relevant Logs**

No log shown

**Device(s):**
 - Device: both deskyop and mobile (web interface) 
 - OS: Android, Windows
 - Browser: Chrome

**Comment by SC2Mitch** [comment]
https://github.com/AzuraCast/AzuraCast/issues/3435#issuecomment-729887727

This issue is being tracked at the moment.
