### ISSUE TITLE
Twitter Web Hook only works when *Tested*.

### ISSUE THREAD

**Issue by Anitron1** [AzuraCast/AzuraCast#3433]
I currently have the twitter activated any time the currently playing song changes.  Short story... nothing is happening when the tracks change.  However, each time I use the Test button to try out the web hook, it works perfectly.  Can anyone tell me why its not engaging when the tracks change?  Thanks.

**Comment by stickbear2015** [comment]
what if any, output are you getting from logs?
see
https://www.azuracast.com/help/logs/
for instructions on viewing logs.

**Comment by Anitron1** [comment]
I'm using a service over the web, so I can't get at the Azura logs directly. Here is a snippet or what I could find:

2020/11/18 12:01:21 [clock.wallclock_main:2] We must catchup 2.10 seconds!
2020/11/18 12:01:41 [capitol_54_dc_next_song:3] Prepared "/var/azuracast/stations/capitol_54_dc/media/MXAB/05AB/02WST4 - I Got Soul (Original Mix).mp3" (RID 1).
2020/11/18 12:01:41 [cross_7767:3] Analysis: -54.611910dB / -13.446635dB (2.99s / 3.01s)
2020/11/18 12:01:41 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/11/18 12:01:42 [lang:3] AzuraCast Feedback Response: OK
2020/11/18 12:02:05 [clock.wallclock_main:2] We must catchup 1.04 seconds!
2020/11/18 12:02:06 [clock.wallclock_main:2] We must catchup 1.66 seconds!

The rest of the log looks the same.  When I manually [test] the web hook, everything works fine.  I get a 200 response back from Twitter.

**Comment by stickbear2015** [comment]
I'm not seeing anything abnormal in that log output.
1. Have you contacted your provider for assistance?
2. Have you deleted the webhook and re-added it in the event something's funky with the authorization?

I understand testing is working, but there is clearly something wrong, and we'd need more detailed logs to troubleshoot this one.
:)

**Comment by Anitron1** [comment]
Thanks for the quick response.  Yes.  I deleted the web hook.  Got new authentications and created a new web hook... same results.  Will contact the provider to see whats wrong.  Thanks again.
