### ISSUE TITLE
In "rolling-release" there is bug when selecting media files

### ISSUE THREAD

**Issue by ttodua** [AzuraCast/AzuraCast#3434]
I've installed latest version a hour ago on a fresh ubuntu.
I've chosen Rolling-release (not Stable installation) and under stations, where I upload music files, then when I click "select all" checkbox, it does nothing. I have to select tracks one-by-one and then "add to queue", however, neither "add to queue" button worked. 

(note, I've had uploaded folders into sFTP in media root, so, AzuraCast showed "File Not Processed" onto all folders at first, but after trying to "rename" one of them, the page was refreshed and it resolved all foders/subfiles. However, even after that, the above problem was still in).

**Comment by ttodua** [comment]
Here I have recorded a video with STABLE VERSION, doing similar: https://files.fm/f/3xegw74qv

**Comment by SlvrEagle23** [comment]
@ttodua I believe the issue with not being able to select media on the media manager is related to #3435, which has just been fixed as of the latest rolling-release version. Please update and let us know if the issue is resolved.

**Comment by ttodua** [comment]
Ok, thanks!
