### ISSUE TITLE
Can't add song to playlist, can't move or delete files, Duplicate songs feature not working, Liquidsoap auto-start after update not working

### ISSUE THREAD

**Issue by technplus** [AzuraCast/AzuraCast#3435]
**Using Docker installation method**

Yes

**AzuraCast version**

Rolling Release #edc17a8 (2020-11-18 7:47) 

**Host Operating System**

Debian 10

**Describe the bug**

1.  From the web interface, you can't move, delete songs or assign them to a playlist, you can't select all the files, when you select only one and try to move it, nothing happens, if you try to add it to a playlist, you get a NO FILES SELECTED error message.
2. After the update, Liquidsoap is not auto start, you have to start it manually.
3. The duplicate songs' feature is not working anymore

**To Reproduce**
Steps to reproduce the behavior 1
1. Go to Music files
2. Select a single since it's not possible to select multiple files
3. Click Playlists
4. Select the appropriate playlist
5. Error message "NO FILES SELECTED"

Steps to reproduce the behavior 3
1. On the left menu, click on Reports
2. Click on "Duplicate Songs"
3. Error message "This page isn’t working"

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
- Device: Desktop
- OS: Windows
- Browser: Chrome

**Additional context**

**Comment by SC2Mitch** [comment]
I've been able to replicate the bugs mentioned in your report. 

Deleting files:  https://puu.sh/GOPI5/d3153ab2d5.mp4
Bug issue: When files aren't linked with a playlist it's impossible to delete them. 

Assigning playlists: https://puu.sh/GOPL6/92130126c3.png
Bug issue: The software does not recognize the files nor calculates them. 

I'm unable to replicate the duplicate songs feature.

**Comment by SlvrEagle23** [comment]
@technplus The first error you reported (about files being selected but not being able to act on those selected files) should now be fixed as of the latest rolling-release update.

We're having trouble reproducing the other issues you reported, but in the interest of ensuring we can easily keep track of the status and progress of resolving any issues, I'd ask that you create those issues as separate ones. In general, we prefer to follow a "one-problem-per-issue" rule here, even if it results in a higher volume of GitHub issues total.

**Comment by technplus** [comment]
I confirm that the issues regarding moving, deleting files and assigning songs to playlists have been resolved (in the release #9af3979), I didn't know about the "one-problem-per-issue" rule, I will comply in my next reports.

**Comment by SlvrEagle23** [comment]
@technplus No problem at all, it's just a courtesy we ask so we can more easily track projects. Glad to hear the first issue is fixed!
