### ISSUE TITLE
Does azuracast have a DJ priority?

### ISSUE THREAD

**Issue by Radio-Quergedacht** [AzuraCast/AzuraCast#3437]
examples

DJ 1 sends to mountpoint / test without explicit priority.
DJ 2 connects with priority 5: / test? Prio = 5. DJ 1 is kicked out, DJ 2 broadcasts.
DJ 1 tries to reconnect / test without explicit priority. The connection fails because DJ 2 is transmitting with a higher priority.
DJ 1 now connects with priority 1: / test? Prio = 1. Now the connection works, DJ 2 is thrown out.

Is that possible with azuracast?

**Comment by Vaalyn** [comment]
This is currently not possible.

There has been a feature request for something similar but specifically for a Shoutcast only feature [here](https://features.azuracast.com/suggestions/61866/shoutcast-2-dnas-dj-priority) which is currently not planned on being done.

I can imagine, but I'm not sure if it is really possible, to incorporate something like this in the DJ authentication script via Liquidsoap. If you'd like you can create a feature request for that over at https://features.azuracast.com/ though.
