### ISSUE TITLE
How to block a listener ip ?

### ISSUE THREAD

**Issue by suricloud** [AzuraCast/AzuraCast#3438]
**Using Docker installation method**

yes
**AzuraCast version**
 v0.10.4 Stable

**Host Operating System**

ubuntu 20.04
**Describe the bug**

Hi,

How can we block a listerner ip?
I noticed someone is restreaming my radio and updated his stream link on tunein for my radio station?
This is very bad thing what has happend.I do see the ip from which it is restreamed.How to block that ip in azuracast?

**Comment by Vaalyn** [comment]
In the `Station Profile` in `Broadcasting` you can add IP-addresses to the `Advanced Banned IP Addresses` field.
