### ISSUE TITLE
Station name upside down

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#344]
Everything is good from the point of view of the station's profile, the name of the radio station is in the right direction.
![profile station](https://user-images.githubusercontent.com/379099/34068964-82e2e41c-e246-11e7-9e25-31155762f4ad.png)

But if I look at SHOUTcast:
![upside down](https://user-images.githubusercontent.com/379099/34068965-8b2780e2-e246-11e7-8f2d-d30970ac7f6e.jpg)

The same thing with IceCast:
![icestats](https://user-images.githubusercontent.com/379099/34068977-e2c814d8-e246-11e7-8eb7-e285b80f6df8.png)

**Comment by SlvrEagle23** [comment]
@ckeurk There's no reason whatsoever that the station name would transpose letters or anything. Did you recently update the name? If so, go to Utilities > Restart Broadcasting on the station's panel to rewrite the relevant configuration sections.

**Comment by ckeurk** [comment]
Okay, problem solved. Thank you

**Comment by ckeurk** [comment]
Okay, problem solved. Thank you
