### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by adoboligh1** [AzuraCast/AzuraCast#3440]
Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.

It says temporary but been there for about 7 hours now! help!

**Comment by SlvrEagle23** [comment]
@adoboligh1 We need more information on what this error message is regarding.

You can get more information on an error by running, on the host via SSH:

```
cd /var/azuracast
docker-compose logs -f web
```

...paste any error messages here that appear there when trying to load the page.

**Comment by adoboligh1** [comment]
Fixed it, problem was with my ram😊
