### ISSUE TITLE
MariaDB failing to start up

### ISSUE THREAD

**Issue by linareyne** [AzuraCast/AzuraCast#3441]
**Using Docker installation method**
Yes

**AzuraCast version**
Can't access the web interface because mariadb

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
MariaDB is failing to start up... dunno much more than that. Tried updating the script and pulling the latest container images.

**To Reproduce**
No idea. Was working recently, not sure when/why it isn't now.

**Expected behavior**
Should work?

**Relevant Logs**
```
mariadb_1                  | 2020-11-20 06:35:06+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.4.13+maria~bionic started.
mariadb_1                  | 2020-11-20 06:35:07+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mariadb_1                  | 2020-11-20 06:35:07+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.4.13+maria~bionic started.
mariadb_1                  | 2020-11-20  6:35:07 0 [Note] mysqld (mysqld 10.4.13-MariaDB-1:10.4.13+maria~bionic) starting as process 11 ...
mariadb_1                  | 2020-11-20  6:35:07 0 [Note] InnoDB: Using Linux native AIO
mariadb_1                  | 2020-11-20  6:35:07 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1                  | 2020-11-20  6:35:07 0 [Note] InnoDB: Uses event mutexes
mariadb_1                  | 2020-11-20  6:35:07 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1                  | 2020-11-20  6:35:07 0 [Note] InnoDB: Number of pools: 1
mariadb_1                  | 2020-11-20  6:35:07 0 [Note] InnoDB: Using SSE2 crc32 instructions
mariadb_1                  | 2020-11-20  6:35:07 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
mariadb_1                  | 2020-11-20  6:35:07 0 [ERROR] mysqld: Can't create/write to file '/tmp/ibnkaimO' (Errcode: 13 "Permission denied")
mariadb_1                  | 2020-11-20  6:35:07 0 [ERROR] InnoDB: Unable to create temporary file; errno: 13
mariadb_1                  | 2020-11-20  6:35:07 0 [ERROR] mysqld: Can't create/write to file '/tmp/ibwT5pSP' (Errcode: 13 "Permission denied")
mariadb_1                  | 2020-11-20  6:35:07 0 [ERROR] InnoDB: Unable to create temporary file; errno: 13
mariadb_1                  | 2020-11-20  6:35:07 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
mariadb_1                  | 2020-11-20  6:35:07 0 [Note] InnoDB: Starting shutdown...
mariadb_1                  | 2020-11-20  6:35:07 0 [ERROR] Plugin 'InnoDB' init function returned error.
mariadb_1                  | 2020-11-20  6:35:07 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
mariadb_1                  | 2020-11-20  6:35:07 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1                  | 2020-11-20  6:35:07 0 [ERROR] Unknown/unsupported storage engine: InnoDB
mariadb_1                  | 2020-11-20  6:35:07 0 [ERROR] Aborting
mariadb_1                  | 2020/11/20 06:35:07 Command exited with error: exit status 1
```

**Device(s):**
 - Device: NUC8
 - OS: Ubuntu
 - Browser: Firefox
 - Version: unsure, can't access web interface

**Comment by linareyne** [comment]
Went ahead and just started from scratch. Guess I did something somewhere somehow. :P

**Comment by kemecs** [comment]
after yesterday's last update, my plow won't start mariadb_1 container

radio@folktest:~/azuracast$ docker-compose ps
Name Command State Ports
azuracast_mariadb_1 dockerize -template /tmp/d ... **Restarting**
azuracast_nginx_proxy_1 /app/docker-entrypoint.sh ... Up

radio@folktest:/azuracast$ docker-compose logs -f mariadb
.....
mariadb_1 | 2021/02/10 12:57:16 Command exited with error: exit status 1
mariadb_1 | 2021-02-10 12:58:19+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.8+mariafocal started.
mariadb_1 | 2021-02-10 12:58:20+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mariadb_1 | 2021-02-10 12:58:20+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.8+mariafocal started.
mariadb_1 | 2021-02-10 12:58:21 0 [Note] mysqld (mysqld 10.5.8-MariaDB-1:10.5.8+mariafocal) starting as process 12 ...
mariadb_1 | 2021-02-10 12:58:21 0 [Note] InnoDB: Using Linux native AIO
mariadb_1 | 2021-02-10 12:58:21 0 [Note] InnoDB: Uses event mutexes
mariadb_1 | 2021-02-10 12:58:21 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1 | 2021-02-10 12:58:21 0 [Note] InnoDB: Number of pools: 1
mariadb_1 | 2021-02-10 12:58:21 0 [Note] InnoDB: Using generic crc32 instructions
mariadb_1 | 2021-02-10 12:58:21 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
mariadb_1 | 2021-02-10 12:58:21 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
mariadb_1 | 2021-02-10 12:58:21 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1 | 2021-02-10 12:58:21 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_1 | 2021-02-10 12:58:21 0 [ERROR] InnoDB: Upgrade after a crash is not supported. The redo log was created with MariaDB 10.4.13.
mariadb_1 | 2021-02-10 12:58:21 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
mariadb_1 | 2021-02-10 12:58:21 0 [Note] InnoDB: Starting shutdown...
mariadb_1 | 2021-02-10 12:58:21 0 [ERROR] Plugin 'InnoDB' init function returned error.
mariadb_1 | 2021-02-10 12:58:21 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
mariadb_1 | 2021-02-10 12:58:21 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1 | 2021-02-10 12:58:21 0 [ERROR] Unknown/unsupported storage engine: InnoDB
mariadb_1 | 2021-02-10 12:58:21 0 [ERROR] Aborting
mariadb_1 | 2021/02/10 12:58:21 Command exited with error: exit status 1

I just did that:

docker-compose stop
docker-compose up -d mariadb
docker-compose stop mariadb
docker-compose start

has not improved:

radio@folktest:~/azuracast$ docker-compose ps
Name Command State Ports
azuracast_mariadb_1 dockerize -template /tmp/d ... **Restarting**
azuracast_nginx_proxy_1 /app/docker-entrypoint.sh ... Up 0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
