### ISSUE TITLE
Temporarly disable the synchronization tasks

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#3442]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #02d87dd (2020-11-18 22:24)

**Host Operating System**
Ubuntu 18.04

**Describe the bug**

I'm trying to extract old playing data from a database only backup . I setup a fresh vps for that, restored the old db only backup and imedtlly marked the "Days of Playback History to Keep" to Indefinitely. Everything went fine and I could see the data but after a few seconds the **synchronization tasks** deleted the data .

Is there a way to disable all the synchronization tasks?

**Comment by Vaalyn** [comment]
There are 2 relatively new environment variables that are used to define the time that sync tasks are allowed to run. Maybe you can use those to set the execution time to 1 before starting the containers (setting it to 0 would allow it do run indefinitely). Hopefully that will prevent it from deleting the data. Apart from that there isn't really a way to prevent them from running.

```
# The maximum execution time (and lock timeout) for the 15-second, 1-minute and 5-minute synchronization tasks.
# SYNC_SHORT_EXECUTION_TIME=600

# The maximum execution time (and lock timeout) for the 1-hour synchronization task.
# SYNC_LONG_EXECUTION_TIME=1800
```
