### ISSUE TITLE
AzuraCast is not installed via Docker on Ubuntu

### ISSUE THREAD

**Issue by voluburator** [AzuraCast/AzuraCast#3445]
**Using Docker installation method**
Yes

**Host Operating System**
Dedicated server
Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-47-generic x86_64)

**Describe the bug**
During the installation through Docker, connection errors appear and then the installation ends. The browser has a 502 error.
Trying commands:
docker-compose down
docker-compose up -d mariadb
docker-compose up -d

After them in the browser:
Slim Application Error

Reinstalling doesn't help. The problem is recurring. I tried installing 30 times and it didn't work

**Relevant Logs**

docker-compose logs -f mariadb
Attaching to azuracast_mariadb_1
mariadb_1                  | 2020-11-21 23:10:31+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.4.13+maria~bionic started.
mariadb_1                  | 2020-11-21 23:10:32+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mariadb_1                  | 2020-11-21 23:10:32+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.4.13+maria~bionic started.
mariadb_1                  | 2020-11-21 23:10:32+00:00 [Note] [Entrypoint]: Initializing database files
mariadb_1                  |
mariadb_1                  |
mariadb_1                  | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
mariadb_1                  | To do so, start the server, then issue the following commands:
mariadb_1                  |
mariadb_1                  | '/usr/bin/mysqladmin' -u root password 'new-password'
mariadb_1                  | '/usr/bin/mysqladmin' -u root -h  password 'new-password'
mariadb_1                  |
mariadb_1                  | Alternatively you can run:
mariadb_1                  | '/usr/bin/mysql_secure_installation'
mariadb_1                  |
mariadb_1                  | which will also give you the option of removing the test
mariadb_1                  | databases and anonymous user created by default.  This is
mariadb_1                  | strongly recommended for production servers.
mariadb_1                  |
mariadb_1                  | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
mariadb_1                  | MySQL manual for more instructions.
mariadb_1                  |
mariadb_1                  | Please report any problems at http://mariadb.org/jira
mariadb_1                  |
mariadb_1                  | The latest information about MariaDB is available at http://mariadb.org/.
mariadb_1                  | You can find additional information about the MySQL part at:
mariadb_1                  | http://dev.mysql.com
mariadb_1                  | Consider joining MariaDB's strong and vibrant community:
mariadb_1                  | https://mariadb.org/get-involved/
mariadb_1                  |
mariadb_1                  | 2020-11-21 23:10:57+00:00 [Note] [Entrypoint]: Database files initialized
mariadb_1                  | 2020-11-21 23:10:57+00:00 [Note] [Entrypoint]: Starting temporary server
mariadb_1                  | 2020-11-21 23:10:57+00:00 [Note] [Entrypoint]: Waiting for server startup
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] mysqld (mysqld 10.4.13-MariaDB-1:10.4.13+maria~bionic) starting as process 132 ...
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] InnoDB: Using Linux native AIO
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] InnoDB: Uses event mutexes
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] InnoDB: Number of pools: 1
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] InnoDB: Using SSE2 crc32 instructions
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] InnoDB: Waiting for purge to start
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] InnoDB: 10.4.13 started; log sequence number 61220; transaction id 21
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mariadb_1                  | 2020-11-21 23:10:57 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1                  | 2020-11-21 23:10:58 0 [Warning] 'user' entry 'root@0ae290fa882a' ignored in --skip-name-resolve mode.
mariadb_1                  | 2020-11-21 23:10:58 0 [Warning] 'user' entry '@0ae290fa882a' ignored in --skip-name-resolve mode.
mariadb_1                  | 2020-11-21 23:10:58 0 [Warning] 'proxies_priv' entry '@% root@0ae290fa882a' ignored in --skip-name-resolve mode.
mariadb_1                  | 2020-11-21 23:10:58 0 [Note] InnoDB: Buffer pool(s) load completed at 201121 23:10:58
mariadb_1                  | 2020-11-21 23:10:58 0 [Note] Reading of all Master_info entries succeeded
mariadb_1                  | 2020-11-21 23:10:58 0 [Note] Added new Master_info '' to hash table
mariadb_1                  | 2020-11-21 23:10:58 0 [Note] mysqld: ready for connections.
mariadb_1                  | Version: '10.4.13-MariaDB-1:10.4.13+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
mariadb_1                  | 2020-11-21 23:10:59+00:00 [Note] [Entrypoint]: Temporary server started.
mariadb_1                  | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.

mariadb_1                  | 2020-11-21 21:58:10 22 [Warning] Aborted connection 22 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:10 21 [Warning] Aborted connection 21 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:15 23 [Warning] Aborted connection 23 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:15 24 [Warning] Aborted connection 24 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:16 25 [Warning] Aborted connection 25 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:16 26 [Warning] Aborted connection 26 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:17 27 [Warning] Aborted connection 27 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:18 28 [Warning] Aborted connection 28 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:19 29 [Warning] Aborted connection 29 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:22 31 [Warning] Aborted connection 31 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:22 30 [Warning] Aborted connection 30 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:22 32 [Warning] Aborted connection 32 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:25 33 [Warning] Aborted connection 33 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:30 34 [Warning] Aborted connection 34 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:30 35 [Warning] Aborted connection 35 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:30 36 [Warning] Aborted connection 36 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:31 37 [Warning] Aborted connection 37 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:31 38 [Warning] Aborted connection 38 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:32 39 [Warning] Aborted connection 39 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:33 40 [Warning] Aborted connection 40 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:34 41 [Warning] Aborted connection 41 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:37 42 [Warning] Aborted connection 42 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:37 43 [Warning] Aborted connection 43 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:40 44 [Warning] Aborted connection 44 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:45 45 [Warning] Aborted connection 45 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:45 46 [Warning] Aborted connection 46 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:46 47 [Warning] Aborted connection 47 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:46 48 [Warning] Aborted connection 48 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:47 49 [Warning] Aborted connection 49 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:48 50 [Warning] Aborted connection 50 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:49 51 [Warning] Aborted connection 51 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:52 52 [Warning] Aborted connection 52 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:52 53 [Warning] Aborted connection 53 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)
mariadb_1                  | 2020-11-21 21:58:55 54 [Warning] Aborted connection 54 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)

**Screenshots**
![begor](https://user-images.githubusercontent.com/74839275/99888576-fbeb9380-2c5e-11eb-9352-7f5d6d2ca64f.jpg)
![r3cki](https://user-images.githubusercontent.com/74839275/99888592-0b6adc80-2c5f-11eb-8c87-b48c146bdc2d.jpg)
![1fazx](https://user-images.githubusercontent.com/74839275/99888619-39e8b780-2c5f-11eb-8925-4581309f1d5b.jpg)
![osy7s](https://user-images.githubusercontent.com/74839275/99888605-1a518f00-2c5f-11eb-977f-f0136b7f8703.jpg)
![7vmxw](https://user-images.githubusercontent.com/74839275/99888625-43721f80-2c5f-11eb-99e6-826c13d4b190.jpg)

**Comment by lennvilardi** [comment]
same issue try with a debian buster but I've always have in the log of mariadb :
mariadb_1                  | 2020-12-29 16:56:31 337 [Warning] Aborted connection 337 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.3' (This connection closed normally without authentication)
