### ISSUE TITLE
2-factor authorization asks everytime

### ISSUE THREAD

**Issue by ttodua** [AzuraCast/AzuraCast#3446]
When we have enabled 2-fa, it asks everytime (even if we re-login in 5 minutes) for "Two-Factor code". 
Which is odd to ask it everytime. There should be some mechanism to save the successful login once we first time enter the Two-Factor code correctly, and within next 30 days, it shouldn't ask again, like Google, FB, or any web-service does. I don't know if that is feature-request or issue, as it should have that option and probably some kind of frustration/issue.

**Comment by SlvrEagle23** [comment]
@ttodua Hello! We have an existing pending request to add "remember me" functionality over on our [FeatureUpvote](https://features.azuracast.com/) page. Feel free to vote on that submission there and we will consider it for inclusion!
