### ISSUE TITLE
Seamless transition?

### ISSUE THREAD

**Issue by eskapiste** [AzuraCast/AzuraCast#3448]
**Using Docker installation method**

Yes

**AzuraCast version**

0.10.4

**Host Operating System**

Ubuntu 20.04

**Describe the bug**
high there! got a question about transitions from AutoDJ to LiveDJ.
Streamers are enabled.
So, i found this line in documentation 

> In order to allow a seamless transition between live DJs and the AutoDJ, each streamer connects directly to the AutoDJ software (Liquidsoap).

I decided to try how it works, and, basically, if AutoDJ i splaying and you will try to connect with streamer account - it will basically cut out the AutoDJ and will start broadcasting whatever is playing on DJ side (or silence).

So, here is the question. Is there any way to seamlessly fade out what is playingby AutoDJ and then fade in the DJ side? I guess, fade out is enough, cause we always begin live sessions with a silence.

Otherwise, i should wait till the Auto DJs song will finish  and then connect as a LiveDJ, in that silence gap - which is ok, if there are no any other options.

Have a good day!

**Comment by SpeedyCharly** [comment]
Personally worked with HMS Sonic and Centova before coming to Azuracast and haven't seen such an option on any of 'em...

On Azura, the gap killing and crossfading still need work, so I don't think your excellent idea will come to light in a near future...

**Comment by eskapiste** [comment]
yeah.
but someone here told me that there was a manual crossfade feature, but it was a bit buggy and they decided to turn it down for improvement.
