### ISSUE TITLE
Move AzuraCast to sub-folder

### ISSUE THREAD

**Issue by giovanni256** [AzuraCast/AzuraCast#3449]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.4 Stable

**Host Operating System**
Ubuntu 20.04

Hi there.
Is there a way to move AzuraCast to a sub-folder?
I want to use my VPS in order to run my webradio and even my website, but it actually points to the AzuraCast backend.

Thanks!

Edit: I linked my domain to my VPS and moved AzuraCast on ports 85 and 448
If I try to connect to MY_IP:85 I can see AzuraCast back-end.
If I try to connect MY_DOMAIN:85 it isn't working... some explanation?

**Comment by Vaalyn** [comment]
Since AzuraCast is not using a pre-installed web server it is not possible to run it in a sub-directory.
I'd recommend you to point a sub-domain to the server for AzuraCast and use the [Multi-Site](https://www.azuracast.com/extending/multisite.html) feature or let AzuraCast run on different ports like you wrote in the `Edit`.

> If I try to connect MY_DOMAIN:85 it isn't working... some explanation?

Going by the conservation on the discord server this is most likely due to CloudFlare since they block non-standard ports.

**Comment by giovanni256** [comment]
> Since AzuraCast is not using a pre-installed web server it is not possible to run it in a sub-directory.
> I'd recommend you to point a sub-domain to the server for AzuraCast and use the [Multi-Site](https://www.azuracast.com/extending/multisite.html) feature or let AzuraCast run on different ports like you wrote in the `Edit`.
> 
> > If I try to connect MY_DOMAIN:85 it isn't working... some explanation?
> 
> Going by the conservation on the discord server this is most likely due to CloudFlare since they block non-standard ports.

Hi there. 
Just today I removed CloudFlare and AzuraCast is running correctly on ports 85 and 448.
I'm having troubles using the Multi-Site feature. 

I had to manually copy the docker-compose.yml file (since I cannot paste the code via VNC), but I get these errors:
` The compose file... is invalid because:
Unsupported config option for services.networks 'backend'
Unsupported config option for services.volumes 'db_data' 
Unsupported config option for services.wordpress 'depends_on' `

**Comment by giovanni256** [comment]
Update: I re-installed the VPS and now I'm using SSH.
I get this error while executing

Error: `ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 6, column 47`

My docker-compose.yml file
`version: '2.2'

services:
    wordpress:
        image: wordpress:latest
        depends_on:
         - db
        networks:
         - azuracast_frontend
         - backend
        restart: always
        environment:
            # Change this to the domain your Wordpress site should be served on.
            VIRTUAL_HOST: domain.com
            # If you want to use LetsEncrypt on this domain, uncomment these and update them.
            LETSENCRYPT_HOST: domain.com
            LETSENCRYPT_EMAIL: email@email.com
            WORDPRESS_DB_HOST: db:3306
            # If you customize these values, make sure to customize them below also.
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: mypass
            WORDPRESS_DB_NAME: wordpress

    db:
        image: mysql:5.7
        volumes:
         - db_data:/var/lib/mysql
        networks:
         - backend
        restart: always
        environment:
            # If you customize these values, make sure to customize them above also.
            MYSQL_ROOT_PASSWORD: mypass
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: mypass

networks:
    azuracast_frontend:
        external: true
    backend:
        driver: bridge

volumes:
    db_data: {}`
