### ISSUE TITLE
Ipv6 listener support

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#345]
Hello!

Ill request the IPv6 support for in the listeners table because i use a integration on my website where i use the IP column for.

Greetings,
Remco

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38781/show-ipv6-ips-in-listener-statistics-where-available
