### ISSUE TITLE
Song already set in a playlist gets removed when adding it to another one

### ISSUE THREAD

**Issue by picpakdog** [AzuraCast/AzuraCast#3451]
**Using Docker installation method**

Yes

**AzuraCast version**

 #b1f7d24 (2020-11-23 8:14)

**Host Operating System**

Ubuntu Server 20.04

**Describe the bug**

When a song is already added to a playlist, going in and setting it to more than one playlist clears it from the previous playlist and only includes it in the newly added playlist.

**To Reproduce**

1. Go to Music Files > choose a song already in a playlist (e.g. All music)
2. Select it, go to Playlists > choose All music and another playlist, e.g. Currents
3. The song is cleared from the All music playlist and is only in the Currents playlist.

**Expected behavior**

The song is added to the All music and Currents playlists.

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  Desktop
 - OS:  OS X 10.15.7
 - Browser:  Safari
 - Version:  14.0.1

**Additional context**

**Comment by SlvrEagle23** [comment]
@picpakdog This is currently the intended functionality of the "Set Playlists" menu, which is to assign the selected items to the selected playlists, regardless of which playlists they were already in.

Admittedly this may not be what all users expect, and we're always working to improve our media manager as it's central to the functionality of the application, so any feature requests would be welcome on our [features page](https://features.azuracast.com/).
