### ISSUE TITLE
Recurring Playlist

### ISSUE THREAD

**Issue by eugeniosulweb1981** [AzuraCast/AzuraCast#3453]
Hello!
Is it possible to schedule recurring playlist in azuracast?
For example, can I schedule a playlist to go every monday at 8pm?

**Comment by Vaalyn** [comment]
Yes this is possible via the `Schedule` tab when creating or editing a playlist:

![image](https://user-images.githubusercontent.com/13745863/100032130-8a931880-2df7-11eb-899a-de37bc068740.png)
