### ISSUE TITLE
Azuracast Relay Listeners Bug (Reproduced)

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#3454]
**Using Docker installation method**
Docker

**AzuraCast version**
Latest

**Host Operating System**
Ubuntu 16 and 18

**Describe the bug**
My AzuraCast instance crashed randomly (i got error 500's). When a DJ was livestreaming. Errors in the log: 
![image](https://user-images.githubusercontent.com/29834979/100070162-e383a080-2e39-11eb-8a6a-705416f599da.png)

But that is not the problem. Thankfully I i installed the day before a new Azuracast instance on another server, with 2 relays. When i changed the servers on the site i noticed that the Listeners count is the relay count. In the listeners report only the relays are showed.
![image](https://user-images.githubusercontent.com/29834979/100028409-2a987400-2def-11eb-8ec2-62356d64cf26.png)
![image](https://user-images.githubusercontent.com/29834979/100028422-37b56300-2def-11eb-98b9-ccf4494e6606.png)

After updating my (old) crashed Azuracast instance to the latest version, I could reach the webinterface again. But same problem: Only the two relays are showed in the listeners report and the listeners count doesn't work good anymore. (Which was working perfectly before the update)

**To Reproduce**
Update to the latest version.

**Expected behavior**
I would see all the listeners in the overview not the amount of relays as listenres.

**Relevant Logs**
In the IceCast errorlog is see the following:
```[2020-11-24  00:47:41] WARN slave/slave_startup process has 65536 max file descriptor limit```

@SlvrEagle23 I think this is a bug you would like to know.

**Comment by Vaalyn** [comment]
Could you update your AzuraRelay and AzuraCast to the latest versions and check if this is still happening?
There has been a rather big update to the Relay recently.

**Comment by RemBdev** [comment]
Done. It is still happening.

**Comment by RemBdev** [comment]
Done @Vaalyn it is still happening

**Comment by Vaalyn** [comment]
Does your installation still crash and do you still see the same error on your AzuraCast logs?

**Comment by RemBdev** [comment]
I moved to another azuracast instance where the bug doesn't happen. The problem right now is that the relay's are counted as a listener. So 3 of the 4 unique listeners are relays.

![image](https://user-images.githubusercontent.com/29834979/103580692-ef538f80-4eda-11eb-9727-60733ddfcfed.png)

**Comment by RemBdev** [comment]
@Vaalyn I moved to another azuracast instance where the bug doesn't happen. The problem right now is that the relay's are counted as a listener. So 3 of the 4 unique listeners are relays.

![image](https://user-images.githubusercontent.com/29834979/103580810-21fd8800-4edb-11eb-8149-66a27ca9e81e.png)
