### ISSUE TITLE
Question: Help with API

### ISSUE THREAD

**Issue by giovanni256** [AzuraCast/AzuraCast#3456]
Hi there.

Since I'm new in AzuraCast, I don't know how to manage API in order to get basic information such as current listeners and current song title from mywebsite.com/api/nowplaying/1

I tried something like that:
```
$file = "https://website.com/api/nowplaying/1";
$data = file_get_contents($file);
$result = json_decode($data, true);
echo $result['listeners'][0]['current'];
```

Than...
```
$url = "https://website.com/api/nowplaying/1";
$data = file_get_contents($url);
$infos = json_decode($data, true);
$nazwa = $infos['now_playing']['song']['title'];
echo $nazwa;
```

Nothing is working.
What can I do?

**Comment by Vaalyn** [comment]
I'd recommend you to check out our PHP API client for AzuraCast: https://packagist.org/packages/azuracast/php-api-client

You can also take a look at the source code of the API client to see how we interact with the API.

**Comment by giovanni256** [comment]
> I'd recommend you to check out our PHP API client for AzuraCast: https://packagist.org/packages/azuracast/php-api-client
> 
> You can also take a look at the source code of the API client to see how we interact with the API.

Thank you.
I already saw the PHP API client but I don't know where I should put this code, since I don't know where the folder "vendor" is located.

```
<?php

require __DIR__ . '/vendor/autoload.php';

$api = \AzuraCast\Api\Client::create(
	'<IP-Address | Host>',
	'<API Key>'
);

$nowPlaying = $api->nowPlaying();

echo $nowPlaying->getCurrentSong()->getSong()->getTitle();
```

**Comment by giovanni256** [comment]
Solved with jQuery
