### ISSUE TITLE
File not processed

### ISSUE THREAD

**Issue by emiryapici** [AzuraCast/AzuraCast#3457]
**Using Docker installation method**

yes
**AzuraCast version**

#428021b
**Host Operating System**

Ubuntu 18.04
**Describe the bug**

**To Reproduce**

Hello. I have problem with flac files. I've tried both web and sftp upload, also tried 16 bit-24bit flac files but it always gives me "File not processed" error. The previous solutions are not working anymore.
MP3 files are working fine.
**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
Please look run `docker-compose logs -f web` and then (while having that running) go to the `System Debugger` page, do `Clear Message Queue` and then manually run the `5-Minute Sync` and see if any errors are shown in the output of the `docker-compose logs -f web` command. This should help identify why those files are not being processed.

**Comment by emiryapici** [comment]
It's now working with version  #8331efb. Problem solved
