### ISSUE TITLE
Queue button not working properly

### ISSUE THREAD

**Issue by emiryapici** [AzuraCast/AzuraCast#3458]
**Using Docker installation method**

yes
**AzuraCast version**

#428021b 
**Host Operating System**

Ubuntu 18.04
**Describe the bug**

Queue button not working properly (or as expected)

**To Reproduce**

1. Go to 'Music Files'
2. Click on a song and then queue button

**Expected behavior**

It should add the selected file to the first element of the queue but it doesn't. Song is added 4-5 songs after.

**Comment by SlvrEagle23** [comment]
@emiryapici The latest rolling-release update queues any selected tracks for playback next instead of submitting them as no-delay requests.
