### ISSUE TITLE
SSL Domain

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#3462]
Hi,

The domain already with https certificate, just put the domain pointed to the streaming server and then put it in the panel in the field: "ip"?

It will work with subdomain too?

Thanks

**Comment by YosefAdPro** [comment]
You need the certificate to be installed on the auracast server.

**Comment by jonikane** [comment]
Ah ok,

I am using an ansible installation.
Do you have a tutorial on how to do this on the azuracast server itself?

I have no domain on the server.
It's only with the ip
