### ISSUE TITLE
Security: Liquidsoap's `string.quote()` Leads to Shell Injection

### ISSUE THREAD

**Issue by dtcooper** [AzuraCast/AzuraCast#3465]
Hi there! I haven't tested this one, but it's somewhat concerning. If you'd like me to reproduce it, I _could_ try but it should be fairly easy. The end result could be a user authenticating on your Liquidsoap's script's harbor could lead to shell injection with a carefully crafted username/password combination.

Per savonet/liquidsoap#1215 &mdash; I can't read PHP very well &mdash; however, I note AzuraCast uses `string.quote()` in `Radio/Backend/Liquidsoap/ConfigWriter.php` both [here](https://github.com/AzuraCast/AzuraCast/blob/6de636f4755837ee01873ec2c11842e5cb52c317/src/Radio/Backend/Liquidsoap/ConfigWriter.php#L659) and [here](https://github.com/AzuraCast/AzuraCast/blob/6de636f4755837ee01873ec2c11842e5cb52c317/src/Radio/Backend/Liquidsoap/ConfigWriter.php#L670) which I believe gets used to sanitize user input, ie during harbor authentication.

Anyway, I'm working on an open source radio backend ([Crazy Arms](/dtcooper/carb)), and borrowing some inspiration from AzuraCast so I thought I'd give you a heads up. Thanks for the great project!

**Comment by dtcooper** [comment]
Oh, one thing to note: I posted a mitigation technique in the above linked issue using the `env=` argument to `get_process_output()`

**Comment by SlvrEagle23** [comment]
@dtcooper Thank you for the heads-up. We'll likely switch to implementing the environment variable solution immediately, as it seems to be a rather clean solution in general (not just as a mitigation to this).

**Comment by dtcooper** [comment]
No prob! Cheers, and thanks for the great project.

**Comment by SlvrEagle23** [comment]
@dtcooper The switch to using environment variables has been implemented in our rolling release branch, and will be implemented in the next stable release. Thank you for the update!
