### ISSUE TITLE
liq_cue_out not passed to liquid soap if cue_in is (too) long.

### ISSUE THREAD

**Issue by walterdevos** [AzuraCast/AzuraCast#3467]
Using Docker installation method
Yes

**AzuraCast version**
v0.10.4 Stable

**Host Operating System**
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"

**Describe the bug  / And reproducing **

Sometimes AutoDJ won't give Liquid Soap the 'cue_out' parameter
![image](https://user-images.githubusercontent.com/3726763/100351163-49fbf080-2feb-11eb-8609-7d240242548a.png)
Though the Cue-out is set:
![image](https://user-images.githubusercontent.com/3726763/100351230-68fa8280-2feb-11eb-99cf-9da6b6b58c3d.png)

It's happening with songs that have a **long CUE IN.**

Furthermore, if you use the visual cueue editor, you'll find that the SET OVERLAP will not color the region when the CUE IN is long. And if you go the length of the CUE IN  forward in the song, the OVERLAP start working.

long cue in:
![image](https://user-images.githubusercontent.com/3726763/100351428-ba0a7680-2feb-11eb-8d16-80d22e5b2206.png)

click on OVERLAP, nothing shows:
![image](https://user-images.githubusercontent.com/3726763/100351463-c2fb4800-2feb-11eb-9a69-fdd0be56181d.png)

click on OVERLAP ( aprox  the CUE IN time back ) and it starts working.
![image](https://user-images.githubusercontent.com/3726763/100351521-d6a6ae80-2feb-11eb-9c4a-b05c828683aa.png)

Liquid-soap calculates cue-out from the beginning of the songs.  BUT ( maybe ) it starts counting from the cue_in?

**The result is** that the song will **not cue out** at the specified point. It will just play till the end.  
The OVERLAP point is shifted passed the end of the file. (?)
Strangely the Visual cue editor "knows" this? 

**Expected behavior**
Correctly send CUE out information to liquid soap.

**Relevant Logs**
See screens

**Screenshots**
See screens

**Device(s):**
Web

**Additional context**
This is possibly also the root cause for this ticket https://github.com/AzuraCast/AzuraCast/issues/3304
My theory:
As far as I can tell Liquid soap and AutoDJ keep in sync by using time-stamps. AutoDJ caclulates where Liquid soap is at a given time, and the response to the internal API call ( next track " AzuraCast Raw Response: annotate:title="Todays... ) is what AutoDJ "thinks" it should be at that time.  

If something goes wrong with CUE IN of CUE OUT time, not being processed correctly. Could this cause issue 3304?

I will link the other ticket to this one as well. 

Cheers!

**Comment by walterdevos** [comment]
I did some extra experimenting.
I have a song with these parameters:

Custom Fading: Overlap Time (seconds) 1.70
Custom Fading: Fade-In Time (seconds) 0.30
Custom Fading: Fade-Out Time (seconds) 1.30
Custom Cues: Cue-In Point (seconds) 33.10
Custom Cues: Cue-Out Point (seconds) 193.2
 
**Pre edit (Liquid Soap log):**
2020/11/25 04:27:54 [lang:3] AzuraCast Raw Response: annotate:title="Looking For Me",artist="Paul Woolford,Diplo,Kareen Lomax",duration="212.35",song_id="f6c6d1d455fb61681a94ddae165fc9b8",media_id="14355",liq_amplify="0.00dB",liq_cross_duration="1.70",liq_fade_in="0.30",liq_fade_out="1.30",liq_cue_in="33.10",playlist_id="5375":/var/azuracast/stations/100_hitradio/media/paul_woolford-2Cdiplo-2Ckareen_lomax_-_looking_for_me.mp3
 
**EDIT:**
Custom Cues: Cue-Out Point (seconds) - Custom Cues: Cue-In Point (seconds)
193.2 - 33.1 = 160.1
 
**Post edit (Liquid Soap log):**
2020/11/26 16:31:37 [lang:3] AzuraCast Raw Response: annotate:title="Looking For Me",artist="Paul Woolford,Diplo,Kareen Lomax",duration="212.35",song_id="f6c6d1d455fb61681a94ddae165fc9b8",media_id="14355",liq_amplify="0.00dB",liq_cross_duration="1.70",liq_fade_in="0.30",liq_fade_out="1.30",liq_cue_in="33.10",**liq_cue_out="160.10"**,request_id="36":/var/azuracast/stations/100_hitradio/media/paul_woolford-2Cdiplo-2Ckareen_lomax_-_looking_for_me.mp3

As soon as I reducte the cue_out with the cue_in time, It is given to Liquid Soap.

**But the problem now is that it's cueing out too soon. It's now 33.10 too soon**

**Comment by walterdevos** [comment]
(edited title for clarity / new insights )

**Comment by walterdevos** [comment]
![image](https://user-images.githubusercontent.com/3726763/100379208-c8b95380-3014-11eb-9a30-7c6359102948.png)

seems it doesn't matter how far you go back, OVERLAP must always be at least the CUE IN lenght.  Something is astray here :)

**Comment by walterdevos** [comment]
![image](https://user-images.githubusercontent.com/3726763/100380995-47fc5680-3018-11eb-8fa2-cd46d4ff7546.png)
Also in the player the clock goes until the 2:22 and then stops. The song keeps playing till the end. ( including the long silence at the end of the file).

**Comment by Vaalyn** [comment]
The `cue_out` problem is fixed by my PR.

The problem with the `Overlap` seems to be due to the assumption that the `Overlap` value is also a duration seen from the beginning of the file like the `Cue In` / `Cue Out` which is not the case as that is the duration as seen from the Cue Out point. See this part of the frontend code: https://github.com/AzuraCast/AzuraCast/blob/master/frontend/vue/station_media/form/MediaFormWaveformEditor.vue#L127

I'm currently researching what the Overlap exactly does behind the scenes and how it should be used so that I can correctly fix this without breaking anything.

Would you mind creating a separate issue for that so that we can keep track of that?

**Comment by walterdevos** [comment]
@Vaalyn ok I will.
And thanks for the quick fix.
