### ISSUE TITLE
ERROR IN UPDATE

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#347]
Hello to all,
Greetings..
I have 2 vps running AzuraCast both are manual installation. I updated both azuracast install but same error occur at the end of update here is the error in both azuracast which i update causes the web interface not working and the streamer cannot connect to the autodj to stream.

TASK [services : Enable and restart all core services] *****************************************************************************************************************
changed: [localhost] => (item=influxdb)
changed: [localhost] => (item=mysql)
changed: [localhost] => (item=php7.2-fpm)
failed: [localhost] (item=nginx) => {"changed": false, "item": "nginx", "msg": "Unable to start service nginx: Job for nginx.service failed because the control process exited with error code. See \"systemctl status nginx.service\" and \"journalctl -xe\" for details.\n"}
changed: [localhost] => (item=redis)

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=68   changed=18   unreachable=0    failed=1

=======================================

root@shoutcast:/var/azuracast/www# systemctl status nginx.service

* nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2017-12-17 10:21:37 EST; 1min 8s ago
     Docs: man:nginx(8)
  Process: 2766 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

Dec 17 10:21:37 shoutcast systemd[1]: Starting A high performance web server and a reverse proxy server...
Dec 17 10:21:37 shoutcast nginx[2766]: nginx: [emerg] unknown directive "`" in /etc/nginx/nginx.conf:27
Dec 17 10:21:37 shoutcast nginx[2766]: nginx: configuration file /etc/nginx/nginx.conf test failed
Dec 17 10:21:37 shoutcast systemd[1]: nginx.service: Control process exited, code=exited status=1
Dec 17 10:21:37 shoutcast systemd[1]: Failed to start A high performance web server and a reverse proxy server.
Dec 17 10:21:37 shoutcast systemd[1]: nginx.service: Unit entered failed state.
Dec 17 10:21:37 shoutcast systemd[1]: nginx.service: Failed with result 'exit-code'.

================================

root@shoutcast:/var/azuracast/www# journalctl -xe

Dec 17 10:23:01 shoutcast CRON[4479]: (azuracast) CMD (php /var/azuracast/www/util/cli.php sync:run nowplaying)
Dec 17 10:23:01 shoutcast CRON[4478]: (azuracast) CMD (php /var/azuracast/www/util/cli.php sync:run short)
Dec 17 10:23:01 shoutcast CRON[4470]: pam_unix(cron:session): session opened for user azuracast by (uid=0)
Dec 17 10:23:01 shoutcast CRON[4482]: (azuracast) CMD (sleep 15; php /var/azuracast/www/util/cli.php sync:run nowplaying)
Dec 17 10:23:01 shoutcast postfix/pickup[25379]: 75F6E45005CA: uid=1000 from=<azuracast>
Dec 17 10:23:01 shoutcast postfix/cleanup[25381]: 75F6E45005CA: message-id=<20171217152301.75F6E45005CA@localhost.localdomain>
Dec 17 10:23:01 shoutcast CRON[4472]: pam_unix(cron:session): session closed for user azuracast
Dec 17 10:23:01 shoutcast postfix/qmgr[25380]: 75F6E45005CA: from=<azuracast@localhost.localdomain>, size=667, nrcpt=1 (queue active)
Dec 17 10:23:01 shoutcast sshd[4282]: Failed password for root from 61.177.172.44 port 34554 ssh2
Dec 17 10:23:01 shoutcast postfix/local[25393]: 75F6E45005CA: to=<azuracast@localhost.localdomain>, orig_to=<azuracast>, relay=local, delay=0.32, delays=0.19/0/0/0.13,
Dec 17 10:23:01 shoutcast postfix/qmgr[25380]: 75F6E45005CA: removed
Dec 17 10:23:02 shoutcast sshd[4282]: Received disconnect from 61.177.172.44 port 34554:11:  [preauth]
Dec 17 10:23:02 shoutcast sshd[4282]: Disconnected from 61.177.172.44 port 34554 [preauth]
Dec 17 10:23:02 shoutcast sshd[4282]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=61.177.172.44  user=root
Dec 17 10:23:02 shoutcast influxd[2547]: [httpd] ::1 - - [17/Dec/2017:10:23:02 -0500] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.2.1 curl/7.
Dec 17 10:23:02 shoutcast postfix/pickup[25379]: 97DF345005C4: uid=1000 from=<azuracast>
Dec 17 10:23:02 shoutcast postfix/cleanup[25381]: 97DF345005C4: message-id=<20171217152302.97DF345005C4@localhost.localdomain>
Dec 17 10:23:02 shoutcast CRON[4471]: pam_unix(cron:session): session closed for user azuracast
Dec 17 10:23:02 shoutcast postfix/qmgr[25380]: 97DF345005C4: from=<azuracast@localhost.localdomain>, size=679, nrcpt=1 (queue active)
Dec 17 10:23:02 shoutcast postfix/local[25383]: 97DF345005C4: to=<azuracast@localhost.localdomain>, orig_to=<azuracast>, relay=local, delay=0.18, delays=0.12/0/0/0.06,
Dec 17 10:23:02 shoutcast postfix/qmgr[25380]: 97DF345005C4: removed
Dec 17 10:23:17 shoutcast influxd[2547]: [httpd] ::1 - - [17/Dec/2017:10:23:17 -0500] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.2.1 curl/7.
Dec 17 10:23:17 shoutcast postfix/pickup[25379]: 6253045005C1: uid=1000 from=<azuracast>
Dec 17 10:23:17 shoutcast CRON[4470]: pam_unix(cron:session): session closed for user azuracast
Dec 17 10:23:17 shoutcast postfix/cleanup[25381]: 6253045005C1: message-id=<20171217152317.6253045005C1@localhost.localdomain>
Dec 17 10:23:17 shoutcast postfix/qmgr[25380]: 6253045005C1: from=<azuracast@localhost.localdomain>, size=689, nrcpt=1 (queue active)
Dec 17 10:23:17 shoutcast postfix/local[25384]: 6253045005C1: to=<azuracast@localhost.localdomain>, orig_to=<azuracast>, relay=local, delay=0.11, delays=0.06/0/0/0.05,
Dec 17 10:23:17 shoutcast postfix/qmgr[25380]: 6253045005C1: removed
Dec 17 10:23:19 shoutcast sshd[4839]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=61.177.172.44  user=root
Dec 17 10:23:21 shoutcast sshd[4839]: Failed password for root from 61.177.172.44 port 15026 ssh2
Dec 17 10:23:24 shoutcast sshd[4839]: Failed password for root from 61.177.172.44 port 15026 ssh2
Dec 17 10:23:25 shoutcast sshd[4839]: Failed password for root from 61.177.172.44 port 15026 ssh2
Dec 17 10:23:26 shoutcast sshd[4839]: Received disconnect from 61.177.172.44 port 15026:11:  [preauth]
Dec 17 10:23:26 shoutcast sshd[4839]: Disconnected from 61.177.172.44 port 15026 [preauth]
Dec 17 10:23:26 shoutcast sshd[4839]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=61.177.172.44  user=root
Dec 17 10:23:31 shoutcast influxd[2547]: [httpd] ::1 - - [17/Dec/2017:10:23:31 -0500] "POST /write?db=stations&precision=s HTTP/1.1" 204 0 "-" "GuzzleHttp/6.2.1 curl/7.
Dec 17 10:23:31 shoutcast postfix/pickup[25379]: AD88645005C1: uid=1000 from=<azuracast>
Dec 17 10:23:31 shoutcast postfix/cleanup[25381]: AD88645005C1: message-id=<20171217152331.AD88645005C1@localhost.localdomain>
Dec 17 10:23:31 shoutcast postfix/qmgr[25380]: AD88645005C1: from=<azuracast@localhost.localdomain>, size=689, nrcpt=1 (queue active)
Dec 17 10:23:31 shoutcast CRON[4469]: pam_unix(cron:session): session closed for user azuracast
Dec 17 10:23:31 shoutcast postfix/local[25383]: AD88645005C1: to=<azuracast@localhost.localdomain>, orig_to=<azuracast>, relay=local, delay=0.01, delays=0/0/0/0, dsn=2.
Dec 17 10:23:31 shoutcast postfix/qmgr[25380]: AD88645005C1: removed

**Comment by jonikane** [comment]
same error here too

**Comment by reans** [comment]
i found the error just edit the entry in

 /etc/nginx/nginx.conf 

        server_tokens off;` 

just remove the ` character

make it  

server_tokens off;

**Comment by SlvrEagle23** [comment]
@reans @jonikane Sorry about that, folks! Minor typo in an update from yesterday. If you were affected, follow the steps listed above (remove the backtick from the line in `/etc/nginx/nginx.conf`) and it should work just fine.
