### ISSUE TITLE
Docker port range 9000 -9999

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#3470]
**Using Docker installation method**
 Yes

**Host Operating System**
Ubuntu 20

It is possible to change port range from 8000 - 8999 to 9000 - 9999?

I tried to change in on but it gave me this error: 

ERROR: The Compose file './docker-compose.override.yml' is invalid because:
services.stations.ports is invalid: Invalid port "9000-9000:9090-9090:9999-9999", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

Thank you

**Comment by Vaalyn** [comment]
It is possible to expand the port range. Take a look at the documentation and example here: https://www.azuracast.com/help/docker/#expand-the-docker-radio-station-port-range

It is however not possible with a `docker-compose.override.yml` to remove already mapped ports from the `docker-compose.yml`.
