### ISSUE TITLE
Delete "AzuraCast is Live!" Audio message from liquidsoap

### ISSUE THREAD

**Issue by AlexNoxious** [AzuraCast/AzuraCast#3471]
Hello,

I would like to know what is the procedure to delete the audio message "AzuraCast is Live!". I understand that the "AzuraCast is Live!" It is used to prevent silences from appearing during transmission.

I have added a song to a playlist so that the "AzuraCast is Live!" stop working. But I need a definitive solution.

Is it possible to permanently disable it by modifying the liquidsoap code?

Thank you
Alex

**Comment by Vaalyn** [comment]
You can replace this file by following [this tutorial](https://www.azuracast.com/help/docker/#using-a-custom-default-track) on our website.

If you don't want to hear anything if for some reason AC falls back to that file just replace it with a file with silence in it.
