### ISSUE TITLE
Icecast Status Page!

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#3477]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 20

**Describe the bug**
It is possible to remove Same lines on icecast status page?

Thank you
![imagem_2020-11-27_225553](https://user-images.githubusercontent.com/7109309/100488028-b407b900-3103-11eb-8ed5-a2bde7c45cf3.png)

**Comment by Vaalyn** [comment]
We do not offer any way to hide or disable parts of the IceCast status page.
