### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#348]
Hello,

I tried installing Azuracast with Traditional Installation Ubuntu 16.04 LTS but this one gave me an error.

"TASK [php: Create Locales]"

the error is on the attached printscreen
![azuracast install error](https://user-images.githubusercontent.com/7109309/34081875-75fb4b70-e34c-11e7-9663-16bfd70a61bc.png)

**Comment by jonikane** [comment]
Hello,

Is it possible to install the previous version?
Is that before the upgrade had no error ...

**Comment by SlvrEagle23** [comment]
@jonikane This appears to be related to: https://github.com/ansible/ansible/issues/29200

Try `rm /etc/locale.gen`, which should fix the issue.

There's no need to use a previous version of AzuraCast, and I don't recommend not updating to the latest version of the software.

**Comment by jonikane** [comment]
Its ok now. Thank you :)

**Comment by jonikane** [comment]
I tried to install on ubuntu 16.04 by ansiable installation and it gave me this error:
![azuracast_install_error](https://user-images.githubusercontent.com/7109309/62900401-f2803580-bd51-11e9-8999-5cba78c67d9b.jpg)
