### ISSUE TITLE
Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s

### ISSUE THREAD

**Issue by scotchale** [AzuraCast/AzuraCast#3480]
**Using Docker installation method**
yes

**Host Operating System**
debian 10 "buster"

**Describe the bug**
trying to do a fresh install, bad results. Since april i'm using azuracast with the same server, same hardware, never a problem. Three weeks ago I made a mistake and restore e bad backup so I decided, also for other reasons, to reinstall it all (debian included). No way to have azuracast running without errors (or simply understand them).

**Shell**
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:25 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
Docker Compose does not appear to be installed. Install Docker Compose now? [Y/n] y
curl: (23) Failed writing body (0 != 1371)
Writing default .env file...
Creating default AzuraCast settings file...
Prefer stable release versions of AzuraCast? [y/N] y
Retrieving default docker-compose.yml file...
Customize AzuraCast ports? [y/N] n
Set up LetsEncrypt? [y/N] y
Domain name (example.com) or names (example.com,foo.bar) to use with LetsEncrypt []: *********************
Optional e-mail address for expiration updates []: **********************
Pulling mariadb                 ... done
Pulling influxdb                ... done
Pulling redis                   ... done
Pulling stations                ... done
Pulling web                     ... done
Pulling nginx_proxy             ... done
Pulling nginx_proxy_letsencrypt ... done
Creating network "azuracast_backend" with driver "bridge"
Creating network "azuracast_frontend" with driver "bridge"
Creating volume "azuracast_nginx_proxy_vhosts" with default driver
Creating volume "azuracast_db_data" with default driver
Creating volume "azuracast_influx_data" with default driver
Creating volume "azuracast_letsencrypt" with default driver
Creating volume "azuracast_letsencrypt_html" with default driver
Creating volume "azuracast_shoutcast2_install" with default driver
Creating volume "azuracast_geolite_install" with default driver
Creating volume "azuracast_sftpgo_data" with default driver
Creating volume "azuracast_station_data" with default driver
Creating volume "azuracast_www_vendor" with default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_redis_data" with default driver
Creating volume "azuracast_backups" with default driver
Creating azuracast_stations   ... done
Creating azuracast_influxdb_1 ... done
Creating azuracast_redis_1    ... done
Creating azuracast_mariadb_1  ... done
2020/11/28 15:44:05 Waiting for: tcp://mariadb:3306
2020/11/28 15:44:05 Waiting for: tcp://influxdb:8086
2020/11/28 15:44:05 Waiting for: tcp://redis:6379
2020/11/28 15:44:05 Connected to tcp://redis:6379
2020/11/28 15:44:05 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:05 Connected to tcp://influxdb:8086
2020/11/28 15:44:06 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:07 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:08 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:09 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:10 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:11 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:12 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:13 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:14 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:15 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:16 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:17 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:18 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:19 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:20 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:21 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:22 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:23 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:24 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:25 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:26 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:27 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:28 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:29 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:30 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:31 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:32 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:33 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:34 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:35 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:36 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:37 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:38 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:39 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:40 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:41 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:42 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:43 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:44 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:45 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:46 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:47 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:48 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:49 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:50 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:51 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:52 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:53 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:54 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:55 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:56 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:57 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:58 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:44:59 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:00 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:01 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:02 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:03 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:04 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:05 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:06 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:07 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:08 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:09 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:10 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:11 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:12 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:13 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:14 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:15 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:16 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:17 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:18 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:19 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:20 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:21 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:22 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:23 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:24 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:25 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:26 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:27 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:28 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:29 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:30 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:31 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:32 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:33 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:34 Problem with dial: dial tcp 172.18.0.4:3306: connect: connection refused. Sleeping 1s
2020/11/28 15:45:35 Timeout after 1m30s waiting on dependencies to become available: [tcp://mariadb:3306 tcp://influxdb:8086 tcp://redis:6379]
azuracast_mariadb_1 is up-to-date
azuracast_influxdb_1 is up-to-date
azuracast_redis_1 is up-to-date
azuracast_stations is up-to-date
Creating azuracast_web ... done
Creating azuracast_nginx_proxy_1 ... done
Creating azuracast_nginx_proxy_letsencrypt_1 ... done

**Comment by roger-net** [comment]
Same thing happened to me. Try after installing run the commands to update, with me it worked.

https://www.azuracast.com/administration/system/updating.html

**Comment by scotchale** [comment]
I tried and you're right: the problem during the update seems to disapear. But still lots of error in the logs, that I reported here: https://github.com/AzuraCast/AzuraCast/issues/3256#issuecomment-734793897 lot of error 200

**Comment by scotchale** [comment]
this morning i've reinstall for the 100th time and.. all is working! :)
