### ISSUE TITLE
Icecast CSS

### ISSUE THREAD

**Issue by TomSmith-Developer** [AzuraCast/AzuraCast#3481]
Hello there!

Is it possible to change the Icecast CSS. After researching I could not find anything on how to do it with Azuracast. 

Thanks, Tom

**Comment by xewl** [comment]
In principle, there's documentation for overriding the ["error.mp3"](https://www.azuracast.com/help/docker/#using-a-custom-default-track) & setting ["intro" files](https://www.azuracast.com/help/docker/#adding-a-stream-intro-file).
In addition there's documention to [customize eg. the nginx config](https://www.azuracast.com/extending/modifying-docker.html#how-azuracast-s-docker-installation-works).

The same principle works for the Icecast stylesheet:

- copy over the original css to your system via the cli command (if Docker):
```sh
cd /etc/azuracast
docker cp azuracast_stations:/usr/local/share/icecast/web/style.css /var/azuracast/icecast.css
```

This way, "icecast.css" will be available in your host.

Then in `docker-compose.override.yml` you can then mount/override the file inside the docker container again:
```
version: '2.2'

services:
    stations:
        volumes:
            - /var/azuracast/icecast.css:/usr/local/share/icecast/web/style.css
```

You'll have to restart the containers for the override to become active.
```
docker-compose down
docker-compose up -d
```

Note that this will override all styles of any Icecast server inside the container.
