### ISSUE TITLE
rolling to stable release

### ISSUE THREAD

**Issue by suricloud** [AzuraCast/AzuraCast#3483]
**Using Docker installation method**

yes
**AzuraCast version**

**Host Operating System**

ubuntu 20
**Describe the bug**

Hi,
I just saw you release stable release.
I have rolling release : Rolling Release #88c8547 (2020-11-29 8:45) 
and want to switch to the stable AzuraCast 0.11 (Nov 28, 2020)
Can i do the switch?

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@suricloud You can learn more about the release channels here: https://www.azuracast.com/administration/system/release-channels.html

In short, to switch to the rolling release, run:

```bash
cd /var/azuracast
./docker.sh update-self
./docker.sh setup-release
```

..then update (via `./docker.sh update`) and you'll be on the stable branch.

**Comment by julianborghuis** [comment]
This would bring problems right? with databases and all?? or is that not anymore the case?

**Comment by BusterNeece** [comment]
You can go from Rolling to Stable as long as your Rolling is _behind_ the latest Stable. If your Rolling is _ahead_ of the latest Stable (which is likely given the recent updates), then switching channels risks putting your database in an unmaintainable state, and it's best to wait until the next stable release.
