### ISSUE TITLE
500 errors when I want to upload a small song

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#3485]
Hey.
I tried to upload a song with a length of one second (15KB). In the network tab at Chrome the page "upload" is on status code 500.

Other error messages I can not find at all. I have also tried any other ticket solution from here without success (Sync button, Docker Process command, etc.)

The upload works. But the file is not processed.

**Comment by Vaalyn** [comment]
Could you provide us with the file so that we can test it?

**Comment by Abqehebter** [comment]
Sure. Would it be bad to do this later? I'm not working right now.

**Comment by Abqehebter** [comment]
Here:
[START_AD_BREAK.zip](https://github.com/AzuraCast/AzuraCast/files/5615743/START_AD_BREAK.zip)

**Comment by SlvrEagle23** [comment]
@Abqehebter This should now be fixed as of the latest rolling-release version.

**Comment by Vaalyn** [comment]
Closing as fixed
