### ISSUE TITLE
Custom url stream

### ISSUE THREAD

**Issue by atmix** [AzuraCast/AzuraCast#3487]
Hello. Tell me how to use this function or does it not work?

![AUT2A](https://user-images.githubusercontent.com/75258577/100652896-668c8580-3369-11eb-9cf2-5f485f000b82.png)

**Comment by Vaalyn** [comment]
It can be used for example when you have a reverse proxy somewhere which proxies the stream to that URL and you want AzuraCast to show that URL instead of the "regular" URL in the AzuraCast interface.
