### ISSUE TITLE
SSL not working going to localhost

### ISSUE THREAD

**Issue by flybelgium** [AzuraCast/AzuraCast#3489]
Hello,
I'm "newbie" with Azuracast. I test it over a VPS freshly installed with Ubuntu 20. I'm not expert with linux.
All is working, SSL Not
On the installation i have choose configure via Letsencrypt with my domain : neoradio.ovh
I have tried  ./docker.sh letsencrypt-create mydomain.example.com and i have already my domain in [neoradio.ovh]...
When i access to my domain or ip over https i have certificate invalid "localhost" with warning.

I have tried a lot of posts here nothing work :(
Can i have a little help ?
Thank you

**Comment by Vaalyn** [comment]
Please run `./docker.sh letsencrypt-create` and copy the output here so we can check if there were any errors happening.

**Comment by flybelgium** [comment]
Thank you : 
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by flybelgium** [comment]
Thank you
```
sudo ./docker.sh letsencrypt-create
Domain name (example.com) or names (example.com,foo.bar) to use with LetsEncrypt [neoradio.ovh]: neoradio.ovh
Optional e-mail address for expiration updates [web@neoradio.be]: web@neoradio.be
Stopping azuracast_web ... done
Going to remove azuracast_web
Removing azuracast_web ... done
azuracast_redis_1 is up-to-date
azuracast_mariadb_1 is up-to-date
azuracast_stations is up-to-date
Creating azuracast_web ... done
azuracast_nginx_proxy_1 is up-to-date
azuracast_nginx_proxy_letsencrypt_1 is up-to-date
```

**Comment by SwaXTech** [comment]
Hello, I am having a similar problem. I followed the steps to enable letsencrypt as indicated in the documentation but after 3 days, I cannot access via HTTPS. The set up shows no errors.

![Untitled](https://user-images.githubusercontent.com/43499966/101518379-9981db00-3960-11eb-8b71-1d57891cb7a4.png)

**Comment by flybelgium** [comment]
> Hello, I am having a similar problem. I followed the steps to enable letsencrypt as indicated in the documentation but after 3 days, I cannot access via HTTPS. The set up shows no errors.
> 
> ![Untitled](https://user-images.githubusercontent.com/43499966/101518379-9981db00-3960-11eb-8b71-1d57891cb7a4.png)

The only i found is a SSL Gateway with my provider OVH.
I link my server to a Secure Gateway and it working but, the problem on Azuracast is a problem...
My solution is not really a solution, this is a countourned solution.

**Comment by SwaXTech** [comment]
> Hello, I am having a similar problem. I followed the steps to enable letsencrypt as indicated in the documentation but after 3 days, I cannot access via HTTPS. The set up shows no errors.
> 
> ![Untitled](https://user-images.githubusercontent.com/43499966/101518379-9981db00-3960-11eb-8b71-1d57891cb7a4.png)

Ok I already found my mistake, I feel a bit silly. By default in Google Cloud Platform, the https port 443 is closed. When I opened it it started working.

**Comment by fast97** [comment]
Hello! By doing an update this morning, who can help me?

**Comment by fast97** [comment]
A bit weird when I put another sub-domain, it works well, with the sub-domain that is the one I normally use, it doesn't work ...

**Comment by fast97** [comment]
hello failed to make ssl on the desired sub-domain forced to change sub-domain.
Thank

**Comment by ATOMONLINE** [comment]
**Help me please. After I completed the update. I can't access my station manager.**

![Screenshot_6](https://user-images.githubusercontent.com/68115153/103146472-691da780-477c-11eb-9ccd-a891ce46cf25.png)

**Comment by xewl** [comment]
> **Help me please. After I completed the update. I can't access my station manager.**
> 
> ![Screenshot_6](https://user-images.githubusercontent.com/68115153/103146472-691da780-477c-11eb-9ccd-a891ce46cf25.png)

That's a separate issue. Please don't bloat other's.
