### ISSUE TITLE
ERROR IN STREAMER if HTTPS is activated

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#349]
hello everyone,
i have azuracast manual installation and updated while ago. I tried to activate the HTTPS function in the setting yes it working good in the web interface but the problem is the stream/dj cannot login to stream using the stream username:password but when i disable again the HTTPS thing back to normal. It seems secured url blocking the streamer account.

**Comment by SlvrEagle23** [comment]
@reans The problem was a behind-the-scenes issue with the connection between the AutoDJ and AzuraCast, and should have been fixed by recent patches related to #354.
