### ISSUE TITLE
File Not Processed

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#3490]
**Using Docker installation method**
No

**AzuraCast version**
Rolling Release #f9048cb (2020-11-27 9:07)

**Host Operating System**
Ubuntu 18.04.5 LTS

**Describe the bug**
File Not Processed label in the Music Files

**Screenshots**
[https://imgur.com/a/PRFgUhQ](https://imgur.com/a/PRFgUhQ)

**Device(s):**
 - Device: Raspberry Pi 3 B+

**Additional context**
I have mounted the folder from the network storage. I don't have problem with the old songs,
I have problem with the newly uploaded (after the updates 1 week ago).
EDIT: I Found out also that it doesn't read the Artworks anymore. Everything is with the default artwork ALWAYS. Even the old processed songs don't have it now :(

**Comment by NicoxDJ** [comment]
I try again ./update.sh --full
And end up with that:
```
TASK [composer : Install Composer Dependencies (Production)] **********************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "composer install --no-dev --optimize-autoloader", "delta": "0:00:01.841942", "end": "2020-12-01 20:29:19.751937", "msg": "non-zero return code", "rc": 2, "start": "2020-12-01 20:29:17.909995", "stderr": "Loading composer repositories with package information\nInstalling dependencies from lock file\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - Installation request for ocramius/proxy-manager 2.10.0 -> satisfiable by ocramius/proxy-manager[2.10.0].\n    - ocramius/proxy-manager 2.10.0 requires composer-runtime-api ^2.0.0 -> no matching package found.\n  Problem 2\n    - doctrine/migrations 3.0.1 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.10.0].\n    - doctrine/migrations 3.0.1 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.10.0].\n    - ocramius/proxy-manager 2.10.0 requires composer-runtime-api ^2.0.0 -> no matching package found.\n    - Installation request for doctrine/migrations 3.0.1 -> satisfiable by doctrine/migrations[3.0.1].\n\nPotential causes:\n - A typo in the package name\n - The package is not available in a stable-enough version according to your minimum-stability setting\n   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.\n - It's a private package and you forgot to add a custom repository to find it\n\nRead <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.", "stderr_lines": ["Loading composer repositories with package information", "Installing dependencies from lock file", "Your requirements could not be resolved to an installable set of packages.", "", "  Problem 1", "    - Installation request for ocramius/proxy-manager 2.10.0 -> satisfiable by ocramius/proxy-manager[2.10.0].", "    - ocramius/proxy-manager 2.10.0 requires composer-runtime-api ^2.0.0 -> no matching package found.", "  Problem 2", "    - doctrine/migrations 3.0.1 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.10.0].", "    - doctrine/migrations 3.0.1 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.10.0].", "    - ocramius/proxy-manager 2.10.0 requires composer-runtime-api ^2.0.0 -> no matching package found.", "    - Installation request for doctrine/migrations 3.0.1 -> satisfiable by doctrine/migrations[3.0.1].", "", "Potential causes:", " - A typo in the package name", " - The package is not available in a stable-enough version according to your minimum-stability setting", "   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.", " - It's a private package and you forgot to add a custom repository to find it", "", "Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems."], "stdout": "", "stdout_lines": []}
```

**Comment by Deiiji** [comment]
You need composer by hand, as elevated user do composer self-update --2

**Comment by NicoxDJ** [comment]
> For processing issue, yes, is very very slow , some time now.

@Deiiji No, it's not slow, it's not processing at all.

**Comment by NicoxDJ** [comment]
Yes, its because the files are in read-only mode.
So i found this:
```
[2020-12-08T23:33:56.477766+00:00] AzuraCast.ERROR: Impossible to create the root directory "/media/Music/.albumart". mkdir(): Read-only file system {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []
```
Than i find i try to edit src/Entity/StationMedia.php and return the old folders from:
```
    public const DIR_ALBUM_ART = '.albumart';
    public const DIR_WAVEFORMS = '.waveforms';
```
to:
```
    public const DIR_ALBUM_ART = '/var/azuracast/stations/club-bg/album_art';
    public const DIR_WAVEFORMS = '/var/azuracast/stations/club-bg/waveforms';
``` 
But there is still something that i have to edit, because it's still trying to search in `/media/Music/var/azuracast/stations/club-bg/album_art`. Please @SlvrEagle23 Tell me what i have to edit more, so it will start storing the artworks and waveforms in the old dirs. Thank you. In other ways, it will be cool to select these folders in the station settings, instead to be hardcoded to the code :(

**Comment by Deiiji** [comment]
Well check owner and permissions, me, I mount media disks inside of /var/azuracast/stations 
By this, chown and chmod when updating fix permissions

**Comment by NicoxDJ** [comment]
@Deiiji I don't have problems with the permissions. The NAS is mounted as RO (readonly) flag. And thats how it supposed to be, because its a backup. And any changes from AzuraCast to that folder, will mess with the backup. Plus it's securing from file corruptions. Thats why it's in read-only, and AzuraCast can't create .artwork and .waveforms folders inside that mounted folder. What i'm trying to do is, to change these folder, to not be in the mounted drive, but in the station folder (like before). But i'm hitting stone while digging so i hope @SlvrEagle23 will tell me what else i have to change.

**Comment by NicoxDJ** [comment]
@Vaalyn can you help too? Do you know what i have to change to return the data into station folder?

**Comment by SlvrEagle23** [comment]
@NicoxDJ This is a byproduct of our storage location modifications. In the previous arrangement, album art and waveforms for the associated media could be stored in different folders, but that doesn't facilitate portability of the storage locations or the ability for one storage location to serve multiple stations without redundant reprocessing (which was one of the largest reasons we implemented the change).

It would be possible for us to implement, as an advanced feature, the ability to specify a secondary folder for waveforms and album art on a per-storage-location basis, but even if that were changed, a read-only filesystem would cause issues because any time the media is edited it would attempt to write the ID3 tags back to the file and fail, causing errors. Basically, we're just not built for read-only filesystems at the moment.

**Comment by NicoxDJ** [comment]
@SlvrEagle23 Well, yes, thats what i want. I don't want the id3 to be touched at all. I'm using rsync to upload the songs to the server, and this will change the songs on my personal computer too.

If it's not a problem, just tell me what i have to change, to return saving data in the station folder, and i will change it only for myself. And you don't have to change it for the master version.

**Comment by SlvrEagle23** [comment]
@NicoxDJ The storage location overhaul was a fairly significant one that affected lots of places around the system. It's possible that you could update `src/Entity/StationMedia.php`, in particular its functions for getting album art and waveform paths.

**Comment by NicoxDJ** [comment]
@SlvrEagle23 Am i in the right way with the modifications that i post here 6 comments above? Can you point me the functions?

**Comment by Vaalyn** [comment]
@NicoxDJ should probably change those functions here like this:

```
public static function getArtPath(string $uniqueId): string
{
    return 'album_art/' . $uniqueId . '.jpg';
}

public static function getArtUri(string $uniqueId): string
{
    return FilesystemManager::applyPrefix(
        FilesystemManager::PREFIX_CONFIG,
        self::getArtPath($uniqueId)
    );
}

public static function getWaveformPath(string $uniqueId): string
{
    return . 'waveforms/' . $uniqueId . '.json';
}

public static function getWaveformUri(string $uniqueId): string
{
    return FilesystemManager::applyPrefix(
        FilesystemManager::PREFIX_CONFIG,
        self::getWaveformPath($uniqueId)
    );
}
```

This changes the Filesystem that is used for the Waveform and Art URI generation and the path for the directory. I've copied the values from the old version. The `FilesystemManager::PREFIX_CONFIG` tells it to use the config directory.

(Haven't tested it so I can't guarantee that it works)

**Comment by NicoxDJ** [comment]
@Vaalyn I did this, but there is still some other places to change. Maybe another file? That is triggering 5 minute sync and the file processing. Its still trying to create folder in the media folder:
```
[2020-12-09T16:31:49.128793+00:00] AzuraCast.ERROR: Impossible to create the root directory "/media/Music/album_art". mkdir(): Read-only file system {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []
```

**Comment by NicoxDJ** [comment]
@Vaalyn Even if i put the full path in the function:
```
    public static function getArtPath(string $uniqueId): string
    {
        return '/var/azuracast/stations/club-bg/album_art/' . $uniqueId . '.jpg';
    }

    public static function getArtUri(string $uniqueId): string
    {
        return FilesystemManager::applyPrefix(
            'album_art',
            self::getArtPath($uniqueId)
        );
    }
```
i still get:
```
[2020-12-09T19:21:45.652863+00:00] AzuraCast.ERROR: Impossible to create the root directory "/media/Music/var/azuracast/stations/club-bg/album_art". mkdir(): Read-only file system {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []
```
It's like in another file somewhere else is putting the media folder as prefix.

**Comment by Vaalyn** [comment]
Seems to be rather tricky.

In addition to what I wrote these parts are also relevant:

The filesystem for saving the album art is fetched here: 
https://github.com/AzuraCast/AzuraCast/blob/b6a01eb07b6fcd3492059784a340a21edd571bf0/src/Entity/Repository/StationMediaRepository.php#L313

through the `getFilesystem` method here: https://github.com/AzuraCast/AzuraCast/blob/b6a01eb07b6fcd3492059784a340a21edd571bf0/src/Entity/Repository/StationMediaRepository.php#L429
The same method is also used for getting the filesystem for the media files so you can't just modify that method.

You'd have to replace the `$fs = $this->getFilesystem($media);` in `readAlbumArt`, `writeAlbumArt`, `removeAlbumArt`, `updateWaveform` and `writeWaveform` with fetching the config filesystem but in order fetch a filesystem you'd either need access to an `AdapterInterface` like it's done in the `getFilesystem` with `$media->getStorageLocation()->getStorageAdapter()` or access to a `Station` entity in those places which is not possible since `StationMedia` is not related to a single Station anymore.

I don't see how this would be possible to do in the current state and I personally don't want to spend time on this since it is not a use-case that we are currently supporting.

I would recommend you to manually create the `.albumart` and `.waveforms` directories on your network storage and make only those 2 directories writeable.

**Comment by NicoxDJ** [comment]
@Vaalyn I was trying to edit files few hours, and than i gave up.
Than i just think about your suggestion. And i saw that there is other way.

Instead of mounting folder in the linux /media folder and symlink it to the station folder (as "media" link), i mount the folder inside station/media. In this way the mounted folder is still read only, but its inside the media folder. The .albumart and .waveforms are in the media folder too, but they are writable, because they are in the raspberry pi.

Now i have to change my primary station mounted folder, and i have to re-add the songs into the playlists again. Or maybe i will play around with the mysql, and edit the paths to the all songs with adding prefix.

I think the case is closed. I hope to help someone who's trying the same thing :)
