### ISSUE TITLE
Problem updating to 0.11

### ISSUE THREAD

**Issue by stemvantwente** [AzuraCast/AzuraCast#3491]
Ansible installation on Unbuntu 18.04

The error I get is:

TASK [composer : Install Composer Dependencies (Production)] *******************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "composer install --no-dev --optimize-autoloader", "delta": "0:00:00.300328", "end": "2020-12-02 00:04:11.501682", "msg": "non-zero return code", "rc": 2, "start": "2020-12-02 00:04:11.201354", "stderr": "Loading composer repositories with package information\nInstalling dependencies from lock file\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - Installation request for ocramius/proxy-manager 2.10.0 -> satisfiable by ocramius/proxy-manager[2.10.0].\n    - ocramius/proxy-manager 2.10.0 requires composer-runtime-api ^2.0.0 -> no matching package found.\n  Problem 2\n    - doctrine/migrations 3.0.1 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.10.0].\n    - doctrine/migrations 3.0.1 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.10.0].\n    - ocramius/proxy-manager 2.10.0 requires composer-runtime-api ^2.0.0 -> no matching package found.\n    - Installation request for doctrine/migrations 3.0.1 -> satisfiable by doctrine/migrations[3.0.1].\n\nPotential causes:\n - A typo in the package name\n - The package is not available in a stable-enough version according to your minimum-stability setting\n   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.\n - It's a private package and you forgot to add a custom repository to find it\n\nRead <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.", "stderr_lines": ["Loading composer repositories with package information", "Installing dependencies from lock file", "Your requirements could not be resolved to an installable set of packages.", "", "  Problem 1", "    - Installation request for ocramius/proxy-manager 2.10.0 -> satisfiable by ocramius/proxy-manager[2.10.0].", "    - ocramius/proxy-manager 2.10.0 requires composer-runtime-api ^2.0.0 -> no matching package found.", "  Problem 2", "    - doctrine/migrations 3.0.1 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.10.0].", "    - doctrine/migrations 3.0.1 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.10.0].", "    - ocramius/proxy-manager 2.10.0 requires composer-runtime-api ^2.0.0 -> no matching package found.", "    - Installation request for doctrine/migrations 3.0.1 -> satisfiable by doctrine/migrations[3.0.1].", "", "Potential causes:", " - A typo in the package name", " - The package is not available in a stable-enough version according to your minimum-stability setting", "   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.", " - It's a private package and you forgot to add a custom repository to find it", "", "Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems."], "stdout": "", "stdout_lines": []}

**Comment by pacija** [comment]
Same error for me, ansible installation on Ubuntu 20.04.1 LTS

**Comment by pacija** [comment]
I am not sure if what I did has any negative consequences (I have no clue about AzuraCast internals), but apparently update went through after updating composer.

```
pacija@azuracast:/var/azuracast/www$ sudo composer self-update --2
Updating to version 2.0.7 (2 channel).
   Downloading (100%)         
Use composer self-update --rollback to return to version 1.10.13
```
After this, update finishes with:
```
PLAY RECAP *************************************************************************************
localhost: ok=22   changed=11   unreachable=0    failed=0    skipped=71   rescued=0    ignored=0   
```

Station is active, footer shows:
`Rolling Release #58a1611 (2020-12-02 4:10) • Ansible • PHP 7.4`

**Comment by NicoxDJ** [comment]
@pacija Thanks! This helped me too! :)

**Comment by stemvantwente** [comment]
Thank you @pacija this worked for me to!

Greets

**Comment by ThatLadyDev** [comment]
> I am not sure if what I did has any negative consequences (I have no clue about AzuraCast internals), but apparently update went through after updating composer.
> 
> ```
> pacija@azuracast:/var/azuracast/www$ sudo composer self-update --2
> Updating to version 2.0.7 (2 channel).
>    Downloading (100%)         
> Use composer self-update --rollback to return to version 1.10.13
> ```
> 
> After this, update finishes with:
> 
> ```
> PLAY RECAP *************************************************************************************
> localhost: ok=22   changed=11   unreachable=0    failed=0    skipped=71   rescued=0    ignored=0   
> ```
> 
> Station is active, footer shows: `Rolling Release #58a1611 (2020-12-02 4:10) • Ansible • PHP 7.4`

This worked for me!!

**Comment by F8ER** [comment]
> $ sudo composer self-update --2

In case of `Command "self-update" is not defined` you might want re-install Composer: https://getcomposer.org/download

Currently, the installation process is the following:

```bash
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
```

---

Related: https://stackoverflow.com/questions/37772798/unable-to-self-update-composer
