### ISSUE TITLE
composer-runtime-api ^2.0.0 -> no matching package found.

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#3494]
**Using Docker installation method**
No

**AzuraCast version**
Rolling Release #6183870 (2020-11-29 10:26) but trying to update to latest dev

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
composer throws an error when doing the update

**Relevant Logs**

`fatal: [localhost]: FAILED! => {"changed": true, "cmd": "composer install --no-dev --optimize-autoloader", "delta": "0:00:00.155448", "end": "2020-12-03 08:25:14.589064", "msg": "non-zero return code", "rc": 2, "start": "2020-12-03 08:25:14.433616", "stderr": "Loading composer repositories with package information\nInstalling dependencies from lock file\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - Installation request for ocramius/proxy-manager 2.10.0 -> satisfiable by ocramius/proxy-manager[2.10.0].\n    - ocramius/proxy-manager 2.10.0 requires composer-runtime-api ^2.0.0 -> no matching package found.\n  Problem 2\n    - doctrine/migrations 3.0.1 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.10.0].\n    - doctrine/migrations 3.0.1 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.10.0].\n    - ocramius/proxy-manager 2.10.0 requires composer-runtime-api ^2.0.0 -> no matching package found.\n    - Installation request for doctrine/migrations 3.0.1 -> satisfiable by doctrine/migrations[3.0.1].\n\nPotential causes:\n - A typo in the package name\n - The package is not available in a stable-enough version according to your minimum-stability setting\n   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.\n - It's a private package and you forgot to add a custom repository to find it\n\nRead <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.", "stderr_lines": ["Loading composer repositories with package information", "Installing dependencies from lock file", "Your requirements could not be resolved to an installable set of packages.", "", "  Problem 1", "    - Installation request for ocramius/proxy-manager 2.10.0 -> satisfiable by ocramius/proxy-manager[2.10.0].", "    - ocramius/proxy-manager 2.10.0 requires composer-runtime-api ^2.0.0 -> no matching package found.", "  Problem 2", "    - doctrine/migrations 3.0.1 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.10.0].", "    - doctrine/migrations 3.0.1 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.10.0].", "    - ocramius/proxy-manager 2.10.0 requires composer-runtime-api ^2.0.0 -> no matching package found.", "    - Installation request for doctrine/migrations 3.0.1 -> satisfiable by doctrine/migrations[3.0.1].", "", "Potential causes:", " - A typo in the package name", " - The package is not available in a stable-enough version according to your minimum-stability setting", "   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.", " - It's a private package and you forgot to add a custom repository to find it", "", "Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems."], "stdout": "", "stdout_lines": []}`

**Comment by YosefAdPro** [comment]
see this:
https://github.com/AzuraCast/AzuraCast/issues/3491#issuecomment-737226594
