### ISSUE TITLE
File not processed in mounted folders via docker-composer-overryde.yml

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#3495]
Hi,
We continue with the failure of unprocessed files after updating to Azuracast version 0.11.

We have tried to update to the rolling release, and the bug continues.

When running media sync manually, we come across this message.

![imagen](https://user-images.githubusercontent.com/16152034/101013154-25ac9080-3564-11eb-8a6c-c60688f8213d.png)

Clarify that the errors occur in the folders that are mounted from outside of docker and that are configured in docker-composer-override.yml

![imagen](https://user-images.githubusercontent.com/16152034/101013352-715f3a00-3564-11eb-9a01-e454acb7ee60.png)

In version 10.3 of Azuracast everything worked correctly. Any idea where the error may come from?

For our station it is important since we feed the station by downloading podcasts in those shared folders. If we cannot use the downloaded audios in those folders, many programs are left without broadcasting.

**Comment by Vaalyn** [comment]
Please look into the output of `docker-compose logs -f web` for any errors regarding processing this file.
Go to the `System Debugger` page and `Clear Cache` as well as `Clear Message Queue` and then run the `5-Minute Sync` while having the terminal with the command running open. That way you'll get a live output of the logs.

**Comment by fidegr** [comment]
In Connection.php line 374:
web_1                      |
web_1                      |   Could not acknowledge redis message "1607009533545-0".
web_1                      |
web_1                      |
web_1                      | queue:process [--worker-name WORKER-NAME] [--] [<runtime>]
web_1                      |
web_1                      | [2020-12-03T15:32:14.745691+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":300,"workerName":"app_worker_0"} []
web_1                      | [2020-12-03T15:32:14.912060+00:00] AzuraCast.ERROR: Cannot process media file at path "done": MIME type "text/plain" is not processable. {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []
web_1                      | [2020-12-03T15:32:14.930607+00:00] AzuraCast.ERROR: Cannot process media file at path "errors": MIME type "text/plain" is not processable. {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []
web_1                      |
web_1                      | In Connection.php line 374:
web_1                      |
web_1                      |   Could not acknowledge redis message "1607009534267-0".
web_1                      |
web_1                      |
web_1                      | queue:process [--worker-name WORKER-NAME] [--] [<runtime>]
web_1                      |
web_1                      | [2020-12-03T15:32:15.862921+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":300,"workerName":"app_worker_0"} []
web_1                      | [2020-12-03T15:32:16.472792+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data [] []
web_1                      | [2020-12-03T15:32:16.731740+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":8,"name":"Radio Topo"}}
web_1                      | [2020-12-03T15:32:16.750357+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":11,"name":"Irola Irratia"}}
web_1                      | [2020-12-03T15:32:16.751498+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":11,"name":"Irola Irratia"}}
web_1                      | [2020-12-03T15:32:16.752382+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":11,"name":"Irola Irratia"}}
web_1                      | [2020-12-03T15:32:17.161199+00:00] AzuraCast.ERROR: Request returned status code 404. {"body":""} {"station":{"id":2,"name":"Radios Libres "}}
web_1                      |
web_1                      | In Connection.php line 374:
web_1                      |
web_1                      |   Could not acknowledge redis message "1607009535021-1".
web_1                      |
web_1                      |
web_1                      | queue:process [--worker-name WORKER-NAME] [--] [<runtime>]
web_1                      |
web_1                      | [2020-12-03T15:32:17.474525+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":300,"workerName":"app_worker_0"} []
web_1                      | [2020-12-03T15:32:17.615042+00:00] AzuraCast.ERROR: Request returned status code 404. {"body":""} {"station":{"id":6,"name":"Radio Almaina"}}
web_1                      | [2020-12-03T15:32:17.615207+00:00] AzuraCast.WARNING: Could not fetch XML data; falling back to public JSON. [] {"station":{"id":6,"name":"Radio Almaina"}}
web_1                      | [2020-12-03T15:32:17.616535+00:00] AzuraCast.ERROR: Request returned status code 404. {"body":""} {"station":{"id":6,"name":"Radio Almaina"}}
web_1                      | [2020-12-03T15:32:17.621179+00:00] AzuraCast.ERROR: Request returned status code 404. {"body":""} {"station":{"id":6,"name":"Radio Almaina"}}
web_1                      | [2020-12-03T15:32:17.621790+00:00] AzuraCast.ERROR: Cannot process media file at path "done": MIME type "text/plain" is not processable. {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []
web_1                      |
web_1                      | In Connection.php line 393:
web_1                      |
web_1                      |   Could not delete message "1607009537284-0" from the redis stream.
web_1                      |
web_1                      |
web_1                      | queue:process [--worker-name WORKER-NAME] [--] [<runtime>]
web_1                      |
web_1                      | [2020-12-03T15:32:19.007729+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":300,"workerName":"app_worker_0"} []
web_1                      |
web_1                      | In Connection.php line 374:
web_1                      |
web_1                      |   Could not acknowledge redis message "1607009537561-0".
web_1                      |
web_1                      |
web_1                      | queue:process [--worker-name WORKER-NAME] [--] [<runtime>]
web_1                      |
web_1                      | [2020-12-03T15:32:20.761809+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":300,"workerName":"app_worker_0"} []
web_1                      | [2020-12-03T15:32:21.013149+00:00] AzuraCast.ERROR: Cannot process media file at path "03 - Only For The Weak": ["Could not find valid MPEG synch before end of file"] {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []
web_1                      | [2020-12-03T15:32:21.056712+00:00] AzuraCast.ERROR: Cannot process media file at path "04 How Many Times": ["Invalid MPEG audio header (ff ff ff ff ) at offset 13820","Invalid MPEG audio header (ff ff ff fe ) at offset 13821","Invalid MPEG audio header (ff ff fe bf ) at offset 13822","Invalid MPEG audio header (ff fe bf a1 ) at offset 13823","Invalid MPEG audio header (ff ff ff ff ) at offset 13929","Invalid MPEG audio header (ff ff ff fa ) at offset 13930","Invalid MPEG audio header (ff ff fa 77 ) at offset 13931","Invalid MPEG audio header (92 49 12 00 ) at offset 14221","Invalid MPEG audio header (ff e6 3f a7 ) at offset 13966"] {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []
web_1                      | [2020-12-03T15:32:21.103631+00:00] AzuraCast.ERROR: Cannot process media file at path "03 While My Guitar Gently Weeps": ["Invalid MPEG audio header (ff ff ff ff ) at offset 14027","Invalid MPEG audio header (ff ff ff ff ) at offset 14028","Invalid MPEG audio header (ff ff ff ff ) at offset 14029","Invalid MPEG audio header (ff ff ff ff ) at offset 14030","Invalid MPEG audio header (ff ff ff fe ) at offset 14031","Invalid MPEG audio header (ff ff fe 04 ) at offset 14032","Invalid MPEG audio header (fe 04 a0 86 ) at offset 14034","Invalid MPEG audio header (ff ff ff ff ) at offset 14058","Invalid MPEG audio header (ff ff ff ff ) at offset 14059","Invalid MPEG audio header (ff ff ff ff ) at offset 14060","Invalid MPEG audio header (ff ff ff ff ) at offset 14061","Invalid MPEG audio header (ff ff ff a7 ) at offset 14062","Invalid MPEG audio header (8c 00 00 00 ) at offset 14387"] {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []
web_1                      | [2020-12-03T15:32:31.499780+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data [] []
web_1                      | [2020-12-03T15:32:34.989509+00:00] AzuraCast.ERROR: Cannot process media file at path "05 Goodbye Elenore.mp3": MIME type "application/x-font-gdos" is not processable. {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []
web_1                      | [2020-12-03T15:32:44.533189+00:00] AzuraCast.ERROR: Cannot process media file at path "02 Don't Chain My Heart": ["Invalid MPEG audio header (ff ff ff ff ) at offset 13744","Invalid MPEG audio header (ff ff ff ff ) at offset 13745","Invalid MPEG audio header (ff ff ff ff ) at offset 13746","Invalid MPEG audio header (ff ff ff ff ) at offset 13747","Invalid MPEG audio header (ff ff ff ff ) at offset 13748","Invalid MPEG audio header (ff ff ff ff ) at offset 13749","Invalid MPEG audio header (ff ff ff ff ) at offset 13750","Invalid MPEG audio header (ff ff ff 55 ) at offset 13751","Invalid MPEG audio header (ff ff ff ff ) at offset 13912","Invalid MPEG audio header (ff ff ff ff ) at offset 13906","Invalid MPEG audio header (ff ff ff ff ) at offset 13907","Invalid MPEG audio header (ff ff ff ff ) at offset 13908","Invalid MPEG audio header (ff ff ff ff ) at offset 13909","Invalid MPEG audio header (ff ff ff ff ) at offset 13910","Invalid MPEG audio header (ff ff ff ff ) at offset 13911","Invalid MPEG audio header (ff ff ff ff ) at offset 13913","Invalid MPEG audio header (ff ff ff ff ) at offset 13914","Invalid MPEG audio header (ff ff ff ff ) at offset 13915","Invalid MPEG audio header (ff ff ff 15 ) at offset 13916","Invalid MPEG audio header (ff ff fa 7b ) at offset 13949","Invalid MPEG audio header (ff ff ff ff ) at offset 13938","Invalid MPEG audio header (ff ff ff ff ) at offset 13939","Invalid MPEG audio header (ff ff ff ff ) at offset 13940","Invalid MPEG audio header (ff ff ff ff ) at offset 13941","Invalid MPEG audio header (ff ff ff ff ) at offset 13942","Invalid MPEG audio header (ff ff ff ff ) at offset 13943","Invalid MPEG audio header (ff ff ff ff ) at offset 13944","Invalid MPEG audio header (ff ff ff ff ) at offset 13945","Invalid MPEG audio header (ff ff ff ff ) at offset 13946","Invalid MPEG audio header (ff ff ff ff ) at offset 13947","Invalid MPEG audio header (ff ff ff fa ) at offset 13948","Invalid MPEG audio header (00 00 00 00 ) at offset 14383"] {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []
web_1                      | [2020-12-03T15:32:44.553075+00:00] AzuraCast.ERROR: Cannot process media file at path "07 White Sister.mp3": MIME type "application/x-font-gdos" is not processable. {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []
web_1                      | [2020-12-03T15:32:46.654048+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data [] []
web_1                      | [2020-12-03T15:33:02.092655+00:00] AzuraCast.NOTICE: Running sync task: 1-Minute Sync [] []
web_1                      | [2020-12-03T15:33:02.124470+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data [] []
web_1                      |
web_1                      | In AbstractMySQLDriver.php line 51:
web_1                      |
web_1                      |   An exception occurred while executing 'UPDATE station_playlists SET played_
web_1                      |   at = ? WHERE id = ?' with params [1607010362, 284]:
web_1                      |
web_1                      |   SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to
web_1                      |   get lock; try restarting transaction
web_1                      |
web_1                      |
web_1                      | In Exception.php line 18:
web_1                      |
web_1                      |   SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to
web_1                      |   get lock; try restarting transaction
web_1                      |
web_1                      |
web_1                      | In PDOStatement.php line 115:
web_1                      |
web_1                      |   SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to
web_1                      |   get lock; try restarting transaction
web_1                      |
web_1                      |
web_1                      | sync:run [<task>]

**Comment by emilio-pro** [comment]
I've got the same/similar problem. 
<img width="932" alt="afbeelding" src="https://user-images.githubusercontent.com/26246547/101058689-af248880-358d-11eb-9113-144d8bd6f216.png">
But when I run manually, i get:
<img width="543" alt="afbeelding" src="https://user-images.githubusercontent.com/26246547/101058804-d67b5580-358d-11eb-8474-fc705f5b6ce4.png">

I'm on Docker, v0.11 Stable, running on a Synology (which worked fine until now).

Unfortunately, the log doesn't show much:
<img width="604" alt="afbeelding" src="https://user-images.githubusercontent.com/26246547/101059299-66210400-358e-11eb-9892-f059a5a498c4.png">

The log file in azuracast itself shows:
`[2020-12-03T16:39:02.744538+00:00] AzuraCast.NOTICE: Running sync task: 1-Minute Sync [] []
[2020-12-03T16:39:17.537550+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data [] []
[2020-12-03T16:39:32.707702+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data [] []
[2020-12-03T16:39:47.709590+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data [] []
[2020-12-03T16:40:02.995098+00:00] AzuraCast.NOTICE: Running sync task: 5-Minute Sync [] []
[2020-12-03T16:40:03.019489+00:00] AzuraCast.NOTICE: Failed to acquire the "{resource}" lock. Someone else already acquired the lock. {"resource":{"Symfony\\Component\\Lock\\Key":"lock_sync_medium"}} []
[2020-12-03T16:40:03.441692+00:00] AzuraCast.NOTICE: Running sync task: 1-Minute Sync [] []
[2020-12-03T16:40:03.553882+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data [] []
[2020-12-03T16:40:17.549186+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data [] []`

Not sure how to proceed.

**Comment by Vaalyn** [comment]
Please update your installation to the newest version `v0.11.2` from 2020-12-12 and check if this issue is still happening. There have been some fixes regarding media processing.

Those `Cannot process media file at path ... Invalid MPEG audio header ...` errors are happening due to invalid data in the file mentioned in those errors. That is not something that we are currently able to fix since this is an error reported by the library that we use to process ID3 metadata so you'll have to re-encode those files.
There have been a few issues here on GitHub from people who have also encountered this error with some files. For more information about this you can check out this issue were I wrote about the background of this problem: https://github.com/AzuraCast/AzuraCast/issues/3263

**Comment by emilio-pro** [comment]
Thx @Vaalyn. The v0.11.2 has fixed my problem indeed. And I do see some `Invalid MPEG audio header` errors, so I'll re-encode those. Unfortunately, all my album art is gone now but I guess this I a different issue.

**Comment by Vaalyn** [comment]
> Unfortunately, all my album art is gone now but I guess this I a different issue.

That's most likely unrelated to this issue here.
Could it be that you added the album art through AzuraCast or do your files have album art on them already from before uploading them?

If you added them through AC it might be that you did that before we fixed an issue in commit 5e007fe4fd00350af54709635cb6cd69251d90d9 that caused AC to not write metadata changes back to the file. In that case there is most likely nothing we can do to fix this. If the files already have album art from before uploading them I'd recommend you to create a new issue.

Since this issue here is resolved now I'll close it.

**Comment by IKHNetworks** [comment]
I actually experience the same issue exactly as described. The only difference between this thread and mine is I'm not using docker. Everything else though - is the same issue verbatim. I'm on the latest release as of February 1st 2021
