### ISSUE TITLE
ansible install fail on Install Composer Dependencies (composer.lock Permission denied)

### ISSUE THREAD

**Issue by Psychoses** [AzuraCast/AzuraCast#3496]
**Using Docker installation method** and **Host Operating System**
i don't use docker, my env is proxmox => lxc => ubuntu 20.04 => traditional ansible install

**AzuraCast version**
 0.11
58a16112cfd403486fdb01f43ec3da1ede8ebdcb

**Describe the bug** and **To Reproduce**
- Use install.sh
- On `TASK [composer : Install Composer Dependencies (Production)] *******************`
- i get `fatal: [localhost]: FAILED!` `"msg": "non-zero return code"`

**Expected behavior**
No fail

**Relevant Logs**
https://pastebin.com/xpC9jYAs

**Temp workarround**
executing again the command `ansible-playbook util/ansible/deploy.yml --inventory=util/ansible/hosts --extra-vars "app_env=$APP_ENV"` is needed for get install sucess

**Additional context**
this bug are already referenced here
https://github.com/AzuraCast/AzuraCast/issues/3411#issuecomment-727076991

**Comment by Vaalyn** [comment]
This is most likely unrelated to the issue your mentioned.

From your logs this is the part why the composer update failed:
```
file_put_contents(./composer.lock): failed to open stream: Permission denied
```

This looks like a permission issue. Make sure that `composer.lock` is writable by the azuracast user.

Also you'll most likely need to manually upgrade composer to v2 since we currently have no update routine for Ansible users that upgrades it automatically. You can do this by running: `sudo composer self-update --2`

**Comment by blindndangerous** [comment]
Perfect, the update to composer fixed it for me. Thanks @Vaalyn

**Comment by Psychoses** [comment]
sorry this is all a bit obscure to me

> This is most likely unrelated to the issue your mentioned.

Look on the comment not all issue. On the @webafrancois post  https://github.com/AzuraCast/AzuraCast/issues/3411#issuecomment-727076991 we can see the `file_put_contents(./composer.lock): failed to open stream: Permission denied`

so i have replace

```
(some stuff...)
ansible-playbook util/ansible/deploy.yml --inventory=util/ansible/hosts --extra-vars "app_env=$APP_ENV"
(get fail  `composer.lock Permission denied`)
```

with

```
(some stuff...)
useradd azuracast
chown azuracast:azuracast composer.lock
ansible-playbook util/ansible/deploy.yml --inventory=util/ansible/hosts --extra-vars "app_env=$APP_ENV"
```

all seems be ok on this point. the fail `composer.lock Permission denied` seems have disapear now.
after that if i do

```
cd /var/azurcast/www
sudo composer self-update --2
i get : 
You are already using composer version 2.0.8 (2.x channel).
```

@Vaalyn
So that the good way ?
create azuracast user, chown composer.lock before the ansible-playbook command ?
and for the `sudo composer self-update --2`, i don't need it ?

**Comment by SlvrEagle23** [comment]
This should be fixed as of the most recent updates, which ensure the latest version of Composer is installed.
