### ISSUE TITLE
Web page completly down after letsencrypt activation

### ISSUE THREAD

**Issue by shogd3838** [AzuraCast/AzuraCast#3497]
Hello I have activated letsencrypt on my azuracast installation and now the web part is down. No page either on port 80 or 443

Maybe it is due to my installation having a docker-compose.override.yml where I change the volumes path for web and radio ?
version: '2.2'

services:
  web:
    volumes:
      - /MYPATH:/var/azuracast/stations

  stations:
    volumes:
      - /MYPATH:/var/azuracast/stations

I want to know as a fast workaround if I can rollback to before letsencrypt activation by recreating the web and nginx proxy docker ? I have a certain knowledge in docker and I want to know if I can modify by hand the docker-compose.yml file and recreate the web and nginx-proxy docker to use port 80 without searching for certificate.
I don't want to rebuild everything because my streaming is still working fine on port 8000 

Thank you all in advance for your help.

**Comment by shogd3838** [comment]
Hi I succeed to fix my web access by following this solution 
https://github.com/AzuraCast/AzuraCast/issues/2855

But now when I connect via https it says the site is unsecure because the certificate is from localhost !
![image](https://user-images.githubusercontent.com/73856627/101089428-6e406a00-35b5-11eb-97b8-bbe882411e6e.png)

**Comment by Deiiji** [comment]
How have you installed your certificate? Ansible or docker install?

**Comment by shogd3838** [comment]
I have use the command from Azuracast documentation. ./docker.sh letsencrypt-create
