### ISSUE TITLE
Slim Application Error after update

### ISSUE THREAD

**Issue by Likeandfeel** [AzuraCast/AzuraCast#3502]
Hi Team

I get same error as ticket #3327
During update 

_TASK [composer : Ensure Composer is up-to-date] **************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'composer_installed.changed !== True' failed. The error was: template error while templating string: unexpected '='. String: {% if composer_installed.changed !== True %} True {% else %} False {% endif %}\n\nThe error appears to be in '/var/azuracast/www/util/ansible/roles/composer/tasks/main.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Ensure Composer is up-to-date\n  ^ here\n"}_

And when i try to connect me to admin i get 

_Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.

Go Back_

I dont use contenair or docker and i have check log and no error are report, only seem's i dont get correct template.

My environment is : "Running Ansible on localhost with OS Ubuntu bionic 18.04 x86_64 (production)"
And i try to update >> Updating AzuraCast (Environment: production, Update revision: 58)

Diffusion seems working, but admin panel is off...

Thanks in advance for your help
Best regards

**Comment by SlvrEagle23** [comment]
@Likeandfeel This should be fixed as of the latest update.

**Comment by Likeandfeel** [comment]
Hi SlvrEagle23

Thanks for your answer, when i do this i get 

fatal: [localhost]: FAILED! => {"changed": true, "cmd": "composer self-update --2", "delta": "0:00:00.136137", "end": "2020-12-04 11:37:50.984954", "msg": "non-zero return code", "rc": 1, "start": "2020-12-04 11:37:50.848817", "stderr": "\n                                                          \n  [Symfony\\Component\\Console\\Exception\\RuntimeException]  \n  The \"--2\" option does not exist.                        \n                                                          \n\nself-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--set-channel-only] [--] [<version>]", "stderr_lines": ["", "                                                          ", "  [Symfony\\Component\\Console\\Exception\\RuntimeException]  ", "  The \"--2\" option does not exist.                        ", "                                                          ", "", "self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--set-channel-only] [--] [<version>]"], "stdout": "", "stdout_lines": []}

i'm on Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer version 1.7.2 2018-08-16 16:57:12

It's the issue ? 

Thanks a lot
Best regards

**Comment by SlvrEagle23** [comment]
@Likeandfeel Ah, that's a new error. I've just pushed a fix that should help with that as well. Thanks for your patience.

**Comment by Likeandfeel** [comment]
Hi SlvrEagle23

yes i confirm you, no its works !
I just get the update of 
util/ansible/roles/composer/tasks/main.yml | 9 +--------

Thank you so much for your reactivity :)
Best regards
