### ISSUE TITLE
install stop Redis

### ISSUE THREAD

**Issue by drno88** [AzuraCast/AzuraCast#3506]
**Using Docker installation method**
No

**AzuraCast version**
0.10.4 , 0.11

**Host Operating System**
Ubuntu 16.04 x32 !! , Ubuntu 18.04 x32 !!

**Describe the bug**
On a clean install, the following error occurs

>>fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service redis: host"}
**To Reproduce** <<

I followed this instruction
https://www.azuracast.com/install/ansible.html#installing

[install.sh.log](https://github.com/AzuraCast/AzuraCast/files/5644657/install.sh.log)

>>>DOCKER<<<
I also tried to install via docker, but my system does not officially support it.
I followed this instruction and docker, docker-compose was installed.
https://gitlab.com/docker-32bit/ubuntu
or
https://stackoverflow.com/a/51936287
But docker-compose is version 1.8
And the yml file is 2. * ...
So I am getting the error 

> Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.<

Unfortunately, my docker knowledge is not enough to rewrite the yml file to a different version, and I'm not sure if this is possible ...
I would be fine with installing Ansible if it works.
Thank you in advance!

**Comment by ogrenci01** [comment]
Hi @drno88 ;

With the latest update, the installation error has been resolved for Ansible. Please try setup again.

**Comment by drno88** [comment]
Everything worked. Thank you so much for your work!
