### ISSUE TITLE
my playlists don't start on time

### ISSUE THREAD

**Issue by Dave-porter** [AzuraCast/AzuraCast#3508]
**Using Docker installation method**

**AzuraCast version**
 **v0.10.3**

**Host Operating System**

**Describe the bug**

**hello, I made a lot of playlists in my Azuracast they are all planned. I'm not a great professional of this Soft but I like it a lot.

for example:
08:00 10:00 playlist X
10:00 12:00 playlist y
etc...

My problem is that they don't start automatically at the scheduled time.

Any ideas?**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
Since you are using AzuraCast in version `v0.10.3` I'd recommend you to update to the newest stable version `v0.11.2` since there have been quite a lot of fixes released in the time since Jun 21 including a rewrite of the AutoDJ scheduler.

**Comment by Dave-porter** [comment]
Thank you for your information. I can't find where I can get the command
lists to update AzuraCast... The server was created directly via the order
at the provider...

**Comment by Dave-porter** [comment]
ok I've figured out how to get into the console on the "hetzner" site but
I'm afraid I'm doing something wrong I'm not very good at code line 😢

**Comment by Vaalyn** [comment]
Check out our docs about updating AzuraCast: https://docs.azuracast.com/en/getting-started/updates

The process is quite simple. Since you are on a quite old version the update can take some time though. Just let it run until it is completed.

**Comment by Dave-porter** [comment]
one more thing... If i update AzuraCast i lost all in this ? (playlist and
mp3)

**Comment by Vaalyn** [comment]
Updating AzuraCast should never delete your playlists or media. We do advise you however to always make a backup before updating so that if something unexpectedly goes wrong you can restore from that.

**Comment by Dave-porter** [comment]
Hello

thank you for all your information! I was able to update Azuracast this
morning and everything went very well.

Have a nice day and thanks again for your help

**Comment by Dave-porter** [comment]
I have one more question if I may...

On one of my playlists I have enabled "Include on demand functionality in
the player" it's the only one that is assigned to that, but the songs in
the other playlists are also available on demand to the listeners.

How can I have only the list of this playlist?

after that i think i should not bother you anymore :)

Thanks again

**Comment by Dave-porter** [comment]
Hello, I still have the same problem with Azura in version V.0.12.2

When I launch the broadcasting service and the liquid soap the stream stays
off line. I know that there is maintenance with shoutcast but this is not
the first time it happens to me. Would you have a solution ?

Thanks and have a nice day !

Best regards
