### ISSUE TITLE
Let’s Encrypt fails : can’t reach AzuraCast setup page in HTTPS mode

### ISSUE THREAD

**Issue by Keepshango** [AzuraCast/AzuraCast#3514]
Hello,

**MY ENVIRONMENT**
Machine : VPS SSD 2
OS distro : Ubuntu 18.04
Web server : apache2
Cpanel : ISP Config 3.2

**AZURACAST PORTS**
HTTP : 442
HTTPS : 8092

When I want to access the Azuracast setup page (Firefox browser), **althought I am connecting with URL in HTTPS mode**, I am returned a **security risk alert page** saying that this connection is not securized, and alerting any potential vistor that he may access the desired page at his own risk !

**MORE DETAILS** 
• **https**://IP-ADDRESS:8092 (security risk message)
• **https**://webradio.mydomain.net:8092 (security risk message)
• **http**://IP-ADDRESS:8092 (error 400 : bad request)
• **http**://webradio.mydomain.net:8092 (error 400 : bad request)

**How can I get rid of such this security alert page ?**

Regards

**Comment by Vaalyn** [comment]
The automatic Let's Encrypt integration is not supported on non-default ports as the ACME protocol that Let's Encrypt uses requires you to use the default ports 80 and 443.

See https://www.azuracast.com/extending/letsencrypt.html#important-considerations

On that page there is also an entry about using your own certificates.
