### ISSUE TITLE
Update Error (Ansible v0.11.1)

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#3516]
**Using Docker installation method**
No

**AzuraCast version**
Latest

**Host Operating System**
Ubuntu 18.04 LTS x64

**Describe the bug**
`TASK [composer : Install Composer Dependencies (Production)] ***********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "composer install --no-dev --optimize-autoloader", "delta": "0:00:11.959386", "end": "2020-12-08 12:25:59.927481", "msg": "non-zero return code", "rc": 1, "start": "2020-12-08 12:25:47.968095", "stderr": "Installing dependencies from lock file\nVerifying lock file contents can be installed on current platform.\nPackage operations: 0 installs, 1 update, 0 removals\n  - Upgrading doctrine/dbal (2.10.2 => 2.12.1):     Update of doctrine/dbal failed\n\n                                                                                                                    \n  [RuntimeException]                                                                                                \n  Could not delete /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Event/SchemaCreateTableEventArgs.php:  \n                                                                                                                    \n\ninstall [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...", "stderr_lines": ["Installing dependencies from lock file", "Verifying lock file contents can be installed on current platform.", "Package operations: 0 installs, 1 update, 0 removals", "  - Upgrading doctrine/dbal (2.10.2 => 2.12.1):     Update of doctrine/dbal failed", "", "                                                                                                                    ", "  [RuntimeException]                                                                                                ", "  Could not delete /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Event/SchemaCreateTableEventArgs.php:  ", "                                                                                                                    ", "", "install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]..."], "stdout": "", "stdout_lines": []}
`

**Additional context**
I know you have no support for Ansible. I'm so sorry I have to use Ansible. I wish the AzuraCast team success.

**Comment by NicoxDJ** [comment]
Try "./update.sh --full". Mostly for me the now full update is not working. The full is needing more time, because its rebuilding everything, but it's sure it will work after that.

**Comment by ogrenci01** [comment]
Hi @NicoxDJ ;

I've tried everything AzuraCast allows. I've done it many times. The problem still persists.

**Comment by NicoxDJ** [comment]
@ogrenci01 OK, try than to update the composer manually: `sudo composer self-update --2` and than hit the update.

**Comment by SlvrEagle23** [comment]
@ogrenci01 You may need to try setting the vendor permissions recursively, like:

```
sudo chown -R azuracast:www-data /var/azuracast/www/vendor
```

**Comment by ogrenci01** [comment]
Hi @SlvrEagle23 ;

I tried this and the output is as follows:

`chown: changing ownership of '/var/azuracast/www/vendor/doctrine/dbal/lib/Doctri                                                                                        ne/DBAL/Event/SchemaCreateTableEventArgs.php': Structure needs cleaning
chown: changing ownership of '/var/azuracast/www/vendor/doctrine/dbal/lib/Doctri                                                                                        ne/DBAL/Event/SchemaIndexDefinitionEventArgs.php': Structure needs cleaning
chown: changing ownership of '/var/azuracast/www/vendor/doctrine/dbal/lib/Doctri                                                                                        ne/DBAL/Event/SchemaColumnDefinitionEventArgs.php': Structure needs cleaning
chown: changing ownership of '/var/azuracast/www/vendor/doctrine/dbal/lib/Doctri                                                                                        ne/DBAL/Event/SchemaDropTableEventArgs.php': Structure needs cleaning
chown: changing ownership of '/var/azuracast/www/vendor/doctrine/dbal/lib/Doctri                                                                                        ne/DBAL/Event/SchemaEventArgs.php': Structure needs cleaning
chown: changing ownership of '/var/azuracast/www/vendor/doctrine/dbal/lib/Doctri                                                                                        ne/DBAL/Event/SchemaCreateTableColumnEventArgs.php': Structure needs cleaning
chown: changing ownership of '/var/azuracast/www/vendor/doctrine/dbal/lib/Doctri                                                                                        ne/DBAL/Statement.php': Structure needs cleaning
chown: changing ownership of '/var/azuracast/www/vendor/doctrine/dbal/lib/Doctri                                                                                        ne/DBAL/Events.php': Structure needs cleaning
chown: cannot access '/var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/                                                                                        Tools': Structure needs cleaning
chown: cannot access '/var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/                                                                                        Sharding/ShardChoser': Structure needs cleaning
chown: changing ownership of '/var/azuracast/www/vendor/doctrine/dbal/lib/Doctri                                                                                        ne/DBAL/Sharding/SQLAzure/SQLAzureShardManager.php': Structure needs cleaning
chown: cannot access '/var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/                                                                                        Sharding/SQLAzure/Schema': Structure needs cleaning
chown: changing ownership of '/var/azuracast/www/vendor/doctrine/dbal/lib/Doctri                                                                                        ne/DBAL/Sharding/ShardingException.php': Structure needs cleaning
chown: changing ownership of '/var/azuracast/www/vendor/doctrine/dbal/lib/Doctri                                                                                        ne/DBAL/Sharding/ShardManager.php': Structure needs cleaning
chown: cannot access '/var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/                                                                                        Exception': Structure needs cleaning`

When I tried to update later, the following problem occurred:

https://prnt.sc/w0padh

**Comment by SlvrEagle23** [comment]
@ogrenci01 I'm looking that up and it strongly suggests filesystem corruption on the part of your server. This may be something you need to look into at a provider level.

**Comment by ogrenci01** [comment]
Hi @SlvrEagle23 ;

We use a physical server by virtualizing it. The server ram was 8 GB. After doing this to 32 GB Azuracast gave a "Slim Error" error. I have updated. I've seen all these mistakes. We cannot use the server. Should I reinstall?

**Comment by SlvrEagle23** [comment]
@ogrenci01 I cannot provide you support with your server itself. Even the Ansible installation itself is not supposed to be supported by me to this extent, but I've gone out of my way to try to support it all the same; I can't provide support for servers I don't manage, though.

**Comment by ogrenci01** [comment]
Hi @SlvrEagle23 ;

I know you don't support Ansible installation. I am installing Azuracast for personal use. I have no commercial purpose. I love Azuracast and your team.

I have not need any special support. I will rent a virtual server for re-installation. I will test for issues [here](https://github.com/AzuraCast/AzuraCast/issues/3517#issuecomment-743326274).

**Comment by ogrenci01** [comment]
Hi @SlvrEagle23 ;

The problem is caused by the file system. I'm sure of that now. The "vendor" folder was empty. I wanted to add something to it, but I saw a mistake. You are right and I apologize for keeping you busy. I turn this off.
