### ISSUE TITLE
Install Error (Ansible v0.11.1)

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#3517]
**Using Docker installation method**
No

**AzuraCast version**
latest

**Host Operating System**
Ubuntu 18.04 LTS x64

**Describe the bug**
During installation, Liquidsoap gives the error in the picture. Installation does not complete.

**Screenshots**
https://prnt.sc/vy4es8

**Device(s):**
 - Device: PC
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: latest

**Additional context**
I know you have no support for Ansible. I'm so sorry I have to use Ansible.

**Comment by SlvrEagle23** [comment]
@ogrenci01 That message isn't an error, it's just checking on the long-running process of installing Liquidsoap; it should complete eventually.

**Comment by ogrenci01** [comment]
Thank you very much for your message. I'm so sorry for keeping you busy. Completed but another problem occurred.

This: https://prnt.sc/vy6dss

**Comment by anmiefan** [comment]
here is another error redis worked but this came up

fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/AzuraCast/bin/console azuracast:setup", "delta": "0:00:00.500598", "end": "2020-12-10 06:22:02.092980", "msg": "non-zero return code", "rc": 1, "start": "2020-12-10 06:22:01.592382", "stderr": "\nIn AbstractMySQLDriver.php line 61:\n                                                                               \n  An exception occurred while executing 'SELECT t0.setting_key AS setting_key  \n  _1, t0.setting_value AS setting_value_2 FROM settings t0':                   \n                                                                               \n  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  \n  gs' doesn't exist                                                            \n                                                                               \n\nIn Exception.php line 18:\n                                                                               \n  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  \n  gs' doesn't exist                                                            \n                                                                               \n\nIn PDOConnection.php line 125:\n                                                                               \n  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  \n  gs' doesn't exist                                                            \n                                                                               \n\nazuracast:setup [--update] [--load-fixtures] [--release]", "stderr_lines": ["", "In AbstractMySQLDriver.php line 61:", "                                                                               ", "  An exception occurred while executing 'SELECT t0.setting_key AS setting_key  ", "  _1, t0.setting_value AS setting_value_2 FROM settings t0':                   ", "                                                                               ", "  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  ", "  gs' doesn't exist                                                            ", "                                                                               ", "", "In Exception.php line 18:", "                                                                               ", "  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  ", "  gs' doesn't exist                                                            ", "                                                                               ", "", "In PDOConnection.php line 125:", "                                                                               ", "  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin  ", "  gs' doesn't exist                                                            ", "                                                                               ", "", "azuracast:setup [--update] [--load-fixtures] [--release]"], "stdout": "", "stdout_lines": []}

**Comment by anmiefan** [comment]
what dose that error above mean the one i typed 13 hours aga so i can fix it my self

**Comment by SlvrEagle23** [comment]
The various issues with Ansible installations should be fixed as of the latest update. Please try installing or updating again and let me know if you still encounter these issues.

**Comment by ogrenci01** [comment]
Hi @SlvrEagle23 ;

A lot of thanks for everything. Azuracast is setup corretly. I know you have no support for Ansible. But I have to use Ansible. Sorry to keep you busy but Update problem persists.

**Comment by SlvrEagle23** [comment]
@ogrenci01 Which problem? Please be more detailed. There are a lot of issues reported that have been fixed with Ansible.

**Comment by ogrenci01** [comment]
Hi @SlvrEagle23 ;

Azuracast now installs without any problems. I want to report some problems I encountered after installation.

**1-)** I installed Azuracast on a clean Ubuntu 16.04.
This was error free. I updated right after the installation.
The update remained in the "**Run AzuraCast Setup (Update Mode)**" phase.
I waited too long but the phase was not finished (**image-1**).
Broadcast software was not working because the stage was not completed (**image-2**).
I restarted the server and everything was working normally.

**2-)** I added a station.
Nothing happens after pressing the "**Restart to Apply Changes**" button.
The process is not completed (**image-3**).
Broadcasting software stops (**image-4**).
Azuracast won't work.
Server CPU load and RAM are normal.
Azuracast becomes unusable.

I don't know if I should report these as a new notification.

I apologize for keeping you too busy. I have to use Ansible. I'm so sorry for this.

**image-1**: ![image-1](https://user-images.githubusercontent.com/24523085/101934837-32c62100-3bef-11eb-9961-689ea0436dea.jpg)

**image-2**: 
![image-2](https://user-images.githubusercontent.com/24523085/101934951-57ba9400-3bef-11eb-9f87-c418c0150084.jpg)

**image-3**: 
![image-3](https://user-images.githubusercontent.com/24523085/101934972-5f7a3880-3bef-11eb-8029-daa41ff83d93.jpg)

**image-4**: 
![image-4](https://user-images.githubusercontent.com/24523085/101934990-65701980-3bef-11eb-8ed4-0c2c88be422f.jpg)

**Comment by SlvrEagle23** [comment]
@ogrenci01 These issues are likely different and not caused by the same problem you were experiencing during installation.

Please create a new issue, and in the new issue be sure to include logs from both Icecast and Liquidsoap, as they may indicate what the problem is.

**Comment by ogrenci01** [comment]
Hi @SlvrEagle23 ;

I will do a reinstallation and try everything from scratch. I report the problems.

I do not want to keep you busy. I am very sorry for that and apologize to you.
