### ISSUE TITLE
Web Hooks

### ISSUE THREAD

**Issue by technplus** [AzuraCast/AzuraCast#3520]
**Using Docker installation method**

Yes

**AzuraCast version**

Rolling Release #17068fb

**Host Operating System**

Debian 10

**Describe the bug**

Got a 500 error when trying to access the Web Hooks page

**To Reproduce**

1. Go to the station's manager page of any station, by clicking on 'MANAGE' on the right side of any station
2. Then click on 'Web Hooks' in the left side menu

**Expected behavior**

Load the Web Hooks page

**Screenshots**
![azuracast_webhooks_scrsht](https://user-images.githubusercontent.com/59397833/101529964-44919500-395f-11eb-9b17-51ff108eda5b.png)

**Device(s):**
 - Device:  
Desktop
 - OS: 
Windows 10 Enterprise
 - Browser: 
Edge and Brave
 - Version: 
Latest

**Comment by xewl** [comment]
Confirmed to also be the case on v0.11.1

**Comment by SlvrEagle23** [comment]
@technplus @xewl This should be fixed as of the latest rolling-release version. We'll likely ship a new minor stable version with bug fixes in the near future.
