### ISSUE TITLE
What is administrator username?

### ISSUE THREAD

**Issue by ttodua** [AzuraCast/AzuraCast#3521]
I've looked through  https://www.azuracast.com/help/ but cant find the answer.
So, on the right side, there is "broadcasting" panel, where passwords are disclosed : https://i.imgur.com/TP5aV6n.png
however, what are admin usernames for them? I couldnt find.

**Comment by ogrenci01** [comment]
Hi @ttodua;

Please, would you try this: **admin** ?

Good luck :)
