### ISSUE TITLE
Storage Dropbox

### ISSUE THREAD

**Issue by Takumi86ES** [AzuraCast/AzuraCast#3527]
I am trying to add dropbox but I always get an error.

"App \ Exception \ ValidationException at /var/azuracast/www/src/Controller/Api/AbstractApiCrudController.php L148: Object (App \ Entity \ StorageLocation) .adapter: The value you selected is not a valid choice. (Code 8e179f1b- 97aa-4560-a02f-2a8b42e49df7) "

Can you do a tutorial on how to add this? step by step.

**Comment by SC2Mitch** [comment]
I'll write up some documentation on it soon.

**Comment by SlvrEagle23** [comment]
The main errors with Dropbox storage locations should be resolved. I'm seeing some other errors with listing directories, but I'm not sure if that's a product of my own configuration on Dropbox itself or something else. Will continue to investigate.

**Comment by Takumi86ES** [comment]
> The main errors with Dropbox storage locations should be resolved. I'm seeing some other errors with listing directories, but I'm not sure if that's a product of my own configuration on Dropbox itself or something else. Will continue to investigate.

I tried the latest update and it worked.

The truth is that it works very well and fluently. The problem is that dropbox costs a lot to subscribe.

Very good work. If you add Google Drive it would be great.

**Comment by Takumi86ES** [comment]
> The main errors with Dropbox storage locations should be resolved. I'm seeing some other errors with listing directories, but I'm not sure if that's a product of my own configuration on Dropbox itself or something else. Will continue to investigate.

Is it normal that if I upload something to the Bucket (through Dropbox) it doesn't appear in "Music files" (/ files)?

**Comment by stardevelop** [comment]
It takes a few seconds for the new uploaded files to be appeared in Music Files.
