### ISSUE TITLE
Broken Import from PLS/M3U 

### ISSUE THREAD

**Issue by Ferz0id** [AzuraCast/AzuraCast#3528]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.11.1 Stable 

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
When I do Import from PLS/M3U I get this message:  **An error occurred and your request could not be completed.**

For test I do:
1. Export M3U
2. Then I do "Import" this file 
3. Still get this error

**Relevant Logs**
Logs from Console:
POSThttp://168.119.253.222:85/api/station/1/playlist/56/import
[HTTP/1.1 500 Internal Server Error 113ms]

Error: Request failed with status code 500
    exports http://168.119.253.222:85/static/dist/vendor-959ed73eb6.js:1
    exports http://168.119.253.222:85/static/dist/vendor-959ed73eb6.js:1
    onreadystatechange http://168.119.253.222:85/static/dist/vendor-959ed73eb6.js:1
    exports http://168.119.253.222:85/static/dist/vendor-959ed73eb6.js:1
    exports http://168.119.253.222:85/static/dist/vendor-959ed73eb6.js:1
    exports http://168.119.253.222:85/static/dist/vendor-959ed73eb6.js:1
    promise callback*s.prototype.request http://168.119.253.222:85/static/dist/vendor-959ed73eb6.js:1
    r http://168.119.253.222:85/static/dist/vendor-959ed73eb6.js:1
    exports http://168.119.253.222:85/static/dist/vendor-959ed73eb6.js:1
    doSubmit http://168.119.253.222:85/static/dist/StationPlaylists-0669024bf6.js:1
    He http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    n http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    _wrapper http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    Yr http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    rt http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    ei http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    y http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    f http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    h http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    f http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    h http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    f http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    h http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    f http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    h http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    f http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    zi http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    _update http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    r http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    get http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    fn http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    mount http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    $mount http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    $mount http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    init http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    f http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    f http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    h http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    f http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    zi http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    _update http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    r http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6
    get http://168.119.253.222:85/static/dist/lib/vue/vue-fb19233884.min.js:6

**Device(s):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: mozilla
 - Version: 83

**Comment by emilio-pro** [comment]
Same here.
In fact, to replicate: just try to import anything to the demo https://demo.azuracast.com/station/1/playlists
Same error.

**Comment by picpakdog** [comment]
This bug, combined with this one: https://github.com/AzuraCast/AzuraCast/issues/3451 make playlist management cumbersome, if not impossible. It's easier to just drop your shows altogether.

**Comment by emilio-pro** [comment]
> This bug, combined with this one: #3451 make playlist management cumbersome, if not impossible. It's easier to just drop your shows altogether.

This is an annoying bug indeed, but lets not get to gloomy: @SlvrEagle23 and his team have produced a great package. It is developing at an amazing pace. I'm sure it will be resolved soon

**Comment by picpakdog** [comment]
> > This bug, combined with this one: #3451 make playlist management cumbersome, if not impossible. It's easier to just drop your shows altogether.
> 
> This is an annoying bug indeed, but lets not get to gloomy: @SlvrEagle23 and his team have produced a great package. It is developing at an amazing pace. I'm sure it will be resolved soon

Oh no, I didn't mean the knock the project at all. I've seen it improve with every update in just the short few months I've been using it. This is a setback I'm sure will be looked at soon.
