### ISSUE TITLE
How to upload multiple music songs at once

### ISSUE THREAD

**Issue by demil** [AzuraCast/AzuraCast#353]
Is there possibility to upload songs via ftp and automatically add to some playlist?

**Comment by ckeurk** [comment]
Yes, this is possible using ftp software
example:
server: vps12345. lou.net
User: root
Password:..........

You'll find the media file:
/var/azuracast/stations/ the name of your radio/media/

**Comment by SlvrEagle23** [comment]
@demil Hello!

Depending on what type of installation you're using, there are different ways to connect to your server and upload files in bulk without using the web interface.

If you're using a Docker-based installation, the instructions for setting up a temporary SFTP server are here: https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#access-files-via-sftp-docker-installations

If you're using a traditional install, you can connect via SFTP using the same credentials you use to connect via SSH to your server, then upload files to `/var/azuracast/stations/(your_station_name)/media`
