### ISSUE TITLE
At what location are AzuraCast scr files installed?

### ISSUE THREAD

**Issue by ttodua** [AzuraCast/AzuraCast#3530]
I know that in `/var/lib/docker/volumes/` there are mounted all azuracast volumes. Howeveer, I cant find directly AzuraCast (this repo's  .php files) package inside there. Where I can find , specifically I am searching `AzuraCast/src/` folder, as I have to manually change some AzuraCast php file on my server to achieve my goals (which seem unable by plugin).

BTW:  I was able to find temp folder, but not sure if that's:

```
cd /var
find . -type f -name "*ConfigWriter*"
```
gives something like: 
`./lib/docker/overlay2/cc3a65d8bb1dec694c723e4dc857e3b49d/diff/var/azuracast/www/src/Radio/Backend/Liquidsoap/ConfigWriter.php`

**Comment by ttodua** [comment]
I was able to find temp folder, but not sure if that's:

```
cd /var
find . -type f -name "*ConfigWriter*"
```

**Comment by Vaalyn** [comment]
Manually editing source code files inside a Docker container is pretty useless as those files are part of the Docker image and thus every change to them will be reverted after a restart of the container.

If you need to override anything you can use a volume mount but this is completely unsupported by us so we will not be providing any support on this.

**Comment by ttodua** [comment]
seems I have to write a plugin which automatically checks those source files and injects code if that code not already injected. that's the way to go at this moment.
