### ISSUE TITLE
stream url issue

### ISSUE THREAD

**Issue by amirkhattak** [AzuraCast/AzuraCast#3532]
i tried azura cast on debian 10 ubantu 16 18 20 but i am still facing the stream url not working e.g  https://stream.reinflux.com:8010/radio.mp3

**Comment by Takumi86ES** [comment]
> i tried azura cast on debian 10 ubantu 16 18 20 but i am still facing the stream url not working e.g https://stream.reinflux.com:8010/radio.mp3

I think it's because using Cloudflare.

**Comment by taiBsu** [comment]
what do you mean "not working"? https://stream.reinflux.com seems to be working just fine so maybe the best would be to use a web proxy to access the stream. check your system settings, then you can access the .mp3 stream without having to specify a port.

**Comment by Vaalyn** [comment]
You are using CloudFlare as your DNS provider which is actually blocking traffic on non standard ports so you need to use the `Use Web Proxy for Radio` setting from the `System Settings` page and direct your users to use https://stream.reinflux.com/radio/8010/radio.mp3 instead when using the URL in a desktop media player, etc.
