### ISSUE TITLE
Can't connect remote S3 storage aws

### ISSUE THREAD

**Issue by ImaCrea** [AzuraCast/AzuraCast#3534]
Hello dear crew at AzuraCast,
What a joy when I discovered Azura is now supporting s3 remote storage 💯 

Unfortunately, even though I tried to follow you're great guide I can't manage to connect it. There might be some kind of mistake in my config. Help would be greatly appreciated 🤗 

Here's the error I get :
![Capture d’écran 2020-12-09 à 22 31 04](https://user-images.githubusercontent.com/764332/101691487-0be0e100-3a6f-11eb-8892-13b40e6a945e.jpg)

- user I generated in IAM (aws) has "AmazonS3ReadOnlyAccess" permission.
- values erased in the pic attached for endpoint subdomain and bucketname are the same

**Comment by SlvrEagle23** [comment]
@ImaCrea Try putting a `https://` before your endpoint.

**Comment by ImaCrea** [comment]
ok I found it. endpoint must be **https://s3.amazonaws.com** without the bucketname in it. Because azuracast then take it from the bucketname and adds it to the url.
found it because of the error I got when I added https :) thanks!

**Comment by ImaCrea** [comment]
but not sure what happens next though :/ am I going to find the files in my music browser?

**Comment by ImaCrea** [comment]
Ok I found where to change the station media storage in station admin panel :)
