### ISSUE TITLE
Webhook Error

### ISSUE THREAD

**Issue by pde-system-integration** [AzuraCast/AzuraCast#3535]
Pls help me check why I could not use Webhook.
![image](https://user-images.githubusercontent.com/72959779/101706911-bb907000-3abc-11eb-9d4d-de38ce90fed8.png)
P.S: I install Azuracast in digitalocean droplet

**Comment by Vaalyn** [comment]
Please try updating your installation. There has been a fix for webhooks regarding the environment around 20h ago.

**Comment by pierluigi** [comment]
Can confirm I get the same error now, even on `Rolling Release #5e62a1b (2020-12-10 2:14) • Ansible • PHP 7.4`

<img width="683" alt="image" src="https://user-images.githubusercontent.com/1078545/101728074-b2b99180-3af0-11eb-82fe-8551be511926.png">

**Comment by pde-system-integration** [comment]
I have just updated and restarted but this error still happens

**Comment by Takumi86ES** [comment]
It also occurs to me.

**Comment by pierluigi** [comment]
Can confirm this is now fixed in https://github.com/AzuraCast/AzuraCast/commit/2f4f10ce5737c778ec177bd6962ce1362f106ae4

Kudos @SlvrEagle23 !

**Comment by Vaalyn** [comment]
Closing as fixed
