### ISSUE TITLE
How to enable LiquidSoap plugin, that was disabled during Azuracast installation?

### ISSUE THREAD

**Issue by ttodua** [AzuraCast/AzuraCast#3540]
We want to use some addiitonal features of liquidsoap (in liquidsoap configuration). However when we use the native functions described [here](https://www.liquidsoap.info/doc-1.4.3/reference.html), but in azuracast, when we try to start liquidsoap, we get, i.e.  `Undefined variable **gstreamer**` 

In var\lib\docker\overlay2\1ad06411d05843dc65a492d8a7a76f438dd6a0d7dde46e0c8124c3200c4c1c2a\merged\var\azuracast\.opam\ocaml-system.4.08.1\.opam-switch\build\liquidsoap.1.4.3\liquidsoap.config  (and also in `....opam-switch/config/liquidsoap.config` )

I see some plugins were disabled, i.e. `gstreamer-enabled: false`.  How can I enable them, so liquidsoap (in azuracast) used those features? I tried to manually type `true` instead of `false`,  then restarted docker : `docker ps -q | xargs docker restart` but it didnt work.  When I try to start liquidsoap, it still gives `Undefined variable gstreamer` .

//if that action also needs installation of plugin, is not it possible to install liquidsoap plugin in docker ?  so i dont have to build custom azuracast image (which i will be unable). 

(tldt: i want to enable soundtouch plugin in liquidsoap)

**Comment by SlvrEagle23** [comment]
@ttodua That is not how to change how Liquidsoap is built. You have to rebuild Liquidsoap once your configuration has been updated, and the likely best way to do this is to update the Docker image itself that you're building and using for your `stations` container.

Like many of the issues you've created in the last few days, this is beyond the scope of the free support we provide here.

**Comment by ttodua** [comment]
SlvrEagle, I understand and I've mailed you to make a hire. Can you help or answer to email? thanks.

**Comment by ttodua** [comment]
Sorry for saying this, but it would be nice if anyone write a paragraph of steps what to do. 
I have tried to get a paid support, but even couldnt get that. So, as there is no-one in azurateam to provide som paid support for regular users, would you do a favor for us, and write a paragraph in DOCS, where is described the steps, how to enable liquidsoap plugin/settings (what was disabled in Azura installation).

Or what is a process (how to) `..Update the Docker image itself that you're building and using for your stations container...`. thanks in advance.

**Comment by ttodua** [comment]
The only "custom" way I was able to reach, like described here: https://puvox.software/blog/add-plugin-for-liquidsoap-in-azuracast/

**Comment by ttodua** [comment]
@Vaalyn  
May I advisesomething:
to create aliases, so users will have facilitated using azura. for example, we have to frequently restart azuracast. it would be nice, that during installation, installer (docker.sh) also registered aliases, like:

`alias azuracast-restart='docker-compose down && docker-compose up -d'`

so, we could simply execute: `azuracast-restart` in command line to easily restart azuracast and forget the docker multi-sentence commands.

**Comment by ttodua** [comment]
added bounty, to add ability into azuracast (i.e. additional argument during installation in CLI) which will allow as to add additional plugins for liquidsoap: https://app.bountysource.com/issues/100662334-how-to-enable-liquidsoap-plugin-that-was-disabled-during-azuracast-installation

**Comment by BusterNeece** [comment]
@ttodua If you want to make sure that other packages are installed in the Docker container besides the ones we package, it's possible to do this already.

You'd need a `docker-compose.override.yml` like this:

```yaml
services:
  web:
    volumes:
      - ./packages.sh:/etc/my_init.d/99-packages.sh
```

And then a `packages.sh` file looking something like this:

```bash
#!/bin/bash
set -e
set -x

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install -y --no-install-recommends package-name
```

That'll make something that runs at the startup process any time the container starts up, which should ensure that the packages are always present when the container is running.

**Comment by ttodua** [comment]
Thanks! i will check it tomorrow and will post my followup.

**Comment by ttodua** [comment]
Can you please give an example, how to add i.e. liquidsoap's `sountouch` plugin? 
My goal was, if it could become achievable from cli during installation (https://docs.azuracast.com/en/getting-started/installation/docker) so, before doing `./docker.sh install` we could somehow run i.e. :
```
./docker.sh enable-liquidsoap-plugins soundtouch
./docker.sh install
```
so, the first command did whatever needed, so we dont have to manually create files there or here, as it's tedious because I did bunch of installations and migrating from one vps to another, so it become tedious to manually enable that simple plugin.

**Comment by ttodua** [comment]
@BusterNeece is there any way to add bounty on FR? i'll send $50 on paypal if you can add this option somehow, so we could add some option during azuracast installation and it did the trick.
