### ISSUE TITLE
Audit log overflow since the update

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#3545]
Hi,

I am running docker installation. Since I updated today, I found the audit log is overflown with "SettingsTable"
Settings information. 
Field shown there are mostly "nowplaying" and "syncShortLastRun" so there is a new entry for each song played.
Until now this feature was useful to show user changes, not automatic ones. 

![image](https://user-images.githubusercontent.com/25333002/101918486-b5d48080-3bc9-11eb-978c-e1c423c55261.png)

**Comment by SlvrEagle23** [comment]
@griffon56 Definitely a valid issue, and it wound up flooding my audit log folder with tens of thousands of records too. Yikes!

The latest update ignores the automated settings and won't audit log their changes, and also cleans up the existing spurious entries from the audit log.

Thank you for your report.

**Comment by griffon56** [comment]
Many thanks @SlvrEagle23 for the quick fix - after update the issue is not there anymore and the audit log is cleant.
