### ISSUE TITLE
Not working properly with music on S3 remote storage

### ISSUE THREAD

**Issue by ImaCrea** [AzuraCast/AzuraCast#3546]
Hello :)
Continuing my exploration of S3 storage...

**AzuraCast version**
v0.11.1 Stable • Docker • PHP 7.4 

**Host Operating System**
Debian 10

**Describe the bug**
After a certain moment,Azuracast stops playing music and keeps playing default jingle in loop as if there was no more music is media space. And in deed, when I get to the media space there's nothing anymore. I then need to go back to storage, then switch back and on from the local to S3 storage in the station settings. Then my remote folders are back in the media space but playlist settings are lost and I need to set again files into my playlist. Then I need to restart everything to have them start streaming.

**To Reproduce**
1. Set a remote storage
2. Set station to use that remote storage
3. Go into media, find all folders from the storage. Check them all and add to default playlist
4. Restart station
5. Seems to work well.
6. But then crashes at some point.

**Expected behavior**
- Music should keep playing
- All tracks should keep their playlist settings saved

**Relevant Logs**
I see there are errors happening when adding them all to default playlist, such as :
```
web_1                      | [2020-12-11T15:57:27.221514+00:00] AzuraCast.ERROR: Error executing "PutObject" on "https://mailtapesounds.s3.amazonaws.com/radio/.albumart/81b1deb151edbd4889124577.jpg"; AWS HTTP error: Client error: `PUT https://mailtapesounds.s3.amazonaws.com/radio/.albumart/81b1deb151edbd4889124577.jpg` resulted in a `403 Forbidden` response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>E2EB92 (truncated...)  AccessDenied (client): Access Denied - <?xml version="1.0" encoding="UTF-8"?> <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>E2EB92CAD7827FC6</RequestId><HostId>xtytoMkjPjlowfE5sEPx5O+U2K87vhqxrmiZaS/QCjFwCBB35CfoE5wbA+dYf7THx9HenpRYmm4=</HostId></Error> {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []
```

The S3 API Key I gave to Azuracast is for read-only. Is it coming from that (as I see error access in the log)? Azuracast needs to write stuff on the remote S3 storage to work?

Thank you for all :)

**Comment by Vaalyn** [comment]
Yes AzuraCast needs to be able to write to the media storage location as it is saving the album covers to separate files when processing media files.

**Comment by ImaCrea** [comment]
Ok I understand, thanks for your help. I'll try that. :)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ImaCrea** [comment]
Well, after thinking more about it. I'm not fully confident with giving "full access to s3". Imagine any security hole in Azuracast.. 

What minimal permission rules should I need to activate in order to let Azuracast works but only in its sole area?

**Comment by Vaalyn** [comment]
As I'm definitely not an expert in regards to AWS IAM roles & permissions I have no idea.

In general I'd say read, write and delete access to the media files location is required in order to allow all functionality of AzuraCast to work but how that translates to IAM no clue.

If you have this figured out please let us know. We could then include it on the [S3 configurations page](https://www.azuracast.com/extending/s3-configuration.html#introduction) on our website.
