### ISSUE TITLE
Services do not run after installation (Ansible v0.11.2)

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#3547]
**Using Docker installation method**
Ansible

**AzuraCast version**
Rolling Release #6671882

**Host Operating System**
Ubuntu 18.04 LTS x64

**Describe the bug**
I just installed it on a new Ubuntu. Liquidsoap and Icecast services will not start.

**IMPORTANT EDİT**: /var/azuracast/station directory is empty. I found the radio directories in the Azuracast home directory (/var/azuracast). Their names are wrong. While a directory should be created with the name of the radio, the directory was created with the name of the storage area I set for the radio (https://prnt.sc/w135zy).

**Expected behavior**
The newly added station should go on air. But the station is offline.

**Relevant Logs**
AzuraCast APP Logs:
`[2020-12-12T10:01:21.974309+00:00] AzuraCast.ERROR: BAD_NAME: station_1:station_1_backend {"file":"/var/azuracast/www/vendor/supervisorphp/supervisor/src/Exception/SupervisorException.php","line":79,"code":10} []`

PHP APP Logs:
`[12-Dec-2020 09:49:32 UTC] PHP Warning:  file_put_contents(512 MB/config/nowplaying.txt.new): failed to open stream: No such file or directory in /var/azuracast/www/src/Webhook/LocalWebhookHandler.php on line 91
[12-Dec-2020 09:49:32 UTC] PHP Warning:  rename(512 MB/config/nowplaying.txt.new,512 MB/config/nowplaying.txt): No such file or directory in /var/azuracast/www/src/Webhook/LocalWebhookHandler.php on line 92`

Supervizord Logs:
`2020-12-12 15:46:40,738 CRIT Supervisor running as root (no user in config file)
2020-12-12 15:46:40,741 WARN No file matches via include "/var/azuracast/stations/*/config/supervisord.conf"
2020-12-12 15:46:40,741 WARN No file matches via include "/etc/supervisor/conf.d/*"
2020-12-12 15:46:40,871 INFO RPC interface 'supervisor' initialized
2020-12-12 15:46:40,950 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2020-12-12 15:46:40,951 INFO RPC interface 'supervisor' initialized
2020-12-12 15:46:40,951 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-12-12 15:46:40,955 INFO supervisord started with pid 965`

Radio's "Icecast Access Log", "Icecast Error Log", "Liquidsoap Log" records are not visible. The error that appears is below:
`Error: App\Exception\NotFoundException at /var/azuracast/www/src/Controller/AbstractLogViewerController.php L25: Log file not found!`

Errors that come with start services:
Error-1:
`Supervisor\Exception\Fault\BadNameException at /var/azuracast/www/vendor/supervisorphp/supervisor/src/Exception/SupervisorException.php L79: BAD_NAME: station_1`
Error-2:
`App\Exception\Supervisor\BadNameException at /var/azuracast/www/src/Radio/AbstractAdapter.php L205: Icecast is not recognized as a service.
It may not be registered with Supervisor yet. Restarting broadcasting may help.`

**Device(s):**
 - Device: PC
 - OS: Windows 10 Pro
 - Browser: Opera
 - Version: Latest

**Additional context**
I know there is no support for Ansible and I understand the AzuraCast team very well. But I have to use Ansible. I'm so sorry for this. I don't know if similar errors exist on Docker?

**Comment by SC2Mitch** [comment]
I'm not having any issues on the latest rolling release for Docker.

**Comment by ogrenci01** [comment]
Hi @SC2Mitch ;

I just reinstalled AzuraCast on a new and clean server. AzuraCast has already been installed on its latest version. I'm testing the update now. If anything different, I will report that as well.

**Comment by SC2Mitch** [comment]
Can you check the storage location for `    BAD_NAME: station_1` and or provide it's full name here?

**Comment by ogrenci01** [comment]
Hi @SC2Mitch ;

To complete the installation, I added a station called "demo" with "512 MB" of storage space. The problems I have reported above have occurred. then I added a new station. It was named "trial" and had "1024 MB" storage space.

**Comment by SC2Mitch** [comment]
Can you verify the storage path? It should be something like `/var/azuracast/stations/{Station_Name}/media`

**Comment by ogrenci01** [comment]
Hi @SC2Mitch ;

Could you please review the images below? These pathes are added by Azuracast by default after adding stations.

Image-1: https://prnt.sc/w18ygd

Image-2: https://prnt.sc/w18z5b

Image-3: https://prnt.sc/w18z1h

FTP-1: https://prnt.sc/w18zlz

FTP-2: https://prnt.sc/w18ztz

FTP-3: https://prnt.sc/w1900j

FTP-4: https://prnt.sc/w19080

**Comment by ogrenci01** [comment]
Oh my God! I apologize more than anyone. I am stupid. I solved the problem. I am very sorry to the Azuracast team. I love Azuracast and the team.

**Comment by SC2Mitch** [comment]
Glad it was fixed, what was the issue?

**Comment by ogrenci01** [comment]
Hi @SC2Mitch ;

It's all my fault. I noticed this late.

Could you tell me if there is the following problem for Docker?

Radio's "Icecast Access Log", "Icecast Error Log", "Liquidsoap Log" records are not visible. The error that appears is below:
`Error: App\Exception\NotFoundException at /var/azuracast/www/src/Controller/AbstractLogViewerController.php L25: Log file not found!`

**Comment by EmpressFiona** [comment]
I believe the issue is that station config paths aren't created properly when you provide a custom folder name.

![image](https://user-images.githubusercontent.com/17802496/102937001-31121e00-4477-11eb-8545-771e34e4dfab.png)

If you change this box, it breaks. Is that how you fixed it? (I mixed it up with the box that gives a custom URL stub.)

That said, I would check those logs, they're not working even when your config folder is in the proper place.

**Comment by ogrenci01** [comment]
Hi @EmpressFiona ;

Azuracast should auto-populate the "Advanced Base Station Directory" section. You can customize this later by changing in the "Storage Location" section.

That was exactly the mistake I made. While setting the storage limit, I actually changed the station directory. Therefore, the services did not start.
