### ISSUE TITLE
Set sequential playlist to the beginning the next time it is played?

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#3550]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #4ba9fb0 (2020-12-08 20:04)

**Host Operating System**
Debian 9

**Describe**
I currently have the problem that the playlist plays normally from 09-10 o'clock, for example, but at 12-13 o'clock it starts again where it left off. Yes, that is the purpose of the "Continuous" mode, but a variant/option with "Plays as far as it goes" would be fine.
Or I could just call it "Play from the beginning again". Or does such a function already exist?

**Comment by Vaalyn** [comment]
Do you mean the `Sequential` playlist mode when you say `Continuous`?

**Comment by Abqehebter** [comment]
Yes. Sequential

**Comment by Vaalyn** [comment]
Would you mind describing your playlist setup a bit so I can better understand the use-case?

How I understood it you have a sequential playlist that you have playing from 9-10 then something else and at 12-13 you have the sequential playlist scheduled again. Is that correct?

**Comment by Abqehebter** [comment]
That is correct. I play a sequential playlist every 3 hours, which contains 21 songs. We start at song 1 and end at song 19. In the next 3 hours the playlist starts at song 20 (instead of song 1 again).

Example:
09-10 o'clock: Songs 1-19 played!
12-13 o'clock: Songs 20-17 played!

But I would like the playlist to start from the beginning. Always at song 1 and not at those, which did not get there.

**Comment by Abqehebter** [comment]
@Vaalyn With the commit https://github.com/AzuraCast/AzuraCast/commit/df660ea45a0a8164d0f4998ef44c44c6069b4fcc my "suggestion" or question is hereby answered or added. Thank you! Works as I wanted it.
