### ISSUE TITLE
No Connecting to stream

### ISSUE THREAD

**Issue by top100fm** [AzuraCast/AzuraCast#3560]
can't connect to any encoder. always shows error 10061. auto dj runs without problems. who knows the solution?

**Comment by Vaalyn** [comment]
Please fill out the issue template to provide us with a clear description of your setup, the issue and possibly logs and debug information.

**Comment by DerJulien90** [comment]
I have exactly the same problem as my successor. azuracast works without problems on ubuntu 04/20. all settings work, auto DJ works. I can also create djs. then you have to restart the car dj .. i did it too. it just doesn't matter which program I want to connect to, I can't get on the stream. port for the auto dj is 8050 and for the DJs 8052.

what is the problem?
