### ISSUE TITLE
Streaming does not work

### ISSUE THREAD

**Issue by ivi-v** [AzuraCast/AzuraCast#3561]
I am new at AzuraCast and I have launched my station by following some online tutorials, so my knowledge at Ubuntu console and coding is very limited.

I tried to configure the stream on RadioBoss, Butt and RadioCaster taping the data given by AzuraCast — server IP, port 8005, DJ user and DJ password, but the streaming does not connect. RadioBoss gives back the following error: "[E40] Cannot start broadcasting (output 3) Error 40 (network timeout)" and both Butt & RadioCaster show permanently a "connecting" window. I have tried IceCast and ShoutCast V1 options and the issue is the same.

If you want more information, I would try to give it to you as I find it possible.

Thanks in advance!

**Comment by Vaalyn** [comment]
Are you using CloudFlare for your domain?
If so then this would be the issue as CF blocks non-standard ports.

**Comment by ivi-v** [comment]
> 
> 
> Are you using CloudFlare for your domain?
> If so then this would be the issue as CF blocks non-standard ports.

Thanks Vaalyn for your answer! I don't remember having activated CloudFare when setting the domain and server. Just in case I looked up but there isn't any mention to it anywhere.
