### ISSUE TITLE
Failing to delete a Station with Broadcasting disabled.

### ISSUE THREAD

**Issue by xewl** [AzuraCast/AzuraCast#3562]
**Using Docker installation method**
Yes

**AzuraCast version**
0.11.[0,1,2 + up until release #6671882]

**Host Operating System**
Ubuntu

**Describe the bug**
When deleting a "Broadcast"-disabled station, it'll fail to match the station ID (or stub),
and thus ultimately fail to delete the station.

**To Reproduce**
1. Change Station Profile: un-check "Enable Broadcasting" (Administration)
2. Delete Station -> 500

**Expected behavior**
Station being correctly deleted, even though being disabled for Broadcasting.

**Relevant Logs**
Error occurring (500):
```
BAD_NAME: station_16
SupervisorException.php : 79
```

**Screenshots**
N/A, see Relevant logs.

**Device(s):**
N/A

**Additional context**
- I encountered this before, but didn't make an issue for it.
- Also mentioned by moran1804 on Discord, temp solution as I did before helped.

**Temporary solution**
- Re-enable station Broadcasting (under Administration)
- Delete station

**Comment by SlvrEagle23** [comment]
@xewl Should be fixed now as of latest rolling-release version.
