### ISSUE TITLE
Viewing recent backup logs returns [ERROR] Invalid storage location specified.

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#3563]
**Using Docker installation method**
Yes

**AzuraCast version**
 Release #d5bab23 

**Host Operating System**
Ubuntu 20.04 

**Describe the bug**
Two bugs: 
When checking the backup page, click `most recent backup log` and it'll return `[ERROR] Invalid storage location specified`.
When viewing the page, no backups are listed, despite the successful backups

**To Reproduce**
Go to backup page
Click `most recent backup log`
View the error
Look down and see the no backups / you cant download, modify or delete. 

**Expected behavior**
To successfully view the logs, or allow a user to view the storage location for backups. 

**Relevant Logs**
None. 

**Screenshots**
https://puu.sh/GXnXC/5404cf82d7.png

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch This isn't actually a bug, necessarily; if you're enabling automated backups, you have to specify where they'll go by picking a storage location in the automatic backup configuration page.

Normally, we'd just make that a required field, but if you're disabling backups, then that field shouldn't be required. Making fields dynamically required or not is mostly something that's only possible in our newer frontend code (the Vue components), and the backup system is using the older component system, at least for now.

**Comment by SC2Mitch** [comment]
I see, I think where this has gone a bit confusing is that here I can pick the path for backups 
![image](https://user-images.githubusercontent.com/29955942/102255831-85ab1b80-3f02-11eb-8b92-56a98c0d3e36.png)
but when I look into the configuration page, it shows `none`
![image](https://user-images.githubusercontent.com/29955942/102255880-98255500-3f02-11eb-933b-28c9b9259f21.png)

**Comment by SlvrEagle23** [comment]
> I see, I think where this has gone a bit confusing is that here I can pick the path for backups 
> ![image](https://user-images.githubusercontent.com/29955942/102255831-85ab1b80-3f02-11eb-8b92-56a98c0d3e36.png)
> but when I look into the configuration page, it shows `none`
> ![image](https://user-images.githubusercontent.com/29955942/102255880-98255500-3f02-11eb-933b-28c9b9259f21.png)
> 
> 

That "None" should be a drop-down that has the other storage location listed in it.

We could also update that text to say "Select ..." or similar to avoid confusion there.

**Comment by SC2Mitch** [comment]
Perhaps select would be a bit more user-friendly? Unsure

**Comment by SC2Mitch** [comment]
All better.
