### ISSUE TITLE
On Running Database Migrations on update, i've 4 errors

### ISSUE THREAD

**Issue by FleuryK** [AzuraCast/AzuraCast#3564]
Hello azuracast staff,

I have a problem with your software. On update on running database migrations, i've 4 errors :

```
Running Database Migrations
---------------------------

[notice] Migrating up to App\Entity\Migration\Version20201211164613

SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'idx_search'"

In AbstractMySQLDriver.php line 128:

  An exception occurred while executing 'CREATE INDEX idx_search ON audit_log (class, user, identifier)':  

  SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'idx_search'                  


In Exception.php line 18:

  SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'idx_search'  


In PDOConnection.php line 52:

  SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'idx_search'  


azuracast:setup [--update] [--load-fixtures] [--release]
```

How to fix this problem ?

Cordially.

**Comment by SC2Mitch** [comment]
Can you explain your system please, the format. 
Ansible, docker? System specs? You self hosting or using a third party provider?

**Comment by FleuryK** [comment]
I'm running on Docker under VPS KVM.

System Specs :
OS : Debian 9.
RAM : 10 Go.
HDD : 190 Go.

**Comment by SlvrEagle23** [comment]
@FleuryK This isn't necessarily an error with our migrations, but it's likely that the previous migration took a little longer than you were expecting and so it got cancelled and re-attempted, which caused the migration to be attempted again as well, when it already existed, causing a collision.

In this case, it's safe for us to loosen the tolerances of the migration to make it more able to handle that, but generally even if a migration takes a few minutes, it's best to always wait for it to complete to ensure you don't throw your database out of whack.

The latest rolling-release update will have an update that should make that migration run without any issues for you here in just a few minutes.
