### ISSUE TITLE
mp4 audio files (AAC encoded) NOT PROCESSED

### ISSUE THREAD

**Issue by kgguru** [AzuraCast/AzuraCast#3569]
Ubuntu 20.04
Docker installation 
Version Rolling Release #06bb766 (2020-12-15 18:05) • Docker • PHP 7.4 

The m4a files recognized as a video files "MIME type "video/mp4" is not processable".
This issue was not present on Azuracast version 10.4

web_1                      | [2020-12-16T01:00:10.352298+00:00] AzuraCast.ERROR: Cannot process media file at path "HTMTop20 VOTE part9.m4a": MIME type "video/mp4" is not processable. {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []

**Comment by Takumi86ES** [comment]
I have several m4a files and they work fine.

Although they don't weigh even 1Mb

**Comment by kgguru** [comment]
@Takumi86ES Please try with a m4a files greater than 200MB. I had no luck with it.

**Comment by SlvrEagle23** [comment]
@Takumi86ES @kgguru It's likely that there's an error with your file being imported. You can see the error by hitting F12 (or right clicking a blank space on the page and clicking "Inspect Element"), clicking the "Network" tab, then re-performing the upload. You'll see the request, probably lit up in red, and can click it and view the response, which will have an error message we can review.

**Comment by kgguru** [comment]
I didn't import files vie website. I do import via FIlleZilla SFTP.

**Comment by SlvrEagle23** [comment]
@kgguru You may be able to diagnose what's wrong with processing the files by using the web uploader, at least just for the "trouble" songs.

**Comment by kgguru** [comment]
I didn't import files vie website. I do import via FIlleZilla SFTP.
I had no problem with the m4a files on AzuraCast version 10.4.
I have not changed the encoder since then.
Only the AzuraCast revision has changed.

**Comment by kgguru** [comment]
On many softwares like ProTools, Presonus Studio, WaveLab, the m4a files
are recognizable as AUDIO files.
ONLY AzuraCast has a problem with the MIME type of the m4a files. So I
assure you guys, this is AzuraCast problem, not the audio file.

**Comment by SlvrEagle23** [comment]
@kgguru I'm not disagreeing with that...it's very possible we're just mis-parsing the file, but in order for us to figure out _how_ that error is happening we'd either need to see the file in question or see the error logs indicating why it can't process.

**Comment by kgguru** [comment]
You guys meant that?

web_1 | [2020-12-16T01:00:10.352298+00:00] AzuraCast.ERROR: Cannot process
media file at path "HTMTop20 VOTE part9.m4a": MIME type "video/mp4" is not
processable.
{"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0}
[]

**Comment by kgguru** [comment]
I would send a problematic m4a file to you.
And you would upload for test purposes that file to your test server.
We would see what the result could be.

**Comment by SlvrEagle23** [comment]
@kgguru We don't normally expect MP4 files to be recognized as `video/mp4` but those should otherwise be handled fine by the application, so I've added it as one of our supported media types; that update will be live in the rolling release in a few minutes.

**Comment by kgguru** [comment]
The question is: Why that worked well in Azuracast version 10.4 and STOPPED work on other releases?

**Comment by SlvrEagle23** [comment]
@kgguru The answer is simple from our side: we introduced MIME type checking ahead of our regular processing to avoid the huge performance overhead of having our ID3 library try to parse the tags of a file that it couldn't actually process, only to throw an error and then send the file back to the queue for re-processing later. The MIME type checking helps stop that cycle from continuing indefinitely for files we know we won't be able to process.

We have some fine-tuning to do with the MIME type formats, sure, but otherwise this has helped improve our overall system performance quite a bit.

**Comment by kgguru** [comment]
Ok I can 100% agree with that. To improve with AzuraCast is the MIME types. The wrong recognizable MIME types generating the issue.

**Comment by kgguru** [comment]
I must underline M4A not MP4. Audio format is M4A not the MP4.

**Comment by kgguru** [comment]
I encode the M4A straight  from WaveLab Studio. Original, licensed version.

**Comment by SlvrEagle23** [comment]
@kgguru That's fine, and nothing you're doing is wrong like we said, it's just that the `.mp4` file extension is occasionally being detected as `video/mp4` when it's in a slightly different format than it expects for M4A audio. This exemption just accounts for that and shouldn't otherwise have any side effects.
