### ISSUE TITLE
Creating >=2 Stations automatically adds a duplicate default playlist

### ISSUE THREAD

**Issue by amavarick** [AzuraCast/AzuraCast#357]
On a brand new docker installation on an Ubuntu 16.x OS... creating a 2nd or more radio stations will be created with 2 playlists instead of 1.  Easy fix is to delete one of them.  No big deal as a workaround.

![image](https://user-images.githubusercontent.com/20918832/34329427-9b8ba930-e8cd-11e7-9097-93da8b1201c7.png)

**Comment by SlvrEagle23** [comment]
@amavarick Should be fixed now. :)

**Comment by amavarick** [comment]
Confirmed, only one playlist on new station now.  Thank you!
