### ISSUE TITLE
Hy there

### ISSUE THREAD

**Issue by rofmvalencia** [AzuraCast/AzuraCast#3578]
I'm not writing a issue is just a recommendation if is possible of course. I like Azuracast very much and I hope in the future will not make changes to a corporate paid plan because will ruined. I hope can find to my little question an answer: The admin page of azuracast can you make it responsive? Becouse can be very useful to control it from the mobile phone some times.
In the next update I've like to see it... thank you so much. Keeping going to great things for us.

**Comment by SlvrEagle23** [comment]
@rofmvalencia We have no plans to make the core AzuraCast project a paid project, as our entire purpose with the program is to offer a fully free and open-source alternative to other broadcast software. We may sell add-ons or plugins or even support related to the project, but we intend to keep the core project free.

What do you mean that the administration page isn't responsive? It may not be as responsive as it could be, but all pages in AzuraCast are scalable to a mobile size. Can you post a screenshot of what you're seeing in your situation and what needs fixing?

**Comment by rofmvalencia** [comment]
![Screenshot_20201219-211056](https://user-images.githubusercontent.com/67313797/102698604-f6be3c00-423e-11eb-8637-af29ecda28ee.jpg)
![Screenshot_20201219-211113](https://user-images.githubusercontent.com/67313797/102698606-fe7de080-423e-11eb-9be5-03356790a506.jpg)
Just this... I made some change in to the css custom code... but nothing else... just touching the colors...

**Comment by rofmvalencia** [comment]
![Screenshot_20201219-211934](https://user-images.githubusercontent.com/67313797/102698780-494c2800-4240-11eb-981d-cf2349b035d9.jpg)
![Screenshot_20201219-212202](https://user-images.githubusercontent.com/67313797/102698783-4d784580-4240-11eb-8e75-bde9664868b7.jpg)
  Thanks for your quickly answer, nice to meet you.

**Comment by SlvrEagle23** [comment]
@rofmvalencia The main dashboard and profile's responsiveness on mobile should now be fixed. It'll take more work to fix the tables on pages like the playlist editor, but we'll work on those when we get a chance. For now, though, the two main pages that are having problems should be fixed. Thank you for your report.
