### ISSUE TITLE
List of Dj Streamers are not visualized

### ISSUE THREAD

**Issue by dvdred** [AzuraCast/AzuraCast#3580]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #d955d63 (2020-12-20 2:17) •

Host Operating System
CentOS 7.9

**Describe the bug**
**List of Dj Streamer are not visualized, but using swagger ui they are correctly listed (and the live session are correctly working)**

**To Reproduce**
Go to Streamer/DJ Accounts and look at the list

**Expected behavior**
Streamer/DJ Accounts are listed

**Relevant Logs**
GET to /api/station/1/streamers?internal=true&rowCount=0 answer is:
Pagerfanta\Exception\LessThan1CurrentPageException at /var/azuracast/www/vendor/pagerfanta/core/Pagerfanta.php L255: 

**Screenshots**
https://paste.pics/ea430d56f5b7d73a78829df3fc0a1705

**Device(s):**
All browser and OS

**Comment by SlvrEagle23** [comment]
@dvdred Should be fixed in newest rolling release.

**Comment by dvdred** [comment]
You are the best! Thanks!
