### ISSUE TITLE
Can't install Azuracast with Docker on Raspberry Pi 3b+

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#3581]
**Using Docker installation method**
Yes

**AzuraCast version**
Latest

**Host Operating System**
Ubuntu 20.04.1 LTS

**Describe the bug**
I'm trying to install Azuracast on freshly installed ubuntu with Docker. During the installation i had problem with `ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).` But after setting variable `COMPOSE_HTTP_TIMEOUT=200 docker-compose up` it did the install. Also during install there is error, showed in the log down. I tried install 3 times, every time this error exist. After installation `http://STATIONIP/dashboard` is not working. In `htop` there is several `dockerd` processes, and the cpu usage is like there is working liquidsoap.

**To Reproduce**
./docker.sh install

**Relevant Logs**
```
root@ubuntu:/var/azuracast# ./docker.sh install
Docker is already installed! Continuing...
Docker Compose is already installed! Continuing...
Customize AzuraCast ports? [y/N] n
Set up LetsEncrypt? [y/N] y
Domain name (example.com) or names (example.com,foo.bar) to use with LetsEncrypt [xxxxxxxxxxxx]: 
Optional e-mail address for expiration updates [xxxxxxxxxxxxxxx]: 
Pulling mariadb                 ... done
Pulling redis                   ... done
Pulling stations                ... done
Pulling web                     ... done
Pulling nginx_proxy             ... done
Pulling nginx_proxy_letsencrypt ... done
Starting azuracast_redis_1   ... done
Starting azuracast_mariadb_1 ... done
Starting azuracast_stations  ... done
**standard_init_linux.go:219: exec user process caused: exec format error**
azuracast_redis_1 is up-to-date
azuracast_mariadb_1 is up-to-date
azuracast_stations is up-to-date
azuracast_web is up-to-date
azuracast_nginx_proxy_1 is up-to-date
azuracast_nginx_proxy_letsencrypt_1 is up-to-date
```

**Device(s):**
 - Device: Raspberry Pi 3b+

**Comment by Vaalyn** [comment]
This error is due to the NGINX proxy not having a Docker image for the ARM cpu architecture.

See the following issue on their repository for the current status regarding ARM support for the NGINX proxy: https://github.com/nginx-proxy/nginx-proxy/issues/1370

There is also a PR on their repository the would add initial support for ARM: https://github.com/nginx-proxy/nginx-proxy/pull/1262
