### ISSUE TITLE
Recording of broadcast does not stop after streamer is disconnected.

### ISSUE THREAD

**Issue by intelrug** [AzuraCast/AzuraCast#3588]
**Using Docker installation method**
Yes

**AzuraCast version**
#c625b12 (2020-12-11 23:01) • Docker • PHP 7.4 Windows 10 20H2 x64
#c625b12 (2020-12-11 23:01) • Ansible • PHP 7.4 Ubuntu 20.04

**Describe the bug**
Recording of broadcast does not stop after streamer is disconnected.

**To Reproduce**
1. Start broadcast
2. Stop broadcast
3. Open Streamer Broadcasts
4. End Time is "Live"
![image](https://user-images.githubusercontent.com/18365200/102797903-c3f47f00-43c9-11eb-8c3f-cd749385b147.png)
5. Try to skip current song on station profile page
6. See error message
![image](https://user-images.githubusercontent.com/18365200/102801007-1899f900-43ce-11eb-9166-ceff643061f4.png)

**Expected behavior**
Broadcast recording should stop.

**Relevant Logs**
There is no errors, except
`2020/12/21 17:04:23 [lang:3] AzuraCast Raw Response: Error: File already exists at path: admin/20201221-164815.mp3 on /var/azuracast/www/vendor/league/flysystem/src/Filesystem.php L405`

**Additional context**
Sometimes liquidsoap ignore playback queue and takes random songs, playback progress is not shown on public page and on station profile page.
![image](https://user-images.githubusercontent.com/18365200/102804345-171eff80-43d3-11eb-89f5-13fe54f3afaf.png)

**Comment by jackerman426** [comment]
Yes we have the same issue as well

**Comment by Vaalyn** [comment]
I can reproduce this problem on my test installation.

The recording itself is actually stopped correctly after a DJ disconnects but the timestamp for when the broadcast ended is not set to the `StationStreamerBroadcast`.

After disconnecting the `timestamp_end` field stays at the value `0`:

```
+----+------------+-------------+-----------------+---------------+----------------------------+
| id | station_id | streamer_id | timestamp_start | timestamp_end | recording_path             |
+----+------------+-------------+-----------------+---------------+----------------------------+
|  1 |          1 |           1 |      1609316988 |             0 | vaalyn/20201230-082948.mp3 |
+----+------------+-------------+-----------------+---------------+----------------------------+
```

On the next connection this field is correctly updated though:
```
+----+------------+-------------+-----------------+---------------+----------------------------+
| id | station_id | streamer_id | timestamp_start | timestamp_end | recording_path             |
+----+------------+-------------+-----------------+---------------+----------------------------+
|  1 |          1 |           1 |      1609316988 |    1609317361 | vaalyn/20201230-082948.mp3 |
|  2 |          1 |           1 |      1609317361 |             0 | vaalyn/20201230-083601.mp3 |
+----+------------+-------------+-----------------+---------------+----------------------------+
```

**Comment by intelrug** [comment]
I don't know why but line 122 in StationStreamerRepository is not working.
`$this->em->persist($broadcast);`

So I replaced it with this:
`$this->broadcastRepo->endAllActiveBroadcasts($station);`
I'm not sure if this is correct however now everything is fine. Even the problems with the queuing and displaying the playback progress are gone.

**Comment by psduk1** [comment]
is there a way i can implement this fix in my install ?

**Comment by stafot** [comment]
Ideally should be a functionality that if the same user reconnects within a short amount of time the server should merge the old and the new recording to one. I know that this should open as a separate issue, just sharing the idea of which behaviour could be the ideal user's experience.
