### ISSUE TITLE
Web DJ don't switch the stream

### ISSUE THREAD

**Issue by Deiiji** [AzuraCast/AzuraCast#3589]
Hello, another issue after couple of updates...

**Using Docker installation method**

No
**AzuraCast version**

 AzuraCast • Rolling Release #a253341 (2020-12-21 2:41) • Ansible • PHP 7.4
**Host Operating System**

Ubuntu 20.04
**Describe the bug**

When using assynchronous worker web dj even don't start, without that it start, cue work but main stream still on station without swotching to web DJ
**To Reproduce**

Go to web DJ, upload couple of songs and try to broadcast 
**Expected behavior**

Stream shall switch from radio to web DJ
**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by arusi01** [comment]
Same problem here.

AzuraCast • Rolling Release #e4e7f8c (2020-12-24 1:33) • Docker • PHP 7.4

**Comment by rmueck** [comment]
Same here:
Ubuntu 20.04.1 LTS
AzuraCast • Rolling Release #5ff1f44 (2021-01-02 9:05) • Docker • PHP 7.4

**Comment by dvdokkum** [comment]
Also experiencing this on:
Rolling Release #8242136 (2021-01-13 8:14) • Docker • PHP 7.4 (Ubuntu 20.04)

To add more specifics, this appears to be an issue with the `Use Asynchronous Worker` option when using the Web DJ in the Chrome browser. It works fine in Safari, but in the current version of Chrome (Version 87.0.4280.141) if you have the async worker box checked (currently the default behavior) it throws an error in the console:

```
webcast-75f3ecd006.js:34 Refused to create a worker from 'blob:https://stream.subpar.fm/a77aba6f-4a6f-4967-ae84-c57b81105c08' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'nonce-VsSiAXwBPS0ReRrIqkgmegDn'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.
```

I confirmed this same error behavior on the Azuracast demo instance.
