### ISSUE TITLE
Music show only on page 1  in on-demand media pages

### ISSUE THREAD

**Issue by technplus** [AzuraCast/AzuraCast#3592]
**Using Docker installation method**

Yes

**AzuraCast version**

Rolling Release #c93d888

**Host Operating System**

Debian 10

**Describe the bug**

When visiting on-demand media page, the media show only on the first page, when click on the other pages, we have a no record to display message

**To Reproduce**

1. Go to On-Demand Media Page
2. Click on any other pages tab

**Expected behavior**

The other pages should show the existing media

**Screenshots**

![azuracast_on-demand_page_1](https://user-images.githubusercontent.com/59397833/102881079-5290ec80-441a-11eb-95ca-06838d93cb62.png)
![azuracast_on-demand_page_2](https://user-images.githubusercontent.com/59397833/102881082-53298300-441a-11eb-9f09-43b5b9b6f2be.png)

**Comment by boiciuc** [comment]
Not sure, but it might be generated by this commit: [Switch to using Pagerfanta library for pagination](https://github.com/AzuraCast/AzuraCast/commit/bc247a7257ea7dc135a665299298272b61246ff6). 

I have a somewhat similar issue on another functionality that had the pagination switched.

**Comment by SlvrEagle23** [comment]
@boiciuc Thank you for the report; this should be fixed as of the latest rolling-release version.
