### ISSUE TITLE
Stations: History API endpoint JSON response is limited to the last 10 songs played

### ISSUE THREAD

**Issue by boiciuc** [AzuraCast/AzuraCast#3593]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #a253341 (2020-12-21 2:41)

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
The JSON received from  Stations: History endpoint only contains the last 10 songs played.

**To Reproduce**

1. Make an ajax request to the Stations: History endpoint (/api/station/{station_id}/history)
2. Check the JSON response
3. The JSON response has maximum 10 results

**Expected behavior**
The JSON response should contain all the songs played in the last 2 weeks (or in the period that is configured in the settings)

**Relevant Logs**
-

**Screenshots**
-

**Device(s):**
 - 

**Additional context**
Might be related to this commit: [Switch to using Pagerfanta library for pagination](https://github.com/AzuraCast/AzuraCast/commit/bc247a7257ea7dc135a665299298272b61246ff6) (the JSON seems to be generated from this file: [SongHistoryApiGenerator.php](https://github.com/AzuraCast/AzuraCast/blob/master/src/Entity/ApiGenerator/SongHistoryApiGenerator.php)).

**Comment by Vaalyn** [comment]
Fixed by commit efaf75442f6a27c2e5ce87c70dbb2fb643ae7596
