### ISSUE TITLE
Docker unable to reach outside IPs

### ISSUE THREAD

**Issue by EmpressFiona** [AzuraCast/AzuraCast#3595]
**Using Docker installation method**

Yes

**AzuraCast version**

Rolling Release #c93d888 (2020-12-22 7:10)

**Host Operating System**

Ubuntu 20.04 LTS

**Describe the bug**

When installing AzuraCast, for whatever reason, it is unable to reach the outside world to retrieve HTTP sites. I don't know why this is, because the site itself functions normally [when reached over the Internet](http://empress.duckdns.org), except over HTTPS - because among what I am assuming is many other symptoms, this causes Let's Encrypt to continually fail.

Interestingly enough, this only happens on my home setup, so it *might* be something on my configuration - though the reason this happened (in the 'additional context') suggests that this is still a bug, or at least an implementation problem. I tried this first on a Scaleway instance, but at 1 GB of RAM and one CPU, it was unable to handle the amount of Docker containers demanded, which took most of my local storage to begin with and would repeatedly crash due to a lack of memory. (Eventually, the configuration ate itself sufficiently that I had to start from scratch, but I'm assuming that's an unrelated issue on my end.) While this is unsupported given the specs, I might recommend not recommending even 1 GB of RAM as enough anymore.

**To Reproduce**
Install AzuraCast. If this happens, there will be an error just before the installation completes, and your external IP will not show up in the install.

**Expected behavior**
I expected HTTP client calls to function as intended, which they currently do not. I also expected it to accept certificates properly when introduced into the image (more on that below) and for Let's Encrypt to run.

**Relevant Logs**
```
[2020-12-22T16:16:47.578955+00:00] AzuraCast.ERROR: HTTP client GET call to https://central.azuracast.com/ip produced response NULL [] []
[2020-12-22T16:16:47.579853+00:00] AzuraCast.ERROR: Could not fetch remote IP: cURL error 28: Resolving timed out after 3000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://central.azuracast.com/ip [] []

 [OK] AzuraCast installation complete!

      Visit http:// to complete setup.
```
```
nginx_proxy_letsencrypt_1  | Info: running letsencrypt-nginx-proxy-companion version v2.0.1-6-ga717c35
nginx_proxy_letsencrypt_1  | Info: Custom Diffie-Hellman group found, generation skipped.
nginx_proxy_letsencrypt_1  | Reloading nginx proxy (5bfcc5d4c127071d0bb67671b1770035b1e067ecb71f2e4d391f25ce5dc7ae36)...
nginx_proxy_letsencrypt_1  | 2020/12/22 16:59:39 Generated '/etc/nginx/conf.d/default.conf' from 8 containers
nginx_proxy_letsencrypt_1  | 2020/12/22 16:59:39 [notice] 56#56: signal process started
nginx_proxy_letsencrypt_1  | 2020/12/22 16:59:39 Generated '/app/letsencrypt_service_data' from 8 containers
nginx_proxy_letsencrypt_1  | 2020/12/22 16:59:39 Running '/app/signal_le_service'
nginx_proxy_letsencrypt_1  | 2020/12/22 16:59:39 Watching docker events
nginx_proxy_letsencrypt_1  | 2020/12/22 16:59:39 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
nginx_proxy_letsencrypt_1  | [Tue Dec 22 16:59:44 UTC 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
nginx_proxy_letsencrypt_1  | [Tue Dec 22 16:59:44 UTC 2020] Can not init api.
nginx_proxy_letsencrypt_1  | [Tue Dec 22 16:59:45 UTC 2020] Create account key ok.
nginx_proxy_letsencrypt_1  | [Tue Dec 22 16:59:45 UTC 2020] Registering account: https://acme-v02.api.letsencrypt.org/directory
nginx_proxy_letsencrypt_1  | [Tue Dec 22 16:59:50 UTC 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
nginx_proxy_letsencrypt_1  | [Tue Dec 22 16:59:50 UTC 2020] Could not get nonce, let's try again.
nginx_proxy_letsencrypt_1  | [Tue Dec 22 16:59:57 UTC 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
nginx_proxy_letsencrypt_1  | [Tue Dec 22 16:59:57 UTC 2020] Could not get nonce, let's try again.
nginx_proxy_letsencrypt_1  | [Tue Dec 22 17:00:04 UTC 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
nginx_proxy_letsencrypt_1  | [Tue Dec 22 17:00:04 UTC 2020] Could not get nonce, let's try again.
nginx_proxy_letsencrypt_1  | [Tue Dec 22 17:00:11 UTC 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
nginx_proxy_letsencrypt_1  | [Tue Dec 22 17:00:11 UTC 2020] Could not get nonce, let's try again.
nginx_proxy_letsencrypt_1  | [Tue Dec 22 17:00:18 UTC 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
nginx_proxy_letsencrypt_1  | [Tue Dec 22 17:00:18 UTC 2020] Could not get nonce, let's try again.
nginx_proxy_letsencrypt_1  | [Tue Dec 22 17:00:25 UTC 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
nginx_proxy_letsencrypt_1  | [Tue Dec 22 17:00:25 UTC 2020] Could not get nonce, let's try again.
nginx_proxy_letsencrypt_1  | [Tue Dec 22 17:00:32 UTC 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
```

**Additional context**
As an aside, the documentation on this is woefully incomplete and support for trying to change your setup to AzuraCast seems oddly minimal. I understand that the requirement for AzuraCast to manage the entire system's domain name and SSL is one imposed by outside projects, so I can't hold that against the project given IceCast's seeming inability to care about the issue, but surely it's not an uncommon use case for someone to want to install it on a server they've previously set SSL up with Let's Encrypt and Certbot before, right?

Using one of the suggestions - that is, [directly using existing SSL keys](https://www.azuracast.com/extending/letsencrypt.html#using-a-custom-certificate) - results in an *incredibly* loud warning message from Docker warning that the file system is read-only, causing it to immediately halt. (This may be an upstream issue with the nginx proxy, admittedly.) Other suggestions in the issues didn't work either. And at least one of the commands for the Docker script (that to renew letsencrypt using the docker script) does not function as stated in the docs:

```
fiona@XXXXX:/var/azuracast$ ./docker.sh letsencrypt-renew
./docker.sh: line 616: letsencrypt-renew: command not found
```

Copying in keys from elsewhere (ie, my system which has perfectly functional LE keys already) fails as well, even using [a suggestion from the nginx proxy side](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues/455). In essence, it seems to just not recognize at all that they're there, nor serves them to outside sites. Can't tell if that's a bug, an implementation problem/change, or something I'm doing wrong, but it *always* serves locally-signed certs regardless of what I do.

It *did* work on the Scaleway server, eventually, after many attempts...but as mentioned, that kind of isn't an option. (I may try an RPi configuration at some point, though.)

This also means that failures run into CA limits - a crucial problem when trying to get a site up quickly. 

I can get it all through HTTP, sure, but that's insecure and unnecessary. There should be no reason why I spent all of yesterday trying to set this up. LE seems unreliable at best in this setup, workarounds don't seem to work, and I can't imagine it'd be that difficult to check a system for preexisting LE certs and import them into the machine - that might actually be more reliable, given just how many containers you're using and how much is demanded to go perfectly for AzuraCast to function.

**Comment by EmpressFiona** [comment]
I believe it may also be causing my current issue below, of my server not being able to fetch its own XML. (I did, however, get a 'Permission denied' when trying to change my station root...)

```
web_1                      | [2020-12-22T18:07:44.297094+00:00] AzuraCast.WARNING: Could not fetch XML data; falling back to public JSON. [] {"station":{"id":1,"name":"Transient Facts: The Throne of Want Radio Station"}}
web_1                      | [2020-12-22T18:07:44.419709+00:00] AzuraCast.ERROR: Request returned status code 400. {"body":""} {"station":{"id":1,"name":"Transient Facts: The Throne of Want Radio Station"}}
web_1                      | [2020-12-22T18:07:47.192929+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data [] []
web_1                      | [2020-12-22T18:07:47.468578+00:00] AzuraCast.ERROR: Remote server has no mount points listed. {"response":"<?xml version=\"1.0\"?>\n<icestats>\n  <admin>icemaster@localhost</admin>\n  <banned_IPs>0</banned_IPs>\n  <build>133-g4bdfa25</build>\n  <client_connections>11</client_connections>\n  <clients>1</clients>\n  <connections>9</connections>\n  <file_connections>0</file_connections>\n  <host>empress.duckdns.org</host>\n  <listener_connections>0</listener_connections>\n  <listeners>0</listeners>\n  <location>AzuraCast</location>\n  <outgoing_kbitrate>0</outgoing_kbitrate>\n  <server_id>Icecast 2.4.0-kh15-ac1</server_id>\n  <server_start>22/Dec/2020:13:07:41 -0500</server_start>\n  <source_client_connections>1</source_client_connections>\n  <source_relay_connections>0</source_relay_connections>\n  <source_total_connections>1</source_total_connections>\n  <sources>1</sources>\n  <stats>0</stats>\n  <stats_connections>0</stats_connections>\n  <stream_kbytes_read>60</stream_kbytes_read>\n  <stream_kbytes_sent>0</stream_kbytes_sent>\n  <source mount=\"/radio.mp3\">\n    <artist>CHVRCHES</artist>\n    <audio_codecid>2</audio_codecid>\n    <audio_info>channels=2;samplerate=44100;bitrate=128</audio_info>\n    <bitrate>128</bitrate>\n    <connected>5</connected>\n    <genre>Synth</genre>\n    <incoming_bitrate>165712</incoming_bitrate>\n    <listener_connections>0</listener_connections>\n    <listener_peak>0</listener_peak>\n    <listeners>0</listeners>\n    <listenurl>http://empress.duckdns.org:8000/radio.mp3</listenurl>\n    <max_listeners>-1</max_listeners>\n    <metadata_updated>22/Dec/2020:13:07:43 -0500</metadata_updated>\n    <mpeg_channels>2</mpeg_channels>\n    <mpeg_samplerate>44100</mpeg_samplerate>\n    <outgoing_kbitrate>0</outgoing_kbitrate>\n    <public>0</public>\n    <queue_size>61857</queue_size>\n    <server_description>&#x1F5A4;</server_description>\n    <server_name>Transient Facts: The Throne of Want Radio Station</server_name>\n    <server_type>audio/mpeg</server_type>\n    <server_url>http://sharon.empress.ml</server_url>\n    <slow_listeners>0</slow_listeners>\n    <source_ip>127.0.0.1</source_ip>\n    <stream_start>22/Dec/2020:13:07:41 -0500</stream_start>\n    <title>Lungs</title>\n    <total_bytes_read>62144</total_bytes_read>\n    <total_bytes_sent>0</total_bytes_sent>\n    <total_mbytes_sent>0</total_mbytes_sent>\n    <user_agent>Liquidsoap/1.4.3+git@3075878f (Unix; OCaml 4.08.1)</user_agent>\n    <yp_currently_playing>CHVRCHES - Lungs</yp_currently_playing>\n  </source>\n</icestats>\n"} {"station":{"id":1,"name":"Transient Facts: The Throne of Want Radio Station"}}
```

I may, in fact, just consider using Ansible at this point. (That might even work on my VPS, at this point, without the Docker overhead.)

**Comment by EmpressFiona** [comment]
Having looked into the matter, the issue may be with AzuraCast's Docker containers not handling DNS properly.

For some reason, my resolv.conf as configured by Ubuntu has two servers in it - a Pi-hole DNS server, but a previous Pi-hole IP that is no longer valid on my network. The invalid IP is first on the list.

While I haven't figured out how to remove it, and this is obviously an issue on my end I'll need to figure out...it doesn't cause problems for either Ubuntu itself, *or* for any other Docker containers I've been using so far, because it knows to skip over the DNS server that's missing. For whatever reason, AzuraCast can't reach the server that works, nor fallback to 8.8.8.8, so it chokes. So I would still qualify this as a bug.

At this point I've given up and moved to an Ansible installation in the cloud, though. It's simpler than the Docker installation, and it runs better, even on hardware up to the task like my home server. Making Azuracast more friendly to domain owners who are being asked to replace their entire webserver setup would be ideal.

**Comment by SC2Mitch** [comment]
Hi, 

I help contribute towards the documentation for AzuraCast, what kind of information would you like to see in the future? Please make a list and I'll work on it, a brief note that none of us are full time and I'll be looking into this issue in a moment as well.

**Comment by EmpressFiona** [comment]
Integration or smooth transition for existing webservers, mostly.

Also, troubleshooting the individual Docker containers, and documentation of each of them and what they're responsible for, so that troubleshooting can be more easily performed by people comfortable with a command line. Right now, it feels more like a bunch of black boxes than an easy to use appliance, and when things go wrong, I have to figure out which container is going wrong.

In particular, using preexisting Certbot certificates should be a simple process, to make transitioning to using AzuraCast's proxy frontend as smooth as possible.

**Comment by Vaalyn** [comment]
> While this is unsupported given the specs, I might recommend not recommending even 1 GB of RAM as enough anymore.

Where do we recommend 1GB of RAM?

![image](https://user-images.githubusercontent.com/13745863/102946199-347dc780-44c0-11eb-83c1-7efcf10eaa4a.png)

As you wrote in a comment your network issues were due to a wrongly configured `resolv.conf` which is not something that we anticipate.
We are a very small team so we can't anticipate each and every thing that might go wrong when someone re-purposes a server/vm that was previously doing something else. Which is why it is written in the install instructions to use a fresh server:

> Regardless of which OS you choose, to avoid any compatibility or permissions issues you should install AzuraCast on a fresh minimal installation without Docker or Docker Compose installed.

You also mentioned that you tried using [custom certificates](https://www.azuracast.com/extending/modifying-docker.html#custom-ssl-certificates) and that this resulted in `an incredibly loud warning message from Docker warning that the file system is read-only, causing it to immediately halt.`. Could you provide us with the exact errors from your command line and how you configured your `docker-compose.override.yml`? If there is a problem with mounting custom certificates I'd like to know what it is exactly and how to reproduce it.

> In particular, using preexisting Certbot certificates should be a simple process, to make transitioning to using AzuraCast's proxy frontend as smooth as possible.

In general it should be quite easy to do by just creating a `docker-compose.override.yml` according to the documentation and restarting the containers. If there is a bug causing this to not work then we can surely fix that.

In regards of providing documentation for `Integration or smooth transition for existing webservers` I'm not sure what exactly could be written for that, as the only things would be "Either change the AzuraCast web ports as per the [documentation](https://www.azuracast.com/help/docker/#use-non-standard-ports) or change your existing Apache2/NGINX ports from 80/443 to something else or uninstall your existing Apache2/NGINX" and "Use the built-in [Let's Encrypt certificate generator](https://www.azuracast.com/extending/letsencrypt.html#enabling-https-with-letsencrypt) or provide your own custom certificates as per the [documentation](https://www.azuracast.com/extending/letsencrypt.html#using-a-custom-certificate)".

> troubleshooting the individual Docker containers, and documentation of each of them and what they're responsible for

We should definitely put a small description for each container on the [Troubleshooting](https://www.azuracast.com/help/#troubleshooting) page to help users better understand what each is responsible for. 

Regarding the troubleshooting stuff, what would you expect there to be apart from how to get logs (which is already written)?

@SC2Mitch regarding documentation the `./docker.sh letsencrypt-renew` command does not exist anymore as that is entirely handled by the [jrcs/letsencrypt-nginx-proxy-companion](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion) so we should remove that from [here](https://www.azuracast.com/developers/docker-sh.html#renew-a-letsencrypt-certificate) or replace it with the text from [here](https://www.azuracast.com/extending/letsencrypt.html#enabling-letsencrypt).

**Comment by EmpressFiona** [comment]
> Where do we recommend 1GB of RAM?
Some issues mention it, including fairly recent ones, for a very small installation with only a tiny handful of listeners. Since that was my use case, I thought I'd at least give it a shot.

I know it's not officially recommended, but *unofficially* it still seems to be, including on Ansible documentation where it indicates resource-strained installs. I gave it a shot and it actually worked much more smoothly than Docker in a lot of ways, though various issues of configuration made it obvious it wasn't going to be my end use case.

This is just a mention of my experience with something that people have tried here, and that maintainers have talked about. I don't consider this an actual problem with the software given the official requirements.

> You also mentioned that you tried using custom certificates and that this resulted in an incredibly loud warning message from Docker warning that the file system is read-only, causing it to immediately halt.. Could you provide us with the exact errors from your command line and how you configured your docker-compose.override.yml? If there is a problem with mounting custom certificates I'd like to know what it is exactly and how to reproduce it.

This is the config:

```
version: '2.2'

services:
  web:
    volumes:
      - /media/fiona/XXXXX/shared-media/XXXXX:/var/azuracast/stations/XXXXX/media
      - /etc/letsencrypt/live/empress.duckdns.org-0001/fullchain.pem:/etc/nginx/certs/yourdomain.com.crt:ro
      - /etc/letsencrypt/live/empress.duckdns.org-0001/privkey.pem:/etc/nginx/certs/yourdomain.com.key:ro

  stations:
    volumes:
      - /media/fiona/XXXXX:/var/azuracast/stations/XXXXX/media
      - /etc/letsencrypt/live/empress.duckdns.org-0001/fullchain.pem:/etc/nginx/certs/empress.duckdns.org.crt:ro
      - /etc/letsencrypt/live/empress.duckdns.org-0001/privkey.pem:/etc/nginx/certs/empress.duckdns.org.key:ro
```

The error is below:

```
Creating network "azuracast_frontend" with driver "bridge"
Creating network "azuracast_backend" with driver "bridge"
Creating azuracast_redis_1   ... done
Creating azuracast_stations  ... error
Creating azuracast_mariadb_1 ... done

ERROR: for azuracast_stations  Cannot start service stations: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/etc/letsencrypt/live/empress.duckdns.org-0001/privkey.pem" to rootfs at "/var/lib/docker/overlay2/74c1a1f79907eb661d8f759fa31b6008627d91b9d0de92d918caa4d96f0e98a2/merged/etc/nginx/certs/empress.duckdns.org.key" caused: open /var/lib/docker/overlay2/74c1a1f79907eb661d8f759fa31b6008627d91b9d0de92d918caa4d96f0e98a2/merged/etc/nginx/certs/empress.duckdns.org.key: read-only file system: unknown

ERROR: for stations  Cannot start service stations: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/etc/letsencrypt/live/empress.duckdns.org-0001/privkey.pem" to rootfs at "/var/lib/docker/overlay2/74c1a1f79907eb661d8f759fa31b6008627d91b9d0de92d918caa4d96f0e98a2/merged/etc/nginx/certs/empress.duckdns.org.key" caused: open /var/lib/docker/overlay2/74c1a1f79907eb661d8f759fa31b6008627d91b9d0de92d918caa4d96f0e98a2/merged/etc/nginx/certs/empress.duckdns.org.key: read-only file system: unknown
ERROR: Encountered errors while bringing up the project.
```

As you can see, it yells about a read-only file system. (Names on the original keys per official conventions.) This is the recommendation on your documentation, so if this isn't working, it's probably a bug.

I mentioned that this might be upstream, though - and that's part of the issue. Relying on a wide variety of different containers doing a lot of different jobs, some of which aren't maintained here, seems to be causing issues. But because the Docker containers are so closed off and the volumes are split up so much, it's not simple to troubleshoot. While the Ansible installation had its problems, and I'm familiar with the difficulties caused by dependencies, I was able to more effectively solve my own issues.

> As you wrote in a comment your network issues were due to a wrongly configured resolv.conf which is not something that we anticipate.
> We are a very small team so we can't anticipate each and every thing that might go wrong when someone re-purposes a server/vm that was previously doing something else. Which is why it is written in the install instructions to use a fresh server:
As it happens, this was only my first guess. Changing my system's resolv.conf around to make the proper DNS server the first didn't fix it. My other Docker containers don't seem to have this problem, either; it's just the AzuraCast ones. I poked into one and in its resolv.conf it shows 127.0.0.11...

I had to add my router in as an intermediary - that is, making it so that 192.168.1.1 was my top nameserver, so Docker didn't loop back on itself and fail when trying to contact another container. From the looks of it, this is a general problem with Pi-hole and AdGuard Home. At the very least, this isn't an AzuraCast bug, but if people *are* running multiple Docker services, it's probably a good idea to help them out.

> In regards of providing documentation for Integration or smooth transition for existing webservers I'm not sure what exactly could be written for that, as the only things would be "Either change the AzuraCast web ports as per the documentation or change your existing Apache2/NGINX ports from 80/443 to something else or uninstall your existing Apache2/NGINX" and "Use the built-in Let's Encrypt certificate generator or provide your own custom certificates as per the documentation".
Currently the instructions insist on just generating new LE certs. If you have preexisting certificates, the only method to import them is the one that's bugged. Picking up the config off an existing Certbot installation on the host seems like a good idea.

Honestly, while it increases support overhead, it might be better to have some method of using an outside proxy - if that's technically feasible. It's probably not a huge priority, but AzuraCast asks a lot of the end user already.

> Regarding the troubleshooting stuff, what would you expect there to be apart from how to get logs (which is already written)?

Mostly the specific Docker containers and problems with them - and potential customization of their configuration. The proxy in particular might be a sticking point, especially if a multi-site installation is being run entirely through it; if it breaks in some fashion, so does the rest of the server! AzuraCast isn't exactly a one-click solution to begin with; documenting how to work with its structure would be really helpful.

**Comment by EmpressFiona** [comment]
I'm back on the Docker install, and I got a new error:

```
An exception occurred while executing 'SELECT t0.id AS id_1, t0.type AS type_2, t0.adapter AS adapter_3, t0.path AS path_4, t0.s3_credential_key AS s3_credential_key_5, t0.s3_credential_secret AS s3_credential_secret_6, t0.s3_region AS s3_region_7, t0.s3_version AS s3_version_8, t0.s3_bucket AS s3_bucket_9, t0.s3_endpoint AS s3_endpoint_10, t0.dropbox_auth_token AS dropbox_auth_token_11, t0.storage_quota AS storage_quota_12, t0.storage_used AS storage_used_13 FROM storage_location t0 WHERE t0.type = ?' with params ["station_media"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.storage_location' doesn't exist
```

This wasn't in the console; it was in the web interface.

Doing an update fixed it. It looks like it's a database issue of some kind. Maybe related to AzuraCast being unable to put up its services fast enough, maybe related to me setting a volume up before the containers were up, or that it timed out on starting its services.

**EDIT:** In case it's not clear, the Docker install is on a home server with far more than 1 GB of RAM, so I'm not still trying to run it on the VPS.
Also, I got another error:

```
500
Impossible to create the root directory "/var/azuracast/stations/apple/playlists". mkdir(): Permission denied
Local.php : 112
```

Since this is inside the Docker containers, this should be impossible.
