### ISSUE TITLE
500 error: limit of 255 listeners.

### ISSUE THREAD

**Issue by andx512** [AzuraCast/AzuraCast#3600]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.11.2 Stable

**Host Operating System**
Ubuntu 20.04.1 LTS (Focal Fossa)

**Describe the bug**
Good day!
We faced the fact that the server with AzuraCast installed was able to connect about 255 users, and on subsequent connections went with an error of 500. Nothing was saved in the logs, I lost time, the old logs were gone.
The data on the peak of clients from icecast - 255 listeners, although there were many times more.
Server 1 CPU 2 GB RAM.
UBUNTU Os 20.04
The limit on the number of icecast listeners has been set at 4500.
Server logs did not report errors.

**Screenshots**

![image](https://user-images.githubusercontent.com/76536700/103036554-d74f4800-458b-11eb-824b-177af109e31c.png)
![image](https://user-images.githubusercontent.com/76536700/103036591-f1892600-458b-11eb-8a43-f52e8f472b1f.png)

**Comment by DefectivenessYT** [comment]
This might possibly be a hardware limitation, a thing to test though, are you accessing via /radio/8000 or port 8000 on the vps?

**Comment by Vaalyn** [comment]
Closing as resolved.

If you encounter any further issues regarding the listener amount please follow #3702.
