### ISSUE TITLE
Error after created second station, not start Liquidsoap

### ISSUE THREAD

**Issue by petrechkiv** [AzuraCast/AzuraCast#3602]
Docker installation

**Using Docker installation method**

Yes
**AzuraCast version**

0.9.8.1
**Host Operating System**

Ubuntu 18.04
**Describe the bug**

After create second station
Liquidsoap error
At line 117, char 8-43:
Error 7: Invalid value: That source is fallible
At line 117, char 8-43:
Error 7: Invalid value: That source is fallible
At line 117, char 8-43:
Error 7: Invalid value: That source is fallible
**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
Please update your installation from `0.9.8.1` to at least the current stable version `0.11.2`. The version you are using is nearly 1 year old. We do not provide support for versions that are this old since we have fixed, improved and reworked quite a lot of things since then.
