### ISSUE TITLE
API station files only returns 10 ITEMS

### ISSUE THREAD

**Issue by markus-dark-green** [AzuraCast/AzuraCast#3609]
Hallo!
.

**Install Method  docker script ***

**AzuraCast version**
Rolling Release #e4e7f8c (2020-12-24 1:33) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 18.04 LTS 64bit

**Describe the bug**
Since latest update the API Call to   /station/id/files only returns 10 rows. But within Media in the admin panel there are many more...
**To Reproduce**

**Expected behavior**
Return all Songs which are in the repository of the station

**Additional context**
Is there a pagination setting or something new added to the api restrict result set?

**Comment by markus-dark-green** [comment]
Found a quick fix solution for that issue:

Add  ?per_page=0  to the  https://xxx/api/<stationid>/files call
It returns then a one pager with all entries

**Comment by SlvrEagle23** [comment]
@markus-dark-green Should be fixed as of latest update.

**Comment by markus-dark-green** [comment]
@SlvrEagle23 how does it behave now?   ist my fix still working or how is it set now?

**Comment by SlvrEagle23** [comment]
@markus-dark-green You don't need to apply any special query parameters as of the latest rolling-release update. It'll show all records by default unless you provide pagination query parameters.
