### ISSUE TITLE
Remove azuracast text from the public radio url

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#361]
Hello,

How can i remove the AzuraCast text from the public radio.
On my browser i see now like this : Radio Example - AzuraCast
I just want to show Radio Example on the browser

title>Radio Example - AzuraCast</title>

**Comment by surihost** [comment]
And also if you could add the option to load our own logo in the dashboard

**Comment by surihost** [comment]
If possible can you also add the option to display the portnumber of the station which is in use on the main dashboard.

**Comment by SlvrEagle23** [comment]
@surihost Please keep Github issues to one issue at a time. In this case, this issue is for the original request to allow the removal of the "AzuraCast" branding in the titlebar. Please create new issues for the other questions.

**Comment by SlvrEagle23** [comment]
@surihost For all the nothing you folks pay for AzuraCast, it's a wonder to me that such a request would exist at all, to remove even the most minor mention of the application's name from public pages, when this is about the smallest possible credit one can give to the free software running things under the hood.

Nonetheless, I can see the value this offers to white-label applications of the software, and I can also see how some would consider exposing the software name to be something of a vulnerability, though this is more of a "security through obscurity" thing (a-la turning server tokens off).

You'll find a "Hide AzuraCast name" setting inside the branding configuration page now, which will remove it from both the public-facing login page and the public radio pages.
