### ISSUE TITLE
AzuraRelay error: Instance crashes on reaching 600+ listeners

### ISSUE THREAD

**Issue by engrsam** [AzuraCast/AzuraCast#3610]
**Using Docker installation method**

Yes

**AzuraCast version**

v0.11.2

**Host Operating System**

Ubuntu 20.04

**Describe the bug**

My AzuraRelay instance displays internal error 500 and crashes when listeners traffic reaches 600 listeners on visiting relay url: 
http://0.0.0.0:85/radio/8000/live

**To Reproduce**

cd /var/azurarelay 
docker-compose logs -f

**Expected behavior**

**Relevant Logs**

nginx.1    | 2020/12/27 08:02:55 [alert] 130#130: *55836 1024 worker_connections are not enough while connecting to upstream, client: 0.0.0.0, server: azurarelay.local, request: "GET /radio/8000/live?90987866 HTTP/1.1", upstream: "http://192.168.0.2:80/radio/8000/live?1569692293", host: "domain.org"

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

My setup uses an Azuracast instance with another relay instance and i use nginx load balancing to handle the traffic. How can you guys help me to increase the connection count on my instance up to 20k thousand live listeners. Thanks

**Comment by SlvrEagle23** [comment]
This was fixed as of an updated release of AzuraRelay.
