### ISSUE TITLE
After the last update i only see the first mount point on the profile page

### ISSUE THREAD

**Issue by PB-SF** [AzuraCast/AzuraCast#3611]
**Using Docker installation method**
No, Ansible

**AzuraCast version**
 Update to Rolling Release # cac7ec9 (2020-12-27 23:49)

**Host Operating System**
Ubuntu 18.04.

After the last update to Rolling Release # cac7ec9 (2020-12-27 23:49) i only see the first mount point on the profile page in the streams section.

As before, all 4 installed mount points are available and these are also played out properly. They are just no longer visible.

Is this a new feature or is it a bug during the update?

So far it has always been a good thing that all mount points were displayed here. Because of quick access.

**Comment by SlvrEagle23** [comment]
@PB-SF I'm not seeing this error on any of my installations. Are all the mount points enabled?

**Comment by PB-SF** [comment]
@SlvrEagle23 The Mountpoints are enabled and playing well. I see all mountpoints on the mountpoint page and also in Icecast. But on the profile page i see only the first one (of 4).

**Comment by PB-SF** [comment]
@SlvrEagle23 - i have 2 screenshots - maybe they can help you

On profile page only one mountpoint displayed:
![2020-12-30_07h13_09](https://user-images.githubusercontent.com/45131983/103333649-e09a5200-4a6e-11eb-8a83-ee97259665f8.png)

On mountpoint page i see all 4:
![2020-12-30_07h13_46](https://user-images.githubusercontent.com/45131983/103333665-ed1eaa80-4a6e-11eb-944c-cd132fa99057.png)

I also tried to delete an re-enable the mountpoint. that doesnt help.

Greets

**Comment by SlvrEagle23** [comment]
@PB-SF I've found the likely cause of this issue and the fix is released in the latest rolling release version.
