### ISSUE TITLE
404 Not Found Error when using custom url - mountpoint

### ISSUE THREAD

**Issue by SwaXTech** [AzuraCast/AzuraCast#3612]
**Using Docker installation method**
 YES

**AzuraCast version**
0.11.2
 

**Host Operating System**
 Ubuntu 20.04 LTS

**Describe the bug**

When inserting a custom url in the configuration of a mountpoint, when accessing it throws the error 404 not found.

**To Reproduce**

1. Go to 'mounpoints'
2. Click on 'edit'
3. Scroll down to 'advanced custom stream url'
4. Put an URL
5. See the error

**Expected behavior**

It should work when entering adfradio.com.ar/streaming

**Relevant Logs**

I don't know if it has to do, but I found this in the log:
`[2020-12-28T18:01:46.764488+00:00] AzuraCast.WARNING: Not found. {"file":"/var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php","line":91,"code":404} []`

**Screenshots**

![image](https://user-images.githubusercontent.com/43499966/103234332-301d3880-491e-11eb-8e9d-22062f9292cb.png)

![image](https://user-images.githubusercontent.com/43499966/103234368-45926280-491e-11eb-81ab-b611d47d9194.png)

**Comment by Vaalyn** [comment]
This setting is not for creating a custom URL. It can be used for example when you have a reverse proxy somewhere which proxies the stream to that URL and you want AzuraCast to show that URL instead of the "regular" URL in the AzuraCast interface.
