### ISSUE TITLE
shared media between 2 stations can only be assigned to 1 station's playlist

### ISSUE THREAD

**Issue by gosntvrdi** [AzuraCast/AzuraCast#3618]
**Using Docker installation method**

Yes

**AzuraCast version**

Rolling Release #0acefe8 (2020-12-29 21:27) • Docker • PHP 7.4

**Host Operating System**

Digitalocean 1-click installation app

**Describe the bug**

I am using shared media for 2 stations. When adding media to 1st station's playlist, it automatically deletes those files from 2nd station's playlist and viceversa. Additionally in 2nd station all files have message "File processing....". If I reassign those media files to a playlist, the message will dissapear, but it will appear on other station for those same files.

**Expected behavior**

Both stations should be able to assign media files to their own playlists - this worked in previous Azuracast versions.

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
Can confirm this problem happening on my test installation.

Thank you for reporting this issue.

**Comment by SlvrEagle23** [comment]
@gosntvrdi Thank you for the report; I was able to validate these same issues locally, and they've been fixed with some minor changes to our query structure. The fixes are now available in the latest rolling-release version, and we will likely include them in a stable release in the near future.

**Comment by gosntvrdi** [comment]
Hi, thanks for the quick response. I have updated the installation, but now it won't apply playlist to either station, no matter what. Log doesn't output any error.
