### ISSUE TITLE
Problem:  Stream breaks off and the stream is marked as offline

### ISSUE THREAD

**Issue by NurKai3** [AzuraCast/AzuraCast#3620]
**Server Information:**
System: Debian 10
Azuracast Version: Docker, v0.11.2 Stable
CPU: 2 vCores
Ram: 4 GB
Space: 80 GB SSD

**The Problem / The Error:** 
The problem is that the stream stops and only starts again after a few seconds to minutes. Azuracast was reinstalled. The stream will also be marked as "Offline" in the AzuraCast interface. The playlist then continues to run normally, as if nothing had happened. It went for 6-7 hours now and now the problem started again with AzuraCast. I even reinstalled the whole root server. The playlist is on the server.
https://i.imgur.com/vi15DdV.png

**Comment by Vaalyn** [comment]
Please provide us with your `Liquidsoap Log` from `Utilities` -> `Log Viewer`.

**Comment by NurKai3** [comment]
https://nextcloud.nurkai.eu/index.php/s/cQrrbwocE6p9eiG

**Comment by Vaalyn** [comment]
I haven't seen that error yet, interesting. 🤔 

Could you also provide us with the `Liquidsoap Configuration` and the `Icecast Error Log` from the same page?

**Comment by NurKai3** [comment]
https://nextcloud.nurkai.eu/index.php/s/ZWsy3rd2zZjgN6Y Liquidsoap Configuration
https://nextcloud.nurkai.eu/index.php/s/kJc7SaDXLxC3bBC Icecast Error Log

**Comment by Vaalyn** [comment]
The problem seems to be with the remote relay.

Can you also post the logs of that relay?

If you are using the `AzuraRelay` you can view its logs via the console and the command `docker-compose logs relay` from within the directory of the relay.

**Comment by NurKai3** [comment]
I'm using the AzuraRelay but the Console says: `root@vServer:~# cd /var/azuracast/
root@vServer:/var/azuracast# docker-compose logs relay
ERROR: No such service: relay`

https://hastebin.com/vipuduyapu.apache https://i.imgur.com/Yl7oM3C.png

**Comment by Vaalyn** [comment]
You have to use this command on the server where the relay is installed (and while being inside the directory of the relay).

**Comment by Vaalyn** [comment]
Make sure the directory you are in contains `docker-compose.yml` of the `AzuraRelay` / make sure you are on the server of the relay (check with `ls` and look into the file to make sure it's definitely correct.).

You could also omit the `relay` from the command to get the logs of all the containers of the relay.

**Comment by NurKai3** [comment]
There is nothing in the logs, simply nothing, with "relay", I uploaded the log here.https://nextcloud.nurkai.eu/index.php/s/Pe6cS54BojtS3ae 

But I use the relays; https://i.imgur.com/Yl7oM3C.png

**Comment by Vaalyn** [comment]
You are not running the `docker-compose logs` command in the directory where your `AzuraRelay` is installed. You are running it in the directory where `AzuraCast` is installed.

**Comment by NurKai3** [comment]
It was already included in the AzuraCast installation. I have not changed anything on it. I can't find a log for it either. https://i.imgur.com/e3f9crB.png

**Comment by Vaalyn** [comment]
@NurKai3 you are confusing me quite a bit here.

Please clarify some things for me.

You answered that you are using the `AzuraRelay` project for your `Remote Relay` but now you say that your `Remote Relay` came already with your `AzuraCast` installation. That doesn't make sense to me as we don't include the `AzuraRelay` itself in `AzuraCast`.

Did you install our [`AzuraRelay`](https://github.com/AzuraCast/AzuraRelay) on a server via the instructions on that Repository or not?

If you didn't install `AzuraRelay` on any server how have you setup your `Remote Relay` / what kind of `Remote Relay` is that`?

**Comment by NurKai3** [comment]
I'm sorry if it's confusing.

This "remote relays" was with the Installtion, no idea why, but it has
always been with it: https://i.imgur.com/RnsJmMS.png

I don't know how else to explain it, the problem always occurs more in the
evening, during the day I have no problems.

I suspect quite simply explained that this "remote relays" function is
responsible for the malfunction.

I have AzuraCast installed normally without any additional things, via
Docker installation on Debian 10. I use this "remote relays" feature to
broadcast to another station, but I as I said nothing else installed. I
also don't know.

I can also give you access to the server if you add me via Discord, then
you can see for yourself. It is only an offer.

Am So., 3. Jan. 2021 um 20:20 Uhr schrieb Vaalyn <notifications@github.com>:

**Comment by Vaalyn** [comment]
The thing I was not understanding is answered by this sentence of you:
> I use this "remote relays" feature to broadcast to another station

Since you were saying before that you were using (and then later on that you aren't) the `AzuraRelay` which is a separate project apart from `AzuraCast` this was pretty confusing to me. Especially when you wrote that "It was already included in the AzuraCast installation" which didn't make much sense in my head. Didn't think you were refering to the `Remote Relay` feature in general with that.

When you say you are just using the `Remote Relay` feature to broadcast to another station that's a pretty clear description to me. Thank you for clarifying that.

Could you also share the configuration of the mount point on your second station (the one that you are broadcasting to via the `Remote Relay` feature)?

**Comment by Vaalyn** [comment]
Closing this issue since no further information was supplied and the provided logs / config files are no longer available so we can't debug this anymore.
