### ISSUE TITLE
You can't add songs/folders to playlist. Passing null.

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#3622]
**Using Docker installation method**
No

**AzuraCast version**
Rolling Release #916deb7 (2021-01-02 18:28)

**Host Operating System**
Ubuntu 18.04.1 LTS

**Describe the bug**
It seems like can't get the dom elements. It's sending `null` instead of filename or folder name to the batch api
```
URL: http://172.16.1.202/api/station/1/files/batch
Status: 500 Internal Server Error
Source: Network

code: 500
extra_data: []
formatted_message: "<b>TypeError at /var/azuracast/www/src/Flysystem/Filesystem.php L141:</b> Argument 1 passed to App\Flysystem\Filesystem::createIterator() must be of the type string, null given, called in /var/azuracast/www/src/Controller/Api/Stations/Files/BatchAction.php on line 404"
message: "TypeError at /var/azuracast/www/src/Flysystem/Filesystem.php L141: Argument 1 passed to App\Flysystem\Filesystem::createIterator() must be of the type string, null given, called in /var/azuracast/www/src/Controller/Api/Stations/Files/BatchAction.php on line 404"
success: false

{"do":"playlist","playlists":[7],"new_playlist_name":"","currentDirectory":"Storage","files":[],"dirs":[null]}
{"do":"playlist","playlists":[7],"new_playlist_name":"","currentDirectory":"Storage/Dance & Pop","files":[null,null,null,null,null,null,null,null,null,null,null,null,null],"dirs":[]}
```

**Device(s):**
 - Device: Raspberry Pi 3b+

**Comment by SlvrEagle23** [comment]
@NicoxDJ Should be fixed now. Sorry about that and thank you for the report.

**Comment by NicoxDJ** [comment]
@SlvrEagle23 Hey, thanks for the fast response. I found another bug, that is similar with this one, that's why i don't want to open new issue. So basically when you add folder/file to playlist later you have option to remove it, when select the folder and open the menu with playlists should be selected, and than deselect and save again. But the checkbox is no more checked.
![](blob:https://imgur.com/0dabbbd9-1a33-4776-8246-5c06ef22db46)

**Comment by SlvrEagle23** [comment]
@NicoxDJ Thanks for the additional report; this is fixed in the newest rolling release that's going out now.
