### ISSUE TITLE
AutoDJ help

### ISSUE THREAD

**Issue by SimonJStark** [AzuraCast/AzuraCast#3623]
I always get this azura jingle as soon as the autodj has run through. How do I get rid of that AutoDJ repeats itself over and over again?

**Comment by Vaalyn** [comment]
Here is a guide on how to use your own default track that is played when nothing else is playing. If you want there to just be silence on the stream use a track that contains only silence: https://www.azuracast.com/help/docker/#using-a-custom-default-track
