### ISSUE TITLE
Hide list of mountpoins

### ISSUE THREAD

**Issue by grupoexperiencia** [AzuraCast/AzuraCast#3624]
Hello everyone, I would like how to hide the audience of a station with azura, that is, let's imagine that we have page XX.XX.X: 8000 if you access there you get all the mountpoints (and listeners), my intention is to hide that page but without using the `<hiden>1<hiden>` so that we can see the audience at all times. It would be like showing another website, but that we through the control panel if we can see the audience.

I hope I explained myself correctly, thanks in advance everyone.

**Comment by Vaalyn** [comment]
There is no built-in method of hiding this page apart from using the `<hiden>1<hiden>` in the frontend config of the mount points.

You could theoretically do this with a custom reverse-proxy but this is out of scope for the support that we provide.

You are welcome to open a discussion on our GitHub Discussions page to talk with others about this: https://github.com/AzuraCast/AzuraCast/discussions
