### ISSUE TITLE
No changes after update

### ISSUE THREAD

**Issue by talionwar** [AzuraCast/AzuraCast#363]
Hi, I'm running azuracast on a Vps with ubuntu 16.0 lts updated and upgraded. The azuracst's updates were successfully completed with 64 modules and 18 changes,  vps  restarted but no changes  were made on the core. 
Thanks for your work and happy new year

**Comment by SlvrEagle23** [comment]
@talionwar What do you mean, no changes were made? The recent changes have largely been smaller bug fixes that affect the web application, but you wouldn't see those as major core changes.

**Comment by SlvrEagle23** [comment]
@talionwar I'm closing this issue as there has been no response for a month now, but if you do find that your local copy of AzuraCast isn't updating properly from the source code, make sure your installation of Git is functioning properly and is up-to-date. You may also need to manually run `git reset --hard && git pull` in the AzuraCast root to reset any local changes and pull down new changes. After this, you should make sure to run either `./update.sh` (for traditional installations) or `./docker-update.sh` (for Docker ones).
