### ISSUE TITLE
Is it possible to clear the Upcoming Song Queue?

### ISSUE THREAD

**Issue by madwonko** [AzuraCast/AzuraCast#3632]
**Using Docker installation method**
Yes

**AzuraCast version**
 Rolling Release #b74a0c4 (2021-01-04 8:35) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 20.04.1 LTS

**Describe the bug**

Added several thousand songs to the Queue by mistake and now the Upcoming Song Queue keeps being populated. There are 3 and never more than 4 songs in the queue and removing them and refreshing the page adds 3 or 4 songs again. 

**To Reproduce**

**Expected behavior**

I would imagine that a command exists to clear the queue but I have not been able to find it.

**Relevant Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/57959443/103579908-36279200-4ea7-11eb-802d-bdd229ed49d1.png)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

I have restarted Liquidsoap, the Broadcasting Service and the station individually and restarted the server to no avail.

**Comment by Vaalyn** [comment]
The `Upcoming Song Queue` is always being automatically filled up by AzuraCast to the limit set in the station profile `AutoDJ Queue Length`.

Why do you want to have this list be empty?
It is not meant to be empty as this is where the AutoDJ is pulling the songs from that it should push to Liquidsoap to play next.

What exactly do you mean with the following sentence:
> Added several thousand songs to the Queue by mistake

As seen in your screenshot there are just 3 songs in the queue.
If you have manually queued up songs via the `Music Files` page they would be in that list (additionally to the other ones and would have no `source`).

**Comment by madwonko** [comment]
I hit the Queue button after I selected a bunch of folders 
![image](https://user-images.githubusercontent.com/57959443/103582731-750c1680-4eac-11eb-9766-cb1cc4f055c7.png)

The Song Request feature is disabled.
![image](https://user-images.githubusercontent.com/57959443/103583082-1a26ef00-4ead-11eb-9b36-731f8fc446b6.png)


My reasoning was that the songs in the queue were added manually as I have all the playlists disabled except one, and the songs played are in alphabetical order from the playlist AllJazz, which is disabled...

**Comment by madwonko** [comment]
For example, right now is again playing the AllAmbient playlist, but the next queued song is not in that playlist,
![image](https://user-images.githubusercontent.com/57959443/103708252-35156400-4f7e-11eb-8ad2-28058a8562e1.png)

and the list in Upcoming Song Queue is also not from AllAmbient
![image](https://user-images.githubusercontent.com/57959443/103708321-5d9d5e00-4f7e-11eb-9c82-9189251c2ade.png)

**Comment by madwonko** [comment]
I figured it out: when Song Request is enabled and additional menu item appears in Reports, Song Requests. From there it is possible to erase all requests.
![image](https://user-images.githubusercontent.com/57959443/103913097-2b067900-50d6-11eb-9709-094addeb0cc7.png)
