### ISSUE TITLE
Enabling CORS not working

### ISSUE THREAD

**Issue by flybelgium** [AzuraCast/AzuraCast#3634]
Hello,
I dont understand why the CORS policy not working.
i have added the security tab with **Access-Control-Allow-Origin: *** and my player wont retrieve api now playing.
`Access to XMLHttpRequest at 'https://domain.com/api/nowplaying?_=1609834945766' from origin 'https://anotherdomain.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

How i can check if CORS in correctly enabled in azuracast ?
I have to edit nginx conf file directly ? Docker-compose.yml ?
I'm not expert about that.

I can run everything api from swagger  > mydomain.com/static/api > all is working.
Thanks in advance.

**Comment by SlvrEagle23** [comment]
@flybelgium Did you set it to `*` or to a specific domain? If you set it to `***` that won't work. It also won't return an ACAO header on an API call unless it actually matches the domain(s) specified in the ACAO header list.

**Comment by flybelgium** [comment]
i have set this syntax : " Access-Control-Allow-Origin: * "
![alloworigin](https://user-images.githubusercontent.com/43602020/103627011-4e49f080-4f3d-11eb-9f68-fb69a9535ac8.JPG)

**Comment by SlvrEagle23** [comment]
@flybelgium You can just put `*` in that field. We automatically set the header name.

**Comment by flybelgium** [comment]
> @flybelgium You can just put `*` in that field. We automatically set the header name.

Yes ! It working ! Just the documentation is not really explained about that... just syntax problem.
Thank you very much SlvrEagle23
