### ISSUE TITLE
Letsencrypt cant secure domain.

### ISSUE THREAD

**Issue by JohnKoumpouras** [AzuraCast/AzuraCast#3636]
**Using Docker installation method**
Yes (Digital Ocean)

**AzuraCast version**
Rolling Release #991465d (2021-01-05 11:02)

**Host Operating System**
Ubuntu Server 20.04

**Describe the bug**
After a new installation the "letsencrypt-create" command does not create a correct certificate and the domain appears unsafe on the browser

**To Reproduce**

**Expected behavior**

**Relevant Logs**
This is a small section of "docker-compose -f logs"

nginx_proxy_1              | WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
nginx_proxy_1              | is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
nginx_proxy_1              | Generating DSA parameters, 4096 bit long prime
nginx_proxy_1              | forego     | starting dockergen.1 on port 5000
nginx_proxy_1              | forego     | starting nginx.1 on port 5100
nginx_proxy_1              | dockergen.1 | 2021/01/05 11:31:40 Generated '/etc/nginx/conf.d/default.conf' from 6 containers
nginx_proxy_1              | dockergen.1 | 2021/01/05 11:31:40 Running 'nginx -s reload'
nginx_proxy_1              | dockergen.1 | 2021/01/05 11:31:40 Watching docker events
nginx_proxy_1              | dockergen.1 | 2021/01/05 11:31:40 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx_proxy_1              | 2021/01/05 11:31:45 [notice] 64#64: signal process started
nginx_proxy_1              | dhparam generation complete, reloading nginx
nginx_proxy_1              | Custom dhparam.pem file found, generation skipped
nginx_proxy_1              | forego     | starting dockergen.1 on port 5000
nginx_proxy_1              | forego     | starting nginx.1 on port 5100
nginx_proxy_1              | dockergen.1 | 2021/01/05 11:32:28 Generated '/etc/nginx/conf.d/default.conf' from 6 containers
nginx_proxy_1              | dockergen.1 | 2021/01/05 11:32:28 Running 'nginx -s reload'
nginx_proxy_1              | dockergen.1 | 2021/01/05 11:32:28 Watching docker events
nginx_proxy_1              | dockergen.1 | 2021/01/05 11:32:28 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
Take a look at the output of `docker-compose logs nginx_proxy_letsencrypt`.

I'm assuming you might be running into rate limits from Let's Encrypt which should be visible in the logs of that container (have seen it a few times already).
