### ISSUE TITLE
Music files are there, but won't display

### ISSUE THREAD

**Issue by krakenfury** [AzuraCast/AzuraCast#3640]
**Using Docker installation method**

yes

**AzuraCast version**

Rolling Release #991465d (2021-01-05 11:02)

**Host Operating System**

Debian 10

**Describe the bug**

After updating this evening, I am not able to list music files in my station anymore. Media storage location is s3 compatible object storage hosted in Linode which worked perfectly until updating. Up at the top it lists an accurate size and count for the summary, but where the rows were it just shows "Loading..." and spins but never loads the list. Screenshot included. Liquidsoap still works fine, and station plays music. I can even see the folders listed if I click "move". I can see the files listed in playlists (configure playlist as sequential and then "reorder"). Nothing else seems to be affected, only displaying the music files.

**To Reproduce**

1. Update to latest rolling release
2. Go to "manage station"
3. Go to "music files"

**Expected behavior**

Music files should show folders and files in rows.

**Relevant Logs**

I don't see any relevant logs when doing `docker-compose logs -f`. I would welcome an alternative method to see more logs. Log levels are whatever defaults are configured in docker-compose.yml

**Screenshots**

![2021-01-06-094545_931x763_scrot](https://user-images.githubusercontent.com/11742556/103784754-5327a680-5008-11eb-891c-e80f20a5c301.png)

**Device(s):**
 - Device:  Desktop
 - OS:  Arch Linux
 - Browser:  Chromium
 - Version:  Version 87.0.4280.88

**Additional context**

I attempted a couple of things, neither was successful:
1. I restored from a backup taken before the update. Since my storage is in s3, I elect to omit media storage backup, so the backup contained config. The restore works fine, but still won't show media file rows.
2. I redid the storage location config. I just removed it from the station, deleted it from storage locations, then created it new and added it to the station. At first, the summary went back to 0GB 0 files, but then I ran the 5 minute sync from the system debugger page, and it re-imported all the files. I waited for the summary to catch up refreshing music files page every few minutes, but the rows still would not list after it finished.
3. This looks to be like a database problem, but I don't have the knowledge to troubleshoot it.

**Comment by Vaalyn** [comment]
Could you open your browsers JavaScript console and look if there is any error showing up there (also look into the network tab)?

When the media list fails to load there should be a failed network request with more information.

**Comment by krakenfury** [comment]
Thanks @Vaalyn, you're right!

The GET request to `https://{stationDomain}/api/station/2/files/list?internal=true&rowCount=10&current=1&currentDirectory=` returns 500

Here's the response:
```{"code":500,"message":"TypeError at /var/azuracast/www/src/Controller/Api/Stations/Files/ListAction.php L282: Typed property App\\Entity\\Api\\FileList::$timestamp must be int, null used","formatted_message":"<b>TypeError at /var/azuracast/www/src/Controller/Api/Stations/Files/ListAction.php L282:</b> Typed property App\\Entity\\Api\\FileList::$timestamp must be int, null used","extra_data":[],"success":false}```

There's another error I don't know anything about, though:
```Uncaught (in promise) TypeError: Cannot read property 'message' of undefined
    at StationMedia-792d8bb1ce.js:1```

`StationMedia-792d8bb1ce.js:1` is a different link: `https://{stationDomain}/static/dist/StationMedia-792d8bb1ce.js`

**Comment by Vaalyn** [comment]
@krakenfury thank you for posting the error. 

According to the error the problem lies in this line [here](https://github.com/AzuraCast/AzuraCast/blob/master/src/Controller/Api/Stations/Files/ListAction.php#L282) where we assign the `timestamp` of the metadata that we get from the filesystem for each file to the respective `FileList` API response.

It seems like the S3 filesystem adapter can return metadata where this `timestamp` is not set at all (for whatever reason, couldn't find anything about this in the S3 documentation).

This is pretty easy to fix so I'll submit a PR with the fix.

**Comment by krakenfury** [comment]
@Vaalyn thanks a ton. maybe Linode object storage used to return those tags in the metadata? seems like the bug was introduced with the recent update, though. anyhow, thanks for looking into this, and i'll watch the PR.
