### ISSUE TITLE
.PLS not running on winamp.

### ISSUE THREAD

**Issue by JustIrinel** [AzuraCast/AzuraCast#3642]
Hello guys,

Any ideea why the listen .pls file is not working in Winamp ? I see it's working only on VLC Player. I need somehow to make it run on winamp.

I am using latest version of Azuracast installed from Digital Ocean.

**Comment by Vaalyn** [comment]
Winamps current version is unable to play HTTPS streams with SSL certificates from Let's Encrypt. Seeing as the current version `5.666` was released in 2013 this is not a surprise.

On http://winamp.com/ they shared a new beta version of Winamp with `5.8` which I've confirmed to be able to open the streams that it couldn't in `5.666`. You could also manually distribute .pls files where you changed the `https://` to `http://` and probably also change the url from for example `/radio/8000/radio.mp3` to `:8000/radio.mp3` to make sure that the web proxy doesn't automatically forward to https.
