### ISSUE TITLE
  Many "AzuraCast Feedback Response: OK" entries in log. Stream stops. Using pipe

### ISSUE THREAD

**Issue by PB-SF** [AzuraCast/AzuraCast#3644]
Hi there.

I'm currently working on various complex scripts that need filters for the audio.

For the filters I use `FFMPEG` which i integrate via the `pipe` parameter of Liquidsoap at the end of the configuration.

Example for FFMPEG's dynaudnorm filter:
`radio = pipe (id = "ffmpeg", buffer = 5.00, max = 10.00, replay_delay = 1.00, restart_on_error = true, process = 'ffmpeg -i - -af dynaudnorm -f wav -', radio)`

After restarting the station everything runs normally. After about 5 minutes i get an entry "AzuraCast Feedback Response: OK" in the log almost every second. After a while, this in turn leads to the stream either falling back to the error jingle or stopping entirely.

![2021-01-07_13h24_58](https://user-images.githubusercontent.com/45131983/103892370-c1916500-50eb-11eb-880a-ad3d342fea75.png)

I have reproduced this on different machines. Both with Docker and with Ansible installations.

All machines are dedicated Ubuntu 18.04 Servers with 8 core CPUs and over 10 gigs of RAM. So it shouldn't be a performance problem.

The liquidsoap configuration is original from Azuracast except for FFMPEG via pipe.

It would be great if there was a solution for this.

That would make your great software perfect for me :)

many Greetings

**Using Docker installation method**
Docker & Ansible - tried both

**AzuraCast version**
Rolling Release #14cf57c (2021-01-05 5:51) 

**Host Operating System**
Ubuntu 18.04

**To Reproduce**
Include FFMPEG in Liquidsoap Script like my Example
Open Logfile and wait a few Minutes

**Comment by Vaalyn** [comment]
When pasting this line into my test installation Liquidsoap always crashes with the following error:

```
At line 86, char 8-43:
Error 7: Invalid value: That source is fallible
```

Could it be that there is something missing in the LS code you posted?

**Comment by PB-SF** [comment]
I am sorry, my mistake. I forgot the second line with the safe fallback:

`radio = fallback (id = "final_safe_fallback", track_sensitive = false, [radio, single (id = "error_jingle", "/var/azuracast/www/resources/error.mp3")])`

**Comment by SlvrEagle23** [comment]
@PB-SF The `AzuraCast Feedback Response: OK` line appears every time there's a metadata change, as that metadata change is then sent over to AzuraCast for processing and it responds with either an error or just `OK`. If you're getting a flood of them, it means the system thinks your metadata is changing every second, so that could be a problem that ends up flooding the system more than it should.

**Comment by Vaalyn** [comment]
@PB-SF I still get this error:

```
At line 84, char 8-43:
Error 7: Invalid value: That source is fallible
```

I added the following to the last config block in `Edit Liquidsoap Configuration`:
```
radio = pipe (id = "ffmpeg", buffer = 5.00, max = 10.00, replay_delay = 1.00, restart_on_error = true, process = 'ffmpeg -i - -af dynaudnorm -f wav -', radio)

radio = fallback (id = "final_safe_fallback", track_sensitive = false, [radio, single (id = "error_jingle", "/var/azuracast/www/resources/error.mp3")])
```

**Comment by PB-SF** [comment]
HI @Vaalyn 

I didn't see Docker and Ansible have different paths for the Azuracast Error Jingle. Sorry.

```
radio = pipe (id = "ffmpeg", buffer = 5.00, max = 10.00, replay_delay = 1.00, restart_on_error = true, process = 'ffmpeg -i - -af dynaudnorm -f wav -', radio)

radio = fallback(id="safe_fallback_final", track_sensitive = false, [radio, single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")])
```

![2021-01-09_07h00_47](https://user-images.githubusercontent.com/45131983/104084558-6cb73100-5248-11eb-891a-889d1447edf0.png)

Hopefully that should work now

FFMPEG should also be available on the system

**Comment by PB-SF** [comment]
Hi @SlvrEagle23 

I've now found that out. Thanks.

I just don't know where all the metadata updates come from. If I understand the FFMPEG man page correctly, the metadata is just looped through.

I don't know if that would work, but maybe it could be avoided if there was an additional custom field in the Liquidsoap configuration? Right before #Local Broadcasts?

Here the metadata in the script would have already been completely completed and given back to Azuracast and it would actually be the better mount point for filters or sound processing of all kinds.

**Comment by Vaalyn** [comment]
@PB-SF with the 2 lines from your 2nd last post I'm getting the following errors when I restart Liquidsoap:

```
Queue generic queue #1 crashed with exception Broken pipe in write()
Raised at file "tools/process_handler.ml", line 296, characters 16-23
Called from file "duppy.ml", line 151, characters 61-77
Called from file "duppy.ml", line 279, characters 14-23
Called from file "duppy.ml", line 313, characters 7-24
Called from file "duppy.ml", line 356, characters 5-9
Called from file "tools/tutils.ml", line 225, characters 18-54
```

I just copy and pasted the following lines at the bottom of the configuration as seen in the following screenshot:
```
radio = pipe (id = "ffmpeg", buffer = 5.00, max = 10.00, replay_delay = 1.00, restart_on_error = true, process = 'ffmpeg -i - -af dynaudnorm -f wav -', radio)

radio = fallback(id="safe_fallback_final", track_sensitive = false, [radio, single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")])
```

![image](https://user-images.githubusercontent.com/13745863/104104040-dc0f3e00-52a5-11eb-8a61-0a1da1098a7d.png)

**Comment by PB-SF** [comment]
Hi @Vaalyn 

I'm sorry to keep you up with this.

My main installation is Ansible for several reasons. FFMPEG does not work out of the box with Docker.

To test it, i got it to run on a Docker installation by logging into the container via SSH

`docker exec -it azuracast_web /bin/bash`

and it was installed right there with 

`apt-get update -y && apt-get install -y ffmpeg`

I know this is not the way to go, but it worked for a test with the code lines in liquidsoap config:

```
radio = pipe(id="ffmpeg", buffer=5.00, max=10.00, replay_delay=1.00, restart_on_error=true, process='/usr/bin/ffmpeg -i - -af dynaudnorm -f wav -', radio)

radio = fallback(id="test_safe_fallback", track_sensitive=false, [radio, single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")])
```

![2021-01-10_08h32_56](https://user-images.githubusercontent.com/45131983/104117079-790dbd80-531e-11eb-8c18-a898ef58a400.png)

I've tested some radio software over the past few years. Azuracast is the best so far.

Also because with my attempts for FFMPEG (and thus also other filters and processors such as stereo tool) it is the only software with which one could edit the sound directly in front of the stream server. That would be the icing on the cake :)

I am sure that many would welcome this as it saves a lot of work.
