### ISSUE TITLE
How to move the login box 

### ISSUE THREAD

**Issue by gInAmOsLaMi** [AzuraCast/AzuraCast#3646]
How can I edit the css of js of the login page to move the login box to any position and change the box size?

Thank You in Advance!

Best Regards and More Power to the Team

**Comment by Vaalyn** [comment]
In general you can add custom CSS and JS for public pages in the `Custom Branding` section of the administration.

We have a small guide on our page about customizing stuff with CSS: https://www.azuracast.com/extending/custom-css.html

Regarding the login specifically the page has a class `login-content` on the `<body>` element so if you want to apply styles only to that page you should prefix your CSS paths with this class.

For example if you want to change the background color of the login card:
```
.login-content .card {
  background-color: #3d3d3d;
}
```
