### ISSUE TITLE
Streamer/DJ Account Ports

### ISSUE THREAD

**Issue by kbysfm** [AzuraCast/AzuraCast#365]
If I edit the port for a particular station I've noticed that the streamer/dj connection information port does not reflect the change. Would it be possible to edit streamer account ports down the road?

**Comment by SlvrEagle23** [comment]
@kbysfm I could swear I added that already, actually. After seeing this ticket, I went and checked, and sure enough I didn't.

Will flag as an enhancement and get it in promptly.

**Comment by kbysfm** [comment]
@SlvrEagle23 you're the best!

**Comment by SlvrEagle23** [comment]
@kbysfm Both the DJ/streamer port and internal telnet port (used for relaying song requests and skipping songs) are now user-configurable. This makes all ports associated with a typical station user-manageable as needed.

**Comment by kbysfm** [comment]
thanks man!
