### ISSUE TITLE
location of website files - question

### ISSUE THREAD

**Issue by gosntvrdi** [AzuraCast/AzuraCast#3650]
I am trying to find location where all the web files have ben stored, there doesn't seem a volume dedicated to it. When I exec into container azuracast_web, I can see the www files, but can't find them anywhere in docker volumes.

![image](https://user-images.githubusercontent.com/39313008/104118815-03a8e980-532c-11eb-88b2-c5ade963a2ff.png)

**Comment by Vaalyn** [comment]
The application code of AzuraCast (the PHP files and such from the web container) are not persistently saved to a volume since they are part of the Docker image.

When modifying those files in the running container those changes will be lost on the next restart of the container.
