### ISSUE TITLE
DJ Authentication (and other Internal API calls) not working - Cannot check permission with no user set

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#3653]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #cca4592 (2021-01-11 13:09) • Docker • PHP 7.4 

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
In the application log, a new error `Cannot check permission with no user set`. 

**To Reproduce**
Run the latest update on the rolling release to https://github.com/AzuraCast/AzuraCast/commit/cca4592da03ec1a79a7af24cb06dcd53747a4bba and view the application log, the docker log does not reveal the error. 
**Expected behavior**
This error to not occur or for it to find the right permissions.  
**Relevant Logs**
```
[2021-01-11T15:31:23.980113+00:00] AzuraCast.ERROR: Cannot check permission with no user set. {"file":"/var/azuracast/www/src/Acl.php","line":136,"code":0} []
```
**Screenshots**
N/A 

**Device(s):**
Edge, latest, Desktop. 
**Additional context**
The system in question only has one service installed (AzuraCast) and only one user `root` (Not including the AzuraCast user)

**Comment by smilingpeanut** [comment]
I'm seeing the same error after updating just now. In addition, my encoder cannot connect to AzuraCast.

**Comment by smilingpeanut** [comment]
Paging @SlvrEagle23

**Comment by SC2Mitch** [comment]
Please dont ping developers, they notified of bug reports regardless, pinging does not help, be patient.
