### ISSUE TITLE
AlbumArt Missing

### ISSUE THREAD

**Issue by jdrodriguez** [AzuraCast/AzuraCast#3654]
I just updated to the latest version and suddenly the album arts are not showing up. Any recommendations?

**Comment by SlvrEagle23** [comment]
@jdrodriguez Can you be more specific? Is album art just not working at all? Does it show up in the Media Manager for the files, but not on public pages when the same files are playing? We need more information to be able to diagnose this problem.

**Comment by SlvrEagle23** [comment]
Closing as a duplicate of #3652.

**Comment by jdrodriguez** [comment]
The latest update fixed the issue. Thanks.
