### ISSUE TITLE
After upgrade DJ Streamers cannot connect

### ISSUE THREAD

**Issue by dinosd** [AzuraCast/AzuraCast#3658]
Although credentials and connection parameters are correct I get the following message in Liquidsoap log:

 AzuraCast Feedback Response: Error: Cannot check permission with no user set. on /var/azuracast/www/src/Acl.php L136

**Comment by smilingpeanut** [comment]
Duplicate of #3653.

**Comment by Vaalyn** [comment]
Closing as duplicate
