### ISSUE TITLE
Liquidsoap encountered an error, after update

### ISSUE THREAD

**Issue by istahilagi** [AzuraCast/AzuraCast#3662]
Please help me, 
Liquidsoap encountered an error, after update

2021/01/12 09:10:28 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/9/media/IMTAQ/11_doa_khatam_al_qur_an_mix_2_mnt.mp3".
2021/01/12 09:10:38 [lang:3] AzuraCast Live Disconnected Response: 
2021/01/12 09:10:38 [harbor:3] Removing mountpoint '/' on port 8095
2021/01/12 09:10:38 [harbor:3] Nothing more on port 8095: closing sockets.
At line 27, char 40:
Error 3: Syntax error!
At line 27, char 40:
Error 3: Syntax error!
At line 27, char 40:
Error 3: Syntax error!
At line 27, char 40:
Error 3: Syntax error!
At line 27, char 40:
Error 3: Syntax error!
At line 27, char 40:
Error 3: Syntax error!
At line 27, char 40:

**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #007ce2e (2021-01-12 3:21)

**Host Operating System**
Ubuntu 16.04,

**Describe the bug**
Liquidsoap encountered an error, after update

**Comment by Vaalyn** [comment]
Have you tried manually restarting your station via `Utilities` -> `Restart Broadcasting`?

If you've tried that already please post your `Liquidsoap Configuration` from `Utilities` -> `Log Viewer`

**Comment by beefour** [comment]
Check the config and look for line 23, it should define the default playlist, e.g. playlist__default_...

Check if there are any special characters in the name, specifically if the default playlist has brackets.

@Vaalyn, just had this issue, removed brackets from the playlist name and it worked, should the playlist name be quoted or has something changed in LS?

**Comment by istahilagi** [comment]
> Check the config and look for line 23, it should define the default playlist, e.g. playlist__default_...
> 
> Check if there are any special characters in the name, specifically if the default playlist has brackets.
> 
> @Vaalyn, just had this issue, removed brackets from the playlist name and it worked, should the playlist name be quoted or has something changed in LS?
> 
> playlist__default_(dont_delete_or_disable_this) = playlist(
> ->
> playlist__default___dont_delete_or_disable_this = playlist(

okkey, thanks.. this is work on my problem
