### ISSUE TITLE
When more than 1000 listeners are connected with Shoutcast

### ISSUE THREAD

**Issue by alaca33** [AzuraCast/AzuraCast#3663]
When there are more than 1000 listeners connected to Shoutcast, it gives an error nginx. What setting need to be made on the server to increase Shoutcast listener capacity?

**Comment by DefectivenessYT** [comment]
I'm going to assume you're running in docker for this. This will be an issue where you are hitting the connection limit values in the azuracast web radio proxy (/radio/8000)


Make a new file called docker-compose.override.yml, put this in here but do not restart quite yet.
`
version: '2.2'

services:
  web:
    volumes:
     - /var/azuracast/nginx.conf:/etc/nginx/nginx.conf:ro
`

Then, run this command to copy the nginx config from the docker container to the main filesystem.

`docker cp azuracast_web:/etc/nginx/nginx.conf /var/azuracast/nginx.conf`


Then, edit this nginx.conf. 
Set this in the events tab, so it can accept more than one connection at once, and a limit of 65000 (near the upper bounds)
`
events {
        worker_connections 65000;
        multi_accept on;
}

`

Also, outside of the events tab, put `worker_rlimit_nofile 65000;`. This allows it to read a file from disk more than the basic connections. I'm not too sure if this affects the AzuraCast suite in particular.


Then, run `docker-compose down` and then restart it with `docker-compose up -d`

**Comment by YosefAdPro** [comment]
@DefectivenessYT I'm having the same problem.
I tried your suggestion and added at the beginning of the file /var/azuracast/nginx.conf:

```
worker_processes 8;
worker_rlimit_nofile 65000;

events {
        worker_connections 65000;
        multi_accept on;
}
```

And now I get in all pages of AzuraCast :502 Bad Gateway

**"no live upstreams while connecting to upstream"**

```2021/01/18 11:53:18 [error] 106#106: *2830 no live upstreams while connecting to upstream, client: 109...., server: azuracast.local, request: "GET /api/live/nowplaying/test?last_event_id=1610970513%3A0 HTTP/1.1", upstream: "http://azuracast.local/api/live/nowplaying/test?last_event_id=1610970513%3A0", host: ".....com"```

**Comment by DefectivenessYT** [comment]
The worker processes value may already be defined in the AzuraCast config. (it might be worker_processes auto;) already defined

**Comment by DefectivenessYT** [comment]
The 502 will be the nginx server failing to start ^

**Comment by Vaalyn** [comment]
Closing this to consolidate with #3702 please follow that issue for further updates regarding this problem.
