### ISSUE TITLE
Running Song Playback Timeline export CSV results in HTTP Error 500

### ISSUE THREAD

**Issue by AaronUnmuted** [AzuraCast/AzuraCast#3664]
**Using Docker installation method**
Yes

**AzuraCast version**
 v0.11.2 Stable

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
When attempting to export a CSV file for the Song Playback Timeline, regardless of the timeframe selected, this results in an instant HTTP Error 500. Other reports export fine. 

**Expected behavior**
CSV file should begin to download.

**Comment by SC2Mitch** [comment]
I'm unable to replicate this issue on Rolling Release #03b79d9, all downloads appear to work fine for me, any error logs within Docker? 

It should be like this

`nginx_proxy_1              | nginx.1    | DOMAIN.COM IP - - [12/Jan/2021:16:35:01 +0000] "GET /api/station/54/history?format=csv HTTP/2.0" 200 45583 "https://loca.host/station/54/reports/timeline" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75"`

**Comment by AaronUnmuted** [comment]
> I'm unable to replicate this issue on Rolling Release #03b79d9, all downloads appear to work fine for me, any error logs within Docker?
> 
> It should be like this
> 
> `nginx_proxy_1 | nginx.1 | DOMAIN.COM IP - - [12/Jan/2021:16:35:01 +0000] "GET /api/station/54/history?format=csv HTTP/2.0" 200 45583 "https://loca.host/station/54/reports/timeline" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75"`

The following error is shown:

`[error] 53#53: *1822 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 1098907648 bytes exhausted (tried to allocate 147456 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 115" while reading response`

Our PHP Memory Limit in azuracast.env seems sufficient and so unsure as to why this could be happening?

**Comment by Vaalyn** [comment]
> Our PHP Memory Limit in azuracast.env seems sufficient and so unsure as to why this could be happening?

Looking at the the error message it's definitely not enough for the export you are trying to do.

In general this CSV export is very optimized in terms of memory usage so the bigger the time range you selected the more SongHistory objects are loaded into memory when the CSV is generated.

From looking at my own station I'm able to export a 3 month time range with the default settings when I select 4 months then I'm also getting an "Allowed memory size ... exhausted" error.

What time range are you trying to export?

**Comment by SlvrEagle23** [comment]
This should be significantly improved (and likely completely resolved) as of the latest update, which runs the timeline export process through our newer batch processing tools which automatically flush and clear the memory every few rows, which will allow for a _much_ larger result set without any problems.

**Comment by AaronUnmuted** [comment]
Regrettfully, this issue is still present, despite updating to the latest Stable release (v0.12). More specifically, we are attempting to export the Song Playback Timeline. This succeeds when trying to view Today, Yesterday reports, but Last 7 Days onwards does not work and does not load any data at all - on any accounts. 

This only happens on this single server running AzuraCast - we have a number of dedicated servers running AzuraCast whereby this problem is not present. Checking logs does not appear to produce any helpful information.

**Comment by SlvrEagle23** [comment]
@AaronUnmuted I would check the `azuracast.env` file and make sure you're assigning enough RAM to each PHP process, as it's likely that this is where you're running into issues. Even with the latest improvements, if you have a big enough instance with enough songs, that report can still run out of memory just on account of the sheer volume it's having to deal with, but it should be far less likely with the optimizations.

**Comment by AaronUnmuted** [comment]
@SlvrEagle23 Thanks for taking a look, this has transpired to be a bit more of a complicated issue than first though. What triggered me to investigate further was that on this particular server, the Now Playing Data task and 1 Hour Sync tasks had not ran in a long time (upwards of a month). When attempting to run these tasks from Admin Debug, the log would remain blank and nothing would show. I decided to compare this server to another server running AzuraCast which is the same specification and has roughly the same number of stations, thus resource usage should be very similar. When comparing the azuracast.env values, I noted that the problem server may have two AzuraCast containers. 

There is an azuracast.env file in /var/azuracast - as I would expect to find. 

However, there is also an azuracast.env file (plus the other docker files) in the root folder. This is not the same for our other AzuraCast servers.

Could this be causing the issue, and how would we go about resolving potentially conflicting containers that are presumably causing these problems? I'm not overly familiar or confident with Docker and so don't just want to remove these files in case this ends in disaster! Appreciate this isn't an issue with AzuraCast and more than likely a server administration task gone-wrong.
