### ISSUE TITLE
Issue with database

### ISSUE THREAD

**Issue by DefectivenessYT** [AzuraCast/AzuraCast#3665]
**Using Docker installation method**
yes

**AzuraCast version**
latest stable

**Host Operating System**
Ubuntu

**Describe the bug**

502 when visiting web panel, database issue in logs, i've tried to start the database first, and then start the whole stack a bit later, but to no avail

`2021-01-12 12:56:19 20 [Warning] Aborted connection 20 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.5' (This connection closed normally without authentication)`

**Comment by Vaalyn** [comment]
Please also look into the output of `docker-compose logs web` and maybe also post a bit more logs from the mariadb container too. This warning alone does not give us any hints as to what's happening on your installation.

**Comment by DefectivenessYT** [comment]
reinstalled and it started working, i have no idea why i didnt do that before but thanks for responding :)
