### ISSUE TITLE
Unable to connect live with DJ/Streamer Account

### ISSUE THREAD

**Issue by AaronUnmuted** [AzuraCast/AzuraCast#3666]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.11.2 Stable

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
We are using AzuraCast to run an Icecast server with Liquidsoap. We have created a DJ/Streamer account and have restarted broadcasting for the changes to take effect. However, we're unable to connect live with any live encoding software such as BUTT. There is absolutely nothing shown in the logs to suggest the connection is even reaching Liquidsoap. BUTT simply displays "Connecting..." and AzuraCast continues to play the Auto DJ playlist that has been setup. There is no custom Liquidsoap configuration.

We are using a dedicated server with Proxmox installed to create several smaller Ubuntu VM's that run AzuraCast. Other installations seem to be behaving normally. 

Any help would be hugely appreciated. Thanks in advance. 

**Expected behavior**
Live encoder should connect and encode audio to the server.

**Relevant Logs**
From the Icecast Error Log: 

''[2021-01-13  11:27:57] WARN xml/parsing skipping element "stream-description" parsing "mount" at line 27
[2021-01-13  11:27:57] WARN slave/slave_startup process has 65536 max file descriptor limit''

**Comment by AaronUnmuted** [comment]
Furthermore, we have recreated the Station in AzuraCast and have also attempted to change the DJ/Streamer port, to no avail.

**Comment by SC2Mitch** [comment]
When you attempt to connect, can you review the liquidsoap logs and try and search under `DJ connection` or something like that, it'll give you more details in there. Along with this Docker related logs might be helpful.

**Comment by AaronUnmuted** [comment]
> When you attempt to connect, can you review the liquidsoap logs and try and search under `DJ connection` or something like that, it'll give you more details in there. Along with this Docker related logs might be helpful.

Unfortunately absolutely nothing shows in the Liquidsoap logs - nothing that even suggests that a DJ connection is attempting to take place. Also nothing at all in the Docker logs.

**Comment by Vaalyn** [comment]
Are you using CloudFlare for your domain?

If you are using CloudFlare see this information on our website about DJ connections and CloudFlare: https://www.azuracast.com/extending/cloudflare.html#incoming-dj-connections

**Comment by AaronUnmuted** [comment]
> Are you using CloudFlare for your domain?
> 
> If you are using CloudFlare see this information on our website about DJ connections and CloudFlare: https://www.azuracast.com/extending/cloudflare.html#incoming-dj-connections

We are using CloudFlare but this is set to DNS only, regardless, using the IP rather than the hostname also fails to establish a connection unfortunately.

**Comment by Vaalyn** [comment]
If connecting directly via the IP is not working and you are not even seeing an authentication attempt in the Liquidsoap logs then this would indicate that for some reason the dj port for your station is not reachable.

If you can see the dj port of your station in the output of `sudo netstat -tunlp` then this would indicate something with your network blocking the connection from the PC to the servers dj port.

**Comment by AaronUnmuted** [comment]
Managed to fix this - very simple issue. The station was using ports outside of the port range allowed by default (8500+). Not sure why I didn't think of this before. Adjusted & fixed. Thanks for your suggestions!

**Comment by folkperu** [comment]
> Se las arregló para arreglar esto - problema muy simple. La estación estaba usando puertos fuera del rango de puertos permitido por defecto (8500+). No estoy seguro de por qué no pensé en esto antes. Ajustado y fijo. ¡Gracias por tus sugerencias!

hello can you help me please I have the same problem I can't broadcast live with azuracast tell me how you solved it this is my email write me please: contacto@radiofolkperu.com

**Comment by rfolkperu** [comment]
Hello, does anyone know why the music of my Azuracast autodj pauses, cuts, intermittently and goes to the next song? my email write me please: [contacto@radiofolkperu.com](mailto:contacto@radiofolkperu.com)

**Comment by YanikOberheid** [comment]
I have the same problem and dont know if its worth it to reopen a new ticket for this. But is there any solution available?
