### ISSUE TITLE
Problems with mp4 files

### ISSUE THREAD

**Issue by radioutopia** [AzuraCast/AzuraCast#3668]
Hello
This version doesn´t accept mp4 files?
GIves an error, it says, file not processed... 

Thanks

My Azura Cast is Powered by AzuraCast • v0.11.2 Stable • Docker • PHP 7.4

**Using Docker installation method**

**AzuraCast version**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
You'll need to update to the rolling-release version. We've added the mp4 MIME type in a commit that is not yet included in a stable release.

See https://www.azuracast.com/administration/system/release-channels.html#switching-release-channels for how to change your release channel.

**Comment by radioutopia** [comment]
thanks

**Comment by Vaalyn** [comment]
Closing as resolved
