### ISSUE TITLE
There are still translation entries that have not yet been added to the .po file

### ISSUE THREAD

**Issue by dpy013** [AzuraCast/AzuraCast#3669]
**Host Operating System**

none
**Describe the bug**

There are still some translation entries that have not yet been added to the .po file
Pagination
Go to page 1 
(Click to sort Ascending)
(Click to sort Ascending)
Press Start
Jack Slicer
Pagination

**To Reproduce**

**Expected behavior**

Incomplete translation
**Relevant Logs**

none
**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 
windows10-2004
**Additional context**

 testingscreen reader NVDA
thanks

**Comment by dingpengyu** [comment]
Also found an entry that was not in .po.

18 Listeners
2020-12-31
33 Listeners
