### ISSUE TITLE
Switching from "Rolling Release" to "Stable"

### ISSUE THREAD

**Issue by drno88** [AzuraCast/AzuraCast#3677]
Good day. Please tell me how to switch the installation to the mode "Stable".
To update (tidy up) I used this instruction -- https://github.com/AzuraCast/AzuraCast/issues/3507#issuecomment-739366556-- . Now showing  "Rolling Release"...
Ubuntu 16.04, Ansible Install

**Comment by SlvrEagle23** [comment]
@drno88 You can learn more about our AzuraCast release channels here, along with instructions on when and how to switch:

https://www.azuracast.com/administration/system/release-channels.html

**Comment by krono86** [comment]
@SlvrEagle23 The link doesn't report how to switch between channels on Ansible installation.

**Comment by SlvrEagle23** [comment]
Documentation has been added for Ansible installs.
