### ISSUE TITLE
Song restarts (shuffle)

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#3682]
**Using Docker installation method**
Yes.

**AzuraCast version**
Rolling Release #664b0dc (2021-01-15 0:56)

**Host Operating System**
Debian 9

**Describe the bug**
The error occurs rather irregularly but still frequently. At some point a song simply repeats itself after it has already been played.
I have already followed the instructions (https://github.com/AzuraCast/AzuraCast/issues/1285) and changed or adjusted everything. All playlists are on shuffle, all stations that have only one playlist have a weight of 25 and there are no duplicates.
The repeat avoidance period is set to 180 minutes and the station queue is set to 7. I don't use any advanced features, so AzuraCast would normally have free rein to handle everything on its own.

**Relevant Logs**
```
2021/01/16 19:27:21 [lang:3] AzuraCast Feedback Response: OK

2021/01/16 19:30:35 [lang:3] AzuraCast Raw Response: annotate:title="START_AD_BREAK",artist="START_AD_BREAK",duration="0.97",song_id="586c1559fda5ac5d5a94dbaca8e863f6",media_id="787",liq_amplify="0.00dB",playlist_id="31":/var/azuracast/stations/STATION/media/start_ad_break.mp3
2021/01/16 19:30:35 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/STATION/media/start_ad_break.mp3".
2021/01/16 19:30:35 [lang:3] AzuraCast Raw Response: annotate:title="Don't Start Now (Andy Jarvis Remix)",artist="Dua Lipa",duration="143.49",song_id="e2e1f788674b0943fb434980d2dc7183",media_id="543",liq_amplify="0.00dB",playlist_id="28":/var/azuracast/stations/STATION/media/dance/dua_lipa_-_don_t_start_now_-28andy_jarvis_remix-29.mp3
2021/01/16 19:30:35 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/STATION/media/dance/dua_lipa_-_don_t_start_now_-28andy_jarvis_remix-29.mp3".
2021/01/16 19:31:14 [STATION_next_song:3] Prepared "/var/azuracast/stations/STATION/media/start_ad_break.mp3" (RID 3).
2021/01/16 19:31:14 [STATION_next_song:3] Prepared "/var/azuracast/stations/STATION/media/dance/dua_lipa_-_don_t_start_now_-28andy_jarvis_remix-29.mp3" (RID 5).
2021/01/16 19:31:14 [cross_7781:3] Analysis: -25.180764dB / -95.143065dB (4.98s / 0.94s)
2021/01/16 19:31:14 [crossfade:3] No transition: using default.
2021/01/16 19:31:19 [lang:3] AzuraCast Feedback Response: OK
2021/01/16 19:31:19 [cross_7787:3] Analysis: -25.180764dB / -35.274962dB (4.46s / 4.46s)
2021/01/16 19:31:19 [crossfade:3] No transition: using default.
2021/01/16 19:31:19 [lang:3] AzuraCast Feedback Response: OK
2021/01/16 19:31:30 [lang:3] AzuraCast Feedback Response: OK
2021/01/16 19:31:31 [lang:3] AzuraCast Feedback Response: OK

2021/01/16 19:32:59 [lang:3] AzuraCast Raw Response: annotate:title="Kids (feat. MKLA)",artist="KSHMR & Stefy De Cicco",duration="244.09",song_id="77b5b842cc274aa12515d0ca271e406d",media_id="567",liq_amplify="0.00dB",playlist_id="28":/var/azuracast/stations/STATION/media/dance/kshmr_a_stefy_de_cicco_-_kids_-28feat._mkla-29.mp3
2021/01/16 19:32:59 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/STATION/media/dance/kshmr_a_stefy_de_cicco_-_kids_-28feat._mkla-29.mp3".
2021/01/16 19:33:38 [STATION_next_song:3] Prepared "/var/azuracast/stations/STATION/media/dance/kshmr_a_stefy_de_cicco_-_kids_-28feat._mkla-29.mp3" (RID 12).
2021/01/16 19:33:38 [cross_7781:3] Analysis: -50.026588dB / -15.919349dB (4.98s / 5.02s)
2021/01/16 19:33:38 [crossfade:3] new >= old + margin, old <= medium and new <= high.
2021/01/16 19:33:38 [crossfade:3] Do not fade if it's already very low.
2021/01/16 19:33:38 [crossfade:3] Transition: crossed, no fade.
2021/01/16 19:33:43 [lang:3] AzuraCast Feedback Response: OK

2021/01/16 19:36:58 [lang:3] AzuraCast Raw Response: annotate:title="Kids (feat. MKLA)",artist="KSHMR & Stefy De Cicco",duration="244.09",song_id="77b5b842cc274aa12515d0ca271e406d",media_id="567",liq_amplify="0.00dB",playlist_id="28":/var/azuracast/stations/STATION/media/dance/kshmr_a_stefy_de_cicco_-_kids_-28feat._mkla-29.mp3
2021/01/16 19:36:58 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/STATION/media/dance/kshmr_a_stefy_de_cicco_-_kids_-28feat._mkla-29.mp3".
2021/01/16 19:37:37 [STATION_next_song:3] Prepared "/var/azuracast/stations/STATION/media/dance/kshmr_a_stefy_de_cicco_-_kids_-28feat._mkla-29.mp3" (RID 7).
2021/01/16 19:37:37 [cross_7781:3] Analysis: -58.916816dB / -15.919081dB (4.98s / 5.02s)
2021/01/16 19:37:37 [crossfade:3] new >= old + margin, old <= medium and new <= high.
2021/01/16 19:37:37 [crossfade:3] Do not fade if it's already very low.
2021/01/16 19:37:37 [crossfade:3] Transition: crossed, no fade.
2021/01/16 19:37:42 [lang:3] AzuraCast Feedback Response: OK

2021/01/16 19:40:57 [lang:3] AzuraCast Raw Response: annotate:title="START_AD_BREAK",artist="START_AD_BREAK",duration="0.97",song_id="586c1559fda5ac5d5a94dbaca8e863f6",media_id="787",liq_amplify="0.00dB",playlist_id="31":/var/azuracast/stations/STATION/media/start_ad_break.mp3
2021/01/16 19:40:57 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/STATION/media/start_ad_break.mp3".
2021/01/16 19:40:58 [lang:3] AzuraCast Raw Response: annotate:title="I Miss U",artist="Jax Jones",duration="298.11",song_id="ba2cf264ca98ef2717b96f0ae50826fd",media_id="556",liq_amplify="0.00dB",playlist_id="28":/var/azuracast/stations/STATION/media/dance/jax_jones_-_i_miss_u.mp3
2021/01/16 19:40:58 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/STATION/media/dance/jax_jones_-_i_miss_u.mp3".
```

**Screenshots**
![2x Same Song](https://user-images.githubusercontent.com/42640247/104820338-6884a800-5834-11eb-9e50-0e403f432362.jpg)

**Comment by Abqehebter** [comment]
![image](https://user-images.githubusercontent.com/42640247/106452499-43c13f00-6488-11eb-975f-48427a4dd288.png)

After a complete reinstall and some improvements still the same.

**Comment by Abqehebter** [comment]
@Vaalyn Sorry for the marking but I sit here meanwhile felt from morning to evening to analyze the problem. I have 3 stations with a playlist length of minimum 100 songs set to "shuffle", the other 6 run via the "random" mode.
For the 3 stations with shuffle, I noticed the error irregularly one or two times a day, which can be quite fatal for a live operation.

<details>
    <summary>Liquidsoap Log Station 2</summary>
    
```log
2021/02/02 02:33:50 [lang:3] AzuraCast Raw Response: annotate:title="Alien",artist="Dennis Lloyd",duration="138.68",song_id="d6a138e53d380a3a5fa57d3601490c74",media_id="458",liq_amplify="0.00dB",playlist_id="2":/var/azuracast/stations/station2/media/playlist/alien.mp3
2021/02/02 02:33:50 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/station2/media/playlist/alien.mp3".
2021/02/02 02:34:30 [station2_next_song:3] Prepared "/var/azuracast/stations/station2/media/playlist/alien.mp3" (RID 2).
2021/02/02 02:34:30 [cross_38743:3] Analysis: -74.761395dB / -22.619768dB (4.45s / 4.47s)
2021/02/02 02:34:30 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2021/02/02 02:34:30 [lang:3] AzuraCast Feedback Response: OK
2021/02/02 02:36:05 [lang:3] AzuraCast Raw Response: annotate:title="Alien",artist="Dennis Lloyd",duration="138.68",song_id="d6a138e53d380a3a5fa57d3601490c74",media_id="458",liq_amplify="0.00dB",playlist_id="2":/var/azuracast/stations/station2/media/playlist/alien.mp3
2021/02/02 02:36:05 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/station2/media/playlist/alien.mp3".
2021/02/02 02:36:44 [station2_next_song:3] Prepared "/var/azuracast/stations/station2/media/playlist/alien.mp3" (RID 27).
2021/02/02 02:36:45 [cross_38743:3] Analysis: -82.013979dB / -22.628285dB (4.46s / 4.46s)
2021/02/02 02:36:45 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2021/02/02 02:36:45 [lang:3] AzuraCast Feedback Response: OK
```
</details>

<details>
    <summary>Liquidsoap Log Station 3</summary>
    
```log
2021/02/02 19:55:26 [lang:3] AzuraCast Raw Response: annotate:title="Back and Forth",artist="MK x Jonas Blue x Becky Hill",duration="287.11",song_id="8443c40ebb443827443db79937f59a61",media_id="396",liq_amplify="0.00dB",playlist_id="3":/var/azuracast/stations/station3/media/playlist/mk_x_jonas_blue_x_becky_hill_-_back_and_forth.mp3
2021/02/02 19:55:26 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/station3/media/playlist/mk_x_jonas_blue_x_becky_hill_-_back_and_forth.mp3".
2021/02/02 19:56:05 [station3_next_song:3] Prepared "/var/azuracast/stations/station3/media/playlist/mk_x_jonas_blue_x_becky_hill_-_back_and_forth.mp3" (RID 1).
2021/02/02 19:56:05 [cross_38743:3] Analysis: -34.140890dB / -14.050750dB (5.97s / 5.99s)
2021/02/02 19:56:05 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2021/02/02 19:56:07 [lang:3] AzuraCast Feedback Response: OK
2021/02/02 20:00:07 [lang:3] AzuraCast Raw Response: annotate:title="Back and Forth",artist="MK x Jonas Blue x Becky Hill",duration="17.48",song_id="2d66938f60f826abe266ae1dcbf8448e",liq_amplify="0.00dB",jingle_mode="true":/var/azuracast/stations/station3/media/jingle.mp3
2021/02/02 20:00:07 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/station3/media/jingle.mp3".
2021/02/02 20:00:24 [lang:3] AzuraCast Raw Response: annotate:title="The Business, Pt. II",artist="Tiësto & Ty Dolla $ign",duration="164.18",song_id="0f08a1641b4a4f1908c49b2d10534a50",media_id="437",liq_amplify="0.00dB",playlist_id="3":/var/azuracast/stations/station3/media/playlist/tiësto__ty_dolla_ign_-_the_business,_pt._ii.mp3
2021/02/02 20:00:24 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/station3/media/playlist/tie\204\136sto__ty_dolla_ign_-_the_business,_pt._ii.mp3".
2021/02/02 20:00:46 [station3_next_song:3] Prepared "/var/azuracast/stations/station3/media/jingle.mp3" (RID 2).
2021/02/02 20:00:46 [cross_38743:3] Analysis: -42.250465dB / -15.721533dB (5.97s / 5.99s)
2021/02/02 20:00:46 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2021/02/02 20:00:47 [lang:3] AzuraCast Feedback Response: OK
```
</details>

On the one station with shuffle, I currently experience that at least very often after the 0 second commercial break, it tries to play the last played track again, but it then chooses another one a few seconds later.

I don't know exactly where the error should be with me in the installation, I have reinstalled the entire server (Now Ubuntu 20.04 instead of Debian 9), AzuraCast completely set up again on the empty new server and with the stable version 0.12 (Docker) kept live.

As far as I analyze it correctly I don't have the problem with the "random" mode with the playlists, that I would observe from now on however then.
(Small question about this: The random mode also observes the "period for repetition avoidance" or?)

I hope we can do something, I'm really a bit helpless desperate...

**Comment by SlvrEagle23** [comment]
I've added some safety checks to our AutoDJ code that will do two things:
 - If the current song playing is the exact same as the one that we're about to send to play, we'll delete that duplicate track and send the next one instead, and
 - If the same track gets queued one or more times, for whatever reason, the duplicates will be deleted.

There is a more in-depth effort involved in determining how the AutoDJ encounters this problem from time to time, but the effort of these fixes is to make it a non-issue by preventing listeners from ever hearing the same track twice in a row.

These updates are already live in the latest Rolling Release version. Please test it and let me know if it helps.

**Comment by Abqehebter** [comment]
At the current time I could not find any duplicates within the hours, but I just noticed that the queue clock is now going a bit crazy. Is this possibly because it rebuilds the queue, but does not observe the time?
![image](https://user-images.githubusercontent.com/42640247/106858453-f9c39d80-66c1-11eb-9952-d480e8850a51.png)

**Comment by Abqehebter** [comment]
@SlvrEagle23 At the current time I could not find any duplicates within the hours, but I just noticed that the queue clock is now going a bit crazy. Is this possibly because it rebuilds the queue, but does not observe the time?
![image](https://user-images.githubusercontent.com/42640247/106858855-8e2e0000-66c2-11eb-8ae7-0e28366f1498.png)

**Comment by hecgua** [comment]
The solution worked for me. Thank you @SlvrEagle23!

**Comment by Abqehebter** [comment]
However, I also note a lot of artist repeats even though the duplicate avoidance checkbox is on, for all playlists:
![image](https://user-images.githubusercontent.com/42640247/106958339-85c4dc00-6739-11eb-845a-f70174fe47be.png)
![image](https://user-images.githubusercontent.com/42640247/106958556-d3414900-6739-11eb-9f92-07465c870a68.png)
![image](https://user-images.githubusercontent.com/42640247/106958812-26b39700-673a-11eb-92d0-66d3e7fbdf6d.png)
![image](https://user-images.githubusercontent.com/42640247/106959002-65e1e800-673a-11eb-9144-99269e9059b9.png)

and so on...

**Comment by SlvrEagle23** [comment]
@Abqehebter This shouldn't be happening if our AutoDJ can prevent it from happening, though if we can't avoid an artist overlap, we will still do that in some cases. Our code already checks for separators like `&` and `,` to delineate distinct artists, so that shouldn't be an issue in this case.

In any event, that's a separate issue from the one being reported here, which seems to be resolved by the latest code, so I'll be closing this issue as completed; if you'd like to create a new issue, feel free to do so.
