### ISSUE TITLE
Proposed HLS Implementation

### ISSUE THREAD

**Issue by SlvrEagle23** [AzuraCast/AzuraCast#3685]
This weekend's Liquidshop has me excited about rolling out some increasingly popular features to mainstream users via AzuraCast, and one of the most heavily requested ones is support for HLS (often referred to as M3U8 after its main playlist manifest file).

### Proposed Implementation

 - Add a new `is_hls` flag to `Entity\StationMount` that will allow each of the various HLS bitrates (and/or codecs, if not using AAC as the standard) to be created and managed the same way as regular mount points.
 - Update pages that use mount points to allow creation/management of mount points even without a frontend broadcasting software, as HLS does not need one.
 - Convert the mount point management to a Vue single file component with separation between standard and HLS mount points and custom forms for each.
 - In `App\Radio\Backend\Liquidsoap\ConfigWriter`, check for whether any HLS mount points exist and handle them separately from the main mount/remotes. Using code similar to [this example](https://www.liquidsoap.info/doc-1.4.1/hls_output.html), the various mount points would be aggregated into a single radio stream and written to a temporary directory available only in the `stations` container (for Docker installations).
 - Evaluate a way to distribute the HLS contents while keeping track of listeners actively engaging with the HLS stream, and connect to this service for metrics in the same manner as other mount points.
 - The main outward-facing `nginx` service (the `nginx-proxy` for Docker installations) would have built-in rules for proxying the HLS version of station streams in the same manner that regular streams are proxied, allowing for LetsEncrypt and compatibility with services like CloudFlare.
 - A new web player library would allow the playback of the HLS stream(s) directly inside AzuraCast in the same manner as existing streams are played.

### Missing Solution: Listener Metrics

One thing we're missing in cleanly implementing this is the ability to keep track of listeners who are connected to the HLS streams in the same manner as we do for Icecast/SHOUTcast streams, providing a continuity of our existing statistics services.

One very promising piece of code, [hlswatch](https://github.com/faryon93/hlswatch), offers the ability to take HLS files generated by the `nginx-rtmp` module, serve them to listeners and track active connections. While we would be intending to use Liquidsoap to write the HLS files, the core of this code seems to be designed to just watch a given folder and keep track of the changes to the files in it, which I would generally expect to be compatible with Liquidsoap's HLS implementation as well as any other. The `/stats` REST endpoint it exposes would likely provide all the information we'd need for our purposes.

This code would likely need to be further adopted to allow easier daemonization via Supervisor (or conversely, we could just improve how we write environment variables), but it seems like the closest we're getting to a turnkey solution.

One alternative would be to serve the HLS files through nginx directly and then collect metrics via the [Amplify](https://www.nginx.com/blog/nginx-amplify-custom-dashboards-filters/) plugin, but this requires further research for how viable it would be for this use-case.

### Public Feedback Wanted

HLS is a new frontier for me at least, one that I haven't used in practice in a public radio station, but I understand the underpinnings and core design considerations of it. I want to hear from stations who may have implemented it already, ideally on top of AzuraCast itself, to gain some feedback on whether our approach is missing something, or whether there are better options out there that may meet our metrics requirements.

When implementing this, we absolutely intend to take the same approach as we normally do with AzuraCast, which is to make it as low-effort as possible to implement full HLS support for most stations, with almost zero need to worry about how the pieces glue together and instead a working solution that meets the needs of 95% of moderate-sized stations out there.

**Comment by Vaalyn** [comment]
I like the proposed implementation.

Making the mount point management to a Vue component would probably also make it easier to implement showing some advanced options only for specific AutoDJ Formats to allow more fine tuning of a streams parameters (for example `internal_quality` or `samplerate`).

Regarding statistics, when using the `nginx-rtmp-module` there is an option for it to expose a statistics page: https://github.com/arut/nginx-rtmp-module/wiki/Directives#statistics

When I look at examples on GitHub where this feature was used to built a dashboard for rtmp & hls streams that seems like it exposes what we need (see Viewers column in screenshot): https://github.com/3m1o/nginx-rtmp-monitoring
Here is their [stat.xsl](https://github.com/3m1o/nginx-rtmp-monitoring/blob/master/stat.xsl) file as an example.

**Comment by SlvrEagle23** [comment]
@Vaalyn But do we actually want to use the `nginx-rtmp-module` to serve the HLS site? I'm looking at this implementation, and it looks like we could probably use that statistics service even if nginx itself just serves the static files that Liquidsoap generates, but I'm not sure if that's the case.

I'd definitely want to keep the HLS file generation inside Liquidsoap for maximum customization and flexibility, so basically I'm just looking for rudimentary stats on top of that.

**Comment by Vaalyn** [comment]
I don't exactly know if this module can take pre-generated HLS files and server them. If it does then this could be solution that's not very heavy or invasive. If it is not possible to use the module to serve existing HLS files then this is probably not what we are looking for.

I'm with you there on wanting the generation in LS for the same reasons.

**Comment by mbugeia** [comment]
Hi, I'm probably the first person to ever used HLS with liquidsoap in production (in fact the support was written at my request) and we did implemented HLS stats at my work. Feel free to ask me any question about it here or on the Liquidsoap slack.

Also a related question on HLS stats on my small project : https://github.com/mbugeia/srt2hls/discussions/14#discussioncomment-635172

Some insight on HLS:
- Keep in mind that one of the main advantage of HLS on the server side is the ability to cache content so you probably want to add cache-control headers like here https://github.com/mbugeia/srt2hls/blob/master/nginxhls/stream.conf
- If you want to be compatible with a wide range of client use mpegts encapsulation, not mp4. Also mp3 isn't widely supported and other codec aren't compliant with the RFC.
- If you want to use adaptative bitrate you need to use the same aac profile for all quality (use AAC LC).
- You will need to decide (or let the user decide) the duration of each HLS segment, 4s or 6s works well for audio content, don't go lower than 4s.
- You will need to decide (or let the user decide) the duration of each HLS Playlist, most client will start at the beginning of the playlist. ~30s is a good choice

**Comment by SlvrEagle23** [comment]
HLS support has been implemented in our Rolling Release, thanks in large part to the help and example scripts provided by @mbugeia . Thank you!

**Comment by pimseb** [comment]
Thanks for this great feature !
Where can I change the HLS settings like @mbugeia explained ? I'd like to add more length to the HLS segment, so the radio will not skip while driving. Would it be also possible to add a 32kbps aac+ stream ? The sound is fine and it could cover areas with only EDGE

**Comment by SlvrEagle23** [comment]
@pimseb I've added segment length as a configurable value in the station profile. You can customize the individual streams via the HLS Streams page under Broadcasting.

**Comment by pimseb** [comment]
very nice @SlvrEagle23 ! What about "backBufferLength" ? What's its default value at the moment ?

**Comment by SlvrEagle23** [comment]
@pimseb Right now, the back-buffer I believe is 5 segments and the overhead is also 5 segments. We can also make this configurable if need be...I honestly haven't played with it enough to know the implications of various changes.

**Comment by pimseb** [comment]
I it could be a great improvement to add also these values to the advanced configuration but it's up to you :)
Is there also a way to have artist / title metadata or is it a limitation of the hls streams?

**Comment by Vaalyn** [comment]
> Is there also a way to have artist / title metadata or is it a limitation of the hls streams?

Atm. it's not possible for us I think since timed metadata inside of the MPEG-2 transport stream is not yet implemented in Liquidsoap.

See: https://github.com/savonet/liquidsoap/issues/1487

**Comment by pimseb** [comment]
Thank you for the metadata answer @Vaalyn 

@SlvrEagle23 Concerning the hls segments it appears after some tests that the back buffer segment is 2 blocks and the overhead  segment is 3 blocks. I'd like to tweak a bit more these values especially to increase the overhead blocks. If you could add this configurable value in the next update I could play some more with better playback :)

**Comment by pimseb** [comment]
Thank you for having added the segment configurable option @SlvrEagle23 !
But I'm not sure it's working as it should. The "segments in Playlist" is working but the "overhead segment" is never longer than 2 or 3 segments, even if I enter a bigger value.

On this example my settings are : 
segment length : 10 seconds
segments in playlist : 20
segments overhead : 10
I would expect the stream to start at the middle of the segments (10 before and 10 after, so around 3:20 on the screenshot) but it starts with only 2 overhead segments which is not enough to avoid buffering issues. 
![image](https://user-images.githubusercontent.com/23084628/177649798-046ac98d-9d9e-4c19-8935-b466fa023ec2.png)
