### ISSUE TITLE
Scheduled Time playlist is not working

### ISSUE THREAD

**Issue by rofmvalencia** [AzuraCast/AzuraCast#3688]
To play once per day, set the start and end times to the same value 20:25  If the end time is before the start time, the playlist will play overnight. 20:25 NOT WORKS :(

**Comment by SC2Mitch** [comment]
We need way more information than this to work on, can you please fill out the format and fill in the logs section so we can take a look? Saying it doesn't work isn't helpful.

**Comment by rofmvalencia** [comment]
Hi i wil explain whit my bad English, I try to schedule a playlist whit a single mp3 is a podcast recorded... I make the configuration 

![Screenshot_20210118-223941](https://user-images.githubusercontent.com/67313797/104965091-38790880-59de-11eb-91b1-1ca2f83519c3.jpg)
![Screenshot_20210118-223952](https://user-images.githubusercontent.com/67313797/104965103-40d14380-59de-11eb-9a13-1b771fa22646.jpg)
![Screenshot_20210118-224007](https://user-images.githubusercontent.com/67313797/104965106-4595f780-59de-11eb-885a-244dcd18e1f1.jpg)
![Screenshot_20210118-224023](https://user-images.githubusercontent.com/67313797/104965110-49297e80-59de-11eb-90a2-9b3138586b0d.jpg)



And not starts at the programmed schedule... 
Can you help me whit this?

**Comment by SC2Mitch** [comment]
Turn off advanced settings, they can cause issues with scheduling.

**Comment by rofmvalencia** [comment]
I've tried, still not work... 😔

**Comment by rofmvalencia** [comment]
Wait you say advance settings from the first foto? Or the last one?

**Comment by SC2Mitch** [comment]
From the 'Avanzado' setting, turn them off, they're known to cause issues.

**Comment by YosefAdPro** [comment]
@rofmvalencia You need to restart AutoDJ Service (Liquidsoap) for the changes to take effect.

**Comment by rofmvalencia** [comment]
Ok, i will come back with updates...

**Comment by rofmvalencia** [comment]
Hi, still not start :( i don't know what to do :(((

**Comment by JackCoder21** [comment]
Same problem, does not respect playlists.  (Rolling Release #b6656a3)

**Comment by sidney65** [comment]
@rofmvalencia  :

- In basic info : use once per hour

- in Fuente : use sequential if you have just one podcast to use ; Hide metadata is only if you dont want song title appear on player(like when you play jingle)

- Edit playlist: Start time & end do it the same if you want podcast start à the time set (19h30 at - or + 2 min)

- Don't use avanzado ! is only if you want to use liquidsoap dj and not azuracast dj.
On my station is work but for one file ; when you have more than one in sequential mode , only the first one play .
Hope this one can help you ;-)

**Comment by rofmvalencia** [comment]
@sidney65 Hi works fine whit Jingle mode And Random settings and put the minutes 1 per Hour  settings ! 
![FIX NEWS SETTINGS](https://user-images.githubusercontent.com/67313797/106149741-e4f38100-617a-11eb-9d7c-4c1fe93cb23d.png)
