### ISSUE TITLE
Custom SSL

### ISSUE THREAD

**Issue by huhas12** [AzuraCast/AzuraCast#3689]
Hello just need your help,

Tried to set up my certificates, following the guide https://www.azuracast.com/extending/modifying-docker.html#common-examples

replaced all the necessary by making an override file with the following :

**version: '2.2'

services:
nginx_proxy:
volumes:
- /home/xenia_ath/radio_just4music_live.crt:/etc/nginx/certs/radio.just4music.live.crt:ro
- /home/xenia_ath/radio_just4music_live.key:/etc/nginx/certs/radio.just4music.live.key:ro
stations:
volumes:
- /home/xenia_ath/radio_just4music_live.crt:/etc/nginx/certs/radio.just4music.live.crt:ro
- /home/xenia_ath/radio_just4music_live.key:/etc/nginx/certs/radio.just4music.live.key:ro**

but getting an error message back. Docker installed in google VM

root@radio:/var/azuracast# docker-compose up -d
azuracast_redis_1 is up-to-date
Starting azuracast_stations ...
Starting azuracast_stations ... error
ERROR: for azuracast_stations Cannot start service stations: OCI runtime create failed: container_linux.go:370: st
arting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/home/x
enia_ath/radio_just4music_live.crt" to rootfs at "/var/lib/docker/overlay2/38ddd2b70197ccc58b772ca6e7bd3cdf2ef4dd10
ed55b0dc505a25dc552fd250/merged/etc/nginx/certs/radio.just4music.live.crt" caused: open /var/lib/docker/overlay2/38
ddd2b70197ccc58b772ca6e7bd3cdf2ef4dd10ed55b0dc505a25dc552fd250/merged/etc/nginx/certs/radio.just4music.live.crt: re
ad-only file system: unknown
ERROR: for stations Cannot start service stations: OCI runtime create failed: container_linux.go:370: starting con
tainer process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/home/xenia_ath/r
adio_just4music_live.crt" to rootfs at "/var/lib/docker/overlay2/38ddd2b70197ccc58b772ca6e7bd3cdf2ef4dd10ed55b0dc50
5a25dc552fd250/merged/etc/nginx/certs/radio.just4music.live.crt" caused: open /var/lib/docker/overlay2/38ddd2b70197
ccc58b772ca6e7bd3cdf2ef4dd10ed55b0dc505a25dc552fd250/merged/etc/nginx/certs/radio.just4music.live.crt: read-only fi
le system: unknown
ERROR: Encountered errors while bringing up the project.

**Comment by Vaalyn** [comment]
The `read-only file system: unknown` problem was resolved in a commit in the rolling-release channel. Since there has not been a stable release yet where this fix is included you'll need to update to the rolling release.

**Comment by YosefAdPro** [comment]
@Vaalyn I am having a similar problem.
I have custom ports so I am required to modify the azuracast.conf file as well.

my docker-compose.override.yml file:
```yaml

`version: '2.2'

services:
  web:
    volumes:
     - /var/azuracast/azuracast-nginx.conf:/etc/nginx/conf.d/azuracast.conf:ro

  stations:
    ports:
      - "6060-6062:6060-6062"
      - "8000-8500:8000-8500"
 
```


```

web_1                      | Starting up AzuraCast services...
web_1                      | Services started up and ready!
web_1                      | *** Running /etc/my_init.d/nginx.sh...
web_1                      | 2021/03/09 22:32:44 unable to create open /etc/nginx/conf.d/azuracast.conf: read-only file system
web_1                      | *** /etc/my_init.d/nginx.sh failed with status 1
web_1                      |
web_1                      | *** Killing all processes...
```

I am using the latest rolling version.

**Comment by Vaalyn** [comment]
Closing this issue as resolved since the fix for the `read-only file system` has also been included in the stable releases.
