### ISSUE TITLE
Your installation is currently 5 update(s) behind the latest version.

### ISSUE THREAD

**Issue by JP-FOURNIER** [AzuraCast/AzuraCast#3693]
**PLEASE DO NOT SUBMIT FEATURE REQUESTS THROUGH GITHUB!**

We have a special web site dedicated to submitting and voting on new features for completion.

Submit your feature request at [features.azuracast.com](https://features.azuracast.com/).

**Comment by JP-FOURNIER** [comment]
i do update each day but didnt correct this message

**Comment by JP-FOURNIER** [comment]
Your installation is currently 7 update(s) behind the latest version.
 Rolling Release #686f480 (2021-01-19 5:44) • Docker • PHP 7.4

**Comment by SC2Mitch** [comment]
Have you tried to update? There has been indeed 7 updates since commit #686f480

Commits can be tracked through this: https://github.com/AzuraCast/AzuraCast/commits/master

**Comment by JP-FOURNIER** [comment]
before was named instead of just update .......

**Comment by SC2Mitch** [comment]
Yes this was recently changed.
