### ISSUE TITLE
Auto DJ crossfade time does not accept float input

### ISSUE THREAD

**Issue by PB-SF** [AzuraCast/AzuraCast#3694]
When I try to change the crossfade time to a float (e.g. 3.5 or 3,5) I get the error message "Must be numeric."

![2021-01-20_18h46_57](https://user-images.githubusercontent.com/45131983/105214139-e657f480-5b4f-11eb-9fd9-ca95865a94cd.png)

![2021-01-20_18h26_25](https://user-images.githubusercontent.com/45131983/105214152-e9eb7b80-5b4f-11eb-9367-b300a634aac2.png)

In liquidsoaps crossfade parameters, the times for fade in and fade out are specified separately. It would be great if the times could also be specified separately in the GUI in order to create individual transitions instead of a standard crossfade.

![2021-01-20_18h48_11](https://user-images.githubusercontent.com/45131983/105214313-21f2be80-5b50-11eb-98ce-6b2c3f563049.png)

Many Greetings

**Comment by Abqehebter** [comment]
Strange. It works for me with 3.5
Which AzuraCast version do you currently have?

**Comment by PB-SF** [comment]
Just updated to  Rolling Release #092f4eb (2021-01-20 20:05) Ansible

But it doesn't work after the update either

**Comment by Vaalyn** [comment]
Can confirm that there is a problem when using `3,5` since that value is not converted to a float. With `3.5` it works. I think we should either convert the `3,5` to a float correctly or adjust what values are allowed in those fields.

**Comment by BusterNeece** [comment]
I've kept this one around in case it was something we could do, but apparently the HTML5 `<input type="number">` spec specifically doesn't allow comma-separated decimals. If we wanted to support it, we'd need to specifically work around the standard spec. That's a little surprising to me, given I'd have imagined that the spec would have considered internationalization in its design.

**Comment by BusterNeece** [comment]
Correction...apparently `<input type="number">` _does_ properly localize if the locale you use uses commas as the decimal separator, but it transparently converts the resulting number into a period-separated decimal when submitting the form, which is exactly the functionality we want it to have in this case. I believe our switch to HTML5 numbers has thus fixed this.
