### ISSUE TITLE
Livesource stops with any audio from AutoDJ

### ISSUE THREAD

**Issue by danielrodrigotest** [AzuraCast/AzuraCast#3698]
**Using Docker installation method**
 Yes 

**AzuraCast version**
 Rolling Release #092f4eb (2021-01-20 20:05)

**Host Operating System**
 Ubuntu 20.04

**Describe the bug**
 Azuracast is working fine with AutoDj streams with no live source. However, some days ago live streams with autodj fallback (jingle + songs) started with an unusual behaviour. I checked my internet connection with an optimal upload speed, but the live source stopped after 4 o 6 seconds with the autodj songs. To this, I checked with some codecs like MP2, AAC+, AAC, MP3, OPUS and OGG and those previously mentioned codecs were a totally fail. The problem wasn't resolve with increasing or decreasing the buffer. In fact, the live audio started with some lag for some hours. To finish, I restarted my vps in case of, restarted docker and updated my version in case of, and it was impossible.

Here's the log:

> 2021/01/20 18:30:48 [lang:3] DJ Source disconnected! Current live DJ: rrc
2021/01/20 18:30:48 [lang:3] AzuraCast Live Disconnected Response: true
2021/01/20 18:30:50 [lang:3] Authenticating DJ: rrc
2021/01/20 18:30:50 [lang:3] AzuraCast DJ Auth Response: true
2021/01/20 18:30:50 [decoder:3] Method "OGG" accepted "application/ogg".
2021/01/20 18:30:50 [lang:3] DJ Source connected! Last authenticated DJ: rrc - [("icy-pub", "1"), ("icy-name", "Breakaway One"), ("icy-genre", "Rock'n'roll"), ("icy-url", "http://www.breakaway.one"), ("icy-br", "128"), ("content-type", "application/ogg")]
2021/01/20 18:30:50 [lang:3] AzuraCast Live Connected Response: true
2021/01/20 18:30:50 [radio_riquelme_coquimbo_input_streamer:3] Decoding...
2021/01/20 18:30:51 [lang:3] Authenticating DJ: rrc
2021/01/20 18:30:51 [dummy:3] Source failed (no more tracks) stopping output...
2021/01/20 18:30:51 [radio_riquelme_coquimbo_live_fallback:3] Switch to radio_riquelme_coquimbo_requests_fallback with forgetful transition.
2021/01/20 18:30:51 [lang:3] AzuraCast DJ Auth Response: true
2021/01/20 18:30:53 [radio_riquelme_coquimbo_live_fallback:3] Switch to audio_to_stereo_38759 with transition.
2021/01/20 18:31:00 [dummy:3] Source failed (no more tracks) stopping output...
2021/01/20 18:31:00 [radio_riquelme_coquimbo_live_fallback:3] Switch to radio_riquelme_coquimbo_requests_fallback with forgetful transition.
2021/01/20 18:31:03 [radio_riquelme_coquimbo_live_fallback:3] Switch to audio_to_stereo_38759 with transition.
2021/01/20 18:31:05 [radio_riquelme_coquimbo_live_fallback:3] Switch to radio_riquelme_coquimbo_requests_fallback with forgetful transition.
2021/01/20 18:31:05 [dummy:3] Source failed (no more tracks) stopping output...
2021/01/20 18:31:16 [lang:3] Authenticating DJ: rrc
2021/01/20 18:31:17 [lang:3] AzuraCast DJ Auth Response: true
2021/01/20 18:31:17 [lang:3] Authenticating DJ: rrc
2021/01/20 18:31:18 [lang:3] AzuraCast DJ Auth Response: true
2021/01/20 18:31:20 [lang:3] Authenticating DJ: rrc
2021/01/20 18:31:21 [lang:3] AzuraCast DJ Auth Response: true
2021/01/20 18:31:23 [lang:3] Authenticating DJ: rrc
2021/01/20 18:31:24 [lang:3] AzuraCast DJ Auth Response: true
2021/01/20 18:31:25 [lang:3] Authenticating DJ: rrc
2021/01/20 18:31:26 [lang:3] AzuraCast DJ Auth Response: true
2021/01/20 18:31:27 [lang:3] Authenticating DJ: rrc
2021/01/20 18:31:28 [lang:3] AzuraCast DJ Auth Response: true
2021/01/20 18:31:29 [lang:3] Authenticating DJ: rrc
2021/01/20 18:31:29 [lang:3] AzuraCast DJ Auth Response: true
2021/01/20 18:31:30 [lang:3] Authenticating DJ: rrc
2021/01/20 18:31:31 [lang:3] AzuraCast DJ Auth Response: true
2021/01/20 18:31:32 [lang:3] Authenticating DJ: rrc
2021/01/20 18:31:32 [lang:3] AzuraCast DJ Auth Response: true
2021/01/20 18:31:33 [lang:3] Authenticating DJ: rrc
2021/01/20 18:31:34 [lang:3] AzuraCast DJ Auth Response: true
2021/01/20 18:31:35 [lang:3] Authenticating DJ: rrc
2021/01/20 18:31:35 [lang:3] AzuraCast DJ Auth Response: true
2021/01/20 18:31:36 [radio_riquelme_coquimbo_live_fallback:3] Switch to audio_to_stereo_38759 with transition.
2021/01/20 18:31:36 [lang:3] Authenticating DJ: rrc

**Expected behavior**
 Liquidsoap problem and buffer time 

**Screenshots**

![Screenshot 2021-01-21 at 10 39 58](https://user-images.githubusercontent.com/40525323/105358594-22816880-5bd5-11eb-8fa5-7c179808b3d4.png)
![Screenshot 2021-01-21 at 10 40 26](https://user-images.githubusercontent.com/40525323/105358599-23b29580-5bd5-11eb-9863-3a7ea9c9ebda.png)

**Comment by williambatson** [comment]
Same or similar issue here -  System works with auto autoDJ just fine -   Icecast or Shoutcast, runs flawlessly and uninterrupted   I logged into the station as a live DJ  and after a short time - the source dropped and the connection failed.    Azuracast would not respond unless the VPS was restarted.   Running:  AzuraCast • v0.12 Stable • Docker • PHP 7.4 Ubuntu 20.04
I'm in here looking for answers before updating or looking further.  Very unexcpected behavior from an otherwise very stable install.
