### ISSUE TITLE
Incorrect "next song" name and no play time/duration time.

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#3699]
**Using Docker installation method**
 Yes
**AzuraCast version**
Rolling Release #092f4eb (2021-01-20 20:05)

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
I see strange behavior since the last rolling release:
  
1. Azuracast not playing the correct "next song" , it display correctly the "now playing" song but when the next song is coming up, it's not the song that displayed on the "next song" .
It only works out after 3 songs
2. After rebooting Azuracast,  the first 3 songs are not displaying the play time/duration.

Please take a look on the screenshot:

![1](https://user-images.githubusercontent.com/2701228/105362874-152fa280-5c04-11eb-890f-2f9d86dbb51b.JPG)
![2](https://user-images.githubusercontent.com/2701228/105362885-182a9300-5c04-11eb-9e64-829e2cd4d3fd.JPG)
![3](https://user-images.githubusercontent.com/2701228/105362893-19f45680-5c04-11eb-98be-d03e17d09906.JPG)

Please take a look on the screenshot of "on the air"

**Comment by rolradio** [comment]
Do you use an advanced setting in your playlist?

**Comment by eranwo** [comment]
@rolradio 
No, I don't use the advanced setting

**Comment by SC2Mitch** [comment]
![image](https://user-images.githubusercontent.com/29955942/105619006-fab51f00-5de5-11eb-8200-ac1779038872.png)
I'm struggling to replicate this issue on my Rolling Release.

Any errors show up in the console logs / docker logs?

**Comment by eranwo** [comment]
@SC2Mitch Try restart azuracast to replicate the issue
or just update. 
Please let me know which logs do you need?
Here what i'm getting:
![11](https://user-images.githubusercontent.com/2701228/105626169-da618080-5e36-11eb-9302-66a931ef66b5.JPG)
![12](https://user-images.githubusercontent.com/2701228/105626170-dc2b4400-5e36-11eb-895c-9787c99c04d1.JPG)
![13](https://user-images.githubusercontent.com/2701228/105626172-dd5c7100-5e36-11eb-9948-b1ad0b8c31cb.JPG)
