### ISSUE TITLE
Highcharts Button Bug?

### ISSUE THREAD

**Issue by kbysfm** [AzuraCast/AzuraCast#370]
@SlvrEagle23 looks like a bug after the recent commits - 
![screen shot 2018-01-10 at 9 55 43 am](https://user-images.githubusercontent.com/25082477/34781926-c3730d4a-f5ec-11e7-983d-7bae0912f6d4.png)

**Comment by SlvrEagle23** [comment]
@kbysfm Yep, this one was my mistake...I updated the CDN that Highcharts loads from, and used the wrong URL for the exporting module. It's fixed now.

**Comment by kbysfm** [comment]
@SlvrEagle23 thanks bro
