### ISSUE TITLE
No statistics retrieved from Icecast 2.4.4 (or Icecast KH with HTTP proxy) 

### ISSUE THREAD

**Issue by lramilo** [AzuraCast/AzuraCast#3700]
**Using Docker installation method**

YES

**AzuraCast version**

v0.10.4 Stable • Docker • PHP 7.4

**Host Operating System**

Ubuntu 18.04

**Describe the bug**

We're testing AzuraCast with external relays as we need to handle high audience volumes, and it could not handle statistics well in some cases as Icecast 2.4.4 or when retrieving from Icecast KH with a HTTP/HTTPS proxy on top (like remote relays from other AzuraCast installations)

Case A - Icecast 2.4.4: If we set an external relay running on Icecast 2.4.4, it doesn't retrieve the listener details list and it's showing 0 as the unique listeners count, even when these listeners are really connected to Icecast. Anyway, it shows the total listener counts (not unique) while no unique listeners are counted from other Icecast KH relays. We guess this could be related to AzuraCast not parsing well the XML format of the Icecast 2.4.4 responses.

_Example of case A where the last 3 remote relays from the bottom are Icecast 2.4.4 with 420, 419 and 1 listeners respectively (840 in total) It shows 840 listeners, and 0 unique._
![image](https://user-images.githubusercontent.com/74368492/105417345-3c916a00-5c1a-11eb-8e9b-56e13d06706d.png)

Case B - Icecast 2.4.4 and Icecast KH combined: If there's at least 1 unique listener counted from one of the Icecast KH relays, the total listeners count changes to be the same as the unique listeners count, even when the individual Icecast 2.4.4 relays shows other numbers as total listener counts.

_Example of case B where the last 3 remote relays from the bottom are Icecast 2.4.4 with high amount of listeners, but as the third remote relay from the top (an Icecast KH) has 1 unique listener, the total counts equals the unique listener count._
![image](https://user-images.githubusercontent.com/74368492/105417653-b295d100-5c1a-11eb-934c-12e35643fc0c.png)

_Anyway, on both cases A and B, dashboard statistics seems to always show the total listeners count:_
![image](https://user-images.githubusercontent.com/74368492/105420610-6ef19600-5c1f-11eb-8015-66c31e8bce17.png)
![image](https://user-images.githubusercontent.com/74368492/105420740-aa8c6000-5c1f-11eb-8057-c255ff922f41.png)

Case C - Icecast KH with HTTP/HTTPS proxy on top: Stats could not be grabbed when using an external Icecast KH relay with a HTTP/HTTPS proxy on top (like remote relays from other AzuraCast installations) Even when we are able to set the direct Icecast relay, it's not possible to use this link on the public player as it is HTTP and doesn't play on Google Chrome. Also, as we're using Cloudflare as proxy, we are hiding our Icecast specific ports to the public on the public hostname.

_Example of case C while these 3 streams are the same remote relay, accessed by HTTP proxy, HTTPS proxy and Icecast respectively, listeners are shown just from the third relay (the Icecast direct one)_ 
![image](https://user-images.githubusercontent.com/74368492/105418674-46b46800-5c1c-11eb-9bda-d5ca66629c45.png)

We've checked all the admin passwords and parameters from all the relays and tested each one separately.

[This issue seems to be related to this other one, which was closed](https://github.com/AzuraCast/AzuraCast/issues/2667)

**Device(s):**
 - Device: Desktop 
 - OS: macOS Big Sur 11.0.1
 - Browser: Google Chrome
 - Version: 87.0.4280.141 (Build oficial) (x86_64)

**Comment by balmasedano** [comment]
I'm getting the same problem when relaying. I see the current listeners at home page but no data when I generate listener stat reports. Thanks!

**Comment by SlvrEagle23** [comment]
@lramilo It's possible that the Icecast return format is slightly different from the Icecast-KH format after a certain point. Would it be possible for you to send us a sample link of an Icecast installation that's running the version that's having the problem, so we can test our NowPlaying library on it?

**Comment by lramilo** [comment]
hi @SlvrEagle23 wich specific URLs do you need? I could take a snapshot of the results and paste them here, as it's a productive installation and I will be forced to publish admin's password in order for you to grab this info. 

Another option could be to install a testing instance. 

Please notice I'm using an external relay in order to handle +1000 listeners, as I'm still struggling with #3702. I also planning to test statistics with this high volume. 

Thanks !

**Comment by SlvrEagle23** [comment]
@lramilo Could you possibly spin up a test instance for us to test things out? You can e-mail me the relevant credentials at my personal e-mail (buster@busterneece.com) if that works better for you.

I could probably spin up a test instance myself, but since you're experiencing the problem with your specific version it would probably be easier to test with that.

**Comment by lramilo** [comment]
@SlvrEagle23 I've sent you the credentials from lramilo@gmail.com (Subject: "Info for issue #3700 No statistics retrieved from Icecast 2.4.4 (or Icecast KH with HTTP proxy") Thanks a lot !

**Comment by SlvrEagle23** [comment]
@lramilo Thank you for the e-mail and the information!

I found one problem in particular with our Now Playing adapter: if you don't specify an administrator password it'll load the JSON feed for information, and there was a bug in merging the various Now Playing responses back into an aggregated result. Minor bug, but it definitely affected the results.

If you update to the latest Rolling Release, it should be fixed now.

**Comment by SlvrEagle23** [comment]
@lramilo As a related note, based on the formatting from your message I think I may have also figured out a second problem: if you specify a stream URL in `https://username:password@stream` format, it doesn't properly detect that as an administrator username/password and extract it, which would normally trigger it to pull the more reliable XML feed from the administrative side of the installation rather than the public-facing JSON feed.

This has also been fixed as of the latest version, so it works just as well.

**Comment by lramilo** [comment]
@SlvrEagle23 I've tested it again on a new instance with rolling release, but I still find the same issue. I'm using one of the same relays I've sent you on my last e-mail. Here are the screenshots. I've tested with Icecast 2.4.4 on HTTP and HTTPS. Do I am missing anything ?

Thank you !
![image](https://user-images.githubusercontent.com/74368492/111885539-38c65d80-89a7-11eb-9ee8-ab3253a0692f.png)

![image](https://user-images.githubusercontent.com/74368492/111885562-5267a500-89a7-11eb-8c10-d8cc94e4e2b2.png)

![image](https://user-images.githubusercontent.com/74368492/111885532-2a784180-89a7-11eb-870e-f9bcbf9d11d7.png)

![image](https://user-images.githubusercontent.com/74368492/111885553-4976d380-89a7-11eb-828a-89ce02c061e6.png)

**Comment by pimseb** [comment]
Hello,

I have exactly the same problem. I'm using an icecast 2.4.4 as relay. Azuracast doesn't show its unique listeners (always 0) and the listeners statistics remain empty.
I've checked the admin password and it's OK. 
Is there any update on this bug?
Thank you

**Comment by SlvrEagle23** [comment]
@pimseb After further investigation I found another issue where unique listeners weren't being iterated because of a check that failed on some Icecast installation versions (due to capitalization of a property).

This should be fixed as of the latest Rolling Release version currently being deployed.

**Comment by pimseb** [comment]
@SlvrEagle23 Great news, thank you for your fast update.
I'll test the rolling release when it will be available and let you know
