### ISSUE TITLE
MusicBrainz API runs into hits error 503 (Rate Limit) after repeated Now Playing checks

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#3705]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #fe8beda (2021-01-21 20:12) 

**Host Operating System**
Ubuntu 20.04 

**Describe the bug**
When I enabled the third party service `Check Web Services for Album Art for Now Playing Tracks` it runs into repeated 503 errors which flood the logs, I'm assuming this is due to multiple stations present. 

As per the MusicBrainz API documentation it reveals this `For "python-musicbrainz/0.7.3": we allow through (on average) 50 requests per second, and decline the rest (though recently this has not been hit).` 

I'd perhaps propose the Now Playing be changed to the 5 minute media check to avoid hitting the rate limits, or streamline it so it doesn't flood it at once. 
**To Reproduce**
Enable the third party services
Review Docker web_1 logs. 
**Expected behavior**
The third party to not be bombarded with excessive API requests which results in a 503. 
**Relevant Logs**
```
web_1                      | [2021-01-22T19:55:34.205919+00:00] AzuraCast.ERROR: MusicBrainz Album Art Error: Server error: `GET https://musicbrainz.org/ws/2/recording/?query=%2229%22%20AND%20artist%3A%22declan%20mckenna%20-%20rapture%20-28lyric%20video%22&inc=releases&limit=5&fmt=json` resulted in a `503 Service Temporarily Unavailable` response: {"error": "Your requests are exceeding the allowable rate limit. Please see http://wiki.musicbrainz.org/XMLWebService fo (truncated...)  {"exception":"[object] (GuzzleHttp\\Exception\\ServerException(code: 503): Server error: `GET https://musicbrainz.org/ws/2/recording/?query=%2229%22%20AND%20artist%3A%22declan%20mckenna%20-%20rapture%20-28lyric%20video%22&inc=releases&limit=5&fmt=json` resulted in a `503 Service Temporarily Unavailable` response:\n{\"error\": \"Your requests are exceeding the allowable rate limit. Please see http://wiki.musicbrainz.org/XMLWebService fo (truncated...)\n at /var/azuracast/www/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)","song":"declan mckenna - rapture -28lyric video - 29","songId":"bfda66a5a8b833fbb6e974aba7f0d390"} {"station":{"id":49,"name":"Hills"}}
```
**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**
MusicBrainz API Rate Limits can be found here: https://wiki.musicbrainz.org/MusicBrainz_API/Rate_Limiting

**Comment by SlvrEagle23** [comment]
@SC2Mitch Latest update (currently rolling out to images) implements much stronger rate limit checking, both on our end by delaying subsequent requests several seconds if needed, and on the request handling side by detecting and logging rate limit errors.
