### ISSUE TITLE
Liquidsoap deactivation for Shoutcast only

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#3708]
**Using Docker installation method**
Ansible

**AzuraCast version**
Rolling Release #13bd765

**Host Operating System**
Ubuntu 18.04 LTS

**Describe the bug**
Liquidsoap cannot be disabled for our broadcasts using Shoutcast only.

**To Reproduce**
1. Go to 'Station Profile Edit Page'
2. Click on 'AutoDJ' tab
3. Liquidsoap cannot be disabled (https://prnt.sc/xjmicq)

**Expected behavior**
Liquidsoap cannot be disabled for stations using Shoutcast-only on the last update.

**Relevant Logs**

**Screenshots**
https://prnt.sc/xjmicq

**Device(s):**
 - Device: PC
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: Latest

**Additional context**
Stations using Shoutcast should easily be disabled. DJ port, playlist, etc. to stations that do not use autodj. no need to add. This is my personal opinion.

I know you don't have Ansible support. I apologize for keeping you busy.

**Comment by SlvrEagle23** [comment]
@ogrenci01 Thank you for the report; this has been fixed as of the latest rolling-release version and these options are now back on the profile menus.
