### ISSUE TITLE
Can't connect from Traktor PRO for streaming

### ISSUE THREAD

**Issue by solariz9** [AzuraCast/AzuraCast#3709]
When I try to connect from the Traktor Pro, I get:
```
2021/01/24 22:58:43 [lang:3] AzuraCast Feedback Response: OK
2021/01/24 23:00:40 [lang:3] Authenticating DJ: source
2021/01/24 23:00:40 [lang:3] AzuraCast DJ Auth Response: false
```
I use the format:
`username:password`
in "password" field, because Traktor Pro does not have a "user" field.

**Comment by SkeletorMonkey** [comment]
@solariz9, Try username,password  (comma)

**Comment by solariz9** [comment]
> @solariz9, Try username,password (comma)

Thank you very much! In this way, I connected.
