### ISSUE TITLE
Remote URL doesn't play correctly after fix for #3701

### ISSUE THREAD

**Issue by cpeter1207** [AzuraCast/AzuraCast#3712]
I upgraded AzuraCast to the latest rolling release this morning. Everything was running smoothly until my scheduled remote URL playlists this evening. They've played flawlessly for years, but this evening they're extremely broken up and impossible to listen too.

I believe this may be caused by the fix for #3701, since I don't see any other recent changes to direct stream remote URL playlists.

Looking at the comments for #3701, the author says he had to disable crossfading. I have smart crossfading enabled, and all of my remote URLs are in the "interrupting" switch in the liquidsoap config.

Is it possible that that switch needs to be moved to after the crossfade like live is?

**Comment by Vaalyn** [comment]
Closing this issue since the commit that was the problem reported here was reverted some time back.

For the general problem with remote playlists please follow the other issue/s mentioned.
