### ISSUE TITLE
Cue points are not respected by playlists in Jingle mode

### ISSUE THREAD

**Issue by bla-ckbox** [AzuraCast/AzuraCast#3713]
**Using Docker installation method**

Yes

**AzuraCast version**

v0.11.2 Stable

**Host Operating System**

Ubuntu 18.04 (LTS) x64

**Describe the bug**

Cue points are not respected by playlists in Jingle mode

**To Reproduce**

1. Edit Media to add Custom Cues, example add a cue out at 20s
2. Create Playlist with the Hide Metadata from Listeners ("Jingle Mode") option
3. Add the media (step 1) in the playlist
4. Restart the broadcasting to apply the settings
5. Listen, cue points are not are not respected, track is played full

**Expected behavior**
Hide metadata option should not disable the ADVANCED PLAYBACK SETTINGS of a track

**Relevant Logs**

No logs, here is a short excerpt from the config that interests us

```
playlist_advert = playlist(id="playlist_advert",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/cosmic_address/playlists/playlist_advert.m3u")
playlist_advert = drop_metadata(playlist_advert)
playlist_advert = audio_to_stereo(id="stereo_playlist_advert", playlist_advert)
playlist_advert = cue_cut(id="cue_playlist_advert", playlist_advert)
```

The problem stems from the fact that the _drop_metadata_ function is present before the _cue_cut_ function.
_drop_metadata_ delete all meta, but cue point are storred in _liq_cue_in_ and _liq_cue_out_ meta
When generating configuration _cue_cut_ must be inserted before a possible drop metadata

**Additional context**

Référence:

- https://www.liquidsoap.info/doc-dev/reference.html#cue_cut

- https://www.liquidsoap.info/doc-dev/reference.html#drop_metadata

**Comment by SlvrEagle23** [comment]
@bla-ckbox Thank you for the report; comprehensive reports like this that point out the exact cause of the problem are the best ones we can get, and the easiest for us to fix.

I've made a commit to the rolling release channel that will fix this. It should be deployed to the Docker images in about 5-10 minutes from the time of this post.
