### ISSUE TITLE
Liquidsoap randomly falling-back to error.mp3 using S3 Compatible Remote Storage

### ISSUE THREAD

**Issue by dimasalfaridzi** [AzuraCast/AzuraCast#3719]
Hi. I'm using AzuraCast v0.11.2 Stable on Ubuntu 20.04 using Docker installation. Recently, I move my station media directory from local storage to S3 Compatible Remote Storage. The media files at remote storage is pre-uploaded. All of the tracks at remote storage have been processed by AzuraCast and all of the existing playlist have been updated too.

I encounter an issue. Randomly, liquidsoap is falling back and playing "error.mp3" audio just like #3660 . Skipping songs sometimes fix the problem but the same problem occur few minutes or hours again. Sometimes, fallback audio playing for almost more than 15 minutes if I'm not skipping songs.

There is no connection issue between AzuraCast server and remote storage.

**Comment by SC2Mitch** [comment]
Without any logs from liquidsoap this is nearon impossible to debug, can you provide some logs please

**Comment by Vaalyn** [comment]
Closing this issue since there have been no replies for quite some time and we have no logs that we can use to debug.
