### ISSUE TITLE
Add settings to <mount>

### ISSUE THREAD

**Issue by Jhonbeaver** [AzuraCast/AzuraCast#372]
Hi, for example, I want to add `<intro>` setting to `<mount>` in icecast config. I add it in station's profile configuration, but line `<intro>somefile.mp3</into>` appeared in the end of file, not in mount section. 
Is it possble, to add something to mount config?

**Comment by SlvrEagle23** [comment]
@Jhonbeaver There are two "Custom Configuration" sections, one for the entire Icecast configuration (inside your station's main profile), and another inside each individual mount point's configuration from the "Mount Points" section. The latter should work just fine for this purpose.
