### ISSUE TITLE
Api for Statistics 

### ISSUE THREAD

**Issue by AleeRobles** [AzuraCast/AzuraCast#3720]
Hello! is there any api to get the statistics of a radio? such as connected users, minutes listened, IP list, devices (mobile or browser) etc.

**Comment by SlvrEagle23** [comment]
@AleeRobles We do have an API endpoint for enhanced listener details. It's an authenticated endpoint, but if you call it with no other arguments you'll get a list of the current live listeners for a station, along with the IP, user agent, inferred device and inferred location (from IP):

https://www.azuracast.com/api/#/Stations%3A%20Listeners/App%5CController%5CApi%5CStations%5CListenersController%3A%3AindexAction

**Comment by AleeRobles** [comment]
Thanks, but with that api I get the ones that are in real time, right? I don't have a "history" to which to pass dates for example, do I?

**Comment by SlvrEagle23** [comment]
@AleeRobles You can pass `start` and `end` parameters in the query string of that endpoint. Both formats should be dates in the form of `YYYY-MM-DD` (i.e. `2021-01-28`).
