### ISSUE TITLE
Cannot upload music to stations

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#3723]
**Using Docker installation method**
Ansible

**AzuraCast version**
Rolling Release #283946e

**Host Operating System**
Ubuntu 18.04 LTS

**Describe the bug**
Cannot upload music to stations.

**To Reproduce**
1. Go to 'Music Files'
2. Click on 'Select File' and Select any "MP3"
3. Music upload stops before it finishes

**Expected behavior**
No music can be added to any playlist of any station. Loading does not occur.

**Relevant Logs**
`2021/01/27 07:53:02 [error] 1204#1204: *17905 client intended to send too large body: 1049894 bytes, client: 162.158.19.39, server: localhost, request: "POST /api/station/8/files/upload HTTP/1.1", host: "azuracast.domain.com", referrer: "https://azuracast.domain.com/station/8/files"
2021/01/27 07:53:02 [error] 1204#1204: *17799 client intended to send too large body: 1049894 bytes, client: 162.158.19.39, server: localhost, request: "POST /api/station/8/files/upload HTTP/1.1", host: "azuracast.domain.com", referrer: "https://azuracast.domain.com/station/8/files"
2021/01/27 07:53:32 [error] 1204#1204: *17832 open() "/var/azuracast/www/web/static/dist/lib/bootstrap/bootstrap.bundle.min.js.map" failed (2: No such file or directory), client: 162.158.19.40, server: localhost
2021/01/27 07:53:36 [error] 1204#1204: *17801 client intended to send too large body: 1049894 bytes, client: 162.158.19.39, server: localhost, request: "POST /api/station/8/files/upload HTTP/1.1", host: "azuracast.domain.com", referrer: "https://azuracast.domain.com/station/8/files"
2021/01/27 07:53:36 [error] 1204#1204: *17907 open() "/var/azuracast/www/web/static/dist/lib/bootstrap-vue/bootstrap-vue.min.js.map" failed (2: No such file or directory), client: 162.158.19.39, server: localhost
2021/01/27 07:53:36 [error] 1204#1204: *17819 client intended to send too large body: 1049894 bytes, client: 162.158.19.39, server: localhost, request: "POST /api/station/8/files/upload HTTP/1.1", host: "azuracast.domain.com", referrer: "https://azuracast.domain.com/station/8/files"
2021/01/27 07:53:36 [error] 1205#1205: *17918 open() "/var/azuracast/www/web/static/dist/lib/moment/locales.min.js.map" failed (2: No such file or directory), client: 162.158.19.39, server: localhost
2021/01/27 07:53:36 [error] 1204#1204: *17917 open() "/var/azuracast/www/web/static/dist/lib/bootstrap-vue/bootstrap-vue.min.css.map" failed (2: No such file or directory), client: 162.158.19.39
2021/01/27 07:53:36 [error] 1205#1205: *17919 open() "/var/azuracast/www/web/static/dist/lib/moment/moment.min.js.map" failed (2: No such file or directory), client: 162.158.19.39, server: localhost
2021/01/27 07:54:05 [error] 1204#1204: *17781 open() "/var/azuracast/www/web/static/dist/lib/bootstrap/bootstrap.bundle.min.js.map" failed (2: No such file or directory), client: 162.158.19.39, server: localhost
2021/01/27 07:54:05 [error] 1205#1205: *17821 open() "/var/azuracast/www/web/static/dist/lib/bootstrap-vue/bootstrap-vue.min.js.map" failed (2: No such file or directory), client: 162.158.19.39, server: localhost
2021/01/27 07:54:05 [error] 1204#1204: *17924 open() "/var/azuracast/www/web/static/dist/lib/moment/moment.min.js.map" failed (2: No such file or directory), client: 162.158.19.39, server: localhost
2021/01/27 07:54:05 [error] 1204#1204: *17928 open() "/var/azuracast/www/web/static/dist/lib/moment/locales.min.js.map" failed (2: No such file or directory), client: 162.158.19.39, server: localhost
2021/01/27 07:54:05 [error] 1204#1204: *17907 open() "/var/azuracast/www/web/static/dist/lib/bootstrap-vue/bootstrap-vue.min.css.map" failed (2: No such file or directory), client: 162.158.19.39, server: localhost`

**Screenshots**
Screen capture cannot be taken because the processes ended very quickly.

**Device(s):**
 - Device: PC
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: Latest

**Additional context**
I know very well that you do not support Ansible. However, this option should work fine for those using Ansible. Thank you very much to the Azuracast team.

**Comment by ogrenci01** [comment]
Hi @SlvrEagle23 

I found the solution for this error. For Ansible, the "client_max_body_size" option must be added to the "Basic Settings" section in the "nginx.conf" file. I edited it and loaded it without any problems.

`client_max_body_size 1024M;`

Source: https://stackoverflow.com/questions/44741514/nginx-error-client-intended-to-send-too-large-body

**Comment by SlvrEagle23** [comment]
@ogrenci01 I could swear we used to have that line of configuration in place on Ansible nginx installations, but in any case I've added it back so it matches our configuration on Docker installs.
