### ISSUE TITLE
5 minute cronjob fails to run.

### ISSUE THREAD

**Issue by stickbear2015** [AzuraCast/AzuraCast#3724]
Hello,
When I attempt to run the five minute cron job, it likes to stall out on automated assignment for station primary.
I don't understand why it's dying.
I'm attaching the log from the page.
azuracast version in use: AzuraCast • Rolling Release #4cf94c6 (2021-01-24 17:35) • Docker • PHP 7.4.
core OS: debian 10
Any help would be appreciated.
[5-minute-cron-output.txt](https://github.com/AzuraCast/AzuraCast/files/5877926/5-minute-cron-output.txt)

**Comment by stickbear2015** [comment]
@SlvrEagle23 what more info would you like?

**Comment by stickbear2015** [comment]
I've attached the output of docker-compose logs -f from just before and right through the attempted run of the five minute task. I hope their's something useful here.
[azuracast-logs.txt](https://github.com/AzuraCast/AzuraCast/files/5886042/azuracast-logs.txt)

**Comment by stickbear2015** [comment]
did the attached logs help?

**Comment by Vaalyn** [comment]
From what I can see in the logs there are a lot of the following errors:
```
Unable to init from given binary data.
```

This would indicate to me that the album art image of one or multiple media file is not parsable by the Intervention Image library.

**Comment by stickbear2015** [comment]
@Vaalyn I can possibly sort that out by removing the unprocessable files, but the reports>unprocessable files for that station refuses to load. Is their another way to get around it? meaning get into unprocessable files so I can remove them?

**Comment by stickbear2015** [comment]
as a follow up, all stations now report 0 unprocessable media files, is their a way to dump the album art from the effected station, in this case, primary, so I start clean?

**Comment by stickbear2015** [comment]
Hello all,
so in further digging, It takes about ten minutes to process the effected station, but it finishes it, but other stations are experiencing similar issues. note that sometimes, like in this case, primary never fully finishes. it's completing of primary is hit or miss.
I know the cronjob stalls out completely, because I see it attempt to restart 5 minutes after the 600 second timer expires on the effected station.
note: I've disabled the new station album art system by unchecking the boxes in system settings>services and removed my lastfm key to see if the issue might have been their.
Logs attached to this ticket.
one is azuracast-webpage-output.txt the contents of the scrolling log shown on the webpage of admin/debug/sync/medium
the second is azuracast-logs-dockercompose.txt the docker-compose logs -f output.
[azuracast-webpage-output.txt](https://github.com/AzuraCast/AzuraCast/files/5914906/azuracast-webpage-output.txt)
[azuracast-logs-dockercompose.txt](https://github.com/AzuraCast/AzuraCast/files/5914907/azuracast-logs-dockercompose.txt)

**Comment by Vaalyn** [comment]
From the error message I quoted (which is also in the docker-compose logs you attached) this would lead me to believe that your media files artwork image is in a format that the image library can not handle. Here you can see the supported image formats (we are using the default GD driver): http://image.intervention.io/getting_started/formats

I'm not sure what software you could use to check what format the images in your files are using.

**Comment by stickbear2015** [comment]
@Vaalyn
thanks for that, I'll do further plowing to see if I can rip the artwork out of the mp3's.
This is a solvable issue, and I appreciate you providing the link to supported formats.
More to come.

**Comment by stickbear2015** [comment]
I've done further testing and troubleshooting, but I suck as log parcing to find the current error being presented in documentaries.
[azuracast-web-log-02142021.txt](https://github.com/AzuraCast/AzuraCast/files/5979278/azuracast-web-log-02142021.txt)
doesn't give anything useful that I can see, but I attach it for sanity.
[azuracast-docker-log02142021.txt](https://github.com/AzuraCast/AzuraCast/files/5979282/azuracast-docker-log02142021.txt)
is the docker-compose logs -f output.
Any insite would be appreciated.

**Comment by stickbear2015** [comment]
I'm re-opening this issue, as the task, still isn't completing. I'm running the latest rolling release, d7d343.
[azuracast-web-console-02182021.txt](https://github.com/AzuraCast/AzuraCast/files/6006389/azuracast-web-console-02182021.txt)
is the web console output.
[azuracast-log-02182021.txt](https://github.com/AzuraCast/AzuraCast/files/6006393/azuracast-log-02182021.txt)
is the docker-compose logs -f output.
Any further advice would be appreciated.

**Comment by Vaalyn** [comment]
From your web console log:

```
[2021-02-18T22:39:45.379783+00:00] AzuraCast.INFO: Processing auto-assigning folders for station... {"station":"primary"} []
[2021-02-18T22:48:34.771279+00:00] AzuraCast.ERROR: An exception occurred while executing 'INSERT INTO station_playlist_media (playlist_id, media_id, weight, last_played) VALUES (?, ?, ?, ?)' with params [1, 73282, 14303, 0]:  SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []
[2021-02-18T22:48:34.772678+00:00] AzuraCast.INFO: Worker stopped due to time limit of {timeLimit}s exceeded {"timeLimit":300} []
```

This is unrelated to the album art issue that got fixed by my PR.

What you are now seeing is that the "auto-assigning folders" task is running a database transaction that takes too long and times out. My guess is that you have an auto-assign folder that contains so many songs that this db transaction is trying to send a huge amount of songs in one transaction, the db starts happily working on it until the transaction time limit is reached.

How many songs are in the folder that is set to auto-assign to the playlist with the id `1`?

**Comment by stickbear2015** [comment]
@Vaalyn 
station ID 1 is Primary, so, from the same log
[2021-02-18T22:39:33.044499+00:00] AzuraCast.INFO: Processing media for storage location Local: /var/azuracast/stations/primary/media... [] []
[2021-02-18T22:39:35.313803+00:00] AzuraCast.DEBUG: Media processed for "Local: /var/azuracast/stations/primary/media". {"total_size":"89736091389 (89.7 GB)","total_files":14338,"already_queued":0,"unchanged":14338,"updated":0,"created":0,"deleted":0,"not_processable":0} []

**Comment by Vaalyn** [comment]
@stickbear2015 The amount of files in the output there with `"total_files":14338` is only for the media processing and not the auto-assign.

Please check what folders you have set to auto-assign to `playlist with id 1` and how many songs they contain.

**Comment by stickbear2015** [comment]
@Vaalyn nothing is set to auto assign. as I don't use that feature.

**Comment by stickbear2015** [comment]
so I did some further checking, @Vaalyn and no, auto assign isn't enabled anywhere that I can see.
Any further advice would be appreciated.
