### ISSUE TITLE
M4A files generated by Anchor.fm will not process

### ISSUE THREAD

**Issue by adamburnsuk** [AzuraCast/AzuraCast#3727]
**Using Docker installation method**

Yes
**AzuraCast version**
Powered by AzuraCast • v0.11.2 Stable • Docker • PHP 7.4

**Host Operating System**

Ubuntu 20.04.1 LTS
**Describe the bug**

When I upload any m4a file generated with anchor.fm, it will not process.  In the music page in Azuracast, it will always say "File Not Processed."  I have tested the files, and they do play locally.  
The mime type tag in ID3 tags is showing as: audio/x-m4a
I have tried both ftp upload and uploading through the web page and both have the same effect.  I have two different files, one is around 20mb and one is about 70mb and neither of them will process.  I see anchor.fm as the commonality, as other m4a files I try do work.  But, I can't figure out what is different.
I have also tried to look at console log in browser when uploading and no errors occur in network log or console log when processing upload.  I tried looking at docker logs and also liquidsoap logs, but I can't find any logs related to processing files...so I'm not sure where else to look.

**To Reproduce**
1. Go to music page
2. Upload any m4a file generated by anchor.fm
3. File will remain as "Not Processed" forever

**Expected behavior**

I expect that these files would process as I think they are just normal m4a files.

**Relevant Logs**

I can't find any errors in the logs, but I've looked at console log, network log, web log, station log and liquidsoap log.  If there is somewhere else I can look to provide logs, please let me know.

**Screenshots**

**Device(s):**
 - OS: I'm uploading from Windows using both browser and ftp

**Additional context**

I can attach the actual files if needed, but couldn't find the way to attach them here.

**Comment by SlvrEagle23** [comment]
@adamburnsuk I believe this is already fixed as of our latest rolling-release version. You may want to try updating to that version, or just wait for us to package those changes into a new stable version (which should happen soon, since it has been a while since we've had our last stable release).

**Comment by adamburnsuk** [comment]
Ok I'll try that, I think I just assumed that the other ticket(s) for m4a would have been in the stable release already.  :)  That's my bad.  I'll try that today.

**Comment by adamburnsuk** [comment]
It worked!!!  Thanks for the help.
