### ISSUE TITLE
When using S3 Compatible storage playlists will not be defined in the liquidsoap script

### ISSUE THREAD

**Issue by silfversound** [AzuraCast/AzuraCast#3728]
Installed on Ubuntu server 20.04 with docker, v0.11.2 Stable

So i would like to use S3 compatible storage and yet be able tweak my playlists in the Liquidsoap script.
First i was wondering why my playlist wouldn't show up in the liquidsoap script until i tried with local storage and the playlists would show up. 

Is it supposed to like this that the playlist won't be defined in the liquidsoap script when using S3 Compatible storage, or is it a bug?

**Comment by Vaalyn** [comment]
Yes this is currently the intended behaviour for non-local media storage locations.

Since the media files are pulled by the AzuraCast AutoDJ from the external storage location into a local temporary location prior to them being send to Liquidsoap they are not defined as a playlist for LS.
