### ISSUE TITLE
Storage location behavior

### ISSUE THREAD

**Issue by noam2205** [AzuraCast/AzuraCast#3729]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.11.2

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
If multiple stations share a storage location but not playlists. A media file that belongs to a playlist in one station will be marked as File Not Processed in the media files section of other stations (and will be removed from playlists in other stations)

**To Reproduce**
1. Make two stations that share a storage locations but have different playlists.
2. Add a media file to first station's playlist
3. Add it to the second station's playlist
4. You can now see that the file was removed from the first playlist and will be displayed as File Not Processed on the media files section of the first station

**Expected behavior**
Being able to have one storage location for multiple stations with different playlists and being able to share media files. This is without seeing File Not Processed for media files that belong to playlists in other stations and that adding a shared media file to one playlist will not remove it from the other playlist.

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86

**Additional context**
Either I totally misunderstood the usage of storage locations or it's a bug.
Note that I did played directly with the Docker's volume and moved media files between storage locations in order to unify existing stations' media while not changing the playlists configurations' location.

**Comment by SlvrEagle23** [comment]
@noam2205 This was fixed as of a rolling release update. If you switch to the rolling release channel, you will be able to take advantage of the latest features, or you can wait until we roll the changes into another stable build, which will be happening quite soon.

**Comment by noam2205** [comment]
Good to know!
And thank you for the quick response
