### ISSUE TITLE
Azuracast shows listeners from the same ip even if they are not on the same ip Azuracast via docker on ubuntu 20.04

### ISSUE THREAD

**Issue by SaschaDK** [AzuraCast/AzuraCast#3730]
azuracast installed via docker on ubuntu 20.04

Hi there. i experience that azuracast says the listeners come from the same ip. which is not the case. which I do not quite understand why. how do i fix this? :)
azuracast I have installed via docker on an ubuntu 20.04
azuracast v Rolling Release #6f8f6df (2021-01-28 0:20) • Docker • PHP 7.4 

I thank you many times for a really nice software and look forward to future releases :)
/ Sascha

**Comment by LordHelmchen666** [comment]
I believe to have the same problem. Seems there is a problem with nginx parsing the wrong IP to Icecast.
In my listener stats:
`

IP | Zeit (Sekunden) | User Agent | Stream | Ort
-- | -- | -- | -- | --
93.192.xxx.xxx | 213 | desktop_windows Desktop-Gerät                             VLC/3.0.11.1 LibVLC/3.0.11.1  VLC 3.0, Unknown OS | MP3@192kbps                                      Lokal | Hesse, Deutschland
172.19.0.4 | 153 | desktop_windows Desktop-Gerät                             Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0  Firefox 78.0, GNU/Linux | MP3@192kbps                                      Lokal | Internal/Reserved IP

`
First one is directly connected to Icecast http://stream.eisradio.de:8000/radio.mp3
Second connected to https://stream.eisradio.de/radio/8000/radio.mp3

Restarting docker did not help.

**Comment by Vaalyn** [comment]
Please refer to issue #2898 about this ongoing bug.

Closing as duplicate.
