### ISSUE TITLE
"now_playing" doesn't update when live dj disconnects

### ISSUE THREAD

**Issue by krono86** [AzuraCast/AzuraCast#3734]
When live dj connects, now_playing information is updated taking information from the stream tags (generic_song.jpg is used as cover art); furthermore live.is_live is set to "true".
When live dj disconnects, live.is_live is set to "false", but now_playing information still contains the live stream tags until the next scheduled song is played.

Running azuraCast on a VPS with docker installation.

**Comment by Catskill909** [comment]
Same here

**Comment by s7ntax** [comment]
Same problem here, Ubuntu 20.04 Docker Installation.
