### ISSUE TITLE
Playlist weight for general rotation

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#3735]
Dear azuracast team
It took a while for me to realize this but it has become obvious that the "general rotation" playlist weight setting has the opposite behaviour than what is labeled.
The lower the weight is, the more it gets rotated.
So a general rotation playlist with weight of 1 will play all the time, opposed to a general playlist with 25, which will never be aired.

![image](https://user-images.githubusercontent.com/25333002/106146729-53cedb00-6177-11eb-9767-7d5634b487f8.png)

Could you please confirm and possiblity fix the labels of the drop down menu?

**Comment by SlvrEagle23** [comment]
@griffon56 My goodness, I'm amazed this is the first time this was reported as this code has been running in production for quite some time now, and yet you're right, it was weighing things by a fraction of their weight, so weight 1 became `1/1`, the highest probability, while 25 became `1/25`. 

I've updated that algorithm to be vastly simpler and to just use the weight unmodified, no logs or exponents or anything funny, which should far more reliably match what people are expecting. I've also made sure the new algorithm properly weighs the higher weights into *heavier* rotation.

This should be rolling into the Rolling Release shortly.
