### ISSUE TITLE
HELP ME WHIT THIS PLSS 2 ISSUES

### ISSUE THREAD

**Issue by rofmvalencia** [AzuraCast/AzuraCast#3736]
![ERRORS](https://user-images.githubusercontent.com/67313797/106149978-25eb9580-617b-11eb-8738-cc54688ac396.png)

**Comment by SlvrEagle23** [comment]
@rofmvalencia These don't look like our standard settings we use in AzuraCast. With our software, you connect to the AutoDJ for live streaming, which is usually on port 8005, not 8000, which is the port Icecast uses. Unless you've set your installation up differently, you should be able to connect by following the instructions on the "Streamers/DJs" page for your station.

**Comment by rofmvalencia** [comment]
Yes but for statistics of my radioboss, works before updating the azuracast i know the stremer DJ has a different port but to get statistics form the server in the software i can connect... to get them like before

**Comment by dvdred** [comment]
I have the same issue (the second) too after update. In the listeners reports, now are reported internal docker ip.

**Comment by dvdred** [comment]
I solved the second issue adding this option in the nginx proxy configuration:
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

**Comment by rofmvalencia** [comment]
@dvdred I cannot find the folder... i use docker...

**Comment by rofmvalencia** [comment]
in the default folder ## Start of configuration add by letsencrypt container
location ^~ /.well-known/acme-challenge/ {
    auth_basic off;
    auth_request off;
    allow all;
    root /usr/share/nginx/html;
    try_files $uri =404;
    break;
}
## End of configuration add by letsencrypt container
 
i have this config...

**Comment by rofmvalencia** [comment]
In the v11 is a good way to keep it, the new version is not so stable... I've reinstalled from the marketplace digitalocean site... and now is working good... I'm gonna close this issue. Thank you all for the support, and I wait the stable version of azuracast 12
