### ISSUE TITLE
Shoutcast licensing with AzuraCast

### ISSUE THREAD

**Issue by anoopv89** [AzuraCast/AzuraCast#3738]
Installed ShoutCast using Azuracast panel, now need to license ShoutCast. How can I do that?

**Comment by Catskill909** [comment]
https://www.shoutcast.com/Pricing

**Comment by anoopv89** [comment]
I have the license.. how can I add it with Azuracast setup?

**Comment by rolradio** [comment]
The only way in azuracst is to add these 4 entries directly to your shoutcast sc_serv.conf.


publicserver = always
licenseid = ......
userid = ......
streamauthhash = ......

You can find this information in your schoutcast.com account for your created radio.

Then you have to make the sc_serv.conf read only via putty Chmod:..
Otherwise the data will disappear after restarting your radio.

Then restart your radio.

**Comment by rolradio** [comment]
See also: 

https://help.shoutcast.com/hc/en-us/articles/360002877334-My-DNAS-station-is-registered-on-the-Radio-Manager-but-is-not-listed-in-Shoutcast-s-directory

and

https://help.shoutcast.com/hc/en-us/articles/115003673933-Shoutcast-Server-Configuration-Advanced-

**Comment by rolradio** [comment]
If you also want to make your stream https for the shoutcast.com radio directories you have to ...


publicserver = always
licenseid = ......
userid = ......
streamauthhash = ......

And then for your https stream, that domain name and port will also be included in the shoutcast directories: Such as: https://your.azuracastdomain.com:8000/mountpointname

alternateports = 443
destdns = your.azuracastdomain.com
destip = your.azuracastdomain.com
publicdns = your.azuracastdomain.com
publicip = your.azuracastdomain.com
sslcertificatefile = / path to your domain.com.crt
sslcertificatekeyfile = / path to your domain.com.key 

Thats all...

**Comment by SlvrEagle23** [comment]
@anoopv89 You can set the license information by following these steps:

> Visit the station profile
> Click "Edit Profile", then the "Broadcasting" tab
> In the "Custom Configuration" section, enter something like this:

```json
{ "licenseid": "YOUR_LICENSE_ID", "userid": "YOUR_USER_ID" }
```

Then save changes and restart broadcasting; this should apply your license without worrying about overwriting the configuration file.

**Comment by rolradio** [comment]
@SlvrEagle23 

Thanks.

I had to figure out the previous solution myself.
But I hadn't come across your solution anywhere.
Thanks.

**Comment by coolmusicradio** [comment]
Hi.
I simply put in "custom settings" of "broadcast", the following:

<userid> MYUSERID</userid>
<licenceid> MYLICENCEID</licenceid>

... and at each "mount point" the “Shoutcast hash”.
I have a premium account and it works perfectly for me.

Instead it didn't work for me with this other code format (Shoutcast 2.6):

{ "licenseid": "YOUR_LICENSE_ID", "userid": "YOUR_USER_ID" }

**Comment by Vaalyn** [comment]
I have added the solution posted above to our new documentation so that this information is easier to find in the future:
https://docs.azuracast.com/en/user-guide/station-management#adding-a-license-key

Closing this issue as resolved.
