### ISSUE TITLE
Listeners IPs

### ISSUE THREAD

**Issue by la-roleplay** [AzuraCast/AzuraCast#3739]
Apparently there is a small error when obtaining the IPs

https://i.gyazo.com/7d45b4aa7b4dbc25af1586fc5321bbed.png

**Comment by Vaalyn** [comment]
Please refer to issue #2898 about this ongoing bug.

Closing as duplicate.

**Comment by pixel-paul** [comment]
Take a look at this: https://github.com/AzuraCast/AzuraCast/issues/3108

Recommended action is to restart the docker service.
