### ISSUE TITLE
Add "Listener Authentication"

### ISSUE THREAD

**Issue by FAaBbiii** [AzuraCast/AzuraCast#374]
Hi, please add the "Listener Authentication" for icecast:

http://icecast.org/docs/icecast-2.3.1/auth.html
http://icecast.org/docs/icecast-2.4.1/auth.html

If i set the Options via "Advanced Frontend Configuration" nothing happens.
It would be great if you can manage the users via the station management.

**Comment by SlvrEagle23** [comment]
@FAaBbiii I have tested this locally, and verified that setting up authentication on a mount point is indeed possible, though you have to use a somewhat unique syntax to make it work. The JSON you should input into the "Advanced Configuration" section of the mount point config is below:

```json
{ "authentication": { "@type": "htpasswd", "option": [ { "@name": "filename", "@value": "myauth"}, {"@name": "allow_duplicate_users", "@value": "0"} ] }}
```

Try that and let me know how it works.

**Comment by SlvrEagle23** [comment]
@FAaBbiii While I was looking into it, I also discovered (and fixed) an error that would've caused the XML version of the above to not work. You should be able to now directly enter the XML code needed to generate authentication without any problems:

```xml
        <authentication type="htpasswd">
            <option name="filename" value="myauth"/>
            <option name="allow_duplicate_users" value="0"/>
        </authentication>
```

**Comment by FAaBbiii** [comment]
Thx now htpasswd and url auth works!

<authentication type="url">
	<option name="listener_add" value="http://DOMAIN/login"/>
	<option name="username" value="user"/>
	<option name="password" value="pass"/>
	<option name="auth_header" value="icecast-auth-user: 1"/>
	<option name="timelimit_header" value="icecast-auth-timelimit:"/>
	<option name="headers" value="x-pragma,x-token"/>
	<option name="header_prefix" value="ClientHeader."/>
</authentication>

**Comment by Gaili** [comment]
Hi,
how can i add a user for the "Listener Authentication", manageauth.xsl is not working. I`m on Ubuntu 16.04 traditional.
Thanks
