### ISSUE TITLE
Custom locale in production

### ISSUE THREAD

**Issue by fafamonge** [AzuraCast/AzuraCast#3740]
I'm not clear about how could I custom my locale es_ES (Spanish).

If I edit directly the file /resources/locale/es_ES.UTF-8/LC_MESSAGES/default.po nothing happen and string message doesn't change.

Nor editing /resources/locale/compiled/es_ES.UTF-8.php

I'm a bit confused because some string into the file are empty but in frontend (public page) it shows the translated string so I'm not sure where it's the file it use to get the string.

Using docker:
Rolling Release #6f8f6df (2021-01-28 0:20) • Docker • PHP 7.4

Thank you!

**Comment by SlvrEagle23** [comment]
@fafamonge In the case of our locales, they're compiled into two files:

- `resources/locale/compiled/(locale).php` for the backend, and
- `resources/locale/translations.json` for the frontend.

The backend cache is generated by running `bin/console locale:import` inside the `web` Docker container (or running `./docker.sh cli locale:import`) and the frontend cache is built by running `npm run import-locales` inside the frontend container (which is located inside the `/frontend` folder).

**Comment by Vaalyn** [comment]
Closing as resolved.
