### ISSUE TITLE
No Web Interface after update / PHP Fatal error: Class 'App\Console\ErrorHandler' not found

### ISSUE THREAD

**Issue by emilio-pro** [AzuraCast/AzuraCast#3741]
**Using Docker installation method**

Yes

**AzuraCast version**

Current stable version

**Host Operating System**

Synology Linux

**Describe the bug**

After updating to the latest version the web-interface isn't working. All I get is a blank screen. On the positive site: the audio streams are up.

**To Reproduce**

1.  ./docker.sh update-self
2. ./docker.sh update
And just to be sure:
3. docker-compose down
4. docker-compose up -d --build --force-recreate

**Expected behavior**

I expect to be able to login to the  webinterface.

**Relevant Logs**

```
PHP Fatal error:  Uncaught Error: Class 'App\Console\ErrorHandler' not found in /var/azuracast/www/src/EventDispatcher.php:33
Stack trace:
#0 /var/azuracast/www/src/EventDispatcher.php(28): App\EventDispatcher->addServiceSubscriber()
#1 /var/azuracast/www/config/events.php(178): App\EventDispatcher->addServiceSubscriber()
#2 /var/azuracast/www_tmp/CompiledContainer.php(294): CompiledContainer::{closure}()
#3 [internal function]: CompiledContainer::{closure}()
#4 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(75): call_user_func_array()
#5 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(116): Invoker\Invoker->call()
#6 /var/azuracast/www_tmp/CompiledContainer.php(301): DI\CompiledContainer->resolveFactory()
#7 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(53): CompiledContainer->get14()
#8 /var/azuracast/www/src/AppFactory.php(210): DI\CompiledContainer->get()
#9 /var/azuracast/www/src/AppFactory.php(60): App\AppFactory::buildRoutes()
#10 /var/azuracast/www/bin/console(11): App\Ap in /var/azuracast/www/src/EventDispatcher.php on line 33
```
**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
Please try re-running the update process via `./docker.sh update`.

When starting the containers manually via `docker-compose up -d` you shouldn't add ` --build --force-recreate` since the AzuraCast containers are already pre-build by our build system.

**Comment by emilio-pro** [comment]
Thx for your reply.
Unfortunately it doesn't help.

The same error occurs when I rerun ./docker.sh update.
Also when I restart with:
docker-compose down
docker-compose up -d

Radio streams are still available, luckily.

**Comment by SlvrEagle23** [comment]
@emilio-pro This suggests for some reason your `azuracast_tmp_data` volume isn't being cleared as part of the update process. You may need to manually run:

```
docker-compose down
docker volume rm azuracast_tmp_data
./docker.sh update
```

**Comment by emilio-pro** [comment]
It is getting stranger by the minute:
`docker volume rm azuracast_tmp_data
Error: No such volume: azuracast_tmp_data`

**Comment by SlvrEagle23** [comment]
@emilio-pro It's possible your installation is both in a folder not named `azuracast` and didn't end up with the initial `.env` file that it should've had that would've defined its project name as `azuracast`, so the volume wouldn't be named that.

I'll see about adding something in the install script that clears the directory either way.

**Comment by emilio-pro** [comment]
You're right. I'm having a different prefix. Found it, removed it, checked that is was removed using docker volume ls, ran .docker.sh update. But still the same error. The volume is recreated.

**Comment by SlvrEagle23** [comment]
@emilio-pro Is your `docker-compose.yml` file up-to-date? There should no longer be a `www` volume in use.

**Comment by emilio-pro** [comment]
I believe so. Just to be sure, I removed it and reran the update to make sure the latest version was downloaded. En new version was downloaded, but still the same error.

**Comment by SlvrEagle23** [comment]
@emilio-pro Something about your installation is nonstandard and the struggle is finding it without being able to actually see your installation. With the information we have, there's nothing we can do to reproduce the issue or recreate it; if you're unable to get to the bottom of it from your end, it may be worthwhile to follow the Docker installation instructions and reinstall your instance using the default settings (i.e. into `/var/azuracast` and with the latest Docker utility script doing the installation).

**Comment by emilio-pro** [comment]
I guess you're right. I'll investigate some more and try the reinstallation and report back afterwards.

**Comment by emilio-pro** [comment]
Okay. I guess it is fixed.
I have a `COMPOSE_PROJECT_NAME=proprad` directive in my .env-file.
When stopping the project, I noticed these errors:
```
Error: No such volume: azuracast_www_vendor
Error: No such volume: azuracast_tmp_data
Error: No such volume: azuracast_redis_data
```
So on starting the proprad-* volumes are created, but on shutdown the script tries to remove azurast-* volumes.
Removing the prodrad-* volumes manually and rerunning the update fixed my problem. Might be some to add to the install-script as you suggested.

Thanks again for all your great work on this project, your swift replies and for pointing me in the right direction.
