### ISSUE TITLE
Version 0.12 does not show IPS

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#3742]
Version: 0.12
OS: Ubuntu 18.04

After updating to version 0.12 Azuracast no longer shows the ips of the connected listeners as shown in the attached image.

![Capturar](https://user-images.githubusercontent.com/58113324/106273902-284cfe80-6212-11eb-83c9-1acd238f9368.JPG)

**Comment by pixel-paul** [comment]
Take a look at this: https://github.com/AzuraCast/AzuraCast/issues/3108

Recommended action is to restart the docker service.

**Comment by Vaalyn** [comment]
As mentioned by @pixel-paul please refer to issue #3108 and #2898 about this ongoing bug.

Closing as duplicate.
