### ISSUE TITLE
All listeners appear with the same IP since the last update

### ISSUE THREAD

**Issue by coolmusicradio** [AzuraCast/AzuraCast#3744]
Installation: Docker
so: Ubuntu 16.04 Server
VPS: OVH
core: 1 vCore
RAM: 4 GiB
Storage: 40 GiB
Server: Shoutcast 2 with premium account.

Since I have updated to the latest version of Azuracast, all listeners that connect to this radio appear with the same ip: 172.19.0.4 and say: "Internal / Reserved IP".
I have verified that it is not the same listener with different devices (when I connect to the radio I also appear with this IP.
Has it happened to you? What could be the problem?
Thank you very much in advance and greetings.
David. 

![azuracast](https://user-images.githubusercontent.com/78275699/106365736-c8e90e80-6337-11eb-9dbf-4eac4ba1982d.png)

**Using Docker installation method**

**AzuraCast version**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
Please refer to issue #3108 and #2898 about this ongoing bug.

Closing as duplicate.
