### ISSUE TITLE
MK Pascal Question 

### ISSUE THREAD

**Issue by burnin-hell** [AzuraCast/AzuraCast#3749]
We can use the mk pascal script only if there is no LIVE DJ, because the live DJ is already using processing
And then there is double processing on the stream, which is not desirable.
my question is it possible with liquidsoap / azuracast to disable the script during live ?

**Comment by Vaalyn** [comment]
You can add the script to your LS config in the `4th` text area on the `Edit Liquidsoap Configuration` instead of in the last one to apply this before the live source is mixed into the final stream. This would be the box directly after `radio = crossfade(...`.
