### ISSUE TITLE
No "Today" Report When Unique Listeners Over 3,000

### ISSUE THREAD

**Issue by buddhatunes** [AzuraCast/AzuraCast#3753]
**Using Docker installation method**

Yes
**AzuraCast version**

Rolling Release #ac28dfb
**Host Operating System**

Ubuntu 20.04
**Describe the bug**

I updated twice in the last several weeks, and noticed that I no longer can get a unique listener report when the daily listeners exceed 3,000. 
**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by buddhatunes** [comment]
I had 6 crashes in the last 24 hours since I upgraded to the latest stable version. I upgraded from 4GB RAM to 8GB RAM and everything seems stable now. I can now access daily reports from 3000+ listener days, but it still takes a couple minutes for the report to display.

I ran "docker-compose logs web" but not sure what I am looking for there.

See graph below of memory issues in last 24 hours since upgrade to stable release.

![memory](https://user-images.githubusercontent.com/2067407/106726892-e2f54c00-65d8-11eb-8d47-a4703a2eec7b.png)

**Comment by cristianbejenariu** [comment]
There might be a configuration problem. I'm having the same problem when selecting a Report for the last 30 days for example. 
Here's my log entry:

web_1                      | 2021/02/03 10:27:05 [error] 48#48: *527759 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/azuracast/www/vendor/symfony/cache/Traits/RedisTrait.php on line 324" while reading response header from upstream, client: 172.19.0.4, server: localhost, request: "GET /api/station/4/listeners?start=2021-01-05&end=2021-02-03 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "azura.dotwhite.ro", referrer: "https://azura.dotwhite.ro/station/4/reports/listeners"
web_1                      | [2021-02-03T10:27:16.595128+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data {"force":false} []

I tried changing the PHP max execution time from azuracast.env but it doesn't fix the problem.

Any ideas?

**Comment by buddhatunes** [comment]
I spoke too soon previously. While I can get a report up to appx. 3,100 daily listeners, anything after that will not display.

**Comment by buddhatunes** [comment]
Since I know it is not a memory issue now, how do I change the timeout limits?

**Comment by cristianbejenariu** [comment]
I second this question.

# PHP's maximum script execution time (in seconds).
# PHP_MAX_EXECUTION_TIME=30

This value does not seem to have any effect. 
Please advise.

**Comment by SlvrEagle23** [comment]
If your script is running long on execution time, you can do the steps outlined below:

Open `azuracast.env` on your host computer, add or modify the line that looks like this:

```
# PHP_MAX_EXECUTION_TIME=30
```

to look like this:

```
PHP_MAX_EXECUTION_TIME=300
```

(or higher than 300 if you want), then running:

```
docker-compose down
docker-compose up -d
```

**Comment by cristianbejenariu** [comment]
I tried doing setting that flag to 6000 and unfortunately it doesn't seem to work. 
Maybe a nginx timeout limit must be increased also? 
Is it maybe a bug?

Thanks!

**Comment by buddhatunes** [comment]
Cristian, just curious, did you docker-compose down and up afterwards?

**Comment by cristianbejenariu** [comment]
I did not. I restarted the entire virtual machine. I figured it's safer.

**Comment by Vaalyn** [comment]
@cristianbejenariu you will need to manually restart via `docker-compose down` & `docker-compose up -d` or it will use the previously parsed configuration.

**Comment by buddhatunes** [comment]
@Vaalyn will "docker-compose down" & "docker-compose up -d" disrupt the current playing stream and lose current listeners?

**Comment by Vaalyn** [comment]
@buddhatunes yes, shutting down the containers will stop all services of AzuraCast. When it is started again audio players should automatically re-connect but not all players do that.

**Comment by cristianbejenariu** [comment]
> @cristianbejenariu you will need to manually restart via `docker-compose down` & `docker-compose up -d` or it will use the previously parsed configuration.

Thanks for the hint. I will try it tonight, outside peak listeners times.

**Comment by cristianbejenariu** [comment]
That worked. Thank you very much!

**Comment by buddhatunes** [comment]
It seems to be working for me so far, will know for sure this weekend

**Comment by buddhatunes** [comment]
problem solved :)
