### ISSUE TITLE
Upcoming Song Queue is programing same song twice

### ISSUE THREAD

**Issue by hecgua** [AzuraCast/AzuraCast#3758]
**Using Docker installation method**
Yes

**AzuraCast version**
Powered by AzuraCast • Rolling Release #b8d4570 (2021-01-30 20:17)

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
Upcoming Song Queue is programing same song twice and Liquid Soap plays twice the songs.

**Expected behavior**
Not to list the same song twice

**Screenshots**
![Screenshot_83](https://user-images.githubusercontent.com/58102945/106701314-0fdf3a00-65ac-11eb-9bdc-f7c07147ab19.png)

**Additional context**
No special configure on Liquidsoap. The station has more than a thousand songs on 6 playlists, some playlists are configured with playlist weight and some others are configured to play songs once every X songs. I have a default playlist configured with playlist weight. Avoid Duplicate Artists/Titles is marked on all playlists.

**Comment by Abqehebter** [comment]
Same Problem: https://github.com/AzuraCast/AzuraCast/issues/3682

**Comment by SlvrEagle23** [comment]
Follow issue #3682 for updates.
