### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by mikemlp2021** [AzuraCast/AzuraCast#3761]
I'm on the latest version of Azuracast and after updating today, when clicking on Playlists, it throws up a 500 error: - Call to undefined method App\Environment::enableAdvancedFeatures()index.js.phtml

Advanced Features are enabled. 

Thanks,

Mike

**Comment by SlvrEagle23** [comment]
@mikemlp2021 Thank you for the report; this should be fixed in the latest Rolling Release version that is being deployed shortly.
