### ISSUE TITLE
The "skip song" stopped working 

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#3763]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #bd5b717 (2021-02-03 19:10)

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
When I click the "Skip song" button on profile page, and  "Skip song" confirmation, nothing happens and the current song just keeps playing instead of skipping to the next song

**Comment by SlvrEagle23** [comment]
@eranwo Should be fixed in the latest Rolling Release being deployed right now (should be available to your installation in about 5-10 minutes).
