### ISSUE TITLE
Could not access Icecast ports (self-signed certificate)

### ISSUE THREAD

**Issue by lramilo** [AzuraCast/AzuraCast#3764]
**Using Docker installation method**

Yes

**AzuraCast version**

Rolling Release #cabeeb5 (2021-02-03 4:17) • Docker • PHP 7.4

**Host Operating System**

Ubuntu 20.04 (LTS) x64

**Describe the bug**

When accesing directly to Icecast ports using both HTTP or HTTPS, it returns a certificate error, because it's forcing HTTPS and using a self-signed "localhost" certificate. On previous versions, I was able to access the port directly to bypass Nginx proxy as I am doing some stress-testing. 

This problems also seems to cause a streamer not being able to connect directly to a mountpoint when AutoDJ is disabled for the station or for this mountpoint. These types of mountpoints are useful when some customer asks for no transcoding while using low bitrate upstreams as AAC+ @ 48 Kbps, or when customers want to be able to monitor DJs before going live, instead of using Liquidsoap harbor to schedule live shows.

**Comment by YosefAdPro** [comment]
You can put hare your docker-compose.override.yml file?

**Comment by Abqehebter** [comment]
Yee I wanted to ask the same thing, on what port the web server then runs. I made it easy, started the webserver on port 80 and 443, then created the certificate and changed the port to XYZ again.

**Comment by lramilo** [comment]
@YosefAdPro I'm testing on a clean installation as described on #3702; so I don't have a docker-compose.override.yml

**Comment by YosefAdPro** [comment]
Create a `docker-compose.override.yml` file in /var/azuracast directory and paste:


``` yaml

version: '2.2'

services:

  stations:
    volumes:
      -/SSL_FILE_LOCATION.crt:/etc/nginx/certs/default.crt:ro
      -/SSL_FILE_LOCATION.key:/etc/nginx/certs/default.key:ro

 ```

Change SSL_FILE_LOCATION to the location of the certificate folder.


run
`docker-compose down 
`and
`docker-compose up -d
`

**Comment by SlvrEagle23** [comment]
@lramilo Are you using a certificate generated by LetsEncrypt via the nginx proxy service? If you are, once the certificate is assigned, you should restart broadcasting (via `Utilities` > `Restart Broadcasting`) and it should assign the same SSL certificate used for your main domain to Icecast itself.

**Comment by lramilo** [comment]
@SlvrEagle23 in this test, I was used the certificate generated by the AzuraCast suite (using LetsEncrypt) I'll try what you mentioned if I find again the same issue, thanks a lot !

**Comment by Vaalyn** [comment]
Since there have been no further replies and I don't see anything that we can further debug I'm closing this issue.

If you are still seeing this problem please let us know.
