### ISSUE TITLE
Feature request: Let us change the error.mp3 file in the config.

### ISSUE THREAD

**Issue by TheVingard** [AzuraCast/AzuraCast#377]
^

**Comment by SlvrEagle23** [comment]
@TheVingard Bear in mind, the Icecast error sound is literally only intended for a situation when the entire broadcasting stack ahead of that has failed or has yet to be configured, such as for a brand new installation. During normal operation, LiquidSoap will always preempt the error message.

In any event, if you don't like the sound of my voice _that much_, then you can always just set another "fallback mount" URL for Icecast to use instead. You can configure this in the Mount Points configuration section for the station. The actual contents of `error.mp3` itself can't be changed from within the web app, as the file is located outside the directories that AzuraCast writes to.
