### ISSUE TITLE
Added possibility to allocate disk space for the user

### ISSUE THREAD

**Issue by pawel06281990** [AzuraCast/AzuraCast#3770]
Hello, A nice function would be to add the ability to assign a given user the disk surface because now the entire disk surface is shown.

Thank you in advance for considering my request because I was looking for such a polo and it is not there :(

**Comment by Vaalyn** [comment]
You can already give a station a storage quota when editing their storage location:

![image](https://user-images.githubusercontent.com/13745863/106939295-5d7cb380-6720-11eb-9ecc-62ac1dab7689.png)

**Comment by pawel06281990** [comment]
Thank you for your help and I found it in the whole panel.
