### ISSUE TITLE
Feature request: Playlist fixes and improvements

### ISSUE THREAD

**Issue by vingard** [AzuraCast/AzuraCast#378]
Hi, I found a few bugs for the playlist system and came up with a few ideas.

1. On the playlist page where you can see all playlists daily playlists all say 'Once per Day Plays at 12:00 AM' even if they are scheduled to play at another time than 12:00 AM.

**Comment by SlvrEagle23** [comment]
@TheVingard As a friendly reminder, GitHub issues track the progress and completion of a single bug report or enhancement request. It's not possible to separately track the progress of multiple list items if they're in the same issue, so they should always be submitted as separate issues.

This issue can represent the first bug report item, but please resubmit the other list items as their own issues.

Keep in mind that the main playlists page will always show the playlist times relative to your own local time zone, which is set in your profile ("My Account" on the top right menu).

**Comment by TheVingard** [comment]
Sorry about this, I'll edit the OP now. I have checked that the time is set correctly, but it always fails to play at the correct time and no matter what I enter on the playlist page it displays 'Plays at 12:00 AM'

**Comment by SlvrEagle23** [comment]
@TheVingard There was an error, fixed earlier this week, where the wrong fields were showing when you selected which type of playlist you wanted to use. Try going in and specifying the date using the updated fields, and it should work again. Sorry for the trouble.
