### ISSUE TITLE
Shuffled & Random playlists plays sequential

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#3781]
**Using Docker installation method**
Yes.

**AzuraCast version**
Rolling Release #92910d7 (2021-02-09 6:34)

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
I don't know if it's intentional, because Shuffle only shuffles the playlist once. But as far as I know, it "actually" repeats after the playlist has been played through.
But that is not the case here. It repeats probably exactly the same list, as a "few" hours before.

**Screenshots**
13:30-14:00:
![bug_1](https://user-images.githubusercontent.com/42640247/107119140-e103e500-6885-11eb-9acc-46ea941ee664.jpg)

04:00-04:30:
![bug_2](https://user-images.githubusercontent.com/42640247/107119144-e3fed580-6885-11eb-85f3-45de68cd48a1.jpg)

**Comment by leo269n** [comment]
Occurs in exactly the same way for me. The playlist is random but repeats itself over and over again.
with the Rolling Release #4eeb725 (2021-02-06 2:42)

**Comment by Abqehebter** [comment]
@SlvrEagle23 It may be that my "period to avoid repetition" was a bit too high. I have now reduced this considerably. I'll analyze whether the playlist can shuffle better now.

**Comment by Abqehebter** [comment]
OK it still seems like the AutoDJ occasionally has a clean sequence that it has to follow, but it shouldn't. Not always and also not 1 to 1 but already close together.

**Comment by Abqehebter** [comment]
I suppose I have found the error on my end. The playlist priority (weight) was still set to 3 everywhere - also the period for repetition avoidance (as described above) was apparently set too high for me. Double artists I currently also no longer see, if very rarely and then but with distance.

Should I notice something again, I write it here again purely!
