### ISSUE TITLE
Is python-mysqldb really important?

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#3782]
**Using Docker installation method**
No

**AzuraCast version**
--uptating right now to last one

**Host Operating System**
Ubuntu 20.04 LTS

**Describe the bug**
I've got errors while updating right now, during Liquidsoap installation.
But in the beginning I've got:
```
Package python-mysqldb is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-mysqldb' has no installation candidate
```
Is this is something important? Because there is no package for raspberry pi yet.

**Device(s):**
 - Device: Raspberry Pi B+

**Comment by SlvrEagle23** [comment]
@NicoxDJ It's needed by Ansible (which is a Python program) to directly access the MariaDB database to make the changes it makes during the setup process.

**Comment by NicoxDJ** [comment]
@SlvrEagle23 There is no `python-mysqldb` in the Ubuntu 20.04 repos, there is only `python3-mysqldb`

**Comment by SlvrEagle23** [comment]
@NicoxDJ Looking at the installer script, it actually appears to be checking to see if you're on Ubuntu Focal Fossa (i.e. 20.04 LTS) and instead runs:

```bash
sudo apt-get install -q -y ansible python3-pip python3-mysqldb
```

which would work correctly on 20.04.

If you look at the contents of `/etc/lsb-release` on your device, what do you see? Is it reporting something different from the standard?

**Comment by NicoxDJ** [comment]
@SlvrEagle23 Hm, yes, actually it's `Ubuntu 20.04.2 LTS`

**Comment by SlvrEagle23** [comment]
@NicoxDJ Specifically though, what does `/etc/lsb-release` say? It should have a `CODENAME` variable, and that's what we're checking for that.

**Comment by NicoxDJ** [comment]
@SlvrEagle23 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```

**Comment by SlvrEagle23** [comment]
@NicoxDJ Okay, so then definitely this line in `./install.sh` should be installing the Focal dependencies instead:

```bash
if [[ $DISTRIB_CODENAME == "focal" ]]; then
        sudo apt-get install -q -y ansible python3-pip python3-mysqldb
```

**Comment by NicoxDJ** [comment]
@SlvrEagle23 Check `update.sh`. There are these lines that are running

**Comment by SlvrEagle23** [comment]
@NicoxDJ Ah yep, the update script is running different code than the install script. I've updated both so they run identical code to ensure you're on the latest version of Ansible before running Ansible tasks.

**Comment by NicoxDJ** [comment]
Yes, now it's fine ^_^ Thanks!
