### ISSUE TITLE
No duration time on API and public page after skip song

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#3784]
**AzuraCast version**
Rolling Release #4eeb725 (2021-02-06 2:42)

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
From time to time i'm getting a song without `duration` and `remaining` time this issue occurs most when doing "`skip song`" 
```
},
now_playing: {
elapsed: 198,
remaining: 0,
sh_id: 6863,
played_at: 1612685805,
duration: 0,
playlist: "default",
streamer: "",
is_request: false,
song: {
id: "e3310b88f603afca09834222ebe1efae",
text: "U2 - Beautiful Day",
artist: "U2",
title: "Beautiful Day",
album: "",
genre: "",
lyrics: "",
art: "http://coverartarchive.org/release/61748ffb-9e82-49db-9018-c9c061c40f18/4859680722-500.jpg",
custom_fields: {
composer: null,
publisher: null,
title: null,
track_number: null,
year: null
}
}

```
![u2](https://user-images.githubusercontent.com/2701228/107141271-53310400-6930-11eb-8622-f098982ed9c9.JPG)

**Comment by NicoxDJ** [comment]
I have the same problem. Apparently is a known issue by the Dev team.
In my case i don't have even Artwork :(
Will wait till the devs find out how to handle this.

**Comment by eranwo** [comment]
@NicoxDJ 
I have not seen this behavior in previous versions.

**Comment by asa767** [comment]
I have the same issue.

**Comment by leo269n** [comment]
I currently have the same problem.
Debian 10
Rolling Release #4eeb725 (2021-02-06 2:42)

**Comment by jranby** [comment]
Same issue

**Comment by WillSykesDJ** [comment]
I have a similar issue when my playlist is set to interrupt current song. No duration info or album art is displayed.

**Comment by eranwo** [comment]
@Vaalyn The error still exist even in the last version -Rolling Release #e3d105f (2021-03-03 9:00)
I've updated Azuracast and immediately checked the `skip song`.

Actually when using `skip song` the player goes completely crazy.
1. Getting random song 
2. No duration time
3. Sometimes the song title is not the song that actually playing

I must remark that this problem was not exist before, and appeared only in the latest versions.
It's a serious issue that affects the reliability of the software. Is it possible to do something to fix this?

**Comment by Vaalyn** [comment]
Take a look at the in-depth explanation of the underlying issue here: https://github.com/AzuraCast/AzuraCast/issues/3673#issuecomment-771214132

We are aware of it but haven't found a good solution for this yet.

**Comment by Vaalyn** [comment]
We have done some updates with how songs are matched so any remaining issues with the metadata are most likely due to the problem with skipping songs. More information about that can be found in https://github.com/AzuraCast/AzuraCast/issues/3821 which we will use to further track the progress on fixing this behavior so I'll close this one here and recommend you to follow that issue.
