### ISSUE TITLE
Crazy Queue Clock

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#3785]
**Using Docker installation method**
Yes.

**AzuraCast version**
Rolling Release #92910d7 (2021-02-09 6:34)

**Host Operating System**
Ubuntu 20.04 & Debian 10

**Describe the bug**
I'll describe the error in a separate issue to separate it better. (Old Issue: #3776)
On both host systems of mine the clock in the queue jumps sometimes forward and sometimes back, which should not be the case.

I found out that sometimes already played tracks are listed again in the queue at position 1, but probably not really played. (Example in the screenshots)

As soon as I restart the station, the queue of songs already continues into the future. So the scheduling doesn't really seem to work.

**Screenshots**
Repeating Songs:
![image](https://user-images.githubusercontent.com/42640247/107153082-ee939a80-696b-11eb-9a5d-ab1686d94040.png)
History:
![image](https://user-images.githubusercontent.com/42640247/107153098-023f0100-696c-11eb-817e-1dbbed518fd8.png)

General:
![image](https://user-images.githubusercontent.com/42640247/106858855-8e2e0000-66c2-11eb-8ae7-0e28366f1498.png)

**Comment by SpeedyCharly** [comment]
Also have noted this issue on my setup >> usually happens in the interleave between 2 live streamers

**Comment by bjarn** [comment]
Also happening here since 1 week ago after I updated, only noticed it yesterday. Difference here is an entire hour.

**Comment by SlvrEagle23** [comment]
This should be significantly resolved in the latest rolling-release version. The AutoDJ queue has grown so complicated in some areas that I can't even keep it all in my own head at once, so every time I go in to fix an issue like this I also look for ways to simplify the queue so it goes through less code and is more predictable. This should help both in the immediate term with this fix and in the long term with future improvements.

**Comment by Abqehebter** [comment]
@SlvrEagle23 Does this also fix error #3781 or is that separate again? I will install it right away.

**Comment by SlvrEagle23** [comment]
@Abqehebter That is a different issue from this one.

**Comment by bjarn** [comment]
Great! That was quick, thank a ton @SlvrEagle23
