### ISSUE TITLE
External sources in playlists stopped working

### ISSUE THREAD

**Issue by NadjaNeville** [AzuraCast/AzuraCast#3786]
<!--
Hello!

Since the last update my playlists containing external sources "direct stream URL" stopped working. Liquidsoap quits with the log entry:
`2021/02/08 01:41:15 [http_38700:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!`

I am using the docker installation and other stations using a song based playlist run fine. The Issue appeared after the last update yesterday.

**Comment by Vaalyn** [comment]
Please follow our issue template for reporting bugs.

We have no information to work with here.
