### ISSUE TITLE
Feature request: Allow web section of AzuraCast to be hosted on subdomains or directories. 

### ISSUE THREAD

**Issue by TheVingard** [AzuraCast/AzuraCast#379]
This would be useful as most people will want to setup a web server for themselves.

**Comment by SlvrEagle23** [comment]
@TheVingard AzuraCast can already be served on a subdomain without any issue. Just set the base URL to be the subdomain, and everything will route correctly.

As for subfolders, while this is possible programmatically, this introduces a whole unnecessary complexity in how we parse the base URL when using alternate ports (i.e. the radio ports, 8000-8999).

Given that in both of the distribution methods AzuraCast uses, it sets up and installs its own entire stack, from the webserver to database, storage and station software, it is intended to occupy its own domain or subdomain rather exclusively. It's possible to proxy its built-in nginx service's responses to another web server running it in a subdirectory, but this isn't supported officially.
