### ISSUE TITLE
Public player and admin dashboard showing 'Stream Offline'

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#3790]
**Using Docker installation method**
Yes  >>   Docker • PHP 7.4

**AzuraCast version**
 AzuraCast • v0.10.3, #9811fbb (2020-06-22 4:38)

**Host Operating System**
 Ubuntu 20.20)

**Describe the bug**
Public page, Azura player widget and Admin dashboard showing '**Stream offline**' when operator streaming live.  
Meanwhile 3rd party player and chatroom app on my website displaying correct metadata. What is going on here?

![Azur1](https://user-images.githubusercontent.com/66107794/107284887-66c19500-6a2c-11eb-979e-7042c63be6a9.jpg)
![Azur2](https://user-images.githubusercontent.com/66107794/107284893-688b5880-6a2c-11eb-9f58-71f117ef8bc3.jpg)
![Azur3](https://user-images.githubusercontent.com/66107794/107284897-6a551c00-6a2c-11eb-9be7-9d38eb24836e.jpg)

**Comment by SpeedyCharly** [comment]
[**EDIT**] The issue resolved itself over time with no action on my part.  But is there a way to prevent it reoccurring?

**Comment by YosefAdPro** [comment]
You have an old version, it is recommended to upgrade. 
you did not attach any log ... A similar issue has been resolved here in recent days.

https://github.com/AzuraCast/AzuraCast/issues/3771

**Comment by SpeedyCharly** [comment]
There seemed to be nothing untoward in the logs so I didn't see fit to include them.  There also were none of the error flags like those shown in the post you referred to (#3771).

As for upgrading, I am unsure of the correct procedure so I don't dare try it for fear of messing up and killing my radio.

**Comment by Gibacast** [comment]
Preciso de ajuda.

Não consigo reverter o problema: stream offline

**Comment by SpeedyCharly** [comment]
Translated message from **Gibacast**
Need help.

I can't reverse the problem: stream offline

**Comment by Vaalyn** [comment]
Regarding updating AzuraCast, you can find the update instructions here in our new documentation: https://docs.azuracast.com/en/getting-started/updates

In general you should create and download a backup of your AzuraCast installation before updating so that in the case something goes wrong you can restore your installation from the backup. Backups can be done via the administration pages. More about backup & restore can be found here: https://docs.azuracast.com/en/administration/backup-and-restore

**Comment by SpeedyCharly** [comment]
Thank you for this link Vaalyn, I shall thy my hand at this and, yes, I am quite aware of the procedure for backups, thanks for the reminder. I will close the ticket with this comment. Good luck to me!
