### ISSUE TITLE
External playlist sources stopped playing with last update

### ISSUE THREAD

**Issue by NadjaNeville** [AzuraCast/AzuraCast#3791]
**Using Docker installation method**
Yes 

**AzuraCast version**
Rolling Release #6ad1882 (2021-02-08 4:15) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 20.04.2

**Describe the bug**
Any playlist using an external source doesn't play. It played before the update flawlessly, now the backend stops and gets into "not running" mode after a couple minutes. The station is silent. The "playing" tab shows stream offline". Playlists using uploaded tracks on internal rotation work flawlessly.

**To Reproduce**
Go to Playlists
click on "edit"
click on "sources"
click on "external URL"
file in URL like: http://94.130.242.5:8056
click on "direct stream URL"
click "save"

**Expected behavior**
Expecting the stream to play with the URL of my station. The "playing" tab should display the metadata of the remote stream showing track name and artist.

**Relevant Logs**

**Liquidsoap log**

> 2021/02/08 04:51:07 [http_38700:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
> 2021/02/08 04:51:07 [lang:3] AutoDJ could not be initialized within the specified timeout.
> 2021/02/08 04:51:07 [main:3] Shutdown started!
> 2021/02/08 04:51:07 [main:3] Waiting for main threads to terminate...
> 2021/02/08 04:51:07 [local_1:3] Closing connection...
> 2021/02/08 04:51:07 [lang:3] DJ Source disconnected! Current live DJ: 
> 2021/02/08 04:51:07 [http_38700:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
> 2021/02/08 04:51:07 [http_38700:2] Feeding stopped: source stopped
> 2021/02/08 04:51:07 [server:3] New client: 172.18.0.5.
> 2021/02/08 04:51:07 [server:3] Client 172.18.0.5 disconnected.
> 2021/02/08 04:51:07 [lang:3] AzuraCast Live Disconnected Response: true
> 2021/02/08 04:51:07 [harbor:3] Removing mountpoint '/' on port 8115
> 2021/02/08 04:51:07 [harbor:3] Nothing more on port 8115: closing sockets.
> 2021/02/08 04:51:07 [clock.wallclock_main:3] Streaming loop stopped.
> 2021/02/08 04:51:07 [main:3] Threads terminated.
> 2021/02/08 04:51:07 [threads:3] Shutting down scheduler...
> 2021/02/08 04:51:07 [threads:3] Scheduler shut down.
> 2021/02/08 04:51:07 [threads:3] Waiting for queue threads to terminate...
> 2021/02/08 04:51:07 [threads:3] Queues shut down
> 2021/02/08 04:51:07 [server:3] Closing socket.
> 2021/02/08 04:51:07 [main:3] Cleaning downloaded files...
> 2021/02/08 04:51:07 [main:3] Freeing memory...

**Liquidsoap config**

> # WARNING! This file is automatically generated by AzuraCast.
> # Do not update it directly!
> 
> 
> set("init.daemon", false)
> set("init.daemon.pidfile.path","/var/azuracast/stations/valmoor_radio/config/liquidsoap.pid")
> set("log.stdout", true)
> set("log.file", false)
> set("server.telnet",true)
> set("server.telnet.bind_addr","0.0.0.0")
> set("server.telnet.port", 8114)
> set("harbor.bind_addrs",["0.0.0.0"])
> 
> set("tag.encodings",["UTF-8","ISO-8859-1"])
> set("encoder.encoder.export",["artist","title","album","song"])
> 
> setenv("TZ", "UTC")
> 
> azuracast_api_auth = ref "(PASSWORD)"
> ignore(azuracast_api_auth)
> 
> autodj_is_loading = ref true
> ignore(autodj_is_loading)
> 
> autodj_ping_attempts = ref 0
> ignore(autodj_ping_attempts)
> 
> playlist_valmoorish = mksafe(input.http(max=30., "http://www.partyviberadio.com:8056"))
> playlist_valmoorish = audio_to_stereo(id="stereo_playlist_valmoorish", playlist_valmoorish)
> playlist_valmoorish = cue_cut(id="cue_playlist_valmoorish", playlist_valmoorish)
> 
> # Standard Playlists
> radio = random(id="standard_playlists", weights=[3], [playlist_valmoorish])
> 
> # AutoDJ Next Song Script
> def autodj_next_song() =
>     uri = list.hd(get_process_lines(env=[("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/12/nextsong --form api_auth="$API_AUTH"'), default="")
>     log("AzuraCast Raw Response: #{uri}")
> 
>     if uri == "" or string.match(pattern="Error", uri) then
>         []
>     else
>         r = request.create(uri)
>         if request.resolve(r) then
>             [r]
>         else
>             []
>        end
>     end
> end
> 
> # Delayed ping for AutoDJ Next Song
> def wait_for_next_song(autodj)
>     autodj_ping_attempts := !autodj_ping_attempts + 1
>     delay = ref 0.5
> 
>     if source.is_ready(!autodj) then
>         log("AutoDJ is ready!")
> 
>         autodj_is_loading := false
>         delay := -1.0
>     elsif !autodj_ping_attempts > 200 then
>         log("AutoDJ could not be initialized within the specified timeout.")
> 
>         autodj_is_loading := false
>         shutdown()
> 
>         delay := -1.0
>     end
> 
>     !delay
> end
> 
> dynamic = request.dynamic.list(id="next_song", timeout=20., retry_delay=2., autodj_next_song)
> dynamic = audio_to_stereo(id="stereo_next_song", dynamic)
> dynamic = cue_cut(id="cue_next_song", dynamic)
> 
> dynamic_startup = fallback(
>     id = "dynamic_startup",
>     track_sensitive = false,
>     [
>         dynamic,
>         at(
>             fun()-> !autodj_is_loading,
>             blank(id = "autodj_startup_blank", duration = 120.)
>         )
>     ]
> )
> radio = fallback(id="autodj_fallback", track_sensitive = true, [dynamic_startup, radio])
> 
> ref_dynamic = ref dynamic;
> add_timeout(0.25,fun()->wait_for_next_song(ref_dynamic))
> 
> requests = request.queue(id="requests")
> requests = audio_to_stereo(id="stereo_requests", requests)
> requests = cue_cut(id="cue_requests", requests)
> 
> radio = fallback(id="requests_fallback", track_sensitive = true, [requests, radio])
> add_skip_command(radio)
> 
> # DJ Authentication
> live_enabled = ref false
> last_authenticated_dj = ref ""
> live_dj = ref ""
> 
> def dj_auth(auth_user,auth_pw) =
>     user = ref ""
>     password = ref ""
> 
>     if (auth_user == "source" or auth_user == "") and (string.match(pattern="(:|,)+", auth_pw)) then
>         auth_string = string.split(separator="(:|,)", auth_pw)
> 
>         user := list.nth(default="", auth_string, 0)
>         password := list.nth(default="", auth_string, 2)
>     else
>         user := auth_user
>         password := auth_pw
>     end
> 
>     log("Authenticating DJ: #{!user}")
> 
>     ret = list.hd(get_process_lines(env=[("DJ_USER", !user), ("DJ_PASSWORD", !password), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/12/auth --form dj-user="$DJ_USER" --form dj-password="$DJ_PASSWORD" --form api_auth="$API_AUTH"'), default="")
>     log("AzuraCast DJ Auth Response: #{ret}")
> 
>     authed = bool_of_string(ret)
>     if (authed) then
>         last_authenticated_dj := !user
>     end
> 
>     authed
> end
> 
> def live_connected(header) =
>     dj = !last_authenticated_dj
>     log("DJ Source connected! Last authenticated DJ: #{dj} - #{header}")
> 
>     live_enabled := true
>     live_dj := dj
> 
>     ret = list.hd(get_process_lines(env=[("DJ_USER", dj), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/12/djon --form dj-user="$DJ_USER" --form api_auth="$API_AUTH"'), default="")
>     log("AzuraCast Live Connected Response: #{ret}")
> end
> 
> def live_disconnected() =
>     dj = !live_dj
> 
>     log("DJ Source disconnected! Current live DJ: #{dj}")
> 
>     ret = list.hd(get_process_lines(env=[("DJ_USER", dj), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/12/djoff --form dj-user="$DJ_USER" --form api_auth="$API_AUTH"'), default="")
>     log("AzuraCast Live Disconnected Response: #{ret}")
> 
>     live_enabled := false
>     last_authenticated_dj := ""
>     live_dj := ""
> end
> 
> # A Pre-DJ source of radio that can be broadcast if needed',
> radio_without_live = radio
> ignore(radio_without_live)
> 
> # Live Broadcasting
> live = audio_to_stereo(input.harbor("/", id = "input_streamer", port = 8115, auth = dj_auth, icy = true, icy_metadata_charset = "UTF-8", metadata_charset = "UTF-8", on_connect = live_connected, on_disconnect = live_disconnected, buffer = 5.00, max = 10.00))
> ignore(output.dummy(live, fallible=true))
> 
> radio = fallback(id="live_fallback", replay_metadata=false, track_sensitive=false, [live, radio])
> 
> # Record Live Broadcasts
> stop_recording_f = ref (fun () -> ())
> 
> def start_recording(path) =
>     output_live_recording = output.file(%mp3(samplerate=44100, stereo=true, bitrate=192, id3v2=true), fallible=true, reopen_on_metadata=false, "#{path}", live)
>     stop_recording_f := fun () -> source.shutdown(output_live_recording)
> end
> 
> def stop_recording() =
>     f = !stop_recording_f
>     f ()
> 
>     stop_recording_f := fun () -> ()
> end
> 
> server.register(namespace="recording", description="Start recording.", usage="recording.start filename", "start", fun (s) -> begin start_recording(s) "Done!" end)
> server.register(namespace="recording", description="Stop recording.", usage="recording.stop", "stop", fun (s) -> begin stop_recording() "Done!" end)
> 
> # Allow for Telnet-driven insertion of custom metadata.
> radio = server.insert_metadata(id="custom_metadata", radio)
> 
> # Apply amplification metadata (if supplied)
> radio = amplify(override="liq_amplify", 1., radio)
> 
> radio = fallback(id="safe_fallback", track_sensitive = false, [radio, single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")])
> 
> # Send metadata changes back to AzuraCast
> def metadata_updated(m) =
>     def f() =
>         if (m["song_id"] != "") then
>             ret = list.hd(get_process_lines(env=[("SONG", m["song_id"]), ("MEDIA", m["media_id"]), ("PLAYLIST", m["playlist_id"]), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/12/feedback --form song="$SONG" --form media="$MEDIA" --form playlist="$PLAYLIST" --form api_auth="$API_AUTH"'), default="")
>             log("AzuraCast Feedback Response: #{ret}")
>         end
>         (-1.)
>     end
> 
>     add_timeout(fast=false, 0., f)
> end
> 
> radio = on_metadata(metadata_updated,radio)
> 
> # Local Broadcasts
> output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), id="local_1", host = "127.0.0.1", port = 8110, password = "(PASSWORD):#1", icy_id = 1, name = "xxxxxxx", description = "", genre = "Electronica", url = "https://secondlife.com/destination/valmoor", public = false, encoding = "UTF-8", protocol="icy", radio)
> 
> # Remote Relays

**Shoutcast log**

> 2021-02-09 00:53:31	INFO	*********************************************************************
> 2021-02-09 00:53:31	INFO	**        Shoutcast Distributed Network Audio Server (DNAS)        **
> 2021-02-09 00:53:31	INFO	**    Copyright (C) 2014-2019 Radionomy SA, All Rights Reserved    **
> 2021-02-09 00:53:31	INFO	*********************************************************************
> 2021-02-09 00:53:31	INFO	[MAIN] Shoutcast DNAS/posix(linux x64) v2.6.0.753 (Apr 25 2019)
> 2021-02-09 00:53:31	INFO	[MAIN] PID: 20638
> 2021-02-09 00:53:31	INFO	[MAIN] Saving log output to `/var/azuracast/stations/valmoor_radio/config/sc_serv.log'
> 2021-02-09 00:53:31	INFO	[MAIN] Automatic log rotation interval: 1 day
> 2021-02-09 00:53:31	INFO	[MAIN] Loaded config from `/var/azuracast/stations/valmoor_radio/config/sc_serv.conf'
> 2021-02-09 00:53:31	INFO	[MAIN] Calculated CPU count is 2 -> 1 CPU specified to be used
> 2021-02-09 00:53:31	INFO	[MAIN] Limited to 65536 file descriptors [relates to ulimit -n]
> [0;32m2021-02-09 00:53:31	DEBUG	ident is DIDCf465928ec16144c79230f03404a7b5e0-8110, DID is 968dff54444ba1e4b6dd64e6a2422702b5428ddc42f9d3e63e2550ae3797b5
> [0m2021-02-09 00:53:31	INFO	[MAIN] Starting 1 network thread
> 2021-02-09 00:53:31	INFO	[MICROSERVER] Listening for source and client connections on port 8110
> 2021-02-09 00:53:31	INFO	[MICROSERVER] Listening for legacy source connections on port 8111
> 2021-02-09 00:53:31	INFO	[MICROSERVER] Flash policy file server not enabled
> 2021-02-09 00:53:32	INFO	[SRC 127.0.0.1:48244 sid=1] Shoutcast 1 source connection starting.
> 2021-02-09 00:53:32	INFO	[SRC 127.0.0.1:48244 sid=1] stream detected MPEG v1 layer 3 stereo
> 2021-02-09 00:54:11	INFO	[DST xxx.xxx.xxx.xxx:53324 (xff) sid=1] HTTP client connection accepted. User-Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36', UID: 1, GRID: 1
> 2021-02-09 00:54:23	INFO	[DST xxx.xxx.xxx.xxx:53324 (xff) sid=1] HTTP client connection closed (12 seconds) [Bytes: 448053] Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36', UID: 1, GRID: 1
> [0;32m2021-02-09 00:55:12	DEBUG	[SRC 127.0.0.1:48244 sid=1] Remote socket closed while waiting for data.
> [0m2021-02-09 00:55:12	INFO	[SRC 127.0.0.1:48244 sid=1] Shoutcast 1 source disconnected.
> [01;31m2021-02-09 00:56:28	ERROR	[DST xxx.xxx.xxx.xxx:54866 (xff) sid=1] HTTP client connection rejected. Stream not available as there is no source connected. Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36'
> [0m

**Device(s):**
Tried it on Windows 10 using a Chrome browser

**Comment by NadjaNeville** [comment]
Enabling a timed schedule from 0:00 - 23:59 daily and ticking the first option, "cut other songs to play at scheduled time" in the advanced settings of the playlist lets the external source play for a couple minutes then Liquidsoap stops and in the logs you can find this:

> 2021/02/09 20:16:19 [http_38701:3] New metadata chunk: ? -- Shawn Mendes & Justin Bieber  - Monster.
> 2021/02/09 20:16:19 [http_38701:3] Buffer overrun: Dropping 0.01s. Consider increasing the max buffer size!
> 2021/02/09 20:16:19 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:16:22 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:16:24 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:16:27 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:16:29 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:16:32 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:16:34 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:16:37 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:16:39 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:16:42 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:16:44 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:16:47 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:16:49 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:16:52 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:16:54 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:16:57 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:16:59 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:17:02 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:17:04 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:17:07 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:17:09 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:17:12 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:17:14 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:17:17 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:17:19 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:17:22 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:17:24 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:17:27 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:17:29 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:17:32 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:17:34 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:17:37 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:17:39 [lang:3] AzuraCast Raw Response: 
> 2021/02/09 20:17:40 [lang:3] AutoDJ could not be initialized within the specified timeout.
> 2021/02/09 20:17:40 [main:3] Shutdown started!
> 2021/02/09 20:17:40 [main:3] Waiting for main threads to terminate...
> 2021/02/09 20:17:40 [local_1:3] Closing connection...
> 2021/02/09 20:17:40 [lang:3] DJ Source disconnected! Current live DJ: 
> 2021/02/09 20:17:40 [server:3] New client: 172.18.0.5.
> 2021/02/09 20:17:40 [server:3] Client 172.18.0.5 disconnected.
> 2021/02/09 20:17:40 [lang:3] AzuraCast Live Disconnected Response: true
> 2021/02/09 20:17:40 [harbor:3] Removing mountpoint '/' on port 8065
> 2021/02/09 20:17:40 [harbor:3] Nothing more on port 8065: closing sockets.
> 2021/02/09 20:17:40 [clock.wallclock_main:3] Streaming loop stopped.
> 2021/02/09 20:17:40 [http_38701:2] Feeding stopped: source stopped
> 2021/02/09 20:17:40 [main:3] Threads terminated.
> 2021/02/09 20:17:40 [threads:3] Shutting down scheduler...
> 2021/02/09 20:17:40 [threads:3] Scheduler shut down.
> 2021/02/09 20:17:40 [threads:3] Waiting for queue threads to terminate...
> 2021/02/09 20:17:40 [threads:3] Queues shut down
> 2021/02/09 20:17:40 [server:3] Closing socket.
> 2021/02/09 20:17:40 [main:3] Cleaning downloaded files...
> 2021/02/09 20:17:40 [main:3] Freeing memory...

**Comment by Cedric-Demarais** [comment]
Quite the same pb here, some of our playlists don't play at scheduled times, as other does. It was ok before update with exactly the same settings. Tryed other settings but with no results.

I have the same logs as NadjaNeville: plenty of empty azuracast raw response and no stream at all if i restart the station at the time of the non playing playlist. I have to force a song from media librairy to make the playlist play again. But on the next schedule it doesn't play.

**Comment by Vaalyn** [comment]
Is this still happening on the current version of AzuraCast?

**Comment by NadjaNeville** [comment]
The external streams play only if you go to advanced options and tick "interrupt other songs to play at scheduled time" which de facto hands over the playlist control to liquidsoap and renders the "Streamers/DJs" option unusable.

[https://i.gyazo.com/19212a87f2c48383114bb536e0e32b98.png](url)

It would be a great success if the functionality could be restored.
