### ISSUE TITLE
Writing metadata to file wrongly assumes all media formats can contain id3 metadata

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#3798]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #be301df (2021-02-10 5:16)

**Host Operating System**
Ubuntu 20.04 LTS

**Describe the bug**
The `GetId3MetadataService` currently always sets the metadata formats that the getId3 library should write to file as `['id3v1', 'id3v2.3']`. This assumes that every media format does support id3 / that getId3 does support writing id3 data for all media formats. This assumption does not hold up though.

As far as I was able to find out getId3 does support the following:
- mp3, mp2, mp1
  - id3v1, id3v2.3, ape

- mpc
  - ape

- ogg (vorbis)
  - vorbiscomment

- flac
  - metaflac

- real
  - real

**To Reproduce**
- Upload a file were id3 is not supported according to the list above
- Edit Media File in web interface
- Look for the error `Tag format "id3v1" is not allowed on ...` in the AzuraCast Application Log

**Expected behavior**
Writing metadata to file should take into account which formats support id3 and set the format(s) as specified above for the writer. For formats that are not explicitly supported the writing to file should be skipped in general I think.

**Relevant Logs**
AzuraCast.ERROR: Tag format "id3v1" is not allowed on "wav.wav" files {"exception":"[object] (App\\Exception\\CannotProcessMediaException(code: 0): Tag format \"id3v1\" is not allowed on \"wav.wav\" files at /var/azuracast/www/src/Exception/CannotProcessMediaException.php:43)"} []

**Device(s):**
 - Device: Desktop
 - OS: macOS 10.15
 - Browser: Chrome
 - Version: 88

**Comment by SlvrEagle23** [comment]
This should be improved in the latest rolling release, which won't try to write an unsupported format and will write the proper format for the given file's extension.

**Comment by Marabon** [comment]
I'm still seeing an error for this:
`App\Exception\CannotProcessMediaException at /var/azuracast/www/src/Exception/CannotProcessMediaException.php L43: Tag format "id3v1" is not allowed on "flac.flac" files`

Powered by AzuraCast • Rolling Release #8d1d127 (2021-04-18 8:26) • Docker • PHP 7.4

**Comment by Vaalyn** [comment]
@Marabon could you provide me with the file that you encountering this problem with?

**Comment by Marabon** [comment]
@Vaalyn This is the file: https://bit.ly/32oybrE

I even tried to delete it and reupload it to Azura but it gives the same error.

**Comment by Vaalyn** [comment]
@Marabon I've found the cause of this and I'm working on a fix for it 👍

**Comment by Marabon** [comment]
Thanks, confirmed working well.
