### ISSUE TITLE
Error in Setup

### ISSUE THREAD

**Issue by bishalbaishya** [AzuraCast/AzuraCast#380]
There's an error in Install In ubuntu 16 LTS Xenial version.

Error Details:

TASK [azuracast-db-install : Remove anonymous users] ***************************
failed: [localhost] (item=DELETE FROM mysql.user WHERE User='') => {"changed": false, "cmd": ["mysql", "--defaults-extra-file=/root/.my.cnf", "-ne", "DELETE FROM mysql.user WHERE User=''"], "delta": "0:00:00.885761", "end": "2018-01-15 11:48:21.160517", "item": "DELETE FROM mysql.user WHERE User=''", "msg": "non-zero return code", "rc": 1, "start": "2018-01-15 11:48:20.274756", "stderr": "ERROR 1142 (42000) at line 1: DELETE command denied to user 'azuracast'@'localhost' for table 'user'", "stderr_lines": ["ERROR 1142 (42000) at line 1: DELETE command denied to user 'azuracast'@'localhost' for table 'user'"], "stdout": "", "stdout_lines": []}

**Comment by SlvrEagle23** [comment]
@bishalbaishya Are you installing this on a clean VPS with nothing else installed on it yet? Errors like this tend to happen if MySQL/MariaDB was already set up beforehand, and then the installer tries to set it up again, causing problems.

If you want to run AzuraCast alongside existing software, I highly recommend using the Docker installation method.

**Comment by bishalbaishya** [comment]
I tried again with docker. The traditional Install sometimes causes problems. This error was in traditional install method.
