### ISSUE TITLE
Technical Change: Renaming `master` Branch to `main`

### ISSUE THREAD

**Issue by SlvrEagle23** [AzuraCast/AzuraCast#3800]
Hello all!

Following along with a number of Git repositories and in an effort to [be more inclusive](https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main), we are renaming our `master` branch across all of our repositories to `main`.

For a majority of our users, especially those on the Docker deployment method, this will have no noticeable impact on day-to-day operations or updates.

For our Ansible users, you may encounter issues trying to update your installation now that the remote branch name is different from your local version. In order to resolve this, you can run the following commands in a terminal:

```bash
cd /var/azuracast/www
git branch -m master main
git fetch origin
git branch -u origin/main main
```

If you have any other questions or encounter any issues with this change, please reply to this thread and let us know.

**Comment by ogrenci01** [comment]
Hi @SlvrEagle23 

I updated for Ubuntu 18.04 LTS Ansible without any problem. Thank you.

Current version: **Rolling Release #648c348 (2021-02-12 4:30) • Ansible • PHP 7.4**
