### ISSUE TITLE
Install issues with building LiquidSoap

### ISSUE THREAD

**Issue by eddiejibson** [AzuraCast/AzuraCast#381]
Hi,

I am trying to install AzuraCast on Ubuntu 16.04 via the install script as I don't have enough memory to install Docker. There is an error, however - Liquid Soap build fails.

Here's the install logs: https://pastebin.com/zup8npnJ

Any ideas?

Thank-you.

**Comment by SlvrEagle23** [comment]
@eddiejibson We recently had this same problem with our Docker container build, and I had meant to apply the solution to the traditional install script once it had been shown to work, but it slipped my mind.

If you update, LiquidSoap should build without any problems.

**Comment by SlvrEagle23** [comment]
@eddiejibson It appears you actually don't have enough memory to run the installer properly.

It may be possible to create a swap space to alleviate the memory issue, using a series of commands like these:

```bash
fallocate -l 2G /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
echo "/swapfile   none    swap    sw    0   0" >> /etc/fstab
```

**Comment by SlvrEagle23** [comment]
@eddiejibson I haven't heard any follow-up on this issue, so I don't know if the issue has been fixed or if further action is required on my end. If you don't mind, could you please update me on the status of this issue?

If I don't hear any updates for a while, I'll close the issue as resolved.
