### ISSUE TITLE
"502 Incorrect gateway" problem after upgrade, mariadb cyclic restarting

### ISSUE THREAD

**Issue by kemecs** [AzuraCast/AzuraCast#3810]
Using Docker installation method
Yes

AzuraCast version
Can't access the web interface because mariadb

Host Operating System
Ubuntu 20.04

Describe the bug
MariaDB is failing to start up... dunno much more than that. Tried updating the script and pulling the latest container images.

To Reproduce
No idea. Was working recently, not sure when/why it isn't now.

Expected behavior
Should work?

Relevant Logs

after yesterday's last update, my plow won't start mariadb_1 container

radio@folktest:~/azuracast$ docker-compose ps
Name Command State Ports
azuracast_mariadb_1 dockerize -template /tmp/d ... Restarting
azuracast_nginx_proxy_1 /app/docker-entrypoint.sh ... Up

radio@folktest:/azuracast$ docker-compose logs -f mariadb
.....
mariadb_1 | 2021/02/10 12:57:16 Command exited with error: exit status 1
mariadb_1 | 2021-02-10 12:58:19+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.8+mariafocal started.
mariadb_1 | 2021-02-10 12:58:20+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mariadb_1 | 2021-02-10 12:58:20+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.8+mariafocal started.
mariadb_1 | 2021-02-10 12:58:21 0 [Note] mysqld (mysqld 10.5.8-MariaDB-1:10.5.8+mariafocal) starting as process 12 ...
mariadb_1 | 2021-02-10 12:58:21 0 [Note] InnoDB: Using Linux native AIO
mariadb_1 | 2021-02-10 12:58:21 0 [Note] InnoDB: Uses event mutexes
mariadb_1 | 2021-02-10 12:58:21 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1 | 2021-02-10 12:58:21 0 [Note] InnoDB: Number of pools: 1
mariadb_1 | 2021-02-10 12:58:21 0 [Note] InnoDB: Using generic crc32 instructions
mariadb_1 | 2021-02-10 12:58:21 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
mariadb_1 | 2021-02-10 12:58:21 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
mariadb_1 | 2021-02-10 12:58:21 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1 | 2021-02-10 12:58:21 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_1 | 2021-02-10 12:58:21 0 [ERROR] InnoDB: Upgrade after a crash is not supported. The redo log was created with MariaDB 10.4.13.
mariadb_1 | 2021-02-10 12:58:21 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
mariadb_1 | 2021-02-10 12:58:21 0 [Note] InnoDB: Starting shutdown...
mariadb_1 | 2021-02-10 12:58:21 0 [ERROR] Plugin 'InnoDB' init function returned error.
mariadb_1 | 2021-02-10 12:58:21 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
mariadb_1 | 2021-02-10 12:58:21 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1 | 2021-02-10 12:58:21 0 [ERROR] Unknown/unsupported storage engine: InnoDB
mariadb_1 | 2021-02-10 12:58:21 0 [ERROR] Aborting
mariadb_1 | 2021/02/10 12:58:21 Command exited with error: exit status 1

I just did that:

docker-compose stop
docker-compose up -d mariadb
docker-compose stop mariadb
docker-compose start

has not improved:

radio@folktest:~/azuracast$ docker-compose ps
Name Command State Ports
azuracast_mariadb_1 dockerize -template /tmp/d ... Restarting
azuracast_nginx_proxy_1 /app/docker-entrypoint.sh ... Up 0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp

this does not indicate the solution:

https://github.com/AzuraCast/AzuraCast/issues/3441

how to fix it?

**Comment by Vaalyn** [comment]
Here is what I wrote for another user on Discord who encountered the same issue:

> From my understanding of the error the DB crashed while using MariaDB 10.4. Was then not restarted with the same MariaDB version so that it can recover from the redo log files but was updated to 10.5 which now is not able to handle the old redo log format (in 10.5 they changed that format).
>
>A post on the mariadb website and the archlinux forum says that renaming the `ib_logfile0` (and if there are more `ib_logfile*` files those too) and then starting the db again should work.
>
>You can find those files here: `/var/lib/docker/volumes/azuracast_db_data/_data`
>
>Stop your AC via docker-compose down, then try renaming them via `mv ib_logfile0 ib_logfile0.old` and after that run the update again.

**Comment by kemecs** [comment]
Yes! :)
I solved it

cd azuracast/
docker-compose stop
sudo mv /var/lib/docker/volumes/azuracast_db_data/_dataib_logfile0 /var/lib/docker/volumes/azuracast_db_data/_dataib_logfile0_old
sudo mv /var/lib/docker/volumes/azuracast_db_data/_dataib_logfile1 /var/lib/docker/volumes/azuracast_db_data/_dataib_logfile1_old
./docker.sh update-self
./docker.sh update

thx
