### ISSUE TITLE
Cant delete file with the api despite a positive response (200)

### ISSUE THREAD

**Issue by gwado** [AzuraCast/AzuraCast#3813]
**Using Docker installation method**
Yes

**AzuraCast version**
V0.12 Stable

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
Hello,

I use the api to update folders containing mp3s. These folders are linked to playlists.
My script removes mp3s from some folders and sends mp3s to other folders.
Unfortunately, if the mp3s seem to be deleted, they always come back.
Uploading via api works well.
Deleting via the web interface is ok too.

Testing via swagger for exemples, here are some screenshots to show you the steps.

The api returns me success for deletion.
![The api returns me success for deletion.](https://user-images.githubusercontent.com/54929707/107863186-696c2200-6e52-11eb-8622-28da6dc2ae1f.png)

The file is not physically deleted but seems to have disappeared from the database. The file ID will be change.
![The file is not physically deleted but seems to have disappeared from the database.](https://user-images.githubusercontent.com/54929707/107863190-6ec96c80-6e52-11eb-9cfe-552bf4ab1aa2.png)

Then the system re-reads the metadata and the file reappears completely.
![Then the system re-reads the metadata and the file reappears completely.](https://user-images.githubusercontent.com/54929707/107863193-72f58a00-6e52-11eb-92ac-a70eb479a595.png)

Same bug on version 0.11.2.
The 0.10.3 seems ok.

I can tell you more if you tell me how. I'm not very good at accessing containers dockers and retrieving the right information.
(sorry for my bad english)

**Comment by SlvrEagle23** [comment]
@gwado Thank you for the report; I've found the cause of this problem and the fix is pushing out to our Rolling Release branch in the next few minutes.

**Comment by gwado** [comment]
@SlvrEagle23 It works perfectly, thanks!
