### ISSUE TITLE
Update AzureCast or Letsencrypt stopped working

### ISSUE THREAD

**Issue by tanotar** [AzuraCast/AzuraCast#3816]
Hello friends. I tell you that today I have updated the Azurecast panel based on these commands ^cd/var/azuracast - ./docker.sh update-self and ./docker.sh update^ and it updated perfectly. Enter the panel and notice that the SSL certificate was not working which continue executing ^. / Docker.sh letsencrypt-create ^ and load the old data but the panel continues giving problems, the connection is not private in web browser.
Run the command ^ docker-compose logs -f nginx_proxy_letsencrypt ^ and it throws me this

^[[Attaching to azuracast_nginx_proxy_letsencrypt_1                                                                                  nginx_proxy_letsencrypt_1  | Info: running letsencrypt-nginx-proxy-companion version v2.0.2-26-g74f9014
nginx_proxy_letsencrypt_1  | Warning: '/etc/acme.sh' does not appear to be a mounted volume.
nginx_proxy_letsencrypt_1  | Info: Custom Diffie-Hellman group found, generation skipped.
nginx_proxy_letsencrypt_1  | Reloading nginx proxy (3c73b42cb688e6103944c6432a55ec90f9427f6aa3428fc450263c5e0fc203e0)...
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:15 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:15 [warn] 43#43: duplicate MIME type "text/plain" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:15 [warn] 43#43: duplicate MIME type "text/css" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:15 [warn] 43#43: duplicate MIME type "application/javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:15 [warn] 43#43: duplicate MIME type "application/json" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:15 [warn] 43#43: duplicate MIME type "application/x-javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:15 [warn] 43#43: duplicate MIME type "text/xml" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:15 [warn] 43#43: duplicate MIME type "application/xml" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:15 [warn] 43#43: duplicate MIME type "application/xml+rss" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:15 [warn] 43#43: duplicate MIME type "text/javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:15 [notice] 43#43: signal process started
nginx_proxy_letsencrypt_1  | Warning: /app/letsencrypt_service_data not found, skipping data from containers.
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:17 Generated '/app/letsencrypt_service_data' from 7 containers
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:17 Running '/app/signal_le_service'
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:17 Watching docker events
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:18 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
nginx_proxy_letsencrypt_1  | [Sun Feb 14 08:54:19 UTC 2021] Create account key ok.
nginx_proxy_letsencrypt_1  | [Sun Feb 14 08:54:19 UTC 2021] Registering account: https://acme-v02.api.letsencrypt.org/directory
nginx_proxy_letsencrypt_1  | [Sun Feb 14 08:54:20 UTC 2021] Registered
nginx_proxy_letsencrypt_1  | [Sun Feb 14 08:54:20 UTC 2021] ACCOUNT_THUMBPRINT='sR3VlpjCe9vAkAkKQU3byTLOhmrGn0ZIkvHwYMu51Ks'
nginx_proxy_letsencrypt_1  | Reloading nginx proxy (3c73b42cb688e6103944c6432a55ec90f9427f6aa3428fc450263c5e0fc203e0)...
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:21 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:21 [warn] 63#63: duplicate MIME type "text/plain" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:21 [warn] 63#63: duplicate MIME type "text/css" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:21 [warn] 63#63: duplicate MIME type "application/javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:21 [warn] 63#63: duplicate MIME type "application/json" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:21 [warn] 63#63: duplicate MIME type "application/x-javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:21 [warn] 63#63: duplicate MIME type "text/xml" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:21 [warn] 63#63: duplicate MIME type "application/xml" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:21 [warn] 63#63: duplicate MIME type "application/xml+rss" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:21 [warn] 63#63: duplicate MIME type "text/javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:21 [notice] 63#63: signal process started
nginx_proxy_letsencrypt_1  | Creating/renewal nvradios.com certificates... (nvradios.com)
nginx_proxy_letsencrypt_1  | [Sun Feb 14 08:54:22 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
nginx_proxy_letsencrypt_1  | [Sun Feb 14 08:54:22 UTC 2021] Creating domain key
nginx_proxy_letsencrypt_1  | [Sun Feb 14 08:54:23 UTC 2021] The domain key is here: /etc/acme.sh/nvirred@hotmail.com/nvradios.com/nvradios.com.key
nginx_proxy_letsencrypt_1  | [Sun Feb 14 08:54:23 UTC 2021] Single domain='nvradios.com'
nginx_proxy_letsencrypt_1  | [Sun Feb 14 08:54:23 UTC 2021] Getting domain auth token for each domain
nginx_proxy_letsencrypt_1  | [Sun Feb 14 08:54:23 UTC 2021] Create new order error. Le_OrderFinalize not found. {
nginx_proxy_letsencrypt_1  |   "type": "urn:ietf:params:acme:error:rateLimited",
nginx_proxy_letsencrypt_1  |   "detail": "Error creating new order :: too many certificates already issued for exact set of domains: nvradios.com: see https://letsencrypt.org/docs/rate-limits/",
nginx_proxy_letsencrypt_1  |   "status": 429
nginx_proxy_letsencrypt_1  | }
nginx_proxy_letsencrypt_1  | [Sun Feb 14 08:54:23 UTC 2021] Please check log file for more details: /dev/null
nginx_proxy_letsencrypt_1  | Reloading nginx proxy (3c73b42cb688e6103944c6432a55ec90f9427f6aa3428fc450263c5e0fc203e0)...
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:24 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:24 [warn] 83#83: duplicate MIME type "text/plain" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:24 [warn] 83#83: duplicate MIME type "text/css" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:24 [warn] 83#83: duplicate MIME type "application/javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:24 [warn] 83#83: duplicate MIME type "application/json" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:24 [warn] 83#83: duplicate MIME type "application/x-javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:24 [warn] 83#83: duplicate MIME type "text/xml" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:24 [warn] 83#83: duplicate MIME type "application/xml" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:24 [warn] 83#83: duplicate MIME type "application/xml+rss" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:24 [warn] 83#83: duplicate MIME type "text/javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt_1  | 2021/02/14 08:54:24 [notice] 83#83: signal process started
nginx_proxy_letsencrypt_1  | Sleep for 3600s

I don't understand much about this program which I try not to touch anything. I use it because my website is https and I need it.
I hope you have a solution.

**Comment by Vaalyn** [comment]
Your Let's Encrypt container got the response that you have hit their rate limit for renewing a certificate for a week. They have a rate limit of 5 so called "Duplicate Certificates" per week. See the link in the following error message from your logs for more information directly from Let's Encrypt:

```
nginx_proxy_letsencrypt_1 | "detail": "Error creating new order :: too many certificates already issued for exact set of domains: nvradios.com: see https://letsencrypt.org/docs/rate-limits/",
```

There seems to be an issue with the Lets Encrpyt container that leads it to renew a certificate when updating (I haven't checked if it also does that when just restarting).

I would guess that this is also why you are hitting this rate limit.

I'm currently looking to why this happens and how to fix it refer to issue #3817 for more detailed information.
Maybe you can try to check if you can see the same "warning" that I mentioned in that issue on your logs too.

**Comment by tanotar** [comment]
Thank you very much for responding. I
The domain is hosted in cPanel. Someone who knows how to link the SSL certificate provided by cPanel for free, give a tutorial to use it.

**Comment by tanotar** [comment]
Thank you very much for responding. I
The domain is hosted in cPanel. Someone who knows how to link the SSL certificate provided by cPanel for free, give a tutorial to use it.

**Comment by Vaalyn** [comment]
The main issue of the certificates being constantly renewed has been fixed now.

Regarding using you own / cPanels SSL certificate please refer to the following docs page: https://docs.azuracast.com/en/administration/ssl-and-lets-encrypt

I don't remember were cPanel saves it's SSL certs so you might need to look into their documentation for the correct path on your machine.

**Comment by tanotar** [comment]
Thank you very much for your answer @Vaalyn. To solve the problem I have to update the panel or command the command ". / Docker.sh letsencrypt-create"?

**Comment by Vaalyn** [comment]
I think simply updating AzuraCast should be sufficient.

**Comment by tanotar** [comment]
I do not repair anything the update :( @Vaalyn
