### ISSUE TITLE
Let's Encrypt container always fetches a new certificate on update due to volume mount issue

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#3817]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling-Release #b79f892 (2021-02-14 4:53)

**Host Operating System**
Ubuntu 20.04 LTS

**Describe the bug**
We sometimes see users reporting that their installations HTTPS stops working after and update (for example #3816) where we can see in the logs of the `nginx_proxy_letsencrypt_1` that it has hit the rate limit from LE for renewing certs.

This seems to be caused by a volume mount that we should have but currently do not have.

In the logs you can see the following warning entry:
```
Warning: /app/letsencrypt_service_data not found, skipping data from containers.
```

and you can see it actually registering a new account and fetching a key again in the logs:

```
Warning: /app/letsencrypt_service_data not found, skipping data from containers.

...

nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:26 UTC 2021] Create account key ok.
nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:26 UTC 2021] Registering account: https://acme-v02.api.letsencrypt.org/directory
nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:27 UTC 2021] Registered

...

nginx_proxy_letsencrypt_1  | Creating/renewal azuracast.vaachar.de certificates... (azuracast.vaachar.de)
nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:29 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:29 UTC 2021] Creating domain key
nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:30 UTC 2021] The domain key is here: /etc/acme.sh/default/azuracast.vaachar.de/azuracast.vaachar.de.key
nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:30 UTC 2021] Single domain='azuracast.vaachar.de'
nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:30 UTC 2021] Getting domain auth token for each domain
nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:33 UTC 2021] Getting webroot for domain='azuracast.vaachar.de'
nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:33 UTC 2021] Verifying: azuracast.vaachar.de
nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:36 UTC 2021] Pending
nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:39 UTC 2021] Pending
nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:42 UTC 2021] Pending
nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:45 UTC 2021] Success
nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:45 UTC 2021] Verify finished, start to sign.
nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:45 UTC 2021] Lets finalize the order.
nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:45 UTC 2021] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/xxx/xxx'
nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:46 UTC 2021] Downloading cert.
nginx_proxy_letsencrypt_1  | [Sun Feb 14 11:25:46 UTC 2021] Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/xxx'

...
```

We currently do not mount anything to the `/app/letsencrypt_service_data` directory which the LE container is complaining about. This is most likely the source of this bug.

**Expected behavior**
When updating and restarting an AzuraCast installation it should only renew / fetch a new cert when it actually needs a new one.

**Comment by tanotar** [comment]
Thank you very much for responding. I
The domain is hosted in cPanel. Someone who knows how to link the SSL certificate provided by cPanel for free, give a tutorial to use it.

**Comment by SlvrEagle23** [comment]
@Vaalyn It turns out the LetsEncrypt proxy companion has updated to version 2.x which uses `acme.sh` as its underlying handler instead of `simp_le`, which requires a new persistent volume be created for the proxy companion.

Since previously we were directly depending on the latest version of that companion container (unlike all of our other containers), this caught us off guard and we didn't have a chance to prepare for it. We should've done it sooner, but I went ahead and created our own proxy Docker image (with corresponding `latest` and `stable` branches) for the LetsEncrypt companion that our Docker users will refer to.

The latest Docker Compose update points to this new internally-managed image and also adds the `acme.sh` volume that the latest version appears to need to persist its data.
