### ISSUE TITLE
This stream is not configured for adverts.

### ISSUE THREAD

**Issue by Roforum** [AzuraCast/AzuraCast#382]
Hi,
I get this msg : 
This stream is not configured for adverts.

Please upgrade your stream to the DNAS+ service to enable advert support.
I make a new account but i don`t have Authhash, only server, port and id station.
How ca i config my station with rmo.shoutcast.com?
http://prntscr.com/i1urm3
thk you.

**Comment by peppinoita** [comment]
This is not related to AzuraCast
