### ISSUE TITLE
The AutoDJ and the real problems...

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#3820]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #3d50d12 (2021-02-14 18:36) - Latest Rolling Release

**Host Operating System**
Ubuntu 20.04 & Debian 10

### Describe the bug
So, to make it a little clearer at the beginning: The errors that occur here are certainly already distributed here in the issues, but I wanted to summarize this again clearly to possibly the duplicates, the repeating queue and the settings to say the fight on.

It's about nothing else than the AutoDJ which has some errors in connection with other functions (If I can call it an error at all). It should be said that all my observations are based on my own analyses and not on those of others (if then linked to other issues here).

I describe everything in more detail under "Expected behavior".

### Expected behavior
In this case, we have several factors that play an important role here:

**Avoid Duplicate Artists/Titles Function - Duplicate Prevention Time Range - Song Playback Order - AutoDJ Queue (Length) - Song Count**

Let's start with the "Avoid Duplicate Artists/Titles Function":
This function is quite simple and works well. In most cases it does what it is supposed to do, namely avoid duplicate artists & titles. However, this does not work so well in combination with the...

"Duplicate Prevention Time Range" - My playlist goes for exactly 19 hours. If I set the "Duplicate Prevention Time Range" to 15 hours or slightly higher or lower, it sometimes still grabs the same artists / tracks often (See Issue: #3776) - Not always, but often. If the "Duplicate Prevention Time Range" is set too low for this 19 hour playlist (for example to 60 minutes or 120 minutes), songs will be repeated quite often, but not the artist himself (In most cases). Despite the fact that the...

"Song Playback Order" is set to "Shuffle" (as recommended). As far as I have read through any issue here, it should be clear that the "Shuffle" mode shuffles the playlist once and then plays COMPLETELY through. But this is not the case, because even with a "Duplicate Prevention Time Range" of 0 minutes titles can repeat completely within 30 minutes.
The "Song Playback Type" "Random" is minimally different here - This shuffles or randomizes possibly better, but here artists repeat themselves much more often than in the "Shuffle" mode (See #3140)

Important point: Sequentially the shuffle mode plays as well as soon as the "Duplicate Prevention Time Range" is in use again. Should I (as in my case) set the "Duplicate Prevention Time Range" to 15 hours for an 18 hour playlist, then the songs that were running 15 hours ago at the beginning will repeat again and everything will start from the beginning - meaning there will be no more shuffling, because it will only stick to the "Duplicate Prevention Time Range". Once this is okay - but not if the playlist should continue to run normally. At some point you know the order by heart (As described in these issues: #3630 & #3781)

I also noticed that an "AutoDJ Queue (Length)" of 3 shuffles better than an "AutoDJ Queue (Length)" of 25 - I don't know exactly how the queue handles this - if it uses the "Avoid Duplicate Artists/Titles Function" only when a new song is added or completely during creation - I was unsure.

Of course, the number of songs also plays a big role, so only songs that are part of a playlist of 60 songs, for example, can be repeated constantly. However, I find it glaring that the "Song Playback Order" "Shuffle" somehow fails to shuffle more than 350 songs, at a given "Duplicate Prevention Time Range".

**Conclusion**

With my current variant (Avoid Duplicate Artists/Titles: ON - Duplicate Prevention Time Range: 15 hours - Song Playback Order: Shuffle - AutoDJ Queue (Length): 3 - Song Count: 337 (19 hours) it actually works as it should - but you quickly get the impression that the playlist runs continuously through the playlist and not mixed - What it should actually do.

I have to admit: I don't always get the same artist immediately on my current solution, but he reappears on a few cases right after 3-4 songs immediately, although the he is in just as often as some others.

**I was able to make these observations for myself on my 2-3 servers, which were clean from the start (newly installed, AzuraCast only, the latest updates). If other station owners have the same problem, feel free to comment. If I have set anything wrong myself or if I have reported anything wrong, please correct me as well! Should anything be awkwardly worded or questions arise, please do not hesitate to comment here too.**

### To Reproduce

1. Set up a playlist with the following options:
> Playlist Weight: 25
> Avoid Duplicate Artists/Titles: Yes (Tick)
> Include in On-Demand Player: No (No Tick)
> Playlist Type: General Rotation
> Source: Song-Based Playlist
> Song Playback Order: Shuffled
> Allow Requests from This Playlist
> Schedule: No Schedule
> Advanced: All off
2. Add X songs to the respective playlist
3. See how long the playlist would run (Playlists > NAME > # Songs > (My example:) 337 (19 hours)
4. Set the "AutoDJ Queue Length" to 3 (Edit Profile -> AutoDJ -> AutoDJ Queue Length) or for the duplicate check to 25
5. Set the Duplicate Prevention Time Range near the playlist length (In my case 1020 minutes - 15 hours) to play any tracks (Edit Profile > AutoDJ > Duplicate Prevention Time Range (Minutes))
6 (Optional). Set the "Duplicate Prevention Time Range" to 60 or 120 minutes to see that the tracks repeat quite often.

### Relevant Logs

The only logs I get from AzuraCast itself are permanently these:
```
[2021-02-15T10:45:31.986933+00:00] AzuraCast.ERROR: Request returned status code 404. {"body":""} {"station":{"id":7,"name":"Station7"}}
[2021-02-15T10:45:31.995025+00:00] AzuraCast.ERROR: Request returned status code 404. {"body":""} {"station":{"id":7,"name":"Station7"}}
[2021-02-15T10:45:31.995140+00:00] AzuraCast.WARNING: Could not fetch XML data; falling back to public JSON. [] {"station":{"id":7,"name":"Station7"}}
[2021-02-15T10:45:33.327768+00:00] AzuraCast.ERROR: Request returned status code 404. {"body":""} {"station":{"id":1,"name":"Station1"}}
[2021-02-15T10:45:33.336149+00:00] AzuraCast.ERROR: Request returned status code 404. {"body":""} {"station":{"id":1,"name":"Station1"}}
[2021-02-15T10:45:33.336249+00:00] AzuraCast.WARNING: Could not fetch XML data; falling back to public JSON. [] {"station":{"id":1,"name":"Station1"}}
```

### Screenshots

"AutoDJ Queue (Length)" is set to 25 and "Duplicate Prevention Time Range" is set to 0 minutes
![image](https://user-images.githubusercontent.com/42640247/107932565-fe1f6e80-6f7d-11eb-9092-92f3813a7e29.png)
![image](https://user-images.githubusercontent.com/42640247/107933455-0cba5580-6f7f-11eb-8084-9500ac1c6d28.png)

"AutoDJ Queue (Length)" is set to 3 and "Duplicate Prevention Time Range" is set near to playlist time (Can't be shown well, because there are only 3 songs, however the history looks better)
![image](https://user-images.githubusercontent.com/42640247/107932757-34f58480-6f7e-11eb-9ba1-0281bb5c8459.png)
...the History:
![image](https://user-images.githubusercontent.com/42640247/107932886-55bdda00-6f7e-11eb-8088-4cd4f7fb5cf7.png)

...but "High/(Low) Duplicate Prevention Time Range" + "Shuffle" Playlists run in the same order (Sequential)
![image](https://user-images.githubusercontent.com/42640247/107932060-6b7ecf80-6f7d-11eb-89bf-5a67b56025a3.png)
(some artist duplicates because of a slightly older version - also the weight was set to 3 only)
![image](https://user-images.githubusercontent.com/42640247/107932300-b0a30180-6f7d-11eb-9e1d-71f39062a44b.png)

**Comment by Reaktiv4** [comment]
Increase the number of songs 3-4 times and everything will be fine

**Comment by Abqehebter** [comment]
@Reaktiv4 How? I should now watch to bring my playlist to 1000 songs just like that? Songs not only cost money, you also have to "look after" them. It should work just as well with 350 songs. Correct me if I have misunderstood something ...

**Comment by Reaktiv4** [comment]
In order for an auto-DJ to "turn around" he needs more songs or not to touch him for a week or two .. then he will work better. That is, do not add songs, do not change the playlist, do not restart the station, etc. The longer the AutoDj runs unchanged, the better the results.

**Comment by Abqehebter** [comment]
Ah I understand now. Sorry for the overreaction. Yes that may well be that I have the AutoDJ bit annoyed lately. I think I'll put my final solutions in there, and just watch it for a while. Thanks for the tip! (P.S. AutoDJ Rolling Updates I take with pleasure times understands itself)

**Comment by SlvrEagle23** [comment]
@Abqehebter With threads like this, there is very little we can actually address from a developmental perspective, since it appears to just be a list of things that are already represented in various other issues on the system, reinforcing that they're happening in your case.

As a rule, we prefer to have a "one issue per Issue" setup, where each issue here on GitHub represents one specific problem that we can investigate, develop a fix for, and resolve. A big post about everything wrong with our AutoDJ script isn't something we can track in a meaningful way.

While we appreciate that you've had a number of issues with our AutoDJ, the AutoDJ section of our application is one of those areas where it is seemingly impossible to build a solution that pleases every station operator out there. When we get reports of things being wrong with the AutoDJ (and, as you can tell, we get them all the time), we basically never get code samples that point to specific things that are going wrong with the code, and we absolutely never get pull requests with updated code that will help resolve the issue.

I don't know that there is any meaningful way we could respond to this one issue. I know it would be easiest if we could "just fix the issues", but you have to realize from a developer perspective, sometimes the real difficulty isn't in writing the code to fix the problem, it's trying to figure out where the problem exists in the first place, what's causing it, and what needs changing. This is where we're stuck with a majority of the AutoDJ issues, and we need more developer eyes looking at it to overcome that hurdle.

**Comment by Abqehebter** [comment]
@SlvrEagle23 Beautifully said! I was never about writing an issue and then saying "go for it, you'll get it" - I was more about small steps (yes with the huge issue bit awkward that's true) that you could follow to take care of the problem.
I see the problem of course also from your eyes, it's hard to move with two, three people there much - Only I have the problem too. I don't see anything in the code at first glance that could lead to this.

But I found my solution to the problem anyway. I think it was my own stupidity. If I hadn't set the "Duplicate Prevention Time Range" too high, everything would have been fine.
AzuraCast is now running "normally" for me, and I had to somehow first teach myself that the songs can run more often.

A big sorry from my side - I still hope you won't get off the AutoDJ course too. Thanks for any tests and try at it - Must also be said times!

I report only with "single-issues", also thanks for the hint.
