### ISSUE TITLE
When push on "skip song" twice, the player jump to random song

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#3821]
**Using Docker installation method**
 Yes

**AzuraCast version**
Rolling Release #3d50d12 (2021-02-14 18:36)

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
On `skip song` the player jump to random song  
When push `skip song`  the next song is not as it shown in `Playing Next` or on  `Upcoming Song Queue` but other random song from the playlist. Sometimes after `skip song` the song title is not the song that actually playing.

Also this issue still exist #3784. I think it related

**Comment by eranwo** [comment]
**To Reproduce** :
- On station profile page try clicking on "`skip song`".
- You'll get to right song but might be without the duration time.
- Then click "`skip song`" again and you will get random song , not the "`Playing Next` " song.

**Comment by Vaalyn** [comment]
Closing as resolved since our update to LS 2.0
