### ISSUE TITLE
Need to change the IP of Services

### ISSUE THREAD

**Issue by Jaadoo13** [AzuraCast/AzuraCast#3829]
Hello. On my Server, i have 3 IPs. and two of them should to be used by azuracast. one ip for icecast and one for the web.
Because i need every part to be run on port 80. So how can i tell to the docker-composer or nginx or Icecast, which IP they should use instead of 0.0.0.0 ?
i have found the containers here: /var/lib/docker/containers/ and i know which one is for nginx. But what should i do now? Oh, and i cant change something outside of the container.

Has someone an idea? thx

**Comment by Abqehebter** [comment]
If you are using Docker, modify the `docker-compose.yml` as follows:

```
ports :
    - '127.0.0.1:${AZURACAST_HTTP_PORT:-80}:80'
    - '127.0.0.1:${AZURACAST_HTTPS_PORT:-443}:443'
```

The 127.0.0.1 is the IP you want to use.
For me it is enough to change it at nginx_proxy, but I would recommend it for all (nginx_proxy, web...).
This works for my docker method at least.

**Comment by Jaadoo13** [comment]
Thx. But i think, there is an error in your code.. because i got an nginx 502 error. and azuracast-services will not start
Any ideas?

**Comment by Abqehebter** [comment]
That is strange. I only specified the respective IP address in the port range (Only for nginx_proxy) once restarted everything and it ran.

Say...
```
cd /var/azuracast
docker-compose down
docker-compose up -d
```

The GeoIP runs automatically after the installation. I can see everything directly in the "Listeners" area (Station > Manage > Reports > Listeners)

**Comment by Jaadoo13** [comment]
It does not helped. Starting azuracast service...waiting...
Here is my yaml file(IPs here are incomplete. But two different 1. starts with 81. and second with 85):

`#
# AzuraCast Docker Compose Configuration File
#
# When updating, you will be prompted to replace this file with a new
# version; you should do this whenever possible to take advantage of
# new updates.
#
# If you need to customize this file, you can create a new file named:
#   docker-compose.override.yml
# with any changes you need to make.
#
version : '2.2'

services :
  nginx_proxy :
    container_name : nginx_proxy
    image : "azuracast/azuracast_nginx_proxy:${AZURACAST_VERSION:-latest}"
    ports :
      - '81.0.0.0:${AZURACAST_HTTP_PORT:-80}:80'
      - '81.0.0.0:${AZURACAST_HTTPS_PORT:-443}:443'
    volumes :
      - letsencrypt:/etc/nginx/certs
      - nginx_proxy_vhosts:/etc/nginx/vhost.d
      - letsencrypt_html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment :
      DEFAULT_HOST : ${LETSENCRYPT_HOST:-azuracast.local}
    networks :
      - frontend
    depends_on :
      - web
    restart : always

  nginx_proxy_letsencrypt :
    container_name : nginx_proxy_letsencrypt
    image : "azuracast/azuracast_nginx_proxy_letsencrypt:${AZURACAST_VERSION:-latest}"
    volumes_from :
      - nginx_proxy
    volumes :
      - letsencrypt_acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment :
      DEFAULT_EMAIL : ${LETSENCRYPT_EMAIL}
    networks :
      - frontend
    restart : always

  web :
    container_name : azuracast_web
    image : "azuracast/azuracast_web_v2:${AZURACAST_VERSION:-latest}"
    # Want to customize the HTTP/S ports? Follow the instructions here:
    # https://docs.azuracast.com/en/administration/docker#using-non-standard-ports
    ports :
      - '81.0.0.0:${AZURACAST_SFTP_PORT:-2022}:2022'
    depends_on :
      - mariadb
      - stations
      - redis
    env_file : azuracast.env
    environment :
      LANG : ${LANG:-en_US.UTF-8}
      AZURACAST_DC_REVISION : 11
      AZURACAST_VERSION : ${AZURACAST_VERSION:-latest}
      AZURACAST_SFTP_PORT : ${AZURACAST_SFTP_PORT:-2022}
      VIRTUAL_HOST : ${LETSENCRYPT_HOST:-azuracast.local}
      LETSENCRYPT_HOST : ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL : ${LETSENCRYPT_EMAIL}
    volumes :
      - letsencrypt:/etc/nginx/certs:ro
      - www_vendor:/var/azuracast/www/vendor
      - tmp_data:/var/azuracast/www_tmp
      - station_data:/var/azuracast/stations
      - shoutcast2_install:/var/azuracast/servers/shoutcast2
      - geolite_install:/var/azuracast/geoip
      - sftpgo_data:/var/azuracast/sftpgo/persist
      - backups:/var/azuracast/backups
    networks :
      - frontend
      - backend
    restart : always
    ulimits : &default-ulimits
      nofile :
        soft : 65536
        hard : 65536
    logging : &default-logging
      options :
        max-size : "1m"
        max-file : "5"

  mariadb :
    container_name : azuracast_mariadb
    image : "azuracast/azuracast_db:${AZURACAST_VERSION:-latest}"
    volumes :
      - db_data:/var/lib/mysql
    env_file : azuracast.env
    networks :
      - backend
    restart : always
    logging : *default-logging

  redis :
    container_name : azuracast_redis
    image : "azuracast/azuracast_redis:${AZURACAST_VERSION:-latest}"
    sysctls :
      net.core.somaxconn : 1024
    volumes :
      - redis_data:/data
    networks :
      - backend
    restart : always
    logging : *default-logging

  stations :
    container_name : azuracast_stations
    image : "azuracast/azuracast_radio:${AZURACAST_VERSION:-latest}"
    ports :
      # This default mapping is the outgoing and incoming ports for the first 50 stations.
      # You can override this port mapping in your own docker-compose.override.yml file.
      # For instructions, see:
      # https://docs.azuracast.com/en/administration/docker#expanding-the-station-port-range
      - '85.214.0.0:80:80'
      - '8005:8005'
      - '8006:8006'
      - '8010:8010'

    volumes :
      - station_data:/var/azuracast/stations
      - shoutcast2_install:/var/azuracast/servers/shoutcast2
      - letsencrypt:/etc/nginx/certs
      - tmp_data:/var/azuracast/www_tmp
    networks :
      - frontend
      - backend
    init : true
    restart : always
    ulimits : *default-ulimits
    logging : *default-logging

networks :
  frontend :
    driver : bridge
  backend :
    driver : bridge

volumes :
  nginx_proxy_vhosts : { }
  db_data : { }
  letsencrypt : { }
  letsencrypt_html : { }
  letsencrypt_acme : { }
  shoutcast2_install : { }
  geolite_install : { }
  sftpgo_data : { }
  station_data : { }
  www_vendor : { }
  tmp_data : { }
  redis_data : { }
  backups : { }
`

if i dont change the IP, then it works. i will try changing ports again...

**Comment by Abqehebter** [comment]
Ah I see the problem. You specified "- '85.214.0.0:80:80" for the station ports, which doesn't belong there.
Should look more like this...

```
ports :
- '85.214.0.0:8000:8000'
- '85.214.0.0:8005:8005'
- '85.214.0.0:8006:8006'
- '85.214.0.0:8010:8010'
...
```

**Comment by Jaadoo13** [comment]
But i want the station on port 80. Because of many firewall problems on the listener side. i dont need port 8000 or something. and if there is a problem, why all things does not work instead of only icecast wont work? Ok icecast can get an invidual config on webpage settings.

**Comment by Abqehebter** [comment]
AzuraCast uses the nginx_proxy to rewrite the "port URL" to a "normal URL". Say...

```
http://127.0.0.1:8000/radio.mp3
becomes
https://azuracast.example.com/radio/8000/radio.mp3
```

Thus the stream runs already over port 80 or 443
You can enable this in the System Settings (Administration > System Settings > Tick Prefer Browser URL (If Available))

**Comment by Jaadoo13** [comment]
Ya okay. But i can not start azura at all.... See Picture(whatever i try, since ip changing):
![8888](https://user-images.githubusercontent.com/63636492/108599775-84c7b780-7393-11eb-8518-9f7b6d67b8e1.png)

**Comment by Abqehebter** [comment]
Hm. I would recommend you to leave the ports as they are, as soon as you want to use another IP address, you can enter it in front with the `'127.0.0.1:${AZURACAST_HTTP_PORT:-80}:80'` variant.
Station-Ports I would leave as well, because the nginx_proxy will handle all this already over port 80 / 443.

If you are asked if you want to use custom ports, it is best to use...

`HTTP: 80 | HTTPS: 443 | SFTP: 2022`

... in the .env file.
The "Waiting" display after the installation also took me quite a long time, which should be shorter by now.

**Comment by Jaadoo13** [comment]
So, many thx to you. It works now. But i have few more questions.
How can i change the Proxy from "/radio/8000/mountpoint" to "/mountpoint" ? Or isnt this possible?
And the buildin geoip is only to see, from where the People are listening. But i need geoip to prevent some countries from listening. because of Licensing.
And at least i need of course https streaming. But How exactly? Reinstall again with letsencrypt?

**Comment by Abqehebter** [comment]
The URL redirection to change (So from /radio/8000/radio.mp3 to /radio.mp3) I have not yet figured out, but I was / am sure that it was / is possible. I think there is this advanced option (see picture) but I don't know if it fits. You have to tinker a little bit.

![image](https://user-images.githubusercontent.com/42640247/108605139-95d3f100-73b2-11eb-87b7-b78f59630190.png)

With the listeners themselves, I can see exactly where they come from (see picture) - The country should also be in the CSV ("Download CSV")

![image](https://user-images.githubusercontent.com/42640247/108605201-ffec9600-73b2-11eb-94e3-c2a63f83c3e3.png)

What you could possibly look at again is the GeoLite IP Database, which can be "installed" (Administration > Stations > Install GeoLite IP Database).

![image](https://user-images.githubusercontent.com/42640247/108605284-7093b280-73b3-11eb-8cb6-cc56d01930c3.png)

**Comment by Jaadoo13** [comment]
Thx. in the case of geoip, thx also. but that wasnt what i meant. To see its nice. But i mean to block a whole country with geoip. in the last time i blocked the whole server.  for advanced url i will give it a try. ;)

**Comment by Abqehebter** [comment]
Then I did not understand your question correctly. Sorry. As far as I know, GeoBlocking is not supported. Of course, you can do things differently on the server side.

I correct myself to the Custom URL: That was not quite right. The feature to bypass /radio/8000/radio.mp3 does not exist yet - You can try to change something in the nginx config - but this is not supported.
For me it is enough to change the mountpoint URL: /radio.mp3 -> /stream1.mp3 (See: Mount Points > Edit > Mount Point URL: /xyz.mp3) That looks better than just /radio.mp3 :)

**Comment by Jaadoo13** [comment]
Do you know, where is the docker template for the iptables? Because if i manually change the rules, then few minutes later, docker changes it back. so, i have to change the dockers template file i think. because docker-user chain also doesnt help.....

**Comment by Abqehebter** [comment]
@Jaadoo13 Hauptsächlich sollten wir ja hier in englisch schreiben 😋

Sorry for the late reply, only unfortunately I do not know anything about IP tables now. What exactly does Docker change again? Deny path on Icecast? I think I wrote some nonsense there. Check if you have the Advanced Settings on and have a look at: Station > Edit Profile > Broadcasting

At the bottom is a field with "Advanced Banned IP Addresses" - There you can also enter them.
![image](https://user-images.githubusercontent.com/42640247/109205283-ac10f100-77a6-11eb-82cb-8ac36120d904.png)

**Comment by Jaadoo13** [comment]
I think it works now. But i will see, what happens, when i have to restart the whole Server.... Because i think, docker rewrites on a new reboot. I had only canceld the rewrite on running processes. and iptables-persitent does not rewrite the old rules. so it is a miracle. i will watch it for a while and after then i will write here again. But many thx at all.

**Comment by Abqehebter** [comment]
You mean the Auto Playlist? So that...

![image](https://user-images.githubusercontent.com/42640247/109208162-49b9ef80-77aa-11eb-95b7-4e212a690e2b.png)

Have you deactivated the other playlists or something similar? Can not currently recreate this with me. I do not use the feature.

**Comment by Jaadoo13** [comment]
Hello. I found many issues. But today i got a big Problem. Ubuntu was updating the system. and then my station brokes.
![Screenshot 2021-03-15 175450](https://user-images.githubusercontent.com/63636492/111193385-659aff00-85ba-11eb-9ff4-8266b1ee2fd3.png)

**Comment by Abqehebter** [comment]
The best way (To possibly fix this later) would be to open a new issue with it. The topic here has certainly settled.

**Comment by Jaadoo13** [comment]
Ya, youre right. i had reinstaled the server and used my backup. But i cant find the place, where i can prevent docker from updating the iptables
