### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by drno88** [AzuraCast/AzuraCast#3830]
Good day. Maybe someone can help me. Can't install Azuracast on raspberry pi 4.
In the last paragraph when installing "TASK [composer : Install Composer Dependencies" 
I get an error, the meaning of which is - ""Installing dependencies from lock file\nVerifying lock file contents can be installed on current platform.""
Ubuntu 20.04, Ansible, raspberry pi 4

**Comment by Vaalyn** [comment]
This is most likely due to the same bug reported in #3828.

Please follow that issue, we'll push an update for this soon.
