### ISSUE TITLE
Not able to change songname

### ISSUE THREAD

**Issue by Tummke** [AzuraCast/AzuraCast#3832]
Hello all,,

I've been trying to find the information that I need, but unfortunately couldn't find anything related to my issue.

When I try to change song names, I open up the box, make the changes, save the changes and go to the next one... But when I re-open the previous folders, which already had been changed, they were set back to the unchanged names... 

So it let's me make all the changes, but after refreshing or re-entering the page, all has been set back..

Is there anyone who can give me a solution?

**Comment by SlvrEagle23** [comment]
@Tummke I have identified a possible cause of this issue, and it should be fixed as of the latest Rolling Release update. Please update and let me know if this issue persists.
