### ISSUE TITLE
dropbox

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#3836]
Hello,
I downloaded the latest version to use the dropbox function, but there is no tutorial explaining how to configure it. Can someone help me ?

**Comment by Vaalyn** [comment]
Hey, I've written up a small guide on how to use Dropbox as a storage location:
https://docs.azuracast.com/en/user-guide/storage-locations/dropbox-configuration

Please let me know if something is now working.

**Comment by Marcioghiraldelli** [comment]
img: https://prnt.sc/104eu4a
Path/Suffix 
in this part I put what?
Because in the tutorial does not say.

**Comment by Vaalyn** [comment]
That should stay empty in most cases. You would use this to manually define a sub-directory that it should mount from the storage location.

**Comment by Vaalyn** [comment]
Closing as resolved

**Comment by Marcioghiraldelli** [comment]
Hello, coming back to this subject, I can't get both the s3 and the dropbox to work .;
Does the dropbox need to be bussines? or works with normal dropbox?
in the folder prefix field (Path / Suffix) there is the path of the radio folder on the local server, when I select dropbox it asks for the token, I generate toke and place it and nothing happens.
You said to leave the suffix path empty but if I leave the following error:

App \ Exception \ ValidationException at /var/azuracast/www/src/Controller/Api/AbstractApiCrudController.php L155: Object (App \ Entity \ StorageLocation): This storage location could not be validated: Impossible to create the root directory "". mkdir (): Invalid path
