### ISSUE TITLE
500 MISCONF Redis error

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#384]
Hello,

I do see this error often after somen days of running azuracast?
Its on debian9 with docker.

500
MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
/var/azuracast/www/app/src/AzuraCast/RateLimit.

**Comment by SlvrEagle23** [comment]
@surihost Is your disk running out of space on the server? This error often appears when the Redis image can't write to the disk because it's full.
