### ISSUE TITLE
Problem with Stereo Tool and Live DJ Harbor 

### ISSUE THREAD

**Issue by pimseb** [AzuraCast/AzuraCast#3840]
**Using Docker installation method**

Yes

**AzuraCast version**

Rolling Release #d7d3439

**Host Operating System**

Ubuntu 20.04 Server

**Describe the bug**

I'm posting this here but I think it's more a bug related to Stereo Tool or Liquidsoap
I know Stereo Tool is a 3rd party app and isn't officially supported by azuracast but it's working great to enhance the sound in azuracast auto dj mode. To achieve this I've added this line in the liquidsoap custom config field (the one before output lines) 

``radio = mksafe(pipe(data_length=0, replay_delay=1.5, restart_on_error = true, process='/stereo_tool - - -s /radio.sts -k "<xxxxxxx>" -q',radio))``

Everything works good when I only use azuracast auto dj. 
Yesterday I tried to stream on the live dj harbor during the night :
``` 
2021/02/23 22:48:00 [lang:3] DJ Source connected! Last authenticated DJ: source - [("Authorization", "Basic c291cmNlOmF3aGMzc25y"), ("Host", "192.168.1.2:8255"), ("User-Agent", "butt 0.1.28"), ("Content-Type", "audio/mpeg"), ("ice-name", "Live"), ("ice-public", "0"), ("ice-url", ""), ("ice-genre", "Dance"), ("ice-description", "Live !"), ("ice-audio-info", "ice-bitrate=320;ice-channels=2;ice-samplerate=48000"), ("Expect", "100-continue")]
2021/02/23 22:48:00 [lang:3] AzuraCast Live Connected Response: true
2021/02/23 22:48:00 [input_streamer:3] Decoding...
2021/02/23 22:48:05 [live_fallback:3] Switch to audio_to_stereo_38846 with transition.
2021/02/24 06:59:09 [input_streamer:2] Feeding stopped: Mad.End_of_stream.
```
As you see in the log everything works fine. The problem with stereo tools happens when I send metadata to the live dj server. At this moment the sound begins to "skip" and "glitches" :

```
2021/02/24 07:03:28 [live_fallback:3] Switch to audio_to_stereo_38846 with transition.
2021/02/24 07:04:32 [lang:3] Authenticating DJ: source
2021/02/24 07:04:32 [lang:3] AzuraCast DJ Auth Response: true
2021/02/24 07:04:32 [input_streamer:3] New metadata chunk ? -- Test Metadata
2021/02/24 07:04:52 [clock.wallclock_main:2] We must catchup 1.02 seconds!
2021/02/24 07:04:53 [clock.wallclock_main:2] We must catchup 1.31 seconds!
2021/02/24 07:04:54 [clock.wallclock_main:2] We must catchup 1.66 seconds!
2021/02/24 07:04:55 [clock.wallclock_main:2] We must catchup 1.95 seconds!
2021/02/24 07:04:56 [clock.wallclock_main:2] We must catchup 2.29 seconds!
2021/02/24 07:04:57 [clock.wallclock_main:2] We must catchup 2.63 seconds!
2021/02/24 07:04:58 [clock.wallclock_main:2] We must catchup 2.92 seconds!
```
I must disconnect the live dj source because the sound becomes really bad. There is something in the " New metadata chunk" that stereo tools doesn't like. It's really strange because stereotools does accept the auto dj metadatas without any problem.

I've added `live = drop_metadata(live)` in a manual liquidsoap liq file just after this line `live = audio_to_stereo(input.harbor("/", id = "input_streamer", port = 8255, auth = dj_auth, icy = true, icy_metadata_charset = "UTF-8", metadata_charset = "UTF-8", on_connect = live_connected, on_disconnect = live_disconnected, buffer = 5.00, max = 10.00))
`
With this setting, stereotools works without any issue. And I still can force the artist - title metadata calling the main icecast url, for example http://192.168.1.10:8000/admin/metadata?mount=/mystream&mode=updinfo&song=ACDC+Back+In+Black
But it can't be a permanent setting because it breaks azuracast engine (I had to mount the custom liq file into docker and force azuracast to use it in read only mode)

**Expected behavior**

This issue is due to the way stereo tools handles the live harbor metadata. 
Would it be possible to add a "drop live dj metadata" option in azuracast settings ? 
Or is there another way to drop this metadata and include it back  in the icecast stream ?

Sorry for my english

**Comment by messkaline** [comment]
Please note that stereo tool accepts only WAV or raw PCM data. Are sure that you are not sending to input any kind of compressed stream? in this case, you need to decode stream to raw pcm or wav, first. like 

process='ffmpeg SOME_OPT | stereo_tool - - -s /radio.sts -k "<xxxxxxx>" -q'

**Comment by pimseb** [comment]
Yes I'm sending mp3 compressed audio to stereo tool. Why should I decode the stream into wav? Auto dj works fine without decoding anything and if I do it I will lose the original metadatas. 

The only problem is the live dj harbor stream sending metadata and breaking stereo tool

**Comment by messkaline** [comment]
stereo tool  works with raw data and does not include mp3 decoder inside. it accept only WAV or raw PCM data and it is true, because complicated process requires full range of audio data which mp3 does not have.

**Comment by Vaalyn** [comment]
Hey, I'd recommend taking a look at this Liquidsoap issue thread: https://github.com/savonet/liquidsoap/issues/885

There is a lot of information in there about the usage of Stereo Tool in Liquidsoap and how to deal with metadata.

Since there isn't really anything to do for us in AzuraCast itself about Stereo Tool integration I'll close this issue.
