### ISSUE TITLE
Single quote characters in filenames cause incorrect display

### ISSUE THREAD

**Issue by pacija** [AzuraCast/AzuraCast#3847]
**Using Docker installation method**
No

**AzuraCast version**
v0.11.2 Stable • Ansible • PHP 7.4

**Host Operating System**
Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-65-generic x86_64)

**Describe the bug**
Tracks with single quote `'` in filenames show incorrectly on public page while playing and also in song history. Album cover is not being displayed, also album name is missing (see screenshot).

**To Reproduce**
Play correctly tagged track (containing at least album art, track no., artist, album, title) which contains single quote in filename.

**Expected behavior**
Album cover and album name should be displayed the same for all correctly tagged files regardless of their filenames.

**Relevant Logs**
There seems to be no difference in liquidsoap log between correctly and incorrectly displayed tracks

```
2021/02/26 15:33:00 [lang:3] AzuraCast Raw Response: annotate:title="Keep On Music (12' Vocal Version)",artist="Danny Keith",duration="404.04",song_id="e39dfc16d54c693c84223464aac24e2f",media_id="22856",liq_amplify="0.00dB",playlist_id="6":/var/azuracast/stations/underbottom/media/airsonic/compilations/Various Artists/80's Revolution - Italo Disco Volume 1/01 - Danny Keith - Keep On Music (12' Vocal Version).mp3
2021/02/26 15:33:00 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/underbottom/media/airsonic/compilations/Various Artists/80's Revolution - Italo Disco Volume 1/01 - Danny Keith - Keep On Music (12' Vocal Version).mp3".
2021/02/26 15:33:42 [underbottom_next_song:3] Prepared "/var/azuracast/stations/underbottom/media/airsonic/compilations/Various Artists/80's Revolution - Italo Disco Volume 1/01 - Danny Keith - Keep On Music (12' Vocal Version).mp3" (RID 5).
2021/02/26 15:33:42 [cross_7783:3] Analysis: -151.242802dB / -21.115848dB (11.98s / 11.98s)
2021/02/26 15:33:42 [crossfade:3] new >= old + margin, old <= medium and new <= high.
2021/02/26 15:33:42 [crossfade:3] Do not fade if it's already very low.
2021/02/26 15:33:42 [crossfade:3] Transition: crossed, no fade.
2021/02/26 15:33:43 [lang:3] AzuraCast Feedback Response: OK
2021/02/26 15:39:33 [lang:3] AzuraCast Raw Response: annotate:title="U.S.S.R.",artist="Eddy Huntington",duration="354.87",song_id="09424ec124711c4a250c3c9f75a88837",media_id="24924",liq_amplify="0.00dB",playlist_id="6":/var/azuracast/stations/underbottom/media/airsonic/compilations/Various Artists/Disco Hits - The Greatest/03 - Eddy Huntington - U.S.S.R_.mp3
2021/02/26 15:39:33 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/underbottom/media/airsonic/compilations/Various Artists/Disco Hits - The Greatest/03 - Eddy Huntington - U.S.S.R_.mp3".
2021/02/26 15:40:14 [underbottom_next_song:3] Prepared "/var/azuracast/stations/underbottom/media/airsonic/compilations/Various Artists/Disco Hits - The Greatest/03 - Eddy Huntington - U.S.S.R_.mp3" (RID 1).
2021/02/26 15:40:14 [cross_7783:3] Analysis: -75.097918dB / -14.834202dB (11.97s / 11.99s)
2021/02/26 15:40:14 [crossfade:3] No transition: using default.
2021/02/26 15:40:15 [lang:3] AzuraCast Feedback Response: OK
2021/02/26 15:40:27 [lang:3] AzuraCast Feedback Response: OK
```

**Screenshots**
![azurabug](https://user-images.githubusercontent.com/14246467/109316603-1760ce80-784c-11eb-8c5e-9918438405e9.png)

**Comment by NicoxDJ** [comment]
Hey, this is known problem, and it's not about the single quotes. Check your track #3, have quote too.
Here is the in-depth explanation of the problem: https://github.com/AzuraCast/AzuraCast/issues/3673#issuecomment-771214132

**Comment by pacija** [comment]
Hi, thanks.

Still, it is strange that problems are always with files containing single quotes, although not with all of them.

For example, check the following excerpt from song playback timeline:

![azura](https://user-images.githubusercontent.com/14246467/109982727-774eed80-7d02-11eb-9713-390626ae19cc.png)

Files that have `12'` string don't have playlist column, although they are in the playlist. Those are the same files that are shown incorrectly without album art while playing, and also without album name in song history.

Those files actually have double quotes in tag (`12"`), but only single quote in filename (`12'`), due to EasyTag's "Replace illegal characters when renaming" preference (double quotes are apparently illegal on FAT16/32 and Joliet filesystems).

**Comment by SaneMethod** [comment]
@SlvrEagle23 Since you're tracking this, I can add to this that I have seen that songs with double quotes in the name, e.g. `AmIEvil "7th Guest".mp3`, appear to be returned from liquidsoap with the double quotes replaced with single quotes, e.g. `AmIEvil '7th Guest'.mp3`, which appears to end up stripping the album, album art and duration from the return in the API, likely due to it being treated as a Song rather than StationMedia record on the match failure.

**Comment by SaneMethod** [comment]
And as a quick follow-up, I can confirm that replacing the double-quotes with single quotes in the station_media.text field achieves the desired result, with the media matching up and album, album art and duration being correct in an API call to `/nowplaying`.

**Comment by SaneMethod** [comment]
For those struggling with a similar problem, here's what I did to work-around the problem for now, on the off-chance it may help you:

```
cd /var/azuracast
./docker.sh update-self
./docker.sh cli dbal:run-sql "UPDATE station_media SET text = REPLACE(text, '\"', \"'\");"
./docker.sh cli dbal:run-sql "UPDATE station_media SET title = REPLACE(title, '\"', \"'\");"
```

This obviously doesn't *fix* the problem, but if you don't care whether the name contains double-quotes or single-quotes, that may be sufficient for your needs.

**Comment by SlvrEagle23** [comment]
@SaneMethod This is likely caused by our own escaping function that we use before annotating values to send them to Liquidsoap:

```php
    public static function annotateString(string $str): string
    {
        $str = mb_convert_encoding($str, 'UTF-8');
        return str_replace(['"', "\n", "\t", "\r", '|'], ["'", '', '', '', '-'], $str);
    }
```

LS historically had issues with double-quotes, newlines and the pipe character for different reasons. In my local testing, even escaping the double-quote the normal way (`\"`) was ineffective at fixing the issue, instead requiring the substitution to the single quote.

As for how to fix that mismatching with our own tracks...that'll require some extra work on our end.

**Comment by SlvrEagle23** [comment]
In the Rolling Release branch, we've updated how the "Song hash" (the unique identifier associated with each track) is calculated to specifically take into account special characters like quotation marks, which should fix any issues with pulling rich metadata for tracks with quotation marks, apostrophes, etc.
