### ISSUE TITLE
Not working: Play exactly once every X songs

### ISSUE THREAD

**Issue by JackCoder21** [AzuraCast/AzuraCast#3852]
Ubuntu Server 20.04.1
Docker: Yes
AzuraCast:  v0.12.1 Stable 

From version 0.11 and later I have problems with playlists with rule every X songs. I tried with new installation and also with rollingrelease but autodj respects the rule for some time but after 1/2 hours it goes randomly.

I tried to do a new installation on a new machine with version 0.10.4 (the last one that complies with this playlist rule for me) but without success, AzuraCast has database error.

**Comment by roger-net** [comment]
I also noticed this problem, when you play it every X minutes it seems to work a lot more when you play it every X times it doesn't work well and in this case you have to enable the "Manual AutoDJ Mode" function on the "Edit Profile" tab.

**Comment by petrechkiv** [comment]
I also noticed this problem
