### ISSUE TITLE
No more update announcements

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#3854]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #d7d3439 (2021-02-17 19:40)

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
Since the update from master to main I somehow don't get any update notifications anymore. Previously, the message was seen every day and currently there is nothing.

**To Reproduce**
1. Go to 'Administration'
2. Click on 'System Settings'
3. Go to 'Services'
4. Click 'Show Update Announcements' so that is ticked on
5. Look onm' dashboard that no message appears there anymore.

**Screenshots**
![image](https://user-images.githubusercontent.com/42640247/109632410-4d050080-7b47-11eb-84df-d58623f9ccf8.png)
![Screenshot_2](https://user-images.githubusercontent.com/42640247/109632615-83428000-7b47-11eb-971a-7b5d791669cd.jpg)

**Comment by Vaalyn** [comment]
The central update server where AzuraCast installations are looking for new updates is currently still trying to look for a `master` branch instead of the new `main` branch.

Thank you for the report.

**Comment by SlvrEagle23** [comment]
Our central updates server should be back up and running now, including update announcements.

**Comment by yarik2720** [comment]
Being on version 0.12.3 there were no announce about available update 0.12.4

**Comment by SlvrEagle23** [comment]
@yarik2720 This should now be fixed; we identified a problem with how our central updates server was reporting back items.
