### ISSUE TITLE
Cannot add more than 1 file in WEB DJ

### ISSUE THREAD

**Issue by la-roleplay** [AzuraCast/AzuraCast#3859]
I have tried to add more than one song at the same time by selecting and it is not possible.

https://i.gyazo.com/680ed4f14d38241c44b57f8d02a8d2a8.gif

**Comment by appnostic-io** [comment]
Hi!

Not to dispute your attached .gif but the folks here might need more information.  I've had no problems with WebDJ and adding multiple (up to about 10 or so) files at a time.

I use the stock docker images, if that makes a difference.

**Comment by la-roleplay** [comment]
> Hi!
> 
> Not to dispute your attached .gif but the folks here might need more information. I've had no problems with WebDJ and adding multiple (up to about 10 or so) files at a time.
> 
> I use the stock docker images, if that makes a difference.

It freezes me when I add a lot of songs even when I add two or three.

**Comment by SC2Mitch** [comment]
I'm unable to replicate this issue, I've been able to add multiple songs. When you say freezing, do you mean the browser freezes or the website freezes? And can you check your browser / docker logs.

**Comment by la-roleplay** [comment]
> I'm unable to replicate this issue, I've been able to add multiple songs. When you say freezing, do you mean the browser freezes or the website freezes? And can you check your browser / docker logs.

WEB DJ freezes. I cannot add. I can pause but it does not show as paused but as frozen.

How can I get the logs?

**Comment by SC2Mitch** [comment]
Depends on the browser, right click on the browser and 'inspect' there should be a 'console' tab within it. 
For docker logs, you can check them by going into putty, cd /var/azuracast then docker-compose logs -f

**Comment by la-roleplay** [comment]
> Depends on the browser, right click on the browser and 'inspect' there should be a 'console' tab within it.
> For docker logs, you can check them by going into putty, cd /var/azuracast then docker-compose logs -f

I'll do the test now. This is the third time that has happened to me. I think the file size has something to do with it.

**Comment by Vaalyn** [comment]
Closing this issue since there have been no further replies with additional information and we haven't been able to replicate this issue.
