### ISSUE TITLE
SFTP Issue

### ISSUE THREAD

**Issue by Rezanans-wow** [AzuraCast/AzuraCast#3860]
**Using Docker installation method**
Yes

**AzuraCast version**
Lasted stable edition (I installed yesterday)

**Host Operating System**
Ubuntu 18.04 64-bit

**Describe the bug**
I have issue with SFTP, before i written in discord server. And guys say open issue on github
So what problem, i create user with password (Example user24) with same password(Because its 4-5 attempt = 100% True login info), and then i write it i got error 'Access denied'
- I connecting to IP not domain
- AzuraCast work from domain, but i try connect from IP

**To Reproduce**
Create SFTP user, and try login

**Expected behavior**
-

**Relevant Logs**
no

**Screenshots**
![изображение](https://user-images.githubusercontent.com/49691442/110116865-cc513900-7dc0-11eb-937d-9b0dda9ee113.png)

**Device(s):**

- Device: Desktop
- OS: Windows
- Browser: FireFox 
- Version: Lasted

**Additional context**
-

**Comment by SC2Mitch** [comment]
Can you please provide docker logs when you try a connection, it should be something like this: 
```
web_1                      | {"level":"debug","time":"2021-03-05T13:35:59.257","sender":"dataprovider_bolt","message":"last login updated for user \"mitch\""}
web_1                      | {"level":"debug","time":"2021-03-05T13:35:59.258","sender":"common","connection_id":"trunace","message":"ssh connection added, num open connections: 1"}
web_1                      | {"level":"debug","time":"2021-03-05T13:35:59.360","sender":"SFTP","connection_id":"trunace","message":"connection added, num open connections: 1"}
```

**Comment by Rezanans-wow** [comment]
> 
> 
> Can you please provide docker logs when you try a connection, it should be something like this:
> 
> ```
> web_1                      | {"level":"debug","time":"2021-03-05T13:35:59.257","sender":"dataprovider_bolt","message":"last login updated for user \"mitch\""}
> web_1                      | {"level":"debug","time":"2021-03-05T13:35:59.258","sender":"common","connection_id":"trunace","message":"ssh connection added, num open connections: 1"}
> web_1                      | {"level":"debug","time":"2021-03-05T13:35:59.360","sender":"SFTP","connection_id":"trunace","message":"connection added, num open connections: 1"}
> ```

Yes, how i can copy docker logs?

**Comment by appnostic-io** [comment]
> Yes, how i can copy docker logs?

From the command line just run:

docker logs <name of container>

eg: docker logs azuracast_web

**Comment by Vaalyn** [comment]
Closing this issue since there have been no further replies with additional logs that we'd need to debug this.

**Comment by Rezanans-wow** [comment]
Sorry, i not see mentions
`Spinning up SFTP process...
nginx: [warn] could not build optimal variables_hash, you should increase either variables_hash_max_size: 1024 or variables_hash_bucket_size: 64; ignoring variables_hash_bucket_size
{"level":"info","time":"2021-04-29T20:20:56.206","sender":"service","message":"starting SFTPGo 2.0.4-f117d6d-2021-04-10T06:39:21Z +metrics +awskms +gcpkms +vaultkms +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable, config dir: /var/azuracast/sftpgo, config file: , log max size: 10 log max backups: 5 log max age: 28 log verbose: true, log compress: false, load data from: \"\""}
{"level":"debug","time":"2021-04-29T20:20:56.222","sender":"config","message":"config file used: '\"/var/azuracast/sftpgo/sftpgo.json\"', config loaded: {Common:{IdleTimeout:15 UploadMode:2 Actions:{ExecuteOn:[upload] Hook:/usr/local/bin/azuracast_sftp_upload} SetstatMode:1 ProxyProtocol:0 ProxyAllowed:[] PostConnectHook: MaxTotalConnections:0 DefenderConfig:{Enabled:false BanTime:30 BanTimeIncrement:50 Threshold:15 ScoreInvalid:2 ScoreValid:1 ObservationTime:30 EntriesSoftLimit:100 EntriesHardLimit:150 SafeListFile: BlockListFile:} idleTimeoutAsDuration:0 idleLoginTimeout:0 defender:<nil>} SFTPD:{Banner:SFTPGo_2.0.4 Bindings:[{Address: Port:2022 ApplyProxyConfig:true}] BindPort:0 BindAddress: IdleTimeout:0 MaxAuthTries:0 UploadMode:0 Actions:{ExecuteOn:[] Hook:} Keys:[] HostKeys:[persist/id_rsa persist/id_ecdsa persist/id_ed25519] KexAlgorithms:[] Ciphers:[] MACs:[] TrustedUserCAKeys:[] LoginBannerFile: SetstatMode:0 EnabledSSHCommands:[md5sum sha1sum cd pwd scp] KeyboardInteractiveHook: PasswordAuthentication:true ProxyProtocol:0 ProxyAllowed:[] certChecker:<nil> parsedUserCAKeys:[]} FTPD:{Bindings:[{Address: Port:0 ApplyProxyConfig:true TLSMode:0 ForcePassiveIP: ClientAuthType:0 TLSCipherSuites:[]}] BindPort:0 BindAddress: ForcePassiveIP: Banner:SFTPGo 2.0.4 ready BannerFile: CertificateFile: CertificateKeyFile: CACertificates:[] CARevocationLists:[] ActiveTransfersPortNon20:true DisableActiveMode:false EnableSite:false HASHSupport:0 CombineSupport:0 TLSMode:0 PassivePortRange:{Start:50000 End:50100}} WebDAVD:{Bindings:[{Address: Port:0 EnableHTTPS:false ClientAuthType:0 TLSCipherSuites:[]}] BindPort:0 BindAddress: CertificateFile: CertificateKeyFile: CACertificates:[] CARevocationLists:[] Cors:{AllowedOrigins:[] AllowedMethods:[] AllowedHeaders:[] ExposedHeaders:[] AllowCredentials:false Enabled:false MaxAge:0} Cache:{Users:{ExpirationTime:0 MaxSize:50} MimeTypes:{Enabled:true MaxSize:1000}}} ProviderConf:{Driver:bolt Name:sftpgo.db Host: Port:5432 Username: Password:[redacted] SSLMode:0 ConnectionString: SQLTablesPrefix: TrackQuota:1 PoolSize:0 UsersBaseDir:/var/azuracast/stations Actions:{ExecuteOn:[] Hook:} ExternalAuthHook:/usr/local/bin/azuracast_sftp_auth ExternalAuthScope:0 CredentialsPath:credentials PreLoginHook: PostLoginHook: PostLoginScope:0 CheckPasswordHook: CheckPasswordScope:0 UpdateMode:0 PasswordHashing:{Argon2Options:{Memory:65536 Iterations:1 Parallelism:2}} PreferDatabaseCredentials:false SkipNaturalKeysValidation:false} HTTPDConfig:{Bindings:[{Address:127.0.0.1 Port:0 EnableWebAdmin:true EnableHTTPS:false ClientAuthType:0 TLSCipherSuites:[]}] BindPort:0 BindAddress: TemplatesPath:/usr/share/sftpgo/templates StaticFilesPath:/usr/share/sftpgo/static BackupsPath:backups CertificateFile: CertificateKeyFile: CACertificates:[] CARevocationLists:[]} HTTPConfig:{Timeout:20 RetryWaitMin:2 RetryWaitMax:30 RetryMax:3 CACertificates:[] Certificates:[] SkipTLSVerify:false customTransport:<nil> tlsConfig:<nil>} KMSConfig:{Secrets:{URL: MasterKeyPath: masterKey:}} TelemetryConfig:{BindPort:0 BindAddress:127.0.0.1 EnableProfiler:false AuthUserFile: CertificateFile: CertificateKeyFile: TLSCipherSuites:[]}}"}
{"level":"debug","time":"2021-04-29T20:20:56.226","sender":"dataprovider_bolt","message":"bolt key store handle created"}
{"level":"info","time":"2021-04-29T20:20:56.237","sender":"dataprovider_bolt","message":"updating bolt database version: 1 -> 2"}
{"level":"info","time":"2021-04-29T20:20:56.240","sender":"dataprovider_bolt","message":"updating bolt database version: 2 -> 3"}
{"level":"info","time":"2021-04-29T20:20:56.242","sender":"dataprovider_bolt","message":"updating bolt database version: 3 -> 4"}
{"level":"info","time":"2021-04-29T20:20:56.244","sender":"dataprovider_bolt","message":"updating bolt database version: 4 -> 5"}
{"level":"info","time":"2021-04-29T20:20:56.246","sender":"dataprovider_bolt","message":"updating bolt database version: 5 -> 6"}
{"level":"debug","time":"2021-04-29T20:20:56.251","sender":"dataprovider_bolt","message":"no admins found, try to create the default one"}
{"level":"debug","time":"2021-04-29T20:20:56.513","sender":"service","message":"HTTP server not started, disabled in config file"}
{"level":"debug","time":"2021-04-29T20:20:56.513","sender":"service","message":"FTP server not started, disabled in config file"}
{"level":"debug","time":"2021-04-29T20:20:56.513","sender":"service","message":"WebDAV server not started, disabled in config file"}
{"level":"debug","time":"2021-04-29T20:20:56.513","sender":"service","message":"telemetry server not started, disabled in config file"}

`
