### ISSUE TITLE
AzuraCast API returns a mess with the latest update

### ISSUE THREAD

**Issue by ruLait** [AzuraCast/AzuraCast#387]
![](https://pp.userapi.com/c830108/v830108891/51cbc/CgMATmR9ee0.jpg)

**Comment by SlvrEagle23** [comment]
@ruLait The nowplaying API endpoint should be fixed now. Thanks for letting me know.

The other issue is unrelated to the recent refactor, and should be created as a new ticket.

**Comment by ruLait** [comment]
@SlvrEagle23 problem also exists with the listeners API endpoint.
![](https://pp.userapi.com/c834104/v834104861/98f28/hxvXTuNaaPw.jpg)
