### ISSUE TITLE
Showing dashboard charts not remembered

### ISSUE THREAD

**Issue by MarkWasley** [AzuraCast/AzuraCast#3884]
If you click to show the charts on the dashboard, it won't be remembered anymore. If you go to other pages, or even refresh the page, the charts will go back to being hidden.

**Comment by xewl** [comment]
Please use the Issue template that was provided during creation of the ticket; as currently, no one knows which version/platform you're having this phenomenon.

**Comment by MarkWasley** [comment]
@xewl I believe it started occuring in the latest stable version 0.12.1 and is still occuring in the rolling releases.
