### ISSUE TITLE
Style for Icecast Pages (Mountpoints)

### ISSUE THREAD

**Issue by grupoexp** [AzuraCast/AzuraCast#3885]
Hello everyone! I am trying to edit the mountpoints page (IP: 8020) to display another completely different way. What is the correct directory to find the Style file? Any recommendations? Thanks for everything!

**Comment by adoboligh1** [comment]
Use An External Nginx Proxy.

**Comment by SlvrEagle23** [comment]
@grupoexp Please continue this discussion on the Discussion you created at about the same time; that's a better place for Q&A items.
