### ISSUE TITLE
Add new Route

### ISSUE THREAD

**Issue by fabricioguedes** [AzuraCast/AzuraCast#389]
I need to customize a new route in AI,
where do I update the routes beyond modules / api / routers.php? Where else do I have to move?

**Comment by SlvrEagle23** [comment]
@fabricioguedes Updating the routes in `modules/api/routes.php` should be sufficient. If you're running on a production instance, the routes are cached in a temporary file named `/var/azuracast/www_tmp/app_routes.cache.php`, which you can flush via `php /var/azuracast/www/util/cli.php cache:clear` or `docker-compose run --rm cli azuracast_cli cache:clear` for traditional and Docker installs, respectively.

**Comment by fabricioguedes** [comment]
@SlvrEagle23  Thanks, as I'm printing a new version of Node.js to update the metadata updates in real time, I'll get a direct reading of the audio metadata to send a socket to the user. I'll add new functionality

**Comment by fabricioguedes** [comment]
@SlvrEagle23 done, but without success qq route the more I add in the file, it drops the application:
"Station not found!"

**Comment by SlvrEagle23** [comment]
@fabricioguedes I'm not sure what routes you're looking to set up, but make sure you follow the [Slim router guidelines](https://www.slimframework.com/docs/objects/router.html) and that the route is set up in the right spot in the file.

**Comment by SlvrEagle23** [comment]
@fabricioguedes I'm closing this issue, but just as a heads-up for yourself and anyone else looking to add custom routes: the most recent refactor of the application has moved all routes to `app/bootstrap/routes.php`, where they are all managed in one location. The routing and middleware have been adapted to much more closely resemble a traditional middleware-based application (as AzuraCast itself now is), so much of what is done there will match what the Slim documentation says should happen.
