### ISSUE TITLE
Liquidsoap Error

### ISSUE THREAD

**Issue by julianodls** [AzuraCast/AzuraCast#3892]
Liquidsoap encontrou um erro
rame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2021/03/09 11:07:25 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2021/03/09 11:07:25 [decoder:3] Method "FFMPEG" accepted "/usr/local/share/icecast/web/error.mp3".
2021/03/09 11:07:25 [sandbox:3] Running inside a docker container, disabling sandboxing..
init: exception encountered during start phase:
Error while trying to bind server/telnet socket: Address already in use in bind()

**Comment by Vaalyn** [comment]
Please fill out the issue template to provide us with all the necessary information that we request from you in the template.

**Comment by Vaalyn** [comment]
Closing since there have been no further replies and the issue template was not used so we don't have enough information to debug.
