### ISSUE TITLE
Update error to 0.12.2

### ISSUE THREAD

**Issue by julianodls** [AzuraCast/AzuraCast#3899]
**Using Docker installation method**
YES

**AzuraCast version**
v0.10.2, #5102ce8 (2020-05-10 7:34) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-21-generic x86_64

TASK [init : Update pip components] **************************************************************************************************fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["/usr/local/bin/pip2", "install", "-U", "pip"], "msg": "\n:stderr: Traceback (most recent call last):\n  File \"/usr/local/bin/pip2\", line 7, in <module>\n    from pip._internal.cli.main import main\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/main.py\", line 60\n    sys.stderr.write(f\"ERROR: {exc}\")\n                                   ^\nSyntaxError: invalid syntax\n"}

https://www.loom.com/share/226d478cf3784d1f8c12bf3e34d0987e

**Comment by SlvrEagle23** [comment]
@julianodls This log message is from the Ansible installation method, not the Docker installation method.

If you're using Docker, just run:
```bash
cd /var/azuracast
./docker.sh update-self
./docker.sh update
```

**Comment by Vaalyn** [comment]
Closing this issue since there has been no response for over 2 weeks.
