### ISSUE TITLE
repeaters 0 listeners

### ISSUE THREAD

**Issue by matteocisilino** [AzuraCast/AzuraCast#3906]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #f09351b (2021-03-11 7:21) • Docker • PHP 7.4 

**Host Operating System**
debian 9.12

**Describe the bug**
in the repeart part , i use icecast
ii  icecast2                        2.4.2-1+deb9u1                    amd64        streaming media server
the mounts report 0 listeners , but in the icecast2 page it reports more then 0 .

I've tried to use the publica page too , and also there no listeners are reported 
the mount points works correctly 

i got 2 remote mounts on a repeater
and public page active 

this stopped after the upgrade on the 9th march 2021
and stil exist on the version described

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context**

**Comment by matteocisilino** [comment]
solved , 
retriving the xml from remote icecast don't support redirections ( 302, 301 ).
If you have the remote relay on a server that make redirects, you must set in the remote relay url the full host ( target of redirect )

**Comment by Vaalyn** [comment]
Closing as resolved
