### ISSUE TITLE
listeners data on google maps with icecast connection not showing correct

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#391]
Hello,

I made live stream connection with icecast,all is working well, but i dont get the country and the real ip displayed. This is what i get:

Ip:172.18.0.3 
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 
Location:  private range

How to fix this and get the real info as it does with a  shoutcast connection.

**Comment by SlvrEagle23** [comment]
@surihost This is still a pending issue relating to #293. Turn off any proxying and connect directly to the IceCast server if you need listener IP information until the issue is resolved.
