### ISSUE TITLE
Server error repeating over and over 

### ISSUE THREAD

**Issue by AshleyinSpain** [AzuraCast/AzuraCast#3913]
**Using Docker installation method**

Yes

**AzuraCast version**

v0.12.2 Stable

**Host Operating System**

Ubuntu 20.04

**Describe the bug**

web_1                      | 2021/03/12 20:30:33 [error] 56#56: *6682 open() "/usr/share/nginx/html/pub/summer_grooves_-_copy_02" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "POST /pub/summer_grooves_-_copy_02 HTTP/1.1", host: "localhost:9010"

**To Reproduce**

It references a cloned station set up as
Summer Grooves - Copy 02
Copy Media? = Share the same folder 
Copy Playlists? = No
Copy Streamer/DJ Accounts? = No 
Copy Permissions? = YES

The station plays

**Expected behavior**

No Errors in logs

**Relevant Logs**

web_1                      | 2021/03/12 20:30:33 [error] 56#56: *6682 open() "/usr/share/nginx/html/pub/summer_grooves_-_copy_02" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "POST /pub/summer_grooves_-_copy_02 HTTP/1.1", host: "localhost:9010"

**Screenshots**

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context**

The station plays

Is this a real problem

**Comment by Vaalyn** [comment]
It doesn't look like anything is going wrong and there are no other problems mentioned.

Closing this issue.

If you notice anything that's not working feel free to create a new issue and mention this one here.
