### ISSUE TITLE
CPU / RAM problem

### ISSUE THREAD

**Issue by la-roleplay** [AzuraCast/AzuraCast#3915]
**Using Docker installation method**

Yes

**AzuraCast version**

Rolling Release #cb990c1 (2021-03-12 11:56)

**Host Operating System**

Ubuntu 16.04

**Describe the bug**

I turn on the radio and after ten minutes the server starts to raise the CPU / RAM to 100%. The radio stops working and the web cannot be accessed.

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

https://i.gyazo.com/7a8fbe3e2a5ca6fb2776d34ef648050b.png
https://i.gyazo.com/a1a2e740ba28d3a104f16857eeec0e6a.png
https://i.gyazo.com/95cb1520b9807ee3c46b3292e08ea29a.png
https://i.gyazo.com/8e24708a0065ad1c68348246dc9a2e64.png
https://i.gyazo.com/5fe63746611e1c9028639a8b02a583b5.png
https://i.gyazo.com/5027346dfafb1fe98187d713c15ac8d9.png
https://i.gyazo.com/f8e9aec3aecfb555d5ff28f47774ca46.png

New:
https://i.gyazo.com/847eb86e7be799a95b506bb64a25aa7d.png
https://i.gyazo.com/6dc9189e1aab0fd95fca78d98004abf0.png

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context**

This error happens since they modified "worker connection"

**Comment by SlvrEagle23** [comment]
This was already discussed in Discord; the long and short of it is that increasing the worker connections didn't suddenly cause your system to spike to 100% CPU/RAM, but it caused your existing load of users (many of whom likely were unable to connect with the previous settings) to be able to connect, which led to your resources accurately reflecting how many resources your station requires.

You can override the nginx configuration if absolutely necessary, but other solutions were proposed to help accommodate this on even an economy VPS, including taking advantage of swap space to avoid RAM thrashing.
