### ISSUE TITLE
nginx.conf

### ISSUE THREAD

**Issue by atmix** [AzuraCast/AzuraCast#3916]
Hello. Wanted to edit nginx file to set up proxy pass but this command doesn't work.
```
version : '2.2'

services:
  web:
    volumes:
     - /var/azuracast/azuracast-nginx.conf:/etc/nginx/conf.d/azuracast.conf:ro
```

**Comment by la-roleplay** [comment]
You must search for the container with: docker ps -a
You enter the container with: docker exec -it CONTAINERID bash
and once inside you go to /etc/nginx/nginx.conf. Edit it with vi nginx.conf

**Comment by atmix** [comment]
Solution here https://github.com/AzuraCast/AzuraCast/issues/3902#issue-827550661
