### ISSUE TITLE
Next song does not match the playing queue

### ISSUE THREAD

**Issue by agonzalo36r** [AzuraCast/AzuraCast#3917]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.12.2

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
I made a livestream, with the option of record live streams activated. After stopping the stream via the client I'm using (butt), I go to see the files recorded, and the last emision still appears as live. Also, when I use the next song button, I got an "League\Flysystem\FileExistsException at /var/azuracast/www/vendor/league/flysystem/src/Filesystem.php L405: File already exists at path: gonzalo/20210312-195000.mp3" message, with the date of the file matching the start time of the last stream. This prevent me not only to skip a song, but I think is affecting the playing queue, which doesn't match to the songs played next and not loading the correct cover art of the songs.

Also, on the logs, I get similar messages for every song played:
2021/03/13 12:00:48 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/buquetrece_radio/media/n0045_nameofsong.mp3".
2021/03/13 12:00:48 [lang:3] AzuraCast Raw Response: Error: File already exists at path: gonzalo/20210312-195000.mp3 on /var/azuracast/www/vendor/league/flysystem/src/Filesystem.php L405
2021/03/13 12:00:48 [lang:3] AzuraCast Feedback Response: OK

I've tried to erase the last emission, but it keeps appearing.

**Expected behavior**
After finishing a livestream, the playing queue should work as usual.

**Relevant Logs**
2021/03/13 12:00:47 [ffmpeg:3] [mp3float @ 0x7fa3c84cb080] Could not update timestamps for discarded samples.
2021/03/13 12:00:48 [playlist_mundiales:3] Prepared "/var/azuracast/stations/buquetrece_radio/media/m0038_bloodorange_besttoyou.mp3" (RID 6).
2021/03/13 12:00:48 [standard_playlists:3] Switch to cue_playlist_lista_nacionales_aprobadas with forgetful transition.
2021/03/13 12:00:48 [ffmpeg:3] [mp3float @ 0x7fa3c8b57f80] Could not update timestamps for skipped samples.
2021/03/13 12:00:48 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/buquetrece_radio/media/n0045_jeanpaulmedroaftsolosantiago_nomepreguntesxq.mp3".
2021/03/13 12:00:48 [lang:3] AzuraCast Raw Response: Error: File already exists at path: gonzalo/20210312-195000.mp3 on /var/azuracast/www/vendor/league/flysystem/src/Filesystem.php L405
2021/03/13 12:00:48 [lang:3] AzuraCast Feedback Response: OK
2021/03/13 12:03:08 [ffmpeg:3] [mp3float @ 0x7fa3c8b57f80] Could not update timestamps for discarded samples.
2021/03/13 12:03:08 [playlist_lista_nacionales_aprobadas:3] Prepared "/var/azuracast/stations/buquetrece_radio/media/n0045_jeanpaulmedroaftsolosantiago_nomepreguntesxq.mp3" (RID 7).
2021/03/13 12:03:08 [standard_playlists:3] Switch to cue_playlist_mundiales with forgetful transition.
2021/03/13 12:03:08 [ffmpeg:3] [mp3float @ 0x7fa3c856b700] Could not update timestamps for skipped samples.
2021/03/13 12:03:08 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/buquetrece_radio/media/m0059_clevergirl_teleblister.mp3".
2021/03/13 12:03:09 [lang:3] AzuraCast Raw Response: Error: File already exists at path: gonzalo/20210312-195000.mp3 on /var/azuracast/www/vendor/league/flysystem/src/Filesystem.php L405
2021/03/13 12:03:09 [lang:3] AzuraCast Feedback Response: OK

**Screenshots**
This appears everythime I try to skip a song:
![image](https://user-images.githubusercontent.com/51273601/111037950-62561680-83f4-11eb-8ccb-7e0ec1bfe84f.png)

This appears on the emissions of my stream user (I'm not currently streaming):
![image](https://user-images.githubusercontent.com/51273601/111037979-831e6c00-83f4-11eb-83e5-fac0fb6a8d82.png)

I hope you can help me with this. Thanks a lot for this software and for reading to this point :)

**Comment by Vaalyn** [comment]
Is this still happening on the newest rolling-release version?
