### ISSUE TITLE
ACC+ at 48 kbps?

### ISSUE THREAD

**Issue by multi023** [AzuraCast/AzuraCast#392]
Hi,

I think it would be very interesting to be able to emit at 48 kbps because many telephone operators, once the limits of data use have been exceeded, allow us to continue using data at 54 kbps or less.

Would it be possible to add this bitrate?

Thank you very much. Greetings,

**Comment by SlvrEagle23** [comment]
@multi023 Makes perfect sense to me. Added for all mount types.
