### ISSUE TITLE
2 Issues with queue builder

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#3926]
**Using Docker installation method**
No

**AzuraCast version**
Rolling Release #cb990c1 (2021-03-12 11:56)

**Host Operating System**
20.04.2 LTS

**Describe the bug**
Hey! First of all thanks for the last update. With the update you fix my issues #3541 #3549 #3673
- Now there is only 2 problems with the queue left. #2972 where the play next song is sometimes wrong. Happens on every 5-7 songs and fixes for some time, then again.
- ~~And another issue that i mention here: https://github.com/AzuraCast/AzuraCast/issues/3673#issuecomment-767426663 .
It's about that somehow the queue is filling with a lot of songs. Maybe unplayed song, and mysql is not deleting them. Right now i have amount of 164 songs in the queue table (see the screenshot) for about 7 hours of playing (after the update).
EDIT: And it's growing, without the station stop problem. It looks like the old problem is fixed, but its really didn't delete the played entries.~~
- And as we talking about mysql, i still notice empty tables, or tables with small amount of inserts, that are taking of a lot of space. Like `messenger_messages`, see the second screenshot. One time i found it with 0 inserts and location around 250mb. The fix for this is easy. You can send a cron job to optimize the tables on every 12hours for example. After the optimize, the whole database become 22mb again.

~~EDIT2: Again strange activity with play now and the queue. Take a look at screenshot 3.
It was playing song with id 169, then 170. After that it skip to song 172 `BUT` playing audio of 172 and displaying the play now info of song 182 (name and artwork). Then it continues with 173, 174 ... 181 with the right names. Then skip to 183 because 182 was already with `sent_to_autodj`=1.~~

Sorry for everything! I know i'm the guy with the problems but it seems so strange to me, and i don't know how nobody don't have this problem too (or maybe didn't notice).

**Screenshots**
![](https://i.imgur.com/6g7M4Qc.png)

![](https://i.imgur.com/ZxsKxvd.png)

![](https://i.imgur.com/r9FHX0f.png)

**Device(s):**
- Device: Raspberry Pi 3b

**Comment by SlvrEagle23** [comment]
@NicoxDJ The issue with the queue being "full" is actually fully intentional; it's how we fix a number of queue issues, by just tracking our own internal queue independent from the one we report in Song History, which is based on what Liquidsoap/Icecast reports back to me, and thus has a much higher tendency to miss things (and deliberately misses "jingle mode" playlists, for example, which our own queue doesn't). The distinguishing factor is the `sent_to_autodj` flag; anything with `0` as its value is in the "upcoming" queue, sorted by `timestamp_cued`.

You don't happen to be using S3 or Dropbox for your media storage do you? That may be a cause of the songs occasionally mismatching from the "playing next" that we indicate.

**Comment by NicoxDJ** [comment]
@SlvrEagle23 Ok, will `station_queue` table do some truncate over 24hrs or will reach the maximum integer someday? i'm using mounted folder inside the media folder from NAS storage. And what about the playing next song? Liqudsoap is playing always the songs from the `station_queue` in the right direction, but some times playing next `API` shows wrong song.

**Comment by SlvrEagle23** [comment]
@NicoxDJ Yes, the `station_queue` will auto-truncate using the exact same setting you have for `song_history`, so both will be about the same size and it shouldn't grow too long.

**Comment by NicoxDJ** [comment]
@SlvrEagle23 OK, i strikethrough this one in the original issue post. Please, when you have time, check the playing next API builder.
