### ISSUE TITLE
Prevent Docker from updating iptables

### ISSUE THREAD

**Issue by Jaadoo13** [AzuraCast/AzuraCast#3927]
Hello.
Does anybody know, how to prevent Docker from updating iptables?
The reason is, i want to block Countries and it works great. as long Docker don't update iptables.

thx.

**Comment by appnostic-io** [comment]
Hi,

Unfortunately this logic is deep inside the docker codebase but there are some options for you.  I assume your [whatever_blocks_the_countries] is running on the host so if that's the case one option is to containerize it and run it alongside your AzuraCast in the stack and as a dependency.

The container will need some slightly elevated privileges and mounts as well as iptables package (alpine will work fine for this) but its definitely possible.

**Comment by Jaadoo13** [comment]
Before i reinstalled my server, i had great iptables with geoip which worked. But ive forgotten to save it before. 
I have a new Problem, now. Because whatever i put into iptables, it will not block the reaching of docker sites. But its very Important to block some countries. Normally US, too. But US have to be free because of Lets Encrypt. Why it will not Block my docker site anymore? Her are my iptables rules...:
`root@server:~# iptables -S
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-N DOCKER
-N DOCKER-ISOLATION-STAGE-1
-N DOCKER-ISOLATION-STAGE-2
-N DOCKER-USER
-A INPUT -d 81.x.x.x/32 -p tcp -m tcp --dport 443 -m geoip --source-country DE,US  -j ACCEPT
-A INPUT -d 81.x.x.x/32 -p tcp -m tcp --dport 80 -m geoip --source-country DE,US  -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp ! --tcp-flags FIN,SYN,RST,ACK SYN -j REJECT --reject-with tcp-reset
-A INPUT -m state --state INVALID -j DROP
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8443 -m geoip --source-country DE,US  -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8880 -m geoip --source-country DE,US  -j ACCEPT
-A INPUT -p tcp -m tcp --dport 21 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 25 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 465 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 110 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 995 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 143 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 993 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 106 -j DROP
-A INPUT -p tcp -m tcp --dport 3306 -j DROP
-A INPUT -p tcp -m tcp --dport 5432 -j DROP
-A INPUT -p tcp -m tcp --dport 9008 -j DROP
-A INPUT -p tcp -m tcp --dport 9080 -j DROP
-A INPUT -p udp -m udp --dport 137 -j DROP
-A INPUT -p udp -m udp --dport 138 -j DROP
-A INPUT -p tcp -m tcp --dport 139 -j DROP
-A INPUT -p tcp -m tcp --dport 445 -j DROP
-A INPUT -p udp -m udp --dport 1194 -j DROP
-A INPUT -p udp -m udp --dport 53 -j DROP
-A INPUT -p tcp -m tcp --dport 53 -j DROP
-A INPUT -p icmp -m icmp --icmp-type 8/0 -j ACCEPT
-A INPUT -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -m geoip --source-country DE,CH  -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -m geoip ! --source-country DE,AT,CH,US  -j DROP
-A INPUT -p tcp -m tcp --dport 80 -m geoip ! --source-country DE,AT,CH,US  -j DROP
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o br-ee5da3c3e62a -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o br-ee5da3c3e62a -j DOCKER
-A FORWARD -i br-ee5da3c3e62a ! -o br-ee5da3c3e62a -j ACCEPT
-A FORWARD -i br-ee5da3c3e62a -o br-ee5da3c3e62a -j ACCEPT
-A FORWARD -o br-c8256f44983f -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o br-c8256f44983f -j DOCKER
-A FORWARD -i br-c8256f44983f ! -o br-c8256f44983f -j ACCEPT
-A FORWARD -i br-c8256f44983f -o br-c8256f44983f -j ACCEPT
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -p tcp -m tcp ! --tcp-flags FIN,SYN,RST,ACK SYN -j REJECT --reject-with tcp-reset
-A FORWARD -m state --state INVALID -j DROP
-A FORWARD -i lo -o lo -j ACCEPT
-A FORWARD -j DROP
-A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp ! --tcp-flags FIN,SYN,RST,ACK SYN -j REJECT --reject-with tcp-reset
-A OUTPUT -m state --state INVALID -j DROP
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -j ACCEPT
-A OUTPUT -d 81.x.x.x/32 -p tcp -m tcp --dport 80 -m geoip --source-country DE,US  -j ACCEPT
-A OUTPUT -d 81.x.x.x/32 -p tcp -m tcp --dport 443 -m geoip --source-country DE,US  -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 443 -m geoip ! --source-country DE,AT,CH,US  -j DROP
-A DOCKER -d 172.19.0.4/32 -p tcp -m tcp --dport 80 -m geoip --source-country DE,US  -j ACCEPT
-A DOCKER -d 172.19.0.4/32 -p tcp -m tcp --dport 443 -m geoip --source-country DE,US  -j ACCEPT
-A DOCKER -d 172.18.0.2/32 -p tcp -m tcp --dport 80 -m geoip --source-country DE,US  -j ACCEPT
-A DOCKER -d 172.18.0.2/32 -p tcp -m tcp --dport 443 -m geoip --source-country DE,US  -j ACCEPT
-A DOCKER -d 172.21.0.4/32 ! -i br-550ea8cc2888 -o br-550ea8cc2888 -p tcp -m tcp --dport 443 -m geoip --source-country DE,US  -j ACCEPT
-A DOCKER -d 172.21.0.4/32 ! -i br-550ea8cc2888 -o br-550ea8cc2888 -p tcp -m tcp --dport 80 -m geoip --source-country DE,US  -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8135 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8130 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8125 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8116 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8115 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8110 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8106 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8105 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8100 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8096 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8095 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8090 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8076 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8075 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8070 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8066 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8065 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8060 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8056 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8055 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8050 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8046 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8045 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8040 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8036 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8035 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8030 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8026 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8025 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8020 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8016 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8015 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8010 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8006 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8005 -j ACCEPT
-A DOCKER -d 172.24.0.4/32 ! -i br-c8256f44983f -o br-c8256f44983f -p tcp -m tcp --dport 8000 -j ACCEPT
-A DOCKER -p tcp -m tcp --dport 80 -m geoip --source-country DE,US  -j ACCEPT
-A DOCKER -p tcp -m tcp --dport 443 -m geoip --source-country DE,US  -j ACCEPT
-A DOCKER -m geoip --source-country DE,US  -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i br-ee5da3c3e62a ! -o br-ee5da3c3e62a -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i br-c8256f44983f ! -o br-c8256f44983f -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o br-ee5da3c3e62a -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o br-c8256f44983f -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN
`

**Comment by Jaadoo13** [comment]
In this case i found it out, now.
you have to edit /etc/docker/deamon.json
change iptables: true, to false and save it.
but before azuracast updates, it could be better to allowed it again.
