### ISSUE TITLE
Azura cast does not install

### ISSUE THREAD

**Issue by hspeijer** [AzuraCast/AzuraCast#3934]
**Using Docker installation method**

Yes

**AzuraCast version**

AzuraCast/AzuraCast/master

**Host Operating System**

Ubuntu 18 LTS

**Describe the bug**

Does not install on clean ubuntu install

**To Reproduce**

root@h2929828:/var/azuracast# ./docker.sh install
Docker is already installed! Continuing...
Docker Compose does not appear to be installed. Install Docker Compose now? [Y/n] 
Writing default .env file...
Prefer stable release versions of AzuraCast? [y/N] y
Creating default AzuraCast settings file...
Retrieving default docker-compose.yml file...
Customize AzuraCast ports? [y/N] 
Set up LetsEncrypt? [y/N] y
Domain name (example.com) or names (example.com,foo.bar) to use with LetsEncrypt []: radio.greentribe.nl
Optional e-mail address for expiration updates []: hanso@greentribe.nl
Pulling mariadb                 ... done
Pulling redis                   ... done
Pulling stations                ... done
Pulling web                     ... done
Pulling nginx_proxy             ... done
Pulling nginx_proxy_letsencrypt ... done
Creating network "azuracast_backend" with driver "bridge"
Creating network "azuracast_frontend" with driver "bridge"
Creating volume "azuracast_nginx_proxy_vhosts" with default driver
Creating volume "azuracast_db_data" with default driver
Creating volume "azuracast_letsencrypt" with default driver
Creating volume "azuracast_letsencrypt_html" with default driver
Creating volume "azuracast_letsencrypt_acme" with default driver
Creating volume "azuracast_shoutcast2_install" with default driver
Creating volume "azuracast_geolite_install" with default driver
Creating volume "azuracast_sftpgo_data" with default driver
Creating volume "azuracast_station_data" with default driver
Creating volume "azuracast_www_vendor" with default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_redis_data" with default driver
Creating volume "azuracast_backups" with default driver
Creating azuracast_stations ... 
Creating azuracast_stations ... error
Creating azuracast_redis    ... done
WARNING: Host is already in use by another container

Creating azuracast_mariadb  ... done
acast_stations (a030fc1770b39986c98de2b6678437b014214527e48a39793c172d29cd627579): Error starting userland proxy: 

ERROR: for stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (a030fc1770b39986c98de2b6678437b014214527e48a39793c172d29cd627579): Error starting userland proxy: 
ERROR: Encountered errors while bringing up the project.
azuracast_mariadb is up-to-date
Starting azuracast_stations ... 
azuracast_redis is up-to-date
Starting azuracast_stations ... error

ERROR: for azuracast_stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (c2b3e0c2219dd55d89ed2d75ab4110850fb74281e02b8c0cd52f7f931ac95058): Error starting userland proxy: 

ERROR: for stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (c2b3e0c2219dd55d89ed2d75ab4110850fb74281e02b8c0cd52f7f931ac95058): Error starting userland proxy: 
ERROR: Encountered errors while bringing up the project.

**Expected behavior**

A clean install

**Relevant Logs**

**Screenshots**

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context**

**Comment by SC2Mitch** [comment]
Is anything running on port 80? If yes, you'll need to change it before installing AzuraCast.

**Comment by SlvrEagle23** [comment]
@hspeijer This error may indicate there's something using one of the existing ports that the standard AzuraCast installation tries to open; many of the ports are in the range between 8000 and 8500 (excluding 8080, as that's commonly used). You can often view what's listening on given ports by running `netstat -tulpn`.

**Comment by hspeijer** [comment]
Nothing is listening on port 80. All that is currently running is sshd.

`# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      330/sshd            
tcp6       0      0 :::22                   :::*                    LISTEN      330/sshd`

I will investigate further.

**Comment by hspeijer** [comment]
When I start directly using docker compose I get

```
ERROR: for azuracast_stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (7a6e3a1a486904fb7ed5d8c7dc98b767d3761b4795ea6a84743a1dd110fdf188):  (iptables failed: iptables --wait -t filter -A DOCKER ! -i br-197c026e007b -o br-197c026e007b -p tcp -d 172.19.0.2 --dport 8250 -j ACCEPT:  (fork/exec /sbin/iptables: resource temporarily unavailable))
```

**Comment by hspeijer** [comment]
Maybe something is wrong with my docker network environment since I would expect listening ports for the running redis and mariadb?

```
root@h2929828:/var/azuracast# docker ps -a
CONTAINER ID   IMAGE                              COMMAND                  CREATED       STATUS       PORTS      NAMES
50defe89ce48   azuracast/azuracast_redis:stable   "docker-entrypoint.s…"   12 days ago   Up 12 days   6379/tcp   azuracast_redis
efaca72126dd   azuracast/azuracast_radio:stable   "/usr/bin/supervisor…"   12 days ago   Created                 azuracast_stations
a1288285b5f6   azuracast/azuracast_db:stable      "dockerize -template…"   12 days ago   Up 12 days   3306/tcp   azuracast_mariadb
```

**Comment by hspeijer** [comment]
In case this is useful here is my docker version info:

```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:05 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:00 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by hspeijer** [comment]
These log statements seem related/relevant from syslog
```
Apr  1 03:37:03 h2929828 systemd-networkd[151]: vethca537b1: Link UP
Apr  1 03:37:03 h2929828 systemd-udevd[1196]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Apr  1 03:37:03 h2929828 systemd-udevd[1196]: Could not generate persistent MAC address for vethca537b1: No such file or directory
Apr  1 03:37:03 h2929828 systemd-udevd[1195]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Apr  1 03:37:03 h2929828 systemd-udevd[1195]: Could not generate persistent MAC address for vethe0be8c0: No such file or directory
Apr  1 03:37:06 h2929828 dockerd[508]: time="2021-04-01T03:37:06.859711145+02:00" level=warning msg="Failed to allocate and map port 8240-8240: Error starting userland proxy: "
Apr  1 03:37:08 h2929828 systemd-networkd[151]: vethca537b1: Link DOWN
Apr  1 03:37:10 h2929828 dockerd[508]: time="2021-04-01T03:37:10.448219997+02:00" level=error msg="74a7044f459e2d9674ebfbb47ce83220fb71f65432ec51f08626ef3bdbff55b1 cleanup: failed to delete container from containerd: no such container"
Apr  1 03:37:10 h2929828 dockerd[508]: time="2021-04-01T03:37:10.448881003+02:00" level=error msg="Handler for POST /v1.25/containers/74a7044f459e2d9674ebfbb47ce83220fb71f65432ec51f08626ef3bdbff55b1/start returned error: driver failed programming external connectivity on endpoint azuracast_stations (8b95f2a9323ed6363784ce742ebc6f49776940820ce5c7f441c679e3d86ab233): Error starting userland proxy: "
```

**Comment by hspeijer** [comment]
Trying a second time after the 'userland proxy' error gives
```
Apr  1 03:39:58 h2929828 systemd-networkd[151]: veth73f595e: Link UP
Apr  1 03:39:58 h2929828 systemd-udevd[2870]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Apr  1 03:39:58 h2929828 systemd-udevd[2870]: Could not generate persistent MAC address for veth73f595e: No such file or directory
Apr  1 03:39:58 h2929828 systemd-udevd[2869]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Apr  1 03:39:58 h2929828 systemd-udevd[2869]: Could not generate persistent MAC address for vethbd2027a: No such file or directory
Apr  1 03:39:59 h2929828 dockerd[508]: time="2021-04-01T03:39:59.866775545+02:00" level=warning msg="Failed to allocate and map port 8245-8245:  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8245 -j DNAT --to-destination 172.18.0.4:8245 ! -i br-d14dfd5cc19d:  (fork/exec /sbin/iptables: resource temporarily unavailable))"
Apr  1 03:40:04 h2929828 systemd-networkd[151]: veth73f595e: Link DOWN
Apr  1 03:40:04 h2929828 dockerd[508]: time="2021-04-01T03:40:04.961437007+02:00" level=error msg="74a7044f459e2d9674ebfbb47ce83220fb71f65432ec51f08626ef3bdbff55b1 cleanup: failed to delete container from containerd: no such container"
Apr  1 03:40:04 h2929828 dockerd[508]: time="2021-04-01T03:40:04.962304092+02:00" level=error msg="Handler for POST /v1.25/containers/74a7044f459e2d9674ebfbb47ce83220fb71f65432ec51f08626ef3bdbff55b1/start returned error: driver failed programming external connectivity on endpoint azuracast_stations (b42ea0be5a12d38a9c95614bad9d93e4532d4a51f2921a9edca30169e04b44a7):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8245 -j DNAT --to-destination 172.18.0.4:8245 ! -i br-d14dfd5cc19d:  (fork/exec /sbin/iptables: resource temporarily unavailable))"
```

**Comment by hspeijer** [comment]
I think I might be onto something.. Followed this thread: https://github.com/moby/moby/issues/22614 and disabled the userland proxy.

**Comment by hspeijer** [comment]
I have a running AzureCast server! http://radio.greentribe.nl The magic line was:

```
echo "{\"userland-proxy\":false}" > /etc/docker/daemon.json
sudo systemctl restart docker
```

**Comment by SC2Mitch** [comment]
It appears that the user has since resolved this issue, tag me directly if your having issues or make another ticket, thanks.
