### ISSUE TITLE
File uploaded through FTP with £ $ can break file locations

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#3935]
**Using Docker installation method**
Yes 

**AzuraCast version**
Rolling Release #777e229  

**Host Operating System**
Ubuntu 20.04 

**Describe the bug**
In rare circumstances it appears that files with the $ or £ can break AzuraCast's Media directory, resulting in a error 500 file not found  at path, I've included a exact excerpt of the log. 

**To Reproduce**
Upload a file through FTP with a $ £ ! " at the start of it
Go to the Media Directory
Review the errors showing, you need to open the debug logs. 

**Expected behavior**
The music files page should load regardless of files missing or throw a more gentle warning

**Relevant Logs**
```
code: 500
extra_data: []
formatted_message: "<b>League\Flysystem\FileNotFoundException at /var/azuracast/www/vendor/league/flysystem/src/Filesystem.php L389:</b> File not found at path: $tupid Young - Slide For This (Audio) (feat. TayF3rd, O.T. Genasis, DW Flame & Saviii 3rd).mp3"
message: "League\Flysystem\FileNotFoundException at /var/azuracast/www/vendor/league/flysystem/src/Filesystem.php L389: File not found at path: $tupid Young - Slide For This (Audio) (feat. TayF3rd, O.T. Genasis, DW Flame & Saviii 3rd).mp3"
success: false
[00:17]
```

**Screenshots**
https://puu.sh/Hqx7o/e77bbd84a3.png
![image](https://user-images.githubusercontent.com/29955942/111770152-f6672880-88a1-11eb-93b4-c95a8c925f38.png)
Media Files not loading
![image](https://user-images.githubusercontent.com/29955942/111770190-01ba5400-88a2-11eb-8cf1-c41d8fea9f51.png)

Error page

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch I can't reproduce this locally...I uploaded a file starting with `$` to both the base directory and a subfolder of a station and both loaded in the media manager without any issue.

**Comment by SC2Mitch** [comment]
How strange, is there any technical reason as to why the whole folder will refuse to load if it's missing a single file?

**Comment by SlvrEagle23** [comment]
@SC2Mitch If it's throwing an exception that's not caught properly, then that could definitely prevent the directory from listing correctly. We don't expect to not be able to get information on files that we _just_ confirmed were there in the directory listing, though, which is why this is so unusual.

**Comment by SC2Mitch** [comment]
It's very strange, even after I nuked the whole music file folder and done all the sync checks, it still renders my folder unavailable with it still trying to locate the file *after its fully deleted* which makes me even more confused. I'll do more testing to try and figure out exactly what is triggering this strange behaviour.

**Comment by SlvrEagle23** [comment]
@SC2Mitch Try clearing the cache from the Admin > System Debugger page. Should flush any remaining cache that has it listed.

**Comment by SC2Mitch** [comment]
Seems to be working now, I'll keep a close eye on it if it re-occurs again, cheers Silver.
