### ISSUE TITLE
update error!

### ISSUE THREAD

**Issue by adoboligh1** [AzuraCast/AzuraCast#3937]
Installation Method : Docker

OS : Ubuntu 20.04 LTS

RAM : 16 GB

CORES : 8

AZURACAST UPDATE ERROR!

Error Log Below

WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
Creating network "stable_backend" with driver "bridge"
Creating network "stable_frontend" with driver "bridge"
Creating azuracast_mariadb  ... error                                                                                                                                                           Creating azuracast_stations ...

ERROR: for azuracast_mariadb  Cannot create container for service mariadb: Conflict. The container name "/azuracast_mariadb" is already in use by container "ee578769d230ab6ce94d2307825aa94f961Creating azuracast_stations ... error                                                                                                                                                           Creating azuracast_redis    ...

ERROR: for azuracast_stations  Cannot create container for service stations: Conflict. The container name "/azuracast_stations" is already in use by container "4e03e6ae2560c50b06f2566bf981036dCreating azuracast_redis    ... error                                                                                                                                                           
ERROR: for azuracast_redis  Cannot create container for service redis: Conflict. The container name "/azuracast_redis" is already in use by container "94fcd39024a68f94dc68712f2d73ef36e99573681c164ef8f67c1264e074e0a4". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for mariadb  Cannot create container for service mariadb: Conflict. The container name "/azuracast_mariadb" is already in use by container "ee578769d230ab6ce94d2307825aa94f9613fc1a18937b63349fa0a8963428f4". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for stations  Cannot create container for service stations: Conflict. The container name "/azuracast_stations" is already in use by container "4e03e6ae2560c50b06f2566bf981036dc5b996063652b77f4e50214b6cea0e85". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for redis  Cannot create container for service redis: Conflict. The container name "/azuracast_redis" is already in use by container "94fcd39024a68f94dc68712f2d73ef36e99573681c164ef8f67c1264e074e0a4". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.

DOCKER IMAGES

REPOSITORY                                    TAG       IMAGE ID       CREATED        SIZE
azuracast/azuracast_web_v2                    latest    4b9c4b41d61f   10 hours ago   663MB
azuracast/azuracast_nginx_proxy_letsencrypt   latest    00062c8b98b9   9 days ago     24.4MB
azuracast/azuracast_nginx_proxy               latest    0013c526d489   9 days ago     63.1MB
azuracast/azuracast_redis                     latest    16f2042a9495   9 days ago     32.4MB
azuracast/azuracast_db                        latest    bc00bcdfa5bf   9 days ago     452MB
azuracast/azuracast_radio                     stable    ec315d78d8fa   9 days ago     1.14GB
azuracast/azuracast_radio                     latest    4443d1a237a0   9 days ago     1.14GB
azuracast/azuracast_redis                     stable    42bc69b16437   10 days ago    32.3MB
azuracast/azuracast_web_v2                    stable    4b0050658d7a   10 days ago    663MB
azuracast/azuracast_nginx_proxy               stable    0f66e38eea64   10 days ago    56.3MB
jc21/nginx-proxy-manager                      latest    066af0708929   4 weeks ago    809MB
jc21/mariadb-aria                             latest    9b987f90dc35   5 weeks ago    217MB
jrcs/letsencrypt-nginx-proxy-companion        latest    6fb78d916762   6 weeks ago    25.7MB
azuracast/azuracast_db                        stable    19f4e70dad9d   6 weeks ago    457MB
azuracast/azuracast_nginx_proxy_letsencrypt   stable    60ed55bf245f   2 months ago   24.3MB

**Comment by SlvrEagle23** [comment]
@adoboligh1 The update process should be turning off any Docker images before updating them. Did you move the directory it's stored in or make any other changes?

**Comment by adoboligh1** [comment]
> @adoboligh1 The update process should be turning off any Docker images before updating them. Did you move the directory it's stored in or make any other changes?

I only changed the port thats all, followed the update process but still getting this error.
