### ISSUE TITLE
Please Add Album field to Request show list and search option

### ISSUE THREAD

**Issue by unbreakhyek** [AzuraCast/AzuraCast#394]
could you add to request songs search the album field?

I hope you can add this feature.

And if possible, I want to have a way to limit the duplicate songs request within a certain time.

thanks.

**Comment by SlvrEagle23** [comment]
@unbreakhyek Done! The album was already returned as part of the API response, so adding it was simple.

As for the request limits per song, those already exist and you can configure the threshold for how recently a song must be played before it can be requested again on the station's profile.
