### ISSUE TITLE
Embedded player themes not working.

### ISSUE THREAD

**Issue by BPike-KueMedia** [AzuraCast/AzuraCast#3949]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #69cc051 (2021-03-19 14:11)

**Host Operating System**
Linux Debian 10 (Linode)

**Describe the bug**
Using the generated embedded iframe works but the Light/Dark themes do not work

**To Reproduce**
Add the generated iFrame to a website.

**Expected behavior**
Dark/Light Themes to work and the player to have a box like appearance? 

**Relevant Logs**
`DevTools failed to load SourceMap: Could not load content for https://stream.kueradio.com.au/static/dist/lib/bootstrap/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Screenshots**
![image](https://user-images.githubusercontent.com/81078816/112093951-6c46f900-8bee-11eb-8356-238aa82097d1.png)

**Device(s):**

- Device: Desktop
- OS: Win 10
- Browser: Chrome/Firefox
- Version: Latest

**Additional context**

**Comment by ErnestPH** [comment]
The embed player is different from the station's default player. You may have to add CSS code to style it...
Of if you want the box type player, remove the **embed** on the iframe code

So it's something like this instead...
`<iframe src="https://yoursite.com/public/station_name/" frameborder="0" allowtransparency="true" style="width: 100%; min-height: 150px; border: 0;"></iframe>`

Adjust the height if needed...

**Comment by SlvrEagle23** [comment]
The specific embed code for the embeddable version of the player looks like:

> `<iframe src="https://azuracast.local/public/azuratest_radio/embed?theme=light" frameborder="0" allowtransparency="true" style="width: 100%; min-height: 150px; border: 0;"></iframe>`

You can view and customize the embeddable components from the "Embed Widgets" button on the station profile. Changing the "theme" with embeds just changes the expected background color (while the embed itself remains transparent).
