### ISSUE TITLE
I updated and now it doesn't work.

### ISSUE THREAD

**Issue by la-roleplay** [AzuraCast/AzuraCast#3954]
**Using Docker installation method**

Yes

**AzuraCast version**

Last version.

**Host Operating System**

Ubuntu 20.04

**Describe the bug**

I updated and now it doesn't work.

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

https://i.gyazo.com/805728a21c82d7dd9d1b9e74fb511443.png
https://i.gyazo.com/545205247a60035edfe7822ab3f29e2d.png

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@la-roleplay Please try updating again; this was caused by a known issue that has since been fixed.
