### ISSUE TITLE
Public Pages show stream offline even while broadcasting is enabled and has a source (playing) Icecast

### ISSUE THREAD

**Issue by fritexvz** [AzuraCast/AzuraCast#3960]
**Using Docker installation method**
Yes

**AzuraCast version**
 v0.12.2

**Host Operating System**
 Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-70-generic x86_64)

**Describe the bug**
Using Icecast and streaming via source of my computer through Sound Empire Caster.
When broadcasting is enabled like via Icecast and autodj disabled, playlist disabled, Stream shows offline on public pages.

Tested with multiple browsers from laptop, mobile, desktop (shows 24 clients in total).
It shows "stream online" only when using autodj/playlists (enabled).

**Expected behavior**
Show "stream online" instead "stream offline" while broadcasting is playing via Icecast.

![test123](https://user-images.githubusercontent.com/4490792/113333884-496dc080-9323-11eb-94b3-9a9fc285615c.png)

**Comment by themadcap1976** [comment]
I'm experiencing the same issue when a streamer connects. It shows stream offline and no listeners, however the radio station is up and listeners can been seen by visiting the listener tab.

**Comment by SlvrEagle23** [comment]
@themadcap1976 We've identified one potential cause of this problem and fixed it in our Rolling Release builds. You can update to those if you need the issue fixed immediately or just wait for a new stable release version to be tagged.

**Comment by BeyondChrispy** [comment]
I'm also seeing this issue.  No listeners and 'Stream Offline' on Dashboard, but listeners show in the 'Manage' section.

**Comment by christiansacks** [comment]
+1 bump, I'm also seeing this in the rolling release docker version for 3 or so months at least.
