### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#3962]
My stream link is "https://stream.myradio.com/radio/8000/radio.mp3" and works and plays fine in browsers and SSL certificate is valid but when it is submitted to Yellow Pages, they convert the stream link to "https://stream.myradio.com:8000/radio.mp3" which I get SSL error: 

Your connection is not private
NET::ERR_CERT_AUTHORITY_INVALID 

in browsers and it is not possible to start streaming.

**Comment by YosefAdPro** [comment]
You not provided details about your configuration. or any log.
So it does not seem to me that anyone can help you.

**Comment by triangle-stream** [comment]
With newest docker installation, the certificate is issued by "localhost" and the cert error appears in browsers.

Maybe changing the server's hostname could solve the issue but this one was not present on installations before yesterday.

**Comment by triangle-stream** [comment]
Try this, it seems to work for now:

1. Enter into nginx_proxy_letsencrypt image by doing: 
`   docker-compose exec nginx_proxy_letsencrypt sh`

2. Then execute the script force_renew:
`    ./force_renew`

After this, the certificate should be ok and you can access your Azuracast instance with HTTPS.

**Comment by stardevelop** [comment]
SSL certificate works fine on https://stream.myradio.com/radio/8000/radio.mp3 but doesn't work on https://stream.myradio.com:8000/radio.mp3

**Comment by triangle-stream** [comment]
That's because the port 800 is not mapped as ssl port. 

If you want to use https on that port, you need to change Azuracast ports during install or add a proxy on top of it.

**Comment by Vaalyn** [comment]
If I remember correctly when a certificate is renewed/added IceCast would need to be reloaded to notice the new cert and I think I read some time ago that it's not yet implemented to automatically reload IceCast when a renew happens.

Have you tried manually restarting IceCast after adding/renewing the certificate?

**Comment by stardevelop** [comment]
> If I remember correctly when a certificate is renewed/added IceCast would need to be reloaded to notice the new cert and I think I read some time ago that it's not yet implemented to automatically reload IceCast when a renew happens.
> 
> Have you tried manually restarting IceCast after adding/renewing the certificate?

Normally SSL works but I get error when I user https://stream.myradio.com:8000/radio.mp3

**Comment by Vaalyn** [comment]
> > If I remember correctly when a certificate is renewed/added IceCast would need to be reloaded to notice the new cert and I think I read some time ago that it's not yet implemented to automatically reload IceCast when a renew happens.
> > Have you tried manually restarting IceCast after adding/renewing the certificate?
> 
> Normally SSL works but I get error when I browse https://stream.myradio.com:8000/radio.mp3

I do understand when exactly that error shows up to you but you haven't answered my question.
Have you manually restarted IceCast yet?

**Comment by stardevelop** [comment]
> > > If I remember correctly when a certificate is renewed/added IceCast would need to be reloaded to notice the new cert and I think I read some time ago that it's not yet implemented to automatically reload IceCast when a renew happens.
> > > Have you tried manually restarting IceCast after adding/renewing the certificate?
> > 
> > 
> > Normally SSL works but I get error when I browse https://stream.myradio.com:8000/radio.mp3
> 
> I do understand when exactly that error shows up to you but you haven't answered my question.
> Have you manually restarted IceCast yet?

Yes, I have rebooted the server several times.

**Comment by zloysystem** [comment]
> My stream link is "https://stream.myradio.com/radio/8000/radio.mp3" and works and plays fine in browsers and SSL certificate is valid but when it is submitted to Yellow Pages, they convert the stream link to "https://stream.myradio.com:8000/radio.mp3" which I get SSL error:
> 
> Your connection is not private
> NET::ERR_CERT_AUTHORITY_INVALID
> 
> in browsers and it is not possible to start streaming.

There was the same problem on ubuntu 20.04, after updating the components of the system itself, I moved to debian 10, installed the docker Rolling Release version, now the problem is gone, it works on the ssl port and nginx sends a stream regularly with ssl.
On ubuntu, I worked around this problem like this, reinstalled the server, installed the panel, configured everything, and only then apt update && apt upgrade -y of the server.
on ubuntu 20.04, as far as I remember, the libssl and libssl-dev packages were updated not so long ago, perhaps because of this the certificate does not cling to the port.

**Comment by zipho** [comment]
My problem is that, I am even missing the `nginx_proxy_letsencrypt` any pointers?

**Comment by dolphin-cat** [comment]
same issue on debian 11
