### ISSUE TITLE
No Covers on Music Request Page

### ISSUE THREAD

**Issue by Jaadoo13** [AzuraCast/AzuraCast#3974]
Hello.
As im searching in the issues and also in the settings of azuracast, i dont find a reason, why there will no covers displayed. On all Songs is only the Fallback cover. But all my Files have a Cover and also the search of Covers is also on.

So, how can i display the correct Covers? thx.

**Comment by Abqehebter** [comment]
Same problem.

**Comment by SlvrEagle23** [comment]
The cause of this bug has been identified and fixed as of the latest Rolling Release version, currently being deployed.
