### ISSUE TITLE
Revoke Letsencrypt on Docker Installation

### ISSUE THREAD

**Issue by babycommando** [AzuraCast/AzuraCast#3977]
Using Docker installation method
Yes

Host Operating System
Ubuntu 

Describe the bug

Hey guys! I need some ultra help here!

I have the docker installation running on an digitalocean droplet, ubuntu server.

I use the command ./docker.sh letsencrypt-create to create the domain register and stuff, I've done It for a year and it worked.

Now my domain expired but I have a new one, and I'm trying to register the new domain via the docker.sh letsencrypt-create command, but It seems that I must revoke the old certificate with the old domain.

How can I revoke the letsencrypt certificate, so I can create a new one with the new domain? thanks!

Also, would be nice to not having to reinstall azuracast, because I have A LOT of gbs of music in there, I don't even have it on my computer anymore (Also, how can I find those files on the docker installation?)

Master thanks guys!

**To Reproduce**

1. Go to 'var/azuracast'
2. Run './docker.sh letsencrypt-create' and configure the new domain

Then when I check the certificate of the new site, It still saying the certificate is the old certificate that only expires in June.

Expected behavior
I need to "revoke", "override" or maybe find the certificate files and delete so I can delete them and create a new one.

**Comment by ErnestPH** [comment]
Have you tried running `./docker.sh letsencrypt-create yourdomain.com`? It worked for me...

**Comment by babycommando** [comment]
I've done It for a year with the same domain and worked, now with a new domain doesn't work at all. Seems something like the old domain is still registered, and I must delete the files created by letsencrypt inside that docker to create a new one with a new domain. How could I be able do do It?
