### ISSUE TITLE
Changes to host filesystem files not reflected inside running AzuraCast instance

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#398]
I updated it today from the radio repository and as always copied my full translation into the folder, but this translation does not fit in the panel, I overloaded nginx and still without results, I used to always do this and everything worked, but now it does not work. Help please, what can I do?
Even if I delete the translation, it still sees it although in the folder there is no translation for my language at all.
The thing is that before the update I forgot to make backups and for me it's a huge problem, I've been translating for a few days and now everything is displayed in broken language.

TASK [azuracast-update : Update configuration from legacy] *********************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php azuracast:config:migrate", "delta": "0:00:15.536333", "end": "2018-02-01 11:19:33.929224", "msg": "non-zero return code", "rc": 255, "start": "2018-02-01 11:19:18.392891", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
localhost   

I found the reason, you put all the translations in a container and everything is copied from the repository.

**Comment by SlvrEagle23** [comment]
@susl16c Why are you not using our CrowdIn system to generate and submit translations? That would ensure the translations actually make it into the application's code itself.

In any case, you can configure a custom volume mount on Docker to force the system to use your translations from the host instead of using the ones pulled from the repository.

I don't know the specifics of your setup, but essentially the modifications to the docker-compose.yml file would look something like this:

```
version: '2'

services:
  web:
    volumes:
      - ./app/locale:/var/azuracast/www/app/locale

  nginx:
    volumes:
      - ./app/locale:/var/azuracast/www/app/locale
```

**Comment by susl16c** [comment]
I do not know how to use it. I crossed the path /var/lib/docker/volumes/azuracast_www_data/_data and just copied the translation there and everything was transferred, but again you did not add all the phrases for the translation after the update. Thank you for your help, maybe you will have time and you will add phrases for translation. Thank you very much.
