### ISSUE TITLE
Missing thumbnail in history

### ISSUE THREAD

**Issue by ncfernan** [AzuraCast/AzuraCast#3980]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #e0270f9 (2021-04-06 11:32) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 20.04 LTS

**Describe the bug**
Some tracks have thumbnails that come and go. When they are listed as "playing now" and "next" the thumbnails appear. When they go to history, the thumbnail is gone. I have 3 tracks behaving this way. It happens in stable and rolling versions.

**To Reproduce**
I don't know, I already tried to clear Azuracast cache, browser cache, reprocessed those files many times, to no avail. I have 2 stations in the same box and this behavior affects only one of them (2).

**Expected behavior**
All my files have cover art, so I expected to see them in history.

**Relevant Logs**

**Screenshots**
![image](https://user-images.githubusercontent.com/10008844/113713575-e3d05a00-96bd-11eb-9da6-9dec65fddbb1.png)
![image](https://user-images.githubusercontent.com/10008844/113713621-f0ed4900-96bd-11eb-95af-e9e17a7440c1.png)
![image](https://user-images.githubusercontent.com/10008844/113713639-f64a9380-96bd-11eb-919d-3aaf6c20dc35.png)

**Device(s):**

- Device: Desktop
- OS: Win10
- Browser: chrome
- Version: 89.0.4389.114 (Official Build) (64-bit)

**Additional context**

**Comment by Abqehebter** [comment]
Not the best solution, but: Try to re-upload the songs. It worked for me.

**Comment by ncfernan** [comment]
The screenshots above were taken after 3 re-uploads and reprocesses...  the system recognized the cover art, it's shown above.

I thought the picture shown on screenshots 2 and 3 (musics tab) were only thumbnails, but no, it is the real cover art. 

What happens when the history is assembled that is droping the picture is a mystery to me. The reprocess procedure should read the picture from the mp3 file again and refresh all links and records inside the system, but it seems this is not happening and only for a few files.

Is there any log related to this issue that I can check and post here?  If so, where do I find it?

**Comment by YosefAdPro** [comment]
I also experience a similar problem.
After reprocess some of the images disappear.

**Comment by Abqehebter** [comment]
@ncfernan Hm that is strange. You mean you've already completely re-uploaded the songs as well? So deleted and then re-uploaded?

**Comment by ncfernan** [comment]
Yes, I did all that. Do you wanna see something weird?  Take a look:

![image](https://user-images.githubusercontent.com/10008844/113932981-6c3c2100-97ca-11eb-918b-a802b4399bff.png)

The cover art picture is there, but somehow the task that builds the history is messing with the links.

There is another weird thing here: the album name is missing, too...

![image](https://user-images.githubusercontent.com/10008844/113933292-c806aa00-97ca-11eb-8286-e62394b6a09b.png)

**Comment by Abqehebter** [comment]
Okay, that can be due to many things at the moment. At least the filesystem V2 is currently being tested.

Do you find anything conspicuous in the AzuraCast log that can be traced back to this? Have a look in `Administration > System logs > AzuraCast-Applicationprotocol`

**Comment by SlvrEagle23** [comment]
@ncfernan We have a known issue with songs with the quote character in them that causes them to sometimes not properly be represented when we pull metadata for a given track. See issue #3847 for more information.
