### ISSUE TITLE
Embedded player does not work on iOS devices

### ISSUE THREAD

**Issue by user171** [AzuraCast/AzuraCast#3981]
**Using Docker installation method**

Yes

**AzuraCast version**

Rolling Release #15a7a20 (2021-03-28 3:11) • Docker • PHP 7.4 

**Host Operating System**

Ubuntu 20.04

**Describe the bug**

Using the embedded web player from an iOS device does not produce any sound on the device. Although it works on other operating systems, on mobile and desktop.
I have embedded the web player found in the "profile" -> "embed widgets" inside a Wordpress site. It works correctly on anything but iOS devices.

**To Reproduce**

1. embed the "Radio Player" widget inside a worpdress site.
2. open the site with the player on an iPhone -> no sound is playing

**Expected behavior**

Sound should be playing on iOS.

**Relevant Logs**

**Screenshots**

**Device(s):**

- Device:  iPhone
- OS:  iOS
- Browser:  Safari
- Version: 

**Additional context**

I assumed more people had experienced this before and the issue was probably already created. But I could not find anything. Please, if this is already reported ignore this and direct me there.

**Comment by ErnestPH** [comment]
How was it done? Via a builder? code block? What theme is it? It's actually working in WordPress at least on my end.
Can you check the console logs? It's probably an issue with WordPress... 

If you can provide the site, maybe we can check it for you.

**Comment by ncfernan** [comment]
I just tested my station on iOS 14.4.2 and it works flawlessly.

**Comment by user171** [comment]
Thanks for your support. 

It was done in Wordpress 5.7 (but I had experienced the same issue with a previous version of Wordpress as well), with the Hueman theme, using a custom html widget with the html code found in Azuracast "profile" -> "embed widgets".
The player appears correctly everywhere, even on iOS. And the sound works on every browser, except on iOS.

I should be able to access any log. Please, what do you mean by console logs? On Wordpress or Azuracast?

I don't have an iOS device myself to test, if you want to check, the site is https://kivi.re/

**Comment by ncfernan** [comment]
I tested both addresses of your station. They work on Win10 with Chrome but no sound on iOS 14.4.2 (latest)

**Comment by user171** [comment]
Thanks for your feedback @ncfernan.

So if you can't get any sound from the Public Page, I think we can rule out Wordpress being the issue here.

I have installed AzuraCast straight with Docker, following the instructions, with no fancy action on my side. It's on an Ubuntu 20.04 VPS freshly installed for that purpose.

I don't understand what could prevent iOS from playing sound on that specific install.
Any idea is welcome. What logs could have any interesting information about that?

**Comment by ErnestPH** [comment]
@user171 Is there a change you install it in Ubuntu 18?

**Comment by user171** [comment]
@ErnestPH I'm not sure to understand if you mean I should try on an Ubuntu 18 instead of the 20.04 currently installed?

**Comment by Vaalyn** [comment]
@user171 I have looked at the player / stream that you posted.

The reason why iOS users can't hear your stream is that your stream is using the OGG format which iOS is unable to play since Safari does not support playing OGG. See https://caniuse.com/?search=ogg

**Comment by user171** [comment]
@Vaalyn thank you so much! I would never have thought Safari could not play OGG.

**Comment by user171** [comment]
@Vaalyn if you are interested I have created a PR to update the docs:
https://github.com/AzuraCast/azuracast-docs/pull/2

**Comment by Vaalyn** [comment]
@user171 Thank you for the contribution to the documentation. I have just merged your PR 👍
