### ISSUE TITLE
No Sound Output using Icecast

### ISSUE THREAD

**Issue by buddhatunes** [AzuraCast/AzuraCast#3987]
**Using Docker installation method**

Yes

**AzuraCast version**

Rolling Release #aea1cde

**Host Operating System**

Ubuntu 20.04

**Describe the bug**

I installed a new Azuracast server from Linode marketplace, and set up using the same settings that I previously had success with on Linode and Digital Ocean. When I test and press play at, https://e.countrymusic.io/public/live, there is no audio output and no current listener listed. I double-checked the audio settings on my laptop and confirmed other audio plays successfully.

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context**

**Comment by Abqehebter** [comment]
Hey! Here is your streaming-link: https://e.countrymusic.io/radio/8000/radio.mp3
Can you tick the "Use webproxy for radios" option on in `Administration > System settings`?

**Comment by buddhatunes** [comment]
That worked, thank you!
