### ISSUE TITLE
AzuraCast Not starting properly/playing anything

### ISSUE THREAD

**Issue by creatort** [AzuraCast/AzuraCast#3988]
Upon starting the station, tracks queue up but the station remains in an offline state.
Nothing gets played, but everything gets queued via AutoDJ.

![image](https://user-images.githubusercontent.com/27066503/113945597-90195a00-97fe-11eb-9f0b-310c5d52b3fd.png)

After clearing Docker cache using ./docker.sh cli cache:clear, the default sound gets played through the mountpoint but AutoDJ functions do not work.

I've restarted the server, and the modules yet no sign of life.

--

Update after writing the above: AutoDJ started working but the station still appears as offline from the admin panel.
![image](https://user-images.githubusercontent.com/27066503/113945442-37e25800-97fe-11eb-85b9-1e5eda23c909.png)
![image](https://user-images.githubusercontent.com/27066503/113945461-403a9300-97fe-11eb-88a8-d6f4a5ced6cd.png)
![image](https://user-images.githubusercontent.com/27066503/113945629-a1626680-97fe-11eb-98bb-af2b8a4402ea.png)

**Is this a bug with my installation? Do I just reinstall?**
I'd love to provide steps on how to make it end out like this, but alas I have no idea.

OS: Ubuntu 20.04
RAM: 4GB
Disk: 30GB SSD
![image](https://user-images.githubusercontent.com/27066503/113945504-547e9000-97fe-11eb-99e1-26504dc418c9.png)

**Comment by Abqehebter** [comment]
Can you post your liquidsoap log of the station? Look in `Tools > Log Viewer > Liquidsoap Log`

**Comment by SlvrEagle23** [comment]
@creatort You didn't use our issue template; you should have, as it has the questions I now have to ask you anyway.

What version are you on? Also, are you using the Ansible installation or Docker?

Do you have any relevant logs you can show that indicate any error from the Utilities > Log Viewer page?

**Comment by creatort** [comment]
What version are you on?
Supposedly the latest stable version

Also, are you using the Ansible installation or Docker?
Docker

Do you have any relevant logs you can show that indicate any error from the Utilities > Log Viewer page?
Not really, here's the IceCast error log:
https://pastebin.com/3ay0Xkex

LiquidSoap Log:
https://pastebin.com/emUMfT7M

**Comment by Vaalyn** [comment]
Could you provide us with the `AzuraCast Application Log` too?

If possible please provide us with 2-3 of the media files that you are using.

Also please look at the IceCast admin page to see if IceCast itself shows the title and artist or if this is empty.

**Comment by laodikea** [comment]
I guess that this is the same problem than this: #https://github.com/AzuraCast/AzuraCast/issues/3629. At least the behaviour on my azuracast installation (stable v.0.12.4) on Ubuntu 20.04 have same behaviour than mentioned in this issue.

**Comment by laodikea** [comment]
This is also maybe the same problem than these: https://github.com/AzuraCast/AzuraCast/issues/3790 and this: https://github.com/AzuraCast/AzuraCast/issues/3771

**Comment by Vaalyn** [comment]
Closing this issue as it has been reported by others to be resolved.

If this is still happening on the latest version please create a new issue for this.
