### ISSUE TITLE
The size docker (What's happening ?)

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#400]
du -hs /var/lib/docker/volumes/azuracast_station_data/_data/media
1,3G    /var/lib/docker/volumes/azuracast_station_data/_data/media

du -hs /var/lib/docker                                      
101G    /var/lib/docker

Tell me the size of the files is only about 2GB, but the dock itself weighs about 100GB, what happens and what it can be connected with, I cleaned not the working images, the containers and partitions were about 200GB occupied

**Comment by SlvrEagle23** [comment]
If you're doing frequent updates to the Docker images, it's a good idea to occasionally prune the unused containers and volumes, by running a command like:

```
docker volume prune -f
docker rmi $(docker images | grep "none" | awk '/ / { print $3 }')
```

That should clear up quite a bit of space.

**Comment by susl16c** [comment]
I have Centos 7
 docker volume prune -f
unknown shorthand flag: 'f' in -f
See 'docker volume --help'.

Usage:  docker volume COMMAND

Manage Docker volumes

Options:
      --help   Print usage

Commands:
  create      Create a volume
  inspect     Display detailed information on one or more volumes
  ls          List volumes
  rm          Remove one or more volumes

Run 'docker volume COMMAND --help' for more information on a command.

 docker rmi $(docker images | grep "none" | awk '/ / { print $3 }')
"docker rmi" requires at least 1 argument(s).
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images


 docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-71.git3e8e77d.el7.centos.1.x86_64
 Go version:      go1.8.3
 Git commit:      3e8e77d/1.12.6
 Built:           Tue Jan 30 09:17:00 2018
 OS/Arch:         linux/amd64

 docker info
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-8:18-30146561-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.104 GB
 Data Space Total: 107.4 GB
 Data Space Available: 104.3 GB
 Metadata Space Used: 5.947 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Thin Pool Minimum Free Space: 10.74 GB

And on the server only radio works, and there are no other options how to make room? Your option did not help me. Thank you very much for helping you.

**Comment by mkody** [comment]
You should probably consider upgrading your docker installation. You'll need to remove the Docker Engine and move to Docker CE. 
Everything's documented here: https://docs.docker.com/install/linux/docker-ce/centos/#os-requirements

**Comment by SlvrEagle23** [comment]
Closing this issue, as with the latest iteration of Docker Community Edition, the commands I provided above will work fine to clear up any extra space that's used up.

**Comment by br0kenlink** [comment]
Hi, I'm trying to do backup for migration but it kept running out of space, after checking got this,
`du -hs /var/lib/docker/volumes/azuracast_station_data/
11G     /var/lib/docker/volumes/azuracast_station_data/
du -hs /var/lib/docker
28G     /var/lib/docker`
I can see that /var/lib/docker/devicemapper takes up nearly 18GB.
Im also on Centos 7 with Docker-CE, first command worked and cleared 10MB,
second command gives same arror as previous fella had, that it needs at least one argument.
Any help would be appreciated.
Not sure can I delete things from /var/lib/docker/devicemapper/

Thanks

**Comment by SlvrEagle23** [comment]
@br0kenlink You may not be getting accurate size reports from the Docker directory, as Docker takes advantage of a unique kind of overlaid filesystem that only tracks changes made from the base image.

If you run: `docker system prune`, that may help clean up some space.

If you continue to have issues, I would normally advise to create a new GitHub issue, but this is a problem with Docker and not with AzuraCast in particular, so it is probably best to search for solutions within the greater Docker community.
