### ISSUE TITLE
Error on Update - Running Database Migration

### ISSUE THREAD

**Issue by williambatson** [AzuraCast/AzuraCast#4003]
Update fails and install now unstable after running update.
Update fails or stalls out at Running Database Migration...   then nothing
https://gyazo.com/5431e43a6598b8dd88b18662617c08bc

https://gyazo.com/65f0c23b51b9ed86fc98838e41c3a658 <-- any attempt to run any of these manually crashes the server and it shuts down.

I'm afraid to do more at this point on my own as I don't want to lose the stations or data.

**Using Docker installation method**

**AzuraCast version**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**
https://gyazo.com/5431e43a6598b8dd88b18662617c08bc
https://gyazo.com/65f0c23b51b9ed86fc98838e41c3a658

**Comment by SlvrEagle23** [comment]
@williambatson How far back are you updating from, and how big is the database you're updating?

The migrations can be pretty significant if they involve updates from an installation more than, say, 6 months or so old. Unfortunately they're necessary to bring the database up to its current spec, so you may just have to wait them out to continue.

**Comment by williambatson** [comment]
I've logged in and run update once more -  
For reference - the server has 9 stations and approx 650GB of music files on it.
The VPS itself is as follows:
Ubuntu 16.04 (with all updates installed) 10 vCPU Cores, 60 GB RAM, 1.6 TB SSD, 1 Gbit/s Port

sat here for hours....
Running Database Migrations
---------------------------

Update ran for a total of 6.5 hours 'migrating databases' then Linux posted this:
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
then rebooted the system - update failed again.  Current status, some stations are playing music, some not, all web services are down -cannot log into anything via web interface -  I do have SSL access.

**Comment by SlvrEagle23** [comment]
@williambatson You could possibly try stepping through the migrations one-by-one by running:

```
docker-compose run --rm --user=azuracast web bash
```

and then inside the terminal that appears, run:

```
php bin/console migrations:migrate current+1
```

Which will bump you one migration up from where you are now. You can keep running that one-by-one, which will let the migrations slowly update without all piling up at once and possibly wrecking your installation.

**Comment by williambatson** [comment]
https://gyazo.com/4e2f55a8a74f6ad6a43b6152f137dfe6

Ouch - Not as expected, I'm sorry Buster!

WARNING! You are about to execute a migration in database "azuracast" that could result in schema changes and data loss. Are you sure you wish to continue? (yes/no) [yes]:
 > yes

[2021-04-12T02:19:24.207344+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\ConnectionException: An exception occurred in driver: SQL         STATE[HY000] [2002] Connection refused (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Abstr         actMySQLDriver.php line 112 while running console command `migrations:migrate` {"exception":"[object] (Doctrine\\DBAL\\Exception\\Con         nectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/azuracast/www/vendor/do         ctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Except         ion(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Ex         ception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/azuracast         /www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)"} []
[2021-04-12T02:19:24.557639+00:00] AzuraCast.WARNING: Console command `migrations:migrate` exited with error code 1. [] []

In AbstractMySQLDriver.php line 112:

  An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused


In Exception.php line 18:

  SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 38:

  SQLSTATE[HY000] [2002] Connection refused


migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [-         -configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]

**Comment by williambatson** [comment]
I ran the code as described 2 days ago -  it crashed the server, it's now status web services and stations all down, vps running.
Is there a way to save this thing?

**Comment by SlvrEagle23** [comment]
@williambatson You probably need to do some basic Docker diagnostic work to get it working again...definitely restart all the containers with:

```bash
docker-compose down
docker-compose up -d
```

Otherwise this would require us directly looking at the installation to further troubleshoot it.

**Comment by williambatson** [comment]
Docker down and up got it to respond some - something's going on with it as it will run for a bit, I was able to catch some log filehere:
[2021-04-13T23:56:42.452749+00:00] AzuraCast.ERROR: Too many attempts to get next song; giving up. {"station":{"id":205,"name":"LUXentertainment Resident 1"}} []
[2021-04-13T23:56:45.709628+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":205,"name":"LUXentertainment Resident 1"}}
[2021-04-13T23:56:45.712899+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":205,"name":"LUXentertainment Resident 1"}}
[2021-04-13T23:56:45.715407+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":205,"name":"LUXentertainment Resident 1"}}

Then I get this:
Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.

and Azuracast halts.   Is there a way I an get info to you privately to look at this thing?

**Comment by williambatson** [comment]
There's an obvious bug here - likely too small for attention so close it up and file it.  I've migrated my station to a more stable platform - letting it sit a week wasn't viable for me so had to move on.

**Comment by SlvrEagle23** [comment]
@williambatson Best of luck with your station. While I'm not sure what caused this particular issue, fixing it would have required inspecting your installation directly, which is something we no longer do in most cases as part of our unpaid support due to increased time demand.

**Comment by williambatson** [comment]
so i s leaving an open tviekt an dthe thing hanging for a week -
dont sya unpaid Busyer - i've dropped more than a lot on donations and now
am paying for a real service so i dont have to seal with the 'we do it for
free nonsense'    you do it for cee but you really don't do it/   you're
building a user base until you get an offer from Sonic or Centova - no
shocker there

**Comment by SlvrEagle23** [comment]
@williambatson I still think about this message a lot. I definitely read it when it was first sent, and it hit me then just as it does today.

I don't know what it was that made you give up on us after years of working with our team. I can't imagine it was just a matter of waiting a week on a GitHub issue, as it's fairly common to have to do that even with much, much larger projects than ours. If you look at the backlogs of open-source behemoths like Firefox, they have unfixed issues from ten years ago.

When I say AzuraCast is powered by volunteers, I'm not telling the folks who already donate that their donations don't matter (they of course do), I'm telling everyone else that:
 - You can use this project for free without ever contributing, and a vast majority of people do;
 - The existing total of donations we get keeps me far below the federal poverty line, and doesn't clear rent and groceries on most months, so it is _not_ equivalent to a salary and is absolutely not equivalent to the value of the time I put into the project; and
 - Unless you're specifically paying for a support package (i.e. the ones we're starting to consider implementing), donations aren't tied to your GitHub issues and don't necessarily get you special treatment. We don't even keep track of which donor on Patreon, etc. corresponds to which GitHub user, so we could never know. They're just donations, meant as a gesture of support for the work we do.

I think it's a shame, though, that you wrote off our entire project as just waiting for a buyout from a competitor.

Truth be told, I would _beg_ for a buyout at this point if it meant having enough to pay my rent, to have groceries delivered, to live my very simple and very quiet life without the now almost constant panic of having to beg friends (and users of my software) for money every few weeks or months just to clear basic expenses. That cycle has grown so incredibly exhausting for me, and has probably taken years off of my already short life expectancy.

That doesn't mean that I've given up on AzuraCast or that I'm just preparing it for some reseller. I still work on it every day; I still build my own desktop computing environment around what will let me work on it more effectively; I still wake up and read through GitHub issues and go to sleep only after I feel like I've got enough done to justify resting that day.

Working with you was always pleasant, until suddenly one day you left with such an angry message that I still think about it months later. I wonder if you're proud of that and how it represented your time with us, the work we do, and what it means to be a part of the open-source community.
