### ISSUE TITLE
Edit Media Error

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#4006]
**Using Docker installation method**
Yes 

**AzuraCast version**
Rolling Release #f792019

**Host Operating System**
Ubuntu

**Describe the bug**
Small problem in the editing on a 1h00 mix

![Capture d’écran 2021-04-11 à 19 55 51](https://user-images.githubusercontent.com/379099/114315705-6a42cc80-9b00-11eb-9ea3-01b4a9d88d7a.png)

**Comment by SlvrEagle23** [comment]
@ckeurk Did you rename the file at the same time as making other changes? It seems possible that the filename itself is what's causing problems as it has special characters (that we would normally be escaping when uploading via the web).

**Comment by ckeurk** [comment]
No name change and on other 1h00 media the same problem comes up

**Comment by SC2Mitch** [comment]
I'm struggling to re-produce this issue on the latest rolling release, are you still having this issue @ckeurk ?

**Comment by ckeurk** [comment]
the problem comes directly if I SFTP the folder with the mp3s into the media folder
