### ISSUE TITLE
 Recorded instreams not listed

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#4007]
v0.12.2 Stable • Docker • PHP 7.4
![IMG_20210412_133744_474](https://user-images.githubusercontent.com/16152034/114388681-50eb6000-9b94-11eb-9575-b6a6ba8f4ecb.jpg)

We are suffering an issue that our stream connections to Azura are not being listed. The systems always shows “loading” and no matter how much we wait, it never load. Is there a possibility to access directly throught sftp to a direct folder? Where is the original folder of recording hosted? That will help us.

**Comment by SC2Mitch** [comment]
Hello, for the future, please follow our github bug report format, I've investigated this issue and found the error show up on the debug logs. 
`{"code":500,"message":"TypeError at /var/azuracast/www/vendor/league/flysystem/src/Filesystem.php L34: Argument 1 passed to League\\Flysystem\\Filesystem::fileExists() must be of the type string, null given, called in /var/azuracast/www/src/Controller/Api/Stations/Streamers/BroadcastsController.php on line 66","formatted_message":"<b>TypeError at /var/azuracast/www/vendor/league/flysystem/src/Filesystem.php L34:</b> Argument 1 passed to League\\Flysystem\\Filesystem::fileExists() must be of the type string, null given, called in /var/azuracast/www/src/Controller/Api/Stations/Streamers/BroadcastsController.php on line 66","extra_data":[],"success":false}`

**Comment by SlvrEagle23** [comment]
@fidegr This should now be fixed as of the latest Rolling Release version. If so, feel free to close this issue. Thank you for your report.

**Comment by Vaalyn** [comment]
Closing as resolved
