### ISSUE TITLE
The played track history widget has become a player

### ISSUE THREAD

**Issue by zloysystem** [AzuraCast/AzuraCast#4008]
Hello
Panel: Rolling Release # 6fcd9ad
installation: docker
OS: Debian 10
Now, instead of the history of played tracks, the player is displayed on the public page)
"https:` // streamingcast / public / listen / history? theme = `light`"
Widget Type Played Previously and Radio player is absolutely the same output - player.
Also, when you try to download a playlist from a public page, the player opens

**Comment by SubwooferNL** [comment]
i have the same
![image](https://user-images.githubusercontent.com/58433471/114540832-4abdb800-9c56-11eb-99ef-2986ef2c1922.png)
![image](https://user-images.githubusercontent.com/58433471/114540859-527d5c80-9c56-11eb-81d8-be489881f277.png)
![image](https://i.imgur.com/is6Vb7j.png)

**Comment by SlvrEagle23** [comment]
Thanks everyone for the reports; this was caused by a slightly over-eager regular expression in our routing configuration, and a fix is being published right now to the Rolling Release channel.
