### ISSUE TITLE
Disabling reports

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#401]
Thank you very much for your work. Tell me you can make settings to turn off unnecessary reports?

**Comment by SlvrEagle23** [comment]
@susl16c What reports are you describing? The reports on the station sidebar?

There's currently no way to disable the ones you don't want.

**Comment by susl16c** [comment]
Yes, right on the sidebar. I see. Thanks

**Comment by SlvrEagle23** [comment]
Closing this issue, as while a report may not be of particular use to a certain station, I see no reason why an administrator should be able to hide one report from the station operator and deny them some measure of the analytical power behind the AzuraCast system.

If you want to remove the ability for a user to see _all_ station reports, there is a "view station reports" permission that can be removed from a role.
