### ISSUE TITLE
Once per x does not work properly (anymore)

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#4013]
**Using Docker installation method**
Yes.

**AzuraCast version**
Rolling Release #f22fbc8 (2021-04-12 6:41)

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
The "Once per x ..." option has been disabled since commit https://github.com/AzuraCast/AzuraCast/commit/e7cf4e585eda56e88ff33b1092abfa99ef963576 has become so unreliable that the AutoDJ doesn't want to play my advertising trigger at all. Before I already had big problems with it, that it sometimes sat out a complete hour, but one hour on the other hand to currently 3 hours (or even more) is not there at all.

**Expected behavior**
At the top of the screenshot you can see the light red line, this is supposed to represent my advertising trigger, which is supposed to run every 15 minutes. But it does not (as you can see here).

The list in the screenshot starts at 10:05 o'clock and ends at 13:38 (+) o'clock.

**Screenshots**
![image](https://user-images.githubusercontent.com/42640247/114704678-2aa9f980-9d27-11eb-9298-508c82d7eb7c.png)

**Comment by SlvrEagle23** [comment]
@Abqehebter In my own tests, I have encountered no issues with any of the "Once per X Minutes" or "Once per X Songs" playlists. 

The image you attached isn't really legible and doesn't really constitute sufficient information for us to investigate this issue further; what we would need are logs from the AutoDJ "next song" calculations, which are now attached to every piece of media listed in `Utilities` > `Upcoming Song Queue`.

In general, "The AutoDJ isn't working right" issues constitute a ton of bug reports we get, and yet also tend to be the most difficult for us to reproduce and resolve.

**Comment by Abqehebter** [comment]
@SlvrEagle23 Thank you for your feedback. For me it occurred only after a long time. I can attach a decent picture here again:
![image](https://user-images.githubusercontent.com/42640247/114790490-2280a700-9d85-11eb-826b-8ee3f067096c.png)
After 2 hours, it was only then that we continued:
![image](https://user-images.githubusercontent.com/42640247/114790926-df730380-9d85-11eb-8a20-5c976fd94b69.png)

All my Upcoming song logs are empty:
![image](https://user-images.githubusercontent.com/42640247/114790698-7e4b3000-9d85-11eb-8c9c-f1002baf7aaf.png)

> In general, "The AutoDJ isn't working right" issues constitute a ton of bug reports we get, and yet also tend to be the most difficult for us to reproduce and resolve.

I can understand, I try to explain it as simple as possible, but you can see that English is not my native language :-)

**Comment by silvaalex2021** [comment]
sorry for my interference, but I was also never able to view any logs on the autoDJ nextsong queue for any of the tracks listed there. All logs are always empty!

**Comment by Abqehebter** [comment]
@SlvrEagle23 Okay I was able to track that it runs normally on my test instance, so every 15 minutes there is a song running called START_AD_BREAK - Now to the question, what is the production issue?

Can it possibly be because the START_AD_BREAK is 00:00 minutes long? And the START_AD_BREAK on my test instance is a normal song, so it goes 03:19 minutes long? I noticed that well in the history. It shows the 00:00 minutes START_AD_BREAK often just not in the history.

Or do I have too many stations running on AzuraCast that want to "eat" a bit much there and all focus on that?

**Comment by Abqehebter** [comment]
@SlvrEagle23 Okay I could also see on my test instance that it plays through the START_AD_BREAK normally every 15 minutes. But what is the problem with the production server?

Is it because the START_AD_BREAK on my test instance is a song which is 03:19 minutes long, and the START_AD_BREAK on my production server goes 0 seconds (about one second)? Because the 0 seconds START_AD_BREAK title, also mostly doesn't show up in the history, so it's also hard to track the commercials via AzuraCast.

Or is it because there are too many stations running on the production server, which should also run the 0 seconds START_AD_BREAK every 15 minutes? That it may be too much for him?

**Comment by Abqehebter** [comment]
Small update on this: It looks like (so far) that it was actually due to the 0 seconds ad break. Since I increased it to one second, it seems to work (so far).

How @silvaalex2021 already mentioned with me, the logs in the Upcoming Song Queue are still empty unfortunately, and songs or ad-breaks that are below 2-3 seconds don't show up in the song history either (Sometimes quite handy, but for debug unfortunately not).
