### ISSUE TITLE
My Ansible installation does not update

### ISSUE THREAD

**Issue by PB-SF** [AzuraCast/AzuraCast#4023]
**Using Docker installation method**
No - Ansible

**AzuraCast version**
Rolling Release #92910d7 (2021-02-09 6:34) • Ansible • PHP 7.4 

**Host Operating System**
Ubuntu 18.04.

I'm on the rolling release channel. My current version is `Rolling Release #92910d7 (2021-02-09 6:34) • Ansible • PHP 7.4`

As always, I tried to install the latest updates.

`sudo ./update.sh`

The update process runs as usual, but no new features are installed or updated.

I've tried the normal update command twice and the `--full` parameter once.

My installation still remains on #92910d7.

At the beginning of the update process I get the following message:

`Your configuration specifies to merge with the ref 'refs/heads/master' from the remote, but no such ref was fetched.`

![grafik](https://user-images.githubusercontent.com/45131983/114893651-345a5c80-9e0e-11eb-8b23-a94e91a33eaf.png)

Maybe it has something to do with it?

Many thanks for your help

**Comment by Vaalyn** [comment]
This is due to the renaming of the Git branch `master` to `main`.

Follow the instructions in the pinned issue: https://github.com/AzuraCast/AzuraCast/issues/3800
