### ISSUE TITLE
Event on updated - Vue Object RadioPlayer

### ISSUE THREAD

**Issue by youngdesenv** [AzuraCast/AzuraCast#4025]
**Using Docker installation method**
 Yes

**AzuraCast version**
0.12.2

**Host Operating System**
Ubuntu Server 20

Which event of the 'PublicRadioPlayer' object can I customize to fetch data from NowPlaying and detect each metadata change?
In previous versions I accessed the "on event hub" of the 'radio_player' object.

**Comment by SlvrEagle23** [comment]
@youngdesenv Definitely a valid question, as our recent updates have prevented there from being a global variable that you can latch onto in your own custom code to detect nowplaying updates.

I've updated the latest Rolling Release version of AzuraCast to once again assign a global variable to the Vue components, so connecting to that and listening for updates should be as simple as calling:

```js
Vue_PublicFullPlayer.$eventHub.$on('np_updated', function(np_new) {
  // custom code with np_new
});
```

**Comment by youngdesenv** [comment]
Thanks. I will wait for this correction to enter the stable version.
