### ISSUE TITLE
Error Profile

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#403]
Hello,
Small problem with the page Profile
![capture d ecran 2018-02-03 a 07 25 04](https://user-images.githubusercontent.com/379099/35763780-f0b0bb34-08b3-11e8-825f-0fa5a064e327.png)

**Comment by SlvrEagle23** [comment]
@ckeurk That screenshot doesn't actually tell me anything...it appears to be attached to a Whoops error report, but I'd like the rest of said report too.

**Comment by ckeurk** [comment]
![azu](https://user-images.githubusercontent.com/379099/35766810-20d5220c-08df-11e8-8cbf-b0d4ff40423d.jpg)

**Comment by SlvrEagle23** [comment]
@ckeurk I'm not seeing that issue at all on any of my instances. Are you sure you have the latest copy of the code? You may need to do a manual `git reset --hard && git pull` if all else fails.

**Comment by ckeurk** [comment]
Okay, I've done a complete update(./update.sh --full), the problem is solved.
