### ISSUE TITLE
Media files table keeps currentPage when searching leading to a server error due to invalid page number

### ISSUE THREAD

**Issue by akrapovicalex** [AzuraCast/AzuraCast#4034]
**Using Docker installation method**
Yes 

**AzuraCast version**
 v0.12.3 Stable

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
The error when searching for more than 50 files if select page 
If there are more than 1000-2000 files, the same error does not display files in folder and  search dont work

**To Reproduce**
Click Music files folder. Search .

**Relevant Logs**
 GET http://stationIP/api/station/1/files/list?internal=true&rowCount=10&current=3&searchPhrase=ade&currentDirectory=music 500 (Internal Server Error)
StationsMedia-9f7023c5f7.js:1 Uncaught (in promise) TypeError: Cannot read property 'message' of undefined at StationsMedia-9f7023c5f7.js:1

**Screenshots**
![SKh4aqQWRw](https://user-images.githubusercontent.com/52565001/115116190-aa8aca80-9f98-11eb-954a-edda6efe9510.gif)

**Device(s):**

- Device: Desktop PC
- OS: Windows 10 
- Browser: Chrome
- Version: Latest  90.0 64 bit

**Additional context**

**Comment by silvaalex2021** [comment]
maybe the same issue as here: https://github.com/AzuraCast/AzuraCast/issues/4009

**Comment by Vaalyn** [comment]
Could definitely be related to the issue @silvaalex2021 linked.

We already have a fix on the way.

**Comment by Vaalyn** [comment]
@akrapovicalex could you check if this issue is fixed for you with the newest rolling-release version?

**Comment by akrapovicalex** [comment]
@Vaalyn . I updated to Rolling Release #1ca6f62 . Display files in folder files is ok (1100+ files). No error.
But same error in search if i select page is still here. I attach screenshot if i go to error link 

![error](https://user-images.githubusercontent.com/52565001/115160514-d9886580-a098-11eb-9bee-e0e4090ee495.png)

**Comment by Vaalyn** [comment]
Ahh your are now seeing an issue with our paginated tables where it does not reset the `currentPage` parameter when you enter a search. I just realised that I know about this problem but haven't found an existing GitHub issue for that...

I think we can use this issue here to track this problem then.

For now you can circumvent this error from showing by first going to page 1 in the pagination and then searching.
