### ISSUE TITLE
SQL Error - Tablespace is missing

### ISSUE THREAD

**Issue by paulbonass** [AzuraCast/AzuraCast#4037]
**Using Docker installation method**
YES

**AzuraCast version**
Rolling Release #34b075b (2021-02-28 23:28)

**Host Operating System**
DigitalOcean Docker

**Describe the bug**
Something similar has happened my last few docker images despite doing completely clean installs.. Seems the DB grows mammoth or something. I can't make any changes to any config, anywhere, without a error along the lines of  "Tablespace is missing for a table" from storage engine InnoDB" when using LOCK TABLES.

 Language changes every so often but always DB related.

All stations playing but no changes can be made anywhere and from previous experience any reboot of the droplet/vm will lock me out completely.

**To Reproduce**
Make any config changes anywhere

**Screenshots**
![ConfigChange](https://user-images.githubusercontent.com/47790075/115151245-f6567600-a063-11eb-9522-09d0d578f804.jpg)
![Backup](https://user-images.githubusercontent.com/47790075/115151246-f6ef0c80-a063-11eb-84ab-929e99ad8616.JPG)

Thank you for your help! Longtime supporter of the project :)

**Comment by SlvrEagle23** [comment]
This error was caused by general data corruption on the server where the AzuraCast installation is based, and was fixed through direct intervention.
