### ISSUE TITLE
Missing song_album for search_fields

### ISSUE THREAD

**Issue by unbreakhyek** [AzuraCast/AzuraCast#404]
![default](https://user-images.githubusercontent.com/8805965/35771592-bac7cad4-0972-11e8-9e7e-8562a0f715b6.PNG)

First, thank you for accepting my previous request.

Album information is displayed well, but album search is not possible.

could you modify the code to search the album?

I always appreciate it.

thanks.

**Comment by SlvrEagle23** [comment]
@unbreakhyek Kinda funny that ticket #404 is something missing. Heh.

Added!

**Comment by unbreakhyek** [comment]
Update proceeded but problem not resolved. could you check it for me?

**Comment by SlvrEagle23** [comment]
@unbreakhyek Sorry, a little tired on my end and my IDE threw in some extra braces there.

For a change of this nature, where you already know where the code is that needs to be updated, in the future you can always just submit a pull request to update it and I'll make sure it gets merged.
