### ISSUE TITLE
Album art files are being erased after some time

### ISSUE THREAD

**Issue by ncfernan** [AzuraCast/AzuraCast#4040]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #4e6f1d7 (2021-04-17 18:42) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 20.04 LTS

**Describe the bug**
I have a local storage (host) with several media directories. My 3 stations use a combination of those directories in their playlists, but all album art files are stored inside a single hidden ".albumart" directory. After processing all files, all album art files are stored in the same place no matter what station started the reprocess task.

After some time, all album art files are being erased. It seems that some task is performing a cleanup of unused files without considering that other stations may be using those files.

**To Reproduce**
Basically create 2 stations that share the same local storage (host), each with one or more directories attached to a playlist.

**Expected behavior**
The album art files should remain untouched by other stations. Maybe a simple solution could be using separate album art directories, one for each station. Maybe store the album art inside the container, and not in the shared media root dir.

**Relevant Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/10008844/115157898-04a39280-a062-11eb-94c1-140d770c0bfe.png)

![image](https://user-images.githubusercontent.com/10008844/115157957-39afe500-a062-11eb-8d22-267de305d84f.png)

**Device(s):**

- Device: Desktop
- OS: Win10
- Browser: Chrome
- Version: 89.0.4389.128 (Official Build) (64-bit)

**Additional context**

**Comment by YosefAdPro** [comment]
I also experience the problem.
And I reported it on Discord a month ago.

**Comment by Vaalyn** [comment]
We need a bit more information in order to debug this issue.

I have created 2 stations sharing the same storage location were I have media with album art on a directory called `test` which I have assigned to a playlist in one of the stations.

After running all sync tasks multiple times the images in the .albumart directory are not being removed.
To check if this is something related to the timestamp on those images I set them to be 20 years old and re-checked again after running all tasks and they are still not being removed.

I also tested this with the directory assigned to playlists in both stations, still the same.

**Comment by ncfernan** [comment]
@Vaalyn please find below the sequence I used:

![image](https://user-images.githubusercontent.com/10008844/115264052-5acd1000-a10c-11eb-8270-586a24ad41cf.png)

![image](https://user-images.githubusercontent.com/10008844/115264191-76381b00-a10c-11eb-9e88-7bfd2cf3c898.png)

![image](https://user-images.githubusercontent.com/10008844/115264279-894aeb00-a10c-11eb-87b8-d73df777b776.png)

![image](https://user-images.githubusercontent.com/10008844/115264389-a41d5f80-a10c-11eb-8643-6b3077a21961.png)

![image](https://user-images.githubusercontent.com/10008844/115264426-ad0e3100-a10c-11eb-9c47-63ac7b212340.png)

![image](https://user-images.githubusercontent.com/10008844/115264505-bb5c4d00-a10c-11eb-87f1-7985b8e020b6.png)

![image](https://user-images.githubusercontent.com/10008844/115264569-cc0cc300-a10c-11eb-81e8-781eb38b4e79.png)

![image](https://user-images.githubusercontent.com/10008844/115264642-dd55cf80-a10c-11eb-92ee-385eb04f8ee1.png)

Log:

Loading...[2021-04-19T15:37:25.568621+00:00] AzuraCast.NOTICE: Running sync task: 1-Hour Sync {"force":true} []
[2021-04-19T15:37:25.569453+00:00] AzuraCast.DEBUG: Successfully acquired the "{resource}" lock. {"resource":{"Symfony\\Component\\Lock\\Key":"lock_sync_long"}} []
[2021-04-19T15:37:25.569657+00:00] AzuraCast.DEBUG: Expiration defined for "{resource}" lock for "{ttl}" seconds. {"resource":{"Symfony\\Component\\Lock\\Key":"lock_sync_long"},"ttl":1800.0} []
[2021-04-19T15:37:25.594144+00:00] AzuraCast.DEBUG: Starting sub-task: RunAnalyticsTask [] []
[2021-04-19T15:37:27.032502+00:00] AzuraCast.DEBUG: Timer "RunAnalyticsTask" completed in 1.438 second(s). [] []
[2021-04-19T15:37:27.041781+00:00] AzuraCast.DEBUG: Starting sub-task: RunAutomatedAssignmentTask [] []
[2021-04-19T15:37:27.047861+00:00] AzuraCast.INFO: Automated assignment [NCF Radio]: Skipped. [] []
[2021-04-19T15:37:27.056768+00:00] AzuraCast.INFO: Automated assignment [Orquestradas]: Skipped. [] []
[2021-04-19T15:37:27.064360+00:00] AzuraCast.INFO: Automated assignment [Brasileiras]: Skipped. [] []
[2021-04-19T15:37:27.075396+00:00] AzuraCast.DEBUG: Timer "RunAutomatedAssignmentTask" completed in 0.034 second(s). [] []
[2021-04-19T15:37:27.085103+00:00] AzuraCast.DEBUG: Starting sub-task: CleanupLoginTokensTask [] []
[2021-04-19T15:37:27.085900+00:00] AzuraCast.DEBUG: Timer "CleanupLoginTokensTask" completed in 0.001 second(s). [] []
[2021-04-19T15:37:27.093709+00:00] AzuraCast.DEBUG: Starting sub-task: CleanupHistoryTask [] []
[2021-04-19T15:37:27.096729+00:00] AzuraCast.DEBUG: Timer "CleanupHistoryTask" completed in 0.003 second(s). [] []
[2021-04-19T15:37:27.105567+00:00] AzuraCast.DEBUG: Starting sub-task: CleanupStorageTask [] []
[2021-04-19T15:37:27.156639+00:00] AzuraCast.INFO: Storage directory cleanup completed. {"albumart":3,"waveform":0} []
[2021-04-19T15:37:27.184590+00:00] AzuraCast.INFO: Storage directory cleanup completed. {"albumart":0,"waveform":0} []
[2021-04-19T15:37:27.209140+00:00] AzuraCast.INFO: Storage directory cleanup completed. {"albumart":0,"waveform":0} []
[2021-04-19T15:37:27.221442+00:00] AzuraCast.DEBUG: Timer "CleanupStorageTask" completed in 0.116 second(s). [] []
[2021-04-19T15:37:27.226458+00:00] AzuraCast.DEBUG: Starting sub-task: RotateLogsTask [] []
[2021-04-19T15:37:27.228061+00:00] AzuraCast.INFO: Processing logs for station. {"id":1,"name":"NCF Radio"} []
[2021-04-19T15:37:27.235208+00:00] AzuraCast.INFO: Processing logs for station. {"id":2,"name":"Orquestradas"} []
[2021-04-19T15:37:27.241206+00:00] AzuraCast.INFO: Processing logs for station. {"id":3,"name":"Brasileiras"} []
[2021-04-19T15:37:27.255106+00:00] AzuraCast.DEBUG: Timer "RotateLogsTask" completed in 0.029 second(s). [] []
[2021-04-19T15:37:27.266930+00:00] AzuraCast.DEBUG: Starting sub-task: UpdateGeoLiteTask [] []
[2021-04-19T15:37:27.267027+00:00] AzuraCast.INFO: Not checking for GeoLite updates; no license key provided. [] []
[2021-04-19T15:37:27.273297+00:00] AzuraCast.DEBUG: Timer "UpdateGeoLiteTask" completed in 0.006 second(s). [] []
[2021-04-19T15:37:27.282226+00:00] AzuraCast.INFO: Lock acquired, now computing item "{key}" {"key":"settings"} []
[2021-04-19T15:37:27.294226+00:00] AzuraCast.DEBUG: Sync task "1-Hour Sync" completed successfully. [] []

**Comment by ncfernan** [comment]
There is another hidden directory that is being shared by all 3 stations: ".waveform". I guess that its contents is being deleted as well...

By the way, what is this ".waveform" directory used for?

**Comment by SlvrEagle23** [comment]
@ncfernan Do you have 3 separate storage locations for those stations that are all pointing to the same actual directory?

That may be the problem. Each "Storage Location" should correspond to...well, a storage location. If multiple stations use the same directory, they should also be using the same Storage Location.

It's entirely possible in this case that what's happening is the multiple storage locations are just overriding each other and fighting for control of the same directory.

**Comment by ncfernan** [comment]
@SlvrEagle23 Yes, I have a single "vault" with all my music files. My 3 stations have playlists with a mix of the music files stored at the same base location. I don't see anything strange in this kind of situation, it seems natural to have all music files at the same place for any station to play at will.

You are right about the race condition. Each station is deleting any file that does not belong to any playlist at the time the 1-hour cleanup process occurs, that's why I described the problem as related to the playlist.

I looked at the php code and it seems that the ".albumart" directory name is hardwired in a file that deals with media only, not related to any station in particular. This prevents the workaround of naming the directory as ".albumart99", where the 99 is the station number.

My suggestion is to move the ".albumart" reference to another place **_inside_** the container, as a sibling to "config", "media", "playlists", "recordings" and "temp". If the album art directory is inside the container, each station will have its own album art collection and waveform files. No race conditions.

I don't know if changing the hardwired directory name ".albumart" to something like "../music_temp/.albumart" will render the desired effect of reaching a location inside the container instead of using the host place, but it seems reasonable to me. Perhaps the workaround may be that simple...

**Comment by SlvrEagle23** [comment]
@ncfernan There's nothing wrong with having 3 stations that use the same storage location. What I'm saying is are the 3 stations using 3 separate "Media Storage Locations" (as visible in `Administration` > `Storage Locations`) that point to the same folder, or are they using one single Storage Location that they all share?

The latter arrangement is what we're actually wanting in this situation, and it should eliminate any sort of issues.

The reason we keep album art, waveforms, etc. in the same folder as the media directory is so these files can also be stored once for a Storage Location and then used for every station that needs them, instead of us having to process the same media multiple times for multiple stations, which is exactly what our previous arrangement was, and this was a very bad experience for any installation sharing media between stations.

**Comment by ncfernan** [comment]
@SlvrEagle23 I guess that I found the starting point of all that mess:

![image](https://user-images.githubusercontent.com/10008844/115549099-a30c3f80-a27e-11eb-8271-940063a746b4.png)

As I showed in a previous message, I just duplicated the line that creates the new `media` to let all 3 stations share the same common location.

![image](https://user-images.githubusercontent.com/10008844/115549539-22017800-a27f-11eb-9246-e26c97cefe44.png)

Obviously it worked, I could see all my music directories and files in all 3 stations. For about one hour everything ran smoothly. Then suddenly all album art files were deleted.

The `Administration > Storage Locations` was:

![image](https://user-images.githubusercontent.com/10008844/115549879-91776780-a27f-11eb-9577-30390b45957b.png)

So, answering your question, each station "thought" it was seeing a different storage location, but in fact the mapping made them point to the same physical directory.

Regarding your suggestion, I'm not sure if I point all 3 stations to the same `/var/azuracast/stations/ncf_radio/media` will prevent the `.albumart` directory from being emptied if the `1-Hour Cleanup task` does not know the difference between 3 apparently separate directories that happen to be mapped to the same physical location and 3 stations pointing to the same Storage Location (that is mapped to physical location). I'll test it later today.

Yesterday, before I received your message, I tested my idea of putting the `.albumart` directory inside the container and let only the music directory and files outside on the physical location. I mapped the music root directory to one level above the `media` directory this way:

![image](https://user-images.githubusercontent.com/10008844/115551983-267b6000-a282-11eb-987a-f79b9f8851a6.png)

The `.albumart` directory was created inside the container, and not on the media folder like before:

![image](https://user-images.githubusercontent.com/10008844/115552190-680c0b00-a282-11eb-914f-965ab140fb4b.png)

Now everything is running smoothly, but as you mentioned, each station has to decode the metadata from the music files and create its own collection of album art images. Considering that this effort is done just once, I'm satisfied with the results.

I will test your suggestion to see if it leads to a single .albumart directory and no racing condition.

**Comment by ncfernan** [comment]
@SlvrEagle23 I just tested your suggestion (or at least what I thought your suggestion was): I defined one Storage Location and pointed all 3 stations to it.

![image](https://user-images.githubusercontent.com/10008844/115565846-1c605e00-a290-11eb-934f-c88e3fe5b764.png)

I mapped the host Storage Location to replace the `media` directory the way your Help section states:

![image](https://user-images.githubusercontent.com/10008844/115566082-5467a100-a290-11eb-914e-46f8f215694f.png)

Then I restarted the stations and the `5-Minute Sync` task began to populate the `.albumart` directory. 

Important: the `.albumart` directory was created as a sibling of my music files diretory:

![image](https://user-images.githubusercontent.com/10008844/115566730-e4a5e600-a290-11eb-90a3-02721532781a.png)

As you can see, just one Storage Location with one `.albumart` directory and one music files directory.

Then I manually started the `1-Hour Sync` cleanup task:

![image](https://user-images.githubusercontent.com/10008844/115567287-7d3c6600-a291-11eb-96e2-f29f7ea9e13f.png)

AzuraCast.INFO: Storage directory cleanup completed. {"albumart":125,"waveform":0} []
AzuraCast.INFO: Storage directory cleanup completed. {"albumart":0,"waveform":0} []
AzuraCast.INFO: Storage directory cleanup completed. {"albumart":0,"waveform":0} []

You can see that the same result came out from 3 Storage Locations (one for each station) being mapped to the same host location (3 mappings) and one Storage Location shared by 3 stations (1 mapping).

This is not what you said it would occur, so probably I did not understand exactly how to implement your suggestion. Could you please give more detailed directions on how I can do what you mean?

I can stop all stations at any time for extended periods of time, so I'm ready to test whatever you say.

**Comment by Vaalyn** [comment]
@ncfernan I think you two are talking past each other.

You should only configure 1 `Storage Location` in AzuraCast, not 3 that point to the same path (regardless of if they are mapped as different paths into the container.

A single Storage Location, pointing to a single mounted directory. Then assign each station this single Storage Location.

**Comment by YosefAdPro** [comment]
I have one location for two stations, and I have the same problem.

![image](https://user-images.githubusercontent.com/11810187/115577718-53a13000-a2cd-11eb-928b-fb013274656d.png)

**Comment by ncfernan** [comment]
@Vaalyn That is what I just did and reported in my last message. Maybe you are one message behind.

**Comment by ncfernan** [comment]
@Vaalyn I could not find where to assign more than one station to the same Storage Location. The edit option does not have any field to enter the station names.  Could you please give me directions on how to do it?

**Comment by Vaalyn** [comment]
You have to edit the Stations directly, go to the Administration tab while editing the station and there you set the `Media Storage Location` to the single `Storage Location`. Do that for each Station.

![image](https://user-images.githubusercontent.com/13745863/115593470-d4175f00-a2d4-11eb-9306-9e84cda18bcf.png)

**Comment by ncfernan** [comment]
@Vaalyn  That's exactly what is in all stations of mine:

Station 1:

![image](https://user-images.githubusercontent.com/10008844/115594566-432c8d80-a2ac-11eb-837d-d7fbb00f3746.png)


Station 2:

![image](https://user-images.githubusercontent.com/10008844/115594617-53446d00-a2ac-11eb-987e-7c8347cd651c.png)


Station 3:

![image](https://user-images.githubusercontent.com/10008844/115594655-5dff0200-a2ac-11eb-8a75-10c370bab6f2.png)


The Storage Locations are:

![image](https://user-images.githubusercontent.com/10008844/115594874-a4546100-a2ac-11eb-998a-3b710cfab54a.png)


The problem now is that I cannot delete the last 2 Storage Locations. The big warning popup sign appears and when I confirm the action, nothing happens. 

I stopped the AutoDJ, but I guess this not sufficient.

I also put everything down with `docker-compose down` but - of course - the web task was gone.

Then I restarted with `docker-compose up -d` expecting that the delete action could be queued somewhere. All 3 storage locations came up, so the delete action was not queued.

Tried again to delete using the big red button. Nothing happens.

![image](https://user-images.githubusercontent.com/10008844/115596054-0bbee080-a2ae-11eb-9a70-170863cb0e14.png)




What else must I do to delete those Storage Locations and see if all stations go to the same basket?

**Comment by Vaalyn** [comment]
They are not using the same `Storage Location` entity.

When you click on the dropdown for the `Media Storage Location` in the `Edit Station` you will see 3 entries with the same path there. You need to set your stations to use the same entry from that list. Then you can delete the other 2 `Storage Locations`.

Do not just look for at the `/var/azuracast/stations/ncf_radio/media` path to determine which `Storage Location` they are using. They are all configured to use a different `Storage Location` which is why you can't delete them yet.

**Comment by ncfernan** [comment]
@Vaalyn Thank you. It worked. The combobox showed the same text 3 times (same path). I had to select the first one to let the station release the location it was using.

Now I can proceed with the test.

**Comment by ncfernan** [comment]
It's working flawlessly. The missing `.albumart` files was not an error, but misuse, bad configuration. Maybe if you guys could add some lines and one or two screenshots to the Help page this kind of misuse could be avoided.

Thank you all for your support!

**Comment by Vaalyn** [comment]
Great to hear that it's now working as intended.

I've created an issue for us that we need to prevent situations like this from happening and to give users more information regarding this type of setup.
