### ISSUE TITLE
On-demand widget width does not work correctly

### ISSUE THREAD

**Issue by Ferz0id** [AzuraCast/AzuraCast#4042]
**Using Docker installation method**
Yes
**AzuraCast version**
 v0.12.3 Stable 
**Host Operating System**
Ubuntu 

**Describe the bug**
On-demand widget width does not match 

**To Reproduce**
All widgets have the parameter "style="width: 100%", but only on-demand widget has an empty space and doesn't match with embede place
![Снимок](https://user-images.githubusercontent.com/44975254/115229971-5c063900-a11c-11eb-9eb7-c0ff11f2c1fe.JPG)
![Снимок](https://user-images.githubusercontent.com/44975254/115230010-6d4f4580-a11c-11eb-9009-50c3dc473997.JPG)
![Снимок](https://user-images.githubusercontent.com/44975254/115230193-b0111d80-a11c-11eb-866f-3fbe525ec100.JPG)
![Снимок](https://cdn.discordapp.com/attachments/647149735991443467/833642073608552448/dc8d75c6b38b6bfa.JPG)

**Comment by Vaalyn** [comment]
Closing as resolved by [this PR](https://github.com/AzuraCast/AzuraCast/pull/4322) some time ago.
