### ISSUE TITLE
MountsController grabbing from station->getId() results into 500.

### ISSUE THREAD

**Issue by xewl** [AzuraCast/AzuraCast#405]
- **Installation Method:**
Traditional on Ubuntu 16.04

**Describe the issue in full detail, including screenshots if possible:**
Saving Station data uses method "getId()" from the Station model.
Sadly it returns `null` on `->station`

Occurred on saving a Mount's options:
[post(/put?)] station/1/mounts/edit/1

Result:
500: Call to a member function getId() on null (MountsController.php : 125)

The updates stick, though.

**Comment by SlvrEagle23** [comment]
@xewl This should be fixed as of the latest code update.

**Comment by xewl** [comment]
Thought I'd keep you updated;
ran `./update.sh`
Still there:
station/3/mounts/edit/3 @ line 134

**Comment by SlvrEagle23** [comment]
@xewl Sorry about that! Should be fixed again. Please verify and let me know.

**Comment by xewl** [comment]
Ok, it removed my symlinks to the nginx certificates and the server name ending up in nginx bugging out. Which is outside of your support scope, and nothing I'm gonna bother you with. I need to set that up properly.

The change should be what it needed - & I hereby verify that the error is gone :)

Thanks for the update!

**Comment by surihost** [comment]
I have the same problem on centos7 docker installation:

500
Call to a member function getId() on null
MountsController.php : 134
