### ISSUE TITLE
server side recording isn't working.

### ISSUE THREAD

**Issue by stickbear2015** [AzuraCast/AzuraCast#4050]
I've set everything up to record server side, but when a broadcaster is live, the system doesn't record.
I checked the broadcaster recording section of the appropriate broadcaster, the record is their with a start, and end time, but no file is associated.
Checking the recording folder in the docker image, shows it to be empty.
Any help would be appreciated.

**Comment by SlvrEagle23** [comment]
@stickbear2015 We were able to find and fix this problem in the latest Rolling Release version, per issue #4055.

**Comment by stickbear2015** [comment]
I'm commenting on this issue, as an interesting quirk has cropped up.
One of the stations I am apart of most recently did a radiothon, and due to the fact of a technical glitch, the second part did not record.
As shown by the text below
first chunk: Play/Pause   Download
Apr 23, 2021 3:14 PM
Apr 23, 2021 9:04 PM
479.48 MB
DELETE

Second chunk:  
Apr 23, 2021 9:05 PM
Apr 24, 2021 3:17 PM
  
You'll notice the second chunk does not have a play/pause column, or a delete column or a size column either.
What part of logs do I need to review to get a little more appropriate information for you?

**Comment by stickbear2015** [comment]
To clarify, it wasn’t a technical issue on the server, the technical issue was on the broadcaster’s end and they had to reconnect to the stream.




-- 
This email has been checked for viruses by AVG.
https://www.avg.com

**Comment by SlvrEagle23** [comment]
@stickbear2015 I've heard reports of this before, and I suspect there's a "race condition" involved between the disconnect of the first segment of the stream and the reconnection of the second segment. Unfortunately, when I looked into it, it seemed like it might be something internal to Liquidsoap, which would make it rather difficult for us to remedy on our end. I believe there's already a GitHub issue somewhere out there on our repository that's still active for this problem.

**Comment by stickbear2015** [comment]
@SlvrEagle23
Is their a way around the issue, meaning a set number of seconds broadcasters should wait before reconnecting?
Thanks.
Shane

Sent from Mail for Windows 10

**Comment by SlvrEagle23** [comment]
@stickbear2015 I'm not sure. That would require more investigation.
