### ISSUE TITLE
Record Live Broadcasts function no longer works properly in Stable / Rolling Releases. 

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#4055]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #2dc41d0

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
When a the setting 'record broadcasts' is enabled and a user broadcasts through their software, Liquidsoap does not save the recording properly to the disk, thus leaving a empty download folder. 

**To Reproduce**
Configure your station to setup Record Live Broadcasts and restart your station. After restarting you should attempt to stream to the station, after your stream has ended, inspect the Streamer panel and review fields. 

**Expected behavior**
Liquidsoap should be saving the recording properly and storing it in the right location. 

**Relevant Logs**
Liquidsoap Logs when I connected and it confirmed it was recording. I couldn't find any relevant Docker logs on the matter. 
```
2021/04/22 14:10:21 [lang:3] AzuraCast Live Connected Response: recording
2021/04/22 14:10:21 [input_streamer:3] Decoding...
2021/04/22 14:10:26 [live_fallback:3] Switch to audio_to_stereo_38817 with transition.
2021/04/22 14:10:36 [lang:3] Authenticating DJ: mitch
2021/04/22 14:10:37 [lang:3] AzuraCast DJ Auth Response: true
2021/04/22 14:10:37 [input_streamer:3] New metadata chunk ? -- DDG - OD (Official Music Video).
2021/04/22 14:11:05 [input_streamer:2] Feeding stopped: Mad.End_of_stream.
2021/04/22 14:11:05 [lang:3] DJ Source disconnected! Current live DJ: mitch
2021/04/22 14:11:05 [server:3] New client: 172.18.0.5.
2021/04/22 14:11:05 [server:3] Client 172.18.0.5 disconnected.
2021/04/22 14:11:05 [lang:3] AzuraCast Live Disconnected Response: true
2021/04/22 14:11:10 [dummy:3] Source failed (no more tracks) stopping output...
```

**Screenshots**
Broadcasts appearing blank - https://puu.sh/HAwHv/72aea09517.png

**Device(s):**

Desktop, Windows 10, Chromium. 

**Additional context**
Related to issue: #4052 & #4044

**Comment by Vaalyn** [comment]
I have investigated this issue and found the source of the problem.

I've prepared a PR for the flysystem-v2-extension that should fix this problem.

**Comment by SlvrEagle23** [comment]
The fix for this has been incorporated into the Rolling Release version, and will be included in the next stable release as well. Thanks to @Vaalyn and @SC2Mitch for helping investigate and fix this. ❤
