### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by xhuljanmeta** [AzuraCast/AzuraCast#4056]
Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.

Go Back

**Comment by Vaalyn** [comment]
As it stands there is no information in this issue that we can use to debug.

Please copy and fill out the issue template that we provide with the information we ask of you there and edit this issue.

Let me know when you have done this and I'll re-open this issue.

**Comment by xhuljanmeta** [comment]
Hello,
I can 
![Screenshot 2021-04-22 214051](https://user-images.githubusercontent.com/11904942/115775720-84f42b80-a3b3-11eb-8364-2d3fa9d39f64.png)
not log in to view log.
Thank you!

**Comment by xhuljanmeta** [comment]
![Screenshot 2021-04-22 214051](https://user-images.githubusercontent.com/11904942/115775810-9dfcdc80-a3b3-11eb-933a-c0cb22255105.png)
Hello,
I can not log in to view log.
Thank You!

**Comment by Vaalyn** [comment]
Follow the instructions laid out in our documentation on how to troubleshoot AzuraCast issues and how to access logs without access to the web interface:

https://docs.azuracast.com/en/user-guide/troubleshooting

https://docs.azuracast.com/en/user-guide/logs

**Comment by xhuljanmeta** [comment]
![Screenshot 2021-04-22 224927](https://user-images.githubusercontent.com/11904942/115783337-08664a80-a3bd-11eb-9f0b-33c661ae1bc7.png)
Hello!
Display this error.
Thank you!

**Comment by Vaalyn** [comment]
I have added a note to the docs page about logs on where to run this command. Please take another look at the docs page.

**Comment by xhuljanmeta** [comment]
Displayed This...
Thank you!



web_1                      | [2021-04-22T20:56:02.408439+00:00] AzuraCast.CRITICAL: Fatal error: Uncaught TypeError: Typed property App\Entity\Settings::$mail_sender_email must be string, null used in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2718 Stack trace: #0 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2718): ReflectionProperty->setValue() #1 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php(163): Doctrine\ORM\UnitOfWork->createEntity() #2 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php(77): Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateRowData() #3 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(213): Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateAllData() #4 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(739): Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll() #5 /var/azuracast/www/vendor/doctrine/orm/li in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2718 [] []

**Comment by xhuljanmeta** [comment]
ommand = 'list'; private ${Symfony\Component\Console\Application}singleCommand = FALSE; private ${Symfony\Component\Console\Application}initialized = TRUE; private ${Symfony\Component\Console\Application}signalRegistry = class Symfony\Component\Console\SignalRegistry\SignalRegistry { ... }; private ${Symfony\Component\Console\Application}signalsToDispatchEvent = [...] }; private ${Symfony\Component\Console\Command\Command}name = 'sync:run'; private ${Symfony\Component\Console\Command\Command}processTitle = NULL; private ${Symfony\Component\Console\Command\Command}aliases = []; private ${Symfony\Component\Console\Command\Command}definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 0; private $hasAnArrayArgument = FALSE; private $hasOptional = TRUE; private $options = [...]; private $shortcuts = [...] }; private ${Symfony\Component\Console\Command\Command}hidden = FALSE; private ${Symfony\Component\Console\Command\Command}help = ''; private ${Symfony\Component\Console\Command\Command}description = 'Run one or more scheduled synchronization tasks.'; private ${Symfony\Component\Console\Command\Command}fullDefinition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = TRUE; private $options = [...]; private $shortcuts = [...] }; private ${Symfony\Component\Console\Command\Command}ignoreValidationErrors = FALSE; private ${Symfony\Component\Console\Command\Command}code = class Closure { public $static = [...]; public $this = class App\Console\Application { ... }; public $parameter = [...] }; private ${Symfony\Component\Console\Command\Command}synopsis = []; private ${Symfony\Component\Console\Command\Command}usages = []; private ${Symfony\Component\Console\Command\Command}helperSet = class Symfony\Component\Console\Helper\HelperSet { private $helpers = [...]; private $command = NULL } }, $input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'sync:run', 1 => 'nowplaying']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = TRUE; private $options = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = ['command' => 'sync:run', 'task' => 'nowplaying']; protected $interactive = TRUE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(549) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private $consoleSectionOutputs = []; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(541) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = FALSE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/azuracast/www/vendor/symfony/console/Application.php:290
web_1                      |
web_1                      | [2021-04-22T21:00:31.822582+00:00] AzuraCast.CRITICAL: Fatal error: Uncaught TypeError: Typed property App\Entity\Settings::$mail_sender_email must be string, null used in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2718 Stack trace: #0 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2718): ReflectionProperty->setValue() #1 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php(163): Doctrine\ORM\UnitOfWork->createEntity() #2 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php(77): Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateRowData() #3 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(213): Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateAllData() #4 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(739): Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll() #5 /var/azuracast/www/vendor/doctrine/orm/li in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2718 [] []

**Comment by Vaalyn** [comment]
We still need information about your installation itself and what you did before encountering this error.

Please make use of the issue template that we provide and fill the information asked in there.
We do not want to ask every question on there separately.

**Comment by Vaalyn** [comment]
This has been reported as fixed by the latest update.

Please make use of the issue template next time you create an issue. To make support easier for us we have decided to close new issues if they ignore our issue template since the time investment and often times stress caused by this has been becoming too high for us.

**Comment by xhuljanmeta** [comment]
Okay 
Thank you :)
