### ISSUE TITLE
Unable to edit metadata of audio files

### ISSUE THREAD

**Issue by jdrodriguez** [AzuraCast/AzuraCast#4068]
When I click on the Edit button to try to edit the information for a track I get the following error:

TypeError at /var/azuracast/www/src/Normalizer/DoctrineEntityNormalizer.php L463: App\Normalizer\DoctrineEntityNormalizer::isEntity(): Argument #1 ($class) must be of type object|string, array given, called in /var/azuracast/www/src/Normalizer/DoctrineEntityNormalizer.php on line 196

**Comment by Vaalyn** [comment]
@SlvrEagle23 I can see this happen on the demo installation too so this is as far as I can see a general issue for the current rolling-release version. I think this is most likely caused by a change in https://github.com/AzuraCast/AzuraCast/commit/e893a939810b8baa5ffa4961611b3e0d396dfa09

**Comment by la-roleplay** [comment]
> @SlvrEagle23 I can see this happen on the demo installation too so this is as far as I can see a general issue for the current rolling-release version. I think this is most likely caused by a change in [e893a93](https://github.com/AzuraCast/AzuraCast/commit/e893a939810b8baa5ffa4961611b3e0d396dfa09)

This happens only when you add it to a playlist.

**Comment by SlvrEagle23** [comment]
This should be fixed in the latest Rolling Release.
