### ISSUE TITLE
Update failed (rolling release)

### ISSUE THREAD

**Issue by Deiiji** [AzuraCast/AzuraCast#4069]
**Using Docker installation method**

No

**AzuraCast version**

Rolling

**Host Operating System**

Ubuntu 20.04

**Describe the bug**

Update fail with:

TASK [azuracast-setup : Migrate Legacy Configuration (Update Mode)] ********************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/console azuracast:config:migrate", "delta": "0:00:00.080925", "end": "2021-04-24 17:39:29.779595", "msg": "non-zero return code", "rc": 255, "start": "2021-04-24 17:39:29.698670", "stderr": "PHP Fatal error:  During class fetch: Uncaught ParseError: syntax error, unexpected 'static' (T_STATIC) in /var/azuracast/www/src/Traits/AvailableStaticallyTrait.php:13\nStack trace:\n#0 /var/azuracast/www/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()\n#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()\n#2 /var/azuracast/www/src/Environment.php(9): spl_autoload_call()\n#3 /var/azuracast/www/vendor/composer/ClassLoader.php(478): include('/var/azuracast/...')\n#4 /var/azuracast/www/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()\n#5 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()\n#6 /var/azuracast/www/bin/console(11): spl_autoload_call()\n#7 {main} in /var/azuracast/www/src/Environment.php on line 9", "stderr_lines": ["PHP Fatal error:  During class fetch: Uncaught ParseError: syntax error, unexpected 'static' (T_STATIC) in /var/azuracast/www/src/Traits/AvailableStaticallyTrait.php:13", "Stack trace:", "#0 /var/azuracast/www/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()", "#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()", "#2 /var/azuracast/www/src/Environment.php(9): spl_autoload_call()", "#3 /var/azuracast/www/vendor/composer/ClassLoader.php(478): include('/var/azuracast/...')", "#4 /var/azuracast/www/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()", "#5 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()", "#6 /var/azuracast/www/bin/console(11): spl_autoload_call()", "#7 {main} in /var/azuracast/www/src/Environment.php on line 9"], "stdout": "\nFatal error: During class fetch: Uncaught ParseError: syntax error, unexpected 'static' (T_STATIC) in /var/azuracast/www/src/Traits/AvailableStaticallyTrait.php:13\nStack trace:\n#0 /var/azuracast/www/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()\n#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()\n#2 /var/azuracast/www/src/Environment.php(9): spl_autoload_call()\n#3 /var/azuracast/www/vendor/composer/ClassLoader.php(478): include('/var/azuracast/...')\n#4 /var/azuracast/www/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()\n#5 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()\n#6 /var/azuracast/www/bin/console(11): spl_autoload_call()\n#7 {main} in /var/azuracast/www/src/Environment.php on line 9", "stdout_lines": ["", "Fatal error: During class fetch: Uncaught ParseError: syntax error, unexpected 'static' (T_STATIC) in /var/azuracast/www/src/Traits/AvailableStaticallyTrait.php:13", "Stack trace:", "#0 /var/azuracast/www/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()", "#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()", "#2 /var/azuracast/www/src/Environment.php(9): spl_autoload_call()", "#3 /var/azuracast/www/vendor/composer/ClassLoader.php(478): include('/var/azuracast/...')", "#4 /var/azuracast/www/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()", "#5 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()", "#6 /var/azuracast/www/bin/console(11): spl_autoload_call()", "#7 {main} in /var/azuracast/www/src/Environment.php on line 9"]}

PLAY RECAP *****************************************************************************************
localhost                  : ok=23   changed=13   unreachable=0    failed=1    skipped=72   rescued=0    ignored=0

**To Reproduce**

Standard update

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context**

**Comment by Vaalyn** [comment]
Could you run `php --version` on the SSH terminal and post the output here?

**Comment by Deiiji** [comment]
Hello 
PHP 7.4.16 (cli) (built: Mar  5 2021 07:54:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies
  By the way Silver's key is still valid to connect to this server

**Comment by SlvrEagle23** [comment]
@Deiiji Try updating again; latest commit should fix that.

**Comment by Deiiji** [comment]
Worked, 8 fix the thing, thank you all

**Comment by SlvrEagle23** [comment]
@Deiiji Happy to help :)
