### ISSUE TITLE
WHMCS Integration

### ISSUE THREAD

**Issue by AndyRixon** [AzuraCast/AzuraCast#407]
I know I am not using the template provided, but are there any plans now or in the future to develop an automatic server provisioning module for WHMCS so that shoutcast providers can sell shoutcast services using AzuraCast with WHMCS.

**Comment by SlvrEagle23** [comment]
@AndyRixon We had a request regarding WHMCS support before (#284), and the request was closed with a somewhat detailed explanation of why it's not a priority for me at the moment.
