### ISSUE TITLE
Storing station data on the host machine doesn't work

### ISSUE THREAD

**Issue by ITRangering20** [AzuraCast/AzuraCast#4070]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.12.3 Stable

**Host Operating System**
Debian 10

**Describe the bug**
When I try to set a local path (from the host machine) in the storage location (recordings), I get an error.

**To Reproduce**
1. Create a folder in the home path of the host machine (/home/stationfiles) and set the owner to 1000
2. Go to _domain.com/admin/storage_locations_ and set the storage location (of recordings) path to /home/stationfiles
3. See error

**Expected behavior**
It should save all recordings in /home/stationsfiles on the host machine.

**Relevant Logs**
`App\Exception\ValidationException at /var/azuracast/www/src/Controller/Api/AbstractApiCrudController.php L155: Object(App\Entity\StorageLocation): Unable to create a directory at /home/stationfiles. mkdir(): Permission denied`

**Comment by Vaalyn** [comment]
In order for that folder being accessable by the docker container/s you'll have to mount it into the container/s first.

See these two documentation entries for reference:

https://docs.azuracast.com/en/administration/docker#mounting-a-directory-into-a-station

https://docs.azuracast.com/en/administration/docker#storing-your-station-data-on-the-host-machine

**Comment by ITRangering20** [comment]
Thank you! I have followed the docs for [#storing-your-station-data-on-the-host-machine](https://docs.azuracast.com/en/administration/docker#storing-your-station-data-on-the-host-machine) and now I see all my station files in my directory on the host machine.
Though the recordings were not saved and by loading the recordings in the ACP, it loads endless and looking at the console there is an error by loading _domain.com/api/station/1/streamer/1/broadcasts?internal=true&rowCount=0_


```
Argument 1 passed to League\Flysystem\Filesystem::fileExists() must be of the type string, null given, called in /var/azuracast/www/src/Controller/Api/Stations/Streamers/BroadcastsController.php on line 66
Filesystem.php : 34
```

**Comment by Vaalyn** [comment]
I think this problem has been fixed in the rolling-release.

**Comment by ITRangering20** [comment]
Yes. In the rolling-release, it work's fine! Thank you very much for your help @Vaalyn @SC2Mitch 🙏
