### ISSUE TITLE
Profiler Control Panel Link not working

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#4072]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #e2de28b (2021-04-25 7:24)

**Host Operating System**
Ubuntu 20.04 LTS

**Describe the bug**
The link onm' dashboard redirects me back to the home page/ dashboard.

Link looks like this: http://azuracast.example.com/?SPX_UI_URI=%2F&SPX_KEY=dev

**Screenshots**
![image](https://user-images.githubusercontent.com/42640247/115987959-b6d5df80-a5b7-11eb-939d-3fe2c47d1d03.png)

**Comment by SC2Mitch** [comment]
I did note this when I was testing the function myself on my local instance, I'll take another look and reply to this when I'm free

**Comment by SC2Mitch** [comment]
My investigation has been completed and I do believe this is a bug for the developers to review. 

This is my configuration in the `azuracast.env` NOTE: I have changed the field 'IP Whitelist' to my local IP, server IP, alas nothing happens, still redirects to the dashboard. 
```
# Enable the profiling extension.
# Profiling data can be viewed by visiting http://your-azuracast-site/?SPX_KEY=dev&SPX_UI_URI=/
# Default: 0
PROFILING_EXTENSION_ENABLED=1

# Profile ALL requests made to this account.
# This will have significant performance impact on your installation and should only be used in test circumstances.
# Default: 0
PROFILING_EXTENSION_ALWAYS_ON=1

# Configure the value for the SPX_KEY parameter needed to access the profiling dashboard
# Default: dev
# PROFILING_EXTENSION_HTTP_KEY=dev

# Configure the IP whitelist for the profiling dashboard
# Default: *
# PROFILING_EXTENSION_HTTP_IP_WHITELIST=*
```
I did observe this error in my Docker logs however, when the profile extension always on was enabled. 
```
web_1                      | 2021/04/25 13:19:50 [error] 61#61: *29 FastCGI sent in stderr: "PHP message: PHP Notice:  SPX: access not granted: "172.27.0.4" IP is not in white list ("127.0.0.1") in Unknown on line 0" while reading response header from upstream, client: 172.27.0.4, server: localhost, request: "GET /?SPX_UI_URI=%2F&SPX_KEY=dev HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "crosshost.ml", referrer: "https://crosshost.ml/dashboard"
```

**Comment by SlvrEagle23** [comment]
@SC2Mitch The whitelist variable should probably be kept at * since the IP the profiling extension is seeing is the internal Docker IP coming from the nginx_proxy service, not your IP itself.

I'm not sure there's an easy way to tell the SPX extension what the "real IP" is, even though we tend to get that in a HTTP header of its own.

**Comment by SC2Mitch** [comment]
I tried keeping it under the `*` and it still refused me access with this error:
web_1                      | 2021/04/25 14:02:02 [error] 56#56: *148 FastCGI sent in stderr: "PHP message: PHP Notice:  SPX: access not granted: "192.168.32.4" IP is not in white list ("127.0.0.1") in Unknown on line 0" while reading response header from upstream, client: 192.168.32.4, server: localhost, request: "GET /?SPX_UI_URI=%2F&SPX_KEY=dev HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "crosshost.ml", referrer: "https://localhost/dashboard"

I'm unsure as to why its throwing this.  My configuration still remains the same as above.

**Comment by Vaalyn** [comment]
@SC2Mitch I've checked this on a rolling-release installation of my room mate and can confirm that there seems to be something wrong with the default value for the IP whitelist.

After uncommenting the `# PROFILING_EXTENSION_HTTP_IP_WHITELIST=*` line and restarting AzuraCast it was working correctly. Gonna be looking into where exactly the default might be missing.

**Comment by Vaalyn** [comment]
That was rather fast^^

The default is set to `PROFILING_EXTENSION_HTTP_IP_WHITELIST=127.0.0.1` in the Dockerfile and since the container does not see you as localhost it naturally declines access.

The `# Default: *` description of in the `azuracast.env` is not really correct then.

**Comment by SC2Mitch** [comment]
Can confirm this issue has since been fixed in the latest rolling release, tag me if your having any issues @Abqehebter

**Comment by Abqehebter** [comment]
@SC2Mitch With the solution everything works. Super many thanks!
