### ISSUE TITLE
playlist name dont display in folder

### ISSUE THREAD

**Issue by akrapovicalex** [AzuraCast/AzuraCast#4079]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #4cd4abe 

**Host Operating System**
20.04

**Describe the bug**
Playlists names dont display in folder

**To Reproduce**
Selected two or more playlists

**Screenshots**
![29B4O0agUX](https://user-images.githubusercontent.com/52565001/116136368-8171e480-a6d2-11eb-9c73-35e7901aa990.gif)

**Device(s):**

- Device: PC
- OS: Windows 10
- Browser: Chrome 
- Version:  90.0

**Comment by SC2Mitch** [comment]
I'm struggling to reproduce this on my local instances, is there any errors showing up in the browser console? (F12 - Console, refresh the page and reproduce this bug) also can you check your Network tab to see if there's any errors being flagged?
