### ISSUE TITLE
Can I change my Domain Name on an existing Azuracast Install?

### ISSUE THREAD

**Issue by pwrj** [AzuraCast/AzuraCast#4080]
I want to change my domain name on Azuracast? Is that possible, if so how?

Docker Installation Method.

**Comment by renatopinto89** [comment]
If you have a domain, you can manage domains and subdomains on CloudFlare for free

**Comment by pwrj** [comment]
Thanks. So If I wanna replace an old domain, just add the domain?

**Comment by Abqehebter** [comment]
`So If I wanna replace an old domain, just add the domain?`

@pwrj Yes.
