### ISSUE TITLE
Please help: Unable to Run Synchronization Tasks for "Now Playing Data"

### ISSUE THREAD

**Issue by pwrj** [AzuraCast/AzuraCast#4081]
**Using Docker installation method**

**AzuraCast version**

**Host Operating System**

**Describe the bug**
I get this when I run: Synchronization Tasks, Now Playing Data task:

"[2021-04-26T23:21:44.541495+00:00] AzuraCast.ERROR: NowPlaying\Result\Client::__construct(): Argument #1 ($uid) must be of type string, int given, called in /var/azuracast/www/vendor/azuracast/nowplaying/src/Adapter/SHOUTcast2.php on line 113 {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} {"station":{"id":1,"name":"My Station Name"}}"

**To Reproduce**

**Comment by SC2Mitch** [comment]
We still require some more basic information from you, can you fill in the format and this will be reviewed properly.

**Comment by pwrj** [comment]
My Apologies:

**Using Docker installation method**



**AzuraCast version**



**Host Operating System**



**Describe the bug**
When I login to my station, I see the following: 
Synchronized Task Not Recently Run
The "Now Playing Data" synchronization task has not run recently. This may indicate an error with your installation

**To Reproduce**



**Expected behavior**
I expected to run the task with no issues.


**Relevant Logs**
N/A


**Screenshots**
See Above


**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context**
N/A

**Comment by SlvrEagle23** [comment]
@pwrj This should be fixed as of the latest rolling update.

**Comment by enigmathion** [comment]
Is this correction made for both the rolling release and the stable version?

**Comment by pwrj** [comment]
Thank you @SlvrEagle23 - I can confirm that my issues are fixed.👍🏾
