### ISSUE TITLE
Run azuracast cli command with crontab

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#4085]
v0.12.3 Stable • Docker • PHP 7.4

For a couple of stations that use the advanced playlist options to work properly, we need to restart these stations at least once a day. If we do not restart the stations, the podcasts that are downloaded via podget and that we access by mounting a folder, are not updated. By restarting the station it seems that if it detects these new contents again.

We are trying to configure an early morning restart with crontab so that we do not have to perform the reboots by hand on a daily basis, but we do not see that it finishes working.

```
56 04 * * * /var/azuracast/docker.sh cli azuracast:radio:restart radio_la_granja
```

This is the line in crontab, it should work, but it doesn't. Any idea what may be going on?

**Comment by Vaalyn** [comment]
Can you see any errors in the `/var/log/syslog` related to the cronjob?

**Comment by fidegr** [comment]
Apr 27 04:55:01 radiobot CRON[8919]: (root) CMD (/var/azuracast/docker.sh cli azuracast:radio:restart agora_sol_radio)

**Comment by Vaalyn** [comment]
Hm okay so no errors there.

When you manually run `/var/azuracast/docker.sh cli azuracast:radio:restart agora_sol_radio` does it work?

**Comment by fidegr** [comment]
> Hm okay so no errors there.
> 
> When you manually run `/var/azuracast/docker.sh cli azuracast:radio:restart agora_sol_radio` does it work?

Hello,

no, first I have to go to the / var / azuracast / folder

**Comment by fidegr** [comment]
Finally the solution that we have seen that works is to create a bash script where docker.sh is executed. 

In any case, the failure that we have with the contents downloaded in the stations that use the advanced playlist options continues to occur and is only corrected by restarting the station daily.

It seems that Azuracast does not update well the media that is downloaded outside of docker and accessed through a mounted folder. One doubt, do you think that using `docker.sh cli azuracast: debug: optimize-tables` could solve the problem?

It would be a less aggressive solution than restarting the stations.

**Comment by Vaalyn** [comment]
I don't think that this command would help in your use-case since you are using the `advanced playlist options`.

When using those it's necessary for the playlist to be made available to Liquidsoap.
If it's a completely new playlist that hasn't existed when the Liquidsoap process was started it won't be able to recognise it since it needs to re-run the liquidsoap config for that and LS does not support hot-reloading currently.

If it's a playlist that is already included in the LS config when the LS process was started it should be possible for LS to notice that the contents were changed as playlists in the LS config are set to `reload_mode="watch"`.

**Comment by fidegr** [comment]
Finally we have created a bash script to execute the reboots we need at dawn from there. Add / bin / bash was missing for docker.sh to run correctly 

`/bin/bash docker.sh cli azuracast:debug:optimize-tables`

**Comment by fidegr** [comment]
Hi, we still can't run cli commands from crontab. Is there a way to define in docker.sh cli the location of the docker-compose.yml file?

![image](https://user-images.githubusercontent.com/16152034/116844868-a1c70500-abe4-11eb-99ac-794bf0dc81a6.png)

**Comment by SlvrEagle23** [comment]
@fidegr At that point, you might as well just actually run the command that `./docker.sh cli` is actually running itself, which would in your case look a little like:

```
docker-compose -f /var/azuracast/docker-compose.yml run --rm --user="azuracast" web azuracast_cli azuracast:debug:optimize-tables
```

**Comment by fidegr** [comment]
> @fidegr At that point, you might as well just actually run the command that `./docker.sh cli` is actually running itself, which would in your case look a little like:
> 
> ```
> docker-compose -f /var/azuracast/docker-compose.yml run --rm --user="azuracast" web azuracast_cli azuracast:debug:optimize-tables
> ```
> 
> It's worth pointing out that the `optimize-tables` script does nothing more than just remove any extra space used by database tables; it isn't intended to reset any caches or otherwise modify the system, so it would be unexpected to me if it actually fixed any issues that aren't related to available disk space.

it works, thanks a lot

**Comment by fidegr** [comment]
Hi, another crontab related query. We have run two vps with Azuracast. One in production with the radio stations that we share on the server and a second with a single station for testing. The fact is that in the test station, following the indications of @SlvrEagle23  crontab, it correctly restarts the station at the time that we indicate. But when we do the same on the main station, the station is not restarted. We have been reviewing and we do not find the problem.

Both stations work with debian 10 and Azuracast rolling release.

**Comment by SlvrEagle23** [comment]
@fidegr Since Docker is managed at the host level, we don't manage upgrading it if it's outdated; our installation helper for it is meant to make getting started easier, but updating Docker itself is up to the host operator, since it typically doesn't present any issues for us.

You can update Docker via your host's package manager once a new version ships.
