### ISSUE TITLE
Error on play in CUE EDITOR

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#4093]
**Using Docker installation method**
No 

**AzuraCast version**
Rolling Release #e94f90c (2021-04-29 10:30) • Ansible • PHP 8.0

**Host Operating System**
Ubuntu 16.04

**Describe the bug**
Hello everyone. I can't listen to audio from the CUT EDITOR preview, when I press play in console I get an error, and no audio is heard. Can you help me? I leave a screen

![image](https://user-images.githubusercontent.com/22561729/116550236-cd9d6e80-a8f6-11eb-9a53-d5bd477115bc.png)

![image](https://user-images.githubusercontent.com/22561729/116550270-daba5d80-a8f6-11eb-8285-e602ab976e7c.png)

**Comment by SC2Mitch** [comment]
Error 403 relates to permissions, it may be a issue with your local installation. 

I'm also unable to replicate this on my Docker instance which is running the latest version

**Comment by Ilario42** [comment]
@SC2Mitch Fixed using Docker installation. Thank you very much.
