### ISSUE TITLE
Enter On MariaDB From Docker Installation

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#4097]
**Using Docker installation method**
Yes

**AzuraCast version**
Last

**Host Operating System**
Ubuntu 20

I am trying to enter the database after installing for the first time via Docker method. I found this old post, but it doesn't seem to work.
Until now I have always used the traditional installation and then through the "mysql" command I was able to enter. Not now.
How can I enter the DataBase?

https://github.com/AzuraCast/AzuraCast/issues/266

![image](https://user-images.githubusercontent.com/22561729/116666921-d6944b80-a99b-11eb-927d-357efc3760b6.png)

**Comment by SlvrEagle23** [comment]
@Ilario42 MariaDB (the MySQL drop-in replacement) is contained within its own Docker container and thus can't be accessed via normal means on the host.

You can, however, run `./docker.sh db` and it should connect you into the database container with a fully authenticated terminal.

**Comment by Ilario42** [comment]
> @Ilario42 MariaDB (the MySQL drop-in replacement) is contained within its own Docker container and thus can't be accessed via normal means on the host.
> 
> You can, however, run `./docker.sh db` and it should connect you into the database container with a fully authenticated terminal.

How can I make the database accessible from the outside then?  Thanks for your help @SlvrEagle23

**Comment by Ilario42** [comment]
Solved All my problems, DataBase and https://github.com/AzuraCast/AzuraCast/issues/4093  by reinstalling the NonDocker version and running the command `chmod -R 777 azuracast`
3 days to format my dedicated to no avail. The important thing is that everything is OK now.

Thank you
