### ISSUE TITLE
Add file name sanitisation as custom action hook to SFTPGo

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#4104]
In order to prevent issues caused by invalid file names that Flysystem is unable to handle we should apply the same file name sanitisation from the web uploader to files uploaded via SFTP.

This can be done via a [`Custom Action`](https://github.com/drakkan/sftpgo/blob/main/docs/custom-actions.md) for SFTPGo.

For reference of what type of issues this should prevent see https://github.com/AzuraCast/AzuraCast/issues/4094

**Comment by SlvrEagle23** [comment]
@Vaalyn Latest Rolling Release incorporates special handling for SFTP uploads (renaming them if their file path doesn't match the sanitized version), and also adds handling for renaming/deleting files so these are handled in the exact same way their batch action equivalents are handled (preserving things like playlist folders, etc).
