### ISSUE TITLE
Display public Song Requests

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#411]
- **Installation Method:** Traditional
- **Host OS (if using Docker):** Ubuntu 16.04

 Hi,
I have a wordpress site and for some time now, the iframe code is not displayed concerning the "Song requests" and also the player.

`<iframe src="http://217.182.128.137/public/radio_deep_underground/embed-requests" frameborder="0" allowtransparency="true" style="width: 100%; min-height: 850px; border: 0;"></iframe>`

Thank you.

**Comment by SlvrEagle23** [comment]
@ckeurk Sorry about that, it got lost in the big middleware refactor and I forgot to re-enable frame embedding for the few pages that actually _should_ be embeddable.

Should be fixed now.

**Comment by ckeurk** [comment]
Problem solved Thank you
