### ISSUE TITLE
Geolite Maxmind Map Not Displaying

### ISSUE THREAD

**Issue by buddhatunes** [AzuraCast/AzuraCast#4110]
Ubuntu 20.04 LTS
Rolling Release #95aea5f (2021-05-02 3:15) • Docker • PHP 8.0
GeoLite version "GeoLite2-City (2021-04-27)" is currently installed.

New install. The Listener Map does not display a map. The location markers display listeners centered in a group on a gray background.

**Comment by SC2Mitch** [comment]
We need some more information to debug this, please use the format we provide on new issues, thank you.

**Comment by buddhatunes** [comment]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #95aea5f (2021-05-02 3:15) • Docker • PHP 8.0

**Host Operating System**
Ubuntu 20.04 LTS

**Describe the bug**
I entered my MaxMind license key in the "Install Geolite Database" and this message displays as a result: 'GeoLite version "GeoLite2-City (2021-04-27)" is currently installed.'

When I am in the Admin panel, and click on Reports, then click on Listeners, then select "Live Listeners" and wait for live listeners to display on a map; a map does not display, there is just a gray background with all locations centered in the screen rather than scattered over a map.

**To Reproduce**
In the Admin panel, click on Reports, click on Listeners, select "Live Listeners" and wait for live listeners to display on a map.

**Expected behavior**
For listeners to display on a map.

**Comment by buddhatunes** [comment]
I see the label "needs more information" is still assigned to this issue. What more information is needed?

**Comment by Vaalyn** [comment]
Mainly logs, like errors from your browsers JS console and AzuraCast application log.

Without seeing an error message it's very hard to diagnose why the map doesn't show.

**Comment by buddhatunes** [comment]
Here are the errors from the Firefox browser console:

services.settings: main/normandy-recipes-capabilities sync already running RemoteSettingsClient.jsm:497
services.settings: security-state/intermediates Signature failed  TypeError: NetworkError when attempting to fetch resource. RemoteSettingsClient.jsm:934
services.settings: TypeError: NetworkError when attempting to fetch resource. remote-settings.js:318
BroadcastService: receivedBroadcastMessage: handler for remote-settings/monitor_changes threw error: TypeError: NetworkError when attempting to fetch resource. PushBroadcastService.jsm:264
[Exception... "Favicon at "https://theme.zdassets.com/favicon.ico" failed to load: Forbidden."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 253"  data: no] FaviconLoader.jsm:253:22
TypeError: (destructured parameter) is undefined Grammarly-bg.js:2:1311909

**Comment by Vaalyn** [comment]
I don't recognise any of these `.jsm` and `.js` files mentioned in those errors.

Are you sure these are errors from the JS console of the Listeners page?

**Comment by buddhatunes** [comment]
How about this from Chrome Developer Tools / Console:

Failed to load resource: the server responded with a status of 404 (Not Found)
1.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
0.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
0.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
DevTools failed to load SourceMap: Could not load content for https://z.countrymusic.io/static/dist/lib/bootstrap/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://z.countrymusic.io/static/dist/lib/moment/moment.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://z.countrymusic.io/static/dist/lib/moment/locales.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by Vaalyn** [comment]
These here are most likely related to the map:

```
1.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
0.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
0.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

Could you check the `Network` tab in the dev tools and post a screenshot of the `Headers` -> `General`?

**Comment by SlvrEagle23** [comment]
Figured it out: if your theme is set to the "prefer system default" theme, it was causing the map tiles not to load, as there was no tile URL for the corresponding setting (`browser` instead of `light`/`dark`).

The rolling release update pushing out right now should fix this issue and use the appropriate theme, even if you're using the prefer-browser setting.
