### ISSUE TITLE
Script to delete old recordings

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#4111]
Rolling Release #0a10378 (2021-04-30 13:17) • Docker • PHP 8.0

In some stations, users are a bit clueless and do not delete the recordings after downloading them. We have prepared a script that checks the folder  / var / lib / docker / volumes / azuracast_station_data / _data / radio_almaina / recordings

find /var/lib/docker/volumes/azuracast_station_data/_data/radio_almaina/recordings -type f -mtime +30 -exec rm {} \;

and delete those older than 30 days. Is it safe to delete these files like this?

**Comment by SlvrEagle23** [comment]
@fidegr Docker advises that you not delete files in the volumes it manages like that, but honestly we've never run into any issues with doing exactly that, and there's nothing wrong with just removing the broadcast file; our system can detect the missing file and not show the "Download" link.

**Comment by fidegr** [comment]
Hello,
everything works fine, except for one detail, the deleted recordings are still listed. Can we do something about this?

![image](https://user-images.githubusercontent.com/16152034/117560679-3374bd80-b090-11eb-974a-2a1b4b249801.png)
