### ISSUE TITLE
Unexpected album arts and album values on public pages

### ISSUE THREAD

**Issue by yarik2720** [AzuraCast/AzuraCast#4112]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.12.4 Stable • Docker • PHP 8.0

**Host Operating System**
Ubuntu 16.04

**Describe the bug**
On public pages in song history displays album arts and album name, on song requests displays album arts

**To Reproduce**
1. Go to Administration -> Custom branding
2. Check "Hide Album Art on Public Pages" and Save
3. Open Public page
4. Click on Song requests
5. You can see album arts
6. Click on Song history, you can see album arts and album names

**Expected behavior**

You shouldn't see album arts on public pages at all while option was enabled.
Also displaying album name is unexpected

**Screenshots**

![image](https://user-images.githubusercontent.com/1839978/116856229-743d8400-ac03-11eb-8eb7-b7f109a47033.png)
![image](https://user-images.githubusercontent.com/1839978/116856265-81f30980-ac03-11eb-8f1e-2995387a54b1.png)
![image](https://user-images.githubusercontent.com/1839978/116856286-8fa88f00-ac03-11eb-8805-457c33102a95.png)

**Comment by SC2Mitch** [comment]
I'm unable to replicate the album art for the request a song, but I've been able to replicate the Song History album art on Rolling Release #95aea5f 

I shall be taking another look at this when I'm free later.

**Comment by yarik2720** [comment]
Still actual on 0.13.0

**Comment by yarik2720** [comment]
Still actual on 0.14.0
