### ISSUE TITLE
Restrict user settings on request page

### ISSUE THREAD

**Issue by yarik2720** [AzuraCast/AzuraCast#4113]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.12.4 Stable

**Host Operating System**
Ubuntu 16.04

**Describe the bug**
Add ability to restrict setting number of tracks per page on public page.
Any user can change it from 10 to All and make server overload if there is a lot of tracks. For example I have ~3000 tracks and someone can make requests spam with unlimited page.
Also there is needs to be added minimum entered symbols in search field to run search, for example now it begin to search even with one entered symbol and this also can be spammed

**To Reproduce**
1. Go to Public page
2. Click on Request Song
3. Switch Rows per page to All

1. Go to Public page
2. Click on Request Song
3. Enter in search field letter `a`

**Expected behavior**
Settings of rows per page should be only on admin side and doesn't allow to show all.
Search filed should have minimum amount of symbols to start search

**Comment by SC2Mitch** [comment]
I propose adding a 5 second delay when users are using the search field, while it's a small delay, it might be helpful to prevent extensive abuse, or perhaps a `.env` variable to extend the delay if required?

**Comment by SlvrEagle23** [comment]
@yarik2720 The latest commit to the Rolling Release branch limits the number of per-page rows an unauthenticated user can request to 25 rows on both the client-side dropdown and the server-side pagination implementation, preventing them from hammering the database by requesting all records.
