### ISSUE TITLE
Duplicate Artist file played from the same playlist within minutes

### ISSUE THREAD

**Issue by oliverneedham** [AzuraCast/AzuraCast#4116]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.12.4 Stable

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
Two songs by an artist played back to back from the same playlist, with the "Avoid Duplicate Artists/Titles" option enabled on the playlist.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have two tracks by the same artist in the same playlist. (In this instance, a different mix of the same song)
2. The playlist is scheduled and plays Track A by Artist A.
3. Track B by Artist A plays immediately after it.

**Expected behaviour**
Media files that have the same titles and/or track names should avoid playing one after the other.

The setting in the Playlist "Avoid Duplicate Artists/Titles" was active.
The description of the feature is:
> Whether the AutoDJ should attempt to avoid duplicate artists and track titles when playing media from this playlist.

This is potentially ambiguous and maybe doesn't describe how often it will try to put a gap between tracks by the same artist within the same playlist. In most radio situations this is somewhere between 2-3 hours.

If, according to my situation, this is the expected behaviour, maybe;
a) the description of this checkbox could be improved to help understand the impact it has.
b) an improved version could be introduced, which includes a specific timeframe in which the same artist/track titles are avoided.

I can understand that this maybe a LiquidSoap setup issue, so have provided [my config here](https://today.olivr.uk/github/liquidsoapsetup_2129_20210502.txt).

**Relevant Logs**
These are the two items in question and their associated metadata (from an API request).
`{
    "id": 103,
    "album": "One Night",
    "genre": "Dance",
    "lyrics": null,
    "isrc": null,
    "length": 161.93,
    "length_text": "2:41",
    "path": "mk-onenight.mp3",
    "mtime": 1616793362,
    "amplify": null,
    "fade_overlap": null,
    "fade_in": 0.9,
    "fade_out": 3.1,
    "cue_in": null,
    "cue_out": 159.3,
    "art_updated_at": 1615656393,
    "playlists": [
      {
        "id": 12,
        "name": "Time - Night",
        "weight": 11
      }
    ],
    "unique_id": "f0cb9242ac0b73e76053f284",
    "song_id": "dc85bf85dc0935793b79f950e42dd6bd",
    "text": "MK & Sonny Fodera - One Night",
    "artist": "MK & Sonny Fodera",
    "title": "One Night",
    "custom_fields": [],
    "links": {
      "self": "https://todayradio.olivr.uk/api/station/1/file/103"
    }
  },`
  `{
    "id": 104,
    "album": "One Night",
    "genre": "Dance",
    "lyrics": null,
    "isrc": null,
    "length": 244.95,
    "length_text": "4:04",
    "path": "mk-onenight(6amremix).mp3",
    "mtime": 1616793355,
    "amplify": null,
    "fade_overlap": null,
    "fade_in": null,
    "fade_out": 1.4,
    "cue_in": null,
    "cue_out": 241.4,
    "art_updated_at": 0,
    "playlists": [
      {
        "id": 12,
        "name": "Time - Night",
        "weight": 13
      },
      {
        "id": 19,
        "name": "Time - 06",
        "weight": 5
      }
    ],
    "unique_id": "4e96eea2b6ae5cb12ba9ec8a",
    "song_id": "f3f28b4967456c10852b7d38739ae171",
    "text": "MK & Sonny Fodera - One Night (6am Remix)",
    "artist": "MK & Sonny Fodera",
    "title": "One Night (6am Remix)",
    "custom_fields": [],
    "links": {
      "self": "https://todayradio.olivr.uk/api/station/1/file/104"
    }
  },`

**Screenshots**
Song Playback Timeline: https://imgur.com/HybjM2R
Playlist Basic Info: https://imgur.com/7QKO9PL
Playlist Schedule: https://imgur.com/oM9m5Jf

**Device(s):**
- Device: Desktop
- OS: MacOS
- Browser: Chrome
- Version: 90.0.4430.85

**Additional context**
Associated Timeline CSV for the day of the incident reported here: https://today.olivr.uk/github/today_radio_timeline_20210503_to_20210503.csv

Is it possible that if a track from a 'Jingle Mode' played in between them, this would mean two songs by the same artist could play back to back? (Jingle Mode tracks aren't displayed as currently playing or in the Song Playback Timeline).
Even if this was the case, I wouldn't expect songs by the same artist to play so closely to one another.

**Comment by Abqehebter** [comment]
Such problems have been reported here many times, including many by me: https://github.com/AzuraCast/AzuraCast/issues/3957, https://github.com/AzuraCast/AzuraCast/issues/3863

But this is only more or less a bug. If your playlist is set to shuffle, it plays every, really every song once completely. Towards the end, it usually happens that there was still 2x MK, for example. This can not be prevented at the moment, as explained in detail here: https://github.com/AzuraCast/AzuraCast/issues/3863#issuecomment-812822849

Quote there: _"Earlier this year in conversations with one of the developers of AzuraCast, I suggested making duplicate prevention configurable per playlist and separating the feature so users can prevent duplicate titles or artists, or both. This may help you._

_I also have thought of a new suggestion to store the original artist of a track in the database. This would be fetched from track metadata when uploaded, or added in the Music Files interface. This would mean different compositions with the same title, where they are not covers, will be allowed to be played. For example, Jump, Best of My Love, Money, Shout, Gloria, Lady, Daniel, Photograph, A Thousand Years, America, Who's that Girl?, to name a few."_

So to prevent this, possibly note:
- Include less of the same artist.
- lower the time period to avoid repetition (I have it set to 60 everywhere by now)
- add more different songs to your playlist.

I hope I could help you a little bit with this. The AzuraCast team can correct me again.
