### ISSUE TITLE
Change height for embedded player/widget on twitter page

### ISSUE THREAD

**Issue by countrymusicfy** [AzuraCast/AzuraCast#4119]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #95aea5f

**Host Operating System**
Ubuntu 20.04 LTS

**Describe the bug**
I tweeted the the URL of my station's public player page, and the player component automatically appeared in the tweet that included an embedded player for my station. Unfortunately, the height of the player is only 150px. Is there a way I can customize the player's height to 700px? I already do this with the embed code for the embedded widget on my website.

**To Reproduce**
Tweet the URL of your station's public player page.

**Expected behavior**
A custom height of 700px for the embedded widget on my twitter page.

**Comment by SC2Mitch** [comment]
If I'm reading this correctly, the height is managed in this field, https://github.com/AzuraCast/AzuraCast/blob/main/frontend/vue/Stations/Profile/EmbedModal.vue#L173-L175 and it can possibly be changed to suit the 700px that you require, I'll do some local testing to see if this is the case.

**Comment by buddhatunes** [comment]
Thank you, I also noticed that the embedded player on twitter does not display on my iphone, just the url to the station's public player page.

**Comment by SlvrEagle23** [comment]
@buddhatunes This is a limitation of Twitter itself; on some platforms the embeddable player doesn't embed the way it does on desktop.

**Comment by buddhatunes** [comment]
@SlvrEagle23, thank you for the quick reply, can you confirm that the embeddable player's height on twitter can be changed at:
  
[](https://github.com/AzuraCast/AzuraCast/blob/main/frontend/vue/Stations/Profile/EmbedModal.vue#L173-L175)

**Comment by buddhatunes** [comment]
https://github.com/AzuraCast/AzuraCast/blob/main/frontend/vue/Stations/Profile/EmbedModal.vue#L173-L175

**Comment by SlvrEagle23** [comment]
@buddhatunes It can, but that would require rebuilding the static assets on your installation, which is an advanced function we don't officially support.

**Comment by buddhatunes** [comment]
@SlvrEagle23 Not sure what you mean by rebuilding the static assets. If I edit line 175 and change 150px to 700 px, will that change the height of the embedded player on twitter, or is there more involved than that?

case 'player':
                default:
                    return '150px';

**Comment by SlvrEagle23** [comment]
@buddhatunes No, because that's the raw source code. You'd have to rebuild the static assets. In development, we'd run:

```
cd frontend
docker-compose run --rm frontend npm run build
```
