### ISSUE TITLE
Problem with media upload

### ISSUE THREAD

**Issue by kevinboeger** [AzuraCast/AzuraCast#4122]
**Using Docker installation method**
Yes

**AzuraCast version**
Latest stable

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
TypeError at /var/azuracast/www/vendor/james-heinrich/getid3/getid3/getid3.lib.php L437: decbin(): Argument #1 ($num) must be of type int, string given

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**
https://i.imgur.com/p6NRvJr.png

**Comment by Abqehebter** [comment]
Remove the "07.", "12." ... before the file name, maybe it works then?

**Comment by kevinboeger** [comment]
https://i.imgur.com/FcYPHXj.png 

still the same result :/

**Comment by Abqehebter** [comment]
I'm not quite sure anymore if the bug was fixed in a rolling release version or if it's just the file itself. Commit https://github.com/AzuraCast/AzuraCast/commit/8dfe6af6663be80f0ed7a4b7a4f7165ac7465794 looks like it to me.

**Comment by SC2Mitch** [comment]
Can you upload the files to a uploading site, Google Drive, etc, so we can investigate this issue properly?

**Comment by Vaalyn** [comment]
Related issue from the getID3 library (for debugging purposes): https://github.com/JamesHeinrich/getID3/issues/299
