### ISSUE TITLE
Dropbox storage location putting media into playlists

### ISSUE THREAD

**Issue by jweston010** [AzuraCast/AzuraCast#4123]
**Using Docker installation method**

**AzuraCast version**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context**

I don't think this is a bug, but when I switch my stations media storage location over dropbox, and I go to put my music in the fall playlist, is it working? Of course it may take a long time, since it's coming from dropbox, and there's like almost 50 gigs of music. I noticed that when I did this, and then went and removed the media from the local storag location, it went back to the azuracast error message as if there's no music in the system. I was thinking I should probably take a look at the audit log to see if I get any info. like I said probably this isn't a bug, I'm sure it's just going to take a long time to process the media. From dropbox that is. I noticed that when I switch from local to remote storage, the five minute media folder sink task requires to be manually run. I currently have it set to local storage since it works, could the fact that I am using the same access token in all three of my storage locations, station media, broadcast recordings, and back ups, cause a problem?￼￼￼￼

**Comment by SlvrEagle23** [comment]
@jweston010 Yeah, if you're using Dropbox as your media storage location and you're dealing with a library that big, things are going to take extremely long.

**Comment by jweston010** [comment]
that does make sense. So I’m probably better off using dropbox for station recordings in my case. Too bad there wasn’t a wait you have media in more than one storage location for the same station. That would probably confuse the autoDJ.
