### ISSUE TITLE
Add Icecast mountpoint alias - Possible feature request. 

### ISSUE THREAD

**Issue by digitaldarragh** [AzuraCast/AzuraCast#4125]
Using Docker: Yes
Azuracast version: 0.12.4

I'm only a week into using Azuracast so I'm still very much a beginner.  My objective is to create Icecast mountpoint aliases. 

I have attempted to configure this in Station \ Edit Profile | Broadcasting in the field "Advanced Custom Configuration". 

The JSON I have used is: 
```
  "paths" : {
    "alias source" : "/live", "dest" : "/live.mp3"
    "alias source" : "/live.m3u", "dest" : "/live.mp3"
}
```

I have also alternatively tried by entering the XML instead. 
```
<paths>
    <alias source="/live" dest="/live.mp3"/>
    <alias source="/live.m3u" dest="/live.mp3"/>
</paths>
```

Have I missed something? 
I don't see any documentation on the Azuracast site for adding aliases and many searches through various forums hasn't surfaced anything either.

Perhaps I'm making a mistake in creating the alias.  I know that it's unreasonable to ask for a UI component covering every possible feature of Icecast2. The custom config is likely there so that you don't need to do this.  So, am I doing something wrong, or is this something that needs to be explicitly supported by Azuracast? 

I really appreciate the work that you have done on this.  May I also say that your UI is perfectly accessible to blind screen reader users such as myself. I'm continually impressed.

**Comment by SlvrEagle23** [comment]
@digitaldarragh Thank you for the report. I was able to verify locally that the "alias" custom configuration wasn't overwriteable with the current custom configuration implementation.

The latest Rolling Release version (currently being deployed, and will be available in a few minutes) fixes this issue.

One caveat with aliases: since there's an existing alias, if you want to keep that alias there you have to add it in the custom code, otherwise it'll be replaced.

Your intended alias configuration would thus look like this below:

```json
{ 
  "paths": {
    "alias": [
      { "@source": "/", "@dest": "/status.xsl" },
      { "@source": "/live", "@dest": "/live.mp3" },
      { "@source": "/live.m3u", "@dest": "/live.mp3" }
    ]
  }
}
```

**Comment by digitaldarragh** [comment]
@SlvrEagle23  thanks for that.  
I have updated and replaced the custom config with that provided. 

I encounter an error when restarting the station: 
`Laminas\Config\Exception\RuntimeException at /var/azuracast/www/src/Xml/Writer.php L98: Mixing of string and numeric keys is not allowed`

Again, I'm not beyond anticipating that this could be something that I'm doing wrong. I have looked through various sources and see that this has been encountered once or twice.  It seems to normally be user error.

**Comment by SlvrEagle23** [comment]
@digitaldarragh Are you on the "Stable" release channel? The updates are being pushed to the "Rolling Release" channel; you may need to [switch release channels](https://docs.azuracast.com/en/getting-started/updates/release-channels) to get the updated code.

**Comment by digitaldarragh** [comment]
@SlvrEagle23  Fantastic.  I have updated and now all works as expected. 

I really appreciate your quick replies to this. Thanks again.
