### ISSUE TITLE
Problems update

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#4126]
I'm trying to update an old azuracast version to the last one and when it comes to the part of
! [NOTE] Running in update mode.

Running database migrations
---------------------------------------

It gives the error below and does not update, how can I fix it?

[2021-05-05T05:09:24.171547+00:00] AzuraCast.ERROR: TypeError: mb_substr(): Argument #1 ($string) must be of type string, int given (uncaught exception) at /var/azuracast/www/src/Entity/Migration/Version20210419043231.php line 129 while running console command `azuracast:setup` {"exception":"[object] (TypeError(code: 0): mb_substr(): Argument #1 ($string) must be of type string, int given at /var/azuracast/www/src/Entity/Migration/Version20210419043231.php:129)"} []
[2021-05-05T05:09:24.173986+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 1. [] []
[05-May-2021 05:09:24 UTC] PHP Fatal error:  Uncaught TypeError: mb_substr(): Argument #1 ($string) must be of type string, int given in /var/azuracast/www/src/Entity/Migration/Version20210419043231.php:129
Stack trace:
#0 /var/azuracast/www/src/Entity/Migration/Version20210419043231.php(129): mb_substr()
#1 /var/azuracast/www/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php(157): App\Entity\Migration\Version20210419043231->preUp()
#2 /var/azuracast/www/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php(102): Doctrine\Migrations\Version\DbalExecutor->executeMigration()
#3 /var/azuracast/www/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php(101): Doctrine\Migrations\Version\DbalExecutor->execute()
#4 /var/azuracast/www/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php(74): Doctrine\Migrations\DbalMigrator->executePlan()
#5 /var/azuracast/www/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php(151): Doctrine\Migrations\DbalMigrator->executeMigrations()
#6 /var/azuracast/www/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php(207): Doctrine\Migrations\DbalMigrator->migrate()
#7 /var/azuracast/www/vendor/symfony/console/Command/Command.php(256): Doctrine\Migrations\Tools\Console\Command\MigrateCommand->execute()
#8 /var/azuracast/www/src/Console/Command/CommandAbstract.php(30): Symfony\Component\Console\Command\Command->run()
#9 /var/azuracast/www/src/Console/Command/SetupCommand.php(52): App\Console\Command\CommandAbstract->runCommand()
#10 [internal function]: App\Console\Command\SetupCommand->__invoke()
#11 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()
#12 /var/azuracast/www/vendor/mnapoli/silly/src/Application.php(95): Invoker\Invoker->call()
#13 /var/azuracast/www/vendor/symfony/console/Command/Command.php(254): Silly\Application->Silly\{closure}()
#14 /var/azuracast/www/vendor/symfony/console/Application.php(989): Symfony\Component\Console\Command\Command->run()
#15 /var/azuracast/www/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#16 /var/azuracast/www/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#17 /var/azuracast/www/bin/console(14): Symfony\Component\Console\Application->run()
#18 {main}
  thrown in /var/azuracast/www/src/Entity/Migration/Version20210419043231.php on line 129

Fatal error: Uncaught TypeError: mb_substr(): Argument #1 ($string) must be of type string, int given in /var/azuracast/www/src/Entity/Migration/Version20210419043231.php on line 129

TypeError: mb_substr(): Argument #1 ($string) must be of type string, int given in /var/azuracast/www/src/Entity/Migration/Version20210419043231.php on line 129

Call Stack:
    0.0005     391312   1. {main}() /var/azuracast/www/bin/console:0
    0.4824   18283456   2. App\Console\Application->run($input = ???, $output = ???) /var/azuracast/www/bin/console:14
    0.4997   18587448   3. App\Console\Application->doRun($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'azuracast:setup', 1 => '--update', 2 => '--update']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = ['update' => TRUE]; protected $arguments = ['command' => 'azuracast:setup']; protected $interactive = TRUE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(604) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private $consoleSectionOutputs = []; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(596) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = TRUE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/azuracast/www/vendor/symfony/console/Application.php:166
    0.5007   18606744   4. App\Console\Application->doRunCommand($command = class Silly\Command\Command { private ${Symfony\Component\Console\Command\Command}application = class App\Console\Application { private ${Silly\Application}expressionParser = class Silly\Command\ExpressionParser { ... }; private ${Silly\Application}invoker = class Invoker\Invoker { ... }; private ${Silly\Application}container = class CompiledContainer { ... }; private ${Symfony\Component\Console\Application}commands = [...]; private ${Symfony\Component\Console\Application}wantHelps = FALSE; private ${Symfony\Component\Console\Application}runningCommand = ...; private ${Symfony\Component\Console\Application}name = 'AzuraCast Command Line Tools (production)'; private ${Symfony\Component\Console\Application}version = '0.12.4'; private ${Symfony\Component\Console\Application}commandLoader = NULL; private ${Symfony\Component\Console\Application}catchExceptions = TRUE; private ${Symfony\Component\Console\Application}autoExit = TRUE; private ${Symfony\Component\Console\Application}definition = class Symfony\Component\Console\Input\InputDefinition { ... }; private ${Symfony\Component\Console\Application}helperSet = class Symfony\Component\Console\Helper\HelperSet { ... }; private ${Symfony\Component\Console\Application}dispatcher = class App\EventDispatcher { ... }; private ${Symfony\Component\Console\Application}terminal = class Symfony\Component\Console\Terminal { ... }; private ${Symfony\Component\Console\Application}defaultCommand = 'list'; private ${Symfony\Component\Console\Application}singleCommand = FALSE; private ${Symfony\Component\Console\Application}initialized = TRUE; private ${Symfony\Component\Console\Application}signalRegistry = class Symfony\Component\Console\SignalRegistry\SignalRegistry { ... }; private ${Symfony\Component\Console\Application}signalsToDispatchEvent = [...] }; private ${Symfony\Component\Console\Command\Command}name = 'azuracast:setup'; private ${Symfony\Component\Console\Command\Command}processTitle = NULL; private ${Symfony\Component\Console\Command\Command}aliases = []; private ${Symfony\Component\Console\Command\Command}definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 0; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = [...]; private $shortcuts = [...] }; private ${Symfony\Component\Console\Command\Command}hidden = FALSE; private ${Symfony\Component\Console\Command\Command}help = ''; private ${Symfony\Component\Console\Command\Command}description = 'Execute todas as etapas de configuração geral do AzuraCast.'; private ${Symfony\Component\Console\Command\Command}fullDefinition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = [...]; private $shortcuts = [...] }; private ${Symfony\Component\Console\Command\Command}ignoreValidationErrors = FALSE; private ${Symfony\Component\Console\Command\Command}code = class Closure { public $static = [...]; public $this = class App\Console\Application { ... }; public $parameter = [...] }; private ${Symfony\Component\Console\Command\Command}synopsis = []; private ${Symfony\Component\Console\Command\Command}usages = []; private ${Symfony\Component\Console\Command\Command}helperSet = class Symfony\Component\Console\Helper\HelperSet { private $helpers = [...]; private $command = NULL } }, $input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'azuracast:setup', 1 => '--update', 2 => '--update']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = ['update' => TRUE]; protected $arguments = ['command' => 'azuracast:setup']; protected $interactive = TRUE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(604) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private $consoleSectionOutputs = []; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(596) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = TRUE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/azuracast/www/vendor/symfony/console/Application.php:290

[2021-05-05T05:09:24.174960+00:00] AzuraCast.CRITICAL: Fatal error: Uncaught TypeError: mb_substr(): Argument #1 ($string) must be of type string, int given in /var/azuracast/www/src/Entity/Migration/Version20210419043231.php:129 Stack trace: #0 /var/azuracast/www/src/Entity/Migration/Version20210419043231.php(129): mb_substr() #1 /var/azuracast/www/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php(157): App\Entity\Migration\Version20210419043231->preUp() #2 /var/azuracast/www/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php(102): Doctrine\Migrations\Version\DbalExecutor->executeMigration() #3 /var/azuracast/www/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php(101): Doctrine\Migrations\Version\DbalExecutor->execute() #4 /var/azuracast/www/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php(74): Doctrine\Migrations\DbalMigrator->executePlan() #5 /var/azuracast/www/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php(151): Doctrine\Migrations\DbalMigrator->executeMigrations() #6 /var/azuracast/www/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php(207): Doctrine\Migrations\DbalMigrator->migrate() #7 /var/azuracast/www/vendor/symfony/console/Command/Command.php(256): Doctrine\Migrations\Tools\Console\Command\MigrateCommand->execute() #8 /var/azuracast/www/src/Console/Command/CommandAbstract.php(30): Symfony\Component\Console\Command\Command->run() #9 /var/azuracast/www/src/Console/Command/SetupCommand.php(52): App\Console\Command\CommandAbstract->runCommand() #10 [internal function]: App\Console\Command\SetupCommand->__invoke() #11 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array() #12 /var/azuracast/www/vendor/mnapoli/silly/src/Application.php(95): Invoker\Invoker->call() #13 /var/azuracast/www/vendor/symfony/console/Command/Command.php(254): Silly\Application->Silly\{closure}() #14 /var/azuracast/www/vendor/symfony/console/Application.php(989): Symfony\Component\Console\Command\Command->run() #15 /var/azuracast/www/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand() #16 /var/azuracast/www/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun() #17 /var/azuracast/www/bin/console(14): Symfony\Component\Console\Application->run() #18 {main}   thrown in /var/azuracast/www/src/Entity/Migration/Version20210419043231.php on line 129 [] []
azuracast_mariadb is up-to-date
azuracast_stations is up-to-date
azuracast_redis is up-to-date
Creating azuracast_web ... done
Creating nginx_proxy   ... done
Creating nginx_proxy_letsencrypt ... done

**Comment by Marcioghiraldelli** [comment]
I tried to run the command:
php bin / console migrations: migrate current + 1

And even then it gave error below


Call Stack:
    0.0004     392776   1. {main}() /var/azuracast/www/bin/console:0
    0.2485   16108768   2. App\Console\Application->run($input = ???, $output = ???) /var/azuracast/www/bin/console:14
    0.2615   16412792   3. App\Console\Application->doRun($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'migrations:migrate', 1 => 'current+1']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = TRUE; private $options = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = ['command' => 'migrations:migrate', 'version' => 'current+1']; protected $interactive = TRUE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(547) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private $consoleSectionOutputs = []; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(539) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = TRUE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/azuracast/www/vendor/symfony/console/Application.php:166
    0.2624   16431712   4. App\Console\Application->doRunCommand($command = class Doctrine\Migrations\Tools\Console\Command\MigrateCommand { private ${Doctrine\Migrations\Tools\Console\Command\DoctrineCommand}dependencyFactory = class Doctrine\Migrations\DependencyFactory { private $inResolution = [...]; private $configuration = class Doctrine\Migrations\Configuration\Configuration { ... }; private $dependencies = [...]; private $connection = class Doctrine\DBAL\Connection { ... }; private $em = class App\Doctrine\DecoratedEntityManager { ... }; private $frozen = TRUE; private $configurationLoader = class Doctrine\Migrations\Configuration\Migration\ConfigurationArray { ... }; private $connectionLoader = NULL; private $emLoader = class Doctrine\Migrations\Configuration\EntityManager\ExistingEntityManager { ... }; private $factories = [...] }; protected $io = class Symfony\Component\Console\Style\SymfonyStyle { private $input = class Symfony\Component\Console\Input\ArgvInput { ... }; private $questionHelper = class Symfony\Component\Console\Helper\SymfonyQuestionHelper { ... }; private $progressBar = NULL; private $lineLength = 120; private $bufferedOutput = class Symfony\Component\Console\Output\TrimmedBufferOutput { ... }; private ${Symfony\Component\Console\Style\OutputStyle}output = class Symfony\Component\Console\Output\ConsoleOutput { ... } }; private ${Symfony\Component\Console\Command\Command}application = class App\Console\Application { private ${Silly\Application}expressionParser = class Silly\Command\ExpressionParser { ... }; private ${Silly\Application}invoker = class Invoker\Invoker { ... }; private ${Silly\Application}container = class CompiledContainer { ... }; private ${Symfony\Component\Console\Application}commands = [...]; private ${Symfony\Component\Console\Application}wantHelps = FALSE; private ${Symfony\Component\Console\Application}runningCommand = ...; private ${Symfony\Component\Console\Application}name = 'AzuraCast Command Line Tools (production)'; private ${Symfony\Component\Console\Application}version = '0.12.4'; private ${Symfony\Component\Console\Application}commandLoader = NULL; private ${Symfony\Component\Console\Application}catchExceptions = TRUE; private ${Symfony\Component\Console\Application}autoExit = TRUE; private ${Symfony\Component\Console\Application}definition = class Symfony\Component\Console\Input\InputDefinition { ... }; private ${Symfony\Component\Console\Application}helperSet = class Symfony\Component\Console\Helper\HelperSet { ... }; private ${Symfony\Component\Console\Application}dispatcher = class App\EventDispatcher { ... }; private ${Symfony\Component\Console\Application}terminal = class Symfony\Component\Console\Terminal { ... }; private ${Symfony\Component\Console\Application}defaultCommand = 'list'; private ${Symfony\Component\Console\Application}singleCommand = FALSE; private ${Symfony\Component\Console\Application}initialized = TRUE; private ${Symfony\Component\Console\Application}signalRegistry = class Symfony\Component\Console\SignalRegistry\SignalRegistry { ... }; private ${Symfony\Component\Console\Application}signalsToDispatchEvent = [...] }; private ${Symfony\Component\Console\Command\Command}name = 'migrations:migrate'; private ${Symfony\Component\Console\Command\Command}processTitle = NULL; private ${Symfony\Component\Console\Command\Command}aliases = [0 => 'migrate']; private ${Symfony\Component\Console\Command\Command}definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 0; private $hasAnArrayArgument = FALSE; private $hasOptional = TRUE; private $options = [...]; private $shortcuts = [...] }; private ${Symfony\Component\Console\Command\Command}hidden = FALSE; private ${Symfony\Component\Console\Command\Command}help = 'The <info>%command.name%</info> command executes a migration to a specified version or the latest available version:\n\n    <info>%command.full_name%</info>\n\nYou can show more information about the process by increasing the verbosity level. To see the\nexecuted queries, set the level to debug with <comment>-vv</comment>:\n\n    <info>%command.full_name% -vv</info>\n\nYou can optionally manually specify the version you wish to migrate to:\n\n    <info>%command.full_name% FQCN</info>\n\nYou can specify the '; private ${Symfony\Component\Console\Command\Command}description = 'Execute a migration to a specified version or the latest available version.'; private ${Symfony\Component\Console\Command\Command}fullDefinition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = TRUE; private $options = [...]; private $shortcuts = [...] }; private ${Symfony\Component\Console\Command\Command}ignoreValidationErrors = FALSE; private ${Symfony\Component\Console\Command\Command}code = NULL; private ${Symfony\Component\Console\Command\Command}synopsis = []; private ${Symfony\Component\Console\Command\Command}usages = []; private ${Symfony\Component\Console\Command\Command}helperSet = class Symfony\Component\Console\Helper\HelperSet { private $helpers = [...]; private $command = NULL } }, $input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'migrations:migrate', 1 => 'current+1']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = TRUE; private $options = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = ['command' => 'migrations:migrate', 'version' => 'current+1']; protected $interactive = TRUE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(547) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private $consoleSectionOutputs = []; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(539) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = TRUE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/azuracast/www/vendor/symfony/console/Application.php:290

[2021-05-05T05:25:07.676947+00:00] AzuraCast.CRITICAL: Fatal error: Uncaught TypeError: mb_substr(): Argument #1 ($string) must be of type string, int given in /var/azuracast/www/src/Entity/Migration/Version20210419043231.php:129 Stack trace: #0 /var/azuracast/www/src/Entity/Migration/Version20210419043231.php(129): mb_substr() #1 /var/azuracast/www/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php(157): App\Entity\Migration\Version20210419043231->preUp() #2 /var/azuracast/www/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php(102): Doctrine\Migrations\Version\DbalExecutor->executeMigration() #3 /var/azuracast/www/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php(101): Doctrine\Migrations\Version\DbalExecutor->execute() #4 /var/azuracast/www/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php(74): Doctrine\Migrations\DbalMigrator->executePlan() #5 /var/azuracast/www/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php(151): Doctrine\Migrations\DbalMigrator->executeMigrations() #6 /var/azuracast/www/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php(207): Doctrine\Migrations\DbalMigrator->migrate() #7 /var/azuracast/www/vendor/symfony/console/Command/Command.php(256): Doctrine\Migrations\Tools\Console\Command\MigrateCommand->execute() #8 /var/azuracast/www/vendor/symfony/console/Application.php(989): Symfony\Component\Console\Command\Command->run() #9 /var/azuracast/www/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand() #10 /var/azuracast/www/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun() #11 /var/azuracast/www/bin/console(14): Symfony\Component\Console\Application->run() #12 {main}   thrown in /var/azuracast/www/src/Entity/Migration/Version20210419043231.php on line 129 [] []

**Comment by SC2Mitch** [comment]
Can you confirm the last commit has since resolved this issue @Marcioghiraldelli

**Comment by Marcioghiraldelli** [comment]
Thank you very much, it solved my problem!
