### ISSUE TITLE
AzuraCast docker not starting anymore after update

### ISSUE THREAD

**Issue by taiBsu** [AzuraCast/AzuraCast#4128]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.12.3

**Host Operating System**
Xubuntu 20.04

**Describe the bug**
After updating my Azuracast docker environment, I wasn't able to start it anymore. I keep getting this error message over and over again:
```
web_1                      | [2021-05-05T18:31:23.563798+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":null,"workerName":"app_worker_0"} []
web_1                      | [2021-05-05T18:31:23.584681+00:00] AzuraCast.ERROR: Message queue error: An exception occurred while executing 'SELECT m.* FROM messenger_messages m WHERE (m.delivered_at is null OR m.delivered_at < ?) AND (m.available_at <= ?) AND (m.queue_name = ?) ORDER BY available_at ASC LIMIT 1 FOR UPDATE' with params ["2021-05-05 17:31:23", "2021-05-05 18:31:23", "high_priority"]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.messenger_messages' doesn't exist {"workerName":"app_worker_0","exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): An exception occurred while executing 'SELECT m.* FROM messenger_messages m WHERE (m.delivered_at is null OR m.delivered_at < ?) AND (m.available_at <= ?) AND (m.queue_name = ?) ORDER BY available_at ASC LIMIT 1 FOR UPDATE' with params [\"2021-05-05 17:31:23\", \"2021-05-05 18:31:23\", \"high_priority\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.messenger_messages' doesn't exist at /var/azuracast/www/vendor/symfony/doctrine-messenger/Transport/DoctrineReceiver.php:63)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT m.* FROM messenger_messages m WHERE (m.delivered_at is null OR m.delivered_at < ?) AND (m.available_at <= ?) AND (m.queue_name = ?) ORDER BY available_at ASC LIMIT 1 FOR UPDATE' with params [\"2021-05-05 17:31:23\", \"2021-05-05 18:31:23\", \"high_priority\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.messenger_messages' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:61)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.messenger_messages' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.messenger_messages' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:112)"} []
web_1                      | [2021-05-05T18:31:23.585500+00:00] AzuraCast.WARNING: Console command `queue:process` exited with error code 1. [] []
```

Opening the dashboard just gives me this screen:
![image](https://user-images.githubusercontent.com/8024663/117191781-40b85080-ade1-11eb-975a-087deffc580d.png)

**To Reproduce**
1. shutdown azuracast 0.11.2
2. `./docker.sh update-self`
3. `./docker.sh update`
4. `docker-compose up -d`

**Expected behavior**
After a successful update (I get the `Update complete!` message) everything should work as expected before.

**Relevant Logs**
Provided above.

**Screenshots**
Provided above.

Additionally, there's a warning just before the above error message:
![image](https://user-images.githubusercontent.com/8024663/117192148-ad334f80-ade1-11eb-9062-6d2ae3252aed.png)

**Device(s):**
Browser + Linux Shell

Thanks a lot in advance + keep up the great work.

**Comment by Vaalyn** [comment]
Have you tried re-running the update again?

**Comment by taiBsu** [comment]
@Vaalyn yes I did, a couple of times, same result.

**Comment by Vaalyn** [comment]
Is the error from the screenshot showing while updating or when starting AzuraCast?
(Trying to narrow down what is going wrong exactly)

**Comment by taiBsu** [comment]
Sorry, should've been more specific about that: it's showing what happens after starting AC.

**Comment by Vaalyn** [comment]
Are there (or were there) any errors showing when you ran the update for the first time?

Since the error on the screenshot (the one from the terminal) is saying that it can't find a column in the database it looks like a database migration has failed. When something like that happens you should see an error when the update is running (and I think it should mention which migration exactly it's failing but I'm not 100% sure about that).

**Comment by taiBsu** [comment]
Well it's quite possible that this is the case, however unfortunately (stupid me) I don't have the log from the update anymore. 

**What bugs me a bit** is that AzuraCast automatically tries to run the containers after updating. I made some customizations in the docker-compose.yml (removed some ports from the stations container because they're already in use by other containers) and starting AC fails after the update. That's why I didn't have a closer look at the update log in the first place, sorry.

**Comment by taiBsu** [comment]
Is there a way to retain the update log somehow?

**Comment by Vaalyn** [comment]
> What bugs me a bit is that AzuraCast automatically tries to run the containers after updating ...

Since the containers have to be running in order to execute stuff like DB migrations this is a necessity for updating.

I'm not sure if the output of the migrations are logged but you could try checking the output of `docker-compose logs azuracast_web`. Alternatively if a migration failed the updater should be trying to run it again if you re-run the update command.

**Comment by taiBsu** [comment]
> Alternatively if a migration failed the updater should be trying to run it again if you re-run the update command

Unfortunately that doesn't happen here, since re-running the update multiple times didn't do anything :/
I was not able to find the update log anymore. Is there something like a integrity check for the database?

**Comment by Vaalyn** [comment]
You could run the migration command manually.

Access the web container via `docker exec -it azuracast_web bash` and then run `php bin/console migrations:migrate`.

**Comment by taiBsu** [comment]
Perfect, thanks @Vaalyn, that solved it.

**Comment by SC2Mitch** [comment]
Issue has since been resolved as per OP, tag me directly if there's still issues.
