### ISSUE TITLE
Listener Authentication

### ISSUE THREAD

**Issue by Gaili** [AzuraCast/AzuraCast#413]
Hi,
how and where  can i add a user for the "Listener Authentication", manageauth.xsl is not working. I`m on Ubuntu 16.04 traditional.
Thanks

**Comment by SlvrEagle23** [comment]
@Gaili The listener authentication feature isn't supported out of the box for AzuraCast, and requires manual configuration, so I haven't run into this issue and I can't do much to diagnose it sight unseen.

When you say "not working", do you mean it's returning some sort of error page, or just a 404 in general?

**Comment by SlvrEagle23** [comment]
I haven't heard any follow-up on this issue, so I don't know if the issue has been fixed or if further action is required on my end. If you don't mind, could you please update me on the status of this issue?

If I don't hear any updates for a while, I'll close the issue as resolved.
