### ISSUE TITLE
 AzuraCast Player  PWA / Mobile application 

### ISSUE THREAD

**Issue by oussamatn** [AzuraCast/AzuraCast#4132]
Hello guys,

I'm planning to publish my PWA Player. It fully compatible with AzuraCast  API. 

I have been working on this a years ago, then I forgot about it for a while. ( #1937 )
Well, Today is a new day. The player is available for beta tester. 

Please contact me so I add you to the private repository.
 **[twitter](https://twitter.com/tn_oussama) | [email](mailto:oussama@jelliti.me)**

If everything goes as planned, project will be public in two weeks. 

Here's a short preview : 
[https://player.jelliti.me](https://bit.ly/3uCCNaf)
Screenshots : 

<img src="https://user-images.githubusercontent.com/2962369/117323879-92b7af80-ae8f-11eb-9411-90fe1bc0459a.gif" width="300"><img src="https://user-images.githubusercontent.com/2962369/117322713-8a12a980-ae8e-11eb-8fe1-34106f25fe25.png" width="300"><img src="https://user-images.githubusercontent.com/2962369/117321797-bc6fd700-ae8d-11eb-997c-4f46c67fbbfc.png" width="300">

**Comment by SlvrEagle23** [comment]
@oussamatn Super cool! Thank you for sharing your time and contributing back to the open-source world just like we do. :)

**Comment by ttodua** [comment]
Thanks @oussamatn, i'd like to see that.

**Comment by zloysystem** [comment]
thank you, it's interesting to take a look at the demo version (:

**Comment by oussamatn** [comment]
@SlvrEagle23 I'm working on a plug&play integration with AzuraCast ( Nginx revers proxy & Let's Encrypt )
@ttodua @zloysystem you can have a look at it : [https://player1.jelliti.me](https://player1.jelliti.me)

**Comment by zloysystem** [comment]
@oussamatn unfortunately, this is how my page looks like(
![Screenshot_20210507-012305_Chrome.png](https://user-images.githubusercontent.com/26243386/117372990-1e9efb00-aed3-11eb-913d-ec32c4e7ed7b.png)

**Comment by oussamatn** [comment]
@zloysystem I fixed the issue. It's working now

**Comment by oussamatn** [comment]
Update: 
@SlvrEagle23 I finally got the Player fully integrated into an already existing Azuracast installation.
I'm documenting the installation process. I hope that everything will be available next week.

**Comment by zloysystem** [comment]
@oussamatn Will there be support for choosing the bitrate of the stream?

**Comment by oussamatn** [comment]
@zloysystem  for the first version it takes the dafault stream url from : `station.listen_url`

**Comment by buddhatunes** [comment]
@oussamatn please add me to the private repository

**Comment by oussamatn** [comment]
@buddhatunes : Done !

**Comment by adoboligh1** [comment]
@oussamatn Please add me to the private repository.

**Comment by eranwo** [comment]
@oussamatn Hi, Please add me to the private repository

**Comment by YosefAdPro** [comment]
@oussamatn Please add me to the private repository.

**Comment by SlvrEagle23** [comment]
@oussamatn I would definitely encourage you to open this repository to the public in the spirit of AzuraCast itself, especially if it's in a state where it can readily be tested out and used by other stations.

**Comment by danielrodrigotest** [comment]
Hi, May you add me to the private repo?..Thanks in advanced!!!!

**Comment by brianshano** [comment]
Hi, I'm interested in this... can you add me too?

**Comment by oussamatn** [comment]
Hello everyone , 
 
Projet is public on Github : [https://github.com/oussamatn/radio-player](url)
Documentation is coming soon.

**Comment by oussamatn** [comment]
Hello everyone , 
 
Projet is public on Github : [https://github.com/oussamatn/radio-player](https://github.com/oussamatn/radio-player)
Documentation is coming soon.
