### ISSUE TITLE
Music Files not loading large folder

### ISSUE THREAD

**Issue by bjarn** [AzuraCast/AzuraCast#4134]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #67121c1 (2021-05-06 21:06)

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
Since we updated to the latest rolling release it stopped loading our music folder.

Smaller folders like shows or imaging still loads since those are smaller.

Not sure if that's the reason, but it's the only difference.

**To Reproduce**
1. Have a large folder with music
2. Open the media browser and go to that folder
3. It will load very long, eventually showing "No records to display"

**Expected behavior**
It should load the songs

**Relevant Logs**
[2021-05-07T07:43:21.133381+00:00] AzuraCast.CRITICAL: Fatal error: Maximum execution time of 30 seconds exceeded in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/Type.php on line 235 [] []
[2021-05-07T07:43:32.515289+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data {"force":false} []
[2021-05-07T07:43:47.507817+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data {"force":false} []
[2021-05-07T07:43:55.006774+00:00] AzuraCast.CRITICAL: Fatal error: Maximum execution time of 30 seconds exceeded in /var/azuracast/www/vendor/slim/slim/Slim/Routing/Route.php on line 232 [] []

--

Again, thanks a lot for your work!

**Comment by SC2Mitch** [comment]
Hi, have you extended the maximum execution timer in the `azuracast.env` file? It might help resolve this issue your having. 
```
# PHP's maximum script execution time (in seconds).
# PHP_MAX_EXECUTION_TIME=30
```

**Comment by bjarn** [comment]
> Hi, have you extended the maximum execution timer in the `azuracast.env` file? It might help resolve this issue your having.
> 
> ```
> # PHP's maximum script execution time (in seconds).
> # PHP_MAX_EXECUTION_TIME=30
> ```

Hi! Haven't yet, will try it later today.

It didn't happen before though, however, I was 160 updates behind before I updated today 😅

**Comment by SlvrEagle23** [comment]
@bjarn Are you using an S3 or Dropbox storage location? Those have increased latencies as of our latest software version due to some changes that were made upstream in preparation for our move to PHP 8.0, but the local filesystem adapter should be performing as normal.

**Comment by bjarn** [comment]
@SlvrEagle23 Nope, using the good ol' local driver. It are around 2750 tracks that are listed in that directory.

**Comment by SlvrEagle23** [comment]
@bjarn The latest Rolling Release version offers some significant improvements to listing large directories with the Media Manager, as we discovered several items that were being called with every single row that had pretty high performance loads and were able to optimize those down to just the _displayed_ rows and further optimize performance from there. Try updating and let me know if it improves your experience.

**Comment by bjarn** [comment]
Hi @SlvrEagle23, thanks a lot! I will update Azura later today and will post an update over here :)

**Comment by bjarn** [comment]
Apologies, took a bit longer than expected :)

Update fixed the issue, thanks a lot @SlvrEagle23!
