### ISSUE TITLE
Search for the cover by http

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#4135]
Azuracast version: 0.12.4
OS: Ubuntu 20.04

I recently checked by the browser error log that Azuracast searches for covers by http and several messages appear in the browser log and according to the browser it should be done by https. Below is the message.

"The page at "https://*******" was loaded over HTTPS, but requested an insecure element 'http://coverartarchive.org/release/919bf74d-355c-4ff8-b9b8-dd295cf7ef63/1484124100-500.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html"

**Comment by roger-net** [comment]
I am using a code that connects to Azuracast through the URL "https://azuracastserverurl/api/nowplaying/stationnumber"
But I noticed that on the public page you can also connect to http to get the covers.

**Comment by SlvrEagle23** [comment]
@roger-net After some debugging I discovered that the MusicBrainz API, even when we call it via a HTTPS URL, is returning URLs that are prefixed with `http`, which was what we were relaying through to the end-user via our own API.

They certainly support HTTPS on their album art service, so we fix the response on the way through so this shouldn't be a problem as of the latest Rolling Release.
