### ISSUE TITLE
Webhook telegram returned code 400

### ISSUE THREAD

**Issue by radiopulsar** [AzuraCast/AzuraCast#4136]
**Using Docker installation method**
 Yes

**AzuraCast version**
 Webhook telegram returned code 400

**Host Operating System**
 Ubuntu 20.04 LTS 

**Describe the bug**
 This is what retuns of my webhook fot telegram: "request_url
"https:\/\/api.telegram.org\/bot1803870020:AAHTiJm61H2ZqODpeOX8RzyIeDeVmygY9qU\/sendMessage"
request_params
{
    "chat_id": "@radiopulsarbot",
    "text": "Now playing on Radio Pulsar: BOO by RAQUEL RALHA & PEDRO RENATO - PEEK-A! Tune in now.",
    "parse_mode": "Markdown"
}
response_body
"{\"ok\":false,\"error_code\":400,\"description\":\"Bad Request: chat not found\"}""

What i do wrong? its everything running on Telegram

Thanks

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context**

**Comment by zloysystem** [comment]
I already wrote here about this, but so far I have not been given a solution #4087

**Comment by SlvrEagle23** [comment]
@zloysystem It appears the error you're encountering is different from this one.

**Comment by zloysystem** [comment]
@SlvrEagle23
response_body
"{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}"
