### ISSUE TITLE
Player not working

### ISSUE THREAD

**Issue by AaronUnmuted** [AzuraCast/AzuraCast#4138]
**Using Docker installation method**

Yes

**AzuraCast version**

v0.12.4 Stable

**Host Operating System**

Ubuntu 20.04

**Describe the bug**

The web player on the stations public page is not working. The stream is up & functioning as expected. 
https://clare.shoutca.st/public/radio_stjepan

**To Reproduce**

1. Navigate to https://clare.shoutca.st/public/radio_stjepan and press play. No audio is delivered.
2. Navigate to the direct stream URL of https://clare.shoutca.st/radio/8190/radio.mp3 - audio is delivered as normal. 

**Expected behavior**

Audio should be delivered via the web player without issue. 

**Relevant Logs**

Chrome Console - "Uncaught (in promise) DOMException: Failed to load because no supported source was found."
No further errors.

**Comment by Abqehebter** [comment]
Hey. Your stream URL is here: https://clare.shoutca.st:8000/radio.mp3
Please activate the setting `Use webproxy for the radio` under `Administration > System Settings > Settings > Use webproxy for the radio`
Then it should work.

**Comment by Vaalyn** [comment]
Since you are paying shoutca.st for their hosting they are responsible for handling the support of their customers.
You should contact your reseller for support first so that they can check the installation and try to resolve this issue with you.

From looking at the API response of your station it seems like you have no mount points set up on your station.

**Comment by AaronUnmuted** [comment]
> Hey. Your stream URL is here: https://clare.shoutca.st:8000/radio.mp3
> Please activate the setting `Use webproxy for the radio` under `Administration > System Settings > Settings > Use webproxy for the radio`
> Then it should work.

Thanks - but that option is already enabled. The stream URL you've provided is for an alternative station.



> Since you are paying shoutca.st for their hosting they are responsible for handling the support of their customers.
> You should contact your reseller for support first so that they can check the installation and try to resolve this issue with you.
> 
> From looking at the API response of your station it seems like you have no mount points set up on your station.

I am SHOUTca.st - we're referring this back to yourselves for investigation as we are unable to pinpoint the issue on this particular installation and seemingly no other users have been affected. This station has a singular 320kb/s MP3 mountpoint with Auto DJ enabled, with no additional Liquidsoap configuration. A rather strange issue.

**Comment by Vaalyn** [comment]
@AaronUnmuted Are you sure that the mount point is correctly set up?

If you take a look at the API response for that station here you can see that there are no mount points listed: https://clare.shoutca.st/api/nowplaying/radio_stjepan

If you directly access the IceCast page you can also see that there are no mount points: https://clare.shoutca.st:8190/

**Comment by AaronUnmuted** [comment]
> @AaronUnmuted Are you sure that the mount point is correctly set up?
> 
> If you take a look at the API response for that station here you can see that there are no mount points listed: https://clare.shoutca.st/api/nowplaying/radio_stjepan
> 
> If you directly access the IceCast page you can also see that there are no mount points: https://clare.shoutca.st:8190/

Bingo. You're right - the mountpoint was not correctly setup. "Show on Public Pages" was disabled and therefore obviously not showing and preventing the player from working. Thanks & apologies for user error!
