### ISSUE TITLE
Unable to update installation

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#4140]
Docker install ; I think so
Azura version; 0.10.3.
Serve OS; Ubuntu 20.04
----------------------------
Tried to update Azura installation to version 0.12.4 as suggested in recent notification.

Sudo connected to server via Putty and issued the commands for Docker update supplied on update page. It returned a "No such file or directory" error and, of course wouldn't proceed.
https://zupimages.net/up/21/18/cbpl.jpg

Followed up by accessing the server via Filezilla which shows that the Var/Azuracast directory appears empty!!
https://zupimages.net/up/21/18/92lq.jpg

I am a newbie to the world of servers, so my question is; What's up with that?

(Not so LOL) SpeedyCharly

**Comment by SlvrEagle23** [comment]
@SpeedyCharly That suggests you didn't install AzuraCast in the recommended location when initially installing it.

It's possible you installed it directly in the base directory, at which point just running the `./docker.sh` commands from that directory would work.

Basically, the first command to change directories into `/var/azuracast` can be replaced with wherever you installed AzuraCast on your server.

**Comment by SpeedyCharly** [comment]
I actually inherited that installation from another Joe. I have no idea what he may have done and I no longer have any contact with him... How do I go about finding out where the actual meat of the program is?

**Comment by SpeedyCharly** [comment]
Found 2 instances of Docker folder in server, which so I need to point to?
![FZ1](https://user-images.githubusercontent.com/66107794/117565510-ac1f4e00-b07f-11eb-891a-a13a4bbac5e0.jpg)
![FZ2](https://user-images.githubusercontent.com/66107794/117565512-acb7e480-b07f-11eb-8ebd-f9059631f5db.jpg)

**Comment by SpeedyCharly** [comment]
@Vaalyn - It seems I'm not the only one who hasn't used the issue template - how about making visible and readily accessible?

**Comment by laodikea** [comment]
> I actually inherited that installation from another Joe. I have no idea what he may have done and I no longer have any contact with him... How do I go about finding out where the actual meat of the program is?

I would search if there are "docker.sh" named file somewhere in the server or check .bash_history file to know what commands had been run before.

**Comment by SlvrEagle23** [comment]
> @Vaalyn - It seems I'm not the only one who hasn't used the issue template - how about making visible and readily accessible? Took me a while to find it under BUG REPORT and it seems to me that I had provided all the info relevant to my issue anyways...

In looking into this, we did find out that GitHub still had a way to create a new issue without using our standard issue template; we've updated that this morning so all new GH issues will route through our standard template, which should avoid that confusion in the future.

**Comment by SpeedyCharly** [comment]
> > I actually inherited that installation from another Joe. I have no idea what he may have done and I no longer have any contact with him... How do I go about finding out where the actual meat of the program is?
> 
> I would search if there are "docker.sh" named file somewhere in the server or check .bash_history file to know what commands had been run before.

Found docker.sh in folder /home/ubuntu while looking for bash_history - can I call it from there?

**Comment by laodikea** [comment]
> Found docker.sh in folder /home/ubuntu while looking for bash_history - can I call it from there?

Based on this comment from :

> It's possible you installed it directly in the base directory, at which point just running the `./docker.sh` commands from that directory would work.

I would say that yes, you can call the docker.sh file from there. I think that there should also be azuracast.env file in that same folder.

**Comment by SlvrEagle23** [comment]
@SpeedyCharly That isn't us making assumptions about where your Docker socket is located; that error typically indicates that your user account _can't_ connect to Docker at all, which is usually a permissions issue.

Running the update script with `sudo` may help, or just adding yourself to the Docker group via:

```
usermod -aG docker ubuntu
```

and then logging out/back in should resolve the issue as well.

**Comment by SpeedyCharly** [comment]
DANG IT...  Update concluded successfully using sudo command but can no longer connect to azuracast dashboard - gettig Slim Application error...

**Comment by SlvrEagle23** [comment]
@SpeedyCharly It shouldn't be affecting anything for InfluxDB to still be running (we don't use it any more), but you can indeed run `docker-compose down --remove-orphans` to remove it, then `docker-compose up -d` to restart services.

As for the slim application error, we'd need to see the actual text of that error. Try `docker-compose logs -f web` to see if the web log has anything about it.

**Comment by SpeedyCharly** [comment]
This is what the command returned;

[2021-05-10T09:12:31.584949+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT t0.app_unique_identifier AS app_unique_identifier_1, t0.base_url AS base_url_2, t0.instance_name AS instance_name_3, t0.prefer_browser_url AS prefer_browser_url_4, t0.use_radio_proxy AS use_radio_proxy_5, t0.history_keep_days AS history_keep_days_6, t0.always_use_ssl AS always_use_ssl_7, t0.api_access_control AS api_access_control_8, t0.enable_websockets AS enable_websockets_9, t0.analytics AS analytics_10, t0.check_for_updates AS check_for_updates_11, t0.update_results AS update_results_12, t0.update_last_run AS update_last_run_13, t0.public_theme AS public_theme_14, t0.hide_album_art AS hide_album_art_15, t0.homepage_redirect_url AS homepage_redirect_url_16, t0.default_album_art_url AS default_album_art_url_17, t0.use_external_album_art_when_processing_media AS use_external_album_art_when_processing_media_18, t0.use_external_album_art_in_apis AS use_external_album_art_in_apis_19, t0.last_fm_api_key AS last_fm_api_key_20, t0.hide_product_name AS hide_product_name_21, t0.public_custom_css AS public_custom_css_22, t0.public_custom_js AS public_custom_js_23, t0.internal_custom_css AS internal_custom_css_24, t0.backup_enabled AS backup_enabled_25, t0.backup_time_code AS backup_time_code_26, t0.backup_exclude_media AS backup_exclude_media_27, t0.backup_keep_copies AS backup_keep_copies_28, t0.backup_storage_location AS backup_storage_location_29, t0.backup_last_run AS backup_last_run_30, t0.backup_last_result AS backup_last_result_31, t0.backup_last_output AS backup_last_output_32, t0.setup_complete_time AS setup_complete_time_33, t0.nowplaying AS nowplaying_34, t0.sync_nowplaying_last_run AS sync_nowplaying_last_run_35, t0.sync_short_last_run AS sync_short_last_run_36, t0.sync_medium_last_run AS sync_medium_last_run_37, t0.sync_long_last_run AS sync_long_last_run_38, t0.external_ip AS external_ip_39, t0.geolite_license_key AS geolite_license_key_40, t0.geolite_last_run AS geolite_last_run_41, t0.enable_advanced_features AS enable_advanced_features_42, t0.mail_enabled AS mail_enabled_43, t0.mail_sender_name AS mail_sender_name_44, t0.mail_sender_email AS mail_sender_email_45, t0.mail_smtp_host AS mail_smtp_host_46, t0.mail_smtp_port AS mail_smtp_port_47, t0.mail_smtp_username AS mail_smtp_username_48, t0.mail_smtp_password AS mail_smtp_password_49, t0.mail_smtp_secure AS mail_smtp_secure_50, t0.avatar_service AS avatar_service_51, t0.avatar_default_url AS avatar_default_url_52 FROM settings t0 LIMIT 1':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 61 while running console command `sync:run` {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.app_unique_identifier AS app_unique_identifier_1, t0.base_url AS base_url_2, t0.instance_name AS instance_name_3, t0.prefer_browser_url AS prefer_browser_url_4, t0.use_radio_proxy AS use_radio_proxy_5, t0.history_keep_days AS history_keep_days_6, t0.always_use_ssl AS always_use_ssl_7, t0.api_access_control AS api_access_control_8, t0.enable_websockets AS enable_websockets_9, t0.analytics AS analytics_10, t0.check_for_updates AS check_for_updates_11, t0.update_results AS update_results_12, t0.update_last_run AS update_last_run_13, t0.public_theme AS public_theme_14, t0.hide_album_art AS hide_album_art_15, t0.homepage_redirect_url AS homepage_redirect_url_16, t0.default_album_art_url AS default_album_art_url_17, t0.use_external_album_art_when_processing_media AS use_external_album_art_when_processing_media_18, t0.use_external_album_art_in_apis AS use_external_album_art_in_apis_19, t0.last_fm_api_key AS last_fm_api_key_20, t0.hide_product_name AS hide_product_name_21, t0.public_custom_css AS public_custom_css_22, t0.public_custom_js AS public_custom_js_23, t0.internal_custom_css AS internal_custom_css_24, t0.backup_enabled AS backup_enabled_25, t0.backup_time_code AS backup_time_code_26, t0.backup_exclude_media AS backup_exclude_media_27, t0.backup_keep_copies AS backup_keep_copies_28, t0.backup_storage_location AS backup_storage_location_29, t0.backup_last_run AS backup_last_run_30, t0.backup_last_result AS backup_last_result_31, t0.backup_last_output AS backup_last_output_32, t0.setup_complete_time AS setup_complete_time_33, t0.nowplaying AS nowplaying_34, t0.sync_nowplaying_last_run AS sync_nowplaying_last_run_35, t0.sync_short_last_run AS sync_short_last_run_36, t0.sync_medium_last_run AS sync_medium_last_run_37, t0.sync_long_last_run AS sync_long_last_run_38, t0.external_ip AS external_ip_39, t0.geolite_license_key AS geolite_license_key_40, t0.geolite_last_run AS geolite_last_run_41, t0.enable_advanced_features AS enable_advanced_features_42, t0.mail_enabled AS mail_enabled_43, t0.mail_sender_name AS mail_sender_name_44, t0.mail_sender_email AS mail_sender_email_45, t0.mail_smtp_host AS mail_smtp_host_46, t0.mail_smtp_port AS mail_smtp_port_47, t0.mail_smtp_username AS mail_smtp_username_48, t0.mail_smtp_password AS mail_smtp_password_49, t0.mail_smtp_secure AS mail_smtp_secure_50, t0.avatar_service AS avatar_service_51, t0.avatar_default_url AS avatar_default_url_52 FROM settings t0 LIMIT 1':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:61)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:132)"} []
web_1                      | [2021-05-10T09:12:31.588200+00:00] AzuraCast.WARNING: Console command `sync:run` exited with error code 1. [] []
web_1                      |
web_1                      | In AbstractMySQLDriver.php line 61:
web_1                      |
web_1                      |   An exception occurred while executing 'SELECT t0.app_unique_identifier AS a
web_1                      |   pp_unique_identifier_1, t0.base_url AS base_url_2, t0.instance_name AS inst
web_1                      |   ance_name_3, t0.prefer_browser_url AS prefer_browser_url_4, t0.use_radio_pr
web_1                      |   oxy AS use_radio_proxy_5, t0.history_keep_days AS history_keep_days_6, t0.a
web_1                      |   lways_use_ssl AS always_use_ssl_7, t0.api_access_control AS api_access_cont
web_1                      |   rol_8, t0.enable_websockets AS enable_websockets_9, t0.analytics AS analyti
web_1                      |   cs_10, t0.check_for_updates AS check_for_updates_11, t0.update_results AS u
web_1                      |   pdate_results_12, t0.update_last_run AS update_last_run_13, t0.public_theme
web_1                      |    AS public_theme_14, t0.hide_album_art AS hide_album_art_15, t0.homepage_re
web_1                      |   direct_url AS homepage_redirect_url_16, t0.default_album_art_url AS default
web_1                      |   _album_art_url_17, t0.use_external_album_art_when_processing_media AS use_e
web_1                      |   xternal_album_art_when_processing_media_18, t0.use_external_album_art_in_ap
web_1                      |   is AS use_external_album_art_in_apis_19, t0.last_fm_api_key AS last_fm_api_
web_1                      |   key_20, t0.hide_product_name AS hide_product_name_21, t0.public_custom_css
web_1                      |   AS public_custom_css_22, t0.public_custom_js AS public_custom_js_23, t0.int
web_1                      |   ernal_custom_css AS internal_custom_css_24, t0.backup_enabled AS backup_ena
web_1                      |   bled_25, t0.backup_time_code AS backup_time_code_26, t0.backup_exclude_medi
web_1                      |   a AS backup_exclude_media_27, t0.backup_keep_copies AS backup_keep_copies_2
web_1                      |   8, t0.backup_storage_location AS backup_storage_location_29, t0.backup_last
web_1                      |   _run AS backup_last_run_30, t0.backup_last_result AS backup_last_result_31,
web_1                      |    t0.backup_last_output AS backup_last_output_32, t0.setup_complete_time AS
web_1                      |   setup_complete_time_33, t0.nowplaying AS nowplaying_34, t0.sync_nowplaying_
web_1                      |   last_run AS sync_nowplaying_last_run_35, t0.sync_short_last_run AS sync_sho
web_1                      |   rt_last_run_36, t0.sync_medium_last_run AS sync_medium_last_run_37, t0.sync
web_1                      |   _long_last_run AS sync_long_last_run_38, t0.external_ip AS external_ip_39,
web_1                      |   t0.geolite_license_key AS geolite_license_key_40, t0.geolite_last_run AS ge
web_1                      |   olite_last_run_41, t0.enable_advanced_features AS enable_advanced_features_
web_1                      |   42, t0.mail_enabled AS mail_enabled_43, t0.mail_sender_name AS mail_sender_
web_1                      |   name_44, t0.mail_sender_email AS mail_sender_email_45, t0.mail_smtp_host AS
web_1                      |    mail_smtp_host_46, t0.mail_smtp_port AS mail_smtp_port_47, t0.mail_smtp_us
web_1                      |   ername AS mail_smtp_username_48, t0.mail_smtp_password AS mail_smtp_passwor
web_1                      |   d_49, t0.mail_smtp_secure AS mail_smtp_secure_50, t0.avatar_service AS avat
web_1                      |   ar_service_51, t0.avatar_default_url AS avatar_default_url_52 FROM settings
web_1                      |    t0 LIMIT 1':
web_1                      |
web_1                      |   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin
web_1                      |   gs' doesn't exist
web_1                      |
web_1                      |
web_1                      | In Exception.php line 18:
web_1                      |
web_1                      |   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin
web_1                      |   gs' doesn't exist
web_1                      |
web_1                      |
web_1                      | In PDOConnection.php line 132:
web_1                      |
web_1                      |   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin
web_1                      |   gs' doesn't exist
web_1                      |
web_1                      |
web_1                      | sync:run [--force] [--] [<task>]

**Comment by SlvrEagle23** [comment]
@SpeedyCharly This can sometimes be fixed by running the update again; make sure to update the `docker-compose.yml` file when prompted.

**Comment by SpeedyCharly** [comment]
Shouldn't the yes in the command take care of that?

**Comment by SlvrEagle23** [comment]
@SpeedyCharly It should, unless you have a `docker-compose.override.yml` file that's overriding things, but for whatever reason (we still have yet to figure this out ourselves), some updates don't run database migrations properly and re-updating fixes things.

**Comment by SlvrEagle23** [comment]
@SpeedyCharly You may have multiple instances of the Docker containers running on that installation. Easiest solution is just to stop all containers, and then start up the ones you need:

```bash
docker stop $(docker ps -q)
```

then run the update script again.

**Comment by SpeedyCharly** [comment]
Ubuntu installs Docker by default at setup time I think and Azura installs it again too...

How do I know which to restart and how??? sorry to bother... my first time working with seervers nad not too Unix savvy

**Comment by SlvrEagle23** [comment]
@SpeedyCharly There should not be two running instances of Docker itself on your installation. AzuraCast does ensure the latest version of Docker is installed, yes, but not _in addition to_ the one Ubuntu installs.

Try the commands from the previous post and let me know what results from that. We may be approaching the end of the support we can provide for free for this situation.

**Comment by SpeedyCharly** [comment]
Says I am missing arguments in the stop command

**Comment by SpeedyCharly** [comment]
web_1                      | [2021-05-10T09:52:47.465112+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT t0.app_unique_identifier AS app_unique_identifier_1, t0.base_url AS base_url_2, t0.instance_name AS instance_name_3, t0.prefer_browser_url AS prefer_browser_url_4, t0.use_radio_proxy AS use_radio_proxy_5, t0.history_keep_days AS history_keep_days_6, t0.always_use_ssl AS always_use_ssl_7, t0.api_access_control AS api_access_control_8, t0.enable_websockets AS enable_websockets_9, t0.analytics AS analytics_10, t0.check_for_updates AS check_for_updates_11, t0.update_results AS update_results_12, t0.update_last_run AS update_last_run_13, t0.public_theme AS public_theme_14, t0.hide_album_art AS hide_album_art_15, t0.homepage_redirect_url AS homepage_redirect_url_16, t0.default_album_art_url AS default_album_art_url_17, t0.use_external_album_art_when_processing_media AS use_external_album_art_when_processing_media_18, t0.use_external_album_art_in_apis AS use_external_album_art_in_apis_19, t0.last_fm_api_key AS last_fm_api_key_20, t0.hide_product_name AS hide_product_name_21, t0.public_custom_css AS public_custom_css_22, t0.public_custom_js AS public_custom_js_23, t0.internal_custom_css AS internal_custom_css_24, t0.backup_enabled AS backup_enabled_25, t0.backup_time_code AS backup_time_code_26, t0.backup_exclude_media AS backup_exclude_media_27, t0.backup_keep_copies AS backup_keep_copies_28, t0.backup_storage_location AS backup_storage_location_29, t0.backup_last_run AS backup_last_run_30, t0.backup_last_result AS backup_last_result_31, t0.backup_last_output AS backup_last_output_32, t0.setup_complete_time AS setup_complete_time_33, t0.nowplaying AS nowplaying_34, t0.sync_nowplaying_last_run AS sync_nowplaying_last_run_35, t0.sync_short_last_run AS sync_short_last_run_36, t0.sync_medium_last_run AS sync_medium_last_run_37, t0.sync_long_last_run AS sync_long_last_run_38, t0.external_ip AS external_ip_39, t0.geolite_license_key AS geolite_license_key_40, t0.geolite_last_run AS geolite_last_run_41, t0.enable_advanced_features AS enable_advanced_features_42, t0.mail_enabled AS mail_enabled_43, t0.mail_sender_name AS mail_sender_name_44, t0.mail_sender_email AS mail_sender_email_45, t0.mail_smtp_host AS mail_smtp_host_46, t0.mail_smtp_port AS mail_smtp_port_47, t0.mail_smtp_username AS mail_smtp_username_48, t0.mail_smtp_password AS mail_smtp_password_49, t0.mail_smtp_secure AS mail_smtp_secure_50, t0.avatar_service AS avatar_service_51, t0.avatar_default_url AS avatar_default_url_52 FROM settings t0 LIMIT 1':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 61 while running console command `sync:run` {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.app_unique_identifier AS app_unique_identifier_1, t0.base_url AS base_url_2, t0.instance_name AS instance_name_3, t0.prefer_browser_url AS prefer_browser_url_4, t0.use_radio_proxy AS use_radio_proxy_5, t0.history_keep_days AS history_keep_days_6, t0.always_use_ssl AS always_use_ssl_7, t0.api_access_control AS api_access_control_8, t0.enable_websockets AS enable_websockets_9, t0.analytics AS analytics_10, t0.check_for_updates AS check_for_updates_11, t0.update_results AS update_results_12, t0.update_last_run AS update_last_run_13, t0.public_theme AS public_theme_14, t0.hide_album_art AS hide_album_art_15, t0.homepage_redirect_url AS homepage_redirect_url_16, t0.default_album_art_url AS default_album_art_url_17, t0.use_external_album_art_when_processing_media AS use_external_album_art_when_processing_media_18, t0.use_external_album_art_in_apis AS use_external_album_art_in_apis_19, t0.last_fm_api_key AS last_fm_api_key_20, t0.hide_product_name AS hide_product_name_21, t0.public_custom_css AS public_custom_css_22, t0.public_custom_js AS public_custom_js_23, t0.internal_custom_css AS internal_custom_css_24, t0.backup_enabled AS backup_enabled_25, t0.backup_time_code AS backup_time_code_26, t0.backup_exclude_media AS backup_exclude_media_27, t0.backup_keep_copies AS backup_keep_copies_28, t0.backup_storage_location AS backup_storage_location_29, t0.backup_last_run AS backup_last_run_30, t0.backup_last_result AS backup_last_result_31, t0.backup_last_output AS backup_last_output_32, t0.setup_complete_time AS setup_complete_time_33, t0.nowplaying AS nowplaying_34, t0.sync_nowplaying_last_run AS sync_nowplaying_last_run_35, t0.sync_short_last_run AS sync_short_last_run_36, t0.sync_medium_last_run AS sync_medium_last_run_37, t0.sync_long_last_run AS sync_long_last_run_38, t0.external_ip AS external_ip_39, t0.geolite_license_key AS geolite_license_key_40, t0.geolite_last_run AS geolite_last_run_41, t0.enable_advanced_features AS enable_advanced_features_42, t0.mail_enabled AS mail_enabled_43, t0.mail_sender_name AS mail_sender_name_44, t0.mail_sender_email AS mail_sender_email_45, t0.mail_smtp_host AS mail_smtp_host_46, t0.mail_smtp_port AS mail_smtp_port_47, t0.mail_smtp_username AS mail_smtp_username_48, t0.mail_smtp_password AS mail_smtp_password_49, t0.mail_smtp_secure AS mail_smtp_secure_50, t0.avatar_service AS avatar_service_51, t0.avatar_default_url AS avatar_default_url_52 FROM settings t0 LIMIT 1':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:61)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:132)"} []
web_1                      | [2021-05-10T09:52:47.467421+00:00] AzuraCast.WARNING: Console command `sync:run` exited with error code 1. [] []
web_1                      |
web_1                      | In AbstractMySQLDriver.php line 61:
web_1                      |
web_1                      |   An exception occurred while executing 'SELECT t0.app_unique_identifier AS a
web_1                      |   pp_unique_identifier_1, t0.base_url AS base_url_2, t0.instance_name AS inst
web_1                      |   ance_name_3, t0.prefer_browser_url AS prefer_browser_url_4, t0.use_radio_pr
web_1                      |   oxy AS use_radio_proxy_5, t0.history_keep_days AS history_keep_days_6, t0.a
web_1                      |   lways_use_ssl AS always_use_ssl_7, t0.api_access_control AS api_access_cont
web_1                      |   rol_8, t0.enable_websockets AS enable_websockets_9, t0.analytics AS analyti
web_1                      |   cs_10, t0.check_for_updates AS check_for_updates_11, t0.update_results AS u
web_1                      |   pdate_results_12, t0.update_last_run AS update_last_run_13, t0.public_theme
web_1                      |    AS public_theme_14, t0.hide_album_art AS hide_album_art_15, t0.homepage_re
web_1                      |   direct_url AS homepage_redirect_url_16, t0.default_album_art_url AS default
web_1                      |   _album_art_url_17, t0.use_external_album_art_when_processing_media AS use_e
web_1                      |   xternal_album_art_when_processing_media_18, t0.use_external_album_art_in_ap
web_1                      |   is AS use_external_album_art_in_apis_19, t0.last_fm_api_key AS last_fm_api_
web_1                      |   key_20, t0.hide_product_name AS hide_product_name_21, t0.public_custom_css
web_1                      |   AS public_custom_css_22, t0.public_custom_js AS public_custom_js_23, t0.int
web_1                      |   ernal_custom_css AS internal_custom_css_24, t0.backup_enabled AS backup_ena
web_1                      |   bled_25, t0.backup_time_code AS backup_time_code_26, t0.backup_exclude_medi
web_1                      |   a AS backup_exclude_media_27, t0.backup_keep_copies AS backup_keep_copies_2
web_1                      |   8, t0.backup_storage_location AS backup_storage_location_29, t0.backup_last
web_1                      |   _run AS backup_last_run_30, t0.backup_last_result AS backup_last_result_31,
web_1                      |    t0.backup_last_output AS backup_last_output_32, t0.setup_complete_time AS
web_1                      |   setup_complete_time_33, t0.nowplaying AS nowplaying_34, t0.sync_nowplaying_
web_1                      |   last_run AS sync_nowplaying_last_run_35, t0.sync_short_last_run AS sync_sho
web_1                      |   rt_last_run_36, t0.sync_medium_last_run AS sync_medium_last_run_37, t0.sync
web_1                      |   _long_last_run AS sync_long_last_run_38, t0.external_ip AS external_ip_39,
web_1                      |   t0.geolite_license_key AS geolite_license_key_40, t0.geolite_last_run AS ge
web_1                      |   olite_last_run_41, t0.enable_advanced_features AS enable_advanced_features_
web_1                      |   42, t0.mail_enabled AS mail_enabled_43, t0.mail_sender_name AS mail_sender_
web_1                      |   name_44, t0.mail_sender_email AS mail_sender_email_45, t0.mail_smtp_host AS
web_1                      |    mail_smtp_host_46, t0.mail_smtp_port AS mail_smtp_port_47, t0.mail_smtp_us
web_1                      |   ername AS mail_smtp_username_48, t0.mail_smtp_password AS mail_smtp_passwor
web_1                      |   d_49, t0.mail_smtp_secure AS mail_smtp_secure_50, t0.avatar_service AS avat
web_1                      |   ar_service_51, t0.avatar_default_url AS avatar_default_url_52 FROM settings
web_1                      |    t0 LIMIT 1':
web_1                      |
web_1                      |   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin
web_1                      |   gs' doesn't exist
web_1                      |
web_1                      |
web_1                      | In Exception.php line 18:
web_1                      |
web_1                      |   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin
web_1                      |   gs' doesn't exist
web_1                      |
web_1                      |
web_1                      | In PDOConnection.php line 132:
web_1                      |
web_1                      |   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settin
web_1                      |   gs' doesn't exist
web_1                      |
web_1                      |
web_1                      | sync:run [--force] [--] [<task>]

**Comment by SpeedyCharly** [comment]
Radio silence????  What can I do to repair my installation????

**Comment by SpeedyCharly** [comment]
Not hostile in any way... not my type - but need a solution... am trying to restore from backup to return to a functional system but haven't yet found path to backup - can I simply upload te local copy I have here and work from that?

If you can offer more support with a reasonable service charge I am willing to consider

**Comment by SlvrEagle23** [comment]
@SpeedyCharly If you like, you can e-mail me at buster@busterneece.com or DM me on Discord via https://discord.gg/azuracast and we can discuss taking a look at your specific installation.
