### ISSUE TITLE
Streamer Broadcasts lists all recordings on each streamer

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#4142]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #f09f5e6 (2021-05-04 17:32)

**Host Operating System**
Ubuntu 20.04 LTS

**Describe the bug**
When viewing the `Streamer Broadcasts` for a specific DJ Account the list shows the recordings / broadcasts of all DJ accounts instead of just the ones associated with this one.

**To Reproduce**

1. Create 2 DJ Accounts
2. Enable Recording
3. Connect to stream for some time with both accounts to get recordings for both
4. Look at the `Streamer Broadcasts` of one of the DJ accounts
5. You should now see the recordings of both accounts

**Expected behavior**
The `Streamer Broadcasts` list should only show the recordings of the DJ that you are looking at.

**Relevant Logs**
Since there are no errors, logs should not be relevant to this issue.

**Device(s):**

- Device: MacBook Pro (Retina, 15', Mitte 2014)
- OS: macOS Big Sur 11.2.3 (20D91)
- Browser: Chrome
- Version: 90

**Comment by SlvrEagle23** [comment]
@Vaalyn Figured this one out; the route name for the "view all broadcasts" route was identical to the "view a specific streamer's broadcasts" one. Fixed in latest Rolling.
