### ISSUE TITLE
Backup list unsorted

### ISSUE THREAD

**Issue by ncfernan** [AzuraCast/AzuraCast#4143]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #f32eebb (2021-05-08 10:07) • Docker • PHP 8.0

**Host Operating System**
Ubuntu 20.04 LTS

**Describe the bug**
The backup list is not sorted, so when looking for a specific backup we need to search sequentially.

**To Reproduce**
Just look at the backup list.

**Expected behavior**
A list sorted in inverse chronological order (latest first).

**Relevant Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/10008844/117543345-c95a0b00-aff2-11eb-99dd-10c9bf8e8065.png)

**Device(s):**

- Device: Desktop
- OS: Win10
- Browser: Chrome
- Version: 90.0.4430.93 (Official Build) (64-bit)

**Additional context**

**Comment by SlvrEagle23** [comment]
@ncfernan Fixed in the latest rolling release version.
