### ISSUE TITLE
SFTP messing with files!

### ISSUE THREAD

**Issue by ncfernan** [AzuraCast/AzuraCast#4146]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #f32eebb (2021-05-08 10:07) • Docker • PHP 8.0

**Host Operating System**
Ubuntu 20.04 LTS

**Describe the bug**
The SFTP server is removing the slash from the path and storing all files at root directory.

**To Reproduce**
Follow the screenshots below.

**Expected behavior**
The SFTP server was working fine until the last update.

**Relevant Logs**

**Screenshots**

Filezilla:

![image](https://user-images.githubusercontent.com/10008844/117557603-ffc37480-b04a-11eb-84ea-258b3d3f506e.png)

![image](https://user-images.githubusercontent.com/10008844/117557605-08b44600-b04b-11eb-9fbe-6187f09169cf.png)

![image](https://user-images.githubusercontent.com/10008844/117557607-1073ea80-b04b-11eb-98e1-94d9ea569767.png)

![image](https://user-images.githubusercontent.com/10008844/117557635-8d06c900-b04b-11eb-9426-d6bd3b4cd9e2.png)

![image](https://user-images.githubusercontent.com/10008844/117557616-24b7e780-b04b-11eb-8207-d6c9ca6a06b8.png)

**Device(s):**

- Device: Desktop
- OS: Win10
- Browser: Chrome
- Version: 90.0.4430.93 (Official Build) (64-bit)

**Additional context**

![image](https://user-images.githubusercontent.com/10008844/117557629-60eb4800-b04b-11eb-82f9-c56eea44f7b1.png)

**Comment by SlvrEagle23** [comment]
@ncfernan We already reverted some recent changes to the SFTP file renaming process earlier this evening; if you update, you should notice these issues are resolved.
