### ISSUE TITLE
Same playlist appears several times for the same song - bug or feature?

### ISSUE THREAD

**Issue by ncfernan** [AzuraCast/AzuraCast#4148]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #4789f62 (2021-05-08 19:45) • Docker • PHP 8.0

**Host Operating System**
Ubuntu 20.04 LTS

**Describe the bug**
The playlist name appears several times for some music tracks. See screenshot.

`Important:` the file `really` appears 5 times in that playlist.

**To Reproduce**
Insert the same song more than once in any playlist and then check the music tab.

**Expected behavior**
I don't know if this is a bug or a feature to indicate how many times that song appears in a particular playlist. 

If this is a feature, I guess that showing the playlist name once with or without the number of occurrences of that track would be better.

**Relevant Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/10008844/117558789-9cd7da80-b056-11eb-99a6-2ca5de825f44.png)

![image](https://user-images.githubusercontent.com/10008844/117558799-b24d0480-b056-11eb-98ee-3fed2b6d87da.png)

**Device(s):**

- Device: Desktop
- OS: Win10
- Browser: Chrome
- Version: 90.0.4430.93 (Official Build) (64-bit)

**Additional context**

**Comment by SlvrEagle23** [comment]
@ncfernan With sequential playlists, you can add the same track to a playlist multiple times; this is by design.

This is not something that will happen with either Shuffled or Random playlists, as they don't benefit from having the same track in multiple places along the playback queue.

**Comment by ncfernan** [comment]
@SlvrEagle23 I have my own shuffler, so my playlist is made of 5 shuffled playlists sequentially concatenated. As a sequential playlist, I undertand and agree that each track would appear 5 times.

My question has to do with the number of times the name of the playlist appears next to the track in music tab. It could show something like "default, orquestradas_2021-04-27_shuffled (5)" or simply the name of the playlists with no count. After all, that column is to indicate which playlists contain that track, not necessarily the number of times the track appears in each playlist.
