### ISSUE TITLE
Cannot access playlists via sftp following latest rolling update

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#4153]
**Using Docker installation method?**
 Yes

**AzuraCast version:**
 Rolling Release #fdc1c6a (2021-05-09 19:08)

**Host Operating System:**
 Ubuntu 20.04

**Describe the bug:**

Just updated to latest rolling release and lost sftp access to media folders.  Getting Authentification failed error but haven't changed anything in access codes and p-word.  Flushed and re-did access in Filezilla - no luck | Created second account in Azura - still no luck

**Steps to reproduce:**
N/A

**Expected behavior:**
 N/A

**Relevant logs:**
 N/A

**Screenshots:**

![sftp1](https://user-images.githubusercontent.com/66107794/117663401-a2c0df00-b16e-11eb-81dc-7f96fd96f585.jpg)
![sftp2](https://user-images.githubusercontent.com/66107794/117667451-e3225c00-b172-11eb-9ace-961807d4ec48.jpg)

**Device(s):**

- Device:  Desktop
- OS:  Win 7 Ultimate
- ftp Client:  Filezilla 
- Version:  3.53.1

**Additional context:**
 N/A

**Comment by SC2Mitch** [comment]
i shall take a look at this a bit later today and see if i can replicate this.

**Comment by SC2Mitch** [comment]
Unable to replicate this bug on my local instance, please pull up the docker logs `docker-compose logs -f` and attempt to connect through FTP.
The logs should look like this. 

```
web_1                      | {"level":"info","time":"2021-05-10T14:55:49.908","sender":"SSH","connection_id":"snips","message":"User id: 1, logged in with: \"password\", username: \"test42\", home_dir: \"/var/azuracast/stations/azuracast_test_station/media\" remote addr: \"snips\""}
web_1                      | {"level":"debug","time":"2021-05-10T14:55:49.908","sender":"dataprovider_bolt","message":"last login updated for user \"test42\""}
web_1                      | {"level":"debug","time":"2021-05-10T14:55:49.909","sender":"common","connection_id":"snips","message":"ssh connection added, num open connections: 1"}
web_1                      | {"level":"debug","time":"2021-05-10T14:55:50.001","sender":"SFTP","connection_id":"snips","message":"connection added, num open connections: 1"}
```

**Comment by SpeedyCharly** [comment]
This is what I could see in the specified log;

![sftp3](https://user-images.githubusercontent.com/66107794/117725989-e7bb3480-b1b3-11eb-9855-a87a4b910169.jpg)

**Comment by SlvrEagle23** [comment]
@SpeedyCharly The error there seems pretty self-explanatory; the SFTP username you use (which is created via the `SFTP Users` section, not the same username/password you use to log in to AzuraCast) shouldn't be in the format of an e-mail address; in fact, it shouldn't actually let you create a username there that follows that format for that specific reason.

**Comment by SpeedyCharly** [comment]
But this is what Azura itself is giving me and it worked fine until the update...

**Comment by SpeedyCharly** [comment]
Ok edited my sftp account credentials and now working fine - but at the time I hade created the original it specified that it should be same as Azura login and I created another account this morning using the very same format - no flag at creation - but which didn't work either...
