### ISSUE TITLE
Statistics Error (not shown)

### ISSUE THREAD

**Issue by KoneSV** [AzuraCast/AzuraCast#4154]
I have the same problem in ansible version

https://pasteboard.co/K0w9yTO.png
https://pasteboard.co/K0wairL.png
https://pasteboard.co/K0war8H.png

**Using Docker installation method?**
No

**AzuraCast version:**
v0.12.4 Stable • Ansible • PHP 8.0 

**Host Operating System:**
Ubuntu 16.04

**Describe the bug:**
Statistics are not seen in the ondemand stations, only the stations that have autodj

**Comment by radio-schlauti** [comment]
Note Ansible
Ansible installations are not officially supported; we strongly recommend Docker installations.

Ansible installations are an advanced option for seasoned Linux server administrators. The software we install can conflict with other software installed on your server and cause problems which are difficult to diagnose and support.

We do not provide support if you install AzuraCast on a server through the Ansible method.

Furthermore, Ubuntu 16.04 is also out of date

Aus diesem Grund kann PHP 8.0 nicht funktionieren

**Comment by KoneSV** [comment]
I use the ansible version for the ports Non-standard ports, can non-standard ports be used in Docker?

**Comment by fiercestartx** [comment]
> ~Ubuntu 16.04 is no longer supported by us~, nor is Ansible, I ask for some kind of logs from you, to help us further look into this, but I'm unable to assist you further unless other users are encountering this issue.

I am also encountering this issue with the statistics not being shown on the graph on the main super administrator page and individual station pages too when they are only using relay mount points. My instance is running Ubuntu 18.04.5 and installed with the Ansible method. I understand that only Docker is supported but if someone could provide us with a list of dependencies and version numbers in the Docker deployment, that would be very helpful and we may be able to do the rest ourselves. It would also be useful for confirmation that the Docker version is unaffected by this issue..

**Comment by SlvrEagle23** [comment]
> The first issue I found was that of the three streams, two use ffmpeg source (which I also helped them with) as they have 'live' analogue studios and this means they do not provide any metadata. I quickly realised that Azuracast ignores active streams in this state.

Correct. Without metadata there isn't really much we can associate with on a timeline, and we depend on that "song history" playback timeline for the rest of our statistics to function.

> I worked around this by adding static metadata via the Icecast2 admin page and presto - it worked! However this breaks when the mountpoint restarts, which happens from time to time and I plan to tackle that problem later by modifying the encoder or seeing if I can add non-volatile metadata to the mountpoints.

I think we found the problem!

If you have static metadata, then AzuraCast never detects a change in song; this means it never has an endpoint to create a new "Song History" record; statistics are pulled for all of the "song history" records within a given day, but if your song started a week ago and continues a week into the future (or possibly indefinitely), then basically our statistics system thinks there's nothing playing that day.

The solution to work with AzuraCast is just to change up the metadata once in a while, maybe once an hour or so. While we could internally chop up larger song history records into smaller ones to help alleviate this problem, I'm certain that somewhere out there, there's someone broadcasting 4-day-long tracks that would somehow be very upset about that, so we'd take that with a cautionary approach.

> One interesting observation I have made (possibly worthy of a bug report) is the 'now playing' metadata from the third stream seems to 'bleed' in to the 'top track' etc portion of the stats of the ones that don't, so if the one that sends 'now playing' metadata plays foo.mp3, Azuracast claims that the other two (which don't send now playing info) have also been playing foo.mp3.

That may indeed be a bug and likely warrants making a new issue if you don't mind.

**Comment by KoneSV** [comment]
> 
> I think we found the problem!
> 
> If you have static metadata, then AzuraCast never detects a change in song; this means it never has an endpoint to create a new "Song History" record; statistics are pulled for all of the "song history" records within a given day, but if your song started a week ago and continues a week into the future (or possibly indefinitely), then basically our statistics system thinks there's nothing playing that day.

If that is the detail, that my stations are with live signal without autodj any solution, because since the last update of December this problem occurred here

**Comment by KoneSV** [comment]
> 
> 
> > I think we found the problem!
> > If you have static metadata, then AzuraCast never detects a change in song; this means it never has an endpoint to create a new "Song History" record; statistics are pulled for all of the "song history" records within a given day, but if your song started a week ago and continues a week into the future (or possibly indefinitely), then basically our statistics system thinks there's nothing playing that day.
> 
> If that is the detail, that my stations are with live signal without autodj any solution, because since the last update of December this problem occurred here

...

**Comment by KoneSV** [comment]
I need help because my statistics are zero, and the stations are live, not a playlist, so what is changing the "playing right now"
