### ISSUE TITLE
5 minute sync cronjob takes extreme amount of time to run when dropbox storage location is present 

### ISSUE THREAD

**Issue by doctator81** [AzuraCast/AzuraCast#4159]
**Using Docker installation method?**

Yes

**AzuraCast version:**

 #5271957

**Host Operating System:**

Ubuntu 20.04 LTS

**Describe the bug:**

When a dropbox storage location is present in Azuracast, the 5 minute cronjob will take an extreme amount of time to run when seemingly any amount of media is present in the dropbox. The SYNC_SHORT_EXECUTION_TIME=2200 in the azuracast.env file as tested. Concurrent 5 minute cronjobs will then try to run while the first one is still running, causing them to error out. 

**Steps to reproduce:**

1.) Create a dropbox storage applet as defined in the documentation and set it as an azuracast storage location. Stations can remain on internal storage if present. 

2.) Place any amount of media in the dropbox

3.) Wait for 5 minute sync cronjob to run. After about 30 minutes a notice will appear in Azuracast stating that the 5 minute sync hasn't run in awhile, and this might indicate an error with the installation. Since there is no way of determining whether the previous job completed or not, the only way to guarantee a successful run after that point is to restart azuracast, either via update, or manually. 

**Expected behavior:**

The expected result would have been the 5 minute cronjob running successfully every time, that way dropbox can be set as a storage location for stations. 

**Relevant logs:**

If a cronjob is running when the next 5 minute sync task initiates, the following error will appear when attempting to force the sync task via command line : 

[2021-05-12T00:01:11.985647+00:00] AzuraCast.NOTICE: Running sync task: 5-Minute Sync {"force":true} []
[2021-05-12T00:12:23.845083+00:00] AzuraCast.NOTICE: Failed to define an expiration for the "{resource}" lock, someone else acquired the lock. {"resource":{"Symfony\\Component\\Lock\\Key":"lock_sync_medium"}} []
[2021-05-12T00:12:25.647502+00:00] AzuraCast.NOTICE: Failed to define an expiration for the "{resource}" lock, someone else acquired the lock. {"resource":{"Symfony\\Component\\Lock\\Key":"lock_sync_medium"}} []

**Screenshots:**

**Device(s):**

- Device:  Desktop
- OS:  Windows 10 
- Browser:  Firefox
- Version: 89.0b9

**Additional context:**

**Comment by doctator81** [comment]
As requested : with all files present in dropbox, the total size is about 103GB

**Comment by SlvrEagle23** [comment]
@doctator81 I found a very large potential cause of this when fixing #4212 -- If you update to the latest Rolling Release version, the performance on this should be _vastly_ improved.

**Comment by doctator81** [comment]
Wow, sync time went down to like 60 seconds vs like 5 to 10 minutes for the same size dropbox. Awesome!

**Comment by SlvrEagle23** [comment]
Good to hear!
