### ISSUE TITLE
Best performing Songs and the worst are the same....

### ISSUE THREAD

**Issue by Jaadoo13** [AzuraCast/AzuraCast#4161]
Hello. 
As i take a look inte best and worst played songs in 48 hours.. i get completly the same list. That could not be possible... ;)

![best_worst](https://user-images.githubusercontent.com/63636492/117982074-ea459780-b335-11eb-88f5-e16895da5102.png)

And Also on the left side the green datas are incorrect. if it goes 5 up from 6 to 11, the the song isnt good... and needs to go on right side...
It should be 11 to 6 instead.

**Comment by SC2Mitch** [comment]
@Jaadoo13 can you check if the latest commit on the rolling branch fixed this?

**Comment by Jaadoo13** [comment]
Sorry there was the actually one at this time. but in the meanwhile there was a new build:  Rolling Release #2f0b109 (2021-05-12 14:31)  and ive updated to it. But still the same..

**Comment by balmasedano** [comment]
Hi! I also have this problem since 0.13.0 stable version on all my stations.

<img width="1033" alt="Captura de pantalla 2021-08-04 a las 0 45 20" src="https://user-images.githubusercontent.com/2371754/128095899-4b026472-a2e4-4f48-9d55-cbe508788873.png">

Thanks!

**Comment by yarik2720** [comment]
Actual for `v0.14.0 Stable`

**Comment by SlvrEagle23** [comment]
It turns out this one was a very silly bug...it was showing "best" on both columns, despite doing the calculations correctly under the hood. Fixed in Rolling Release.
