### ISSUE TITLE
Is there a way to set a Telegram Web Hook to send messages every xx minutes?

### ISSUE THREAD

**Issue by hecgua** [AzuraCast/AzuraCast#4163]
Is there a way to set the Telegram Web Hook to send messages every xx minutes like the Twitter Web Hook does?

**Comment by hecgua** [comment]
No body?

**Comment by SlvrEagle23** [comment]
@hecgua It's not currently possible to do this via our Web Hook system; we only operate based on specific triggers, and the only timing options we provide are to avoid flooding social media services (or other APIs) with data in a short period of time. This may be a good candidate for a [feature request](https://features.azuracast.com/), though.
