### ISSUE TITLE
Multiple hard drives on server

### ISSUE THREAD

**Issue by renatopinto89** [AzuraCast/AzuraCast#4165]
Hey guys

I have a server with 2 drives, one system SSD and a attached 500GB HDD, I install and run AzuraCast just fine on the SSD and everything works as it should, but I can´t find a way to set the media to go to HDD instead, I´m probably missing a setting or something and I´m asking for your help on how to set that up.

Thank you

v0.12.4 Stable • Docker • PHP 8.0 - ubuntu-20.04

**Comment by ncfernan** [comment]
@renatopinto89  I couldn't locate the instructions on how to use another local storage location for media files, I guess they are rewriting them. The old instructions led to more than one interpretation. I took the wrong turn myself, but now it's working like a charm.

(seu nome sugere que você é brasileiro...)

**Comment by renatopinto89** [comment]
@ncfernan (Quase, português haha)

 I searched high and low and couldn't find any instructions and since my server only has 30GB of SSD storage that is a little short. I would really appreciate if you could share what you did to have that working. 

Thank you

**Comment by ncfernan** [comment]
@renatopinto89  mande um e-mail para ncfernan no gmail que eu te explico.

I can guide you, no problem.
