### ISSUE TITLE
New scheduling-style?

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#4169]
**Using Docker installation method?**
Yes

**AzuraCast version:**
Rolling Release #4195386 (2021-05-07 15:24)

**Host Operating System:**
Ubuntu 20.04 LTS

**Describe the bug:**
I don't know myself if this is supposed to be new or unintentional, but it looks unintentional, so I think I'll report it (see screenshot).

The planning view looks kind of strange.

**Screenshots:**
![image](https://user-images.githubusercontent.com/42640247/118270471-6835aa00-b4c0-11eb-817e-e8e9effd5e2b.png)

**Comment by Vaalyn** [comment]
Due to the recent CSS changes for the light/dark themes there is a bug happening here.

The following CSS is overriding the styling of the schedule blocks:

```
@media screen and (prefers-color-scheme: dark) {
    [data-theme=browser] a {
        background-color: transparent;
        color: #2196f3;
    }
}
```

This is the styling that should be applied but is overridden by the one above:

```
.fc-event, .fc-event-dot {
    background-color: #3788d8;
}
```
