### ISSUE TITLE
Add 5 latest request list via nowplaying api

### ISSUE THREAD

**Issue by Protomothis** [AzuraCast/AzuraCast#417]
- **Installation Method:** 
- **Host OS (if using Docker):** 

**Describe the issue in full detail, including screenshots if possible:**

could you add to 5 latest request list via nowplaying api?

I wish get the song_name, song_artist and timestamp fields like this.

  "song_request": [
    {
      "sh_id": foo,
      "date_requested": timestamp,
      "requester_ip": bar,
      "requester_region: yee
      "song": {
        "text": "exam - ple",
        "artist": "exam",
        "title": "ple"
      }
    }
  ]

thank you.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38783/add-api-endpoint-for-most-recent-song-requests
