### ISSUE TITLE
"synchronized task not recently run" warning is persistent after server reboot

### ISSUE THREAD

**Issue by silvaalex2021** [AzuraCast/AzuraCast#4173]
**Using Docker installation method?**
yes

**AzuraCast version:**
Rolling Release #5271957 (2021-05-11 21:16)

**Host Operating System:**
Ubuntu 20.04

**Describe the bug:**
every time i need to reboot the server, my dashboard shows alerts that the synchronized tasks have not run. These alerts will continue to be displayed, no matter how many times I run the tasks manually. the only way to prevent this from happening is to log into the server and manually restart azuracast (docker-compose down && docker-compose up -d). after that, everything goes back to normal.

**Steps to reproduce:**
1. Just reboot the server!

**Relevant logs:**
according to the logs, tasks run normally, although the warning continues to be shown on the dashboard.

**Comment by SC2Mitch** [comment]
investigating

**Comment by SC2Mitch** [comment]
unable to verify this bug, after my server is rebooted the tasks run successfully and the error message is cleared

**Comment by silvaalex2021** [comment]
@SC2Mitch It seems that when the VM is restarted, something does not go well. maybe something is wrong with the VM template.

maybe not related to the issue, but should i say that this instance is running on OpenVZ. I remember reading some warnings that I could run into problems if I ran docker on an OpenVZ vm. Can you confirm that this is still true, even in OpenVZ 7? anyway, i'll  create a Hyper V VM just to test this theory.

**Comment by SC2Mitch** [comment]
Our official stance on the matter is this, it may have some incompatibility issues. 

_OpenVZ or LXC-based Web Hosts:
Some hosting providers use OpenVZ or LXC, and sometimes these technologies are incompatible with Docker. If the Docker installation does not work on your host, you should consider using a different server for AzuraCast, or you can use the unsupported Ansible installation method._

**Comment by silvaalex2021** [comment]
@SC2Mitch as for the type of virtualizer being used, unfortunately there’s not much I can do about it since I’m just the system administrator. What I'm going to do is continue with the measure that I have already taken, which was to include a crontab entry to restart azuracast 5 minutes after the daily reboot.
