### ISSUE TITLE
Analytics broken since update to v0.12.4 Stable

### ISSUE THREAD

**Issue by sezeryilmaz** [AzuraCast/AzuraCast#4174]
**Using Docker installation method?**

Yes
 
**AzuraCast version:**

v0.12.4 Stable

**Host Operating System:**

Ubuntu 20.04

**Describe the bug:**

After updating from previous stable release to current stable release 0.12.4 the calculations for analytics seem to have partially stopped or are wrongly calculated to be zero.

As seen in the screenshots below the numbers for unique listeners are showing but the graph for average listener counts went down to zero. After analysing the analytics table I can say that the numbers are also missing in the database as also seen in the screenshot.

No errors were shown during the update. There seem to be no relevant errors in AzuraCast Logs other than an error regarding missing playlists because of live streaming usage only. Bug could still be related to this. Any help/bugfix would be appreciated.

Additional Finding: 
Total/Sum is missing in Unique Listeners Graph but is available in Average Listeners Graph.
Unsure if this is inteded behaviour. People are also desperately asking for monthly numbers and total listening hours. Will add that to feature requests.

**Steps to reproduce:**

Update to v0.12.4

**Expected behavior:**

**Relevant logs:**

**Screenshots:**

![listeners_graph](https://user-images.githubusercontent.com/4102922/118380542-e4c0a980-b5e2-11eb-9b51-8ca08e27e419.PNG)
![listeners_unique_graph](https://user-images.githubusercontent.com/4102922/118380547-e8543080-b5e2-11eb-92d9-7d3557c20c19.PNG)
![analytics_db](https://user-images.githubusercontent.com/4102922/118380548-ebe7b780-b5e2-11eb-8780-09b0676280c4.PNG)
![azuracast_logs](https://user-images.githubusercontent.com/4102922/118380695-0a9a7e00-b5e4-11eb-85c0-7a01536c7448.PNG)
**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context:**

**Comment by sezeryilmaz** [comment]
Could be related to these changes:
https://github.com/AzuraCast/AzuraCast/commit/ab69db64c07da6d459b6b3c508be9c58e36eb59f#diff-6a4c83ee18b92989a10586223ce09d0418272da7d925573e4a8865dd8c673706

**Comment by SC2Mitch** [comment]
investigating

**Comment by SC2Mitch** [comment]
Alright so, 

On my local development instance which is running the `rolling release` and on my production server, I'm unable to replicate this issue. The only thing I can advise is a update to the rolling release to see if this resolves your issue,

Cheers.

**Comment by sezeryilmaz** [comment]
Hi Mitch,

Thanks for your efforts. I will have to try with the rolling release and see if it solves the problem. I will give you some feedback after monitoring it for a while.

By the way my people are asking me for monthly numbers. I assume it will be wrong to just add up the daily numbers right ? Any idea how I could provide these numbers or any plans to calculate and write these into the table in the future ?

Cheers

**Comment by sezeryilmaz** [comment]
Hi Mitch,

I did the update to current rolling release (2021-05-12 14:31). Cannot see any improvement and average listeners for today is still showing 0 in the graph, but I'm not exactly sure on how you implemented it and if I have to wait a day to see the improvement. 

Best,
Sezer

**Comment by sezeryilmaz** [comment]
Info from another server with exact same config. As seen in the screenshot some stations went to zero but some not.
Additionally unique listener counts seem to go down while average listener counts go up. In the unique listeners view the total sum is missing which is available in the average listeners view. I am updating this in the original bug report. Don't know if this is intended behaviour but seems wrong to me.

**Comment by sezeryilmaz** [comment]
As promised some feedback after updating to rolling release and monitoring for a while. As seen on the screenshots the update didn't help. Unique listener counts are also going down now. Any idea what I can do to solve the problem until the bug is resolved ?

![listeners_graph_20210517](https://user-images.githubusercontent.com/4102922/118462096-a02a3080-b6fe-11eb-8eb8-734d41dc8dc4.PNG)

![listeners_unique_graph_20210517](https://user-images.githubusercontent.com/4102922/118462145-a9b39880-b6fe-11eb-9336-18be9eec4cd6.PNG)

**Comment by SlvrEagle23** [comment]
@sezeryilmaz I suspect this may have something to do with how your stations are configured. I would be curious about:

 - Do you have only local mount points, only remote relays, or a combination of both?
 - When you look at the Song Playback Timeline for these stations, is there at least one entry within about every hour, or is the metadata not updating either? Having no new timeline information can prevent us from accurately pulling listener information.

It's likely that the bug in this case isn't actually with the analytics calculation but "upstream" a bit, with the song history tracking, which you can notice in the actual live numbers coming from a station's metadata (i.e. the Now Playing API).

**Comment by sezeryilmaz** [comment]
@SlvrEagle23 The setup is as follows: 

- Live-Streamers only
- No Playlists / No Auto-DJ
- Local mount points only
- No remote relays used
- Unfortunately just static non changing metadata as suspected (intended since a couple of days)

Since Auto-Dj/Playlists were never used, I also assume the bug is related to static metadata. Can this be solved or do you have any idea for a workaround ? I'm thinking about contributing in regards to analytics, but have to dive into the code when I have some spare time.

**Comment by SlvrEagle23** [comment]
@sezeryilmaz Yeah, it's very likely the static metadata is causing the downstream issues with analytics not loading correctly.

I'm not sure what the eventual solution to this will be, since we depend so much on having reliable metadata to generate a fair amount of our statistics, including the analytics charts.

We'll continue looking into this.

**Comment by sezeryilmaz** [comment]
@SlvrEagle23 Thank you for looking into this. Although song statistics will not work with static metadata it should be a valid use case and at least listener statistics should work I think. Think about news only stations or just some kind of talk show which could be a couple of hours long and results in the same metadata for a long period of time. 

Sometimes because of the static metadata it is also changing the title to offline, but still streaming correctly. I have to restart the stream then, because it irritates listeners and numbers go down. 

Please let me know if I can to any other testing to help with this.

**Comment by sezeryilmaz** [comment]
@SlvrEagle23 After providing some fake dynamic metadata again as a workaround it normalized as expected by you, so it was really the static metadata which was triggering the bug. Good thing is that the missing numbers from before were even calculated afterwards and filled up again..that's nice.

![listeners_graph_20210517_2](https://user-images.githubusercontent.com/4102922/118521492-64618c00-b73b-11eb-86ec-c3813a86f619.PNG)
