### ISSUE TITLE
5 minute sync.....

### ISSUE THREAD

**Issue by tsisma** [AzuraCast/AzuraCast#4175]
**Using Docker installation method?**
 yes

**AzuraCast version:**

Rolling Release #2f0b109 & • v0.12.4 Stable 

**Host Operating System:**

 Ubuntu 20.04
**Describe the bug:**

Synchronized Task Not Recently Run
The "5-Minute Sync" synchronization task has not run recently. This may indicate an error with your installation.

i run manually and it feels to run sometimes. other times i take the message:
An exception occurred while executing 'INSERT INTO messenger_messages (body, headers, queue_name, created_at, available_at) VALUES(?, ?, ?, ?, ?)' with params ["O:36:\\\"Symfony\\\\Component\\\\Messenger\\\\Envelope\\\":2:{s:44:\\\"\\0Symfony\\\\Component\\\\Messenger\\\\Envelope\\0stamps\\\";a:0:{}s:45:\\\"\\0Symfony\\\\Component\\\\Messenger\\\\Envelope\\0message\\\";O:30:\\\"App\\\\Message\\\\RunSyncTaskMessage\\\":2:{s:4:\\\"type\\\";s:6:\\\"medium\\\";s:10:\\\"outputPath\\\";s:32:\\\"\/tmp\/sync_task_medium_p1ULSE.log\\\";}}", "[]", "high_priority", "2021-05-16 09:42:02", "2021-05-16 09:42:02"]: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
DoctrineSender.php : [52]([](url
[Χωρίς τίτλο.zip](https://github.com/AzuraCast/AzuraCast/files/6489011/default.zip)
))

**Steps to reproduce:**

**Expected behavior:**

**Relevant logs:**

**Screenshots:**

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context:**

**Comment by SC2Mitch** [comment]
Despite my many attempts, been unable to replicate this on any of my systems, this still a issue?
