### ISSUE TITLE
Player Dont Working (IceCast Mount)

### ISSUE THREAD

**Issue by ricardomecca** [AzuraCast/AzuraCast#4179]
Hi,

I created new IceCast Radio, the streaming works but the player dont play and error 404 in direct access to listen.

Print of error:
https://image.prntscr.com/image/aNt0uN-DQO2L6sdswQ6nGw.png

**Comment by zloysystem** [comment]
Connection Point URL *
one extra "/"

**Comment by ricardomecca** [comment]
> @ricardomecca
> Connection Point URL *
> one extra "/"

Thanks, problem solved!
