### ISSUE TITLE
Error when installing Azuracast

### ISSUE THREAD

**Issue by wegGehamstert** [AzuraCast/AzuraCast#4188]
I just want to install Azuracast but there is everytime this Error:
I use Debain 10

ERROR: for azuracast_stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (9041f48912da48da14eba9d793205ffd912e3f3f96edcd81cfe59f03a9ec6a20): Error starting userland proxy:

ERROR: for stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (9041f48912da48da14eba9d793205ffd912e3f3f96edcd81cfe59f03a9ec6a20): Error starting userland proxy:

How to fix this?

**Comment by SC2Mitch** [comment]
Have you tried restarting the docker service?

**Comment by wegGehamstert** [comment]
Yes i restarted it. And now it works fine. That was the problem. I got another one. Can i say the problem here or do i need to open a new one?

**Comment by wegGehamstert** [comment]
Is it possible to connect the domain with azuracast so that i can use for example testsite.com/azura

**Comment by wegGehamstert** [comment]
i dont want a ip adress

**Comment by SC2Mitch** [comment]
Then you can add a domain to the website, this can be found in the admin settings.

**Comment by wegGehamstert** [comment]
![image](https://user-images.githubusercontent.com/78315888/119045728-2030ee80-b9bc-11eb-92e9-ee797fadb223.png)
You mean this`?

**Comment by SC2Mitch** [comment]
Yep, make sure you've fully set up your domain and pointed it correctly, there's many guides to sort this kind of stuff out.

This is an example

**Comment by HobbyistKevin** [comment]
I have still got the same problem, what can i do?

**Comment by wegGehamstert** [comment]
I did a full reinstall of Docker and Azuracast. That worked out.
