### ISSUE TITLE
Duration of minutes of all songs

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#419]
You can add in the statistics to the auto DJ, where the total number of songs and playlists is considered, and the continuity of all the songs, so that you can calculate for what time without repetitions there will be a number of songs to play. Thank you very much.

**Comment by SlvrEagle23** [comment]
@susl16c This is just further commentary on the exact same "songs repeating themselves" issue that you posted before as #406. There's no reason for each extra thought you have on the same subject matter to be its own Github issue.

You were already banned from this repository once for excessively abusing my patience and flooding the repository with low-quality, one-sentence issues, and here you are doing it again. Please do better.
