### ISSUE TITLE
wrong metadata on live dj connections

### ISSUE THREAD

**Issue by mariustgv2004** [AzuraCast/AzuraCast#4193]
Hello all. I am using AzuraCast with Docker on Ubuntu 18.04 and I notices a strange behaviour.
As I have multiple DJs connecting to my station, every time one of them connects, the metadata seems to remain stuck for some time (sometimes it's a metter of minutes, but simetimes even hours) with the previous DJ's name. I am using the latest version of azuracast, but the problem it's not new, as I noticed this issue in other previous versions as well. My DJs are connecting through Sam Broadcaster, using a shoutcast connection. I have no other issues regarding the autodj service, just the live connections.
Any help would be much appreciated.
Thanks.

**Comment by SC2Mitch** [comment]
We don't support the shoutcast software natively due to it being proprietary software, thus it not being bundled with our software. 

Can you use the issue template also please.

**Comment by SlvrEagle23** [comment]
@mariustgv2004 This is a known issue with DJ connections; the first metadata sent with the initial connection doesn't trigger a metadata update, so we don't receive it; we only receive the first _update_ to metadata after the DJ connects. This is an upstream issue with our AutoDJ software, Liquidsoap.

A lot of DJs overcome this by running a short sweeper/bumper advertisement as the initial content being streamed, before switching immediately to other content, which triggers the first metadata update and lines everything up.
