### ISSUE TITLE
Keeps stopping and playing AzuraCast Advert

### ISSUE THREAD

**Issue by smoothmixfm** [AzuraCast/AzuraCast#4198]
Here is the log 
021/05/22 21:40:01 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:40:05 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:40:05 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:40:05 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:40:09 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:40:09 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:40:09 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:40:13 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:40:13 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:40:13 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:40:17 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:40:17 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:40:17 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:40:21 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:40:21 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:40:21 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:40:25 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:40:25 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:40:25 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:40:29 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:40:29 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:40:29 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:40:33 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:40:33 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:40:33 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:40:37 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:40:37 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:40:37 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:40:41 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:40:41 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:40:41 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:40:42 [lang:3] AzuraCast Raw Response: annotate:title="Heaven",artist="Kane Brown",duration="175.39",song_id="7fd42ffe0c69d88a9e2d49ca66ab030c",media_id="321",liq_amplify="0.00dB",playlist_id="1":/var/azuracast/stations/smoothmix_fm/media/kane_brown_-_heaven.mp3
2021/05/22 21:40:42 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/smoothmix_fm/media/kane_brown_-_heaven.mp3".
2021/05/22 21:40:45 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:40:45 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:40:45 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:40:49 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:40:49 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:40:49 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:40:53 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:40:53 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:40:53 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:40:57 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:40:57 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:40:57 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:41:01 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:41:01 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:41:01 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:41:05 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:41:05 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:41:05 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:41:09 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:41:09 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:41:09 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:41:13 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:41:13 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:41:13 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:41:17 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:41:17 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:41:17 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:41:21 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:41:21 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:41:21 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:41:21 [ffmpeg:3] [mp3float @ 0x7f63185e1000] Could not update timestamps for discarded samples.
2021/05/22 21:41:21 [next_song:3] Prepared "/var/azuracast/stations/smoothmix_fm/media/kane_brown_-_heaven.mp3" (RID 3).
2021/05/22 21:41:21 [ffmpeg:3] [mp3float @ 0x7f6318a27140] Could not update timestamps for skipped samples.
2021/05/22 21:41:21 [cross_38843:3] Analysis: -103.551763dB / -20.107466dB (2.97s / 2.99s)
2021/05/22 21:41:21 [crossfade:3] new >= old + margin, old <= medium and new <= high.
2021/05/22 21:41:21 [crossfade:3] Do not fade if it's already very low.
2021/05/22 21:41:21 [crossfade:3] Transition: crossed, no fade.
2021/05/22 21:41:22 [lang:3] AzuraCast Feedback Response: OK
2021/05/22 21:41:25 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:41:25 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/05/22 21:41:25 [local_2:3] Will try again in 3.00 sec.
2021/05/22 21:41:29 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/05/22 21:41:29 [local_2:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
``

**Using Docker installation method?**

**AzuraCast version:**

**Host Operating System:**

**Describe the bug:**

**Steps to reproduce:**

**Expected behavior:**

**Relevant logs:**

**Screenshots:**

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context:**

**Comment by SC2Mitch** [comment]
Use the template, it's there for a reason.

**Comment by smoothmixfm** [comment]
it's ok I seemed to have sorted it was a Schedule bug that was causing the issue.
