### ISSUE TITLE
No se escucha en la pagina publica

### ISSUE THREAD

**Issue by DannyDjj-alt** [AzuraCast/AzuraCast#4200]
Buneas tardes por favor con su ayuda doy click en la pagina publica pero no se escucha la musica

**Using Docker installation method?**

**AzuraCast version:**

**Host Operating System:**

**Describe the bug:**

**Steps to reproduce:**

**Expected behavior:**

**Relevant logs:**

**Screenshots:**

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context:**

**Comment by Vaalyn** [comment]
Please fill out the template in english and provide the required information we ask in the template.

**Comment by DannyDjj-alt** [comment]
¿Utilizas el método de instalación de Docker?si

Versión AzuraCast:v0.12.4 Stable

Sistema operativo host: Ubuntu Server

Describe el error: al abrir el link de musica publica le doy play pero no se escucha nada

Pasos para reproducir: abro el link de la radio donde dice pagina publica, se abre pero no se escucha nada el audio

Comportamiento esperado: que se escuche la musica

Registros relevantes:

Capturas de pantalla:
![image](https://user-images.githubusercontent.com/84608705/119278638-1beb1800-bbec-11eb-83d9-2f898c4a4653.png)


Dispositivos):

Dispositivo: PC Escritorio,  laptop, smartphone
ENTONCES:
Navegador: google chroome
Versión: 2021
Contexto adicional:

**Comment by DannyDjj-alt** [comment]
Do you use the Docker installation method? Yes

AzuraCast version: v0.12.4 Stable

Operating host system: Ubuntu Server

Describe the error: when I open the public music link I give it play but nothing is heard

Steps to reproduce: I open the link of the radio where it says public page, it opens but the audio is not heard at all

Expected behavior: let the music be heard

Relevant records:


Screenshots:
![image](https://user-images.githubusercontent.com/84608705/119283440-adfe1b00-bc02-11eb-8ae6-efa564195bc6.png)

**Comment by Vaalyn** [comment]
Please also provide any errors from your browsers JavaScript console.

**Comment by DannyDjj-alt** [comment]
![image](https://user-images.githubusercontent.com/84608705/119284385-32519d80-bc05-11eb-9aad-7008a172d6d1.png)

**Comment by Vaalyn** [comment]
This looks like an issue that is very similar to one I have talked with another user about a while back.

Please make sure that you have at least one mount point set up and configured to be available on public pages.

**Comment by DannyDjj-alt** [comment]
reinstall again

**Comment by DannyDjj-alt** [comment]
the problem remains
