### ISSUE TITLE
A few streamer broadcasts doesn't load

### ISSUE THREAD

**Issue by DylantjeT** [AzuraCast/AzuraCast#4201]
**Using Docker installation method?**
Yes

**AzuraCast version:**
 Rolling Release #b2ae1da (2021-04-06 19:36) • Docker • PHP 7.4

**Host Operating System:**
Windows Server 

**Describe the bug:**
In the beginning, I could listen back to all of the deejays' broadcasts.

Now more than half of the broadcasts of random deejays do not load. 

Then the broadcast page stays on load.... 

**Steps to reproduce:**
Reproducing cannot be done. It is done gradually. It seems like the deejays with more broadcasts have this problem faster. 

**Expected behavior:**
Through broadcasts, you should normally be able to listen back to all of the deejays' broadcasts. Or download them. 

**Relevant logs:**

**Screenshots:**
![image](https://user-images.githubusercontent.com/84686803/119278136-b1ee6500-bc23-11eb-8210-486e535a4ac6.png)

**Device(s):**
All browsers.

**Comment by SC2Mitch** [comment]
Can you open up the console when this issue happens and check the network tab for any failed or errors with the connection? This will be very helpful for us to debug

**Comment by DylantjeT** [comment]
{code: 500,…}
code: 500
extra_data: []
formatted_message: "<b>TypeError at /var/azuracast/www/vendor/league/flysystem/src/Filesystem.php L34:</b> Argument 1 passed to League\\Flysystem\\Filesystem::fileExists() must be of the type string, null given, called in /var/azuracast/www/src/Controller/Api/Stations/Streamers/BroadcastsController.php on line 66"
message: "TypeError at /var/azuracast/www/vendor/league/flysystem/src/Filesystem.php L34: Argument 1 passed to League\\Flysystem\\Filesystem::fileExists() must be of the type string, null given, called in /var/azuracast/www/src/Controller/Api/Stations/Streamers/BroadcastsController.php on line 66"
success: false

**Comment by DylantjeT** [comment]
![image](https://user-images.githubusercontent.com/84686803/119369942-05f55a00-bcb5-11eb-8351-edce1a380d65.png)

**Comment by Vaalyn** [comment]
I'm pretty sure this bug was already fixed.
Please update your installation and check if that resolves the issue.
