### ISSUE TITLE
Upcoming Song Queue - next song time to play is tracking actual time

### ISSUE THREAD

**Issue by pixel-paul** [AzuraCast/AzuraCast#4207]
**Using Docker installation method?**
Yes

**AzuraCast version:**
Rolling Release #2f0b109 (2021-05-12 14:31) • Docker • PHP 8.0 

**Host Operating System:**
CentOS 7

**Describe the bug:**
The upcoming song queue appears to be tracking the actual time. So in this example, the actual time is 7:25pm BST and the next song to play is marked as starting at 7:25pm, even though the current song playing is a DJ mix that finishes in 1 hour 35 minutes.

**Steps to reproduce:**
All I have done to reproduce is use the debugger to regenerate the song queue.

**Expected behavior:**
The song queue to recognise the length of the song now playing and account for that in the song queue display

**Screenshots:**
**Actual time**
![Screenshot_2021-05-24 Upcoming Song Queue - time](https://user-images.githubusercontent.com/389303/119391668-8b353a80-bcc6-11eb-851c-795181a2e152.png)
**Time next song is marked to play**
![Screenshot_2021-05-24 Upcoming Song Queue - times](https://user-images.githubusercontent.com/389303/119391674-8d979480-bcc6-11eb-93f8-bb5549f19549.png)
**In context (edit)**
![InkedScreenshot_2021-05-24 Upcoming Song Queue(1)_still](https://user-images.githubusercontent.com/389303/119392236-6a211980-bcc7-11eb-8db3-40b58dd6d13f.jpg)

**Comment by SC2Mitch** [comment]
I'm unsure if this is a technical 'bug' or is how it's intended, I'll raise it for a comment from the team.

**Comment by SlvrEagle23** [comment]
@pixel-paul This is working as intended; when we don't know the duration of the track being played, we assume the next track is due to be played immediately and then update the queue every few minutes accordingly to adjust for that.

**Comment by pixel-paul** [comment]
@SlvrEagle23 - is there a cause as to why we wouldn't know the duration of the current track being played?

**Comment by SlvrEagle23** [comment]
@pixel-paul If it's a live broadcast, we don't have duration data for those; if it's something that was in the queue, it should have a duration but there are also circumstances where we can't pull the current track, but those should be more rare.

**Comment by pixel-paul** [comment]
@SlvrEagle23 in my case it was not a live broadcast, so it appears I ran into one of the edge case circumstances.
