### ISSUE TITLE
Updating Feb 13, 2018

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#422]
- **Installation Method:** Traditional
- **Host OS (if using Docker):** Ubuntu 16.04 

Since the February 13th update I can't connect to the server, Radio always works.
Safari cannot open the page "? 217.182.128.137" because Safari cannot connect to the server "217.182.128.137".

**Comment by SlvrEagle23** [comment]
@ckeurk Nginx was updated back to its normal latest version without nchan integrated, so it's possible things didn't restart correctly. Try running `service nginx restart` and see if that helps?

**Comment by ckeurk** [comment]
Doesn't work.
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.

**Comment by ckeurk** [comment]
`nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabl
   Active: failed (Result: exit-code) since mer. 2018-02-14 06:26:26 CET; 1min 28s 
  Process: 17893 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on

févr. 14 06:26:26 vps407479 systemd[1]: Starting A high performance web server and 
févr. 14 06:26:26 vps407479 nginx[17893]: nginx: [emerg] unknown directive "nchan_p
févr. 14 06:26:26 vps407479 nginx[17893]: nginx: configuration file /etc/nginx/ngin
févr. 14 06:26:26 vps407479 systemd[1]: nginx.service: Control process exited, code
févr. 14 06:26:26 vps407479 systemd[1]: Failed to start A high performance web serv
févr. 14 06:26:26 vps407479 systemd[1]: nginx.service: Unit entered failed state.
févr. 14 06:26:26 vps407479 systemd[1]: nginx.service: Failed with result 'exit-cod`

**Comment by ckeurk** [comment]
`● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since mer. 2018-02-14 06:26:26 CET; 1min 28s ago
  Process: 17893 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, sta

févr. 14 06:26:26 vps407479 systemd[1]: Starting A high performance web server and a reverse proxy ser
févr. 14 06:26:26 vps407479 nginx[17893]: nginx: [emerg] unknown directive "nchan_publisher" in /etc/n
févr. 14 06:26:26 vps407479 nginx[17893]: nginx: configuration file /etc/nginx/nginx.conf test failed
févr. 14 06:26:26 vps407479 systemd[1]: nginx.service: Control process exited, code=exited status=1
févr. 14 06:26:26 vps407479 systemd[1]: Failed to start A high performance web server and a reverse pr
févr. 14 06:26:26 vps407479 systemd[1]: nginx.service: Unit entered failed state.
févr. 14 06:26:26 vps407479 systemd[1]: nginx.service: Failed with result 'exit-code'.`

**Comment by SlvrEagle23** [comment]
@ckeurk What does the log say if you run `systemctl status nginx.service`?

**Comment by ckeurk** [comment]
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since mer. 2018-02-14 06:26:26 CET; 5min ago
  Process: 17893 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

févr. 14 06:26:26 vps407479 systemd[1]: Starting A high performance web server and a reverse proxy server...
févr. 14 06:26:26 vps407479 nginx[17893]: nginx: [emerg] unknown directive "nchan_publisher" in /etc/nginx/sites-enabled/00-azuracast:7
févr. 14 06:26:26 vps407479 nginx[17893]: nginx: configuration file /etc/nginx/nginx.conf test failed
févr. 14 06:26:26 vps407479 systemd[1]: nginx.service: Control process exited, code=exited status=1
févr. 14 06:26:26 vps407479 systemd[1]: Failed to start A high performance web server and a reverse proxy server.
févr. 14 06:26:26 vps407479 systemd[1]: nginx.service: Unit entered failed state.
févr. 14 06:26:26 vps407479 systemd[1]: nginx.service: Failed with result 'exit-code'.
~

**Comment by SlvrEagle23** [comment]
@ckeurk Seems nchan wrote a configuration that the old nginx doesn't like. Working on it right now.

**Comment by ckeurk** [comment]
Ok Thank you ;)

**Comment by SlvrEagle23** [comment]
@ckeurk Newest push should force a proper configuration file into the nginx root...try it out!

**Comment by ckeurk** [comment]
always the same problem : Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.

nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since mer. 2018-02-14 07:15:20 CET; 24s ago
  Process: 13616 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

févr. 14 07:15:20 vps407479 systemd[1]: Starting A high performance web server and a reverse proxy server...
févr. 14 07:15:20 vps407479 nginx[13616]: nginx: [emerg] unknown directive "nchan_publisher" in /etc/nginx/sites-enabled/00-azuracast:7
févr. 14 07:15:20 vps407479 nginx[13616]: nginx: configuration file /etc/nginx/nginx.conf test failed
févr. 14 07:15:20 vps407479 systemd[1]: nginx.service: Control process exited, code=exited status=1
févr. 14 07:15:20 vps407479 systemd[1]: Failed to start A high performance web server and a reverse proxy server.
févr. 14 07:15:20 vps407479 systemd[1]: nginx.service: Unit entered failed state.
févr. 14 07:15:20 vps407479 systemd[1]: nginx.service: Failed with result 'exit-code'.

**Comment by SlvrEagle23** [comment]
@ckeurk The latest update script should be forcing that file to be the correct new version. I've verified on my local install that it's doing that correctly; I'm not sure why your updater isn't doing that.

Try running `./update.sh --full` or just manually replace `/etc/nginx/sites-enabled/00-azuracast` with:

```
client_max_body_size 50M;

server {
    listen 80;
    listen 443 default_server ssl;

    ssl_certificate    /etc/nginx/ssl/server.crt;
    ssl_certificate_key    /etc/nginx/ssl/server.key;

    root /var/azuracast/www/web;
    index index.php;

    server_name localhost;

    add_header X-XSS-Protection 1;
    add_header X-Content-Type-Options nosniff;
    add_header Referrer-Policy no-referrer-when-downgrade;

    access_log /var/azuracast/www_tmp/access.log;
    error_log /var/azuracast/www_tmp/error.log;

    location / {
        try_files $uri @clean_url;
    }

    location @clean_url {
        rewrite ^(.*)$ /index.php last;
    }

    location ~ \.php$ {
        fastcgi_hide_header Cache-Control;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/azuracast/www/web$fastcgi_script_name;
        include fastcgi_params;

        fastcgi_read_timeout 1800;
    }

    # Reverse proxy all possible radio listening ports (8000, 8010...8480, 8490)
    location ~ ^/radio/(8[0-4][0-9]0)(/?)(.*)$ {
        proxy_buffering           off;
        proxy_ignore_client_abort off;
        proxy_intercept_errors    on;
        proxy_next_upstream       error timeout invalid_header;
        proxy_redirect            off;
        proxy_connect_timeout     60;
        proxy_send_timeout        21600;
        proxy_read_timeout        21600;

        proxy_set_header Host localhost:$1;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;

        proxy_pass http://127.0.0.1:$1/$3;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    location ~ /\.ht {
        deny all;
    }
}
```

**Comment by ckeurk** [comment]
After ./update.sh --full

`TASK [nginx : Install nginx] ***************************************************
failed: [localhost] (item=[u'nginx', u'nginx-common', u'nginx-extras']) => {"cache_update_time": 1518589375, "cache_updated": false, "changed": false, "item": ["nginx", "nginx-common", "nginx-extras"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'nginx' 'nginx-extras'' failed: No apport report written because the error message indicates its a followup error from a previous failure.\nE: Sub-process /usr/bin/dpkg returned an error code (1)\n", "rc": 100, "stderr": "No apport report written because the error message indicates its a followup error from a previous failure.\nE: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stderr_lines": ["No apport report written because the error message indicates its a followup error from a previous failure.", "E: Sub-process /usr/bin/dpkg returned an error code (1)"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nnginx is already the newest version (1.10.3-0ubuntu0.16.04.2).\nnginx-extras is already the newest version (1.10.3-0ubuntu0.16.04.2).\n0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.\n2 not fully installed or removed.\nAfter this operation, 0 B of additional disk space will be used.\nSetting up nginx-extras (1.10.3-0ubuntu0.16.04.2) ...\r\nJob for nginx.service failed because the control process exited with error code. See \"systemctl status nginx.service\" and \"journalctl -xe\" for details.\r\ninvoke-rc.d: initscript nginx, action \"start\" failed.\r\n\u001b[0;1;31m*\u001b[0m nginx.service - A high performance web server and a reverse proxy server\r\n   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)\r\n   Active: \u001b[0;1;31mfailed\u001b[0m (Result: exit-code) since Wed 2018-02-14 07:23:40 CET; 7ms ago\r\n  Process: 20293 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; \u001b[0;1;31m(code=exited, status=1/FAILURE)\u001b[0m\r\n\r\nFeb 14 07:23:40 vps407479 systemd[1]: Starting A high performance web serve.....\r\nFeb 14 07:23:40 vps407479 nginx[20293]: nginx: [emerg] unknown directive \"nc...7\r\nFeb 14 07:23:40 vps407479 nginx[20293]: nginx: configuration file /etc/nginx...d\r\nFeb 14 07:23:40 vps407479 systemd[1]: \u001b[0;1;39mnginx.service: Control process exited...=1\u001b[0m\r\nFeb 14 07:23:40 vps407479 systemd[1]: \u001b[0;1;31mFailed to start A high performance we...r.\u001b[0m\r\nFeb 14 07:23:40 vps407479 systemd[1]: \u001b[0;1;39mnginx.service: Unit entered failed state.\u001b[0m\r\nFeb 14 07:23:40 vps407479 systemd[1]: \u001b[0;1;39mnginx.service: Failed with result 'ex...'.\u001b[0m\r\nHint: Some lines were ellipsized, use -l to show in full.\r\ndpkg: error processing package nginx-extras (--configure):\r\n subprocess installed post-installation script returned error exit status 1\r\ndpkg: dependency problems prevent configuration of nginx:\r\n nginx depends on nginx-core (>= 1.10.3-0ubuntu0.16.04.2) | nginx-full (>= 1.10.3-0ubuntu0.16.04.2) | nginx-light (>= 1.10.3-0ubuntu0.16.04.2) | nginx-extras (>= 1.10.3-0ubuntu0.16.04.2); however:\r\n  Package nginx-core is not installed.\r\n  Package nginx-full is not installed.\r\n  Package nginx-light is not installed.\r\n  Package nginx-extras is not configured yet.\r\n nginx depends on nginx-core (<< 1.10.3-0ubuntu0.16.04.2.1~) | nginx-full (<< 1.10.3-0ubuntu0.16.04.2.1~) | nginx-light (<< 1.10.3-0ubuntu0.16.04.2.1~) | nginx-extras (<< 1.10.3-0ubuntu0.16.04.2.1~); however:\r\n  Package nginx-core is not installed.\r\n  Package nginx-full is not installed.\r\n  Package nginx-light is not installed.\r\n  Package nginx-extras is not configured yet.\r\n\r\ndpkg: error processing package nginx (--configure):\r\n dependency problems - leaving unconfigured\r\nErrors were encountered while processing:\r\n nginx-extras\r\n nginx\r\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "nginx is already the newest version (1.10.3-0ubuntu0.16.04.2).", "nginx-extras is already the newest version (1.10.3-0ubuntu0.16.04.2).", "0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.", "2 not fully installed or removed.", "After this operation, 0 B of additional disk space will be used.", "Setting up nginx-extras (1.10.3-0ubuntu0.16.04.2) ...", "Job for nginx.service failed because the control process exited with error code. See \"systemctl status nginx.service\" and \"journalctl -xe\" for details.", "invoke-rc.d: initscript nginx, action \"start\" failed.", "\u001b[0;1;31m*\u001b[0m nginx.service - A high performance web server and a reverse proxy server", "   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)", "   Active: \u001b[0;1;31mfailed\u001b[0m (Result: exit-code) since Wed 2018-02-14 07:23:40 CET; 7ms ago", "  Process: 20293 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; \u001b[0;1;31m(code=exited, status=1/FAILURE)\u001b[0m", "", "Feb 14 07:23:40 vps407479 systemd[1]: Starting A high performance web serve.....", "Feb 14 07:23:40 vps407479 nginx[20293]: nginx: [emerg] unknown directive \"nc...7", "Feb 14 07:23:40 vps407479 nginx[20293]: nginx: configuration file /etc/nginx...d", "Feb 14 07:23:40 vps407479 systemd[1]: \u001b[0;1;39mnginx.service: Control process exited...=1\u001b[0m", "Feb 14 07:23:40 vps407479 systemd[1]: \u001b[0;1;31mFailed to start A high performance we...r.\u001b[0m", "Feb 14 07:23:40 vps407479 systemd[1]: \u001b[0;1;39mnginx.service: Unit entered failed state.\u001b[0m", "Feb 14 07:23:40 vps407479 systemd[1]: \u001b[0;1;39mnginx.service: Failed with result 'ex...'.\u001b[0m", "Hint: Some lines were ellipsized, use -l to show in full.", "dpkg: error processing package nginx-extras (--configure):", " subprocess installed post-installation script returned error exit status 1", "dpkg: dependency problems prevent configuration of nginx:", " nginx depends on nginx-core (>= 1.10.3-0ubuntu0.16.04.2) | nginx-full (>= 1.10.3-0ubuntu0.16.04.2) | nginx-light (>= 1.10.3-0ubuntu0.16.04.2) | nginx-extras (>= 1.10.3-0ubuntu0.16.04.2); however:", "  Package nginx-core is not installed.", "  Package nginx-full is not installed.", "  Package nginx-light is not installed.", "  Package nginx-extras is not configured yet.", " nginx depends on nginx-core (<< 1.10.3-0ubuntu0.16.04.2.1~) | nginx-full (<< 1.10.3-0ubuntu0.16.04.2.1~) | nginx-light (<< 1.10.3-0ubuntu0.16.04.2.1~) | nginx-extras (<< 1.10.3-0ubuntu0.16.04.2.1~); however:", "  Package nginx-core is not installed.", "  Package nginx-full is not installed.", "  Package nginx-light is not installed.", "  Package nginx-extras is not configured yet.", "", "dpkg: error processing package nginx (--configure):", " dependency problems - leaving unconfigured", "Errors were encountered while processing:", " nginx-extras", " nginx"]}`

**Comment by ckeurk** [comment]
To modify the file you're asking me for, I can't because no software even textwrangler (I'm on Mac) can open it.

**Comment by FrBillyD** [comment]
Removing of all blocks containing "nchan" in the nginx config file seems to work. But how to be sure it don't break my installation ?

**Comment by susl16c** [comment]
I do not understand why I should even delete "nchan" ? What does it even give except problems?

**Comment by FrBillyD** [comment]
Don't know :smile:  But it worked for me. I did not do reverse engineering. Probably only @SlvrEagle23 can reply to this at now. nchan components removed from Nginx ? Or need to be loaded differently ?

**Comment by ckeurk** [comment]
For the moment he sleeps the answer arrives in not long. 🛌

**Comment by FrBillyD** [comment]
Yup, no problem, it's not urgent in our case.

**Comment by SlvrEagle23** [comment]
Good morning all! Explaining time. @FrBillyD @ckeurk @susl16c 

At one point, I was getting complaints that the updates to the "now playing" data on the web site didn't always line up very well with when the actual song title had changed on the radio station. I wanted to streamline that entire stack, so I added a ping tool that monitors the station for changes (`station-watcher`), more responsive updates to the now-playing manager, and a frontend tool called nchan that allowed live, websocket-based updates to the now-playing data on the client side.

Unfortunately, it turns out nchan not only doesn't build binaries for ARM processors (meaning as long as I used it, Raspberry Pi's were out of the question) but it requires that I use prepackaged copies of nginx that are missing some crucial security fixes, especially in light of the recent spectre/meltdown situation.

Fortunately, the other changes I mentioned are actually sufficient to produce more response, faster "now playing" updates that line up better with the actual song changes on the station, so nchan isn't really needed.

The latest updates have been trying to remove it cleanly from traditional installs. It's already removed from Docker installs, and there were no problems in that transition (since it's easier to do things like this in Docker). I've pushed out another update today that should do a "harder" removal of the old nginx and install the new one more cleanly.

In the event that even the latest fix doesn't work, the copy of nginx being used now is just the updated version straight from the Ubuntu 16.04 repos, so you could just as well install it via `apt-get install nginx` if you wanted.

Hope that answers some questions!

**Comment by ckeurk** [comment]
Great, it's working again thanks.
