### ISSUE TITLE
scheduled tracks playing later than expected

### ISSUE THREAD

**Issue by cpeter1207** [AzuraCast/AzuraCast#4239]
**Using Docker installation method?**
yes

**AzuraCast version:**
v0.12.4 Stable • Docker • PHP 8.0 

**Host Operating System:**
Ubuntu 20.04

**Describe the bug:**
Last year I helped debug and fix an issue where scheduled events were playing later than expected. The primary reason for this was a race condition where liquidsoap dequeues a song about 40 seconds before it starts. If the buildQueue task runs during that time, the length of the dequeued, but not started, song is not taken into account and the value of $now is off by what ever the length of that track is. On a song-based station, this ends up being around 3 minutes (if tracks average 3 minutes in length).

The impact of this is that scheduled events, E.g. top of hour IDs, play a few minutes later than you'd expect them too.

Recently while listening to my station, my wife commented to me that the IDs were playing late. I started paying attention to this and she is correct. Upon further investigation, I see that the code I added to annotateNextSong to fix this has been removed. I'm sure I could create a PR to have it added again, but I'd like to understand the reason for removing it before I do that as I thought I'd explained the reason for it quite clearly.

**Comment by Vaalyn** [comment]
There have been a few iterations of refactoring on the scheduler / autodj but I think in the rolling-release the fix should still be there: https://github.com/AzuraCast/AzuraCast/blob/main/src/Radio/AutoDJ.php#L127-L180

The last stable release does not have the latest fix included so you might be hitting this problem due to the version you are running on.

Can you update to the rolling-release and check if this happens there too?

If you can still see this happening on the current rolling-release please link us the exact parts of the code that are missing the fix for adjusting to the correct time.

**Comment by zloysystem** [comment]
@Vaalyn on Rolling Release # 41b66e1 I confirm that the same behavior of the list, also when skipping a completely random track is inserted, not according to the list

**Comment by Vaalyn** [comment]
@zloysystem The random track on skipping is an issue with Liquidsoap that we can currently not fix. LS tries to fetch a song from the dynamic list aka the AzuraCast API and instantly falls back to fetching a track directly from the generated m3u files.

**Comment by cpeter1207** [comment]
@Vaalyn I upgraded to the latest rolling release and have been monitoring this all morning. My impression is that this is better than then 0.12.4 stable, but still not right. I've heard several instances this morning where scheduled track played one track later than it should've.

I've been looking at the refactors since my fix. I'm almost certain that the code I added has been removed and not replaced by something else, but it's been a year since I've looked at this code so I'm still looking into what I did and comparing it to what is there now to be sure I understand the current state of the code.

**Comment by cpeter1207** [comment]
The missing code I'm referring to is here:

public function annotateNextSong(Entity\Station $station, $asAutoDj = false): string
    {
        $queueRow = $this->queueRepo->getNextInQueue($station);
        if (!($queueRow instanceof Entity\StationQueue)) {
            return '';
        }

        $this->logger->pushProcessor(function ($record) use ($station) {
            $record['extra']['station'] = [
                'id' => $station->getId(),
                'name' => $station->getName(),
            ];
            return $record;
        });

[CP]: Here is where I calculate now to account for the LS behavior I mentioned.

        $duration = $queueRow->getDuration();
        $now = $this->getNowFromCurrentSong($station);

        $this->logger->debug('Adjusting now based on duration of most recently cued song.', [
            'song' => $queueRow->getSong()
                ->getText(),
            'cued' => (string)$now,
            'duration' => $duration,
        ]);

        $now = $this->getAdjustedNow($station, $now, $duration);

        $event = new AnnotateNextSong($queueRow, $asAutoDj);
        $this->dispatcher->dispatch($event);

[CP]: This is where I hacked because I don't really know what I'm doing. A better solution might be to add $now to the AnnotateNextSong event that gets dispatched above and run buildQueue from an AnnotateNextSong event handler. There is really no reason to run buildQueue periotically. If tracks are very long, buildQueue runs a number of times without doing anything. For tracks that are very short, it doesn't run often enough and the queue drains and has to get refilled. Imo it's better to add a new track to the queue as soon as one is removed. More importantly, though, you have the potential to lose an accurate value for $now if you remove a track without adding its length to the expected end time of the currently playing song and passing that to buildQueue.

        $this->buildQueueFromNow($station, $now, true);

        $this->logger->popProcessor();

        return $event->buildAnnotations();
    }

I spent weeks observing, debugging, and documenting this behavior last September. I also taught myself enough PHP to code and test a fix for this. I'm sure I can incorporate this fix into the refactoring that has been done since then, but I wonder how we can make sure that this doesn't regress again?

**Comment by Vaalyn** [comment]
@SlvrEagle23 could you take a look at this with me?

I'm unsure if you have already incorporated the fixes from @cpeter1207 when you where refactoring the AutoDJ.

I think like mentioned by @cpeter1207 we should maybe rethink the `AnnotateNextSong` in regards to the `$now` time but I'm not very familiar with the AutoDJ so I might be missing something that was already intended to port the fixes over.

**Comment by silvaalex2021** [comment]
sorry but, while looking at these AutoDJ scheduling questions, could I kindly ask you to take a look at this post to see if it's possible to implement?

https://github.com/AzuraCast/AzuraCast/discussions/4186

Thank You!

**Comment by YosefAdPro** [comment]
I saw a fix for it. https://github.com/AzuraCast/AzuraCast/pull/4373
I still have the problem, and there is a 3-5 minute delay in scheduling.

Rolling Release #97e373a
