### ISSUE TITLE
Update 31/05/2021 : SQL update error

### ISSUE THREAD

**Issue by Likeandfeel** [AzuraCast/AzuraCast#4243]
Hi Team

I get an error during update regarding SQL update . Install is 100% standard since 2018.
Any idea ? 

Thanks a lot
best regards

**Using Docker installation method?**
No

**AzuraCast version:**
AzuraCast (Environment: production, Update revision: 62
Last update Saturday 29/05/2021

**Host Operating System:**
Ubuntu 20.04

**Describe the bug:**
During update i get 

fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/console azuracast:setup --update", "delta": "0:00:00.744553", "end": "2021-05-31 13:31:44.887956", "msg": "non-zero return code", "rc": 1, "start": "2021-05-31 13:31:44.143403", "stderr": "[2021-05-31T11:31:44.871136+00:00] AzuraCast.ERROR: Doctrine\\DBAL\\Exception\\SyntaxErrorException: An exception occurred while executing 'ALTER TABLE users RENAME COLUMN uid TO id':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN uid TO id' at line 1 (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 98 while running console command `azuracast:setup` {\"exception\":\"[object] (Doctrine\\\\DBAL\\\\Exception\\\\SyntaxErrorException(code: 0): An exception occurred while executing 'ALTER TABLE users RENAME COLUMN uid TO id':\\n\\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN uid TO id' at line 1 at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:98)\\n[previous exception] [object] (Doctrine\\\\DBAL\\\\Driver\\\\PDO\\\\Exception(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN uid TO id' at line 1 at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\\n[previous exception] [object] (PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN uid TO id' at line 1 at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:132)\"} []\n[2021-05-31T11:31:44.872809+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 1. [] []\n\nIn AbstractMySQLDriver.php line 98:\n                                                                               \n  An exception occurred while executing 'ALTER TABLE users RENAME COLUMN uid   \n  TO id':                                                                      \n                                                                               \n  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  \n  n your SQL syntax; check the manual that corresponds to your MariaDB server  \n   version for the right syntax to use near 'COLUMN uid TO id' at line 1       \n                                                                               \n\nIn Exception.php line 18:\n                                                                               \n  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  \n  n your SQL syntax; check the manual that corresponds to your MariaDB server  \n   version for the right syntax to use near 'COLUMN uid TO id' at line 1       \n                                                                               \n\nIn PDOConnection.php line 132:\n                                                                               \n  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  \n  n your SQL syntax; check the manual that corresponds to your MariaDB server  \n   version for the right syntax to use near 'COLUMN uid TO id' at line 1       \n                                                                               \n\nazuracast:setup [--update] [--load-fixtures] [--release]", "stderr_lines": ["[2021-05-31T11:31:44.871136+00:00] AzuraCast.ERROR: Doctrine\\DBAL\\Exception\\SyntaxErrorException: An exception occurred while executing 'ALTER TABLE users RENAME COLUMN uid TO id':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN uid TO id' at line 1 (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 98 while running console command `azuracast:setup` {\"exception\":\"[object] (Doctrine\\\\DBAL\\\\Exception\\\\SyntaxErrorException(code: 0): An exception occurred while executing 'ALTER TABLE users RENAME COLUMN uid TO id':\\n\\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN uid TO id' at line 1 at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:98)\\n[previous exception] [object] (Doctrine\\\\DBAL\\\\Driver\\\\PDO\\\\Exception(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN uid TO id' at line 1 at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\\n[previous exception] [object] (PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN uid TO id' at line 1 at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:132)\"} []", "[2021-05-31T11:31:44.872809+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 1. [] []", "", "In AbstractMySQLDriver.php line 98:", "                                                                               ", "  An exception occurred while executing 'ALTER TABLE users RENAME COLUMN uid   ", "  TO id':                                                                      ", "                                                                               ", "  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  ", "  n your SQL syntax; check the manual that corresponds to your MariaDB server  ", "   version for the right syntax to use near 'COLUMN uid TO id' at line 1       ", "                                                                               ", "", "In Exception.php line 18:", "                                                                               ", "  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  ", "  n your SQL syntax; check the manual that corresponds to your MariaDB server  ", "   version for the right syntax to use near 'COLUMN uid TO id' at line 1       ", "                                                                               ", "", "In PDOConnection.php line 132:", "                                                                               ", "  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  ", "  n your SQL syntax; check the manual that corresponds to your MariaDB server  ", "   version for the right syntax to use near 'COLUMN uid TO id' at line 1       ", "                                                                               ", "", "azuracast:setup [--update] [--load-fixtures] [--release]"], "stdout": "\nAzuraCast Setup\n===============\n\nWelcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...\n * Environment: Production\n * Installation Method: Ansible\n\n ! [NOTE] Running in update mode.                                               \n\n\nRunning Database Migrations\n---------------------------", "stdout_lines": ["", "AzuraCast Setup", "===============", "", "Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...", " * Environment: Production", " * Installation Method: Ansible", "", " ! [NOTE] Running in update mode.                                               ", "", "", "Running Database Migrations", "---------------------------"]}

**Steps to reproduce:**

1. Go to '/var/zaurcast/www
2. execute ./update.sh
3. Scroll down to end of script execution

**Expected behavior:**
Update = Ok

**Relevant logs:**
See above

**Comment by Vaalyn** [comment]
The error you are seeing is caused by an outdated MariaDB version that does not support the `ALTER TABLE ... RENAME COLUMN ... TO ...` syntax in the newest migration.

@SlvrEagle23 do we ever update the MariaDB version on Ansible installations?

**Comment by SlvrEagle23** [comment]
@Likeandfeel Try updating again; we've updated the version of MariaDB that's used on Ansible installations, which should fix issues with the update migration.

**Comment by Likeandfeel** [comment]
Hi team

Thanks a lot for your answer and assistance.
Seems working with the change. Only this notice during the update


TASK [mariadb : Update MariaDB Dependencies] ***********************************************************************************************************************
[WARNING]: Consider using the get_url or uri module rather than running 'curl'.  If you need to use command because get_url or uri is insufficient you can add
'warn: false' to this command task or set 'command_warnings=False' in ansible.cfg to get rid of this message.

Thanks for all
Best regards
