### ISSUE TITLE
Disappeared images of songs

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#425]
Please tell me why the missing images of songs?
![dfbdfb](https://user-images.githubusercontent.com/23697714/36191744-a98fab6a-116f-11e8-924f-eb62acb9261c.png)

**Comment by SlvrEagle23** [comment]
@susl16c Songs that don't have album art won't show anything in the art section. The art section will just disappear for those songs. This may be a bit confusing, but this is on purpose, so that stations that don't have any album artwork don't stick out as missing that data.
