### ISSUE TITLE
Azuracast not working after update :(

### ISSUE THREAD

**Issue by Gujalls** [AzuraCast/AzuraCast#4258]
**Using Docker installation method?**
Yes

**AzuraCast version:**
latest

OS: CentOs

**Issue** : Not able to access Azuracast :(

After very long and being hesitant to update the Azuracast cast - I performed an update today.
Followed the instruction as provided 'https://docs.azuracast.com/en/getting-started/updates' and performed the below steps
cd /var/azuracast
./docker.sh update-self
./docker.sh update

My installation all went well. 
I've previously configured azuracast to run in non-standard ports for HTTP and HTTPS. 

I tried the below command to change to different ports
./docker.sh change-ports

Performed below steps as well
docker-compose down
docker-compose up -d

But nothing is working. I verified that the ports are running using the command 
docker container ls 

I could also see all the ports of my radios are also running. 
But I'm not able to connect either to azuracast dashboard and not even able to listen to the radio station.

Please can you help - these are live stations
And I've been trying to fix it from morning referring to various documents and issues/links - but nothing worked.

Many thanks for your help & support.

**Comment by SC2Mitch** [comment]
We need logs to even provide basic assistance.

**Comment by Gujalls** [comment]
I don't have access to the web otherwise I could have provided the logs from "AzuraCast installation you can check most logs through the Administration -> System Logs."
Please can you let me know where in the system can I find these logs so that I can provide with the required.
I have following directories
/var/azuracast
/var/lib/docker

**Comment by SC2Mitch** [comment]
`cd /var/azuracast`
`docker-compose logs -f`

**Comment by Gujalls** [comment]
[output.log](https://github.com/AzuraCast/AzuraCast/files/6602758/output.log)

Thank you. I've attached the log file - please let me know if there is anything else that I can provide to resolve this issue.

I can see the server port is running as below. [9443 is the SSL port that I'm using]
> netstat -an | grep 9443
tcp        0      0 0.0.0.0:9443            0.0.0.0:*               LISTEN

**Comment by SlvrEagle23** [comment]
@Gujalls I think you're using an old version of `docker-compose.yml`...when updating, be sure to run:

```
./docker.sh update-self
./docker.sh update
```

and when prompted to update your `docker-compose.yml` file, answer `Y` to allow it.

You can do these steps even from your current state and it should fix it right up.

**Comment by Gujalls** [comment]
@SlvrEagle23 
Thank you. I was very hesitant to say Y for updating docker-compose.yml but had no other option. So went with an 'Y' and it worked. Thank you for the wonderful support.

Greatly Appreciated.
