### ISSUE TITLE
Error: File Not Processing, and SFTP  - (5 JUNE 2021)

### ISSUE THREAD

**Issue by dancefmlive** [AzuraCast/AzuraCast#4259]
Hiya everyone, Firstly I'm not a geek or know anything about coding, I'm just a DJ and know the basics small basics, I'm talking about nothing.

anyway, my friend installed this azuracast for me on my server after leaving Centovacast, he persuaded me to use this system because centovacast are cheekily asking for money just to ask the simplest question and of cause, they still don't have SSL on their players after 1.5 years of me asking them, my problem here today is that Files are not processing or when I upload via the browser I get a message - **TRUE** in red and it doesn't do anything else I've also come across when uploading on SFTP when you drag files into the window I get slow upload every time I stop it then do the same again overwrite the file and its uploads in MB, not kb, and you also can't go up a folder to the main menu in FTP says permission denied, 

I'm also having issues with processing I've followed this video to try to fix = [https://www.youtube.com/watch?v=LTbCxMeX4AQ](url) but this not working my file is saying (file Processing) that is it, its 163Mb in size and it said that the last 2 hours

the azuacast is also very picky about what it wants to upload why is this

**Comment by SC2Mitch** [comment]
can you use our template?

**Comment by dancefmlive** [comment]
Not sure what u mean.
-------- Original message --------From: Mitch ***@***.***> Date: 05/06/2021  17:45  (GMT+00:00) To: AzuraCast/AzuraCast ***@***.***> Cc: dancefmlive ***@***.***>, Author ***@***.***> Subject: Re: [AzuraCast/AzuraCast] Error: File Not Processing, and SFTP  - (5
  JUNE 2021) (#4259) 
can you use our template?

**Comment by SC2Mitch** [comment]
When you create new issues you have a template, can you fill it out? 

https://puu.sh/HMzrr/bfd4785af4.png

**Comment by adoboligh1** [comment]
SFTP doesnt upload after 104 audio files.

**Comment by dancefmlive** [comment]
I have not got 104 files on the station

I have about 6, and about 7 adverts.

I dont know what it means TRUE in red

**Comment by dancefmlive** [comment]
As I explained I'm sorry I'm looking for email support I'm not a programmer or a geek that knows anything about this I'm a clown 🤡 when it comes to all this I don't have a clue, basically I'm homer Simpson looking for the any key
-------- Original message --------From: Mitch ***@***.***> Date: 05/06/2021  23:10  (GMT+00:00) To: AzuraCast/AzuraCast ***@***.***> Cc: dancefmlive ***@***.***>, Author ***@***.***> Subject: Re: [AzuraCast/AzuraCast] Error: File Not Processing, and SFTP  - (5
  JUNE 2021) (#4259) 
When you create new issues you have a template, can you fill it out?
https://puu.sh/HMzrr/bfd4785af4.png

**Comment by SC2Mitch** [comment]
Without the very basic kind of information about your installation, such as version, operating system and the likes we cannot offer any sort of help, as I'm unable to replicate this on my local host / development machine.

We do not offer any kind of email support, we're a very small team consisting of two developers and a moderator, we do not have the man power to offer such luxuries.

**Comment by dancefmlive** [comment]
All I need to know, is what does the TRUE mean and why is the system selective of what is uploaded normally before upload I correctify the tag information mix files down to 192 and upload, and it don't like it, whatever TRUE means why it keeps saying thatSent from my Galaxy
-------- Original message --------From: Mitch ***@***.***> Date: 06/06/2021  00:45  (GMT+00:00) To: AzuraCast/AzuraCast ***@***.***> Cc: dancefmlive ***@***.***>, Author ***@***.***> Subject: Re: [AzuraCast/AzuraCast] Error: File Not Processing, and SFTP  - (5
  JUNE 2021) (#4259) 
Without the very basic kind of information about your installation, such as version, operating system and the likes we cannot offer any sort of help, as I'm unable to replicate this on my local host / development machine.
We do not offer any kind of email support, we're a very small team consisting of two developers and a moderator, we do not have the man power to offer such luxuries.

**Comment by SC2Mitch** [comment]
Without knowing what version of AzuraCast you are currently on, we have no idea as to what is causing this issue. The version can be found at the bottom of your station dashboard, example: 
![image](https://user-images.githubusercontent.com/29955942/120910419-d102e300-c676-11eb-8a64-1159b44dacd2.png)
