### ISSUE TITLE
Import playlist error

### ISSUE THREAD

**Issue by bebjakub** [AzuraCast/AzuraCast#426]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Docker Image on VC1S from Scaleway

**Describe the issue in full detail, including screenshots if possible:**

I would like to import playlist but I'm getting error 500 http://prntscr.com/ieieaf
Media upload works perfectly...

Thank you!

**Comment by SlvrEagle23** [comment]
@bebjakub I was able to verify this issue and push a resolution to it; update your installation and try it out, and let me know how it works.

**Comment by bebjakub** [comment]
@SlvrEagle23 Thank you! It works for now!
