### ISSUE TITLE
Fresh install fails with 2GB RAM

### ISSUE THREAD

**Issue by parksquare** [AzuraCast/AzuraCast#4265]
**Using Docker installation method?**
Yes

**AzuraCast version:**

azuracast/azuracast_web_v2                    latest    2c2866723b2b   9 hours ago   880MB
azuracast/azuracast_radio                     latest    56442948c608   3 days ago    1.14GB
azuracast/azuracast_redis                     latest    1928548e43fb   3 days ago    32.4MB
azuracast/azuracast_nginx_proxy               latest    b94e896124d4   3 days ago    51.6MB
azuracast/azuracast_db                        latest    35faaba2d69d   3 days ago    447MB
azuracast/azuracast_nginx_proxy_letsencrypt   latest    b9c53a84526b   3 days ago    30.3MB

**Host Operating System:**
Debian 10.9 amd64

**Describe the bug:**
Fresh install fails with 2GB RAM, nginx process consistently killed as out of memory

**Steps to reproduce:**
1. Use a fresh installation of Debian with minimum recommended RAM of 2GB
2. Follow the Docker installation steps
3. Use stable or latest options (doesn't make any difference) 
4. Installation succeeds
5. Cannot access public or dashboard web pages
6. About 2 or 3 times per second get 'out of memory killed process <process id> (nginx)'
 
It seems that increasing the RAM to 4GB still does not allow the station to start properly, however at 5GB it does. 

Azuracast has previously installed and run perfectly on VM with identical specs

**Expected behavior:**
Should install and run successfully with 2GB RAM. 

**Relevant logs:**

**Screenshots:**

**Device(s):**

Hyper-V VM 
24 x vCPU 
2GB RAM 
180GB HDD

**Additional context:**

**Comment by SC2Mitch** [comment]
Do you have anything else on the VM / VPS? Otherwise, if you can provide some logs from Docker, that'd be very helpful.

**Comment by parksquare** [comment]
It's a completely fresh VM provisioned just for running Azuracast, so apart from ssh server has nothing else running on it

**Comment by parksquare** [comment]
If you need me to run any commands to get logs/other useful info just let me know

**Comment by SC2Mitch** [comment]
After installing AzuraCast, run `docker-compose logs -f` when your running into issues, this is helpful for us to debug this problem.
