### ISSUE TITLE
Cannot make my OPUS stream play in mono

### ISSUE THREAD

**Issue by ivellios1988** [AzuraCast/AzuraCast#4275]
**Using Docker installation method?**
Yes

**AzuraCast version:**
Rolling Release #3f23efa (2021-06-08 6:40)

**Host Operating System:**
Ubuntu 18.04

**Describe the bug:**
OPUS with 24kbps produces stereo output, causing a lot of artifacts, and there seems to be no way to make it play in mono

**Steps to reproduce:**
1. create a mountpoint with OPUS, set bitrate to 32 kbps (or even less by editing liquidsoap.liq and making the file read-only)
2. listen to itto hear the distortion
3. try editing liquidsoap.liq, add parameters such as channels=1 or stereo="false"/mono="true"
4. try to restart liquidsoap

Adding parameters described in 3) makes liquidsoap fail to start.

**Expected behavior:**
OPUS stream with bitrate of 32kbps and below should play in mono

**Relevant logs:**
channels=1 results in this:
```
At line 124, char 354-359:
Error 5: this value has type
  source(audio=2+_,...) (inferred at line 120, char 8-43)
but it should be a subtype of
  source(audio=1,...)
```
And stereo="false"/mono="true" results in this:

```
At line 124, char 90-95:
Error 8: Unknown parameter name or invalid parameter value
```

**Additional context:**
In my radio, I have a stream in OPUS with 24kbps, for those of my listeners who have bandwidth limits or weak connection with the Internet. I really do care about the audio quality even with bitrate as low as 24kbps and as long as this stream played in mono, it sounded pretty fine. However, after I updated my installation of AzuraCast two days ago, I discovered that this particular stream started playing in stereo... which, of course, results in a lot of artifacts being produced.

So, I'm trying to force this stream to play in mono... well, with no success. Even though I followed official Liquidsoap's documentation when modifying my liquidsoap.liq.

Setting channels=1 results in that Liquidsoap fails to start.

Tried adding stereo="false" or mono="true" - same result. Liquidsoap fails to start.

Maybe there is a way to somehow mix stereo channels to mono?

**Comment by ivellios1988** [comment]
channels=1 results in this:

```
At line 124, char 354-359:
Error 5: this value has type
  source(audio=2+_,...) (inferred at line 120, char 8-43)
but it should be a subtype of
  source(audio=1,...)
```


And stereo="false"/mono="true" results in this:

```
At line 124, char 90-95:
Error 8: Unknown parameter name or invalid parameter value
```

And here's the configuration of my stream:

`output.icecast(%opus(samplerate=48000, bitrate=24, vbr="none", application="voip", channels=2, signal="music", complexity=10, max_bandwidth="wide_band"), id="local_1", host = "127.0.0.1", port = 8020, password = "n0n3_0f_y0ur_b00siness_xP", mount = "/32", name = "opus eksperymenty", description = "", genre = "", public = false, encoding = "UTF-8", icy_metadata="true", radio)`

**Comment by SC2Mitch** [comment]
Use the template, please.

**Comment by ivellios1988** [comment]
Thanks @SC2Mitch. I corrected my first post.

**Comment by SC2Mitch** [comment]
This is a upstream issue as noted by Vaayn, I'm unsure if this is fixed in the large Liquidsoap update, but we have no idea when that'll come, unfortunately. You can always post a GH issue there as well to see what they say for possible alternatives for the time being.

**Comment by toots** [comment]
Hi! With `channels=1` you should wrap the source in a `mean()` operator to make sure it is converted to mono:
```
s = ...

s = mean(s)

output.icecast(%opus(channels=1, ...), ...)
```

Does that help?

PS: I believe the need to explicitly convert channels like this should go away with `2.0.0`.

**Comment by ivellios1988** [comment]
Unfortunately, changing channels=2 to channels=1 makes Liquidsoap fail to start. And I always make sure to correctly wrap the source in ().

**Comment by ivellios1988** [comment]
Thanks a lot @toots , now it works like a charm!
