### ISSUE TITLE
Some reports not showing

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#4276]
I am not able to get a report of Last 7 Days and Last 30 Days in Rolling Release. It shows nothing.
This issue happened since previous releases and still persists.

**Comment by SlvrEagle23** [comment]
@stardevelop Need logs. Follow the template.

**Comment by stardevelop** [comment]
**Using Docker installation method?**
Yes

**AzuraCast version:**
Rolling Release #553c8bd (2021-06-10 23:28) • Docker • PHP 8.0

**Host Operating System:**
Ubuntu 20.04

**Describe the bug:**
Last 7 Days and Last 30 Days not showing. Nothing is showed after choosing time frame.
Today and Yesterday reports are showed correctly.

**Steps to reproduce:**
Reports > Select Last 7 Days

**Expected behavior:**
Showing report

**Comment by SC2Mitch** [comment]
This appears to be working fine for me, unable to replicate this issue. 

https://puu.sh/HO4Um/c140499c87.png - https://puu.sh/HO4UI/a3ac3fd17b.png

Without any logs of the issue I got no idea. 

To collect logs, check either Docker logs, or the browser network console and refresh the page. Example below. 
![image](https://user-images.githubusercontent.com/29955942/121685542-f6994d80-cab7-11eb-9a23-1bb15b63ec80.png)

**Comment by stardevelop** [comment]
There are not errors in the logs.

**Comment by SC2Mitch** [comment]
check the browser network tab, refresh the page, and check to see if theres any errors.

**Comment by SC2Mitch** [comment]
Closing in favor of https://github.com/AzuraCast/AzuraCast/issues/4279 as it has logs and way more detail.
