### ISSUE TITLE
Need Help ASAP

### ISSUE THREAD

**Issue by theblindadvocacyradio** [AzuraCast/AzuraCast#4278]
I am using StationPlaylist Studio as my broadcast software to stream to Azuracast via the source password. I am having a major issue that needs solving as soon as possible.

I am trying to set up a DJ Account to livestream to the server. Like I said, I already set up the source password to stream from the StationPlaylist Studio software from another remote server. When I entered the DJ account information, it won't connect. I tried everything. I even tried the ShoutCast mode. It still won't connect. I am using the latest Rolling Release, with Debian 10. My question is, can a DJ take over the stream where the source is streaming?

Thank you.

**Comment by SC2Mitch** [comment]
Need some kind of logs here, bud. Template would be nice too.

**Comment by ivellios1988** [comment]
Check the logs to see if the software on your server 'sees' that someone tries to connect.

**Comment by SlvrEagle23** [comment]
@theblindadvocacyradio Yes, a streamer can definitely connect while the AutoDJ is streaming; the software is absolutely built to handle that and transition to the live DJ source, then back to the regular one.

I would make sure you're connecting via the connection information provided on the "Streamers/DJs" page of AzuraCast. It isn't advisable to give streamers the source password for the public broadcasting mount point, but instead to set up a new account for them to connect to via our own Streamer/DJ system, which supports both Icecast and SHOUTcast connection formats.

**Comment by ivellios1988** [comment]
Check if your ports for streamers are open. You may use a tool such as this: https://www.yougetsignal.com/tools/open-ports/

Try opening your ports using _ufw_ command.

I had a similar problem a couple of days ago, I tried to connect but AzuraCast didn't 'see' me. Tried opening ports and connecting again - no success. Probably there was something terribly wrong with my system because I completely reinstalled Ubuntu 18.04 and AzuraCast and since then the issue is gone.

**Comment by theblindadvocacyradio** [comment]
Update: I have moved to a new server. Here is some of the logs. It now disconnects and connects. Then, it disconnects again.

2021/09/03 00:05:13 [live_fallback:3] Switch to requests_fallback with transition.
2021/09/03 00:05:13 [dummy:3] Source failed (no more tracks) stopping output...
2021/09/03 00:05:13 [lang:3] AzuraCast Feedback Response: OK
2021/09/03 00:05:16 [live_fallback:3] Switch to audio_to_stereo_38805 with transition.
2021/09/03 00:05:50 [live_fallback:3] Switch to requests_fallback with transition.
2021/09/03 00:05:50 [dummy:3] Source failed (no more tracks) stopping output...
2021/09/03 00:05:51 [lang:3] AzuraCast Feedback Response: OK
2021/09/03 00:05:52 [ffmpeg:3] [mp3float @ 0x7f8bd41252c0] Could not update timestamps for discarded samples.
2021/09/03 00:05:53 [next_song:3] Prepared "/var/azuracast/stations/personalradio/media/resources_30_second_promo.mp3" (RID 3).
2021/09/03 00:05:53 [ffmpeg:3] [mp3float @ 0x7f8bd41268c0] Could not update timestamps for skipped samples.
2021/09/03 00:05:53 [lang:3] AzuraCast Feedback Response: OK
2021/09/03 00:05:53 [live_fallback:3] Switch to audio_to_stereo_38805 with transition.
2021/09/03 00:06:00 [live_fallback:3] Switch to requests_fallback with transition.
2021/09/03 00:06:00 [dummy:3] Source failed (no more tracks) stopping output...
2021/09/03 00:06:00 [lang:3] AzuraCast Feedback Response: OK
2021/09/03 00:06:03 [live_fallback:3] Switch to audio_to_stereo_38805 with transition.

**Comment by SlvrEagle23** [comment]
@theblindadvocacyradio That sounds like a buffer issue...have you tried updating the station profile to increase the buffer time for live DJs? It adds a bit of delay to the broadcast but it also helps avoid rapid disconnections.

**Comment by theblindadvocacyradio** [comment]
@SlvrEagle23 I tried that. It still disconnects and reconnects. I am using DigitalOcean.

**Comment by SlvrEagle23** [comment]
@theblindadvocacyradio What DJ software are you using? Updating the buffer is one of the only few ways we have to fix issues like this, so it may be specific to your DJ software.

**Comment by theblindadvocacyradio** [comment]
I am using StationPlaylist Software.

**Comment by theblindadvocacyradio** [comment]
@SlvrEagle23 I just sent an email to the developer of StationPlaylist. Hopefully, something can be fixed.
