### ISSUE TITLE
Viewing large listening data causes significant slowdowns and MySQL Deadlocks

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#4279]
**Using Docker installation method?**
Yes

**AzuraCast version:**
Rolling Release #9488a2e (2021-06-09 1:38) •

**Host Operating System:**
Ubuntu 20.04 

**Describe the bug:**
One of our users reported significant slowdowns when viewing large listening data pools on his reports. When we pulled the 30 day logs, it was indeed very slow, taking well over 3 minutes to pull the information. This makes the page itself fairly slow and unresponsive until the load is completed. 

**Steps to reproduce:**
Have a large unique listener data set (3000+) 
View the data in the past 30 days
View the network tab and watch how long it takes. 

**Expected behavior:**
The database to load the information successfully.

I believe this issue might be related to MariaDB trying to pull the vast amount of information but there may be some bottlenecks. Along with this, we had the database locking up multiple times while trying to pull the information. 

**Relevant logs:**
```
web_1                      | [2021-06-12T17:02:59.523765+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\DeadlockException: An exception occurred while executing 'INSERT INTO analytics (station_id, type, moment, number_min, number_max, number_avg, number_unique) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [109, "hour", "2021-06-10 00:00:00.000000", 0, 0, "0", 0]:  SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 51 while running console command `sync:run` {"exception":"[object] (Doctrine\\DBAL\\Exception\\DeadlockException(code: 0): An exception occurred while executing 'INSERT INTO analytics (station_id, type, moment, number_min, number_max, number_avg, number_unique) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [109, \"hour\", \"2021-06-10 00:00:00.000000\", 0, 0, \"0\", 0]:\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:51)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /var/azuracast/www/vend
```
**Screenshots:**
![image](https://user-images.githubusercontent.com/29955942/121784069-af8b8500-cba9-11eb-9a13-bd1fc67bfb0e.png) 

**Device(s):**

**Additional context:**

**Comment by SC2Mitch** [comment]
Tagging this as possible bug, as I'm not as experienced in MySQL as the team members, I can provide further logs upon request.

**Comment by SlvrEagle23** [comment]
I've identified a very likely source of both performance deficit and DB lockup...in transitioning to a single "Batch processing" handler for DB queries, the new batch processing handler, regardless of whether the operation was read-only or not, still went through the process of writing changes back to the database (and also wrapped the entire query in a database transaction).

I've replaced it in some important scenarios (song history, listener report, etc) with a read-only version that is far more optimized for these scenarios; that should improve the performance of those pages quite a lot.

**Comment by SC2Mitch** [comment]
a lot better, cheers
