### ISSUE TITLE
 intermittent streaming sound

### ISSUE THREAD

**Issue by istahilagi** [AzuraCast/AzuraCast#4282]
**Using Docker installation method?**
 Yes 

**AzuraCast version:**
v0.12.4 for Stable Releases

**Host Operating System:**
Ubuntu 20.04

**Describe the bug:**
 intermittent streaming sound in all my stations. this is the sample
http://sx.alhasmedia.com:8160/radio

and many of my stations are written offline streaming, even though auto dj is running

**Comment by Vaalyn** [comment]
According to the response of `http://sx.alhasmedia.com/api/nowplaying` you have 33 stations on that server.

What's your hardware?
What's the load shown to you by the `htop` or `top` command?

Could you post the Liquidsoap log of that station?

This looks like a resource problem to me.

**Comment by istahilagi** [comment]
%Cpu(s): 15.4 us,  1.4 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.9 si, 82.3 st
MiB Mem :   7961.6 total,   3793.9 free,   3134.3 used,   1033.4 buff/cache
MiB Swap:   2048.0 total,   2048.0 free,      0.0 used.   4516.6 avail Mem
4 vCPU Cores
8 GB RAM
200 GB SSD


this happens not only at one station, but all..


2021/06/13 09:03:58 [clock.wallclock_main:2] We must catchup 55.76 seconds!
2021/06/13 09:03:59 [clock.wallclock_main:2] We must catchup 56.67 seconds!
2021/06/13 09:04:01 [clock.wallclock_main:2] We must catchup 57.55 seconds!
2021/06/13 09:04:02 [clock.wallclock_main:2] We must catchup 58.92 seconds!
2021/06/13 09:04:04 [clock.wallclock_main:2] Too much latency! Resetting active sources...
2021/06/13 09:04:04 [local_1:3] Closing connection...
2021/06/13 09:04:04 [local_1:3] Connecting mount /radio for source@127.0.0.1...
2021/06/13 09:04:04 [local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/06/13 09:04:04 [local_1:3] Will try again in 3.00 sec.
2021/06/13 09:04:09 [local_1:3] Connecting mount /radio for source@127.0.0.1...
2021/06/13 09:04:09 [local_1:3] Connection setup was successful.
2021/06/13 09:04:09 [clock.wallclock_main:2] We must catchup 2.53 seconds!

**Comment by Vaalyn** [comment]
Yep your system is overloaded by something.

You CPU has an `st` of `82.3%`.

The `st` shows the percentage of time spent in involuntary wait by the virtual CPU while the hypervisor was servicing another virtual processor.

This is usually the case when you run multiple VMs on a single server and one of those is using up all the resources of if you have rented a VM from a hoster they could throttle VMs that are using to much CPU in a short amount of time.

**Comment by istahilagi** [comment]
I have another server with the same specs... the others are not overloaded even though there are more than 40 stations

**Comment by SlvrEagle23** [comment]
> I have another server with the same specs... the others are not overloaded even though there are more than 40 stations

Yep, what's happened is this particular VPS has hit 100% CPU for too long, and the hosting provider has throttled its overall CPU. The telltale indicator of this is that stolen CPU percentage, which makes it slow to a crawl.

One resolution we found was to completely power-off the VPS via the web UI (not just via `shutdown`), let it power off, and then power it back on...that sometimes fixed the throttling.

Other times, the only resolution is to move to a dedicated-CPU plan for that VPS.

**Comment by istahilagi** [comment]
what is the reasonable limit of the percentage of st that should be?

**Comment by SlvrEagle23** [comment]
I don't know that there's a reasonable limit...basically that "st" statistic indicates CPU power that's being "stolen" from your VPS and used elsewhere. If that number gets high enough, or you're suddenly throttled by your hosting provider (which frequently happens for users on "shared CPU" plans), it can be too much for you to be able to keep stable broadcasts going. A lot of VPS providers will deliberately throttle a high-CPU-consuming customer by 'stealing' a part of the CPU resources back, preventing them from possibly using so many resources that they cause downtime for other customers on those same CPU cores.

This isn't an AzuraCast problem but rather an infrastructural one for your hosting arrangement. My advice is to transition to a dedicated CPU" hosting plan (if your host offers one), or an actual dedicated server where you have full access to the full hardware on the system.

**Comment by istahilagi** [comment]
I just reinstalled Azurazast.
but still like this. even though I haven't made any stations yet
%Cpu(s):  0.3 us,  1.1 sy,  5.5 ni, 33.6 id,  0.3 wa,  0.0 hi,  0.2 si, 59.0 st
MiB Mem :   7961.7 total,   3025.8 free,    985.6 used,   3950.3 buff/cache
MiB Swap:   2048.0 total,   2048.0 free,      0.0 used.   6688.4 avail Mem

**Comment by SlvrEagle23** [comment]
@istahilagi You reinstalled it on that exact same VPS?

I don't think you're listening to what we're telling you. AzuraCast isn't doing this. This is your _hosting provider_ limiting your CPU availability, which is going to constantly limit your ability to run AzuraCast on that host until you either switch to a "Dedicated CPU" plan or a different host altogether.

This isn't something we're doing or we can help with further beyond just giving you that advice.

**Comment by istahilagi** [comment]
ok sir... thanks a lot for the information... this is very helpful for me... :)
