### ISSUE TITLE
azuracast does not follow playlist sequence when marked sequential

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#4283]
Using Docker installation method?*
yes

AzuraCast version:*
Rolling Release #2f0b109 (2021-05-12 14:31) • Docker • PHP 8.0

Host Operating System:
centos 7

Describe the bug:
Since I started using azuracast, I didn't use azuracast managed mode but manual mode where liquidsoap always managed auto dj. but as i needed to use vignettes for a certain time i ended up switching to auto dj management mode by azuracast and then my problems started. if I schedule a program or several programs and place them sequentially, most of the time the azuracar does not follow the sequence of what I put, either starts wrong or starts right and ends wrong. I've done everything I could do with changes to the list and etc... but the same error of never following the sequence I put always happens.

Img1
https://prnt.sc/156gj02
img2
https://prnt.sc/156gn6u

As you can see in the images above, they are all in the sequence, marked as sequential but the queue never goes right. Sometimes it shows all files but everything out of sequence as 2,1,4,3

**Comment by SC2Mitch** [comment]
https://github.com/AzuraCast/AzuraCast/issues/4170
