### ISSUE TITLE
Wrong statistics order

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#4284]
**Using Docker installation method?**
Yes

**AzuraCast version:**
Rolling Release #9488a2e (2021-06-09 1:38)

**Host Operating System:**
Ubuntu 20.04

**Describe the bug:**
Hey.
I've noticed for a while now that Average Listeners and Unique Listeners have the listeners displayed upside down, which is pretty fatal when you have to deliver these numbers to the relevant authorities:
For example, my backup stream in the second screenshot doesn't exist at all (June 13) but at the back of the start (January 31) it does - so exactly once reversed (mainly for new stations).

**Screenshots:**
![Wrong Statistics](https://user-images.githubusercontent.com/42640247/121804747-342ce080-cc48-11eb-82d2-e3a4d9d353ce.jpg)
![Wrong Statistics2](https://user-images.githubusercontent.com/42640247/121804796-65a5ac00-cc48-11eb-8553-e502bd909586.jpg)

**Comment by SlvrEagle23** [comment]
@Abqehebter Which screenshot corresponds to which report?

Unique Listeners should always be quite a bit higher than average. I'm not seeing the reports flipped in my local installation.

**Comment by Abqehebter** [comment]
@SlvrEagle23 Both refer to the unique listener statistics - but is also the case for the average listener.

Can you try to create a new station? For previously created stations it works as it should, just not for newer ones (For me at least).

**Comment by Abqehebter** [comment]
Or is it in the possible range that the numbers "disappear" backwards when you reduce the title storage period?

For example, the normal listener numbers are then also reduced in the station statistics.

**Comment by Abqehebter** [comment]
Seems to be fixed with "newer versions" of the table, since you now see each station individually.
//Close
