### ISSUE TITLE
Cloning station error  `A new entity was found through the relationship`

### ISSUE THREAD

**Issue by YosefAdPro** [AzuraCast/AzuraCast#4285]
**Using Docker installation method?**

Yes
**AzuraCast version:**

 Rolling Release #a35b456

**Host Operating System:**

U 20.4
**Describe the bug:**

When attempting to duplicate a station the error is received:
```
AzuraCast.ERROR: A new entity was found through the relationship 'App\Entity\StationPlaylistFolder#station' that was not configured to cascade persist operations for entity: להיטים. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). {"file":"/var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php","line":114,"code":0} []
```

In fact the duplication takes place and a station is created, but the playlists and other definitions are not duplicated.

In the same matter:
https://github.com/AzuraCast/AzuraCast/issues/3958
https://github.com/AzuraCast/AzuraCast/issues/4262

**Steps to reproduce:**

**Expected behavior:**

**Relevant logs:**

**Screenshots:**

![image](https://user-images.githubusercontent.com/11810187/121818939-15077080-cc93-11eb-9073-4bc9ebe8f55e.png)

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context:**

**Comment by SlvrEagle23** [comment]
@YosefAdPro Found and fixed a possible cause of this in the latest rolling update.

**Comment by YosefAdPro** [comment]
@SlvrEagle23 I can confirm that after the update it is OK!
Closes this issue.
Thank you!
