### ISSUE TITLE
backup file size is too small....

### ISSUE THREAD

**Issue by istahilagi** [AzuraCast/AzuraCast#4286]
**Using Docker installation method?**
Yes

**AzuraCast version:**
0.12.4 for Stable Releases

**Host Operating System:**
Ubuntu 20.04, 

**Describe the bug:**
after performing a backup with media included, I found the backup file to be very small.
how can i do a restore if the files i backed up are just this:

root@vmi553712:/var/azuracast# ls -la
total 24016
drwxr-xr-x  2 root root     4096 Jun 13 14:38 .
drwxr-xr-x 12 root root     4096 Mar 28 02:09 ..
-rw-r--r--  1 root root     4427 Mar 28 02:15 azuracast.env
-rw-r--r--  1 root root     7497 Mar 28 02:15 docker-compose.yml
-rwxr-xr-x  1 root root    16908 Jun  5 21:30 docker.sh
-rw-r--r--  1 root root      225 Apr 13 02:00 .env
-rw-r--r--  1 root root 21625344 Jun 13 14:39 path-to-backup.zip
-rw-r--r--  1 root root  2914816 Jun 13 14:18 radio.zip

I back it up on the radio.zip file

by doing the command:
./docker.sh backup radio.zip

**Expected behavior:**
I want to successfully restore the backup

**Relevant logs:**
```
root@vmi553712:/var/azuracast# ls -lh
total 24M
-rw-r--r-- 1 root root 4.4K Mar 28 02:15 azuracast.env
-rw-r--r-- 1 root root 7.4K Mar 28 02:15 docker-compose.yml
-rwxr-xr-x 1 root root  17K Jun  5 21:30 docker.sh
-rw-r--r-- 1 root root  21M Jun 13 14:39 path-to-backup.zip
-rw-r--r-- 1 root root 2.8M Jun 13 14:18 radio.zip



**Device(s):**



**Additional context:**
Please help me

**Comment by SC2Mitch** [comment]
You might of made a mistake with the backup, the backup files do indeed appear to be too small. Have you tried running the backup through the Web Interface?

**Comment by istahilagi** [comment]
when I do a backup via the web, I can't find the file in ssh putty... I can't even go to the backups folder

**Comment by SC2Mitch** [comment]
you can find the file in `/var/lib/docker/volumes/azuracast_backups/_data`

**Comment by istahilagi** [comment]
it worked....thank you very much 👍 :)

**Comment by SC2Mitch** [comment]
Nice to see it's fixed, closed.
