### ISSUE TITLE
Problems following sequential playlist

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#4289]
I previously informed about a possible problem with the sequential playlist managed by the azuracast panel. If I mark the management done by liquidaoap the sequence works very well, but if I unmark and let azuracast manage it messes everything up, it doesn't follow the playlist in the sequence or if it does the sequence it doesn't make it complete, if the list has 6 files that must follow sequence it sometimes cuts the first or middle or last and puts files out or simply doesn't put anything. I've reinstalled azura cast, tested it on two servers and it always has the same problem, when you have many playlists scheduled.

**Comment by SC2Mitch** [comment]
Most likely a duplicate, we are aware of Liquidsoap issues, we have numerous issues on this topic already posted.
