### ISSUE TITLE
API `POST` /admin/stations does not return `media_storage_location_id`

### ISSUE THREAD

**Issue by ArronUnmuted** [AzuraCast/AzuraCast#4290]
**Using Docker installation method?**
Yes

**AzuraCast version:**
#462759b12216633d07ea5916fb649af578091b61

**Host Operating System:**
Ubuntu 20.04.1 LTS

**Describe the bug:**
A `POST` request to `/admin/stations` to create a new station does not return the `media_storage_location_id` so it is not possible to `PUT` request a `storage_quota` to the created `storage_location`.

**Steps to reproduce:**
`POST` request `/admin/stations` - no `media_storage_location_id` is returned.

**Expected behavior:**
Expect the `media_storage_location_id` to be returned. 

**Additional context:**
@SlvrEagle23 said that the expected behaviour was:
![image](https://user-images.githubusercontent.com/80755435/122049356-3e7ee400-cdda-11eb-93f6-7676e05c1f68.png)

**Comment by SlvrEagle23** [comment]
@ArronUnmuted I'm looking at this locally, and it looks like `media_storage_location`, `recordings_storage_location` and `podcasts_storage_location` are all being returned as populated arrays, i.e. you should be able to call `media_storage_location.id` to get that storage location's ID (to thus manage its quota). Is that not working on POST?

**Comment by AaronUnmuted** [comment]
For reference - this appears to be resolved and this can be closed!
