### ISSUE TITLE
Prefer Browser URL not working

### ISSUE THREAD

**Issue by istahilagi** [AzuraCast/AzuraCast#4291]
**Using Docker installation method?**
 Yes 

**AzuraCast version:**
Rolling Release #bd040c6 (2021-06-14 21:24)

**Host Operating System:**
Ubuntu 20.04, 

**Describe the bug:**
in the "Prefer Browser URL"
If this setting is set to "Yes", the browser URL will be used instead of the base URL when it's available. 

I chose yes, but in the profile it still uses the base url when I access via another subdomain.

this happened after migrating the server and restoring the backup from the old server.

this is the picture i experienced https://alhasmedia.com/profil.JPG

**Expected behavior:**

**Relevant logs:**

**Screenshots:**
https://alhasmedia.com/profil.JPG

**Additional context:**

**Comment by SC2Mitch** [comment]
have you tried unticking the box, saving, then trying it again?

**Comment by istahilagi** [comment]
I've tried, but it doesn't work

**Comment by SlvrEagle23** [comment]
@istahilagi There were several areas in the code causing this, but they should all be fixed now. Thank you for the report!

**Comment by istahilagi** [comment]
so what should i do next...
thank you

**Comment by SlvrEagle23** [comment]
@istahilagi Update your installation to the latest "Rolling Release" version and it should be fixed.

**Comment by istahilagi** [comment]
it worked, thank you very much 👍
