### ISSUE TITLE
Can't Enabling HTTPS with LetsEncrypt

### ISSUE THREAD

**Issue by istahilagi** [AzuraCast/AzuraCast#4294]
**Using Docker installation method?**
Yes 

**AzuraCast version:**
Rolling Release #1e15b3b (2021-06-15 21:54) 

**Host Operating System:**
Ubuntu 18.04,

**Describe the bug:**
I have implemented the method here,
https://docs.azuracast.com/en/administration/ssl-and-lets-encrypt
on PuTTY it says it worked
But still can't Enable HTTPS on my sub domain sx.alhastream.com
please help with this problem

**Relevant logs:**

 docker-compose logs nginx_proxy_letsencrypt
Attaching to nginx_proxy_letsencrypt
nginx_proxy_letsencrypt    | Info: running letsencrypt-nginx-proxy-companion ver                                  sion v2.0.2
nginx_proxy_letsencrypt    | Info: Custom Diffie-Hellman group found, generation                                   skipped.
nginx_proxy_letsencrypt    | Reloading nginx proxy (cdb6a9d86db53af30e792b5a246c                                  8e0a617b591139b1bd8ebe03e409866f81cf)...
nginx_proxy_letsencrypt    | 2021/06/15 23:05:19 Contents of /etc/nginx/conf.d/d                                  efault.conf did not change. Skipping notification ''
nginx_proxy_letsencrypt    | 2021/06/15 23:05:19 [warn] 50#50: duplicate MIME ty                                  pe "text/css" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/06/15 23:05:19 [warn] 50#50: duplicate MIME ty                                  pe "application/javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/06/15 23:05:19 [warn] 50#50: duplicate MIME ty                                  pe "application/json" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/06/15 23:05:19 [warn] 50#50: duplicate MIME ty                                  pe "application/x-javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/06/15 23:05:19 [warn] 50#50: duplicate MIME ty                                  pe "text/xml" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/06/15 23:05:19 [warn] 50#50: duplicate MIME ty                                  pe "application/xml" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/06/15 23:05:19 [warn] 50#50: duplicate MIME ty                                  pe "application/xml+rss" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/06/15 23:05:19 [warn] 50#50: duplicate MIME ty                                  pe "text/javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/06/15 23:05:19 [notice] 50#50: signal process                                   started
nginx_proxy_letsencrypt    | 2021/06/15 23:05:20 Generated '/app/letsencrypt_ser                                  vice_data' from 6 containers
nginx_proxy_letsencrypt    | 2021/06/15 23:05:20 Running '/app/signal_le_service                                  '
nginx_proxy_letsencrypt    | 2021/06/15 23:05:20 Watching docker events
nginx_proxy_letsencrypt    | Reloading nginx proxy (cdb6a9d86db53af30e792b5a246c                                  8e0a617b591139b1bd8ebe03e409866f81cf)...
nginx_proxy_letsencrypt    | 2021/06/15 23:05:22 Contents of /etc/nginx/conf.d/d                                  efault.conf did not change. Skipping notification ''
nginx_proxy_letsencrypt    | 2021/06/15 23:05:23 Contents of /app/letsencrypt_se                                  rvice_data did not change. Skipping notification '/app/signal_le_service'
nginx_proxy_letsencrypt    | 2021/06/15 23:05:22 [warn] 77#77: duplicate MIME ty                                  pe "text/css" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/06/15 23:05:22 [warn] 77#77: duplicate MIME ty                                  pe "application/javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/06/15 23:05:22 [warn] 77#77: duplicate MIME ty                                  pe "application/json" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/06/15 23:05:22 [warn] 77#77: duplicate MIME ty                                  pe "application/x-javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/06/15 23:05:22 [warn] 77#77: duplicate MIME ty                                  pe "text/xml" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/06/15 23:05:22 [warn] 77#77: duplicate MIME ty                                  pe "application/xml" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/06/15 23:05:22 [warn] 77#77: duplicate MIME ty                                  pe "application/xml+rss" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/06/15 23:05:22 [warn] 77#77: duplicate MIME ty                                  pe "text/javascript" in /etc/nginx/conf.d/default.conf:32
nginx_proxy_letsencrypt    | 2021/06/15 23:05:22 [notice] 77#77: signal process                                   started
nginx_proxy_letsencrypt    | Creating/renewal sx.alhasmedia.com certificates...                                   (sx.alhasmedia.com)
nginx_proxy_letsencrypt    | [Tue Jun 15 23:05:24 UTC 2021] Using CA: https://ac                                  me-v02.api.letsencrypt.org/directory
nginx_proxy_letsencrypt    | [Tue Jun 15 23:05:24 UTC 2021] Creating domain key
nginx_proxy_letsencrypt    | [Tue Jun 15 23:05:25 UTC 2021] The domain key is he                                  re: /etc/acme.sh/istahilagi@yahoo.com/sx.alhasmedia.com/sx.alhasmedia.com.key
nginx_proxy_letsencrypt    | [Tue Jun 15 23:05:25 UTC 2021] Single domain='sx.alhasmedia.com'
nginx_proxy_letsencrypt    | [Tue Jun 15 23:05:25 UTC 2021] Getting domain auth                                   token for each domain
nginx_proxy_letsencrypt    | [Tue Jun 15 23:05:27 UTC 2021] Create new order err                                  or. Le_OrderFinalize not found. {
nginx_proxy_letsencrypt    |   "type": "urn:ietf:params:acme:error:rateLimited",
nginx_proxy_letsencrypt    |   "detail": "Error creating new order :: too many c                                  ertificates (5) already issued for this exact set of domains in the last 168 hou                                  rs: sx.alhasmedia.com: see https://letsencrypt.org/docs/rate-limits/",

**Steps to reproduce:**

**Screenshots:**

**Comment by ivellios1988** [comment]
Have you tried with different domain/subdomain?

**Comment by Vaalyn** [comment]
You will need to wait some time since you have hit the rate limit of Let's Encrypts API:

`Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: sx.alhasmedia.com`

You can read more about rate limits of Let's Encrypt here on their website: https://letsencrypt.org/docs/rate-limits/

The most important part of that website:

> If you’ve hit a rate limit, we don’t have a way to temporarily reset it. You’ll need to wait until the rate limit expires after a week.

**Comment by istahilagi** [comment]
> Have you tried with different domain/subdomain?
I haven't tried it yet, while I don't want to switch domains. 


> You will need to wait some time since you have hit the rate limit of Let's Encrypts API:
> 
> `Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: sx.alhasmedia.com`
> 
> You can read more about rate limits of Let's Encrypt here on their website: https://letsencrypt.org/docs/rate-limits/
> 
> The most important part of that website:
> 
> > If you’ve hit a rate limit, we don’t have a way to temporarily reset it. You’ll need to wait until the rate limit expires after a week.

oh, oke sir, thanks for the info :)
