### ISSUE TITLE
Podcast Error

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#4295]
**Using Docker installation method?**
Yes

**AzuraCast version:**
0.13.0 Stable

**Host Operating System:**
Ubuntu 20.04

**Describe the bug:**
When posting the podcasts, errors are occurring as per the attached images. I'm only being allowed to post small files, I've tried to upload an hour-long podcast and the message "undefined" appears. I tried to upload a file with the extension "M4A" as instructed and also got an error.

Error 1
![indefinido](https://user-images.githubusercontent.com/58113324/122266032-ba972b80-ceaf-11eb-9a2c-72f75416ec90.jpg)

Error 2
![m4a](https://user-images.githubusercontent.com/58113324/122266054-c2ef6680-ceaf-11eb-8f18-f007cb3d703e.jpg)

**Comment by SC2Mitch** [comment]
How big was these files you was attempting to upload?

**Comment by roger-net** [comment]
> How big was these files you was attempting to upload?

Approximately 50MB.

**Comment by LATINMIXMASTERS** [comment]
Yes I think that the issue is  file size set up on the script is low maybe need to be put like 60mb to 100mb since all podcast are around 1hr long and more. I have put up to 15 minutes mp3 files 20 megabytes and work so if possible will be good to have an area to adjust the file size.

**Comment by SC2Mitch** [comment]
Can you check now on the latest rolling release @roger-net

**Comment by SlvrEagle23** [comment]
This might not be fixed yet, as I'm still working on implementing split uploads for the larger media. Expect to see that in Rolling Release shortly, with an upload process similar to the Media manager.

**Comment by SlvrEagle23** [comment]
Update: The latest Rolling Release version incorporates improvements I've been working on to allow our "chunked" multipart uploads, the same style we use when uploading files via the Media Manager, to work elsewhere in the system, and this is now how media is uploaded for podcast episodes. If you update, you should no longer find yourself up against upload size limits even when uploading rather large files.
