### ISSUE TITLE
AzuraCast API doesn't recognize Live stream

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#4298]
**Using Docker installation method?**
No

**AzuraCast version:**
Rolling Release #133a943 (2021-06-16 19:34)

**Host Operating System:**
Ubuntu 20.04.02

**Describe the bug:**
So i made major update (didn't update 2 months).
Now i tested everything is it working, and realize, that the API doesn't recognize when it's streaming.
I'm connecting successfully. Audio is playing, ID3 is sent and showing correct EXCEPT:
```
"live": {
        "is_live": false,
        "streamer_name": "",
        "broadcast_start": null
    },
```
in `http://ip/api/nowplaying/1`
It always shows that the is_live is false. I've setup some mine APIs to check for that variable, and since is not changing, mine API doesn't work neither :(

EDIT: + Another problem. It doesn't RECORD the live streams. Maybe it's because the problem above.

EDIT2: Oh my god... i just realized something worse. The API is correct, it's working and recording. Ignore the things above... BUT.... I just realized, that i've been made a typo with the username. The username WAS WRONG, and it lets me stream. And because of that the username isn't in the DJ's table, doesn't show that it's live. After i fix the username, it show `is_live: true`, but the DJ isn't presented in artist field (like before):
```
"live": {
        "is_live": true,
        "streamer_name": "Nicox",
        "broadcast_start": 1623921143
    },
    "now_playing": {
        "elapsed": 136,
        "remaining": 0,
        "sh_id": 24094,
        "played_at": 1623921158,
        "duration": 0,
        "playlist": "",
        "streamer": "Nicox",
        "is_request": false,
        "song": {
            "id": "7c97bb4b86d77bce715f407d3a90b56d",
            "text": " - LadioCast 0.13.0",
            "artist": "",
            "title": "LadioCast 0.13.0",
            "album": "",
            "genre": "",
            "lyrics": "",
            "art": "",
            "custom_fields": []
        }
    },
```
And the text is ` - LadioCast 0.13.0` instead `Nicox - LadioCast 0.13.0`.

And the password isn't `dj_username:dj_password or dj_username,dj_password` it's just `dj_password`

**Device(s):**
- Device: Raspberry Pi 3b

**Comment by PaulMaur** [comment]
The Ansible is not supported so there is no support for that either, which is not difficult to understand

**Comment by NicoxDJ** [comment]
Don't worry @PaulMaur, this absolutely doesn't matter :) It's about the code part, not about the system preferences.

**Comment by SC2Mitch** [comment]
> The Ansible is not supported so there is no support for that either, which is not difficult to understand
@PaulMaur 
Please be respectful of other users when making these remarks, we foster a all inclusive family here, everyone is welcome, regardless of installation options, review our Code of Conduct before making further remarks on other peoples issues. 

https://docs.azuracast.com/en/contribute/code-of-conduct
