### ISSUE TITLE
API recognized unsafe by web browsers

### ISSUE THREAD

**Issue by PinguiFabgeeklab** [AzuraCast/AzuraCast#4299]
**Using Docker installation method?** Yes

**AzuraCast version:**  v0.13.0 Stable

**Host Operating System:**  Ubuntu 18.04

**Describe the bug:** 
Hey, 
I made a player for my radio but Edge, Firefox have recognized him like unsafe and most precisely the API. LetsEncrypt is enabled so I'm a little bit lost and I don't now how to resolve this.
 

**Steps to reproduce:**

**Device(s):**

- Device:  Many devices
- OS:  Windows, Android & iOS
- Browser:  All

**Comment by SC2Mitch** [comment]
Need some pictures of logs please

**Comment by PinguiFabgeeklab** [comment]
I have to show you what logs ?

**Comment by SC2Mitch** [comment]
Sorry typo, can you show us a picture of the error your getting, and check the docker logs for any errors when you run into the unsafe page?

I'm wondering if the HTTPS wasn't setup correctly

**Comment by PinguiFabgeeklab** [comment]
![api](https://user-images.githubusercontent.com/78692586/122384311-deb84280-cf6b-11eb-98b3-09618a734801.PNG)
![player](https://user-images.githubusercontent.com/78692586/122384314-df50d900-cf6b-11eb-89b1-a9e8b6fff467.PNG)

First, API screen and player screen

**Comment by PinguiFabgeeklab** [comment]
![logs_putty](https://user-images.githubusercontent.com/78692586/122385154-bbda5e00-cf6c-11eb-8284-8d5e107c9421.PNG)
And here there are logs

**Comment by SC2Mitch** [comment]
I'm looking at your certificate and it appears to be mapped to the localhost, instead of the actual website. 

![image](https://user-images.githubusercontent.com/29955942/122415743-14ffbd00-cf80-11eb-9950-3962bb234728.png)

**Comment by PinguiFabgeeklab** [comment]
I know but I don't know how to resolve it :/

**Comment by YosefAdPro** [comment]
> ![api](https://user-images.githubusercontent.com/78692586/122384311-deb84280-cf6b-11eb-98b3-09618a734801.PNG)
> ![player](https://user-images.githubusercontent.com/78692586/122384314-df50d900-cf6b-11eb-89b1-a9e8b6fff467.PNG)
> 
> First, API screen then player screen

Are you sure you defined the address with www?

**Comment by PinguiFabgeeklab** [comment]
It changes nothing

**Comment by PinguiFabgeeklab** [comment]
I have reset my VPS and reinstalled AzuraCast and now there isnt the problem. I close the post
