### ISSUE TITLE
Autodj not working

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#430]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Centos 7

**Describe the issue in full detail, including screenshots if possible:**

I have just installed the latest version and uploaded my musicfiles an created a playlist.
After restarting the station the music files are not played,it keeps playing only the azurast demo file>

Also when editing the mountpoint i do get this error:
500
Call to a member function getId() on null
MountsController.php : 134

**Comment by SlvrEagle23** [comment]
@surihost Regarding the MountsController issue, please don't put more than one request on a single Github issue.

Considering the MountsController issue (which already exists as #405) has recently been resolved, I'm not sure you're updated to the very latest version of the code. Can you run the update script again with the latest version, and verify that the issue still exists?

**Comment by surihost** [comment]
I have just updated, but the problem is still there.Autodj is not working.
I deleted the playlist,created again a new one,restarted but still the same.
Maybe some bug that when creating the paylist it doesnt take take or save the content of the songs?

**Comment by susl16c** [comment]
I just updated, everything works the error was gone, I've had such a mistake before.

**Comment by surihost** [comment]
Yes the 500 error is gone,but the autodj still not working.

**Comment by susl16c** [comment]
With this, I also agree at all it is not clear how it works, if you watch reports, then many songs, he does not lose at all from added ones. Why is it not clear how to make him lose all the songs for me is not clear. Perhaps the author will clarify the situation, I initially thought that it all depends on the rating of the songs.

**Comment by surihost** [comment]
Hope to see a fix for this,still the autodj not working.

**Comment by SlvrEagle23** [comment]
Heh, reading this thread is like watching a contest where both sides are trying to figure out who can understand the other _less_.

@surihost Just telling me "thing isn't working" is not likely to lead to a quick or simple response. Rather than just going in and fixing the relevant error message, I have to type out a long string of diagnostic commands for you to try, then wait for you to try them, etc...if you pursued these diagnostics before submitting the original issue, things will go a lot faster.

In this case (as in many cases with Docker) your debugging process should be to run, inside the AzuraCast folder:
```
docker-compose logs -f stations
```

(If nginx is having trouble, replace "stations" with "nginx"...if it's the web app, replace it with "web", and so on...using the same names as the services in `docker-compose.yml`)

Try restarting the station and see if errors appear. If they do, paste them here.

**Comment by surihost** [comment]
Here the logs:
stations_1     | 2018/02/15 12:29:30 [radio_out_1:3] Will try again in 3.00 sec.
stations_1     | 2018-02-15 12:29:30    ERROR   [SRC 127.0.0.1:47084 sid=1] SHOUTcast 1 source rejected. A source is already connected.
stations_1     | strange error flushing buffer ...
stations_1     | strange error flushing buffer ...
stations_1     | 2018/02/15 12:29:30 main.go:90: Change in content: triggering web hook
stations_1     | 2018/02/15 12:29:34 [radio_out_1:3] Connecting mount sid#1 for @127.0.0.1...
stations_1     | 2018/02/15 12:29:34 [radio_out_1:2] Connection failed: bad answer: Stream In Use
stations_1     | 2018/02/15 12:29:34 [radio_out_1:3] Will try again in 3.00 sec.
stations_1     | 2018-02-15 12:29:34    ERROR   [SRC 127.0.0.1:47148 sid=1] SHOUTcast 1 source rejected. A source is already connected.

**Comment by SlvrEagle23** [comment]
@surihost Do you have two stations trying to use the same port range? Up until fairly recently, cloning a station didn't properly assign it a new radio port, so you may need to make sure stations aren't trying to stack directly on top of each other port-wise.

**Comment by surihost** [comment]
No i dont have stations using the same port.
If i restream on the same station(port)  it works and when i want use playlist to play the songs i have uploaded it doesnt work,only plays the azuracast demo.

**Comment by SlvrEagle23** [comment]
@surihost Per the error, _something_ is getting between the Liquidsoap AutoDJ and the Shoutcast instance. 

I'd start by verifying that there are no other radio sources connected to the same Shoutcast endpoint, and this includes running a command like:

```
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
```

to ensure *all* containers are stopped, then run the usual `docker-compose up -d` to spin the correct ones back up again.

**Comment by surihost** [comment]
Thanks for the help.I reinstalled the vps all fresh again and it's working now.Don't what actually happend i was getting the error.
