### ISSUE TITLE
Install Azuracast with Cyberpanel

### ISSUE THREAD

**Issue by vpsinghbaghel** [AzuraCast/AzuraCast#4306]
Can we run docker version of Azuracast on CyberPanel server through Docker Manager option available in CyberPanel ?

Server Type: VPS
Web Control Panel: CyberPanel
OS: CentOS 7/8 or Ubuntu 18/20.

**Comment by SC2Mitch** [comment]
Hello,

As long as it's not running on ports: (80, 443) It should be able to run fine, we have some documentation to assist you further. 

https://docs.azuracast.com/en/user-guide/troubleshooting

You can always change the ports in the custom .env files we provide.
