### ISSUE TITLE
Error: File Not Processing

### ISSUE THREAD

**Issue by abrahamonyancha** [AzuraCast/AzuraCast#4313]
**Using Docker installation method?**

Yes
**AzuraCast version:**

v0.12.4 Stable • Docker • PHP 8.0
**Host Operating System:**

Ubuntu 20.04
**Describe the bug:**

When I try to upload songs, I get 'File Not Processing' error. I have even tried SFTP, it still gives the 'File Not Processed' error
**Steps to reproduce:**

**Expected behavior:**

**Relevant logs:**

**Screenshots:**

**Device(s):**

- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Version: 90

**Additional context:**

The Problem started after I updated to the current version.

**Comment by Vaalyn** [comment]
Please update your installation to version 0.13.0 and check if the problem remains.
