### ISSUE TITLE
Bug: Songs requested by user does not play jingle before it.

### ISSUE THREAD

**Issue by BlakeB415** [AzuraCast/AzuraCast#4316]
**Using Docker installation method?**

Yes

**AzuraCast version:**

Rolling Release #133a943

**Host Operating System:**

Ubuntu 20.04

**Describe the bug:**

When a user requests a song, it does not add the jingles as it does with AutoDJ.

**Steps to reproduce:**

Make a jingles playlist with "Once per 1 song".
Make a normal song playlist.
Request a song.

**Expected behavior:**

The jingle is supposed to be added in between requested songs and AutoDJ songs.

**Comment by Jaadoo13** [comment]
Oh yes, that would be nice. That i can set a playlist/Song wich will be played directly before the Music wish comes...
So all Listeners knowing that this following Song was a wish.

**Comment by BlakeB415** [comment]
> Oh yes, that would be nice. That i can set a playlist/Song wich will be played directly before the Music wish comes...
> So all Listeners knowing that this following Song was a wish.

Not necessarily, usually, all songs have some sweeper audio that plays before them. Queued and requested songs don't have this for some reason. But that idea would also be neat as well.
