### ISSUE TITLE
after upgrade the version azuracast, init error Nginx

### ISSUE THREAD

**Issue by celsobtu** [AzuraCast/AzuraCast#4317]
**Using Docker installation method?**
Yes

**AzuraCast version:**
2021-02-07 #abcdefg

**Host Operating System:**
Ubuntu 20.04 LTS

**Describe the bug:**
after upgrade the version azuracast, init error Nginx

**Steps to reproduce:**
1. on start ok the azuracast, but not enable in browser

**Expected behavior:**
in linux when starting the azuracast is ok, but it does not enable in the browser, it shows the message nginx 502 Bad Gateway and does not start the connection of the radios.
Looking at the docker-compose logs -f web log, I see the following msg "unable to create open /etc/nginx/conf.d/azuracast.conf: read-only file system /etc/my_init.d/nginx.sh failed with status 1"
but note that the file rights are ok.
![image](https://user-images.githubusercontent.com/1683424/122663071-3faf6880-d16e-11eb-9e48-1d0ce2baf5d3.png)

**Relevant logs:**
*** Killing all processes...
web_1                      | Starting up AzuraCast services...
web_1                      | Services started up and ready!
web_1                      | *** Running /etc/my_init.d/nginx.sh...
web_1                      | 2021/06/20 04:52:13 unable to create open /etc/nginx/conf.d/azuracast.conf: read-only file system
web_1                      | *** /etc/my_init.d/nginx.sh failed with status 1
web_1                      |
web_1                      | *** Killing all processes...
azuracast_web exited with code 1

**Screenshots:**
screenshots in attachment
![image](https://user-images.githubusercontent.com/1683424/122662928-28bc4680-d16d-11eb-876b-104ce006278a.png)

**Comment by SlvrEagle23** [comment]
@celsobtu Do you have any customizations in a separate `docker-compose.override.yml` file?

Also, when updating, make sure if you're prompted to update `docker-compose.yml` that you do so, since it may have changed since your last update. You can re-run the update again to do this if you didn't before.

**Comment by celsobtu** [comment]
Great !
I removed docker-compose.override.yml and everything is fine now
Thank you very much
