### ISSUE TITLE
Adding a new user

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#432]
When adding a new user, an existing user opens to edit, then the question is how to add a new user?
![bdfdfbdf](https://user-images.githubusercontent.com/23697714/36245679-3fb8a290-123d-11e8-9c28-87a227881f08.png)

**Comment by SlvrEagle23** [comment]
This is not a bug at all.

For the entire history of AzuraCast, even dating back to its PVL roots, an `/edit` URL with no ID specified is the equivalent of "Add". This is a byproduct of MVC-style routing that doesn't allow the easy creation of custom route aliases for identical functions.

While I admire your desire to crawl through the application looking for every last possible issue, if you actually clicked the button in question here (whose title attribute is "Add new item") and submitted the form, it would create a new account.

There are certainly some user experience improvements that can be made here, but this is not broken functionality of the application, and is thus rather low priority.

**Comment by SlvrEagle23** [comment]
Per this request, I've reworked the routing scheme to add new `/add` URLs, use friendlier language for the titles of forms that more properly indicates what the form is doing, and added translatable text in multiple locations.
