### ISSUE TITLE
I'm not able to update the Azuracast installation

### ISSUE THREAD

**Issue by arusi01** [AzuraCast/AzuraCast#4321]
AzuraCast • Rolling Release #ccdee79 (2021-04-27 17:51) • Docker • PHP 8.0

Stopping Stations.....

ERROR: for azuracast_stations  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
Error response from daemon: remove azuracast_www_vendor: volume is in use - [723dc77a2838d49c81510ebfbe1525c11a01ac6d896977aca374968aeac835cd]
Error response from daemon: remove azuracast_tmp_data: volume is in use - [723dc77a2838d49c81510ebfbe1525c11a01ac6d896977aca374968aeac835cd, 213fe29c2bd63d304e9d3bb717e653b796113224b07926b8c660b83815fbc366]
Error response from daemon: remove azuracast_redis_data: volume is in use - [595dd5c0dd294b0a2f5b33396fb1cf75467a9d4a26321817dd277cc1e71b825b]
ERROR: for azuracast_stations  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

**Comment by SC2Mitch** [comment]
Need logs and the template filling in.

**Comment by arusi01** [comment]
**Using Docker installation method?** Yes
**AzuraCast version:** Rolling Release #ccdee79 (2021-04-27 17:51)
**Host Operating System:** Debian 10
**Describe the bug:** I'm unable to update the Azuracast installation to the latest version
**Steps to reproduce:**

Login as root
cd /var/azuracast
./docker.sh update-self
./docker.sh update

**Expected behavior:**
Update Azuracast Installation

**Relevant logs:**
root@srv2:~# cd /var/azuracast
root@srv2:/var/azuracast# ./docker.sh update-self
New Docker utility script downloaded.
root@srv2:/var/azuracast# ./docker.sh update
[NOTICE] Before you continue, please make sure you have a recent snapshot of your system and or backed it up.
Are you ready to continue with the update? [Y/n] Y
Pulling mariadb                 ... done
Pulling redis                   ... done
Pulling stations                ... done
Pulling web                     ... done
Pulling nginx_proxy             ... done
Pulling nginx_proxy_letsencrypt ... done
Stopping nginx_proxy_letsencrypt ... done
Stopping nginx_proxy             ... done
Stopping azuracast_web           ... done
Stopping azuracast_stations      ...
Stopping azuracast_redis         ... done
Stopping azuracast_mariadb       ... done

ERROR: for azuracast_stations  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
Error response from daemon: remove azuracast_www_vendor: volume is in use - [723dc77a2838d49c81510ebfbe1525c11a01ac6d896977aca374968aeac835cd]
Error response from daemon: remove azuracast_tmp_data: volume is in use - [723dc77a2838d49c81510ebfbe1525c11a01ac6d896977aca374968aeac835cd, 213fe29c2bd63d304e9d3bb717e653b796113224b07926b8c660b83815fbc366]
Error response from daemon: remove azuracast_redis_data: volume is in use - [595dd5c0dd294b0a2f5b33396fb1cf75467a9d4a26321817dd277cc1e71b825b]
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
Recreating azuracast_stations ... done
Recreating azuracast_redis    ... done
Recreating azuracast_mariadb  ... done
Recreating azuracast_web      ... done
Recreating nginx_proxy        ... done
Recreating nginx_proxy_letsencrypt ... done
Clean up all stopped Docker containers and images to save space? [Y/n] Y
Total reclaimed space: 0B
Update complete!
root@srv2:/var/azuracast#


**Screenshots:**

**Device(s):**

**Additional context:**

**Comment by ivellios1988** [comment]
Same problem here, I'm getting exactly the same error message. My system is Ubuntu 18.04. AzuraCast v0.12.4 Stable

**Comment by PaulMaur** [comment]
The Ansible is not supported so there is no support for that either, which is not difficult to understand
