### ISSUE TITLE
Media file inconsistencies 

### ISSUE THREAD

**Issue by AaronUnmuted** [AzuraCast/AzuraCast#4328]
**Using Docker installation method?**
Yes

**AzuraCast version:**
v0.13.0 Stable

**Host Operating System:**
Ubuntu 20.04

**Describe the bug:**
For one particular station, the media file system appears to be broken.  The amount of files seems to differ depending on what source of information you're looking at. See screenshots below. The media sync task appears to be completing without issue. However, this particular installation of AzuraCast runs on a VM and at least once per day, the VM will freeze up, Nginx will show a 500 error and we will be unable to access the VM via SSH. I'm not sure if these two issues are related? 

**Expected behavior:**
Media file count should be accurate in all places after sync task. 

**Screenshots:**
http://prntscr.com/1673199
http://prntscr.com/167341w
SFTP: http://prntscr.com/167381i

**Comment by SC2Mitch** [comment]
Have you fully cleared the cache from your machine via the system settings? I'm wondering if this is a cache or a issue with the recent implementation of the file system changes.

**Comment by AaronUnmuted** [comment]
> Have you fully cleared the cache from your machine via the system settings? I'm wondering if this is a cache or a issue with the recent implementation of the file system changes.

I've just tried clearing the cache both via Docker & via the admin panel to no avail. The issue persists.

**Comment by Marcioghiraldelli** [comment]
fter I upgraded to the latest version I can't send files through the panel either, only through the filezilla sftp.

**Comment by Vaalyn** [comment]
For both, the media list not loading as well as the failed uploads, we need logs. Most importantly the error from the failed requests in the browsers dev consoles "Network" tab and the JS error logs. The "AzuraCast Application Log" would also be helpful.

**Comment by AaronUnmuted** [comment]
Console error when loading Music Files - http://prntscr.com/16bia84
Network error when loading Music Files - http://prntscr.com/16bih2y

AzuraCast Application Log attached.
[azuracast-log.txt](https://github.com/AzuraCast/AzuraCast/files/6693996/azuracast-log.txt)
This log might not be overly helpful as we've recently had to restart the VM due to the issue described above. 

From what I can see, looks like an issue with a specific file?

**Comment by Marcioghiraldelli** [comment]
In the example azuracast itself, the direct upload from the browser does not work either. The upload bar doesn't appear, you select the file, it shows the upload bar quickly and then it looks like this in the image below. Upload only works by filezilla.

error upload : https://prnt.sc/16bx13o

**Comment by SC2Mitch** [comment]
On the recent rolling release, I'm unable to verify these issues, is it possible for you to update to the rolling branch?

**Comment by Marcioghiraldelli** [comment]
ok, i did several other tests here, including with older versions of azuracast and i realized that in the last version it did some kind of verification that prevents the file from being sent as I showed in the image above. Already in previous versions it doesn't happen and I can send normally, but this verification that he did when sending via the panel doesn't happen through filezilla, I can send the same file through filezilla but not through the panel. It doesn't load the submission and it's just the file size below the name and nothing happens. What I find strange is that the files are mp3. no special characters.

**Comment by Vaalyn** [comment]
Could you provide me with one of those files that fails to upload for you?

I haven't been able to reproduce this on my test installation nor on the demo installation so I'd like to try with the same file/s that you are having this issue with.

**Comment by SlvrEagle23** [comment]
I'm not sure that we ever got enough information to reliably diagnose this issue and come to any conclusions. It's possible that this issue was caused by a similar smaller bug we ran into that was preventing smaller files from uploading correctly, and it's also possible that other media processing errors were stacking up and causing the problem (which should also be largely resolved as a result of our recent emphasis on building solutions to these problems into the application), but if the issue persists on the latest Rolling Release version, please let us know along with accompanying logs.
