### ISSUE TITLE
Liquidsoap search for nonexisting files and crash the server

### ISSUE THREAD

**Issue by rquara** [AzuraCast/AzuraCast#4329]
**Using Docker installation method?**
Yes

**AzuraCast version:**
Rolling Release #bd040c6 (2021-06-14 21:24) • Docker • PHP 8.0

**Host Operating System:**
Ubuntu 20.04

**Describe the bug:**
Liquidsoap search for lots of old files that are not existing anymore generating a spike in CPU utilization that crash the server putting the radio offline for about 5 to 10 minutes. 
It happens at least once a day (almost always at the same time) since a couple of weeks. 
The files searched are not existing on the hard disk and there is no playlist linked with them.
We uploaded and deleted all our mp3 using the azuracast interface from the browser

**Relevant logs:**
https://pastebin.com/Erqk3n2E

**Screenshots:**
The playlists "22 aprile" or "15 giugno" are not existing 
![image](https://user-images.githubusercontent.com/64473163/122892824-06315580-d346-11eb-9cb5-1650cc11cbd1.png)
![image](https://user-images.githubusercontent.com/64473163/122892930-23662400-d346-11eb-8abe-bb84f4abea83.png)

**Additional context:**
I found this comment https://github.com/AzuraCast/AzuraCast/issues/3241#issuecomment-704803152 but I'm not sure if it is the correct fix to my bug. The context is different but the error message is similar. I didn't apply that suggested fix yet because it is a radio in production and I don't want to stop or crash it without being sure it is the correct fix.

I already tried to flush the system cache as suggested here https://docs.azuracast.com/en/user-guide/troubleshooting but it didn't fix the problem.

I didn't include the full log because it exceed the max number of characters

**Comment by SC2Mitch** [comment]
Go to the system debugger and check if there's any messages stuck in the queue. `admin/debug`

**Comment by rquara** [comment]
> Go to the system debugger and check if there's any messages stuck in the queue. `admin/debug`

I don't see any queued message
![image](https://user-images.githubusercontent.com/64473163/122921220-86fe4a80-d362-11eb-9aeb-1b22557437d0.png)

**Comment by SC2Mitch** [comment]
Are you able to update your installation and see if this issue continues?

**Comment by rquara** [comment]
> Are you able to update your installation and see if this issue continues?

I updated to the latest release, flushed the docker cache again and restarted the server. It is working fine now but we have another problem with the uploading of some files (I'm opening another bug report for it because I don't think it is linked with this one).

Just for your information we tried to figure out more information about the trigger of the CPU spike and we discovered that it could also be linked with the upload of mp3 files using the browser interface. 

One of our DJ was uploading a large amount of mp3 files (hundreds, covering the daily needs of our radio) using the browser interface every day more or less at the same time as the CPU spike and the liquidsoap strange behaviour. 

I'm not sure if it is linked with the problem in any way and I don't have logs of the exact timing of the uploads so I can't investigate it more. I will update this ticket if we will have more liquidsoap unexpected behaviours in the coming days. 

Thanks for the support!

**Comment by SC2Mitch** [comment]
Is it possible you can instruct your DJs to upload via Filezilla or any FTP software? It might help us debug if this is a issue with the frontend interface or some stuff lurking in the code which is causing issues.

Thanks for the detailed reply.

**Comment by rquara** [comment]
> Is it possible you can instruct your DJs to upload via Filezilla or any FTP software? It might help us debug if this is a issue with the frontend interface or some stuff lurking in the code which is causing issues.
> 
> Thanks for the detailed reply.

This morning the radio crashed again. Nobody was uploading any file. It looks like a liquidsoap issue

Liquidsoap logs: https://pastebin.com/FuntZE1X

 
![image](https://user-images.githubusercontent.com/64473163/123214770-ed50ad80-d4c7-11eb-8c0d-af82674aac4d.png)
![image](https://user-images.githubusercontent.com/64473163/123214796-f3468e80-d4c7-11eb-8050-053955cbf17e.png)
![image](https://user-images.githubusercontent.com/64473163/123214825-fb063300-d4c7-11eb-9efd-fe51db6872c4.png)
![image](https://user-images.githubusercontent.com/64473163/123214843-00fc1400-d4c8-11eb-80eb-a4921f1759fc.png)
![image](https://user-images.githubusercontent.com/64473163/123214865-08bbb880-d4c8-11eb-9b72-476ecbca7355.png)
![image](https://user-images.githubusercontent.com/64473163/123214884-0e190300-d4c8-11eb-865c-c037063b608a.png)

**Comment by rquara** [comment]
The radio crashed again at about 2pm for 3 minutes. CPU, load, disk I/O and memory usage spiked

I'm attaching our azuracast application logs too. Hope it helps

![image](https://user-images.githubusercontent.com/64473163/123261773-716e5980-d4f7-11eb-8362-e6d66c814eff.png)
![image](https://user-images.githubusercontent.com/64473163/123261817-7f23df00-d4f7-11eb-9b5c-80d127505476.png)


[azuracastapplicationlogs.txt](https://github.com/AzuraCast/AzuraCast/files/6709072/azuracastapplicationlogs.txt)

**Comment by SC2Mitch** [comment]
Okay, do you own the server or is it a rented VPS? If it's a rented, are you sharing CPU cores with other people? I'm wondering if something is hogging up the whole VPS cluster if that's the case if this causes significant slowdowns.

**Comment by rquara** [comment]
> Okay, do you own the server or is it a rented VPS? If it's a rented, are you sharing CPU cores with other people? I'm wondering if something is hogging up the whole VPS cluster if that's the case if this causes significant slowdowns.
> 
> I'll be flagging this up for the developers to take a look at, as they can possibly offer other input on this.

It is a digitalocean dedicated droplet with dedicated resources hosting just the azuracast docker.

**Comment by Vaalyn** [comment]
The following LS errors indicate that LS is restarting due to the high CPU load:
```
...
We must catchup 57.98 seconds!
Too much latency! Resetting active sources...
Closing connection...
```

In the AzuraCast Application Log there are a lot of the following errors which are most likely also due to the high load on CPU and I/O:
```
AzuraCast.CRITICAL: Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused ...
```

This could be caused by several things so we need to check a few places.

Some process on the server could be doing something at that time (maybe one of the sync tasks) that causes it to use the remaining few % of memory. This would cause the VPS to use swap space (if enabled) using hard disk space as additional memory. Due to the slower response time of swap the CPU would spend a lot of time waiting for the i/o.
You can check if this is happening by looking at the `%wa` value of the CPU from the command line `top` command.

It could be that Digital Ocean is throttling the CPU of your VPS due to the constant CPU load (which is something a lot of hosters do with their VPS services). You can check if this is happening by looking at the `%st` value of the CPU from the command line `top` command.

Please also take a look at the process list in `top` at the time this is happening to check which process is using what % of the CPU.
