### ISSUE TITLE
Translating phrases in the file manager

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#433]
Translating phrases in the file manager.
![dfbdfbd](https://user-images.githubusercontent.com/23697714/36245528-91402882-123c-11e8-9074-7fa70317518b.png)

**Comment by susl16c** [comment]
And even about the translation, this does not apply to the resource manager, but in order not to pay for the topic I decided to place everything in one place.
![dsbvdsvs](https://user-images.githubusercontent.com/23697714/36246221-c5eaa3f2-123f-11e8-9a1a-a9572b88a6fb.png)

**Comment by SlvrEagle23** [comment]
The phrases in question are part of JavaScript libraries that have internal strings that I can't localize on the application's end.

While I do aspire to ensure that every possible string in the application is localized and translated, I can't affect strings that aren't pulled in from my application itself, so some small issues like this may appear as a result.
