### ISSUE TITLE
I want to participate in Crowdin Korean translation.

### ISSUE THREAD

**Issue by YaPurO** [AzuraCast/AzuraCast#4331]
First of all, I uploaded it to the Crowdin site discussion section, but I am rewriting it because I was told to request it here.
I'm not sure if it's okay to post it, but please kindly understand. I'm sorry for my poor English.

https://translate.azuracast.com/project/azuracast/discussions/4

I want to translate the project into Korean. However, the Korean language is not displayed in the list of languages, so we are directly translating strings by downloading translation files (ex. frontend.po) from other countries. Could you add a language?

**Comment by SlvrEagle23** [comment]
@YaPurO Hello and thank you for offering to help with our translation efforts. I have added Korean as a targeted language, so now you can submit your translations for direct inclusion into the AzuraCast software.
