### ISSUE TITLE
Could not parse input data when creating external relays using API

### ISSUE THREAD

**Issue by lramilo** [AzuraCast/AzuraCast#4333]
**Using Docker installation method?**
Yes

**AzuraCast version:**
0.12.2 stable

**Host Operating System:**
Ubuntu 18

**Describe the bug:**
As plan to have multiple custom external relays pulling from my AzuraCast master instance, I wrote a shell script for automate the creation of remote relays for every available stream on my AzuraCast installation. But when I call the `/api/station/${station_id}/remotes` method, I get an **"could not parse input data"** error.

**Steps to reproduce:**
This is the part of the script that calls the API using cURL:

`curl -X POST 'https://'$hostnameMaster'/api/station/13/remotes' -H 'Accept: application/json' -H 'Content-Type: application/json' -H 'Authorization: Bearer '$apiKey`  -d currentRelay.json

`currentRelay.json` is a file automatically generated by my script, containing a JSON to be used. This is one of the exact JSONs I'm trying to send to the API (except for the passwords and URLs, of course):

`{ "id": 13, "display_name": "128kbps MP3 (tampa)", "is_visible_on_public_pages": false, "type": "icecast", "enable_autodj": false, "autodj_format": "mp3", "autodj_bitrate": 128, "custom_listen_url": "https://URL", "url": "URL", "mount": "/listen.mp3", "admin_password":"password", "source_port": 8110, "source_mount": "/", "source_username": "source", "source_password": "password", "is_public": false, "listeners_unique": 0, "listeners_total": 0 }`

When executing the above cURL command, I get the next error:

`Error: Could not parse input data. on /var/azuracast/www/src/Controller/Api/AbstractApiCrudController.php L148`

Help will be appreciated !

Regards,

**Comment by Vaalyn** [comment]
Hey, I think you need to put the filename like this in the curl command:
`-d @currentRelay.json`

without a `@` it will just send the text `currenRelay.json` instead of the contents of the file.

**Comment by lramilo** [comment]
Oh my God, you're right... this happens when you end the day burned out :P  Thank you @Vaalyn, it worked !

**Comment by Vaalyn** [comment]
Nice, good to hear it's working now 👍
