### ISSUE TITLE
radiodeintercity

### ISSUE THREAD

**Issue by radiodeintercity2021** [AzuraCast/AzuraCast#4342]
**Using Docker installation method?**

**AzuraCast version:**

**Host Operating System:**

**Describe the bug:**

**Steps to reproduce:**

**Expected behavior:**

**Relevant logs:**

**Screenshots:**

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context:**

**Comment by SC2Mitch** [comment]
I'm unsure what exactly your trying to do here, can you explain?

**Comment by ivellios1988** [comment]
I have a feeling that we're reading an utterly failed advertisement.
