### ISSUE TITLE
No sound or album art behind HTPPS proxy

### ISSUE THREAD

**Issue by LABills** [AzuraCast/AzuraCast#4346]
**Using Docker installation method?**
 yes

**AzuraCast version:**
 v0.13.0 Stable 

**Host Operating System:**
 Debian 10

**Describe the bug:**
 Sound and album art do not load when accessing through nginx proxy manager https. 

**Steps to reproduce:**

Setup https forward using [niginx proxy manager](https://nginxproxymanager.com/) to forward to station public page
Observe no sound is played and album art does not load
Album Art is generic placeholder, and sound receives a blocked status 

**Expected behavior:**
 Sound to play 

**Relevant logs:**

These are from the browser consoles, I cannot find any errors in azuracast logging. 

`A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.`

`Uncaught (in promise) DOMException: The media resource indicated by the src attribute or assigned media provider object was not suitable.`

**Screenshots:**

**Device(s):**

- Device:  Desktop
- OS:  Windows 10
- Browser:  Firefox, Chome
- Version:  89.0.1 (64-bit) Firefox,  Version 91.0.4472.114 (Official Build) (64-bit) chrome
 

**Additional context:**

This began here https://github.com/AzuraCast/AzuraCast/discussions/4319
I have since started from scratch so behavior is a bit different in that sound does not load regardless how I access
Album art is defualt instead of failing to load as it was previously. 

Configuration from nginx proxy manager. minus some blank lines:

server {
  set $forward_scheme https;
  set $server         "192.168.0.171";
  set $port           443;

  listen 80;
listen [::]:80;

listen 443 ssl http2;
listen [::]:443;

  server_name music.my.site;

  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-14/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-14/privkey.pem;

  access_log /data/logs/proxy_host-9.log proxy;

location = /{return 301 $scheme://$http_host/public/urdak;}

  location / {

 
    Proxy!
    include conf.d/include/proxy.conf;
  }

  Custom
  include /data/nginx/custom/server_proxy[.]conf;
}

docker-compse.yml here: https://pastebin.com/raw/vBmWc5Lr

Sound also does not play from the administration page. However, directly navigating to http://192.168.0.171:8000/radio.mp3 does load sound.

**Comment by SC2Mitch** [comment]
Since your using 3rd party program I'm not too sure if we fully support it

**Comment by LABills** [comment]
Understood, any direction on getting some logging from azuracast itself via `docker exec -it` to to attach maybe would be appreciated. I don't know much of anything about https, but the public page itself loads as https without error or any security warnings through the niginx proxy manager forward, so my thinking was other resources, like sound, not doing so was an azuracast specific issue. 

If I were to try some other form of proxy instead of nginx proxy manager, does it make sense to generate a letsencrypt certificate via `./docker.sh letsencrypt-create` in azuracast, or should the proxy be able to handle all https?
