### ISSUE TITLE
Root Password (Via docker)

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#435]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Ubuntu 16.04

Hello, where can i find the root-password of the database? I would like to give GRANT permissions so i could connect to the database form other hosts!

Greetings!

**Comment by RemBdev** [comment]
I found it in the installation logs.

**Comment by SlvrEagle23** [comment]
@RemBdev Sorry for the delay, I was just about to say the same thing...MariaDB assigns a random root password that it logs during the installation process. Those logs are where you can find the password.

**Comment by RemBdev** [comment]
Thanks for the answer!

I have another problem.. I would like to get into the database of azuracast. But i don't understand Docker any at all.

How can i get into the database from my own computer, the database ports are not forwarded i suggest?

Greetings.

**Comment by SlvrEagle23** [comment]
@RemBdev Basically, exposing MariaDB is a matter of updating your `docker-compose.yml` file to include something to this effect:

```yaml
services:
  mariadb:
    ports:
      - "127.0.0.1:3306:3306"
```

(You don't need to double up on the "services" and "mariadb" sections, just put the "ports" thing under those headers in the existing file)

Restart Docker and you should have the server accessible from anywhere on that local host. I wouldn't recommend ever exposing MariaDB to the web at large unless you're really sure what you're doing.
