### ISSUE TITLE
Some API endpoints aren't working with an access through an IP-Address

### ISSUE THREAD

**Issue by maestro300** [AzuraCast/AzuraCast#4352]
**Using Docker installation method?**
yes

**AzuraCast version:**
v0.13.0 

**Host Operating System:**
Debian Linux 10 (Virtual Machine)

**Describe the bug:**
When i'm trying to use the api via IP some of the endpoints are redirecting to the login page or response with an empty page

for example 
https://[my IP]/api/nowplaying results in an empty response
https://[my IP]/api/nowplaying/1 is working
https://[my IP]/api/stations results in an empty response
https://[my IP]/api/station/1 is working
https://[my IP]/api/station/1/history redirects to login screen
https://[my IP]/api/station/1/status redirects to login screen
https://[my IP]/api/station/1/listeners redirects to login screen

**Steps to reproduce:**
1) open browser
2) navigate to https://[your server IP]/api/station/1/history 

**Expected behavior:**
get a json response from the endpoints

**Relevant logs:**
nginx_proxy                | nginx.1     | 192.168.1.113 192.168.1.200 - - [27/Jun/2021:16:31:14 +0000] "GET /api/station/1/status HTTP/2.0" 302 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"
nginx_proxy                | nginx.1     | 192.168.1.113 192.168.1.200 - - [27/Jun/2021:16:31:14 +0000] "GET / HTTP/2.0" 302 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"
nginx_proxy                | nginx.1     | 192.168.1.113 192.168.1.200 - - [27/Jun/2021:16:31:14 +0000] "GET /login HTTP/2.0" 200 1734 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"

**Device(s):**
- Device: Desktop / VM
- OS: Windows / Ubuntu
- Browser: Firefox /  Firefox 
- Version: 89.02 / 88.0

**Additional context:**
the Debian is a Virtual machine and can be accessed through a internal privat IP from other VMs or via Public IP. It doesn't seem to matter which IP I'm using

what could i do to fix this?

**Comment by SC2Mitch** [comment]
can you use the format please :)

**Comment by maestro300** [comment]
> 
> 
> can you use the format please :)

i reformated the original post

**Comment by SlvrEagle23** [comment]
@maestro300 The endpoints that require login appear to be normal, as those require authentication via an API key since they contain sensitive information.

The reason the non-station-ID-specific endpoints may be returning empty would be if you've disabled the "Is Public" setting on your station, which would hide it from any API endpoints that return all stations on the installation. The endpoints for that one specific station will continue to respond as normal (to allow you to use the API for normal purposes for your station) but any bulk listing of stations wouldn't include the non-public ones.

**Comment by maestro300** [comment]
@SlvrEagle23 ah then i read the api documentation wrong - i only now noticed the little lock symbol and assumed that no api key is required ... my bad

**Comment by SC2Mitch** [comment]
Seems to be resolved, tag me if there's any further issues.
