### ISSUE TITLE
[API] Stations: Service Control no longer functions correctly. 

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#4353]
**Using Docker installation method?**
Yep 

**AzuraCast version:**
Rolling Release #8a6625f

**Host Operating System:**
Ubuntu 

**Describe the bug:**
In the API `localhost.com/api` under `Stations: Service Control` you can no longer view `POST /station/{station_id}/frontend /{action}` or the backend variant. The page loads indefinitely. Type errors are located in the debug console which are the root cause of this. 

**Steps to reproduce:**
Review above for the steps. 

**Expected behavior:**
The page should load successfully. 

**Relevant logs:**
N/A 

**Screenshots:**

**Device(s):**
Edge, Latest, Windows 11 Developer Build. 

**Additional context:**

**Comment by Vaalyn** [comment]
Closing this issue as resolved
