### ISSUE TITLE
Azuracast docker update

### ISSUE THREAD

**Issue by pawelzet** [AzuraCast/AzuraCast#4356]
Hello,

What is the last stable version of azuracast? Here I can see it is 0.12.3, I've update azuracast with:

`cd /var/azuracast
./docker.sh update-self
./docker.sh update`

And still my version is 12.2. On your changelog there is a version of 0.13.0 with podcasts. Is it stable now?

Thank you in advance for your help.

**Comment by SC2Mitch** [comment]
hello, our latest update is 0.13.0 and its the latest stable version, you can update :)

**Comment by pawelzet** [comment]
> hello, our latest update is 0.13.0 and its the latest stable version, you can update :)

I've tried to, it was said that azuracast was succesfully update, in the panel I have still 0.12.2 version. Any ideas why it is like that?

Paweł

**Comment by SC2Mitch** [comment]
You can try and switch the `release channel` to see if it resolves this issue, what I suggest is switching to Rolling THEN back to Stable, and attempting the update. 

https://docs.azuracast.com/en/getting-started/updates/release-channels
