### ISSUE TITLE
Song Lengths of 30 seconds to 1 minute cannot be uploaded

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#4357]
**Using Docker installation method?**
Yes

**AzuraCast version:**
Rolling Release #c2b388b (2021-06-26 22:23)

**Host Operating System:**
Ubuntu 20.04

**Describe the bug:**
I can't upload files (MP3) files in the music files in the local system. Error in the console see below.

**Screenshots:**
![image](https://user-images.githubusercontent.com/42640247/123641961-17390580-d823-11eb-858f-6b379f889864.png)

**Device(s):**
- Device: Desktop
- OS: Windows 10
- Browser: Opera GX (Chrome)
- Version: LVL2 (core: 76.0.4017.208)

**Comment by Abqehebter** [comment]
**Important Update on the Issue:**

This probably only affects MP3 files or files that have a length smaller than 1 minute / 30 seconds.

**Comment by SC2Mitch** [comment]
Can you upload the MP3 your having issues with and post it in here?

**Comment by Abqehebter** [comment]
Sure:
[START_AD_BREAK.zip](https://github.com/AzuraCast/AzuraCast/files/6726634/START_AD_BREAK.zip)

**Comment by SC2Mitch** [comment]
Confirmed there's an issue with it. Does this happen with other files under 1 minute?

**Comment by Abqehebter** [comment]
`Does this happen with other files under 1 minute?`

Yes. So I still tried with jingles, these go around the 17-20 seconds each. There this also occurs.

Via SFTP, the files are then recorded at some point, I say.
