### ISSUE TITLE
Azuracast stopped working since the last update

### ISSUE THREAD

**Issue by enigmathion** [AzuraCast/AzuraCast#4359]
Since the last Azuracast update, one of the stations (only 1 of 9) LiquidSoap is deactivated and activated every so often! Why could it be?
It is not a lack of resources on the part of the vps!

**Comment by SC2Mitch** [comment]
this greatly lacks detail and the issue template is not used, please fill it in.

**Comment by enigmathion** [comment]
Tell me what details you need please!

**Comment by SC2Mitch** [comment]
The template when you posted this bug report needs to be filled in. 

https://puu.sh/HSmPK/04da9268e9.png

**Comment by enigmathion** [comment]
I don't have it, delete it! Is there a way to reopen?

**Comment by SC2Mitch** [comment]
Fill this template in. 



**Using Docker installation method?**


**AzuraCast version:**


**Host Operating System:**


**Describe the bug:**


**Steps to reproduce:**


**Expected behavior:**


**Relevant logs:**


**Screenshots:**


**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context:**

**Comment by enigmathion** [comment]
Thank you SC2Mitch!


Using Docker installation method?
Yes

AzuraCast version:
Rolling Release #c2b388b

Host Operating System:
Ubuntu 20.04

Describe the bug:
Azuracast stopped working since the last update

Steps to reproduce:
Since the last Azuracast update, one of the stations (only 1 of 9) LiquidSoap is deactivated and activated every so often! Why could it be?
It is not a lack of resources on the part of the vps!

Expected behavior:
When LiquidSoap is stopping, the usual programming does not advance!

Relevant logs:
I found the following in the liquidsoap log!
At line 44, char 53-55:
Error 7: Invalid value:
Maximum buffering inferior to pre-buffered data
At line 44, char 53-55:
Error 7: Invalid value:
Maximum buffering inferior to pre-buffered data
At line 44, char 53-55:
Error 7: Invalid value:
Maximum buffering inferior to pre-buffered data

Screenshots:

Device(s):

Device:
OS:
Browser:
Version:
Additional context:

**Comment by Vaalyn** [comment]
Could you post the Liquidsoap Configuration of the station that is showing the `Maximum buffering inferior to pre-buffered data` in the Liquidsoap Log?

**Comment by Vaalyn** [comment]
Closing since we don't have further information for debugging.

If this is still happening please post the LS config as requested above and I'll re-open the issue.
