### ISSUE TITLE
Update failed, webs ite gve HTTP 500

### ISSUE THREAD

**Issue by Deiiji** [AzuraCast/AzuraCast#4360]
**Using Docker installation method?**

No
**AzuraCast version:**

Latest rolling
**Host Operating System:**

Ububtu 20.04
**Describe the bug:**

UPdate is failing
**Steps to reproduce:**

Normal update command gives this:
TASK [azuracast-setup : Migrate Legacy Configuration (Update Mode)] ********************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/console azuracast:config:migrate", "delta": "0:00:00.113683", "end": "2021-06-28 18:10:13.633540", "msg": "non-zero return code", "rc": 255, "start": "2021-06-28 18:10:13.519857", "stderr": "", "stderr_lines": [], "stdout": "\nParse error: syntax error, unexpected token \":\", expecting \")\" in /var/azuracast/www_tmp/CompiledContainer.php on line 228", "stdout_lines": ["", "Parse error: syntax error, unexpected token \":\", expecting \")\" in /var/azuracast/www_tmp/CompiledContainer.php on line 228"]}

PLAY RECAP *****************************************************************************************
localhost                  : ok=23   changed=13   unreachable=0    failed=1    skipped=68   rescued=0    ignored=0
**Expected behavior:**

**Relevant logs:**

**Screenshots:**

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context:**

**Comment by SC2Mitch** [comment]
fixed in the latest rolling release
