### ISSUE TITLE
502 Bad Gateway after rolling release update, all AC services down

### ISSUE THREAD

**Issue by smilingpeanut** [AzuraCast/AzuraCast#4361]
**Using Docker installation method?**
Yes

**AzuraCast version:**
#edb1839

**Host Operating System:**
Ubuntu 16.04

**Describe the bug:**
After running `docker.sh update-self && docker.sh update`, all services are down, dashboard reports 502 bad gateway error.

**Steps to reproduce:**

1. Run `docker.sh update-self && docker.sh update`.

**Expected behavior:**

AzuraCast to be updated properly and resumed

**Relevant logs:**

Creating azuracast_mariadb  ... done
Creating azuracast_redis    ... done
Creating azuracast_stations ... done
Creating azuracast_web_run  ... done
Starting up AzuraCast services...
Services started up and ready!
AzuraCast Setup
(Environment: production)
[28-Jun-2021 16:13:11 UTC] PHP Parse error:  syntax error, unexpected token ":", expecting ")" in /var/azuracast/www_tmp/CompiledContainer.php on line 228

Parse error: syntax error, unexpected token ":", expecting ")" in /var/azuracast/www_tmp/CompiledContainer.php on line 228

ERROR: 255
azuracast_redis is up-to-date

**Device(s):**

- Device: Desktop
- OS: macOS
- Browser: Chrome
- Version: 91.0

**Additional context:**
N/A

**Comment by SC2Mitch** [comment]
A new commit just got pushed, can you update and see if this error persists?

**Comment by SlvrEagle23** [comment]
The cause of this was identified and should now be resolved. Latest commit should fix this issue.

**Comment by smilingpeanut** [comment]
Looks like we're back in business. Thanks y'all!
