### ISSUE TITLE
Cannot broadcast live after update

### ISSUE THREAD

**Issue by smilingpeanut** [AzuraCast/AzuraCast#4362]
**Using Docker installation method?**
Yes

**AzuraCast version:**
#9f12e08

**Host Operating System:**
Ubuntu 18.04

**Describe the bug:**
After today's most recent update, my streaming software cannot connect to AzuraCast. Receiving generic connection refused error.

**Steps to reproduce:**
1. Use provided instructions for docker update.
2. Attempt to broadcast live.

**Expected behavior:**
Live broadcast starts.

**Relevant logs:**
Did not see any connection errors or anything similar in Liquidsoap or Icecast logs.

**Screenshots:**
Output of `netstat -tulpn`. Does not appear to be listening on intended port (8005, using Icecast2).

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      789/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1057/sshd
tcp6       0      0 :::33186                :::*                    LISTEN      18985/docker-proxy
tcp6       0      0 :::33154                :::*                    LISTEN      18576/docker-proxy
tcp6       0      0 :::33122                :::*                    LISTEN      18175/docker-proxy
tcp6       0      0 :::33090                :::*                    LISTEN      17771/docker-proxy
tcp6       0      0 :::33187                :::*                    LISTEN      18998/docker-proxy
tcp6       0      0 :::33155                :::*                    LISTEN      18589/docker-proxy
tcp6       0      0 :::33123                :::*                    LISTEN      18188/docker-proxy
tcp6       0      0 :::33091                :::*                    LISTEN      17785/docker-proxy
tcp6       0      0 :::33188                :::*                    LISTEN      19011/docker-proxy
tcp6       0      0 :::33156                :::*                    LISTEN      18604/docker-proxy
tcp6       0      0 :::33124                :::*                    LISTEN      18201/docker-proxy
tcp6       0      0 :::33092                :::*                    LISTEN      17797/docker-proxy
tcp6       0      0 :::33189                :::*                    LISTEN      19024/docker-proxy
tcp6       0      0 :::33157                :::*                    LISTEN      18617/docker-proxy
tcp6       0      0 :::33125                :::*                    LISTEN      18213/docker-proxy
tcp6       0      0 :::33093                :::*                    LISTEN      17809/docker-proxy
tcp6       0      0 :::2022                 :::*                    LISTEN      19858/docker-proxy
tcp6       0      0 :::33190                :::*                    LISTEN      19036/docker-proxy
tcp6       0      0 :::33158                :::*                    LISTEN      18630/docker-proxy
tcp6       0      0 :::33126                :::*                    LISTEN      18225/docker-proxy
tcp6       0      0 :::33094                :::*                    LISTEN      17822/docker-proxy
tcp6       0      0 :::33062                :::*                    LISTEN      17213/docker-proxy
tcp6       0      0 :::33191                :::*                    LISTEN      19049/docker-proxy
tcp6       0      0 :::33159                :::*                    LISTEN      18642/docker-proxy
tcp6       0      0 :::33127                :::*                    LISTEN      18238/docker-proxy
tcp6       0      0 :::33095                :::*                    LISTEN      17835/docker-proxy
tcp6       0      0 :::33063                :::*                    LISTEN      17245/docker-proxy
tcp6       0      0 :::33192                :::*                    LISTEN      19062/docker-proxy
tcp6       0      0 :::33160                :::*                    LISTEN      18655/docker-proxy
tcp6       0      0 :::33128                :::*                    LISTEN      18251/docker-proxy
tcp6       0      0 :::33096                :::*                    LISTEN      17846/docker-proxy
tcp6       0      0 :::33064                :::*                    LISTEN      17259/docker-proxy
tcp6       0      0 :::33193                :::*                    LISTEN      19075/docker-proxy
tcp6       0      0 :::33161                :::*                    LISTEN      18668/docker-proxy
tcp6       0      0 :::33129                :::*                    LISTEN      18264/docker-proxy
tcp6       0      0 :::33097                :::*                    LISTEN      17859/docker-proxy
tcp6       0      0 :::33065                :::*                    LISTEN      17294/docker-proxy
tcp6       0      0 :::33194                :::*                    LISTEN      19087/docker-proxy
tcp6       0      0 :::33162                :::*                    LISTEN      18680/docker-proxy
tcp6       0      0 :::33130                :::*                    LISTEN      18277/docker-proxy
tcp6       0      0 :::33098                :::*                    LISTEN      17871/docker-proxy
tcp6       0      0 :::33066                :::*                    LISTEN      17313/docker-proxy
tcp6       0      0 :::33195                :::*                    LISTEN      19099/docker-proxy
tcp6       0      0 :::33163                :::*                    LISTEN      18693/docker-proxy
tcp6       0      0 :::33131                :::*                    LISTEN      18290/docker-proxy
tcp6       0      0 :::33099                :::*                    LISTEN      17883/docker-proxy
tcp6       0      0 :::33067                :::*                    LISTEN      17333/docker-proxy
tcp6       0      0 :::33196                :::*                    LISTEN      19112/docker-proxy
tcp6       0      0 :::33164                :::*                    LISTEN      18706/docker-proxy
tcp6       0      0 :::33132                :::*                    LISTEN      18303/docker-proxy
tcp6       0      0 :::33100                :::*                    LISTEN      17896/docker-proxy
tcp6       0      0 :::33068                :::*                    LISTEN      17348/docker-proxy
tcp6       0      0 :::33197                :::*                    LISTEN      19124/docker-proxy
tcp6       0      0 :::33165                :::*                    LISTEN      18719/docker-proxy
tcp6       0      0 :::33133                :::*                    LISTEN      18315/docker-proxy
tcp6       0      0 :::33101                :::*                    LISTEN      17909/docker-proxy
tcp6       0      0 :::33069                :::*                    LISTEN      17367/docker-proxy
tcp6       0      0 :::33198                :::*                    LISTEN      19137/docker-proxy
tcp6       0      0 :::33166                :::*                    LISTEN      18732/docker-proxy
tcp6       0      0 :::33134                :::*                    LISTEN      18327/docker-proxy
tcp6       0      0 :::33102                :::*                    LISTEN      17922/docker-proxy
tcp6       0      0 :::33070                :::*                    LISTEN      17380/docker-proxy
tcp6       0      0 :::33199                :::*                    LISTEN      19150/docker-proxy
tcp6       0      0 :::33167                :::*                    LISTEN      18744/docker-proxy
tcp6       0      0 :::33135                :::*                    LISTEN      18340/docker-proxy
tcp6       0      0 :::33103                :::*                    LISTEN      17935/docker-proxy
tcp6       0      0 :::33071                :::*                    LISTEN      17400/docker-proxy
tcp6       0      0 :::80                   :::*                    LISTEN      20022/docker-proxy
tcp6       0      0 :::33200                :::*                    LISTEN      19163/docker-proxy
tcp6       0      0 :::33168                :::*                    LISTEN      18757/docker-proxy
tcp6       0      0 :::33136                :::*                    LISTEN      18352/docker-proxy
tcp6       0      0 :::33104                :::*                    LISTEN      17948/docker-proxy
tcp6       0      0 :::33072                :::*                    LISTEN      17418/docker-proxy
tcp6       0      0 :::33201                :::*                    LISTEN      19176/docker-proxy
tcp6       0      0 :::33169                :::*                    LISTEN      18769/docker-proxy
tcp6       0      0 :::33137                :::*                    LISTEN      18364/docker-proxy
tcp6       0      0 :::33105                :::*                    LISTEN      17960/docker-proxy
tcp6       0      0 :::33073                :::*                    LISTEN      17467/docker-proxy
tcp6       0      0 :::33202                :::*                    LISTEN      19189/docker-proxy
tcp6       0      0 :::33170                :::*                    LISTEN      18781/docker-proxy
tcp6       0      0 :::33138                :::*                    LISTEN      18376/docker-proxy
tcp6       0      0 :::33106                :::*                    LISTEN      17972/docker-proxy
tcp6       0      0 :::33074                :::*                    LISTEN      17480/docker-proxy
tcp6       0      0 :::33203                :::*                    LISTEN      19202/docker-proxy
tcp6       0      0 :::33171                :::*                    LISTEN      18794/docker-proxy
tcp6       0      0 :::33139                :::*                    LISTEN      18389/docker-proxy
tcp6       0      0 :::33107                :::*                    LISTEN      17984/docker-proxy
tcp6       0      0 :::33075                :::*                    LISTEN      17584/docker-proxy
tcp6       0      0 :::33204                :::*                    LISTEN      19214/docker-proxy
tcp6       0      0 :::33172                :::*                    LISTEN      18806/docker-proxy
tcp6       0      0 :::33140                :::*                    LISTEN      18401/docker-proxy
tcp6       0      0 :::33108                :::*                    LISTEN      17996/docker-proxy
tcp6       0      0 :::33076                :::*                    LISTEN      17596/docker-proxy
tcp6       0      0 :::33205                :::*                    LISTEN      19227/docker-proxy
tcp6       0      0 :::33173                :::*                    LISTEN      18818/docker-proxy
tcp6       0      0 :::33141                :::*                    LISTEN      18414/docker-proxy
tcp6       0      0 :::33109                :::*                    LISTEN      18008/docker-proxy
tcp6       0      0 :::33077                :::*                    LISTEN      17608/docker-proxy
tcp6       0      0 :::33206                :::*                    LISTEN      19239/docker-proxy
tcp6       0      0 :::33174                :::*                    LISTEN      18831/docker-proxy
tcp6       0      0 :::33142                :::*                    LISTEN      18427/docker-proxy
tcp6       0      0 :::33110                :::*                    LISTEN      18021/docker-proxy
tcp6       0      0 :::33078                :::*                    LISTEN      17620/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      1057/sshd
tcp6       0      0 :::33207                :::*                    LISTEN      19252/docker-proxy
tcp6       0      0 :::33175                :::*                    LISTEN      18844/docker-proxy
tcp6       0      0 :::33143                :::*                    LISTEN      18440/docker-proxy
tcp6       0      0 :::33111                :::*                    LISTEN      18034/docker-proxy
tcp6       0      0 :::33079                :::*                    LISTEN      17633/docker-proxy
tcp6       0      0 :::33208                :::*                    LISTEN      19265/docker-proxy
tcp6       0      0 :::33176                :::*                    LISTEN      18857/docker-proxy
tcp6       0      0 :::33144                :::*                    LISTEN      18452/docker-proxy
tcp6       0      0 :::33112                :::*                    LISTEN      18045/docker-proxy
tcp6       0      0 :::33080                :::*                    LISTEN      17645/docker-proxy
tcp6       0      0 :::33177                :::*                    LISTEN      18869/docker-proxy
tcp6       0      0 :::33145                :::*                    LISTEN      18464/docker-proxy
tcp6       0      0 :::33113                :::*                    LISTEN      18058/docker-proxy
tcp6       0      0 :::33081                :::*                    LISTEN      17657/docker-proxy
tcp6       0      0 :::33178                :::*                    LISTEN      18883/docker-proxy
tcp6       0      0 :::33146                :::*                    LISTEN      18477/docker-proxy
tcp6       0      0 :::33114                :::*                    LISTEN      18070/docker-proxy
tcp6       0      0 :::33082                :::*                    LISTEN      17670/docker-proxy
tcp6       0      0 :::443                  :::*                    LISTEN      20003/docker-proxy
tcp6       0      0 :::33179                :::*                    LISTEN      18895/docker-proxy
tcp6       0      0 :::33147                :::*                    LISTEN      18489/docker-proxy
tcp6       0      0 :::33115                :::*                    LISTEN      18083/docker-proxy
tcp6       0      0 :::33083                :::*                    LISTEN      17682/docker-proxy
tcp6       0      0 :::33180                :::*                    LISTEN      18908/docker-proxy
tcp6       0      0 :::33148                :::*                    LISTEN      18501/docker-proxy
tcp6       0      0 :::33116                :::*                    LISTEN      18096/docker-proxy
tcp6       0      0 :::33084                :::*                    LISTEN      17695/docker-proxy
tcp6       0      0 :::33181                :::*                    LISTEN      18921/docker-proxy
tcp6       0      0 :::33149                :::*                    LISTEN      18513/docker-proxy
tcp6       0      0 :::33117                :::*                    LISTEN      18108/docker-proxy
tcp6       0      0 :::33085                :::*                    LISTEN      17708/docker-proxy
tcp6       0      0 :::33182                :::*                    LISTEN      18934/docker-proxy
tcp6       0      0 :::33150                :::*                    LISTEN      18526/docker-proxy
tcp6       0      0 :::33118                :::*                    LISTEN      18121/docker-proxy
tcp6       0      0 :::33086                :::*                    LISTEN      17721/docker-proxy
tcp6       0      0 :::33183                :::*                    LISTEN      18947/docker-proxy
tcp6       0      0 :::33151                :::*                    LISTEN      18538/docker-proxy
tcp6       0      0 :::33119                :::*                    LISTEN      18134/docker-proxy
tcp6       0      0 :::33087                :::*                    LISTEN      17734/docker-proxy
tcp6       0      0 :::33184                :::*                    LISTEN      18959/docker-proxy
tcp6       0      0 :::33152                :::*                    LISTEN      18550/docker-proxy
tcp6       0      0 :::33120                :::*                    LISTEN      18149/docker-proxy
tcp6       0      0 :::33088                :::*                    LISTEN      17746/docker-proxy
tcp6       0      0 :::33185                :::*                    LISTEN      18972/docker-proxy
tcp6       0      0 :::33153                :::*                    LISTEN      18563/docker-proxy
tcp6       0      0 :::33121                :::*                    LISTEN      18162/docker-proxy
tcp6       0      0 :::33089                :::*                    LISTEN      17759/docker-proxy
udp        0      0 127.0.0.53:53           0.0.0.0:*                           789/systemd-resolve

**Device(s):**

- Device: Desktop
- OS: macOS
- Browser: Chrome
- Version: 91.0

**Additional context:**
None

**Comment by SlvrEagle23** [comment]
@smilingpeanut This has been fixed in a temporary revert as of the latest rolling release version.

**Comment by smilingpeanut** [comment]
> @smilingpeanut This has been fixed in a temporary revert as of the latest rolling release version.

Thank you for the swift attention as always!
