### ISSUE TITLE
Not possible to upload short mp3 files of 5 to 10 seconds

### ISSUE THREAD

**Issue by rolradio** [AzuraCast/AzuraCast#4369]
**Using Docker installation method?**

Yes

**AzuraCast version:**

Rolling Release #b403160

**Host Operating System:**

Unbuntu 18

**Describe the bug:**

With the last update of azuracast a few days ago it is not possible to upload short mp3 files of 5 to 10 seconds (station IDs and jingles) via azuracast web upload.

The problem is the same with different servers.

The update from a few minutes ago did not fix the problem.

**Steps to reproduce:**

**Expected behavior:**

**Relevant logs:**

**Screenshots:**

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context:**

**Comment by SC2Mitch** [comment]
duplicate https://github.com/AzuraCast/AzuraCast/issues/4357
