### ISSUE TITLE
No longer able to upload media via Azuracast Console

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#4375]
**Using Docker installation method?**
Yes

**AzuraCast version:**
Rolling Release #2b70f65 (2021-06-29 2:58) 

**Host Operating System:**
Ubuntu 20.04

**Describe the bug:**

Neither drag/drop nor Select File work to upload media to a music folder. The file just sits there and doesn't get added to the media list.  Uploading the same file to the same location works fine via SFTP (Filezilla, in my case)

**Steps to reproduce:**

1. Go to 'Server ip/station/1/files#Radio%20ID' or any other media folder
2. Click on 'Select File' or Drag/Drop
3. Scroll down thru folder content 
4. File doesn't appear in list

**Expected behavior:**

Files selected or pasted should immediately upload to media folder

**Relevant logs:**

N/A
**Screenshots:**
![Image1](https://user-images.githubusercontent.com/66107794/124376906-25e64900-dc77-11eb-8c89-6c609b831099.jpg)

**Device(s):**

- Device:  Desktop
- OS:  Win 7
- Browser: Edge and Chrome
- Version:  Latest versions

**Additional context:**

**Comment by SC2Mitch** [comment]
try updating to the latest rolling release, works for me on the latest version.

**Comment by SpeedyCharly** [comment]
Danke SC2Mitch!  That did the trick...
