### ISSUE TITLE
PHP Api documentation ?

### ISSUE THREAD

**Issue by RainbowDash53** [AzuraCast/AzuraCast#438]
I'm not a pro at web developpement, but I want to know if there is an PHP API doc or not, because I don't know how to use JSON :/

Can anyone help me please?

**Comment by TorchwoodPL** [comment]
[your azura host]/static/api/index.html

There you have all endpoints

**Comment by SlvrEagle23** [comment]
@RainbowDash53 The endpoints all return JSON (as it's a popular standard nowadays for APIs of all kinds, and can be used in many languages), but it's easy to convert that data back into a PHP array by calling `json_decode($return, true)` on the data.

The full API is documented at [this site](http://azuracast.com/api/index.html), and the API version corresponding to each installed AzuraCast instance is available at the URL @TorchwoodPL provided.
