### ISSUE TITLE
redis installation error

### ISSUE THREAD

**Issue by pegasusict** [AzuraCast/AzuraCast#4385]
**Using Docker installation method?**
Yes

**AzuraCast version:**
v0.13.0

**Host Operating System:**
debian 10 lxc container using docker-ce 20.10

**Describe the bug:**
ERROR: for redis  Cannot start service redis: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: write sysctl key net.core.somaxconn: open /proc/sys/net/core/somaxconn: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.

**Steps to reproduce:**
1. install Proxmox VE 7
2. create unpriviliged container based on template turnkey-core v16.1-1
3. in options, check nesting, keyctl
4. start container
5. apt-get -qqy update && apt-get -qy dist-upgrade && apt-get -qy install screen mc curl && apt-get -qy autoremove && apt-get -qy autoclean
6. curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
7. echo \
"deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
8. apt-get -qqy update && apt-get -qy dist-upgrade && apt-get -qy install docker-ce
9. mkdir -p /var/azuracast
10. cd /var/azuracast
11. curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/main/docker.sh > docker.sh
12. chmod a+x docker.sh
13. yes 'Y' | ./docker.sh setup-release
14. ./docker.sh install (defaults, no letsencrypt)

**Expected behavior:**
succesful installation of azuracast stack

**Relevant logs:**
__console output:__
Docker is already installed! Continuing...
Docker Compose does not appear to be installed. Install Docker Compose now? [Y/n] 
Creating default AzuraCast settings file...
Retrieving default docker-compose.yml file...
Customize AzuraCast ports? [y/N] 
Set up LetsEncrypt? [y/N] 
WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
Pulling mariadb                 ... done
Pulling redis                   ... done
Pulling stations                ... done
Pulling web                     ... done
Pulling nginx_proxy             ... done
Pulling nginx_proxy_letsencrypt ... done
WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
Creating network "azuracast_backend" with driver "bridge"
Creating network "azuracast_frontend" with driver "bridge"
Creating volume "azuracast_nginx_proxy_vhosts" with default driver
Creating volume "azuracast_db_data" with default driver
Creating volume "azuracast_letsencrypt" with default driver
Creating volume "azuracast_letsencrypt_html" with default driver
Creating volume "azuracast_letsencrypt_acme" with default driver
Creating volume "azuracast_shoutcast2_install" with default driver
Creating volume "azuracast_geolite_install" with default driver
Creating volume "azuracast_sftpgo_data" with default driver
Creating volume "azuracast_station_data" with default driver
Creating volume "azuracast_www_vendor" with default driver
Creating volume "azuracast_tmp_data" with default driver
Creating volume "azuracast_redis_data" with default driver
Creating volume "azuracast_backups" with default driver
Creating azuracast_stations ... 
Creating azuracast_redis    ... error
Creating azuracast_mariadb  ... done

Creating azuracast_stations ... doneused: process_linux.go:545: container init caused: write sysctl key net.core.somaxconn: open /proc/sys/net/core/somaxconn: no such file or directory: unknown

ERROR: for redis  Cannot start service redis: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: write sysctl key net.core.somaxconn: open /proc/sys/net/core/somaxconn: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
Starting azuracast_redis ... 
azuracast_mariadb is up-to-date
Starting azuracast_redis ... error

ERROR: for azuracast_redis  Cannot start service redis: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: write sysctl key net.core.somaxconn: open /proc/sys/net/core/somaxconn: no such file or directory: unknown

ERROR: for redis  Cannot start service redis: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: write sysctl key net.core.somaxconn: open /proc/sys/net/core/somaxconn: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.

**Screenshots:**
N/A

**Device(s):**
- Device: Homelab Proxmox VE server
- OS: Debian bullseye
- Browser: chrome
- Version: Version 91.0.4472.114 (Official Build) (64-bit)

**Additional context:**
N/A

**Comment by pegasusict** [comment]
New information: it appears this is a known issue with unpriviliged containers which means it's an issue outside of the scope of this project.
https://discuss.linuxcontainers.org/t/increase-somaxconn-in-unprivileged-containers/4477

**Comment by pegasusict** [comment]
Please advice users not to install docker version in an unpriviliged container

**Comment by SC2Mitch** [comment]
If I recall correctly, we don't officially support Proxmox, as it can conflict with Docker and or other dependances we rely on.

**Comment by SlvrEagle23** [comment]
@pegasusict If you remove that sysctl line from the Redis container (it'll operate without that, that just improves its performance)...does your installation otherwise work completely fine inside that double-nested environment?

If so, in the interest of compatibility I'd be okay with removing it from our stock Docker Compose file and offering folks the ability to add it via an override or a custom setting.

**Comment by pegasusict** [comment]
I'll look into it right away! I'll keep you posted!

**Comment by pegasusict** [comment]
sofar I've managed to get everything installed but I run into a http500, further information will follow

**Comment by pegasusict** [comment]
can't get it working, switching to vm
