### ISSUE TITLE
Live DJ goes off the air out of nowhere.

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#4386]
**Using Docker installation method?**
NO (Ansible)

**AzuraCast version:**
AzuraCast • Rolling Release #3cb73fe (2021-07-06 16:41)

**Host Operating System:**
Ubuntu 18.04 LTS

**Describe the bug:**
Live DJ goes off the air out of nowhere.

**Expected behavior:**
While in normal broadcast stream, Live DJ drops from broadcast. I am using SAM Publisher. It is a virtual server with twenty radios. This issue applies to several radios. It happens to some users.

**Relevant logs:**
```2021/07/08 18:34:05 >>> LOG START
2021/07/08 18:34:04 [main:3] Liquidsoap 1.4.2
2021/07/08 18:34:04 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.6 sedlex=2.3 menhirLib=20210419 dtools=0.4.2 duppy=0.8.0 cry=0.6.1 mm=0.5.1 ogg=0.5.2 vorbis=0.7.1 opus=0.1.3 mad=0.4.5 flac=0.1.5 flac.ogg=0.1.5 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.3.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.9 camomile=1.0.2 faad=0.4.0 ladspa=0.1.5
2021/07/08 18:34:05 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2021/07/08 18:34:05 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2021/07/08 18:34:05 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2021/07/08 18:34:05 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2021/07/08 18:34:05 [decoder:3] Method "MAD" accepted "/var/azuracast/www/resources/error.mp3".
2021/07/08 18:34:05 [sandbox:3] Sandboxing disabled
2021/07/08 18:34:05 [video.converter:3] Couldn't find preferred video converter: gavl.
2021/07/08 18:34:05 [audio.converter:3] Using samplerate converter: libsamplerate.
2021/07/08 18:34:05 [harbor:3] Adding mountpoint '/' on port 5910
2021/07/08 18:34:05 [playlist_stationname:3] Loading playlist...
2021/07/08 18:34:05 [playlist_stationname:3] No mime type specified, trying autodetection.
2021/07/08 18:34:05 [playlist_stationname:3] Playlist treated as format application/x-mpegURL
2021/07/08 18:34:05 [playlist_stationname:3] Successfully loaded a playlist of 183 tracks.
2021/07/08 18:34:05 [error_jingle:3] "/var/azuracast/www/resources/error.mp3" is static, resolving once for all...
2021/07/08 18:34:05 [local_1:3] Connecting mount sid#1 for @127.0.0.1...
2021/07/08 18:34:05 [local_1:3] Connection setup was successful.
2021/07/08 18:34:05 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2021/07/08 18:34:05 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/stationname/media/Kivircik Ali  Kurban OLdugum.mp3".
2021/07/08 18:34:05 [safe_fallback:3] Switch to amplify_10663.
2021/07/08 18:34:05 [live_fallback:3] Switch to cross_10633.
2021/07/08 18:34:05 [requests_fallback:3] Switch to autodj_fallback.
2021/07/08 18:34:05 [autodj_fallback:3] Switch to dynamic_startup.
2021/07/08 18:34:05 [dynamic_startup:3] Switch to switch_10615.
2021/07/08 18:34:05 [switch_10615:3] Switch to autodj_startup_blank.
2021/07/08 18:34:05 [lang:3] AzuraCast Raw Response: annotate:title="ERGÜN EFE  SERPİL EFE  Sen Ne Dersin",duration="276.00",song_id="9055c2c180cc774ff39c3cf26d9e7fb1",media_id="2300",liq_amplify="0.00dB",playlist_id="35":/var/azuracast/stations/stationname/media/ERGÜN EFE  SERPİL EFE  Sen Ne Dersin.mp3
2021/07/08 18:34:05 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/stationname/media/ERG\195\156N EFE  SERP\196\176L EFE  Sen Ne Dersin.mp3".
2021/07/08 18:34:05 [next_song:3] Prepared "/var/azuracast/stations/stationname/media/ERG\195\156N EFE  SERP\196\176L EFE  Sen Ne Dersin.mp3" (RID 3).
2021/07/08 18:34:05 [dynamic_startup:3] Switch to cue_next_song with transition.
2021/07/08 18:34:05 [cross_10633:3] Analysis: -infdB / -19.634383dB (14.96s / 14.96s)
2021/07/08 18:34:05 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2021/07/08 18:34:05 [lang:3] AutoDJ is ready!
2021/07/08 18:34:05 [lang:3] AzuraCast Feedback Response: OK
2021/07/08 18:37:46 [lang:3] AzuraCast Raw Response: annotate:title="barabar  aman of",artist="Barabar",duration="144.00",song_id="0737dc01536f5ec5047539a65592a501",media_id="2571",liq_amplify="0.00dB",playlist_id="35":/var/azuracast/stations/stationname/media/barabar__aman_of.mp3
2021/07/08 18:37:46 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/stationname/media/barabar__aman_of.mp3".
2021/07/08 18:38:26 [next_song:3] Prepared "/var/azuracast/stations/stationname/media/barabar__aman_of.mp3" (RID 4).
2021/07/08 18:38:27 [cross_10633:3] Analysis: -78.231857dB / -13.748051dB (14.98s / 14.98s)
2021/07/08 18:38:27 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2021/07/08 18:38:27 [lang:3] AzuraCast Feedback Response: OK
2021/07/08 18:39:12 [lang:3] Authenticating DJ: stationdjlive
2021/07/08 18:39:13 [lang:3] AzuraCast DJ Auth Response: true
2021/07/08 18:39:13 [decoder:3] Method "MAD" accepted "audio/mpeg".
2021/07/08 18:39:13 [lang:3] DJ Source connected! Last authenticated DJ: stationdjlive - [("icy-name", "Radyo Cember"), ("icy-genre", "Genel"), ("icy-url", "http://www.stationname.com"), ("icy-irc", "#audiorealm"), ("icy-icq", "NA"), ("icy-aim", "NA"), ("icy-pub", "1"), ("icy-br", "48"), ("Content-type", "audio/mpeg")]
2021/07/08 18:39:13 [lang:3] AzuraCast Live Connected Response: true
2021/07/08 18:39:13 [input_streamer:3] Decoding...
2021/07/08 18:39:43 [live_fallback:3] Switch to audio_to_stereo_10656 with transition.
2021/07/08 18:42:58 [lang:3] Authenticating DJ: stationdjlive
2021/07/08 18:42:59 [lang:3] AzuraCast DJ Auth Response: true
2021/07/08 18:42:59 [camomile:3] Failed to convert "DJ BESTE iLE T\220RK\220L\220 SAATLER - Servet Kocakaya - Hayat Dediin" from UTF-8 to UTF-8 (CamomileLibrary__CharEncoding.Configure(Config).Malformed_code)!
2021/07/08 18:42:59 [input_streamer:3] New metadata chunk ? -- DJ BESTE iLE T?RK?L? SAATLER - Servet Kocakaya - Hayat Dediin.
2021/07/08 18:46:34 [lang:3] Authenticating DJ: stationdjlive
2021/07/08 18:46:35 [lang:3] AzuraCast DJ Auth Response: true
2021/07/08 18:46:35 [camomile:3] Failed to convert "DJ BESTE iLE T\220RK\220L\220 SAATLER - Selda_Bagcan_ - _Ucurum_Cicekleri" from UTF-8 to UTF-8 (CamomileLibrary__CharEncoding.Configure(Config).Malformed_code)!
2021/07/08 18:46:35 [input_streamer:3] New metadata chunk ? -- DJ BESTE iLE T?RK?L? SAATLER - Selda_Bagcan_ - _Ucurum_Cicekleri.
2021/07/08 18:50:37 [lang:3] Authenticating DJ: stationdjlive
2021/07/08 18:50:38 [lang:3] AzuraCast DJ Auth Response: true
2021/07/08 18:50:38 [camomile:3] Failed to convert "DJ BESTE iLE T\220RK\220L\220 SAATLER - NURAY - -M-EK -- ALTIN Y\220Z\220-\220M KIRILDI  (2014)" from UTF-8 to UTF-8 (CamomileLibrary__CharEncoding.Configure(Config).Malformed_code)!
2021/07/08 18:50:38 [input_streamer:3] New metadata chunk ? -- DJ BESTE iLE T?RK?L? SAATLER - NURAY - -M-EK -- ALTIN Y?Z?-?M KIRILDI  (2014).
2021/07/08 18:52:17 [lang:3] Authenticating DJ: stationdjlive
2021/07/08 18:52:19 [lang:3] AzuraCast DJ Auth Response: true
2021/07/08 18:52:32 [input_streamer:3] Timeout reached!
2021/07/08 18:52:32 [input_streamer:2] Error while reading from client: Timed out after waiting for 30.00 sec.
2021/07/08 18:52:32 [lang:3] DJ Source disconnected! Current live DJ: stationdjlive
2021/07/08 18:52:32 [live_fallback:3] Switch to cross_10633 with forgetful transition.
2021/07/08 18:52:32 [dummy:3] Source failed (no more tracks) stopping output...
2021/07/08 18:52:34 [lang:3] AzuraCast Live Disconnected Response: true
2021/07/08 18:52:34 [input_streamer:2] Feeding stopped: Mad.End_of_stream.
2021/07/08 18:52:34 [lang:3] DJ Source disconnected! Current live DJ: 
2021/07/08 18:52:34 [lang:3] AzuraCast Live Disconnected Response: true
2021/07/08 18:52:44 [lang:3] AzuraCast Raw Response: annotate:title="selma geçer  gam elinden benim zülfü siyahım",artist="Selma gecer",duration="310.00",song_id="c7ffd7ddb858a34a2137aaee30b7c142",media_id="2709",liq_amplify="0.00dB",playlist_id="35":/var/azuracast/stations/stationname/media/selma_geçer__gam_elinden_benim_zülfü_siyahım.mp3
2021/07/08 18:52:44 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/stationname/media/selma_gec\204\167er__gam_elinden_benim_zu\204\136lfu\204\136_siyah\196\177m.mp3".
2021/07/08 18:53:25 [next_song:3] Prepared "/var/azuracast/stations/stationname/media/selma_gec\204\167er__gam_elinden_benim_zu\204\136lfu\204\136_siyah\196\177m.mp3" (RID 1).
2021/07/08 18:53:25 [cross_10633:3] Analysis: -34.101159dB / -15.033987dB (14.96s / 15.00s)
2021/07/08 18:53:25 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2021/07/08 18:53:26 [lang:3] AzuraCast Feedback Response: OK
2021/07/08 18:53:55 [lang:3] Authenticating DJ: stationdjlive
2021/07/08 18:53:56 [lang:3] AzuraCast DJ Auth Response: true
2021/07/08 18:53:56 [camomile:3] Failed to convert "DJ BESTE iLE T\220RK\220L\220 SAATLER - Semra Aslan - Sebebi Var  Gndem Mzik" from UTF-8 to UTF-8 (CamomileLibrary__CharEncoding.Configure(Config).Malformed_code)!
2021/07/08 18:53:56 [input_streamer:3] New metadata chunk ? -- DJ BESTE iLE T?RK?L? SAATLER - Semra Aslan - Sebebi Var  Gndem Mzik.
```

**Device(s):**

- Device: PC
- OS: Windows 10
- Browser: Opera
- Version: Latest

**Additional context:**
I know there is no support for Ansible. Please help me find the source of this problem.

**Comment by SC2Mitch** [comment]
Taking a look at this now and will get back to you when I can.

**Comment by ogrenci01** [comment]
Hi @SC2Mitch ;

There is a similar issue reported for Liquidsoap. Can you help me find the source?

Check This: https://github.com/savonet/liquidsoap/issues/1619

**Comment by SpeedyCharly** [comment]
Check your bandwidth usage...
Had similar issue when we first used Azuracast - on a server rented from a reseller who wouldn't allow us access to the console.  My impression was that he was putting too many stations on his servers and exceeding bandwidth allocations at peak time but he never acknowledged the problem.  I then got fed up and rented a an empty vps which I set up and configured myself.  No longer any problems with buffer at 15 secs, but upped it to 30 anyhow to help mitigate streamer errors by allowing them a bit more time to re-encode...

**Comment by ogrenci01** [comment]
Hi @SpeedyCharly ;

I am using a virtual server with independently partitioned resources. Connection usage is pretty low and I have a private network to me. I don't think it's a network issue. Unfortunately internet network is expensive in my country and I use 1 Gbits. I'm using 60 seconds right now. It looks like there's no problem. My tests continue.

**Comment by ogrenci01** [comment]
Hello to everyone!

Even if the Buffer Time is 60 seconds, the broadcaster will be down. What should I do to solve this problem? Anyone have another idea?

New Logs Here:
`2021/07/13 12:52:47 [camomile:3] Failed to convert "DJ BESTEE iLE T\220RK\220L\220 SAATLER - Ayd\253n \214zt\252rk - \214mr\252m Senindir(Ayd\253n \214zt\252rk)" from UTF-8 to UTF-8 (CamomileLibrary__CharEncoding.Configure(Config).Malformed_code)!
2021/07/13 12:52:47 [input_streamer:3] New metadata chunk ? -- DJ BESTEE iLE T?RK?L? SAATLER - Ayd?n ?zt?rk - ?mr?m Senindir(Ayd?n ?zt?rk).
2021/07/13 12:57:08 [lang:3] Authenticating DJ: stationdj
2021/07/13 12:57:09 [lang:3] AzuraCast DJ Auth Response: true
2021/07/13 12:57:09 [camomile:3] Failed to convert "DJ BESTEE iLE T\220RK\220L\220 SAATLER - Mustafa \195\150zarslan - Derd\196\177n yarden m\196\177d\196\177r" from UTF-8 to UTF-8 (CamomileLibrary__CharEncoding.Configure(Config).Malformed_code)!
2021/07/13 12:57:09 [input_streamer:3] New metadata chunk ? -- DJ BESTEE iLE T?RK?L? SAATLER - Mustafa Özarslan - Derdın yarden mıdır.
2021/07/13 13:00:45 [lang:3] Authenticating DJ: stationdj
2021/07/13 13:00:46 [lang:3] AzuraCast DJ Auth Response: true
2021/07/13 13:00:46 [camomile:3] Failed to convert "DJ BESTEE iLE T\220RK\220L\220 SAATLER - \195\150zcan T\195\188re - Kimsesizler \195\156lkesi [ \196\176ber T\195\188rk\195\188leri \194\169 2020 \196\176ber Prod\195\188ksiyon ]" from UTF-8 to UTF-8 (CamomileLibrary__CharEncoding.Configure(Config).Malformed_code)!
2021/07/13 13:00:46 [input_streamer:3] New metadata chunk ? -- DJ BESTEE iLE T?RK?L? SAATLER - Özcan Türe - Kimsesizler Ülkesi [ İber Türküleri © 2020 İber Prodüksiyon ].
2021/07/13 13:01:51 [lang:3] Authenticating DJ: stationdj
2021/07/13 13:01:53 [lang:3] AzuraCast DJ Auth Response: true
2021/07/13 13:02:07 [input_streamer:3] Timeout reached!
2021/07/13 13:02:07 [input_streamer:2] Error while reading from client: Timed out after waiting for 30.00 sec.
2021/07/13 13:02:07 [lang:3] DJ Source disconnected! Current live DJ: stationdj
2021/07/13 13:02:07 [lang:3] AzuraCast Live Disconnected Response: true
2021/07/13 13:02:07 [input_streamer:2] Feeding stopped: Mad.End_of_stream.
2021/07/13 13:02:07 [lang:3] DJ Source disconnected! Current live DJ: 
2021/07/13 13:02:08 [lang:3] AzuraCast Live Disconnected Response: true
2021/07/13 13:02:37 [dummy:3] Source failed (no more tracks) stopping output...
2021/07/13 13:02:37 [live_fallback:3] Switch to cross_10633 with forgetful transition.
2021/07/13 13:03:08 [lang:3] AzuraCast Raw Response: annotate:title="rıdvan adede  neriman",artist="Rıdvan adede",duration="146.00",song_id="5113d95b23970f9fb13e4ee9d8c9e8fa",media_id="2785",liq_amplify="0.00dB",playlist_id="35":/var/azuracast/stations/stationname/media/Ridvan_adede__neriman.mp3
2021/07/13 13:03:08 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/stationname/media/Ridvan_adede__neriman.mp3".
2021/07/13 13:03:48 [next_song:3] Prepared "/var/azuracast/stations/stationname/media/Ridvan_adede__neriman.mp3" (RID 1).
2021/07/13 13:03:48 [cross_10633:3] Analysis: -138.150547dB / -12.049728dB (14.99s / 15.01s)
2021/07/13 13:03:48 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2021/07/13 13:03:49 [lang:3] AzuraCast Feedback Response: OK
2021/07/13 13:04:12 [lang:3] Authenticating DJ: stationdj
2021/07/13 13:04:13 [lang:3] AzuraCast DJ Auth Response: true
2021/07/13 13:04:13 [decoder:3] Method "MAD" accepted "audio/mpeg".
2021/07/13 13:04:13 [lang:3] DJ Source connected! Last authenticated DJ: stationdj - [("icy-name", "Station Name"), ("icy-genre", "Genel"), ("icy-url", "http://www.stationname.com"), ("icy-irc", "#audiorealm"), ("icy-icq", "NA"), ("icy-aim", "NA"), ("icy-pub", "1"), ("icy-br", "48"), ("Content-type", "audio/mpeg")]
2021/07/13 13:04:14 [lang:3] AzuraCast Live Connected Response: true
2021/07/13 13:04:14 [input_streamer:3] Decoding...
2021/07/13 13:05:14 [live_fallback:3] Switch to audio_to_stereo_10656 with transition.
2021/07/13 13:05:27 [lang:3] Authenticating DJ: stationdj
2021/07/13 13:05:28 [lang:3] AzuraCast DJ Auth Response: true
2021/07/13 13:05:28 [camomile:3] Failed to convert "DJ BESTEE iLE T\220RK\220L\220 SAATLER - \195\150zlem \195\150zdil - T\195\188rk\195\188lere Sor Beni" from UTF-8 to UTF-8 (CamomileLibrary__CharEncoding.Configure(Config).Malformed_code)!
2021/07/13 13:05:28 [input_streamer:3] New metadata chunk ? -- DJ BESTEE iLE T?RK?L? SAATLER - Özlem Özdil - Türkülere Sor Beni.`

**Comment by ivellios1988** [comment]
Have you tried switching to a different server? I had a similar issue with my old server. The issue is gone since I switched to a new VPS in different location three days ago. Turned out there was some serious connection issue between me and my old server.

**Comment by ogrenci01** [comment]
Hi @ivellios1988 ;

I can't test it on a different server. I am sad. My VPS has private network. I don't think this is a network issue. The problem persists. This problem does not occur on all stations. It does in some.

**Comment by hottweelz** [comment]
See it all the time, its YOUR internet connection dropping and reconnecting. 110% of the time, if you can, hardwire instead of WiFi, we have 50+ Live DJs and 45 Channels... its always the users internet.

**Comment by ogrenci01** [comment]
Hello Friends;

Sorry everyone for taking your time. This problem still persists. I consider this issue as publisher issue. I'm closing it for now as I can't provide you with enough evidence. Endless thanks to the team.
