### ISSUE TITLE
Attempting an installation from scratch : it fails

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#4388]
**Using Docker installation method?**
Yes

**Host Operating System:**
Ubuntu 20.04 2 LTS

**Describe the bug:**
The install would fail rapidly. the user is root and I tried with su and su -u root 

**Steps to reproduce:**
```
$ docker -v
Docker version 20.10.7, build f0df350
:~/azuracast$ sudo ./docker.sh install
Docker is already installed! Continuing...
Docker Compose is already installed! Continuing...
ERROR: Invalid interpolation format for "installer" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"
ERROR: Invalid interpolation format for "installer" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"
mv: cannot stat 'docker-compose.new.yml': No such file or directory
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

:~/azuracast$ ls
docker-compose.installer.yml  docker.sh
:~/azuracast$
```

**Comment by SlvrEagle23** [comment]
@griffon56 I suspect the version of Docker Compose that's installed on your system may be too old for us to use the formatting we're using in our installation files.

I've added a check to the `docker.sh` utility script that will check if your Docker Compose is out-of-date during the initial installation and prompt you to update it instead of just skipping it if it's installed at all.

You can manually run this update process by running `./docker.sh install-docker-compose`.

**Comment by Esionru** [comment]
> @griffon56 I suspect the version of Docker Compose that's installed on your system may be too old for us to use the formatting we're using in our installation files.
> 
> I've added a check to the `docker.sh` utility script that will check if your Docker Compose is out-of-date during the initial installation and prompt you to update it instead of just skipping it if it's installed at all.
> 
> You can manually run this update process by running `./docker.sh install-docker-compose`.

It did not help

**Comment by Esionru** [comment]
![image](https://user-images.githubusercontent.com/315414/125162557-0634b080-e1a2-11eb-8df5-c5b89be77e9e.png)
![image](https://user-images.githubusercontent.com/315414/125162571-13519f80-e1a2-11eb-8966-535ea3a89cf7.png)

**Comment by SlvrEagle23** [comment]
@Esionru At the azuracast directory (`/var/azuracast`), type `ls -lah` and let me know what that returns.

I think there's a permissions issue preventing the new installer from writing to that directory, but the new installer runs as root and shouldn't be running into issues like that at all.

**Comment by Esionru** [comment]
> @Esionru At the azuracast directory (`/var/azuracast`), type `ls -lah` and let me know what that returns.
> 
> I think there's a permissions issue preventing the new installer from writing to that directory, but the new installer runs as root and shouldn't be running into issues like that at all.

![image](https://user-images.githubusercontent.com/315414/125163714-da1c2e00-e1a7-11eb-8b19-5bb9c1567d8c.png)

**Comment by SlvrEagle23** [comment]
@Esionru What host operating system are you using? I want to try to reproduce this locally but on every Ubuntu/Debian server I test, it works fine.

**Comment by tegelane89** [comment]
I have seemingly same failure as @Esionru  screenshot in comment [with screenshot](https://github.com/AzuraCast/AzuraCast/issues/4388#issuecomment-877628350)
I tried to spin up fresh Ubuntu 20.04 2 LTS virtual machine to see if it would happen with fresh install.  It did. 
Here is what I did:
```
sudo apt-get update && sudo apt-get dist-upgrade
sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io

sudo su -
mkdir -p /var/azuracast
cd /var/azuracast
curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/main/docker.sh > docker.sh
chmod a+x docker.sh
./docker.sh install
```

I hope it helps.

**Comment by SlvrEagle23** [comment]
This is definitely a permissions issue, but since the VPSes I'm spinning up don't have those same permission issues, I can't see exactly what it is we need to fix.

If I could take a look at one of your installations I could probably get it fixed rather quickly, otherwise if you could let me know who your hosting provider is (if you're doing a standard VM, are you just using the stock Ubuntu ISO?) so I can possibly replicate the same setup.

The reason the issue here is tricky is because we're actually running the installer program as root specifically so it'll have no permission issues with regard to the host filesystem, only to discover it's still having issues with regard to the host filesystem. Always a fun time.

**Comment by steevLP** [comment]
i am ending up in the same issuse :/
is there a fix i am running on `Debian GNU/Linux 10 (buster)`

**Comment by SC2Mitch** [comment]
It's clear that users are indeed running into this issue, I'm checking on my local machine to see if I can produce anything helpful to diagnose this further.

**Comment by MichaelLeeHobbs** [comment]
Same issue Centos 7.8 as root or sudo user.

**Comment by Esionru** [comment]
I changed my provider to DigitalOcean, now it's good

**Comment by SC2Mitch** [comment]
> I changed my provider to DigitalOcean, now it's good

Which hosting provider was you using?

**Comment by MichaelLeeHobbs** [comment]
Work around, sort of.

1. `./docker.sh install`
2. Don't answer any questions
3. Open a new terminal
4. `docker ps` find the ID of the installer
5. `docker exec -it ID bash` replacing ID with the ID of the installer container
6. Inside installer container `azuracast_install`
7. go through the install steps
8. `exit` exit the container
9. `docker stop ID` replacing ID with the ID of the installer container
10. Go back to original terminal and watch it complete the install process

After all that I get bad gateway.

Baremetal Setup - Dell R410
```
[root@ubersrc01 azuracast]# cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)
[root@ubersrc01 azuracast]# docker -v
Docker version 19.03.12, build 48a66213fe
[root@ubersrc01 azuracast]# docker-compose -v
docker-compose version 1.29.2, build 5becea4c
[root@ubersrc01 azuracast]#
```

I was checking all the logs to add to this and found. `2021-07-11  1:30:31 1207 [Warning] Access denied for user 'azuracast'@'172.28.0.5' (using password: YES)`

I'll dig into that tomorrow.

**Comment by tegelane89** [comment]
Seems like [#4388](https://github.com/AzuraCast/AzuraCast/issues/4388) fixed it for me.

To answer questions:  I was running stock ubuntu iso that can be obtained [here](https://ubuntu.com/download/desktop/thank-you?version=20.04.2.0&architecture=amd64). 

Attached is commands and output from error (probably not really useful anymore..)
[install-script-commands-and-output.txt](https://github.com/AzuraCast/AzuraCast/files/6796454/install-script-commands-and-output.txt)

**Comment by SlvrEagle23** [comment]
@tegelane89 Does the updated installer have any errors at all? Does it still ask the same language/setup/etc questions?

**Comment by Esionru** [comment]
> > I changed my provider to DigitalOcean, now it's good
> 
> Which hosting provider was you using?

[https://adminvps.ru/](https://adminvps.ru/) Russian hosting

**Comment by Esionru** [comment]
> This is definitely a permissions issue, but since the VPSes I'm spinning up don't have those same permission issues, I can't see exactly what it is we need to fix.
> 
> If I could take a look at one of your installations I could probably get it fixed rather quickly, otherwise if you could let me know who your hosting provider is (if you're doing a standard VM, are you just using the stock Ubuntu ISO?) so I can possibly replicate the same setup.
> 
> The reason the issue here is tricky is because we're actually running the installer program as root specifically so it'll have no permission issues with regard to the host filesystem, only to discover it's still having issues with regard to the host filesystem. Always a fun time.

sent you a mail with login parameters

**Comment by SlvrEagle23** [comment]
@Esionru After looking at your installation, I was able to isolate this permissions issue to a problem where specifically PHP, running inside the container, is denied permissions to access the folder, even though the account it's running as has permissions to create/modify files in that directory.

Frankly, I'm a little baffled by this, and none of us on the team have seen a problem like this pop up before.

In any case, the latest updates to the installer mean even if the fancy PHP installer doesn't work properly for any reason, it will still "fail safe" to a working installation, where you can then modify the environment files as needed.

This should ensure installations can continue even if permissions are, for whatever reason, not working right for PHP itself.

**Comment by SlvrEagle23** [comment]
I worked with @Vaalyn to examine this problem and we were able to find an issue with the actual command line parsing in PHP, where it was passing the incorrect path to the installer. This should now be fixed.

**Comment by MichaelLeeHobbs** [comment]
After doing an uninstall then reinstall all worked well!
