### ISSUE TITLE
Traditional Install | File not found

### ISSUE THREAD

**Issue by LetsBlade** [AzuraCast/AzuraCast#439]
- Traditional
- Ubuntu 16.04.03 LTS (Server Version)

Hey, i made a Clean Ubuntu Installation (on VMWare, ESXI 6.5)
then i went trough the Steps for installing git and cloning the git.
After that i used the Commands to start the Installation.

Everything seems to worked good (i think?) 
![screenshot_5](https://user-images.githubusercontent.com/24629847/36345948-1d8f4490-1435-11e8-9896-5fe121b58411.png)

Then i looked at my IP to start with the Webinterface Part but when i open the Website with
http://[Internal IP]/ i just get the Message "File not Found".
![screenshot_6](https://user-images.githubusercontent.com/24629847/36345949-1dab0914-1435-11e8-9bc7-81f10059f0ad.png)

I never Worked with Git, AzuraCast or Ubuntu so it would be nice if someone Could Help me. 

Thanks, 
Blade aka Nico

**Comment by LetsBlade** [comment]
I Think i found the Problem but not how to Solve it...

In the nginx Settings is the Document Root "/var/azuracast/www/www/web"
But after the Installation there is not even a "var/azuracast/www/www" folder...
Is there a way to see a Log from the Installation or do i need to Record it for myself and Watch it at 0.25?

**Comment by LetsBlade** [comment]
Problem Found and Solved. 

`mkdir -p /var/azuracast/www
cd /var/azuracast/www
git clone https://github.com/AzuraCast/AzuraCast.git .`

While Doing this Git Created a new Folder Called AzuraCast 

I Changed the Following: 
`mkdir -p /var/azuracast
cd /var/azuracast/
git clone https://github.com/AzuraCast/AzuraCast.git .
mv /var/azuracast/AzuraCast /var/azuracast/www`

Then i made the last Steps and now its Working^^

**Comment by SlvrEagle23** [comment]
@LetsBlade That last period in the `git clone` command should be preventing that, cloning it instead into the current directory instead of a folder called AzuraCast. Glad you were able to find and resolve the issue!

**Comment by LetsBlade** [comment]
Maybe it was a Error from my side or Something that i missed to copy the period^^ 

Other Question: Is it Possible to change the Port from 80 to something other like 81? I have a Raspberry Running on 80 and the AzuraCast on 80 but both are running with one External IP. So it would be nice if i can create Custom Pages at AzuraCast or change the Port from 80 to 81 @SlvrEagle23

**Comment by LetsBlade** [comment]
Oh and when visiting the Site with https the Station isnt Working correctly (No Sound) so im Sitting still on Port 80
