### ISSUE TITLE
Stream skipping, glitching and stopping 

### ISSUE THREAD

**Issue by controlfreakstudio** [AzuraCast/AzuraCast#4398]
**Using Docker installation method?**
Yes

**AzuraCast version:**
ran docker update successfully
**Host Operating System:**
ubuntu 20.04 vps

**Describe the bug:**
degrading performance with stream skipping and glitching to eventually not playing and now not even actually starting autodj
WARN slave/slave_startup process has 65536 max file descriptor limit

I watched resources while stream was still playable which I would not describe as maxed, however I did chuck more RAM atr the vps. There is effectivly 95-125% of a free vcpu at all times.

initially, on reboot, or restart of frontend/backend you'd get play for a song or 3 but then glitched out again

now, autodj wont even actually start despite of what the web interface says and stream is stuck offline

Soap Log when restarting:
2021/07/11 22:26:40 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2021/07/11 22:28:20 [lang:3] AutoDJ could not be initialized within the specified timeout.
Soap log if try to live connect:
2021/07/11 22:44:12 [lang:3] AzuraCast Live Disconnected Response: true
2021/07/11 22:44:17 [dummy:3] Source failed (no more tracks) stopping output...

Icecast error log is just line after line of this:
[2021-07-11  22:25:52] WARN slave/slave_startup process has 65536 max file descriptor limit

I Have:
Used the docker update process which was successful
Flushed all cache manual cli
flushed all and did the manual tasks in web admin debug
when this occurs there are zero messages pending in the bottom of debug admin page
stab in the dark I changed the ulimit in the os, i added a docker ulimit to conf

I see reference to this message in 2 other tickets but there is no useful discourse or actions in either.

Anything I can do to avoid a wipe and rebuild?

cheers

**Comment by Vaalyn** [comment]
The Icecast `WARN` log entry is unrelated to this issue. This message is from the Icecast-kh version and is just an information on what file descriptor limit the machine currently has set. Why this is shown as a `WARN` beats me but it's how it is expected as far as I was able to see when I looked into this message.

Regarding the skipping and glitching of the stream, could you open `top` and post the following line from it?
```
%Cpu(s):  0.3 us,  0.3 sy,  0.0 ni, 98.1 id,  1.2 wa,  0.0 hi,  0.0 si,  0.0 st
```

Also, how many vCPUs does your machine have?

**Comment by controlfreakstudio** [comment]
well with autodj soap auto not really running and unavble to get it to start not sure how useful that is. 2 vcpus and its sitting around zero. like i said there was 1 to 1.5 vcpu available when it was last running and the glitching started

**Comment by controlfreakstudio** [comment]
%Cpu(s):  1.2 us,  0.8 sy,  0.0 ni, 97.8 id,  0.2 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   3840.1 total,   1297.9 free,   1102.2 used,   1440.0 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   2453.2 avail Mem

**Comment by Vaalyn** [comment]
It seems like it should have enough resources left to function correctly.

For some reason though LS is not getting a response from the request for the next song to play:
```
AutoDJ could not be initialized within the specified timeout.
```

In most cases I have encountered this was due to high system load but this seems to not be the case here which would leave to thing that it might be some kind of error encountered in the AzuraCast AutoDJ that gives LS the next song to play.

Could you look into the `AzuraCast Application Log` and post it here?
Maybe there is something in there that could help us figure out where this is coming from.

**Comment by controlfreakstudio** [comment]
apologies but can you clarify for docker? I dont see application log in teh web interface, and I dont see a container flag to get it via docker

**Comment by Vaalyn** [comment]
You can get the log via the web interface `Administration` -> `System Logs` -> `AzuraCast Application Log` or via `docker-compose logs web` on the terminal but for copy and pasting the web interface should be easier.

**Comment by controlfreakstudio** [comment]
[2021-07-11T23:44:01.873123+00:00] AzuraCast.ERROR: Remote server has no mount points listed.

[2021-07-11T23:44:01.874230+00:00] AzuraCast.WARNING: Could not fetch XML data; falling back to public JSON.

[2021-07-11T23:44:01.965409+00:00] AzuraCast.ERROR: Response does not contain a "source" listing; the stream may be hidden or misspelled.

**Comment by controlfreakstudio** [comment]
ok im back to playing now will monitor for skip and glitch

based on above message i went to mount points, made an alternate one the default, restarted and it strarted stream no problem
edited unticked and reticked all applicable fields and switched back to the original default mount point, restarted and also started playing...

seems to be populating next plays as well. monitoring resources and glitch

**Comment by controlfreakstudio** [comment]
seems ok for now. resources afre fine. no idea how my original and untouched mountpoints got borked other than maybe update?

rebuilding them worked. sorry for the hassle thanks for the fast set of eyes.
