### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#4399]
I tried to do a recent update and couldn't do it due to errors in the new changes made.

error image: https://prnt.sc/1ae52y0

**Comment by SpeedyCharly** [comment]
Getting exact same error...
Here is full Putty session log;
[Last Update Session.txt](https://github.com/AzuraCast/AzuraCast/files/6799507/Last.Update.Session.txt)
And this is my Azura front page;
![Image1](https://user-images.githubusercontent.com/66107794/125250270-0a58ef00-e2c4-11eb-86a3-60773ec70ae9.jpg)

**Comment by SC2Mitch** [comment]
I'm looking into this issue, for the time being I suggest that you roll back to a snapshot or deploy a backup. 

Also can you use the format, more information the better.

**Comment by SC2Mitch** [comment]
Unable to verify this bug, when you run the command `./docker.sh update` and it brings you to the "select language" what do you type in? 

Here's my logs. https://gist.github.com/SC2Mitch/66d6eac33a528de0e4b3e2567e6647b5

**Comment by Marcioghiraldelli** [comment]
@SC2Mitch  I'm using the version
Rolling Release #2b70f65 (2021-06-29 2:58) • Docker • PHP 8.0
Usually he appeared to choose the language, I chose Brazil and then he presented the errors and did not proceed.

**Comment by Marcioghiraldelli** [comment]
my azuracast is working but unable to get new updates due to the aforementioned error.
It says that the folders already exist and that they need to be renamed, but the system already did this normally.

**Comment by SC2Mitch** [comment]
Can you provide us with your docker logs? Ideally run the update again and run the logs, something useful might show

**Comment by Marcioghiraldelli** [comment]
alright, how can i generate the log?

**Comment by SC2Mitch** [comment]
run `cd /var/azuracast` then `docker-compose logs -f` in that directory.

**Comment by SlvrEagle23** [comment]
@SpeedyCharly @Marcioghiraldelli It looks like neither of you installed AzuraCast in the location we typically recommend it be installed in (`/var/azuracast`), which is why your installations are having this problem when most of our installations aren't.

I'll look into getting it fixed shortly.

**Comment by SlvrEagle23** [comment]
@SpeedyCharly @Marcioghiraldelli Try updating again and see if you run into any similar issues.

If you see similar errors, you may need to spin down all of your existing containers and let the updater spin up new ones by running:

```
docker kill $(docker ps -q)
docker rm $(docker ps -a -q)
```

...and then running the updater again.

**Comment by SpeedyCharly** [comment]
Auxiliary question;  Is there a quick and easy way to revert back to a standard Azura installation.  Preferably one where we wouldn't lose all uploaded media... I live in the boonies and uploading 2 gigs is a 6 hrs job...

**Comment by SlvrEagle23** [comment]
@SpeedyCharly You can specify a version number for an AzuraCast installation, but it's not possible to roll backwards from a rolling-release version to that version, only to move forward in time (i.e. from stable to rolling, or from an older rolling to a newer stable).

This update not working correctly shouldn't result in any sort of data loss for you, though. Just reupdating (or, at worst case, following the steps I specified above) should correct the situation and have your installation back as it was.

**Comment by SpeedyCharly** [comment]
@SlvrEagle23 Whatever changes you've done on your side were successful - updated without a hitch this time round.  Danke Mein Herr!

**Comment by SlvrEagle23** [comment]
Good to hear; assuming from this and my own checks that things are resolved at this point. If anyone runs into similar errors while updating, they can run the commands from my earlier post and it will clean up the environment by stopping all containers (if you're running other non-AzuraCast services, you'll need to start those containers again manually as well).
