### ISSUE TITLE
Metadata on mobile ?

### ISSUE THREAD

**Issue by RainbowDash53** [AzuraCast/AzuraCast#440]
Hi, I don't really know how to explain this, but for some stations when you hit the play button, on the screenshot 1 we can see the title of the show / current song, but when I go to the public page of my station, only the URL it showed(screenshot 2) :/

Screen 1: https://i.imgur.com/UZHir5I.jpg
Screen 2: https://i.imgur.com/oUinVNQ.jpg

Could you add this or send me a link of a player who do this ? Thank's in advance :)

**Comment by SlvrEagle23** [comment]
@RainbowDash53 I'm not sure about iOS (as I don't have any iOS devices to test with), but I know Android has a special API that it uses to set rich metadata for the currently playing song, and both the public and private pages on AzuraCast both use this.

It's likely that, as a default, any metadata that iOS is pulling is coming directly from the MP3 radio stream itself; this is sometimes a spotty source of metadata, as changes don't always make it through correctly.

I'll look into it and see if there's any more effective way to provide this info to iOS, a-la Android's `mediaSession`.

**Comment by RainbowDash53** [comment]
If you need somebody to test, I'm here ;)

**Comment by SlvrEagle23** [comment]
@RainbowDash53 At the moment, it looks like it's somewhat bad news...iOS doesn't support the MediaSession API, as it's currently just a proposed API standard (and the proposer is Google, so...ya know...) and they have no equivalent on the iOS end. :(

**Comment by amavarick** [comment]
Consider an online mobile emulator:
http://www.mobilephoneemulator.com

Here are some additional options:
https://www.webdesignerdepot.com/2012/11/6-free-mobile-device-emulators-for-testing-your-site/

These may be able to get you to the 90% of testing before incorporating live users in your testing?

**Comment by RainbowDash53** [comment]
@amavarick What the use of that here ? '-'

**Comment by SlvrEagle23** [comment]
@amavarick I have no difficulty testing out how a web page might _render_ on mobile browsers. The interaction in question here is whether the OS-level media playback controls will integrate correctly with my web application, which sites like that won't test.

In the interest of avoiding confusion here, I'm closing this issue as currently unresolvable on my end. If further advances happen with the iOS MediaMetadata/MediaSession API integration, or if they (perhaps more likely) roll their own thing just to be difficult, we can revisit the issue.

**Comment by amavarick** [comment]
So sorry guys, I must have posted to the wrong post.  Thought I was putting to the one about viewing the public page metadata.
