### ISSUE TITLE
Shoutcast v1 remote relay configuration incorrect in v0.13.0

### ISSUE THREAD

**Issue by shaksp** [AzuraCast/AzuraCast#4408]
**Using Docker installation method?**
Yes

**AzuraCast version:**
v0.13.0

**Host Operating System:**
Ubuntu 20.04

**Describe the bug:**
I have one Azuracast acting as AutoDJ pushing streams to 1x External Icecast (2.4.4) server 1x External Shoutcast v1 server setup as Relays.

Just upgraded from Azuracast 0.12.x to v0.13.0 using the docker upgrade method. Icecast works OK however, the Shoutcast relay stopped working. Liquidsoap shows the following error:

2021/07/16 15:17:26 [relay_2:3] Connecting mount Use [name] for source@xxxxx...
2021/07/16 15:17:26 [relay_2:2] Connection failed: bad answer
strange error flushing buffer ... 
2021/07/16 15:17:26 [relay_2:3] Will try again in 3.00 sec.

I have checked the liquidsoap configuration and it seems that even though I have selected Shoutcast V1 as the server type, the configuration sets it up as a output.icecast connection instead of output.shoutcast with appropriate shoutcast settings. I have manually entered it as instead and now it is working. So it seems the Relays configuration for Shoutcast V1 has broken during the update.

Liquidsoap Config (generated and doesn't work):
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=64, id3v2=true), id="relay_2", host = "XXX", port = 9980, password = "XXX", name = "ZZZ Radio", description = "", genre = ""ZZZ", url = "https://www.zzz.com/", public = false, encoding = "UTF-8", protocol="http", radio)

Manual Config (works):
output.shoutcast(%mp3(samplerate=44100, stereo=true, bitrate=64, id3v2=true), id="relay_2", host = "XXX", port = 9980, password = "XXX", name = ""ZZZ Radio", genre = "ZZZ", url = "zzz", public = false, encoding = "UTF-8", radio)

**Steps to reproduce:**
1. Go to Remote Relays
2. Create a Shoutcast v1 Relay

**Expected behavior:**
Shoutcast v1 Relay should connect successfully with settings input

**Relevant logs:**
2021/07/16 15:17:26 [relay_2:3] Connecting mount Use [name] for source@xxxxx...
2021/07/16 15:17:26 [relay_2:2] Connection failed: bad answer
strange error flushing buffer ... 
2021/07/16 15:17:26 [relay_2:3] Will try again in 3.00 sec.

**Comment by SlvrEagle23** [comment]
@shaksp This should now be fixed as of the latest Rolling Release version. We will incorporate this same fix into the next Stable release once that is tagged.
