### ISSUE TITLE
Web Proxy doesn't work for non-standard ports

### ISSUE THREAD

**Issue by lurch89** [AzuraCast/AzuraCast#4409]
**Using Docker installation method?**
Yes

**AzuraCast version:**
Rolling Release #64b7d83

**Host Operating System:**
Ubuntu 20.04 Server

**Describe the bug:**
During installation, if non-standard ports are chosen for stations (ex not 8000+), the Web Proxy function does not auto-adjust, and results in 404's when trying to play stations. The link is correct (/radio/(port #)/radio.mp3) but thhere is nothing there unless the NGINX configuration is modified.

**Steps to reproduce:**
Follow installation wizard to set non-standard ports for stations (in my setup I used 12000 to 12499).
Activate Web Proxy checkbox in Settings
Go to a public page for a station and try to play the station. 

**Expected behavior:**
Station should stream via the web interface and use /radio/(port #)/radio.mp3 as a link.

**Relevant logs:**
I didn't capture logs.

**Screenshots:**
N/A

**Device(s):**

- Device: Desktop
- OS: Windows 10 Pro
- Browser: Chrome
- Version: 91

**Additional context:**

**Comment by lurch89** [comment]
Location of needed code change: `/etc/nginx/conf.d/azuracast.conf` on azuracast_web container:

File that needs to be changed/modified/wizarded is `/etc/nginx/conf.d/azuracast.conf`
`
    location ~ ^/radio/(8[0-9][0-9]0)(/?)(.*)$ {
        proxy_buffering           off;
        proxy_ignore_client_abort off;
        proxy_intercept_errors    on;
        proxy_next_upstream       error timeout invalid_header;
        proxy_redirect            off;
        proxy_connect_timeout     60;
        proxy_send_timeout        21600;
        proxy_read_timeout        21600;

        proxy_set_header Host localhost:$1;
        proxy_pass http://stations:$1/$3?$args;
    }

    # Reverse proxy the Liquidsoap harbor inputs to allow for streaming.
    location ~ ^/radio/(8[0-9][0-9]5)(/?)(.*)$ {
        resolver 127.0.0.11;

        proxy_buffering           off;
        proxy_ignore_client_abort off;
        proxy_send_timeout        21600;
        proxy_read_timeout        21600;

        proxy_pass http://stations:$1/$3;
    }
`
Change the regex to accomodate tthe ports specified during setup.

**Comment by SlvrEagle23** [comment]
@lurch89 This previously wouldn't have been possible, but given the recent development of our new installer script, it's now possible and in fact rather easy for us to send custom port ranges over to nginx.
