### ISSUE TITLE
Public page not working

### ISSUE THREAD

**Issue by nikksno** [AzuraCast/AzuraCast#441]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Ubuntu 16

Very simply, the public page doesn't work for a newly created station, showing instead a 500 error, specifying: `Station not found! GetStation.php : 61`. Here is [or should be] my public page: https://az.os.vu/public/1420. The same issue occurs on the demo instance, both for AzuraCast test, and for newly created stations inside the demo. Am I missing something here?

Thank you so much for the amazing work.

**Comment by SlvrEagle23** [comment]
@nikksno If your station's "short name" is solely numerical, the system won't be able to tell the difference between that and a legitimate numeric ID number, as (albeit unlikely in this case) it could actually be one. Short names should have at least one letter or non-numeric character.

**Comment by nikksno** [comment]
Thank you so much, didn't bother trying as I saw that happening on your demo instance as well, sorry to have bothered you for such a small thing. Before I close this, can I simply ask you what client you suggest using to interact with the station? I've found an app called Transistor on F-Droid, which is super cool, but of course it's only to listen to the audio stream. I think an IceCast client is what I'm looking for, but I can only find apps for streamers, albeit I'm looking for an app that listeners can use and use the request / skip functionality that the public page presents. What do you suggest using? [Also, I've sent you an email about external storage, I promise I won't bother you further ;]
Thank you so much for the great work. I'll definitely donate as soon as our radio starts getting some money in our non-profit's cash reserve.

**Comment by SlvrEagle23** [comment]
@nikksno No worries about the issue, it's an internal limitation of AzuraCast that I should probably document better in any case.

As for listening clients...well, there isn't one that will pack in all the extra metadata that AzuraCast itself packs in. That's part of why I put the public players in there; so anyone wanting all that data could just pull the source code of the public page, see how it works and reimplement it in their own sites/apps.

Your average VLC, Media Player Classic, etc will all do just fine at playing the radio stream.

**Comment by nikksno** [comment]
Ahh ok so it's all rather specific to AC, not to the underlying streaming protocol itself, therefore unless some is aware of this project and implements stuff accordingly, no interaction, just listening to the audio stream, correct?

**Comment by SlvrEagle23** [comment]
@nikksno Correct, this is all added metadata that AzuraCast adds to the picture. The raw MP3 stream will generally just contain the title and artist.

**Comment by nikksno** [comment]
Ok thank you once again
