### ISSUE TITLE
[Bug]:  Some but not all stations play "Stream Offline" and there is no output

### ISSUE THREAD

**Issue by Deiiji** [AzuraCast/AzuraCast#4413]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #26fd358 (2021-07-19 18:38) • Ansible • PHP 8.0

### What happened?

Hello
2 stations from 5 play "Stream Offline" in metadata but here is no output,  liquidsoap and icecast are running, restarting all even full upgrade don't help, all stations has same media pool then is not a problem of a single file ....
Creating new mountpoint  make no change for default mountpoint (no output) one but stream appears on new one and all pages show played sound, default

### Relevant log output

```shell
2021/07/20 06:04:24 [ffmpeg:3] [mp3 @ 0x7f3d0804f040] Estimating duration from bitrate, this may be inaccurate
2021/07/20 06:04:25 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/pool/Oni/Doo Wap/The Clickettes - Where Is He.mp3".
2021/07/20 06:04:25 [lang:3] AutoDJ is ready!
2021/07/20 06:04:25 [local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
strange error flushing buffer ... 
2021/07/20 06:04:25 [local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2021/07/20 06:04:25 [local_1:3] Will try again in 3.00 sec.
2021/07/20 06:04:29 [local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
strange error flushing buffer ... 
2021/07/20 06:04:29 [local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
...
...
etc etc
```

**Comment by Abqehebter** [comment]
I can confirm this after updating to Rolling Release #26fd358 (2021-07-19 18:38) nothing works there anymore.

**Comment by SC2Mitch** [comment]
I am investigating this issue now, please be patient and bare with me, as Ansible methods are officially unsupported by our team.

**Comment by Abqehebter** [comment]
@SC2Mitch Addendum from me: I use Docker.

**Comment by kemecs** [comment]
this is also my problem
since I updated yesterday
native instalation

2021/07/20 14:48:51 [local_1:3] Connecting mount /folkradio.mp3 for source@127.0.0.1...
2021/07/20 14:48:51 [local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
strange error flushing buffer ...
2021/07/20 14:48:51 [local_1:3] Will try again in 3.00 sec.



Powered by AzuraCast • Rolling Release #26fd358 (2021-07-19 18:38) • Docker • PHP 8.0
Like our software? Donate to support AzuraCast!

**Comment by Deiiji** [comment]
Creating new mountpoint make station working but stream is only on that new one and I have only two stations affected, always two the same. I am not sure but is possible that those are two the oldest ones.

**Comment by kemecs** [comment]
i only have one mount point because i only have one radio in the system, yet no reason

**Comment by Deiiji** [comment]
Something that I noticed, when I did update --full is that installer checked several times for liquidsoap installation, just after  having build that last. It may been something in correlation, perhaps or may been not .

**Comment by ITC-Media** [comment]
Same problem here: after updateing a docker installation the stream wont run. All is see is "Stream offline".

**Comment by Abqehebter** [comment]
For me "Stream Offline" appears but only for the stations where I have specified remote relays, can anyone confirm this?

**Comment by ITC-Media** [comment]
I have no remote relays configured and only one mount point

**Comment by SC2Mitch** [comment]
How many of you guys are using ShoutCast?

**Comment by Abqehebter** [comment]
I use Icecast2.

**Comment by kemecs** [comment]
I don't use ShoutCast either!

only the embedded Icecast 2.4.0-kh15-ac1

**Comment by joshms123** [comment]
Also having this issue; using icecast.

**Comment by joshms123** [comment]
Removing the mountpoints and re-adding them seemed to work for me. Strange!

**Comment by SlvrEagle23** [comment]
A bunch of folks seem to be experiencing this issue, but we're not seeing a lot of logs to indicate why that's the case.

Do you see any logs (in the AzuraCast application logs, or the station's Liquidsoap log, or when updating, etc.) that would suggest what the problem is?

**Comment by Deiiji** [comment]
Same here, all stations is using Icecast even if I have ShoutC
ast installed and SlvrEagle, you still have access to server, I think, if you shill have right key

**Comment by SC2Mitch** [comment]
Okay, my findings are as follows

I've span up a test instance with 30 stations, 27 stations successfully loaded with a default mount point, 3 of them failed and refused to boot properly, leading to a Liquidsoap error being returned in the console. 

`web_1                      | [2021-07-21T01:24:23.851903+00:00] AzuraCast.ERROR: Remote server has no mount points listed. {"response":"<?xml version=\"1.0\"?>\n<icestats>\n  <admin>icemaster@localhost</admin>\n  <banned_IPs>0</banned_IPs>\n  <build>133-g4bdfa25</build>\n  <client_connections>15</client_connections>\n  <clients>1</clients>\n  <connections>49</connections>\n  <file_connections>0</file_connections>\n  <host>crosshost.ml</host>\n  <listener_connections>0</listener_connections>\n  <listeners>0</listeners>\n  <location>AzuraCast</location>\n  <outgoing_kbitrate>0</outgoing_kbitrate>\n  <server_id>Icecast 2.4.0-kh15-ac1</server_id>\n  <server_start>21/Jul/2021:01:21:43 +0000</server_start>\n  <source_client_connections>0</source_client_connections>\n  <source_relay_connections>2</source_relay_connections>\n  <source_total_connections>2</source_total_connections>\n  <sources>0</sources>\n  <stats>0</stats>\n  <stats_connections>0</stats_connections>\n  <stream_kbytes_read>0</stream_kbytes_read>\n  <stream_kbytes_sent>0</stream_kbytes_sent>\n</icestats>\n"} {"station":{"id":30,"name":"Test32"}}
`

Despite the fact it already has a Mountpoint existing: 
https://puu.sh/HXTBP/376dc013ac.png

I'm unsure as to why this is happening when the mount points infact already exist. I'm wondering if this is perhaps a upstream issue with Liquidsoap?

**Comment by ITC-Media** [comment]
I confirm the quick solution to this error is to delete the mountpoint with error and make a new mountpoint with the same configuration. then restart the server.

**Comment by YosefAdPro** [comment]
> I confirm the quick solution to this error is to delete the mountpoint with error and make a new mountpoint with the same configuration. then restart the server.
> 
> move IT Radio - [www.itclive.de](http://www.itclive.de)

Thanks!



Some logs that might help
```
[2021-07-21T07:41:04.107035+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to stations port 8040: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://stations:8040/admin/stats [] {"station":{"id":50,"name":"TEST - Copy"}}
[2021-07-21T07:41:08.537237+00:00] AzuraCast.ERROR: Supervisor fault: BAD_NAME: station_49:station_49_backend {"faultString":"BAD_NAME: station_49:station_49_backend","faultCode":10} []
[2021-07-21T07:41:08.542239+00:00] AzuraCast.ERROR: Supervisor fault: BAD_NAME: station_49:station_49_frontend {"faultString":"BAD_NAME: station_49:station_49_frontend","faultCode":10} []

[2021-07-21  08:53:29] WARN slave/slave_startup process has 65536 max file descriptor limit
[2021-07-21  08:53:42] WARN xml/parsing warning: 
[2021-07-21  08:53:42] WARN xml/parsing skipping element "server" parsing "relay" at line 54
[2021-07-21  08:53:42] WARN xml/parsing warning: 
[2021-07-21  08:53:42] WARN xml/parsing skipping element "port" parsing "relay" at line 55
[2021-07-21  08:53:42] WARN xml/parsing warning: 
[2021-07-21  08:53:42] WARN xml/parsing skipping element "mount" parsing "relay" at line 56
[2021-07-21  08:53:42] WARN slave/slave_startup process has 65536 max file descriptor limit
[2021-07-21  08:58:30] WARN xml/parsing warning: 
[2021-07-21  08:58:30] WARN xml/parsing skipping element "server" parsing "relay" at line 54

```

**Comment by stardevelop** [comment]
Same problem here. After upgrading to Rolling Release #b6c1c21 (2021-07-20 21:35) • Docker • PHP 8.0, all stations are OFFLINE.
Restarting services and server did not help.

**Comment by stardevelop** [comment]
I am using remote Media Storage Location through Dropbox and I could make stations back online by deleting default Mount Point and creating a new one on each station but now On-Demand Media is not working and no media is displayed.

**Comment by NicoxDJ** [comment]
Same problem here...

What I realize is that the Liquidsoap is not connected to the IceCast:
![](https://i.imgur.com/uDVn0uc.png)

**Comment by Vaalyn** [comment]
We have found something that might point us to why this issue occurs.

Could you all check if your `Icecast Configuration` contains the following block at the bottom of the config?

```xml
<relay>
    <server></server>
    <port></port>
    <mount></mount>
    <local-mount>/radio.mp3</local-mount>
</relay>
```

**Comment by NicoxDJ** [comment]
@Vaalyn yes, I do have it:
```
    <relay>
        <server></server>
        <port></port>
        <mount></mount>
        <local-mount>/live192</local-mount>
    </relay>
```

**Comment by Vaalyn** [comment]
> @Vaalyn yes, I do have it:

Do you have any relays configured (I'm guessing no)?

**Comment by NicoxDJ** [comment]
> Do you have any relays configured (I'm guessing no)?

Nope... or if it's on another place?
![](https://i.imgur.com/rl7kg6Z.png)

**Comment by Abqehebter** [comment]
> Could you all check if your Icecast Configuration contains the following block at the bottom of the config?

Here, there are many of them...
```
<relay>
        <server></server>
        <port></port>
        <mount></mount>
        <local-mount>/station1.mp3</local-mount>
    </relay>
    <relay>
        <server></server>
        <port></port>
        <mount></mount>
        <local-mount>/station1-aac.mp3</local-mount>
    </relay>
    <relay>
        <server></server>
        <port></port>
        <mount>/backup.mp3</mount>
        <local-mount>/backup-relay.mp3</local-mount>
    </relay>
```

**Comment by SC2Mitch** [comment]
Thanks for the information guys, we may of located the issue, thanks for being patient.

**Comment by SlvrEagle23** [comment]
This should now be fixed as of the latest Rolling Release upgrade.

It was one of those bizarre edge cases caused by our increasing "strictness" of code, which is ironically intended to avoid edge cases as much as possible.

Sorry to everyone for the inconvenience and thank you all for your patience, and thank you to @Vaalyn for finding the issue!

**Comment by YosefAdPro** [comment]
@SlvrEagle23 @Vaalyn Thank you for the great project!

**Comment by Abqehebter** [comment]
@SlvrEagle23 @Vaalyn Also from me a big thank you for the whole project. Can not say often enough actually :)

**Comment by Deiiji** [comment]
As usual, great job and fast fix! Thank you.
