### ISSUE TITLE
 Live broadcast recording time

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#4419]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

xx

### What happened?

It seems that there is an average recording time of a live broadcast, as you can see in the image it varies from streamer to another.
How can I make this unlimited without ending up with a few megasbytes?

img : https://prnt.sc/1dovrih

### Relevant log output

```shell
It seems that there is an average recording time of a live broadcast, as you can see in the image it varies from streamer to another.
How can I make this unlimited without ending up with a few megasbytes?

img: https://prnt.sc/1dovrih
```

**Comment by SC2Mitch** [comment]
I don't believe this is a bug, this may have been related to the connection between the DJ Client and the Host Server which caused a second or two stutter, which lead him to be disconnected, after he got reconnected, the stream considered it a 'new' broadcast and recorded it.

**Comment by Marcioghiraldelli** [comment]
@SC2Mitch 
and how can we prevent this from happening? Is there a way to increase the delay before disconnecting the connection?
