### ISSUE TITLE
[Bug]: Slim Application Error

### ISSUE THREAD

**Issue by martchyke** [AzuraCast/AzuraCast#4424]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

4 days ago I noticed that my radio stream was down when I check I discovered that there were some updates, not just Azuracast updates, but some of the other applications like Redis had updates too. I used the ./docker.sh update-self to update the command line. After that, the radio stream came back on and everything looked fine, but I discovered that after every 24 hrs, I will get a Slim Application Error on the login page of the Azuracast installation. 

Please what should I do?

**Comment by SC2Mitch** [comment]
needs docker logs, please. `cd /var/azuracast && docker-compose logs -f`

**Comment by martchyke** [comment]
Here is the log

nginx_proxy                | nginx.1     | radio.gotright.net 147.135.36.151 - - [23/Jul/2021:15:29:01 +0000] "GET /radio/8020/index.html?sid=1 HTTP/1.1" 200 1538 "-" "OnlineRadioBox HisBot (http://onlineradiobox.com/hisbot) Mozilla/5.0 (X11; Linux x86_64) Chrome/64.0.3282.140"
web_1                      | [2021-07-23T15:29:01.782116+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data {"force":false} []
web_1                      | [2021-07-23T15:29:01.829764+00:00] AzuraCast.NOTICE: Running sync task: 1-Minute Sync {"force":false} []
nginx_proxy                | nginx.1     | radio.gotright.net 142.59.114.211 - - [23/Jul/2021:15:29:01 +0000] "GET /api/nowplaying/3 HTTP/2.0" 200 1149 "https://radio.gotright.net/" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"
web_1                      | [2021-07-23T15:29:02.212092+00:00] AzuraCast.ERROR: No playable tracks were found. [] {"station":{"id":4,"name":"FADFM"}}
nginx_proxy                | nginx.1     | radio.gotright.net 24.231.97.117 - - [23/Jul/2021:15:29:06 +0000] "GET /api/nowplaying/3 HTTP/2.0" 200 1149 "https://radio.gotright.net/public/praizenation/embed?theme=light" "Mozilla/5.0 (Linux; Android 10; SAMSUNG SM-A107M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36"
nginx_proxy                | nginx.1     | radio.gotright.net 102.89.3.186 - - [23/Jul/2021:15:29:07 +0000] "GET /api/frontend/dashboard/stations HTTP/2.0" 200 3509 "https://radio.gotright.net/dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
nginx_proxy                | nginx.1     | radio.gotright.net 24.231.97.117 - - [23/Jul/2021:15:29:07 +0000] "GET /api/nowplaying/3 HTTP/2.0" 200 1149 "https://radio.gotright.net/public/praizenation/history?theme=light" "Mozilla/5.0 (Linux; Android 10; SAMSUNG SM-A107M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36"
nginx_proxy                | nginx.1     | radio.gotright.net 154.118.34.53 - - [23/Jul/2021:15:29:11 +0000] "GET /api/frontend/dashboard/stations HTTP/2.0" 403 127 "https://radio.gotright.net/dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36"
nginx_proxy                | nginx.1     | radio.gotright.net 37.208.155.238 - - [23/Jul/2021:15:29:11 +0000] "GET /api/nowplaying/1 HTTP/2.0" 200 1264 "https://radio.gotright.net/public/gospotainment_radio" "Mozilla/5.0 (Linux; Android 5.0.2; SM-G530FZ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Mobile Safari/537.36"
nginx_proxy                | nginx.1     | radio.gotright.net 75.155.37.19 - - [23/Jul/2021:15:29:11 +0000] "GET /api/nowplaying/3 HTTP/2.0" 200 1149 "https://radio.gotright.net/" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"
nginx_proxy                | nginx.1     | radio.gotright.net 102.89.3.186 - - [23/Jul/2021:15:29:11 +0000] "GET /api/frontend/dashboard/stations HTTP/2.0" 200 3508 "https://radio.gotright.net/dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
web_1                      | [2021-07-23T15:29:16.763868+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data {"force":false} []
web_1                      | [2021-07-23T15:29:17.163210+00:00] AzuraCast.ERROR: No playable tracks were found. [] {"station":{"id":4,"name":"FADFM"}}
nginx_proxy                | nginx.1     | radio.gotright.net 142.59.114.211 - - [23/Jul/2021:15:29:17 +0000] "GET /api/nowplaying/3 HTTP/2.0" 200 1149 "https://radio.gotright.net/" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"
nginx_proxy                | nginx.1     | radio.gotright.net 147.135.36.151 - - [23/Jul/2021:15:29:20 +0000] "GET /radio/8030/index.html?sid=1 HTTP/1.1" 200 504 "-" "OnlineRadioBox HisBot (http://onlineradiobox.com/hisbot) Mozilla/5.0 (X11; Linux x86_64) Chrome/64.0.3282.140"
nginx_proxy                | nginx.1     | radio.gotright.net 147.135.36.151 - - [23/Jul/2021:15:29:21 +0000] "GET /radio/8000/index.html?sid=1 HTTP/1.1" 200 1530 "-" "OnlineRadioBox HisBot (http://onlineradiobox.com/hisbot) Mozilla/5.0 (X11; Linux x86_64) Chrome/64.0.3282.140"
nginx_proxy                | nginx.1     | radio.gotright.net 147.135.36.151 - - [23/Jul/2021:15:29:21 +0000] "GET /radio/8020/index.html?sid=1 HTTP/1.1" 200 1538 "-" "OnlineRadioBox HisBot (http://onlineradiobox.com/hisbot) Mozilla/5.0 (X11; Linux x86_64) Chrome/64.0.3282.140"
nginx_proxy                | nginx.1     | radio.gotright.net 24.231.97.117 - - [23/Jul/2021:15:29:22 +0000] "GET /api/nowplaying/3 HTTP/2.0" 200 1149 "https://radio.gotright.net/public/praizenation/embed?theme=light" "Mozilla/5.0 (Linux; Android 10; SAMSUNG SM-A107M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36"
nginx_proxy                | nginx.1     | radio.gotright.net 24.231.97.117 - - [23/Jul/2021:15:29:22 +0000] "GET /api/nowplaying/3 HTTP/2.0" 200 1149 "https://radio.gotright.net/public/praizenation/history?theme=light" "Mozilla/5.0 (Linux; Android 10; SAMSUNG SM-A107M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36"
nginx_proxy                | nginx.1     | radio.gotright.net 102.89.3.186 - - [23/Jul/2021:15:29:23 +0000] "GET /api/frontend/dashboard/stations HTTP/2.0" 200 3524 "https://radio.gotright.net/dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
nginx_proxy                | nginx.1     | radio.gotright.net 37.208.155.238 - - [23/Jul/2021:15:29:26 +0000] "GET /api/nowplaying/1 HTTP/2.0" 200 1264 "https://radio.gotright.net/public/gospotainment_radio" "Mozilla/5.0 (Linux; Android 5.0.2; SM-G530FZ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Mobile Safari/537.36"
nginx_proxy                | nginx.1     | radio.gotright.net 75.155.37.19 - - [23/Jul/2021:15:29:27 +0000] "GET /api/nowplaying/3 HTTP/2.0" 200 1150 "https://radio.gotright.net/" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"
nginx_proxy                | nginx.1     | radio.gotright.net 102.89.3.186 - - [23/Jul/2021:15:29:27 +0000] "GET /api/frontend/dashboard/stations HTTP/2.0" 200 3524 "https://radio.gotright.net/dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
web_1                      | [2021-07-23T15:29:31.709097+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data {"force":false} []
web_1                      | [2021-07-23T15:29:32.070871+00:00] AzuraCast.ERROR: No playable tracks were found. [] {"station":{"id":4,"name":"FADFM"}}
nginx_proxy                | nginx.1     | radio.gotright.net 142.59.114.211 - - [23/Jul/2021:15:29:32 +0000] "GET /api/nowplaying/3 HTTP/2.0" 200 1150 "https://radio.gotright.net/" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"
nginx_proxy                | nginx.1     | radio.gotright.net 24.231.97.117 - -                                                                                                                                                              [23/Jul/2021:15:29:37 +0000] "GET /api/nowplaying/3 HTTP/2.0" 200 1150 "https://                                                                                                                                                             radio.gotright.net/public/praizenation/embed?theme=light" "Mozilla/5.0 (Linux; A                                                                                                                                                             ndroid 10; SAMSUNG SM-A107M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrows                                                                                                                                                             er/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36"
nginx_proxy                | nginx.1     | radio.gotright.net 24.231.97.117 - -

**Comment by SlvrEagle23** [comment]
@martchyke I'm not seeing anything there that would indicate a problem. You can narrow down the logs just to the web application logs by running `docker-compose logs -f web` (you can also view this same log via System Administration > Log Viewer > AzuraCast Application Log).
