### ISSUE TITLE
New Playlist Adding Error

### ISSUE THREAD

**Issue by martchyke** [AzuraCast/AzuraCast#4425]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

When we try to create a new playlist, we get an error. 

### Relevant log output

```shell
Doctrine\DBAL\Exception\NotNullConstraintViolationException at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php L125: An exception occurred while executing 'INSERT INTO station_playlists (station_id, name, type, source, playback_order, remote_url, remote_type, remote_timeout, is_enabled, is_jingle, play_per_songs, play_per_minutes, play_per_hour_minute, weight, include_in_requests, include_in_on_demand, include_in_automation, backend_options, avoid_duplicates, played_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [2, "hghs", "default", "songs", "shuffle", null, "stream", 0, 1, 0, 0, 0, 0, 3, 1, 0, 0, "", 1, 0]: SQLSTATE[HY000]: General error: 1364 Field 'queue_reset_at' doesn't have a default value
```

**Comment by SC2Mitch** [comment]
We need the version your currently using to take a look.

**Comment by SlvrEagle23** [comment]
@martchyke You're on the latest _stable_ release version? That database change was made after the most recent stable version. Did you switch from rolling release backwards to stable? This is known to cause database issues and we don't recommend doing it; you should only switch from Rolling to Stable when Stable is newer (or the same version as) your current Rolling Release version.

If you switch back to the Rolling Release channel and update, it should be fixed.

**Comment by martchyke** [comment]
Please how do I switch back to Rolling Release

**Comment by Vaalyn** [comment]
> Please how do I switch back to Rolling Release

Here is a short guide from our docs on how to switch the release channel:

https://docs.azuracast.com/en/getting-started/updates/release-channels#setting-azuracast-to-use-a-different-channel

**Comment by martchyke** [comment]
Thank you! Mr Buster @SlvrEagle23  and the Team, you guys are super heroes!

**Comment by SC2Mitch** [comment]
Glad to hear it's sorted, if you have any other issues, post a ticket!
