### ISSUE TITLE
[Bug]: A Update Error

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#4426]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

AzuraCast • Rolling Release #80d47a9 (2021-07-24 4:21)

### What happened?

Error occurred in LiquidSoap phase while updating Azuracast.
Error: https://prnt.sc/1f7fjfj

I tried both commands same problem:
```
sudo ./update.sh
sudo ./update.sh --full
```

By examining the records on the screen, I did the following and the update worked successfully. Everything looks normal. Follow:

```
cd /var/azuracast/www
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install libavdevice-dev -y
opam option depext=false
opam init
```

Everything is set up and Azuracast works. You should add this to a suitable place in the installation. I know there is no support for Ansible.

**Comment by SlvrEagle23** [comment]
@ogrenci01 Should be fixed now. :)
