### ISSUE TITLE
--remove orphan not an option

### ISSUE THREAD

**Issue by JP-FOURNIER** [AzuraCast/AzuraCast#4436]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #ec88ed7 (2021-07-26 4:40) • Docker • PHP 8.0

### What happened?

WARNING: Found orphan containers (azuracast_redis, nginx_proxy_letsencrypt, azuracast_mariadb, azuracast_web, nginx_proxy, azuracast_stations) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating azuracast_installer_run ... done

  The "--remove-orphans" option does not exist.

i try to --remove-orphans but gor an error

**Comment by Vaalyn** [comment]
The `--remove-orphans` is a flag of the `docker-compose down` command.

In order to use it you have to enter it like this:
```
docker-compose down --remove-orphans
```
