### ISSUE TITLE
Skip audior Error CORS

### ISSUE THREAD

**Issue by JMultimidia** [AzuraCast/AzuraCast#4446]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.10.3

### What happened?

I created a function in javascipt to skip the music using api and it always gives CORS error. In the azuracast configuration I already defined "*".

The following error follows:

![2021-08-03_14-04](https://user-images.githubusercontent.com/20319612/128056775-dfb558d9-cdbe-4dd1-bc15-cfbe452da123.png)
![2021-08-03_14-04_1](https://user-images.githubusercontent.com/20319612/128056798-1fbff41c-5485-4aff-aa54-8110a35e46cb.png)

**Comment by JMultimidia** [comment]
I already have some radios on this server and would not like to update now. Can I just change the config/routes/api.php file?
Where do I find it using the docker?

**Comment by SlvrEagle23** [comment]
@JMultimidia Just find a good time to update. I don't recommend modifying the code directly in-container without running the normal update process.

**Comment by Vaalyn** [comment]
Closing as fixed in the rolling-release channel.
