### ISSUE TITLE
Random song

### ISSUE THREAD

**Issue by TorchwoodPL** [AzuraCast/AzuraCast#445]
- **Installation Method:** Traditional
- **Host OS (if using Docker):** Ubuntu 16.04

Question: is there a way to play random song from playlist? I can not find that option in admin panel, or it is random right now and I missed it :P

**Comment by SlvrEagle23** [comment]
@TorchwoodPL There isn't currently such a feature in the system, but there's an existing issue to add it: #230 -- you can follow that ticket's progress for more details. :)

**Comment by SlvrEagle23** [comment]
@TorchwoodPL Just to clarify, in case your question was just "do playlists play randomly by default", the answer is yes, the default behavior with playlists is to shuffle their contents and play a random song, as long as the song hasn't been played too recently.
