### ISSUE TITLE
[Bug]: Maybe its a Bug.. Curl gets Time out on webhooks

### ISSUE THREAD

**Issue by Jaadoo13** [AzuraCast/AzuraCast#4453]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#8d0dc45 (2021-08-05 6:31)

### What happened?

Since i have web and radio Server combined into one Server, i got the Problem that curl cant connect to my php script anymore.
i have one networkcard but two IPs. One for Webservices and one for Azura. All other things works great.
I have also unsing geoip to block specific countries. A Post request with Curl from Azura-Station to a website gets error 28 (Timeout).
But why? Do i have to change something the curl settings or at the iptables?
Maybe someone has an idea.. Thx
kindly...

![image](https://user-images.githubusercontent.com/63636492/128423878-bad01c08-6e58-4a58-9a08-cab632a3f457.png)

**Comment by SlvrEagle23** [comment]
@Jaadoo13 Is it always timing out any time you try it? The timeout is meant to prevent our background tasks from hanging by waiting on HTTP requests. I don't think there's currently any way to modify that timeout on a per-webhook basis.

**Comment by Jaadoo13** [comment]
@SlvrEagle23 yes, it is always timed out. And i think it is not a problem of the time. I think its a Problem with the network. Because, if i change the adress to an other external Server, all works great. so i think curl is blocked internal. but, i dont know, how to figured it out. 
EDIT: I found out the Problem. It seems, that curl inside of the docker does not use external ip for requests (it use something like 172...). And because my Server is blocked for connections from outside of Germany, so all private IPs get blocked too. What is really good to prevent also some spammers. So i open port 443 again for all and it is working again. So, it would be nice, if curl can use the Domains IP instead of an Private ip...
