### ISSUE TITLE
[Bug]: Error while add S3 storage location (Wasabi)

### ISSUE THREAD

**Issue by FiloSpaTeam** [AzuraCast/AzuraCast#4457]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.14.0

### What happened?

Compiled the form and click save. Here the error:
```bash
App\Exception\ValidationException at /var/azuracast/www/src/Controller/Api/AbstractApiCrudController.php L168: Object(App\Entity\StorageLocation): Storage location S3: Invalid URI (Found 1 error while validating the input provided for the GetObject operation: [Key] expected string length to be >= 1, but found string length of 0) could not be validated: Error parsing response for ListObjectsV2: AWS parsing error: Error parsing XML: String could not be parsed as XML
```

**Comment by FiloSpaTeam** [comment]
The problem seems related to bucket name that doesn't like name with points in the middle, but Wasabi actually allow and works (i have nextcloud and mattermost configured in the same way)

So i tried without points, another error:
```bash
App\Exception\ValidationException at /var/azuracast/www/src/Controller/Api/AbstractApiCrudController.php L168: Object(App\Entity\StorageLocation): Storage location S3: //radio-unitoo./radio-unitoo could not be validated: Error executing "ListObjectsV2" on "//radio-unitoo./radio-unitoo?list-type=2"; AWS HTTP error: cURL error 6: Could not resolve host: radio-unitoo. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://radio-unitoo./radio-unitoo?list-type=2
```

**Comment by SlvrEagle23** [comment]
@FiloSpaTeam It would appear that isn't a valid URI...most other S3-compatible providers do provide you with an endpoint name that is a valid URL, i.e. `https://nyc3.digitaloceanspaces.com/` that would appear in that validation...

**Comment by FiloSpaTeam** [comment]
I will try to check the endpoint

**Comment by webma5ter23** [comment]
Same problem, how did you solve it?
