### ISSUE TITLE
[Issue]: Can't make playlist play one song every hour

### ISSUE THREAD

**Issue by Maiiwen** [AzuraCast/AzuraCast#4459]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.13.0 Stable

### What happened?

Hello, I want to use the function that plays a song one time every hour, but after it plays the first song of the playlist, it will never play another song one hour later.

![image](https://user-images.githubusercontent.com/43137876/128614245-61fb5fab-08db-4536-890d-3505bff59c80.png)
![image](https://user-images.githubusercontent.com/43137876/128614269-e27502b0-2f2d-4b8c-a4c0-5782ed218555.png)

### Relevant log output

```shell
2021/08/06 22:59:00 [playlist_top_horaire:3] Prepared "/var/azuracast/stations/xxxxxx/media/TOP HORAIRES/23 heure.mp3" (RID 4).
```

**Comment by SC2Mitch** [comment]
Using advanced configurations is currently unsupported as we do not handle it, Liquidsoap handles it.
