### ISSUE TITLE
[Bug]: Reports -> Song Playback Timeline -> Download in CSV format => Slim Application Error

### ISSUE THREAD

**Issue by Envagyokzsoc** [AzuraCast/AzuraCast#4461]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

AzuraCast • v0.14.0 Stable • Docker • PHP 8.0

### What happened?

After the latest update, the dump to CSV stops with an error message.

### Relevant log output

```shell
Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.
```

**Comment by SC2Mitch** [comment]
Confirming this issue on my machine, checked the docker logs, doesn't appear to be any sort of errors that flash up. 

This is the only log I see that's remotely relevant. 
```
nginx_proxy                | nginx.1     | local.host snip - - [08/Aug/2021:12:20:43 +0000] "GET /api/station/93/history?format=csv HTTP/2.0" 500 602 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36 Edg/92.0.902.67"
```
