### ISSUE TITLE
After Intro playing no Stream working

### ISSUE THREAD

**Issue by ITC-Media** [AzuraCast/AzuraCast#4464]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #c859b2d (2021-08-07 2:18)

### What happened?

My Radio Stream works with 128 kbit well. After last Rolling Release Update I add a 10 sec. MP3 Intro File with 128 kbit constant bitrate. After uploading the Intro File I restart the Server. Unfortunately it played only the Intro File, but not the normal Radio Stream after it.

**Comment by Vaalyn** [comment]
Please post your Liquidsoap Log

**Comment by ITC-Media** [comment]
2021/08/08 20:18:59 >>> LOG START
2021/08/08 20:18:54 [main:3] Liquidsoap 1.4.4
2021/08/08 20:18:54 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.6 sedlex=2.4 menhirLib=20210419 dtools=0.4.4 duppy=0.8.0 cry=0.6.1 mm=0.5.1 ogg=0.5.2 vorbis=0.7.1 opus=0.1.3 mad=0.4.5 flac=0.1.5 flac.ogg=0.1.5 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.3.1 ffmpeg=0.4.3 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.9 camomile=1.0.2 faad=0.4.0 ladspa=0.1.5
2021/08/08 20:18:59 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2021/08/08 20:18:59 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2021/08/08 20:18:59 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2021/08/08 20:18:59 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2021/08/08 20:18:59 [decoder:3] Method "FFMPEG" accepted "/usr/local/share/icecast/web/error.mp3".
2021/08/08 20:18:59 [sandbox:3] Running inside a docker container, disabling sandboxing..
2021/08/08 20:18:59 [video.converter:3] Couldn't find preferred video converter: gavl.
2021/08/08 20:18:59 [audio.converter:3] Using samplerate converter: ffmpeg.
2021/08/08 20:18:59 [harbor:3] Adding mountpoint '/' on port 8005
2021/08/08 20:18:59 [playlist_chill_out:3] Loading playlist...
2021/08/08 20:18:59 [playlist_chill_out:3] No mime type specified, trying autodetection.
2021/08/08 20:18:59 [playlist_chill_out:3] Playlist treated as format application/x-mpegURL
2021/08/08 20:18:59 [playlist_chill_out:3] Successfully loaded a playlist of 21 tracks.
2021/08/08 20:18:59 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Chill out/the_lonely_samurai.mp3".
2021/08/08 20:18:59 [playlist_jingles:3] Loading playlist...
2021/08/08 20:18:59 [playlist_jingles:3] No mime type specified, trying autodetection.
2021/08/08 20:18:59 [playlist_jingles:3] Playlist treated as format application/x-mpegURL
2021/08/08 20:18:59 [ffmpeg:3] Incorrect BOM value
2021/08/08 20:18:59 [ffmpeg:3] Error reading lyrics, skipped
2021/08/08 20:18:59 [ffmpeg:3] [mp3 @ 0x7f1c780035c0] Estimating duration from bitrate, this may be inaccurate
2021/08/08 20:18:59 [playlist_jingles:3] Successfully loaded a playlist of 17 tracks.
2021/08/08 20:18:59 [playlist_station_id:3] Loading playlist...
2021/08/08 20:18:59 [playlist_station_id:3] No mime type specified, trying autodetection.
2021/08/08 20:18:59 [playlist_station_id:3] Playlist treated as format application/x-mpegURL
2021/08/08 20:18:59 [playlist_station_id:3] Successfully loaded a playlist of 6 tracks.
2021/08/08 20:18:59 [playlist_opener:3] Loading playlist...
2021/08/08 20:18:59 [playlist_opener:3] No mime type specified, trying autodetection.
2021/08/08 20:18:59 [playlist_opener:3] Playlist treated as format application/x-mpegURL
2021/08/08 20:18:59 [playlist_opener:3] Successfully loaded a playlist of 8 tracks.
2021/08/08 20:18:59 [playlist_actual_stream:3] Loading playlist...
2021/08/08 20:18:59 [playlist_actual_stream:3] No mime type specified, trying autodetection.
2021/08/08 20:18:59 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Jingles/enjoy_back_to_back_music_right_here_right_now.mp3".
2021/08/08 20:18:59 [ffmpeg:3] Incorrect BOM value
2021/08/08 20:18:59 [ffmpeg:3] Error reading lyrics, skipped
2021/08/08 20:18:59 [ffmpeg:3] [mp3 @ 0x7f1c7801ffc0] Estimating duration from bitrate, this may be inaccurate
2021/08/08 20:18:59 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Jingles/all_hits_all_day.mp3".
2021/08/08 20:18:59 [ffmpeg:3] Incorrect BOM value
2021/08/08 20:18:59 [ffmpeg:3] Error reading lyrics, skipped
2021/08/08 20:18:59 [ffmpeg:3] [mp3 @ 0x7f1c780211c0] Estimating duration from bitrate, this may be inaccurate
2021/08/08 20:18:59 [playlist_actual_stream:3] Playlist treated as format application/x-mpegURL
2021/08/08 20:18:59 [playlist_actual_stream:3] Successfully loaded a playlist of 173 tracks.
2021/08/08 20:18:59 [error_jingle:3] "/usr/local/share/icecast/web/error.mp3" is static, resolving once for all...
2021/08/08 20:18:59 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Jingles/24_7_radio.mp3".
2021/08/08 20:18:59 [ffmpeg:3] Incorrect BOM value
2021/08/08 20:18:59 [ffmpeg:3] Error reading lyrics, skipped
2021/08/08 20:18:59 [ffmpeg:3] [mp3 @ 0x7f1c780211c0] Estimating duration from bitrate, this may be inaccurate
2021/08/08 20:18:59 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Jingles/playing_the_hits_you_are_going_to_love.mp3".
2021/08/08 20:18:59 [local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/08/08 20:18:59 [ffmpeg:3] Incorrect BOM value
2021/08/08 20:18:59 [ffmpeg:3] Error reading lyrics, skipped
2021/08/08 20:18:59 [ffmpeg:3] [mp3 @ 0x7f1c78022f00] Estimating duration from bitrate, this may be inaccurate
2021/08/08 20:18:59 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Station-ID/i_like_to_move_it.mp3".
2021/08/08 20:18:59 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Station-ID/move_it_radio_-_station_id_with_joanna.mp3".
2021/08/08 20:18:59 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Opener/moveit_radio_opener_01.mp3".
2021/08/08 20:19:00 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Opener/moveit_radio_opener_03.mp3".
2021/08/08 20:19:00 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/House/Progressive House/miss_monique_-_yearmix_2019.mp3".
2021/08/08 20:19:00 [ffmpeg:3] Incorrect BOM value
2021/08/08 20:19:00 [ffmpeg:3] Error reading lyrics, skipped
2021/08/08 20:19:00 [ffmpeg:3] [mp3 @ 0x7f1c7801bf40] Estimating duration from bitrate, this may be inaccurate
2021/08/08 20:19:00 [lang:3] AzuraCast Raw Response: annotate:title="One thousand and one faces",artist="Shayan Pasha",duration="296.15",song_id="7d7c8b3742b751a332442a063c5b2a1c",media_id="643",liq_amplify="0.00dB",playlist_id="24":/var/azuracast/stations/anycast/media/House/Progressive House/shayan_pasha_-_one_thousand_and_one_faces.mp3
2021/08/08 20:19:00 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/House/Progressive House/shayan_pasha_-_one_thousand_and_one_faces.mp3".
2021/08/08 20:19:00 [next_song:3] Prepared "/var/azuracast/stations/anycast/media/House/Progressive House/shayan_pasha_-_one_thousand_and_one_faces.mp3" (RID 16).
2021/08/08 20:19:00 [lang:3] AutoDJ is ready!
2021/08/08 20:19:01 [local_1:3] Connection setup was successful.
2021/08/08 20:19:01 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2021/08/08 20:19:01 [safe_fallback:3] Switch to compress_38889.
2021/08/08 20:19:01 [live_fallback:3] Switch to cross_38855.
2021/08/08 20:19:01 [requests_fallback:3] Switch to autodj_fallback.
2021/08/08 20:19:01 [autodj_fallback:3] Switch to dynamic_startup.
2021/08/08 20:19:01 [dynamic_startup:3] Switch to switch_38837.
2021/08/08 20:19:01 [switch_38837:3] Switch to autodj_startup_blank.
2021/08/08 20:19:01 [dynamic_startup:3] Switch to cue_next_song with transition.
2021/08/08 20:19:01 [ffmpeg:3] [mp3float @ 0x7f1c6c002cc0] Could not update timestamps for skipped samples.
2021/08/08 20:19:01 [cross_38855:3] Analysis: -infdB / -269.082695dB (0.04s / 0.04s)
2021/08/08 20:19:01 [crossfade:3] new >= old + margin, old <= medium and new <= high.
2021/08/08 20:19:01 [crossfade:3] Do not fade if it's already very low.
2021/08/08 20:19:01 [crossfade:3] Transition: crossed, no fade.
2021/08/08 20:19:02 [lang:3] AzuraCast Feedback Response: OK
2021/08/08 20:23:10 [lang:3] AzuraCast Raw Response: annotate:title="Live at Radio Intense 2020",artist="Patricia di Monaco",duration="3616.20",song_id="ffe37f0cf32546710ddd0b69cfff75af",media_id="667",liq_amplify="0.00dB",playlist_id="24":/var/azuracast/stations/anycast/media/House/Progressive House/patricia_di_monaco_-_live_at_radio_intense_2020.mp3
2021/08/08 20:23:10 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/House/Progressive House/patricia_di_monaco_-_live_at_radio_intense_2020.mp3".
2021/08/08 20:23:49 [ffmpeg:3] [mp3float @ 0x7f1c6c002cc0] Could not update timestamps for discarded samples.
2021/08/08 20:23:49 [next_song:3] Prepared "/var/azuracast/stations/anycast/media/House/Progressive House/patricia_di_monaco_-_live_at_radio_intense_2020.mp3" (RID 17).
2021/08/08 20:23:49 [ffmpeg:3] [mp3float @ 0x7f1c6c36b500] Could not update timestamps for skipped samples.
2021/08/08 20:23:49 [cross_38855:3] Analysis: -22.996689dB / -14.914659dB (7.51s / 7.53s)
2021/08/08 20:23:49 [crossfade:3] No transition: using default.
2021/08/08 20:23:50 [lang:3] AzuraCast Feedback Response: OK
2021/08/08 20:23:57 [lang:3] AzuraCast Feedback Response: OK
2021/08/08 20:37:43 [playlist_chill_out:3] Loading playlist...
2021/08/08 20:37:43 [playlist_chill_out:3] No mime type specified, trying autodetection.
2021/08/08 20:37:43 [playlist_jingles:3] Loading playlist...
2021/08/08 20:37:43 [playlist_jingles:3] No mime type specified, trying autodetection.
2021/08/08 20:37:43 [playlist_chill_out:3] Playlist treated as format application/x-mpegURL
2021/08/08 20:37:43 [playlist_jingles:3] Playlist treated as format application/x-mpegURL
2021/08/08 20:37:43 [playlist_jingles:3] Successfully loaded a playlist of 17 tracks.
2021/08/08 20:37:43 [playlist_chill_out:3] Successfully loaded a playlist of 21 tracks.
2021/08/08 20:37:43 [playlist_station_id:3] Loading playlist...
2021/08/08 20:37:43 [playlist_station_id:3] No mime type specified, trying autodetection.
2021/08/08 20:37:43 [playlist_opener:3] Loading playlist...
2021/08/08 20:37:43 [playlist_opener:3] No mime type specified, trying autodetection.
2021/08/08 20:37:43 [playlist_opener:3] Playlist treated as format application/x-mpegURL
2021/08/08 20:37:43 [playlist_station_id:3] Playlist treated as format application/x-mpegURL
2021/08/08 20:37:43 [playlist_station_id:3] Successfully loaded a playlist of 6 tracks.
2021/08/08 20:37:43 [playlist_actual_stream:3] Loading playlist...
2021/08/08 20:37:43 [playlist_actual_stream:3] No mime type specified, trying autodetection.
2021/08/08 20:37:43 [playlist_opener:3] Successfully loaded a playlist of 8 tracks.
2021/08/08 20:37:43 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Jingles/your_no_1.mp3".
2021/08/08 20:37:43 [ffmpeg:3] Incorrect BOM value
2021/08/08 20:37:43 [ffmpeg:3] Error reading lyrics, skipped
2021/08/08 20:37:43 [ffmpeg:3] [mp3 @ 0x7f1c74036dc0] Estimating duration from bitrate, this may be inaccurate
2021/08/08 20:37:43 [playlist_actual_stream:3] Playlist treated as format application/x-mpegURL
2021/08/08 20:37:43 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Jingles/all_hits_all_day.mp3".
2021/08/08 20:37:43 [ffmpeg:3] Incorrect BOM value
2021/08/08 20:37:43 [playlist_actual_stream:3] Successfully loaded a playlist of 173 tracks.
2021/08/08 20:37:43 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Chill out/kninodj_-_set_1852_lounge_-28ambient_chillout_mix-29.mp3".
2021/08/08 20:37:43 [ffmpeg:3] Error reading lyrics, skipped
2021/08/08 20:37:43 [ffmpeg:3] [mp3 @ 0x7f1c74050600] Estimating duration from bitrate, this may be inaccurate
2021/08/08 20:37:43 [main:3] Shutdown started!
2021/08/08 20:37:43 [main:3] Waiting for main threads to terminate...
2021/08/08 20:37:43 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Station-ID/hi_this_is_sally_you_are_listening_to_moveit_radio.mp3".
2021/08/08 20:37:43 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Jingles/enjoy_back_to_back_music_right_here_right_now.mp3".
2021/08/08 20:37:43 [ffmpeg:3] Incorrect BOM value
2021/08/08 20:37:43 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Station-ID/i_like_to_move_it.mp3".
2021/08/08 20:37:43 [ffmpeg:3] Error reading lyrics, skipped
2021/08/08 20:37:43 [ffmpeg:3] [mp3 @ 0x7f1c7404e080] Estimating duration from bitrate, this may be inaccurate
2021/08/08 20:37:43 [local_1:3] Closing connection...
2021/08/08 20:37:43 [lang:3] DJ Source disconnected! Current live DJ: 
2021/08/08 20:37:43 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Jingles/your_online_radio.mp3".
2021/08/08 20:37:43 [ffmpeg:3] Incorrect BOM value
2021/08/08 20:37:43 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Opener/moveit_radio_opener_01.mp3".
2021/08/08 20:37:43 [ffmpeg:3] Error reading lyrics, skipped
2021/08/08 20:37:43 [ffmpeg:3] [mp3 @ 0x7f1c7404e080] Estimating duration from bitrate, this may be inaccurate
2021/08/08 20:37:43 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/House/Progressive House/best_progressive_house_mix_2020_vol_4.mp3".
2021/08/08 20:37:43 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Opener/moveit_radio_opener_07.mp3".
2021/08/08 20:37:43 [lang:3] AzuraCast Live Disconnected Response: true
2021/08/08 20:37:43 [harbor:3] Removing mountpoint '/' on port 8005
2021/08/08 20:37:43 [harbor:3] Nothing more on port 8005: closing sockets.
2021/08/08 20:37:43 [clock.wallclock_main:3] Streaming loop stopped.
2021/08/08 20:37:43 [main:3] Threads terminated.
2021/08/08 20:37:43 [threads:3] Shutting down scheduler...
2021/08/08 20:37:43 [threads:3] Scheduler shut down.
2021/08/08 20:37:43 [threads:3] Waiting for queue threads to terminate...
2021/08/08 20:37:43 [threads:3] Queues shut down
2021/08/08 20:37:43 [server:3] Closing socket.
2021/08/08 20:37:43 [main:3] Cleaning downloaded files...
2021/08/08 20:37:43 [main:3] Freeing memory...
2021/08/08 20:37:52 >>> LOG START
2021/08/08 20:37:45 [main:3] Liquidsoap 1.4.4
2021/08/08 20:37:45 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.6 sedlex=2.4 menhirLib=20210419 dtools=0.4.4 duppy=0.8.0 cry=0.6.1 mm=0.5.1 ogg=0.5.2 vorbis=0.7.1 opus=0.1.3 mad=0.4.5 flac=0.1.5 flac.ogg=0.1.5 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.3.1 ffmpeg=0.4.3 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.9 camomile=1.0.2 faad=0.4.0 ladspa=0.1.5
2021/08/08 20:37:52 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2021/08/08 20:37:52 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2021/08/08 20:37:52 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2021/08/08 20:37:52 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2021/08/08 20:37:52 [decoder:3] Method "FFMPEG" accepted "/usr/local/share/icecast/web/error.mp3".
2021/08/08 20:37:52 [sandbox:3] Running inside a docker container, disabling sandboxing..
2021/08/08 20:37:52 [video.converter:3] Couldn't find preferred video converter: gavl.
2021/08/08 20:37:52 [audio.converter:3] Using samplerate converter: ffmpeg.
2021/08/08 20:37:52 [harbor:3] Adding mountpoint '/' on port 8005
2021/08/08 20:37:52 [playlist_chill_out:3] Loading playlist...
2021/08/08 20:37:52 [playlist_chill_out:3] No mime type specified, trying autodetection.
2021/08/08 20:37:52 [playlist_chill_out:3] Playlist treated as format application/x-mpegURL
2021/08/08 20:37:52 [playlist_chill_out:3] Successfully loaded a playlist of 21 tracks.
2021/08/08 20:37:52 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Chill out/tiefsee.mp3".
2021/08/08 20:37:52 [playlist_jingles:3] Loading playlist...
2021/08/08 20:37:52 [ffmpeg:3] Incorrect BOM value
2021/08/08 20:37:52 [ffmpeg:3] Error reading lyrics, skipped
2021/08/08 20:37:52 [ffmpeg:3] [mp3 @ 0x7f75b0003580] Estimating duration from bitrate, this may be inaccurate
2021/08/08 20:37:52 [playlist_jingles:3] No mime type specified, trying autodetection.
2021/08/08 20:37:52 [playlist_jingles:3] Playlist treated as format application/x-mpegURL
2021/08/08 20:37:52 [playlist_jingles:3] Successfully loaded a playlist of 17 tracks.
2021/08/08 20:37:52 [playlist_station_id:3] Loading playlist...
2021/08/08 20:37:52 [playlist_station_id:3] No mime type specified, trying autodetection.
2021/08/08 20:37:52 [playlist_station_id:3] Playlist treated as format application/x-mpegURL
2021/08/08 20:37:52 [playlist_station_id:3] Successfully loaded a playlist of 6 tracks.
2021/08/08 20:37:52 [playlist_opener:3] Loading playlist...
2021/08/08 20:37:52 [playlist_opener:3] No mime type specified, trying autodetection.
2021/08/08 20:37:52 [playlist_opener:3] Playlist treated as format application/x-mpegURL
2021/08/08 20:37:52 [playlist_opener:3] Successfully loaded a playlist of 8 tracks.
2021/08/08 20:37:52 [playlist_actual_stream:3] Loading playlist...
2021/08/08 20:37:52 [playlist_actual_stream:3] No mime type specified, trying autodetection.
2021/08/08 20:37:52 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Jingles/geile-musik.mp3".
2021/08/08 20:37:52 [ffmpeg:3] Incorrect BOM value
2021/08/08 20:37:52 [ffmpeg:3] Error reading lyrics, skipped
2021/08/08 20:37:52 [ffmpeg:3] [mp3 @ 0x7f75b000b340] Estimating duration from bitrate, this may be inaccurate
2021/08/08 20:37:52 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Jingles/enjoy_back_to_back_music_right_here_right_now.mp3".
2021/08/08 20:37:52 [ffmpeg:3] Incorrect BOM value
2021/08/08 20:37:52 [ffmpeg:3] Error reading lyrics, skipped
2021/08/08 20:37:52 [ffmpeg:3] [mp3 @ 0x7f75b001edc0] Estimating duration from bitrate, this may be inaccurate
2021/08/08 20:37:52 [playlist_actual_stream:3] Playlist treated as format application/x-mpegURL
2021/08/08 20:37:52 [playlist_actual_stream:3] Successfully loaded a playlist of 173 tracks.
2021/08/08 20:37:52 [error_jingle:3] "/usr/local/share/icecast/web/error.mp3" is static, resolving once for all...
2021/08/08 20:37:52 [local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2021/08/08 20:37:52 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Jingles/ein-sender-alle-hits.mp3".
2021/08/08 20:37:52 [ffmpeg:3] Incorrect BOM value
2021/08/08 20:37:52 [ffmpeg:3] Error reading lyrics, skipped
2021/08/08 20:37:52 [ffmpeg:3] [mp3 @ 0x7f75b001edc0] Estimating duration from bitrate, this may be inaccurate
2021/08/08 20:37:52 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Jingles/synthetic-beauty.mp3".
2021/08/08 20:37:52 [ffmpeg:3] Incorrect BOM value
2021/08/08 20:37:52 [ffmpeg:3] Error reading lyrics, skipped
2021/08/08 20:37:52 [ffmpeg:3] [mp3 @ 0x7f75b001edc0] Estimating duration from bitrate, this may be inaccurate
2021/08/08 20:37:52 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Opener/moveit_radio_opener_03.mp3".
2021/08/08 20:37:52 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Station-ID/move_it_radio_-_station_id_2021-4-9.mp3".
2021/08/08 20:37:52 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/Station-ID/this_is_move_it_radio_-_keep_moving.mp3".
2021/08/08 20:37:52 [lang:3] AzuraCast Raw Response: annotate:title="Defected House Music DJ Set",artist="Vintage Culture",duration="5304.00",song_id="19363c80d0d30a35779b5c7fcef2552d",media_id="790",liq_amplify="0.00dB",playlist_id="24":/var/azuracast/stations/anycast/media/House/Deep House/vintage_culture_-_defected_house_music_dj_set.mp3
2021/08/08 20:37:52 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/House/Deep House/vintage_culture_-_defected_house_music_dj_set.mp3".
2021/08/08 20:37:52 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/anycast/media/House/Deep House/dinorossi_-_the_mask_life_-28deep_house_mix-29.mp3".
2021/08/08 20:37:52 [ffmpeg:3] [mp3 @ 0x7f75b0016280] Estimating duration from bitrate, this may be inaccurate
2021/08/08 20:37:53 [next_song:3] Prepared "/var/azuracast/stations/anycast/media/House/Deep House/vintage_culture_-_defected_house_music_dj_set.mp3" (RID 14).
2021/08/08 20:37:53 [lang:3] AutoDJ is ready!
2021/08/08 20:37:53 [local_1:3] Connection setup was successful.
2021/08/08 20:37:53 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2021/08/08 20:37:53 [safe_fallback:3] Switch to compress_38889.
2021/08/08 20:37:53 [live_fallback:3] Switch to cross_38855.
2021/08/08 20:37:53 [requests_fallback:3] Switch to autodj_fallback.
2021/08/08 20:37:53 [autodj_fallback:3] Switch to dynamic_startup.
2021/08/08 20:37:53 [dynamic_startup:3] Switch to switch_38837.
2021/08/08 20:37:53 [switch_38837:3] Switch to autodj_startup_blank.
2021/08/08 20:37:53 [dynamic_startup:3] Switch to cue_next_song with transition.
2021/08/08 20:37:53 [ffmpeg:3] [mp3float @ 0x7f75a4002cc0] Could not update timestamps for skipped samples.
2021/08/08 20:37:53 [cross_38855:3] Analysis: -infdB / -52.297670dB (0.04s / 0.04s)
2021/08/08 20:37:53 [crossfade:3] new >= old + margin, old <= medium and new <= high.
2021/08/08 20:37:53 [crossfade:3] Do not fade if it's already very low.
2021/08/08 20:37:53 [crossfade:3] Transition: crossed, no fade.
2021/08/08 20:37:53 [lang:3] AzuraCast Feedback Response: OK

**Comment by ITC-Media** [comment]
I tryed with the latest Rolling Release 6529a92 (2022-06-29 3:25) with Docker and PHP 8.1
nothing changed, the problem persists
