### ISSUE TITLE
Liquidsoap Error

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#447]
- **Installation Method:** Traditional 
- **Host OS (if using Docker):** Ubuntu 16.04

Small problem with Liquidsoap, if I want to switch off or restart it shows me 
![capture d ecran 2018-02-24 a 14 46 45](https://user-images.githubusercontent.com/379099/36631083-fd4b9606-1971-11e8-9c43-7ef3549fac59.png)

**Comment by SlvrEagle23** [comment]
@ckeurk Sorry about that, minor error on my part. Should be fixed now.

**Comment by ckeurk** [comment]
Thank you ;)
