### ISSUE TITLE
Changes to users, permissions, etc. don't persist

### ISSUE THREAD

**Issue by LuisCane** [AzuraCast/AzuraCast#4471]
### Installation Method

One-Click Installation (Docker) (Linode)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#ecb54b9

### What happened?

When managing Users, permissions, and a variety of other settings, other changes I have made disappear. 
For example, I add UserA, then when I add UserB, UserA is no longer listed. Then I go to add UserA again and UserB is gone. If I'm lucky the changes I make will stay and I can add all the users I need. 
Sometimes when I click Edit on a user or user group, it will log me in as that user instead of taking me to the user edit page. These may be separate issues, but they happen together.
![AuditLog](https://user-images.githubusercontent.com/84547909/128762632-be74b32d-bad4-47ff-931d-359198d0205e.png)

**Comment by SlvrEagle23** [comment]
@LuisCane I'm not sure why this happening and I'm unable to reproduce it locally. I suspect something may be going wrong with your local cache on your browser.

Are you only seeing this when creating/removing Users via the System Administration > Users page?
