### ISSUE TITLE
[Bug]: Part of error message played between songs in queue

### ISSUE THREAD

**Issue by leonardder** [AzuraCast/AzuraCast#4478]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #6c39311 (2021-08-10 

### What happened?

When songs are in the queue and Liquidsoap skips from one song to the next, it looks like sometimes the error message plays for a very short time (around half a second) between the tracks.

**Comment by SC2Mitch** [comment]
When this happens, can you provide a full Liquidsoap log so we can see whats happening?

**Comment by leonardder** [comment]
Probably caused by having a playlist with advanced settings enabled.
