### ISSUE TITLE
[Bug]: One-click Vultr

### ISSUE THREAD

**Issue by joshopkins787** [AzuraCast/AzuraCast#4479]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.14.0 Stable 

### What happened?

When trying to use the one click install on Vultr using their $40 tier (4 cpu, 8GB ram, 160GB SSD) everything would download and install but AzuraCast would fail to fully come up. If you browsed to the IP address you would get bad gateway.

Looking into the logs it was MariaDB that was failing to initialize, because it said that there was no password set. I looked in the azuracast.env file and I showed that a password was there.

I tried this about 4 times last night making instances on the bottom 4 tier options and they all did the same thing.

In the end I just made an Ubuntu 20.04 instance and manually did the docker install and everything came up like it should have.

I am more than happy to make another instance to get whatever data you might need.

**Comment by SC2Mitch** [comment]
Can you check if this issue has been resolved? I believe a update was deployed to resolve this issue.
