### ISSUE TITLE
Cannot add remote relay

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#4483]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#56a31a9 (2021-08-12 15:44)

### What happened?

As soon as I have entered everything (and also activated 'Broadcast AutoDJ to Remote Station' for AutoDJ) I still can't click on Save Changes:

![image](https://user-images.githubusercontent.com/42640247/129346194-263bb693-91a7-477e-a4db-2abbd76b3c81.png)

**Comment by SlvrEagle23** [comment]
@Abqehebter This should be fixed in the latest rolling release version. Thanks for letting us know!
