### ISSUE TITLE
Sorting in Song Requests doesn't changes sort order

### ISSUE THREAD

**Issue by yarik2720** [AzuraCast/AzuraCast#4484]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.14.0 Stable

### What happened?

1. Open public page
2. Open Request Song
3. Click on any column to change sort order
4. Sort order stays the same

**Comment by Abqehebter** [comment]
I can confirm this.
I have tried it with "Name". The order changes the first time and stays that way.

**Comment by SC2Mitch** [comment]
Verified bug with Public Pages / Song Request feature.
