### ISSUE TITLE
non-fqdn URLs for mountpoints being passed to shoutcast

### ISSUE THREAD

**Issue by ngrhd** [AzuraCast/AzuraCast#4485]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 0.14.0

### What happened?

**Environment**
- Azuracast is behind Cloudflare subdomain
- Base URL is configured as https://radio.domain.tld
- `Use Web Proxy for Radio` is checked
- Uploaded the latest SHOUTcast linux binary v2.6.0.753 
- Mountpoint URL has been correctly formated as `https://radio.domain.tld/radio/8000/radio.mp3`

**Expected behavior**
Shoutcast must get the proxied FQDN URL for the mount point: `https://radio.domain.tld/radio/8000/radio.mp3`

**Unexpected behavior**
Instead, Shoutcast gets `http://IP:8000/radio.mp3`

**Comment by Countryman98** [comment]
Using latest Azuracast docker stable release and also experiencing the same issue as above.
