### ISSUE TITLE
Discord WebHook time is wrong

### ISSUE THREAD

**Issue by RainbowDash53** [AzuraCast/AzuraCast#449]
- **Installation Method:** Traditional
- **Host OS (if using Docker):** Ubuntu 16.04

Hi, currently it's 23:05 in my country but the discord time indicated 00:05 how to fix it ?

**Comment by FrBillyD** [comment]
Hello, same for me. I was just going to post a message.

**Comment by SlvrEagle23** [comment]
@RainbowDash53 @FrBillyD This should be fixed in the latest update.

While I was working in that part of the code, I also added some extra URL validation and the ability to enable/disable webhooks without actually deleting them; should help with managing things. :)
