### ISSUE TITLE
Jingles without interrupting music.

### ISSUE THREAD

**Issue by d-trax** [AzuraCast/AzuraCast#4492]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.14.0

### What happened?

Hey there, 
New AzuraCast user here. I am setting up my radio station using this genius software, but I am trying to figure out is it possible to play jingles on top of music. I read in Liquidsoap's info page, that this is possible, but I can't manage to make it work. Tried adding some scripts in the custom Liquidsoap configuration with no success. Tried every single playlist option with no success. Any help will be highly appreciated.
I am attaching a screenshot from Liquidsoap's info page.
Thanks in advance!
<img width="896" alt="Screen Shot 2021-08-17 at 8 46 26 PM" src="https://user-images.githubusercontent.com/31935215/129775866-e76948e5-ffd5-46cd-9e96-82521d057b1d.png">

**Comment by Abqehebter** [comment]
It is possible to schedule the jingles per hour. AzuraCast will then add the jingle behind the existing songs in the queue at the respective time:
![image](https://user-images.githubusercontent.com/42640247/129805432-e106d176-df6d-4837-a860-777d3237a632.png)
...or is something completely different meant here?

**Comment by d-trax** [comment]
Hi, thanks for your comment. Tried enabling the Manual AutoDJ, and then got the same errors. I believe it's something with the config with Liquidsoap. I do put the script from Liquidsoap's info page, but i get the same errors.
Error with the script - **radio = switch([({ 0m-1m }, jingles), ({ true }, playlist)])**

```
At line 50, char 38-58:
Error 5: this value has type
  _ *
  ((?id : _, ?check_next : _, ?conservative : _, ?default_duration : _,
    ?length : _, ?mime_type : _, ?mode : _, ?on_track : _, ?prefix : _,
    ?reload : _, ?reload_mode : _, ?timeout : _, _) -> _)
but it should be a subtype of the type of the value at line 50, char 16-36
  _ * source(_)

```

I am not sure what I am doing at all... Enabling the Manual AutoDJ and making my jingles playlist Advanced, makes no change with the results. :/

**Comment by denisbriski** [comment]
Hello,

from my experience, you have to restart broadcasting after making changes to Advanced playlist settings for any Liquidsoap changes to work.

**Comment by d-trax** [comment]
I do it all the time after I make changes to some settings, but it shows errors with no matter what script I try in the config. I am really new with AzuraCast and Liquidsoap. It appears to me that I don't understand the configuration of Liquidsoap at all. I believe that the similar errors I get are related to some parts missing in the configuration I am trying to mess with, but I just don't know anything about Liquidsoap's config yet...

**Comment by McP4nth3r** [comment]
@d-trax I have used this one and it works fine
`radio  = 
smooth_add(
        normal= radio,
        p=0.20,
        special=switch([ ( { 04m0s }, playlist_jingles) ])
)`
this code plays the jingle over the main Track and reduce the volume of main Track

**Comment by d-trax** [comment]
@McP4nth3r will try this. Can you please share what settings you used on the 'Jingles' playlist, just to be sure? Thanks!

**Comment by McP4nth3r** [comment]
Only Advanced Configuration is ticked 👌

**Comment by d-trax** [comment]
Thanks man! I owe you a pack of beers 🍻

**Comment by d-trax** [comment]
Hey guys, me again (LOL). 
Is there any chance I can remove the 'fade in' funcition in the script when playing the jingles, because of the fade in function most of the jingle can't be heard at all. 
Also I've tried the 'add' function, which appears to play the jingles straight, but I can't figure out how to reduce the gain on the main source using the 'add' function likewise - p=0.20. 

What I want is to play a jingle without smooth fading in, and reducing the volume of the main source when playing the jingle, then back to normal. Thanks in advance!

**Comment by McP4nth3r** [comment]
You can adjust the fadeIn Time in smooth_add look at the official documentation from liquidsoap 👌🏻 im not at home at this moment but is is possible I have made this too

**Comment by d-trax** [comment]
I've been in the documentation all morning, but I didn't catch up what realy needs to be done. I think the steps in the documentation are incomplete in someway and this makes things difficult to understand, at least for me for now. Tried to define the fade.in/out, but that didn't work. Who would know that making something that simple would be absolutely pain 😂 anyway i will be very glad if you share your knowledge once more for the community. All the best and looking forwars for your reply 🙏

**Comment by d-trax** [comment]
Ok, I officialy read all the documentation including the book, but I didn't manage to reduce the fade in/out time in **smooth_add**.  Tried to adjust it in fades.liq directly, but that didn't help either. Tried to set parameters in the liquidsoap config without success :( 
The **add** function seems to work, but I can't reduce the volume of the radio source when jingle is playing, which makes things bad. Would really appreciate some help. Thanks again!

**Comment by McP4nth3r** [comment]
You can use this selfmade custom function for this.

```ts
# Special function to play jingles over main source with fadeIn
# @param ~delay   Delay before starting the special source.
# @param ~p       Portion of amplitude of the normal source in the mix.
# @param ~normal  The normal source, which could be called the carrier too.
# @param ~jingle The jingle source.

def smooth_add_jingle(~delay=0.5,~p=0.2,~normal,~jingle)
  d = delay
  fade.final = fade.final(duration=d*2.)
  fade.initial = fade.initial(duration=d*2.)
  q = 1. - p
  c = amplify
  fallback(track_sensitive=false,
           [jingle,normal],
           transitions=[
             fun(normal,jingle)->
               add(normalize=false,
                   [c(p,normal),
                    c(q,fade.final(type="sin",normal)),
                    sequence([blank(duration=d),c(q,jingle)])]),
             fun(jingle,normal)->
               add(normalize=false,
                   [c(p,normal),
                    c(q,fade.initial(type="sin",normal))])
           ])
end
```

You can adjust the delay for your problem 👌

**Comment by d-trax** [comment]
So this function should be in the liquidsoap config, or should write it in the fades.liq?

**Comment by McP4nth3r** [comment]
In your .liq file you can add custom functions

**Comment by d-trax** [comment]
`# Mixes two streams, with faded transitions between the state when only the
# normal stream is available and when the special stream gets added on top of
# it.
# @category Source / Track Processing
# @param ~delay   Delay before starting the special source.
# @param ~p       Portion of amplitude of the normal source in the mix.
# @param ~normal  The normal source, which could be called the carrier too.
# @param ~special The special source.
def smooth_add(~delay=0.5,~p=float_getter(0.2),~normal,~special)
  p = to_float_getter(p)
  last_p = ref p()

  def c(fn,s) =
    def v() =
      fn = !fn
      fn()
    end
    amplify(override="",v,s)
  end

  special_volume = ref fun () -> 0.
  special = c(special_volume,special)

  normal_volume = ref fun () -> 1.
  normal = c(normal_volume,normal)

  def to_special(b,special) =
    last_p := p()
    q = 1. - !last_p
    normal_volume := mkfade(start=1.,stop=!last_p,normal)
    special_volume := mkfade(stop=q,special)
    special
  end

  def to_blank(special,b)
    normal_volume := mkfade(start=!last_p,normal)
    special_volume := mkfade(start=1.-!last_p,special)
    sequence([special,b])
  end

  special = fallback(track_sensitive=false,
               transitions=[to_special,to_blank],
               [special,blank()])

  add(normalize=false,[normal,special])
end

`

Here is what I have in fades.liq about "smooth_add". Tried to reduce the delay to 0, but didn't reduce the fading at all.
I will try to add the script you provided, but I don't see where to reduce the fade.in/out durations except for the delay parameter which is already 0.5 and as I understood this is just the delay of the source thats about to be played in the fade, not the fade itself. Its a freakin' mystery this xD

**Comment by d-trax** [comment]
<img width="803" alt="Screen Shot 2021-09-22 at 8 34 33 PM" src="https://user-images.githubusercontent.com/31935215/134393336-b32274ad-86ca-4c99-8e4e-69fee668aacc.png">
That's what I got with the script

**Comment by d-trax** [comment]
Ok, it kinda worked, but it in the middle of the jingle drops down the volume of the main source to 0. After that it amplifies the signal very high and after 1 second it reduces it to normal haha. Will work with that script until i get it working as I like. Thanks very much once again brother! You're the MVP!

**Comment by McP4nth3r** [comment]
ok thats nice sry for the late answer i was not home ^^ what do you mean with mvp? i only know MVP as "Minimum Viable Product" 😄

**Comment by d-trax** [comment]
@McP4nth3r MVP stands for Most Valuable Person :D or at least thats how i know it

**Comment by McP4nth3r** [comment]
ok xD I am new to liquidsoap and azuraCast and this language is very strange but I try to make the best of it :)

**Comment by SC2Mitch** [comment]
I believe this issue has since been resolved, if not, then re-open a ticket.
