### ISSUE TITLE
Azuracast update notifications

### ISSUE THREAD

**Issue by zloysystem** [AzuraCast/AzuraCast#4494]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Azuracast update notifications

### What happened?

Good day gentlemen.
As I recently wrote, I still do not receive update notifications in the panel, the parameter is enabled
I don’t know if there are updates or not, it is necessary to update forcibly, relying on the releases of your demo-version of the panel)
![SmartSelect_20210818-112808_Chrome](https://user-images.githubusercontent.com/26243386/129865995-5b8539fa-f1f2-4970-9c6d-1a0243c816ec.jpg)

**Comment by Abqehebter** [comment]
Hm. I cannot reproduce this. I always get more than I actually want... 😅

**Comment by SC2Mitch** [comment]
The rolling release version includes every single commit we include to our repository, at the bottom of your AzuraCast installation there should be this: Powered by AzuraCast • Rolling Release #01658ff (2021-08-15 18:20) • Docker • PHP 8.0, the important thing is `#01658ff` as this is the commit hash from our commits. https://github.com/AzuraCast/AzuraCast/commits/main If you have any questions, ask away.

**Comment by zloysystem** [comment]
@SC2Mitch no notifications of new updates on the main page of the dashboard when logging in o_O

**Comment by SC2Mitch** [comment]
Which version are you currently running?

**Comment by zloysystem** [comment]
@SC2Mitch Rolling Release # 01658ff is now installed (2021-08-15 18:20) and I only learned about this update from your demo version of the panel and I did not have any pop-up notifications, this is the fifth time I say (

**Comment by Abqehebter** [comment]
@zloysystem Just for understanding, because you write here about pop-up message: The update message actually appears after login on your dashboard under your profile picture + username + email (If there are updates) - Exactly this box you mean, right? So it doesn't show up for you despite updates?

**Comment by zloysystem** [comment]
@Abqehebter yes absolutely right, finally someone understood me

**Comment by SlvrEagle23** [comment]
@zloysystem I can't reproduce this locally either. It's possible the account you're using isn't considered a "super administrator" (i.e. has "Administer All" at the global level) and thus won't see that notification on the homepage. Otherwise, I'm not sure what would cause that notification not to appear for your specific account.

**Comment by zloysystem** [comment]
@SlvrEagle23 I am the only user of the panel, and it started not so long ago, I just noticed that there were no updates for about a week, there were no notifications

**Comment by SlvrEagle23** [comment]
@zloysystem Try manually running the 5-minute sync, which will also check for updates...see if there are any errors that appear there.

**Comment by zloysystem** [comment]
@SlvrEagle23
 > [2021-08-19T22:26:53.630297+00:00] AzuraCast.DEBUG: Expiration defined for "{resource}" lock for "{ttl}" seconds. {"resource":{"Symfony\\Component\\Lock\\Key":"lock_sync_medium"},"ttl":600.0} []
[2021-08-19T22:26:53.630416+00:00] AzuraCast.DEBUG: Starting sub-task: CheckUpdatesTask [] []
[2021-08-19T22:26:53.632235+00:00] AzuraCast.DEBUG: Update request body {"body":{"id":"83c30a07-dc64-4c94-8e43-a6e553bed9c1","is_docker":true,"environment":"production","release_channel":"rolling","version":"01658ff457cc0a337f91e2ed1dd30342dcd973d8"}} []
[2021-08-19T22:26:54.124019+00:00] AzuraCast.DEBUG: HTTP client POST call to https://central.azuracast.com/api/update produced response 200 [] []
[2021-08-19T22:26:54.124347+00:00] AzuraCast.INFO: Successfully checked for updates. {"results":{"needs_rolling_update":true,"rolling_updates_available":2,"rolling_updates_list":["Allow string/int on all Station APIs.","Fix playlist time on Streamer schedule form."],"needs_release_update":false,"current_release":"0.14.0","latest_release":"0.14.0"}} []
[2021-08-19T22:26:54.130499+00:00] AzuraCast.DEBUG: Timer "CheckUpdatesTask" completed in 0.500 second(s). [] []
[2021-08-19T22:26:54.140084+00:00] AzuraCast.DEBUG: Sync task "5-Minute Sync" completed successfully. [] []

**Comment by zloysystem** [comment]
@SlvrEagle23 now there are 2 updates

**Comment by zloysystem** [comment]
@SlvrEagle23 Maybe because it works in relay mode? Maybe this is due to synchronization?
