### ISSUE TITLE
Adding Schedule to DJ/Streamer

### ISSUE THREAD

**Issue by AaronUnmuted** [AzuraCast/AzuraCast#4497]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.14.0 Stable

### What happened?

When trying to add a schedule to a DJ or Streamer account, an error is shown when applying the changes. See below:
http://prntscr.com/1qbrq32

**Comment by Abqehebter** [comment]
Seems to be fixed in the latest rolling release version. For me it works as it should.

**Comment by Vaalyn** [comment]
This was indeed fixed in the Rolling-Release channel via commit https://github.com/AzuraCast/AzuraCast/commit/ecb54b973bc6383b43d1c770b8cede4be5d2db26
