### ISSUE TITLE
VK webhook?

### ISSUE THREAD

**Issue by tehcojam** [AzuraCast/AzuraCast#450]
For example, Azura can updates status of a community with currently playing song.
![](https://pp.userapi.com/c831408/v831408067/879fc/e6NfDfAW5sk.jpg)

Links:  
* https://en.wikipedia.org/wiki/VKontakte (if you don't know what VK is)
* https://vk.com/dev/manuals
* https://vk.com/dev/status.set

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38785/support-vkontakte-as-a-web-hook-destination
