### ISSUE TITLE
Problems with Synchronized Task

### ISSUE THREAD

**Issue by vitorfernandes1976** [AzuraCast/AzuraCast#4500]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.14.0 Stable

### What happened?

After installing AzuraCast in a new VPS, the entire installation without any error; noticed that the "Synchronized Task" do not work.

See attached screenshot.

![error-01](https://user-images.githubusercontent.com/45834146/130085447-ca8ccddf-63c2-4f99-ac3f-b365411bc98a.png)

### Relevant log output

```shell
Loading...[2021-08-19T14:21:58.560189+00:00] AzuraCast.NOTICE: Skipping sync task nowplaying; setup not complete. [] []

Loading...[2021-08-19T14:22:24.623532+00:00] AzuraCast.NOTICE: Skipping sync task short; setup not complete. [] []

Loading...[2021-08-19T14:22:41.670413+00:00] AzuraCast.NOTICE: Skipping sync task medium; setup not complete. [] []

Loading...[2021-08-19T14:23:05.230138+00:00] AzuraCast.NOTICE: Skipping sync task long; setup not complete. [] []
```

**Comment by Abqehebter** [comment]
Try `http://azuracast.yourdomain.com/setup` and complete your setup?

**Comment by vitorfernandes1976** [comment]
Ok solved !!!!

Very simple ... Very Thanks !
