### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#4504]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #01658ff (2021-08-15 18:20) • Docker • PHP 8.0

### What happened?

I did a google analytics configuration on the webhook but the information is not enough. In the link I put my dashboard's link and in id, the id generated in the analytics.
Is this tool functional? is there any tutorial explaining how to configure?

### Relevant log output

```shell
I did a google analytics configuration on the webhook but the information is not enough. In the link I put my dashboard's link and in id, the id generated in the analytics.
Is this tool functional? is there any tutorial explaining how to configure?
```

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli It certainly should be functioning...one caveat, if I recall correctly, is that your Google Analytics property should be the older format that starts with "UA-" in its tracking ID. You will want to make sure that's the case for your specific property; you can always create a new one using that format.

**Comment by Marcioghiraldelli** [comment]
@SlvrEagle23  
you're right, I looked here for a tutorial on youtube on how to create a universal pattern id and applied it to azuracast and it worked.
If you want I can create a tutorial for those who don't know somewhere here on azuracast to help those who also have difficulties in this part.

**Comment by balmasedano** [comment]
When I connected my AzuraCast installation to Google Analytics, I didn't understand how aggregates the data. The unique listeners are different from the reports from AzuraCast. Any help about how calculate unique listeners and hours from Analytics data? Thanks!

**Comment by gunsar** [comment]
@SlvrEagle23 now Google analytics has the latest version, namely version 4, I tried to enter the code and it didn't work. hopefully there will be a new azuracast update with 2 options for: old Google analytics, latest Google analytics (v4)
thank you

**Comment by asa767** [comment]
Up
