### ISSUE TITLE
Error exporting csv

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#4506]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.14

### What happened?

Hello after upgrading to the stable version we have started to find this error when trying to export the reports in format.csv
![imagen](https://user-images.githubusercontent.com/16152034/130271486-cebb79a7-fa19-4cd7-b94f-833f54d946e7.png)

**Comment by Abqehebter** [comment]
I believe this bug has already been fixed in the rolling release. With me everything runs as it should: Rolling Release #02c653a (2021-08-20 3:22)

**Comment by SC2Mitch** [comment]
This was fixed in the latest rolling branch.
