### ISSUE TITLE
Weird bug with getting song files from the now playing API

### ISSUE THREAD

**Issue by chezzzer** [AzuraCast/AzuraCast#4507]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #3569047

### What happened?

Azura keeps returning the wrong song for the currently playing ID.

For instance, let's say song X is playing and returns a `song.id` of `b84ce1e2065b6eb9e16429b514169c86` in the nowplaying API endpoint. When querying the /file/`:id` API endpoint with the ID, it returns a completely different song with the `unique_id` of `0234fcf4c3a5f1b232fa1cb1` (which is different from the song ID above). Normally, `unique_id` and `song.id` would be the same, as this happens in the song that it should get and on every other normal song.

I have done some more investigation into this and it looks like the now playing API sometimes (very rare) returns a wrong song ID. 

I'm not sure how it works but I think a possible solution could be just to put the `media_id` inside the now playing endpoint and just forget about internal song strings.

### Relevant log output

```shell
N/A
```

**Comment by Chezzer-ub** [comment]
Some screenshots to help understand better...

Broken API call:
![image](https://user-images.githubusercontent.com/46093784/130324823-722104f9-6c0a-43f4-98a5-6c58e67230d0.png)

Correct API call:
![image](https://user-images.githubusercontent.com/46093784/130324836-82db2580-e8a7-429e-a641-3ec8303a7c4b.png)

Broken track ID sourced from the now playing API:
```json
{"id":"134fbdc7a66690314746c6358738b4c1","text":"Subsonic - Emotions","artist":"Subsonic","title":"Emotions","album":"Quadrant - EP, Vol. 4","genre":"Electro, Dance","lyrics":"","art":"https://radio.bunker.dance/api/station/1/art/45cb8d1d4c89c5b5b1801303-1629554703.jpg","custom_fields":{"file":null,"id":"GBPWR2000059"}}}
```
