### ISSUE TITLE
Error scheduling a dj account broadcast

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#4508]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.14.0

### What happened?

When creating a dj account everything is normal, however, when configuring a schedule, an error appears and it is not possible to schedule.

![Capturar](https://user-images.githubusercontent.com/58113324/130333294-668e4318-78fd-40bc-b5a4-695b611afff8.JPG)

**Comment by SC2Mitch** [comment]
This has been fixed in latest rolling branch.

**Comment by roger-net** [comment]
@SC2Mitch Thanks.
