### ISSUE TITLE
Suggestion : possibility to add a name to webhook

### ISSUE THREAD

**Issue by FrBillyD** [AzuraCast/AzuraCast#451]
- **Installation Method:** Traditional
- **OS:** Ubuntu 16.04

Hello, can you add the possibilty to name a webhook ? It's usefull when we have many webhooks on same system (example for Discord, we have 3 web-hooks for 3 differents Discord servers...).

Thank you for your wonderful work !

**Comment by SlvrEagle23** [comment]
@FrBillyD Added! The latest update includes the ability to set a nickname for any web hook, which will show up in the administrative panel.
