### ISSUE TITLE
RoutingMiddleware.php 404/Method Not Allowed

### ISSUE THREAD

**Issue by JanieUwU** [AzuraCast/AzuraCast#4516]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.14.1

### What happened?

My system logs are littered with these warnings every 5 minutes, is there insight to if this important or something wrong?

### Relevant log output

```shell
[2021-08-25T02:39:14.962804+00:00] AzuraCast.WARNING: Method not allowed. Must be one of: OPTIONS {"file":"/var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php","line":94,"code":405} []

[2021-08-25T02:39:18.909249+00:00] AzuraCast.WARNING: Not found. {"file":"/var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php","line":91,"code":404} []
```

**Comment by SlvrEagle23** [comment]
@JanieUwU This would suggest something is trying to routinely visit a URL that isn't registered. I thought we lowered the severity of the "Not Found" errors so they wouldn't flood the logs, but it appears that didn't happen, so I'll investigate that.

**Comment by JanieUwU** [comment]
> @JanieUwU This would suggest something is trying to routinely visit a URL that isn't registered. I thought we lowered the severity of the "Not Found" errors so they wouldn't flood the logs, but it appears that didn't happen, so I'll investigate that.

Like a URL that would return a 404 or something that shouldn't be public? A friend did help me develop a tool that goes to the api page with all the now playing info to get the data on anything that's playing for a discord rich presence. Maybe that has something to do with it?
