### ISSUE TITLE
shoutcast support 2.6

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#4526]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #01658ff (2021-08-15 18:20) • Docker • PHP 8.0

### What happened?

I am unable to install a newer version of shoutcast 2.6 premium or normal on azuracast. It always stops working. Does anyone have the shoutcast 2.6 file working? Or procedure how to resolve this? because I want to join the shoutcast radio list but now they only allow shoutcast 2.6

### Relevant log output

```shell
I am unable to install a newer version of shoutcast 2.6 premium or normal on azuracast. It always stops working. Does anyone have the shoutcast 2.6 file working? Or procedure how to resolve this? because I want to join the shoutcast radio list but now they only allow shoutcast 2.6
```

**Comment by Marcioghiraldelli** [comment]
[01;33m2021-08-27 20:46:46	WARN	[Licence sid=3] Format is not MP3, where only MP3 is allowed 
it seems that it is a license error but I put as it says on the panel the licenses, I contacted shoutcast and everything is fine. only here that does not work.

**Comment by Marcioghiraldelli** [comment]
2021-08-27 20:47:57	INFO	[SRC 127.0.0.1:56192 sid=1] stream detected AACv4, LC (2), 22050hz, estimated 64 kbps
2021-08-27 20:47:58	INFO	[SRC 127.0.0.1:56190 sid=3] stream detected AACv4, LC (2), 22050hz, estimated 32 kbps

**Comment by Vaalyn** [comment]
Could you post the full SHOUTcast logs and the generated SHOUTcast configuration for the station?

**Comment by Marcioghiraldelli** [comment]
What is to be understood is that the data that the network enters does not go into the radio's shoutcast configuration file and then does not recognize it. I've also contacted shoutcast and they said the license is normal.

how big log is posted in my dropbox.
follow the link below:
log: https://www.dropbox.com/s/gc1wgkeiibe2xhv/log-shoutcast.txt?dl=0

**Comment by Vaalyn** [comment]
I found out why it's not including the custom config.
There is a small error in the help text of the textbox. The example config is missing a `,`.

It should be
```
{ "licenceid": "YOUR_LICENSE_ID", "userid": "YOUR_USER_ID" }
```

**Comment by Marcioghiraldelli** [comment]
Hello, it seems that you have solved the problem, it really is a , ..

**Comment by Marcioghiraldelli** [comment]
the strangest thing is that it's only working on a radio, and this subscription is shoutcast premium.
if I put the same license on other radios, it won't work.
