### ISSUE TITLE
curl: (23) Failed writing body (0 != 862)

### ISSUE THREAD

**Issue by adoboligh1** [AzuraCast/AzuraCast#4528]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

curl: (23) Failed writing body (0 != 862)

### What happened?

curl: (23) Failed writing body (0 != 862)

**Comment by SC2Mitch** [comment]
Going to need a whole lot more information here, what was you doing before this happened?

**Comment by adoboligh1** [comment]
was installing azuracast when I got to the install docker-compose? and I
selected yes and I got this error before it sent me to select my preferred
azuracast build

**Comment by SlvrEagle23** [comment]
@adoboligh1 That could've just been a temporary error pulling Docker Compose's binary from GitHub; re-running the installation may fix it.

**Comment by adoboligh1** [comment]
installation worked, just reporting it because i thought it might be a
misconfiguration or a dead link

**Comment by SlvrEagle23** [comment]
@adoboligh1 Ah, probably nothing we need to deal with, since issues with pulling files via cURL are rather frequent and just retrying often fixes them.

**Comment by adoboligh1** [comment]
makes sense.
