### ISSUE TITLE
Estou com problema com o azuracast na reprodução estar duplicantdo as vinhetas

### ISSUE THREAD

**Issue by roberio14** [AzuraCast/AzuraCast#4532]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

Desenvolvido por AzuraCast • v0.14.1 Stable • Docker • PHP 8.0

### What happened?

[2021-08-30T01:24:17.873587+00:00] AzuraCast.WARNING: Duplicate prevention yielded no playable song; resetting song queue. [] {"station":{"id":1,"name":"Rádio Studioarmix"}}
esse é o codigo que estar dando nas vinhetas

**Comment by SpeedyCharly** [comment]
I remember a user being blasted to kingdom-come when he fired a question in French on here; he was basically told to 'speak white'.  When I raised the issue with the offending staffer, I was labelled a 'shit disturber'...  Is Portuguese somehow kosher and have you reversed your position on French?

**Comment by SlvrEagle23** [comment]
> I remember a user being blasted to kingdom-come when he fired a question in French on here; he was basically told to 'speak white'. When I raised the issue with the offending staffer, I was labelled a 'shit disturber'... Is Portuguese somehow kosher and have you reversed your position on French?

@SpeedyCharly That is categorically not what happened, specifically your assertion that anyone on our team suggested that submitters should "speak white", and I would strongly caution you to avoid talking about our staff as though we behave in this manner when we clearly do not, especially when dragging an entirely unrelated issue into that accusation.

Support here is provided by our team in English as a matter of commonality, as it is the only language that the entirety of our team is comfortable providing advanced technical support in. While any user is absolutely encouraged to seek support in their native language from the broader community on a whole, we've established that English is the required language for our official support and communications channels.

Once again, and I really cannot state this enough as it seems to be the most misunderstood fact about AzuraCast that any of our users have: we are a _very small team_ tasked with a larger task than most users seem to realize or appreciate, not only building, deploying and maintaining a large web application with hundreds of dependencies, but also supporting it and moderating numerous communication channels. It is well within our prerogative to say that, for ease of moderation and uniformity of communications, we prefer to use a single language.

In this case, we haven't even made any response to the original issue. Any responses I could provide would be in English themselves, with a specific note that we don't provide support in the original language used by the requester (although the logs provided by our own application, which are in English, are sufficient in this case to assume the cause of the question).

I will not be typing out another one of these essay-style responses to you again. The next time you speak out in such a way that I feel compelled to categorically refute everything you say, I will be banning you from this application and all of its communication channels instead. Life is far too short for me, as an open-source maintainer, to be spending my nights dealing with this.
