### ISSUE TITLE
White Page after restart

### ISSUE THREAD

**Issue by RainbowDash53** [AzuraCast/AzuraCast#454]
- **Installation Method:** Traditional
- **Host OS (if using Docker):** Ubuntu 16.04

Hi, my foster had some problems this afternoon and they shutdown my server and restart it, but now, got only a white page.. I can't do anything now. 

I try to make an update and got this error:
[WARNING]: Unable to set correct type for configuration entry:
DEFAULT_LOCAL_TMP

ERROR! Unexpected Exception, this is probably a bug: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/var/azuracast/www']
to see the full traceback, use -vvv

Link of my server:
http://185.163.125.250

**Comment by SlvrEagle23** [comment]
@RainbowDash53 This typically means your server is out of space. With Docker running, these commands may help you clear up space:

```
docker-compose rm
docker rmi $(docker images | grep "none" | awk '/ / { print $3 }')
```

**Comment by RainbowDash53** [comment]
Out of space ? I had 1TO remaining :')

I just reset and install it again, I can't install docker compose on my system won't working.

**Comment by SlvrEagle23** [comment]
@RainbowDash53 After you reinstalled, do things work okay? I'm not sure what kind of host environment you'd be using that wouldn't work with Docker Compose, but it should support almost every platform.
