### ISSUE TITLE
Remote url when scheduled doesn't work

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#4540]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.14.1

### What happened?

In the playlist, under the "source" tab I select "remote url playlist" and add the url, whether it be "direct" or by M3U, PLS, it just doesn't work. Then I make the normal schedule. The control panel shows that the playlist is live but there is simply no audio. There is no problem with the url I want to relay as I have tested several and none work. Am I doing something wrong or do I really have a problem?

**Comment by adoboligh1** [comment]
same issue here, some urls does not even relay!
