### ISSUE TITLE
Swagger API submit a song request test requires an integer for "request_id"

### ISSUE THREAD

**Issue by OnlyTunes** [AzuraCast/AzuraCast#4546]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.14.1 Stable

### What happened?

On the Swagger API docs the request song test is kinda borked. When trying to test it the request_id that azura gives you is a random string where the one that swagger wants it only integer. ( API works fine when using postman ) see images below for references. 

![image](https://user-images.githubusercontent.com/71556423/132096943-76c9e7f0-48fb-4a56-b051-db15a9c767ff.png)

![image](https://user-images.githubusercontent.com/71556423/132096979-748dfc7c-1165-4f12-b44b-a5927913531a.png)

![image](https://user-images.githubusercontent.com/71556423/132095709-fdda3017-51cf-4b36-9cac-0c02d43e0309.png)

When using PostMan

![image](https://user-images.githubusercontent.com/71556423/132097046-29570257-f349-450b-bb96-9e9ccb012f00.png)

**Comment by SlvrEagle23** [comment]
Request ID and station ID accepting strings has been fixed in the latest API documentation on the Rolling Release install.
