### ISSUE TITLE
Reordering playlist items

### ISSUE THREAD

**Issue by bebjakub** [AzuraCast/AzuraCast#455]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Docker image on VC1S Scaleway's server

**Describe the issue in full detail, including screenshots if possible:**

I have large playlists and sometimes I need reorder tracks, so I have to create a new playlist for that.
Is possible add a reorder item feature to Playlist administration, pls?

Thank you!

**Comment by SlvrEagle23** [comment]
@bebjakub I'm consolidating a number of playlist-related enhancements into a more technical-oriented project management issue where I can track the progress on the changes, so feel free to follow that: #480
