### ISSUE TITLE
Can't install AzuraCast, 404

### ISSUE THREAD

**Issue by eduardonwa** [AzuraCast/AzuraCast#4550]
### Installation Method

Docker Installation

### What happened?

Steps to reproduce the issue

1. mkdir -p /var/azuracast
2. cd /var/azuracast
3. curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/main/docker.sh > docker.sh
4. chmod a+x docker.sh
5. ./docker.sh install

Docker is already installed! Continuing...
/usr/local/bin/docker-compose: line 1: Not: command not found
Docker Compose does not appear to be installed. Install Docker Compose now? [Y/n] y
curl: (22) The requested URL returned error: 404
Prefer stable release versions of AzuraCast? [y/N] n
touch: cannot touch 'docker-compose.new.yml': Permission denied
curl: (23) Failed writing body (0 != 277)
/usr/local/bin/docker-compose: line 1: Not: command not found
/usr/local/bin/docker-compose: line 1: Not: command not found
rm: cannot remove 'docker-compose.installer.yml': No such file or directory
cp: cannot create regular file '.env.bak': Permission denied
cp: cannot create regular file '.env.bak': Permission denied
/usr/local/bin/docker-compose: line 1: Not: command not found
/usr/local/bin/docker-compose: line 1: Not: command not found
/usr/local/bin/docker-compose: line 1: Not: command not found

**Comment by SlvrEagle23** [comment]
@eduardonwa That probably means installing Docker Compose didn't work correctly...you can retry the Docker Compose installation by running:

```
./docker.sh install-docker-compose
```

then re-running the install:

```
./docker.sh install
```

**Comment by eduardonwa** [comment]
That command ouputs the following: ```curl: (22) The requested URL returned error: 404```

**Comment by SlvrEagle23** [comment]
@eduardonwa We've looked into this and it seems possible that this is happening because your architecture isn't supported (i.e. ARM instead of X86/X86_64) by our Docker installation. We've added a status check to the initial installation to help avoid issues like this.
