### ISSUE TITLE
Geo Location and OnDemand

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#4563]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#9d73d82 (2021-09-09 6:49) • Docker • PHP 8.0

### What happened?

Geo Location service works fine for radio streaming and it restricts access to banned countries but it doesn't work for OnDemand services.
Please enforce banned countries for OnDemand/Podcast listeners as well.

**Comment by SlvrEagle23** [comment]
@stardevelop We can certainly look into doing that, but currently this isn't a feature in our application and adding it would be a new feature request, which should likely be submitted through https://features.azuracast.com/ instead of through our issue tracker.
