### ISSUE TITLE
Nothing showing after login 

### ISSUE THREAD

**Issue by ItsJamieHosie** [AzuraCast/AzuraCast#4567]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #a75ae7d (2021-09-11 20:47)

### What happened?

Just updated but now unable to see anything or manage station but station is still working as my discord bot is still playing and updating its now playing,

If there is anything else you need me to add just let me know :) 

![image](https://user-images.githubusercontent.com/54157291/132963622-a4327606-3cb0-40b0-9cbd-021b8e507771.png)

**Comment by Abqehebter** [comment]
I can confirm this, with this errors in the dev console:
![image](https://user-images.githubusercontent.com/42640247/132963734-5c2b9f61-aa86-48ed-bb74-38afd007d8f1.png)

**Comment by SC2Mitch** [comment]
I believe Silver is working on a fix for this now, standby.

**Comment by SlvrEagle23** [comment]
Thank you both for the report. I'm pushing a fix up that should resolve this in the next version that publishes to Docker. Keep an eye on [this page](https://github.com/AzuraCast/AzuraCast/actions) and the next time the top action goes green, you should be able to pull the newest version.

**Comment by Abqehebter** [comment]
Yes I have now also seen. I was too slow. Thank you!

**Comment by ItsJamieHosie** [comment]
> 
> 
> Thank you both for the report. I'm pushing a fix up that should resolve this in the next version that publishes to Docker. Keep an eye on [this page](https://github.com/AzuraCast/AzuraCast/actions) and the next time the top action goes green, you should be able to pull the newest version.

Works for me now cheers buster just bought you a coffee too just want to say thanks for everything 😃
