### ISSUE TITLE
ERROR: No such service: nginx_proxy_letsencrypt

### ISSUE THREAD

**Issue by ressonix** [AzuraCast/AzuraCast#4574]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #e408420

### What happened?

After running `./docker.sh letsencrypt-create` to issue a Let's Encrypt certificate, the SSL doesn't appear to work. Instead, when navigating to the subdomain, it tells me that it's a self-signed certificate from `localhost`.

When I go to check the logs as outlined in the documentation (`docker-compose logs nginx_proxy_letsencrypt`), I get the following message: `ERROR: No such service: nginx_proxy_letsencrypt`

**Comment by ressonix** [comment]
It looks to me like the `nginx_proxy_letsencrypt` service never got created/initialized. How would I go about proceeding if the service doesn't exist?

**Comment by ressonix** [comment]
I actually figured it out. In case anyone comes across this issue in the future, here's what I did.

1. Inspect the `docker-compose.yml` file and see if the `nginx_proxy_letsencrypt` entry is present. If not, copy it from the [sample file](https://github.com/AzuraCast/AzuraCast/blob/main/docker-compose.sample.yml).
2. While still in the `docker-compose.yml` file, inspect the `web` entry, specifically under the `environment` section for [this](https://github.com/AzuraCast/AzuraCast/blob/061547bc1f75807884f3feb6f0fc9d1b0a09b4ba/docker-compose.sample.yml#L68) and [this](https://github.com/AzuraCast/AzuraCast/blob/061547bc1f75807884f3feb6f0fc9d1b0a09b4ba/docker-compose.sample.yml#L69). If it's missing, add it.
3. Save the file and re-run `./docker.sh letsencrypt-create`.

**Comment by SlvrEagle23** [comment]
@ressonix We've moved this into the update process...if you run the update script, it will ask you if you want to change any settings, and that will let you specify a LetsEncrypt domain; if you specify one, it will re-enable the LetsEncrypt container. The installer removes the LetsEncrypt container if you have no use for it (i.e. if the environment variables aren't set) to avoid repeatedly trying to set up LetsEncrypt when no domains are set up.

**Comment by gosntvrdi** [comment]
I have exactly the same issue, after ./docker.sh letsencrypt-create command, everything finisehd without problems, but letsencrypt container was never created. In docker-compose there is no defined letsencrypt container and in .env file there is this:

# LetsEncrypt Domain Name(s)
# Domain name (example.com) or names (example.com,foo.bar) to use with
# LetsEncrypt.
# LETSENCRYPT_HOST=

# LetsEncrypt E-mail Address
# Optionally provide an e-mail address for updates from LetsEncrypt.
# LETSENCRYPT_EMAIL=

# Additional Environment Variables
NGINX_TIMEOUT=1800
LETSENCRYPT_HOST=stream.******.com
LETSENCRYPT_EMAIL=********@gmail.com


SlvrEagle23, you are saying I should instead run ./docker.sh update-self | ./docker.sh update?

**Comment by SlvrEagle23** [comment]
I've updated the installer to ensure we won't remove the LetsEncrypt container (just in case someone sets their LetsEncrypt parameters up _outside_ the update process, which apparently a lot of folks are doing).

If you run the update process, it should resolve the issue and restore the LetsEncrypt container back if it's not present.
