### ISSUE TITLE
Jingle Does Not Play

### ISSUE THREAD

**Issue by pwrj** [AzuraCast/AzuraCast#4577]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

v0.14.1

### What happened?

Jingles or Station ID does not play as set. 

<img width="1044" alt="Screen Shot 2021-09-15 at 8 00 27 PM" src="https://user-images.githubusercontent.com/7035452/133528368-17c4884f-d7a0-433f-ade5-f956710ddfff.png">

<img width="1033" alt="Screen Shot 2021-09-15 at 8 00 38 PM" src="https://user-images.githubusercontent.com/7035452/133528375-dd540a81-f494-48e0-bf32-46501b4b96c1.png">

**Comment by atomino10** [comment]
I've got the same issue. I use it with scheduled timings and with weights. Every 3 hours a specific jingle must play. I made a playlist with wight=3 and the jingle's playlist with weight=5. Jingle's playlist does not stops the song that plays.

**Comment by atomino10** [comment]
I solved my issue.
Apparently when a change in playlists is made, autodj (liquidsoap) needs restart. I also restart broadcast to be sure.
!@#! this thing was confusing for months!

**Comment by pwrj** [comment]
@atomino10 Tried. Problem still there.

**Comment by pwrj** [comment]
@atomino10 I found the issue. I had too many playlists. One for each of the day. (24 of them). Somehow, Azuracast can't or don't handle too many playlist. (?). Anyhow, I disabled the 24 playlist and creating one main rotation Playlist and now my Jingles play with no issues. I don't know if @SlvrEagle23 should be made aware of this or not.

**Comment by atomino10** [comment]
nice!
