### ISSUE TITLE
After a couple of months, connections fail with Insecure site errors

### ISSUE THREAD

**Issue by shaunzyb** [AzuraCast/AzuraCast#4578]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.12.4

### What happened?

After a couple of months we start getting reports people can't connect. When this just happened I tried to connect with VLC and got the error message in the attached picture.

I have had a look at the logs but can't see anything related.

![IMG_8919](https://user-images.githubusercontent.com/78295894/133573507-a9eb38f7-8b1f-40d8-98d3-b977cb22f8aa.jpeg)

**Comment by SlvrEagle23** [comment]
@shaunzyb We don't currently have any way of automatically restarting Icecast when the SSL certificate is renewed, so every few months it is advised, if you're directly having users connect to the direct radio port, to restart broadcasting via `Utilities` > `Restart Broadcasting` on the station.

**Comment by shaunzyb** [comment]
Thanks for the info.

Can I do anything simple that would stop listeners connecting via this method?

Am I right in thinking they can could connect through an unencrypted stream? ( Is that right?)

**Comment by SlvrEagle23** [comment]
@shaunzyb You can enable the "Use Web Proxy" setting on the system settings, which will ensure that links on the radio player all use the proxied URLs, which are sent through the main LetsEncrypt certificate.

**Comment by shaunzyb** [comment]
I'll give that a go, Many thanks

**Comment by shaunzyb** [comment]
Just started to look at this and it is already ticked.

Should this issue not happen if it is ticked?
