### ISSUE TITLE
Bug adding a S3 compatible storage

### ISSUE THREAD

**Issue by ccaramel** [AzuraCast/AzuraCast#4579]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.14.1

### What happened?

When adding a S3 compatible storage (I own mine) it works perfectly using IP adresse of a server like xx.xx.xx.xx:9000/minio but when I try to replace by a domain (ie: mydomain.dyndns.org:9000/minio) it doesn't work anymore.
Please find attached error log.
I just replaced my domain by "mydomain.dyndns.org" and the name of my S3 bucket by "bucketname"
regards

### Relevant log output

```shell
App\Exception\ValidationException at /var/azuracast/www/src/Controller/Api/AbstractApiCrudController.php L168: Object(App\Entity\StorageLocation): Storage location S3: //bucketname.mydomain.dyndns.org:9000 could not be validated: Error executing "ListObjectsV2" on "//bucketname.mydomain.dyndns.org:9000/?list-type=2"; AWS HTTP error: cURL error 6: Could not resolve host: bucketname.mydomain.dyndns.org (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://bucketname.mydomain.dyndns.org:9000/?list-type=2
```

**Comment by Vaalyn** [comment]
According to the error log the domain you are trying to access could not be resolved:
```
cURL error 6: Could not resolve host: bucketname.mydomain.dyndns.org
```

This looks like a DNS issue to me. Are you able to access the S3 via that URL outside of AzuraCast to check if the access via the URL works in general?

**Comment by ccaramel** [comment]
the DNS is working since I use it everyday for many other services.
It seems that the error come from the way to write the URL.
with an IP azuracast is writing the URL the right way: XX.XX.XX.XX:9000/minio/bucketname
whereas with a domain name azuracast is writing  URL the wrong way: bucketname.mydomain.dyndns.org:9000/minio
it is not convenient to have a subdomain by bucketname ;)

**Comment by Vaalyn** [comment]
I have read a bit into the AWS PHP SDK and it seems like this is the default behaviour of the S3Client.
It was mentioned in an issue over in their repo that one can set the `use_path_style_endpoint` option to disable `virtual host style` for the endpoint. This might be better suited as a configuration option for the user in the Storage Location edit UI in AzuraCast so that it can be enabled/disabled as needed.

**Comment by ccaramel** [comment]
Thank you, could you please let me informed when implemented?
Regards

**Comment by julianborghuis** [comment]
^^

**Comment by SlvrEagle23** [comment]
@Vaalyn Just revisiting this one...is this still something we need to look into?

**Comment by Vaalyn** [comment]
> @Vaalyn Just revisiting this one...is this still something we need to look into?

Yes, we haven't yet added the possibility to toggle between `use_path_style_endpoint = false` (default) and `use_path_style_endpoint = true` for the S3 adapter / the S3 SDK to enable using S3 without subdomains.

**Comment by SlvrEagle23** [comment]
@Vaalyn Okay...how would we word this for most users to understand? I'm not sure I fully understand the distinction between the settings...I'm assuming this is a thing for when you're using non-S3 S3-style buckets.

**Comment by ccaramel** [comment]
Hi, this is something useful when using a self hosted S3 (like Minio) and your provider changer your public address quite often.

**Comment by ccaramel** [comment]
Ability to write S3 address with bucket name at the end of URL when using a DNS in endpoint (like it is done when using an IP address) will be enough.
to sum up:
when using XX.XX.XX.XX:9000/minio in endpoint and music in bucketname is works perfectly, azuracast uses "XX.XX.XX.XX:9000/minio/music" for storage address.
when using mydomain.dnd.org:9000/minio in endpoint and music in bucketname, azuracast uses "music.mydomain.dns.org:9000/minio" for storage adresse and it doesn't works.
Regards

**Comment by Vaalyn** [comment]
> @Vaalyn Okay...how would we word this for most users to understand? I'm not sure I fully understand the distinction between the settings...I'm assuming this is a thing for when you're using non-S3 S3-style buckets.

Maybe something like `Use path instead of sub-domain endpoint style` for the setting itself with a description that says something like this:

> Enable this option if your S3 provider is using paths instead of sub-domains for their S3 endpoint. This is needed for example when using MinIO or when other self hosted S3 storage solutions that are accessible via a path on a domain instead of a sub-domain

**Comment by Moonbase59** [comment]
I like @Vaalyn’s wording. Should be self-explanatory.

Personally, I use NFS mounts in AzuraCast’s (in-house) host to access the central music and backup storage, but since we don’t have that in the UI, people might opt for using S3, even in local (self-hosted) installations, since TrueNAS supports it (and uses MinIO as far as I know). Besides, S3 is of course also good for AWS "real" cloud storage.

So I’d agree that being able to select the "endpoint style" is still relevant and a good thing for self-hosters, too.

**Comment by saintcore** [comment]
@BusterNeece  Do you already know when this fix will be available in stable-release ? Currently I can go with the ip-based url (@ccaramel Thx for pointing this out!), but would love to use the dns-name once possible in stable-release.
