### ISSUE TITLE
Private release ?

### ISSUE THREAD

**Issue by RainbowDash53** [AzuraCast/AzuraCast#458]
Do you plan to make a private release ? I'm owner of a big network of stations and I wanted to know if you plan to make private release(custom look, private features, etc.) that it's not free or it's not planned for now ?

**Comment by SlvrEagle23** [comment]
@RainbowDash53 My current goal for monetizing AzuraCast is through donations and other support from the radio station owner community. I've also had some people express an interest in sponsoring my development time in building certain features that they want, provided those features remain in the open-source application after they're built.

The Apache license is very permissive if you would like to fork AzuraCast, apply your own branding and use the product internally. For the public pages, the branding customization should remove most of the need to do this.

If you specifically would like my help in building something custom-built for your network, by all means let me know. I don't mind the work. :)

**Comment by RainbowDash53** [comment]
I already saw that on RadioKing I think, it was 1 year ago, don't know if they keep this features but they offer the possibility to put an Spotify playlist url and all the titles was added in the medias files, could be so great: Don't need to download and upload it all media files, etc.
