### ISSUE TITLE
Doesn't display statistics graphs

### ISSUE THREAD

**Issue by zloysystem** [AzuraCast/AzuraCast#4584]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #cbf1b7e (2021-09-16 18:50)

### What happened?

Does not display statistics graphs on the main panel and inside station accounts.

**Comment by zloysystem** [comment]
![Безымянный](https://user-images.githubusercontent.com/26243386/133882661-27b01c95-f1ac-4316-8098-78e14bdaae6d.png)

**Comment by Abqehebter** [comment]
I can confirm this:
![image](https://user-images.githubusercontent.com/42640247/133882665-a7cfe25c-aa63-4475-9150-fff429afa56c.png)

**Comment by SC2Mitch** [comment]
yep verified, thanks for the reports guys,
