### ISSUE TITLE
./docker.sh restore

### ISSUE THREAD

**Issue by aarkkappler** [AzuraCast/AzuraCast#4585]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #cbf1b7e (2021-09-16 18:50)

### What happened?

backup & restore commande does not work

./docker.sh backup

./docker.sh restore

### Relevant log output

```shell
./docker.sh: line 603: realpath: command not found
File '' does not exist. Nothing to restore.
```

**Comment by SC2Mitch** [comment]
Have you followed our documentation on how to restore and backup installations? It's not just `./docker.sh backup` you need to include the file paths as well.

**Comment by aarkkappler** [comment]
Hi yes I deed in several file.zip, ./file.zip, /absolutpath/file.zip

**Comment by SlvrEagle23** [comment]
@aarkkappler I looked this up, and apparently some distributions don't ship with the `realpath` command as it isn't as common as the GNU coreutils `readlink` command, which accomplishes the same thing, so I've updated the Docker utility script to instead use the more common version of that command.

You can run `./docker.sh update-self` and then continue your restore and it should work without any issues.

**Comment by aarkkappler** [comment]
Thank you, I downgraded already because I had an error message, already no more compatibility with Darwin, I hope it will work with it anymore, thank you for you answer
