### ISSUE TITLE
HTML not being applied in certain circumstances after large Vue overhaul

### ISSUE THREAD

**Issue by callumok2004** [AzuraCast/AzuraCast#4589]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.14.1

### What happened?

![image](https://user-images.githubusercontent.com/35779365/133910594-f8c4a9d3-d82c-4780-950c-1d52a0f7d777.png)
The html is not being applied

**Comment by SC2Mitch** [comment]
thanks, on it.

**Comment by SC2Mitch** [comment]
Replicated on the latest rolling release. 

The code is located here: https://github.com/AzuraCast/AzuraCast/blob/main/config/forms/station.php#L282

Valid bug, flagged for you. I'm unsure as to why its doing this, as other areas that use hyperlinks seem to be working fine.
