### ISSUE TITLE
Swagger UI always using the demo server instead of the installed one

### ISSUE THREAD

**Issue by MarkWasley** [AzuraCast/AzuraCast#4590]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #cbf1b7e (2021-09-16 18:50)

### What happened?

The Swagger UI does not display the installed server. Only the AzuraCast Public Demo Server is selectable and all data on this page is supplied from the demo server. I can use all the endpoints as normal throughout the application.

![Swagger UI](https://user-images.githubusercontent.com/25557014/133912554-fbd4acd1-8ecb-48d9-8e2f-f35e50380a20.png)

Thanks to @SC2Mitch for the screenshot, presumably from his installation.

**Comment by Vaalyn** [comment]
I can see this on my test installation too.

When I check my production installation that is not on the latest rolling-release I can see that one showing the correct server in the dropdown. I have compared the `openapi.yml` from both and they have the same `server` set (the demo instance).
I'm not quite sure what has changed that could cause this problem. I'm actually not 100% sure where the older installation gets the server url from, will need to look into where it is taking the url from to check why this isn't the case on recent versions.

**Comment by Vaalyn** [comment]
If you have already found the commit just ignore this comment.

This is the commit that introduced the change that causes the `AZURACAST_API_URL` to not be set to `$api_base_url` anymore:
https://github.com/AzuraCast/AzuraCast/commit/f6c1fbf79c73dcfab61357717c39bfd7db9bf4e3#diff-bf25c35551507ed05e69cb7024fdc0690e272328c9affc412aeb3bfc25c0c8ee
