### ISSUE TITLE
Custom Icy Metadata Not Showing Up

### ISSUE THREAD

**Issue by ressonix** [AzuraCast/AzuraCast#4592]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #e408420 (2021-09-14 16:41)

### What happened?

I added the following XML to the "Custom Frontend Configuration" for each mount:
```xml
<http-headers>
      <header name="icy-index-metadata" value="1" />
</http-headers>
```

Unfortunately, **after restarting by going to Utilities > Restart Broadcasting**, it appears that the header value isn't being served:
![image](https://user-images.githubusercontent.com/60057409/133914137-b9a9f30e-7942-4f56-a697-d9219c25327d.png)

Why would this be the case? Is there something I'm missing? This particular value is needed for various YP services to update station information.

**Comment by ressonix** [comment]
I checked the Icecast Error Log, it provides me with the following error:

```
[2021-09-18  23:00:25] WARN xml/parsing unknown element "http-headers" parsing "mount" at line 52
```

**Comment by ressonix** [comment]
Should I just edit the configuration file directly instead? I was researching this issue previously and one of the maintainers said adding it to the mounts as I did _should_ work.

**Comment by Vaalyn** [comment]
AzuraCast uses the Icecast-KH fork of Icecast.
The `http-headers` element was introduced in Icecast 2.4.1 and seems to not yet be available in Icecast-KH.
