### ISSUE TITLE
specific URL doesnt play on playlists.

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#4597]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

AzuraCast • Rolling Release #aeb230e (2021-09-20 5:18) • Docker • PHP 8.0

### What happened?

I need to make an URL playlist that plays at certain time. but, this URL specifically wont play and every software that plays remote urls, it works. the url is:
http://audio.livemix.com.br/livemix
The radio keeps stoped and stream offline.

**Comment by adoboligh1** [comment]
same issue

**Comment by nunotfc** [comment]
i found the error. this stream is aac. i think is a liquidsoap bug playing aac streams. could someone verify or someone have some idea to correct? i verified also that this link i provided has wrong headers. for example in chrome, aks me to download a infinite file instead of playing it.

**Comment by nunotfc** [comment]
closing because ishue #4787 has more information
