### ISSUE TITLE
Album cover art does not change after changing it in branding section

### ISSUE THREAD

**Issue by pawelzet** [AzuraCast/AzuraCast#4598]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.14.0 Stable

### What happened?

Hello, 

I was trying to change default cover art on my azuracast instance. I've changed it from default coverart URL to the uploaded file in the new branding section. Unfortunately In the player I stil have old Cover Art from the old URL, instead of new uploaded image. I even tried to upload the new image to imgur and put it in the URL default coverart, but still, the only art i can see is the old, deleted one.

Thank you in advance for your help.

**Comment by Abqehebter** [comment]
I had to change my "Default Cover" once, too. Sure the old ones don't change, but "the new covers" should be the ones you entered there.
Is the link correct?
With me it worked after some time.

**Comment by pawelzet** [comment]
Ok, I think i found the reaseon right after adding this post - I've only changed branding section in the administration panel. I forgot that there is also Default Cover URL in the setting panel of the Radio Station. I hope it is going to work now. Sorry for the misunderstanding.

**Comment by Abqehebter** [comment]
Good luck! ;)
