### ISSUE TITLE
Docker-compose azuracast_install needs to be run as sudo

### ISSUE THREAD

**Issue by oresot** [AzuraCast/AzuraCast#460]
- **Installation Method:** Docker
- **Host OS (if using Docker):** macOS 10.13.2

**Describe the issue in full detail, including screenshots if possible:**

Following the steps for docker-compose install is not giving me the expected result. azuracast_install doesn't seem to have permission to write on the volume.

I need to run the command as sudo `docker-compose run --rm cli sudo azuracast_install`

This should be noted on the documentation.

```➜  azura docker-compose run --rm cli azuracast_install
Starting azura_redis_1 ...
Starting azura_influxdb_1 ... done
Starting azura_mariadb_1 ... done
Starting azura_web_1 ... done
Updating AzuraCast (Environment: production)
error: unable to write file .codeclimate.yml
error: unable to write file .env
error: unable to write file .gitattributes
error: unable to write file .github/ISSUE_TEMPLATE.md
error: unable to write file .gitignore
error: unable to write file .travis.yml
error: unable to write file CONTRIBUTING.md

[...]

error: unable to write file web/static/yarn.lock
fatal: Could not reset index file to revision 'HEAD'.
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

ERROR! playbooks must be a list of plays```

**Comment by SlvrEagle23** [comment]
@oresot I think this may be a bug with your specific setup. Typically the installer actually doesn't require sudo permissions, and indeed _should_ be run as the `azuracast` user inside Docker so it appropriately sets the permissions to the files it creates.

I'll flag this as a bug for further investigation.

**Comment by oresot** [comment]
I have tried the same procedure in our Debian server, and there it works as expected without the "sudo", I guess the issue is related with running that from macOS the previous time (permissions on mounted volumes?).

**Comment by SlvrEagle23** [comment]
@oresot This may also have been related to using the older `docker-compose.yml` file that directly mounted the AzuraCast codebase from the folder you were running in, instead of keeping them all in Docker volumes (which removes a number of these types of permission issues). Using the newest Docker Compose style, you shouldn't need to customize any of the commands to get them to run correctly.
