### ISSUE TITLE
playlist files don't work with itunes

### ISSUE THREAD

**Issue by gosntvrdi** [AzuraCast/AzuraCast#4600]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #8b83d8a (2021-09-20 23:54)

### What happened?

Stream files that are available for download on Profile page do not work with Itunes. Both pls and m3u files work correctly with VLC/Winamp etc, but will not open in Itunes. I tried adding stream to itunes by entering adress manually, but to no avail (player makes an audible glitch and stops the player).
Can confirm this is happening on both Mac and Windows machines.
Manual adress I tried entering is something like:
http://xxx.xxx.xxx.xxx/radio/8000/radio.mp3
http://xxx.xxx.xxx.xxx/:8000

I am not using SSL and Let'sEncrypt.

**Comment by Abqehebter** [comment]
You might think it's because you don't use SSL here. Apple itself has always been a disaster for me without SSL.
But just a guess.

**Comment by SC2Mitch** [comment]
Most likely an Apple thing wherein they require HTTPS

**Comment by gosntvrdi** [comment]
i just installed letsencrypt SSL, this is not it, still doesn't play in itunes.
