### ISSUE TITLE
Roles & Permissions Error

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#4601]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #8b83d8a (2021-09-20 23:54)

### What happened?

I'm trying to grant permissions to a user while in the Roles & Permissions settings and I'm seeing an error. This applies to Ansible and Docker. I couldn't find an additional line in the logs.

Check Please:

1-) https://prnt.sc/1t3hz2j (Ansible)
2-) https://prnt.sc/1t3hzj1 (Docker)

**Comment by SlvrEagle23** [comment]
@ogrenci01 This should be mitigated in the latest Rolling update.
