### ISSUE TITLE
Azura videostream not streaming to Youtube

### ISSUE THREAD

**Issue by idolaru** [AzuraCast/AzuraCast#4602]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.14.1 Stable • Docker • PHP 8.0 

### What happened?

Has anyone managed to make the azuracast/videostream to successfully stream to YouTube?

I posted a comment in the proper repo but although following the installation and settings properly, the stream doesn't go live.

I have a feeling this is an abandoned project and just trying to find a solution to a problem I can't see.

1. Successfully running azuracast with SSL enabled
2. Properly installed and running the videostream add-on with no errors
3. Triple checked the configuration file, everything is ok.

Anyone has any idea ?

Thank you in advance for the assistance.

**Comment by SC2Mitch** [comment]
https://github.com/AzuraCast/radio-video-stream/issues/16
Resolved in here, was user configuration error.
