### ISSUE TITLE
Can't upload File when use API

### ISSUE THREAD

**Issue by lamnhungoc** [AzuraCast/AzuraCast#4603]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

#eb8f564 

### What happened?

Dear Team,
I can't upload file through API POST
​/station​/{station_id}​/files/upload
with body: {
  "path": "relative/path/to/file.mp3",
  "file": ""
}
Can you help me ?
Here is my code !
![1](https://user-images.githubusercontent.com/24890845/134237581-9e75f601-a327-4546-b52a-0167c64e7fb8.PNG)
![3](https://user-images.githubusercontent.com/24890845/134237583-c0a47f3c-30e5-438f-a13c-7a1ec7812cbf.PNG)

**Comment by lamnhungoc** [comment]
Dear Mr.SC2Mitch,
I check it return message {success: false} and status is 200.
I attach image file below :
![0](https://user-images.githubusercontent.com/24890845/134280283-0628a1ee-72c1-4b5b-9286-9eb0f0721e91.PNG)
![1](https://user-images.githubusercontent.com/24890845/134280288-8f0680bd-700b-4f22-92d9-816dfb54c1fc.PNG)
Thank you very much !

**Comment by quydox** [comment]
does this issue fixed bro? :D @lamnhungoc

**Comment by lamnhungoc** [comment]
@quydox I don't support for it !
I must change to a difference framework !

**Comment by quydox** [comment]
> @quydox I don't support for it ! I must change to a difference framework !

This one is fixed bro 

```
curl --location --request POST 'http://localhost:8888/api/station/1/files/upload' \
--header 'Content-Type: application/json' \
--header 'X-API-Key: 87ec9c8949e65a53:8a8bfe685010c170a57632eba4d6ce00' \
--header 'Cookie: PHPSESSID=fd0k8qipgadolnqkv0jeomgpge' \
--form 'path="diss/dis1.mp3"' \
--form 'file=@"/home/little/tmp/theloai-nhanha.m4a"' \
--form 'currentDirectory="diss"'
```
