### ISSUE TITLE
Schedule Text

### ISSUE THREAD

**Issue by mickflix** [AzuraCast/AzuraCast#4605]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

Good Morning, 
Im setting up playlists in the schedule to play at specific times and playlists fail to takeover the default playlist and don't start
also in the public schedule page blue block that appears after setting up a playlist doesnt show the playlist name etc

**Comment by Abqehebter** [comment]
Is the default playlist also set with a certain time?

**Comment by mickflix** [comment]
I haven't touched any of the settings on the default playlist
ive just set a playlist now it should say workout mix but theres no text in
the schedule public page but i can view on the dashboard

**Comment by Abqehebter** [comment]
You mean these entries here or?
![image](https://user-images.githubusercontent.com/42640247/134301440-13e75116-d9d8-4e7c-8173-8ae2a3346650.png)

On public pages there is still the error here: https://github.com/AzuraCast/AzuraCast/issues/4505
... where not all playlists are displayed but only internally.

**Comment by mickflix** [comment]
yes thats right

**Comment by Abqehebter** [comment]
Okay we have that with the public page and the schedule.
Now there is only the problem that the playlist does not start, right?
If so, what is the internal schedule where the playlist should actually run? Do you have a screenshot for me?

**Comment by mickflix** [comment]
minor success, i had to disable the default playlist and restart autodj and the new playlist started at the correct time but didn't end at the start of a new playlist ( hopefully that makes sense)

**Comment by mickflix** [comment]
are there any problems with the schedule and playlists on ansible install ?

**Comment by SC2Mitch** [comment]
Ansible uses the exact same Liquidsoap software like Docker and the same code, Ansible is not supported by us and support is incredibly limited.
