### ISSUE TITLE
No Access to Roles

### ISSUE THREAD

**Issue by aarkkappler** [AzuraCast/AzuraCast#4606]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #09b5e1d (2021-09-22 2:56)

### What happened?

Hi When I Tried to use roleRoles & Permissions it does not works, here where can I get :
https://mywebsite/admin/permissions

![Roles](https://user-images.githubusercontent.com/9117901/134466764-67b4ddcb-c008-4395-b71d-0decc3cb73d9.jpg)

regards

### Relevant log output

```shell
Let Me know what relevant output I can provide
```

**Comment by Abqehebter** [comment]
Please check `Administration > System Logs > AzuraCast Application Log` for relevant logs once you access the page. An error should appear there.

**Comment by SC2Mitch** [comment]
taking a look now.

**Comment by Abqehebter** [comment]
For me it's running as it should:
![image](https://user-images.githubusercontent.com/42640247/134555790-cd6eca26-69be-45c9-a7df-d7dcbcfa865c.png)

**Comment by aarkkappler** [comment]
I completely reinstalled, the docker-compose now it works, I think it could be interesting to explain the background process

I can mention a lot of nginx proxy error (from my understanding) that explain a lot of inconsistency due to a bad usage or bad troubleshooting workflow.

**Comment by aarkkappler** [comment]
I totally reinstalled the service, now it works fine, but I don' understand

**Comment by aarkkappler** [comment]
I totally reinstalled the service, now it works fine, but I don' understand
