### ISSUE TITLE
Impossible to broadcast

### ISSUE THREAD

**Issue by zilon93** [AzuraCast/AzuraCast#4607]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

I cant broadcast to azura from Radiocaster or another stream program, it show error 40 network timeout, i try directly and creating a dj. What i have do bad?

**Comment by Abqehebter** [comment]
Can you show us the configuration of Radiocaster? **Important**: Please censor your password if it is not already censored!

**Comment by zilon93** [comment]
(https://user-images.githubusercontent.com/50178250/134494351-9f9fd598-d468-4981-a379-d812c0bf3a81.jpeg)

**Comment by Abqehebter** [comment]
Seems to look normal. Can you send me some from the Configuration Wizard?
Important would be the DJ name and mount point (example:)
![image](https://user-images.githubusercontent.com/42640247/134494937-34358089-2c84-493d-b0f5-73fd240c1fc2.png)

**Comment by zilon93** [comment]
![WhatsApp Image 2021-09-23 at 12 59 16 PM](https://user-images.githubusercontent.com/50178250/134495933-e34ce5a3-e871-4b47-95ea-3a1cd13169e8.jpeg)
![WhatsApp Image 2021-09-23 at 12 59 17 PM](https://user-images.githubusercontent.com/50178250/134495936-f2c7d53e-3e71-4848-a8f2-e3d770ea2951.jpeg)

**Comment by Abqehebter** [comment]
Did you set a live mount point in your station config?
So here: `Station 1 > Edit Profile > AutoDJ > Customize DJ/Streamer Mount Point`

![image](https://user-images.githubusercontent.com/42640247/134496133-d0cedf41-9725-4b6d-a13b-d3e780c51f0a.png)

**Comment by zilon93** [comment]
I do it just now and nothing happend Installation Method
![Captura de pantalla 2021-09-23 a las 13 09 05](https://user-images.githubusercontent.com/50178250/134497145-6a1f7ad4-f720-46fa-84d6-ae24d2e67877.png)

**Comment by Abqehebter** [comment]
The `Customize DJ/Streamer Mount Point` is not the DJ name. Enter /central under `Moint point` on **Radiocaster**.

**Comment by zilon93** [comment]
![WhatsApp Image 2021-09-23 at 1 16 10 PM](https://user-images.githubusercontent.com/50178250/134498601-5fa60336-3fbc-45f2-b5a2-f980c650743a.jpeg)

**Comment by Abqehebter** [comment]
Thanks first of all for your tests.
I read quite often with the' Error 40 (network timeout) from Radiocast that it is due to a firewall in the PC or server.
Also possible that Cloudflare is switched on AzuraCast here.
Has this all been tested?

**Comment by zilon93** [comment]
all ports are supposed to be open
![Captura de pantalla 2021-09-23 a las 13 29 17](https://user-images.githubusercontent.com/50178250/134499439-13c7836d-5688-4e5a-bbc0-83f249fee520.png)

**Comment by Abqehebter** [comment]
Please try to open port 8035 separately:
`8035 - 0.0.0.0/0 - TCP`
If this doesn't work, you can try with UDP

**Comment by zilon93** [comment]
Its work!!!
