### ISSUE TITLE
Random shuffling 

### ISSUE THREAD

**Issue by aarkkappler** [AzuraCast/AzuraCast#4611]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #09b5e1d (2021-09-22 2:56) 

### What happened?

I noticed that the reading of tunes of a playlist is not random, there is a way to force random shuffling/mixing 

thank you

**Comment by Abqehebter** [comment]
The playlists have different random methods:
1. shuffle, where the whole playlist is played through completely in random order.
2. random, where the tracks are simply taken randomly from the playlist.
Both methods work fine (at least for me).
![image](https://user-images.githubusercontent.com/42640247/134653228-b7a7ace5-6459-4aa5-957f-10e4e2c42b2c.png)

**Comment by aarkkappler** [comment]
Ok, Many thanks, maybe I have to click on RANDOM, thank you

**Comment by aarkkappler** [comment]
Ok, Many thanks, maybe I have to click on RANDOM, thank you
