### ISSUE TITLE
cli SYNC nowplaying, short, medium, long : Failed to open stream: Permission denied

### ISSUE THREAD

**Issue by aarkkappler** [AzuraCast/AzuraCast#4612]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #09b5e1d

### What happened?

ERROR: 1
Mac-mini-de-Guillaume:kap 3verL4S57ing$ ./docker.sh cli sync:run mediumCan we 

### Relevant log output

```shell
ERROR: 1
Mac-mini-de-Guillaume:kap 3verL4S57ing$ ./docker.sh cli sync:run medium
Creating azuracast_web_run ... done
Starting up AzuraCast services...
Services started up and ready!

In StreamHandler.php line 119:
                                                                                                                                               
  The stream or file "/var/azuracast/www_tmp/app-2021-09-23.log" could not be opened in append mode: Failed to open stream: Permission denied
```

**Comment by SC2Mitch** [comment]
taking a look, standby for information to follow

**Comment by SC2Mitch** [comment]
Okay I uncovered a few issues with the CLI process, I shall be closing this ticket in favor of a detailed one, thank you for the assistance it has been greatly appreciated! . https://github.com/AzuraCast/AzuraCast/issues/4613
