### ISSUE TITLE
Can't get files into playlist

### ISSUE THREAD

**Issue by mndhkr** [AzuraCast/AzuraCast#4614]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #09b5e1d (2021-09-22 2:56)

### What happened?

i uploaded files directly into the media folder.
i select my folder under files, and add to a new playlist.
i go under playlist.
the playlist show 0 files.

playlist name is albums.

**Comment by Abqehebter** [comment]
What does the folder look like? Are all the files processed correctly there? Did you also try to bring the folder 2x into the said playlist?

**Comment by mndhkr** [comment]
Thank you. Selecting the folder, clicking on playlist, deselecting playlist, reselecting playlist, did the trick :)
