### ISSUE TITLE
Super Admin role can be modified incorrectly

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#4615]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

4792acc

### What happened?

After the recent permission change to migrate it to Vue, it removed the restriction on allowing Super Admin accounts to edit the Super Admin permission. This can lead to users being locked out of their accounts inadvertenly. This should be locked off to all users regardless of permissions. 

Going to flag this under security too as it can lead to account lockout and a user is unable to access the site.

**Comment by adoboligh1** [comment]
I get what you mean but I think this isn't that really that much of a big deal because this has been made to disallow anyone who isnt the main  super admin to modify rules I guess :)
