### ISSUE TITLE
OVERRIDE does not works

### ISSUE THREAD

**Issue by aarkkappler** [AzuraCast/AzuraCast#4616]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #09b5e1d (2021-09-22 2:56) 

### What happened?

Hi, this override does not work what is not good on it ? Many thanks for your help
version: '2.2'

services:
  web:
    volumes:
      - $PWD/stations:/var/azuracast/stations
      - $PWD/certs_ro:/etc/nginx/certs:ro
      - $PWD/vendor:/var/azuracast/www/vendor
      - $PWD/uploads:/var/azuracast/uploads
      - $PWD/tmp:/var/azuracast/www_tmp
      - $PWD/shoutcast:/var/azuracast/servers/shoutcast2
      - $PWD/geoip:/var/azuracast/geoip
      - $PWD/persist:/var/azuracast/sftpgo/persist
      - $PWD/backup:/var/azuracast/backups
  stations:
    volumes:
      - $PWD/stations:/var/azuracast/stations
      - $PWD/shoutcast:/var/azuracast/servers/shoutcast2
      - $PWD/certs:/etc/nginx/certs
      - $PWD/tmp:/var/azuracast/www_tmp
      - ./radio.mp3:/usr/local/share/icecast/web/radio.mp3

**Comment by Vaalyn** [comment]
You can't use `$PWD` in a docker-compose .yml file.
Try using relative paths like this: `./stations:/var/azuracast/stations`
