### ISSUE TITLE
Let's Encrypt Issues

### ISSUE THREAD

**Issue by pwrj** [AzuraCast/AzuraCast#4620]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

v0.14.1

### What happened?

I have 2 domains pointing to one instance of Azuracast, but only one of the domain is secure, the other one shows like this:

Your connection is not private
Attackers might be trying to steal your information from www.mydomain2.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_INVALID

See below: 

<img width="1226" alt="Screen Shot 2021-09-25 at 9 00 09 AM" src="https://user-images.githubusercontent.com/7035452/134772755-31fc054c-639b-4859-8c45-6e226ab7c6eb.png">

What am I doing wrong?

I checked my .env files and it has both of my domains listed:

# LetsEncrypt Domain Name(s)
# Domain name (example.com) or names (example.com,foo.bar) to use with
# LetsEncrypt.
LETSENCRYPT_HOST=mydomain1.com,mydomain2.com

Any assistance is greatly appreciated. Is this a bug or my own error?

### Relevant log output

myserver:/var/azuracast# docker-compose logs nginx_proxy_letsencrypt
Attaching to nginx_proxy_letsencrypt
nginx_proxy_letsencrypt    | Info: running letsencrypt-nginx-proxy-companion version v2.0.2
nginx_proxy_letsencrypt    | Info: Custom Diffie-Hellman group found, generation skipped.
nginx_proxy_letsencrypt    | Reloading nginx proxy (cc29eece7d5d83e59e42afa88fd5a976d1127b1f4e2a94012345191cba7b0b0c)...
nginx_proxy_letsencrypt    | 2021/09/25 14:07:50 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx_proxy_letsencrypt    | 2021/09/25 14:07:50 [notice] 58#58: signal process started
nginx_proxy_letsencrypt    | 2021/09/25 14:07:50 Generated '/app/letsencrypt_service_data' from 6 containers
nginx_proxy_letsencrypt    | 2021/09/25 14:07:50 Running '/app/signal_le_service'
nginx_proxy_letsencrypt    | 2021/09/25 14:07:50 Watching docker events
nginx_proxy_letsencrypt    | 2021/09/25 14:07:50 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
nginx_proxy_letsencrypt    | Reloading nginx proxy (cc29eece7d5d83e59e42afa88fd5a976d1127b1f4e2a12345fcb191cba7b0b0c)...
nginx_proxy_letsencrypt    | 2021/09/25 14:07:51 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx_proxy_letsencrypt    | 2021/09/25 14:07:51 [notice] 90#90: signal process started
nginx_proxy_letsencrypt    | Creating/renewal domain1.com certificates... (domain1.com domain2.com)
nginx_proxy_letsencrypt    | [Sat Sep 25 14:07:51 UTC 2021] Domains not changed.
nginx_proxy_letsencrypt    | [Sat Sep 25 14:07:51 UTC 2021] Skip, Next renewal time is: Fri Nov 19 00:29:29 UTC 2021
nginx_proxy_letsencrypt    | [Sat Sep 25 14:07:51 UTC 2021] Add '--force' to force to renew.
nginx_proxy_letsencrypt    | Sleep for 3600s

**Comment by Abqehebter** [comment]
Does it work with only one domain?

**Comment by pwrj** [comment]
> Does it work with only one domain?

It does. With domain1.

**Comment by Abqehebter** [comment]
I don't think that two domains will be supported. But I am not sure either. I only use one.
Maybe the team here knows more.

**Comment by pwrj** [comment]
> I don't think that two domains will be supported. But I am not sure either. I only use one.
> Maybe the team here knows more.

I think it does. See below: 
<img width="1129" alt="Screen Shot 2021-09-25 at 9 25 19 AM" src="https://user-images.githubusercontent.com/7035452/134773166-f02ab089-5d6c-42fd-865b-0668a5e0467b.png">

**Comment by Abqehebter** [comment]
Thank you for the correction. I also just see in the .env that this is exactly how it should be done.

LETSENCRYPT_HOST=example.com,example2.com

So the application is correct. Does then still work the first one with the certificate or do then just both not work at all?

**Comment by pwrj** [comment]
> Thank you for the correction. I also just see in the .env that this is exactly how it should be done.
> 
> LETSENCRYPT_HOST=example.com,example2.com
> 
> So the application is correct. Does then still work the first one with the certificate or do then just both not work at all?

No problems. I had to look again as well to be sure. In my case, it works with domain1.com, but not with domain2.

**Comment by gunsar** [comment]
I freshly installed the latest version, then setting Using a Custom Certificate according to the instructions in
https://docs.azuracast.com/en/administration/ssl-and-lets-encrypt
I entered the Sectigo SSL according to the instructions and settings in docker-compose.override.yml
But after checking SSL Checker several times it still detects Let's Encrypt
This makes me confused, please solve it

**Comment by mohmafia** [comment]
that is why i use nginx proxy manager in docker you can then point 2 domain names to same container with letsencrypt ssl

**Comment by franckpacaud** [comment]
> that is why i use nginx proxy manager in docker you can then point 2 domain names to same container with letsencrypt ssl

Can I ask how you managed to set up nginx proxy manager with an azuracast instance? I'm having problems where my certificat fails to renew in nginx proxy manager. 

sorry for the noob question

**Comment by mohmafia** [comment]
you have to renew them manually .... as far as i know
