### ISSUE TITLE
Not Able to see the following tune

### ISSUE THREAD

**Issue by aarkkappler** [AzuraCast/AzuraCast#4621]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #09b5e1d (2021-09-22 2:56) 

### What happened?

Hi Everyone, I am not about to see the following tune

I don't think it's a good idea to make a ./docker.sh cli cache:clear

![error](https://user-images.githubusercontent.com/9117901/134773602-2b3568bd-e17b-4bfc-b291-419665884517.jpg)

### Relevant log output

```shell
let me know what kind of log can help to investigate
```

**Comment by SC2Mitch** [comment]
I'm not sure what exactly your image is trying to show, what is the exact issue here, you cant see the full song name?

**Comment by aarkkappler** [comment]
usually u have to parts the current playing song and the future song, I am not able to see the future song

**Comment by aarkkappler** [comment]
override :

version: '2.2'

services:
  web:
    volumes:
      #- ./azuracast-nginx.conf:/etc/nginx/conf.d/azuracast.conf:ro
        - ./stations:/var/azuracast/stations
    environment:
          VIRTUAL_HOST: my.web.site
  stations:
    volumes:
      - ./stations:/var/azuracast/stations
      - /Volumes/EXTERNAL/media:/var/azuracast/stations/fr/media
      - ./uploads:/var/azuracast/uploads
      - ./tmp:/var/azuracast/www_tmp
      - ./backup:/var/azuracast/backup
      - ./persist:/var/azuracast/sftpgo/persist
      - ./stations/error.mp3:/usr/local/share/icecast/web/error.mp3
      - ./stations/radio.mp3:/usr/local/share/icecast/web/radio.mp3
      - ./stations/intro.mp3:/usr/local/share/icecast/web/intro.mp3

  videostream:
    container_name: videostream
    build:
      context: ./videostream
    volumes:
      - ./stations:/var/azuracast/stations
      - ./tmp:/var/azuracast/www_tmp
    restart: always
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    environment:
      # VS_VBR: 1500k
      # VS_FPS: 24
      # VS_QUALITY: superfast
      VS_RTMP_SERVER: rtmp://a.rtmp.youtube.com/live2/…
      # VS_FONT_FILE: /usr/share/fonts/truetype/ubuntu/Ubuntu-B.ttf
      VS_TEXT_SOURCE: /var/azuracast/stations/fr/config/nowplaying.txt
      # VS_TEXT_SIZE: 55
      # VS_TEXT_BOX: 1
      # VS_TEXT_BOX_COLOR: black@0.5
      # VS_TEXT_BORDER_W: 20
      # VS_TEXT_X: 100
      # VS_TEXT_Y: 350
      VS_AUDIO_SOURCE: https://my.web.site/radio/8000/file.mp3
      VS_VIDEO_SOURCE: /var/azuracast/videostream/file.mp4
  phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
         - mariadb
        networks:
         - backend
        ports:
          - notexposed:80"
        restart: always
        environment:
          PMA_HOST: …
          MYSQL_ROOT_PASSWORD: …
