### ISSUE TITLE
How to move files from local filesystem to S3 without breaking the playlists ?

### ISSUE THREAD

**Issue by Shaltz** [AzuraCast/AzuraCast#4622]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #45b899c (2021-09-24 22:18)

### What happened?

For a long time I used the local file system to store the media for my radio, 
but now I'd like to move them all to S3 without having to redo all the playlists and all.
I tried to copy them (keeping the same data structure as in /var/azuracast/stations/.../media/)
to S3, I changed the storage location in the administration part of my radio, but after doing do, 
the playlist showed 0 songs available, and obviously nothing was playing...
I guess their is something to do with the data base, but before doing anything armful, 
I'd like to know if there is a better/official/proper way to do this ?

thanks in advance

**Comment by SlvrEagle23** [comment]
@Shaltz I'm not sure of the best way of accomplishing this, but I believe if you do this:

 - Connect to your new S3 storage location
 - Copy all of your existing media over to it, one-to-one, from your existing media directory
 - Update the station's _existing_ storage location (via `Administration` > `Storage Locations`) to use the new S3 location

...then it should re-detect all the same media in the same location and thus preserve the associations with playlists and such.

**Comment by Shaltz** [comment]
Hi @SlvrEagle23 

That is exactly what I did, expecting the playlists to update the path to the files, if the folder structure stayed the same, 
but that didn't work :(
Is there a button to click somewhere to force update the path of the files in the database, or do you have to wait a set
 amount of time for the files path to be updated or something ?

Or have I missed something somewhere ??

thanks again for you reply

PS: after moving the files to S3 and changing the storage location in the Admin panel of the radio, I could see the files
in the "Music Files" tab, and I could play them from there... I could even enqueue selected files to be played by the radio... 
But the AutoDJ didn't seem to see the files... the service was up and running, it could see my 22 playlists but it couldn't see my files, it kept showing 0 files...
And obviously I had restarted the service, rebooted the server... no luck...

any idea ??


thanks again ;)

**Comment by redwerkz** [comment]
I can confirm exactly that behavior and the pain of recreating all the lists. I'm using Wasabi as S3 Storage.
