### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by istahilagi** [AzuraCast/AzuraCast#4631]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

i am facing problem when logging in azuracast...
the following message appears

Slim Application Error... 
A website error has occurred. Sorry for the temporary inconvenience.

this is the log https://daarunnajaa.com/error.txt

Please help me
thanks

**Comment by Vaalyn** [comment]
The log is complaining about "Redis is configured to save RDB snapshots, but it is currently not able to persist on disk" which might hint at the server not having any HDD space left (or something else).

Could you post the logs of the redis container so we can check what it is saying?

**Comment by istahilagi** [comment]
what command should i type in putty sis?

**Comment by Vaalyn** [comment]
```
cd /var/azuracast
docker-compose logs redis
```

**Comment by istahilagi** [comment]
this is the log

redis_1                    | 17106:C 29 Sep 2021 16:39:45.030 # Write error saving DB on disk: No space left on device
redis_1                    | 1:M 29 Sep 2021 16:39:45.129 # Background saving error
redis_1                    | 1:M 29 Sep 2021 16:39:51.072 * 1 changes in 3600 seconds. Saving...
redis_1                    | 1:M 29 Sep 2021 16:39:51.072 * Background saving started by pid 17107
redis_1                    | 17107:C 29 Sep 2021 16:39:51.073 # Write error saving DB on disk: No space left on device
redis_1                    | 1:M 29 Sep 2021 16:39:51.173 # Background saving error
redis_1                    | 1:M 29 Sep 2021 16:39:57.099 * 1 changes in 3600 seconds. Saving...
redis_1                    | 1:M 29 Sep 2021 16:39:57.100 * Background saving started by pid 17108
redis_1                    | 17108:C 29 Sep 2021 16:39:57.101 # Write error saving DB on disk: No space left on device
redis_1                    | 1:M 29 Sep 2021 16:39:57.200 # Background saving error
redis_1                    | 1:M 29 Sep 2021 16:40:03.047 * 1 changes in 3600 seconds. Saving...
redis_1                    | 1:M 29 Sep 2021 16:40:03.048 * Background saving started by pid 17109
redis_1                    | 17109:C 29 Sep 2021 16:40:03.049 # Write error saving DB on disk: No space left on device
redis_1                    | 1:M 29 Sep 2021 16:40:03.148 # Background saving error
redis_1                    | 1:M 29 Sep 2021 16:40:04.057 # Short write while writing to the AOF file: (nwritten=1434, expected=43317)
redis_1                    | 1:M 29 Sep 2021 16:40:09.088 * 1 changes in 3600 seconds. Saving...
redis_1                    | 1:M 29 Sep 2021 16:40:09.089 * Background saving started by pid 17110
redis_1                    | 17110:C 29 Sep 2021 16:40:09.090 # Write error saving DB on disk: No space left on device
redis_1                    | 1:M 29 Sep 2021 16:40:09.190 # Background saving error
redis_1                    | 1:M 29 Sep 2021 16:40:15.026 * 1 changes in 3600 seconds. Saving...
redis_1                    | 1:M 29 Sep 2021 16:40:15.026 * Background saving started by pid 17111
redis_1                    | 17111:C 29 Sep 2021 16:40:15.028 # Write error saving DB on disk: No space left on device
redis_1                    | 1:M 29 Sep 2021 16:40:15.127 # Background saving error
redis_1                    | 1:M 29 Sep 2021 16:40:21.062 * 1 changes in 3600 seconds. Saving...
redis_1                    | 1:M 29 Sep 2021 16:40:21.062 * Background saving started by pid 17112

**Comment by Vaalyn** [comment]
> Write error saving DB on disk: No space left on device

Yeah, exactly what I suspected. Your server is out of disk space so you'll have to either clean up your server (deleting stuff that you don't need anymore) or upgrade your servers disk space.

**Comment by istahilagi** [comment]
ok sis, thanks for the hint, it worked now
