### ISSUE TITLE
Add ability to autoplay embedded player

### ISSUE THREAD

**Issue by SlvrEagle23** [AzuraCast/AzuraCast#464]

**Comment by amavarick** [comment]
If you add this capability, would you consider making it an optional configuration rather than enabling autoplay by default?

**Comment by SlvrEagle23** [comment]
@amavarick It absolutely will be something that's opt-in, i.e. with an added URL parameter at the end like `/autoplay`. The default will be not to autoplay.

**Comment by SlvrEagle23** [comment]
This feature has been added, exactly as specified above...add `/autoplay` to the end of an embedded URL or a public page URL to have the radio station automatically play when the user visits the page.

Use this feature sparingly!

**Comment by SlvrEagle23** [comment]
@rafaelholeva This is not something for me to correct. This is working as intended.

Chrome (and soon Firefox) on the desktop, along with most mobile browsers, have explicitly prevented autoplaying audio before the user interacts with the page, meaning that any attempt on my part to autoplay audio will simply be ignored by those browsers.

There are more sleazy, underhanded ways of circumventing this (such as using the first click anywhere on a page to trigger the playback) but I'm not in the business of blaring music unsuspectingly into people's ears. For applications like radio, the requirement that someone has to hit a "Play" button is a good thing.

**Comment by rafaelholeva** [comment]
@SlvrEagle23 Thank´s my friend! Very Good!

**Comment by kaweesi** [comment]
You can use custom js for public pages section and add this.

$(function() {
  $(".material-icons")[0].click();
});

**Comment by asdolo** [comment]
> $(function() {
> $(".material-icons")[0].click();
> });

No longer works. See https://developer.chrome.com/blog/autoplay/#media-engagement-index
