### ISSUE TITLE
Priority playlists don't work

### ISSUE THREAD

**Issue by KlolySoftwareFR** [AzuraCast/AzuraCast#4641]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.13.0

### What happened?

Hi,

I have a radio where they are many playlists played at the same time (5 playlists) with a different priority but this system doesn't work fine for me because the playlist named "A" with popular songs repeats them every 2 hours. How I Can change this value to repeat the songs of the playlists every 3 hours ?

**Comment by Abqehebter** [comment]
So for me it runs as it should (Latest Rolling Release)
I would recommend you to update to 0.14.1.
