### ISSUE TITLE
icecast.xml high cpu load

### ISSUE THREAD

**Issue by gosntvrdi** [AzuraCast/AzuraCast#4642]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #8b83d8a (2021-09-20 23:54)

### What happened?

i am having an unusually high cpu load on my 4 core server, average around 5.5 ever since i routed most of the traffic to it (around 2000 listeners currently). i see people  saying liquidsoap process is the most intensive cpu hogger, but i have an issue with icecast.xml taking majority of load, haven't seen anything about this process.

![image](https://user-images.githubusercontent.com/39313008/135595943-da5f5be0-14a8-4ed3-875b-9af438299117.png)

### Relevant log output

```shell
[2021-10-01  05:24:11] WARN slave/slave_startup process has 65536 max file descriptor limit
```

**Comment by SC2Mitch** [comment]
does this only happen with the two stations? and does this happen constantly, or occasionally?

**Comment by gosntvrdi** [comment]
There is only one station in Azura and it is happening constantly.

**Comment by SlvrEagle23** [comment]
@gosntvrdi That's very uncommon, to see Icecast as the source of that much load, but it's possible that the sheer number of listeners connecting to your stream is just overloading Icecast on that installation, or exceeding what your hardware is capable of. It may be advisable to look into setting up an AzuraRelay instance for your listeners to connect to to help distribute the load.

**Comment by gosntvrdi** [comment]
@SlvrEagle23 can you please help clarify how azurarelay handles the load distribution? if i set up an azurarelay instance, does main server automatically sends certain listeners to relay or do users connect to it only if clicking to a direct stream link provided by that instance?

**Comment by SlvrEagle23** [comment]
@gosntvrdi The load-balancing isn't automatic on AzuraCast's part; we just introduce the relays as an additional stream source that listeners can click; a custom player could certainly implement load-balancing if multiple stream sources are available.
