### ISSUE TITLE
Azuracast shows that radio is offline when it's not

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#4643]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.14.1

### What happened?

When accessing the dashboard, Azuracast shows that the broadcaster is offline when in fact it is not. I found that when not uploading the metadata it's shown as offline, even though it's streaming audio normally, I think the correct thing would be to show something like "no title" or something similar. I don't know if it's a small bug or not, I think the user might be mistaken and think his station is offline. Below is a screenshot that shows the station offline but it's actually not, it's just not sending the metadata.

![Capturar](https://user-images.githubusercontent.com/58113324/135618021-d1863b4f-7944-4452-89b4-689b1ad84330.JPG)

**Comment by SC2Mitch** [comment]
ongoing issue that we're well aware of, thanks for the ticket. we hope to resolve this in the next liquidsoap 2.0 update.
