### ISSUE TITLE
PHP Warning:  Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/azuracast/www/bin/uptime_wait on line 134

### ISSUE THREAD

**Issue by aarkkappler** [AzuraCast/AzuraCast#4644]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #64a1c9f (2021-10-01 7:41)

### What happened?

Redis does not work anymore

### Relevant log output

```shell
PHP Warning:  Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/azuracast/www/bin/uptime_wait on line 134
```

**Comment by SC2Mitch** [comment]
going to need a lot more information than it doesn't work anymore, can you explain what your trying to do, etc? need more details

**Comment by aarkkappler** [comment]
Thank you made an global update, and the situation is FIXED
