### ISSUE TITLE
How to disable "Azuracast is Live!" sound without adding a song, or disabling AutoDJ?

### ISSUE THREAD

**Issue by jelliedpizza** [AzuraCast/AzuraCast#4647]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#c4d3a50

### What happened?

I would like to use Azuracast as only an Icecast server with a frontend. It would be perfect for that, except that the AutoDJ needs to be turned on to stream and so it plays the "Azuracast is Live!" sound. When there is no ongoing stream, I would like it to say stream offline, without having to disable the AutoDJ, to make it easier to quickly start a stream.

Any suggestions?

**Comment by renatopinto89** [comment]
Just disable the auto-dj on the specific stations Profile.

**Comment by elpglenn1** [comment]
I don't think this is possible because of liquidsoap needing an infallible source of audio anytime it's running and I believe this track is in there to do just that or the system would fail. You could always replace the error jingle with a track of dead air and give it the title of "stream offline" or whatever you want.

**Comment by renatopinto89** [comment]
> I don't think this is possible because of liquidsoap needing an infallible source of audio anytime it's running and I believe this track is in there to do just that or the system would fail. You could always replace the error jingle with a track of dead air and give it the title of "stream offline" or whatever you want.

If you disable Auto-DJ on the stations profile, Liquid Soap is no longer part of it. I'm running some stations as standalone SHOUTcast and IceCast streams with only the front end using that method and it works perfectly.

**Comment by elpglenn1** [comment]
Yeah I'm not sure why he's specifically using the autoDJ but I guess if he turns it off and connects directly, problem solved.
