### ISSUE TITLE
bug schedule

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#4649]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #c4d3a50 (2021-10-03 0:18) • Docker • PHP 8.0

### What happened?

I noticed that the azuracast scheduling information wrongly shows the calculation for the next program and also shows a scheduling time that doesn't exist.
Example, you schedule a program from 05:00 to 07:00 and in the scheduling part of the home screen it shows 12:00 to 13:00 and it counts the hours until then wrong.
In previous versions it's ok.
In the last update it shows the error.
Even the test I did was on the example azuracast panel.

### Relevant log output

```shell
I noticed that the azuracast scheduling information wrongly shows the calculation for the next program and also shows a scheduling time that doesn't exist.
Example, you schedule a program from 05:00 to 07:00 and in the scheduling part of the home screen it shows 12:00 to 13:00 and it counts the hours until then wrong.
In previous versions it's ok.
In the last update it shows the error.
Even the test I did was on the example azuracast panel.

scheduling :https://prnt.sc/1uucip8

list: https://prnt.sc/1uucn89
```

**Comment by SlvrEagle23** [comment]
This was fixed in a recent Rolling Release update after a duplicate GitHub issue report.
