### ISSUE TITLE
Nginx port 80 is busy - already in use. 

### ISSUE THREAD

**Issue by kashifffff** [AzuraCast/AzuraCast#4651]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

installation issue-- showing port 80 is busy although it s not,

i uninstalled apachee
still same issue

Creating nginx_proxy   ... error

ERROR: for nginx_proxy  Cannot start service nginx_proxy: driver failed programming external connectivity on endpoint nginx_proxy (6a13c32b78500f80c53b9edee2711df9459365f8c9422ae8ca906ead2728ae7b): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use

ERROR: for nginx_proxy  Cannot start service nginx_proxy: driver failed programming external connectivity on endpoint nginx_proxy (6a13c32b78500f80c53b9edee2711df9459365f8c9422ae8ca906ead2728ae7b): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by mohmafia** [comment]
are you using nginx proxy manager in docker ? if so when i have time i can make you a guide on how to install it and change the ports after install ... note you will need portainer for that to work

**Comment by mohmafia** [comment]
Log in to portainer
stop the nginxproxymanager app
install azuracast as normal
make sure you already got a domain name pointing to your server ip
generate letsencrypt certs
when install is finished
go to your domain to log in to azura cast finish up the installation
when completely done
go back to portainer and refresh containers
click on nginx_proxy stack azuracast
scroll all the way down select nginxproxymanager_default
click Join network
scroll back up
click Duplicate/Edit
change ports host 80 to 85
and the host 443 to 8443
turn off always pull the image
then click on deploy the container
once that is done go back to containers and refresh
turn the nginxproxymanager app back on
note at this point you can't access azura cast
login to nginxproxymanager
click hosts
clcik add proxy host
at domain names put in your azuracast domain name same you used to install
scheme https forward hostname/ip put in your server ip the ip your domain points to
forward port 8443
turn on cache assets
turn on websockets support
then click on ssl
SSL Certificate select request a new certificate
and press save
now when you go to your domain azuracast will load
without any conflicts
![image](https://user-images.githubusercontent.com/61617857/140609809-967b87b4-78b0-4668-aae9-b4c5fe6124bf.png)
![image](https://user-images.githubusercontent.com/61617857/140609845-d593bfc9-99d2-418a-8c91-71a6daa22be9.png)
![image](https://user-images.githubusercontent.com/61617857/140609881-b7c9a8a0-b25a-434e-8bac-d882d2405628.png)
![image](https://user-images.githubusercontent.com/61617857/140609910-8ad4f76e-77d0-4a02-9470-f2445e057ae1.png)
![image](https://user-images.githubusercontent.com/61617857/140609962-65932d25-3ca1-4e74-a124-74c8aac4be31.png)
![image](https://user-images.githubusercontent.com/61617857/140610001-2af34c79-f128-4cfb-bfa8-49d6a54301f6.png)
![image](https://user-images.githubusercontent.com/61617857/140610030-3a05a492-51f0-4bae-8254-345fe1670d5d.png)
![image](https://user-images.githubusercontent.com/61617857/140610046-ff4c3643-35d6-4d85-828f-2b1e39b59142.png)
![image](https://user-images.githubusercontent.com/61617857/140610058-814432d3-b2c7-44d5-9581-9b45adb7bc25.png)
