### ISSUE TITLE
Stations Management

### ISSUE THREAD

**Issue by aarkkappler** [AzuraCast/AzuraCast#4656]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #c4d3a50 (2021-10-03 0:18) 

### What happened?

There is a Way to Get A list of Occupied Ports Per Stations and Available ports, thank you

**Comment by SlvrEagle23** [comment]
@aarkkappler There's currently no API way of doing this, but if you're building a plugin, the relevant line of code that could retrieve all used ports is here:

https://github.com/AzuraCast/AzuraCast/blob/main/src/Radio/Configuration.php#L334-L388
