### ISSUE TITLE
Most often Playlist are Broken Because the folders assigned to the playlists are no longer, IDKW

### ISSUE THREAD

**Issue by aarkkappler** [AzuraCast/AzuraCast#4657]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #c4d3a50 (2021-10-03 0:18) 

### What happened?

It happens very frequently, perhaps, after a stop / restart of the services that the folders assigned to the playlists are no longer, playlists are then found without associated muisques

**Comment by SlvrEagle23** [comment]
@aarkkappler So, walk me through the specific steps you're doing to cause this to happen.

You set a folder to assign to a playlist, then do what? Restart the services or rewrite the configuration?

That shouldn't trigger the removal of any playlist folders, but we can look into what may be causing that.

**Comment by aarkkappler** [comment]
Step it's always the same in Flysystem I assign a Folder to A Playlist

and sometime I can see the folder is no longer assigned I don't do more in this moment I am not doing this task so much and I don't manage assignation a lot 

I also can say when I assign files and not folders, it can happen that it does not work, I have to edit the file and go on playlist and assign it like this, that's works

But no idea why I lost the folder assignment
