### ISSUE TITLE
Slim Application Error when creating a station

### ISSUE THREAD

**Issue by taiBsu** [AzuraCast/AzuraCast#4663]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.14.1

### What happened?

When I'm trying to create a new station, I keep getting "Slim Application Error" messages right after trying to create it. Afterwards, the station exists in the dashboard (and is shown as offline stream), but when I'm trying to "manage" it, I keep getting the Slim Application error again. Same Slim Application Error appears when I try to delete the station. I have no idea what might be the reason. 

I tried deleting the cache and had a look at the log output, there's literally zero relevant log output when following any of the above steps. 
When trying to access the station log for the station which has been created but is not usable, I keep getting the same output for all log files:
`Error: App\Exception\NotFoundException at /var/azuracast/www/src/Controller/AbstractLogViewerController.php L27: Log file not found!`

How can I debug this issue further?
Thanks in advance.

**Comment by taiBsu** [comment]
Update: my installation seems to be completely faulty. I recently deleted 4 stations which don't appear in my station list anymore however accessing them directly via the mp3 link shows they're **still running**! how's that possible?

**Comment by SC2Mitch** [comment]
Have you restarted the installation and does the issue persist?

**Comment by taiBsu** [comment]
yes and yes, unfortunately it does.

09.10.2021 21:07:09 Mitch ***@***.***>:

**Comment by SC2Mitch** [comment]
We'll need to see a large chunk of Docker logs, so in your terminal go through `cd /var/azuracast` then `docker-compose logs -f` and provide us with a chunk of logs, this'll help us debug this further.

**Comment by taiBsu** [comment]
@SC2Mitch , have there, by any chance, been any updates so far? this is a real issue for me and I can't find a way to solve this on my own.
