### ISSUE TITLE
Listeners Report - Bug

### ISSUE THREAD

**Issue by arulvakku** [AzuraCast/AzuraCast#467]
Hi Silver Eagle, my hearty congratulations for this wonderful project to stream audio. It is very good. We do understand that it is not the perfect... But in the long run these issues could be solved. 
Here is one such issue just to your kind notice.

The list of listeners in the Report section, is not accurate. The screen shot would explain that better I believe.
![screenshot](https://user-images.githubusercontent.com/37052283/36951768-75948f5c-1fc4-11e8-9de2-dbf4d5502ce4.png)

**Comment by SlvrEagle23** [comment]
This is a known issue, which you can follow at #293. We're still waiting on updates from our upstream software providers to resolve the issue.
