### ISSUE TITLE
Weekdays

### ISSUE THREAD

**Issue by arulvakku** [AzuraCast/AzuraCast#468]
Weekdays when not marked did not play on any day of the week... Kindly check it.
![screenshot](https://user-images.githubusercontent.com/37052283/36957207-20742268-1ff0-11e8-9425-beeb1eb7ac75.png)

**Comment by SlvrEagle23** [comment]
@arulvakku I've made some significant changes to how scheduled playlists work in the system...can you check and let me know if this resolved your issue?

**Comment by SlvrEagle23** [comment]
I haven't heard any follow-up on this issue, so I don't know if the issue has been fixed or if further action is required on my end. If you don't mind, could you please update me on the status of this issue?

If I don't hear any updates for a while, I'll close the issue as resolved.
