### ISSUE TITLE
Port 8000 not loading

### ISSUE THREAD

**Issue by ivi-v** [AzuraCast/AzuraCast#4681]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.14.1

### What happened?

The AzuraCast embed player is not working because it links with the :8000 streaming, and it does not load. For example, in my case, https://radio.oniriaradio.com/radio/8000/radio.mp3 works but https://radio.oniriaradio.com:8000//radio.mp3 does not. And this last one is which the embed player uses. I tried updating the whole installation and rebooting both server and station, but none of them have worked. Which could be the problem? Thank you!

**Comment by LordHelmchen666** [comment]
Your port 8000 is closed. you can test with port checker https://www.google.com/search?client=firefox-b-e&q=port+checker
Open your port 8000 in your firewall!
