### ISSUE TITLE
Mail Client

### ISSUE THREAD

**Issue by aarkkappler** [AzuraCast/AzuraCast#4682]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #c6adbfa (2021-10-14 5:56)

### What happened?

No mail can be delivered
i tested the service in 587 and 465, it does not works, it works in other web app...
If you can help me 

### Relevant log output

```shell
no idea
```

**Comment by Abqehebter** [comment]
Have you tried other ports or other security types? SSL/TLS

**Comment by Abqehebter** [comment]
These are IMAP ports. SMTP ports are as follows:

25, 465 & 587

**Comment by nunotfc** [comment]
same problem, same log, exactly same situation.with port 465, tls checked or unchecked, no diference.  if unchecked, gives oauth2 error because google wants you to signin. i solved using a e-mail provider thath doesnt require ssl or tls to operate. but i would like to use gmail...

**Comment by Vaalyn** [comment]
Closing in favor of https://github.com/AzuraCast/AzuraCast/issues/4839

Will be tracking this problem over on that issue.
If you encounter this problem please follow the thread on the other GH issue.
