### ISSUE TITLE
limit max file

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#4688]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

369e7fe 

### What happened?

Hi
I have more than 1000 mp3 tracks and I have the message 
`[2021-10-16  06:10:09] WARN slave/slave_startup process has 65536 max file descriptor limit
`
Is it possible to increase the limit?

**Comment by Vaalyn** [comment]
This is not an error or anything weird and does not indicate an issue with AzuraCast.

See my response from yesterday on this discussion thread about the same message:
https://github.com/AzuraCast/AzuraCast/discussions/4685
