### ISSUE TITLE
Synchronization tasks do not work centOS 7

### ISSUE THREAD

**Issue by inetactief** [AzuraCast/AzuraCast#469]
We use the docker method and running on CentOS 7.
See below more information: 
v0.8.1-2018.02 Beta (Docker)
PHP 7.2.2-3+ubuntu16.04.1+deb.sury.org+1, SlimPHP 3

The Synchronization tasks do not run. We see this in the /admin page. 
I try to check the crontab but its empty.

**Comment by SlvrEagle23** [comment]
@inetactief This is a long-standing known issue with CentOS hosts, but I've finally made some headway in figuring out what's going on, and have replaced the regular cronjob runner with a new processor for scheduled tasks. This should help significantly with the problem. Try it out and let me know.

**Comment by inetactief** [comment]
Hi thank you for the fast fix. 
It works now only the nowplaying task do not run. He give error:
500
Call to a member function getName() on null
SHOUTcast.php : 53

**Comment by SlvrEagle23** [comment]
@inetactief Check to make sure you have a mount point on the station specified as the "default" mount point. You need one mount point to be specified as default for things to work correctly.

**Comment by inetactief** [comment]
We have update Azurcast to v0.9.1, #8f7d801 (2019-02-06 3:15) • Docker • PHP 7.2
But the Synchronization Tasks do not work anymore. I have before problems for the nowplaying.
When we running in the web the nowplaying is working but we get:

 NowPlaying adapter error: Request returned status 404: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found</h1> <p>The requested URL /status-json.xsl was not found on this server.</p> <p>Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.</p> </body></html>

Other taks are working but not automatic. I try to found out the log. But i can not find it.
