### ISSUE TITLE
clone playlist

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#4699]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #c4d3a50 (2021-10-03 0:18) • Docker • PHP 8.0

### What happened?

I have radio "a" and radio "b" already in operation at all programming, and I want to copy only the playlists from radio "a" to radio "b" without having to delete radio "b" and use the clone button station. Is there any cli command in php or shell that I can copy only the playlist from one station to another?

### Relevant log output

```shell
I have radio "a" and radio "b" already in operation at all programming, and I want to copy only the playlists from radio "a" to radio "b" without having to delete radio "b" and use the clone button station. Is there any cli command in php or shell that I can copy only the playlist from one station to another?
```

**Comment by SC2Mitch** [comment]
duplicate, check discussions
