### ISSUE TITLE
Start on port 9000

### ISSUE THREAD

**Issue by duohost** [AzuraCast/AzuraCast#470]
How can stream on port 9000 ?

**Comment by SlvrEagle23** [comment]
@duohost I have created a section on the support page specifically detailing instructions on how to use custom, non-standard ports for either the AzuraCast web site itself or your radio station streams. It should answer many of the questions you might have about this process:

https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#use-non-standard-ports
