### ISSUE TITLE
Last update broke my azuracast

### ISSUE THREAD

**Issue by Gregory-Hepicloud** [AzuraCast/AzuraCast#4703]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

![image](https://user-images.githubusercontent.com/4592618/137999831-2bab8960-cfb0-41e5-8f77-c8ed46460171.png)
after last update can not acces to panel no error on update and try to acces docker bash say this

and we have made backup in panel but not download its not saved on host server ??

**Comment by Gregory-Hepicloud** [comment]
Who redo update ? we have backup but is on panel interface i dont download it

**Comment by SC2Mitch** [comment]
You can grab the download from this path: `/var/lib/docker/volumes/azuracast_backup(s)`

**Comment by SC2Mitch** [comment]
thats the backup file, they're typically fairly large, if you have many stations or large amounts of media files.
