### ISSUE TITLE
405 Method Not Allowed The request method is not supported for the requested resource.

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#4706]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

Rolling Release #c4d3a50 (2021-10-03 0:18) • Docker • PHP 8.0

### What happened?

I updated my azuracast and now when I click any reset button on the panel, frontend or backend it gives error 405 Method Not Allowed
The request method is not supported for the requested resource.

Can someone help me ?

https://prnt.sc/1wsonq0

### Relevant log output

```shell
405 Method Not Allowed
The request method is not supported for the requested resource.
```

**Comment by SC2Mitch** [comment]
Where is this button your trying to press? I'm having issues replicating this.

**Comment by Marcioghiraldelli** [comment]
hello
image : https://prnt.sc/1wsv7ud
