### ISSUE TITLE
Using a Custom Certificate Not Work

### ISSUE THREAD

**Issue by gunsar** [AzuraCast/AzuraCast#4711]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

AzuraCast 0.14.1

### What happened?

I freshly installed the latest version, then setting **Using a Custom Certificate** according to the instructions in
**https://docs.azuracast.com/en/administration/ssl-and-lets-encrypt**
I entered the **Sectigo SSL** according to the instructions and settings in docker-compose.override.yml
But after checking SSL Checker several times it still detects **Let's Encrypt**
This makes me confused, please solve it, even though in the previous version **AzuraCast 0.13.0** it worked fine

### Relevant log output

root@stream:/var/azuracast# docker-compose logs nginx_proxy_letsencrypt
Attaching to nginx_proxy_letsencrypt
nginx_proxy_letsencrypt    | Info: running letsencrypt-nginx-proxy-companion version v2.0.2
nginx_proxy_letsencrypt    | Info: Custom Diffie-Hellman group found, generation skipped.
nginx_proxy_letsencrypt    | Reloading nginx proxy (....e552ab35874ff8fb952b5a99c919cbcc862d490761ba9afd9b7a29f0669....)...
nginx_proxy_letsencrypt    | 2021/10/21 08:44:43 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx_proxy_letsencrypt    | 2021/10/21 08:44:43 [notice] 55#55: signal process started
nginx_proxy_letsencrypt    | 2021/10/21 08:44:44 Generated '/app/letsencrypt_service_data' from 6 containers
nginx_proxy_letsencrypt    | 2021/10/21 08:44:44 Running '/app/signal_le_service'
nginx_proxy_letsencrypt    | 2021/10/21 08:44:44 Watching docker events
nginx_proxy_letsencrypt    | 2021/10/21 08:44:44 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
nginx_proxy_letsencrypt    | Reloading nginx proxy (....e552ab35874ff8fb952b5a99c919cbcc862d490761ba9afd9b7a29f0669....)...
nginx_proxy_letsencrypt    | 2021/10/21 08:44:45 Generated '/etc/nginx/conf.d/default.conf' from 6 containers
nginx_proxy_letsencrypt    | 2021/10/21 08:44:45 [notice] 81#81: signal process started

**Comment by gunsar** [comment]
> Check your Docker logs, it may give a reason as to whats going on.

no problem after open log for SSL, SSL runs smoothly either on streaming link or browser. what I'm complaining about is, SSL has been redirected from **docker-compose.override.yml** to Sectigo SSL, but after checking it still reads **Let's Encrypt**

**Comment by gunsar** [comment]
Please help

**Comment by gunsar** [comment]
Please help

**Comment by gunsar** [comment]
Please help

**Comment by SC2Mitch** [comment]
Will review in the morning.

**Comment by gunsar** [comment]
I don't understand, updating to the latest version v0.15.0 Stable, still custom SSL doesn't work, always stuck to Let's Encrypt, even though the docker-compose-overage settings are correct, and changing the jingle error.mp3 works fine, but Custom SSL doesn't work
