### ISSUE TITLE
Unable to add s3 storage location

### ISSUE THREAD

**Issue by chrisulloa** [AzuraCast/AzuraCast#4717]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

AzuraCast 0.14.1 

### What happened?

When I try to set my storage locations to an S3 bucket on the latest rolling release I get this error:

Symfony\Component\Serializer\Exception\MissingConstructorArgumentsException at /var/azuracast/www/vendor/symfony/serializer/Normalizer/AbstractNormalizer.php L402: Cannot create an instance of "App\Entity\StorageLocation" from serialized data because its constructor requires parameter "type" to be present.

When I try to overwrite the existing media storage location it accepts the form but then continues to keep the local setting. When I try to create a new storage location there is a 500 error returned. I do not see anything in the docker azuracast web logs.

![Screenshot from 2021-10-22 00-28-38](https://user-images.githubusercontent.com/11605892/138411931-5d9413d4-59ee-4cb3-9c09-cc0d633d2089.png)

**Comment by SlvrEagle23** [comment]
This should now be fixed as of the latest Rolling Release version. Thank you for the report!
