### ISSUE TITLE
Add ability of relay a streaming with Liquidsoap

### ISSUE THREAD

**Issue by oresot** [AzuraCast/AzuraCast#472]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Debian Wheezy

**Describe the issue in full detail, including screenshots if possible:**

Hi! 

We would like that Liquidsoap relays a different streaming until a DJ connects live. In the current config that Azura generates we just need to add the following:

```
# Input the stream,
# from an Icecast server or any other source
url = "http://streaming-url:8080/stream"
relay = mksafe(input.http(url))

radio = fallback(track_sensitive = false, [relay, dynamic, playlists, blank(duration=2.)])
```

Also, we can't add manually those lines, as when we restart Liquidsoap from Azuracast, the config gets rewritten.

If this is not an use case for the Liquidsoap server bundled with Azuracast, it would be nice to at least be able to use our own config.

Thanks!

**Comment by SlvrEagle23** [comment]
@oresot In your station profile, there's an option for "Advanced: Custom Liquidsoap Configuration", where you can add in lines to the configuration that will always be written every time AzuraCast writes to the LS config file.

In this case, since `radio` is the variable used for the managed radio and `live` is the variable used for the harbor input, you can do something like:

```
url = "http://streaming-url:8080/stream"
relay = mksafe(input.http(url))
radio = fallback(track_sensitive = false, [live, relay, blank(duration=2.)])
```

**Comment by oresot** [comment]
@SlvrEagle23 

Thank you, that is a great trick, anyway, to make it work I had to manually comment out the lines:

live = fallback(track_sensitive=false, [live, blank(duration=2.)])
radio = switch(id="live_switch", track_sensitive=false, [({!live_enabled}, live), ({true}, radio)])

Is it possible to disable or overwrite that from the custom settings field?

**Comment by SlvrEagle23** [comment]
@oresot You might be able to get around the issue of unused/overwritten variables by just adding

```
ignore(live)
ignore(radio)
```

to the top of the configuration.

This will probably not be as much of an issue once the changes outlined in #480 are implemented in the codebase, which will allow external URL relaying as a direct part of the AzuraCast system itself.
