### ISSUE TITLE
playlist

### ISSUE THREAD

**Issue by arulvakku** [AzuraCast/AzuraCast#473]
The playlist "Station Identification" is configured to play once every song... But it plays 2,3 or even 4 times continously... It sort of irritates the listeners. Can you please check it?
![screenshot](https://user-images.githubusercontent.com/37052283/37187225-9e2251b2-2306-11e8-816b-40e120c7f2f6.png)

**Comment by SlvrEagle23** [comment]
@arulvakku When you say "once every song", did you actually set it to play once every _two_ songs? If you set it to play once every one song, it'll basically play all the time, because it is following the rule.

**Comment by SlvrEagle23** [comment]
@arulvakku My apologies, as I may have misinterpreted your issue originally.

Out of curiosity, how long are the station identification / jingle songs? This may be a specific problem with songs that are around or under 15 seconds in length, as AzuraCast doesn't have enough time to determine the "next song" while it's playing.

Recent updates should have helped with this, but if they haven't, let me know.
