### ISSUE TITLE
New Public Player Not Playing Sound

### ISSUE THREAD

**Issue by countrymusicfy** [AzuraCast/AzuraCast#4746]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.14.1 Stable

### What happened?

Installed a new Docker, Azuracast server. Server's .mp3 stream on admin page plays music. Player on public page plays, but does not have sound.

**Comment by claudio2306** [comment]
How are they? 
Since yesterday that several radios created have no sound but reproduce. But it only happens on older accounts. The new ones work perfectly. Someone going through the same?

**Comment by mngfng** [comment]
I have the same problem, No audio on public page player.

**Comment by Vaalyn** [comment]
We can't really do anything on this issue here without either the browsers JS logs or just a link to a public player that is showing the issue so that we can check there directly.

I'd also appreciate it if you could tell us what browser, os, device you are using when it's not playing.

**Comment by Harthley** [comment]
Acabo de instalar la ultima version pero no se escucha el audio en pagina publica.
Aqui  os dejo el link [https://viveradio.ca/public/vive_candelaria](url)

Gracias por su apoyo!
