### ISSUE TITLE
How to restore from backup without changing Azuracast version.

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#4747]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

Hi,

When restoring AzuraCast from a backup,
The action will always install the latest version of AzuraCast. In production systems it is sometimes necessary to maintain an existing version. Usually the purpose of the backup and restore from backup is to restore the system to the last normal state.
Is there such an option with AzuraCast? 
Is it possible to restore from a backup without upgrading the version and keeping the AzuraCast version as it was at the time of the backup?

**Comment by eranwo** [comment]
I need to move Azuracast (with some previos version that works good) from old server to a new server and keep the configuration and version of Azuracast as it is.

If I make a full backup from the old server to the new server, Azuracast will also upgrade itself to the new version. How can I **prevent the upgrade** while restoring from a backup?

**Comment by SC2Mitch** [comment]
We don't allow backups to retain a specific version, mostly for security reasons as older versions may have security flaws we haven't located. Remaining on the most up to date stable branch allows for way better support than the old.

**Comment by eranwo** [comment]
Yes, I agree with you about security etc.
But I see  that there are so many issues with the new versions regarding LS (I very appreciate the developers' efforts to address any issue ) so I'm afraid that my system will not work properly after the upgrade, and there is no go back ..
Something to think about.

**Comment by SC2Mitch** [comment]
That's only on the rolling branch, our stable branch is the best suited for stability. We don't recommend rolling for production instances.
