### ISSUE TITLE
Enable Advanced Features and Use WebSockets checkbox activate/deactivate each other

### ISSUE THREAD

**Issue by zloysystem** [AzuraCast/AzuraCast#4749]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #0be5c9b (2021-10-31 1:00)

### What happened?

Good` day gentlemen!
how to enable these options separately?
![26HVBCkEES](https://user-images.githubusercontent.com/26243386/139579644-6954250a-2e85-4f67-a50f-d19f6115cc51.gif)
and also noticed a minor cosmetic
![tb6b0E2Y8S](https://user-images.githubusercontent.com/26243386/139579739-e580c114-a227-43a7-957c-d39bfbded67c.gif)

**Comment by Abqehebter** [comment]
I can confirm point (bug) one.
