### ISSUE TITLE
Episode editing doesn't seem to work

### ISSUE THREAD

**Issue by Enne2** [AzuraCast/AzuraCast#4752]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#d4f2deb

### What happened?

When I try to edit a Podcast episode the window seems to open the closes immediately. So it's impossible to me to edit an already created episode, I've to delete it and recreate it again.

**Comment by SC2Mitch** [comment]
Confirmed with latest rolling

**Comment by Enne2** [comment]
i've ijust nstalled a docker instance of the AzuraCast's latest commit on a test machine: same issue

Rolling Release #5b114a5 (2021-11-04 16:19) • Docker • PHP 8.0

**Comment by Enne2** [comment]
Works great now, thanks alot!
