### ISSUE TITLE
not able to manage anything on Azuracast GuzzleHttp\Psr7\Exception\MalformedUriException

### ISSUE THREAD

**Issue by aarkkappler** [AzuraCast/AzuraCast#4754]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #a06483b (2021-11-03 5:26)

### What happened?

Hi everyone, I am not able to manage anything on the station 

GuzzleHttp\Psr7\Exception\MalformedUriException at /var/azuracast/www/vendor/guzzlehttp/psr7/src/Uri.php L730: The path of a URI with an authority must start with a slash "/" or be empty

**Comment by marcelliotnet** [comment]
i am still having this issue on Rolling Release #52e70fe (2021-11-05 10:29)

**Comment by SlvrEagle23** [comment]
@marcelliotnet Is there any additional information you can provide? It seems this is likely caused by a faulty "base URL" on the application, but the latest fixes should've prevented that.

**Comment by aarkkappler** [comment]
It's always like this and now, finally the Icecast server does not works

**Comment by SlvrEagle23** [comment]
@aarkkappler We need more information to figure out where this error is being triggered. Is this on any page load at all?

**Comment by aarkkappler** [comment]
which information do you need, of course you can get a temporary access if you need

**Comment by SlvrEagle23** [comment]
@aarkkappler Let's try that option...DM me on Discord if you're available.

**Comment by Robdewild** [comment]
Hello all,
Still have that same issue here.
All pages show the url malfunktion error, but system seems to process the commands it‘s given.
Example: delete song from upcoming playlists.
I get the malfunction error, but when i refresh the page the song is gone in cuelist..

**Comment by Robdewild** [comment]
Did someone get any further with this issue?
Latest update:
Rolling Release #d09d36b (2021-11-25 0:40) • Docker • PHP 8.0 

It got worse with latest updates
Can‘t edit anything anymore.
Add files, requests, settings…
Doesn‘t respond, only the malformed url is keeping up constantly.
Any help is appreciated.
Logs don‘t show anything strange…

**Comment by Robdewild** [comment]
Ps :temporary access is no problem, if you need this.
Thanks👍

**Comment by Robdewild** [comment]
![5FE4542A-56E6-4663-8B83-E34DEA09E711](https://user-images.githubusercontent.com/88682313/143432870-9e66d4f5-3c5c-4c30-826f-1fc6a1d09112.png)

**Comment by Robdewild** [comment]
![2EA57CAF-CB1D-44C3-8897-50F291D57533](https://user-images.githubusercontent.com/88682313/143432963-3daf0b07-43a3-4ff3-bfe0-d118d534394c.png)

**Comment by SlvrEagle23** [comment]
@Robdewild That second error isn't related to the "Malformed URI" issue.

Are you only seeing this on specific pages, like media management? Or on every page?

**Comment by Robdewild** [comment]
You‘re right.
Second error occured when i want to add media, but tried with another file, and then i get the malformed url error, however, when i refresh the page, the file gets uploaded.
Probably first time there was something wrong with the mp3 file.
Uploading only sucessfull with ftp, on webpage file will not upload…
Malformed url error appears on every action on webpage.

**Comment by SlvrEagle23** [comment]
@Robdewild Try updating again; I've made some code changes that may help with this.

**Comment by Robdewild** [comment]
Tried the update, but same problem.
In this case a mediafile that i want to remove.
Malformed Error appears, and file is still there.

**Comment by Robdewild** [comment]
Must say, second try file is gone.
Still the error, but something happend👍

**Comment by Robdewild** [comment]
Tried a second time with another file on the mediapage, but doesn’t get deleted.
3 attempts, no affect.
Very weird….

**Comment by SlvrEagle23** [comment]
@Robdewild I'd probably need to actually look at your installation personally. The previous person never messaged me, so I haven't been able to see an example of this error in the wild.

**Comment by Robdewild** [comment]
No problem.
I made a testaccount.
You can have access as admin.
Where can i send the login information?

via 
Mobiel

**Comment by SlvrEagle23** [comment]
@Robdewild Figured it out with your account: your access-control-allow-origin settings were set to `'*'`, which didn't parse correctly and was causing the error you saw. The field's value should actually be just `*` by itself, with no quotes. Fixing that resolved the issue completely on your installation.

I've also updated the code in the latest release to handle this particular type of error gracefully.

**Comment by Robdewild** [comment]
Hello buster,

Very nice!
Thanks for the help.
Will check it out this evening.


via 
Mobiel

**Comment by Robdewild** [comment]
And ther malfunction errors are completely gone (as you said👍)
Thanks again.

**Comment by aarkkappler** [comment]
> @Robdewild Figured it out with your account: your access-control-allow-origin settings were set to `'*'`, which didn't parse correctly and was causing the error you saw. The field's value should actually be just `*` by itself, with no quotes. Fixing that resolved the issue completely on your installation.
> 
> I've also updated the code in the latest release to handle this particular type of error gracefully.

Yes ! sorry I planned to this, on this week-end, my apologize, I know that I am not really good on that type of scheduling
My apologize,

**Comment by aarkkappler** [comment]
I am happy if you detected the problem, I know that in this moment I am not enough focused on this project, you do an AMAZING job !

**Comment by aarkkappler** [comment]
> @aarkkappler Let's try that option...DM me on Discord if you're available.

let me know how I can contact you on discord
