### ISSUE TITLE
Editing station media cover art throws NoFileUploadedException

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#4755]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #2c84d55 (2021-11-03 21:07)

### What happened?

I noticed that as soon as I want to set a new cover image, AzuraCast always throws this error in my face, but still updates the cover image as it should:
![image](https://user-images.githubusercontent.com/42640247/140231947-67f01c33-80ab-473b-81ff-6ad3172cc89f.png)
![image](https://user-images.githubusercontent.com/42640247/140232114-75d61ca1-df64-4d69-957e-0a48da573dfd.png)

**Comment by SlvrEagle23** [comment]
Can't seem to reproduce this error locally. @Abqehebter what browser are you using?

**Comment by Abqehebter** [comment]
@SlvrEagle23 User-Agent: **Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 OPR/80.0.4170.61**

Short: Opera GX 80.0.4170.61

**Comment by paulcjkp** [comment]
Same issue here, Rolling Release #d4f2deb (2021-10-08 12:05), using Brave browser version 1.31.88, or Firefox version 94.0.1.  Doesn't seem to cause any issues, image uploads just fine.

**Comment by SC2Mitch** [comment]
Yep got it, when you `edit media` and change the Album Cover Art` it returns the error
Vid: 
![rYYyJVZkKW](https://user-images.githubusercontent.com/29955942/140654779-72330bef-4f99-4cb7-9f51-6a46a85812df.gif)
