### ISSUE TITLE
Enable Advanced Features not working

### ISSUE THREAD

**Issue by CyberMixRo** [AzuraCast/AzuraCast#4757]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #52e70fe (2021-11-05 10:29)

### What happened?

Enable Advanced Features option is not working, have no effect, remain activated all the time even if you disable for limited user, they have access at all advanced option.

Option disabled:
![image](https://user-images.githubusercontent.com/59975870/140515037-40bb1c15-40c5-4bcd-8529-2d84cd45a35a.png)

User preview:
![image](https://user-images.githubusercontent.com/59975870/140515240-b401d4ee-b26e-41ee-8e2f-5f07b47aa8b5.png)

Please fix this issue as soon is possible. Thanks

**Comment by Abqehebter** [comment]
Seems since the commit https://github.com/AzuraCast/AzuraCast/commit/7dd2f90d1bd7e121c6c64ba0819084f4666d0aa7 to be "fixed".

**Comment by SC2Mitch** [comment]
Should be fixed in the latest rolling, let us know if it's not
