### ISSUE TITLE
restore in synology fails

### ISSUE THREAD

**Issue by cloudbolwell** [AzuraCast/AzuraCast#4758]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

I cant restore a back up to azuracast via the method via the website as its trying to locate the backup in the /var instead of the correct destination iv specified it gets half way through the restore when it gives the error permission denied even the the commands started with sudo is there something im missing

**Comment by Abqehebter** [comment]
Is that exactly how you enter the restore command?

`./docker.sh restore automatic_backup_20211108_030302.zip`

I have loaded the backup directly into the /home folder, so it went quite well.

**Comment by cloudbolwell** [comment]
Yes that's exactly how I did it over and over again but just kept getting a permission error are you running DSM7 just wondering if that's causing the issue I just gave up in the end and started from scratch which is a drag but couldn't get passed that error

**Comment by Abqehebter** [comment]
Have you already tried to give the backup the "permissions"?

`chmod 777 /home/automatic_backup_20211108_030302.zip`

Sounds stupid but you have to go through everything... 😅

**Comment by SC2Mitch** [comment]
@sufyanshafiq was this resolved?

**Comment by sufyanshafiq** [comment]
> @sufyanshafiq was this resolved?

Yes, use backup file name without extension.

**Comment by SC2Mitch** [comment]
> > @sufyanshafiq was this resolved?
> 
> Yes, use backup file name without extension.

thanks ill get a pull sorted to rectify this. 

closed for now

**Comment by cloudbolwell** [comment]
When trying to restore I get the error no backup in the installation directory /var/azuracast as the installation directory is different in synology /volume1/docker/azuracast it's still trying to look for a backup in /var/azuracast even though iv stipulated /volume1/docker/azuracast fails with error code 1 and the message no back found in /var/azuracast
