### ISSUE TITLE
How to install azuracast on a different port

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#476]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Centos 7

**Describe the issue in full detail, including screenshots if possible:**

How can install azuracast with docker on centos 7 vps which is already running vestacp on.
So i want azuracast to be running on a different port then 80 and 8080.

**Comment by SlvrEagle23** [comment]
@surihost On your local `docker-compose.yml` file, modify the following lines:

https://github.com/AzuraCast/AzuraCast/blob/84c5d1c8b02ceb762b83b3d4167075e3d4e7d050/docker-compose.sample.yml#L36-L37

Change the port number before the first half to the new port you want to use, and leave the second number the same. I.e. change "80:80" to "7000:80" if you want.

**Comment by SlvrEagle23** [comment]
@surihost Since I get this question rather often, I have created a new section in the Support.md file with detailed instructions on how to use nonstandard ports for web or radio purposes:
https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#use-non-standard-ports
