### ISSUE TITLE
LiquidSoap Not Start

### ISSUE THREAD

**Issue by enigmathion** [AzuraCast/AzuraCast#4761]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #4cbb9dd (2021-11-08 10:29) • Docker • PHP 8.0

### What happened?

Good morning, a few moments ago I updated the Rolling Release installation to the latest version and from there there are two instances that there is no way to start working. LiquiSoap stops and even if it starts, it first throws this error:

App \ Exception \ Supervisor \ AlreadyRunningException at /var/azuracast/www/src/Radio/AbstractAdapter.php L242: Liquidsoap cannot start
It is already in operation.

Other times it indicates that it is working but the result is always "Stream Offline" and I have already tried everything, update again, restart server, restart liquisoap, etc!

What could be failing? Thank you!

**Comment by Vaalyn** [comment]
Please take a look at the Liquidsoap logs and post them here, maybe LS is crashing and automatically restarting (then crashing again) which should be visible in the logs.

**Comment by enigmathion** [comment]
These are the liquidsoap logs that show me two stations out of the five there are, the rest are doing fine!

has no argument labeled "max"!
At /var/azuracast/stations/radio80sa.com/config/liquidsoap.liq, line 34, char 50-53:
Error 6: Cannot apply that parameter because the function at /var/azuracast/stations/radio80sa.com/config/liquidsoap.liq, line 34, char 35-46

At /var/azuracast/stations/retroclassicradio/config/liquidsoap.liq, line 32, char 36-39:
Error 6: Cannot apply that parameter because the function at /var/azuracast/stations/retroclassicradio/config/liquidsoap.liq, line 32, char 21-32
has no argument labeled **"max"**

**Comment by ivellios1988** [comment]
So there seems to be something messed up with your Liquidsoap configuration. Can you post here the contents of the function mentioned in your logs?

**Comment by enigmathion** [comment]
How did I get there?

**Comment by enigmathion** [comment]
init.daemon.set(false)
init.daemon.pidfile.path.set("/var/azuracast/stations/radio80sa.com/config/liquidsoap.pid")
log.stdout.set(true)
log.file.set(false)
settings.server.telnet.set(true)
settings.server.telnet.bind_addr.set("0.0.0.0")
settings.server.telnet.port.set(8124)
settings.harbor.bind_addrs.set(["0.0.0.0"])

settings.tag.encodings.set(["UTF-8","ISO-8859-1"])
settings.encoder.metadata.export.set(["artist","title","album","song"])

setenv("TZ", "America/Argentina/Buenos_Aires")

azuracast_api_auth = ref("60ce7c88720f46ed9dca623395d91cb5de58ec5051d53be51ed1b8c77d237799a35b1fd3cb709ffb89296923f6cac1e25742")
ignore(azuracast_api_auth)

autodj_is_loading = ref(true)
ignore(autodj_is_loading)

autodj_ping_attempts = ref(0)
ignore(autodj_ping_attempts)


playlist_movidos = playlist(id="playlist_movidos",mode="randomize",reload_mode="watch","/var/azuracast/stations/radio80sa.com/playlists/playlist_movidos.m3u")
playlist_movidos = cue_cut(id="cue_playlist_movidos", playlist_movidos)

playlist_nacionales = playlist(id="playlist_nacionales",mode="randomize",reload_mode="watch","/var/azuracast/stations/radio80sa.com/playlists/playlist_nacionales.m3u")
playlist_nacionales = cue_cut(id="cue_playlist_nacionales", playlist_nacionales)

playlist_san_marcos_radio = mksafe(input.http(max=10., "https://sp2.servidorrprivado.com/8052/stream"))
playlist_san_marcos_radio = cue_cut(id="cue_playlist_san_marcos_radio", playlist_san_marcos_radio)

playlist_artistica = playlist(id="playlist_artistica",mode="random",reload_mode="watch","/var/azuracast/stations/radio80sa.com/playlists/playlist_artistica.m3u")
playlist_artistica = cue_cut(id="cue_playlist_artistica", playlist_artistica)

playlist_tandero = playlist(id="playlist_tandero",mode="randomize",reload_mode="watch","/var/azuracast/stations/radio80sa.com/playlists/playlist_tandero.m3u")
playlist_tandero = cue_cut(id="cue_playlist_tandero", playlist_tandero)

# Standard Playlists
radio = random(id="standard_playlists", weights=[3, 3], [playlist_movidos, playlist_nacionales])

# Standard Schedule Switches

radio = switch(id="schedule_switch", track_sensitive=true, [ ({ (6w) and 15h0m-17h0m }, playlist_san_marcos_radio), ({true}, radio) ])

# Once per x Songs Playlists
radio = rotate(weights=[1,2], [playlist_artistica, radio])
radio = rotate(weights=[1,10], [playlist_tandero, radio])

# AutoDJ Next Song Script
def autodj_next_song() =
    uri = list.hd(process.read.lines(env=[("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/20/nextsong --form api_auth="$API_AUTH"'), default="")
    log("AzuraCast Raw Response: #{uri}")

    if uri == "" or string.match(pattern="Error", uri) then
        null()
    else
        r = request.create(uri)
        if request.resolve(r) then
            r
        else
            null()
       end
    end
end

# Delayed ping for AutoDJ Next Song
def wait_for_next_song(autodj)
    autodj_ping_attempts := !autodj_ping_attempts + 1
    delay = ref(0.5)

    if source.is_ready(!autodj) then
        log("AutoDJ is ready!")

        autodj_is_loading := false
        delay := -1.0
    elsif !autodj_ping_attempts > 200 then
        log("AutoDJ could not be initialized within the specified timeout.")

        autodj_is_loading := false
        delay := -1.0
    end

    !delay
end

dynamic = request.dynamic(id="next_song", timeout=20., retry_delay=2., autodj_next_song)
dynamic = cue_cut(id="cue_next_song", dynamic)

dynamic_startup = fallback(
    id = "dynamic_startup",
    track_sensitive = false,
    [
        dynamic,
        source.available(
            blank(id = "autodj_startup_blank", duration = 120.),
            predicate.activates({!autodj_is_loading})
        )
    ]
)
radio = fallback(id="autodj_fallback", track_sensitive = true, [dynamic_startup, radio])

ref_dynamic = ref(dynamic);
thread.run.recurrent(delay=0.25, { wait_for_next_song(ref_dynamic) })

requests = request.queue(id="requests")
requests = cue_cut(id="cue_requests", requests)

radio = fallback(id="requests_fallback", track_sensitive = true, [requests, radio])
add_skip_command(radio)


radio = crossfade(smart=true, duration=4.50, fade_out=3.00, fade_in=3.00, radio)

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

# Apply amplification metadata (if supplied)
radio = amplify(override="liq_amplify", 1., radio)

radio = fallback(id="safe_fallback", track_sensitive = false, [radio, single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")])


# Send metadata changes back to AzuraCast
def metadata_updated(m) =
    def f() =
        if (m["song_id"] != "") then
            ret = list.hd(process.read.lines(env=[("SONG", m["song_id"]), ("MEDIA", m["media_id"]), ("PLAYLIST", m["playlist_id"]), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/20/feedback --form song="$SONG" --form media="$MEDIA" --form playlist="$PLAYLIST" --form api_auth="$API_AUTH"'), default="")
            log("AzuraCast Feedback Response: #{ret}")
        end
        (-1.)
    end

    thread.run.recurrent(fast=false, delay=0., f)
end

radio.on_metadata(metadata_updated)

# Local Broadcasts
output.icecast(%fdkaac(channels=2, samplerate=44100, bitrate=48, afterburner=false, aot="mpeg4_he_aac_v2", sbr_mode=true), id="local_1", host = "127.0.0.1", port = 8120, password = "MLxGyqjp", mount = "/radio.mp3", name = "Radio80sa", description = "", genre = "", public = false, encoding = "UTF-8", radio)

# Remote Relays

**Comment by enigmathion** [comment]
I guess you ask me this!

**Comment by enigmathion** [comment]
# WARNING! This file is automatically generated by AzuraCast.
# Do not update it directly!


init.daemon.set(false)
init.daemon.pidfile.path.set("/var/azuracast/stations/radio80sa.com/config/liquidsoap.pid")
log.stdout.set(true)
log.file.set(false)
settings.server.telnet.set(true)
settings.server.telnet.bind_addr.set("0.0.0.0")
settings.server.telnet.port.set(8124)
settings.harbor.bind_addrs.set(["0.0.0.0"])

settings.tag.encodings.set(["UTF-8","ISO-8859-1"])
settings.encoder.metadata.export.set(["artist","title","album","song"])

setenv("TZ", "America/Argentina/Buenos_Aires")

azuracast_api_auth = ref("(PASSWORD)")
ignore(azuracast_api_auth)

autodj_is_loading = ref(true)
ignore(autodj_is_loading)

autodj_ping_attempts = ref(0)
ignore(autodj_ping_attempts)

playlist_movidos = playlist(id="playlist_movidos",mode="randomize",reload_mode="watch","/var/azuracast/stations/radio80sa.com/playlists/playlist_movidos.m3u")
playlist_movidos = cue_cut(id="cue_playlist_movidos", playlist_movidos)

playlist_nacionales = playlist(id="playlist_nacionales",mode="randomize",reload_mode="watch","/var/azuracast/stations/radio80sa.com/playlists/playlist_nacionales.m3u")
playlist_nacionales = cue_cut(id="cue_playlist_nacionales", playlist_nacionales)

playlist_san_marcos_radio = mksafe(input.http(max=10., "https://sp2.servidorrprivado.com/8052/stream"))
playlist_san_marcos_radio = cue_cut(id="cue_playlist_san_marcos_radio", playlist_san_marcos_radio)

playlist_artistica = playlist(id="playlist_artistica",mode="random",reload_mode="watch","/var/azuracast/stations/radio80sa.com/playlists/playlist_artistica.m3u")
playlist_artistica = cue_cut(id="cue_playlist_artistica", playlist_artistica)

playlist_tandero = playlist(id="playlist_tandero",mode="randomize",reload_mode="watch","/var/azuracast/stations/radio80sa.com/playlists/playlist_tandero.m3u")
playlist_tandero = cue_cut(id="cue_playlist_tandero", playlist_tandero)

# Standard Playlists
radio = random(id="standard_playlists", weights=[3, 3], [playlist_movidos, playlist_nacionales])

# Standard Schedule Switches

radio = switch(id="schedule_switch", track_sensitive=true, [ ({ (6w) and 15h0m-17h0m }, playlist_san_marcos_radio), ({true}, radio) ])

# Once per x Songs Playlists
radio = rotate(weights=[1,2], [playlist_artistica, radio])
radio = rotate(weights=[1,10], [playlist_tandero, radio])

# AutoDJ Next Song Script
def autodj_next_song() =
    uri = list.hd(process.read.lines(env=[("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/20/nextsong --form api_auth="$API_AUTH"'), default="")
    log("AzuraCast Raw Response: #{uri}")

    if uri == "" or string.match(pattern="Error", uri) then
        null()
    else
        r = request.create(uri)
        if request.resolve(r) then
            r
        else
            null()
       end
    end
end

# Delayed ping for AutoDJ Next Song
def wait_for_next_song(autodj)
    autodj_ping_attempts := !autodj_ping_attempts + 1
    delay = ref(0.5)

    if source.is_ready(!autodj) then
        log("AutoDJ is ready!")

        autodj_is_loading := false
        delay := -1.0
    elsif !autodj_ping_attempts > 200 then
        log("AutoDJ could not be initialized within the specified timeout.")

        autodj_is_loading := false
        delay := -1.0
    end

    !delay
end

dynamic = request.dynamic(id="next_song", timeout=20., retry_delay=2., autodj_next_song)
dynamic = cue_cut(id="cue_next_song", dynamic)

dynamic_startup = fallback(
    id = "dynamic_startup",
    track_sensitive = false,
    [
        dynamic,
        source.available(
            blank(id = "autodj_startup_blank", duration = 120.),
            predicate.activates({!autodj_is_loading})
        )
    ]
)
radio = fallback(id="autodj_fallback", track_sensitive = true, [dynamic_startup, radio])

ref_dynamic = ref(dynamic);
thread.run.recurrent(delay=0.25, { wait_for_next_song(ref_dynamic) })

requests = request.queue(id="requests")
requests = cue_cut(id="cue_requests", requests)

radio = fallback(id="requests_fallback", track_sensitive = true, [requests, radio])
add_skip_command(radio)

radio = crossfade(smart=true, duration=4.50, fade_out=3.00, fade_in=3.00, radio)

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

# Apply amplification metadata (if supplied)
radio = amplify(override="liq_amplify", 1., radio)

radio = fallback(id="safe_fallback", track_sensitive = false, [radio, single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")])

# Send metadata changes back to AzuraCast
def metadata_updated(m) =
    def f() =
        if (m["song_id"] != "") then
            ret = list.hd(process.read.lines(env=[("SONG", m["song_id"]), ("MEDIA", m["media_id"]), ("PLAYLIST", m["playlist_id"]), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/20/feedback --form song="$SONG" --form media="$MEDIA" --form playlist="$PLAYLIST" --form api_auth="$API_AUTH"'), default="")
            log("AzuraCast Feedback Response: #{ret}")
        end
        (-1.)
    end

    thread.run.recurrent(fast=false, delay=0., f)
end

radio.on_metadata(metadata_updated)

# Local Broadcasts
output.icecast(%fdkaac(channels=2, samplerate=44100, bitrate=48, afterburner=false, aot="mpeg4_he_aac_v2", sbr_mode=true), id="local_1", host = "127.0.0.1", port = 8120, password = "(PASSWORD)", mount = "/radio.mp3", name = "Radio80sa", description = "", genre = "", public = false, encoding = "UTF-8", radio)

# Remote Relays

**Comment by Abqehebter** [comment]
Seems like this code section is causing problems here:
```
playlist_san_marcos_radio = mksafe(input.http(max=10., "https://sp2.servidorrprivado.com/8052/stream"))
playlist_san_marcos_radio = cue_cut(id="cue_playlist_san_marcos_radio", playlist_san_marcos_radio)
```
Can you temporarily disable the "san_marcos_radio" playlist?

**Comment by Abqehebter** [comment]
Seems so. At least I have the error as soon as I want to create a remote URL:
```
At /var/azuracast/stations/test/config/liquidsoap.liq, line 31, char 40-43:
Error 6: Cannot apply that parameter because the function at /var/azuracast/stations/test/config/liquidsoap.liq, line 31, char 25-36
has no argument labeled "max"!
```

**Comment by enigmathion** [comment]
Ok, so it will be a matter of waiting for an update with the corrected piece of code!

**Comment by Vaalyn** [comment]
Thank you for the report, I'll get this part of the LS config generator updated shortly and will notify you here when it's fixed. I have missed this while adapting the AC code for LS 2.

**Comment by Vaalyn** [comment]
The updated code is currently built into the Docker image. When this [action](https://github.com/AzuraCast/AzuraCast/actions/runs/1439961811) is done it should be available. Give it like 15-20 minutes and then you should be able to update to it.
