### ISSUE TITLE
Upcoming Song Queue in LS 2

### ISSUE THREAD

**Issue by YosefAdPro** [AzuraCast/AzuraCast#4765]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #4cbb9dd (2021-11-08 10:29) • Docker • PHP 8.0

### What happened?

If you delete a song from the Upcoming Song Queue, or clear the list, LS does not respect the queue and the next song is randomly selected.

**Comment by Vaalyn** [comment]
Hey, since LS 2 the Liquidsoap process prefetches 1 song from the AzuraCast next song API in order to keep an internal "buffer" of what to play next. This helps prevent some other issues we had before. When you clear the upcoming song queue you only clear what's in the AzuraCast queue not the LS processes internal prefetch queue. You will have 1 song currently playing, 1 song prefetched in LS that will be played next and then comes the AzuraCast upcoming song queue.

**Comment by YosefAdPro** [comment]
got it.
Thank you!

**Comment by YosefAdPro** [comment]
Hi,

I think because of the buffer, playlist scheduling is played significantly late.
The buffer may not be calculated in the queue build?

**Comment by Vaalyn** [comment]
Will need to investigate, haven't noticed a delay in the scheduling yet myself.

**Comment by YosefAdPro** [comment]
```
2021/11/10 18:59:19 [playlist_evry_hour:3] Prepared "/var/azuracast/stations/kols/media/maavar/kolsmaavar1.mp3" (RID 8).
2021/11/10 19:14:54 [cue_playlist_evry_hour:3] Cueing in.
```

![image](https://user-images.githubusercontent.com/11810187/141164383-2f7d3fd4-4af2-4569-bfaf-b3358436c56a.png)

**Comment by SlvrEagle23** [comment]
This has been fixed in the latest Rolling Release, which now correctly uses the expected _play_ time of the track instead of the expected _cue_ time, now that the two can differ significantly because of Liquidsoap's internal queue buffer.

**Comment by YosefAdPro** [comment]
@SlvrEagle23 Sorry I'm opening this issue again, maybe for you it works as expected.

But the timing is still late. And I think it's because the song that's in the buffer was not calculated  so the delay happens.

![image](https://user-images.githubusercontent.com/11810187/144045235-d0def22a-2779-4106-a3a6-2ce183021ff4.png)

The song marked in yellow came in at 2:01 instead of the song in red.
The song in red is scheduled to play in the 59th minute.

**Comment by YosefAdPro** [comment]
@SlvrEagle23 The latest rolling version the playlist scheduler plays in time. Thank you.
