### ISSUE TITLE
Failed upgrade using Docker on Debian Jessie

### ISSUE THREAD

**Issue by andrew867** [AzuraCast/AzuraCast#477]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Debian Jessie 8.9

**Describe the issue in full detail, including screenshots if possible:**

Attempted upgrade using Docker upgrade instructions, seems like Icecast is starting but the AzuraCast frontend is returning this error:

```
500
database not found: stations
ResultSet.php : 46
```

What can I do to fix this without loosing the database or old configuration. I initially tried to run the backup script but it looks like it errored out.

**Comment by SlvrEagle23** [comment]
@andrew867 It seems InfluxDB (the time-series management tool we use to keep long-term statistics on station listenership) just pushed out an update to move Docker containers from 1.4 to 1.5, and this isn't playing nicely with our automated update/installer tools.

On your local `docker-compose.yml`, follow the same steps I did in this commit to lock the version to the previous version of InfluxDB: https://github.com/AzuraCast/AzuraCast/commit/84c5d1c8b02ceb762b83b3d4167075e3d4e7d050

Then try re-running the update process. Let me know if this helps.

**Comment by andrew867** [comment]
Still seems to be giving the same error message, something may have happened to the docker-compose file that was created by the initial installer. After upgrading it was gone so I used a copy sample on the master branch. If the MySQL password is set by the installer then maybe the frontend can't connect to the database? Is there a way I can connect to MySQL through docker to verify the password in the file is correct?

**Comment by SlvrEagle23** [comment]
@andrew867 Wait, what method did you use to do the installation? `./install.sh` or `docker-compose run --rm cli azuracast_install`?

The former is for traditional ("baremetal") installations on Ubuntu only. The latter won't set a password other than the one you have in your environment variables in `docker-compose.yml`.

**Comment by andrew867** [comment]
Looks like I used `./docker-install.sh`, but after I put the `docker-compose.yml` back I used `docker-compose run --rm cli azuracast_install`. The last time I touched this server was about four/five months ago after the Icecast-kh iOS 11 patch was done.

**Comment by SlvrEagle23** [comment]
@andrew867 A lot of changes have been made to how we do Docker-based installations. These days, you only need the single `docker-compose.yml` file on your disk, instead of the whole AzuraCast installation. There's a command in the readme that will let you pull down the latest version into the right place:

```
curl -L https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker-compose.sample.yml > docker-compose.yml
```

Your data should still be stored in the Docker volumes, but it appears your InfluxDB container's causing a little trouble. Run the new update commands (also from the readme) and see if it can snap itself back into place.

**Comment by andrew867** [comment]
Looks like it worked! :D Thanks for all your help and the great software!

**Comment by SlvrEagle23** [comment]
@andrew867 Happy to help! Let me know if you run into any other issues.
