### ISSUE TITLE
How to switch the port AzuraCast uses for its own traffic to an unused one

### ISSUE THREAD

**Issue by dekakast** [AzuraCast/AzuraCast#4773]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

.14.1

### What happened?

I tried installing Azuracast with DirectAdmin but got error below. How do I switch Azuracast to port 8080?

ERROR: for nginx_proxy Cannot start service nginx_proxy: driver failed
programming external connectivity on endpoint nginx_proxy
(3f1dcfc506e0e5dd7c242da556ddd9a4a1cd24cd8762cc11c6ae17696fa0d51a): Error
starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in
use

From Azuracast documentation:  "Common services that listen on ports 80 and 443 include web servers like Apache and nginx. One common port to use if you still need these services to remain online alongside AzuraCast is port 8080, which we deliberately leave open due to its common usage with other software."

**Comment by Vaalyn** [comment]
You can follow this guide from our documentation on how to use non-standard ports: https://docs.azuracast.com/en/administration/docker#using-non-standard-ports
