### ISSUE TITLE
miss storage limit per station and not remove station data

### ISSUE THREAD

**Issue by inetactief** [AzuraCast/AzuraCast#4776]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#ec88ed7 (2021-07-26 4:40) • Docker • PHP 8.0

### What happened?

I miss the storage limit per radio station. I did and paid for this one.

And when I remove a station the disk space remains unchanged. 

I know I'm not running the latest version. But I wonder if that solves this or is something else

**Comment by SC2Mitch** [comment]
When you mean paid, who did you pay? If you paid through our premium support, reach out via that method to get this sorted out.

**Comment by SlvrEagle23** [comment]
@inetactief There is still per-storage-location storage quotas; you just manage them via the Storage Locations administration instead of the station administration.

**Comment by inetactief** [comment]
Thanks, i found it.
