### ISSUE TITLE
Generic_song.jpg logo

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#478]
Hello,
Would it be possible to change the basic logo with our own logo?
Maybe add it to the page "Custom Branding"
Thank you
![generic_song](https://user-images.githubusercontent.com/379099/37245081-35d2d756-2493-11e8-8ffc-aced62f37464.jpg)

**Comment by SlvrEagle23** [comment]
@ckeurk It's possible, though in the interest of avoiding having a directory that serves user-uploaded content directly (which is a security risk that I want to avoid if I can help it), I'd rather have the field be a URL that you can enter for an alternate image path.

**Comment by SlvrEagle23** [comment]
@ckeurk Done! Try it out!
