### ISSUE TITLE
aac streams not playing in stream urls.

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#4787]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

72b4329 (2021-11-13 14:08) • Docker • PHP 8.0

### What happened?

hello,
i would like to report a long bug, not from now.
i know that it might be a duplicate, but i will delete the oter ishue.
i have more information.
i'm atempting to play this url in playlist:
https://audio.livemix.com.br/livemix
azuracast wont play this.
i think azuracast wont play aac streams because all aac streams i try to play, doesnt work.
i think also can be problem of azuracast playing encrypted or wrong headers url.
in liquidsoap i have cant conect to https://audio.livemix.com.br/livemix:443 conection timed out.
but this player is working, i can play it in vlc, etc.
it doesnt appen just with this radio.
if you need some more logs, i'm available..

**Comment by ivellios1988** [comment]
Have you tried switching to a non-SSL link? http://audio.livemix.com.br/livemix

**Comment by nunotfc** [comment]
doesnt work.
i think that the radio is with forse redirection
but i think ssl is not the problem because this stream works and have ssl too.
https://stream1.thepuremix.net/nexusdance.mp3
probably the problem is about aac streams or about headers. if you open the link i provided livemix with chrome it asks you to download, not play with built in player, and keeps downloading a infinite file. i contacted the radio and they told me that they will not change headers. So i think azuracast or doesnt play aac streams, or hare not prepared to deal with link with atachment headers instead of content type

**Comment by gunsar** [comment]
explain the steps taken for this costume, so that the error can be seen

**Comment by nunotfc** [comment]
i already explained! :D
I just make a url scheduled playlist, 00 to 07am with the url:
https://audio.livemix.com.br/livemix
buffer doesnt mathers i tested with all options. and just doesnt work, in log says cant conect to https://audio.livemix.com.br/livemix:443 conection timed out or so. tried with http only, but same error.
but is not just with this link.

**Comment by nunotfc** [comment]
solved last rolling release. some oter fix solved this too.
