### ISSUE TITLE
API returns 403 error when trying to play songs in the medialibrary from webbrowser as Administrator

### ISSUE THREAD

**Issue by hcbd** [AzuraCast/AzuraCast#4788]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #71251aa (2021-11-14 18:14) • Ansible • PHP 8.0 

### What happened?

Reproduce / Bug description:
Hitting the playbutton on a .mp3 file in the radiostation's medialibrary from the webinterface does not play the file in question.
Checking the XHR request in the browser: the API is returning a 403 error whilest i am an administrator user within the azuracast

xhr request: 
```
GET /api/station/3/files/play/278 HTTP/1.1
Host: redacted
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0
Accept: audio/webm,audio/ogg,audio/wav,audio/*;q=0.9,application/ogg;q=0.7,video/*;q=0.6,*/*;q=0.5
Accept-Language: nl,en-US;q=0.7,en;q=0.3
Referer: https://redaced/station/3/files
Range: bytes=0-
DNT: 1
Connection: keep-alive
Cookie: app_session=***********e403a97e89a5f53fe9a26
Sec-Fetch-Dest: audio
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
```

Response (no body)
```
HTTP/1.1 403 Forbidden
Server: nginx
Date: Mon, 15 Nov 2021 12:20:16 GMT
Content-Type: text/html
Content-Length: 146
Connection: keep-alive
Content-Disposition: attachment; filename="christmas_jingle_mp3.mp3"; filename*=UTF-8''christmas_jingle_mp3.mp3
Set-Cookie: app_session=***********e403a97e89a5f53fe9a26; Path=/; HttpOnly; SameSite=Lax
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
```

Should note that the mediastorage location is NOT default but uses another path, it is still on localstorage in /var/azuracast/

Expected behaviour: 
- the file playing in my browser

**Comment by SlvrEagle23** [comment]
@hcbd This sounds like a file permissions issue...what is the owner of the directory where you're uploading your media to? You may want to make sure that the folder is owned by the `azuracast` user just to ensure there aren't any problems.

**Comment by hcbd** [comment]
@SlvrEagle23 

This was my initial thought also, 
but after checking the permissions 
any file/folder under /var/azuracast/stations/* has the permission  " azuracast : www-data "

ls -al output for a random mp3 file (they all have the same permissions):
```
-rw-r--r-- 1 azuracast www-data  7388472 Oct 25 08:28  air_bach.mp3
```

**Comment by SlvrEagle23** [comment]
@hcbd I looked into this after some recent changes to the Ansible installation, and discovered that while our default directory permissions are sufficient for Docker installations (as the accessing user and the creating user are the same), they aren't sufficient for Ansible installations, since `nginx` is a different user than `azuracast`.

I've made some minor modifications to the code to accommodate for this, so the latest Rolling Release version should no longer have this issue with Ansible installations.
