### ISSUE TITLE
remote playlist

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#4792]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #c4d3a50 (2021-10-03 0:18) • Docker • PHP 8.0

### What happened?

I'm trying to use the remote playlist.
I want to schedule a relay within a playlist and I'm having a lot of problems, before it was working fine until I upgraded to liquidsoap 2.0. I don't know if this is interfering but no external station link works. I took every test I could. I tried icecast and shoutcast and both don't work. I tested various links from various panels such as centva cast, media cp and etc... None works. The radio can only connect to a relay if I go directly to the mount point and insert it, now if I do it by remote playlist it doesn't work.

### Relevant log output

```shell
Warning 4: Unused variable s
At /var/azuracast/.opam/4.12.0/lib/liquidsoap/share/liquidsoap/git/43aa734d/libs/source.liq, line 1 char 0 - line 37 char 96:
Error 7: Invalid value:
This source may control its own latency and cannot be used with this operator.
File /var/azuracast/stations/radioaquidaweb/config/liquidsoap.liq, line 149, char 102:
Warning 4: Unused variable s
At /var/azuracast/.opam/4.12.0/lib/liquidsoap/share/liquidsoap/git/43aa734d/libs/source.liq, line 1 char 0 - line 37 char 96:
Error 7: Invalid value:
This source may control its own latency and cannot be used with this operator.
```

**Comment by Abqehebter** [comment]
Just for my understanding: You have a rolling release version from 03.10. (10-03)
Would it be possible to update this? The error seems to be "actually" already fixed. See Issue: https://github.com/AzuraCast/AzuraCast/issues/4770

**Comment by Marcioghiraldelli** [comment]
I updated to the latest version and the problem still persists.
