### ISSUE TITLE
Liquidsoap Stalling and Buffer Overruns

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#4794]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#55f04d4 (2021-11-16 13:14)

### What happened?

Did rolling update in the wee AM hours of the 17th and everything ran fine.  Got called @ 8:45am by 1st streamer who was unable to log in and was hearing intermittent stream.  Restarted Liquidsoap at that time and streamer logged in fine.  Here is the log at that time;
[1st instance.txt](https://github.com/AzuraCast/AzuraCast/files/7560444/1st.instance.txt)

Including a Shoutcast log (date/time not properly set on that)  to show nothing unusual;
[Shout Log.txt](https://github.com/AzuraCast/AzuraCast/files/7560552/Shout.Log.txt)

Next streamer also logged in fine, but problem came back when time came to hand stream over to the next guy (myself). Reset my modem and puter to make sure the issue wasn't local, restarted Liquidsoap and managed to stream for my full 3 hrs slot;  
[2nd Log.txt](https://github.com/AzuraCast/AzuraCast/files/7560460/2nd.Log.txt)

Problem resurfaced at the time the 4th and last streamer was set to come on. Reset the buffet time to 30 secs from 15 and repeated the Liquidsoap restart; all was fine until  about 22:30, close to the end of her slot.  Instructed her to disconnect and proceeded to investigate further. At that moment the stream was repeating intermittent 1 sec pieces of  items in JINGLE playlists. Here is what I saw;

![Image0](https://user-images.githubusercontent.com/66107794/142364591-85eb2969-5b85-40d0-a4eb-75117cac2327.jpg)

![Image1](https://user-images.githubusercontent.com/66107794/142364653-d55ec07d-7f22-4808-a056-14daafd1023a.jpg)
Note that these were queued before the start of the 1st stream and couldn't be flushed out manually

![Image2](https://user-images.githubusercontent.com/66107794/142364936-5d7bdbf2-2b4b-4de7-a8e8-c575fcff9318.jpg)
 Webmin capture showing heavy load from Liquidsoap - Our normal = 40-50% or less
 
![Image3](https://user-images.githubusercontent.com/66107794/142365072-1479c769-761e-454e-94f7-37b4872156dc.jpg)
Stopped Liquid soap to see if actual culprit; then restarted;
![Image5](https://user-images.githubusercontent.com/66107794/142365152-c759c1dd-6704-48e5-b04c-a18e143bf0a7.jpg)

![Image6](https://user-images.githubusercontent.com/66107794/142365215-64ab06ed-e909-469c-a715-f61ae30c6750.jpg)
Our server is currently locked like this and playing intermittent 1 sec pieces of the song listed as Playing Next.  Here is the final log that I took at that time;
[Last Log.txt](https://github.com/AzuraCast/AzuraCast/files/7560599/Last.Log.txt)

I must admit I am at a loss as to my next move; do you have enough info to see the problem and offer some help?

Thanks in advance; Speedy

**Comment by SpeedyCharly** [comment]
Here is a final log taken at @2am showing where we're at now..
[Current.txt](https://github.com/AzuraCast/AzuraCast/files/7560733/Current.txt)

**Comment by SC2Mitch** [comment]
Duplicate
