### ISSUE TITLE
liquidsoap crashes after update. liquidsoap have a problem with the naming of a specific playlist

### ISSUE THREAD

**Issue by Horstwursti** [AzuraCast/AzuraCast#4795]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #266305e (2021-11-18 18:57)

### What happened?

After updating to the current release, liquidsoap started restarting continuously. The liquidsoap log kept returning the attached syntax error. The error output said it was a syntax error in the liquidsoap configuration file. Line 178, character 17. When looking in the liquidsoap configuration it was noticed that the line in question deals with the inclusion of a playlist. This playlist is the only one with a dot in the name. I have attached the line of the liquidsoap configuration, which is called by the liquidsoap log.

The problem could be solved for the time being by deactivating the affected playlist. The problem was reproducable after activating this playlist again. Now i have renamed the Playlist and deleted the dot in the name. Now liquidsoap runs fine!

### Relevant log output

```shell
At /var/azuracast/stations/c3lounge_radio/config/liquidsoap.liq, line 178, char 17:
Error 3: Syntax error!

playlist_kif44.5 = playlist(id="playlist_kif44.5",mode="randomize",reload_mode="watch","/var/azuracast/stations/c3lounge_radio/playlists/playlist_kif44.5.m3u")
```

**Comment by Vaalyn** [comment]
**Dev note:**
We should add a replacement of `.` to `_` in the [cleanUpVarName](https://github.com/AzuraCast/AzuraCast/blob/main/src/Radio/Backend/Liquidsoap/ConfigWriter.php#L1157-L1170) method used for playlist variable names.

**Comment by Vaalyn** [comment]
Fixed in https://github.com/AzuraCast/AzuraCast/commit/3a057a469a920b06c2c967a94c2f852f68330e3d
