### ISSUE TITLE
Liquiedsoap giving Error 4

### ISSUE THREAD

**Issue by sufyanshafiq** [AzuraCast/AzuraCast#4797]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #784438f

### What happened?

Azuracast updated to latest Rolling Release #784438f. After upgrade liquidsoap start giving error:

At line 5, char 0-16:
Error 4: Undefined variable init.daemon.set

### Relevant log output

```shell
At line 5, char 0-16:
Error 4: Undefined variable init.daemon.set
At line 5, char 0-16:
Error 4: Undefined variable init.daemon.set
At line 5, char 0-16:
Error 4: Undefined variable init.daemon.set
At line 5, char 0-16:
Error 4: Undefined variable init.daemon.set
At line 5, char 0-16:
Error 4: Undefined variable init.daemon.set
At line 5, char 0-16:
Error 4: Undefined variable init.daemon.set
At line 5, char 0-16:
Error 4: Undefined variable init.daemon.set
At line 5, char 0-16:
Error 4: Undefined variable init.daemon.set
At line 5, char 0-16:
Error 4: Undefined variable init.daemon.set
```

**Comment by Vaalyn** [comment]
It might be that your Liquidsoap Configuration file hasn't been re-generated after the update.
Please try restarting your stations via the `Restart Broadcasting` button under `Utilities` in the sidebar menu.
This should regenerate the configuration file.

If it is still showing this error after doing these steps please post your Liquidsoap Configuration here.

**Comment by sufyanshafiq** [comment]
I tried restarting the stations. But didn't work. Now I am restoring the backup. If this work.

**Comment by cecov74** [comment]
HI I have the same problem, 

`At line 5, char 0-16:
Error 4: Undefined variable init.daemon.set`

I have tryed to update 
now: AzuraCast • v0.15.0 Stable • Docker • PHP 8.1

`# WARNING! This file is automatically generated by AzuraCast.
# Do not update it directly!


init.daemon.set(false)
init.daemon.pidfile.path.set("/var/azuracast/stations/myradio/config/liquidsoap.pid")
log.stdout.set(true)
log.file.set(false)
settings.server.log.level.set(4)
settings.server.telnet.set(true)
settings.server.telnet.bind_addr.set("0.0.0.0")
settings.server.telnet.port.set(8004)
settings.harbor.bind_addrs.set(["0.0.0.0"])

settings.tag.encodings.set(["UTF-8","ISO-8859-1"])
settings.encoder.metadata.export.set(["artist","title","album","song"])

settings.decoder.priorities.ogg.set(15)
settings.decoder.priorities.mad.set(15)
settings.decoder.priorities.flac.set(15)
settings.decoder.priorities.aac.set(15)
settings.decoder.priorities.ffmpeg.set(10)

setenv("TZ", "Europe/Rome")

azuracast_api_auth = ref("(PASSWORD)")
ignore(azuracast_api_auth)

autodj_is_loading = ref(true)
ignore(autodj_is_loading)

autodj_ping_attempts = ref(0)
ignore(autodj_ping_attempts)

# Track live-enabled status script-wide for fades.
live_enabled = ref(false)
ignore(live_enabled)

playlist_default = playlist(id="playlist_default",mime_type="audio/x-mpegurl",mode="randomize",reload_mode="watch","/var/azuracast/stations/myradio/playlists/playlist_default.m3u")
playlist_default = cue_cut(id="cue_playlist_default", playlist_default)

playlist_oldsong = playlist(id="playlist_oldsong",mime_type="audio/x-mpegurl",mode="randomize",reload_mode="watch","/var/azuracast/stations/myradio/playlists/playlist_oldsong.m3u")
playlist_oldsong = cue_cut(id="cue_playlist_oldsong", playlist_oldsong)

playlist_jeengle = playlist(id="playlist_jeengle",mime_type="audio/x-mpegurl",mode="randomize",reload_mode="watch","/var/azuracast/stations/myradio/playlists/playlist_jeengle.m3u")
playlist_jeengle = cue_cut(id="cue_playlist_jeengle", playlist_jeengle)

# Standard Playlists
radio = random(id="standard_playlists", weights=[3, 2], [playlist_default, playlist_oldsong])

# Once per x Songs Playlists
radio = rotate(weights=[1,1], [playlist_jeengle, radio])

# AutoDJ Next Song Script
def autodj_next_song() =
    log("autodj_next_song: Sending AzuraCast API Call...")
    uri = list.hd(process.read.lines(env=[("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/1/nextsong --form api_auth="$API_AUTH"', timeout=10.), default="")
    log("autodj_next_song: AzuraCast API Response: #{uri}")

    if uri == "" or string.match(pattern="Error", uri) then
        null()
    else
        r = request.create(uri)
        if request.resolve(r) then
            r
        else
            null()
       end
    end
end

# Delayed ping for AutoDJ Next Song
def wait_for_next_song(autodj)
    autodj_ping_attempts := !autodj_ping_attempts + 1
    delay = ref(0.5)
    
    if source.is_ready(autodj) then
        log("AutoDJ is ready!")
        
        autodj_is_loading := false
        delay := -1.0
    elsif !autodj_ping_attempts > 200 then
        log("AutoDJ could not be initialized within the specified timeout.")
        
        autodj_is_loading := false
        delay := -1.0
    end
    
    !delay
end

dynamic = request.dynamic(id="next_song", timeout=20., retry_delay=2., autodj_next_song)
dynamic = cue_cut(id="cue_next_song", dynamic)

dynamic_startup = fallback(
    id = "dynamic_startup",
    track_sensitive = false,
    [
        dynamic,
        source.available(
            blank(id = "autodj_startup_blank", duration = 120.),
            predicate.activates({!autodj_is_loading})
        )
    ]
)
radio = fallback(id="autodj_fallback", track_sensitive = true, [dynamic_startup, radio])

ref_dynamic = ref(dynamic);
thread.run.recurrent(delay=0.25, { wait_for_next_song(!ref_dynamic) })

requests = request.queue(id="requests")
requests = cue_cut(id="cue_requests", requests)

radio = fallback(id="requests_fallback", track_sensitive = true, [requests, radio])
add_skip_command(radio)

radio = crossfade(smart=false, duration=3.00, fade_out=2.00, fade_in=2.00, radio)

# DJ Authentication
last_authenticated_dj = ref("")
live_dj = ref("")

live_record_path = ref("")

def dj_auth(login) =
    user = ref("")
    password = ref("")
    
    if (login.user == "source" or login.user == "") and (string.match(pattern="(:|,)+", login.password)) then
        auth_string = string.split(separator="(:|,)", login.password)
        
        user := list.nth(default="", auth_string, 0)
        password := list.nth(default="", auth_string, 2)
    else
        user := login.user
        password := login.password
    end
    
    log("dj_auth: Sending AzuraCast API DJ Auth command for user: #{!user}")
    ret = list.hd(process.read.lines(env=[("DJ_USER", !user), ("DJ_PASSWORD", !password), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/1/auth --form dj-user="$DJ_USER" --form dj-password="$DJ_PASSWORD" --form api_auth="$API_AUTH"', timeout=10.), default="")
    log("dj_auth: AzuraCast API Response: #{ret}")
    
    authed = bool_of_string(ret)
    if (authed) then
        last_authenticated_dj := !user
    end
    
    authed
end

def live_connected(header) =
    dj = !last_authenticated_dj
    log("DJ Source connected! Last authenticated DJ: #{dj} - #{header}")

    live_enabled := true
    live_dj := dj
    
    log("live_connected: Sending AzuraCast API DJ onConnect command...")
    ret = list.hd(process.read.lines(env=[("DJ_USER", dj), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/1/djon --form dj-user="$DJ_USER" --form api_auth="$API_AUTH"', timeout=10.), default="")
    log("live_connected: AzuraCast API Response: #{ret}")

    if (string.contains(prefix="/", ret)) then
        live_record_path := ret
    end
end

def live_disconnected() =
    dj = !live_dj
    
    log("DJ Source disconnected! Current live DJ: #{dj}")
    
    log("live_disconnected: Sending AzuraCast API DJ onDisconnect command...")
    ret = list.hd(process.read.lines(env=[("DJ_USER", dj), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/1/djoff --form dj-user="$DJ_USER" --form api_auth="$API_AUTH"', timeout=10.), default="")
    log("live_disconnected: AzuraCast API Response: #{ret}")
    
    live_enabled := false
    last_authenticated_dj := ""
    live_dj := ""
    
    live_record_path := ""
end

# A Pre-DJ source of radio that can be broadcast if needed',
radio_without_live = radio
ignore(radio_without_live)

# Live Broadcasting
live = input.harbor("/", id = "input_streamer", port = 8005, auth = dj_auth, icy = true, icy_metadata_charset = "UTF-8", metadata_charset = "UTF-8", on_connect = live_connected, on_disconnect = live_disconnected, buffer = 5.00, max = 10.00)

def insert_missing(m) =
    if m == [] then
        [("title", "Live Broadcast")]
    else
        m
    end
end
live = map_metadata(insert_missing, live)

radio = fallback(id="live_fallback", replay_metadata=false, track_sensitive=false, [live, radio])

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

# Apply amplification metadata (if supplied)
radio = amplify(override="liq_amplify", 1., radio)

radio = fallback(id="safe_fallback", track_sensitive = false, [radio, single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")])

# Send metadata changes back to AzuraCast
def metadata_updated(m) =
    def f() =
        if (m["song_id"] != "") then
            ret = list.hd(process.read.lines(env=[("SONG", m["song_id"]), ("MEDIA", m["media_id"]), ("PLAYLIST", m["playlist_id"]), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/1/feedback --form song="$SONG" --form media="$MEDIA" --form playlist="$PLAYLIST" --form api_auth="$API_AUTH"', timeout=10.), default="")
            log("AzuraCast Feedback Response: #{ret}")
        end
        (-1.)
    end
    
    thread.run.recurrent(fast=false, delay=0., f)
end

radio.on_metadata(metadata_updated)

# Local Broadcasts
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), id="local_1", host = "127.0.0.1", port = 8000, password = "(PASSWORD)", mount = "/radio.mp3", name = "myradio", description = "", genre = "", url = "https://myradio.eu", public = false, encoding = "UTF-8", radio)

# Remote Relays
`
