### ISSUE TITLE
Unable to restore backup

### ISSUE THREAD

**Issue by sufyanshafiq** [AzuraCast/AzuraCast#4798]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #784438f

### What happened?

After upgrade system was not responding properly. Having backup I reinstalled the Azuracast when restoring it is not restoring the backup. Giving permission denied and unzip fail error.

### Relevant log output

```shell
Starting up AzuraCast services...
Services started up and ready!
This script must be run as the "azuracast" user. Rerunning...
AzuraCast Backup Restore
(Environment: production)

AzuraCast Restore
=================

Please wait while the backup is restored...

Extracting backup file...
-------------------------

Archive:  /var/azuracast/backups/Nov202021.zip
error:  cannot create Nov202021
        Permission denied
[2021-11-21T11:56:59.950475+00:00] AzuraCast.ERROR: Symfony\Component\Process\Exception\ProcessFailedException: The command "'unzip' '/var/azuracast/backups/Nov202021.zip'" failed.  Exit Code: 50(Unknown error)  Working directory: /  Output: ================ Archive:  /var/azuracast/backups/Nov202021.zip   Error Output: ================ error:  cannot create Nov202021         Permission denied  (uncaught exception) at /var/azuracast/www/vendor/symfony/process/Process.php line 270 while running console command `azuracast:restore` {"exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessFailedException(code: 0): The command \"'unzip' '/var/azuracast/backups/Nov202021.zip'\" failed.\n\nExit Code: 50(Unknown error)\n\nWorking directory: /\n\nOutput:\n================\nArchive:  /var/azuracast/backups/Nov202021.zip\n\n\nError Output:\n================\nerror:  cannot create Nov202021\n        Permission denied\n at /var/azuracast/www/vendor/symfony/process/Process.php:270)"} []
[2021-11-21T11:56:59.953260+00:00] AzuraCast.WARNING: Console command `azuracast:restore` exited with error code 1. [] []

In Process.php line 270:
                                                                        
  The command "'unzip' '/var/azuracast/backups/Nov202021.zip'" failed.  
                                                                        
  Exit Code: 50(Unknown error)                                          
                                                                        
  Working directory: /                                                  
                                                                        
  Output:                                                               
  ================                                                      
  Archive:  /var/azuracast/backups/Nov202021.zip                        
                                                                        
                                                                        
  Error Output:                                                         
  ================                                                      
  error:  cannot create Nov202021                                       
          Permission denied                                             
                                                                        

azuracast:restore [--restore] [--release] [--] <path>

ERROR: 1
WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
```

**Comment by sufyanshafiq** [comment]
I tried the command
./docker.sh restore-legacy Nov202021.zip

It runs successfully but not restoring anything and when I access the web page it shows AzuraCast First-Time Setup

/var/azuracast$ ./docker.sh restore-legacy Nov202021.zip
WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
Stopping nginx_proxy_letsencrypt ... done
Stopping nginx_proxy             ... done
Stopping azuracast_web           ... done
Stopping azuracast_mariadb       ... done
Stopping azuracast_stations      ... done
Stopping azuracast_redis         ... done
Removing nginx_proxy_letsencrypt ... done
Removing nginx_proxy             ... done
Removing azuracast_web           ... done
Removing azuracast_mariadb       ... done
Removing azuracast_stations      ... done
Removing azuracast_redis         ... done
Removing network azuracast_backend
Removing network azuracast_frontend
azuracast_db_data
azuracast_station_data
azuracast_db_data
azuracast_station_data
tar: invalid magic
tar: short read
WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
Creating network "azuracast_backend" with driver "bridge"
Creating network "azuracast_frontend" with driver "bridge"
Creating azuracast_stations ... done
Creating azuracast_redis    ... done
Creating azuracast_mariadb  ... done
Creating azuracast_web      ... done
Creating nginx_proxy        ... done
Creating nginx_proxy_letsencrypt ... done

**Comment by sufyanshafiq** [comment]
@Vaalyn Kindly look into this plz.

I tried restore_legacy as well. It runs but nothing restored and opens up a AzuraCast First-Time Setup page.

**Comment by Abqehebter** [comment]
It does not make it faster to tag the developers. The issue here has been there before: https://github.com/AzuraCast/AzuraCast/issues/4758

**Comment by SC2Mitch** [comment]
Duplicate, don't ping developers, take this to #4758.

**Comment by sufyanshafiq** [comment]
I do understand, I am not expecting a resolution in one comment. Just a note if the this can be addressed. I will further move and comment on 4758.

Thanks for the response.
