### ISSUE TITLE
Playlist Enhancements

### ISSUE THREAD

**Issue by SlvrEagle23** [AzuraCast/AzuraCast#480]
- [x] Add new database field for StationPlaylist entity, "source", indicating what the origin of the playlist should be. Options include: `random_songs` (default), `sequential_songs`, and `remote_url` to start
- [ ] Modify existing "StationPlaylist -> StationMedia" relationship to include a `weight` parameter, along with a `last_played` timestamp for easier "get next song" tracking
- [ ] Add form UI changes necessary to allow selection of these types
- [ ] Restrict playlist addition to playlists with "songs" as the source
- [ ] Integrate new playlist source information into "get next song" code
- [ ] Create new "reorder playlist" page for sequential playlists

**Comment by muzo178** [comment]
I'm really looking forward to these enhancements, especially sequential ordering of playlist contents like others have requested before.

**Comment by SlvrEagle23** [comment]
Update: Follow the progress of playlist enhancements on the "Projects" tab!
