### ISSUE TITLE
AzuraCast Stream URL

### ISSUE THREAD

**Issue by k013play** [AzuraCast/AzuraCast#4800]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

Hello, 

how to setup my direct stream link to be IP:PORT/radio.mp3 or my.radio.com:PORT/radio.mp3  instead of my.radio.com/radio/PORT/radio.mp3 

All other stuff working fine. 

thank you for advice...

**Comment by Abqehebter** [comment]
You can already use my.radio.com:PORT/radio.mp3. It works fine for me:

`azuracast.example.com:8000/radio.mp3`

But to keep it like this by default, you have to disable the webproxy function in the Administations > System Settings area

**Comment by k013play** [comment]
UPDATE> im using shoutcast, not ICEcast, installed from manual

**Comment by k013play** [comment]
> You can already use my.radio.com:PORT/radio.mp3. It works fine for me:
> 
> `azuracast.example.com:8000/radio.mp3`
> 
> But to keep it like this by default, you have to disable the webproxy function in the Administations > System Settings area

Now it shows https://my.radio.com:PORT/radio.mp3 but still not working when i try to open in Winamp or other player. Do i need to uncheck something more?

**Comment by Abqehebter** [comment]
Have you tried it without https?
`http://my.radio.com:PORT/radio.mp3`
So if it works in the browser, it should work there too. That's the status with me.

**Comment by k013play** [comment]
> Have you tried it without https? `http://my.radio.com:PORT/radio.mp3` So if it works in the browser, it should work there too. That's the status with me.

Thank u for trying to help, this is url https://radio.k-013.com:8030/radio.mp3 - not working even is not https. Do i need to disable ssl in cloudflare? In System settings security is alsot turned on Always use HTTPS, site base url is also with https

**Comment by Abqehebter** [comment]
I use the LetsEncrypt service from AzuraCast itself, so it seems to work. Cloudflare I would not recommend with AzuraCast also rather at all, because there the streams simply stop with me every few hours (So but only my experience).
You can try either to turn off SSL at Cloudflare or to turn off Cloudflare in general for this site.

**Comment by k013play** [comment]
> I use the LetsEncrypt service from AzuraCast itself, so it seems to work. Cloudflare I would not recommend with AzuraCast also rather at all, because there the streams simply stop with me every few hours (So but only my experience). You can try either to turn off SSL at Cloudflare or to turn off Cloudflare in general for this site.

I fix half of problem>  I turn of cloudflare proxy, then enable port in VPS panel and it starts working http://radio.k-013.com:8030/radio.mp3  / it not working with https . But now i have problem in panel. Azuracast still force using https when i go to station manager page. What do i need to do more?  Also base url im change from https to http

**Comment by Abqehebter** [comment]
Try deleting your browser data and cookies in your browser itself. Cloudflare is sometimes still a bit behind.
Otherwise, it may also be that the option is still active at AzuraCast. See: `Administration > System Settings > Security & Privacy > Untick Always Use HTTPS`

**Comment by k013play** [comment]
> Try deleting your browser data (cache) and cookies in your browser itself. Cloudflare is sometimes still a bit behind. Otherwise, it may also be that the option is still active at AzuraCast. See: `Administration > System Settings > Security & Privacy > Untick Always Use HTTPS`

Thank u for help, now i got all working. Now tell me do i need to enable letsencrypt and how when to avoid reinstall whole system...

**Comment by Abqehebter** [comment]
Relatively simple. You just have to follow the instructions here: https://docs.azuracast.com/en/administration/ssl-and-lets-encrypt#enabling-letsencrypt
You don't have to reinstall anything at all :)

**Comment by k013play** [comment]
I will follow this instructions. Thank u Abqehebter for help.

**Comment by zloysystem** [comment]
@k013play winamp does not read https streams, you can do the same as me by simply editing the file in a regular notepad listen.pls or listen.m3u, replacing https with http and giving it back.то

**Comment by Abqehebter** [comment]
@zloysystem Thank you for the objection. I have hardly dealt with that. But so it should work well in the overall concept :)
