### ISSUE TITLE
Streamer name doesn't change on disconnect.

### ISSUE THREAD

**Issue by BenFromXonos** [AzuraCast/AzuraCast#4803]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #9b7d7f7 (2021-11-17 16:30)

### What happened?

DJ Streamer name does not update on disconnect. 

It will only ever update when a new DJ connected, and if a DJ connects the streamer name will remain.

I'm not too sure where this behavior has come from, as it was functioning okay before the machine losing network connection due to a provider outage.

Any ideas?

**Comment by BenFromXonos** [comment]
![image](https://user-images.githubusercontent.com/23050115/143303295-36306205-79b1-461b-a1ad-83f4b98b7551.png)

Side note, Liquidsoap seems to know it's playing from a playlist, which makes me think something in AzuraCast is not reading the "disconnected" signal from LiquidSoap. 

I have tried updating and rolling to master, by the way.

**Comment by SC2Mitch** [comment]
Thanks for the report, will check this tonight.

**Comment by BenFromXonos** [comment]
@SC2Mitch 

I think I noticed an issue in logs last night - I don't remember what it was exactly but I'll have to have a look later. 

My theory is some sort of MySQL corruption. I'll keep you updated though.

**Comment by SC2Mitch** [comment]
Unable to replicate this on my machine, after the streamer disconnects and a Now Playing check is ran, it goes back to normal.

**Comment by thisiszane** [comment]
> Unable to replicate this on my machine, after the streamer disconnects and a Now Playing check is ran, it goes back to normal.

What software are you using to encode & what version of AzuraCast are you using?

**Comment by SC2Mitch** [comment]
> > Unable to replicate this on my machine, after the streamer disconnects and a Now Playing check is ran, it goes back to normal.
> 
> What software are you using to encode & what version of AzuraCast are you using?

The latest (dev) build and [Mixx](https://mixxx.org/)

**Comment by BenFromXonos** [comment]
Managed to fix this on our install by deleting the liquidsoap config, letting it regenerate and changing a couple of random settings so it would kick back into gear.

Not sure what caused this, but this is what fixed it for me.

Thank you all for providing such an amazing project.
