### ISSUE TITLE
It is not possible to add a song manually to the queue [MySQL Error]

### ISSUE THREAD

**Issue by YosefAdPro** [AzuraCast/AzuraCast#4804]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #2bc2aa9 (2021-11-24 21:50) 

### What happened?

When trying to add a song to the queue manually. There is a MySQL error.

![image](https://user-images.githubusercontent.com/11810187/143323861-baf4e6c1-c071-4adb-9887-486c5b3ba619.png)

**Comment by YosefAdPro** [comment]
Another problem, perhaps in the same context.
The _**Song Playback Timeline**_ page does not represent new data.

**Comment by SlvrEagle23** [comment]
@YosefAdPro Latest update that's currently deploying (will be ready for update when commit above is green) should fix the queueing issue. Not sure what's causing the Song Playback Timeline issue, as my local timeline is up-to-date.

**Comment by YosefAdPro** [comment]
@SlvrEagle23 queueing now ok.
Song Playback Timeline is fine. Probably my mistake.

Thank you.
