### ISSUE TITLE
the space overlay2 file is getting bigger

### ISSUE THREAD

**Issue by istahilagi** [AzuraCast/AzuraCast#4809]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.14.1

### What happened?

I see the var/lib/docker/overlay2 folder has large files, even bigger than the files in the "volumes" folder.

may i delete the overlay2 folder? and does it affect the azuracast system?
thank you

**Comment by BenFromXonos** [comment]
Hey there!

Anything in /var/lib/docker/volumes or /var/lib/docker/overlay(2) is most likely related to your AzuraCast install, or other docker containers you may have running.

I would not recommend deleting these, as these **WILL** contain vital AzuraCast files.

**Comment by istahilagi** [comment]
it's a very good solution...
 but how to do docker system prune -a?
 
thank you for the response

**Comment by SC2Mitch** [comment]
Go to your terminal and run this in the command line `docker system prune -a`. You may need to be in the azuracast directory. `/var/azuracast`

**Comment by istahilagi** [comment]
I did that and it worked... but only 5 GB of the storage capacity was deleted on the server, while the files in overlay2 were still 263 GB

**Comment by SlvrEagle23** [comment]
@istahilagi How much media do you have uploaded? Do you have automatic backups enabled? Those can be big contributors to the total file size.

You may also just be dealing with logs that are expanding over a long term of use, and it can sometimes be helpful to run the updater from time to time just to clean those out, or just restart your services via:

```
cd /var/azuracast
docker-compose down
docker-compose up -d
```

**Comment by istahilagi** [comment]
thanks, it worked....

thanks for the response and help... :)

**Comment by wheslleyandrade** [comment]
> Hey there!
> 
> Anything in /var/lib/docker/volumes or /var/lib/docker/overlay(2) is most likely related to your AzuraCast install, or other docker containers you may have running.
> 
> I would not recommend deleting these, as these **WILL** contain vital AzuraCast files. When you update next, a good idea would to select yes on the option to delete all of the old unused files and images.
> 
> In the mean time, it might be worth doing `docker system prune -a` which will remove all unused containers and files that aren't needed.

Do I have to stop azura to run this command?

**Comment by SlvrEagle23** [comment]
@wheslleyandrade It's recommended that you keep AzuraCast running when you run that command, as then Docker won't recognize AzuraCast itself as an "unused" container.

**Comment by wheslleyandrade** [comment]
> @wheslleyandradeÉ recomendável que você mantenha o AzuraCast em execução ao executar esse comando, pois o Docker não reconhecerá o próprio AzuraCast como um contêiner "não utilizado".

I'm having the same problem, the /var/lib/docker/overlay2/ folder is 370gb while radio files don't occupy 150gb, compromised storage. this happened 2 days ago and it's not logs either.

**Comment by SlvrEagle23** [comment]
@wheslleyandrade Check your automatic backups...by default, they're stored in that same folder and are often an explanation for why you would have storage space that's almost twice what your actual media storage is.

**Comment by wheslleyandrade** [comment]
I keep 3 backups, both under 2mb.

**Comment by SlvrEagle23** [comment]
@wheslleyandrade You'll have to look through that folder to see what's taking up the space, then, as we can't tell without knowing that information. There's a tool we recommend called `ncdu` that can help with that.
