### ISSUE TITLE
Password reset slim application error

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#4811]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #2747f7a (2021-11-07 21:20)

### What happened?

Hi, I noticed that in the version before Liquidsoap 2.0 the password reset via email did not work, and I have not found an issue yet. Maybe someone here can (still) confirm this (even in the latest version?):
![image](https://user-images.githubusercontent.com/42640247/143488790-606f6d7d-e449-46b6-8cc2-062e085884ac.png)

### Relevant log output

```shell
AzuraCast.ERROR: Library zxcvbn not found! {"file":"/var/azuracast/www/src/Assets.php","line":177,"code":0} []
```

**Comment by SlvrEagle23** [comment]
@Abqehebter Good catch; we missed that one in the Vue passes. Fixed as of latest Rolling being deployed.
