### ISSUE TITLE
Docker returns orphan containers warning

### ISSUE THREAD

**Issue by ItsJamieHosie** [AzuraCast/AzuraCast#4818]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #4fda3c0 (2021-11-25 23:32)

### What happened?

Just noticed this warning when updating not to sure what it is asking to run the command just wondering what i would need to do to get it to run i am completely clueless haha
![Screenshot 2021-11-26 123722](https://user-images.githubusercontent.com/54157291/143582790-84fd3cd2-227a-49b6-bba8-aa8c54e554d0.jpg)

thank youuuuu

**Comment by SC2Mitch** [comment]
I'm fairly sure we should of fixed this issue, but it appears not. I'm able to replicate this on my machine too. We could probably just 'hide' the warning, since it's not a huge issue.

**Comment by Vaalyn** [comment]
I've investigated which line in our `docker.sh` is causing this warning to show up and found out that the `COMPOSE_IGNORE_ORPHANS=True` in [this line](https://github.com/AzuraCast/AzuraCast/blob/main/docker.sh#L348) seems to be ignored by docker-compose. When I disable this line by commenting it out there is no orphans warning anymore.

I haven't yet seen anything in the docker-compose docs or their GH issues about this env var not working for `docker-compose run`.

**Comment by ItsJamieHosie** [comment]
ah ok so is it fine to just ignore it then i just seen it when i updated and thought i had done something wrong haha

**Comment by Vaalyn** [comment]
This warning is due to the addition of the `installer` container which handles specific install / update steps.
The script starts this container via a different `docker-compose.installer.yml` which sees containers in it's space that are not in this file and tells you about this. We added the `COMPOSE_IGNORE_ORPHANS=True` to suppress this warning since it's expected to have those other containers in the same space but for some reason this is not working correctly in docker-compose.

**Comment by SlvrEagle23** [comment]
With the latest commit, I'm trying another route to avoid those confusing (but not actually correct) "orphaned containers" warnings. Let's see if that helps with this issue. Be sure to run `./docker.sh update-self` before updating to make sure you're testing with the latest version.

**Comment by Vaalyn** [comment]
On my test server I can confirm that the warning is now gone with the latest commit.

**Comment by Robdewild** [comment]
Orphan problem solved here👍
