### ISSUE TITLE
Can't run 2 radios at the same time. Liquidsoap Error

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#4820]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #47d595f (2021-11-27 4:10)

### What happened?

So, i decide to stream another station on the same machine. First i copy the same station and tried to change some things, but it didn't work out. Than i deleted it, and create a brand new station. The thing is, that the liquidsoap doesn't connect to the icecast server. I was changing values, and mount points, but nothing helped.
Than i tried to stop the main station. After that i could successfully run the second station. This was wired. Than i can no longer run the main station. Attaching Liquidsoap log

Secondly i want to ask, why i can't run the both stations with one Icecast? Like i want to run the both radios on 8000 port with different mount points. But in the settings, i can't put the 8000 port, because it's already used. I think it will be lighter, if the icecast process is only one.

### Relevant log output

```shell
Liquidsoap Log

At /var/azuracast/stations/christmas/config/liquidsoap.liq, line 19, char 126:
Warning 3: This expression should have type unit.
At /var/azuracast/stations/christmas/config/liquidsoap.liq, line 22, char 24-28:
Warning 3: This expression should have type unit.
At /var/azuracast/stations/christmas/config/liquidsoap.liq, line 25, char 27:
Warning 3: This expression should have type unit.
At /var/azuracast/stations/christmas/config/liquidsoap.liq, line 28, char 116-120:
Error 6: Cannot apply that parameter because the function at /var/azuracast/stations/christmas/config/liquidsoap.liq, line 28, char 27-36
has no argument labeled "conservative"!
```
```

**Comment by Abqehebter** [comment]
Can you send us your liquidsoap config?
`Utilities > Log Viewer > Liquidsoap Configuration`

**Comment by NicoxDJ** [comment]
```
# WARNING! This file is automatically generated by AzuraCast.
# Do not update it directly!


set("init.daemon", false)
set("init.daemon.pidfile.path","/var/azuracast/stations/christmas/config/liquidsoap.pid")
set("log.stdout", true)
set("log.file", false)
set("server.telnet",true)
set("server.telnet.bind_addr","127.0.0.1")
set("server.telnet.port", 8005)
set("harbor.bind_addrs",["0.0.0.0"])

set("tag.encodings",["UTF-8","ISO-8859-1"])
set("encoder.encoder.export",["artist","title","album","song"])

setenv("TZ", "Europe/Sofia")

azuracast_api_auth = ref "(PASSWORD)"
ignore(azuracast_api_auth)

autodj_is_loading = ref true
ignore(autodj_is_loading)

autodj_ping_attempts = ref 0
ignore(autodj_ping_attempts)

playlist_christmas_songs = playlist(id="playlist_christmas_songs",mode="randomize",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/christmas/playlists/playlist_christmas_songs.m3u")
playlist_christmas_songs = audio_to_stereo(id="stereo_playlist_christmas_songs", playlist_christmas_songs)
playlist_christmas_songs = cue_cut(id="cue_playlist_christmas_songs", playlist_christmas_songs)

# Standard Playlists
radio = random(id="standard_playlists", weights=[3], [playlist_christmas_songs])

# AutoDJ Next Song Script
def autodj_next_song() =
    uri = list.hd(get_process_lines(env=[], '/usr/bin/php /var/azuracast/www/bin/console azuracast:internal:nextsong 6'), default="")
    log("AzuraCast Raw Response: #{uri}")

    if uri == "" or string.match(pattern="Error", uri) then
        []
    else
        r = request.create(uri)
        if request.resolve(r) then
            [r]
        else
            []
       end
    end
end

# Delayed ping for AutoDJ Next Song
def wait_for_next_song(autodj)
    autodj_ping_attempts := !autodj_ping_attempts + 1
    delay = ref 0.5

    if source.is_ready(!autodj) then
        log("AutoDJ is ready!")

        autodj_is_loading := false
        delay := -1.0
    elsif !autodj_ping_attempts > 200 then
        log("AutoDJ could not be initialized within the specified timeout.")

        autodj_is_loading := false
        delay := -1.0
    end

    !delay
end

dynamic = request.dynamic.list(id="next_song", timeout=20., retry_delay=2., autodj_next_song)
dynamic = audio_to_stereo(id="stereo_next_song", dynamic)
dynamic = cue_cut(id="cue_next_song", dynamic)

dynamic_startup = fallback(
    id = "dynamic_startup",
    track_sensitive = false,
    [
        dynamic,
        at(
            fun()-> !autodj_is_loading,
            blank(id = "autodj_startup_blank", duration = 120.)
        )
    ]
)
radio = fallback(id="autodj_fallback", track_sensitive = true, [dynamic_startup, radio])

ref_dynamic = ref dynamic;
add_timeout(0.25,fun()->wait_for_next_song(ref_dynamic))

requests = request.queue(id="requests")
requests = audio_to_stereo(id="stereo_requests", requests)
requests = cue_cut(id="cue_requests", requests)

radio = fallback(id="requests_fallback", track_sensitive = true, [requests, radio])
add_skip_command(radio)

radio = crossfade(smart=false, duration=7.50,fade_out=5.00,fade_in=5.00,radio)

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

# Apply amplification metadata (if supplied)
radio = amplify(override="liq_amplify", 1., radio)

radio = fallback(id="safe_fallback", track_sensitive = false, [radio, single(id="error_jingle", "/var/azuracast/www/resources/error.mp3")])

# Send metadata changes back to AzuraCast
def metadata_updated(m) =
    def f() =
        if (m["song_id"] != "") then
            ret = list.hd(get_process_lines(env=[("SONG", m["song_id"]), ("MEDIA", m["media_id"]), ("PLAYLIST", m["playlist_id"])], '/usr/bin/php /var/azuracast/www/bin/console azuracast:internal:feedback 6 --song="$SONG" --media="$MEDIA" --playlist="$PLAYLIST"'), default="")
            log("AzuraCast Feedback Response: #{ret}")
        end
        (-1.)
    end

    add_timeout(fast=false, 0., f)
end

radio = on_metadata(metadata_updated,radio)

# Local Broadcasts
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=192, id3v2=true), id="local_1", host = "127.0.0.1", port = 8001, password = "(PASSWORD)", mount = "/christmas192", name = "Radio Club-BG (Christmas Station)", description = "Radio Club-BG (Christmas Station)", genre = "Christmas", url = "http://*********/", public = false, encoding = "UTF-8", radio)

# Remote Relays
```

**Comment by Abqehebter** [comment]
At first glance, it looks like the config has not been updated to Liquidsoap v2 - because I have a lot more and also other things.

In question 2, with only one Icecast: Of course that should work in normal case. You could try to connect a relay at the second station on the first Icecast. So the stream should run on the first Icecast (This is how it worked for me).

**Comment by NicoxDJ** [comment]
How i can update the config? All what i did is update the system, and than i create the new station. I don't know why is old config.

**Comment by NicoxDJ** [comment]
I manage it to work. I don't know how. I Create Mount point on the first station, than i create Remote Relay on the second station and point it to the other icecast server on 8000 port. At first, didn't want to connect because error
```
BadNameException at /var/azuracast/www/src/Radio/AbstractAdapter.php L251: Liquidsoap is not recognized as a service.
It may not be registered with Supervisor yet. Restarting broadcasting may help.
```
But after reboot it worked out.

**Comment by YosefAdPro** [comment]
@NicoxDJ It is not possible to run multiple instances of on a single port.
The system can work with a different port for each station.

**Comment by NicoxDJ** [comment]
@YosefAdPro Sure it can. Right now I'm running 3 stations with only one Icecast server.
For you and for everybody else who is searching for information here are the steps:

1) On the main station (where the icecast is installed), you create mount point for the second station.
- Important: `Disable` Auto DJ option on the next tab, or the liquidsoap service of the main station will connect to that mount point too.
- Advanced:
You can add these code in the `Custom Fronted Configuration`, or in the icecast page you will see the same data (name, description, genre) for all mount points:
```
<stream-name>Second Station Name</stream-name>
<stream-description>Second Station Description</stream-description>
<stream-url>http://second-station-website/</stream-url>
<genre>Second Station Genre</genre>
```

2) Create the second station and DISABLE broadcasting > select `Only connect to a remote server.` on the Broadcasting tab.

3) Navigate to `Remote Relays` and create a new one. Use the same mount point as on Step 1. Use "http://127.0.0.1:8000" for `Remote Station Listening URL`. On this mount point you can ENABLE Auto DJ -> `Broadcast AutoDJ to Remote Station`. Again use the same mount point as Step 1. On `Remote Station Source Port` type `8000`. Write `source` in `Remote Station Source Username` , and use the `SOURCE` password showed in the MAIN STATION broadcasting settings.

4) Restart all services on the main station, and on the second station, or what I did is reboot of the system. If everything is done correctly the second station liquidsoap service should be connect up to 10 seconds. If not, check the Liquidsoap Log on the second station for errors. If showing error for maximum connections (or something like that), check the mount points for differences.

**Comment by YosefAdPro** [comment]
Officially in AzuraCast Each station needs its own port.

You can always think outside the box and do more advanced things in a personalized way.

**Comment by Abqehebter** [comment]
Officially, I wouldn't stress it. You as a user are free to decide how you want to make your stations public. You can disable or re-enable any service per station.

Therefore, I would say here: completely legal.

**Comment by YosefAdPro** [comment]
> Therefore, I would say here: completely legal.

I did not talk about legal or not.
I mean by the book, that's how it works. :)

**Comment by SlvrEagle23** [comment]
Just to clarify: yes, it's possible to run multiple stations on a single port via the methods above, but it isn't an officially supported way of operating AzuraCast, which means we don't provide support for this specific scenario if things go wrong. By design, we intend for stations to be "sandboxed" into their own port range, where their own instance of Liquidsoap and Icecast/SHOUTcast operate independent from other stations.
