### ISSUE TITLE
now playing not updating when live stream ends

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#4827]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

47d595f (2021-11-27 4:10) • Docker • PHP 8.0

### What happened?

hello,
when i make live stream,   and end it the now playing keeps in the last livestream metadata. it just change when auto dj song ends.
and, when this apens, the bug of jingle mod showing previous song in nowplaying returns but just for the first song change after livestream ends.

**Comment by Abqehebter** [comment]
See: https://github.com/AzuraCast/AzuraCast/issues/4803

**Comment by nunotfc** [comment]
i deleted liquidsoap configs you mean in utilities configs keeping all blank, right? i made this and doesnt work.

**Comment by nunotfc** [comment]
i made all and cant fix this anoying ishue.

**Comment by nunotfc** [comment]
@slvrEagle23
can you do a check this bug please?

**Comment by Abqehebter** [comment]
Please do not flag any developers and request to investigate the bugs. They will keep an eye on it as soon as possible. This will not make it faster.

Can you send me your liquidsoap config in here?
`Utilities > Log Viewer > Liquidsoap Configuration`

**Comment by nunotfc** [comment]
ok, sorry.
btw, here is the log.
# WARNING! This file is automatically generated by AzuraCast.
# Do not update it directly!


init.daemon.set(false)
init.daemon.pidfile.path.set("/var/azuracast/stations/renovaradio/config/liquidsoap.pid")
log.stdout.set(true)
log.file.set(false)
settings.server.telnet.set(true)
settings.server.telnet.bind_addr.set("0.0.0.0")
settings.server.telnet.port.set(8004)
settings.harbor.bind_addrs.set(["0.0.0.0"])

settings.tag.encodings.set(["UTF-8","ISO-8859-1"])
settings.encoder.metadata.export.set(["artist","title","album","song"])

settings.decoder.priorities.ogg.set(15)
settings.decoder.priorities.mad.set(15)
settings.decoder.priorities.flac.set(15)
settings.decoder.priorities.aac.set(15)
settings.decoder.priorities.ffmpeg.set(10)

setenv("TZ", "America/Sao_Paulo")

azuracast_api_auth = ref("(PASSWORD)")
ignore(azuracast_api_auth)

autodj_is_loading = ref(true)
ignore(autodj_is_loading)

autodj_ping_attempts = ref(0)
ignore(autodj_ping_attempts)

playlist_geral = playlist(id="playlist_geral",mode="randomize",reload_mode="watch","/var/azuracast/stations/renovaradio/playlists/playlist_geral.m3u")
playlist_geral = cue_cut(id="cue_playlist_geral", playlist_geral)

playlist_tuga_som = playlist(id="playlist_tuga_som",mode="randomize",reload_mode="watch","/var/azuracast/stations/renovaradio/playlists/playlist_tuga_som.m3u")
playlist_tuga_som = cue_cut(id="cue_playlist_tuga_som", playlist_tuga_som)

playlist_0_10 = playlist(id="playlist_0_10",mode="randomize",reload_mode="watch","/var/azuracast/stations/renovaradio/playlists/playlist_0-10.m3u")
playlist_0_10 = cue_cut(id="cue_playlist_0_10", playlist_0_10)

playlist_playfitas = playlist(id="playlist_playfitas",mode="randomize",reload_mode="watch","/var/azuracast/stations/renovaradio/playlists/playlist_playfitas.m3u")
playlist_playfitas = cue_cut(id="cue_playlist_playfitas", playlist_playfitas)

playlist_eletronicas = mksafe(buffer(buffer=60., input.http(max_buffer=60., "http://104.227.175.125:80/livemix")))

playlist_el_bar_de_moteros = playlist(id="playlist_el_bar_de_moteros",mode="randomize",reload_mode="watch","/var/azuracast/stations/renovaradio/playlists/playlist_el_bar_de_moteros.m3u")
playlist_el_bar_de_moteros = cue_cut(id="cue_playlist_el_bar_de_moteros", playlist_el_bar_de_moteros)

playlist_la_hora_del_relax = playlist(id="playlist_la_hora_del_relax",mode="randomize",reload_mode="watch","/var/azuracast/stations/renovaradio/playlists/playlist_la_hora_del_relax.m3u")
playlist_la_hora_del_relax = cue_cut(id="cue_playlist_la_hora_del_relax", playlist_la_hora_del_relax)

playlist_la_ventana_espanhola = playlist(id="playlist_la_ventana_espanhola",mode="randomize",reload_mode="watch","/var/azuracast/stations/renovaradio/playlists/playlist_la_ventana_espanhola.m3u")
playlist_la_ventana_espanhola = cue_cut(id="cue_playlist_la_ventana_espanhola", playlist_la_ventana_espanhola)

playlist_raizes_do_sertao = playlist(id="playlist_raizes_do_sertao",mode="randomize",reload_mode="watch","/var/azuracast/stations/renovaradio/playlists/playlist_raizes_do_sertão.m3u")
playlist_raizes_do_sertao = cue_cut(id="cue_playlist_raizes_do_sertao", playlist_raizes_do_sertao)

playlist_siempre_ladys = playlist(id="playlist_siempre_ladys",mode="randomize",reload_mode="watch","/var/azuracast/stations/renovaradio/playlists/playlist_siempre_ladys.m3u")
playlist_siempre_ladys = cue_cut(id="cue_playlist_siempre_ladys", playlist_siempre_ladys)

playlist_sertanejo = playlist(id="playlist_sertanejo",mode="randomize",reload_mode="watch","/var/azuracast/stations/renovaradio/playlists/playlist_sertanejo.m3u")
playlist_sertanejo = cue_cut(id="cue_playlist_sertanejo", playlist_sertanejo)

playlist_80s90s = playlist(id="playlist_80s90s",mode="randomize",reload_mode="watch","/var/azuracast/stations/renovaradio/playlists/playlist_80s90s.m3u")
playlist_80s90s = cue_cut(id="cue_playlist_80s90s", playlist_80s90s)

playlist_chamadas = playlist(id="playlist_chamadas",mode="randomize",reload_mode="watch","/var/azuracast/stations/renovaradio/playlists/playlist_chamadas.m3u")
playlist_chamadas = cue_cut(id="cue_playlist_chamadas", playlist_chamadas)
playlist_chamadas = drop_metadata(playlist_chamadas)

playlist_vinhetas = playlist(id="playlist_vinhetas",mode="randomize",reload_mode="watch","/var/azuracast/stations/renovaradio/playlists/playlist_vinhetas.m3u")
playlist_vinhetas = cue_cut(id="cue_playlist_vinhetas", playlist_vinhetas)
playlist_vinhetas = drop_metadata(playlist_vinhetas)

# Standard Playlists
radio = random(id="standard_playlists", weights=[3, 2], [playlist_geral, playlist_sertanejo])

# Standard Schedule Switches

radio = switch(id="schedule_switch", track_sensitive=true, [ ({ (1w) and 14h0m }, playlist_tuga_som), ({ (4w) and 11h10m }, playlist_0_10), ({ (2w) and 12h10m }, playlist_0_10), ({ (5w) and 16h10m }, playlist_playfitas), ({ (0w) and 22h10m }, playlist_playfitas), ({ (3w) and 12h10m }, playlist_el_bar_de_moteros), ({ (5w) and 13h10m }, playlist_el_bar_de_moteros), ({ (6w) and 8h10m }, playlist_el_bar_de_moteros), ({ (6w) and 21h10m }, playlist_la_hora_del_relax), ({ (1w or 5w) and 12h10m }, playlist_la_ventana_espanhola), ({ (4w) and 13h10m }, playlist_la_ventana_espanhola), ({ (0w) and 10h10m }, playlist_raizes_do_sertao), ({ (6w) and 16h10m }, playlist_raizes_do_sertao), ({ (2w or 4w) and 15h50m-18h10m }, playlist_siempre_ladys), ({true}, radio) ])

# Once per x Songs Playlists
radio = rotate(weights=[1,30], [playlist_80s90s, radio])
radio = rotate(weights=[1,15], [playlist_chamadas, radio])
radio = rotate(weights=[1,2], [playlist_vinhetas, radio])

# AutoDJ Next Song Script
def autodj_next_song() =
    uri = list.hd(process.read.lines(env=[("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/1/nextsong --form api_auth="$API_AUTH"'), default="")
    log("AzuraCast Raw Response: #{uri}")

    if uri == "" or string.match(pattern="Error", uri) then
        null()
    else
        r = request.create(uri)
        if request.resolve(r) then
            r
        else
            null()
       end
    end
end

# Delayed ping for AutoDJ Next Song
def wait_for_next_song(autodj)
    autodj_ping_attempts := !autodj_ping_attempts + 1
    delay = ref(0.5)

    if source.is_ready(!autodj) then
        log("AutoDJ is ready!")

        autodj_is_loading := false
        delay := -1.0
    elsif !autodj_ping_attempts > 200 then
        log("AutoDJ could not be initialized within the specified timeout.")

        autodj_is_loading := false
        delay := -1.0
    end

    !delay
end

dynamic = request.dynamic(id="next_song", timeout=20., retry_delay=2., autodj_next_song)
dynamic = cue_cut(id="cue_next_song", dynamic)

dynamic_startup = fallback(
    id = "dynamic_startup",
    track_sensitive = false,
    [
        dynamic,
        source.available(
            blank(id = "autodj_startup_blank", duration = 120.),
            predicate.activates({!autodj_is_loading})
        )
    ]
)
radio = fallback(id="autodj_fallback", track_sensitive = true, [dynamic_startup, radio])

ref_dynamic = ref(dynamic);
thread.run.recurrent(delay=0.25, { wait_for_next_song(ref_dynamic) })

# Interrupting Schedule Switches
radio = switch(id="interrupt_switch", track_sensitive=false, [ ({ 0h15m-7h0m }, playlist_eletronicas), ({true}, radio) ])

requests = request.queue(id="requests")
requests = cue_cut(id="cue_requests", requests)

radio = fallback(id="requests_fallback", track_sensitive = true, [requests, radio])
add_skip_command(radio)

radio = crossfade(smart=false, duration=7.95, fade_out=5.30, fade_in=5.30, radio)

# DJ Authentication
live_enabled = ref(false)
last_authenticated_dj = ref("")
live_dj = ref("")

def dj_auth(login) =
    user = ref("")
    password = ref("")

    if (login.user == "source" or login.user == "") and (string.match(pattern="(:|,)+", login.password)) then
        auth_string = string.split(separator="(:|,)", login.password)

        user := list.nth(default="", auth_string, 0)
        password := list.nth(default="", auth_string, 2)
    else
        user := login.user
        password := login.password
    end

    log("Authenticating DJ: #{!user}")

    ret = list.hd(process.read.lines(env=[("DJ_USER", !user), ("DJ_PASSWORD", !password), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/1/auth --form dj-user="$DJ_USER" --form dj-password="$DJ_PASSWORD" --form api_auth="$API_AUTH"'), default="")
    log("AzuraCast DJ Auth Response: #{ret}")

    authed = bool_of_string(ret)
    if (authed) then
        last_authenticated_dj := !user
    end

    authed
end

def live_connected(header) =
    dj = !last_authenticated_dj
    log("DJ Source connected! Last authenticated DJ: #{dj} - #{header}")

    live_enabled := true
    live_dj := dj

    ret = list.hd(process.read.lines(env=[("DJ_USER", dj), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/1/djon --form dj-user="$DJ_USER" --form api_auth="$API_AUTH"'), default="")
    log("AzuraCast Live Connected Response: #{ret}")
end

def live_disconnected() =
    dj = !live_dj

    log("DJ Source disconnected! Current live DJ: #{dj}")

    ret = list.hd(process.read.lines(env=[("DJ_USER", dj), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/1/djoff --form dj-user="$DJ_USER" --form api_auth="$API_AUTH"'), default="")
    log("AzuraCast Live Disconnected Response: #{ret}")

    live_enabled := false
    last_authenticated_dj := ""
    live_dj := ""
end

# A Pre-DJ source of radio that can be broadcast if needed',
radio_without_live = radio
ignore(radio_without_live)

# Live Broadcasting
live = input.harbor("/", id = "input_streamer", port = 8005, auth = dj_auth, icy = true, icy_metadata_charset = "UTF-8", metadata_charset = "UTF-8", on_connect = live_connected, on_disconnect = live_disconnected)
ignore(output.dummy(live, fallible=true))

radio = fallback(id="live_fallback", replay_metadata=false, track_sensitive=false, [live, radio])

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

# Apply amplification metadata (if supplied)
radio = amplify(override="liq_amplify", 1., radio)

# Normalization and Compression
radio = normalize(target = 0., window = 0.03, gain_min = -16., gain_max = 0., radio)
radio = compress.exponential(radio, mu = 1.0)

# Replaygain Metadata
enable_replaygain_metadata()

radio = fallback(id="safe_fallback", track_sensitive = false, [radio, single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")])

# Send metadata changes back to AzuraCast
def metadata_updated(m) =
    def f() =
        if (m["song_id"] != "") then
            ret = list.hd(process.read.lines(env=[("SONG", m["song_id"]), ("MEDIA", m["media_id"]), ("PLAYLIST", m["playlist_id"]), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/1/feedback --form song="$SONG" --form media="$MEDIA" --form playlist="$PLAYLIST" --form api_auth="$API_AUTH"'), default="")
            log("AzuraCast Feedback Response: #{ret}")
        end
        (-1.)
    end

    thread.run.recurrent(fast=false, delay=0., f)
end

radio.on_metadata(metadata_updated)

# Local Broadcasts
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), id="local_1", host = "127.0.0.1", port = 8000, password = "(PASSWORD)", mount = "/radio.mp3", name = "RenovaRadio", description = "A Renovação Do Som!", genre = "Variado", url = "https://www.renovagames.com/radio", public = false, encoding = "UTF-8", radio)
output.icecast(%fdkaac(channels=2, samplerate=44100, bitrate=32, afterburner=false, aot="mpeg4_he_aac_v2", sbr_mode=true), id="local_2", host = "127.0.0.1", port = 8000, password = "(PASSWORD)", mount = "/radio.aac", name = "RenovaRadio", description = "A Renovação Do Som!", genre = "Variado", url = "https://www.renovagames.com/radio", public = true, encoding = "UTF-8", radio)

# Remote Relays

**Comment by nunotfc** [comment]
hello! it passed some days sinse i posted my config. is something wrong? i am doing something wrong in my config or you can confirm that it is really a bug? thanks!

**Comment by inetactief** [comment]
I have about the same problem.  

the now playing work fine using the autodj. But not when there is DJ live.

**Comment by nunotfc** [comment]
update:
now, the problem is the described, and annoter.
whe you are live and even if you send metadata, it doesnt change, no mather what song is being played, like a jingle playlist.
when you stop streaming, have to wait  to actual auto dj song ends, like i descrived.

**Comment by nunotfc** [comment]
hello! i dont want to press the developers or so. i just want to ask, some news about this bug? some ishue of ls i can follow? thank you all and congratulations for all work done!

**Comment by nunotfc** [comment]
thhe latest commit skiping song after dj terminates doesnt fix this ishue. and, my sinser opinion, i dont like it so much.

**Comment by nunotfc** [comment]
hello, some news about this problem by ls part? thanks!

**Comment by inetactief** [comment]
Yes... i see there is no update.. holidays?

**Comment by SC2Mitch** [comment]
This should be a lot better with the latest commits, can you update and try them?

**Comment by nunotfc** [comment]
the bug i mentioned doesnt fix.
for reproducing this bug:
1. go broadcast;
2. close stream;
3. See now playing.
it will not change untill the actual auto dj song ends.
was made a try to change automatically to the next auto dj song when live broadcast ends, but not worked also.

**Comment by nunotfc** [comment]
hello, any new?

**Comment by bilalbox** [comment]
I am also facing this issue on our installation when DJ's begin live streaming. Do you think we could just run whatever liquidsoap function sets the metadata from the songhistory? I've been trying to parse the liquidsoap code but unsure which one sets the metadata on song change or broadcast and also unsure where to attempt to insert the override in the liquidsoap config. Anyone know exactly which function performs the metadata update?

Thanks!

**Comment by ArvyRogerio** [comment]
@nunotfc

`playlist_eletronicas = mksafe(buffer(buffer=60., input.http(max_buffer=60., "http://104.227.175.125:80/livemix")))`

Must be :

`playlist_eletronicas = mksafe(buffer(buffer=60., input.http(max_buffer=60., "http://streaming.inweb.com.br:80/livemix")))`

You're re-broadcasting my webradio. Contact us at www.livemix.com.br. Found this topic looking for my IP on Google.

**Comment by nunotfc** [comment]
olá, vou falar em português, peço desculpa pelo inconveniente causado. eu estou retransmitindo com sua autorização, eu enviei mensagem no facebook perguntando sobre isso e me deixaram avontade para fazer. foi mias ou menos na data que criei este ishue aqui no github do azura
