### ISSUE TITLE
Sftp connection

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#483]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Debian 9

**Describe the issue in full detail, including screenshots if possible:**

I want to manage my media trough wincsp sftp connection.

Can you be more clear how to use this method ?

docker run --rm \
    -v azuracast_station_data:/home/azuracast/stations \
    -p 2222:22 atmoz/sftp:alpine \
    azuracast:azuracast:::stations

I already use another port for ssh and i have more then 1 station.
How to make the connection with other port nr then 22 and how to accest the desired station, like radio1 radio2 .Can i use to login in winscp with root and pass i already have for the vps or is there another pass word created for the sftp connection?

**Comment by SlvrEagle23** [comment]
@surihost I've added clarification to the support document to explain how the command relates to the SFTP service that it exposes:

https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#access-files-via-sftp-docker-installations

Hopefully this answers your questions.

**Comment by surihost** [comment]
Thanks this is very clear and was able to connect and acces the mediafiles.
What i notice that after the session Ctrl + C doesnt work to disconnect the session.

**Comment by TogarUshindi** [comment]
I'm noticing the same problem. Ctrl+C is not disconnecting the session in terminal. There's another thread with someone mentioning the same problem.
