### ISSUE TITLE
Impossible to start my station 

### ISSUE THREAD

**Issue by aarkkappler** [AzuraCast/AzuraCast#4831]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #ebf631f (2021-12-01 2:14) 

### What happened?

<img width="592" alt="Capture d’écran 2021-12-01 à 23 00 50" src="https://user-images.githubusercontent.com/9117901/144321946-dd588c4c-e01b-4993-9c0f-842e742601a9.png">

**Comment by SlvrEagle23** [comment]
@aarkkappler Same response if you run `Utilities` > `Restart Broadcasting`?

**Comment by aarkkappler** [comment]
yes

**Comment by aarkkappler** [comment]
is it possible for you to take the control and see what's happening ?

**Comment by andrejcarlo** [comment]
![image](https://user-images.githubusercontent.com/37040215/144422904-e540ac21-4197-4af5-a54a-cd4e907536ff.png)
Same here, starting up services resulting in an error on self-hosted vultr installation after updating to the latest release.

**Comment by SlvrEagle23** [comment]
@andrejcarlo That's likely an unrelated issue, as evidenced by the fact that the original report here is a screenshot from within the web UI and yours is a screenshot from a terminal of a different issue. It likely merits being its own GitHub issue, though my recommendation in this case would be to run the updater again, as that often resolves similar issues.

**Comment by aarkkappler** [comment]
Hi, Are you talking about that ? <img width="522" alt="Capture d’écran 2021-12-02 à 18 03 51" src="https://user-images.githubusercontent.com/9117901/144468946-26d04866-dc83-468a-b149-26218475941c.png">

Still an issue

**Comment by SlvrEagle23** [comment]
@aarkkappler That's also an unrelated issue, but probably merits its own GitHub issue.
