### ISSUE TITLE
when are 2 playlists with jingle mode enabled, one reveals the name of the previous.

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#4832]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

ebf631f (2021-12-01 2:14) • Docker • PHP 8.0

### What happened?

hello,
I have 2 playlists. one of jingles, annoter of promos of the live programs. Both with jingle mode enabled
my promos playlist is configured to play after every 15 songs.
when appens to play one jingle and, after one promo, when promo is playing the name of the previous jingle is revealed.
for example:
consider playing spot_radio1 and promo_music mix
when two plays one after the oter, when playing music_mix the now playing shows the name of spot_1 even with jingle mode enabled.
I hope i explained better.

**Comment by Abqehebter** [comment]
I thought the problem was fixed? Also, I can no longer reproduce it. It is fixed for me. See issue: https://github.com/AzuraCast/AzuraCast/issues/4774

**Comment by nunotfc** [comment]
@Abqehebter 
this is annoter variant of the problem.
the ishue you referenced is mine also, but this is nnoter problem.
the problem now is just when you have 2 tracks of 2 jingle playlist playing one after the oter that this appens. 
if you couldnt understand right what i mean, feel free to say, i try to explain again.
the oter problem is a litle bit different than this one.

**Comment by Abqehebter** [comment]
I understand it now. Thank you. I can see if I can trigger something similar on my test instance. Later.

**Comment by nunotfc** [comment]
Thanks

**Comment by Abqehebter** [comment]
Many thanks to @SlvrEagle23 for fixing it!
I did not get around to triggering the error. But with my instance, probably not much would have happened anyway.

**Comment by nunotfc** [comment]
with last commit, the original bug returned back.
one playlist plays the promo, and when oter is played back back song is showed.

**Comment by nunotfc** [comment]
played "eduardo costa primeiro de abril."
played "Irene Cara - Fame"
played "renovaradio promo siempre ladies." showed "Irene Cara - Fame"
played renovaradio promo only here but showed "eduardo costa primeiro de abril" expected is continue to show "Irene Cara - Fame"

**Comment by Countryman98** [comment]
can confirm issue is still ongoing.

**Comment by SlvrEagle23** [comment]
I can no longer verify this issue locally; with the very latest commit, my local tests show that the annotation process works correctly.

You may not be seeing the correct results immediately upon the station starting up, but once it's had a chance to iterate through the queue at least once, it should be working as expected.

If it's not, we'll need to look at your specific setup to determine why that's the case, or at the very least to look at your logs.

**Comment by nunotfc** [comment]
if i rebuild the queue of all playlists it can help?

**Comment by nunotfc** [comment]
if you need i can give you ssh access to my server. i think really i have some problem with my setup because of oter problem about go live and when return back to autodj my metadata is not changing until the autodj song not end.

**Comment by nunotfc** [comment]
I really believe i have some problem with my config or something, because of oter problem of going live and when returning to autodj metadata not changing untill the song not end in autodj. i  can give you access via ssh if you need.

**Comment by SlvrEagle23** [comment]
@nunotfc That's a different issue, and we're working upstream with Liquidsoap to get that figured out, but we don't have any update on that front just yet.

If you want to send me your server's information (i.e. via Discord), that would be fine, but I can't guarantee that I can get back to it immediately.

**Comment by nunotfc** [comment]
ok i will see if the bug appens again and if yes, i will send you my server. how can i do thath? i tried but dm cant be delivered.

**Comment by nunotfc** [comment]
ok, the bug appens all the time.
sometimes dont need to be jingle playlist, the metadata shows the back back song for 1 sdeccond.
what i can do to give access to developers investigate it?

**Comment by nunotfc** [comment]
fixed.
