### ISSUE TITLE
Flood of notifications on the listeners page

### ISSUE THREAD

**Issue by dougllasvieira** [AzuraCast/AzuraCast#4836]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#369e7fe (2021-10-15 17:51)

### What happened?

Hi.
The listeners report page seems to accumulate notifications of getting listeners, even crashing the browser tab, in a station with many listener. Usually this accumulation of notifications happens when the user changes the tab, and after 4 minutes returns to the azuracast page.
I noticed this from the last update, I didn't have it before.

![bug listeners](https://user-images.githubusercontent.com/49848275/144719759-4a1d8389-3d4f-42c6-bead-20d6a1b61997.png)
s.

**Comment by Abqehebter** [comment]
Unfortunately, not only on the Listeners page, also on other pages and/or actions. That would be cool if you could reduce them.

**Comment by SlvrEagle23** [comment]
This is caused by the fact that if you're not focused on the window, notifications will just pile up until you return to the window, when they will all appear at once. I've pushed an update that should reduce the number of notifications that appear.
