### ISSUE TITLE
ERROR INSTALL  - Ubuntu Server 14.04

### ISSUE THREAD

**Issue by titorjav89** [AzuraCast/AzuraCast#484]
- **Installation Method:** 
- **Host OS (if using Docker):** 

**Describe the issue in full detail, including screenshots if possible:**

HELP Ubuntu Server 14.04
ERROR INSTALL 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to validate the SSL certificate for repos.influxdata.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine  (the python executable used (/usr/bin/python) is version: 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]) or you can install the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure."}

**Comment by SlvrEagle23** [comment]
@titorjav89 Ubuntu 14.04 is not supported for this exact reason: it doesn't carry a new enough version of Python to support HTTPS connections with SNI, which a number of packages in AzuraCast depend on, and the PPA to upgrade its internal version of Python ("Deadsnakes") was recently retired.

At this point, with 16.04 still in active maintenance and 18.04 coming out soon, I highly recommend switching to a newer version of Ubuntu Server LTS.
