### ISSUE TITLE
Advanced Playlists don't work

### ISSUE THREAD

**Issue by Crissweb73** [AzuraCast/AzuraCast#4844]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.14.1 Stable • Docker • PHP 8.0

### What happened?

Hello everyone, my goal is to make 2 playlists always play close to each other but I can't, I copied this string in the advanced settings recreating the playlists with the same names but it doesn't work, why
![Playlist](https://user-images.githubusercontent.com/95681862/145000408-b9663da5-ed50-4dbf-a4fc-6f2da3fed5ef.PNG)
![stringa](https://user-images.githubusercontent.com/95681862/145000446-68f86ef1-fc59-46b9-ad5f-b55a25bb7721.PNG)

**Comment by Abqehebter** [comment]
This is the wrong configuration page. You are in the Icecast config and not in the Liquidsoap config.

See: Utilities > Edit Liquidsoap Configuration

**Comment by Crissweb73** [comment]
thanks for the answer liam so the string to copy in the playlist section is this one without weights:
radio = [playlist_commercials, playlist_bumpers, radio
![liquid](https://user-images.githubusercontent.com/95681862/145006065-9a007de6-f71b-452f-8a39-4122f89e7c14.PNG)
])

**Comment by elpglenn1** [comment]
I'm having trouble here as well. According to the docs, you should be updating this under the station profile, however, azuracast seems to ignore the commands here. It doesn't even show in the logs. Did you have any luck?
