### ISSUE TITLE
ishue #4832 not fully fixed

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#4847]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

03c54e0 (2021-12-08 10:10) • Docker • PHP 8.0

### What happened?

hello,
the ishue #4832 is not fully fixed.
but now, the bug is diferent.
when you have 2 jingle playlist playing togeter, the metadata is not hiden.
skiping songs doesnt work, you have to wait.
i have one jingle playlist every 2 songs, and annother every 15.
when the two play together, you doesnt see the song before as previous. but, you see the metadata of the playlist.
the expected behaviour is to not show it.
if i can explain more, p'lease let me know.

**Comment by Countryman98** [comment]
Yeah, i thought problem was fixed too but alas still happening..  Also finding that "Playlist Scheduling" is not being honored.
Details:
Rolling Release #03c54e0 (2021-12-08 10:10) • Docker • PHP 8.0

Problems we not occurring in Stable release but somehow updated to Rolling Release. Is there any way to return to Stable release without re-installing?

**Comment by SC2Mitch** [comment]
Only way to return safely is to use a backup. If you don't then that's unfortunately on you as we do tell people to keep snapshots and backups.

**Comment by Countryman98** [comment]
> Only way to return safely is to use a backup. If you don't then that's unfortunately on you as we do tell people to keep snapshots and backups.

Thanks Sc2Mitch, Have auto backups but unfortunately is backed up the rolling release. Thanks for all your guys hard work and continued dedication :)

**Comment by SlvrEagle23** [comment]
@nunotfc Since you had created the previous issue, you can just directly reopen it if it's not fixed. I have identified a problem with the previous fix and will be publishing a new one shortly.

**Comment by nunotfc** [comment]
many thanks and sorry! I didnt know about this before. and also thanks for fixing!

**Comment by Countryman98** [comment]
Unfortunately the issue it still occurring for my Azuracast Setup..  Seem's to play up when you are logged in an configuring the dashboard songs/stuff in General while Autodj's playing Live.

Doesn't actually play the physical song but shows it as being played twice in the "On the "Air Dashboard" section and Also in the "History API"

Jingles/Sweepers/Adds/Ad's are on another level. Metadata is now hidden but the :Ji. but the Jingles/Sweepers/Add's etc definitely do not honor their schedules. These are currently "out the gate".

Details:  • Rolling Release #fe4cdaa (2021-12-09 11:35) • Docker  • Rolling Release #fe4cdaa (2021-12-09 11:35) • Docker • PHP 8.0 PHP 8.0  • Ubuntu 20.04.1  • Dedicated 8 core / 16GB /TB-SSD  •

**Comment by SC2Mitch** [comment]
Create a new issue please.
