### ISSUE TITLE
some of the response messages aren't localized properly

### ISSUE THREAD

**Issue by FrancescaBoninhb** [AzuraCast/AzuraCast#4848]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #266305e (2021-11-18 18:57)

### What happened?

There is something weird happening with success messages. I would like to understand if this is the result of a wrong configuration of AzuraCast done on my end or if it’s a bug. As I have  understood from this thread https://github.com/AzuraCast/AzuraCast/issues/335, if the browser’s first language is set to Italian, success messages will be shown in Italian (i.e. in your local language ).
Indeed when you shuffle or disable a playlist, the formatted_message received from the api is in Italian. However, other messages are still shown in English such as when restarting the broadcast (../backend/restart), renaming a folder (../files/rename) or editing a media file (../file/102). 
Why aren’t all formatted_message shown in Italian?

**Comment by roger-net** [comment]
I believe this is because the translation into Italian is incomplete, according to Crowdin it is 56% translated and when there are no translations Azuracast shows in English.

**Comment by SC2Mitch** [comment]
Roger is correct, the strings aren't fully translated and thus, it'll only show the English version if there's no translations available. 

If you wish to contribute then by all means, we welcome them. https://crowdin.com/translate/azuracast

**Comment by SlvrEagle23** [comment]
Did a review of the status messages and they are all intended to be localized, we just may not have translations in the system for them yet.
