### ISSUE TITLE
Reconfigure Ngnix ?

### ISSUE THREAD

**Issue by LazosPlaying** [AzuraCast/AzuraCast#486]
- **Installation Method:**
Docker

- **Host OS (if using Docker):**
Ubuntu 16.04

**Describe the issue in full detail, including screenshots if possible:**
Hello! I'd like to know where to reconfigure the main host config for ngnix. I mean... I'm new to that, since I personally use Apache2, and I installed ngnix just because of AzuraCast. Now, if using the default domain, i access the admin panel, how can I change that ? 

I searched for config files, but there is no /etc/ngnix/ directory, which confuses me a bit.

Is it even possible, or I'll have to redo the whole process ?

Thank you in advance for any info.
Regards,
~Aljaz

**Comment by SlvrEagle23** [comment]
@LazosPlaying The Docker installation method is meant to provide you with a fully provisioned, ready-to-go instance of the full stack needed to run the software, including nginx. That means the configuration is already included with the Docker image that you pull down during installation; while it can be customized, it's not necessarily meant to be customized heavily.

If you're more familiar with Apache, you can always install Apache on your host computer and just proxy traffic through it to AzuraCast based on virtual name routing rules, while reserving other virtual names for other domains served off the same server.
