### ISSUE TITLE
Help finding the static dir

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#4863]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.14.1 Stable 

### What happened?

I'm migrating from Ansible to Docker.
Docker is NIGHTMARE!
Please, tell me where to find the www/web/static folder...
I've built custom scripts and i want to continue to use them.
I've been searching more than a hour, 30 min browsing dirs, and 30 min browsing in google.
I'm so mad of these containers, they took 1gb of ram only for the docker processes.
1 running station on Ansible with ubuntu 20.04.3 is using ~600mb ram
1 running station on Docker with ubuntu 20.04.3 is using ~1.2gb ram
I'm so close to delete that docker, and install it via Ansible, i was so happy when everything works native, but you always says that you don't support Ansible.
Anyways, Docker is NIGHTMARE!

Please tell me how to reach that folder and close the issue.

**Comment by SC2Mitch** [comment]
Nobody forced you to move to Docker and I ask that you don't use threatening vibes such as 'I'm so close to deleting Docker and installing via Ansible'. If that system works fine for you, then use it. But expect that you will not be given support. 

The path you seek is in `/lib/var/docker/volumes` and it'll be within that nest. 

Please take into consideration that AzuraCast is maintained by a team of volunteers so demanding and getting angry over things is extremely stressful on our volunteer team, cheers.

**Comment by NicoxDJ** [comment]
@SC2Mitch
1st - That looks pretty much forcing to me:
![](https://i.imgur.com/Q30W3IG.png)

2nd 
> ... threatening vibes...
> ... extremely stressful ...
Really? Are you what, 5 years old? We are developers, we live with the stress 24/7. :)

3rd - After 5 hours of searching i found it, but on different place:
`/var/lib/docker/overlay2/2512b01124c2ad552c947e672c4dec87e660764002de8b65573bc46aa3fb0e09/merged/var/azuracast/www/web/static/`
The specific web volume is missing in `/lib/var/docker/volumes`
And actually, after uploading my scripts there, they appear when i check them with `docker exec -it azuracast_web ls -l web/static/`, BUT when i try to access them it's still 404...

No bad vibes dude, i'm just pissed because i'm trying to make changes for good, but nothing works as it supposed to work.

**Comment by SlvrEagle23** [comment]
@NicoxDJ Two things:

We have a long set of documentation for Docker including how to inject custom scripts into the Docker volumes, so you don't need to directly edit the Docker volumes themselves, and so your changes will persist across updates: https://docs.azuracast.com/en/administration/docker#mounting-a-directory-into-a-station

Secondly,

> We are developers, we live with the stress 24/7.

There is not much that is good about being an open-source developer. The hours are long, the pay isn't great, and the stress is indeed always there.

But the one thing we can do is decide simply _not_ to put up with things. That's not a liberty any boss would give you.

When we insist you treat us with kindness and respect, this is our way of saying we won't put up with you transferring any more stress to us than is absolutely necessary. Life is hard, so we give something away to help make it better. Don't make our lives harder as a thank-you for doing that.

**Comment by NicoxDJ** [comment]
@SlvrEagle23 well than, sorry if you feel it in that way.
As i said in the above comment `No bad vibes...`

Anyway, thanks for the link, maybe someday i will need to use it. I already remove the docker and install AzuraCast via Ansible. I really like to have more native access/control to everything. But all warnings and 'unsupported' labels are frustrating me, that someday you will stop update the installation and i have to start again from the beginning. And i want confirm, that there is really better performance on Ansible. The RAM usage drop with 500-600MB since docker. Maybe i did wrong when i allowed all default ports to proxy to the default address. It was like a thousand processes.

**Comment by SlvrEagle23** [comment]
@NicoxDJ I wouldn't be worried about it, especially in the immediate term. We have nothing against Ansible, but the warnings are largely to discourage people who aren't familiar with Linux server administration from using the more complicated setup.
