### ISSUE TITLE
Station not found ?

### ISSUE THREAD

**Issue by LazosPlaying** [AzuraCast/AzuraCast#487]
- **Installation Method:**
Docker

- **Host OS (if using Docker):**
Ubuntu 16.04

**Describe the issue in full detail, including screenshots if possible:**
I am getting the 
```
500
Station not found!
PublicController.php : 38
```
Error all the time. Any know reason ?

**Comment by SlvrEagle23** [comment]
@LazosPlaying Are you using the station's ID number in the URL, or its shortcode? Also, does the shortcode have any unusual symbols in it?

**Comment by LazosPlaying** [comment]
Well... The address given when you click on it on the admin panel. Pretty sure it's an uid, not an id...

**Comment by LazosPlaying** [comment]
Also, would you happen to know how to fix the issue where you can not access a particular domain, but you can access it though a proxy ?

**Comment by LazosPlaying** [comment]
**back on the main topic**
Also when using the station ID (in my case 1, since it's the only one) the error still apears

**Comment by SlvrEagle23** [comment]
@LazosPlaying Did you upgrade your Docker installation from an earlier version? You may need to edit your station's profile, ensuring the "short name" field is supplied and the "show on public pages" setting is set. It's not common, but some version updates can miss those fields.

**Comment by LazosPlaying** [comment]
No. It's a fresh install. From like 2pm UTC

**Comment by SlvrEagle23** [comment]
@LazosPlaying Not sure what the problem is, then. Provided the "Advanced: Station URL Stub" field is set properly (and isn't, itself, set to a number) things should work fine.

**Comment by LazosPlaying** [comment]
And how do I do that ?

**Comment by SlvrEagle23** [comment]
@LazosPlaying It's in the station's profile page. You can edit it by clicking "Manage" next to the station, then "Profile" on the left sidebar, then editing the profile. It's near the top.

**Comment by LazosPlaying** [comment]
Alright, that worked !

Also, do you have any idea about [this](https://github.com/AzuraCast/AzuraCast/issues/487#issuecomment-373158295) (the DNS issue)?

I'd really like to fix that, because if not I have to use a proxy and that's a bit slow...

**Comment by SlvrEagle23** [comment]
@LazosPlaying What do you mean, accessing the site through a proxy? Do you mean the main site itself, through port 80? That definitely shouldn't be happening.

**Comment by LazosPlaying** [comment]
The issue is that I accessed the domain before the name server change (I switched from my registrar to CloudFlare) so the DNS got cached. And how it does not want to update. The server works, everything works, except me accessing the domain (anything. Plain root domain) does not work.

Do you know any way to fix it?

It'd be a very good thing :/

**Comment by SlvrEagle23** [comment]
@LazosPlaying If you're on Windows, open the command line and run `ipconfig /flushdns` and that should help.

**Comment by LazosPlaying** [comment]
[Well...](https://prnt.sc/irbdrw)

**Comment by LazosPlaying** [comment]
I mean.... I did that already, I tried changing to manual DNS servers (used Google's DNS), but nothing works :/

**Comment by SlvrEagle23** [comment]
@LazosPlaying This could just be a matter of waiting on DNS propagation to kick in, which can take upwards of 48 hours.

You can also manually update your hosts file.

The issue appears to be on your end, as I can reach the domain name from my end.
