### ISSUE TITLE
Problem with Remote Relay Screen

### ISSUE THREAD

**Issue by Maaano** [AzuraCast/AzuraCast#4879]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.14.1

### What happened?

I can't see anymore my remote relays on the remote relay screen, it is stuck on the loading animation.
Streaming to remote relays is OK, I can hear the music, but I can't manage them.

![Remote relays screen](https://user-images.githubusercontent.com/96140101/146054020-1833afe5-87b7-4429-b16a-290e209201e2.png)
.

**Comment by Maaano** [comment]
Can't find any error.. It works when I have only 1 remote relays but as soon as I try to have multiple, I'm stuck with the loading.
I specify that I changed the source number in my Icecast.xml and so it is not 2 as set up by default.

**Comment by SlvrEagle23** [comment]
@Maaano If the page isn't loading, you should certainly see an error if you hit F12 on your browser (or right-click and "Inspect Element"), then go to the "Network" tab, then reload the page. You should see a request that comes back in red, which you can click, then click "Response" to see the details.

**Comment by superlinuxero** [comment]
Same problem here today

**Comment by SlvrEagle23** [comment]
@superlinuxero Check the browser console (F12), then the "Network" tab...you should see a request that lights up in red, possibly that returns a 500...the body of that response should help us out.

**Comment by superlinuxero** [comment]
I'm so sorry but I couldn't wait since this was a running station and the customer got nervous. I had to restore the system.
