### ISSUE TITLE
HELP Please

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#488]
anyone knows or can give a sample script to get this API data like Live DJ stream sothat i can make it display in a website? i really struggling for this one. thanks in advance.

**Comment by mkody** [comment]
Hi, 
You can find the documentation for the API there: http://azuracast.com/api/

What you seem to be interested is about the "now playing" data. Here's an example for accessing the DJ information and the current title.

> Note, I'll use `demo.azuracast.com` as the site url and `1` as the station ID.  
> Make sure to use your own.

The API path you want to query is `/api/newplaying/1` (if `1` is you station ID).  
The full URL would be: `https://demo.azuracast.com/api/nowplaying/1`.

To get that with Javascript:
```javascript
// API Endpoint
var url = 'https://demo.azuracast.com/api/nowplaying/1'

// Fetch the remote file
fetch(url)
  .then(function (request) {
    // Take the request and parse the data as json
    return request.json()  
  })
  .then(function (json) {
    // Now we extract the values we want
    var live = json.live.is_live           // "true" if it is live
    var streamer = json.live.streamer_name // name of the streamer
    var title = json.now_playing.song.text // current song title

    // Here you can put the code that will
    // display those three values on the webpage,
    // like with jQuery or something...
  })
```

Here's for PHP:
```php
<?php
// API Endpoint
$url = 'https://demo.azuracast.com/api/nowplaying/1';

// Fetch and parse data
$content = file_get_contents($url);
$data = json_decode($content);

$live = $data['live']['is_live'];          // "true" if it is live
$streamer = $data['live']['streamer_name'];    // name of the streamer
$title = $data['now_playing']['song']['text']; // current song title

// And then you use those three values on your page,
// or send back a JSON or anything you need...
```

Feel free to search about how to display those values on your website online, as this will fall out of scope of this project. :wink:

**Comment by reans** [comment]
@mkody thank you so much.

**Comment by preterive** [comment]
php don't work

**Comment by SlvrEagle23** [comment]
@preterive This issue is closed, and your issue doesn't seem to relate to it. Please create a new issue if you need help.

**Comment by preterive** [comment]
$data = json_decode($content, true); is the correct

**Comment by shiftgraphix** [comment]
I know this is old, but I was working on this today and I thought I might help someone in the future, 

Here is a script I made to show your 'Now Playing' info on your site.

`<script>

fetch('https://radio.japademy.io/api/nowplaying/japademy_radio')
  .then(response => response.json())
  .then(data => {
    let streamer = data.live.streamer_name;
    let title = data.now_playing.song.title;
    let artist = data.now_playing.song.artist;
    document.getElementById("streamer").innerHTML = streamer;
    document.getElementById("title").innerHTML = title;
    document.getElementById("artist").innerHTML = artist;
  })
  
</script>

 <h3>Now Playing:  <span id="artist"> </span> - <span id="title"> </span></h3>
  <h3>Current Streamer: <span id="streamer"></span> </h3>`
  
  
   You can edit it to suite what you want.

**Comment by shiftgraphix** [comment]
I know this is old, but I was working on this today and I thought I might help someone in the future, 

Here is a javascript I made to show your 'Now Playing' info on your site.  You can edit it to suit what you want. 

```
<script>

fetch('https://your-azuracast-url/api/nowplaying')
  .then(response => response.json())
  .then(data => {
    let streamer = data.live.streamer_name;
    let title = data.now_playing.song.title;
    let artist = data.now_playing.song.artist;
    document.getElementById("streamer").innerHTML = streamer;
    document.getElementById("title").innerHTML = title;
    document.getElementById("artist").innerHTML = artist;
  })
  
</script>

//display results
 <h3>Now Playing:  <span id="artist"> </span> - <span id="title"> </span></h3>
  <h3>Current Streamer: <span id="streamer"></span> </h3>```
