### ISSUE TITLE
ARM64 (oracle VPS) Docker install not working 404

### ISSUE THREAD

**Issue by cybercuate** [AzuraCast/AzuraCast#4882]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Using the ARM based oracle VPS I get this error
"Docker Compose does not appear to be installed error... 404"

Checking installation requirements for AzuraCast...
[PASS] Operating System: Linux
[PASS] Architecture: aarch64
[PASS] Command Present: curl
[PASS] Command Present: awk
[PASS] User Permissions
[PASS] Installation Directory
[PASS] All requirements met!
Docker is already installed! Continuing...
Docker Compose does not appear to be installed. Install Docker Compose now? [Y/n] y
curl: (22) The requested URL returned error: 404
chmod: cannot access '/usr/local/bin/docker-compose': No such file or directory
Prefer stable release versions of AzuraCast? [y/N] n
./docker.sh: line 349: docker-compose: command not found
./docker.sh: line 350: docker-compose: command not found
./docker.sh: line 407: docker-compose: command not found
./docker.sh: line 408: docker-compose: command not found
./docker.sh: line 409: docker-compose: command not found

it appears that the URL to get docker compose is obsolete because I can install docker compose on this vps using other methods. But please check it and contact docker to update their terminal commands

**Comment by cybercuate** [comment]
anyways, running this makes it work

sudo curl -L https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

and installation works and is up and running. Thanks, you are amazing Azuracast team

**Comment by SlvrEagle23** [comment]
Docker Compose has changed a little bit in its latest version, but I was able to rewrite the installer for new users to use the new format with compatibility for the older command format. This should work just fine on Arm64 devices too.

**Comment by RME-Systems** [comment]
Hi, I have the same problem. I did the process again and it does not work for me. i have the same vps arm 64, ubuntu 20.04

**Comment by SlvrEagle23** [comment]
@RME-Systems If you run `./docker.sh update-self`, the installer should run without any issue now.

**Comment by RME-Systems** [comment]
@SlvrEagle23 i updated, but it doesn't work for me. 404 error no longer displayed, but no download. I solved it with @cybercuate commands
