### ISSUE TITLE
S3 : Error when creating a folder from the UI

### ISSUE THREAD

**Issue by Shaltz** [AzuraCast/AzuraCast#4883]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.14.1

### What happened?

Hi, 

I moved my radio to S3 (on AWS) for media storage, but now I am facing an issue when trying to create a folder
from the azuracast UI (Manage > Music Files > New Folder). 
Uploading a music file works perfectly, but trying to create a folder (prefix in S3 term) fails with this error in the azuracast UI:

```shell
League\Flysystem\UnableToWriteFile at /var/azuracast/www/vendor/league/flysystem/src/UnableToWriteFile.php L24: Unable to write file at location: test3/.
```

I have tried to create a folder directly from the AWS console, it works fine, no bucket policy seem to block the process. Plus once created, I can see and delete the folder from the azuracast UI. I just can't create one :/

any idea ?

thanks in advance ;)

### Relevant log output

via Azuracast Application Log
```shell
[2021-12-15T17:45:07.705588+00:00] AzuraCast.ERROR: Unable to write file at location: test3/. {"file":"/var/azuracast/www/vendor/league/flysystem/src/UnableToWriteFile.php","line":24,"code":0} []
```

via docker-compose logs -f
```shell
nginx_proxy                | nginx.1     | radio.somewhere.net 15.1.2.3 - - [15/Dec/2021:18:02:15 +0000] "POST /api/station/1/files/mkdir HTTP/2.0" 500 397 "https://radio.somewhere.net/station/1/files" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0"

```

**Comment by Shaltz** [comment]
PS: restarting the station, docker or even the instance doesn't sort the problem...

**Comment by elpglenn1** [comment]
This sounds like a permissions issue within AWS. You can adjust the account associated with your azuracast instance under the IAM management console.

**Comment by Shaltz** [comment]
Hi, 
thanks for your reply. 

It does,indeed, sound like a permission issue but I check that before posting.
As I stated in the original post, I am able to create (upload) files to S3 from azuracast UI, 
that means there are no restrictions for me to create a folder.

When using the S3 protocol, a folder is not an object as it would be on a block storage device (like a hard disk drive), it's just a prefix added to the name of the file uploaded to the bucket, meaning that if I have the permissions to upload a file, I have the permissions to create a "folder".

Anyways, to make sure of this I did try to modify the policy added to the role used by my instance to ease up the security a bit, and the result ended up the same, uploading of files is possible but not creation of folders.

For the sake of completeness, here is the policy :

![s3-policy](https://user-images.githubusercontent.com/10232812/146384848-c18eef2d-90fe-493c-bba1-e23aaffb9cff.png)

thanks anyway for your help, but unfortunately I still think that the issue is on azuracast end, not AWS...

**Comment by elpglenn1** [comment]
You're right about your permissions. I think you're also right about azuracast. They just need to update the upload flow to allow for "creating a folder" while uploading a file since folders don't exist in AWS. The AWS console allows it because it creates a "fake" file as a placeholder but I'm not sure that the API or CLI can support that.

**Comment by Shaltz** [comment]
hi again, 
no worries ;)

I think you right too about the "create a folder" flow that needs updating...

Hopefully that will be sorted soon, in the meantime I can always created folders
from the AWS console and use them from the azuracast UI... 
it's not the most comfortable way of using them, but it works ^^

thanks anyways for taking the time to look into this ;)

**Comment by SlvrEagle23** [comment]
@Shaltz This may be fixed in the latest Rolling Release version. We updated our underlying Flysystem library and their newest version changed how they handle directories.
