### ISSUE TITLE
Hiding metadata in playlist shows previous song played

### ISSUE THREAD

**Issue by elpglenn1** [AzuraCast/AzuraCast#4884]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #ab44e41 (2021-11-12 1:30)

### What happened?

Once you select "Hide Metadata from Listeners ("Jingle Mode")" in the source menu of editing a playlist, the metadata for the associated tracks is hidden, however, the player displays and the log prints the song that was played previous to the song before the track with hidden metadata (example playlist (latest song played to oldest song played): track with hidden metadata, track b, track a | track with hidden metadata is showing track a info).

**Comment by SlvrEagle23** [comment]
@elpglenn1 This was fixed in late November. Update your Rolling Release version and you should be all set.

**Comment by elpglenn1** [comment]
Thanks! I'll test it out.
