### ISSUE TITLE
Azuracast does not install

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#4889]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

I tried to install the stable version on a vps but I'm not getting it because an error appears. In this same vps the rolling version was installed, I formatted the vps to install the stable but I can't, I tried to install the rolling version again without success. I followed all the installation steps as instructed on the Azuracast website.

### Relevant log output

```shell
./docker.sh: line 356: docker-compose: command not found
./docker.sh: line 357: docker-compose: command not found
./docker.sh: line 404: docker-compose: command not found
./docker.sh: line 405: docker-compose: command not found
./docker.sh: line 406: docker-compose: command not found
```

**Comment by Abqehebter** [comment]
Try to install docker-compose manually:

`sudo apt-get install docker-compose`

**Comment by roger-net** [comment]
@Abqehebter Thanks for the help, it worked. Hugs.
