### ISSUE TITLE
error connecting to sftp

### ISSUE THREAD

**Issue by RME-Systems** [AzuraCast/AzuraCast#4891]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #958d9cf (2021-12-17 7:20) • Docker • PHP 8.1

### What happened?

When I try to connect to sftp using FileZilla I get the following error:
Status: Connecting to radio.rmesystems.com:2222 ...
Response: fzSftp started, protocol_version = 11
Command: keyfile "C: \ Users \ rodrigo \ Downloads \ vps1 \ priv.key"
Command: open "autodj@radio.rmesystems.com" 2222
Error: Connection timed out after 20 seconds of inactivity
Error: Could not connect to server
Status: Waiting to retry ...
Status: Connecting to radio.rmesystems.com:2222 ...
Response: fzSftp started, protocol_version = 11
Command: keyfile "C: \ Users \ rodrigo \ Downloads \ vps1 \ priv.key"
Command: open "autodj@radio.rmesystems.com" 2222
Error: Connection timed out after 20 seconds of inactivity
Error: Could not connect to server
Status: Disconnected from server
Status: Connecting to 144.22.141.167:2222 ...
Response: fzSftp started, protocol_version = 11
Command: keyfile "C: \ Users \ rodrigo \ Downloads \ vps1 \ priv.key"
Command: open "autodj@144.22.141.167" 2222
Error: Connection timed out after 20 seconds of inactivity
Error: Could not connect to server
Status: Waiting to retry ...
Status: Connecting to 144.22.141.167:2222 ...
Response: fzSftp started, protocol_version = 11
Command: keyfile "C: \ Users \ rodrigo \ Downloads \ vps1 \ priv.key"
Command: open "autodj@144.22.141.167" 2222
Error: Connection timed out after 20 seconds of inactivity
Error: Could not connect to server.
i have ubuntu 20.04

**Comment by SC2Mitch** [comment]
Unable to replicate this on my local machine, seems to work fine for me. 

```
Status:	Connecting to localhost...
Status:	Using username "banana". 
Status:	Connected to localhost
Status:	Retrieving directory listing...
Status:	Listing directory /
Status:	Directory listing of "/" successful
```

**Comment by Abqehebter** [comment]
Maybe some firewall problems? Ports closed?

**Comment by RME-Systems** [comment]
I have the ports open

**Comment by Abqehebter** [comment]
Are you also using the correct port, or did you adjust it yourself? The normal SFTP port for AzuraCast is `2022` and **not** `2222`

**Comment by RME-Systems** [comment]
I already resolved it. restart the vps and it solves, thanks
