### ISSUE TITLE
API not allowing creation of streamer accounts that are disabled.

### ISSUE THREAD

**Issue by ItsDestinyDev** [AzuraCast/AzuraCast#4895]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.14.1 Stable

### What happened?

Using Python V3.10 and Requests.

When sending a post request to the Azuracast to create a new streamer account, when specifying `"is_active": False` the Azuracast does not create the account as disabled.

Data being sent to Azuracast:
`{'streamer_username': 'TestAccount', 'streamer_password': 'Redacted', 'display_name': 'TestAccount', 'is_active': False, 'comments': None, 'enforce_schedule': False, 'schedule_items': []}`

**Comment by SlvrEagle23** [comment]
@itsdestinydev This should be fixed as of the latest Rolling Release version. We're working out just a few issues with our Rolling Release channel before tagging our next stable release, so you can update to that when it is tagged.
