### ISSUE TITLE
SFTP permission denied copying files

### ISSUE THREAD

**Issue by cybercuate** [AzuraCast/AzuraCast#4899]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#a2eb5d0

### What happened?

NVM fixed it, it was permission on files (a wierd problem I usually deal with). It wasn't azuracast problem so close this please and thanks.

**Comment by SC2Mitch** [comment]
Closed! Thanks for letting us know

For the future, you can close your own tickets by this button 
![image](https://user-images.githubusercontent.com/29955942/146701255-ee8e6cdc-73eb-4463-92f8-47c4fc075186.png)

- mitch
