### ISSUE TITLE
Listeners statistic +

### ISSUE THREAD

**Issue by efsysefsys** [AzuraCast/AzuraCast#49]
Maby u can add to statistic listerners country?( geoip) to show listeners count and % by country somthing like that.
or mabby create button Now listening :2323 listeners and when u press this (button / link) open new page where show 

country flag (img) - listener ip adress  :    Listener agent ( player img)      :      mount & Connected time

(listeners agents like , winamp , vlc , chrome , gecko , bass etc )
(mount & connected time , how many sec or mins or hours this listener connected )
or without mount

**Comment by daniel-j** [comment]
I use a service called [IPInfoDB](ipinfodb.com) for my [radio station](https://radio.djazz.se/), to show current listeners on a Google Maps map. It also shows user agent (what browser/player is the listener using) and how long they have been connected.

Some code snippets related to the IP lookup (Node.JS):
[Fetch from API](https://github.com/daniel-j/parasprite-radio/blob/master/scripts/iplookup.js)
[Getting listeners with IP addresses from Icecast](https://github.com/daniel-j/parasprite-radio/blob/421585ec4a2b7e079e020420e65fc5cc47730274/server/icecast.js#L102)
[Output JSON from Icecast module](https://github.com/daniel-j/parasprite-radio/blob/421585ec4a2b7e079e020420e65fc5cc47730274/server/icecast.js#L303)
[Same but for the HLS stream module](https://github.com/daniel-j/parasprite-radio/blob/421585ec4a2b7e079e020420e65fc5cc47730274/server/streams.js#L103)
[Cache IP lookups for one hour](https://github.com/daniel-j/parasprite-radio/blob/421585ec4a2b7e079e020420e65fc5cc47730274/server/streams.js#L80)

Note: This is realtime data only, nothing is stored in the database.
