### ISSUE TITLE
Theme features

### ISSUE THREAD

**Issue by RainbowDash53** [AzuraCast/AzuraCast#490]
Hello, I'm currently trying to make my own style for Azuracast but with the update the content will be reset, so why not include a theme features so the community should participate. I think it'll be so great.

**Comment by SlvrEagle23** [comment]
@RainbowDash53 If you go to the "Custom Branding" page on the administration panel, you can customize the CSS on both the public-facing "minimal" pages and the internal full pages.

**Comment by RainbowDash53** [comment]
Yes, but that's not really a theme features with TPL files :')

**Comment by SlvrEagle23** [comment]
The AzuraCast system does indeed use template files already (in `app/templates`), but building an extensible system that would allow users to override those templates somewhere else really doesn't work well with the distribution methods AzuraCast uses.

If you're interested in modifying the actual HTML templates, you're more than welcome to do so, but future updates will likely overwrite any changes made to those files. If the changes you have planned are fairly significant, it may be worth just forking the codebase and applying the changes to the forked version, then merging in from upstream as changes happen.

**Comment by Moderndayfreak** [comment]
> The AzuraCast system does indeed use template files already (in `app/templates`), but building an extensible system that would allow users to override those templates somewhere else really doesn't work well with the distribution methods AzuraCast uses.
> 
> If you're interested in modifying the actual HTML templates, you're more than welcome to do so, but future updates will likely overwrite any changes made to those files. If the changes you have planned are fairly significant, it may be worth just forking the codebase and applying the changes to the forked version, then merging in from upstream as changes happen.

Where is the login page located? Thanks!

**Comment by SlvrEagle23** [comment]
@Moderndayfreak `templates/frontend/account/login.phtml`

If at all possible, however, you should use the custom JavaScript and CSS options provided through the "Custom Branding" page from system administration, which will let you make changes that don't get overridden by updates.

**Comment by Moderndayfreak** [comment]
Already been doing it. Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
