### ISSUE TITLE
installation error on ubuntu 21.10

### ISSUE THREAD

**Issue by amirkhattak** [AzuraCast/AzuraCast#4902]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

i have issue with installation

### Relevant log output

```shell
root@vmi488317:/var/azuracast# ./docker.sh install
Checking installation requirements for AzuraCast...
[PASS] Operating System: Linux
[PASS] Architecture: x86_64
[PASS] Command Present: curl
[PASS] Command Present: awk
[PASS] User Permissions
[PASS] Installation Directory
[PASS] All requirements met!
Docker is already installed! Continuing...
Docker Compose does not appear to be installed. Install Docker Compose now? [Y/n] y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   665  100   665    0     0  27708      0 --:--:-- --:--:-- --:--:-- 27708
100 2884k  100 2884k    0     0  6932k      0 --:--:-- --:--:-- --:--:-- 6932k
Prefer stable release versions of AzuraCast? [y/N] y
./docker.sh: line 356: docker-compose: command not found
./docker.sh: line 357: docker-compose: command not found
./docker.sh: line 404: docker-compose: command not found
./docker.sh: line 405: docker-compose: command not found
./docker.sh: line 406: docker-compose: command not found
```

**Comment by Abqehebter** [comment]
Try to install docker-compose manually:

`sudo apt-get install docker-compose`

See: https://github.com/AzuraCast/AzuraCast/issues/4889

**Comment by SC2Mitch** [comment]
I'll be taking a look as to why it's prompting errors in the script.

**Comment by SlvrEagle23** [comment]
@amirkhattak It appears our new method of installing Docker Compose is a little less reliable than we'd like it to be in all cases.

If you're seeing errors like `docker-compose not found`, try running these items manually:

```bash
curl -fsSL https://github.com/docker/compose/releases/download/v${COMPOSE_VERSION}/docker-compose-linux-$(uname -m) -o docker-compose
curl -fsSL https://raw.githubusercontent.com/docker/compose-switch/master/install_on_linux.sh -o install-compose-switch.sh

sudo chmod a+x ./docker-compose
sudo mv ./docker-compose /usr/libexec/docker/cli-plugins/docker-compose

sudo sh install-compose-switch.sh
rm install-compose-switch.sh
```

...and let me know if you see any errors.

**Comment by simpsss** [comment]
> @amirkhattak It appears our new method of installing Docker Compose is a little less reliable than we'd like it to be in all cases.
> 
> If you're seeing errors like `docker-compose not found`, try running these items manually:
> 
> ```shell
> curl -fsSL https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-linux-$(uname -m) -o docker-compose
> curl -fsSL https://raw.githubusercontent.com/docker/compose-switch/master/install_on_linux.sh -o install-compose-switch.sh
> 
> sudo chmod a+x ./docker-compose
> sudo mv ./docker-compose /usr/libexec/docker/cli-plugins/docker-compose
> 
> sudo sh install-compose-switch.sh
> rm install-compose-switch.sh
> ```
> 
> ...and let me know if you see any errors.

Did not work.

```
sudo curl -L https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```

 It works

**Comment by SC2Mitch** [comment]
This should be fixed now, can you check?

**Comment by amirkhattak** [comment]
yeah thank you its fixed now
