### ISSUE TITLE
Customers do not see their quota disk surfaces

### ISSUE THREAD

**Issue by fast97** [AzuraCast/AzuraCast#4905]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #a2eb5d0 (2021-12-19 18:50) • Docker • PHP 8.1

### What happened?

Customers do not see their quota disk surfaces
Hello as an admin, I see the client quotas but none of the clients who do not have full access do not see their quotas. is this normal? they have a message that says they don't have access to that part of the site. Thank you
![cap36](https://user-images.githubusercontent.com/51033222/146853180-3404781c-010e-4253-aaba-ed1e73531a73.png)
![cap37](https://user-images.githubusercontent.com/51033222/146853206-b4fd2e60-cb14-42e0-8f4e-6a91922d1b13.png)
![cap38](https://user-images.githubusercontent.com/51033222/146853225-d95b0c6d-1dbe-447f-8167-b295fadf34bf.png)

**Comment by SC2Mitch** [comment]
It's most likely the `Manage Station Profile` permission that has the quota.

**Comment by fast97** [comment]
I come back here because I did not understand this is given or removed I always have this problem with a client when I activate the profile management option the client changes the number of listeners and others ... and when I disables the profile management option, the client does not see the disk quota as indicated in screenshot. I saw the code written on the 9dc128a forum that I do not understand if there is a manipulation to be done on my side.
Thank you

**Comment by fast97** [comment]
It would be good if in the client profile management option that the client does not have access to the broadcasting party? I do not want to give access to the client because he modifies the broadcasting information. Thank you
![cap42](https://user-images.githubusercontent.com/51033222/147025153-ddc73ecf-f858-42fd-8b3b-5d6de790959f.png)
