### ISSUE TITLE
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found

### ISSUE THREAD

**Issue by Julien00859** [AzuraCast/AzuraCast#491]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Ubuntu 16.04

**Describe the issue in full detail, including screenshots if possible:**

In the docker-compose ouput:
```nginx_1        | 172.19.0.1 - - [18/Mar/2018:11:34:59 +0000] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0" "-"```

In the error file:
```
[18-Mar-2018 11:34:59 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
Stack trace:
#0 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('SELECT s0_.sett...')
#1 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(912): Doctrine\DBAL\Driver\PDOConnection->query('SELECT s0_.sett...')
#2 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery('SELECT s0_.sett...', Array, Array, NULL)
#3 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(334): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array)
#4 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(957): Doctrine\ORM\Query->_doExecute()
#5 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/A in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 57
```

**Comment by SlvrEagle23** [comment]
@Julien00859 Did you run the installer script as part of the Docker spin-up process? If the database is entirely missing like that, it implies something failed in that installer script, which should've produced an error message.

**Comment by Julien00859** [comment]
Yeah, I don't think I ran anything else than `docker-compose up`

**Comment by SlvrEagle23** [comment]
@Julien00859 Follow the instructions on the readme, they document the installation process...there's a one-time installation that's necessary.
