### ISSUE TITLE
 I can't install release version error in docker.sh

### ISSUE THREAD

**Issue by JMultimidia** [AzuraCast/AzuraCast#4914]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

I'm using ubuntu 20 and docker but it gives the following error:

./docker.sh: line 356: docker-compose: command not found
./docker.sh: line 357: docker-compose: command not found
./docker.sh: line 404: docker-compose: command not found
./docker.sh: line 405: docker-compose: command not found
./docker.sh: line 406: docker-compose: command not found

**Comment by JMultimidia** [comment]
This work for me:

sudo curl -L https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

**Comment by cempack** [comment]
thanks
