### ISSUE TITLE
The installer / update has errors.

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#4916]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #a2eb5d0 (2021-12-19 18:50) • Docker • PHP 8.1

### What happened?

The installer / update has errors.
I'm having problems with the station being turned off and then it won't turn on, I saw that an update was reverted so that the correction can be made, but I can't update because the update doesn't work.
before I ran ./docker update-self and then ./docker update and I got the error.

### Relevant log output

```shell
[NOTICE] Before you continue, please make sure you have a recent snapshot of your system and or backed it up.
Are you ready to continue with the update? [Y/n] y
Pulling installer ... done
Creating network "azuracast_installer_default" with the default driver
Creating azuracast_installer_installer_run ... done
PHP Fatal error:  Uncaught Error: Class "Silly\Application" not found in /var/azuracast/www/bin/installer:17
Stack trace:
#0 {main}
  thrown in /var/azuracast/www/bin/installer on line 17

Fatal error: Uncaught Error: Class "Silly\Application" not found in /var/azuracast/www/bin/installer on line 17

Error: Class "Silly\Application" not found in /var/azuracast/www/bin/installer on line 17

Call Stack:
    0.0004     393200   1. {main}() /var/azuracast/www/bin/installer:0

ERROR: 255
```

**Comment by fast97** [comment]
hello same for me. thank you

**Comment by smilingpeanut** [comment]
Encountering the same issue the OP describes with the identical error message.

**Comment by SC2Mitch** [comment]
Thanks for reports guys. Related to the last commit.

**Comment by betowebti** [comment]
The same for here. Thanks!

**Comment by SlvrEagle23** [comment]
Latest commit on rolling release should fix this. It turns out our test suite wasn't looking at our installer codebase.
