### ISSUE TITLE
Consider using Dockerize in addiction to docker-compose:depends-on

### ISSUE THREAD

**Issue by Julien00859** [AzuraCast/AzuraCast#492]
[Dockerise](https://github.com/jwilder/dockerize) has the following nice feature:

    $ dockerize -wait tcp://db:5432 -wait http://web:80 -wait file:///tmp/generated-file

As some of your services needs to be started after other are *running* (and not just *started*) you could use dockerize to better handle all the dependencies

When #491 will be solved and I succeeded to run AzuraCast, I'll look around to do it and send a pull request :wink:

**Comment by SlvrEagle23** [comment]
@Julien00859 I had no idea this was a thing, and it solves a lot of problems we have on AzuraCast with spin-up readiness.

I'm already planning a refactor of our main Docker images to Alpine, so don't worry about PR'ing anything into the existing web container, but this is definitely going into the new version.

**Comment by SlvrEagle23** [comment]
Implemented in the latest build of the `azuracast_web` image.
