### ISSUE TITLE
Mp3 files does not complete processing

### ISSUE THREAD

**Issue by JMultimidia** [AzuraCast/AzuraCast#4920]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.14.1

### What happened?

I sent the songs via mp3 and when listing the files for more than 24 hours it appears as processing and does not complete.
![image](https://user-images.githubusercontent.com/20319612/147278371-067aea3e-f7fe-4165-a2b3-e9c7e67ef87b.png)

**Comment by SC2Mitch** [comment]
Can you upload them songs to here so I can test them?
