### ISSUE TITLE
Liquidsoap restarting seemingly at random...

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#4922]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#59e5107 (2021-12-23 10:05)

### What happened?

As you well know we just finished going through the process of fixing the problem of buffer overruns and CPU overloads but a new weird problem has now surfaced - It seems LS kicks it's head up at random and boots the live streamer off for no apparent reason;
Here is a first log where I was streaming and got booted off:
[Booted off 1.txt](https://github.com/AzuraCast/AzuraCast/files/7775360/Booted.off.1.txt)

And a second occurrence, a bit later which I am including because it unfolded a bit differently;
[Kicker off-Log.txt](https://github.com/AzuraCast/AzuraCast/files/7775361/Kicker.off-Log.txt)

Could that be related to the observation I sent at the end of issue # 4783 ????

**Comment by SpeedyCharly** [comment]
Again this morning - 3 random restarts within a short time @ 6:04, 6:26 and 6:32...

Here is the edited log;
[12-26 log.txt](https://github.com/AzuraCast/AzuraCast/files/7777100/12-26.log.txt)

**Comment by SlvrEagle23** [comment]
@SpeedyCharly You also created a discussion about this same issue and I replied to it there...this is no doubt a Liquidsoap-related issue, so it should probably be created and followed-up with on their repository. I realize this back-and-forth is more difficult, but we're essentially working out the initial launch issues in Liquidsoap 2 together as a group.

**Comment by SpeedyCharly** [comment]
Sure, will transfer the issue to their hub...thanks

**Comment by SpeedyCharly** [comment]
Issue created @ LS github:

https://github.com/savonet/liquidsoap/issues/2125

**Comment by toots** [comment]
Hi. It's not clear to me that this is coming from liquidsoap. @SlvrEagle23 didn't you mention that there is a restart mechanism in AzuraCast? I believe we've seen it in play while investigating the API calls not being under a default timeout. Have we ruled out that these restart aren't coming from this mechanism?

**Comment by SlvrEagle23** [comment]
@toots It's just a process manager that detects when a process terminates and tries to restart it after it fails. Nothing we're doing is triggering these restarts directly or arbitrarily.

**Comment by toots** [comment]
Ok. Can y'all push an update with a rebuild using `ocaml-lame` `0.3.5`? We've fixed a segfault there and it might very well be the issue here, same for https://github.com/AzuraCast/AzuraCast/issues/4911

**Comment by SlvrEagle23** [comment]
Updated the `stations` container; @SpeedyCharly mind trying to update?

**Comment by SpeedyCharly** [comment]
@SlvrEagle23 Our live broadcast day has started - will update at end of day and report 2morrow morning

**Comment by SpeedyCharly** [comment]
Minutes ago another DJ bites the dust; :P
[Another DJ booted fron stream.txt](https://github.com/AzuraCast/AzuraCast/files/7777729/Another.DJ.booted.fron.stream.txt)

**Comment by toots** [comment]
This looks like another issue than initially reported. If there is a different issue, we should submit separate tickets, this one if for intermittent restarts.

I'm happy to comment on the issue of the DJ being booted but let's make sure to do it in another ticket.

**Comment by SpeedyCharly** [comment]
@toots 
Ok... I simply assumed the two were related...

**Comment by toots** [comment]
They shouldn't!

**Comment by SpeedyCharly** [comment]
Ok will report separately if the issue reoccurs after tonite's update

**Comment by toots** [comment]
Thanks. With errors like these, we first need to sort out external vs. internal issues. Like, was the DJ kicked out because their connection got stalled?

**Comment by SpeedyCharly** [comment]
@ toots - Yes, I quite understand on the issue of djs getting booted. 

As for the issue here; just finished scanning the overnight logs and happy to report that not a single random restart was to be seen.  Will keep an eye out for this for a few more nights, but hopefully, the last commit licked the problem...

**Comment by toots** [comment]
Great. I'm closing the liquidsoap issue then, thanks for reporting!

**Comment by SpeedyCharly** [comment]
All good here after 2 days without a hitch,,,
