### ISSUE TITLE
Error "error while creating mount source path '/var/azuracast': mkdir /var/azuracast: read-only file system" when updating

### ISSUE THREAD

**Issue by Khauron** [AzuraCast/AzuraCast#4927]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#558144c

### What happened?

When doing update in Ubuntu CLI @ root:
cd /var/azuracast/
./docker.sh update-self
./docker.sh update
and answering "y" to the following question, the script returns:
Pulling installer ... done
Creating azuracast_installer_installer_run ... done
Error response from daemon: error while creating mount source path '/var/azuracast': mkdir /var/azuracast: read-only file system
ERROR: 1

### Relevant log output

```shell
root@docker:~# root@docker:~# cd /var/azuracast/
root@docker:/var/azuracast# ./docker.sh update-self
New Docker utility script downloaded.
root@docker:/var/azuracast# ./docker.sh update
[NOTICE] Before you continue, please make sure you have a recent snapshot of your system and or backed it up.
Are you ready to continue with the update? [Y/n]
Pulling installer ... done
Creating azuracast_installer_installer_run ... done
Error response from daemon: error while creating mount source path '/var/azuracast': mkdir /var/azuracast: read-only file system
ERROR: 1
root@docker:/var/azuracast#
```

**Comment by TilsonM17** [comment]
I have the same problem, can anyone solve it?

**Comment by Chrisx84** [comment]
same issue

**Comment by scysys** [comment]
2021, 2022, 2023. Lets see if the next one will be 2024 😂

**Comment by marekdziem** [comment]
me too
