### ISSUE TITLE
Duplicate metadata from Liquidsoap

### ISSUE THREAD

**Issue by LeonLionFM** [AzuraCast/AzuraCast#4929]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #2747f7a (2021-11-07 21:20)

### What happened?

I noticed that the metadata from Liquidsoap/AzuraCast is sent to the streaming server twice via remote relay (more about this in the streaming log of laut.fm below)

I don't know exactly what causes this phenomenon, but I also have two song history entries (locally in AzuraCast itself) for some songs/times,

![grafik](https://user-images.githubusercontent.com/88619559/147584028-b0bcac17-4620-4306-8208-d7337193c665.png)

Maybe this could also be debugged better if you could view the playlist log at Icecast itself (AzuraCast)?

![grafik](https://user-images.githubusercontent.com/88619559/147584167-d72d4e73-d85a-4c05-aeda-446f61987639.png)

**Comment by LeonLionFM** [comment]
With the latest rolling release version (Rolling Release #53bf888 (2021-12-28 1:20)), I also have problems with the queue, which occasionally behaves quite strangely:

![grafik](https://user-images.githubusercontent.com/88619559/147588389-87c1a14a-0ab1-4fde-ab7b-c9c2c860a3da.png)
![grafik](https://user-images.githubusercontent.com/88619559/147588527-245a448f-855a-40b1-89e0-4c371852f863.png)

In this case, 5 songs are lined up, which then appear in the API without playlist source and with the default album cover.

Unfortunately, this is also the current reason why I am not allowed/able to upgrade to the latest rolling release with the live instance.

**Comment by SlvrEagle23** [comment]
@LeonLionFM We had actually encountered this same problem before, and we had disabled a setting as a result to prevent it from causing problems for us, but we were told by the Liquidsoap team to re-enable that setting for some tests.

Unfortunately, that setting seems to be causing the exact same problem it caused before, so I'm reverting it, as it is known to cause problems with the AutoDJ queue and double-metadata-pushing like you're seeing.

**Comment by LeonLionFM** [comment]
@SlvrEagle23 Whether the duplicate metadata transfer to laut.fm is fixed, I can unfortunately only confirm later.

Unfortunately, the error from my comment above is still "active".
But I don't assume that this error is present for everyone. Can I contact elsewhere to discuss the error?

**Comment by LeonLionFM** [comment]
Unfortunately, nothing has changed on the latest Rolling Release. There seems to be another metadata transfer at the fade-out, because the crossfade is set to 2-3 seconds here, so my idea would actually fit:

![image](https://user-images.githubusercontent.com/88619559/147661812-9311bb65-514f-4db5-8f9c-3cf1e77a6390.png)

**Comment by SlvrEagle23** [comment]
This one needs to be looked at upstream, as it's likely related to recent changes made on the Liquidsoap end to improve the reliability of metadata transfers for live broadcasts.

@toots what do we need to begin diagnosing this?

**Comment by SlvrEagle23** [comment]
@LeonLionFM Just to confirm, you're seeing both the double-metadata pushes AND the song queue entries, and you're on the very latest rolling release version? These are actually two separate issues we need to investigate.

**Comment by LeonLionFM** [comment]
@SlvrEagle23 To be exact, there are a whole three problems, but two problems are very similar to each other.

My current **AzuraCast version** (on the test instance) is as follows: **Rolling Release #cc6753a (2021-12-29 5:36) • Docker • PHP 8.1**

- Firstly, we have these three extra entries in the song queue (as already described in my comment above):
(However, this error has become even rarer)

![grafik](https://user-images.githubusercontent.com/88619559/147700952-35891a56-dcca-4289-80dc-2fb03bb4fbd9.png)

- Second, that problem where the metadata is sent twice here (See the laut.fm logs above)

- Third, I occasionally have duplicate song entries in the song history for different stations. As an example:

![grafik](https://user-images.githubusercontent.com/88619559/147701335-dcd56482-b823-43a6-93f8-9c8332f01955.png)

**Comment by LeonLionFM** [comment]
At first glance, the error with the song queue seems to be due to the jingle mode. However, I am not sure:

![grafik](https://user-images.githubusercontent.com/88619559/147703153-89aa9a2e-9bba-4f5e-8263-8ef83fa19d2e.png)

**Comment by SlvrEagle23** [comment]
I'm actually unable to reproduce this issue locally, so I'm thinking we may have another "race condition" issue inside AzuraCast itself. I will investigate this further.

**Comment by LeonLionFM** [comment]
I can also provide my instance for examination if needed.
But it may be important to mention that we operate 15 stations.

**Comment by LeonLionFM** [comment]
However, the first error (see screenshot) seems to be contained:

- It looks like the song queue only forms like this when an ad trigger is about to play (This goes for one second and is played every 15 minutes).
- Also possible, is the playback of the jingle (Jingle-Mode)

In both cases, it clearly happens that the song queue builds itself with 3 to 5 songs.

![grafik](https://user-images.githubusercontent.com/88619559/147751086-56e496ec-b334-4ca8-8e02-078ca5c0a5f6.png)

**Comment by SlvrEagle23** [comment]
@LeonLionFM It's okay if a weird entry occasionally shows up on the upcoming queue, so long as it's not also showing up erroneously on the playback history. The queue is populated sometimes by the "Feedback" mechanism from Liquidsoap, which we use to help inform what's actually playing via Icecast/SHOUTcast (where we only get a title/artist)

**Comment by LeonLionFM** [comment]
@SlvrEagle23 Then I guess error one is cleared up. However, it is still exciting with error three and error one the fact that no album cover and no playlist is stored in the Now-Playing display:

![grafik](https://user-images.githubusercontent.com/88619559/147769741-95096b12-cd51-4a7e-8b6a-30b69a42f9d4.png)

...and the duplicate song history entries.

**Comment by SlvrEagle23** [comment]
@LeonLionFM We're really conflating a ton of issues here, and honestly it's making it quite hard to track what's getting done and what isn't. You may want to separate these out into individual GitHub issues so that we can actually track each one to completion, rather than trying to juggle several in this one thread.

**Comment by LeonLionFM** [comment]
@SlvrEagle23 Then I will put the remaining "bugs" into seperate issues. This remains the "error" for the duplicate metadata to laut.fm.

**Comment by LeonLionFM** [comment]
@SlvrEagle23 Good news!

The problem with duplicate song history entries seems to be fixed thanks to the latest commit (At least on the very latest rolling release version)!!!

**Comment by SC2Mitch** [comment]
Great, glad to hear it's been resolved for you.

**Comment by LeonLionFM** [comment]
I don't want to publish any misunderstandings. With the "FIXED" status I meant the duplicate song history entries at AzuraCast itself. Unfortunately I can only check the fix for laut.fm later.

**Comment by SC2Mitch** [comment]
Okay let us know if it's not fully resolved and we can reopen this.

**Comment by LeonLionFM** [comment]
@SC2Mitch Seems to be fixed according to some colleagues (The laut.fm problem with the duplicate metadata)

This problem probably had two things going on:
- The duplicate metadata was sent to all Icecast outputs (Also remote relays).
- The duplicate metadata was also pushed into the song history.

Error 1/3 is fixed! Thanks a lot so far.
//close
