### ISSUE TITLE
No way to block listening bots / certain IPs/subnets

### ISSUE THREAD

**Issue by radio2019** [AzuraCast/AzuraCast#4939]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

Is there any method to block IPs/subnets of listening bots?
Currently 4 of these are connected to my stream and they are consuming a lot of bandwidth: [https://prnt.sc/25p5hep](https://prnt.sc/25p5hep)

**Comment by Abqehebter** [comment]
It is easiest if your streaming server blocks this itself with a firewall as an example.
AzuraCast / Icecast is not designed to block basically everything.

You can block IP addresses or countries in the respective Icecast instance. But not more than that.

**Comment by PiggyPlex** [comment]
Look into blocking specific useragents too, as it apepars that they're all using the axios client via CloudFlare or the firewall/networking hardware.
My best guess is that they're trying to rip statistics from the stream, but letting the request hang.
Note that there will be side-effects with blocking these sources - and that there are _legitimate uses_ for automating requests to your radio stream.

**Comment by SC2Mitch** [comment]
As the above people have said, we're not designed to block large amounts of users and or target specific useragents. If you want to see this feature in the future, put it on our feature upvote page. - https://features.azuracast.com/

Kind regards

**Comment by kgguru** [comment]
of course IceCast KH can block agents see that: <deny-agents>/path/to/file-with-useragents</deny-agents>
it is possible!

**Comment by Abqehebter** [comment]
This issue here is closed. Please create a feature request.
As described above, you can already block individual IP addresses in AzuraCast.
However, for an extension I would go back to a server firewall.

In my opinion AzuraCast has nothing more to do with it or it is not the task of it.

**Comment by kgguru** [comment]
Please do not be rude to me. As I said ICECAST KH CAN BLOCK AGENTS OUT OF THE BOX.
