### ISSUE TITLE
sync task nowplaying metadata not running

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#4940]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

0cc3008 (2021-12-30 19:56) • Docker • PHP 8.1

### What happened?

hello,
at my administration pannel i see that now playing metadata sync task are not being run.
i see thath the last run of the task is 3 days ago.
if i forse the task to run, nothing appens. it opens the loig with this.
Loading...[2022-01-02T19:10:29.072938+00:00] AzuraCast.NOTICE: Running sync task: Now Playing Data {"force":true} []
I only can avoud it running manually
./docker.sh cli sync:run nowplaying
if you can point me in right direction, i can send proper logs.

**Comment by SlvrEagle23** [comment]
@nunotfc We're currently testing out a fully revamped synchronization system that should help isolate and improve issues with the routine scheduled tasks. Look forward to this change getting merged into the main branch within the next week.

**Comment by SC2Mitch** [comment]
@nunotfc Can you run a update and let us know of the results? Our sync processes should be a lot better now.

**Comment by nunotfc** [comment]
solved, i will close now.
