### ISSUE TITLE
Are artist duplicates allowed?

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#4948]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #9cfc2ee (2022-01-04 22:46)

### What happened?

Hey,

I often have duplicate artists in the song history within a short period of time.
I have attached helpful screenshots of my settings and the entries here.

The three artists are present only once in the entire playlist (Similar can be observed on other stations as well)
Either this is just a display error or it is something serious after all.

![image](https://user-images.githubusercontent.com/42640247/148144388-a9514538-b319-4286-a522-f0d0a055b1e1.png)
![image](https://user-images.githubusercontent.com/42640247/148144416-53404add-4ae1-4898-8bef-3168c24d231b.png)
![image](https://user-images.githubusercontent.com/42640247/148144558-c19ae6c4-394e-4fad-beba-50325ff37079.png)
![image](https://user-images.githubusercontent.com/42640247/148144570-8e028cdc-94e0-40c7-a370-6adbde210dd2.png)

**Comment by Abqehebter** [comment]
Unfortunately, this does not seem to be a display error after all: It is reality.
I have observed the following so far:

- Irregular the song queue builds a song simply in between and steals it not from the queue, but from the playlist. This should not happen.

![image](https://user-images.githubusercontent.com/42640247/148234745-33c64720-3989-43fd-9d08-2c8f531a490f.png)

- Likewise, the song queue will occasionally grab the same song again, but it has been played before. This is then also on the station profile under "Playing Next" **but is not played**.

![image](https://user-images.githubusercontent.com/42640247/148235165-6a5c358c-3c01-4314-9bec-0e6c78c9ca72.png)
![image](https://user-images.githubusercontent.com/42640247/148235250-9ac425aa-9248-4bb6-a4a2-5005bd16c0f4.png)

So the song queue seems to still have some problems from Liquidsoap or from AzuraCast unfortunately.

Please feel free to write me if we need more debugging here.

**Comment by SC2Mitch** [comment]
Taking a look now. Unsure if this is upstream or internal so I'll tag as both until review is done.

**Comment by Abqehebter** [comment]
Otherwise, I can also gladly provide the particular server where I notice the error. Thanks!

**Comment by SC2Mitch** [comment]
If your able to contact me on Discord (You may need to add me) and I can take a look at the specific server to get more debug data from it.
