### ISSUE TITLE
Prevent Duplicate Artist/Title does not work in all cases

### ISSUE THREAD

**Issue by LeonLionFM** [AzuraCast/AzuraCast#4951]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #4bafce2 (2022-01-05 21:31)

### What happened?

I still have an important problem with the song queue. Without this being fixed, I can't do an update.

About the problem: In my song history it is clearly visible that the "Prevent Duplicate Artist/Title" function is currently useless in the latest rolling release version.

In my Rolling Release version before Liquidsoap 2.0 (Rolling Release #2747f7a (2021-11-07 21:20)) the avoidance works as it should.

I can only include screenshots here for now. Logs are only available for the last X minutes in AzuraCast:
![grafik](https://user-images.githubusercontent.com/88619559/148308046-6cc4f457-75a5-410f-b6dc-5af064fc51a6.png)
![grafik](https://user-images.githubusercontent.com/88619559/148308221-3796e36e-ed34-42b4-91ac-8bdbc7e447fe.png)
![grafik](https://user-images.githubusercontent.com/88619559/148308467-26ca1067-401c-4cb2-8729-0791f7768453.png)

**Comment by LeonLionFM** [comment]
The basic principle of the "Prevent Duplicate Artist/Title" function works perfectly without any problems.

I have now also installed the latest commit: https://github.com/AzuraCast/AzuraCast/commit/abaa4a0985f4e56745f4d9978114300e8dd94662

However, I need to do more debugging for this, I think.

I will now suspend the scheduled playlists on some stations to check if this is the problem.

![grafik](https://user-images.githubusercontent.com/88619559/148383501-7db3a84d-0770-48e3-8fbd-1132ff321fea.png)

**Comment by ORIGINALFob** [comment]
I unfortunately have the same problem. Enabling the option does not hel
![azura](https://user-images.githubusercontent.com/79091148/148394087-1fb1aec0-71a3-4a86-855c-d3708ff88171.png)
p

**Comment by LeonLionFM** [comment]
I will try to check the log button. Only with some songs in the queue the log button doesn't show up unfortunately.
