### ISSUE TITLE
./docker.sh letsencrypt-create doesn't return any prompt

### ISSUE THREAD

**Issue by orllewin** [AzuraCast/AzuraCast#4954]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel (Rolling Release?)

### Current AzuraCast Version

Rolling Release #abaa4a0 (2022-01-06 2:29) • Docker • PHP 8.1 

### What happened?

As per the title, I'm unable to get SSL working following the instructions precisely and without any other configuration taking place before, it's a fresh install.

* I installed Azuracast via the Linode Marketplace one-click install
* AzuraCast is working as expected, but no SSL of course
* I SSH to the Linode and `cd` to `/var/azuracast` following the instructions at: https://docs.azuracast.com/en/administration/ssl-and-lets-encrypt
* I run `update-self` successfully, then `letsencrypt-create` which returns immediately without any prompts or output:
```
root@localhost:/var/azuracast# ./docker.sh update-self
New Docker utility script downloaded.
root@localhost:/var/azuracast# ./docker.sh letsencrypt-create
root@localhost:/var/azuracast# 
```

**Expected:** I'm challenged to enter domain, contact and other Let's Encrypt details.

**Actual:** The command returns immediately with no output.

Thanks for your help in advance, I'm utterly stuck, and apologies if this is something obvious.

**Comment by LeonLionFM** [comment]
I can confirm this error so.

**Comment by SC2Mitch** [comment]
Can you try this @LeonLionFM  / @orllewin , go to your `.env` file in `/var/azuracast` and it should have this new field: 
```
LETSENCRYPT_EMAIL
LETSENCRYPT_HOST
```

Can you fill these in and do `docker-compose down && docker-compose up -d`

Let me know if this works and I'll see about adding in some prompt.

**Comment by orllewin** [comment]
**Those fields weren't in the .env file**, so I added like so:

```
LETSENCRYPT_EMAIL=redacted@redacted.uk
LETSENCRYPT_HOST=orrs.live
```
and ran `down` and `up` as above:

```
root@localhost:/var/azuracast# docker-compose down && docker-compose up -d
WARN[0000] The "LETSENCRYPT_EMAIL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "LETSENCRYPT_HOST" variable is not set. Defaulting to a blank string. 
WARN[0000] The "LETSENCRYPT_EMAIL" variable is not set. Defaulting to a blank string. 
[+] Running 8/8
 ⠿ Container nginx_proxy_letsencrypt  Removed  0.2s
 ⠿ Container nginx_proxy              Removed  10.4s
 ⠿ Container azuracast_web            Removed  1.0s
 ⠿ Container azuracast_mariadb        Removed  0.6s
 ⠿ Container azuracast_stations       Removed 6.5s
 ⠿ Container azuracast_redis          Removed 0.3s
 ⠿ Network azuracast_frontend         Removed 0.1s
 ⠿ Network azuracast_backend          Removed  0.1s
WARN[0000] The "LETSENCRYPT_EMAIL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "LETSENCRYPT_HOST" variable is not set. Defaulting to a blank string. 
WARN[0000] The "LETSENCRYPT_EMAIL" variable is not set. Defaulting to a blank string. 
[+] Running 8/8
 ⠿ Network azuracast_frontend         Created 0.1s
 ⠿ Network azuracast_backend          Created 0.1s
 ⠿ Container azuracast_stations       Started 4.6s
 ⠿ Container azuracast_mariadb        Started  1.7s
 ⠿ Container azuracast_redis          Started 1.7s
 ⠿ Container azuracast_web            Started 5.5s
 ⠿ Container nginx_proxy              Started 6.9s
 ⠿ Container nginx_proxy_letsencrypt  Started 8.4s
root@localhost:/var/azuracast# 
```

No change after doing that:

```
root@localhost:/var/azuracast# ./docker.sh letsencrypt-create
root@localhost:/var/azuracast# 
```

**Comment by SC2Mitch** [comment]
Check my latest edit, it should be 
```
# LetsEncrypt Domain Name(s)
# Domain name (example.com) or names (example.com,foo.bar) to use with
# LetsEncrypt.
LETSENCRYPT_HOST=

# LetsEncrypt E-mail Address
# Optionally provide an e-mail address for updates from LetsEncrypt.
# LETSENCRYPT_EMAIL=
```

**Comment by LeonLionFM** [comment]
Working for me. Thanks!

**Comment by orllewin** [comment]
Result, pasted exactly as above, added my domain, uncommented the email line and populated also, and now have progress:

```
root@localhost:/var/azuracast# ./docker.sh update-self
New Docker utility script downloaded.
root@localhost:/var/azuracast# ./docker.sh letsencrypt-create
Domain name (example.com) or names (example.com,foo.bar) to use with LetsEncrypt [orrs.live]: 
```

Thanks for taking the time to investigate @SC2Mitch

**Comment by SC2Mitch** [comment]
Thanks guys, will add some feedback into the command in the next commit.
