### ISSUE TITLE
RasPi 4 : error during installation script (armv7l unsupported)

### ISSUE THREAD

**Issue by Gyoo** [AzuraCast/AzuraCast#4957]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release

### What happened?

When trying to install AzuraCast on my RasPi 4 I get the following error message :

```sh
root@raspberrypi:/var/azuracast# ./docker.sh install
Checking installation requirements for AzuraCast...
[PASS] Operating System: Linux
[FAIL] Architecture: armv7l
       You are running an unsupported processor architecture.
       Automated AzuraCast installation is not currently supported on this
       operating system.
```

Below is an extract of my os-release file : 

```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
```

Because the problem happens on installation, I cannot provide further details about the Rolling Release version. I assume it's the latest one.

**Comment by SC2Mitch** [comment]
I believe this issue is because your architecture is 32 bit, when AzuraCast requires 64 bit. Let me know if you got further questions.

**Comment by Abqehebter** [comment]
@SC2Mitch is right. This version/OS has only 32 bit. I have it also tested and with Ubuntu 20.04 (64 bit) it would run with high probability.
