### ISSUE TITLE
 Token is not in a valid format. 

### ISSUE THREAD

**Issue by MisterSandFR** [AzuraCast/AzuraCast#4958]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#abaa4a0

### What happened?

[2022-01-06T21:35:37.057741+00:00] AzuraCast.ERROR: Token is not in a valid format. {"file":"/var/azuracast/www/src/Security/SplitToken.php","line":37,"code":0} []

https://i.gyazo.com/76e0cb323a9cb4d578c0620f2c3f356d.png

**Comment by SC2Mitch** [comment]
This needs a lot more information, what are you doing when this happens. Do you have an API key? Some docker logs will be helpful too.

**Comment by MisterSandFR** [comment]
Just after login, nothing is loading so i can't get log from the panel.

**Comment by SC2Mitch** [comment]
Can you check your docker logs `docker-compose logs -f` and see whats going on.

**Comment by Vaalyn** [comment]
Did this just randomly start to happen or was this after an update?
If this started after an update, do you remember which version (roughly) you were using before?

**Comment by MisterSandFR** [comment]
randomly start to happen, i updated multiple times thinking it was the issue.
Here is the error when im loading a page who say the token error :


`nginx_proxy                | nginx.1     | radio.*****.fr192.168.208.1 - - [11/Jan/2022:14:09:38 +0000] "GET /api/admin/users?internal=true&rowCount=10&current=1 HTTP/1.1" 500 355 "https://radio.*****.fr/admin/users" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"`

**Comment by SC2Mitch** [comment]
When you go to `admin/users` can you open the browser console and see what errors appears in the `console` or `network` tab for this error to appear? You may need to refresh to produce a result though.

**Comment by MisterSandFR** [comment]
Yes here : https://gyazo.com/225733248e823af209b1f226ff70f480

**Comment by SC2Mitch** [comment]
Do any errors appear in the network tab when this happens? If yes, click on the one marked in red and click on `response.

Do you have any API keys/ 2FA associated with your machine?

**Comment by MisterSandFR** [comment]
Error 500 on the same link shown on the console and this content : 
`{"code":500,"type":"InvalidArgumentException","message":"InvalidArgumentException at /var/azuracast/www/src/Security/SplitToken.php L37: Token is not in a valid format.","formatted_message":"<b>InvalidArgumentException at /var/azuracast/www/src/Security/SplitToken.php L37:</b> Token is not in a valid format.","extra_data":[],"success":false}`

No ApiKeys and no 2FA

**Comment by SlvrEagle23** [comment]
I think what may be happening is that your browser may have cookies or something else with a similar `token` variable, but that isn't intended to be a login token for AzuraCast itself. I've refined the API auth commands to only verify auth tokens that match our format in the first place, which should reduce the number of errors that happen that are caused by such things.

**Comment by MisterSandFR** [comment]
The last update fixed this issue, thanks @SlvrEagle23
