### ISSUE TITLE
Sequential Playlist behaves strangely

### ISSUE THREAD

**Issue by LeonLionFM** [AzuraCast/AzuraCast#4959]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #abaa4a0 (2022-01-06 2:29)

### What happened?

It seems that the Sequential Playlist does not stick to what is set.

Small similarity with the Issue https://github.com/AzuraCast/AzuraCast/issues/4952
Besides, I recognize here exactly such a connection with the random filtering out of any songs. This would explain Issue https://github.com/AzuraCast/AzuraCast/issues/4951 again.

The tracks are set in an order as follows:
![grafik](https://user-images.githubusercontent.com/88619559/148471240-7edbc513-1ca6-4b9a-988b-f8c803294925.png)

... but this is what the final result looks like in the Song Playback Timeline:
![grafik](https://user-images.githubusercontent.com/88619559/148471399-2f1ddec3-9b23-4b2a-8cc8-4452da5a2c24.png)
![grafik](https://user-images.githubusercontent.com/88619559/148471566-2d6a7b65-fa0b-4d52-87a1-808bc443d62b.png)

Two important details I have to explain about this:
- The playlist runs from 11:57 PM to 12:57 AM (set like this).
- The playlist should only run once:
![grafik](https://user-images.githubusercontent.com/88619559/148471628-4bbf988d-8f49-44ed-ab91-894b5539db48.png)

**Comment by Abqehebter** [comment]
Unfortunately, I can confirm that all these song queue problems (duplicate artists, misordering of scheduled playlists, song history problems, jingle mode, etc.) only take place after a certain number of stations. On my server with only one station everything runs as it should.

(_Yes, even with only one station the song queue sometimes gives the impression that it wants to play played songs again, but it's not._)

Conclusion: I can NOT find the following errors with only one station: https://github.com/AzuraCast/AzuraCast/issues/4951, https://github.com/AzuraCast/AzuraCast/issues/4952 and this error/bug here itself.
It looks different with 10+ stations.

This makes reproducing enormously difficult.

**Comment by SC2Mitch** [comment]
related to #4962
