### ISSUE TITLE
White page

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#496]
- **Installation Method:** Traditional
- **Host OS (if using Docker):** Ubuntu 16.04

White page for the public page as well as for the embedded reader

**Comment by radiowestcz** [comment]
white public ip page 
reinstall azuracast = white page (File not found.)
**Instalation Method: Tradicional
Host OS: Ubuntu server 16.04 LTS 64 bit**

**Comment by SlvrEagle23** [comment]
@ckeurk Since other people appeared to be having the same issue, could you explain why you closed the ticket? Were you able to resolve the issue, or did recent updates fix it?

**Comment by ckeurk** [comment]
Indeed the problem is solved, the page works correctly for my part
