### ISSUE TITLE
Character problem

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#497]
- **Installation Method:** Traditional 
- **Host OS (if using Docker):** Ubuntu 16.04

Character problem for some letters in the artist's edition, if I have an artist named Böhmer and I change the timing of the song, when saves the track goes into processing mode and does not save my changes.

**Comment by SlvrEagle23** [comment]
@ckeurk Sorry for the delay in getting back to this. I don't have any particular insight into why this might be happening, as AzuraCast has had support for UTF-8 characters in song names for quite some time.

If you run the 5-minute sync from the Administration page, do you see any errors?

**Comment by SlvrEagle23** [comment]
@ckeurk I have found and fixed a rather long-standing issue with AzuraCast that caused imports to fail with some media files. This may resolve your issue. Update and let me know if it does.

**Comment by ckeurk** [comment]
Great. Thanks. I'll check as soon as I can. 😉

**Comment by SlvrEagle23** [comment]
@ckeurk This was another recent issue #589 that was also related to the overall length of song titles and this causing problems for processing them later. This was recently fixed, and should have also fixed your scenario as well. Try it again and let me know if it helps.

**Comment by ckeurk** [comment]
Super merci ! It works
