### ISSUE TITLE
No sound after update

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#4972]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #4a77e82 (2022-01-08 5:46) • Docker • PHP 8.1

### What happened?

After upgrading to latest Rolling Release, there is no sound on my stations.
They are all on the air and now playing but simply no sound!

**Comment by SC2Mitch** [comment]
Need logs, a link to the public page or anything, this isn't really descriptive of anything.

**Comment by stardevelop** [comment]
I get this error on Chrome Developer tools / Console:
Uncaught (in promise) DOMException: Failed to load because no supported source was found.

**Comment by stardevelop** [comment]
On Firefox:

Invalid URI. Load of media resource  failed.
DOMException: The media resource indicated by the src attribute or assigned media provider object was not suitable.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://mytestradio.com/radio/8020/radio.mp3. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 401.

**Comment by SC2Mitch** [comment]
Have you configured your Access-Control-Allow-Origin in the system settings? 
![image](https://user-images.githubusercontent.com/29955942/148662074-988985ff-1d4a-4f81-86c0-33434b8ab141.png)
If no, then you'll need to configure this.

**Comment by stardevelop** [comment]
No. I have not configured this.
As a matter of fact, the stations were working fine without this configurations for a long time but suddenly there is no audio.

**Comment by stardevelop** [comment]
I set: Access-Control-Allow-Origin: *
Still no audio!

**Comment by stardevelop** [comment]
I found the issue!

It's a bug with Banned Countries option.
When I select a few countries to be banned on a station, AzuraCast asks for authentication for ALL countries (from any IP) and it doesn't let the station plays. When I clear the banned list, it works fine.

Please check and fix the bug.

**Comment by Vaalyn** [comment]
I can confirm this to be the source of this problem on my test installation too.

This is a very recent bug that is caused by the update that introduced Enums in the code base. Since my test installation was 1 or 2 commits before the introduction of Enums I checked if this is happening there and all was fine but after updating it showed the same problem.

I have already identified the exact cause of this bug and pushed an update with the fix.
The fix should be ready to install when [this GH action](https://github.com/AzuraCast/AzuraCast/actions/runs/1673786570) is green.

**Comment by SC2Mitch** [comment]
Thanks for the details

**Comment by stardevelop** [comment]
I can confirm that the bug is fixed in latest update Rolling Release #8f87fbb (2022-01-09 11:38). Thanks @Vaalyn

**Comment by Vaalyn** [comment]
> Hello, I'm running this version, `Powered by [AzuraCast](https://www.azuracast.com/) • Rolling Release #[18fe406](https://github.com/AzuraCast/AzuraCast/commit/18fe4060e7dc822209f62477a94fe6b64b84444d) (2022-06-07 9:00) • Docker • PHP 8.1`
> 
> If I listen to /public/radio_station I do not have sound
> 
> If I use/listen/radio.mp3 I hear sound.
> 
> How can I fix the player? <img alt="image" width="540" src="https://user-images.githubusercontent.com/32204564/172454315-d75ceccb-f6ec-49e4-8a1f-249b338a9133.png">

Your error is unrelated to this GitHub issue thread.

From looking at the error message and the response of the `/api/nowplaying` endpoint of your installation I can see that you do not have any mount points listed on 3 of the 4 stations. Make sure you have mount points on them and also make sure that all mount points that listeners should be able to see on the public page are set to `Show on Public Pages`
