### ISSUE TITLE
Adding directories to shuffled playlist adds media sorted by artist name instead of shuffled

### ISSUE THREAD

**Issue by zloysystem** [AzuraCast/AzuraCast#4975]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #8f87fbb (2022-01-09 11:38)

### What happened?

Good day gentlemen!
I know about the problem with the playback queue, I noticed a strange feature when updating the playlist with the current compositions, the queue gets knocked down and lines up in the order of playback of the compositions of the same name, see I will attach a gif
https://gifyu.com/image/Sbbf9
it turns out that the queue gets lost and after running the script that checks for new files in directories, the update process is carried out with the current tracks, which is identical to manually updating the playlist, as I understand it
*if the problem is known I am sorry then close the post :)

**Comment by Abqehebter** [comment]
I did not know this problem yet. I put this generally in connection with a few problems together with the song queue. I have already written about this here (https://github.com/AzuraCast/AzuraCast/issues/4962).
