### ISSUE TITLE
Listener Reports not working. 

### ISSUE THREAD

**Issue by themadcap1976** [AzuraCast/AzuraCast#4978]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #4a77e82 (2022-01-08 5:46) 

### What happened?

Listener reports not working. Only current listeners can be shown. When I run 7 day report, 30 day report or any report no results and yielded.

**Comment by themadcap1976** [comment]
I've attached a video of what I'm seeing, it's actually not reporting correctly. The numbers are not correct since we exceed that amount of listeners by a bit monthly.
[https://www.dropbox.com/s/t21gafwwt2mueh4/Screen%20Recording%202022-01-11%20at%203.13.55%20PM.mov?dl=0](url)

**Comment by SC2Mitch** [comment]
Okay, watched the video.

Can you reproduce this but do this instead
> Open up your browser console
> Go to Network Tab
> Reproduce the steps in the video.
> Wait for a response in the Network Tab.
> If anything is marked red, click on it then click on `response`

**Comment by themadcap1976** [comment]
DevTools failed to load source map: Could not load content for https://sail.yachtrockmiami.com/static/dist/lib/bootstrap/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by SC2Mitch** [comment]
Is there any other errors? That one is fine, as it's intended for developers.

**Comment by Samh629** [comment]
Hello just to say i'm having the exact issue had it for a good month now i've done what steps u said there get the same http error 404 but what i find interesting i don't know if this is any help all the statuses are pending. 

The dates are selected for last month but that was the listeners that are tuned in atm nothing loads on the site for the listeners etc for the selected time  

i would also like to add i have Days of Playback History to Keep

but when i've selected last month and waited to type this post the backend went down and isn't loading anymore 

to add in the azura cast app logs i fine these im not sure if they help but trying to find as much info to give to u 

[2022-01-18T10:33:30.517687+00:00] AzuraCast.CRITICAL: Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /var/azuracast/www/vendor/symfony/cache/Marshaller/DefaultMarshaller.php on line 85 [] []
[2022-01-18T10:33:33.364510+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":0,"workerName":"app_worker_0"} []

and server stats

8 vCores CPU

24 GB RAM

240 GB SSD

Ubuntu 20.04

 Rolling Release #ce0e9cc (2022-01-17 4:45) • Docker • PHP 8.1

<img width="1691" alt="image" src="https://user-images.githubusercontent.com/53228435/149919850-861026f4-49f3-4675-84fc-06748757215e.png">
<img width="973" alt="image" src="https://user-images.githubusercontent.com/53228435/149919878-a35add9c-62d5-4095-acfa-ea27bf172017.png">
<img width="1695" alt="image" src="https://user-images.githubusercontent.com/53228435/149920347-3d517237-55b5-483a-a9bf-e0751d140097.png">
<img width="416" alt="image" src="https://user-images.githubusercontent.com/53228435/149920898-37ff7d7b-a2ba-49f9-a79f-f165eff526ab.png">

**Comment by SC2Mitch** [comment]
> [2022-01-18T10:33:30.517687+00:00] AzuraCast.CRITICAL: Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /var/azuracast/www/vendor/symfony/cache/Marshaller/DefaultMarshaller.php on line 85 [] []

Your running into the PHP memory limit of 250 MB, you can change it in your azuracast.env 

```
# PHP Memory Limit
# Default: 128M
# PHP_MEMORY_LIMIT=
```

**Comment by Samh629** [comment]
Do i need to do docker-compose down and docker-compose up -d?

**Comment by SC2Mitch** [comment]
Yep, let us know if that doesnt work and Ill see what I can do

**Comment by Samh629** [comment]
no seems like that has nothing to do with the php  memory limit just seems to still be crashing when i ask to last months listeners stats but no errors come up at all cant see logs cos due to it crashing but on the f12 its come up as status pending or failed

**Comment by themadcap1976** [comment]
I'll run mine again and look for any errors in the logs.

Sometimes the 7 day report will run but will not report the correct
listener count.

**Comment by themadcap1976** [comment]
strange, I'm not seeing anything in the logs when I run this. At any given time, we have about 300 listeners, when I run a 7 day report, it doesn't reflect a 7 day report, sometimes it will report less listeners.

**Comment by themadcap1976** [comment]
I have noticed that when running the updates, the update tends to hang for a few minutes. This didn't happen before the reporting issue. Not sure it's related. I'm now on RR162cd14
![Screenshot_20220124-052433_Admin Hands](https://user-images.githubusercontent.com/32073620/150997520-c0009fe0-dbc7-4cb4-92f2-8007a9a4afdd.jpg)

**Comment by themadcap1976** [comment]
The reporting isn't working correctly, typically the station will have anywhere from 300 to 400 listeners at any given time, the 30 day report shows only 320 listeners for a 30 day period. This was confirmed via csv export. 

I'm also experiencing random crashes. I have another station on this Azuracast instance and it's not reporting listener history correctly either. 

![Screen Shot 2022-02-02 at 11 13 01 AM](https://user-images.githubusercontent.com/32073620/152193483-021fb34d-07a8-4b43-81f0-5e6125a74ec0.png)
![Screen Shot 2022-02-02 at 11 13 21 AM](https://user-images.githubusercontent.com/32073620/152193518-7a4b39d7-eeb0-4941-ab91-eeaa60684c39.png)
![Screen Shot 2022-02-02 at 11 13 35 AM](https://user-images.githubusercontent.com/32073620/152193541-a3a3a681-aaf7-430d-8d1c-1a8f9a670779.png)
![Screen Shot 2022-02-02 at 11 13 43 AM](https://user-images.githubusercontent.com/32073620/152193562-57c32f41-ff63-4b93-a23a-396fcee1e072.png)
![Screen Shot 2022-02-02 at 11 14 02 AM](https://user-images.githubusercontent.com/32073620/152193603-6841df5f-6ab5-4009-96fc-78b58d350f9d.png)

**Comment by themadcap1976** [comment]
Is there a way to purge listener data?

**Comment by SC2Mitch** [comment]
Sorry, I forgot to flag this up for the developers to review this, but if it's trying to pull so much data, it may be running into some issues. Perhaps there's some extra optimisations we could make.

**Comment by themadcap1976** [comment]
![Screenshot_20220213-151029_Admin Hands](https://user-images.githubusercontent.com/32073620/153773785-1154005f-e78d-483a-9226-8a7887893a6c.jpg)

Thank you, today it was audio cutouts, and maxed cpu.

**Comment by SC2Mitch** [comment]
Is the CPU usage happening when you're trying to pull the listener data?

**Comment by Samh629** [comment]
See my system must do that due to the whole website server crashes takes
5-10 mins for it to come back online

**Comment by SC2Mitch** [comment]
Can you list your specs? I'll try to see if I can create some listener data and do some tests.

**Comment by themadcap1976** [comment]
4vcpu 8gb RAM

**Comment by SC2Mitch** [comment]
Seeing somewhat similar results, perhaps we can indeed do some optimisations to see how we handle this data, flagging as a bug. Let's see what the team says.

**Comment by SC2Mitch** [comment]
Fix is forthcoming

Thanks for patience guys, we're seeing huge memory and CPU improvements
