### ISSUE TITLE
Super Administrator role can still be modified despite error thrown

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#4979]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#54dc259

### What happened?

The Super Administrator	role can still be modified by the Super Admin Permission despite an error be thrown by AzuraCast, thus leading to account lockout by a server admin. 

While it's _very silly_ for an admin to do as the only way to recover the account is via CLI, we should harden the error to stop it from saving progress and ensuring this embarrassing move never happens. 

![image](https://user-images.githubusercontent.com/29955942/148979370-ec7e266c-1b7a-4a92-9592-42e6d1516a81.png)

### Relevant log output

```shell
N/A
```

**Comment by Vaalyn** [comment]
Small note for the future, when this is fixed we should probably add a test case to our functional tests that ensures this stays fixed.
