### ISSUE TITLE
Live streaming using Streamer/DJ Accounts do not work on some encoders

### ISSUE THREAD

**Issue by inetactief** [AzuraCast/AzuraCast#498]
We try to use DSP plugin Winamp or Altacast using "Streamer/DJ Accounts" for live streaming  it do not work good.
When we use BUTT is works fine. We use:
AzuraCast v0.8.1-2018.02 Beta (Docker)
PHP 7.2.2-3+ubuntu16.04.1+

**Comment by Roforum** [comment]
Use IceCast port and will work. For some reason ShoutCast port don`t work.

**Comment by inetactief** [comment]
Okay i understand it a bug. We wil use Icecast
