### ISSUE TITLE
[Ansible] Install Error (Old version PHP processing error)

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#4980]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

0.15.0 (Ubuntu 20.04 LTS)

### What happened?

While installing the Ansible version, the old version cannot exceed the php versions field. Installation fails and stops. I tried updating but the result is still the same. The installation should pass and continue if there is no older version.

Error: https://prnt.sc/26crovc

**Comment by Vaalyn** [comment]
It seems like our ansible task for removing old php packages does not expect packages to be completely unavailable in the package manager. Maybe someone who know more about the ansible package manager module can chime in here.

Currently having some issues with lightshot not loading correctly for me so for easier debugging I'll copy & paste the screenshot into this comment here:

![image](https://user-images.githubusercontent.com/13745863/149172851-28c17b7b-41c2-482d-bef9-8e9fe2dc90f1.png)

**Comment by aurelienmaury** [comment]
@ogrenci01 What distribution and version are you targeting please?

**Comment by krono86** [comment]
Same here with Ubuntu Server 2020.04.3 LTS.

**Comment by ogrenci01** [comment]
Both Ubuntu 20.04 and 18.04 have the same issue.

**Comment by ogrenci01** [comment]
Apologies to everyone.

I got an error when I tried to reinstall AzuraCast. It has nothing to do with the previous problem, but the installation does not continue. The update does not continue.

Both Ubuntu 20.04 and 18.04 have the same issue.
![xxx](https://user-images.githubusercontent.com/24523085/149297401-f21a4e7c-e6e8-484f-82f2-783a00856962.png)

**Comment by SlvrEagle23** [comment]
@ogrenci01 This should also be fixed now.

**Comment by ogrenci01** [comment]
@SlvrEagle23 try again now. I will check it. Thanks a lot. Good job.

**Comment by ogrenci01** [comment]
@SlvrEagle23

I'm sorry, but now there is a different problem. I am getting an error at this stage.

![xxx](https://user-images.githubusercontent.com/24523085/149302973-420ab90e-e69f-4841-8d99-c1a082e24040.png)

**Comment by ogrenci01** [comment]
@SlvrEagle23 I will try now.

**Comment by SlvrEagle23** [comment]
@ogrenci01 I've uploaded a possible fix for this issue; it's strongly recommended that you run on Ubuntu 20.04 for any new installations, as older Ubuntu versions will fall out of support several years sooner.
