### ISSUE TITLE
Unable to retrieve data from beyond the last two months

### ISSUE THREAD

**Issue by christofferhh** [AzuraCast/AzuraCast#4982]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

• v0.12.3 Stable

### What happened?

Hi,

I need to submit my royalty report at the moment but unfortunately I'm unable to retrieve more than the last 2 months worth of playback information. The server has been running since May 2021 but it has only stored the last two months. Any way to retrieve this information, and how can I ensure this doesn't happen again?

**Comment by SC2Mitch** [comment]
![image](https://user-images.githubusercontent.com/29955942/149227533-731f3248-1faa-40ce-bb0b-518b3062a2d4.png)
Can you check the settings for this field? `Admin/System Settings`

**Comment by christofferhh** [comment]
Sorry for the slow reply. I've been a bit busy and then caught COVID. You're right, that's the setting. Was too thick to realise there was a setting like this. SOCAN is not going to be happy with me, haha.
