### ISSUE TITLE
Live Dj's booted from stream

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#4983]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #b7a7d8e (2022-01-12 4:51 and previous

### What happened?

Pursuant to discussion https://github.com/AzuraCast/AzuraCast/discussions/4963 and LS issue https://github.com/savonet/liquidsoap/issues/2129 here are a few more logs of incidents where DJ's are being dropped on a bogus 401 error, and the last one with no error at all;
[DJ dropped.txt](https://github.com/AzuraCast/AzuraCast/files/7859160/DJ.dropped.txt)
The operator noted that his SAM encoder was showing a bottleneck and buffer overrun. Log shows error 401 just before... He then proceeded to stop encoder and restart which apparently reset the API and LS

Same scenario again with different operator on next day.  Error 401 kills the live stream which entails a buffer overrun in streaming app...
[Error 401.txt](https://github.com/AzuraCast/AzuraCast/files/7859184/Error.401.txt)
![Image2](https://user-images.githubusercontent.com/66107794/149251309-3879e2c3-1289-4e29-b7a6-18ab1062ae83.jpg)

Then today (01-12) another episode where AutoDJ kicked in, this time with no reported error. 
[Speedy Kicked off.txt](https://github.com/AzuraCast/AzuraCast/files/7859203/Speedy.Kicked.off.txt)
I had eyes on the AzuraCast console at the time so I was able to kill the encoder and restart before SAM showed a buffer overrun...

It therefore seem to me that the problem resides with the API call authenticating Dj's...

### Relevant log output

```shell
See above...
```

**Comment by SpeedyCharly** [comment]
Excuse me, but did you look at the evident timeline and chain on events clearly visible in the second instance - error 401 occurerd at 7:04 when the operator clearly hadn't changed his credentials on the fly during the API call.  This caused the server to refuse the stream from SAM which showed a buffer overrun at 7:06... clearly not the other way round as you suggest. 

I have personally witnessed several of these occurrences and in none of them was the connection to the server ever lost - we would have lost connection to out chatroom at the same time.

**Comment by SC2Mitch** [comment]
As someone who is legitimately trying to find alternative solutions to help you with this, I don't understand the way you react sometimes, it's not the first time you've acted like it, but anyway. 

>Excuse me, but did you look at the evident timeline and chain on events clearly visible in the second instance - error 401 occurred at 7:04 where the operator obviously hadn't changed his credentials on the fly during the API call

Yep, I did indeed look at the files you provided, this line specifically `2022/01/09 20:21:30 [harbor:4] Returned 401: wrong auth.`  but I'm struggling to reproduce this on my local and production machine. 

> And... why would you suggest that we go from a battle tank to pop-guns for streaming???

I'm the most experienced with Mixx as it's open-source compared to SAM's closed source nature.

These types of issues are incredibly hard for us to debug and find out what exactly is going on, but some patience is highly appreciated.

**Comment by SpeedyCharly** [comment]
I am being patient... have been pursuing this issue for weeks... It seemed to me that you were dismissing the whole thing out of hand with your first comment.  Sorry it I read that wrong.

This is off topic, but I'll indulge you; I also happen to have experience with both Mixxx and VirtualDj.  Mixxx in it's first iterations was loosely based on Sam Broadcaster and it gradually evolved to become a virtual clone of VirtualDj today.  VirtualDj was not initially designed as a streaming app; such functions were a later addition to hopefully broaden their market. It is therefore somewhat clunky and underwhelming in most streaming applications.  Yes SAM is a proprietary animal, but you have to give it the credit it deserves as one of the best streaming solutions out there and is largely used by most commercial radio stations with a web presence and work-from-home dj's.

**Comment by SpeedyCharly** [comment]
DJs still getting dropped randomly; here is the last incident following right after major bufffer overrun issue in Azuracast.
Log of incident here;
[DJ Dropped 01-20.txt](https://github.com/AzuraCast/AzuraCast/files/7910718/DJ.Dropped.01-20.txt)

And here is the SAM log in the same timeframe;
![SAM Log](https://user-images.githubusercontent.com/66107794/150473428-b6dc6aa6-f5c9-4660-aa3a-75c3b6a13827.jpg)

The AzuraCast buffer issue happened just seconds before SAM also reported a buffer overrun and the operator didn't observe a drop of internet connection at that time...  If there a cause to effect relation here???
