### ISSUE TITLE
Ansible installation error

### ISSUE THREAD

**Issue by d-trax** [AzuraCast/AzuraCast#4984]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.15.0

### What happened?

Hi there, 
I've been using Azuracast with Ansible on my Raspberry Pi 4 B(4GB) sine last year, and it was great. 
Tried to update my Ansible installation from 0.14.1 to 0.15.0 and got an odd error -

```
TASK [php : Remove Old PHP Libraries] *******************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package(s) matching 'php5-*' available"}
```

Tried with `./update.sh` and `./update.sh --full` and got the same error once again. Tried with a clean install of Ubuntu 20.4.3 and got the same error again. 
 Now I can't install Azuracast using Ansible at all. What should I do, or what am I doing wrong?
Thanks in advance!

P.S. tried the Docker install method, which worked, but it uses alot more resources than the Ansible install method, which isn't a prefered option at least for now :)

**Comment by SC2Mitch** [comment]
This issue was fixed on the rolling release branch, can you give it a try?

**Comment by d-trax** [comment]
Sorry for the dumb qustion, but how to do that? Never had to install a rolling release before, and all the info I found is for Docker.

**Comment by SC2Mitch** [comment]
You ask a great question, we don't have anything in our docs to cover that. Give me sometime to review what options you got.

**Comment by d-trax** [comment]
Ok, so I got past that php-5* error, but stopped again here -

```
TASK [ufw : UFW - Disable all other incoming by default] *********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "commands": ["/usr/sbin/ufw status verbose"], "msg": "ERROR: problem running iptables: modprobe: FATAL: Module i
p_tables not found in directory /lib/modules/5.4.0-1045-raspi\niptables v1.8.4 (legacy): can't initialize iptables table `filter': Table does not exist (do you ne
ed to insmod?)\nPerhaps iptables or your kernel needs to be upgraded.\n\n\n"}
```

I've encountered this error in the past, which was due to upgraded kernel, but I will try to bypass it again with reinstalling kernel modules.

**Comment by d-trax** [comment]
Nope, just can't get Azuracast to install via Ansible. Reinstalled kernel modules to fix up iptables, but then got 10 kilometeres of error messages, which I didn't even read. Thanks for the help anyways guys. God bless you!

**Comment by d-trax** [comment]
Update: Got it working, and I can confirm that all the trouble is coming from Ubuntu itself somehow. Reinstalled the kernel with kernel modules several times and it somehow worked without any errors in the end.

**Comment by SC2Mitch** [comment]
Glad to hear it's resolved.

**Comment by RaymondSchnyder** [comment]
Is it possible to "backport" a fix the installation error regarding php5 disappears?

**Comment by SlvrEagle23** [comment]
@RaymondSchnyder Since this is preventing any upgrades on Ansible, I went ahead and did this, since I'm not sure when the 0.15.1 release will be.
