### ISSUE TITLE
A song that is already aired gets re-cued again immediately

### ISSUE THREAD

**Issue by kkabbers** [AzuraCast/AzuraCast#4988]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #09d79b7 (2022-01-14 10:19) • Docker • PHP 8.1

### What happened?

There are three issues here:
1. Timing is not synchronising in line with the scheduled playlist and a scheduled play list is activated five minutes before the hour.
2. A song that is aired is re-cued immediately, but it does not get aired again though. However, this impacts on the timing and hence the playlist that is suppose to be activated on the hour gets readjusted to play five minutes before the hour. Further, the song that was already aired is captured as the next upcoming song on the profile page, but of course it gets skipped. It was not like this before.
3. The new version is not enabling us to delete the top three rows of the upcoming song que. The song that is re-cued as mentioned in 2 is in the top three of these cues and it does not allow any action that could be taken to rectify.

**Comment by SC2Mitch** [comment]
Can you make some separate reports? It's hard to track multiple topics at once. Ideally include the first two as 1, and the 3rd option as a unique report. 

Thanks.

**Comment by kkabbers** [comment]
Hi Mitch,

I have prepared the attached report.

Thank you.
Best,
Kabbers

________________________________

**Comment by kkabbers** [comment]
Hi Mitch,

here is my second report.

Thanks
Kabbers

________________________________

**Comment by kkabbers** [comment]
Not sure the reports were received but am uploading them here again
[Azuracast - Report 1.pdf](https://github.com/AzuraCast/AzuraCast/files/7878868/Azuracast.-.Report.1.pdf)
[Azuracast - Report 2.pdf](https://github.com/AzuraCast/AzuraCast/files/7878870/Azuracast.-.Report.2.pdf)

**Comment by farhad-motechwa** [comment]
Hi Mitch, I am attaching the log file for you. I am helping @kkabers with the Azuracast deployment[](url
[Azuracast Log.txt](https://github.com/AzuraCast/AzuraCast/files/7880863/Azuracast.Log.txt)
)
