### ISSUE TITLE
Request only work on default playlist

### ISSUE THREAD

**Issue by inetactief** [AzuraCast/AzuraCast#499]
We like to use more request songs in other playlist. Now it works only in the default playlist.

We like to have a option in edit a playlist to enabeld request.

AzuraCast v0.8.1-2018.02 Beta (Docker)
PHP 7.2.2-3+ubuntu16.04.1+

**Comment by SlvrEagle23** [comment]
@inetactief This feature was recently added as part of the resolution for #547. You can now specify each playlist as being included in requests, independent of its scheduling.
