### ISSUE TITLE
2022/01/17 12:02:09 [clock.main:2] We must catchup 1.77 seconds!

### ISSUE THREAD

**Issue by vinzity** [AzuraCast/AzuraCast#4994]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

our sound frequently stop auto sound and also disconnected dj with error 2022/01/17 12:02:09 [clock.main:2] We must catchup 1.77 seconds! how can resolving this tnx

### Relevant log output

2022/01/17 12:04:35 [clock.main:2] We must catchup 5.13 seconds!
2022/01/17 12:04:36 [clock.main:2] We must catchup 6.17 seconds!
2022/01/17 12:04:38 [clock.main:2] We must catchup 7.14 seconds!
2022/01/17 12:04:39 [clock.main:2] We must catchup 6.51 seconds!
2022/01/17 12:04:40 [clock.main:2] We must catchup 6.89 seconds!
2022/01/17 12:04:41 [clock.main:2] We must catchup 7.41 seconds!
2022/01/17 12:04:42 [clock.main:2] We must catchup 6.54 seconds!
2022/01/17 12:04:43 [clock.main:2] We must catchup 6.95 seconds!
2022/01/17 12:04:44 [clock.main:2] We must catchup 6.87 seconds!
2022/01/17 12:04:45 [clock.main:2] We must catchup 7.39 seconds!
2022/01/17 12:04:46 [clock.main:2] We must catchup 7.18 seconds!
2022/01/17 12:04:47 [clock.main:2] We must catchup 7.10 seconds!
2022/01/17 12:04:48 [clock.main:2] We must catchup 7.28 seconds!
2022/01/17 12:04:50 [clock.main:2] We must catchup 7.69 seconds!
2022/01/17 12:04:51 [clock.main:2] We must catchup 7.01 seconds!
2022/01/17 12:04:52 [clock.main:2] We must catchup 7.34 seconds!
2022/01/17 12:04:53 [clock.main:2] We must catchup 6.37 seconds!
2022/01/17 12:04:54 [clock.main:2] We must catchup 6.22 seconds!
2022/01/17 12:04:55 [clock.main:2] We must catchup 6.04 seconds!
2022/01/17 12:04:56 [clock.main:2] We must catchup 6.01 seconds!

**Comment by SpeedyCharly** [comment]
Seems the same as here;
https://github.com/AzuraCast/AzuraCast/issues/4783

**Comment by SC2Mitch** [comment]
Hi, we believe this issue was fixed in our rolling releases. Can you update your machine and let us know if it's still not working.

If not, refer to our master issue. 

https://github.com/AzuraCast/AzuraCast/issues/5017

**Comment by SpeedyCharly** [comment]
I believe you've closed this prematurely - I am on the latest rolling release and I still see issues with this ...

**Comment by SC2Mitch** [comment]
We have very limited resources, creating a master issue is a lot easier for us to track things in one thread with the assistance of the Liquidsoap team.
