### ISSUE TITLE
Azura cast widgets, when embeded on site does not work

### ISSUE THREAD

**Issue by FabianZacchary** [AzuraCast/AzuraCast#4999]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

When we embeded an already given widgets of the radio into our wordpress site, it works for 20 minutes and then stopes working, music doesnt play but you will see time go by on the radio.

**Comment by SC2Mitch** [comment]
After it stops working, check your browser logs or docker logs, without it, we cant be helpful because this is lacking in information.
