### ISSUE TITLE
Twitter Web Hook Enhancement 

### ISSUE THREAD

**Issue by kbysfm** [AzuraCast/AzuraCast#500]
Would it be possible to add an option to tweet now playing data at certain intervals? Not sure exactly at what intervals but I think having the option for 15, 30, 45 mins would be a good place to start. The current options are great but could annoy followers if you're blowing up their timeline.

Thanks!

**Comment by SlvrEagle23** [comment]
@kbysfm The latest update introduces custom rate limit support for Twitter web hooks, so you can configure the web hook to only send one tweet per time period, from 15 seconds to an hour.

@br0kenlink There is another currently pending enhancement (#753) that you should follow for updates specific to the "Mark as Jingle" request.
