### ISSUE TITLE
https invalid certificate on icecast port

### ISSUE THREAD

**Issue by zloysystem** [AzuraCast/AzuraCast#5003]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #8e58352 (2022-01-18 20:01)

### What happened?

updated to the latest version and the certificate on the icecast port broke, it works on nginx, but all links to directories, etc., I have the form https://radio:8000/mount
and accordingly there is no sound anywhere now, how to fix it?
the system was specially reinstalled on ubuntu 20.04.3 LTS because https works correctly on the port on it, and on debian 10 the installation of azuracast failed (the problem was voiced but did not wait for an answer) and now it does not work on ubuntu
![IMG_20220119_041546](https://user-images.githubusercontent.com/26243386/150045152-fb85c63e-a9e3-4b18-9e50-3cb940267fe0.jpg)

**Comment by SlvrEagle23** [comment]
@zloysystem This should be fixed in the latest Rolling Release version.

**Comment by SlvrEagle23** [comment]
@zloysystem Are you running SSL on a nonstandard port? You may need to switch it back to port 443 for the provisioning step to work correctly, as you would during normal SSL certificate renewal.

**Comment by zloysystem** [comment]
@SlvrEagle23 This should be fixed in the latest Rolling Release version.
But I'm using the latest Rolling Release.

Using everything as standard, I don’t make any changes to the configuration files, I say updated and that’s it

**Comment by zloysystem** [comment]
@SlvrEagle23 repeatedly ran the update script, and in some strange way to issue certificates
