### ISSUE TITLE
Station language error

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#5005]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #ce0e9cc (2022-01-17 4:45)

### What happened?

Noticed recently that the language was wrong in our station's widgets...Not sure when it happened but recent updates haven't solved this.
When I look at widgets within my dashboard they appear in French, but once posted to website they come out in English;
Dashboard;
![Lang1](https://user-images.githubusercontent.com/66107794/150171348-9c98b12b-5d91-4b71-8bc7-0ce3d8f3938a.jpg)
Website;
![Lang2](https://user-images.githubusercontent.com/66107794/150171469-412ff654-5886-4c4a-aae8-4362d9c9e912.jpg)

The same error also occurs on public page... I don't think it is a navigator issue since it is set to NOT translate French.  Looked in dashboard for a switch to set station language which may be different from the operator's account language, but to no avail.   Is there such a switch somewhere?

### Relevant log output

```shell
N/A
```

**Comment by SlvrEagle23** [comment]
@SpeedyCharly If you're not logged in (and when viewing an embed on the web site, it's quite possible it doesn't consider you logged in), then it should use your browser language preference. If your browser's primary language is French, it should pick that out of the available locales.

**Comment by SpeedyCharly** [comment]
Ok got you and you are right - the system was detecting my navigator language which was set to English - switching to French returned the modules to French.

But still, wouldn't it be a better idea to set an output language in AzuraCast then let the listeners choose to translate or not?
