### ISSUE TITLE
Delay in playlist playback 

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#5014]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.15

### What happened?

Since the update to the latest stable version of Azuracast, an error that seemed resolved in previous updates repeats. This is the delay in the start of playlist playback. For example, a playlist that plays a program at 8 in the morning starts minutes late because a music song is always coming through. It is not placed at the beginning of the queue, but a musical theme is sneaked in that causes a delay of minutes and then that playlist sounds.

The strategy that we are following is to program the playlists of these programs with several minutes in advance. But if the previous content ends after the scheduled start time of that playlist, a music track is sneaked in and a delay is generated again.

What possible solution do you see for this error?

**Comment by fidegr** [comment]
Hello, here is an example of delay. A playlist that is scheduled for 10:00 starts playing 5 minutes late.

![image](https://user-images.githubusercontent.com/16152034/150633539-b16415e3-516b-47c9-a521-aafd1973f994.png)


```
2022/01/22 09:57:10 [lang:3] AzuraCast Feedback Response: OK
2022/01/22 09:59:39 [decoder:2] Decoding "/var/azuracast/stations/Agora_sol_radio/media/Música Almaina/Marie Knight - Come On Baby .mp3" ended: Mad.End_of_stream.
2022/01/22 09:59:39 [next_song:3] Prepared "/var/azuracast/stations/Agora_sol_radio/media/Música Almaina/The (International) Noise Conspiracy - Smash It Up.ogg" (RID 2).
2022/01/22 09:59:39 [cue_next_song:3] Cueing in...
2022/01/22 09:59:39 [lang:3] autodj_next_song: Sending AzuraCast API Call...
2022/01/22 09:59:39 [crossfade_0:3] Analysis: -28.697102dB / -15.137187dB (0.68s / 0.68s)
2022/01/22 09:59:40 [crossfade_0:3] new >= old + margin, old >= medium and new <= high.
2022/01/22 09:59:40 [crossfade_0:3] New source is significantly louder than old one.
2022/01/22 09:59:40 [crossfade_0:3] Transition: crossed, fade-out.
2022/01/22 09:59:40 [lang:3] AzuraCast Feedback Response: OK
2022/01/22 09:59:40 [lang:3] autodj_next_song: AzuraCast API Response: annotate:title="Living a Lie",artist="The BellRays",duration="134.27",song_id="ccfc8dc44e10987c30d12697932c441d",media_id="53202",liq_amplify="0.00dB",playlist_id="879":/var/azuracast/stations/Agora_sol_radio/media/Música Almaina/The Bellrays - Living A Lie.mp3
2022/01/22 10:02:52 [decoder:2] Decoding "/var/azuracast/stations/Agora_sol_radio/media/Música Almaina/The (International) Noise Conspiracy - Smash It Up.ogg" ended: Ogg.End_of_stream.
2022/01/22 10:02:52 [next_song:3] Prepared "/var/azuracast/stations/Agora_sol_radio/media/Música Almaina/The Bellrays - Living A Lie.mp3" (RID 3).
2022/01/22 10:02:52 [cue_next_song:3] Cueing in...
2022/01/22 10:02:52 [lang:3] autodj_next_song: Sending AzuraCast API Call...
2022/01/22 10:02:52 [crossfade_0:3] Analysis: -75.517265dB / -15.281945dB (0.72s / 0.72s)
2022/01/22 10:02:52 [crossfade_0:3] new >= old + margin, old <= medium and new <= high.
2022/01/22 10:02:52 [crossfade_0:3] Do not fade if it's already very low.
2022/01/22 10:02:52 [crossfade_0:3] Transition: crossed, no fade.
2022/01/22 10:02:53 [lang:3] autodj_next_song: AzuraCast API Response: annotate:title="party mf 80958692 feed 1",artist="punky-reggae",duration="3565.00",song_id="1ab75f7ece21b84af1c46116f2df1790",media_id="56327",liq_amplify="0.00dB",playlist_id="876":/var/azuracast/stations/Agora_sol_radio/media/Podcast/1H/colmenas_tapizadas/punky-reggae-party_mf_80958692_feed_1.mp3
2022/01/22 10:02:53 [lang:3] AzuraCast Feedback Response: OK
2022/01/22 10:05:05 [decoder:2] Decoding "/var/azuracast/stations/Agora_sol_radio/media/Música Almaina/The Bellrays - Living A Lie.mp3" ended: Mad.End_of_stream.
2022/01/22 10:05:06 [next_song:3] Prepared "/var/azuracast/stations/Agora_sol_radio/media/Podcast/1H/colmenas_tapizadas/punky-reggae-party_mf_80958692_feed_1.mp3" (RID 4).
2022/01/22 10:05:06 [cue_next_song:3] Cueing in...
2022/01/22 10:05:06 [lang:3] autodj_next_song: Sending AzuraCast API Call...
2022/01/22 10:05:06 [crossfade_0:3] Analysis: -13.945026dB / -13.536029dB (0.72s / 0.72s)
2022/01/22 10:05:06 [crossfade_0:3] No transition: using default.
2022/01/22 10:05:06 [lang:3] AzuraCast Feedback Response: OK
2022/01/22 10:05:06 [lang:3] autodj_next_song: AzuraCast API Response: annotate:title="Cuna_Radio_Almaina_6",artist="TROUPE PLEGADERO BAJO",duration="22.25",song_id="9d77298996c183b7c35357e7aaf77111",media_id="51478",liq_amplify="0.00dB",playlist_id="14":/var/azuracast/stations/Agora_sol_radio/media/Cuñas Almaina/via_libre_con_radio_almaina.mp3
2022/01/22 10:05:07 [lang:3] AzuraCast Feedback Response: OK
```

**Comment by YosefAdPro** [comment]
Seems like a problem similar to what has been reported here in the past.
the problem is still there.

https://github.com/AzuraCast/AzuraCast/issues/4765#issuecomment-965510131


https://github.com/AzuraCast/AzuraCast/issues/4952

**Comment by fidegr** [comment]
Another example of delay introducing a podcast playlist.
This playlist was scheduled at 3:59 p.m., but instead of starting after a jingle, a theme song plays and starts playing at 4:04 p.m.

![image](https://user-images.githubusercontent.com/16152034/151417230-efdb07d4-eb17-4f79-b2e8-389f35dc1b33.png)



![image](https://user-images.githubusercontent.com/16152034/151416972-faed5470-1c51-4187-b7f7-0954d14b7515.png)



2022/01/27 15:53:54 [lang:3] autodj_next_song: AzuraCast API Response: annotate:title="Trouble",artist="Skindred",duration="229.33",song_id="3129ac856cb039bc65a89d97a4df4fe9",media_id="52647",liq_amplify="0.00dB",playlist_id="879":/var/azuracast/stations/Agora_sol_radio/media/Música Almaina/Skindred - Trouble.mp3
2022/01/27 15:56:56 [decoder:2] Decoding "/var/azuracast/stations/Agora_sol_radio/media/Música Almaina/The Julie Ruin - Stop Stop.ogg" ended: Ogg.End_of_stream.
2022/01/27 15:56:57 [next_song:3] Prepared "/var/azuracast/stations/Agora_sol_radio/media/Música Almaina/Skindred - Trouble.mp3" (RID 3).
2022/01/27 15:56:57 [cue_next_song:3] Cueing in...
2022/01/27 15:56:57 [lang:3] autodj_next_song: Sending AzuraCast API Call...
2022/01/27 15:56:57 [crossfade_0:3] Analysis: -15.060633dB / -70.202290dB (0.68s / 0.68s)
2022/01/27 15:56:57 [crossfade_0:3] No transition: using default.
2022/01/27 15:56:57 [lang:3] autodj_next_song: AzuraCast API Response: annotate:title="Cuna_Radio_Almaina_2",artist="TROUPE PLEGADERO BAJO",duration="6.77",song_id="20acc3724de465be72f0e6a3b656a846",media_id="51468",liq_amplify="0.00dB",playlist_id="14":/var/azuracast/stations/Agora_sol_radio/media/Cuñas Almaina/cuna_radio_almaina_2~0.mp3
2022/01/27 15:56:57 [lang:3] AzuraCast Feedback Response: OK
2022/01/27 15:56:57 [lang:3] AzuraCast Feedback Response: OK
2022/01/27 16:00:45 [decoder:2] Decoding "/var/azuracast/stations/Agora_sol_radio/media/Música Almaina/Skindred - Trouble.mp3" ended: Mad.End_of_stream.
2022/01/27 16:00:46 [next_song:3] Prepared "/var/azuracast/stations/Agora_sol_radio/media/Cuñas Almaina/cuna_radio_almaina_2~0.mp3" (RID 0).
2022/01/27 16:00:46 [cue_next_song:3] Cueing in...
2022/01/27 16:00:46 [lang:3] autodj_next_song: Sending AzuraCast API Call...
2022/01/27 16:00:46 [crossfade_0:3] Analysis: -50.605943dB / -27.008066dB (0.72s / 0.72s)
2022/01/27 16:00:46 [crossfade_0:3] new >= old + margin, old <= medium and new <= high.
2022/01/27 16:00:46 [crossfade_0:3] Do not fade if it's already very low.
2022/01/27 16:00:46 [crossfade_0:3] Transition: crossed, no fade.
2022/01/27 16:00:46 [lang:3] AzuraCast Feedback Response: OK
2022/01/27 16:00:46 [lang:3] autodj_next_song: AzuraCast API Response: annotate:title="That's All I Need For You",artist="The Birds",duration="185.75",song_id="6e544ca46eb7bd32b1ce10fc3aae303f",media_id="52679",liq_amplify="0.00dB",playlist_id="879":/var/azuracast/stations/Agora_sol_radio/media/Música Almaina/The Birds - That's All I Need For You.ogg
2022/01/27 16:00:51 [decoder:2] Decoding "/var/azuracast/stations/Agora_sol_radio/media/Cuñas Almaina/cuna_radio_almaina_2~0.mp3" ended: Mad.End_of_stream.
2022/01/27 16:00:52 [next_song:3] Prepared "/var/azuracast/stations/Agora_sol_radio/media/Música Almaina/The Birds - That's All I Need For You.ogg" (RID 1).
2022/01/27 16:00:52 [cue_next_song:3] Cueing in...
2022/01/27 16:00:52 [lang:3] autodj_next_song: Sending AzuraCast API Call...
2022/01/27 16:00:52 [crossfade_0:3] Analysis: -34.874406dB / -83.685717dB (0.68s / 0.68s)
2022/01/27 16:00:52 [crossfade_0:3] No transition: using default.
2022/01/27 16:00:53 [lang:3] autodj_next_song: AzuraCast API Response: annotate:title="Metropolice. La ciudad de los polis",artist="LDD",duration="4508.00",song_id="3f4486a3d2a59a081d58675e1d2d93a2",media_id="56468",liq_amplify="0.00dB",playlist_id="861":/var/azuracast/stations/Agora_sol_radio/media/Podcast/2H/la_linterna_de_diogenes/ldd15x14-metropolice-la-ciudad-polis_mf_81279351_feed_1.mp3
2022/01/27 16:00:53 [lang:3] AzuraCast Feedback Response: OK
2022/01/27 16:00:53 [lang:3] AzuraCast Feedback Response: OK
2022/01/27 16:03:57 [decoder:2] Decoding "/var/azuracast/stations/Agora_sol_radio/media/Música Almaina/The Birds - That's All I Need For You.ogg" ended: Ogg.End_of_stream.
2022/01/27 16:03:58 [next_song:3] Prepared "/var/azuracast/stations/Agora_sol_radio/media/Podcast/2H/la_linterna_de_diogenes/ldd15x14-metropolice-la-ciudad-polis_mf_81279351_feed_1.mp3" (RID 6).
2022/01/27 16:03:58 [cue_next_song:3] Cueing in...
2022/01/27 16:03:58 [lang:3] autodj_next_song: Sending AzuraCast API Call...
2022/01/27 16:03:58 [crossfade_0:3] Analysis: -45.790156dB / -19.196868dB (0.68s / 0.68s)
2022/01/27 16:03:58 [crossfade_0:3] new >= old + margin, old <= medium and new <= high.
2022/01/27 16:03:58 [crossfade_0:3] Do not fade if it's already very low.
2022/01/27 16:03:58 [crossfade_0:3] Transition: crossed, no fade.
2022/01/27 16:03:58 [lang:3] AzuraCast Feedback Response: OK
2022/01/27 16:03:58 [lang:3] autodj_next_song: AzuraCast API Response: annotate:title="29",artist="Hazte soci@ de Radio Almaina para que la tortilla se vuelva",duration="43.39",song_id="85943528c6b55e89a60c1a8dd110660e",media_id="51496",liq_amplify="0.00dB",playlist_id="846":/var/azuracast/stations/Agora_sol_radio/media/Campañas - Anuncios Almaina/cun-cc-83as_socies_-28garroti-cc-81n-29.mp3
2022/01/27 17:19:05 [decoder:2] Decoding "/var/azuracast/stations/Agora_sol_radio/media/Podcast/2H/la_linterna_de_diogenes/ldd15x14-metropolice-la-ciudad-polis_mf_81279351_feed_1.mp3" ended: Mad.End_of_stream.
