### ISSUE TITLE
help install 

### ISSUE THREAD

**Issue by fast97** [AzuraCast/AzuraCast#5018]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

hello, I would like to know if it is possible to install azuracat on promox container debian 10? I tried but the installation hangs here:

[+] Running 6/6
 ⠿ nginx_proxy Pulled                                                                                                                                                                        2.7s
 ⠿ mariadb Pulled                                                                                                                                                                            2.6s
 ⠿ redis Pulled                                                                                                                                                                              2.8s
 ⠿ nginx_proxy_letsencrypt Pulled                                                                                                                                                            2.2s
 ⠿ web Pulled                                                                                                                                                                                2.4s
 ⠿ stations Pulled                                                                                                                                                                           1.6s
[+] Running 2/0
 ⠿ Container azuracast_mariadb   Running                                                                                                                                                     0.0s
 ⠿ Container azuracast_stations  Running                                                                                                                                                     0.0s
[+] Running 0/1
 ⠙ Container azuracast_redis  Starting                                                                                                                                                       2.2s
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: write sysctl key net.core.somaxconn: open /proc/sys/net/core/somaxconn: no such file or directory: unknown
[+] Running 2/3
 ⠿ Container azuracast_mariadb   Running                                                                                                                                                     0.0s
 ⠿ Container azuracast_stations  Running                                                                                                                                                     0.0s
 ⠼ Container azuracast_redis     Starting                                                                                                                                                    2.3s
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: write sysctl key net.core.somaxconn: open /proc/sys/net/core/somaxconn: no such file or directory: unknown
root@streamaudio:/var/azuracast# 

***************
Thank you for your help

### Relevant log output

```shell
[+] Running 6/6
 ⠿ nginx_proxy Pulled                                                                                                                                                                        2.7s
 ⠿ mariadb Pulled                                                                                                                                                                            2.6s
 ⠿ redis Pulled                                                                                                                                                                              2.8s
 ⠿ nginx_proxy_letsencrypt Pulled                                                                                                                                                            2.2s
 ⠿ web Pulled                                                                                                                                                                                2.4s
 ⠿ stations Pulled                                                                                                                                                                           1.6s
[+] Running 2/0
 ⠿ Container azuracast_mariadb   Running                                                                                                                                                     0.0s
 ⠿ Container azuracast_stations  Running                                                                                                                                                     0.0s
[+] Running 0/1
 ⠙ Container azuracast_redis  Starting                                                                                                                                                       2.2s
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: write sysctl key net.core.somaxconn: open /proc/sys/net/core/somaxconn: no such file or directory: unknown
[+] Running 2/3
 ⠿ Container azuracast_mariadb   Running                                                                                                                                                     0.0s
 ⠿ Container azuracast_stations  Running                                                                                                                                                     0.0s
 ⠼ Container azuracast_redis     Starting                                                                                                                                                    2.3s
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: write sysctl key net.core.somaxconn: open /proc/sys/net/core/somaxconn: no such file or directory: unknown
root@streamaudio:/var/azuracast#
```

**Comment by SlvrEagle23** [comment]
@fast97 This should be possible if you edit your `.env` file (note, it's a file literally named "`.env`" and not "azuracast.env") and add the following line:

```
AZURACAST_COMPOSE_PRIVILEGED=false
```

...then re-run the install process. It will pull any privileged settings that may not work in virtualized environments, and should allow the setup to work.

**Comment by fast97** [comment]
hello really thank you it works very well. thanks again
