### ISSUE TITLE
 Parse error: syntax error, unexpected identifier "ApplicationEnvironment"

### ISSUE THREAD

**Issue by krono86** [AzuraCast/AzuraCast#5019]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#5011 (22/01/2022)

### What happened?

When I try access dashboard I get an error.

### Relevant log output

```shell
Parse error: syntax error, unexpected identifier "ApplicationEnvironment" in /var/azuracast/www/src/Enums/ApplicationEnvironment.php on line 9
```

**Comment by SlvrEagle23** [comment]
@krono86 Your Ansible update may not have gone through correctly, because you should be running PHP 8.1, which is fully compatible with the new Enums we're using.

You may need to run:

```bash
./update.sh --full
```
