### ISSUE TITLE
 500 Could not connect to supervisord.

### ISSUE THREAD

**Issue by Yusadolat** [AzuraCast/AzuraCast#502]
- **Installation Method:**  Docker
- **Host OS (if using Docker):**  Ubuntu 16.04

**Describe the issue in full detail, including screenshots if possible:**
Could you please help look to this, I got this error right after the login screen.Thanks

![screenshot-2018-3-20 error - azuracast](https://user-images.githubusercontent.com/10975011/37642652-e0f88c6e-2c15-11e8-9e85-f9b3bd69a4aa.png)

**Comment by ckeurk** [comment]
for me, the radio still works, except I find this to connect me.
![capture d ecran 2018-03-20 a 10 46 52](https://user-images.githubusercontent.com/379099/37647365-5a27cd14-2c2c-11e8-8f5d-8ae08998ea7f.png)

**Comment by mkody** [comment]
@Yusadolat Could you please correct the two bullet points in your issue, to be sure that (1) you're using docker and (2) know what your host OS is.
Did you try to run the `service` command like suggested on the page?

@ckeurk Please [open a new issue](https://github.com/AzuraCast/AzuraCast/issues/new), we could take a look at the logs later.

**Comment by ckeurk** [comment]
Hi why open a new ticket when we have the same connection problem.

**Comment by mkody** [comment]
From your screenshot, I see that you don't even get access to AzuraCast, while Yusadolat gets an 500 error. Those look like unrelated issues.

**Comment by Yusadolat** [comment]
@mkody I have updated it. Thanks

**Comment by SlvrEagle23** [comment]
@ckeurk This is a different issue from the one in this ticket. Please make a new one.

@Yusadolat The error message's instructions are actually inaccurate in this case, as you can't just restart the supervisord service like that in Docker. 

Try restarting the entire collection of services, like:

```
docker-compose down
docker-compose up -d
```

...and see if you get any errors in that process.

**Comment by SlvrEagle23** [comment]
@Yusadolat Is this issue fixed as well? I noticed you mentioned your new installation was working, just wanted to check

**Comment by Yusadolat** [comment]
Yes, it has been fixed.
