### ISSUE TITLE
Let's Encrypt Intermediary Cert not served by nginx, missing fullchain

### ISSUE THREAD

**Issue by YosefAdPro** [AzuraCast/AzuraCast#5021]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #ec63c9d (2022-01-21 12:03) • Docker • PHP 8.1

### What happened?

I encountered an SSL error for an insecure page.
This happens in both my installation and the clean installation I just tried.

It seems to produce SSL LetsEncrypt, but there seems to be a problem needing to install an Intermediate/chain certificate.

![image](https://user-images.githubusercontent.com/11810187/150652549-6da38cc4-969d-4b71-9ccc-0d0de42b3076.png)

![image](https://user-images.githubusercontent.com/11810187/150652574-e909dcb6-fde0-45e5-beed-ea9b617cde33.png)

**Comment by Vaalyn** [comment]
Hey,

I was looking at the same problem on my test installation and here is what I found:

In the update that removed the nginx_proxy and nginx_proxy_letsencrypt containers in favour of including the LE stuff in the nginx container of AzuraCast it looks like we missed adding a block for the `fullchain.pem` file that the ACME script should generate. Thus the nginx of AzuraCast only sends the ssl cert of the domain but not the intermediary and ISRG root cert.

In the old nginx_proxy this was done here: https://github.com/AzuraCast/docker-azuracast-nginx-proxy/blob/main/app/nginx.tmpl#L312-L316

**Comment by Vaalyn** [comment]
Also noticed that there seems to be no `fullchain.pem` file in the `/etc/nginx/certs` directory of the container. It looks like there is a missing config flag when generating the certificate files via the ACME script. I think there needs to be a `--fullchain-file "${certificate_dir}/fullchain.pem"` in this block: https://github.com/AzuraCast/AzuraCast/blob/main/util/docker/web/runit/acme/run#L121-L125

**Comment by YosefAdPro** [comment]
Right. Have only cert + key.

**Comment by SlvrEagle23** [comment]
Should be fixed as of latest commit; have updated how we generate the SSL cert files to ensure the fullchain is the one we use and to make links run more reliably.

**Comment by YosefAdPro** [comment]
After the last update still has the problem. SSL error
The server does not provide an Intermediate certificate.
