### ISSUE TITLE
Song Uploading Bugs

### ISSUE THREAD

**Issue by Tomato6966** [AzuraCast/AzuraCast#5022]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

latest

### What happened?

I'm uploading a Song-File either via sftp from azuracast, from root or via the drag-and-drop from azuracast.

Sometimes it tells this:
AzuraCast.ERROR: Handling "App\Message\AddNewMediaMessage" failed: Media path "Pop_Music/Maroon 5 - Memories.mp3.filepart" not found. {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":129,"code":0} []

which i think is a problem as while it's getting uploaded its renamed from mp3.filepart to .mp3
but azuracast was too quick or smt.

if i restart the whole ROOT SERVER everyting is fine!

I dont know what's causing the problem. 

### Relevant log output

```shell
AzuraCast.ERROR: Handling "App\Message\AddNewMediaMessage" failed: Media path "Pop_Music/Maroon 5 - Memories.mp3.filepart" not found. {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":129,"code":0} []
```

**Comment by SC2Mitch** [comment]
So let me get this correct, you uploading a file `song_name.mp3filepart` to the server and it's returning the error

OR

Your uploading a file `Song_Name.mp3` to the server and it returns the error?

**Comment by Tomato6966** [comment]
yes
