### ISSUE TITLE
file_get_contents(): SSL operation failed with code 1

### ISSUE THREAD

**Issue by vinzity** [AzuraCast/AzuraCast#5024]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /home/ikoolfmc/98.9ikoolfm.com/android/init2.php on line 14

Warning: file_get_contents(): Failed to enable crypto in /home/ikoolfmc/98.9ikoolfm.com/android/init2.php on line 14

Warning: file_get_contents(https://bnt.devzhosting.com/api/nowplaying/989ikoolfm): failed to open stream: operation failed in /home/ikoolfmc/98.9ikoolfm.com/android/init2.php on line 14

**Comment by SlvrEagle23** [comment]
@vinzity What is the context of this error? What are you trying to do on the site?

Those errors don't correspond to AzuraCast files, so I'm not sure what's triggering that.
