### ISSUE TITLE
How to change Live DJ recording folder?

### ISSUE THREAD

**Issue by k013play** [AzuraCast/AzuraCast#5027]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

Hello, 

i want to change folder location from default folder ( i dont know where is located ) to folder where is playlist files.

I created playlist username and password (Manage sftp accounts), login with ftp client and is empty. 

I want to setup Azuracast to recorded files store in that folder, if it is possible. 

Thank you for help.

**Comment by SlvrEagle23** [comment]
@k013play You can change storage locations via `System Administration` in the top right, then `Storage Locations`. Pick the "Station Recordings" storage location used by the station you want to update, and you can change its path, including to be within your media directory if you'd like recordings to be automatically indexed and able to be cued.

**Comment by k013play** [comment]
Hello @SlvrEagle23 thank you for replay. 

In that settings now is /var/azuracast/stations/mix/recordings 

what is correct location for media directory?

**Comment by SlvrEagle23** [comment]
@k013play If it's the default, it's `/var/azuracast/stations/mix/media`

**Comment by k013play** [comment]
Hello @SlvrEagle23, thank you i will now change and test.

**Comment by k013play** [comment]
@SlvrEagle23 thank you for advice, now system created folder "live" and there store mp3 file.

**Comment by k013play** [comment]
issuse marked as closed.
