### ISSUE TITLE
Delete station when deleting DJ

### ISSUE THREAD

**Issue by NLLucifer** [AzuraCast/AzuraCast#503]
- **Installation Method:** 
Docker
- **Host OS (if using Docker):** 
Ubuntu 16.04 (OVH)

**Describe the issue in full detail, including screenshots if possible:**
Hello,
I found out that when you delete a Streamer/DJ account, the station gets deleted.
Can this be fixed?
I'm currently using v0.8.1-2018.02 Beta (Docker)

**Comment by SlvrEagle23** [comment]
@NLLucifer Yikes, that one's bad! Turns out if you delete the account that was most recently listed as the "active streamer" on the station, it tries to delete the entire station due to an errant "ON DELETE CASCADE" specification on that database table.

The latest update should fix that. My apologies if this did any significant damage to your installation.

**Comment by NLLucifer** [comment]
@SlvrEagle23 I know right!
It is okay though, Thats the danger of using beta software.
When will we be able to update to the new build using Docker?

**Comment by SlvrEagle23** [comment]
@NLLucifer Immediately, feel free to run the updater right now.

**Comment by NLLucifer** [comment]
@SlvrEagle23 On updating i get the following error:

> fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php migrations:migrate --no-interaction --allow-no-migration", "delta": "0:00:00.820807", "end": "2018-03-20 16:45:28.549378", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2018-03-20 16:45:27.728571", "stderr": "\nIn AbstractMySQLDriver.php line 65:\n                                                                               \n  An exception occurred while executing 'ALTER TABLE station_media_art ADD CO  \n  NSTRAINT FK_35E0CAB2EA9FDD75 FOREIGN KEY (media_id) REFERENCES station_medi  \n  a (id)':                                                                     \n                                                                               \n  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update   \n  a child row: a foreign key constraint fails (`azuracast`.`#sql-1_a`, CONSTR  \n  AINT `FK_35E0CAB2EA9FDD75` FOREIGN KEY (`media_id`) REFERENCES `station_med  \n  ia` (`id`))                                                                  \n                                                                               \n\nIn PDOConnection.php line 107:\n                                                                               \n  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update   \n  a child row: a foreign key constraint fails (`azuracast`.`#sql-1_a`, CONSTR  \n  AINT `FK_35E0CAB2EA9FDD75` FOREIGN KEY (`media_id`) REFERENCES `station_med  \n  ia` (`id`))                                                                  \n                                                                               \n\nIn PDOConnection.php line 105:\n                                                                               \n  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update   \n  a child row: a foreign key constraint fails (`azuracast`.`#sql-1_a`, CONSTR  \n  AINT `FK_35E0CAB2EA9FDD75` FOREIGN KEY (`media_id`) REFERENCES `station_med  \n  ia` (`id`))                                                                  \n                                                                               \n\nmigrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--] [<version>]", "stderr_lines": ["", "In AbstractMySQLDriver.php line 65:", "                                                                               ", "  An exception occurred while executing 'ALTER TABLE station_media_art ADD CO  ", "  NSTRAINT FK_35E0CAB2EA9FDD75 FOREIGN KEY (media_id) REFERENCES station_medi  ", "  a (id)':                                                                     ", "                                                                               ", "  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update   ", "  a child row: a foreign key constraint fails (`azuracast`.`#sql-1_a`, CONSTR  ", "  AINT `FK_35E0CAB2EA9FDD75` FOREIGN KEY (`media_id`) REFERENCES `station_med  ", "  ia` (`id`))                                                                  ", "                                                                               ", "", "In PDOConnection.php line 107:", "                                                                               ", "  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update   ", "  a child row: a foreign key constraint fails (`azuracast`.`#sql-1_a`, CONSTR  ", "  AINT `FK_35E0CAB2EA9FDD75` FOREIGN KEY (`media_id`) REFERENCES `station_med  ", "  ia` (`id`))                                                                  ", "                                                                               ", "", "In PDOConnection.php line 105:", "                                                                               ", "  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update   ", "  a child row: a foreign key constraint fails (`azuracast`.`#sql-1_a`, CONSTR  ", "  AINT `FK_35E0CAB2EA9FDD75` FOREIGN KEY (`media_id`) REFERENCES `station_med  ", "  ia` (`id`))                                                                  ", "                                                                               ", "", "migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--] [<version>]"], "stdout": "Loading configuration from the integration code of your framework (setter).\n                                                                    \n                    Doctrine Database Migrations                    \n                                                                    \n\nMigrating up to 20180320163622 from 20180211192448\n\n  ++ migrating 20180320052444\n\n     -> ALTER TABLE station_media_art ADD CONSTRAINT FK_35E0CAB2EA9FDD75 FOREIGN KEY (media_id) REFERENCES station_media (id)\nMigration 20180320052444 failed during Execution. Error An exception occurred while executing 'ALTER TABLE station_media_art ADD CONSTRAINT FK_35E0CAB2EA9FDD75 FOREIGN KEY (media_id) REFERENCES station_media (id)':\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`azuracast`.`#sql-1_a`, CONSTRAINT `FK_35E0CAB2EA9FDD75` FOREIGN KEY (`media_id`) REFERENCES `station_media` (`id`))", "stdout_lines": ["Loading configuration from the integration code of your framework (setter).", "                                                                    ", "                    Doctrine Database Migrations                    ", "                                                                    ", "", "Migrating up to 20180320163622 from 20180211192448", "", "  ++ migrating 20180320052444", "", "     -> ALTER TABLE station_media_art ADD CONSTRAINT FK_35E0CAB2EA9FDD75 FOREIGN KEY (media_id) REFERENCES station_media (id)", "Migration 20180320052444 failed during Execution. Error An exception occurred while executing 'ALTER TABLE station_media_art ADD CONSTRAINT FK_35E0CAB2EA9FDD75 FOREIGN KEY (media_id) REFERENCES station_media (id)':", "", "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`azuracast`.`#sql-1_a`, CONSTRAINT `FK_35E0CAB2EA9FDD75` FOREIGN KEY (`media_id`) REFERENCES `station_media` (`id`))"]}

Is that an error on my side or in the code?

**Comment by NLLucifer** [comment]
oh, and appearently it didn't fix it 😞

**Comment by SlvrEagle23** [comment]
@NLLucifer It's not that it didn't fix it, it's that the update process failed before it had a chance to.

Try running the updater again; I've added some code that should hopefully fix the error you saw there.

**Comment by NLLucifer** [comment]
@SlvrEagle23 Looks like Liquidsoap isn't working right now. Can't login to the stream using the right credentials, ip and port. :-/

**Comment by NLLucifer** [comment]
@SlvrEagle23 Yes, The update did run fine. and this happened after the update

**Comment by NLLucifer** [comment]
@SlvrEagle23 Even after a full re-install the same problem happened..

**Comment by SlvrEagle23** [comment]
@NLLucifer Let's go ahead and close this issue, as it corresponds to the previous issue (and the title no longer applies to this new issue), and make a new one to look into this issue.

Before you create the new issue, run `docker-compose logs -f stations` while attempting to connect as a DJ to see if it's returning any useful information.
