### ISSUE TITLE
Problem with Remote Storage Location

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#5030]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#04b2072

### What happened?

After upgrading to latest rolling release, AZ can't connect to Dropbox as remote location storage and the station goes offline or it shows AzuraCast is Live! message.

When trying to skip a song, I get this message:
Exception at /var/azuracast/www/src/Radio/Backend/Liquidsoap.php 
L207: Telnet failure: Connection refused (111)

**Comment by cdiegosr** [comment]
Same here :(

Docker installation and rolling release channel #58139f1

I did one update, no errors with no sound and same error on Liquidsoap

**Comment by stardevelop** [comment]
It seems that if the Azuracast server loses connection with Dropbox API servers for any reason (such as network latency) , the station goes offline because it can't get the files to play.
I suggest to use keepalive and alert us if there is a connection problem.

**Comment by stardevelop** [comment]
Although the token is valid and correct in Dropbox, I get this error:

ClientException at /var/azuracast/www/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php L113: Client error: `POST https://api.dropboxapi.com/2/files/list_folder` resulted in a `401 Unauthorized` response: {"error_summary": "expired_access_token/.", "error": {".tag": "expired_access_token"}}

**Comment by Vaalyn** [comment]
@stardevelop  Do you have the `Access token expiration` set to `No expiration` here?

![image](https://user-images.githubusercontent.com/13745863/152646692-1fe9fa3d-928b-4a97-b98a-d2bfcadab71d.png)

If dropbox says replies with `expired_access_token` is most likely is expired.
Dropbox in general does work, I have just checked this on my test server on the latest Rolling-Release version.

Regarding what happens when it can't connect to the remote location, it might make sense to pre-fetch the media in the upcoming song queue in order to prevent this from taking down the station. For longer disconnects there is not much that can be done though. Also with PHP a `keepalive` wouldn't make much sense since a PHP process is short lived like "process starts, fetches something, does something with this and then exits". The process can't keep a consistent connection alive. Sure stuff like ReactPHP and Swoole could have in theory a continuous connection, but AzuraCast is not based on those frameworks.

**Comment by stardevelop** [comment]
I created another Dropbox Token, however I am not able to change the token in Storage Locations>Station Media menu because there is no EDIT/DELETE button.
I remember there was a red/blue button to do so there.

**Comment by SC2Mitch** [comment]
![image](https://user-images.githubusercontent.com/29955942/152653928-f6f53abd-e20c-4721-911d-74212929cbd2.png)

I'm able to access them fine, can you double check your on the latest version?

**Comment by Vaalyn** [comment]
You might have to scroll to the right side on that page, I when I tested this I saw the buttons being pushed outside of the table due to the long `dropbox://xyz` path.

**Comment by stardevelop** [comment]
Thanks. I could add a new Storage Location with my new token but still the files are not retrieved from Dropbox and I see nothing in Music Files menu.

**Comment by Vaalyn** [comment]
When you go to `/admin/debug` and manually run the `App\Sync\Task\CheckMediaTask` what does it report for this new Storage Location?

**Comment by stardevelop** [comment]
After the new location is added, I see 0.0 B Space Used while I have TBs of files.

**Comment by stardevelop** [comment]
> When you go to `/admin/debug` and manually run the `App\Sync\Task\CheckMediaTask` what does it report for this new Storage Location?

total_size
"0 (0.0 B)"
total_files
0
already_queued
0
unchanged
0
updated
0
created
0
deleted
0
not_processable
0
task
"CheckMediaTask"

**Comment by stardevelop** [comment]
I could fix the problem by setting correct permissions in Dropbox app console.
However, the previous problem still persists and sometimes the station goes offline due not connect to Dropbox API or lack of Music Files.

**Comment by stardevelop** [comment]
@Vaalyn I have fixed everything and see the Music Files and assigned them to the Playlist. 
The station play the song from Dropbox but after a few minutes it plays AzuraCast is Live! message on "On the Air"
again.
It's strange because I can see my music files on "Playing Next" but it never plays.

**Comment by stardevelop** [comment]
Is there any fix to this bug?

**Comment by Vaalyn** [comment]
I'm not sure.

The initial issue with DropBox was fixed by you setting the correct permissions.

Regarding LS not playing the playlists correctly, please check if the Advanced setting `Manual AutoDJ Mode` is enabled in `Edit Station Profile` -> `AutoDJ` and try disabling it if it's enabled. Due to a bug with Liquidsoap not being able to parse the annotated playlist m3u files this mode is broken atm.

**Comment by stardevelop** [comment]
Yes, Manual AutoDJ Mode is disabled.
Do you think the CPU load may affect this issue? Sometimes, CPU load goes to 100% !

**Comment by stardevelop** [comment]
2022/03/04 11:35:49 [lang:3] API nextsong - Response (200): 
[mp3float @ 0x7f38a9277500] invalid new backstep -1
2022/03/04 11:35:49 [decoder:2] Decoding "/var/azuracast/stations/music/config/fallback.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f38ab2305c0] filesize and duration do not match (growing file?)
[mp3 @ 0x7f38ab2305c0] filesize and duration do not match (growing file?)
[mp3float @ 0x7f38a9277500] Could not update timestamps for skipped samples.
2022/03/04 11:35:50 [error_jingle:3] Prepared "/var/azuracast/stations/music/config/fallback.mp3" (RID 0).
2022/03/04 11:35:51 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:35:51 [lang:3] API nextsong - Response (200): 
2022/03/04 11:35:51 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:35:51 [lang:3] API nextsong - Response (200): 
2022/03/04 11:35:53 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:35:53 [lang:3] API nextsong - Response (200): 
2022/03/04 11:35:53 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:35:53 [lang:3] API nextsong - Response (200): 
2022/03/04 11:35:55 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:35:55 [lang:3] API nextsong - Response (200): 
2022/03/04 11:35:55 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:35:55 [lang:3] API nextsong - Response (200): 
[mp3float @ 0x7f38a9277500] invalid new backstep -1
2022/03/04 11:35:56 [decoder:2] Decoding "/var/azuracast/stations/music/config/fallback.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f38ab2305c0] filesize and duration do not match (growing file?)
[mp3 @ 0x7f38ab2305c0] filesize and duration do not match (growing file?)
[mp3float @ 0x7f38a9277500] Could not update timestamps for skipped samples.
2022/03/04 11:35:56 [error_jingle:3] Prepared "/var/azuracast/stations/music/config/fallback.mp3" (RID 0).
2022/03/04 11:35:57 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:35:57 [lang:3] API nextsong - Response (200): 
2022/03/04 11:35:57 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:35:57 [lang:3] API nextsong - Response (200): 
2022/03/04 11:35:59 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:00 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:00 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:00 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:02 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:02 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:02 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:02 [lang:3] API nextsong - Response (200): 
[mp3float @ 0x7f38a9277500] invalid new backstep -1
2022/03/04 11:36:02 [decoder:2] Decoding "/var/azuracast/stations/music/config/fallback.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f38ab80aa40] filesize and duration do not match (growing file?)
[mp3 @ 0x7f38a949e8c0] filesize and duration do not match (growing file?)
[mp3float @ 0x7f38a9277500] Could not update timestamps for skipped samples.
2022/03/04 11:36:03 [error_jingle:3] Prepared "/var/azuracast/stations/music/config/fallback.mp3" (RID 0).
2022/03/04 11:36:04 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:04 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:04 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:04 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:06 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:06 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:06 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:06 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:08 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:08 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:08 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:08 [lang:3] API nextsong - Response (200): 
[mp3float @ 0x7f38a9277500] invalid new backstep -1
2022/03/04 11:36:09 [decoder:2] Decoding "/var/azuracast/stations/music/config/fallback.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f38a9f54a00] filesize and duration do not match (growing file?)
[mp3 @ 0x7f38a9f54a00] filesize and duration do not match (growing file?)
[mp3float @ 0x7f38a9277500] Could not update timestamps for skipped samples.
2022/03/04 11:36:09 [error_jingle:3] Prepared "/var/azuracast/stations/music/config/fallback.mp3" (RID 0).
2022/03/04 11:36:10 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:10 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:10 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:10 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:12 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:13 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:13 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:13 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:15 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:15 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:15 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:15 [lang:3] API nextsong - Response (200): 
[mp3float @ 0x7f38a9277500] invalid new backstep -1
2022/03/04 11:36:15 [decoder:2] Decoding "/var/azuracast/stations/music/config/fallback.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f38a9a7c100] filesize and duration do not match (growing file?)
[mp3 @ 0x7f38a9a7c100] filesize and duration do not match (growing file?)
[mp3float @ 0x7f38a9277500] Could not update timestamps for skipped samples.
2022/03/04 11:36:15 [error_jingle:3] Prepared "/var/azuracast/stations/music/config/fallback.mp3" (RID 0).
2022/03/04 11:36:17 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:17 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:17 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:17 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:19 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:19 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:19 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:19 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:21 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
[mp3float @ 0x7f38a9277500] invalid new backstep -1
2022/03/04 11:36:21 [decoder:2] Decoding "/var/azuracast/stations/music/config/fallback.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/03/04 11:36:21 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:21 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:22 [lang:3] API nextsong - Response (200): 
[mp3 @ 0x7f38a9a7c100] filesize and duration do not match (growing file?)
[mp3 @ 0x7f38a9a7c100] filesize and duration do not match (growing file?)
[mp3float @ 0x7f38a9277500] Could not update timestamps for skipped samples.
2022/03/04 11:36:22 [error_jingle:3] Prepared "/var/azuracast/stations/music/config/fallback.mp3" (RID 0).
2022/03/04 11:36:24 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:24 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:24 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:24 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:26 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:27 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:27 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:27 [lang:3] API nextsong - Response (200): 
[mp3float @ 0x7f38a9277500] invalid new backstep -1
2022/03/04 11:36:28 [decoder:2] Decoding "/var/azuracast/stations/music/config/fallback.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f38a9a7c100] filesize and duration do not match (growing file?)
[mp3 @ 0x7f38a9a7c100] filesize and duration do not match (growing file?)
[mp3float @ 0x7f38a9277500] Could not update timestamps for skipped samples.
2022/03/04 11:36:28 [error_jingle:3] Prepared "/var/azuracast/stations/music/config/fallback.mp3" (RID 0).
2022/03/04 11:36:29 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:29 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:29 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:30 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:32 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:32 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:32 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:32 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:34 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:34 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:34 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:34 [lang:3] API nextsong - Response (200): 
[mp3float @ 0x7f38a9277500] invalid new backstep -1
2022/03/04 11:36:34 [decoder:2] Decoding "/var/azuracast/stations/music/config/fallback.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f38a9a7c100] filesize and duration do not match (growing file?)
[mp3 @ 0x7f38a9a7c100] filesize and duration do not match (growing file?)
[mp3float @ 0x7f38a9277500] Could not update timestamps for skipped samples.
2022/03/04 11:36:35 [error_jingle:3] Prepared "/var/azuracast/stations/music/config/fallback.mp3" (RID 0).
2022/03/04 11:36:36 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:36 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:36 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:36 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:38 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:38 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:38 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:38 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:40 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:40 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:40 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:40 [lang:3] API nextsong - Response (200): 
[mp3float @ 0x7f38a9277500] invalid new backstep -1
2022/03/04 11:36:41 [decoder:2] Decoding "/var/azuracast/stations/music/config/fallback.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f38a9a7c100] filesize and duration do not match (growing file?)
[mp3 @ 0x7f38a9a7c100] filesize and duration do not match (growing file?)
[mp3float @ 0x7f38a9277500] Could not update timestamps for skipped samples.
2022/03/04 11:36:41 [error_jingle:3] Prepared "/var/azuracast/stations/music/config/fallback.mp3" (RID 0).
2022/03/04 11:36:43 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:43 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:43 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:43 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:45 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:45 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:45 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:45 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:47 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:47 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:47 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:47 [lang:3] API nextsong - Response (200): 
[mp3float @ 0x7f38a9277500] invalid new backstep -1
2022/03/04 11:36:47 [decoder:2] Decoding "/var/azuracast/stations/music/config/fallback.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f38a9a7c100] filesize and duration do not match (growing file?)
[mp3 @ 0x7f38a9a7c100] filesize and duration do not match (growing file?)
[mp3float @ 0x7f38a9277500] Could not update timestamps for skipped samples.
2022/03/04 11:36:48 [error_jingle:3] Prepared "/var/azuracast/stations/music/config/fallback.mp3" (RID 0).
2022/03/04 11:36:49 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:49 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:49 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:49 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:51 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:51 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:51 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:51 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:53 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:53 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:53 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:54 [lang:3] API nextsong - Response (200): 
[mp3float @ 0x7f38a9277500] invalid new backstep -1
2022/03/04 11:36:54 [decoder:2] Decoding "/var/azuracast/stations/music/config/fallback.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f38a9a7c100] filesize and duration do not match (growing file?)
[mp3 @ 0x7f38a9a7c100] filesize and duration do not match (growing file?)
[mp3float @ 0x7f38a9277500] Could not update timestamps for skipped samples.
2022/03/04 11:36:54 [error_jingle:3] Prepared "/var/azuracast/stations/music/config/fallback.mp3" (RID 0).
2022/03/04 11:36:56 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:56 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:56 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:56 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:58 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:58 [lang:3] API nextsong - Response (200): 
2022/03/04 11:36:58 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:36:58 [lang:3] API nextsong - Response (200): 
2022/03/04 11:37:00 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
[mp3float @ 0x7f38a9277500] invalid new backstep -1
2022/03/04 11:37:00 [lang:3] API nextsong - Response (200): 
2022/03/04 11:37:00 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:37:00 [decoder:2] Decoding "/var/azuracast/stations/music/config/fallback.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/03/04 11:37:00 [lang:3] API nextsong - Response (200): 
[mp3 @ 0x7f38a8d5a9c0] filesize and duration do not match (growing file?)
[mp3 @ 0x7f38a8d5a9c0] filesize and duration do not match (growing file?)
[mp3float @ 0x7f38a9277500] Could not update timestamps for skipped samples.
2022/03/04 11:37:01 [error_jingle:3] Prepared "/var/azuracast/stations/music/config/fallback.mp3" (RID 0).
2022/03/04 11:37:02 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:37:02 [lang:3] API nextsong - Response (200): 
2022/03/04 11:37:02 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:37:02 [lang:3] API nextsong - Response (200): 
2022/03/04 11:37:04 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:37:05 [lang:3] API nextsong - Response (200): 
2022/03/04 11:37:05 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:37:05 [lang:3] API nextsong - Response (200): 
[mp3float @ 0x7f38a9277500] invalid new backstep -1
2022/03/04 11:37:06 [decoder:2] Decoding "/var/azuracast/stations/music/config/fallback.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f38a8d5a9c0] filesize and duration do not match (growing file?)
[mp3 @ 0x7f38a8d5a9c0] filesize and duration do not match (growing file?)
[mp3float @ 0x7f38a9277500] Could not update timestamps for skipped samples.
2022/03/04 11:37:07 [error_jingle:3] Prepared "/var/azuracast/stations/music/config/fallback.mp3" (RID 0).
2022/03/04 11:37:07 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:37:07 [lang:3] API nextsong - Response (200): 
2022/03/04 11:37:07 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:37:07 [lang:3] API nextsong - Response (200): 
2022/03/04 11:37:09 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:37:09 [lang:3] API nextsong - Response (200): 
2022/03/04 11:37:09 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:37:09 [lang:3] API nextsong - Response (200): 
2022/03/04 11:37:12 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:37:12 [lang:3] API nextsong - Response (200): 
2022/03/04 11:37:12 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:37:12 [lang:3] API nextsong - Response (200): 
[mp3float @ 0x7f38a9277500] invalid new backstep -1
2022/03/04 11:37:13 [decoder:2] Decoding "/var/azuracast/stations/music/config/fallback.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f38a8d5a9c0] filesize and duration do not match (growing file?)
[mp3 @ 0x7f38a8d5a9c0] filesize and duration do not match (growing file?)
[mp3float @ 0x7f38a9277500] Could not update timestamps for skipped samples.
2022/03/04 11:37:13 [error_jingle:3] Prepared "/var/azuracast/stations/music/config/fallback.mp3" (RID 0).
2022/03/04 11:37:14 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:37:14 [lang:3] API nextsong - Response (200): 
2022/03/04 11:37:14 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:37:14 [lang:3] API nextsong - Response (200): 
2022/03/04 11:37:16 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:37:16 [lang:3] API nextsong - Response (200): 
2022/03/04 11:37:16 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:37:16 [main:3] Shutdown started!
2022/03/04 11:37:16 [main:3] Waiting for main threads to terminate...
2022/03/04 11:37:16 [local_1:3] Closing connection...
2022/03/04 11:37:17 [lang:3] API nextsong - Response (200): 
2022/03/04 11:37:17 [clock.main:3] Streaming loop stopped.
2022/03/04 11:37:17 [main:3] Main threads terminated.
2022/03/04 11:37:17 [threads:3] Shutting down scheduler...
2022/03/04 11:37:17 [threads:3] Scheduler shut down.
2022/03/04 11:37:17 [main:3] Cleaning downloaded files...
2022/03/04 11:37:17 [main:3] Freeing memory...
2022/03/04 11:37:29 >>> LOG START
2022/03/04 11:37:23 [main:3] Liquidsoap 2.0.3-1
2022/03/04 11:37:23 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] posix-time2=2.0.0 pcre=7.5.0 sedlex=2.5 menhirLib=20211128 curl=0.9.2 memtrace=v0.2.1.2 mem_usage=0.0.1 dtools=0.4.4 duppy=0.9.2 cry=0.6.6 mm=0.7.5 xmlplaylist=0.1.5 lastfm=0.3.3 ogg=0.7.0 ogg.decoder=0.7.0 vorbis=0.8.0 vorbis.decoder=0.8.0 opus=0.2.1 opus.decoder=0.2.1 speex=0.4.0 speex.decoder=0.4.0 mad=0.5.0 flac=0.3.0 flac.ogg=0.3.0 flac.decoder=0.3.0 dynlink=[distributed with Ocaml] lame=0.3.5 shine=0.2.2 frei0r=0.1.2 fdkaac=0.3.2 theora=0.4.0 theora.decoder=0.4.0 ffmpeg=1.1.1 bjack=0.1.6 alsa=0.3.0 ao=0.2.3 samplerate=0.1.6 taglib=0.3.9 ssl=0.5.9 magic=0.7.3 camomile=1.0.2 inotify=2.3 yojson=1.7.0 faad=0.5.0 soundtouch=0.1.9 portaudio=0.2.3 pulseaudio=0.1.4 ladspa=0.2.0 dssi=0.1.3 tsdl=v0.9.8 tsdl-ttf=0.3.2 tsdl-image=0.3.2 camlimages=4.2.6 cohttp-lwt-unix=5.0.0 prometheus-app=1.1 srt.constants=0.2.2 srt.types=0.2.2 srt.stubs=0.2.2 srt.stubs.locked=0.2.2 srt=0.2.2 lo=0.2.0 gd=1.0a5
2022/03/04 11:37:25 [clock:3] Using native (high-precision) implementation for latency control
2022/03/04 11:37:29 [playlist.basic:3] Wrong mime type application/csv for playlist!
2022/03/04 11:37:29 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz main.
2022/03/04 11:37:29 [frame:3] Video frame size set to: 1280x720
2022/03/04 11:37:29 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2022/03/04 11:37:29 [frame:3] Targeting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2022/03/04 11:37:29 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2022/03/04 11:37:29 [sandbox:3] Running inside a docker container, disabling sandboxing.
2022/03/04 11:37:29 [video.converter:3] Using preferred video converter: ffmpeg.
2022/03/04 11:37:29 [audio.converter:3] Using samplerate converter: ffmpeg.
2022/03/04 11:37:29 [error_jingle:3] /var/azuracast/stations/music/config/fallback.mp3 is static, resolving once for all...
[mp3 @ 0x7f6c2c005c80] filesize and duration do not match (growing file?)
[mp3 @ 0x7f6c2c0271c0] filesize and duration do not match (growing file?)
[mp3 @ 0x7f6c2c005d00] filesize and duration do not match (growing file?)
[mp3 @ 0x7f6c2c005d00] filesize and duration do not match (growing file?)
2022/03/04 11:37:29 [error_jingle:3] Prepared "/var/azuracast/stations/music/config/fallback.mp3" (RID 1).
2022/03/04 11:37:29 [local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2022/03/04 11:37:29 [local_1:3] Connection setup was successful.
2022/03/04 11:37:29 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/3/nextsong' with body: 
2022/03/04 11:37:29 [clock.main:3] Streaming loop starts in auto-sync mode
2022/03/04 11:37:29 [clock.main:3] Delegating synchronisation to CPU clock
[mp3float @ 0x7f6c1c008500] Could not update timestamps for skipped samples.
2022/03/04 11:37:29 [safe_fallback:3] Switch to error_jingle.
