### ISSUE TITLE
Song stream playback and timing/bar

### ISSUE THREAD

**Issue by Zoe8338** [AzuraCast/AzuraCast#5031]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #04b2072 

### What happened?

I have noticed that even if the song stops being streamed for any reason the timer and bar will continue, I am not sure if this is on purpose or just a bug so I am reporting it here.

**Comment by SC2Mitch** [comment]
Thanks for the report, a fairly minor issue but one nonetheless.
