### ISSUE TITLE
File Processing error

### ISSUE THREAD

**Issue by cloudbolwell** [AzuraCast/AzuraCast#5034]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #120c517 (2022-01-26 7:01) 

### What happened?

I believe I am facing the same issue as #4985  however I am running docker on synology and after updating none of the files process after trying to run the synchronization task App\Sync\Task\CheckMediaTask I hit a 502 Bad Gateway I have uninstalled and reinstalled to no effect I have tried both stable and rolling releases same issue if I change the media directory back to default and delete the docker-compose.override.yml and change the UID, PGID in .env back to default restarted everything and upload via SFTP or browser upload they process again

**Comment by SC2Mitch** [comment]
Can you post the files here so I can test them on my local machine? When you hit a bad gateaway, can you check the logs (docker) to see if any `Azuracast.ERROR` shows and paste it here. If its a huge log, use pastebin :)

**Comment by cloudbolwell** [comment]
Here you go https://pastebin.com/EBS4ZRMq

**Comment by cloudbolwell** [comment]
there is a lot of Azuracast.ERROR

**Comment by cloudbolwell** [comment]
@SC2Mitch I got to the bottom of the recursive error because it was to do with the good old recycling bin in the media file location azuracast can see the recycling bin under music files but had no access to it which caused the error I change the permissions of the recycling bin and the error disappeared and the files started processing problem solved I enabled the recycling bin because like a plonker iv accidentally deleted files but never encountered any issues till now
