### ISSUE TITLE
No Audio after update

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#5035]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#f8e2e7c

### What happened?

My stations have no audio after latest update.

**Comment by SC2Mitch** [comment]
Need some logs please, `docker-compose logs -f`

**Comment by stardevelop** [comment]
web_1       |
web_1       | In AbstractMySQLDriver.php line 51:
web_1       |
web_1       |   An exception occurred while executing 'UPDATE station_queue SET is_played =
web_1       |    1, sent_to_autodj = 1 WHERE station_id = ? AND is_played = 0 AND (id = ? O
web_1       |   R timestamp_cued < ?)' with params [1, 271382, 1643270210]:
web_1       |
web_1       |   SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to
web_1       |   get lock; try restarting transaction
web_1       |
web_1       |
web_1       | In Exception.php line 18:
web_1       |
web_1       |   SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to
web_1       |   get lock; try restarting transaction
web_1       |
web_1       |
web_1       | In PDOStatement.php line 117:
web_1       |
web_1       |   SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to
web_1       |   get lock; try restarting transaction
web_1       |
web_1       |
web_1       | azuracast:sync:nowplaying:station <station>
web_1       | [2022-01-27T07:58:09.655067+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":0,"workerName":"app_worker_0"} []
web_1       | [2022-01-27T07:58:41.473792+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":1,"name":"Rodio"}}

**Comment by stardevelop** [comment]
web_1 |
web_1 | In AbstractMySQLDriver.php line 51:
web_1 |
web_1 | An exception occurred while executing 'UPDATE station_queue SET is_played =
web_1 | 1, sent_to_autodj = 1 WHERE station_id = ? AND is_played = 0 AND (id = ? O
web_1 | R timestamp_cued < ?)' with params [1, 271382, 1643270210]:
web_1 |
web_1 | SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to
web_1 | get lock; try restarting transaction
web_1 |
web_1 |
web_1 | In Exception.php line 18:
web_1 |
web_1 | SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to
web_1 | get lock; try restarting transaction
web_1 |
web_1 |
web_1 | In PDOStatement.php line 117:
web_1 |
web_1 | SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to
web_1 | get lock; try restarting transaction
web_1 |
web_1 |
web_1 | azuracast:sync:nowplaying:station
web_1 | [2022-01-27T07:58:09.655067+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":0,"workerName":"app_worker_0"} []
web_1 | [2022-01-27T07:58:41.473792+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":1,"name":"Radio"}}

**Comment by stardevelop** [comment]
web_1 |
web_1 | In AbstractMySQLDriver.php line 51:
web_1 |
web_1 | An exception occurred while executing 'UPDATE station_queue SET is_played =
web_1 | 1, sent_to_autodj = 1 WHERE station_id = ? AND is_played = 0 AND (id = ? O
web_1 | R timestamp_cued < ?)' with params [1, 271382, 1643270210]:
web_1 |
web_1 | SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to
web_1 | get lock; try restarting transaction
web_1 |
web_1 |
web_1 | In Exception.php line 18:
web_1 |
web_1 | SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to
web_1 | get lock; try restarting transaction
web_1 |
web_1 |
web_1 | In PDOStatement.php line 117:
web_1 |
web_1 | SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to
web_1 | get lock; try restarting transaction

**Comment by stardevelop** [comment]
I found the issue!

It's a bug with Banned Countries option.
When I select a few countries to be banned on a station, AzuraCast asks for authentication for ALL countries (from any IP) and it doesn't let the station plays. When I clear the banned list, it works fine.

Please check and fix the bug.

**Comment by SlvrEagle23** [comment]
@stardevelop You're correct; if you have countries banned, it was using the wrong internal parameter when checking whether Icecast was correctly authenticated; this should be fixed in the latest Rolling Release version deploying above (once the commit above turns into a green checkmark).

**Comment by stardevelop** [comment]
Thanks. Issue fixed.
