### ISSUE TITLE
I experienced a spike in RAM usage after upgrading to the latest version

### ISSUE THREAD

**Issue by istahilagi** [AzuraCast/AzuraCast#5038]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.15.0 Stable

### What happened?

is it true that the latest version of azuracast 15.0 stable uses a lot of RAM capacity?
I experienced a spike in RAM usage after upgrading to the latest version
or maybe there is something wrong with the update i did

**Comment by krono86** [comment]
Same here!

**Comment by SC2Mitch** [comment]
duplicate  - https://github.com/AzuraCast/AzuraCast/issues/5010
