### ISSUE TITLE
Web hooks SQL error

### ISSUE THREAD

**Issue by NLLucifer** [AzuraCast/AzuraCast#504]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Ubuntu 16.04 

**Describe the issue in full detail, including screenshots if possible:**
While opening the webhooks page i get the following error:
![image](https://user-images.githubusercontent.com/37590500/37670313-4255b376-2c69-11e8-8e42-3b9495c2805d.png)
`An exception occurred while executing 'SELECT t0.id AS id_1, t0.station_id AS station_id_2, t0.name AS name_3, t0.type AS type_4, t0.is_enabled AS is_enabled_5, t0.triggers AS triggers_6, t0.config AS config_7, t0.station_id AS station_id_8 FROM station_webhooks t0 WHERE t0.station_id = ?' with params [3]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.type' in 'field list'
AbstractMySQLDriver.php : 76`

**Comment by SlvrEagle23** [comment]
@NLLucifer This was due to your previous update failing and should now be resolved.
