### ISSUE TITLE
Error log for playlist upload

### ISSUE THREAD

**Issue by ncfernan** [AzuraCast/AzuraCast#5044]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #0544833 (2022-01-29 13:41) • Docker • PHP 8.1

### What happened?

I'm uploading a playlist with 9095 lines but at the end it shows only 8900 entries. Maybe some filename is ill formed.

How can I see what's going on?  Is there a log that reports this kind of problem?

![image](https://user-images.githubusercontent.com/10008844/151676489-d4b33084-f358-4d26-859c-63e21dfc782f.png)

![image](https://user-images.githubusercontent.com/10008844/151676509-7367e9d5-cdd0-425d-b105-0de340b281d3.png)

**Comment by SlvrEagle23** [comment]
@ncfernan There's not currently a way to view a log that specifically indicates which files successfully imported and which ones didn't, but you could always export the newly imported playlist as a M3U file and use one of a wide number of tools to do a "diff" between that and the original file.

**Comment by ncfernan** [comment]
@SlvrEagle23 I followed your instructions, this is the output:

![image](https://user-images.githubusercontent.com/10008844/151681321-30b201b6-7455-4ef8-9187-d0cdd5a97407.png)

I thought that maybe the music directories were only partially reprocessed, so the missing files in DB should be the missing songs, but to my surprise, even after forcing a reprocess, this is what is appearing now:

![image](https://user-images.githubusercontent.com/10008844/151681374-4ccdd102-ef14-460e-80c1-8338f7b94264.png)

Maybe deleting the db files and letting the MariaDB rebuild the schema could help. Any thoughts?

**Comment by SlvrEagle23** [comment]
@ncfernan The latest Rolling Release version includes a much more detailed results page when the import is completed. It should give you specifics of which tracks are successfully detected/matched, and which ones aren't.

**Comment by ncfernan** [comment]
@SlvrEagle23 It's working now. I tested with the same set of files and the same playlist:

![image](https://user-images.githubusercontent.com/10008844/152681149-8fef80ce-4ea4-4d94-85fb-789d46363738.png)

Thank you
