### ISSUE TITLE
Restore backup azuracast that is different from the backup version

### ISSUE THREAD

**Issue by istahilagi** [AzuraCast/AzuraCast#5045]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

i have a snapshot on linux vps. if I do a rollback, it will return to the condition a few weeks ago, namely when azuracast was still in version v0.14.1

if i back up azuracast while in version v0.15.0,
after that I rollback my vps so that azuracast returns to version v0.14.1,
after that I restored my backup which was v0.15.0 (after I moved it to another storage) on azuracast which was still version v0.14.1
is this not a problem?

**Comment by SC2Mitch** [comment]
Hi,

You should be fine if you have a backup from 14.1 and update to 15.0 to run the restore. You will do some migrations but the updater / restore script should handle it.

**Comment by istahilagi** [comment]
I mean my backup is version 15.0,
and I restore on azuracast which is still version 14.1

is this possible?

**Comment by SC2Mitch** [comment]
No, database changes from 14.1 and 15.0 might leave incompatabilities and database related errors.
