### ISSUE TITLE
Broadcasting stops with error in Mozilla Firefox 

### ISSUE THREAD

**Issue by Ferz0id** [AzuraCast/AzuraCast#5053]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.15.0 Stable

### What happened?

Broadcast from Public Pages or Embeded Widget stops every time with this error in latest Mozilla Firefox (94.0.1) 

![1](https://user-images.githubusercontent.com/44975254/151936399-b5b4cdee-1e49-4a96-a336-13cabb6c3044.JPG)

**Comment by SC2Mitch** [comment]
Seems to be working fine for me on the latest Firefox 94.0.1. 
![image](https://user-images.githubusercontent.com/29955942/152623640-ebb5241b-cdc2-4131-a230-34e0dc1cffb2.png)

Tested on the main public page and via the embeded widget.

**Comment by PinguiFabgeeklab** [comment]
Same problem on a webradio powered by AzuraCast.

![image](https://user-images.githubusercontent.com/78692586/152698397-a3a03fa2-8b97-4935-ae76-abb2c0d43644.png)

**Comment by SC2Mitch** [comment]
Can you both test this out with the Web Proxy Radio enabled in your admin settings, along with the use websockets for now playing?

**Comment by PinguiFabgeeklab** [comment]
> Can you both test this out with the Web Proxy Radio enabled in your admin settings, along with the use websockets for now playing?

I don't know because it's not mine.

**Comment by SC2Mitch** [comment]
> > Can you both test this out with the Web Proxy Radio enabled in your admin settings, along with the use websockets for now playing?
> 
> I don't know because it's not mine.

Can you inform your system admin / server owner to change to the above settings? It should help this out.

**Comment by Ferz0id** [comment]
After v0.15.1 update I can't get anything played in a dasboard:
![Снимок](https://user-images.githubusercontent.com/44975254/155062367-a51ca485-3e66-473e-8e6e-ea62e5d6bfdc.JPG)
Every time when press a play button but only in Mozilla Firefox.

Embeded Widget ran for several hours without any problems.
