### ISSUE TITLE
Update docker.sh to support safe update from any directory

### ISSUE THREAD

**Issue by bilalbox** [AzuraCast/AzuraCast#5058]
Sorry to revive this, but I experienced the same thing upon performing a simple update. However, I think the reason was because I accidentally performed the update from ~ using:
```
root@iq-azuracast:~#
root@iq-azuracast:~# /var/azuracast/docker.sh update-self
New Docker utility script downloaded.
root@iq-azuracast:~# /var/azuracast/docker.sh update
```

INSTEAD OF

```
root@iq-azuracast:~# cd /var/azuracast
root@iq-azuracast:/var/azuracast#./docker.sh update-self
New Docker utility script downloaded.
root@iq-azuracast:/var/azuracast#./docker.sh update
```

After new install and being completely non-functional, I just reran the `docker` commands from the correct directory and the update went smoothly and DB access appears to be resolved. 🎊 

### Installation Method
Docker Installation

### AzuraCast Release Channel
Stable Channel

### Current AzuraCast Version
`Rolling Release #8954be6 (2022-01-30 20:07)`!! <--- running update from ~ appears to have switched my release channel.

### What happened?
I saw the same logs as @uoziod when running `docker logs MARIADB_CID`

_Originally posted by @bilalbox in https://github.com/AzuraCast/AzuraCast/issues/4571#issuecomment-1026090522_

**Comment by SC2Mitch** [comment]
Hi

What exactly is the issue here? I'm struggling to see what the problem is.

**Comment by SlvrEagle23** [comment]
@SC2Mitch The bash script doesn't ensure that you're running it in the proper context, so if you run:

```
cd /var/azuracast
./docker.sh blah
```

...that works correctly, but if you run

```
/var/azuracast/docker.sh blah
```

then the context is the directory you're _currently in_, not the directory the script is in, and that breaks stuff. It's a pretty minor fix I believe.
