### ISSUE TITLE
Error 404 on /api_keys page

### ISSUE THREAD

**Issue by RS232DZ** [AzuraCast/AzuraCast#5066]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.15.0

### What happened?

I have a 0.14.1 version of Azuracast running and connected to azurarelay instance. 
But when I tried a fresh install of the 0.15.0 version the azurarelay can't find the api_keys in the main server
The url http://myserver/api_keys give 404 error and I can't find "my keys" in the menu
Any help please?
0.14.1 menu
![0.14.1 menu](https://user-images.githubusercontent.com/80387880/152365400-b3ba7009-f6e4-4449-b37f-3929a1d43e4c.png)
0.15.0 menu
![0.15.0 menu](https://user-images.githubusercontent.com/80387880/152365446-1ce9ec8a-e679-4564-a15c-782274dd5db1.png)

**Comment by SC2Mitch** [comment]
Hi

I can confirm this indeed is an error 404, I'm unsure the exact reason it was removed. 

We do have a way of accessing all the API keys via `domain/admin/api_keys` for the short term however, also you can click on your profile to create and manage API keys.

**Comment by RS232DZ** [comment]
Hi, Yes I can access keys in domain/admin/api_keys but azurarelay try to connect to domain/api_keys and it gets 404

**Comment by SlvrEagle23** [comment]
@RS232DZ API keys are managed via the main profile page. We merged the profile and API keys pages in the latest version; you can do all of the same functions on the new profile page.

**Comment by RS232DZ** [comment]
@SlvrEagle23  Can you confirm that current Azurarelay version still works with Azuracast V 0.15.0 after this change?
(Tried several times without success) 
Thanks

**Comment by SlvrEagle23** [comment]
@RS232DZ can you be clear on the error you're experiencing? The API hasn't changed in a significant way that should prevent AzuraRelay from working...if you're running into errors and there are logs explaining the errors, please post them so we can diagnose that issue further.

**Comment by RS232DZ** [comment]
Ok there is the steps I folow:
- I installed a fresh install of azuracast 0.15.0 http://server01.mydomain.ltd
- Created a station
- Generated api key (with the admin user profile)
 
Installed a fresh azurarelay in a new server
followed the steps with giving the full url and the api key
(the script tell me that I can generate api in http://server01.mydomain.ltd/api_keys)
Then I have this error message
![Capture d’écran 2022-02-03 à 11 07 24 PM](https://user-images.githubusercontent.com/80387880/152438189-ceb77c65-9548-433a-be55-033c5022a65a.png)

I have an other instance with v 0.14.1 that works fine
