### ISSUE TITLE
No sound but the songs keeps updating and playing

### ISSUE THREAD

**Issue by agonzalo36r** [AzuraCast/AzuraCast#5067]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### What happened?

Everything was running good until a couple of days ago, the songs keep on changing and showing the remaining time, even I can connect to do live shows, but there-s no sound. I-ve tried on desktop and Android, but in the desktop console I get the following message:
The FetchEvent for "https://ac.buquetrece.com:8000/radio.mp3" resulted in a network error response: the promise was rejected.
Promise.then (async) 
GET https://ac.buquetrece.com:8000/radio.mp3 net::ERR_FAILED :8000/radio.mp3:1          
Uncaught (in promise) TypeError: Failed to fetch sw.js:35          

buquetrece_radio:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.

![2022-02-03 22_19_20-Buquetrece Radio](https://user-images.githubusercontent.com/51273601/152466591-2f9473e8-c5dd-474d-83d6-f58a96e768ca.png)

I've tried on the embed player and on the public page, with equal results (this is my public radio page https://ac.buquetrece.com/public/buquetrece_radio )

I hope you can help me, thanks a lot for reading this!

**Comment by RS232DZ** [comment]
Hi,
Your LetsEncrypt ssl cert has expired on  02/02/2022

**Comment by SC2Mitch** [comment]
Not a bug; user SSL error.

**Comment by agonzalo36r** [comment]
Wow thanks a lot! I wasn't aware of that, now it's working, thank you sooo much!
