### ISSUE TITLE
Can't update artwork for apodcast and episode after creating them

### ISSUE THREAD

**Issue by Enne2** [AzuraCast/AzuraCast#5070]
I'm using the latest rolling release (#a2eb5d0) with Docker. Adding an Artwork to a podcast or a episode works only when they are created, when I try to upload a new artwork there is an upload error and when saved the artwork is the same as before.

**Comment by SC2Mitch** [comment]
I'll check this now, possibly been fixed?

**Comment by SC2Mitch** [comment]
Fixed in the latest release, unable to replicate on the latest branch.
