### ISSUE TITLE
Install azuracast with a previous stable version

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#5071]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

I would like to ask if it is possible to install an older version of azuracast. Currently version 0.14.1 of Azuracast is working fine for us and for a new installation we prefer this to the current one. Is there a way to do it?

**Comment by SC2Mitch** [comment]
We don't have any ways to install specific versions, we won't be supporting it for various security and performance reasons.
