### ISSUE TITLE
Error install or update

### ISSUE THREAD

**Issue by KoneSV** [AzuraCast/AzuraCast#5072]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

TASK [php : Remove Old PHP Libraries] *********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package(s) matching 'php5-*' available"}

### Relevant log output

```shell
TASK [php : Remove Old PHP Libraries] *********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package(s) matching 'php5-*' available"}
```

**Comment by SlvrEagle23** [comment]
@KoneSV This was fixed in subsequent rolling-release updates and will be published to the stable branch when the next stable release is tagged; in the meantime, you can update to the latest rolling-release branch to continue to receive updates.

**Comment by KoneSV** [comment]
> This was fixed in subsequent rolling-release updates and will be published to the stable branch when the next stable release is tagged; in the meantime, you can update to the latest rolling-release branch to continue to receive updates.

The update ruined me and I had to reinstall it, now it won't let me install ansible version

**Comment by SlvrEagle23** [comment]
@KoneSV I don't know what specific errors you encountered, or what you mean by it won't "let you" install the Ansible version.

**Comment by Titor-2036** [comment]
The update also broke my ansible installation, upon attempting to install on a new clean server i get no file found error:  ./install.sh file not found
