### ISSUE TITLE
disk space is growing every day

### ISSUE THREAD

**Issue by inetactief** [AzuraCast/AzuraCast#5077]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #7870205 (2022-02-04 2:30) • Docker • PHP 8.1

### What happened?

I've had it before in older version but my disk space is growing without more mp3 files coming on it. 
It grows by 35GB in 4 weeks until the disk is full. 
After an upgrade it goes back to normal. Is it possible to view or delete something without rebooting?

And is it possible to roll it back to a stable release?

**Comment by SlvrEagle23** [comment]
@inetactief We've had two reports of this, and we absolutely need to figure out what's causing these files to be created in the system. Please don't just give up and restore back to a different version or something like that, because that's what most of our users do, and that greatly inhibits our ability to diagnose these things.

**Comment by SC2Mitch** [comment]
Is it possible you can come join our discord so we can run you through some debug steps? Your assistance will be greatly appriciated. Then we can possibly take a look at your machine specifically to see whats going on. 


https://discord.gg/azuracast

**Comment by adoboligh1** [comment]
i face this same issue when i use a remote storage.

**Comment by SC2Mitch** [comment]
For users having this issue please contact one of us on our discord server as we want to find the root cause for this.

**Comment by inetactief** [comment]
That's right, since 3 weeks the disk space has stopped growing. So after an update this is solved
