### ISSUE TITLE
Problem after last update

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#508]
- **Installation Method:**  Traditional 
- **Host OS (if using Docker):**  Ubuntu 16.04

After a new installation, I come across this page:
![capture d ecran 2018-03-21 a 10 39 47](https://user-images.githubusercontent.com/379099/37702933-61f2512c-2cf4-11e8-9e11-f9ef33472a5e.png)

I tried the command `service nginx restart`, but it doesn't work.

**Comment by ckeurk** [comment]
if I do a complete installation I find this at the end 

`TASK [influxdb : Set Up InfluxDB] **********************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php azuracast:setup:influx", "delta": "0:00:00.053147", "end": "2018-03-23 06:58:36.737344", "msg": "non-zero return code", "rc": 255, "start": "2018-03-23 06:58:36.684197", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
localhost                  : ok=55   changed=12   unreachable=0    failed=1  `

**Comment by SlvrEagle23** [comment]
@ckeurk If you manually execute:

```
php /var/azuracast/www/util/cli.php azuracast:setup:influx
```

in your shell, what does it return?

**Comment by ckeurk** [comment]
Okay, I re-installed and everything's working fine.
