### ISSUE TITLE
Statistics broken since 0.15.0 update

### ISSUE THREAD

**Issue by inigosastre** [AzuraCast/AzuraCast#5081]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.15.0

### What happened?

Hi!

Since last update, using Docker with stable channel, from 0.14.2 to 0.15.0, stats graphic has broken as seen at the screenshot.

![image](https://user-images.githubusercontent.com/63013622/152958652-a34eafb4-9c58-46eb-ba4a-7fd07d69ec89.png)

I can't get listeners data on a station where I have added some remote relays.

![image](https://user-images.githubusercontent.com/63013622/152958963-6a59f045-256a-4dc5-ab93-7c25c98ceae6.png)

I can't find the error in logs, because they're relays.

Thanks!

**Comment by SC2Mitch** [comment]
Thanks for the report, will review and flag as necessary

**Comment by SC2Mitch** [comment]
Been unable to verify, but it does indeed appear there's a issue with relays, flagged as such. Thanks for the report.

**Comment by inigosastre** [comment]
This bug has been solved since 0.15.1 update. Thanks!

**Comment by inigosastre** [comment]
I've updated from the 0.15.1 version to 0.17.1, stable channel, and I have had the same problem. No stats since June 30th, last update date.

<img width="1174" alt="Captura de Pantalla 2022-07-05 a las 13 18 45" src="https://user-images.githubusercontent.com/63013622/177316527-10941e3b-a801-4560-a650-0063f8454bc2.png">
