### ISSUE TITLE
azuracast installation error

### ISSUE THREAD

**Issue by dolphin-cat** [AzuraCast/AzuraCast#5083]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

mkdir -p /var/azuracast
cd /var/azuracast
curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/main/docker.sh > docker.sh
chmod a+x docker.sh
./docker.sh install

### Relevant log output

```shell
Checking installation requirements for AzuraCast...
[PASS] Operating System: Linux
[PASS] Architecture: x86_64
[PASS] Command Present: curl
[PASS] Command Present: awk
[PASS] User Permissions
[PASS] Installation Directory
[PASS] All requirements met!
Docker is already installed! Continuing...
Docker Compose is already installed. Continuing...
Prefer stable release versions of AzuraCast? [y/N] y
ERROR: Invalid interpolation format for "installer" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"
ERROR: Invalid interpolation format for "installer" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"
ERROR: Invalid interpolation format for "web" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"
ERROR: Invalid interpolation format for "web" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"
ERROR: Invalid interpolation format for "web" option in service "services": "ghcr.io/azuracast/web:${AZURACAST_VERSION:-latest}"
```

**Comment by dolphin-cat** [comment]
btw neofetch says OS: Debian GNU/Linux 11 (bullseye) x86_64

**Comment by SC2Mitch** [comment]
thanks, will do some checks now

**Comment by SlvrEagle23** [comment]
@dolphin-cat It looks like your installation has a pre-installed version of Docker Compose that's too old for our scripts. The easy solution should be to run:

```
cd /var/azuracast
./docker.sh install-docker-compose
./docker.sh install
```

and the installation should continue as normal.

**Comment by dolphin-cat** [comment]
Hmm weird, i did apt install docker-compose recently, what is required version?

**Comment by SlvrEagle23** [comment]
@dolphin-cat We use the 2.x version of Docker Compose, and that's likely a newer version than what is included with most Linux distributions. I'd recommend using our Docker Compose installer to ensure you're on a new enough version.

**Comment by dolphin-cat** [comment]
but my distro did not come with docker-compose, i did apt install docker docker.io docker-compose like 2 days ago when i did a fresh install

**Comment by dolphin-cat** [comment]
anyways i ran and it failed updating it so i just did ./docker-compose up -d
tell me if script runs extra commands so i can run them

**Comment by dolphin-cat** [comment]
it works but i have another issue now, i may just be stupid but ssl says its issued to localhost by localhost instead of to my server's ip by letsencrypt

**Comment by SC2Mitch** [comment]
Since the issue has been resolved, closing. 

To get SSL properly sorted, please review our documentation on how to setup Lets Encrypt.

**Comment by dolphin-cat** [comment]
i am using ./docker-compose instead of docker-compose so that won't work for me, i already have letsencrypt certs in default certbot path, how do i use them?

**Comment by dolphin-cat** [comment]
nvm problem fixed
