### ISSUE TITLE
LS Remote relay password have :#n added to the end of them ( SHOUTcast V1 )

### ISSUE THREAD

**Issue by OnlyTunes** [AzuraCast/AzuraCast#5085]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.15.0

### What happened?

Shoutcast V1 remote relay passwords have stream_id added to the end of the string `:#N` see test config below

```
# Remote Relays
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=320, id3v2=true), id="relay_1", host = "Remote URL", port = portNum, password = "somePassWord:#1", name = "Radio URL", description = "Main Station", genre = "charts", url = "Radio URL", public = false, encoding = "UTF-8", protocol="icy", radio)
```
*info was removed from the config above ( port URL's and Passwords )

### Relevant log output

```shell
2022/02/09 16:09:44 [relay_1:3] Connecting mount sid#1 for @Remote URL...
2022/02/09 16:09:44 [relay_1:2] Connection failed: bad answer: invalid password
2022/02/09 16:09:44 [relay_1:3] Will try again in 3.00 sec.
```

**Comment by Vaalyn** [comment]
### Debugging info and proposed solution (will be preparing a PR)

The part that is causing this is the following part of the ConfigWriter:
https://github.com/AzuraCast/AzuraCast/blob/main/src/Radio/Backend/Liquidsoap/ConfigWriter.php#L1063-L1067

The following part of this block can be removed (explanation below):
```php
if (StreamProtocols::Icy === $protocol) {
    $password .= ':#' . $id;
}
```

In the [`Entity\StationRemote::getAutodjPassword()`](https://github.com/AzuraCast/AzuraCast/blob/main/src/Entity/StationRemote.php#L196) the `:#N` part is already added to the returned password if (and only if) the Remote is of type Shoutcast V2. For the [`Entity\StationMount::getAutodjPassword()`](https://github.com/AzuraCast/AzuraCast/blob/main/src/Entity/StationMount.php#L386) this is not the case.

So by adding this to the `getAutodjPassword` method of the `Entity\StationMount` this block in the ConfigWriter is not needed anymore.
