### ISSUE TITLE
Multi-Site 

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#5088]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel and Rolling Release

### What happened?

After several tests between the stable version and the latest version.
With the stable version everything works normally I can access wordpress but with the latest version (Rolling Release #84a62a4]) I get the Azurast login page.

**Comment by ckeurk** [comment]
ok I just saw the new documentation https://docs.azuracast.com/en/administration/docker/multi-site-installation

**Comment by ckeurk** [comment]
I reopen my ticket because after several attempts I can't connect to wordpress.
But no problem to connect to AzuraCast. 
But for Wordpress I get a page 502 Bad Gateway.
Following the documentation I can't find the port to access wordpress.
thank you for your help.

**Comment by fhennig** [comment]
I ckeurk, I've set up multi-site with AzuraCast myself, and it sounds like your issue is unreleated to AzuraCast. To find out what the problem is you have to share your docker-compose file.

**Comment by ckeurk** [comment]
thank you for your answer
how I should share docker-compose file ?
thank you

**Comment by ckeurk** [comment]
On which port can I find wordpress? port 80?
