### ISSUE TITLE
Off topic: can I receive commit log via email?

### ISSUE THREAD

**Issue by dreinn** [AzuraCast/AzuraCast#509]
I'm really sorry but I don't know where asking this, I understand if the issue will be deleted, anyway I'd like to know if it is possible to receive via email when there are commits, so I can decide when and if update AzuraCast.
I receive all issues request, but do you know if also commits can be sent via email?

**Comment by mkody** [comment]
Hi, I personally use GitNotify for that: https://gitnotify.com

Here's how the mail looks like: 
![image](https://user-images.githubusercontent.com/843787/37726761-6b521d1e-2d36-11e8-8c6c-105a9f51f6af.png)

**Comment by dreinn** [comment]
Hello, the problem with gitnotify is that you receive that there is a commit but you can't know what's happened.
I want to search other services because I'd like to receive something like:

new commit by SlvrEagle23: worked on timezone settings... 
just for example.
So the comment of the developer is really important!

**Comment by mkody** [comment]
You click the link next to the branch name and you have a list of changes, from there you can open the commit details if you just want to see a single diff, or see the complete diff for the range of commits.
![image](https://user-images.githubusercontent.com/843787/38018227-92842ba0-3274-11e8-926c-f545958cff94.png)

**Comment by SlvrEagle23** [comment]
Closing as @mkody's suggestion is likely the best way to subscribe to a digest of commits made to AzuraCast. Large releases are promoted on Twitter, but a majority of the commits are fairly minor bug fixes and tweaks.
