### ISSUE TITLE
The base path "backup_%numb%.log is not an absolute path

### ISSUE THREAD

**Issue by Countryman98** [AzuraCast/AzuraCast#5092]
Azuracast Backups no longer working resulting in error message as attached in image:

Possibly related to issue https://github.com/AzuraCast/AzuraCast/issues/5090?

Rolling Release #[2001cd3](https://github.com/AzuraCast/AzuraCast/commit/2001cd3aef7b282e31ffe5586d88aaba51ce3f07) (2022-02-10 21:28) - Ubuntu 20.04 - Docker

![Capture](https://user-images.githubusercontent.com/65417549/153616999-222e4a83-d4b2-4535-914a-261e38193d19.JPG)

Application Log Tail:
```
web_1       | [2022-02-11T16:05:53.906917+00:00] AzuraCast.ERROR: Handling "App\Message\BackupMessage" failed: The command "'zip' '-r' '-n' '.tar.gz:.zip:.jpg:.mp3:.ogg:.flac:.aac:.wav' '/tmp/backup_56174.zip' 'tmp/azuracast_backup_mariadb/db.sql' 'var/azuracast/stations/mchavera/media' 'var/azuracast/stations/mggy/media' 'var/azuracast/stations/bloodpukejezus/media' 'var/azuracast/stations/leefm/media'" failed.  Exit Code: 3(Unknown error)  Working directory: /  Output: ================      zip warning: missing end signature--probably not a zip file (did you    zip warning: remember to use binary mode when you transferred it?)      zip warning: (if you are trying to read a damaged archive try -F)  zip error: Zip file structure invalid (/tmp/backup_56174.zip)   Error Output: ================  {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":129,"code":0} []
```

**Comment by SC2Mitch** [comment]
Verified, flagged. 

Thanks for the report, unsure why the template didn't work.

**Comment by SlvrEagle23** [comment]
Thank you for the report; figured out the source of the problem on my end. Should be fixed for backups of all types now.

**Comment by Countryman98** [comment]
Working well now. Thanks Team!
