### ISSUE TITLE
Shoutcast Block User Agent

### ISSUE THREAD

**Issue by YosefAdPro** [AzuraCast/AzuraCast#5100]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #2001cd3 (2022-02-10 21:28)

### What happened?

Following the discussion https://github.com/AzuraCast/AzuraCast/discussions/5047#discussioncomment-2152957

This solution `agentfile : File to store the list of blocked user agents [Default = sc_serv.agent]` Does not really work.
The block is executed only when it is registered in the `sc_serv.agent` file

I know support for Shoutcast is a low priority in the AzuraCast project so it's just an improvement proposal.

**Comment by SlvrEagle23** [comment]
@YosefAdPro If it's as simple as just making sure the file names match what Shoutcast is expecting, then the latest commit should fix it. It's deploying per the status above.

**Comment by YosefAdPro** [comment]
Now it's working.
But if I remove the agent from the blocked list through the azuracast interface it does not clear it from the shoutcast file.

**Comment by SlvrEagle23** [comment]
@YosefAdPro Yeah, it won't "sync" with that file if you change it via Shoutcast...it just manages it via the web UI, and if it changes, it's recommended to rewrite the configuration by reloading it.
