### ISSUE TITLE
External template (Question)

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#511]
Hello.

I wanted to use my own template instead of that of azuracast, is it possible to create a html / php page with nginx and make it communicate with azuracast? So you do not touch the azuracast panel?

**Comment by SlvrEagle23** [comment]
@Ilario42 If you're referring to a page that can play your radio station, then absolutely, you can build your own page and radio player with or without connecting to the AzuraCast web app directly.

If you want an example of how to connect directly to the AzuraCast data for your station, you can visit your station's public page (built into AzuraCast itself) and use the source code there as a guideline to follow when building your own.

If you just want a standard player out of the box, there are a number of options available that you can use and just point at your station's stream URL(s), like:

- http://jplayer.org/latest/demo-08/
- https://www.muses.org/setup

**Comment by Ilario42** [comment]
Yes @SlvrEagle23.

THX This work for me
![image](https://user-images.githubusercontent.com/22561729/38046442-028efec0-32c0-11e8-9e3c-8a1c6c1021b2.png)
