### ISSUE TITLE
Playlist bugs

### ISSUE THREAD

**Issue by ultragain** [AzuraCast/AzuraCast#5113]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#f848567 (2022-02-12 21:00)

### What happened?

since last update it ignores the settings from playlists like: 
Play exactly once every $x songs  -  Play exactly once every $x minutes.

It plays all songs inside the list, not just one track.

### Relevant log output

```shell
.
```

**Comment by radiopiraat** [comment]
I have the same problem.
Before the update i had a general playlist, a playlist that plays one song after 10 songs, a playlist for one song at every hoor and some more this does not work anymore.

**Comment by radiopiraat** [comment]
No solution yet
