### ISSUE TITLE
Error Update

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#5115]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #dcea1b9 (2022-01-18 9:40) • Docker • PHP 8.1 

### What happened?

Last login: Wed Feb 16 21:21:21 2022 from 81.193.63.242
ubuntu@ns329646:~$ cd /var/azuracast
ubuntu@ns329646:/var/azuracast$ ./docker.sh update-self
curl: (23) Failure writing output to destination
chmod: changing permissions of 'docker.sh': Operation not permitted
New Docker utility script downloaded.
ubuntu@ns329646:/var/azuracast$ ./docker.sh update
[NOTICE] Before you continue, please make sure you have a recent snapshot of your system and or backed it up.
Are you ready to continue with the update? [Y/n] Y
curl: (23) Failure writing output to destination
The Docker Utility Script has changed since your version. Update to latest version? [Y/n] Y
mv: cannot stat 'docker.new.sh': No such file or directory
chmod: changing permissions of 'docker.sh': Operation not permitted
A new Docker Utility Script has been downloaded.
Please re-run the update process to continue.
ubuntu@ns329646:/var/azuracast$

### Relevant log output

```shell
I was tried to upgrade this docker installation.
```

**Comment by SC2Mitch** [comment]
Did you try running with `sudo` permissions?

**Comment by jonikane** [comment]
I tried it now and it´s worked.

Thank you

but ssl is not working

it must be upgrade too after?

**Comment by SC2Mitch** [comment]
Whats not working with the SSL?

**Comment by jonikane** [comment]
azuracast install after upgrade don´nt work ssl on https://

**Comment by SlvrEagle23** [comment]
@jonikane Can you give us some more information? You may just need to run `./docker.sh letsencrypt-create` and re-set the values, depending on how old your installation was before this.

**Comment by jonikane** [comment]
Its ok now.

Thank you
