### ISSUE TITLE
WEB DJ sounds bad

### ISSUE THREAD

**Issue by la-roleplay** [AzuraCast/AzuraCast#5116]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.15.0

### What happened?

The song sounds bad when I use WEB DJ. They sound like beeps. -> https://streamable.com/pp4jyh
This has been happening to me for about a year.
It only happens with WEB DJ.

### Relevant log output

```shell
2022/02/17 10:36:47 [input_streamer:3] Decoding...
2022/02/17 10:36:47 [input_streamer:3] New metadata chunk Romeo Santos -- Sus Huellas.
2022/02/17 10:37:31 [live_fallback:3] Switch to map_metadata_0 with transition.
2022/02/17 10:37:37 [live_fallback:3] Switch to crossfade_0 with forgetful transition.
2022/02/17 10:37:43 [input_streamer:2] Error while reading from client: Harbor.Make(T).Websocket_closed
2022/02/17 10:37:43 [lang:3] DJ Source disconnected! Current live DJ: alejandro
2022/02/17 10:37:43 [lang:3] live_disconnected: Sending AzuraCast API DJ onDisconnect command...
2022/02/17 10:37:43 [lang:3] live_disconnected: AzuraCast API Response: true
2022/02/17 10:37:43 [input_streamer:2] Feeding stopped: Mad.End_of_stream.
2022/02/17 10:37:43 [lang:3] DJ Source disconnected! Current live DJ: 
2022/02/17 10:37:43 [lang:3] live_disconnected: Sending AzuraCast API DJ onDisconnect command...
2022/02/17 10:37:43 [lang:3] live_disconnected: AzuraCast API Response: true
2022/02/17 10:37:50 [lang:3] dj_auth: Sending AzuraCast API DJ Auth command for user: alejandro
2022/02/17 10:37:51 [lang:3] dj_auth: AzuraCast API Response: true
2022/02/17 10:37:51 [lang:3] DJ Source connected! Last authenticated DJ: alejandro - [("Origin", "https://radiofarmtruck.com"), ("Host", "radiofarmtruck.com"), ("Upgrade", "websocket"), ("Connection", "upgrade"), ("X-Real-IP", "hide"), ("X-Forwarded-For", "hide"), ("X-Forwarded-Proto", "https"), ("X-Forwarded-Ssl", "off"), ("X-Forwarded-Port", "443"), ("Accept-Encoding", "gzip"), ("CF-IPCountry", "ES"), ("CF-RAY", "6dee0a136c6a75bd-LHR"), ("CF-Visitor", "{\"scheme\":\"https\"}"), ("Pragma", "no-cache"), ("Cache-Control", "no-cache"), ("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"), ("Sec-WebSocket-Version", "13"), ("Accept-Language", "es-ES,es;q=0.9,en;q=0.8"), ("Cookie", "app_session=6bdfd772490feb059a728cba97996591"), ("Sec-WebSocket-Key", "uQsN8QfSWqccq1bQH579DQ=="), ("Sec-WebSocket-Extensions", "permessage-deflate; client_max_window_bits"), ("Sec-WebSocket-Protocol", "webcast"), ("CF-Connecting-IP", "hide"), ("CDN-Loop", "cloudflare")]
2022/02/17 10:37:51 [lang:3] live_connected: Sending AzuraCast API DJ onConnect command...
2022/02/17 10:37:51 [lang:3] live_connected: AzuraCast API Response: true
2022/02/17 10:37:51 [input_streamer:3] Decoding...
2022/02/17 10:37:51 [input_streamer:3] New metadata chunk Romeo Santos -- Sus Huellas.
2022/02/17 10:37:55 [live_fallback:3] Switch to map_metadata_0 with transition.
```

**Comment by ivellios1988** [comment]
Isn't your CPU overloaded?

**Comment by renatopinto89** [comment]
I also have that problem, the music crackles, and I doubt it's server resource related, since it happens everywhere I tried, from cheap VPS to full blown dedicated Ryzen servers. Never paid too much attention to it, because it only happens with WebDJ. Streaming from a outside source has no problems, but would be nice to figure out the reason.

**Comment by SC2Mitch** [comment]
I'll have a look. Is this issue present on dedicated streaming software such as Mixx or BUTT?

**Comment by SlvrEagle23** [comment]
I actually have this exact same problem locally. Seems to not matter what browser I'm using, either. The Web DJ is just snap, crackle, pops. Never have quite figured out why that happens to me and some others but not everyone.

**Comment by la-roleplay** [comment]
> As I continue to review this, can you confirm the bitrate and sample rate for me to do some local tests?

It does this at all bitrates. Only with WEB DJ.

**Comment by la-roleplay** [comment]
Any solution?

**Comment by Takumi86ES** [comment]
Any solutioooon?

**Comment by BusterNeece** [comment]
We've investigated this, and even updated the components used in our WebDJ tool, and discovered that this is just something of an inevitability with Chrome-based browsers. The issue seems to not exist on Firefox, so we strongly recommend using that if possible for the Web DJ.

**Comment by veerabiz1** [comment]
> We've investigated this, and even updated the components used in our WebDJ tool, and discovered that this is just something of an inevitability with Chrome-based browsers. The issue seems to not exist on Firefox, so we strongly recommend using that if possible for the Web DJ.

Thank you so much :) you saved me
