### ISSUE TITLE
Cannot request song

### ISSUE THREAD

**Issue by FiloSpaTeam** [AzuraCast/AzuraCast#5117]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.15.0 Stable • Docker • PHP 8.1

### What happened?

I was trying to request a song and a popup appeared with:
```
MalformedUriException at /var/azuracast/www/vendor/guzzlehttp/psr7/src/Uri.php L730: The path of a URI with an authority must start with a slash "/" or be empty
```

**Comment by radiorecord-ua** [comment]
Да подтверждаю есть такая проблема MalformedUriException at /var/azuracast/www/vendor/guzzlehttp/psr7/src/Uri.php L730: The path of a URI with an authority must start with a slash "/" or be empty при чём неизвесно с чем связанная

**Comment by SlvrEagle23** [comment]
@FiloSpaTeam We fixed several issues relating to URL resolution between version 0.15.0 and the current version. I'd strongly recommend updating at least to the latest stable version to help us confirm that the error is still in place in the latest stable version; if so, and your installation allows for it, you may want to test the latest Rolling Release version, which should most certainly have fixed this issue.

**Comment by FiloSpaTeam** [comment]
I'll check it (actually i'm using the last stable release)

**Comment by adelynx** [comment]
@SlvrEagle23 I just installed the latest Rolling version and I am having this issue tbh.
