### ISSUE TITLE
Error 502 Bad gateway on setting up after installation (Cloudfare)

### ISSUE THREAD

**Issue by Yusadolat** [AzuraCast/AzuraCast#512]
- **Installation Method:** 
- **Host OS (if using Docker):** 

**Describe the issue in full detail, including screenshots if possible:**
Hello there,
Azuracast shutdown itself while working, After trying some command revealed in the resolved issues and still didn't work tried reloading it. On setting it up I got an error in the below screenshot. I tried on other domain too. It still didn't work. What could go wrong, please
![azura_error](https://user-images.githubusercontent.com/10975011/37774657-baf4425a-2dd8-11e8-84e3-f31bc9b51953.png)

**Comment by SlvrEagle23** [comment]
@Yusadolat I have reverted some recent changes to the Docker container used in the AzuraCast web app; please update your local installation and let me know if the errors persist.

If so, please run `docker-compose logs -f web` and let me know if it's reporting any errors back when you visit a page.

**Comment by Yusadolat** [comment]
@SlvrEagle23  It works on new installation. Thanks so much for always been there

**Comment by SlvrEagle23** [comment]
@Yusadolat Happy to help, glad things are working now!
