### ISSUE TITLE
what is the procedure to change the public  ip address?

### ISSUE THREAD

**Issue by inetactief** [AzuraCast/AzuraCast#5122]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #7870205 (2022-02-04 2:30) • Docker • PHP 8.1

### What happened?

Hello,

We like to move the server and we get a new ip adress what is the procedure for that? 
Can not find it in the docs https://docs.azuracast.com/en

**Comment by renatopinto89** [comment]
The public IP is assigned to you by your server hosting provider. It has nothing to do with AzuraCast. Usually if you move providers/servers, a different IP will be assigned to that server.

**Comment by renatopinto89** [comment]
If you're running a domain and you keep the same domain, if you restore from a backup on your new AzuraCast installation, everything should work fine. Just make sure you point the domain to the new IP address on a A Record
