### ISSUE TITLE
Overlay files appear to be consuming all available space

### ISSUE THREAD

**Issue by Countryman98** [AzuraCast/AzuraCast#5127]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#8c2a9bf

### What happened?

Overlay files seem to be consuming all Disk space causing tasks to not run which in turn causes Azuracast to crash due to no available space?
![cap1](https://user-images.githubusercontent.com/65417549/154787810-90986d01-c076-466c-a359-fae2fab5774e.JPG)
![Capture1](https://user-images.githubusercontent.com/65417549/154787815-286eb173-68d0-49b8-947e-d14b75dba510.JPG)
.

**Comment by SC2Mitch** [comment]
Can you join our discord server so we can review this properly? We're trying to track down the exact cause of this

https://discord.gg/azuracast

**Comment by SlvrEagle23** [comment]
We did identify one source of a lot of space being used (the Liquidsoap builds were taking up twice the regular amount of space, which, when expanded, would certainly appear as if the volumes were largely overtaking the storage they normally take up). It may be that updating to a newer version helps with the total space usage.

If the volumes are still taking up too much space, we can continue to investigate, but it appears this is a rare situation.

**Comment by Countryman98** [comment]
Seems to have resolved itself with one of the Rolling Release updates. Thanks for you help
![Capture](https://user-images.githubusercontent.com/65417549/155644865-94276401-5282-47d9-be43-4a37c40433cd.JPG)
!
