### ISSUE TITLE
Additional Storage for Media and Playlist not working

### ISSUE THREAD

**Issue by blindgeek** [AzuraCast/AzuraCast#5128]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Trying to add a storage using the newly mounted volume (or at least that's how I understood it). But then I am getting an error.

Second question; the installation was migrated to another VPS then restored the backup from the previous server. However, it seems that playlists don't work as expected. But misteriously it plays some of my media probably from station commercial playlists but not the others. It is strange that I had to re-add all music tracks to their corresponding playlists but issue is still there nevertheless.

Cheers,

### Relevant log output

```shell
Error
ValidationException at /var/azuracast/www/src/Exception/ValidationException.php L37: Object(App\Entity\StorageLocation): Storage location Local: /mnt/AdditionalStorageForRadio/ could not be validated: Unable to create a directory at /mnt/AdditionalStorageForRadio. mkdir(): Permission denied
```

**Comment by fnfzlznddzn** [comment]
I have the same issue, trying to add a new local storage location but getting the mkdir() permission denied error. I am running Azuracast in Docker on Windows. i tried creating the folder in Windows (D:\radio), it is there and I can access it through the Ubuntu-WSL command line (at /mnt/d/radio). I have the same error when I try to add a folder from my system drive (C:).
I imagine it's an issue with permissions but have no idea how to get around it... i tried running Docker as administrator but that didn't change anything.

Thanks for any help! Azuracast is an amazing piece of software!
