### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by ritche** [AzuraCast/AzuraCast#513]
root@azura:/var/azuracast/www# docker-compose pull
Pulling letsencrypt (certbot/certbot:latest)...
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

How do I fix this?

-----
I am using Ubuntu 16.04.1 64bit LTS and I got a lot of errors also installing docker error.

E: Sub-process /usr/bin/dpkg returned an error code (1).

Can you provide which distro and version we can use without problem?

**Comment by SlvrEagle23** [comment]
@ritche Ubuntu 16.04 LTS works perfectly fine with the Docker installation method.

It sounds like you missed a step in the installation, specifically adding your user to the `docker` group, similar to:

```
usermod -aG docker yourusername
```

As noted in the readme, you have to restart after running the command above, before you can continue.

**Comment by ritche** [comment]
I am using root but the error comes after this command wget -qO- https://get.docker.com/ | sh

**Comment by ritche** [comment]
I am using root but the error comes after this command wget -qO- https://get.docker.com/ | sh

**Comment by ritche** [comment]
I will post the error while installing docker. This is s fresh box.

root@azura:~# wget -qO- https://get.docker.com/ | sh
# Executing docker install script, commit: 02d7c3c
+ sh -c apt-get update -qq >/dev/null
+ sh -c apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial edge" > /etc/apt/sources.list.d/docker.list
+ [ ubuntu = debian ]
+ sh -c apt-get update -qq >/dev/null
+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@azura:~#

**Comment by SlvrEagle23** [comment]
@ritche Since the Docker installer is provided directly by Docker themselves and not by AzuraCast, it's likely that this issue you're having is with their installer, rather than our tools. I would encourage you to look and see if there are other similar issues with your hosting provider and the Docker installer.

**Comment by ritche** [comment]
Okay I fixed that but I can another error.

root@azura:~# docker-compose pull
Pulling letsencrypt (certbot/certbot:latest)...
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
root@azura:~# service docker status
docker start/pre-start, process 14769
root@azura:~#

**Comment by ritche** [comment]
root@azura:~# docker-compose pull
Pulling letsencrypt (certbot/certbot:latest)...
ERROR: Couldn't connect to Docker daemon at http://127.0.0.1:2375 - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by SlvrEagle23** [comment]
@ritche I'm closing this issue since it appears to be an issue with how Docker CE itself runs on your hosting environment, and this is something that may have to do with your hosting environment or Docker itself, but likely doesn't have to do with AzuraCast.
