### ISSUE TITLE
Live dj metadata not working right

### ISSUE THREAD

**Issue by radiopiraat** [AzuraCast/AzuraCast#5139]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

When a Live dj connects for one or two second his metadata is showing than it changes in "Live broadcast" this problem is since the last update.

**Comment by SC2Mitch** [comment]
hi there, will be checking this out today, will let you know what my findings are.

**Comment by radiopiraat** [comment]
Hello Mitch,

Thank you i hope you find the problem.

**Comment by shaunzyb** [comment]
I think we might be having this issue too. 

We always connect via live dj (24hrs). We upgraded our playout systems yesterday and the new system data does not show, just says Live Broadcast. 

I did see in the access log multiple entries that contained the now playing info but Azuracast still said Live Broadcast.

I'll try and replicate and post log.

**Comment by shaunzyb** [comment]
I am seeing this entry in the access log

admin [07/Mar/2022:17:29:23 +0000] "GET /admin/metadata?mount/live&mode=updinfo&song=Call+It+What+You+Want%20by%20Taylor+Swift HTTP/1.1" 200 3829 "-" "Broadcast Radio Myriad OCP v5 (version 5.29.22060.0909)" 1

But nothing is displaying except "live Broadcast"

**Comment by inetactief** [comment]
Hello see here... https://github.com/AzuraCast/AzuraCast/commit/a7c541e64e78f5bbfca70324d9019957442b46e2

But the code change... need some help

**Comment by Kkspike** [comment]
We have the same issue since updating too. You guys are not alone.
