### ISSUE TITLE
Translation into other languages

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#514]
I almost updated the script, but when I looked at what happened with the translation, I was in shock. Tell me how to recompile it now in php as you do?
Convenience with translations used to be better, but then it will not be possible to track what's new for the translation, will it be necessary to revise almost 2000 lines all the time?

**Comment by SlvrEagle23** [comment]
@susl16c The system still uses the original `.po` files that it previously used, then uses a conversion script to create PHP files.

To convert from the .po files to PHP, just run:

(Traditional)
```
php /var/azuracast/www/util.cli locale:import
```

(Docker)
```
docker-compose run --rm cli azuracast_cli locale:import
```

**Comment by susl16c** [comment]
You can add command data to the main page so that when you update you can remember and watch them.
