### ISSUE TITLE
Removing a song from library - it also disappears from song / playback timeline?

### ISSUE THREAD

**Issue by onkelhermansson** [AzuraCast/AzuraCast#5141]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

Hi all,

When I delete a song from my library, it also disappears from song / playback timeline. 
Which means that my reporting becomes incomplete. I usually add / remove songs every other month, but I want to have full reports from the past anyway...

Is there another source of playback history data (where history remains intact even after I’ve deleted a song)?

Anyone else experienced this?

BR
O

**Comment by Vaalyn** [comment]
Which stable version are you using?

I have actually fixed this exact issue at the end of December (see https://github.com/AzuraCast/AzuraCast/pull/4928)

If you are on 0.15.0 or newer this is already fixed.

**Comment by onkelhermansson** [comment]
Much appreciated!
