### ISSUE TITLE
Problem with password recovery

### ISSUE THREAD

**Issue by BakiRadio** [AzuraCast/AzuraCast#5146]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.15.2

### What happened?

I want to recover my password, but I see this message. Please, help me to solve this problem.
![Безымянный](https://user-images.githubusercontent.com/100171923/155041843-77f6dbf2-d676-402e-ad6e-fa4cf7eb31d3.png)

**Comment by SC2Mitch** [comment]
How are you trying to recover, through the email password recovery I'm assuming?

**Comment by BakiRadio** [comment]
Yes, on the log in page I want to recover my password, but see this problem.
