### ISSUE TITLE
Azuracast panel not loading 

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#515]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Debian9

**Describe the issue in full detail, including screenshots if possible:**

After a fresh new install i was able to login and setup my station.Afte the i restarted the station couldnt acces the public page of it.I restarted my vps and now azuracast panel is t loading anymore.

root@vs:/opt/azuracast# docker-compose run --rm cli
Starting azuracast_redis_1 ... done
Starting azuracast_mariadb_1 ... done
Starting azuracast_stations ... done
Starting azuracast_influxdb_1 ... done
Starting azuracast_web_1 ... done
2018/03/23 15:13:46 Waiting for: tcp://mariadb:3306
2018/03/23 15:13:46 Waiting for: tcp://influxdb:8086
2018/03/23 15:13:47 Connected to tcp://mariadb:3306
2018/03/23 15:13:47 Connected to tcp://influxdb:8086
bash-4.4$ tail -f /var/azuracast/www_tmp/php_errors.log
[23-Mar-2018 15:12:57 UTC] PHP Fatal error: Uncaught InvalidArgumentException: Library theme_ not found! in /var/azuracast/www/app/src/AzuraCast/Assets.php:105
Stack trace:
#0 /var/azuracast/www/app/templates/minimal.phtml(38): AzuraCast\Assets->load('t heme_')
#1 /var/azuracast/www/vendor/league/plates/src/Template/Template.php(153): inclu de('/var/azuracast/...')
#2 /var/azuracast/www/vendor/league/plates/src/Template/Template.php(160): Leagu e\Plates\Template\Template->render(NULL)
#3 /var/azuracast/www/vendor/league/plates/src/Engine.php(277): League\Plates\Te mplate\Template->render(NULL)
#4 /var/azuracast/www/app/src/App/Mvc/View.php(56): League\Plates\Engine->render ('system/error_ge...', Array)
#5 /var/azuracast/www/app/src/App/Mvc/ErrorHandler.php(102): App\Mvc\View->rende rToResponse(Object(App\Http\Response), 'system/error_ge...', Array)
#6 [internal function]: App\Mvc\ErrorHandler->invoke(Object(App\Http\Request), Object(App\Http\Response), Object(InvalidArgumentException))
#7 /var/azuracast/www/vendor/slim/slim/Slim/App.php(665): call_user_fun in /var/ azuracast/www/app/src/AzuraCast/Assets.php on line 105
[23-Mar-2018 15:15:25 UTC] PHP Fatal error: Uncaught InvalidArgumentException: Library theme not found! in /var/azuracast/www/app/src/AzuraCast/Assets.php:105
Stack trace:
#0 /var/azuracast/www/app/templates/minimal.phtml(38): AzuraCast\Assets->load('theme')
#1 /var/azuracast/www/vendor/league/plates/src/Template/Template.php(153): include('/var/azuracast/...')
#2 /var/azuracast/www/vendor/league/plates/src/Template/Template.php(160): League\Plates\Template\Template->render(NULL)
#3 /var/azuracast/www/vendor/league/plates/src/Engine.php(277): League\Plates\Template\Template->render(NULL)
#4 /var/azuracast/www/app/src/App/Mvc/View.php(56): League\Plates\Engine->render('system/error_ge...', Array)
#5 /var/azuracast/www/app/src/App/Mvc/ErrorHandler.php(102): App\Mvc\View->renderToResponse(Object(App\Http\Response), 'system/error_ge...', Array)
#6 [internal function]: App\Mvc\ErrorHandler->__invoke(Object(App\Http\Request), Object(App\Http\Response), Object(InvalidArgumentException))
#7 /var/azuracast/www/vendor/slim/slim/Slim/App.php(665): call_user_fun in /var/azuracast/www/app/src/AzuraCast/Assets.php on line 105

**Comment by SlvrEagle23** [comment]
@surihost Should be fixed, update and let me know.

**Comment by surihost** [comment]
Yes i updated with docker and all is loading fine.
What i now see that that when restreaming some station, it play the stream on the port i set it up like  myserver.com: 8035 but its not playing from the azuracast panel and also not from its public page?

**Comment by SlvrEagle23** [comment]
@surihost That's an unrelated issue, and as always I want to stick to the "one issue per issue" rule here for ease of tracking and focus. Make a new ticket for that, since this one seems to be resolved.
