### ISSUE TITLE
Mount Points Page Doesn't Load Mount Points (error on page)

### ISSUE THREAD

**Issue by dvdokkum** [AzuraCast/AzuraCast#5151]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.15.2

### What happened?

When clicking on the Mount Points page under a station, the page loads but it doesn't display any of my mountpoints. I'm getting an error notification on the page:

```MalformedUriException at /var/azuracast/www/vendor/guzzlehttp/psr7/src/Uri.php L730: The path of a URI with an authority must start with a slash "/" or be empty```

It looks like the mounts API endpoint that the page hits is returning a 500 error with the following error message:

```StationNotFoundException at /var/azuracast/www/src/Middleware/RequireStation.php L23: Station not found.```

I'm not sure if this is relevant, but this station uses the URL Stub advanced config option.

**Comment by dvdokkum** [comment]
Just adding some screenshots... still an issue for me.
<img width="1920" alt="Screen Shot 2022-03-06 at 9 48 54 PM" src="https://user-images.githubusercontent.com/1800276/156959437-f87fe24a-2fc0-447f-8b1d-7e56ef48b401.png">
<img width="1914" alt="Screen Shot 2022-03-06 at 9 49 10 PM" src="https://user-images.githubusercontent.com/1800276/156959446-ccbf8681-9413-43bf-849d-850608502cbb.png">

**Comment by SC2Mitch** [comment]
Thanks for the report and the screenshots, I'll pass this onto the team for review.

**Comment by SlvrEagle23** [comment]
@dvdokkum Investigating this issue now and it appears, at least with the latest rolling release version, that it's almost impossible for me to reproduce this error, no matter what custom listen URL I put into the Mount settings.

Given your installation, would it be possible for you to update to the latest Rolling Release version and let me know if the issue is fixed? Alternately, if you could give me some more information about specific customization you may have done to your mount point settings, i.e. what custom URL you put in for them that may have caused the error.

**Comment by dvdokkum** [comment]
Hey @SlvrEagle23, thanks so much for taking some time to look into this. I know the Azuracast team is pretty swamped so the attention here is much appreciated ❤️. I can't update this instance because it is being used for FM broadcast right now, but I did try to replicate on my test server on the latest rolling release and was coming up empty. _However_, with some liberal mucking about with the system settings, I was able to fix the issue on our production server, so I think I may know the problem.

On the system settings main page, our **Site Base URL** did not have a protocol, it was just `remote.wxyc.org`. When I tried to make some unrelated changes to settings on this page, I got a form input warning saying that value for that field wasn't valid. I haven't updated this value in like 2 years so that seemed weird, but I went ahead and changed it to `https://remote.wxyc.org`. After I did that, the Mount Points page started loading as usual and the station API endpoint stopped returning 500 errors. 

<img width="1145" alt="Screen Shot 2022-03-18 at 2 38 04 PM" src="https://user-images.githubusercontent.com/1800276/159066429-a503d219-3c79-492a-9641-a9e277374c02.png">

So I guess maybe the expected format of this value changed at some point, but pre-existing values weren't updated to the new format?

Anyway, things seem to be working here now with that fix, but hope that helps uncover the underlying issue.

**Comment by SlvrEagle23** [comment]
@dvdokkum Aha, yeah, we actually already knew about that one...unfortunately, prior to a certain point, we weren't requiring "full" URLs in that field, and as of recently we started doing so, and the frontend validator is stricter about that kind of thing. It seems that most users were indeed able to fix it after updating their system settings, and it only affects users migrating from previous versions (and only once), so it shouldn't be too widespread of an issue.

Thank you for the extra information!
