### ISSUE TITLE
Station is playing the default error.mp3 files in a loop

### ISSUE THREAD

**Issue by pwrj** [AzuraCast/AzuraCast#5155]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #aa89a43 (2022-02-21 18:57) • Docker • PHP 8.1

### What happened?

I run 2 stations, but one of them started to play the error.mp3 in a loop irrespective of my Playlist set. I searched everywhere to resolve the issue to no avail. It's only happening to one station. I even created a new station to test and the issue does not happen with the newly created station. You can see part of LS log below:

Full Log:
[LS Log.txt](https://github.com/AzuraCast/AzuraCast/files/8135011/LS.Log.txt)

### Relevant log output

```shell
[mp3float @ 0x7f8208aedbc0] Could not update timestamps for discarded samples.
2022/02/18 22:20:56 [decoder:2] Decoding "/var/azuracast/stations/iacfm/media/Station ID/1.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/02/18 22:20:56 [playlist_station_id:3] Prepared "/var/azuracast/stations/iacfm/media/Station ID/2.mp3" (RID 55).
[mp3float @ 0x7f8208dbae80] Could not update timestamps for skipped samples.
2022/02/18 22:20:56 [cue_playlist_station_id:3] Cueing in...
2022/02/18 22:20:56 [crossfade_0:3] Analysis: -18.015175dB / -14.257062dB (4.48s / 4.48s)
2022/02/18 22:20:56 [crossfade_0:3] Simple transition: crossed, fade-in, fade-out.
[mp3float @ 0x7f8208dbae80] Could not update timestamps for discarded samples.
2022/02/18 22:21:00 [decoder:2] Decoding "/var/azuracast/stations/iacfm/media/Station ID/2.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/02/18 22:21:00 [playlist_station_id:3] Prepared "/var/azuracast/stations/iacfm/media/Station ID/3.mp3" (RID 154).
[mp3float @ 0x7f8208c00ec0] Could not update timestamps for skipped samples.
2022/02/18 22:21:01 [cue_playlist_station_id:3] Cueing in...
[mp3float @ 0x7f8208c00ec0] Could not update timestamps for discarded samples.
2022/02/18 22:21:01 [decoder:2] Decoding "/var/azuracast/stations/iacfm/media/Station ID/3.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/02/18 22:21:01 [crossfade_0:3] Analysis: -18.555635dB / -14.724198dB (4.44s / 4.44s)
2022/02/18 22:21:01 [crossfade_0:3] Simple transition: crossed, fade-in, fade-out.
2022/02/18 22:21:05 [playlist_station_id:3] Prepared "/var/azuracast/stations/iacfm/media/Station ID/1.mp3" (RID 56).
[mp3float @ 0x7f8208b1ec00] Could not update timestamps for skipped samples.
2022/02/18 22:21:05 [cue_playlist_station_id:3] Cueing in...
2022/02/18 22:21:05 [crossfade_0:3] Analysis: -infdB / -13.899207dB (0.16s / 0.16s)
2022/02/18 22:21:05 [crossfade_0:3] Simple transition: crossed, fade-in, fade-out.
[mp3float @ 0x7f8208b1ec00] Could not update timestamps for discarded samples.
2022/02/18 22:21:06 [decoder:2] Decoding "/var/azuracast/stations/iacfm/media/Station ID/1.mp3" ended: Ffmpeg_decoder.End_of_file.
```

**Comment by Vaalyn** [comment]
Does this station have the `Manual AutoDJ Mode` enabled in `Edit Station Profile` -> `AutoDJ` (first checkbox in the Advanced Configuration part at the bottom) ?

If so then this is most likely the thing that's causing it. Have seen this issue on a station today.

**Comment by pwrj** [comment]
I do not see that option though. See screenshots:
![1s](https://user-images.githubusercontent.com/7035452/155605025-27cbf968-95ce-4616-b761-3da04a43c37a.png)
![2s](https://user-images.githubusercontent.com/7035452/155605109-917ebb4c-aee4-4690-99f9-0cc32fcaeb89.png)
![3s](https://user-images.githubusercontent.com/7035452/155605153-c5f2bf62-b987-431b-804f-5beda03f811c.png)

**Comment by Vaalyn** [comment]
Oh then the Advanced features are hidden on your installation.
Please go to `Administration` -> `System Settings` and activate the `Enable Advanced Features` in the `Settings` tab.

Then check again for the Manual AutoDJ Mode.

**Comment by pwrj** [comment]
Wow!! Amazing. Thank you!! @Vaalyn for your help. This solved my issues!!
