### ISSUE TITLE
No playable tracks were found. But files are there

### ISSUE THREAD

**Issue by xifi-kif** [AzuraCast/AzuraCast#5156]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.15.2 Stable • Docker • PHP 8.1 

### What happened?

On a fresh docker installation, with data disk mounted with docker-compose.override ([as described here](https://github.com/AzuraCast/AzuraCast/issues/3131)), I can't listen to music. Media are there, I can play them in "music files" section, Liquidsoap shows them, playlist are set, but "on the air" just plays the default message.

The [public page](https://radio.mvtd.it/public/loma) and the [stream](https://radio.mvtd.it/radio/8000/radio.mp3) are not working either 

docker-compose logs is showing an error from azuracast_web: No playable tracks were found

But files are there!

![immagine](https://user-images.githubusercontent.com/22835942/155680887-78931ecb-7487-4025-8de1-69ac7c3309e9.png)

### Relevant log output

```shell
azuracast_web       | [2022-02-25T07:51:49.719609+00:00] AzuraCast.ERROR: No playable tracks were found. [] {"station":{"id":1,"name":"KOKO LOMA"}}
azuracast_web       | [2022-02-25T07:51:56.523906+00:00] AzuraCast.ERROR: No playable tracks were found. [] {"station":{"id":1,"name":"KOKO LOMA"}}
azuracast_web       | [2022-02-25T07:52:12.840263+00:00] AzuraCast.ERROR: No playable tracks were found. [] {"station":{"id":1,"name":"KOKO LOMA"}}

```
```

**Comment by SkeletorMonkey** [comment]
I had a similar problem.  I created new local storage to share music between radios /var/azuracast/music

After adding /stations/ it started working.  Like this > /var/azuracast/**stations**/music

Maybe this will help you too.  Good luck.

**Comment by SC2Mitch** [comment]
Can you provide your liquidsoap logs?

**Comment by xifi-kif** [comment]
After making my head explode for too much time, I backed up all my files and proceded to a clean install and everything went ok.
