### ISSUE TITLE
Liquidsoap download address is incorrect

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#5159]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#c9e8fc8

### What happened?

Hi there;

Have you requested a pull? Liquidsoap 2.0.3 download address for Ansible installations is wrong. You can see that the download link is not correct with the ```update.sh --full``` command. Can you fix this for future releases?

PR: https://github.com/AzuraCast/AzuraCast/pull/5160
LS Download Page: https://github.com/savonet/liquidsoap/releases/tag/v2.0.3
Azuracast Page: https://github.com/AzuraCast/AzuraCast/blob/main/util/ansible/roles/azuracast-radio/tasks/liquidsoap.yml

**Comment by SC2Mitch** [comment]
should be fixed in the latest rolling, thanks for the pull, it's greatly appriecated.
