### ISSUE TITLE
Error 500 - Custom Looks

### ISSUE THREAD

**Issue by RainbowDash53** [AzuraCast/AzuraCast#516]
Hello, I update to the last version and I edit the background for the login form in the admin panel, after I  update it, Error 500, impossible to connect..

**Comment by SlvrEagle23** [comment]
@RainbowDash53 If you're on Docker, try running `docker-compose logs -f web` and visiting the site again, and let me know what error it reports (if any).

**Comment by RainbowDash53** [comment]
I'm not using docker :/

**Comment by RainbowDash53** [comment]
root@185-163-125-250:~# tail -f /var/azuracast/www_tmp/php_errors.log
[23-Mar-2018 20:43:38 Europe/Berlin] PHP Fatal error:  Uncaught InvalidArgumentException: Library theme_0 not found! in /var/azuracast/www/app/src/AzuraCast/Assets.php:105
Stack trace:
#0 /var/azuracast/www/app/templates/minimal.phtml(38): AzuraCast\Assets->load('theme_0')
#1 /var/azuracast/www/vendor/league/plates/src/Template/Template.php(153): include('/var/azuracast/...')
#2 /var/azuracast/www/vendor/league/plates/src/Template/Template.php(160): League\Plates\Template\Template->render(NULL)
#3 /var/azuracast/www/vendor/league/plates/src/Engine.php(277): League\Plates\Template\Template->render(NULL)
#4 /var/azuracast/www/app/src/App/Mvc/View.php(56): League\Plates\Engine->render('system/error_ge...', Array)
#5 /var/azuracast/www/app/src/App/Mvc/ErrorHandler.php(102): App\Mvc\View->renderToResponse(Object(App\Http\Response), 'system/error_ge...', Array)
#6 [internal function]: App\Mvc\ErrorHandler->__invoke(Object(App\Http\Request), Object(App\Http\Response), Object(InvalidArgumentException))
#7 /var/azuracast/www/vendor/slim/slim/Slim/App.php(665): call_user_f in /var/azuracast/www/app/src/AzuraCast/Assets.php on line 105

**Comment by RainbowDash53** [comment]
Just do the latest updates, done, solved.
