### ISSUE TITLE
stats don't work

### ISSUE THREAD

**Issue by zilon93** [AzuraCast/AzuraCast#5165]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.15.2

### What happened?

When trying to configure the statistics of Listeners to 1 month, it stays loading and never shows these statistics, it only shows the statistics in real time

![fallo Azura 2](https://user-images.githubusercontent.com/50178250/156172466-69d224f8-550a-4dad-89f0-4b44d47274b9.png)
![fallo Azura](https://user-images.githubusercontent.com/50178250/156172472-0c0abd1a-8d34-499d-ac53-599abc87638b.png)

UPDATE: 
Now it shows this error when i try to enter 1 month, i think is that the logs are so huge.
![fallo Azura 3](https://user-images.githubusercontent.com/50178250/156177433-2705766c-2f85-43e7-a515-653ab315b074.png)

**Comment by Vaalyn** [comment]
Please check for any related PHP errors around the time the loading failed and post them here.

Also please open your browsers network console (F12 and then switching to the `Network` tab) then when you are on the report page try reloading the report and when the API listeners request failed take a look at the `response` of the request:
<img width="332" alt="image" src="https://user-images.githubusercontent.com/13745863/156184248-03f17432-7f0d-4dab-9ccc-6ac60f916f18.png">

**Comment by zilon93** [comment]
![image](https://user-images.githubusercontent.com/50178250/156352140-6aaaf9d7-b524-4e65-be04-4dc93be5184b.png)
 this is the response

**Comment by zilon93** [comment]
I´ve tried to change PHP Limits

512M memory limit
90 time limit

**Comment by Vaalyn** [comment]
Without seeing the AzuraCast Application Logs it's hard to tell where this issue is coming from.

**Comment by zilon93** [comment]
> Without seeing the AzuraCast Application Logs it's hard to tell where this issue is coming from.

How can i have this logs?

**Comment by zilon93** [comment]
![image](https://user-images.githubusercontent.com/50178250/156575905-df4f166f-8940-4f19-86f0-d3666024d70e.png)
This is the error

**Comment by Vaalyn** [comment]
There should be another error from PHP itself in there that relates to those. Will need that one to tell why exactly it is stopping.

**Comment by themadcap1976** [comment]
This seems to be related to the listener reports issue I'm having, there's another issue opened on this.

**Comment by themadcap1976** [comment]
https://github.com/AzuraCast/AzuraCast/issues/4978

**Comment by zilon93** [comment]
> There should be another error from PHP itself in there that relates to those. Will need that one to tell why exactly it is stopping.

If you tell me how to do it, i´ll do it right now

**Comment by Vaalyn** [comment]
You can find the `AzuraCast Application Log` in the `Administration` -> `System Logs` page.
Copy that, paste it into a .txt file and upload it in a comment here in this thread.

**Comment by zilon93** [comment]
There is not any error when i try to adquire the stats in this log.
[log azura 8 mar.txt](https://github.com/AzuraCast/AzuraCast/files/8205767/log.azura.8.mar.txt)
