### ISSUE TITLE
Mount Point URL Advanced custom not running

### ISSUE THREAD

**Issue by gunsar** [AzuraCast/AzuraCast#5169]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.15.2

### What happened?

Mount Point URL Advanced custom not running

I custom it to https://sub.domain.com:8000/moutpoint
not running/can't play on browser and media player

but https://sub.domain.com/radio/8000/moutpoint still works fine

**Comment by LordFader** [comment]
Got the same issue since last update...

**Comment by SC2Mitch** [comment]
Verified as a bug, tested on my local host.

**Comment by dvdokkum** [comment]
Is is possible that this issue is related to https://github.com/AzuraCast/AzuraCast/issues/5151?

**Comment by Guldstrand** [comment]
Still the same problem.
Custom mount point URL has no effect as of now.

**Comment by BusterNeece** [comment]
So I looked into this locally, and I can confirm that the Advanced "custom mount URL" does work as intended. To be clear, it's only intended to provide a custom URL in the AzuraCast page and API responses, not to actually modify the full path where the station can be listened to in the software. The "mount point name" (i.e. `/radio.mp3`) _does_ change that, but can only be changed within the base directory of the broadcasting software, i.e. `/listen/my_station/radio.mp3`. We don't currently support pointing _any_ URL on an AzuraCast installation to a stream, but these options afford some customization all the same.
