### ISSUE TITLE
Adding feeds to Google Podcasts returns noindex, no follow error. 

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#5170]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

A user has informed us they're having issues with trying to add feeds to Google Podcasts but they're unable to as it returns a noindex/nofollow response. 

Posting this here for Vaalyn's reminder. 
![image](https://user-images.githubusercontent.com/29955942/156810840-3267542f-9360-4a24-b8c0-0bf527d28b65.png)

**Comment by grscr** [comment]
From Google Search Console:

![image](https://user-images.githubusercontent.com/100958608/156816389-4ced762c-5060-44e6-9296-a72588f21d0f.png)
