### ISSUE TITLE
transmission error in dj streamer accounts

### ISSUE THREAD

**Issue by smaui** [AzuraCast/AzuraCast#5172]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

2022/02/26

### What happened?

does not connect the dj streamer user with any streaming software I am hosted on linode

### Relevant log output

```shell
does not connect the dj streamer user with any streaming software I am hosted on linode
```

**Comment by SC2Mitch** [comment]
We need some logs here, Liquidsoap or application logs. Without logs, we cannot really help.
