### ISSUE TITLE
Error 500 "/var/azuracast/www_tmp/proxies" must be writable

### ISSUE THREAD

**Issue by migueltoy** [AzuraCast/AzuraCast#518]
- **Installation Method:** Docker 
- **Host OS (if using Docker): ** Ubuntu 16.04 

**Describe the issue in full detail, including screenshots if possible:**
After the update to the latest version. this error appears after logging in.
<img width="1236" alt="screen shot 2018-03-24 at 01 42 44" src="https://user-images.githubusercontent.com/5246185/37858999-f54d30ce-2f04-11e8-8468-317daae384c0.png">

**Comment by SlvrEagle23** [comment]
@migueltoy When you ran the most recent updater, did it give you any errors?

In any event, you should be able to fix this by typing:

```
docker-compose run --rm cli
```

then, inside the container, running

```
rm -rf /var/azuracast/www_tmp/proxies
```
