### ISSUE TITLE
Couple of things to report

### ISSUE THREAD

**Issue by iplayradionetworks** [AzuraCast/AzuraCast#5184]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.15.2 Stable • Docker • PHP 8.1

### What happened?

Hi 

1. System Settings / Enable Advanced Features:
This setting regarding Advanced features, regardless if its enabled or disabled, the admin user (the superuser) should always have access to these features when managing someone's radio. 

2.  Making it simpler when creating a new radio for a user. Us the admins, have to first create user, then the radio station and then the role... and in the end match all these together.... and finally manually send an email to the user with his credentials to login to his panel. 

3.  Even after extending the radio ports ... for some strange reason, Liquidsoap.... never wants to proceed the playlist and move on to next song... after some small debugging (not being an expert tho) i am getting this error for a particular radio (shown below in the relevant log output) . I wish to use all ports from 8000 to 9999 for radios. And not sure tho what to do for Web DJ ports. And also got confused with the Nginx ports. I did some modifications in the related files under /var/azuracast and then restarted... but i am not sure i am doing it perhaps correctly. But after running some netstat commands i do see that the ports i want are open. Still cannot explain why some radios i created, the autodj cannot start properly... seems like its restarting ... 

4. Metadata not being parsed when web proxy setting is enableld. I guess this happens only on secure streaming via ssl. But when we open the stream url with IP + PORT / stream then we are able to get metadata on player without any issues. Suggestions ? 

5. Perhaps some more widgets like "Now Playing" so we can place this info on another radio player we might have on our site. Also perhaps an 'Album art" widget ? 

Best Regards
Jim

### Relevant log output

```shell
Fatal error: exception Error while trying to bind server/telnet socket: Address already in use in bind()
Raised at Server.start_telnet in file "tools/server.ml", line 463, characters 16-59
Called from Server.start in file "tools/server.ml", line 477, characters 19-34
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Dtools__Dtools_impl.Init.exec.exec in file "src/dtools_impl.ml", line 455, characters 10-16
Re-raised at Dtools__Dtools_impl.Init.exec.exec in file "src/dtools_impl.ml", line 466, characters 8-15
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
```

**Comment by SC2Mitch** [comment]
Hi, 

Adressing 1/2/4/5
These are suggestions and must go to our Feature Upvote page

Number 3, we could do with some more logs. It appears that the port is already in use so Liquidsoap cannot start the station accordingly.

**Comment by iplayradionetworks** [comment]
> Hi,
> 
> Adressing 1/2/4/5 These are suggestions and must go to our Feature Upvote page
> 
> Number 3, we could do with some more logs. It appears that the port is already in use so Liquidsoap cannot start the station accordingly.

Well ok i agree on that. But not sure what i can show you in order to understand what is happening. More likely it could be that but i can assure you tho that the port number assigned on that radio is not being used by any other radio. So that makes it more strange. 

There is a bit of a story on why i wish to probive specific ports tho on my clients. You see i used to have a known popular software.... from Canada... if you understand. And had some issues lately ... after i made a major upgrade on server. So i wanted to maintain the same ports i had for my clients. Which i managed to do so but for that particular radio seems like i can't . Even when i delete the manually assigned ports, and keep it blank so the system itself will assign one automatically... the same issue happens... 

Jim

**Comment by LordFader** [comment]
In fact since the last update of **AzuraCast • v0.15.2 Stable**; a lot of issues with SSL certificates cause all these disruptive behaviors around the streams. "web Players don't work" with old URL's...
eg: https://mydomain:8000/stream - don't work anymore in web browser/player (but if you put it in a mount point as Relay Stream URL - it works - internal azuracast)
eg: https://mydomain/radio/8000/stream - works in browser but don't work as internal Relay Stream URL in a mount point.

Tried all the Options in Admin panel on/off 
- Always Use HTTPS
- Prefer Browser URL (If Available)
- Use Web Proxy for Radio
- Use WebSockets for Now Playing Updates

...didn't get any changes with all these settings off or on.
No changes in docker-compose.yml, I don't have any override.yml.
So let's wait... the team is doing a nice work...(last update was a accident... it happens)
I would like to help... but I'm only a end user --- can't help with coding or debugging.

**Comment by SC2Mitch** [comment]
> I am trying to add another stream url in the mount point menu on the relay area in order to grab audio from another station.

> Seems it doesn't work. No matter what combination i used and setup variations no audio is coming. Only a hiss sound ...

If the audio is having issues, check your Liquidsoap logs, its hard to verify the issues your having without any type of logs.


> In fact since the last update of **AzuraCast • v0.15.2 Stable**; a lot of issues with SSL certificates cause all these disruptive behaviors around the streams. "web Players don't work" with old URL's...

This will require a new issue, we try to keep issues separate so our team can track them properly. 

Patience is greatly appriecated.

**Comment by iplayradionetworks** [comment]
> > I am trying to add another stream url in the mount point menu on the relay area in order to grab audio from another station.
> 
> > Seems it doesn't work. No matter what combination i used and setup variations no audio is coming. Only a hiss sound ...
> 
> If the audio is having issues, check your Liquidsoap logs, its hard to verify the issues your having without any type of logs.
> 
> > In fact since the last update of **AzuraCast • v0.15.2 Stable**; a lot of issues with SSL certificates cause all these disruptive behaviors around the streams. "web Players don't work" with old URL's...
> 
> This will require a new issue, we try to keep issues separate so our team can track them properly.
> 
> Patience is greatly appriecated.

I have already posted what shows in log. But surely can post more messages. 

The thing is that i cannot make experiments when having clients on board ... I want to avoid complaints as much as possible and in the end avoid of course losing them. 

Jim

**Comment by iplayradionetworks** [comment]
Something from the logs.... with a current station with autodj enabled and having already 6 files.... none is playing. Only the pre-recorded Azuracast audio message that station is LIVE.

2022/03/11 00:58:42 >>> LOG START
2022/03/11 00:58:38 [main:3] Liquidsoap 2.0.3-1
2022/03/11 00:58:38 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] posix-time2=2.0.0 pcre=7.5.0 sedlex=2.5 menhirLib=20211128 curl=0.9.2 memtrace=v0.2.1.2 mem_usage=0.0.1 dtools=0.4.4 duppy=0.9.2 cry=0.6.6 mm=0.8.0 xmlplaylist=0.1.5 lastfm=0.3.3 ogg=0.7.0 ogg.decoder=0.7.0 vorbis=0.8.0 vorbis.decoder=0.8.0 opus=0.2.1 opus.decoder=0.2.1 speex=0.4.0 speex.decoder=0.4.0 mad=0.5.0 flac=0.3.0 flac.ogg=0.3.0 flac.decoder=0.3.0 dynlink=[distributed with Ocaml] lame=0.3.5 shine=0.2.2 frei0r=0.1.2 fdkaac=0.3.2 theora=0.4.0 theora.decoder=0.4.0 ffmpeg=1.1.1 bjack=0.1.6 alsa=0.3.0 ao=0.2.3 samplerate=0.1.6 taglib=0.3.9 ssl=0.5.9 magic=0.7.3 camomile=1.0.2 inotify=2.3 yojson=1.7.0 faad=0.5.0 soundtouch=0.1.9 portaudio=0.2.3 pulseaudio=0.1.4 ladspa=0.2.0 dssi=0.1.3 tsdl=v0.9.8 tsdl-ttf=0.3.2 tsdl-image=0.3.2 camlimages=4.2.6 cohttp-lwt-unix=5.0.0 prometheus-app=1.1 srt.constants=0.2.2 srt.types=0.2.2 srt.stubs=0.2.2 srt.stubs.locked=0.2.2 srt=0.2.2 lo=0.2.0 gd=1.0a5
2022/03/11 00:58:39 [clock:3] Using native (high-precision) implementation for latency control
2022/03/11 00:58:41 [playlist.basic:3] Wrong mime type application/csv for playlist!
2022/03/11 00:58:42 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz main.
2022/03/11 00:58:42 [frame:3] Video frame size set to: 1280x720
2022/03/11 00:58:42 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2022/03/11 00:58:42 [frame:3] Targeting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2022/03/11 00:58:42 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2022/03/11 00:58:42 [sandbox:3] Running inside a docker container, disabling sandboxing.
2022/03/11 00:58:42 [video.converter:3] Using preferred video converter: ffmpeg.
2022/03/11 00:58:42 [audio.converter:3] Using samplerate converter: ffmpeg.
2022/03/11 00:58:42 [clock.main:2] Error when starting input_streamer: Address already in use in bind()!
2022/03/11 00:58:42 [lang:3] API djoff - Sending POST request to 'http://web/api/internal/29/djoff' with body: { "user": "" }
2022/03/11 00:58:42 [lang:3] API djoff - Response (200): true
2022/03/11 00:58:42 [clock:2] Error when leaving output input_streamer: Not_found!
2022/03/11 00:58:42 [clock.main:2] Error when starting local_1: Address already in use in bind()!
2022/03/11 00:58:42 [lang:3] API djoff - Sending POST request to 'http://web/api/internal/29/djoff' with body: { "user": "" }
2022/03/11 00:58:42 [lang:3] API djoff - Response (200): true
2022/03/11 00:58:42 [clock:2] Error when leaving output local_1: Not_found!
2022/03/11 00:58:42 [main:3] Shutdown started!
2022/03/11 00:58:42 [main:3] Waiting for main threads to terminate...
2022/03/11 00:58:42 [main:3] Main threads terminated.
2022/03/11 00:58:42 [threads:3] Shutting down scheduler...
2022/03/11 00:58:42 [threads:3] Scheduler shut down.
2022/03/11 00:58:42 [main:3] Cleaning downloaded files...
2022/03/11 00:58:42 [main:3] Freeing memory...

**Comment by iplayradionetworks** [comment]
One other question is.... 

The new web-proxied url is something like https://cast.iplayradio.net/radio/8013/stream .... 
While before it used to be like https://cast.iplayradio.net:8013/stream -> but this says i am not secured... .

I thought that the subdomain i have is ... but in reality i am not using an actual sub-domain but only an A record from DNS.

Should i be actually creating a real sub-domain ?

**Comment by SC2Mitch** [comment]
Okay so, just want to clear things up.

We are **asking** for your patience here, please don't post on multiple other issues bumping them up the queue, it does not make your issue any higher in priority. We deal with many commercial resellers which ultimately don't kick down contributions to the AzuraCast team. The team will review this ticket when we have time. Please note we're a tiny team of 2 developers, 1 community mod, that's it. 

If you believe this issue is mission critical to your business, we offer premium support options at https://azuracast.support

**Comment by iplayradionetworks** [comment]
> Okay so, just want to clear things up.
> 
> We are **asking** for your patience here, please don't post on multiple other issues bumping them up the queue, it does not make your issue any higher in priority. We deal with many commercial resellers which ultimately don't kick down contributions to the AzuraCast team. The team will review this ticket when we have time. Please note we're a tiny team of 2 developers, 1 community mod, that's it.
> 
> If you believe this issue is mission critical to your business, we offer premium support options at https://azuracast.support

I am sorry. I am not trying to create problems. I just read also the other issues that other users have and just post my reply there. Wasn't sure that this was somehow forbidden............... 

I am not trying, with that mentioned above, to escalate my issues in a higher priority . I know that this is an open source software and will have issues and issus are meant to be solved. And also mentioned that i will contribute to the team for all the developement efforts done here. 

I will tho consider the premium support options :)

Thanks
