### ISSUE TITLE
Last azuracast update

### ISSUE THREAD

**Issue by Muppet11** [AzuraCast/AzuraCast#5188]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Unknown

### What happened?

During last update install.
Got a lot of errors.
This is a part of the output of terminal screen:

edis 6.0.6 (00000000/0) 64 bit             .-`` .-```.  ```\/    _.,_ ''-._                                                 (    '      ,       .-`  | `,    )     Running in standalone mode                 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379                                 |    `-._   `._    /     _.-'    |     PID: 78                                     `-._    `-._  `-./  _.-'    _.-'                                                 |`-._`-._    `-.__.-'    _.-'_.-'|                                                |    `-._`-._        _.-'_.-'    |           http://redis.io                       `-._    `-._`-.__.-'_.-'    _.-'                                                 |`-._`-._    `-.__.-'    _.-'_.-'|                                                |    `-._`-._        _.-'_.-'    |                                                 `-._    `-._`-.__.-'_.-'    _.-'                                                      `-._    `-.__.-'    _.-'                                                              `-._        _.-'                                                                      `-.__.-'                                                                                                     78:M 10 Mar 2022 17:28:07.515 # Server initialized                                78:M 10 Mar 2022 17:28:07.515 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.   78:M 10 Mar 2022 17:28:07.515 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.           78:M 10 Mar 2022 17:28:07.516 * Ready to accept connections                       Starting up AzuraCast services...        2022-03-10 17:28:07 0 [Note] mysqld (mysqld 10.5.15-MariaDB-1:10.5.15+maria~focal) starting as process 76 ...              2022-03-10 17:28:07 0 [Note] InnoDB: Uses event mutexes                           2022-03-10 17:28:07 0 [Note] InnoDB: Compressed tables use zlib 1.2.11            2022-03-10 17:28:07 0 [Note] InnoDB: Number of pools: 1                           2022-03-10 17:28:07 0 [Note] InnoDB: Using generic crc32 instructions             2022-03-10 17:28:07 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)                        2022-03-10 17:28:07 0 [Note] InnoDB: Using Linux native AIO                       2022-03-10 17:28:07 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728              2022-03-10 17:28:07 0 [Note] InnoDB: Completed initialization of buffer pool      2022-03-10 17:28:07 0 [Note] InnoDB: 128 rollback segments are active.            2022-03-10 17:28:07 0 [Note] InnoDB: Creating shared tablespace for temporary tables                                       2022-03-10 17:28:07 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...                                       2022-03-10 17:28:07 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.           2022-03-10 17:28:07 0 [Note] InnoDB: 10.5.15 started; log sequence number 44244206005; transaction id 9853265              2022-03-10 17:28:07 0 [Note] Plugin 'FEEDBACK' is disabled.                       2022-03-10 17:28:07 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool                             2022-03-10 17:28:07 0 [Note] Server socket created on 

### Relevant log output

```shell
edis 6.0.6 (00000000/0) 64 bit             .-`` .-.  ```\/    _.,_ ''-._                                                 (    '      ,       .-`  | `,    )     Running in standalone mode                 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379                                 |    `-._   `._    /     _.-'    |     PID: 78                                     `-._    `-._  `-./  _.-'    _.-'                                                 |`-._`-._    `-.__.-'    _.-'_.-'|                                                |    `-._`-._        _.-'_.-'    |           http://redis.io                       `-._    `-._`-.__.-'_.-'    _.-'                                                 |`-._`-._    `-.__.-'    _.-'_.-'|                                                |    `-._`-._        _.-'_.-'    |                                                 `-._    `-._`-.__.-'_.-'    _.-'                                                      `-._    `-.__.-'    _.-'                                                              `-._        _.-'                                                                      `-.__.-'                                                                                                     78:M 10 Mar 2022 17:28:07.515 # Server initialized                                78:M 10 Mar 2022 17:28:07.515 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.   78:M 10 Mar 2022 17:28:07.515 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.           78:M 10 Mar 2022 17:28:07.516 * Ready to accept connections                       Starting up AzuraCast services...        2022-03-10 17:28:07 0 [Note] mysqld (mysqld 10.5.15-MariaDB-1:10.5.15+maria~focal) starting as process 76 ...              2022-03-10 17:28:07 0 [Note] InnoDB: Uses event mutexes                           2022-03-10 17:28:07 0 [Note] InnoDB: Compressed tables use zlib 1.2.11            2022-03-10 17:28:07 0 [Note] InnoDB: Number of pools: 1                           2022-03-10 17:28:07 0 [Note] InnoDB: Using generic crc32 instructions             2022-03-10 17:28:07 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)                        2022-03-10 17:28:07 0 [Note] InnoDB: Using Linux native AIO                       2022-03-10 17:28:07 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728              2022-03-10 17:28:07 0 [Note] InnoDB: Completed initialization of buffer pool      2022-03-10 17:28:07 0 [Note] InnoDB: 128 rollback segments are active.            2022-03-10 17:28:07 0 [Note] InnoDB: Creating shared tablespace for temporary tables                                       2022-03-10 17:28:07 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...                                       2022-03-10 17:28:07 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.           2022-03-10 17:28:07 0 [Note] InnoDB: 10.5.15 started; log sequence number 44244206005; transaction id 9853265              2022-03-10 17:28:07 0 [Note] Plugin 'FEEDBACK' is disabled.                       2022-03-10 17:28:07 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool                             2022-03-10 17:28:07 0 [Note] Server socket created on IP: '::'.                   2022-03-10 17:28:07 0 [Warning] 'proxies_priv' entry '@% root@17b7f5f69fa2' ignored in --skip-name-resolve mode.           2022-03-10 17:28:07 

Did just a simple update.

Thanks for any help.
Grtz,
Rob
```

**Comment by SlvrEagle23** [comment]
@Muppet11 The latest update did change what you see log-wise when running a routine installation or update, but the extra messages aren't necessarily error messages, just messages about related services spinning up. This is because we now have a "unified" Docker container, where all processes run in the same container.

Is your installation working correctly now? If so, then it's likely that the update completed without any issues.

**Comment by Muppet11** [comment]
Yes.
Problem solved!
Thanks for the info👍

via 
Mobiel

**Comment by Vaalyn** [comment]
Closing as resolved
