### ISSUE TITLE
error 500 after configure url adress

### ISSUE THREAD

**Issue by kazwashere** [AzuraCast/AzuraCast#519]
#Installation Method: Traditional
Host OS :  Ubuntu 16.04 LTS

**Describe the issue in full detail, including screenshots if possible:**

Hello, i recently instaling Azurecast in my VPS. after succesfull setup and goes to edit stream server, i've go around public page setting. since i already have a domain adress to use i want to use it as main page adress, not as azurecast server. 

after i decide to hide azurecast logo, #upload some music file and switch intu https. i seems cant go into my main public page. 

and now i cant go into login page and showing error 500 says "unable to handle request" 

i dont know what is happened so maybe i think i will re-instal again if this one problem are critical one.

**Comment by SlvrEagle23** [comment]
@kazwashere Try running `tail -f /var/azuracast/www_tmp/php_errors.log` and see if it's returning any particular error message, and let me know what that error is.

**Comment by kazwashere** [comment]
![troubleshooting error](https://user-images.githubusercontent.com/37731027/37861811-fd38e354-2f73-11e8-8e6b-60981c2addd5.JPG)

okay. i take screenshot just in case.

**Comment by SlvrEagle23** [comment]
@kazwashere Thank you, that helped figure it out very quickly.

I've pushed an update to the codebase; try updating and see if it's still a problem. You'll probably need to set the default public theme again.

**Comment by kazwashere** [comment]
works like a charm.
