### ISSUE TITLE
Docker and Docker Compose Changes in 0.16.0 Stable and Newer

### ISSUE THREAD

**Issue by BusterNeece** [AzuraCast/AzuraCast#5191]
### Summary

AzuraCast has been making some fundamental changes to how our Docker infrastructure works. For most users, this won't result in any changes to your experience and upgrades should complete without issues, but if you've made customizations to your `docker-compose.override.yml` file, you will need to make changes as outlined below.

### What's Changed

Previously (including in all stable releases up to 0.15.2), AzuraCast used a number of Docker containers working in unison to provide services. For many years, there were as many as 7 containers in total, and recently this was reduced to 6, and then 4 containers. Our latest update reduces the number of total containers to _one_ single container managing the entire AzuraCast infrastructure.

The technical reason for this change is to allow users who use Docker app distributors (like Portainer or DockSTARTer) to be able to easily spin up AzuraCast without having to maintain our full Docker Compose ecosystem. It also opens the door for significant possibilities down the road for AzuraCast to control its own services, including possibly even controlling its own automated updates.

### What You Need to Change

If you update and get an error from Docker Compose indicating your configuration file is invalid, you should check to make sure you have a `docker-compose.override.yml` file in your installation directory (by default, `/var/azuracast`). If you don't have such a file present, then you should create a new GitHub issue to report the problem, as it's a different issue than the one mentioned here.

If you **do** have a `docker-compose.override.yml` file, you should open it in your editor of choice and remove any subsections that don't relate to the `web` service.

For example, if your file looks like this:

```yaml
services:
  web:
    volumes:
      - /path/on/disk:/var/azuracast/stations

  stations:
    volumes:
      - /path/on/disk:/var/azuracast/stations
```

Then you should remove the section starting with `stations` and anything "inside" that section (i.e. indented further inward), so your file would look like:

```yaml
services:
  web:
    volumes:
      - /path/on/disk:/var/azuracast/stations
```

You can then test that your changes worked by restarting AzuraCast by running:

```bash
docker-compose down
docker-compose up -d
```

### Common Scenarios

- If you added an override file to customize where station media is stored, your file will likely look a lot like the example above; simply removing the `stations` portion of the file should fix the issue and your station media will still be located in its custom location.
- If you only had an override file to customize the AzuraCast custom error message (the "This station is powered by AzuraCast" message), then you no longer need that file at all and can remove it, as you can now set a custom error/fallback message directly from within AzuraCast on a per-station basis.
- If your override file only modifies the `web` container (i.e. to provide custom code or plugins) then no modification should be required.

**Comment by gunsar** [comment]
thak's
I want to ask for custom ssl with the command below, why doesn't it work? any other way?
I've set it, but after checking SSL it's still detected Let's Encrypt

version: '2.2'

services:
  nginx_proxy:
    volumes:
      - /etc/ssl/ssl.crt:/etc/nginx/certs/live.xxxxxx.com.crt:ro
      - /etc/ssl/ssl.key:/etc/nginx/certs/live.xxxxxx.com.key:ro

  stations:
    volumes:
      - /etc/ssl/ssl.crt:/etc/nginx/certs/live.xxxxxx.com.com.crt:ro
      - /etc/ssl/ssl.key:/etc/nginx/certs/live.xxxxxx.com.com.key:ro

**Comment by gunsar** [comment]
services:
  web:
    volumes:
      - /path/on/host/to/ssl.crt:/etc/nginx/certs/ssl.crt:ro
      - /path/on/host/to/ssl.key:/etc/nginx/certs/ssl.key:ro

  stations:
    volumes:
      - /path/on/host/to/ssl.crt:/etc/nginx/certs/ssl.crt:ro
      - /path/on/host/to/ssl.key:/etc/nginx/certs/ssl.key:ro

I replaced it with this, the result is the same, after checking the SSL it reads only Lets' Encrype, even though I have set it and it should be Sectigo PositiveSSL, I'm confused

**Comment by SlvrEagle23** [comment]
@gunsar That's correct, but remove the `stations` item. Also, make sure you're updating to the latest Rolling Release and not the latest Stable.

**Comment by gunsar** [comment]
> @gunsar That's correct, but remove the `stations` item. Also, make sure you're updating to the latest Rolling Release and not the latest Stable.

I will try it, thank you

**Comment by Muppet11** [comment]
Hello,
Can‘t get the latest update installed.
Didn‘t change override.yml, but got a lot of errors in terminal screen.
Station is of the air..
Thanks for the help!

**Comment by Muppet11** [comment]
Part of the screendump:

Restarting all radio stations...         --------------------------------                                                   0/1 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%2022-03-11 17:43:33,764 INFO success: station_1_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                                2022-03-11 17:43:33,765 INFO success: station_1_frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                              2022-03-11 17:43:35,011 INFO waiting for station_1_backend to stop                2022-03-11 17:43:35,028 INFO stopped: station_1_backend (terminated by SIGTERM)   2022-03-11 17:43:35,033 INFO spawned: 'station_1_backend' with pid 151            2022-03-11 17:43:36,036 INFO success: station_1_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                                1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%                                                                                    [OK] AzuraCast is now updated to the          latest version!                                                                                                      *** uptime_wait exited with status 0.    76:signal-handler (1647020616) Received SIGTERM scheduling shutdown...            2022-03-11 17:43:36 0 [Note] mysqld (initiated by: unknown): Normal shutdown      2022-03-11 17:43:36 0 [Note] Event Scheduler: Purging the queue. 0 events         2022-03-11 17:43:36 0 [Note] InnoDB: FTS optimize thread exiting.                 2022-03-11 17:43:36 0 [Note] InnoDB: Starting shutdown...                         2022-03-11 17:43:36 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool                               2022-03-11 17:43:36 0 [Note] InnoDB: Restricted to 2016 pages due to innodb_buf_pool_dump_pct=25                           2022-03-11 17:43:36 0 [Note] InnoDB: Buffer pool(s) dump completed at 220311 17:43:36                                      76:M 11 Mar 2022 17:43:36.159 # User requested shutdown...                        76:M 11 Mar 2022 17:43:36.159 # Redis is now ready to exit, bye bye...            2022-03-11 17:43:36 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"                                      2022-03-11 17:43:36 0 [Note] InnoDB: Shutdown completed; log sequence number 44518431192; transaction id 9897290           2022-03-11 17:43:36 0 [Note] mysqld: Shutdown complete                                                                     2022-03-11 17:43:37,062 WARN received SIGTERM indicating exit request             2022-03-11 17:43:37,063 INFO waiting for station_1_backend, station_1_frontend to die                                      2022-03-11 17:43:38,075 INFO stopped: station_1_backend (terminated by SIGTERM)   2022-03-11 17:43:40,078 INFO waiting for station_1_frontend to die                2022-03-11 17:43:42,085 INFO stopped: station_1_frontend (exit status 0)          *** Shutting down runit daemon (PID 70)...                                        *** Killing all processes...             Creating azuracast ... done              Clean up all stopped Docker containers and images to save space? [Y/n] y          Deleted Networks:                        azuracast_installer_default                                                       Total reclaimed space: 0B                Update complete!

**Comment by gunsar** [comment]
I tried Rolling Release

Powered by [AzuraCast](https://www.azuracast.com/) • Rolling Release #[ef4c438](https://github.com/AzuraCast/AzuraCast/commit/ef4c4388572248afe93a9441fc1e6cc3a8ee3ec4) (2022-03-12 6:49) • Docker • PHP 8.1

docker-compose.override.yml

services:
  web:
    volumes:
      - /etc/ssl/ssl.crt:/etc/nginx/certs/ssl.crt:ro
      - /etc/ssl/ssl.key:/etc/nginx/certs/ssl.key:ro

  stations:
    volumes:
      - /etc/ssl/ssl.crt:/etc/nginx/certs/ssl.crt:ro
      - /etc/ssl/ssl.key:/etc/nginx/certs/ssl.key:ro

I replaced it with this, the result is the same, after checking the SSL it reads only Lets' Encrype, even though I have set it and it should be Sectigo PositiveSSL, I'm confused

**Comment by Muppet11** [comment]
Solved!(at least with my installation)
Fresh install did the trick👍
running smooth!

**Comment by LordHelmchen666** [comment]
> I tried Rolling Release
> 
> Powered by [AzuraCast](https://www.azuracast.com/) • Rolling Release #[ef4c438](https://github.com/AzuraCast/AzuraCast/commit/ef4c4388572248afe93a9441fc1e6cc3a8ee3ec4) (2022-03-12 6:49) • Docker • PHP 8.1
> 
> using custom URL https://sub.comain.com:port/mountpoint (Work Normal)
> 
> Edit docker-compose.override.yml
> 
> services: web: volumes: - /etc/ssl/ssl.crt:/etc/nginx/certs/ssl.crt:ro - /etc/ssl/ssl.key:/etc/nginx/certs/ssl.key:ro
> 
> stations: volumes: - /etc/ssl/ssl.crt:/etc/nginx/certs/ssl.crt:ro - /etc/ssl/ssl.key:/etc/nginx/certs/ssl.key:ro
> 
> I replaced it with this, the result is the same, after checking the SSL it reads only Lets' Encrype, even though I have set it and it should be Sectigo PositiveSSL, I'm confused

@gunsar Take time and read SlvrEagles first post, then read it again and read it once more. 

>Then you should remove the section starting with stations and anything "inside" that section (i.e. indented further inward), so your file would look like:

Delete your in docker-compose.override.yml where it starts with "stations". So your docker-compose.override.yml should look like this
```
services:
web:
volumes:
- /etc/ssl/ssl.crt:/etc/nginx/certs/ssl.crt:ro
- /etc/ssl/ssl.key:/etc/nginx/certs/ssl.key:ro
```

**Comment by gunsar** [comment]
> 



> > I tried Rolling Release
> > Powered by [AzuraCast](https://www.azuracast.com/) • Rolling Release #[ef4c438](https://github.com/AzuraCast/AzuraCast/commit/ef4c4388572248afe93a9441fc1e6cc3a8ee3ec4) (2022-03-12 6:49) • Docker • PHP 8.1
> > using custom URL https://sub.comain.com:port/mountpoint (Work Normal)
> > Edit docker-compose.override.yml
> > services: web: volumes: - /etc/ssl/ssl.crt:/etc/nginx/certs/ssl.crt:ro - /etc/ssl/ssl.key:/etc/nginx/certs/ssl.key:ro
> > stations: volumes: - /etc/ssl/ssl.crt:/etc/nginx/certs/ssl.crt:ro - /etc/ssl/ssl.key:/etc/nginx/certs/ssl.key:ro
> > I replaced it with this, the result is the same, after checking the SSL it reads only Lets' Encrype, even though I have set it and it should be Sectigo PositiveSSL, I'm confused
> 
> @gunsar Take time and read SlvrEagles first post, then read it again and read it once more.
> 
> > Then you should remove the section starting with stations and anything "inside" that section (i.e. indented further inward), so your file would look like:
> 
> Delete your in docker-compose.override.yml where it starts with "stations". So your docker-compose.override.yml should look like this
> 
> ```
> services:
> web:
> volumes:
> - /etc/ssl/ssl.crt:/etc/nginx/certs/ssl.crt:ro
> - /etc/ssl/ssl.key:/etc/nginx/certs/ssl.key:ro
> ```

Thank's solved

**Comment by SC2Mitch** [comment]
> > 
> 
> > > I tried Rolling Release
> > > Powered by [AzuraCast](https://www.azuracast.com/) • Rolling Release #[ef4c438](https://github.com/AzuraCast/AzuraCast/commit/ef4c4388572248afe93a9441fc1e6cc3a8ee3ec4) (2022-03-12 6:49) • Docker • PHP 8.1
> > > using custom URL https://sub.comain.com:port/mountpoint (Work Normal)
> > > Edit docker-compose.override.yml
> > > services: web: volumes: - /etc/ssl/ssl.crt:/etc/nginx/certs/ssl.crt:ro - /etc/ssl/ssl.key:/etc/nginx/certs/ssl.key:ro
> > > stations: volumes: - /etc/ssl/ssl.crt:/etc/nginx/certs/ssl.crt:ro - /etc/ssl/ssl.key:/etc/nginx/certs/ssl.key:ro
> > > I replaced it with this, the result is the same, after checking the SSL it reads only Lets' Encrype, even though I have set it and it should be Sectigo PositiveSSL, I'm confused
> > 
> > 
> > @gunsar Take time and read SlvrEagles first post, then read it again and read it once more.
> > > Then you should remove the section starting with stations and anything "inside" that section (i.e. indented further inward), so your file would look like:
> > 
> > 
> > Delete your in docker-compose.override.yml where it starts with "stations". So your docker-compose.override.yml should look like this
> > ```
> > services:
> > web:
> > volumes:
> > - /etc/ssl/ssl.crt:/etc/nginx/certs/ssl.crt:ro
> > - /etc/ssl/ssl.key:/etc/nginx/certs/ssl.key:ro
> > ```
> 
> Thank's SSL solved change to Sectigo PositiveSSL
> 
> but I'm still confused to replace the audio error with a jingle
> 
> services: stations: volumes: - /var/local/jingle.mp3:/usr/local/share/icecast/web/error.mp3
> 
> using the command doesn't work

We offer this natively now, you don't need to use a Docker Compose modification.

**Comment by gunsar** [comment]
> > > > I tried Rolling Release
> > > > Powered by [AzuraCast](https://www.azuracast.com/) • Rolling Release #[ef4c438](https://github.com/AzuraCast/AzuraCast/commit/ef4c4388572248afe93a9441fc1e6cc3a8ee3ec4) (2022-03-12 6:49) • Docker • PHP 8.1
> > > > using custom URL https://sub.comain.com:port/mountpoint (Work Normal)
> > > > Edit docker-compose.override.yml
> > > > services: web: volumes: - /etc/ssl/ssl.crt:/etc/nginx/certs/ssl.crt:ro - /etc/ssl/ssl.key:/etc/nginx/certs/ssl.key:ro
> > > > stations: volumes: - /etc/ssl/ssl.crt:/etc/nginx/certs/ssl.crt:ro - /etc/ssl/ssl.key:/etc/nginx/certs/ssl.key:ro
> > > > I replaced it with this, the result is the same, after checking the SSL it reads only Lets' Encrype, even though I have set it and it should be Sectigo PositiveSSL, I'm confused
> > > @gunsar Take time and read SlvrEagles first post, then read it again and read it once more.
> > > > Then you should remove the section starting with stations and anything "inside" that section (i.e. indented further 
> > > Delete your in docker-compose.override.yml where it starts with "stations". So your docker-compose.override.yml should look like this
> > > ```
> > > services:
> > > web:
> > > volumes:
> > > - /etc/ssl/ssl.crt:/etc/nginx/certs/ssl.crt:ro
> > > - /etc/ssl/ssl.key:/etc/nginx/certs/ssl.key:ro
> > > ```

> > Thank's SSL solved change to Sectigo PositiveSSL
> > but I'm still confused to replace the audio error with a jingle
> > services: stations: volumes: - /var/local/jingle.mp3:/usr/local/share/icecast/web/error.mp3
> > using the command doesn't work
> 
> We offer this natively now, you don't need to use a Docker Compose modification.

very good, more simple, thank you very much

**Comment by gunsar** [comment]
yes I totally agree 👍 I can find out Network Interfaces in real time, success for the azuracat team, thank you very much 👍

> I must say, new version runs smooth. Nice cpu/ram statistics. Performance tuning is a very nice feature👍 Good work! via Mobiel
> […](#)
> Op 14 mrt. 2022 om 12:41 heeft gunsar ***@***.***> het volgende geschreven: ﻿ I tried Rolling Release Powered by AzuraCast • Rolling Release #ef4c438 (2022-03-12 6:49) • Docker • PHP 8.1 using custom URL https://sub.comain.com:port/mountpoint (Work Normal) Edit docker-compose.override.yml services: web: volumes: - /etc/ssl/ssl.crt:/etc/nginx/certs/ssl.crt:ro - /etc/ssl/ssl.key:/etc/nginx/certs/ssl.key:ro stations: volumes: - /etc/ssl/ssl.crt:/etc/nginx/certs/ssl.crt:ro - /etc/ssl/ssl.key:/etc/nginx/certs/ssl.key:ro I replaced it with this, the result is the same, after checking the SSL it reads only Lets' Encrype, even though I have set it and it should be Sectigo PositiveSSL, I'm confused @gunsar Take time and read SlvrEagles first post, then read it again and read it once more. Then you should remove the section starting with stations and anything "inside" that section (i.e. indented further Delete your in docker-compose.override.yml where it starts with "stations". So your docker-compose.override.yml should look like this services: web: volumes: - /etc/ssl/ssl.crt:/etc/nginx/certs/ssl.crt:ro - /etc/ssl/ssl.key:/etc/nginx/certs/ssl.key:ro Thank's SSL solved change to Sectigo PositiveSSL but I'm still confused to replace the audio error with a jingle services: stations: volumes: - /var/local/jingle.mp3:/usr/local/share/icecast/web/error.mp3 using the command doesn't work We offer this natively now, you don't need to use a Docker Compose modification. very good, more simple, thank you very much — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.

**Comment by gunsar** [comment]
yesterday it was safe CPU 15% RAM only 2.7GB
VPS E5-2690 0 2.90GHz 4core 4.00GB
I was surprised that it was suddenly full CPU 100% RAM 3.8GB even though there was only 1 autodj station
Powered by [AzuraCast](https://www.azuracast.com/) • Rolling Release #[b8c2f40](https://github.com/AzuraCast/AzuraCast/commit/b8c2f406ca10058aca84bbb9cc30908b5d7c3e7b) (2022-03-14 0:00) • Docker • PHP 8.1
@SC2Mitch @SlvrEagle23 @Muppet11

**Comment by Muppet11** [comment]
Station is running fine, but suddenly lot of memory usage.
Physical memory 60%
virtual memory: 95 % !!
Performance tuning: balanced
Further no issue’s, but memory consumption is too munch, i think.
4G ram 2G virtual memory

**Comment by gunsar** [comment]
I think what makes CPU RAM high apart from AutoDj is one of them is Reports Statistics and Listener because they are always updated, when there are more listeners the more often they load and that causes the VPS to always be 100%
using 4core 4GB

> Station is running fine, but suddenly lot of memory usage. Physical memory 60% virtual memory: 95 % !! Performance tuning: balanced Further no issue’s, but memory consumption is too munch, i think. 4G ram 2G virtual memory

**Comment by ab5hl** [comment]
How can I use custom ports?

**Comment by ncfernan** [comment]
I just followed the instructions to update to the latest rolling release, modified the composer file and now my stations are not reacheable anymore. Of course I have a full backup, so I can rollback.

My question here is related to the "azuracast_frontend" network that disappeared in the latest update. My previous rolling release had that network and my other containers simply used it, based on the code you posted in your help section showing how to add a wordpress container.

```
networks:
    azuracast_frontend:
        external: true
    backend:
        driver: bridge

```

What is the new name of the former "azuracast_frontend"?

By the way, that wordpress example in your help section became outdated with the last rolling release.

**Comment by Fridgemagnet** [comment]
After carefully reading the update instructions and modifying my override.yml file the update worked like an absolute charm.
Thank you @SlvrEagle23 and the rest of the Azuracast crew involved! 😄

**Comment by iplayradionetworks** [comment]
I am having a problem after the latest update. 

Followed all instructions carefully... I used to have an override file but now its not needed so i removed it. No worries but after update finished i am getting 502 Bad Gateway for the WEB GUI panel.... the radios tho work just fine. 

What can the problem be ? Any ideas please ? I have people that cannot login to their panel. 

Please help.

Jim

**Comment by Fridgemagnet** [comment]
> I am having a problem after the latest update.
> 
> Followed all instructions carefully... I used to have an override file but now its not needed so i removed it. No worries but after update finished i am getting 502 Bad Gateway for the WEB GUI panel.... the radios tho work just fine.
> 
> What can the problem be ? Any ideas please ? I have people that cannot login to their panel.
> 
> Please help.
> 
> Jim

Hi @iplayradionetworks 

did you previously use the override file to change the port for the webgui? 502 Bad Gateway could be the response from your reverse proxy when trying to access a specific backend/proxy host where the port has changed and it cannot be reached.
If you are using portainer you can view the ports used by the new, single azuracast container from the "Containers" tab for your environment. Or you could use the "docker ps" command from the cli.
Hope this helps.

**Comment by iplayradionetworks** [comment]
> > I am having a problem after the latest update.
> > Followed all instructions carefully... I used to have an override file but now its not needed so i removed it. No worries but after update finished i am getting 502 Bad Gateway for the WEB GUI panel.... the radios tho work just fine.
> > What can the problem be ? Any ideas please ? I have people that cannot login to their panel.
> > Please help.
> > Jim
> 
> Hi @iplayradionetworks
> 
> did you previously use the override file to change the port for the webgui? 502 Bad Gateway could be the response from your reverse proxy when trying to access a specific backend/proxy host where the port has changed and it cannot be reached. If you are using portainer you can view the ports used by the new, single azuracast container from the "Containers" tab for your environment. Or you could use the "docker ps" command from the cli. Hope this helps.

Hi @Fridgemagnet 

I was using override file only for radio ports extension (increase the range).  I don't anything else.... i have a desgnined static IP where i have open port 80 and 443 on it... everything was working just fine before i update to 16.0 version. 

From command "docker ps" i get this : 

CONTAINER ID   IMAGE              COMMAND                  CREATED             STATUS          PORTS                                                                                                                                                                                                                                                                                              NAMES
0a91173a61f8   ghcr.io/azuracast/azuracast:stable   "/usr/local/bin/my_i…"   About an hour ago   Up 59 minutes   88.198.10.229:80->80/tcp, 3306/tcp, 0.0.0.0:8000-8442->8000-8442/tcp, :::8000-8442->8000-8442/tcp, 8443/tcp, 0.0.0.0:8444-8879->8444-8879/tcp, :::8444-8879->8444-8879/tcp, 8880/tcp, 0.0.0.0:8881-8887->8881-8887/tcp, :::8881-8887->8881-8887/tcp, 88.198.10.229:443->443/tcp, 8888/tcp, 0.0.0.0:8889-9999->8889-9999/tcp, :::8889-9999->8889-9999/tcp, 88.198.10.229:2121->2022/tcp   azuracast

I don;t get it.... what is wrong ? My setup was fine before. But now suddenly is not ?

Jim

**Comment by Fridgemagnet** [comment]
@iplayradionetworks 
I think it would be best if you open a new issue seeing as it could take more support to solve your problem.

**Comment by iplayradionetworks** [comment]
> @iplayradionetworks 
> I think it would be best if you open a new issue seeing as it could take more support to solve your problem.

But replying here to subject isn't it ok ?

I hope some of the devs can see my reply here ... 

Thank you @Fridgemagnet  for your help 😎

**Comment by vpsinghbaghel** [comment]
I have override.yml file but it's completely different than what you showed.
After removing all other contents from file it's giving lot more errors.

**Comment by blindndangerous** [comment]
Thanks, perfect instructions!  I was just about to open a new issue with the error I was getting and checked pinned issues first. Worked without any problems!

**Comment by ttodua** [comment]
> What is the new name of the former "azuracast_frontend"? ..

Have you ever found the solution/fix for that?

**Comment by ucartz** [comment]
can anyone post the docker-compose.override.yml file here.so I can upload it
