### ISSUE TITLE
unable to switch to stable from old rolling release

### ISSUE THREAD

**Issue by webafrancois** [AzuraCast/AzuraCast#5199]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #2eb3d4b (2020-11-13 20:51)

### What happened?

I have an old rolling release, which running good.
I want to switch to a recent stable version (but rolling release don't upgrade too).

In /var/azuracast/www, i run : 
```
# git reset --hard

# git checkout stable
# git pull
```

My git log says : 
```
commit 320c4410b93b41ab69da39f971658a0397ef9fbf (HEAD -> stable, tag: 0.15.2, origin/stable)
Merge: b75efc989 622c468bc
Author: Buster "Silver Eagle" Neece <buster@busterneece.com>
Date:   Sun Feb 20 22:28:24 2022 -0600
    Merge commit '622c468bc95fc25f44c7b7890b1b7f29401fc78c' into stable
```
which is the last commit in stable branch
On my Ubuntu 20.04, I should install php7.4-maxminddb

Then, i run sudo ./update.sh and the upgrade don't apply with this error : 
```
TASK [azuracast-setup : Run AzuraCast Setup (Install Mode)] **********************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/console azuracast:setup", "delta": "0:00:00.075328", "end": "2022-03-14 02:03:11.628248", "msg": "non-zero return code", "rc": 255, "start": "2022-03-14 02:03:11.552920", "stderr": "PHP Parse error:  syntax error, unexpected ':', expecting ')' in /var/azuracast/www/src/AppFactory.php on line 76", "stderr_lines": ["PHP Parse error:  syntax error, unexpected ':', expecting ')' in /var/azuracast/www/src/AppFactory.php on line 76"], "stdout": "\nParse error: syntax error, unexpected ':', expecting ')' in /var/azuracast/www/src/AppFactory.php on line 76", "stdout_lines": ["", "Parse error: syntax error, unexpected ':', expecting ')' in /var/azuracast/www/src/AppFactory.php on line 76"]}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=23   changed=16   unreachable=0    failed=1    skipped=59   rescued=0    ignored=0   
```
With an `./update --full`,  the liquidsoap dependencies don't exist :  
```
TASK [azuracast-radio : Install Liquidsoap] **************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failure downloading https://github.com/savonet/liquidsoap/releases/download/v2.0.3/liquidsoap_2.0.3-ubuntu-focal-1_amd64.deb, HTTP Error 404: Not Found"}
```
Because https://github.com/savonet/liquidsoap/releases/ show the the lib is available on 2.0.3-ubuntu-focal-2-xxx

I download and install manually the good liquidsoap version and re-run the update.sh --full, then same error : 
```
TASK [azuracast-radio : Install Liquidsoap] **************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failure downloading https://github.com/savonet/liquidsoap/releases/download/v2.0.3/liquidsoap_2.0.3-ubuntu-focal-1_amd64.deb, HTTP Error 404: Not Found"}
```
Then I try to re-run ./update.sh and, same error : 
```
TASK [azuracast-setup : Run AzuraCast Setup (Install Mode)] *****************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/console azuracast:setup", "delta": "0:00:00.061705", "end": "2022-03-14 02:27:25.323606", "msg": "non-zero return code", "rc": 255, "start": "2022-03-14 02:27:25.261901", "stderr": "PHP Parse error:  syntax error, unexpected ':', expecting ')' in /var/azuracast/www/src/AppFactory.php on line 76", "stderr_lines": ["PHP Parse error:  syntax error, unexpected ':', expecting ')' in /var/azuracast/www/src/AppFactory.php on line 76"], "stdout": "\nParse error: syntax error, unexpected ':', expecting ')' in /var/azuracast/www/src/AppFactory.php on line 76", "stdout_lines": ["", "Parse error: syntax error, unexpected ':', expecting ')' in /var/azuracast/www/src/AppFactory.php on line 76"]}
```

How can I upgrade to new stable (or rolling) release ?

Thanks.

**Comment by SlvrEagle23** [comment]
@webafrancois Hello! Unfortunately, the version of Liquidsoap that our latest stable release was using on Ansible was removed in favor of a newer version; future stable releases will have the correct URL, but in the meantime, you can upgrade to the latest rolling release by following those same channel-switching steps, but with a different branch name:

```
git reset --hard
git checkout main
git pull
sudo ./update.sh --full
```

**Comment by webafrancois** [comment]
ok, I do a full upgrade in my ubuntu 20.04, and pull from the rolling release like you mention it.
NS : some problems was resolved by stopping php7.4-fpm.service.
But finally I've got another error in the mysql upgrade.
I try to connect to my database withthe credentials in env.in (in /var/azuracast/www)
But the script didn't success : 
`
TASK [azuracast-setup : Run AzuraCast Setup (Install Mode)] ************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/console azuracast:setup", "delta": "0:00:00.323034", "end": "2022-03-19 16:15:44.828788", "msg": "non-zero return code", "rc": 1, "start": "2022-03-19 16:15:44.505754", "stderr": "[2022-03-19T16:15:44.815676+00:00] AzuraCast.ERROR: Doctrine\\DBAL\\Exception\\ConnectionException: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 while running console command `azuracast:setup` {\"exception\":\"[object] (Doctrine\\\\DBAL\\\\Exception\\\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\\n[previous exception] [object] (Doctrine\\\\DBAL\\\\Driver\\\\PDO\\\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:40)\"} []\n[2022-03-19T16:15:44.816964+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 1. [] []\n\nIn AbstractMySQLDriver.php line 112:\n                                                                               \n  An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for u  \n  ser 'azuracast'@'localhost' (using password: YES)                            \n                                                                               \n\nIn Exception.php line 18:\n                                                                               \n  SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (usin  \n  g password: YES)                                                             \n                                                                               \n\nIn PDOConnection.php line 40:\n                                                                               \n  SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (usin  \n  g password: YES)                                                             \n                                                                               \n\nazuracast:setup [--update] [--load-fixtures] [--release]", "stderr_lines": ["[2022-03-19T16:15:44.815676+00:00] AzuraCast.ERROR: Doctrine\\DBAL\\Exception\\ConnectionException: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 while running console command `azuracast:setup` {\"exception\":\"[object] (Doctrine\\\\DBAL\\\\Exception\\\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\\n[previous exception] [object] (Doctrine\\\\DBAL\\\\Driver\\\\PDO\\\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:40)\"} []", "[2022-03-19T16:15:44.816964+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 1. [] []", "", "In AbstractMySQLDriver.php line 112:", "                                                                               ", "  An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for u  ", "  ser 'azuracast'@'localhost' (using password: YES)                            ", "                                                                               ", "", "In Exception.php line 18:", "                                                                               ", "  SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (usin  ", "  g password: YES)                                                             ", "                                                                               ", "", "In PDOConnection.php line 40:", "                                                                               ", "  SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (usin  ", "  g password: YES)                                                             ", "                                                                               ", "", "azuracast:setup [--update] [--load-fixtures] [--release]"], "stdout": "\nAzuraCast Setup\n===============\n\nWelcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...\n\nInitialize AzuraCast\n====================\n\nInitializing essential settings...\n * Environment: Production\n * Installation Method: Ansible\n\n\nRunning Database Migrations\n---------------------------", "stdout_lines": ["", "AzuraCast Setup", "===============", "", "Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...", "", "Initialize AzuraCast", "====================", "", "Initializing essential settings...", " * Environment: Production", " * Installation Method: Ansible", "", "", "Running Database Migrations", "---------------------------"]}

`

Thnaks a lot. It's very kind of you to spend time to help us.

I try to reboot, but same result.

My mariadb.service says that the access is denied for user azuracast (but my previous install works fine)
```
Mar 19 16:28:01 webradios mariadbd[16411]: 2022-03-19 16:28:01 56 [Warning] Access denied for user 'azuracast'@'localhost' (using password: YES)
Mar 19 16:28:13 webradios mariadbd[16411]: 2022-03-19 16:28:13 57 [Warning] Access denied for user 'azuracast'@'localhost' (using password: YES)
Mar 19 16:28:13 webradios mariadbd[16411]: 2022-03-19 16:28:13 58 [Warning] Access denied for user 'azuracast'@'localhost' (using password: YES)
Mar 19 16:28:43 webradios mariadbd[16411]: 2022-03-19 16:28:43 59 [Warning] Access denied for user 'azuracast'@'localhost' (using password: YES)
Mar 19 16:28:43 webradios mariadbd[16411]: 2022-03-19 16:28:43 60 [Warning] Access denied for user 'azuracast'@'localhost' (using password: YES)
```

**Comment by webafrancois** [comment]
When I run : 
```
sudo -u azuracast mysql -uazuracast -p -h localhost
```
with the env.ini password, I can use mysql.

And in root too.

When I run manually : 
`sudo -u azuracast php /var/azuracast/www/bin/console azuracast:setup`

same error : 
```
Running Database Migrations
---------------------------

[2022-03-19T16:45:45.070040+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\ConnectionException: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 while running console command `azuracast:setup` {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:40)"} []
[2022-03-19T16:45:45.071020+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 1. [] []

In AbstractMySQLDriver.php line 112:
                                                                                                                                
  An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES)  
                                                                                                                                

In Exception.php line 18:
                                                                                               
  SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES)  
                                                                                               

In PDOConnection.php line 40:
                                                                                               
  SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES)  
                                                                                               

azuracast:setup [--update] [--load-fixtures] [--release]

```

**Comment by webafrancois** [comment]
I compare a fresh install and my update version and see that the env.ini are differents :
- in my old release, the env.ini contain : 
```
;
; AzuraCast Environment Settings
;
; This file is automatically generated by AzuraCast.
;

[configuration]
application_env = production
db_username = azuracast
db_password = mypassword

```
And in the a fresh new stable install :  
```

;
; AzuraCast Environment Settings
;
; This file is automatically generated by AzuraCast.
;

[configuration]
application_env = production
MYSQL_HOST = localhost
MYSQL_PORT = 3306
MYSQL_USER = azuracast
MYSQL_DB = azuracast
MYSQL_PASSWORD = myotherpassowrd
```

So variable names have changing. And Ansible have not see the difference.

So, I rename whith good name, but the update.sh script can't apply a change on a SQL table :
```
An exception occurred while executing 'ALTER TABLE users RENAME COLUMN uid TO id':                                                                                                                                                                                                                                                      
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for   
  the right syntax to use near 'COLUMN uid TO id' at line 1 
```
Maybe because uid is a primary key ?
My mariadb is v10.

But on my fresh stable version (or in rolling release #5c6d280 (2022-03-25 21:28) ), it works without sound :-(

**Comment by SlvrEagle23** [comment]
@webafrancois Migrating backwards to earlier versions isn't supported in general because of the database migrations involved, and the fact that the older codebase doesn't know what changes were made _since_ it was released, so it can't migrate backwards from them correctly.

**Comment by webafrancois** [comment]
I don't update backwards but forwards. I migrate from a Rolling Release #2eb3d4b (2020-11-13 20:51) to a AzuraCast 0.15.2 stable version of 2022. But that's okay, I'll restart a stable installation from the beginning.
Thanks for the help anyway. 
I just wanted to point out that the variable names in env.ini have changed.
