### ISSUE TITLE
S3 storage wont work

### ISSUE THREAD

**Issue by julianborghuis** [AzuraCast/AzuraCast#5201]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

v0.15.2 Stable

### What happened?

Hello,

I have now s3 storage working. But how can i attache folders or music at an playlist? In the file browser online theres nothing, uploading in the filemanager works, but cant see anything in the folder
if i upload something the storage above goes further, and also the file is uploaded to the s3, i checked that, but still cant see the files..
![image](https://user-images.githubusercontent.com/40545968/158331208-a35a5ac0-5f0c-4fc6-8569-c37dedc633ef.png)

### Relevant log output

```shell
azuracast_web  | 2022/03/15 07:44:20 [warn] 343#343: *87 a client request body i                                                                                                                     s buffered to a temporary file /tmp/app_nginx_client/3/0/0000000003, client: 37.                                                                                                                     120.192.24, server: localhost, request: "POST /api/station/9/files/upload HTTP/2                                                                                                                     .0", host: "listen.cmfm.nl", referrer: "https://listen.cmfm.nl/station/9/files"
azuracast_web  | 2022/03/15 07:44:23 [warn] 343#343: *87 a client request body i                                                                                                                     s buffered to a temporary file /tmp/app_nginx_client/4/0/0000000004, client: 37.                                                                                                                     120.192.24, server: localhost, request: "POST /api/station/9/files/upload HTTP/2                                                                                                                     .0", host: "listen.cmfm.nl", referrer: "https://listen.cmfm.nl/station/9/files"
azuracast_web  | 2022/03/15 07:44:23 [warn] 343#343: *87 a client request body i                                                                                                                     s buffered to a temporary file /tmp/app_nginx_client/5/0/0000000005, client: 37.                                                                                                                     120.192.24, server: localhost, request: "POST /api/station/9/files/upload HTTP/2                                                                                                                     .0", host: "listen.cmfm.nl", referrer: "https://listen.cmfm.nl/station/9/files"
azuracast_web  | 2022/03/15 07:44:23 [warn] 343#343: *87 a client request body i                                                                                                                     s buffered to a temporary file /tmp/app_nginx_client/6/0/0000000006, client: 37.                                                                                                                     120.192.24, server: localhost, request: "POST /api/station/9/files/upload HTTP/2                                                                                                                     .0", host: "listen.cmfm.nl", referrer: "https://listen.cmfm.nl/station/9/files"
azuracast_web  | 2022/03/15 07:44:23 [warn] 343#343: *87 a client request body i                                                                                                                     s buffered to a temporary file /tmp/app_nginx_client/7/0/0000000007, client: 37.                                                                                                                     120.192.24, server: localhost, request: "POST /api/station/9/files/upload HTTP/2                                                                                                                     .0", host: "listen.cmfm.nl", referrer: "https://listen.cmfm.nl/station/9/files"
azuracast_web  | [2022-03-15T07:44:33.125942+00:00] AzuraCast.ERROR: No valid pl                                                                                                                     aylists detected. Skipping AutoDJ calculations. [] {"station":{"id":9,"name":"te
```

**Comment by leakim69** [comment]
Hello,

I got confused about this too, but here is how you do it: 

1. Go to **Manage Stations** / **System Maintenance** / **Storage Locations** and add your S3-drive, see here: https://d.pr/free/i/aEbx7x
2. Go to Manage Stations, see here: https://d.pr/free/i/dAoSL2
3. If connected correctly in step 1, your S3-drive should be selectable here: https://d.pr/free/i/QzsWsA

Now you should see your S3-drive in the **Music Files**-section of your radio station settings.

**Comment by julianborghuis** [comment]
I have used here contabo s3 storage, wich uses an folder and not an subdomain,

so its for my case : eu2.contabostorage.com/bucketname to access the s3 storage

But if i tried an linode s3 storage it works fine wich uses subdomain,

again: files are transfered and i can see the files in the s3 storage but azura doesnt show them

**Comment by kofyebs** [comment]
> Hello,
> 
> I got confused about this too, but here is how you do it: 
> 
> 1. Go to **Manage Stations** / **System Maintenance** / **Storage Locations** and add your S3-drive, see here: https://d.pr/free/i/aEbx7x
> 2. Go to Manage Stations, see here: https://d.pr/free/i/dAoSL2
> 3. If connected correctly in step 1, your S3-drive should be selectable here: https://d.pr/free/i/QzsWsA
> 
> Now you should see your S3-drive in the **Music Files**-section of your radio station settings. 
> 

My Azuracast is connected to my S3 and i can see my files in Azuracast, I've added songs to playlist but it's not playing.

**Comment by SlvrEagle23** [comment]
@kofyebs We found and fixed a major issue with how our AutoDJ interacts with AzuraCast in the latest Rolling Release version; the fix for this was just released a few minutes ago, so if you don't mind updating and trying the new version out to see if it resolves your issues, it would be much appreciated! The latest version also improves how we log errors related to the AutoDJ, so even if there are still errors, we will have more information about them moving forward. Sorry for the inconvenience and thank you for your patience.

**Comment by rbarbier1967** [comment]
Well though you say solved I am having the same issue and it seems it's all Contabo lol. Maybe the type of S3 compatible they are using. they use [Ceph](https://ceph.com/) I was able to play around with it (use the usc1 which was the subdomain on it and put it in the bucket box and put the bucket in prefiix to get the right url etc but no files. ) still doing the subdomain instead of the folder on it as kofyebs said above.
