### ISSUE TITLE
High cpu consumption, radios turning off.

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#5202]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #5303eb9 (2022-03-15 11:58) • Docker • PHP 8.1

### What happened?

I was using azuracast normally until I updated to this latest version. From there the processing load is at 90% most of the time and the radios work for a while and then stop, and other radios don't even work.

### Relevant log output

```shell
I was using azuracast normally until I updated to this latest version. From there the processing load is at 90% most of the time and the radios work for a while and then stop, and other radios don't even work.
```

**Comment by Marcioghiraldelli** [comment]
some radios do not play, so I only managed to play by checking Manual AutoDJ Mode, if left unchecked, being managed by azuracast mode, there is a radio that does not play.

**Comment by Marcioghiraldelli** [comment]
I realize that high consumption is involved in managing the playlist through azuracast, because if I turn off this management and leave it through liquidsoap, the cpu load drops absurdly and the radio starts playing again.

**Comment by AaronUnmuted** [comment]
Hi @Marcioghiraldelli - update to the latest rolling release (there's only one commit above your current installation, but it's quite a vital one which will more than likely be of help).

**Comment by gunsar** [comment]
> ### Installation Method
> Docker Installation
> 
> ### AzuraCast Release Channel
> Rolling Release Channel
> 
> ### Current AzuraCast Version
> Rolling Release #5303eb9 (2022-03-15 11:58) • Docker • PHP 8.1
> 
> ### What happened?
> I was using azuracast normally until I updated to this latest version. From there the processing load is at 90% most of the time and the radios work for a while and then stop, and other radios don't even work.
> 
> ### Relevant log output
> ```shell
> I was using azuracast normally until I updated to this latest version. From there the processing load is at 90% most of the time and the radios work for a while and then stop, and other radios don't even work.
> ```

I'm having the same issue

https://github.com/AzuraCast/AzuraCast/issues/5191#issuecomment-1067717085

**Comment by stardevelop** [comment]
Same issue for me.

**Comment by radiobellissima** [comment]
Same issue for me.

**Comment by SlvrEagle23** [comment]
@stardevelop @radiobellissima It is not useful to us to just post "same issue for me". If you have any log entries you can provide via the Log Viewer utility (or, in the latest rolling release, the "Help" section), particularly from Liquidsoap, that would be helpful as we work to diagnose and fix issues. It's also important to mention which version you're on, including which _specific_ version you're on (i.e. Rolling Release, 2022-03-19).

**Comment by radiobellissima** [comment]
Hi, unfortunately having it in production I immediately had to go back to the previous one I had all 20 channels stopped. I got stuck with the rolling relase not being able to move to a stable anymore.

**Comment by stardevelop** [comment]
Rolling Release #[b25fbd9]

Liquidsoap Log:
2022/03/23 01:53:59 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/03/23 01:54:00 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 1).
[mp3float @ 0x7f5734087900] Could not update timestamps for skipped samples.
[mp3float @ 0x7f5734087900] Could not update timestamps for discarded samples.
2022/03/23 01:54:27 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/03/23 01:54:27 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 1).
[mp3float @ 0x7f5734087900] Could not update timestamps for skipped samples.
[mp3float @ 0x7f5734087900] Could not update timestamps for discarded samples.
2022/03/23 01:54:54 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/03/23 01:54:55 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 1).
[mp3float @ 0x7f573407a740] Could not update timestamps for skipped samples.
2022/03/23 01:56:51 [lang:3] API feedback - Response: 
2022/03/23 01:56:53 [lang:3] API feedback - Response: 
2022/03/23 01:56:55 [lang:3] API nextsong - Response: 
2022/03/23 01:59:54 [lang:3] API nextsong - Response: 
2022/03/23 01:59:56 [lang:3] API nextsong - Response: 
2022/03/23 01:59:58 [lang:3] API nextsong - Response: 
2022/03/23 02:00:00 [lang:3] API nextsong - Response: 
2022/03/23 02:00:02 [lang:3] API nextsong - Response: 
2022/03/23 02:00:04 [lang:3] API nextsong - Response: 
2022/03/23 02:00:06 [lang:3] API nextsong - Response: 
2022/03/23 02:00:08 [lang:3] API nextsong - Response: 
2022/03/23 02:00:10 [lang:3] API nextsong - Response: 
2022/03/23 02:00:12 [lang:3] API nextsong - Response: 
2022/03/23 02:00:14 [lang:3] API nextsong - Response: 
2022/03/23 02:00:16 [lang:3] API nextsong - Response: 
2022/03/23 02:00:18 [lang:3] API nextsong - Response: 
2022/03/23 02:00:20 [lang:3] API nextsong - Response: 
2022/03/23 02:00:22 [lang:3] API nextsong - Response: 
2022/03/23 02:00:24 [lang:3] API nextsong - Response: 
2022/03/23 02:00:26 [lang:3] API nextsong - Response: 
2022/03/23 02:00:28 [lang:3] API nextsong - Response: 
2022/03/23 02:00:30 [lang:3] API nextsong - Response: 
2022/03/23 02:33:43 [lang:3] API nextsong - Response: annotate:title="Raining Again",duration="48.00",song_id="602c24d920fadae2cd89cd2eaf82cfd2",media_id="3106",liq_amplify="0.00dB",playlist_id="1":/var/azuracast/stations/music/media/music/music1.mp3
[mp3 @ 0x7f572003ba00] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f5720062780] Estimating duration from bitrate, this may be inaccurate

**Comment by SlvrEagle23** [comment]
We found and fixed a major issue with how our AutoDJ interacts with AzuraCast in the latest Rolling Release version; the fix for this was just released a few minutes ago, so if you don't mind updating and trying the new version out to see if it resolves your issues, it would be much appreciated! The latest version also improves how we log errors related to the AutoDJ, so even if there are still errors, we will have more information about them moving forward. Sorry for the inconvenience and thank you for your patience.

**Comment by gunsar** [comment]
@SlvrEagle23 
I finally reinstalled and tried the rolling release version
Powered by [AzuraCast](https://www.azuracast.com/) • Rolling Release #[653e6d4](https://github.com/AzuraCast/AzuraCast/commit/653e6d4a3d46930cf083680aabb3fab8c6daa491) (2022-04-08 6:45) • Docker • PHP 8.1
from monitoring CPU RAM is still safe
I'll let you know if there's another problem with the CPU and RAM

**Comment by radiobellissima** [comment]
@SlvrEagle23
Rolling Release #[5d52ff4]
Now CPU RAM is ok.
I think it can be considered a solved problem.
