### ISSUE TITLE
Playlist - error.mp3 not working anymore

### ISSUE THREAD

**Issue by CyberMixRo** [AzuraCast/AzuraCast#5204]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #2bfc1e9 (2022-03-16 4:57)

### What happened?

error.mp3 file is not working anymore on this release for new radio station created with AutoDJ eanbled but without any playlist created. Before playing error.mp3 in loop

**Error on AutoDJ start:** 

BadNameException at /var/azuracast/www/src/Radio/AbstractAdapter.php L251: Liquidsoap is not recognized as a service.
It may not be registered with Supervisor yet. Restarting broadcasting may help.

Error on Server start:

BadNameException at /var/azuracast/www/src/Radio/AbstractAdapter.php L251: Shoutcast is not recognized as a service.
It may not be registered with Supervisor yet. Restarting broadcasting may help.

**Comment by SlvrEagle23** [comment]
@CyberMixRo This is intentional currently; if a station has no music assigned to a playlist and uses the AutoDJ, it simply won't start. This is to significantly save on resources for large operators who have several inactive stations running.

**Comment by CyberMixRo** [comment]
> @CyberMixRo This is intentional currently; if a station has no music assigned to a playlist and uses the AutoDJ, it simply won't start. This is to significantly save on resources for large operators who have several inactive stations running.

I understand, so was removed this option ... better if hide that error message on server and autodj "BadNameException at /var/azuracast/www/src/Radio/AbstractAdapter.php L251: ....." and will be replaced with message as Start broadcasting and have no playlist ;)

**Comment by SlvrEagle23** [comment]
@CyberMixRo I believe as of the latest Rolling Release version, that is exactly what should be happening when you restart broadcasting or click the "Start Station" button. Controlling the individual services may still produce that error, though, which I'll look into fixing.

**Comment by simpsss** [comment]
> @CyberMixRo This is intentional currently; if a station has no music assigned to a playlist and uses the AutoDJ, it simply won't start. This is to significantly save on resources for large operators who have several inactive stations running.

if someone has idle stations, the owner needs to go and turn it off manually. I need to start the new stations via API and now it doesn't work anymore. Any solution?

**Comment by simpsss** [comment]
And i have a station that I use only with a remote playlist.

![image](https://user-images.githubusercontent.com/51731449/160054665-9e73b4cf-ca46-4eaa-a5b4-d384d8a53cdd.png)

**Comment by SlvrEagle23** [comment]
@simpsss This error has been fixed in newer Rolling Release versions; external playlists will now allow a station to start up as normal.
