### ISSUE TITLE
Command 'docker-installer' not found

### ISSUE THREAD

**Issue by coldrust** [AzuraCast/AzuraCast#5206]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

> 
> Creating azuracast_installer_installer_run ... done
>   Command "docker_installer" is not defined.
> ERROR: 1
> 

After this error everything goes fine but I am unable to visit the http page after installation. It says it has been installed successfully but the page doesn't load when I try to do so in the browser

### Relevant log output

```shell
[PASS] Operating System: Linux
[PASS] Architecture: x86_64
[PASS] Command Present: curl
[PASS] Command Present: awk
[PASS] User Permissions
[PASS] Installation Directory
[PASS] All requirements met!
Docker is already installed! Continuing...
Docker Compose is already installed. Continuing...
Prefer stable release versions of AzuraCast? [y/N] y
Pulling installer ... done
Creating azuracast_installer_installer_run ... done


  Command "docker_installer" is not defined.


ERROR: 1
Pulling mariadb  ... done
Pulling redis    ... done
Pulling stations ... done
Pulling web      ... done
Creating network "azuracast_backend" with driver "bridge"
```

**Comment by gunsar** [comment]
I experienced the same thing, tried to reinstall and an error occurred. want the stable or rolling version, it's the same error.

**Command "docker_installer" is not defined.**

_and can't enter the panel_

> ### Installation Method
> Docker Installation
> 
> ### AzuraCast Release Channel
> Stable Channel
> 
> ### Current AzuraCast Version
> _No response_
> 
> ### What happened?
> > Creating azuracast_installer_installer_run ... done
> > Command "docker_installer" is not defined.
> > ERROR: 1
> 
> After this error everything goes fine but I am unable to visit the http page after installation. It says it has been installed successfully but the page doesn't load when I try to do so in the browser
> 
> ### Relevant log output
> ```shell
> [PASS] Operating System: Linux
> [PASS] Architecture: x86_64
> [PASS] Command Present: curl
> [PASS] Command Present: awk
> [PASS] User Permissions
> [PASS] Installation Directory
> [PASS] All requirements met!
> Docker is already installed! Continuing...
> Docker Compose is already installed. Continuing...
> Prefer stable release versions of AzuraCast? [y/N] y
> Pulling installer ... done
> Creating azuracast_installer_installer_run ... done
> 
> 
>   Command "docker_installer" is not defined.
> 
> 
> ERROR: 1
> Pulling mariadb  ... done
> Pulling redis    ... done
> Pulling stations ... done
> Pulling web      ... done
> Creating network "azuracast_backend" with driver "bridge"
> ```

**Comment by SlvrEagle23** [comment]
@gunsar I'm publishing an update that should fix this issue by making sure the installer commands are the same for both the stable and rolling release versions of the software.

Basically, what's happening is that, during installation, you're pulling the Rolling Release version of the installer. 

If you run into this issue in the future for any reason, you could likely work around it by running:

```bash
./docker.sh setup-release
./docker.sh update-self
```

**Comment by gunsar** [comment]
maybe like that, even though I have reinstalled the ubuntu VPS several times. I will try this way. thank you

> @gunsar I'm publishing an update that should fix this issue by making sure the installer commands are the same for both the stable and rolling release versions of the software.
> ```shell
> ./docker.sh setup-release
> ./docker.sh update-self
> ```
