### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#5208]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#ea64d9f

### What happened?

During upgrade to latest version, I get this error:

 Transport error occurred: cURL error 7: Failed to connect to 127.0.0.1 port 9001: Connection refused (see
         https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:9001/RPC2

and the station goes offline.

**Comment by YosefAdPro** [comment]
same error:
![image](https://user-images.githubusercontent.com/11810187/159139920-813d4b0e-cc73-4f18-9a08-d5f961ce616a.png)

**Comment by CyberMixRo** [comment]
> same error: ![image](https://user-images.githubusercontent.com/11810187/159139920-813d4b0e-cc73-4f18-9a08-d5f961ce616a.png)

I have the same issue and station are show on main page as are offline. How can we fix this issue?

**Comment by CyberMixRo** [comment]
Restarting all radio stations...
--------------------------------

 0/3 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
 [ERROR] Radio Flo (ImS #177 - AutoDJ)

         Transport error occurred: cURL error 7: Failed to connect to 127.0.0.1 port 9001: Connection refused (see
         https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:9001/RPC2


 1/3 [▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░]  33%
 [ERROR] Radio Flo Dance - Live

         Transport error occurred: cURL error 7: Failed to connect to 127.0.0.1 port 9001: Connection refused (see
         https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:9001/RPC2



 [ERROR] Radio Flo IceCast

         Transport error occurred: cURL error 7: Failed to connect to 127.0.0.1 port 9001: Connection refused (see
         https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:9001/RPC2


 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


 [OK] AzuraCast is now updated to the latest version!

**Comment by CyberMixRo** [comment]
Ok, i found how to fix for the moment, missing on docker " libcurl4-openssl-dev", have to install that on docker and stations are not looking as offline for the moment after i restarted the docker...

If anyone have this issue here is how i did:

_docker exec -t -i azuracast /bin/bash
apt-get update
apt-get install libcurl4-openssl-dev_
