### ISSUE TITLE
Public website not refreshing tracks and sending error messages in JS log

### ISSUE THREAD

**Issue by taiBsu** [AzuraCast/AzuraCast#5219]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.15.2 stable

### What happened?

Since the latest update, I don't get a frontend update of the next track after one track has finished:
![image](https://user-images.githubusercontent.com/8024663/159548349-8e10874d-7ff7-49d7-9cb6-55df6849e249.png)

Additionally, I can see the following error messages in my browser JS console:
![image](https://user-images.githubusercontent.com/8024663/159547542-f490acae-6dfd-4edf-b728-f4cd3d336b19.png)

I'm running AzuraCast in a docker using a reverse proxy which I haven't set up yet for the new version. Is this a possible cause for the issue?

**EDIT:** I just followed the [Multi-Site Docker Installation Guide](https://docs.azuracast.com/en/administration/docker/multi-site-installation) (AzuraCast Multi-Site Feature) which unfortunately didn't help me, even the dashboard warning with the wrong base-URL persists.

### Relevant log output

```shell
web_1       | 2022/03/22 18:12:52 [error] 898296#898296: *1696919 open() "/usr/share/nginx/html/pub/*********" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "POST /pub/********* HTTP/1.1", host: "localhost:9010"
```

**Comment by SlvrEagle23** [comment]
@taiBsu I believe we fixed this in the Rolling Release version...there were specific limitations on station short codes (special characters, unicode characters, etc.) that we've recently removed and fixed.

**Comment by taiBsu** [comment]
@SlvrEagle23 looks good, I updated Azuracast and it seems that the errors are gone, also tracks are refreshing. thanks!
