### ISSUE TITLE
Stream Offline

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#5221]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#b25fbd9 (2022-03-22 7:52)

### What happened?

The stream goes offline (Stream Offline) after a few hours and I must Restart Broadcasting to get it back online.

### Relevant log output

```shell
**Liquidsoap Log:**
2022/03/23 03:38:11 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/03/23 03:38:12 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 1).
[mp3float @ 0x7f64a0068c00] Could not update timestamps for skipped samples.
[mp3float @ 0x7f64a0068c00] Could not update timestamps for discarded samples.
2022/03/23 03:38:39 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3float @ 0x7f64a0074200] Could not update timestamps for skipped samples.
2022/03/23 03:38:39 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 1).
[mp3float @ 0x7f64a0074200] Could not update timestamps for discarded samples.
2022/03/23 03:39:06 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/03/23 03:39:07 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 1).
[mp3float @ 0x7f64a0185800] Could not update timestamps for skipped samples.
[mp3float @ 0x7f64a0185800] Could not update timestamps for discarded samples.
2022/03/23 03:39:33 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3float @ 0x7f64a0185800] Could not update timestamps for skipped samples.
2022/03/23 03:39:34 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 1).
[mp3float @ 0x7f64a0185800] Could not update timestamps for discarded samples.
2022/03/23 03:40:01 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3float @ 0x7f64a0185800] Could not update timestamps for skipped samples.
2022/03/23 03:40:01 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 1).
[mp3float @ 0x7f64a0185800] Could not update timestamps for discarded samples.
2022/03/23 03:40:28 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/03/23 03:40:29 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 1).
[mp3float @ 0x7f64a005b400] Could not update timestamps for skipped samples.
2022/03/23 04:14:30 [lang:3] API feedback - Response: 
2022/03/23 04:14:30 [lang:3] API feedback - Response: 
2022/03/23 04:14:32 [lang:3] API nextsong - Response: 
2022/03/23 04:14:34 [lang:3] API nextsong - Response: 
2022/03/23 04:14:36 [lang:3] API nextsong - Response: 
2022/03/23 04:14:38 [lang:3] API nextsong - Response: 
2022/03/23 04:14:40 [lang:3] API nextsong - Response: 
2022/03/23 04:14:42 [lang:3] API nextsong - Response: 
2022/03/23 04:14:44 [lang:3] API nextsong - Response: 
2022/03/23 04:14:47 [lang:3] API nextsong - Response: 
2022/03/23 04:14:49 [lang:3] API nextsong - Response: 
2022/03/23 04:14:51 [lang:3] API nextsong - Response: 
2022/03/23 04:14:53 [lang:3] API nextsong - Response: 
2022/03/23 04:14:55 [lang:3] API nextsong - Response: 
2022/03/23 04:14:57 [lang:3] API nextsong - Response: 
2022/03/23 04:14:59 [lang:3] API nextsong - Response: 
2022/03/23 04:15:01 [lang:3] API nextsong - Response: 
2022/03/23 04:15:03 [lang:3] API nextsong - Response: 
2022/03/23 04:15:05 [lang:3] API nextsong - Response: 
2022/03/23 04:15:07 [lang:3] API nextsong - Response: 
2022/03/23 04:15:09 [lang:3] API nextsong - Response: 
2022/03/23 04:15:11 [lang:3] API nextsong - Response: 
2022/03/23 04:15:13 [lang:3] API nextsong - Response: 
2022/03/23 04:15:15 [lang:3] API nextsong - Response: 
2022/03/23 04:15:17 [lang:3] API nextsong - Response: 
2022/03/23 04:15:19 [lang:3] API nextsong - Response: 
2022/03/23 04:15:21 [lang:3] API nextsong - Response: 
2022/03/23 04:15:23 [lang:3] API nextsong - Response: 
2022/03/23 04:15:25 [lang:3] API nextsong - Response: 
2022/03/23 04:15:27 [lang:3] API nextsong - Response: 
2022/03/23 04:15:29 [lang:3] API nextsong - Response: 
2022/03/23 04:15:31 [lang:3] API nextsong - Response: 
2022/03/23 04:15:33 [lang:3] API nextsong - Response: 
2022/03/23 04:15:35 [lang:3] API nextsong - Response: 
2022/03/23 04:15:47 [lang:3] API nextsong - Response: 
2022/03/23 04:15:59 [lang:3] API nextsong - Response: 
2022/03/23 04:16:11 [lang:3] API nextsong - Response: 
2022/03/23 04:16:23 [lang:3] API nextsong - Response: 
2022/03/23 04:16:35 [lang:3] API nextsong - Response: 
2022/03/23 04:16:47 [lang:3] API nextsong - Response: 
2022/03/23 04:16:59 [lang:3] API nextsong - Response: 
2022/03/23 04:17:11 [lang:3] API nextsong - Response: 
2022/03/23 04:17:23 [lang:3] API nextsong - Response: 
2022/03/23 04:17:35 [lang:3] API nextsong - Response: 
2022/03/23 04:17:47 [lang:3] API nextsong - Response: 
2022/03/23 04:17:59 [lang:3] API nextsong - Response: 
2022/03/23 04:18:11 [lang:3] API nextsong - Response: 
2022/03/23 04:18:23 [lang:3] API nextsong - Response: 
2022/03/23 04:18:35 [lang:3] API nextsong - Response: 
2022/03/23 04:18:47 [lang:3] API nextsong - Response: 
2022/03/23 04:18:59 [lang:3] API nextsong - Response: 
2022/03/23 04:19:11 [lang:3] API nextsong - Response: 
2022/03/23 04:19:23 [lang:3] API nextsong - Response: 
2022/03/23 04:19:35 [lang:3] API nextsong - Response: 
2022/03/23 04:19:47 [lang:3] API nextsong - Response: 
2022/03/23 04:19:59 [lang:3] API nextsong - Response: 
2022/03/23 04:20:11 [lang:3] API nextsong - Response: 
2022/03/23 04:20:23 [lang:3] API nextsong - Response: 
2022/03/23 04:20:35 [lang:3] API nextsong - Response: 
2022/03/23 04:20:47 [lang:3] API nextsong - Response: 
2022/03/23 04:20:59 [lang:3] API nextsong - Response: 
2022/03/23 04:21:11 [lang:3] API nextsong - Response: 
2022/03/23 04:21:23 [lang:3] API nextsong - Response: 
2022/03/23 04:21:35 [lang:3] API nextsong - Response: 
2022/03/23 04:21:47 [lang:3] API nextsong - Response: 
2022/03/23 04:21:59 [lang:3] API nextsong - Response: 
2022/03/23 04:22:11 [lang:3] API nextsong - Response: 
2022/03/23 04:22:23 [lang:3] API nextsong - Response: 
2022/03/23 04:22:35 [lang:3] API nextsong - Response: 
2022/03/23 04:22:47 [lang:3] API nextsong - Response: 
2022/03/23 04:22:59 [lang:3] API nextsong - Response: 
2022/03/23 04:23:11 [lang:3] API nextsong - Response: 
2022/03/23 04:23:23 [lang:3] API nextsong - Response: 
2022/03/23 04:23:35 [lang:3] API nextsong - Response: 
2022/03/23 04:23:47 [lang:3] API nextsong - Response: 
2022/03/23 04:23:59 [lang:3] API nextsong - Response: 
2022/03/23 04:24:11 [lang:3] API nextsong - Response: 
2022/03/23 04:24:23 [lang:3] API nextsong - Response: 
2022/03/23 04:24:35 [lang:3] API nextsong - Response: 
2022/03/23 04:24:47 [lang:3] API nextsong - Response: 
2022/03/23 04:24:59 [lang:3] API nextsong - Response: 
2022/03/23 04:25:11 [lang:3] API nextsong - Response: 
2022/03/23 04:25:23 [lang:3] API nextsong - Response: 
2022/03/23 04:25:35 [lang:3] API nextsong - Response: 
2022/03/23 04:25:47 [lang:3] API nextsong - Response: 
2022/03/23 04:25:59 [lang:3] API nextsong - Response: 
2022/03/23 04:26:11 [lang:3] API nextsong - Response: 
2022/03/23 04:26:23 [lang:3] API nextsong - Response: 
2022/03/23 04:26:35 [lang:3] API nextsong - Response: 
2022/03/23 04:26:47 [lang:3] API nextsong - Response: 
2022/03/23 04:26:59 [lang:3] API nextsong - Response: 
2022/03/23 04:27:11 [lang:3] API nextsong - Response: 
2022/03/23 04:27:23 [lang:3] API nextsong - Response: 
2022/03/23 04:27:35 [lang:3] API nextsong - Response: 
2022/03/23 04:27:47 [lang:3] API nextsong - Response: 
2022/03/23 04:27:59 [lang:3] API nextsong - Response: 
2022/03/23 04:28:11 [lang:3] API nextsong - Response: 
2022/03/23 04:28:23 [lang:3] API nextsong - Response: 
2022/03/23 04:28:35 [lang:3] API nextsong - Response: 
2022/03/23 04:28:47 [lang:3] API nextsong - Response: 
2022/03/23 04:28:59 [lang:3] API nextsong - Response: 
2022/03/23 04:29:11 [lang:3] API nextsong - Response: 
2022/03/23 04:29:23 [lang:3] API nextsong - Response: 
2022/03/23 04:29:35 [lang:3] API nextsong - Response: 
2022/03/23 04:29:47 [lang:3] API nextsong - Response: 
2022/03/23 04:29:59 [lang:3] API nextsong - Response: 
2022/03/23 04:30:11 [lang:3] API nextsong - Response: 
2022/03/23 04:30:23 [lang:3] API nextsong - Response: 
2022/03/23 04:30:35 [lang:3] API nextsong - Response: 
2022/03/23 04:30:47 [lang:3] API nextsong - Response: 
2022/03/23 04:30:59 [lang:3] API nextsong - Response: 
2022/03/23 04:31:11 [lang:3] API nextsong - Response: 
2022/03/23 04:31:23 [lang:3] API nextsong - Response: 
2022/03/23 04:31:35 [lang:3] API nextsong - Response: 
2022/03/23 04:31:47 [lang:3] API nextsong - Response: 
2022/03/23 04:31:59 [lang:3] API nextsong - Response: 
2022/03/23 04:32:11 [lang:3] API nextsong - Response: 
2022/03/23 04:32:23 [lang:3] API nextsong - Response: 
2022/03/23 04:32:35 [lang:3] API nextsong - Response: 
2022/03/23 04:32:47 [lang:3] API nextsong - Response: 
2022/03/23 04:32:59 [lang:3] API nextsong - Response: 
2022/03/23 04:33:11 [lang:3] API nextsong - Response: 
2022/03/23 04:33:23 [lang:3] API nextsong - Response: 
2022/03/23 04:33:35 [lang:3] API nextsong - Response: 
2022/03/23 04:33:47 [lang:3] API nextsong - Response: 
2022/03/23 04:33:59 [lang:3] API nextsong - Response: 
2022/03/23 04:34:11 [lang:3] API nextsong - Response: 
2022/03/23 04:34:23 [lang:3] API nextsong - Response: 
2022/03/23 04:34:35 [lang:3] API nextsong - Response: 
2022/03/23 04:34:47 [lang:3] API nextsong - Response: 
2022/03/23 04:34:58 [lang:3] API nextsong - Response: annotate:title="Tom Hop",duration="64.00",song_id="3338c20febbb5b0bafeba8d1c3892dee",media_id="3105",liq_amplify="0.00dB",playlist_id="1":/var/azuracast/stations/music/media/NoVocal1/friendly_folk.mp3
[mp3 @ 0x7f6490036500] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f649003ea40] Estimating duration from bitrate, this may be inaccurate


**Icecast Error Log:**
[2022-03-21  18:56:22] WARN xml/parsing unknown element "directory" parsing "mount" at line 33
[2022-03-21  18:56:22] WARN xml/parsing warning: 
[2022-03-21  18:56:22] WARN xml/parsing unknown element "directory" parsing "mount" at line 37
[2022-03-21  18:56:22] WARN slave/slave_startup process has 65536 max file descriptor limit
[2022-03-22  21:49:17] WARN xml/parsing warning: 
[2022-03-22  21:49:17] WARN xml/parsing unknown element "directory" parsing "mount" at line 33
[2022-03-22  21:49:17] WARN xml/parsing warning: 
[2022-03-22  21:49:17] WARN xml/parsing unknown element "directory" parsing "mount" at line 37
[2022-03-22  21:49:17] WARN slave/slave_startup process has 65536 max file descriptor limit
[2022-03-23  03:11:08] WARN xml/parsing warning: 
[2022-03-23  03:11:08] WARN xml/parsing unknown element "directory" parsing "mount" at line 33
[2022-03-23  03:11:08] WARN xml/parsing warning: 
[2022-03-23  03:11:08] WARN xml/parsing unknown element "directory" parsing "mount" at line 37
[2022-03-23  03:11:08] WARN slave/slave_startup process has 65536 max file descriptor limit
```

**Comment by CyberMixRo** [comment]
Same issue here, stations are going offline after few hours, in Azuracast logs i see many of this errors:

`AzuraCast.WARNING: Console command `azuracast:internal:liquidsoap` exited with error code 1. [] []`

**Comment by aconitumnapellus** [comment]
Same on the stable branch.

**Comment by aconitumnapellus** [comment]
Please backport this to stable: https://github.com/AzuraCast/AzuraCast/pull/5160

**Comment by SlvrEagle23** [comment]
@aconitumnapellus Done; you should now have the correct download URL on the stable Ansible branch.

**Comment by stardevelop** [comment]
azuracast | [2022-09-16T07:49:02.442238+00:00] AzuraCast.WARNING: Console command `azuracast:sync:run` exited with error code 2002. [] []
azuracast |
azuracast | In ExceptionConverter.php line 103:
azuracast |
azuracast |   An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or
azuracast |    directory
azuracast |
azuracast |
azuracast | In Exception.php line 28:
azuracast |
azuracast |   SQLSTATE[HY000] [2002] No such file or directory
azuracast |
azuracast |
azuracast | In Driver.php line 28:
azuracast |
azuracast |   SQLSTATE[HY000] [2002] No such file or directory
azuracast |
azuracast |
azuracast | azuracast:sync:run
azuracast |
🖥️🎵－🎶－📻 Waiting...station_1_backend stdout | 2022/09/16 12:18:55 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body:
azuracast | station_1_backend stdout | 2022/09/16 12:18:55 [lang:3] API nextsong - Response (502): <html>
azuracast | station_1_backend stdout | 2022/09/16 12:18:55 [lang:3] <head><title>502 Bad Gateway</title></head>
azuracast | station_1_backend stdout | 2022/09/16 12:18:55 [lang:3] <body>
azuracast | station_1_backend stdout | 2022/09/16 12:18:55 [lang:3] <center><h1>502 Bad Gateway</h1></center>
azuracast | station_1_backend stdout | 2022/09/16 12:18:55 [lang:3] <hr><center>nginx</center>
azuracast | station_1_backend stdout | 2022/09/16 12:18:55 [lang:3] </body>
azuracast | station_1_backend stdout | 2022/09/16 12:18:55 [lang:3] </html>
azuracast | station_1_backend stdout | 2022/09/16 12:18:55 [lang:3]
azuracast | station_1_backend stdout | 2022/09/16 12:18:55 [request:3] Nonexistent file or ill-formed URI "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r"!
azuracast | station_1_backend stdout |
azuracast | nginx stdout | 2022/09/16 07:48:55 [crit] 133#133: *690 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/3/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast | nginx stdout |
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/3/liquidsoap/nextsong' with body:
azuracast | station_3_backend stdout |
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [lang:3] API nextsong - Response (502): <html>
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [lang:3] <head><title>502 Bad Gateway</title></head>
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [lang:3] <body>
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [lang:3] <center><h1>502 Bad Gateway</h1></center>
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [lang:3] <hr><center>nginx</center>
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [lang:3] </body>
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [lang:3] </html>
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [lang:3]
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [request:3] Nonexistent file or ill-formed URI "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r"!
azuracast | station_3_backend stdout |
azuracast | nginx stdout | 2022/09/16 07:49:05 [crit] 133#133: *692 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/2/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast | nginx stdout | 2022/09/16 07:49:05 [crit] 133#133: *693 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/1/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast | nginx stdout |
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body:
azuracast | station_1_backend stdout |
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/nextsong' with body:
azuracast | station_2_backend stdout |
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [lang:3] API nextsong - Response (502): <html>
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [lang:3] <head><title>502 Bad Gateway</title></head>
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [lang:3] <body>
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [lang:3] <center><h1>502 Bad Gateway</h1></center>
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [lang:3] <hr><center>nginx</center>
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [lang:3] </body>
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [lang:3] </html>
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [lang:3]
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [request:3] Nonexistent file or ill-formed URI "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r"!
azuracast | station_1_backend stdout |
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [lang:3] API nextsong - Response (502): <html>
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [lang:3] <head><title>502 Bad Gateway</title></head>
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [lang:3] <body>
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [lang:3] <center><h1>502 Bad Gateway</h1></center>
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [lang:3] <hr><center>nginx</center>
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [lang:3] </body>
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [lang:3] </html>
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [lang:3]
azuracast | station_2_backend stdout |
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [request:3] Nonexistent file or ill-formed URI "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r"!
azuracast | station_2_backend stdout |
azuracast | nginx stdout | 2022/09/16 07:49:05 [crit] 133#133: *696 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/3/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast | nginx stdout |
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/3/liquidsoap/nextsong' with body:
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [lang:3] API nextsong - Response (502): <html>
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [lang:3] <head><title>502 Bad Gateway</title></head>
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [lang:3] <body>
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [lang:3] <center><h1>502 Bad Gateway</h1></center>
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [lang:3] <hr><center>nginx</center>
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [lang:3] </body>
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [lang:3] </html>
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [lang:3]
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [request:3] Nonexistent file or ill-formed URI "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r"!
azuracast | station_3_backend stdout |
azuracast | station_1_backend stdout | 2022/09/16 12:19:12 [decoder:2] Decoding "/var/azuracast/stations/music/media/NoVocal1/balearic_paradox.mp3" ended: Ffmpeg_decoder.End_of_file.
azuracast | station_1_backend stdout |
azuracast | station_1_backend stdout | [mp3 @ 0x7f12c81e4f40]
azuracast | station_1_backend stdout | Estimating duration from bitrate, this may be inaccurate
azuracast | station_1_backend stdout |
azuracast | station_1_backend stdout | [mp3 @ 0x7f12c81e4f40]
azuracast | station_1_backend stdout | Estimating duration from bitrate, this may be inaccurate
azuracast | station_1_backend stdout |
azuracast | station_1_backend stdout | 2022/09/16 12:19:12 [playlist_default:3] Prepared "/var/azuracast/stations/music/media/NoVocal1/wind_down.mp3" (RID 108).
azuracast | station_1_backend stdout |
azuracast | station_1_backend stdout | 2022/09/16 12:19:12 [cue_playlist_default:3] Cueing in...
azuracast | station_1_backend stdout |
azuracast | station_1_backend stdout | 2022/09/16 12:19:12 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
azuracast | station_1_backend stdout |
