### ISSUE TITLE
Error Uploading Files via Media > Music Files

### ISSUE THREAD

**Issue by bilalbox** [AzuraCast/AzuraCast#5222]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #e19af51 (2022-03-18 10:52)

### What happened?

When the server has been running for a week or so without any updates or restarts, the upload function available at `Stations > Media > Music Files` stops working. The web UI will briefly display an error message (too quick to catch with a screenshot), but the dev tools will provide a `500` response status code for `POST` requests to `/station/STATION_NUMBER/files`. The docker logs below may shed some light.

Restarting the server always fixes the issue, but of course it would be nice to get to the root of the problem.

### Relevant log output

```shell
2022/03/23 16:26:18 [error] 701#701: *179786 open() "/var/azuracast/www/web/static/dist/lib/bootstrap/bootstrap.bundle.min.js.map" failed (2: No such file or directory), client: 114.122.228.3, server: localhost, request: "GET /static/dist/lib/bootstrap/bootstrap.bundle.min.js.map HTTP/2.0", host: "azuracast.iqbpn.com"

2022/03/23 16:26:25 [crit] 701#701: *179786 mkdir() "/tmp/app_nginx_client/5" failed (2: No such file or directory), client: 114.122.228.3, server: localhost, request: "POST /api/station/3/files/upload HTTP/2.0", host: "azuracast.iqbpn.com", referrer: "https://azuracast.iqbpn.com/station/3/files"

2022/03/23 16:26:25 [crit] 701#701: *179786 mkdir() "/tmp/app_nginx_client/6" failed (2: No such file or directory), client: 114.122.228.3, server: localhost, request: "POST /api/station/3/files/upload HTTP/2.0", host: "azuracast.iqbpn.com", referrer: "https://azuracast.iqbpn.com/station/3/files"
  ok: run: php-fpm: (pid 85) 321990s

[2022-03-23T16:26:48.490247+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":0,"workerName":"app_worker_0"} []
```

**Comment by SlvrEagle23** [comment]
@bilalbox We identified this error and should have a fix published for it already; try updating to the latest Rolling Release and it should resolve things for you.

**Comment by bilalbox** [comment]
@SlvrEagle23 OK, thanks! Currently running `Rolling Release #[31ca135] (2022-03-23 22:00)` and hoping for the best...

**Comment by bilalbox** [comment]
I'll close the issue and if it resurfaces we can reopen. Thanks again for your support!
