### ISSUE TITLE
Can't request recently added songs after update on public pages

### ISSUE THREAD

**Issue by coxabling** [AzuraCast/AzuraCast#5223]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #6886f5e (2022-03-23 8:04)

### What happened?

I can't request recently added songs from the public page even though the songs appear in my media library. 

Songs show in the media library but do not show on the public request page.

**Comment by SpeedyCharly** [comment]
Are requests enabled in the playlist these media are assigned to?

**Comment by SlvrEagle23** [comment]
@coxabling I believe we talked about this in the Discord, but it's likely that this is just a cache issue; we temporarily store requestable songs to improve performance when the page is requested by anonymous users.

**Comment by coxabling** [comment]
Yes, clearing the cache sorted the issue. Thanks for the prompt reply.
