### ISSUE TITLE
App\Exception\SupervisorException at /var/azuracast/www/src/Radio/AbstractAdapter.php L268: Liquidsoap encountered an error Check the log for details.

### ISSUE THREAD

**Issue by LOIZoclock** [AzuraCast/AzuraCast#5226]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.14.1

### What happened?

After reinstalling Ubuntu 20.4 and Azuracast v0.14.1 Ansible I set up my playlist, but when I click on Start (AutoDJ service / Liquidsoap) I get the following error in a red label at the top right of the screen:

```
App\Exception\SupervisorException at /var/azuracast/www/src/Radio/AbstractAdapter.php L268: Liquidsoap encountered an error
Check the log for details.
```

After reinstalling I never used Liquidsoap as I have this issue.

I also tried to start Liquidsoap after updating via ` ./update.sh --full`

**Comment by SlvrEagle23** [comment]
@LOIZoclock Why did you install version 0.14.1 specifically? That's several versions old, and is no longer supported by us. I'd strongly recommend updating to the latest version if possible.

**Comment by LOIZoclock** [comment]
Hi [SlvrEagle23](https://github.com/SlvrEagle23),

I use 0.14.1 as it's the only working on my VM after installation. 

I tried 0.15.2, 0.15.1 and 0.15.0 but I get the message "Slim Application Error" in browser.

**Comment by SC2Mitch** [comment]
If you're having issues with them versions then we ask you send us the details of your error accompanied with Docker logs, we don't support older versions.
