### ISSUE TITLE
Bind for 0.0.0.0:8496 failed: port is already allocated

### ISSUE THREAD

**Issue by KylePython** [AzuraCast/AzuraCast#5232]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

31ca135

### What happened?

When updating the server, when it tries to restart all stations and create azuracast it returns error with this

ERROR: for azuracast_web  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web (435ddc9f2cca82ff73b3305053ad4c973d2b398994dcf98cb21a40c90e0c83a7): Bind for 0.0.0.0:8496 failed: port is already allocated

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web (435ddc9f2cca82ff73b3305053ad4c973d2b398994dcf98cb21a40c90e0c83a7): Bind for 0.0.0.0:8496 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

**Comment by KylePython** [comment]
CC: @HuckinB

**Comment by SlvrEagle23** [comment]
@KylePython It can be helpful to run something like `netstat -tulpn` on the host computer to see what other applications are listening on those ports. You can customize port ranges in AzuraCast by re-running the installer/updater, and when prompted to change configuration settings, choose "Yes".

**Comment by KylePython** [comment]
We removed the override yml file and it had seemed to work.

Another thing thoe, is there a way we can toggle "Live Broadcast" when a streamer has connected to the encoder?
I'd prefer if that doesn't broadcast if there's a way?

**Comment by SlvrEagle23** [comment]
@KylePython While you can't disable whether that flag appears in the API responses, you could use custom CSS to remove it from the public player display if you wanted, using something like:

```css
[data-theme] .now-playing-live {
    display: none;
}
```

**Comment by KylePython** [comment]
Ah we don't use the public player display.
We'll try and work a way around it with our API's, thanks for your suggestion anyway :)
