### ISSUE TITLE
Issue when uploading file to station via Azuracast web: mkdir failed

### ISSUE THREAD

**Issue by danielpilot** [AzuraCast/AzuraCast#5238]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #bb6ddf8 (2022-03-18 8:45)

### What happened?

Hello!

So... I'm unable to upload files to my station via the web interface. It just doesn't show any error on the frontal panel but doesn't upload the file at all.

Checking the request done, it just shows a 500 Nginx error. I was able to get the log via the docker log. It just throws a critical error showing that mkdir returns a critical error because not such file or directory exists.

After rebooting the whole system it seems to work again but after some time this ends up happening again.

If you need any additional information, please just ask.

Thank you!

### Relevant log output

```shell
azuracast | 2022/03/27 10:28:56 [crit] 682#682: *28055 mkdir() "/tmp/app_nginx_client/6" failed (2: No such file or directory), client: myip, server: localhost, request: "POST /api/station/1/files/upload HTTP/2.0", host: "myhost", referrer: "https://myhost/station/1/files"
```

**Comment by SlvrEagle23** [comment]
@danielpilot We found another potential cause of this issue and have published a fix for it in the latest Rolling Release version; updating should resolve this issue for you. Sorry for any inconvenience!
