### ISSUE TITLE
Restart command doesn't work

### ISSUE THREAD

**Issue by tehcojam** [AzuraCast/AzuraCast#524]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Ubuntu 17.10

![](https://sun9-5.userapi.com/c840420/v840420199/6df48/WRuDOF9HXYM.jpg)
![](https://sun9-9.userapi.com/c834100/v834100199/fd6a2/TKAKmQ_ZWyw.jpg)

**Comment by SlvrEagle23** [comment]
@tehcojam One of the versions of our Docker container seems to have experienced problems with the temporary container. The easiest fix is to run:

```
docker-compose down
docker volume rm azuracast_tmp_data
docker-compose up -d
```

This will remove the "temporary data" volume associated with AzuraCast, which is automatically regenerated the next time you visit the site itself.

**Comment by tehcojam** [comment]
@SlvrEagle23 It didn't help. There are the same errors as in the screenshots.

**Comment by tehcojam** [comment]
I re-clone the repository from the Github, made an update through Docker, and then did what you advised in your "fix", and the problem seems to be resolved.

¯\_(ツ)_/¯
