### ISSUE TITLE
Ability to detect silence on incoming streams

### ISSUE THREAD

**Issue by muzo178** [AzuraCast/AzuraCast#525]
It might be good practice to add a silence detection mechanism for incoming live streams. When the incoming stream is not disconnected and broadcasting silence, the station stays silent. 

This can easily be implemented with Liquidsoap, but you might want to make the silence threshold and duration configurable in the  UI. See example below:

```
# Switch to fallback if live source is silent (-40dB) for more than 30 seconds
input = fallback(track_sensitive=false,
                 [strip_blank(threshold=-40.,max_blank=30.,live),backupmusic])
```

**Comment by xtechgamer735** [comment]
This is a really good idea, I would kill for a feature like this although I suppose it could be added in an advanced config?

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38925/detect-silence-dead-air-in-incoming-streams
