### ISSUE TITLE
Can't install AzuraCast

### ISSUE THREAD

**Issue by nickloud** [AzuraCast/AzuraCast#5253]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Hello. Previously, I ran the commands and the installation went smoothly. Now it just writes like this and does not install further.

https://ibb.co/x6v3xRk - Screenshote

**Comment by LauraS-Development** [comment]
Here is the same problem.

**Comment by gunsar** [comment]
same problem

`root@on:/var/azuracast# curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh
root@on:/var/azuracast# chmod a+x docker.sh
root@on:/var/azuracast# ./docker.sh install
Checking installation requirements for AzuraCast...
[PASS] Operating System: Linux
[PASS] Architecture: x86_64
[PASS] Command Present: curl
[PASS] Command Present: awk
[PASS] User Permissions
[PASS] Installation Directory
[PASS] All requirements met!
Docker is already installed! Continuing...
Docker Compose is already installed. Continuing...
root@on:/var/azuracast#
`

**Comment by SC2Mitch** [comment]
Thanks for the reports guys, will flag it up

**Comment by JVDELVALLE** [comment]
I have the same problem, I went to install it on a machine and it's giving the same error

**Comment by gunsar** [comment]
# https://github.com/AzuraCast/AzuraCast/issues/5251

**Comment by SlvrEagle23** [comment]
Sorry about that folks! Try running:

```
./docker.sh update-self
```

and then the installation should complete without issue.
