### ISSUE TITLE
Implement advertising or a break for the voice

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#526]
Hello, I was wondering if there is an option that can be implemented after a number of songs start an advertisement from me inserted or the voice from a speaker always pre-recorded by me. Thank you

**Comment by susl16c** [comment]
Create a playlist and schedule it to play it.

**Comment by aline-matos** [comment]
+1

**Comment by aline-matos** [comment]
> Create a playlist and schedule it to play it.

This doesn't work if you need to put the same file multiple times: 

>`{"code":0,"message":"An exception occurred while executing 'UPDATE station_media SET path = ? WHERE id = ?' with params [\"Teste\\\/transcript.mp3\", 7]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Teste\/transcript.mp3-1' for key 'path_unique_idx'","formatted_message":"An exception occurred while executing 'UPDATE station_media SET path = ? WHERE id = ?' with params [\"Teste\\\/transcript.mp3\", 7]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Teste\/transcript.mp3-1' for key 'path_unique_idx'","extra_data":[],"success":false}`

**Comment by SlvrEagle23** [comment]
@aline-matos That is a different error that should be created as a new ticket. Although it's likely not actually an error, as the same file shouldn't be included in a station's media collection twice in any case.

**Comment by aline-matos** [comment]
Ok, thank you @SlvrEagle23
