### ISSUE TITLE
Station not playing music after update

### ISSUE THREAD

**Issue by smilingpeanut** [AzuraCast/AzuraCast#5261]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #99303a6 (2022-04-06 12:22)

### What happened?

After updating AzuraCast to Rolling Release #[99303a6] (2022-04-06 12:22), one of our stations (there are four on the server) has an issue whenever broadcasting is restarted or AzuraCast is updated. The station just loops the default error message over and over and does not play any of the music on the playlist. The music for this station is on an S3-compatible storage (Wasabi), but there is nothing custom in Liquidsoap or Icecast for the station.

Songs are present in the Upcoming Queue (screenshot: https://cloudup.com/cPQbWFO1O8Z) but do not play.

Expected Behavior:
Songs from the playlist should play.

### Relevant log output

```shell
2022/04/06 12:42:47 [lang:3] API nextsong - Response: 
[mp3float @ 0x7f91bc33cf40] Could not update timestamps for discarded samples.
2022/04/06 12:42:49 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/04/06 12:42:50 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 0).
[mp3float @ 0x7f91bc0b1640] Could not update timestamps for skipped samples.
2022/04/06 12:42:59 [lang:3] API nextsong - Response: 
2022/04/06 12:43:01 [lang:3] API nextsong - Response: 
2022/04/06 12:43:13 [lang:3] API nextsong - Response: 
2022/04/06 12:43:15 [lang:3] API nextsong - Response: 
[mp3float @ 0x7f91bc0b1640] Could not update timestamps for discarded samples.

Nothing seemingly relevant in the Docker logs.
```

**Comment by SlvrEagle23** [comment]
@smilingpeanut Would you mind updating to the very latest Rolling Release version, released a few hours later this morning?

We found and fixed a potential cause of this issue and it may apply to your station as well.

**Comment by smilingpeanut** [comment]
@SlvrEagle23 Just updated to #[da6e402] (2022-04-07 2:07) and the issue unfortunately persists. Another oddity: if I switch its Storage Location back to use the local storage on the server, music plays.

**Comment by SlvrEagle23** [comment]
@smilingpeanut We'd probably need a longer slice of the Liquidsoap logs to really see what's going on here. If you don't mind sharing those, that would be helpful.

Also, there's a utility in system administration called the Debugger tool...you can visit that page, then at the bottom, select the station and click "Get Next Song" and see what it returns as far as annotations go. You can also rebuild the upcoming song queue from that same area.

**Comment by SlvrEagle23** [comment]
@smilingpeanut We found and fixed a major issue with how our AutoDJ interacts with AzuraCast in the latest Rolling Release version; the fix for this was just released a few minutes ago, so if you don't mind updating and trying the new version out to see if it resolves your issues, it would be much appreciated! The latest version also improves how we log errors related to the AutoDJ, so even if there are still errors, we will have more information about them moving forward. Sorry for the inconvenience and thank you for your patience.

**Comment by smilingpeanut** [comment]
And we're back! Thank you so very much for all your work!
