### ISSUE TITLE
Geen streaming luisteraars. Op Docker.

### ISSUE THREAD

**Issue by RigaTekk** [AzuraCast/AzuraCast#5263]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

Het feit dat de stream steeds uitvalt, geen connectie kan maken via SamBroadcaster of Mixxx. En er dus niet live gedraaid kan worden. Unable to connect, en geen luisteraars op de AutoDJ

### Relevant log output

```shell
Het feit dat de stream steeds uitvalt, geen connectie kan maken via SamBroadcaster of Mixxx. En er dus niet live gedraaid kan worden. Unable to connect, en geen luisteraars op de AutoDJ
```

**Comment by finnie2006** [comment]
Azuracast is english not dutch, so issues should also be english

**Comment by xewl** [comment]
Next to translation to English, please share the missing pieces of  the requested information;

- Azuracast version (see footer on the admin panel).
- Your server specifications
- Validate if you have any firewall rules set up
- Try 1 port higher or lower than the one that's given while streaming
- Are you trying to stream to the  "/" endpoint, as "source" or as a DJ?
- and if it's a SHOUT or ICEcast based station (I assume ICE, as that's the default)

I reckon they might be useful in this situation.
