### ISSUE TITLE
Unable to install shoutcast v2

### ISSUE THREAD

**Issue by Dezodev** [AzuraCast/AzuraCast#5273]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.15.2

### What happened?

Hello,

I recently installed Azuracast on a vps to start a web radio. I would like to broadcast it with shoutcast.

So I tried to do the shoutcast installation process, but nothing happened.

I downloaded the .zip file and uploaded the file to the `/admin/install/shoutcast` page.
The file is uploaded. It disappears right after and nothing happens afterwards.
When I reload the page it tells me that shoutcast is not installed.

Can you help me ?
Can we install it by connecting to the docker command line?

Deniz.

**Comment by SC2Mitch** [comment]
Hi, you can install it through your server's admin panel, go to this path `domain/admin/install/shoutcast` and drop the file in, it should show this after you've installed. 
![image](https://user-images.githubusercontent.com/29955942/162626021-66c6e1c1-f0c4-4899-872f-c5f5a37e41be.png)

**Comment by Dezodev** [comment]
Hi,

I did it again and got the following result:

![Capture d’écran 2022-04-11 à 10 41 20](https://user-images.githubusercontent.com/13338419/162699079-174e120f-6f30-424d-82be-0b70a85ad236.jpg)

**Comment by SC2Mitch** [comment]
That's a confusing error message, because you have installed it successfully, but it throws this error, strange. 
``` bash
msgid "SHOUTcast 2 DNAS is not currently installed on this installation."
msgstr "SHOUTcast 2 DNAS n'est pas actuellement installé sur votre machine."
```

**Comment by Dezodev** [comment]
Hi,

I did a video screen capture to make it easier to see what’s going on. I hope that can help.

![Kapture 2022-04-19 at 12 40 37](https://user-images.githubusercontent.com/13338419/163987946-96e48211-e095-4c98-a8c7-7a30fca6bd5c.gif)

I forgot to give you the OS version on the VPS : `Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-1025-oracle aarch64)`.

I’m available if you need more information.

Deniz.

**Comment by Vaalyn** [comment]
SHOUTcast does not provide binaries for the `aarch64` architecture.
They only support x86 / x64 CPUs so the installation process fails to execute the binary.
(We don't have a check for this in the installer yet which is why there is no detailed error message).

If you are running AzuraCast on an ARM based machine you will have to use Icecast instead of SHOUTcast.

**Comment by SC2Mitch** [comment]
Should be fixed now in rolling
