### ISSUE TITLE
Twitter Webhook Not Working

### ISSUE THREAD

**Issue by SmartGuyCodes** [AzuraCast/AzuraCast#5277]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 • v0.15.2 Stable • Docker • PHP 8.1•

### What happened?

Already set up Twitter App in dev sandbox and integrated with Azuracast's webhook. 

Unfortunately upon testing I getting error in the log below

Kindly assist.

### Relevant log output

```shell
[2022-04-10T21:08:48.486423+00:00] AzuraCast.DEBUG: Posting to Twitter... [] []
[2022-04-10T21:08:48.674357+00:00] AzuraCast.DEBUG: HTTP client POST call to https://api.twitter.com/1.1/statuses/update.json produced response 401 [] []
[2022-04-10T21:08:48.674570+00:00] AzuraCast.DEBUG: Twitter returned code 401 {"response_body":"{\"request\":\"\\/1.1\\/statuses\\/update.json\",\"error\":\"Read-only application cannot POST.\"}"} []
```

**Comment by Jarad999** [comment]
I'm having the same problem but with discord and probably twitter also. I believe it's all of the web hooks that aren't working. I personally don't know as I'm not an experienced developer.

**Comment by SlvrEagle23** [comment]
@SmartGuyCodes It appears you set up your application on Twitter to only have read-only access to your timeline; it needs to have the ability to create posts, or else it won't function. This may require editing on your part on the Twitter developer console.

@Jarad999 Without any additional information, we can't help in diagnosing your problem.

**Comment by Jarad999** [comment]
> @SmartGuyCodes It appears you set up your application on Twitter to only have read-only access to your timeline; it needs to have the ability to create posts, or else it won't function. This may require editing on your part on the Twitter developer console.
> 
> 
> 
> @Jarad999 Without any additional information, we can't help in diagnosing your problem.

I had created my own issue
