### ISSUE TITLE
Customize port Error

### ISSUE THREAD

**Issue by gunsar** [AzuraCast/AzuraCast#5279]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #b2c79e8 (2022-04-11 2:18)

### What happened?

fresh install 
and have a custom port from the beginning install the port on docker compose 8000-10000

### Relevant log output

```shell
SupervisorException at /var/azuracast/www/src/Radio/AbstractAdapter.php L286: Icecast encountered an error
eate listener socket on port 9000
[2022-04-11 03:14:02] EROR connection/connection_setup_sockets unable to setup all listening sockets
[2022-04-11 03:14:02] EROR main/fatal_error Server startup failed. Exiting
[2022-04-11 03:14:16] EROR connection/connection_setup_sockets Could not create listener socket on port 9000
[2022-04-11 03:14:16] EROR connection/connection_setup_sockets unable to setup all listening sockets
[2022-04-11 03:14:16] EROR main/fatal_error Server startup failed. Exiting
```

**Comment by SlvrEagle23** [comment]
@gunsar Internally, we use various ports from 9000 to 9010 to handle internal traffic between various parts of the application. That's why we typically reserve the range from 8000-8999 for station traffic.

**Comment by gunsar** [comment]
how to solve this problem?
the link that has been spread, my streaming averages between 9000-9999
on the previous version AzuraCast 0.15.0 running normally I use that port

> @gunsar Internally, we use various ports from 9000 to 9010 to handle internal traffic between various parts of the application. That's why we typically reserve the range from 8000-8999 for station traffic.

**Comment by SlvrEagle23** [comment]
@gunsar You can use any port from 9020 upward, but unfortunately it was only really by "accident" that the 9000-9010 port range worked before, because we weren't protecting against that...since they're used internally, it's strongly advisable _not_ to use those ports for public-facing stations.

**Comment by gunsar** [comment]
OK, thanks for the explanation. success for AzuraCast team, I will use port above 9020. thank you, sorry for always bothering..

> @gunsar You can use any port from 9020 upward, but unfortunately it was only really by "accident" that the 9000-9010 port range worked before, because we weren't protecting against that...since they're used internally, it's strongly advisable _not_ to use those ports for public-facing stations.

**Comment by gunsar** [comment]
custom port :8088 doesn't work
