### ISSUE TITLE
Disk space full paralyzes azuracast

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#5280]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release - 10 april 2022

### What happened?

Hello, after an update the disk space fills up to 100%.

I have tried running docker system prune -a and it recovers more than 50% of disk space, but after a few hours it is back to 100%.

Any idea?

**Comment by SlvrEagle23** [comment]
It's possible that, if you're using remote (Dropbox, S3, etc) filesystems, the system is just pulling too many files locally, and that's causing you to run out of space too quickly. We've switched to a new method of handling remote files which also conveniently allows us to implement an "auto-delete-when-finished" function, so Liquidsoap should no longer be cluttering up the filesystem with temporary copies of files. This may improve the disk space usage overall, especially in this specific case.

**Comment by marekdziem** [comment]
I have this problem - Azuracast docker runs out of space and I cant figure out what to do about it!

all sations not running
:(
urgent assistance required
