### ISSUE TITLE
fallback file sc_serv.conf not working

### ISSUE THREAD

**Issue by Vicinis** [AzuraCast/AzuraCast#5285]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#6e728bb 

### What happened?

when i upload a fallback mp3 file in the web interface, it doesn't update the sc_serv.conf after reloading station
no issues with an intro file

**Comment by SC2Mitch** [comment]
Checked on my local machine, can confirm it doesn't update the sc_serv.conf

**Comment by Vicinis** [comment]
just checking to see if there are any updates to this.
thanks

**Comment by SlvrEagle23** [comment]
The Custom Fallback File that's uploaded via the station management UI is something that Liquidsoap uses when it has no other tracks to play or an error occurs; it's meant to replace the default "This station is powered by AzuraCast" message. It doesn't update the frontend (Shoutcast/Icecast) configurations; only the per-mount intro files do that.
