### ISSUE TITLE
Discord webhook for "live dj disconnects" from stream is missing live dj information in metadata

### ISSUE THREAD

**Issue by mdrown** [AzuraCast/AzuraCast#5289]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.15.2 Stable Docker PHP8.1

### What happened?

Set discord web hook for Live Streamer to connect, behaves as expected.

Set discord web hook to Live Stream disconnect, and {{live.streamer_name}} is empty in metadata, so can't populate personalized data.  Expected behavior is live.streamer_name to be populated with streamer going offline.

![image](https://user-images.githubusercontent.com/25239271/163093105-5439ed1e-6701-49b8-af96-a7302a976fee.png)

**Comment by dvdokkum** [comment]
I just recently set up a discord bot for the first time and ran into the same issue. When the webhook fires the streamer is no longer live so the variable is empty. I got around it by grabbing the streamer name from the most recent play history instead: 
`{{ song_history.0.streamer }}`

**Comment by mdrown** [comment]
Appears to work in my quick test, so "workaround" or documented solution is available.
