### ISSUE TITLE
autoupdate folder in playlist

### ISSUE THREAD

**Issue by dreinn** [AzuraCast/AzuraCast#529]
Hello,
I'd like to put an entire folder into a playlist. This is easy, but I see that the playlist is made of several files.
So if for example tomorrow I add 25 files to that folder, the playlist won't update with new files.
This is what I understand checking the content of the playlist generated by Azuracast.
Since liquidsoap can handle also folder into playlist, can you add the capabilities to include just folder and let liquidsoap autoupdate content when update?

**Comment by al-ec** [comment]
Essentially a playlist "watch folder".

I like it. I'll see if I can PR.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38787/automatically-associate-playlists-with-folders
