### ISSUE TITLE
docker-compose.override.yml not present and errors messages

### ISSUE THREAD

**Issue by RadioSSS** [AzuraCast/AzuraCast#5291]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

After trying to update Azuracast, we had this errors messages:

ERROR: The Compose file is invalid because:
Service nginx_proxy has neither an image nor a build context specified. At least one must be provided.
ERROR: The Compose file is invalid because:
Service nginx_proxy has neither an image nor a build context specified. At least one must be provided.

ERROR: for azuracast  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web (b8f4f76791c511e5e06e0249550bf6ba3ab861dc4fde3bed759b33417471f9f8): Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint azuracast_web (b8f4f76791c511e5e06e0249550bf6ba3ab861dc4fde3bed759b33417471f9f8): Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use
ERROR: Encountered errors while bringing up the project.

We can also see that the docker-compose.override.yml file is not present in : /var/azuracast

Can you help please?

**Comment by gunsar** [comment]
I'm using Rolling Release #2c428b1 and it runs normally, which version do you have?

**Comment by RadioSSS** [comment]
We 've tried to update the 0.13.0 Rolling Release to the latest version.


On 2022-04-14 07:32, gunsar wrote:

> I'm using Rolling Release #2c428b1 and it runs normally, which version do you have? 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>

-- 

 		WWW. Radio3S.org

 		E. ***@***.***

 

Links:
------
[1]
https://github.com/AzuraCast/AzuraCast/issues/5291#issuecomment-1098725912
[2]

**Comment by gunsar** [comment]
now i upgrade to Rolling Release #1c4278e (2022-04-14 8:40) still running normally

**Comment by Vaalyn** [comment]
Have you updated the `docker.sh` script too?

Please run the following two commands in this order:
```
./docker.sh update-self
./docker.sh update
```

**Comment by RadioSSS** [comment]
Yes we did it

**Comment by Vaalyn** [comment]
Then please post the full `docker-compose.yml` here please

**Comment by RadioSSS** [comment]
services:
    web:
        container_name: azuracast
        image: 'ghcr.io/azuracast/azuracast:${AZURACAST_VERSION:-latest}'
        ports:
            - '${AZURACAST_HTTP_PORT:-80}:80'
            - '${AZURACAST_HTTPS_PORT:-443}:443'
            - '${AZURACAST_SFTP_PORT:-2022}:2022'
            - '8000:8000'
            - '8005:8005'
            - '8006:8006'
            - '8010:8010'
            - '8015:8015'
            - '8016:8016'
            - '8020:8020'
            - '8025:8025'
            - '8026:8026'
            - '8030:8030'
            - '8035:8035'
            - '8036:8036'
            - '8040:8040'
            - '8045:8045'
            - '8046:8046'
            - '8050:8050'
            - '8055:8055'
            - '8056:8056'
            - '8060:8060'
            - '8065:8065'
            - '8066:8066'
            - '8070:8070'
            - '8075:8075'
            - '8076:8076'
            - '8090:8090'
            - '8095:8095'
            - '8096:8096'
            - '8100:8100'
            - '8105:8105'
            - '8106:8106'
            - '8110:8110'
            - '8115:8115'
            - '8116:8116'
            - '8120:8120'
            - '8125:8125'
            - '8126:8126'
            - '8130:8130'
            - '8135:8135'
            - '8136:8136'
            - '8140:8140'
            - '8145:8145'
            - '8146:8146'
            - '8150:8150'
            - '8155:8155'
            - '8156:8156'
            - '8160:8160'
            - '8165:8165'
            - '8166:8166'
            - '8170:8170'
            - '8175:8175'
            - '8176:8176'
            - '8180:8180'
            - '8185:8185'
            - '8186:8186'
            - '8190:8190'
            - '8195:8195'
            - '8196:8196'
            - '8200:8200'
            - '8205:8205'
            - '8206:8206'
            - '8210:8210'
            - '8215:8215'
            - '8216:8216'
            - '8220:8220'
            - '8225:8225'
            - '8226:8226'
            - '8230:8230'
            - '8235:8235'
            - '8236:8236'
            - '8240:8240'
            - '8245:8245'
            - '8246:8246'
            - '8250:8250'
            - '8255:8255'
            - '8256:8256'
            - '8260:8260'
            - '8265:8265'
            - '8266:8266'
            - '8270:8270'
            - '8275:8275'
            - '8276:8276'
            - '8280:8280'
            - '8285:8285'
            - '8286:8286'
            - '8290:8290'
            - '8295:8295'
            - '8296:8296'
            - '8300:8300'
            - '8305:8305'
            - '8306:8306'
            - '8310:8310'
            - '8315:8315'
            - '8316:8316'
            - '8320:8320'
            - '8325:8325'
            - '8326:8326'
            - '8330:8330'
            - '8335:8335'
            - '8336:8336'
            - '8340:8340'
            - '8345:8345'
            - '8346:8346'
            - '8350:8350'
            - '8355:8355'
            - '8356:8356'
            - '8360:8360'
            - '8365:8365'
            - '8366:8366'
            - '8370:8370'
            - '8375:8375'
            - '8376:8376'
            - '8380:8380'
            - '8385:8385'
            - '8386:8386'
            - '8390:8390'
            - '8395:8395'
            - '8396:8396'
            - '8400:8400'
            - '8405:8405'
            - '8406:8406'
            - '8410:8410'
            - '8415:8415'
            - '8416:8416'
            - '8420:8420'
            - '8425:8425'
            - '8426:8426'
            - '8430:8430'
            - '8435:8435'
            - '8436:8436'
            - '8440:8440'
            - '8445:8445'
            - '8446:8446'
            - '8450:8450'
            - '8455:8455'
            - '8456:8456'
            - '8460:8460'
            - '8465:8465'
            - '8466:8466'
            - '8470:8470'
            - '8475:8475'
            - '8476:8476'
            - '8480:8480'
            - '8485:8485'
            - '8486:8486'
            - '8490:8490'
            - '8495:8495'
            - '8496:8496'
        env_file: azuracast.env
        environment:
            LANG: '${LANG:-en_US.UTF-8}'
            AZURACAST_DC_REVISION: 14
            AZURACAST_VERSION: '${AZURACAST_VERSION:-latest}'
            AZURACAST_SFTP_PORT: '${AZURACAST_SFTP_PORT:-2022}'
            NGINX_TIMEOUT: '${NGINX_TIMEOUT:-1800}'
            LETSENCRYPT_HOST: '${LETSENCRYPT_HOST:-}'
            LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL:-}'
            PUID: '${AZURACAST_PUID:-1000}'
            PGID: '${AZURACAST_PGID:-1000}'
        volumes:
            - 'letsencrypt:/etc/nginx/certs'
            - 'letsencrypt_acme:/etc/acme.sh'
            - 'www_uploads:/var/azuracast/uploads'
            - 'station_data:/var/azuracast/stations'
            - 'shoutcast2_install:/var/azuracast/servers/shoutcast2'
            - 'geolite_install:/var/azuracast/geoip'
            - 'sftpgo_data:/var/azuracast/sftpgo/persist'
            - 'backups:/var/azuracast/backups'
            - 'db_data:/var/lib/mysql'
        restart: unless-stopped
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        logging:
            options:
                max-size: 1m
                max-file: '5'
volumes:
    db_data: {  }
    letsencrypt: {  }
    letsencrypt_acme: {  }
    shoutcast2_install: {  }
    geolite_install: {  }
    sftpgo_data: {  }
    station_data: {  }
    www_uploads: {  }
    backups: {  }

**Comment by ncfernan** [comment]
Exactly the same here. Updated today. Tried twice in a row.

![image](https://user-images.githubusercontent.com/10008844/166154782-2f8e44f9-5541-4226-b601-101068d209f5.png)


[azura_files.zip](https://github.com/AzuraCast/AzuraCast/files/8599294/azura_files.zip)

Going back with full VM backup... again (twice today)

**Comment by SlvrEagle23** [comment]
@ncfernan Did you see the pinned discussion about changes to `docker-compose.yml`? You should follow the instructions here: https://github.com/AzuraCast/AzuraCast/issues/5191

**Comment by ncfernan** [comment]
@SlvrEagle23 Yes, I followed the instructions on #5191 and commented in that thread 25 days ago. I'll try again now and let you know. Thanks

**Comment by ncfernan** [comment]
It's working now, following the #5191 instructions.

As I have a multi-site installation, all my websites became unreachable after the update. I learned that the "azuracast_frontend" changed to "azuracast_default", and now all sites are back. Maybe a little reminder about the network name change in that same WordPress example page would help.

Thank you.
