### ISSUE TITLE
After last update the stations wont start up again

### ISSUE THREAD

**Issue by HvidstenMediaNO** [AzuraCast/AzuraCast#5294]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Release #a71d3b3 (2022-04-14 1:06)

### What happened?

The stations wont start up again...

### Relevant log output

```shell
Error 3: Syntax error!
At /var/azuracast/stations/country/config/liquidsoap.liq, line 79, char 16:
playlist_a-liste = playlist(id="playlist_a-liste",mime_type="audio/x-mpegurl",mode="randomize",reload_mode="watch","/var/azuracast/stations/country/playlists/playlist_a-liste.m3u")

Error 3: Syntax error!
```

**Comment by HvidstenMediaNO** [comment]
Heres Liquidsoap logg....

https://pastebin.com/NHuswjkR

**Comment by HvidstenMediaNO** [comment]
Fixed it.... :)

**Comment by bjarn** [comment]
Hi @HvidstenMediaNO, what is it you have done to fix it? Experienced this issue too as of updating last night. Haven't tried the latest commit, is that the one who fixed it?

**Comment by HvidstenMediaNO** [comment]
yes i tried to update once more and vipps :)



*Med vennlig hilsen*

*Thor Arne Hvidsten*

Daglig Leder

*Hvidsten Media *- Din Media Partner | M: +47 92 30 10 30

***@***.*** - https://hvidstenmedia.no/



                     *Din leverandør av Digitale og Audiovisuelle
tjenester...*


Informasjonen i denne e-postmeldingen er utelukkende ment for adressaten.
Det er forbudt for andre enn adressaten å bruke eller videreformidle
informasjonen. Hvis du mottar denne meldingen ved en feil, ber vi deg
informere avsenderen umiddelbart ved å returnere meldingen og deretter
slette den. Hvidsten Media fraskriver seg ethvert ansvar for feilsendt
e-post.


tor. 14. apr. 2022 kl. 11:47 skrev Bjarn Bronsveld ***@***.***

**Comment by bjarn** [comment]
Awesome, just updated, fixed here too! Great work and thanks again @SlvrEagle23 <3!
