### ISSUE TITLE
The playback stops after about 4 minutes

### ISSUE THREAD

**Issue by weiszmatyi** [AzuraCast/AzuraCast#5295]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### What happened?

Hi!

I have recently started using AzuraCast. Unfortunately in all cases (on all mount points) the playback stops after about 4 minutes. 
Anyone have any ideas? The stream does not restart.

Thank you!

**Comment by weiszmatyi** [comment]
I forgot to write that only playback stops. So pressing the play button will restart playback immediately afterwards.

**Comment by Vaalyn** [comment]
Are your mount points all using `ogg` as the audio format?

**Comment by weiszmatyi** [comment]
No, I use mp3, because that's the format that all players support and that's what I'm used to.
I don't think it should stop after 4 minutes. :D

**Comment by Vaalyn** [comment]
Okay, it was asking because for a long time browsers (Chrome specifically) had issues with the ogg format were they identified a track change / metadata change as "oh the track ended, let's stop playback".

If your playback stops with MP3 that's quite unusual.

Please post some information about what browser you are using as well as any errors that your browsers JS console shows to you when the playback stops (open the JS console on the player page, let it play until it stops and copy&paste any errors here).

If possible please also post a link to your public player page so I can check from my end too.

**Comment by weiszmatyi** [comment]
I use the latest Google Chrome browser.

The console remained completely blank, no errors were reported:
![image](https://user-images.githubusercontent.com/93072148/163566953-fe999b9d-b0c6-48f4-a885-117c59a01066.png)

The player:
[http://stream.szunet-radio.hu:8000/mainstream.mp3](http://stream.szunet-radio.hu:8000/mainstream.mp3)
In all cases it stops around 4 minutes 10 seconds. It looks like the stream is interrupted, but that is not what happens.

**Comment by SC2Mitch** [comment]
Can you provide us some Liquidsoap logs from your station? Might give us a indication as to what's going on and if the service is crashing unexpectedly.

**Comment by Vaalyn** [comment]
Not sure what's happening there (see screenshot) the stream just ends being sent to the browser.

Some logs from Icecast and Liquidsoap could help here.

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/13745863/163580132-c928a0b3-d474-492b-a045-3c184a8dd114.png">

**Comment by weiszmatyi** [comment]
You can find the log here: 
http://stream.szunet-radio.hu/station/1/logs/view/liquidsoap_log

By the way, all mount points have this problem.
For example this stream is Auto DJ: [http://stream.szunet-radio.hu:8000/z_backup192.mp3](http://stream.szunet-radio.hu:8000/z_backup192.mp3)
And this one is relaying another server: [http://stream.szunet-radio.hu:8000/mainstream.mp3](http://stream.szunet-radio.hu:8000/mainstream.mp3)

Thanks in advance for your help.

**Comment by Vaalyn** [comment]
> You can find the log here: http://stream.szunet-radio.hu/station/1/logs/view/liquidsoap_log I hope it will be appropriate in this form. I'm not very familiar with Azuracast yet.

We do not have access to pages that require a login 😉 

Please copy and paste the log into something like [pastebin](https://pastebin.com/) and send us a link.
Or put them into a `.txt` file and upload that directly here in a new comment

**Comment by weiszmatyi** [comment]
Oh, that's right. :D

https://pastebin.com/k0EthWqh

**Comment by weiszmatyi** [comment]
The problem was solved by reinstallation. 
Thanks for your help anyway!
