### ISSUE TITLE
Cloning a station doesn't copy audio files in some situations

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#5298]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #1c4278e

### What happened?

When attempting to clone a station while using the `playlists` function, it does not process the files (I checked after the recording and waited 30+ minutes, didn't process, nor was there any pending media queues) 

When attempting to clone a station with no fields, just clone the station and media, it does not clone the media, leaving a blank station. (Unsure if this is intended?)
https://user-images.githubusercontent.com/29955942/163657659-1a257ede-65b1-4dc5-9c0a-f3d096bd211a.mp4

**Comment by SlvrEagle23** [comment]
@SC2Mitch Having trouble reproducing this...in the latest Rolling, it has the option to "share media storage location" and if you select that, it just uses the same media storage location for both stations, which means there's no reprocessing involved, it just shares that pool of media immediately (and the media's still processed from the first station).

**Comment by SC2Mitch** [comment]
So, I done some more testing, and this is providing incredibly hard to repro reliably, I'm getting either these edge cases

Case 1#
Playlists Ticked only
Media copies over normally but remains stuck on processing, Playlists are copied normally

Case 2# 
Playlists Ticked Only
Media is not copied over, Playlists are copied normally

Case 3# 
Playlists Ticked Only
Media is copied successfully, Playlists are copied normally


I did check the Docker logs, but no conclusive errors was shown, I'm up for closing this, due to how hard this to reproduce, this could possibly be a issue with my localhost, but I don't believe it is.

**Comment by SlvrEagle23** [comment]
I'm having trouble reproducing it with any settings I try. The thing with the "share media storage location" setting is that it should just point both stations at the exact same storage location, and it's that storage location that has the media associated with it, not the station, so none of that media should need reprocessing. That was the whole point of us implementing that "Storage Location" paradigm in the first place.

I'm tempted to close now on account of difficulty in reproducing, but if you find a reliable way to demonstrate the error in the future, by all means reopen or remake the issue.
