### ISSUE TITLE
Schedule view not works when some playlist is sheduled crossing midnight

### ISSUE THREAD

**Issue by cjuniorfox** [AzuraCast/AzuraCast#530]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Ubuntu 16.04

**Describe the issue in full detail, including screenshots if possible:**

If some playlist is scheduled crossing midnight, the schedule view doesn't work. Looking into debugging window, fells like you're using some time and date plugin, and it's setting always 1/1/2018 as date.
If some list is scheduled between 11:30PM and 12:30AM, he tryes to use this plugin passing time and date starting 1/1/2018 - 11:30 PM and ending 1/1/2018 - 12:30 AM. This is impossible and throws a exception hanging the functionality.
This list scheduled crossing midnight is on my timezone (GMT -3).

**Comment by SlvrEagle23** [comment]
@cjuniorfox I've updated the playlist display code, so it should handle events that wrap over midnight better. Try it out and let me know.
