### ISSUE TITLE
An Update Error: fatal: unsafe repository (Ansible)

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#5301]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

latest

### What happened?

Hi everyone;

I encountered an interesting error while updating Azuracast. Azuracast says git library is not secure. How can I fix the problem according to the logs below?

### Relevant log output

```shell
Updating AzuraCast (Environment: production, Update revision: 75)
fatal: unsafe repository ('/var/azuracast/www' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /var/azuracast/www
fatal: unsafe repository ('/var/azuracast/www' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /var/azuracast/www
```

**Comment by SlvrEagle23** [comment]
@ogrenci01 It should be completely safe to run that command:

```bash
git config --global --add safe.directory /var/azuracast/www
```

**Comment by ogrenci01** [comment]
Hi @SlvrEagle23 

Thanks a lot. I run this command. Close issue.
