### ISSUE TITLE
Scheduled playlist does not relay URL

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#5311]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.15.2

### What happened?

I configure the playlist to relay a url from another radio and configure the schedule, but it doesn't work, the playlist is simply ignored and nothing happens. I've already tested several urls including the Azuracast itself and it doesn't work. Below is an image where the fields in red are the ones I configure. Am I doing something wrong?
Note: Scheduled playlists with songs play normally, only the ones that are configured to relay another url do not work.
![Capturar](https://user-images.githubusercontent.com/58113324/164999750-d46cfbab-e62f-4e1c-87ff-5c30171018b9.JPG)

**Comment by PManuel1986** [comment]
I have the same problem
