### ISSUE TITLE
Digital Ocean 1-click installer not working

### ISSUE THREAD

**Issue by Bazzy-B** [AzuraCast/AzuraCast#5315]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

latest stable

### What happened?

Commenced the 1-click installer process from the Digital Ocean Marketplace, waited for the droplet to finish setting up. 
Went to the public IP for the droplet once it became available, browser can't reach the site. 

The description on the DO marketplace states that I should be able to setup/configure the station from this link [which I have done in the past] however I am unable to this time.

**Comment by FynnZW** [comment]
Same as #5063. Why was that issue closed? It is not fixed.
I know this is open source, don’t expect too much and all that, and I’m grateful for the work people put in. but it is a **1-click-installer**. Why not verify with one click if the issue is resolved?

**Comment by SC2Mitch** [comment]
I'll raise it up with the team to see if we can get to the bottom of this. 

The last issue was closed because the issue the OP reported was resolved and is a entirely different issue to this one.
