### ISSUE TITLE
Switch to OAuth for Dropbox tokens due to forced expiration of tokens

### ISSUE THREAD

**Issue by MannyJMusic** [AzuraCast/AzuraCast#5316]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

**Issue**:  Auto DJ and Playlist fail due to missing remote media files

**Root Cause:** When using Dropbox as a storage location for Media or other files, generating a token from the App Console in Dropbox is only temporary.

When the token expires, all media is not reachable unless you go back and generate another token.  

**Recommended Solution**:  

According to [this dropbox issue](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/API-access-token-expired/td-p/363473
) :

 When generating a token from the Drobox App Console, it is prefix with an "sl".  This indicated the token is only temporary and to be used for development purposes.  This means if your app is not in production status, you cannot generate a permanent one
from the app console.

To fix this, an in-App Authorize button or Oauth workflow should be implemented on the front end.

System Administration -> Storage Locations -> Remote -> Dropbox.  

This would generate a permanent token that can be managed from the app console.   

Another option is that rather than, enter just the token, a user could provide and API ID and Secret to make the connection.

I would be happy to work on this issue and contribute to the code base.  See attached file.

Manny

![Snag_892bdf1](https://user-images.githubusercontent.com/79352500/165363185-4c3cfb6a-e332-44af-937e-e2d9417747af.png)

**Comment by Vaalyn** [comment]
It seems like Dropbox removed the ability to have an access token on a dev app set to have no expiration.
When we implemented this and for quite a long time this was possible to do.

We should definitely look into OAuth for Dropbox Storage then.
From a cursory glance at the Flysystem Dropbox library as well as the Dropbox API library they can already work with an access key + secret. We'd probably need to implement the initial OAuth request flow on our end and an automatic refresh task for the token.

**Comment by SlvrEagle23** [comment]
@Vaalyn The Dropbox API client also lets you authenticate with an App Key and App Secret, both of which are assigned to apps created on Dropbox as well. This will likely be the thing we have to do for this situation, just switching to those credentials, because implementing oauth consumption will be a huge pain since each of our installations will have to be their own fully registered app with oauth endpoints and such.

**Comment by ComputerComa** [comment]
Hi, I was just curious if there is any updates for this or if there is a workaround that I could implement to bypass the short lived access tokens. Thanks for the incredible work guys!

**Comment by BusterNeece** [comment]
Update: After playing with the app key/app secret option, we've discovered that this won't work for our needs, as it doesn't properly authenticate you to Dropbox in a way that lets you make filesystem calls.

We are not in a position currently to implement a full OAuth client workflow for Dropbox storage locations. If there is enough interest in it from our community, it's possible we can look into this further, but it's likely to be somewhat more technically complicated and difficult for our users than we'd like.
