### ISSUE TITLE
Allow the ability to edit liquidsoap.liq

### ISSUE THREAD

**Issue by nickdodd25** [AzuraCast/AzuraCast#532]
As the title says, allow advanced users to edit liquidsoap.liq config file. As it is now the file is overwritten at every restart of azuracast. The Advanced: Custom Configuration feature is pretty limited on what you can do.

**Comment by SlvrEagle23** [comment]
@nickdodd25 The problem with this, of course, is that AzuraCast wants to automatically generate multiple portions of the `liquidsoap.liq` file, so figuring out how to reconcile the sections it writes with the custom sections would be an interesting challenge. I've only really seen it approached by one other piece of software, namely cPanel, in how they allow editing of the configuration file but "ghost out" any lines that the software itself manages and would overwrite.

The current "advanced configuration" drops code into the most commonly overwritten spot, after the station has been composed fully but before it has been broadcast out to the frontends. This allows for custom equalization and integration of custom playlists and has generally been sufficient for many advanced use-cases, without overcomplicating things too much.

**Comment by macbroadcast** [comment]
Great @SlvrEagle23 thanks for the answer , i tested with an simple snippet to try out liquidsoaps functionality . `# add a jingle every full hour
# jingle = single("/home/var/azuracast/stations/bayradio/media/jingles/20_bay_radio_copy_5.mp3")
# add([stream,switch([({0m0s},jingle)])])` but it doesnt seems to work, is the home/var? path correct or just /var/ and so on ?

**Comment by aldorr** [comment]
That seems like the best idea, to insert configuration parameters in a "safe" spot.

I also tested configuring liquidsoap based on the example in the Wiki:
```
radio = rotate(weights=[1,1,5], [mksafe(playlist_default), playlist_ilka_hoffmann_interview_and_tracks, playlist_georg_krefeld_interview_and_tracks])
```
(Here, it seems like the weights should be [5,1,1]. But got similar results for both.)

And the API Documentation:
```
radio = rotate(weights=[1, 1, 5],[playlist_ilka_hoffmann_interview_and_tracks, playlist_georg_krefeld_interview_and_tracks, radio])
radio = fallback(track_sensitive = false,[radio, playlist_default])
```

This doesn't get the desired results; that the first two playlists should play one after the other, and the general radio stream should play otherwise.

Plus, once I add any settings in the Advanced Custom Configuration, the song duration no longer shows up in my player... and when I look at the response from the API, it shows a `nowplaying: duration : 0`
That's funny.

Will have to do some more testing. Where can we get/see the current liquidsoap.liq configuration file being used? Maybe that would shed some light on things.

**Comment by SlvrEagle23** [comment]
@aldorr Per #891, you can now view the full automatically generated `liquidsoap.liq` file in the new Log Viewer page, under "Utilities" on each station. Users will need to either be station administrators or have the "view station logs" permission to see this page, as it can contain sensitive information.

The enhancement request in question from this thread has not yet been implemented, as it would basically bypass a huge section of AzuraCast's functionality and if it's going to be done at all, I want it to be done cleanly and easily reversibly.

**Comment by aldorr** [comment]
@SlvrEagle23 Thanks!
Looks like I'll have to update, but then I'll check it out.
I was at least able to see what was changing in the `liquidsoap.liq` file within the container.
I'll start another thread about the odd _elapsed_ and _remaining_ responses when using the **Advanced Custom Configuration**.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39033/add-more-editable-locations-in-liquidsoapliq

**Comment by rmacari** [comment]
Sorry to bump this again, but I can't find the liquidsoap conf editor field anymore. Was that removed or moved?
Thanks.

**Comment by BusterNeece** [comment]
@rmacari It wasn't moved, it's just under "Broadcasting" now as its own more full-featured editor.
