### ISSUE TITLE
Listeners report shows internal IP when using nginx reverse proxy

### ISSUE THREAD

**Issue by luuk58** [AzuraCast/AzuraCast#5330]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.16.0 Stable, Docker, PHP 8.1 

### What happened?

Since updating from 0.15.2 to 0.16.0, all listeners show up with the internal IP address of my nginx proxy. Before updating, the correct IP address was shown.

I have tried restarting the docker service as that seemed to work in other bug reports, but unfortunately it didn't work for me.

My nginx configuration:
```
proxy_pass http://localhost:28000;
client_max_body_size 0;
chunked_transfer_encoding on;
proxy_buffering off;
proxy_request_buffering off;
proxy_http_version 1.1;
proxy_pass_request_headers on;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
```
Listeners report:
<img width="1100" alt="Listeners report" src="https://user-images.githubusercontent.com/7101239/166147240-fb03ff98-b0e0-43b3-a981-a0a3d4af0891.png">

**Comment by messkaline** [comment]
I have the same issue. some it shows original IP for some client, but some have docker proxy internal IP. Nginx configured to pass IP like:

```
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
```

not sure what it depends...

<img width="1064" alt="Screenshot 2565-05-15 at 02 58 59" src="https://user-images.githubusercontent.com/1375849/168446717-31eeb17e-c9f9-44bb-839c-e705fff561af.png">

**Comment by luuk58** [comment]
My AzuraCast shows the internal IP address regardless of the user agent. So maybe a different cause for the same problem?

As a quick but ugly fix to at least get accurate unique listener statistics, I have added the IP to the user agent in Nginx. Not really a solution, but at least every unique listener gets counted 🙂

```
set $new_user_agent "IP: $remote_addr - UA: $http_user_agent";
proxy_set_header User-Agent $new_user_agent;
```

**Comment by SC2Mitch** [comment]
I'll raise this up with the team, see what we can do.

**Comment by adoboligh1** [comment]
Simple, do not proxy directly to icecast..

Icecast : 1.1.1.1.1:8000/

do instead.

1.1.1.1.1:Azura-Port/radio/8000/Mount_point

eg. 1.1.1.1.1:3829/radio/9000/radio.mp3

**Comment by Vaalyn** [comment]
If you use your own proxy to directly proxy to Icecast this behaviour is to be expected since trusting every proxy by default is insecure so Icecast ignores the `X-FORWARDED-FOR` header for proxy IPs that it doesn't have in it's list for trusted proxies.

You'll have to manually extend the following config to include the IP of your proxy in addition to the `127.0.0.1` via the `Edit Station Profile` -> `BROADCASTING` -> `Custom Configuration`:
```
<paths>
    <x-forwarded-for>127.0.0.1</x-forwarded-for>
</paths>
```

**Comment by messkaline** [comment]
ho! it works!!

but,actually,  in my case the solutions is

```
<paths>
    <x-forwarded-for>172.18.0.1</x-forwarded-for>
</paths>
```

**Comment by Vaalyn** [comment]
> ho! it works!!
> 
> but,actually, in my case the solutions is
> 
> ```
> <paths>
>     <x-forwarded-for>172.18.0.1</x-forwarded-for>
> </paths>
> ```

Like I said you need to `extend the config` not copy and paste what I posted 😉 

Glad it's working for you now 👍

**Comment by luuk58** [comment]
Adding the internal ip to the x-forwarded-path works, thank you @Vaalyn!

When using 0.15.2 the proxied ips were logged correctly, without the need for this custom Icecast configuration. Any idea what changed with the update to 0.16.x?

**Comment by Vaalyn** [comment]
> Adding the internal ip to the x-forwarded-for path works, thank you @Vaalyn!
> 
> When using 0.15.2 the proxied ips were logged correctly, without the need for this custom Icecast configuration. Any idea what changed with the update to 0.16.x?

The internal IP ranges that Docker uses were previously put into the `x-forwarded-for` config since Icecast was running in a different container than the nginx. With 0.16.x we unified the containers into a single one so in the standard setup this wasn't needed anymore which is why it was removed.

The default ranges we set previously were those 2 values:
`172.*.*.*`, `192.*.*.*`
