### ISSUE TITLE
play immediately error: Telnet failure: Connection refused (111)

### ISSUE THREAD

**Issue by YosefAdPro** [AzuraCast/AzuraCast#5333]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #97aaaa3 (2022-05-01 7:02) • Docker • PHP 8.1

### What happened?

The new function added does not seem to work and gives an error:

`Telnet failure: Connection refused (111)`

**Comment by SC2Mitch** [comment]
Thanks, we're aware, will fix shortly.
