### ISSUE TITLE
Error 502 bad gateway

### ISSUE THREAD

**Issue by iplayradionetworks** [AzuraCast/AzuraCast#5336]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.16

### What happened?

I am having a problem after the latest update.

Followed all instructions carefully... I used to have an override file but now its not needed so i removed it. No worries but after update finished i am getting 502 Bad Gateway for the WEB GUI panel.... the radios tho work just fine.

What can the problem be ? Any ideas please ? I have people that cannot login to their panel.

Please help.

Jim

### Relevant log output

```shell
I haven't got any output from a log yet.
```

**Comment by SC2Mitch** [comment]
We'll need some docker logs for this, this can be done by running `docker-compose logs -f` in the /var/azuracast directory.

**Comment by iplayradionetworks** [comment]
> We'll need some docker logs for this, this can be done by running `docker-compose logs -f` in the /var/azuracast directory. 

Hi . Thank you for your reply. I will run this command now and write a new reply. I guess that command won't affect running streams while being active yes ?

**Comment by iplayradionetworks** [comment]
azuracast  |  [OK] Local cache flushed.
azuracast  |
azuracast  |
azuracast  |  [OK] AzuraCast is now initialized.
azuracast  |
azuracast  | [ERROR] unable to bind listening socket for address '127.0.0.1:9000': Address already in use (98)
azuracast  | [ERROR] FPM initialization failed
azuracast  | 2022/05/02 16:21:26 [error] 256#256: *152931 connect() failed (111: Connection refused) while connecting to upstream, client: 94.70.243.194, server: localhost, request: "GET /radio/8028/ HTTP/1.0", upstream: "http://127.0.0.1:8028/?", host: "cast.iplayradio.net"
azuracast  | 2022-05-02 16:21:26 43872 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
azuracast  | mysqladmin: connect to server at 'localhost' failed
azuracast  | error: 'Access denied for user 'root'@'localhost' (using password: NO)'
azuracast  | ok: run: mariadb: (pid 92) 22802s
azuracast  | ok: run: redis: (pid 87) 22802s
azuracast  | 2022/05/02 16:21:26 Command finished successfully.
azuracast  | 2022/05/02 16:21:26 [error] 256#256: *152933 connect() failed (111: Connection refused) while connecting to upstream, client: 94.70.243.194, server: localhost, request: "GET /radio/8028/ HTTP/1.0", upstream: "http://127.0.0.1:8028/?", host: "cast.iplayradio.net"
azuracast  | Starting up AzuraCast services...
azuracast  | 2022-05-02 16:21:26 43873 [Warning] Aborted connection 43873 to db: 'azuracast' user: 'azuracast' host: 'localhost' (Got an error reading communication packets)
azuracast  | Services started up and ready!
azuracast  |
azuracast  | Initialize AzuraCast
azuracast  | ====================
azuracast  |
azuracast  | Initializing essential settings...
azuracast  |  * Environment: Production
azuracast  |  * Installation Method: Docker
azuracast  |
azuracast  |
azuracast  | Running Database Migrations
azuracast  | ---------------------------
azuracast  |
azuracast  | 2022/05/02 16:21:27 [error] 256#256: *152935 connect() failed (111: Connection refused) while connecting to upstream, client: 94.70.243.194, server: localhost, request: "GET /radio/8028/ HTTP/1.0", upstream: "http://127.0.0.1:8028/?", host: "cast.iplayradio.net"
azuracast  |
azuracast  |  [OK] Already at the latest version
azuracast  |       ("App\Entity\Migration\Version20220421123900")
azuracast  |
azuracast  |
azuracast  | Generating Database Proxy Classes
azuracast  | ---------------------------------
azuracast  |
azuracast  | 2022/05/02 16:21:27 [error] 256#256: *152937 connect() failed (111: Connection refused) while connecting to upstream, client: 94.70.243.194, server: localhost, request: "GET /radio/8028/ HTTP/1.0", upstream: "http://127.0.0.1:8028/?", host: "cast.iplayradio.net"
azuracast  |
azuracast  |  Processing entity "App\Entity\StorageLocation"
azuracast  |  Processing entity "App\Entity\StationMedia"
azuracast  |  Processing entity "App\Entity\StationStreamerBroadcast"
azuracast  |  Processing entity "App\Entity\Podcast"
azuracast  |  Processing entity "App\Entity\StationPlaylistMedia"
azuracast  |  Processing entity "App\Entity\StationPlaylist"
azuracast  |  Processing entity "App\Entity\AuditLog"
azuracast  |  Processing entity "App\Entity\Listener"
azuracast  |  Processing entity "App\Entity\Analytics"
azuracast  |  Processing entity "App\Entity\PodcastCategory"
azuracast  |  Processing entity "App\Entity\StationSchedule"
azuracast  |  Processing entity "App\Entity\Settings"
azuracast  |  Processing entity "App\Entity\SftpUser"
azuracast  |  Processing entity "App\Entity\CustomField"
azuracast  |  Processing entity "App\Entity\StationPlaylistFolder"
azuracast  |  Processing entity "App\Entity\User"
azuracast  |  Processing entity "App\Entity\StationMediaCustomField"
azuracast  |  Processing entity "App\Entity\Station"
azuracast  |  Processing entity "App\Entity\SongHistory"
azuracast  |  Processing entity "App\Entity\UnprocessableMedia"
azuracast  |  Processing entity "App\Entity\Relay"
azuracast  |  Processing entity "App\Entity\StationQueue"
azuracast  |  Processing entity "App\Entity\Role"
azuracast  |  Processing entity "App\Entity\StationWebhook"
azuracast  |  Processing entity "App\Entity\PodcastEpisode"
azuracast  |  Processing entity "App\Entity\StationStreamer"
azuracast  |  Processing entity "App\Entity\StationRequest"
azuracast  |  Processing entity "App\Entity\StationRemote"
azuracast  |  Processing entity "App\Entity\RolePermission"
azuracast  |  Processing entity "App\Entity\UserLoginToken"
azuracast  |  Processing entity "App\Entity\PodcastMedia"
azuracast  |  Processing entity "App\Entity\ApiKey"
azuracast  |  Processing entity "App\Entity\StationMount"
azuracast  |
azuracast  |  Proxy classes generated to "/var/azuracast/www_tmp/proxies"
azuracast  |
azuracast  | Reload System Data
azuracast  | ------------------

**Comment by iplayradionetworks** [comment]
Since there is no reply yet.... i moved on as clients cannot wait that much.... I made a full backup of AzuraCast with all mp3 files. WIll now proceed into uninstalling and re-install again. After i will make a restore from the backup. Hope that will fix my issue. 

Thank you team for your help...............................................................................................
