### ISSUE TITLE
live api does not work after a certain time

### ISSUE THREAD

**Issue by djbenbe** [AzuraCast/AzuraCast#5349]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.16.1

### What happened?

best,

after a certain time the live API drops out.
via this link api/live/nowplaying/.....
We then have to reboot the entire platform for it to work again.

Sincerely,
ben

**Comment by SC2Mitch** [comment]
hi, we'll need some logs, or a way to reproduce this. this current report is incredibly vague and will be hard to reproduce without any sort of detailed information.

**Comment by djbenbe** [comment]
I've searched the log all the time but we don't find anything that looks like an error with api

**Comment by SC2Mitch** [comment]
When the API 'stops working', what happens, can you not access it? What happens exactly

**Comment by djbenbe** [comment]
we get an error that the page does not exist

**Comment by SC2Mitch** [comment]
Okay, when this error happens, you should be able to check the docker logs and it should print back a error or anything useful. Should this happen again, feel free to send over a docker-compose logs -f file so we can check it.
