### ISSUE TITLE
liquidsoap is unable to play music files from docker bind mount

### ISSUE THREAD

**Issue by calne-ca** [AzuraCast/AzuraCast#535]
- **Installation Method:** Docker
- **Host OS:** Ubuntu 16.04

I've setup AzuraCast on an EC2 instance and wanted to use an EFS mount for storing the music files. I tried this by adding this line to the docker-compose file under services: web: volumes

\- */efs/music:/var/azuracast/music*
(*/efs/music* being my EFS mount on the host machine)

and then set */var/azuracast/music* as media directory of the station. I can see the files in the web gui and I can even play them directly but when I add them to a playlist and let liquidsoap play them it's not working at all. After looking in the docker logs I saw this line being constantly spammed for all music files in the playlist:

stations_1  | 2018/04/02 12:25:43 [request:3] **Nonexistent file or ill-formed URI** "/var/azuracast/music/jp/vocaloid/rice_records/social_zombie/03._tangram.mp3"!

Of course this file does exist and is accessible by the azuracast user since I can play them directly from the music files menu; I also confirmed it by using docker exec both in the web and cli container. This problem only occurs when using a bind mount as media directory, when using any other directory it works perfectly fine.

I sat here for hours trying to figure out what the problem is but I can't find a solution.

**Comment by SlvrEagle23** [comment]
@calne-ca If you're using a custom volume for station data, you should make sure to add it to all of the following services:

* web
* cron
* cli
* stations

The music playback via Liquidsoap actually happens from within the `stations` controller, which has its own filesystem for reference that differs from the `web` container's, but you can map the same directory to both without any trouble.

**Comment by calne-ca** [comment]
@SlvrEagle23 Ah, of course, that makes sense. The log message even said stations_1 >_>
I just assumed they all use the same volumes since cli and cron include the volume config from web with volume_from. But station actually doesn't.

It works now, thank you!
