### ISSUE TITLE
api/nowplaying return empty array without athorization

### ISSUE THREAD

**Issue by vneznaikin** [AzuraCast/AzuraCast#5352]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #c4deb40 (2022-05-04 10:30)

### What happened?

If I log in api work correct, but after log out api/nowplaying return empty array
api/nowplaying/{station_id} work correct

in AzuraCast v0.13.0 Stable - work without problem

---------------------
By the way:
also maybe swagger is broken in last rolling realise
api/nowplaying/{station_id} asks for an object instead of ID or Name how it was before.
but {"stationed_id":1} not working
and why is the lock icons always unlocked? I don't understand this logic. When I add API key, icons goes to loked. after page refresh it's again unlocked...
Bug or work as designed?

**Comment by Sakretsos** [comment]
Hello @vneznaikin, 
try to use Postman for the API calls.

**Comment by vneznaikin** [comment]
@Sakretsos I didn't understand. Why do you need Postman? How will this fix the bug?

**Comment by vneznaikin** [comment]
@Vaalyn yes. I use my own player.
How can I access this API node through my player? Can you provide an example or link to documentation? Thx

**Comment by vneznaikin** [comment]
If the only way is to enable public pages, give me a reason why it should work that way. Maybe we should separate public pages logic and API logic? Some additional checkbox in the Station Profile settings for example...

**Comment by vneznaikin** [comment]
@SC2Mitch thx for the conversation. I'll think of a better way
