### ISSUE TITLE
Error in custom Port Range - version 0.16.1

### ISSUE THREAD

**Issue by youngdesenv** [AzuraCast/AzuraCast#5354]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.16.1

### What happened?

After update to 0.16.1, with custom port range, has no possible to start AzuraCast. Error:

Service stations has neither an image nor a build context specified. At least one must be provided.

**Comment by SC2Mitch** [comment]
If you're using a custom docker-compose override then please up date it, we have a issue pinned for more information. 

https://github.com/AzuraCast/AzuraCast/issues/5191

**Comment by SC2Mitch** [comment]
When you run a update, you can manually configure your station ports, removing the requirement for the override part. This isn't a bug with us, please update your override accordingly.
