### ISSUE TITLE
 processing file

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#5376]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

roling release

### What happened?

Good morning people!
I'll expose my doubt again, maybe you haven't seen it...

"Hello, I don't know if it's working with azuracast or not, but I'm testing the S3 and I notice that if I send the files through the S3 platform or directly from the browser, the azuracast recognizes the audios quickly, now if I send it by SFTP it seems that it is not recognizing, it has a status of processing file and does not work. If you create a link through s3fs-fuse it doesn't work either. allow azuracast to use the files.
I checked the permissions and they are all ok."

### Relevant log output

```shell
2022/05/12 11:06:31 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:9010/api/internal/271/liquidsoap/nextsong' with body:
5/12/2022 11:06:31 [lang:3] nextsong API - Response(200): false
```

**Comment by SC2Mitch** [comment]
I did ask you to provide the files on Discord, but they was never sent so I wasn't able to review.

If you can send them, I'll have a look.

**Comment by Marcioghiraldelli** [comment]
the error also happens if you use s3fs fuse .

**Comment by julianborghuis** [comment]
same error looks like also when switching back to local storage you need to restart azuracast to work processing files again
#5398
