### ISSUE TITLE
Current Song meta and Image are not updating

### ISSUE THREAD

**Issue by amavarick** [AzuraCast/AzuraCast#538]
Docker
Ubuntu 16.04.4 LTS
Most recent AzuraCast Code Deployment

Connecting to the Icecast stream, songs play and rotate properly...
However on the Azuracast web pages and my iframe player, they do not update the song or artwork properly.  Clicking on play will play the current song though.  Please see documentation below.  Let me know if I can provide additional validation.

AzuraCast...    /station/1/profile
Once the current song finishes, there is no update, the same song remains indefinitely
![image](https://user-images.githubusercontent.com/20918832/38394681-7427c5ce-38fd-11e8-84c4-6026c255be49.png)

AzuraCast Public Radio Page:
![image](https://user-images.githubusercontent.com/20918832/38394851-120b0b5c-38fe-11e8-9211-3aed93827de0.png)

Embedded iframe on my radio site:
![image](https://user-images.githubusercontent.com/20918832/38394894-45bfbe5c-38fe-11e8-9e44-a8fe8f693fd7.png)

![image](https://user-images.githubusercontent.com/20918832/38394927-7f3b65b4-38fe-11e8-8297-c85abf96262a.png)

This is what appears when I browse to the art link above:
![image](https://user-images.githubusercontent.com/20918832/38394968-9dfc1ec6-38fe-11e8-8822-f963eb84d469.png)

I went to the actual song to show you that I have artwork setup properly but this seems to be a more involved issue.  Browsing to the Music Files section, I clicked on edit for the song:
![image](https://user-images.githubusercontent.com/20918832/38395181-a65206ca-38ff-11e8-92e2-a362553d43a8.png)

![image](https://user-images.githubusercontent.com/20918832/38395192-ba4578ec-38ff-11e8-8cf1-b13689aebaec.png)

**Comment by SlvrEagle23** [comment]
@amavarick This probably has something to do with the same error mentioned in #518...can you try the same fix listed there and let me know if it works? I'm also updating the updater script itself to help ensure that doesn't continue to happen.

**Comment by amavarick** [comment]
```
root@stream1:/var/tmp# cd /opt/azuracast
root@stream1:/opt/azuracast# docker-compose run --rm cli
Starting azuracast_influxdb_1 ... done
Starting azuracast_stations ... done
Starting azuracast_mariadb_1 ... done
Starting azuracast_web_1 ... done
2018/04/06 03:25:10 Waiting for: tcp://mariadb:3306
2018/04/06 03:25:10 Waiting for: tcp://influxdb:8086
2018/04/06 03:25:10 Connected to tcp://mariadb:3306
2018/04/06 03:25:10 Connected to tcp://influxdb:8086
azuracast@205e22419286:~/www$ sudo -i
root@205e22419286:~# rm -rf /var/azuracast/www_tmp/proxies
root@205e22419286:~# exit
logout
azuracast@205e22419286:~/www$ exit
exit
2018/04/06 03:27:16 Command finished successfully.
root@stream1:/opt/azuracast# ./docker-update.sh
```

After services restart from update, everything appears to be working properly!
Thank you!

**Comment by SlvrEagle23** [comment]
@amavarick Glad to hear. I'll be working to refine the updater script in the future so this doesn't tend to happen as often (probably by just wiping the `tmp_data` container upon any update, which is 100% safe to do)
