### ISSUE TITLE
No more menu

### ISSUE THREAD

**Issue by netbladenl** [AzuraCast/AzuraCast#5380]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#2ec0319

### What happened?

Since the last update, there is no menu on the profile page.

**Comment by ckeurk** [comment]
I confirm the problem

**Comment by Sakretsos** [comment]
i confirm the problem too!

**Comment by SC2Mitch** [comment]
Thanks guys, confirming

**Comment by netbladenl** [comment]
Fixed! Thanks for fixing!
