### ISSUE TITLE
Azuracast sending wrong information to Shoutcast

### ISSUE THREAD

**Issue by Countryman98** [AzuraCast/AzuraCast#5387]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

Rolling Release #c720d95

### What happened?

Can an Dev please have a look into why Azuracast is sending our site External/Wan IP to Shoucast instead of full domain name.

As Azuracast sends the listening links to Shoutcast it appends the "s" and makes the external ip secure which then shoutcast listeners cant listen to via shoutcast (which really defeats the purpose of paying for shoutcast)

Can this be corrected to use azuracast domain name and ssl cert instead?

![Capture](https://user-images.githubusercontent.com/65417549/168949096-0489a0a9-b5e7-426d-9e91-8eb19aba84e0.JPG)

![Capture1](https://user-images.githubusercontent.com/65417549/168949377-f5cc5fc2-4544-4ac7-9f0a-2d85481fd96a.jpg)

Thanks Guys!

**Comment by SC2Mitch** [comment]
I'll raise it up to the team, but this'll most likely be a low priority bug since we don't support ShoutCast.

**Comment by radiobellissima** [comment]
I wanted to know if there have been any developments regarding this issue. I am at the latest stable version but the problem still exists.

Thanks

**Comment by Countryman98** [comment]
> I wanted to know if there have been any developments regarding this issue. I am at the latest stable version but the problem still exists.
> 
> Thanks

Likewise, External IP instead of Domain Name

**Comment by rolradio** [comment]
You can quickly adjust this yourself:

Go to: Edit Profile / Broadcasting of the relevant station.
In Custom Configuration (Advanced) you enter this code:

{ "alternateports": "443", "destip": "yoursub.domain.com", "publicip": "yoursub.domain.com" }

Save and restart your radio.

**Comment by BusterNeece** [comment]
@rolradio Ah, that's what we were needing to get this fixed! I struggle to find Shoutcast documentation, but if it is possible for us to just supply an updated listening URL, we'll just do that ourselves.

**Comment by rolradio** [comment]
This is indeed the code I am using.
And works perfectly.

Using this extra code your shoutcast sc_serv.conf will look something like this (see below)
And the stream https://yoursub.domain.com:port/radio.mp3 and will also appear public in the shoutcasts directories.

**Configuration File: sc_serv.conf**

Stream Settings:

streamauthhash_1=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
streampath_1=/radio.mp3

General Settings:

adminpassword=xxxxxxxxx
agentfile=/var/azuracast/stations/yourradio/config/sc_serv.agent
alternateports=443
banfile=/var/azuracast/stations/yourradio/config/sc_serv.ban
destdns=yoursub.domain.com
destip= yoursub.domain.com
logfile=/var/azuracast/stations/yourradio/config/sc_serv.log
maxuser=100
password=xxxxxxxxxxxxxx
publicdns= yoursub.domain.com
publicip= yoursub.domain.com
requirestreamconfigs=1
ripfile=/var/azuracast/stations/yourradio/config/sc_serv.rip
saveagentlistonexit=0
savebanlistonexit=0
sslcertificatefile=/var/azuracast/acme/ssl.crt
sslcertificatekeyfile=/var/azuracast/acme/ssl.key
w3clog=/var/azuracast/stations/yourradio/config/sc_w3c.log

**Comment by BusterNeece** [comment]
Added to the latest Rolling Release!

**Comment by Countryman98** [comment]
Hmmm Buster, Still doesn't appear to be working for my instance.. Shoutcast still seeing external IP?

**Comment by radiobellissima** [comment]
@rolradio You are great. :-).
I confirm the problem has been perfectly solved with this configuration.

Thanks
Marcello
