### ISSUE TITLE
Editing a Station Profile doesn't flag errors if using different tabs. 

### ISSUE THREAD

**Issue by kieranlittle667** [AzuraCast/AzuraCast#5393]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

0074ec2 (2022-05-19 5:39) 

### What happened?

When editing a station profile, if you have an error on the basic info page, but press save from another tab e.g. auto DJ or broadcasting, you don't see the error from basic info making you think something is broken.
For example, I didn't have a full URL in the station homepage field however I didn't know as I was trying to change crossfading settings. I only found by accidently pressing save in the basic info tab.

**Comment by SC2Mitch** [comment]
Thanks for the report, was able to verify this.
