### ISSUE TITLE
url playlists are not playing again

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#5395]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

dee9278 (2022-05-20 4:50) • Docker • PHP 8.1

### What happened?

hello,
i have one playlist playing from 00pm to 06pm.
this playlist have this url: http://104.227.175.125:80/livemix
this is not working. i cant find anything in the log regarding it, simply it is ignored i believe.
previous week all was normal.
i have the option interrupt oter songs checked, but unchecked it and it doesnt plays as well.

**Comment by nunotfc** [comment]
hello,
withouth any logic reason, url started to play, at this moment!
i have my configs right, see
07:58:01 BRT
and the playlist is out of range. is from 00 to 06 only.
i cant understand how and why this appened.
in logs, again nothing regarding the url.

**Comment by nunotfc** [comment]
the bug sometimes appens, sometimes not...

**Comment by ArvyRogerio** [comment]
@nunotfc I found this topic looking for my IP on Google.
"http://104.227.175.125:80/livemix" it's my webradio Live Mix and should not be referenced by IP.
This IP will be cancelled soon. The correct URL is https://streaming.inweb.com.br/livemix
Contact us at livemix.com.br
