### ISSUE TITLE
Error restarting station from cron

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#5397]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.16.0

### What happened?

Until a couple of days ago we have been working with version 0.14.1 of Azuracast. Some stations that use the advanced playlist options needed to be restarted daily in order to update the audio files that were automatically downloaded, otherwise azuracast did not recognize these new files coming from podcast subscriptions.

To do this we used this command that was executed from cron at a certain time in the morning:

`05 17  * * 4 /usr/local/bin/docker-compose -f /var/azuracast/docker-compose.yml run --rm --user="azuracast" web azuracast_cli azuracast:radio:restart agora_sol_radio`

After updating to version 0.16.0 it has stopped working and returns this error:

![image](https://user-images.githubusercontent.com/16152034/169651448-baae4fa1-6518-4ee0-8f93-a0bf168949a5.png)

How could we solve it?

**Comment by SlvrEagle23** [comment]
@fidegr Switch from `run --rm --user="azuracast"` to `exec --user="azuracast"`

**Comment by fidegr** [comment]
Hello, thanks for the answer... from the command line it works correctly, but not from cron. Any idea where the error could be?

**Comment by SlvrEagle23** [comment]
@fidegr Cron can be very picky about how it processes commands. I don't see anything particularly wrong with that command, though you could simplify that using our utility script to:

```
bash /var/azuracast/docker.sh cli azuracast:radio:restart radio_cadenazo_libre
```

**Comment by SC2Mitch** [comment]
Closing, let us know if you got any other issues.
