### ISSUE TITLE
error, remote list

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#5401]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

OK, I've been reporting this problem for some time and so far no solution.
Remote list doesn't work if you use azuracast managed mode.
Remote list only works if you set advanced mode, auto dj managed mode outside of azuracast. That way it even enters, but when the radio ends, it freezes and doesn't follow the programming correctly. I notice that the advanced mode in the playlist doesn't work well either.

### Relevant log output

```shell
OK, I've been reporting this problem for some time and so far no solution.
Remote list doesn't work if you use azuracast managed mode.
Remote list only works if you set advanced mode, auto dj managed mode outside of azuracast. That way it even enters, but when the radio ends, it freezes and doesn't follow the programming correctly. I notice that the advanced mode in the playlist doesn't work well either.
```

**Comment by nunotfc** [comment]
#5395
