### ISSUE TITLE
Error response from daemon: unknown log opt 'max-size' for journald log driver

### ISSUE THREAD

**Issue by pbu80** [AzuraCast/AzuraCast#5402]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

tried to follow the unattended installation 

```
root@prabhu-desktop:/var# mkdir -p /var/azuracast
root@prabhu-desktop:/var# cd /var/azuracast
root@prabhu-desktop:/var/azuracast# curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/main/docker.sh > docker.sh
root@prabhu-desktop:/var/azuracast# chmod a+x docker.sh
root@prabhu-desktop:/var/azuracast# yes 'Y' | ./docker.sh setup-release
Your current release channel is 'Rolling Release'. Switch to 'Stable' release channel? [y/N] You should update the Docker Utility Script after changing release channels. Automatically update it now? [Y/n] New Docker utility script downloaded.
root@prabhu-desktop:/var/azuracast# yes '' | ./docker.sh install
Checking installation requirements for AzuraCast...
[PASS] Operating System: Linux
[PASS] Architecture: x86_64
[PASS] Command Present: curl
[PASS] Command Present: awk
[PASS] User Permissions
[PASS] Installation Directory
[PASS] All requirements met!
Docker is already installed! Continuing...
Docker Compose is already installed. Continuing...
[+] Running 1/1lease channel is 'Stable'. Switch to 'Rolling Release' release channel? [y/N]
 ⠿ installer Pulled                                                                                                                                                                     1.3s
the input device is not a TTY
[+] Running 1/1
 ⠿ web Pulled                                                                                                                                                                           1.2s
the input device is not a TTY
[+] Running 0/0
 ⠋ Container azuracast  Creating                                                                                                                                                        0.0s
Error response from daemon: unknown log opt 'max-size' for journald log driver
```

**Comment by SC2Mitch** [comment]
Not entirely sure this is an AzuraCast problem as the error relates to Docker itself. 

Have you tried the other default installation method?

**Comment by Vaalyn** [comment]
This as a problem with a setting of the Docker daemon itself.

Docker supports multiple ways to save container logs (those are called logging drivers). The default way in most cases is the `JSON File` logging driver. For this one the AzuraCast compose file definition contains a block to specify how big a single log file is allowed to be in order to prevent the logs from filling up the servers HDD.

When your Docker daemon is set to use the `Journald` logging driver instead this setting is not available / allowed to be used.

The simple solution to this problem is to switch from the Journald driver to JSON by editing the `/etc/docker/daemon.json` and changing the `"log-driver": "journald"` to `"log-driver": "json-file"`. After that simply restart the Docker daemon via `systemctl restart docker`.

**Comment by pbu80** [comment]
> This as a problem with a setting of the Docker daemon itself.
> 
> Docker supports multiple ways to save container logs (those are called logging drivers). The default way in most cases is the `JSON File` logging driver. For this one the AzuraCast compose file definition contains a block to specify how big a single log file is allowed to be in order to prevent the logs from filling up the servers HDD.
> 
> When your Docker daemon is set to use the `Journald` logging driver instead this setting is not available / allowed to be used.
> 
> The simple solution to this problem is to switch from the Journald driver to JSON by editing the `/etc/docker/daemon.json` and changing the `"log-driver": "journald"` to `"log-driver": "json-file"`. After that simply restart the Docker daemon via `systemctl restart docker`.

Thanks a lot.

**Comment by SC2Mitch** [comment]
Let us know if you keep having issues, closed.
