### ISSUE TITLE
Remote url not working

### ISSUE THREAD

**Issue by PManuel1986** [AzuraCast/AzuraCast#5404]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.15.2 Stable

### What happened?

No matter what URL I try to transfer from a remote URL, it doesn't work

**Comment by Marcioghiraldelli** [comment]
I reported the same error.

**Comment by nunotfc** [comment]
#5395

**Comment by SC2Mitch** [comment]
Duplicate of #5395
