### ISSUE TITLE
Stereo Tool installation failed with infinity load when wrong version uploaded

### ISSUE THREAD

**Issue by Sakretsos** [AzuraCast/AzuraCast#5408]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #39898b9 (2022-05-23 7:50)

### What happened?

Hello, 
i tried to install stereo tool on my test server in order to check it, well i download an wrong version of the stereo tool (the x64 bit GUI binary) and when i install it i get an error with ifinity load.
![stereo_tool](https://user-images.githubusercontent.com/8127121/169783236-427e721f-69e0-4581-92a6-7edfd0ef150d.PNG).
after i restore my backup yml and i download the correct version and installation completed successfully.

**Comment by Sakretsos** [comment]
well, this was my fail, i try to install gui version. sorry i close this ticket.

**Comment by Marcioghiraldelli** [comment]
@Sakretsos  
which version did you use?

**Comment by Sakretsos** [comment]
@Marcioghiraldelli latest one, 9.90.

**Comment by Marcioghiraldelli** [comment]
I understand, this function was implemented recently. neece should probably sort this out today or tomorrow.

**Comment by bjarn** [comment]
Ah - it tries to get the version number by executing the binary. When you install the GUI version, it will boot the GUI and then get stuck, I think.

**Comment by bjarn** [comment]
> @bjarn maybe if we set a general timeout on the Process execution like this `$process->setTimeout(5.0);` we can fix this for all of the available invalid versions that can be downloaded 🤔
> 
> We should probably also add a call to the binary on the install process itself and remove the uploaded binary if it's not valid.

Good one! Will create a PR later today :)

**Comment by Sakretsos** [comment]
@Vaalyn is it possible to help me to stop the gui version of stereo tool from my server? since my server load is now 100% and i dont know how to remove the binary file in order to upload the right one!

**Comment by Vaalyn** [comment]
> @Vaalyn is it possible to help me to stop the gui version of stereo tool from my server? since my server load is now 100% and i dont know how to remove the binary file in order to upload the right one!

Should be as simple as killing the process via `htop` for example and then removing the binary file from inside the container.

For removing the file from inside the container, access the container like this:
```
docker exec -it azuracast bash
```

Then navigate to the `/var/azuracast/servers/stereo_tool` directory and then running `rm` on the binary.

**Comment by Sakretsos** [comment]
> 

Thanks a lot!
