### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by TorchwoodPL** [AzuraCast/AzuraCast#541]
- **Installation Method:** Traditional
- **Host OS (if using Docker):** Ubuntu 16.04

**Describe the issue in full detail, including screenshots if possible:**

After update few minutes ago I get:

`2018/04/06 22:47:43 [error] 2138#2138: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 188.146.38.66, server: radio.vps.expij.pl, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "radio.vps.expij.pl"`

**Comment by SlvrEagle23** [comment]
@TorchwoodPL Did the update itself show any errors? It looks like the PHP-FPM process is giving you trouble, maybe manually restarting it via `service php7.2-fpm restart` will help?

**Comment by TorchwoodPL** [comment]
Upadte do not show any errors, also restarting do not fix problem. I get alvays 502 on enter radio.vps.expij.pl

**Comment by SlvrEagle23** [comment]
@TorchwoodPL If you run `tail -f /var/azuracast/www_tmp/php_errors.log`, are there any errors?

**Comment by TorchwoodPL** [comment]
Yeap, I have the same error as above.

**Comment by SlvrEagle23** [comment]
@TorchwoodPL @alutus The latest update should help with this issue. Let me know if it helps. You can also manually run `composer install --no-dev` to pull the missing dependencies.

**Comment by TorchwoodPL** [comment]
http://radio.vps.expij.pl/ I have the same "502 Bad Gateway" :(

Last error from /var/azuracast/www_tmp/error.log is
`2018/04/07 09:36:24 [error] 15515#15515: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 188.146.181.242, server: radio.vps.expij.pl, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "radio.vps.expij.pl"`

There is something wrong with php instance after update, maybe it is not php error itself but php interpreter only...

**Comment by TorchwoodPL** [comment]
I changed vhost php conf from:

> location ~ \.php$ {
>         fastcgi_hide_header Cache-Control;
>         fastcgi_split_path_info ^(.+\.php)(/.+)$;
> 
>         # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
>         fastcgi_pass 127.0.0.1:9000;
>         fastcgi_index index.php;
>         fastcgi_param SCRIPT_FILENAME /var/azuracast/www/web$fastcgi_script_name;
>         include fastcgi_params;
> 
>         fastcgi_read_timeout 1800;
>     }

to

> location ~ \.php$ {
>         fastcgi_hide_header Cache-Control;
>         fastcgi_split_path_info ^(.+\.php)(/.+)$;
> 
>         # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
>         fastcgi_pass unix:/run/php/php7.2-fpm.sock;
>         fastcgi_index index.php;
>         fastcgi_param SCRIPT_FILENAME /var/azuracast/www/web$fastcgi_script_name;
>         include fastcgi_params;
> 
>         fastcgi_read_timeout 1800;
>     }

And now I get:

> 2018/04/08 09:36:13 [error] 7769#7769: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  require(): Failed opening required '/var/azuracast/www/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/azuracast/www/app/bootstrap.php on line 55" while reading response header from upstream, client: 46.161.55.106, server: radio.vps.expij.pl, request: "GET /_asterisk/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "77.55.208.240"

**Comment by SlvrEagle23** [comment]
@TorchwoodPL Yeah, that's the same problem as before...composer dependencies aren't installed correctly.

Did you run the `composer install --no-dev` in the `/var/azuracast/www` folder? Should fix it.

**Comment by TorchwoodPL** [comment]
```
root@vps:/var/azuracast/www# composer install --no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
```
And error is the same...

**Comment by SlvrEagle23** [comment]
@TorchwoodPL Oh, yeah...you're running composer update as root, but the user looking for the files is the `azuracast` user.

Try `chown -R azuracast:www-data /var/azuracast/www/vendor`

**Comment by SlvrEagle23** [comment]
@TorchwoodPL And then, if you need to do that by hand in the future, just make sure you `sudo -u azuracast composer install --no-dev` it

**Comment by TorchwoodPL** [comment]
No effect :(

**Comment by SlvrEagle23** [comment]
@TorchwoodPL Make sure you restart the PHP-FPM service as well. You mentioned changing it to use the socket, and that's not actually normally supposed to work, which suggests to me that something went wrong in an install or update.

**Comment by TorchwoodPL** [comment]
I change back php conf to:

```
    location ~ \.php$ {
        fastcgi_hide_header Cache-Control;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/azuracast/www/web$fastcgi_script_name;
        include fastcgi_params;

        fastcgi_read_timeout 1800;
    }
```
Done:

```
root@vps:~# service php7.2-fpm restart
root@vps:~# service nginx restart
```

And still getting "502 Bad Gateway" with error:

`2018/04/08 18:54:21 [error] 19844#19844: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 188.146.181.242, server: radio.vps.expij.pl, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "radio.vps.expij.pl"`

**Comment by SlvrEagle23** [comment]
@TorchwoodPL Just for curiosity, can you try running `./update.sh --full` in the `/var/azuracast/www` directory? It should force-reset everything into place.

**Comment by TorchwoodPL** [comment]
Ok, your update somehow change /etc/php/7.2/fpm/pool.d/www.conf for wrong one... I do not know why...

**Comment by SlvrEagle23** [comment]
@TorchwoodPL I don't know what you mean. It changes it to one that works with AzuraCast. If you're changing it back, then that's probably the problem, because php-fpm needs to run as the user specified in the PHP-FPM `www.conf` config for permissions to work correctly.

**Comment by TorchwoodPL** [comment]
I checked www.conf file and conntent was different, you file was in the same folder but named www.conf.dpkg-old. So some update process update the file that you provide with AzuraCast.

**Comment by SlvrEagle23** [comment]
@TorchwoodPL Hmm, I'm not sure what update triggered that. Could be something with `php7.2-fpm` itself...

Either way, can you confirm that switching back to the one provided by AzuraCast and restarting the PHP-FPM service fixes things?

**Comment by TorchwoodPL** [comment]
Yes I can confirm that
