### ISSUE TITLE
WebDJ wss not working

### ISSUE THREAD

**Issue by polo-1245-oficial** [AzuraCast/AzuraCast#5413]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.16.0 Stable

### What happened?

When I connect to the radio station with WebDJ I can't but in the console I have a WebSocket error.
<img src="https://cdn.discordapp.com/attachments/753976774005882911/978647313486581790/unknown.png">

**Comment by ivellios1988** [comment]
What browser do you use? And what version?

**Comment by polo-1245-oficial** [comment]
Browser: Brave
Version: 1.39.111 Chromium: 102.0.5005.61 (Build oficial) (64 bits)

But I tried with another browser and I have the same error

**Comment by antho2305** [comment]
Same here cannot connect using the WEB DJ page, however it works great using Mixx or Butt
![error](https://user-images.githubusercontent.com/40645459/170894809-94647dd6-6e8a-4bb3-bd30-8f39651a3c5f.jpg)

**Comment by SC2Mitch** [comment]
Tested on the rolling release, seems to work fine for me

I also ask that people try the `Use Asynchronous Worker` option and sign in.

**Comment by antho2305** [comment]
I did try using asynchronous worker still the same, I'm on the rolling release, update it but nothing change

**Comment by polo-1245-oficial** [comment]
Same error

**Comment by SC2Mitch** [comment]
![image](https://user-images.githubusercontent.com/29955942/170990913-c3f811a5-4e0d-48af-acbb-1e3becbd3c26.png)
Can you guys try enabling these settings and trying again? I'm not able to repro this on Firefox, Edge, Chrome or Brave.

**Comment by antho2305** [comment]
Nope still the error

**Comment by antho2305** [comment]
> Browsers disallow using the `MediaDevices.getUserMedia()` function (or rather using Media input like Mics and Webcams in general) for non-https websites.
> 
> Citation from mdn Web Docs:
> 
> > ... in insecure contexts, navigator.mediaDevices is undefined, preventing access to getUserMedia(). A secure context is, in short, a page loaded using HTTPS or the file:/// URL scheme, or a page loaded from localhost.
> 
> Further more the connection between the WebDJ and the Liquidsoap process is running via WSS (WebSocket Secure) which also requires an SSL certificate.
> 
> In order to use the WebDJ you will need to point a domain to your AzuraCast installation and setup an SSL certificate (for example via the built-in Let's Encrypt).

@Vaalyn that's what I did, I tried to recreate a certificate and SSL looks okay. Azura is installed on a personnal server, in my registrar I set and pointed my domain to my box IP, define ports 80, 443, 8000, 8005, 8004 in TCP redirect to my local server.

Note that the WebDJ service connect I got a success and in the same time disconnect.

By the way I tried with Butt and I set port 443 avec tick the SSL/TLS option it works great! so I guess there's a problem with the webDJ page.

![screen7](https://user-images.githubusercontent.com/40645459/171263409-470d66dc-12b8-4eb2-ab3a-82e945c2b8ca.png)

![certificat](https://user-images.githubusercontent.com/40645459/171263798-77dc6fe7-bb80-45cc-bf14-3c17b0d34a60.png)

![butt](https://user-images.githubusercontent.com/40645459/171263813-3020d1e2-21a4-4f23-b0c2-3fdfc7a6a9a2.png)

**Comment by Mozitux** [comment]
Hello, I have the same issue, tested with different version, operating systems, hosting services and nothing change

**Comment by marik22312** [comment]
Hey! I'm experiencing the same issue with Azuracast v17.1 stable, docker installation
any update on this?

**Comment by marik22312** [comment]
Any updates on this issue?
still reproduces on various installations =\

**Comment by SlvrEagle23** [comment]
@marik22312 Going through a personal emergency. Check literally any of our pinned issues, social media, Discord, etc. Please be patient.

**Comment by marik22312** [comment]
@SlvrEagle23 I'm deeply sorry to hear that. 🙏🏻
I didn't see the pinned issue or social media
Apologizes.
