### ISSUE TITLE
Error in playlists configured to broadcast once a day

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#5415]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.16.1

### What happened?

Error in playlists configured to broadcast once a day

After the update to version 0.16.1, playlists set to play at a certain time play ahead of time. For example, a playlist set to air at 5:59 p.m. starts playing 10 minutes earlier or even long. An example:

![image](https://user-images.githubusercontent.com/16152034/170080226-8ec429f4-378b-45d8-9f66-413be4886cdf.png)

![image](https://user-images.githubusercontent.com/16152034/170080337-3815c403-79ae-4509-80b8-795f903567b0.png)

**Comment by fidegr** [comment]
Hello, I share this error with you again. In lists programmed to sound on the hour, or approximately on the hour, they sound very soon, as in the example that I paste below, or later because some music from the start time sneaks in.

As you can understand, when it comes to keeping broadcast schedules for a radio station, it is a problem.

![image](https://user-images.githubusercontent.com/16152034/172785106-81b2fb5b-de65-41df-bc4d-e521d95e607f.png)

```
2022/06/09 06:51:22 [decoder:2] Decoding "/var/azuracast/stations/radio_almaina/media/Música/Pop Rock Punk Metal/Travoltas - Little Honda.ogg" ended: Ffmpeg_decoder.End$
2022/06/09 06:51:22 [next_song:3] Prepared "/var/azuracast/stations/radio_almaina/media/Podcast/1H/es_lo_que_hay/es-lo-hay-08-06-22_mf_88215372_feed_1.mp3" (RID 9).
[mp3float @ 0x7fd3685d1e40] Could not update timestamps for skipped samples.
2022/06/09 06:51:22 [cue_next_song:3] Cueing in...
2022/06/09 06:51:22 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:9010/api/internal/6/liquidsoap/nextsong' with body:
2022/06/09 06:51:22 [cross_0:3] Analysis: -35.102796dB / -14.415825dB (2.96s / 2.96s)
2022/06/09 06:51:22 [crossfade_0:3] No transition: using default.
2022/06/09 06:51:22 [lang:3] API nextsong - Response (200): annotate:title="Radio Almaina en el 88.5 FM",artist="1",duration="6.00",song_id="2b639347d7463ca9168e96652db$
2022/06/09 06:51:25 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:9010/api/internal/6/liquidsoap/feedback' with body: {
2022/06/09 06:51:25 [lang:3]   "song_id": "4666ceff73e5cd0c527b4b56cfdd908b",
2022/06/09 06:51:25 [lang:3]   "playlist_id": "94",
2022/06/09 06:51:25 [lang:3]   "media_id": "90127"
2022/06/09 06:51:25 [lang:3] }
2022/06/09 06:51:25 [lang:3] API feedback - Response (200): true
[mp3float @ 0x7fd3685d1e40] Could not update timestamps for discarded samples.
2022/06/09 07:51:18 [decoder:2] Decoding "/var/azuracast/stations/radio_almaina/media/Podcast/1H/es_lo_que_hay/es-lo-hay-08-06-22_mf_88215372_feed_1.mp3" ended: Ffmpeg_$
2022/06/09 07:51:18 [next_song:3] Prepared "/var/azuracast/stations/radio_almaina/media/Cuñas/cuna_radio_almaina_2~0.mp3" (RID 4).
[mp3float @ 0x7fd368061d00] Could not update timestamps for skipped samples.
2022/06/09 07:51:18 [cue_next_song:3] Cueing in...
2022/06/09 07:51:18 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:9010/api/internal/6/liquidsoap/nextsong' with body:
2022/06/09 07:51:18 [cross_0:3] Analysis: -20.480594dB / -14.695799dB (2.96s / 2.96s)
2022/06/09 07:51:18 [crossfade_0:3] No transition: using default.
2022/06/09 07:51:18 [lang:3] API nextsong - Response (200): annotate:title="Straight Fire Funk 45",artist="The Jive Turkeys",duration="140.00",song_id="df77acd3b9fe678e$
2022/06/09 07:51:21 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:9010/api/internal/6/liquidsoap/feedback' with body: {
2022/06/09 07:51:21 [lang:3]   "song_id": "2b639347d7463ca9168e96652dbf18f0",
2022/06/09 07:51:21 [lang:3]   "playlist_id": "63",
2022/06/09 07:51:21 [lang:3]   "media_id": "1589"
2022/06/09 07:51:21 [lang:3] }
2022/06/09 07:51:21 [lang:3] API feedback - Response (200): true
[mp3float @ 0x7fd368061d00] Could not update timestamps for discarded samples.
2022/06/09 07:51:24 [decoder:2] Decoding "/var/azuracast/stations/radio_almaina/media/Cuñas/cuna_radio_almaina_2~0.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/06/09 07:51:25 [next_song:3] Prepared "/var/azuracast/stations/radio_almaina/media/Música/Blues-Jazz-R&B-Soul_R&R/Funk/Música/Electrónica-HipHop/Jazz & Funk/The Ji$
2022/06/09 07:51:25 [cue_next_song:3] Cueing in...
2022/06/09 07:51:25 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:9010/api/internal/6/liquidsoap/nextsong' with body:
2022/06/09 07:51:25 [cross_0:3] Analysis: -35.519221dB / -37.358694dB (2.96s / 2.96s)
2022/06/09 07:51:25 [crossfade_0:3] Old <= medium, new <= medium and |old-new| <= margin.
2022/06/09 07:51:25 [crossfade_0:3] Old and new source are not too loud and close.
2022/06/09 07:51:25 [crossfade_0:3] Transition: crossed, fade-in, fade-out.
2022/06/09 07:51:25 [lang:3] API nextsong - Response (200): annotate:title="Fire",artist="The Excitements",duration="166.00",song_id="fea830fbe041da191ad92954d0437771",$
2022/06/09 07:51:25 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:9010/api/internal/6/liquidsoap/feedback' with body: {
2022/06/09 07:51:25 [lang:3]   "song_id": "df77acd3b9fe678e6262e2163baa589a",
2022/06/09 07:51:25 [lang:3]   "playlist_id": "233",
2022/06/09 07:51:25 [lang:3]   "media_id": "23770"
2022/06/09 07:51:25 [lang:3] }
2022/06/09 07:51:25 [lang:3] API feedback - Response (200): true
2022/06/09 07:53:42 [decoder:2] Decoding "/var/azuracast/stations/radio_almaina/media/Música/Blues-Jazz-R&B-Soul_R&R/Funk/Música/Electrónica-HipHop/Jazz & Funk/The Jive$
2022/06/09 07:53:43 [next_song:3] Prepared "/var/azuracast/stations/radio_almaina/media/Música/Blues-Jazz-R&B-Soul_R&R/Jazz & Funk/The Excitements - Fire
```.ogg" (RID 1).
2022/06/09 07:53:43 [cue_next_song:3] Cueing in...

**Comment by jprush76** [comment]
> Hello, I share this error with you again. In lists programmed to sound on the hour, or approximately on the hour, they sound very soon, as in the example that I paste below, or later because some music from the start time sneaks in.
> 
> As you can understand, when it comes to keeping broadcast schedules for a radio station, it is a problem.
> 
> ![image](https://user-images.githubusercontent.com/16152034/172786766-35cf4f49-d0d0-435c-9676-209f49d2bfd7.png)
> 
> ![image](https://user-images.githubusercontent.com/16152034/172785106-81b2fb5b-de65-41df-bc4d-e521d95e607f.png)
> 
> ```
> 2022/06/09 06:51:22 [decoder:2] Decoding "/var/azuracast/stations/radio_almaina/media/Música/Pop Rock Punk Metal/Travoltas - Little Honda.ogg" ended: Ffmpeg_decoder.End$
> 2022/06/09 06:51:22 [next_song:3] Prepared "/var/azuracast/stations/radio_almaina/media/Podcast/1H/es_lo_que_hay/es-lo-hay-08-06-22_mf_88215372_feed_1.mp3" (RID 9).
> [mp3float @ 0x7fd3685d1e40] Could not update timestamps for skipped samples.
> 2022/06/09 06:51:22 [cue_next_song:3] Cueing in...
> 2022/06/09 06:51:22 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:9010/api/internal/6/liquidsoap/nextsong' with body:
> 2022/06/09 06:51:22 [cross_0:3] Analysis: -35.102796dB / -14.415825dB (2.96s / 2.96s)
> 2022/06/09 06:51:22 [crossfade_0:3] No transition: using default.
> 2022/06/09 06:51:22 [lang:3] API nextsong - Response (200): annotate:title="Radio Almaina en el 88.5 FM",artist="1",duration="6.00",song_id="2b639347d7463ca9168e96652db$
> 2022/06/09 06:51:25 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:9010/api/internal/6/liquidsoap/feedback' with body: {
> 2022/06/09 06:51:25 [lang:3]   "song_id": "4666ceff73e5cd0c527b4b56cfdd908b",
> 2022/06/09 06:51:25 [lang:3]   "playlist_id": "94",
> 2022/06/09 06:51:25 [lang:3]   "media_id": "90127"
> 2022/06/09 06:51:25 [lang:3] }
> 2022/06/09 06:51:25 [lang:3] API feedback - Response (200): true
> [mp3float @ 0x7fd3685d1e40] Could not update timestamps for discarded samples.
> 2022/06/09 07:51:18 [decoder:2] Decoding "/var/azuracast/stations/radio_almaina/media/Podcast/1H/es_lo_que_hay/es-lo-hay-08-06-22_mf_88215372_feed_1.mp3" ended: Ffmpeg_$
> 2022/06/09 07:51:18 [next_song:3] Prepared "/var/azuracast/stations/radio_almaina/media/Cuñas/cuna_radio_almaina_2~0.mp3" (RID 4).
> [mp3float @ 0x7fd368061d00] Could not update timestamps for skipped samples.
> 2022/06/09 07:51:18 [cue_next_song:3] Cueing in...
> 2022/06/09 07:51:18 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:9010/api/internal/6/liquidsoap/nextsong' with body:
> 2022/06/09 07:51:18 [cross_0:3] Analysis: -20.480594dB / -14.695799dB (2.96s / 2.96s)
> 2022/06/09 07:51:18 [crossfade_0:3] No transition: using default.
> 2022/06/09 07:51:18 [lang:3] API nextsong - Response (200): annotate:title="Straight Fire Funk 45",artist="The Jive Turkeys",duration="140.00",song_id="df77acd3b9fe678e$
> 2022/06/09 07:51:21 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:9010/api/internal/6/liquidsoap/feedback' with body: {
> 2022/06/09 07:51:21 [lang:3]   "song_id": "2b639347d7463ca9168e96652dbf18f0",
> 2022/06/09 07:51:21 [lang:3]   "playlist_id": "63",
> 2022/06/09 07:51:21 [lang:3]   "media_id": "1589"
> 2022/06/09 07:51:21 [lang:3] }
> 2022/06/09 07:51:21 [lang:3] API feedback - Response (200): true
> [mp3float @ 0x7fd368061d00] Could not update timestamps for discarded samples.
> 2022/06/09 07:51:24 [decoder:2] Decoding "/var/azuracast/stations/radio_almaina/media/Cuñas/cuna_radio_almaina_2~0.mp3" ended: Ffmpeg_decoder.End_of_file.
> 2022/06/09 07:51:25 [next_song:3] Prepared "/var/azuracast/stations/radio_almaina/media/Música/Blues-Jazz-R&B-Soul_R&R/Funk/Música/Electrónica-HipHop/Jazz & Funk/The Ji$
> 2022/06/09 07:51:25 [cue_next_song:3] Cueing in...
> 2022/06/09 07:51:25 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:9010/api/internal/6/liquidsoap/nextsong' with body:
> 2022/06/09 07:51:25 [cross_0:3] Analysis: -35.519221dB / -37.358694dB (2.96s / 2.96s)
> 2022/06/09 07:51:25 [crossfade_0:3] Old <= medium, new <= medium and |old-new| <= margin.
> 2022/06/09 07:51:25 [crossfade_0:3] Old and new source are not too loud and close.
> 2022/06/09 07:51:25 [crossfade_0:3] Transition: crossed, fade-in, fade-out.
> 2022/06/09 07:51:25 [lang:3] API nextsong - Response (200): annotate:title="Fire",artist="The Excitements",duration="166.00",song_id="fea830fbe041da191ad92954d0437771",$
> 2022/06/09 07:51:25 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:9010/api/internal/6/liquidsoap/feedback' with body: {
> 2022/06/09 07:51:25 [lang:3]   "song_id": "df77acd3b9fe678e6262e2163baa589a",
> 2022/06/09 07:51:25 [lang:3]   "playlist_id": "233",
> 2022/06/09 07:51:25 [lang:3]   "media_id": "23770"
> 2022/06/09 07:51:25 [lang:3] }
> 2022/06/09 07:51:25 [lang:3] API feedback - Response (200): true
> 2022/06/09 07:53:42 [decoder:2] Decoding "/var/azuracast/stations/radio_almaina/media/Música/Blues-Jazz-R&B-Soul_R&R/Funk/Música/Electrónica-HipHop/Jazz & Funk/The Jive$
> 2022/06/09 07:53:43 [next_song:3] Prepared "/var/azuracast/stations/radio_almaina/media/Música/Blues-Jazz-R&B-Soul_R&R/Jazz & Funk/The Excitements - Fire
> ```.ogg" (RID 1).
> 2022/06/09 07:53:43 [cue_next_song:3] Cueing in...
> ```

Hi @fidegr I have the same problem, did you solve it?
