### ISSUE TITLE
Ice cast server not starting

### ISSUE THREAD

**Issue by jasonboateng** [AzuraCast/AzuraCast#5417]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.16.1 Stable • Docker • PHP 8.

### What happened?

Ice cast server not starting 
after installing using Digital Ocean I created a radio station, and the ice cast server  is not starting 

![image](https://user-images.githubusercontent.com/16203851/170139051-9547beb6-6f7f-4530-b246-82841ebd320a.png)

**Comment by adoboligh1** [comment]
you need to have music assigned to your playlist before icecast will start, i see you are a Ghanaian like myself, you can email me on adoboligh1@gmail.com and i will gladly help incase you need help

**Comment by jasonboateng** [comment]
Thanks it for the help I'm live
