### ISSUE TITLE
Use a specific port for streaming

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#5418]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.16.1

### What happened?

Hello, we have been presented with a somewhat peculiar case. A station asks us to use a specific port, 8152. In the location they are in, it is the port that they have open in the router and for bureaucratic reasons they prefer to continue using that for streaming from the studio. The thing is that trying to change the default port in the station profile in azuracast doesn't work.

What would be the steps to configure the port?

**Comment by Sakretsos** [comment]
Hello @fidegr,
Instead of changing the port from azuracast frontend, you must also configure the docker compose file in order to open this specific port on the radio server.

**Comment by SlvrEagle23** [comment]
@fidegr When updating your installation, you'll be prompted if you want to change configuration settings; if you answer "yes", this will let you change the port mapping to include the ports you want to use for your station and will make sure they're cleared through the Docker firewall. You can then edit the station's profile inside AzuraCast and assign it to use whatever port you want.
