### ISSUE TITLE
buffer

### ISSUE THREAD

**Issue by alutus** [AzuraCast/AzuraCast#542]
Ubuntu 16.04

Howdy
I use azuracast on a vps with ubuntu,
since the last update they receive delay * buffer * in the winamp client.
I use 32 Kbs/s acc.
Also buffering... also i tested the up/down link...60MB/s speed.

```
Winamp STATUS Radio
Network received: 42383 bytes
Server: Ultravox/2.1 SHOUTcast v2.5.5.733/posix(linux x64)
Content-Type: audio/aacp
Ultravox sync: 228 messages, 0 desyncs
Ultravox Data Message: 0x8003
Ultravox SID/AvgBR/MaxBR: 1/32000/32000

```
How to return on non-beta version?
AzuraCast v0.8.1-2018.02 Beta

**Comment by SlvrEagle23** [comment]
@alutus I'm not sure what you mean by "non-beta version"...are you referring to a non-beta version of AzuraCast? The project's still under active development, and has no stable releases to date, so it's still beta software in general.

**Comment by SlvrEagle23** [comment]
I haven't heard any follow-up on this issue, so I don't know if the issue has been fixed or if further action is required on my end. If you don't mind, could you please update me on the status of this issue?

If I don't hear any updates for a while, I'll close the issue as resolved.

**Comment by ErnestPH** [comment]
@SlvrEagle23 - it's confirmed a 30 seconds delay when playing live using WinAmp. But I just updated to the latest build. Will update this one. Thanks
