### ISSUE TITLE
Unable to enable broadcasting

### ISSUE THREAD

**Issue by blindndangerous** [AzuraCast/AzuraCast#5420]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #693e437 (2022-05-24 5:50) • Docker • PHP 8.1

### What happened?

Tried to enable broadcasting, and I get the following error in my log. It also gives me a 400 bad request.
[2022-05-25T15:15:08.837187+00:00] AzuraCast.ERROR: Supervisor fault: BAD_NAME: station_1 {"faultString":"BAD_NAME: station_1","faultCode":10} []
I also see in the log viewer "Your current installation type is %s".

**Comment by blindndangerous** [comment]
I don't believe that it exists, but can you enable stations from the console?  If not, I'll keep waiting on a fix for this.

**Comment by SlvrEagle23** [comment]
@blindndangerous Do you know which link you're using to start the broadcasting for the station? It's possible that the supervisor configuration hasn't been written yet; in that case, the way to start the station would be via the Broadcasting menu, then "Restart Broadcasting".

**Comment by blindndangerous** [comment]
@SlvrEagle23  When I try restart broadcasting from broadcasting>restart broadcasting, I get the message that my station is disabled.  When I click the edit your station profile from the profile page to enable broadcasting is when I get the 400 bad request. http://station_url:port/station/1/%s
