### ISSUE TITLE
Azuracast provided embed player is not working

### ISSUE THREAD

**Issue by infogatel2** [AzuraCast/AzuraCast#5426]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

The embedded player shows a blank page used in joomla or wordpress sites.
The stream used is from shoutcast and ssl broadcast link is used. The websites tested are using a valid ssl too.
Testing the other embedded tools like latest songs or shedule is working normally.
Am i missing something?

Thank you in advance.

**Comment by SC2Mitch** [comment]
Can you pull up the browser logs f12 or right click > inspect > console

Check if there's any errors. If there's none check the network and refresh the page.

**Comment by infogatel2** [comment]
You are totally right. I noticed in console too many jquery conflicts and mootools errors. 
Disabled all the modules and plugins causing the problem and tested again. 
The player works as it should. It is embedded normally with no problems now.
Seems like i really was misleaded from older reported issues and did not investigate further. 
Thank you for your time and hint. That was really helpful.

**Comment by SC2Mitch** [comment]
Happy to help, have a lovely day :)
