### ISSUE TITLE
Problem with "Allowed IP Addresses"

### ISSUE THREAD

**Issue by chredeur0** [AzuraCast/AzuraCast#5428]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#ee5b623

### What happened?

When I enter an ip address in "Allowed IP Addresses" I expect that only this ip address and access to the radio except that everyone has access to the radio.
![image](https://user-images.githubusercontent.com/50155089/170568140-c492bc41-727e-40cf-a728-0498177f9298.png)

### Relevant log output

```shell
I have no error in my logs
```

**Comment by SlvrEagle23** [comment]
@chredeur0 Unfortunately, by itself our "allowed IPs" list doesn't automatically block all other IPs that aren't on the list. You can easily work around this, however, by including the CIDR notation for all IP addresses in the "Blocked IPs" field:

```
0.0.0.0/0
```

This will put your station in a "default block" state, with only the IPs listed in the allow list allowed.

**Comment by chredeur0** [comment]
> @chredeur0 Unfortunately, by itself our "allowed IPs" list doesn't automatically block all other IPs that aren't on the list. You can easily work around this, however, by including the CIDR notation for all IP addresses in the "Blocked IPs" field:
> 
> ```
> 0.0.0.0/0
> ```
> 
> This will put your station in a "default block" state, with only the IPs listed in the allow list allowed.

The problem with doing what you advised is that I can't do a "Reload to apply change" I think it also blocks the radio.

**Comment by BusterNeece** [comment]
I've just pushed an update to our Rolling Release channel that changes how the "Allowed IPs" list is processed; now, if you have any IPs in that list, it will be used as the authoritative list for what IPs are allowed to connect; if

**Comment by chredeur0** [comment]
> I've just pushed an update to our Rolling Release channel that changes how the "Allowed IPs" list is processed; now, if you have any IPs in that list, it will be used as the authoritative list for what IPs are allowed to connect; if

I just tried and I can't block all the ip except one
