### ISSUE TITLE
Raspberry pi3 model b+

### ISSUE THREAD

**Issue by wilz7** [AzuraCast/AzuraCast#543]
- **Installation Method:** <Traditional -->
- **Host OS (if using Docker):** 

**Describe the issue in full detail, including screenshots if possible:**

When trying to install on Raspberry pi 3 model B+
i get the following error after  sending the command /install.sh

Processing triggers for libc-bin (2.24-11+deb9u3) ...
Setting up python-selinux (2.6-3) ...
Setting up ansible (2.2.1.0-2) ...
Setting up python-mysqldb (1.3.7-1.1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Installing AzuraCast (Environment: production)
ERROR! no action detected in task. This often indicates a misspelled module name                                                                                                             , or incorrect module path.

The error appears to have been in '/var/azuracast/www/util/ansible/roles/azuraca                                                                                                             st-radio/tasks/main.yml': line 2, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
  - include_tasks: x86.yml
    ^ here

The error appears to have been in '/var/azuracast/www/util/ansible/roles/azuraca                                                                                                             st-radio/tasks/main.yml': line 2, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
  - include_tasks: x86.yml
    ^ here

pi@raspberrypi:/var/azuracast/www $

![raspian](https://user-images.githubusercontent.com/32097721/38456873-1d9ca46a-3a81-11e8-992d-6284a350665f.PNG)

**Comment by SlvrEagle23** [comment]
@wilz7 Currently, the Raspberry Pi models are not supported, due to some of our dependent software components not being built yet for the ARMHF architecture. I'm continuing to keep an eye on improving compatibility for the RPIs, but right now I have no updates. If we're able to re-introduce ARMHF/RPi support in the future, it'll be announced via a Github release and our social media channels.
