### ISSUE TITLE
Error during install on AWS LightSail LAMP VM php 7.4

### ISSUE THREAD

**Issue by inglesuniversal** [AzuraCast/AzuraCast#5430]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Successfully installed script but got this error at the end... Any pointers?

Thanks

### Relevant log output

```shell
root@ip-172-26-0-189:/var/azuracast# ./docker.sh install
Checking installation requirements for AzuraCast...
[PASS] Operating System: Linux
[PASS] Architecture: x86_64
[PASS] Command Present: curl
[PASS] Command Present: awk
[PASS] User Permissions
[PASS] Installation Directory
[PASS] All requirements met!
Docker is already installed! Continuing...
Docker Compose does not appear to be installed. Install Docker Compose now? [Y/n] Y
Installing Docker Compose...
mv: cannot move './docker-compose' to '/usr/libexec/docker/cli-plugins/docker-compose': No such file or directory
```

**Comment by SC2Mitch** [comment]
This is most likely an issue with AWS Lightsail but I'll flag it up anyway.

**Comment by SlvrEagle23** [comment]
@inglesuniversal This probably means you need a newer version of Docker installed. Even though it detected a Docker version, we currently don't detect which version of Docker is running. You can update it by running:

```
./docker.sh install-docker
```

...then re-running the installation script.
