### ISSUE TITLE
The routine synchronization task has not run recently. This may indicate an error with your installation.

### ISSUE THREAD

**Issue by infogatel2** [AzuraCast/AzuraCast#5436]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

I see that error everytime i get to dashboard. Checking "System Debugger" I see Synchronization Tasks
 have never run. To all of them under last run i see "Not Run".
I tried to restart using the follow commands 
```
docker-compose down
docker-compose up -d
```
The result is "no configuration file provided: not found"
Could you please help me?

**Comment by infogatel2** [comment]
Ok i just managed to run the commands normally and restart installation. 
I had to use it as follows to enter azuracast folder first.

```
cd /var/azuracast
docker-compose down
docker-compose up -d
```

After some minutes i see that now tasks are working normally.
Hope that will help someone else :)

**Comment by SC2Mitch** [comment]
Glad to hear it's fixed.

Should people be having this issue, you can manually run these tasks via the system debugger. If an error appears, report it here.

Closed.
