### ISSUE TITLE
Help page redirects to locahost instead of AzuraCast's docs

### ISSUE THREAD

**Issue by Blat4** [AzuraCast/AzuraCast#5439]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #3056952

### What happened?

I was alerted to a broken link in Azuracast by a station admin attemping to use the support documents link in the help section of the web interface. 

They got a 400 Bad Request. Now this may not seem like to much of a problem, as you can easily find all the help you need via a simple google search. However Im sure it worked before, and this only concerns me that something may have happened to my installation.

Hovering over the link shows the follow destination /station/2/%s after the server address.

There's 4 stations in total, and the link in help section is broken for all.

Please can someone advise.

**Comment by SC2Mitch** [comment]
>I was alerted to a broken link in Azuracast by a station admin attemping to use the support documents link in the help section of the web interface.

Can you give a screenshot or more information on the link the station admin was attempting to use?

**Comment by Blat4** [comment]
I've included a screenshot to the page and link in question.
![Screenshot 2022-05-29 180600](https://user-images.githubusercontent.com/106454822/170882682-ce4eb458-daec-4258-8df4-28d6000cf9e3.png)

It's not a big problem. But I'm just concerned if something has happened to my installation. 

Is there a repair option for a possible corrupt or damaged installation ?

**Comment by SC2Mitch** [comment]
Reproduced and flagged up for the developers to fix. 
Note: I'm unsure why it's redirecting to your localhost when we have the docs already linked there, there's also a small issue with recognising users installations too. 

Broken support docs URI: https://github.com/AzuraCast/AzuraCast/blob/main/templates/partials/log_help_card.phtml#L7-L8 
Unable to recognise the machine type: https://github.com/AzuraCast/AzuraCast/blob/main/templates/partials/log_help_card.phtml#L14-L15
