### ISSUE TITLE
Facebook Live Hooks

### ISSUE THREAD

**Issue by RainbowDash53** [AzuraCast/AzuraCast#544]
Hello, I was thinking about that, the up/down vote system still impossible to use so why don't you make a system that we can stream on facebook with the image and the title of the current song and with live reactions people can say if they like or they don't the music.

Grrr = I don't like
Thumbs Up = I like it

Thank's in advance 👍

**Comment by mkody** [comment]
Facebook has been cracking down on FBLive about people using reactions for votes.
Also a live can't be up for more than 4 hours.

**Comment by SlvrEagle23** [comment]
@RainbowDash53 To be clear, it's not "impossible to use", it's just a feature that was requested but hasn't been implemented yet. It's still on the global to-do list for AzuraCast, it's just not a particularly high priority for development.

**Comment by SlvrEagle23** [comment]
I'm closing this issue, as the request is specifically that we support Facebook Live Video, which is inherently a video streaming service, not an audio one.

In the (seemingly increasingly likely) event that an AzuraCast video version is created, by all means Facebook Video will be one of the possible destinations for it. That will very likely be a new repository, though, with its own issues, as video streaming is a very, very different beast from audio streaming.
