### ISSUE TITLE
HLS Problem

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#5458]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#fac86b7 (2022-06-04 3:39)

### What happened?

I enabled HLS on my station, however I got Slim Application error immediately. Anyway I see that it's enabled under HLS Streams menu.
Then I added a new HLS Stream and created a Playlist and added a song.
I see "https://www.radio.com/hls/stationname/live.m3u8" on my station but it doesn't play and when I click on the URL, I get:
**404 Not Found
nginx**

**Comment by SlvrEagle23** [comment]
@stardevelop More logs are necessary and would be appreciated.

**Comment by stardevelop** [comment]
**Liquidsoap Log:**

Unknown position:

Error -1: Exception raised: The requested ffmpeg encoder was not found, please make sure that ffmpeg was compiled with support for it
Raised by primitive operation at Avcodec in file "avcodec/avcodec.ml", line 219, characters 0-1023
Called from Ffmpeg_internal_encoder.mk_audio in file "encoder/ffmpeg_internal_encoder.ml", line 94, characters 14-54
Re-raised at Ffmpeg_internal_encoder.mk_audio in file "encoder/ffmpeg_internal_encoder.ml", line 98, characters 12-19
Called from Stdlib__Option.map in file "option.ml", line 24, characters 57-62
Called from Ffmpeg_encoder_common.encoder.make in file "encoder/ffmpeg_encoder_common.ml", line 124, characters 6-109
Called from Ffmpeg_encoder_common.encoder in file "encoder/ffmpeg_encoder_common.ml", line 139, characters 20-29
Called from Hls_output.hls_output.f in file "outputs/hls_output.ml", line 334, characters 20-67
Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
Called from Hls_output.hls_output.mk_streams in file "outputs/hls_output.ml" (inlined), line 400, characters 24-42
Called from Hls_output.hls_output in file "outputs/hls_output.ml", line 401, characters 17-30
Called from Lang.add_operator.(fun).f in file "lang/lang.ml", line 810, characters 41-46
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 257, characters 8-12
Called from Evaluation.eval_toplevel in file "lang/evaluation.ml", line 424, characters 16-22
Called from Runtime.type_and_run.(fun) in file "lang/runtime.ml", line 38, characters 13-43
Called from Tutils.finalize in file "tools/tutils.ml", line 105, characters 12-16
Re-raised at Tutils.finalize in file "tools/tutils.ml", line 111, characters 4-38
Called from Runtime.report in file "lang/runtime.ml", line 227, characters 12-23

**Comment by SC2Mitch** [comment]
Confirming, reproduced on my local machine. 

I have two HLS mount points setup, one 32kb and one 320kb, Liquidsoap immediately crashes upon restarting the stations with the error log listed above.

**Comment by SlvrEagle23** [comment]
I'm removing MP3 as a HLS Stream option...AAC is the only current supported option.

**Comment by stardevelop** [comment]
Thanks. It works fine now.
But I still can't play a M3U8 Remote URL Playlist on my station. (remote URL example, http://remote.domain.com:1935/radio1/playlist.m3u8).
Nothing plays when I set the default Playlist as Remote URL.

**Comment by SlvrEagle23** [comment]
@stardevelop That's a different issue for sure...outputting HLS is very different from inputting it. I'm not quite sure Liquidsoap _can_ handle an HLS stream as an input.

**Comment by stardevelop** [comment]
Do you support the HLS stream as an input (Remote URL) in the latest update?
https://github.com/AzuraCast/AzuraCast/commit/c7cfa2d00a9965cf842853f1461f47a0c7f968fe

**Comment by SlvrEagle23** [comment]
@stardevelop Yeah, turns out Liquidsoap does support HLS input, just with a different flag on the input. Try it out.

**Comment by stardevelop** [comment]
Station goes offline when I input m3u8 playlist as Remote URL.
You may test with this example: https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8
