### ISSUE TITLE
Metadata live dj

### ISSUE THREAD

**Issue by radiopiraat** [AzuraCast/AzuraCast#5466]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

![20220607_000512](https://user-images.githubusercontent.com/62199851/172257272-6f7be2bf-1b63-4e4a-a875-f31e4eb349cb.jpg)
I have a problem that when a live dj starts a broadcast for a few seconds his metadata appears and than turn into the text live broadcast.
This is a problem since the last update

**Comment by inetactief** [comment]
Have the same problem
