### ISSUE TITLE
Encoder not connecting

### ISSUE THREAD

**Issue by daraghos1** [AzuraCast/AzuraCast#5469]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.0 Stable • Docker • PHP 8.1

### What happened?

Hi
odd one, I have been streaming from an encoder for the last couple of years, and just at the weekend the stream dropped and I cannot connect now from the encoder to azuracast. 

I have restarted the server, and also azuarcast, also all the stations, flushed the cache, and updated the software, all to no avail. 

Any help much appreciated. The station with the issues are 'rewind' and 'rewind_test' 

### Relevant log output

```shell
https://docs.google.com/document/d/1ap0RNNRPQIPL1e_rnXuZlFWhc5_5cSDk8fXqQAnQ1wc/edit?usp=sharing
```

**Comment by SC2Mitch** [comment]
How exactly are you using it to connect to AzuraCast, are you using BUTT, Mixxx, etc? 

If yes, you'll need to check your Liquidsoap logs which can be found under `broadcasting` and `liquidsoap log`
