### ISSUE TITLE
Podcast Exclusion

### ISSUE THREAD

**Issue by parkerj** [AzuraCast/AzuraCast#547]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Ubuntu 17.10

**Describe the issue in full detail, including screenshots if possible:**

I want to create a podcast playlist, but don't want listeners to request podcasts at this time. Is it possible to exclude podcasts from being requested?

**Comment by SlvrEagle23** [comment]
@parkerj Previously, all standard playlists were requestable and all scheduled/nonstandard ones weren't, to allow for things like bumpers/commercials to be excluded, but I've discovered that this isn't exactly what people are always looking for.

I've expanded playlists to now include a "Allow Requests from This Playlist" toggle, which can be set independently of any other settings for a playlist. Users will only be able to see and request media from playlists where this is marked "Yes".
