### ISSUE TITLE
Updates count don't reset

### ISSUE THREAD

**Issue by Deiiji** [AzuraCast/AzuraCast#5476]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Current

### What happened?

Hello.
Updates only increment, hust after update it show no updates but few time after it show more as 200 now.

**Comment by Deiiji** [comment]
Hello,
I just ran update and  30 minutes after, admin page show: 
[Screen](https://ibb.co/CBFVQnH)

**Comment by SlvrEagle23** [comment]
@Deiiji What version does it show you are running in the footer?

**Comment by Deiiji** [comment]
Hello again,
[6e728bb](https://github.com/AzuraCast/AzuraCast/commit/6e728bbf73ff623c6d8cf4da6924e47e6ca8bb34)
Is old one but it do update with no changes.

**Comment by SlvrEagle23** [comment]
@Deiiji Since you're on the Ansible installation, did you follow the steps to switch to the main branch when we renamed it a while back? https://github.com/AzuraCast/AzuraCast/issues/3800

**Comment by Deiiji** [comment]
Yes, is very old that one, I did, once if you changed again then I did not

**Comment by Deiiji** [comment]
I found, for some reason git  flagged  Azura repo as unsafe, I needed make it trusted again but now I have another error, I open new issue, thank you for trying to solve this.
