### ISSUE TITLE
web proxy URLs

### ISSUE THREAD

**Issue by KoneSV** [AzuraCast/AzuraCast#5477]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.0

### What happened?

I think it's too early to change this option when several of us already have that configured on websites, apps and repeaters, etc... why would I have to ask Google and Apple for permission to update a link in the apps?

They should activate the option to be able to keep the radio/8000 so not to do so much change of links

### Relevant log output

```shell
Code Quality/Technical Changes

    We can now write custom Nginx configuration on a per-station basis and automatically reload it on-the-fly without losing any active connections. This allows us to replace our standard /radio/8000 web proxy URLs with station-specific /listen/station_name ones, among other improvements.
```

**Comment by SlvrEagle23** [comment]
@KoneSV To be clear, we absolutely are not retiring the `/radio/8xxx`-style links! We know that many stations continue to use those URLs, and even in our latest versions, they will absolutely continue to work.

At some point in the future we may look into retiring those older URL formats, but if we do so it will be with ample notice and deprecation.

**Comment by KoneSV** [comment]
And where active is option, because in version 0.17.0 listen/name_station appears, I can't put the radio/8000

**Comment by SlvrEagle23** [comment]
@KoneSV There's no option to visually switch back to the `/radio/xxxx` URLs, because those were honestly a stopgap in the earlier years of AzuraCast that we've only got around to replacing now. The URLs will still _work_, and you can always extrapolate what the URL would be based on the broadcasting port of your station.
