### ISSUE TITLE
When i change source password from API maxlisteners get null value

### ISSUE THREAD

**Issue by Sakretsos** [AzuraCast/AzuraCast#5480]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #18fe406 (2022-06-07 9:00)

### What happened?

Hello, i find today a possible bug.
When i try to change source password from a stream the max listeners changed to null.
Also port changed to null instead of the custom i have enter.
Can you please have a look?

I use the bellow PUT API call.
https://URL/api/admin/station/ID
`{"frontend_config":{"source_pw": "testpass"}}`

Thanks,
Ioannis

**Comment by Sakretsos** [comment]
Update:
Same issue on stable version too!

**Comment by SC2Mitch** [comment]
Can't reproduce this on my local machine. 
![image](https://user-images.githubusercontent.com/29955942/173189503-2dff0955-2393-4acd-a0f5-f84c410bcdff.png)

**Comment by Sakretsos** [comment]
Hello @SC2Mitch,
i do it again just to be sure is not something other weird... but still i have the same issue.
![test2](https://user-images.githubusercontent.com/8127121/173190392-8ec351e7-f16a-4ea1-bc41-0927516d4f30.JPG)

**Comment by Sakretsos** [comment]
@ItsMitchh hello again, this problem caused because i use PUT api call and i dont set any value on listeners and on port so the system change only password and gets the default values for listeners and port.
But on my way i need to change only password without change port - listeners.

**Comment by ItsMitchh** [comment]
Thanks, flagging it up.

**Comment by Sakretsos** [comment]
@ItsMitchh thanks, also this problem caused on stable version too!
