### ISSUE TITLE
Liquidsoap error

### ISSUE THREAD

**Issue by unzelnet** [AzuraCast/AzuraCast#5483]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

0a30648

### What happened?

Station won’t start.
Liquidsoap error
Image attached 
![7067DADD-1F1D-4191-BDDD-5ADBB5FA8176](https://user-images.githubusercontent.com/64159469/173120887-34d99b83-2388-4205-aae7-6f0acb61d8be.png)

**Comment by unzelnet** [comment]
![D571F806-5412-44A2-B153-B3F6BE68900A](https://user-images.githubusercontent.com/64159469/173121193-246e419e-a4c0-4ce2-a337-7459425891d3.png)

**Comment by unzelnet** [comment]
Liquidsoap log:
Error 5: this value has no method metadata
At /var/azuracast/stations/lucifer/config/liquidsoap.liq, line 186, char 20-30:
        cross.smart(old.source, new.source, fade_in=4.00, fade_out=4.00)

Error 5: this value has no method metadata
At /var/azuracast/stations/lucifer/config/liquidsoap.liq, line 186, char 20-30:
        cross.smart(old.source, new.source, fade_in=4.00, fade_out=4.00)

Error 5: this value has no method metadata
At /var/azuracast/stations/lucifer/config/liquidsoap.liq, line 186, char 20-30:
        cross.smart(old.source, new.source, fade_in=4.00, fade_out=4.00)

Error 5: this value has no method metadata

**Comment by SC2Mitch** [comment]
Hi, quick questions, 

Are you using arm? 

Are you using a custom docker-compose.override.yml which relate to storage?

**Comment by finnie2006** [comment]
Yes i use overide, see discord, and yes using arm here

**Comment by SC2Mitch** [comment]
> Yes i use overide, see discord, and yes using arm here

I was asking @unzelnet , not you.

**Comment by finnie2006** [comment]
I have the same error though

**Comment by Vaalyn** [comment]
I can reproduce this error by setting the stations `Crossfade Method` to `Smart Mode`.

Going by the documentation the type of `old.source` and `new.source` is as follows:
```
source(audio=pcm('a), video='b, midi='c)
```

So a source without methods.
The `cross.smart` method however expects parameters that look as follows:
```
.{
   db_level : float,
   metadata : [string * string],
   source : source(audio=pcm('a), video=internal('b), midi=internal('c))
 }
```

This is the format of the `old` and `new` variable itself.

I have created a PR that corrects this problem by using `old` and `new` directly in the `cross.smart` method instead of the `*.source`.
