### ISSUE TITLE
MariaDB unexpected crash - An exception occurred in the driver SQLSTATE [2002] - No such file or directory

### ISSUE THREAD

**Issue by KylePython** [AzuraCast/AzuraCast#5484]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

a281f93

### What happened?

Roughly 8:00, within 5 minutes of one of my Presenters Connected.
Azura crashed stopping Presenters to connect but Liquidsoap was still going.
I have no access to the AzuraCast Panel at all, but I can view the Shoutcast Stream Status at the same time.

![image](https://user-images.githubusercontent.com/41867471/173139508-c009a420-a399-43e0-b851-edd83bd79e08.png)
![image](https://user-images.githubusercontent.com/41867471/173139526-cdc21cef-ed57-4db6-8c9d-60686c5aba74.png)
![image](https://user-images.githubusercontent.com/41867471/173139537-63fec578-e4e5-439e-a971-f345662fd678.png)

**Comment by shagia** [comment]
This may be relevant to me, I'm updating from 10.2 to the latest release and my log is a bit different, but Azuracast closes with the same error code, 2002 and loops over and over. Maybe for me it's more of a migration issue than it is an updated issue.
![image](https://user-images.githubusercontent.com/13505837/173177581-0019c4ca-50ef-4a1c-8700-e91ec121605a.png)
![image](https://user-images.githubusercontent.com/13505837/173177591-f0455902-5b46-4cde-aa7d-4414940e5881.png)

**Comment by SpeedyCharly** [comment]
Same issue here after update this morning; 
![Loop1](https://user-images.githubusercontent.com/66107794/173186876-7492bb21-4f16-49a8-a13f-0f0ad6902f32.jpg)
![Loop2](https://user-images.githubusercontent.com/66107794/173186880-01442d77-6990-4033-82df-006fb5b4e7cf.jpg)
[LS Log - Looping.txt](https://github.com/AzuraCast/AzuraCast/files/8883788/LS.Log.-.Looping.txt)

**Comment by SC2Mitch** [comment]
> Same issue here after update this morning; 
> ![Loop1](https://user-images.githubusercontent.com/66107794/173186876-7492bb21-4f16-49a8-a13f-0f0ad6902f32.jpg)
> ![Loop2](https://user-images.githubusercontent.com/66107794/173186880-01442d77-6990-4033-82df-006fb5b4e7cf.jpg)
> [LS Log - Looping.txt](https://github.com/AzuraCast/AzuraCast/files/8883788/LS.Log.-.Looping.txt)
> 
> 

This is entirely a different issue that should of been fixed this morning

**Comment by SpeedyCharly** [comment]
@SC2Mitch - Did a second update this morning which seems to have fixed the looping issue.... Thanks

**Comment by KylePython** [comment]
I've just updated the latest rolling and this is all I'm getting now.

![image](https://user-images.githubusercontent.com/41867471/173194391-9dcfed18-8c8b-4d3e-ab9b-71e234e77654.png)

**Comment by KylePython** [comment]
> This may be relevant to me, I'm updating from 10.2 to the latest release and my log is a bit different, but Azuracast closes with the same error code, 2002 and loops over and over. Maybe for me it's more of a migration issue than it is an updated issue. ![image](https://user-images.githubusercontent.com/13505837/173177581-0019c4ca-50ef-4a1c-8700-e91ec121605a.png) ![image](https://user-images.githubusercontent.com/13505837/173177591-f0455902-5b46-4cde-aa7d-4414940e5881.png)

Are you getting a 502 error as well?

**Comment by SC2Mitch** [comment]
Closed, issue was related to a corrupted table in MariaDB, We urge people to take regular backups, especially on production machines.

**Comment by shagia** [comment]
@KylePython The update from earlier has fixed the issue I was having myself :( Best of luck to your MDB
