### ISSUE TITLE
Error on Update

### ISSUE THREAD

**Issue by NLLucifer** [AzuraCast/AzuraCast#549]
- **Installation Method:** Docker
- **Host OS (if using Docker):** ubuntu 16.04
**Describe the issue in full detail, including screenshots if possible:**
After updating i get an "502 Bad Gateway" error while loading the web interface
![image](https://user-images.githubusercontent.com/37590500/38541772-5ec2b6c0-3ca0-11e8-9265-715fefd390b6.png)
![image](https://user-images.githubusercontent.com/37590500/38541790-6f61cb24-3ca0-11e8-9b1f-4430e5138af7.png)
![image](https://user-images.githubusercontent.com/37590500/38541807-7a643430-3ca0-11e8-847f-38c43bc48bcd.png)
![image](https://user-images.githubusercontent.com/37590500/38541823-82cffe56-3ca0-11e8-8d95-03a0a4ed843e.png)

**Comment by SlvrEagle23** [comment]
@NLLucifer To help us diagnose the issue, in the AzuraCast folder, run `docker-compose logs -f web`, try to visit the web page and see what error messages appear in the logs.

**Comment by NLLucifer** [comment]
@SlvrEagle23 After restarting it appears to be working again.. Next time i'll try to post an error log in this way!
