### ISSUE TITLE
Install Stereo Tool Bug

### ISSUE THREAD

**Issue by PaulMaur** [AzuraCast/AzuraCast#5495]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

• v0.17.0 Stable • Docker • PHP 8.1

### What happened?

Error
×
ProcessTimedOutException at /var/azuracast/www/vendor/symfony/process/Process.php L1152: The process "'/var/azuracast/servers/stereo_tool/stereo_tool' '--help'" exceeded the timeout of 5 seconds.

**Comment by alencarwell** [comment]
same error... help.... please...

**Comment by Vaalyn** [comment]
Which binary did you download from the Stereo Tool website?

Make sure you download the `Command Line` version for the respective system you are using.
If you are using a wrong version the installation will fail since it will either outright fail (for example if you use the ARM version on an Intel CPU server) or if you don't use a `Command Line` version it will try running the Stereo Tool binary which will open a GUI for the install process which will end in a timeout.

**Comment by alencarwell** [comment]
> Which binary did you download from the Stereo Tool website?
> 
> Make sure you download the `Command Line` version for the respective system you are using. If you are using a wrong version the installation will fail since it will either outright fail (for example if you use the ARM version on an Intel CPU server) or if you don't use a `Command Line` version it will try running the Stereo Tool binary which will open a GUI for the install process which will end in a timeout.

Yes, download via site Stereo Tools.

**Comment by Vaalyn** [comment]
@alencarwell my question is, did you download one of these 2 specific files here, not if you downloaded "something" from the Stereo Tools website?

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/13745863/174312728-1c83bb58-e083-4683-a432-1e9747870b59.png">

**Comment by alencarwell** [comment]
> @alencarwell my question is, did you download one of these 2 specific files here, not if you downloaded "something" from the Stereo Tools website?
> 
> <img alt="image" width="1281" src="https://user-images.githubusercontent.com/13745863/174312728-1c83bb58-e083-4683-a432-1e9747870b59.png">

Yes, download this link:

https://www.stereotool.com/download/stereo_tool_gui_jack_64

Now, this page is loading infinity:

https://conecta.welltecnologia.com.br/admin/install/stereo_tool

**Comment by Vaalyn** [comment]
@alencarwell You downloaded the wrong version.

I explicitly said you need to download the `Command line version`, not the `Jack` or `Alsa` version. Those are GUI versions that are not supported and will not work.

**Comment by alencarwell** [comment]
> @alencarwell You downloaded the wrong version.
> 
> I explicitly said you need to download the `Command line version`, not the `Jack` or `Alsa` version. Those are GUI versions that are not supported and will not work.

Ok, so, format the server ?

**Comment by alencarwell** [comment]
> > Ok, so, format the server ?
> 
> No!
> 
> See my reply on this thread here: [#5408 (comment)](https://github.com/AzuraCast/AzuraCast/issues/5408#issuecomment-1134805828)

root@CONECTA:/var/azuracast# root@CONECTA:/var/azuracast#
-bash: root@CONECTA:/var/azuracast#: No such file or directory
root@CONECTA:/var/azuracast#

**Comment by alencarwell** [comment]
I formated my server, but, i dont working configuring the certifacte...

This error..

root@CONECTA:/var/azuracast# ./docker.sh letsencrypt-create
LetsEncrypt is now managed from within the web interface.
root@CONECTA:/var/azuracast# docker-compose down
[+] Running 2/2
 ⠿ Container azuracast        Removed                                                                                                                                  3.9s
 ⠿ Network azuracast_default  Removed                                                                                                                                  0.1s
root@CONECTA:/var/azuracast# docker-compose up -d
[+] Running 2/2
 ⠿ Network azuracast_default  Created                                                                                                                                  0.0s
 ⠿ Container azuracast        Started                                                                                                                                  2.4s
root@CONECTA:/var/azuracast# ./docker.sh letsencrypt-create
LetsEncrypt is now managed from within the web interface.
root@CONECTA:/var/azuracast#

**Comment by alencarwell** [comment]
formated the server...

**Comment by SC2Mitch** [comment]
We explicitly told you not to format the server, yet you done it anyway... Please read our instructions very carefully a

**Comment by Vaalyn** [comment]
Closing as fixed in commit c73dd5cc841cdda14a1a42d260581f6a20d6692c

**Comment by alencarwell** [comment]
Hello. I preferred to format the server to start with everything new.

I did it following the documentation, I've been using Azuracast for over 4 years, and I'm passionate about the system you guys created.

I use it for my church radio.

However, I can't hear the radio, everything is fine, transmitting successfully, but then I press play, no sound comes out.

Can you help me on what I did wrong?
