### ISSUE TITLE
No track title show on public page

### ISSUE THREAD

**Issue by radiomanFR** [AzuraCast/AzuraCast#5496]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

last

### What happened?

Hello,

In public page (and dashboard), the current title & artist won't display.

Any idea for fix this please?

### Relevant log output

```shell
No error in log...
```

**Comment by SC2Mitch** [comment]
Unable to repro on my local machine. If you're having issues with metadata, go ahead and check your Liquidsoap log for more information.

**Comment by gunsar** [comment]
on my server all metadata runs smoothly in latest version in public page and in music player (foobar, winamp, VLC).
but for HLS metadata not showing

**Comment by ItsMitchh** [comment]
Create a new issue and include liquidsoap logs or ways to reproduce, thanks.

**Comment by gunsar** [comment]
no error on docker-compose logs

> @gunsar Create a new issue and include liquidsoap logs or ways to reproduce, thanks.

**Comment by gunsar** [comment]
2022/06/21 11:00:15 [local_1:3] Connecting mount /live for source@127.0.0.1...
2022/06/21 11:00:15 [local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2022/06/21 11:00:15 [local_1:3] Will try again in 3.00 sec.
2022/06/21 11:00:16 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
2022/06/21 11:00:16 [lang:3]   "song_id": "f77050e10469dfce622fc329a8fbdf30",
2022/06/21 11:00:16 [lang:3]   "is_live": false,
2022/06/21 11:00:16 [lang:3]   "playlist_id": "1",
2022/06/21 11:00:16 [lang:3]   "media_id": "124"
2022/06/21 11:00:16 [lang:3] }
2022/06/21 11:00:16 [lang:3] API feedback - Response (200): false
2022/06/21 11:00:19 [local_1:3] Connecting mount /live for source@127.0.0.1...
2022/06/21 11:00:19 [local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2022/06/21 11:00:19 [local_1:3] Will try again in 3.00 sec.
2022/06/21 11:00:23 [local_1:3] Connecting mount /live for source@127.0.0.1...
2022/06/21 11:00:23 [local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2022/06/21 11:00:23 [local_1:3] Will try again in 3.00 sec.
2022/06/21 11:00:27 [local_1:3] Connecting mount /live for source@127.0.0.1...
2022/06/21 11:00:27 [local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2022/06/21 11:00:27 [local_1:3] Will try again in 3.00 sec.
2022/06/21 11:00:31 [local_1:3] Connecting mount /live for source@127.0.0.1...
2022/06/21 11:00:31 [local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2022/06/21 11:00:31 [local_1:3] Will try again in 3.00 sec.
2022/06/21 11:00:35 [local_1:3] Connecting mount /live for source@127.0.0.1...
2022/06/21 11:00:35 [local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2022/06/21 11:00:35 [local_1:3] Will try again in 3.00 sec.
2022/06/21 11:00:39 [local_1:3] Connecting mount /live for source@127.0.0.1...
2022/06/21 11:00:39 [local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2022/06/21 11:00:39 [local_1:3] Will try again in 3.00 sec.
2022/06/21 11:00:43 [local_1:3] Connecting mount /live for source@127.0.0.1...
2022/06/21 11:00:43 [local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2022/06/21 11:00:43 [local_1:3] Will try again in 3.00 sec.
2022/06/21 11:00:47 [local_1:3] Connecting mount /live for source@127.0.0.1...
2022/06/21 11:00:47 [local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2022/06/21 11:00:47 [local_1:3] Will try again in 3.00 sec.
