### ISSUE TITLE
GA4 no data issue

### ISSUE THREAD

**Issue by asa767** [AzuraCast/AzuraCast#5498]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.0

### What happened?

I've already using an UA Google Analytics ID as web hook with no issue. But when I add the new GA4 ID it's not serving/getting data.

**Comment by gunsar** [comment]
it seems that for GA4 there is no update in this regard, for the old GA it is still running well

**Comment by asa767** [comment]
But Google will give up support for UA. Azuracast have to support GA4 in this scope.
