### ISSUE TITLE
schedules are not respected when a dj is connected.

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#5499]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

aa70489 (2022-06-12 13:07) • Docker • PHP 8.1

### What happened?

hello,
if i have one playlist set to play from 10h to 11h, for example, and a dj connects 09:59h and disconnects 13h, the scheduled playlist will play because is marked with next song. autodj is skiping songs normally after dj disconect, but i think when the dj disconects it have to verify if the quewe contains songs out of schedule and remove or replace it. as oter way i think it probably need a extra option because in some cases it is good to play out of schedule songs, and oter cases are not. i think in playlists that have the stop actual song checked it need to respect the start and end schedule and not play when are out of schedule. with the actual behaviour, if i have for example 1 hour files, and have one playlist to play every hour, is enough to bug a dj connects, disconnects as i explained, and the rest of the day will run with delay.

**Comment by nunotfc** [comment]
this ishue is not solved, and is so important.

**Comment by nunotfc** [comment]
hello, just to keep this ishue active. it still hapens.

**Comment by BusterNeece** [comment]
@nunotfc Deploying a Rolling Release update now that should help resolve this; the logic makes sense on why this happens, we just don't periodically recheck existing queue entries to see if their scheduled slot continues to be active for them after they've been queued up. This update adds that check and will remove any queue entries that fall out of their scheduled time slot while waiting to be cued/played.

**Comment by nunotfc** [comment]
hello, @BusterNeece BusterNeece
this apear not fixed. i have a playlist playing from 15:00 to 15:00 Brasil, and dj connected 14:55, at 17:02, when he disconected the playlist played...
tell me if i'm using right commit. c9e8a76 (2022-09-11 8:39) • Docker • PHP 8.1

**Comment by BusterNeece** [comment]
@nunotfc This should work for items that are in the queue that haven't been cued up by Liquidsoap yet, but I would bet in your case Liquidsoap had already prepared that track for playback prior to the DJ going live, and unfortunately there isn't much we can do about that; the goal is just to prevent it from playing _subsequent_ tracks that are scheduled.

**Comment by nunotfc** [comment]
how i can make it? aparently, checking the options interrupt oter songs solved the problem, but i need to test it.
I think, would be great if in future versions we could assign one folder to schedule for example assign folder 80s to chedule 1 of dj streamer nuno and check option, if dj not conect launch a file and set a timeout for wait. due to this thing, i have sometimes my station delayed playing 2 times one live and anoter not, the same show.

**Comment by nunotfc** [comment]
@BusterNeece BusterNeece
hello, sorry for flagging just to let you know about my final tests. definitely, not solved. we tested, i connected at 11:45 and disconected at time we write this message, 13:07 brasil and the playlist of 12:00 played inmediately after i disconected. i connected 15 minutes before, i think autodj not prepared the song...  thanks for all!

**Comment by BusterNeece** [comment]
@nunotfc Right, like I said, the track that's already cued up by Liquidsoap is basically out of our control at that point. Liquidsoap needs a track to be ready to "skip" to after a DJ disconnects, so it has to keep one in its internal registry, and that one can be outside the normal schedule bounds and there isn't much we can do to prevent that. It's the subsequent queue that follows that that we can control.

**Comment by nunotfc** [comment]
Thanks.... Any advice from my SIDE i can do tô workaround? I think i Will leave this thing of replacememt programs

**Comment by BusterNeece** [comment]
> Thanks.... Any advice from my SIDE i can do tô workaround?

We'll continue to look into it, but as we always say, pull requests or additional development time are always appreciated. Tens of thousands of stations basically depend on our free labor to operate, and we're doing the best we can given those circumstances.

One possible workaround would be to skip the incoming song _twice_ when a DJ disconnects, i.e. via a webhook or something similar.

> I think i Will leave this thing of replacememt programs

You've been here long enough to know saying this doesn't work here.

**Comment by nunotfc** [comment]
how i can make this webook?

**Comment by nunotfc** [comment]
hei, sorry for all, i understood now i've made a language error.... just for clarify, i dont like things unclear.
"I think i Will leave this thing of replacememt programs"
i was talking about the subject of the ishue, replacement programs. here, in portugal, when you make for example 2 hours of 80s songs we speake you are making a program or a radio program, i thinked in english it is aplicable too.
with replacement programs, "Programas de Substituição", i wanted to say that probably i leave it as is, i will probably take out the replacement program when a dj cant conect.
This ishue started because when a dj cant connect in it's time, we ahve repalacement playlists, that plays one pre recorded or past recorded file.
thes is what i said. if the error cant be solved for now. never wanted to say bad words, i simply think azuracast is the best panel and most customizable i found, i have no reason to leave it.

**Comment by nunotfc** [comment]
hello, just updating, for the ones that have my problem, the webook trick doesnt work. i'm going to disable the playists in the dj schedule untill we find a fix. thanks all and sorry again for something.
