### ISSUE TITLE
Icecast Advertise to YP Directories (Public Station) do not work

### ISSUE THREAD

**Issue by inetactief** [AzuraCast/AzuraCast#550]
We use v0.8.1-2018.02 Beta (Docker) 
Host CentOS 7 64 bit

We try to set 
Icecast Advertise to YP Directories on yes and restart but no public stream found 
We try also : 
{"public": "1"}

And we want to change the buffer settings, but where can we find that? 

Best regards,

**Comment by SlvrEagle23** [comment]
@inetactief Icecast by default doesn't advertise to any YP directories unless configured to do so, unlike Shoutcast. Make sure you specify the YP URL it should be advertising to here: http://icecast.org/docs/icecast-2.3.1/yp.html

Once specified, then setting each mount point to be "Public" will trigger it being advertised via the YP advertisement.

**Comment by SlvrEagle23** [comment]
@inetactief In the Station Profile, there is an "Advanced Configuration" section underneath the broadcasting software section. You can specify custom configuration in either XML or JSON format there, which should allow you to just drop a configuration line exactly like this in:

```xml
<directory>
    <yp-url-timeout>15</yp-url-timeout>
    <yp-url>http://dir.xiph.org/cgi-bin/yp-cgi</yp-url>
</directory>
```

**Comment by inetactief** [comment]
Yes i try it but it do not work. ( i see the stream is public in the xml)  And yes" to advertise this stream on the YP public radio directories.
I try it on AzuraCast v0.8.1-2018.02 Beta (Docker) and now AzuraCast v0.8.2-2018.04 Beta (Docker)

**Comment by inetactief** [comment]
Icecast status page is also incomplete. We miss the logo of icecast and the menu. How can we solve that?

**Comment by SlvrEagle23** [comment]
@inetactief That problem is upstream from AzuraCast...it appears the Icecast-KH branch doesn't include one of the templates used in rendering the Icecast page.

**Comment by inetactief** [comment]
And how can we solve that problem? Can I do that? Or is it a bug?

**Comment by SlvrEagle23** [comment]
@inetactief It's possible to hack together a solution by pulling those files from other places, but I haven't done so on account of how little the Icecast UI itself is accessed.
