### ISSUE TITLE
Error showing time and duration in song playback history

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#5506]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

5bc5736

### What happened?

Hello, as you can see in the image, the date and duration of the files played in the history are not displayed correctly

![image](https://user-images.githubusercontent.com/16152034/173888322-240e33bd-709d-4c3d-93a2-bab96e2e1ad3.png)

**Comment by SlvrEagle23** [comment]
@fidegr If you hit F12 or right click and hit "Inspect Element" and then click the "Console" tab, do you see any errors there?

**Comment by fidegr** [comment]
`DevTools no ha podido cargar el mapa de la fuente: No se ha podido cargar contenido de https://radio.radiobot.org/static/dist/lib/bootstrap/bootstrap.bundle.min.js.map: Error de HTTP: código de estado 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by Countryman98** [comment]
Yeah i get that error too!
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
DevTools failed to load source map: Could not load content for https://myplace.live/static/dist/lib/bootstrap/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by SlvrEagle23** [comment]
@fidegr What page are you looking at? The newest version of the Song Playback Timeline page looks very different from that.

**Comment by fidegr** [comment]
Hello, the bug occurs in the latest stable version. The strange thing is that in another installation of Azuracast also in the stable version it is displayed correctly. So I don't know where the error is coming from.
