### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by NLLucifer** [AzuraCast/AzuraCast#551]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Ubuntu 16.04

**Describe the issue in full detail, including screenshots if possible:**
At the moment i have the problem that my updates don't update anything. 
After a update i didn;t have any new functions (e.g. request option in playlist).
I checked the form file, and it didn;t change/add the option.
![image](https://user-images.githubusercontent.com/37590500/38773793-51e7a122-4056-11e8-8a8a-303cbddc55ef.png)
![image](https://user-images.githubusercontent.com/37590500/38773794-5d02bd44-4056-11e8-8371-4beb93978f55.png)
![image](https://user-images.githubusercontent.com/37590500/38773798-67e9156e-4056-11e8-8b44-3d6858f5d9bb.png)

**Comment by SlvrEagle23** [comment]
@NLLucifer What happens when you just try to run:

```
docker-compose run --rm cli azuracast_update
```

by itself? It looks like, for some reason, the docker-compose library is installed fine but it's having trouble running that one specific command.

**Comment by NLLucifer** [comment]
When running that command it does update. Weird. Might need to reinstall docker xd. Thanks!
