### ISSUE TITLE
Minor Bug with History Embedded Widget

### ISSUE THREAD

**Issue by Countryman98** [AzuraCast/AzuraCast#5510]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #6bfdd24

### What happened?

History Widget seem to have issues, When i select to display "10" song history the widget only displays 8 and when i select 15 to display the widget only displays 10

Maybe the widgets forgotten how to count?

### Relevant log output

```shell
No Log Output
```

**Comment by SlvrEagle23** [comment]
@Countryman98 Oh, it's probably filtering out "jingle mode" tracks _after_ doing the limit.

**Comment by SlvrEagle23** [comment]
@Countryman98 We discovered an issue where our song history was still logging "Jingle Mode" playlists, and have fixed this behind the scenes...this should also fix this issue in the latest Rolling Release version.
