### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by alencarwell** [AzuraCast/AzuraCast#5513]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 #fdd3f5c (2022-06-17 22:19) • Docker • PHP 8.1

### What happened?

Hello. I preferred to format the server to start with everything new.

I did it following the documentation, I've been using Azuracast for over 4 years, and I'm passionate about the system you guys created.

I use it for my church radio.

However, I can't hear the radio, everything is fine, transmitting successfully, but then I press play, no sound comes out.

Can you help me on what I did wrong?

**Comment by alencarwell** [comment]
Friends, I managed to solve it.

I was using the old DNAS, I downloaded this one and now the sound came out...

http://download.nullsoft.com/shoutcast/tools/sc_serv2_linux_x64-latest.tar.gz

**Comment by SlvrEagle23** [comment]
Good to hear!

**Comment by alencarwell** [comment]
> Good to hear!

I'm a fan of your work...
As soon as I can I will contribute to the project.
You guys are very good at what you do.
