### ISSUE TITLE
Install SSL LetsEncrypt on v0.17.1

### ISSUE THREAD

**Issue by gunsar** [AzuraCast/AzuraCast#5516]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.1

### What happened?

I reinstalled the stable version because I had problems moving from the rolling release version
I'm confused install LetsEncrypt SSL in version v0.17.1
command: cd /var/azuracast, ./docker.sh update-self, ./docker.sh letsencrypt-create (it doesn't work anymore)
finally I'm confused for this SSL setting
can anyone help install step by step?

**Comment by gunsar** [comment]
try to use SSL myself
then edit in docker-compose.override.yml
services:
   web:
     volumes:
       - /etc/ssl/ssl.crt:/var/azuracast/acme/ssl.crt:ro
       - /etc/ssl/ssl.crt:/var/azuracast/acme/ssl.key:ro
not successful

**Comment by SC2Mitch** [comment]
Can you try using the web UI and attempt to process your SSL? 
It's in  Admin > System Settings

If not, provide some logs please.

**Comment by gunsar** [comment]
@SC2Mitch 
Yes, I checklist on this menu
Use Web Proxy for Radio
Preferred Browser URL (If Available)

**Comment by gunsar** [comment]
@SC2Mitch 
azuracast  | Initialize AzuraCast
azuracast  | ====================
azuracast  |
azuracast  | Initializing essential settings...
azuracast  |  * Environment: Production
azuracast  |  * Installation Method: Docker
azuracast  |
azuracast  |
azuracast  | Running Database Migrations
azuracast  | ---------------------------
azuracast  |
azuracast  |
azuracast  |  [OK] Already at the latest version
azuracast  |       ("App\Entity\Migration\Version20220611123923")
azuracast  |
azuracast  |
azuracast  | Generating Database Proxy Classes
azuracast  | ---------------------------------
azuracast  |
azuracast  |
azuracast  |  Processing entity "App\Entity\StorageLocation"
azuracast  |  Processing entity "App\Entity\StationMedia"
azuracast  |  Processing entity "App\Entity\Settings"
azuracast  |  Processing entity "App\Entity\SongHistory"
azuracast  |  Processing entity "App\Entity\Station"
azuracast  |  Processing entity "App\Entity\StationStreamer"
azuracast  |  Processing entity "App\Entity\RolePermission"
azuracast  |  Processing entity "App\Entity\StationPlaylist"
azuracast  |  Processing entity "App\Entity\StationMount"
azuracast  |  Processing entity "App\Entity\StationRemote"
azuracast  |  Processing entity "App\Entity\StationHlsStream"
azuracast  |  Processing entity "App\Entity\StationWebhook"
azuracast  |  Processing entity "App\Entity\SftpUser"
azuracast  |  Processing entity "App\Entity\CustomField"
azuracast  |  Processing entity "App\Entity\StationMediaCustomField"
azuracast  |  Processing entity "App\Entity\PodcastCategory"
azuracast  |  Processing entity "App\Entity\User"
azuracast  |  Processing entity "App\Entity\Podcast"
azuracast  |  Processing entity "App\Entity\StationQueue"
azuracast  |  Processing entity "App\Entity\UnprocessableMedia"
azuracast  |  Processing entity "App\Entity\PodcastMedia"
azuracast  |  Processing entity "App\Entity\Analytics"
azuracast  |  Processing entity "App\Entity\ApiKey"
azuracast  |  Processing entity "App\Entity\StationPlaylistMedia"
azuracast  |  Processing entity "App\Entity\Listener"
azuracast  |  Processing entity "App\Entity\StationStreamerBroadcast"
azuracast  |  Processing entity "App\Entity\AuditLog"
azuracast  |  Processing entity "App\Entity\PodcastEpisode"
azuracast  |  Processing entity "App\Entity\StationPlaylistFolder"
azuracast  |  Processing entity "App\Entity\UserLoginToken"
azuracast  |  Processing entity "App\Entity\StationRequest"
azuracast  |  Processing entity "App\Entity\StationSchedule"
azuracast  |  Processing entity "App\Entity\Relay"
azuracast  |  Processing entity "App\Entity\Role"
azuracast  |
azuracast  |  Proxy classes generated to "/var/azuracast/www_tmp/proxies"
azuracast  |
azuracast  | Reload System Data
azuracast  | ------------------
azuracast  |
azuracast  |
azuracast  |  [OK] Local cache flushed.
azuracast  |
azuracast  |
azuracast  |  [OK] AzuraCast is now initialized.
azuracast  |
azuracast  |
azuracast  |  [ERROR] Skipping LetsEncrypt; no domain(s) set.
azuracast  |
azuracast  | [2022-06-19T11:35:10.564791+00:00] AzuraCast.WARNING: Console command `azuracast:acme:get-certifi                     cate` exited with error code 1. [] []
azuracast  | [19-Jun-2022 11:35:10] NOTICE: fpm is running, pid 98
azuracast  | [19-Jun-2022 11:35:10] NOTICE: ready to handle connections
azuracast  | [19-Jun-2022 11:35:10] NOTICE: systemd monitor interval set to 10000ms

**Comment by gunsar** [comment]
@SC2Mitch 
i tried to edit and add in azuracast.env format:
LETSENCRYPT_HOST=sub.domain.com
LETSENCRYPT_EMAIL=emailssl@domain.com
still not running

**Comment by SC2Mitch** [comment]
did you run restart your instance after editing the env file? Do this by running `docker compose down && docker-compose up -d `

**Comment by gunsar** [comment]
@SC2Mitch 
well i did that, but the result is the same SSL doesn't work
> did you run restart your instance after editing the env file? Do this by running `docker compose down && docker-compose up -d `

**Comment by gunsar** [comment]
@SC2Mitch 
please wait, I'm curious
Now I'm re-installing the VPS
and will fresh install azuracast stable
then do the same for edits in docker-compose and azuracast.env

**Comment by SC2Mitch** [comment]
Then we'll need more logs, the ones you have provided isn't particularly helpful for us.

I don't see the reason to reinstall the VPS as well

**Comment by gunsar** [comment]
now SSL is successful using SSL Alone
the point is edit docker-compose.override.yml and azuracast.env

docker-compose.override.yml :
====================
services:
  web:
    volumes:
      - /path/on/host/to/ssl.crt:/var/azuracast/acme/ssl.crt:ro
      - /path/on/host/to/ssl.key:/var/azuracast/acme/ssl.key:ro`

azuracast.env, add : 
=============
LETSENCRYPT_HOST=sub.domain.com
LETSENCRYPT_EMAIL=emailssl@domain.com

so there is a change from the original tutorial from https://docs.azuracast.com/en/administration/ssl-and-lets-encrypt

thank's for helping me
good luck to you and the Azuracast team

**Comment by ItsMitchh** [comment]
Glad to hear it's fixed, closed.

Docs updated https://github.com/AzuraCast/azuracast-docs/commit/d491a4627046eef121d94427d0593aaa26f3704d
