### ISSUE TITLE
mkpascal script dont work with latest release

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#5517]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#fdd3f5c (2022-06-17 22:19)

### What happened?

Liquidsoap won't start with mkpascal-script https://gist.github.com/SlvrEagle23/43a06ee6624975273fdc903ba4a39998 and giving this error:
```
Error 15: Missing arguments in function application: source(audio=pcm(stereo), video='A, midi='B).
At /var/azuracast/stations/eisradio/config/liquidsoap.liq, line 337, char 13-39:
compressor = ladspa.sc4(rms_peak = 0.5)
```

I changed my script to ->
```
# Custom Configuration (Specified in Station Profile)
# This script is customized from the original, which can be found here:
# https://github.com/mkpascal/mk_liquidsoap_processing/blob/master/process.liq
# 
# It can be added to your station via `Utilities` > `Edit Liquidsoap Configuration`
# where it can then be pasted into the bottom-most open text area, before the broadcasts
# are sent out to the various sources.

# Audio Input --------------------->

mkpProcess = radio

# Processing Blocks --------------------->

# Gate
mkpProcess = ladspa.gate(mkpProcess, threshold = -60.0, attack = 0.15, hold = 1.0, decay = 200.0, range = -25.0)

# Wideband AGC + Pre-Processing
mkpProcess = normalize(target = 0., window = 0.03, gain_min = -16., gain_max = 0., mkpProcess)
mkpProcess = ladspa.sc4(rms_peak=0.3, attack_time = 0.5, release_time = 3., threshold_level = -36.0, ratio=1., makeup_gain = 6., mkpProcess)

# Stereo Expander
mkpProcess = ladspa.matrixspatialiser(width=16, mkpProcess)

# Bass EQ
mkpProcess = ladspa.tap_equalizer(band_1_freq=70., band_1_gain=8., mkpProcess)
mkpProcess = ladspa.tap_equalizer(band_1_freq=150., band_1_gain=4., mkpProcess)
# Middle EQ
mkpProcess = ladspa.tap_equalizer(band_2_gain=4., mkpProcess)
mkpProcess = ladspa.tap_equalizer(band_5_gain=2., mkpProcess)
# High EQ
mkpProcess = ladspa.tap_equalizer(band_7_gain=5., mkpProcess)
mkpProcess = ladspa.tap_equalizer(band_8_gain=6., mkpProcess)

# 5 Bands Compress/Limit
mkpProcess = compress.multiband(mkpProcess, [
  {frequency=200., attack=3.5, release=30., ratio=3., threshold=-10., gain=2.},
  {frequency=1000., attack=2.25, release=40., ratio=2., threshold=-13., gain=2.},
  {frequency=3500., attack=2.25, release=40., ratio=3., threshold=-9., gain=2.},
  {frequency=6500., attack=2.25, release=60., ratio=2., threshold=-6., gain=1.5},
  {frequency=20000., attack=2.25, release=70., ratio=2., threshold=-4., gain=1.},
])

# 2 Bands Compress/Limit
mkpProcess = compress.multiband(mkpProcess, [
  {frequency=200., attack=10., release=30., ratio=2., threshold=-4., gain=0.},
  {frequency=20000., attack=10., release=40., ratio=2., threshold=-2., gain=-2.}
])

# De-esser
mkpProcess = ladspa.tap_deesser(threshold_level=-5., frequency=6000., mkpProcess)

# Final Limiter
mkpProcess = ladspa.tap_limiter(limit_level = -0.5, mkpProcess)

# Audio Output --------------------->
radio = mkpProcess
```
This is working for me. Can you test it please?

**Comment by danceradiouk** [comment]
This works just fine for me on version 0.17.1

Copy & paste this into the 4th window down. 

# Custom Configuration (Specified in Station Profile)
# This script is customized from the original, which can be found here:
# https://github.com/mkpascal/mk_liquidsoap_processing/blob/master/process.liq
# 
# It can be added to your station via `Utilities` > `Edit Liquidsoap Configuration`
# where it can then be pasted into the bottom-most open text area, before the broadcasts
# are sent out to the various sources.

# Functions / Modules --------------------->

# Compressor Module / Limiter Module
compressor = ladspa.sc4(rms_peak = 0.5)
limiter = ladspa.tap_limiter(limit_level = -0.3)

# Single Band Compressor
def multiband_band(process, from_freq, to_freq, attack, release, ratio, threshold, gain)
	from_filter = filter.iir.eq.high(frequency = from_freq,)
	to_filter = filter.iir.eq.low(frequency = to_freq,)
	process_filtered = to_filter(from_filter(process))
	process_compressed = limiter(compressor(attack_time = attack, release_time = release, threshold_level = threshold, ratio=ratio, makeup_gain = gain, process_filtered))
	process_compressed
end

# Audio Input --------------------->

mkpProcess = radio

# Processing Blocks --------------------->

# Gate
mkpProcess = ladspa.gate(mkpProcess, threshold = -45.0, attack = 0.15, hold = 0.5, decay = 200.0, range = -25.0)

# Wideband AGC + Pre-Processing
mkpProcess = normalize(target = 0., window = 0.03, gain_min = -16., gain_max = 0., mkpProcess)
mkpProcess = ladspa.sc4(rms_peak=0.3, attack_time = 0.05, release_time = 999., threshold_level = -25.0, ratio=2., makeup_gain = 10., mkpProcess)

# 5 Bands Compress/Limit
mkpProcess = add(normalize=false,
  [
   multiband_band(mkpProcess, 30., 150., 40., 999., 2., -15., 0.), 
   multiband_band(mkpProcess, 100., 800., 30., 999., 2., -15., 4.),  
   multiband_band(mkpProcess, 700., 2500., 15., 999., 2., -15., 4.), 
   multiband_band(mkpProcess, 2000., 6000., 10., 999., 2., -15., 2.), 
   multiband_band(mkpProcess, 5000., 11000., 10., 999., 2., -15., -2.),
   multiband_band(mkpProcess, 10000., 16000., 8., 999., 2., -15., -5.)
  ])

# 2 Bands Compress/Limit
mkpProcess = add(normalize=false,
  [
  multiband_band(mkpProcess, 30., 16000., 10., 40., 2., -1., 1.)
  ])

# De-esser
mkpProcess = ladspa.tap_deesser(threshold_level=-2., frequency=7000., mkpProcess)

# Final Limiter
mkpProcess = limiter(mkpProcess)

# Audio Output --------------------->
radio = mkpProcess
