### ISSUE TITLE
ERROR IN UPDATED

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#552]
- **Installation Method:**  Traditional 
- **Host OS (if using Docker):** Ubuntu 16.04

**Describe the issue in full detail, including screenshots if possible:**

I've just updated my AzuraCast Traditional Method of installation but i end up with some error and this here is the error message. Ill try already the ./update.sh --full but same error output

TASK [init : Update pip components] ************************************************************************************************************************************
failed: [localhost] (item=pip) => {"changed": false, "cmd": "/usr/local/bin/pip2 install -U pip", "item": "pip", "msg": "stdout: Collecting pip\n\n:stderr: Exception:\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/pip/basecommand.py\", line 215, in main\n    status = self.run(options, args)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/commands/install.py\", line 335, in run\n    wb.build(autobuilding=True)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/wheel.py\", line 749, in build\n    self.requirement_set.prepare_files(self.finder)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py\", line 380, in prepare_files\n    ignore_dependencies=self.ignore_dependencies))\n  File \"/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py\", line 620, in _prepare_file\n    session=self.session, hashes=hashes)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/download.py\", line 821, in unpack_url\n    hashes=hashes\n  File \"/usr/local/lib/python2.7/dist-packages/pip/download.py\", line 659, in unpack_http_url\n    hashes)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/download.py\", line 853, in _download_http_url\n    stream=True,\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/sessions.py\", line 521, in get\n    return self.request('GET', url, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/download.py\", line 386, in request\n    return super(PipSession, self).request(method, url, *args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/sessions.py\", line 508, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/sessions.py\", line 618, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/adapter.py\", line 47, in send\n    resp = super(CacheControlAdapter, self).send(request, **kw)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/adapters.py\", line 499, in send\n    raise RetryError(e, request=request)\nRetryError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/62/a1/0d452b6901b0157a0134fd27ba89bf95a857fbda64ba52e1ca2cf61d8412/pip-10.0.0-py2.py3-none-any.whl (Caused by ResponseError('too many 503 error responses',))\nYou are using pip version 9.0.3, however version 10.0.0 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n"}

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=1

**Comment by mkody** [comment]
You should retry launching the `update.sh`. 
This error comes from the Python repositories being down for a moment.
```
raise RetryError(e, request=request)
RetryError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): 
Max retries exceeded with url: [snip] (Caused by ResponseError('too many 503 error responses',)
```
