### ISSUE TITLE
CPU Usage went up by 50%

### ISSUE THREAD

**Issue by NadjaNeville** [AzuraCast/AzuraCast#5520]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #60a66c9 (2022-06-20 17:11) • Docker • PHP 8.1

### What happened?

After the last update the CPU usage went up by 50% and using now 80% of my system resources while it was running at a comfy 30% before. No changes in any confuguration have been done.

I will send any logs when requested, the log post section always says comment too long no matter if there are only three lines of text in it.

**Comment by ItsMitchh** [comment]
Hi there, you can post your logs to Pastebin or Github Gist and post the link here.

**Comment by Vaalyn** [comment]
Which version where you running before the update?

**Comment by NadjaNeville** [comment]
Rolling Release #[60a66c9] (2022-06-20 17:11) • Docker • PHP 8.1

Had to roll back, here server resources before rollback and after
https://i.gyazo.com/892066d0538eb7949ecf18fe7bd46578.png

**Comment by ItsMitchh** [comment]
Hi there @NadjaNeville !

We have made some improvements to CPU usage, can you update your machine and let us know? 

If it's still high CPU usage, can you use `htop` or `top` and let us know what's using the most resources?

**Comment by NadjaNeville** [comment]
@ItsMitchh !

Unfortunately the CPU usage goes up to 87% again. I have a few stations using scheduled external sources to break up their usual program and bring in some different music during low audience times. They seem to cause the high load as mentioned here, as the amount of high CPU use stations is exactly the same as the amount of stations using external sources at the time of the analysis. As you mentioned in your comment about the empty stations, during external source times, the stations are "empty". They weren't "empty" until they lost their ability to show titles from the external sources, showing a title makes the nowplaying task return a value. I have three stations using an external source all the time so that may explain the high CPU use all the time in my case.

top: https://i.gyazo.com/cbd4ed095ee6d0b79f5ae120f5f15a0a.png

htop: https://i.gyazo.com/256c86f162c6fb7fb18a4b9cd05236a8.png

**Comment by ItsMitchh** [comment]
Can you explain how you're handling the 'external sources'?

**Comment by Marcioghiraldelli** [comment]
Hi Mitch, as said in discord, I also have this high consumption problem, but mine only happens when I use a remote playlist.

**Comment by ItsMitchh** [comment]
This issue seems to stem from remote playlists causing an abnormally high CPU usage, I'll be following this up with the dev team for reviews.

**Comment by NadjaNeville** [comment]
This is a typical config for the external sources:

https://i.gyazo.com/04ff5211a6d287a5b48f1bf1b3ed7243.png
https://i.gyazo.com/7ccfbf1196a469554fa5e1c6b348c1bc.png
https://i.gyazo.com/1e17bd16fac7febfbd8fb97f1abc8ee0.png

The whole day schedule was necessary as when the ability to display the titles was gone, the station didn't play without a defined schedule, although it should.

**Comment by ItsMitchh** [comment]
@NadjaNeville, @Marcioghiraldelli 

Just popping in, this has now been fixed upstream and will be fixed on our rolling release branch fairly soon

Thanks for the reports.

**Comment by Marcioghiraldelli** [comment]
thanks mitch

**Comment by NadjaNeville** [comment]
Thanks a lot Mitchh!

**Comment by Marcioghiraldelli** [comment]
Hello Mitch, can you tell me if LS fixes this CPU problem with remote playlist in version 2.1x which is what Azura currently uses? Thank you in advance for your answer.

**Comment by ItsMitchh** [comment]
Fixed in the rolling branch yesterday
