### ISSUE TITLE
No UI option to turn off HLS

### ISSUE THREAD

**Issue by fluential** [AzuraCast/AzuraCast#5526]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.0 Stable

### What happened?

After enabling HLS there is no UI option to turn it off?

**Comment by SlvrEagle23** [comment]
@fluential It's in the station profile, under the "AutoDJ" tab.

**Comment by fluential** [comment]
Oh right, got it now. PS: Before this gets closed, is there a way to tell I am using HLS other than seeing `hls_enabled=true` in the embedded player config in the page source code? When I click play I still see traffic coming from default mountpoint.

**Comment by SlvrEagle23** [comment]
@fluential You'll see the HLS stream on the station profile on the "Streams" panel at the top right. We haven't integrated HLS into the main public player yet because we're working on getting listener statistics to work well in that situation.
