### ISSUE TITLE
don't appear album field on request table.

### ISSUE THREAD

**Issue by unbreakhyek** [AzuraCast/AzuraCast#553]
- OS : Docker
- azuracast : latest
![default](https://user-images.githubusercontent.com/8805965/38868781-4a8f14bc-4283-11e8-8300-70e38f18ca92.PNG)

Despite the existence of album infomation ,album field is not visible.

**Comment by SlvrEagle23** [comment]
@unbreakhyek Should be fixed as of the latest update. I temporarily limited the fields there as I was working on implementing custom data, but they can now be restored back to normal.
