### ISSUE TITLE
Stereo Tool - no option to upload configuration

### ISSUE THREAD

**Issue by thehijacker** [AzuraCast/AzuraCast#5536]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #21e9fc6 (2022-06-25 2:32)

### What happened?

I wish to enable Stereo Tool for station processing. Binary uploaded and detected as version 9.91. Under station profile and menu Auto DJ I have selected Stereo Tool as audio processing mode. It says:

`Upload a Stereo Tool configuration file from the "Broadcasting" submenu in the station profile.`

But I can not find this option under Broadcasting submenu. I now tried Rolling Release Channel but again there is no option for uploading STS file.

**Comment by danceradiouk** [comment]
With Stereo Tool enabled and Azuracast restarted for the changes to take effect, select the "Broadcasting" tab on the main menu on the left hand side of the screen, "Upload Stereo Tool Configuration" is located there. I have used it myself and it works just fine.

**Comment by thehijacker** [comment]
Sorry I do not see it.

![image](https://user-images.githubusercontent.com/13857043/175807750-bc3e2f14-686f-4cc8-8a64-07cc5861a5a7.png)

Looking at wrong section?

**Comment by danceradiouk** [comment]
Hi yes you are looking in the wrong place, see the image below. You need to come out of the profile section and to the main Azuracast screen, the one you see one you first login into your station.

Hope this helps you.
(image on this link)
https://i.postimg.cc/7LvDt0vS/stereotoolconfig.png

**Comment by ItsMitchh** [comment]
Danceradiouk has the solution you require, closed.

**Comment by WishBoneBoy007** [comment]
Hi team, I'be reloaded/restarted multiple times and sadly I can't see this option either. 
Can someone please advise? PS- I've using v0.17.3 Stable. Cheers. 

![1_Screen Shot 2022-10-13 at 12 00 31 PM](https://user-images.githubusercontent.com/88299050/195464114-f8a6bcd9-bb98-4300-a0bf-884467bb8f75.jpg)
![2_Screen Shot 2022-10-13 at 11 59 53 AM](https://user-images.githubusercontent.com/88299050/195464119-a9734853-190e-403e-8202-9da98f4fbdc1.jpg)

**Comment by BusterNeece** [comment]
@WishBoneBoy007 I believe the Stereo Tool menu item won't show up unless Stereo Tool is confirmed installed at the system level via the System Administration > Install Stereo Tool page.

**Comment by WishBoneBoy007** [comment]
Thanks Buster. I have already applied this update, but to no avail.

<img width="1364" alt="Screen Shot 2022-10-13 at 12 20 47 PM" src="https://user-images.githubusercontent.com/88299050/195465504-87720a34-9e54-44cd-b500-279307d4eb90.png">

**Comment by danceradiouk** [comment]
I have it working just fine on 0.17.3 stable and also using the same version of Stereo Tool too, the only difference i can see is you have a license key entered for Stereo Tool. Remove that and save your settings and see if the option appears to upload a Stereo Tool config file afterwards.

**Comment by pitsch** [comment]
![grafik](https://github.com/AzuraCast/AzuraCast/assets/3827235/12df61ae-b3b5-47cb-99d9-e4b93020c06b)

Rolling Release #203ca2c (2023-07-25 22:05) • Docker • PHP 8.2 
libStereoTool_64.so version 10, as well as version 9.22 - as current download of x86/64 Linux Thimeo-ST, plugin SDK for all OS. 
https://download.thimeo.com/Stereo_Tool_Generic_plugin.zip

**Comment by BusterNeece** [comment]
@pitsch Upload the zip itself, not the individual plugin files.

**Comment by pitsch** [comment]
![grafik](https://github.com/AzuraCast/AzuraCast/assets/3827235/a1a95b9a-b5b5-48f3-bf89-e8ea8b58d8f1)
thank you. works brilliantly now! was misreading the instructions.
considering, still probably better to do the audioprocessing on the encoder ("dj") side and focus on AGC.
using 41.1 khz flac files as testing material i'd still prefer the unprocessed audio quality. 
might be caused by the default sampler used by liquidsoap. (should select SoxR where possible for ffmpeg).

**Comment by danielloretti** [comment]
I'm trying to upload file: Stereo_Tool_Generic_plugin.zip - on the admin page. I'm get a message "Uploaded file not recognized"

**Comment by PoGo606** [comment]
I have the same problem. I can't upload the binary.

**Comment by BusterNeece** [comment]
@PoGo606 issues with uploading the binary should be fixed in the latest Rolling Release version. Have you tried that?

**Comment by PoGo606** [comment]
> @PoGo606 issues with uploading the binary should be fixed in the latest Rolling Release version. Have you tried that?

Thanks for your reply, unfortunatly I can't as I'd rather stick with a stable release. I'll wait for this fix to be published in an upcoming stable release ;)
