### ISSUE TITLE
Volume slider not visible on Edge and Chrome (at least)

### ISSUE THREAD

**Issue by fnfzlznddzn** [AzuraCast/AzuraCast#5537]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#f7d33b3 (2022-06-24 15:36)

### What happened?

The volume slider on the public player is not visible on Edge and Chrome, possibly other browsers as well (didn't test) but appears fine on Firefox.
This problem is present even on the AzuraCast public demo page, see https://demo.azuracast.com/public/azuratest_radio

On Edge:
![unknown 1](https://user-images.githubusercontent.com/45518224/175768936-6b1aef52-6ccc-4e4f-8ad9-b4cc0f202c28.png)
On Firefox:
![unknown 1](https://user-images.githubusercontent.com/45518224/175768953-ea422a61-4731-4174-9a04-7a7d4e7776ab.png)

I was unable to find a way to modify the volume slider's appearance despite many tries through the Inspect Element dev tool.

Thanks in advance for looking into it :)

**Comment by SlvrEagle23** [comment]
This may be a browser-level stylesheet limitation, and there may not be much we can do about it unfortunately.

**Comment by fnfzlznddzn** [comment]
> This may be a browser-level stylesheet limitation, and there may not be much we can do about it unfortunately.

Oh, that's sad to hear :'( I hope you find a way somehow. It's not breaking anything thankfully, since the slider still works, but it looks a bit weird, especially on a black background like this:
![unknown 1](https://user-images.githubusercontent.com/45518224/175815164-f479a33c-4b08-46f8-bdc6-f627cc74f540.png)

**Comment by ItsMitchh** [comment]
I'll have a look at the slider tonight, just need to go file digging.
