### ISSUE TITLE
AzuraCast editado para cuota de usuarios

### ISSUE THREAD

**Issue by hoting593** [AzuraCast/AzuraCast#554]
- **Installation Method:** Traditional
- **Host OS (if using Docker):** Ubuntu 16.04

he logrado incorporar cuotas de disco para cada usuario, y varios cosas mas al panel y ademas ponerle ssl  con letsencript

lista para ponerla a trabajar en produccion

mail: ortiz.a.carlos@gmail.com

captura: http://omegatv.ml/cap.png

**Comment by SlvrEagle23** [comment]
@hoting593 I sent you an e-mail with questions, but never heard back. If you're interested in contributing code to AzuraCast, I would absolutely welcome any contributions via GitHub's Pull Requests system.
