### ISSUE TITLE
Wrong Stream URL Displayed in Streams Card

### ISSUE THREAD

**Issue by HuckinB** [AzuraCast/AzuraCast#5541]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#c840bb0

### What happened?

In the Streams Card it is displayed that our streams are 
https://radio.simulatorhits.com:8000/****** <- Endpoint

But this does not return anything.

The actual url to the streams are 
https://radio.simulatorhits.com/radio/8000/****** <- Endpoint

Due to the original url not returning, upon pressing the play button. There is no audio (Assuming because it's going to the wrong place)

**Comment by HuckinB** [comment]
![Ehel3Y0](https://user-images.githubusercontent.com/41655029/175815868-ea6a3bd3-c5e3-41cc-b3b5-e5e1dc99d03d.png)

**Comment by SlvrEagle23** [comment]
@HuckinB Whether that URL shows the port or not is based on the system-wide "Use Web Proxy" setting, which, if enabled, will show the `/listen/station_name` (previously the `/radio/8xxx`) URLs.
