### ISSUE TITLE
Enabled LetsEncrypt Not working now

### ISSUE THREAD

**Issue by nobertamooti** [AzuraCast/AzuraCast#5547]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

i encrypted ssl certificate and pointed it to my domain radio.urdt.net using DNS, the station worked perfectly with the certificate but now it has stopped. its now using the default mp3 link
when i tried to re encrypt again then i got this massage #LetsEncrypt is now managed from within the web interface.#
kindly help on this issue

### Relevant log output

```shell
LetsEncrypt is now managed from within the web interface.
```

**Comment by gilfuser** [comment]
Hello there!
What if the message was`LetsEncrypt is now managed from within the web interface under System Settings/Services`?
I think people (like me) would spare some precious time searching for it.

all the best,
Gil

**Comment by ItsMitchh** [comment]
Good suggestion, I'll get that added.
