### ISSUE TITLE
Question - how to relay station and have dj connect as well

### ISSUE THREAD

**Issue by edzel** [AzuraCast/AzuraCast#555]
Hi 
I want to have a station ralaying music and when a dj connects i want the dj to interupt the relayed station 
is that possible?

Thanks
Johan

**Comment by SlvrEagle23** [comment]
@edzel This is now possible by creating a playlist whose source is a remote URL. This will cause Liquidsoap to relay a remote audio stream, which DJs will automatically connect on top of, and which will resume when the DJ disconnects.

**Comment by edzel** [comment]
@SlvrEagle23 Thank You so much!!!
