### ISSUE TITLE
Request Minimum Delay at 0 doesn't allow songs to be requested after 15 seconds. 

### ISSUE THREAD

**Issue by Klinshy** [AzuraCast/AzuraCast#5550]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### What happened?

I keep on receiving this error, thus the cooldown time is set to 0 (=15seconds) even after that time I cant call requests. Lowering the Threshold of last played songs to 0 solved this issue. I think this isnt the way those features should work.

**Comment by ItsMitchh** [comment]
Confirming, reproduction methods - Change your station's settings to Request Minimum Delay = 0 

Request a song, wait 16 seconds, request a song, see error
