### ISSUE TITLE
Streamer Name isn't being listed on NowPlaying API. 

### ISSUE THREAD

**Issue by ItsMitchh** [AzuraCast/AzuraCast#5553]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

https://github.com/AzuraCast/AzuraCast/commit/520f9745a14c6a7e07dfa7851f14d26529ac9aeb

### What happened?

Reported in our Discord by a user who was having issues with our API. 

When a streamer connects to a station it's listed under the `live` portion of the `nowplaying` API, but it's not listed under the `now_playing` endpoint. See the image below. 

![image](https://user-images.githubusercontent.com/29955942/176762258-647c2aec-a210-4b19-a1c9-05fb78854775.png)

**Comment by dumber-Chatteurs** [comment]
Problems with The current song info too when streamer is online
