### ISSUE TITLE
Listening time is not updated in HLS streams

### ISSUE THREAD

**Issue by YosefAdPro** [AzuraCast/AzuraCast#5555]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #6529a92 (2022-06-29 3:25) • Docker • PHP 8.1

### What happened?

I noticed that listening time is not updated in HLS streams.
in reports >listeners.

![image](https://user-images.githubusercontent.com/11810187/176777731-e653b9b6-5120-44b4-9dde-cbef115af4af.png)

**Comment by MarkWasley** [comment]
I can replicate this. For current listeners, it appears to only show the time for twice the chunk length, as per the below code. In listener history, time listened duration is aggregated correctly.

https://github.com/AzuraCast/AzuraCast/blob/5e31ddce639eed6cd97058d7ff21ab3e8167c955/src/Nginx/HlsListeners.php#L36
