### ISSUE TITLE
All Stations Offline because over 76800 files in one radio db

### ISSUE THREAD

**Issue by Schrebergarten03-links** [AzuraCast/AzuraCast#5558]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #0fb1709 (2022-06-30 19:30)

### What happened?

Hi 

I added a very large folder with music and after the media counter reached 76800 all stations gone offline .

had errors in logs like:

allowed memory size of 134217728 bytes exhausted
Error while sending data: could not write data to host: Broken pipe in write()!
AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to 127.0.0.1 port 8301: Connection refused

But the real reason was that the mariaDB db hit some kind of "OVER 9000" limit in from of 3x 256 aka over 76800 files in the media folders.

after i changed the media folder to a smaller one and did a rescan of one playlist the media file counter got reset and i was able to bring all stations back online.

Dunno much about mariadb but there must be a hard limit ^^

greetings 

### Relevant log output

```shell
allowed memory size of 134217728 bytes exhausted
Error while sending data: could not write data to host: Broken pipe in write()!
AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to 127.0.0.1 port 8301: Connection refused
```

**Comment by ItsMitchh** [comment]
Can you try allocating more memory? 

It's in your `azuracast.env` under .`# PHP_MEMORY_LIMIT=128M`, try bumping up to 250 or something and it should give it the memory it needs.

**Comment by Schrebergarten03-links** [comment]
Yes i did that up to 512M but even after restart docker and station restart stations were still frozen ...

**Comment by Schrebergarten03-links** [comment]
also in debugger under 

Message Queues i had "media 6338643+ queued messages"

**Comment by ItsMitchh** [comment]
I'm not entirely sure the best solution here, the queued messages will eventually go down but it's the case of the system itself trying to catch up with demand. I'd propose bumping up the memory a bit higher to see if this improves things. 

Having that much media while is fine, but I can look into this on my local machine to see if there's some things we can do to improve this.

**Comment by Schrebergarten03-links** [comment]
Looks like this is the reason :

https://mariadb.com/kb/en/innodb-limitations/

Page Sizes

Using the innodb_page_size system variable, you can configure the size in bytes for InnoDB pages. Pages default to 16KB. There are certain limitations on how you use this variable.

MariaDB instances using one page size cannot use data files or log files from an instance using a different page size.
When using a Page Size of 4KB or 8KB, the maximum index key length is lowered proportionately. 

InnoDB Page Size	Index Key Length
**Reason ? >>>>>>4KB	768B**
8KB	1536B
16KB	3072B

So i dunno much about mariadb and database stuff ...

How to change the page size without breaking everthing ^^ 
Is this configured in azuracast docker or o the mariadb server of the host ?

greetings
