### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#556]
> 502 Bad Gateway
> nginx
docker-compose kill -s SIGHUP nginx - does not help start the station.
How can I still start the station? 
The error appears spontaneously after several days of operation of the station.

**Comment by SlvrEagle23** [comment]
@susl16c Try running `docker-compose logs -f web` and seeing if there's any error there.

Sometimes, the 502 Bad Gateway error can happen for reasons we don't fully understand, and the easiest solution is to restart the station overall, using `docker-compose down` and `docker-compose up -f`. You may need to try that if the logs don't provide any additional information.

**Comment by susl16c** [comment]
> Attaching to azuracast_web_1
web_1          | 2018/04/20 05:47:18 Waiting for: tcp://mariadb:3306
web_1          | 2018/04/20 05:47:18 Waiting for: tcp://influxdb:8086
web_1          | 2018/04/20 05:47:18 Connected to tcp://mariadb:3306
web_1          | 2018/04/20 05:47:18 Connected to tcp://influxdb:8086
web_1          | [20-Apr-2018 05:47:23] NOTICE: fpm is running, pid 17
web_1          | [20-Apr-2018 05:47:23] NOTICE: ready to handle connections
web_1          | [20-Apr-2018 05:47:23] NOTICE: systemd monitor interval set to 10000ms
web_1          | [20-Apr-2018 06:03:10] WARNING: [pool www] child 45 said into stderr: "[2018-04-20 06:03:10] AzuraCast.ERROR: Too few arguments to function Entity\Song::api(), 0 passed in /var/azuracast/www/app/src/AzuraCast/Sync/NowPlaying.php on line 168 and exactly 1 expected {"file":"/var/azuracast/www/app/src/Entity/Song.php","line":174,"code":0} []"
web_1          | [20-Apr-2018 06:03:49] WARNING: [pool www] child 50 said into stderr: "[2018-04-20 06:03:49] AzuraCast.ERROR: Too few arguments to function Entity\Song::api(), 0 passed in /var/azuracast/www/app/src/AzuraCast/Sync/NowPlaying.php on line 168 and exactly 1 expected {"file":"/var/azuracast/www/app/src/Entity/Song.php","line":174,"code":0} []"
web_1          | [20-Apr-2018 06:04:06] WARNING: [pool www] child 50 said into stderr: "[2018-04-20 06:04:06] AzuraCast.ERROR: Too few arguments to function Entity\Song::api(), 0 passed in /var/azuracast/www/app/src/AzuraCast/Sync/NowPlaying.php on line 168 and exactly 1 expected {"file":"/var/azuracast/www/app/src/Entity/Song.php","line":174,"code":0} []"
web_1          | [20-Apr-2018 06:14:06] NOTICE: [pool www] child 45 exited with code 0 after 964.721150 seconds from start
web_1          | [20-Apr-2018 06:14:06] NOTICE: [pool www] child 70 started

**Comment by SlvrEagle23** [comment]
@susl16c Ah, the errors you're seeing there are a bug on my part as a result of a recent update.

The latest commit should fix that.

**Comment by Xara** [comment]
Regression, same bug observed on latest upgrade

**Comment by amirkhattak** [comment]
i am facing nginx bad gateway 502 how to fix it
