### ISSUE TITLE
Metadata not being returned on API

### ISSUE THREAD

**Issue by HuckinB** [AzuraCast/AzuraCast#5564]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#311f07a

### What happened?

Meta is being sent by streamer, this is proven by the Shoutcast Admin Panel
![J0JzE4Z](https://user-images.githubusercontent.com/41655029/177038999-4559782f-b68e-4400-a1b8-a7281b3dc923.png)

If I go into the Debugger and manually run the Task, under "Final NowPlaying Response for Station", the meta is there
![3HVwhYb](https://user-images.githubusercontent.com/41655029/177038991-77e7eba2-2446-4bf6-aff1-b6b5c7973d3b.png)

But as you can see, upon checking the API it says "Live Broadcast"
![eyPUF35](https://user-images.githubusercontent.com/41655029/177039038-fd4d4199-d16f-4837-8400-fd1a78992506.png)

This is also seen on the Dashboard of Azuracast
![e9Las1G](https://user-images.githubusercontent.com/41655029/177039050-3c2dd83e-3df6-4d82-bf37-8a74e1d061e8.png)

**Comment by Vaalyn** [comment]
This issue should have been fixed with commit 1e8b45803a7eff1c8a7f156cbba7ec9191ca98a2 which was released 3 days after the commit that you are using (311f07a)

**Comment by HuckinB** [comment]
Convenient... I have a cron setup to update every week at 00:00 so it should be fixed now.
:)

If it continues I'll re-open the issue
