### ISSUE TITLE
Translation into other languages

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#557]
I noticed that you began to make translations by collecting phrases from several words, but you do not take into account that in other languages there are declensions that sound differently for different combinations of words.
Before, let the words repeat themselves, but they could be translated in different cases in an optimal way, now I can not do this and swap words.
Therefore, when translating, you now save time on repetitions, but my language turns out to be complete nonsense and I have nothing to do with it.

**Comment by susl16c** [comment]
Yes, but I can not figure it out in that system, for me it's heavy. I can update my language here, but you do not accept it. Therefore, I have no choice whatsoever how to do the translation separately.

**Comment by SlvrEagle23** [comment]
@susl16c Please give it an effort. CrowdIn is an important part of our internationalization efforts, as it provides an important review and approval tool. I've used it and not only is it easy to use, but it allows multiple people to suggest translations and corrections.

**Comment by lamasbr** [comment]
Hello, @SlvrEagle23.
I would like to help translating AzuraCast into Brazilian Portuguese.
I signed up in CrowdIn but I can't find my language available to begin the translation. How can I do it?

**Comment by SlvrEagle23** [comment]
@lamasbr I apologize; I actually got your message a while back, but I've been dealing with personal issues and haven't had a chance to catch up on AzuraCast things for a while.

I will add Brazilian Portuguese as a supported language and prepopulate it with the contents of the Portuguese translation; hopefully this helps.

**Comment by SlvrEagle23** [comment]
@lamasbr My mistake...it appears we don't have a Portuguese translation of any sort yet! I'll start a new one.

**Comment by lamasbr** [comment]
It's all right. I'm waiting so I can start the translation.
In time, thanks for AzuraCast, I have used it with some stations and everything works just fine!

**Comment by SlvrEagle23** [comment]
@lamasbr Thank you, and thank you for volunteering to help with translations! I have added Portuguese and Brazilian Portuguese as target languages for AzuraCast in CrowdIn. Let me know when there are translations to review and I will get them included in the software itself.

**Comment by lamasbr** [comment]
Hi @SlvrEagle23! I've done with Brazilian Portuguese translation.

**Comment by SlvrEagle23** [comment]
@lamasbr Approved, built and added to the repo. Thank you for your contributions!
