### ISSUE TITLE
update to v0.17.2, remote relay menu is missing

### ISSUE THREAD

**Issue by gunsar** [AzuraCast/AzuraCast#5571]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.2

### What happened?

update from v0.17.1 to v0.17.2, remote relay menu is missing
[https://i.imgur.com/1m4pgqk.jpg](url)

**Comment by gunsar** [comment]
![Screenshot 2022-07-06 035855](https://user-images.githubusercontent.com/56213562/177418751-4b684b3e-5fe2-4d8d-934f-714222189780.jpg)

**Comment by SlvrEagle23** [comment]
@gunsar Is your station using the Liquidsoap AutoDJ? I believe our latest updates added that as a requirement for manipulating the Remote Relays.

**Comment by gunsar** [comment]
@SlvrEagle23 Previously the station was only set to "Only connect to a remote server", then I was curious to change the settings to autodj, but the "Remote Relays" menu didn't appear, restarted VPS and Broadcasting several times but nothing changed, I've also tried to create a new station , but still the "Remote Relays" menu is missing. good idea if you have a trick to manipulate this, if there is another trick, can you tell me.

> @gunsar Is your station using the Liquidsoap AutoDJ? I believe our latest updates added that as a requirement for manipulating the Remote Relays.

**Comment by MarkWasley** [comment]
@gunsar The only other reason the link won't appear in the menu is if you haven't got the Remote Relays permission enabled for your user account. So check your permissions, in case you have changed something.

**Comment by gunsar** [comment]
@MarkWasley the account I use is a super administrator account and only one account on my Azuracast VPS. I create a new station also does not appear. on other VPS for a fresh install is not a problem. the problem with the "Remote relay" menu is the upgrade from the previous version to the new version according to the title of this trid

> @gunsar The only other reason the link won't appear in the menu is if you haven't got the Remote Relays permission enabled for your user account. So check your permissions, in case you have changed something.
