### ISSUE TITLE
disconnection in live streaming

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#5577]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #17b4b6f (2022-07-06 2:08)

### What happened?

When I'm broadcasting live through Butt Broadcaster, after a few minutes I've noticed disconnections from azura in my broadcast. This happens around 20 to 40 minutes of live streaming.

I'm testing via shoutcast, so I decided to save the log of the exact moment when the last live disconnection happened.

### Relevant log output

```shell
2022/07/07 12:47:22 [output.file_0:3] Source failed (no more tracks) stopping output...
2022/07/07 12:47:22 [lang:3] Recording stopped: Switching from /var/azuracast/stations/q_bradeira_black/temp/pcosrj/stream_20220707-093904.mp3.tmp to /var/azuracast/stations/q_bradeira_black/temp/pcosrj/stream_20220707-093904.mp3
2022/07/07 12:47:22 [live_fallback:3] Switch to cross_0 with forgetful transition.
2022/07/07 12:47:22 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/108/liquidsoap/feedback' with body: {
2022/07/07 12:47:22 [lang:3]   "song_id": "0ca024728deb885b1aa3b72466c991bb",
2022/07/07 12:47:22 [lang:3]   "playlist_id": "3786",
2022/07/07 12:47:22 [lang:3]   "media_id": "422381"
2022/07/07 12:47:22 [lang:3] }
2022/07/07 12:47:22 [lang:3] API feedback - Response (200): true
2022/07/07 12:47:25 [decoder:2] Decoding "/var/azuracast/stations/q_bradeira_black/media/Vinhetas Novas PCORJ/VTH003.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/07/07 12:47:26 [next_song:3] Prepared "/var/azuracast/stations/q_bradeira_black/media/Big Lista/mantronix_-_got_to_have_your_love.mp3" (RID 24).
[mp3float @ 0x7ff0ac1c5ec0] Could not update timestamps for skipped samples.
2022/07/07 12:47:26 [cue_next_song:3] Cueing in...
2022/07/07 12:47:26 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/108/liquidsoap/nextsong' with body: 
2022/07/07 12:47:26 [cross_0:3] Analysis: -16.491728dB / -16.235179dB (2.96s / 2.96s)
2022/07/07 12:47:26 [cross.smart:3] No transition: using default.
2022/07/07 12:47:26 [lang:3] API nextsong - Response (200): annotate:title="Thought We Had It All",artist="Cool Million",duration="305.00",song_id="a11f8a487c8dd6b52ca393955d795692",media_id="419020",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="2.00",playlist_id="3773":media:Big Lista/Cool_Million_-_Thought_We_Had_It_All.mp3
2022/07/07 12:47:29 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/108/liquidsoap/feedback' with body: {
2022/07/07 12:47:29 [lang:3]   "song_id": "18895df4e61869e142052935b214df9d",
2022/07/07 12:47:29 [lang:3]   "playlist_id": "3773",
2022/07/07 12:47:29 [lang:3]   "media_id": "420011"
2022/07/07 12:47:29 [lang:3] }
2022/07/07 12:47:29 [lang:3] API feedback - Response (200): true
2022/07/07 12:47:33 [input_streamer:3] Timeout reached!
2022/07/07 12:47:33 [input_streamer:2] Error while reading from client: Timed out after waiting for 30.00 sec.
2022/07/07 12:47:33 [lang:3] API djoff - Sending POST request to 'http://127.0.0.1:6010/api/internal/108/liquidsoap/djoff' with body: { "user": "pcosrj" }
2022/07/07 12:47:33 [lang:3] API djoff - Response (200): true
2022/07/07 12:47:33 [input_streamer:2] Feeding stopped: Failure("relaying stopped").
2022/07/07 12:47:33 [lang:3] API djoff - Sending POST request to 'http://127.0.0.1:6010/api/internal/108/liquidsoap/djoff' with body: { "user": "" }
2022/07/07 12:47:33 [lang:3] API djoff - Response (200): true
2022/07/07 12:47:38 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/108/liquidsoap/auth' with body: { "password": "Nga4hyq9*", "user": "pcosrj" }
2022/07/07 12:47:38 [lang:3] API auth - Response (200): true
2022/07/07 12:47:38 [lang:3] DJ Source connected! Last authenticated DJ: pcosrj - [("Host", "s10.w3bserver.com:8135"), ("icy-name", "Q-Bradeira Black"), ("icy-genre", "Hip-Hop"), ("icy-url", "http://q-bradeirablack.com"), ("icy-pub", "0"), ("icy-br", "96"), ("content-type", "audio/mpeg")]
2022/07/07 12:47:38 [lang:3] API djon - Sending POST request to 'http://127.0.0.1:6010/api/internal/108/liquidsoap/djon' with body: { "user": "pcosrj" }
2022/07/07 12:47:38 [lang:3] API djon - Response (200): true
2022/07/07 12:47:38 [input_streamer:3] Decoding...
2022/07/07 12:47:39 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/108/liquidsoap/auth' with body: { "password": "Nga4hyq9*", "user": "pcosrj" }
2022/07/07 12:47:39 [lang:3] API auth - Response (200): true
2022/07/07 12:47:39 [input_streamer:3] New metadata chunk ? -- Q--Bradeira Black ! A Melhor Web Radio do Brasil !.
2022/07/07 12:47:57 [next_song:3] Prepared "/var/azuracast/stations/q_bradeira_black/media/Big Lista/Cool_Million_-_Thought_We_Had_It_All.mp3" (RID 25).
[mp3float @ 0x7ff0ac1e9800] Could not update timestamps for skipped samples.
2022/07/07 12:47:58 [cue_next_song:3] Cueing in...
2022/07/07 12:47:58 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/108/liquidsoap/nextsong' with body: 
2022/07/07 12:47:58 [lang:3] API nextsong - Response (200): annotate:title="This Feeling",artist="4KaST",duration="243.00",song_id="a771f4ecb0b23b0d93b4c32314689107",media_id="418460",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="2.00",playlist_id="3773":media:Big Lista/4KaST_-_This_Feeling.mp3
2022/07/07 12:47:58 [cross_0:3] Analysis: -10.304299dB / -8.323854dB (2.96s / 2.96s)
```

**Comment by Vaalyn** [comment]
Looks like your client (the broadcasting software) stopped sending Data for at least 30s which then prompted LS to timeout the connection and disconnect it.

```
2022/07/07 12:47:33 [input_streamer:3] Timeout reached!
2022/07/07 12:47:33 [input_streamer:2] Error while reading from client: Timed out after waiting for 30.00 sec.
```

**Comment by Marcioghiraldelli** [comment]
so this would be a local problem? Something in the software or internet?

**Comment by Vaalyn** [comment]
Most likely yes. If LS doesn't get data from the client for such a long time it's to be expected that the streamer will be disconnected. As for why no data was received, that's not something we can really investigate since this is mostly down to the PC, internet provider, server's internet connectivity, temporary routing issues, etc.

**Comment by maaakmal** [comment]
What happened?

I have been getting the same issue
WEB DJ fails/ disconnects

Local Windows 10 installed on Docker 

![image](https://user-images.githubusercontent.com/69513786/177924342-0d3231e3-0518-4878-837c-be61d4380106.png)

Installation Method
Docker Installation

AzuraCast Release Channel
Rolling Release Channel

Current AzuraCast Version
Rolling Release #17b4b6f (2022-07-06 2:08)



Liquid Soap:
2022/07/08 07:27:25 [lang:3]   "song_id": "22e89b5a57f95ffedfc9cf687663ecee",
2022/07/08 07:27:25 [lang:3]   "playlist_id": "6",
2022/07/08 07:27:25 [lang:3]   "media_id": "32"
2022/07/08 07:27:25 [lang:3] }
2022/07/08 07:27:25 [lang:3] API nextsong - Response (200): annotate:title="Pruned",artist="John Roberts",duration="390.00",song_id="4c579a12a6aa53905d4760131cd08330",media_id="40",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="2.00",playlist_id="6":media:john_roberts_-_pruned.mp3
2022/07/08 07:27:25 [lang:3] API feedback - Response (200): true
2022/07/08 07:33:37 [decoder:2] Decoding "/var/azuracast/stations/radiomal/media/john_roberts_-_august.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/07/08 07:33:38 [next_song:3] Prepared "/var/azuracast/stations/radiomal/media/john_roberts_-_pruned.mp3" (RID 8).
[mp3float @ 0x7f45f018f040] Could not update timestamps for skipped samples.
2022/07/08 07:33:38 [cue_next_song:3] Cueing in...
2022/07/08 07:33:38 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/nextsong' with body: 
2022/07/08 07:33:38 [cross_0:3] Analysis: -71.655923dB / -27.247088dB (2.96s / 2.96s)
2022/07/08 07:33:38 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/feedback' with body: {
2022/07/08 07:33:38 [lang:3]   "song_id": "4c579a12a6aa53905d4760131cd08330",
2022/07/08 07:33:38 [lang:3]   "playlist_id": "6",
2022/07/08 07:33:38 [lang:3]   "media_id": "40"
2022/07/08 07:33:38 [lang:3] }
2022/07/08 07:33:38 [lang:3] API nextsong - Response (200): annotate:title="Glass Eights",artist="John Roberts",duration="285.00",song_id="cbfab661b2d8e612f1422e256b3df329",media_id="35",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="2.00",playlist_id="6":media:john_roberts_-_glass_eights.mp3
2022/07/08 07:33:38 [lang:3] API feedback - Response (200): true
2022/07/08 07:38:09 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/auth' with body: { "password": "M00n", "user": "maaak" }
2022/07/08 07:38:09 [lang:3] API auth - Response (200): false
2022/07/08 07:38:33 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/auth' with body: { "password": "M00n", "user": "maaak" }
2022/07/08 07:38:34 [lang:3] API auth - Response (200): false
2022/07/08 07:38:35 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/auth' with body: { "password": "M00n", "user": "maaak" }
2022/07/08 07:38:36 [lang:3] API auth - Response (200): false
2022/07/08 07:38:41 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/auth' with body: { "password": "M00n", "user": "maaak" }
2022/07/08 07:38:42 [lang:3] API auth - Response (200): false
2022/07/08 07:40:05 [decoder:2] Decoding "/var/azuracast/stations/radiomal/media/john_roberts_-_pruned.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/07/08 07:40:06 [next_song:3] Prepared "/var/azuracast/stations/radiomal/media/john_roberts_-_glass_eights.mp3" (RID 9).
[mp3float @ 0x7f45f03b9b40] Could not update timestamps for skipped samples.
2022/07/08 07:40:06 [cue_next_song:3] Cueing in...
2022/07/08 07:40:06 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/nextsong' with body: 
2022/07/08 07:40:06 [cross_0:3] Analysis: -89.646038dB / -26.082034dB (2.96s / 2.96s)
2022/07/08 07:40:06 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/feedback' with body: {
2022/07/08 07:40:06 [lang:3]   "song_id": "cbfab661b2d8e612f1422e256b3df329",
2022/07/08 07:40:06 [lang:3]   "playlist_id": "6",
2022/07/08 07:40:06 [lang:3]   "media_id": "35"
2022/07/08 07:40:06 [lang:3] }
2022/07/08 07:40:06 [lang:3] API nextsong - Response (200): annotate:title="Ever or Not",artist="John Roberts",duration="386.00",song_id="ede3927709a6f5eaafc5dd157a4b3bd3",media_id="34",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="2.00",playlist_id="6":media:john_roberts_-_ever_or_not.mp3
2022/07/08 07:40:06 [lang:3] API feedback - Response (200): true

Ice Cast

2022/07/08 07:27:25 [lang:3]   "song_id": "22e89b5a57f95ffedfc9cf687663ecee",
2022/07/08 07:27:25 [lang:3]   "playlist_id": "6",
2022/07/08 07:27:25 [lang:3]   "media_id": "32"
2022/07/08 07:27:25 [lang:3] }
2022/07/08 07:27:25 [lang:3] API nextsong - Response (200): annotate:title="Pruned",artist="John Roberts",duration="390.00",song_id="4c579a12a6aa53905d4760131cd08330",media_id="40",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="2.00",playlist_id="6":media:john_roberts_-_pruned.mp3
2022/07/08 07:27:25 [lang:3] API feedback - Response (200): true
2022/07/08 07:33:37 [decoder:2] Decoding "/var/azuracast/stations/radiomal/media/john_roberts_-_august.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/07/08 07:33:38 [next_song:3] Prepared "/var/azuracast/stations/radiomal/media/john_roberts_-_pruned.mp3" (RID 8).
[mp3float @ 0x7f45f018f040] Could not update timestamps for skipped samples.
2022/07/08 07:33:38 [cue_next_song:3] Cueing in...
2022/07/08 07:33:38 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/nextsong' with body: 
2022/07/08 07:33:38 [cross_0:3] Analysis: -71.655923dB / -27.247088dB (2.96s / 2.96s)
2022/07/08 07:33:38 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/feedback' with body: {
2022/07/08 07:33:38 [lang:3]   "song_id": "4c579a12a6aa53905d4760131cd08330",
2022/07/08 07:33:38 [lang:3]   "playlist_id": "6",
2022/07/08 07:33:38 [lang:3]   "media_id": "40"
2022/07/08 07:33:38 [lang:3] }
2022/07/08 07:33:38 [lang:3] API nextsong - Response (200): annotate:title="Glass Eights",artist="John Roberts",duration="285.00",song_id="cbfab661b2d8e612f1422e256b3df329",media_id="35",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="2.00",playlist_id="6":media:john_roberts_-_glass_eights.mp3
2022/07/08 07:33:38 [lang:3] API feedback - Response (200): true
2022/07/08 07:38:09 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/auth' with body: { "password": "M00n", "user": "maaak" }
2022/07/08 07:38:09 [lang:3] API auth - Response (200): false
2022/07/08 07:38:33 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/auth' with body: { "password": "M00n", "user": "maaak" }
2022/07/08 07:38:34 [lang:3] API auth - Response (200): false
2022/07/08 07:38:35 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/auth' with body: { "password": "M00n", "user": "maaak" }
2022/07/08 07:38:36 [lang:3] API auth - Response (200): false
2022/07/08 07:38:41 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/auth' with body: { "password": "M00n", "user": "maaak" }
2022/07/08 07:38:42 [lang:3] API auth - Response (200): false
2022/07/08 07:40:05 [decoder:2] Decoding "/var/azuracast/stations/radiomal/media/john_roberts_-_pruned.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/07/08 07:40:06 [next_song:3] Prepared "/var/azuracast/stations/radiomal/media/john_roberts_-_glass_eights.mp3" (RID 9).
[mp3float @ 0x7f45f03b9b40] Could not update timestamps for skipped samples.
2022/07/08 07:40:06 [cue_next_song:3] Cueing in...
2022/07/08 07:40:06 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/nextsong' with body: 
2022/07/08 07:40:06 [cross_0:3] Analysis: -89.646038dB / -26.082034dB (2.96s / 2.96s)
2022/07/08 07:40:06 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/feedback' with body: {
2022/07/08 07:40:06 [lang:3]   "song_id": "cbfab661b2d8e612f1422e256b3df329",
2022/07/08 07:40:06 [lang:3]   "playlist_id": "6",
2022/07/08 07:40:06 [lang:3]   "media_id": "35"
2022/07/08 07:40:06 [lang:3] }
2022/07/08 07:40:06 [lang:3] API nextsong - Response (200): annotate:title="Ever or Not",artist="John Roberts",duration="386.00",song_id="ede3927709a6f5eaafc5dd157a4b3bd3",media_id="34",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="2.00",playlist_id="6":media:john_roberts_-_ever_or_not.mp3
2022/07/08 07:40:06 [lang:3] API feedback - Response (200): true

**Comment by maaakmal** [comment]
Thanks so much for the fantastic info and feedback.
