### ISSUE TITLE
100% CPU Utilization on random station logs

### ISSUE THREAD

**Issue by renatopinto89** [AzuraCast/AzuraCast#5578]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.2

### What happened?

Hello

I've been noticing some random sustained logs for some stations keeping CPU at 100%
Nothing abnormal shows up on any logs, though.
Restarting the container usually fixes this issue but it happens again after some time.
Any idea what can be the cause of this and how to fix it?
Thank you.
![IMG_20220708_085127](https://user-images.githubusercontent.com/83221826/177948876-2ced1ea7-0d3b-4342-9ca5-715d56b054ad.jpg)

**Comment by ItsMitchh** [comment]
Duplicate, aware and working on it
