### ISSUE TITLE
High Consumption Radio

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#5584]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.2

### What happened?

There is a radio that consumption is very high, on htop it shows "tail -q -n +0 --retry -F /var/azuracast/stations/radio_name".

**Comment by ItsMitchh** [comment]
https://github.com/AzuraCast/AzuraCast/issues
