### ISSUE TITLE
Automatic Backup Disable

### ISSUE THREAD

**Issue by Blat4** [AzuraCast/AzuraCast#5585]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

64e2a48

### What happened?

Hi I don't know if this is a bug or just me not doing something the correct way. 

Every time I try to untick the Automatic Backups, it just stays enabled.
![Screenshot 2022-07-10 at 07 21 51](https://user-images.githubusercontent.com/106454822/178133833-4c997982-6a40-4a4e-91b2-71068710f5ac.png)

Screenshot of it unticked.
![Screenshot 2022-07-10 at 07 22 38](https://user-images.githubusercontent.com/106454822/178133858-0a3419f2-87dc-40b7-98f8-b757ab217691.png)

I press enter or the cross on the right side and it just stays enabled?

**Comment by SlvrEagle23** [comment]
@Blat4 I'm having trouble reproducing this issue on my installation. When you try to disable the automatic backups, do you see any sort of error message pop up? You may want to hit F12 (or right click the page and click "Inspect Element"), then look at either the Console tab for any errors or the Network tab to see if the most recent request was successful. If either show any sort of error message, feel free to paste that here so we can investigate it.
