### ISSUE TITLE
High CPU Drain after update to last stable version

### ISSUE THREAD

**Issue by Sakretsos** [AzuraCast/AzuraCast#5587]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.2 Stable

### What happened?

Hello, after updating to last stable release on my main server and after i did some test a radio server stucks.
Bellow you can find the htop of the 99% cpu drain.
![high_cpu_drain](https://user-images.githubusercontent.com/8127121/178149752-c910f918-9151-4620-abcf-ad1056164f77.JPG)

**Comment by ItsMitchh** [comment]
Please read our issues before making new ones, we are aware of this and are working on it.
