### ISSUE TITLE
Add custom general API 

### ISSUE THREAD

**Issue by Protomothis** [AzuraCast/AzuraCast#559]
It is hoped that the user can change the value by adding custom fields to the general API ( station nowplaying ) looks like this.

    "station":
    {
        "id": 1,
        "name": "test",
        "shortcode": "test",
        "description": "test",
        "frontend": "icecast",
        "backend": "liquidsoap",
        "listen_url": "http",
        "is_public": true,
        "mounts": [
        {
            "name": "\/radio.mp3",
            "is_default": true,
            "url": "",
            "bitrate": 0,
            "format": "mp3"
        }],
        "custom_api": {
             "custom_field" : false,
             "custom_field" : "notice : thank you.."
        }
   }

More can be done if allowing the station profile edit to add custom general API fields.

**Comment by SlvrEagle23** [comment]
@unbreakhyek It sounds like what you're looking for is custom field support similar to songs, but for other entities in the system, namely in this case stations, correct?

If so, I'll update the title of the request accordingly.

**Comment by unbreakhyek** [comment]
@SlvrEagle23 That sounds about right. :)

**Comment by SlvrEagle23** [comment]
Closing this issue as our continued work with implementing our API has resulted in a significantly more powerful API that should solve many of the problems that the ability to customize the API response would solve, and customizing the API response outside the existing "custom fields" section would likely lead to undefined behavior and unpredictable APIs that don't match our documentation.
