### ISSUE TITLE
App slim error and update failed again

### ISSUE THREAD

**Issue by Deiiji** [AzuraCast/AzuraCast#5590]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Update is failing and site is in app slim error, streams are working

### Relevant log output

```shell
TASK [azuracast-setup : Run AzuraCast Setup (Update Mode)] ***********************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/console azuracast:setup --update", "delta": "0:00:00.255840", "end": "2022-07-11 06:33:41.424630", "msg": "non-zero return code", "rc": 255, "start": "2022-07-11 06:33:41.168790", "stderr": "[2022-07-11T04:33:41.408508+00:00] AzuraCast.ERROR: Doctrine\\DBAL\\Exception\\ConnectionException: An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 103 while running console command `azuracast:setup` {\"exception\":\"[object] (Doctrine\\\\DBAL\\\\Exception\\\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\\n[previous exception] [object] (Doctrine\\\\DBAL\\\\Driver\\\\PDO\\\\Exception(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)\"} []\n[2022-07-11T04:33:41.409632+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 2002. [] []\n\nIn ExceptionConverter.php line 103:\n                                                                               \n  An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or  \n   directory                                                                   \n                                                                               \n\nIn Exception.php line 30:\n                                                    \n  SQLSTATE[HY000] [2002] No such file or directory  \n                                                    \n\nIn Driver.php line 28:\n                                                    \n  SQLSTATE[HY000] [2002] No such file or directory  \n                                                    \n\nazuracast:setup [--update] [--load-fixtures] [--release]", "stderr_lines": ["[2022-07-11T04:33:41.408508+00:00] AzuraCast.ERROR: Doctrine\\DBAL\\Exception\\ConnectionException: An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 103 while running console command `azuracast:setup` {\"exception\":\"[object] (Doctrine\\\\DBAL\\\\Exception\\\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\\n[previous exception] [object] (Doctrine\\\\DBAL\\\\Driver\\\\PDO\\\\Exception(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)\"} []", "[2022-07-11T04:33:41.409632+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 2002. [] []", "", "In ExceptionConverter.php line 103:", "                                                                               ", "  An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or  ", "   directory                                                                   ", "                                                                               ", "", "In Exception.php line 30:", "                                                    ", "  SQLSTATE[HY000] [2002] No such file or directory  ", "                                                    ", "", "In Driver.php line 28:", "                                                    ", "  SQLSTATE[HY000] [2002] No such file or directory  ", "                                                    ", "", "azuracast:setup [--update] [--load-fixtures] [--release]"], "stdout": "\nAzuraCast Setup\n===============\n\nWelcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...\n\nInitialize AzuraCast\n====================\n\nInitializing essential settings...\n * Environment: Production\n * Installation Method: Ansible\n\n\nRunning Database Migrations\n---------------------------", "stdout_lines": ["", "AzuraCast Setup", "===============", "", "Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...", "", "Initialize AzuraCast", "====================", "", "Initializing essential settings...", " * Environment: Production", " * Installation Method: Ansible", "", "", "Running Database Migrations", "---------------------------"]}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=28   changed=18   unreachable=0    failed=1    skipped=70   rescued=0    ignored=0
```

**Comment by Deiiji** [comment]
Same thing after fresh install on  a blank vps, it work  but station don't start, after server's reboot  web site on slim error app.
Fpr example reprocess command give this: 
Reprocessing media for all stations...
--------------------------------------

[2022-07-11T11:19:51.966931+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\ConnectionException: An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 103 while running console command `azuracast:media:reprocess` {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2022-07-11T11:19:51.967570+00:00] AzuraCast.WARNING: Console command `azuracast:media:reprocess` exited with error code 2002. [] []

In ExceptionConverter.php line 103:

  An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory


In Exception.php line 30:

  SQLSTATE[HY000] [2002] No such file or directory


In Driver.php line 28:

  SQLSTATE[HY000] [2002] No such file or directory


azuracast:media:reprocess [<station-name>]

**Comment by kemecs** [comment]
I'm experiencing the same thing now after a ./docker.sh update

Database Migrations
===================

"[2022-09-22T09:41:50.057648+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\ConnectionException: An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 101 while running console command `azuracast:setup` {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2022-09-22T09:41:50.068724+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 2002. [] []

In ExceptionConverter.php line 101:

  An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory


In Exception.php line 28:

  SQLSTATE[HY000] [2002] No such file or directory


In Driver.php line 28:

  SQLSTATE[HY000] [2002] No such file or directory


azuracast:setup [--update] [--load-fixtures] [--release]

ERROR: 255"
