### ISSUE TITLE
Slim Application Error and 

### ISSUE THREAD

**Issue by anmiefan** [AzuraCast/AzuraCast#5591]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

latest

### What happened?

i got part of it working now its saying this what in the world is a Slim Application @SlvrEagle23 

Slim Application Error
A website error has occurred. Sorry for the temporary inconvenienc

ubuntu 20.04 has some issues with this
i have to kill it everytime i boot the pi up and then start it back up
it dosn't work anymore with 20.04
the site loads up the same
i have to use this command pkill -f nginx & wait $! to kill nginx evertime i boot the pi i have to keep the pi on 24/7 if it turns off then i have to kill nginx again and start it back up

i have to keep on killing it everytime it boots up and starting back up to clear this issue but i need to know what this slim app error is 
i made need to take apart the docker imgae to see how you made it work 
i am not getting the port numbers errors but still i have to kill nginx with this command still pkill -f nginx & wait every time i turn on the pi

### Relevant log output

```shell
nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
Jul 12 20:18:33 sapr-azuracast-radio-server nginx[1541]: nginx: [emerg] bind() to 127.0.0.1:6011 failed (98: Address already in use)
Jul 12 20:18:33 sapr-azuracast-radio-server nginx[1541]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Jul 12 20:18:33 sapr-azuracast-radio-server nginx[1541]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Jul 12 20:18:33 sapr-azuracast-radio-server nginx[1541]: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
Jul 12 20:18:33 sapr-azuracast-radio-server nginx[1541]: nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
Jul 12 20:18:34 sapr-azuracast-radio-server nginx[1541]: nginx: [emerg] still could not bind(
```

**Comment by ItsMitchh** [comment]
The errors logs you provided indicate something is already using those specific ports. 

I ask that you don't ping any of the development team, they're experiencing some emergencies and they will not be providing support. As always with Ansible, expect limited support options, thanks for patience.
