### ISSUE TITLE
Our Lead Developer Buster "Silver Eagle" Neece requires your help

### ISSUE THREAD

**Issue by ItsMitchh** [AzuraCast/AzuraCast#5593]
Hi everyone, you may know me as Mitch, team member on our community Discord server or frequently helping out folks here on GitHub, but this issue isn't about me. 

This topic is about our lead developer and founder, Buster "Silver Eagle" Neece, whom has had some terrible news from his landlord on the 10th of July. I've known and regularly speak with Buster on a day to day basis in our Discord, he's a great guy with a huge heart for AzuraCast and we're asking for your help. 

**What happened?**
On the 10th of July 2022, Buster heard the news from his Landlord he needs to move out within 30 days, due to his Landlord's therapist believing they need to live independently. Despite the fact that Texas (Hell, even the United States) is still dealing with the COVID-19 pandemic and the various variants that continue to run rampant and the sweltering heatwave Texas is currently going under, the Landlord refused at every turn to accommodate or give extra time.  

For folks that have been around long enough, us, AzuraCast is ran by a small team of three members, Buster "Silver Eagle" Neece, Vaalyn and myself. The majority of our community has been nothing but amazing to us, but during these times, we're asking for our communities help to find Buster a new home. 

**Support & Development**
During these emergency times, support and development will be slower, we can only urge patience as we work to help Buster in anyway we can. The faster we can find him a new home, the faster work can resume. 

**How can you help?**
You can help Buster by donating to his GoFundMe - https://www.gofundme.com/f/30-days-to-find-a-new-life-help-needed
If you don't wish to use GoFundMe, you can donate through these methods:
Ko-fi: https://ko-fi.com/silvereagle
Paypal: https://www.paypal.com/paypalme/SlvrEagle23
Cashapp or Venmo: $BusterNeece 
Github Sponsors - AzuraCast: https://github.com/sponsors/AzuraCast | Silver's Sponsors page: https://github.com/sponsors/SlvrEagle23

Thank you. This issue will remain pinned until Buster has a new home.

**Comment by BusterNeece** [comment]
Thank you to everyone who has shown your support to me through this campaign.

Thanks to all the support from my friends, peers and station owners and operators, I was able to find a new place to live, and have settled into the new place over the last month. My overall living costs are quite a bit higher now, but I'm continuing to work through those issues.

**Comment by Fridgemagnet** [comment]
Wishing you the best of luck, @BusterNeece
