### ISSUE TITLE
Processing tags inside an ogg container no longer works

### ISSUE THREAD

**Issue by JRB-Prod** [AzuraCast/AzuraCast#5595]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.2

### What happened?

Hello! Since about version 0.17 of Azuracast, the metadata of OGG Vorbis and Opus files is no longer handled properly. The 'Album' and 'Track Genre' fields remain empty and the 'Artist' field is, in my case, filled in incorrectly. See the screenshot below as an example. I think Pull Request [5392](https://github.com/AzuraCast/AzuraCast/pull/5392) has something to do with it, although Vorbis Comments are case insensitive. This problem should occur with all formats that mainly use Vorbis Comments, but I've only tested it with Vorbis and Opus files. MP3 and AAC files are processed correctly.

Thanks for all you guys great work! And I hope Silver Eagle gets a new home soon!

![image](https://user-images.githubusercontent.com/109231898/178773948-bef30b0d-3994-41db-8782-1b66fb0a4508.png)

**Comment by fnfzlznddzn** [comment]
I have not uploaded any ogg/opus files, so I cannot say anything about them, but I uploaded many FLAC files (which use Vorbis comments) since 0.17.2 version and they are processing fine for me.

**Comment by JRB-Prod** [comment]
I can confirm that FLAC files are indeed processed just fine, which makes this all a bit more confusing. Maybe some people can test this as well to make sure this is an actual bug?

First screenshot: FLAC file.
Second screenshot: an opus version of the same song.

![image](https://user-images.githubusercontent.com/109231898/179218016-e8419f24-91d9-4ad3-84d5-9c2c732da475.png)
![image](https://user-images.githubusercontent.com/109231898/179218069-dff6d004-40ae-4458-9a2f-100650882ba2.png)

**Comment by JRB-Prod** [comment]
Ok, one last update (hopefully). I put one of my FLAC files in an ogg container and guess what? Processing Vorbis Comments doesn't work anymore in the ogg container but it does in a raw FLAC. So it has nothing to do with the Vorbis Comments but with the container.

First screenshot: FLAC file in its original raw container.
Second screenshot: Exact same FLAC stream, but inside an ogg container.

![image](https://user-images.githubusercontent.com/109231898/179355922-b2a6d941-c2ab-49a8-a4ce-85dd94aecabe.png)
![image](https://user-images.githubusercontent.com/109231898/179355942-e0fe3a30-85e9-4aa8-b3bd-b434d1e0baf5.png)

**Comment by fnfzlznddzn** [comment]
can confirm the one track i have on my station in .ogg does not have its metadata displayed correctly (instead, azuracast falls back to guessing from the filename, which is "xxx - artist - title.ogg", resulting in ARTIST= "xxx - artist" and TITLE= "title" )
the metadata is correctly displayed in foobar2000
