### ISSUE TITLE
I am moving to another program

### ISSUE THREAD

**Issue by Deiiji** [AzuraCast/AzuraCast#5596]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Current rolling

### What happened?

What I see is that my stations are down for more as month now, I had promisse that ansible will been supported, associations need they radios edits and is nothing. In past support was great, is no more now, so I am moving away and for sure I won't make you good adverts.

**Comment by ItsMitchh** [comment]
You are using an Ansible system, which has been very much advertised as unsupported and we have explictedly stated you won't get support for it. We made it clearly abdundent our lead developer is having some emergencies so support will be limited. 

Goodbye, good luck finding another project which has this level of dedication.
