### ISSUE TITLE
docker.sh install, and every other docker.sh command, is producing no output

### ISSUE THREAD

**Issue by Seedy-Threepio** [AzuraCast/AzuraCast#5598]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

N/A

### What happened?

So far, I've followed every instruction correctly as per https://docs.azuracast.com/en/getting-started/installation/docker. However, I'm having a problem where running docker.sh install, or any docker.sh command for that matter, results in no output whatsoever being produced. This happens both with and without sudo.
I had this problem before on another VPS and fixed it, however that was ages ago and I've forgotten the steps I took.

### Relevant log output

```shell
N/A
```

**Comment by SlvrEagle23** [comment]
@Seedy-Threepio Does `bash docker.sh install` yield the same result?

**Comment by iDJHost** [comment]
If this issue hasn't been resolved:
Not sure if it helps at all, I had issues with my Docker installation.
I had to manually run:

sudo systemctl enable docker
sudo systemctl start docker

and then run:

./docker.sh install

to finish the complete installation and then it installed and worked perfectly.
Hope this helps.

**Comment by Seedy-Threepio** [comment]
The issue was resolved in the end. Docker-compose didn't install properly for some reason, so I had to reinstall it.
I'm going to leave this issue open so that others with this issue, or a similar one, can submit their comments and others can come up with potential solutions to try. It's better than cluttering this repo with issues that are the same or similar.
