### ISSUE TITLE
SFTP to media directory issue

### ISSUE THREAD

**Issue by Zethrus** [AzuraCast/AzuraCast#561]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Ubuntu 16.04

**Describe the issue in full detail, including screenshots if possible:**
![image](https://user-images.githubusercontent.com/8649594/39148087-aafe445c-46f8-11e8-8ccd-2e894c0d78e6.png)

Can you explain the SFTP command in more detail? I'm not able to get into my radio stations media directory upon running this command. All that I get is the /stations directory as seen in the screenshot. There isn't a station name directory or media directory.

docker run --rm \
    -v azuracast_station_data:/home/azuracast/stations \
    -p 2222:22 atmoz/sftp:alpine \
    azuracast:4zur4c457:::stations

Running that as root and copying exactly as is, is that what I'm supposed to do, if not can you please explain what to do to access my media directory via sftp?

**Comment by Roforum** [comment]
Login with root user or give to your user root access and will work.
I had the same problem and after I gave root access I was able to see the folder.

**Comment by Zethrus** [comment]
I am running it on the root account though... ?
Am I supposed to change something on that command or?

**Comment by SlvrEagle23** [comment]
@Zethrus If you're running the AzuraCast docker containers in a folder that isn't named "azuracast", the volume will be prefixed with whatever the actual name of the parent folder is. You can see all volumes by running `docker volume ls`, then just replace `azuracast_station_data` with whichever one is correct for your setup.

I'll be working to update the installer to help make sure this isn't an issue in the future.

**Comment by Zethrus** [comment]
Still sort of confused on this. Sorry, this is the first time I've played around with Docker so I'm kind of learning, quite a nifty thing though.

Anyway, this is my volume ls: 
![image](https://user-images.githubusercontent.com/8649594/39160523-fdae63c8-4728-11e8-9a12-4cd5c7f1aaea.png)

I changed my command to: 
```
docker run --rm \
    -v root_station_data:/var/azurecast/stations \
    -p 2222:22 atmoz/sftp:alpine \
    azuracast:4zur4c457:::stations
```

Assuming that is correct as my setup states my directory is: 
![image](https://user-images.githubusercontent.com/8649594/39160555-2c97f834-4729-11e8-8b92-559f8211c927.png)
However, still no luck. What am I doing wrong here?

**Comment by SlvrEagle23** [comment]
@Zethrus You're typing `/var/azurecast/stations` not `/var/azuracast/stations`, azurA with an A.

**Comment by Zethrus** [comment]
D'oh. Just noticed that. Hahaha, typo.

**Comment by SlvrEagle23** [comment]
@Zethrus Also, sorry, just noticed in this command's case it's supposed to be `/home/azuracast`, not `/var/azuracast` in the SFTP command.

**Comment by Zethrus** [comment]
Yeah, still no luck getting to the media directory. Am I understanding the command correctly?

**Comment by Zethrus** [comment]
Yup, works now. I didn't think it was installed in /home/azuracast. Sorry, not fully understanding Docker volumes yet.

Issue closed.

**Comment by SlvrEagle23** [comment]
@Zethrus Where it is installed in any given Docker container can actually change from container to container. The "volumes" are just blocks of data that can be mounted anywhere in a container...in the main AzuraCast images' cases, that's `/var/azuracast`, but in the SFTP image it needs to be `/home/azuracast`, but since both use the same volume, they represent the same data.

It's one of those weird Docker paradigm things. Docker's a bit of a learning curve, but it's a whole new world that's kind of exciting once you get the hang of it.
