### ISSUE TITLE
Streaming with Mixxx

### ISSUE THREAD

**Issue by maaakmal** [AzuraCast/AzuraCast#5610]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Wow just gets better and better !
So enjoying learning about Azuracast, thank you again for such an amazing project.
I hope you can assist with my issue:
I am not able to stream from Mixxx (yet)
![image](https://user-images.githubusercontent.com/69513786/180185704-d796e5d1-52f6-482f-824d-c651717eeb91.png)

![image](https://user-images.githubusercontent.com/69513786/180185789-c6337d60-032b-47e9-ad8c-7324490bd1e4.png)
![image](https://user-images.githubusercontent.com/69513786/180185958-7239c6e1-57db-4f8f-bc1b-178456a580b6.png)
![image](https://user-images.githubusercontent.com/69513786/180186030-7464b344-9555-4f94-9dba-a02ad251cf6f.png)
I have tried both domain and URL
Your help hugely appreciated
Mark 

### Relevant log output

```shell
[2022-07-18  13:07:39] WARN slave/slave_startup process has 65536 max file descriptor limit
[2022-07-18  18:45:31] WARN slave/slave_startup process has 65536 max file descriptor limit
[2022-07-19  12:15:31] WARN slave/slave_startup process has 65536 max file descriptor limit
[2022-07-19  13:54:51] WARN slave/slave_startup process has 65536 max file descriptor limit
[2022-07-20  07:11:06] WARN slave/slave_startup process has 65536 max file descriptor limit
[2022-07-20  07:45:40] WARN slave/slave_startup process has 65536 max file descriptor limit
```

**Comment by maaakmal** [comment]
i should of added this earlier

![image](https://user-images.githubusercontent.com/69513786/180189674-db6e8078-2412-47dc-8a4f-ae3b2bd6dcf8.png)

**Comment by LordHelmchen666** [comment]
Are you sure needed ports are open. Check your firewall. Your ports from 8000 up to 8010 seems to be closed.

**Comment by maaakmal** [comment]
Hi
Thank you for the advice, I have followed several pathways , but unfortunately have not resolved,yet.

I opened port 8005 (i think)

I did this
![image](https://user-images.githubusercontent.com/69513786/180595588-8a6d937a-0bd4-410a-8835-9ecbf706b165.png)

Created an ingress rule on my cloud instance (Oracle)
![image](https://user-images.githubusercontent.com/69513786/180595657-e4962acf-0d94-45bb-abe8-6ddf05d6b05f.png)
rebooted instance
restarted Azuracast

Not able to connect with Mixxx using:
![image](https://user-images.githubusercontent.com/69513786/180595727-56fd3dfb-0a3e-4cb8-a5a5-02caa365b3e4.png)

[Icecast Error.txt](https://github.com/AzuraCast/AzuraCast/files/9173373/Icecast.Error.txt)
[icecast log.txt](https://github.com/AzuraCast/AzuraCast/files/9173374/icecast.log.txt)
[Liquid Soap log.txt](https://github.com/AzuraCast/AzuraCast/files/9173375/Liquid.Soap.log.txt)
[Liquid Soapconfig.txt](https://github.com/AzuraCast/AzuraCast/files/9173376/Liquid.Soapconfig.txt)
[Icecast Access.txt](https://github.com/AzuraCast/AzuraCast/files/9173377/Icecast.Access.txt)
[Icecast Config.txt](https://github.com/AzuraCast/AzuraCast/files/9173378/Icecast.Config.txt)

**Comment by LordHelmchen666** [comment]
Your port 8005 is closed. You can test with a portscanner like this one. http://www.ipv6scanner.com/cgi-bin/main.py

**Comment by maaakmal** [comment]
Greets and thankyou LordHelmchen666
Thanks for the tip
Old dog teaching itself new tricks
Let me explore further

**Comment by maaakmal** [comment]
Thanks again sorted
