### ISSUE TITLE
Station Offline after update

### ISSUE THREAD

**Issue by shogd3838** [AzuraCast/AzuraCast#5615]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

latest

### What happened?

During the update I got an error message that says that it can't create the local folder where my station is.

**[ERROR] NAME OF THE STATION: Failed to create "MY LOCAL FOLDER": mkdir(): Permission denied**

I remove from the docker-compose.override.yml the station part and only left the web part.
when I connect to the backend it says the station is offline now.

I try to give read+write to all users -> still the same error.

In the log I add to the issue I see that it search in /var/azuracast/stations but this folder doesn't exists on my computer.

### Relevant log output

```shell
azuracast  | Error: The directory named as part of the path /var/azuracast/stations/STATION NAME/config/liquidsoap.log does not exist in section 'program:station_1_backend' (file: '/var/azuracast/stations/<WRONG STATION NAME>/config/supervisord.conf')
```

**Comment by shogd3838** [comment]
After trying different things, none of them worked, the solution was to completely delete the local station folder that contains stations data and medias and restore everything from a full backup that contains the media files.

So to everyone, always do a full backup that includes all the music files before any update !

**Comment by HiddenLights** [comment]
Hello! Today, I had the same issue updating to the latest "Rolling Release" version and disabling Liquidsoap, restart and enabling it, has fixed the problem.

**Comment by shogd3838** [comment]
Thank you very much for this information.
Hope it can help other people.
