### ISSUE TITLE
Scheduled general rotation playlists are mixed with unscheduled general rotation playlists outside of schedules

### ISSUE THREAD

**Issue by guiltlab** [AzuraCast/AzuraCast#5618]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

I would like the AutoDJ to only use one specific playlist as the source when there is no scheduled playlist running, but it doesn't seem to be currently possible.

Example of setup:
39 different playlists, all assigned to schedule timeslots, all "general rotation" type. 1 playlist that I actually want to play when there is nothing else scheduled, also set as "general rotation" type.

7am-8am: scheduled playlist 1
8am-10am: scheduled playlist 2
10am-11am: nothing scheduled
11am-1pm: scheduled playlist 3

Between 10am and 11am, the AutoDJ will play songs from any of the 40 playlists I have set as "general rotation" type, but I would like it to only play from **one** specific playlist and ignore the others, as they are only meant to be used in schedule slots. However, this is not possible because all playlists are of the "general rotation" type. Currently, I set the weight of the playlist I want to play when there is no schedule to "25" and the weight of all other playlists to 1, but that does not work well enough to ensure only the weight 25 playlist gets played when there is no schedule.

Proposed way of fixing this issue: add a new "scheduled playlist" type, that is **outside of the general rotation**. This way, people who want to set playlists to "schedule only" like me can do so, and there is still the option to set schedule slots for playlists that you want to also keep in the general rotation (current behavior). See mockup below:

![image](https://user-images.githubusercontent.com/45518224/180651984-5eb24ab6-1c22-4fee-b154-720548fd81fe.png)

Thanks in advance!

**Comment by fnfzlznddzn** [comment]
bump
sorry if it's bad etiquette, not sure if i should bump when the stale label is added or not, to avoid the issue being closed?

**Comment by fnfzlznddzn** [comment]
bump

**Comment by guiltlab** [comment]
bump

**Comment by BusterNeece** [comment]
I'm reopening this, but looking through the scheduler logic, the system really shouldn't be lumping playlists that *do* have scheduled times in with "General Rotation" playback.
