### ISSUE TITLE
Traditional Install Fails on Servers Where Root User Unavailable

### ISSUE THREAD

**Issue by iserlohner2009** [AzuraCast/AzuraCast#562]
- **Installation Method:** Traditional
- **Host OS (if using Docker):** Ubuntu 16.04, 

![screenshot_1](https://user-images.githubusercontent.com/13096790/39207164-8ed1026c-47ff-11e8-8af5-c88b54e29910.png)
![screenshot_2](https://user-images.githubusercontent.com/13096790/39207166-8eead02a-47ff-11e8-885c-0e23ad7ec202.png)

Hello i Have a Question on you 

I have install the AzuraCast script with Putty SSH, in Putty the Installation is Complete, now i open in my Browser the ip Adress from the Server what i have but i become the Message "File not found"

i cant install that on the Browser 

can anywhere Help

**Comment by iserlohner2009** [comment]
ich habe es heute nochmal installiert aber auch jetzt ist die Seite nicht erreichbar 
hier siehst du auch die Struktur des Servers

![screenshot_1](https://user-images.githubusercontent.com/13096790/39331099-e2b9f5f0-49a3-11e8-8e73-f2767c16eede.png)

![screenshot_2](https://user-images.githubusercontent.com/13096790/39331110-e6add672-49a3-11e8-81be-dcd5dfe9a462.png)

**Comment by iserlohner2009** [comment]
can you give me a detailed guide how I should do it as the operating system I have Ubuntu 16.04 root user does not exist but I am as root u276XXX with the sudo command I can do everything

**Comment by amingomezd** [comment]
i have exactly the same problem, installed in a fresh ubuntu 16.04 on aws, can you please help?

**Comment by SlvrEagle23** [comment]
@iserlohner2009 @amingomezd I've made some changes that should allow you to install AzuraCast on the latest versions of 16.04 and 18.04 without requiring direct root user access, instead just needing any account with `sudo` permission.

**Comment by SlvrEagle23** [comment]
Closing this issue as the Ansible-based traditional installation should now work in "sudo" mode with no issues. If anyone continues to experience these issues, feel free to create a new issue.
