### ISSUE TITLE
Song title in 'Now playing' does not update in time. (in server with several stations)

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#5623]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #5ab3cf9 (2022-07-23 16:10)

### What happened?

Apparently the song title for each station is updated separately one statsion after the other in inteval of 3-4 seconds. 

When a server has many stations, a large time interval between updates is created. ( Station 1 will be updated after all other stations have completed their updates round ) 

On a server with 40 stations for exmple, it might take a few minutes for each station to be update. It results in song title display in 'now playing' being out of date. The player just stay stuck on the previos song name ( see screenshot)

![image](https://user-images.githubusercontent.com/2701228/180772614-9fb7445b-2947-47c3-bb21-ed9c8477b3c9.png)

Would it be possible to make 'nowplaying' sync of all statios at once (in parallel) every 3 seconds?
As far as I remember, in previous versions it worked in parallel.

**Comment by eranwo** [comment]
Here is a screenshot **video** demonstrating the title issue. After the song ends, the title remains and does not update for a couple of minutes

[2022-07-28 12-52-14.webm](https://user-images.githubusercontent.com/2701228/181483455-2121a8d1-4fbc-4348-b9da-2a37c35c4e9e.webm)

**Comment by adoboligh1** [comment]
i have this same issue, it takes around 10 to 15 seconds sometimes a whole minute.

**Comment by Mozitux** [comment]
Same issue here with only one station, it can take up to 15s to update

**Comment by eranwo** [comment]
Up

**Comment by adoboligh1** [comment]
Must be.

**Comment by eranwo** [comment]
v0.17.5 Stable - the issue still exist

**Comment by BusterNeece** [comment]
As mentioned in other issues, we strongly recommend using the "High Performance Now Playing Updates" setting in System Settings if your installation allows for it (most do). This, along with other changes we've made in new versions, should result in much, much more accurate Now Playing playback times and track progress.

**Comment by eranwo** [comment]
@BusterNeece The "High Performance Now Playing Updates" haven't worked for me. The songs are still getting updated after a minute + -.
The last stable version that worked properly was v0.14.1.
As of version 15, you made changes to the synchronization mechanism and isolated the Now Playing synchronization.
Suddenly, Now Playing went wrong. Previously, the synchronization had been parallel for all stations on the server at the same time. From ver. 0.15.0 (Jan 12, 2022), it has been serial, meaning station by station.
Having one or two stations on the server is not a problem, but when you have more, synchronization for each station takes very long time
Hopefully, you will be able to find a solution to this problem.

**Comment by BusterNeece** [comment]
@eranwo I think your characterization of the Now Playing updates are inaccurate, and in fact are backwards to what really changed in recent versions.

Previously, we had a single "Now Playing" sync task that iterated through all stations every 15 seconds, one by one, and updated their current playing data. This limited the accuracy of any given station to that 15-second window, and if the combined total of stations on an installation led to load times exceeding those 15 seconds, the updates would "pile" on top of each other, causing lots of problems.

The updated system dispatches each station's now-playing updates as a separate process, then keeps an eye on all of them and triggers a new check a few seconds after the last check has completed. This means that if NP updates come back for a given station very quickly, then we get increasingly accurate results from that station, even if other slower stations exist on the same installation. It also means that we never "pile up" with checks, as the Now Playing service is an always-running service that doesn't just run every 15 seconds.

Whatever is going wrong in your specific case is something we should investigate, but fundamentally the structure of the new Now Playing update service should be _improving_ these things, not harming them.

**Comment by eranwo** [comment]
@BusterNeece If it helps, I can share with you the root password to my test server so you can investigate the problem directly

**Comment by BusterNeece** [comment]
@eranwo I don't do direct installation inspections for AzuraCast as part of our free support tier any more.

**Comment by eranwo** [comment]
@BusterNeece  I Got it. Could you please let me know if there is anything I can do to help resolve this issue? If you need logs or anything else, please let me know. Currently, I am not able to upgrade beyond version 0.14.1.

**Comment by BusterNeece** [comment]
@eranwo In our latest Rolling Release versions, we've slightly tweaked how we handle Now Playing processes. This updated method should improve the responsiveness of your Now Playing updates, especially on installations with multiple stations.

**Comment by eranwo** [comment]
@BusterNeece That's great! I have tested it, and it works better than ever. Now playing updates instantly whenever the song changes. This is exactly what I was looking for. I love it! 
There is only one problem I noticed, the CPU load (1 minute) before the upgrade was 3 now it's 23 .Servers with 12 CPUs, 64GB ram, and SSD drives

**Comment by BusterNeece** [comment]
@eranwo If you look at, say, htop on the host...what's consuming all that CPU? There may be one or two stations that are running into the crash/restart problem we saw before.

**Comment by eranwo** [comment]
@BusterNeece Mysql seems to be the cause of the overload
![image](https://user-images.githubusercontent.com/2701228/212669959-af94578c-4743-499b-8489-6c95aeca32b7.png)

**Comment by BusterNeece** [comment]
@eranwo How many stations/listeners are we talking about? It's likely that the previous Now Playing process was having problems because the DB transactions to set listener data took so long that it never got around to the other stations, which is why things kept going out of sync, and now that we've switched things around, it's just a ton of load on the DB all at once.

We may need to make the "time between now-playing pings" to be a configurable thing on a per-installation basis, just so you can tune it down if needed for larger installs. Right now, we're pinging every 5 seconds or so, which does yield much higher-resolution now playing data, but if you wanted to match our older process, you could slow that down to 15 seconds and still get fairly good results.

**Comment by BusterNeece** [comment]
@eranwo I pushed up a change that optimizes how we ingest listeners even further, which should help with the heavy load times of our regular Now Playing tasks if you have a large variable population of listeners. Let me know if that helps your installation in any way.

**Comment by BusterNeece** [comment]
If, after the latest update, you're still seeing too much MariaDB load on your installation, you can try tuning the delay between Now Playing checks. By default, it's 5 seconds, but if you set it to longer, it'll reduce the load on your server considerably. The value is `NOW_PLAYING_DELAY_TIME` and can be set in `azuracast.env`.
