### ISSUE TITLE
Lost the information about the city of listeners

### ISSUE THREAD

**Issue by Kkspike** [AzuraCast/AzuraCast#5628]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.2 Stable • Docker • PHP 8.1

### What happened?

Since a couple of versions, the information about the city location of the listeners isn't showing in the API (or the map on the GUI for that matter). I know you guys didn't bother with the coty info on the listeners report because it's innacurate, but I was able to pull it from the API and make a page showing where our live listeners where located (even if it was sometimes innacurate). We've been using the GeoLite database for months now without issue (I checked and it was updated two days ago).

Is this something that was removed somewhere in Azuracat alltogether in the last couple of versions ?
![image](https://user-images.githubusercontent.com/35116060/181298384-5d13d2fd-8ebd-42a3-972a-46fcab870ad8.png)

I enclosed the content of a listener object location from the API, it shows null

### Relevant log output

```shell
object(stdClass)#3 (6) { ["description"]=> string(10) "Quebec, CA" ["region"]=> string(6) "Quebec" ["city"]=> NULL ["country"]=> string(2) "CA" ["lat"]=> string(9) "45.567100" ["lon"]=> string(10) "-73.899400" }
```

**Comment by Vaalyn** [comment]
Yep, there was a small bug in the refactored code for the geoip stuff.

Thank you for the report.

When the new Docker image has finished building this should be fixed and you can see the City on the pin again as well as get it through the API 👍
