### ISSUE TITLE
Built-in API tester doesn't seem to input some arguments to requests

### ISSUE THREAD

**Issue by janek** [AzuraCast/AzuraCast#5631]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.2

### What happened?

At http://my-station.com/static/api/index.html, you can read the API documentation and test it. When I test an endpoint with no parameters (like `nowplaying`), it works fine. When I tried to use an endpoint with an argument (`/nowplaying/{station_id}`), and input "1" as a station ID, I was getting a "resource not found" answer. I tested this endpoint independently and "1" is a valid value in my case. 

Looking at the UI of the page and the Network tab browser dev tools, I think that the API tester uses the string `{station_id}` literally, rather than treating it as a variable and inputting its value (the string `1`) instead.

### UI
<img width="1429" alt="Screenshot 2022-07-28 at 11 36 41" src="https://user-images.githubusercontent.com/2146927/181474494-9d8d4e93-34fb-4632-bd25-155987e3a540.png">

### Network tab:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/2146927/181476042-6c8637b7-b5ff-4b69-8bbd-55d80cfb61ad.png">

**Comment by janek** [comment]
I tested another endpoint, and playlist id was input correctly, while station id wasn't. Could be that this affects station id specifically.


<img width="894" alt="image" src="https://user-images.githubusercontent.com/2146927/181480871-d7d5670d-c2a0-46fd-95a4-33242528a520.png">

**Comment by devrob20** [comment]
has the api-key your testing have the correct rights to access the station ID ?

**Comment by caturria** [comment]
I can confirm that this is affecting me as well. The API test form literally sends {station_id} instead of the supplied value to any endpoint which expects a station ID.
Also, complements on this fantastic software.

**Comment by andretunes** [comment]
Hello,
I found out, that the file `openapi.yml`, in `https://example.com/api/openapi.yml`, instead of having this configuration:
```yml
  parameters:
    StationIdRequired:
      name: station_id
      in: path
```

We have:
```yml
  parameters:
    StationIdRequired:
      name: StationIdRequired
      in: path
```

I opened a PR #6230, hope they accept it. It fixed it, in my side.

**Comment by Moonbase59** [comment]
Same as @caturria here, Rolling Release #[c0e9752](https://github.com/AzuraCast/AzuraCast/commit/c0e975294ef2b80f83cea4c107c4d296b516a081) (2023-04-22 9:11).
