### ISSUE TITLE
schedules are not respected when a dj is connected. reopening #5499

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#5635]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

5ab3cf9 (2022-07-23 16:10) • Docker • PHP 8.1

### What happened?

hello,
if i have one playlist set to play from 10h to 11h, for example, and a dj connects 09:59h and disconnects 13h, the scheduled playlist will play because is marked with next song. autodj is skiping songs normally after dj disconect, but i think when the dj disconects it have to verify if the quewe contains songs out of schedule and remove or replace it. as oter way i think it probably need a extra option because in some cases it is good to play out of schedule songs, and oter cases are not. i think in playlists that have the stop actual song checked it need to respect the start and end schedule and not play when are out of schedule. with the actual behaviour, if i have for example 1 hour files, and have one playlist to play every hour, is enough to bug a dj connects, disconnects as i explained, and the rest of the day will run with delay.

**Comment by Vaalyn** [comment]
Reopened the original issue thread #5499, closing this one here to prevent duplicate issues.
