### ISSUE TITLE
Let's Encrypt Error - Certificate not due for renewal

### ISSUE THREAD

**Issue by s7ntax** [AzuraCast/AzuraCast#5636]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.1 Stable

### What happened?

When renewing the certificate in azuracast it fails with the error 'certificate not expired'

I do not want to have to wait until it expires before I renew it, this is because I run Azuracast on port 8443 as I also run apache on the same server so I need to manually stop apache and temporarily change the ports for azuracast so that I can renew the cert. 

Is there a way that I can renew it early, I am reluctant to bash into the container and delete the certificates as I do not want to break the installation. If someone can confirm if there is a safe way to do this or another way to renew early so that the certificate never expires. 

Thanks

**Comment by ItsMitchh** [comment]
Thanks for the report, I'll get this pushed up to the team, see what they think.

**Comment by hillebr** [comment]
...same here on webradio.gq latest build Release #6a30481 (2022-08-22 7:34) 

CLI says: root@k005107vsa:/var/azuracast# ./docker.sh letsencrypt-create
LetsEncrypt is now managed from within the web interface.

Web interface: [2022-08-22T19:12:48.789034+00:00] AzuraCast.DEBUG: ACME: Using directory URL: https://acme-v02.api.letsencrypt.org/directory [] []
[2022-08-22T19:12:48.795956+00:00] AzuraCast.ERROR: ACME Error: Certificate does not need renewal. {"exception":"[object] (RuntimeException(code: 0): Certificate does not need renewal. at /var/azuracast/www/src/Service/Acme.php:131)"}

Monitoring: SSL_CERT WARN webradio.gq: x509 certificate will expire in 21 day(s) on Sep 13 14:26:53 2022 GMT

So how to renew?

**Comment by hitzgh** [comment]
same issue here , i thought i did something wrong but that was not the case

**Comment by modularstation** [comment]
Same issue here.
It should be renewed before letsencrypt sends a notice by mail.
It's the first renewal I'm receiving this mail.

**Comment by burjuyz** [comment]
the same situation.
`azuracast  |  [ERROR] Certificate does not need renewal.
azuracast  |
azuracast  | [2022-09-08T16:57:33.323159+00:00] AzuraCast.WARNING: Console command `azuracast:acme:get-certificate` exited with error code 1. [] []
`

**Comment by BusterNeece** [comment]
@burjuyz In the latest Rolling Release version, I have increased the threshold for LetsEncrypt certificate renewal to 30 days, to avoid you receiving any "upcoming expiration" e-mails from LetsEncrypt. Even in previous versions, your certificate should never expire, it should just renew 14 days away from its expiration date instead of 30 days, which means you may receive a notice but should still have no issues with continuity of service.

**Comment by hitzgh** [comment]
@BusterNeece how about my issue, new installation but i cannot install i get the error

./docker.sh letsencrypt-create
LetsEncrypt is now managed from within the web interface.

i use cloudlflare as dns but i bypass their sssl

**Comment by BusterNeece** [comment]
@hitzgh As the message says, LetsEncrypt is now managed via the web interface, via System Administration > Settings > the "Services" tab.

**Comment by hitzgh** [comment]
@BusterNeece thank you very much it works perfectly now

**Comment by s7ntax** [comment]
> @burjuyz In the latest Rolling Release version, I have increased the threshold for LetsEncrypt certificate renewal to 30 days, to avoid you receiving any "upcoming expiration" e-mails from LetsEncrypt. Even in previous versions, your certificate should never expire, it should just renew 14 days away from its expiration date instead of 30 days, which means you may receive a notice but should still have no issues with continuity of service.

This doesn't help when you run Azuracast on non standard ports, it won't update automatically as it's not on ports 80 and 443 and so it has to be done manually. I still get the error when I try to update it manually.

I have a certificate for the same domain that I use certbot to update automatically and that lives in /etc/letsencrypt/live
however i can't point Azuracast to this certificate as it doesn't seem to like the certificates that end in .pem extension and is looking for a certificate ending in .crt

Is there a way using docker-compost-override.yml to point azuracast to my certbot certificate ending with the .pem extension that exists outside of the docker container on my server, the domain is the same as the azuracast domain. This will remove any port conflict issues when renewing the certs and I won't have to disable apache and change the azuracast ports each time.

**Comment by BusterNeece** [comment]
@s7ntax In recent versions we've changed how our SSL directory is laid out (since we now manage LetsEncrypt internally via our web interface), so the path has changed to mount a custom SSL certificate. See the updated info here: https://docs.azuracast.com/en/administration/ssl-and-lets-encrypt#using-a-custom-certificate

After you update the location, it should work just as it did before (and you can still just remap the `fullchain.pem` to `ssl.crt`).

**Comment by s7ntax** [comment]
> @s7ntax In recent versions we've changed how our SSL directory is laid out (since we now manage LetsEncrypt internally via our web interface), so the path has changed to mount a custom SSL certificate. See the updated info here: https://docs.azuracast.com/en/administration/ssl-and-lets-encrypt#using-a-custom-certificate
> 
> After you update the location, it should work just as it did before (and you can still just remap the `fullchain.pem` to `ssl.crt`).

The paths I have set in my docker-compose-override.yml are exactly as the ones on the page you linked to, however Azuracast is still using it's own certificate and not the one I am mapping.

**Comment by s7ntax** [comment]
> @s7ntax In recent versions we've changed how our SSL directory is laid out (since we now manage LetsEncrypt internally via our web interface), so the path has changed to mount a custom SSL certificate. See the updated info here: https://docs.azuracast.com/en/administration/ssl-and-lets-encrypt#using-a-custom-certificate
> 
> After you update the location, it should work just as it did before (and you can still just remap the `fullchain.pem` to `ssl.crt`).

Thank you, I have successfully mapped it now.
