### ISSUE TITLE
Why automatic tasks not starting ?

### ISSUE THREAD

**Issue by drno88** [AzuraCast/AzuraCast#5654]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.12.1

### What happened?

Good day.
First of all, thanks for your product!
We use it not exactly as intended, but to automate music in various institutions.
Everything works well, but there was one problem with our new hardware
I understand that our method of use is different from what was intended, but I think you can tell me what and where I need to check

We use - 
Armbian x64 - ubuntu 18.04 (latest)
Azuracast Ansible - 0.12.1  (until we can update, for personal reasons)

Automatic tasks do not work.
sync:run [nowplaying|short|medium|long]
Not work from web interface too

but they work from the command line))

All log files are empty. There are no errors.
in folder /tmp  a file with a task is created, of the form sync_task_nowplaying_gbMJqr  and sync_task_nowplaying_gbMJqr.log
but they are empty
And hang there

The problem is only with Armbian.  x86\64 have no problem
log2ram is disable

Can you please tell me what and where should I check? to start working on these tasks?

**Comment by ItsMitchh** [comment]
Good day,

You are using an incredibly old version, but I see you mentioned you can't update, which is fine. 

When you attempt to run the tasks while in the browser, can you check the browser logs to see if any network errors show?

**Comment by drno88** [comment]
After I wrote here, I thought of looking at the crontab for the user azuracast
It was completely empty

I copied it from a working installation and it worked.

I tried for 3 hours to understand what was wrong ... and I reinstalled Azura .. but for some reason I guessed only now)))

`
0 * * * * php /var/azuracast/www/bin/console sync:run long
*/5 * * * * php /var/azuracast/www/bin/console sync:run medium
*/5 * * * * php /var/azuracast/www/bin/console queue:process 275
* * * * * php /var/azuracast/www/bin/console sync:run short
* * * * * php /var/azuracast/www/bin/console sync:run nowplaying
* * * * * sleep 15; /var/azuracast/www/bin/console sync:run nowplaying
* * * * * sleep 30; /var/azuracast/www/bin/console sync:run nowplaying
* * * * * sleep 45; /var/azuracast/www/bin/console sync:run nowplaying
0 */6 * * * tmpreaper 12h /var/azuracast/stations/*/temp


`

**Comment by SlvrEagle23** [comment]
@drno88 This is what should be in the AzuraCast user's cron tasks as of the latest stable version:
https://github.com/AzuraCast/AzuraCast/blob/main/util/ansible/roles/azuracast-cron/templates/azuracast_cron.j2
