### ISSUE TITLE
Remote Relay page not loading

### ISSUE THREAD

**Issue by AliUK1** [AzuraCast/AzuraCast#5657]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.2

### What happened?

I created a Remote Relay, in which I don't think it has been configured correctly. After attempting to delete it, by visiting the Remote Relay page, it gets stuck with an infinite loop. I expected it to display the current & only remote relay, in which I should be able to edit it. I tried looking on the network tab, as instructed via Discord support, that showed up clean & so did Chrome's console log.

I did some digging in the LiquidSoap Logs and discovered the remote relay was erroring out. (Probs because I set it up worng), however I'm not sure how that would affect me not being able to visit the remote relay page & delete it. 

I have attached the relevant LiquidSoap logs below.

### Relevant log output

```shell
2022/08/07 18:34:08 [relay_1:3] Connecting mount Use [name] for source@s51.radiolize.com...
2022/08/07 18:34:08 [relay_1:2] Connection failed: SSL connection() error: error:00000000:lib(0):func(0):reason(0)
2022/08/07 18:34:08 [relay_1:3] Will try again in 3.00 sec.
```

**Comment by ItsMitchh** [comment]
Should be fixed in the latest rolling release, can you let us know?
