### ISSUE TITLE
Long wait time when press play

### ISSUE THREAD

**Issue by youngdesenv** [AzuraCast/AzuraCast#5658]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.3

### What happened?

When the listener presses play it takes a long time to load the audio, if we restart the azuracast service this problem comes back after a few days. Does anyone know what can it be?

**Comment by Mozitux** [comment]
Hello, check your RAM and CPU consumption in the Azuracast administration, aren't they high?

**Comment by youngdesenv** [comment]
![statusCast2](https://user-images.githubusercontent.com/46824994/184134949-aa861176-e8d4-4839-b6b8-fcb4d377acc8.png)

It doesn't seem to have high consumption, but it continues to be slow and also crashes at times.
