### ISSUE TITLE
server cannot see files in storage location but azuracast can

### ISSUE THREAD

**Issue by Ohmslaw79** [AzuraCast/AzuraCast#5661]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.3 Stable

### What happened?

This might be a really dumb question but, I am working on cleaning up a bunch of stuff on my current azuracast installation and one thing I have run into is none of the media files seem to be in the location specified by azuracast on the storage locations page. All of the storage locations say that they are under ```var/azuracast/stations/station_name``` however when I look in ```var/azuracast```  there is no stations folder, let alone any of the subfolders or files. At first, I thought that maybe it just couldn't create the directories so it wasn't saving recordings, however, I can access all of the recordings from the azuracast website. Am I just looking in the wrong spot?

**Comment by ItsMitchh** [comment]
Hi,

The folders you seek are currently inside the Docker container, you'll need to go to `/var/lib/docker/volumes/` and have a look in here. I believe the folder your looking for is called `station_data`

**Comment by Ohmslaw79** [comment]
I figured it was just a quirk of the install. Thank you!
