### ISSUE TITLE
Custom network subnet configuration

### ISSUE THREAD

**Issue by messkaline** [AzuraCast/AzuraCast#5664]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.3

### What happened?

Hey, Azuracast!

I use custom icecast configuration(due to using my own nginx) to show correct listener IP in reports like:

```
<paths>
    <x-forwarded-for>172.18.0.1</x-forwarded-for>
</paths>
```

it works well, but there is one issue - it assign to container new different network subnet(172.19.0.1/16, 172.20.0.1/16 etc) each time when docker restarted. So I need to check what subnet was assigned, then go to icecast configuration and change "x-forwarded-for" option after each restart....It is very uncomfortable

Could you please explain how bind custom network subnet in docker-compose.override.yml correctly?

**Comment by SlvrEagle23** [comment]
@messkaline I believe wildcards are supported on that field, if you wanted to just use that.

**Comment by messkaline** [comment]
it works! thank you so much

```
<paths>
    <x-forwarded-for>172.*.*.*</x-forwarded-for>
</paths>
```
