### ISSUE TITLE
Remote URL playlist Schedule bug

### ISSUE THREAD

**Issue by sbhal** [AzuraCast/AzuraCast#5666]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #[e087567](https://github.com/AzuraCast/AzuraCast/commit/e087567a648d8eccf60f204620665ec3107f39ed) (2022-08-08 0:39)

### What happened?

I have few Remote URL based playlist and while trying to edit a schedule for a playlist, the same schedule is applied to remaining playlists. I believe, its a bug since every playlist can have unique schedule.

**Comment by SlvrEagle23** [comment]
@sbhal We need much more information about this bug, since it sounds like it involves specific steps.

Can you document the exact steps you follow to reproduce this issue?
