### ISSUE TITLE
What options are there to increase more than 50 radio in azuaracast?

### ISSUE THREAD

**Issue by guidomontp** [AzuraCast/AzuraCast#5674]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

AzuraCast • v0.17.3 Stable • Docker • PHP 8.1

### What happened?

What options are there to increase more than 50 radio in azuaracast?

### Relevant log output

```shell
What options are there to increase more than 50 radio in azuaracast?
```

**Comment by ItsMitchh** [comment]
hi there, you can use our update script to extend the ports to allocate more stations. By default, it's up to `8499` but you can expand this to `9000` for example.
