### ISSUE TITLE
liquidsoap costume doesn't work well

### ISSUE THREAD

**Issue by gunsar** [AzuraCast/AzuraCast#5677]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.3

### What happened?

liquidsoap costume doesn't work well

` def live_aware_crossfade(old, new) =
    if !to_live then
        # If going to the live show, play a simple sequence
        sequence([fade.out(old.source),fade.in(new.source)])
    else
        # Otherwise, use the smart transition
        cross.simple(old.source, new.source, fade_in=0.00, fade_out=0.00)
    end
end
radio = cross(minimum=0., duration=3.00, live_aware_crossfade, radio) `

fadein and fade out are still running, even though they have been made 0.00

I tried on a non-azuracast panel
`	("crossfade", "3"),
	("crossfade_fadein", "0"),
	("crossfade_fadeout", "0"),
	("crossfade_mode", "normal"),
	("replay_gain", "0"),`

run well crossfade without fadeout fadeout

**Comment by ItsMitchh** [comment]
hi, this might be a upstream issue with liquidsoap, can you post an issue there for them to look?

**Comment by gunsar** [comment]
I'm setting on Centova version 15.0
`radio = crossfade(smart=false, duration=3.00, fade_out=0.00, fade_in=0.00, radio)` 
crossfade runs smoothly without fadein and fadeout

> hi, this might be a upstream issue with liquidsoap, can you post an issue there for them to look?
