### ISSUE TITLE
Song History does not match with Song Playback Timeline

### ISSUE THREAD

**Issue by afonsosantos** [AzuraCast/AzuraCast#5678]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #048791d

### What happened?

Have 2 playlists:

- default - normal rotation, some songs
- jingles - played between each song, jingle mode enabled

On my public site, I have the Song History embed widget, that displays the last 5 songs. After enabling the jingles, the widget does not match the timeline on the Song Playback Timeline page in Azuracast.

![image](https://user-images.githubusercontent.com/46262740/185252373-57ad0aab-15d4-4f2d-ab4b-da9ea306274e.png)

![image](https://user-images.githubusercontent.com/46262740/185252395-a1a36ed0-c0d1-4ee3-ba06-f9627a4e4183.png)

Before enabling the jingles playlist, the widget was ok. Now, the songs appear as duplicates.

**Comment by SpeedyCharly** [comment]
Had the same issue a while back....  was about to report it when a rolling release update appeared to solve it...

**Comment by BusterNeece** [comment]
Likely the same cause as #5589; see that thread for an upstream issue with Liquidsoap that may be the cause.

**Comment by julianborghuis** [comment]
same problem

**Comment by BusterNeece** [comment]
@julianborghuis Please stop replying to threads saying "same problem".
