### ISSUE TITLE
Resize Storage

### ISSUE THREAD

**Issue by iDJHost** [AzuraCast/AzuraCast#5680]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.3 Stable

### What happened?

Tried resizing the storage like I normally would on my VM's but AzuraCast does not recognize the space change, also unsure which directory (/root or /home) it uses for space to the rest of the free space to the proper location.

/admin page says 53.7 GB

lsblk:
dev/centos/root had 50G
dev/centos/home had 69G
added 10G each
dev/centos/root now has 60G
dev/centos/home now has 79G

/admin page still says 53.7 GB

### Relevant log output

```shell
N/A
```

**Comment by iDJHost** [comment]
I did do docker-compose down & docker-compose up -d to restart AzuraCast to see if that helped.

**Comment by BusterNeece** [comment]
@iDJHost This may be an issue with Docker or with how your partitions are mounted in the VPS itself. Usually, Docker stores its own internal data in a directory similar to `/var/lib/docker/volumes`, so wherever that's mounted is what you would want to expand.

**Comment by nexion63** [comment]
Hello @BusterNeece,
I installed Azuracast which is a pure happiness for webradios or radio in DAB+, thank you very much for this development.

I have the same problem as @iDJHost , I put on an Ubuntu server via docker with 80 GB of storage but Azuracast uses only 41 GB, I do not understand why?

Could you explain me more in detail?
Can we increase the storage?

Thanks !
