### ISSUE TITLE
AutoDJ Suggestion

### ISSUE THREAD

**Issue by iDJHost** [AzuraCast/AzuraCast#5681]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.3 Stable

### What happened?

Have AutoDJ "stopped" by default so Broadcaster can be online for immediate use with DJ software like Mixxx.

Currently - Need to upload at least one file, start broadcaster and then stop AutoDJ.

**Comment by iDJHost** [comment]
Another Suggestion: 
Implement AutoDJ storage limits
Station 1: 5GB
Station 2: 10GB

**Comment by ItsMitchh** [comment]
You can already limit storage limits for stations. 

For other suggestions, post them here: https://features.azuracast.com

**Comment by iDJHost** [comment]
How do I limit the storage? I have looked through all 4 tabs for station creation/edit and I don't see any options for limiting storage.

**Comment by iDJHost** [comment]
> You can already limit storage limits for stations.
> 
> For other suggestions, post them here: https://features.azuracast.com


How do I limit the storage? I have looked through all 4 tabs for station creation/edit and I don't see any options for limiting storage.

**Comment by BusterNeece** [comment]
@iDJHost You go to the System Settings, then "Storage Locations", and then for the per-station storage location you can set a quota.

**Comment by iDJHost** [comment]
@ItsMitchh Thank You, I figured it out right after asking and used the link you provided for suggestions, suggesting maybe adding it in to station creation instead since that seems more like the most logical place for setting all the stations limits in 1 go. But for now, it's fine.
