### ISSUE TITLE
Deleting a Station can fail to remove

### ISSUE THREAD

**Issue by alencarwell** [AzuraCast/AzuraCast#5683]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.17.3 Stable • Docker • PHP 8.1

### What happened?

Hello,

My Azuracast is giving a strange error.
I deactivated the transmission of a station, then I tried to remove it, but it was even deactivated, but I cannot remove it from the system, nor can I reactivate it.

I wanted to totally delete this station, but I can't.

I click the remove button and nothing happens.

**Comment by ItsMitchh** [comment]
Can you give us the error AzuraCast returned? 

You can also look into the docker logs for this.

**Comment by alencarwell** [comment]
It does not generate any errors on the screen, it simply does not delete the station, nor does it activate the transmission anymore.

I don't know where to get these logs on Linux.

**Comment by ItsMitchh** [comment]
You can get the logs from running this command. 

Go to your Linux Terminal/SSH. Run this command > `cd /var/azuracast` and then run `docker-compose logs -f`
