### ISSUE TITLE
LetsEncrypt having issues connecting to ACME

### ISSUE THREAD

**Issue by TGCFabian** [AzuraCast/AzuraCast#5684]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #048791d (2022-08-13 22:49)

### What happened?

While setting up Azuracast, i tried to generate the SSL Certs for the Icecast servers 
(Which is not needed when using "Web Proxy for Radio", but its a nice to have)

While generating it, it errors out where it then says no route to host

To reproduce:
Administration
System Settings
Services
Generate/Renew Certificate

(I could not find a similar issue within the repo, thus making a new issue)

Edit:

Using Certbot manually, and following the docs (https://docs.azuracast.com/en/administration/ssl-and-lets-encrypt)
I did manage to get it to work, 

Ofcourse, this cant be seen as a fix, as this is a pure work around
Would love to see the integration itself to be fixed

(Also when trying to go to the "Install Shoutcast" page gives me a Slim error, should i open a extra ticket or is this known?)

### Relevant log output

```shell
[2022-08-18T18:42:16.611733+00:00] AzuraCast.DEBUG: ACME: Using directory URL: https://acme-v02.api.letsencrypt.org/directory [] []
[2022-08-18T18:42:16.619559+00:00] AzuraCast.ERROR: ACME Error: HTTP Request Error: Failed to connect to acme-v02.api.letsencrypt.org port 443: No route to host {"exception":"[object] (Exception(code: 0): HTTP Request Error: Failed to connect to acme-v02.api.letsencrypt.org port 443: No route to host at /var/azuracast/www/vendor/skoerfgen/acmecert/src/ACMEv2.php:311)"} []
```

**Comment by ItsMitchh** [comment]
Thank you for the report, will look into this issue soon.

**Comment by BusterNeece** [comment]
I noticed our documentation page on LetsEncrypt is out-of-date and is no longer accurate; we now manage LetsEncrypt via the web interface. I've updated that page accordingly.

The error you're experiencing suggests that your VPS doesn't have access to an external DNS server. Most VPSes are configured with usable DNS servers out of the box, but in case they aren't, you can usually edit a file (possibly `/etc/resolv.conf`) to supply your own. Here are a few common ones:

```
nameserver 9.9.9.9
nameserver 8.8.8.8
nameserver 1.1.1.1
```

These correspond to the Quad9 DNS service, Google's DNS provider, and Cloudflare's DNS provider, respectively.

**Comment by TGCFabian** [comment]
> I noticed our documentation page on LetsEncrypt is out-of-date and is no longer accurate; we now manage LetsEncrypt via the web interface. I've updated that page accordingly.
> 
> The error you're experiencing suggests that your VPS doesn't have access to an external DNS server. Most VPSes are configured with usable DNS servers out of the box, but in case they aren't, you can usually edit a file (possibly `/etc/resolv.conf`) to supply your own. Here are a few common ones:
> 
> ```
> nameserver 9.9.9.9
> nameserver 8.8.8.8
> nameserver 1.1.1.1
> ```
> 
> These correspond to the Quad9 DNS service, Google's DNS provider, and Cloudflare's DNS provider, respectively.

I Think you possibly mis-understood my issue

This issue actually happened while using the web interface, and at the time, 
My DNS Servers are working fine, as i was able to generate SSL Certificates with certbot (On the machine itself) just fine, just not via the web interface
Webinterface gave the error listed above, 

Right now, i cant test it again, as it has valid certificates, but if it happens again, ill notify
