### ISSUE TITLE
Schedules not working

### ISSUE THREAD

**Issue by derks-wesley** [AzuraCast/AzuraCast#5687]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #7f6df2a

### What happened?

Create schedule windows is crashing.
When i create a schedule it is not showing up.

Once i was able to create one i could not delete it.

### Relevant log output

```shell
Let me know what you need!
```

**Comment by AnitaLalu** [comment]
The playlist does not play at a Scheduled Time.

I have tried lots of time scheduling a Playlist, but the playlist does not play at a scheduled time. Can anyone please guide how to get this working?

**Comment by Seehed** [comment]
I have tried switching releases, and neither worked, and scheduled playlists are very important to me, since I air a nationally-wide music show at a set time. Please devs, fix this, automation of scheduled playlists make it way better than doing it manually.

**Comment by kemecs** [comment]
is the container time zone OK?
