### ISSUE TITLE
Crossfade help

### ISSUE THREAD

**Issue by radiobellissima** [AzuraCast/AzuraCast#5688]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#ed220ad (2022-08-13 3:55) 

### What happened?

I've always used custom crossfade settings to get rid of that ugly fade in.

This is the string I currently use:
radio = crossfade(smart=false, duration=2.00, fade_out=2.00, fade_in=0.01, radio)

After updating to the latest versions this is completely ignored, I saw that even in the edit page these items have disappeared. So I ask is it a bug or is there a new way to get rid of the fade in?

Thanks

**Comment by ItsMitchh** [comment]
Closed, duplicate
