### ISSUE TITLE
bug with the new installation script?

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#569]
- **Installation Method:** 
- **Host OS (if using Docker):** 

**Describe the issue in full detail, including screenshots if possible:**
Hello,
I see that there is new install script
curl -L https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh
chmod a+x docker.sh
./docker.sh install

I do get this error when installing on a fresh debian 9 kvm.

root@ls:~# ./docker.sh install
Docker is already installed! Continuing...
Docker Compose does not appear to be installed. Install Docker Compose now? [Y/n] y
./docker.sh: line 70: sudo: command not found
./docker.sh: line 71: sudo: command not found
./docker.sh: line 72: sudo: command not found
./docker.sh: line 86: docker-compose: command not found
./docker.sh: line 87: docker-compose: command not found
./docker.sh: line 88: docker-compose: command not found

**Comment by SlvrEagle23** [comment]
@surihost You need to have `sudo` installed on your host computer. I didn't include this in the instructions as I assumed a vast majority of VPSes and server images would have `sudo` on them by default, with the only exception really being containerized OSes like Alpine.

**Comment by SlvrEagle23** [comment]
Closing as I've added the note to the installation instructions that `sudo` and `curl` are required before proceeding with Docker installation. A vast majority of server instances should already have these installed, so this largely shouldn't be an issue.
