### ISSUE TITLE
Client website crashing with out of memory errors when embedding AzuraCast stream

### ISSUE THREAD

**Issue by matthewunmuted** [AzuraCast/AzuraCast#5691]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.1

### What happened?

One of our clients has a website where they have embedded an AzuraCast stream hosted with us - they are reporting that their website is crashing every couple of hours with out of memory errors. They have contacted a local developer who has indicated that this is not an issue with their website, but rather an issue with either ShoutCast or AzuraCast.

The developer believes that the stream is not purging old data/there is no buffer/garbage collector function, which is causing the browser tab to exceed the allowed memory limit

Any help or advice would be appreciated on this

**Comment by BusterNeece** [comment]
@matthewunmuted Does this station have HLS streaming enabled? This may be something to do with that, as that involves storing the smaller chunks of HLS data locally, converting them for playback, and then playing them...and could exhaust memory more rapidly than traditional streaming.

**Comment by matthewunmuted** [comment]
Hi Buster, many thanks for your prompt response. This station does not have HLS streaming enabled currently

**Comment by Omnichannel-nz** [comment]
Hi! Referred local Dev here.

Just to provide more information on the troubleshooting:
- Firefox does not crash.
- 3 different Chromium-based browsers crash with out of memory errors, on very specific intervals (i.e. 3 Hours 20 minutes after initiating a stream)
- The website itself doesn't crash, it's still accessible - it is just the browser tab on local machines that crash.
- I cannot verify 100% where the issue resides, but in my research it appears to be related to a 'garbage collector' function not clearing old data, hence the browser running of out allowed memory and crashing the tab.
- This appears to be only an issue for Chromium based users who stream for over 3 hours (bitrate dependant I guess), but as is the nature of a radio streaming service, that could be quite regular.

Glad to see both the web host and cast provider working together on this to determine where the issue may be.

**Comment by BusterNeece** [comment]
@Omnichannel-nz @matthewunmuted I'm not actually sure that there's anything we can do on our end to resolve this. I think there's a distinct possibility that in Chrome, the HTML5 `<audio>` tag thinks, for whatever reason, that it needs to keep the entire previously played track in its buffer, which would result in a fairly predictable "out of memory" limit being hit after a certain period of playback.

There are some workarounds we could apply, such as automatically "flushing" the player every hour or so (stopping and then restarting it on the same URL, which deletes the previous `<audio>` element entirely and makes a new one under the hood, which should flush any associated buffer as well). I would expect that, for most users, while this would be noticeable it wouldn't be a huge inconvenience versus the inconvenience of having one's browser tab hang or fill up with a great deal of memory.

**Comment by Omnichannel-nz** [comment]
Thanks @BusterNeece - when you say noticeable, what would the end-user/listener experience?  A temporary cut-out of the audio?
