### ISSUE TITLE
Letsencrypt

### ISSUE THREAD

**Issue by Mixnetwork** [AzuraCast/AzuraCast#5697]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.17.3 Stable • Docker • PHP 8.1 

### What happened?

Wanted to add an ssl for certain domains, but does not work as described in your help document

### Relevant log output

```shell
I get the following message:
Lets Encrypt is now managed from within the web interface.
```

**Comment by ItsMitchh** [comment]
You need to manage let's encrypt from the admin area. This isn't a bug
