### ISSUE TITLE
How to use remote ssh for media file's 

### ISSUE THREAD

**Issue by serrebi** [AzuraCast/AzuraCast#5699]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

AzuraCast • Rolling Release #53080b1 (2022-08-23 4:36) • Docker • PHP 8.1

### What happened?

I try to setup a remote path for media under storage locations for a station, but it stays at local. How do I write the remote path? I've tried remote:/mnt/0b061a8f-d705-4673-813b-06f998a78d73/Media/Audio/Music/Genres and just the path but nothing seems to work! I've put in a key and the working info but it doesn't seem to connect to the location. Thanks in advanced for your help!

**Comment by devrob20** [comment]
looks like your trying to mount a remote USB drive ? do you know the filesystem for that drive ?

seems like your ssh user doesnt have access rights or the docker and/or host is unprivileged to bind and mount.
its also best to create a AzuraCast ssh user with its own home folder and mount the usb into that, then point that remote path.

on the remote host dont forget to set the usb mount in fstab, that way it automaticly remounts on reboots and it has the propper ACL rights. 

https://linuxconfig.org/howto-mount-usb-drive-in-linux


but SFTP has some issues, i can mount but the api still cant get to the .albumart and .wave so the backend playback and CUE is broken.

https://github.com/AzuraCast/AzuraCast/issues/5695
