### ISSUE TITLE
add playlist advanced allow requests option

### ISSUE THREAD

**Issue by Protomothis** [AzuraCast/AzuraCast#570]
could these things be possible?

**Current options**
- Allow Requests from This Playlist

**necessary things**
- request time range configuration.
ex ) A playlist -> 6am ~ 6pm request allowed

- number of requests allowed per song configuration.
ex ) A playlist -> request allowed 2 times per hour

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38907/specify-a-time-when-songs-can-be-requested-from-a-given-playlist
