### ISSUE TITLE
Disabled playlists still being played by AutoDJ

### ISSUE THREAD

**Issue by matthewunmuted** [AzuraCast/AzuraCast#5702]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #57c1163

### What happened?

We have a client who has disabled one of their playlists, however the AutoDJ is still playing media from this playlist even after restarting LiquidSoap, the broadcasting service, and reloading the station itself.

The skip song feature simply skips to the next track in this Disabled playlist. No other playlists will play.

**Comment by BusterNeece** [comment]
@matthewunmuted I just pushed an update up (I tagged the wrong GH issue on it, but still) that should also remove queue entries that are already in the Upcoming Song Queue but that are from playlists that are now disabled. I suspect that's what was happening in this case...the queue had already included the tracks from the disabled playlist and just kept them in, even after the status was switched.

**Comment by matthewunmuted** [comment]
Hi Buster,

Thanks for your prompt response and resolution - it does seem that this issue is now fixed for our client. I will bear in mind that clearing the playback queue could solve this in future. 

Thanks again.
