### ISSUE TITLE
Distorted sound on some devices

### ISSUE THREAD

**Issue by Hadhab** [AzuraCast/AzuraCast#5709]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #53080b1 (2022-08-23 4:36)

### What happened?

Stream playing distorted sound in some devices 

Steam link: http://qurum.ddns.net:8000/radio.mp3

**Comment by ItsMitchh** [comment]
Can you list the devices it can be distorted on? 

I've listened to this on an Android and Windows 10 machine, appears to be fine for me.

**Comment by Hadhab** [comment]
It plays distorted sound on iPhone and iPad and does not play any sound on my windows 11 laptop (Firefox browser)

**Comment by Hadhab** [comment]
Not sure if this would help, but I was trying from the same network where my server containing azura cast is

**Comment by Vaalyn** [comment]
The intro file you are using has a different audio format than the stream itself which is causing the audio decoders on client devices to either outright fail or to incorrectly playing the audio data.

Here is what Google Chrome reports:

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/13745863/188944368-11628067-9a9b-417d-98b5-12f03db08c9c.png">

As you can see it says it detected a mid-stream format change from mono to stereo.

Furthermore when I look at the codec details while playing the stream in VLC I can see that the intro file is a `mono` file with `192kbps` while the stream itself is `stereo` at `128kbps`.

To fix this issue you'll need to convert your intro file to the same settings that your stream is using, namely `stereo` and `128kbps`

### Intro
<img width="493" alt="image" src="https://user-images.githubusercontent.com/13745863/188944499-61783fb8-a3a0-49d6-9584-42e653bc6ba9.png">

### Stream
<img width="500" alt="image" src="https://user-images.githubusercontent.com/13745863/188944517-d19f017b-83ac-44c2-998b-76f965062eaa.png">

**Comment by Hadhab** [comment]
It is fixed now.... thank you
