### ISSUE TITLE
Uninstall script does not just uninstall azuracast

### ISSUE THREAD

**Issue by Xiodine** [AzuraCast/AzuraCast#571]
The ./docker.sh uninstall does not just uninstall azure as I assumed.

It just annihilated my email server, there is no reason for the script to be this destructive.

**Comment by SlvrEagle23** [comment]
@Xiodine My apologies for that...the Docker uninstaller was originally intended for local dev use, and indeed it does seem a little aggressive in what it removes. I'll work on revising it to ensure it only affects the AzuraCast docker containers and volumes.

**Comment by SlvrEagle23** [comment]
@Xiodine I've updated the Docker utility script to only remove AzuraCast containers and volumes by default, with instructions to remove all Docker containers and volumes if necessary, i.e. for dev purposes.

My apologies if this caused any significant data loss on your end. I've made sure to keep the warning message that appears before uninstalling intentionally broad, just in case.

**Comment by Xiodine** [comment]
The server had only been up for a couple of weeks following a migration, most of the data was restored from an archive.

Thanks for the prompt fix, I look forward to working with your software in the future (airtime is on its way out).
