### ISSUE TITLE
Failed Migration in 0.17.3 Stable - Syntax error or access violation: 1091 Can't DROP FOREIGN KEY

### ISSUE THREAD

**Issue by Maaano** [AzuraCast/AzuraCast#5725]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.3

### What happened?

Hello,
I just ran the last update of Azuracast with docker and I can't access to my dashboard and all the stations public pages anymore.
The stations are running, I can listen to them but not manage them with the dashboard on my IP adress.
It's like I have the back but not the front !
Any idea to get back my dashboard without restore my VPS ?

Many thanks

**Comment by ItsMitchh** [comment]
Can you check your docker logs and give some screenshots for us, this is fairly hard to look I to without them.

**Comment by erikmevis** [comment]
Hi, we have the same issue. We get a 502 bad gateway. Also-

In Connection.php line 72:

  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_2AD16164427EB8A5`; check that it exists

**Comment by erikmevis** [comment]
> Hi, we have the same issue. We get a 502 bad gateway. Also-
> 
> In Connection.php line 72:
> 
> SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_2AD16164427EB8A5`; check that it exists

[radio.easternhops-log update issue.txt](https://github.com/AzuraCast/AzuraCast/files/9539226/radio.easternhops-log.update.issue.txt)

**Comment by ItsMitchh** [comment]
thanks.

**Comment by BusterNeece** [comment]
We have created a new section in our troubleshooting documentation relating to failed database migrations, please see it for further instructions: https://docs.azuracast.com/en/user-guide/troubleshooting#failed-database-migrations
