### ISSUE TITLE
Custom fields not displayed in Export Media to CSV

### ISSUE THREAD

**Issue by paulcjkp** [AzuraCast/AzuraCast#5727]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#53080b1 (2022-08-23 4:36)

### What happened?

Trying to use the Bulk Media Import/Export, but none of the custom fields are filled in, other than Year.  Also, only one playlist is displayed (the one assigned to the media folder).

I have also noticed that when downloading a file, none of the custom fields are assigned to the MP3 either, despite using the proper ID3v2 values.  These fields will upload and fill in properly, but it seems like saving will overwrite the ID3v2 field, leaving it blank.  

### Relevant log output

```shell
id,path,title,artist,album,genre,lyrics,isrc,amplify,fade_overlap,fade_in,fade_out,cue_in,cue_out,playlists,custom_field_year,custom_field_track_no,custom_field_label,custom_field_composer,custom_field_buy_link,custom_field_country,custom_field_comment,custom_field_p_line,custom_field_Catalog

e6f524dd8dbd9b9342e61710,"Music/Main/A/05_-_a_perfect_circle_-_so_long,_and_thanks_for_all_the_fish.mp3","So Long, and Thanks for All the Fish","A Perfect Circle","Eat the Elephant","Progressive Rock","",QMRSZ1800114,,,,,,261.5,Everything,2018,,,,,,,,
```

**Comment by BusterNeece** [comment]
@paulcjkp Should be fixed in Rolling Release. Was caused by an erroneous GROUP BY in the SQL query for the bulk export.
