### ISSUE TITLE
'Station Offline' on Public Page & On The Air box in Station Profile

### ISSUE THREAD

**Issue by matthewunmuted** [AzuraCast/AzuraCast#5730]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #57c1163

### What happened?

A number of our clients on our Ascella server are reporting that even though their station is broadcasting either live or from the AutoDJ, their public page and 'On The Air' box in the Profile page reports that their station is offline.

We have restarted the Broadcasting and AutoDJ services on these stations, as well as reloading the entire station through making changes, and restarted AzuraCast via SSH. This issue persists.

Any advice or help would be very welcome.

**Comment by ItsMitchh** [comment]
Good morning,

When these issue persists can you check your liquidsoap logs and docker ones respectively.

**Comment by ItsMitchh** [comment]
Good morning,

When these issue persists can you check your liquidsoap logs and docker ones respectively.

**Comment by matthewunmuted** [comment]
Hi Mitch,

When the issue occurs again I will grab the entire liquidsoap/docker log and paste it here

Thank you

**Comment by ItsMitchh** [comment]
Thanks! If the log is too big, please use gist to save our eyes :)
