### ISSUE TITLE
Increase data size

### ISSUE THREAD

**Issue by afsound** [AzuraCast/AzuraCast#574]
- **Installation Method:** 
- **Host OS (if using Docker):** 

**Describe the issue in full detail, including screenshots if possible:**

Where do i increase the space for autodj? from 6gb to 20gb?

Also, i cant see the var/azuracast/www/station/name media files...where they are stored?

**Comment by SlvrEagle23** [comment]
@afsound You didn't specify (please always follow our issue template), but I'm assuming that you're running the Docker installation. If you're running the Traditional installation, the music files will just be directly accessible via `/var/azuracast/stations/...`.

For Docker, the files are stored inside what's called a Docker Volume, which is a set of disk space that Docker manages. If you type `docker-compose run --rm cli`, you can get launched into a shell where you can view and manage the volume's files.

If you need to manage them in bulk via, say, SFTP, you can follow [these instructions](https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#access-files-via-sftp-docker-installations).

**Comment by GaetanSsfm** [comment]
Hello,

I'm also running out of space, running with PROXMOX, i've added 200 more gb but in azura, I see total space disk 51gb ... how to increase ? 

I don't found any command on the internet :/
