### ISSUE TITLE
"Only play one track" playlists stopped playing.

### ISSUE THREAD

**Issue by paulcjkp** [AzuraCast/AzuraCast#5752]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#c9e8a76 (2022-09-11 8:39)

### What happened?

Since updating (from rolling release #53080b1), any playlists that have "Only play one track at scheduled time" checked, and are scheduled, do not play.  If they are set to one track every x minutes, but not scheduled, it plays fine.  These playlists are being played overtop of another scheduled playlist, but the regular playlist has a weight of 5, vs the play one track weight of 25.  

I checked both the Azuracast application logs, and Liquidsoap logs, but no errors appear.  It's just as if these playlists are being ignored completely.

**Comment by paulcjkp** [comment]
Got some error logs now, while an 2 hour long show should be in the queue.  Start time 6:57, but at 6:57 there is currently a song playing, nothing in the queue.  6:58, still not queued up.  7:01, song ends, no show in the queue, and the station goes offline.

`[2022-10-08T22:53:39.672292+00:00] AzuraCast.ERROR: No playable tracks were found. [] {"station":{"id":1,"name":"CJKP-DB Alt Rock Radio"}}
[2022-10-08T22:57:32.472287+00:00] AzuraCast.ERROR: Error with Internal Command NextSongCommand: Queue is empty for station. {"exception":"[object] (RuntimeException(code: 0): Queue is empty for station. at /var/azuracast/www/src/Radio/AutoDJ/Annotations.php:50)"} {"station":{"id":1,"name":"CJKP-DB Alt Rock Radio"}}
`

I believe this might be caused by issue #5499, possibly?  "This update adds that check and will remove any queue entries that fall out of their scheduled time slot while waiting to be cued/played."  Especially for our jingles playlist, where start and end times are the same, would this not remove them from the queue, the instant they are added?

**Comment by paulcjkp** [comment]
Updated to the latest rolling release, still dealing with this issue.  Any help would be appreciated, thanks.

**Comment by paulcjkp** [comment]
Would it be possible to add some kind of check to the queue?  If autoDJ is on, then don't check the queue, but if we're live, then yes?  I understand the need to want to clear the queue during a live show, but it shouldn't be affecting our jingles or podcasts.

**Comment by paulcjkp** [comment]
Just giving a bit more info, this is one of the playlists we are having issues with.  General rotation, scheduled to queue near the end of our autoDJ, with a bit of overlap.

![az_playlist1](https://user-images.githubusercontent.com/68815082/209252584-8ea954af-a106-454b-bf1a-d756fb9e1e57.png)
![az_playlist2](https://user-images.githubusercontent.com/68815082/209252595-2c36000e-c94c-422f-86d1-af93a5270360.png)
![az_playlist3](https://user-images.githubusercontent.com/68815082/209252609-71a54e2d-4b41-4970-8b76-b854a04b0b90.png)
![az_playlist4](https://user-images.githubusercontent.com/68815082/209252622-e807df16-1664-4711-81dd-1429ab23c1a4.png)

**Comment by BusterNeece** [comment]
@paulcjkp We had another report explaining what we were doing wrong here in terms of Liquidsoap configuration, so this issue may be fixed as of the latest Rolling Release version.
