### ISSUE TITLE
I can't play the radio from public page, request access

### ISSUE THREAD

**Issue by AlbEagle** [AzuraCast/AzuraCast#5756]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #4bf668e (2022-09-18 2:47)

### What happened?

Hello, i have create radio, and update mp3 and i want to play i request access user pass>

Please help!  [https://i.imgur.com/scZiGuJ.jpg](https://i.imgur.com/scZiGuJ.jpg)

Please help!

**Comment by paulcjkp** [comment]
Make sure to enable public pages (Edit Profile>Profile>Enable Public Pages).  Otherwise, this may be due to Icecast blocking your country/IP (Edit Profile>Broadcasting>Banned IP Addresses, Banned Countries).
