### ISSUE TITLE
a playlist more than once a day

### ISSUE THREAD

**Issue by dreinn** [AzuraCast/AzuraCast#576]
Hello,
please tell me if I am wrong.
It is not possible to have a playlist that plays more than once a day. For example, I have a playlist called modernMusic. 
On my old radio, it was configured from 9 am to 11 am, then from 15 to 16 and  from 18 to 19 pm, all days.
Other example, I have a podcast that plays tuesday and thursday at 21, saturday and sunday at 16.
Can we have a more flexible time settings for the playlists?
For now the unique solution I see is creating many playlists with the same files!

Thank you!

**Comment by SlvrEagle23** [comment]
@dreinn Currently, you are correct. There is a fair amount of work going into overhauling playlists, so I'll take your request into consideration when working on it!

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38780/allow-multiple-schedule-entries-for-a-single-playlist
