### ISSUE TITLE
Stereo tool integration with 

### ISSUE THREAD

**Issue by master-magic** [AzuraCast/AzuraCast#5760]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

Rolling Release #4bf668e (2022-09-18 2:47) • Docker • PHP 8.1 

### What happened?

i have a question about stereo tool, I use this with a license, and have put a .sts file in that I make but when I upload and use stereo tool option I don't here the difference with the standard sound when I listen to it.
the line down here I have in my installation, is this the good one so I use stereo tool live or have I need to change that?????
thanks in advance for the help in this.

I like the azuracast and use it for 2 years almost with great pleasure.
the stereo tool option would make it perfect.

I try also other .sts file's what I found on the forum of stereo tool but won't change anything on the sound.
license is also active for stereo tool. (fm basic license)

**Comment by ckeurk** [comment]
Does not use code

**Comment by master-magic** [comment]
@ckeurk  is removed ;)
