### ISSUE TITLE
Character limit for the 'Song Album' field

### ISSUE THREAD

**Issue by matthewunmuted** [AzuraCast/AzuraCast#5761]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #5ab3cf9

### What happened?

Hi there,

We have a client hosted on one of our shared servers that is asking us if it is possible to increase the character limit for the 'Song Album' field in the 'Edit Media' dialog.

They wish to have it increased from 200 to 500.

Is this something that we are able to do? 

Many thanks in advance.

**Comment by BusterNeece** [comment]
@matthewunmuted I believe Custom Fields have no assigned character limit, so you can take advantage of those to solve this particular problem.

**Comment by matthewunmuted** [comment]
Hi Buster,

Thank you very much for your response - I will add a custom field for this specific client.

All the best.

**Comment by matthewunmuted** [comment]
Hi again,

Please see the response from our client - is it possible to have this custom field feed into the original Song Album field in the Edit Media dialog?

------------------------------------------------------------

Hi there i can see the extra fields which is great, The reason we were using the "Album" field is that we can embed our info in to the actual MP3 file so if played locally or from server all the information is there. So we can access the same information in the same way.
The Mp3 file has the character capacity, but when imported in to Azura Cast it truncates to 200 characters and misses and deletes information past 200 characters.
We would need the extra field to feed in to the "Album" line or export Mp3 with a similar additional field that can be picked up in another program.
Does this make sense?

**Comment by BusterNeece** [comment]
@matthewunmuted It does make sense, but if we enlarge that field, it means that every single song record will take up potentially more space in the database, just for this edge case scenario. We set those limits quite high already versus what is normally used (less than 50 characters), but we have to trade-off performance and space usage versus functionality.

Custom fields can also automatically be set to the value of a field via their configuration.

**Comment by matthewunmuted** [comment]
Hi Buster,

Thanks for your explanation and clarification on this matter, I really do appreciate it. I will relay this back to the client and ensure their custom fields are set to ID3 tag values. All the best.
