### ISSUE TITLE
Telnet failure: No such file or directory (2)

### ISSUE THREAD

**Issue by matthewunmuted** [AzuraCast/AzuraCast#5764]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.16.1 Stable

### What happened?

Hi there, hope you're well.

One of our client stations is having numerous issues with LiquidSoap - most notably, when attempting to Skip Song, we recieve this error: 

Exception at /var/azuracast/www/src/Radio/Backend/Liquidsoap.php L175: Telnet failure: No such file or directory (2)

The AutoDJ service can be successfully started in the Profile page, however it stops roughly one minute later no matter what.

In the 'On The Air' box, 'Now Playing - Stream Offline' is shown, however under 'Playing Next', this is shown:

Jingle 2
Rhyl Radio
Playlist: Jingles

I have re-loaded the station, checked the mount point configuration, restarted the docker containers and our server, with no luck.

Any advice would be welcome.

### Relevant log output

```shell
Exception at /var/azuracast/www/src/Radio/Backend/Liquidsoap.php L175: Telnet failure: No such file or directory (2)
```

**Comment by matthewunmuted** [comment]
This error repeats over and over in the LiquidSoap log:


Error 5: this value has type
  _ * source(audio=?A, video=?B, midi=?C)
  .{
    time : () -> float,
    fallible : bool,
    skip : () -> unit,
    seek : (float) -> float,
    is_active : () -> bool,
    is_up : () -> bool,
    log : 
    {level : (() -> int?).{set : ((int) -> unit)}
    },
    self_sync : () -> bool,
    duration : () -> float,
    elapsed : () -> float,
    remaining : () -> float,
    on_track : ((([string * string]) -> unit)) -> unit,
    on_leave : ((() -> unit)) -> unit,
    on_get_ready : ((() -> unit)) -> unit,
    on_shutdown : ((() -> unit)) -> unit,
    on_metadata : ((([string * string]) -> unit)) -> unit,
    last_metadata : () -> [string * string]?,
    is_ready : () -> bool,
    id : () -> string,
    current : () -> request?,
    set_queue : ([request]) -> unit,
    add : (request) -> bool,
    queue : () -> [request],
    fetch : () -> bool,
    reload : (?uri : string?) -> unit,
    length : (() -> int)
  }
but it should be a subtype of the type of the value at /var/azuracast/stations/marinebeachhut/config/liquidsoap.liq, line 149, char 88-103
  _ * _.{selected : _}

**Comment by matthewunmuted** [comment]
This error from the ShoutCast log:

22-10-04 14:57:31	WARN	[CONFIG] Invalid item on line 13 of /var/azuracast/stations/marinebeachhut/config/sc_serv.conf -> `licenceid'
[0m[01;33m2022-10-04 14:57:31	WARN	[CONFIG] Invalid item on line 14 of /var/azuracast/stations/marinebeachhut/config/sc_serv.conf -> `userid'
[0m[01;33m2022-10-04 14:57:31	WARN	[CONFIG] Invalid item on line 15 of /var/azuracast/stations/marinebeachhut/config/sc_serv.conf -> `sslcertificatefile'
[0m[01;33m2022-10-04 14:57:31	WARN	[CONFIG] Invalid item on line 16 of /var/azuracast/stations/marinebeachhut/config/sc_serv.conf -> `sslcertificatekeyfile'

**Comment by BusterNeece** [comment]
@matthewunmuted 0.16.1 is quite outdated at this point...I'm not sure what's causing this particular error in any case, though. :/

**Comment by RandomGreymane** [comment]
We are also experiencing this error with the Skip.  Install a Stable release from the install pages.

From the Azuracast log:

[2023-02-03T05:17:09.598494+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":0,"workerName":"app_worker_0"} []
[2023-02-03T05:17:09.728239+00:00] AzuraCast.ERROR: Telnet failure: No such file or directory (2) {"file":"/var/azuracast/www/src/Radio/Backend/Liquidsoap.php","line":83,"code":0,"context":[]} []
[2023-02-03T05:22:13.714914+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":0,"workerName":"app_worker_0"} []

We're using Icecast2 not Shoutcast.  This is the only thing in the Icecast Error Log:

[2023-02-03  01:36:31] WARN slave/slave_startup process has 65536 max file descriptor limit

So nothing around the related time.

Everything else seems to work except Skip Track.
