### ISSUE TITLE
FW blocking

### ISSUE THREAD

**Issue by slacombe5** [AzuraCast/AzuraCast#577]
Traditional - Ubuntu 16.04
Install script.

The script turns firewall on abnd i loose the SSH on the server. It doesn't respond too web too.

Regards.

**Comment by slacombe5** [comment]
This problem occurs with hosting "scaleway" not on hosting OVH.

**Comment by SlvrEagle23** [comment]
Closing as this appears to be a problem imposed by the hosting provider, rather than any sort of misconfiguration on AzuraCast's part.
