### ISSUE TITLE
Email delivery service not working

### ISSUE THREAD

**Issue by uthingo** [AzuraCast/AzuraCast#5775]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

The email delivery service is not working. I tried to send a test email after adding smtp credentials. I first added my own private smtp and later I added Sendgrid smtp credentials but the response was the same , I couldn't receive the test email.

![azuracast](https://user-images.githubusercontent.com/99258154/194704583-ad60367a-33ec-4e27-bbe3-990bef302728.PNG)

**Comment by colorpride** [comment]
usually enabled for port 465, disabled for port 587 or 25

**Comment by uthingo** [comment]
WebDJ streamer was not working, I tested it the whole of yesterday.

**Comment by scysys** [comment]
Same here. Not working with 587 or 465. Using Amazon SES (Ansible)

**Comment by scysys** [comment]
You can ignore this issue here. Amazon SES is definitly working when not using the ansible installation.
