### ISSUE TITLE
Ip diferente al server

### ISSUE THREAD

**Issue by DannySolucions** [AzuraCast/AzuraCast#5777]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.3

### What happened?

Good evening, at the moment of installing azuracast to carry out the live transmission, I have another IP different from the one I have with the server, I tried several times but I still have the problem, I have also installed the ssl and domain but the port continues to appear, please with 
![ip diferente](https://user-images.githubusercontent.com/115383468/194736012-491ead42-1176-46fb-98f4-0558dfe1486a.PNG)
![ip server](https://user-images.githubusercontent.com/115383468/194736014-f923e9f9-7519-4f4f-aa52-fe6fe1aa5f7b.PNG)
your help

**Comment by ajeje989** [comment]
i have same error .. how to fix ? i have internal ip docker not public ip ..

**Comment by BusterNeece** [comment]
This was a bug in our Central update server and has now been fixed; I'd recommend updating just to flush your IP address and reset it to the correct one.
