### ISSUE TITLE
Slim Application Error  A website error has occurred. Sorry for the temporary inconvenience.

### ISSUE THREAD

**Issue by hitzgh** [AzuraCast/AzuraCast#5779]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

Rolling Release #39c0372 (2022-10-09 2:24) 

### What happened?

hello, i just installed azuacast on ubuntu 22.04 after successful setup i want to setting to upload shoutcast but i encountered this error

Slim Application Error

A website error has occurred. Sorry for the temporary inconvenience.
[Go Back](https://cast.hitzgh.com/admin/install/shoutcast#)

any help on this issue

**Comment by BusterNeece** [comment]
@hitzgh Do you see the error in the system logs? We need additional logs to be able to diagnose the issue.

**Comment by hitzgh** [comment]
@BusterNeece i am still new in ssh, can you show me how i can fetch you the logs

**Comment by BusterNeece** [comment]
@hitzgh `docker-compose logs -f` in the `/var/azuracast` directory, then revisit the page and see what appears.

**Comment by hitzgh** [comment]
@BusterNeece i think i see the cause, shout cast cannot be installed on my system 


azuracast  | [2022-10-10T00:03:04.536815+00:00] AzuraCast.WARNING: ACME Failed: Certificate does not need renewal. {"exception":"[object] (RuntimeException(code: 0): Certificate does not need renewal. at /var/azuracast/www/src/Service/Acme.php:131)"} {"task":"RenewAcmeCertTask"}
azuracast  | [2022-10-10T00:03:14.818025+00:00] AzuraCast.ERROR: Shoutcast cannot be installed on non-X86_64 systems. {"file":"/var/azuracast/www/src/Controller/Admin/ShoutcastAction.php","line":19,"code":0} []

**Comment by hitzgh** [comment]
@BusterNeece is there anyway to bypass or fix this

**Comment by BusterNeece** [comment]
@hitzgh The error is exactly as it says, you can't use Shoutcast on ARM-based machines. You'd need to switch to an X86-based machine or use Icecast.

**Comment by hitzgh** [comment]
@BusterNeece ok thanks, can I have your email for dm
