### ISSUE TITLE
After Install issue

### ISSUE THREAD

**Issue by unclechippah** [AzuraCast/AzuraCast#578]
- **Installation Method:**  Docker
- **Host OS (if using Docker):**  CentOS 7

**Describe the issue in full detail, including screenshots if possible:**

After install I can access the admin area however its all messed up. No artwork just white background and a menu tree. It seems like there is a step missing in the install from the last version.
![ac error 05012018](https://user-images.githubusercontent.com/19339536/39470119-7d3955ca-4d01-11e8-8723-53a87c51eafd.jpg)

**Comment by SlvrEagle23** [comment]
@unclechippah Did you customize your `docker-compose.yml` file at all? This seems to suggest that the nginx service isn't loading the static files from the web directory correctly, while the PHP service is still running fine. It may be as simple as `docker-compose restart nginx` if you haven't changed anything.

**Comment by unclechippah** [comment]
I have reinstalled CentOS 7 and when installing I get to chmod a+x docker.sh and it says no such file found. 
I have had this up and running on another server with no issues. Now I cannot even get it to install following the commands you have for docker installation.

**Comment by SlvrEagle23** [comment]
@unclechippah The `docker.sh` file is just the one at the root of this Github repository; if the little copy/paste script to download it fails, you can always just manually fetch it (or use wget or curl or anything else) and drop it into a folder.

Once the utility script is in the right place, and `chmod a+x docker.sh` is run, it should be able to complete the rest of the installation without any issues.

**Comment by SlvrEagle23** [comment]
Closing this issue as I haven't heard any further updates in the last few months.

If you see an AzuraCast page where the HTML loads but the content is unstyled and/or missing dynamic functionality, and you're running Docker, make sure that the `nginx` service inside `docker-compose.yml` has the same thing mounted into the `/var/azuracast/www` directory as the `web` service does; for normal installations, this will be a volume called `www_data`.
