### ISSUE TITLE
Encoding but default shhhhhhh Sound

### ISSUE THREAD

**Issue by hitzgh** [AzuraCast/AzuraCast#5780]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

Rolling Release #39c0372 (2022-10-09 2:24) • Docker • PHP 8.1

### What happened?

the encoder is encoding alright but the output sound is the shhhhhhhh sound i do not know why

**Comment by adoboligh1** [comment]
Means there is no audio file playing.

**Comment by hitzgh** [comment]
@adoboligh1 it is encoded alright in my software "samcast" and audio meter is peaking

**Comment by adoboligh1** [comment]
Are you pushing audio?

**Comment by hitzgh** [comment]
@BusterNeece kindly check this issue, when using shoutcast it works alright but with icecast; it will be encoding alright but still the shhhh sound

**Comment by renatopinto89** [comment]
> @BusterNeece kindly check this issue, when using shoutcast it works alright but with icecast; it will be encoding alright but still the shhhh sound

You have to make sure you´re broadcasting to the correct mount point ("/radio" by Default), setting to only "/" won´t actually stream anything and the white noise will continue.
![icecast mount](https://user-images.githubusercontent.com/83221826/196558848-f6ac076f-6300-489e-9473-8b689d2fe21e.png)

**Comment by hitzgh** [comment]
@BusterNeece thank you very much, i didnt know the mount point was important in icecast, fully working now!

**Comment by ItsMitchh** [comment]
Closed, reportedly fixed.
