### ISSUE TITLE
Unable to install AzuraCast on fresh Ubuntu 20.04 Server

### ISSUE THREAD

**Issue by ChristopherG05** [AzuraCast/AzuraCast#5781]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

I followed the installation instructions as given on the website, the installation goes well until the script tries creating/starting the azuracast container which fails with `Error response from daemon: driver failed programming external connectivity on endpoint azuracast (89d499109481c2c0370706bae60373b090dfe7931577afc1c24c86f5adf69a74): fork/exec /usr/bin/docker-proxy: resource temporarily unavailable`
I already tried using different ports and a complete fresh reinstallation of Ubuntu Server 20.04 as well as a docker reinstallation, but this did not fix the issue either.
Edit: It's a Strato VServer - I read that other people had problems with running AzuraCast on those servers in the past...

**Comment by DannySolucions** [comment]
One question, do you have a domain hosted? In my case it worked for me and hosting the ssl so that the other person can enter the link that I assigned
