### ISSUE TITLE
Your credentials could not be verified

### ISSUE THREAD

**Issue by izobretatel88** [AzuraCast/AzuraCast#5784]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

AzuraCast 0.15.0 

### What happened?

The password does not work if it is updated through AzuraCast management and then notifies you that "Your credentials could not be verified."

`docker-compose run --rm cli azuracast_cli azuracast:account:reset-password your-email-address@example.com`

When I apply the command I get "no configuration file provided: not found"

adoboligh1 have said "Do you have STMP setup?
If not it means you can't use this method."

How to setup SMTP?

AzuraCast 0.15.0 on Ubuntu 20.04

**Comment by ItsMitchh** [comment]
Hello, this version is incredibly old. Can you update and see if the problem persists?

**Comment by izobretatel88** [comment]
Hello)

Thanks for your response!

I has updated to v0.17.3 Stable and the problem is actual.

**Comment by izobretatel88** [comment]
It happened when I wanted to create another station and a new user and give him rights to a new station.

**Comment by Vaalyn** [comment]
To preface this, I'd recommend you to use `./docker.sh cli` to run commands.

The command to reset a password generally works (also tested it with email delivery disabled), in both cases it will print a new temporary password in the console. There is no email component involved when resetting a PW from the CLI.

Make sure you are actually inside of the azuracast directory (in most cases this is `/var/azuracast`).
You can switch to that directory via:
```
cd /var/azuracast
```

**Comment by izobretatel88** [comment]
![image](https://user-images.githubusercontent.com/3668578/195606226-b3a171b4-a664-4944-a213-8fcb42c2563d.png)

@Vaalyn thanks, I used your recommendation, the system send me "no such service: cli" you may check it on screenshot above.

**Comment by Vaalyn** [comment]
@izobretatel88 as I said in my post, switch to using `./docker.sh cli` instead of `docker-compose run --rm cli`

**Comment by izobretatel88** [comment]
Ok, I got it)

> PS I'm in a bit of a hurry here

**Comment by izobretatel88** [comment]
The problem is solved! Thanks!
