### ISSUE TITLE
Central update service return Docker network IP address instead of external IP for an AzuraCast installation

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#5785]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

0.17.3 #39c0372cfb9dd4ffbd21d1c2dc7cfff74c596330

### What happened?

The IP that the AzuraCast central update service returns when an AzuraCast installation asks it for the external IP of the installation is from an internal Docker network instead.

@BusterNeece  This seems related to the recent hosting provider switch for our services & sites

You can reproduce this easily by sending a GET request to https://central.azuracast.com/ip which will result in the IP `172.19.8.81`

This causes AzuraCast installations to show this wrong IP address for example on the Streamers page in the connection details.

**Comment by BusterNeece** [comment]
Fixed!
