### ISSUE TITLE
Album artwork not showing

### ISSUE THREAD

**Issue by matthewunmuted** [AzuraCast/AzuraCast#5797]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.1 Stable

### What happened?

One of our client's album artwork is not showing for their uploaded media - only the default AzuraCast artwork will show for all media, where the correct artwork shows on their PC locally and in media players.

**Comment by BusterNeece** [comment]
@matthewunmuted We found and fixed an issue with Ogg Vorbis and some other containerized music files pulling metadata and album art, that may be what's causing this. It's fixed in rolling. Expect a new stable release soon.

**Comment by matthewunmuted** [comment]
Hi Buster,

Many thanks for the extremely prompt response. I appreciate your time.
