### ISSUE TITLE
ERROR IN UPDATE

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#580]
- **Installation Method:** Traditional
- **Host OS (if using Docker):** Ubuntu 16.04

I just updated my traditional installation of Azuracast but error is encountered at the end of update here is the error.

TASK [azuracast-update : Restart Radio Stations] ***********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php azuracast:radio:restart", "delta": "0:00:02.381960", "end": "2018-05-06 13:02:40.988056", "msg": "non-zero return code", "rc": 255, "start": "2018-05-06 13:02:38.606096", "stderr": "", "stderr_lines": [], "stdout": "Restarting all radio stations...\nRestarting station #2: Bliss Radio", "stdout_lines": ["Restarting all radio stations...", "Restarting station #2: Bliss Radio"]}

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=18   changed=7    unreachable=0    failed=1

but i tried to restart the radio manually inside the panel it works any idea where is the problem?

**Comment by SlvrEagle23** [comment]
@reans For some reason, it considered a totally normal response to be an unsuccessful one. The messages there indicate that everything actually went just fine, and it still considered it a fail for some reason.

I've updated the CLI scripts to ensure they "officially" send the proper 0 response code to indicate a successful run. Try it now and let me know if it helps.

**Comment by reans** [comment]
@SlvrEagle23 sir i've just updated right now but still the error at end of update and need to start the station from the panel manually after update inorder to back streaming.

TASK [azuracast-update : Restart Radio Stations] ***********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php azuracast:radio:restart", "delta": "0:00:00.619761", "end": "2018-05-07 10:38:17.289974", "msg": "non-zero return code", "rc": 255, "start": "2018-05-07 10:38:16.670213", "stderr": "", "stderr_lines": [], "stdout": "Restarting all radio stations...\nRestarting station #2: Bliss Radio", "stdout_lines": ["Restarting all radio stations...", "Restarting station #2: Bliss Radio"]}

RUNNING HANDLER [azuracast-cron : restart cron] ************************************************************************************************************************

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=75   changed=23   unreachable=0    failed=1

**Comment by SlvrEagle23** [comment]
@reans What happens if you manually run:

```
php /var/azuracast/www/util/cli.php azuracast:radio:restart
```

**Comment by reans** [comment]
this is the output

root@azuracast5:/var/azuracast/www# php /var/azuracast/www/util/cli.php azuracast:radio:restart
Restarting all radio stations...
Restarting station #2: Bliss Radio
root@azucast5:/var/azuracast/www#

but in the stream still not running. need to login in the panel and start 
![image](https://user-images.githubusercontent.com/27730047/39730333-927f655e-5293-11e8-86ee-ce2fe69840b7.png)

![image](https://user-images.githubusercontent.com/27730047/39730346-a73dcc88-5293-11e8-8364-fb1c54376d0a.png)

that 2 services manually and if that started the DJ also connect connect using their streamer account.

**Comment by ckeurk** [comment]
I have the same problem
`fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php azuracast:radio:restart", "delta": "0:00:04.206613", "end": "2018-05-19 08:09:18.145691", "msg": "non-zero return code", "rc": 255, "start": "2018-05-19 08:09:13.939078", "stderr": "", "stderr_lines": [], "stdout": "Restarting all radio stations...\nRestarting station #1: Radio Deep Underground", "stdout_lines": ["Restarting all radio stations...", "Restarting station #1: Radio Deep Underground"]}
`

**Comment by ckeurk** [comment]
Since the last little update, everything works fine for me thanks
