### ISSUE TITLE
AzuraCast not connecting with SAM Broadcaster

### ISSUE THREAD

**Issue by ahadaman757** [AzuraCast/AzuraCast#5819]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

Hi, at first I was able to connect to SAM Broadcaster via the source password but it wasn't really reliable because I am looking to provide people their our dj/rj credentials to login. So I installed the Shoutcast on my AzuraCast and changed the station broadcasting to Shout cast and when I used the credentials like user:password it still isn't working and giving me errors like Disconnected (10060)

**Comment by PaulMaur** [comment]
All old versions of SAM Broadcaster  no longer work You need the latest version of SAM Broadcaster

**Comment by LordHelmchen666** [comment]
Try `user,password` this works with Sam 4.9.8
