### ISSUE TITLE
Media files page keeps loading

### ISSUE THREAD

**Issue by netbladenl** [AzuraCast/AzuraCast#5825]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#5d399d6

### What happened?

Since the last update I cannot see any of the music files under the mediafiles tab.
It keeps loading and never shows all the media files.

The station is playing as it should and the public requestpage is working aswell.

I've tested this with 2 different servers and booth have the same issue, also tested with different browsers (ff, edge, chrome)

### Relevant log output

```shell
I could not find any logs that tells me what is causing this.
```

**Comment by novsal** [comment]
Yes same us with me
![bug](https://user-images.githubusercontent.com/53934647/199585382-ec3b0827-ea97-4e8b-bf87-53ec8281bf02.JPG)

**Comment by BusterNeece** [comment]
Sorry folks, this was a regression introduced in our 12/24 hour time format change. A fix is currently deploying; you can update in about 5-10 minutes.
