### ISSUE TITLE
Icecast2 config - ability to add more than 3 mountpoints per station

### ISSUE THREAD

**Issue by aripisprecer** [AzuraCast/AzuraCast#583]
- **Installation Method:** Traditional (LXC Container)
- **Host OS (if using Docker):** Ubuntu 16.04

**Describe the issue in full detail, including screenshots if possible:**

Hello,

i have created one icecast2 station with 9 mountpoints.
Unfortunately, i cannot add more than three mount points to icecast2 using azuracast. If i change the config manually and after that, i restart the icecast server from azura cast, it will restore the value back to the original one which is 3 sources.

Example:
<limits>
        <clients>1000</clients>
        <sources>9</sources>

Default value is 3.

Please add the ability to change this value from azuracast and to make it persistent.

Thank you,
Marius

**Comment by SlvrEagle23** [comment]
@aripisprecer Can you clarify what you mean by your example values (1000 and 9)? I don't understand the context of those.

There's no hard limit inside the Liquidsoap configuration that would lock Icecast down to only having 3 mount points.

Are you referring to custom configuration of Icecast itself? You can specify that inside the station's profile, under "Advanced: Custom Configuration", in order to ensure it persists across reloads.

**Comment by aripisprecer** [comment]
@SlvrEagle23 

I am sorry, it seems github removed some details from my post.

so, for example:

i have the station1 which is using icecast2.

The station config is under:

`/var/azuracast/stations/station1/config/icecast.xml`

in icecast.xml there is a parameter called sources:

` <limits>
        <clients>1000</clients>
        `<sources>9</sources>`

The default value for sources is 3, but i want to add more than 3 sources.

In azuracast dashboard, i click on "manage" under station1, than i click on mount points and i add more than 3 mount points. After that i click on "apply configuration" and restart the broadcasting service.

Only 3 mount points will be aviable.

I have tried to add `<sources>9</sources>` in the Advanced: Custom Configuration field in Azuracast but the problem is that this parameter is added at the end of the config file and it has no effect, because it has to be changed at the begining of the config file.

**Comment by SlvrEagle23** [comment]
@aripisprecer You have to add the full path of the XML you want to add, like:

```xml
<limits><sources>9</sources></limits>
```

That should override the existing configuration default.

**Comment by aripisprecer** [comment]
@SlvrEagle23 

You've right, it worked like this, and i think the next issue with shoutcast has the same solution.

I used shoutcast and icecast for years, installed directly on linux, but i decided to try Azuracast.
I have to say that it is a good open source software and you are doing a very good job.

Thank you,
Marius

**Comment by SlvrEagle23** [comment]
@aripisprecer Happy to help, and thank you! I hope AzuraCast continues to be useful to you for your stations. :)
