### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by giovanni256** [AzuraCast/AzuraCast#5832]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

0.17.4

### What happened?

Hi there.
This topic is a duplicate for issue #5808 to give it more visiblity since it is closed.

During the update from 0.16 to 0.17.4, the update fails with the error log below.
This occurs in Rolling Release channel and also in Stable Channel.

Log here
https://pastebin.com/wGdvS67v

I'm also getting this first:

** Running startup script '/etc/my_init.d/05_setup_db.sh'...
2022-11-05 22:56:56+00:00 [Note] [Entrypoint]: Initial DB setup...
2022-11-05 22:56:57+00:00 [ERROR] [Entrypoint]: mariadbd failed while attempting to check config
        command was: mysqld --verbose --help --log-bin-index=/tmp/tmp.a2J2x1pFSa
        Can't initialize timers
** Startup script complete.

**Comment by balmasedano** [comment]
I got an error on the last updates too. I resolved it making a new installation from zero and restoring backup, but in my case was an InnoDB error.

**Comment by BusterNeece** [comment]
@giovanni256 This is likely actually a different issue than the one reported in the other thread.

From my research, upgrading Docker itself should resolve this issue. You can do that via our utility script by running:

```bash
./docker.sh install-docker
```

**Comment by giovanni256** [comment]
> @giovanni256 This is likely actually a different issue than the one reported in the other thread.
> 
> From my research, upgrading Docker itself should resolve this issue. You can do that via our utility script by running:
> 
> ```shell
> ./docker.sh install-docker
> ```

Thanks, but will it cancel all my data?

**Comment by BusterNeece** [comment]
@giovanni256 It should certainly not do that, but I'd always recommend backing up just in case at the server/VPS host level if you can.

**Comment by giovanni256** [comment]
> @giovanni256 It should certainly not do that, but I'd always recommend backing up just in case at the server/VPS host level if you can.

Thank you so much!!
