### ISSUE TITLE
WSL All Listeners showing Internal IP Address

### ISSUE THREAD

**Issue by DGdB** [AzuraCast/AzuraCast#5846]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.4 Stable

### What happened?

Running using Ubuntu 20.04 WSL2 installed completely as per the documentation just yesterday.

All listener IP address' are showing up as 172.21.0.1, presumably due to the NAT done by WSL. I can't seem find a way to retain the original IP address.

I found an old issue with similar symptoms relating to Docker (https://github.com/AzuraCast/AzuraCast/issues/3108) but it sounds like this has been fixed and I'm sure it is a different issue.

Happy to do any testing to try and work this out, I'm just not sure where to go from here. This data is very important to us for reporting and also country filtering... Hoping someone can point me in the right direction and we can solve this for all WSL users.

Cheers
![image](https://user-images.githubusercontent.com/4328436/201196243-9d9be18f-c2ee-46dd-b620-4454e0efba63.png)

**Comment by dzsam** [comment]
I installed azuracast on a virtual disk, with virtual box.
I have the same problem with the ip addresses of the listeners
Only the virtual address is displayed for each connected listener
Kind regards

**Comment by diarieslive** [comment]
Hi All,
Same issues with WSL2 and v0.17.6 Stable Azuracast
