### ISSUE TITLE
502 Bad Gateway (nginx)

### ISSUE THREAD

**Issue by pi-mad** [AzuraCast/AzuraCast#5847]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

When after restarting the machine, azuracast refuses to boot up the gui webpages, it just turns out "502 Bad Gateway nginx) the streams are still running but cant open any admin pages or public pages.

I had this issue once before after a reboot and the only way I could get it back up was to uninstall and reinstall and inport a back up.

I'm a bit confused as to why this is happining.

If there is any log outputs you would like, let me know with the commands to run and I will post them back to you

**Comment by mdisabato** [comment]
I am having the same problem. Raspberry Pi 4. Current OS. All patches applied. log from Portainer attached.
[502 error log.txt](https://github.com/AzuraCast/AzuraCast/files/9985127/502.error.log.txt)

I have uninstalled and reinstalled. I have also started from a fresh install of the OS. Added Docker, Portainer, Telegraf, and Watchtower (excluding Azuracast). Over a 2-day period, the problem persists.

**Comment by hitzgh** [comment]
i have has similar issue before, and i find out the issue was the server was having 1GB or RAM, kindly check if the server ram is 2GB and up

**Comment by JohnyBeGood** [comment]
Same issue here. Running on Debian.

**Comment by MaxDeepCoder** [comment]
Same problem here on a Linode VPS. 

https://panel.deepradio.co.uk/listen/deepradio/128

**Comment by MaxDeepCoder** [comment]
Fixed. I just updated and rebooted.

**Comment by totoyaya** [comment]
Hello , i have the same problem and i try to re install and portainer , but it was impossible
