### ISSUE TITLE
servers drop out occasionally..

### ISSUE THREAD

**Issue by Gartral** [AzuraCast/AzuraCast#585]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Ubuntu 16.04

Ok, so I've been dealing with this and gathering data for a while, and as best I can tell, it's docker but the bug is, after about an hour or so, DJs and listeners experience "fade outs" where azuracast_stations go into a buffer overrun state: 
`azuracast_stations | 2018/05/09 06:26:21 [input(dot)harbor_5909:3] Buffer overrun: Dropping 0.03s.`

 then the server goes into a catchup: 
`azuracast_stations | 2018/05/09 06:37:26 [clock.wallclock_main:2] We must catchup 40.19 seconds!`

this happens exclusively on 2 DO droplets, both the $5 single core, 1gb ram units, a similarly equiped linode server doesn't have this, and an AlphaRacks 2cpu/1gb ram server running traditional also does not suffer this fault.
these issues could be related or symptomatic of another issue, which I'll open another ticket for, see #586

**Comment by SlvrEagle23** [comment]
@Gartral I've found that for the $5 DO VPS tier, it's necessary to set up a swap space, because DO does not provide one and this is necessary to avoid out-of-memory errors.

Here's a shortcut I often use to do this:

```bash
fallocate -l 2G /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
echo "/swapfile   none    swap    sw    0   0" >> /etc/fstab
```

**Comment by aripisprecer** [comment]
@SlvrEagle23 

I don't know if this is the same, but my shoutcast is randomply stoping every 3-4 days. I am running Ubuntu 16.04 on LXC.

The only think i saw at the time when the server was not runing, was the statistic from proxmox: 
Cpu usage 200% (for 2 cpus), and very high disk read (about 120-130MB/s),

Could this be related to the above bug?

![high cpu usage](https://user-images.githubusercontent.com/39081032/40266258-1b4da08c-5b48-11e8-9a32-c13f9fa9b5f1.JPG)
![high disk io](https://user-images.githubusercontent.com/39081032/40266259-1b6a5042-5b48-11e8-86d1-19f80f32b4ac.JPG)

**Comment by SlvrEagle23** [comment]
@aripisprecer That's definitely not normal, and likely not related to the original issue. You should probably submit a new issue about this.

Also, if you observe it happening again, make sure to check the logs (using [these instructions](https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#troubleshooting-by-viewing-logs)) and include any log messages that look like errors or appear relevant in the issue report.

**Comment by SlvrEagle23** [comment]
@Gartral Were you able to try out adding a swap file and see if that helps? It may just be that you're overrunning the available resources on such a low-end VPS, which can definitely happen if you have too many mountpoints running or too many separate stations.

**Comment by SlvrEagle23** [comment]
Closing this issue as it hasn't been followed up on by the reporter recently.

If anyone stumbles upon this issue and has similar issues, check the available system resources on the machine running AzuraCast. Liquidsoap needing to "catch up" is often because it's running very short on available CPU cycles because something else is hogging them on the system.
