### ISSUE TITLE
Playlist Advanced configuration

### ISSUE THREAD

**Issue by finnie2006** [AzuraCast/AzuraCast#5853]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#0ba1556

### What happened?

![afbeelding](https://user-images.githubusercontent.com/57916807/201497531-168b7bc6-ffa0-4214-aa3e-ae1a31549c2f.png)
The only play one song at the scheduled time option currently uses the liquidsoap once statement, this will indeed only play one song, but it will also do this only once, so it will work 1 time when the scheduled playlist plays but not the next time

See: https://github.com/savonet/liquidsoap/issues/1544

Solution: ````predicate.once```` should be used or ````predicate.at_most(1,````

### Relevant log output

```shell
X
```

**Comment by finnie2006** [comment]
May I ask why the fix was implemented but later reverted?

**Comment by BusterNeece** [comment]
@finnie2006 I'm not really sure, that was December. I've slept since then!

I suspect it may have something to do with the Liquidsoap 2.2.x rollout. We could look into putting it back.
