### ISSUE TITLE
after several days of uptime, azuracast goes unresponsive in interesting ways

### ISSUE THREAD

**Issue by Gartral** [AzuraCast/AzuraCast#586]
- **Installation Method:** docker
- **Host OS (if using Docker):** Ubuntu 16.04

**Describe the issue in full detail, including screenshots if possible:**

after several days the station_watcher thread/container gets OOMed, this might be related to #585 as it only happens on my DO hosts, and not AlphaRacks or Linode..

**Comment by SlvrEagle23** [comment]
Closing as likely related to #585 and hitting the upper memory limit of an economy VPS with no swap space available.
