### ISSUE TITLE
(Fresh Installed) Cannot connect to the stream USING Streamer/DJ Accounts 

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#587]
- **Installation Method:** Traditional
- **Host OS (if using Docker):**  Ubuntu 16.04, 

Before i freshly installed my AzuraCast i made an update. But after the update the streamer/dj account cannot login anymore in the stream. Two azuracast installation I updated with the same problem after the update the streamer/dj account cannot login to the stream. Now i decided to reinstalled the OS to make a fresh installed azuracast and now i have a fresh installed azuracast then i created a streamer/dj account but same problem still cannot login to the stream. I dont know where is the problem exactly. but before I updated everything is working fine. I hope anyone can help.

**Comment by Weigand-Hub** [comment]
I have the problem too. I have new installed Azuracast Traditional on Ubuntu 16.04 (without docker). I have testing with different streamingprograms. I have at all programs the same error. I hope this bug is fixed soon. This is not good for my project.

**Comment by SlvrEagle23** [comment]
@reans @Weigand-Hub This issue has been identified and should now be fixed. Please update your installations and let me know if the issue persists. Sorry for any inconvenience!

**Comment by Weigand-Hub** [comment]
Icecast works. but not yet Shoutcast. With Shoutcast I have to use Shoutcast 1 from the encoder.

**Comment by Manuelazu** [comment]
@SlvrEagle23 Icecast works. but not yet Shoutcast. With Shoutcast I have to use Shoutcast 1 from the encoder. Use SHOUTcast DNAS 2 No description
Cannot start broadcasting

**Comment by surihost** [comment]
I do have the same problem.

**Comment by surihost** [comment]
No fix yet? Need to connect live radio station with shoutcast dnas2.And when connecting with icecast it works but the listeners report doesnt show the real connection ip's.

**Comment by SlvrEagle23** [comment]
@Manuelazu @surihost @reans When attempting to log in via Shoutcast 2 DNAS, do you see anything in the log messages at `/var/azuracast/stations/(your_station)/config/liquidsoap.log`? You may also see an error message appear in `/var/azuracast/www_tmp/php_errors.log`. Check both and let me know if they show anything out of the ordinary so I can quickly get this fixed.

**Comment by surihost** [comment]
With the latest docker installation i dont see the azuracast folder in  /var

**Comment by SlvrEagle23** [comment]
@surihost Everyone else in this thread is using the Traditional installation. If you're seeing the issue in the Docker install as well, that would be new to me, and you should check that by running

`docker-compose logs -f web`
and
`docker-compose logs -f stations`

and seeing if anything pops up there.

**Comment by surihost** [comment]
root@ks:/opt/azuracast# docker-compose logs -f web
Attaching to azuracast_web_1
web_1          | 2018/05/22 00:37:39 Waiting for: tcp://mariadb:3306
web_1          | 2018/05/22 00:37:39 Waiting for: tcp://influxdb:8086
web_1          | 2018/05/22 00:37:39 Connected to tcp://mariadb:3306
web_1          | 2018/05/22 00:37:39 Connected to tcp://influxdb:8086
web_1          | [22-May-2018 00:37:39] NOTICE: fpm is running, pid 10
web_1          | [22-May-2018 00:37:39] NOTICE: ready to handle connections
web_1          | [22-May-2018 00:37:39] NOTICE: systemd monitor interval set to                                                                                                  10000ms
web_1          | [22-May-2018 00:38:00] WARNING: [pool www] server reached max_c                                                                                                 hildren setting (3), consider raising it
web_1          | 2018/05/22 00:38:14 Received signal: terminated
web_1          | [22-May-2018 00:38:14] NOTICE: Terminating ...
web_1          | [22-May-2018 00:38:14] NOTICE: exiting, bye-bye!
web_1          | 2018/05/22 00:38:14 Command finished successfully.
web_1          | 2018/05/22 00:38:23 Waiting for: tcp://mariadb:3306
web_1          | 2018/05/22 00:38:23 Waiting for: tcp://influxdb:8086
web_1          | 2018/05/22 00:38:23 Problem with dial: dial tcp 172.18.0.4:3306                                                                                                 : connect: connection refused. Sleeping 1s
web_1          | 2018/05/22 00:38:23 Problem with dial: dial tcp 172.18.0.3:8086                                                                                                 : connect: connection refused. Sleeping 1s
web_1          | 2018/05/22 00:38:24 Connected to tcp://influxdb:8086
web_1          | 2018/05/22 00:38:24 Connected to tcp://mariadb:3306
web_1          | [22-May-2018 00:38:25] NOTICE: fpm is running, pid 10
web_1          | [22-May-2018 00:38:25] NOTICE: ready to handle connections
web_1          | [22-May-2018 00:38:25] NOTICE: systemd monitor interval set to                                                                                                  10000ms
web_1          | [22-May-2018 00:38:40] WARNING: [pool www] server reached max_c                                                                                                 hildren setting (3), consider raising it
web_1          | [22-May-2018 00:47:13] WARNING: [pool www] child 23 said into s                                                                                                 tderr: "[2018-05-21 21:47:13] AzuraCast.ERROR: Cannot start process; AutoDJ is c                                                                                                 urrently disabled. {"station_id":9,"station_name":"Radio Ek Sitara"} []"
web_1          | [22-May-2018 00:56:20] NOTICE: [pool www] child 15 exited with                                                                                                  code 0 after 1063.087820 seconds from start
web_1          | [22-May-2018 00:56:20] NOTICE: [pool www] child 127 started
web_1          | [22-May-2018 00:58:21] NOTICE: [pool www] child 23 exited with                                                                                                  code 0 after 1168.686020 seconds from start
web_1          | [22-May-2018 00:58:21] NOTICE: [pool www] child 131 started
web_1          | [22-May-2018 00:58:30] NOTICE: [pool www] child 25 exited with                                                                                                  code 0 after 1177.690031 seconds from start
web_1          | [22-May-2018 00:58:30] NOTICE: [pool www] child 134 started
web_1          | [22-May-2018 01:20:14] NOTICE: [pool www] child 127 exited with                                                                                                  code 0 after 1434.163136 seconds from start
web_1          | [22-May-2018 01:20:14] NOTICE: [pool www] child 197 started
web_1          | [22-May-2018 01:22:06] NOTICE: [pool www] child 131 exited with                                                                                                  code 0 after 1425.107347 seconds from start
web_1          | [22-May-2018 01:22:06] NOTICE: [pool www] child 204 started
web_1          | [22-May-2018 01:22:21] NOTICE: [pool www] child 134 exited with                                                                                                  code 0 after 1430.708316 seconds from start
web_1          | [22-May-2018 01:22:21] NOTICE: [pool www] child 205 started
web_1          | [22-May-2018 01:45:09] NOTICE: [pool www] child 197 exited with                                                                                                  code 0 after 1494.946651 seconds from start
web_1          | [22-May-2018 01:45:09] NOTICE: [pool www] child 263 started
web_1          | [22-May-2018 01:47:07] NOTICE: [pool www] child 204 exited with                                                                                                  code 0 after 1501.252723 seconds from start
web_1          | [22-May-2018 01:47:07] NOTICE: [pool www] child 269 started
web_1          | [22-May-2018 01:47:10] NOTICE: [pool www] child 205 exited with                                                                                                  code 0 after 1488.871705 seconds from start
web_1          | [22-May-2018 01:47:10] NOTICE: [pool www] child 270 started
web_1          | [22-May-2018 02:09:48] NOTICE: [pool www] child 263 exited with                                                                                                  code 0 after 1479.004179 seconds from start

stations_1     | 2018/05/22 02:26:52 [radio_out_1:2] Connection failed: bad answer: Stream In Use
stations_1     | 2018/05/22 02:26:52 [radio_out_1:3] Will try again in 3.00 sec.
stations_1     | strange error flushing buffer ...
stations_1     | strange error flushing buffer ...
stations_1     | 2018/05/22 02:26:54 [lang:3] AzuraCast Raw Response: /usr/local/share/icecast/web/error.mp3
stations_1     | 2018/05/22 02:26:54 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
stations_1     | 2018/05/22 02:26:56 [radio_out_1:3] Connecting mount sid#1 for @127.0.0.1...
stations_1     | 2018/05/22 02:26:56 [radio_out_1:2] Connection failed: bad answer: Stream In Use

**Comment by surihost** [comment]
@SlvrEagle23 any idea what is happening, still not able to connect live streams.

**Comment by SlvrEagle23** [comment]
@surihost Your logs don't seem to indicate any details relating to actually attempting to connect as a Shoutcast 2 DJ account.

One major reason I'm having trouble diagnosing this is because none of my usual test DJ software connects using the Shoutcast 2 format.

**Comment by surihost** [comment]
So can i email you my vps and azuracast logins so can trace the problem?Cause it was working smooth on the earlier versions.And i can connect to live stream trough icecast but the problem is i dont see the connected ip's of the listeners and there place on the listeners report.

**Comment by surihost** [comment]
@SlvrEagle23 no fix yet?

**Comment by SlvrEagle23** [comment]
@surihost Please don't make posts like that. I'm a volunteer working on this project for free (and, mind you, alone) so if I have personal issues that prevent me from working, sometimes work doesn't happen as quickly as one might like.

If you'd like me to take a look at your setup, you can send me an e-mail with your login credentials and I can take a look. Otherwise, I have no insight into this problem or how to resolve it.

**Comment by surihost** [comment]
Ok will send you an email with my logins.
