### ISSUE TITLE
MIME Type: Application/x-empty is not processable

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#5872]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #f7d2d01 (2022-11-21 12:00

### What happened?

Did the update to fix this bug as soon as it came up, but afterwards AzuraCast App Log still reporting sh*t load of errors similar to what is shown in #5870.

Do I need to worry?
[AzuraCast App Log.txt](https://github.com/AzuraCast/AzuraCast/files/10061178/AzuraCast.App.Log.txt)

**Comment by ItsMitchh** [comment]
Can you provide some files that have this invalid MIME type? We can review this when we can.

**Comment by BusterNeece** [comment]
@SpeedyCharly I've updated the media processor in Rolling so it won't just keep trying to reprocess that same file, but we'd need to see the actual file in question that is being flagged as `application/x-empty`.

**Comment by SpeedyCharly** [comment]
Did the Update but seems like the log is the same...
Identifies 2 problem songs:
[Oopsie Songs.zip](https://github.com/AzuraCast/AzuraCast/files/10072523/Oopsie.Songs.zip)

**Comment by BusterNeece** [comment]
@SpeedyCharly Indeed, the files we're seeing here are 0kb and empty, and that seems to be what the metadata library is seeing as well.

**Comment by BusterNeece** [comment]
@SpeedyCharly Try redownloading, rezipping and reuploading them here?

**Comment by SpeedyCharly** [comment]
Both local and remote folders were showing proper file size in Filezilla. But, on closer look the problem files were dated in a year range between 2033 and 2038 and they returned 0 bites files on re-download (Search me on how that happened???).  Guess I must have somehow corrupted that folder during my last cleanup operations.  

Flushed the entire folder, reuploaded and synchronized the playlist to refresh the database. Result = no more error reports.  So I guess the whole thing was my bad... sorry to have wasted your time on this, and thanks for your help.

**Comment by BusterNeece** [comment]
@SpeedyCharly No worries. It definitely looked like an issue on our end. Glad you were able to get it figured out.
