### ISSUE TITLE
Password update failed

### ISSUE THREAD

**Issue by matthewunmuted** [AzuraCast/AzuraCast#5874]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.1 Stable

### What happened?

A client of ours is trying to change their password, however every time they try, they receive the message 'password update failed'.

Has this been reported by any other users?

**Comment by BusterNeece** [comment]
@matthewunmuted I don't believe I've seen this before...there were some Rolling Release versions that had some issues with saving API calls, but those date to way later than 0.17.1 and have since been resolved.
