### ISSUE TITLE
Urgent Help Required

### ISSUE THREAD

**Issue by Hadhab** [AzuraCast/AzuraCast#5875]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #dac19b1 (2022-11-16 1:59)

### What happened?

Cannot make any changes to my station. Getting error "You do not have permission to access this portion of the site."

**Comment by Hadhab** [comment]
I am not sure in which log should i look...

**Comment by MarkWasley** [comment]
You need to update your installation. This was fixed in rolling release version #93eb40a.

**Comment by ItsMitchh** [comment]
Fixed in rolling, let us know if you still having issues.

**Comment by Hadhab** [comment]
I have just updated and its working now... Thank You
