### ISSUE TITLE
The radio music storage dont match

### ISSUE THREAD

**Issue by machetedj** [AzuraCast/AzuraCast#5887]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.5 Stable

### What happened?

I have 5095 music files(.mp3) in the physical folder, but the admin panel in the music section show 4568 files, so why doesn't match?

**Comment by machetedj** [comment]
Back to the same issue

**Comment by machetedj** [comment]
![Screenshot 2022-11-18 151450](https://user-images.githubusercontent.com/55002144/204193586-50fc45cc-321b-438f-bd46-8be76d6432d2.png)
[
![Screenshot 2022-11-24 180155](https://user-images.githubusercontent.com/55002144/204193614-cbaa2477-647a-4fdd-9964-c8e6225f87c5.png)
](url)

**Comment by machetedj** [comment]
[
![Screenshot 2022-11-18 151450](https://user-images.githubusercontent.com/55002144/204193661-13ae4a99-ae60-4f0f-a8db-78dc19764142.png)
](url)

**Comment by BusterNeece** [comment]
@machetedj That's showing the number of processable media files that it is aware of, not the total number of files. The other files are likely things like cover art and other supplementary data.
