### ISSUE TITLE
AzuraCast.ERROR: Supervisor fault: BAD_NAME: station_1:station_1_backend {"faultString":"BAD_NAME: station_1:station_1_backend","faultCode":10} []

### ISSUE THREAD

**Issue by aarkkappler** [AzuraCast/AzuraCast#5888]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

The Radio Service Won"t start AzuraCast.ERROR: Supervisor fault: BAD_NAME: station_1:station_1_backend {"faultString":"BAD_NAME: station_1:station_1_backend","faultCode":10} []

Action already done : 

1) Flush cache
2) Updates
3) Reinstallation from Zero
4) restart from the front PHP
5 restart from the docker.sh cli radio

No idea what can I do, but I am not able to use Azuracast at all

### Relevant log output

```shell
AzuraCast.ERROR: Supervisor fault: BAD_NAME: station_1:station_1_backend {"faultString":"BAD_NAME: station_1:station_1_backend","faultCode":10} []
```

**Comment by BusterNeece** [comment]
Was a permissions issue on the installation's side.
