### ISSUE TITLE
mp3 uploaded files labeled as "not processed"

### ISSUE THREAD

**Issue by mlmateos** [AzuraCast/AzuraCast#589]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Debian 9

**Describe the issue in full detail, including screenshots if possible:**

Have my recent SFTP uploaded mp3 files labeled as "file not processed", as well as some uploaded using the web updater. Is there some guide to upload and check mp3 files?

![screenshot from 2018-05-13 08-16-55](https://user-images.githubusercontent.com/6385699/39967754-1f08a728-5687-11e8-80cb-fe9ff97c55c8.png)
![screenshot from 2018-05-13 07-39-55](https://user-images.githubusercontent.com/6385699/39967758-27460af2-5687-11e8-9272-af2edc3a6ffb.png)

**Comment by SlvrEagle23** [comment]
@mlmateos Were you able to find a solution to this issue? The AzuraCast code does include automatic truncating of strings, which should normally prevent this from happening in the system, but for some reason it appears Unicode characters are breaking this. :/

**Comment by xewl** [comment]
It's the query that fails, not the code.

Looking at `util/azuracast_db.sql` it seems like the field `artist` can only take up to a length of 200.

**Comment by SlvrEagle23** [comment]
@xewl Why so? The `setArtist` and other value-setting functions call the protected `_truncateString` function, which uses `mb_substr` because multibyte support is necessary for Unicode strings.

**Comment by xewl** [comment]
Exactly why I'm dumbfounded. There should be no reason.

artist: "Tanayev Piano Quintet in G minor Yuja Wang, Cho-Liang Lin violin, Helen Nightengale violin, Choon-Jin Chang viola, Lynn Harrel cello Santa Fe Chamber Music Festival, New Mexico Museum of Art, St. Francis Auditorium 7-23"

**Comment by SlvrEagle23** [comment]
@xewl Probably just MariaDB being MariaDB, like, where the database is counting characters a different way than `mb_substr` is. There's a possible solution in just truncating to a lower number than the actual limit, but I'd like to avoid that if at all possible. :(

**Comment by xewl** [comment]
@SlvrEagle23 I'm thinking you'll be a long way, by abiding 255 instead of 200 for varchar length.
Weird thing is that the query above, really does receive a 219 length string, even when seemingly not having this 

I'm kinda wondering atm where exactly these files get processed and ultimately pushed to the database. A stack-trace should show far more.

**Comment by SlvrEagle23** [comment]
@xewl Figured it out...the `loadFromFile` function in StationMedia was directly setting properties on the object instead of calling the `setFoo()` functions that did truncation.

Should be fixed now.
