### ISSUE TITLE
Saving the URL playlist 

### ISSUE THREAD

**Issue by brewkrezi** [AzuraCast/AzuraCast#5891]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

17.5 stable

### What happened?

When I create and save a playlist, it is directly active. However, when I enter a URL playlist, it is not active after saving. Only when I restart the AutoDJ, it is active. Is it possible for the URL playlist to become active just by saving?

**Comment by BusterNeece** [comment]
@brewkrezi Some functions of AzuraCast require that Liquidsoap be loaded with the playlists configured a certain way; while we can now reload Liquidsoap without disconnecting your listeners, that reload is still necessary when configuration changes. Playlists with external URL sources are one of those things, just like Mount Points and Remote Relays.
