### ISSUE TITLE
WebOoks triggering all the time

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#5894]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

c1263de (2022-11-28 12:27) • Docker • PHP 8.1

### What happened?

hello,
i have 2 webooks in my instalation. one, that sends me a email each time a dj connects and disconnects, and anoter that skips the auto dj song if live dj disconects. Sinse this morning, i noticed that i have like 200 e-mails in my inbox, and autodj is skiping the song all the time in  a non stop loop. the only way to make this stop was disabling the webooks.
sorry if i can't explain so much, but i'm here to provide all logs needed.

**Comment by ColinTheBossReal** [comment]
I am having the exact same problem. Right now I have 100 emails in the span of 20 minutes.

**Comment by ColinTheBossReal** [comment]
I turned my webhooks off and they keep going off.
