### ISSUE TITLE
Services stops more and more frequently

### ISSUE THREAD

**Issue by CouinCouin** [AzuraCast/AzuraCast#5895]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.10.3

### What happened?

Hi, 

We usually running with this version since a little more 2 year without critical problems (perhaps having to reboot VPS 2 or 3 times since the beginning).
Oui use AutoDJ only as falldown source (All rest of time we use live , from PC at home with Radio DJ). So oui have only 6 or 7 files of 1 hour playlists recorded with our audio processing (to get the meme sound quality betweey PC RadioDJ and fallback playlists).

But since a little more one month, we are to our 4th reboot from SSH console, with Putty : 
2022-10-25
2022-11-24
2022-11-27
2022-12-01

Symptoms are no AzuraCast web administration (website no responding), Icecast mountpoints not reachable (for encoder and listeners).

Ok I know it's an "old" version, on an "old" OS (Ubuntu 16.04 Server), but as well we use always for the same function, the both server and azuracast should not perish. (I still using XP machines to do always the same things sinces several years and it does not perish, it work now like several years ago).

I wanted to try azura update but docker is depreciated, purposing to update, but OS is depreciated for updating docker (f*cking programmed EOLs...). 

Perhaps a way to purge some old datas or don't know other else, to "clean" the configuration ? 

Thanks :)
Couin

**Comment by BusterNeece** [comment]
Without any logs or other additional information, it's very hard for us to tell what's causing the problem. We've fixed literally hundreds of bugs and made fundamental changes to the application between version 0.10 and our current version, so we would likely be unable to reproduce any errors reported with that version in any case. We'd recommend taking a backup of your current installation (preferably a VPS/VM level backup, but using our built-in backup software is possible as well) and upgrading to a newer version to take advantage of performance improvements.

**Comment by CouinCouin** [comment]
Hi,
The problem is that logs I find in AzuraCast (after VPS reboot) are limited, I mean, as well as system crashed, logs are no longer fed :(
About upgrading, I agree, It could be a good thing abouts fixes, even if we still use AzuraCast  with the same way since the beginning (as a "live" relay - because we use RadioDJ to make rotations etc etc - with somes 1 hour "podcasts" with the same audio threatment, in case of live failure), the actual configuration we have should still doing the samee job :) 
Also, the VPS OS is not elligible to update, so docker too, and Azuracast too :(  If I want to update AzuraCast, I have to reinstall VPS (available OS versions are 18.04 and 20.04 for Ubuntu Server, or 10 for Debian. There is Centos 7 but I never used Centos, just a little Ubuntu and Debian at home).
Also, for the moment I had no longer reboot to do since 18 days. Perhaps some OVH failures ?. 
See ya :)
