### ISSUE TITLE
High CPU Usage.

### ISSUE THREAD

**Issue by adoboligh1** [AzuraCast/AzuraCast#5896]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.5

### What happened?

Installed azuracast on a fresh instance and liquidsoap is using so much CPU  resources.

Station number : 20

CPU : 12 core AMD RYZEN 5 3600.
RAM : 64 GB DDR4
Storage : 12 TB HDD.
OS : Ubuntu 22.04

htop Screenshot below.

![Screenshot 2022-12-01 15 10 08](https://user-images.githubusercontent.com/43940776/205090857-5979a38e-ed11-48cf-8aa5-255d680d684f.png)

Liquidsoap Log : https://gist.github.com/adoboligh1/b2b2a171b9e5edec6878da1022301b34

Azuracast Docker Logs Is not working....has been loading for the pas 20 minutes. below is what is happening.

![Screenshot 2022-12-01 15 10 08](https://user-images.githubusercontent.com/43940776/205094092-ab74128e-1299-45b7-a5a7-033a6549773b.png)

**Comment by Vaalyn** [comment]
Those entries in the log suggest that the station is not returning anything for the autodj to play:
```
API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/10/liquidsoap/nextsong' with body: 
API nextsong - Response (200): false
```

Please check the following things:

What does LS show on the stations dashboard here for this station?

<img width="491" alt="image" src="https://user-images.githubusercontent.com/13745863/205094730-79a38a0b-bbdb-4f8f-a5ac-8a26d1855571.png">

And also check what the `Broadcasting` -> `Upcoming Song Queue` is showing for that station.

**Comment by Vaalyn** [comment]
I've looked through the AzuraCast log you posted an noticed the following things:

- Station 22, 13, 20, 17, 21, 18, 11, 19, 16, 14
  - Error: `No output defined, nothing to do.`
  - These stations have no outputs / mount points defined
  
This is causing those stations to be constantly restarting thus consuming a lot of CPU resources.
You should define at least one mount point for each of those stations.

Let's get those fixed and then look how the system behaves afterwards.

**Comment by Vaalyn** [comment]
😃 great to hear that it's working properly now.

I'll close this issue as resolved then 👍
