### ISSUE TITLE
Problems with Azuracast

### ISSUE THREAD

**Issue by tanotar** [AzuraCast/AzuraCast#5899]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

I tell you my story friends. In the company where I am, they had to change my server due to a problem with a disk. The moment I started the panel it started throwing errors, as shown in "image1". There seems to be a problem with the database. The audit_log.ibd table is weighing 112 GB "image2".
Mysql turns on and crashes

image1 https://ibb.co/wR8xQTJ
image2 https://ibb.co/McrnG1f

### Relevant log output

```shell
root@128971:/var/lib/docker/volumes/azuracast_db_data# docker exec -it azuracast_mariadb service mariadb status
/usr/bin/mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: NO)'


From 172.21.0.1 icmp_seq=1 Destination Host Unreachable
From 172.21.0.1 icmp_seq=2 Destination Host Unreachable
From 172.21.0.1 icmp_seq=3 Destination Host Unreachable
64 bytes from 172.21.0.2: icmp_seq=4 ttl=64 time=0.117 ms
64 bytes from 172.21.0.2: icmp_seq=5 ttl=64 time=0.025 ms
64 bytes from 172.21.0.2: icmp_seq=6 ttl=64 time=0.027 ms
64 bytes from 172.21.0.2: icmp_seq=14 ttl=64 time=0.073 ms
64 bytes from 172.21.0.2: icmp_seq=15 ttl=64 time=0.031 ms
64 bytes from 172.21.0.2: icmp_seq=16 ttl=64 time=0.031 ms
64 bytes from 172.21.0.2: icmp_seq=17 ttl=64 time=0.042 ms
64 bytes from 172.21.0.2: icmp_seq=18 ttl=64 time=0.025 ms
64 bytes from 172.21.0.2: icmp_seq=19 ttl=64 time=0.026 ms
```

**Comment by sachinshakya507** [comment]
in my case also 
audit_log.ibd weights about 42 GB .

**Comment by ItsMitchh** [comment]
I'll flag that bit up to the team for review, thanks for the details!
