### ISSUE TITLE
Custom port range

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#590]
It is possible to add possibility to custom port range from 8000 - 8999 to 9000 - 9999?

**Comment by jonikane** [comment]
Yeah, I saw that. But if I change the port for example: "9000" the station does not work ...

**Comment by SlvrEagle23** [comment]
@jonikane A small port range from 9000 to 9010 is used internally by AzuraCast, but you can use any port after 9010 for station hosting.

If you're using Docker, however, these ports aren't forwarded by default. You'll have to manually edit your `docker-compose.yml` file, and down near the very bottom, where it lists out the specific ports forwarded by the `stations` service, update those ports to reflect the specific range you want to use.

If you're on a Traditional install, the UFW firewall may not open those ports by default, but you can enable them by running `ufw allow 9010:9999/tcp`

**Comment by jonikane** [comment]
Thank you.

Its working now with port 9090 but doesn´t working with proxy...

**Comment by SlvrEagle23** [comment]
@jonikane The port 80/443 proxy expects that the stations will all fall within a range of 8000-8999. If you're on a traditional installation, you can update `/etc/nginx/conf.d/00-azuracast.conf` and modify the proxy rule that starts with `8` to start with `9`. Currently, there's not an easy way to change this for the Docker based installations.
