### ISSUE TITLE
how to Increase storage ?

### ISSUE THREAD

**Issue by freqq68** [AzuraCast/AzuraCast#5909]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.5

### What happened?

Hello There ! 

If someone know how increase storage ?

i'm running azuracast on proxmox, and at the installation, i've set 50Gb of data, and now I wan't to increase this, 
So, i've set more +250gb in proxmox that is ok (see picture below)
![image](https://user-images.githubusercontent.com/4027268/205637418-bd95e6a7-4717-4324-bde0-b0000227e22f.png)

And when I check on the azura :
![image](https://user-images.githubusercontent.com/4027268/205637812-4a3cac79-e338-48fd-a252-87401be478ff.png)

Don't know why :/

Thank's in advance!

### Relevant log output

```shell
No logs output.
```

**Comment by Dragondarn1993** [comment]
If you use block memory on the server, you still have to tell your Linux about the memory increase with the tool growpart/growroot

**Comment by GaetanSsfm** [comment]
> If you use block memory on the server, you still have to tell your Linux about the memory increase with the tool growpart/growroot

Thank's for your idea. normally the memory is not blocked but i don't mind about the growpart/root 

many thank's

**Comment by iamflorencejay** [comment]
Mount a volume first on your ``docker-compose.override.yml`` file. 

More here:
https://docs.azuracast.com/en/administration/docker#mounting-a-directory-into-a-station
