### ISSUE TITLE
Play Particular song from the list

### ISSUE THREAD

**Issue by jrsarath** [AzuraCast/AzuraCast#591]
Installation Method: Traditional
Host OS (if using Docker): Ubuntu Server 18.04

Hi there, 
is it possible to play a particular song from playlist ? i mean i can listen to the particular song at the backend but i wanted to broadcast that particular song..
and is it possible to stop a station without stopping LiquidSoap ?

**Comment by SlvrEagle23** [comment]
Hello! Your first issue is actually already an enhancement request, issue #230, so you can follow that for updates.

To answer your second question, on the station's "Profile" page, next to the frontend (Icecast/Shoutcast/etc) and backend (Liquidsoap) there are little three-dot menus; from those menus, you can individually shut down or restart just the frontend or backend independent from the other portion. This should let you do what you need to do.

**Comment by jrsarath** [comment]
Hi,
thanks for the reply.. 
theres one more request is it possible to fadeout the current song and fadein next song while crossfading/changing songs ?
i saw that while use skip song from backend then next song fades in and previous song get stopped..

**Comment by SlvrEagle23** [comment]
@jrsarath Crossfading is normally configurable via the station's profile, but if you "Skip Song" it immediately terminates the existing song while fading in the new one. As far as I know, there's no way for us to make that process more graceful, as it's controlled by Liquidsoap.

**Comment by jrsarath** [comment]
Alright thanks again..
