### ISSUE TITLE
permission denied local storage

### ISSUE THREAD

**Issue by 01123581321345589144233** [AzuraCast/AzuraCast#5924]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

latest

### What happened?

UnableToCreateDirectory at /var/azuracast/www/vendor/league/flysystem/src/UnableToCreateDirectory.php L20: Unable to create a directory at /var/azuracast/stations/lin/media/. mkdir(): Permission denied

system disk 60GB
/data disk 1.8TB

i have mountet a local storage /data/stations and added the config to the docker-compose.override.yml

services:
  web:
    volumes:
      - /data/stations:/var/azuracast/stations

i have try the user:group www-data:www-data perms denied
with www-data:www-data 0775 its working

**But what is the right user to mount the local storage mount?**

i can see the station inside the foulder has another username and group

### Relevant log output

```shell
UnableToCreateDirectory at /var/azuracast/www/vendor/league/flysystem/src/UnableToCreateDirectory.php L20: Unable to create a directory at /var/azuracast/stations/lin/media/. mkdir(): Permission denied
```

**Comment by learntoswim** [comment]
What was your fix?

**Comment by 01123581321345589144233** [comment]
with www-data:www-data 0775 its working
