### ISSUE TITLE
shoutcast directory showing a double https

### ISSUE THREAD

**Issue by rbarbier1967** [AzuraCast/AzuraCast#5926]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

I am not sure if it is Azuracast sending the wrong url or Shoutcast directory adding an extra HTTPS:// to the URL. But if you try to listen through the Shoutcast directory it adds an additional HTTPS :// to the URL.  via the m3u in vlc you get VLC is unable to open the MRL 'https://https://shokanradio.com:6050/autodj'. Check the log for details.

if you try to do it from the web page its simular error as well. not sure if there is a way to send the url to shoutcast without the https from azuracasts end or not . Just thought I would bring this to your attention.
Once again thank you for all your hard work on this program and project.

**Comment by rolradio** [comment]
The error is in the shoutcast sc_serv.conf
Azuracast provides the following information:

destdns=https://sub.domain.com
destip=https://sub.domain.com
publicdns=https://sub.domain.com
publicip=https://sub.domain.com

it should be without "https://"

If this is corrected for the next update, it will be resolved.

**Comment by rbarbier1967** [comment]
well the update said it supposedly fixed it, but still does it on mine, even canceled and remade the station on shoutcast to make sure it was fresh, unless they were refering to a different link posting. Really frustratin lol. At least the icecast ones work, but no monetization there :/ Well it will eventually get fixed I guess.

**Comment by BusterNeece** [comment]
@rbarbier1967 We have not released any update addressing this yet. What do you mean "the update said it supposedly fixed it"?

**Comment by rbarbier1967** [comment]
I must had misread the release notes. please ignore previous comments.

**Comment by rbarbier1967** [comment]
Btw thanks for all your hard work on the project, I am quite tired tonight so i missread the release notes.

**Comment by dzsam** [comment]
hello,
I have the same problem.
Ubuntu last release. Docker installation
Kind regards

**Comment by rbarbier1967** [comment]
@dzsam we just got to hang in there until they get around to fixing this problem. They have a lot on their plate and with the constant updates we have been getting, there may be a fix for it in one of them sooner or later. Plus it is the Holiday season so I would imagine they have more things going on in their lives than they usually do. Meanwhile I think ill buy them a cup of coffee, Since at the moment it is all I can do. Happy Holidays to Azuracast and the community.

**Comment by BusterNeece** [comment]
Fixed in the latest Rolling Release which is currently deploying.

**Comment by rbarbier1967** [comment]
> Fixed in the latest Rolling Release which is currently deploying.

Thanks @BusterNeece  Happy Holidays

**Comment by dzsam** [comment]
Thank you for all your efforts. your work is wonderful. Barbier is right to say that your work deserves the support of the whole community. I don3t know a web radio management, as complete as yours.
