### ISSUE TITLE
No play button on public page

### ISSUE THREAD

**Issue by anyall** [AzuraCast/AzuraCast#5927]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#37dc95b

### What happened?

After an Azuracast update, the Play button no longer appears on the public page

**Comment by lesmonds** [comment]
I can confirm, I have the same issue, also dont show on the 'Embed Widgets' 
Rolling Release #37dc95b 

![Screenshot_1](https://user-images.githubusercontent.com/25802127/206868008-3f328e31-bacf-4977-bec0-48fbfc13cb6b.png)

**Comment by ItsMitchh** [comment]
This should be fixed in the latest rolling release (https://github.com/AzuraCast/AzuraCast/commit/b8a825b8eab5ba5deb42f43f75c61cf73eb83a2c) Wait for the green tick before updating.

**Comment by isAAAc** [comment]
update done here, fixed ok on my side , thx @ItsMitchh ;)
:white_check_mark:

**Comment by anyall** [comment]
Yes it's OK now
Than you !
