### ISSUE TITLE
Station player not updating song title when the song changes

### ISSUE THREAD

**Issue by MatthewSmithYT** [AzuraCast/AzuraCast#5932]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

b8a825b (2022-12-10 18:06)

### What happened?

After a song ends, the title of the song does not change to the new one, and the time sits at the end. 
Example.
2 songs, song 1 and song 2
song 1 is playing and has a total time of 3:20
song 2 is next
song 1 finishes and song 2 starts in the audio stream
the player displays song 1 having finished and displays that 3:20/3:20 have played
Even though song 2 started, the player will display song 1 for quite a while, I'm not exactly sure how long. Using the clear cache option fixes the problem, for a song or two at least, but I shouldn't have to do that every time it breaks, which seems to be pretty often.
I have no idea which logs will be important and I'm not sure where in the logs to look. If logs are needed, please direct if possible.

Thanks for the help!

**Comment by PeWe79** [comment]
Same issue here

**Comment by BusterNeece** [comment]
We strongly recommend using the "High-Performance Now Playing Updates" setting (via System Settings) if you can. We've made some changes to how our Now Playing data updates, including how the clock syncs, that should significantly improve the software's ability to line up with the current playing track.
