### ISSUE TITLE
3 errors after stable version update

### ISSUE THREAD

**Issue by radiobellissima** [AzuraCast/AzuraCast#5935]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.6

### What happened?

I insert photos of the 3 errors found.
![Test](https://user-images.githubusercontent.com/57127248/207113688-c80f46b3-1eb5-491e-93f7-0a8a1c0bc0a6.png)
![Test1](https://user-images.githubusercontent.com/57127248/207113691-90ea02fa-8e87-44ac-9d0e-2a96efb0e4e6.png)
![test2](https://user-images.githubusercontent.com/57127248/207113693-19cdad11-d558-4937-8bde-fd7c1213b982.png)

**Comment by BusterNeece** [comment]
@radiobellissima You're so close to helping us diagnose this! Try to actually run that task and let me know what it says in the logs.

**Comment by radiobellissima** [comment]
I get this
![Test](https://user-images.githubusercontent.com/57127248/207115311-0d2ddb58-cfec-4dd3-9479-717563766f9f.png)

**Comment by radiobellissima** [comment]
UPDATE:
I wanted to point out that magically without carrying out any operation for a few minutes both the statistics on the home page and also the tasks have started working again and the error has disappeared. If it helps it's been about 22 hours since I updated to this version.
![Test](https://user-images.githubusercontent.com/57127248/207144871-a048290e-014b-463c-8fcd-43382f8de66f.png)
![Test1](https://user-images.githubusercontent.com/57127248/207144873-c2d859e9-bc50-466e-a804-499f540af1c1.png)
