### ISSUE TITLE
Web DJ connecting, then immediately disconnecting

### ISSUE THREAD

**Issue by matthewunmuted** [AzuraCast/AzuraCast#5947]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #f8fd85d

### What happened?

When attempting to use the WebDJ feature, upon clicking the 'Start Streaming' button, these Error messages appear:

Live stream connected.

Live stream disconnected.

Please see this screenshot showing this:

https://imgur.com/a/JlAgFwd

We have tried changing all of the settings and playlist media to no avail

**Comment by Mozitux** [comment]
I'have the same issue
