### ISSUE TITLE
Incorrect song length in media library 

### ISSUE THREAD

**Issue by iplayradionetworks** [AzuraCast/AzuraCast#5948]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #e0cc6e6 (2022-12-14 21:09)

### What happened?

![Screenshot_20221216_092321_Chrome](https://user-images.githubusercontent.com/40426604/208082537-b14747a1-d9da-4b8b-9702-f3fabd8cf354.jpg)

There is incorrect time length shown on the tracks.

**Comment by iplayradionetworks** [comment]
To be precise what's being displayed is in seconds and not in minutes.

**Comment by iplayradionetworks** [comment]
The problem still persists on 0.17.6 stable version

**Comment by BusterNeece** [comment]
@iplayradionetworks The issue is fixed in our latest Rolling Release version, which will be incorporated into a future stable release. You can either switch release channels or wait for the stable release to incorporate this fix.

**Comment by iplayradionetworks** [comment]
> @iplayradionetworks The issue is fixed in our latest Rolling Release version, which will be incorporated into a future stable release. You can either switch release channels or wait for the stable release to incorporate this fix.

Oh ok Buster . Got it. Thanks. 
I am on stable now (was on rolling before weekend) so I will wait. 

Thanks for your amazing support.

Take care 
Jim
