### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#595]
- Installation Method: Traditional
- Host OS: Ubuntu 16.04 LTS

It gave me an error when i try to install Azuracast.
Error on build liquidsoup.

"TASK [azuracast-radio : Build LiquidSoap]"

the error is on the attached printscreen
![azuracast_error](https://user-images.githubusercontent.com/7109309/40590410-3fa5be9c-61f6-11e8-82eb-01e17e062f6d.png)

**Comment by jonikane** [comment]
Now it gave another error on another ubuntu 16.04

error: TASK [init : Update pip components]

![azuracast_error1](https://user-images.githubusercontent.com/7109309/40689171-fd10d59a-6398-11e8-8968-c844362021ef.png)

**Comment by SlvrEagle23** [comment]
@jonikane Both of these processes depend on third-party systems working properly on the host computer. As such, they may go wrong and it's very difficult for us to diagnose, as it's something wrong with a system we don't control.

It definitely appears there's something causing problems with your specific hosting setup, but I have no idea what is causing it.

I'd highly recommend, if possible, using the Docker installation for this exact reason.
