### ISSUE TITLE
There is no progress bar when uploading files to the media folder

### ISSUE THREAD

**Issue by novsal** [AzuraCast/AzuraCast#5950]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 AzuraCast Rolling Release #6cb6236 (2022-12-17 3:43) • Docker • PHP 8.1

### What happened?

There is no progress blue bar when uploading files to the media folder, but files can still be uploaded and successfully
screen shot is below

![not showing](https://user-images.githubusercontent.com/53934647/208238422-e415ea7f-418a-4a38-936a-1d7707ba4a6e.JPG)

![Capture](https://user-images.githubusercontent.com/53934647/208238862-fc1c3ec6-6955-40e8-b19a-3722696818b3.JPG)

**Comment by rolradio** [comment]
I can confirm this. Even on a new installation.
