### ISSUE TITLE
Metadata Update Issue

### ISSUE THREAD

**Issue by PeWe79** [AzuraCast/AzuraCast#5955]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

18.04 LTS AsuraCast v0.17.6 Stable

### What happened?

The metadata Icecast streaming often doesn't up to date when the metadata from the encoder sends the last metadata.
So, title & artist often not updated.

**Comment by Aegischatz** [comment]
2022-12-28 19:56:22	INFO	[ADMINCGI sid=1] Title updated [Paffendorf - Smile (Original Mix)]
[01;33m2022-12-28 20:01:41	WARN	[ADMINCGI sid=1] Title update rejected - value not allowed: Unknown
[0m2022-12-28 20:01:42	INFO	[ADMINCGI sid=1] Title updated [Propaganda - Machinery]
2022-12-28 20:05:24	INFO	[ADMINCGI sid=1] Title updated [Propaganda - Machinery]
[01;33m2022-12-28 20:05:30	WARN	[ADMINCGI sid=1] Title update rejected - value not allowed: Unknown
[0m
2022-12-28 20:06:47	INFO	[ADMINCGI sid=1] Title updated [Harris & Ford & Outsiders - Irrenhaus | chrissy Live on Air aus Frankreich]

we have the same Problem, see Log
In the shoutcast it is not connected immediately, but a title from the playlist is played first. Although the streamer is online according to Azuracast, you can only hear the streamer after the title from the playlist has been played. Even a reconnect with the streaming software brings no change.

**Comment by PeWe79** [comment]
I think this metadata issue when streaming server is Icecast, but not happen on Shoutcast server. Event if I try with all audio support (AAC, mp3, opus and flac) metadata always up to date and working well.

**Comment by Aegischatz** [comment]
no, it occurs on both sides. Icecast and Shoutcast have identical bugs. The autodj latches onto shoutcast and only lets the streamer on after a title has been played. The Icecast takes over the title display from the last streamer and it doesn't matter how much time is in between.


Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by PeWe79** [comment]
Hi @Aegischatz on my case, just happen on Icecast server only. But if I use Shoutcast server metada update working well.

**Comment by Aegischatz** [comment]
As I said, I have both configurations running and since the update these errors


Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Kingsradio** [comment]
Am a new user of Azura cast and am having an update metadata issue, can anyone be of help? Thanks
