### ISSUE TITLE
With the Visual CUE Editor, you cannot use the sliders when the song is playing

### ISSUE THREAD

**Issue by wegGehamstert** [AzuraCast/AzuraCast#5957]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.6

### What happened?

With the Visual CUE Editor, when the song is playing, you cannot move the slider below to change the position

https://youtu.be/lZQHchR2eek

**Comment by BusterNeece** [comment]
I've looked into this and confirmed that it's acting as described, but this is a known limitation of the Wavesurfer library itself that we use, and I don't believe it's something we can directly fix ourselves.

**Comment by wegGehamstert** [comment]
Okey thank you!
