### ISSUE TITLE
Port 8000 doesn't loads

### ISSUE THREAD

**Issue by Daniellop1** [AzuraCast/AzuraCast#5965]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.6 Stable

### What happened?

I am hosting azuracast on an Oracle Cloud machine and have configured a local mp3 broadcast on port 8000. When I want to access the link that appears on the dashboard (https://radio.dglobal.dev:8000/radio.mp3) it never loads.

**Comment by LordHelmchen666** [comment]
Firewall port open?
```


Adresse: radio.dglobal.dev
--

Port 8000 - closed


```

**Comment by Daniellop1** [comment]
<img width="434" alt="Captura de pantalla 2022-12-27 a las 15 56 31" src="https://user-images.githubusercontent.com/44546966/209683965-370255d0-e024-4f16-a1b6-c78cc9792f1c.png">
It's open.

**Comment by LordHelmchen666** [comment]
Maybe same like here #5970

**Comment by Daniellop1** [comment]
<img width="434" alt="Captura de pantalla 2022-12-27 a las 16 53 54" src="https://user-images.githubusercontent.com/44546966/209690346-683eea5d-4711-4036-9377-878bab76ff42.png">
I have tried and I'm getting this error
