### ISSUE TITLE
Can't create music storage folder on seperate mounted disk

### ISSUE THREAD

**Issue by astridbunny** [AzuraCast/AzuraCast#5973]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

I'm trying to use a different disk to store music but I am getting this error from the web console: 

`ValidationException at /var/azuracast/www/src/Exception/ValidationException.php L37: Object(App\Entity\StorageLocation): Storage location Local: /mnt/music could not be validated: Unable to create a directory at /mnt/music. mkdir(): Permission denied`

The folder is owned and read/writable by gid/uid 1000 so I'm unsure what permissions I need to set.

**Comment by itsmejosh8** [comment]
Hey, I worked through this exact issue earlier today using [this LinuxMan.co blogpost](https://linuxman.co/uncategorized/host-your-own-personal-internet-radio-station-with-azuracast/#using-volumes-in-docker-7d8febf0-2853-477e-a7cc-92a4332de89d). 

In short, the path needs to be defined within the docker-compose.yml before you can add the path in the UI:
- Stop the docker container responsible for AzuraCast (`sudo docker stop $CONTAINER_ID`)
- Either edit the original `/var/azuracast/docker-compose.yml` or copy & edit an "override" file `/var/azuracast/docker-compose.override.yml` to include your mounted disk and the directory AzuraCast should use on that disk to store files. For me, this looked like: `- '/mnt/AzuraCast-ExtraSpace:/Music/'`
- You have already made sure that the disk is owned by the correct user, but this can be verified within `/var/azuracast/.env` (my GID/UID was also 1000). if you need to change it, `sudo chown 1000:1000 /disk/path`
- Restart AzuraCast container: `sudo docker-compose -f docker-compose.override.yml up -d`
- Add that new path within the AzuraCast UI, in my case my Path Suffix was `/Music/` (as defined earlier).

The disk should now be recognized as additional storage, but one nuance I am currently working though is that any station can only seem to mount one path at a time. If you switch a station's path, it seems to lose visibility of music stored elsewhere.

**Comment by astridbunny** [comment]
This worked!! Thank you so much.
