### ISSUE TITLE
Problem with new role button

### ISSUE THREAD

**Issue by megasmorf** [AzuraCast/AzuraCast#5974]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release # 0408efb (2022-12-27 13:40) • Docker • PHP 8.1

### What happened?

When I try to create a new user role by clicking on the "new role" button it does not start any function so that I create a new role

**Comment by BusterNeece** [comment]
@megasmorf This was fixed in a slightly later version of the Rolling Release.

**Comment by megasmorf** [comment]
Do I have to reinstall from scratch? or can I somehow upgrade my installation?

**Comment by BusterNeece** [comment]
@megasmorf https://docs.azuracast.com/en/getting-started/updates
