### ISSUE TITLE
A USER WHO'S NOT ADMIN HAVE ACCESS TO MY ACCOUNT ??

### ISSUE THREAD

**Issue by freqq68** [AzuraCast/AzuraCast#5976]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.17.6 Stable • Docker • PHP 8.1

### What happened?

Hello,

Security report, I don't know why and how is it possible, but an user that not have admin rank have suddenly have access to my account with no password... just in navigate to azuracast thru is radio station so... little bit embarassing...

And some times, when I navigate thru azuracast, I switch to an random account -_-

Not very secure so,

Anybody ? ^^

**Comment by BusterNeece** [comment]
We need a lot more information about this before we can address it.

It sounds, from how you're describing it, like there might be a misconfigured reverse proxy installed between AzuraCast and the web, and it's caching pages viewed by one session and serving them to another.

Even if this is the case, such a misconfiguration should still not allow other users to _modify_ parts of the system, as it would only be letting them view cached pages that other users had viewed before.

**Comment by freqq68** [comment]
Yes, maybe a misc buuuut sometimes, it disconnect us avec changing pages and a text will be appear like "you don't have access to this page please log in"

We use : Nginx Proxy Manager and the option caching is on and idem on cloudflare that is proxised 


Nginx Config:
![image](https://user-images.githubusercontent.com/4027268/209996008-29909462-06a6-40bf-8ca1-e48c9acedc3b.png)

**Comment by BusterNeece** [comment]
@freqq68 What is your caching setup like on Cloudflare? I strongly suspect this is an aggressive cache situation and not a security vulnerability in AzuraCast itself.

**Comment by freqq68** [comment]
@BusterNeece 

Our cachin Level : 
![image](https://user-images.githubusercontent.com/4027268/209996948-45e04e17-0e1b-436c-bf22-bc5603fc92ad.png)

And this one in cloudflare ? : 
![image](https://user-images.githubusercontent.com/4027268/209997091-0e6b027e-6386-4bfd-810a-9f81b187683a.png)

And finally this one the ratio : 
![image](https://user-images.githubusercontent.com/4027268/209997197-4a015211-10e6-4461-89f8-1b3f2834f70e.png)


Hope you can understood this situation :/

**Comment by BusterNeece** [comment]
@freqq68 I don't immediately see anything particularly wrong, but I also don't see your full infrastructure here. It's possible that  this issue is beyond the scope of our support.

**Comment by freqq68** [comment]
Mmmmh right thank's a lot, what you would to see particularly ? @BusterNeece
