### ISSUE TITLE
Clear Media Queue times out when queue is too long (but the clear operation does work!)

### ISSUE THREAD

**Issue by guiltlab** [AzuraCast/AzuraCast#5978]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#08de0f9 (2022-12-26 18:14)

### What happened?

Sometimes when you do operations on too many items at the same time, the media queue gets extremely long, keeps getting bigger and no new files actually get processed until you clear the queue entirely. This happens for example when I delete thousands of tracks and then add thousands of tracks. I don't know if this behavior can be prevented in the first place, it's the source of the problem but that's a different bug. What I'm reporting here is that when the media queue is too long (think > 100k messages), if you click "clear queue" (or "clear all message queues"), it will time out after a while and show a blank page. However, the function actually works ! 
Yesterday I had > 500k media queue messages, when I clicked clear queue => blank page after a while => reload the debugger admin page => there are ~100k less unprocessed messages in the queue. I repeated the process 5/6 times and eventually managed to clear the queue entirely, which fixed my issue. So I believe the problem here is not with the function itself, it's doing its job correctly, but just the fact that some timeout happens before it is done clearing the queue when that queue is too long. I am using Firefox on Windows, in case that matters, I haven't tried with other browsers.

**Comment by BusterNeece** [comment]
Yeah...setting timeouts on things like this is difficult, as we don't want it to just be indefinite and let the process hang, but we have to set it to something reasonable for most requests. I think it's probably okay as it is, as long as folks know that the queue does get cleared even if it times out.

**Comment by guiltlab** [comment]
I don't know if it's feasible (maybe it's hard to know if the timeout happened for this reason or another...), but it might help if AzuraCast displayed a message like "queue too long to clear all at once, you will need to repeat this operation. x messages remaining in the queue" with a link to admin/debug page, instead of the blank page. Or maybe better, a warning about this potential behaviour when clearing lots of messages next to the "clear queue" buttons, as an explanation text so users don't think there is a bug with their system when it happens ?
Personally I understood quickly that it was a timeout and not the clear function being broken, but perhaps it's not obvious to everyone.

**Comment by BusterNeece** [comment]
@guiltlab As an update to this, since I still had it flagged for follow-up, this should now be a non-issue now that we've switched our message queue processing back over to Redis. Redis allows us to instantly clear message queues, which greatly optimizes our processes in various areas.
