### ISSUE TITLE
Stereotool cannot clear configfile

### ISSUE THREAD

**Issue by 01123581321345589144233** [AzuraCast/AzuraCast#5982]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #9862a28 (2022-12-30 22:02) 

### What happened?

Hi i will upload a new stereotool config but i cannot clean the old config, the button "clear file" is not responding.

**Comment by novsal** [comment]
Yes, it's the same as mine, clear file in the stereo tools section doesn't work to update the sts file

**Comment by BusterNeece** [comment]
Fixed in latest Rolling Release.
