### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by MarkWasley** [AzuraCast/AzuraCast#5983]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #fb5dba9 (2023-01-02 21:33)

### What happened?

I've found a few UI issues that have recently cropped up in the application.

When adding or editing a playlist, the second line of the Source, Playlist Type and Song Playback Order were previously on a second line in smaller text. On the Schedule tab, the Scheduled Time number counter doesn't display anymore.

On the player, clicking the mute button doesn't move the volume slider to the far left, making it difficult to see if the audio has been muted or another issue is occurring. If the audio is muted, you cannot move the volume slider.

When live broadcasting, the player used to display the word "Live" wrapped in a span element with the class "badge badge-primary".

**Comment by Countryman98** [comment]
Experiencing the same Scheduling "Time Error" as above. 
Running rolling release version • Rolling Release #[a5bf63e](https://github.com/AzuraCast/AzuraCast/commit/a5bf63ed490e1c230cab5e26f41a3469e1ffa74d) (2023-01-03 22:55

**Comment by MarkWasley** [comment]
The issues in the first paragraph have not been resolved yet.

**Comment by BusterNeece** [comment]
@MarkWasley These should really be separate GH issues. I track "doneness" on a per-issue basis, not a per-paragraph-of-issue basis.
