### ISSUE TITLE
Cannot add storage locations

### ISSUE THREAD

**Issue by Dragondarn1993** [AzuraCast/AzuraCast#5986]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #4ceb167 (2023-01-06 2:28)

### What happened?

Hi,

when I click on the "Add Storage Location" button under Storage Locations, nothing happens. Also when I click on Edit on added locations, nothing happens.

**Comment by guiltlab** [comment]
I see the same thing on my installation, Rolling Release #[08de0f9](https://github.com/AzuraCast/AzuraCast/commit/08de0f96dc265759afc069740204ed872cc5d993) (2022-12-26 18:14).

**Comment by unudelaradio** [comment]
Same issue on Roles & Permissions. Cannot Add Role or Edit the existing ones.

**Comment by mxpro4k** [comment]
AzuraCast• v0.17.3 Stable • Docker • PHP 8.1
remote storage location setup is working for me and connected to my remote sftp server ! , it shows the files in remote storage under locations in azuracast, but is not visible in the media files ? is the remote connection only used for backups and not extended media library ? as i was under the impression it was to extend the media library ?
