### ISSUE TITLE
radio 404

### ISSUE THREAD

**Issue by Sendoushi** [AzuraCast/AzuraCast#599]
- **Installation Method:** Traditional
- **Host OS (if using Docker):** Ubuntu 18

**Describe the issue in full detail, including screenshots if possible:**
I've set azuracast inside a bridged adapter virtualbox machine. I've set the base page as a browser one because I'll be accessing by ip and is easier this way. I can easily access the frontend and public webpage. Easy to manage whatever but when I play the mountpoint (which is the default radio.mp3) it gives me 404. Anywhere I should look for logs? Any idea why this happens? Radio is on auto dj and seems to be working on the frontend except the 404.

**Comment by Sendoushi** [comment]
I keep getting on the sidebar "Apply pending changes. Restart to apply" and when I hit it, i get "please wait" (without a change back). I rebooted and the same still happens.

Icecast log doesn't have anything to worry just a simple 
```
INFO admin/admin_handle... processing file stats
``` 

The php error log gives me some issues: 
```
Allowed memory size of 134217728 bytes exhausted (tried to allocate 114688 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/BlobType.php on line 50
```

Nothing else... 404 on the radio.mp3 default route.

**Comment by SlvrEagle23** [comment]
@Sendoushi This sounds like a base URL problem. The URLs for stations are based on the "Site Base URL" setting inside AzuraCast, and if that URL doesn't respond properly to the radio ports, you won't be able to listen using the web interface at all.

You may also want to try proxying the radio connections through port 80 (also a setting on that same Settings page) as a way of resolving the issue.

**Comment by SlvrEagle23** [comment]
@Sendoushi I haven't heard any follow-up on this issue, so I don't know if the issue has been fixed or if further action is required on my end. If you don't mind, could you please update me on the status of this issue?

If I don't hear any updates for a while, I'll close the issue as resolved.
