### ISSUE TITLE
WebDJ not working

### ISSUE THREAD

**Issue by Hadhab** [AzuraCast/AzuraCast#5994]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #f15ef56 (2023-01-07 1:05)

### What happened?

Web DJ not working...

Showing the following error when trying to go live: 

Error
An error occurred with the WebDJ socket.
 PLease do help me fix it

**Comment by Hadhab** [comment]
![image](https://user-images.githubusercontent.com/70360646/211139959-64d51934-acca-4043-b465-4e462b5fda05.png)

**Comment by Hadhab** [comment]
if it helps, i had changed the default port from port 80 to port 100

**Comment by BusterNeece** [comment]
@Hadhab Is your base URL in System Settings set to `yoururl:100` (or, it appears from your browser screenshots, `:500`?

**Comment by Hadhab** [comment]
No, I have not changed my base URL as it will also change my Stream Link

**Comment by BusterNeece** [comment]
@Hadhab Yeah...but if you're using nonstandard ports, that's okay, right? Your listeners connect on one port, and your main web interface is on another? You could also override the listen URLs for each individual Mount Point...

**Comment by Hadhab** [comment]
Will try

**Comment by Hadhab** [comment]
I am stoll getting the same issue after changing the Base URL

**Comment by Hadhab** [comment]
Update: I have updated to Rolling Release #fe2b44d(2023-01-12 3:13). I am still facing the same issue "An error occurred with the WebDJ socket"

**Comment by Hadhab** [comment]
Update:
Even after updating to the latest version, I am getting the same error

**Comment by Hadhab** [comment]
The issue still exists, any way to fix it?

**Comment by BusterNeece** [comment]
@Hadhab So what is your base URL currently set to? It should just be taking your full base URL and only replacing the scheme with "ws" or "wss" for the websocket.

**Comment by Hadhab** [comment]
My current base url is qurum.ddns.net:100

**Comment by BusterNeece** [comment]
It seems the WebDJ isn't picking up the `:500` part for some reason. Maybe you have "Prefer Browser URL" enabled...I don't know enough about your specific setup to be able to comment much further here.

**Comment by Hadhab** [comment]
I am not sure how but it has started working properly now

**Comment by ElvisGarces** [comment]
How sad when things "solve themselves" or do not share the solution >:(
