### ISSUE TITLE
Rules station

### ISSUE THREAD

**Issue by pablozabrze** [AzuraCast/AzuraCast#5997]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.6

### What happened?

Good morning. In my installation there is a problem in making station permissions. I cannot create a role for a given station, I can create global permissions. The problem occurs on two installations. My installations
AzuraCast • v0.17.6 Stable • Docker • PHP 8.1

**Comment by pablozabrze** [comment]
https://user-images.githubusercontent.com/122202998/211189445-9707952a-7242-4d43-95fa-e40ecedf7e48.mp4

**Comment by brbranco** [comment]
First you must add a name for the rule, only then do the configuration and save.

**Comment by pablozabrze** [comment]
> First you must add a name for the rule, only then do the configuration and save.

this is actually how it works. a person learns all his life. you can close the topic. thank you for your help and answers

**Comment by ItsMitchh** [comment]
closed, not a bug^
