### ISSUE TITLE
onse per x songs not working

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#6003]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

0c938b2 (2023-01-08 4:24) • Docker • PHP 8.1

### What happened?

hello, i have one playlist of spots to play onse per 2 songs, but i have one oter playlist configured to play onse per 4. tht thing is the playlist that plays every 2 songs is playing after each song. i think these rules doesnt ignore gingle mode and consider them as songs.

**Comment by wegGehamstert** [comment]
Yes, can confirm this behaviour. It's very annoying. I hope there is a fix for it
