### ISSUE TITLE
Add Support for Google Analytics

### ISSUE THREAD

**Issue by jrsarath** [AzuraCast/AzuraCast#601]
Installation Method: Traditional
Host OS: Ubuntu 16.04

He there, 
This is not an issue..
I wanted to know if there are any possibilities to get analytics within google analytics ?

**Comment by jrsarath** [comment]
can anyone tell me where i can change the xml response for 
https://domain/radio/8000/admin/stats

**Comment by SlvrEagle23** [comment]
@jrsarath I assume when you refer to Google Analytics, you're referring to the public radio page? Or do you want to integrate Google Analytics directly with your radio listening traffic itself?

Your second question should likely be a separate issue, but I can tell you already that it does not appear to be currently possible to modify the Shoutcast internal files served by the radio binary, without replacing the entire Shoutcast DNAS binary itself.

**Comment by jrsarath** [comment]
@SlvrEagle23 I want to integrate Google analytics with radio listening traffic itself..
something interesting i found here.. https://coherent-receiver.com/google-analytics-and-icecast..
it works.. but with stock icecast config.. since azuracast has modified configs i was unable get it working with azuracast

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38908/add-support-for-google-analytics
