### ISSUE TITLE
Upcoming Song Cue Issue

### ISSUE THREAD

**Issue by rbarbier1967** [AzuraCast/AzuraCast#6010]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

When I go in to look at upcoming song cue I get the error 
Error at /var/azuracast/www/vendor/monolog/monolog/src/Monolog/DateTimeImmutable.php L35: Typed property Monolog\DateTimeImmutable::$useMicroseconds must not be accessed before initialization

**Comment by ItsMitchh** [comment]
Upstream issue, we have informed the developers of said software

**Comment by BusterNeece** [comment]
This is temporarily resolved on our end by hiding the AutoDJ queue log from the Upcoming Queue page. Once the upstream issue is fixed, we'll restore that functionality on our end.
