### ISSUE TITLE
Plethora of problems after update this morning

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#6015]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #fe2b44d (2023-01-12 3:13)

### What happened?

Updated to latest rolling release this morning (was 20 behind) and server returned with a slew of problems;

• Station showing offline
• Unspecified error showing intermittently
• Live streamer not displayed during live
• Upcoming queue not showing in AutoDJ
• Showing 0 Listeners above and stuck on 6 on SID 1 and 0 on SID 2
• LIVE BROADCAST resetting intermittently but streamer not disconnecting
• Audio stream cutting out at random for 1-2 seconds
Here's a few images showing what I see;
![Radio1](https://user-images.githubusercontent.com/66107794/212174088-ba030011-e45e-4675-8cd2-5b780fb89632.jpg)
![Radio2](https://user-images.githubusercontent.com/66107794/212174231-34267ffb-7b70-451b-b7de-75faf32102b6.jpg)
![Radio3](https://user-images.githubusercontent.com/66107794/212174324-2b8f387e-32ea-4ec1-89d9-9833fe9be311.jpg)
![Radio4](https://user-images.githubusercontent.com/66107794/212174432-9f973d0a-f7cc-420c-ab98-4fea1f4a2ec0.jpg)

ShoutCast log here (Liquid Log below;
[ShoutCast LOG.txt](https://github.com/AzuraCast/AzuraCast/files/10405735/ShoutCast.LOG.txt)

Please advise if anything needs be done at this end....

### Relevant log output

```shell
LIQUIDSOAP LOG...


2023/01/12 14:17:18 [playlist_jingles_festival:4] Could not resolve request: annotate:title="Yvan Daveluy",artist="ID",duration="59.00",song_id="de43765913facf728e77589445d8679a",media_id="1774",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="2.00",playlist_id="5",jingle_mode="true":media:Pub Festivals/yvan_-_daveluy.mp3.
2023/01/12 14:17:18 [clock.main:2] We must catchup 26.33 seconds!
2023/01/12 14:17:18 [input_streamer:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2023/01/12 14:17:19 [input_streamer:3] Buffer overrun: Dropping 0.01s. Consider increasing the max buffer size!
2023/01/12 14:17:19 [input_streamer:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2023/01/12 14:17:19 [input_streamer:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2023/01/12 14:17:19 [input_streamer:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2023/01/12 14:17:19 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/radio_des_festivals/media/Pub Festivals/yvan_-_daveluy.mp3"!
2023/01/12 14:17:19 [playlist_jingles_festival:4] Could not resolve request: annotate:title="Yvan Daveluy",artist="ID",duration="59.00",song_id="de43765913facf728e77589445d8679a",media_id="1774",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="2.00",playlist_id="5",jingle_mode="true":media:Pub Festivals/yvan_-_daveluy.mp3.
2023/01/12 14:17:19 [clock.main:2] We must catchup 26.49 seconds!
2023/01/12 14:17:19 [input_streamer:3] Buffer overrun: Dropping 0.02s. Consider increasing the max buffer size!
2023/01/12 14:17:19 [input_streamer:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2023/01/12 14:17:20 [input_streamer:3] Buffer overrun: Dropping 0.00s. Consider increasing the max buffer size!
2023/01/12 14:17:20 [input_streamer:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
2023/01/12 14:17:20 [input_streamer:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!


>>>>> THIS REPEATING AD INFINITUM <<<<<<
```

**Comment by ItsMitchh** [comment]
Split this issue up into multiple issues, we won't work on a 'mega' issue, include logs for each issue you are encountering.

**Comment by SpeedyCharly** [comment]
It cannot be split as the logs always repeat the same message ad infinitum  every 20 lines or so ... What would you want me to show???

**Comment by BusterNeece** [comment]
@SpeedyCharly You listed like 10 issues that are happening on the web UI, and you only showed the Liquidsoap logs. There's no way we can keep track of these as one major issue, and we have no idea if they're even the same problem.

You should be checking the web application logs or your browser console for information about what's going on with some of these errors. Clearly our entire local installations aren't broken or we wouldn't have shipped that Rolling Release version, so there's something different about your installation and it's not apparent from this post.

**Comment by SpeedyCharly** [comment]
Shoutcast log is also shown as a txt file, and it also repeats the same info every 20 lines or so

**Comment by BusterNeece** [comment]
@SpeedyCharly We're not here to debate the "one issue per issue" rule. It's a rule. Follow it.

Your web UI issues should be posted on their own and should have accompanying logs from the web application side or from your browser's inspect console / Network tab. With no logs or additional information, we can do absolutely nothing with that information.

Your broadcast problems may be explained literally in the error message itself ("try increasing the buffer").

**Comment by SpeedyCharly** [comment]
How can I split anything issue by issue when there is no specifically identifiable date to be extracted from the logs. 

The only buffer I know of is this one, and it's always been fine at 30 seconds...
![Radio5](https://user-images.githubusercontent.com/66107794/212187921-1a3272a9-78b3-4eb4-8873-dea0314b46bc.jpg)

**Comment by BusterNeece** [comment]
@SpeedyCharly Not gonna spend today arguing with you. If you fight us on this one more post, it'll be a permanent ban. You are warned.

Please report the web UI issues in a separate issue, accompanied by logs. There are logs for these issues, as I have said 3 times now, in the Application log (in System Debugger) and in your browser's Inspect console, specifically the Network tab. You haven't read my messages and just keep saying there isn't any other logs.

The broadcasting issues should be reported as their own GitHub issue.

Do not test our patience today.

**Comment by SpeedyCharly** [comment]
Not arguing, trying to understand what you need. I'm a radio operator, not a coder; I can read the logs just fine but, not knowing what does what, I cannot relate the info to any specific issue.  
For example, I can see reported errors in nginx log, but I have no idea what they affect...
[nginx log.txt](https://github.com/AzuraCast/AzuraCast/files/10406518/nginx.log.txt)

I can open the browser's Inspect console and look at the Network tab, but I have no idea what I'm looking at, or even where exactly I should look...
