### ISSUE TITLE
No metadata when using direct stream URL to any mount point type, except OGG Vorbis

### ISSUE THREAD

**Issue by guiltlab** [AzuraCast/AzuraCast#6019]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#5d1e46a (2023-01-08 2:26)

### What happened?

When I use my direct stream URL (e.g. `https://example.com/listen/<station name>/<mount point name>`) in an app like foobar2000, poweramp, sonos, etc... I don't get any metadata apart from Artist - Title (I suspect it actually comes from the "text" field and not really from artist and title fields) with AAC and MP3 streams. With Opus and FLAC, I don't even get Artist - Title, instead I get the station name. The only format where I do get all the metadata (for example: album name, genre) is OGG Vorbis. I use stock Icecast and Liquidsoap, no custom configuration.

Here is the result I get for the same song on foobar2000, using different mount points. The top row looks for TITLE, middle row looks for ARTIST and bottom row looks for ALBUM.

![Eqj5vt 1](https://user-images.githubusercontent.com/45518224/212373034-d1a473a8-d2c0-4cbf-acda-8f94ec52a024.jpg)

I have confirmed this also happens with the mp3 stream from the Azuracast test radio: https://demo.azuracast.com/public/azuratest_radio
If I download the playlist from the test radio, I get the same behaviour as the first example on the screenshot: only title and artist, even when the currently playing track does have album information (confirmed by checking https://demo.azuracast.com/api/nowplaying_static/azuratest_radio.json).

Thanks in advance for looking into it !

**Comment by BusterNeece** [comment]
Very, very likely a limitation of Liquidsoap and/or Icecast, not something we can control in our stack.

**Comment by guiltlab** [comment]
Thanks for your answer, this is unfortunate. Hopefully it will be changed upstream at some point.

**Comment by isAAAc** [comment]
same here, 
public azuracast say: Stream Offline (even there is some sound streamed), 
but the admin icecast webpage is up2date with the good track streamed, 
looks like azuracast can't update the good information in the player.

**Comment by isAAAc** [comment]
fixed on my side disabling autodj on the station :white_check_mark:

**Comment by gasguti** [comment]
I have the autodj disabled and have the same problem

**Comment by learntoswim** [comment]
I am also not getting any metadata in any app receiving the stream, even though `http://<myserver>/api/nowplaying` is showing detailed data. Autodj enabled or disabled.
