### ISSUE TITLE
Liquid Soap does not start when using docker-compose.override.yml to map a mounted SMB share

### ISSUE THREAD

**Issue by ebildebil** [AzuraCast/AzuraCast#6025]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #963e803 (2023-01-15 7:02) • Docker • PHP 8.2

### What happened?

Fresh install, both stable and then rolling release.
Reverse proxy via Nginx proxy manager. Default ports are changed.

None of the radio channels start. I can access both the admin console and the station playback page externally.
Tried forwarding ports from router to the instance, and also forcing ssl to use ssl port.

**Error When Trying to Start AutoDJ (Liquidsoap)**
SupervisorException at /var/azuracast/www/src/Exception/SupervisorException.php L69: station_2:station_2_backend encountered an error: SpawnErrorException

In the log, below  error repeats:
 **Error while trying to bind server/telnet socket: Operation not permitted in bind()
exception: Error while trying to bind server/telnet socket: Operation not permitted in bind()
Raised at Server.start_socket in file "tools/server.ml", line 396, characters 16-59
Called from Server.start in file "tools/server.ml", line 464, characters 26-41
Called from Main.(fun).main in file "main.ml", line 537, characters 8-23
Called from Dtools__Dtools_impl.Init.main.thread in file "src/dtools_impl.ml", line 497, characters 8-12
2023/01/15 20:54:08 [main:3] Shutdown started!**

**Liquid soap config:**
# WARNING! This file is automatically generated by AzuraCast.
# Do not update it directly!

init.daemon.set(false)
init.daemon.pidfile.path.set("/var/azuracast/stations/old_hindi/config/liquidsoap.pid")

log.stdout.set(true)
log.file.set(false)

settings.server.log.level.set(4)

settings.server.socket.set(true)
settings.server.socket.permissions.set(0o660)
settings.server.socket.path.set("/var/azuracast/stations/old_hindi/config/liquidsoap.sock")

settings.harbor.bind_addrs.set(["0.0.0.0"])

settings.tag.encodings.set(["UTF-8","ISO-8859-1"])
settings.encoder.metadata.export.set(["artist","title","album","song"])

setenv("TZ", "UTC")

autodj_is_loading = ref(true)
ignore(autodj_is_loading)

autodj_ping_attempts = ref(0)
ignore(autodj_ping_attempts)

# Track live-enabled status.
live_enabled = ref(false)
ignore(live_enabled)

# Track live transition for crossfades.
to_live = ref(false)
ignore(to_live)

azuracast_api_url = "http://127.0.0.1:6010/api/internal/2/liquidsoap"
azuracast_api_key = "(PASSWORD)"

def azuracast_api_call(~timeout_ms=2000, url, payload) =
    full_url = "#{azuracast_api_url}/#{url}"
    
    log("API #{url} - Sending POST request to '#{full_url}' with body: #{payload}")
    try
        response = http.post(full_url,
            headers=[
                ("Content-Type", "application/json"),
                ("User-Agent", "Liquidsoap AzuraCast"),
                ("X-Liquidsoap-Api-Key", "#{azuracast_api_key}")
            ],
            timeout_ms=timeout_ms,
            data=payload
        )
        
        log("API #{url} - Response (#{response.status_code}): #{response}")
        "#{response}"
    catch err do
        log("API #{url} - Error: #{error.kind(err)} - #{error.message(err)}")
        "false"
    end
end

station_media_dir = "/var/azuracast/stations/old_hindi/media"
def azuracast_media_protocol(~rlog=_,~maxtime=_,arg) =
    ["#{station_media_dir}/#{arg}"]
end

add_protocol(
    "media",
    azuracast_media_protocol,
    doc="Pull files from AzuraCast media directory.",
    syntax="media:uri"
)

playlist_all_tracks = playlist(id="playlist_all_tracks",mime_type="audio/x-mpegurl",mode="randomize",reload_mode="watch","/var/azuracast/stations/old_hindi/playlists/playlist_all_tracks.m3u")
playlist_all_tracks = cue_cut(id="cue_playlist_all_tracks", playlist_all_tracks)

# Standard Playlists
radio = random(id="standard_playlists", weights=[3], [playlist_all_tracks])

requests = request.queue(id="requests")
requests = cue_cut(id="cue_requests", requests)
radio = fallback(id="requests_fallback", track_sensitive = true, [requests, radio])

interrupting_queue = request.queue(id="interrupting_requests")
interrupting_queue = cue_cut(id="cue_interrupting_requests", interrupting_queue)
radio = fallback(id="interrupting_fallback", track_sensitive = false, [interrupting_queue, radio])

def add_skip_command(s) =
    def skip(_) =
        source.skip(s)
        "Done!"
    end
    
    server.register(namespace="radio", usage="skip", description="Skip the current song.", "skip",skip)
end

add_skip_command(radio)

def live_aware_crossfade(old, new) =
    if !to_live then
        # If going to the live show, play a simple sequence
        sequence([fade.out(old.source),fade.in(new.source)])
    else
        # Otherwise, use the smart transition
        cross.simple(old.source, new.source, fade_in=2.00, fade_out=2.00)
    end
end

radio = cross(minimum=0., duration=3.00, live_aware_crossfade, radio)

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

# Apply amplification metadata (if supplied)
radio = amplify(override="liq_amplify", 1., radio)

# Replaygain Metadata
enable_replaygain_metadata()
radio = replaygain(radio)

radio = fallback(id="safe_fallback", track_sensitive = false, [radio, single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")])

# Send metadata changes back to AzuraCast
last_title = ref("")
last_artist = ref("")

def metadata_updated(m) =
    def f() =
        if (m["title"] != !last_title or m["artist"] != !last_artist) then
            last_title := m["title"]
            last_artist := m["artist"]
            
            j = json()
            
            if (m["song_id"] != "") then
                j.add("song_id", m["song_id"])
                j.add("media_id", m["media_id"])
                j.add("playlist_id", m["playlist_id"])
            else
                j.add("artist", m["artist"])
                j.add("title", m["title"])
            end
            
            _ = azuracast_api_call(
                "feedback",
                json.stringify(j)
            )
        end
    end
    
    thread.run(f)
end

radio.on_metadata(metadata_updated)

# Handle "Jingle Mode" tracks by replaying the previous metadata.
last_metadata = ref([])
def handle_jingle_mode(m) = 
    if (m["jingle_mode"] == "true") then
        !last_metadata    
    else
        last_metadata := m
        m
    end
end

radio = metadata.map(update=false, strip=true, handle_jingle_mode, radio)

# Local Broadcasts
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), id="local_1", host = "127.0.0.1", port = 14365, password = "(PASSWORD)", mount = "/oldhindi", name = "Old Hindi", description = "Old Hindi songs!!", genre = "", public = false, encoding = "UTF-8", radio)

# HLS Broadcasting
aac_lofi = %ffmpeg(
    format="mpegts",
    %audio(
        codec="aac",
        samplerate=44100,
        channels=2,
        b="48k",
        profile="aac_low"
    )
)
aac_midfi = %ffmpeg(
    format="mpegts",
    %audio(
        codec="aac",
        samplerate=44100,
        channels=2,
        b="96k",
        profile="aac_low"
    )
)
aac_hifi = %ffmpeg(
    format="mpegts",
    %audio(
        codec="aac",
        samplerate=44100,
        channels=2,
        b="192k",
        profile="aac_low"
    )
)
hls_streams = [("aac_lofi", aac_lofi), ("aac_midfi", aac_midfi), ("aac_hifi", aac_hifi)]

def hls_segment_name(~position,~extname,stream_name) =
    timestamp = int_of_float(time())
    duration = 4
    "#{stream_name}_#{duration}_#{timestamp}_#{position}.#{extname}"
end

output.file.hls(playlist="live.m3u8",
    segment_duration=4.0,
    segments=5,
    segments_overhead=2,
    segment_name=hls_segment_name,
    persist_at="/var/azuracast/stations/old_hindi/config/hls.config",
    "/var/azuracast/stations/old_hindi/hls",
    hls_streams,
    radio
)

# Remote Relays

### Relevant log output

```shell
2023/01/15 21:01:18 [main:3] or to join the slack chat at <http://slack.liquidsoap.info>.
2023/01/15 21:01:18 [main:3] 
2023/01/15 21:01:18 [main:3] Please send any bug report or feature request
2023/01/15 21:01:18 [main:3] at <https://github.com/savonet/liquidsoap/issues>.
2023/01/15 21:01:18 [main:3] 
2023/01/15 21:01:18 [main:3] We hope you enjoy this snapshot build of Liquidsoap!
2023/01/15 21:01:18 [main:3] 
2023/01/15 21:01:19 [clock:3] Using native (high-precision) implementation for latency control
2023/01/15 21:01:20 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz main.
2023/01/15 21:01:20 [frame:3] Video frame size set to: 1280x720
2023/01/15 21:01:20 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2023/01/15 21:01:20 [frame:3] Targeting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2023/01/15 21:01:20 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2023/01/15 21:01:20 [sandbox:3] Sandboxing disabled
2023/01/15 21:01:20 [video.converter:3] Using preferred video converter: ffmpeg.
2023/01/15 21:01:20 [audio.converter:3] Using samplerate converter: libsamplerate.
2023/01/15 21:01:28 >>> LOG START
init: exception encountered during main phase:
  Error while trying to bind server/telnet socket: Operation not permitted in bind()
exception: Error while trying to bind server/telnet socket: Operation not permitted in bind()
Raised at Server.start_socket in file "tools/server.ml", line 396, characters 16-59
Called from Server.start in file "tools/server.ml", line 464, characters 26-41
Called from Main.(fun).main in file "main.ml", line 537, characters 8-23
Called from Dtools__Dtools_impl.Init.main.thread in file "src/dtools_impl.ml", line 497, characters 8-12
2023/01/15 21:01:28 [main:3] Shutdown started!
2023/01/15 21:01:28 [threads:3] Shutting down scheduler...
2023/01/15 21:01:28 [threads:3] Scheduler shut down.
2023/01/15 21:01:28 [main:3] Cleaning downloaded files...
2023/01/15 21:01:28 [main:3] Freeing memory...
2.2 dssi=0.1.5 tsdl=v0.9.9 tsdl-ttf=0.3.2 tsdl-image=0.3.2 camlimages=4.2.6 camlimages.freetype=5.0.4 cohttp-lwt-unix=5.0.0 prometheus-app=1.2 srt.constants=0.2.2 srt.types=0.2.2 srt.stubs=0.2.2 srt.stubs.locked=0.2.2 srt=0.2.2 lo=0.2.0 gd=1.0a5 irc-client-unix=[unspecified]
2023/01/15 21:01:26 [main:3] 
2023/01/15 21:01:26 [main:3] DISCLAIMER: This version of Liquidsoap has been
2023/01/15 21:01:26 [main:3] compiled from a snapshot of the development code.
2023/01/15 21:01:26 [main:3] As such, it should not be used in production
2023/01/15 21:01:26 [main:3] unless you know what you are doing!
2023/01/15 21:01:26 [main:3] 
2023/01/15 21:01:26 [main:3] We are, however, very interested in any feedback
2023/01/15 21:01:26 [main:3] about our development code and committed to fix
2023/01/15 21:01:26 [main:3] issues as soon as possible.
2023/01/15 21:01:26 [main:3] 
2023/01/15 21:01:26 [main:3] If you are interested in collaborating to
2023/01/15 21:01:26 [main:3] the development of Liquidsoap, feel free to
2023/01/15 21:01:26 [main:3] drop us a mail at <savonet-devl@lists.sf.net>
2023/01/15 21:01:26 [main:3] or to join the slack chat at <http://slack.liquidsoap.info>.
2023/01/15 21:01:26 [main:3] 
2023/01/15 21:01:26 [main:3] Please send any bug report or feature request
2023/01/15 21:01:26 [main:3] at <https://github.com/savonet/liquidsoap/issues>.
2023/01/15 21:01:26 [main:3] 
2023/01/15 21:01:26 [main:3] We hope you enjoy this snapshot build of Liquidsoap!
2023/01/15 21:01:26 [main:3] 
2023/01/15 21:01:27 [clock:3] Using native (high-precision) implementation for latency control
2023/01/15 21:01:28 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz main.
2023/01/15 21:01:28 [frame:3] Video frame size set to: 1280x720
2023/01/15 21:01:28 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2023/01/15 21:01:28 [frame:3] Targeting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2023/01/15 21:01:28 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2023/01/15 21:01:28 [sandbox:3] Sandboxing disabled
2023/01/15 21:01:28 [video.converter:3] Using preferred video converter: ffmpeg.
2023/01/15 21:01:28 [audio.converter:3] Using samplerate converter: libsamplerate.
2023/01/15 21:01:36 >>> LOG START
2023/01/15 21:01:34 [main:3] Liquidsoap 2.1.4+git@f845354f8
2023/01/15 21:01:34 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] posix-time2=2.0.0 pcre=7.5.0 sedlex=3.0 menhirLib=20220210 curl=0.9.2 uri=4.2.0 memtrace=v0.2.2 mem_usage=0.0.4 dtools=0.4.4 duppy=0.9.3 cry=0.6.8 mm=0.8.2 xmlplaylist=0.1.5 lastfm=0.3.3 ogg=0.7.3 ogg.decoder=0.7.3 vorbis=0.8.1 vorbis.decoder=0.8.1 opus=0.2.3 opus.decoder=0.2.3 speex=0.4.1 speex.decoder=0.4.1 mad=0.5.2 flac=0.3.1 flac.ogg=0.3.1 flac.decoder=0.3.1 dynlink=[distributed with Ocaml] lame=0.3.6 shine=0.2.3 frei0r=0.1.2 fdkaac=0.3.2 theora=0.4.0 theora.decoder=0.4.0 ffmpeg=1.1.6 bjack=0.1.6 alsa=0.3.0 ao=0.2.4 samplerate=0.1.6 taglib=0.3.10 ssl=0.5.11 magic=0.7.3 camomile=1.0.2 inotify=2.0-58-g1beb568 faad=0.5.2 soundtouch=0.1.9 portaudio=0.2.3 pulseaudio=0.1.5 ladspa=0.2.2 dssi=0.1.5 tsdl=v0.9.9 tsdl-ttf=0.3.2 tsdl-image=0.3.2 camlimages=4.2.6 camlimages.freetype=5.0.4 cohttp-lwt-unix=5.0.0 prometheus-app=1.2 srt.constants=0.2.2 srt.types=0.2.2 srt.stubs=0.2.2 srt.stubs.locked=0.2.2 srt=0.2.2 lo=0.2.0 gd=1.0a5 irc-client-unix=[unspecified]
2023/01/15 21:01:34 [main:3] 
2023/01/15 21:01:34 [main:3] DISCLAIMER: This version of Liquidsoap has been
2023/01/15 21:01:34 [main:3] compiled from a snapshot of the development code.
2023/01/15 21:01:34 [main:3] As such, it should not be used in production
2023/01/15 21:01:34 [main:3] unless you know what you are doing!
2023/01/15 21:01:34 [main:3] 
2023/01/15 21:01:34 [main:3] We are, however, very interested in any feedback
2023/01/15 21:01:34 [main:3] about our development code and committed to fix
2023/01/15 21:01:34 [main:3] issues as soon as possible.
2023/01/15 21:01:34 [main:3] 
2023/01/15 21:01:34 [main:3] If you are interested in collaborating to
2023/01/15 21:01:34 [main:3] the development of Liquidsoap, feel free to
2023/01/15 21:01:34 [main:3] drop us a mail at <savonet-devl@lists.sf.net>
2023/01/15 21:01:34 [main:3] or to join the slack chat at <http://slack.liquidsoap.info>.
2023/01/15 21:01:34 [main:3] 
2023/01/15 21:01:34 [main:3] Please send any bug report or feature request
2023/01/15 21:01:34 [main:3] at <https://github.com/savonet/liquidsoap/issues>.
2023/01/15 21:01:34 [main:3] 
2023/01/15 21:01:34 [main:3] We hope you enjoy this snapshot build of Liquidsoap!
2023/01/15 21:01:34 [main:3] 
2023/01/15 21:01:35 [clock:3] Using native (high-precision) implementation for latency control
2023/01/15 21:01:36 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz main.
2023/01/15 21:01:36 [frame:3] Video frame size set to: 1280x720
2023/01/15 21:01:36 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2023/01/15 21:01:36 [frame:3] Targeting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2023/01/15 21:01:36 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2023/01/15 21:01:36 [sandbox:3] Sandboxing disabled
2023/01/15 21:01:36 [video.converter:3] Using preferred video converter: ffmpeg.
2023/01/15 21:01:36 [audio.converter:3] Using samplerate converter: libsamplerate.
init: exception encountered during main phase:
  Error while trying to bind server/telnet socket: Operation not permitted in bind()
exception: Error while trying to bind server/telnet socket: Operation not permitted in bind()
Raised at Server.start_socket in file "tools/server.ml", line 396, characters 16-59
Called from Server.start in file "tools/server.ml", line 464, characters 26-41
Called from Main.(fun).main in file "main.ml", line 537, characters 8-23
Called from Dtools__Dtools_impl.Init.main.thread in file "src/dtools_impl.ml", line 497, characters 8-12
2023/01/15 21:01:36 [main:3] Shutdown started!
2023/01/15 21:01:36 [threads:3] Shutting down scheduler...
2023/01/15 21:01:36 [threads:3] Scheduler shut down.
2023/01/15 21:01:36 [main:3] Cleaning downloaded files...
2023/01/15 21:01:36 [main:3] Freeing memory...
```

**Comment by ebildebil** [comment]
I wanted to post an update.
I have tried reinstalling over 20 times. Hypervisor  is Hyper-v. Tried both Ubuntu server and also Debian 11. 
All times, I had mounted an SMB share via FStab.
This was done via the docker-compose.override.yml
Everytime i had the same error and liquidsoap would not start.

I finally removed docker-compose.override.yml and it started.

Perhaps I was mounting it incorrectly. 
below is the FSTAB entry:
//192.168.xx.xx/xxx/yyy /var/azuracast/media cifs username=xxxxx,password=xxxxxxx,file_mode=0777,dir_mode=0777,rw,nofail 0 0

Is there something wrong with this?

If possible I really would like to mount my media files from my nas.

**Comment by Vilhjalmr26** [comment]
I have this same issue.  Can confirm it is having the SMB share passed through that is the problem.  
in my vm had SMB share mounted to /media/Radio, made a new folder /media/Radio2, copied the station adn media files over into the local, and then updated the docker-compose.override.yml to point to the Radio2 folder instead of Radio and now it is working.  

This shows that mounting the path in docker-compose.override.yml is fine, and having a smb share mounted in the system are fine, but mounting paths within the SMB share to the docker-compose.override.yml is the problem.
I use the follownig for my FSTAB entry:
//192.168.xx.xx/xxxx   /media/Radio    cifs    credentials=/path/to/.smbcredentials,uid=1000,gid=1000,nounix,iocharset=utf8,file_mode=0775,dir_mode=0775  0       0

Any help on this would be greatly appreciated as I too would really like to leave management of my media on a share.

**Comment by ebildebil** [comment]
Unsolved.

**Comment by RM-FM** [comment]
I have the same problem. Station was created and songs imported perfectly fine from mounted storage paths. But the station won't start anymore. I tried to restart all station using CLI with below result...

![Bildschirmfoto 2023-11-25 um 20 43 01](https://github.com/AzuraCast/AzuraCast/assets/40538914/b0739cb8-c678-4910-8ff8-4abe2834b95a)
