### ISSUE TITLE
Can't update Image on media file  AzuraCast • Rolling Release #08de0f9 (2022-12-26 18:14)

### ISSUE THREAD

**Issue by ChandigarIT** [AzuraCast/AzuraCast#6027]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #08de0f9 (2022-12-26 18:14)

### What happened?

When I try to upload an image to a media file, after I have selected the jpeg, the name is in the area next to the paper clip, but the picture does not upload. 

**I am following exactly the same process as in the Podcast file area, which works fine.**

![Screenshot 2023-01-16 at 17 46 17](https://user-images.githubusercontent.com/108827431/212739234-b63e5784-a2a8-4b0c-ab39-3a2b1fbaaa03.png)

There is no button for "upload" or "cancel" any more.

![old upload](https://user-images.githubusercontent.com/108827431/212739529-d9e318ad-69f4-45e8-94b6-b09a61312f92.png)

Thanks for your help.

**Comment by BusterNeece** [comment]
@ChandigarIT You should update your Rolling Release to the latest, where this issue should be fixed.

**Comment by BusterNeece** [comment]
@ChandigarIT This should be its own brand new GitHub issue if you don't mind.

**Comment by ChandigarIT** [comment]
Buster

Reported as https://github.com/AzuraCast/AzuraCast/issues/6884

Thanks,

Malcolm
