### ISSUE TITLE
Metadata issues when going live as an end user

### ISSUE THREAD

**Issue by DJEclypse** [AzuraCast/AzuraCast#6031]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

the latest rolling release

### What happened?

When i use radiocaster to stream and connect to azurast server it doesnt show the metadata i have set in the software all i get is live broadcast where the djs name should be so i tried butt broadcast using this tool and the same issue just says live broadcast where the dj name should be however if i go to the streaming tab of butt and set the update song name delay to 8 seconds butt will delay title sending to azuracast panel for 8 seconds and then title will display with the accociated metadata the thing is we should have to set butt to delay title sending for 8 second we should be able to instantly push metadata title and set it to instant sending please could this issue be resolved as soon as possible as its a real headache as my djs use radiocaster and not butt for treaming which pushes titles instantly from metadata thus azuracast not showing any metadata at all here is a vid of what i mean with butt

https://user-images.githubusercontent.com/122891217/212937477-abf9dd9b-073f-4e7e-af6e-0ce8fece41f9.mp4

**Comment by DJEclypse** [comment]
When i use radiocaster to stream and connect to azurast server it doesnt show the metadata i have set in the software all i get is live broadcast where the djs name should be so i tried butt broadcast using this tool and the same issue just says live broadcast where the dj name should be however if i go to the streaming tab of butt and set the update song name delay to 8 seconds butt will delay title sending to azuracast panel for 8 seconds and then title will display with the accociated metadata the thing is we should have to set butt to delay title sending for 8 second we should be able to instantly push metadata title and set it to instant sending please could this issue be resolved as soon as possible as its a real headache as my djs use radiocaster and not butt for treaming which pushes titles instantly from metadata thus azuracast not showing any metadata at all here is a vid of what i mean with butt

https://mega.nz/file/Cgw1EBBT#89-S545Qmzoq4ej6PWDdyPUAZ-HcTVDCEx3zNo5RnPs

**Comment by DJEclypse** [comment]
Ok thanks for your quick answer my friend if anyone else has anything to add to this please do so thanks

**Comment by DJEclypse** [comment]
HI bro not sure did you check my video that explains everything thats happening with my issue as an end user

**Comment by DJEclypse** [comment]
Got my provider to change to change installation to stable and it seems its this latest version of azuracast as last version the metadata titles showed perfectly please could we get a FIX for this ?

**Comment by DJEclypse** [comment]
BUMP ...

**Comment by BusterNeece** [comment]
@DJEclypse It has long, long, long been a known issue that the initial metadata sent via a live connection doesn't make it through to AzuraCast, and instead it's the first metadata _update_ that makes it through.

This is a limitation of Liquidsoap's implementation of the Shoutcast/Icecast protocol, and has unfortunately been a known issue for quite some time now.

There is nothing that we've done lately to cause this issue; the only change we recently made is setting the metadata to "Live Broadcast" if no metadata exists on the stream but a live DJ is connected, to avoid it just showing the AutoDJ metadata instead in that gap.

**Comment by DJEclypse** [comment]
Ah ok thanks for your answer i tested azuracast from 2 versions ago v0.17.4 Stable and it doesnt have the same problem the metadata actually works it just the latest stable version v0.17.6 Stable and rolling release thats having the pushing metadata issue so im not sure whats going on there mate but i hope you can fix it becaus 2 versions ago it was working as i have older panel set up and latest one too

**Comment by BusterNeece** [comment]
@DJEclypse We can't just "fix it" without being able to identify the specifics of the issue and reproduce it directly. Additional logs may be helpful, as well as knowing exactly what versions of what software trigger the issue. If it's commercial software, it'll be even harder for us to reproduce on account of not having access to the software.

Like I said, this issue is also "upstream" from us in the form of a long known Liquidsoap limitation, so it may very well end up being something that needs to be fixed on their end, not ours.

**Comment by DJEclypse** [comment]
Ok well ive tested butt broadcasting siftware and radiocaster when i delay sedning metadata with butt for 8 seconds the latest version of azura panel pipcks up the metadata and when i turn the delay back to 0 it doesnt and radiocaster doesnt have a sending metadata delay setting so cant be done but what i dont get is why the older version of your panel sends metadata without setting a delay on butt whereas latest version doesnt

**Comment by DJEclypse** [comment]
I am an end user and cannot provide the things your asking me for but i have got hold of my provider and am hoping he can continue this chat here with you all i can say is what i experience as an end user of the panel

**Comment by DJEclypse** [comment]
If you need a video of the problem sending using the old version of azuracast with metadata working and with newer panel with it not please let me know in fact ill post it here now for you to see thanks

https://user-images.githubusercontent.com/122891217/214397077-07aa0259-f81c-4dbd-ab3a-1f7d8632ec08.mp4

**Comment by DJEclypse** [comment]
https://mega.nz/file/bohlmKiT#aPFVszI9Fx3WFVyDwkyufIxMzm3-CVkx4sXXJkATXPg
