### ISSUE TITLE
high cpu consumption and showing offline radio

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#6035]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #4c59ad5 (2023-01-18 5:53) • Docker • PHP 8.2

### What happened?

I was USING the stable version which already had this problem, so I updated to the roling version and it still remains.
It's something very strange, only the station that has the offline error has process usage at 100%, the other stations are normal. This station is also "locking" the audio.
I already restarted, I reduced the playlist and even so this problem ends up returning in other stations. No station has LS file change. All standard.

https://prnt.sc/PieFQEu6vITU

### Relevant log output

```shell
2023/01/18 23:39:48 [local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2023/01/18 23:39:48 [local_1:2] Connection failed: 403, Mountpoint in use (HTTP/1.0)
2023/01/18 23:39:48 [local_1:3] Will try again in 3.00 sec.
2023/01/18 23:39:50 [clock.main:2] We must catchup 1.04 seconds!
2023/01/18 23:39:51 [clock.main:2] We must catchup 1.65 seconds!
2023/01/18 23:39:52 [local_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
2023/01/18 23:39:52 [local_1:3] Connection setup was successful.
2023/01/18 23:39:52 [clock.main:2] We must catchup 2.35 seconds!
2023/01/18 23:39:53 [clock.main:2] We must catchup 3.00 seconds!
2023/01/18 23:39:54 [clock.main:2] We must catchup 3.57 seconds!
2023/01/18 23:39:55 [clock.main:2] We must catchup 4.13 seconds!
2023/01/18 23:39:56 [clock.main:2] We must catchup 4.72 seconds!
2023/01/18 23:39:57 [clock.main:2] We must catchup 5.31 seconds!
2023/01/18 23:39:58 [clock.main:2] We must catchup 5.89 seconds!
2023/01/18 23:39:59 [clock.main:2] We must catchup 6.46 seconds!
2023/01/18 23:40:00 [clock.main:2] We must catchup 7.04 seconds!
2023/01/18 23:40:02 [clock.main:2] We must catchup 7.76 seconds!
2023/01/18 23:40:03 [clock.main:2] We must catchup 8.46 seconds!
```

**Comment by bofh666** [comment]
> Update: NVM. I had to play with some settings to get the stations to appear online again.

Could you please describe which settings did you set to which values to get your station back online?
