### ISSUE TITLE
NotWritableException at /var/azuracast/www/vendor/intervention/image/src/Intervention/Image/Image.php L150: Can't write image data to path

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#6037]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

xx

### What happened?

I'm trying to update the favicon and it's giving permission error.

### Relevant log output

```shell
NotWritableException at /var/azuracast/www/vendor/intervention/image/src/Intervention/Image/Image.php L150: Can't write image data to path (/var/azuracast/uploads/browser_icon/original.png
```

**Comment by Marcioghiraldelli** [comment]
well, if it's intentional, why is there an option to change it then? If you have the option there and there's nothing saying that you shouldn't change the favicon, I don't understand. I like to modify the dashboard css to my liking.

**Comment by BusterNeece** [comment]
@gunsar The Icecast thing isn't even related to this issue at all. They also just released that stable Icecast version like 3 days ago. Be patient, please.
