### ISSUE TITLE
ERROR: for stations  Cannot start service stations: container is marked for removal and cannot be started

### ISSUE THREAD

**Issue by Yusadolat** [AzuraCast/AzuraCast#604]
- **Installation Method:** 
- **Host OS (if using Docker):** 

**Describe the issue in full detail, including screenshots if possible:**
I installed the Azuracast on the station 3 days Ago and Everything works fine, One checking today I got,
`This page isn’t working
server3.dnstreams.com.ng is currently unable to handle this request.
HTTP ERROR 500`
So I log in through ssh and tried restart docker, below is the error I got in the 
![azura_server3_error](https://user-images.githubusercontent.com/10975011/40984678-5ba83648-68da-11e8-8272-730bd9589163.png)
screenshot. Thanks

**Comment by SlvrEagle23** [comment]
@Yusadolat Try just shutting down and restarting the services:

```
docker-compose down
docker-compose up -d
```

the first command should pull down any "marked for removal" containers. You may also just need to restart the system to fix any deadlock conditions if that doesn't work.

**Comment by Yusadolat** [comment]
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by SlvrEagle23** [comment]
@Yusadolat That's something wrong with your Docker installation. You may be able to fix it by rebooting or running something akin to `service docker start` (if applicable), but troubleshooting Docker is outside the scope of AzuraCast itself.

**Comment by Yusadolat** [comment]
I just tried it now, got `Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
`

**Comment by SlvrEagle23** [comment]
@Yusadolat You're going to have to be resourceful on this one. Run the command it says to run, see if there's any insight into what's causing the problem.

**Comment by Yusadolat** [comment]
`docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Tue 2018-06-05 15:30:57 UTC; 4min 53s ago
     Docs: https://docs.docker.com
  Process: 24932 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 24932 (code=exited, status=1/FAILURE)

Jun 05 15:30:57 dawahnigeria systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jun 05 15:30:57 dawahnigeria systemd[1]: Failed to start Docker Application Container Engine.
Jun 05 15:30:57 dawahnigeria systemd[1]: docker.service: Unit entered failed state.
Jun 05 15:30:57 dawahnigeria systemd[1]: docker.service: Failed with result 'exit-code'.
Jun 05 15:30:57 dawahnigeria systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Jun 05 15:30:57 dawahnigeria systemd[1]: Stopped Docker Application Container Engine.
Jun 05 15:30:57 dawahnigeria systemd[1]: docker.service: Start request repeated too quickly.
Jun 05 15:30:57 dawahnigeria systemd[1]: Failed to start Docker Application Container Engine.

`

**Comment by SlvrEagle23** [comment]
@Yusadolat Like I said, this issue is one with Docker, not one with AzuraCast. I don't build or maintain Docker, and it's a huge project that's impossible for me to diagnose and troubleshoot as a single developer. You'll have to consult Docker's own Github repository and follow their own troubleshooting steps for assistance.

**Comment by Yusadolat** [comment]
Hello there,
I was able to fix and All working fine but I'm still getting This page isn’t working
server3.dnstreams.com.ng is currently unable to handle this request.
HTTP ERROR 500 on station page. What do you suggest?
