### ISSUE TITLE
Custom error file, page are gone

### ISSUE THREAD

**Issue by 01123581321345589144233** [AzuraCast/AzuraCast#6041]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

AzuraCast • Rolling Release #fed474b (2023-01-23 3:11)

### What happened?

Hi, i try to update my custom error file but cannot find the page in my default radio mount.
I can see the intro and it works well, but not the error page hm???

**Comment by BusterNeece** [comment]
@01123581321345589144233 The page should be "Custom Fallback File" under the "Broadcasting" submenu. Is there an error when you see it?
