### ISSUE TITLE
Station Default Album Art URL missing?

### ISSUE THREAD

**Issue by PeWe79** [AzuraCast/AzuraCast#6042]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #fed474b

### What happened?

Today I'm update to Rolling Release #fed474b  but Station Default Album Art URL was gone or missing?

**Comment by BusterNeece** [comment]
@PeWe79 Not removed, just moved! If you look under the Public Pages section of the station profile, you'll see "Station Branding", where you can now upload custom per-station album art, public page background, and custom public page CSS/JS.

**Comment by PeWe79** [comment]
Hi @BusterNeece cooll. Thanks
