### ISSUE TITLE
AutoDJ - (Time-)Schedule does not work

### ISSUE THREAD

**Issue by traplinefm** [AzuraCast/AzuraCast#6044]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.6 Stable • Docker • PHP 8.1

### What happened?

Hey,

**I have discovered the following error:**

If I run a playlist with AutoDJ and then schedule another playlist with an MP3 at a certain time, AutoDJ simply does not play it. I have tried changing several settings but to no avail. I think this is a system error. Maybe this can be fixed please?

If I let the AutoDJ play music and then schedule a radio interview at a certain time, unfortunately it doesn't work... just won't play...?

Please provide feedback.

Best regards
Luca :)

**Comment by paulcjkp** [comment]
See https://github.com/AzuraCast/AzuraCast/issues/5752

This should be fixed in the latest stable (v0.17.7) and rolling release.

**Comment by gasguti** [comment]
Try restarting autodj after every change, if it does not work, try disabling Avoid Duplicate Artists/Titles option in the playlists
