### ISSUE TITLE
Metadata update when connected live

### ISSUE THREAD

**Issue by psduk1** [AzuraCast/AzuraCast#6049]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #aae06e2 (2023-01-27 9:42) 

### What happened?

When a DJ Connects live the metadata does not always update correctly just shows "LIVE" occasionally it displays correctly but not very often.
Is there a way to pull the metadata from the live connection 10 seconds after the live connection as if a delay is set of 10 secs in butt it works.
would be good if you could add a delay in liquidsoap config to allow for this.

**Comment by DJEclypse** [comment]
I second this problem i think a delay title setting of 2 and 4 and 6 and 8 and 10 seconds should be added to the azuracast software panel to circumvent this issue as when i set a delay of title sending in broadcast using this tool to between 8 and 10 seconds the metadata starts to work again on azuracast and sends to icecast and shoutcast so if this could be implimented that would be excellent and problem solved FINALLY !!

**Comment by psduk1** [comment]
Any ideas to a fix for the issue ?
As there seems to be no response or help
