### ISSUE TITLE
QUESTION: Radio with talkshows and jingles 

### ISSUE THREAD

**Issue by ohld** [AzuraCast/AzuraCast#605]
Hi @SlvrEagle23! I just found your repo and it looks like the most fanciable online-radio software I've ever seen!

I'm the admin of our local online-radio radio.mipt.ru and we are using icecast now. I'm thinking about to start using your software. Can you please help me to answer if all our requirements can be handled with AzuraCast now or in near future?

I can describe our architecture this way:
<img width="461" alt="image" src="https://user-images.githubusercontent.com/5613295/41035122-5a75762c-6994-11e8-96ac-15186827a304.png">

Our radio stream contains three types of a content: songs, jingles and live talk shows stream.

* We use [Radiologik](http://www.radiologik.com) for our Mac mini to stream different playlists for a different daytime (for example we have calm and nice songs for mornings and dance music for a late evenings). All our songs base is located in Mac mini hard disk (it can be relocated to AzuraCast server if needed). Radiologik send audio to [Nicecast](https://rogueamoeba.com/nicecast/) macOS app (even if it is retired now) which sends audio stream to Icecast mount.
* We recorded a lot of jingles (5-10 seconds) and use Radiologik Scheduler to play a random jingle approximately every 5 minute between the songs.
* Sometimes we have talkshows. For know to stream talkshows we just change input source in Nicecast macOS app from Radiologik to audio card device.

Can anything I've mentioned be done with AzuraCast? If yes can you please help me to start using your software because It looks like all-in-one turnkey solution, moreover this software is highly maintained live project (compared to Icecast for example). I just need to make sure that anything I've mentioned can be done with AzuraCast. Thanks.

**Comment by ohld** [comment]
So if your software has the ability to 
* create scheduled playlists, 
* play jingles between songs,
* play live talkshow stream on top of songs stream

**Comment by xewl** [comment]
Azuracast is a management layer on top of Icecast, SHOUTcast and [Liquidsoap](http://savonet.sourceforge.net/).

It'll install those services (or have them available in the docker image), but you can connect to an existing instance of Ice/SHOUT too.

So to answer the points in your comment,
• The AutoDJ feature can handle this, to a very minimal but useful enough state, and it can be maintained via the Playlists feature.
• Also a playlist type.
• DJ Accounts are possible, You can also take over the stream by the credentials it provides under a Stations' Profile.

You can check out the [demo](http://azuracast.com/demo.html) to confirm your needs.

**Comment by ohld** [comment]
thanks
