### ISSUE TITLE
Debian 11 AzuraCast docker installation

### ISSUE THREAD

**Issue by PManuel1986** [AzuraCast/AzuraCast#6052]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

AzuraCast • Rolling Release #aae06e2 (2023-01-27 9:42) • Docker • PHP 8.2

### What happened?

Debian 11 AzuraCast docker installation It does not work

### Relevant log output

```shell
Debian 11 AzuraCast docker installation It does not work
```

**Comment by paulcjkp** [comment]
We're going to need some more information, other than "it doesn't work".  What error messages are you getting during installation?
