### ISSUE TITLE
cors-anywhere  problem with azura 0.17.7 not work

### ISSUE THREAD

**Issue by ajeje989** [AzuraCast/AzuraCast#6053]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.7

### What happened?

hi, I've always used the cors called cors-anywhere to extract titles for external players.

With the latest version it gives me a 404 error with the cors

If I try an icecast radio with an older version than the recent one it works.

Maybe it's the new version of Icecast 2.4.0-kh17 that creates this conflict.

Is it possible to fix it?

### Relevant log output

```shell
https://i.imgur.com/MS8KAEv.jpg
```

**Comment by Vaalyn** [comment]
The URL for the status-json.xsl you are using does not exist.

Try with one of the following:
- https://azura.servertec85.com/radio/8090/status-json.xsl
- https://azura.servertec85.com:8090/status-json.xsl

**Comment by ajeje989** [comment]
ok i check 
on cors ..
this not work https://azura.servertec85.com:8090/

this work  https://azura.servertec85.com/radio/8090/

in the last version work also https://azura.servertec85.com:8090/

**Comment by ajeje989** [comment]
I try with another server with last version azura  0.17.7

And not work the cors with  ip:port
Works only ip/radio/port

U can fix ?

**Comment by Reaktiv4** [comment]
Have you solved the problem? I also have problems with cors.

**Comment by ajeje989** [comment]
With last version not work

**Comment by ajeje989** [comment]
> Have you solved the problem? I also have problems with cors.

ip:port not work now
/radio/port/ this work

**Comment by Reaktiv4** [comment]
Two options work, but two options give an error cors. I think to put icecast on a separate vps - https://mediarealm.com.au/articles/icecast-https-ssl-setup-lets-encrypt/

**Comment by ajeje989** [comment]
> Two options work, but two options give an error cors. I think to put icecast on a separate vps - https://mediarealm.com.au/articles/icecast-https-ssl-setup-lets-encrypt/

this is another problem .. is not similar to my problem

u need to add ssl cert on your azuracast panel

u can use letsencrypt .
is easy .

**Comment by Reaktiv4** [comment]
The problem is elsewhere - https://github.com/AzuraCast/AzuraCast/issues/6104
