### ISSUE TITLE
Media search returns no results or wrong results for most playlists

### ISSUE THREAD

**Issue by guiltlab** [AzuraCast/AzuraCast#6059]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#18b1e88

### What happened?

When using the playlist:string special search in station/<id>/files (both using the internal interface and with the API) most playlists return no results at all, this is what I see with about 90% of them:
[](url)
![image](https://user-images.githubusercontent.com/45518224/216305225-961c59f0-c8ba-4801-ab08-a02323d4bcc7.png)

A few playlists searches do give results, but they're wrong. As you can see from the "playlists" column, none of the songs returned actually belong to the "pop music" playlist. 
![image](https://user-images.githubusercontent.com/45518224/216305778-4a6bc2d6-4f05-4a38-843e-e4156dc6aaae.png)

I suppose this is caused by https://github.com/AzuraCast/AzuraCast/commit/b98d1600cc3eb155a6aaad581648bb4c0ff639bf. I'm not sure what other details I could give, sorry !

**Comment by BusterNeece** [comment]
Ah yeah, seems the "chained" searches don't work with playlists with spaces or other special symbols. Reverting that for now.
