### ISSUE TITLE
super administrator cannot create new accounts V.17.7 Stable • Docker • PHP 8.2

### ISSUE THREAD

**Issue by marekdziem** [AzuraCast/AzuraCast#6067]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

17.7

### What happened?

after updating to 17.7 administrator cannot create new user accounts

**Comment by marekdziem** [comment]
![image](https://user-images.githubusercontent.com/3094096/217220282-1302ee33-f82e-4d7b-aee3-5c569fc8d759.png)

Error: You do not have permission to access this portion of the site
![image](https://user-images.githubusercontent.com/3094096/217220628-a4e23bf1-2754-4b52-a10b-e3fa35f1aa2f.png)

**Comment by BusterNeece** [comment]
@marekdziem I can't reproduce this issue on my end. I'm not sure what's causing it in this case.

**Comment by gasguti** [comment]
It happened to me. You may have another window open and logged with the new user, close all the open sessions.

**Comment by marekdziem** [comment]
hi @BusterNeece we experienced the same issue again yesterday on two azuracast instances!
I eventually managed to come right by clearing all the caches ad queues under system debugger and clearing our my browser cache.

**Comment by BusterNeece** [comment]
@marekdziem Are you logging in as these users? That would change your session to appear as if you're that user, which wouldn't have the appropriate permissions until you log back out as that user.
