### ISSUE TITLE
Now Playing information not showing for a live broadcast

### ISSUE THREAD

**Issue by matthewunmuted** [AzuraCast/AzuraCast#6068]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #5ab3cf9

### What happened?

Hi, hope you are well.

We have a client who is reporting that when broadcasting live to their service, no 'Now Playing' information is being displayed. 

We have tried reloading the configuration and restarting the broadcasting services, with no luck.

The ShoutCast Server Summary page simply displays 'Playing: Live Broadcast'

The currentsong page displays the correct track artist and name, but this does not reflect in the 'On the Air' box on the Profile page: https://clare.shoutca.st/listen/ms_radio_suriname/currentsong?sid=1

The nowplaying API page looks correct, too: https://clare.shoutca.st/api/nowplaying/9

Any advice or help would be very welcome.

**Comment by DJEclypse** [comment]
This is something they blame on liquidsoap and i and many more have put this problem to them and ive suggested a fix but they dont seem to want to fix the things that are harder to fix which is amazing really because the azuracast panel from 2 versions ago works fine with titles its one of those if it aint broke dont try and fix it mate ;)

**Comment by DJEclypse** [comment]
I opened this weeks ago https://github.com/AzuraCast/AzuraCast/issues/6031

**Comment by Moonbase59** [comment]
Well, it’s free and open source beta software, after all… And you _have_ to rely on some upstream projects like LiquidSoap. This is actually a known problem.

Then again—if your streaming software allows—you could set your metadata intervals to send metadata more often. I once played around with that (years ago) and seem to remember I used 16k and 64k intervals back then.

Streaming with IDJC, I seldom see the "Live Broadcast" message for longer than a few seconds. And I’m rather happy it’s there—much better than a blank.

**Comment by amacleod457** [comment]
I am seeing this issue with Azuracast 0.17.7 Stable, using Icecast as backend broadcast software. The DJ is using Station Playlist Studio, latest version from 6.0. The first and second titles came through fine, but then title streaming then got stuck on the second track.
