### ISSUE TITLE
Some problems with auto backups

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#6072]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

7034249 (2023-02-06 4:21) • Docker • PHP 8.2

### What happened?

hello, i have various problems with automatic backup.
1. i think older backups are being deleted after making backup, it should be before making the backup.
2. I think the system is not verifing the available space before making backup. at the moment, i have a backup with 11gb, and all my backups, the complete ones is about 60gb.
my hard drive is only 200 gb, and it causes hd to be full, incomplete backups being incomplete, and radio totally stop to work, because hd is full.

**Comment by Moonbase59** [comment]
Let me chime in as a user:

1. I strongly _disagree_. What if the current backup fails? The old one will be lost then!
2. I agree—it should try to estimate and check the free space before starting the actual backup.

**Comment by nunotfc** [comment]
Ok, agreed first point
