### ISSUE TITLE
azuracast_updater not starting after update

### ISSUE THREAD

**Issue by Dragondarn1993** [AzuraCast/AzuraCast#6073]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #be32f43 (2023-02-11 5:29)

### What happened?

When I update AzuraCast with ./docker.sh update, an error appears at the end that prevents the azuracast_updater container from starting.

### Relevant log output

```shell
Creating azuracast ...
Creating azuracast_updater ... error
Creating azuracast         ... done
ERROR: for azuracast_updater  Cannot start service updater: unable to find user root: no matching entries in passwd file

ERROR: for updater  Cannot start service updater: unable to find user root: no matching entries in passwd file
ERROR: Encountered errors while bringing up the project.
```

**Comment by isAAAc** [comment]
same here, looks like it doesn't find the mysql auth

**Comment by BusterNeece** [comment]
Should be fixed now. Sorry about that!
