### ISSUE TITLE
Customizing Liquidsoap through the Advanced Custom Config. mechanism

### ISSUE THREAD

**Issue by franckalbinet** [AzuraCast/AzuraCast#608]
First of all, thanks a lot for this amazing app., really appreciate it!

I am trying to customize the LiquidSoap config. file via the `profile > Advanced Custom Configuration` mechanism provided but my attempts have remained unsuccessful so far. Here is my simple use case for now:
* 3 playlists: (rock, groove, jingles)
* pay 2 songs from `rock` playlist, 2 songs from `groove` playlist and 1 jingle from `jingles` successively

According to Liquisoap doc. and https://github.com/AzuraCast/AzuraCast/wiki/Using-Advanced-Playlists (which has been redirected in the last 2 days but which mentioned the automatic renaming rules of the playlist, ... ), adding 
```
radio = rotate(weights=[2,2,1], [playlist_rock, playlist_groove, playlist_jingles])
````
to `profile > Advanced Custom Configuration`  should do the job right? 

Furthermore each of these playlist should be configured as followed right?
![image](https://user-images.githubusercontent.com/1142608/41091834-caf88714-6a47-11e8-93c6-5d8e111a1cb8.png)

Am I missing something here?

All the best and thanks again for the initiative.

**Comment by SlvrEagle23** [comment]
@franckalbinet That all looks fine (and thanks for reminding me about the now-missing Advanced Playlists page...need to move that to the new azuracast.com homepage!)...one important note: you have to "restart broadcasting" (under Utilities) to rewrite the Liquidsoap configuration file, restart the station and apply the changes.

**Comment by franckalbinet** [comment]
@SlvrEagle23 Thanks for your prompt support! Indeed, I did not `"restart broadcasting"`, however still not managing to play my setup. I've tried with the simplest possible Liquidsoap possible in `profile > Advanced Custom Configuration` : 

```
radio = playlist_rock
```
and when restarting ("restart broadcasting"), it looks stuck in the `"Please wait..."` state (I've actually waited 20 min,  I guess this is sufficient -:). I've the feeling I am missing something crucial there ?

**Comment by SlvrEagle23** [comment]
@franckalbinet It's likely that something's going wrong with the restarting process. I definitely need to fix that so it actually bounces back an error immediately so nobody winds up waiting 20 minutes! :(

You can check `docker-compose logs -f stations` (if you're on Docker) or `tail -f /var/azuracast/stations/(station_name)/config/liquidsoap.log` to see what's specifically going wrong.

**Comment by SlvrEagle23** [comment]
@franckalbinet I've significantly rebuilt a portion of the code to much more elegantly handle errors when restarting radio services. You'll still need to check the logs for the specific error causing the problem for now (still working on that), but it won't just hang indefinitely and will return an indicator of which service caused the problem.

**Comment by SlvrEagle23** [comment]
@franckalbinet Also, I've turned the wiki back on and just removed the pages that are already represented in the new homepage, leaving the other pages up for reference (including the Advanced Playlists one). Thank you for reminding me of that.

**Comment by franckalbinet** [comment]
@SlvrEagle23 Thanks a lot! Please see attached a portion of the log file (I extracted full Thursday 7th of June logs) where you might spot something informative. I've tried several time during the "Advanced configuration option" as mentioned in earlier messages.

[liquisoap-2018-06-07.log](https://github.com/AzuraCast/AzuraCast/files/2087158/liquisoap-2018-06-07.log)

**Comment by SlvrEagle23** [comment]
@franckalbinet It doesn't look like there's anything going wrong in this scenario. The log file seems to suggest the Liquidsoap process is restarting just fine, has a few ignorable warnings and then continues on to shuffle music.

It could be that you're not using the previously defined `radio` variable in your rotation, which is confusing Liquidsoap as it still tries to "cue up" tracks from the regular AutoDJ rotation, but fails to have anywhere to play them. You may want to put one of the playlists in the regular AutoDJ rotation, then refer to `radio` for that section only, like:

```
radio = rotate(weights=[2,2,1], [playlist_rock, playlist_groove, radio])
```

Where your jingles are a standard rotation playlist.

This might not resolve any issues you're having, but it's something worth trying.

**Comment by franckalbinet** [comment]
Thank you, your support is very much appreciated!

I've tried it and slightly making progress on this simple use case. If I understand properly the `radio` variable is defined by default (as a default stream) and should absolutely conveys something: we cannot start from scratch feeding the radio variable with rotation of two `advanced` playlists.

So what you have suggested (just correct me if I am wrong) is to define `jingles` as a `Standard play list` and as a result will feed the `radio` default stream and both `rock` and `groove` playlists defined as `Advanced` ones. Anyhow, in that specific setup (so I confirm now that broadcast is restarting properly) and with this liquidsoap:
```
radio = rotate(weights=[2,2,1], [playlist_rock, playlist_groove, radio])
```
I am getting the following behaviour: 2 of rock, 2 of groove and then ... jingles, jingles, jingles, ... (never leave that "jingles/radio" state). Do you understand it? What am I missing?

**Comment by SlvrEagle23** [comment]
@franckalbinet That's exactly what I meant, and you set it up exactly as I would have recommended, so it's strange that it's doing the thing you're describing.

If you go back to the first way you had it set up (with all the playlists being Advanced, and just rotating between them) with the latest version of the AzuraCast codebase, do you still get the same error popping up?

**Comment by franckalbinet** [comment]
@SlvrEagle23 

I pulled your last changes and made different tests:

When configured as follows (with all playlist as advanced):

```
radio = rotate(weights=[1,1,1], [playlist_groove, playlist_rock, playlist_jingles])
```

Here after the logs (after restarting - I get the error as popup in the UI now as well so that we don't get stuck in a hanging state):
```
2018-06-14 12:35:59,237 INFO spawned: 'station_1_backend' with pid 827
stations_1     | Warning: unused variable ret at line 40, character 7.
stations_1     | Warning: unused variable ret at line 46, character 7.
stations_1     | Warning: unused variable radio at line 73, character 7.
stations_1     | Warning: unused variable radio at line 70, character 7.
stations_1     | Warning: unused variable radio at line 64, character 7.
stations_1     | Warning: unused variable radio at line 59, character 7.
```
which confirms what you mentioned already that using the `radio` var is required at the moment

Using the previous set up with jingles as follows  (see screenshot) and 
![image](https://user-images.githubusercontent.com/1142608/41412717-2fa145ea-6fe1-11e8-9123-e4b137c0d65c.png)
I still have the same behaviour as before: play each playlist then got stuck in the `radio` one (no error logged) 

```
radio = rotate(weights=[1,1,1], [playlist_groove, playlist_rock, radio])
```
Any idea?  Thanks a lot! Franck

**Comment by franckalbinet** [comment]
@SlvrEagle23  Got it!

Reading Liquidsoap doc, it appears that the playlist we get by default using your naming convention playlist_[playlist_name] is **fallible** (using Liquidsoap jargon). So I simply made them safe (I am using the most straightforward way to do so for now) as follows (all of them being defined as advanced one):

```
groove = mksafe(playlist_groove)
rock = mksafe(playlist_rock)
jingles = mksafe(playlist_jingles)

radio = rotate(weights=[1,1,1], [groove, rock, jingles])
```

and works like a charm. I need to have smoother transition etc ... but have now the full freedom to explore Liquidsoap world -:)

Thanks again for your great support!

**Comment by SlvrEagle23** [comment]
@franckalbinet Awesome. I must've missed that detail on my end, and I suppose that's why including `radio` as an option works, as it's one non-fallible source of audio, and Liquidsoap always needs at least one to fall back on.

I see no reason on my end why I shouldn't just `mksafe` the playlists across the board for this exact reason.

**Comment by franckalbinet** [comment]
@SlvrEagle23 Not sure that playlists should be made safe (`mksafe` by default) on your side when making them available in advanced Liquidsoap config as it is only one of more possible way to do so (look at  http://liquidsoap.info/doc-dev/quick_start.html). Leaving it as it is now will offer more flexibility I believe. 

This being said, this should be reflected in your documentation. I will now extensively explore Liquidsoap vast possibilities and for sure will be more than happy to contribute to that piece of documentation in near future if you are interested.

**Comment by SlvrEagle23** [comment]
@franckalbinet That's a fair point, and perhaps most importantly, once a playlist has had `mksafe` applied to it, you can never revert that and make it "unsafe" again (for whatever reason).

I'll update the Advanced Playlists wiki page for now.

**Comment by SlvrEagle23** [comment]
@franckalbinet The wiki article has been updated to make specific mention of this scenario and to generally discuss the "fallibility" of playlists by default.

Thanks for your help. Any future contributions on this front would be greatly appreciated.

**Comment by franckalbinet** [comment]
@SlvrEagle23 Continuing exploring possibilities of custom config. via Liquidsoap after our constructive message exchanges; and almost ready for production: composing playlists with rotate, random, switch, scheduler, ... This is really awesome! 

Now, this said, I am still facing an important issue related to the use of dynamic requests. Let me try to explain my issue :

* Starting from the easiest use case  simply let's say rotating with two playlists defined as `advanced`:
```
radio = rotate(weights=[1, 1], [playlist_radio, playlist_groove])
```
it plays as expected however when fetching the api `/api/nowplaying` I am loosing the duration, remaining, art, ... JSON fields given that we don't use dynamic request and cue_cut mechanism as implemented and generated in the default `liquidsoap.liq`:
![image](https://user-images.githubusercontent.com/1142608/41810136-75addce6-76f9-11e8-8e9d-df941ddf0b8a.png)

The part I am referring to in the `liquidsoap.liq` when both `playlist_radio` and `playlist_groove` are defined as `advanced` hence "overwriting the dynamic request and cueing mechanism.
```
# Standard Playlists
radio = random(weights=[3], [playlist_default]);

# Assemble final playback order
dynamic = request.dynamic(id="azuracast_next_song", azuracast_next_song)
dynamic = cue_cut(id="azuracast_next_song_cued", dynamic)
radio = fallback(track_sensitive = false, [dynamic, switch([ ({ true }, radio) ]), blank(duration=2.)])
...
# Custom Configuration (Specified in Station Profile)
radio = rotate(weights=[1,1], [mksafe(playlist_rock), playlist_jingles])
```

* so my point is to get the expected `duration`, `remaining` json attributes back as we further need them for the player, ... on the front-end side. So my understanding is that I need to re-assemble the final playback order after my custom configuration (rotate, ...). For now, when I naively do the following (just showing the custom part of the `liquidsoap.liq` file:
```
# Custom Configuration (Specified in Station Profile)
radio = rotate(weights=[1,1], [mksafe(playlist_rock), playlist_jingles])

dynamic = request.dynamic(id="azuracast_next_song", azuracast_next_song)
dynamic = cue_cut(id="azuracast_next_song_cued", dynamic)
radio = fallback(track_sensitive = false, [dynamic, switch([ ({ true }, radio) ]), blank(duration=2.)])
```
I get played the default `error.mp3` file as there is currently nothing in the `playlist_default` (automatically generated) and when querying 
```
curl -s --request POST --url http://nginx/api/internal/1/nextsong --form api_auth=...
```
I get the `/usr/local/share/icecast/web/error.mp3` file as expected.

* so it looks like I need to "re-init" or "destroy" or "free" or something in that spirit the previous "hooked" dynamic request in order to "feed" it with the new assembled stream (sorry for the multiplication of quotes but don't really now the proper terminology") and harness the dynamic request ,cue_cut mechanism allowing to get back the required json fields, next song, ...

* I have tried multiple other scenario but unsuccessful so far and this message is long enough -:)

So my questions are first: 
* do  you see what I mean?
* would you have an idea?
* am I completely missing the point?

Cheers, Franck

**Comment by SlvrEagle23** [comment]
@franckalbinet Yep, this all makes sense, and the answer is unfortunately rather simple: because I'm not aware of any reliable way to have Liquidsoap transmit metadata about song duration and/or playback position, this information in AzuraCast is determined strictly by the AzuraCast AutoDJ as it specifies the "to be played next" song to Liquidsoap.

If you're using an advanced configuration, this will naturally bypass the AzuraCast AutoDJ, and while AzuraCast will still dutifully return now-playing information from a routine ping of the Shoutcast/Icecast server, it won't have that richer metadata that it would have if it were the source of the playlist control itself.

**Comment by franckalbinet** [comment]
@SlvrEagle23 Not sure to understand exactly how AzuraCast AutoDJ works but I thought that the whole purpose of the generated "Assemble final playback order" code chunk  with previously defined `azuracast_next_song()` function: 

```
radio = rotate(...) # depending on playlists config in Azuracast UI

# Assemble final playback order
dynamic = request.dynamic(id="azuracast_next_song", azuracast_next_song)
dynamic = cue_cut(id="azuracast_next_song_cued", dynamic)
radio = fallback(track_sensitive = false, [dynamic, switch([ ({ true }, radio) ]), blank(duration=2.)])
```
in the auto-generated `liquidsoap.liq` file was to dynamically fetch next sont to be played based on the `radio` defined variable after a cue in point as described here: http://liquidsoap.info/doc-1.3.3/reference.html#cue_cut then dynamically request querying `http://nginx/api/internal/1/nextsong` API ... 

What if instead injecting the advanced custom part after the "Assemble final playback order" we insert it just before it and after  the default `radio` definition as shown below:

```
# Standard Playlists
radio = random(weights=[3], [playlist_default]);

# -----------------------------------------------------------------------
# Custom Configuration (Specified in Station Profile) - Injecting is instead
radio = rotate(weights=[1,1], [mksafe(playlist_rock), playlist_jingles])
# -----------------------------------------------------------------------

# Assemble final playback order
dynamic = request.dynamic(id="azuracast_next_song", azuracast_next_song)
dynamic = cue_cut(id="azuracast_next_song_cued", dynamic)
radio = fallback(track_sensitive = false, [dynamic, switch([ ({ true }, radio) ]), blank(duration=2.)])
...
```

Wouldn't is solve the issue or do I misunderstand the way it works?

**Comment by franckalbinet** [comment]
@SlvrEagle23 Thanks a lot, it is clearer now! It took few days to accept the reality as we were so close to our dreamed web radio -:) and we are ready to  forgo the `elapsed`, `duration` attributes we needed for our player as not so critical.

As regards the Album images, this is more critical and we are still hoping to find a way to fetch them. 

On AutoDJ mode you are fetching those images from a dedicated API:
```
api/station/1/art/album_image_ID
```
how is this `album_image_ID` generated? Would I have a way to access it  from my Liquidsoap custom chunk, ... in songs metadata or elsewhere?

Thanks for your support!

**Comment by gammaw** [comment]
@franckalbinet did you find a fix for this? I'm having the same issue.

**Comment by franckalbinet** [comment]
@gammaw Unfortunately not! I finally had to implement a very ugly hack:

1. systematically processing  all uploaded mp3, ... with ffmpeg locally to extract album art and resizing them using PIL Python package for instance, and finally naming it using a naming convention (concatenating title, ...);
2. uploading them to an AWS bucket in order to serve them to the radio client (here the result: http://parlementia-records.com/player);
3. as fetching these images from AWS might be slow (and expensive), they are only pulled the first time then cached on the server).

Really ugly, but we got the job done and really wanted to keep the ability to customize the Liquidsoap file.

**Comment by gammaw** [comment]
@franckalbinet thanks. I also thought of something similar. I was hoping to be able to use some other field to convey the cover art URL (e.g., lyrics field) but unfortunately only the song name and artist are transferred by Liquidsoap (all other fields are empty in the nowplaying API). A real ugly hack would be (much uglier than yours) to encode the URL in the song or artist name :) I guess I will use a [song ID, cover art URL] map on the client side.
