### ISSUE TITLE
default station cover art and relay metadata

### ISSUE THREAD

**Issue by dgohn404** [AzuraCast/AzuraCast#6087]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #159272c (2023-02-15 2:51) 

### What happened?

Hi all! earlier it was possible to set a default cover for each station, but now I can’t find it, only a default cover for all stations

and one more problem, earlier, when rebroadcasting another station, the name of the current track was displayed and even the cover was loaded from lastfm, and now only the station is offline, but the sound goes on, tried both shoutcast and icecast and with autodj on and off and retransmitting with shoutcast and icecast in no way wants

**Comment by BusterNeece** [comment]
@dgohn404 We moved the default album art per-station to a dedicated Station Branding page, mirroring the system-wide Branding page. You can upload custom album art, backgrounds, and more.

**Comment by dgohn404** [comment]
@BusterNeece I didn’t find anything other than this, the standard one is used, but before there was a choice to set the path to the standard cover of each station and not all (
![IMG_20230223_163627](https://user-images.githubusercontent.com/99274225/220923654-91e8358d-b23d-43a8-9b37-87ea7642d856.jpg)

**Comment by BusterNeece** [comment]
@dgohn404 What I'm saying is that there _is_ per-station branding functionality for public pages. I can't tell from your screenshot whether you're looking at the system-wide one or the per-station one, but the per-station one is accessible by clicking the "Profile" menu, then "Branding", or going to the profile and looking at the bottom of the "Public Pages" panel.

**Comment by dgohn404** [comment]
@BusterNeece I found everything thank you very much)
