### ISSUE TITLE
Reprocess media files: Errors with larger collections (~150k files in my case)

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6088]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #46b71d7 (2023-02-16 4:28)

### What happened?

This is a rather standard local network installation in an Ubuntu 22.04 LTS server VM with 4 CPUs and 4 GB RAM, running off a SSD. The only thing I added was a Music folder which points to my actual music collection of roughly 150,000 well-tagged files (MP3 & FLAC) over a read-only NFS connection. I made a `/var/azuracast/docker-compose.override.yml` with the following content:

```yaml
services:
  web:
    volumes:
      - /mnt/Musik/Tagged:/var/azuracast/stations/azura_radio/media/Tagged
```

In my `/etc/fstab`, the media folder is mounted as follows:

```
192.168.170.32:/export/Musik    /mnt/Musik      nfs     ro      0       0
```

(read-only for safety's sake—don't want anything to mess up my valuable collection).

Under Media it shows correctly up as a folder "Tagged", containg all 10,631 band subfolders, their album subfolders and the titles. I assumed the system would need a reprocessing for this folder(s), checked the "Tagged" folder and selected _More → Reprocess_. After about 5 minutes working (htop shows a load average of ~4, as opposed to 0.3–0.4 normally), an error message briefly shows up in the top right corner stating something like "Error occurred: Your request couldn't be fulfilled" (quoted from memory).

I added the files to be reprocessed to a new playlist "Tagged" and expected it to eventually show up as `/var/lib/docker/volumes/azuracast_station_data/_data/azura_radio/playlists/playlist_tagged.m3u` but it doesn't. Also, clicking into the folders and viewing their content now (expectedly) takes much longer, and every title I checked has "File Processing" beneath it.

**Q1: Can AzuraCast handle that many media files, and was that ever tested?**

**Q2: Should I keep waiting (how long, approx.?) or can I anyhow help diagnosing this?**

I'd rather like being able to access my complete media collection (collected and ripped over the past 30 years or so) using AzuraCast… Thanks for building such an easy-to-use system!

### Rationale/Use Case

I’m asking for the (currently hypothetical) situation where you have a powerful central location, with one or more studios, and plan to broadcast to several remote relays—from a huge in-house music collection (which may not be modified). Evaluating if AzuraCast could be used for that, due to its easy administration and great progress in the past years.

For smaller stations on a budget it’s often simply not feasible to store multi-terabyte music collections on cloud servers. This could easily raise legal and financial problems, not talking about incredible upload/sync times.

### Relevant log output

```shell
Checked logs, nothing relevant found.
```

### Screenshots

![Music Files – Mozilla Firefox_001](https://user-images.githubusercontent.com/3706922/219533179-bcd79586-f260-49e8-8a5a-c6a1ce901c51.png)

Folder shows up, last modified time is correct, and 1.6 TB is also correct (the VM only has a 50 GB "drive"). I don't know what the red "100" means, though.

Side note: The player seems to play random files from the collection!

![Music Files – Mozilla Firefox_002](https://user-images.githubusercontent.com/3706922/219533517-3dba4c36-1ed8-4b60-b6f5-9c2b340dbc80.png)

Folder content seems correct, too. (The `.stfolder` is from Syncthing, can't exclude such files & folders from a simple mount.)

![Auswahl_198](https://user-images.githubusercontent.com/3706922/219535683-a5ea3319-c384-4928-8259-e41fa095612c.png)

In the "System Debugger", when refreshing, I find a constantly increasing number of "media—queued messages". Whatever that means.

**Comment by Moonbase59** [comment]
N.B.: On some titles, AzuraCast seems to mess up the title display. Since the tags are surely correct, I think this might be due to a RegEx that tries to separate Artist/Title?

![Azura Radio – Mozilla Firefox_002](https://user-images.githubusercontent.com/3706922/219531909-ad03bd63-09e7-4ba3-8753-300f77bc9c05.png)

**Comment by Moonbase59** [comment]
After leaving AuraCast running for about 9 hours now, I see "AzuraCast.ERROR: Symfony\Component\Process\Exception\ProcessTimedOutException" timeout errors creeping up in the "AzuraCast Application Log".

Also, the number of "media—queued messages" has meanwhile increased to 2,629,343 queued messages.

**Q: Should I change something in `azuracast.env` and maybe even `.env` and try it all over again? What to change?**

Here’s the log:

[AzuraCast Application Log.txt](https://github.com/AzuraCast/AzuraCast/files/10765297/AzuraCast.Application.Log.txt)

**Comment by guiltlab** [comment]
Two pieces of advice from my experience adding several tens of thousands of files to azuracast (so, a lot but still less than you...):
- clear the media queue, when it starts filling up like this (to hundreds of thousand messages), it usually will not recover on its own. don't be surprised if it times out and you need to do it many times before you reach 0 queued message
- don't add so many files at the same time. try to do it in batches of <10k, maybe even under 5k. you can simply move the files out of the mounted directory, and then progressively back in, one batch at a time whenever you see that the queued messages for the previous batch have all been treated

**Comment by Moonbase59** [comment]
Thanks for your feedback, will try.

- You mean, I can clear the msg queue anytime? It’s now at roughly 2,4 mio entries.

- Adding in parts seems difficult—folders are band names (10,631 folders), beneath are album folders, so quite a lot to do.
  - Let’s assume I set display to 50 entries/page and mark all, then the next 50 (which will take a long time), how do I know it’s done with each batch?
  - Exactly these repetitious tasks a computer should do for me, I somehow feel… ;-) I’m thinking if the system _knows_ about not being able to handle such larger collections, could it not by itself run smaller batches sequentially?

- Do you think I should modify the title of this issue to, say "Errors when scanning larger music collections" or the like? Seems to boil down to that.

**Comment by guiltlab** [comment]
>  You mean, I can clear the msg queue anytime? It’s now at roughly 2,4 mio entries. **EDIT:** _Just tried to clear the media msg queue, only to arrive at a blank white screen after a few seconds… 

Yes you can clear the media message queue at any time, AFAIK it shouldn't have any bad side effects. Never had an issue doing that personally. The blank white screen you get is exactly what I was referring to when I said "don't be surprised if it times out and you need to do it many times before you reach 0 queued message". See https://github.com/AzuraCast/AzuraCast/issues/5978 where I talk about this behavior. You only get a blank screen because the queue is so big that the clear operation times out before it's finished, but it the clear queue function does work, you should see that the number of messages has decreased after you get the timeout. If your queue is more than a million messages, it will probably take at least 20 cycles of clicking "clear queue" => blank screen => reload system debugger page ==>  click "clear queue" ==> repeat until number of queued media messages is zero.

> When I go back to the /admin/debug page and hit F5 refresh, it looks like about one msg per second is removed—something highly inefficient here._

Yes, AzuraCast still appears to be processing files even with a lot queued messages, but if you monitor it closely, you will see that there is a continuous small decrease (files processing) and every once in a while, a huge increase (dunno what's the cause), which offsets the decrease by a lot, and therefore the net result is that your queue increases indefinitely. Which is why I recommend clearing it entirely when you see this behavior.
So far I have not found any other way to prevent this than to add files in smaller batches and wait for them to be processed before adding more. Obviously it's not very practical, but it's a workaround for now.

**Comment by Moonbase59** [comment]
Thanks for all your explanations, much appreciated. So the "message queue" actually seems something that decreases (maybe files processed?). When I'm fast enough clicking them away (usually increases by ~150k messages every time one of these periodic background processes hits in), I can actually see that more and more files get done (i.e., show length, date and folder in the media view).

A super-tedious process. I’d recommend one of the developers has a look into this, and probably can optimize the process for larger collections. I’ve seen installations with around 1.3 million audio files (a public broadcaster, and they were using another broadcasting system but had an installation with SAM Broadcaster handling >1 mio. files blindingly fast—I was impressed), but clearly AzuraCast isn't targeting that market. Still I think some people doing non-profit or semi-commercial broadcasting easily have 50–200k files, which—I feel—AzuraCast should be able to handle. Maybe it could actually be done in chunks programmatically, just as we have to do now manually.

The use case of having all files stored centrally, on people’s own servers and well backed up, and then broadcasting to external relays shouldn’t be too far-fetched.

**Comment by BusterNeece** [comment]
@Moonbase59 Catching up on this thread...the start of the sync task actually looks through the existing queue and won't re-queue up things that are either already queued or already processed. Somehow, in your case you're running into a "runaway media queue" issue, and I'm curious as to why that is but I'm not immediately sure.

If you have, say, 150k files, you should only ever see...well, 150k media queue items. The fact that you're seeing them double up suggests that perhaps somewhere in the process, Docker/PHP/AzuraCast/etc. isn't seeing things correctly, or it's thinking things are "moving", or being removed and re-added, or something similar.

That amount of files is pretty large, and it'll take a minute to process them for sure, but it _definitely_ shouldn't end up with you waiting multiple days with a queue in the millions.

**Comment by Moonbase59** [comment]
@BusterNeece Thanks for chiming in!

1. It seems that some processing worker continually hits in _while the first process isn’t finished yet._ Following @guiltlab’s advice, I now continually clear the media queue, and it seems like you indicate: From 0 it goes up to ~148k (roughly # files to process yet), and when I hit F5 (refresh) I can actually see the number _decreasing_. A few minutes later said process seems to hit again, roughly _doubling_ the number of entries (i.e., always adding the number of yet unprocessed files _again_ to the queue). Then again, and again…
2. The process of scanning the files is surely slower than it could be if the music collection was on the same server, but it is _not_. As I said above, they are really on my central server, only NFS-mounted into `/mnt/Musik` (of the server running AzuraCast), then mounted from there into the docker container. This would account for some speed loss, since I only have a 1 GBit/s ethernet currently, and the files need to be accessed over the network.
3. My gut feeling says the processing part simply hits every x minutes, sees there’s work to do, and adds it to the queue. It doesn’t seem to check if its previous run is finished yet. This situation—I think—could be remedied easily by setting a lock or flag so that the new process would check if its previous run has finished and probably simply skip this time round. Although there might be adverse effects, since it obviously should check for _new_ files having been added which might be missed. Of course no one can foresee actual processing speeds in various environments, so simply relying on timeouts or "not doing it so often" will fail eventually. Some semaphore might indeed be needed.

**Comment by BusterNeece** [comment]
@Moonbase59 Regarding point 3, your latter idea is exactly what it does presently...it looks through the queue, gets the IDs of all currently queued messages, and it _shouldn't_ re-queue those messages.

The problem we're running into here is, I think, largely one of the design of Beanstalk, our message queue processor. It's very, very fast and lightweight, but it is very purpose-built for the job of simply handing one job to one worker, and not much more. It has no bulk "get the IDs of every task pending" or "delete every pending queued item", which means we instead have to basically "pop" each item off the list, one by one, and delete each one via a separate API request.

There may be little we can do to improve the performance of the "Clear Message Queue" function (though we can of course just set it to have no timeout), and ironically we could use the message queue _itself_ for the "clear queue" functionality, throwing it to a background process so the frontend process returns immediately.

However, I'm thinking about ways we can improve upon our bulk processing capabilities for newly ingested media.

**Comment by BusterNeece** [comment]
And yes, to your 4th point, if the system thinks the storage location is full for any reason, it'll prevent web uploads from going through, but this may be a nonissue for you if you're managing your media by other means.

**Comment by Moonbase59** [comment]
Thanks for thinking along and looking for solutions, much appreciated!

Re (4) Maybe I could use SFTP instead of web uploads, ok. Still I’m thinking maybe when checking the drive space one could use (as some Linux tools can) a "same filesystem only" check (like in `df -hl`) which would show only the free space on the _local_ filesystem. Or one might add the mount target’s free space (which would be 1.2 TB in my case). This would allow web uploads if space were free on the _local_ drive still, disregarding whatever else is mounted in.

Re (1), (2), (3): What would be your priorities on that? (Because I’m evaluating and struggling a little here.) Should I just wait and see what happens in "rolling"? Or do we continue this here so I can get a feeling for an ETA?

**Comment by BusterNeece** [comment]
@Moonbase59 Right now, I have a lot on my plate, but when I have some free time I will look into the "runaway queue" issue and see what I can do there.

Improving media processing speeds will be a more complex issue that will take quite a lot longer to fix.

**Comment by Moonbase59** [comment]
I agree, but in general (on local drives) I feel the speed is okay. Mine is surely a border case. Getting the "runaway" fixed is definitely much more important. It’s no problem starting the rescan process and let it run a day or so in the background. It just shouldn’t fail or need to be watched. After all, a computer should take away the long, tedious task from us ;-)

**Comment by BusterNeece** [comment]
@Moonbase59 Pushing up a large-scale rebuild of the message queue delivery stack right now.

I investigated the situation further, and discovered that a large portion of the problem we're having is because Beanstalkd can't properly "seek" through its records, which would indeed cause a "runaway queue" issue.

I've shifted our message queue system back over to using Redis with some under-the-hood modifications to ensure stability. This will allow for instant queue-clearing, which means we can now just clear the media queue every time the media sync task runs. While this may result in some fluctuation of the queue numbers you see from moment to moment, it should in the long term result in absolutely no possibility for "runaway queues", and instant clearing on the part of the user via the debug console if it does somehow happen anyway.

Once the latest commits show green check marks, I'd encourage you to update to the latest Rolling Release version (using whatever update method you prefer, they should all yield the same result) and let me know if it improves things at all.

**Comment by Moonbase59** [comment]
Happy that you found time to investigate this! Believe me, it’s betterto wait for a day while a large collection over an NFS mount is scanned in than having to do it manually in chunks! :-) I’ll surely test this, especially since I need a rescan anyway because I introduced several custom fields (that’s the tagging thing I mentioned elsewhere).

Just give me a signal, or otherwise I’ll "blindly" follow the rolling update notices. :-) Appreciate your work.

**Comment by BusterNeece** [comment]
@Moonbase59 The update has already deployed, per our commit history. Feel free to update as needed.

**Comment by BusterNeece** [comment]
@Moonbase59 Also, to your secondary comment about the Redis memory usage (I wish you wouldn't edit your messages to include substantially new information, as I do not get notified of these updates and thus can't respond to them)...we already use Redis in our stack. This is just switching back to using its message queue capabilities instead of Beanstalk's, so the impact should be minimal.

**Comment by Moonbase59** [comment]
Thanks for your explanation. Sorry, wasn’t aware that edits don’t push notices! I’ll try to compose my thoughts a little _before_ posting in the future… I somehow tend to type along while it’s in my head and then thinking "Oh, and this and that also happened"… Sorry again.

Will update now and start a media reprocess…

**Comment by Moonbase59** [comment]
Quick feedback:

1. The update ran flawlessly (using CLI). I’m now on Rolling Release #[94efd77](https://github.com/AzuraCast/AzuraCast/commit/94efd77a7d03b2a9429dd6f011cf06caae7d8209) (2023-02-20 3:57). It pulled a lot of new/changed things.
2. I can now see many more Sync Tasks in the System Debugger. Trying a "Reprocess" on my ~150k files folder shows a "Processing" message at top right, but _no_ green "Done" message comes up (it does when I do shorter reprocessings, like on a single album). When I refresh the page, a very brief unreadable error message shows up at top right.
3. Reprocessing didn’t give any media queue count in System Debugger, but multiple times a single high_priority queue entry showed.
4. Memory still at ~2.3 GB, load avg ~1.9–2.3 when doing things. Looks good.
5. I somehow think a reprocess on already scanned files is rather efficient and doesn’t do all the work a new scan does. In order to test this thoroughly, would there be an easy way to make AzuraCast "forget" my "Tagged" folder, so it would have to rescan all 150k files and we get similar test results as before (like when freshly inputting media)?
6. The App Log still shows occasional 30s-timeouts, mainly when I’m listing or searching in "Music Files" or "On Demand". Since the song request search in the player is _blindingly fast_ and shows no errors, is it possible that you use not only the database but the filesystem too in "Music Files" and "On Demand" searches? And should I increase `PHP_MAX_EXECUTION_TIME` in `azuracast.env` to something more than 30s?

**Comment by BusterNeece** [comment]
@Moonbase59 Thoughts:
 - If you're reprocessing a whole media library, run `./docker.sh cli azuracast:media:reprocess station-name` to instead just flag all media as in need of reprocessing, which will let it run through the normal queue process again. This is greatly preferred for large reprocessing efforts over manually flagging each item for reprocessing, which queues each item up one-by-one and is definitely where you're seeing slowdown there.
 - The performance on searching your playlists is unrelated to our media processing ingest process. We're already looking into implementing Meilisearch for users who have the system resources to support it.

**Comment by Moonbase59** [comment]
- Cheers for that pointer, good to know. Will do that immediately and see what comes out of it.
- Ah, I get it. So you’re saying the "song request" search is actually a _playlist search_ driven by fast database-only processes, and "Music files" uses DB+files in a different kind of process?

**Comment by BusterNeece** [comment]
@Moonbase59 Requestable tracks is cached in a way that makes things faster than our playlist search. There's more data to merge in from the media manager page.

**Comment by Moonbase59** [comment]
_CheckMediaTask_ running, albeit the process is mostly in "D" state. I see my bottleneck is definitely network speed for the NFS mount.

```bash
root@azura:/var/azuracast# ./docker.sh cli azuracast:media:reprocess azura_radio
 
Manually Reprocess Media
========================

Reprocessing media for station: Azura Radio
Marked 157676 records for reprocessing.
root@azura:/var/azuracast# 
```

![Arbeitsfläche 1_007](https://user-images.githubusercontent.com/3706922/220065916-453f9c8e-c123-476e-8fc2-895c9f81270a.png)

![Administration – Mozilla Firefox_001](https://user-images.githubusercontent.com/3706922/220066450-7e33136b-a9f1-47a3-b4de-1b081b1fa4db.png)

**How will I know when it’s finished?**

**Comment by BusterNeece** [comment]
@Moonbase59 If you manually run the Check Media task, you'll see a debug log including the stats from the media processing. It's finished when there are 0 "created" records.

**Comment by Moonbase59** [comment]
So far system is chugging along, apparently always queueing up 100 messages into the media queue.

An error occurred here:

```log
[2023-02-20T09:38:42.735399+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":0,"workerName":"app_worker_0"} []
[2023-02-20T09:43:45.190273+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":0,"workerName":"app_worker_0"} []
[2023-02-20T09:46:01.007967+00:00] AzuraCast.ERROR: Message queue error: Could not acknowledge redis message "1676885207090-0". {"workerName":"app_worker_0","exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Could not acknowledge redis message \"1676885207090-0\". at /var/azuracast/www/vendor/symfony/redis-messenger/Transport/Connection.php:386)"} []
[2023-02-20T09:46:01.009052+00:00] AzuraCast.WARNING: Console command `azuracast:queue:process` exited with error code 1. [] []
```

**Comment by Moonbase59** [comment]
Another try shows only xxx files now:

```
root@azura:/var/azuracast# ./docker.sh cli azuracast:media:reprocess azura_radio
 
Manually Reprocess Media
========================

Reprocessing media for station: Azura Radio
Marked 7529 records for reprocessing.
root@azura:/var/azuracast# 
```

**Comment by BusterNeece** [comment]
Right, that's how many files it had already processed at that point.

Usually the worker process should restart on its own and get back to things rather quickly.

**Comment by Moonbase59** [comment]
Phew. After a day and a few hours and ~1.1 TB data read (as shown by the host OS, includes web and streaming), it has now completed!

I let it finish on Rolling Release #[94efd77](https://github.com/AzuraCast/AzuraCast/commit/94efd77a7d03b2a9429dd6f011cf06caae7d8209) (2023-02-20 3:57) and will now do the outstanding updates.

Using my generous PHP & NGINX settings, it worked without a glitch, always queueing up the next 100. Apart from a few errors (WMA album art), nothing bad happened and the station kept running and streaming happily the whole time.

Thanks for this change—it’ll really help all of us with large collections, possibly even mounted from external storage. A job well done!

If you have no objections, we can close this for now.

**Comment by stickbear2015** [comment]
@Moonbase59 I've got a similarly sized collection, what php limits and custom nginx settings worked for you?
Please note as a blind system administrator screenshots don't help me so as much textual information you can provide would be amazing, and where you make the changes you made that helped you.

**Comment by Moonbase59** [comment]
@stickbear2015 I used the settings mentioned here → https://github.com/AzuraCast/AzuraCast/issues/6095#issuecomment-1436664889. Running on an Ubuntu 22.04 VM, 4 CPUs, 4 GB RAM.

Hope that helps, let me know if it works out for you!
