### ISSUE TITLE
Station removed when remove streamer account

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#609]
- **Installation Method:** Traditional
- **Host OS (if using Docker):** Ubuntu 16.04

The mountpoint gets removed when removing a streamer account. No errors in logs.

In de database: Station_requests, station_streamers, station_webhooks, station_mounts, listeners, song_history all empty

I am completely sure that the action DJ account removal ensures that this also removes the drive. I tested it 2x. Maybe it is possible that it is because the DJ has just been On Air.

**Comment by RemBdev** [comment]
In de database: Station_requests, station_streamers, station_webhooks, station_mounts, listeners, song_history all empty

**Comment by SlvrEagle23** [comment]
@RemBdev This is a known issue from versions prior to March 20, 2018 (the `Version20180320163622` database migration), but was fixed as of that update. Is your installation updated to include that fix?

**Comment by RemBdev** [comment]
Oh hell no! I'm sorry @SlvrEagle23 for creating an issue thats not existing anymore!
Do you allready know when de next "release" will be released?
