### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Claw22000** [AzuraCast/AzuraCast#6091]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

Fresh install

### What happened?

I can't pull logs it just hangs with trying to do so.  I will explain how to recreate it and if you can help pull info let me know what to do and I will try. 

It originally started as the same issue on the rolling release.  Difference there was it was after doing an upgrade. I eventually game up and reinstalled.

Fresh install of Ubuntu 20.04 server in a VMware VM with 8 Cores 2.2Ghz each and 8G of Ram 600G storage.

followed the install guide.  Installs just fine

get in setup the initial setup works fine.

Add the first few thousand songs.  I have them separated alphabetically by directory. so 0-9 is one A1 is one A2 is another and so on.  I try to keep no more than 5000 songs in each directory.

After uploading the 0-9 folder I then added the directory to the playlist and then started the station.  worked just fine.

uploaded the next directory and added it to the playlist and continued like this for a while.  all was well.  It got late so decide to go to bed and have it upload the rest of the directories.  

In the AM I see it was done and then 1 directory at a time added them to the play list.  This time they added much quicker than usual.  

I noticed that the new additions were not increasing the playlist file count or becoming available to request.

Check debug and there was over 7million messages.  Tried to clear them and the page eventually hangs.  Refresh and the number dropped little.  Refreshing occasionally to monitor it eventually it stopped going down and started increasing again.  

pressed the button again and did this for a while.  I remembered a similar issue on the rolling release and a reboot would clear them all out at once and it would eventually start pulling the song into the list.  Tried it again here and then upon reboot I get the 502 bad gateway.  Cannot access it at all.  Tried to do the command (docker-compose logs -f azuracast) and it just hangs.  

I have searched for this error and none of them really seem to match my issue and not being able to pull the logs properly I have no idea what the issue is.  

All of the Files are MP3 128Kbit.  There all files that were Mod and XM's that I converted to MP3 to make it easier to work with.  They play fine in the normal player and the songs that did play while it was working didn't have issues.  

I am not super familiar with Docker even though I have used it for several different servers.  Typically I follow the directions and it just work.  My guess it the system simply can't take the total of 144019 files even separated in to 38 total folders.  

I'm fine with starting over again if I need to but would like to know what I did wrong in the first place to avoid this happening again.  

What I typically do is create a snapshot before the upgrade so I can easily remove it if it fails.  Well the one time I didn't on the rolling release was the time it happened initially.  figured on the reinstall I would choose Stable to see if that helped.

And Advise is appreciated.

DrClaw

**Comment by Claw22000** [comment]
Thank you this is working.  I just have to do it slower and keep an eye on it.  would be nice if there was a clear all messages button that truly cleared the Queue fast enough to get out of a mess once your in it.  Might want to make an note for fresh installers that they will need to put the files in slowly to not have an issue.  I to intend to make a snapshot once its up so any future upgrades are actually able to be rolled back easily.

Confirmed this was the issue on the new install.  I did end up starting over again and it is working this way.  

Not sure what happened the first install was working .  Files went in slowly that time as I was converting them and putting them in. But an update did kill the server.  If I have it happen again I will try to get as much info as I can to share it with you.  

Thanks for the awesome project!

**Comment by Moonbase59** [comment]
@Claw22000 I’m just a user like you, but apparently ran into the same problem. So all thanks should go to the developer(s) of this project, Fortunately, @BusterNeece chimed in on my above issue and he’ll keep an eye on this, because an issue it is.

**Comment by Claw22000** [comment]
Well an update is due here.  This time I snapshotted with VMware first Thank god!  So ran the update and same thing immediately goes to Bad Gateway after completion.  Not sure whats happening but will not be updating anymore.  Hopefully this is something that can be fixed.  I will try to check this later.  What if anything can I do to help track this down.  I know once Bad Gateway happens I cannot pull logs from it or I would have.

Let me know if I can help.

**Comment by Moonbase59** [comment]
I find that—[given enough resources](https://github.com/AzuraCast/AzuraCast/issues/6095#issuecomment-1436664889)—AzuraCast in the current rolling release versions can well handle ~150k files (Station overview shows _"LiquidSoap is currently shuffling from 273251 uploaded songs and 29 playlists."_ but that number is so high because songs appear in more than one playlist.

I tend to be rather impatient, so directly after an update I also see "502 Bad Gateway", and after that, the station shows offline for a moment. Keep in mind that on a complete restart, with our collection size, it really has to do a lot of stuff upon startup. So if I wait a few minutes (usually ~5–6 minutes), everything works fine as intended.

You sure you weren’t also just a little too impatient?

**Comment by Claw22000** [comment]
Giving it a shot.  I have it some time before but I will make sure to time it this time around.

Suggestion to the Devs.  When updating or restarting (which should be an option due to OS updates) Before starting any of the station(s) get the web admin site up and allow people to monitor the progress of the starting of the station(s).  

this would really help with trouble shooting as it will then at least allow access to the logs, even it it can't start the station.  

This time I updated via the terminal.  Start to finish to update complete was ~2min 30sec.  Watching a second window with htop I could see after it said finish there was clearly something running as used CPU increases considerably over normal operation.  

Waited for the stop watch to hit 20min before checking the page again Still 502 Bad Gateway.  

I would be happy to grant access to this machine to any Dev to poke around and reperform this process to see what is going on to possible help other folks. 

System specs are 8 Cores @2.2Ghz and 8G ram.  

Let me know if there is anything I can try if you are not able to or don't want to have access to it. 

this is installed on an isolated machine so it will not be a problem if you need to take it down to view things.

Appreciate anything in advance. 

DrClaw
