### ISSUE TITLE
[Feature Request] Support Original Year, Decade in a filetype-independent way

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6092]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #46b71d7 (2023-02-16 4:28)

### What happened?

Sorry to "misuse" GH Issues for this, but the 1000 character limit on the "Suggestions" page was just too small!

**Many of us need (and use) the Original Year a song was published, and possibly even the Decade,** to make playlists, say, like "Best of 80’s Rock". For this—using well-tagged files—it would be necessary being able to specify Custom Fields that _work in both MP3 and FLAC_ (possibly other formats, too).

I tried setting up an "Original Year" custom field (from ID3v2 Original Year) which works great with MP3 _but not with FLAC_. I know Vorbis Comments are rather free-format, but most taggers (like MusicBrainz’ Picard) use the field `ORIGINALYEAR` for this. Could this please be implemented in a way that you can select like "Original Year" from the list, and get it indepently of the file format used?

---

While we’re at it, having a "Decade" in the format "XXXXs" (like `2020s`) would also be very helpful for many of us. It’s a string and stems from the Original Year, or—as a fallback—from YEAR (of publication) and can be calculated as "replace last digit of Original Year (or Year) by a zero and add the letter "s". So Original Year 1982 would become "1980s". Many of us actually use MusicBrainz Picard to store this field already in

- In `comment:Songs-DB_Custom1` for MP3.
- A Vorbis Comment field like: "1980s (Songs-DB_Custom1)" for FLAC.

Can’t offhand remember why it’s called `Songs-DB_Custom1` (there are others like `Songs-DB_Custom4` for the band’s country of origin), but it was required for interoperability with other software that uses _last.fm_ data. It’s used in Picard’s _ [Last.fm.ng-Plugin](https://github.com/fdemmer/Picard-Last.fm.ng-Plugin).

---

**Having these available in a filetype-independent manner would surely be a great help for many of us** in building better playlists, so I’d much appreciate if it could be looked into. I wouldn’t be able to code it myself, but glad to help diagnosing, testing and have a look at the code.

The main chore would surely be to build "translation tables" so the same tag could be read from different file formats and stored in the DB. **Since MusicBrainz and Picard have (fortunately) evolved as a de-facto-standard for good tagging, I’d strongly suggest checking Picard’s code and use the same tables they do.** That should ensure best overall compatibility and interoperability across most platforms and applications, and give AzuraCast the "extra edge".

More about Picard’s tag handling and field association:
- [All about tag mapping](https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html) for the various file formats (including differences for ID3v2.3 and ID3v2.4)
- [picard/formats](https://github.com/metabrainz/picard/tree/master/picard/formats) – current Python code for tag handling

### Relevant log output

```shell
—
```

**Comment by guiltlab** [comment]
While I'm definitely interested in more tag support in AzuraCast, I can give a workaround for now, using Custom Fields: https://your.site/admin/custom_fields

![image](https://user-images.githubusercontent.com/45518224/219865647-e642be40-9a01-4217-a1bc-754688a0c5bf.png)

I have not tried ORIGINAL YEAR, so I can't confirm or deny that it doesn't work as a custom field with FLAC, but I definitely use the YEAR field with FLAC files without issues. You can easily retag all your files by copying the value in original year to the year field, for example using foobar2000 I set the YEAR tag by using the data in the DATE tag, through the "format from other fields" option in the properties dialog box.
I'm sure it's possible to do the same with the decade, assigning it to one of the available fields in the custom fields list (by picking a random field you don't use).

**Comment by Moonbase59** [comment]
Thanks for trying to help! I actually tried YEAR and it works, but I’m not willing to mess up a 150k songs database built and tagged carefully over ~30 years. Besides, I do need YEAR, too, for finding the release date of, say, a later version of the album, like a remaster. That could have 1995 as YEAR (release date of the remaster) and ORIGINALYEAR as 1980 (original release year of the album/song). Of course, when building a playlist with songs from the 1980’s, I’d want to include this song, even if it was from a remaster album. :-)

Thanks for the suggestion of a brief at the features site, will do.

**Comment by guiltlab** [comment]
Ah, I see, if you're already using the YEAR tag, then of course my approach won't work. But you can probably apply my second suggestion (using a random unused field available in the list of custom fields), surely there must be a few available tags to try ?
I will also try the original year tag on my FLAC files and report what I see.

**Comment by Moonbase59** [comment]
Gee, thanks! Happy to see there are others like me, who’d like to be able to build even better playlist experience for our listeners _within_ AzuraCast! :-)

**Comment by guiltlab** [comment]
I was indeed not able to use ORIGINALYEAR or ORIGINAL YEAR as source tag in custom fields for FLAC files. Did not try with mp3 files.
As a troubleshooting test, I tried adding an original year custom field directly from the azuracast interface, and it is being kept after saving changes, it's visible in the custom fields part of the JSON response when searching for the file in the API, however the value does not seem to be added to the file itself, I could not find it anywhere. So I'm not sure what's happening there.

**Comment by Moonbase59** [comment]
For safety reasons, I actually mount my main music collection _read-only_ (no one except me is allowed to modify the actual files—have seen too many softwares messing up my tags), so writing something back (except in the DB) is not an option here.

I think a general, filetype-independent tag mapping must be programmed into AzuraCast, much like MusicBrainz Picard has it (see links above). This would allow using custom fields independently of the underlying file type.

**Comment by guiltlab** [comment]
> Thanks for trying to help! I actually tried YEAR and it works, but I’m not willing to mess up a 150k songs database built and tagged carefully over ~30 years. Besides, I do need YEAR, too, for finding the release date of, say, a later version of the album, like a remaster. That could have 1995 as YEAR (release date of the remaster) and ORIGINALYEAR as 1980 (original release year of the album/song).

I just found out that for any tag that has several words, you need underscores between the words in the field name. So ORIGINALYEAR or ORIGINAL YEAR are not recognized as custom fields, but ORIGINAL_YEAR works.

**Comment by Moonbase59** [comment]
not stale

**Comment by Moonbase59** [comment]
For some example files, see https://github.com/AzuraCast/AzuraCast/issues/6093#issuecomment-1553910678.

**Comment by Moonbase59** [comment]
I always miss that darn bot’s closing actions. Please keep open.

**Comment by BusterNeece** [comment]
Looking into this one and I think it may be upstream from us, honestly.

When we process media, we use the `php-getid3` library, which parses and then returns for us a list of metadata, both in aggregate and individual tag provider (id3v1, id3v2, and vorbiscomment) arrays.

The translation of the actual name of the metadata value into a PHP key/value array takes place inside that library. It seems that, for the most part, it indeed does match the conventions used by software like Picard, though it isn't a perfect match.

I certainly don't want AzuraCast to get into the business of parsing metadata directly. As you've shown, that's a rabbit hole we are not interested in going down; we are quite satisfied with the "good enough" we have now if it means avoiding diving into a subject that will only cause us frustration.

The only thing I can think of that would ensure we're using Picard-esque tagging formats would be...to use Picard itself, as in to call its CLI in some way that would facilitate it returning basically a JSON dump of the metadata associated with a track. I'm looking through Picard's CLI docs and I'm not certain such a thing actually exists. It doesn't seem to be meant for that kind of programmatic use by other applications. If there's such a tool out there, though, that can leverage Picard's internal tagging and processing code to allow third-party apps to read/write metadata, then we'd implement that in a snap.

**Comment by Moonbase59** [comment]
I can understand that very well! Can’t go down every rabbit hole (though I sometimes do), especially when concentrating on an _application_ that’s supposed to be robust and "good enough" for most users. I’d have used _getID3_ myself (and actually done so with PHP projects in the past)—it might well be the best choice currently.

Re: Picard. No, you can’t tap in that way—it’s simply not meant for that. With Python, I’d always use _Mutagen_ (the underlying tagging library programs like _Picard_ and _Quod Libet_ use), but we’re on PHP. ;-)

All good, just a small nuisance, because I tend to search for original year more often. But I can as well use software like _Quod Libet_, _Clementine_/_Strawberry_ and _Guayadeque_ to search things and generate playlists locally. Using my little bash scripts [_ql-playlists_](https://gist.github.com/Moonbase59/a62363d61a4dcb596bd27d464368a9a4) and [_pl-copyfiles_](https://gist.github.com/Moonbase59/3ced819f3beb5cfa648d8ed888bc6ad1) plus an _sshfs_ mount, and the new "Empty playlist" function, selecting music and uploading it to the station(s) can be done without too much effort.

In any case, thanks for always keeping an eye on AzuraCast’s robustness and ease-of-use.

**Comment by BusterNeece** [comment]
@Moonbase59 We can and do call out to programs in other languages in AzuraCast...I swear I looked high and low and I guess it didn't dawn on me that "mutagen" was the name of a name of a media metadata library, not some sort of...other unrelated library.

And yeah, that's what I meant. Picard itself is a finished UI product and we wouldn't interface with its CLI, but if its tagging tools were accessible, we very well could use those.

**Comment by BusterNeece** [comment]
Looking into it, and Mutagen is pretty neat. I'd have no problems using it if someone were to write a little batch utility that took a M3U playlist in and spit out a JSON feed with metadata on the files specified, and/or to use it for writing a JSON file via another CLI type command.

Right now I don't think it's a high-yield enough exercise to do all of that myself, but if it was done, I'd be open to using it.

**Comment by Moonbase59** [comment]
Well, Mutagen is actually the best library for handling most tags efficiently. Sorry I didn’t explain better, somehow thought you might know it.

But…

- it’s low-level, so wouldn’ŧ solve aggregating tags that are called differently in different file formats. The "tag mapping" and things like deciding whether to use, say, ID3v2 `TIT1` or `GRP1` to store "grouping" is more higher-level, and that is where Picard excels—as a tagging tool. We’d have to re-engineer too much of Picard’s logic to make it feasible for not-so-often use cases.
- it’s Python. So yes, we’d need some wrapper, which may well introduce new problems.
- the Mutagen tools that come with it, like `mid3v2`, don’t handle all file types, and don’t do JSON.

We could—in theory—use `exiftool` (a Perl script mainly for image tagging), which _can_ output JSON data for almost any file type. But I don’t know what _their_ underlying tag reading code does, and how good it actually is…

Let’s take `Calvin - Barracuda Girl-id3v2.3.mp3` from the `testfiles-genre.zip` I once sent you, and do a `exiftool -json "Calvin - Barracuda Girl-id3v2.3.mp3"`:

```json
[{
  "SourceFile": "Calvin - Barracuda Girl-id3v2.3.mp3",
  "ExifToolVersion": 12.40,
  "FileName": "Calvin - Barracuda Girl-id3v2.3.mp3",
  "Directory": ".",
  "FileSize": "16 MiB",
  "FileModifyDate": "2023:05:19 03:49:10+02:00",
  "FileAccessDate": "2023:08:29 16:56:16+02:00",
  "FileInodeChangeDate": "2023:05:19 04:56:00+02:00",
  "FilePermissions": "-rw-rw-r--",
  "FileType": "MP3",
  "FileTypeExtension": "mp3",
  "MIMEType": "audio/mpeg",
  "MPEGAudioVersion": 1,
  "AudioLayer": 3,
  "AudioBitrate": "320 kbps",
  "SampleRate": 44100,
  "ChannelMode": "Stereo",
  "MSStereo": "Off",
  "IntensityStereo": "Off",
  "CopyrightFlag": false,
  "OriginalMedia": false,
  "Emphasis": "None",
  "ID3Size": 81398,
  "Title": "Barracuda Girl",
  "Artist": "Calvin",
  "Track": "13/15",
  "Album": "Euro Disco: The Lost Legends, Vol. 20",
  "PartOfSet": "1/1",
  "Genre": "Disco; Euro Disco",
  "Compilation": "Yes",
  "Media": "CD",
  "BeatsPerMinute": 129,
  "Language": "eng",
  "Date": "0705",
  "OriginalReleaseYear": 1986,
  "Year": 2018,
  "Grouping": "Disco",
  "Warning": "[minor] Frame 'TSOP' is not valid for this ID3 version",
  "PerformerSortOrder": "Calvin",
  "Publisher": "Disco Magic Melody",
  "Comment": "(Songs-DB_Custom1) 1980s",
  "UserDefinedText": "(MusicMagic Fingerprint) AQ1HU2Q89Br/H6MXNRd7COAM+xncEW0Nfg9uDyAJAwbeCPcFGgyoBLALQwsuBvgErQSjBKkDZAOpArECWAJMAeYBpgGwAYsBrQGGAVIBdAFT+ovCI92JB6Yl7x05GuYLXhWvNYMcSxbVDCIgnBM0CoMQbgYMFKkGzBB9FBgK+wc7BfUGBAQnBWMDbgJfAcEBjgFgAc4BrQF7AaQBewFMAUsAAx9g3hwBAvZY3Qr1gQQNB4tdKNd95cX58QZiAufvOOL9/fIEIwI48ZLvuAAj/cX8qf6h/tX+M/7P/lH+Tv7j/5z/MAAW/1P/5/+2/7L/7f0ezfFWZvgrFG38YNoy9JwDAhij7MvmZNPyFOgNlP4J/7D9qvgX+fT7BgLR/vD/X//7AKsA1AG9AM4AmABmAJsANwBOAGQAgQA9ACUAMwAxAInoqREDB2cW5gqqO5UI4PHV5wLHONWYNnMM3Ahv9XfcxADIE84E6/Wf78X+v/9o/Ej95/+e/bj9Yf5cAAYAA//2AAr/0wCWADkADABe//8AAOfoHYD2kwm0BZMVvP5SE+glYxSYEqUh3Lj/y875AQAs+Nzg8/F16+7iPPZV/Pn7H/t+/G/7Iv0l/tP/xf9T/1r/ZP7j/0f/Wf9R/zf+/gOIEv/cN/9HR4Y18AiP+Eb9WvOz9HTuEb+/9UHuE/Zv+Q38CexL9tftv+5Q91P+mvuB/Wf9yf9Y/ez+owAK//j/1wAU/2AACf+P/9//7v9cNjQxJQ==",
  "PictureMIMEType": "image/jpeg",
  "PictureType": "Front Cover",
  "PictureDescription": "",
  "Picture": "(Binary data 58497 bytes, use -b option to extract)",
  "DateTimeOriginal": "2018:07:05",
  "Duration": "0:07:07 (approx)"
}]
```

We see that `exiftool` adds additional information that isn’t in the file’s ID3v2.3  tags. The tags aren’t referenced by their code (like `TCON`) but by a mapped internal name. The Language part of `COMM` and `TXXX` fields is missing, their description is output as a value in parentheses (`Songs-DB_Custom1) 1980s`). Some tag frames (like `TXXX` `XFade`) are silently left out, others generate warnings (`TSOP`—intentionally violated the spec there, it officially only came in ID3v2.4). Etc, etc.

Also, things like ID3v2.3’s `TDAT` & `TYER` frames (`DDMM` and `YYYY`, respectively) have been discontinued in ID3v2.4 and replaced by a combined `TDRC` frame (`YYYY-MM-DD`). _Lots_ of pitfalls…

Probably—for now—not worth the effort, just to make some perfectionists like me happy…?

The idea behind all that was mainly that I know many stations that are genre- and decade-based, and just love to know the original (first) release year and decade of a song that might have been re-released umpteenth times. Even for a 2023 remaster, you’d probably like to know that it belongs to "1970's Rock". Unfortunately, original year is called differently in each file type, and the decade has never been standardized—just a convention I brought up 15 years back or so, and many have followed, albeit the tag has a shitty name.
