### ISSUE TITLE
Missing multiple-genre support

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6093]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #46b71d7 (2023-02-16 4:28)

### What happened?

While evaluating AzuraCast, I find that apparently _multiple genres_ aren’t supported. The DB only shows _one_ genre per song, even if it has multiple genres tagged.

Now genres with ID3 in MP3 are a mess—as we all know—, but I suggest this could easily be improved by using _MusicBrainz Picard’s_ way of doing it, for example by

- for MP3: reading ID3v2 TCON and splitting it into an array separated by `; ` (semicolon blank; the older `/` has been deprecated for some time since a slash could be in the genre text)
- for FLAC: reading the (possibly multiple!) GENRE Vorbis Comments

I don’t know how the DB is structured right know, but it should be easy to build a "Genre" table from existing files, and set up song→genre and genre→song relations, so searching for genre(s) would be easier, all songs with certain genre(s) could be found, and possibly even a multiple-choice (check buttons) could be made.

Many of us (and Picard) also use "Grouping" as kind of "Main Genre", plus "Genre" for the sub-genre(s). The main genre can or cannot be repeated as the first item in the Genre field, depending on preference, application needs and _last.fm.ng_ plugin settings. So it would be nice if this can also be read as separate value, or—second best—added to the genre list.

- for MP3: ID3v2 `TIT1` (normally used) or `GRP1` (iTunes compatible)
- for FLAC: Vorbis Comment `GROUPING`

I trust this would be **a much-needed and great addition to AzuraCast for many of us** and allow for much easier building of great playlists _within AzuraCast_.

I’m not that great a programmer, but I’d be willing to assist in thinking this out, testing and making it work.

### Relevant log output

```shell
—
```

**Comment by BusterNeece** [comment]
I gotta admit, I just don't see this as being all that critical, to be honest.

Our ingestion tools will already support pulling Genre information from both MP3/ID3v2 sources and FLAC/VorbisComment sources, and will reconcile both types into our "genre" field (and then correspondingly write both back to their correct fields for the format).

Beyond that, supporting multiple genres in a one-to-many way would introduce a great deal of overhead for us just to solve a problem that could just as easily be solved with a single genre field separated by a delimiter.

**Comment by Moonbase59** [comment]
With FLAC this isn’t feasible, due to the structure of Vorbis Comments.

With MP3 ID3v2.3, I already use a `; ` (semicolon+blank) separated `TCON` but the library you use seems to read only the first genre (i.e., I have `Rock; Humour` and it picks up `Rock` only.

**Comment by BusterNeece** [comment]
If you want to send me over some sample files that have the comments set up in the way you're describing, I can see about maybe parsing those properly.

**Comment by Moonbase59** [comment]
@BusterNeece Oops, missed this one. Here goes: I took a FLAC file, converted it to MP3, OGG and WMA so that you have the same data for the more often used file types, and tagged/saved each using MusicBrainz Picard 2.7.3.

The files have a _Grouping_ (»main genre«) of »Disco« and _two genres_ each: »Disco« and »Euro Disco«. They also have a _release date_ of »2018-05-07«, _original date_ and _original year_ of »1986«.

[testfiles-genre.zip](https://kaufen-ist-toll.de/download/radio/testfiles-genre.zip)

**Comment by Moonbase59** [comment]
Darn the bot… How can I reopen this?

**Comment by Moonbase59** [comment]
Thanks! This might not be top priority, but I wouldn’t like it to vanish…

**Comment by BusterNeece** [comment]
@Moonbase59 Glad I kept this one in my inbox, because after looking through how our media is processed, I found the obvious cause; our parsing library was splitting things by semicolon into multiple values, but we were just looking at the first value and not smartly looking at every value across every tag format we ingest.

I've reworked our media processing to be a lot more thorough about that kind of thing, and especially to support multiple entries in a single ID3 tag. This should make multiple genres display and work correctly.

**Comment by Moonbase59** [comment]
Yep, what I said. Tagging is a mess. I remember (long time ago) when working with getId3) I had problems en masse. ID3v2.3 tags were often "separated" by '/', or ','  (which I wouldn’t allow anymore nowadays, since these characters could very well be legal _inside_ a value), or NUL-sparated (which, I _think_, is still legal in one odd case).

Then, if you only had _one_ DB field to store them, you’d at least be able to use a "contains". But in any case, when writing back, to formats like ID3v2.4 or Vorbis Comments, yoou’d have to _split_ those again, since these use multiple (same) tags containing only one value each. Etc, etc., …

And of, course, there’s "grouping" in various variants (and tags, sometimes misused), most commonly used as the "main genre" (say "Rock") while genre being used for "sub-genre" or "style" (say "Alternative Rock", "Indie Rock"). Only the interpretation varies—in ID3v2.3, almost everyone uses `TIT1`, only iTunes uses `GRP1`. (Also messing up (TXXX:)WORK which everyone uses except iTunes—they use `TIT1`.)

With Vorbis Comments (FLAC etc.), it’s much easier: All tags uppercase, freely named, multiple same tags with different values allowed (one value per tag). ID3v2.4 tried to also do that, btw. Of course—with that scheme—suddenly everyone starting _naming_ tags differently.

The best bet, and I mean it, is to stick with Picard’s tag mapping, they keep current and do _everything_ right. And would be the "master tagging program" for serious collectors anyway. But even Picard allows so set some configuration for exotic edge cases (and hardcore iTunes lovers).

Oh, well. One can’t have everything, I guess. Then again, my suggested settings and strict tagging rules, even down to a rather fixed file naming convention, have made life easier for a lot of radio people, and a few million files having been tagged this way I know of.

**Comment by BusterNeece** [comment]
@Moonbase59 I was more intent in this case on just fixing the specific situation you were referring to; now that's fixed on our end.

Indeed, if we were to go all-in on making tagging a first-class thing in AzuraCast, we'd likely just build right on top of Picard.

**Comment by Moonbase59** [comment]
I’m on Rolling Release #[d2ca5eb](https://github.com/AzuraCast/AzuraCast/commit/d2ca5eb22a09096756e78498145d147fb2e82685) (2023-08-22 1:05) now, ready for testing.

What was the command again to reprocess all files?
Or should I click all base folders in my UI and do a _More → Reprocess_?

**Comment by BusterNeece** [comment]
`./docker.sh cli azuracast:media:reprocess`

**Comment by Moonbase59** [comment]
Okay, says
```
Marked 161614 records for reprocessing.
```
Media queue shows chunks of 100, like we had.
Let’s see how fast it’s this time around, if I remember remember correctly it took around 23 hours last time (has to get the files through a 1 Gbit NFS connection, after all).

Is there any way to see how many are left to process, or detect when it’s finished?

**Comment by Moonbase59** [comment]
The first reprocessed files are coming in. It seems to work in principle, but **genre lists are cut off** at some point, regardless of the file being FLAC or MP3. For comparison, I show the "Music Files" and the _Quod Libet_ list of the same tracks.

Let’s hope this is just some display length problem and the values are ok in the database.

FLAC example:

![Nite Radio – Mozilla Firefox_010](https://github.com/AzuraCast/AzuraCast/assets/3706922/1300a735-ff45-4c9e-be27-ba91db8b8623)

![Pipi AA - La Düsseldorf - Quod Libet_001](https://github.com/AzuraCast/AzuraCast/assets/3706922/099d51ac-6b9a-4502-a2f1-3acf48889f6a)

MP3 example:

![Nite Radio – Mozilla Firefox_011](https://github.com/AzuraCast/AzuraCast/assets/3706922/9aa5f370-47b6-4c37-83de-cceb1fbd342c)

![Pipi AA - La Düsseldorf - Quod Libet_002](https://github.com/AzuraCast/AzuraCast/assets/3706922/420556b9-2bec-41df-a8bc-b6d28d805be8)

(I have the "2raumwohnung - Kommt zusammen" album in two different versions, that explains the dups.)

**Comment by Moonbase59** [comment]
Looks like you define the genre field length based on the original ID3v1 spec (128 byte header, max 30 chars/frame). **Nobody**, repeat **nobody** should use _ID3v1_, _ID3v1.1_, _ID3v1.1b_ or _ID3v2.2_ anymore today! They only lead to confusion (if saved together with ID3v2.3/ID3v2.4, which is possible), or have restrictions long outdated. _Everything_  out there nowadays can handle at least _ID3v2.3.0_ or _ID3v2.4_!

Strings are theoretically endless in length, being $00 (or $00 $00 if UTF-16) terminated, but some restrictions apply: The total ID3 tag can’t be more than 256 MB, and the extended header might specify a string length restriction of (none)/1024/128/30 bytes.

Being pragmatic here, I’d say even with modern long genres like "Progressive Psychedelic Rock", and, say 5 or 6 joined, using a `VARCHAR(255)` for the combined tags should be long enough for some time to come, and at the same time not blow up the database too much. What do you think?

**Comment by Moonbase59** [comment]
Looking forward to that, really. Just now re-processing, will test afterwards. Thanks a bundle!
