### ISSUE TITLE
Error after (rolling) update: 502 Bad Gateway + PHP 512M not enough

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6095]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #46b71d7 (2023-02-16 4:28)

### What happened?

After having managed to get my ~150k files into AzuraCast using a PHP max. memory of `512M` and tediously building a 149k file playlist, all seemed to run just fine.

Suddenly in the evening (2023-02-18) an upgrade message showed up, insisting that I need an upgrade. So I shut it down using `docker-compose down` and did the upgrade using `./docker.sh update-self` and `./docker.sh update`.

On the newly started system, the message that I needed to upgrade persisted, so I did it all again. Same result.

So from pure frustration I tried the "Upgrade from Web" via the Web UI. AzuraCast didn’t start up anymore but presented a `502 Bad Gateway` page instead. The 4 CPU/4 GB server showed heavy activity and an average load around 2–3.

I then entered a console inside the container using `./docker.sh bash` and checked out my `app-2023-02-19.log` (attached as `AzuraCast App Log PHP 512M.txt`). It showed that my PHP 512 MB were exhausted!

So I tried setting up a PHP max memsize of `1G` in my `/var/azuracast/azuracast.env` and started again. The `app-2023-02-19.log` (attached as `AzuraCast App Log PHP 1G.txt`) now shows no more memory problems, but still no luck and the `502 Bad Gateway` page.

Help, please! Be it only an evaluation, I’d still hate to waste another 2 days getting my music into the system… chunk by chunk…

For the time being, I’ll keep the system as it is, for possible further diagnostics.

---

Attachments:

[AzuraCast App Log PHP 512M.txt](https://github.com/AzuraCast/AzuraCast/files/10775556/AzuraCast.App.Log.PHP.512M.txt)

[AzuraCast App Log PHP 1G.txt](https://github.com/AzuraCast/AzuraCast/files/10775557/AzuraCast.App.Log.PHP.1G.txt)

**Comment by Moonbase59** [comment]
**Very odd.** I did one final experiment, shut down the AzuraCast Ubuntu 22.04 LTS VM, updated my Arch-based ArcoLinux host, and rebooted the whole machine. Then I started the AzuraCast VM again, and the dockers. It now seems to work again, albeit has several errors in the startup process.

I copied the startup messages after the `docker-compose up` (no daemon, wanted to see all) and attach it here for further diagnosis. It looks like the data is still there. Phew!

[AzuraCast docker startup log after complete reboot.txt](https://github.com/AzuraCast/AzuraCast/files/10775609/AzuraCast.docker.startup.log.after.complete.reboot.txt)

**Comment by BusterNeece** [comment]
@Moonbase59 I feel like perhaps you're pushing the limits of our system's capabilities. I'm not sure that I have any immediate solution for your issues, and I admittedly am a little overwhelmed by the _volume_ of issues streaming in about this.

I will do my best to address these things as possible.

**Comment by Moonbase59** [comment]
@BusterNeece Please don’t feel obliged to start full-time debugging for me alone now! :-) It’s mainly me evaluating the current state of AzuraCast and—yes!—pushing it a bit, to check out reliability. Also, the huge amount of feedback is so that it doesn’t go under and can be diagnosed/used by all of us, and hopefully helps in making this wonderful system even better. Just trying to give a little back here. I know you’re working hard on all this and greatly appreciate it, believe me.

Just let me know if and how I can help.

**Comment by guiltlab** [comment]
This may be a useless comment, but just in case...

> Suddenly in the evening (2023-02-18) an upgrade message showed up, insisting that I need an upgrade. So I shut it down using docker-compose down and did the upgrade using ./docker.sh update-self and ./docker.sh update.
On the newly started system, the message that I needed to upgrade persisted, so I did it all again. Same result.

Did you run the update commands as sudo ? When I tried ./docker.sh update without sudo a while back, it didn't update correctly (the CLI messages said it updated, but it didn't in reality).

I have no input to offer on the other problems, sorry.

**Comment by Moonbase59** [comment]
Thanks. And yes, I did run run the update commands as root.

I _had_ to give PHP 1 GB of memory before it worked again, total consumption is around 2.3 GB and a load average between 0.6 and 1.7, using 4x i7 2.5/3.5 GHz CPUs, running in a Ubuntu 22.04 Server VM on top of an Arch-based Linux.

Seems it works for the moment, except for a few minor glitches like "Synchronization Not Recently Run. The routine synchronization task has not run recently. This may indicate an error with your installation." popping up from time to time (goes away after some time though), the On-Demand page not being able to handle that many songs, and rescanning of songs only being possible in batches (I do 100 "band folders" per batch, containing from one to many albums each).

The latest update (to Rolling Release #[f38c25b](https://github.com/AzuraCast/AzuraCast/commit/f38c25b7dee716b46ff68e8351cfd5f6cc9615e2) (2023-02-17 10:48)) worked okay. The 502 Gateway error is there when starting up but it eventually works after a few minutes.

**Comment by Moonbase59** [comment]
The latest update to Rolling Release #[94efd77](https://github.com/AzuraCast/AzuraCast/commit/94efd77a7d03b2a9429dd6f011cf06caae7d8209) (2023-02-20 3:57) brought more sync tasks and a faster startup time. I’m just rescanning my media, but so far all looks ok.

My current non-default settings:

- In `.env`:
  - `NGINX_TIMEOUT=3600`
- In `azuracast.env`:
  - `PHP_MAX_FILE_SIZE=256M`
  - `PHP_MEMORY_LIMIT=1G`
  - `PHP_MAX_EXECUTION_TIME=60`
  - `SYNC_LONG_EXECUTION_TIME=3600`

My `docker-compose.override.yml`:

```yaml
services:
  web:
    volumes:
      - /mnt/Musik/Tagged:/var/azuracast/stations/azura_radio/media/Tagged
      - /mnt/Musik/Schraeg:/var/azuracast/stations/azura_radio/media/Schraeg
      - /mnt/Musik/Other:/var/azuracast/stations/azura_radio/media/Other
```

Processing bottlenecks are mostly due to network speed: My `/mnt/Musik` is a NFS read-only mount onto my main music server.

---

Closing this for the time being, to reduce clutter.
