### ISSUE TITLE
media sync task runs and azuracast goes back to playing the error message.

### ISSUE THREAD

**Issue by stickbear2015** [AzuraCast/AzuraCast#6098]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #94efd77 (2023-02-20 3:57) • Docker • PHP 8.2

### What happened?

when azuracast starts, things are fine, up to and until the media sync task runs, then the system just sits and loops the error file.
I couldn't put the logs in the appropriate box, so I'm attaching the files.
[Azura Errors from app log.txt](https://github.com/AzuraCast/AzuraCast/files/10783954/Azura.Errors.from.app.log.txt)
[liquidsoap-errors.log](https://github.com/AzuraCast/AzuraCast/files/10783959/liquidsoap-errors.log)

**Comment by BusterNeece** [comment]
@stickbear2015 Anything else in the app log errors? I can see how this would prevent the worker process from working correctly, but I'm not sure how that would also yield the "next song" process failing...

**Comment by stickbear2015** [comment]
@BusterNeece you and me both, here's the last 10K of the app log.
[app-2023-02-20.log](https://github.com/AzuraCast/AzuraCast/files/10784424/app-2023-02-20.log)

**Comment by BusterNeece** [comment]
@stickbear2015 Sounds like your database is having trouble. I'd try restarting the whole service. I'm pushing up some fixes that should make things more error-resilient, but it may not fix your particular issue.

**Comment by stickbear2015** [comment]
@BusterNeece I've docker-compose down and docker-compose up -d at least once, and for a bit of interesting trivia, if I restart liquidsoap from the station profile page things fix themselves, for a time, then vomit again. Note that when I docker-compose down && docker-compose up -d restarting the entire docker stack that fixes it to, for a time. Was this what you meant by "restart the entire service"? If their's something else I should restart, let me know.  I could just reboot the entire box to restart the world, but if their's a service that needs to be manually restarted outside of docker and docker-compose that isn't restarted with docker-compose down and then docker-compose up -d feel free to school me.  I'm willing to try anything at this point. Note that this instance has recently been moved to a full on dedicated bare-metal instance so hardware specs, ram, etc. and the issues you and I previously encountered with stalling because of accessing the storage are now null and void, thank the gods. That's another story for another time when you catch me on discord. :-)

**Comment by stickbear2015** [comment]
@BusterNeece I just updated to
6d81fa
it played a song, and then went right back to what it was doing before and looping the default error file.
I posted a log previously, in my last reply, so hopefully that gives some insight.
If you feel it's necessary, I do have a backup from two days prior to the last stable release, I could switch to stable, restore the db, re-run the migration to make sure the db's got everything for the latest stable release, and see if that, at least for now, stabalizes things, while you see if you can figure out this rather interesting broken. laughs.
:-)
Let me know, or if you want me to hang out while you kick this around internally.

**Comment by stickbear2015** [comment]
Hello,
I just thought I'd check on this issue to see if their was an update so that the auto bot that closes issues doesn't squish the issue. :-)

**Comment by BusterNeece** [comment]
@stickbear2015 No update I'm afraid. I don't know from looking at the logs what's wrong with your installation.

**Comment by stickbear2015** [comment]
so in doing some further checking, because I'm mounting a host machine folder for my station storage via an override file, something was niggling at the back of my mind about the azuracast user (UID 1000).

**Comment by stickbear2015** [comment]
so things were still acting strange, playlists not doing what they should, etc. and in discussions with my other sys admin, it was determined that parts of the SQL database had become corrupted. We've since rebuilt the entire infrastructure from a clean slate, and things are stable and the issue reported in this issue has been officially resolved. I do note that adding 27,618 media tracks to a playlist at once does implode just a bit, but that's an issue for another issue, and if I'd not gone the route of adding things in smaller chunks to the playlist I could have probably solved it by extending the time outs, but enough with my rambling. I've gone ahead and closed this issue.
