### ISSUE TITLE
Disk Space Growing

### ISSUE THREAD

**Issue by sachinshakya507** [AzuraCast/AzuraCast#6105]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.7 Stable • Docker • PHP 8.2

### What happened?

I have around 50 radio stations.
Every day my disk space is growing.
azuracast_db_data folder is taking around 62 GB of my disk space. Is it expected to take such huge disk space.
In couple of days i might run out of storage. In that case what can i do.

**Comment by sachinshakya507** [comment]
My disk is almost full now.
/var/lib/docker/volumes/azuracast_db_data/_data/ibdata1 file is alone taking 51G of my disk space.
Is it expected that to be toot huge .
How can i resolve disk full issue now.

**Comment by BusterNeece** [comment]
@sachinshakya507 Without knowing what's filling up your records, it's hard to advise you of what to do. There are settings in System Settings for what level of analytics to keep and how long to keep history records, and you could tweak those to reduce the total size of your database.

**Comment by sachinshakya507** [comment]
Thankyou @BusterNeece it helped with my issue.
