### ISSUE TITLE
Iframe error on Chrome Incognito

### ISSUE THREAD

**Issue by honoluluman2** [AzuraCast/AzuraCast#6107]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

On my WordPress site, it seems that when a user is in **Chrome Incognito** on the page with the Radio Player iframe. The iframe doesn't load. After inspection i found in console the error ''Failed to read the 'localStorage' property from 'Window': Access is denied for this document.'' 

On the same page i am also using the history embed Widget that is loading correct.

The above problem also applies for Requests widget. 
Run many tests on clean wordpress installs, even using the azuracast demo iframe.

**Comment by guiltlab** [comment]
I can confirm this behavior. It doesn't happen on the history widget, interestingly.

**Comment by honoluluman2** [comment]
@BusterNeece problem is not solved in chrome incognito.
