### ISSUE TITLE
HLS Segment Overlaps

### ISSUE THREAD

**Issue by jitheshvijayakumar** [AzuraCast/AzuraCast#6108]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.7 Stable

### What happened?

I have enabled HLS stream for my station and it's segments are overlapping while listening.

Config : 
segment_duration=4
segments=5
segments_overhead=2

### Relevant log output

```shell
# HLS Broadcasting
aac_hifi = %ffmpeg(
    format="mpegts",
    %audio(
        codec="aac",
        samplerate=44100,
        channels=2,
        b="128k",
        profile="aac_low"
    )
)
hls_streams = [("aac_hifi", aac_hifi)]

def hls_segment_name(~position,~extname,stream_name) =
    timestamp = int_of_float(time())
    duration = 4
    "#{stream_name}_#{duration}_#{timestamp}_#{position}.#{extname}"
end

output.file.hls(playlist="live.m3u8",
    segment_duration=4.0,
    segments=5,
    segments_overhead=2,
    segment_name=hls_segment_name,
    persist_at="/var/azuracast/stations/<>/config/hls.config",
    "/var/azuracast/stations/<>/hls",
    hls_streams,
    radio
)
```

**Comment by BusterNeece** [comment]
@jitheshvijayakumar This is likely an upstream issue with Liquidsoap. We just directly call Liquidsoap's HLS output script to handle our own HLS streaming purposes.

**Comment by jitheshvijayakumar** [comment]
@BusterNeece Can you share the liquidsoap config that you are using for HLS.
