### ISSUE TITLE
azuracast indicates only internal ip addresses.

### ISSUE THREAD

**Issue by svandernaalt** [AzuraCast/AzuraCast#6109]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

At first I could see external ip addresses, but now only see internal ip addresses by the number of listener page. How can I change this?

**Comment by BusterNeece** [comment]
Are you using a reverse proxy in front of AzuraCast, or a service like Cloudflare? You may need to make sure the right headers are being sent through so we get the correct IP address. Some users have also reported that Docker's "userland proxy" can cause issues similar to this. See this for info on how to disable that: https://docs.azuracast.com/en/getting-started/installation/optimizing#disable-userland-proxy
