### ISSUE TITLE
Song Title and Song Artist Not Showing and Songs Skipped

### ISSUE THREAD

**Issue by techbp** [AzuraCast/AzuraCast#611]
- **Installation Method:** 
Installation Method: Traditional

- **Host OS (if using Docker):** 
Host OS: Ubuntu 16.04

**Describe the issue in full detail, including screenshots if possible:**
In the public page, when playing - it should display the current song playing and the artist name but what is showing is Song Title then below Artist Name... and ALL song are played like someone is skipping it, so the result a song last for 20 seconds or so... 

Another question:
When I have multiple radio station setup (I have 3 now with my azuracast instance), when one radio is broadcasting, I cannot broadcast my other stations, it stays at "Pleast Wait.." forever. Each radio station differs port, so I think that's not the problem. Other than that, I'm I missing something - like additional/advance settings? 

Thank you

**Comment by SlvrEagle23** [comment]
@techbp Sorry for the delay in getting back to your issue.

If you manually visit the "Administration" page, then run the "Now Playing" synchronization task (the one on the farthest left side of the page) and let me know what it says, if anything?

This may be the kind of situation where I need to actually take a look at your specific setup. If you're comfortable with that, let me know and I can provide you with instructions on how to securely send your station's details over to me.

**Comment by techbp** [comment]
Sorry for the late reply. Was able to solve the issues by changing ports :-)
