### ISSUE TITLE
How to connect Wasabi?

### ISSUE THREAD

**Issue by webma5ter23** [AzuraCast/AzuraCast#6112]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.7

### What happened?

It tells me that the URI is not valid, I chose the Wasabi US East 2 (N. Virginia) region
uri: s3.us-east-2.wasabisys.com
https://docs.wasabi.com/docs/what-are-the-service-urls-for-wasabis-different-storage-regions

I'm in a Trial account, is that why?

**Comment by webma5ter23** [comment]
Update: I was able to connect but I don't know how to do it for each radio

**Comment by scysys** [comment]
`Update: I was able to connect but I don't know how to do it for each radio`

Just add multiple sasabi locations inside the storage locations.
After this edit each station and choose the media storage location under the administration tab.

**Comment by webma5ter23** [comment]
Thanks @scysys but doesn't let the radio edit, just add the storage separately but I don't think it works like this, right?

**Comment by webma5ter23** [comment]
Where do I get the folder prefix?

**Comment by webma5ter23** [comment]
Thanks @scysys  and @leakim69 for screenshots in post  #5201
