### ISSUE TITLE
About cutting off the song at the time point!

### ISSUE THREAD

**Issue by hillfm** [AzuraCast/AzuraCast#6113]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Maybe the newest version？I don't know！

### What happened?

I scheduled some spot,jingle,station ID at time point, But I don't know how to cut off last song and play a new song after the time point.It always continue to play the song last hour.

**Comment by s0t0na666** [comment]
Edit playlist, advanced tab

![image](https://user-images.githubusercontent.com/40716724/227208157-e9a3e808-cec1-4782-bc38-670ae18d2511.png)

Select: "Interrupt other songs to play at scheduled time." - this will ensure the track is played in scheduled time 

You can also select "Only play one track at scheduled time." if you want to play one jingle and go back to the program
"
