### ISSUE TITLE
Song requests of  scheduled playlists available all day long

### ISSUE THREAD

**Issue by netbladenl** [AzuraCast/AzuraCast#6115]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#768d577

### What happened?

Since last update it's possible to do requests of timed scheduled playlists.
This wasn't the case with the older versions. Can this be fixed?

### Relevant log output

```shell
none
```

**Comment by Moonbase59** [comment]
Did you uncheck "[_] Allow requests from this playlist"?

![Playlists – Mozilla Firefox_001](https://user-images.githubusercontent.com/3706922/221370589-332b6e0f-23d0-4975-adf9-34ea62b33c60.png)

**Comment by netbladenl** [comment]
No, but before it was only avalible during the playback time of the scheduled playlist with this checkbox on.

**Comment by Moonbase59** [comment]
Yeah, right, remember that was an [implemented feature](https://features.azuracast.com/suggestions/86320/song-request-contains-only-songs-related-to-playlist-loaded). And a good one. So really a bug.
