### ISSUE TITLE
Update error ./docker.sh update

### ISSUE THREAD

**Issue by inetactief** [AzuraCast/AzuraCast#612]
AzuraCast v0.8.2-2018.04 Beta (Docker) 
Centos 7.2 64 bit

When we do ./docker.sh update

First i get:  Update docker-compose.yml file? This will overwrite any customizations you made to this file? [y/N]  (we do no)

Then we get: 
In GenerateProxiesCommand.php line 87:

  Proxies destination directory '<info>/var/azuracast/www_tmp/proxies</info>' does not have write permissions.

azuracast:setup [--update] [--load-fixtures]

2018/06/11 09:43:32 Command exited with error: exit status 1

And @last we get Error response from daemon: conflict: unable to delete 7c5026733dfb (cannot be forced) - image is being used by running container 3a1f71406613

**Comment by SlvrEagle23** [comment]
@inetactief There seem to be a lot of issues that CentOS encounters when running Docker that no other host environment encounters. I suspect this may have something to do with SELinux and the permission changes under the hood that result from that, but I'm not sure.

Restarting the host server may fix the issue, or running 

```bash
docker-compose down
docker volume rm azuracast_tmp_data
```

before updating again might help.

**Comment by inetactief** [comment]
Selinux is disabled and i already restart the server.  
We  try to update Update docker-compose.yml. But  azuracast is not starting. 
The docker-compose.yml is empty. 

I try to fix it, now it works but many problems (update stil not working)  ssl not working only go to localhost in cet. 
How do i setup a new (good no localhost) domein name for let encrypte?

**Comment by SlvrEagle23** [comment]
@inetactief I'm not sure I understand your question. If your `docker-compose.yml` file is empty, you can always create a new one based on the [sample file](https://github.com/AzuraCast/AzuraCast/blob/master/docker-compose.sample.yml), though this may not have the customizations you may have made, or custom credentials (like database password) if you set them up that way.

**Comment by inetactief** [comment]
Thanks it works! When i do a update i still get @ last  
Error response from daemon: conflict: unable to delete 7c5026733dfb (cannot be forced) - image is being used by running container 0334d906390b

Already try
 docker-compose down
docker volume rm azuracast_tmp_data

**Comment by SlvrEagle23** [comment]
@inetactief Try `docker rm 7c5026733dfb` to manually remove that container. Repeat with any other containers that have that problem.

**Comment by SlvrEagle23** [comment]
@inetactief This issue is still open and marked as unresolved. Any update?

**Comment by inetactief** [comment]
I have update 1 week ago and i have the same problem. 
conflict: unable to delete filename
can not use docker rm filename.

**Comment by SlvrEagle23** [comment]
@inetactief This sounds like a case for a full system reboot. If you have a Docker container that won't shut down properly, that's usually a quick resolution for it.
