### ISSUE TITLE
Sequential playlists not static

### ISSUE THREAD

**Issue by wmfinck** [AzuraCast/AzuraCast#6122]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.7 Stable • Docker • PHP 8.2

### What happened?

This may not be a "bug" to a developer, but it is from my perspective as a self-hosting content producer. 

I am brand new to Azuracast, and want it to replace a few streams which I have always managed manually. That is mainly because the liquidsoap 2.x upgrade gives many errors for my old version 1.x scripts. Now using it after a couple of days, I see it has wonderful potential, except for a few quirks which make it very difficult for me to use. 

I made 7 sequential playlists, one for each day of the week, and carefully ordered the recordings, as it is important to me that they play in a prescribed order. I added each to the playlist in the precise order I want them to play. Each list is very close to 12 hours of play and contains 12-15 items. Some are songs, some are 2-hour podcast recordings. The songs are just filler to round out the number of desired hours and give listeners a break between podcasts. 

Immediately, Azuracast began changing the order of the playlists. Moving all songs to the end, randomly changing the order of long recordings. The songs are in a different subfolder. 

Yesterday I used the reorder feature to put all 7 playlists back into the correct order. I am hoping that they stay in that order, or I will never be able to migrate my streams away from the old system. But if I add one recording to a different, new playlist, its order changes on EVERY playlist in which that recording appears! Usually it is moved to the end of every playlist. 

**One thing I noticed is that when a recording is added to a playlist from the media page, every playlist which contains that recording is reordered.** This is the "bug". I would expect a sequential playlist to remain in sequence, to be static and not subject to random changes. It is burdensome to check and reorder nearly every playlist because I might add a title to a new playlist or remove it from an old one.

**Comment by Moonbase59** [comment]
Hm. I’m also using some carefully constructed sequential playlists (done with external software), and I’d also consider that a bug. Will have to test on the rolling release, though.

**Comment by Moonbase59** [comment]
Just gave this a quick check on Rolling Release #[2bdf611](https://github.com/AzuraCast/AzuraCast/commit/2bdf611fecbec3fddf80826d0b4321f375821690) (2023-03-03 21:39).

I had:

- Playlist A (sequential, scheduled, Interrupt other songs)
  1. ID
  2. Song
  3. Jingle
- Playlist B (sequential, general rotation)
  - added "ID" (same as above, from Media)

Result:

- Playlist A
  1. Song
  2. Jingle
- Playlist B
  1. ID

"ID" was _removed_ from Playlist A!

Something must be wrong somewhere here.
