### ISSUE TITLE
*Question* How can I expand port range in traditional installation 

### ISSUE THREAD

**Issue by Yusadolat** [AzuraCast/AzuraCast#613]
- **Installation Method:** 
- **Host OS (if using Docker):** 

**Describe the issue in full detail, including screenshots if possible:**
Hello there,
Quick question, How can I expand the port range like that of docker installation?
Thanks

**Comment by SlvrEagle23** [comment]
@Yusadolat The traditional installation uses the Uncomplicated Firewall (UFW) to manage port restrictions, and while it is fairly permissive, it does by default restrict the radio ports to the range of 8000-8999.

You can add new ports to the UFW range by running:

```
sudo ufw allow 11200:11299/tcp
```
