### ISSUE TITLE
Banned Countries select not visible

### ISSUE THREAD

**Issue by 01123581321345589144233** [AzuraCast/AzuraCast#6135]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#6f36430

### What happened?

Hi when i will block a contry i cannot see the contry is enabled. After save i reload the config but in the list the contry is not selectet as blocked.

**Comment by BusterNeece** [comment]
Fixed in the latest Rolling Release!
