### ISSUE TITLE
Admin page of Icecast-kh19 crashes Icecast – a known bug

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6137]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #6f36430 (2023-03-06 4:41)

### What happened?

Trying to go to Icecast’s admin page with Icecast-kh19 first shows 502 Bad Gateway, then crashes Icecast. Apparently a known [bug in kh19](https://github.com/karlheyes/icecast-kh/issues/403).

Just so you know we’re affected. It _is_ possible to restart Icecast via the UI.

**Comment by BusterNeece** [comment]
Latest update includes KH20. Is it fixed in that version?

**Comment by Moonbase59** [comment]
@BusterNeece @gunsar 
Rolling Release #[935d460](https://github.com/AzuraCast/AzuraCast/commit/935d46095cfdb508d08178eaa6a98c1ae2d50274) (2023-03-07 21:12), confirm fixed.

Thanks @karlheyes and @BusterNeece for a fast fix.
