### ISSUE TITLE
Unterbrechung bei Remote-Relays

### ISSUE THREAD

**Issue by PManuel1986** [AzuraCast/AzuraCast#6153]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #29d12b7 (2023-03-09 0:17) • Docker • PHP 8.2

### What happened?

Oft Unterbrechung bei Remote-Relays

![d8b133a5-b141-4de4-a39a-87c3e2c75b6a](https://user-images.githubusercontent.com/91166974/225894923-ee81dac1-345e-487b-82fe-76d62f6453b4.jpg)
![eb23ab02-7ba2-4536-9d46-460a2dad36a0](https://user-images.githubusercontent.com/91166974/225894928-0a8d9ece-91bd-488d-b240-e485a1bd2724.jpg)
![a61b1fe9-01db-497d-9efd-5c8c0b94b8c3](https://user-images.githubusercontent.com/91166974/225894929-943d257a-a452-4ba2-bc2e-517bf4d9bd0e.jpg)

**Comment by scysys** [comment]
Your use of German while expressing your problems is not ideal, in my opinion. Anyway, the error message "broken pipe" in Icecast typically denotes an unexpected interruption of the connection between two servers. This error frequently occurs in the context of relaying when the server that delivers the audio stream, the source of the relay, is no longer reachable or when the connection is broken for some other reason. Network, CPU and so on.... This is not a problem related to AzuraCast and not much where developers can help. Someone here can correct me when im wrong :)
