### ISSUE TITLE
How to move a working Azuracast to a new server

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#6158]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

The installation needs to be moved to a new server. This is a Docker installation. Backups and restores are super easy, but this process does not allow saving the existing version of Azuracast.

As a result, a new version is installed and the data is copied into it.

What is the best way to copy the system (like a snapshot) to a new server without changing the Azuracast version?

**Comment by ItsMitchh** [comment]
You can't 'save' the current version when moving over, this is mainly due to security risks with older versions and people wanting to stay on them. We don't support older versions either.

**Comment by eranwo** [comment]
@ItsMitchh Unfortunately, I can't agree with you, most updates are improvements or fixes for previous updates. In fact, there is not much difference between the stable and rolling versions in terms of stability. Don't get me wrong, I'm very appreciate the work of the developers here, led by BusterNeece, but if we want to use the system daily, it needs to be stable and correct.

When a perfect version like this is created, I prefer to stick to it and and at the same time checks the new versions on a test server, and when I identify a new version that is stable and correct according to the parameters, I upgrade.

As a systems administrator, I also postpone Windows operating system updates until I have made sure that they do not affect the system's stability. 

Azuracast has already crashed in the past when I restored a backup to a new server or updated version. If that happens, you are stuck with the error and can't go back.

Therefore, I believe it would be reasonable to allow users to choose whether to update or not when restoring from a backup.

**Comment by ItsMitchh** [comment]
Can you at least provide hte exact issues your currently having with your machine, which prevents you from going forward to newer versions.

**Comment by eranwo** [comment]
@ItsMitchh Yes, I can, but that's not the point. Every time you upgrade Azuracast, you run the risk of a system crash. 
When it comes to open source projects like this, it's legitimate, however, in order to avoid harming users, there should be a way to restore the previous state without updating the version.

If you're not sure you'll be able to use your backup, what's the point?

**Comment by danceradiouk** [comment]
If you want to downgrade to an older version of Azuracast you can do that, but you will need to do the Ansible installation method and install everything manually yourself, no docker etc.  As you say you are a system admin, then i'm sure you'll have no problem with this. 

If you are looking for a docker install of an old version, don't bother looking as there aren't any. So Ansible install of an old version or docker of the current version, choice is yours.
