### ISSUE TITLE
Custom stream URLs

### ISSUE THREAD

**Issue by KokaKiwi** [AzuraCast/AzuraCast#616]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Arch Linux

**Describe the issue in full detail, including screenshots if possible:**

Not really an issue, but is there a way to use custom stream URL for stations (and Streamer, etc.)
Notably I saw the reverse-proxy paths in the nginx configuration (`/radio/<port>[/...]`) and wondered why there was no way to actually use them in the UI...

NB: I've searched about it on the doc/issues but I haven't found anything, if it's already mentioned somewhere I missed it...

**Comment by KokaKiwi** [comment]
Ok I just saw the "Use Web Proxy" settings does set the radio stream URL to the proxyfied one...

**Comment by SlvrEagle23** [comment]
@KokaKiwi I see you found the setting to enable or disable the proxy URLs, but beyond that, there is currently not a way to specify a custom "Listen URL" for a given stream. There is a currently pending pull request that will resolve the issue, and once that's merged in, this will be possible.

**Comment by SlvrEagle23** [comment]
Closing as this has now been implemented via the custom listen URL feature on each mount point.
