### ISSUE TITLE
Play exactly once every x songs.

### ISSUE THREAD

**Issue by radiobellissima** [AzuraCast/AzuraCast#6162]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.17.7 Stable

### What happened?

Help 1 for song doesn't work properly.
There is no way to get 1 jingle x 1 song to play. Sometimes he plays 1 sometimes 2 and it can happen that he plays even 3 or 4 in a row. I attach photos.
![Test1](https://user-images.githubusercontent.com/57127248/226455220-e4a8ea20-e888-431e-9664-3c44de430130.png)
![Test](https://user-images.githubusercontent.com/57127248/226455252-f1f4696c-16db-4714-a790-a6b9862f0658.png)

**Comment by nunotfc** [comment]
i think i've found the cause of this.
when a song is picked and skiped because of repetition filter, somehow the playlist mechanism considers it as a song that in fact played, but no. i cant explain this so much more.

**Comment by radiobellissima** [comment]
Unfortunately not solved yet, a pity really any software from the old centova to the most recent can do it. You should simply mark the jingles category as non-songs this would prevent jingles from being counted as songs. At this point the bulk should be done, then understand by seeing the behavior if it still repeats 2 or 3 consecutively and from the logs understand why.

**Comment by wegGehamstert** [comment]
Please fix this.. It's for so long a big issue, and it is very annoying

**Comment by BusterNeece** [comment]
<img width="289" alt="2023-05-03 09_23_24-(Development) Song Playback Timeline - AzuraCast" src="https://user-images.githubusercontent.com/6744885/235950407-cb70545c-14db-4a97-9b86-b4afacb772a1.png">

As you can see in my local testing environment, even when I set the jingle to play "Once per X songs" and then have duplicate songs playing between them, I _still_ can't get this situation to happen. Scheduler works exactly as expected for me and has never deviated from that after several days of watching.

If we're going to get down to the bottom of what's causing this, we basically need exact reproduction steps, i.e. a way to reproduce this reliably with a specific set of setup steps. I certainly believe it's an issue that folks are running into, I just don't know enough to fix it or be able to reproduce it locally.

**Comment by radiobellissima** [comment]
Hello, I have studied the situation more carefully. In practice, perhaps an additional option on the playlists would be needed because effectively anything that goes on the air he considers it a song and this is not good.
I try to make you understand, if I want to carry out:
song
spot
spot
jingles
song
jngle
song
jingles
I can't do it because he considers spot as a song and puts the jingle in between.
Whereas I also have silent tones triggering commercials on shoutcast
jingles
silent tone
jingles
the listening result becomes
jingles
jingles
So to solve it you should increase an option or a simple check that indicates that spots, tones, etc. are not to be considered songs.
I really hope that with the translator the meaning is not changed and the problem is understood..

**Comment by radiobellissima** [comment]
Sorry but I have now recovered the photo.
Then there's this other thing that happens with the very short 2" seconds. He can't get it in between but he does put it after.
![Test](https://user-images.githubusercontent.com/57127248/235961167-c9f243fc-be6f-4292-a200-cd4a15af85f7.png)

**Comment by radiobellissima** [comment]
@BusterNeece  So maybe one of the problems we found is because I can't mark it as a jingle because I need to send the tag advert: - advert:
![Test](https://user-images.githubusercontent.com/57127248/235976816-4487b405-1106-49f7-9204-597ff019d9d1.png)

**Comment by BusterNeece** [comment]
@radiobellissima Ohh, so it's a non-jingle playlist but you want to exclude it from calculations...interesting.

**Comment by BusterNeece** [comment]
Well, the other issue with wanting to be able to not consider tracks even if they're not "jingle mode" would actually be a new feature, so you should submit that over at https://features.azuracast.com/ so we can get that in the new feature queue.

I think what's being reported here is specifically a bug in our scheduler occasionally playing a "once per x songs" track back-to-back instead of skipping a track like it's supposed to. This issue should certainly not be happening any more.

**Comment by radiobellissima** [comment]
@BusterNeece Done, let's hope the translator helps. 
:-)

**Comment by wegGehamstert** [comment]
So do i understand this right, @BusterNeece, 

> This issue should certainly not be happening any more.

Did you pushed a new fix for the problem? Because it's also occuring for me still. Or are you still looking into it?

**Comment by BusterNeece** [comment]
@wegGehamstert The fix for the "shouldn't include jingles in the once-per-x-songs calculation" problem was fixed quite a while ago.

If you're still having issues now, then the previous recommendation stands: we need a specific list of steps to reproduce the bug reliably so we can identify what's causing it in this particular case.

**Comment by wegGehamstert** [comment]
> @wegGehamstert The fix for the "shouldn't include jingles in the once-per-x-songs calculation" problem was fixed quite a while ago.
> 
> If you're still having issues now, then the previous recommendation stands: we need a specific list of steps to reproduce the bug reliably so we can identify what's causing it in this particular case.

Okey, then i will make this for you. I will send it as soon as possible

**Comment by wegGehamstert** [comment]
Steps how to reproduce the error with "Play once x songs"

1. Have two playlist wich contains jingles.
2. Mark both of them as "Jingle Mode"
3. Set the order of the songs to random
4. Set the playlist type to "every x songs" and set the value to 3 and for the other playlist 7
5. Make sure that there is at least one playlist that plays music in between.

Every number will eventually overlap. With 3 and 7 it takes a little bit until this is the case, but then that's exactly what happens: The two jingle playlists play back to back which doesn't make any sense.

![image](https://user-images.githubusercontent.com/78315888/235996005-67177d7a-075b-4907-82d6-54e4df52447f.png)

**Comment by wegGehamstert** [comment]
Oh I'm sorry then I think we always talked a little past each other with this bug. i thought this was easy to fix
Then I got it wrong. Does that mean it is currently simply not possible to avoid this due to the effort involved?

**Comment by BusterNeece** [comment]
@wegGehamstert Yeah...in your case, it is possible to implement what you're wanting but only with "Advanced" playlists and custom Liquidsoap code. We don't have native support for grouped playlists in the web UI yet, and it's a pretty big project to build in.

**Comment by wegGehamstert** [comment]
Yes, I can completely understand that, my request is complex. I also tried my hand at custom Liquidsoap code, but somehow it never really worked. I'll probably have to study it more.

But thank you anyways for your amazing work @BusterNeece! I'm very grateful to you for Azuracast, it can do so much and what I'm doing here is complaining at a high level
