### ISSUE TITLE
Error on trying to add SFTP Backups storage location

### ISSUE THREAD

**Issue by CouinCouin** [AzuraCast/AzuraCast#6163]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.7 Stable

### What happened?

Hi, 

I'm trying to add a SFTP storage location for backup, but I get this error when I save : 

> ValidationException at /var/azuracast/www/src/Exception/ValidationException.php L37: Object(App\Entity\StorageLocation): Storage location SFTP: could not be validated: Unable to check existence for: /test

I don't know what is "/test" ? 

If someone has an idea :) 

Thanks

**Comment by CouinCouin** [comment]
Hi, 

How can I resolve this ?  
The server is installed by docker installation. 

Thanks :)

**Comment by BusterNeece** [comment]
Check the permissions on the remote SFTP server. If it's failing to create a directory, it doesn't have the appropriate permissions.

**Comment by CouinCouin** [comment]
I though AzuraCast was trying to create a "Test" flolder on its server , to make the backup and then to send to the SFTP server. 

On the SFTP server (these of the radio website) I use the same user/password than I use with filezilla, and provided by the hoster (ionos), so AzuraCast should be able to create the "Test" folder. 
I created this folder manually but I stil get the same problem :(

**Comment by BusterNeece** [comment]
Without any more specifics or logs I'm afraid there isn't much I can do to help here.

**Comment by CouinCouin** [comment]
Logs from which side you need ? 
The web hosting is a mutualized server (https://www.ionos.fr/hebergement/hebergement-web#packs), where final users have no SFTP logs access :(

**Comment by aukfood** [comment]
Hello, up, I have the same issue.

**Comment by BusterNeece** [comment]
@aukfood Can you please provide significantly more information? What's going wrong, what error message are you seeing, what logs have you checked, etc?
