### ISSUE TITLE
Autologin not working

### ISSUE THREAD

**Issue by ivellios1988** [AzuraCast/AzuraCast#6170]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.7

### What happened?

Each time I log in to my installation of AzuraCast I check the 'remember me' option in order not to have to provide my password and 2fa code. Autologin works then correctly until I restart my PC because then I need to provide credentials again since AzuraCast doesn't log me in automatically.

Is it supposed to work this way or maybe I'm doing something wrong? Maybe it has something to do with my browser (Google Chrome) 'silently' updating itself when it's not used?

**Comment by netbladenl** [comment]
This is because of 2fa. if you disable 2fa it should work like you want it to work
