### ISSUE TITLE
Cannot add new stations

### ISSUE THREAD

**Issue by sachinshakya507** [AzuraCast/AzuraCast#6174]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.7 Stable • Docker • PHP 8.2

### What happened?

I have successfully added 34 radio stations but i couldn't add new stations any more
I am getting this error.
![Screenshot from 2023-03-24 10-07-13](https://user-images.githubusercontent.com/107086988/227424019-54868e82-68d1-4e08-afcf-f772d97fee02.png)

**Comment by BusterNeece** [comment]
@sachinshakya507 We have a specific range of ports that we use to assign to stations, and if you have enough stations in one install, it's possible to run out of that port allocation. You can expand it by updating, and then when the updater asks if you want to customize settings, choose "Yes", then extend the port range used by stations to a larger range.
