### ISSUE TITLE
Internal API returning error 500 (Internal Server Error)

### ISSUE THREAD

**Issue by lamasbr** [AzuraCast/AzuraCast#618]
**Installation method:** Docker
**Host OS:** Ubuntu 14.04.4 LTS

**Describe the bug:**
I ran `docker-compose logs -f` and noticed a lot of internal API errors with 500 Internal Server Error:
```
stations_1     | 2018/06/14 05:42:29 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/<station name removed>/media/music.mp3".
stations_1     | 2018/06/14 05:42:29 main.go:90: Change in content: triggering web hook
nginx_1        | 172.18.0.5 - - [14/Jun/2018:05:42:29 +0000] "POST /api/internal/1/notify?api_auth=API_AUTH_KEY_REMOVED HTTP/1.1" 500 199 "-" "Go-http-client/1.1" "-"
stations_1     | 2018/06/14 05:42:29 main.go:100: Webhook returned response 500 Internal Server Error verify API key.
```

I'd like to know how to solve this problem. I already tried to update (`./docker update`) and it also did not fix the problem.

**Comment by lamasbr** [comment]
@SlvrEagle23 I have updated AzuraCast now with some errors (#746 ). I saw the logs with docker-composer logs -f command and the described errors continues:

![image](https://user-images.githubusercontent.com/668513/44613626-35b56180-a7ec-11e8-8f6b-f334cc231287.png)

I don't have no API key or web hook on the system.

**Comment by SlvrEagle23** [comment]
@lamasbr Turns out API calls weren't logging properly to the unified logging stack, and thus weren't showing up alongside the `stations` container's calls.

Please update your AzuraCast instance and let me know if any specific error code pops up alongside the "Webhook returned response 500" line.

**Comment by lamasbr** [comment]
@SlvrEagle23 

![image](https://user-images.githubusercontent.com/668513/44623939-68c32800-a8b4-11e8-8fb9-aea6efa63a66.png)

**Comment by SlvrEagle23** [comment]
@lamasbr There are three ports that should be used on each station, one for outbound streaming, one for inbound API calls and one for inbound DJs. If AzuraCast is trying to connect to port 80, one of those likely isn't set. You should check your station's profile and verify that they're all set.

**Comment by lamasbr** [comment]
@SlvrEagle23 I have only one station and we use only AutoDJ (Liquidsoap).

Icecast port:
![image](https://user-images.githubusercontent.com/668513/44624207-b5f7c780-a8bd-11e8-9949-a6b9b3ceee1e.png)

Other ports:
![image](https://user-images.githubusercontent.com/668513/44624217-01aa7100-a8be-11e8-8db5-1a1eb444bad5.png)

My domain is on CloudFlare but the traffic don't pass through CloudFlare (we only use for manage dns records) and in AzuraCast system settings "Always use HTTPS" and "Use Web Proxy for Radio" is set to YES:
![image](https://user-images.githubusercontent.com/668513/44624229-6d8cd980-a8be-11e8-9e89-a4d4aea3d375.png)

**Comment by SlvrEagle23** [comment]
@lamasbr Figured out the problem. Should be fixed now. Update and try again.

**Comment by lamasbr** [comment]
Thank you! No more API errors now!
