### ISSUE TITLE
HLS CRASH - no EXTM3U delimiter

### ISSUE THREAD

**Issue by loan-talvat** [AzuraCast/AzuraCast#6184]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

sha256:3b5e2fd1f6e81802a1dd3ffa67ec392ad2d67b3911a1b0aad5de6633f139bba5

### What happened?

I encounter an amazing error on the player of the public page but also with an HLS.js integration, randomly the player gives me this error:
Object { type: "networkError", details: "manifestParsingError", fatal: false, url: "https://stream.DOMAIN.LTD/hls/[radio_id]/aac_hifi.m3u8", reason: "no EXTM3U delimiter", response: {…}, context: {…}, networkDetails: XMLHttpRequest }
​
The player tries to play this url: 
![image](https://user-images.githubusercontent.com/23056644/229083781-fe258b5d-e588-4108-bdc0-201da9a90174.png)

By checking it seems that aac_hifi.m3u8 (and probably the others) randomly generates an error in the playlist...

### Relevant log output

```shell
CONSOLE WITH HLS.js
Object { type: "networkError", details: "manifestParsingError", fatal: false, url: "https://stream.DOMAIN.LTD/hls/[RADIO_ID]/aac_hifi.m3u8", reason: "no EXTM3U delimiter", response: {…}, context: {…}, networkDetails: XMLHttpRequest }
context: Object { id: 0, level: 2, responseType: "text", … }
details: "manifestParsingError"
fatal: false
networkDetails: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
reason: "no EXTM3U delimiter"
response: Object { url: "https://stream.DOMAIN.LTD/hls/[RADIO_ID]/aac_hifi.m3u8", data: "" }
type: "networkError"
url: "https://stream.DOMAIN.LTD/hls/[RADIO_ID]/aac_hifi.m3u8"
```

**Comment by loan-talvat** [comment]
Hello, I come back this subject, any idea of a problem on the back of Azuracast?

**Comment by BusterNeece** [comment]
I think this may be an upstream issue with Liquidsoap, actually. It may be worthwhile to report it over there: https://github.com/savonet/liquidsoap

If they're curious about our HLS generation code, it looks like this:

```
# HLS Broadcasting
aac_lofi = %ffmpeg(
    format="mpegts",
    %audio(
        codec="aac",
        samplerate=44100,
        channels=2,
        b="48k",
        profile="aac_low"
    )
)
aac_midfi = %ffmpeg(
    format="mpegts",
    %audio(
        codec="aac",
        samplerate=44100,
        channels=2,
        b="96k",
        profile="aac_low"
    )
)
aac_hifi = %ffmpeg(
    format="mpegts",
    %audio(
        codec="aac",
        samplerate=44100,
        channels=2,
        b="192k",
        profile="aac_low"
    )
)
hls_streams = [("aac_lofi", aac_lofi), ("aac_midfi", aac_midfi), ("aac_hifi", aac_hifi)]

def hls_segment_name(~position,~extname,stream_name) =
    timestamp = int_of_float(time())
    duration = 4
    "#{stream_name}_#{duration}_#{timestamp}_#{position}.#{extname}"
end

output.file.hls(playlist="live.m3u8",
    segment_duration=4.0,
    segments=5,
    segments_overhead=2,
    segment_name=hls_segment_name,
    persist_at="/var/azuracast/stations/azuratest_radio/config/hls.config",
    "/var/azuracast/stations/azuratest_radio/hls",
    hls_streams,
    radio
)
```

**Comment by loan-talvat** [comment]
Hey ! :) 
After many tests, it turns out that Liquidsoap updates files constantly, and if we make a request precisely when liquidsoap updates the file, nginx sends an empty file or a file in progress...

My question is the following:
Given the architecture of HLS in azuracast, is it possible to add in the nginx configuration a rule or something to serve files only when they are available?
Or if necessary to make a PHP route that checks before returning?

Here below is a very stupid little script to spam the playlist file (the error appears approximately between 100 and 400 requests)

`<?php
ini_set('max_execution_time', 0);

$url = 'https://AZURACAST/hls/RADIO/aac_lofi.m3u8';
$error = false;
$call = 0;

    while ($error == false) {
        $call ++;
        $curl = curl_init();
        curl_setopt_array($curl, [
            CURLOPT_URL => $url,
            CURLOPT_CUSTOMREQUEST => "GET",
            CURLOPT_RETURNTRANSFER => true,
        ]);
        $response = curl_exec($curl);
        curl_close($curl);
        
        $lines =  substr_count($response,"\n");


        if($lines < 5000){
            $error = true;
            echo "Il y a $lines lignes, une erreur est détectée au bout de $call appels.<br>";
        }
    }
?>`

**Comment by BusterNeece** [comment]
Ah, I see what's going on.

I think honestly this should be fixed by the Liquidsoap folks. I'd recommend making a new issue there about the writes not being atomic on the filesystem. Atomic writes are rather simple to implement in most tools by just writing the file somewhere else, then renaming it into the right spot.

If we were to implement some sort of "shim" between us and the filesystem, it would wipe out a ton of performance in HLS streams and would bog down the server a lot more than it probably seems, given HLS is just a ton of little requests being made. Having it directly served by nginx is really the best way to handle that.

**Comment by toots** [comment]
From savonet/liquidsoap#3284:

> Thanks for reporting. This is addressed with https://github.com/savonet/liquidsoap/pull/3286 which I'll merge as soon as it's been properly tested.
> 
> Although this breaks the even API, I think that this is a good candidate for a rolling-release backport.
> 
> If y'all need a workround, it's possible to used a separate folder for nginx serving and use the (soon to be deprecated) "closed" event to move files when they are done writing.

**Comment by BusterNeece** [comment]
I saw the upstream commit was merged, so we've updated to the latest Rolling Release to test it out. Thanks @toots !

**Comment by loan-talvat** [comment]
Superb, however we tried to switch our instance to latest to fix the problem... but streamers can't connect, we went back to stable

Do you have any idea when there will be a next stable release?
Here is the new platform working with Azuracast in back for more than 20 associative radios in Brittany (France)
https://radio-boa.bzh
