### ISSUE TITLE
SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by SmOkEnksp** [AzuraCast/AzuraCast#6187]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #1443b06 (2023-04-01 16:29) • Docker • PHP 8.2

### What happened?

after setup ssl get error with cert
SSL_ERROR_RX_RECORD_TOO_LONG

**Comment by BusterNeece** [comment]
Not enough information to know what's causing this...is it happening with a domain pointed directly at AzuraCast with LetsEncrypt set up? Are you using a multi-site configuration, or something like Cloudflare?
