### ISSUE TITLE
Limited access

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#619]
Is it not possible to display only the "music files" and "playlists" in the dashboard for limited access to some users?

**Comment by SlvrEagle23** [comment]
@jonikane The "Manage Station Media" permission currently includes both music files and playlists, and has both view and edit permissions included. Splitting those up into separate permissions would be a new enhancement, but is definitely possible.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38909/make-playlist-management-a-separate-permission-from-media-management
