### ISSUE TITLE
when trying to enter the playlist to see the files inside it shows the error and I can't access it.

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#6193]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

xxx

### What happened?

when trying to enter the playlist to see the files inside it shows the error and I can't access it.

### Relevant log output

```shell
ApiException at /var/azuracast/www/vendor/meilisearch/meilisearch-php/src/Http/Client.php L199: Attribute `station_202_playlists` is not filterable. This index does not have configured filterable attributes. 1:22 station_202_playlists = 4194
```

**Comment by s0t0na666** [comment]
I'm having the same issue altough the error message was a bit differentbut still related to meilisearch. This is also causing jingles and intro not to be loaded. I don't know the exact error since I reverted back to the previous version.

**Comment by BusterNeece** [comment]
We've retired Meilisearch in favor of optimizing our overall query performance, so this shouldn't be an issue any longer.
