### ISSUE TITLE
Transition issue on live DJ mixes.

### ISSUE THREAD

**Issue by replayfactory** [AzuraCast/AzuraCast#620]
Looks like the is an issue when live source is connected to hardor input.

DJ usually use Traktor software to broadcast their live DJ mixes but on each track change audio stream stops for 1 or 2 seconds and logs reports :
```
2018/06/15 06:09:12 [fallback_5964:3] Switch to blank_5963 with forgetful transition.
2018/06/15 06:09:12 [dummy:3] Source failed (no more tracks) stopping output...
2018/06/15 06:09:17 [fallback_5964:3] Switch to audio_to_stereo_5960 with transition.
```
After some test I think this is not a blank detection issue. I noticed that issue happens when mixing software pushed new icy metadata to stream.

_Broadcasting Software : Native Instrument Traktor Pro 2.6.2
Traditional installation on Ubuntu 16.04 LTS
AzuraCast v0.8.2-2018.04 Beta
PHP 7.2.5-1_

**Comment by karndt84** [comment]
This is a very important note for people who want to stream with Native Traktor! This should be included in the documentation. I have set the DJ / Streamer Buffer Time to 20 seconds and it works wonderfully.
