### ISSUE TITLE
how to play audio link to audio tag

### ISSUE THREAD

**Issue by sankamaduranga** [AzuraCast/AzuraCast#6204]
[###](_url_) ### 
audio src="http://radio.kithuraawa.lk/api/station/1/file/81/play"> </audio

**Comment by sankamaduranga** [comment]
<audio src="http://radio.kithu-raawa.lk/api/station/1/file/81/play"> </audio>

**Comment by Moonbase59** [comment]
@sankamaduranga As far as I know, there is currently no API endpoint for playing arbitrary files (and with good reason).

The link type you show above (/api/station/1/file/81/play) is used within the media manager to initiate a download of a file, and can only be accessed if you’re logged in with correct user permissions.
