### ISSUE TITLE
Major load increase after update to rolling release

### ISSUE THREAD

**Issue by AaronUnmuted** [AzuraCast/AzuraCast#6205]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #fc3044e (2023-04-12 22:22)

### What happened?

After updating our rolling release server, we've had a huge increase in load (even higher than it was before, which was the issue we were trying to fix following the changes to Now Playing!). 

We're seeing the following load averages:
![image](https://user-images.githubusercontent.com/62389707/231705737-327373ba-4215-4c7e-b2e3-b2d911791138.png)

htop isn't providing much useful information:
![image](https://user-images.githubusercontent.com/62389707/231705838-4af63ad0-b899-4f18-9b89-84e2fb0446d6.png)

Stations don't actually seem to be broadcasting. No queued messages.
Not able to run 'docker-compose logs -f azuracast' as it just hangs.

Any help/guidance would be hugely appreciated. 

### Relevant log output

```shell
Unable to obtain docker logs.
```

**Comment by BusterNeece** [comment]
@AaronUnmuted This may have something to do with our recent `master_me` incorporation. Try updating again; we've temporarily reverted including that library in our collection.
