### ISSUE TITLE
The bug of nowplaying and gingle mode is back!

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#6215]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

cdb3311 (2023-04-16 5:12) • Docker • PHP 8.2

### What happened?

hello, the older bug of gingle mode and now playing is back! sometimes, not all time, song xx is played, after, play song xy and play a gingle. during playing of gingle, the xx name is shown in nowplaying..

**Comment by Moonbase59** [comment]
I think that’s an intended feature, at least if you have set "Hide Metadata from Listeners ("Jingle Mode")" in a playlist, say, the station id playlist. It _should_ show the jingles if this is not set.

**Comment by nunotfc** [comment]
yes, i agree, but it ahve to keep showing the song that played previously, and not one that played 1 or 3 songs ago. let me show you with a more consistent example. imagine you have playing the 1.mp3, 2.mp3, and 3.mp3. you play 1.mp3, play gingle, play 2.mp3. in the gingle before playing 3.mp3, im nowplaying it starts to show that is playing ,1.mp3 during the gingle playback, and not continue to show 2.mp3. it shows 1.mp3 during the jingle playback, and after plays and shows 3.mp3, that is correct.

**Comment by Moonbase59** [comment]
Hm. Works here, or maybe I completely misunderstand you. For a try, I unset "Hide Metadata from Listeners ("Jingle Mode")" in my _Station ID_ playlist, and waited until it hit in:

![Auswahl_206](https://user-images.githubusercontent.com/3706922/234028075-20f9bec4-0c4f-422e-86b3-79c1c1a428e1.png)

It played (and showed)
- "It’s Not Easy"
- "On The Air" (the jingle)
- "Panama-Boy"

When I _set_ ""Hide Metadata from Listeners ("Jingle Mode")"" in my _Station ID_ playlist, it only shows
- "It’s Not Easy"
- (no update while the jingle plays, "On The Air" _not_ shown)
- "Panama-Boy"

So the latter one is like what you experience.

**Comment by Moonbase59** [comment]
I still don’t understand—it is exactly as it _should_ be: If I tell it to omit the jingle metadata, it _does_. And vice versa.

**Comment by nunotfc** [comment]
ahaa, i cant explain more...
the bug is not with jingle mode...
the bug is with now playing. when you are with jingle mode checked, instead of omiting the data, after the 2nd or 3rd song, sometimes, not forever, it shows a previous played song...
if, for example, you play a song called "my love", and after you play a song called "lets go". with 1 jingle separating them. and you play a 3rd song called for example "good times". When the gingles that go from the "lets go" song to the "good times", instead of omiting data or continuing showing the "lets go"title, during the jingle selected to play it show s like "my love" song played other time, and, indeed, is just the jingle... i hope i can clarify more...

**Comment by Moonbase59** [comment]
Ah, I think I grasp it now… Seems a possible bug indeed, probably some timing or race condition.

**Comment by Moonbase59** [comment]
Are the jingles extremely _short_ (a few seconds only)? You could try using _longer_ jingles for a test, and see if it still happens then. Just in case it has something to do with crossfading and Liquidsoap not being fast enough or something…

**Comment by nunotfc** [comment]
right, all my jingles are like 2 or 3 secconds. in rare cases, 1.
