### ISSUE TITLE
master_me: Loudness jumps because ReplayGain applied AFTER master_me

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6216]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #cdb3311 (2023-04-16 5:12)

### What happened?

I’m trying out _master_me_ processing and get crazy (wrong) loudness values on playout. I _am_ using ReplayGain and in the LiquidSoap config it is applied _after_ master_me. This of course leads to wrong loudness corrections, because _master_me_ has done the work already, _then_ LS applies additional replay gain.

A tool like _master_me_ MUST always come _last_ in the processing chain.

Easy fix: Apply replay gain (and probably other effects) _before_ master_me. Put that at the end of the chain.

### Relevant log output

Snippet from the generated LS config (I was trying the "Music General" preset):

```liquidsoap
# Apply amplification metadata (if supplied)
radio = amplify(override="liq_amplify", 1., radio)

radio = ladspa.master_me(
    bypass = false,
    target = -16,
    brickwall_bypass = false,
    brickwall_ceiling = -1.00,
    brickwall_release = 75.00,
    eq_bypass = false,
    eq_highpass_freq = 5.00,
    eq_side_bandwidth = 1.00,
    eq_side_freq = 600.00,
    eq_side_gain = 1.00,
    eq_tilt_gain = 0.00,
    gate_attack = 0.00,
    gate_bypass = true,
    gate_hold = 50.00,
    gate_release = 430.50,
    gate_threshold = -90.00,
    kneecomp_attack = 20.00,
    kneecomp_bypass = false,
    kneecomp_dry_wet = 50,
    kneecomp_ff_fb = 50,
    kneecomp_knee = 6.00,
    kneecomp_link = 60,
    kneecomp_makeup = 0.00,
    kneecomp_release = 340.00,
    kneecomp_strength = 20,
    kneecomp_tar_thresh = -4.00,
    leveler_brake_threshold = -10.00,
    leveler_bypass = false,
    leveler_max = 10.00,
    leveler_max__ = 10.00,
    leveler_speed = 20,
    limiter_attack = 3.00,
    limiter_bypass = false,
    limiter_ff_fb = 50,
    limiter_knee = 3.00,
    limiter_makeup = 0.00,
    limiter_release = 40.00,
    limiter_strength = 80,
    limiter_tar_thresh = 6.00,
    mscomp_bypass = false,
    high_attack = 8.00,
    high_crossover = 8000.00,
    high_knee = 12.00,
    high_link = 30,
    high_release = 30.00,
    high_strength = 30,
    high_tar_thresh = -12.00,
    low_attack = 15.00,
    low_crossover = 60.00,
    low_knee = 12.00,
    low_link = 70,
    low_release = 150.00,
    low_strength = 10,
    low_tar_thresh = -3.00,
    makeup = 1.00,
    dc_blocker = false,
    input_gain = 0.00,
    mono = false,
    phase_l = false,
    phase_r = false,
    stereo_correct = false,
    radio
)

# Replaygain Metadata
enable_replaygain_metadata()
radio = replaygain(radio)
```

**Comment by BusterNeece** [comment]
Updated Rolling to put post-processing after Replaygain, provided you have the "include live broadcasts" setting checked.

If you don't, then post-processing happens earlier in the process (before the live DJ comes in), which means the replaygain/amplify work happens after it, because those apply to the composited stream with live included.

**Comment by Moonbase59** [comment]
Fantastic, will try these out! Having _master_me_ in AzuraCast really looks very promising!

**Comment by BusterNeece** [comment]
@Moonbase59 Also just a heads-up since you had mentioned it earlier, but I'm planning on adding another option alongside the preset to manually pick from common LUFS settings. Some folks have complained the defaults render their streams too quiet, and some folks are looking for -18 LUFS, so this will add some flexibility there.

**Comment by Moonbase59** [comment]
Excellent, love it! Maybe you could even make it a slider, like the _master_me_ GUI has? Might probably be enough to go in 0.5 or 1.0 steps, though.

**Comment by Moonbase59** [comment]
A little off-topic: On a 2 CPU, 4GB RAM VM, even when Meilisearch is eating CPU power, the LADSPA you use behaves quite well. I note a load average between 0.8 and 1.4 during normal use. So this should run rather well on data center VMs (probably opting for dedicated CPUs).

**Comment by Moonbase59** [comment]
Cheers for the quick fix—works like a charm now (and 2 LUFS too loud, as expected, hee hee). Running Rolling Release #[84166cf](https://github.com/AzuraCast/AzuraCast/commit/84166cf080b3ca8169769dd4e312af9e7d026e06) (2023-04-17 20:08).
