### ISSUE TITLE
Cannot update via Web

### ISSUE THREAD

**Issue by Hadhab** [AzuraCast/AzuraCast#6218]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #cdb3311 (2023-04-16 5:12)

### What happened?

Cannot update via Web

### Relevant log output

```shell
ConnectException at /var/azuracast/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php L210: cURL error 6: Could not resolve host: updater (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://updater:8080/v1/update
```

**Comment by nezia1** [comment]
Is your azuracast_updater container running? I had the same issue a few weeks ago and it was because my updater container had stopped.

**Comment by Hadhab** [comment]
> Is your azuracast_updater container running? I had the same issue a few weeks ago and it was because my updater container had stopped.

Not sure how to check that... Pls show me how to check that

**Comment by nezia1** [comment]
You can check it by running `docker compose status --all` from inside your AzuraCast directory.

**Comment by Hadhab** [comment]
it shows `unknown docker command: "compose status"`

**Comment by nezia1** [comment]
Either try `docker-compose status --all` or `docker ps --all` if the former didn't work

**Comment by Hadhab** [comment]
Its working now... My server had frozen so had to restart sand it started working automatically

**Comment by nezia1** [comment]
No problem! I'm glad you could fix it

**Comment by Hadhab** [comment]
facing the same error again

**Comment by SpeedyCharly** [comment]
> facing the same error again

Did you solve your issue ?  Found out that it's as simple as running [docker restart azuracast_updater] in var/azuracast

**Comment by Sakretsos** [comment]
Well, i have the same problem!
I found out on the web that you must add the hostname of the updater on /etc/hosts (linux users) but i dont really find a way to make it works.
Azuracast_updater is running but i get the bellow error.
`ConnectException at /var/azuracast/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php L210: cURL error 6: Could not resolve host: updater (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://updater:8080/v1/update`
Anyone have find a solution to share with us?

**Comment by SpeedyCharly** [comment]
The info I gave above is the solution to this exact error.
• Access Azuracast via SSL with root credentials;
• Send command;
cd /var/azuracast
docker restart azuracast_updater 
• Exit SSL and your WEB updater should now work

If no root access, then;
Sudo cd /var/azuracast
Sudo docker restart azuracast_updater

**Comment by Sakretsos** [comment]
> The info I gave above is the solution to this exact error. • Access Azuracast via SSL with root credentials; • Send command; cd /var/azuracast docker restart azuracast_updater • Exit SSL and your WEB updater should now work
> 
> If no root access, then; Sudo cd /var/azuracast Sudo docker restart azuracast_updater

@SpeedyCharly thanks for your answer!
it works like charm!

**Comment by Hadhab** [comment]
> The info I gave above is the solution to this exact error. • Access Azuracast via SSL with root credentials; • Send command; cd /var/azuracast docker restart azuracast_updater • Exit SSL and your WEB updater should now work
> 
> If no root access, then; Sudo cd /var/azuracast Sudo docker restart azuracast_updater

@SpeedyCharly Thank you for this... works well after following it...
