### ISSUE TITLE
Icecast config: Intro file paths have a double //

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6226]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #f33cb52 (2023-04-21 15:42)

### What happened?

Just cosmetic, doesn’t affect operation.

When adding intro files to mounts, the generated relative paths in `icecast.xml` have an extra `/`, like in:

```xml
<intro>../../../../..//var/azuracast/stations/niteradio/config/mount_3_intro.aac</intro>
```

**Comment by BusterNeece** [comment]
Fixed basically right as you reported it!
