### ISSUE TITLE
Public page edits

### ISSUE THREAD

**Issue by ohld** [AzuraCast/AzuraCast#623]
Hi, and thanks for the tool.
I'd like to change the station public page default player. For example to remove some elements from player or just to change their appearance. Also I'd like to change / add some html element.

I can do that with API calls but I like the ability to control the volume, see the song timing and get the list of passed tracks out of the box.

**Comment by ohld** [comment]
Can I change HTML parts of public page?

**Comment by xewl** [comment]
@ohld You could, but it could be overwritten on update.

I always set up my own player pages, which are socket/polling the Azuracast API. ;)

**Comment by ohld** [comment]
Oww @xewl . So Azuracast has socket API? Wow. I can't find it's documentation. Can you share the link? 

Btw. Can you share the code of your players? Are they JS-only or you use PHP?
