### ISSUE TITLE
Now playing out of sync in ver. 0.18.1

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#6232]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #ee5b2dc (2023-04-23 1:55)

### What happened?

Currently, the "now playing" feature takes a long time to update the song title (about 30-50 seconds ) this issue has already been fixed (https://github.com/AzuraCast/AzuraCast/issues/5623), but it has come back in the latest version.
It also takes a long time to get the song title after updating or rebooting the server. Until then, it displays "stream offline".

Master_me works great!!!

**Comment by BusterNeece** [comment]
@eranwo How many stations do you have running on one installation? The previous fix was meant to provide faster updates, but in turn it resulted in quite a lot of CPU/DB load. The recent revisions have reduced the total number of "Now Playing" processes that run at a given time. If you're having issues with  some stations "hanging" for long periods, then that could cause issues with the other stations.

**Comment by eranwo** [comment]
@BusterNeece My server has 12 cores and I run 40+ stations with an average load of 4-6. 
An old Azuracast version (0.14.1) is running on another server with the same spec and stations as the current server, with "now playing" running without issue and song title is updated almost instantly when a song changes. Also there is no special load on CPU (load average 3-4 )
Would it be possible to use the same method for "Now Playing" as in version (0.14.1) also on the latest ver.? 
It would be great if you could
