### ISSUE TITLE
Requests no longer work on public pages

### ISSUE THREAD

**Issue by thackmaster** [AzuraCast/AzuraCast#6234]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.18.1

### What happened?

I have requests enabled on multiple stations of mine. After updating, when on one of my public pages, clicking Requests now displays an empty list even though requests is enabled on the station.

**Comment by thackmaster** [comment]
Yes. I checked and nothing was adjusted between the updates. Public URL is [live.thackerbroadcasting.com/public/z96_mix](https://live.thackerbroadcasting.com/public/z96_mix) if that'll help. I don't know which logs might be applicable in assisting.
![image](https://user-images.githubusercontent.com/73045785/234143967-d083c350-479f-46d6-bfe2-15cfe8816ce3.png)
![image](https://user-images.githubusercontent.com/73045785/234144073-ef85a669-7c8d-4e4a-aa9c-339335a7ba8d.png)

**Comment by thackmaster** [comment]
Restarting the Meilisearch service from the dashboard didn't change the outcome. A full instance restart also did not fix the issue.

**Comment by BusterNeece** [comment]
Closing this issue for internal reasons. If anyone else is experiencing a similar issue, feel free to create a new issue.
