### ISSUE TITLE
Listing a playlist taking minutes with thousands of songs in the database

### ISSUE THREAD

**Issue by muzo178** [AzuraCast/AzuraCast#624]
**Installation method**
"Traditional"

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
When trying to load the songs in a playlist with about 10000 tracks in the database, the **list** request is taking about 3 minutes. Sometimes even longer.. 

**To Reproduce**
Please see video: https://www.dropbox.com/s/y365ndl8sqjkvri/AzuracastBug.mp4?dl=0

**Expected behavior**
Listing the songs in a playlist should be much much faster. This makes it pretty much unusable...

**Screenshots**
<img width="859" alt="screen shot 2018-06-18 at 12 18 04" src="https://user-images.githubusercontent.com/247520/41528068-b1d14624-72f1-11e8-868e-cc9fa1b56658.png">

**Comment by SlvrEagle23** [comment]
@muzo178 Yeah, that's definitely a problem! Sorry for any inconvenience there.

I'm actively looking into the issue and will update you as soon as I can. I'm also dealing with some personal health issues, and one of my development machines is out of commission briefly, so updates may be a little slow.

Just for clarity, is this only happening when viewing the files inside a given playlist? Not when iterating through the files normally?

**Comment by muzo178** [comment]
I’m sorry to hear about your health issues.I hope you feel better soon..

> Just for clarity, is this only happening when viewing the files inside a given playlist? Not when iterating through the files normally?

Yes, it is only happening when viewing the files inside a given playlist. When going through the files normally, it is fine.

**Comment by SlvrEagle23** [comment]
@muzo178 Thank you for your patience. I've been able to take a detailed look at the file listing functionality in the media manager, and fortunately there was ample room for optimization of the search/playlist view functions. They've now been significantly sped up, and you should notice a vastly lower performance impact from using these functions.

Please update and let me know if it has any impact on your setup.

**Comment by muzo178** [comment]
I just updated and the difference is huge. Great job and thank you.

**Comment by SlvrEagle23** [comment]
@muzo178 Excellent to hear. Just out of curiosity, what's the updated time for listing out a playlist's contents in your case? It should be significantly faster than before, but I want to make sure it's not still some unnecessarily high time.

**Comment by muzo178** [comment]
It is pretty much instant for a playlist of 5 songs, about 1.5 seconds for a playlist of 170 songs,  62 seconds for a general rotation playlist of about 9500 songs. Maybe a bit more room for improvement for the last case..
