### ISSUE TITLE
Yellow Pages (dir.xiph.org) gets wrong playing URL

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6241]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #4b05857 (2023-04-24 15:58)

### What happened?

Apparently Iceast, and thus its YP protocol, knows nothing about our playing URLs, especially if you sit behind a reverse proxy.

For instance, my playing URL is
```
https://radio.testradio.net/listen/testradio/radio.mp3
```

and _dir.xiph.org_ shows a playing URL of
```
http://radio.testradio.net:8000/radio.mp3
```
and, of course, cannot play the station.

Is there any way to correct this in AzuraCast, or do we actually have to manually modify reverse proxy settings (NGINX Proxy Managaer, in my case)?

**Comment by Moonbase59** [comment]
My Icecast configuration (names changed):

```xml
<icecast>
    <location>AzuraCast</location>
    <admin>icemaster@localhost</admin>
    <hostname>radio.testradio.net</hostname>
    <limits>
        <clients>499</clients>
        <sources>2</sources>
        <queue-size>524288</queue-size>
        <client-timeout>30</client-timeout>
        <header-timeout>15</header-timeout>
        <source-timeout>10</source-timeout>
        <burst-size>65535</burst-size>
    </limits>
    <authentication>
        <source-password>(PASSWORD)</source-password>
        <relay-password>(PASSWORD)</relay-password>
        <admin-user>admin</admin-user>
        <admin-password>(PASSWORD)</admin-password>
    </authentication>
    <listen-socket>
        <port>8000</port>
    </listen-socket>
    <mount type="normal">
        <mount-name>/radio.mp3</mount-name>
        <charset>UTF8</charset>
        <stream-name>Test Radio</stream-name>
        <stream-description>Non-public test &amp; evaluation server only</stream-description>
        <stream-url>https://radio.testradio.net/public/testradio</stream-url>
        <genre>Various</genre>
        <intro>../../../../../var/azuracast/stations/testradio/config/mount_1_intro.mp3</intro>
        <fallback-mount>/fallback-[128].mp3</fallback-mount>
        <fallback-override>1</fallback-override>
        <http-headers>
            <header name="icy-index-metadata" value="1"/>
            <header name="icy-version" value="2"/>
            <header name="icy-logo" value="https://radio.testradio.net/static/uploads/browser_icon/192.1678626043.png"/>
            <header name="icy-country-code" value="DE"/>
            <header name="icy-country-subdivision-code" value="DE-BY"/>
            <header name="icy-language-codes" value="deu,eng"/>
            <header name="icy-do-not-index" value="0"/>
        </http-headers>
    </mount>
    <mount type="normal">
        <mount-name>/radio.aac</mount-name>
        <charset>UTF8</charset>
        <stream-name>Test Radio</stream-name>
        <stream-description>Non-public test &amp; evaluation server only</stream-description>
        <stream-url>https://radio.testradio.net/public/testradio</stream-url>
        <genre>Various</genre>
        <intro>../../../../../var/azuracast/stations/testradio/config/mount_3_intro.aac</intro>
        <fallback-mount>/fallback-[128].aac</fallback-mount>
        <fallback-override>1</fallback-override>
        <http-headers>
            <header name="icy-index-metadata" value="1"/>
            <header name="icy-version" value="2"/>
            <header name="icy-logo" value="https://radio.testradio.net/static/uploads/browser_icon/192.1678626043.png"/>
            <header name="icy-country-code" value="DE"/>
            <header name="icy-country-subdivision-code" value="DE-BY"/>
            <header name="icy-language-codes" value="deu,eng"/>
            <header name="icy-do-not-index" value="1"/>
        </http-headers>
    </mount>
    <fileserve>1</fileserve>
    <paths>
        <basedir>/usr/local/share/icecast</basedir>
        <logdir>/var/azuracast/stations/testradio/config</logdir>
        <webroot>/usr/local/share/icecast/web</webroot>
        <adminroot>/usr/local/share/icecast/admin</adminroot>
        <pidfile>/var/azuracast/stations/testradio/config/icecast.pid</pidfile>
        <alias source="/" dest="/status.xsl"/>
        <ssl-private-key>/var/azuracast/acme/ssl.key</ssl-private-key>
        <ssl-certificate>/var/azuracast/acme/ssl.crt</ssl-certificate>
        <ssl-allowed-ciphers>ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS</ssl-allowed-ciphers>
        <deny-ip>/var/azuracast/stations/testradio/config/ip_bans.txt</deny-ip>
        <deny-agents>/var/azuracast/stations/testradio/config/user_agent_bans.txt</deny-agents>
        <x-forwarded-for>127.0.0.1</x-forwarded-for>
    </paths>
    <logging>
        <accesslog>icecast_access.log</accesslog>
        <errorlog>/dev/stderr</errorlog>
        <loglevel>2</loglevel>
        <logsize>10000</logsize>
    </logging>
    <security>
        <chroot>0</chroot>
    </security>
    <directory>
        <yp-url-timeout>15</yp-url-timeout>
        <yp-url>http://dir.xiph.org/cgi-bin/yp-cgi</yp-url>
    </directory>
</icecast>
```

**Comment by Moonbase59** [comment]
In https://github.com/karlheyes/icecast-kh/issues/417, I have explained why it would be beneficial to have an "adjustable" listener URL. If this turns out to be an upstream issue, you might want to chime in over there.

Maybe we can get get something up that could in turn be supported by AzuraCast…

**Comment by BusterNeece** [comment]
@Moonbase59 Likely nothing we can do on our end to expedite this, but I'll flag it as upstream in-progress; if Icecast-KH updates to support custom listen URLs then we can incorporate that.

I've also wondered if we could just "cut out the middleman" in a sense and actually send the YP data ourselves, since we have rich Now Playing data for stations...could be worth looking into.

**Comment by Moonbase59** [comment]
Yeah, let’s see if @karlheyes can come up with something. Icecast 2.5-beta3 is said to have "[Improved directory configuration including updated mechanism for listen URL submission](https://www.icecast.org/news/icecast-release-2_5-beta3/)" but, spelunking around in their code, I didn’t find anything immediately useful for this issue.

I also thought maybe AzuraCast could maybe directly talk to the yp-v2 servers, but it seems to me that would be kind of re-inventing the wheel and better kept within Icecast, especially since you’d have to react to lots of of events known only internally to Icecast, and in a timely manner. So I feel this is better left with Icecast.

In the long run, I feel Icecast can’t ignore requirements of the "modern world", where projects like Icecast and even AzuraCast are used as building blocks within larger systems, with appropriate adaptation (like listener URLs and SSL certs generated elsewhere, and probably proxied).

AzuraCast, in turn, might shine with more high-level playing data (via web hooks and [extra ICY-headers](https://www.stream-meta.info/version_2_headers.html)) to well-known aggregators like TuneIn, Radio.de, and others.

Just my 2 cents.

**Comment by BusterNeece** [comment]
I spent the better part of today working on a direct implementation of the YellowPages protocol, and while it was simple to do...I must say, the YP protocol is a product of a different time. It is not, even a little bit, built for how we serve radio stations in the modern web.

Basically, it's looking for `http://some-url:8000/stream.mp3`, where `some-url` points, directly via an `A` entry in DNS, directly to the same server making the outbound listing request. As far as I know, it doesn't even allow the server to be installed in a subfolder, as Icecast traditionally doesn't expect to be installed there.

So really, not only does this wipe out the potential for us to use our proxied `/listen/station/radio.mp3` URLs, but it also completely destroys the functionality for anyone with any sort of reasonably complex network topology between them and their domain name, whether that's CloudFlare or a load balance or something else.

Ideally, a directory like this would be based on something a lot more robust and yet also verifiable, like a challenge-response protocol that dropped something into `.well-known` to verify ownership, similar to LetsEncrypt et al.

I think if we ever set up our own radio directory (who knows, we might!) it would be based on a secure handshake like that.

**Comment by Moonbase59** [comment]
You’re right, the old (even v2) YP protocol is kinda anachronism nowadays… ;-)

That’s why I’m hoping @karlheyes could come up with something within Icecast that could make it a little more usable, while still being able to use the old, albeit well-known directories. After all, just scrolling through some random entries on dir.xiph.org, I found entries that indicate it _should_ somehow be possible:

- `http://s37.derstream.net/live.mp3` (no port)
- `http://web.radio.antennevorarlberg.at/av-2010er/stream/mp3?aggregator=icecastdirectory` (subfolders, no port, added parameter)
- `https://edge16.streamonkey.net/charivaristream-kult80er/stream/mp3?aggregator=icecastdirectory` (https://, subfolder, added parameter)

**Comment by Moonbase59** [comment]
@BusterNeece Karl got around adding an option for this in https://github.com/karlheyes/icecast-kh/commit/aa74340fb3571c467970fed762322db48b488844. see also https://github.com/karlheyes/icecast-kh/issues/417.

If anyhow possible, it’d be nice to (optionally?) use that in AzuraCast in order to have Icecast show the correct AzuraCast listen URLS, and thus update the yellow pages correctly. Finally!

Note _some_ YP providers can’t (yet) handle `https://` URIs, so for these the option to still use the old Icecast URIs might be needed.

This would really be neat, because we can save open ports and use proxies.

N.B.: I think we might as well go to the latest version, some other minor stuff has been fixed since.

**Comment by Moonbase59** [comment]
@BusterNeece Suggest moving to icecast-2.4.0-kh21.8.

**Comment by Moonbase59** [comment]
@BusterNeece I’m very happy to say that using <listenurl>…</listenurl> per mountpoint is working very well so far with

- dir.xiph.org
- icecast-yp.internet-radio.com

Station and now-playing info as well as the player links work on both, and finally our stations can be correctly listed.

Thanks @karlheyes for implementing this and @BusterNeece for switching to icecast-kh21.8!

Maybe AzuraCast could use this in mountpoint setup so a newbie wouldn’t have to fiddle with advanced settings per mountpoint.

**Comment by Moonbase59** [comment]
@BusterNeece Feedback on https://github.com/AzuraCast/AzuraCast/commit/5a73a41024825e331e4cc235aa607aa2fb8619e2 and https://github.com/AzuraCast/AzuraCast/commit/996bc43773b414ac1e72e270741bb26ba4409c38: The automatic filling in of `<listenurl>…</listenurl>` works nicely in both commits, even after removing my manual entry in the mountpoints. (My AzuraCast runs behind an NGinX Proxy Manager.)

Thanks for implementing this! Directory listings are fine now, and reference the SSL streams.
