### ISSUE TITLE
Incomplete translations

### ISSUE THREAD

**Issue by NicolasERT** [AzuraCast/AzuraCast#625]
Hi, today the translations have been updated, but I have noticed that there are still a lot of words to translate, which are not in crowdin.

How can I add them to that page?

The language I am using is Spanish, thank you.

**Comment by frecuencialibre** [comment]
Hi @SlvrEagle23 awesome work! what would be the most useful format for you? never used crowdin...

just a list of complete english strings one per line? 

eg. "You can also upload files in bulk via SFTP by following these instructions. Newly uploaded files will automatically be processed within a few minutes."

**Comment by SlvrEagle23** [comment]
@frecuencialibre Thank you for offering to help with translating AzuraCast! Our translations are managed through CrowdIn. You can create an account and submit translations by following the instructions in our contributors guide: https://github.com/AzuraCast/AzuraCast/blob/master/CONTRIBUTING.md#translating-azuracast
