### ISSUE TITLE
Ran out of storage while creating a Backup

### ISSUE THREAD

**Issue by renatopinto89** [AzuraCast/AzuraCast#6253]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.18.1

### What happened?

Hello everyone, hope any of you can help me.

I have a Azuracast instance installed in a VPS with a 240GB capacity.
When I tried to do a .tzst backup of my instance (110GB), it came to a point the log window hanged for a good hour.
When I checked the VPSs storage, it reported 0 bytes free, so I closed the window and a 60GB incomplete backup showed up in the backups admin page, I deleted it but now I have 180GB occupied, which makes me believe there's a temporary version of that backup hidden somewhere.

Any clue oh how can I get rid of it and recover the free space I had before? 

Thanks in advance and thank you so much for this amazing project.

**Comment by adoboligh1** [comment]
you should delete your ongoing backup file i guess

**Comment by SpeedyCharly** [comment]
Same thing happened to me a few days ago... deleted all backups and restarted the sever and that seemed to to the trick
