### ISSUE TITLE
Azuracast on OVH SYS armv7 server

### ISSUE THREAD

**Issue by amitx11** [AzuraCast/AzuraCast#626]
**Installation method**
Docker and traditional

**Host OS (for Docker installations)**
Ubuntu 16.04 and Debian 9
**Describe the bug**

I tried to install Azuracast on these server ( https://www.soyoustart.com/ie/server-storage/)
Is there a special installation script for this Armv7 server?

**Comment by SlvrEagle23** [comment]
@amitx11 Currently, ARM/ARMHF devices (including Raspberry Pi) are not supported by AzuraCast, due to a software dependency (MariaDB 10.2) that currently has no releases for the platform and thus prevents the entire project from installing properly.

You can follow #332 for updates to this issue.

**Comment by rexjohannes** [comment]
Can i use an external Database and install it on an ARM Server?
