### ISSUE TITLE
DNS Records are not valid.  Do not have a valid SSL for domain www.wlcp-db.com

### ISSUE THREAD

**Issue by daveterry195310** [AzuraCast/AzuraCast#6263]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

[2023-05-07T19:46:32.651822+00:00] AzuraCast.DEBUG: ACME: Using directory URL: https://acme-v02.api.letsencrypt.org/directory [] []
[2023-05-07T19:46:34.272659+00:00] AzuraCast.ERROR: ACME Error: Challenge validation failed: no valid A records found for www.wlcp-db.com; no valid AAAA records found for www.wlcp-db.com (urn:ietf:params:acme:error:dns) {"exception":"[object] (skoerfgen\\ACMECert\\ACME_Exception(code: 0): Challenge validation failed: no valid A records found for www.wlcp-db.com; no valid AAAA records found for www.wlcp-db.com (urn:ietf:params:acme:error:dns) at /var/azuracast/www/vendor/skoerfgen/acmecert/src/ACMEv2.php:122)"} []

**Comment by BusterNeece** [comment]
@daveterry195310 I believe the DNS settings on your domain name are misconfigured. Make sure that you have an `A` type record that points to the IP address of your AzuraCast installation. I don't believe that only using IPv6 is currently supported.

**Comment by daveterry195310** [comment]
Thank you.  I am new to this process.  I was not sure how to create a SSL Certificate for each of the websites i have for multiple stations.  I watched your Youtube video several times and just could not pick up how to insure the SSL certificates were generated properly.  I tried to use LetsEncrypt and that's when I got the error reported.  Thanks so much for all your help.  I worked in UNIX several years ago but I am new to Cloud Servers and Linux.  I believe this is Linux but correct me if I am wrong.

Dave Terry
Life Changing Productions RVA, Inc
804-337-2576

________________________________________

**Comment by BusterNeece** [comment]
@daveterry195310 It is indeed Linux-based, and LetsEncrypt is set up via the web UI these days, but the error you're seeing indicates that your DNS is misconfigured at the domain-name level, which is outside AzuraCast. Your domain's DNS may be configured with your registrar, or if you use a service like Cloudflare, it would be managed there.

**Comment by daveterry195310** [comment]
I am using Cloudflare.  I will see if i can get the dns records configured correctly through Cloudflare.  Thanks again for all your help.  I am looking forward to getting this working and getting on with Music Streaming.  This is the most affordable solution i have found to do multiple formats.

**Comment by joeyboli** [comment]
> I am using Cloudflare. I will see if i can get the dns records configured correctly through Cloudflare. Thanks again for all your help. I am looking forward to getting this working and getting on with Music Streaming. This is the most affordable solution i have found to do multiple formats.

i think if you use cloudflare for streaming they will automatically accept IPV6 and pass it to azuracast.
