### ISSUE TITLE
The port 8004 is in use by another station.

### ISSUE THREAD

**Issue by hitzgh** [AzuraCast/AzuraCast#6267]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#39c0372 (2022-10-09 2:24)

### What happened?

i created a first station with the port 8004 but the port was unable to connect so i deleted the station and tried to create it again with the same port number but i keep getting the error that the port is in use by another station.

ValidationException at /var/azuracast/www/src/Exception/ValidationException.php L37: Object(App\Entity\Station): The port 8004 is in use by another station.

**Comment by ajeje989** [comment]
I am not sure
But is better u create only port example 8000 or 8010 

Multiple to 10
