### ISSUE TITLE
HTTPS with different port

### ISSUE THREAD

**Issue by ohld** [AzuraCast/AzuraCast#627]
I have the server with main radio site. And I want your AzuraCast tool to be on that server too.

Unfortunately ports 80 and 443 are already used for main radio site. So I've changed port mappings in docker-compose. But How can I use **let's encrypt** to move Azuracast from HTTP to HTTPS? 

I've installed Azuracast via docker. Thanks

**Comment by LazosPlaying** [comment]
Umm you cal also just use  different subdomain ?
something like `panel.yourdomain.com` and simply use virtualhost for it ^-^

**Comment by SlvrEagle23** [comment]
@ohld If you want to host both your main webserver and AzuraCast from the same server, this is entirely possible, but you need to run something "in front" of both of them that can route traffic smartly. This can be another Apache instance, an nginx instance, possibly even something lightweight like Caddy.

You could even integrate this into the configuration of your web server that's serving the main site; just have all references to a subdomain or subfolder proxy out to the `nginx` AzuraCast container, and modify the port mapping in `docker-compose.yml` for `nginx` to use different ports.

It's worth noting that this is all considered rather advanced to do, and the easier method by far is to run AzuraCast on its own VPS/VM/server, or to make it the only service on that machine listening on port 80/443.

**Comment by ohld** [comment]
So my solution was: 
1) reinstall AzuraCast with default ports.
2) set up **Letsencrypt** for Azuracast
3) change 80 and 443 ports in `docker-compose.yml`
4) install _nginx_ on the server and install **Letsencrypt** via `certbot`

And it worked fine.
