### ISSUE TITLE
Playlist - Meilisearch no update

### ISSUE THREAD

**Issue by JackCoder21** [AzuraCast/AzuraCast#6274]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.18.1

### What happened?

Doing an import of a pls/m3u playlist, AzuraCast correctly sets the tracks in the playlist but clicking on the number of tracks in the playlist results in an empty playlist.

**This does not affect the broadcast of this playlist, all tracks are played.**

I have tried restarting the service and performing the "App\Sync\Task\UpdateMeilisearchIndex" task manualy, clearing the cache but it does not update.

**This problem has been present since version 0.18.0 and also in the rolling releases.**

I temporarily disabled the Meilisearch component by editing the `azuracast.env` configuration by inserting:
`ENABLE_MEILISEARCH=false`

Is there a system to force playlist update for Meilisearch?
How can I disable the Service Not Running mesage from the home?

**Comment by BusterNeece** [comment]
Closing as Meilisearch has been retired in favor of optimizing other parts of the search process in newer Rolling Release versions.
