### ISSUE TITLE
Live listeners data not loaded

### ISSUE THREAD

**Issue by bebjakub** [AzuraCast/AzuraCast#628]
**Installation method**
Docker

**Host OS (for Docker installations)**
Docker image on VC1S at Scaleway

**Describe the bug**
Live listeners are not loaded. `/api/station/1/listeners` has response `cURL error 28: Connection timed out after 10000 milliseconds`.

**To Reproduce**
1. Go to '/station/1/reports/listeners'

**Expected behavior**
Live listeners data loaded.

**Screenshots**
[Live listeners](https://prnt.sc/jyfe9x)

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser chrome
 - Version 67

Thank you! :)

**Comment by SlvrEagle23** [comment]
@bebjakub Thank you for the very detailed report. Looks like it may be an issue with our third-party IP geolocation provider, which will be a bit of a pain to resolve.

I'll look into it further and update you as soon as I can.

**Comment by SlvrEagle23** [comment]
@bebjakub I've taken another look into this issue, and it appears the IP geolocation database service is working just fine again. There may have been a temporary outage that was responsible for the problem you experienced. If you try it again now, does it work, or does it produce the same error?

**Comment by bebjakub** [comment]
@SlvrEagle23 Updated, but Error persists. How can I check if geolocation database service is working correctly? Anyway, I had to use manual update due old version of docker image (Docker version 1.12.2, docker-compose version 1.8.1).

**Comment by SlvrEagle23** [comment]
@bebjakub I've done some refactoring of the underlying code and updated the system so that IP geolocation data now comes directly from a database installed locally on the server, so no IP information has to transit out and visit a third-party API at all, and there's significantly reduced potential for problems like timeouts and such.

Update again and let me know if it works any better for you. :)

**Comment by bebjakub** [comment]
@SlvrEagle23 Thanx! Now it definitely works! :)
