### ISSUE TITLE
Error 500 when LOGIN

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#6280]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

i update my azuracast docker installation but after updating i cant login anymore. 

![image](https://github.com/AzuraCast/AzuraCast/assets/27730047/1f2d4f00-be49-43fe-a06c-59df1a2362cb)

### Relevant log output

```shell
500
Context: Trying to hydrate enum property "App\Entity\User::$theme" Problem: Case "" is not listed in enum "App\Enums\SupportedThemes" Solution: Either add the case to the enum type or migrate the database column to use another case of the enum
vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php : L978
```

**Comment by BusterNeece** [comment]
@reans Thank you for the report! Fixed in the latest Rolling Release deploying right now.
