### ISSUE TITLE
Song Request meilisearch error

### ISSUE THREAD

**Issue by gregorymcewanmarriot** [AzuraCast/AzuraCast#6281]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.18.1 Stable • Docker • PHP 8.2

### What happened?

When you try to access REQUEST SONG from player on 4 of my 5 stations get the following error (see console log)

Have tried 

- Clearing Cache
- Disabling and Reenabling Song Request Feature 
- Restarting Server on Linode
- Checked all settings of playlists (against working station)

Non Working station> https://buzzradio.live/public/spiritbox
Working station> https://buzzradio.live/public/rastabox

Same Server

![Clipboard01](https://github.com/AzuraCast/AzuraCast/assets/48602432/2439e202-f213-44e1-8abd-c97dba303dfb)

### Relevant log output

```shell
ApiException at /var/azuracast/www/vendor/meilisearch/meilisearch-php/src/Http/Client.php L199: Attribute `station_7_playlists` is not filterable. This index does not have configured filterable attributes.
1:20 station_7_playlists IN [13, 14, 17, 18, 19]
```

**Comment by BusterNeece** [comment]
Closing as Meilisearch has been retired in favor of optimizing other parts of the search process in newer Rolling Release versions.
