### ISSUE TITLE
Analytics show error everytime i login because it's turned off

### ISSUE THREAD

**Issue by jardaskera** [AzuraCast/AzuraCast#6285]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#643aa75

### What happened?

Hello, i have turned off analytics on my azuracast instalation, and every time i login to the administration, there's a popup showing as Error with message ''Analytics are disabled for this installation.'', is there any solution to turn this popup off? Thanks! (Sorry for my bad English)

![Snímek obrazovky 2023-05-21 v 21 16 22](https://github.com/AzuraCast/AzuraCast/assets/48823563/a1c9a773-bf23-4033-94d4-6ad575fa62ea)

**Comment by BusterNeece** [comment]
@jardaskera Thanks for the report! Should be fixed in the latest Rolling Release.
