### ISSUE TITLE
Jingles Playlist incorrectly fading & playing randomly throughout song.

### ISSUE THREAD

**Issue by JackCrispy** [AzuraCast/AzuraCast#6288]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.18.1

### What happened?

I setup a separate playlist named tags, to play jingles before every song. 
Playlist has these settings:
![image](https://github.com/AzuraCast/AzuraCast/assets/34707863/013c0d5c-da82-4e50-a63a-74ee17ed7f3f)
![image](https://github.com/AzuraCast/AzuraCast/assets/34707863/a5ad6e6b-5cf6-412d-970e-a3a5f2726301)
The 1 media file has these settings:
![image](https://github.com/AzuraCast/AzuraCast/assets/34707863/19a869d7-1cb8-43a5-b04a-74bb5e504365)

However as you can see in the video below, the jingle plays over a minute into the song. This on it's own, I don't mind as much, however, it also fades the main playlist's audio, causing this listening experience: https://streamable.com/y27ww9

### Relevant log output

```shell
N/A
```

**Comment by Moonbase59** [comment]
You might try disabling `[_] Interrupt other songs to play at scheduled time`.
