### ISSUE TITLE
To high Bass level with the AutoDJ

### ISSUE THREAD

**Issue by NeddyPlays** [AzuraCast/AzuraCast#630]
Hi,

We have just started using AzuraCast for our Radiostation. I only got some thing that the level of the Bass is way to high. This causes that it is not nice to listen to. It also does this while a DJ is live on air.

Is there a way to lower the bass level overall?

**Comment by SlvrEagle23** [comment]
@NeddyPlays By default, AzuraCast does not do any equalization to the audio signal at all. The issue you're experiencing may be with any number of factors, from your source audio files to the software you're using to listen to the radio stream. If you've specified any custom code in the "Advanced: Custom Configuration" section of the station's profile, this can also affect how the AutoDJ system equalizes audio.

**Comment by NeddyPlays** [comment]
I've not specified any things in Advanced: Custom Configuration. Is there something like a replaygain thing in there?

**Comment by SlvrEagle23** [comment]
@NeddyPlays By default, the replaygain metadata resolver isn't enabled by default. You would have to follow the suggested configuration changes from the [Liquidsoap documentation](http://savonet.sourceforge.net/doc-svn/replay_gain.html).

**Comment by NeddyPlays** [comment]
Ok thanks. Iam not able to find it yet.

**Comment by SlvrEagle23** [comment]
@NeddyPlays I don't think this is an issue with AzuraCast, as by default we do absolutely no equalization of music. There are even other requests for us to offer level normalization and such out of the box, which are possible future features that can be turned on and off, but currently no such features exist.
