### ISSUE TITLE
Huge latency in low-bitrate OPUS stream

### ISSUE THREAD

**Issue by ivellios1988** [AzuraCast/AzuraCast#6302]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.18.1 Stable

### What happened?

My radio offers several streams in different formats and at various bitrates, depending on the user's preferences, Internet connection speed, etc. Since my radio mainly broadcasts spoken content, and I have some listeners from areas where the quality of the Internet connection is, to say the least, extremely bad, I decided to create a stream that broadcasts in OPUS with a bitrate of 8 kbps.

Here's a definition of this stream from my Liquidsoap configuration file:

`output.icecast(%opus(samplerate=48000, bitrate=8, vbr="constrained", application="audio", channels=1, signal="music", complexity=10, max_bandwidth="full_band"), id="local_8", host = "127.0.0.1", port = 8000, password = "Passwords? Who needs them?!", mount = "/opus8", name = "Radio Paranormalium", description = "", genre = "", public = true, encoding = "UTF-8", icy_metadata="true", mean(radio))`

The stream works fine, despite one issue: it has a HUGE latency compared to my other streams, reaching up to 25-30 seconds. When I restart my station, my other streams start simultaneously and I can play them immediately, whereas the 8 kbps one in OPUS 'waits' 25-30 seconds before it starts playing.

Today I did some experiments and what I found is the issues with latency in OPUS streams start when you use bitrates as low as 16 kbps. The lower the bitrate, the bigger the latency becomes. I tried changing complexity to 0, signal to voice or restricted_lowdelay, samplerate to 8000, max_bandwidth to narrowband, etc. - no success, the delay is still somewhere around 25-30 seconds.

Is it possible at all to reduce the latency in OPUS streams at low bitrates or this is just the way such streams are supposed to work?

**Comment by redcastle-de** [comment]
Without knowing the exact issue - I would research the buffers used in the full chain. 
With a bitrate of 8kbps, a buffer will need longer to fill causing bigger latency. 

If either liquidsoap or the player uses a fixed buffer size to buffer network issues, with 8kbps the same buffer will be used for 30 seconds, that would be enough for only 5 seconds with 48kpbs.

**Comment by ivellios1988** [comment]
@redcastle-de thank you for your reply. The issue may be caused by the buffer size indeed, I just checked if it happens regardless of which codec I use and it turned out that 8kbps AAC stream also produces huge latency of about 15 seconds. Does LS allow for manually setting bufer sizes on a per-stream basis?
