### ISSUE TITLE
1000003460 (1638×2048)

### ISSUE THREAD

**Issue by daveterry195310** [AzuraCast/AzuraCast#6312]
![chrome_screenshot_1685893834678.png](https://github.com/AzuraCast/AzuraCast/assets/132607615/a049c83e-ebf1-4b88-980a-519a77ee86fe)

**Comment by BusterNeece** [comment]
@daveterry195310 Can you provide some more information beyond just this screenshot? I'm assuming the error in question is that LetsEncrypt isn't working correctly on your domain? Or possibly not set up yet?

**Comment by daveterry195310** [comment]
Enter the following in a chrome browser to recreate the errorhttps://45.79.206.172/public/wlcp-db_classic_rockMore details attachedSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Buster Neece ***@***.***> Date: 6/7/23  2:50 AM  (GMT-05:00) To: AzuraCast/AzuraCast ***@***.***> Cc: Dave Terry ***@***.***>, Mention ***@***.***> Subject: Re: [AzuraCast/AzuraCast] 1000003460 (1638×2048) (Issue #6312) 
@daveterry195310 Can you provide some more information beyond just this screenshot? I'm assuming the error in question is that LetsEncrypt isn't working correctly on your domain? Or possibly not set up yet?

**Comment by Moonbase59** [comment]
@daveterry195310 Your certificate is only valid for www.wlcp-db.com, _not_ for the IP address 45.79.206.172. If you use https://www.wlcp-db.com/public/wlcp-db_classic_rock instead, the player works fine.

**Comment by daveterry195310** [comment]
Thank you , i verified this too and it works correctly now using the domain
name and full url.

Dave Terry
