### ISSUE TITLE
Station offline since latest update

### ISSUE THREAD

**Issue by sb-200** [AzuraCast/AzuraCast#6319]
[###](url) Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #35a6c8c (2023-06-05)

### What happened?

Hi there,

I have 2 stations running on my installation but since updating to the latest rolling release one of them fails to start, displaying offline even after resetting. the other station continues to work fine, however.

Liquidsoap error appears in custom configuration however I do not have any custom code added. 

<img width="377" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/84730588/e11d67e0-67f3-4042-a96c-c4c49502c3db">

Liquidsoap log below.

Thanks guys! :)

### Relevant log output

```shell
Error 5: this value has type
  format(_)
but it should be a subtype of
  {string}
INFO: Loading Sdl_image, Target = linux
INFO: Loading Sdl_ttf, Target = linux
```

**Comment by sb-200** [comment]
**Update after disabling Streamers/DJs the issue seems to have gone away

**Comment by Moonbase59** [comment]
Thanks for the update, this helps diagnosing the problem!

**Comment by netbladenl** [comment]
After update #a3a1119 my station wont start anymore when streamers active

**Comment by netbladenl** [comment]
Not fixed yet when using stereotool als audioprocessing. All other processing settings work
