### ISSUE TITLE
Question: Radiodj as autodj and also a live souce sometime

### ISSUE THREAD

**Issue by edzel** [AzuraCast/AzuraCast#632]
Hi 
I im thinking of setting up a backup station with azuracast and on that station i would like radiodj (or any other software as a autodj) and then i want live djs to connect to azuracast 
Is that possible and how do i configure it?

Thanks

**Comment by SlvrEagle23** [comment]
@edzel You can always choose to disable Liquidsoap as an AutoDJ in your station's profile. This will allow you to set up a Shoutcast or Icecast station, but with no source provided by default.

You can then provide the "Source password" to any software (including RadioDJ) and it can connect directly to Shoutcast or Icecast and broadcast anything it wants.
