### ISSUE TITLE
LS config: ConfigWriter generates duplicates

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6321]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #7c3b83a (2023-06-06 8:38)

### What happened?

Checking my `liquidsoap.liq` from #6316, I stumbled over some duplicates generated:

```
# Apply amplification metadata (if supplied)
radio = amplify(override="liq_amplify", 1., radio)

error_file = single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")

error_file = single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")

def tag_error_file(m) =
    ignore(m)
    ignore(m)
    [("is_error_file", "true")]
end
error_file = metadata.map(tag_error_file, error_file)
```

`error_file` and `ignore(m)`.

**Comment by BusterNeece** [comment]
Seems like that Git merge didn't go so cleanly.

**Comment by Moonbase59** [comment]
Nothing serious, just wanted to mention it. Shit happens ;-)
