### ISSUE TITLE
Update ./docker.sh change-ports no option Station Port Range

### ISSUE THREAD

**Issue by gunsar** [AzuraCast/AzuraCast#6323]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#be877d8

### What happened?

i tried update rolling release using command :

`./docker.sh update-self`
`./docker.sh update`
no longer appears for port change requests

i repeated with the command
`./docker.sh update-self`
`./docker.sh change-ports`
there is only a request to change port 80, 443, 2022, there is no option to change Station Port Range

i tried to add in docker-compose.override.yml
services:
   `web:`
     `ports:`
       `-"9000-9999:9000-9999"` 

doesn't work well, I see docker-compose.yml is still in the range of 8000-8500. while the station port range that I want to use is only port 9000-9999. port 8000-8999 I use for other purposes

Please help

**Comment by Moonbase59** [comment]
@gunsar As you can see, the #8a50add build failed due to a problem with mariadb-server 10.9, so this is to be expected. I’m sure there’ll be a fix soon.

**Comment by Moonbase59** [comment]
Same thing, we have to wait for @BusterNeece to fix it.

As long as you see the red "x" on the "Commits" page (click on "Code" then on the number of commits on the Github page), the build failed. (A brownish dot instead means it’s currently building.)

![Commits · AzuraCast-AzuraCast – Mozilla Firefox_001](https://github.com/AzuraCast/AzuraCast/assets/3706922/b29c2ab0-cd27-4f06-99dd-2e14d787ffab)

**Comment by BusterNeece** [comment]
@gunsar I'm fixing an issue with the installer in the very latest update that's rolling out right now. After that's deployed, then the installer should work as normal. That's where you'd do the station port changes, during the update process when it asks if you want to modify configuration.
