### ISSUE TITLE
Can not edit Station Profile

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#6328]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#0c06451 (2023-06-08 13:36)

### What happened?

When i click on "Edit Station Profile"   error 500 is thrown.
```
Unknown named parameter $station_id

vendor/slim/slim/Slim/Handlers/Strategies/RequestResponseNamedArgs.php : L42 
```

**Comment by dersonbsb2022** [comment]
Me too!

**Comment by LordHelmchen666** [comment]
@BusterNeece Thank you for your very quick response!
