### ISSUE TITLE
Could we move Liquidsoap to next commit to fix blank.eat()?

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6332]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

@BusterNeece Can we dare to move Liquidsoap 2.2 to ~~commit #50cc747~~ the next commit once the build finishes, so we can test `blank.eat()`? It is supposed to fix https://github.com/savonet/liquidsoap/issues/3132 which hangs my station when songs have silence at the end.

This _is_ a bumpy road, but thanks to all participating, we’re really getting somewhere…

**Comment by Moonbase59** [comment]
@Vaalyn We’d need commit 50cc747 for the fixed blank.eat() but their build failed. Using 39717ae might be too early a version.

**Comment by Moonbase59** [comment]
Confirm `blank.eat()` works as intended in AzuraCast 2e0c89d with LS 2.2.0+git@50cc747f6. It _does_ use quite a bit CPU when "eating" longer silence parts (went to ~80% shortly), but quickly goes down again, and playout is fine.

Anyway, a typical radio would mostly use `blank.skip()` instead, as shown in https://github.com/AzuraCast/AzuraCast/discussions/6334, which also works fine.

**Comment by Moonbase59** [comment]
Additional feedback re LS 2.2.0+git@50cc747f6:

- Runs stable at 12-18% CPU since about 17 hours now, with HLS enabled + MP3 + AAC stream.
- "Use ReplayGain" in station disabled (using pre-tagged files) since that still eats too much CPU. I think @toots is working on that.
- Now enabled additional "master_me" processing and will leave it running for a day or so. Brings CPU load up to ~28–32%, which is to be expected. 15-min load avg around 0.9–1.0, with 1-min avg sometimes going up to 1.6 when doing tasks like CheckMediaTask. Seems okay so far.

**Comment by toots** [comment]
See: https://github.com/AzuraCast/AzuraCast/issues/6327#issuecomment-1585680594 for additional optimization/regression fix of replaygain.
