### ISSUE TITLE
Stereotool Preset bug

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#6337]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#2e0c89d

### What happened?

If I activate Stereotool without a preset, I don't have any problems.
When I load a preset it works but after a few minutes the error message appears, no significant CPU load.
Liquidsoap Log:
`
2023/06/09 10:20:06 [clock.main:2] We must catchup 1.00 seconds!
2023/06/09 10:20:07 [clock.main:2] We must catchup 1.11 seconds!
2023/06/09 10:20:08 [clock.main:2] We must catchup 1.10 seconds!
`

**Comment by netbladenl** [comment]
2023/06/16 16:43:49 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Ffmpeg_decoder.End_of_file.
2023/06/16 16:43:50 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
[mp3float @ 0x7f98a4025b40] Could not update timestamps for skipped samples.
2023/06/16 16:43:55 [playlist_default:3] Reloading playlist with URI /var/azuracast/stations/radio_netblade/playlists/playlist_default.m3u.
2023/06/16 16:43:55 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/radio_netblade/playlists/playlist_default.m3u"!
2023/06/16 16:43:55 [playlist_default:3] Couldn't read playlist: request resolution failed.
2023/06/16 16:43:55 [request.dynamic:3] Fetch failed: empty.
2023/06/16 16:43:55 [playlist_jingles:3] Reloading playlist with URI /var/azuracast/stations/radio_netblade/playlists/playlist_jingles.m3u.
2023/06/16 16:43:55 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/radio_netblade/playlists/playlist_jingles.m3u"!
2023/06/16 16:43:55 [playlist_jingles:3] Couldn't read playlist: request resolution failed.
2023/06/16 16:43:55 [request.dynamic:3] Fetch failed: empty.
2023/06/16 16:43:55 [main:3] Shutdown started!
2023/06/16 16:43:55 [main:3] Waiting for main threads to terminate...
2023/06/16 16:43:55 [local_2:3] Closing connection...
2023/06/16 16:43:55 [local_1:3] Closing connection...
2023/06/16 16:43:55 [clock.main:3] Streaming loop stopped.
2023/06/16 16:43:55 [main:3] Main threads terminated.
2023/06/16 16:43:55 [threads:3] Shutting down scheduler...
2023/06/16 16:43:55 [threads:3] Scheduler shut down.
2023/06/16 16:43:55 [main:3] Cleaning downloaded files...
2023/06/16 16:43:55 [main:3] Freeing memory...
INFO: Loading Sdl_image, Target = linux
INFO: Loading Sdl_ttf, Target = linux
2023/06/16 16:44:04 >>> LOG START
2023/06/16 16:43:56 [main:3] Liquidsoap 2.2.0+git@64732ea7a
2023/06/16 16:43:56 [main:3] Using: alsa=0.3.0 angstrom=0.15.0 ao=0.2.4 asetmap=0.8.1 asn1-combinators=0.2.6 astring=0.8.5 base.caml=v0.15.1 base64=3.5.1 bigarray=[distributed with OCaml] bigarray-compat=1.1.0 bigstringaf=0.9.1 bjack=0.1.6 bos=0.2.1 bytes=[distributed with OCaml] ca-certs=v0.2.3 camlimages.all_formats=4.2.6 camlimages.core=5.0.4 camlimages.exif=5.0.4 camlimages.gif=5.0.4 camlimages.jpeg=5.0.4 camlimages.png=5.0.4 camlimages.tiff=5.0.4 camlimages.xpm=5.0.4 camlp-streams camomile=d3773ec camomile.lib=d3773ec cohttp=5.1.0 cohttp-lwt=5.1.0 cohttp-lwt-unix=5.1.0 conduit=6.2.0 conduit-lwt=6.2.0 conduit-lwt-unix=6.2.0 cry=1.0.0 cstruct=6.2.0 ctypes=0.20.2 ctypes.foreign=0.20.2 ctypes.stubs=0.20.2 curl=0.9.2 domain-name=0.4.0 dssi=0.1.5 dtools=0.4.5 dune-build-info=3.7.1 dune-private-libs.dune-section=3.7.1 dune-site=3.7.1 dune-site.private=3.7.1 duppy=0.9.3 eqaf=0.9 eqaf.bigstring=0.9 eqaf.cstruct=0.9 faad=0.5.2 fdkaac=0.3.3 ffmpeg-av=1.1.8 ffmpeg-avcodec=1.1.8 ffmpeg-avdevice=1.1.8 ffmpeg-avfilter=1.1.8 ffmpeg-avutil=1.1.8 ffmpeg-swresample=1.1.8 ffmpeg-swscale=1.1.8 fileutils=0.6.4 flac=0.4.0 flac.decoder=0.4.0 flac.ogg=0.4.0 fmt=0.9.0 fpath=0.7.3 frei0r=0.1.2 gd=1.0a5 gen=1.1 gmap=0.3.0 hkdf=1.0.4 inotify=2.4.1 integers ipaddr=5.5.0 ipaddr-sexp=5.5.0 ipaddr.unix=5.5.0 irc-client irc-client-unix ladspa=0.2.2 lame=0.3.7 lastfm=0.3.3 lilv=0.1.0 liquidsoap-lang=2.2.0 liquidsoap-lang.console=2.2.0 liquidsoap_alsa=rolling-release-v2.2.x-79-g64732ea liquidsoap_ao=rolling-release-v2.2.x-79-g64732ea liquidsoap_bjack=rolling-release-v2.2.x-79-g64732ea liquidsoap_builtins=rolling-release-v2.2.x-79-g64732ea liquidsoap_camlimages=rolling-release-v2.2.x-79-g64732ea liquidsoap_core=rolling-release-v2.2.x-79-g64732ea liquidsoap_dssi=rolling-release-v2.2.x-79-g64732ea liquidsoap_faad=rolling-release-v2.2.x-79-g64732ea liquidsoap_fdkaac=rolling-release-v2.2.x-79-g64732ea liquidsoap_ffmpeg=rolling-release-v2.2.x-79-g64732ea liquidsoap_flac=rolling-release-v2.2.x-79-g64732ea liquidsoap_frei0r=rolling-release-v2.2.x-79-g64732ea liquidsoap_gd=rolling-release-v2.2.x-79-g64732ea liquidsoap_irc=rolling-release-v2.2.x-79-g64732ea liquidsoap_ladspa=rolling-release-v2.2.x-79-g64732ea liquidsoap_lame=rolling-release-v2.2.x-79-g64732ea liquidsoap_lastfm=rolling-release-v2.2.x-79-g64732ea liquidsoap_lilv=rolling-release-v2.2.x-79-g64732ea liquidsoap_lo=rolling-release-v2.2.x-79-g64732ea liquidsoap_mad=rolling-release-v2.2.x-79-g64732ea liquidsoap_magic=rolling-release-v2.2.x-79-g64732ea liquidsoap_mem_usage=rolling-release-v2.2.x-79-g64732ea liquidsoap_memtrace=rolling-release-v2.2.x-79-g64732ea liquidsoap_ogg=rolling-release-v2.2.x-79-g64732ea liquidsoap_ogg_flac=rolling-release-v2.2.x-79-g64732ea liquidsoap_optionals=rolling-release-v2.2.x-79-g64732ea liquidsoap_opus=rolling-release-v2.2.x-79-g64732ea liquidsoap_osc=rolling-release-v2.2.x-79-g64732ea liquidsoap_oss=rolling-release-v2.2.x-79-g64732ea liquidsoap_portaudio=rolling-release-v2.2.x-79-g64732ea liquidsoap_posix_time=rolling-release-v2.2.x-79-g64732ea liquidsoap_prometheus=rolling-release-v2.2.x-79-g64732ea liquidsoap_pulseaudio=rolling-release-v2.2.x-79-g64732ea liquidsoap_runtime=rolling-release-v2.2.x-79-g64732ea liquidsoap_samplerate=rolling-release-v2.2.x-79-g64732ea liquidsoap_sdl=rolling-release-v2.2.x-79-g64732ea liquidsoap_shine=rolling-release-v2.2.x-79-g64732ea liquidsoap_soundtouch=rolling-release-v2.2.x-79-g64732ea liquidsoap_speex=rolling-release-v2.2.x-79-g64732ea liquidsoap_srt=rolling-release-v2.2.x-79-g64732ea liquidsoap_ssl=rolling-release-v2.2.x-79-g64732ea liquidsoap_stereotool=rolling-release-v2.2.x-79-g64732ea liquidsoap_taglib=rolling-release-v2.2.x-79-g64732ea liquidsoap_theora=rolling-release-v2.2.x-79-g64732ea liquidsoap_tls=rolling-release-v2.2.x-79-g64732ea liquidsoap_vorbis=rolling-release-v2.2.x-79-g64732ea liquidsoap_xmlplaylist=rolling-release-v2.2.x-79-g64732ea liquidsoap_yaml=rolling-release-v2.2.x-79-g64732ea lo=0.2.0 logs=0.7.0 logs.fmt=0.7.0 logs.lwt=0.7.0 lwt=5.6.1 lwt.unix=5.6.1 macaddr=5.5.0 mad=0.5.3 magic=0.7.3 magic-mime=1.3.0 mem_usage=0.0.4 memtrace=0.2.3 menhirLib=20230415 metadata=0.2.0 mirage-crypto=0.11.1 mirage-crypto-ec=0.11.1 mirage-crypto-pk=0.11.1 mirage-crypto-rng=0.11.1 mirage-crypto-rng.unix=0.11.1 mm=0.8.3 mm.audio=0.8.3 mm.base=0.8.3 mm.image=0.8.3 mm.midi=0.8.3 mm.video=0.8.3 ocplib-endian ocplib-endian.bigstring ogg=0.7.4 ogg.decoder=0.7.4 opus=0.2.3 opus.decoder=0.2.3 osc osc-unix parsexp=v0.15.0 pbkdf pcre=7.5.0 portaudio=0.2.3 posix-base=b516d46 posix-socket=b516d46 posix-socket.constants=b516d46 posix-socket.stubs=b516d46 posix-socket.types=b516d46 posix-time2=b516d46 posix-time2.constants=b516d46 posix-time2.stubs=b516d46 posix-time2.types=b516d46 posix-types=b516d46 posix-types.constants=b516d46 ppx_sexp_conv.runtime-lib=v0.15.0 prometheus=1.2 prometheus-app=1.2 ptime=1.1.0 ptime.clock.os=1.1.0 pulseaudio=0.1.6 re=1.10.4 result=1.5 rresult=0.7.0 samplerate=0.1.6 sedlex=3.1 seq=[distributed with OCaml 4.07 or above] sexplib=v0.15.1 sexplib0=v0.15.0 shine=0.2.3 soundtouch=0.1.9 speex=0.4.2 speex.decoder=0.4.2 srt=0.3.0 srt.constants=0.3.0 srt.stubs=0.3.0 srt.stubs.locked=0.3.0 srt.types=0.3.0 ssl=0.5.13 stdlib-shims=0.3.0 stereotool=rolling-release-v2.2.x-79-g64732ea str=[distributed with OCaml] stringext=1.6.0 taglib=0.3.10 theora=0.4.1 theora.decoder=0.4.1 threads=[distributed with OCaml] threads.posix=[distributed with OCaml] tls=0.17.0 tsdl=v1.0.0 tsdl-image=0.5 tsdl-ttf=0.5 unix=[distributed with OCaml] unix-errno=0.6.2 unix-errno.errno_bindings=0.6.2 unix-errno.errno_types=0.6.2 unix-errno.errno_types_detected=0.6.2 unix-errno.unix=0.6.2 uri=4.2.0 uri-sexp=4.2.0 uri.services=4.2.0 vorbis=0.8.1 vorbis.decoder=0.8.1 x509=0.16.4 xmlm=1.4.0 xmlplaylist=0.1.5 yaml=3.1.0 yaml.bindings=3.1.0 yaml.bindings.types=3.1.0 yaml.c=3.1.0 yaml.ffi=3.1.0 yaml.types=3.1.0 zarith=1.12
2023/06/16 16:43:57 [clock:3] Using native (high-precision) implementation for latency control
2023/06/16 16:44:04 [main:3] Standard library loaded in 6.25 seconds.
2023/06/16 16:44:04 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz main.
2023/06/16 16:44:04 [frame:3] Video frame size set to: 1280x720
2023/06/16 16:44:04 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2023/06/16 16:44:04 [frame:3] Targeting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2023/06/16 16:44:04 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2023/06/16 16:44:04 [sandbox:3] Sandboxing disabled
2023/06/16 16:44:04 [startup:3] DSSI plugins registration: 0.00s
2023/06/16 16:44:04 [startup:3] FFmpeg filters registration: 0.02s
2023/06/16 16:44:04 [startup:3] FFmpeg bitstream filters registration: 0.00s
2023/06/16 16:44:04 [startup:3] Lilv plugins registration: 0.01s
2023/06/16 16:44:04 [startup:3] Frei0r plugin registration: 0.00s
2023/06/16 16:44:04 [startup:3] LADSPA plugins registration: 0.03s
2023/06/16 16:44:04 [startup:3] Typechecking: 6.07s
2023/06/16 16:44:04 [startup:3] Evaluation: 0.02s
2023/06/16 16:44:04 [startup:3] Typechecking: 0.04s
2023/06/16 16:44:04 [startup:3] Evaluation: 0.01s
2023/06/16 16:44:04 [startup:3] Typechecking: 0.06s
2023/06/16 16:44:04 [startup:3] Evaluation: 0.04s
2023/06/16 16:44:04 [startup:3] Loaded /var/azuracast/stations/radio_netblade/config/liquidsoap.liq: 0.10s
2023/06/16 16:44:04 [video.converter:3] Using preferred video converter: ffmpeg.
2023/06/16 16:44:04 [audio.converter:3] Using samplerate converter: libsamplerate.
2023/06/16 16:44:04 [local_1:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [metadata_map.6:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [metadata_map.5:3] Content type is {}.
2023/06/16 16:44:04 [pipe:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [amplify.3:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [custom_metadata:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [on_frame:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [metadata_map.2:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [metadata_map:3] Content type is {}.
2023/06/16 16:44:04 [input_streamer:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [harbor:3] Adding mountpoint '/' on port 9025
2023/06/16 16:44:04 [cross:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [cue_interrupting_requests:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [interrupting_requests:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [cue_requests:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [requests:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [cue_next_song:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [next_song:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [source.available:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [autodj_startup_blank:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [on_track.2:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [source:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [cue_playlist_jingles:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [playlist_jingles:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [on_track:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [cue_playlist_default:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [playlist_default:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [amplify.2:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [metadata_map.4:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [metadata_map.3:3] Content type is {}.
2023/06/16 16:44:04 [error_jingle:3] "/usr/local/share/icecast/web/error.mp3" is static, resolving once for all...
2023/06/16 16:44:04 [decoder.ffmpeg:3] Requested content-type for "/usr/local/share/icecast/web/error.mp3": {audio=pcm(stereo)}
2023/06/16 16:44:04 [decoder.ffmpeg:3] FFmpeg recognizes "/usr/local/share/icecast/web/error.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/06/16 16:44:04 [decoder.ffmpeg:3] Decoded content-type for "/usr/local/share/icecast/web/error.mp3": {audio=pcm(stereo)}
2023/06/16 16:44:04 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
2023/06/16 16:44:04 [local_2:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:04 [clock.main:3] Streaming loop starts in auto-sync mode
2023/06/16 16:44:04 [clock.main:3] Delegating synchronization to CPU clock
2023/06/16 16:44:04 [video.text:3] Using sdl implementation
2023/06/16 16:44:04 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/4/liquidsoap/nextsong' with body: 
[mp3float @ 0x7fcb40004e40] Could not update timestamps for skipped samples.
Incorrect BOM value
Error reading lyrics, skipped
2023/06/16 16:44:04 [safe_fallback:3] Switch to metadata_map.4.
2023/06/16 16:44:04 [local_1:3] Connecting mount /radio.aac for source@127.0.0.1...
2023/06/16 16:44:04 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/radio_netblade/media/Jingles/radio_netblade_endless1.mp3": {audio=pcm(stereo)}
2023/06/16 16:44:04 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/radio_netblade/media/Jingles/radio_netblade_endless1.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/06/16 16:44:04 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/radio_netblade/media/Jingles/radio_netblade_endless1.mp3": {audio=pcm(stereo)}
2023/06/16 16:44:04 [lang:3] API nextsong - Response (200): annotate:title="Way Down We Go",artist="Kaleo",duration="220.00",song_id="972f182cc16a57381d686efab62c1e4b",media_id="7226",playlist_id="8":media:Daily Playlist/Juli 2019/way_down_we_go.mp3
Incorrect BOM value
Error reading lyrics, skipped
Incorrect BOM value
Error reading lyrics, skipped
Incorrect BOM value
Error reading lyrics, skipped
2023/06/16 16:44:04 [playlist_jingles:3] Prepared "/var/azuracast/stations/radio_netblade/media/Jingles/radio_netblade_endless1.mp3" (RID 3).
2023/06/16 16:44:04 [live_fallback:3] Switch to cross.
2023/06/16 16:44:04 [interrupting_fallback:3] Switch to requests_fallback.
2023/06/16 16:44:04 [requests_fallback:3] Switch to autodj_fallback.
2023/06/16 16:44:04 [autodj_fallback:3] Switch to switch.4.
2023/06/16 16:44:04 [switch.4:3] Switch to on_track.2.
2023/06/16 16:44:04 [switch.3:3] Switch to source.
[mp3float @ 0x7fcb4410ae40] Could not update timestamps for skipped samples.
2023/06/16 16:44:04 [cue_playlist_jingles:3] Cueing in...
2023/06/16 16:44:04 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/radio_netblade/media/Daily Playlist/Juli 2019/way_down_we_go.mp3": {audio=pcm(stereo)}
2023/06/16 16:44:04 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/radio_netblade/media/Daily Playlist/Juli 2019/way_down_we_go.mp3" as video: {codec: png, 300x300, rgb24}, audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/06/16 16:44:04 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/radio_netblade/media/Daily Playlist/Juli 2019/way_down_we_go.mp3": {audio=pcm(stereo)}
2023/06/16 16:44:04 [local_1:3] Connection setup was successful.
2023/06/16 16:44:04 [local_2:3] Connecting mount /radio.mp3 for source@127.0.0.1...
[mp3float @ 0x7fcb4410ae40] Could not update timestamps for discarded samples.
2023/06/16 16:44:04 [decoder:2] Decoding "/var/azuracast/stations/radio_netblade/media/Jingles/radio_netblade_endless1.mp3" ended: Ffmpeg_decoder.End_of_file.
2023/06/16 16:44:04 [next_song:3] Prepared "/var/azuracast/stations/radio_netblade/media/Daily Playlist/Juli 2019/way_down_we_go.mp3" (RID 4).
2023/06/16 16:44:04 [autodj_fallback:3] Switch to dynamic_startup with forgetful transition.
2023/06/16 16:44:04 [dynamic_startup:3] Switch to cue_next_song.
[mp3float @ 0x7fcb4401d240] Could not update timestamps for skipped samples.
2023/06/16 16:44:04 [cue_next_song:3] Cueing in...
2023/06/16 16:44:05 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/radio_netblade/media/Daily Playlist/oktober 2018/where_did_we_go_wrong_-28feat_cali_papershapes-29.mp3": {audio=pcm(stereo)}
2023/06/16 16:44:05 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/radio_netblade/media/Daily Playlist/oktober 2018/where_did_we_go_wrong_-28feat_cali_papershapes-29.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/06/16 16:44:05 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/radio_netblade/media/Daily Playlist/oktober 2018/where_did_we_go_wrong_-28feat_cali_papershapes-29.mp3": {audio=pcm(stereo)}
2023/06/16 16:44:05 [local_2:3] Connection setup was successful.
2023/06/16 16:44:05 [lang:3] AutoDJ is ready!
Incorrect BOM value
Error reading lyrics, skipped
2023/06/16 16:44:05 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/radio_netblade/media/Jingles/radio_netblade_endless_2.mp3": {audio=pcm(stereo)}
2023/06/16 16:44:05 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/radio_netblade/media/Jingles/radio_netblade_endless_2.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/06/16 16:44:05 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/radio_netblade/media/Jingles/radio_netblade_endless_2.mp3": {audio=pcm(stereo)}
Incorrect BOM value
Error reading lyrics, skipped
2023/06/16 16:44:05 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/4/liquidsoap/nextsong' with body: 
2023/06/16 16:44:05 [cross:3] Analysis: -25.857825dB / -83.574067dB (2.83s / 2.85s)
2023/06/16 16:44:05 [cross.smart:3] No transition: using default.
2023/06/16 16:44:05 [cross_before:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:05 [buffer:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:05 [cross_after:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:05 [buffer.2:3] Content type is {audio=pcm(stereo)}.
2023/06/16 16:44:05 [lang:3] API nextsong - Response (200): annotate:title="Endless Music 3",artist="Radio NetBlade",duration="2.00",song_id="9ebbb7fac35a8c940093ec8561c96654",media_id="7379",playlist_id="9",jingle_mode="true":media:Jingles/radio_netblade_endless_3.mp3
Incorrect BOM value
Error reading lyrics, skipped
2023/06/16 16:44:05 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/radio_netblade/media/Jingles/radio_netblade_endless_3.mp3": {audio=pcm(stereo)}
2023/06/16 16:44:05 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/radio_netblade/media/Jingles/radio_netblade_endless_3.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/06/16 16:44:05 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/radio_netblade/media/Jingles/radio_netblade_endless_3.mp3": {audio=pcm(stereo)}
Incorrect BOM value
Error reading lyrics, skipped
[mp3float @ 0x7fcb40004e40] Could not update timestamps for discarded samples.
2023/06/16 16:44:31 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Ffmpeg_decoder.End_of_file.
2023/06/16 16:44:32 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
[mp3float @ 0x7fcb4003cf40] Could not update timestamps for skipped samples.
[mp3float @ 0x7fcb4003cf40] Could not update timestamps for discarded samples.
2023/06/16 16:44:59 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Ffmpeg_decoder.End_of_file.
2023/06/16 16:44:59 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
[mp3float @ 0x7fcb40049a00] Could not update timestamps for skipped samples.
[mp3float @ 0x7fcb40049a00] Could not update timestamps for discarded samples.
2023/06/16 16:45:26 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Ffmpeg_decoder.End_of_file.
2023/06/16 16:45:27 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 2).
[mp3float @ 0x7fcb40046cc0] Could not update timestamps for skipped samples.

Same issue here with rolling release, only when there's no stereotool preset uploaded it will work as it should. 
Also tested without licence key, same issue.

Stable release is working as it should
