### ISSUE TITLE
Move ReplayGain code more up, i.e. before crossfading?

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6338]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #9f7825e (2023-06-10 16:39)

### What happened?

I’m a little unsure about this, maybe @toots can enlighten us.

I _think_ when "Use ReplayGain" is enabled in a station, the

```
# Apply amplification metadata (if supplied)
radio = amplify(override="liq_amplify", 1., radio)

# Replaygain Metadata
enable_replaygain_metadata()
radio = replaygain(radio)
```

should come much earlier, i.e. _before_ crossfading, to avoid loudness jumps when crossing.

The code currently comes in rather late in `liquidsoap.liq`:

[AzuraCast 9f7825e LS Config - RG enabled.txt](https://github.com/AzuraCast/AzuraCast/files/11712986/AzuraCast.9f7825e.LS.Config.-.RG.enabled.txt)

Question @toots: Would that make a difference? My gut feeling says loudness should be normalized (i.e. ReplayGain applied) _before_ trying a crossfade. Is that correct? Does the smart crossfade, for instance, calculate the audio power values from _raw_ audio data or from a source that already had _amplify()_ applied?

Maybe this could explain the sudden audio volume jumps some people experience when using smart crossfading?

**Comment by toots** [comment]
Replaygain is applied per track and depends on metadata to it makes sense to put it right after operators creating sources from files e.g. `playlist` and etc.
