### ISSUE TITLE
SQL ERROR and memory error processing media folders

### ISSUE THREAD

**Issue by sterreke** [AzuraCast/AzuraCast#635]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
I have a music library of +50k songs mounted via NFS.
PHP.ini setting
memory_limit = 256M

Processing the media folders fails with following errors:

In Browser:

ERROR: An exception occurred while executing 'INSERT INTO station_media (station_id, song_id, title, artist, album, lyrics, isrc, length, length_text, path, mtime, fade_overlap, fade_in, fade_out, cue_in, cue_out, unique_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "7e380e568cffbe8611293863a665a697", "Track 10", null, null, null, null, 131, "2:10", "\x4d\x50\x33\x2f\x56\x6f\x6f\x72\x20\x64\x65\x20\x6b\x69\x64\x73\x2f\x53\x69\x6e\x74\x65\x72\x6b\x6c\x61\x61\x73\x20\x6d\x75\x7a\x69\x65\x6b\x2f\x45\x72\x6e\x73\x74\x20\x42\x6f\x62\x62\x69\x65\x20\x65\x6e\x20\x64\x65\x20\x52\x65\x73\x74\x20\x2d\x20\x42\x69\x6a\x20\x53\x69\x6e\x74\x65\x72\x6b\x6c\x61\x61\x73\x2f\x31\x30\x20\x2d\x20\x4a\x6f\x6e\x67\x65\x6e\x73\x20\x68\x65\x62\x20\x6a\x65\x20\xef\x74\x20\x61\x6c\x20\x76\x65\x72\x6e\x6f\x6d\x65\x6e\x2e\x6d\x70\x33", 1191445776, null, null, null, null, null, "9703c7f57102490494f0e855"]: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xEFt al ...' for column 'path' at row 1
file
/var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
line
122
code
0

AND

~$ docker logs azuracast_web_1
[29-Jun-2018 10:48:13] WARNING: [pool www] child 41 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 425984 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/BlobType.php on line 50"

**To Reproduce**
2. Click in administrator page on '5 min sync - Check media folders'

**Expected behavior**
Correct processing of all music files.

**Screenshots**
![image](https://user-images.githubusercontent.com/2543474/42090193-ba37ee32-7ba0-11e8-809e-5ea0b6f0bd67.png)
![image](https://user-images.githubusercontent.com/2543474/42090208-cea42890-7ba0-11e8-93aa-bbc40a9ad19d.png)
![image](https://user-images.githubusercontent.com/2543474/42090223-e6d65762-7ba0-11e8-9ac2-fc3887b70c01.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser chrome
 - Version 67.0.3396.99 (Officiële build) (64-bits) 

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
N/A

**Comment by SlvrEagle23** [comment]
@sterreke Looking into this issue, I'm a little baffled at the fact that MariaDB is trying to insert the song's path as an escaped Unicode string, despite the decoded string consisting of entirely normal ASCII characters as far as I can tell.

Also, the error about "invalid datetime" is especially concerning, as there is no datetime being inserted in that query, and that has me wondering if there's some sort of invalid Unicode there that's escaping out of the query, despite the fact that we use prepared statements across the board.

If you don't mind, can you copy/paste the exact path of the file that's causing that problem? Also, did you upload it via SFTP or via the web interface?

**Comment by sterreke** [comment]
The media files are actually on an NFS mount in docker.

\xef is the culprit, i guess.

Original path:
$ls -al
/data/storage/muziek/MP3/Voor de kids/Sinterklaas muziek/Ernst Bobbie en de Rest - Bij Sinterklaas/10 - Jongens heb je ?t al vernomen.mp3
Even bash isn't showing the correct character (thus showing the question mark).
It is supposed to be the quote '
However /xef (UTF-8) is ï

Anyway I believe this error was due a very bad character. Renaming the file is a decent workaround for me.

This also means this SQL error is not related with the PHP memory overflow.

~$ docker logs azuracast_web_1
[29-Jun-2018 10:48:13] WARNING: [pool www] child 41 said into stderr: "NOTICE: PHP message: PHP Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 425984 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/BlobType.php on line 50"
