### ISSUE TITLE
Unable to log in to a user created by a super administrator even if the information provided is correct

### ISSUE THREAD

**Issue by SalehAcehUtara** [AzuraCast/AzuraCast#6352]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

AzuraCast • v0.18.3 Stable • Docker • PHP 8.2

### What happened?

As an enthusiastic AzuraCast user, I'm having trouble creating a new user and facing the "Credential Failed Login" issue. I want to share this experience and hope to get help and advice from the AzuraCast team to solve this problem.

AzuraCast has become my favorite platform for managing online radio stations. After successfully installing and setting up my first account, I was satisfied with how easy it was to use. However, when I tried to create a new user to double my efforts at managing radio stations, I ran into a challenge that I couldn't handle alone.
After filling in my email and password correctly, I always get a "Credential Failed Login" message when I try to log in with a new user. I tried several different password and email combinations, but the result was the same. This frustrates me because I believe all the information I entered is correct.
I've searched various sources for a solution, but none have provided an adequate answer. My friends who use AzuraCast also don't have this problem, so they can't help me. In situations like these, I rely on the help of the AzuraCast team to solve this problem.
I checked the login failure logs and looked for clues in the AzuraCast documentation, but found no useful information. I'm sure that this problem is not caused by my settings, because my first user can login without problem. I also ensure that there is no limit on the number of users I reach or any other technical hurdles.
Under these circumstances, I feel trapped and cannot continue smoothly managing my radio station. AzuraCast team is my only hope to solve this problem. I hope they can provide specific suggestions and instructions so that I can create a new user and avoid this "Credential Failed Login" problem.
Conclusion:
As a passionate AzuraCast user, I'm having trouble creating a new user with the "Credential Failed Login" issue. Even though I'm sure that all the information I've entered is correct, I keep getting this error message when I try to log in with a new user.
I need help from the AzuraCast team to solve this problem so I can continue my journey with this platform. My hope is to get specific suggestions and instructions for solving this "Credential Failed Login" problem. I really appreciate the attention and help.
Thank You,

**Comment by Vaalyn** [comment]
There was a bug were the password that is entered when creating a new user was not being saved correctly.
This was fixed in https://github.com/AzuraCast/AzuraCast/commit/69f1234af6d0b2e1c4401fe71e9069d5e3fda7a5 on the Rolling-Release channel 3 days ago.

See also https://github.com/AzuraCast/AzuraCast/issues/6292
