### ISSUE TITLE
Any way to skip radio silence?

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#6353]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release # (N/A) // 311 update(s) behind the latest version

### What happened?

So i have this situation.

I have radioshows playing every week on my radio.
I made the scheduled playlist and i set to only one hour (i.e. from 21:00 to 22:00)
I have selected in Advanced: "Interrupt other songs to play at scheduled time."  and "Only play one track at scheduled time."
Playlist Type: General rotation
Playlist Weight: 24

So everything works like it supposed to work. When it's time, the current song stops and starts the radio show.
BUT...
I have one radioshow that somehow everytime is exported 1hour and 10 MINS... these 10 mins are silence. There no any sound on the set. The next set is not running on it's scheduled time, because this one is still running.
I tried to sed the next set with 25 weight, so it will interrupt the interrupted set. But nope.

If i don't set "Interrupt other songs to play at scheduled time.", it's puting the radioshow to queue, and if there are 2-3 songs in the queue before the set, they are playing in that time.

Is there anyway, i can set this to work? Somehow to detect the silence in the stream, and skip the track? Some setting for the liquidsoap? If the sound is 0 to play next track?

EDIT: Something like that [https://www.liquidsoap.info/doc-dev/blank.html](https://www.liquidsoap.info/doc-dev/blank.html), but how and where i should insert it?

**Comment by Moonbase59** [comment]
You might want to follow the discussions at https://github.com/AzuraCast/AzuraCast/discussions/6343 and https://github.com/AzuraCast/AzuraCast/discussions/6334.

HTH & good luck!

**Comment by NicoxDJ** [comment]
Hey @Moonbase59 Yesterday i finally restart the station. I did #6334, and last night i test it. It works perfect, thanks!

**Comment by Moonbase59** [comment]
@NicoxDJ Thanks for the feedback, great it works for you!
