### ISSUE TITLE
Error when trying to update via dashboard

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#6355]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.18.3

### What happened?

When trying to update through the panel, an error appears and the update is not carried out.
Operation system: Ubuntu 22.04

![error](https://github.com/AzuraCast/AzuraCast/assets/58113324/2e981fb5-f420-4503-bff8-95fdb73e0b71)

**Comment by SpeedyCharly** [comment]
This issue was discussed a little while back and should be resolved easily by running this in SSH

_cd /var/azuracast
docker restart azuracast_updater_
