### ISSUE TITLE
Couldn't switch to STABLE even if I wanted to... SSH error

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#6356]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #0a603db (2023-06-16 1:27) 

### What happened?

• Logged into SSH via Putty with root credentials
• Input update commands
• Stalled on error ; 
[ root@vps-cff8157d:/var/azuracast# ./docker.sh update-self
./docker.sh: line 743: unexpected EOF while looking for matching `)'
./docker.sh: line 744: syntax error: unexpected end of file
root@vps-cff8157d:/var/azuracast# ./docker.sh setup-release ] 

Been seeing this error for weeks now... Only WEB update is working for me.  Will hold off on updating until response here
Any ideas?

### Relevant log output

```shell
N/A
```

**Comment by Vaalyn** [comment]
Your `docker.sh` is broken. The current version has 891 lines, yours ends at line 744 according to bash.

This can happen when for whatever reason the download from GitHub when updating the script itself fails, leaving you with only a part of that file.

Just re-download it:
```
curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/main/docker.sh > docker.sh
chmod a+x docker.sh
```

I've added a section about this to the docs: https://docs.azuracast.com/en/user-guide/troubleshooting#docker-utility-script-not-working
