### ISSUE TITLE
FLAC mountpoint breaks station

### ISSUE THREAD

**Issue by saschaludwig** [AzuraCast/AzuraCast#6358]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #c8cf93b (2023-06-17 21:29)

### What happened?

Creating a FLAC mountpoint breaks the whole station due to invalid liquidsoap config.

As stated here:
https://github.com/savonet/liquidsoap/blob/main/CHANGES.md

> BREAKING: in output.{shoutcast,icecast}:
> Old icy_metadata renamed to send_icy_metadata and changed to a nullable bool. null means guess.

What ConfigWriter.php does here:
https://github.com/AzuraCast/AzuraCast/blob/c8cf93bc5cb548f7784bb9c447438b892c159f94/src/Radio/Backend/Liquidsoap/ConfigWriter.php#L1334

Is using the string "true" which then fails at liquidsoap because of the log output shown below.

### Relevant log output

```shell
At /var/azuracast/stations/xxxxxxxxxx/config/liquidsoap.liq, line 247, char 304-310:
output.icecast(%ogg(%flac(samplerate=48000, channels=2, compression=4, bits_per_sample=24)), id="local_2", host = "127.0.0.1", port = 8000, password = "(PASSWORD)", mount = "/radio.flac", name = "xxxxxxxxxx", description = "", genre = "", public = false, encoding = "UTF-8", send_icy_metadata="true", radio)

Error 5: this value has type
  string
but it should be a subtype of the type of the value at icecast.liq, line 47, char 19-62
  bool?
```

**Comment by BusterNeece** [comment]
PR is merged. Thank you for your contribution!
