### ISSUE TITLE
Recording live stream not moving Error on MoveBroadcastsTask

### ISSUE THREAD

**Issue by Eyecu** [AzuraCast/AzuraCast#6360]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#a660942 (2023-06-11 17:25)

### What happened?

Error when running MoveBroadcastsTask
A four digit year could not be found Not enough data available to satisfy format

storageLocation
"Local: \/var\/azuracast\/stations\/relay-radio\/recordings"
task
"MoveBroadcastsTask"

Files in temp direcotry are made for recordings in the following (note they are not having the date)
stream_%Y%m%d-%H%M%S.mp3.tmp

### Relevant log output

```shell
2023/06/19 01:35:38 [lang:3] Recording stopped: Switching from /var/azuracast/stations/relay-radio/temp/shocky/stream_%Y%m%d-%H%M%S.mp3.tmp to /var/azuracast/stations/relay-radio/temp/shocky/stream_%Y%m%d-%H%M%S.mp3
```

**Comment by BusterNeece** [comment]
@Eyecu You may have a temp recording in that directory from before we fixed the recording string format, so it's not able to parse that temp recording. You may have to jump into the container (`./docker.sh bash`) and either rename the recording or delete it.

**Comment by Eyecu** [comment]
@BusterNeece There were no recordings from before as i had just turned on recording yesterday, but i renamed the recordings that were there like you said, and it's working now, Updated to the newest rolling release before a live dj came on and it's naming the temp recording correctly now and seems to be working. So this can be closed. Thank you!
