### ISSUE TITLE
Provide DJ display name in pregenerated LS code, like the login name live_dj(), for use in video stream

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6362]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #9f7825e (2023-06-10 16:39)

### What happened?

I’m trying to get my head around showing a "**Live: DJ Display Name**" indication in my video stream (code will be published here when finished).

Using Liquidsoap 2.2.0+git@dcf405ff4 (installed inside Docker; works well), I’d like to show the current live DJ’s _display name_, but I can’t get the code and API calls sorted out, so this little request (had to use GH since the "Features" page only allows so much text and no images).

I’ve gotten as far as to add a red "Live" indicator but can only show the DJ’s _login name_ (from using `live_dj()`).

![video m2t - VLC media player_010](https://github.com/AzuraCast/AzuraCast/assets/3706922/f6dc2bf8-5902-4e95-9844-3c86a92676ee)

**It would be just great if we could also have a variable like `live_dj_name` within the pre-generated Liquidsoap code. Since you of course know the possibilities best, could we have that?**

I think it might possibly fit into `def dj_auth(login)` or `def live_connected(header)`, what do you think?

I’m sure it would be a great addition to those stations that use video streaming, to easily get at the _DJ display name_ (and possibly even the _DJ’s image_), to make a real great video stream.

**Comment by SpeedyCharly** [comment]
Our station doesn't do video streaming but such a feature would still be useful to us... We have a banner above our chatroom which displays an animation with the faces of all our djs. We could use these variables to switch the banner to ones displaying the dj during his/her live broadcast.
So add my vote to this wish list...

**Comment by Moonbase59** [comment]
Would still be nice to have, but in the meantime I call the API and have to traverse the list of streamers to get at it.

**Comment by BusterNeece** [comment]
@Moonbase59 I looked into this, and tried expanding our API response parsing so we could pass rich JSON data back from the API, but Liquidsoap's type system seems to absolutely hate it. I flagged that with the LS team and haven't heard back. I'd love to be able to supply richer metadata to the LS script, because there are several other things we could do with that.

**Comment by Moonbase59** [comment]
Would still be a "nice-to-have", even if it can be done "the hard way".

**Comment by BusterNeece** [comment]
Tagging this as in-progress since we absolutely do want to get into parsing JSON responses inside Liquidsoap. I have an idea on how to do it, I just haven't gotten back around to doing it. Lost most of this month to chronic back pain flare-ups.

**Comment by Moonbase59** [comment]
Yeah, it’s actually not hard and I do it for my videostreams all the time. We _could_ also just close this, if it requires extra API calls in LS. My videostream uses it like so:

The function to make API GET calls with:

```ruby
def azuracast_api_get(~timeout=2.0, url) =
    full_url = "#{my_api_url}/#{url}"

    log(level=4, label="api_get", "API #{url} - Sending GET request to '#{full_url}'")
    try
        response = http.get(full_url,
            headers=[
                ("accept", "application/json"),
                ("User-Agent", "Liquidsoap AzuraCast"),
                ("X-API-Key", "#{my_api_key}")
            ],
            timeout=timeout
        )

        log(level=4, label="api_get", "API #{url} - Response (#{response.status_code}): #{response}")
        "#{response}"
    catch err do
        log(level=2, label="api_get", "API #{url} - Error: #{error.kind(err)} - #{error.message(err)}")
        "false"
    end
end
```

When metadata updates occur:

```ruby
# API calls take time, let’s run this in a separate thread, so we don’t block anything
a.on_metadata(fun(m) -> thread.run(fast=false, {update_nowplaying(m)}))
```

and within _that_:

```ruby
if m["is_live"] == "true" then
  if live_dj() != "" then
    url = "streamers"
    djs = azuracast_api_get(url)
    # get current live DJ’s name and image from streamers list
    let json.parse (dj_list : [{
      streamer_username: string,
      display_name: string,
      has_custom_art: bool,
      art: string
      }]) = djs
    dj = list.find(fun(entry) -> entry.streamer_username == live_dj(), dj_list)
    log(level=3, "API #{url} - #{dj}")
    show_color := 0xeb0000 # red
    show_alpha := 0.5
    show_text := "Live: #{dj.display_name}"
    if dj.has_custom_art then
      # if we have a DJ image, use it instead of the station logo
      show_image := dj.art
      log(level=3, label="nowplaying", "Show: \"#{show_text()}\", color=0x#{string.hex_of_int(pad=6,show_color())}, alpha=#{show_alpha()}, image='#{show_image()}'")
    else
      # no image, use station logo
      show_image := logo_file
      log(level=3, label="nowplaying", "Show: \"#{show_text()}\", color=0x#{string.hex_of_int(pad=6,show_color())}, alpha=#{show_alpha()}, image='#{show_image()}'")
    end
```

Get well soon!
