### ISSUE TITLE
API call to playlists/xxx fails with error 405

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6366]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #9f7825e (2023-06-10 16:39)

### What happened?

I’m trying to get at a playlist name in Liquidsoap but the API keeps returning error 405, even when using `curl` inside the docker. This applies to both using the internal and external URLs:

```
curl -X 'GET'   'http://127.0.0.1:6010/api/internal/1/liquidsoap/playlist/173'  -H 'accept: application/json' -H 'X-Liquidsoap-Api-Key: mylongAPIkey' -H 'User-Agent: Liquidsoap AzuraCast'
Error: Method not allowed. Must be one of: OPTIONS on /var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php L79
root@533405640ee6:/var/azuracast/www# 
```

Using this LS script:
```
def azuracast_api_get(~timeout=2.0, url) =
    full_url = "#{azuracast_api_url}/#{url}"

    log("API #{url} - Sending GET request to '#{full_url}'")
    try
        response = http.get(full_url,
            headers=[
                ("accept", "application/json"),
                ("User-Agent", "Liquidsoap AzuraCast"),
                ("X-Liquidsoap-Api-Key", "#{azuracast_api_key}")
            ],
            timeout=timeout
        )

        log("API #{url} - Response (#{response.status_code}): #{response}")
        "#{response}"
    catch err do
        log("API #{url} - Error: #{error.kind(err)} - #{error.message(err)}")
        "false"
    end
end

…

let json.parse { name } = azuracast_api_get('playlist/' ^ src)
```

I get in the LS log:
```
2023/06/20 16:12:07 [lang:3] API playlist/173 - Sending GET request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/playlist/173'
…
2023/06/20 16:12:07 [lang:3] API playlist/173 - Response (405): Error: Method not allowed. Must be one of: OPTIONS on /var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php L79
```

I _does_ work when I use AzuraCast’s Swagger pages.

Anything I’m doing wrong here or a bug?

**Comment by BusterNeece** [comment]
@Moonbase59 If you're using the `azuracast_api_url`, that's a direct link to the internal API endpoint for LS commands specifically, not the base URL for the API. You can tell because you're calling `http://127.0.0.1:6010/api/internal/1/liquidsoap/playlist/173` instead of the correct URL, which would be `http://127.0.0.1:6010/api/stations/1/playlist/173`. You'll have to hard-code in that URL, as we don't normally want Liquidsoap doing a bunch of API stuff outside its little sandbox of internal command endpoints.

**Comment by Moonbase59** [comment]
@BusterNeece Yeah, didn’t realize at the time it was the "other way round" API I was calling :-) … and forgot to close this.

But thanks for pointing out that I can use the `http://127.0.0.1:6010/api/` after all—that’ll be much better than using the "outside URL" and having to adapt things if the network infrastructure changes.

Can I also use the predefined `azuracast_api_key` with that?
It would greatly simplify adding a Video stream, eliminating the extra steps for a user to create his own key. (Since the video script would be added in the LS config anyway, after the "Relays" section.)

**Comment by BusterNeece** [comment]
@Moonbase59 That API key should work on any API endpoint, afaik. Is it not working?

**Comment by Moonbase59** [comment]
No, it wasn’t, but I’m querying AzuraCast , not Liquidsoap. Generated a new key in the UI, and with that it works. Just wondered if I could reuse yours for internal work.

**Comment by Moonbase59** [comment]
keep

**Comment by Moonbase59** [comment]
Let’s just dismiss this for more important issues. Not worth fighting the bloody bot for…
