### ISSUE TITLE
Is there a forum for Azuracast? I don't want to fill your issues list ;)

### ISSUE THREAD

**Issue by JohnnyC1951** [AzuraCast/AzuraCast#637]
Question above.

**Comment by SlvrEagle23** [comment]
@JohnnyC1951 Not at the moment, no. I'm not sure I could ever pick something that everyone would agree on using. ;)

If you have any questions, feel free to post them here for now. I may end up setting up a Gitter chat channel or something similar for quick questions and support.

**Comment by xewl** [comment]
Just my 2c aka Rant on Github Issues not really being a forum, but perfect for the issues you have at hand.. 

Long story short:
I'd gladly answer a concise question -if I can and seem fit-, my notifications are on for this repo anyway.

In my opinion, Github's Issues feature is almost the best version of Q&A and in essence a perfect forum for this project. In a forum, this would be a category filled with subthreads on another site. Here, we have the code close to an explanation of a certain problem. I do cringe at Issues like this, where the basic text that gives you steps are intact, and there's solely a title to base upon. I'm just here to show that I'm fine with receiving notifications - but I'm more eager to -not answer-

**Comment by JohnnyC1951** [comment]
Cool. Many Gits expressly forbid it unless it's a very specific code issue. These questions are general.

I am a coder/dev and a long time user of Airtime & more recently Libretime.
I can probably code the (missing) bits I need so: 

What I am trying to do is make streams using playlists derived from the most recent item from collections of RSS podcast feeds. Am I barking up the wrong tree?

I gather you are using LS to transcode. Is this transcoded on the fly, or transcoded once & cached on ingress?

I gather you can use XML playlists, if so must they reference local files only or can they use remote urls?

Thanks for any thoughts :)

**Comment by JohnnyC1951** [comment]
Never mind. I did not care for Ken's attitude. (his reply seems to have disappeared. Seems I have come to the wrong project. I fail to see how a one line question in a topic can possibly be a  quote 'rant' and he is '- more eager to -not answer-'
I shall find a more welcoming project
Thank you . SlvrEagle23 & Ken Verhaegen

'

**Comment by SlvrEagle23** [comment]
@JohnnyC1951 Just for clarity, I am the sole maintainer and developer of the AzuraCast project. Other people can and do comment here on GitHub but they don't represent the project or its administration.

Your points are entirely valid and I would be happy to discuss them with you further. You are right, though, that GitHub may not be the best venue for that. I will look into other methods of group communication and will get back to you.

**Comment by JohnnyC1951** [comment]
I suggest Discord. It integrates right into the Git, But don't worry on my account, I will probably do it using a ffmpeg caching transcoder with a LS 'AutoDJ' as fallback/filler. I was hoping this might be simpler.

**Comment by xewl** [comment]
@JohnnyC1951 @SlvrEagle23 Note to self: don't enter the rant when it's clearly not my call to make anyway (sorry)

**Comment by BartManX** [comment]
thats a great idea !  i found this conversation with a google search for AzuraCast forum ..
