### ISSUE TITLE
PHP-Worker Doesn't Keep Running

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#6372]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.18.5

### What happened?

S.O.: Ubuntu 22.04 updated

The php-worker is not running, when clicking on the "restart" button it appears "running" but soon after it stops again. I noticed in the system debugger that when the information of "100 messages in the queue" appears, the php-worker stops.

![Screenshot 2023-06-25 at 14-56-51 Depurador do sistema](https://github.com/AzuraCast/AzuraCast/assets/58113324/8584994c-3553-421d-a5e0-0ba233a2266a)

[mariadb-log.txt](https://github.com/AzuraCast/AzuraCast/files/11860473/mariadb-log.txt)
[nginx-log.txt](https://github.com/AzuraCast/AzuraCast/files/11860474/nginx-log.txt)
[azuracast log.txt](https://github.com/AzuraCast/AzuraCast/files/11860475/azuracast.log.txt)

**Comment by roger-net** [comment]
Sorved.

**Comment by benotf** [comment]
Same for me. But in French ☺️
![Screenshot_20231018_234032](https://github.com/AzuraCast/AzuraCast/assets/48473816/ed8680d5-73e6-4c39-a8a0-87e52f4a4072)
