### ISSUE TITLE
Very slow loading before playing

### ISSUE THREAD

**Issue by webezvous** [AzuraCast/AzuraCast#6373]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #996bc43 (2023-06-26 10:42)

### What happened?

I installed Azuracast on a Cloud server (Ubuntu 22.04, 2 vCore, RAM:2 GB, SSD:80 GB).
On the public page (and web player), when I click on "Play", the stream MP3 takes 2 to 3 minutes to load before it starts playing.
The stream MP3 on VLC is playing fine. 

What can I do to reduce this delay?

**Comment by webezvous** [comment]
Error

**Comment by BusterNeece** [comment]
We don't have nearly enough information on this to know what might be causing it. It could be any of a ton of things. The built-in delay for streaming is almost instantaneous for both HLS and Icecast/Shoutcast streams these days, so there is certainly something wrong if your delay is measured in _minutes_, but without more console logs it is difficult to know what's causing it.
