### ISSUE TITLE
Live streaming doesn't show id3 tags anymore

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#6378]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling release after v17.7, before v18 (2023-04-02)

### What happened?

So, basically i came from 17.1, where everything was working.
I was streaming with [this app](https://apps.apple.com/us/app/ladiocast/id411213048?mt=12), and when i connect every tag was populating correctly, and i could change the Title tag and set the live stream name (the place where i'm playing).
Today i was preparing for new party, and i realized, that there is no ANY tag available. Same streaming application, but different Azuracast. The Azuracast API doesn't put any tag, except the streamer name.
![](https://i.imgur.com/6BlVAVh.png)

Since Ansible is no longer supported, can you please refer me to which php file should i edit, so i can make the API read again the id3 tags? It's really important for me, because i have website, where i get all data and display it to my users.

And before someone say something, i'm still using Ansible, because Docker is too heavy for my server to handle.
And right now i'm afraid to pull the new code, because i'm afraid that everything will stops working.

**Comment by expert-geeks** [comment]
I'm on the rolling release 
`Rolling Release #[e3c768c](https://github.com/AzuraCast/AzuraCast/commit/e3c768c4a6593c15fcd9cb1c52c08f3524e6ec0c) (2023-08-21 9:03) • Docker • PHP 8.2'
I don't get ID3 tags connecting the DJ input to shoutcast. Playback of MP3 files etc shows ID3 tags correctly.
