### ISSUE TITLE
Constant IP Bans on SFTP

### ISSUE THREAD

**Issue by jadenf1** [AzuraCast/AzuraCast#6382]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

A customer keep getting the following errors on the AzuraCast SFTP logs:

{"level":"debug","time":"2023-07-01T16:56:11.700","sender":"SSH","message":"connection refused, ip \"86.167.XXX.XXX\" is banned"}

Connecting works fine, then as soon as we upload anything via SFTP, it seems to just kill the connection - how can we disable IP bans or connection tracking?

This is a brand new install of AzuraCast on Ubuntu 20.04. 

Any help would be appreciated.

**Comment by SpeedyCharly** [comment]
That issue would be best dealt with by creating a support ticket with your provider; it's them blocking you, not Azuracast.

There's no such limitation with my provider; you might want to switch providers if this issue isn't addressed by the current one.

**Comment by jadenf1** [comment]
This is a dedicated server for one of our customers with AzuraCast installed on, pretty basic really - basic install of Ubuntu 20.04. 

Nothing network level blocking the traffic as clearly stated in the logs. 

Does AzuraCast have something like Fail2Ban installed? Tried looking for it and can't see it installed anywhere. 

Thanks in advance.

**Comment by itsolliedev** [comment]
With regards to this, I am using the exact same host with a different AzuraCast version and it is working fine. It is something to do with the Rolling Release - #2e15da8

**Comment by Moonbase59** [comment]
I [tried](https://github.com/AzuraCast/AzuraCast/issues/6383#issuecomment-1616050368) using 5 concurrent connections on my server and had no problems:
- Ubuntu 22.04.2 LTS Server
- AzuraCast Rolling Release #[996bc43](https://github.com/AzuraCast/AzuraCast/commit/996bc43773b414ac1e72e270741bb26ba4409c38) (2023-06-26 10:42)

**Comment by jadenf1** [comment]
Hello,

I've edited the SFTPGO config file, disabled the defender, and also increased the limits on how many files can be uploaded per second. 

I ran: find / -name sftpgo.json

<img width="1301" alt="Screenshot 2023-07-01 at 21 43 53" src="https://github.com/AzuraCast/AzuraCast/assets/62446711/dff4cee2-c080-46e8-b496-026f1da0ac2e">

<img width="1301" alt="Screenshot 2023-07-01 at 21 43 27" src="https://github.com/AzuraCast/AzuraCast/assets/62446711/c7d01321-32b3-4c7b-8910-ba4b0c6d70d1">

Then, edited the sftpgo.json files, and modified the following to false. I also increased the max connections per host.

**Comment by Moonbase59** [comment]
Thanks for your feedback, @jadenf1, these are valuable insights!

Maybe @BusterNeece could add some settings for _sftpgo_, in system or station administration.

**Comment by pitsch** [comment]
as there is constant hammering on the sftp port, with lots of invalid user names and silly brute force pw trials, i´d like to be able to restrict SFTP access to team members, and those who have accounts to the system, djs could get access to stats or a very basic role to count as users.  IPs of currently logged in users would then be used as a whitelist for the sftp server.  currently i'd rather consider to set up port knocking or whitelist specific ip range of recurring team members.
