### ISSUE TITLE
SFTP Filezilla Uploads

### ISSUE THREAD

**Issue by tmiradio** [AzuraCast/AzuraCast#6383]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Ubuntu 20.04

### What happened?

Just been told by my service provider that my IP has been banned. I have been uploading mp3 to my server for my channels and I have noticed that I unable to re-access. Is it true that if you decide to upload multiple mp3 files at the same time (5 concurrent uploads) would this cause the issue? I am not sure if you are limited to 1 upload at a time. Please let me know.

This is a continuation from the previous ticket sent in by my provider:
[https://github.com/AzuraCast/AzuraCast/issues/6382](url)

**Comment by Moonbase59** [comment]
Must be a provider restriction. I just set my FileZilla to 5 concurrent uploads and tested with my server—no problems at all.

**Comment by tmiradio** [comment]
Could you possibly address the ticket 6382 please and let my provider know

**Comment by SpeedyCharly** [comment]
Might be a better idea to change providers - preferably one who offers free migration....

**Comment by tmiradio** [comment]
I dont want to change providers to be fair. I have a dedicated server with Azuracast installed on it and I do have root access

**Comment by jadenf1** [comment]
Is there any way we can modify the built-in SFTP server on AzuraCast, or change the settings in a config file?

I believe the config of it may be the issue:

https://github.com/drakkan/sftpgo/blob/main/docs/defender.md

The below is from the startup config of the SFTP log on AzuraCast:

{"level":"debug","time":"2023-07-01T14:47:52.325","sender":"config","message":"config file used: '\"/var/azuracast/sftpgo/sftpgo.json\"', config loaded: {Common:{IdleTimeout:15 UploadMode:2 Actions:{ExecuteOn:[upload pre-delete rename] ExecuteSync:[] Hook:http://127.0.0.1:6010/api/internal/sftp-event} SetstatMode:1 RenameMode:0 TempPath: ProxyProtocol:0 ProxyAllowed:[] ProxySkipped:[] StartupHook: PostConnectHook: PostDisconnectHook: DataRetentionHook: MaxTotalConnections:0 MaxPerHostConnections:20 AllowListStatus:0 AllowSelfConnections:0 DefenderConfig:{Enabled:true Driver:memory BanTime:30 BanTimeIncrement:50 Threshold:15 ScoreInvalid:2 ScoreValid:1 ScoreLimitExceeded:3 ScoreNoAuth:0 ObservationTime:30 EntriesSoftLimit:100 EntriesHardLimit:150} RateLimitersConfig:

**Comment by tmiradio** [comment]
for the record...jadenf1 is my provider

**Comment by BusterNeece** [comment]
I've looked into sftpgo's configuration and have loosened the ban conditions used by defender. We still want to ban a bunch of failed login attempts, but we don't want to ban people just for exceeding transfer rates if they're valid users, so I've updated the config to reflect that.
