### ISSUE TITLE
Drag and drop scheduler

### ISSUE THREAD

**Issue by jrsarath** [AzuraCast/AzuraCast#639]
Hello there,
thanks for this amazing piece of software..
i was wondering if we could get a drag and drop music scheduler
it very annoying to schedule list's using playlist settings..

**Comment by SlvrEagle23** [comment]
Merging other related issues with this one.

Copying a comment from @xtechgamer735 in #779:

> I think it would be good if I could view an hour by hour view of each day, selected by a calendar, which I can drag playlists or individual audio items into. This would be a little easier than scheduling each playlist separately if I wanted a certain piece of audio to play out once for example.Scheduling on a per playlist basis is good, this can be done to set up a 'default rotation'. These scheduled playlists would show in this new view and have the option for them to be overridden with audio or changed. There could also be an option to expand them to view the exact song list.This may be more complicated, but the option to expand the playlist into a unique hour and edit it with all items shown would be really good.There should be two views possible for this, an isolated hour view (so just 6PM for example) or a complete day view (so 00 to 23) in a list. Each hour should show its expected duration in the header (or separator part).I look forward to hearing your feedback on this and helping to clarify anything that may need it,Many thanks.

...and a photo from @MrSteelMiner in #1184:

![](https://user-images.githubusercontent.com/47743654/52952124-f4110800-3383-11e9-8470-1088c16b58cf.png)

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39021/draganddrop-music-scheduler
