### ISSUE TITLE
Deselect all rows is not working on pages other than the first page

### ISSUE THREAD

**Issue by zcraber** [AzuraCast/AzuraCast#6392]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #f5f9dfb (2023-07-03 14:26)

### What happened?

Could this be counted as a bug? I noticed this behaviour on the `Music Files` [page](https://demo.azuracast.com/station/1/files). Selecting/deselecting all rows using the table header checkbox is working fine on page 1. But moving to page 2, it's not! Here's a screen recording of what I meant:

![azuracast unselect](https://github.com/AzuraCast/AzuraCast/assets/61133303/5f0153fd-040d-4683-8834-3d295fdf68d9)

**Comment by Moonbase59** [comment]
Interesting find. I had to go up to page 1131 (of 10 ea.) to see this effect. It seems to happen when the last page isn’t "full", i.e. hasn’t the full number of entries like 10, 25, …, etc.

I’m on Rolling Release #[996bc43](https://github.com/AzuraCast/AzuraCast/commit/996bc43773b414ac1e72e270741bb26ba4409c38) (2023-06-26 10:42).

**Comment by BusterNeece** [comment]
Valid issue; we're in the process of reviewing an upgrade of our frontend framework to Bootstrap 5 and Vue 3, and this should be fixed in that environment. Expect it in the rolling release shortly.

**Comment by zcraber** [comment]
Closing this as the issue is now fixed.
