### ISSUE TITLE
Mount Point Intro is breaking the stream

### ISSUE THREAD

**Issue by renatopinto89** [AzuraCast/AzuraCast#6395]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.18.5 Stable • Docker • PHP 8.2 

### What happened?

Hello you amazing people!

Since I´ve updated AzuraCast to the latest stable release, some stations with Mount Point Intros became broken, meaning, the Intro plays fine, but the handover to the actual stream isn´t made, so it´s silence aftterwards.
I´ve tried to troubleshoot by making sure the Intro was in the same format and bitrate as the Mount Point itself, which checks out (was working fine before the update) and nothing shows in the logs

Maybe it´s important to note that the streams are running Shoutcast.

Thank you for your time and for this amazing project

Kind Regards

**Comment by Moonbase59** [comment]
I wonder if this could be raleted to https://github.com/AzuraCast/AzuraCast/issues/6407 — are you, by chance, using Firefox 115?
