### ISSUE TITLE
Icecast Server YP Directory

### ISSUE THREAD

**Issue by tmiradio** [AzuraCast/AzuraCast#6398]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Ubuntu 20.04

### What happened?

I am trying to see if I can add a section on my servers to allow for Internet-Radio.com to be able to initiate their side of the directory so my servers are then public on their side.

All the documentation I have found is for Centovacast system and none for Azuracast. 

Are you able to assist please? I have linked you the relevant documentation to assist with your findings.

[https://www.internet-radio.com/community/threads/icecast-server-yp-directory-settings.22223/](url)

Thank you in advance

**Comment by Moonbase59** [comment]
Some work was lately done to better integrate YP providers, and it works fine in the latest rolling releases. Check out these issues for some hints:

- https://github.com/AzuraCast/AzuraCast/issues/6241
- https://github.com/karlheyes/icecast-kh/issues/417

Basically, under _Edit Station Profile → Broadcasting → Custom Configuration_, enter the directory servers to be used, like so:

```
<directory>
    <yp-url-timeout>15</yp-url-timeout>
    <yp-url>http://dir.xiph.org/cgi-bin/yp-cgi</yp-url>
</directory>
<directory>
    <yp-url-timeout>15</yp-url-timeout>
    <yp-url>http://icecast-yp.internet-radio.com</yp-url>
</directory>
```
The former entry is for `dir.xiph.org`, the latter for `internet-radio.com`.

Then, under _Broadcasting → Mount Points → (mountpoint) → Edit → Basic Info_, check _Publish to "Yellow Pages" Directories_.

Optionally, under _Advanced → Custom Frontend Configuration_, you can add extended headers per mountpoint, as suggested by [stream-meta.info](https://www.stream-meta.info/version_2_headers.html), for instance like so:

```
<http-headers>
  <header name="icy-index-metadata" value="1" />
  <header name="icy-version" value="2" />
  <header name="icy-logo" value="https://example.com/static/uploads/browser_icon/192.1678626043.png" />
  <header name="icy-country-code" value="DE" />
  <header name="icy-country-subdivision-code" value="DE-BY" />
  <header name="icy-geo-lat-long" value="48.333281,11.806216" />
  <header name="icy-language-codes" value="deu,eng" />
  <header name="icy-do-not-index" value="0" />
</http-headers>
```

After some time (often just a few minutes), and some checks done by the YP provider, your station should be listed. Most YP providers display one entry per published mountpoint.

**Comment by Moonbase59** [comment]
@tmiradio Since Internet Radio has no guide for AzuraCast yet, you might be the first to create one in their ["Guides" section](https://www.internet-radio.com/community/forums/guides.12/)! ;-)

**Comment by tmiradio** [comment]
For some unknown reason, I fail to locate Custom Configuration. Please check the image
![Screenshot 2023-07-06 172240](https://github.com/AzuraCast/AzuraCast/assets/121205761/87991826-a85a-4cc8-a34e-6c9205a01dd3)

**Comment by Moonbase59** [comment]
It’s not under _Broadcasting_, but under _Edit Station Profile → Broadcasting…_ (click the pencil next to the station name or use the _Profile → Edit Profile_ station menu entry.

**Note:** For using the advanced functions, you’ll also need to check _Enable Advanced Features_, under _Administration → System Maintenance → System Settings → Settings_.

**Comment by tmiradio** [comment]
I have done all that and still I go to the Internet-Radio website and nothing is showing and I have zero clue on how to remedy this.

**Comment by Moonbase59** [comment]
Odd. For comparison: I run Rolling Release #[996bc43](https://github.com/AzuraCast/AzuraCast/commit/996bc43773b414ac1e72e270741bb26ba4409c38) (2023-06-26 10:42), and Icecast 2.4.0-kh21.8.

Just tried it again, and it worked within 2 minutes:

![Auswahl_226](https://github.com/AzuraCast/AzuraCast/assets/3706922/f0ac8f93-a93a-4b61-a909-f722a32bd150)

If you go to your Icecast admin page and check the mount point, it should show `public 1` and the `yp_currently_playing` like so:

![Icecast Streaming Media Server – Mozilla Firefox_001](https://github.com/AzuraCast/AzuraCast/assets/3706922/13a6f0f9-5f6f-47f7-b7bb-ff75ce42e8ef)

Also check that your Icecast is actually running and the `listenurl` is correct (open it in an audio player like Audacious or VLC).

You _did_ reload/restart broadcasting after making the changes, right?

**Comment by Moonbase59** [comment]
For verification, I updated to Rolling Release #[221852a](https://github.com/AzuraCast/AzuraCast/commit/221852abf30a95b4e06e8514ec289717946518f4) (2023-07-05 16:32) and Icecast 2.4.0-kh22.

It still works, but after changes I had to _Restart Broadcasting_ (not just _Reload_), so the Icecast gets restarted, too. (A restart of Icecast is needed when changing YP settings.)

**Comment by tmiradio** [comment]
I am unable to locate how to access my icecast admin page. Is it from the server itself or elsewhere?
When I did all the changes, the server requested that I did the restart to which I completed successfully. My host is unable to assist as he normally deals with server handling and not azuracast.

**Comment by Moonbase59** [comment]
AzuraCast has docs here: https://docs.azuracast.com/en/home

Locate the "Broadcasting Service" card on the station management page, click on "Show Credentials", click on the little "copy" icon right next to the Administration password (copies that into the clipboard), then click the "Administration" link.

On the Icecast page that shows up, login with the user name shown and the copied password.

**Comment by tmiradio** [comment]
OK, thank you for helping with that. I have just checked all my channels and all are showing the right credentials as you have previously suggested showing that the public is set to 1 and the yp_currently_playing is showing the actual song information playing.
I even checked the audio on the listenerurl to check if all is playing and I can confirm that all is good.

I have no clue what I else I can do.

**Comment by Moonbase59** [comment]
You might try _Broadcasting → Restart Broadcasting_ again. AzuraCast, on changes, usually prompts for **_Reload_** and yes, there _is_ a difference.

- On which Rolling Release exactly are you? (Can be found at the bottom of most pages)
- What Icecast version is shown on the Icecast admin page?

**Comment by tmiradio** [comment]
My rolling release is on #2e15da8

Icecast 2.4.0-kh21.8

**Comment by tmiradio** [comment]
I checked all typos....I copied and pasted the scripts to all channels anyway.....all are fine.

**Comment by tmiradio** [comment]
On each of my channels....I pasted this script into the section "Edit Station Profile > Broadcasting and added this into the Custom Config:

<directory>
    <yp-url-timeout>15</yp-url-timeout>
    <yp-url>http://dir.xiph.org/cgi-bin/yp-cgi</yp-url>
</directory>
<directory>
    <yp-url-timeout>15</yp-url-timeout>
    <yp-url>http://icecast-yp.internet-radio.com</yp-url>
</directory>

followed by this on the Broadcasting section > Mount Points > Edit then onto Advanced then copied this script into the Custom Frontend Config:

<http-headers>
  <header name="icy-index-metadata" value="1" />
  <header name="icy-version" value="2" />
  <header name="icy-logo" value="https://example.com/static/uploads/browser_icon/192.1678626043.png" />
  <header name="icy-country-code" value="DE" />
  <header name="icy-country-subdivision-code" value="DE-BY" />
  <header name="icy-geo-lat-long" value="48.333281,11.806216" />
  <header name="icy-language-codes" value="deu,eng" />
  <header name="icy-do-not-index" value="0" />
</http-headers>

**Comment by Moonbase59** [comment]
Okay, #2e15da8 and icecast-kh21.8 should work (but I’d recommend an update nevertheless). **Did you do a _Broadcasting → RESTART Broadcasting_?**

Your code doesn’t show. Use code tags, please (surround your code with separate lines consisting of ` ``` ` (3 x accent grave)).

**Comment by tmiradio** [comment]
I have restarted it, yes

On each of my channels....I pasted this script into the section "Edit Station Profile > Broadcasting and added this into the Custom Config:

```<directory>
    <yp-url-timeout>15</yp-url-timeout>
    <yp-url>http://dir.xiph.org/cgi-bin/yp-cgi</yp-url>
</directory>
<directory>
    <yp-url-timeout>15</yp-url-timeout>
    <yp-url>http://icecast-yp.internet-radio.com</yp-url>
</directory>```

Followed by this on the Broadcasting section > Mount Points > Edit then onto Advanced then copied this script into the Custom Frontend Config:

```<http-headers>
  <header name="icy-index-metadata" value="1" />
  <header name="icy-version" value="2" />
  <header name="icy-logo" value="https://example.com/static/uploads/browser_icon/192.1678626043.png" />
  <header name="icy-country-code" value="DE" />
  <header name="icy-country-subdivision-code" value="DE-BY" />
  <header name="icy-geo-lat-long" value="48.333281,11.806216" />
  <header name="icy-language-codes" value="deu,eng" />
  <header name="icy-do-not-index" value="0" />
</http-headers>```

**Comment by Moonbase59** [comment]
Looks good so far, except for the missing `<directory>` (first block, first line).

You might leave out the second block (on the mountpoints) for now, and btw, you’d locate your station near Munich, Germany with that ;-) Only few providers use those headers, and they’re not strictly necessary for YP listing.

**Comment by Moonbase59** [comment]
> I have tried to update my server but it comes with this error script:
> 
> `ConnectException at /var/azuracast/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php L210: cURL error 6: Could not resolve host: updater (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://updater:8080/v1/update`

Please open a separate issue for that—that’s some kind of update error, unrelated to YP.

**Comment by tmiradio** [comment]
![Screenshot 2023-07-07 155442](https://github.com/AzuraCast/AzuraCast/assets/121205761/e78a4aec-1176-4828-bce5-036e9be4be22)

how is this!

**Comment by tmiradio** [comment]
![Screenshot 2023-07-07 155553](https://github.com/AzuraCast/AzuraCast/assets/121205761/2ca0be46-eba9-44ff-ae76-381db56b39ef)

**Comment by Moonbase59** [comment]
Yup, this looks correct (would provide updates to `dir.xiph.org` and `internet-radio.com`.

For easier diagnosis, I’d leave out the mountpoint headers for now (being incorrect anyway, except if your station would sit in the woods near Munich Airport—this is just an example).

**Comment by tmiradio** [comment]
ill remove them and restart?

**Comment by Moonbase59** [comment]
Would you mind sharing your Icecast Config? (_Logs → Icecast Configuration → Copy to Clipboard_, passwords will be replaced by "(PASSWORD)")

Yup, just remove the whole block, including the `<http-headers>` and `</http-headers>`.

**Comment by tmiradio** [comment]
```
<icecast>
    <location>AzuraCast</location>
    <admin>icemaster@localhost</admin>
    <hostname>server1.wguradio.com</hostname>
    <limits>
        <clients>2500</clients>
        <sources>1</sources>
        <queue-size>524288</queue-size>
        <client-timeout>30</client-timeout>
        <header-timeout>15</header-timeout>
        <source-timeout>10</source-timeout>
        <burst-size>65535</burst-size>
    </limits>
    <authentication>
        <source-password>(PASSWORD)</source-password>
        <relay-password>(PASSWORD)</relay-password>
        <admin-user>admin</admin-user>
        <admin-password>(PASSWORD)</admin-password>
    </authentication>
    <listen-socket>
        <port>8020</port>
    </listen-socket>
    <mount type="normal">
        <mount-name>/radio.mp3</mount-name>
        <charset>UTF8</charset>
        <stream-name>Dance</stream-name>
        <listenurl>https://server1.wguradio.com/listen/dance/radio.mp3</listenurl>
        <stream-description>All styles of Underground Dance Music</stream-description>
        <stream-url>https://wguradio.com</stream-url>
        <genre>house, techno, trance, hard dance, drum n' bass</genre>
        <fallback-mount>/fallback-[320].mp3</fallback-mount>
        <fallback-override>1</fallback-override>
        <header name="icy-index-metadata" value="1"/>
        <header name="icy-version" value="2"/>
        <header name="icy-logo" value="https://example.com/static/uploads/browser_icon/192.1678626043.png"/>
        <header name="icy-country-code" value="DE"/>
        <header name="icy-country-subdivision-code" value="DE-BY"/>
        <header name="icy-geo-lat-long" value="48.333281,11.806216"/>
        <header name="icy-language-codes" value="deu,eng"/>
        <header name="icy-do-not-index" value="0"/>
    </mount>
    <fileserve>1</fileserve>
    <paths>
        <basedir>/usr/local/share/icecast</basedir>
        <logdir>/var/azuracast/stations/dance/config</logdir>
        <webroot>/usr/local/share/icecast/web</webroot>
        <adminroot>/usr/local/share/icecast/admin</adminroot>
        <pidfile>/var/azuracast/stations/dance/config/icecast.pid</pidfile>
        <alias source="/" dest="/status.xsl"/>
        <ssl-private-key>/var/azuracast/acme/ssl.key</ssl-private-key>
        <ssl-certificate>/var/azuracast/acme/ssl.crt</ssl-certificate>
        <ssl-allowed-ciphers>ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS</ssl-allowed-ciphers>
        <deny-ip>/var/azuracast/stations/dance/config/ip_bans.txt</deny-ip>
        <deny-agents>/var/azuracast/stations/dance/config/user_agent_bans.txt</deny-agents>
        <x-forwarded-for>127.0.0.1</x-forwarded-for>
    </paths>
    <logging>
        <accesslog>icecast_access.log</accesslog>
        <errorlog>/dev/stderr</errorlog>
        <loglevel>2</loglevel>
        <logsize>10000</logsize>
    </logging>
    <security>
        <chroot>0</chroot>
    </security>
    <directory>
        <yp-url-timeout>15</yp-url-timeout>
        <yp-url>http://dir.xiph.org/cgi-bin/yp-cgi</yp-url>
    </directory>
    <directory>
        <yp-url-timeout>15</yp-url-timeout>
        <yp-url>http://icecast-yp.internet-radio.com</yp-url>
    </directory>
</icecast>

```

**Comment by Moonbase59** [comment]
Looks good to me.

BUT the stream 
https://server1.wguradio.com/listen/dance/radio.mp3 always _stops after 1:43_. 

This is not enough for a valid YP entry (the directory servers check once in a while, and want a _continuous_ stream).

You should find out what’s causing this first. For others’ reference, here are above stream’s response headers:

![Auswahl_228](https://github.com/AzuraCast/AzuraCast/assets/3706922/e656c8db-5136-41bc-b041-233e86a35245)

**Comment by tmiradio** [comment]
Just checking now

**Comment by tmiradio** [comment]
![Screenshot 2023-07-07 162327](https://github.com/AzuraCast/AzuraCast/assets/121205761/01814584-2c20-444b-bc28-be4156afa060)

Its fine for me

**Comment by Moonbase59** [comment]
Yeah, fine here now, too, using Audacious, VLC and Chromium. Maybe that was because I was looking at the headers, who knows.

**Comment by tmiradio** [comment]
so now what?

**Comment by tmiradio** [comment]
trying it now

**Comment by tmiradio** [comment]
OK, still nothing. I have send the config file to Internet-Radio to see if they can remedy it but thank you for trying to help at least.

It means a lot.

**Comment by Moonbase59** [comment]
It actually works, at least on `dir.xiph.org`:

![Auswahl_230](https://github.com/AzuraCast/AzuraCast/assets/3706922/20798b82-d55b-40b2-82f5-04c7a86eec47)

Just probably not the best idea to call the Radio "Dance", since you get about a zillion hits on `internet-radio.com`. Maybe rename it to "WGU Radio" or the like?

**Comment by Moonbase59** [comment]
Whatever you have under _Edit Station Profile → Profile_, like _Name_, _Description_ and _Genre_ gets used in the Icecast configuration, and then of course in the YP entries.

**Comment by tmiradio** [comment]
so edit the same two sections as I did before basically?

**Comment by Moonbase59** [comment]
Sure, here:

![Auswahl_231](https://github.com/AzuraCast/AzuraCast/assets/3706922/c6e5236b-7caf-4f5f-9816-d503c8854952)

**Comment by tmiradio** [comment]
Yes!! It's working now :)

**Comment by Moonbase59** [comment]
Great it worked out for you. Let’s say you owe me a beer ;-)

You might want to close this when it all works.

**Comment by tmiradio** [comment]
Will do...
and ill say a few beers to be fair

**Comment by tmiradio** [comment]
Thank you once again buddy.

**Comment by BusterNeece** [comment]
Glad you were able to get it all worked out. Thank you @Moonbase59 for the extensive help.

**Comment by Moonbase59** [comment]
No problem, we all help each other. Thanks for the kind words.

**Comment by cheleentano** [comment]
Hi guys, everything shows fine in the internet-radio catalog, but the field where the site address is indicated is empty, although the link is specified in the settings. Is everyone like this?

**Comment by tmiradio** [comment]
@cheleentano yes, I am not sure why this is like this. Maybe someone could answer this for us?
