### ISSUE TITLE
Station Genre limited to 150 characters (too short in some cases)

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6399]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

For better recognition in YP directories, I tried to enter some station genres under _Edit Station Profile → Profile → Genre_ but it appears the input field is limited to 150 characters:

Input:
```
Celtic, Classic Rock, Darkwave, Deep Trance, Disco, Easy Listening, Electro, Electronic, Folk Rock, Glam Rock, Goa, Gothic, Hard Rock, Heavy Metal, House, Irish Folk, Lounge, Motown, New Age, Oldies, Philly Soul, Pop, Power Metal, Prog Rock, Psytrance, Schlager, Soul, Southern Rock, Synthpop
```

Result (in Station, Icecast and YP entries):
```
Celtic, Classic Rock, Darkwave, Deep Trance, Disco, Easy Listening, Electro, Electronic, Folk Rock, Glam Rock, Goa, Gothic, Hard Rock, Heavy Metal, Ho
```

Icecast and YP directories can handle much longer entries, and sometimes it is advisable to use these (above is a collection of a weekly program in a "Various genres" station which shall be found under each entry). YP directories usually offer search by genre, so taking advantage of this makes sense to get more listeners.

**Comment by BusterNeece** [comment]
Every database column length calculation is a balancing act, weighing the total size of the database and performance of searches, etc. against the reasonable length that would be expected of something in that field.

Even given this use-case (which looks a little like "SEO stuffing" to me), I still think the limit of 150 characters is entirely reasonable for the vast majority of cases, and I don't think I'd want to possibly make every single row in the `station_media` table (a notoriously huge table already) bigger just to accommodate these edge cases.

**Comment by BusterNeece** [comment]
@Moonbase59 Oh, you mean the STATION'S genre field, not the genre field on each track?

**Comment by BusterNeece** [comment]
Yeah you totally said "Station Genre" in like 4 places. I just can't read.

We can expand that field no problem. Should only be a few dozen records in `stations` tops, and we have some recent savings on that table anyway.

**Comment by Moonbase59** [comment]
That’d be nice! Phew, misunderstandings ;-) Maybe you remembered by "multiple genres" feature request… (Even I currently restrict multiple genres per song to one grouping, plus max. 6 genres.) :-)

**Comment by Moonbase59** [comment]
Not _quite_ as much as I (planned to) need, but VARCHAR(255) is a good compromise for most of us, I should think. Thanks!
