### ISSUE TITLE
Server Update Issue

### ISSUE THREAD

**Issue by tmiradio** [AzuraCast/AzuraCast#6402]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Ubuntu 20.04

### What happened?

I have tried to update my server but it comes with this error script:

```ConnectException at /var/azuracast/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php L210: cURL error 6: Could not resolve host: updater (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://updater:8080/v1/update```

**Comment by tmiradio** [comment]
will anyone be taking a look at this issue for me?

**Comment by BusterNeece** [comment]
@tmiradio If this happens, try running the update from shell: https://docs.azuracast.com/en/getting-started/updates

**Comment by tmiradio** [comment]
Still having these issues....I now have 11 updates pending and I am unable to do anything by them
![image](https://github.com/AzuraCast/AzuraCast/assets/121205761/64759529-7336-4f55-87e5-8a86f2d8ba84)

**Comment by BusterNeece** [comment]
@tmiradio Did you read my response? If you can't update via the web, that just means you have to update via SSH. I'll look into updating the app to properly indicate this, but there is certainly still a way you can update.

**Comment by tmiradio** [comment]
I dont have a clue on how to do this.

**Comment by tmiradio** [comment]
I know you have sent me how to do it but when I look at the server, I do not have access to certain areas.

**Comment by Sakretsos** [comment]
Hello @tmiradio,
We have already discuss this problem on the bellow link
https://github.com/AzuraCast/AzuraCast/issues/6218

You can fix this issue with the bellow commands with root access:
```
1) Access Azuracast via SSL with root credentials;
2) Send command;
cd /var/azuracast
docker restart azuracast_updater
3)Exit SSL and your WEB updater should now work
```
Note: you have to do this every time you restart your linux server.
