### ISSUE TITLE
Rolling #40155bd: "Unicorn Background" can’t be overridden

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6409]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #40155bd (2023-07-09 4:29)

### What happened?

Referring to https://github.com/AzuraCast/AzuraCast/discussions/6406#discussioncomment-6395977, here is the bug report:

> > The Unicorn background has come back on the public pages, even though I have set a general override for background, default cover and browser icon in Administration → Custom Branding. This should apply to all stations, if nothing else is set there. (When using station branding, the uploaded background image is also ignored.)
> 
> This seems to be a bug thinking
> 
> @Moonbase59 could you create a bug issue about this?

**Comment by BusterNeece** [comment]
Fixed in latest rolling!

**Comment by Moonbase59** [comment]
Yup, confirm working again in Rolling Release #[0a46ef2](https://github.com/AzuraCast/AzuraCast/commit/0a46ef2a2f9d038774280e911e832da6b98486ff) (2023-07-09 14:55). Thanks.
