### ISSUE TITLE
Track or artist name too long

### ISSUE THREAD

**Issue by Siriusa77II** [AzuraCast/AzuraCast#641]
**Is your feature request related to a problem? Please describe.**
If the Track or artist name is too long it make a big paté of text and it's not very.

**Describe the solution you'd like**
after few character put three dot [...] and put the long version in alt="" or somethings like this.

**Additional context**
This issue is related to [this tweet. ](https://twitter.com/Sirius242/status/1013828801137201153)

**Comment by SlvrEagle23** [comment]
@Siriusa77II Fixed! For longer song titles, ellipsis will now automatically appear, and when you hover over the item, it will expand to show the longer title.
