### ISSUE TITLE
Can't play a playlist sequentially

### ISSUE THREAD

**Issue by ghost** [AzuraCast/AzuraCast#6411]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.18.5

### What happened?

First of all, I'd like to thank you for such a wonderful peace of software that AzuraCast is.

I first installed AzuraCast back when the version was 0.17.x, and back then when I needed to play a playlist sequentially, I would set the Song playback order as "Sequential" and uncheck the "Avoic Duplicate Artists/Titles" as shown in the image below
![Screenshot 2023-07-10 at 1 25 05 PM-xxx](https://github.com/AzuraCast/AzuraCast/assets/17083569/f170b1f5-012b-43ce-ae95-dc4108fc9252)

However, since updating to 0.18.x, I haven't been able to play songs sequentially. AutoDJ shuffles the songs within the playlist even though I specifically set the order to be sequential.

Am I missing something here? 

Thanks for your time in advance!

**Comment by BusterNeece** [comment]
@ahmedXabdeen Sequential playlists normally don't get shuffled by us at all. I think what you may be running into is a previous issue in AzuraCast where, if you set the playlists of a given file, it would remove it from the playlist, then add it right back to the playlist, which basically put it at the "end of the line". Obviously, this isn't what people wanted, especially in sequential playlists, and we rewrote that code a few weeks back, but it hasn't been shipped in a new stable channel release yet.

You can either update to the Rolling Release version, or just wait a bit for the next Stable channel release that incorporates it, to see if that fixes the issue.
