### ISSUE TITLE
Main page (Frontend) keeps on loading...

### ISSUE THREAD

**Issue by danielrodrigohub** [AzuraCast/AzuraCast#6414]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #7be5a94 (2023-07-10 13:56)

### What happened?

Hi dear Azuracast. I updated my azuracast release. Stations are ok, but after login the system freezes on **Loading...** on all stations and administration menus.

<img width="1440" alt="Screenshot 2023-07-10 at 10 49 24" src="https://github.com/AzuraCast/AzuraCast/assets/40525323/a7ad429e-b7b8-489a-99e8-0cc63a86e1c3">

**Comment by BusterNeece** [comment]
Right click the page, click "Inspect Element", then click the "Console" tab in the window that pops up. If you see anything in red, take a screenshot or copy/paste that here.

**Comment by danielrodrigohub** [comment]
`Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
DevTools failed to load source map: Could not load content for https://cp.streamchileno.cl/static/dist/lib/bootstrap/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

<img width="1440" alt="Screenshot 2023-07-10 at 11 03 13" src="https://github.com/AzuraCast/AzuraCast/assets/40525323/acee75d7-89a1-4a6a-92b0-2a7158da671b">

**Comment by danielrodrigohub** [comment]
Hi, I could log in into the server through IP (not full Domain). In fact, I'm using Cloudflare CDN, but the main problem may be this. 
Check it out!:

<img width="1440" alt="Screenshot 2023-07-11 at 02 01 52" src="https://github.com/AzuraCast/AzuraCast/assets/40525323/bfd02aa1-a2a6-4b4e-8464-64eb9074e85b">

**Comment by BusterNeece** [comment]
@danielrodrigohub With Cloudflare, do you have their Rocket CSS/JS thing turned on? That breaks our installations and you may want to turn it off.
