### ISSUE TITLE
When 2 jingles play in sequence, next song metadata not shown

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6415]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #7be5a94 (2023-07-10 13:56)

### What happened?

It sometimes (not often) happens that two jingles from different playlists are played in sequence, so that you get

Song 1 – Jingle 1 – Jingle 2 – Song 2 – Song 3

All this works nicely but the metadata for Song 2 is lost—Nowplaying shows Song 1’s metadata (and wrong timing) until Song 3 plays.

Both jingle playlists have "Hide Metadata from Listeners ("Jingle Mode")" checked.

**Comment by Moonbase59** [comment]
not stale

**Comment by RM-FM** [comment]
Same issue here but happens very frequently also with just one jingle. Apparently related to the length of the jingle. It could be related to crossfades that are longer or close to the duration of the jingle. Already took note of this every now and then an previous versions but it seems that it became worser with the recent versions.

**Comment by Moonbase59** [comment]
Yep. Running Rolling Release #[ccbddf0](https://github.com/AzuraCast/AzuraCast/commit/ccbddf08e7e5d71773328870e0f3edaa979ba9ab) (2023-12-14 21:44) currently and listening to my own station, it just happened a few times.

**Comment by Moonbase59** [comment]
Haven’t seen this in a while, and seen no others complain.
Closing.
