### ISSUE TITLE
Album Cover opens in new tab (window)

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#6417]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #96fb9d4 (2023-07-11 1:14)

### What happened?

When you click on album cover thumb it opens in a new tab. This happens on any page where a cover is shown (public player, song history, admin dashboard...)
No errors shown in browser.

**Comment by Moonbase59** [comment]
Confirm that.
