### ISSUE TITLE
Top 5 VOTE!

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#642]
It would be very nice if you can enable the top 5 at a station that you want. Users can vote for a song in a list, depending on the vote, go up or down a list, and start this list every 60 minutes. Once you have finished the top 5 you start with a normal playlist to give the time to vote. At the end of 60 minutes users can no longer vote and the top 5 starts

**Comment by SlvrEagle23** [comment]
Closing as duplicate of #79. Voting has already been requested, but represents a significant time investment in order to do it right and ensure that the results matter and can be easily managed/viewed by station administrators, which is why it hasn't been taken on yet.
