### ISSUE TITLE
Visual Cue Editor bug

### ISSUE THREAD

**Issue by rgriep** [AzuraCast/AzuraCast#6421]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#e6a8fd8 (2023-07-12 2:50)

### What happened?

Hi,

I found out by doing something in the Visual Cue Editor, like clicking on Cue In, de pop-up screen of the Cue Editor disappears.
It happens with all the buttons. Thank you for a solution in the next updates.

BTW, I am very happy with the fast responses of the developers of Azurcast. 

Best regards,
Robert

**Comment by ItsMitchh** [comment]
hi, 

can you provide a video or some screenshots of the issue your having?
