### ISSUE TITLE
Web player "Request Song" & "Song History" pages don’t yet use lightbox for album covers

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6424]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #e6a8fd8 (2023-07-12 2:50)

### What happened?

The public web player’s "Request Song" page still opens album covers in a new tab, not yet using the lightbox.

**Comment by LordHelmchen666** [comment]
Can confirm that. Does it work on "Song History" for you? Also still opens new tab on my install. Same Azuracast version.

**Comment by Moonbase59** [comment]
@LordHelmchen666 Thanks for the hint: I didn’t check Song History, and it indeed also still doesn’t use the lightbox.
