### ISSUE TITLE
Azuracast "web proxy" issue coupled with Cloudflare "argo" tunnel inside a Proxmox VM.

### ISSUE THREAD

**Issue by mindspies** [AzuraCast/AzuraCast#6428]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

Latest

### What happened?

I've been able in the past to use the "web proxy" function to use with a Cloudflare's "argo" tunnel. It was working well, but I recently had to change my server and reinstall my Azuracast instance. Now, whenever I enable the "web proxy" for my channels to stream on ports 80-443, I could only manage to play the first created channel (id-1). Other channels give a "The file you requested could not be found" (see attached picture) error when loading from browser, or the audio is muted when I play on the channel's public page. Note also that it makes that issue even if I'm not using Cloudflare tunnel, ex. accessing it with local address (192.168.x.x), or redirecting 80/443 to my LAN server (those ports are open from my internet provider).

I followed the "Cloudflare's guide", disabling cache for "domain.com/radio/* | domain.com/listen/* | domain.com/hls/*". I also tried to enable "CloudFlare (CF-Connecting-IP)" option in security tab. I also ensure "Rocker Loader" is not enable in Cloudflare for my domain.

Note that I also tried to reinstall Azuracast from scratch, and also switch from stable channel to rolling-release channel. But the issue persists.

Now I'm out of clue, cause I'd really like to enjoy the "web proxy" function coupled with Cloudflare to be able to "hide" my residential IP address from web traffic or listeners. Note that
![2023-07-13_17-02-52](https://github.com/AzuraCast/AzuraCast/assets/18006736/90b4ec0c-9ec2-47b4-8816-69d42f914a09)
 when I disable the web proxy and use the usual ports for radio streaming all my channels stream well.

I don't know if it's relevant but I use PROXMOX as hypervisor for my Azuracast instance, and before I was on a "real" computer. I also tried with Ubuntu Server 22.04, Debian 10 and still the same. I use the docker-compose installation for sure.

Thank you anyone trying to help me.

William

**Comment by mindspies** [comment]
OK I finally managed to make it work by installing Azuracast on Ubuntu 22.04 (Desktop version). I don't know why but for me on other Linux distributions I was having problem. Sorry for disturbing. William.

**Comment by BusterNeece** [comment]
I'm not sure really what would've caused this. It's possible you were running into some issues we had with Safari not playing stations correctly, and it just looked like it was something else causing it. In any case, glad you were able to fix it.
