### ISSUE TITLE
System settings completely reset after update

### ISSUE THREAD

**Issue by Dragondarn1993** [AzuraCast/AzuraCast#6429]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #79acb7a (2023-07-13 22:52)

### What happened?

After updating to the latest version of AzuraCast, my settings under System Settings were completely reset. After I set the settings and saved them again, they are applied, but after reloading the system settings page, everything is reset again.

**Comment by BusterNeece** [comment]
@Dragondarn1993 Minor bug on our part. Sorry about that! Should be fixed in the latest Rolling Release.
