### ISSUE TITLE
Blank Listeners Per Station after update Rolling Release #bc5877c

### ISSUE THREAD

**Issue by PeWe79** [AzuraCast/AzuraCast#6431]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#bc5877c

### What happened?

Hi,

Just got blank Listeners Per Station after update Rolling Release #bc5877c.

![Screenshot from 2023-07-14 21-21-19](https://github.com/AzuraCast/AzuraCast/assets/117633869/7a736499-1787-4d4a-81be-4cfbb6c145c9)

**Comment by PeWe79** [comment]
Update,
All Station Statistics just blank also.

![Screenshot from 2023-07-14 21-41-15](https://github.com/AzuraCast/AzuraCast/assets/117633869/2ed3a334-afbc-4dba-a640-55626e0a9224)
![Screenshot from 2023-07-14 21-41-31](https://github.com/AzuraCast/AzuraCast/assets/117633869/ed6779f0-40fe-4dfa-b387-ca213395355c)
![Screenshot from 2023-07-14 21-41-53](https://github.com/AzuraCast/AzuraCast/assets/117633869/e47cf30d-0eb5-4e45-b7c3-e490071663ad)
![Screenshot from 2023-07-14 21-42-09](https://github.com/AzuraCast/AzuraCast/assets/117633869/835b3ec2-ce12-4797-9bd7-9a6ddee50578)
![Screenshot from 2023-07-14 21-42-28](https://github.com/AzuraCast/AzuraCast/assets/117633869/fed971c8-3f53-4e01-9585-7b20acc009c0)
![Screenshot from 2023-07-14 21-42-42](https://github.com/AzuraCast/AzuraCast/assets/117633869/1e4e87c2-9075-4005-8a60-8cb9fa0db0dc)

**Comment by Blat4** [comment]
All blank from me as well, I really want to move away from rolling and get back to a stable release asap.

**Comment by PeWe79** [comment]
Hi @Blat4, when switch to stable release I can't login to my Azuracast server. From begining my Azuracast Docker runing on Rolling release.

**Comment by Blat4** [comment]
Hi @PeWe79 you need to insure the stable release is newer than the rolling release when switching, if the rolling in newer than the current stable you get the error you mention.

**Comment by PeWe79** [comment]
Still got blank on Station Statistics page after last Rolling Release #e566b30.

![Screenshot from 2023-07-15 16-56-18](https://github.com/AzuraCast/AzuraCast/assets/117633869/001b6b7b-6149-4ee0-ad40-5a39a5712ccc)

![Screenshot from 2023-07-15 16-56-56](https://github.com/AzuraCast/AzuraCast/assets/117633869/893fb9f4-e9a4-48b8-a8a9-2e766d3cea8c)

![Screenshot from 2023-07-15 16-57-35](https://github.com/AzuraCast/AzuraCast/assets/117633869/0fd97af5-4ed8-48a1-b0a0-bfda4b915af0)

![Screenshot from 2023-07-15 16-58-17](https://github.com/AzuraCast/AzuraCast/assets/117633869/46ba2aae-175a-45a3-984b-eb76891fa389)

![Screenshot from 2023-07-15 16-58-54](https://github.com/AzuraCast/AzuraCast/assets/117633869/e3de9466-8926-43f7-bf60-7562a9d5faea)
