### ISSUE TITLE
Player does not play on iOS devices

### ISSUE THREAD

**Issue by Eyecu** [AzuraCast/AzuraCast#6436]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #e566b30 (2023-07-15 3:54)

### What happened?

Player will not play on iOS devices iphone, ipad etc. When you tap the play button it shows playing but no sound is received and the system doesn't detect the person is connected ie not listed under the listener report, I've tested this on Safari, chrome and Opera on an iphone 13 pro max.
This happens with the player widget through iframe on a website and through the player on the public page
https://www.relay-radio.com
https://radio.relay-radio.com/public/relay-radio

Also trying to access the to feeds directly on and iOS device ie
https://radio.relay-radio.com/listen/relay-radio/radio.mp3
https://radio.relay-radio.com/listen/relay-radio/mobile

The links get changed and you get a 404 error page
https://radio.relay-radio.com//listen/relay%5C-radio/radio.mp3?&_ic2=1689450034673
https://radio.relay-radio.com//listen/relay%5C-radio/mobile?&_ic2=1689450059523

**Comment by Vaalyn** [comment]
I can replicate this issue when creating a station with a URL stub that includes a `-`.
There is most likely a bug in how we put that into the `proxy_set_header Host` setting in the stations nginx code for the proxy connection to Icecast 🤔

**Comment by Eyecu** [comment]
Has to be a recent change that did it, it worked until i did an update maybe 5 or 6 days ago.
