### ISSUE TITLE
Display Settings that are saved globally or by account

### ISSUE THREAD

**Issue by amavarick** [AzuraCast/AzuraCast#644]
**Is your feature request related to a problem? Please describe.**
There are various settings that when set within a session do not remain after leaving that particular screen.  Upon leaving the screen and browsing back to the screen, the settings must be reset.  This is not a high priority concern as it is easy enough to make the setting change but it is a different experience than I'm used to with other applications.  I'm not sure the best solution whether the setting is remembered globally or per account or some other solution.  Thank you so much for your time.

**Additional context**
Some of these "settings" that stand out to me include:
Playlist and music files count of items viewed
Playlist and music files columns selected to display
This also appears on the public page song request but... (I'm not sure if anything would need to be modified with the public page song request given that to implement would involve maybe some sort of cookie and tracking mechanism where the work wouldn't be worth the benefit?)

![image](https://user-images.githubusercontent.com/20918832/42247347-7ad64710-7eee-11e8-9623-afd984e7faa0.png)

![image](https://user-images.githubusercontent.com/20918832/42247395-aec659ca-7eee-11e8-9ecb-42946b0b371f.png)

![image](https://user-images.githubusercontent.com/20918832/42247577-6cbb4288-7eef-11e8-9f0d-6694168bc56e.png)

**Comment by SlvrEagle23** [comment]
@amavarick Definitely a valid point. This may be something that bootgrid (the library we use for these types of things) may include natively, but just needs to be turned on. If so, I'll look into it and make sure it's turned on.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38911/persist-bootgrid-settings-across-sessions
