### ISSUE TITLE
Rolling Release #fefb49c cross fade "normal mode" no work

### ISSUE THREAD

**Issue by radiobellissima** [AzuraCast/AzuraCast#6441]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #fefb49c 

### What happened?

Last night I upgraded my install to version Rolling Release #fefb49c and the normal mode crossfade doesn't work anymore. All edited mix points are no longer respected.

**Comment by radiobellissima** [comment]
Done, maybe a little improved but still not as perfect as before. With fadein 0 there is still a slight fade in.

**Comment by radiobellissima** [comment]
In normal mode and with all files edited it worked wonderfully well before the update. Unfortunately I can no longer go back to the previous version but I remember it said that I was 136 updates behind, perhaps this can help you understand what has been changed.

**Comment by radiobellissima** [comment]
UPDATE.
I noticed that all decimal values ​​(0.1-0.2-0.3 etc etc) are no longer saved. So could this be the cause?
![Test](https://github.com/AzuraCast/AzuraCast/assets/57127248/4903b554-1e5b-42dc-98c6-8e772f78a366)

**Comment by lotussutol** [comment]
I am on rolling release and I can't get crossfade to work at all. This has been the case since installing azuracast years ago. It is the main reason Azuracast is only been used to capture/send a stream and a backup player for when the stream goes down.

**Comment by lotussutol** [comment]
Should not have to set it manually on every song. That is unrealistic. Look at Plexamp Sweet Fades. You analyze your library and sets knows if the song is a fade or cold ending and does nice overlap or non overlap fades accordingly.

**Comment by radiobellissima** [comment]
@BusterNeece 
Still no solution to reset the editor that no longer accepts decimal values?

Thanks

**Comment by radiobellissima** [comment]
Thanks
