### ISSUE TITLE
After curl update on host machine Azuracast update won't work

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#6443]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #0ca7564 (2023-07-16 1:55) 

### What happened?

Today i updated packages on my host machine (Ubuntu 22.04.02 LTS). There was also an update to curl. After that i tried updating Azuracast but getting an error.
```
./docker.sh update-self
curl: (60) SSL: no alternative certificate subject name matches target host name 'raw.githubusercontent.com'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
Seems curl is more restrictive now with handling CA Certfile now.

**Comment by Vaalyn** [comment]
This is a bug with Ubuntu, not AzuraCast. See: https://bugs.launchpad.net/ubuntu/+source/curl/+bug/2028170

As such I'm closing this issue

**Comment by LordHelmchen666** [comment]
Thanks. Searched for informatins, but did not find that.
