### ISSUE TITLE
CSV import gives error "Unable to update. Call to a member function getIdRequired() on int"

### ISSUE THREAD

**Issue by zcraber** [AzuraCast/AzuraCast#6447]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #3afa6b6 (2023-07-23 6:13)

### What happened?

Getting this error while importing changes from CSV. 

**To Reproduce**:

1. Go to `Bulk Media Import/Export`.
2. Click `Export Media to CSV` and save the file.
3. Import the file and click `Import Changes from CSV`.

Here's a screen-recording of the issue:

![azuracast csv import error](https://github.com/AzuraCast/AzuraCast/assets/61133303/13f8fa56-ed35-45ff-bb04-407af5399136)

**Comment by BusterNeece** [comment]
@zcraber Thank you for the report! Should be fixed in the latest Rolling Release.
