### ISSUE TITLE
Playing Next stuck on same song

### ISSUE THREAD

**Issue by matthewunmuted** [AzuraCast/AzuraCast#6449]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.17.7 Stable

### What happened?

One of our client's stations has an issue with the 'Playing Next' information on their station - it is stuck on one track even after reloading the station configuration and restarting all broadcasting services.

This song was requested through the 'Request Song' feature on the public page. Is this a known issue, or is there anything we can do to remove this from the Playing Next box?

**Comment by BusterNeece** [comment]
@matthewunmuted It should usually clear up after a song or two...unless you have, say, Manual AutoDJ mode turned on, in which case the "Next Song" functionality isn't used, so it's possible in that scenario that it could get "stuck" on the last result it showed before switching to that.

**Comment by matthewunmuted** [comment]
Hi Buster,

Many thanks for the response. Unfortunately it still has not cleared up, and we have ensured that the station is not using Manual AutoDJ mode. Is there anything else we could try to remove this?
