### ISSUE TITLE
after the update, an error

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#645]
**docker 13
Centos 7.5**

web_1          | exec -- failed: No such file or directory
How to solve this error? Help please I got a working radio station.

> Creating azuracast_web_1 ... done
exec -- failed: No such file or directory

All I solved my problem, complete reinstallation, recovery from backups and subsequent updating.

**Comment by SlvrEagle23** [comment]
@susl16c I don't really have enough information here to be able to troubleshoot things further. It sounds like a problem with your local Docker setup, not something wrong with the images built on our end.

**Comment by SlvrEagle23** [comment]
This doesn't appear to have any items that I can really do anything about on my end, so I'm closing this issue.
