### ISSUE TITLE
Stream Authhash Azuracast Docker

### ISSUE THREAD

**Issue by freqq68** [AzuraCast/AzuraCast#6450]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.18.5 Stable • Docker • PHP 8.2

### What happened?

Hi ! 

Some problem with the Authhash of Shoutcast. I've modified the authhash beceause he won't work as expected. Unfortunately, If I change the authhash token, and after reboot, the OLD authhash appear ^^ 

I try to change it in the SSH but when I go to /var/azuracast and then /stations... there's no folder here... just a docker.sh 

I have try the ./docker.sh cli command but i'm a little bit lost right now... have you got a solution for the change that make effective ? 

(And don't tell me that I do to click on save or restart my internet box ehhehe)

Peace !

**Comment by freqq68** [comment]
this file : 
<img width="561" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/4027268/afb53e08-2e2f-4b97-9edc-0863e06bedbe">

**Comment by BusterNeece** [comment]
I can't reproduce this in the current version of AzuraCast's Rolling Release. It's a known thing that if you change things like the authhash, it requires restarting broadcasting on the station to rewrite the configuration (especially for Shoutcast, where we don't have the "soft reload" ability like Icecast).

**Comment by rolradio** [comment]
I suspect you enter the authhash directly into the shoutcast admin. (as it should with centovacast) After restart it indeed disappears.
Azuracast has provided this in the panel itself:
You must enter the authhash for shoutcast in the mount point of your radio in azuracast.

**Comment by freqq68** [comment]
> I can't reproduce this in the current version of AzuraCast's Rolling Release. It's a known thing that if you change things like the authhash, it requires restarting broadcasting on the station to rewrite the configuration (especially for Shoutcast, where we don't have the "soft reload" ability like Icecast).

Yes, i've restarded so many times, inlcued the VM ^^ but it's rewrite the old everytime :P 



> I suspect you enter the authhash directly into the shoutcast admin. (as it should with centovacast) After restart it indeed disappears. Azuracast has provided this in the panel itself: You must enter the authhash for shoutcast in the mount point of your radio in azuracast.

Hum, interesting, like : youradioblablablabaguette.mp3/authash=authash_id ?

Thank's for your comments ! :)

**Comment by BusterNeece** [comment]
@freqq68 As people mentioned, if you set the authhash from the Shoutcast administration panel, that doesn't save it within AzuraCast. If you reset or reload, it will overwrite that configuration. Instead, you should go to `Broadcasting`, then `Mount Points`, then set the stream's authhash there, where it will be saved.

**Comment by freqq68** [comment]
No, i've been done all the solutions here and nothing works.

Except for the link I don't have tested and I do know how it work's 

best :)
