### ISSUE TITLE
User Login GUI Gone

### ISSUE THREAD

**Issue by Blat4** [AzuraCast/AzuraCast#6453]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

? Cant see anything

### What happened?

So I ran this morning Rolling Release update and now I can no longer see any of the UI. Everything seems to be running apart from the login page and UI pages are all blank?

**Comment by BusterNeece** [comment]
@Blat4 If you right click the page and click "Inspect Element" (or hit F12), then click the "Console" tab, do you see any errors in red?

**Comment by Blat4** [comment]
Hi I see no errors in red, But now in google chrome I get HTTP 500 error, but in Safari no errors just all UI pages are blank.

**Comment by Blat4** [comment]
The stations are all working it would seem here one https://147.148.94.112:8000/missionuk | just no UI anymore

**Comment by BusterNeece** [comment]
@Blat4 Thank you for the report. We found the issue and have updated our images to fix it. Try updating again via the SSH update instructions and things should be fixed.

**Comment by Blat4** [comment]
Thank you, I updated via SSH and all is working now.
