### ISSUE TITLE
Listener Map Pins Missing / Broken Image 

### ISSUE THREAD

**Issue by Blat4** [AzuraCast/AzuraCast#6454]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #0b1c295 (2023-07-25 12:35) 

### What happened?

Nothing major, but I see the listener map pins are now missing after todays updates.

![Screenshot 2023-07-25 at 15 58 16](https://github.com/AzuraCast/AzuraCast/assets/106454822/d0f0fa56-b739-43d1-8cec-187b3f6b8c5b)

**Comment by Vaalyn** [comment]
Seems like it can't find the referenced images:
<img width="708" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/81d78d7a-ee72-4105-ad98-9cd7e9eb21c2">

**Comment by BusterNeece** [comment]
Thank you for the report! Fixed in the latest Rolling Release that's deploying right now and will be available in a few minutes.
