### ISSUE TITLE
Get Dot on Listeners Per Station Charts

### ISSUE THREAD

**Issue by PeWe79** [AzuraCast/AzuraCast#6458]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #32919e5 (2023-07-28 14:15) • Docker • PHP 8.2

### What happened?

Listeners Per Station Average & Unique Listeners Chart just got Dot & not Chart data.

![Screenshot from 2023-07-29 02-11-00](https://github.com/AzuraCast/AzuraCast/assets/117633869/57ff040d-91c7-447d-b892-e5d8e4b5323b)

![Screenshot from 2023-07-29 02-11-05](https://github.com/AzuraCast/AzuraCast/assets/117633869/e47b4c53-a497-4c8c-85ed-ffafbffaaeae)

**Comment by lotussutol** [comment]
same here. rolling release and updaed.

**Comment by PeWe79** [comment]
Just update video. Look at video from dashboard Listeners Per Station Average.

[Screencast from 30-07-23 03:43:58.webm](https://github.com/AzuraCast/AzuraCast/assets/117633869/ddc891da-cc9b-42cd-beb1-b6e8c71fddc1)
