### ISSUE TITLE
Azuracast/Liquidsoap crossfade is horrible

### ISSUE THREAD

**Issue by lotussutol** [AzuraCast/AzuraCast#6459]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #40e60e5 (2023-07-29 2:37) • Docker • PHP 8.2

### What happened?

I have been using Azuracast for years with other sources feeding a stream to Azuracast. Every time I update Azuracast I spend about a week trying to get the crossfade to work to see if it has been fixed so that I can use autoDJ. It sucks and makes it impossible for me to utilize autodj.
I have tried every setting from smartfade to normal from 0 to 5 seconds. There is no consistency no matter what setting you use. Sometimes a tiny crossfade sometimes a second of silence between songs.

I see you can set points on every song...unrealistic when you have thousands of songs.

crossfade is my only complaint/hatred of Azuracast. Look at plexamp...rip off what they do. their smart fade analyzes the song and you set the crossfade time to like 3 seconds. If there is a fade on the song it starts the fade when the DB drop to a certain point and then does a 3 second fade to the next song. If the song has a cold ending it starts the next song right on the cold ending. Very nice fade system that every audio player program should be doing.

**Comment by BusterNeece** [comment]
> Look at plexamp...rip off what they do

Nothing makes an open-source maintainer's life better than someone telling them to look at a closed-source, proprietary piece of software and just do what they do

**Comment by lotussutol** [comment]
> > Look at plexamp...rip off what they do
> 
> Nothing makes an open-source maintainer's life better than someone telling them to look at a closed-source, proprietary piece of software and just do what they do

I was expecting this reply. :)
I pointed out the plexamp xover as I have used pretty much every software there is for digital audio and there's is the only one that I have seen that can compete with a human doing a standard fade/xover. open-source or proprietary. If I had an open source project I would be looking at all competing software for the best ideas and would not get butt hurt if someone pointed out some part of the software was better somewhere else even if that part was in a paid software.
If I didn't like Azuracast I would not be using it for....I think almost 4 years now.

**Comment by BusterNeece** [comment]
> If I had an open source project I would be looking at all competing software for the best ideas and would not get butt hurt if someone pointed out some part of the software was better somewhere else even if that part was in a paid software.

If I had an open-source project, I would ban someone for suggesting the lead maintainer was just getting "butt hurt" with the low quality and inappropriate tone of your feedback.

Oh wait, I do!
