### ISSUE TITLE
PlayList History maxium?!

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#646]
I was wondering if you can make a playlist divided into hours, or if azuracast limits the number of playlists!

Example: 11:00 - 12:00
List of the music that has been played from 11 to 12. Is there a similar thing?
@SlvrEagle23

**Comment by SlvrEagle23** [comment]
@Ilario42 There is no limit to the number of playlists you can set up. You could definitely theoretically set up one playlist for every hour of the day if you wanted.

**Comment by Ilario42** [comment]
@SlvrEagle23 
I did not mean the playlist that is set by azuracasdt to send the songs, but the playlist of the cqnzoni already played.
Here is a screen to make you understand:
![image](https://user-images.githubusercontent.com/22561729/44206105-f71f0780-a158-11e8-886c-f9b6164a5a57.png)

**Comment by inetactief** [comment]
Nice playlist, how you do that?

**Comment by SlvrEagle23** [comment]
@Ilario42 I don't understand the nature of your question. What are you wanting to do that AzuraCast's scheduled playlists won't currently do?

**Comment by Ilario42** [comment]
@SlvrEagle23 I'm talking about the story, about the songs already played. Azuracast leaves only 6, plus the one that will be played later. can you have more than 6 story?

**Comment by SlvrEagle23** [comment]
@Ilario42 This was just added as a resolution of issue #700. You can now configure the number of songs shown in the "Song History" section of the public page, which also changes the number of songs shown in that section in the API responses. The valid range is currently between zero (disabled) and 15.
