### ISSUE TITLE
Rolling #9289d63: Streamer/DJ artwork: Suggest lightbox use, wrong image on Edit

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6464]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #9289d63 (2023-07-31 16:19)

### What happened?

- In the Streamer/DJ Accounts List, the lightbox isn’t yet used—clicking on a DJ’s image opens a new page. I suggest using the lightbox here, too.

- After selecting a custom PNG image for a _new_ DJ, it will work, and the small image is shown in the list, but when clicking on _Edit_, the station album artwork is shown on the _Artwork_ tab instead. This worked before (all my already existing DJ images are still shown).

![Auswahl_237](https://github.com/AzuraCast/AzuraCast/assets/3706922/747cdbf5-9fcd-4811-b4ed-2582a3febb61)

![Auswahl_238](https://github.com/AzuraCast/AzuraCast/assets/3706922/617d5ccf-85fb-4858-842a-8f3b3a575fae)

**Comment by BusterNeece** [comment]
@Moonbase59 Well, the first part should be, the second wasn't done yet. May want to make that a separate issue to keep with the "one issue per issue" thing.

**Comment by Moonbase59** [comment]
Yup, you’re right. Then again, I retested with Rolling Release #[5466af5](https://github.com/AzuraCast/AzuraCast/commit/5466af54dcc183f622ddb79edabeb874743f4d9e) (2023-08-02 14:29) and couldn’t make it happen again. Tried existing DJs as well as newly created ones and all worked so far.
