### ISSUE TITLE
Issues with Playing Commercials Playlist Sequentially

### ISSUE THREAD

**Issue by leveex** [AzuraCast/AzuraCast#6466]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #43eecb6 (2023-08-01 12:02) • Docker • PHP 8.2 

### What happened?

I am currently experiencing a problem with my commercials playlist not playing in the correct order. I have set it up in Jingle mode, configured it to play Sequentially, set it to play once per hour, and enabled the 'Merge playlist to play as a single track' option. However, instead of playing the entire playlist from beginning to end, the system is sometimes interrupting the sequence by playing other tracks in between.

The expected behaviour I would like is for the system to play the opener jingle, all the commercials, and then the closing jingle without any interruptions.

I have already tried restarting my AzuraCast server and ensuring that I am running the latest version of the software, but this has not resolved the issue.

Could you please advise on any potential solutions or troubleshooting steps I could take to resolve this problem? I appreciate any help you can provide.

**Comment by leveex** [comment]
2023/08/03 11:11:04 [lang:3] API nextsong - Response (200): annotate:title="reklame break open",duration="4.00",song_id="9103950bc8f48058258e03b9de18c24c",media_id="2862",playlist_id="48",jingle_mode="true":media:pp break/reklame_break_open.mp3
2023/08/03 11:11:04 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
2023/08/03 11:11:04 [lang:3]   "song_id": "ead44b19003a9f4c5053fe6c7384319d",
2023/08/03 11:11:04 [lang:3]   "playlist_id": "7",
2023/08/03 11:11:04 [lang:3]   "media_id": "3880"
2023/08/03 11:11:04 [lang:3] }
2023/08/03 11:11:04 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/radio_101/media/pp break/reklame_break_open.mp3": {audio=pcm(stereo)}
2023/08/03 11:11:04 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/radio_101/media/pp break/reklame_break_open.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/08/03 11:11:04 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/radio_101/media/pp break/reklame_break_open.mp3": {audio=pcm(stereo)}
2023/08/03 11:11:04 [lang:3] API feedback - Response (200): true
[mp3float @ 0x7f492be1cf00] Could not update timestamps for discarded samples.
2023/08/03 11:11:08 [decoder:2] Decoding "/var/azuracast/stations/radio_101/media/xSW_R101/sw_r101_02.mp3" ended: Ffmpeg_decoder.End_of_file.
2023/08/03 11:11:09 [next_song:3] Prepared "/var/azuracast/stations/radio_101/media/pp break/reklame_break_open.mp3" (RID 1173).
[mp3float @ 0x7f492be1ca00] Could not update timestamps for skipped samples.
2023/08/03 11:11:09 [cue_next_song:3] Cueing in...
2023/08/03 11:11:09 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2023/08/03 11:11:09 [cross:3] Analysis: -28.891009dB / -20.960232dB (2.98s / 2.98s)
2023/08/03 11:11:09 [cross.smart:3] new >= old + margin, old >= medium and new <= high.
2023/08/03 11:11:09 [cross.smart:3] New source is significantly louder than old one.
2023/08/03 11:11:09 [cross.smart:3] Transition: crossed, fade-out.
2023/08/03 11:11:09 [source.982:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:09 [audio.add.739:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:09 [cross_after.1108:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:09 [buffer.2216:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:09 [fade_out.282:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:09 [on_end.141:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:09 [on_track.390:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:09 [on_metadata.194:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:09 [on_track.389:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:09 [cross_before.1108:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:09 [buffer.2215:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:09 [fade_out.281:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:09 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
2023/08/03 11:11:09 [lang:3]   "song_id": "9103950bc8f48058258e03b9de18c24c",
2023/08/03 11:11:09 [lang:3]   "playlist_id": "48",
2023/08/03 11:11:09 [lang:3]   "media_id": "2862"
2023/08/03 11:11:09 [lang:3] }
2023/08/03 11:11:09 [lang:3] API nextsong - Response (200): annotate:title="c4 x radio spot",artist="citroen",duration="20.00",song_id="f553e1a3a4335bbd820b22ea82bbcfb2",media_id="7053",playlist_id="48",jingle_mode="true":media:RC kolovoz/citroen_-_c4_x_radio_spot.mp3
2023/08/03 11:11:09 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/radio_101/media/RC kolovoz/citroen_-_c4_x_radio_spot.mp3": {audio=pcm(stereo)}
2023/08/03 11:11:09 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/radio_101/media/RC kolovoz/citroen_-_c4_x_radio_spot.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/08/03 11:11:09 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/radio_101/media/RC kolovoz/citroen_-_c4_x_radio_spot.mp3": {audio=pcm(stereo)}
2023/08/03 11:11:09 [lang:3] API feedback - Response (200): true
[mp3float @ 0x7f492be1ca00] Could not update timestamps for discarded samples.
2023/08/03 11:11:12 [decoder:2] Decoding "/var/azuracast/stations/radio_101/media/pp break/reklame_break_open.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3float @ 0x7f492be1d400] 2023/08/03 11:11:12 [next_song:3] Prepared "/var/azuracast/stations/radio_101/media/RC kolovoz/citroen_-_c4_x_radio_spot.mp3" (RID 1174).
Could not update timestamps for skipped samples.
2023/08/03 11:11:12 [cue_next_song:3] Cueing in...
2023/08/03 11:11:12 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2023/08/03 11:11:12 [cross:3] Analysis: -37.245789dB / -10.651476dB (1.09s / 1.11s)
2023/08/03 11:11:12 [cross.smart:3] No transition: using default.
2023/08/03 11:11:12 [cross_before.1109:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:12 [buffer.2217:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:12 [cross_after.1109:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:12 [buffer.2218:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:12 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
2023/08/03 11:11:12 [lang:3]   "song_id": "4e8dfc1d3767a9a2254975e7023ac617",
2023/08/03 11:11:12 [lang:3]   "playlist_id": "16",
2023/08/03 11:11:12 [lang:3]   "media_id": "5455"
2023/08/03 11:11:12 [lang:3] }
2023/08/03 11:11:12 [lang:3] API nextsong - Response (200): annotate:title="dont stop til you get enough",artist="michael jackson",duration="351.00",song_id="32f814c59e582eda3bdddd742d814356",media_id="5542",playlist_id="16":media:REGULAR/michael_jackson_-_dont_stop_til_you_get_enough.mp3
2023/08/03 11:11:12 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/radio_101/media/REGULAR/michael_jackson_-_dont_stop_til_you_get_enough.mp3": {audio=pcm(stereo)}
2023/08/03 11:11:12 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/radio_101/media/REGULAR/michael_jackson_-_dont_stop_til_you_get_enough.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/08/03 11:11:12 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/radio_101/media/REGULAR/michael_jackson_-_dont_stop_til_you_get_enough.mp3": {audio=pcm(stereo)}
2023/08/03 11:11:12 [lang:3] API feedback - Response (200): true
2023/08/03 11:11:13 [metadata_map.3:3] Inserting missing metadata.
2023/08/03 11:11:13 [metadata_map.5:3] Inserting missing metadata.
2023/08/03 11:11:13 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
2023/08/03 11:11:13 [lang:3]   "song_id": "f553e1a3a4335bbd820b22ea82bbcfb2",
2023/08/03 11:11:13 [lang:3]   "playlist_id": "48",
2023/08/03 11:11:13 [lang:3]   "media_id": "7053"
2023/08/03 11:11:13 [lang:3] }
2023/08/03 11:11:13 [lang:3] API feedback - Response (200): true
[mp3float @ 0x7f492be1d400] Could not update timestamps for discarded samples.
2023/08/03 11:11:30 [decoder:2] Decoding "/var/azuracast/stations/radio_101/media/RC kolovoz/citroen_-_c4_x_radio_spot.mp3" ended: Ffmpeg_decoder.End_of_file.
2023/08/03 11:11:30 [next_song:3] Prepared "/var/azuracast/stations/radio_101/media/REGULAR/michael_jackson_-_dont_stop_til_you_get_enough.mp3" (RID 1175).
[mp3float @ 0x7f492be1cf00] Could not update timestamps for skipped samples.
2023/08/03 11:11:30 [cue_next_song:3] Cueing in...
2023/08/03 11:11:30 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2023/08/03 11:11:30 [cross:3] Analysis: -10.516195dB / -22.228691dB (3.00s / 3.00s)
2023/08/03 11:11:30 [cross.smart:3] No transition: using default.
2023/08/03 11:11:30 [cross_before.1110:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:30 [buffer.2219:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:30 [cross_after.1110:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:30 [buffer.2220:3] Content type is {audio=pcm(stereo)}.
2023/08/03 11:11:30 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: { "artist": "", "title": "" }
2023/08/03 11:11:30 [lang:3] API nextsong - Response (200): annotate:title="Our House",artist="Madness",duration="196.00",song_id="a36d8d3cc6a72ab450cf2a5eb06ca136",media_id="5388",playlist_id="16":media:REGULAR/madness_-_our_house.mp3
2023/08/03 11:11:30 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/radio_101/media/REGULAR/madness_-_our_house.mp3": {audio=pcm(stereo)}
2023/08/03 11:11:30 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/radio_101/media/REGULAR/madness_-_our_house.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/08/03 11:11:30 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/radio_101/media/REGULAR/madness_-_our_house.mp3": {audio=pcm(stereo)}
2023/08/03 11:11:30 [lang:3] API feedback - Response (200): true
2023/08/03 11:11:33 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
2023/08/03 11:11:33 [lang:3]   "song_id": "32f814c59e582eda3bdddd742d814356",
2023/08/03 11:11:33 [lang:3]   "playlist_id": "16",
2023/08/03 11:11:33 [lang:3]   "media_id": "5542"
2023/08/03 11:11:33 [lang:3] }
2023/08/03 11:11:33 [lang:3] API feedback - Response (200): true

**Comment by leveex** [comment]
Am I really the only one experiencing this issue? I've tried all possible and impossible solutions, but all to no avail.

**Comment by BusterNeece** [comment]
Please be patient. It may not be that you are the only one experiencing the issue, but issues with our AutoDJ scheduler are just immensely hard for us to diagnose and resolve. It's one of the few sections of the app where we hit the very real limitations of having an incredibly small team working on this software (usually 1-2 people) while having tens of thousands of stations depending on us. If we had more developers putting more eyes on that same code, a lot would likely be resolved at this point.

One way you can help diagnose things is by going to the Queue page under the Broadcasting sidebar menu. This page will let you see upcoming tracks, and you can also click "Logs" to see the specific decision-making process we went through to play a single song. This can either tell you what is misconfigured or help narrow down the bug for us.
