### ISSUE TITLE
Setup without additional components

### ISSUE THREAD

**Issue by pacija** [AzuraCast/AzuraCast#647]
Hi,

I'd like to try AzuraCast, but none of the two supported setup possibilities - docker or install.sh on Ubuntu - suit my needs. This is because I already have separate hosts for liquidsoap and icecast, and would like to have only web component from AzuraCast on a http server, preferrably apache and not nginx.

Thank you in advance for any advice.

**Comment by SlvrEagle23** [comment]
@pacija The core concept of AzuraCast is to be an "all-in-one" environment that includes the necessary broadcast, database, web server, cache, etc. software preconfigured and ready to go with very little effort required to get a station up and running.

If there are portions of this that you don't intend to use (i.e. Liquidsoap and the radio stack), the rest of the installed software will still work without any issues, and you can always just remove the unneeded components after the initial setup. Alternatively, you can fork the AzuraCast project and modify the Ansible deployment playbooks (located in `/util/ansible`) to remove any unnecessary installations and avoid them altogether.

This is even easier to accomplish via the Docker environment, where you can simply not spin up the `stations` service at all, avoiding the entire stack of Liquidsoap/Icecast/Shoutcast and yet still having all of the necessary components to operate the system. I would highly recommend this approach.

At its core, AzuraCast is indeed just a standard PHP web application, and really any suitably configured PHP setup, including Apache+ModPHP, should run it without any issues, provided you have a MariaDB, Redis and InfluxDB instance available for it to connect to.

I'm closing this issue as this counts as an advanced use-case that I don't necessarily intend to broadly support in the distributed version of the software, and it's a problem that can be solved either through customization of the existing codebase or through fairly minor changes to the Docker deployment.
