### ISSUE TITLE
Issue with the appearance of various tables not keeping within fixed card width on screens with mobile dimensions, since converting UI components to Vue.

### ISSUE THREAD

**Issue by radioguy0** [AzuraCast/AzuraCast#6475]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Applicable to all versions containing the latest app-wide Vue updates

### What happened?

The tables on Station Overview, Streams, Public Pages, Music Files, Playlists, Podcasts, Streamer/DJ Accounts, Web Hooks, Listeners, Song Requests, Song Playback Timeline, Custom Fallback File, Upcoming Song Queue pages no longer respecting the fixed width container boundaries while viewed on vertical screens (e.g. mobile) since being updated as Vue components. 

### Relevant log output

```shell
N/A
```

**Comment by Moonbase59** [comment]
Verified that, Rolling Release #[092c7c2](https://github.com/AzuraCast/AzuraCast/commit/092c7c270846dd937834baa554eefe25ad2b4476) (2023-08-03 8:34). I typically use my browser 1/2 to 2/3 screen width and also see some of these, the streamer page for instance:

![Streamer-DJ Accounts – Mozilla Firefox_001](https://github.com/AzuraCast/AzuraCast/assets/3706922/8d83e43e-ad04-4cea-8083-14229bbf355c)

**Comment by Moonbase59** [comment]
Plus, we have no menu on half-width and mobile/tablet browsers:

![Arbeitsfläche 1_015](https://github.com/AzuraCast/AzuraCast/assets/3706922/14a30e6f-e3f6-4852-9fda-b0497d02ee4c)

![AzuraCast Tablet - No Menu](https://github.com/AzuraCast/AzuraCast/assets/3706922/0a065e81-bc1a-49bf-9229-589ad4484605)

**Comment by BusterNeece** [comment]
@Moonbase59 We just changed the threshold for which the menu collapses into the little hamburger icon up at the top to the left of the "AzuraCast" icon. I can tell from your screenshots, though, that it's the wrong color on the light theme, which would certainly make it easy to miss.

**Comment by Moonbase59** [comment]
@BusterNeece Darn, you’re right! I totally missed the grey hamburger button at top left! Btw, the Lenovo D330 is a 800x1280 pixel (or 1280x800) Windows 10 tablet, and I used Edge for testing.

**Comment by Moonbase59** [comment]
Can’t find anything wrong anymore, Rolling Release #[a90dde7](https://github.com/AzuraCast/AzuraCast/commit/a90dde779dfeb64d6ccd1fe8ee68cfc7f21a0302) (2023-08-04 9:29).

Light hamburger shows fine, tables too wide have a horizontal scrollbar so one gets at the buttons—all good.

![Streamer-DJ Accounts – Mozilla Firefox_003](https://github.com/AzuraCast/AzuraCast/assets/3706922/50d5eda0-73a4-411d-bd8f-dd67c681930c)

![Streamer-DJ Accounts – Mozilla Firefox_004](https://github.com/AzuraCast/AzuraCast/assets/3706922/03e9a4ab-c051-4ef4-9af4-2665d41f4814)

**Comment by radioguy0** [comment]
Unfortunately I am still able to replicate this issue on portrait orientation for iOS and Android mobile devices post-implementation. 

Although it's not affecting the visibility of the different Ui elements, you still have to scroll the full pages (not just inside the cards) horizontally, e.g. when you want to view the Manage button on Station Overview on the main dashboard. 

The same can also be said for the Station Profile cards for Streams and Public Pages cards, among others. 

Some of the page tables are now fixed but not all of those listed in the initial description.

**Comment by Moonbase59** [comment]
@radioguy0 Just trying to emulate some real small screen devices in my Firefox, and I think I see what you mean. Is that a real use case, needing to administer a station on a small phone?

![Dashboard – Mozilla Firefox_001](https://github.com/AzuraCast/AzuraCast/assets/3706922/49de35d6-2d6c-489d-8625-b19e433596e9)

![Dashboard – Mozilla Firefox_002](https://github.com/AzuraCast/AzuraCast/assets/3706922/fb559f03-4dc0-44d0-993f-8f43536ccae3)

- Could you give us some actual screen dimensions of devices affected, for better testing?
- It’s often not easy displaying table rows of data on such small screens—what would you expect to happen? Each card having a horizontal scrollbar?

@BusterNeece If this is something to be followed up upon, maybe reopen?
I wonder if some general ("card-wise") `overflow` handling would help, on small screen sizes.

**Comment by radioguy0** [comment]
Thanks for getting back on this @Moonbase59 

Yes, it would be a daily driver use case while on the move. OS and Docker based AzuraCast updates are also run remotely from the same device via a terminal app. For example, that way you wouldn't have to carry a laptop around if you're travelling to a busy location. 

Ideally the horizontal scrolling option would be best for such small screens while keeping the inner elements contained within the dimensions of their cards, preventing dead space around the outside cards as a result of the table running outside the box. 

Horizontal scrolling used to work as expected in this way across all pages prior to converting over to Vue, it seems that something in the code change process may have regressed a commit that previously fixed it. 

Hope this context helps and thanks all!
