### ISSUE TITLE
Rolling #092c7c2: some playlists not yet using new layout, lacking # songs

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6476]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #092c7c2 (2023-08-03 8:34)

### What happened?

Seems the playlist view isn’t yet fully adapted to the new layout: # songs missing on most of them, list looks "jumpy". "default" and remote stream playlists look different than the others:

![Playlists – Mozilla Firefox_002](https://github.com/AzuraCast/AzuraCast/assets/3706922/1c81e672-1f14-45ae-8ce7-2e3fc8c731b7)

![Playlists – Mozilla Firefox_003](https://github.com/AzuraCast/AzuraCast/assets/3706922/7184c725-319c-475e-8539-e2809d2845e1)

**Comment by BusterNeece** [comment]
@Moonbase59 I fixed something not necessarily related to this, but it might've caused that mis-layout issue. See if updating fixes it.

**Comment by Moonbase59** [comment]
Yup, confirm fixed in Rolling Release #[a90dde7](https://github.com/AzuraCast/AzuraCast/commit/a90dde779dfeb64d6ccd1fe8ee68cfc7f21a0302) (2023-08-04 9:29). And thanks for bringing the # songs back ;-)
