### ISSUE TITLE
Table sorting: A killer feature! But indicators like ⏷ or ⏶ missing.

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6482]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #a90dde7 (2023-08-04 9:29)

### What happened?

By pure accident, I found that **tables can be sorted by clicking on the table headers**—having about 157k songs, this an absolute **killer feature** in the "Music Files" tables!

![Music Files – Mozilla Firefox_003](https://github.com/AzuraCast/AzuraCast/assets/3706922/9f340e6e-21ca-42e3-a30e-b6df234e3180)

It would be extremely helpful to have a little up- or downward pointing triangle right next to the currently sorted column header to indicate which column is currently sorted, and whether it’s ascending or descending. This is how spreadsheets and file managers do it.

I’d suggest using something like

- U+23F7 ⏷ for "sorted by this column, in ascending order", and
- U+23F6 ⏶ for "sorted by this column, in descending order".

If anyhow possible, this should sort _the whole table_, not just what can be seen on a paginated view. And we would have a **super killer feature**.

Do you think that possible?

(Sorry for "misusing" the issues again, but things like this can simply not be described in the feature suggest pages…)

**Comment by BusterNeece** [comment]
The little up/down arrow thing is definitely a leftover Bootstrap 5 migration problem. I'm looking into how to do this elegantly with styling.

It _should_ be sending the "sort" parameter to the remote API to sort the actual response, not just what's shown, though.

**Comment by Moonbase59** [comment]
Sounds wonderful, looking forward to it!

**Comment by Moonbase59** [comment]
Confirm working in Rolling Release #[6fde92d](https://github.com/AzuraCast/AzuraCast/commit/6fde92db8980285b22fee8de2d8bdeeaa75c3320) (2023-08-11 22:58)—thanks a lot, this is really helpful!

And yes, it _does_ sort the complete list, not only what’s on the current page ;-)
