### ISSUE TITLE
Auto DJ Repeating songs.

### ISSUE THREAD

**Issue by joeyboli** [AzuraCast/AzuraCast#6488]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#85214e6

### What happened?

Auto DJ Repeated the same song in 30 mins, also noticed it repeated the same song twice continously during the day.

LiquidSoap Logs : https://anonfiles.com/h8eeq778zc/logs_txt

**Comment by Vaalyn** [comment]
Could you point out which song/s or at what time that was?
I don't really want to read through 24h of logs just to find the right place in the logs 😓 

Please also post how your playlists are configured.
