### ISSUE TITLE
# Songs shortcut to Music Files on Playlist uses the wrong URL

### ISSUE THREAD

**Issue by MarkWasley** [AzuraCast/AzuraCast#6490]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #631dda9 (2023-08-08 17:23)

### What happened?

The shortcut to the music files on the Playlists page is using the wrong URL. In a recent update to `Playlists.vue`, the `filesUrl` was changed to a `getStationApiUrl`, when it should remain a stations page URL. This means the browser navigates to the API endpoint, not the music files filtered search.

**Comment by BusterNeece** [comment]
Fixed in the latest Rolling Release. Thank you!

**Comment by Moonbase59** [comment]
Confirm working in Rolling Release #[6fde92d](https://github.com/AzuraCast/AzuraCast/commit/6fde92db8980285b22fee8de2d8bdeeaa75c3320) (2023-08-11 22:58).
