### ISSUE TITLE
Stereo tool upload issue

### ISSUE THREAD

**Issue by XPA1** [AzuraCast/AzuraCast#6491]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

Unkown

### What happened?

I'm trying to install stereo tool but it says cannot upload file

### Relevant log output

```shell
None
```

**Comment by BusterNeece** [comment]
@XPA1 Are you really using the Ansible version of the application, or did you not fill out the GitHub issue questions correctly?

If so, we haven't tested the last few versions on Ansible and we aren't confident they will work at all with the latest versions. The Ansible installer is community-maintained now and not officially supported by us, and given the lack of any pull requests or activity on it, it doesn't appear the community is very interested in maintaining it.

**Comment by XPA1** [comment]
Nvm. Got my friend to help
