### ISSUE TITLE
Shoutcast Fails To Install - Identical Issue to #5273

### ISSUE THREAD

**Issue by Blat4** [AzuraCast/AzuraCast#6494]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.18.5 Stable

### What happened?

So to sum up the issues quickly I had an error within the database, with a fresh install being the easiest method of fixing the problem. Ok I did this.

I decided to continue with Rolling release as I had before. I then proceeded to install Shoutcast, to which it failed in the same manor as raised in Issue #5273 by [Dezodev]

I'm now on Stable Release 0.18.5, thinking this may help, and I'll stay on this release channel until the next update. However the same problem with Shoutcast persists.

**Comment by BusterNeece** [comment]
It's possible they've released a new version that changes how the file is supplied. Otherwise, the usual cause of that is a mismatch between your server's architecture and the version of the file downloaded.

**Comment by Blat4** [comment]
Hi Buster, Ok so I had a little play and I did the following below

SSH into my docker installation root@server:/var/lib/docker/volumes/azuracast_shoutcast2_install/_data

Then I found "sc_serv.tar.gz", So I just ran "tar -xf sc_serv.tar.gz"

Now it shows the following in azurcast below


![Screenshot 2023-08-11 at 21 53 57](https://github.com/AzuraCast/AzuraCast/assets/106454822/344638cb-622e-4e09-910d-ce0fb66cb27d)

**Comment by Blat4** [comment]
Ok So I've tested it and all is working with Shoutcast, However I'd still be interested in any feed back regarding what happened and my approach to the fix.
