### ISSUE TITLE
Any chance for a full API?

### ISSUE THREAD

**Issue by mrcatman** [AzuraCast/AzuraCast#650]
Now the API is incomplete and allows only to get some information about the station and restart the services. Is it possible to make a complete API for managing playlists and uploading tracks from outside?

**Comment by SlvrEagle23** [comment]
@mrcatman This is absolutely a long-term goal. The idea is to make the application be able to be, essentially, "headless", with API calls that can perform any function the web application can perform. This will allow for third-party applications to be created that can manage AzuraCast instances with only an API key.

**Comment by mrcatman** [comment]
In any case, thanks, I'll try to implement it on my own.
