### ISSUE TITLE
RR #6fde92d: Swagger API link broken

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6500]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

I get a 404 when trying to access the Swagger API at `https://example.com/api`.
(Installation URL replaced by "example.com".)

**Comment by BusterNeece** [comment]
Can't reproduce: https://demo.azuracast.com/api works fine for me.

**Comment by Moonbase59** [comment]
Hmm, odd. I’ll retest after updating to the next RR. :-)

**Comment by Moonbase59** [comment]
Confirm working in Rolling Release #[43784b3](https://github.com/AzuraCast/AzuraCast/commit/43784b378d4f792cd10e2b010a56412593512827) (2023-08-12 21:22).

Maybe the error sat 2 ft before the screen, after all… ;-)
