### ISSUE TITLE
We must catchup xx.xx seconds back again!

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#6501]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #6fde92d (2023-08-11 22:58)

### What happened?

Was on Stable release 18.5 and all was fine but reverted to current rolling release (#6fde92d - 2023-08-11 22:58) to take advantage of new features.  Minutes after switching stream became intermittent; having deal with the issue before I immediately disabled Replay Gain and restarted broadcasting which solved it. 
My question is; if replay gain works fine in 18.5 stable why doesn't it work on a newer rolling release?

*Was my impression last time that the LS team had solved this...

### Relevant log output

```shell
2023/08/12 08:52:50 [source:4] Source dummy.112 gets down.
2023/08/12 08:52:50 [source:4] Source source.replaygain.compute.112 gets down.
2023/08/12 08:52:50 [source:4] Source request.once.112 gets down.
2023/08/12 08:52:50 [file.replaygain.112:3] Computed replay gain -0.77 dB for "/var/azuracast/stations/radio_des_festivals/media/Country Franco/Danny Boudreau - Mes legendes.mp3" (time: 396.03666091 s).
2023/08/12 08:52:50 [request:2] Time limit exceeded by 372.00 secs!
2023/08/12 08:52:50 [playlist_country_franco:4] Queued 1 requests
2023/08/12 08:52:50 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
2023/08/12 08:52:50 [lang:3]   "song_id": "8242df90983e8e4d3ab942d037e89e79",
2023/08/12 08:52:50 [lang:3]   "playlist_id": "1",
2023/08/12 08:52:50 [lang:3]   "media_id": "9542"
2023/08/12 08:52:50 [lang:3] }
2023/08/12 08:52:50 [lang:3] API feedback - Response (200): true
2023/08/12 08:52:51 [clock.main:2] We must catchup 54.03 seconds!
2023/08/12 08:52:52 [clock.main:2] We must catchup 55.26 seconds!
2023/08/12 08:52:53 [clock.main:2] We must catchup 55.67 seconds!
2023/08/12 08:52:54 [clock.main:2] We must catchup 56.06 seconds!
2023/08/12 08:52:56 [clock.main:2] We must catchup 57.22 seconds!
2023/08/12 08:52:57 [clock.main:2] We must catchup 58.32 seconds!
2023/08/12 08:52:58 [clock.main:2] We must catchup 59.39 seconds!
2023/08/12 08:52:59 [clock.main:2] Too much latency! Resetting active sources...
2023/08/12 08:52:59 [lang:3] API djoff - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/djoff' with body: { "user": "" }
2023/08/12 08:53:00 [lang:3] API djoff - Response (200): true
2023/08/12 08:53:00 [local_1:3] Closing connection...
2023/08/12 08:53:00 [local_2:3] Closing connection...
2023/08/12 08:53:00 [local_2:3] Connecting mount sid#2 for @127.0.0.1...
2023/08/12 08:53:00 [local_2:3] Connection setup was successful.
2023/08/12 08:53:00 [local_1:3] Connecting mount sid#1 for @127.0.0.1...
2023/08/12 08:53:00 [local_1:3] Connection setup was successful.
2023/08/12 08:53:03 [clock.main:2] We must catchup 1.22 seconds!
2023/08/12 08:53:05 [clock.main:2] We must catchup 2.16 seconds!
2023/08/12 08:53:06 [clock.main:2] We must catchup 3.64 seconds!
2023/08/12 08:53:07 [clock.main:2] We must catchup 4.67 seconds!
```

**Comment by BusterNeece** [comment]
@SpeedyCharly As with any other Liquidsoap issue, this is probably best suited as an issue on Liquidsoap's GitHub so they can diagnose and fix it on their end, at which point we can update our dependencies.

> My question is; if replay gain works fine in 18.5 stable why doesn't it work on a newer rolling release?

We have updated to use Liquidsoap 2.2.x in our Rolling Release channel, which we don't currently use in our Stable channel. There were a huge number of changes in 2.2.x, and they actually spent a lot of time on improving issues like the one you're reporting, so I'm not sure what specific circumstances are causing it.

**Comment by SpeedyCharly** [comment]
Thanks Buster, will transfer this to LS forum
