### ISSUE TITLE
RR #29091c4: Custom fields can’t be selected for display on Music Files table

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6504]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #29091c4 (2023-08-14 4:26)

### What happened?

I’m almost positive that worked before… Custom fields can’t be selected anymore for display in the _Media → Music Files_ table.

I have:

![Auswahl_254](https://github.com/AzuraCast/AzuraCast/assets/3706922/d5f17563-cfd8-452f-807b-13f8360235e0)

These can be selected on the Song Request modal just fine:

![Auswahl_252](https://github.com/AzuraCast/AzuraCast/assets/3706922/173e6d5e-182f-449f-ba76-58cf32dda605)

But not on the Music Files:

![Auswahl_253](https://github.com/AzuraCast/AzuraCast/assets/3706922/b42aecc0-b172-4338-8100-ef83eb8c3213)

**Comment by Moonbase59** [comment]
Correction: Must be some caching or SPA issue, I think.

- If you come from Playlist view and select a "# songs" link, you get the media files view "playlist: xxx" in which custom fields _can’t_ be  selected.

- Then click on the "Home" link to display all, and they _still_ can’t be selected.

- Press F5 to refresh the page, and the custom fields reappear in the list for selection.

Would be nice if custom fields could always be selected, independent of being in a _normal_, _special_ or _playlist_ search.

**Comment by BusterNeece** [comment]
@Moonbase59 Yeah you found a bonafide bug on this one...if you navigate to a new route, but the component stays the same, it _doesn't_ populate the props. While the file browser still mostly works despite this, it would absolutely destroy several other component pages. Definitely needed fixing. Should be fixed in Rolling.

**Comment by Moonbase59** [comment]
Good that we found and you fixed it early, then. ;-)

Confirm working in Rolling Release #[8b8836a](https://github.com/AzuraCast/AzuraCast/commit/8b8836a182c52815a4f0fcfeeda294fe7c0ceeda) (2023-08-14 17:39).
