### ISSUE TITLE
Files stuck on 'File processing'

### ISSUE THREAD

**Issue by matthewunmuted** [AzuraCast/AzuraCast#6508]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.7 Stable

### What happened?

One of our client's stations has an issue where files that are uploaded either via the panel or via FTP do not complete processing - they simply stay stuck on 'File Processing'.

We have checked routine sync tasks and reloaded all station configuration, as well as restarting broadcasting processes, however this issue persists. Screenshot is attached.

Please advise? Thanks in advance.
![Screenshot 2023-08-15 162909](https://github.com/AzuraCast/AzuraCast/assets/111743235/53b1844a-d826-4cac-88d4-f6828283e065)

**Comment by BusterNeece** [comment]
@matthewunmuted Is the php-worker doing okay? That likes to stop sometimes for no good reason. In recent Rolling versions we added better logging so you can follow specifically what the php-worker is doing and see if it's throwing any errors.

**Comment by matthewunmuted** [comment]
Hi Buster,

Many thanks for the response. php-worker seems to be doing fine, we've restarted it a few times but this doesn't seem to have solved the issue. Would updating to a more recent version potentially resolve this issue?

It's strange that this issue seems specific to this station, and files are processing normally on other stations on the same server

**Comment by Moonbase59** [comment]
I have a (very) few files also stuck in processing. This can be due to illegal formats; malicious people sometimes try to disguise viruses as `.mp3` files. I saw 3 of those in a supposed-to-be-free MP3 sound effects collection, but AzuraCast—in my case—marked these as "unprocessable files".

You might still want to check your client’s file for viruses, illegal Xing VBR header, Lyrics3, or invalid tags. Who knows what AzuraCast migt _not_ be able to detect…

**Comment by matthewunmuted** [comment]
Hi Moonbase,

Many thanks for your response. We have tested this with a large number of known good MP3 files with correct metadata and formatting, and MP3 Diags reports no issues with all of them - at this point we are completely stuck!

**Comment by BusterNeece** [comment]
@matthewunmuted Did you also select the files and hit "Reprocess" under the "More" dropdown? That should at least trigger a new message for the queue to process, and that'll let you look at the logs to see how it processes that file, as it should do so immediately after queueing it for reprocessing. I'm not sure if the 0.17.x versions have that feature yet, though.
