### ISSUE TITLE
Decimal values for Advanced: Control Song Playback & Crossfade Duration

### ISSUE THREAD

**Issue by anducampu** [AzuraCast/AzuraCast#651]
Hi. I want to have a more precise way to crossfade the tracks. Is it possible to add decimal values to Crossfade Duration, Fade In, Fade Out, Cue In & Cue Out? I think liquidsoap supports that.

Thank you

**Comment by SlvrEagle23** [comment]
@anducampu Definitely possible! Will look into it shortly. :)

**Comment by anducampu** [comment]
Great! Thank you

**Comment by SlvrEagle23** [comment]
@anducampu I've looked into this a little further and it appears the system already _does_ support decimal values for the custom song crossfade and cue in/out points. You just have to specify a number with a decimal point, otherwise it formats it as an integer when displaying it.

**Comment by anducampu** [comment]
Hi. Thank you for the reply. It works for small values (I get no errors) but when I want to edit a 1 hour mix file I get this error:

-----
500
An exception occurred while executing 'UPDATE station_media SET album = ?, lyrics = ?, isrc = ?, fade_in = ?, fade_out = ?, cue_in = ?, cue_out = ? WHERE id = ?' with params ["", "", "", 0.1, 3735.8, 9.7, 3739.3, 16]: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'fade_out' at row 1
AbstractMySQLDriver.php : 122
-----

Also please allow decimal values for the default cross-fade setting in the station's profile.

Thank you

**Comment by anducampu** [comment]
Thank you for your answer. Can you add decimal value also for the default Crossfade Duration in Profile?

**Comment by SlvrEagle23** [comment]
@anducampu Implemented! Thank you for your patience.
