### ISSUE TITLE
RR #5baaf95: Media Files should not show the trash bin or other hidden files

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6514]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #5baaf95 (2023-08-15 3:09)

### What happened?

Seems _Media Files_ shows the Linux trash bin and other hidden files (starting with a dot). Since they’re supposed to be _hidden_, AzuraCast shouldn’t show them.

![Nite Radio – Mozilla Firefox_006](https://github.com/AzuraCast/AzuraCast/assets/3706922/0c921876-54fa-4812-8e69-481b6c7e9cd7)

**Comment by Moonbase59** [comment]
Thanks, confirm working in Rolling Release #[26b79e7](https://github.com/AzuraCast/AzuraCast/commit/26b79e7509ccf72b9d2ea7d6ae5e1e7448bb5e40) (2023-08-20 8:03).

**Comment by Moonbase59** [comment]
Just realized, in Rolling Release #[97f0226](https://github.com/AzuraCast/AzuraCast/commit/97f02266ce2a36ea4966d950fde8df905c060ef7) (2023-08-24 10:05), some hidden folders are still shown, like Syncthing’s `.stfolder`:

![Nite Radio – Mozilla Firefox_017](https://github.com/AzuraCast/AzuraCast/assets/3706922/d74b5527-0f28-4eb2-95fa-bcb60c1686ec)

**Comment by BusterNeece** [comment]
Can't repro this either: creating a directory named `.stfolder` is expressly ignored in all media views.

**Comment by BusterNeece** [comment]
So the Syncthing `.stfolder` is a bit of a weird one, it's apparently a _file_ rather than a directory, yet it's listed as a directory by our system. I can see how it would be baffling our exclusion system as a result. Will have to look into it specifically.

**Comment by Moonbase59** [comment]
Hm, the one in the `Tagged` folder should be a directory. So says `file` and `ls`:

![matthias@e6510: ~-Musik-Tagged_001](https://github.com/AzuraCast/AzuraCast/assets/3706922/3ad25161-b52a-46d1-b52d-af649ee880b7)

**Comment by Moonbase59** [comment]
Seems to work fine now, in Rolling Release #[47a4c00](https://github.com/AzuraCast/AzuraCast/commit/47a4c00df83acc4e9190c8d9910d55f9f1242ba5) (2023-08-29 12:02), thanks. I put some hidden folders and files into subfolders, and none of these appeared. :+1:
