### ISSUE TITLE
Various UI bugs

### ISSUE THREAD

**Issue by MarkWasley** [AzuraCast/AzuraCast#6515]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #f71a9b5 (2023-08-18 2:12)

### What happened?

Just a few UI bugs I've just noticed in the application.

The styling of the inline player in the top bar of the dashboard should not change when the theme switched. It should keep the normal light (white) theming, as used on the public pages. Buttons and _time-display_ should be white.

Enable/Disable buttons on the station profile shouldn't have "Delete" as the confirm button.

Search doesn't work on Upcoming Song Queue.

**Comment by Vaalyn** [comment]
### Dev Note:

## Inline player styling

Should keep the icons white on the light theme too, see reference screenshots for comparison:

Light theme:
<img width="457" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/e265ccf6-2899-40da-8734-afa99bb9b77c">

Dark theme:
<img width="446" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/8395716e-482c-436d-8ec7-c86db1e44f6e">

@MarkWasley not sure what you mean with `time-display` though, could you clarify?

## Confirm button naming

<img width="1428" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/3461a4c9-bd2d-4ed7-92cf-b0e75a5d02e5">

## Search doesn't work on Upcoming Song Queue.

As far as I could see this was already not working for quite a while, even before the UI rework.

On a station that is currently still on `Rolling Release #a28072d (2023-06-01 7:17)` when I enter a specific word that is only in one of the songs shown on the `Upcoming Song Queue` page it does a quick reload of the table but still shows all songs.

Looks like the backend doesn't apply the search string to the query.

**Comment by MarkWasley** [comment]
@Vaalyn Thanks for your input and screenshots.

> @MarkWasley not sure what you mean with `time-display` though, could you clarify?

This is the class for the `currentTimeText` and `durationText`, as in the snippet below. It appears when you play a track from Music Files.

https://github.com/AzuraCast/AzuraCast/blob/fe0c672c2ce7d93988b79b974f41701165251726/frontend/vue/components/InlinePlayer.vue#L17-L33

**Comment by thackmaster** [comment]
As part of these UI glitches, I've found that all of my Embeded players no longer respect the "allowtransparency=true" field. Most (not all) of mine are in dark mode, and they display the default dark color instead of being transparent. The light mode ones don't seem to be affected by it.
<img width="501" alt="Screenshot 2023-08-19 at 08 29 55" src="https://github.com/AzuraCast/AzuraCast/assets/73045785/d28ea716-b39a-4da1-9beb-87b0dd659726">
![Untitled](https://github.com/AzuraCast/AzuraCast/assets/73045785/5c4a57c1-3d5e-41ed-ac22-a98b1c4fcfe8)

**Comment by BusterNeece** [comment]
Several fixes pushing up to Remote for the reported issues.

**Comment by MarkWasley** [comment]
@BusterNeece Thank you for your work! All issues have been fixed in Rolling Release #bbd92f6.

**Comment by Moonbase59** [comment]
Yup, can also confirm for Rolling Release #[26b79e7](https://github.com/AzuraCast/AzuraCast/commit/26b79e7509ccf72b9d2ea7d6ae5e1e7448bb5e40) (2023-08-20 8:03)—thanks!
