### ISSUE TITLE
Edit Mount Point Advance in v0.19.0 is missing for custom xml

### ISSUE THREAD

**Issue by gunsar** [AzuraCast/AzuraCast#6519]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.0

### What happened?

in this latest version there is only to edit Mount Point URL Advanced
whereas previous versions can still add `<http-headers>` and other custom code for the xml mountpoint. accidentally deleted or moved to another menu?

**Comment by Moonbase59** [comment]
Oops. Confirm that for Rolling Release #[0362de0](https://github.com/AzuraCast/AzuraCast/commit/0362de0386c439e9bc4e3c5638e8a7ffb5e70b44) (2023-08-17 18:09).

I _use_ custom headers, so hopefully this will be back soon…

**Comment by Moonbase59** [comment]
Custom headers are back, hooray! ;-)

Confirm working in Rolling Release #[26b79e7](https://github.com/AzuraCast/AzuraCast/commit/26b79e7509ccf72b9d2ea7d6ae5e1e7448bb5e40) (2023-08-20 8:03).
