### ISSUE TITLE
Problem with music files in playlist (add with directory not working)

### ISSUE THREAD

**Issue by azug** [AzuraCast/AzuraCast#652]
**Installation method**
Traditional

**Host OS (for Docker installations)**
Ubuntu 18.04 LTS

**Describe the bug**
Problem with add songs to playlist when have directories

**To Reproduce**
1. Music FIles tab
2. Create directory "test"
3. Enter to directory "test"
4. Upload .mp3 file test.mp3
5. Go to Music Files tab (now i see "test" directory which includes test.mp3).
6. click checkbox on "test" directory
7. Add to playlist "default"
8. Go to playlists (and see default playlist)
9. Enter to default playlist
10. See that you have test.mp3 but:
lenght: 0:00
size: null bytes
modified: Jan 1, 1970 1:00 AM
11. try to download this file and see:

error |  
-- | --
code | 404
msg | "File or Directory Not Found"

and log from nginx:
188.137.29.254 - - [08/Jul/2018:13:50:53 +0200] "GET /station/1/files/download?file=test.mp3 HTTP/1.1" 404 69 "https://panel.streamcast.pl/station
/1/files" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"

What is important? file have link to: /station/1/files/download?file=test.mp3
without "test" directory.

When I go to Music Files tab and try to download the link looks different: /station/1/files/download?file=test/test.mp3

which is different and contain "test" directory after "file".

I tried to do the same in docker configuration and problem is not appear.

If I enter to directory in music tab files and add file to playlist it is ok and show correctly but if I try to add directory with .mp3 file, the link looks like broken, and playlist also.

**Expected behavior**
Fix :)

**Screenshots**

**Comment by SlvrEagle23** [comment]
@azug Thank you for the detailed report. I was able to track it down to one minor item that was part of a very recent refactor. It should be fixed now. :)

**Comment by SlvrEagle23** [comment]
@azug As a note, you will have to re-add those files to the playlists if they were added via selecting their parent folder while the error was happening.

**Comment by azug** [comment]
Heelo,
Thanks a lot!! :) now it is working correctly.
One more time, thanks, great work, great app! :)

Regards,
Arkadiusz Zug
