### ISSUE TITLE
Fallback disappeared 

### ISSUE THREAD

**Issue by heyDaino** [AzuraCast/AzuraCast#6521]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.0

### What happened?

 The fallback that takes you from one mountpoint to another is missing. Example: When accessing "/stream2", you get redirected to "/stream1" instead. The fallback is currently only working for the auto DJ and could send a file. In previous versions, it was available inside mountpoint settings.

**Comment by Vaalyn** [comment]
### Dev Note:
For reference, it's the `Fallback Mount` input field that's missing in the `Edit Mount` modal:

## Before:

<img width="833" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/5f842113-b517-4157-9d35-837bb8e946e7">

## After:

<img width="878" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/49819bde-8c79-4545-8652-c906841921fb">

**Comment by BusterNeece** [comment]
Fixed in the latest Rolling Release commit. We'll likely do a few bug fixes and then push a minor stable release.

Folks, this is why nobody being on the Rolling Release is bad for all of us! We need testers!

**Comment by Moonbase59** [comment]
Hee, hee :-)

Confirm working in Rolling Release #[26b79e7](https://github.com/AzuraCast/AzuraCast/commit/26b79e7509ccf72b9d2ea7d6ae5e1e7448bb5e40) (2023-08-20 8:03).
