### ISSUE TITLE
Issue with Audio Glitch on iOS after AzuraCast 0.19.0 Update

### ISSUE THREAD

**Issue by heyDaino** [AzuraCast/AzuraCast#6522]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

0.19.0

### What happened?

After updating to AzuraCast version 0.19.0, I've noticed an issue with listening apps like TuneIn or MyTuner (only on iOS). There's an audio glitch at the start, where the audio repeats for about 1 second. This happens frequently, though not always. The problem emerged after updating to version 0.19.0 of AzuraCast. I haven't made any custom configuration

**Comment by heyDaino** [comment]
** the problem only occurs with streaming addresses https://URL/listen/namestation/radio.mp3

**Comment by wegGehamstert** [comment]
Did the problem got fixed?

**Comment by heyDaino** [comment]
No, the problem has not been fixed. Recently, I tried reinstalling Azuracast from scratch (without the backup) and manually recreating the instances, but the issue still persists. I also have a second VPS with a clean Azuracast installation, and the problem is present there as well. I previously mentioned that the problem only occurs with streaming, using URLs like https://url/listen/namestation/radio.mp3 as an example. However, it's not limited to that. The streaming audio starts very quickly (also in 4G network) unlike many other radio stations, but then it creates this audio repetition effect in the first second.

**Comment by wegGehamstert** [comment]
Did you (@heyDaino) used for the reinstall from scratch also the version 0.19.0?

**Comment by heyDaino** [comment]
Sure

**Comment by wegGehamstert** [comment]
> Sure

Could you maybe test it again with the latest rolling release?
I had similar issues on the version 0.19, in the newest rolling release this dosen't happen anymore

**Comment by lindenwade** [comment]
I get the same issue on my own iOS App which is developed by an external provider. It plays a second or so of audio, then jumps back, sometimes twice before it continues to play. 

I setup a new VPS to test the stream with another Icecast service and the issue stopped.

I have also noticed that it doesn't re-connect the stream as it used to when you lose a mobile data connection.

**Comment by mdrxy** [comment]
We're facing a similar issue, but only occasionally. v0.19.1 Stable. Unclear what's going on.

**Comment by abradio-ai** [comment]
The issue is still prevalent after updating to v0.19.1 Stable.

**Comment by abradio-ai** [comment]
Still having this issue after the latest update to v0.19.4 Stable.

**Comment by pearsond32** [comment]
I have the same issue. Looking at the age of this report, it's unlikely to be fixed any time soon...

**Comment by abradio-ai** [comment]
> I have the same issue. Looking at the age of this report, it's unlikely to be fixed any time soon...

Be patient...

**Comment by abradio-ai** [comment]
Update: It does not seem to do this using SHOUTcast DNAS, so I have switched my server to that.
