### ISSUE TITLE
Database migration error during update to v0.19.0 from previous rolling release version

### ISSUE THREAD

**Issue by Fridgemagnet** [AzuraCast/AzuraCast#6525]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #90f9129 (2023-08-19 17:16)

### What happened?

Rollback successful after failed update.
Stated "Current AzuraCast Version" might be incorrect/bugged.

### Relevant log output

```shell
[ERROR] Database migration failed: An exception occurred while executing a query: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'cache_items' already exists
```

**Comment by BusterNeece** [comment]
I've updated the migration in the latest Rolling Release so it will be a bit more tolerant of errors like this one.

**Comment by Fridgemagnet** [comment]
> I've updated the migration in the latest Rolling Release so it will be a bit more tolerant of errors like this one.

Thank you very much, Buster.

**Comment by Fridgemagnet** [comment]
Updating to "Rolling Release #[26b79e7](https://github.com/AzuraCast/AzuraCast/commit/26b79e7509ccf72b9d2ea7d6ae5e1e7448bb5e40) (2023-08-20 8:03)" worked flawlessly without any errors.
