### ISSUE TITLE
Error 500 after logging in

### ISSUE THREAD

**Issue by techbp** [AzuraCast/AzuraCast#653]
**Installation method**
Installation method: Traditional
OS: Ubuntu16.04

**Describe the bug**
Suddenly, I'm getting this error:
 "500 
An exception occurred while executing 'SELECT t0.id AS id_1, t0.station_id AS station_id_2, t0.name AS name_3, t0.is_default AS is_default_4, t0.is_public AS is_public_5, t0.fallback_mount AS fallback_mount_6, t0.relay_url AS relay_url_7, t0.authhash AS authhash_8, t0.enable_autodj AS enable_autodj_9, t0.autodj_format AS autodj_format_10, t0.autodj_bitrate AS autodj_bitrate_11, t0.custom_listen_url AS custom_listen_url_12, t0.frontend_config AS frontend_config_13, t0.remote_type AS remote_type_14, t0.remote_url AS remote_url_15, t0.remote_mount AS remote_mount_16, t0.remote_source_username AS remote_source_username_17, t0.remote_source_password AS remote_source_password_18, t0.station_id AS station_id_19 FROM station_mounts t0 WHERE t0.station_id = ? AND t0.is_default = ? LIMIT 1' with params [3, 1]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.custom_listen_url' in 'field list'
AbstractMySQLDriver.php : "

- That is showing in my dashboard. I already updated using ./update.sh --full 
but no luck.

**Comment by SlvrEagle23** [comment]
@techbp Try manually running
```
php /var/azuracast/www/util/cli.php migrations:migrate
```
...as it's likely that this isn't running correctly and that's what's causing your problem.

**Comment by techbp** [comment]
@SlvrEagle23 you save my life! Thank you so much :-)

**Comment by robnoordt** [comment]
Error 500 after logging in
 The solution given here dows nog solved the problem on mi raspberry pi Ubuntu16 installed. Is there more to do fixing the problem?!!!

**Comment by CodeSteele** [comment]
@robnoordt are you also getting the following error?

```
Unknown column 't0.custom_listen_url' in 'field list'
AbstractMySQLDriver.php : "
```

**Comment by robnoordt** [comment]
I attached some files so you can sea wat is happening.
[After login into Azuracast.docx](https://github.com/AzuraCast/AzuraCast/files/2542953/After.login.into.Azuracast.docx)
[install.sh eroor500.docx](https://github.com/AzuraCast/AzuraCast/files/2542957/install.sh.eroor500.docx)
[update.sh eroor500.docx](https://github.com/AzuraCast/AzuraCast/files/2542958/update.sh.eroor500.docx)

**Comment by CodeSteele** [comment]
@robnoordt is this a fresh install? If so can you run `./uninstall.sh` then `./install.sh` again?

The error connecting to port 8086 suggests that there is a problem connecting to the InfluxDB server, so I'd check for things like firewalls and that the service is up and running.

**Comment by robnoordt** [comment]
It is a fresch install indeed. I go to try your option and let you know...Thanks!

**Comment by robnoordt** [comment]
root@ubuntu:/var/azuracast/www# ./uninstall.sh
-bash: ./uninstall.sh: Permission denied
root@ubuntu:/var/azuracast/www#

**Comment by SlvrEagle23** [comment]
@robnoordt Your issue is related to being on an ARM processor. ARM is currently unsupported on AzuraCast until updated versions of upstream software are made available. See issue #332.

**Comment by robnoordt** [comment]
So I understand it is not posible at the moment to install it on a Raspberry pi 3? am I right?

**Comment by SlvrEagle23** [comment]
@robnoordt It is currently not, due to the Raspberry Pi line using ARM processors.

**Comment by robnoordt** [comment]
Ok, thanks for your answers! Do you know if there are raspberry's witsch wel supporting it? Or is it not posible at all?

**Comment by SlvrEagle23** [comment]
@robnoordt Currently, almost all of the small single-board computers (SBCs) use ARM processors, so they won't work with AzuraCast. You would need an x86 one, like the Lattepanda.

We definitely plan to support ARM processors when we can.

**Comment by robnoordt** [comment]
the Lattepanda? that is a ardino system? Not a rasberry pi? If a ardino, can Azuracast on that system? Wher can I find a manual how to install and setup? sorry if I am asking stupide questions, i am just a hob'by based...

**Comment by robnoordt** [comment]
Ok, on this page:
https://github.com/AzuraCast/AzuraCast/releases
Pre-release
 0.9.0-2018.10
 39ee5fa

Re-enabled support for ARMHF (Scaleway C1 and Raspberry Pi 3) hosts by re-enabling legacy IceCast 2 and LiquidSoap installation for these architectures.
