### ISSUE TITLE
RR #26b79e7: Move files doesn’t move in spite of success message

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6532]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #26b79e7 (2023-08-20 8:03)

### What happened?

**EDIT: Some corrections, after further testing.**

On Rolling Release #[26b79e7](https://github.com/AzuraCast/AzuraCast/commit/26b79e7509ccf72b9d2ea7d6ae5e1e7448bb5e40) (2023-08-20 8:03), I was just trying to move a video file for my video stream from my "videostream/videos" to the "videostream/videos-off-rotation" folder in order to temporarily disable it. Doing atomic moves is the method of choice, much better than deleting and later re-uploading multi-gigabyte files.

I used AzuraCast’s "Music Files" for that, since I was just to lazy to fire up my FileZilla, and noticed the following:

- I was really happy to see that it _should_ have worked—a green badge appeared shortly, telling me "Files moved. bla bla successfully.".
- _But_ the file still showed up in the original place in the "videostream/videos" media folder. (Verified with FileZilla.) So it wasn’t actually moved.
- Apparently all my MKV (Matroska) videos must be stuck in "File processing" _for weeks_. I just didn’t check. Not that I need that, but file is file and maybe someone would like to play a video file’s audio track… Maybe videos should be automatically excluded from processing—or "just work".
- Moving the video in FileZilla worked, and the change was immediately reflected in AzuraCast’s "Music Files"..
- Then I thought "well, maybe it can’t move things not yet processed", and tried to move a MP3 file to another directory—totally forgetting that the source music files tree is actually a read-only file system so no one can corrupt my "sacred" music. (The target was r/w, being just a normal folder on the station.).
- AzuraCast _still_ told me "File moved. xxx successfully." (green badge). But of course it wasn’t moved.
- When I tried to verify that situation using FileZilla, it promptly errored—which is correct.
- So some error checking is missing.
- I then tried to move a (processed) PNG image from "videostream/videos" to "videostream/images-off-rotation" which also gave me the green "Files moved" badge but it wasn’t moved. (Move ok using FileZilla.)
- I then created a new folder "test2" and moved some files from the "test" folder to "test2" and back. That worked (green badge, mivle moved, update shown in Music Files).
- Looks like the Move (maybe others, too?) needs some error checking.

### Relevant log output

![Screenshot 2023-08-21 at 09-18-05 Nite Radio](https://github.com/AzuraCast/AzuraCast/assets/3706922/3135c3cf-db6b-4a8e-8d42-b892493a0d49)

![Screenshot 2023-08-21 at 09-26-37 Nite Radio](https://github.com/AzuraCast/AzuraCast/assets/3706922/a75fbec8-89b5-4db6-99ba-5a20a2cc37ae)

**Comment by Moonbase59** [comment]
To be sure, just cross-checked from inside the AzuraCast Docker container:

```bash
cd ~/stations/niteradio/media/videostream/videos/
mv Nite\ Radio\ -\ Sendeplan.png ../images-off-rotation/
```
and
```bash
cd ~/stations/niteradio/media/videostream/
mv "videos/The Magic Of The Great Dorset Steam Fair At Night (2016).mkv" videos-off-rotation/
```
work without a glitch (and are reflected in AzuraCast’s "Music Files").

All files are owned by UID/GID 1000 and have 644 permission, so no rights problem either.

**Comment by BusterNeece** [comment]
Can't seem to repro this one either. Moving works flawlessly for me on local dev. Not sure if this is specific to your filesystem setup.

**Comment by Moonbase59** [comment]
Tested again again using Rolling Release #[d2ca5eb](https://github.com/AzuraCast/AzuraCast/commit/d2ca5eb22a09096756e78498145d147fb2e82685) (2023-08-22 1:05): Same behaviour, no error message but green "success" badge.

**Comment by Moonbase59** [comment]
Shoo, bot!

**Comment by Moonbase59** [comment]
Retested using Rolling Release #[ccbddf0](https://github.com/AzuraCast/AzuraCast/commit/ccbddf08e7e5d71773328870e0f3edaa979ba9ab) (2023-12-14 21:44). It still shows the green badge and _doesn’t work_.

And you can’t imagine how I hate having to remember to check my issues every few days and fight the stale bot… grrr. Otherwise, I’m very patient and keep waiting, in the hope the old issues will also be fixed…

**Comment by BusterNeece** [comment]
I mean, it's every 60 days, but there's just too few of us to keep up with the issues unless we have something like a bot helping us. If I can confirm an issue, I flag it as "in progress" so I know it's something I can do something about, but with a lot of these, they're hard for me to reproduce.

**Comment by Moonbase59** [comment]
Yeah, I know. And I _do_ see the need of running the stale bot for a repo as active as this. For me, it’s just having to keep up issues that still disturb me every few days, since the time between becoming stale and auto-closing is rather short.

No offence, it’s just sometimes a sudden "bot hate" coming up, lol.

Maybe some of these "longtime" issues will resolve themselves by upstream updates, or we can fix them.

**Comment by Moonbase59** [comment]
Yep, appreciated, I mean it. Guess we both still have something on our lists, but your project—your priorities. ;-) Thanks!

Did you see my extra findings re the iframe height thingy? Guess we were on the right track after all, care to have a look again, or shall we postpone that?
