### ISSUE TITLE
RR #26b79e7: MP4 videos (!) can apparently be played as audio in "Music Files" but show a totally wrong "cover image"

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6533]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #26b79e7 (2023-08-20 8:03)

### What happened?

I wonder if this is intended or an oversight: `*.mp4` files (usually _videos_) can apparently be "played" (the audio plays) in "Music Files". I didn’t try to play them in the station queue, for fear it might break something.

In the music files list, these show up with a "cover image" that seems to be taken randomly (or maybe from the first image type file, relying on inode numbers?), _if_ there are any JPG or PNG files in the folder, too.

Stumbled over this while working in my video stream playout directory, which can handle _both_ video and image files to play in the station’s video stream.

Interesting: File processing for MP4 files reads artist and title I have tagged in the video file (only title was set: "Solar System + Universe") and even _replaygain values_, should I run those videos through my `loudgain` (yes, it _can_ replaygain video formats). Hee, hee!

![Screenshot 2023-08-21 at 10-25-32 Nite Radio](https://github.com/AzuraCast/AzuraCast/assets/3706922/ba9d2a3e-facb-4201-99ff-5764714c3854)

Then again, here’s the "cover" it suggests (`Nite Radio - Sendeplan.png`)—which would absolutely confuse any user and has _nothing_ to do with the video.

![Screenshot 2023-08-21 at 10-27-40 Nite Radio](https://github.com/AzuraCast/AzuraCast/assets/3706922/91889762-a6a2-4ea8-a3ae-5ffbe37b89c9)

Suggest either _not_ handling videos at all (multi-gigabyte files with many audio tracks would probably confuse Liquidsoap playout anyway, and make things _sloooow_), _or_ handle other video formats as well (Matroska MKV comes to mind, which is the most flexible container anyway, and remuxing is a snap).

### Files

Should you need something to test, here is a very small MP4 video that doesn’t even _have_ an audio track:
[Nite Radio - Game of Life.mp4.zip](https://github.com/AzuraCast/AzuraCast/files/12394400/Nite.Radio.-.Game.of.Life.mp4.zip)

I see _why_ you’re doing that—[MP4](https://en.wikipedia.org/wiki/MP4_file_format) is a _container_ format that _could_ also hold only audio (usually with MIME type `audio/mp4` instead of `video/mp4`), but would usually expect audio with `.m4a` (audio-only MPEG-4), `.m4p` (iTunes "FairPlay" DRM encrypted audio) or `.m4b` (audio book, podcast) file extensions, and video+audio in `.mp4`. Probably just leave this as it is, most users woud agree, and videos should be kept somewhere separate anyway.

Then again, if you _have_ videos inside your media folder (like in my `videostream` subtree), these appear together with all audio files in searches:

![Screenshot 2023-08-21 at 11-50-40 Nite Radio](https://github.com/AzuraCast/AzuraCast/assets/3706922/d796990f-eb14-483b-887c-eea1857edf46)

A _good_ or a _bad_ thing? I’m undecided. (But somehow feel it might be a good thing…)

**Comment by Moonbase59** [comment]
Note: If I _embed_ a cover image in the video file (video dimensions, jpg), AzuraCast will use _that_ (as expected) but display it like an audio cover image (squared). It doesn’t do that on images (which are shown in the lightbox respecting their original aspect ratio):

![Screenshot 2023-08-21 at 13-49-08 Nite Radio](https://github.com/AzuraCast/AzuraCast/assets/3706922/7be519a8-53a3-491a-b31d-8b2b4a25e0dd)

![Screenshot 2023-08-21 at 13-53-23 Nite Radio](https://github.com/AzuraCast/AzuraCast/assets/3706922/82b65418-199e-4098-a7bf-954b2a59f020)

Here is the same video file as above, with embedded cover:
[Nite Radio - Game of Life (with cover).mp4.zip](https://github.com/AzuraCast/AzuraCast/files/12395639/Nite.Radio.-.Game.of.Life.with.cover.mp4.zip)

**Comment by Moonbase59** [comment]
In case anyone feels like experimenting/debugging, here is the exact same file, correctly remuxed into a Matroska container (in which the cover image is an attachment and tags are handled differently):
[Nite Radio - Game of Life (with cover).mkv.zip](https://github.com/AzuraCast/AzuraCast/files/12398571/Nite.Radio.-.Game.of.Life.with.cover.mkv.zip)

**Comment by Moonbase59** [comment]
Shoo, bot!

**Comment by BusterNeece** [comment]
Not much we can really do about this one, honestly.
