### ISSUE TITLE
RR #26b79e7: Uploading files via "Music Files" broken

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6534]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #26b79e7 (2023-08-20 8:03)

### What happened?

Tried to quickly upload a file using AzuraCast’s "Music File" drag-n-drop in Rolling Release #[26b79e7](https://github.com/AzuraCast/AzuraCast/commit/26b79e7509ccf72b9d2ea7d6ae5e1e7448bb5e40) (2023-08-20 8:03).

This didn’t work: The page "jumps" for a fraction of a second, but no message appears, and the file isn’t uploaded.

The same applies when using the "Select" button and actually selecting the file to be uploaded from the local file tree.

Tried with several file types: `mp4`, `mp3`, `flac`, `ogg`.

(Using SFTP works.)

**Comment by BusterNeece** [comment]
@Moonbase59 What browser? Can't reproduce on latest Firefox or Chrome. Drag-and-drop and select file both work fine on both.

**Comment by Moonbase59** [comment]
Firefox 116.0.3. I’d say d&d works (because the page "jumps") but then something must not work maybe? (And actually dragging n dropping cover images into MusicBrainz works using this browser).

**Comment by BusterNeece** [comment]
@Moonbase59 It's possible the file's encountering an error and just popping out of view before you can see it; I extended the "show the file status" thing a little so those are visible now.

**Comment by Moonbase59** [comment]
Shoo, bot!

**Comment by Moonbase59** [comment]
This has nothing to do with set quota—unlimited in my case, no quota set.

Would of course be no bug if a set quota was overrun.

**Comment by Moonbase59** [comment]
Still applies, Rolling Release #[ccbddf0](https://github.com/AzuraCast/AzuraCast/commit/ccbddf08e7e5d71773328870e0f3edaa979ba9ab) (2023-12-14 21:44).

Maybe AzuraCast shouldn’t try to determine what can’t be determined beforehand and instead _try_ to upload and just report the error if it fails?

**Comment by Moonbase59** [comment]
It’s like lots of little Christmas presents we currently get … works fine on Rolling Release #[dfd2ad8](https://github.com/AzuraCast/AzuraCast/commit/dfd2ad8873cec74deadbe46fff8f255d57d22438) (2023-12-17 18:01) :heart:
