### ISSUE TITLE
RR #26b79e7: Hidden sftpgo remnants remain after upload

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6535]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #26b79e7 (2023-08-20 8:03)

### What happened?

After uploading files, I sometimes detect hidden _sftpgo_ remnants. That’s bad because it a) fills the disc, and b) AzuraCast tries to process them.

![Screenshot 2023-08-21 at 13-17-44 Nite Radio](https://github.com/AzuraCast/AzuraCast/assets/3706922/f096397d-05c6-484d-89e8-b59264b6f3af)

This _seems_ to happen only when I use Nemo (Linux Mint/Cinnamon's default file manager) and the inbuilt `sftp://` scheme for a quick connect (I have saved this as a bookmark):

![Nemo](https://github.com/AzuraCast/AzuraCast/assets/3706922/05abbffe-9840-442a-96f0-3bd5df359b4f)

You can use _File_ → _Connect to server_ in Nemo to set up the connection details and enter your credentials.

I didn’t yet see such leftovers when:
- using FileZilla
- using sshfs to mount my station’s media folder locally

**Comment by BusterNeece** [comment]
@Moonbase59 I'd bet dollars to donuts that a bunch of problems you're having with the filesystem manager are due to you having set the disk quota for this station to be way, way under the actual on-disk size of the collection. We do checks (even with sftp) that a storage location still has "room" for a file before allowing the final operation, and if that fails we don't let it through. No doubt that's causing some measure of problems in your case.

**Comment by Moonbase59** [comment]
Well, it _says_ "1.6 TB used of 78.4 GB" but that wasn’t a problem before (I think). It should probably only check free space staying on the local filesystem, as in `df -l`? But good point, that could be it.

![azuracast@bbd629e71ced: ~-www_001](https://github.com/AzuraCast/AzuraCast/assets/3706922/4a1ae89e-ba27-482f-8105-d196de2c8ec6)

**Comment by Moonbase59** [comment]
Just checked if the correct free size can be gotten using a simple _stat_ (available in almost any programming language, a OS function). As expected, _stat_’ing the file system gives ~28 GB free (stat gives us blocks, so ask it for the block size and calculate):

![azuracast@bbd629e71ced: ~-www_002](https://github.com/AzuraCast/AzuraCast/assets/3706922/b7fe5ea3-1841-45b2-afd2-df9fe5bff6cb)

Question is, of course, what if we had a _writable_ fs mounted. If we find that SFTP always works correctly, only the web uploader doesn’t, I could live with it. Only I think that _both_ the check and the display should agree (either both count non-local, or both don’t). 1.6 TB used in 78.4 GB could _never_ be true. ;-)

**Comment by Moonbase59** [comment]
Shoo, bot!

**Comment by Moonbase59** [comment]
Not stale: Just tested again using Rolling Release #[ccbddf0](https://github.com/AzuraCast/AzuraCast/commit/ccbddf08e7e5d71773328870e0f3edaa979ba9ab) (2023-12-14 21:44).

It seems to happen when replacing files (via file manager SFTP mount). They seem to be temporary upload files, and don’t get erased correctly.

Just freed many GB because I didn’t look for a while…

**Comment by BusterNeece** [comment]
@Moonbase59 So we have two options here, one being to disable "resume" mode in SFTP and just wipe the temp files out immediately should something fail, and the other being to put the temp files in a directory that we include in our bi-daily "temp reaping" process which automatically deletes files that are older than 12 hours old.

I'm inclined to do the latter, as the "resume" feature is really helpful if people are uploading large volumes of files and get interrupted for some reason. That does mean we wind up with a lot more little temp remnant files laying around, but now those files should only be laying around for maybe half a day before getting cleaned up. Definitely shouldn't wind up with GB's worth of files piling up under the hood.

**Comment by Moonbase59** [comment]
Sounds good and the reasoning is solid. I’ll give it a spin later on.

**Comment by Moonbase59** [comment]
Didn’t test the "12-hr-cleanup", but uploaded a few multi-GB files using Filezilla (as most users would probably use), forced some interrupts, used "resume", and `sha256sum`s match. No invisible `.sftpgo…` files to find, and `/tmp/sftpgo_temp/` seems to be used as expected.

Using SFTP with the Nemo file manager also seems to work so far.

I’m wondering a little why the uploaded file
```
Relaxing Meditation Music with Ocean Views, 2 ½ Hours of Tranquility.mp4
```

becomes

```
-rw-r--r-- 1 azuracast azuracast 3555750716 Dec 18 06:04 'Relaxing Meditation Music with Ocean Views, 2 '$'\302\275'' Hours of Tranquility.mp4'
```
inside the Docker when doing an `ls`, but it is displayed alright in file managers and Filezilla, so this might be alright.
