### ISSUE TITLE
Actualización de Azuracast no deja instalar Stereo Tool

### ISSUE THREAD

**Issue by rfigueroa9** [AzuraCast/AzuraCast#6542]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.1

### What happened?

Desde la nueva actualización de Azuracast no se ha podido instalar Stereo Tool

**Comment by BusterNeece** [comment]
What error are you encountering when trying to install Stereo Tool?

We support either the command line version or the plugin version, though the plugin version is strongly recommended in newer versions of AzuraCast.

**Comment by rfigueroa9** [comment]
No me deja instalar la versión de plugin

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BusterNeece** [comment]
@rfigueroa9 What error are you encountering? You have to be more detailed so we can fix the issue.

**Comment by rfigueroa9** [comment]
Actualicé Azuracast a la última versión estable pero esta no me permite instalar Stereo tóol. Lo tenía instalado en la versión anterior pero al actualizar la plataforma se borró y no me deja volverlo a instalar.

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rfigueroa9** [comment]
________________________________
De: Buster Neece ***@***.***>
Enviado: martes, 22 de agosto de 2023 9:41 p. m.
Para: AzuraCast/AzuraCast ***@***.***>
Cc: rfigueroa9 ***@***.***>; Mention ***@***.***>
Asunto: Re: [AzuraCast/AzuraCast] Actualización de Azuracast no deja instalar Stereo Tool (Issue #6542)


@rfigueroa9<https://github.com/rfigueroa9> What error are you encountering? You have to be more detailed so we can fix the issue.
