### ISSUE TITLE
Metadata delays.

### ISSUE THREAD

**Issue by redegradios** [AzuraCast/AzuraCast#6543]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.0

### What happened?

Hello, there are metadata delays.
taking 10 to 40 seconds to update, song name, progress and album art.
Noticeable on the panel itself and on the public page:
https://demo.azuracast.com/public/azuratest_radio

### Relevant log output

```shell
We are using the SSE method
```

**Comment by Moonbase59** [comment]
What is an "SSE method"? Anyway, can’t reproduce here on Rolling Release #[d2ca5eb](https://github.com/AzuraCast/AzuraCast/commit/d2ca5eb22a09096756e78498145d147fb2e82685) (2023-08-22 1:05). Checked with both audio and video streams.

**Comment by redegradios** [comment]
SSE

https://docs.azuracast.com/en/developers/apis/now-playing-data#high-performance-updates

Em ter., 22 de ago. de 2023 12:06, Matthias C. Hormann <
***@***.***> escreveu:

**Comment by Moonbase59** [comment]
Thanks for the pointer.

I hacked up a quick ’n’ dirty one to check:

```
<html>

<head>
  <meta charset="utf-8">
  <title>Nite Radio Now Playing SSE Test</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>

<p id="artist"></p>
<p id="title"></p>

<script>
  const sseUri = "https://example.com/api/live/nowplaying/sse?cf_connect="+JSON.stringify({
    "subs": {
      "station:niteradio": {}
    }
  });

  let sse = new EventSource(sseUri);

  sse.onmessage = (e) => {
    const data = JSON.parse(e.data);
    const np = data?.pub?.data?.np || null;
    if (np) {
      // Handle Now Playing data update as `np` variable.
      //console.log(JSON.stringify(np))
      console.log(Date())
      var a = document.getElementById('artist');
      a.innerHTML = np.now_playing.song.artist;
      console.log(np.now_playing.song.artist);
      var t = document.getElementById('title');
      t.innerHTML = np.now_playing.song.title;
      console.log(np.now_playing.song.title);
    }
  };
</script>

</body>

</html>
```

First update was almost instantaneous, then every so many seconds:

![Nite Radio Now Playing SSE Test – Mozilla Firefox_001](https://github.com/AzuraCast/AzuraCast/assets/3706922/e69776da-ba11-4352-ae99-935002d72ba9)

**Comment by redegradios** [comment]
> Thanks for the pointer.
> 
> I hacked up a quick ’n’ dirty one to check:
> 
> ```
> <html>
> 
> <head>
>   <meta charset="utf-8">
>   <title>Nite Radio Now Playing SSE Test</title>
>   <meta name="viewport" content="width=device-width, initial-scale=1">
> </head>
> 
> <body>
> 
> <p id="artist"></p>
> <p id="title"></p>
> 
> <script>
>   const sseUri = "https://example.com/api/live/nowplaying/sse?cf_connect="+JSON.stringify({
>     "subs": {
>       "station:niteradio": {}
>     }
>   });
> 
>   let sse = new EventSource(sseUri);
> 
>   sse.onmessage = (e) => {
>     const data = JSON.parse(e.data);
>     const np = data?.pub?.data?.np || null;
>     if (np) {
>       // Handle Now Playing data update as `np` variable.
>       //console.log(JSON.stringify(np))
>       console.log(Date())
>       var a = document.getElementById('artist');
>       a.innerHTML = np.now_playing.song.artist;
>       console.log(np.now_playing.song.artist);
>       var t = document.getElementById('title');
>       t.innerHTML = np.now_playing.song.title;
>       console.log(np.now_playing.song.title);
>     }
>   };
> </script>
> 
> </body>
> 
> </html>
> ```
> 
> First update was almost instantaneous, then every so many seconds:
> 
> ![Nite Radio Now Playing SSE Test – Mozilla Firefox_001](https://user-images.githubusercontent.com/3706922/262424685-e69776da-ba11-4352-ae99-935002d72ba9.png)

See the delay, my SSE link:
https://servidor.geracaoradios.com/api/live/nowplaying/sse?cf_connect={%22subs%22:{%22station:sertanejouniversitario%22:{}}}

**Comment by Moonbase59** [comment]
That _is_ slow! First answer from the API was instantaneous, then about once a minute.

![Nite Radio Now Playing SSE Test – Mozilla Firefox_002](https://github.com/AzuraCast/AzuraCast/assets/3706922/a5764c30-456b-47eb-b001-7590ca5a794c)

Sure you have enabled "Use High-Performance Now Playing Updates" in System Settings?

![Administration – Mozilla Firefox_006](https://github.com/AzuraCast/AzuraCast/assets/3706922/d83cecea-cb70-4741-8d49-ae5685e3555f)

**Comment by Moonbase59** [comment]
This also affects your public web player: The next song is often playing already for 30–40s before the display switches.

**Comment by redegradios** [comment]
No, the server is not in the bottleneck, I'll send you a print. I think
there must be some limitation. I have about 1000 listeners on the radios,
it consumes resources, but my server is not at the limit.

**Comment by Moonbase59** [comment]
Hm, so we must pass it on to the devs.

I ran some crashtests a few weeks ago, and could serve ~5,000 listeners from one station, using Icecast and a 2-CPU, 4 GB RAM and 40 GB SSD VM. So that may really not be the limit. I don’t know how fast Centrifugo is, maybe with 1,000 listeners all using SSE updates the API could be a limit?

**Comment by redegradios** [comment]
I have 16 cores. And almost every radio station uses master-me processing. the people who work with me will interact here, to answer questions

![image](https://github.com/AzuraCast/AzuraCast/assets/142024160/123a1b75-5400-4f43-a658-5791d1f8399e)

**Comment by Marcioghiraldelli** [comment]
really, in sse sometimes it works and other times it doesn't. But I realize that this only happens more frequently when you have more stations on the same server. Even with a relatively low load, SSE fails at some point or takes a long time to generate an update.
I also noticed that even in the example azuracast panel this happens.

**Comment by BusterNeece** [comment]
In looking into this, I noticed that High-Performance Now Playing updates were disabled on the demo installation (and by default on local dev ones), so that's fixed now.

It's possible, even if you're using high-performance now playing updates, that having several stations running on a single server could mean that a station sends a now-playing update out moments before the track changes, resulting in some unfortunate timing as it delays for its usual period waiting on the next update.

I've made some changes to our code to force it to prioritize that station in the next round of Now Playing updates. This won't make things instant (we actually don't want that, as that means the Now Playing updates _before_ listeners hear it on Icecast/Shoutcast) but it should make things more responsive.

**Comment by Moonbase59** [comment]
In Rolling Release #[2e78758](https://github.com/AzuraCast/AzuraCast/commit/2e78758d91099780434c49cdbe16f4603b842bc5) (2023-08-23 1:33), not much change for my evaluation station, but that’s to be expected with 2 listeners…

Updates every 7–20 seconds here, plus apparently sometimes an extra update near the song change. The SSE update hits in a few fractions of a second earlier than the update of the station profile page.

**Comment by redegradios** [comment]
Cool I'm on the STABLE version. Once released I will update

Em qua., 23 de ago. de 2023 00:05, Matthias C. Hormann <
***@***.***> escreveu:
