### ISSUE TITLE
RR #2e78758: Profile page/player/SSE nowplaying don't update when jingle in between songs

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6544]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #2e78758 (2023-08-23 1:33)

### What happened?

While testing the new NP high-performance updates in Rolling Release #[2e78758](https://github.com/AzuraCast/AzuraCast/commit/2e78758d91099780434c49cdbe16f4603b842bc5) (2023-08-23 1:33), I recognized that neither profile page nor web player nor SSE updated when a jingle played between two songs.

The metadata of the song before the jingle was shown
- during the jingle playout (ok so far)
- during the whole next song (not ok)

After the next song finished playing (and no other jingle hit in), display was updated again.

![Auswahl_259](https://github.com/AzuraCast/AzuraCast/assets/3706922/8e2aa025-f46b-4765-ae1e-7390c9f3de54)

![Nite Radio Now Playing SSE Test – Mozilla Firefox_003](https://github.com/AzuraCast/AzuraCast/assets/3706922/2f85c9f9-9550-4484-ba89-823ce9c447cb)

**Comment by Moonbase59** [comment]
Just had an other jingle in between songs, and it _did_ update correctly, so it’s not happening always.

**Comment by Moonbase59** [comment]
Can’t have anything to do with the filetype, right? Just asking because "Solsbury Hill" is a `.ogg` song, and I almost exclusively have FLAC and MP3. Only 901 songs out of 157,430 are "exotic formats", i.e. not FLAC or MP3.

**Comment by BusterNeece** [comment]
It shouldn't, no...it's possible it's just not updating fast enough to "catch" the jingle. Perhaps the between-now-playing-tasks delay is itself longer than the jingle.

**Comment by Moonbase59** [comment]
That’d be bad. Unfortunately I can’t remember _which_ jingle it was. They’re between 7 and 19 seconds. All are set to `0.1` seconds fade-in, fade-out, overlap to avoid crossfading jingles with music.

![Auswahl_260](https://github.com/AzuraCast/AzuraCast/assets/3706922/ce45e88b-0d65-4e80-82ad-1b5bccfadd76)

**Comment by Moonbase59** [comment]
Let’s close this, in order not to clutter the issues. We can re-open if needed.

Seems I really caught an edge case here. Of course I don’t watch my station 24/7, but I didn’t see it again while listening.

**Comment by Moonbase59** [comment]
_Might_ be related, probably also a little edge-casey: https://github.com/AzuraCast/AzuraCast/issues/6415

Just noting this here so we don’t lose a possible connection.
