### ISSUE TITLE
RR #2e78758: Listener History: Convenience menu "Last x days/weeks/months" missing

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6548]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #2e78758 (2023-08-23 1:33)

### What happened?

In Listener History, the "convenience menu" next to the calendar selection that had "Last … days/weeks/months" isn’t there anymore. Is that intentionally? (It _was_ useful!)

![Nite Radio – Mozilla Firefox_012](https://github.com/AzuraCast/AzuraCast/assets/3706922/7fdb0626-efa1-40fa-92d4-60c3c9a9f6cf)

**Comment by BusterNeece** [comment]
We updated to 6.0.x of the `vue-datepicker` library, and it seems that threw some stuff off. I tried following the migration instructions, but it still wasn't quite right. Will give them a little time to work out the bugs.

**Comment by Moonbase59** [comment]
Yeah, no problem. It was convenience anyway, but one gets used to thinks being more easy ;-)

**Comment by Moonbase59** [comment]
N.B.: Using the old datepicker (5.0?) for the time being makes it as convenient as it was, thanks. This really helps getting "quick glances" on one’s audience.
