### ISSUE TITLE
Admin → System Debugger: Sync Tasks not shown anymore (but running)

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6550]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #b80c0a6 (2023-08-24 1:26)

### What happened?

In  _Administration → System Debugger → Synchronization Tasks_, the table stays empty.

Sync tasks are still running, as verified by watching `htop` within the station.

![Administration – Mozilla Firefox_009](https://github.com/AzuraCast/AzuraCast/assets/3706922/ef61ec8e-7b48-461b-bed0-784f1a513807)

**Comment by Moonbase59** [comment]
Confirm fixed in Rolling Release #[f994922](https://github.com/AzuraCast/AzuraCast/commit/f9949222842a5f2fd3051e437a9a4e04f401053a) (2023-08-26 1:36).

Drawback with this page (want a new issue?): Doesn’t auto-update, so you have to refresh the page (no prob), but it always jumps back to the top, which is a hindrance when you want to watch the queues (like on a large media reprocess).

**Comment by BusterNeece** [comment]
@Moonbase59 Yeeah let's do a new issue for that, just because it's actually a product of the Vuetification of the page, so it'll require a little more re-engineering.
