### ISSUE TITLE
Web update error code

### ISSUE THREAD

**Issue by XPA1** [AzuraCast/AzuraCast#6555]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.18.5 Stable

### What happened?

i will click update via web but it will not work, i wanna update the page so bad please help

### Relevant log output

```shell
v0.18.5 Stable
```

**Comment by BusterNeece** [comment]
@XPA1 Just update via SSH following our standard instructions:
https://docs.azuracast.com/en/getting-started/updates

**Comment by XPA1** [comment]
how do u do that im useing lindoe/akamai to use azuracast?
