### ISSUE TITLE
Decoding/Categorizing listener user agents: `StudioDisplay/0.5` not recognized

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6556]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #97f0226 (2023-08-24 10:05)

### What happened?

Don’t know how you decode/categorize listener user agents, but my `StudioDisplay/0.5` is seen as "Unknown Browser 0.00" instead of "StudioDisplay 0.5".

![Auswahl_263](https://github.com/AzuraCast/AzuraCast/assets/3706922/95dfb34d-c39b-4173-92f2-b14e7b9c2a19)

[StudioDisplay](https://github.com/Moonbase59/studiodisplay), my suite of programs for web radio studios, has been around since 2017 and uses this module to watch a stream, read its in-stream metadata, and feed my studio display monitor with it, via MQTT. Most show hosts/DJs also have one, so it would be nice to see how many "listeners" are actually dumb screens on the wall without any sound. :-)

![studiodisplay-en-GB-night](https://github.com/AzuraCast/AzuraCast/assets/3706922/d999f524-cbf0-4964-8c83-6cf0305ec930)

The reason for using the archaic piece of software is that DJs/show hosts work with more than one station, and they have no influence on the software or APIs used, thus the easiest solution was to read in-stream metadata, which works with Shoutcast 1 & 2, and Icecast (if provided, of course). The last value in the user agent tells a station owner what character set StudioDisplay is set up to expect for this stream. (Many still send in-stream metadata in "illegal" character sets like Chinese, Korean, Russian, etc., and we try to decode these into UTF-8 for proper display.)

**Comment by BusterNeece** [comment]
Upstream library called https://github.com/matomo-org/device-detector

**Comment by Moonbase59** [comment]
Added upstream, waiting for their next release.
