### ISSUE TITLE
Manage User & Role minor bug?

### ISSUE THREAD

**Issue by PeWe79** [AzuraCast/AzuraCast#6557]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#97f0226 (2023-08-24 10:05)

### What happened?

Hi, after update I think got "minor" bug on Manage User & Role.

![Screenshot from 2023-08-25 02-26-17](https://github.com/AzuraCast/AzuraCast/assets/117633869/e2bc37eb-da09-4274-a930-7f31e2f07c5c)

![Screenshot from 2023-08-25 02-29-53](https://github.com/AzuraCast/AzuraCast/assets/117633869/d3938faa-4880-4920-b1e2-3bd52d86b330)

**Comment by BusterNeece** [comment]
@PeWe79 Thank you for the report! Pushing a fix up for that right now.
