### ISSUE TITLE
RR #f994922: Admin: AzuraCast Synchronized Task Log not found

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6560]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #[f994922](https://github.com/AzuraCast/AzuraCast/commit/f9949222842a5f2fd3051e437a9a4e04f401053a) (2023-08-26 1:36)

### What happened?

Trying to check _Administration → System Maintenance → System Logs → AzuraCast Synchronized Task Log_, got error "Log not found":

![Administration – Mozilla Firefox_012](https://github.com/AzuraCast/AzuraCast/assets/3706922/dcf976a7-c92e-46cf-a073-2c70ceee1628)

**Comment by BusterNeece** [comment]
Can't currently repro. It's possible the file wasn't created if you either had just updated or it was the turn of the 24-hour period, at which point it would rotate out the logs.

**Comment by Moonbase59** [comment]
Yeah, of course I update pretty often with Rolling Relase… And you’re right, now (>24 hours later) it displays. Might still confuse a user who just updated.

**Comment by Moonbase59** [comment]
Hmm… Just updated again, and the _AzuraCast Synchronized Task Log_ missing again. Does that mean we have to wait 24 hours after update before we can see it?

**Comment by BusterNeece** [comment]
Not 24 hours, no...just until it produces a few log entries.

**Comment by Moonbase59** [comment]
Ah, okay, guess we could live with that. Will test tomorrow.

**Comment by Moonbase59** [comment]
Same now happens with the "Now playing" log:

![Administration – Mozilla Firefox_014](https://github.com/AzuraCast/AzuraCast/assets/3706922/699ead24-5481-4eb9-845f-7c85027ee135)

On RR # 47a4c00
