### ISSUE TITLE
Podcast public page not formatted correctly.

### ISSUE THREAD

**Issue by ChandigarIT** [AzuraCast/AzuraCast#6563]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 v0.19.1 Stable - Docker - PHP 8.2

### What happened?

Podcast public page is missing the top few listings. However, I have found the problem, it's in the CSS file 

/static/vite_dist/assets/layout-e652eb15.css

Removing the following rules fixes this.

element.style {
    height: 100dvh; 
}
.align-items-center {
    align-items: center!important; 
}

I don't know what lines these are on, as the file is minified, but they are towards the end.

### Relevant log output

```shell
No logs relevant
```

**Comment by BusterNeece** [comment]
This should be fixed in the latest Rolling Release.
