### ISSUE TITLE
Problem with crossfade since 0.19.x

### ISSUE THREAD

**Issue by wegGehamstert** [AzuraCast/AzuraCast#6564]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#2a52016 

### What happened?

Especially jingles are skipped in a strange way and not played correctly. This often creates a great silence. Unfortunately, I still don't know what the problem is.

I pasted some liquidsoap logs down there but i can't see any problems with that

### Relevant log output

```shell
[mp3 @ 0x7f853d52e400] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f853d52e400] Estimating duration from bitrate, this may be inaccurate
2023/08/26 15:33:46 [next_song:3] Prepared "/var/azuracast/stations/mainstream/media/► Jingle /breathfm_social_media.mp3" (RID 209).
2023/08/26 15:33:46 [cue_next_song:3] Cueing in...
2023/08/26 15:33:46 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2023/08/26 15:33:46 [lang:3] API nextsong - Response (200): annotate:title="Boys Do Cry",artist="Marius Bear",duration="178.00",song_id="a5151854f9915992480f8cf148630e9a",media_id="5925",playlist_id="16":media:» 20er/marius_bear_-_boys_do_cry.mp3
2023/08/26 15:33:46 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/mainstream/media/» 20er/marius_bear_-_boys_do_cry.mp3": {audio=pcm(stereo)}
2023/08/26 15:33:46 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/mainstream/media/» 20er/marius_bear_-_boys_do_cry.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}, video: {codec: mjpeg, 800x800, yuvj420p}
2023/08/26 15:33:46 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/mainstream/media/» 20er/marius_bear_-_boys_do_cry.mp3": {audio=pcm(stereo)}
2023/08/26 15:33:46 [cross:3] Analysis: -19.076623dB / -43.411834dB (7.44s / 7.44s)
2023/08/26 15:33:46 [source.517:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:46 [audio.add.166:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:46 [fade_in.332:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:46 [fade_in.331:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:46 [on_track.666:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:46 [on_metadata.332:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:46 [on_track.665:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:46 [cross_after.166:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:46 [buffer.332:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:46 [fade_out.332:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:46 [fade_out.331:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:46 [on_end.166:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:46 [on_track.664:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:46 [on_metadata.331:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:46 [on_track.663:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:46 [cross_before.166:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:46 [buffer.331:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:46 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
2023/08/26 15:33:46 [lang:3]   "song_id": "f7c00bf4d1cbed6f7932fbe0076f71fe",
2023/08/26 15:33:46 [lang:3]   "playlist_id": "6",
2023/08/26 15:33:46 [lang:3]   "media_id": "7725"
2023/08/26 15:33:46 [lang:3] }
2023/08/26 15:33:46 [lang:3] API feedback - Response (200): true
2023/08/26 15:33:55 [decoder:2] Decoding "/var/azuracast/stations/mainstream/media/► Jingle /breathfm_social_media.mp3" ended: Ffmpeg_decoder.End_of_file.
2023/08/26 15:33:55 [next_song:3] Prepared "/var/azuracast/stations/mainstream/media/» 20er/marius_bear_-_boys_do_cry.mp3" (RID 210).
[mp3float @ 0x7f853b34e900] Could not update timestamps for skipped samples.
2023/08/26 15:33:55 [cue_next_song:3] Cueing in...
2023/08/26 15:33:55 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2023/08/26 15:33:55 [lang:3] API nextsong - Response (200): annotate:title="RefugiaCraft.de Werbung",artist="BreathFM",duration="12.00",song_id="b3f003756147286fb85d3addc4dbab1a",media_id="9091",liq_fade_in="0.10",liq_fade_out="2.10",playlist_id="58",jingle_mode="true":media:► Jingle /refugiacraft_werbung_br.mp3
[mp3 @ 0x7f853cb79000] Estimating duration from bitrate, this may be inaccurate
2023/08/26 15:33:55 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/mainstream/media/► Jingle /refugiacraft_werbung_br.mp3": {audio=pcm(stereo)}
2023/08/26 15:33:55 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/mainstream/media/► Jingle /refugiacraft_werbung_br.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/08/26 15:33:55 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/mainstream/media/► Jingle /refugiacraft_werbung_br.mp3": {audio=pcm(stereo)}
[mp3 @ 0x7f853cb79000] Estimating duration from bitrate, this may be inaccurate
2023/08/26 15:33:55 [cross:3] Analysis: -25.791873dB / -32.721367dB (7.45s / 7.47s)
2023/08/26 15:33:55 [source.520:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:55 [audio.add.167:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:55 [fade_in.334:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:55 [fade_in.333:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:55 [on_track.670:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:55 [on_metadata.334:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:55 [on_track.669:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:55 [cross_after.167:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:55 [buffer.334:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:55 [fade_out.334:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:55 [fade_out.333:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:55 [on_end.167:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:55 [on_track.668:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:55 [on_metadata.333:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:55 [on_track.667:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:55 [cross_before.167:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:55 [buffer.333:3] Content type is {audio=pcm(stereo)}.
2023/08/26 15:33:55 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
2023/08/26 15:33:55 [lang:3]   "song_id": "a5151854f9915992480f8cf148630e9a",
2023/08/26 15:33:55 [lang:3]   "playlist_id": "16",
2023/08/26 15:33:55 [lang:3]   "media_id": "5925"
2023/08/26 15:33:55 [lang:3] }
2023/08/26 15:33:55 [lang:3] API feedback - Response (200): true
[mp3float @ 0x7f853b34e900] Could not update timestamps for discarded samples.
2023/08/26 15:36:46 [decoder:2] Decoding "/var/azuracast/stations/mainstream/media/» 20er/marius_bear_-_boys_do_cry.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f853d52e400] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f853d52e400] Estimating duration from bitrate, this may be inaccurate
2023/08/26 15:36:46 [next_song:3] Prepared "/var/azuracast/stations/mainstream/media/► Jingle /refugiacraft_werbung_br.mp3" (RID 211).
2023/08/26 15:36:46 [cue_next_song:3] Cueing in...
2023/08/26 15:36:46 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2023/08/26 15:36:46 [lang:3] API nextsong - Response (200): annotate:title="Levitating",artist="Dua Lipa",duration="203.00",song_id="0cef747e9c00e5ba5e7bebb432deced8",media_id="5765",liq_cue_out="201.40",playlist_id="16":media:» 20er/dua_lipa_-_levitating.mp3
2023/08/26 15:36:46 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/mainstream/media/» 20er/dua_lipa_-_levitating.mp3": {audio=pcm(stereo)}
2023/08/26 15:36:46 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/mainstream/media/» 20er/dua_lipa_-_levitating.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}, video: {codec: mjpeg, 800x800, yuvj444p}
2023/08/26 15:36:46 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/mainstream/media/» 20er/dua_lipa_-_levitating.mp3": {audio=pcm(stereo)}
2023/08/26 15:36:46 [cross:3] Analysis: -33.924027dB / -50.555038dB (7.47s / 7.49s)
```

**Comment by wegGehamstert** [comment]
Maybe is this relevant. 
https://github.com/savonet/liquidsoap/issues/3334

**Comment by Moonbase59** [comment]
You seem to use a long cross duration, let’s see your custom crossfade part of the script.

If you wish for the jingles not to be affected by what you have set for normal crossfading, you can set them like I do, with a minimal fade-in and fade-out time of `0.1`s (0 won’t work, it means "use the default") like so:

![Auswahl_260](https://github.com/AzuraCast/AzuraCast/assets/3706922/83ff1138-0c33-4478-90bf-12e23e820d4d)

That should ensure that jingles are played with (nearly) no crossfading, while normal songs will be crossfaded according to your settings. It may still fail if the jingle duration is less than your cross duration.

**Comment by wegGehamstert** [comment]
Thank you for those tips! 

But my main problem is that the songs also don't fade like they do before.
It's more like a hard cut at the end rather then a smooth fade out. 

This changed sind i upgraded to 0.19

**Comment by wegGehamstert** [comment]
Toots posted a modified script.

https://github.com/savonet/liquidsoap/issues/3334#issuecomment-1694960122

**Comment by radiobellissima** [comment]
I confirm that something is wrong with the code. We had arrived at a good compromise between modified code and advanced options everything was perfect in the mixes. From this update onwards there is no way to make it work in normal mode anymore. While waiting for the bug to be fixed, I had to put the mix back in smart mode which still works very badly. In practice, at the end mix with the same song that is about to end by turning up the volume and almost creating an echo and then cut everything. Also noticed a problem with the on air the minutes of the song on the air are far behind almost 2 minutes.

**Comment by wegGehamstert** [comment]
https://github.com/savonet/liquidsoap/issues/3334#issuecomment-1697932705

Maybe solved soon :)

**Comment by wegGehamstert** [comment]
https://github.com/savonet/liquidsoap/issues/3334#issuecomment-1698030411

Should be pushed soon @BusterNeece. Fingers crossed!

**Comment by Sweetness2k** [comment]
I also have this issue on all my stations it sound really bad at the end and too fix the issue I have to do a soft reload every morning, it seem too work good for 24hrs after that it go back skipping at the end with a silence at the end...hope this get fix soon

**Comment by Moonbase59** [comment]
How ’bout doing some field testing before this gets implemented? Rather easy (and the change will be reverted after the next `docker compose down`/ `docker compuse up -d`:

SSH into your host where AzuraCast is installed, then:
```bash
cd /var/azuracast
sudo ./docker.sh bash
```
You are now _inside_ the running docker container. Continue like so (assuming you’re running on Ubuntu 22.04):
```bash
sudo su
cd
wget https://github.com/savonet/liquidsoap-release-assets/releases/download/rolling-release-v2.2.x/liquidsoap-de9dc76_2.2.1-ubuntu-jammy-1_amd64.deb
apt install ./liquidsoap-de9dc76_2.2.1-ubuntu-jammy-1_amd64.deb
```
It should now tell you something like "1 to remove, 1 to install" and indicate the old and new Liquidsoap versions. Answer "Y"es and ignore the error message about something not installed.

Leave all the terminals:
```bash
exit
exit
exit
exit
```

Now go to your station profile, to _AutoDJ Service Liquidsoap_ and click on "Restart". Wait a while (~1–2 minutes) until it says "running" again.

Voilà! You now have your station running with the latest Liquidsoap! And safely—you can always SSH into your host again and
```bash
cd /var/azuracast
sudo docker compose down
sudo docker compose up -d
```
to revert to a "clean" version again (not containing the updated Liquidsoap).
If `docker compose` doesn’t work, use `docker-compose` instead (with a hyphen).

**Comment by Moonbase59** [comment]
Using Rolling Release #[47a4c00](https://github.com/AzuraCast/AzuraCast/commit/47a4c00df83acc4e9190c8d9910d55f9f1242ba5) (2023-08-29 12:02) and Liquidsoap 2.2.1+git@de9dc76e1, here are video & audio samples of how my top-of-the-hour (interrupting, track-insensitive) time announcement sounds:
https://github.com/savonet/liquidsoap/issues/3334#issuecomment-1699061698

**Comment by wegGehamstert** [comment]
The rolling release wich you wrote ist not the newest. There was some hours ago a newer version with a possible patch. @Moonbase59

**Comment by BusterNeece** [comment]
We've updated the Rolling Release of AzuraCast to be on the very latest Liquidsoap Rolling Release available currently.

**Comment by Moonbase59** [comment]
> The rolling release wich you wrote ist not the newest. There was some hours ago a newer version with a possible patch. @Moonbase59

@wegGehamstert Read carefully: _"and Liquidsoap 2.2.1+git@de9dc76e1"_ ;-) [There _was_ a reason I showed how this can be done. Couldn’t know @BusterNeece would implement it _that_ fast. Now I have to sit out another day before further updates, because it was reported it happened only after 24 hours or so.]

**Comment by wegGehamstert** [comment]
> Read carefully

Okey this is my bad. But i need to say, on the newest rolling release it is working fine for me since 6 hours straight.

**Comment by Moonbase59** [comment]
We’re looking at more than one problem here, although they might have the same underlying causes. See https://github.com/savonet/liquidsoap/issues/3334#issuecomment-1699165262.

**Comment by wegGehamstert** [comment]
> We’re looking at more than one problem here, although they might have the same underlying causes. See [savonet/liquidsoap#3334 (comment)](https://github.com/savonet/liquidsoap/issues/3334#issuecomment-1699165262).

I need to change me anwser, it's not completley fixed. The weird cuts at the end of the track are sometimes there but not as annoying as bevore.

**Comment by radiobellissima** [comment]
Updated to the latest release last night. I have to confirm that nothing has been fixed or changed. I can reproduce the problem in less than 1 hour perhaps due to the high number of stations on my server.
Rolling Release #[6c27dfb] (2023-08-30 12:20)

**Comment by Moonbase59** [comment]
Currently testing Liquidsoap 2.3.0+git@3dbbdc994 (.deb from main) in AzuraCast RR #[6c27dfb](https://github.com/AzuraCast/AzuraCast/commit/6c27dfbd8237c4364d6ea12c3c43536f3d7772ed), let’s see.

**Comment by wegGehamstert** [comment]
For me with the rolling release #[c205487](https://github.com/AzuraCast/AzuraCast/commit/c2054876209d7f7cd22a144dd32f9817b9511b8c) the issue got fixed by the liquidsoap team. 

I will close this issue, if you have problems with the crossfade, open a other issue.
