### ISSUE TITLE
Weird redirects on Safari and on all mobile browsers on iOS in conjunction with Nginx Proxy Manager.

### ISSUE THREAD

**Issue by djakobi** [AzuraCast/AzuraCast#6570]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.1

### What happened?

Hello all,

since the update to 0.19.1 this week, I have the problem that my music playback no longer works under macOS/iOS devices.

We have a web app through which our users listen to the radio. In the web app, we have stored an extra subdomain that is forwarded through the Nginx Proxy Manager to our AzuraCast domain (keyword proxy pass).

Since the update, however, there is a forwarding under iOS/macOS devices, which is why the link is invalid. In the background, a 302 forwarding takes place, which forwards to the link with an ending ic_.
The problem unfortunately disrupts the operation of all our channels, which is super annoying.

I have already looked at a few issues and it sounds very much like the following numbers:
#6480 #6436 

It would be really urgent to get this working again.

Thank you!
Dominik

**Comment by audio-stream** [comment]
Here we have the same problem, after the Update to 19.1 our iOS app plays for 5 seconds and stops.
I tested it with a CentovaCast streaming and it works perfect.
There is definitely something wrong with AzuraCast.

**Comment by BusterNeece** [comment]
I suspect this is related to the work that Icecast-KH has been doing specific to iOS. I'm not sure why, but it seems to be causing a whole myriad of issues downstream for us.

**Comment by audio-stream** [comment]
I believe it is Kh who is doing this.

**Comment by audio-stream** [comment]
Can't we go back to the previous version of Kh?
Until version 18.1 of AzuraCast did not have this problem.

**Comment by Vaalyn** [comment]
@BusterNeece regarding the redirect issue we could probably try something like the commenter here posted: https://github.com/AzuraCast/AzuraCast/issues/6304#issuecomment-1646866991

Didn't see that comment until now unfortunately.

> I suspect this is related to the work that Icecast-KH has been doing specific to iOS. I'm not sure why, but it seems to be causing a whole myriad of issues downstream for us.

The redirect thing was done due to caching issues in Safari, see the following comments from their code with the redirect as well as the note in their changelog:
> Safari is an oddball, seems to use multiple connections with one being a range request of 0-1 to get the size

(Therefore they drop the range request, preventing Safari users from counting as 2 listeners, which was a huge issue in itself too. For that reason we shouldn't revert to earlier versions imho.)

> trick for safari only (redirect to same url with random code param) to workaround a caching issue.

**Comment by BusterNeece** [comment]
The latest Rolling Release does include a hotfix for this particular issue...can anyone confirm if it made any difference on iOS devices?

**Comment by Vaalyn** [comment]
Tested Safari on iOS 17.0.1 and Safari on macOS Sonoma 14.0 (23A339), both working well for me and no more redirects being done as far as I can see.

**Comment by audio-stream** [comment]
Tested with iPhone ios16 and 17 everything seems normal now.
