### ISSUE TITLE
The listener report doesn't work

### ISSUE THREAD

**Issue by radiobellissima** [AzuraCast/AzuraCast#6574]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#7bea769 (2023-08-29 3:55) 

### What happened?

The listeners appear on the map, but you don't get any lists on the page.

**Comment by Moonbase59** [comment]
Confirmed for Rolling Release #[47a4c00](https://github.com/AzuraCast/AzuraCast/commit/47a4c00df83acc4e9190c8d9910d55f9f1242ba5) (2023-08-29 12:02).

**Comment by Moonbase59** [comment]
Thanks, confirm working again in Rolling Release #[6c27dfb](https://github.com/AzuraCast/AzuraCast/commit/6c27dfbd8237c4364d6ea12c3c43536f3d7772ed) (2023-08-30 12:20).
