### ISSUE TITLE
RR #47a4c00: Left menu doesn’t open pages when on station profile

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6575]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #47a4c00 (2023-08-29 12:02)

### What happened?

Didn’t check many other combinations, suspect SPA problem: When on the station profile page and clicking _Media → Music Files_ or _Logs_ in the left menu, the small white progress bar at the top of the pages moves through once, but nothing happens, i.e., the desired page doesn’t load.

EDIT: Interestingly, when refreshing the page (F5) after that try, the correct (last selected) page shows up. So just some notification/refresh missing.

**Comment by BusterNeece** [comment]
Browser console saying anything? Can't repro this on my side, all the links work fine.

**Comment by Moonbase59** [comment]
I wonder if this was caused by an update. Could it be that something is stored/cached in the browser that’s refreshed in the meantime? Because I used `Ctrl`+`F5` several times, to be sure.

Can’t now repro myself, neither on normal Firefox nor on "Private Mode" (to be sure about Cache/Cookies, I tried that, too).

Browser Console just reports a few problems with `transition` but states them being ignored:

![Nite Radio – Mozilla Firefox Privater Modus_001](https://github.com/AzuraCast/AzuraCast/assets/3706922/03b33e33-8f41-4cf1-87e5-7123a230305d)

**Comment by BusterNeece** [comment]
Could've had something to do with the DataTable issues that were affecting things like the listener report.

No idea if Firefox honors env settings like that for locales. We can always translate console messages, though. It's better by far to have the messages than to not have them.

**Comment by Moonbase59** [comment]
With Rolling Release #[6c27dfb](https://github.com/AzuraCast/AzuraCast/commit/6c27dfbd8237c4364d6ea12c3c43536f3d7772ed) (2023-08-30 12:20), this happened more often than not tonight. I was mainly jumping around between station profile, Edit LS Config, and Logs. As usual, refreshing the page usually displayed the correct page content.

Unfortunately, it doesn’t _always_ happen, and I couldn’t yet nail it down to some sequence of events. Using Firefox 117.0 currently, if that helps.

**Comment by BusterNeece** [comment]
I need to see a video of this or something. It's not happening at all on my local instances.

**Comment by Moonbase59** [comment]
Here you go:

[AzuraCast No page update-2023-09-01_14.32.47.mkv.zip](https://github.com/AzuraCast/AzuraCast/files/12498026/AzuraCast.No.page.update-2023-09-01_14.32.47.mkv.zip)

Fortunately, it happened almost immediately. Running Rolling Release #[6c27dfb](https://github.com/AzuraCast/AzuraCast/commit/6c27dfbd8237c4364d6ea12c3c43536f3d7772ed) (2023-08-30 12:20).

**Comment by BusterNeece** [comment]
@Moonbase59 Is anything showing up on the browser console/F12?

**Comment by Moonbase59** [comment]
Just this:

![Auswahl_267](https://github.com/AzuraCast/AzuraCast/assets/3706922/3c747438-c7fa-4711-836e-1e665518bd38)

But I currently can’t make it "not work", sigh… Sometimes it almost never works, sometimes almost ever.

**Comment by Moonbase59** [comment]
Probably won’t help you much, but I _almost_ caught one: Browser console displayed a type error and a long list of lines starting with one or two letters, all Vue-related: "D", "A", "O", "be", etc.

Unfortunately, when trying to save console output to a file, Firefox 117 crashed!
Will keep you updated.

**Comment by Moonbase59** [comment]
Finally aucght one. What a long run.

Here’s the console log:
[2023-09-03 AzuraCast Menu problem browser console log.txt](https://github.com/AzuraCast/AzuraCast/files/12504899/2023-09-03.AzuraCast.Menu.problem.browser.console.log.txt)

**Comment by BusterNeece** [comment]
I found a few type errors being thrown out and fixed those...but it's really hard for me to pin down what's going on here. If it's possible to get a video of it, it would be helpful.

**Comment by Moonbase59** [comment]
It’s very hard for me reproducing these, too. They aso become less and less frequent with newer updates. I _do_ still see some (few) times when the right contents part of the app doesn’t update after clicking something from the lefthand menu. Last time I was on "Station Profile" view and wanted to change to "Playlists" and nothing happened, only after F5 the playlists were shown.

Let’s just hope your found type errors fix these few occurences. It happens seldom enough to not be a deal-breaker, but of course is a little irritating, clicking the same menu entry over and over again and nothing happens ;-)

**Comment by Moonbase59** [comment]
Still happens once in a while on Rolling Release #[ab9b626](https://github.com/AzuraCast/AzuraCast/commit/ab9b626103a134ba74b9c8de0898303123c1ff00) (2024-02-10 2:39).
