### ISSUE TITLE
empty title random

### ISSUE THREAD

**Issue by radiobellissima** [AzuraCast/AzuraCast#6577]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#7bea769 (2023-08-29 3:55)

### What happened?

An empty title meta tag is seemingly randomly sent.
![Test](https://github.com/AzuraCast/AzuraCast/assets/57127248/c2e61f05-ba36-423a-bb13-5f6c4c7b6ed2)

**Comment by wegGehamstert** [comment]
Can you maybe provide more information like logs?

**Comment by radiobellissima** [comment]
Here is a log with the error. At 21.14 the problem that did not exist before the recent updates reappeared. I think the relevant part is this:
2023/09/03 21:14:34 [metadata_map.3:3] Inserting missing metadata.
2023/09/03 21:14:34 [metadata_map.5:3] Inserting missing metadata.


2023/09/03 21:11:33 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/100_best_ibiza_deep_house/media/ADVERT 1 SEC/start_ad_break_1sec.mp3": {audio=pcm(stereo)}
2023/09/03 21:11:33 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/100_best_ibiza_deep_house/media/ADVERT 1 SEC/start_ad_break_1sec.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}, video: {codec: mjpeg, 600x600, yuvj444p}
2023/09/03 21:11:33 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/100_best_ibiza_deep_house/media/ADVERT 1 SEC/start_ad_break_1sec.mp3": {audio=pcm(stereo)}
2023/09/03 21:11:33 [lang:3] API feedback - Response (200): true
[mp3float @ 0x7f02c01b7900] Could not update timestamps for discarded samples.
2023/09/03 21:14:29 [decoder:2] Decoding "/var/azuracast/stations/100_best_ibiza_deep_house/media/DEEP TOP 1000/Kydus - 1985.mp3" ended: Ffmpeg_decoder.End_of_file.
2023/09/03 21:14:29 [next_song:3] Prepared "/var/azuracast/stations/100_best_ibiza_deep_house/media/ADVERT 1 SEC/start_ad_break_1sec.mp3" (RID 1006).
[mp3float @ 0x7f02c01b7e00] Could not update timestamps for skipped samples.
2023/09/03 21:14:29 [cue_next_song:3] Cueing in...
2023/09/03 21:14:29 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/nextsong' with body: 
[mp3float @ 0x7f02c01b7e00] Could not update timestamps for discarded samples.
2023/09/03 21:14:29 [decoder:2] Decoding "/var/azuracast/stations/100_best_ibiza_deep_house/media/ADVERT 1 SEC/start_ad_break_1sec.mp3" ended: Ffmpeg_decoder.End_of_file.
2023/09/03 21:14:29 [autodj_fallback:3] Switch to switch.4 with forgetful transition.
2023/09/03 21:14:29 [replay_metadata.2259:3] Content type is {audio=pcm(stereo)}.
[mp3float @ 0x7f02c0d5fc00] Could not update timestamps for skipped samples.
2023/09/03 21:14:29 [cue_playlist_jingle_deep_house:3] Cueing in...
2023/09/03 21:14:29 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/100_best_ibiza_deep_house/media/JINGLE DEEP HOUSE/JINGLE 100 BEST - Broadcast High quality music.mp3": {audio=pcm(stereo)}
2023/09/03 21:14:29 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/100_best_ibiza_deep_house/media/JINGLE DEEP HOUSE/JINGLE 100 BEST - Broadcast High quality music.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/09/03 21:14:29 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/100_best_ibiza_deep_house/media/JINGLE DEEP HOUSE/JINGLE 100 BEST - Broadcast High quality music.mp3": {audio=pcm(stereo)}
2023/09/03 21:14:29 [cross:3] Analysis: -47.962473dB / -19.254897dB (2.96s / 3.00s)
2023/09/03 21:14:29 [cross.smart:3] new >= old + margin, old <= medium and new <= high.
2023/09/03 21:14:29 [cross.smart:3] Do not fade if it's already very low.
2023/09/03 21:14:29 [cross.smart:3] Transition: crossed, no fade.
2023/09/03 21:14:29 [source.675:3] Content type is {audio=pcm(stereo)}.
2023/09/03 21:14:29 [audio.add.504:3] Content type is {audio=pcm(stereo)}.
2023/09/03 21:14:29 [cross_after.857:3] Content type is {audio=pcm(stereo)}.
2023/09/03 21:14:29 [buffer.1714:3] Content type is {audio=pcm(stereo)}.
2023/09/03 21:14:29 [cross_before.857:3] Content type is {audio=pcm(stereo)}.
2023/09/03 21:14:29 [buffer.1713:3] Content type is {audio=pcm(stereo)}.
2023/09/03 21:14:29 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/feedback' with body: {
2023/09/03 21:14:29 [lang:3]   "song_id": "6558ba1b7b3817457354f4c52d5b04b7",
2023/09/03 21:14:29 [lang:3]   "playlist_id": "35",
2023/09/03 21:14:29 [lang:3]   "media_id": "36687"
2023/09/03 21:14:29 [lang:3] }
2023/09/03 21:14:29 [lang:3] API nextsong - Response (200): annotate:title="YOU ARE LISTENING 100 BEST IBIZA",artist="100 BEST",duration="4.00",song_id="84a0be094f4fe75caa65733d766feb8d",media_id="36690",playlist_id="35":media:JINGLE DEEP HOUSE/100_best_-_you_are_listening_100_best_ibiza.mp3
2023/09/03 21:14:29 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/100_best_ibiza_deep_house/media/JINGLE DEEP HOUSE/100_best_-_you_are_listening_100_best_ibiza.mp3": {audio=pcm(stereo)}
2023/09/03 21:14:29 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/100_best_ibiza_deep_house/media/JINGLE DEEP HOUSE/100_best_-_you_are_listening_100_best_ibiza.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/09/03 21:14:29 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/100_best_ibiza_deep_house/media/JINGLE DEEP HOUSE/100_best_-_you_are_listening_100_best_ibiza.mp3": {audio=pcm(stereo)}
2023/09/03 21:14:29 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/feedback' with body: {
2023/09/03 21:14:29 [lang:3]   "song_id": "353b2707395e3ad502ff5fc3a60a5e30",
2023/09/03 21:14:29 [lang:3]   "playlist_id": "31",
2023/09/03 21:14:29 [lang:3]   "media_id": "32853"
2023/09/03 21:14:29 [lang:3] }
2023/09/03 21:14:30 [lang:3] API feedback - Response (200): true
2023/09/03 21:14:30 [lang:3] API feedback - Response (200): true
[mp3float @ 0x7f02c0d5fc00] Could not update timestamps for discarded samples.
2023/09/03 21:14:32 [decoder:2] Decoding "/var/azuracast/stations/100_best_ibiza_deep_house/media/JINGLE DEEP HOUSE/100_best_-_ibiza_deep_house_a.mp3" ended: Ffmpeg_decoder.End_of_file.
2023/09/03 21:14:32 [playlist_jingle_deep_house:3] Prepared "/var/azuracast/stations/100_best_ibiza_deep_house/media/JINGLE DEEP HOUSE/JINGLE 100 BEST - Broadcast High quality music.mp3" (RID 1007).
2023/09/03 21:14:32 [switch.4:3] Switch to switch.3 with forgetful transition.
2023/09/03 21:14:32 [replay_metadata.2262:3] Content type is {audio=pcm(stereo)}.
2023/09/03 21:14:32 [next_song:3] Prepared "/var/azuracast/stations/100_best_ibiza_deep_house/media/JINGLE DEEP HOUSE/100_best_-_you_are_listening_100_best_ibiza.mp3" (RID 1008).
2023/09/03 21:14:32 [autodj_fallback:3] Switch to dynamic_startup with forgetful transition.
2023/09/03 21:14:32 [replay_metadata.2263:3] Content type is {audio=pcm(stereo)}.
2023/09/03 21:14:32 [dynamic_startup:3] Switch to cue_next_song.
2023/09/03 21:14:32 [replay_metadata.2264:3] Content type is {audio=pcm(stereo)}.
[mp3float @ 0x7f02c01b7400] Could not update timestamps for skipped samples.
2023/09/03 21:14:32 [cue_next_song:3] Cueing in...
2023/09/03 21:14:32 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/nextsong' with body: 
2023/09/03 21:14:32 [cross:3] Analysis: -18.767246dB / -14.932321dB (1.45s / 1.47s)
2023/09/03 21:14:32 [cross.smart:3] No transition: using default.
2023/09/03 21:14:32 [cross_before.858:3] Content type is {audio=pcm(stereo)}.
2023/09/03 21:14:32 [buffer.1715:3] Content type is {audio=pcm(stereo)}.
2023/09/03 21:14:32 [cross_after.858:3] Content type is {audio=pcm(stereo)}.
2023/09/03 21:14:32 [buffer.1716:3] Content type is {audio=pcm(stereo)}.
2023/09/03 21:14:32 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/feedback' with body: {
2023/09/03 21:14:32 [lang:3]   "song_id": "6558ba1b7b3817457354f4c52d5b04b7",
2023/09/03 21:14:32 [lang:3]   "playlist_id": "35",
2023/09/03 21:14:32 [lang:3]   "media_id": "36687"
2023/09/03 21:14:32 [lang:3] }
2023/09/03 21:14:32 [lang:3] API feedback - Response (200): true
2023/09/03 21:14:32 [lang:3] API nextsong - Response (200): annotate:title="Feel Shine",artist="Cary Summer",duration="283.00",song_id="fe3a98633c202a851caf3be46d9ccc39",media_id="87857",playlist_id="32":media:DEEP HOUSE 2022 - 2023/Cary Summer - Feel Shine.mp3
2023/09/03 21:14:32 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/100_best_ibiza_deep_house/media/DEEP HOUSE 2022 - 2023/Cary Summer - Feel Shine.mp3": {audio=pcm(stereo)}
2023/09/03 21:14:32 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/100_best_ibiza_deep_house/media/DEEP HOUSE 2022 - 2023/Cary Summer - Feel Shine.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}, video: {codec: mjpeg, 800x800, yuvj420p}
2023/09/03 21:14:32 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/100_best_ibiza_deep_house/media/DEEP HOUSE 2022 - 2023/Cary Summer - Feel Shine.mp3": {audio=pcm(stereo)}
2023/09/03 21:14:34 [metadata_map.3:3] Inserting missing metadata.
2023/09/03 21:14:34 [metadata_map.5:3] Inserting missing metadata.
2023/09/03 21:14:34 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/feedback' with body: {
2023/09/03 21:14:34 [lang:3]   "song_id": "84a0be094f4fe75caa65733d766feb8d",
2023/09/03 21:14:34 [lang:3]   "playlist_id": "35",
2023/09/03 21:14:34 [lang:3]   "media_id": "36690"
2023/09/03 21:14:34 [lang:3] }
2023/09/03 21:14:34 [lang:3] API feedback - Response (200): true
[mp3float @ 0x7f02c01b7400] Could not update timestamps for discarded samples.
2023/09/03 21:14:35 [decoder:2] Decoding "/var/azuracast/stations/100_best_ibiza_deep_house/media/JINGLE DEEP HOUSE/100_best_-_you_are_listening_100_best_ibiza.mp3" ended: Ffmpeg_decoder.End_of_file.
2023/09/03 21:14:35 [next_song:3] Prepared "/var/azuracast/stations/100_best_ibiza_deep_house/media/DEEP HOUSE 2022 - 2023/Cary Summer - Feel Shine.mp3" (RID 1009).
[mp3float @ 0x7f02c0dbd900] Could not update timestamps for skipped samples.
2023/09/03 21:14:35 [cue_next_song:3] Cueing in...
2023/09/03 21:14:35 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/nextsong' with body: 
2023/09/03 21:14:35 [cross:3] Analysis: -22.139242dB / -32.785580dB (2.98s / 2.98s)
2023/09/03 21:14:35 [cross.smart:3] No transition: using default.
2023/09/03 21:14:35 [cross_before.859:3] Content type is {audio=pcm(stereo)}.
2023/09/03 21:14:35 [buffer.1717:3] Content type is {audio=pcm(stereo)}.
2023/09/03 21:14:35 [cross_after.859:3] Content type is {audio=pcm(stereo)}.
2023/09/03 21:14:35 [buffer.1718:3] Content type is {audio=pcm(stereo)}.
2023/09/03 21:14:35 [lang:3] API nextsong - Response (200): annotate:title="Why Do I? - 2021",artist="Vavo / nicopop. / Zohara",duration="172.00",song_id="8671499c4d848974b27e283d27876544",media_id="89029",playlist_id="2":media:DEEP HOUSE 2021/Vavo  nicopop.  Zohara - Why Do I - 2021.mp3
2023/09/03 21:14:35 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/100_best_ibiza_deep_house/media/DEEP HOUSE 2021/Vavo  nicopop.  Zohara - Why Do I - 2021.mp3": {audio=pcm(stereo)}
2023/09/03 21:14:35 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/100_best_ibiza_deep_house/media/DEEP HOUSE 2021/Vavo  nicopop.  Zohara - Why Do I - 2021.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}, video: {codec: mjpeg, 800x800, yuvj420p}
2023/09/03 21:14:35 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/100_best_ibiza_deep_house/media/DEEP HOUSE 2021/Vavo  nicopop.  Zohara - Why Do I - 2021.mp3": {audio=pcm(stereo)}
2023/09/03 21:14:38 [metadata_map.3:3] Inserting missing metadata.
2023/09/03 21:14:38 [metadata_map.5:3] Inserting missing metadata.
2023/09/03 21:14:38 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/feedback' with body: {
2023/09/03 21:14:38 [lang:3]   "song_id": "fe3a98633c202a851caf3be46d9ccc39",
2023/09/03 21:14:38 [lang:3]   "playlist_id": "32",
2023/09/03 21:14:38 [lang:3]   "media_id": "87857"
2023/09/03 21:14:38 [lang:3] }
2023/09/03 21:14:38 [lang:3] API feedback - Response (200): true
[mp3float @ 0x7f02c0dbd900] Could not update timestamps for discarded samples.
2023/09/03 21:19:18 [decoder:2] Decoding "/var/azuracast/stations/100_best_ibiza_deep_house/media/DEEP HOUSE 2022 - 2023/Cary Summer - Feel Shine.mp3" ended: Ffmpeg_decoder.End_of_file.
2023/09/03 21:19:19 [next_song:3] Prepared "/var/azuracast/stations/100_best_ibiza_deep_house/media/DEEP HOUSE 2021/Vavo  nicopop.  Zohara - Why Do I - 2021.mp3" (RID 1010).
[mp3float @ 0x7f02c0dbc000] Could not update timestamps for skipped samples.
2023/09/03 21:19:19 [cue_next_song:3] Cueing in...
2023/09/03 21:19:19 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/nextsong' with body: 
2023/09/03 21:19:19 [cross:3] Analysis: -162.130475dB / -20.985439dB (2.99s / 3.01s)
2023/09/03 21:19:19 [cross.smart:3] new >= old + margin, old <= medium and new <= high.
2023/09/03 21:19:19 [cross.smart:3] Do not fade if it's already very low.
2023/09/03 21:19:19 [cross.smart:3] Transition: crossed, no fade.
2023/09/03 21:19:19 [source.676:3] Content type is {audio=pcm(stereo)}.
2023/09/03 21:19:19 [audio.add.505:3] Content type is {audio=pcm(stereo)}.

**Comment by IrcXchat** [comment]
Change your Crossfade Method to normal mode in station profile.
