### ISSUE TITLE
issue with time in the calendar

### ISSUE THREAD

**Issue by 01123581321345589144233** [AzuraCast/AzuraCast#6580]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

v0.19.1 Stable • Docker • PHP 8.2

### What happened?

Hi, i can see after my last update and switch to stable are there visuelle issue's in the calendar an the frontend.
You can see this here 432hz.dk the history and the calender are not viewing the correct time.
we have 10:00 and the calender and the history views (playes from 9hours) and the calender time is 18:30
timezone is Berlin

**Comment by wegGehamstert** [comment]
Can you maybe provide us a screenshot? 
For me, this issue is not here.
