### ISSUE TITLE
The interface is not centered after the update

### ISSUE THREAD

**Issue by MajesticUniverse** [AzuraCast/AzuraCast#6583]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #6c27dfb (2023-08-30 12:20)

### What happened?

On mobile devices, after the update, it shifted to the left side: the authorization menu and the public page, what could be the reason and how can this be solved?

![telegram-cloud-photo-size-2-5447172894439361830-y](https://github.com/AzuraCast/AzuraCast/assets/108705888/d63b53c1-de0d-47a1-a147-180321302c1f)

![telegram-cloud-photo-size-2-5447172894439361831-y](https://github.com/AzuraCast/AzuraCast/assets/108705888/4e9fc0a3-3dbf-48d9-bd09-b647d70142d9)

**Comment by MajesticUniverse** [comment]
Обновился до Rolling Release #c205487 (2023-09-01 17:41), проблема сохраняется.

**Comment by netbladenl** [comment]
Same problem with two android devices and samsung browsers.

**Comment by MajesticUniverse** [comment]
Reinstalled Linux and AzuraCast, it doesn't solve the problem, most likely it's in the latest version, now the release is: Rolling Release #aa0ca7f (2023-09-18 7:30)
Maybe you can temporarily fix it through CSS, who knows how to do it?
