### ISSUE TITLE
Menu for adding songs to playlists closes after each click.

### ISSUE THREAD

**Issue by wegGehamstert** [AzuraCast/AzuraCast#6584]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#c205487 

### What happened?

Since the UI update, the menu where you can select which playlist the song should be in, closes after every click. If you have selected a field, then you still have to open the window again to click "Save".  The only moment it don't closes, is when exactly the checkbox is aimed.

### Expected behavior:
- The window remains open until "Save" is pressed. 

https://github.com/AzuraCast/AzuraCast/assets/78315888/4897bcd1-ce70-46dd-90fa-c09a3ce8776e

**Comment by meintobi** [comment]
yes, me too. and many other bugs after that update :(

**Comment by BusterNeece** [comment]
> yes, me too. and many other bugs after that update :(

Not helpful!

**Comment by extobi** [comment]
If i click in the Media Folder on Playlists and change any checked or unchecked Playlist, the Popup Window is closing.

**Comment by wegGehamstert** [comment]
Still not fixed.
