### ISSUE TITLE
Can no longer change the login-content background

### ISSUE THREAD

**Issue by renatopinto89** [AzuraCast/AzuraCast#6586]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.1 Stable

### What happened?

After the latest Stable Update I can no longer use the CSS Code to change the login pages background
This code no longer works, what can I do? 

[data-theme] body.login-content {
    background: #edecec url(https://XXXX);
    background-size: cover;
    background-attachment: fixed;
}

Thank you so much for this amazing project
Kind Regards

**Comment by BusterNeece** [comment]
@renatopinto89 Just change `[data-theme]` to `[data-bs-theme]` and it should work. This change was necessary because of the upgrade to the latest Bootstrap version under the hood.

**Comment by renatopinto89** [comment]
@BusterNeece Thank you so much. That did the trick

**Comment by renatopinto89** [comment]
Hi everyone

After updating AzuraCast to 0.19.4, I cannot change the the login pages background again
This code no longer works, what can I do?

[data-bs-theme] body.login-content {
    background: #edecec url(https://XXXX);
    background-size: cover;
    background-attachment: fixed;
  
}

Thank you so much for this amazing project
Kind Regards
