### ISSUE TITLE
Starting/Stopping audio, including changing mountpoints, anywhere in the application freezes and crashes the browser

### ISSUE THREAD

**Issue by MarkWasley** [AzuraCast/AzuraCast#6587]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #1e6306b (2023-09-03 18:05)

### What happened?

There's not much more to say about this bug that has recently surfaced, but it needs investigation and it's critical that it's resolved.

**Comment by BusterNeece** [comment]
There's plenty else you could say if you want this to get resolved quickly! Like, what browser and OS are you using? Do you see any console error logs when it happens? Are you on a development or production instance?

**Comment by MarkWasley** [comment]
Sorry, I would have included this information if I thought it would help. I've tested with three different devices, a Windows 11 desktop PC, Windows 10 laptop and Android 13 mobile, on the demo and my production instance. I've tried Chrome and Edge browsers and with my broadband and mobile data connection. All produce the same bug. There are no console error logs.

**Comment by boerdb** [comment]
Installation Method

Docker Installation

AzuraCast Release Channel

Rolling Release Channel

Current AzuraCast Version

Rolling Release #1e6306b (2023-09-03 18:05)


I have the same problem, browser (Safari and Edge ) is freezing after play button is pressed . Only a page refresh stops freezing

**Comment by paulcjkp** [comment]
Rolling release #[c205487]

https://altrockradio.icu/public/cjkp_db here's an example public page.  Clicking play works fine, but once the audio is playing, switching streams or hitting stop, the audio stops and freezes all tabs, not just the player.  Choosing a different stream, the music plays, but tabs are frozen again.

Windows 10, Firefox, Chrome, and Brave.  No console errors.

**Comment by BusterNeece** [comment]
The issue has been found and is fixed in the latest Rolling Release deploying right now. Thanks everyone for their patience.
