### ISSUE TITLE
Podcast "download " option missing on Firefox

### ISSUE THREAD

**Issue by ChandigarIT** [AzuraCast/AzuraCast#6588]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.19.1 Stable - Docker - PHP 8.2

### What happened?

When viewing a podcast's "View Details" page in Chrome on a Mac, there is a "treble-dot" menu button that gives access to an option to download the show to your device, also a playback speed option.

![on a mac](https://github.com/AzuraCast/AzuraCast/assets/108827431/0f5d6749-9b7e-432c-a84e-c54629725a10)

![Mac2](https://github.com/AzuraCast/AzuraCast/assets/108827431/c4c7b385-0c92-4659-b52e-1140b1e876de)

On Chrome/Android, there is only the playback speed option, no download.

On Firefox/Linux, the "treble-dot" menu button is completely missing.

![on Firefox](https://github.com/AzuraCast/AzuraCast/assets/108827431/59f12c53-7f33-4aeb-aaca-e161033632cb)

**Comment by BusterNeece** [comment]
The audio player control on the podcasts page is the browser's native control. We don't implement our usual media player on the Podcasts page currently, but we can look into doing that. It might be better to post this as a suggestion over at https://features.azuracast.com/

**Comment by ChandigarIT** [comment]
Many thanks for your response.
