### ISSUE TITLE
Now Playing stuck on same song

### ISSUE THREAD

**Issue by czmilosz** [AzuraCast/AzuraCast#659]
When I attempt to manually sync the "Now Playing" data I receive the following error:

ERROR: Argument 1 passed to AppProxy\__CG__\Entity\StationMedia::api() must be an instance of App\Url, instance of AzuraCast\ApiUtilities given, called in /var/azuracast/www/app/src/Entity/SongHistory.php on line 480

Additional info:

I've run both cache:clear and sync:run nowplaying

Same result.

**Comment by czmilosz** [comment]
Additional info:

I've run both cache:clear and sync:run nowplaying

Same result.

**Comment by SlvrEagle23** [comment]
@czmilosz The auto-updater should be generating updated proxy classes on its own, but in case it isn't, the solution to this is to run `orm:generate-proxies`, and likely then clear the cache again for good measure. Try that and let me know if it works.

**Comment by czmilosz** [comment]
SlvrEagle23 - I never did get this to work.  I ended up doing a full reinstall and that seemed to fix my issues.

Sorry for the delay in response and thanks for your help!
