### ISSUE TITLE
Record Not Found

### ISSUE THREAD

**Issue by kevinwilliams123** [AzuraCast/AzuraCast#6593]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Report Not Found keeps flashing up in red box but server seems to be fine ?

**Comment by BusterNeece** [comment]
Don't make one-sentence reports like this. Include screenshots, check your browser's inspect console (F12) to see if there are errors, let us know *what page you're on* when seeing things, etc.

**Comment by kevinwilliams123** [comment]
![record not found](https://github.com/AzuraCast/AzuraCast/assets/144227275/6bcb24b1-1a67-4013-952a-aa6467729b21)

**Comment by kevinwilliams123** [comment]
This occurs on every page record not found and also when embedded on website it appears on the polayer and the playlist.

**Comment by kevinwilliams123** [comment]
And Now Azuracast Mira Server Has Gone Down ??????????

**Comment by BusterNeece** [comment]
I see. You're using a reseller. You need to take this up with the reseller's support channels, not our GitHub Issues section.
