### ISSUE TITLE
Azuracast Mira Server Is Down

### ISSUE THREAD

**Issue by kevinwilliams123** [AzuraCast/AzuraCast#6599]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Unable to connect

An error occurred during a connection to mira.streamerr.co.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.

**Comment by BusterNeece** [comment]
That's a reseller. Don't file issues with a reseller's instance on this repository.
