### ISSUE TITLE
Live broadcast doesn't override remote playlist

### ISSUE THREAD

**Issue by joshms123** [AzuraCast/AzuraCast#6600]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 • Rolling Release #d769b66 (2023-08-29 15:21) • Docker • PHP 8.2

### What happened?

When broadcasting to the harber input while automation is playing a remote playlist, it connects and the page shows that we are live; however, the remote playlist just continues to play.
Stopping the remote playlist stream falls back to the live; and resuming the remote stream doesn't interrupt the live, so that suggests its in the connection phase.
Recording also starts and stops.

**Comment by expert-geeks** [comment]
Same issue on rolling release Rolling Release #[919e9b5] (2023-09-05 19:22) • Docker • PHP 8.2

**Comment by Moonbase59** [comment]
Related: https://github.com/AzuraCast/AzuraCast/issues/6344

**Comment by joshms123** [comment]
Just want to note down my ideas.
From reviewing the LS code, it seems that when we get a live connection, we call source.skip.
However, I'm assuming, skipping will do nothing on the live stream.
I believe this may cause the fallback to stay on the auto DJ, as track_sensitive defaults to true and we don't define that on the live fallback, so we can handle the skip and such.
These are just my ideas; someone who is more EXPERIENCED may wish to look into this.
Thanks.

**Comment by BusterNeece** [comment]
@joshms123 Good catch. That may be exactly what's going on. Not sure why that *used to* work and doesn't now, though, but it's likely we'll have to look into how we handle the DJ transition so it's not track sensitive. Will investigate shortly.

**Comment by BusterNeece** [comment]
@joshms123 Looking into it further, and it looks like our live fallback just didn't have the `track_sensitive` flag specified at all, which means it now defaults to `true`. Whether it used to do that isn't clear, but either way it's better for us to explicitly specify it in this case so we're sure of the behavior. I've explicitly set it to `false`, so the transition should always kick in and be immediate for live DJs as the top-priority thing.
