### ISSUE TITLE
Request page shows there are no songs found.

### ISSUE THREAD

**Issue by NeddyPlays** [AzuraCast/AzuraCast#661]
For some kind of strange reason the Request page shows there are now songs found. How can i fix this?

**Comment by JustIrinel** [comment]
Hi, from what I saw on my Azuracast server, on the playlist you have an option that says if you want to use the songs on the request page, or something like this. Find it and turn it ON ! Also be sure that the playlist is live and running.

**Comment by NeddyPlays** [comment]
Its turned on. And the playlist is running.

**Comment by JustIrinel** [comment]
Leave a link here from the public page :)

**Comment by NeddyPlays** [comment]
https://listen.thisisqhr.co.uk/public/this_is_qhr

**Comment by SlvrEagle23** [comment]
@NeddyPlays It appears there's an HTTP 500 error happening with this page:
https://listen.thisisqhr.co.uk/api/station/1/requests

Can you check the logs on your end and see what the error is?

**Comment by NeddyPlays** [comment]
I can see more .log files what one do i need?

**Comment by SlvrEagle23** [comment]
@NeddyPlays If you're on the traditional install, try `/var/azuracast/www_tmp/php_errors.log`. If you're on Docker, try `docker-compose logs -f web`.

**Comment by NeddyPlays** [comment]
Ok will do it when there is no DJ on air. Cause i have the SFTP running at the moment and can't seem to get that off with DigitalOcean somehow.

**Comment by NeddyPlays** [comment]
![image](https://user-images.githubusercontent.com/37535577/42751729-fb3527da-88eb-11e8-8874-64828d151f3e.png)

**Comment by SlvrEagle23** [comment]
@NeddyPlays The system was not originally built or optimized to handle nearly that many songs. Basically, it was loading all requestable songs into memory before sorting and showing them, which was obviously significantly overflowing your available memory on your system.

I've had to rewrite significant portions of the underlying routing system to make it possible, but requests are now paginated far more intelligently, only loading from the database the records that are currently visible.

Please update your AzuraCast installation and let me know if this resolves the issue.

**Comment by SlvrEagle23** [comment]
Closing this issue as the entire requests API has been overhauled dramatically to properly paginate requests, significantly reducing the amount of memory that can be occupied by one given request. If you run into issues with the new requests API, feel free to create a new issue.
