### ISSUE TITLE
Time announcement from remote URL

### ISSUE THREAD

**Issue by paavalan** [AzuraCast/AzuraCast#6615]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.1

### What happened?

I'm experiencing an issue with AzuraCast and Liquidsoap. I've set up a time announcement that fetches audio from an HTTP source (http://helix-time-xmywojz7ta-as.a.run.app/speak). The problem I'm facing is a delay of about 1-2 seconds before the time announcement audio starts playing, even though the original source doesn't have this delay.

I've tried several solutions, including adjusting buffering and attempting to trim any potential silence, but the delay persists. My goal is to have the time announcement play immediately without any noticeable delay.

Any insights, suggestions, or recommendations would be greatly appreciated! Thank you in advance.

```
def fetch_time_announcement() =
current_time = mksafe(input.http("http://helix-time-xmywojz7ta-as.a.run.app/speak"))
drop_metadata(current_time)
end

radio = rotate(weights=[3,1],[radio, fetch_time_announcement()])
```

**Comment by BusterNeece** [comment]
This delay may just be inherent in the media streaming software being used...Icecast incorporates a small delay into the broadcast, and HLS also has a small delay as browsers catch up with the supplied files.
