### ISSUE TITLE
GoogleCast: change CORS type

### ISSUE THREAD

**Issue by dabclassic-o** [AzuraCast/AzuraCast#6624]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

For Google Cast support, according to this specification, 
https://developers.google.com/cast/docs/media/streaming_protocols?hl=en#segment_format_support

content-type: application/vnd.apple.mpegurl needs to be changed to application/x-mpegurl
loadRequestData.media.contentType = 'application/x-mpegurl';

**Comment by BusterNeece** [comment]
Assuming the commit from Oct 7 fixed it.
