### ISSUE TITLE
The station goes offline when the remote playlist is played.

### ISSUE THREAD

**Issue by iRealDream** [AzuraCast/AzuraCast#6627]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

When a remote playlist is played, two problems occur:

- The station goes offline, but the playlist is playing and the sound of the remote playlist comes from the public page. The URL type is Icecast/Shoutcast Stream URL.
- At the same time, the streamer from the Web DJ page cannot play anything from the microphone or playlists 1 and 2, but on the public page, the word live appears along with the name of the streamer, and the radio continues to play the remote playlist.

**Comment by BusterNeece** [comment]
I've made some changes to the Rolling Release version that should fix both of these issues. Updating to the latest Rolling Release is recommended in this case; a stable release will be tagged in the future that includes these fixes.
