### ISSUE TITLE
Search is case sensitive

### ISSUE THREAD

**Issue by muzo178** [AzuraCast/AzuraCast#663]
When searching for songs, case is case sensitive. 

Searching for **supermayer** returns No results but searching for **Supermayer** returns ie _Supermayer - The Lonesome King_

I think search should be case _insensitive_

**Comment by SlvrEagle23** [comment]
@muzo178 I do agree with you that search should be case-insensitive, but this is actually oddly enough a side-effect of your other bug report about searches taking too long. I offloaded the string comparison functionality to the database itself, which speeds it up significantly but also means it's beholden to the database's quirkiness, in this case its case-sensitivity. I'll look into it and see if there's a way to get around it, but there may not be an easy one.

**Comment by SlvrEagle23** [comment]
@muzo178 This has been fixed by the latest update, which changes the MariaDB collation of the database to `utf8mb4_general_ci`, which returns case-insensitivity to the search results.
