### ISSUE TITLE
Memory raises until server is full

### ISSUE THREAD

**Issue by Zagrthos** [AzuraCast/AzuraCast#6630]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #aa0ca7f (2023-09-18 7:30)

### What happened?

Today in the morning (1-2 AM CEST) our server went out of memory (4GB RAM) because Liquidsoap just didn't stopped claiming memory for itself and didn't released it again. The CPU usage went to full 100% and the Disk has written everything in swap.

We have two stations running parallel and after 4 days or so the RAM usage is so high we have to restart the container or the thing mentioned happens.

Is this a known bug, already fixed or not?
If you need logs, please tell me and I try to get them.

**Comment by amacleod457** [comment]
Seeing something similar on  • Rolling Release #546e1ce (2023-10-07 16:53) • Docker • PHP 8.2 after around two-four hours of Azuracast working, playing, and behaving. Then things just run-away with the memory and CPU until everything is practically locked up and nothing works. The app log just shows a bunch of 400 errors over and over again. Centrifugo seems to be chewing a fair bit of resources as well, and host system CPU spikes on SY, WA, and ST percentages. Unfortunately, the two times I caught my instance in this state, the web interface was useless, audio was playing the hissing sound thing that means things are broken, and system was so loaded, it was taking 30 secondds per shell command to do anything, so pulling teeth would be easier than pulling logs at that point. The instance is running on a quad-core, 4 GB RAM VPS that formerly ran the same workload for years with total stability on stable with the latest in use prior of 0.18.5.

**Comment by amacleod457** [comment]
Looks like it was Liquidsoap that was running away with the CPU and RAM after several hours of operation on rolling releases from 2023-10-07 and 2023-10-08.
Interestingly, i have two other machines with more than 4 GB of rAM, running multiple stations, that do not experience this. Just a guess that something in recent Liquidsoap requires more than the recommended 4 GB of rAM.

I am certainly thankful for the rollback feature recently implemented.
For anyone experiencing the runaway issue on recent rolling releases, and nothing you do fixes it, and if you have a database backup from a recent stable, like 0.18.5:
log into your Azuracast host via ssh
cd /var/azuracast
./docker.sh rollback 0.18.5
Once it is complete, do:
./docker.sh restore /path/to/backup-of-0.18.5-stations.zip
Where the path and file name must be modified to where you have your Azuracast backup from the version that you've rolled back to.

This is a great project, by lots of dedicated and talented volunteers of teams and programmers. It just has lots of working parts that don't always play nice together. But with features like rollback, it can be brought to a working state for production use.

**Comment by Zagrthos** [comment]
Server runs fine now - deactivated the feature that liquidsoap calculates the song dB for each song before playing it.

**Comment by mishcazzulani** [comment]
how did you deactivate it?

**Comment by Zagrthos** [comment]
Look at this guide:
https://www.azuracast.com/docs/help/optimizing/#disable-replaygain-or-pre-calculate-replaygain-for-audio-files
