### ISSUE TITLE
Cannot manually backup on Rolling Release

### ISSUE THREAD

**Issue by renatopinto89** [AzuraCast/AzuraCast#6634]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #e1300ed

### What happened?

Hi everyone

When I try to do a manual backup through the dashboard, clicking the "Run Manual Backup" does nothing

Kind regards

**Comment by hyperbrute** [comment]
same issue here !
thanks
