### ISSUE TITLE
[Rolling Release] Some features not working

### ISSUE THREAD

**Issue by FleuryK** [AzuraCast/AzuraCast#6636]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #e1300ed (2023-09-26 15:16)

### What happened?

Hello Azuracast Team,

Since few versions for rolling release, some features not working:

- Button "Run Manual Backup" not work (issue #6634 open yesterday by [renatopinto89](https://github.com/renatopinto89))
- For listen a music from web interface, time indicated on the top right is not correct
- For another language (French in my case), some words are correctly translated, others not

For language, French in my case, the file is translated at 100%.

Can you fix these problems?

I'm running Rolling Release #e1300ed (2023-09-26 15:16).

**Comment by BusterNeece** [comment]
@FleuryK The first issue should be fixed now in the latest Rolling Release.

If you want to make corrections or changes to our translations, you can do so at https://translate.azuracast.com/

For the second item, you mention the time indicated on the top right is incorrect...what do you mean?

**Comment by LordHelmchen666** [comment]
I must agree with FleuryK there is something going wrong with translation. For example this is in de_DE.-uTF-8 default.po
```
#: vue/components/Admin/Stations.vue:124
#: vue/components/Admin/Stations/Form/FrontendForm.vue:3
#: vue/components/Stations/menu.ts:222
msgid "Broadcasting"
msgstr "Übertragen"
```
I set language in my account to German, but in Dashboard it show "Broadcasting" instead  of "Übertragen"

**Comment by FleuryK** [comment]
For this "For listen a music from web interface, time indicated on the top right is not correct" :
Short video joined for explain:

https://github.com/AzuraCast/AzuraCast/assets/6574104/079e117e-e830-4ab9-b3d4-d9eaac2b21ce

**Comment by BusterNeece** [comment]
We found and fixed the problem with translations in the app. Things are updated and working again in the latest Rolling Release version. Thanks for your patience!
