### ISSUE TITLE
SoundExchange report is not generating expected output

### ISSUE THREAD

**Issue by everettmarshall** [AzuraCast/AzuraCast#6637]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.1 PHP 8.2

### What happened?

Our music database contains about 4,000 songs and broadcasts 24/7.

When running a SoundExchange report, I select a date range and click "generate report" button.

The output is a .TXT file and the contents of the file appears to only contain header information - with the exception of ONE song title. (Because I do not know what data the file should contain, I do not know if the headers are incomplete.)

Viewing the file in Text Edit (Mac) and some other simple text viewer apps. I have also opened in Excel and Numbers, as well as Chrome, Safari, and Firefox - there is no additional data. 

Also, there is no difference in the output when enabling the "Attempt to Automatically Retrieve ISRC When Missing." 

Our music metadata may be incomplete but I expected to see more data. The filesize is only 244 bytes so I feel that Azura is not running a complete report.

Any assistance is appreciated.

THX

**Comment by slyderc** [comment]
I am seeing the same results for "LIVE" streaming broadcasts - when a remote DJ connects to broadcast and updates their playlist metadata during the show - and these plays don't show up in the report.  It looks like AutoDJ playouts are reporting correctly, however.

**Comment by BusterNeece** [comment]
@slyderc I suspect that's a separate issue, though I already see a different GitHub issue created for it, so we can address that there.

@everettmarshall I'm having trouble reproducing this on my end. When I select a date range, it generates an appropriate report for that window. Do you have any settings that may be affecting this, i.e. are you on a non-English locale, is your browser using a different date format than mm/dd/yyyy, are you tracking live broadcasts or AutoDJ broadcasts?
