### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#664]
**Installation method**
Indicate whether you are using the "Docker" or "Traditional" installation method.
Traditional
**Host OS (for Docker installations)**
Indicate what your host operating system is (i.e. Ubuntu 16.04, MacOS High Sierra, Windows 10), if you're using the Docker installation method.
Openvz, Ubuntu 16.04
**Describe the bug**
After i Configure the mount point an open the station profile, i get this error: "
```
500
Argument 2 passed to Monolog\Logger::error() must be of the type array, object given, called in /var/azuracast/www/app/src/AzuraCast/Radio/Frontend/FrontendAbstract.php on line 183
Logger.php : 614
```
"
**Screenshots**
If applicable, add screenshots to helpexplain your problem.

http://imgur.com/iwUvRCpl.png

**Desktop (please complete the following information):**
Firefox Mxlinux

I use remote mountpoint, i have the error only after adding the remote server.

**Comment by JustIrinel** [comment]
Usually 500 errors are due tot bypass the resources that you have on the server, or due to a wrong htaccess config. You can try download azuracast and maybe replace that file, but I don't think is the  solution.

**Comment by preterive** [comment]
I also have done this.

**Comment by SlvrEagle23** [comment]
@preterive I'll take a look. Looks like a simple problem on the code end.

@JustIrinel This is not always accurate. AzuraCast in particular uses nginx, and does not use .htaccess rules in its processing. 500 errors are likely due to an exception or error thrown in the code, and should definitely be reported as issues here.

**Comment by SlvrEagle23** [comment]
@preterive I've updated the exception handler for this functionality to properly handle issues. You'll want to update and see what the actual error message is that it's returning.

**Comment by preterive** [comment]
Okay, Herr the error: ```
500
Client error: `GET http://alles-radio4.stream.laut.fm:8080/status-json.xsl?mount=/alles-radio4` resulted in a `404 Not Available` response: Could not parse XSLT file 
FrontendAbstract.php : 183
```

This is normal because the server don't have any XSL Files, because this is only a server for live sreaming. The listeners listen to another audio server with other software.

**Comment by SlvrEagle23** [comment]
@preterive Currently there is no way to specify that nowplaying data should be pulled from a different URL than the one listeners actually connect to, so without a corresponding `status-json.xsl` file on that Shoutcast instance, AzuraCast won't be able to pull any listener counts or other data, and won't be particularly useful.

There's an enhancement request to allow AzuraCast to use customized remote URLs, but until this is complete, this will continue to error out like that as a result.

**Comment by preterive** [comment]
Hello, there is no status-json.xsl on all servers because we have to use a streams server from our advertiser rms.de with idividual ads, only 1 prestream ad per user and many more.
Is there no option to take the statics of or use our own api, wich provides a simple 1 line text with the current listeners?

**Comment by SlvrEagle23** [comment]
@preterive I believe you already created a second issue asking that exact question, and that's what I'm referring to when I say there's an existing enhancement request to add that functionality. Currently, we're expecting that our users are either working with the Shoutcast/Icecast instance that we provide them, or that they're working with standard versions of either software that will provide the requisite URLs needed to pull detailed metadata.

Even if we were to allow a custom URL for metadata, it would likely have to be a specific, known format, as we can't just guess what the data coming in represents (listeners, current song, etc). In other words, a one-line response with just the listener count wouldn't make any sense to the parser, and the response would need to be structured JSON with the necessary fields included.

**Comment by preterive** [comment]
Hello,
Please have a look there http://api.laut.fm and there https://github.com/lautde/lautfm_js_tools @lautde 
http://api.laut.fm/doc and this is an example url: http://api.laut.fm/station/alles-radio

**Comment by SlvrEagle23** [comment]
@preterive I'll take a look, but I can't promise interoperability with every third party service. A majority of AzuraCast is modular enough to support these things, but not all sections of the system are.

If I may ask, what is the value in adding AzuraCast to a setup where you already have your AutoDJ and broadcasting managed by another system, that appears to be serving its own API as well?

**Comment by preterive** [comment]
Hello,
Laut.fm is a page there everyone can create a own radio station. Laut.fm pay all license fees like gema and play ads. Laut.fm have a not really good own autodj. Only 128 kb/s mp3 and no crossfading, clock, only one dj login ...

Now, i block all conect to icecast from outside, then i stream to a internal icecast server with azuracast and then, i restream this signal with liqudisoap.

**Comment by SlvrEagle23** [comment]
@preterive I understand. At the moment, it's likely that you'll just have to use AzuraCast for tracking the Icecast instance that it manages internally, as it won't understand the API of Laut.fm. I will look into this as a possible area for modular expansion in the future.

**Comment by preterive** [comment]
I work on a improvement. The most is finished.

**Comment by preterive** [comment]
https://pastebin.com/BPMGZkB9
