### ISSUE TITLE
Station displays itself as offline even if it's online

### ISSUE THREAD

**Issue by Zagrthos** [AzuraCast/AzuraCast#6642]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #0791831 (2023-10-01 5:33)

### What happened?

We have a station which is only sometimes online so we can save server resources. But every time when we activate it and join in through the stream URL the web display shows it as "Station Offline" but it isn't. The music is playing correctly, the playlist behaves as it should, the services are online as expected and everything works.

We disable the station through "Edit Profile" -> "Administration" -> "Enable Broadcasting" - is this the wrong way or the correct one?

I'll attach a picture:
![Screenshot 2023-10-02 at 17-38-08 Sellara](https://github.com/AzuraCast/AzuraCast/assets/36556009/355829b3-c8c9-4c61-871b-6c72dfe5058b)

**Comment by Zagrthos** [comment]
Got fixed with #1ea88fe

**Comment by apopovski72** [comment]
Can you please provide the link to   #1ea88fe .  Cannot find it.

**Comment by apopovski72** [comment]
Thank you BusterNeece.  I have no idea on what release I am honestly.  I just installed azuracast via docker and have bunch of issues trying to figure it out. Let me check how to update azuracast and which release I am using.  Thank you again. Alex

**Comment by BusterNeece** [comment]
@apopovski72 https://www.azuracast.com/docs/getting-started/updates/#for-docker-installations

**Comment by Jkudjo** [comment]
I realised this can be changed from the Branding settings.
