### ISSUE TITLE
Listener number from own api

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#665]
**Is your feature request related to a problem? Please describe.**
I use more than one Server and i reboroadcast. 
I have a own api for listeners, and i want to use it. 
I could give the number on a simple 1 line php page.

**Comment by SlvrEagle23** [comment]
I believe this problem can now be solved by the plugin architecture. Outside the plugin architecture, we don't want to allow custom PHP to be input in any way via the web interface for security reasons.
