### ISSUE TITLE
Songs with long names are duplicated in metadata

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#6657]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.1

### What happened?

I noticed that in the latest updates, when the song name is long, the duplicate name is displayed in the metadata with a semicolon separating it. The attached image shows what happens. This happens in both Shoutcast and Icecast.

![Shoutcast-Server](https://github.com/AzuraCast/AzuraCast/assets/58113324/0f72a6ee-3511-46aa-a132-f1ba68dc392a)

![Screenshot 2023-10-12 at 16-19-13 Radio Estudio 76-crop](https://github.com/AzuraCast/AzuraCast/assets/58113324/a0364ad9-1fb9-491e-a5cb-6cabd783b63b)
![Radio-Estudio-76](https://github.com/AzuraCast/AzuraCast/assets/58113324/8d48613b-7a99-47ce-9612-beee00d05596)

**Comment by Sweetness2k** [comment]
I have that same issue also.

**Comment by Moonbase59** [comment]
Could you check if _one_ of the dups is shorter, i.e. a max of 30 characters?

That could indicate you have multiple tags in yout files, and can happen when you use _both_ ID3v1/ID3v1.1 _and_ ID3v2.x tags. _(Hint: Get rid of all ID3v1, ID3v1.1, ID3v2.2 tags—nobody needs them anymore and they’re troublemakers.)_

**Comment by roger-net** [comment]
> Could you check if _one_ of the dups is shorter, i.e. a max of 30 characters?
> 
> That could indicate you have multiple tags in your files, and can happen when you use _both_ ID3v1/ID3v1.1 _and_ ID3v2.x tags. _(Hint: Get rid of all ID3v1, ID3v1.1, ID3v2.2 tags—nobody needs them anymore and they’re troublemakers.)_
> 
> Just an idea, though.

Hello my friend. The tags are correct, I edit them one by one myself. This issue did not occur in previous versions of Azuracast.

**Comment by Moonbase59** [comment]
Odd, doesn’t happen here, **but I found another bug:** Long titles are actually **cut off** by AzuraCast! Shouldn’t happen, especially classical music can have real long title tags.

Sample video (I’m assuming you used the "Edit" function, right?

[AzuraCast No page update-2023-10-16_12.29.32.mkv.zip](https://github.com/AzuraCast/AzuraCast/files/12915225/AzuraCast.No.page.update-2023-10-16_12.29.32.mkv.zip)

The real title tag of this song is (194 characters, I have some that are longer):

```
Medley: Bier her / Wir haben Hunger / Die Musik hat Durst / Schon wieder eine Seele vom Alkohol gerettet / Wir versaufen unserer Oma ihr kleines Häuschen / Jetzt trink'n ma noch a Flascherl Wein
```

Anyway, I haven’t completely re-scanned my collection (more than 160,000 tracks) for a while, so maybe your issue is some kind of software bug. I _still_ suspect the tags, and you didn’t answer my question.

**Comment by roger-net** [comment]
> Odd, doesn’t happen here, **but I found another bug:** Long titles are actually **cut off** by AzuraCast! Shouldn’t happen, especially classical music can have real long title tags.
> 
> Sample video (I’m assuming you used the "Edit" function, right?
> 
> [AzuraCast No page update-2023-10-16_12.29.32.mkv.zip](https://github.com/AzuraCast/AzuraCast/files/12915225/AzuraCast.No.page.update-2023-10-16_12.29.32.mkv.zip)
> 
> The real title tag of this song is (194 characters, I have some that are longer):
> 
> ```
> Medley: Bier her / Wir haben Hunger / Die Musik hat Durst / Schon wieder eine Seele vom Alkohol gerettet / Wir versaufen unserer Oma ihr kleines Häuschen / Jetzt trink'n ma noch a Flascherl Wein
> ```
> 
> Anyway, I haven’t completely re-scanned my collection (more than 160,000 tracks) for a while, so maybe your issue is some kind of software bug. I _still_ suspect the tags, and you didn’t answer my question. The assumption of what "correct" means can vastly differ.

Test your Azuracast. The attached song causes this problem.
[air supply - making love out of nothing at all.zip](https://github.com/AzuraCast/AzuraCast/files/12918522/air.supply.-.making.love.out.of.nothing.at.all.zip)
