### ISSUE TITLE
Track without id3 Tag

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#666]
Hello,
if i want to upload a aac+ track without any idv3 Tags, get an error.

**Comment by preterive** [comment]
Hello,
now i have conver it to mp3 with id3. But it don't work. the file is 6,2gb and 11 hours long

**Comment by SlvrEagle23** [comment]
@preterive ...

The file is 6.2GB and 11 hours long?

This is not supported in AzuraCast. While the exact upper limit of a MP3 file's size varies by host, I would expect it to be in the range of 100-500MB. The vast majority of radio stations I've seen never exceed a single file size of 50MB for an audio file.

**Comment by preterive** [comment]
Now i see 48 Hours and 5.5gb. I use my own vps. is tehre no option to take the filesize limit higher? now, i search in the php config

**Comment by preterive** [comment]
what php version? I have 5.6 to 7.2 on my server?

**Comment by SlvrEagle23** [comment]
@preterive AzuraCast uses PHP 7.2.

**Comment by preterive** [comment]
thanks.

**Comment by preterive** [comment]
Now, i see this: ; Maximum allowed size for uploaded files.
; http://php.net/upload-max-filesize
upload_max_filesize = 25M
... But already have files with 250 mb on my server...

**Comment by preterive** [comment]
There was an error, because the sond is to long for the db...

**Comment by preterive** [comment]
Okay, now i simple upload the track via sftp and change the settings in the db and all works fine!

**Comment by SlvrEagle23** [comment]
@preterive Your login is automatically generated upon installation if you're using a Traditional install. You can find your credentials in `/var/azuracast/www/app/env.ini`.

**Comment by preterive** [comment]
thanks.

**Comment by preterive** [comment]
i simple have to change the length from smallint(6) to smallint(8). Now ot works really good! I would really like it if you put this in the code.

**Comment by SlvrEagle23** [comment]
@preterive While I hesitate to say, in famous-last-words fashion, "SMALLINT ought to be enough for anybody", I think for the majority of use-cases this is the case.

Nonetheless, considering the change in DB size is rather small and it helps to "future-proof" the feature against anybody looking to upload long archival footage to a radio station later on, I'm inclined to bump the size of the `length` field up to `INT`.

The latest migration and code update does this officially.
