### ISSUE TITLE
After upgrading to 0.19.1, I get 'incorrect definition of table mysql.column_stats...' errors in my logs...

### ISSUE THREAD

**Issue by Shaltz** [AzuraCast/AzuraCast#6662]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.1

### What happened?

Hi, 

today I updated my installation from 0.17.3 to 0.19.1.
Everything went smoothly and the station is back online.
But now, my docker logs are filled with the same error message from
mariadb:
`
mariadb stdout | 2023-10-14 16:48:22 401 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').

mariadb stdout | 2023-10-14 16:48:22 401 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
`

what did I miss in my migration path ? 
what can I do to fix the issue because, even tho the station is up and running, having the logs polluted like this will make it quite hard in the future if I need to fix/troubleshoot something...

Looking around the internet, it seems that the issue can be fixed by running
`
mysql_upgrade --user=root --password
`
to force the upgrade of mysql/mariadb.

I tried to popup a test server from an AMI I did before the upgrade and running the command on it to see what's what...
but it seems that you need a "root" password for the mariadb instance that, apparently, you can find in the installation logs... 

Where are these logs located ? 
My installation is over a year old, will I still be able to access them ?

thanks in advance for your help and guidance

### Relevant log output

```shell
mariadb stdout | 2023-10-14 16:48:22 401 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
mariadb stdout | 2023-10-14 16:48:22 401 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
mariadb stdout | 
mariadb stdout | 2023-10-14 16:48:22 401 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
mariadb stdout | 2023-10-14 16:48:22 401 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
mariadb stdout | 
mariadb stdout | 2023-10-14 16:48:22 401 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
mariadb stdout | 2023-10-14 16:48:22 401 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
mariadb stdout | 
mariadb stdout | 2023-10-14 16:48:22 401 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
mariadb stdout | 2023-10-14 16:48:22 401 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
mariadb stdout | 
mariadb stdout | 2023-10-14 16:48:22 401 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
mariadb stdout | 2023-10-14 16:48:22 401 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
mariadb stdout | 
mariadb stdout | 2023-10-14 16:48:22 401 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
mariadb stdout | 2023-10-14 16:48:22 401 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
mariadb stdout | 
mariadb stdout | 2023-10-14 16:48:22 401 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
mariadb stdout | 2023-10-14 16:48:22 401 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
```

**Comment by BusterNeece** [comment]
@Shaltz You should find the MariaDB root password in `azuracast.env` on the host these days. Running the upgrade command should indeed help (though it should automatically be running after any update, so it's unusual that it hasn't in this case).

**Comment by Shaltz** [comment]
@BusterNeece 
thanks for your quick reply

and indeed, the mysql_root_password is in the `azuracast.env` file :)

after running the `mysql_upgrade` command, it seems that they are no error left in the logs :)

thank you very much again, I'm closing this ticket ;)
