### ISSUE TITLE
S3 : Error when creating a folder from the UI

### ISSUE THREAD

**Issue by Shaltz** [AzuraCast/AzuraCast#6663]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.1

### What happened?

Hi, 

this ticket is a follow up on [this one](https://github.com/AzuraCast/AzuraCast/issues/4883).

Basically, ever since I changed my storage type from local to S3 (on Amazon S3), I can't create a folder from the Azuracast UI.
The premises are the same as in the previous post.
I can upload a file, I can create a "folder" from the AWS console and use it in azuracast but, for the life of me, I cannot create a folder from the azuracast GUI ...

Since last I checked (about a year ago), the error message as evolved, here it is now...

```bash
UnableToWriteFile at /var/azuracast/www/vendor/league/flysystem/src/UnableToWriteFile.php L24: Unable to write file at location: testing2023/. 
Error executing "PutObject" on "https://s3.eu-west-3.amazonaws.com/<my bucket>/radio/media/testing2023/"; AWS HTTP error: Client error: `PUT https://s3.eu-west-3.amazonaws.com/<my bucket>/radio/media/testing2023/` resulted in a '400 Bad Request' response: 
<?xml version="1.0" encoding="UTF-8"?> <Error><Code>AccessControlListNotSupported</Code><Message>The bucket does not all (truncated...) 
AccessControlListNotSupported (client): The bucket does not allow ACLs - 
<?xml version="1.0" encoding="UTF-8"?> <Error><Code>AccessControlListNotSupported</Code><Message>The bucket does not allow ACLs</Message><RequestId>PA.....9ZD</RequestId><HostId>OtPGb11nnffznsd9+oNI3v...v0DoonbVtAPnndfBuddZXRSW/0E=</HostId></Error>
```
The error message is quite criptic, speaking about S3 ACL not being allowed. It's not recommended to use S3 ACL [anymore](https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-access-control.html#intro-managing-access-s3-resources) anyways ^^.

In the IAM role attached to the instance running Azuracast, there is an inline policy as so:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListAllMyBuckets"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::<my bucket>"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:GetObjectTagging",
                "s3:PutObjectTagging"
            ],
            "Resource": [
                "arn:aws:s3:::<my bucket>/radio/*"
            ]
        }
    ]
}
```

and again, I am able to upload and delete files from the azuracast UI, there is no reason (as far as my experience go) for me being to be able to upload files and not to create prefixes (folders).

any idea ? :/

thanks in advance :)

**Comment by Shaltz** [comment]
Can we reopen this issue please, it's still a problem.
Even with the latest Rolling-Update version, I still get an error when trying to create a folder on AWS S3.
I have enabled ACL (which shouldn't be needed now since AWS S3 uses another mechanism) and I still get this:

```
Unable to write file at location: testing_folder/. Error executing "PutObject" on "https://s3.eu-west-3.amazonaws.com/<my bucket>/radio/media/testing_folder/"; AWS HTTP error: Client error: `PUT https://s3.eu-west-3.amazonaws.com/<my bucket>/radio/media/testing_folder/` resulted in a `403 Forbidden` response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>959HVZ (truncated...) AccessDenied (client): Access Denied - <?xml version="1.0" encoding="UTF-8"?> <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId><EDITED></RequestId><HostId><EDITED></HostId></Error>
```

I wonder... Has anyone ever been able to create a folder on AWS S3 (or any S3 compatible service) ??
I mean, I'm siprised to be the only one...


any help ???

**Comment by elisandroesp** [comment]
I just did it after some S3 config gymnastics, @Shaltz:
ON the S3 bucket 'permissions' tab, enable ACLs on the `Object Ownership` area selecting `ACLs enabled` and leaving `Bucket owner preferred` radio button. save it, 
If this doesn't work, just open the ACL option `Access control list (ACL)` and just save it with the default option (Bucket owner reads, writes)
After a whole day thinking it was my mistake, it's actually some new Flysystem development, since it always look for ACLs, even if their docs doesn't say anything about it.

**Comment by Shaltz** [comment]
@elisandroesp 
hey, thanks so much for your help :)
unfortunately, after following your guidance, the problem still remains.
Same error, everything was set to the values you told me to set.
I have, anyways, edited and saved again, in case of...
but still not working...

any other insights ?

**Comment by BusterNeece** [comment]
This may be a limitation of the [filesystem abstraction library](https://flysystem.thephpleague.com/docs/adapter/aws-s3-v3/) that we use. It appears it's expecting to have IAM permissions to create and fetch object ACLs:

```
 {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:GetObjectAcl",
                "s3:PutObjectAcl",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::your-bucket-name",
                "arn:aws:s3:::your-bucket-name/*"
            ]
        }
    ]
}
```

**Comment by BusterNeece** [comment]
@Shaltz I updated the Rolling Release to disable ACLs entirely on S3 buckets, per new best practices...try that and see if it helps.

**Comment by Shaltz** [comment]
hi again @BusterNeece 

I've updated my azuracast instance to the latest rolling update.
and I tried again, I still ended up with the 
403 - Forbidden : Access Denied error

I then disabled the ACL on the bucket, and now I am back to the 
400 - Bad Request error : The bucket doesn't allow ACL error

Is there anything in particular that you want me to try ?

**Comment by BusterNeece** [comment]
@Shaltz Sure, but I'm out of options for you from my end. You may want to go looking through the Flysystem github repo and see what other insights people have in your situation.

**Comment by Shaltz** [comment]
@BusterNeece 
sure, I'll try that but I am surprised to see that I am the only facing this issue.
No one uses s3 as storage for their Azuracast instance ?
No one tested it before moving to production ?

I am lost to be honest, I work with AWS on a daily basis and I don't
see anything that I can do differentely on my end for it to work :/

thanks again to @elisandroesp and @BusterNeece  for their insights
If someone wann help and need me to do some tests on my instances, 
feel free to ask ;)

**Comment by BusterNeece** [comment]
> No one uses s3 as storage for their Azuracast instance ?

Plenty of people do, and as far as I know none are having this issue.

> No one tested it before moving to production ?

If you're implying that we didn't test S3 compatibility before shipping this feature, that's both wrong and a little insulting. We absolutely tested S3 support thoroughly, and have continued to use it in real-world scenarios ever since it launched. It's been out for years and working fine in a majority of cases.

I don't know why it's not working well in your case, because I don't know every intricacy of AWS's services. But do try to be respectful despite the frustration.

**Comment by Shaltz** [comment]
@BusterNeece 
sorry, I really didn't want to sound mean or disrespectful at all
I am so hyped about azuracast and all the amazing work that you did, I really am :)

And didn't want my frustration to appear judgemental about your work, 
english isn't my 1st language so I may appear clumsy sometimes...
Please accept my appologizes if I sounded unrespectfull

Now, knowing that this is working for most ppl, I will conduct more tests 
on my end to see what's what and as soon as I found something, I'll make sure to let you know

thanks again for your insights and help
