### ISSUE TITLE
CPU usage triple increased after upgrading to Liquidsoap 2.2.x

### ISSUE THREAD

**Issue by pawelzet** [AzuraCast/AzuraCast#6664]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.1

### What happened?

Hi, I was testing the latest 2.x liquidsoap series and found that it consumes 3 times the CPU per instance than Liquidsoap in my Azuracast version 0.18.5.

Is there a flag or something I can set to get the old CPU behavior? For now I have rolled out my Azuracast version back to 0.18.5. I do not have any additional Liquidsoap configuration.
[Link to htop](https://imgur.com/a/gVvLYP6)

**Comment by BusterNeece** [comment]
Liquidsoap had some issues with CPU consumption right upon the initial release of their 2.2.x version, but they've since dedicated a ton of time to optimizing it, and in our tests things are back down to where they were in earlier versions.

I'd be curious if you're doing anything specific that might increase that workload, like using audio post-processing (Master_me or StereoTool), what your crossfade settings are, if you're using any sort of advanced playlists, etc.

**Comment by pawelzet** [comment]
Yes, Im using  master_me and smar crossfade. But as far as I know these features were the same in 0.18.5 and back then my CPU usage was around 35-40%.

**Comment by pawelzet** [comment]
Thats my liquidsoap .liq file in v0.18.1:
[liquidsoap.liq.log](https://github.com/AzuraCast/AzuraCast/files/12910009/liquidsoap.liq.log)

**Comment by LordHelmchen666** [comment]
Try disable Replaygain and see what happens.

**Comment by pawelzet** [comment]
> Try disable "Use Replaygain Metadata" in Station Profile - AutoDJ and see what happens. There are big changes they have done in LS.

Thanks! It helped, my cpu usage is around 50% on avarage now. @BusterNeece Is it normal that Replay Gain is consuming 3x more CPU than all off the proccesses on my azuracast?

**Comment by LordHelmchen666** [comment]
That is an LS issue. They changed the method how RG is calculated in new version.

**Comment by pawelzet** [comment]
@Moonbase59 That's very professional from you, so thank you for the tips. For now it is just the hobby online radio for less than 20 people but maybe in the future it is going to change :)

**Comment by Moonbase59** [comment]
@pawelzet Same here, when it all started out… Those were the days. Let me tell you from many decades of IT experience (man, I must be getting _old_… almost 50 years in IT now…), that it _always_ pays off in the long run if one does things _right_ in the first place, even if it means a little more effort.

Learned from many mistakes I made in my days. ;-)
