### ISSUE TITLE
Can't assign folder to playlist

### ISSUE THREAD

**Issue by benotf** [AzuraCast/AzuraCast#6678]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #6f17fd6 (2023-10-18 8:52) • Docker • PHP 8.2

### What happened?

I'm trying to assig,n folder to playlist (folowing your instructions [here ](https://www.azuracast.com/docs/user-guide/media-management/)

Auto-Assigning Folders to Playlists
From the media manager, you can select a folder, select “Set Playlists” and assign the folder to a playlist.

Once assigned to a playlist, any files added to the folder will automatically be added to those same playlists. The system won’t remove any additional playlists that the media is in, but it will add the missing ones from the folder.

So it's not working

### Relevant log output

```shell
Error message prompted : 

RedisException at /var/azuracast/www/vendor/symfony/redis-messenger/Transport/Connection.php L137: Connection refused
```

**Comment by BusterNeece** [comment]
I'm not sure that this problem is specific to assigning a playlist to a folder; I think it's just something wrong with the Redis service. Restarting the whole container (or the whole server) should resolve the issue, as would running the update instructions.

**Comment by benotf** [comment]
Hi,

Thank you for giving me a hand.
I've done a reinstall and I'm doing updates quite often. But the issue is
still here.
😔

Thank you.

Fred


Le mar. 28 nov. 2023 à 23:56, Buster Neece ***@***.***> a
écrit :

**Comment by BusterNeece** [comment]
Currently I don't have enough information to know what's causing this issue to be able to solve it. It may be helpful to update to the latest Rolling Release version and then paste the Redis log (from System Administration > Log Viewer) so we can see what's going on there.
