### ISSUE TITLE
Daily playlist more then one time

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#668]
Hello,
I wish a feature to play a daily playlist more than one time a day for example every hour on 8:45, 9:45 etc. And not only one per day.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38780/allow-multiple-schedule-entries-for-a-single-playlist
