### ISSUE TITLE
No metadata in SSL Stream :(

### ISSUE THREAD

**Issue by benotf** [AzuraCast/AzuraCast#6682]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #6f17fd6 (2023-10-18 8:52) • Docker • PHP 8.2

### What happened?

https://github.com/AzuraCast/AzuraCast/issues/1598

I'm sorry, I'm opening this discussion again... I found it on the discussion thread : [Title/Artist data not streamed to VLC](https://github.com/AzuraCast/AzuraCast/issues/1598) but I see that it has not been solved. I don't know why?

I was used to broadcasting my web radio stream via Icecast installed locally on my PC and under Windows. Everything was working fine, but my stream couldn't be streamed to Google Chrome because I didn't have a proxy (no ssl).

So I installed Azuracast on my NAS and was able to broadcast my stream with SSL. It is very good.

On the other hand, the metadata of the stream sent to the players via the "pls, m3u, asx..." extensions does not display the metadata!!

**I would like to have this functionality back.**

Don't you find it convenient, when you like a piece, to look up and see who it is? (and note it to find the entire album of this artist?).

### Relevant log output

```shell
no
```

**Comment by scysys** [comment]
Its because of SSL. The .pls file links actually to the Proxy

https://example.com/listen/autodj/stream

It should link directly to the Icecast station in HTTP like this here

File1=http://example.com:PORT/MOUNT

Then it will work and show titles. But thats up to the Team to change. Inside pls in my opinion ssl makes no sense. Also when respect all the devices out there who dont know ssl will also fail to play this pls.

**Comment by BusterNeece** [comment]
Whether we link the `/listen/` URL or the direct port URL is a product of the `Use Web Proxy` system setting. You can change that to use direct port links, though there are just as many players out there (and hosting environments) that _do_ prefer a reliable HTTPS connection over ports 80/443 that the proxy still makes sense in a lot of cases.

As for VLC not showing metadata in certain situations, this is unfortunately not something we intentionally did ourselves but rather a limitation of either VLC or Icecast. In either case, those are separate pieces of software maintained by separate folks, so we can't do anything to remedy that situation directly.

**Comment by Moonbase59** [comment]
Additionally, if you try to use a _non-SSL_ stream on a secure webpage, almost all browsers nowadays will throw _mixed-content warnings_. I agree it is actually nonsense encoding and decoding an _audio or video stream_ which is public anyway, but the browser vendors force us…
