### ISSUE TITLE
Long delay between metadata and played music

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#6695]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.1

### What happened?

There is a delay between the metadata information and the song being played. For example, song A is playing but Azuracast is already displaying song B in the metadata and this difference reaches almost two minutes.

**Comment by Rafaelrds2017** [comment]
I'm also having problems with delays in information and metadata. Taking about 40 seconds to update.

**Comment by roger-net** [comment]
I discovered that when I disable crossfade the problem disappears.

**Comment by roger-net** [comment]
It was resolved in version 0.19.2
