### ISSUE TITLE
Podcastpage looks weird

### ISSUE THREAD

**Issue by 011248163264** [AzuraCast/AzuraCast#6700]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

v0.19.1 Stable • Docker • PHP 8.2

### What happened?

My podcast page looks strange: 
https://radio.danmarkvaagner.dk/public/1/podcast/1ed9b310-f77e-61d6-af87-8fe716b00b0a/episodes
i think there is now in the css or theme.
the issue is on all browsers

**Comment by BusterNeece** [comment]
@01123581321345589144233 Currently deploying a change that should fix this on public pages.
