### ISSUE TITLE
constant synchronization warning

### ISSUE THREAD

**Issue by marekdziem** [AzuraCast/AzuraCast#6705]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.1 Stable

### What happened?

when I log in as super user I constantly get warning:
Synchronization Not Recently Run
The routine synchronization task has not run recently. This may indicate an error with your installation.

I go to system debugger and try fire off the synch tasks not run for a while.

but I always come back to this message again when logging back in later.

Some stations have reported issues with playlist sequential playback breaking and undue metadata update intervals.

server resource utilization seems adequate and I can't find any specifics in the logs to troubleshoot this!
any help appreciated - hey @BusterNeece  :)

**Comment by BusterNeece** [comment]
@marekdziem Which task in particular isn't working correctly? In newer versions of AzuraCast, we also have a specific PHP synchronization task log in the Log Viewer page, and that may be of help.
