### ISSUE TITLE
COMPOSER_PLUGIN_MODE note

### ISSUE THREAD

**Issue by vneznaikin** [AzuraCast/AzuraCast#6708]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

COMPOSER_PLUGIN_MODE is not documented in the plugin installation documentation (https://www.azuracast.com/docs/developers/plugins/) which is misleading

**Comment by BusterNeece** [comment]
The sample plugin has been updated to 0.19.x code standards and also includes the plugin mode note on the `docker-compose.override.yml` instructions.
