### ISSUE TITLE
mono to stereo azuracast

### ISSUE THREAD

**Issue by Blazedallup** [AzuraCast/AzuraCast#671]
hi i am new to github and azuracast , so i will apologize now.
i cant get my mono files to play. i have looked up audio_to_stereo but i have no idea where to change this
everywhere i look refers to it but noone explains what file or location it is in PLEASE HELP!
Thank you for you're time.

**Comment by SlvrEagle23** [comment]
@Blazedallup Hello and thank you for submitting your request over here as well. :)

It's so rare for us to get files with audio input that I've never actually been asked about this in the entire history of AzuraCast, but after you asked, I looked at our automatically generated configuration and discovered that we are applying `audio_to_stereo` to the live input, but not to the entire composited signal. It appears that, for the more common stereo signals, this incurs no performance overhead as it just passes the audio through, but it converts mono to stereo, and this is safe to do in almost all cases.

I've updated the AzuraCast code to apply this change. If you update your AzuraCast installation, you should automatically have the stereo upconversion built in now without any modifications.

**Comment by Blazedallup** [comment]
Thank you so much. i will update and let you know how it works out. just wanna say thank you for this great program. and all the time you have put into it, it works great.

**Comment by Blazedallup** [comment]
it seems to be working very well. Thanks again for this great piece of software and for you're time.
