### ISSUE TITLE
API: Make "hls_is_default" available in GET /stations as well (like in GET /admin/stations)

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6712]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #155f66e (2023-11-05 17:46)

### What happened?

`azuracast_xmltv` can’t reliably determine which stream should be default, since mounts and HLS are two separate things. We _do_ have "is_default" in the mounts, so can determine which should be default here.

But we don’t see if HLS should be preferred (as set in station profile and shown in API GET /admin/stations as "hls_is_default").

Should be no harm showing that in the "open" GET /stations, too.

I could then generate the same sequence as the web player does, for the XMLTV M3Us, and ensure they play using the same defaults when opened with an audio player.

**Comment by Moonbase59** [comment]
Thanks again. In (non-Admin) `/stations` and `/nowplaying`—this is helpful. Will adapt `azuracast_xmltv` later on and run some tests.

**Comment by Moonbase59** [comment]
@BusterNeece Just for my understanding: Just tried some combinations of this and it works fine.

One one station, I have _both_ an Icecast mount _and_ HLS as default. I _unset_ the default on the one Icecast stream but after restarting broadcast it automatically is _also_ (re-)selected as `default`.

Is this correct? I.e., do Icecast/Shoutcast _need_ one of  _their_ mounts being a default?

If so, and we have both HLS & Icecast/Shoutcast, should we simply prioritize HLS, if both are set as default, as the player seems to do?

**Comment by BusterNeece** [comment]
> @BusterNeece Just for my understanding: Just tried some combinations of this and it works fine.
> 
> One one station, I have _both_ an Icecast mount _and_ HLS as default. I _unset_ the default on the one Icecast stream but after restarting broadcast it automatically is _also_ (re-)selected as `default`.
> 
> Is this correct? I.e., do Icecast/Shoutcast _need_ one of _their_ mounts being a default?
> 
> If so, and we have both HLS & Icecast/Shoutcast, should we simply prioritize HLS, if both are set as default, as the player seems to do?

Yeah, there's always a "default" mount point out of the traditional mount points. The `hls_is_default` is meant to trump those and to put HLS at the top of the list, followed by the default mount, then the others.

**Comment by Moonbase59** [comment]
Perfect, thanks. So I’ll change `azuracast_xmltv` the same way, and it’ll behave the same as AzuraCast itself does (for generating the M3U etc.).

**Comment by Moonbase59** [comment]
[`azuracast_xmltv` v0.18.0](https://github.com/Moonbase59/azuracast_xmltv) is out and tested. Supports the new `hls_is_default` (but stays backwards-compatible) and will put HLS first if specified as default stream.
