### ISSUE TITLE
Manual Crossfade per Media not working

### ISSUE THREAD

**Issue by PoGo606** [AzuraCast/AzuraCast#6713]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.1

### What happened?

Hello,

I'm struggling with manual crossfade settings per media.
After setting a manual cue out on certain media that are something too long for radio broadcasting I'm trying to set a crossfade (out) longer than the global setting of Auto DJ (2sec in my case)

It seems that the setting of AutoDJ always takes over the manual settings.
For example, I've set a manual "Custom Fading: Fade-Out Time" of 10 sec for debugging purpose. 
Unfortunatly the track always end with a 2sec or less crossfade.

I've tried with the smart crossfade and the normal one.
Also by disabling the mastering chain.

I've set up a beta test station here : https://webradio.roflcopter.fr/public/webradio_roflcopter_(beta_test)
It has single playlist with 4 sequential tracks :
- 2 shorts tracks "left untouched"
```
API nextsong - Response (200): annotate:title="Flowers",artist="Nujabes",duration="76.00",song_id="91d535f8721f30d49d9de545861ad1ae",media_id="587",playlist_id="38":media:06_-_nujabes_-_flowers.mp3
API nextsong - Response (200): annotate:title="Rock It Number Nine",artist="Metaform",duration="81.00",song_id="04d824a4464116e7c4db146904c037e5",media_id="539",playlist_id="38":media:metaform_-_standing_on_the_shoulders_of_giants_-_01_rock_it_number_nine.mp3
```
- 2 intialy long tracks manually set for cue in and cue out
```
API nextsong - Response (200): annotate:title="So Flute",artist="St. Germain",duration="509.00",song_id="3920fa2accb65e81fd821b0b07505d14",media_id="620",liq_fade_in="2.00",liq_fade_out="10.00",liq_cue_in="274.60",liq_cue_out="314.30",playlist_id="38":media:03_-_so_flute.flac
API nextsong - Response (200): annotate:title="Under the Pressure",artist="The War on Drugs",duration="532.00",song_id="29a5ce66bfd4d4733063ac4a6a157663",media_id="485",liq_fade_in="2.00",liq_fade_out="10.00",liq_cue_in="300.00",liq_cue_out="348.20",playlist_id="38":media:01_-_under_the_pressure.flac
```
![image](https://github.com/AzuraCast/AzuraCast/assets/1552904/7a8623e4-4f6f-47d2-a51c-b7e1550a26dd)

I'd really like to understand how to make things work.

You may find here the current Liquidsoap configuration : https://wtf.roflcopter.fr/paste/?932fe50622c3c81b#DioCfu9z5bCXAfY4X9owTMddCv2bFwtooJnTdyRSVKze

Thank you in advance for your help !

**Comment by DE1103DX** [comment]
On my AzuraCast 0.19.1 installation, I can fully confirm that bug malfunction. Also tried different croosfade and smart crossfade settings, but then had to disable crossdafing (sounds allright on many songs, apart from a few exceptions). the standard 2 second crossfade worked fine on previous AzuraCast versions up to 0.18.xx. After the current version was installed, at the very end of a song, when it usualy slowly gradualy fades out, it even abruptly faded back up and then slowly back down again...

**Comment by PoGo606** [comment]
No change since the upgrade with 0.19.2.

**Comment by pozhiloy-enotik** [comment]
> For example, I've set a manual "Custom Fading: Fade-Out Time" of 10 sec for debugging purpose.
Unfortunatly the track always end with a 2sec or less crossfade.

This is fully a liquidsoap limitation [as referenced here](https://github.com/AzuraCast/AzuraCast/discussions/6252#discussioncomment-6947901)


```php
def live_aware_crossfade(old, new) =
    if to_live() then
        # If going to the live show, play a simple sequence
        sequence([fade.out(old.source),fade.in(new.source)])
    else
        # Otherwise, use the smart transition
        cross.simple(old.source, new.source, fade_in=2.00, fade_out=2.00)
    end
end
 
radio = cross(minimum=0., duration=3.00, live_aware_crossfade, radio)
```

your fades hereby are limited by ```duration=3.00``` 
should ask those developers what their intentions were
