### ISSUE TITLE
Station dead following STABLE release update

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#6718]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.2 Stable

### What happened?

•  Downloaded last backup;
•  Updated to 19.2 from 19.1 >> updated manually via Putty ; process ran fine; no hiccups;
•  Station came back apparently normally... Observed that player was displaying song titles,  but no sound whatsoever;
•  Logged in to console normally >> everything appeared normal except no listeners on the streams;
•  Checked Liquidsoap log >> See edited file below below << surprised to see that LS was calling to ICECAST instead of SHOUTCAST
•  SHOUTCAST shows properly installed;
[See in replies below]
•  Queried Shoutcast config which appears to be normal;
[See in replies]
•  However Shoutcast log shows that connection is denied;
[See in replies]
• Logged in to stream with Sam Broadcaster >> connection accepted fine but obviously couldn't push a Shoutcast stream through Icecast pipeline;
• Tried to restore from backup... seems I couldn't figure out proper Linux syntax...

Please... what went wrong, and how can I fix this?

**Comment by SpeedyCharly** [comment]
[LS Log.txt](https://github.com/AzuraCast/AzuraCast/files/13306314/LS.Log.txt)

**Comment by SpeedyCharly** [comment]
![S-Cast installed](https://github.com/AzuraCast/AzuraCast/assets/66107794/2b6aab95-1c43-4145-9ac7-185658f2583f)
[Sh-Cast Config.txt](https://github.com/AzuraCast/AzuraCast/files/13306335/Sh-Cast.Config.txt)

**Comment by SpeedyCharly** [comment]
[Shoutcast Log.txt](https://github.com/AzuraCast/AzuraCast/files/13306338/Shoutcast.Log.txt)

**Comment by BusterNeece** [comment]
@SpeedyCharly Looking into this...if you go to edit the station's profile, does it show you as being on Icecast or Shoutcast as the broadcasting frontend? Can you switch it from one to the other?

Have you tried restarting broadcasting fully via the Utilities menu?

**Comment by SpeedyCharly** [comment]
All was normal on BROADCASTING control panel - Shoutcast ticked and settings unchanged. Also able to switch back/forth
Was beat last night-went to bed in frustration... LOL. Tried restarting  Autodj and Broadcasting as per your suggestion and
station cam back fine... Thanks ♫   Here is Shoutcast log at restart in case it may help elucidate what transpired:
[REBOOT BROADCAST.txt](https://github.com/AzuraCast/AzuraCast/files/13312402/REBOOT.BROADCAST.txt)

Please let me know if it was a misstep on my part that causes this. THANKS AGAIN FOR YOUR HELP!!!

**Comment by BusterNeece** [comment]
@SpeedyCharly not sure you did anything wrong, it just seems like sometimes the update process doesn't rewrite the configurations correctly. Not sure why that is, but doing a manual restart like that should ensure you're in a known-good state.

**Comment by SpeedyCharly** [comment]
Noted a white line that randomly zips across the top of the player and the top of the Control panel pages, seemingly in time with DEBUG calls observed in Shoutcast log [below] Doesn't seem to really affect operations, but could be a clue to a larger issue...
[DEBUG.txt](https://github.com/AzuraCast/AzuraCast/files/13313103/DEBUG.txt)

**Comment by BusterNeece** [comment]
@SpeedyCharly No, I put that there on purpose to indicate remote fetches that may take some time to load without any other observable indicator of loading. Not a bug, it's a feature

**Comment by SpeedyCharly** [comment]
@BusterNeece Noted ♪ Danke Mein Freund !
