### ISSUE TITLE
Installation loses SSL certificate after update

### ISSUE THREAD

**Issue by Sella-3DX** [AzuraCast/AzuraCast#6721]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#efef6c2 (2023-11-10 15:44)

### What happened?

AzuraCast loses the SSL certificate issued by Let's encrypted and replaces it with a self-signed certificate after it has been updated.
![image](https://github.com/AzuraCast/AzuraCast/assets/147769367/beca3aec-7684-49a4-94fc-9a8ab22cd864)
![image](https://github.com/AzuraCast/AzuraCast/assets/147769367/0bd8f1ca-bb8e-4a32-9f0e-a269c4829030)

After logging in with another browser I had to request a new cert manually and then it worked again.

**Comment by BusterNeece** [comment]
@Sella-3DX The cause of this has been identified and fixed in the latest Rolling Release. I plan to tag a stable release rather soon once we've knocked out a few other issues.

**Comment by Sella-3DX** [comment]
Thanks! I'll update as soon as it's possible, currently we're waiting a bit. 🙂

**Comment by bboyles303** [comment]
This seems to be happening in the latest Rolling Release (Rolling Release #[57dd7e5](https://github.com/AzuraCast/AzuraCast/commit/57dd7e5c154ae8c758944c9659514fe5be421dcb) (2023-11-17 22:06)) as well. Tried to regen the LE cert via the interface and it won't renew:  AzuraCast.ERROR: ACME Error: Certificate does not need renewal.

**Comment by BusterNeece** [comment]
This is fixed in the latest Rolling Release and Stable releases (with 0.19.3 being released specifically to address this issue).
