### ISSUE TITLE
Stations OFFLINE after Update 0.19.2

### ISSUE THREAD

**Issue by RadioHerzblut** [AzuraCast/AzuraCast#6725]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

After Update from 0.19.1 -> 0.19.2 the Stations Offlline.

Befor Update Azuracast i habe update Docker .

**Comment by BusterNeece** [comment]
@RadioHerzblut Can you provide some more information on steps you've tried to resolve it?

One important step would be to restart broadcasting via Utilities > Restart Broadcasting. That often fixes issues like this.

**Comment by RadioHerzblut** [comment]
Hello. Can give you more information. Tomorrow.I Test ist again with RESTART BROADCASTING.Thank you Am 12.11.2023 20:06 schrieb Buster Neece ***@***.***>:
@RadioHerzblut Can you provide some more information on steps you've tried to resolve it?
One important step would be to restart broadcasting via Utilities > Restart Broadcasting. That often fixes issues like this.

**Comment by RadioHerzblut** [comment]
**My system:**

**OS:** Linux Ubuntu 20.04.3 LTS

- Updated Ubuntu to the latest update

- Docker brought up to date


- Update from Azuracast according to instructions.

Tried the whole thing again today and it worked. Even starting from the station worked by itself.

I have no idea why it didn't work for the last few days.

Update was successful today on Docker 0.19.2
