### ISSUE TITLE
Recording live streamer breaks liquidsoap

### ISSUE THREAD

**Issue by netbladenl** [AzuraCast/AzuraCast#6727]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#b5ef6ea

### What happened?

When you turn on "Record Live Broadcast" at the Streamers/DJs page it breaks liquidsoap, Titles ain't updated anymore and sometimes after the streamer quits broadcasting the autodj wont play anymore. The only solution is to restart the autodj service at the main page.

I've tried turning off stereotool or use none at all, when the setting "Record Live Broadcast" is turned on those issues show up, tested on two different servers. 

Without this function turned on everything works as it should with direct artist and song names updates, (except for the fading when a streamer connects, and a part of the last song played before the streamer connected can be heard).

See https://github.com/AzuraCast/AzuraCast/issues/6726 aswell
### Relevant log output

```shell
2023/11/11 18:02:28 [lang:3] API feedback - Response (200): true
2023/11/11 18:03:12 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/auth' with body: { "user": "user", "password": "****" }
2023/11/11 18:03:12 [lang:3] API auth - Response (200): true
2023/11/11 18:03:12 [lang:3] DJ Source connected! Last authenticated DJ: iwan - [("Authorization", "Basic **Password**="), ("Host", "streaming.youradio.nl:8005"), ("User-Agent", "butt 0.1.39"), ("Content-Type", "audio/mpeg"), ("ice-name", "no name"), ("ice-public", "0"), ("ice-audio-info", "ice-bitrate=320;ice-channels=2;ice-samplerate=48000"), ("Expect", "100-continue")]
2023/11/11 18:03:12 [lang:3] API djon - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/djon' with body: { "user": "iwan" }
2023/11/11 18:03:12 [lang:3] API djon - Response (200): true
2023/11/11 18:03:12 [input_streamer:3] Decoding...
2023/11/11 18:03:42 [input_streamer:2] Error while reading from client: Timed out after waiting for 30.02 sec.
2023/11/11 18:03:42 [lang:3] API djoff - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/djoff' with body: { "user": "iwan" }
2023/11/11 18:03:42 [lang:3] API djoff - Response (200): true
2023/11/11 18:03:42 [input_streamer:2] Feeding stopped: Avutil.Error(Invalid data found when processing input).
2023/11/11 18:03:42 [lang:3] API djoff - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/djoff' with body: { "user": "" }
2023/11/11 18:03:42 [lang:3] API djoff - Response (200): true
2023/11/11 18:03:57 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/auth' with body: { "user": "iwan", "password": "***" }
2023/11/11 18:03:57 [lang:3] API auth - Response (200): true
2023/11/11 18:03:57 [lang:3] DJ Source connected! Last authenticated DJ: iwan - [("Authorization", "Basic *****="), ("Host", "streaming.youradio.nl:8005"), ("User-Agent", "butt 0.1.39"), ("Content-Type", "audio/mpeg"), ("ice-name", "no name"), ("ice-public", "0"), ("ice-audio-info", "ice-bitrate=320;ice-channels=2;ice-samplerate=48000"), ("Expect", "100-continue")]
2023/11/11 18:03:57 [lang:3] API djon - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/djon' with body: { "user": "iwan" }
2023/11/11 18:03:57 [lang:3] API djon - Response (200): true
2023/11/11 18:03:57 [input_streamer:3] Decoding...
2023/11/11 18:04:16 [input_streamer:2] Feeding stopped: Avutil.Error(Invalid data found when processing input).
2023/11/11 18:04:16 [lang:3] API djoff - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/djoff' with body: { "user": "iwan" }
2023/11/11 18:04:16 [lang:3] API djoff - Response (200): true
2023/11/11 18:04:35 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/auth' with body: { "user": "", "password": "" }
2023/11/11 18:04:35 [lang:3] API auth - Response (200): true
2023/11/11 18:04:35 [lang:3] DJ Source connected! Last authenticated DJ: iwan - [("Host", "streaming.youradio.nl:8005"), ("icy-name", "No Name"), ("icy-pub", "0"), ("icy-br", "320"), ("content-type", "audio/mpeg")]
2023/11/11 18:04:35 [lang:3] API djon - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/djon' with body: { "user": "iwan" }
2023/11/11 18:04:35 [lang:3] API djon - Response (200): true
2023/11/11 18:04:35 [input_streamer:3] Decoding...
2023/11/11 18:05:05 [input_streamer:2] Error while reading from client: Timed out after waiting for 30.00 sec.
2023/11/11 18:05:05 [lang:3] API djoff - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/djoff' with body: { "user": "iwan" }
2023/11/11 18:05:05 [lang:3] API djoff - Response (200): true
```

**Comment by entured** [comment]
It happens the same to me too

**Comment by BusterNeece** [comment]
@netbladenl It seems likely that this issue is a problem with Liquidsoap, the software we use to accept incoming DJ connections, to manage our AutoDJ, and to compose the audio signal that is then broadcasted out to the world.

I'd recommend raising this issue with the Liquidsoap team on [their GitHub](https://github.com/savonet/liquidsoap/issues/new/choose). Be sure to provide them with all the information you provided here. It may also be helpful to include your auto-generated Liquidsoap configuration (visible on the station's "Logs" page).

If they indicate that this is indeed an issue with AzuraCast instead, feel free to return to this issue and let us know.

**Comment by netbladenl** [comment]
@BusterNeece Thanks for checking, I've made an issue at https://github.com/savonet/liquidsoap/issues/3537
I hope they can solve this issue.

**Comment by streulma** [comment]
We encountered this issue at our production radio station server. With the new stable update 0.19.3 our live shows started from VLC and Butt, starting the show was OK, but when we send a disconnect, then the live stream was broken and AzuraCast played a "sea wave" and did not end correctly the broadcast. As soon as I read this issue here, I disabled recording in Azuracast and the problem was solved. From now on we setup an own recording system on the same server with VLC constantly listening to the Icecast stream and record as MP3 and split in files per a couple of hours.

**Comment by netbladenl** [comment]
[toots](https://github.com/toots) commented [14 hours ago](https://github.com/savonet/liquidsoap/issues/3537#issuecomment-1828469090)
I was able to test and confirm that the latest commit on the [fix-has-ticked-2.2.x](https://github.com/savonet/liquidsoap/tree/fix-has-ticked-2.2.x) branch does fix the issue.

Reproduction was tricky because it relied on two elements:

Source sharing, achieved via the two outputs
Partial frame fill.
Partial frame fill can depend on timing such as when the harbor gets available. By changing the duration to 20.03 (frame sizes are 0.04 by default), I was able to make the test case reproducible.

Seems like the issue has been fixed @BusterNeece  could you add the new rolling release of liquidsoap to the rolling release?

**Comment by netbladenl** [comment]
Thanks for your action, still the problem exists ;

2023/11/28 13:09:30 [lang:3] API djon - Response (200): true
2023/11/28 13:09:30 [input_streamer:3] Decoding...
2023/11/28 13:09:39 [live_fallback:3] Switch to metadata_map.4 with transition.
2023/11/28 13:09:39 [metadata_map.7:3] Inserting missing metadata.
2023/11/28 13:10:09 [input_streamer:2] Error while reading from client: Harbor.Make(T).Websocket_closed
2023/11/28 13:10:09 [lang:3] API djoff - Sending POST request to 'http://127.0.0.1:6010/api/internal/4/liquidsoap/djoff' with body: { "user": "iwan" }
[matroska,webm @ 0x7f84e2e17000] File ended prematurely at pos. 198330 (0x306ba)
[matroska,webm @ 0x7f84e2e17000] Seek to desired resync point failed. Seeking to earliest point available instead.
2023/11/28 13:10:09 [lang:3] API djoff - Response (200): true
2023/11/28 13:10:09 [input_streamer:2] Feeding stopped: Ffmpeg_decoder.End_of_file.
2023/11/28 13:10:09 [lang:3] API djoff - Sending POST request to 'http://127.0.0.1:6010/api/internal/4/liquidsoap/djoff' with body: { "user": "" }
2023/11/28 13:10:09 [lang:3] API djoff - Response (200): true

[2023-11-28  13:10:20] WARN source/_source_read Nothing received on /radio.aac for 3 seconds
[2023-11-28  13:10:20] WARN source/_source_read Nothing received on /radio.mp3 for 3 seconds
[2023-11-28  13:10:20] WARN source/_source_read Nothing received on /radio.aac for 3 seconds
[2023-11-28  13:10:20] WARN source/_source_read Nothing received on /radio.mp3 for 3 seconds
[2023-11-28  13:10:20] WARN source/_source_read Nothing received on /radio.aac for 3 seconds
[2023-11-28  13:10:28] WARN source/_source_read Disconnecting /radio.aac due to socket timeout
[2023-11-28  13:10:28] WARN source/_source_read Disconnecting /radio.mp3 due to socket timeout
[2023-11-28  13:11:01] WARN fserve/fserve_client_create req for file "/usr/local/share/icecast/web/radio.mp3" No such file or directory
[2023-11-28  13:12:21] WARN fserve/fserve_client_create req for file "/usr/local/share/icecast/web/radio.mp3" No such file or directory
[2023-11-28  13:12:22] WARN fserve/fserve_client_create req for file "/usr/local/share/icecast/web/radio.mp3" No such file or directory


The autodj dont come back, ill post this aswell on the github of liquidsoap

**Comment by netbladenl** [comment]
I was a bit to soon, the patch was not implemented yet:
https://github.com/savonet/liquidsoap/issues/3537#issuecomment-1830253073
Could you please once more add the latest liquidsoap again @BusterNeece ?

**Comment by netbladenl** [comment]
Problem has been resolved with the latest update. 
Thank you for the help Buster!
