### ISSUE TITLE
The stream stops when the playing file ends. Only in webplayers.

### ISSUE THREAD

**Issue by anducampu** [AzuraCast/AzuraCast#673]
Installation method: Docker
Host OS (for Docker installations): Ubuntu 18,04
Describe the bug: 

I have a radio that plays 1 hour mixes. The files are .flac. The stream is opus/96 kbps. On VLC and mobile players the stream works great. The files mix as they should. On web players it's a different story. The stream stops when the playing file ends (html5, javascript). 

I read that I have to rise the time in "Advanced: DJ/Streamer Buffer Time". It's 24 seconds now but that does't fix the problem. I also configured different values in the Mount Point - Advanced Frontend Configuration (queue-size=524288, burst-size=131072) but no luck. Any ideas?

Thank you

**Comment by Lukahhh** [comment]
Hi! 

Does this happen when the stream is set to MP3? I seem to recall reading somewhere there's an issue within liquidsoap that causes OGG/Vorbis/Opus streams to drop clients at the end of a file? I can't remember exactly where I saw this. I'd say try testing the Icecast output as MP3 and see if that solves it, then you can identify where the issue lies exactly.

**Comment by anducampu** [comment]
No. Opus. The rest of the codecs work fine. I read opus stream has some known issues with icecast. My confusion is that on a mobile player or VLC the stream works fine.

**Comment by Lukahhh** [comment]
I found the reference I had read, but it specifically references Ogg/Vorbis. The issue with Ogg/Vorbis sounds very similar to whats happening for you.

http://www.liquidsoap.info/doc-1.3.3/faq.html#Listeners_are_disconnected_at_the_end_of_every_track

> 
> Several media players, including renowned ones, do not properly support Ogg/Vorbis streams: they treat the end of a track as an end of file, resulting in the disconnection.
> 
> Players that are affected by this problem include VLC. Players that are not affected include ogg123, liquidsoap.
> 
> One way to work around this problem is to not use Ogg/Vorbis (which we do not recommend) or to not produce tracks within a Vorbis stream. This is done by merging liquidsoap tracks (for example using add(normalize=false,[blank(),source])) and also not passing any metadata (which is also a result of the previous snippet).

Have you run a `docker-compose logs -f`? There may be something valuable in the logs.
