### ISSUE TITLE
HLS stream metadata seems to send the track name instead of the artist name

### ISSUE THREAD

**Issue by Kkspike** [AzuraCast/AzuraCast#6730]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.2 Stable • Docker • PHP 8.2

### What happened?

We started using the HLS stream for our iOS app because the metadata wasn't sending on the mp3 streams like they used to. Using HLS, the metadata seems to be sent successfully. However, the song name seems to be sent instead of the artist name for the "artist" value (the song title gets sent also, with the "title" value).

`Updating metadata in Now Playing ["MPNowPlayingInfoPropertyIsLiveStream": true, "artist": "Le Roi Des Cieux", "title": "Le Roi Des Cieux", "artwork": <MPMediaItemArtwork: 0x600001ad47c0>]`

The information is displayed fine on the web player and here are the tags we have on that song. 
![image](https://github.com/AzuraCast/AzuraCast/assets/35116060/3ca2fefd-1780-464a-a5ec-db345cb121cb)

I'm not sure how to see this in any logs, tough, or if it's something I can change in the configurations.

**Comment by BusterNeece** [comment]
@Kkspike It seems likely that this issue is a problem with Liquidsoap, the software we use to accept incoming DJ connections, to manage our AutoDJ, and to compose the audio signal that is then broadcasted out to the world.

I'd recommend raising this issue with the Liquidsoap team on [their GitHub](https://github.com/savonet/liquidsoap/issues/new/choose). Be sure to provide them with all the information you provided here. It may also be helpful to include your auto-generated Liquidsoap configuration (visible on the station's "Logs" page).

If they indicate that this is indeed an issue with AzuraCast instead, feel free to return to this issue and let us know.

**Comment by gAlleb** [comment]
Hi @Kkspike It might be just a configuration of iOS APP. You can test the metadata here https://hlsjs.video-dev.org/demo/
Insert your HLS stream url at the bottom of the page find metadata info, which is being sent
<img width="1036" alt="Снимок экрана 2023-11-15 в 16 06 28" src="https://github.com/AzuraCast/AzuraCast/assets/144447266/af0a0eda-e199-4060-98a4-9e6b4b324b75">

You can enlarge that area and see what metedata is sent, usually its title, artist and album.

In the iOS player with which I am listening to HLS streams there is no support for artist tags, so I had to add a function to azuracast liquidsoap conf to make artist - title behave like in ordinary icecast.

```
def hls_meta(m) =
title = m["title"]
artist = m["artist"]
if artist != "" and title != "" then
[...list.assoc.remove("artist", m), ("title", "#{artist} - #{title}")]
else
m
end
end
radio = metadata.map(update=false, hls_meta, radio)
```

**Comment by Kkspike** [comment]
@gAlleb Wow this tool is very useful! I've checked and it seems we are getting the artist and the song title (it's difficult to see since I have seem to be at maximum zoom on the metadata filed).
![image](https://github.com/AzuraCast/AzuraCast/assets/35116060/c2487455-c350-4e12-9d43-4b59d2df8785)

But you are right, we seem to be getting something. I'll try to figure out what is going on with our app. This has been helpful, really.

**Comment by gAlleb** [comment]
You are getting as far as I can see
'TPE1' - Artist - Queen
'TIT2' - Title - Thank God It's Christmas
'TALB' - Album - The Works (deluxe remastered edition)

So yes, HLS working ok.
