### ISSUE TITLE
Error appears on Update via web

### ISSUE THREAD

**Issue by CouinCouin** [AzuraCast/AzuraCast#6731]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.1

### What happened?

Hi, 

When trying to "Update via web", I get a red pop-up in the top-right corner "An error occurred and your request could not be completed."

I got it also with 1.8.5 (so I manually update via SSH). 

Thanks

**Comment by Zagrthos** [comment]
Same issue here, happens when I update AzuraCast via web. You then need to reload it with F5 and afterwards it shows you the login screen again. I guess this error is produced while the Web-Updater restarts the docker container in background but the UI isn't coded to reload itself.

**Comment by CouinCouin** [comment]
I don't know, but it does nothing (no update), I have to update from command lines.
Also, I did not updated to 0.19.2 as well as ity looks having some problems (offline stations, SSL out etc ).

**Comment by BusterNeece** [comment]
@CouinCouin I would not judge the stable release based on new issues created. I have no reason to suspect those issues are widespread right now.
