### ISSUE TITLE
docker.sh update | stuck on "Pulling"

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#6735]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #7433533 (2023-11-03 15:41) 

### What happened?

I want to update using the docker.sh update script.
The script starts, downloads the images but is stuck on "pulling" (see screenshot attached).
The timer counts up alle the time but the script is not doing anything because all images are already downloaded.
![image](https://github.com/AzuraCast/AzuraCast/assets/47743654/5a8382f4-6f9e-4069-a9e2-28283aca794c)

**Comment by MrSteelMiner** [comment]
After 437.0 seconds, the installer continues... Seems like I am impatient... 
Is it still a bug or no reproducable nonsense on my side?

**Comment by gAlleb** [comment]
> Is it still a bug or no reproducable nonsense on my side?

The second one! :)

**Comment by BusterNeece** [comment]
You may be running out of disk space...we had an issue in the last few Rolling Releases where their uncompressed file size was closer to 3GB than the normal 1.5GB; this has been resolved in the newest Rolling Releases.
