### ISSUE TITLE
Can't access webinterface and stream anymore

### ISSUE THREAD

**Issue by Sella-3DX** [AzuraCast/AzuraCast#6737]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #34e739b

### What happened?

After the update I can't access the web interface and the music stream anymore.
Server can be pinged but no access to the website.

I also noticed in the monitoring that liquidsoap still runs but it seems like that the webserver doesn't work anymore.

### Relevant log output

```shell
N/a
```

**Comment by RadioHerzblut** [comment]
Hi, I have the same problem. 

Current version: Docker 24.07.7
Azuracast: 0.19.2

My system:

OS: Linux Ubuntu 20.04.3 LTS

Ubuntu updated to the latest version

Update Azuracast according to the instructions.

**Comment by Sella-3DX** [comment]
There you go 🙂 
![image](https://github.com/AzuraCast/AzuraCast/assets/147769367/4d731d36-5db3-41c9-abcc-7958e8651336)

**Comment by BusterNeece** [comment]
Thank you! I'm deploying a fix right now that should address the issue in Rolling Release. I'd recommend waiting about 10 minutes and then updating to see if things are resolved.

Thank you for helping test things out and for posting the logs.

**Comment by Sella-3DX** [comment]
Nope, fix didn't worked. Web is still not available but the error doesn't come up anymore instead it says that there's no track to update.

**Comment by BusterNeece** [comment]
@Sella-3DX Try updating again? And also feel free to post the full log here, especially the section that relates to nginx.

**Comment by Sella-3DX** [comment]
Currently I'm gone, I'll test it out in a few hours again when I'm back and then post the details. 🙂

**Comment by mkbwr** [comment]
`azuracast  | nginx stdout | nginx: [emerg] cannot load certificate "/var/azuracast/storage/acme/ssl.crt": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/var/azuracast/storage/acme/ssl.crt, r) error:10000080:BIO routines::no such file)
azuracast  | nginx stdout | 
azuracast  | 2023-11-17 21:39:38,242 WARN exited: nginx (exit status 1; not expected)
azuracast  | 2023-11-17 21:39:38,391 INFO gave up: nginx entered FATAL state, too many start retries too quickly
azuracast  | 
`

**Comment by BusterNeece** [comment]
@mkbwr That's after updating to the latest Rolling?

**Comment by mkbwr** [comment]
Yes - 5 mins ago

**Comment by BusterNeece** [comment]
@mkbwr See if the latest update helps?

**Comment by mkbwr** [comment]
@BusterNeece Perfect - thank you.

**Comment by Sella-3DX** [comment]
I can confirm, this works now pretty well again!
Thank you for the fast help. 🙂

**Comment by BusterNeece** [comment]
Thank y'all for the quick responses!
