### ISSUE TITLE
Stations go offline with current rolling and stable releases - falling back to Rolling Release 0440685 solves it

### ISSUE THREAD

**Issue by knakatsu** [AzuraCast/AzuraCast#6743]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

0440685

### What happened?

Ever since I left #[0440685](https://github.com/AzuraCast/AzuraCast/commit/04406853ec6bac172de306d204b33795ef8bf3ce) and moved to stable, I have been seeing stations go offline and fallback to error.mp3 for no apparent reason.  I don't remember the first release since [0440685](https://github.com/AzuraCast/AzuraCast/commit/04406853ec6bac172de306d204b33795ef8bf3ce) where I first noticed this.  Somewhere around the time you added the Donate banner.  I just reverted to a backup server from #[771108a](https://github.com/AzuraCast/AzuraCast/commit/771108a5a87f61abcd9470b90649a6a724ed83ef) and the problem has gone away.

Before I abandoned ship, I did notice that I was seeing a lot of stuff like this in the logs:

2023/11/18 14:23:34 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2023/11/18 14:23:34 [lang:3] API nextsong - Response (200): false

I hope that helps...

### Relevant log output

```shell
2023/11/18 14:23:34 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2023/11/18 14:23:34 [lang:3] API nextsong - Response (200): false
```

**Comment by BusterNeece** [comment]
@knakatsu We've had some issues with SSL certificates, but I'm not sure that would cause the problems you're experiencing here. It may still be worth updating to see if things have improved as a result of recent updates.

**Comment by knakatsu** [comment]
Thanks for the reply and I agree that this isn't a cert issue.  I have >1000 concurrent listeners so can't afford to take the chance.  I am currently stable on a backup server with #[0440685](https://github.com/AzuraCast/AzuraCast/commit/04406853ec6bac172de306d204b33795ef8bf3ce).  

I do have the #[771108a](https://github.com/AzuraCast/AzuraCast/commit/771108a5a87f61abcd9470b90649a6a724ed83ef) instance still running on my primary server and stations are going offline randomly.  Let me know if there is anything I can test.  I will also attach a Liquidsoap log.  Thanks for looking at this.
[liquidsoap.log](https://github.com/AzuraCast/AzuraCast/files/13403179/liquidsoap.log)

**Comment by knakatsu** [comment]
@BusterNeece  Bump.  I upgraded to #[38d9be3](https://github.com/AzuraCast/AzuraCast/commit/38d9be3c65ea2e47ae545a01ff4dd41cd64f6406) and am still seeing this issue.  It's seemingly random and it reverts to error.mp3 for 10-20 seconds then re ques.

`2023/12/12 09:35:01 [on_metadata.1587:3] Content type is {audio=pcm(stereo)}.
2023/12/12 09:35:01 [on_track.3175:3] Content type is {audio=pcm(stereo)}.
2023/12/12 09:35:01 [cross_before.798:3] Content type is {audio=pcm(stereo)}.
2023/12/12 09:35:01 [buffer.1595:3] Content type is {audio=pcm(stereo)}.
2023/12/12 09:35:01 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/6/liquidsoap/feedback' with body: {
2023/12/12 09:35:01 [lang:3]   "song_id": "fddc5854f5aee974ebaf3f4963fb97fb",
2023/12/12 09:35:01 [lang:3]   "playlist_id": "7",
2023/12/12 09:35:01 [lang:3]   "media_id": "6083"
2023/12/12 09:35:01 [lang:3] }
2023/12/12 09:35:03 [lang:3] API nextsong - Response (522): 
2023/12/12 09:35:03 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/6/liquidsoap/nextsong' with body: 
2023/12/12 09:35:03 [lang:3] API feedback - Response (522): 
2023/12/12 09:35:05 [lang:3] API nextsong - Response (522): 
2023/12/12 09:35:05 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/6/liquidsoap/nextsong' with body: 
2023/12/12 09:35:05 [lang:3] API nextsong - Response (200): false
2023/12/12 09:35:05 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/6/liquidsoap/nextsong' with body: 
2023/12/12 09:35:05 [lang:3] API nextsong - Response (200): false
2023/12/12 09:35:05 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/6/liquidsoap/nextsong' with body: 
2023/12/12 09:35:05 [lang:3] API nextsong - Response (200): false
2023/12/12 09:35:05 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/6/liquidsoap/nextsong' with body: 
2023/12/12 09:35:05 [lang:3] API nextsong - Response (200): false
2023/12/12 09:35:05 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/6/liquidsoap/nextsong' with body: 
2023/12/12 09:35:06 [lang:3] API nextsong - Response (200): false
2023/12/12 09:35:06 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/6/liquidsoap/nextsong' with body: 
2023/12/12 09:35:06 [lang:3] API nextsong - Response (200): false
2023/12/12 09:35:06 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/6/liquidsoap/nextsong' with body: 
2023/12/12 09:35:06 [lang:3] API nextsong - Response (200): false`

**Comment by Moonbase59** [comment]
Side note: I’ve seen symptoms like these when the system is overloaded (i.e., too much CPU load), for instance from using ReplayGain, reindexing hundreds of thousands song, or using a video stream and Liquidsoap/ffmpeg can’t keep up.

You can check your stream server logs (Icecast/Shoutcast) for things like `WARN source/_source_read Nothing received on /radio.mp3 for 3 seconds`. If you find many of these, above could be the reason.

**Comment by BusterNeece** [comment]
@knakatsu Curious on your station...how long do you have it set to build the queue out for, and how many stations are on that installation?

If the `nextsong` command returns the string `false`, that means it literally has no next song to instruct Liquidsoap to play at that point, i.e. it thinks the queue's completely empty, so it's just telling Liquidsoap to check again later. In these periods, basically LS will just keep checking over and over, meanwhile falling back to its offline/default error message if there aren't any local playlists it knows about to fall back upon.

It's possible that AzuraCast just isn't building the queue up for your station fast enough, which could happen if there were numerous very short tracks, too short of an overall queue, and/or too long of an interval between Now Playing updates for your station. Debugging these kinds of problems are difficult, but if Liquidsoap is working correctly and sending requests and just getting `false` back, then it suggests it's something wrong with our ability to build and maintain the queue.

**Comment by knakatsu** [comment]
@BusterNeece I have 5 stations, each with 4 mountpoints.  Good question on the queue setting.  I don't know how to set or even check it.  None of my content is less than a minute in length so I don't think that's the problem.

I am using High Performance Now Playing Updates for Websocket connections.  I'm curious to explore the overall queue length and Now Playing update interval possibilities.  Any suggestions are appreciated.  Thanks again.

**Comment by BusterNeece** [comment]
@knakatsu Station queue length is set in the station profile. It's an advanced setting and should be under AutoDJ.

You can view the upcoming queue from Broadcasting on the left side menu.

That number of stations shouldn't really be causing such an overload that we're getting behind on queue, so I'm curious what's going on there.

**Comment by knakatsu** [comment]
@BusterNeece Thank you!  I have set each station queue to 5 and will watch the logs.  If you would be interested in a paid gig just to do an administrative review of my site, check settings, review logs, make recommendations, etc., I would be happy to discuss (not sure if DM'ing is even supported here).  In any case, thanks again for the great work and great project!

**Comment by knakatsu** [comment]
@BusterNeece The increase in queue length made no difference.  As I mentioned initially, I have #[0440685](https://github.com/AzuraCast/AzuraCast/commit/04406853ec6bac172de306d204b33795ef8bf3ce) running perfectly on a backup server.  At this point, I would just like to install #[0440685](https://github.com/AzuraCast/AzuraCast/commit/04406853ec6bac172de306d204b33795ef8bf3ce) on my primary as well.  I see two options:

1. You mentioned in [another thread](https://github.com/AzuraCast/AzuraCast/discussions/3873) that it is not possible to install an older version using the Docker installation except by using the Local Development instructions.  Where are they?
2.  Since I have it running on another server, is it possible to just replicate that instance via `docker commit/save/load`, rsync the Azuracast volumes, and update the docker-compose.yml to point to the replicated images?

Let me know which you think is most viable.  Thank you.

**Comment by knakatsu** [comment]
I increased the queue length from 3 to 5 songs and that seems to have "fixed" the station actually going offline but the logs remain full of the errors noted above.  I'm closing this as I don't think it will get resolved.
