### ISSUE TITLE
Icecast instance won't run after update to 0.19.2

### ISSUE THREAD

**Issue by cafecitopuro** [AzuraCast/AzuraCast#6746]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

0.19.2

### What happened?

After updating to 0.19.2, the Icecast instance for my station won't run; trying to start/restart the service results in an error (specifically, I get `SupervisorException at /var/azuracast/www/src/Exception/SupervisorException.php L69: station_1:station_1_frontend encountered an error: SpawnErrorException`). I can see the public page for the station in the browser and the now-playing tracks update, but of course there's no sound / pressing play gives back a 500 Internal Server Error for the GET. Trying to load the stream URL gives the same 500 error. When I look at the Icecast credentials in the station's profile, it lists the port as 0 which seems odd. 

<img width="707" alt="Captura de Pantalla 2023-11-18 a la(s) 5 46 08 p m" src="https://github.com/AzuraCast/AzuraCast/assets/60331056/b397d53b-50ad-471c-9364-85b228aeb3a3">

I've only customized some of the styling of the app; Azuracast is running with default ports, no custom server/broadcast config. I've tried running the update commands again & restarting the container. I'll try rolling back to my last backup but having trouble locating the backup file. 

The Icecast error log is below. Any thoughts are much appreciated! Thank you for this excellent software!!!

### Relevant log output

```shell
[2023-11-18  17:18:30] WARN cfgfile/config_get_port port out of range, 0
[2023-11-18  17:18:30] WARN xml/parsing warning: 
[2023-11-18  17:18:30] WARN xml/parsing failed to read element "port" within "listen-socket" at line 21
[2023-11-18  17:18:30] WARN cfgfile/_parse_root No listen-socket defintions
[2023-11-18  17:18:30] EROR main/fatal_error FATAL: error parsing config file (/var/azuracast/stations/ochomil/config/icecast.xml)
[2023-11-18  17:18:30] EROR main/fatal_error XML config parsing error
```

**Comment by BusterNeece** [comment]
@cafecitopuro What version were you on before 0.19.2? It seems to think your port number is zero, which obviously isn't correct. Can you try setting it back to what it was before the update by editing the profile?

**Comment by cafecitopuro** [comment]
I was on 0.19.1. I switched the Icecast port to 8000 and all's well. Thank you!
