### ISSUE TITLE
Auto-assigning folders to playlists strange behaviour

### ISSUE THREAD

**Issue by mishcazzulani** [AzuraCast/AzuraCast#6748]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #eab3cfe (2023-11-19 3:46) • Docker • PHP 8.2

### What happened?

Hello, I have enabled the auto-assign function but it doesn't work as espected. 

Let's say I have a "Jingles" folder assigned to a "Jingles" playlist: if I upload the new files reaching the folder by clicking under the name column (so that the breadcrumb is "Home / Jingles" and the search bar is empty) azuracast doesnt assign any playlist but simply uploads the files in the jingles folder.

If instead I reach the folder by clicking under the the playlists column (so that the breadcrumb is "Home" and the search bar contains "playlist:ingles") azuracast assigns the correct playlist to the new files.

**Comment by BusterNeece** [comment]
@mishcazzulani If you're using the playlist folders, it should still put the items within it into a playlist eventually, though it won't do that immediately in the current version.

**Comment by mishcazzulani** [comment]
You're right, after a couple of minutes I found the files assigned to the playlist. Thank you!
