### ISSUE TITLE
Replay gain still killing station

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#6751]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.3 Stable 

### What happened?

Just reporting on current issues;
• Upgraded to Stable 19.3 from 19.2 a few days ago 
As with last time, station did not restart correctly after update - had to restart broadcasting to kick-start it,

• Tried Replay Gain once more, with no luck;  station didn't restart after applying changes... Reverting to Master_me fixed it instantly, as expected...

Hoping your team ant Toot's @ LS are still devoting some time to these issues...  Keep up the good work ♫

### Relevant log output

```shell
No use.... :P
```

**Comment by LordHelmchen666** [comment]
Did you read this? https://www.azuracast.com/docs/help/optimizing/

**Comment by SpeedyCharly** [comment]
> Did you read this? https://www.azuracast.com/docs/help/optimizing/

Yes... tried all of that to no avail... Thanks all the same ♫

**Comment by LordHelmchen666** [comment]
Did you tag all files with replaygain values? If yes then you can turn on using Replaygain in your Profile whithout overloading CPU.

**Comment by SpeedyCharly** [comment]
Even if I hadn't tagged them all, the radio should work fine until it eventually hits a CPU overload.  As it is now, the station doesn't even come back from the restart to apply the settings changes...

**Comment by LordHelmchen666** [comment]
I found there will be changes in upcoming LS 2.3.x Release. https://github.com/savonet/liquidsoap/commit/42660cebc1029ae532bb22b64f5450752c70fb43
Maybe this will help.
