### ISSUE TITLE
"Play now" option for multiple songs doesn't queue them

### ISSUE THREAD

**Issue by Sella-3DX** [AzuraCast/AzuraCast#6755]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #3b13030 (2023-11-21 1:59)

### What happened?

If you select multiple songs in the media library and then click on "Play Now" they are queued internally from liquidsoap and will be played but they don't show up inside the "Upcoming Song Queue" list.

**Comment by BusterNeece** [comment]
This is by design, as this is how we have to queue songs for immediate playback, and we don't have a reliable way of pulling the Liquidsoap internal queue's contents and displaying them in our own UI.

**Comment by Sella-3DX** [comment]
Then this issue can be closed, thanks for explaining. :)
