### ISSUE TITLE
Cue/fade values ignored if value is 0 (nextsong/annotate response)

### ISSUE THREAD

**Issue by RM-FM** [AzuraCast/AzuraCast#6756]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.2

### What happened?

After I did some test and deeper analysis related to #6749, it turned out that there is another bug. Cue and fade-in/out values that are set to 0 are not handed over to Liquidsoap in next song / annotate response from Azuracast ("liq_" meta data). Instead a default fade duration will be applied. Actually, the result is the opposite from what was intended when setting the value to 0. I think correct behaviour should be to consider 0 as a valid value and not suppress it somehow in the annotate response.

![Bildschirmfoto 2023-11-26 um 16 01 01](https://github.com/AzuraCast/AzuraCast/assets/40538914/be55c83c-4175-418c-80d5-9961404ecc2e)

### Relevant log output

```shell
2023/11/26 09:22:12 [lang:3] API nextsong - Response (200): annotate:title="Dropin 01",artist="RadioMonster.FM",duration="6.00",song_id="827aa2aeadb831c28eb78ad6ead2cf57",media_id="8197",liq_fade_out="0.10",playlist_id="20",jingle_mode="true":media:Dropin 01.mp3
```

**Comment by RM-FM** [comment]
As a quick workaround we have disabled the native Azuracast crossfade feature and replaced the related piece of code in the Liquidsoap config by a slightly adjusted one. We just set 0 as default value for fadein/out and crossfades.

```
def live_aware_crossfade(old, new) =
    if to_live() then
        # If going to the live show, play a simple sequence
        sequence([fade.out(old.source),fade.in(new.source)])
    else
        # Otherwise, use the smart transition
        cross.simple(old.source, new.source, fade_in=0., fade_out=0.)
    end
end

radio = cross(minimum=0., duration=0., live_aware_crossfade, radio)
```

**Comment by PoGo606** [comment]
Hello,

I my case, I've solved it by using "0.1" value in the custom fading time.

**Comment by BusterNeece** [comment]
Fix deploying for this to Rolling right now. Thank you all for the detailed issue!

**Comment by RM-FM** [comment]
@BusterNeece I see that you touched the cue out  related code only. Will this fix the fade in/out issues too? Fade duration felt back to default as well on fade duration of 0.

**Comment by BusterNeece** [comment]
@RM-FM you are incorrect; the update allows for "0" or "0.0" values for both fades and cues.

**Comment by RM-FM** [comment]
@BusterNeece Tested the latest rolling release. It seems that fade-ins are now behaving correctly. But I'm not sure if allowing "cue out" to be 0 is a good idea. There is no way to distinguish between 0 and null/empty in the GUI. All my jingles didn't play anymore because the had cue out set to 0.

**Comment by unudelaradio** [comment]
Hello!

I tested the latest rolling release today and especially the 0 and 0.0 values on Normal Mode. So basically when setting Normal Mode to 0 is the same thing with Disable Crossfading. The thing is that the cue/mix points are ignored too. I was expecting this 0 value to disable only that fade in effect... but unfortunately all cue points setted in Visual Cue Editor are ignored too. 

So for me the best solution is still the 0.1 value. Even if sometimes this causes crackles at the beginning of the song. But at least the Cue Mix Poins are not ignored.

Maybe, in the future, an extra Crossfade Method, called Custom Cue Points will be implemented.

All the best!

**Comment by BusterNeece** [comment]
@unudelaradio We revisited this issue in the last few versions of AzuraCast and have made it so that 0.0 is once again a legitimate value that can be provided, and if you want to fall back to the default value, there's now a "clear" button under each input to reset it to a blank field. This should allow for both scenarios, where you want an actual fade/cue/etc. of 0.0, and where you want to remove the value and reset it to default.
