### ISSUE TITLE
Visual Cue Editor throws error if opened with a .m4a file

### ISSUE THREAD

**Issue by Sella-3DX** [AzuraCast/AzuraCast#6757]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #ee9b7d8 (2023-11-26 8:52)

### What happened?

If you edit a media (an .m4a file from iTunes) and go to "Visual Cue Editor" you get the following error message:
![image](https://github.com/AzuraCast/AzuraCast/assets/147769367/e90df54d-4b12-4771-b8e7-74625afb0474)

Is this by design or a bug?

**Comment by BusterNeece** [comment]
@Sella-3DX The problem with audiowaveform is valid (it can't generate server-side waveforms for some audio formats) but the exception was rather inelegantly documented in the message; I've fixed it to be clearer about the error message. If you can generate the waveform client-side (as you can with M4A's) then it's a nonissue, it just can't server-side cache it.

**Comment by Sella-3DX** [comment]
Good idea to change the text but I would rather prefer it not to be an exception but some kind of message like "You can't generate waveforms for this file type". Showing an exception to one who is not really familiar with coding and such is not that great I guess. A error message on the other is IMHO a bit more understandable.🙂
Oh and while we're talking about exceptions and messages... IF you consider making an error message out of the exception could you maybe add one for this exception too?

`StationUnsupportedException at /var/azuracast/www/src/Middleware/StationSupportsFeature.php L23: This feature is not currently supported on this station.`

This is thrown when the song requests are disabled but a user moves onto the embed (or public page) for song requests.
