### ISSUE TITLE
SHOUTCast stream info problem when use proxy

### ISSUE THREAD

**Issue by MyTheValentinus** [AzuraCast/AzuraCast#676]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 18.04

**Describe the bug**
When you enable web proxy for stations, some url of shoutcast or icecast is not accesible or return wrong content.
Like https://yourproxy.auzracast.domain.com/radio/8000/played?type=json&sid=1
But when you type directly the good ip with port, it's good.
http://192.168.0.1:8000/played?type=json&sid=1

**To Reproduce**
1. Go to https://yourproxy.auzracast.domain.com/radio/8000/played?type=json&sid=1
2. Go to http://192.168.0.1:8000/played?type=json&sid=1
3. See not good returned content

**Comment by MyTheValentinus** [comment]
Hello,

This issue is fixed with my last PR for docker install. To apply this patch to the standard install update the file locate in `/util/ansible/roles/nginx/templates/default.j2` with my fix.

Thanks

**Comment by MyTheValentinus** [comment]
Hello, is good for docker installation do you plan to update ansible role ?
Thanks

**Comment by SlvrEagle23** [comment]
@MyTheValentinus Done and done on both. Sorry I missed the PR on the nginx container repo. Fix has been applied to both now.
