### ISSUE TITLE
Autodj dont fades when streamer connects or disconnects

### ISSUE THREAD

**Issue by netbladenl** [AzuraCast/AzuraCast#6763]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#1657f22

### What happened?

Helllo!

Anybody else noticed this behaviour in the latest version? When a streamer disconnects, and the AutoDJ starts to play, part of the latest song (the part where AutoDJ previously stopped), is still playing for a few seconds, mixed with the jingle or song that should normaly start.

Also, i noticed some refresh/update deelays for about 30 seconds in Now Playing, Listeners Reports, Upcoming Song Queue. This reminds me of an old problem in the older versions, when now playing updates were too slow.

Hope you could identify this behaviour and fix it somehow.

Many thanks!

### Relevant log output

```shell
2023/11/29 07:47:05 [lang:3] DJ Source connected! Last authenticated DJ: henk - [("Host", "streaming.vanleijden.net:9005"), ("icy-name", "No Name"), ("icy-pub", "0"), ("icy-br", "320"), ("content-type", "audio/mpeg")]
2023/11/29 07:47:05 [lang:3] API djon - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/djon' with body: { "user": "henk" }
2023/11/29 07:47:05 [lang:3] API djon - Response (200): true
2023/11/29 07:47:05 [input_streamer:3] Decoding...
2023/11/29 07:47:11 [live_fallback:3] Switch to metadata_map.2 with transition.
2023/11/29 07:47:11 [replay_metadata.10:3] Content type is {audio=pcm(stereo)}.
2023/11/29 07:47:11 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: { "artist": "", "title": "Live Broadcast" }
2023/11/29 07:47:11 [lang:3] API feedback - Response (200): true
2023/11/29 07:47:33 [input_streamer:2] Feeding stopped: Ffmpeg_decoder.End_of_file.
2023/11/29 07:47:33 [lang:3] API djoff - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/djoff' with body: { "user": "henk" }
2023/11/29 07:47:33 [lang:3] API djoff - Response (200): true
2023/11/29 07:47:39 [live_fallback:3] Switch to cross with forgetful transition.
2023/11/29 07:47:39 [replay_metadata.11:3] Content type is {audio=pcm(stereo)}.
2023/11/29 07:47:39 [cue_playlist_daily:3] End of track reached before cue-out point.
2023/11/29 07:47:39 [playlist_daily:3] Prepared "/var/azuracast/stations/popstation/media/00's Pop Rock/35_-_stereophonics_-_maybe_tomorrow.mp3" (RID 11).
2023/11/29 07:47:39 [next_song:3] Prepared "/var/azuracast/stations/popstation/media/90s 3fm/032_-_live_-_lightning_crashes.mp3" (RID 10).
2023/11/29 07:47:39 [autodj_fallback:3] Switch to dynamic_startup with forgetful transition.
2023/11/29 07:47:39 [replay_metadata.12:3] Content type is {audio=pcm(stereo)}.
2023/11/29 07:47:39 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
2023/11/29 07:47:39 [lang:3]   "song_id": "2ef2fa002f315c13c151c66999374580",
2023/11/29 07:47:39 [lang:3]   "playlist_id": "1",
2023/11/29 07:47:39 [lang:3]   "media_id": "13"
2023/11/29 07:47:39 [lang:3] }
2023/11/29 07:47:39 [output_file:3] Source failed (no more tracks) stopping output...
2023/11/29 07:47:39 [lang:3] Recording stopped: Switching from /var/azuracast/stations/popstation/temp/henk/stream_20231129-074711.mp3.tmp to /var/azuracast/stations/popstation/temp/henk/stream_20231129-074711.mp3
2023/11/29 07:47:39 [dynamic_startup:3] Switch to cue_next_song.
2023/11/29 07:47:39 [replay_metadata.13:3] Content type is {audio=pcm(stereo)}.
[mp3float @ 0x7f3899e50200] Could not update timestamps for skipped samples.
2023/11/29 07:47:39 [cue_next_song:3] Cueing in...
2023/11/29 07:47:39 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2023/11/29 07:47:39 [lang:3] API feedback - Response (200): true
2023/11/29 07:47:39 [cross:3] Analysis: -9.342196dB / -36.078688dB (6.08s / 6.08s)
2023/11/29 07:47:39 [cross.smart:3] No transition: using default.
2023/11/29 07:47:39 [cross_before.4:3] Content type is {audio=pcm(stereo)}.
2023/11/29 07:47:39 [buffer.7:3] Content type is {audio=pcm(stereo)}.
2023/11/29 07:47:39 [cross_after.4:3] Content type is {audio=pcm(stereo)}.
2023/11/29 07:47:39 [buffer.8:3] Content type is {audio=pcm(stereo)}.
```

**Comment by DAMaia1989** [comment]
Hi @netbladenl thanks for opening this post. In fact, I've been struggling with this problem for a long time and no one has come up with a solution yet.

**Comment by fidegr** [comment]
Same problem. 

2023/12/04 01:11:40 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
2023/12/04 01:11:41 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
2023/12/04 01:11:42 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/8/liquidsoap/auth' with body: { "user": "unidadmovil", "password": "xxxxxxx" }
2023/12/04 01:11:42 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
2023/12/04 01:11:43 [lang:3] API auth - Response (200): true
2023/12/04 01:11:43 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
2023/12/04 01:11:43 [lang:3] DJ Source connected! Last authenticated DJ: unidadmovil - [("Authorization", "Basic dW5pZGFkbW92aWw6aG9uZGFzbGlicmVz"), ("Host", "95.217.177.114:8065"), ("User-Agent", "butt 0.1.30"), ("Content-Type", "audio/mpeg"), ("ice-name", "no name"), ("ice-public", "0"), ("ice-audio-info", "ice-bitrate=128;ice-channels=2;ice-samplerate=48000"), ("Expect", "100-continue")]
2023/12/04 01:11:43 [lang:3] API djon - Sending POST request to 'http://127.0.0.1:6010/api/internal/8/liquidsoap/djon' with body: { "user": "unidadmovil" }
2023/12/04 01:11:44 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
2023/12/04 01:11:44 [lang:3] API djon - Response (200): true
2023/12/04 01:11:44 [input_streamer:3] Decoding...
2023/12/04 01:11:45 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
2023/12/04 01:11:46 [output_file:2] Warning: there may be an infinite sequence of empty tracks!

**Comment by roeku** [comment]
> I have the same issue on both stable and rolling releases. I've had to disable fading until fixed as fading back from live continues playing the last song for 5 seconds(depending on the crossfade time) then crossfades to a new song.

I have the exact same issue, is there an update on this?

**Comment by roeku** [comment]
I believe the issue might be resolved with the new liquidsoap RR

https://github.com/savonet/liquidsoap/issues/3318
