### ISSUE TITLE
vertical scrollbar embedded player 

### ISSUE THREAD

**Issue by karndt84** [AzuraCast/AzuraCast#677]
**Installation method**
Docker

**Host OS (for Docker installations)**
Debian 9.5.0

How can I deactivate the vertical scrollbar in the embedded player (via iframe)?
ordinary css instructions have no effect.

![image](https://user-images.githubusercontent.com/9092791/42973797-f2a9af70-8bb4-11e8-9707-b29a558f2cd2.png)

![image](https://user-images.githubusercontent.com/9092791/42973817-0a0a523c-8bb5-11e8-9da9-ffa748c4d91f.png)

**Comment by karndt84** [comment]
Oh, I had a mistake.
If you set the width in iframe to 115%, then the scrollbar disappears

**Comment by ErnestPH** [comment]
Thanks! been looking for a solution for this one
