### ISSUE TITLE
Demo Website Bad Gateway

### ISSUE THREAD

**Issue by royaltongue** [AzuraCast/AzuraCast#6782]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Visit https://demo.azuracast.com/

### Relevant log output

```shell
Cloudflare Bad Gateway Error 502
```

**Comment by royaltongue** [comment]
Sorry, refreshed again and now I see the message that it refreshes on the hour. Bad timing on my part!

**Comment by royaltongue** [comment]
Actually, now that it's back up, it shows the same error.

**Comment by Moonbase59** [comment]
Don’t fret, probably due to some change just being made.

**Comment by BusterNeece** [comment]
Fixed now.
