### ISSUE TITLE
Service Not Running: hpnp

### ISSUE THREAD

**Issue by PeWe79** [AzuraCast/AzuraCast#6784]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#f2dd535 (2023-12-07 6:38)

### What happened?

HpNp Service Not Running & when try to start HpNp still not working.

```
SupervisorException at /var/azuracast/www/src/Exception/SupervisorException.php L69: hpnp encountered an error: SpawnErrorException
```

**Comment by Moonbase59** [comment]
See also: https://github.com/AzuraCast/AzuraCast/issues/6771#issuecomment-1844772735

**Comment by PeWe79** [comment]
@Moonbase59 noted.

**Comment by Moonbase59** [comment]
How can I do that correctly?

Just `hpnp` dumps core…

```
root@radio:/var/azuracast# ./docker.sh bash
azuracast@56f56c34c5b8:~/www$ hpnp
Illegal instruction (core dumped)
azuracast@56f56c34c5b8:~/www$ 
```

**Comment by Moonbase59** [comment]
@BusterNeece This is what `gdb` shows:

```
(gdb) file /usr/local/bin/hpnp
Reading symbols from /usr/local/bin/hpnp...
(No debugging symbols found in /usr/local/bin/hpnp)
(gdb) run
Starting program: /usr/local/bin/hpnp -v --debug /usr/local/bin/hpnp
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x000055cc366f62a8 in ?? ()
(gdb) 
```

**Comment by BusterNeece** [comment]
@Moonbase59 Ready for updating.

**Comment by Moonbase59** [comment]
Hooray, I can see event messages (in curl; why do you send comment lines?)!

**Comment by BusterNeece** [comment]
@Moonbase59 I'd bet CORS failing here is because it's sending the 404...I bet it's not taking that hyphen in the station name gracefully.

**Comment by Moonbase59** [comment]
Hm. I’ve been using hyphens (instead of underlines) ever since, since a station shortcode can’t have "_" for the azuracast_xmltv to work.

**Comment by BusterNeece** [comment]
Pushing up changes:
 - Handle hyphens in station names
 - Add support for multiple station subscriptions at once via passing `station_1,station_2,station_3` at the end of the URL
 - The `payload` for nowplaying updates is changed slightly to go one level deeper, the response now looks like:
```json
{
  type: 'nowplaying',
  payload: {
    station: 'azuratest_radio',
    np: {},
    triggers: []
  }
}```
...since, if you can subscribe to multiple stations, it's helpful to immediately recognize at the base what station is being updated, and the `triggers` are which webhooks triggered along with that NP update (i.e. changed song, DJ live/unlive, etc)

**Comment by BusterNeece** [comment]
Everything's golden on my production instances and it seems they're working good on yours, closing this for now as completed.

**Comment by Moonbase59** [comment]
Yep, client script also works fine and rather fast:

![Auswahl_314](https://github.com/AzuraCast/AzuraCast/assets/3706922/01c3119d-7c6b-4779-bba9-b458a99a20bb)

![Auswahl_315](https://github.com/AzuraCast/AzuraCast/assets/3706922/660fb71d-9dd2-4917-943e-e2601ac877bc)

**Comment by Moonbase59** [comment]
@BusterNeece FYI: Did some load tests (some stations _do_ have many listeners after all).

Set up 1000 curl’s starting on 0.1s increments and running for 5min ea., subscribing to 3 stations ea.:

- 425 succeeded in making a connection
- 179 of these 425 got HTTP 500, and
- 246 delivered good JSON data

Might not be representative, just wanted to let you know.

Thanks for all the work!
