### ISSUE TITLE
Jingles are crossfaded although it is not desired

### ISSUE THREAD

**Issue by RadioHerzblut** [AzuraCast/AzuraCast#6797]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #779fdc0 (2023-12-13 18:52)

### What happened?

The old problem with "not fading" has crept back into this realease.

Currently, no " 0 " parameters are processed as a valid value.

With the following parameters it works.

![image](https://github.com/AzuraCast/AzuraCast/assets/150465082/a478aa02-3aa3-4c01-abf2-9682107a744c)

**Comment by Vaalyn** [comment]
seems to be related to the fix for https://github.com/AzuraCast/AzuraCast/issues/6787#issuecomment-1848939379

**Comment by BusterNeece** [comment]
This should be fixed in the latest Rolling Release.
