### ISSUE TITLE
Intentional CORS error when trying to access demo site with my HPNP example?

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6798]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #5755b60 (2023-12-12 20:42)

### What happened?

I try to keep my [HPNP example code](https://gist.github.com/Moonbase59/d42f411e10aff6dc58694699010307aa) up-to-date with AzuraCast, and it worked fine with the demo instance before.

As of today, I get a CORS error. Is this intentional?

![Auswahl_321](https://github.com/AzuraCast/AzuraCast/assets/3706922/ae3eae93-5be7-4362-a33d-ee2bc6818c6b)

(Would be nice if this worked, so others can benefit from my example code.)

**Comment by BusterNeece** [comment]
@Moonbase59 You're gonna wanna check your mentions on other GH issues.

**Comment by Moonbase59** [comment]
Yup, thanks, just read https://github.com/AzuraCast/AzuraCast/issues/6774#issuecomment-1854207217
