### ISSUE TITLE
Cannot login from web interface ..no error

### ISSUE THREAD

**Issue by justjess59** [AzuraCast/AzuraCast#680]
Traditional install

Hosted on droplet from DigitalOcean

At login MyIP\login get login prompt but cannot login with email and password , just goes back to login screen from any browser, I expect  perhaps the account is locked but no message indicating this.

Any help on this would be greatly appreciated

**Comment by SlvrEagle23** [comment]
@justjess59 My apologies for the delay in responding to this message. Were you able to resolve the situation, or do you still need help recovering your account?

**Comment by justjess59** [comment]
Yes I cannot seem to login still

**Comment by SlvrEagle23** [comment]
You can reset the password for any given account by logging into the SSH terminal of the server and run: 

```bash
php /var/azuracast/www/util/cli.php azuracast:account:reset-password your-email-address@example.com
```

**Comment by justjess59** [comment]
When I run this i get the following error, please pardon me being such a noob to linux 

![image](https://user-images.githubusercontent.com/32026162/44553873-f5c38100-a6fc-11e8-8ac0-e0a00893ac84.png)

**Comment by SlvrEagle23** [comment]
@justjess59 I'm not sure you used the Traditional installation method. It looks like you used the Docker installation method. Does this work?

```bash
docker-compose run --rm cli azuracast_cli azuracast:account:reset-password your-email-address@example.com
```

**Comment by justjess59** [comment]
No this did not work and if I remember I did do the traditional install , is there a directory I need to change to from root?

**Comment by justjess59** [comment]
Im sorry that  did not work and if I remember I did do the traditional install , is there a directory I need to change to from root?

**Comment by SlvrEagle23** [comment]
@justjess59 Send me an e-mail at buster@busterneece.com with your server details and I'd be happy to take a look.

**Comment by SlvrEagle23** [comment]
@justjess59 I haven't heard any follow-up on this issue, so I don't know if the issue has been fixed or if further action is required on my end. If you don't mind, could you please update me on the status of this issue?

If I don't hear any updates for a while, I'll close the issue as resolved.

**Comment by Vaalyn** [comment]
Since this issue has been stale for quite some time I'll close it for now.
