### ISSUE TITLE
Port in URL

### ISSUE THREAD

**Issue by wegGehamstert** [AzuraCast/AzuraCast#6806]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#3776085

### What happened?

In the newest rolling release, there was the port added to the url. 
Is there any way to remove it? My stream dont work any more because of this:
https://stream.breathfm.de:3007/hls/mainstream/live.m3u8

**Comment by BusterNeece** [comment]
@wegGehamstert Are you using the "Prefer Browser URL" setting? I assume you're running AzuraCast through a proxy and serving nginx on the port specified, and it's mistakenly thinking that's the port you're using on your browser.

**Comment by wegGehamstert** [comment]
Good to know, i switched to the Stable release yesterday, so i couldn't test it out now.
But yes i use the "Prefer Browser URL". That would be the solution. Thank you!
