### ISSUE TITLE
HLS streams on Mobile Safari stuck on lofi

### ISSUE THREAD

**Issue by mb0x88** [AzuraCast/AzuraCast#6811]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

19.3

### What happened?

Mobile Safari streams HLS in lofi and doesn't change to higher quality automatically, not an issue on Desktop Safari or other browsers on Android

Trying to ascertain if this is an azuracast issue or something more to do with Mobile Safari

**Comment by BusterNeece** [comment]
I'm not sure either, but I'm reasonably confident our HLS stream is fully compliant as it broadly works across every other platform we've tested. We can test more with mobile safari, but it's harder to test with than some other browsers.

**Comment by gAlleb** [comment]
I do confirm such behavior. Also it happens in some apps. For example on my iOS app I have to add explicitly subtream m3u8 file with desired bitrate (not the main one) cause it won't change to higher quality by itself. Some apps and browsers do have such problem. But on azuracast's side probably there is little that could be done.

**Comment by mb0x88** [comment]
it seems that if i play the stream once it gets stuck on lofi, if i then restart the stream(stop and start it) it figures itself out and changes to hifi
