### ISSUE TITLE
Title bar in music files vanishes after selecting an option

### ISSUE THREAD

**Issue by Sella-3DX** [AzuraCast/AzuraCast#6814]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #8b15a55 (2023-12-21 23:00)

### What happened?

If you select a song (or even multiple) in the music files section, then select a playlist for them and "Save" - the title bar vanishes and you have to reload the site.

Besides that in the upper right corner it says "Playlist cleared [...]" for every action you do with the playlists.

https://github.com/AzuraCast/AzuraCast/assets/147769367/1f21a097-8f1b-4a5c-9be1-4de1d40c20df

**Comment by Moonbase59** [comment]
Confirm (RR 8b15a55 (2023-12-21 23:00)):
- the button bar vanishes (Playlists, Move, More, Delete, …)
- "Playlists cleared" is displayed on top of the correct message
