### ISSUE TITLE
Streaming Software Documentation Typo

### ISSUE THREAD

**Issue by mdrxy** [AzuraCast/AzuraCast#6817]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.3

### What happened?

"PlayIt Live" should be a h2 like the other softwares but it is a h1, which causes it to not display in the sidebar table of contents. Its subsections should also be incremented by 1 (h2 -> h3, h3 -> h4, etc.)

**Comment by BusterNeece** [comment]
Fixed. Thank you!
