### ISSUE TITLE
LE doesn't work

### ISSUE THREAD

**Issue by impli-osx** [AzuraCast/AzuraCast#682]
**Installation Method:** Docker
**Host OS (if using Docker):** Debian 9.4

Hi,

I've activated HTTPS on the azuracast configuration and it's work.
But when I try to use

> ./docker.sh letsencrypt-create

I have this return

> Starting azuracast_influxdb_1 ... done
Starting azuracast_mariadb_1  ... done
Starting azuracast_stations   ... done
Starting azuracast_redis_1    ... done
Starting azuracast_web_1      ... done
2018/07/23 03:33:12 Waiting for: tcp://web:9000
2018/07/23 03:33:12 Connected to tcp://web:9000
Domain is ready to be served via LetsEncrypt!
To reload nginx, please run:
  docker-compose kill -s SIGHUP nginx
2018/07/23 03:33:12 Command finished successfully.
Reloading nginx...
Killing azuracast_nginx_1 ... done
Nginx reloaded; letsencrypt certificate has been set up.

But the HTTPS on my website stay unsecure (no certificate).

Thank's.

**Comment by MyTheValentinus** [comment]
Hello,
Je suis français aussi ;)
I'm waiting your investigation before work on this issue.
Thanks

**Comment by impli-osx** [comment]
Hi,

Find a "hacky" solution : 

- Generate a wildcard certificate via Lets Encrypt (a simply certificate is avalaible)
- Copy and rename the fullchain.pem and privkey.pem like 
>cp /etc/letsencrypt/live/yourdomain/fullchain.pem /var/lib/docker/volumes/azuracast_nginx_letsencrypt_certs/_data/ssl.crt
cp /etc/letsencrypt/live/yourdomain/privkey.pem /var/lib/docker/volumes/azuracast_nginx_letsencrypt_certs/_data/ssl.key

- Modify the icecast.xml in /var/lib/docker/volumes/azuracast_station_data/_data/yourstation/config/icecast.xml like
><ssl-private-key>/var/lib/docker/volume/azuracast_nginx_letsencrypt_certs/_data/ssl.key</ssl-private-key>
<ssl-certificate>/var/lib/docker/volume/azuracast_nginx_letsencrypt_certs/_data/ssl.crt</ssl-certificate>

- Go on your azuracast directory (directory with the docker.sh file) and type
>docker-compose restart


Now all the stations & backend are secure with Letsencrypt.

See ya.

**Comment by MyTheValentinus** [comment]
Uhmmm okay, this solution is very crappy. I will test in next days and come back to you when i would have make some tests.

**Comment by impli-osx** [comment]
It's a crappy solution, yep. But for the moment, my server is not in production. 

I will install a full nginx server next day and I'll try with proxys. You known why the certificates generate with `./docker.sh letsencrypt-create` is not valide ?

**Comment by MyTheValentinus** [comment]
I'm not sure that was the certificate he is not valid. I think it's nginx config problem.
I never tested this feature for the moment. I will test soon.

**Comment by impli-osx** [comment]
When a make the test (./docker.sh letsencrypt-create) I haven't install a nginx server (standalone). I try this command with the docker install only. So I don't see a nginx conf with docker. (But I can miss it.)

**Comment by impli-osx** [comment]
Hm.

Le script ne fait qu'un symlink. 
Et vu le code de la fonction de letsencrypt-create() dans docker.sh, je ne suis pas sûr que le répertoire source pour les symlink soient corrects (les certifs ne sont pas pris dans /etc/letsencrypt/live et aucun répertoire n'est défini pour l'enregistrement des certifs dans la fonction letsencrypt-create()).

**Comment by MyTheValentinus** [comment]
Ha oui, autant pour moi j'ai lu trop vite.
Je vais tester tout ça dès que j'aurais trouver une ip publique à dispo.

**Comment by impli-osx** [comment]
Correction, y'a bien un webroot de donné dans la fonction letsencrypt-create(), mais elle ne correspond pas du tout au script que tu m'as donné.
Autrement dit, les certifs qui sont collés dans /etc/nginx/ssl ne doivent pas être les bons. Ou alors j'ai raté une étape.

**Comment by gondp** [comment]
Hello, I have the same problem, I have generated a certificate and in icecast it gives us an error, with nginx it works perfectly.

[2020-04-16  20:08:38] WARN connection/get_ssl_certificate Invalid cert file /etc/nginx/ssl/ssl.crt (system lib)

The symbolic link to the letsencrypt certificate has been created

 $ dir /etc/nginx/ssl# ls -la

lrwxrwxrwx 1 root root   56 Apr 16 19:44 server.crt -> /etc/letsencrypt/live/DOMAIN/fullchain.pem
lrwxrwxrwx 1 root root   54 Apr 16 19:44 server.key -> /etc/letsencrypt/live/DOMAIN/privkey.pem

lrwxrwxrwx 1 root root   56 Apr 16 20:07 ssl.crt -> /etc/letsencrypt/live/DOMAIN/fullchain.pem
lrwxrwxrwx 1 root root   54 Apr 16 20:07 ssl.key -> /etc/letsencrypt/live/DOMAIN/privkey.pem
