### ISSUE TITLE
RR 4ab8fe6: (Cosmetic) Updater script scrolls while pulling, layers 29 & 30 shown as 0B/0B but take ~70s

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6821]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #4ab8fe6 (2023-12-25 2:35)

### What happened?

When updating to Rolling Release #[4ab8fe6](https://github.com/AzuraCast/AzuraCast/commit/4ab8fe667b27578869a7cded111bd1edeab80084) (2023-12-25 2:35) via CLI, I observed

- (cosmetic) scrolls while pulling
- pulling layers 29 & 30 took ~70s but both showed "0B/0B"
- update seems much faster than releases before
- update uses much less CPU than releases before (load avg ~2.5 instead of up to 4.7) on 4 CPU VM w/ 4 stations + video stream

![root@radio: -var-azuracast_011](https://github.com/AzuraCast/AzuraCast/assets/3706922/7af29d01-23d2-43c3-a8d0-0b4a9887093d)

**Comment by Sella-3DX** [comment]
Seems to be gone with the newest RR

![image](https://github.com/AzuraCast/AzuraCast/assets/147769367/4507fe45-fc00-48cd-8934-5b1c7cf79457)

**Comment by Moonbase59** [comment]
Now on Rolling Release #[5de2358](https://github.com/AzuraCast/AzuraCast/commit/5de23588f55249890060e4b1ee677c6d61f9c31c) (2023-12-29 1:33).

Looks like this is caused by lines longer than the (default) terminal width of 80 characters.

**Comment by Vaalyn** [comment]
Just FYI: The "Pulling" & "Layers" stuff is directly from Docker / Docker Compose and not something we can control.

If something in their UI / TUI is behaving weirdly you'd need to bring that up on their repository.

**Comment by Moonbase59** [comment]
@Vaalyn Thanks for the info. It’s not a deal-breaker, just looks a little weird. But anyway, we can make our terminal windows wider…

**Comment by BusterNeece** [comment]
So as @Vaalyn mentioned, this is caused by Docker and Docker Compose, though fortunately this is something they've improved upon greatly in recent versions. If you run `./docker.sh install-docker` (and `./docker.sh install-docker-compose`), that can upgrade you to the newest Docker supported by your host OS, which may have improved greatly upon the UX of this particular thing.

**Comment by Moonbase59** [comment]
I wonder if I should do that—this is a Ubuntu VM, and I usually use `apt` for that.

My docker and docker-compose versions are:
```
matthias@radio:~$ docker --version
Docker version 24.0.7, build afdd53b
matthias@radio:~$ docker-compose --version
Docker Compose version v2.21.0
```
