### ISSUE TITLE
Liquidsoap crash after the live broadcast

### ISSUE THREAD

**Issue by PROFLJann** [AzuraCast/AzuraCast#6826]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.3 Stable

### What happened?

Hello,

Since the last update to version 0.19.3 I have the following problem:

If recording is enabled for live broadcasts, Liquidsoap will crash after the live broadcast.
If the live broadcast is not recorded, the problem does not occur.
The transition from AutoDJ to live broadcast is no longer what it once was.
Previously I used version 0.19.1 and there were no problems here.

Unfortunately nothing is shown in the log, it seems like Liquidsoap freezes when the live broadcast ends.
The following message only appears in the Liquidsoap log after approx. 5 minutes after freezing

### Relevant log output

```shell
2023/12/29 00:54:08 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
2023/12/29 00:54:09 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
2023/12/29 00:54:09 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
2023/12/29 00:54:10 [output_file:2] Warning: there may be an infinite sequence of empty tracks!
```

**Comment by netbladenl** [comment]
Has been fixed in the rolling releases; https://github.com/savonet/liquidsoap/issues/3537

There hasn't been a stable release yet since then.
