### ISSUE TITLE
hifi HLS stream stops after a minute (or few) on mobile LTE after update to 246709b

### ISSUE THREAD

**Issue by gAlleb** [AzuraCast/AzuraCast#6827]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

commit 246709b. nginx reverse proxy

### What happened?

Following https://github.com/AzuraCast/AzuraCast/issues/6811

After update to 246709b I have encountered strange behavior on mobile apps. When hifi (192kb/s) is selected manually (e.g. http://radio/hls/radio/aac_hifi.m3u8 or `https` — doesn't matter) and added to play — it stops after a minute or 5 minutes and doesn't resume unless stop/start (or restarts within a minute and starts to stop every few seconds like the speed is very very low). This doesn't happen when `aac_lofi.m3u8` or `aac_midfi.m3u8` are manually selected — they never stop.

I have tried different apps on iOS (VLC, Audio Stream Player, m3u8 Player) — the behavior stays the same. (In mobile browsers hifi never gets selected on iOS when running azuracast public player — so here I can't tell anything.)

Prior to update I have been always selecting hifi HLS stream specifically to play and everything was great. (Even if it had stopped due to mobile tower change or lack of signal it immediately resumed).

I have upgraded once again to latest RR — the issue persists. 
(So now while in a car I have to select `aac_midfi.m3u8` to play :))

Maybe something in my nginx proxy conf
```
server {
            server_name ...;
            index index.php index.html index.htm;
            autoindex off;
            error_log ...;
	    access_log ...;            


 location / {
            proxy_pass                         http://127.0.0.1:5080;
            # Websocket 
            proxy_http_version                 1.1;
            proxy_cache_bypass                 $http_upgrade;
            proxy_set_header Upgrade           $http_upgrade;
            proxy_set_header Connection        "upgrade";
            
            #proxy_set_header Connection $connection_upgrade;
            
            # Proxy headers
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host  $host;
            proxy_set_header X-Forwarded-Port  $server_port;
            proxy_set_header X-Forwarded-Scheme $scheme;            
            proxy_set_header Accept-Encoding "";

            # Proxy timeouts
            proxy_connect_timeout              2400s;
            proxy_send_timeout                 60s;
            proxy_read_timeout                 60s;

            proxy_buffering           off;
            proxy_ignore_client_abort off;
        }



    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/radio/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/radio/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

            listen 80;
            listen [::]:80;
}
 ```

Very very strange.

**Comment by gAlleb** [comment]
Nope. Not nginx proxy conf. Stopped nginx, started nginx proxy manager in container — same result

**Comment by BusterNeece** [comment]
Very bizarre. Definitely not sure how to reliably reproduce this one. If it was an nginx misconfiguration on our end, you'd think it would apply equally to all the HLS streams (which we didn't actually touch in all of our latest caching improvements).

This is pure hearsay on my part, but I heard once that iOS in particular will try to prevent streams from ever exceeding a certain data limit per hour (corresponding to the bandwidth generated by a 128kbps MP3 stream running constantly in that time, so...57MB per hour?) because a great number of iOS users are on metered phone plans and the higher-bandwidth streams are not as beneficial for them while greatly increasing the amount of bandwidth consumed on their plans. I'm not sure either if this *ever* was policy, if it's still policy now, or how to detect or work around this.

**Comment by gAlleb** [comment]
Thank you, @BusterNeece
Indeed very bizarre. Gonna test further. Perhaps I'm fighting windmills and it is just a confluence of circumstances.

**Comment by gAlleb** [comment]
After upgrading to latest RR issue has vanished:) 
Very bizarre but I’m glad. Closing.
