### ISSUE TITLE
api/nowplaying Method not allowed

### ISSUE THREAD

**Issue by PeWe79** [AzuraCast/AzuraCast#6828]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #dd13a5a (2023-12-29 17:28)

### What happened?

Hi,
Api Nowplaying with api/nowplaying not work again with errot "Method not allowed. Must be one of: OPTIONS", but with api/nowplaying/{station_id} work well.

Thank you

**Comment by Moonbase59** [comment]
Confirm same for Rolling Release #[5de2358](https://github.com/AzuraCast/AzuraCast/commit/5de23588f55249890060e4b1ee677c6d61f9c31c) (2023-12-29 1:33):

```json
{
  "code": 405,
  "type": "HttpMethodNotAllowedException",
  "message": "Method not allowed. Must be one of: OPTIONS",
  "formatted_message": "Method not allowed. Must be one of: OPTIONS",
  "extra_data": {
    "class": "HttpMethodNotAllowedException",
    "file": "/var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php",
    "line": 79
  },
  "success": false
}
```
