### ISSUE TITLE
Since a few versions, some iframe embeds show scrollbars again (worked before)

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6829]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #328af6d (2023-12-30 1:16)

### What happened?

Since a few versions, embedded iframes show scrollbars again on the "Request" widget, most notably on Chrome, Chromium, Opera, MS Edge. Firefox only shows a horizontal scrollbar.

This is using the code from my [Gist](https://gist.github.com/Moonbase59/fbe49e4be4ea9e833f29e94c8526455f), which worked nicely before. See the [live test for "Requests" on the demo instance](https://grav1.niteradio.net/wh/iframe-resizer.html).

The "Schedule" widget still works fine ([real page](https://grav1.niteradio.net/sendeplan)), the "Request" widget shows scrollbars ([real page](https://grav1.niteradio.net/musikwunsch)). I had no time to test the other widgets, but they might be affected, too. Unfortunately, I can’t pinpoint the exact rolling release where it started happening, since I only discovered it today. It definitely worked on Rolling Release #[8b15a55](https://github.com/AzuraCast/AzuraCast/commit/8b15a55bad985c3d8eebb0ec2fbff7d7ee2cf7f9) (2023-12-21 23:00), since I did exhaustive tests at that time.

Tested using Rolling Release #328af6d (2023-12-30 1:16) on:
- Firefox 121.0 (Linux Mint)
- Chromium 120.0.6099.129 (Linux Mint)
- Opera One 106.0.4998.19 (Linux Mint)
- MS Edge 120.0.2210.61 (Windows 10)
- Chrome 120.0.6099.144 (Android 9, Smartphone)

![Arbeitsfläche 1_039](https://github.com/AzuraCast/AzuraCast/assets/3706922/e1d91c19-3d13-470f-91c8-bb5bddf4011e)

![Iframr MS Edge](https://github.com/AzuraCast/AzuraCast/assets/3706922/b2d4b78e-04d0-438f-8f67-3381a77eb970)

![Screenshot_20231230-151804](https://github.com/AzuraCast/AzuraCast/assets/3706922/2d52f56c-739b-4b09-a526-84b7f92926b3)

**Comment by Vaalyn** [comment]
Seems to come from the margins that are applied via the `row` class on the div inside of the `datatable-toolbar-top`:

<img width="1727" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/9da1fd0b-36fe-4041-8c9b-096d0866651a">
<img width="1726" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/83c9682c-8bad-4a0d-88d8-02ff050a1128">

**Comment by Moonbase59** [comment]
Good catch @Vaalyn!

I tried this also in the "naked" embed test page, and indeed the used width is more than reported in the `postMessage`. When disabling the left & right margins, the used width becomes same as reported:

![Iframe widget resizing test - Chromium_001](https://github.com/AzuraCast/AzuraCast/assets/3706922/2030c0dd-ddb2-40f7-b847-bd122877e4b7)

![Iframe widget resizing test - Chromium_002](https://github.com/AzuraCast/AzuraCast/assets/3706922/87737304-4de3-47cb-a3cc-58652b60098f)

There is a little cosmetic problem still: When removing the margins, the upper pagination buttons will "jump" to the right and not line up with the lower pagination buttons anymore:

![Iframe widget resizing test - Chromium_003](https://github.com/AzuraCast/AzuraCast/assets/3706922/65edf805-6042-40c2-8826-55e2ae50d596)

![Iframe widget resizing test - Chromium_004](https://github.com/AzuraCast/AzuraCast/assets/3706922/9483574b-18fd-4405-b0a7-040bcaa1dfa9)

Do you think I need to test all the other possible embeds, too? Or is this enough for now to maybe get it fixed?
