### ISSUE TITLE
502 BAD GATEWAY Nginx

### ISSUE THREAD

**Issue by iChurchR** [AzuraCast/AzuraCast#6839]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

I have been trying to access my Azurcast Public IP for some days now and it keep coming back with the 502 Error. I tried updating to see if that would help clear the issue, but this is to no avail.

However, in the screenshot is an error message I have no  idea  about. Can someone help in interpreting this?

Thanks

![AzuraCast Error Update](https://github.com/AzuraCast/AzuraCast/assets/155507193/965e0a15-3002-465e-af1a-7996742e302d)

**Comment by hitzgh** [comment]
i am having the same issue here, right after installaltion and i open the ip in web browser i get this error

**Comment by hitzgh** [comment]
![Screenshot 2024-01-04 at 16-34-35 502 Bad Gateway](https://github.com/AzuraCast/AzuraCast/assets/45140361/bf930b5e-0905-45de-8093-1b4c354939dc)

**Comment by BusterNeece** [comment]
@hitzgh If you pull up the logs from the server side, via `docker-compose logs -f web`, what errors do you see?

**Comment by iChurchR** [comment]
@BusterNeece what do you think is going on based on the screenshot I sent?

Thanks for tthe great job you are doing

**Comment by geckonet1** [comment]
I updated my installation to the new stable version today.  Now I have this error message.

**Comment by hitzgh** [comment]
@BusterNeece here is the output
root@cast2:/home/info# docker-compose logs -f web
Command 'docker-compose' not found, but can be installed with:
snap install docker          # version 20.10.24, or
apt  install docker-compose  # version 1.29.2-1
See 'snap info docker' for additional versions.

if am correct dockers seems not to be installed right?

**Comment by BusterNeece** [comment]
@hitzgh You may need to run `docker compose logs -f web` (the same command but with `docker compose` instead of `docker-compose`).

**Comment by hitzgh** [comment]
@BusterNeece here is the output
root@cast2:/home/info# docker compose logs -f web
no configuration file provided: not found
root@cast2:/home/info#

**Comment by BusterNeece** [comment]
@hitzgh Sorry, you should also run this command from the folder where AzuraCast is installed. If you followed our instructions, that'll be `/var/azuracast`, so:

```bash
cd /var/azuracast
docker compose logs -f web
```

**Comment by iChurchR** [comment]
@BusterNeece what do you think could possibly be the issue based no the screeshot I shared above?

Thanks

**Comment by BusterNeece** [comment]
@iChurchR Tons of things. No need to keep pinging me to follow up. A "connection refused" error is really vague...could be a misconfigured database, could be a temporary issue that's fixed by updating or restarting, could be something else...I'd need to see more logs to know for sure.
