### ISSUE TITLE
Azuracast is reading the hell out of my disk

### ISSUE THREAD

**Issue by TexMex100** [AzuraCast/AzuraCast#6840]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### What happened?

If i start the radio, after a few days its reading 100% off my disk for no reason, and while its doing that i cant access the website. any sollucions?

**Comment by BusterNeece** [comment]
@TexMex100 This may be caused by an issue we had with Liquidsoap recordings, and updating to the latest Stable release (0.19.4) should resolve that issue.

**Comment by TexMex100** [comment]
so i need to rerun the installation to with the update thingy after the command to update it to the latest liquidsoap?

**Comment by BusterNeece** [comment]
@TexMex100 If you update AzuraCast itself per our instructions on our web site (https://www.azuracast.com/docs/getting-started/updates/), then Liquidsoap will automatically be updated as well.

**Comment by TexMex100** [comment]
Alright, thank you very much!
