### ISSUE TITLE
The m3u file when downloaded is empty

### ISSUE THREAD

**Issue by VictorSdelsol** [AzuraCast/AzuraCast#6842]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.3 Stable • Docker • PHP 8.2

### What happened?

When I click on download M3U under local streams it downloads the file but it is empty.

I am using butt para for streaming and icecast on the server.

**Comment by BusterNeece** [comment]
@VictorSdelsol I can't currently reproduce this issue. What types of streams do you have?

**Comment by VictorSdelsol** [comment]
Hi Buster,

I have a transmission through BUTT and Icecast.

The mount point is in mp3 96kbps. Autodj is activated.
