### ISSUE TITLE
Public Pages and API URLs Broken After Update to   0.19.4

### ISSUE THREAD

**Issue by Seehed** [AzuraCast/AzuraCast#6845]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.4

### What happened?

After updating to AzuraCast version 0.19.4, the following issues were observed:

Public Pages Display Issue:

The public pages for all stations are broken. Despite the internal dashboard showing that the stations are online and playable, the public pages indicate that the stations are offline.
API URLs Not Functioning:

The API URLs used for on-air audio processing, RDS units, and player now playing fetching stopped working after the update. The original URLs, such as http://radio.ttech.fun/api/station/{station_id}/nowplaying, no longer provide the expected data.
Strange API Response:

While inspecting the public player, I noticed a fetch URL with unexpected parameters: https://radio.ttech.fun/api/live/nowplaying/sse?cf_connect=%7B%22subs%22%3A%7B%22station%3Adance247_public%22%3A%7B%7D%2C%22global%3Atime%22%3A%7B%7D%7D%7D. The API response contains the following information: "data: {"disconnect":{"code":3502,"reason":"stale"}}.
These issues were not present before the update, and they are affecting the functionality of the public pages and API endpoints. The internal dashboard still indicates that the stations are online and playable.

https://cdn.discordapp.com/attachments/647143522054701084/1192713911703707688/image.png?ex=65aa1464&is=65979f64&hm=f86add9f4f3989757af8f2a6c40ad914b81a197478f6b2f8b53b3e18e75161f0&

https://cdn.discordapp.com/attachments/647143522054701084/1192713911934402621/image.png?ex=65aa1464&is=65979f64&hm=e967e830ff449da1926692377b68ff9a94846e9974e63e1c7f7f6e32dddda9a4&

https://cdn.discordapp.com/attachments/647143522054701084/1192713912181870613/image.png?ex=65aa1464&is=65979f64&hm=759c0e5434925a3ad95ce91f384b7cfc564e0f5a1274f7a4bf9c4e1c85503169&

**Comment by haz3mn-tim3y** [comment]
Same issues as KOLX Also experiencing bugs on AzuraCast
![Uploading 91266e1d-36e9-42f9-afaa-c77c89bd454a.jpg…]()
![Uploading 5b9ddaf0-6364-421e-bb94-a45bd5fdc2d7.jpg…]()

**Comment by BusterNeece** [comment]
@Seehed I fixed a bug with the `/api/station/(id)/nowplaying` route endpoint.

As for the public stations, it seems things have worked themselves out on your station and things are working as expected. If you run into this issue again, I'd recommend toggling the "High-Performance Now Playing Updates" setting (either enabling it if it's off, or disabling it if it's on).
