### ISSUE TITLE
Prevent other users other than the "Super Administrator" to have access to the Advanced Features

### ISSUE THREAD

**Issue by renatopinto89** [AzuraCast/AzuraCast#6848]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.3 Stable

### What happened?

This is not really a bug, but something that could be looked at,
More times than I would like to admit, when a DJ starts messing around with the Stations Profile options, it always breaks something, either by enabling something on the AutoDJ tab, change ports or max users, etc

Is there any way to let those "limited users" have access to the Profiles Name, Description, Requests, Branding, etc, but not super sensitive stuff like the Advanced features?

The "Manage Station Profile" permission is a bit too permissive.

Thank you so much for this amazing project.

**Comment by BusterNeece** [comment]
@renatopinto89 You should probably submit this over at https://features.azuracast.com/ rather than having it be a GitHub issue, which is specifically for bugs encountered in the current app rather than feature requests for it.
