### ISSUE TITLE
Urgent: How to reset station IDs!

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#685]
Hello. I had created some stations that I deleted, but the id is still saved (station: 2 - station: 3 and c ...) How do I delete these ids to create stations with the ids of the deleted stations? Help!
![image](https://user-images.githubusercontent.com/22561729/43197577-de8380ec-900b-11e8-998d-431db63c7b8d.png)
![image](https://user-images.githubusercontent.com/22561729/43197599-f043a4e2-900b-11e8-85c2-345506f859ce.png)

**Comment by MyTheValentinus** [comment]
Hello,
You need to update auto increment index in your database.
The best practice is to keep maria db manage this index.
To avoid any issue in the future I recommend you to reinstall your instance (if you do not have in production station)
See https://mariadb.com/kb/en/library/auto_increment/ for more informations
Thanks

**Comment by SlvrEagle23** [comment]
@Ilario42 Just to confirm from my end, the answer from @MyTheValentinus is indeed accurate; this has to do with the auto-incremented ID number of the station in the database. You can manually update a station's ID number by directly accessing the database. You can see issue #266 for details on how to connect to MariaDB.
