### ISSUE TITLE
Issue with Auto DJ Not Taking Over After Live Hosts Disconnect

### ISSUE THREAD

**Issue by JesperSchwaner** [AzuraCast/AzuraCast#6850]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

v0.19.2

### What happened?

We are currently experiencing an issue with our radio server (AzuraCast) where, upon disconnection of our live hosts, the Auto DJ does not initiate and take over the broadcast as expected. We have noticed that there are no error messages in the server logs related to this issue.

Could you please provide guidance on how to resolve this issue? Any assistance or suggestions you can offer would be greatly appreciated.

Thank you for your prompt attention to this matter

### Relevant log output

```shell
[2023-12-15  07:40:19] WARN connection/_handle_get_request server client limit reached (2500/2503) for 128.140.13.132
```

**Comment by netbladenl** [comment]
You should update to 0.19.4 issue has been resolved within that release.
