### ISSUE TITLE
POST /station/{station_id}/webhooks doesn't work as expected.

### ISSUE THREAD

**Issue by ARandomBoiIsMe** [AzuraCast/AzuraCast#6851]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #aec2359

### What happened?

Using this JSON body: 

```
{
    "name": "from library", 
    "type": "email", 
    "triggers": ["song_changed"], 
    "config": {
        "to": "gXXXXX@gmail.com",
        "subject": "this is a subject"
        "message": "message message"
    }
}
```
I have tried to create a webhook, but I am met with multiple errors with a common message of a wrong data type.
I tried to recreate this error in Postman, but the request always succeeded and the webhook was successfully created.

However, when trying to perform this request in Python via the requests library with the same JSON body, I am met with this error:
`App\Entity\StationWebhook::setConfig(): Argument #1 ($config) must be of type ?array, string given, called in /var/azuracast/www/src/Normalizer/DoctrineEntityNormalizer.php on line 372`

Upon either removing the 'config' attribute or changing it to a list data type, I am then met with this error:
`App\Entity\StationWebhook::setTriggers(): Argument #1 ($triggers) must be of type ?array, string given, called in /var/azuracast/www/src/Normalizer/DoctrineEntityNormalizer.php`

The request is only successful when both the 'triggers' and 'config' attributes are empty lists.

Any help on this would be appreciated.

**Comment by Moonbase59** [comment]
Missing comma after `"subject": "this is a subject"`.

**Comment by ARandomBoiIsMe** [comment]
> Missing comma after `"subject": "this is a subject"`. (Verified on Rolling Release #[940666b](https://github.com/AzuraCast/AzuraCast/commit/940666bf327d5bc49269482702c8a6e3dc780fa3) (2024-01-05 11:46).)

Oops. Just corrected that. The issue still persists.

`App\Entity\StationWebhook::setConfig(): Argument #1 ($config) must be of type ?array, string given, called in /var/azuracast/www/src/Normalizer/DoctrineEntityNormalizer.php on line 372`

**Comment by ARandomBoiIsMe** [comment]
> Missing comma after `"subject": "this is a subject"`. (Verified on Rolling Release #[940666b](https://github.com/AzuraCast/AzuraCast/commit/940666bf327d5bc49269482702c8a6e3dc780fa3) (2024-01-05 11:46).)

Oops. Just corrected that. The issue still persists.

`App\Entity\StationWebhook::setConfig(): Argument #1 ($config) must be of type ?array, string given, called in /var/azuracast/www/src/Normalizer/DoctrineEntityNormalizer.php on line 372`

Image of my code, for reference:
![Screenshot (1345)](https://github.com/AzuraCast/AzuraCast/assets/105561324/b5c02e53-fbe6-46ae-b3cf-062d99b0b243)

**Comment by Moonbase59** [comment]
Suggest trying with `curl` first, then check your Python code.

Works fine here using `curl` (domain changed):
```
matthias@e6510:~$ curl -X 'POST' \
  'https://radio.niteradio.net/api/station/1/webhooks' \
  -H 'accept: application/json' \
  -H 'X-API-Key: afd3fd78e7610bdd:05859e2f48da92d90074714e014cafc6' \
  -H 'Content-Type: application/json' \
  -d '{
    "name": "from library", 
    "type": "email", 
    "triggers": ["song_changed"], 
    "config": {
        "to": "gXXXXX@gmail.com",
        "subject": "this is a subject",
        "message": "message message"
    }
}'
{"name":"from library","type":"email","is_enabled":true,"triggers":["song_changed"],"config":{"to":"gXXXXX@gmail.com","subject":"this is a subject","message":"message message"},"id":10,"links":{"self":"https://radio.niteradio.net/api/station/1/webhook/10","toggle":"https://radio.niteradio.net/api/station/1/webhook/10/toggle","test":"https://radio.niteradio.net/api/station/1/webhook/10/test"}}
matthias@e6510:~$ 
```

_Note: No need to try attacks, the API key is a fake!_

![Auswahl_326](https://github.com/AzuraCast/AzuraCast/assets/3706922/3824ab97-320c-4a0f-af8b-e3e3921a61a7)

**Comment by ARandomBoiIsMe** [comment]
That's the thing.

I performed this exact request in Postman and it worked.
I just tried it out in curl, and it worked too.

I've gone back to my code and moved through every step with the debugger:
- The function I passed the values into in my previous screenshot generates a valid JSON object, with the outer curly braces and everything:
    ![Screenshot (1347)](https://github.com/AzuraCast/AzuraCast/assets/105561324/0f85697d-545e-4029-9bb0-ea252904eab6)
    
    Printing out the fully-generated body with those values yields this object:
    `{'name': 'from library', 'type': 'email', 'triggers': ['song_changed'], 'config': {'to': 'gXXXXX@gmail.com', 'subject': 
    'This is a subject', 'message': 'Message'}}` 

- It sends a post request
- The request sends back a 500 Response, with one of the two previously mentioned errors

It seems to work everywhere else except my Python code, which sounds crazy. 

I made an isolated script to test it out - it failed too. I'll drop it here so you can test it out and confirm that I'm not losing my mind:
```
import requests

body = {
    "name": "from library",
    "type": "email",
    "triggers": ["song_changed"],
    "config": {
        "to": "gXXXXXX@gmail.com",
        "subject": "This is a subject",
        "message": "This is a message"
    }
}

x_api_key = "XXXX" # Your API Key
radio_url = "XXXX" # Your radio URL
headers = {"accept": "application/json", "X-API-Key": x_api_key}

res = requests.post(url=f"{radio_url}/api/station/1/webhooks", data=body, headers=headers)
print(res.text)
```

**Comment by Moonbase59** [comment]
In your `requests.post`, how about `json=body` instead of `data=body`? ;-)

This is probably the easiest way to achieve what you want ((added in requests version 2.4.2).

Doing a `print(json.dumps(res.json(), indent=2))` to see the API response at the end I get:

```json
{
  "name": "from library",
  "type": "email",
  "is_enabled": true,
  "triggers": [
    "song_changed"
  ],
  "config": {
    "to": "gXXXXXX@gmail.com",
    "subject": "This is a subject",
    "message": "This is a message"
  },
  "id": 11,
  "links": {
    "self": "https://example.com/api/station/1/webhook/11",
    "toggle": "https://example.com/api/station/1/webhook/11/toggle",
    "test": "https://example.com/api/station/1/webhook/11/test"
  }
}
```

So all good.

**Comment by BusterNeece** [comment]
Yep, I suspect if you're not using `json=data` on Requests, it's not sending `Content-Type: application/json` in the headers, which means we're not parsing it as JSON at all.

**Comment by Moonbase59** [comment]
Yep.

And if you’re _really_ stuck with a pre-2.4.2 `requests` module, you could as well
- add `Content-Type` to the headers
- `import json`
- use `data=json.dumps(body)` instead of `json=body`.

But why make life too complicated? ;-)

**Comment by ARandomBoiIsMe** [comment]
> In your `requests.post`, how about `json=body` instead of `data=body`? ;-)
> 
> This is probably the easiest way to achieve what you want (added in requests version 2.4.2). (The Python object `body` needs to be serialized as a JSON string to correctly work with the API.)
> 
> Doing a `print(json.dumps(res.json(), indent=2))` to see the API response at the end I get:
> 
> ```json
> {
>   "name": "from library",
>   "type": "email",
>   "is_enabled": true,
>   "triggers": [
>     "song_changed"
>   ],
>   "config": {
>     "to": "gXXXXXX@gmail.com",
>     "subject": "This is a subject",
>     "message": "This is a message"
>   },
>   "id": 11,
>   "links": {
>     "self": "https://example.com/api/station/1/webhook/11",
>     "toggle": "https://example.com/api/station/1/webhook/11/toggle",
>     "test": "https://example.com/api/station/1/webhook/11/test"
>   }
> }
> ```
> 
> So all good.

This worked!
You have no idea how grateful I am!

I guess I should have done more research about the library I was using instead of jumping to conclusions so quickly.
Thanks dude.

Issue resolved.
