### ISSUE TITLE
Crossfade default duration 0 disables crossfading entirely 

### ISSUE THREAD

**Issue by RM-FM** [AzuraCast/AzuraCast#6852]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #8bda7bb (2024-01-06 0:30)

### What happened?

Crossfade default duration 0 disables crossfading: It removes `cross` part from the Liquidsoap script entirely, even if the crossfading option is still enabled.

**Comment by BusterNeece** [comment]
@RM-FM The crossfade default duration should be 2 seconds, not 0, if you're creating a new station at this point. We had a period in the past where the defaults weren't being set correctly, so you may be seeing that, but it should be set as expected in newer versions.

**Comment by RM-FM** [comment]
@BusterNeece Sorry, I was not very clear on that… With default value I meant just whatever has been set for „Crossfade Duration“ in the Station Profile -> AutoDJ.

I set it to 0 on purpose, expecting that there will be no crossfade if nothinh has been set for a particular track - but still for all others. I think removing the whole crossfade part from the Liquidsoap script just because the default has been set to 0 is not a smart behavior. If I would like to disable crossfading entirely, then I would change the Crossfade Method to „Disable Crossfading“ but not „Normal Mode“.

**Comment by Moonbase59** [comment]
I actually _rely_ on that: Setting crossfade to "Normal mode" and duration to "0" removes the predefined code in the LS config so I can place my own. For some reason, "Disable Crossfade" never worked.

**Comment by RM-FM** [comment]
> I actually _rely_ on that: Setting crossfade to "Normal mode" and duration to "0" removes the predefined code in the LS config so I can place my own. For some reason, "Disable Crossfade" never worked.

I took note of that as well in the past. But with recent version (at least with rolling release), it seems to be enough to set the "disable crossfade" option.
