### ISSUE TITLE
Passkeys feature not working

### ISSUE THREAD

**Issue by quizmastergary** [AzuraCast/AzuraCast#6853]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.4

### What happened?

I tried to set up a passkey for my installation but can't and get the following error when I try to Add A New Passkey in the Security menu:
An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.user_passkeys' doesn't exist

**Comment by BusterNeece** [comment]
@quizmastergary This suggests your database migrations didn't run correctly...try manually updating your installation again and let me know if you see any error messages in your logs.
