### ISSUE TITLE
Schedule When DJS Can Connect

### ISSUE THREAD

**Issue by daredevil22180** [AzuraCast/AzuraCast#686]
Too often in stations I've been part of, I have occasions where djs forget to drop their encoder when they are finished, ir in some cases, a dj fell asleep for several hours, and dead air went over the stream. So I would love to see a feature where dj accounts could have a schedule assigned for when they can and can't log in. This would mean that once a dj was finished, they would be kicked and auto DJ would take over, thus allowing the automation to kick in or the next dj to connect.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38913/schedule-when-djs-can-connect
