### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by onlinegill** [AzuraCast/AzuraCast#6864]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

I've been struggling to install Azuracast on my VPS with various operating systems, but each attempt results in a 502 Bad Gateway error. I've attached the log file for your review. Any insights or guidance on resolving this issue would be greatly appreciated.   [log.txt](https://github.com/AzuraCast/AzuraCast/files/13930319/log.txt)

**Comment by DocTator2281** [comment]
Bad Gateway errors are normal when first loading Azuracast. Have you tried waiting a few minutes and then refreshing the page to see if it resolves?

**Comment by onlinegill** [comment]
> Bad Gateway errors are normal when first loading Azuracast. Have you tried waiting a few minutes and then refreshing the page to see if it resolves?

Its been over 18 hours since i installed and still shows same error, tried ubuntu, centos, alma/rocky Linux on OVH vps ( 2Gb ram)
