### ISSUE TITLE
Only listener statistics for a user group.

### ISSUE THREAD

**Issue by djmuratb** [AzuraCast/AzuraCast#687]
First of all thank you very much for this excellent project.

I want to show only listener statistics for a user group that I will set (I do not want them to see the playing songs and profile page).
if you show me a way to do this I will be pleased.

Thanks!..

**Comment by SlvrEagle23** [comment]
@djmuratb AzuraCast's permissions structure requires that the profile (and the currently playing song) be visible, but not editable. If you assign a user with only the "View station administration" and "View reports" permissions, this will be the only part of the system they are able to see.
