### ISSUE TITLE
Version incompatible with raspberry pi 5

### ISSUE THREAD

**Issue by Nariod68** [AzuraCast/AzuraCast#6875]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/master/docker.sh > docker.sh

### What happened?

![image_2024-01-17_153320237](https://github.com/AzuraCast/AzuraCast/assets/79050575/fc49ba1e-6083-4ac0-8e52-f2ce6f104f35)

### Relevant log output

Version incompatible with raspberry pi 5

**Comment by BusterNeece** [comment]
@Nariod68 I'd recommend using a host OS that is arm64, not ARMv8. Both are supported on the Raspberry Pi 5 and ARM64 is what we build against in our builds to support the most possible devices.
