### ISSUE TITLE
Request History now upside down?

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6876]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #a0562e9 (2024-01-17 19:13)

### What happened?

I seem to remember the Request History used to show requests in reverse (i.e., newest at top). It now shows requests chronologically, so one has to scroll to the end to find the latest requests. And it’s not sortable, so the user can’t reverse the list.

Intentional? (I’d prefer "latest at top", i.e. reverse order.)

**Comment by Sella-3DX** [comment]
I can confirm this and I agree, the history should be reversed like it's with the general song history. Would be way more friendly - maybe even add pagination to it.

**Comment by BusterNeece** [comment]
@Moonbase59 I believe this was actually a bug in our query builder that has since been fixed, as I'm now seeing the intended original sort order where the newest requests are listed first and then go backwards from there.
