### ISSUE TITLE
Podcast RSS route not found

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6879]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #d7b8c59 (2024-01-20 23:19)

### What happened?

Clicking on the Podcast `RSS` button produces an error:

```
Error
Named route does not exist for name: public:podcast:episodes

vendor/slim/slim/Slim/Routing/RouteCollector.php : L209
```

![Podcasts - Nite Radio – Mozilla Firefox_001](https://github.com/AzuraCast/AzuraCast/assets/3706922/3db09c13-9ced-4f35-83d2-059e139fc13e)

**Comment by PeWe79** [comment]
Confirm here, same issue on it.

**Comment by Moonbase59** [comment]
Thanks. Confirm working in Rolling Release #[87e7802](https://github.com/AzuraCast/AzuraCast/commit/87e7802d01b3dd366b8ef4b668e3dcd54e0ba6bf) (2024-01-21 3:08).
