### ISSUE TITLE
mono files not playing

### ISSUE THREAD

**Issue by anarchiso** [AzuraCast/AzuraCast#688]
hello, i just did a traditional install on a new computer running ubuntu 18.04 and I am still having this issue #671 where mono files will not play  
the liquidsoap.log file keeps repeating these lines

2018/07/30 00:05:39 [lang:3] AzuraCast Raw Response: annotate:title="Democracy Now! Thursday, July 26, 2018",artist="Democracy Now!":/var/azuracast/stations/free_radio_test/media/dn2018-0726.mp3
2018/07/30 00:05:39 [decoder.mad:3] File "/var/azuracast/stations/free_radio_test/media/dn2018-0726.mp3" has an incompatible number of channels.
2018/07/30 00:05:39 [decoder:3] Unable to decode "/var/azuracast/stations/free_radio_test/media/dn2018-0726.mp3" as {audio=2;video=0;midi=0}!

if this helps, the file is MPEG Audio layer 1/2(mpga), Mono, 44100 Hz, 32 Bits per sample, 64kb/s

**Comment by SlvrEagle23** [comment]
@anarchiso I don't think the issue here is that the file is mono, it's that it's encoded as mpga but has the mpeg layer 3 audio file extension. I'm not sure that Liquidsoap supports that file format at all.

**Comment by anarchiso** [comment]
@SlvrEagle23 i used VLC to check the codec info of other .mp3 files that were working in auzuracast and it is saying they are also mpga, so i might have been wrong about the file being mpga. i just mixed down a stereo song that was working in azuracast down to mono in audacity and it still isn't playing. it is layer 3.

$ file Kalimba-mono.mp3
Kalimba-mono.mp3: Audio file with ID3 version 2.4.0, extended header, contains:MPEG ADTS, layer III, v1, 128 kbps, 44.1 kHz, Monaural

the log is still the same 
2018/07/30 13:06:42 [decoder.mad:3] File "/var/azuracast/stations/free_radio_test/media/kalimba-mono.mp3" has an incompatible number of channels.
2018/07/30 13:06:42 [decoder:3] Unable to decode "/var/azuracast/stations/free_radio_test/media/kalimba-mono.mp3" as {audio=2;video=0;midi=0}!

**Comment by Lukahhh** [comment]
Hey @anarchiso! Just further to the above, I have solved this with a bit of Liquidsoap magic using the Advanced configuration.

In this example, **playlist_default** contains stereo MP3 tracks, and **playlist_messages** contains mono MP3 tracks (jingles), but you could simply add the 'audio_to_stereo' wrapper to wherever you need.

```
playlist_messages = audio_to_stereo(playlist(reload_mode="watch","/var/azuracast/stations/STATIONNAME/media/messages",mode="normal"))
playlist_default = playlist(reload_mode="watch","/var/azuracast/stations/STATIONNAME/media/music",mode="normal")
radio = rotate(weights=[1,1], [mksafe(playlist_default), playlist_messages])
radio = normalize(radio)

```

Using the audio_to_stereo wrapper around the messages playlist, I was able to force liquidsoap to accept these files. :) 

I hope that makes sense - let me know if not.

**Comment by SlvrEagle23** [comment]
@anarchiso I've moved the `audio_to_stereo` calls to wrap around each individual audio source, as this appears to be what Liquidsoap requires for this to work properly. Try it out and let me know if it helps.
