### ISSUE TITLE
RR 87e7802: Embedded player sometimes stops, doesn’t allow stream selection on Firefox

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6882]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #87e7802 (2024-01-21 3:08)

### What happened?

I was just re-testing all possible embeds for resizing and found that:

- On Chromium/Chrome, selecting another stream expands the iframe down to show the stream selection (good) but doesn’t make it smaller again after the selection is done. Don’t know if this is worth fixing, though.
- On Chromium/Chrome, after a while the audio stops, although the button suggests it’s still playing. If you wait long enough (minutes), sound will come back but be interrupted again. This works okay on Firefox. I was playing a 24:15 mins, 132 MB FLAC track at the time (Klaus Schulze - Friedrich Nietzsche). Browser console shows one of Chromium’s dreaded `ERR_NETWORK_CHANGED` messages:

  ```
  15:40:42.856 radio.niteradio.net/api/live/nowplaying/sse?cf_connect=%7B%22subs%22%3A%7B%22station%3Aniteradio%22%3A%7B%7D%2C%22global%3Atime%22%3A%7B%7D%7D%7D:1 
         GET https://radio.niteradio.net/api/live/nowplaying/sse?cf_connect=%7B%22subs%22%3A%7B%22station%3Aniteradio%22%3A%7B%7D%2C%22global%3Atime%22%3A%7B%7D%7D%7D net::ERR_NETWORK_CHANGED 200 (OK)
  15:40:42.857 radio.niteradio.net/listen/niteradio/radio.mp3:1 
         GET https://radio.niteradio.net/listen/niteradio/radio.mp3 net::ERR_NETWORK_CHANGED 200 (OK)
  ```
  No reason I could find for this, except _maybe_ an IPv6 DHCP lease ran out or the IPv6 prefix changed (they sometimes do).
- On Firefox, the stream selection doesn’t work at all. The button changes its shade of gray but no selection box appears. **EDIT:** Just found out that it _does_ work if you scroll down in the iframe. Apparently Firefox doesn’t show the enlarged iframe as Chromium does. Or no post message in this case?

See https://grav1.niteradio.net/wh/iframe-resizer.html for a live example.

### Screenshot (Chromium 120.0.6099.216)

![Iframe widget resizing test - Chromium_005](https://github.com/AzuraCast/AzuraCast/assets/3706922/919d1ef7-6ae6-42ad-af13-ca4c3e300b91)

**Comment by Moonbase59** [comment]
More diagnosing shows that

- the `ERR_NETWORK_CHANGED` Chromium error might have resulted from the underlying network manager on my laptop Linux changing between WiFi & LAN connection—both were enabled as I tested this. Browsers are definitely getting too "clever"—other apps usually just don’t care (like Firefox). So this can be disregarded I think.
- the iframe isn’t resized vertically on Firefox, for whatever reason.  Still, if you scroll when the dropdown opens, you can access the entries, say with the arrow keys on the keyboard. Since this works fine on Chromium, there must be some subtle difference here.
- Opera 106.0.4998.52 (based on Chromium 120.0.6099.234) expands the iframe for the button dropdown, but after the initial playout seems unable to play _any_ stream when you select another one. It also displays an error:
  ![Iframe widget resizing test - Opera_001](https://github.com/AzuraCast/AzuraCast/assets/3706922/0f21809d-38ab-4943-9e18-33245b1987b8)
  And why does `usePlayerVolume…` access `https://goo.gl/LdLk22`?

**Comment by BusterNeece** [comment]
@Moonbase59 It's not accessing it, it's linking it to you, to explain that audio playback is async as of newer Chromes. We should probably update our player code accordingly honestly.

**Comment by Moonbase59** [comment]
Ah, okay, thanks. I still wonder about the iframe resizing difference between Chromium and Firefox.

**Comment by BusterNeece** [comment]
With regards to the resizing thing...I'm not sure that's *possible* to fix. The only way we get resizing information is through the listener we have registered already, as it's about the only way to monitor for size changes in a performant way that doesn't involve just constantly hammering the page looking for size changes. If that has bugs in it, then we'll just have to live with those bugs.
