### ISSUE TITLE
White page after updating

### ISSUE THREAD

**Issue by pilovali** [AzuraCast/AzuraCast#6892]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.4

### What happened?

After updating from 0.19.3 to 0.19.4, I'm getting a fully blank page on the login screen. API still does work.
Reboot didn't help.
I tried restoring VM backup and trying to update again. This time it worked, however after a day, the issue re-appeared.
I'm also having issues with webhooks.

### Relevant log output

```shell
[2024-01-25T20:07:52.603094+00:00] AzuraCast.INFO: Dispatching test web hook "final"... [] []
[2024-01-25T20:07:52.605037+00:00] AzuraCast.DEBUG: Writing local nowplaying text file... [] []
[2024-01-25T20:07:52.605480+00:00] AzuraCast.DEBUG: Writing static nowplaying text file... [] []
[2024-01-25T20:07:52.606606+00:00] AzuraCast.DEBUG: HTTP client POST call to http://localhost:6025/api produced response 200 [] []
[2024-01-25T20:07:52.606838+00:00] AzuraCast.ERROR: /var/azuracast/www/src/Webhook/Connector/AbstractConnector.php L99: App\Webhook\Connector\AbstractConnector::App\Webhook\Connector{closure}(): Return value must be of type string, int returned {"exception":"[object] (TypeError(code: 0): App\Webhook\Connector\AbstractConnector::App\Webhook\Connector\{closure}(): Return value must be of type string, int returned at /var/azuracast/www/src/Webhook/Connector/AbstractConnector.php:99)"} []
```

**Comment by BusterNeece** [comment]
@pilovali The logs you supplied don't really give us enough information to know what's going on here. A white page can indicate a lot of things unfortunately, but it wouldn't be possible for us to narrow down that list without more extensive logs. In particular, it would be useful for us to see the logs during an update and/or right after running the update process.

I'd also be curious how you're doing the update; if you're doing it via the web panel (i.e. in-browser updates), I'd recommend trying the SSH command-line update method to see if that resolves things.

**Comment by Lokke** [comment]
i've exactly the same issues

"white page" when not logged in
![image](https://github.com/AzuraCast/AzuraCast/assets/6406275/ba995fb6-33ec-4caa-b439-0bb16035c622)
workaround is to navigate to 
azuracast.domain.tld/login

discord webhook breaks, if the form is filled with values related to now_playing.
"Return value must be of type string, int returned"

Not working:
![image](https://github.com/AzuraCast/AzuraCast/assets/6406275/882e208d-4d97-4b8e-a99d-60902757eb5b)

Working:
![image](https://github.com/AzuraCast/AzuraCast/assets/6406275/cc5dabd9-affc-416a-aca7-5dbf2e8b8bdb)

suspected related commit:
https://github.com/AzuraCast/AzuraCast/commit/bbf8d56b460d5cca9318bdefc463a44631024eef

**Comment by pilovali** [comment]
> @pilovali The logs you supplied don't really give us enough information to know what's going on here. A white page can indicate a lot of things unfortunately, but it wouldn't be possible for us to narrow down that list without more extensive logs. In particular, it would be useful for us to see the logs during an update and/or right after running the update process.
> 
> I'd also be curious how you're doing the update; if you're doing it via the web panel (i.e. in-browser updates), I'd recommend trying the SSH command-line update method to see if that resolves things.

I'm doing updates via the command line, I always update via command line. Which logs do you want to see?

**Comment by Lokke** [comment]
can't reproduce "white page" issue anymore in 0.19.5.
i'll suggest to trim this ticket and rename it to describe the non functionality of webhooks belonging to discord, if "page isn't redirecting properly" doesn't occur for you since 0.19.5 as well.

**Comment by Lokke** [comment]
never mind - discord webhooks are working for me as well fine again.
