### ISSUE TITLE
Advanced Playlists Not Working, Even Using Example from Docs

### ISSUE THREAD

**Issue by wppronto** [AzuraCast/AzuraCast#6899]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.4 Stable

### What happened?

First, thanks for all the work on AzuraCast! I want to leverage the power of rotations using Advanced Playlists. I've tried the "side-by-side" example verbatim, and it never works. I don't know if it's a bug or if I missed something.

I create the playlists and enter the code as in the example, but nothing ever plays from the Advanced Playlists in the code added to Liquidsoap. I don't see any error messages either. I have searched through similar reports that I could find, and I couldn't find a resolution there.

If I'm missing something simple, I totally apologize. Thank you.

**Comment by gAlleb** [comment]
Hi! So
1. You create a Playlist with tracks.
2. In "Basic Info" settings of Playlist you choose "Advanced"
3. Go to "Broadcasting" - "Edit Liquidsoap Configuration"
4. You must see your Playlist there (where all other playlists located). Something like:
```
playlist_classic_rock = playlist(id="playlist_classic_rock",mime_type="audio/x-mpegurl",mode="randomize",reload_mode="watch","/var/azuracast/stations/radio/playlists/playlist_classic_rock.m3u")
playlist_classic_rock(ignore)
```
5. Navigate lower (to the place where you can edit config - below `# Apply amplification metadata (if supplied)
radio = amplify(override="liq_amplify", 1., radio)`
6. Paste your playlist again (Loose the "ignore" line):
`playlist_classic_rock = playlist(id="playlist_classic_rock",mime_type="audio/x-mpegurl",mode="randomize",reload_mode="watch","/var/azuracast/stations/radio/playlists/playlist_classic_rock.m3u")`
7. Then add code for what you  wanna do with it. E.g.:
`radio = rotate(weights=[1,5], [playlist_classic_rocks, radio])` or anything else like "switch" `radio = switch([({6h-9h}, playlist_classic_rock), ({true}, radio)]) ` 
8. As a result you will have the next code in your config:
```
playlist_classic_rock = playlist(id="playlist_classic_rock",mime_type="audio/x-mpegurl",mode="randomize",reload_mode="watch","/var/azuracast/stations/radio/playlists/playlist_classic_rock.m3u")
radio = rotate(weights=[1,5], [playlist_classic_rocks, radio])
```
9. Restart broadcasting
10. Your playlist will play 1 track and then all your other (not advanced) playlists will play 5 tracks
11.  Keep in mind that you will not see "next" of your advanced playlist nor any of the functions (you choose in "edit playlist")  that you might want to see in it.

**Comment by wppronto** [comment]
Thank you so, so much!

I think there may have been two causes originally:

- As you showed, the playlist details needed to be copied into the configuration section. I don't think I had done that in the example.
- I was probably putting the custom code in the wrong place. I thought the docs said to put it in Edit Profile > Broadcasting > Custom Configuration.

Following your code, I was able to get results!

Thank you!

**Comment by RadioChecheresOk** [comment]
Hello, congratulations for your enormous work and brain, thank you for it, how can I make the "switch" start after finishing the song that is already playing at that time and not interrupt the song in the middle?

Thank you, we love you!
