### ISSUE TITLE
Feature request: Nginx now playing integration

### ISSUE THREAD

**Issue by aftechro** [AzuraCast/AzuraCast#6903]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

v0.19.4 Stable

### What happened?

After each azuracast upgrade, i have to manually add the NGINX configuration, so i can use nowplaying integrated with my website.

this is what i'm using in my nginx:
`   location /public/radiostation/nowplaying.txt {
     alias /var/azuracast/stations/radiostation/config/nowplaying.txt;
     }`  

then if i accessing my url radiostation.com/nowplaying.txt the plugin will read the current song. 

can this be done so the nginx config wont loose the custom config?

Thank you!

**Comment by gAlleb** [comment]
Hi @aftechro! May I ask why do you need this?

Azuracast has very detailed API.
Moreover there are ready-to-use decisions for a website like https://gist.github.com/Moonbase59/d42f411e10aff6dc58694699010307aa

**Comment by aftechro** [comment]
Well, looking at that code, for a non-webdev person, looks way to complicated/complex and to many lines code which would be handy for someone who understands it. 

for me at least, is to just take the existing integrated now playing file, make it accessible by url other than azuracast public page but withing the same domain, and added on my apps to be used. 

especially if my server host 5 radios stations, is much easy for me to get the domain/stationname/nowplaying.txt pointing to exiting /var/azuracast/stations/radiostation/config/nowplaying.txt, for each station and then have the user using that within their apps.

hope this make sense, at lease from an itadmin point of view which does not know to much about web-developing :d

**Comment by gAlleb** [comment]
> this is what i'm using in my nginx:
 location /public/radiostation/nowplaying.txt { alias /var/azuracast/stations/radiostation/config/nowplaying.txt; }

You mean you edit nginx config inside a docker container? Where exactly is your nginx config?

**Comment by aftechro** [comment]
Yep, i`m using nginx inside docker

**docker exec -it azuracast /bin/bash**
**cd /var/azuracast/stations/radiostation/config**
**nano nginx.conf**
add: **location /public/radiostation/nowplaying.txt { alias /var/azuracast/stations/radiostation/config/nowplaying.txt; }**
**exit**
**docker exec -it azuracast nginx -s reload**

**Comment by gAlleb** [comment]
Well the most simple and rude way is copy nginx.conf into your local directory and add that line. Then create docker-compose.override.yml file in /var/azuracast:

```
services:
  web:
    volumes:
      - /home/user/nginx.conf:/var/azuracast/stations/radiostation/config/nginx.conf
```

Every time you start Azuracast in docker - your modified nginx.conf from your local folder will rewrite nginx.conf in docker.

**Comment by aftechro** [comment]
I'm thinking if it can be done by defining a **$station_name** variable in nginx.conf inside docker for location /public/**$station_name**/nowplaying.txt { alias /var/azuracast/stations/**$station_name**/config/nowplaying.txt; } and have it as default nginx configuration going forward probably would work. then by default the url: domain/public/**$station_name**/nowplaying.txt will be accessible

and this could be a second option to the api where you have some apps that just needs and work with nowplaying.txt file

**Comment by Moonbase59** [comment]
It probably all depends on the amount of information you need, but did you ever think of JSON instead of text? It’s easily parseable in almost any language, and you can get at it using the official API easily, like:

```
https://your.domain.tld/api/nowplaying/station_id
```

or, with `curl` (as an example):

```
curl -X 'GET' \
  'https://your.domain.tld/api/nowplaying/station_id' \
  -H 'accept: application/json'
```

**Comment by Moonbase59** [comment]
Yeah, seeing that you only require the `Artist - Title` string, and in a fixed location, seems logical how you did it.

**Comment by Moonbase59** [comment]
Crazy solutions coming up here—love it!

**Comment by gAlleb** [comment]
If you don't have HLS


1. Go to Station Profile - Broadcasting - Edit Liquidsoap Configuration
2. Paste the following code before # Local Broadcasts line:
```
def write_txt(m) =
ignore(file.write(data="#{m[\"artist\"]} - #{m[\"title\"]}", append=false, "/var/azuracast/www/web/static/nowplaying.txt"))
end
radio.on_metadata(write_txt)
```
3. Restart Broadcasting

Now you'll have Artist - Title nowplaying https://radio.com/static/nowplaying.txt

For every station you can Edit Configuration and specify a name of txt. E.G.
"/var/azuracast/www/web/static/nowplaying_station1.txt"
"/var/azuracast/www/web/static/nowplaying_station2.txt"

And they will be accessible by  https://radio.com/static/nowplaying_station1.txt and so on.

**Comment by aftechro** [comment]
see, team work :)) in one way or the other, solutions exits :D

**Comment by BusterNeece** [comment]
Just as a note, none of the text-file generation stuff above is actually necessary; AzuraCast already writes a simple `.txt` file that contains the artist and title and is useful for automation and other tools:
https://www.azuracast.com/docs/developers/now-playing-data/#simple-text-file

For example, here's the one for the demo installation:
https://demo.azuracast.com/api/nowplaying_static/azuratest_radio.txt

**Comment by aftechro** [comment]
Hey BusterNeece,

yes, the txt file exists indeed, but is not visible on public page unless i do the alias config in nginx like:
location /public/radiostation/nowplaying.txt { alias /var/azuracast/stations/radiostation/config/nowplaying.txt; }

but best as i proposed, would be to have it under the widgets as well, so now playing that shows in the admin/public page to be available as widget and placed in on the custom website

**Comment by BusterNeece** [comment]
@aftechro This is incorrect; as I linked above, we write that same file to the public web directory right alongside the other static nowplaying JSON data. This is true as of the latest stable and Rolling releases. No extra work required.

**Comment by aftechro** [comment]
but can we have the widget as well with iframe? :d that would be handy
