### ISSUE TITLE
RR f2c5050: Now replays "last" metadata I’ve sent days ago when switching to live

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6905]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #f2c5050 (2024-01-30 17:51)

### What happened?

I suspect this has something to do with the latest LS metadata replaying logic: After the update to Rolling Release #[f2c5050](https://github.com/AzuraCast/AzuraCast/commit/f2c505070cbbb4437ad884974241947e069dd7f7) (2024-01-30 17:51), when going live: Instead of missing the first metadata from the DJ stream as it was before, it now _replays_ the last metadata I’ve sent to this DJ input—days ago!

Upon the first song change on the live input, all becomes well again.

This really confuses listeners—instead of the intro they expect (or the first song), they get shown something completely different…

Tagging @toots since I think he made the replay metadata changes in LS.

**Comment by toots** [comment]
Ok. I made one blind change on replay metadata when trying to fix https://github.com/savonet/liquidsoap/issues/3610 that I just reverted. I'd recommend to try the next `rolling-release-v2.2.x` when it comes out: https://github.com/savonet/liquidsoap/issues/3610

**Comment by toots** [comment]
Updated rolling release is ready for testing: https://github.com/savonet/liquidsoap/releases/tag/rolling-release-v2.2.x

**Comment by Moonbase59** [comment]
Okay, now it keeps the last song metadata played on the AutoDJ until the first (manual) metadata update or song change.

Much better, but we still have to find out why it misses the initial metadata when a DJ starts streaming. Will have to experiment with ffmpeg, to exclude any chance it being a problem with my streaming software (IDJC).

**Comment by Moonbase59** [comment]
All back, I was too fast—tested directly after updating & restarting. On the second time a DJ connects, it still shows the last metadata streamed on that input…

**Comment by toots** [comment]
So.. we're good or nah?

**Comment by Moonbase59** [comment]
nah, sorry…

**Comment by Moonbase59** [comment]
This seems to be a more general problem with replaying metadata. I’ve set up a testing station (mainly for crossfade testing) that shows metadata is now _off by one track_.

The station is supposed to play one song (shortened to the first & last 15s, so I don’t have to wait long for the next transition), and I’ve currently replaced the crossfade by a `sequence` so the effects aren’t influencing the progress bar count.

Testing something else, don’t wonder: The station is currently on Mumbai time (GMT+05:30).

With this setup, it clearly shows the metadata shown is _off by one_, i.e. "Sine, 400 Hz, -18 dB, 30s" shows while the song is playing, and while the song metadata is shown, the sine plays.

Here’s what I have done to the Liquidsoap config:

```
# Be sure to have ReplayGain applied before crossing.
radio = amplify(1.,override="replaygain_track_gain",radio)

# If a song has <song> <silence> <bonus track>,
# blank.eat() will skip <silence> and play <bonus track>
#radio = blank.eat(radio, max_blank=5.0, threshold=-60.0)
# blank.skip() will skip to next song and NOT play <bonus track>.
# Defaults: max_blank=20.0 (seconds), threshold=-40.0 (dB)
radio = blank.skip(radio, max_blank=5.0, threshold=-80.0)

# Skip base part of song, play only first and last 15 seconds
skipped = ref(false)
def skip_song(s) =
  if source.elapsed(s) > 15. then
    if skipped() == false then
      # seeking can take a while!
      s = source.seek(s, source.remaining(s) - 15.)
      log(label="skip_song", "Skipping #{s}s…")
      skipped := true
    end
  else
    skipped := false
  end
end
radio = source.on_frame(radio, {skip_song(radio)})

def live_aware_crossfade(old, new) =
    if to_live() then
        # If going to the live show, play a simple sequence
        # fade out AutoDJ, do (almost) not fade in streamer
        sequence([fade.out(duration=3.0,old.source),fade.in(duration=0.1,new.source)])
    else
        # Otherwise, use the simple transition
        log("Using custom crossfade")
        #cross.simple(old.source, new.source, fade_in=0.00, fade_out=3.50)
        # use a simple sequence for testing
        sequence([old.source,new.source])
    end
end

radio = cross(minimum=0., duration=4.00, width=2.00, live_aware_crossfade, radio)
```

Station player at: https://radio.niteradio.net/public/niteradio-test

Progress also shown as "Nite Radio Test" (last item) under: https://grav1.niteradio.net/blog/winterzeit-ist-radiozeit
The "clock" at the left just shows the station time (I’m in another timezone).

@toots Can you make something of this?

**Comment by Moonbase59** [comment]
Updated to Rolling Release #[c9b1187](https://github.com/AzuraCast/AzuraCast/commit/c9b118787967d0091bfa89e07de6dfe9e13c5792) (2024-02-02 9:47), same results.

**Comment by Moonbase59** [comment]
Current RR (using LS 2.2.4+git@1245e08aa) seems rather sensitive to _what_ and _how_ one does things. @toots was suspecting a clocking issue, I think.

I changed the crossfading code used, mainly to find out if smart crossfade still has the "volume jumps" when crossing, and now the metadata shown is in most cases _off by one song_, or missing:

```
# Be sure to have ReplayGain applied before crossing.
radio = amplify(1.,override="replaygain_track_gain",radio)

radio = blank.eat(radio, max_blank=.1, threshold=-50.0)

def live_aware_crossfade(old, new) =
    if to_live() then
        # If going to the live show, play a simple sequence
        # fade out AutoDJ, do (almost) not fade in streamer
        sequence([fade.out(duration=3.0,old.source),fade.in(duration=0.1,new.source)])
    else
        # Test smart crossfade again
        log("Using custom crossfade")
        cross.smart(old, new, fade_in=0.1, fade_out=2.5, margin=8.)
    end
end

radio = cross(duration=3.0, width=2.0, live_aware_crossfade, radio)
```

**Comment by Sella-3DX** [comment]
We got issue here that the songs always show they're fully done playing but are still playing (03:51/03:51). This does not change when the next song starts instead the next one is always fully done as well. Before the new Liquidsoap release it was fine.

**Comment by RM-FM** [comment]
@Moonbase59 @BusterNeece We should update to the lastest LS RR as there were few more fixes in the crossfade/fade area.

**Comment by Moonbase59** [comment]
@RM-FM Good point. I rolled forward to Liquidsoap 2.2.4+git@6721bb156 in my Docker. Let’s see.

**Comment by RM-FM** [comment]
> @RM-FM Good point. I rolled forward to Liquidsoap 2.2.4+git@6721bb156 in my Docker. Let’s see.

How do you do that?

**Comment by Moonbase59** [comment]
`ssh` into my radio host, then

```
sudo su
cd /var/azuracast
./docker.sh bash
```

Now, _within the Docker_:
```
sudo su
cd
wget https://github.com/savonet/liquidsoap-release-assets/releases/download/rolling-release-v2.2.x/liquidsoap-6721bb1_2.2.4-ubuntu-jammy-1_amd64.deb
apt install ./liquidsoap-6721bb1_2.2.4-ubuntu-jammy-1_amd64.deb
```

Accept replacing "old" against "new" Liquidsoap, ignore permissions error. After install, check LS version running by
```
liquidsoap --version
```

Then go to the UI of _all_ your stations running on this instance, and do a _Restart Broadcasting_ on each.

Finally, leave all the nested terminals by doing `exit` or `Ctrl+D` until you’re out of your ssh.

---

And yes, after the first few songs playing, this seems to have the metadata issue fixed. I will leave it running for some time so we can test. (In my case, on "Nite Radio" and "Nite Radio Test", if you want to follow.)

**Note:** The change will only be effective until the next Docker restart—so if you wish to revert, simply use `docker compose` or `docker-compose` to `down` and `up -d` the containers.

**Comment by Moonbase59** [comment]
Thanks for updating LS @BusterNeece. Confirm it fixes all the "in-between" metadata & remote stream issues, but not the original issue (old metadata replay on DJ input).

I observe the following, using Rolling Release #[1e2aa03](https://github.com/AzuraCast/AzuraCast/commit/1e2aa033d2c7c266c084d6d37f24e02e106f637d) (2024-02-04 11:46):

- Metadata "on-off" and remote stream issues fixed.
- **On first DJ conect after station restart, `<Unknown>` is shown for both artist and title**, until the next song metadata is picked up from the DJ stream (or he manually updates).
- Titles then shown correctly until streaming ends.
- **On leaving the stream and returning to AutoDJ, for a short time, like fractions of a second to a few seconds, some (previous?) song fragment (and its metadata) are played.** Looks like some buffer content being played.
- Then switches to next song (and following) correctly.
- **Upon _next_ DJ stream, the last song’s metadata from this input is shown**, until the next song metadata is picked up from the DJ stream (or he manually updates).

So some major issues fixed but something small remains.
