### ISSUE TITLE
AzuraCast slows down when connected to S3 storage

### ISSUE THREAD

**Issue by Sella-GH** [AzuraCast/AzuraCast#6907]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #f2c5050 (2024-01-30 17:51)

### What happened?

Because of Issues regarding Album Arts we switched from SFTP to S3 storage (Synology C2 Object storage) but now experience extremely high performance issues every now and then.

Server runs on 2 exclusive virtual cores with 8 GB of RAM and does not spike out at all. Only for a little bit of time the disk spikes up to 5 Mbps (approx. 10s) - I'd guess that's when Azura tries to buffer the things coming from the external S3 storage.

However the UI is extremely laggy sometimes and even NGINX refuses to respond when loading the page or even working with the API. Timeouts after trying more than 15s to connect occur more often right now than when we were using regular local storage of the server.

If you need any log info tell me and I snap it from the server.

**Comment by Ignacio1972** [comment]
Are you having problems with Art Album using S3 for storage and web uploader. All my tracks are going back to default image because I´m using S3. Any advice or help with that?  Thanks !

**Comment by Sella-3DX** [comment]
Album Art works totally fine, only issue is the slowdown.
