### ISSUE TITLE
(Edge case documentation) Playing progress reset to 0:00, duration stays, when jingle with suppressed metadata interrupts

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6909]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #9bab412 (2024-02-01 19:48)

### What happened?

This is mainly to document an edge case:

- Assume you have a playlist 1 with long songs in the AutoDJ.
- Another interrupting playlist 2 with hidden metadata, say a TOTH announcement.
- It’s a full hour and jingle from playlist 2 hits in while long song from playlist 1 plays.
- Playing "elapsed" resets to 0:00, while duration is kept, due to the metadata replay.
- In the official web player, the progress bar will jump backwards to zero, but still show the full song duration (and later end the song "somewhere in the middle" when it is really ending).
- This also affects my SSE playing progress bars, since I can only rely on what’s coming in the nowplaying updates.

This might be too much effort to handle, since it’s an edge case, but at least I wanted to document it somewhere.

A similar situation can happen when you use `blank.skip` and the song has a very silent ending: It gets skipped and the progress bars will look like it has prematurely ended (which it actually _has_ in this case).

See also: [Example for dynamic webpages, using AzuraCast’s HPNP (High-Performance Now Playing) API and SSE (Server-Sent Events)](https://gist.github.com/Moonbase59/d42f411e10aff6dc58694699010307aa?permalink_comment_id=4786603#gistcomment-4786603), under _Known Problems_.

**Comment by unudelaradio** [comment]
I'm using Azuracast for about 2 years, but few days ago i decided to finally test, for the first time, this 'Interrupt other songs to play at scheduled time' feature. I noticed too this playing progress behaviour. Why so complicated?

What i was expected from this feature? I think everything would be more simple if the interruption will act as a SKIP. Also this will sound more like a radio software. In my opinion, the interrupted song should be totally skipped. No coming back. After the announcement ends, the AutoDJ should play a jingle or next song. This will sound more... RADIO.

**Comment by Moonbase59** [comment]
Keep?

**Comment by BusterNeece** [comment]
@Moonbase59 Is this still a thing that's happening?

**Comment by Moonbase59** [comment]
Sorry, just found this again.
Not happening anymore. It now "sticks at the end", and tbh, I see no better way to do it, really.
Closing.
