### ISSUE TITLE
Simple URL Webhook

### ISSUE THREAD

**Issue by ohld** [AzuraCast/AzuraCast#691]
There are a lot of ways to manage web hooks in Azuracast now. 
But I can not make simple get Webhook to trigger something.

For example, I'd like to send a message to our Telegram chat when a DJ is connected to the radio.

Normally I just go to this url:
```
https://api.telegram.org/bot<bot_token>/sendMessage?chat_id=-1001433&text=LIVE
```

![image](https://user-images.githubusercontent.com/5613295/43594322-9cda517a-9682-11e8-8bd4-ee002856f395.png)

How can I solve it my myself or I should wait for the new feature?

**Comment by MyTheValentinus** [comment]
Hello,

You can get this with a transitional server.
For example i have a simple webhook that understand azuracast post body and reformat for another service.

Thanks

**Comment by MyTheValentinus** [comment]
Or another solution is to add telegram as template for azuracast.
I think is not so hard

**Comment by ohld** [comment]
Thats why I'm asking for the enhancement.

**Comment by SlvrEagle23** [comment]
@ohld Not sure why that doesn't register as a valid URL...it appears pretty valid to me.

Either way, we can avoid some trouble (and make the message configurable with variables) by adding a Telegram connector. Should be simple enough; I'll work on that and let you know.

**Comment by MyTheValentinus** [comment]
@SlvrEagle23 You work on this ? I able to make this if you want

**Comment by SlvrEagle23** [comment]
@ohld @MyTheValentinus The Telegram webhook connector has been completed and is ready for use in the latest version of the AzuraCast codebase.

I don't have a Telegram bot myself, so I can't test the actual final step of posting just yet, but let me know if it works for your purposes and if there are any errors I can take a look at them shortly.

**Comment by MyTheValentinus** [comment]
Hello,
Fast dev ! Great, i will test this feature soon
Thanks

**Comment by ohld** [comment]
@SlvrEagle23 Thanks! Will this feature appear when I run `update` command in docker?

**Comment by MyTheValentinus** [comment]
@ohld, yes update your docker installation, i have new feature after this

**Comment by MyTheValentinus** [comment]
Hello @SlvrEagle23 i'v test telegram hook, work perfectly ! Nice work

**Comment by SlvrEagle23** [comment]
@MyTheValentinus Good to hear! Closing this issue as complete; let me know if any issues arise with this webhook later on.

@ohld Yes, the feature should appear if you run `./docker.sh update` (if you're using the Docker utility script). :)

**Comment by ohld** [comment]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/5613295/43984970-97ab691a-9d0c-11e8-91d8-2d3d34959229.png">
I've updated Azuracast. Telegram webhook have not been triggered by song change.

**Comment by MyTheValentinus** [comment]
Are you sure your bot has access to your chat ? You need to initiate communication if is your first message with bot. Simply send message to the bot if is private conversation, or put the bot as admin if is in a group chat.

**Comment by ohld** [comment]
@MyTheValentinus I definitely checked that. The simple webhook
```
https://api.telegram.org/bot462636304:AAEgasdasdsadasdamg0nL_9zvU/sendMessage?chat_id=-1000012000092433&text=SAMPLE_TEXT
```
works

**Comment by SlvrEagle23** [comment]
@ohld @MyTheValentinus I've expanded the Web Hooks configuration page to add a new "Test" button, which will let you manually trigger a web hook and view the raw response, which should help you identify the problem.

**Comment by ohld** [comment]
@SlvrEagle23  Thanks! I'll update now and check it.

**Comment by ohld** [comment]
@SlvrEagle23 I've received this error:

<img width="982" alt="image" src="https://user-images.githubusercontent.com/5613295/44001623-3a8ca7e8-9e3e-11e8-8d3c-7a0227c75db4.png">

**Comment by ohld** [comment]
I think, I've found the solution:

Telegram is blocked in my country: Russia. That is why the request can't be made. Thanks anyway!

**Comment by ohld** [comment]
Ok, thanks anyway.

**Comment by SlvrEagle23** [comment]
@ohld In the interest of supporting radio stations across the globe, I've updated the code to allow you to manually specify the address where the Telegram API is located. By default, it'll use `https://api.telegram.org/`, but you can specify any other third-party service, like `https://api.pwrtelegram.xyz/` (currently down) or any other similar proxy that exists.

That should let you still interact with Telegram even if the main Telegram API is blocked. :)

**Comment by ohld** [comment]
WOW. Thanks, I'll check it.

**Comment by ohld** [comment]
I've moved our Azuracast server to Google Cloud, where Telegram API isn't blocked. And all works fine! Thank you again @SlvrEagle23

**Comment by Feisalgro** [comment]
I just made this work, I had one error and that's because I added the bot to a group where regular users don't have permission to write messages, so I changed the bot's permissions (made him an admin) and all works smoothly.

My only question is how do I write a piece of code if I want the bot to:
- send a message each time the track changes
- have the track title and artist in the message
?

The first part I got, but the second part I don't know what to write.

I went here: https://www.azuracast.com/api/#/
created an API key and connected it, but the tip "Variables are in the form of: {{ var.name }}" did not help me out because I'm not a coder. 

Can someone else please tell me how to do it?
