### ISSUE TITLE
letsencrypt certificate refresh without nginx reload

### ISSUE THREAD

**Issue by wendelinux** [AzuraCast/AzuraCast#6918]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.3

### What happened?

after a while i notice certificate invalid notifications in my browser. When asking for a new certificate azuracasts says that there are no certificates due for renewal.
when i reboot the system the certificate is valid without dooing a renewal.
it looks to me that when the letsencrypt certificate gets updated, nginx is not beeing reloaded. Without reload it'll keep using the old and expired certificate

**Comment by BusterNeece** [comment]
Fixed in the latest version of the Rolling Release. Thanks, @skoerfgen!
