### ISSUE TITLE
High-Performance Updates - Websockets

### ISSUE THREAD

**Issue by dabclassic-o** [AzuraCast/AzuraCast#6919]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #7f629b0 

### What happened?

Using High-Performance Updates - Websockets, no song update, neither posters

### Relevant log output

```shell
wss://your-azuracast-url/api/live/nowplaying/websocket
```

**Comment by dabclassic-o** [comment]
Public needs to be activated to allow Websockets

**Comment by Moonbase59** [comment]
@dabclassic-o Good to know, thanks for coming back with the info!
