### ISSUE TITLE
Implement Facebook Webhook

### ISSUE THREAD

**Issue by NeddyPlays** [AzuraCast/AzuraCast#692]
Hi,

I love the Twitter and Discord auto posting! Is it possible to also have a Facebook auto poster?
Not to my personal Facebook but a page i made.

**Comment by ohld** [comment]
@NeddyPlays I don't have a solution for you, I'm not a developer.

But I host a radio station too. Can you please share your station and your pages? May be we can share the experiences.
My stations is https://radio.mipt.ru
My contact: okhlopkov@phystech.edu

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38918/add-facebook-webhook
