### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by peckamal** [AzuraCast/AzuraCast#6931]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.4

### What happened?

Hi, after updating to v0.19.4 Stable, this error appears and I don't know how to proceed, Thank you

> An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.user_passkeys' doesn't exist

**Comment by roger-net** [comment]
Run the update command again and upon completion, restart the server.

**Comment by peckamal** [comment]
> Run the update command again and upon completion, restart the server.

Thank you
