### ISSUE TITLE
azuracast freezes / dies  as server suddenly runs out of space 

### ISSUE THREAD

**Issue by marekdziem** [AzuraCast/AzuraCast#6932]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.19.4 Stable

### What happened?

A concerned station woke me at the crack of dawn today in a panic that their station shows as offline but their encoder still seems to be running.

I jump on the admin dasdhboard and see all stations are offline.
I ssh in and cant even docker compose down / up - the server is completely out of space  - 0% available.

After some frantic file deletion I am able to restart the server but azurcast docker doenst come automatically - had to manually compose it up.

after seeing the streamerDJ encoders connecting again I looked more closely at the file system.
/var/lib/docker/volumes/azuracast_station_data is using up only 20Gb of disk space on the 182gb drive.
but 
/var/lib/docker/overlay2 reports taking up a whopping 150Gb of disk space!

docker prune commands do nothing to alleviate the massive overlay2 size.
I've read not to fiddle with the folders & files in docker/overlay2 lest I break the running azuracast container irreparably. 
What can be done about this docker overlay / diff / tmp /merged disk space ballooning problem - especially while azuracast is running live?

The station data footprint is about 20gb - there should normally be 160Gb space available to both the host server and azuracast!!

WTF!?

PS I had just 'migrated' this server from rolling to stable a few weeks ago - a tremendously vexing mission: see https://github.com/AzuraCast/AzuraCast/issues/6895

### Relevant log output

```shell
20G	2024-02-10 01:02	/var/lib/docker/volumes
4.3M	2024-02-10 01:02	/var/lib/docker/containers
108K	2024-02-09 13:12	/var/lib/docker/buildkit
3.4M	2024-02-09 08:43	/var/lib/docker/image
544K	2024-02-09 08:13	/var/lib/docker/network
261G	2024-02-10 01:02	/var/lib/docker/overlay2
4.0K	2023-11-06 06:53	/var/lib/docker/swarm
16K	2023-11-06 06:53	/var/lib/docker/plugins
4.0K	2024-02-09 08:12	/var/lib/docker/runtimes
4.0K	2024-02-09 08:12	/var/lib/docker/tmp
281G	2024-02-10 01:02	/var/lib/docker/
```

**Comment by marekdziem** [comment]
the sftp store files are available to queue and playback via the public player though

**Comment by marekdziem** [comment]
sasme issue - server suddenly out of space= cant prune docker -

**Comment by marekdziem** [comment]
it happened again!

root@radio3-redo:/var/azuracast# docker-compose down
[+] Running 3/3
✔ Container azuracast_updater  Removed                                                                                                                                                0.5s 
 ✔ Container azuracast          Removed                                                                                                                                               22.6s 
 ✔ Network azuracast_default    Removed                                                                                                                                                0.3s 
root@radio3-redo:/var/azuracast# docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
root@radio3-redo:/var/azuracast# docker image prune -a
WARNING! This will remove all images without at least one container associated to them.
Are you sure you want to continue? [y/N] y
Deleted Images:
untagged: ghcr.io/azuracast/azuracast:stable
untagged: [ghcr.io/azuracast/azuracast@sha256:362457a1467584c5040346f24b821c07f6bf502ac56553c4ccd3bc01491b1f68](mailto:ghcr.io/azuracast/azuracast@sha256:362457a1467584c5040346f24b821c07f6bf502ac56553c4ccd3bc01491b1f68)
deleted: sha256:f2e4d2ad45547157efeba9845f2dfa0594986e35bb17351648a5646a85cc61dd
deleted: sha256:cb5e252d57008c41aaaed56ab4c976b653a73ee6a94fb28014721c120b14932b
deleted: sha256:cc645aea3839c083fa3b3418d5b5aeebda9bd143f1b3359450606e2e8794fb50
deleted: sha256:d6ee89325d95d2a60210f9d7836fdfcb2f594d20bcfbe0d1abd7555df98940e7
deleted: sha256:cd5d1b1aa04b67063e10da1c961c3c4f28a6b4f6234da873d5e3efaad933bc3d
deleted: sha256:8ab74f86e764919b9f36cfe9a0c235c6425329b9e44402ad30874ae35b7a6107
deleted: sha256:142403e349c8547c854c26711861d78c87e051928c9f7f3d6bc9a9aacd45b5fe
deleted: sha256:dc4259285e78c72ae32b502efe71660bb7e5ac178b731712476ba4e6e9c3dfcd
deleted: sha256:fa99c6b35e0f8eb02f1236f2f422bad404125b825a374ead80b5c18c6969fa09
deleted: sha256:406322c931ee0a219f2dcef217d773a9cd31eda76e98f99e93a2d098a167372d
deleted: sha256:f00d02737e722734f5b08a02a9ff0fad1114220c1cead25ed59974ffbe32a9e9
deleted: sha256:30e8df0294257b41d0ecab6da39d8456836019306e99ab769312559c788bdbba
deleted: sha256:ba8df21d7b5d337bff2594c9df3e6f45fec9faf0b8eba287c74aa28226577de5
deleted: sha256:07e4b625ff26f0a755f7133a9df9d3b973ad05a75ba75bdf81308104324bc8cf
deleted: sha256:e3be1225a1958b8482878f2d01d61f1918a4c56a9e6644b377060ce0383b3376
deleted: sha256:ef5685858152b60310340c80e93907508cb7c6459d7587ee4f7c94e59bdc1c5f
deleted: sha256:381183f0d648c142c807be269629867d9f9d5fed252d294414acb20c133d3001
deleted: sha256:3ff824433ccb1da63d207e6f0053c9568e529aee13f21eadbc7a604d922bffd0
deleted: sha256:60c048c960dc0ee0cd2be53b3cab85f89996230236cc57175d54c63ceeed38ea
deleted: sha256:36309df54ecc48731d9c1ac6fbd01488188e46f0f0f20cdbb76cfb71f6ec33d4
deleted: sha256:8a463fc7294ef0ff8110e91cf11e56378b2af6fe1f143d5884092022d3371235
deleted: sha256:76c3e1accff7b05a54a8916dbadb2628e84a2b4cdfad51a6353879dcccda9f81
deleted: sha256:afd8b0c5ce2df2a7f6357bc4c8b712638b1a8ed1a65de5c9a95476cfe6977402
deleted: sha256:a7aa0e29398d75e617c48cb9cb5e0cc6d343824b5dd481d6613697690e9fe4e9
deleted: sha256:a7a3f8908f49843348ebe0dd6f234947b287cd3b2f4dbe4a6b5d5d45c5d7ad77
deleted: sha256:e38112373a829de3c42f1218c69a5cf9ca965c0438a4f49d1f447263d0186d67
deleted: sha256:eb749a667139d8ea14ddf6eb1bcbdf09a90dfa443b8a9f399649f9a8fa187c8a
deleted: sha256:d6ad0c40c3393fde7b27a5410c9168087d5c4a2b6d5dc8a9e5f6e41baf0f2b1a
deleted: sha256:eab62278295a5a09223ad2a92877d9504235f16f13c3ce90828ad65db51391b2
deleted: sha256:878a05a25657f6df384f6e09c3800f2e8c8095fd94b41e05c2d418429b29b0b7
deleted: sha256:009d1b558d4644cf513391255e6e04a19601c716f59bd7bfa6e11778b3fe0ffd
deleted: sha256:fa9c4eee81c755e7684f94396cd34b03b10638ec0b54ed39041419ab8d3bc0bc
deleted: sha256:775c1ff11d82537f0855df6b3693d7ec0278c8ea24aa6205602a8b32b2301c83
deleted: sha256:fc267024837f41aae5e16d79eb0a0d68f3d5d2e7c3ce1f2950f5e13aa4c04d5c
deleted: sha256:b792e87f316a93d5048c18c5666b8a9d04b753f52e6c0a53a4131429d70e9ded
deleted: sha256:c4bf47140a160977c24228d939b3c1208e81e91c90533ba5278e251d487e071e
deleted: sha256:f639e34004666949d9b7223d6c261d1f41c9a2df5ca0c7755207c7e211fae111
deleted: sha256:ceb365432eec83dafc777cac5ee87737b093095035c89dd2eae01970c57b1d15
untagged: ghcr.io/azuracast/updater:latest
untagged: [ghcr.io/azuracast/updater@sha256:27b20a46f5a87de668807f952779187dfa44085cd786e4673373f6fc99c468dc](mailto:ghcr.io/azuracast/updater@sha256:27b20a46f5a87de668807f952779187dfa44085cd786e4673373f6fc99c468dc)
deleted: sha256:7725e0ece43875fa07b14a54c3686cb1f1686d15fdf8727a871a78b4b58c1cd6
deleted: sha256:44fb93f2573db3c572e2e2a27b09607284f539cfb73c27902c08184d02c8ee38
deleted: sha256:b020833797a5d27bc3fe4d8312f29ad4a28e3fe99043e163d74a20e6bb22869b
deleted: sha256:19152fbe55ec0e7d50efa7a3cae90189cac61f762e5e8d0a095db144edcf9e84

Total reclaimed space: 1.923GB
root@radio3-redo:/var/azuracast#


was in a rush to get services up again for clients so didnt get a docker volume dir listing

**Comment by marekdziem** [comment]
and it happened yet again... :( WHY!?
root@radio3-redo:/var/lib/docker# find . -type f -size +100M -exec du -h {} + 2>/dev/null | sort -r -h
57G	./overlay2/adad54595512e4d7b56019ea6205b12759434cada7f5dd169bf9ad00c3f602d0/merged/tmp/backup_93697011266022d8a35a157.93738304.tgz
57G	./overlay2/adad54595512e4d7b56019ea6205b12759434cada7f5dd169bf9ad00c3f602d0/diff/tmp/backup_93697011266022d8a35a157.93738304.tgz
54G	./overlay2/adad54595512e4d7b56019ea6205b12759434cada7f5dd169bf9ad00c3f602d0/merged/tmp/backup_92122794266037f46074d32.01178331.tgz
54G	./overlay2/adad54595512e4d7b56019ea6205b12759434cada7f5dd169bf9ad00c3f602d0/diff/tmp/backup_92122794266037f46074d32.01178331.tgz
617M	./volumes/azuracast_db_data/_data/azuracast/listener.ibd
505M	./overlay2/adad54595512e4d7b56019ea6205b12759434cada7f5dd169bf9ad00c3f602d0/merged/tmp/azuracast_backup_mariadb/db.sql
505M	./overlay2/adad54595512e4d7b56019ea6205b12759434cada7f5dd169bf9ad00c3f602d0/diff/tmp/azuracast_backup_mariadb/db.sql
501M	./volumes/azuracast_station_data/_data/bogart/media/tequilagang_rec_pereremidrand_with_chronicaldeep_ottob_tsmooth_trevordee.mp3
230M	./volumes/azuracast_station_data/_data/bogart/recordings/BogartEnc/stream_20240318-100913.mp3
119M	./volumes/azuracast_station_data/_data/bogart/media/deep_melodious_tribute_to_rocco_special_mix_mixed_by_yzee_melodious.mp3
112M	./overlay2/adad54595512e4d7b56019ea6205b12759434cada7f5dd169bf9ad00c3f602d0/merged/usr/lib/x86_64-linux-gnu/libLLVM-15.so.1
112M	./overlay2/5eeea92fade2ca1fadc178882db03d39fdaff9f4ac1f608a672277275060bd5d/diff/usr/lib/x86_64-linux-gnu/libLLVM-15.so.1
109M	./volumes/azuracast_db_data/_data/azuracast/song_history.ibd
root@radio3-redo:/var/lib/docker# 



root@radio3-redo:/var/azuracast# docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
root@radio3-redo:/var/azuracast# docker image prune -a
WARNING! This will remove all images without at least one container associated to them.
Are you sure you want to continue? [y/N] y
Deleted Images:
untagged: ghcr.io/azuracast/updater:latest
untagged: ghcr.io/azuracast/updater@sha256:27b20a46f5a87de668807f952779187dfa44085cd786e4673373f6fc99c468dc
deleted: sha256:7725e0ece43875fa07b14a54c3686cb1f1686d15fdf8727a871a78b4b58c1cd6
deleted: sha256:44fb93f2573db3c572e2e2a27b09607284f539cfb73c27902c08184d02c8ee38
deleted: sha256:b020833797a5d27bc3fe4d8312f29ad4a28e3fe99043e163d74a20e6bb22869b
deleted: sha256:19152fbe55ec0e7d50efa7a3cae90189cac61f762e5e8d0a095db144edcf9e84
untagged: ghcr.io/azuracast/azuracast:stable
untagged: ghcr.io/azuracast/azuracast@sha256:362457a1467584c5040346f24b821c07f6bf502ac56553c4ccd3bc01491b1f68
deleted: sha256:f2e4d2ad45547157efeba9845f2dfa0594986e35bb17351648a5646a85cc61dd
deleted: sha256:cb5e252d57008c41aaaed56ab4c976b653a73ee6a94fb28014721c120b14932b
deleted: sha256:cc645aea3839c083fa3b3418d5b5aeebda9bd143f1b3359450606e2e8794fb50
deleted: sha256:d6ee89325d95d2a60210f9d7836fdfcb2f594d20bcfbe0d1abd7555df98940e7
deleted: sha256:cd5d1b1aa04b67063e10da1c961c3c4f28a6b4f6234da873d5e3efaad933bc3d
deleted: sha256:8ab74f86e764919b9f36cfe9a0c235c6425329b9e44402ad30874ae35b7a6107
deleted: sha256:142403e349c8547c854c26711861d78c87e051928c9f7f3d6bc9a9aacd45b5fe
deleted: sha256:dc4259285e78c72ae32b502efe71660bb7e5ac178b731712476ba4e6e9c3dfcd
deleted: sha256:fa99c6b35e0f8eb02f1236f2f422bad404125b825a374ead80b5c18c6969fa09
deleted: sha256:406322c931ee0a219f2dcef217d773a9cd31eda76e98f99e93a2d098a167372d
deleted: sha256:f00d02737e722734f5b08a02a9ff0fad1114220c1cead25ed59974ffbe32a9e9
deleted: sha256:30e8df0294257b41d0ecab6da39d8456836019306e99ab769312559c788bdbba
deleted: sha256:ba8df21d7b5d337bff2594c9df3e6f45fec9faf0b8eba287c74aa28226577de5
deleted: sha256:07e4b625ff26f0a755f7133a9df9d3b973ad05a75ba75bdf81308104324bc8cf
deleted: sha256:e3be1225a1958b8482878f2d01d61f1918a4c56a9e6644b377060ce0383b3376
deleted: sha256:ef5685858152b60310340c80e93907508cb7c6459d7587ee4f7c94e59bdc1c5f
deleted: sha256:381183f0d648c142c807be269629867d9f9d5fed252d294414acb20c133d3001
deleted: sha256:3ff824433ccb1da63d207e6f0053c9568e529aee13f21eadbc7a604d922bffd0
deleted: sha256:60c048c960dc0ee0cd2be53b3cab85f89996230236cc57175d54c63ceeed38ea
deleted: sha256:36309df54ecc48731d9c1ac6fbd01488188e46f0f0f20cdbb76cfb71f6ec33d4
deleted: sha256:8a463fc7294ef0ff8110e91cf11e56378b2af6fe1f143d5884092022d3371235
deleted: sha256:76c3e1accff7b05a54a8916dbadb2628e84a2b4cdfad51a6353879dcccda9f81
deleted: sha256:afd8b0c5ce2df2a7f6357bc4c8b712638b1a8ed1a65de5c9a95476cfe6977402
deleted: sha256:a7aa0e29398d75e617c48cb9cb5e0cc6d343824b5dd481d6613697690e9fe4e9
deleted: sha256:a7a3f8908f49843348ebe0dd6f234947b287cd3b2f4dbe4a6b5d5d45c5d7ad77
deleted: sha256:e38112373a829de3c42f1218c69a5cf9ca965c0438a4f49d1f447263d0186d67
deleted: sha256:eb749a667139d8ea14ddf6eb1bcbdf09a90dfa443b8a9f399649f9a8fa187c8a
deleted: sha256:d6ad0c40c3393fde7b27a5410c9168087d5c4a2b6d5dc8a9e5f6e41baf0f2b1a
deleted: sha256:eab62278295a5a09223ad2a92877d9504235f16f13c3ce90828ad65db51391b2
deleted: sha256:878a05a25657f6df384f6e09c3800f2e8c8095fd94b41e05c2d418429b29b0b7
deleted: sha256:009d1b558d4644cf513391255e6e04a19601c716f59bd7bfa6e11778b3fe0ffd
deleted: sha256:fa9c4eee81c755e7684f94396cd34b03b10638ec0b54ed39041419ab8d3bc0bc
deleted: sha256:775c1ff11d82537f0855df6b3693d7ec0278c8ea24aa6205602a8b32b2301c83
deleted: sha256:fc267024837f41aae5e16d79eb0a0d68f3d5d2e7c3ce1f2950f5e13aa4c04d5c
deleted: sha256:b792e87f316a93d5048c18c5666b8a9d04b753f52e6c0a53a4131429d70e9ded
deleted: sha256:c4bf47140a160977c24228d939b3c1208e81e91c90533ba5278e251d487e071e
deleted: sha256:f639e34004666949d9b7223d6c261d1f41c9a2df5ca0c7755207c7e211fae111
deleted: sha256:ceb365432eec83dafc777cac5ee87737b093095035c89dd2eae01970c57b1d15

Total reclaimed space: 1.923GB
root@radio3-redo:/var/azuracast# 


@BusterNeece  ???  please we need help to find a way to stop / avoid this coz we stand to see clients churn :(
it 's a standard vannilla debian server instance only running azurazcast and nothing else. :(

**Comment by BusterNeece** [comment]
@marekdziem It's your automated backups. You can tell from the largest files in there...they're all related to the automatic backup system. You should either disable these backups or keep fewer copies.

**Comment by marekdziem** [comment]
Hi Buster ,
Nope! incorrecto - daily azuracast backups use remote sftp thus dont stay on the server disk at all.
![image](https://github.com/AzuraCast/AzuraCast/assets/3094096/e3b45ac5-dad8-4bc9-9445-6b5e8c2e94b9)

**Comment by BusterNeece** [comment]
@marekdziem 

> Nope! incorrecto

Please consider, for a moment, that I may understand my own software quite well.

Even when backing up to an external source like SFTP, in order to _build_ the file that we're transferring over to the remote location, we have to assemble all the local files together into a temp directory. This means that for automated backups to work correctly, we have to have as much space free on the local disk as the total size of the media you're wanting to back up. If you don't have that space, then the backup process will fail as it's trying to assemble everything, which means the backup won't ever be uploaded, which means the temp file won't ever be removed, which means you'll run into this situation.

It's clear from your logs that your largest files _are_ these temp backup files. That's why I specifically pointed out the backup process. I didn't just guess that, it's specifically spelled out in your logs.

If there's a bug that's preventing the local backup files from being removed after a successful backup, then we can look into that, but first you should make sure that your local VPS (or whatever partition you have Docker mounted on, i.e. that would be used by `/tmp` inside the Docker container, not necessarily `/var/azuracast/backups`) has enough space to permit a full backup to complete successfully. Another point of interest will be to look at the logs from the backup process itself to see if it's erroring out, though if the disk completely fills up, it might not throw any clear errors and might instead just fail in an unexpected way.

**Comment by marekdziem** [comment]
@BusterNeece you're sincerely appreciated - apologies if I came across otherwise!
What puzzles me is that this has occurred previously even when there was sufficient disk space. Pity I didnt capture timestamps of the files before pruning!

From the most recent backup log - which ran on schedule last night - and seems to have completed fine:

Exited with code 0:
AzuraCast Backup
================
....
.,..
Cleaning up temporary files...
------------------------------
 [OK] Backup complete in 3041.09 seconds.

The azurcast admin cron logs dont yield any further insights, having no errors shown. Where else shoudl I look?

This issue occured first on 16 feb, going from:
![image](https://github.com/AzuraCast/AzuraCast/assets/3094096/cefa6fe1-4c18-4faf-bf5c-02d9c9a80554)
and after pruning etc, to:
Filesystem     1K-blocks     Used Available Use% Mounted on
udev             3993340        0   3993340   0% /dev
tmpfs             803208      720    802488   1% /run
**/dev/sda1      183684504 43239632 131041380  25% /**
tmpfs            4016028        0   4016028   0% /dev/shm
tmpfs               5120        0      5120   0% /run/lock
tmpfs             803204        0    803204   0% /run/user/1000

that was with approx. 25% space used.

The same issue occurred this past monday 24 march, so the docker tmp stuff was subsequently pruned and ample space made available again - admin dash showed use to be under 50%.

and then it occurred again this morning as you know!
right now azura admin  dash shows:74.8 GB of total Disk Space : 175.2 GB

**Comment by EdgeCaseLord** [comment]
I had the same problem with PostGreSQL logs cluttering the server.

**Comment by BornKillaz** [comment]
I'm having the exact same problem with latest stable version. All sites in the VPS are down. 0% space left on disk.

Anyone got this solved?

**Comment by BornKillaz** [comment]
Ok, in my case it was that I had multiple temporary nonsense backups originated by AzuraCast, each with 19GB... 

So, I found them with:
`find /var/lib/docker -type f -size +100M -exec ls -lh {} \; | sort -k5 -hr | head -n 20`

And I got a few of these:
`-rw-r--r-- 1 1000 psaadm 19G Dec  9 04:22 /var/lib/docker/overlay2/e7a7052202b2be3ec48b61fc789d15c41ae1e76623477c9ecfa2992d44039489/merged/tmp/backup_15394532756756621d1aff75.37822613.zip
-rw-r--r-- 1 1000 psaadm 19G Dec  9 04:22 /var/lib/docker/overlay2/e7a7052202b2be3ec48b61fc789d15c41ae1e76623477c9ecfa2992d44039489/diff/tmp/backup_15394532756756621d1aff75.37822613.zip
-rw-r--r-- 1 1000 psaadm 19G Dec  8 04:21 /var/lib/docker/overlay2/e7a7052202b2be3ec48b61fc789d15c41ae1e76623477c9ecfa2992d44039489/merged/tmp/backup_652917497675510614c5e63.49236989.zip
-rw-r--r-- 1 1000 psaadm 19G Dec  8 04:21 /var/lib/docker/overlay2/e7a7052202b2be3ec48b61fc789d15c41ae1e76623477c9ecfa2992d44039489/diff/tmp/backup_652917497675510614c5e63.49236989.zip
-rw-r--r-- 1 1000 psaadm 19G Dec  7 04:20 /var/lib/docker/overlay2/e7a7052202b2be3ec48b61fc789d15c41ae1e76623477c9ecfa2992d44039489/merged/tmp/backup_20629065586753bea56fd5b5.71409341.zip
-rw-r--r-- 1 1000 psaadm 19G Dec  7 04:20 /var/lib/docker/overlay2/e7a7052202b2be3ec48b61fc789d15c41ae1e76623477c9ecfa2992d44039489/diff/tmp/backup_20629065586753bea56fd5b5.71409341.zip
-rw-r--r-- 1 1000 psaadm 19G Dec  6 04:19 /var/lib/docker/overlay2/e7a7052202b2be3ec48b61fc789d15c41ae1e76623477c9ecfa2992d44039489/merged/tmp/backup_168977236767526ce968f951.26909713.zip
-rw-r--r-- 1 1000 psaadm 19G Dec  6 04:19 /var/lib/docker/overlay2/e7a7052202b2be3ec48b61fc789d15c41ae1e76623477c9ecfa2992d44039489/diff/tmp/backup_168977236767526ce968f951.26909713.zip`

I got rid of them and got my space back, and now the server is up and running. But yes, that was insane. I now need to keep an eye on these to ensure it doesn't happen again, as the disk was completely full because of this. 

Also, I have Azuracast to only keep a couple of backups, not 8 of them.

**Comment by ronlaws86** [comment]
There is a slight design flaw in the backup process that needs to be addressed, as this is a likely cause of a lot of 'lost disk space' 

For me, my server had a hole in it's available disk space and it was unclear where exactly this hole (to the sum of 30GB) was. 
I found that there was a Docker overlay pertaining to Azuracast with a bunch of failed backup archives and other stuff that had not been deleted on failure, but did not show up in the GUI to be deleted either. 

```
$:/var/lib/docker/overlay2/<UUIDsnip>/merged/tmp# du -shx * | sort -rh | head -10
**8.5G	backup_43484568667a05f6101a969.38606885.
3.9G	backup_4349087467a06a8c6a41b9.72914055.tzst
3.6G	backup_15111932367a072d3119be6.85052601.tzst**
51M	stdout-stdout---supervisor-vfbgi8ay.log.4
51M	stdout-stdout---supervisor-vfbgi8ay.log.3
51M	stdout-stdout---supervisor-vfbgi8ay.log.2
51M	stdout-stdout---supervisor-vfbgi8ay.log.1
37M	stdout-stdout---supervisor-vfbgi8ay.log
11M	master_me
984K	azuracast_backup_mariadb

```
these are temp backup files that failed to complete for one reason or another (Disk space in my case) but were not automatically purged from the disk, thus wasting space. If the backup script fails to complete, it should purge these files - not leave unreferenced, half-finished backup archives sitting in an obscure, undisclosed location on the system.

**Comment by BusterNeece** [comment]
@ronlaws86 This was fixed in a recent Rolling Release, but hasn't been included in the latest Stable release yet.
