### ISSUE TITLE
[Installation Phase]: open /var/lib/snapd/void/docker-compose.installer.yml: no such file or directory

### ISSUE THREAD

**Issue by J0hn3ch** [AzuraCast/AzuraCast#6939]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

Following the official guide with Docker installation (recommended), during the installation phase this happen when launch the last command to install AzuraCast

`root@server:/var/azuracast# ./docker.sh install`
`Checking installation requirements for AzuraCast...`
`[PASS] Operating System: Linux`
`[PASS] Architecture: x86_64`
`[PASS] Command Present: curl`
`[PASS] Command Present: awk`
`[PASS] User Permissions`
`[PASS] Installation Directory`
`[PASS] All requirements met!`
`Docker is already installed! Continuing...`
`Docker Compose v2 is already installed. Continuing...`
`Your current release channel is 'Stable'. Switch to 'Rolling Release' release channel? [y/N]: N`
`stat /var/lib/snapd/void/docker-compose.installer.yml: no such file or directory`
`stat /var/lib/snapd/void/docker-compose.installer.yml: no such file or directory`
`no configuration file provided: not found`
`no configuration file provided: not found`
`no configuration file provided: not found`

Operating System: Ubuntu 22.04

### Relevant log output

```shell
root@azuracast-server:/var/azuracast# ./docker.sh install
Checking installation requirements for AzuraCast...
[PASS] Operating System: Linux
[PASS] Architecture: x86_64
[PASS] Command Present: curl
[PASS] Command Present: awk
[PASS] User Permissions
[PASS] Installation Directory
[PASS] All requirements met!
Docker is already installed! Continuing...
Docker Compose v2 is already installed. Continuing...
Your current release channel is 'Stable'. Switch to 'Rolling Release' release channel? [y/N] N
stat /var/lib/snapd/void/docker-compose.installer.yml: no such file or directory
stat /var/lib/snapd/void/docker-compose.installer.yml: no such file or directory
no configuration file provided: not found
no configuration file provided: not found
no configuration file provided: not found
```

**Comment by kzeirxn** [comment]
I'm also experiencing this issue? Was it easily resolved?

**Comment by stophman1** [comment]
> I'm also experiencing this issue? Was it easily resolved?

You can only build docker files in the home directory with snap docker.
