### ISSUE TITLE
docker is eating up the disk space!

### ISSUE THREAD

**Issue by marekdziem** [AzuraCast/AzuraCast#6950]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.19.4 Stable

### What happened?

this is the second server that has suddenly run out of disk space!
docker seems to be doing something weird with overlay / diff / merge volumes:
288295620	/var
288006324	/var/lib
287850680	/var/lib/docker
256699936	/var/lib/docker/overlay2
255110376	/var/lib/docker/overlay2/2b24fb32698b81ba63c2d2f929eceed36307bbd124235263e181c5fa99055fa3
128331396	/var/lib/docker/overlay2/2b24fb32698b81ba63c2d2f929eceed36307bbd124235263e181c5fa99055fa3/merged
126778960	/var/lib/docker/overlay2/2b24fb32698b81ba63c2d2f929eceed36307bbd124235263e181c5fa99055fa3/diff
126760592	/var/lib/docker/overlay2/2b24fb32698b81ba63c2d2f929eceed36307bbd124235263e181c5fa99055fa3/merged/tmp
126760580	/var/lib/docker/overlay2/2b24fb32698b81ba63c2d2f929eceed36307bbd124235263e181c5fa99055fa3/diff/tmp
31142056	/var/lib/docker/volumes

I dont know what to do to fix it

**Comment by BusterNeece** [comment]
@marekdziem You can run `docker system prune` to clean up unused space on Docker, and if you've left your container running for quite a long time, just restarting it can clear up a ton of space.

**Comment by marekdziem** [comment]
I did - reclaimed exactly 0gb of space!

Deleted Containers:
bad529a016f037db4756c9faa2e5b2e5d5694029ebe299394b758cea7f10c293

Deleted Networks:
azuracast_installer_default

Total reclaimed space: 0B

**Comment by marekdziem** [comment]
isnt there another way to install azurcast?

**Comment by marekdziem** [comment]
I cant even search for lare files now:
du -a / | sort -n -r | head -n 20
	sort: write failed: /tmp/sortcnbIHi: No space left on device

**Comment by marekdziem** [comment]
is it maybe an issue with the underlying OS?
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian

**Comment by BusterNeece** [comment]
@marekdziem Is that your host OS? That's no problem at all, that's quite a new version and is well supported.

You may want to reinstall Docker to get the latest version, though, if you haven't done so in a while. You can use AzuraCast to help with that by running `./docker.sh install-docker`.

**Comment by marekdziem** [comment]
issues....

unable to get image 'ghcr.io/azuracast/azuracast:stable': Error response from daemon: stat /var/lib/docker/overlay2/7d885412c5e2bd66670343971d68be0ab44de2fe1b7dafe81824c3ce12961a1f: no such file or directory
unable to get image 'ghcr.io/azuracast/azuracast:stable': Error response from daemon: stat /var/lib/docker/overlay2/7d885412c5e2bd66670343971d68be0ab44de2fe1b7dafe81824c3ce12961a1f: no such file or directory
unable to get image 'ghcr.io/azuracast/updater:latest': Error response from daemon: stat /var/lib/docker/overlay2/8b2681c6cb0f2c4c0cf8031fd63906a369e734291b57059214cfadf89eb35631: no such file or directory
WARN[0000] volume "azuracast_backups" already exists but was not created by Docker Compose. Use `external: true` to use an existing volume 
unable to get image 'ghcr.io/azuracast/azuracast:stable': Error response from daemon: stat /var/lib/docker/overlay2/7d885412c5e2bd66670343971d68be0ab44de2fe1b7dafe81824c3ce12961a1f: no such file or directory
unable to get image 'ghcr.io/azuracast/updater:latest': Error response from daemon: stat /var/lib/docker/overlay2/8b2681c6cb0f2c4c0cf8031fd63906a369e734291b57059214cfadf89eb35631: no such file or directory

**Comment by marekdziem** [comment]
docker eating up all the space again - 100% disk use
those silly tmp /overlay  files 43Gb plus
docker prune doenst work 

how do I fix trhis? our stations are livid

**Comment by BusterNeece** [comment]
@marekdziem Restarting can often fix this if it's just the temp files in your filesystem overflowing. Otherwise you'd need to look through the overlay filesystem and see what's taking up the space.

**Comment by marekdziem** [comment]
Thanks @BusterNeece again for your attentiveness :)
this time I docker-compose down then ran docker prune which succeeded in clearing out ~150gb tmp/overlay docker stuff, and was soon back online with compose up.

when is docker meant to clean up / purge those massive files normally? is there a recurring cron task or schedule that executes a docker clean up periodically? perhaps server ran out of space while waiting for a coming cleanup? this makes some sense the nearer to 50% of the disk container being duplicated?

**Comment by BusterNeece** [comment]
@marekdziem I'd be really curious to see _which_ temp files are taking up all that space if you have the issue happen again. We actually _do_ have a routine task that should clear up any outdated temp files and prevent that kind of thing from happening.

**Comment by marekdziem** [comment]
@BusterNeece yes fersure I'll dump a filelist of teh big offenders should it happen again!

**Comment by marekdziem** [comment]
it happened again!

**Comment by marekdziem** [comment]
and it happened yet again... :( WHY!?
root@radio3-redo:/var/lib/docker# find . -type f -size +100M -exec du -h {} + 2>/dev/null | sort -r -h
57G	./overlay2/adad54595512e4d7b56019ea6205b12759434cada7f5dd169bf9ad00c3f602d0/merged/tmp/backup_93697011266022d8a35a157.93738304.tgz
57G	./overlay2/adad54595512e4d7b56019ea6205b12759434cada7f5dd169bf9ad00c3f602d0/diff/tmp/backup_93697011266022d8a35a157.93738304.tgz
54G	./overlay2/adad54595512e4d7b56019ea6205b12759434cada7f5dd169bf9ad00c3f602d0/merged/tmp/backup_92122794266037f46074d32.01178331.tgz
54G	./overlay2/adad54595512e4d7b56019ea6205b12759434cada7f5dd169bf9ad00c3f602d0/diff/tmp/backup_92122794266037f46074d32.01178331.tgz
617M	./volumes/azuracast_db_data/_data/azuracast/listener.ibd
505M	./overlay2/adad54595512e4d7b56019ea6205b12759434cada7f5dd169bf9ad00c3f602d0/merged/tmp/azuracast_backup_mariadb/db.sql
505M	./overlay2/adad54595512e4d7b56019ea6205b12759434cada7f5dd169bf9ad00c3f602d0/diff/tmp/azuracast_backup_mariadb/db.sql
501M	./volumes/azuracast_station_data/_data/bogart/media/tequilagang_rec_pereremidrand_with_chronicaldeep_ottob_tsmooth_trevordee.mp3
230M	./volumes/azuracast_station_data/_data/bogart/recordings/BogartEnc/stream_20240318-100913.mp3
119M	./volumes/azuracast_station_data/_data/bogart/media/deep_melodious_tribute_to_rocco_special_mix_mixed_by_yzee_melodious.mp3
112M	./overlay2/adad54595512e4d7b56019ea6205b12759434cada7f5dd169bf9ad00c3f602d0/merged/usr/lib/x86_64-linux-gnu/libLLVM-15.so.1
112M	./overlay2/5eeea92fade2ca1fadc178882db03d39fdaff9f4ac1f608a672277275060bd5d/diff/usr/lib/x86_64-linux-gnu/libLLVM-15.so.1
109M	./volumes/azuracast_db_data/_data/azuracast/song_history.ibd
root@radio3-redo:/var/lib/docker# 



root@radio3-redo:/var/azuracast# docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
root@radio3-redo:/var/azuracast# docker image prune -a
WARNING! This will remove all images without at least one container associated to them.
Are you sure you want to continue? [y/N] y
Deleted Images:
untagged: ghcr.io/azuracast/updater:latest
untagged: ghcr.io/azuracast/updater@sha256:27b20a46f5a87de668807f952779187dfa44085cd786e4673373f6fc99c468dc
deleted: sha256:7725e0ece43875fa07b14a54c3686cb1f1686d15fdf8727a871a78b4b58c1cd6
deleted: sha256:44fb93f2573db3c572e2e2a27b09607284f539cfb73c27902c08184d02c8ee38
deleted: sha256:b020833797a5d27bc3fe4d8312f29ad4a28e3fe99043e163d74a20e6bb22869b
deleted: sha256:19152fbe55ec0e7d50efa7a3cae90189cac61f762e5e8d0a095db144edcf9e84
untagged: ghcr.io/azuracast/azuracast:stable
untagged: ghcr.io/azuracast/azuracast@sha256:362457a1467584c5040346f24b821c07f6bf502ac56553c4ccd3bc01491b1f68
deleted: sha256:f2e4d2ad45547157efeba9845f2dfa0594986e35bb17351648a5646a85cc61dd
deleted: sha256:cb5e252d57008c41aaaed56ab4c976b653a73ee6a94fb28014721c120b14932b
deleted: sha256:cc645aea3839c083fa3b3418d5b5aeebda9bd143f1b3359450606e2e8794fb50
deleted: sha256:d6ee89325d95d2a60210f9d7836fdfcb2f594d20bcfbe0d1abd7555df98940e7
deleted: sha256:cd5d1b1aa04b67063e10da1c961c3c4f28a6b4f6234da873d5e3efaad933bc3d
deleted: sha256:8ab74f86e764919b9f36cfe9a0c235c6425329b9e44402ad30874ae35b7a6107
deleted: sha256:142403e349c8547c854c26711861d78c87e051928c9f7f3d6bc9a9aacd45b5fe
deleted: sha256:dc4259285e78c72ae32b502efe71660bb7e5ac178b731712476ba4e6e9c3dfcd
deleted: sha256:fa99c6b35e0f8eb02f1236f2f422bad404125b825a374ead80b5c18c6969fa09
deleted: sha256:406322c931ee0a219f2dcef217d773a9cd31eda76e98f99e93a2d098a167372d
deleted: sha256:f00d02737e722734f5b08a02a9ff0fad1114220c1cead25ed59974ffbe32a9e9
deleted: sha256:30e8df0294257b41d0ecab6da39d8456836019306e99ab769312559c788bdbba
deleted: sha256:ba8df21d7b5d337bff2594c9df3e6f45fec9faf0b8eba287c74aa28226577de5
deleted: sha256:07e4b625ff26f0a755f7133a9df9d3b973ad05a75ba75bdf81308104324bc8cf
deleted: sha256:e3be1225a1958b8482878f2d01d61f1918a4c56a9e6644b377060ce0383b3376
deleted: sha256:ef5685858152b60310340c80e93907508cb7c6459d7587ee4f7c94e59bdc1c5f
deleted: sha256:381183f0d648c142c807be269629867d9f9d5fed252d294414acb20c133d3001
deleted: sha256:3ff824433ccb1da63d207e6f0053c9568e529aee13f21eadbc7a604d922bffd0
deleted: sha256:60c048c960dc0ee0cd2be53b3cab85f89996230236cc57175d54c63ceeed38ea
deleted: sha256:36309df54ecc48731d9c1ac6fbd01488188e46f0f0f20cdbb76cfb71f6ec33d4
deleted: sha256:8a463fc7294ef0ff8110e91cf11e56378b2af6fe1f143d5884092022d3371235
deleted: sha256:76c3e1accff7b05a54a8916dbadb2628e84a2b4cdfad51a6353879dcccda9f81
deleted: sha256:afd8b0c5ce2df2a7f6357bc4c8b712638b1a8ed1a65de5c9a95476cfe6977402
deleted: sha256:a7aa0e29398d75e617c48cb9cb5e0cc6d343824b5dd481d6613697690e9fe4e9
deleted: sha256:a7a3f8908f49843348ebe0dd6f234947b287cd3b2f4dbe4a6b5d5d45c5d7ad77
deleted: sha256:e38112373a829de3c42f1218c69a5cf9ca965c0438a4f49d1f447263d0186d67
deleted: sha256:eb749a667139d8ea14ddf6eb1bcbdf09a90dfa443b8a9f399649f9a8fa187c8a
deleted: sha256:d6ad0c40c3393fde7b27a5410c9168087d5c4a2b6d5dc8a9e5f6e41baf0f2b1a
deleted: sha256:eab62278295a5a09223ad2a92877d9504235f16f13c3ce90828ad65db51391b2
deleted: sha256:878a05a25657f6df384f6e09c3800f2e8c8095fd94b41e05c2d418429b29b0b7
deleted: sha256:009d1b558d4644cf513391255e6e04a19601c716f59bd7bfa6e11778b3fe0ffd
deleted: sha256:fa9c4eee81c755e7684f94396cd34b03b10638ec0b54ed39041419ab8d3bc0bc
deleted: sha256:775c1ff11d82537f0855df6b3693d7ec0278c8ea24aa6205602a8b32b2301c83
deleted: sha256:fc267024837f41aae5e16d79eb0a0d68f3d5d2e7c3ce1f2950f5e13aa4c04d5c
deleted: sha256:b792e87f316a93d5048c18c5666b8a9d04b753f52e6c0a53a4131429d70e9ded
deleted: sha256:c4bf47140a160977c24228d939b3c1208e81e91c90533ba5278e251d487e071e
deleted: sha256:f639e34004666949d9b7223d6c261d1f41c9a2df5ca0c7755207c7e211fae111
deleted: sha256:ceb365432eec83dafc777cac5ee87737b093095035c89dd2eae01970c57b1d15

Total reclaimed space: 1.923GB
root@radio3-redo:/var/azuracast# 


@BusterNeece  ???  please we need help to find a way to stop / avoid this coz we stand to see clients churn :(
it 's a standard vannilla debian server instance only running azurazcast and nothing else. :(

**Comment by keybrdist** [comment]
I see the following backups files are taking up your space. I would try changing your backup storage settings to save them elsewhere, or if you are already doing that, write your own cleanup script to delete these .tgz files.

./overlay2/adad54595512e4d7b56019ea6205b12759434cada7f5dd169bf9ad00c3f602d0/merged/tmp/backup_93697011266022d8a35a157.93738304.tgz
57G ./overlay2/adad54595512e4d7b56019ea6205b12759434cada7f5dd169bf9ad00c3f602d0/diff/tmp/backup_93697011266022d8a35a157.93738304.tgz
54G
