### ISSUE TITLE
Azuracast is suddenly showing message: This server is not the current active instance. This likely means that multiple AzuraCast instances are connecting to the same database. This instance is not the current active one, so synchronized tasks won't run on this server.. Why? 

### ISSUE THREAD

**Issue by marekdziem** [AzuraCast/AzuraCast#6958]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

One of our azuracast server hosts just started showing this message:
This server is not the current active instance.
This likely means that multiple AzuraCast instances are connecting to the same database. This instance is not the current active one, so synchronized tasks won't run on this server. If this is intentional, you can disregard this message

Why would that be the case as its a docker install so database is not accessible outside the docker instance?

Is this anything to be concerned about?

running  v0.19.4 Stable

**Comment by BusterNeece** [comment]
It's nothing to be concerned about; it seems to appear occasionally after updates, and should disappear quite quickly.

**Comment by marekdziem** [comment]
Thanks again!
