### ISSUE TITLE
Scheduled Playlist Does Not Immediately Play First Song When Queue is Not Empty

### ISSUE THREAD

**Issue by alexaungmyooo** [AzuraCast/AzuraCast#6959]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.4 Stable • Docker • PHP 8.2

### What happened?

**Actual Behavior:**
When a scheduled playlist starts, if there is still a song playing or in the queue, the first song of the scheduled playlist does not play immediately. Instead, it gets added to the queue and waits for the current song to finish, which can delay the start of the scheduled content.

**Expected Behavior:**
When a scheduled playlist's time arrives, the first song of the playlist is expected to play immediately, interrupting the current song if necessary, to ensure the schedule is adhered to precisely.

**Steps to Reproduce:**

1. Schedule a playlist to start at a specific time.
2. Ensure a song is playing or in the queue close to the start time of the scheduled playlist.
3. Observe that the scheduled playlist's first song does not play immediately at the scheduled time but is instead added to the queue.

**Additional Context:**
This issue impacts the timing and reliability of scheduled broadcasts, which is critical for users relying on AzuraCast for time-sensitive programming.

**Comment by gAlleb** [comment]
And this doesn't work? o_O
<img width="500" alt="Снимок экрана 2024-02-21 в 14 00 17" src="https://github.com/AzuraCast/AzuraCast/assets/144447266/6dcd8501-e07a-464d-acbc-ae269f225267">

**Comment by alexaungmyooo** [comment]
Enabling the suggested option resolved the issue. Thank you for your assistance!

**Comment by alexaungmyooo** [comment]
I think It is not working even we set Interrupt other songs to play at scheduled time. We have tested two or three time.
