### ISSUE TITLE
How ban one IP?

### ISSUE THREAD

**Issue by multi023** [AzuraCast/AzuraCast#696]
Hi,

I would know how to ban an ip. There is an IP that connects with the same address about 200 times every few seconds, all day and I want to ban it. 

In the admin panel, when I click on "Ban List", nothing appears. Neither in other functions like "Help & Documentation", "Bandwidth Usage", "Reserved List" ... When clicking on any option, it always remains in the "Summary" window.

Any idea how I can solve this?

Thank you very much. Greetings,

**Comment by kenshin869** [comment]
The problem is that on the servers that use the web proxy, the list of shoutcast server locks does not appear, nor does any other option work.

You should not redirect the nginx rule correctly after the server port in the shoutcast admin panel, since it is not a canonical URL and is "normal", for example, https://myserver.com/radio/8020/**admin.cgi?mode=viewban** It doesn't work

**Comment by Likeandfeel** [comment]
Hi multi023

You can try some of theses options and adapt of your use
This code must include inside .htaccess file in the root of your radio by default is there >> /var/azuracast/www

Link i send  you, give you some informations that you must adapt for your personal use.
Let me know if you fix your problem with this

Bests regards 


<ifModule mod_geoip.c>
GeoIPEnable On
# Add countries you wish to deny here
SetEnvIf GEOIP_COUNTRY_CODE CO DenyCountry
SetEnvIf GEOIP_COUNTRY_CODE EG DenyCountry
SetEnvIf GEOIP_COUNTRY_CODE HI DenyCountry
Allow from all
Deny from env=DenyCountry
</ifModule>


https://help.crucial.com.au/hc/en-gb/articles/115005014487--Block-IP-Addresses-and-Countries-using-htaccess

Ip Block generator
https://www.ip2location.com/blockvisitorsbycountry.aspx#form
http://blogmotion.fr/systeme/bloquer-acces-site-pays-5387

**Comment by SlvrEagle23** [comment]
@Likeandfeel These will not work, as AzuraCast is hosted by nginx and does not use .htaccess files by default.

**Comment by Likeandfeel** [comment]
Hi @SlvrEagle23 

Ok and something like this ? 

Edit nginx.conf file, enter (note my nginx path is set to /usr/local/nginx/, replace this according to your setup): 

# cd /usr/local/nginx/conf/  << regarding path of your nginx conf
# vi nginx.conf

Add the following line in http section:
## Block spammers and other unwanted visitors  ##
 include blockips.conf;

Save and close the file. Finally, create blockips.conf in /usr/local/nginx/conf/, enter:
# vi blockips.conf

Append / add entries as follows:
deny 1.2.3.4; 
deny 91.212.45.0/24; 
deny 91.212.65.0/24;
--

Save and close the file. Test the config file, enter:
# /usr/local/nginx/sbin/nginx -t

Reload the new config, enter:
# /usr/local/nginx/sbin/nginx -s reload

Let me know :p

**Comment by Likeandfeel** [comment]
### Hi @SlvrEagle23 

Ok and something like this ? 

Edit nginx.conf file, enter (note my nginx path is set to /usr/local/nginx/, replace this according to your setup): 

# cd /usr/local/nginx/conf/  << regarding path of your nginx conf
# vi nginx.conf

Add the following line in http section:
## Block spammers and other unwanted visitors  ##
 include blockips.conf;

Save and close the file. Finally, create blockips.conf in /usr/local/nginx/conf/, enter:
# vi blockips.conf

Append / add entries as follows:
deny 1.2.3.4; 
deny 91.212.45.0/24; 
deny 91.212.65.0/24;
--

Save and close the file. Test the config file, enter:
# /usr/local/nginx/sbin/nginx -t

Reload the new config, enter:
# /usr/local/nginx/sbin/nginx -s reload

Let me know :p

**Comment by allymitton** [comment]
This is just what I'm looking for! Any advice on how to do this when using Docker?
