### ISSUE TITLE
Azuracast cuts 2-3 seconds from the jingle.

### ISSUE THREAD

**Issue by chrissarvanis** [AzuraCast/AzuraCast#6965]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

AzuraCast 0.19.5

### What happened?

After the last update, Azuracast cuts any jingle that plays. Does anyone else have the same problem?"

**Comment by zcraber** [comment]
Experiencing the same with the latest updates. 
Seeing this in the Liquidsoap log, is it somehow related to the issue?

`[mp3float @ 0x7fd95441c800] Could not update timestamps for discarded samples.`
