### ISSUE TITLE
Custom Fallback File Not Working for HLS Streaming

### ISSUE THREAD

**Issue by alexaungmyooo** [AzuraCast/AzuraCast#6967]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.5 Stable • Docker • PHP 8.3

### What happened?

**Issue Description:**
I've encountered an issue where the Custom Fallback File functionality does not operate as expected when streaming over HLS. While the feature works flawlessly for MP3 streaming, it fails to trigger the fallback file for HLS streams. This inconsistency suggests a potential bug in the HLS streaming implementation.

**Expected Behavior:**
The Custom Fallback File should be played when the primary stream is unavailable, regardless of the streaming format (MP3 or HLS). Users rely on this feature to maintain a seamless listening experience, and its malfunctioning for HLS streams disrupts this continuity.

**Steps to Reproduce:**

Set up an AzuraCast station with both MP3 and HLS streaming enabled.
Configure a Custom Fallback File from the station's profile settings.
Simulate a scenario where the primary stream goes offline or is otherwise unavailable.
Observe the behavior of the fallback functionality for both MP3 and HLS streams.

**Additional Information:**

This issue has been verified across multiple setups to ensure it's not an isolated case.
The HLS stream itself functions correctly under normal conditions; the problem only arises when attempting to use the Custom Fallback File feature.
I've checked the troubleshooting guide, known issues, and the current list of GitHub issues but did not find a similar report. I appreciate your attention to this matter and look forward to any guidance or updates you can provide. Thank you for your continuous efforts in improving AzuraCast.

**Comment by Vaalyn** [comment]
The fallback file feature is implemented in Liquidsoap by replacing the default "AzuraCast is live" mp3 jingle with the provided file and if I remember correctly in IceCast additionally via the `<fallback-mount>` setting in case Liquidsoap is down.

Since HLS is done by serving the HLS playlist that Liquidsoap generates & the respective segment files via NGINX there is no equivalent "fallback" feature available there. I think ShoutCast also doesn't have this feature.

**Comment by gAlleb** [comment]
That is true:)

```
    <mount type="normal">
        <mount-name>/radio.mp3</mount-name>
        <charset>UTF8</charset>
        <stream-name>Radio</stream-name>
        <listenurl>https://radio/listen/radio/radio.mp3</listenurl>
        <stream-description>radio</stream-description>
        <stream-url>https://radio/public/radio</stream-url>
        <fallback-mount>/fallback-[128].mp3</fallback-mount>
        <fallback-override>1</fallback-override>
    </mount>
```

```
radio = fallback(id="safe_fallback", track_sensitive = false, [radio, error_file])
```

@alexaungmyooo, HLS can't play error file if Liiquidsoap is down. It just how things work.

**Comment by alexaungmyooo** [comment]
Ok, understand now and will closed.
