### ISSUE TITLE
AzuraCast doesn't show the real IP of listeners

### ISSUE THREAD

**Issue by Rescor** [AzuraCast/AzuraCast#6975]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #ca425d3 

### What happened?

I installed AzureCast from caprover from the official image.
My problem is that the IP addresses of all the listeners are shown as 10.0.0.2 in station statistic, not their real addresses.
Please could you help me with this problem?
![image](https://github.com/AzuraCast/AzuraCast/assets/5821403/5bc09c72-7751-47b9-b04b-741293987c36)

**Comment by Sella-3DX** [comment]
Have you disabled the Docker Userland Proxy?
https://www.azuracast.com/docs/help/optimizing/

**Comment by gAlleb** [comment]
<img width="857" alt="Снимок экрана 2024-02-28 в 21 19 28" src="https://github.com/AzuraCast/AzuraCast/assets/144447266/433a77f1-87ad-4413-8ffe-a832a13ed3ea">

**Comment by Rescor** [comment]
> <img alt="Снимок экрана 2024-02-28 в 21 19 28" width="857" src="https://private-user-images.githubusercontent.com/144447266/308668704-433a77f1-87ad-4413-8ffe-a832a13ed3ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDc1MDEsIm5iZiI6MTcwOTE0NzIwMSwicGF0aCI6Ii8xNDQ0NDcyNjYvMzA4NjY4NzA0LTQzM2E3N2YxLTg3YWQtNDQxMy04ZmZlLWE4MzJhMTNlZDNlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQxOTA2NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDA2MWVlYTE5MDk1OGZiMTgyYmY3ZjkwNTQwNjA1ZDYzMGI1ZWNjNzk3OGQwNmZlMjAwYWQwYWE1YWYyMmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O4J3xgM9dn1skiYN7hpJ80GdWPL2ILfnRpixJy3R7bU">

Thank you!
