### ISSUE TITLE
Playlist Scheduling Creates Duplicate Entries Across Date Change

### ISSUE THREAD

**Issue by alexaungmyooo** [AzuraCast/AzuraCast#6986]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.5 Stable • Docker • PHP 8.3

### What happened?

**Description of the Issue:**

When creating a scheduled playlist intended to span overnight from 10:00 PM to 06:00 AM, starting on March 3, 2024, and ending on March 4, 2024, AzuraCast creates two separate scheduled instances instead of one continuous schedule. The expected behavior is to have a single playlist scheduled from 10:00 PM (March 3, 2024) to 06:00 AM (March 4, 2024). However, the system schedules it as follows:

1. Playlist tt - 10:00 PM, Mar 3, 2024, to 6:30 AM, Mar 4, 2024
2. Playlist tt - 10:00 PM, Mar 4, 2024, to 6:00 AM, Mar 5, 2024

This duplication suggests an issue with how AzuraCast handles overnight playlist scheduling, particularly around date changes.

**Expected Behavior:**

A single scheduled playlist from 10:00 PM to 06:00 AM spanning from the start date to the end date without creating additional, unintended schedules.

Steps to Reproduce:

1. Navigate to the playlist scheduling interface in AzuraCast.
2. Create a new scheduled playlist with the following parameters:
      Start Time: 10:00 PM
      End Time: 06:00 AM
      Start Date: 03/03/2024
      End Date: 03/04/2024
3. Save the scheduled playlist.
4. Observe the created schedules in the playlist overview.

### Relevant log output
[2024-03-03T17:36:40.984372+00:00] AzuraCast.NOTICE: Webhook "Google Analytics " has run less than 10 seconds ago; skipping... [] []
[2024-03-03T17:36:45.739790+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":3,"name":"Testing"}}
[2024-03-03T17:36:45.792867+00:00] AzuraCast.ERROR: No track to update. {"exception":"[object] (RuntimeException(code: 0): No track to update. at /var/azuracast/www/src/Entity/Repository/SongHistoryRepository.php:79)"} {"station":{"id":3,"name":"Testing"}}
[2024-03-03T17:36:54.093184+00:00] AzuraCast.ERROR: No valid playlists detected. Skipping AutoDJ calculations. [] {"station":{"id":3,"name":"Testing"}}
[2024-03-03T17:36:54.139160+00:00] AzuraCast.ERROR: No track to update. {"exception":"[object] (RuntimeException(code: 0): No track to update. at /var/azuracast/www/src/Entity/Repository/SongHistoryRepository.php:79)"} {"station":{"id":3,"name":"Testing"}}
_No response_

**Comment by alexaungmyooo** [comment]
![Screenshot 2024-03-03 at 9 33 48 PM](https://github.com/AzuraCast/AzuraCast/assets/152832891/d40b348d-3451-4333-ac2b-fc6a015070e1)
![Screenshot 2024-03-03 at 9 33 32 PM](https://github.com/AzuraCast/AzuraCast/assets/152832891/27d127f0-e7a6-4723-8b08-972b85b5c858)

**Comment by alexaungmyooo** [comment]
We are currently facing an issue that prevents us from moving our station into production. It seems that version 0.19.4 Stable is functioning correctly, but we're unsure how to revert to this previous version. Is there a workaround, or can any developer suggest a solution to overcome this problem? We would greatly appreciate guidance from the AzuraCast team on how to proceed or an estimated timeline for a fix. We understand that the team is busy, but we're hopeful for any assistance or advice. Thank you in advance!

**Comment by BusterNeece** [comment]
> We would greatly appreciate guidance from the AzuraCast team on how to proceed or an estimated timeline for a fix. 

As a rule, we do not offer estimated timelines for any support provided here. Support is provided on an as-available basis by volunteers supported by community donations.

I'm aware of this bug, though I'm not certain what would be causing it or why it would've been introduced in 0.19.5 specifically. I'll look into it as soon as possible.

**Comment by BusterNeece** [comment]
@alexaungmyooo I have confirmed this bug locally and found the source of the issue. Now, if you have an overnight schedule item that also has a specified end date, then this means that the schedule item will *end* on that date, but won't *start* on that date (going into the next day) as well. This matches the expectation that a schedule item going from "10pm on March 15" to "4am on March 16" would only play *once* in the time period starting on the evening of the 15th and going until the morning of the 16th.
