### ISSUE TITLE
Unable to download current Stereo Tool configuration

### ISSUE THREAD

**Issue by sb-200** [AzuraCast/AzuraCast#6987]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #466f036

### What happened?

Hi,

I am currently getting the below error when trying to download the current Stereo Tool config I have loaded on my install:

Unable to retrieve the mime_type for file at location: stereo-tool.sts.
vendor/league/flysystem/src/UnableToRetrieveMetadata.php : L49

Loaded a nice Stereo Tool preset but can't remember which one it was, so I would love to be able to download whats currently loaded again :)

**Comment by BusterNeece** [comment]
I'm not able to reproduce this on my local development environment. When I go to download an existing StereoTool configuration, it works without any issue. I'm not sure specifically what's causing this problem, but without being able to reproduce it locally, it's difficult for me to make any progress on fixing it.
