### ISSUE TITLE
Playlist shedule Error 500

### ISSUE THREAD

**Issue by Siriusa77II** [AzuraCast/AzuraCast#699]
**Installation method**
Docker

**Host OS (for Docker installations)**
Debian 9
**Describe the bug**
Error 500 after create shedule playlist.

**To Reproduce**
Upload Playlist songs
go to playlist
Set the playlist as Shedule for Sunday & Saturday from 09:00PM to 12PM

**Expected behavior**
I try to create Week end nightly playlist but I probablly should create 2 playlist for these two days.

**Screenshots**
![image](https://user-images.githubusercontent.com/16348488/43687848-6d869836-98dd-11e8-9504-cb1fad2ef90c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro [Insider Build] && Windows Server 2016
 - Browser Chrome
 - Version  Chrome 68 on Windows 10 &&  Firefox 57 on Windows Server

**Additional context**
Now i dont know how to fix the 500 and get access back to my playlists.

**Comment by SlvrEagle23** [comment]
@Siriusa77II Should be fixed now. Sorry about that!

**Comment by Siriusa77II** [comment]
Perfect Thanks :)
