### ISSUE TITLE
Previous Songs Played.

### ISSUE THREAD

**Issue by NeddyPlays** [AzuraCast/AzuraCast#700]
Hi,

I am thinking. Is it possible to get a previous songs played list for the last like 2 hours for the DJ's?
The Public one only shows 5 songs.

Thanks!

**Comment by SlvrEagle23** [comment]
@NeddyPlays The station playback timeline (one of the available reports on the station) will show a much longer history of song playback, including allowing you to download that report as a CSV.

**Comment by NeddyPlays** [comment]
I know i can download a report. But i also need this for the DJ's too see and be live information.

I can't give all of them access to the panel.

**Comment by SlvrEagle23** [comment]
@NeddyPlays This is now customizable in the station profile. You can set how many song history items show, from zero (disabled entirely) up to 15 items. More than that would create a very large API response and could degrade the performance of the system.
