### ISSUE TITLE
Feature request: Play A Jingle in the 5 second buffer for the DJ

### ISSUE THREAD

**Issue by NeddyPlays** [AzuraCast/AzuraCast#701]
Hi,

Another thing where iam thinking of.
Is it possible to play a Jingle in the 5 second buffer when a DJ connects. Now you get a 5 second silence, that 5 seconds is perfect to play a Jingle in :)

Or 10 seconds of course if you use 10 second buffer.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39022/play-a-jingle-in-the-buffer-while-a-dj-connects
