### ISSUE TITLE
Podcast public all-episodes page does not display page background image correctly

### ISSUE THREAD

**Issue by batsonjay** [AzuraCast/AzuraCast#7010]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #76fc4e8

### What happened?

On /public/x/podcast/(all-episodes-page) the page uses the file specified as the "Public Page Background".

This image is shown "actual size", and is not scaled to the width of the browser in which it is displayed. (It should be).

This *might* apply to other public pages; I haven't checked.

**Comment by BusterNeece** [comment]
@batsonjay This may be a Safari-ism...I can't confirm it on my browsers personally. Can you check to see if the same effect happens on other browsers on your machine?

**Comment by batsonjay** [comment]
I wish to amend this report.

The image stretches fine; the issue arises when narrowing the window and both X & Y dimensions are shrinking. When both X & Y shrink simultaneously, the image stays centered, and shrinks to fit the window (roughly).

In contrast:
- When narrowing the window with only X (width) change, the image stays anchored to the left, and the right of the image disappears off the right of the page. My expectation is that it would stay centered and shrink given the behavior of what happens when both dimensions are changing.
- When shortening the window with only Y (height) change, the bottom of the image disappears off the bottom of the page. my expectation is that it would stay centered and shrink. My expectation is that it would stay centered and shrink given the behavior of what happens when both dimensions are changing.

I've recorded my screen to demonstrate the above, first showing simultaneous X/Y reduction, then X-only, then Y-only, then repeat the start. [Screencast here](https://www.dropbox.com/scl/fi/2kssy43c1zg9ia2kr486b/AzC-podcast-bg-resize.mov?rlkey=o9g0epsidkymlowx418vjbjxq&dl=0).

Is this because the anchoring CSS properties aren't set to match my expectations? Or am I simply misunderstanding what CSS image handling can / does do?

**Comment by BusterNeece** [comment]
@batsonjay I think it's a little of both. We previously anchored background images to the top left (the default anchoring position), so as images resized, they'd cut off the bottom and right sides accordingly.

After playing with it a little, I think that for most scenarios, this _isn't_ what people are thinking will be the default, and it actually doesn't even work the best with our default graphic. I think it would be better to anchor from `center center` so the image spreads out evenly from the center, and that would also match user expectations likely more cleanly.

As a note for anyone who customizes the login screen and doesn't like the new position anchoring, you can always override this in Custom Branding (either per-station or global) with the following CSS:

```css
[data-bs-theme] body.page-minimal {
  background-position: top left;
}
```
