### ISSUE TITLE
API Streamers/DJs Issue (Schedules deleted because updating)

### ISSUE THREAD

**Issue by rmueck** [AzuraCast/AzuraCast#7014]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

• v0.19.5 Stable 

### What happened?

I want to update two fields for an existing DJ `display_name` and `streamer_password` only without touching/modify other fields/arrays like `schedule_items` .

So my JSON file looks like:
~~~json
{
  "id": 6,
  "streamer_username": "mydj",
  "streamer_password": "$ecretpw",
  "display_name": "DJ One"
 }
~~~

So when i am firing up:

~~~sh
http  PUT https://localhost:9999/api/station/1/streamer/6  X-API-Key:45fccb60ad85c6539cbcb  < upd.json
~~~
Result:
~~~
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json
Date: Mon, 18 Mar 2024 10:55:12 GMT
Permissions-Policy: autoplay=*, fullscreen=*, interest-cohort=()
Referrer-Policy: no-referrer-when-downgrade
Server: nginx
Strict-Transport-Security: max-age=3600
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Robots-Tag: noindex, nofollow
X-XSS-Protection: 1

{
    "formatted_message": "Record updated successfully.",
    "message": "Record updated successfully.",
    "success": true
}
~~~
**The fields got updated correctly, BUT all existing schedules are gone!**

### Relevant log output

```shell
NA
```

**Comment by rmueck** [comment]
Any actual investigations?

**Comment by BusterNeece** [comment]
@rmueck Sorry for the delay. This is indeed a valid issue and should be fixed now in the latest Rolling Release.
