### ISSUE TITLE
Even as I deleted all music files, it shows as if memory is full at 100%, thus not allowing to update music programming 

### ISSUE THREAD

**Issue by Panamax865** [AzuraCast/AzuraCast#7016]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Even as I deleted all music files, it shows as if memory is full at 100%, thus not allowing to update music programming

**Comment by SpeedyCharly** [comment]
Seems you're confusing storage space with Random Access Memory; the amount of files stored on the sever has no effect on the operating memory used by Azuracast.
