### ISSUE TITLE
Listener authentication with OAuth

### ISSUE THREAD

**Issue by xewl** [AzuraCast/AzuraCast#702]
**Is your feature request related to a problem? Please describe.**
This package's AutoDJ feature is only able to feed itself via _public_ Requests.

**Describe the solution you'd like**
Authentication -therefore maybe only temporarily- with an(y) OAuth service for Listeners and/or Requests, as an extra wall between the ability to request songs and possibly also know the user's public name for other purposes. You would only request a basic connection from the OAuth-service with minimal data-sharing: maybe even just the token when possible or when set-up like that.

**Describe alternatives you've considered**
Full accounts, with a "User"-role. But GDPR and a-like wouldn't like that, neither would these users benefit from this, directly. This way, with OAuth, you minimize the privacy constraints. But I don't count it out as a possibility.

**Additional context**
An extra, but welcome, addition to the request system and the setting for the timeouts in between requests, possibly serving as an extra way to limit per user.

**Comment by SlvrEagle23** [comment]
@xewl We don't currently have plans to implement OAuth into AzuraCast for reasons of technical complexity that aren't easily solved in self-hosted installation cases.

However, as an alternative to only having authenticated requests, we have an existing feature request to allow station operators to manually specify the next song, which will fulfill much of the same purpose (and use the same underlying code) as authenticated requests would:
https://azuracast.featureupvote.com/suggestions/38778/add-ability-to-manipulate-the-nextplaying-song-or-specify-a-song-to-play-next-by
