### ISSUE TITLE
No audio comes out in iOS devices

### ISSUE THREAD

**Issue by rodmark** [AzuraCast/AzuraCast#7026]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #6632b51 (2024-03-22 17:54) • Docker • PHP 8.3

### What happened?

When trying to play music on mobile devices, no sound comes out. Play appears to work but there is no sound. I've already tried with SSL, without SSL, and with cloudflare and it didn't work. What will be the problem? Is a fresh installtion on Ubunto 22.04. Thank you in advance.

**Comment by keybrdist** [comment]
Can you provide a URL to your stream?

**Comment by rodmark** [comment]
> Can you provide a URL to your stream?

Yes, https://cast.kooy.io/public/demo

**Comment by keybrdist** [comment]
Seems to work fine. Tested ok on Google Pixel and on IPhone SE 2nd Gen.
