### ISSUE TITLE
Typo in Docs

### ISSUE THREAD

**Issue by mdrxy** [AzuraCast/AzuraCast#7027]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

["users around the world or accept **_al arge_** volume of incoming traffic"](https://www.azuracast.com/docs/administration/azurarelay/#_top)

Under AzuraRelay header, 2nd sentence.

Should be "a large"

**Comment by thackmaster** [comment]
Opened a pull request to resolve the issue

**Comment by BusterNeece** [comment]
Thank you @mdrxy and @thackmaster!
