### ISSUE TITLE
[feature] Improve UX of Move Files folder list popup

### ISSUE THREAD

**Issue by rogercreagh** [AzuraCast/AzuraCast#7031]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #2ce2b09 (2024-03-26 18:25) • Docker • PHP 8.3

### What happened?

When you are moving music files the list of destination folders in the popup pane is not sorted. If you add new folders they simply get added at the end of the list - or if other folders have been deleted they may appear in the middle of the list. 

If you have a large list of folders this makes it very difficult to find your desired destination.

Expected minimum behaviour is that the list should be sorted alphabetically every time you open it

Desirable additional behaviours:
 - a facility to reverse the sort whilst the popup remains open
 - a facility to start to type a folder name and have the list scroll automatically to the first match as you type

Using SFTP it is cumbersome to move stuff between folders, the internal Azuracast move facility is very good apart from this annoying quirk. I regard this as a bug rather than a feature request as the desired behaviour is what one would naturally expect.

**Comment by rogercreagh** [comment]
How strange - I just checked again and now it works. Shame I didn't take a screen shot last time. Can't explain it at all.

The other two bullet point stands as feature requests, as if you have 100+ folders the current dialogue can require a lot of scrolling. To slightly expand the desired options:

- on the media page when the move dialogue is open either provide a button to reverse the order of the list (so that if you are looking for a folder name starting with W you don't have to scroll right through the list)
- or enable keyboard input on the move dialogue so that you could start typing an destination name and it would jump down to the relevant point in the list
- or/and remember the previous destination from last time move was invoked and start from that positon in the list.
- or/and remember the most recent 3 folders created and repeat them at the top of this list on the basis that if you are reorganising files into a new folder most likely it is one you just created.

Start with whichever of these is easiest to implement...

**Comment by BusterNeece** [comment]
@rogercreagh The "Move Files" popup dialog is now paginated, sortable and searchable like most data tables in the application. Hopefully this helps with large sets of directories.

**Comment by rogercreagh** [comment]
Brilliant, I'll try it asap (or more accurately dreckly I've rebuilt my test server). Many thanks @BusterNeece
