### ISSUE TITLE
Sweepers Sometimes Play Twice or 1.5 Times!

### ISSUE THREAD

**Issue by wppronto** [AzuraCast/AzuraCast#7035]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #ca425d3

### What happened?

I have four sweeper playlists (sharing the same files)...one set to play each hour at 00, and other at 15, another 30 and another 45. Each playlist is set to only play one song at the specified time.

Sometimes two sweepers will play back-to-back, which of course is undesirable and shouldn't happen with the settings I'm using. Occasionally they will play 1.5 times...a complete sweeper followed by half of it again, then fading out.

I don't see anything in the logs that seem to be related to this issue.

**Comment by wppronto** [comment]
It just happened again: Two sweepers ini a row, with the second one fading out awkwardly. Below is the log data from around that time. Note that "My Sharona" is shown in this data, but it never played.

`2024/03/29 10:56:03 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/the_river/media/10cc_-_im_not_in_love_(clean).mp3": {audio=pcm(stereo)}
2024/03/29 10:56:03 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/the_river/media/10cc_-_im_not_in_love_(clean).mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}, video: {codec: mjpeg, 600x600, yuvj420p}
2024/03/29 10:56:03 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/the_river/media/10cc_-_im_not_in_love_(clean).mp3": {audio=pcm(stereo)}
[mp3 @ 0x7fccf2252500] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7fccf2252500] Estimating duration from bitrate, this may be inaccurate
2024/03/29 10:56:03 [request.once.1056:3] Prepared "/var/azuracast/stations/the_river/media/10cc_-_im_not_in_love_(clean).mp3" (RID 2241).
2024/03/29 10:56:08 [autodj_fallback:3] Switch to switch.4 with forgetful transition.
2024/03/29 10:56:08 [replay_metadata.3100:3] Content type is {audio=pcm(stereo)}.
[aac @ 0x7fcd15a33c00] Could not update timestamps for skipped samples.
2024/03/29 10:56:08 [cross:3] Analysis: -103.013117dB / -3.600144dB (0.14s / 0.14s)
2024/03/29 10:56:08 [cross:3] Computing crossfade duration over overlapping 0.14s buffered data at start and end.
2024/03/29 10:56:08 [source.3461:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [audio.add.1151:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/the_river/media/sweeper_2_replaygain_91.m4a": {audio=pcm(stereo)}
2024/03/29 10:56:08 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/the_river/media/sweeper_2_replaygain_91.m4a" as audio: {codec: aac, 44100Hz, 2 channel(s)}
2024/03/29 10:56:08 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/the_river/media/sweeper_2_replaygain_91.m4a": {audio=pcm(stereo)}
2024/03/29 10:56:08 [fade_in.1151:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [fade_scale.1151:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [track_amplify.2304:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [blank.1152:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [on_metadata.2302:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [on_track.2304:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [cross_after.1153:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [buffer.3014:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [fade_out.1151:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [track_amplify.2303:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [on_frame.2302:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [on_metadata.2301:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [on_track.2303:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [cross_before.1153:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [buffer.3013:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [file.replaygain.1057:3] Computing replay gain for "/var/azuracast/stations/the_river/media/sweeper_2_replaygain_91.m4a"
2024/03/29 10:56:08 [dummy.1057:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [source.replaygain.compute.1057:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [request.once.1057:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:08 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/the_river/media/sweeper_2_replaygain_91.m4a": {audio=pcm(stereo)}
2024/03/29 10:56:08 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/the_river/media/sweeper_2_replaygain_91.m4a" as audio: {codec: aac, 44100Hz, 2 channel(s)}
2024/03/29 10:56:08 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/the_river/media/sweeper_2_replaygain_91.m4a": {audio=pcm(stereo)}
2024/03/29 10:56:08 [request.once.1057:3] Prepared "/var/azuracast/stations/the_river/media/sweeper_2_replaygain_91.m4a" (RID 2243).
[aac @ 0x7fccf0c2b400] Could not update timestamps for skipped samples.
2024/03/29 10:56:08 [relay_1:2] Metadata update may have failed with error: 401, Authentication Required (HTTP/1.0)
2024/03/29 10:56:09 [decoder:2] Decoding "/var/azuracast/stations/the_river/media/sweeper_2_replaygain_91.m4a" ended: Ffmpeg_decoder.End_of_file.
2024/03/29 10:56:09 [dummy.1057:3] Source failed (no more tracks) stopping output...
2024/03/29 10:56:09 [file.replaygain.1057:3] Computed replay gain -8.32 dB for "/var/azuracast/stations/the_river/media/sweeper_2_replaygain_91.m4a" (time: 0.595907926559 s).
2024/03/29 10:56:09 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
2024/03/29 10:56:09 [lang:3]   "song_id": "0d0bdbb2e6dab9d37e34593b689cf2ff",
2024/03/29 10:56:09 [lang:3]   "playlist_id": "47",
2024/03/29 10:56:09 [lang:3]   "media_id": "462"
2024/03/29 10:56:09 [lang:3] }
2024/03/29 10:56:09 [lang:3] API feedback - Response (200): true
2024/03/29 10:56:13 [decoder:2] Decoding "/var/azuracast/stations/the_river/media/sweeper_2_replaygain_91.m4a" ended: Ffmpeg_decoder.End_of_file.
2024/03/29 10:56:13 [request.2203:3] End of track reached before cue-out point!
2024/03/29 10:56:13 [playlist_sweepers_replaygain:3] Prepared "/var/azuracast/stations/the_river/media/sweeper_2_replaygain_91.m4a" (RID 2242).
2024/03/29 10:56:13 [switch.3:3] Switch to standard_playlists with forgetful transition.
2024/03/29 10:56:13 [replay_metadata.3103:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/the_river/media/knack_-_my_sharona.mp3": {audio=pcm(stereo)}
2024/03/29 10:56:14 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/the_river/media/knack_-_my_sharona.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2024/03/29 10:56:14 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/the_river/media/knack_-_my_sharona.mp3": {audio=pcm(stereo)}
2024/03/29 10:56:14 [file.replaygain.1058:3] Computing replay gain for "/var/azuracast/stations/the_river/media/knack_-_my_sharona.mp3"
2024/03/29 10:56:14 [dummy.1058:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [source.replaygain.compute.1058:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [request.once.1058:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/the_river/media/knack_-_my_sharona.mp3": {audio=pcm(stereo)}
2024/03/29 10:56:14 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/the_river/media/knack_-_my_sharona.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2024/03/29 10:56:14 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/the_river/media/knack_-_my_sharona.mp3": {audio=pcm(stereo)}
2024/03/29 10:56:14 [request.once.1058:3] Prepared "/var/azuracast/stations/the_river/media/knack_-_my_sharona.mp3" (RID 2245).
[mp3float @ 0x7fccf0c2b400] Could not update timestamps for skipped samples.
2024/03/29 10:56:14 [cross:3] Analysis: -8.530131dB / -26.762650dB (1.70s / 1.70s)
2024/03/29 10:56:14 [cross:3] Computing crossfade duration over overlapping 1.70s buffered data at start and end.
2024/03/29 10:56:14 [source.3464:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [audio.add.1152:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [fade_in.1152:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [fade_scale.1152:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [track_amplify.2306:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [blank.1153:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [on_metadata.2304:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [on_track.2306:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [cross_after.1154:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [buffer.3017:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [fade_out.1152:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [track_amplify.2305:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [on_frame.2304:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [on_metadata.2303:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [on_track.2305:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [cross_before.1154:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [buffer.3015:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [cross_after_tail.684:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:56:14 [relay_1:2] Metadata update may have failed with error: 401, Authentication Required (HTTP/1.0)
2024/03/29 10:56:19 [decoder:2] Decoding "/var/azuracast/stations/the_river/media/10cc_-_im_not_in_love_(clean).mp3" ended: Ffmpeg_decoder.End_of_file.
2024/03/29 10:56:19 [dummy.1056:3] Source failed (no more tracks) stopping output...
2024/03/29 10:56:19 [file.replaygain.1056:3] Computed replay gain -5.53 dB for "/var/azuracast/stations/the_river/media/10cc_-_im_not_in_love_(clean).mp3" (time: 16.3900279999 s).
2024/03/29 10:56:19 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
2024/03/29 10:56:19 [lang:3]   "song_id": "6a38124180dae29dae9a6724b32ab70c",
2024/03/29 10:56:19 [lang:3]   "playlist_id": "45",
2024/03/29 10:56:19 [lang:3]   "media_id": "173"
2024/03/29 10:56:19 [lang:3] }
2024/03/29 10:56:19 [lang:3] API feedback - Response (200): true
[mp3float @ 0x7fccf0c2b400] Could not update timestamps for discarded samples.
2024/03/29 10:56:24 [decoder:2] Decoding "/var/azuracast/stations/the_river/media/knack_-_my_sharona.mp3" ended: Ffmpeg_decoder.End_of_file.
2024/03/29 10:56:24 [dummy.1058:3] Source failed (no more tracks) stopping output...
2024/03/29 10:56:24 [file.replaygain.1058:3] Computed replay gain -2.2 dB for "/var/azuracast/stations/the_river/media/knack_-_my_sharona.mp3" (time: 10.7877850533 s).
2024/03/29 10:58:58 [decoder:2] Decoding "/var/azuracast/stations/the_river/media/jimmy_buffett_-_cheeseburger_in_paradise_(clean).mp3" ended: Ffmpeg_decoder.End_of_file.
2024/03/29 10:58:58 [playlist_1970s:3] Prepared "/var/azuracast/stations/the_river/media/knack_-_my_sharona.mp3" (RID 2244).
2024/03/29 10:58:58 [switch:3] Switch to playlist_1990s with forgetful transition.
2024/03/29 10:58:58 [replay_metadata.3106:3] Content type is {audio=pcm(stereo)}.
[mp3 @ 0x7fcd15abe700] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7fcd15abe700] Estimating duration from bitrate, this may be inaccurate
2024/03/29 10:58:58 [next_song:3] Prepared "/var/azuracast/stations/the_river/media/10cc_-_im_not_in_love_(clean).mp3" (RID 2240).
2024/03/29 10:58:58 [autodj_fallback:3] Switch to dynamic_startup with forgetful transition.
2024/03/29 10:58:58 [replay_metadata.3107:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [dynamic_startup:3] Switch to next_song.
2024/03/29 10:58:58 [replay_metadata.3108:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2024/03/29 10:58:58 [lang:3] API nextsong - Response (200): annotate:title="Material Girl (Radio Edit)",artist="Madonna",duration="240.35",song_id="511a6a2f358df47d6e3e31550a7990d0",media_id="47",liq_fade_in="0.00",playlist_id="46":media:202_material_girl_(radio_edit).mp3
[mp3 @ 0x7fccf2252500] Estimating duration from bitrate, this may be inaccurate
2024/03/29 10:58:58 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/the_river/media/202_material_girl_(radio_edit).mp3": {audio=pcm(stereo)}
2024/03/29 10:58:58 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/the_river/media/202_material_girl_(radio_edit).mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}, video: {codec: mjpeg, 900x900, yuvj420p}
2024/03/29 10:58:58 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/the_river/media/202_material_girl_(radio_edit).mp3": {audio=pcm(stereo)}
[mp3 @ 0x7fccf2252500] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7fccf2252500] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7fccf2252500] Estimating duration from bitrate, this may be inaccurate
2024/03/29 10:58:58 [file.replaygain.1059:3] Computing replay gain for "/var/azuracast/stations/the_river/media/202_material_girl_(radio_edit).mp3"
2024/03/29 10:58:58 [dummy.1059:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [source.replaygain.compute.1059:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [request.once.1059:3] Content type is {audio=pcm(stereo)}.
[mp3 @ 0x7fccf2252500] Estimating duration from bitrate, this may be inaccurate
2024/03/29 10:58:58 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/the_river/media/202_material_girl_(radio_edit).mp3": {audio=pcm(stereo)}
2024/03/29 10:58:58 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/the_river/media/202_material_girl_(radio_edit).mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}, video: {codec: mjpeg, 900x900, yuvj420p}
2024/03/29 10:58:58 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/the_river/media/202_material_girl_(radio_edit).mp3": {audio=pcm(stereo)}
2024/03/29 10:58:58 [cross:3] Analysis: -64.065606dB / -27.883634dB (5.99s / 6.01s)
2024/03/29 10:58:58 [cross:3] Computing crossfade duration over overlapping 5.99s buffered data at start and end.
2024/03/29 10:58:58 [source.3467:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [audio.add.1153:3] Content type is {audio=pcm(stereo)}.
[mp3 @ 0x7fccf2252500] Estimating duration from bitrate, this may be inaccurate
2024/03/29 10:58:58 [fade_in.1153:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [fade_scale.1153:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [track_amplify.2308:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [blank.1154:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [on_metadata.2306:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [on_track.2308:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [cross_after.1155:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [buffer.3020:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [fade_out.1153:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [track_amplify.2307:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [on_frame.2306:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [on_metadata.2305:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [on_track.2307:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [cross_before.1155:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [buffer.3018:3] Content type is {audio=pcm(stereo)}.
2024/03/29 10:58:58 [cross_after_tail.685:3] Content type is {audio=pcm(stereo)}.
[mp3 @ 0x7fccf2252500] Estimating duration from bitrate, this may be inaccurate
2024/03/29 10:58:58 [request.once.1059:3] Prepared "/var/azuracast/stations/the_river/media/202_material_girl_(radio_edit).mp3" (RID 2247).
2024/03/29 10:58:58 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
2024/03/29 10:58:58 [lang:3]   "song_id": "f0e1f3ba661d2889f2d71f94e364e7e2",
2024/03/29 10:58:58 [lang:3]   "playlist_id": "45",
2024/03/29 10:58:58 [lang:3]   "media_id": "143"
2024/03/29 10:58:58 [lang:3] }
2024/03/29 10:58:59 [lang:3] API feedback - Response (200): true
2024/03/29 10:58:59 [relay_1:2] Metadata update may have failed with error: 401, Authentication Required (HTTP/1.0)
2024/03/29 10:59:08 [decoder:2] Decoding "/var/azuracast/stations/the_river/media/202_material_girl_(radio_edit).mp3" ended: Ffmpeg_decoder.End_of_file.
2024/03/29 10:59:08 [dummy.1059:3] Source failed (no more tracks) stopping output...
2024/03/29 10:59:08 [file.replaygain.1059:3] Computed replay gain -10.64 dB for "/var/azuracast/stations/the_river/media/202_material_girl_(radio_edit).mp3" (time: 9.88380479813 s).
`

**Comment by unudelaradio** [comment]
Your sweepers may be too short... shorter than the previous song overlap. This can cause chaotic behaviors. Try to add few seconds of silence at the end of your sweepers. Then set a Cue Out for each one.

**Comment by wppronto** [comment]
Thanks. I'm wondering why it only happens sometimes though?

There is about three seconds at the end of each one, and the cues are set before end of file. But I see, that might not be long enough.  I'll try longer.

Thank you!

**Comment by wppronto** [comment]
Update: Not sure it's just a song length issue. Now I'm occasionally seeing instances where a sweeper plays, then a song, then the same sweeper after the song...even though that sweeper playlist is set for once an hour at a specific time.

**Comment by RM-FM** [comment]
@wppronto This was a Liquidsoap issue that should have been solved alongside with the `autocue` implementation and improvements. As soon as Azuracast is using the latest `Liquidsoap Rolling Release 2.2.x`, you should not have this issue anymore. Actually the issue was solved for `autocue` only, but it should also cover non-`autocue` scenarios. However, the final solution will be available with `Liquidsoap 2.3.0` only.

**Comment by RM-FM** [comment]
> Your sweepers may be too short... shorter than the previous song overlap. This can cause chaotic behaviors. Try to add few seconds of silence at the end of your sweepers. Then set a Cue Out for the new extended duration and Overlap for each one.

@unudelaradio Correct. Tracks shorter than the actual transition/overlap, caused weird behaviours such as repeating and missing metadata updates. This has been fixed now (please see my comment above). Liquidsoap now re-calculates the whole transition to match overlap/fade out/cue out the duration of the (too short) upcoming track.

**Comment by RM-FM** [comment]
@wppronto @unudelaradio Azuracast Rolling Release https://github.com/AzuraCast/AzuraCast/commit/b37e79358817407baaa7e029161ef5bc66aef285 (2024-04-05 16:58) comes with the latest LS fixes now.

**Comment by t0mtaylor** [comment]
@wppronto I had similar issue, fix is here in my comment: https://github.com/AzuraCast/AzuraCast/issues/7162#issuecomment-2143803893
