### ISSUE TITLE
Station Statistics - Listeners by Time Period error - DateTimeImmutable::shiftTimezone()

### ISSUE THREAD

**Issue by Eyecu** [AzuraCast/AzuraCast#7037]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#e9255d2

### What happened?

When you click on The station statistics Listeners by Time Period you get a red popup saying 
call to undeifined method
DateTimeImmutable::shiftTimezone()

And no information will display, Only found it happening on the Listeners By Time Period tab.

**Comment by netbladenl** [comment]
Same issue on two different servers

**Comment by netbladenl** [comment]
@BusterNeece Do you know what is going wrong with our installations?
