### ISSUE TITLE
Replace artwork/Dupes Issues

### ISSUE THREAD

**Issue by colmusic** [AzuraCast/AzuraCast#704]
1. We have a pretty substantial playlist and need to add some album artwork in. Fortunately Azura has the ability to replace album artwork and the feature works great. Unfortunately the feature does not end up changing the underlying metadata of the track (yet it does if you change the artist/track name for example). Is there a way of enabling this so replacing the artwork changes the artwork on the actual mp3/wav? 

2. When trying to remove duplicates, the tracks end up re-appearing.

**Comment by MyTheValentinus** [comment]
Missing informations about your issue, like installation method etc...
Unable to reproduct in this state....

**Comment by SlvrEagle23** [comment]
@colmusic I'm not sure what's going on with the second issue, but the first issue is definitely a valid enhancement request. Currently we do indeed only write back the basic ID3 data to the song, not including the album artwork.

**Comment by SlvrEagle23** [comment]
I forgot to update this enhancement request, but we've actually been writing album artwork back to the file for several months now. Closing this issue as resolved.
