### ISSUE TITLE
Unexpected Behavior When Moving Files within Subdirectories via Web Interface

### ISSUE THREAD

**Issue by Lokke** [AzuraCast/AzuraCast#7048]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

v0.19.5 Stable • Docker • PHP 8.3

### Description:
There seems to be an unexpected behaviour when using the web interface to move files, particularly those within subdirectories, while having the filter **"special:duplicates"** set. When moving files located within subdirectories to another directory, the subdirectories themselves are inadvertently moved along with the files, resulting in unexpected directory structures in the destination folder.

### Steps to Reproduce:

Access the web interface/media.
Navigate to a "Duplicate Songs".
Select files within (e.g., track1.mp3 and track2.mp3).
Move the selected files to a new folder (e.g., /media/destination/).

### Expected Behavior:
After moving the files, the contents of the destination folder (/media/destination/) should only contain the selected files without replicating the subdirectory structure. All files should be directly within the destination folder.

### Actual Behavior:
Upon inspection of the destination folder (/web/media/destination/), it's noticed that along with the selected files, the directory structure from the original location is also replicated within the destination folder. This leads to unexpected subdirectories within the destination folder, such as /media/destination/FOLDER/track1.mp3 and /media/destination/FOLDER/track2.mp3.

### Additional Information:
This behavior could potentially confuse users, as it deviates from the expected behavior and complicates file organization within the destination folder. To enhance user experience, it would be helpful to either maintain the original directory structure or provide an option to exclude subdirectories when moving files via the web interface.

Please let me know if you need further clarification or additional details to address this issue effectively.

https://github.com/AzuraCast/AzuraCast/assets/6406275/ace60599-39d8-4f01-b668-288b2262cd29

**Comment by BusterNeece** [comment]
@Lokke Thank you for the report, and sorry for the delay in getting back to it. It's a valid issue indeed, and certainly the intended behavior is that if you're moving files from search results (or other special pages) that it'll dump the files directly into the target directory, not matching the directory structure. This should now be the case in the latest Rolling Release.
