### ISSUE TITLE
Webplayer not starting playback

### ISSUE THREAD

**Issue by mediamagnet** [AzuraCast/AzuraCast#705]
**Installation method**
Traditional 
Linux media1804 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**
Attempting to start playback on web player is yielding a 404 error
playback works when visiting the icecast console and playing directly

errors in browser console:
GET http://radiotasbot.com:7001/radio?1533764078 404 (Not Found)
ocremix:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.

**To Reproduce**

**Expected behavior**
Playback starts.

**Screenshots**
![image](https://user-images.githubusercontent.com/16123496/43865894-87310d40-9b29-11e8-82cd-d36aea1a172d.png)

**Desktop (please complete the following information):**
 - Windows 10
 - chrome 68.0.3440.84 firefox 61.0.1

**Comment by SlvrEagle23** [comment]
@mediamagnet Have you customized the mount point for this station? If so, what media encoding did you use?

Basically all browsers can play MP3, many can play Ogg Vorbis and/or AAC+, but very few can play Opus. This may be the cause of this issue.

**Comment by mediamagnet** [comment]
@SlvrEagle23 it is mp3 128kbps

**Comment by SlvrEagle23** [comment]
@mediamagnet What port number is your station running on? The port you linked appears to be the port that AzuraCast itself is running on; the stations need their own dedicated port range, usually something like 8000.

**Comment by mediamagnet** [comment]
@SlvrEagle23 We're running it on 9989, there is a lot of LXC containers on the host system so finding ports that aren't claimed by other things is the reason for the high number, is the webplayer looking for port 8000?

**Comment by SlvrEagle23** [comment]
@mediamagnet No, if you've specified that the radio should be running on 9989 in the station profile, then it should correctly be looking for that port.

It appears it's still using the custom port on which AzuraCast itself is being served.

That same URL, but with port 9989, should be streaming audio, correct?

**Comment by mediamagnet** [comment]
@SlvrEagle23 Yes correct though I will point out that the 7001 is just a port forward to port 80, if I am on the same network as the server however I get the same results.

**Comment by SlvrEagle23** [comment]
@mediamagnet I'll look into that part of the code; if a nonstandard port is specified, it should be overwriting the port with the proper radio station port.

In the meantime, on the mount point, you should be able to specify a "custom listen URL"; if you manually enter in the domain and correct port, it should stream without issue.

**Comment by mediamagnet** [comment]
@SlvrEagle23 awesome thank you.

**Comment by jxrse** [comment]
I can't make the radio play from the WebPlayer, I have several errors in red and it doesn't work for me.

If I listen directly to the radio with the link in mp3 if I can hear it without problems.

It is configured with port 8000

I attached a series of photos with the error that gives me the console of Google Chrome and the Configuration of the ports in the server

Thank you !!

![ports-server](https://user-images.githubusercontent.com/55897061/65799881-70b76080-e175-11e9-8f28-095b1ba76a68.png)

![console-error](https://user-images.githubusercontent.com/55897061/65799882-70b76080-e175-11e9-98e6-41c67d398bc5.png)

![error-console2](https://user-images.githubusercontent.com/55897061/65799879-701eca00-e175-11e9-8630-1cfef5a06703.png)
