### ISSUE TITLE
On-Demand Issue

### ISSUE THREAD

**Issue by corey-harker** [AzuraCast/AzuraCast#7050]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#b37e793 

### What happened?

I am seeing 'This station does not currently support on-demand media'. I have gone through all the settings and enabled 'on-demand' but cannot find where to put the media files that are specifically for that feature. Am I missing something?

**Comment by BusterNeece** [comment]
@corey-harker It's at the per-playlist level; just mark a playlist as "available in on-demand" and all of its contents will become available. You may have to wait a minute or two after changing that for the caches to reset.

**Comment by corey-harker** [comment]
Thanks Buster… Got it!

 

Best,

 

Corey Harker

507-782-9613

 ***@***.***> ***@***.***
