### ISSUE TITLE
AzuraCast Web DJ not working

### ISSUE THREAD

**Issue by BornKillaz** [AzuraCast/AzuraCast#7058]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable

### Current AzuraCast Version

AzuraCast • v0.19.5 Stable • Docker • PHP 8.3

### What happened?

Hi.

Web DJ is not working. I use streamer username and password, and it doesn't start streaming. Nothing happens.

This streamer is not limited to any specific time.

In Chrome and Edge I don't even get an error message, on Firefox I get this error when trying to connect: "An error occurred with the WebDJ socket."

### Relevant log output

```shell
Nothing on log.
```

**Comment by BornKillaz** [comment]
Am I the only one suffering from this issue?

**Comment by gAlleb** [comment]
Latest RR. All is good for me.
