### ISSUE TITLE
WebDJ, start streaming results in DOMException: Failed to construct 'WebSocket': The URL 'undefined' is invalid.

### ISSUE THREAD

**Issue by emtoonst** [AzuraCast/AzuraCast#7059]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.5 Stable • Docker • PHP 8.3

### What happened?

When I click the button 'Start streaming' in the WebDJ, an error occurs in both Firefox and Chrome:

vue-D_WLdR4x.js:13 DOMException: Failed to construct 'WebSocket': The URL 'undefined' is invalid.

![domexception](https://github.com/AzuraCast/AzuraCast/assets/9829360/9f107536-4768-494c-bfea-3dceb2763887)

It looks simmilar to #5994 

The docker is running on a Linux (ubuntu 22.04) server in the Azure Cloud. It has al the relevant ports open in the firewall:

443
8000
80
2022
8005

**Comment by BornKillaz** [comment]
Hi! 

Same happening to me. I've posted it [here](https://github.com/AzuraCast/AzuraCast/issues/7058).

**JS Console Log**
`PublicWebDJ-D7lpc58V.js:1 [Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (https://bit.ly/audio-worklet)
(anonymous) @ PublicWebDJ-D7lpc58V.js:1
(anonymous) @ vue-D_WLdR4x.js:9
run @ vue-D_WLdR4x.js:9
get value @ vue-D_WLdR4x.js:9
(anonymous) @ PublicWebDJ-D7lpc58V.js:1
(anonymous) @ vue-D_WLdR4x.js:9
run @ vue-D_WLdR4x.js:9
get value @ vue-D_WLdR4x.js:9
startStream @ PublicWebDJ-D7lpc58V.js:1
x.onClick.s.<computed>.s.<computed> @ PublicWebDJ-D7lpc58V.js:1
Ue @ vue-D_WLdR4x.js:13
we @ vue-D_WLdR4x.js:13
n @ vue-D_WLdR4x.js:17
vue-D_WLdR4x.js:13 DOMException: Failed to construct 'WebSocket': The URL 'undefined' is invalid.
    at connect (https://stream.xxxxxxxxxxxxxxxxx.com:8090/static/vite_dist/assets/PublicWebDJ-D7lpc58V.js:1:8272)
    at startStream (https://stream.xxxxxxxxxxxxxxxxx.com:8090/static/vite_dist/assets/PublicWebDJ-D7lpc58V.js:1:3389)
    at x.onClick.s.<computed>.s.<computed> (https://stream.xxxxxxxxxxxxxxxxx.com:8090/static/vite_dist/assets/PublicWebDJ-D7lpc58V.js:1:18541)
    at Ue (https://stream.xxxxxxxxxxxxxxxxx.com:8090/static/vite_dist/vue-D_WLdR4x.js:13:1373)
    at we (https://stream.xxxxxxxxxxxxxxxxx.com:8090/static/vite_dist/vue-D_WLdR4x.js:13:1443)
    at HTMLButtonElement.n (https://stream.xxxxxxxxxxxxxxxxx.com:8090/static/vite_dist/vue-D_WLdR4x.js:17:8113)
dc @ vue-D_WLdR4x.js:13
Ct @ vue-D_WLdR4x.js:13
Ue @ vue-D_WLdR4x.js:13
we @ vue-D_WLdR4x.js:13
n @ vue-D_WLdR4x.js:17`

**Comment by emtoonst** [comment]
If test it on my Synology NAS and I configure a Reverse Proxy with websocket header, it works as intended. So I must find a way to add a reverse proxy to my server.

**Comment by BornKillaz** [comment]
Let me know if you can get this resolved with some hacking, as unfortunately it looks like this is not a priority. And I'm positive that this issue occurs on many installations, however not everyone needs this feature, so this bug just gets ignored by the most.

**Comment by BusterNeece** [comment]
@emtoonst @BornKillaz Can y'all link an example of this happening in the wild? I'm not seeing it happening on our local installations, which is why it's especially difficult to diagnose and fix.

**Comment by emtoonst** [comment]
Hi Buster, I have added you as  a Super User to my radiostation, details are mailed to your mailadres.

**Comment by BusterNeece** [comment]
@emtoonst Oh, this was actually fixed in the Rolling Release channel. Can you try switching to that and see if it fixes it? Should resolve it completely.

**Comment by emtoonst** [comment]
Confirmed @BusterNeece , switching to rolling release fixed the error. I am now on Rolling Release #[aefe069] (2024-04-26 21:38) • Docker • PHP 8.3.

**Comment by emtoonst** [comment]
Closed.

**Comment by BornKillaz** [comment]
Nice. I have Docker install. How to properly update to Rolling Release? Is it safe to do it without loosing any data? 
Thank you.

**Comment by emtoonst** [comment]
How to switch is descrided in the manual. It was easy and only took a few minutes. You don't loose data, but please make an update anyway.

**Comment by BornKillaz** [comment]
> How to switch is descrided in the manual. It was easy and only took a few minutes. You don't loose data, but please make an update anyway.

Ok, thank you.
