### ISSUE TITLE
player embed not working 

### ISSUE THREAD

**Issue by jasonboateng** [AzuraCast/AzuraCast#706]
Refused to display 'https://41.66.213.14/public/atuonline_radio/embed-requests' in a frame because it set 'X-Frame-Options' to 'deny'.

how can i set X-Frame -Option to allow or can i find it

**Comment by MyTheValentinus** [comment]
Hello,
Thanks to use issue template..

Missing information to reply on your issue.


- **Installation method**
- **Host OS (for Docker installations)**
- **To Reproduce**
- **Screenshots**
- **Desktop (please complete the following information):**
- **Additional context**

**Comment by jasonboateng** [comment]
Docker install 
Host OS  Ubuntu Server 16
![screenshot 2](https://user-images.githubusercontent.com/16203851/43906162-770f4840-9ba7-11e8-85d9-208397e88baf.png)

**Comment by SlvrEagle23** [comment]
@jasonboateng Sorry about that! One of my recent updates appears to have the unintended side effect of breaking embedding on the public pages. This should now be fixed. Thank you for your report. :)
