### ISSUE TITLE
Streamers/DJ Accounts page blank.

### ISSUE THREAD

**Issue by Eyecu** [AzuraCast/AzuraCast#7064]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 #c3e540e

### What happened?

Going to the Streamers/DJ Accounts page the page is blank no info displays. 
![azuracast1](https://github.com/AzuraCast/AzuraCast/assets/443742/f5ab9735-d675-46a3-bd9a-da2d0ddfd284)

**Comment by BusterNeece** [comment]
I'm not seeing this same issue on my local development instance...I'd have to look at the actual source code of that page (the HTML it's serving) to know what's causing the problem. You can right click a blank area on the page and click "View Source" to see it. You may want to make sure nothing sensitive is in that code, but feel free to post it here otherwise.

**Comment by Eyecu** [comment]
`<html>
<body>

  | <!DOCTYPE html>
-- | --
  | <html lang="en">
  | <head>
  | 
  | <meta http-equiv="X-UA-Compatible" content="IE=edge">
  | <meta name="viewport" content="width=device-width, initial-scale=1">
  |  
  | <title>Relay-Radio - AzuraCast</title>
  |  
  | <script type="module" src="/static/vite_dist/assets/Layout-nsVCYyrR.js"></script>
  | <script>
  | function ready(callback) {
  | if (document.readyState !== "loading") callback();
  | else document.addEventListener("DOMContentLoaded", callback);
  | }
  | </script>    <link rel="stylesheet" href="/static/vite_dist/assets/Layout-i2BxCP3p.css" />
  | <link rel="apple-touch-icon" sizes="57x57" href="/static/icons/production/57.png">
  | <link rel="apple-touch-icon" sizes="60x60" href="/static/icons/production/60.png">
  | <link rel="apple-touch-icon" sizes="72x72" href="/static/icons/production/72.png">
  | <link rel="apple-touch-icon" sizes="76x76" href="/static/icons/production/76.png">
  | <link rel="apple-touch-icon" sizes="114x114" href="/static/icons/production/114.png">
  | <link rel="apple-touch-icon" sizes="120x120" href="/static/icons/production/120.png">
  | <link rel="apple-touch-icon" sizes="144x144" href="/static/icons/production/144.png">
  | <link rel="apple-touch-icon" sizes="152x152" href="/static/icons/production/152.png">
  | <link rel="apple-touch-icon" sizes="180x180" href="/static/icons/production/180.png">
  | <link rel="icon" type="image/png" sizes="192x192" href="/static/icons/production/192.png">
  | <link rel="icon" type="image/png" sizes="32x32" href="/static/icons/production/32.png">
  | <link rel="icon" type="image/png" sizes="96x96" href="/static/icons/production/96.png">
  | <link rel="icon" type="image/png" sizes="16x16" href="/static/icons/production/16.png">
  | <meta name="msapplication-TileColor" content="#2196F3">
  | <meta name="msapplication-TileImage" content="/static/icons/production/144.png">
  | <meta name="theme-color" content="#2196F3">
  |  
  | <link rel="stylesheet" href="/static/vite_dist/assets/InlinePlayer-Cc-AU7A8.css" />
  | <link rel="modulepreload" href="/static/vite_dist/usePlayerStore-aUauACMm.js" />
  | <link rel="modulepreload" href="/static/vite_dist/vue-TWk4UXiX.js" />
  | <link rel="modulepreload" href="/static/vite_dist/lodash-BduLK7P_.js" />
  | <link rel="modulepreload" href="/static/vite_dist/router-BrW47JAG.js" />
  | <link rel="modulepreload" href="/static/vite_dist/PanelLayout-Ku-SYMum.js" />
  | <link rel="modulepreload" href="/static/vite_dist/icons-UKi4lxOD.js" />
  | <link rel="modulepreload" href="/static/vite_dist/useOptionalStorage-gd3_gss2.js" />
  | <link rel="modulepreload" href="/static/vite_dist/index-BKgP_r0V.js" />
  | <link rel="modulepreload" href="/static/vite_dist/populateComponentRemotely-BMDCdoDh.js" />
  | <link rel="modulepreload" href="/static/vite_dist/acl-DZtVH4Sl.js" />
  | <link rel="modulepreload" href="/static/vite_dist/router-DLVqvRtz.js" />
  | <link rel="modulepreload" href="/static/vite_dist/useStationDateTimeFormatter-CiQDqqUX.js" />
  | <link rel="modulepreload" href="/static/vite_dist/luxon-Dk5TlS5B.js" />
  | <link rel="modulepreload" href="/static/vite_dist/datetime-BLS2EMbI.js" />
  | <link rel="modulepreload" href="/static/vite_dist/Lightbox-DVAogVm6.js" />
  | <link rel="modulepreload" href="/static/vite_dist/HeaderInlinePlayer-CxPXdQF2.js" />
  | <link rel="modulepreload" href="/static/vite_dist/InlinePlayer-Cke5EAvm.js" />
  | <link rel="modulepreload" href="/static/vite_dist/usePlayerVolume-BQ2aWIBX.js" />
  | <link rel="modulepreload" href="/static/vite_dist/hlsjs-NT_6F8Ap.js" />
  | <link rel="modulepreload" href="/static/vite_dist/formatTime-DvDPwXf4.js" />
  | <link rel="modulepreload" href="/static/vite_dist/lightbox-BuOdrX5v.js" />
  | <style>
  | </style>
  | </head>
  | <body class="page-full">
  | <script type="module" src="/static/vite_dist/assets/Stations-DL2OTXiZ.js"></script>
  | <script type="text/javascript">
  | let Vue_Stations;
  | ready(() => {
  | Vue_Stations = window.vueComponent('#stations-index', {"enableAdvancedFeatures":true,"locale":"en_US","localeShort":"en","localeWithDashes":"en-US","user":{"id":1,"displayName":"manager@relay-radio.com","globalPermissions":["administer all"],"stationPermissions":[]},"timeConfig":{"hour12":true},"station":{"id":1,"name":"Relay-Radio","isEnabled":true,"shortName":"relay-radio","timezone":"America\/Toronto","offlineText":null},"apiCsrf":"jfrNO1d9hg","panelProps":{"instanceName":"Relay-Radio","userDisplayName":"manager@relay-radio.com","homeUrl":"\/dashboard","adminUrl":"\/admin","profileUrl":"\/profile","logoutUrl":"\/logout","showAdmin":true,"version":"Rolling Release #<a href=\"https:\/\/github.com\/AzuraCast\/AzuraCast\/commit\/c3e540eae7d38e995782a683d6914c8aeaba6bdb\" target=\"_blank\">c3e540e<\/a> (2024-04-17 10:18)","platform":"Docker &bull; PHP 8.3"},"sidebarProps":{"station":{"hasStarted":true,"needsRestart":false,"enablePublicPages":true,"publicPageUrl":"\/public\/relay-radio","enableOnDemand":true,"onDemandUrl":"\/public\/relay-radio\/ondemand","webDjUrl":"https:\/\/radio.relay-radio.com\/public\/relay-radio\/dj","enableRequests":true,"features":{"media":true,"sftp":true,"podcasts":true,"streamers":true,"webhooks":true,"mountPoints":true,"hlsStreams":false,"remoteRelays":true,"customLiquidsoapConfig":true,"autoDjQueue":true}}},"componentProps":{"baseUrl":"\/station\/1"}});
  | });
  | </script>
  |  
  | <div id="stations-index">Loading...</div>
  | <div class="toast-container position-fixed top-0 end-0 p-3">
  | </div>
  | </body>
  | </html>
  |  


</body>
</html><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Relay-Radio - AzuraCast</title>

        <script type="module" src="[/static/vite_dist/assets/Layout-nsVCYyrR.js](https://radio.relay-radio.com/static/vite_dist/assets/Layout-nsVCYyrR.js)"></script>
    <script>
    function ready(callback) {
        if (document.readyState !== "loading") callback();
        else document.addEventListener("DOMContentLoaded", callback);
    }
    </script>    <link rel="stylesheet" href="[/static/vite_dist/assets/Layout-i2BxCP3p.css](https://radio.relay-radio.com/static/vite_dist/assets/Layout-i2BxCP3p.css)" />
<link rel="apple-touch-icon" sizes="57x57" href="[/static/icons/production/57.png](https://radio.relay-radio.com/static/icons/production/57.png)">
<link rel="apple-touch-icon" sizes="60x60" href="[/static/icons/production/60.png](https://radio.relay-radio.com/static/icons/production/60.png)">
<link rel="apple-touch-icon" sizes="72x72" href="[/static/icons/production/72.png](https://radio.relay-radio.com/static/icons/production/72.png)">
<link rel="apple-touch-icon" sizes="76x76" href="[/static/icons/production/76.png](https://radio.relay-radio.com/static/icons/production/76.png)">
<link rel="apple-touch-icon" sizes="114x114" href="[/static/icons/production/114.png](https://radio.relay-radio.com/static/icons/production/114.png)">
<link rel="apple-touch-icon" sizes="120x120" href="[/static/icons/production/120.png](https://radio.relay-radio.com/static/icons/production/120.png)">
<link rel="apple-touch-icon" sizes="144x144" href="[/static/icons/production/144.png](https://radio.relay-radio.com/static/icons/production/144.png)">
<link rel="apple-touch-icon" sizes="152x152" href="[/static/icons/production/152.png](https://radio.relay-radio.com/static/icons/production/152.png)">
<link rel="apple-touch-icon" sizes="180x180" href="[/static/icons/production/180.png](https://radio.relay-radio.com/static/icons/production/180.png)">
<link rel="icon" type="image/png" sizes="192x192" href="[/static/icons/production/192.png](https://radio.relay-radio.com/static/icons/production/192.png)">
<link rel="icon" type="image/png" sizes="32x32" href="[/static/icons/production/32.png](https://radio.relay-radio.com/static/icons/production/32.png)">
<link rel="icon" type="image/png" sizes="96x96" href="[/static/icons/production/96.png](https://radio.relay-radio.com/static/icons/production/96.png)">
<link rel="icon" type="image/png" sizes="16x16" href="[/static/icons/production/16.png](https://radio.relay-radio.com/static/icons/production/16.png)">
<meta name="msapplication-TileColor" content="#2196F3">
<meta name="msapplication-TileImage" content="/static/icons/production/144.png">
<meta name="theme-color" content="#2196F3">

        <link rel="stylesheet" href="[/static/vite_dist/assets/InlinePlayer-Cc-AU7A8.css](https://radio.relay-radio.com/static/vite_dist/assets/InlinePlayer-Cc-AU7A8.css)" />
    <link rel="modulepreload" href="[/static/vite_dist/usePlayerStore-aUauACMm.js](https://radio.relay-radio.com/static/vite_dist/usePlayerStore-aUauACMm.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/vue-TWk4UXiX.js](https://radio.relay-radio.com/static/vite_dist/vue-TWk4UXiX.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/lodash-BduLK7P_.js](https://radio.relay-radio.com/static/vite_dist/lodash-BduLK7P_.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/router-BrW47JAG.js](https://radio.relay-radio.com/static/vite_dist/router-BrW47JAG.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/PanelLayout-Ku-SYMum.js](https://radio.relay-radio.com/static/vite_dist/PanelLayout-Ku-SYMum.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/icons-UKi4lxOD.js](https://radio.relay-radio.com/static/vite_dist/icons-UKi4lxOD.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/useOptionalStorage-gd3_gss2.js](https://radio.relay-radio.com/static/vite_dist/useOptionalStorage-gd3_gss2.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/index-BKgP_r0V.js](https://radio.relay-radio.com/static/vite_dist/index-BKgP_r0V.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/populateComponentRemotely-BMDCdoDh.js](https://radio.relay-radio.com/static/vite_dist/populateComponentRemotely-BMDCdoDh.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/acl-DZtVH4Sl.js](https://radio.relay-radio.com/static/vite_dist/acl-DZtVH4Sl.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/router-DLVqvRtz.js](https://radio.relay-radio.com/static/vite_dist/router-DLVqvRtz.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/useStationDateTimeFormatter-CiQDqqUX.js](https://radio.relay-radio.com/static/vite_dist/useStationDateTimeFormatter-CiQDqqUX.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/luxon-Dk5TlS5B.js](https://radio.relay-radio.com/static/vite_dist/luxon-Dk5TlS5B.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/datetime-BLS2EMbI.js](https://radio.relay-radio.com/static/vite_dist/datetime-BLS2EMbI.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/Lightbox-DVAogVm6.js](https://radio.relay-radio.com/static/vite_dist/Lightbox-DVAogVm6.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/HeaderInlinePlayer-CxPXdQF2.js](https://radio.relay-radio.com/static/vite_dist/HeaderInlinePlayer-CxPXdQF2.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/InlinePlayer-Cke5EAvm.js](https://radio.relay-radio.com/static/vite_dist/InlinePlayer-Cke5EAvm.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/usePlayerVolume-BQ2aWIBX.js](https://radio.relay-radio.com/static/vite_dist/usePlayerVolume-BQ2aWIBX.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/hlsjs-NT_6F8Ap.js](https://radio.relay-radio.com/static/vite_dist/hlsjs-NT_6F8Ap.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/formatTime-DvDPwXf4.js](https://radio.relay-radio.com/static/vite_dist/formatTime-DvDPwXf4.js)" />
    <link rel="modulepreload" href="[/static/vite_dist/lightbox-BuOdrX5v.js](https://radio.relay-radio.com/static/vite_dist/lightbox-BuOdrX5v.js)" />
    <style>
            </style>
</head>
<body class="page-full">
    <script type="module" src="[/static/vite_dist/assets/Stations-DL2OTXiZ.js](https://radio.relay-radio.com/static/vite_dist/assets/Stations-DL2OTXiZ.js)"></script>
    <script type="text/javascript">
        let Vue_Stations;
        ready(() => {
            Vue_Stations = window.vueComponent('#stations-index', {"enableAdvancedFeatures":true,"locale":"en_US","localeShort":"en","localeWithDashes":"en-US","user":{"id":1,"displayName":"manager@relay-radio.com","globalPermissions":["administer all"],"stationPermissions":[]},"timeConfig":{"hour12":true},"station":{"id":1,"name":"Relay-Radio","isEnabled":true,"shortName":"relay-radio","timezone":"America\/Toronto","offlineText":null},"apiCsrf":"jfrNO1d9hg","panelProps":{"instanceName":"Relay-Radio","userDisplayName":"manager@relay-radio.com","homeUrl":"\/dashboard","adminUrl":"\/admin","profileUrl":"\/profile","logoutUrl":"\/logout","showAdmin":true,"version":"Rolling Release #<a href=\"https:\/\/github.com\/AzuraCast\/AzuraCast\/commit\/c3e540eae7d38e995782a683d6914c8aeaba6bdb\" target=\"_blank\">c3e540e<\/a> (2024-04-17 10:18)","platform":"Docker &bull; PHP 8.3"},"sidebarProps":{"station":{"hasStarted":true,"needsRestart":false,"enablePublicPages":true,"publicPageUrl":"\/public\/relay-radio","enableOnDemand":true,"onDemandUrl":"\/public\/relay-radio\/ondemand","webDjUrl":"https:\/\/radio.relay-radio.com\/public\/relay-radio\/dj","enableRequests":true,"features":{"media":true,"sftp":true,"podcasts":true,"streamers":true,"webhooks":true,"mountPoints":true,"hlsStreams":false,"remoteRelays":true,"customLiquidsoapConfig":true,"autoDjQueue":true}}},"componentProps":{"baseUrl":"\/station\/1"}});
        });
    </script>

<div id="stations-index">Loading...</div>
<div class="toast-container position-fixed top-0 end-0 p-3">
    </div>
</body>
</html>`

**Comment by Eyecu** [comment]
Not sure if this is relevant, But seems to be a greater issue for me say I go to the streamers page and then try and go back to the main (profile) page it's blank unless I refresh the page the profile page displays again. 

Also out of the blue this morning the embedded players I have on my websites stopped working. the station id is 1 and now in the API 1 just displays an image and not a json return, using any other number displays the radio info (note I have only one station running in azuracast) but I didn't update today or anything just out of the blue stopped working at 7:18am EST this morning.

**Comment by BusterNeece** [comment]
@Eyecu Try visiting this URL once you're signed in to AzuraCast on your installation: https://radio.relay-radio.com/api/station/1/vue/streamers and let me know what you see there. It seems that URL isn't loading correctly on your install.

**Comment by Eyecu** [comment]
{"connectionInfo":{"serverUrl":"https://radio.relay-radio.com","streamPort":8005,"ip":"198.27.81.15","djMountPoint":"/"}}

**Comment by Eyecu** [comment]
I've gone through everything i can think of the only two pages that seem to have an issue are the streamers/dj accounts page. and the reports - listeners page. all other pages load correctly.  Then the API issue which fixed itself last night. We recently added the player widget to a site that has more traffic like the night before all this started and wondering if maybe that has a hand in this

**Comment by BusterNeece** [comment]
@Eyecu That response is pretty normal...it's possible you just had a one-time error on the streamers page. Does refreshing resolve the issue, or yield a different issue in the network console? This one's pretty tricky to diagnose.

**Comment by Eyecu** [comment]
Ya it's weird refresh doesn't resolve the streamers or listeners page. i restart the PHP worker, clear browser cache and go back to the page and ctrl + f5 and it works again. Worked all evening last night just fine, then woke up this morning and it wasn't working again.

**Comment by erik-agens** [comment]
I am seeing the same thing, but it happens to me on the View Profile page. If I hit refresh it flickers with the page for a millisecond before it goes blank. It just suddenly started to happen and it does not help to clear cache.
However, when opening the page in a different browser it works as expected.

**Comment by netbladenl** [comment]
> I am seeing the same thing, but it happens to me on the View Profile page. If I hit refresh it flickers with the page for a millisecond before it goes blank. It just suddenly started to happen and it does not help to clear cache. However, when opening the page in a different browser it works as expected.

Same issue with a new install, in Edge It shows a half not working profilepage, in Firefox and Chrome it works as it should. Deleted cookies and history without any effect
