### ISSUE TITLE
Problem Play music

### ISSUE THREAD

**Issue by Ciacho132066** [AzuraCast/AzuraCast#7066]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

![Zrzut ekranu 2024-04-19 150734](https://github.com/AzuraCast/AzuraCast/assets/59518363/ae873904-f182-44d4-ae17-5908da367833)
![Zrzut ekranu 2024-04-20 100351](https://github.com/AzuraCast/AzuraCast/assets/59518363/d31bdeb7-325e-46b7-b92a-28d94804cbcf)
![Zrzut ekranu 2024-04-20 100410](https://github.com/AzuraCast/AzuraCast/assets/59518363/f3baa44b-ba4b-4129-903b-a33a08af0d77)
![Zrzut ekranu 2024-04-20 100424](https://github.com/AzuraCast/AzuraCast/assets/59518363/55268f29-9808-4d73-b7a0-c161fb63809b)
![Zrzut ekranu 2024-04-20 100448](https://github.com/AzuraCast/AzuraCast/assets/59518363/7dcd23ec-09dc-42bc-9a1f-3cffedb6ca8e)

After deleting the mp3 media files, the memory was still occupied even though all the files were deleted. Only after connecting via Sftp was it possible to add the files, but now the files do not work and the inscription "File processing" appears next to each mp3 file.
The music just doesn't work, some guy says something in English while broadcasting....

### Relevant log output

```shell
After deleting the mp3 media files, the memory was still occupied even though all the files were deleted. Only after connecting via Sftp was it possible to add the files, but now the files do not work and the inscription "File processing" appears next to each mp3 file.
The music just doesn't work, some guy says something in English while broadcasting....
```

**Comment by BusterNeece** [comment]
@Ciacho132066 It's hard to tell what's going wrong with your installation just based on your description. I'd strongly recommend restarting the host server to reset any temporary files that may be in your Docker container and clear up any used storage.

It's possible that your synchronized tasks aren't running properly, which a restart also should significantly help resolve.

If those things don't get resolved, check System Administration > Log Viewer and look at the application logs to see if you see any error messages. If you do, feel free to post them here.

**Comment by BusterNeece** [comment]
@Ciacho132066 I can't give you instructions on how specifically to restart your host server, since I don't know where you host your server, what kind of platform it is...I can generally assume that you'd connect with SSH to the server that hosts AzuraCast and type `reboot` or something similar. Maybe `sudo reboot`. This task requires some minor Linux knowledge.

**Comment by Ciacho132066** [comment]
Hosted normally on azuracast
https://www.asurahosting.com/azuracast-hosting
I have no idea what this is about and I can't restart it...

sob., 20 kwi 2024 o 14:05 Buster Neece ***@***.***>
napisał(a):

**Comment by BusterNeece** [comment]
@Ciacho132066 AsuraHosting is a company whose name just happens to sound a lot like AzuraCast but is not officially associated with AzuraCast in any way. You'll need to contact them to resolve the issue.
