### ISSUE TITLE
fade_overlap doesn't work

### ISSUE THREAD

**Issue by DJMic** [AzuraCast/AzuraCast#7070]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.5

### What happened?

I have set the fade_overlap for each of my songs and jingles, but it doesn't work. Songs and jingles are played until cue_out. Default fade is set to 0.2 sec and I use normal crossfading. Is there a workaround for custom fade overlap to be applied ?

**Comment by gAlleb** [comment]
https://github.com/AzuraCast/AzuraCast/discussions/6252
