### ISSUE TITLE
Message; This server is not the current active instance !!

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#7078]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.19.5 Stable • Docker • PHP 8.3

### What happened?

Opened my dashboard this morning to empty a media folder and all was fine...

1 hr later I reopen the dashboard and this message appears; 
This server is not the current active instance.
This likely means that multiple AzuraCast instances are connecting to the same database. This instance is not the current active one, so synchronized tasks won't run on this server. If this is intentional, you can disregard this message.

I have only 1 station on this server, so I fail to understand the meaning of this.  What is going on and what do I need to do to fix it?

Thanks in advance;
Speedy

**Comment by Sweetness2k** [comment]
I get that message every week and it make my all my streams playlist go in a loop playing the same song over and over till i have to restart all the streams, it was like this for months now and it becoming really bad.. just had the same issue today...
