### ISSUE TITLE
How to re-stream AND transcode a 3rd party station? (Edited)

### ISSUE THREAD

**Issue by AdamDaze** [AzuraCast/AzuraCast#708]
HI crew.

I'm looking to re-stream a station from http://streamer.dgen.net:8000/rinseradio and transcode it to OGG format for use for something that only accepts that format. 

I've tried setting that as a relay stream url for a mountpoint, which works, but the "AutoDJ' transcode settings aren't affecting the live stream. Though the mount point is *.ogg, the headers show it's still a mp3 stream. 

Any assistance? I hear liquidsoap can help with this but I'm lost. 

running Ubuntu server, latest version, docker install.

**Comment by AdamDaze** [comment]
Ah, I believe I'm specifying the wrong thing entirely. I'm trying to use the "connect to remote server" option as though it's the SOURCE, not the DESTINATION, of audio. My bad. Is there a way to specify a remote stream as the input for Azuracast, have azuracast transcode it, then send it on to my intended application?

**Comment by AdamDaze** [comment]
Okay, I think I have this. I need to configure the icecast mount as a relay, using https://icecast.org/docs/icecast-trunk/relaying/ , and punching that into  Advanced: Custom Configuration?

**Comment by AdamDaze** [comment]
Okay, after trying to do it all the hard way I finally found the mount point config setting : "Relay Stream URL
Enter the full URL of another stream to relay its broadcast through this mount point.
"

This doesn't appear to be working either. 

Hmm. Not sure if icecast supports on the fly transcoding of a stream when relaying, hey.

**Comment by AdamDaze** [comment]
So I put this in the liquidsoap config section 

# Input the stream,
# from an Icecast server or any other source
url = "http://streamer.dgen.net:8000/rinseradio"
input = mksafe(input.http(url))

# First transcoder: 

output.icecast(
 %vorbis.cbr(samplerate=44100, channels=2, bitrate=96)
  mount="/australisrinse.ogg",
  host="http://144.48.37.170", port=8020, user="rinse", password="ausrad",
  mean(input))

On on station restart get "SPAWN_ERROR: station_7:station_7_backend" and the liquidsoap service says "not running", though the rest is.  Removing that and restarting restores service starting.

**Comment by AdamDaze** [comment]
So I put this in the liquidsoap config section 

# Input the stream,
# from an Icecast server or any other source
url = "http://streamer.dgen.net:8000/rinseradio"
input = mksafe(input.http(url))

# First transcoder: 

output.icecast(
 %vorbis.cbr(samplerate=44100, channels=2, bitrate=96)
  mount="/australisrinse.ogg",
  host="redacted", port=8020, user="redacted", password="redacted",
  mean(input))

On on station restart get "SPAWN_ERROR: station_7:station_7_backend" and the liquidsoap service says "not running", though the rest is.  Removing that and restarting restores service starting.

**Comment by SlvrEagle23** [comment]
@AdamDaze The variable name for the composited radio signal is `radio`, not `input`. If you change the name, that code above might work. If you're running Docker, you can run `docker-compose logs -f stations` from the host's SSH terminal to view the services as they're restarting, and see what's preventing it from starting up, if anything.
