### ISSUE TITLE
How to change back the direct stream URL from /listen to /radio

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#7085]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #c694c81 (2024-05-05 0:26) • Docker • PHP 8.3

### What happened?

Yesterday I upgraded the system from version 0.14.1 to the latest version. It's about time!
I noticed that the direct link to the stream has changed
In the old version it was `http://domain.com/radio/statsion/radio.mp3`
Whereas in the new version: `http://domain.com/listen/statsion/radio.mp3`
How can you change it back to **/radio** ?

**Comment by rolradio** [comment]
Hi,

You probably mean this link that was previously used:
https://domain.com/radio/portnumber/radio.mp3
(Where port number is the broadcast port number of your radio)
This one still works, next to the link currently used.

**Comment by eranwo** [comment]
Hi,
I'm running Rolling Release #c694c81 (2024-05-05 0:26) • Docker • PHP 8.3
And it doesn't work for me. I remember that in previous versions it worked both ways
![image](https://github.com/AzuraCast/AzuraCast/assets/2701228/a905fdd1-21f4-421a-b299-2db924ce9062)

**Comment by eranwo** [comment]
This is the structure of the direct link to the stream that worked in the previous version that I used until now:
http://domain.com/listen/statsion/radio.mp3 (proxy mode)
Is it possible to change or add /radio as well so that the previous structure continues to work without disturbing the users?

**Comment by BusterNeece** [comment]
@eranwo We only ever supported two formats, one being the older `/radio/8000/radio.mp3` which included the port number, and the newer being `/listen/station_name/radio.mp3` which included the station's short name. We switched to the latter to improve personalization of the URLs and to avoid the URLs being tied directly to port number mappings, which are an internal detail, though you can definitely still use the former URL format without issue. It just was never `/radio/(station_name)/radio.mp3`.
