### ISSUE TITLE
Error on Manage DJ

### ISSUE THREAD

**Issue by fiesi** [AzuraCast/AzuraCast#7087]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.06 Stable

### What happened?

When i Click on Live-Streaming -> Live Streamer / DJ Account then i become this Error:

Ignore on "DoctrineProxies\__CG__\App\Entity\StationStreamer::__setInitialized()" cannot be added. Ignore can only be added on methods beginning with "get", "is", "has" or "set".

This Problem is Only on One Stream. The Other Stream has the Problem not

### Relevant log output

```shell
Ignore on "DoctrineProxies\__CG__\App\Entity\StationStreamer::__setInitialized()" cannot be added. Ignore can only be added on methods beginning with "get", "is", "has" or "set".
```

**Comment by BusterNeece** [comment]
@fiesi This may be caused by the proxies not being generated correctly upon update...can you try restarting your AzuraCast instance and seeing if that fixes things by itself?

**Comment by BusterNeece** [comment]
@fiesi Disregard the previous message...I discovered that this is a legitimate bug introduced in Symfony, one of our upstream package dependencies. I've updated it and am tagging a 0.19.7 release, as it's likely that it will affect large portions of the application for users. The 0.19.7 release will be available shortly and I'd recommend updating to it to resolve this issue.
