### ISSUE TITLE
Time range selection in reports section.

### ISSUE THREAD

**Issue by djmuratb** [AzuraCast/AzuraCast#709]
**Is your feature request related to a problem? Please describe.**
Time range selection in reports section.

**Describe the solution you'd like**
Datepicker form in Song Playback Timeline.
https://www.eyecon.ro/bootstrap-datepicker

**Describe alternatives you've considered**
By adding a Datepicker form, we can download a PDF or CSV report for an optional time interval. I would like to add this myself, but I do not have enough knowledge.

**Additional context**
![indir](https://user-images.githubusercontent.com/25807005/43976701-3c98a9ec-9cea-11e8-9613-51e9d6b051c1.png)

Thanks.

**Comment by SlvrEagle23** [comment]
@djmuratb This has now been implemented via a new Station History API, which allows authenticated users to retrieve a station's history for any given date range. This has also been expanded into a custom date range selector for the Song Playback Timeline report, which will also export to CSV the date range you're currently viewing.
