### ISSUE TITLE
Backups do not automatically delete

### ISSUE THREAD

**Issue by AaronUnmuted** [AzuraCast/AzuraCast#7095]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.19.5 Stable

### What happened?

Our backup settings are set to keep 3 copies, as you can see here: 
![image](https://github.com/AzuraCast/AzuraCast/assets/62389707/55cf7c9f-d0a5-4dca-84a5-04aa99cad651)

Though it does not seem as these are processed accordingly, as we often have to delete the excess backup files, as you can see here:
![image](https://github.com/AzuraCast/AzuraCast/assets/62389707/ee3394e4-1a97-488e-b448-92b2186834c4)

**Comment by BusterNeece** [comment]
@AaronUnmuted If you manually run the `RotateLogs` task, is there any log output?

**Comment by AaronUnmuted** [comment]
Running this from the debug page, it took a while but ran successfully. Though before I ran it manually it looks as though it had never been ran, presume this should run automatically?

**Comment by BusterNeece** [comment]
@AaronUnmuted It certainly should, though I actually did just discover something in another issue (#7101) that meant that if a long-running task was set to happen in the few minutes after another long-running task, the cron task wouldn't let both run at the same time, which could possibly mean that the second task simply _never_ ran. This is updated in the latest Rolling Release, and may fix issues like that.
