### ISSUE TITLE
LetsEncrypt certificate not working without reboot

### ISSUE THREAD

**Issue by mishcazzulani** [AzuraCast/AzuraCast#7105]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.5

### What happened?

I'm adding a new domain to my installation: in system settings -> services I add a new one, click save, then generate certificate. The new certificate will not be loaded unless i restart the whole container.

**Comment by BusterNeece** [comment]
@mishcazzulani This should be fixed in stable releases after 0.19.5.
