### ISSUE TITLE
Content-Security-Policy on web player broken

### ISSUE THREAD

**Issue by elmussol** [AzuraCast/AzuraCast#7108]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.7

### What happened?

Since upgrading to latest stable from previous latest stable we have problems loading the player. I am seeing the following error in my browser console:
```
Content-Security-Policy: The page's settings blocked the loading of a resource at data: ("media-src").
```
Please see the [TopCat Radio](https://topcatradio.eu/) site for a visual. A [separate player](https://radio.elsmussols.net/listen/topcat_radio/radio.mp3) loads fine.

**Comment by BusterNeece** [comment]
@elmussol I think you're running into a rather unusual bug that we're seeing on certain instances with 0.19.7 stable; I believe this is fixed in the latest Rolling Release. Could you update and confirm?

**Comment by elmussol** [comment]
I have updated to Rolling Release #[73d0db4] (2024-05-16 9:46) and all seems good so far. I am canvassing listeners for different platform/browser combos. Thanks @BusterNeece .
