### ISSUE TITLE
Import M3U playlist

### ISSUE THREAD

**Issue by ivanpotylitcyn** [AzuraCast/AzuraCast#711]
**Is your feature request related to a problem? Please describe.**
I can't add songs in playlist using external PLS file. I've exported PLS from Azura to make a test. I did not change exported file, clear playlist in web and try to full it again with exported PLS file. Saving leads to red "File is invalid" message, so import impossible. M3U files work fine, but I've noticed that there is no way to sort songs, they are added in alphabetical order.

**Describe the solution you'd like**
I'd like to load playlist with custom order. Probably using PLS files.

**Describe alternatives you've considered**
Maybe it's possible to make media browser in web like a tree. It will give opportunity to fill up playlist from "one page". Now it's a bit annoying to surf around folders to find a song.

**Additional context**
Even more powerful could be a split window with media browser tree on one side and playlists on the other. So users are able to drag'n'drop media to playlists in one window. It will extremely increase usability in playlist part. (May be I should send this feature in a separate request.)

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38915/import-m3upls-playlists-with-sequential-order
