### ISSUE TITLE
IceCast2 YP question

### ISSUE THREAD

**Issue by mediamagnet** [AzuraCast/AzuraCast#712]
More of a question than a bug, when setting up a mount point to update the YP directory do I need to add the XML for the YP url and all of that?

i.e.
```
<directory>
    <yp-url-timeout>15</yp-url-timeout>
    <yp-url>http://dir.xiph.org/cgi-bin/yp-cgi</yp-url>
</directory>
<genre>Music Video Game Remix </genre>
```

**Comment by SlvrEagle23** [comment]
@mediamagnet That should be valid, yes. You can specify the custom configuration using either snippets of XML in the exact style you described there (each customized element, all the way up to, but not including, the root) or snippets of JSON that depict the same info.
