### ISSUE TITLE
No Listeners for Non-AutoDJ stations in Dashboard under Average Graph and Overview

### ISSUE THREAD

**Issue by bombelman** [AzuraCast/AzuraCast#7127]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.5 Stable

### What happened?

I have several AutoDJ stations that show listener quantity live in the Dashboard on the Average Listeners graph and in numbers onder Station Overview.
However non-AutoDJ station that only have live streaming from a live source don't show these numbers.
I'm using dnas.

Also, on the station profile page it shows as "Offline", but below under "Streams" the numbers do show.
Is this normal behavior for live stations ?

**Comment by renatopinto89** [comment]
That usually happens when the DJ/Live Streamer doesn´t send metadata over to the stream.
Since there´s no metadata, the stream itself will output sound but doesn´t have anything to trigger an update to the front-end

**Comment by bombelman** [comment]
That indeed did the trick ! There was indeed no metadata being sent.
Some hardware streaming devices don't have that feature, or the stations don't use that feature at all.

I managed to send a single metadata update and it works great now !
Is there a way this could be triggered without the metadata ?
Should I suggest this as a feature update ?
