### ISSUE TITLE
Extra directory created during file move on Media page.

### ISSUE THREAD

**Issue by bombelman** [AzuraCast/AzuraCast#7128]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.5 Stable

### What happened?

Example directory structure:

Home/Dance/Track01.mp3
Home/Dance/Track02.mp3
Home/Techno/

When I select Track02.mp3 and move it to Techno, this is what I get as result:

Home/Dance/Track01.mp3
Home/Techno/Dance/Track02.mp3

The track is indeed moved to Techno, but placed in a subfolder "Dance" where it was previously in.

Is this a bug or normal behavior ?

**Comment by Vaalyn** [comment]
This was indeed a bug and was fixed via https://github.com/AzuraCast/AzuraCast/commit/3a33a59980745454657cd129d335a4b3cf891d0d 

The latest stable version `0.20.0` includes this fix
