### ISSUE TITLE
Playlist does not follow the position of the files that I have established.

### ISSUE THREAD

**Issue by Gi252** [AzuraCast/AzuraCast#7133]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

V.0.20

### What happened?

The playlists I create are all made up of orgg files which have a specific order of broadcast on air. However, I notice that my playlists are broadcast in an order that was not mine initially.
However, I chose the sequential option (should I - while I'm thinking about it - also choose "advanced" and "consider the playlist as a single track"?).

So I don't understand how this could be possible. If I create a playlist, how can the system not deal with that??
It's not a question of file metadata, because positioning a title in a ranking has nothing to do with the name of the titles or their CD track numbers, right.

It is essential for me that the order of the playlist is respected.

I have the liquidsoap logs but the number of lines is colossal, so I don't think I can display them here ?

**Comment by SpeedyCharly** [comment]
Experienced the same problem...can't wait for an answer...

**Comment by BusterNeece** [comment]
@Gi252 If you click "More" next to the playlist and click "Reorder", are the tracks all in the correct order in that popup?

**Comment by Gi252** [comment]
Well, I reinstalled Azuracast and currently have the version :  pour information, Busterneece :
I would like to point out that everything I am going to describe to you in anomalies also appeared on the stable version.

Description :
So, wanting to start from scratch with the files, I started by deleting all of these files present in your program. There was an anomaly when I got to the last page: 
![delete](https://github.com/AzuraCast/AzuraCast/assets/169987975/5eb29e51-2df7-45d3-b7c8-7df12bc9c842)


This anomaly disappeared when I refreshed the browser page since I was able to delete the last page of audio files present and completely empty azuracast.
Then, I uploaded a first series of .Ogg files with this order of play: 
![good_order_files](https://github.com/AzuraCast/AzuraCast/assets/169987975/a4b7bc1c-04d7-46ce-8f3b-1d543873fe28)

Then, a second.
As you can see on the screenshot of the "music files" page, the files are classified according to track number (01,02,03, etc.), which is logical. Then, I assigned all these files to a playlist called "secular baroque".

Then, I went to playlist reordering and this is the order of the files as it appeared: 
![playlist](https://github.com/AzuraCast/AzuraCast/assets/169987975/d890f5a9-f002-4f51-901f-03fccd222a72)


As you can see, there are parts here and parts there. The order is disparate.

So, imagine all the work to be done to reorganize the playback tracks in the right order, especially since, as I said in a post, the reorganization window only shows 7 or 8 drag and drop titles and you have to constantly scroll the page or drag and drop. It is not practical !

**Comment by SpeedyCharly** [comment]
What needs be done here is figure out which metadata item Azuracast uses to sort media files in 'Media' folders and 'Playlist'. Logically, both should be the same, but it seems it isn't the case - Media folders appears to be sorted by filename while playlists are sorted by title...  Might be an idea to standardize this to make results predictable in all cases.

**Comment by Gi252** [comment]
Yes, an interesting question, but then, what a lot of work to do!

**Comment by BusterNeece** [comment]
So basically I think the issue here is that when you select a lot of tracks to be added to a playlist, i.e. all the tracks in a folder, it isn't sorting that selection necessarily in a way that matches the order you're seeing on the screen, so it appears that AzuraCast isn't following the proper order of the playlists, when really it's following the order it knows (which is the order in the "Reorder Playlists" window).

That's certainly something we can improve upon, even if it's just a matter of making sure that the "selected files" list we send when setting playlists is sorted the same way as our display table.

In the meantime though, it's likely the only workaround is just to manually reorganize the tracks using the "Reorder" feature. The tracks should be both resortable with the buttons and draggable overall.

**Comment by SpeedyCharly** [comment]
Exactly Buster, thanks.  A solution might be to display playlist content in a grid, much like Windows Explorer does which would give the ability to sort by filename or by title simply by clicking on the column header...

**Comment by Gi252** [comment]
Isn't there a way to make Azura do, for example, that all the songs that are included in a playlist would be added only and exclusively at the end of the playlist?

**Comment by Gi252** [comment]
> Isn't there a way to make Azura do, for example, that all the songs that are included in a playlist would be added only and exclusively at the end of the playlist?

yes, this is very interesting too.

**Comment by SpeedyCharly** [comment]
> I was wondering if there was not also the possibility of forcing Azuracast to systematically put any new files added at the end of the playlist.

Not sure that can be done - files aren't uploaded sequentially to the server, but in order of size mostly...

**Comment by Gi252** [comment]
Loaded into the server at the time of upload you mean? well... no! I don't think so, they are loaded in track order!

**Comment by FastJack2** [comment]
Had the same problem and "solved" it by exporting the playlist by m3u, which then contains an order, different than the one displayed when hitting the "reorder" button. after that i used a text editor to sort the tracks in the m3u, cleared the playlist and imported it from the newly sorted m3u again... now things play in the order i want... but theres definitely some bug in the first import of the playlist...

**Comment by SpeedyCharly** [comment]
All of the workarounds put forth are ok for playlists of no more than 20-30 media files - more than that it becomes a tedious, lengthy job. Files should automatically sort by name in the playlist.  Then adding a leading number to the name before uploading would sort them properly...

**Comment by FastJack2** [comment]
> All of the workarounds put forth are ok for playlists of no more than 20-30 media files - more than that it becomes a tedious, lengthy job. Files in the playlist should automatically sort by name. Then adding a leading number to the name before uploading would sort them properly...

Well, no... I have a strong directory structure \sampler\[name]\[vol]\[CD#]\
And all the tracks are named with the pattern:
[track#] - [artist] - [name]
But the sorting is wrong after selecting them from media dir.. Well .. it's right in "reorder" but wrong in "queue"....

And if you got a sophisticated text editor it's just a matter of seconds with some sort of "sort lines" command... I got 1147 tracks in that particular playlist, so manual sorting is absolutely no option ;)
