### ISSUE TITLE
Stats showing 1 listener after last update

### ISSUE THREAD

**Issue by Tolarion** [AzuraCast/AzuraCast#715]
Traditional installation method
Update done with no errors of exceptions but after first update stats is showing 1 listener all the time.
But listeners list on the geomap is showing properly.
Current version is v0.8.2-2018.04 Beta

Screenshots included
![screenshot_2](https://user-images.githubusercontent.com/8142146/44002934-964732f0-9e53-11e8-986b-6659ce2362a0.jpg)
![screenshot_3](https://user-images.githubusercontent.com/8142146/44002935-9662f2f6-9e53-11e8-8b85-76b94e70b791.jpg)
![screenshot_4](https://user-images.githubusercontent.com/8142146/44002936-96bf72ba-9e53-11e8-940e-54705cd44d6a.jpg)
![screenshot_1](https://user-images.githubusercontent.com/8142146/44002937-96db0a34-9e53-11e8-8092-62436e2d29f5.jpg)

**Comment by SlvrEagle23** [comment]
@Tolarion How recently did you update? Your statistics seem to be showing 1 listener for quite a while now; there have been several significant code changes in the last few weeks, so you should try updating again to the very latest version and seeing if this persists.

**Comment by Tolarion** [comment]
@SlvrEagle23 Hi! Updating once per week after problem appears. Was hoping the problem wold be solved during update but no luck. The nearest one was just b4 creating this topic.

**Comment by SlvrEagle23** [comment]
@Tolarion I'm not sure what's causing this problem, but I definitely want to look into it and fix it, especially in case other users are experiencing the same issue.

In this case, that will likely mean taking a look at your specific AzuraCast installation. I don't have any remote way of debugging AzuraCast instances as they have no "phone home" or remote diagnostic tools installed, so I would have to look directly at your instance to diagnose the issue further.

If you're comfortable letting me know where your AzuraCast installation is located out on the web, you can find me on Keybase under the username SlvrEagle23, or send me an e-mail at buster@busterneece.com with your station details.

**Comment by SlvrEagle23** [comment]
After further investigation, I identified an issue with how unique listeners were calculated on Icecast. This led to the statistics always reporting 1 listener on Icecast 2 stations. This has apparently been an issue for quite a while, since the more detailed listener reporting tools have been available.

While I'm a little surprised that the issue wasn't reported until now, a big thanks to @Tolarion for reporting it with such detail and allowing it to be fixed very quickly.
