### ISSUE TITLE
API page is missing

### ISSUE THREAD

**Issue by dagors** [AzuraCast/AzuraCast#716]
When trying to access the site http://www.azuracast.com/api/ returns error 404.

![azuracasapierror](https://user-images.githubusercontent.com/39383393/44047915-24783b16-9eed-11e8-862c-743d53101b4c.png)

**Comment by SlvrEagle23** [comment]
@dagors I've updated the documentation to fix the link. The proper URL in this case is http://www.azuracast.com/api/index.html
