### ISSUE TITLE
"Interrupt other songs to play at scheduled time." not working for any playlist or ToTH Jingle

### ISSUE THREAD

**Issue by t0mtaylor** [AzuraCast/AzuraCast#7162]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #4368a9f (2024-05-29 0:14) • Docker • PHP 8.3

### What happened?

Given you set a playlist to play either a media item at a "scheduled time" or "once per hour",
And when you set "Interrupt other songs to play at scheduled time." and "Only play one track at scheduled time."
Then you would expect the playlist to interrupt and play at the set time

Unfortunately this is not the case, and the current output is not interrupted at the requested time

Jingles are also playing 2 together again when you set a Jingle playlist to play 1 single  jingle every 2 tracks (Once per x Songs and Only play one track at scheduled time.)

**Comment by wegGehamstert** [comment]
It does work for me. I don't really see what the error could be on your case

**Comment by t0mtaylor** [comment]
> It does work for me. I don't really see what the error could be on your case

helpful 😆 but if i look into the logs, why are these telnet calls from the php files failing within the docker container?

`
[2024-06-02T10:05:00.427478+00:00] AzuraCast.ERROR: App\Exception: Telnet failure: No such file or directory (2) (uncaught exception) at /var/azuracast/www/src/Radio/Backend/Liquidsoap.php line 84 while running console command azuracast:sync:task {"exception":"[object] (App\\Exception(code: 0): Telnet failure: No such file or directory (2) at /var/azuracast/www/src/Radio/Backend/Liquidsoap.php:84)"} {"task":"QueueInterruptingTracks"}
[2024-06-02T10:05:00.428623+00:00] AzuraCast.WARNING: Console command azuracast:sync:task exited with error code 1. [] {"task":"QueueInterruptingTracks"}
[2024-06-02T10:06:00.393815+00:00] AzuraCast.ERROR: App\Exception: Telnet failure: No such file or directory (2) (uncaught exception) at /var/azuracast/www/src/Radio/Backend/Liquidsoap.php line 84 while running console command azuracast:sync:task {"exception":"[object] (App\\Exception(code: 0): Telnet failure: No such file or directory (2) at /var/azuracast/www/src/Radio/Backend/Liquidsoap.php:84)"} {"task":"QueueInterruptingTracks"}
[2024-06-02T10:06:00.395019+00:00] AzuraCast.WARNING: Console command azuracast:sync:task exited with error code 1. [] {"task":"QueueInterruptingTracks"}
[2024-06-02T10:06:02.250701+00:00] AzuraCast.ERROR: Handling "App\Message\ProcessCoverArtMessage" failed: Unable to decode input {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":124,"code":0} []
[2024-06-02T10:07:00.393634+00:00] AzuraCast.ERROR: App\Exception: Telnet failure: No such file or directory (2) (uncaught exception) at /var/azuracast/www/src/Radio/Backend/Liquidsoap.php line 84 while running console command azuracast:sync:task {"exception":"[object] (App\\Exception(code: 0): Telnet failure: No such file or directory (2) at /var/azuracast/www/src/Radio/Backend/Liquidsoap.php:84)"} {"task":"QueueInterruptingTracks"}
`

This is a fresh docker install with the latest version ( just updated to latest release ) - also have the same issue with stable release channel

**Comment by t0mtaylor** [comment]
Ok i think i solved the problem! Pesky Permissions Issues! Due to changing permissions for external volumes to load correctly

I deleted the two offending volumes (because all the settings are stored in the DB) 

```
azuracast_station_data
azuracast_www_vendor
```

Then i did an upgrade to resinstall those volumes fresh and its fixed the liquidsoap issues, along with the scheduling ToTH, etc :)

Maybe we should have an option to do a refresh of these 2 volumes during an update (default no) to ensure they are updated and avoid having these permissions issues

**Comment by BenMauriceKeil** [comment]
okay, and how exactly do I delete the directories and especially where do I have to do that, especially databases I don't really know much about

**Comment by t0mtaylor** [comment]
@BenMauriceKeil you should delete the docker volumes and follow the details as per this comment https://github.com/AzuraCast/AzuraCast/issues/7162#issuecomment-2143803893

**Comment by BenMauriceKeil** [comment]
> @BenMauriceKeil you should delete the docker volumes and follow the details as per this comment [#7162 (comment)](https://github.com/AzuraCast/AzuraCast/issues/7162#issuecomment-2143803893)

That helps me a lot too, I can't do anything with the things listed here.

azuracast_station_data
azuracast_www_vendor

**Comment by t0mtaylor** [comment]
> > @BenMauriceKeil you should delete the docker volumes and follow the details as per this comment [#7162 (comment)](https://github.com/AzuraCast/AzuraCast/issues/7162#issuecomment-2143803893)
> 
> That helps me a lot too, I can't do anything with the things listed here.
> 
> azuracast_station_data azuracast_www_vendor

Delete the volumes when the containers are not running 👍

**Comment by BusterNeece** [comment]
@t0mtaylor Please do not advise the general public to delete important volumes on their Docker installations.

You have been in several GitHub issues that seem to be completely unrelated to this, telling users that deleting important Docker volumes is the solution to their problems. This is not only likely not the cause of their problems, but it's quite possibly exposing them to danger. Please do not continue posting this advice on every issue.

**Comment by BenMauriceKeil** [comment]
> @t0mtaylor Please do not advise the general public to delete important volumes on their Docker installations.
> 
> You have been in several GitHub issues that seem to be completely unrelated to this, telling users that deleting important Docker volumes is the solution to their problems. This is not only likely not the cause of their problems, but it's quite possibly exposing them to danger. Please do not continue posting this advice on every issue.

Hi, unfortunately I still have the error, the error was partially gone after the last update and at some point the station just restarted and today I have the error with the noise and the jingle again, how can I fix it, you can't run a radio station like this

**Comment by t0mtaylor** [comment]
> @t0mtaylor Please do not advise the general public to delete important volumes on their Docker installations.
> 
> You have been in several GitHub issues that seem to be completely unrelated to this, telling users that deleting important Docker volumes is the solution to their problems. This is not only likely not the cause of their problems, but it's quite possibly exposing them to danger. Please do not continue posting this advice on every issue.

@BusterNeece Those 2 volumes are rebuilt by information from the database so it is safe - every-time I have this issue or similar after an upgrade, this resolves the problem those users have experienced

It would be better you fix the problem between upgrades of RR (or when the user switches between RR and Stable), than stating my workaround is dangerous 👍

**Comment by BusterNeece** [comment]
@t0mtaylor You are absolutely incorrect in a way that is sincerely dangerous if you're providing advice for users.

You listed two volumes for removal, one being the temp directory and the other being `azuracast_station_data`.

The latter, in default installations, contains the entirety of all media uploaded to _all_ stations that use local storage. The only case where this wouldn't be the case would be if you're using S3 buckets or otherwise remounting the directory in advanced code, both of which represent a minority of users.

And for your information, we do actually clear the temp folder upon every app startup: https://github.com/AzuraCast/AzuraCast/blob/main/util/docker/web/startup_scripts/10_clear_temp.sh

I'm not going to debate this with you further. Your advice was actively dangerous in a majority of installations, so I deleted it and advised you to stop posting it. Continuing to do so will result in a permanent ban.
