### ISSUE TITLE
Access denied HTML shown when API key has no permission

### ISSUE THREAD

**Issue by Sella-GH** [AzuraCast/AzuraCast#7182]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#5bbd484 (2024-06-06 6:21)

### What happened?

It could be debatable if this is a bug or not but for me who works with the API it's a... strange thing I don't understand.

I'd prefer to get a 401 or 403 instead of a 200 with an HTML body telling me "You do not have access to this", because then I get exceptions all along when the parsing of the JSON data doesn't works because it's HTML.

However I do understand the intention to fuzz around with bots when sending out the 200's but for valid cases like when using the API productive it's not that helpful.

**Comment by Sella-GH** [comment]
I have to correct myself here since it's only happening on some portions of the service:
- GET `/station/id/fallback`
- GET `/station/id/mount/id/intro`
- GET `/station/{station_id}/podcast/{podcast_id}/art`
- GET `/station/{station_id}/podcast/{podcast_id}/episode/{episode_id}/art`
- GET `/station/{station_id}/podcast/{podcast_id}/episode/{episode_id}/media`

**Comment by BusterNeece** [comment]
Definitely not a bot fuzzing thing, just a legitimate bug that these are in the "public API" route group and that group doesn't properly throw exceptions as JSON across the board. Will push a fix up.
