### ISSUE TITLE
Have Turbo mode env option for radio streams quick start, to reduce startup lag and cpu spike

### ISSUE THREAD

**Issue by t0mtaylor** [AzuraCast/AzuraCast#7185]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Affects Latest and Stable

### What happened?

Have Turbo mode env option for radio streams quick start, to reduce startup lag and cpu spike

During startup, it is too slow to start streaming the station after you update or simply restart the docker container, with a massive CPU spike

Even on a system with 12 cores and 64gb of ram, the massive resource spike always slows starting up and streaming of all stations - even just one station!

Looking into the startup logs, Azuracast is trying to scan playlists and files, which seems unnecessary at startup!

I propose a "Turbo" mode within the env file, which would force Azuracast to "Quick Start" the radio streams as a priority without the massive CPU Spike with the other lower priority services and actions - bit like a feature flag

The scheduled tasks (and any others not a priority to start the stream) should also start 5 minutes after the station starts, or the user has the option to manually trigger the jobs via the GUI if required, although for Turbo mode this is not essential

**Comment by BusterNeece** [comment]
@t0mtaylor Much of the startup stuff that we do isn't really something you can skip on. For example, the initial portion is flushing caches, clearing temp files, ensuring the database is on the latest version and migrated, etc...and those don't take too terrifically long but are very important.

I believe the slowdown you're referring to specifically comes from the initial CPU burden of either analyzing files for ReplayGain or for AutoCue. Both of those will, if there isn't any metadata already written to the file, basically analyze any file that _could_, in theory, play right at that moment; that includes at least one file from every playlist you have and the first file that's cued up for playback by the AutoDJ.

In that regard, there's definitely room for improvement, and it's a very high priority for us right now to do that. We have to make some "under the hood" changes to facilitate it, but we intend to add the ability for you to set a "save metadata" mode, enabled by default if you enable either ReplayGain or AutoCue, where the special metadata used by those processes is automatically written to the file (and/or to our metadata database) as it's uploaded (or during routine reprocessing), which would then be referenced by those tools upon startup, all but removing the initial CPU load and shifting it to a much more gradual process that happens only when media is uploaded or reprocessed.

**Comment by t0mtaylor** [comment]
Thank you @BusterNeece 

The latest PR (https://github.com/AzuraCast/AzuraCast/pull/7189) with the new feature `Always Write Playlists to Liquidsoap` when disabled has improved the startup, but this has made me think of another option to improve autocue further

Please see my comment here: https://github.com/AzuraCast/AzuraCast/pull/7189#issuecomment-2161216001 and Issue: https://github.com/AzuraCast/AzuraCast/issues/7193

**Comment by BusterNeece** [comment]
I think the "Always Write Playlists to Liquidsoap" setting is about the best we can currently do. The rest would depend on changes internal to the scheduling and operation of Liquidsoap itself. We're also working under the hood on caching the tags associated with AutoCue in our database, but this will be a larger process with more work involved.

**Comment by t0mtaylor** [comment]
> I think the "Always Write Playlists to Liquidsoap" setting is about the best we can currently do. The rest would depend on changes internal to the scheduling and operation of Liquidsoap itself. We're also working under the hood on caching the tags associated with AutoCue in our database, but this will be a larger process with more work involved.

Sounds good @BusterNeece, hopefully this will allow for `turbo mode` and even quicker startup times
