### ISSUE TITLE
Update crash with repositories no authentificates

### ISSUE THREAD

**Issue by Likeandfeel** [AzuraCast/AzuraCast#719]
**Installation method**
Traditionnal method

**Host OS (for Docker installations)**
Ubuntu 16.04 server and desktop (local and VPS on OVH)

**Describe the bug**
When we have a repositories without authentification, and we launch update script. Script failed as you can see on this log

TASK [init : Update apt] *************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:The repository 'http://ppa.launchpad.net/ecometrica/servers/ubuntu xenial Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details., E:Impossible de récupérer http://ppa.launchpad.net/ecometrica/servers/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found, E:Le téléchargement de quelques fichiers d'index a échoué, ils ont été ignorés, ou les anciens ont été utilisés à la place."}

PLAY RECAP ***************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1   

**To Reproduce**
first add unathentificated source by exemple 
sudo add-apt-repository ppa:ecometrica/servers 
sudo apt-get update && apt-get upgrade
cd /var/azuracast/www
sudo chmod a+x update.sh
sudo ./update.sh

**Expected behavior**
If some repositories are not authentificated, pass on and let script update azucast instancy

**Comment by SlvrEagle23** [comment]
@Likeandfeel This appears to be caused entirely by a PPA that is not included in AzuraCast itself. As I am a solo developer working on this fairly large-scale project (with two very distinct installation styles), it's impossible for me to account for every possible interaction with third-party software that may be running on your given server. This is why I explicitly say in all documentation that AzuraCast should be installed on a "clean" VPS if you're installing using the traditional route. The Docker installation method doesn't suffer from these dependency problems, as its software is self-contained and isolated from the rest of the OS.
