### ISSUE TITLE
Problem recording live

### ISSUE THREAD

**Issue by nexion63** [AzuraCast/AzuraCast#7192]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.20.1

### What happened?

Hi there!

I have a problem with the recordings of the live broadcasts. 
Basically, we use a software to record 24/24h the radio, I wanted to test this part of AzuraCast to make a complement in case the software bug but I notice that it does not work properly.

AzuraCast managed to record 2 out of 5 shows that have been broadcast live since Sunday. I put the storage on an FTP that is on my NAS, I checked via the FTP account if it still manages to connect and access the folder, which is still good at the moment.

I don't understand what's wrong, do you have a solution for me?

Thanks

**Comment by keybrdist** [comment]
We are having the same issue. AzuraCast seems to not always record the live shows. I'm uncertain of the cause.  Our storage is S3.

**Comment by nexion63** [comment]
@keybrdist I'm not the only one with this problem.

What software do you use to record in the meantime?

**Comment by keybrdist** [comment]
The issue persists for us.. not sure what the cause is..
