### ISSUE TITLE
Introduce an `Autocue on demand` to improve performance & compliment `Always Write Playlists to Liquidsoap` disabled

### ISSUE THREAD

**Issue by t0mtaylor** [AzuraCast/AzuraCast#7193]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #117f4cb (2024-06-10 9:21) • Docker • PHP 8.3

### What happened?

Introduce an `Autocue on demand` to improve performance & compliment `Always Write Playlists to Liquidsoap` disabled

Since PR https://github.com/AzuraCast/AzuraCast/pull/7189 has been merged, it has introduced a performance improvement with the new option `Always Write Playlists to Liquidsoap` is disabled

However as per my comment within the PR (https://github.com/AzuraCast/AzuraCast/pull/7189#issuecomment-2161216001), Autocue is still processing playlists when they are not required at the time or in the next hour

If we can introduce an `Autocue on demand` option, which enabled only forces up and coming playlists or ones scheduled at the current time to be processed on startup or next - this could also allow for the `Always Write Playlists to Liquidsoap` to be re-enabled as it only processes and writes those files on demand and up next

This would improve startup performance further for all stations and large operations, and also provide playlists updated before they are aired, depending on the scheduled job which would now have to run (potential trade off but less work to do, just more frequent in processing which should be fine and without drama)

> `station_1_backend stdout | 2024/06/11 17:48:50 [autocue.cue_file:3] Now autocueing: filepath`
> 
> I noticed at the startup there was still alot of `autocueing` for playlists **not even required now**, for example:- I would have expected only playlists required now or the next hour to be processed (for Tuesday Evening) and not processing playlists scheduled for Tuesday Morning or the following Monday (which was yesterday in the 7 day week!)
> 
> `Autocue on demand` could be a further enhancement using the available scheduling information of the playlists to compliment `Always Write Playlists to Liquidsoap` in disabled mode for the performance improvements when Autocue is enabled. (currently available via the RR release)

### Relevant log output

```shell
`station_1_backend stdout | 2024/06/11 17:48:50 [autocue.cue_file:3] Now autocueing: filepath`
```

**Comment by BusterNeece** [comment]
This wouldn't be something we could implement on AzuraCast's side. It would have to be implemented by Liquidsoap, and would likely require a pretty dramatic change to their scheduler to accomplish it.

I'd recommend creating an issue over on https://github.com/savonet/liquidsoap to float the idea, though. I know it's already been discussed as part of the AutoCue work.

**Comment by t0mtaylor** [comment]
Just a quick update - I got around this issue with my own mods to autocue so I can process large files outside of azuracast - then azuracast ignores regenerating the tags as they already exist - more here: https://github.com/AzuraCast/AzuraCast/issues/7356#issuecomment-2284682566
