### ISSUE TITLE
Banned IP's not banned

### ISSUE THREAD

**Issue by bombelman** [AzuraCast/AzuraCast#7194]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.20.1 Stable

### What happened?

I added 2 ip's to the ban list, they are also in the sc_serv.ban file, however the connections from these ip's are not banned blocked.... How is that ?

![Screenshot 2024-06-11 at 2 46 16 PM](https://github.com/AzuraCast/AzuraCast/assets/107536852/39832928-7b8b-435c-897d-aba0f1963004)
![Screenshot 2024-06-11 at 2 46 35 PM](https://github.com/AzuraCast/AzuraCast/assets/107536852/47983bca-35f5-4a91-8155-814dffca52fe)

**Comment by handris** [comment]
Hi, please try to reload/restart after input IP.

**Comment by bombelman** [comment]
upon entering the IP's, it already requested a restart, and I restarted 1 more time after that, so in total 2 restarts since adding the IP's.

**Comment by bombelman** [comment]
restarted again. in the log it just shows "client connected" for those IP's..... 
in the SC config the sc_serv.ban file is listed.

**Comment by bombelman** [comment]
still wondering, does anyone have an idea?

I need to be able to block IPs, it's not working at all...

**Comment by bombelman** [comment]
when using DNAS, the IP's added in AzuraCast are not banned or added to the DNAS ban list.
When doing this, the broadcast needs to restart. However nothing happens when doing this.

However a workaround is, if you log into the DNAS you can block the IP there and it gets added to the banlist without the servers requiring a restart.
