### ISSUE TITLE
Order audios per year

### ISSUE THREAD

**Issue by multi023** [AzuraCast/AzuraCast#720]
Hello,

For me it would be very interesting to be able to add the option to add in "Files" the option of being able to sort them by Years.

In this way, if the label identifies the year, the lists could be created more easily, if we want to separate them by decades or by specific years.

![year](https://user-images.githubusercontent.com/20141463/44170574-0dd14a00-a0d8-11e8-9696-777949f3a658.jpg)

Thank you very much for taking it into account.

Regards,

**Comment by SlvrEagle23** [comment]
@multi023 This is actually possible right now using the Custom Fields feature. If you visit the AzuraCast administration page and create a new custom field labeled "Year", you can specify it on all of your files, and then it will automatically become a searchable and selectable field when viewing the station media.
