### ISSUE TITLE
Ignore dot files and empty/invalid audio files to stop playlist implosion

### ISSUE THREAD

**Issue by t0mtaylor** [AzuraCast/AzuraCast#7201]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #117f4cb (2024-06-10 9:21) • Docker • PHP 8.3

### What happened?

Ignore dot files and empty/invalid audio files to stop playlist implosion

It would be good if we can ignore these invalid files, otherwise playlist and music folder scanning doesn't seem to work as expected and errors out alot

### Relevant log output

```shell
cron stdout | time="2024-06-14T12:26:00Z" level=info msg="[2024-06-14T12:26:00.758468+00:00] AzuraCast.ERROR: League\\Flysystem\\UnableToListContents: Unable to list contents for '/', deep listing  Reason: SplFileInfo::getMTime(): stat failed for /invalid-dodgy-file.mp3 (uncaught exception) at /var/azuracast/www/vendor/league/flysystem/src/UnableToListContents.php line 17 while running console command `azuracast:sync:task` {\"exception\":\"[object] (League\\\\Flysystem\\\\UnableToListContents(code: 0): Unable to list contents for '/', deep listing\\n\\nReason: SplFileInfo::getMTime(): stat failed for /invalid-dodgy-file.mp3 at /var/azuracast/www/vendor/league/flysystem/src/UnableToListContents.php:17)\\n[previous exception] [object] (RuntimeException(code: 0): SplFileInfo::getMTime(): stat failed for /invalid-dodgy-file.mp3 at /var/azuracast/www/vendor/league/flysystem-local/LocalFilesystemAdapter.php:225)\"} {\"task\":\"CheckMediaTask\"}" channel=stderr iteration=4057 job.command="azuracast_cli azuracast:sync:run" job.position=0 job.schedule="0 * * * * * *"
```

**Comment by Vaalyn** [comment]
🤔 Dot files are already ignored [here](https://github.com/AzuraCast/AzuraCast/blob/main/backend/src/Sync/Task/CheckMediaTask.php#L95) when iterating over the filesystem:

<img width="1000" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/826c27a9-0a7e-47ca-adfb-9e83423c3d89">

And each file this returned is also checked to see if it would be processable [here](https://github.com/AzuraCast/AzuraCast/blob/main/backend/src/Sync/Task/CheckMediaTask.php#L111-L138) via the mime type of the file:

<img width="796" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/0ecff1d7-15ec-4cae-8bf1-beccd0c084da">

The error message says the filesystem library itself can't retrieve the `modified time` of a file:
```
League\Flysystem\UnableToListContents(code: 0): Unable to list contents for '/', deep listing
Reason: SplFileInfo::getMTime(): stat failed for /invalid-dodgy-file.mp3
```

Since this seems to be a local file system (the error message includes the `LocalFilesystemAdapter`) I'd guess there is a permission problem on the file/files it is failing on.

Could you check the permissions of those files it is failing on?

**Comment by Vaalyn** [comment]
@t0mtaylor sorry but no it does **not** try to process files starting with a `.` 😅 

I just did a fresh installation and uploaded a directory containing a `.DS_Store` file and ran the `CheckMediaTask`. It did only see the 13 actual media files and completely ignored the dot file.

I then added a "write the array of files from the filesystem iterator to a .json file" to the `CheckMediaTask` and ran it again, still the iterator does only return the actual media files excluding the dot file.

See the following screenshots and the json output.

Regarding skipping empty files from being tried to process, I just sent in a PR to add that.

<img width="1010" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/28fd406b-5fd5-4f0e-8fa5-0b58eb76ab0b">

<img width="594" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/db4f199d-19aa-4280-b9d6-80d4a4280f34">

<img width="943" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/0c7fec02-3405-4b2a-b7bd-0b77877756eb">

```json
[
    {
        "type": "file",
        "path": "MLP Movie Soundtrack\/12 - I'll Be Around.mp3",
        "file_size": 7463701,
        "visibility": "public",
        "last_modified": 1718639211,
        "mime_type": null,
        "extra_metadata": []
    },
    {
        "type": "file",
        "path": "MLP Movie Soundtrack\/08 - Thank You For Being A Friend.mp3",
        "file_size": 6711237,
        "visibility": "public",
        "last_modified": 1718639211,
        "mime_type": null,
        "extra_metadata": []
    },
    {
        "type": "file",
        "path": "MLP Movie Soundtrack\/01 - We Got This Together.mp3",
        "file_size": 7544713,
        "visibility": "public",
        "last_modified": 1718639211,
        "mime_type": null,
        "extra_metadata": []
    },
    {
        "type": "file",
        "path": "MLP Movie Soundtrack\/07 - Off To See The World.mp3",
        "file_size": 6399539,
        "visibility": "public",
        "last_modified": 1718639211,
        "mime_type": null,
        "extra_metadata": []
    },
    {
        "type": "file",
        "path": "MLP Movie Soundtrack\/13 - Neighsayer.mp3",
        "file_size": 6191403,
        "visibility": "public",
        "last_modified": 1718639211,
        "mime_type": null,
        "extra_metadata": []
    },
    {
        "type": "file",
        "path": "MLP Movie Soundtrack\/10 - I'll Chase The Sky.mp3",
        "file_size": 5832867,
        "visibility": "public",
        "last_modified": 1718639211,
        "mime_type": null,
        "extra_metadata": []
    },
    {
        "type": "file",
        "path": "MLP Movie Soundtrack\/05 - Open Up Your Eyes.mp3",
        "file_size": 6783127,
        "visibility": "public",
        "last_modified": 1718639211,
        "mime_type": null,
        "extra_metadata": []
    },
    {
        "type": "file",
        "path": "MLP Movie Soundtrack\/06 - Rainbow (From The Original Motion Picture Soundtrack 'My Little Pony_ The Movie').mp3",
        "file_size": 6724014,
        "visibility": "public",
        "last_modified": 1718639211,
        "mime_type": null,
        "extra_metadata": []
    },
    {
        "type": "file",
        "path": "MLP Movie Soundtrack\/03 - Time To Be Awesome.mp3",
        "file_size": 6081970,
        "visibility": "public",
        "last_modified": 1718639211,
        "mime_type": null,
        "extra_metadata": []
    },
    {
        "type": "file",
        "path": "MLP Movie Soundtrack\/11 - No Better Feelin'.mp3",
        "file_size": 5922410,
        "visibility": "public",
        "last_modified": 1718639211,
        "mime_type": null,
        "extra_metadata": []
    },
    {
        "type": "file",
        "path": "MLP Movie Soundtrack\/04 - One Small Thing.mp3",
        "file_size": 5798233,
        "visibility": "public",
        "last_modified": 1718639211,
        "mime_type": null,
        "extra_metadata": []
    },
    {
        "type": "file",
        "path": "MLP Movie Soundtrack\/02 - I'm The Friend You Need.mp3",
        "file_size": 4519682,
        "visibility": "public",
        "last_modified": 1718639211,
        "mime_type": null,
        "extra_metadata": []
    },
    {
        "type": "file",
        "path": "MLP Movie Soundtrack\/09 - Can You Feel It.mp3",
        "file_size": 5886126,
        "visibility": "public",
        "last_modified": 1718639211,
        "mime_type": null,
        "extra_metadata": []
    }
]
```

**Comment by t0mtaylor** [comment]
@Vaalyn Awesome work on the empty files fix 👍  https://github.com/AzuraCast/AzuraCast/pull/7208

I'll retest the latest RR my end (regarding the dot file issue), I may have been on an older build - good to see the changes are working ❤️
