### ISSUE TITLE
Podcasts not being saved in backups

### ISSUE THREAD

**Issue by punyauk** [AzuraCast/AzuraCast#7202]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #b25a4b9 (2024-06-12 2:04)

### What happened?

On restoring a full backup (created by running ./docker.sh backup) none of the podcasts are there. Inspecting the backup zip file it only shows music media.

**Comment by Vaalyn** [comment]
From a quick look into the `BackupCommand` I think the podcasts are not yet added to the backup process.
I've flagged this as an enhancement since this should definitely be added.

**Comment by renatopinto89** [comment]
Also, the custom branding assets aren't included in the backup as well
