### ISSUE TITLE
AutoDJ Service Not Running Liquidsoap

### ISSUE THREAD

**Issue by masoudgb** [AzuraCast/AzuraCast#7203]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Hello, thank you for this project

Broadcasting Service Not Running
Icecast

AutoDJ Service Not Running
Liquidsoap

**Comment by Moonbase59** [comment]
And now? Shall we get our crystal balls? Mine is broken.

_(Hint: The issue template isn’t there for nothing. Please fill in enough data for anyone to help.)_
