### ISSUE TITLE
AutoCue Update (yesterday)

### ISSUE THREAD

**Issue by DAMaia1989** [AzuraCast/AzuraCast#7204]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #7f99b44

### What happened?

hi there,
I realized that yesterday there was an update that I think was in the autocue. What happens is that since yesterday the music transitions have a little more space between them and the problem after leaving the livedj was practically solved. now it seems that everything returns to how it was before, still listening to the music that was playing before from live dj.
How can I get Azuracast back before yesterday's update?

**Comment by Moonbase59** [comment]
Re: Autocue.

Yes it know uses the "sustained ending" logic, too, so—depending on your tracks—maybe more endings are kept and not overlayed.

You can adjust the "sustained ending" feature by reducing the "drop" percentage, which will lead to "tighter" overlaying, or switch it of entirely by setting to `0.0`, which will restore the previous behaviour.

In AzuraCast’s _Edit Liquidsoap Configuration_, second input box, just set:
```
settings.autocue.cue_file.sustained_loudness_drop := 60.0  # max. percent drop to be considered sustained
```
to the desired value, and restart broadcasting.

**Comment by wegGehamstert** [comment]
The other thing that you mentioned got already reported:
https://github.com/AzuraCast/AzuraCast/issues/7159

**Comment by DAMaia1989** [comment]
Thanks guys!
I had setting it to 0.0 and right now is working fine. I know the other thing is not related to autocue, but from my standpoint, with this setting, it sounds better whe streamer leave and go back to the autodj

**Comment by Moonbase59** [comment]
No problem, that’s why we always try to be as backwards-compatible as possible while you can _still_ enjoy new features in the rolling releases.

Btw, talked to @RM-FM about this. For Dance-type music, he suggests these settings:
```
settings.autocue.cue_file.sustained_loudness_drop := 40.0
settings.autocue.cue_file.overlay_longtail := -12.0  # extra LU
```
They should give a "tighter" overlap.

**Comment by kotevskimk** [comment]
I updated Azuracast to v0.20.1 Stable and CPU now is 100%.
Nothing changed before, everything was working fine, and CPU was 30-40%.
I have VPS with 8 CPU and 30GB of ram.

**Comment by RM-FM** [comment]
@Moonbase59 @DAMaia1989 we use the above settings for all our stations. Turned out that `sustained_loudness_drop` of `60.0` was a bit too conservative and therefore added the Longtail extra LU correction in too many situations. Therefore we corrrected the default value to `40.0` and in addition changed `overlay_longtail` to `-12.0`. From my perspective, that setting allows a "tight" crossfade point detection like it was before `4.0.0` but still preserves (real) relevant endings like vocals or kind of silent outros.

@Moonbase59 already changed the  `sustained_loudness_drop` default with `4.0.2`. Please take note that `overlay_longtail` has still a default of `-15.0` but not `-12.0`. That shouldn't make a big difference. However, if you would like to keep the transitions tight also for in cases where a "sustained ending" was detected, `-12.0` might help.

**Comment by BornKillaz** [comment]
> No problem, that’s why we always try to be as backwards-compatible as possible while you can _still_ enjoy new features in the rolling releases.
> 
> Btw, talked to @RM-FM about this. For Dance-type music, he suggests these settings:
> ```
> settings.autocue.cue_file.sustained_loudness_drop := 40.0
> settings.autocue.cue_file.overlay_longtail := -12.0  # extra LU
> ```
> They should give a "tighter" overlap.


@Moonbase59, I'm also looking for a more tight overlap... Should that settings be placed on AzuraCast liquidsoap 2nd box?

As you may know, I now parse big audio files with cue_file before it reaches AzuraCast. So, my question in, do we need to make any parameters change with the cue_file pre tagging operation? 

Thank you.

**Comment by Moonbase59** [comment]
> @Moonbase59, I'm also looking for a more tight overlap... Should that settings be placed on AzuraCast liquidsoap 2nd box?

Yes, exactly there, like

> As you may know, I now parse big audio files with cue_file before it reaches AzuraCast. So, my question in, do we need to make any parameters change with the cue_file pre tagging operation?

Yes, you should. Just use the corresponding parameters (see `cue_file --help`). To get the same result as mentioned above, add
```
-d 40 -x -12
```
to the `cue_file` parameters you already use. (You can leave out `-d 40` in version 4.0.2, because it’s already the default in this version.)

**Comment by t0mtaylor** [comment]
This one caught me out for `settings.autocue.cue_file.blankskip` since Autocue was updated on the 12 June

Change the bool to a integer such as `1.5`or `2.5` or remove it - `0.0` is disabled

https://github.com/Moonbase59/autocue/releases/tag/v3.0.0
```

In Liquidsoap/AzuraCast, you can use this setting which defaults to zero (0.00) and means "disabled":
settings.autocue.cue_file.blankskip := 0.0

Don’t forget to change this setting if you used true or false before!

```

We should keep an eye on the release notes before upgrading, or list the breaking changes somewhere central?

**Comment by Moonbase59** [comment]
A float, actually. ;-) And yes, that’s why I started the changelog and noted the breaking changes as such. ;-) Good you caught it, though.

**Comment by t0mtaylor** [comment]
> A float, actually. ;-) And yes, that’s why I started the changelog and noted the breaking changes as such. ;-) Good you caught it, though.

haha I shall wash my mouth out 🧼  (have updated lol) 

I do agree we should look at the change log, although we should all understand the risks when running the Rolling Releases may contain breaking changes 😄 

Latest RR seems to run well! 🚀

**Comment by DAMaia1989** [comment]
hello guys! Once again I noticed that after the last two updates, the music was once again spaced out between the jingles, creating a slightly unpleasant silence.
How could I remedy this situation?
