### ISSUE TITLE
can't get metadata with https thru proxy on vlc player

### ISSUE THREAD

**Issue by djmarcoleiva** [AzuraCast/AzuraCast#721]
hi

i got problems with proxy https, can't get file metadata when i connected from dj account

here is the url without proxy http://sv2.mediaweb.stream:8020/radio.mp3
and here is the url thru proxy https://sv2.mediaweb.stream/radio/8020/radio.mp3

i using a html5 wordpress plugin of need it this info 

how can do for get https with metadata ? 
i see it in another scripts like centova cast, they modify the icecast configuration adding a pair of lines
maybe you can do it that for get https directly from icecast.

thank you for your time. and for this great app

**Comment by SlvrEagle23** [comment]
@djmarcoleiva We have worked on improving our LetsEncrypt integration, and now Icecast serves its pages directly via the same HTTPS certificate used by the main nginx server. This should resolve your issue and allow you to retrieve the station stream directly via HTTPS.
