### ISSUE TITLE
Randomly selected 8080 port problem.

### ISSUE THREAD

**Issue by djmuratb** [AzuraCast/AzuraCast#722]
Traditional Installation
Ubuntu 18.04.1 LTS
Installation Time: Yesterday

**Describe the bug**
Randomly selected 8080 port problem. That's why LiquidSoap does not work. 
We can manually change the port number. But, port number 8080 is selected again in the next station account.

![11111](https://user-images.githubusercontent.com/25807005/44190521-e1491c80-a12f-11e8-8734-b2d663560d38.png)
![2222](https://user-images.githubusercontent.com/25807005/44190527-e60dd080-a12f-11e8-9bf0-2bedecd6ec5d.png)

I had the same problem with my previous server. There is the same problem with the new test server.
You have details of my test server. You can log in and check.

Thanks.

**Comment by SlvrEagle23** [comment]
@djmuratb I looked into it, and indeed there is another service (InfluxDB) that sits on port 8086, which interrupts the 8080 port range and prevents it from working properly.

I've added a special flag to avoid the 8080 range when auto-assigning ports for stations.
