### ISSUE TITLE
Profil bearbeiten nicht auffindbar im UI

### ISSUE THREAD

**Issue by Domky1996** [AzuraCast/AzuraCast#7222]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.20.1.

### What happened?

Kann aktuell mein Profil bei azuracast nicht bearbeiten um z.B. den ReplaiyGain ausschalten zu können. Ich kann nur Profil anzeigen auswählen und sonst nichts. Ich benutze azuracast über die Plattform radiosendungen.net

**Comment by Vaalyn** [comment]
Please contact your provider and ask them to check your accounts permissions.
They probably removed your `Manage Station Profile` / `Sender-Profil verwalten` permission.

**Comment by Domky1996** [comment]
Danke für die schnelle Rückmeldung. Das denke ich auch das da was gelöscht
worden ist in meinem Profil. Leider meldet sich der Provider auf meine
Emails nicht. Könnt ihr das nicht einsehen wenn ich meine Daten euch gebe?

Vaalyn ***@***.***> schrieb am Fr., 21. Juni 2024, 13:18:

**Comment by Vaalyn** [comment]
Da ich davon ausgehe, dass du nur einen "normalen" Benutzer Account hast und keinen Admin/Super-Admin für den gesamten AzuraCast Server, wirst du mit deinem Account nicht die nötigen Berechtigungen haben um in die Administrationskonsole der AzuraCast Installation zu kommen.

Das kann nur dein Hosting Provider erledigen, wenn dieser sich nicht auf deine Anfragen meldet würde ich dir empfehlen einen zuverlässigeren Hoster zu suchen oder direkt auf einem VPS selbst zu hosten.
