### ISSUE TITLE
Sound processing takes very long on large files. Can it be skipped?

### ISSUE THREAD

**Issue by wunschradio** [AzuraCast/AzuraCast#7224]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.20.0 Stable

### What happened?

Hi. This is not a bug, its probably because of my virtual setup, but a concert with a length of more than an hour takes almost 4 minutes until its playable with master_me soundprocessing. Is it possible to skip soundprocessing on large files only? Or set a timeout on soundprocessing itself? Maybe this could be a feature request.

Thanks in advance.

**Comment by Vaalyn** [comment]
It's most likely not master_me that's taking this long but rather AutoCue (if you have it enabled) since master_me is applying filters live on the stream signal thus not doing any pre-processing and AutoCue is pre-processing only.

@Moonbase59 wrote a really neat FAQ about AutoCue that could help: https://github.com/Moonbase59/autocue/blob/master/FAQ.md

For large files like this it would probably best to use AutoCue to manually pre-process the files before uploading to AzuraCast so it doesn't have to do it on-the-fly on startup / playout anymore.

**Comment by wunschradio** [comment]
Thank you. AutoCue is a feature of v20.1 I read and I am on v20.0. But you lead me to the right section while the soundprocessing is live. I disabled ReplayGain and the file plays immediately now. Thanks!

**Comment by Vaalyn** [comment]
Oh, yeah overlooked that.
Yeah, ReplayGain can be quite taxing too, didn't think of that. Great to hear disabling it has worked for you 😄 

Closing the issue as resolved then 👍

**Comment by wunschradio** [comment]
Maybe I could ask for a feature request to use ReplayGain and similar features on a max filesize setting (duration/MB)? Don't know if it might be possible, but this setting could help on smaller server structures. I am still testing though.

Normally DJ sets or concerts that play for a longer while can be streamed without the need of gain or processing because there are no other songs following a different loudness.

**Comment by Vaalyn** [comment]
As far as I'm aware that's currently not possible to define in Liquidsoap, when enabling ReplayGain we only put the [enable_replaygain_metadata](https://www.liquidsoap.info/doc-2.2.4/reference.html#enable_replaygain_metadata) operator into the config which takes care of the computation in the background. I don't think there is a way to configure something like that atm.

For more control and better results I'd recommend to check out AutoCue in newer versions 🙂

**Comment by wunschradio** [comment]
I will. Thank you!

**Comment by LordHelmchen666** [comment]
But you can also pre-tag with replaygain tags the file before uploading. Then LS will take this values and won't calculate. You can use a tool like loudgain or rsgain or even cue_file to do that.

**Comment by wunschradio** [comment]
@LordHelmchen666 thank you... I'll check it out.
But would sound processing not be enough to achieve a constant volume?

**Comment by LordHelmchen666** [comment]
I would say no. If they much different in volume I think you will here it even with sound processing.
