### ISSUE TITLE
Upcoming song queue empty

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#7226]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #35eca37 (2024-06-21 14:26) 

### What happened?

Upcoming song queue is empty. I set it to 5.
Running System Debugger Next Song 
![Screenshot_20240621_221027](https://github.com/AzuraCast/AzuraCast/assets/43477041/b628118d-a6a8-4195-8da7-bdfbb942652e)

System debugger clear upcoming queue
![Screenshot_20240621_220613](https://github.com/AzuraCast/AzuraCast/assets/43477041/6b933a66-c7ce-4bcb-8464-e09db4c6b3a5)

### Relevant log output

```shell
2024/06/21 22:00:33 [lang:3] API feedback - Response (200): true
2024/06/21 22:00:36 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2024/06/21 22:00:36 [lang:3] API nextsong - Response (200): false
2024/06/21 22:00:47 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2024/06/21 22:00:47 [lang:3] API nextsong - Response (200): false
2024/06/21 22:00:57 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2024/06/21 22:00:57 [lang:3] API nextsong - Response (200): false
2024/06/21 22:01:08 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2024/06/21 22:01:08 [lang:3] API nextsong - Response (200): false
2024/06/21 22:01:18 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2024/06/21 22:01:18 [lang:3] API nextsong - Response (200): false
2024/06/21 22:01:29 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2024/06/21 22:01:29 [lang:3] API nextsong - Response (200): false
2024/06/21 22:01:39 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2024/06/21 22:01:39 [lang:3] API nextsong - Response (200): false
2024/06/21 22:01:47 [lang:3] AutoDJ could not be initialized within the specified timeout.
```

**Comment by LordHelmchen666** [comment]
It is weird. My testserver with exactly same settings and files is working fine. Only difference I am aware of is I pre-tagged with cue_file (4.0.3) on not working server. Could this be the problem?

**Comment by Moonbase59** [comment]
@LordHelmchen666 Nope (tagging with 4.0.3 being the issue). I would _assume_ that one of the latest internal database tag storage and UI changes, in combination with some changed typing rules _could_ have caused this.

@BusterNeece will surely have a look.

**Comment by LordHelmchen666** [comment]
```
[2024-06-22T18:06:42.659097+00:00] AzuraCast.ERROR: Queue builder error: App\Entity\StationMediaMetadata::setLiqAmplify(): Argument #1 ($amplify) must be of type ?float, string given, called in /var/azuracast/www/backend/src/Entity/AbstractStationConfiguration.php on line 47 {"exception":"[object] (TypeError(code: 0): App\\Entity\\StationMediaMetadata::setLiqAmplify(): Argument #1 ($amplify) must be of type ?float, string given, called in /var/azuracast/www/backend/src/Entity/AbstractStationConfiguration.php on line 47 at /var/azuracast/www/backend/src/Entity/StationMediaMetadata.php:33)"} {"station":{"id":1,"name":"Eisradio"}}
[2024-06-22T18:06:42.861314+00:00] AzuraCast.ERROR: Request returned status code 404. {"body":""} {"station":{"id":1,"name":"Eisradio"}}
```
Here is one more error i found in the logs. 
`("liq_amplify", "-10.72 dB")` Could it cause the proplem? Does Azuracast need `("liq_amplify", "-10.72")` instead? Just a guessing,

**Comment by Moonbase59** [comment]
Good point. The parameter to `amplify` can either be float (linar amplitude, 0..1) _or_ a string (value in dB, including the ` dB`). Autocue/cue_file use dB exclusively, as does more and more Liquidsoap software.

**Comment by Vaalyn** [comment]
Sounds like a problem with the automatic mapping of the `StationMediaMetadata` field to `liq_amplify`. If it's allowed to contain a "dB" suffix that will most likely need to be handled specifically when assigning that value. Not sure if that should be done in each metadata reader or somewhere automatically in the mapping of the entity 🤔

**Comment by Moonbase59** [comment]
We could skip the "amplify" UI field, and just pass it through as a string ;-) I always wondered if anybody ever used that. Or we switch that to dB, too.

**Comment by LordHelmchen666** [comment]
@Vaalyn Is there a way to identify the file causing this error?

**Comment by BusterNeece** [comment]
@LordHelmchen666 I've updated the extra metadata handler to better handle media that has a string value for amplify, and to convert it to a float and strip the `dB` annotation where possible. Should fix your issue.

**Comment by LordHelmchen666** [comment]
@BusterNeece You are my hero. Thanks for fixing this. I updated a few minutes ago and the error is gone. The upcoming queue is working as expected again.

**Comment by Moonbase59** [comment]
@BusterNeece Great! Do you store amplify as flot _dB_ values (as indicated in the UI)? And add the ` dB` again when annotating?

**Comment by Vaalyn** [comment]
@Moonbase59 yes, they are stored as floats and when annotating them they get the dB added again: https://github.com/AzuraCast/AzuraCast/blob/main/backend/src/Radio/AutoDJ/Annotations.php#L145

**Comment by Moonbase59** [comment]
Thanks @Vaalyn!

Noticed this won’t work: https://github.com/AzuraCast/AzuraCast/blob/836d09af1098154d675737b1933017025ac38268/backend/src/Radio/AutoDJ/Annotations.php#L140-L143

You’re trying to convert _all_ `liq*` metadata to float, which can’t succeed on these:

|tag|typical value|suffix(es)|
|---|---|---|
|`liq_blank_skipped`|`false`|—|
|`liq_longtail`|`false`|—|
|`liq_sustained_ending`|`false`|—|
|`liq_amplify_adjustment`|`0.00 dB`|`dB`|
|~~`liq_amplify`~~|~~`-1.23 dB`~~|~~`dB`~~|
|`liq_loudness`|`-16.67 LUFS`|`LUFS`|
|`liq_loudness_range`|`9.62 LU`|`LU`|
|`liq_reference_loudness`|`-18.00 LUFS`|`LUFS`|
|`liq_true_peak_db`|`-0.63 dBFS`|`dBFS`, `dBTP`|
|`replaygain_album_gain`|`-1.34 dB`|`dB`, `LU`|
|`replaygain_album_peak`|`0.930153`|none=linear, `dB`, `dBFS`, `dBTP`|
|`replaygain_album_range`|`9.10 dB`|`dB`, `LU`|
|`replaygain_reference_loudness`|`-18.00 LUFS`|`dB`, `dBFS`, `LUFS`|
|`replaygain_track_gain`|`-1.34 dB`|`dB`, `LU`|
|`replaygain_track_peak`|`0.930153`|none=linear, `dB`, `dBFS`, `dBTP`|
|`replaygain_track_range`|`9.10 dB`|`dB`, `LU`|

…and some more to come in LS 2.3.0.

**Comment by Moonbase59** [comment]
@Vaalyn Should I maybe make a separate issue of this, or do you keep an eye on this?

**Comment by Vaalyn** [comment]
> @Vaalyn Should I maybe make a separate issue of this, or do you keep an eye on this?

😄 was creating a new issue right at this moment
