### ISSUE TITLE
Type conversions for `liq_*` and `replaygain_*` metadata are too simplistic

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#7231]
@Moonbase59 notified us on the issue #7226 about the possibility that a lot of these metadata fields can have suffixes and might be expected by Liquidsoap / other tools to be there.

Currently the code assumes that all those values shall be floats which won’t work correctly in those cases where the suffixes are expected: https://github.com/AzuraCast/AzuraCast/blob/836d09af1098154d675737b1933017025ac38268/backend/src/Radio/AutoDJ/Annotations.php#L140-L143

He compiled a list of the metadata tags with possible suffixes that we'd need to handle:

|tag|typical value|suffix(es)|
|---|---|---|
|`liq_blank_skipped`|`false`|—|
|`liq_longtail`|`false`|—|
|`liq_sustained_ending`|`false`|—|
|`liq_amplify_adjustment`|`0.00 dB`|`dB`|
|~~`liq_amplify`~~|~~`-1.23 dB`~~|~~`dB`~~|
|`liq_loudness`|`-16.67 LUFS`|`LUFS`|
|`liq_loudness_range`|`9.62 LU`|`LU`|
|`liq_reference_loudness`|`-18.00 LUFS`|`LUFS`|
|`liq_true_peak_db`|`-0.63 dBFS`|`dBFS`, `dBTP`|
|`replaygain_album_gain`|`-1.34 dB`|`dB`, `LU`|
|`replaygain_album_peak`|`0.930153`|none=linear, `dB`, `dBFS`, `dBTP`|
|`replaygain_album_range`|`9.10 dB`|`dB`, `LU`|
|`replaygain_reference_loudness`|`-18.00 LUFS`|`dB`, `dBFS`, `LUFS`|
|`replaygain_track_gain`|`-1.34 dB`|`dB`, `LU`|
|`replaygain_track_peak`|`0.930153`|none=linear, `dB`, `dBFS`, `dBTP`|
|`replaygain_track_range`|`9.10 dB`|`dB`, `LU`|

> I’d suggest a [_type conversion dictionary_](https://github.com/Moonbase59/autocue/blob/17cd91aa6e476107d7a5a1b05f24bf1828193221/cue_file#L201-L236) like I use in `cue_file`, and a general [_suffix remover_](https://github.com/Moonbase59/autocue/blob/17cd91aa6e476107d7a5a1b05f24bf1828193221/cue_file#L323-L341) using a RegEx.

We'll need to handle those as advised in a more sophisticated manner.

**Comment by Moonbase59** [comment]
You _are_ fast! :-) Thanks!

**Comment by BusterNeece** [comment]
@Moonbase59 @Vaalyn Pushing up a few changes that should improve both how we ingest custom metadata into our own `extra_metadata` class and also be smarter about how we annotate that data back to Liquidsoap on the flipside, so if we're sending a string over it'll just keep it a string, but if it's a numeric value it'll properly format it as one.

**Comment by Moonbase59** [comment]
@BusterNeece Code looks good to me, will update tomorrow. We should stay sync’ed about the hardcoded tag names, in case some get changed (again!) or become another type (as has happened with `liq_blankskip`).

Fortunately, we have the list in `cue_file --help` ("cue_file x.y.z knows about these tags:"). I plan to make a "metadata/tag keys" table on my repo, too, so we have a reference (unlike Liquidsoap…).

**Comment by BusterNeece** [comment]
@Moonbase59 I was a little looser in my interpretation since we only really need fixed decimal values for the ones we actually maintain internally (fade/cue/amplify/etc)...the others we can just pass through directly as-is, so it's safer for us to just do an "is a number or numeric string" check on those without listing them all out one by one.

**Comment by Moonbase59** [comment]
@BusterNeece That’s a good principle. "Know what you need, don’t touch the rest."

**Comment by Moonbase59** [comment]
@BusterNeece Testing Rolling Release #[1fec896](https://github.com/AzuraCast/AzuraCast/commit/1fec89644f030dc2400e4d1f482c27e64df4e329) (2024-06-25 0:57).

Seems sometimes metadata isn’t read. Sure you read tags **case-insensitively**?

![Arbeitsfläche 1_060](https://github.com/AzuraCast/AzuraCast/assets/3706922/3c33d74d-5b6c-4181-92ab-7b3b899b3d03)

In _Media Files_, I tagged this file for reprocessing a few times, but doesn’t seem to change things.

**Comment by Vaalyn** [comment]
🤔 I remember that I added an explicit `strtolower` call on the tag names some time ago in the FFProbe metadata reader since the getId3 lib was always returning them lower cased, see https://github.com/AzuraCast/AzuraCast/pull/5392

I've just double checked and in the meantime we introduced an enum for the metadata tag names here: https://github.com/AzuraCast/AzuraCast/blob/main/backend/src/Media/Enums/MetadataTags.php

Which has a `getTag` method that still handles the strtolower thing.

Maybe something has changed in the other metadata tag reader (getId3) since (if I remember correctly) that one runs first and only on failure do we fall back to FFProbe due to speed.

@Moonbase59 would you be comfortable with manually editing the https://github.com/AzuraCast/AzuraCast/blob/main/backend/src/Media/Metadata/Reader/PhpReader.php on your server to add a `file_put_contents(__DIR__ . '/debug.json', json_encode($toProcess, JSON_PRETTY_PRINT));` here?
https://github.com/AzuraCast/AzuraCast/blob/main/backend/src/Media/Metadata/Reader/PhpReader.php#L62

Then re-analyze a file and look what the debug.json contains exactly?

**Comment by BusterNeece** [comment]
@Moonbase59 @Vaalyn Played with this extensively locally and found several discrepancies between how we handle metadata that's ingested via php-getid3 and via ffprobe. I've rewritten both of the metadata readers to use a single channel for processing metadata.

I also made sure that all of our key handling is case-insensitive and that we properly coerce types when ingesting things into our own `StationMediaMetadata` class.

This should collectively result in _much_ more reliable metadata fetching regardless of source.

**Comment by Moonbase59** [comment]
@BusterNeece Sounds great, and I agree.
@Vaalyn Still need that test?

**Comment by Vaalyn** [comment]
Nope, all good I think 👍

**Comment by Moonbase59** [comment]
Looks much better now (example: Queen FLAC), but I miss the other ReplayGain values:

![Arbeitsfläche 1_064](https://github.com/AzuraCast/AzuraCast/assets/3706922/ed0bb53e-715d-49c9-9446-8184872eb072)

Tested on Rolling Release #[435ed3b](https://github.com/AzuraCast/AzuraCast/commit/435ed3b6340d75470d254beaa131ea6ae42d8dc7) (2024-06-25 12:53).

**Comment by BusterNeece** [comment]
@Moonbase59 Weirdly, php-getid3 isn't showing those replaygain values at all in the vorbiscomment field. Is there any reason they'd be stored somewhere other than what it was fetching? That doesn't make a ton of sense...

**Comment by Moonbase59** [comment]
@BusterNeece No, makes no sense, Vorbis Comments being the _easiest_ of all tag formats. You can try for yourself, the `Queen - Bohemian Rhapsody.flac` is in the test set.

It somehow looks like it would read only _one_ of the various `replaygain_album_*` and `replaygain_track_*` tags. Let me cross-check…

**Comment by Moonbase59** [comment]
Darn! Upstream bug! Same here with getID3() v1.9.23-202310190849. Wonder what they messed up, sigh. You gonna report upstream?

Kid3 and mutagen-inspect show clearly the tags are there.

**Comment by Moonbase59** [comment]
Had a quick look at te getID sources. Guess I found it. They _don’t know_ the `_range` values, so they’re not touched.

All others are read into some internal `replay_gain` structure and converted to double.

![Auswahl_443](https://github.com/AzuraCast/AzuraCast/assets/3706922/520da49c-32c7-452a-a8d1-5034a38c1407)

**Comment by BusterNeece** [comment]
@Moonbase59 Yeah, I do not know how to tell them _not_ to do that, but I suppose we can convert back from their denormalized version into a version we can use.

**Comment by Moonbase59** [comment]
Unfortunately, that’s not consistent over file types… sigh again. For ASF (WMA) for instance, these are left in the `extended_content_description_object`. for M4A they’re in the comments, for OGG they’re in the `replay_gain`, for MP3, a part is in `text`, another part in `replay_gain`, for WAV, part is in `text`, part in `tags` (deeply buried), and so on…

What a mess.

**Comment by BusterNeece** [comment]
@Moonbase59 Well, for flac and mp3, I can convert back from getid3's array format back into a tag format we can use. I updated the RR to do this.

**Comment by Moonbase59** [comment]
We might not be able to handle _all_ formats, but it seems the community also uses a lot of `.wma`, `.m4a` (both AAC and ALAC) files. Think these could be in it, too?

**Comment by BusterNeece** [comment]
@Moonbase59 Looking at your samples and it appears both `.wma` and `.m4a` already _are_ properly pulling RG values.

I think we're doing much better now in regards to this issue; will close it, feel free to reopen if needed.
