### ISSUE TITLE
API GET /station/{station_id}/files times out (504)

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#7236]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #f70c987 (2024-06-23 18:50)

### What happened?

Trying to get a list of media files via the API times out with a 504 error..

![AzuraCast-Swagger-timeout](https://github.com/AzuraCast/AzuraCast/assets/3706922/825403c2-6a57-4961-957c-4e1b1f159236)

Now I _do_ have about 160k tracks and _expect_ it to take a while, but no timeout.

Is there any parameter I could change? Looks like an Nginx timeout to me.

**Comment by Sella-GH** [comment]
Only seems to happen on _very large_ stations, mine with ~90 does not timeout.

Somewhat understandable tho 😄

**Comment by Vaalyn** [comment]
@Moonbase59 you could try overriding the `NGINX_TIMEOUT=1800` in the `.env` as well as the `PHP_MAX_EXECUTION_TIME=30` in the `azuracast.env` file.

Or you can use the `?per_page=5&page=1` parameters to get paginated results from that endpoint (probably not directly usable with the swagger page)

**Comment by Moonbase59** [comment]
@Vaalyn 

- NGINX_TIMEOUT=3600
- PHP_MAX_EXECUTION_TIME=600

**Comment by BusterNeece** [comment]
There's definitely some room for improvement in terms of how we handle large volumes of media via that endpoint...it's really meant to be paginated, though.

**Comment by Moonbase59** [comment]
Well, it’s not absolutely a showstopper, I was just trying to find some media_ids. I only wonder why it terminates so "fast" even with the generous settings.

**Comment by Vaalyn** [comment]
Maybe it's hitting the php memory limit due to the amount of data from those 160k media entries?
