### ISSUE TITLE
Change `send_icy_metadata=true` to `false` for OGG FLAC & OGG Opus streams

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#7240]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #f70c987 (2024-06-23 18:50)

### What happened?

I suggest changing the `send_icy_metadata=true` to `send_icy_metadata=false` for ConfigWriter if we’re outputting to Ogg FLAC and Ogg Opus streams.

Reason: Icecast-kh doesn’t support ICY metadata on these stream types (otherwise we could at least generate a `StreamTitle` which will apparently be supported in Xiph-Icecast 2.4.99 (beta) and 2.5+, but is not in Icecast-kh).

But if we set it to `false`, we will produce ["chained" (discontinuous) Ogg streams](https://xiph.org/ogg/doc/oggstream.html), that more and more players now seem to support, and can use the in-stream metadata.

Only drawback: All software that uses the ffmpeg decoder suffers from a [bug @toots reported 14 months ago](https://trac.ffmpeg.org/ticket/10363), "accumulating" metadata. This affects for instance _mpv_ and _Celluloid_, possibly many more.

_VLC_ is ok but has minor glitches during the phase the metadata is sent, _Audacious_ only ever displays the first metadata seen after connection, _Quod Libet_ and _Rhythmbox_ seem to work fine, and so on.

See the [discussion](https://github.com/savonet/liquidsoap/discussions/3990) over at Liquidsoap.

Since Opus offers an unrivaled quality at small bandwidth, and some people might even want to stream Ogg FLAC, we should at least _provide_ the metadata as intended by Xiph.

```
$ ffprobe -hide_banner https://radio.niteradio.net/listen/niteradio/radio.opus
Input #0, ogg, from 'https://radio.niteradio.net/listen/niteradio/radio.opus':
  Metadata:
    icy-description : Wir spielen die bessere Musik.
    icy-genre       : Classic Rock, Easy Listening, Electronic, Folk Rock, Hard Rock, Oldies, Pop, Schlager, Various
    icy-name        : Nite Radio
    icy-pub         : 0
    icy-url         : https://grav1.niteradio.net/
  Duration: N/A, start: 210.840000, bitrate: N/A
  Stream #0:0: Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      album           : Hell or High Water
      artist          : Rob Queen
      title           : For the Broken
```
Here are two streams to test with, both using the chained method and Icecast-kh:

- https://radio.niteradio.net/listen/niteradio/radio.opus (minimum metadata)
- http://zeremy.serv00.net:8200/opus (more metadata)

**Comment by Vaalyn** [comment]
As far as I remember there was also the issue of players (notably Chrome) thinking that an ogg streams has to end when a new tracks metadata begins thus stopping playback. 

See: https://github.com/AzuraCast/AzuraCast/issues/3597

**Comment by Moonbase59** [comment]
Interestingly, Chromium now plays fine even with Ogg Opus "chained", but Firefox misbehaves (keeps reading stream but no sound after first track).

Using `icy_metadata=true` is actually working around a problem using another bug ;-) If you’d do it manually, you’d see the Icecast returning an error message for this configuration. But yes, since it’s supposed to send ICY metadata and can’t (or doesn’t want to, RSAS have their clone that _does_ it), it won’t send the real metadata as well.

Even ffmpeg now "plays on", if only they hadn’t the "accumulating metadata" bug.

**Comment by Vaalyn** [comment]
Yeah, I'm not really happy with the current work around but until the major browsers work decently with the "regular" ogg streams incl. metadata I wouldn't feel good with using `false`. Most listeners will probably use browsers, don't wanna break that for them "just" for the metadata working again in other clients 😓

**Comment by Moonbase59** [comment]
Added to Firefox’ 7-year-old bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1427527#c9

**Comment by Moonbase59** [comment]
Go a little further in testin with @smoralis: It seems that if we use _ffmpeg_ for Opus instead of `%opus`, a stream is generated that even Firefox can read. Still have to check some intrinsics, to find out what exactly is causing this.

**Comment by Moonbase59** [comment]
Ok, finally got it. Looks like Liquidsoap are using some other encoder (?) with `%opus`, and _that_ makes Firefox not play the streams.

If we change from `%opus` (example from my tests):
```
output.icecast(%opus(samplerate=48000, bitrate=128, vbr="constrained", application="audio", channels=2, signal="music", complexity=10, max_bandwidth="full_band"), id="local_7", host = "127.0.0.1", port = 8000, password = "(PASSWORD)", mount = "/test.opus", name = "Nite Radio", description = "Wir spielen die bessere Musik.", genre = "Classic Rock, Easy Listening, Electronic, Folk Rock, Hard Rock, Oldies, Pop, Schlager, Various", url = "https://grav1.niteradio.net/", public = false, encoding = "UTF-8", send_icy_metadata=false
```

to `ffmpeg` and use `libopus` instead, all is fixed, for all browsers and more:
```
output.icecast(%ffmpeg(format="ogg", %audio(codec="libopus", samplerate=48000, b="128k", vbr="constrained", application="audio", channels=2, compression_level=10, cutoff=20000)), id="local_7", host = "127.0.0.1", port = 8000, password = "(PASSWORD)", mount = "/test.opus", name = "Nite Radio", description = "Wir spielen die bessere Musik.", genre = "Classic Rock, Easy Listening, Electronic, Folk Rock, Hard Rock, Oldies, Pop, Schlager, Various", url = "https://grav1.niteradio.net/", public = false, encoding = "UTF-8", send_icy_metadata=false, radio)
```

See also:
- https://github.com/savonet/liquidsoap/discussions/3990#discussioncomment-9891297
- https://github.com/savonet/liquidsoap/discussions/3990#discussioncomment-9892368

Hooray!

**(being happy and making a nice pretty-please face) Could we implement that?**

**Comment by Vaalyn** [comment]
Sounds like a great solution to this issue 🥳 

I'll see that I prepare a PR to change this from `%opus` to the `%ffmpeg` encoder over the weekend.

Thank you for investigating this ❤️

**Comment by Moonbase59** [comment]
Thank you for all the support, too! I think the same will apply to Ogg FLAC streams, but let’s do and test one thing at a time. When this is done, I’ll start checking Ogg FLAC streams…

**Comment by Moonbase59** [comment]
Here are some easy ways to check for stream and metadata.

Check metadata, using the official Opus decoder:

```
$ curl -s https://radio.niteradio.net/listen/niteradio/test.opus| opusdec --float - - >/dev/null
```

Check metadata and play in WAV format:

```$ curl -s https://radio.niteradio.net/listen/niteradio/test.opus| opusdec --float --force-wav - - | ffplay -v quiet -
```

(You could substitute something else instead of `ffplay`.)

**Comment by Moonbase59** [comment]
@Vaalyn It would be rather helpful if we could get the `now_playing.song.art` in the metadata, possibly as `cover`. That’d make it easy for playout systems like _Logitech Media Server_ (now _Lyrion Music Server_) to pick it up and display the image from the URL.

**Comment by Vaalyn** [comment]
> @Vaalyn It would be rather helpful if we could get the `now_playing.song.art` in the metadata, possibly as `cover`. That’d make it easy for playout systems like _Logitech Media Server_ (now _Lyrion Music Server_) to pick it up and display the image from the URL.

This doesn't really have much to do with this specific issue thread though 😉 

That's basically a feature / enhancement request and should ideally be either a feature request or at least its own issue thread.

**Comment by Moonbase59** [comment]
Yah, ok, true ;-)

**Comment by Vaalyn** [comment]
@Moonbase59 I've prepared a PR that:
- Switches `ogg/opus`, `ogg/vorbis` and `ogg/flac` over to use the ffmpeg encoder with its respective encoding engines for those formats
- Sets `send_icy_metadata=false` for those formats

I've tried to convert the settings on the LS operators to the respective ffmpeg options and tested all 3 stream formats:
- In VLC all streams play correctly and show the same metadata that AzuraCast shows for the now playing song.
- In Chrome
  - direct stream access => all play correctly
  - public page player => all play correctly
- In Firefox (developer edition)
  - direct stream access
    - opus & vorbis play correctly
    - flac stops playback on transitions
  - public page player
    - opus & vorbis play correctly
    - flac stops playback on transitions
- In macOS Safari 17.4.1
  - direct stream access doesn't work, when accessing a stream it just starts to download it
    - Supports opus only in a WebM container => https://caniuse.com/?search=opus
    - Supports only the vorbis codec, not the ogg container => https://caniuse.com/?search=vorbis
      - Same for flac
  - public page player
    - opus, vorbis, flac => no sound
      - [Error] Unhandled Promise Rejection: NotSupportedError: The operation is not supported.
- In Apple Music
  - Opus, vorbis & flac all don't play

I've double checked the `ogg/flac` against the `%ogg(%flac(...` one and that one does not stop on transitions in Firefox so it looks like we could switch Vorbis & Opus over to the `%ffmpeg` encoder but with Flac i'd probably keep it as is for now (incl. the icy metadata) so that those streams don't stop in FF.

**Comment by Moonbase59** [comment]
@Vaalyn Think we also have to change Ogg/Vorbis? That seemed to work fine.

Ogg/Flac I have to investigate still. Did it work before? (Never yet set up an AzuraCast Ogg/Flac stream)

**Comment by smoralis** [comment]
> @Vaalyn Think we also have to change Ogg/Vorbis? That seemed to work fine.
> 
> Ogg/Flac I have to investigate still. Did it work before? (Never yet set up an AzuraCast Ogg/Flac stream)

I believe using ffmpeg for vorbis also is a good choice, as it is possible to add more metadata fields including the above mention of cover_url.

I have added 2 streams to the test server for comparison. 

http://zeremy.serv00.net:8200/vorbis1
http://zeremy.serv00.net:8200/vorbis2
