### ISSUE TITLE
problems with ftp and stereotool.

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#7242]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

f70c987 (2024-06-23 18:50) • Docker • PHP 8.3

### What happened?

hello. Firstly, I will describe the problem and hope that you will direct me to the most correct way of providing logs and information.
The first problem is the stereotool. I didn't do radio for about a year. Today, I bought a new server and installed azuracast. However, when I installed stereotool and placed my sts file, the radio just started playing the Azuracast music, all in cuts as if there was a CPU problem. I used the same sts preset on the radio I ran about a year ago, and everything was fine. When I deactivate the stereotool, everything goes back to normal.
The server has 3.2ghz 6 cores, and 8gb of ram.
The second problem is with ftp.
after uploading 20 or 30 files I get disconnected from ftp. and whenever I connect, filezilla says. ftp started protocol version 11. and then, it was not possible to connect to the server. I need to restart the entire vps, because I can't restart just the ftp service, and everything goes back to normal.
I know without logs it's a little difficult, however, based on these issues, tell me what you need, and I'll send it without any problems. Suggestions are also welcome.

**Comment by BornKillaz** [comment]
Look, I'm in no way an AzuraCast specialist, I'm far from that, but I've experienced a few issues in the past 3 months and I notice that even with a powerful server setup, some things seem to keep causing issues. 

So my first guess is, have you disabled AutoCue? Becouse AutoCue along with StereoTool would hit hard on your server resources for sure, specially on some scenarios...

**Comment by nunotfc** [comment]
yes, i disabled all that says high cpu, leaving only stereotool active and, no way. if i leave stereotool withouth a configuration file, it works! but if i upload some config file, even one i have that is for older cpus, it doesnt work

**Comment by BornKillaz** [comment]
Ok... so this transcends my knowledge, as unfortunately I don't use Stereotool, too expensive for me...

Maybe the developers can have an answer for you so you can get things running.

**Comment by nunotfc** [comment]
i also use without a serial number

**Comment by ckeurk** [comment]
8 GB of Ram seems too low to run Stereotool properly. The best thing is to have double or even more, even for the core. Stereotool is very greedy and requires a lot of resources.

**Comment by nunotfc** [comment]
i wated moneyh aqnd updated for a vps with 8 cpu, 32gb of ram. it starts working good, but, after 10 or 20 seconds starts to cut and so. it is so frustrating, because i like stereotool and the possibilities it gives for me. i used it before in a vps with same specs than before, but i needed to update, so i updated. i disabled all. write playlists, replay gain, autocue. it is something more i can do to test? for exmaple parameters in the env file or something in the docker configuration?

**Comment by nunotfc** [comment]
hello, i fixed. the problem is that when i did radio last time 1 year ago, i used version cmd of stereotool. i downloaded the one that says that is for liquidsoap and it worked!
