### ISSUE TITLE
Demo Instance: Odd default streams list returned (2024-06-26T00:59:36)

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#7246]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #435ed3b (2024-06-25 12:53)

### What happened?

I was testing the new [SSE HPNP](https://grav1.niteradio.net/wh/sse_cf_demo.html) demo version and found a mysterious list of default stream URLs returned. Observed at 2024-06-26T00:59:36+0200:

![Auswahl_444](https://github.com/AzuraCast/AzuraCast/assets/3706922/d3ff2369-38dc-48fa-bd2e-915d943705e5)

![Auswahl_445](https://github.com/AzuraCast/AzuraCast/assets/3706922/93b1da5b-144a-4854-93b8-b6a916aa881a)

**Comment by Vaalyn** [comment]
You most likely encountered this due to someone testing stuff on the demo instance, probably entering this URL in the field for the mount point URL.

Nothing we need to look at imho

**Comment by Moonbase59** [comment]
No, surely not. Just wanted to alert in case some attack was going on. Closing.
