### ISSUE TITLE
I can't create my account with my email

### ISSUE THREAD

**Issue by rfigueroa9** [AzuraCast/AzuraCast#7247]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.21

### What happened?

I had to uninstall Azuracast and when I reinstalled it and entered my data to create the super administrator account it did not let me do it.

**Comment by BusterNeece** [comment]
@rfigueroa9 We need a lot more information to be able to help you out here.

Do you see any sort of error message? Either in the browser console, in a red popup, or in the terminal (https://www.azuracast.com/docs/help/logs/#docker-container-logs), it would be helpful to see what the system is saying.

It's possible that the uninstallation, for whatever reason, didn't delete your database completely.

You can manually delete all volumes associated with AzuraCast by running:

```bash
# WARNING: THIS WILL DELETE YOUR INSTALLATION DATA! DO NOT RUN UNLESS YOU ARE UNINSTALLING!
cd /var/azuracast
docker-compose down -v
```
