### ISSUE TITLE
How can I add landing page to Azuracast?

### ISSUE THREAD

**Issue by br0kenlink** [AzuraCast/AzuraCast#725]
Hi,
firstly want to say massive thank you for this project. Works great so far!
I have a small issue though.
I'm trying to add landing page where I want to make a list of all streams for people to pick one they want to listen, then they'll be redirected to Azuracast radio page/s.

I added this to nginx virtual host for Azuracast

location /main {
        alias /var/www/broken;

    }

When i try to go to https://radiohost/main it gives me 403 forbidden error.
Everything else works perfect.
Would appreciate help

**Comment by SlvrEagle23** [comment]
Try

```
location /main {
    root /var/www/othersite;
}
```

in your nginx configuration. Keep in mind you can also have the homepage redirect anywhere you like (even off-site) for non-logged-in users by changing the corresponding setting in the AzuraCast system settings page, while still allowing you to directly access the login page via `/login`.

**Comment by br0kenlink** [comment]
That seems to almost work. Now I'm getting this in nginx:
*117 "/var/www/broken/main/index.php" is not found (2: No such file or directory),

it looks for files in /var/www/broken/main/ and if I create that folder with all site files in it, it will work but the site is simply broken.
Any way to make it not look for main folder?

I know I can host landing page at different location/server it just feels pointless if I could keep things simple and have it on same server as AzuraCast.
It is simple one page site with few images and some CSS, unfortunately it isn't simple enough for me to edit it by myself

**Comment by br0kenlink** [comment]
ok, got it to work. Missed it somehow.
had to change root for alias to /var/www and rename site folder to main
Thanks for help
