### ISSUE TITLE
Metadata conversion produces multiple values that crash Autocue cue_file

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#7253]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #6a8a450 (2024-06-25 20:58)

### What happened?

`cue_file` can’t gracefully handle multiple values for one `liq_*` tag (it cannot know which to use). It appears that due to the numeric conversions, the annotation string can become different from the file tag, and in that case produces multiple tag values of the form `value1; value2`. This mostly seems to happen when the stored tag value has trailing zeroes:

```
2024/06/27 03:58:10 [lang:3] Failed to execute `'cue_file' '-j' '/tmp/cue_file5ba8bf.json' '-n' '-k' '-t' '-18.00' '-s' '-42.00' '-o' '-8.00' '-l' '15.00' '-x' '-12.00' '-d' '40.00' '/var/azuracast/stations/niteradio/media/Other/Jingles/Liners/Dan O'\''Keeffe - The Soundtrack of Your Life.mp3'`: exit (1)  Traceback (most recent call last):
2024/06/27 03:58:10 [lang:3]   File "/usr/local/bin/cue_file", line 1184, in <module>
2024/06/27 03:58:10 [lang:3]     skip_analysis, tags_found = read_tags(
2024/06/27 03:58:10 [lang:3]                                 ^^^^^^^^^^
2024/06/27 03:58:10 [lang:3]   File "/usr/local/bin/cue_file", line 357, in read_tags
2024/06/27 03:58:10 [lang:3]     tags_found = {k: tags_to_check[k](v) for k, v in tags_found.items()}
2024/06/27 03:58:10 [lang:3]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/06/27 03:58:10 [lang:3]   File "/usr/local/bin/cue_file", line 357, in <dictcomp>
2024/06/27 03:58:10 [lang:3]     tags_found = {k: tags_to_check[k](v) for k, v in tags_found.items()}
2024/06/27 03:58:10 [lang:3]                      ^^^^^^^^^^^^^^^^^^^
2024/06/27 03:58:10 [lang:3] ValueError: could not convert string to float: '0.305470; 0.30547'
2024/06/27 03:58:10 [lang:3] 
2024/06/27 03:58:10 [autocue.cue_file:2] No autocue data found for "/var/azuracast/stations/niteradio/media/Other/Jingles/Liners/Dan O'Keeffe - The Soundtrack of Your Life.mp3"
2024/06/27 03:58:10 [autocue.metadata:2] No autocue data found for file annotate:title="The Soundtrack of Your Life",artist="Dan O'Keeffe",duration="3.77",song_id="85d3657944ffa9d57e10279731bf5226",media_id="323197",liq_fade_in="0.10",liq_fade_out="0.10",replaygain_track_gain="3.06 dB",replaygain_track_peak="0.305470; 0.30547",replaygain_album_gain="1.96 dB",replaygain_album_peak="0.31",replaygain_reference_loudness="-18.00 LUFS; 89 LUFS",replaygain_track_range="0.00 dB",replaygain_album_range="3.24 dB",playlist_id="536",jingle_mode="true":media:Other/Jingles/Liners/Dan O'Keeffe - The Soundtrack of Your Life.mp3
2024/06/27 03:58:10 [autocue.protocol:2] No autocue data found for URI annotate:title="The Soundtrack of Your Life",artist="Dan O'Keeffe",duration="3.77",song_id="85d3657944ffa9d57e10279731bf5226",media_id="323197",liq_fade_in="0.10",liq_fade_out="0.10",replaygain_track_gain="3.06 dB",replaygain_track_peak="0.305470; 0.30547",replaygain_album_gain="1.96 dB",replaygain_album_peak="0.31",replaygain_reference_loudness="-18.00 LUFS; 89 LUFS",replaygain_track_range="0.00 dB",replaygain_album_range="3.24 dB",playlist_id="536",jingle_mode="true":media:Other/Jingles/Liners/Dan O'Keeffe - The Soundtrack of Your Life.mp3!
```

Check `replaygain_track_peak="0.305470; 0.30547"`.
Only _one_ value is allowed to be returned for `liq_*` and ̀`replaygain_*` tags.

Tbh, I’m not sure if it is PHP generating this, or maybe `cue_file` reading the same tag from the temporary JSON file _and_ the file itself. (Shouldn’t happen, the intention is that the JSON content overrides what I have found in the file, because it contains AzuraCast’s or the pre-processor’s annotated overrides.)

The default precision for nearly all numeric values is 2 decimals, the linear `peak` values are stored with a 6 decimals precision. `cue_file` can  _read_ any precision (except 1e10-type) but will always _write_ with above said precision, for rounding purposes. So in above case, Autocue is perfectly happy with getting `0.30547` back, even if it _sent_ `0.305470`.

I’d suggest we both store whatever comes out of our calculations (like LS does), but floats _must_ have at least 1 digit after the period. And of course both of us _must_ return only _one_ value for said tags.

**Same holds true for users _manually tagging_ files! So _not_ `liq_fade_out=5.` but `liq_fade_out=5.0` or `liq_fade_out=5.00`!**

Will check tomorrow. Would be nice if you could cross-check.

**Comment by BusterNeece** [comment]
@Moonbase59 Yeah, this is a consequence of the relative clusterf*** that php-getid3's handling of ReplayGain is...on several file types, it not only sets the ReplayGain values, but *leaves them in the original place*. On others, it removes them.

Probably merits a PR upstream, but that's not a priority for me right now. We can just deduplicate when setting the extra metadata, which is done as of the latest RR.

**Comment by Moonbase59** [comment]
Just saw another one, wonder where _that_ wild value came from (the original `replaygain_track_peak` is `0.652000`):

```
2024/06/27 04:44:02 [lang:3] ValueError: could not convert string to float: '0.652000; 16148.75'
```

**Comment by BusterNeece** [comment]
@Moonbase59 Any time the replaygain data is in the original meta anywhere that we can use, the latest update will prefer that. The "working backwards from php-getid3's replaygain thing" value is always the _last_ value in the pile, and the deduplication in the extra_metadata always prefers the _first_ value.

**Comment by Moonbase59** [comment]
So I guess I’ll update tomorrow morn, before I test again. Thanks.
