### ISSUE TITLE
When you add songs, even if playlist is set to shufle, it starts playing alphabetically.

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#7257]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

dcd4fdc (2024-06-26 23:40) • Docker • PHP 8.3

### What happened?

Hello,
I just deleted all the songs from my playlist folder to start from scratch. Some of my songs had problems, so I edited them on my computer and uploaded them all again. After that, the playlist started playing in order from A to Z, even with shuffle mode enabled.
I have to delete the entire queue and wait for it to be done automatically.
Is this a bug?

**Comment by BusterNeece** [comment]
@nunotfc While this shouldn't be an issue once the playlist plays through the first time and has a chance to shuffle, I've updated some of the code to make sure that it properly shuffles immediately after being added via a playlist folder. This will be available in the Rolling Release shortly and should fix this for future additions.
