### ISSUE TITLE
So I have the problem with sync buttons in administration page .. 

### ISSUE THREAD

**Issue by ElNadie** [AzuraCast/AzuraCast#726]
**Installation method**
Traditional" installation method.

**Host OS (for Docker installations)**
ubuntu 16.4

**Describe the bug**
 I have the problem with sync buttons in administration page .. 
![but](https://user-images.githubusercontent.com/42041208/44261093-3748bd80-a21f-11e8-8dbb-8e8fd3f66b89.png)

If I click on buttons I take this message  “Setup not complete; halting synchronized task.”    Do you know why? 
And I upload music files with ftp (vsftpd) I take “File not Processed” in name of the song 
![2](https://user-images.githubusercontent.com/42041208/44261119-4e87ab00-a21f-11e8-88f9-69c4f3bb5915.png)

and one problem yet can not see listeners i see 0 all of time

**Comment by SlvrEagle23** [comment]
@ElNadie When you log in, are you redirected to the settings page? If so, just click "Save Changes" at the bottom of that page and it will complete the initial setup.

**Comment by ElNadie** [comment]
Solved...with your solution
