### ISSUE TITLE
Changing Web Site URL gives no Reload Button, results in incorrect Icecast/directory stream URL

### ISSUE THREAD

**Issue by mdrxy** [AzuraCast/AzuraCast#7263]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.20.1

### What happened?

Updating Web Site URL does not prompt user to reload settings (similar to #5802), which is necessary for the change to be reflected as the IceCast Stream URL. [This is the code implemented to address a similar issue](https://github.com/AzuraCast/AzuraCast/commit/8724a45a3ad5e4dfe96ef6346c7019fa83101a28#diff-b90a8d34bc554e02f8dbebd48c27bc76cebde9a2e2f2f8e1277d209d9afe104dL456). Based on that, a proposed re-write of setUrl in `Station.php`:

```php
public function setUrl(string $url = null): void
    {
        $url = $this->truncateNullableString($url);

        if ($this->url !== $url) {
            $this->setNeedsRestart(true);
        }

        $this->url = $this->truncateNullableString($url);
    }
```

**Comment by Moonbase59** [comment]
See https://github.com/AzuraCast/AzuraCast/issues/7264#issuecomment-2198540106

**Comment by mdrxy** [comment]
Issue persists in Rolling Release #[5dc00dd](https://github.com/AzuraCast/AzuraCast/commit/5dc00dd98508faa5b41a70f623f49e3dad7d0263) (2024-07-12 7:58)

**Comment by BusterNeece** [comment]
> Issue persists in Rolling Release #[5dc00dd](https://github.com/AzuraCast/AzuraCast/commit/5dc00dd98508faa5b41a70f623f49e3dad7d0263) (2024-07-12 7:58)

@mdrxy It's fixed in the latest Rolling Release, but just so you know for other/future issues, it's not necessary to comment that the issue persists unless we've indicated that it _should_ be fixed.
