### ISSUE TITLE
Icecast is incorrectly provided Web Site URL as the Stream URL on public pages

### ISSUE THREAD

**Issue by mdrxy** [AzuraCast/AzuraCast#7264]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

v0.20.1 Stable

### What happened?

Icecast's Stream URL (shown on the public Icecast page, not logged in to the admin panel) uses the Azura Web Site URL:
<img width="351" alt="Screenshot 2024-06-30 at 04 16 27" src="https://github.com/AzuraCast/AzuraCast/assets/61371264/af65821c-a38b-4f88-8eed-79d094a6f0d2">
<img width="356" alt="Screenshot 2024-06-30 at 04 15 52" src="https://github.com/AzuraCast/AzuraCast/assets/61371264/1a3f9952-7275-404e-819e-f8549f4bf326">

Instead, it would make more sense for this to also pull from the Mount Point URL, like it does for the `listenurl` when logged in to the admin view.

**Comment by Moonbase59** [comment]
Please DO NOT CHANGE THIS! Lots of software outside relies on it, and Xiph’s Icecast documentation also says

> **stream-url** […] The URL is generally for directing people to a website.

**Comment by mdrxy** [comment]
Good catch @Moonbase59  - this is a bit of a wormhole.

Perhaps we need to provide somewhere extra clarity on the "Stream URL" naming since it isn't intuitive?

It appears to me in testing that the [official Icecast directory](https://dir.xiph.org) is in fact pulling the `listenurl` for station listings (from [server stats](https://icecast.org/docs/icecast-2.4.1/server-stats.html)) instead of `stream-url`. I confirmed this by changing the Mount Point URL on my stream (under `Edit Mount Point -> Advanced -> Mount Point URL`) and then restarting broadcasting. The primary play button used on [dir.xiph.org](https://dir.xiph.org) for the stream updated to reflect the new Mount Point URL.

Could you perhaps provide scenarios where `stream-url` is used?

**Comment by Moonbase59** [comment]
Guess I don’t have to justify scenarios, look at everyone, everywhere. It was simply invented and is used for that purpose.

First station on internet-radio.com, for instance:

![Auswahl_457](https://github.com/AzuraCast/AzuraCast/assets/3706922/d93fb3c5-95b8-4b19-8c6c-86c2655cad87)

![Auswahl_458](https://github.com/AzuraCast/AzuraCast/assets/3706922/3b986ca2-91b7-4735-a268-4acd87d68c8a)

![Auswahl_456](https://github.com/AzuraCast/AzuraCast/assets/3706922/93c230dd-0965-41be-8da9-a4ace7774ced)

…and hundreds of thousands more.
