### ISSUE TITLE
Error msg: "port already in use by another station"

### ISSUE THREAD

**Issue by bombelman** [AzuraCast/AzuraCast#7267]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

v0.20.1 Stable Docker

### What happened?

Getting this error when modifying the "Duplicate Prevention Time Range" and clicking "Save Changes".
I have less than 10 stations and none have the same port.
It is unclear why I'm getting the "port already in use by another station" as there is no other station using this port, as far as I can see...

I already checked if other stations have this port and it is not the case.
Also I can restart the station broadcasting, and it starts up as normal. So no error about the port already in use.

![Screenshot 2024-06-30 144904](https://github.com/AzuraCast/AzuraCast/assets/107536852/ea08d4d3-e596-4aa7-8054-2d7be38c6159)

### Relevant log output

```shell
which log?
```

**Comment by bombelman** [comment]
is there a way I can edit this from the back-end without the front-end checking the (false duplicate?) port ?
I need this setting changed urgently...

**Comment by LordHelmchen666** [comment]
https://www.cyberciti.biz/faq/unix-linux-check-if-port-is-in-use-command/

`sudo lsof -i:8146`

**Comment by LordHelmchen666** [comment]
Change uppercase written to fit your station

```
curl -X 'PUT' \
  'https://YORDOMAIN.COM/api/admin/station/YOURSTATIONID' \
  -H 'accept: application/json' \
  -H 'X-API-Key: YOURAPIKEY' \
  -H 'Content-Type: application/json' \
  -d '{  "backend_config": {    duplicate_prevention_time_range": 300   }   }'
```

**Comment by bombelman** [comment]
> sudo lsof -i:8146

this command returns:

COMMAND       PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
docker-pr 2357441 root    4u  IPv4 644982474      0t0  TCP *:8146 (LISTEN)

**Comment by LordHelmchen666** [comment]
This should be OK. Port is not acquired by AzuraCast, not by another process. You can run second command I posted to set the value from command line.
Are you really, really sure you did not use the port in another station?

**Comment by bombelman** [comment]
> This should be OK. Port is acquired by AzuraCast, not by another process. You can run second command I posted to set the value from command line. Are you really, really sure you did not use the port in another station?

I just checked and re-checked.
I have 9 stations, none the 8 other stations use this port 8146 for DNAS, nor does any use one of these for the streamers/dj....
Did not run the command yet, more concerned about the root cause of this and happening in the future.
Any other uses for ports on Azura I could check ?

**Comment by bombelman** [comment]
> Is any of your stations DJ ports 1 port away from 8146?
> 
> If I remember correctly due to some shenanigans regarding which ports some DJ clients use, Liquidsoap listens on the configured DJ port and on the port after it. (Some DJ clients, when you enter for example 8145 will actually try to connect to 8146... no idea why some do that but it is what it is...)

no, not even close.

**Comment by BusterNeece** [comment]
@bombelman So you figured out the problem?

I've updated the Rolling Release to actually tell you _which_ station it considers to be in conflict with the station you're trying to edit. This should help narrow things down considerably in the future.
