### ISSUE TITLE
Media Bulk Import/Export: empty columns for Custom Cue Points

### ISSUE THREAD

**Issue by unudelaradio** [AzuraCast/AzuraCast#7274]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #02ecddc (2024-07-01 2:25)

### What happened?

Media Bulk Import/Export Tool doesn't work properly after recent AzuraCast changes and custom cue conversions. Custom Cue Points values are not exported or imported anymore.

**Comment by Moonbase59** [comment]
Confirm for Rolling Release #[b5c5c22](https://github.com/AzuraCast/AzuraCast/commit/b5c5c22b14292ef5f7d7a438f9cfbf6a6b3bb7c1) (2024-07-02 0:43).

Probably a regression due to the new `extra_metadata`.
