### ISSUE TITLE
Public page has no audio

### ISSUE THREAD

**Issue by ProgressiveDance** [AzuraCast/AzuraCast#7275]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.20.1 Stable

### What happened?

The public page shows the metadata just no audio...
![Azura](https://github.com/AzuraCast/AzuraCast/assets/174472077/f74d0230-a727-4a30-b680-dce76f19b3ab)

**Comment by BusterNeece** [comment]
@ProgressiveDance A ton of things can be causing this and we can't tell just from a screenshot of the page what's going on.

Try opening the browser console (usually F12 on the keyboard) and looking in the "Console" tab for errors. Paste any errors you see here.

Also try reaching out to your hosting provider for assistance.

**Comment by ProgressiveDance** [comment]
Thanks @BusterNeece no errors in the console. It says station offline on Dashboard page though.... Nextkast is connected. but yes the public page continues to show correct metadata. 

What about "Use Web Proxy" I have seen in another post with same issue.?? 

(@s7ntax You may need to enable the "Use Web Proxy" setting at the system level, because it's possible the system doesn't think it needs to be enabled when generating the URLs for the NowPlaying API but it does when you're pulling it from the profile page.)

Where can I find "Use Web Proxy" 

Thanks for your response @BusterNeece

**Comment by ProgressiveDance** [comment]
![Offline](https://github.com/AzuraCast/AzuraCast/assets/174472077/8de6395b-f899-456c-928b-b400cceec0bc)

**Comment by mdrxy** [comment]
> Where can I find "Use Web Proxy"

[I'd recommend reading the docs.](https://www.azuracast.com/docs/administration/cloudflare/#enabling-the-web-proxy-for-radio-broadcasts)

**Comment by kryptonmediagroup** [comment]
I have hit this very problem on several occasions, and it _always_ comes down to making sure the firewall on whatever it is you're using as a server has a hole punched in it for the stream you're trying to run.  This is not an Azuracast problem at all.  It's a firewall problem.

**Comment by Woolton** [comment]
> Thanks [@BusterNeece](https://github.com/BusterNeece) no errors in the console. It says station offline on Dashboard page though.... Nextkast is connected. but yes the public page continues to show correct metadata.
> 
> What about "Use Web Proxy" I have seen in another post with same issue.??
> 
> ([@s7ntax](https://github.com/s7ntax) You may need to enable the "Use Web Proxy" setting at the system level, because it's possible the system doesn't think it needs to be enabled when generating the URLs for the NowPlaying API but it does when you're pulling it from the profile page.)
> 
> Where can I find "Use Web Proxy"
> 
> Thanks for your response [@BusterNeece](https://github.com/BusterNeece)

Ironically, Use Web Proxy makes it so the public player has no audio and turning it off allows me to hear it on localhost.
