### ISSUE TITLE
Restart Broadcasting produces error, but station seems to start okay

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#7276]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #b5c5c22 (2024-07-02 0:43)

### What happened?

Whenever I _Restart Broadcasting_ on my main station (seldom on the others), it takes about a minute or so until the white progress bar at the top reaches the right end. Shortly after, "An error has occured" appears.

Nothing apparent in the logs I could find, and when waiting another minute or so and pressing F5 to refresh the page, the error and the orange "Restart Broadcasting" indicator in the left menu go away. The station then seems to operate normally.

This effect occurs since a few rolling release versions, can’t remember an exact version when it happened first.

![Nite Radio – Mozilla Firefox_043](https://github.com/AzuraCast/AzuraCast/assets/3706922/a78e1e27-aa28-4053-9ed0-d5bf35fe8e56)

**Comment by mdrxy** [comment]
Confirm for Rolling Release #b5c5c22 (2024-07-02 0:43) except it only takes ~5-10 seconds to restart and the error message flashes quickly - it is probably on screen for less than half of a second.

2 mount points, no Auto DJ, no media stored.

**Comment by gAlleb** [comment]
hmrhr! I can confirm this since 0.17.x. Don't see it as an issue though, just a minor design bug I'd say. This can happen on other pages too when "Saving".

**Comment by Moonbase59** [comment]
Ah, I get it. So maybe I only ever have the chance to _see_ it, because the Restart _takes so long_ on my main station! That is entirely possible. On station restart, there are usually several ultrashort messages crawling up, before the page reloads.

I’m generally a little unhappy about AzuraCast’s error messages. Most of them -auto-vanish so fast that one hasn’t a chance to read them before they’re gone. I wonder how elderly people or those with no or bad eyesight handle that.

If you don’t have a fast screenshot tool or can’t copy the long Liquidsoap error messages in "Edit Config" to an editor _real quick_ and then read in peace, you’ve lost… ;-)

**Comment by Moonbase59** [comment]
Minor issue then, just a few times more to hit F5.
Let’s close and concentrate on more important issues.

**Comment by BusterNeece** [comment]
@Moonbase59 Fairly minor change needed to fix this; just had to change how redirection works when bouncing you to that page. Previously we were pushing you over to the profile page, then doing a hard-refresh on the browser (to reload things like the sidebar menu), but I looked into it and it turns out you can just pull the URL of a route and just bounce straight to it. Easy!

**Comment by Moonbase59** [comment]
Gee, thanks! :heart:
