### ISSUE TITLE
Unable to reprocess new media

### ISSUE THREAD

**Issue by blindndangerous** [AzuraCast/AzuraCast#7279]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

369ce08

### What happened?

For the past few updates, I've been seeing this in my logs and my files seem to be stuck in processing.
 azuracast          | [2024-07-03T06:26:21.138772+00:00] AzuraCast.ERROR: Handling "App\Message\ReprocessMediaMessage" failed: mb_strtolower(): Argument #1 ($string) must be of type string, int given {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":124,"code":0} []                                                                                                                                                               
 azuracast          | 2024-07-03 06:26:21,158 INFO exited: php-worker (exit status 0; expected)

**Comment by BusterNeece** [comment]
@blindndangerous Thank you for the report and the logs. I've updated the code in the latest Rolling Release which is currently deploying. Would you mind updating (in a few minutes from the time of this post) to confirm that it fixes things for you?

**Comment by blindndangerous** [comment]
So far, so good after updating.
