### ISSUE TITLE
Greek Language

### ISSUE THREAD

**Issue by ElNadie** [AzuraCast/AzuraCast#728]
My problem its with greek title songs so if i upload any song with greek words in title after upload in my list  this title shows like this
![default](https://user-images.githubusercontent.com/42041208/44276702-f10c5200-a250-11e8-8cde-9ad00955b286.png)
so the right title is not that...
i tried to change char collation with Navicat with greek_general_ci instead UTF8 but the problem still yet

**Comment by Likeandfeel** [comment]
Hi ElNadie 

Please can you try to update name of your song with programm like https://picard.musicbrainz.org/
And be sure to get inside Song Meta the correct name ? 

Sometine encoding of song name is not correct and came from Os system encoding.
Some software as this one can fix for you issue. I send you some configuration you can use.

Please can you make the test ? 
Thanks


![capture d ecran 2018-08-22 a 16 20 15](https://user-images.githubusercontent.com/23337598/44469234-52546c80-a627-11e8-9afb-b2863b95804d.png)
![capture d ecran 2018-08-22 a 16 20 32](https://user-images.githubusercontent.com/23337598/44469235-52546c80-a627-11e8-8f9d-5e8354d10f46.png)

**Comment by CodeSteele** [comment]
As far as I know: UTF-8 encoded ID3v2 tags work fine, and this sometimes happens if the encoding is ISO-8859-1.

You _should_ be able to use the metadata editor on the UI to fix this too.

If neither method works @ElNadie please reopen this issue.
