### ISSUE TITLE
Custom Field issue: Cannot read index because it doesn't implement \ArrayAccess

### ISSUE THREAD

**Issue by RM-FM** [AzuraCast/AzuraCast#7280]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #bc976f3

### What happened?

After upgrading to https://github.com/AzuraCast/AzuraCast/commit/bc976f3c793d61ff902eadc80a510f8e02fdf575, it seems that there is an issue with existing custom fields in the media management. Below error occurs if I try to change the sorting of the custom field column `import_date`.

Btw: I would love to see this field implemented in Azuracast natively.

### Relevant log output

```shell
Cannot read index "import_date" from object of type "App\Entity\Api\HashMap" because it doesn't implement \ArrayAccess.
```

**Comment by BusterNeece** [comment]
@RM-FM Should be fixed in the latest Rolling deploying right now.

You should submit the second item (adding a `import_date` to the entity) as a feature request, as it's something we'd love to do and I don't want to lose track of it.
