### ISSUE TITLE
Crossfade Duration in AutoDJ Settings overrides custom Start Next (`liq_cross_start_next`)

### ISSUE THREAD

**Issue by unudelaradio** [AzuraCast/AzuraCast#7281]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #369ce08 (2024-07-02 19:51)

### What happened?

Custom Start Next (`liq_cross_start_next`) in Advanced Edit Media shouldn't be prioritized?

When i set my Start Next and Fade Out points in Advanced Media, the default value in Normal Mode, in AutoDJ settings should be ignored (am i right?).

Now it seems that Crossfade Duration from AutoDJ setiings is prioritized.

How to reproduce:
- Edit Custom Cue Points in Advanced Media
- Enable `Crossfade Method > Normal` in AutoDJ settings. (Crossfade Duration overrides Custom Cue Points - this is the intended bahaviour?)

Mentions: 
- i don't have AutoCue enabled
- don't have any custom Liquidsoap config

**Comment by Moonbase59** [comment]
@unudelaradio Using `liq_cross_duration` (which we mis-used in old releases for the overlap duration) has been deprecated for users, it’s now declared internal.

We now use `liq_cross_start_next`, which works nicely with the autocue implementations, but _not_ with the older simple and smart crossfades.

I’m currently testing your situation (Autocue disabled, Crossfade Method "Normal Mode", Crossfade duration 0.1 s), and try to devise a work-around, which could possibly be implemented within AzuraCast.

**Comment by unudelaradio** [comment]
> I’m currently testing your situation (Autocue disabled, Crossfade Method "Normal Mode", Crossfade duration 0.1 s), and try to devise a work-around, which could possibly be implemented within AzuraCast for users that do not wish to enable Autocue.

I would be very grateful if you could help me and, of course, all the other users encountering these issues! I apreciate all your work for the new AutoCue feature. But i hope there is a work-around for what it used to be a native functionality in AzuraCast.

Visual Cue Editor and Custom Cue Points would become useful ONLY for AutoCue and not anymore for the classic Azuracast Crossfade Methods (Normal Mode especially, which worked okay in the past with the custom cue points).

**Comment by Moonbase59** [comment]
I agree. Autocue is advanced functionality but of course _optional_. The values we set in the Advanced tab or Visual Cue Editor or file tags should work as intended, even without Autocue enabled.

**Comment by Moonbase59** [comment]
@BusterNeece Devised a solution. It reinstates the old `liq_cross_duration` for non-Autocue setups. With Autocue, that value is set by the LS autocue integration layer and we mustn’t touch it.

Here is a diff against the Liquidsoap [ConfigWriter.php](https://github.com/AzuraCast/AzuraCast/blob/369ce080758f8af9579b6c1aaabbbbb9937df65f/backend/src/Radio/Backend/Liquidsoap/ConfigWriter.php#L36):

[ConfigWriter.php.diff.zip](https://github.com/user-attachments/files/16089975/ConfigWriter.php.diff.zip)

I used `patch` to patch the `ConfigWriter.php` with this diff, and it created all the right crossfading configurations.

The patch will:
- Add the `show_meta` to Autocue and non-Autocue setups, for better diagnosis.
- Add `media_id` to the values shown by `show_meta`, to be able to quickly lookup a song via the API.
- Reinstate a (self-calculated) `liq_cross_duration` for non-Autocue setups with crossfade mode "normal" or "smart".

Testing done:
- Using Rolling Release #[b5c5c22](https://github.com/AzuraCast/AzuraCast/commit/b5c5c22b14292ef5f7d7a438f9cfbf6a6b3bb7c1) (2024-07-02 0:43)
- Patch `/var/azuracast/www/backend/src/Radio/Backend/Liquidsoap/ConfigWriter.php` with the diff.
- Our Autocue test files set
- No Autocue, no crossfade
- No Autocue, normal crossfade, 0.1 and 2.5 s
- No Autocue, smart crossfade, 0.1 and 2.5 s
- Autocue 4.0.5
- Check the generated Liquidsoap configuration for each configuration
- Test playout, recording & checking logs for each configuration

Result:
- All sounding good, and behaving as expected.

Let me know!

**Comment by unudelaradio** [comment]
Hello! Lots of thanks for solving this issue!

One more small detail that i noticed, after testing _No Autocue, Normal Crossfade, 0.1_

Even if my `fade in` is set to `0` in _Advanced Media_ for each track, that `0.1` _chop effect_ is still present on the first beat of every song. Trying to understand if this is intented behavior, or a missed detail. Or maybe a compromise to avoid some issues?

The same effect can also be heard on AutoCue. There is not a _clean `0` fade in_. But a tiny little chop (a 0.1 fade in effect) on the first beat of the songs.

Try to reproduce this with a song with no blank at the begining... with a beat, an abrupt begining. Hope you understand my point.

**Comment by Moonbase59** [comment]
Thank you for bringing it up and testing. And the other thing ;-)

I fear the 0.0/0.1 problem to be a Liquidsoap issue, they could never handle 0.0/0.1 in a good way. Maybe because it is not possible to set up a fade, fade curve, and everything in _zero_ time. Don’t really know, hope it can be fixed in LS 2.3.0, when that’s ready.

I typically set my fades to `0.1`, @RM-FM even prefers `0.2`, trying to avoid this issue.

Using Autocue, on my radio, I don’t really hear these, but that may be due to almost all of my files having a little silence at start and end.

**Comment by unudelaradio** [comment]
Oh, i understand... so `0.1` is the best option, the lowest value, we can have for now, for fade in, either for AutoCue or the classic Normal Mode. Earlier i thouth i could trick it, and set `0.001`, but two or more decimals are not allowed in AutoDJ Settings for Crossfade Duration. 

After that, i tried to do the same in Media Advanced Tab (where multiple decimals are allowed now), even if all my songs already have `0` value in _Fade In_ field. 

No luck with `0.001`.

@RM-FM created a LS config code that worked perfectly for me in v.19.7. With clean `0` fades at the start of every track.

Is there any chance that this custom code could be rebuild/adapted after last night changes in AzuraCast?

```
def clean_transition(old, new) =

  def safe_float_of_string(str) =
    try
      float_of_string(str)
    catch _ do
      0.
    end
  end

  cross_duration = safe_float_of_string(old.metadata["liq_cross_duration"])
  fade_out = safe_float_of_string(old.metadata["liq_fade_out"])
  fade_in = safe_float_of_string(new.metadata["liq_fade_in"])
  log_label = "clean_transition"
    
  let fade.out = fun (s) -> fade.out(type="exp", duration=fade_out, s)
  let fade.in = fun (s) -> fade.in(type="log", duration=fade_in, s)

  add = fun (a, b) -> add(normalize=false, [b, a])
  sequence = fun (a, b) -> (sequence([a, b]) : source)

  if cross_duration > 0. then
    log(label= log_label,"Crossfade. Duration: #{cross_duration}. Fade out: #{fade_out}. Fade in: #{fade_in}.")
    if fade_out > 0. and fade_in > 0. then 
      add(fade.out(old.source), fade.in(new.source))
    elsif fade_out > 0. and fade_in <= 0. then 
      add(fade.out(old.source), new.source)
    elsif fade_out <= 0. and fade_in > 0. then 
      add(old.source, fade.in(new.source))
    else
      add(old.source, new.source)
    end
  else
    log(label= log_label,"Sequence. Fade out: #{fade_out}. Fade in: #{fade_in}.")
    if fade_out > 0. and fade_in > 0. then 
      sequence(fade.out(old.source), fade.in(new.source))
    elsif fade_out > 0. and fade_in <= 0. then 
      sequence(fade.out(old.source), new.source)
    elsif fade_out <= 0. and fade_in > 0. then 
      sequence(old.source, fade.in(new.source))
    else
      sequence(old.source, new.source)
    end
  end

end

radio = cross(clean_transition,radio)
```

**Comment by RM-FM** [comment]
@unudelaradio Please try again with the latest Azuracast Rolling Release. It seems that @BusterNeece brought back `liq_cross_duration` for non-autocue installations (https://github.com/AzuraCast/AzuraCast/commit/a236a7c2f098129516eb22c0b20014248d7e6fe9). With that, my "clean transistion" script should work again.

**Comment by unudelaradio** [comment]
@RM-FM I tried with the latest Azuracast Rolling Release. I've made every possible test. Custom Cue Points are working fine _only_ with native _Normal Crossfade_ after the changes suggested by @Moonbase59 

I tried to Disable Crossfading in AutoDJ settings and use your old custom script again, but nothing happens. 

The only thing that still bothers me is i can't get clean 0.0 _fade in_ transitions even if all my tracks have 0 _fade in_ value in Edit Media > Advanced. The best i can get is _0.1 fade in._

And unfortunalely, i have lots of songs and jingles starting with a beat very close to Cue In: so the _0.1 chop effect_ is annoying for OCD guys like me.

**Comment by unudelaradio** [comment]
I just discovered something that makes things work: i get clean `0.0` fades!

Testing and playing around with LS config boxes i just placed Stereo Tool code in the 3rd box, before crossfade code.

This:
```
# Stereo Tool Pipe
radio = stereotool(
    library_file="/var/azuracast/storage/stereo_tool/libStereoTool_arm64.so",
    license_key="",
    preset="/var/azuracast/stations/testradio/config/stereo-tool.sts",
    radio
)
```

Before this:
(which is generated by Azuracast)

```
# Apply amplification metadata (if supplied)
radio = amplify(override="liq_amplify", 1., radio)

# reinstate liq_cross_duration if AutoCue is disabled
def set_cross_duration(m) =
    fade_out = float_of_string(default=0., m["liq_fade_out"])
    duration = float_of_string(default=0., m["duration"])
    cue_out = float_of_string(default=duration, m["liq_cue_out"])
    start_next = float_of_string(default=cue_out, m["liq_cross_start_next"])
    cross_duration = max(cue_out - start_next, fade_out)
    log(level=4, label="set_cross_duration", "Setting liq_cross_duration=#{cross_duration}")
    
    if cross_duration > 0. then
        [("liq_cross_duration", "#{cross_duration}")]
    else
        []
    end
end
radio = metadata.map(set_cross_duration, radio)

# Show metadata in log (Debug)
def show_meta(m)
    label="show_meta"
    l = list.sort.natural(metadata.cover.remove(m))
    list.iter(fun(v) -> log(level=4, label=label, "#{v}"), l)

    nowplaying = ref(m["artist"] ^ " - " ^ m["title"])

    if m["artist"] == "" then
        if string.contains(substring=" - ", m["title"]) then
            let (a, t) = string.split.first(separator=" - ", m["title"])
            nowplaying := a ^ " - " ^ t
        end
    end

    # show `liq_` & other metadata in level 3
    def fl(k, _) =
        tags = ["duration", "media_id", "replaygain_track_gain", "replaygain_reference_loudness"]
        string.contains(prefix="liq_", k) or list.mem(k, tags)
    end

    liq = list.assoc.filter((fl), l)
    list.iter(fun(v) -> log(level=3, label=label, "#{v}"), liq)
    log(level=3, label=label, "Now playing: #{nowplaying()}")

    if m["liq_amplify"] == "" then
        log(level=2, label=label, "Warning: No liq_amplify found, expect loudness jumps!")
    end
    if m["liq_blank_skipped"] == "true" then
        log(level=2, label=label, "Blank (silence) detected in track, ending early.")
    end
end

radio.on_metadata(show_meta)

def live_aware_crossfade(old, new) =
    if to_live() then
        # If going to the live show, play a simple sequence
        sequence([fade.out(old.source),fade.in(new.source)])
    else
        # Otherwise, use the smart transition
        cross.simple(old.source, new.source, fade_in=3.00, fade_out=3.00)
    end
end

radio = cross(minimum=0., duration=4.50, live_aware_crossfade, radio)
```

Now i'm wondering how Stereo Tool code can fix things? Maybe there's another way of fixing this, another code which actually could fix things. Stereo Tool does something there... **_`0.0` fade in_** is back.
