### ISSUE TITLE
Advanced track edit: Values have 2 decimals, only 1 allowed. Tooltips wrong language.

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#7282]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #b5c5c22 (2024-07-02 0:43)

### What happened?

The _Advanced_ tab of edit media accepts only 1 decimal digit, but most values shown internally have 2 decimals (or more) precision. Don ’t really know what to do here, maybe _allow_ 2 decimals (probably seldom needed), but have the up/down still do 0.1 increments?

I just fear we might "destroy" carefully pre-tagged values here, that’s mainly it.

Also the tooltip has the wrong language: My AzuraCast is set to English, my system language is German, and it should display in the language the AzuraCast user has set.

![Auswahl_465](https://github.com/AzuraCast/AzuraCast/assets/3706922/cb3a9927-092b-4ef7-8856-005adc1903f5)

**Comment by BusterNeece** [comment]
@Moonbase59 Updated the code to expand to support any level of decimals. The tooltip is something your browser is doing, not something we're doing, so we don't control its localization.

**Comment by Moonbase59** [comment]
Really? Including the values? Interesting. Another new thing learned, thanks for the hint!
