### ISSUE TITLE
Visual Cue Editor (VCE) shows wrong cue/fade points in default zoom

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#7283]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #b5c5c22 (2024-07-02 0:43)

### What happened?

The Visucal Cue Editor (VCE) shows wrong data points/markings in the default zoom. Only when you start zooming in, the correct colored areas are displayed.

Short video to show it:

https://github.com/AzuraCast/AzuraCast/assets/3706922/b9e00da2-d6f2-466d-a9d2-3c4a710a5775

Another example:

Here is a test file that in reality looks like this:

![Erste Spur005](https://github.com/AzuraCast/AzuraCast/assets/3706922/0c677b90-5292-435a-90df-cf152781eaa1)

[test-5-15-5-15-5s.mp3.zip](https://github.com/user-attachments/files/16086017/test-5-15-5-15-5s.mp3.zip)

And this is what we get in the VCE: Full waveform not shown until zooming, no scrollbar present.

https://github.com/AzuraCast/AzuraCast/assets/3706922/59b9ae7f-be2d-4a82-b691-c214eb89069e

**Comment by Gasparmejor** [comment]
First of all: I love Azuracast, thanks for all your work.

I experience the same issue as described above. I would like to add that ever since this problem occurred clicking around in the visual editor while playing to skip to another part of a song does no longer work while zoomed in. When zoomed out, you can click around while playing the song, but a soon as you're zoomed in (no matter how far) this no longer works. 

I'm not sure if it's a bug or a feature, but since I discovered it at the same time as the bug reported above, perhaps it's related. If not, sorry for the confusion.

**Comment by Moonbase59** [comment]
To me, it looks like the initial zoom is just not displaying the complete waveform. That could also explain the wrong overlap area shown in the first video.

@Gasparmejor Jumping the playhead around while playing works for me, zoomed in or not. Tested on Rolling Release #[b5c5c22](https://github.com/AzuraCast/AzuraCast/commit/b5c5c22b14292ef5f7d7a438f9cfbf6a6b3bb7c1) (2024-07-02 0:43).

**Comment by Gasparmejor** [comment]
@Moonbase59 Thanks for your reply. I did some more testing and I get the same unwanted behavior in Safari 17.5 and Chrome 126.0.6478.127. However in Firefox 127.0.2 jumping around while playing works fine, just as it used to do in Safari. Guess I'll be using Firefox for now. 

I'm on Rolling Release #944fa6d (2024-07-04 0:59)

**Comment by unudelaradio** [comment]
> The Visucal Cue Editor (VCE) shows wrong data points/markings in the default zoom. Only when you start zooming in, the correct colored areas are displayed.

> clicking around in the visual editor while playing to skip to another part of a song does no longer work while zoomed in.

Tested in Brave and Edge, i have the same (both) problems.

**Comment by Moonbase59** [comment]
Confirm for Chromium Version 126.0.6478.126: No playhead jumping.
Edge 126.0.2592.81 on Win10 works.
I originally quick-tested on Firefox 127.0.2, where playhead jumping works.

Couldn’t yet find if there is a difference between using the binary vs. JS for the waveform calculation and wrong zoom/region display. (The binary can’t do all file types.)

**Comment by BusterNeece** [comment]
It appears that this was an upstream bug with Wavesurfer, as I was able to confirm some weirdness at the default zoom level myself, and updating to the latest minor point release of Wavesurfer (as is deployed in the latest RR) seems to have resolved it for me.

**Comment by Moonbase59** [comment]
Confirm for Rolling Release #[ba75595](https://github.com/AzuraCast/AzuraCast/commit/ba755951485c9c5ba7322dd1d486db57e8e65049) (2024-07-09 4:02).

Both default zoom & zoomed in display correct again.

Playhead jumping when zoomed in still doesn’t work on Chromium 126.0.6478.126. In Firefox 127.0.2 it works.
