### ISSUE TITLE
Incorrect date on Dashboard charts

### ISSUE THREAD

**Issue by bombelman** [AzuraCast/AzuraCast#7294]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

v0.20.1 Stable / Docker / PHP 8.3

### What happened?

I migrated from a server in USA to a server in EU.
All went well and is up and running already.

When I made the backup it was the 16th of the month,
by the time the backup finished transferring it was already the next day (17th) on the new server.
While the date on the server is set correctly, I get stats with a day behind in the charts,
I'm guessing there is a missing row in the DB caused by the backup/restore.

Is there a way to manually fix this or is it something that can be fixed with an update?
I'm guessing when I would restore an install from an even older backup, this difference would be much greater also, which should not happen.

Tnx.

additional info:
Today when posting this, it's july 4th,
the graph show jully 3rd as the last date.

**Comment by bombelman** [comment]
at noon today (UTC) on July 5th, which date should be the last to be shown on the graph?

**Comment by bombelman** [comment]
At this time, the new day (July 5th) has just started.
The (latest) stats showing, for today, are a day behind, and showing on July 4th.

![Screenshot 2024-07-05 015501](https://github.com/AzuraCast/AzuraCast/assets/107536852/786b1926-0aa0-4e73-915e-d2b1b1edbdfd)

**Comment by BusterNeece** [comment]
@bombelman Ah, it seems it's trying to render dates on time series databases in your local timezone (local to the browser), not UTC which they actually are, so they're often off by a day. This should be fixed in the latest Rolling Release.
