### ISSUE TITLE
Timed out waiting for services to start on installation

### ISSUE THREAD

**Issue by Partymann2000** [AzuraCast/AzuraCast#7298]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

i tested the latest stable and Rolling

### What happened?

![image](https://github.com/AzuraCast/AzuraCast/assets/53320411/eacd95fd-c11d-427f-a0ff-15d615f0faaa)

**Comment by Partymann2000** [comment]
I have tried to find the error, I have switched to my docker container and looked where the officebllem is located, the problem is that mariedb is there but no mysql so qwhen I e.g. the command mysql --version amche it does not work

1. cd /var/azuracast/
2. docker exec -it azuracast bash
3. mariadb --version (OUTPU: mariadb from 11.2.4-MariaDB, client 15.2 for debian-linux-gnu (x86_64) using  EditLine wrapper)
4. mysql --version (OUTPUT: bash: mysql: command not found

i mean its a prob with the install from mysql)

**Comment by Partymann2000** [comment]
How to solve the problem, would be if someone sends me a freshly installed version as `.zip` from the directory `/var/lib/docker/volumes/*`

**Comment by BusterNeece** [comment]
@Partymann2000 Can you show the logs from further up in the process, before it starts waiting for services to start? It's possible MariaDB simply isn't starting for some reason, so the timeout makes sense.

**Comment by Partymann2000** [comment]
I found the prob, thx
