### ISSUE TITLE
SSL install issue on docker !

### ISSUE THREAD

**Issue by JustIrinel** [AzuraCast/AzuraCast#730]
Hi there, I have a website named edmromania.ro that is hosted on a shared webhosting.
I've made one A record to my Azuracast server IP 37.251.160.193  (radio.edmromania.ro)
Now I want to install SSL certificate for radio.edmromania.ro 
I go : cd /
./docker.sh letsencrypt-create

After I receive error message : 

> - The following errors were reported by the server:
> 
>    Domain: radio.edmromania.ro
>    Type:   unauthorized
>    Detail: Invalid response from
>    http://radio.edmromania.ro/.well-known/acme-challenge/foW4PFqPJ1vc-O6Je-8rXhT3zgZ0ga4m15Qnatk5DZQ:
>    "<html>
>    <head><title>404 Not Found</title></head>
>    <body bgcolor="white">
>    <center><h1>404 Not Found</h1></center>
>    <hr><center>"
> 
>    To fix these errors, please make sure that your domain name was
>    entered correctly and the DNS A/AAAA record(s) for that domain
>    contain(s) the right IP address.
> -------------------------------------------------------------------------------
> Re-enter the domain name that was entered in the previous step:

Now, what can I do ? I mention that I've read this guide https://github.com/AzuraCast/AzuraCast/issues/364 but it doesen't work due to the fact that on docker there is no azuracast folder like on traditional...

**Comment by SlvrEagle23** [comment]
@JustIrinel Sometimes DNS changes take quite a while to propagate out through the Internet. Services like CloudFlare have little tricks they do to make it go faster, but other registrars may not be nearly as quick to update.

From my end, it looks like your domain is working fine now. You should try the LetsEncrypt process again and see if it works this time.

**Comment by JustIrinel** [comment]
Hi there, now it's ok ! Thank you so much, I will grab a coffe for you :) 👍 +1 for your patience.
