### ISSUE TITLE
Azure: Killed VM after installation

### ISSUE THREAD

**Issue by B4sicallyF0x** [AzuraCast/AzuraCast#7303]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

I installed AzuraCast in a newly created VM in Azure. I followed this guide https://www.azuracast.com/docs/getting-started/installation/docker/. After the installation, I can't access my machine via SSH anymore. Rebooting doesn't fix the problem. I had to completely delete the VM.

**Comment by JulianvanD** [comment]
this is likely a problem on your side, but certainly not on azuracast's side. i've never had this happen and i tried to recreate this, but nothing like what you said happened to me, even after leaving the vm for hours.

**Comment by B4sicallyF0x** [comment]
Will try to make a screen recording when I got time

**Comment by BusterNeece** [comment]
@B4sicallyF0x We're going to need a fair amount more information to be able to really tell whether this is something on our end or something on yours. In particular, we'd need to see some logs from the server indicating what's happening. You may be able to see some logs from a rescue console even if you can't directly connect via SSH.

**Comment by B4sicallyF0x** [comment]
@BusterNeece The problem is that once it loses the connection, I am not able to connect again, I lose the SSH connection, it disconnects from the CloudFlare tunnel, and I cannot connect from Azure. Even restarting the machine doesn't work again.
