### ISSUE TITLE
Now playing not updating with live dj

### ISSUE THREAD

**Issue by Eyecu** [AzuraCast/AzuraCast#7305]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#60088c6

### What happened?

Updated this morning and when a live DJ goes on the air the now playing both for API and in the azuracast web interface isn't updating with the current song playing, Autodj is working fine and everything updates when the song changes. Just not for live dj.

**Comment by BusterNeece** [comment]
@Eyecu It's a known issue that metadata doesn't update on the initial connection. It seems we're having that same issue coming up again.

@toots Sorry to ping you on this, but it looks like the `replay_metadata` isn't actually replaying metadata in this case...or for some reason, it's not firing off the `on_metadata` event despite actually having metadata from the DJ when the transition happens:

```
2024/07/09 00:45:19 [input_streamer:3] New metadata chunk Tom Walker -- Leave a Light On.
[opus @ 0x7f45c3064c00] Could not update timestamps for skipped samples.
2024/07/09 00:45:24 [live_fallback:3] Switch to metadata_map.2 with transition.
2024/07/09 00:45:24 [metadata_map.5:3] Inserting missing metadata.
2024/07/09 00:46:07 [input_streamer:3] New metadata chunk Suzanne Vega -- Tom's Diner.
2024/07/09 00:46:13 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/9/liquidsoap/feedback' with body: {"artist":"Suzanne Vega","title":"Tom's Diner"}
2024/07/09 00:46:13 [lang:3] API feedback - Response (200): true
2024/07/09 00:47:27 [input_streamer:3] New metadata chunk Toto -- Africa.
2024/07/09 00:47:33 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/9/liquidsoap/feedback' with body: {"artist":"Toto","title":"Africa"}
2024/07/09 00:47:33 [lang:3] API feedback - Response (200): true
```

Here's a relevant chunk of the AzuraCast auto-generated code:

```
# A Pre-DJ source of radio that can be broadcast if needed
radio_without_live = radio
ignore(radio_without_live)

# Live Broadcasting
live = input.harbor("/", id = "input_streamer", port = 8005, auth = dj_auth, icy = true, icy_metadata_charset = "UTF-8", metadata_charset = "UTF-8", on_connect = live_connected, on_disconnect = live_disconnected, buffer = 5.00, max = 10.00)

def insert_missing(m) =
    if m == [] then
        [("title", "Live Broadcast"), ("is_live", "true")]
    else
        [("is_live", "true")]
    end
end
live = metadata.map(insert_missing, live)

radio = fallback(id="live_fallback", track_sensitive=false, replay_metadata=true, [live, radio])

# Skip non-live track when live DJ goes live.
def check_live() =
    if live.is_ready() then
        if not to_live() then
            to_live.set(true)
            radio_without_live.skip()
        end
    else
        to_live.set(false)
    end
end

# Continuously check on live.
radio = source.on_frame(radio, check_live)

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

error_file = single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")

def tag_error_file(m) =
    ignore(m)
    [("is_error_file", "true")]
end
error_file = metadata.map(tag_error_file, error_file)

radio = fallback(id="safe_fallback", track_sensitive = false, [radio, error_file])

# Send metadata changes back to AzuraCast
last_title = ref("")
last_artist = ref("")

def metadata_updated(m) =
    def f() =
        if (m["is_error_file"] != "true") then
            if (m["title"] != last_title() or m["artist"] != last_artist()) then
                last_title.set(m["title"])
                last_artist.set(m["artist"])
                
                # Only send some metadata to AzuraCast
                def fl(k, _) =
                    tags = ["song_id", "media_id", "playlist_id", "artist", "title"]
                    string.contains(prefix="liq_", k) or string.contains(prefix="replaygain_", k) or list.mem(k, tags)
                end
                
                feedback_meta = list.assoc.filter((fl), metadata.cover.remove(m))
                
                j = json()
                for item = list.iterator(feedback_meta) do
                    let (tag, value) = item
                    j.add(tag, value)
                end
                
                _ = azuracast_api_call(
                    "feedback",
                    json.stringify(compact=true, j)
                )
            end
        end
    end

    thread.run(f)
end

radio.on_metadata(metadata_updated)
```

Anything sticking out there that we might be doing wrong? I assumed the `replay_metadata` flag on the live fallback would take care of this particular issue, but in my testing it didn't.

**Comment by Eyecu** [comment]
Thanks for letting me know @BusterNeece Also not sure if this is related or if I should open another ticket cause for me both things started with the same update but after updating now or restarting docker or rebooting the machine some of the services don't start and I have to go into the administration and restart them they are cron nginx php-nowplaying php-worker sftpgo centrifugo

**Comment by BusterNeece** [comment]
@Eyecu Should be a separate issue, and I"d need logs on that too, namely from `docker-compose logs -f web` on the host as services are starting up.

**Comment by Eyecu** [comment]
okay will do.

**Comment by Eyecu** [comment]
Just an update to this, seems like it's something to do with the new autocue feature causing this. When autocue is enabled the nowplaying with live DJ doesn't update. when it's disabled, everything works as it should.

**Comment by toots** [comment]
Hi.

I don't think that `replay_metadata` would help here as it looks like y'all are missing the first ever metadata on the source.

Yes, the mechanism for passing metadata is a little fragile in that a metadata could be lost of the very first chunk of content from the live is lost for some reason, there's no redundancy for it.

Typically, the problem could very likely be caused by `check_live` introducing a single frame lag before switching to the `live` source.

Meanwhile, I would recommend trying something to harness this. The idea would be to remember the last metadata on the live source and re-inject it manually each time you switch back to it. Something like this:

```liquidsoao
last_live_meta = ref([])

def insert_missing(m) =
   updates = 
      if m == [] then
          [("title", "Live Broadcast"), ("is_live", "true")]
      else
          [("is_live", "true")]
      end
  end
  last_live_meta := [...m, ...updates]
  
  updates
end
live = metadata.map(insert_missing, live)

live = insert_metadata(live)

def insert_latest_live_metadata() =
  live.insert_metadata(last_live_meta())
end

def to_live(_, s) =
  insert_latest_live_metadata()
  s
end
  
def to_radio(_, s) = s end

radio = fallback(
  id="live_fallback",
  track_sensitive=false,
  replay_metadata=true,
  transitions=[to_live, to_radio],
  [live, radio]
)
```

**Comment by BusterNeece** [comment]
@toots Thank you for the code snippet. In my local tests, this greatly improves the reliability of receiving the initial metadata when transitioning to a live DJ.

This may indeed have fixed an issue we've had for...well, years honestly. :)

**Comment by hwalker928** [comment]
Does this solve the issue of metadata not updating at all?

**Comment by Aealyn** [comment]
> Does this solve the issue of metadata not updating at all?

No... This issue is not solved....

**Comment by BusterNeece** [comment]
@hwalker928 @Aealyn You're going to have to give us more information here.

**Comment by hwalker928** [comment]
I'm currently experiencing the now playing completely freezing on whatever the AutoDJ last played when a live streamer connects.

**Comment by Aealyn** [comment]
@BusterNeece https://github.com/AzuraCast/AzuraCast/issues/7320 
I have described everything in detail here.

**Comment by Aealyn** [comment]
But I have now discovered that it also affects the IceCast servers.

**Comment by BusterNeece** [comment]
@Eyecu You may also want to update to the latest Rolling after improvements made in the other related issue.

**Comment by Eyecu** [comment]
Just did @BusterNeece when we have a DJ go on I'll Check if things are working but I'm sure you guys got it. Thank You

**Comment by Eyecu** [comment]
Finally had a dj go on and everything is working the way it should now. Thanks @BusterNeece @toots greatly appreciated
