### ISSUE TITLE
CORS issue with stream only on Safari

### ISSUE THREAD

**Issue by dimitriaatos** [AzuraCast/AzuraCast#7308]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.20.1

### What happened?

Safari is failing to load azuracast's stream, I've tried tweaking the station's nginx.conf (/var/azuracast/stations/example/config/nginx.conf) but the changes don't seem to take effect.

This is how I'm trying to access the stream:
```html
<audio crossorigin="anonymus" src="https://azuracast.example.com:8010/radio.mp3"/>
```

### Relevant log output

```shell
Cross-origin redirection to https://azuracast.example.com:8010/radio.mp3?_ic2=1720543447794 denied by Cross-Origin Resource Sharing policy: Origin https://example.com is not allowed by Access-Control-Allow-Origin. Status code: 302

Failed to load resource: Cross-origin redirection to https://azuracast.example.com:8010/radio.mp3?_ic2=1720543447794 denied by Cross-Origin Resource Sharing policy: Origin https://example.com is not allowed by Access-Control-Allow-Origin. Status code: 302
```

**Comment by dimitriaatos** [comment]
It seems that Safari doesn't like wildcards like `Access-Control-Allow-Origin '*';`. I've tried changing it but I think I'm doing something wrong with the nginx config. What would be the right way to add a header to the mounting point of a station?

**Comment by RadioFlamingo** [comment]
Since the last update from IOS i've got the same problem
