### ISSUE TITLE
Reports data

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#731]
**Installation method**
Traditional

**Host OS (for Docker installations)**
Ubuntu 18.04.1

**Describe the bug**
Hello,
In the panel, in the "reports" menu, the map with the names of the countries appears, but now, after the last updates, it no longer appears.

Attached PrintScreen
![live_listeners](https://user-images.githubusercontent.com/7109309/44303481-e1b50380-a339-11e8-9d4d-b4d03cb879dc.jpg)

**Comment by Likeandfeel** [comment]
Hi

same issue
We get only name if we are on the point / spot

![capture d ecran 2018-08-22 a 16 14 39](https://user-images.githubusercontent.com/23337598/44468954-b75b9280-a626-11e8-842c-3223c32b69ff.png)
