### ISSUE TITLE
High CPU consumption AzuraCast 0.20.1

### ISSUE THREAD

**Issue by Cris247R** [AzuraCast/AzuraCast#7313]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.20.1

### What happened?

We have two radio stations with a music base somewhere around 50 GB each. Each Server has a 6 vCore configuration of course from two different providers and we noticed the following situation:

The moment you have a large music base and you perform a search in the Media section the CPU level reaches the Maximum. The same thing happens when you add more songs in a playlist.

CPU resource consumption should be investigated with the new AzuraCast version. I have been using AzuraCast on a smaller 4vCore configuration without any problems and have not had these problems with this program. 

Please investigate what is causing this excessive CPU consumption with this update. AzuraCast 0.20.1

Thank you and appreciate all your efforts

**Comment by hwalker928** [comment]
What provider(s) are you using?

**Comment by Cris247R** [comment]
Hetzner and Contabo. I also use OVH Cloud but there I have an older version 0.19.0 and there are no problems.

**Comment by hwalker928** [comment]
There do appear to be issues with Contabo - as I experienced this myself, and mentioned in #7207. Contacting their support fixed it for me.
