### ISSUE TITLE
Port number: api/nowplaying_static.json and api/nowplaying are not coherent

### ISSUE THREAD

**Issue by BornKillaz** [AzuraCast/AzuraCast#7316]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #dd73f87

### What happened?

The static nowplaying JSON file does not include the port number in all URLs, except for the listen_url.
http://your-azuracast-site.example.com/api/nowplaying_static/station_shortcode.json

The dynamic nowplaying file does not have this problem.
http://your-azuracast-site.example.com/api/nowplaying/station_shortcode

### Relevant log output

```shell
Not applicable
```

**Comment by mdrxy** [comment]
I'm not able to recreate this - can you give more details regarding your station config + screenshots?
