### ISSUE TITLE
AzuraCast.ERROR: ACME Error: Certificate does not need renewal.  Let´s Entcrypt SSL

### ISSUE THREAD

**Issue by RadioHerzblut** [AzuraCast/AzuraCast#7317]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #[dd73f87](https://github.com/AzuraCast/AzuraCast/commit/dd73f878963055e4d613ba81fba9720507fac450) (2024-07-11 15:55) • Docker • PHP 8.3

### What happened?

Hello,

the certificate is no longer recognized and I have no SSL connection. Even a renewal does not work. Let's Entcrypt recognizes as in the log that this is not necessary.

Is there a solution here?  I have already restarted my server. 

[2024-07-12T04:52:05.994858+00:00] AzuraCast.DEBUG: ACME: Using directory URL: https://acme-v02.api.letsencrypt.org/directory [] []
[2024-07-12T04:52:06.005614+00:00] AzuraCast.ERROR: ACME Error: Certificate does not need renewal. {"exception":"[object] (RuntimeException(code: 0): Certificate does not need renewal. at /var/azuracast/www/backend/src/Service/Acme.php:138)"} []

### Relevant log output

```shell
[2024-07-12T04:52:05.994858+00:00] AzuraCast.DEBUG: ACME: Using directory URL: https://acme-v02.api.letsencrypt.org/directory [] []
[2024-07-12T04:52:06.005614+00:00] AzuraCast.ERROR: ACME Error: Certificate does not need renewal. {"exception":"[object] (RuntimeException(code: 0): Certificate does not need renewal. at /var/azuracast/www/backend/src/Service/Acme.php:138)"} []
```

**Comment by skoerfgen** [comment]
You could check the current certificate using openssl like this:

```
openssl x509 -noout -text -in acme.crt
```
What does `Issuer`and `Validity` say?

**Comment by RadioHerzblut** [comment]
Hello Skoerfgen - > This ist the output:

![image](https://github.com/user-attachments/assets/c8557845-21be-4ff7-9fa3-e3c0558acf64)

**Comment by skoerfgen** [comment]
Sorry, I assumed that `acme.crt` would be replaced with the path to the certificate being used.

Since you are running it via Docker, this should work:

```bash
docker exec azuracast openssl x509 -noout -text -in /var/azuracast/storage/acme/ssl.crt
```

**Comment by RadioHerzblut** [comment]
Sorry ! I have the version - Rolling Release #3f9c21b. This is the backup from two months ago.

But the error is also present in the current update. I have restored it in the hope that this problem is not in the last backup. Unfortunately it is !

Do you have any ideas about the rolling realease ?

**Comment by RadioHerzblut** [comment]
Hello, unfortunately the SSL has not become active. 
A manual update is not possible, as it is not yet necessary to renew the certificate. 
I now have the new Azuracast Docker version on the system:

 
 AzuraCast - v0.20.1 Stable - Docker - PHP 8.3

**Comment by skoerfgen** [comment]
Ok, this means the initial error message "Certificate does not need renewal" was not wrong. The certificate itself looks good and is valid: https://crt.sh/?id=13759840121

Even the SSL-Test shows that this certificate is currently in use:
https://www.ssllabs.com/ssltest/analyze.html?d=www.rh-autodj.de&hideResults=on

I can't see anything wrong.

What do you exactly mean by "SSL has not become active"? What error message do you get?

**Comment by RadioHerzblut** [comment]
I thought your Docker command would cause Azuracast to take the certificate back. 
But it was about the result in the post above. 
I wrote very strangely here.

I can't renew it manually because it's not the time yet. 

I am absolutely no professional when it comes to certificates, or rather I have no idea ;-)

**Comment by skoerfgen** [comment]
> I thought your Docker command would cause Azuracast to take the certificate back.

The command I posted only checks the existing certificate but does not change anything on the system.

> I can't renew it manually because it's not the time yet.

Since the certificate was successfully issued by Let's Encrypt and is also used by the web server, there is no need to renew the certificate. The certificate is valid for 90 days.

Also make sure you use the exact domain name you issued the certificate for.
Assuming you have issued a certificate for www.example.com, https://www.example.com/ must be entered in the browser. https://example.com/ would not work in this case.

**Comment by RadioHerzblut** [comment]
Many Thanks für your Help. In a Backup was a old URL .

![image](https://github.com/user-attachments/assets/7f5590b3-84e0-427a-a434-77d2c49015a0)
 
Nice Weekend

**Comment by skoerfgen** [comment]
Glad I could help!

Have a nice weekend too!
