### ISSUE TITLE
 Unable to Automatically Assign Ports for New Radio Stations

### ISSUE THREAD

**Issue by wiozo** [AzuraCast/AzuraCast#7319]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

I am experiencing an issue with AzuraCast where it is unable to automatically assign ports for new radio stations. Despite manually configuring a port (8500 or 8600) and verifying its availability, the system reports that there are no available ports for new stations.

Please investigate this issue and provide guidance on how to resolve it. If there are any additional diagnostics or configurations needed, please let me know.

Thank you for your assistance.

### Relevant log output

```shell
docker-compose.override.yml

version: '2.2'

services:
  web:
    ports:
      - "8600-9099:8600-9099"

/var/azuracast/.env

# Station Ports
# The ports AzuraCast should listen to for station broadcasts and incoming DJ
# connections.
# Default: 8000,8005,8006,8010,8015,8016,8020,8025,8026,8030,8035,8036,8040,8045,8046,8050,8055,8056,8060,8065,8066,8070,8075,8076,8090,8095,8096,8100,8105,8106,8110,8115,8116>
AZURACAST_STATION_PORTS=8600-9099
```

**Comment by LordHelmchen666** [comment]
Did you really checked used ports? `sudo lsof -i -P -n | grep LISTEN`

**Comment by wiozo** [comment]
docker-pr 22727            root    4u  IPv6  88081      0t0  TCP *:9082 (LISTEN)
docker-pr 22733            root    4u  IPv4  81415      0t0  TCP *:9083 (LISTEN)
docker-pr 22739            root    4u  IPv6  81418      0t0  TCP *:9083 (LISTEN)
docker-pr 22745            root    4u  IPv4  80331      0t0  TCP *:9084 (LISTEN)
docker-pr 22751            root    4u  IPv6  78351      0t0  TCP *:9084 (LISTEN)
docker-pr 22760            root    4u  IPv4  78354      0t0  TCP *:9085 (LISTEN)
docker-pr 22768            root    4u  IPv6  82483      0t0  TCP *:9085 (LISTEN)
docker-pr 22775            root    4u  IPv4  84554      0t0  TCP *:9086 (LISTEN)
docker-pr 22782            root    4u  IPv6  75464      0t0  TCP *:9086 (LISTEN)
docker-pr 22788            root    4u  IPv4  80334      0t0  TCP *:9087 (LISTEN)
docker-pr 22796            root    4u  IPv6  70599      0t0  TCP *:9087 (LISTEN)
docker-pr 22803            root    4u  IPv4  84557      0t0  TCP *:9088 (LISTEN)
docker-pr 22810            root    4u  IPv6  75467      0t0  TCP *:9088 (LISTEN)
docker-pr 22818            root    4u  IPv4  84560      0t0  TCP *:9089 (LISTEN)
docker-pr 22825            root    4u  IPv6  76561      0t0  TCP *:9089 (LISTEN)
docker-pr 22832            root    4u  IPv4  87063      0t0  TCP *:9090 (LISTEN)
docker-pr 22838            root    4u  IPv6  84563      0t0  TCP *:9090 (LISTEN)
docker-pr 22845            root    4u  IPv4  75470      0t0  TCP *:9091 (LISTEN)
docker-pr 22852            root    4u  IPv6  86263      0t0  TCP *:9091 (LISTEN)
docker-pr 22858            root    4u  IPv4  84568      0t0  TCP *:9092 (LISTEN)
docker-pr 22865            root    4u  IPv6  84571      0t0  TCP *:9092 (LISTEN)
docker-pr 22873            root    4u  IPv4  77359      0t0  TCP *:9093 (LISTEN)
docker-pr 22879            root    4u  IPv6  76566      0t0  TCP *:9093 (LISTEN)
docker-pr 22886            root    4u  IPv4  70604      0t0  TCP *:9094 (LISTEN)
docker-pr 22892            root    4u  IPv6  79481      0t0  TCP *:9094 (LISTEN)
docker-pr 22900            root    4u  IPv4  77362      0t0  TCP *:9095 (LISTEN)
docker-pr 22906            root    4u  IPv6  77365      0t0  TCP *:9095 (LISTEN)
docker-pr 22913            root    4u  IPv4  86266      0t0  TCP *:9096 (LISTEN)
docker-pr 22919            root    4u  IPv6  76569      0t0  TCP *:9096 (LISTEN)
docker-pr 22926            root    4u  IPv4  86269      0t0  TCP *:9097 (LISTEN)
docker-pr 22933            root    4u  IPv6  79484      0t0  TCP *:9097 (LISTEN)
docker-pr 22941            root    4u  IPv4  73537      0t0  TCP *:9098 (LISTEN)
docker-pr 22948            root    4u  IPv6  86272      0t0  TCP *:9098 (LISTEN)
docker-pr 22956            root    4u  IPv4  86275      0t0  TCP *:9099 (LISTEN)
docker-pr 22965            root    4u  IPv6  84574      0t0  TCP *:9099 (LISTEN)

**Comment by wiozo** [comment]
docker ps
CONTAINER ID   IMAGE                                COMMAND                  CREATED       STATUS       PORTS                                                                                                                                                                                               NAMES
92a38e32d642   ghcr.io/azuracast/azuracast:latest   "tini -- /usr/local/…"   3 hours ago   Up 3 hours   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:2022->2022/tcp, :::2022->2022/tcp, 0.0.0.0:8600-9099->8600-9099/tcp, :::8600-9099->8600-9099/tcp, 8000-8599/tcp   azuracast
99aa0be9cd6e   ghcr.io/azuracast/updater:latest     "/watchtower"            3 hours ago   Up 3 hours   8080/tcp                                                                                                                                                                                            azuracast_updater

**Comment by wiozo** [comment]
If I manually add the PORT, then it works. Azuracast will not add it automatically :(

**Comment by LordHelmchen666** [comment]
Did you read this ? https://www.azuracast.com/docs/administration/docker/#using-non-standard-ports

**Comment by wiozo** [comment]
Step by step. Everything done according to the documentation.

**Comment by BusterNeece** [comment]
@wiozo You didn't mention updating `azuracast.env` to include new values for these environment variables:

```
AUTO_ASSIGN_PORT_MIN=8500
AUTO_ASSIGN_PORT_MAX=8999
```

That is equally important if you're using nonstandard ports. Update those values, then restart the Docker container.

**Comment by wiozo** [comment]
I did everything.
Changed ports 
from 8500 
from 8600

Does not help :(

**Comment by wiozo** [comment]
Fixed :)

**Comment by LordHelmchen666** [comment]
@wiozo Would it be possible to share your solution? Maybe you could help others with similar problem. Thanks
