### ISSUE TITLE
Edit liquidsoap configuration / output.alsa / sending radio stream to sound card output for monitor speaker.

### ISSUE THREAD

**Issue by kosnick** [AzuraCast/AzuraCast#7327]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #536b5f6 (2024-07-10 8:05

### What happened?

Info: Ubuntu 20.04.6 LTS / Rolling Release 536b5f6 / Docker 27.0.3

The idea is to output the stream of my radio to the sound card (which would end up to monitor speakers) using liquidsoap (edit liquidsoap configuration).
One other solution would be to open the stream in web locally and use the play button to start the stream.
But I would like to have it start during boot and not manually.
Hence I could edit the liquidsoap configuration to output the stream to alsa (which would end up in the speakers output of the sound card).
Iwas able to, was to use a oneliner on my ubuntu installation (the one that has the docker container of azuracast as well), and send with liquidsoap the stream to alsa. I used the following oneliner:

`liquidsoap 'output.alsa(mksafe(input.http("http://localhost/mystream")))' `

However, when i use the following part of the oneliner 

`output.alsa(mksafe(input.http("http://localhost/mystream")))`

to the liquidsoap configuration edit , azuracast complains (this is docker container).
I tried adding this to the very last part of the liquidsoap configuration file (even the one before).
At this point I tried creating a service (systemd) for the usable one liner, but was not able to, so I went back to 'liquidsoap edit configuration'.
To simplify things, i even tried using the simpliest liquidsoap script for alsa output

`output.alsa(sine())`

but this did not work either for the docker container (it worked on the os installation though).
Based on the liquidsoap log output, and some research, could it be that there is some permissions issue?
Or anything else, someone could help on?
I even tried 

`output.alsa(mksafe(radio))`

hoping that the radio stream would help it work, but it didn't.
Thank you in advance
Nick

p.s. I restarted broadcasting!

### Relevant log output

```shell
Fatal error: exception Alsa error: No such file or directory
Raised by primitive operation at Alsa_out.output#get_device in file "src/core/outputs/alsa_out.ml", line 79, characters 22-56
Called from Alsa_out.output#push_block in file "src/core/outputs/alsa_out.ml", line 132, characters 16-31
Called from IoRing.output#reader in file "src/core/tools/ioRing.ml", line 190, characters 10-61
Re-raised at IoRing.output#reader in file "src/core/tools/ioRing.ml", line 214, characters 12-19
Called from Tutils.create.(fun).process in file "src/core/tools/tutils.ml", line 186, characters 12-15
Re-raised at Tutils.exit in file "src/core/tools/tutils.ml", line 68, characters 34-70
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Dune__exe__Liquidsoap in file "src/bin/liquidsoap.ml", line 1, characters 9-41
```

**Comment by gAlleb** [comment]
Since you are running Docker container - you can't just output stream to your soundcard. There is no `your soundcard` inside Docker container. 

But you can pass, e.g. ALSA, and share sound devices with something like `--device /dev/snd`. In compose it's done with devices attribute. This way you can make container aware of your sound card. 

> The idea is to output the stream of my radio to the sound card (which would end up to monitor speakers) using liquidsoap (edit liquidsoap configuration). 

Why not just open your stream in audio player?

**Comment by kosnick** [comment]
Thanks for your reply gAlleb!
I will give it a try and find out how to share local alsa with docker image.
I need to send the output to a mixer. That's why I would like to have the output to the sound card.

**Comment by kosnick** [comment]
I sorted it out with a workaround.
I used vlc (actually cvlc) to play the stream - so no need to run a browser to reach the stream.
And i was able to run it as a service.
One point here, was to make it a service at the user level - in which case alsa or audio or whatever was a problem to be reached from a root level, was accessible afterwards.
Thanks for helping out.
Closing the comment.
