### ISSUE TITLE
Icecast Now Playing and Station information not showing on external media players.

### ISSUE THREAD

**Issue by reviselabs** [AzuraCast/AzuraCast#7330]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.20.1 Stable • Docker • PHP 8.3

### What happened?

Hi Team,

When I play a file from my Icecast installation on Azuracast in an external media player (using VLC as an example), I cannot get any information to show for that stream in that media player, but I can view information if I use a different Icecast server. 
This seems to affect only a MP3 or AAC formatted mounts and not OGG Vorbis.

Before the last major update, I had no issue with this.

A working information Icecast link:
http://10321.cloudrad.io:9054/chill
![image](https://github.com/user-attachments/assets/ea36f00e-a06c-49c5-9fa9-76b63bf6fea2)

A non-working information Icecast link (Azuracast):
https://streaming.starterfm.com/listen/space/chill192
![image](https://github.com/user-attachments/assets/9f330675-31d9-4b57-8c1c-c9f80058a570)

Please help, as I have an app which now has stopped reading metadata information from my Azuracast.

**Comment by gAlleb** [comment]
Hi, lose `s` in https://`

**Comment by Vaalyn** [comment]
That's a bug in VLC as far as I'm aware. I've tested this back in 2019 and playing HTTPS URLs was breaking metadata in there already. See my comment about this from back then: https://github.com/AzuraCast/AzuraCast/issues/1598#issuecomment-518002693

**Comment by reviselabs** [comment]
> Hi, lose `s` in `https://`

Yes, Yes that worked

**Comment by gAlleb** [comment]
You'll never know unless you try)

**Comment by t0mtaylor** [comment]
> That's a bug in VLC as far as I'm aware. I've tested this back in 2019 and playing HTTPS URLs was breaking metadata in there already. See my comment about this from back then: [#1598 (comment)](https://github.com/AzuraCast/AzuraCast/issues/1598#issuecomment-518002693)

It's been years and its still not been fixed in VLC - they need a volunteer to fix it - https://code.videolan.org/videolan/vlc/-/issues/21057

Heres another azuracast issue from 2019 https://github.com/AzuraCast/AzuraCast/issues/1598
