### ISSUE TITLE
Streamer/DJ Accounts not saving password on update - DJ can't login

### ISSUE THREAD

**Issue by donwildman** [AzuraCast/AzuraCast#7338]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

I can't update the streamer's password on the Streamers Accounts page, it responds with a success message but returns the record with no password. Same issue if I delete the streamer and add him again.

Response from server when updating:
# payload
`{"schedule_items":[],"artwork_file":null,"streamer_username":"don","streamer_password":"password","display_name":"Don Wildman","comments":null,"is_active":true,"enforce_schedule":false}`

# response
`{
    "success": true,
    "message": "Record updated successfully.",
    "formatted_message": "Record updated successfully."
}`

Then in the Json response:
`{
            "streamer_username": "don",
            "streamer_password": "",
            "display_name": "Don Wildman",
            "comments": null,
            "is_active": true,
            "enforce_schedule": false,
            "reactivate_at": null,
            "art_updated_at": 1720871337,
            "schedule_items": [],
            "id": 8,
            "links": {
                "self": "/api/station/2/streamer/8",
                "broadcasts": "/api/station/2/streamer/8/broadcasts",
                "art": "/api/station/2/streamer/8/art"
            },
            "has_custom_art": true,
            "art": "/api/station/2/streamer/8/art-1720871337.jpg"
        }
`

DJ's can't connect, getting invalid password error in BUTT.

**Comment by BusterNeece** [comment]
@donwildman It is actually updating the password for the streamer under the hood, it just doesn't return the password, either encrypted or in plaintext, as a security measure. The password is stored via a one-way "salted hash" in the database and can only be used to authenticate users logging in, not viewed in plain text.

**Comment by SpeedyCharly** [comment]
The OP also stated that streamers can't login following this issue... If password was stored properly they should still be able to login

**Comment by donwildman** [comment]
I keep getting incorrect password when trying to connect as a streamer, how can I query the database manually to try to troubleshoot further?

**Comment by donwildman** [comment]
Also, if it's a security measure, why are passwords returned in other parts of the site, like the relay password etc?

**Comment by SpeedyCharly** [comment]
[DJ's can't connect, getting invalid password error in BUTT.]

Is your BUTT in Icecast or Shoutcast mode?  They have different ways of inputting password into the encoder as shown here;
https://www.azuracast.com/docs/user-guide/streaming-software/
