### ISSUE TITLE
Using Munin Monitoring alongside Azuracast

### ISSUE THREAD

**Issue by bombelman** [AzuraCast/AzuraCast#7347]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Is it safe to install Munin Monitoring alongside Azuracast?

On this page, it instructs to install Apache:
https://www.debuntu.org/how-to-monitoring-a-server-with-munin-page-2/
In the end you'll be able to access the monitoring via http://monitoring.example.com

Just want to make sure Apache does not interfere with Azuracast.

Could the ngnix also be configured to view the munin monitoring?

**Comment by gAlleb** [comment]
Hi @bombelman. It can be safe. You have few options with this. 

1. Use non-standard ports for Azuracast (https://www.azuracast.com/docs/administration/docker/#using-non-standard-ports) and install apache2 for Munin on standard ports. In the end you'll have Azuracast site on non-standard ports: e.g. `http://yourazuracast.com:9999` and Munin on standard ports: `http://munin.yourazuracast.com`. As you can see it's not a good option))
2. Use non-standard ports for Munin and install apache2. You should edit apache2's `ports.conf` (/etc/apache2/ports.conf) after install to fit your desired port. E.g. `http://munin.yourazuracast.com:9999`
3. Use one more `nginx` server. For this:
-- Set non-standard ports for Azuracast (https://www.azuracast.com/docs/administration/docker/#using-non-standard-ports) 
-- Install `nginx` on your server
----- and use it as reverse proxy for Azuracast installation
----- use it for Munin hosting
-- Install `certbot` to get certificates for Azuracast and Munin domains. 
-- More or less working Nginx config to proxy Azuracast installation:
```ruby
server {
	    listen 80;
            listen [::]:80;
            server_name www.yourdomain.com yourdomain.com;
            index index.php index.html index.htm;
            autoindex off;
            error_log /var/log/nginx/radio.error.log;
	    access_log /var/log/nginx/radio.access.log;            

 location / {
            proxy_pass                         http://127.0.0.1:9999;
            # Websocket 
            proxy_http_version                 1.1;
            proxy_cache_bypass                 $http_upgrade;
            proxy_set_header Upgrade           $http_upgrade;
            proxy_set_header Connection        "upgrade";
            
            # Proxy headers
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host  $host;
            proxy_set_header X-Forwarded-Port  $server_port;
            proxy_set_header X-Forwarded-Scheme $scheme;            
            proxy_set_header Accept-Encoding "";

            # Proxy timeouts
            proxy_connect_timeout              2400s;
            proxy_send_timeout                 60s;
            proxy_read_timeout                 60s;
        }
}

```
4. Use `Nginx Proxy Manager`
-- Read https://www.azuracast.com/docs/administration/multi-site-installation/
-- Install apache2 on non-standard ports and set up Munin
-- Install Azuracast on non-standard ports or change them
-- Install `Nginx Proxy Manager` and create new Proxy Hosts for Munin and Azuracast as per this guide https://nginxproxymanager.com/guide/

Choose your option, dive into FAQs and tutorials and you'll get a good result!

**Comment by gAlleb** [comment]
Hi @bombelman. It can be safe. You have few options with this. 

1. Use non-standard ports for Azuracast (https://www.azuracast.com/docs/administration/docker/#using-non-standard-ports) and install apache2 for Munin on standard ports. In the end you'll have Azuracast site on non-standard ports: e.g. `http://yourazuracast.com:9999` and Munin on standard ports: `http://munin.yourazuracast.com`. Additionaly you can proxy Azuracast via apache2. As you can see it's not a good option))
2. Use non-standard ports for Munin and install apache2. You should edit apache2's `ports.conf` (/etc/apache2/ports.conf) after install to fit your desired port. E.g. `http://munin.yourazuracast.com:9999`
3. Use one more `nginx` server. For this:
-- Set non-standard ports for Azuracast (https://www.azuracast.com/docs/administration/docker/#using-non-standard-ports) 
-- Install `nginx` on your server
----- and use it as reverse proxy for Azuracast installation
----- use it for Munin hosting
-- Install `certbot` to get certificates for Azuracast and Munin domains. 
-- More or less working Nginx config to proxy Azuracast installation:
```ruby
server {
	    listen 80;
            listen [::]:80;
            server_name www.yourdomain.com yourdomain.com;
            index index.php index.html index.htm;
            autoindex off;
            error_log /var/log/nginx/radio.error.log;
	    access_log /var/log/nginx/radio.access.log;            

 location / {
            proxy_pass                         http://127.0.0.1:9999;
            # Websocket 
            proxy_http_version                 1.1;
            proxy_cache_bypass                 $http_upgrade;
            proxy_set_header Upgrade           $http_upgrade;
            proxy_set_header Connection        "upgrade";
            
            # Proxy headers
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host  $host;
            proxy_set_header X-Forwarded-Port  $server_port;
            proxy_set_header X-Forwarded-Scheme $scheme;            
            proxy_set_header Accept-Encoding "";

            # Proxy timeouts
            proxy_connect_timeout              2400s;
            proxy_send_timeout                 60s;
            proxy_read_timeout                 60s;
        }
}

```
4. Use `Nginx Proxy Manager`
-- Read https://www.azuracast.com/docs/administration/multi-site-installation/
-- Install apache2 on non-standard ports and set up Munin
-- Install Azuracast on non-standard ports or change them
-- Install `Nginx Proxy Manager` and create new Proxy Hosts for Munin and Azuracast as per this guide https://nginxproxymanager.com/guide/
-- Install certificates for your sites.

Choose your option, dive into FAQs and tutorials and you'll get a good result!

**Comment by PoGo606** [comment]
Hi there, I'm using Munin to monitor the evolution of my playlists, here's a plugin I've developed : https://wtf.roflcopter.fr/paste/?bcb9874c2d082cb4#9wKUHh9KFCqbN1MsALd2gL75vhxHX8ZxhtkuPaCQDF3c

I guess you can tweak it to fill your needs

**Comment by bombelman** [comment]
> evolution of my playlists

hi, what exactly do you mean by this? can you share a screenshot? Thanks!

@PoGo606

**Comment by bombelman** [comment]
> Hi @bombelman. It can be safe. You have few options with this.
> 
> 1. Use non-standard ports for Azuracast (https://www.azuracast.com/docs/administration/docker/#using-non-standard-ports) and install apache2 for Munin on standard ports. In the end you'll have Azuracast site on non-standard ports: e.g. `http://yourazuracast.com:9999` and Munin on standard ports: `http://munin.yourazuracast.com` or `http://yourazuracast.com`. Additionaly you can proxy Azuracast via apache2. As you can see it's not a good option))
> 2. Use non-standard ports for Munin and install apache2. You should edit apache2's `ports.conf` (/etc/apache2/ports.conf) after install to fit your desired port. E.g. `http://munin.yourazuracast.com:9999` or  `http://yourazuracast.com:9999`
> 3. Use one more `nginx` server. For this:
>    -- Set non-standard ports for Azuracast (https://www.azuracast.com/docs/administration/docker/#using-non-standard-ports).
>    -- Install `nginx` on your server.
>    ----- and use it as reverse proxy for Azuracast installation.
>    ----- use it for Munin hosting or install Munin on apache2 and use nginx as reverse proxy for apache2.
>    -- Install `certbot` to get certificates for Azuracast and Munin domains.
>    -- More or less working Nginx config to proxy Azuracast installation:
> 
> ```ruby
> server {
> 	    listen 80;
>             listen [::]:80;
>             server_name www.yourdomain.com yourdomain.com;
>             index index.php index.html index.htm;
>             autoindex off;
>             error_log /var/log/nginx/radio.error.log;
> 	    access_log /var/log/nginx/radio.access.log;            
> 
>  location / {
>             proxy_pass                         http://127.0.0.1:9999;
>             # Websocket 
>             proxy_http_version                 1.1;
>             proxy_cache_bypass                 $http_upgrade;
>             proxy_set_header Upgrade           $http_upgrade;
>             proxy_set_header Connection        "upgrade";
>             
>             # Proxy headers
>             proxy_set_header Host              $host;
>             proxy_set_header X-Real-IP         $remote_addr;
>             proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
>             proxy_set_header X-Forwarded-Proto $scheme;
>             proxy_set_header X-Forwarded-Host  $host;
>             proxy_set_header X-Forwarded-Port  $server_port;
>             proxy_set_header X-Forwarded-Scheme $scheme;            
>             proxy_set_header Accept-Encoding "";
> 
>             # Proxy timeouts
>             proxy_connect_timeout              2400s;
>             proxy_send_timeout                 60s;
>             proxy_read_timeout                 60s;
>         }
> }
> ```
> 
> 4. Use `Nginx Proxy Manager`
>    -- Read https://www.azuracast.com/docs/administration/multi-site-installation/
>    -- Install apache2 or nginx on non-standard ports and set up Munin.
>    -- Install Azuracast on non-standard ports or change them.
>    -- Install `Nginx Proxy Manager` and create new Proxy Hosts for Munin and Azuracast as per this guide https://nginxproxymanager.com/guide/
>    -- Install certificates for your sites.
> 
> Choose your option, dive into FAQs and tutorials and you'll get a good result!
> 
> P.S. Of course you can set any subdomains in any of the above options or use main domain on non-standard port alongside standard port.

can I use Azura and Munin on 1 nginx server, with nginx on a subdomain?

**Comment by gAlleb** [comment]
> can I use Azura and Munin on 1 nginx server, with nginx on a subdomain?

With option number 3 or 4. You see, Azuracast uses nginx. And you have only one port 80 and port 443. It doesn't matter if it's a subdomain or not.

**Comment by bombelman** [comment]
> > can I use Azura and Munin on 1 nginx server, with nginx on a subdomain?
> 
> With option number 3 or 4. You see, Azuracast uses nginx insiide docker and occupies ports 80 and 443 by default. And you have only one port 80 and port 443. It doesn't matter if it's a subdomain or not. So in order to host Azuracast and Munin on 1 server the easiest option is:
> 
> 1. Change default web ports for Azuracast.
> 2. Install nginx on host machine
> 3. Reverse proxy Azuracast for main domain - `maindomain.com`
> 4. Host Munin on the same nginx (that you have installed on step 2) with a subdomain - `munin.maindomain.com`

I want to keep the Azuracast as much as stock, so on default ports install and default portst.

Can I skip step3 and use non-std ports for Munin, keeping Azura as it is?

**Comment by gAlleb** [comment]
> Can I skip step3 and use non-std ports for Munin, keeping Azura as it is?

Yeah. Just install nginx server on your host machine and host Munin on available non-standard ports via a subdomain (`munin.maindomain.com:9999`) or even via main domain (`maindomain.com:9999`). Then if you go to

`maindomain.com` - you will reach AC.
`maindomain.com:9999` - Munin.

**Comment by PoGo606** [comment]
> > evolution of my playlists
> 
> hi, what exactly do you mean by this? can you share a screenshot? Thanks!
> 
> @PoGo606

As we are several users to manage the playlists, I thought  it was nice to graph the evolution of the playlist along the time
I monitor them by total length (in hours) : 
![azuracast_playlists_total_length-pinpoint=1688070331,1722630331](https://github.com/user-attachments/assets/6de7c2ca-38d2-4680-827b-6847f2a60e9d)
And by counting the songs for each of them : 
![azuracast_playlists_num_songs-pinpoint=1688070331,1722630331](https://github.com/user-attachments/assets/ea993948-2bf9-4b62-8d91-eeab4bd28606)
_(don't mind the lack of data in March, I had an issue with the script that I've fixed)_

**Comment by gAlleb** [comment]
Regarding your email, as I've written earlier "Choose your option, dive into FAQs and tutorials and you'll get a good result!". Nothing difficult here. You've got lots of options and lots of faqs laying around internet. If you want any specific assistance you're ought to ask members in the community or hire a professional to do it for you (but where is fun in that? 😃).

**Comment by bombelman** [comment]
> > > evolution of my playlists
> > 
> > 
> > hi, what exactly do you mean by this? can you share a screenshot? Thanks!
> > @PoGo606
> 
> As we are several users to manage the playlists, I thought it was nice to graph the evolution of the playlist along the time I monitor them by total length (in hours) : ![azuracast_playlists_total_length-pinpoint=1688070331,1722630331](https://private-user-images.githubusercontent.com/1552904/354716369-6de7c2ca-38d2-4680-827b-6847f2a60e9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2ODQwMzQsIm5iZiI6MTcyMjY4MzczNCwicGF0aCI6Ii8xNTUyOTA0LzM1NDcxNjM2OS02ZGU3YzJjYS0zOGQyLTQ2ODAtODI3Yi02ODQ3ZjJhNjBlOWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDNUMTExNTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2E3ZWMzODE1YzVhNjYyZTZjODZjZjFjYTc5ZmMxMWQ3ODFhY2U2NGVjNDZhZTViOWQ4OWFjY2FhOTc0MmUyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4MGUHt0Z0w7mz0lIy51LPtykI_6jDk8BitKbxuVFXh8) And by counting the songs for each of them : ![azuracast_playlists_num_songs-pinpoint=1688070331,1722630331](https://private-user-images.githubusercontent.com/1552904/354716866-ea993948-2bf9-4b62-8d91-eeab4bd28606.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2ODQwMzQsIm5iZiI6MTcyMjY4MzczNCwicGF0aCI6Ii8xNTUyOTA0LzM1NDcxNjg2Ni1lYTk5Mzk0OC0yYmY5LTRiNjItOGQ5MS1lZWFiNGJkMjg2MDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDNUMTExNTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDcwNWY4NzdmMTQwZDYyOTkxZjVkMDM0NDEyMjg1YTc3NzlmMjgxMGI2YzI4OGEzZDk4Mjg4MjNlMTE3NDI3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zdXhogzypQHm2kvatcoHzlQYrxzHUEhllAjFxRI57Rc) _(don't mind the lack of data in March, I had an issue with the script that I've fixed)_

this is reallly nice ! thanks for posting!
