### ISSUE TITLE
Unable to Access Control Panel and Server Error 500

### ISSUE THREAD

**Issue by ahmedmoussa2020875** [AzuraCast/AzuraCast#7348]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

I am currently experiencing with my AzuraCast instance. I am unable to access the control panel, and my website, which is integrated with AzuraCast, is displaying a "Server Error 500" messag

**Comment by BusterNeece** [comment]
@ahmedmoussa2020875 I noticed you also e-mailed us directly asking for support...I think you may be confused about what AzuraCast is in your setup. We make and distribute the radio software, but we don't provide hosting services or direct support to hosting providers or their customers.

In order for us to know what's going on with your installation that's causing the HTTP 500 error, we'd need to see some supporting logs from the server itself. Instructions for finding logs can be found here: https://www.azuracast.com/docs/help/logs/

**Comment by ahmedmoussa2020875** [comment]
@BusterNeece Thank you for your attention and response.
I have checked the Azura documentation regarding potential issues, but the problem now is that I cannot access my AzuraCast dashboard. Whenever I try to access it, this message appears on the web page. "This site can’t be reached"
