### ISSUE TITLE
AutoCue after last updates

### ISSUE THREAD

**Issue by DAMaia1989** [AzuraCast/AzuraCast#7351]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #4bef6d6 (2024-07-27 22:53)

### What happened?

hello guys! Once again I noticed that after the last two updates, the music was once again spaced out between the jingles, creating a slightly unpleasant silence.
How could I remedy this situation?

**Comment by t0mtaylor** [comment]
Also noticed same issue, even with modified LQ script which tightened the transitions up last time there was an update to AutoCue the other month

@DAMaia1989 try some of the tweaks as mentioned here to see if they help https://github.com/AzuraCast/AzuraCast/issues/7204

@Moonbase59 @BusterNeece

**Comment by DAMaia1989** [comment]
hi @t0mtaylor thanks for the answer. Unfortunately, I already tried these options and it didn't work.
