### ISSUE TITLE
Create Station via API return Error: response status is 500

### ISSUE THREAD

**Issue by handris** [AzuraCast/AzuraCast#7353]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#7b16397 (2024-07-30 23:42)

### What happened?

After upgrade to latest rolling relase We can not create station via API : https://azuracastaddress/api/admin/stations with curl.
via swagger ui does not work too.

### Relevant log output

```shell
{
  "code": 500,
  "type": "TypeError",
  "message": "App\\Entity\\AbstractStationConfiguration::set(): Argument #1 ($key) must be of type string, int given, called in /var/azuracast/www/backend/src/Entity/AbstractStationConfiguration.php on line 49",
  "formatted_message": "App\\Entity\\AbstractStationConfiguration::set(): Argument #1 ($key) must be of type string, int given, called in /var/azuracast/www/backend/src/Entity/AbstractStationConfiguration.php on line 49",
  "extra_data": {
    "class": "TypeError",
    "file": "/var/azuracast/www/backend/src/Entity/AbstractStationConfiguration.php",
    "line": 93
  },
  "success": false
}
```

**Comment by gAlleb** [comment]
Seems like something in your request needs to be `string` instead if `int` as per `protected function set(string $key, mixed $value): static`

It means you missed qoutes `""` somewhere. Maybe we can find it, what's your POST request?

**Comment by handris** [comment]
> @handris The TypeError seems to be indicating specifically what the problem is...did you pass it a `backend_config` with an integer key in the API call? I'd need to see what you're sending it to know what the problem is.

Hi, this is my curl. It's run from built it Swagger UI Azuracast : 

curl -X 'POST' \
  'https://myazuracastadress/api/admin/stations' \
  -H 'accept: application/json' \
  -H 'X-API-Key: 171a917176e4ea0c:d02589f96dfd29c92bcbaa5c3bbbc902' \
  -H 'Content-Type: application/json' \
  -d '{
  "id": 0,
  "name": "AzuraTest Radio",
  "short_name": "azuratest_radio",
  "is_enabled": true,
  "frontend_type": "icecast",
  "frontend_config": [
    "string"
  ],
  "backend_type": "liquidsoap",
  "backend_config": [
    "string"
  ],
  "description": "A sample radio station.",
  "url": "https://demo.azuracast.com/",
  "genre": "Various",
  "radio_base_dir": "/var/azuracast/stations/azuratest_radio",
  "enable_requests": true,
  "request_delay": 5,
  "request_threshold": 15,
  "disconnect_deactivate_streamer": 0,
  "enable_streamers": false,
  "is_streamer_live": false,
  "enable_public_page": true,
  "enable_on_demand": true,
  "enable_on_demand_download": true,
  "enable_hls": true,
  "api_history_items": 5,
  "timezone": "UTC",
  "branding_config": [
    "string"
  ]
}'

You can also try via htpp://yourazuracastadress/api and try crate station to see this error. it happens on recent rolling version. 

Thank you

**Comment by BusterNeece** [comment]
@handris Well, the error is correct. The `backend_config`, `frontend_config` and `branding_config` are meant to be objects and to store specific configuration information. What you're passing is just a list in JSON, which translates to an array with keys that are numeric, which wouldn't work.

You can basically remove those three fields from your JSON and you should be fine. In fact, most of the other items are already set up as defaults, so you should only send in your JSON what you need to change from the default, since that's easier to maintain.
