### ISSUE TITLE
Update to latest Rolling Release fails

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#7357]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Trying to update to latest RR, but it fails with error.
```
cd /var/azuracast
./docker.sh update-self
./docker.sh update
```

### Relevant log output

```shell
Warning: include(/var/azuracast/www/vendor/composer/../../src/AppFactory.php): Failed to open stream: No such file or directory in /var/azuracast/www/vendor/composer/ClassLoader.php on line 576

Warning: include(): Failed opening '/var/azuracast/www/vendor/composer/../../src/AppFactory.php' for inclusion (include_path='.:/usr/local/lib/php') in /var/azuracast/www/vendor/composer/ClassLoader.php on line 576

Fatal error: Uncaught Error: Class "App\AppFactory" not found in /var/azuracast/www/backend/bin/uptime_wait:11
Stack trace:
#0 {main}
  thrown in /var/azuracast/www/backend/bin/uptime_wait on line 11
```

**Comment by BusterNeece** [comment]
@LordHelmchen666 Yeah, don't go directly back to Stable if you're this far along in Rolling, that's moving backwards in database migrations and doesn't work right. You can try `./docker.sh rollback` but that's not guaranteed to work.

I've seen this error crop up several times, but I've never been able to pin down why it's happening. The logs never fully explain what's going on. In every case I've seen, just re-running the updater or restarting seems to help a great degree.

**Comment by LordHelmchen666** [comment]
Doesn't work either.
```
Roll Back Database
==================

                                                                                                                        
 [ERROR] Class "App\Entity\Migration\UpdateAllRecords" does not exist                                                   
                                                                                                                        

[2024-08-01T20:01:48.693952+00:00] AzuraCast.WARNING: Console command `azuracast:setup:rollback` exited with error code 1. [] []

```

I guess i need to completely reinstall. :(

**Comment by BusterNeece** [comment]
@LordHelmchen666 I can look and see what's going on there...if you re-run the update, do you see the same error as originally?

**Comment by Arsimael** [comment]
This error now also happens on stable:

`.+....+..+.......+...+..+...+....+...+...............+...........+.+...+.....+.+.....+.+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
chown: changing ownership of '/var/azuracast/acme/ssl.key': Read-only file system
chown: changing ownership of '/var/azuracast/acme/ssl.crt': Read-only file system
chmod: changing permissions of '/var/azuracast/acme/ssl.key': Read-only file system
chmod: changing permissions of '/var/azuracast/acme/ssl.crt': Read-only file system
** Startup script complete.
** Running startup script '/etc/my_init.d/02_install_extra_packages.sh'...
** Startup script complete.
** Running startup script '/etc/my_init.d/03_persist_dir.sh'...
Creating persist directories...
** Startup script complete.
** Running startup script '/etc/my_init.d/04_mariadb_conf.sh'...
** Startup script complete.
** Running startup script '/etc/my_init.d/05_centrifugo_conf.sh'...
** Startup script complete.
** Running startup script '/etc/my_init.d/05_nginx_conf.sh'...
** Startup script complete.
** Running startup script '/etc/my_init.d/05_setup_db.sh'...
2024-08-01 22:54:24+00:00 [Note] [Entrypoint]: Initial DB setup...
2024-08-01 22:54:24+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2024-08-01 22:54:24+00:00 [Note] [Entrypoint]: Initial DB setup...
2024-08-01 22:54:25+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
** Startup script complete.
** Running startup script '/etc/my_init.d/06_php_conf.sh'...
** Startup script complete.
** Running startup script '/etc/my_init.d/07_sftpgo_conf.sh'...
** Startup script complete.
** Running startup script '/etc/my_init.d/10_clear_temp.sh'...
** Startup script complete.
** Running Supervisord...
** Supervisord started.
** Running uptime_wait...

Warning: include(/var/azuracast/www/vendor/composer/../../src/AppFactory.php): Failed to open stream: No such file or directory in /var/azuracast/www/vendor/composer/ClassLoader.php on line 576

Warning: include(): Failed opening '/var/azuracast/www/vendor/composer/../../src/AppFactory.php' for inclusion (include_path='.:/usr/local/lib/php') in /var/azuracast/www/vendor/composer/ClassLoader.php on line 576

Fatal error: Uncaught Error: Class "App\AppFactory" not found in /var/azuracast/www/backend/bin/uptime_wait:11
Stack trace:
#0 {main}
  thrown in /var/azuracast/www/backend/bin/uptime_wait on line 11
[+] Running 2/2
 ✔ Container azuracast_updater  Running                                                                                                                                            0.0s 
 ✔ Container azuracast          Started            `

**Comment by BusterNeece** [comment]
Still trying to figure out what the common factor is here between these installations. It's definitely not happening on every installation, or even any of the installations I work with.

Do you have plugin mode enabled? Do you mount custom code via `docker-compose.override.yml`? Is there anything nonstandard about your installation that I should know about?

**Comment by Arsimael** [comment]
My files are on a different harddrive, and an own certificate. thats most likely it:

```
services:
  web:
    volumes:
      - /storage/data:/var/azuracast/stations
      - /opt/certs/fullchain.crt:/var/azuracast/acme/ssl.crt:ro
      - /opt/certs/privkey.key:/var/azuracast/acme/ssl.key:ro
```

**Comment by Arsimael** [comment]
Rollback to Version 0.20.1 seem'd to do the trick. 
At least it's now running again.

**Comment by BusterNeece** [comment]
@Arsimael That shouldn't actually be causing it by itself...those files are certainly there in the filesystem, so it's not clear why they're not registering as being there in some installations. I don't currently have enough information to know what's going on here, and I'd probably have to actually look at one of these installations via SSH to figure out what's up.

**Comment by Arsimael** [comment]
My installation isn't productive. It's currently a test / fooling around system. I could let you have a look into it.

**Comment by BusterNeece** [comment]
@Arsimael Feel free to message me via our Discord or via e-mail.

**Comment by Arsimael** [comment]
@LordHelmchen666 We could fix my issue by going with:

./docker.sh install

And when asked if the "cudtom plugins" shall be activates I selected "no",

Fixed the problem for me (I don't use any plugins)

**Comment by PoGo606** [comment]
I had the same issue, a fresh install + restoring a backup solved it.

**Comment by LordHelmchen666** [comment]
Thanks to ALL for your time and input!
@BusterNeece You where right! I had enabled _COMPOSER_PLUGIN_MODE=true_ in azuracast.env and  _AZURACAST_PLUGIN_MODE=true_ in docker-compose.override.yml
I set `COMPOSER_PLUGIN_MODE=false` in azuracast.env. Deleted `AZURACAST_PLUGIN_MODE=true` from docker-compose.override.yml. Then run normal update
```
cd /var/azuracast
./docker.sh update-self
./docker.sh update
```
Everything fine now!

**Comment by dannyodj** [comment]
i was in the version stable 0.20.0 im still in centos 7  , i tried to upgrade to latest version and i get the same error 
Warning: include(/var/azuracast/www/vendor/composer/../../src/AppFactory.php): Failed to open stream: No such file or directory in /var/azuracast/www/vendor/composer/ClassLoader.php on line 576

Warning: include(): Failed opening '/var/azuracast/www/vendor/composer/../../src/AppFactory.php' for inclusion (include_path='.:/usr/local/lib/php') in /var/azuracast/www/vendor/composer/ClassLoader.php on line 576

Fatal error: Uncaught Error: Class "App\AppFactory" not found in /var/azuracast/www/backend/bin/uptime_wait:11

and nothing Sims to works , so what i  did is : i just run a rollback :

`./docker.sh rollback 0.20.1`

now everything its working back and it shows me this version installed:

Powered by [AzuraCast](https://www.azuracast.com/) • Rolling Release #[ce937c1](https://github.com/AzuraCast/AzuraCast/commit/ce937c181890ebd9a27695c3283df95f682435d4) (2024-06-02 19:22) • Docker • PHP 8.3

i like to have the latest release stable but i don't know where the problem is
