### ISSUE TITLE
Getting redirected to port 80 when saving settings for some reason...

### ISSUE THREAD

**Issue by LazosPlaying** [AzuraCast/AzuraCast#736]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu

**Describe the bug**
When saving system settings the form submission is always directed to `host.tld:80/uri` which is not really accepted by CloudFlare for some reason. So I get the "Server unexpectedly closed the connection." message.

**To Reproduce**
1. Go to admin panel `/admin/settings`
2. Scroll to bottom of the page
3. Submit the form (save changes)

**Expected behavior**
Not getting redirected to port 80

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera 
 - Version 54.0.2952.71 stable

**Comment by SlvrEagle23** [comment]
@LazosPlaying Should be fixed now. Didn't expect that explicitly specifying the port in the URI redirect like that would cause trouble.
