### ISSUE TITLE
Left sidebar width issue in greek locale

### ISSUE THREAD

**Issue by kosnick** [AzuraCast/AzuraCast#7367]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#d7070dd (2024-07-21 15:48) 

### What happened?

Verifying the greek translation.
When translated into greek the left sidebar's width is not enough.
Administration -> Stations -> Install GeoLite IP Database, translates into greek as 
"Εγκατάσταση Βάσης Δεδομένων GeoLite IP" 
which is longer than the sidebar's width.
And hence, part of it is hidden.
Here is a screenshot of the issue:

![azuracast_greek](https://github.com/user-attachments/assets/1f0f224b-66b8-4d1f-bf3d-ef4b10d0e681)

I tried investigating a bit more, but my knowledge in php, vue and ts and extremely limited (...zero!).
If this helps, two files seem to me related to this issue:

frontend/components/Admin/Stations.vue
frontend/components/Admin/menu.ts

Maybe, something like "auto width" could fix this.
Or, if the width needs to stay as is, different display of the translation???

**Comment by mdrxy** [comment]
It looks like those `nav-link` list items should have `display: block` for ellipses to display:
<img width="788" alt="Screenshot" src="https://github.com/user-attachments/assets/5e275242-d689-434a-b94e-72ddf153e5b4">

Currently, they take on `inline-flex`.

However, applying `block` to all `.nav-link` items (by appending `!important` to `display: block` in [`_navdrawer.scss`](https://github.com/AzuraCast/AzuraCast/blob/5b009153e00ad5d701befe00ea14f20bffed99ce/frontend/scss/overrides/_navdrawer.scss#L92)) overrides the `inline-flex` needed to center the section header links (System Maintenance, Users, and Stations in this case).

So, `!important` seems to also be necessary for `display` under `.navdrawer-nav .nav-link`.

I'm not well versed in Sass, so I can't make a precise suggestion in the code adjustment.
