### ISSUE TITLE
Update available but unable to update

### ISSUE THREAD

**Issue by Sella-GH** [AzuraCast/AzuraCast#7368]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #a234059 (2024-08-01 21:40)

### What happened?

The latest GitHub commit https://github.com/AzuraCast/AzuraCast/commit/6660854136ed7cc679ba1dd056d4fb5f57d9e6fa pushes the integrated update to an invalid state (again). No new build was pushed through GitHub Actions but somehow it recognizes the new commit as an update and wants that one updates to the new version.

However when clicking on the "Update Via Web" button or running the install script nothing gets really updated. Instead it just stays on the old version.

Can this behavior be modified so that the updater ignores commits on which no action run through or the action failed? Failed too because it still recognizes the update but it's unable to update.

**Comment by nexion63** [comment]
Hello,
it's the same on my test and production servers.

**Comment by BusterNeece** [comment]
I've updated how the central updates server responds to Rolling Release users to only return updates for commits that we know successfully deployed (by adding a webhook on successful package deploy that we use to set a flag on the commit). This should make it quite a lot more reserved in

**Comment by Sella-GH** [comment]
Okay nvm. I restarted the instance whole application and now it works again...
