### ISSUE TITLE
Migrate single station data

### ISSUE THREAD

**Issue by bombelman** [AzuraCast/AzuraCast#7370]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.20.1 Stable / Docker / PHP 8.3

### What happened?

Hi all,
Apart from station media files,
which files are required to do a single (1) station migration from 1 server/install to another?

I have all media/music files already in the exact same directories, how can I also copy/migrate the playlists and if possible the configs, so I don't have to reconfigure this one by one?

Please also take into account: migration of modified cue points etc...

Thanks !

**Comment by BusterNeece** [comment]
@bombelman Right now, we don't have a way to migrate all settings for a single station to another one on a different installation.

We have a feature request to enable single station backup, but we haven't implemented it yet: https://features.azuracast.com/suggestions/191858/exportimport-single-station
