### ISSUE TITLE
Jingle plays several times

### ISSUE THREAD

**Issue by BenMauriceKeil** [AzuraCast/AzuraCast#7371]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Powered by AzuraCast • Rolling Release #5b00915 (2024-08-06 1:06) • Docker • PHP 8.3

### What happened?

I have set everything up as usual, recently it doesn't matter if it's the stable or the rolling release version, the jingle always plays several times, once normally and then straight after that again at a quiet volume, or it plays it normally and then plays it another 10 times, or the second time it only plays half of the jingle, which is about 4 seconds, and then straight after that it plays the jingle again but only the last 3 seconds, really strange error, I have tried absolutely everything and don't know what to do anymore, I have already reset the server several times and reinstalled it several times, I urgently need help so that it works properly again and I can listen to the station normally again without interference.

**Comment by BenMauriceKeil** [comment]
If you can answer me in German this would be very helpful, because I work with the translator here and generally with things like this because I don't know if it is a German and/or English developer.

**Comment by t0mtaylor** [comment]
@BenMauriceKeil see my fix here - you need to delete some volumes so they are re-created from the db data

https://github.com/AzuraCast/AzuraCast/issues/7162#issuecomment-2143803893
