### ISSUE TITLE
Azuracast Icecast - Nginx Proxy Issues. - X-Real-IP

### ISSUE THREAD

**Issue by StefCoders** [AzuraCast/AzuraCast#7376]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.20.1 Stable • Docker • PHP 8.3

### What happened?

I recently changed to Icecast due to its stablity and compatibility but I have one problem. All the IPs are from my proxy that is needed for reasons. It has SSL and works perfectly. I have also tried adding `<x-forwarded-for>45.**.**.**</x-forwarded-for>`

My nginx config for the proxy:

```
server {
    server_name listen.moinestifm.ro;

    location / {
        proxy_pass http://91.**.**.**:8010;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        add_header 'Access-Control-Allow-Origin' '*' always;

        chunked_transfer_encoding on; 
        keepalive_timeout  65; 
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/listen.moinestifm.ro-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/listen.moinestifm.ro-0001/privkey.pem;
}

server {
    if ($host = listen.moinestifm.ro) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name listen.moinestifm.ro;
    return 404; # managed by Certbot
}

```
![Control-V](https://github.com/user-attachments/assets/5f975a5e-dd79-49ca-b02d-776d4323f615)

**Comment by joeyboli** [comment]
you need to add this config into your icecast configuration.

its at edit profile -> broadcasting -> custom config 

paste and restart your icecast server


`<paths>
<x-forwarded-for>PROXY_IP_ADDRESS</x-forwarded-for>
</paths>`

**Comment by StefCoders** [comment]
Thanks!

I didn't add <path>

**Solution:**

`**<paths> <x-forwarded-for>PROXY_IP_ADDRESS</x-forwarded-for> </paths>**`

**Comment by joeyboli** [comment]
Lol
