### ISSUE TITLE
Port 8080 and 8085 are not working anymore.

### ISSUE THREAD

**Issue by NeddyPlays** [AzuraCast/AzuraCast#738]
I have updated AzuraCast to the latest version today. After that the main station stopped working.
It looks like port 8080 and port 8085 are not open anymore. 

When i check the Firewall Port 8080 and 8085 are both open but nothing is mapped to it.

**Comment by djmuratb** [comment]
https://github.com/AzuraCast/AzuraCast/issues/722

**Comment by NeddyPlays** [comment]
Mine is not the same. The LiquedSoap is actually running and is playing Music. Can listen to it via the proxified listen link.

**Comment by SlvrEagle23** [comment]
@NeddyPlays If you're using Docker, your `docker-compose.yml` file may have updated. The simple solution is to open the file, scroll down to the bottom where the list of ports associated with the `stations` service are listed, add `"8080:8080"` (and `"8085:8085"` and `"8086:8086"`, most likely) to the list, then restart the service with `docker-compose down` and `docker-compose up -d`.

**Comment by NeddyPlays** [comment]
Let me try to find that! I am not that good without GUI lol

**Comment by SlvrEagle23** [comment]
@NeddyPlays Also keep in mind, once you've modified that file, you're using a custom `docker-compose.yml` file, which is completely fine, you just have to make sure to say "No" when updating if it asks if you want to replace your `docker-compose.yml` file with a new one.
