### ISSUE TITLE
Erroneous deletion of scheduled playlist items from station_queue

### ISSUE THREAD

**Issue by caturria** [AzuraCast/AzuraCast#7382]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

ca0bce7

### What happened?

For some time now, I've been experiencing an intermittent bug with sequential, scheduled playlists, in which one item (usually the first) would be skipped.

Recently I started observing the database as the station ran and waiting patiently for this to occur. Here's what I witnessed when I finally managed to catch it live:

I had a playlist scheduled as follows. Song-based, avoid duplicates off, general rotation, sequential. The playlist was scheduled to play from 9:30 to 9:45 PM, America/Toronto. The playlist contains a jingle, followed by six messages, followed by another jingle, for a total duration of 3 minutes, 28 seconds.

A few minutes before the scheduled time, the first jingle was queued up with two regular songs proceeding it, as expected. A few minutes later, the jingle was deleted from the station_queue table, and a song from unscheduled rotation was queued up in its place, naturally producing a gap in the sequence of IDs. This caused the scheduled block to begin late with its first item missing.

As the station itself is actually a private project, I do not wish to post logs publicly without redacting a fair amount of information. I would be happy to turn them over privately however. I'm also going to do a bit more digging to nail down exactly what triggers a queue item to get deleted. It'll be great to squash this bug as it's been making scheduled, sequential playlists unreliable for years.

**Comment by caturria** [comment]
Dear @BusterNeece:

I have tracked down this bug to lines 88 - 92 of queue.php:
```
                if (!$this->isQueueRowStillValid($queueRow, $expectedPlayTime)) {
                    $this->em->remove($queueRow);
                    continue;
                }
```

The media is not requeued on its associated playlist before being removed from the upcoming song queue, so it just gets skipped. This can occur seemingly at random, especially nowadays with AutoCue in the picture, because expected playtime calculations don't take dynamic crossfade durations into account. Improving expected playtime computation would prevent this from happening out of the blue, but it still happens if you manipulate the queue in some way (such as skipping a song).

Unfortunately, the fix for this seems ugly and nontrivial. The station_queue table needs to reference the station_playlist_media id so that the media can be un-played as far as the playlist is concerned. Worse yet is that if you remove one sequencial playlist item from station queue and re-queue it on its playlist, then any subsequent station queue items belonging to the same playlist are invalid too as they would play sequential items out of order. Lastly, when a queue item is removed as invalid, its duration must be subtracted from all subsequent items' expected playtime in order to prevent other manifestations of weirdness (sequentials playing out of order, schedules being interrupted by standard rotation, etc).

My thinking is to keep things as simple as possible, when an upcoming song is declared invalid, anything in the queue beyond that point should be discarded too: rewind playlists, re-queue requests and start over.

Your thoughts?

**Comment by BusterNeece** [comment]
@caturria I was actually going to respond to this here in short order, but you already got the PR in, and I reviewed and merged that into the latest Rolling Release.

I assume you tested it locally and it resolves your issue, but it's worth re-testing on Rolling just to make sure. If it fixes things, feel free to close.

Thanks again for your contributions!

**Comment by caturria** [comment]
Thank you @BusterNeece! I'll roll with it for a week or so, and will come back to either close this report or fix bugs.

I'm also working on the priority-based scheduler and expect to have a first draft of that in within a day or so. Its use will be entirely optional, and legacy behaviour will be carefully preserved for those who choose not to use the new feature.

Though it will amount to a pretty significant restructuring of the playlist selection machinery, I expect the power it will bring to the table will be well worth any growing pains.

It goes without saying, but if new scheduling issues do arise, feel free to mention me.

**Comment by caturria** [comment]
Hi @BusterNeece:

While working on the priority feature, I stumbled upon a couple more song selection bugs.

I have a question for you. What is the rationale behind this hardcoded prohibition on playing the same track back-to-back? The following is from Event\Radio\BuildQueue.php:
```
            if ($this->lastPlayedSongId === $nextSongs->getSongId()) {
                return false;
            }
```

Do I have your blessing to simply remove this? It just seems like an arbitrary restriction. though reasons to loop a track might be rare, it does not strike me as inconceivable that someone might legitimately want to do this.

It's also worth mentioning that this prohibition is actually bugged. The 'makeQueueFromApi' method (in Radio\AutoDJ\QueueBuilder) automatically persists the StationQueue item it generates. Then, QueueBuilder submits it, and if setNextSongs rejects it as a duplicate, it's of course too late: the item is silently queued anyway.

The results of this are unpredictable. The track will loop several times in a row, then at some point it'll manage to insert something from a different playlist.

Of course, the fix is as simple as removing the persist from makeQueueFromApi. But I don't see why playing a track multiple times should be prevented.

**Comment by Vaalyn** [comment]
@caturria I've looked through the Git history to track when this check was added:

It was added with commit 55444a7baa449fb58f9cb36a91be448f8392fe1e in response to #3682 around 3 years ago in a class that was refactored away in the meantime.

I don't remember anyone complaining that they cannot play songs back-to-back in those 3 years so I would be inclined to say we should keep it until we actually have reports about this being something needed with a good explanation as for the reason. I personally can't construe a good reason for a radio station to play the exact same song back-to-back though, it strikes me as a situation that pretty much every station would want to prevent, not even for ads it makes sense in my mind since you want your listeners to hear a more varied playout of both songs an ads (and it might confuse listeners to hear the same thing twice in a row and advertisers might even complain).

**Comment by BusterNeece** [comment]
@caturria @Vaalyn I think you both might be right in this case: most users won't want to play the same song back-to-back, but if we're persisting the record before "skipping" that queue item, then that could be exactly how that weird situation keeps popping up where people say the same track keeps looping over and over and over, the exact thing that function is supposed to prevent.

It probably merits some investigation to make sure that if it's trying to cancel the operation, that it properly resets things. We may even want to move that "cancellation" logic to be a part of the same logic that was recently updated to properly reset sequential playlists, etc.

**Comment by caturria** [comment]
This is resolved.
