### ISSUE TITLE
RSS owner email is missing in RSS feed

### ISSUE THREAD

**Issue by dabclassic-o** [AzuraCast/AzuraCast#7383]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.20.2

### What happened?

RSS owner email is missing in RSS feed

**Comment by BusterNeece** [comment]
I'm not able to reproduce this on the latest Rolling Release. The `itunes:owner` object lists properly for me, including e-mail address:

```xml
<itunes:owner>
    <itunes:name>AzuraCast</itunes:name>
    <itunes:email>demo@azuracast.com</itunes:email>
</itunes:owner>
```

**Comment by dabclassic-o** [comment]
Fixed in last version
