### ISSUE TITLE
We must catch up xx seconds even if there is enough server ressources

### ISSUE THREAD

**Issue by wegGehamstert** [AzuraCast/AzuraCast#7386]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #7b16397 

### What happened?

After some days of running azuracast with 4 stations, one use Autocue, all use StereoTool i get on every station the following problem: `[clock.main:2] We must catchup 3.95 seconds!`

The longer the station runs, the longer the delay becomes. He always manages to make up for the delay, but it always comes back after AutoCue prepares a song. The songs were also pre-tagged so that doesn't really make much sense.

**Settings of AutoCue:**
```
# settings.autocue.cue_file.path := "cue_file"
# settings.autocue.cue_file.fade_in := 0.1  # seconds #settings.autocue.cue_file.fade_out := 4.5  # seconds
# settings.autocue.cue_file.timeout := 60.0  # seconds
# settings.autocue.cue_file.target := -18.0  # LUFS
# settings.autocue.cue_file.silence := -42.0  # LU below track loudness
# settings.autocue.cue_file.overlay := -8.0  # LU below track loudness
# settings.autocue.cue_file.longtail := 15.0  # seconds
# settings.autocue.cue_file.noclip := false  # clipping prevention like loudgain's `-k`
 settings.autocue.cue_file.blankskip := 1.0  # skip silence in tracks
# settings.autocue.cue_file.unify_loudness_correction := true  # unify `replaygain_track_gain` & `liq_amplify`
settings.autocue.cue_file.write_tags := false  # write liq_* tags back to file
# settings.autocue.cue_file.force_analysis := false  # force re-analysis even if tags found
settings.autocue.cue_file.sustained_loudness_drop := 0.0
settings.autocue.cue_file.overlay_longtail := -12.0
```
**Server ressources:**
![image](https://github.com/user-attachments/assets/b12a7968-2cc1-4be1-8e2d-9d362e8a13b8)

### Relevant log output

```shell
2024/08/13 11:55:22 [cross_after_tail.4336:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:55:22 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/5/liquidsoap/feedback' with body: {"song_id":"5578aad0e17876b261654202896248f6","artist":"Lefwee, BOOTY LEAK, Margad","liq_cross_duration":"3.5","title":"Maneater","playlist_id":"61","media_id":"10869","liq_cross_start_next":"136.50"}
2024/08/13 11:55:22 [clock.main:2] We must catchup 2.29 seconds!
2024/08/13 11:55:22 [lang:3] API feedback - Response (200): true
2024/08/13 11:55:23 [clock.main:2] We must catchup 1.73 seconds!
2024/08/13 11:55:24 [clock.main:2] We must catchup 1.23 seconds!
2024/08/13 11:57:36 [decoder:2] Decoding "/var/azuracast/stations/mainstream/media/• InTheMiX/» remix&mashup/lefwee_-_maneater.mp3" ended: Ffmpeg_decoder.End_of_file.
2024/08/13 11:57:37 [next_song:3] Prepared "/var/azuracast/stations/mainstream/media/• InTheMiX/» brandnew/milcon_-_big_jet_plane.mp3" (RID 8021).
2024/08/13 11:57:37 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/5/liquidsoap/nextsong' with body: 
2024/08/13 11:57:37 [lang:3] API nextsong - Response (200): annotate:title="Body",artist="Loud Luxury",duration="163.24",song_id="8d95b224e41b3c2f351fb67e6b488af2",media_id="6364",liq_amplify="-11.1 dB",liq_amplify_adjustment="0.00 dB",liq_autocue="cue_file",liq_blank_skipped="false",liq_blankskip="1.00",liq_cross_duration="2.50",liq_cross_start_next="161.50",liq_cue_duration="162.50",liq_cue_in="0.00",liq_cue_out="162.50",liq_fade_in="0.10",liq_fade_in_delay="1.30",liq_fade_out="1.00",liq_fade_out_delay="1.50",liq_longtail="false",liq_loudness="-6.90 LUFS",liq_loudness_range="5.73 LU",liq_reference_loudness="-18.00 LUFS",liq_sustained_ending="false",liq_true_peak="1.45",liq_true_peak_db="3.20 dBFS",replaygain_reference_loudness="-18.00 LUFS",replaygain_track_gain="-11.10 dB",playlist_id="62":media:» 10er /loud_luxury_-_body.mp3
2024/08/13 11:57:38 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/mainstream/media/» 10er /loud_luxury_-_body.mp3": {audio=pcm(stereo)}
2024/08/13 11:57:38 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/mainstream/media/» 10er /loud_luxury_-_body.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}, video: {codec: mjpeg, 800x800, yuvj420p}
2024/08/13 11:57:38 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/mainstream/media/» 10er /loud_luxury_-_body.mp3": {audio=pcm(stereo)}
2024/08/13 11:57:38 [show_meta:3] ("duration", "121.00")
2024/08/13 11:57:38 [show_meta:3] ("media_id", "10741")
2024/08/13 11:57:38 [show_meta:3] Now playing: Milcon; Masove; Niteblue - Big Jet Plane
2024/08/13 11:57:38 [show_meta:2] Warning: No liq_amplify found, expect loudness jumps!
2024/08/13 11:57:38 [cross:3] Analysis: -32.512258dB / -13.449577dB (3.49s / 3.51s)
2024/08/13 11:57:38 [cross:3] Computing crossfade transition over overlapping 3.49s buffered data at start and end.
2024/08/13 11:57:38 [source.22180:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:57:38 [audio.add.7391:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:57:39 [fade_in.7391:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:57:39 [fade_scale.7391:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:57:39 [track_amplify.14783:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:57:39 [blank.7393:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:57:39 [on_metadata.14782:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:57:39 [on_track.14784:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:57:39 [cross_after.7391:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:57:39 [buffer.19736:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:57:39 [fade_out.7391:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:57:39 [track_amplify.14782:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:57:39 [on_frame.14782:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:57:39 [on_metadata.14781:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:57:39 [on_track.14783:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:57:39 [cross_before.7391:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:57:39 [buffer.19734:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:57:39 [cross_after_tail.4337:3] Content type is {audio=pcm(stereo)}.
2024/08/13 11:57:39 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/5/liquidsoap/feedback' with body: {"song_id":"fed6e89c62c480b5255114126b9aba2d","artist":"Milcon; Masove; Niteblue","title":"Big Jet Plane","playlist_id":"77","media_id":"10741"}
2024/08/13 11:57:39 [clock.main:2] We must catchup 2.42 seconds!
2024/08/13 11:57:39 [lang:3] API feedback - Response (200): true
2024/08/13 11:57:40 [clock.main:2] We must catchup 2.14 seconds!
2024/08/13 11:57:41 [clock.main:2] We must catchup 2.02 seconds!
2024/08/13 11:57:42 [clock.main:2] We must catchup 2.01 seconds!
2024/08/13 11:57:43 [clock.main:2] We must catchup 1.70 seconds!
2024/08/13 11:57:44 [clock.main:2] We must catchup 1.31 seconds!
```

**Comment by wegGehamstert** [comment]
The problem occured after i used AutoCue after some time. So i guess maybe @Moonbase59 can help.

**Comment by RM-FM** [comment]
I have the same issue. Usually the issue occurs after 2-3 days. I've discussed this with Romain/Toots already and ran a very detailed performance monitoring (CPU, Memory, Disk, etc.) over a few days. There was no correlation of "we must catch up" to any performance stuff at all. As we were not able to track it down, I decided to go for a workaround restarting Azuracast each 48 hrs. which fixed the issue for now.

I am now putting all my hopes in Liquidsoap 2.3.0. Rolling Release is already out and I guess @BusterNeece and @Moonbase59 will start working behind the scenes very soon.

**Comment by RM-FM** [comment]
> The problem occured after i used AutoCue after some time. So i guess maybe @Moonbase59 can help.

@wegGehamstert It seems to be a Liquidsoap internal issue but not related to @Moonbase59's Autocue code.

**Comment by wegGehamstert** [comment]
> I’m experiencing the same issue, which typically happens after 2-3 days. I’ve already discussed it with Romain/Toots and conducted thorough performance monitoring (CPU, Memory, Disk, etc.) over several days. There was no correlation between the `we must catch up` messages and any performance metrics. Since we couldn't pinpoint the cause, I opted for a workaround by restarting Azuracast every 48 hours, which has resolved the issue for now.
> 
> Now, I’m placing all my hopes on Liquidsoap `2.3.0`. The Rolling Release is already out, and I’m confident that @BusterNeece and @Moonbase59 will start working behind the scenes very soon.

Thank you so much for your response. I was a little bit worried, that i'm the only one with the problem.
But yeah, then it seams like i will need to do the same and hope for Liquidsoap 2.3.0. Weirdly enough that nobody else mentioned the issue. _Issue is not resolved so i wont close the report unless it works without it_

**Comment by RM-FM** [comment]
@wegGehamstert I managed to get the Azuracast `dev-ls2.3.x` branch running with Autocue. However, there are some changes required by @Moonbase59 in `autocue.cue_file.liq` (or `autocue.liq` in Azuracast respectively):

- Regular expression used in `check_autocue_setup` / `semver` do not work anymore
- Setting `settings.autocue.target_cross_duration` is not available in 2.3.x and therefore needs to be removed

First impressions are very promising! It seems that Romain really managed to greatly improve the whole transition/crossfade things in LS 2.3.x (at least when using autocue). To me the transitions sound more smooth and reliable even with very short jingles.

Unfortunately, there is also an issue while trying to save the LS config. But I guess that one is not a big deal for @BusterNeece to fix.

`At line 1, char 0-12: Error 14: Uncaught runtime error: type: not_found, message: "File not found! Given path: -, resolved path: ./-", stack: at line 1, char 0-12`

**Comment by wegGehamstert** [comment]
> @wegGehamstert I managed to get the Azuracast `dev-ls2.3.x` branch running with Autocue. However, there are some changes required by @Moonbase59 in `autocue.cue_file.liq` (or `autocue.liq` in Azuracast respectively):
> 
> * Regular expression used in `check_autocue_setup` / `semver` do not work anymore
> * Setting `settings.autocue.target_cross_duration` is not available in 2.3.x and therefore needs to be removed
> 
> First impressions are very promising! It seems that Romain really managed to greatly improve the whole transition/crossfade things in LS 2.3.x (at least when using autocue). To me the transitions sound more smooth and reliable even with very short jingles.
> 
> Unfortunately, there is also an issue while trying to save the LS config. But I guess that one is not a big deal for @BusterNeece to fix.
> 
> `At line 1, char 0-12: Error 14: Uncaught runtime error: type: not_found, message: "File not found! Given path: -, resolved path: ./-", stack: at line 1, char 0-12`

Oh wow thats very good news, thanks for coming back to this issue!
Do you run the `dev-ls2.3.x` branch in a productive environment or is this a test environment?
Would love to test this out too but maybe i should wait until everything is more stable

**Comment by RM-FM** [comment]
> Do you run the `dev-ls2.3.x` branch in a productive environment or is this a test environment?
No, of course not :-)

**Comment by wegGehamstert** [comment]
Okey haha, i was a little bit worried would you mind sending a link wich i can listen to this dev branch station?

**Comment by RM-FM** [comment]
> Okey haha, i was a little bit worried would you mind sending a link wich i can listen to this dev branch station?

No, it's not public, but you can follow the discussion about LS 2.3.0 and Azuracast here: https://github.com/AzuraCast/AzuraCast/discussions/7354

**Comment by t0mtaylor** [comment]
See my comment here - https://github.com/AzuraCast/AzuraCast/issues/7402#issuecomment-2322058186

**Comment by mishcazzulani** [comment]
Hello, I'm experiencing this same issue on stable 0.20.2 

@RM-FM did you schedule the restart with the CLI command azuracast:radio:restart? Isn't it enough to schedule a reload?

**Comment by RM-FM** [comment]
> Hello, I'm experiencing this same issue on stable 0.20.2
> 
> @RM-FM did you schedule the restart with the CLI command azuracast:radio:restart? Isn't it enough to schedule a reload?

@mishcazzulani Sorry, missed your question. Actually, I'm restarting the while docker container. But `azuracast:radio:restart` should work as well.

**Comment by BusterNeece** [comment]
There are several issues currently open regarding the "We must catchup..." errors currently, and while I've been able to reproduce them from time to time, they're intermittent and often hard to diagnose.

Since this issue is specific to Liquidsoap, I'd recommend creating an issue on their GitHub here: https://github.com/savonet/liquidsoap

Before creating an issue, however, I'd recommend updating, if possible, to the latest Rolling Release, which uses the release version of Liquidsoap 2.3.0, which offers a fair number of performance and memory improvements. If this doesn't resolve your issue, then creating a new issue on Liquidsoap's GitHub is recommended.

If there's anything in our configuration that we need to change, feel free to create a new issue here.
