### ISSUE TITLE
Don't check for audio metadata Album Art for large files over X mb in size

### ISSUE THREAD

**Issue by t0mtaylor** [AzuraCast/AzuraCast#7389]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #cbc07f4 (2024-08-12 0:15) • Docker • PHP 8.3

### What happened?

Don't check for audio metadata Album Art for large files over X mb in size

The logs output alot of large files for syndicate shows that are 50-300mb in size, which shouldn't need to be checked for meatdata or albumart from LastFm, MusicBrainz, etc

Can we set a max file size within the config somewhere with a toggle for Album Art (such as 20MB) before these external data sources are queued to pull remote data, so only smaller track files will be checked?

You could also disable Album Art metadata for files which are within a playlist with "Hide Metadata from Listeners" enabled?

This will also reduce any limit errors from the third parties

Related issue: https://github.com/AzuraCast/AzuraCast/issues/5103

### Relevant log output

```shell
Lots of errors checking files which dont need to be checked:

 (RuntimeException(code: 6): last.fm API error: Track not found at /var/azuracast/www/backend/src/Service/LastFm.php:95)","song":" - large mp3 file of show bigger than 20 MB.mp3","songId":"046414eafca79fd9a0118fa8c0d13c0b"} []
 (RuntimeException(code: 6): last.fm API error: Track not found at /var/azuracast/www/backend/src/Service/LastFm.php:95)","song":" - large mp3 file of show bigger than 20 MB.mp3","songId":"046414eafca79fd9a0118fa8c0d13c0b"} []
 (RuntimeException(code: 6): last.fm API error: Track not found at /var/azuracast/www/backend/src/Service/LastFm.php:95)","song":" - large mp3 file of show bigger than 20 MB.mp3","songId":"046414eafca79fd9a0118fa8c0d13c0b"} []
 (RuntimeException(code: 6): last.fm API error: Track not found at /var/azuracast/www/backend/src/Service/LastFm.php:95)","song":" - large mp3 file of show bigger than 20 MB.mp3","songId":"046414eafca79fd9a0118fa8c0d13c0b"} []
 (RuntimeException(code: 6): last.fm API error: Track not found at /var/azuracast/www/backend/src/Service/LastFm.php:95)","song":" - large mp3 file of show bigger than 20 MB.mp3","songId":"046414eafca79fd9a0118fa8c0d13c0b"} []
 (RuntimeException(code: 6): last.fm API error: Track not found at /var/azuracast/www/backend/src/Service/LastFm.php:95)","song":" - large mp3 file of show bigger than 20 MB.mp3","songId":"046414eafca79fd9a0118fa8c0d13c0b"} []
```

**Comment by mdrxy** [comment]
If this were to be implemented (as an advanced config setting), I'd be cautious with setting a low default, since FLAC/uncompressed songs are 40-60MB+ each on average.

> This will also reduce any limit errors from the third parties

How do you mean?

> Related issue: [#5103](https://github.com/AzuraCast/AzuraCast/issues/5103)

How does this relate? If I'm reading it correct, that issue doesn't relate to file sizes.

**Comment by Sella-GH** [comment]
I'd suggest to implement a hard default setting limiting the file size to the API maximum standards of the said service(s). Possibly by file type because the log output says the limit for mp3 is at 20 MB, maybe the limit for FLAC is automatically at 50 or higher.

**Comment by t0mtaylor** [comment]
> I'd suggest to implement a hard default setting limiting the file size to the API maximum standards of the said service(s). Possibly by file type because the log output says the limit for mp3 is at 20 MB, maybe the limit for FLAC is automatically at 50 or higher.

@Sella-GH Yea that would work, can have an object of key values with each file type and a max file size, set some default options which can be adjusted


> > This will also reduce any limit errors from the third parties
> 
> How do you mean?

@mdrxy most third parties have an api limit for requests, if a station has alot of syndicate/pre-recorded shows and then Azuracast hammers the api with files not even worth checking against (the ones we want to exclude), then Azuracast will be hit with the limit which will slow down the fetch of metadata for single tracks that you wanted to check
> 
> > Related issue: [#5103](https://github.com/AzuraCast/AzuraCast/issues/5103)
> 
> How does this relate? If I'm reading it correct, that issue doesn't relate to file sizes.

There are other issues when using the api where the relevant data or backup isn't working, these issues could be caused by the api limiter - the proposed changes in this ticket may help reduce the impact with the other ticket, plus it is good practice to link similar tickets so we can discuss :)
