### ISSUE TITLE
Streaming not working and trouble with now-playing data in AzuraCast player

### ISSUE THREAD

**Issue by ivi-v** [AzuraCast/AzuraCast#7390]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #5dc00dd

### What happened?

Hello! I reinstalled AzuraCast a month ago with the last version in a new Ubuntu server after using an old one for some years. The thing is that the streaming does not work in AzuraCast player, nor in the "official" widget, so I need to use third-party players for the radio's website.

In addition, one of my radios is 24/7 connected to RadioBOSS and the now-playing metadata is not shown in Azura, but it does on Icecast stream.

Thank you in advance!

**Comment by BusterNeece** [comment]
Please explain the problem in greater detail, along with any corresponding logs (i.e. from the Log Viewer or your browser's console if streaming playback isn't working).

**Comment by ivi-v** [comment]
Hello!

It is as I described: the player from AzuraCast does not "launch" the streaming playback when pressing Play button. What I found is that it only happens in Mozilla Firefox (of course, I have adblock disabled), while in Google Chrome it works well.

What do you mean with logs from the browser? Is that the view-source page? I was observing it in both Chrome and Firefox and it's identical, so I don't know where the trouble is.

Thanks!!

**Comment by bombelman** [comment]
> What do you mean with logs from the browser?

in your station admin, the last menu item on the bottom left has logs.

**Comment by ivi-v** [comment]
Thank you! I hope I understood it well. I think these are the IceCast error logs while I was trying to play on my Firefox browser:

`[2024-08-16  01:22:30] WARN fserve/fserve_client_create req for file "/usr/local/share/icecast/web/query" No such file or directory
[2024-08-16  01:22:30] WARN fserve/fserve_client_create req for file "/usr/local/share/icecast/web/v2/_catalog" No such file or directory
[2024-08-16  01:22:30] WARN fserve/fserve_client_create req for file "/usr/local/share/icecast/web/cgi-bin/authLogin.cgi" No such file or directory
[2024-08-16  01:22:30] WARN fserve/fserve_client_create req for file "/usr/local/share/icecast/web/solr/admin/info/system" No such file or directory
[2024-08-16  01:22:30] WARN connection/http_client_request unhandled request type from 172.233.81.59
[2024-08-16  01:22:30] WARN fserve/fserve_client_create req for file "/usr/local/share/icecast/web/solr/admin/cores" No such file or directory `

**Comment by Vaalyn** [comment]
There are 2 things which are needed here:

1. The liquidsoap autodj logs of the station from the `Logs` -> `Liquidsoap Log`
2. Open the Browsers JavaScript Console (in Firefox this is either Ctrl + Shift + K (or Cmd + Option + K on a Mac) while being on the player page, then try to start the playback and copy & paste all output from that here

The first is to check if the AutoDJ is handling the stream generation correctly and the second is to check if the browser says anything about it not being able to start the plackback

**Comment by ivi-v** [comment]
Okay. As you say, an error appears in the browser's console while trying to play the stream:

`Uncaught (in promise) TypeError: HTMLMediaElement.volume setter: Value being assigned is not a finite floating-point value.
    d https://radio.oniriaradio.com/static/vite_dist/usePlayerVolume-D41vbOkv.js:1
    promise callback*Qn https://radio.oniriaradio.com/static/vite_dist/vue-CMqoy3Jy.js:13
    d https://radio.oniriaradio.com/static/vite_dist/usePlayerVolume-D41vbOkv.js:1
    setup https://radio.oniriaradio.com/static/vite_dist/usePlayerVolume-D41vbOkv.js:1
    je https://radio.oniriaradio.com/static/vite_dist/vue-CMqoy3Jy.js:13
    we https://radio.oniriaradio.com/static/vite_dist/vue-CMqoy3Jy.js:13
    q https://radio.oniriaradio.com/static/vite_dist/vue-CMqoy3Jy.js:13
    je https://radio.oniriaradio.com/static/vite_dist/vue-CMqoy3Jy.js:13
    Wi https://radio.oniriaradio.com/static/vite_dist/vue-CMqoy3Jy.js:13
    promise callback*Ki https://radio.oniriaradio.com/static/vite_dist/vue-CMqoy3Jy.js:13
    zn https://radio.oniriaradio.com/static/vite_dist/vue-CMqoy3Jy.js:13
    x https://radio.oniriaradio.com/static/vite_dist/vue-CMqoy3Jy.js:13
    Ys https://radio.oniriaradio.com/static/vite_dist/vue-CMqoy3Jy.js:9
    Si https://radio.oniriaradio.com/static/vite_dist/vue-CMqoy3Jy.js:9
    Rt https://radio.oniriaradio.com/static/vite_dist/vue-CMqoy3Jy.js:9
    set value https://radio.oniriaradio.com/static/vite_dist/vue-CMqoy3Jy.js:9
    s https://radio.oniriaradio.com/static/vite_dist/usePlayerStore-BPjELoVJ.js:7
    n https://radio.oniriaradio.com/static/vite_dist/PlayButton-DJke4FgJ.js:1
    je https://radio.oniriaradio.com/static/vite_dist/vue-CMqoy3Jy.js:13
    we https://radio.oniriaradio.com/static/vite_dist/vue-CMqoy3Jy.js:13
    n https://radio.oniriaradio.com/static/vite_dist/vue-CMqoy3Jy.js:17
usePlayerVolume-D41vbOkv.js:1:1396
`

In relation to LiquidSoap's logs, I attach you some of the last ones. The previous are more or less the same; this seems to be about the problems with now-playing widget:

`2024/08/18 23:31:39 [input_streamer:3] New metadata chunk ? -- James Blunt - 1973.
2024/08/18 23:31:43 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {"title":"James Blunt - 1973"}
2024/08/18 23:31:44 [lang:3] API feedback - Response (200): false
2024/08/18 23:36:06 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/auth' with body: { "user": "oniriadirecto", "password": "OniriaLive24" }
2024/08/18 23:36:06 [lang:3] API auth - Response (200): true
2024/08/18 23:36:06 [input_streamer:3] New metadata chunk ? -- M-Clan - Miedo.
2024/08/18 23:36:11 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {"title":"M-Clan - Miedo"}
2024/08/18 23:36:11 [lang:3] API feedback - Response (200): false
2024/08/18 23:40:55 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/auth' with body: { "user": "oniriadirecto", "password": "OniriaLive24" }
2024/08/18 23:40:56 [lang:3] API auth - Response (200): true
2024/08/18 23:40:56 [input_streamer:3] New metadata chunk ? -- Mads Langer - You're Not Alone.
2024/08/18 23:41:01 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {"title":"Mads Langer - You're Not Alone"}
2024/08/18 23:41:02 [lang:3] API feedback - Response (200): false
2024/08/18 23:44:00 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/auth' with body: { "user": "oniriadirecto", "password": "OniriaLive24" }
2024/08/18 23:44:02 [lang:3] API auth - Response (200): true
2024/08/18 23:44:02 [input_streamer:3] New metadata chunk ? -- Spice Girls - Wannabe.
2024/08/18 23:44:06 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {"title":"Spice Girls - Wannabe"}
2024/08/18 23:44:07 [lang:3] API feedback - Response (200): false
`

**Comment by Vaalyn** [comment]
For me the playback works in FF on the public player of the domain shown in the browser logs.

Generally the browser logs you posted say that the player tried to set an invalid value to the volume control. I think the likely problem is that for some reason your FF has an invalid value saved in it's cookies for the player which it then tries to apply to the volume.

Try clearing your cache & cookies for the domain.

**Comment by ivi-v** [comment]
It worked, thank you so much!!

What is still wrong is the now-playing data on AzuraCast. On the other version I had, metadata showed the song it was being played while connected to an external service (such as RadioBOSS in my case), but now it doesn't.

Is it related to the LiquidSoap logs I posted?

**Comment by ivi-v** [comment]
I've updated AzuraCast to the last version and the issue with now-playing data seems already fixed.

Thank you so much for your help!!

**Comment by ivi-v** [comment]
I've updated AzuraCast to the last version and the issue with now-playing data seems already fixed.

Thank you so much for your help!!
