### ISSUE TITLE
error 502 bad gateway after update to stable version 0.20.2

### ISSUE THREAD

**Issue by DJMic** [AzuraCast/AzuraCast#7395]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.20.1

### What happened?

I've tried to update from stable version 0.20.1 to 0.20.2 but after update, I've an error 502 bad gateway. I waited more than 10 minutes and this message is always display.

**Comment by BusterNeece** [comment]
We need logs to know what's causing this: https://www.azuracast.com/docs/help/logs/#docker-container-logs

**Comment by DJMic** [comment]
Today, updating works successfully. I don't understand why it didn't work the previous days.
