### ISSUE TITLE
Mixed response not accounted for in OpenAPI.yml

### ISSUE THREAD

**Issue by Lexian-droid** [AzuraCast/AzuraCast#7396]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#48b55e4 (2024-08-17 7:28)

### What happened?

I generated a PHP API client using OpenAPI's Generator Cli, otherwise called a "Codegen" I believe, and I am having an issue with the submitSongRequest endpoint.

Basically, on the first request, to a song that hasn't yet been played, it responds normally, code 200, "message" and "message_formatted", all is good, however, if you request that same song again, or a song that was played recently, it will respond with an error 500, which I assume is normal, but the issue lies with the OpenAPI.yml file.

The file instructs the client to expect a different type of response, causing the client to throw an exception, ``Invalid array 'mixed[]`` which I believe may be the result of something in the OpenAPI.yml file.

I've submitted the same type of issue with the generator's repository, in case it is an issue with the PHP API Client, but I wanted to also put an issue in here, as It does relate to Azuracast, and it's possibly an issue with the OpenAPI.yml.

Here is the issue I've placed in their repo: https://github.com/OpenAPITools/openapi-generator/issues/19379 in case it will help find more details.

**Comment by Vaalyn** [comment]
🤔 as far as I can tell the OA Attributes should be correct for this case on our side:

- The endpoint has a defined response for error code `500`: https://github.com/AzuraCast/AzuraCast/blob/main/backend/src/Controller/Api/Stations/Requests/SubmitAction.php#L47 
- The response points to the `GenericError` response definition: https://github.com/AzuraCast/AzuraCast/blob/main/backend/src/OpenApi.php#L96-L99
- The `GenericError` response points to the `Api_Error` schema which includes the `extra_data` property, which is what this exception seems to point to: https://github.com/AzuraCast/AzuraCast/blob/48b55e43b986fafbb380ebd437fc08ca4037c41a/backend/src/Entity/Api/Error.php#L42-L46

**Comment by Lexian-droid** [comment]
> 🤔 as far as I can tell the OA Attributes should be correct for this case on our side:
> 
>     * The endpoint has a defined response for error code `500`: https://github.com/AzuraCast/AzuraCast/blob/main/backend/src/Controller/Api/Stations/Requests/SubmitAction.php#L47
> 
>     * The response points to the `GenericError` response definition: https://github.com/AzuraCast/AzuraCast/blob/main/backend/src/OpenApi.php#L96-L99
> 
>     * The `GenericError` response points to the `Api_Error` schema which includes the `extra_data` property, which is what this exception seems to point to: https://github.com/AzuraCast/AzuraCast/blob/48b55e43b986fafbb380ebd437fc08ca4037c41a/backend/src/Entity/Api/Error.php#L42-L46

Oh jeez, I don't know what the issue could be then honestly, I don't know if you've checked, but I've had Gemini review the code as well, since it's too much code for a human to review, and it thinks it's the following code:
```yaml
        extra_data:
          description: Stack traces and other supplemental data.
          type: array
          items: {}
```
"The key point here is that the extra_data field is an array, but the type of items within the array is not explicitly defined (represented by items: { }). In OpenAPI, this translates to a "mixed" type, meaning the array can contain elements of any data type."

I don't know if that's a problem though.

**Comment by Vaalyn** [comment]
Could you adjust your code a bit, then try it again and post what is printed when it fails?

```php
try {
    $result = $apiInstance->submitSongRequest($station_id, $request_id);
    print_r($result);
} catch (Throwable $e) {
    print_r($e);
}
```

I'd like to see where exactly the generated code fails, my hunch is that the [ObjectSerializer::deserialize](https://github.com/Lexian-droid/azuracast-php-api-client/blob/master/src/ObjectSerializer.php#L402-L545) somehow ends up trying to call `deserialize` on one of the sub entries of that array while still supplying it with the `$class` as `mixed[]` instead of `mixed` which would lead it to end up in the marked block of code instead of falling through to the block that explicitly handles `mixed` itself.

**Comment by Lexian-droid** [comment]
> Could you adjust your code a bit, then try it again and post what is printed when it fails?
> 
> ```
> try {
>     $result = $apiInstance->submitSongRequest($station_id, $request_id);
>     print_r($result);
> } catch (Throwable $e) {
>     print_r($e);
> }
> ```
> 
> I'd like to see where exactly the generated code fails, my hunch is that the [ObjectSerializer::deserialize](https://github.com/Lexian-droid/azuracast-php-api-client/blob/master/src/ObjectSerializer.php#L402-L545) somehow ends up trying to call `deserialize` on one of the sub entries of that array while still supplying it with the `$class` as `mixed[]` instead of `mixed` which would lead it to end up in the marked block of code instead of falling through to the block that explicitly handles `mixed` itself.

Sure, here is the output for that:

```
InvalidArgumentException Object ( [message:protected] => Invalid array 'mixed[]' [string:Exception:private] => [code:protected] => 0 [file:protected] => D:\Documents\Web Testing\openapi-generator\output\azuracast-php-api-client\src\ObjectSerializer.php [line:protected] => 412 [trace:Exception:private] => Array ( [0] => Array ( [file] => D:\Documents\Web Testing\openapi-generator\output\azuracast-php-api-client\src\ObjectSerializer.php [line] => 540 [function] => deserialize [class] => AzuraCast\ObjectSerializer [type] => :: [args] => Array ( [0] => stdClass Object ( [class] => NotFoundException [file] => /var/azuracast/www/backend/src/Exception/NotFoundException.php [line] => 24 ) [1] => mixed[] [2] => ) ) [1] => Array ( [file] => D:\Documents\Web Testing\openapi-generator\output\azuracast-php-api-client\src\Api\StationsSongRequestsApi.php [line] => 757 [function] => deserialize [class] => AzuraCast\ObjectSerializer [type] => :: [args] => Array ( [0] => stdClass Object ( [code] => 404 [type] => NotFoundException [message] => Record not found. [formatted_message] => Record not found. [extra_data] => stdClass Object ( [class] => NotFoundException [file] => /var/azuracast/www/backend/src/Exception/NotFoundException.php [line] => 24 ) [success] => ) [1] => \AzuraCast\Model\ApiError [2] => Array ( [Date] => Array ( [0] => Mon, 19 Aug 2024 16:23:12 GMT ) [Content-Type] => Array ( [0] => application/json ) [Transfer-Encoding] => Array ( [0] => chunked ) [Connection] => Array ( [0] => keep-alive ) [vary] => Array ( [0] => Accept-Encoding ) [x-powered-by] => Array ( [0] => PHP/8.3.10 ) [CF-Cache-Status] => Array ( [0] => DYNAMIC ) [Report-To] => Array ( [0] => {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=88OC6RqFxcZZkqsB1P2iGLQdAZJgxbpyVKWxrdr86IDH7VixI1Jy4oq7Wkv1jGLLpjMDWzZagKCSbOn4cAvDfSpLEGavAWTTzgFDh3AeWGcZ6f%2BXLREPKQirga4BExt6PPO4Fg%3D%3D"}],"group":"cf-nel","max_age":604800} ) [NEL] => Array ( [0] => {"success_fraction":0,"report_to":"cf-nel","max_age":604800} ) [X-Content-Type-Options] => Array ( [0] => nosniff ) [Server] => Array ( [0] => cloudflare ) [CF-RAY] => Array ( [0] => 8b5b7c9d39dd4362-EWR ) [alt-svc] => Array ( [0] => h3=":443"; ma=86400 ) ) ) ) [2] => Array ( [file] => D:\Documents\Web Testing\openapi-generator\output\azuracast-php-api-client\src\Api\StationsSongRequestsApi.php [line] => 545 [function] => submitSongRequestWithHttpInfo [class] => AzuraCast\Api\StationsSongRequestsApi [type] => -> [args] => Array ( [0] => azuratest_radio [1] => b283195df2bbf1b418a27a65 [2] => application/json ) ) [3] => Array ( [file] => D:\Documents\Web Testing\azuracast_api_test\public\index.php [line] => 17 [function] => submitSongRequest [class] => AzuraCast\Api\StationsSongRequestsApi [type] => -> [args] => Array ( [0] => azuratest_radio [1] => b283195df2bbf1b418a27a65 ) ) ) [previous:Exception:private] => ) 
```

Sorry about the length, I don't know if there's any formatting I can do.

**Comment by Vaalyn** [comment]
I've reformatted the output to be more readable 👍 

This gives us a good clue as to what's happening here.

The code generator read the OA yaml, read the definition of the [Api_Error](https://github.com/AzuraCast/AzuraCast/blob/48b55e43b986fafbb380ebd437fc08ca4037c41a/backend/src/Entity/Api/Error.php#L42-L46) and parse this `extra_data` field which we annotate as an array of `OA\Items`, which the generator interprets as a `mixed[]`.

Then when the generated `ObjectDeserializer` tries to parse the data it json decodes the response of the API into `stdClass` instances so the `extra_data` from the decoded json becomes a `stdClass` too instead of an array, which then causes it to not match the type that the generator got from the OA definition.

Not sure if / how this can be fixed from our side though 🤔

**Comment by Lexian-droid** [comment]
> I've reformatted the output to be more readable 👍
> 
> This gives us a good clue as to what's happening here.
> 
> The code generator read the OA yaml, read the definition of the [Api_Error](https://github.com/AzuraCast/AzuraCast/blob/48b55e43b986fafbb380ebd437fc08ca4037c41a/backend/src/Entity/Api/Error.php#L42-L46) and parse this `extra_data` field which we annotate as an array of `OA\Items`, which the generator interprets as a `mixed[]`.
> 
> Then when the generated `ObjectDeserializer` tries to parse the data it json decodes the response of the API into `stdClass` instances so the `extra_data` from the decoded json becomes a `stdClass` too instead of an array, which then causes it to not match the type that the generator got from the OA definition.
> 
> Not sure if / how this can be fixed from our side though 🤔

That is indeed a difficult issue to resolve, hmm... I'll see if I can do anything to fix it, I just hope I don't need to modify the actual generation tool, because I don't know Java 😅

**Comment by Lexian-droid** [comment]
Hello, unfortunately, I don't think I can fix the issue, also, a new problem has cropped up, essentially, when you have custom fields added, it'll show an error saying "Invalid array string[]" when getting requestable songs, which I also didn't know of until now, I was adding custom fields to see if it would fix it, but to no avail. I might retry submitting an issue on their repo, but I don't really have any other options other then that sadly.

**Comment by Vaalyn** [comment]
Sounds like it's probably the same root cause for that, generated code expects it to be an array but it's probably also decoded to a stdClass 😓

**Comment by Lexian-droid** [comment]
I hate to say it, but I don't think the codegen is a good idea anymore, It doesn't seem to be a "One size fits all" like I initally thought, and their repo is way too busy to get help regarding the problem unfortunately, so I believe I might just switch back to you guy's API, but I wanted to ask, if you guys consider adding more features to it in the future, could you add Scheduling support? I only wanted to make my own API client for that reason, I know it's overkill, but I figured it was inactive due to the 1 year gap in commits.

**Comment by Vaalyn** [comment]
> but the submitSongRequest() method seems to respond with a different error now:

You tried to request something again that was previously played which was prevented by AC and thus declined as a server error:

```
Cannot submit request: This song or artist has been played (truncated...)
```

That probably isn't resulting in an exception, just printing what's being returned. You could double check this by doing a `var_dump` instead of `print_r` to see what type of result is returned.

> Alright, I've tried on both methods, the getRequestableSongs() method, with custom fields, still results in a Invalid array string[],

Would you mind pushing the updated code and also posting the raw respone from the API when you get the list from your instances swagger page so I can see what format exactly is being give there?

**Comment by Lexian-droid** [comment]
> > but the submitSongRequest() method seems to respond with a different error now:
> 
> You tried to request something again that was previously played which was prevented by AC and thus declined as a server error:
> 
> ```
> Cannot submit request: This song or artist has been played (truncated...)
> ```
> 
> That probably isn't resulting in an exception, just printing what's being returned. You could double check this by doing a `var_dump` instead of `print_r` to see what type of result is returned.
> 
> > Alright, I've tried on both methods, the getRequestableSongs() method, with custom fields, still results in a Invalid array string[],
> 
> Would you mind pushing the updated code and also posting the raw respone from the API when you get the list from your instances swagger page so I can see what format exactly is being give there?

It does indeed throw an exception, also, which code do you mean? apologies, I don't quite understand.
Do you want me to PR the new openapi code to azuracast repo? or do you want me to update the client package?

**Comment by Vaalyn** [comment]
> It does indeed throw an exception
Then please post the full output of `print_r($e);` instead of just the message as that will help me better understand the reason of the exception

> ... also, which code do you mean? apologies, I don't quite understand.
The updated code that the generator gave you after you adjusted the OA definitions on the AzuraCast entities.
The code that you have in this repo: https://github.com/Lexian-droid/azuracast-php-api-client/tree/master

**Comment by Lexian-droid** [comment]
> Then please post the full output of print_r($e); instead of just the message as that will help me better understand the reason of the exception

Sorry, here is the exception.
```
AzuraCast\ApiException Object ( [message:protected] => [500] Server error: `POST https://demo.azuracast.com/api/station/azuratest_radio/request/b315edf2aa1b9195c31848b8` resulted in a `500 Internal Server Error` response: {"code":500,"type":"CannotCompleteActionException","message":"Cannot submit request: This song was already requested and (truncated...) [string:Exception:private] => [code:protected] => 500 [file:protected] => D:\Documents\Web Testing\openapi-generator\output\azuracast-php-api-client\lib\Api\StationsSongRequestsApi.php [line:protected] => 569 [trace:Exception:private] => Array ( [0] => Array ( [file] => D:\Documents\Web Testing\openapi-generator\output\azuracast-php-api-client\lib\Api\StationsSongRequestsApi.php [line] => 545 [function] => submitSongRequestWithHttpInfo [class] => AzuraCast\Api\StationsSongRequestsApi [type] => -> [args] => Array ( [0] => azuratest_radio [1] => b315edf2aa1b9195c31848b8 [2] => application/json ) ) [1] => Array ( [file] => D:\Documents\Web Testing\azuracast_api_test\public\index.php [line] => 23 [function] => submitSongRequest [class] => AzuraCast\Api\StationsSongRequestsApi [type] => -> [args] => Array ( [0] => azuratest_radio [1] => b315edf2aa1b9195c31848b8 ) ) ) [previous:Exception:private] => [responseBody:protected] => {"code":500,"type":"CannotCompleteActionException","message":"Cannot submit request: This song was already requested and will play soon.","formatted_message":"Cannot submit request: This song was already requested and will play soon.","extra_data":{"class":"CannotCompleteActionException","file":"/var/azuracast/www/backend/src/Exception/Http/CannotCompleteActionException.php","line":26},"success":false} [responseHeaders:protected] => Array ( [Date] => Array ( [0] => Thu, 22 Aug 2024 17:59:05 GMT ) [Content-Type] => Array ( [0] => application/json ) [Transfer-Encoding] => Array ( [0] => chunked ) [Connection] => Array ( [0] => keep-alive ) [x-powered-by] => Array ( [0] => PHP/8.3.10 ) [CF-Cache-Status] => Array ( [0] => DYNAMIC ) [Report-To] => Array ( [0] => {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=tJQQPRxVmnMOe7qY1hW%2FHbjgNLxouwgkNOjY6QR%2FYD2%2BKrkaEkFM8EyNWNvgiEh0h8VEoTTFmxlA5EXL2G%2FM%2BE%2BjLOggJW4aUUYK3LR9bNmN6NsQp%2FY%2BSDmzAkvYVIbhLo6BdQ%3D%3D"}],"group":"cf-nel","max_age":604800} ) [NEL] => Array ( [0] => {"success_fraction":0,"report_to":"cf-nel","max_age":604800} ) [X-Content-Type-Options] => Array ( [0] => nosniff ) [Server] => Array ( [0] => cloudflare ) [CF-RAY] => Array ( [0] => 8b74c1340cc943be-EWR ) [alt-svc] => Array ( [0] => h3=":443"; ma=86400 ) ) [responseObject:protected] => AzuraCast\Model\ApiError Object ( [openAPINullablesSetToNull:protected] => Array ( ) [container:protected] => Array ( [code] => 500 [type] => CannotCompleteActionException [message] => Cannot submit request: This song was already requested and will play soon. [formatted_message] => Cannot submit request: This song was already requested and will play soon. [extra_data] => Array ( [class] => CannotCompleteActionException [file] => /var/azuracast/www/backend/src/Exception/Http/CannotCompleteActionException.php [line] => 26 ) [success] => ) ) ) 
```

> The updated code that the generator gave you after you adjusted the OA definitions on the AzuraCast entities.
The code that you have in this repo: https://github.com/Lexian-droid/azuracast-php-api-client/tree/master

I've made the update to the repository, in an effort to fix it, I did change most parameters back to their default values, so you may need to modify the code a little bit on your end, but I am not 100% sure. assuming you're using autoloader, it should be fine.

**Comment by Vaalyn** [comment]
Okay, regarding the exception from the duplicate request:

The generated code doesn't take into account that Guzzle will by default throw Request exceptions for statu code 500 responses although we explicitly say that a 500 response is to be expected on that endpoint (https://github.com/Lexian-droid/azuracast-php-api-client/blob/46610764390421cf2a2d50835060326dd2df9488/lib/Api/StationsSongRequestsApi.php#L568-L574) which lets it throw an error directly after it received the response although the code generator also put some code below the try catch to handle the code 500 (which it can never actually reach due to Guzzle not being configured to ignore those here).

That's quite unfortunate 😅 
It would need to be supplied with the `'http_errors' => false` option so it doesn't throw on 4xx/5xx status codes. Not sure how that can be achieved.

The generated code calls a `createHttpClientOption` method, which sadly doesn't really look like you can provide options yourself: https://github.com/Lexian-droid/azuracast-php-api-client/blob/46610764390421cf2a2d50835060326dd2df9488/lib/Api/StationsSongRequestsApi.php#L962

Regarding the other request, can you post the printed exception for that too?

**Comment by Lexian-droid** [comment]
> Okay, regarding the exception from the duplicate request:
> 
> The generated code doesn't take into account that Guzzle will by default throw Request exceptions for statu code 500 responses although we explicitly say that a 500 response is to be expected on that endpoint (https://github.com/Lexian-droid/azuracast-php-api-client/blob/46610764390421cf2a2d50835060326dd2df9488/lib/Api/StationsSongRequestsApi.php#L568-L574) which lets it throw an error directly after it received the response although the code generator also put some code below the try catch to handle the code 500 (which it can never actually reach due to Guzzle not being configured to ignore those here).
> 
> That's quite unfortunate 😅 It would need to be supplied with the `'http_errors' => false` option so it doesn't throw on 4xx/5xx status codes. Not sure how that can be achieved.
> 
> The generated code calls a `createHttpClientOption` method, which sadly doesn't really look like you can provide options yourself: https://github.com/Lexian-droid/azuracast-php-api-client/blob/46610764390421cf2a2d50835060326dd2df9488/lib/Api/StationsSongRequestsApi.php#L962
> 
> Regarding the other request, can you post the printed exception for that too?

Here is the output for the ``getRequestableSongs()``
```
InvalidArgumentException Object ( [message:protected] => Invalid array 'string[]' [string:Exception:private] => [code:protected] => 0 [file:protected] => D:\Documents\Web Testing\azuracast_api_test\vendor\lexiandev\azuracast-php-api-client\lib\ObjectSerializer.php [line:protected] => 417 [trace:Exception:private] => Array ( [0] => Array ( [file] => D:\Documents\Web Testing\azuracast_api_test\vendor\lexiandev\azuracast-php-api-client\lib\ObjectSerializer.php [line] => 545 [function] => deserialize [class] => AzuraCast\ObjectSerializer [type] => :: [args] => Array ( [0] => stdClass Object ( [tst] => a ) [1] => string[] [2] => ) ) [1] => Array ( [file] => D:\Documents\Web Testing\azuracast_api_test\vendor\lexiandev\azuracast-php-api-client\lib\ObjectSerializer.php [line] => 545 [function] => deserialize [class] => AzuraCast\ObjectSerializer [type] => :: [args] => Array ( [0] => stdClass Object ( [id] => 3de468a54bfa0c765f7f388c03778068 [art] => https://radio.aimusicradio.org/api/station/ai_music_radio_-_testing/art/30247cc9f585c6dffe563a15 [custom_fields] => stdClass Object ( [tst] => a ) [text] => - broccoli blues [artist] => [title] => broccoli blues [album] => [genre] => [isrc] => [lyrics] => ) [1] => \AzuraCast\Model\ApiSong [2] => ) ) [2] => Array ( [file] => D:\Documents\Web Testing\azuracast_api_test\vendor\lexiandev\azuracast-php-api-client\lib\ObjectSerializer.php [line] => 423 [function] => deserialize [class] => AzuraCast\ObjectSerializer [type] => :: [args] => Array ( [0] => stdClass Object ( [request_id] => 30247cc9f585c6dffe563a15 [request_url] => /api/station/6/request/30247cc9f585c6dffe563a15 [song] => stdClass Object ( [id] => 3de468a54bfa0c765f7f388c03778068 [art] => https://radio.aimusicradio.org/api/station/ai_music_radio_-_testing/art/30247cc9f585c6dffe563a15 [custom_fields] => stdClass Object ( [tst] => a ) [text] => - broccoli blues [artist] => [title] => broccoli blues [album] => [genre] => [isrc] => [lyrics] => ) ) [1] => \AzuraCast\Model\ApiStationRequest [2] => ) ) [3] => Array ( [file] => D:\Documents\Web Testing\azuracast_api_test\vendor\lexiandev\azuracast-php-api-client\lib\Api\StationsSongRequestsApi.php [line] => 217 [function] => deserialize [class] => AzuraCast\ObjectSerializer [type] => :: [args] => Array ( [0] => Array ( [0] => stdClass Object ( [request_id] => 30247cc9f585c6dffe563a15 [request_url] => /api/station/6/request/30247cc9f585c6dffe563a15 [song] => stdClass Object ( [id] => 3de468a54bfa0c765f7f388c03778068 [art] => https://radio.aimusicradio.org/api/station/ai_music_radio_-_testing/art/30247cc9f585c6dffe563a15 [custom_fields] => stdClass Object ( [tst] => a ) [text] => - broccoli blues [artist] => [title] => broccoli blues [album] => [genre] => [isrc] => [lyrics] => ) ) [1] => stdClass Object ( [request_id] => 5df7b7dcf3d6d3f7e0570a2c [request_url] => /api/station/6/request/5df7b7dcf3d6d3f7e0570a2c [song] => stdClass Object ( [id] => fa9d6eb886a7048354ad0a634cc8a426 [art] => https://radio.aimusicradio.org/api/station/ai_music_radio_-_testing/art/5df7b7dcf3d6d3f7e0570a2c-1722717467.jpg [custom_fields] => stdClass Object ( [tst] => b ) [text] => TimeWisely - Burger Groove [artist] => TimeWisely [title] => Burger Groove [album] => [genre] => house, French house, electronic, dance, disco [isrc] => [lyrics] => ) ) [2] => stdClass Object ( [request_id] => 518d4f64f1d5282144c0706c [request_url] => /api/station/6/request/518d4f64f1d5282144c0706c [song] => stdClass Object ( [id] => 8298cf1d456fb248dc29a56f1d044269 [art] => https://radio.aimusicradio.org/api/station/ai_music_radio_-_testing/art/518d4f64f1d5282144c0706c-1722717465.jpg [custom_fields] => stdClass Object ( [tst] => c ) [text] => TimeWisely - Dollar Blues [artist] => TimeWisely [title] => Dollar Blues [album] => [genre] => blues slow soulful [isrc] => [lyrics] => ) ) [3] => stdClass Object ( [request_id] => 9ce2f343566143ec6fea57c5 [request_url] => /api/station/6/request/9ce2f343566143ec6fea57c5 [song] => stdClass Object ( [id] => a96693ac204cd17e06aad5e80f1ab966 [art] => https://radio.aimusicradio.org/api/station/ai_music_radio_-_testing/art/9ce2f343566143ec6fea57c5-1722717464.jpg [custom_fields] => stdClass Object ( [tst] => d ) [text] => TimeWisely - Just Okay V2 [artist] => TimeWisely [title] => Just Okay V2 [album] => [genre] => country acoustic melodic [isrc] => [lyrics] => ) ) [4] => stdClass Object ( [request_id] => c32523e31f6ef9d3bec0dab4 [request_url] => /api/station/6/request/c32523e31f6ef9d3bec0dab4 [song] => stdClass Object ( [id] => c8c36840d319e47ec02d64141e65b01e [art] => https://radio.aimusicradio.org/api/station/ai_music_radio_-_testing/art/c32523e31f6ef9d3bec0dab4-1722717462.jpg [custom_fields] => stdClass Object ( [tst] => e ) [text] => TimeWisely - Lost in the Memes V2 [artist] => TimeWisely [title] => Lost in the Memes V2 [album] => [genre] => pop electronic [isrc] => [lyrics] => ) ) [5] => stdClass Object ( [request_id] => 78fbbfc4062020e1eed14826 [request_url] => /api/station/6/request/78fbbfc4062020e1eed14826 [song] => stdClass Object ( [id] => 14c7ead3cb1c0d5ffa1467e0b9c3d08a [art] => https://radio.aimusicradio.org/api/station/ai_music_radio_-_testing/art/78fbbfc4062020e1eed14826-1722717460.jpg [custom_fields] => stdClass Object ( [tst] => f ) [text] => TimeWisely - Roadside Blues [artist] => TimeWisely [title] => Roadside Blues [album] => [genre] => country [isrc] => [lyrics] => ) ) [6] => stdClass Object ( [request_id] => db59378e43d4d615f3f0e7d7 [request_url] => /api/station/6/request/db59378e43d4d615f3f0e7d7 [song] => stdClass Object ( [id] => 8dd4b801c9fcdf9b666a2014382f7364 [art] => https://radio.aimusicradio.org/api/station/ai_music_radio_-_testing/art/db59378e43d4d615f3f0e7d7-1722717458.jpg [custom_fields] => stdClass Object ( [tst] => g ) [text] => TimeWisely - Why is Dave So Grey? [artist] => TimeWisely [title] => Why is Dave So Grey? [album] => [genre] => pop mellow soulful [isrc] => [lyrics] => ) ) [7] => stdClass Object ( [request_id] => 36845895c7c697b354a0a319 [request_url] => /api/station/6/request/36845895c7c697b354a0a319 [song] => stdClass Object ( [id] => b0b85642177902b62d113ef970ed7e2c [art] => https://radio.aimusicradio.org/api/station/ai_music_radio_-_testing/art/36845895c7c697b354a0a319-1722717457.jpg [custom_fields] => stdClass Object ( [tst] => h ) [text] => TimeWisely - Why So Sad Pepe? V2 [artist] => TimeWisely [title] => Why So Sad Pepe? V2 [album] => [genre] => soft pop ballad melancholic [isrc] => [lyrics] => ) ) ) [1] => \AzuraCast\Model\ApiStationRequest[] [2] => Array ( ) ) ) [4] => Array ( [file] => D:\Documents\Web Testing\azuracast_api_test\vendor\lexiandev\azuracast-php-api-client\lib\Api\StationsSongRequestsApi.php [line] => 140 [function] => getRequestableSongsWithHttpInfo [class] => AzuraCast\Api\StationsSongRequestsApi [type] => -> [args] => Array ( [0] => ai_music_radio_-_testing [1] => application/json ) ) [5] => Array ( [file] => D:\Documents\Web Testing\azuracast_api_test\public\index.php [line] => 17 [function] => getRequestableSongs [class] => AzuraCast\Api\StationsSongRequestsApi [type] => -> [args] => Array ( [0] => ai_music_radio_-_testing ) ) ) [previous:Exception:private] => ) 
```

**Comment by Vaalyn** [comment]
> Here is the output for the getRequestableSongs()

That looks like it could also be defined as `type: object` with `additionalProperties: true` in the OA definition to make it work:
```php
#[OA\Property(
    type: 'object',
    additionalProperties: true
)]
public array $custom_fields = [];
```

This will basically happen for all dictionary like arrays due to the json decoding in the generated lib.

**Comment by Lexian-droid** [comment]
> > Here is the output for the getRequestableSongs()
> 
> That looks like it could also be defined as `type: object` with `additionalProperties: true` in the OA definition to make it work:
> 
> ```
> #[OA\Property(
>     type: 'object',
>     additionalProperties: true
> )]
> public array $custom_fields = [];
> ```
> 
> This will basically happen for all dictionary like arrays due to the json decoding in the generated lib.

Thanks for your help, I think it's good now, that error is indeed gone, only issue I can see happening is on the off chance the client starts flagging legitimate error 500s as simple "Song can't be requested" errors. Do you know if there's any other way to handle that?

Also, should the updates made to my instance be PR'd to the main repository? or no

**Comment by Vaalyn** [comment]
> Thanks for your help, I think it's good now, that error is indeed gone, only issue I can see happening is on the off chance the client starts flagging legitimate error 500s as simple "Song can't be requested" errors. Do you know if there's any other way to handle that?

The only way that I'd say makes sense would be to update the code generator to allow supplying additional options for the Guzzle HTTP client that the generated code constructs. That way it would be possible to supply the needed `'http_errors' => false` option. Or to update the code generator to discern that specific codes are expected for an endpoint and automatically set this option. The first one would be simpler to do I think.

> Also, should the updates made to my instance be PR'd to the main repository? or no

I'd say yes, would make sense to me to upstream those adjustments with a reference to this thread in the PR 👍
