### ISSUE TITLE
Moving audio files

### ISSUE THREAD

**Issue by aljaxus** [AzuraCast/AzuraCast#740]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to move music files in `/stations/ID/files`

**Describe the solution you'd like**
To be able to move files by dragging them

**Describe alternatives you've considered**
An alternative solution would be a separate menu / popup / modal that would open, instead of being able to simply drag the file

**Comment by LazosPlaying** [comment]
// talking about moving them into / out of folders

**Comment by tropimega** [comment]
no puedo agregar mas musica, a que se debe, espero respuestas gracias

**Comment by aljaxus** [comment]
> no puedo agregar mas musica, a que se debe, espero respuestas gracias

what ?
