### ISSUE TITLE
Two jingles played

### ISSUE THREAD

**Issue by LuukdeKing** [AzuraCast/AzuraCast#7403]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.20.2 Stable

### What happened?

I have this issue where while playing jingles it all of a sudden plays two jingles instead of one, idk if thats just my settings or if it's a bug.

**Comment by RM-FM** [comment]
Are those quite short jingles? There are still some issues related to such in Liquidsoap `2.2.5` - at least when not using Autocue. However, this should have been finally resolved in upcoming LS `2.3.0`. Azuracast related discussion and early testing status can be followed here: https://github.com/AzuraCast/AzuraCast/discussions/7354

**Comment by t0mtaylor** [comment]
you should delete the docker volumes and follow the details as per this comment https://github.com/AzuraCast/AzuraCast/issues/7162#issuecomment-2143803893
