### ISSUE TITLE
Toggle playlist "enabled" state

### ISSUE THREAD

**Issue by aljaxus** [AzuraCast/AzuraCast#741]
**Is your feature request related to a problem? Please describe.**
Add a switch to enable / disable playlist(-s) in main playlists table menu

**Describe the solution you'd like**
You could use the "bootstrap switch" (since it is not included in bootstrap itself) [bootstrapswitch.site](http://bootstrapswitch.site/examples.html) or [bootstraptoggle.com](http://www.bootstraptoggle.com)

**Describe alternatives you've considered**
If not the switch (which looks neat), the "[radio toggle](http://getbootstrap.com/docs/4.1/components/forms/#checkboxes-and-radios)" input could be also used

**Additional context**
![image](https://user-images.githubusercontent.com/24414483/44465639-6f387200-a61e-11e8-8e28-2f4428b9c2f5.png)

**Comment by SlvrEagle23** [comment]
This is implemented in the latest rolling update.
