### ISSUE TITLE
jingles don't play after update

### ISSUE THREAD

**Issue by DAMaia1989** [AzuraCast/AzuraCast#7414]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #167a59e (2024-08-28 14:00)

### What happened?

Since the last updates yesterday, the jingles have not played. I have a sequence so that a jingle plays for each song and it never plays. Is anyone else like this?

**Comment by t0mtaylor** [comment]
Sometimes you have to delete some of the docker volumes so they can rebuilt after an update (or switch between stable and rolling release) - the update script doesnt do this for you yet

try and follow the details as per this comment then restart azuracast https://github.com/AzuraCast/AzuraCast/issues/7162#issuecomment-2143803893

**Comment by caturria** [comment]
Hi @DAMaia1989,

The scheduler is being actively worked on at the moment.

If you are still experiencing this, could you please share your playlist configuration so I can try to reproduce it?
Thanks.

**Comment by DAMaia1989** [comment]
Hi @caturria ,
i've updated and now is working fine. Thanks so much!
