### ISSUE TITLE
Maximum bitrate stuck at 128kbps

### ISSUE THREAD

**Issue by ryanginn** [AzuraCast/AzuraCast#7416]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #167a59e

### What happened?

Trying to make mount point 320kbps, but only seeing options up to 128. Trying to manually put in 320 shows you 32kbps!

![image](https://github.com/user-attachments/assets/50d9d84c-ff05-458c-91d1-f2586bf6d0d7)

**Comment by Vaalyn** [comment]
Check if your admin or hoster has set your stations maximum bitrate to 128 under `Edit Station Profile` -> `Administration`:

![image](https://github.com/user-attachments/assets/4d8add3e-293c-4b5c-8e1c-fb6230c84692)

By default this value is set to `0` which means "unlimited".

**Comment by ryanginn** [comment]
Thank you, never saw this! Must be a new thing ;)
