### ISSUE TITLE
Mountpoint - no setting for 320 kbit stream

### ISSUE THREAD

**Issue by RadioCuxhaven** [AzuraCast/AzuraCast#7420]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

Rolling Release #6ac9447 (2024-08-29 9:13)

### What happened?

There is no option to create a 320 kbit stream. It only works up to 128 kbit.

192, 256 and 320 kbit are missing

![Unbenannt - 1](https://github.com/user-attachments/assets/0b3461dc-d45b-4ea4-a812-8fe125e95f9d)

**Comment by RM-FM** [comment]
@RadioCuxhaven did you check this... https://github.com/AzuraCast/AzuraCast/issues/7416 ?

**Comment by RadioCuxhaven** [comment]
ohhh, thank you. I didn't find that at all. But is it new or do you have to set it that way now?

**Comment by Vaalyn** [comment]
This is a relatively new feature but the migration that adds these settings explicitly sets it to 0 (unlimited) by default for existing stations and when creating new stations it also defaults to 0.


As far as I'm aware this has to have been set to a limit manually.

**Comment by RadioCuxhaven** [comment]
new installation

**Comment by Vaalyn** [comment]
Found and prepared a fix for an incorrect value in the used model of the respective station form vue component 👍
