### ISSUE TITLE
Remote server statistic tracking

### ISSUE THREAD

**Issue by JDBlackman** [AzuraCast/AzuraCast#743]
On my current radio setup it includes a main server and three "relays". Currently it I have created my own statistics panel to track listeners and song history. I would love if i could add my external radio servers (which run icecast) to the Azura panel to be able to get the great statistics that azura have to offer.

I have tried adding a remote server and connecting it to the mountpoint of the relay on the external icecast server but it still doesn't track the listeners. 

I wonder if this is functionality is planned or currently doable. It would just be great to use the statistical features of Azura on my remote servers. 

or even better the option for azura to setup an external server as a relay.

**Comment by SlvrEagle23** [comment]
@JDBlackman Support for remote relays has been fully implemented! Now, from the same station inside AzuraCast, you can both broadcast locally and/or view statistics from (or also broadcast to) remote relays. The "Remote Relays" menu item is now visible on the left side of the station's menu, replacing the previous method of doing this, where you had to select whether you wanted to broadcast locally or broadcast/syndicate remotely.
