### ISSUE TITLE
Where are the Azuracast files located on docker ?

### ISSUE THREAD

**Issue by JustIrinel** [AzuraCast/AzuraCast#744]
Hi,

For optimizing my website, I need to find the Azuracast files and activate a GZIP compression and some minify :) . Where do I find them ? I installed with DOCKER.

Also, sometimes, the players stop from singing without pressing any stop button. Someone have any ideea how to fix it ?

**Comment by SlvrEagle23** [comment]
@JustIrinel If you're using Docker, the files are inside the Docker container itself, and aren't intended to be modified directly. The build process does a fair amount of compression of the files, which are then assigned a unique path for cache-busting purposes, so they can be cached basically indefinitely.

The other issue is unrelated to the first one, and I'll likely need more information on what's happening behind the scenes when the song playback stops, i.e. logs from the Docker container if any exist.
