### ISSUE TITLE
Found track that avoids duplicate title and artist

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#7450]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release installed on 10 Sept

### What happened?

Ok so basically here is what i found. There are some tracks stuck in the queue. In my case two.

They were declined to play because of repeating, which is good (which is how i set it)

This is the error log that it gives me:
```
[2024-09-17T11:21:34.204671+00:00] AzuraCast.INFO: Found track that avoids duplicate title and artist. {"media_id":28521,"title":"So Much Joy (Alaia & Gallo Extended Remix)","artist":"Ann Nesby"} {"station":{"id":1,"name":"AzuraCast Radio"}}
[2024-09-17T11:21:34.208180+00:00] AzuraCast.INFO: Playable track(s) found and registered. {"next_song":"StationMedia 28521: Ann Nesby - So Much Joy (Alaia & Gallo Extended Remix)"} {"station":{"id":1,"name":"AzuraCast Radio"}}
```

So far good, BUT, the track is not deleted from mysql, and still stays in the queue and waiting.
And it's stay on the next position, which means, it shows at "play next" track, which is actually not true.
I mark it as played, but it blocked the queue list... The tracks stayed probably so much long, that they already played but didn't been marked as played.... Ot Liquidsoap just plays some random songs until the time to play that blocked track can play. I'm not sure whats really happening yet, but i will do more investigation.

**Comment by NicoxDJ** [comment]
Actually I misread the log. But it acts like its duplicated.
As i hit the play next button, some times it try to plays it, and about 10-15 seconds after the track plays, liquidsoap stops it and starts the next one. After few "play next" button hits it starts again and again is skipped.
And the next track is picked randomly by Liquidsoap, because it isn't in the AzuraCasts Queue list.

**Comment by caturria** [comment]
Do you have playlists with the 'interrupt other tracks' setting on? If so, these are currently handled by Liquidsoap directly and do not work properly.
