### ISSUE TITLE
Warning 4: Unused variable file_metadata

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#7455]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #2858f6a (2024-09-18 6:36) 

### What happened?

Azuracast is running fine, but i found a warning in LS Logs when restarting LS. So i thought i report it just in case it could be causing an error.

### Relevant log output

```shell
2024/09/19 17:10:42 >>> LOG END
At /var/azuracast/liquidsoap/azuracast.liq, line 65 char 28 - line 96 char 3:
# AzuraCast AutoCue Provider
def azuracast_autocue(
...
    end
end

Warning 4: Unused variable file_metadata
At /var/azuracast/liquidsoap/azuracast.liq, line 65 char 28 - line 96 char 3:
# AzuraCast AutoCue Provider
def azuracast_autocue(
...
    end
end

Warning 4: Unused variable filename
2024/09/19 17:10:52 >>> LOG START
```

**Comment by BusterNeece** [comment]
Fixed in newer Rolling Releases.
