### ISSUE TITLE
AutoCue feature limits volume to 50% on Shoutcast

### ISSUE THREAD

**Issue by Lokke** [AzuraCast/AzuraCast#7458]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

v0.20.2 Stable

### What happened?

When using the "AutoCue" feature with Shoutcast (I have not tested this with Icecast yet), I am experiencing an issue where the volume is automatically limited to 50%. This happens consistently while AutoCue is enabled.

**Steps to Reproduce:**
- Set up a Shoutcast stream.
- Enable the "AutoCue" feature.
- Observe the volume levels during playback.

Expected Behavior: The volume should remain at its original level and not be reduced.

Actual Behavior: The volume is reduced to 50% automatically.

Additional Context: I have only tested this with Shoutcast, so it's unclear if the issue also occurs with Icecast.

Let me know if you need any further information or logs!

**Comment by gAlleb** [comment]
Hi @Lokke!

Are you sure it does limit by 50%?

When you enable autocue - it changes LUFS target to -18, so all of your tracks get amplified to meet this. If you have some kind of master_me enabled - it can play a role too.

You can check your stream loudness in Audacity or `audiometer.py` (https://github.com/Warblefly/audiometer).

Also you can change LUFS target to whatever you want via autocue settings `settings.autocue.cue_file.target := -18.0`.

**Comment by RM-FM** [comment]
@Lokke you could try to set `settings.autocue.amplify_behavior := "ignore"` in the 2nd box of the Liquidsoap Configuration. This should prevent Autocue from applying the loudness correction.

**Comment by gAlleb** [comment]
Would `settings.autocue.amplify_behavior := "ignore"` work with `cue_file` autocue, which is used above?

**Comment by RM-FM** [comment]
> Would `settings.autocue.amplify_behavior := "ignore"` work with `cue_file` autocue, which is used above?

Yes, it should as it is a setting of Liquidsoap Autocue API that is used by all Autocue integration.
