### ISSUE TITLE
Error updating AzuraCast using docker.sh script

### ISSUE THREAD

**Issue by lamasbr** [AzuraCast/AzuraCast#746]
**Installation method:** Docker
**Host OS (for Docker installations):** Ubuntu 16.04.4 LTS

**Describe the bug**
Update AzureCast using ./docker.sh update command shows '"docker rmi" requires at least 1 argument' after recreate the containers.

**To Reproduce**
1. Login on ssh
2. Change to docker.sh directory
3. Execute `./docker update` (using Y option to update docker-compose.yml)

**Expected behavior**
Cleanup unused AzuraCast docker images after successfully update.

**Screenshots**
![image](https://user-images.githubusercontent.com/668513/44613498-98a5f900-a7ea-11e8-8782-6144cdaaa4fd.png)

**Comment by SlvrEagle23** [comment]
@lamasbr The updating script returns the raw output of some underlying commands, and some of those look like errors even though they really aren't. In this case, if Docker has no spare images to remove, that's okay, it doesn't mean the update necessarily failed. As long as your AzuraCast instance is up and running, you're doing fine.
