### ISSUE TITLE
Redis db index is awlays 0, environment variable REDIS_DB has no effect

### ISSUE THREAD

**Issue by StoneEngineer** [AzuraCast/AzuraCast#7469]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Docker Compose environment variable REDIS_DB has no effect. Redis DB index is always 0 since REDIS_DB is not considered in code:
```
{{ if isTrue .Env.ENABLE_REDIS }}
engine = "redis"
redis_address = "{{ .Env.REDIS_HOST }}:{{ default .Env.REDIS_PORT "6379" }}"
redis_db = 0
{{ end }}
```
shall be:
`redis_db = {{ default .Env.REDIS_DB 0 }}`

**Comment by BusterNeece** [comment]
I'm a little torn on this one. On the one hand, we removed the internal references to the database index, as Redis themselves have said that this feature is "vestigial" to older versions of the cache and that it is no longer recommended to use any DB other than the default, and to instead rely on prefixing to separate "namespaces" in the cache (which we already do). On the other hand, if you're referring to external Redis DBs, it may be useful to compartmentalize AzuraCast into its own DB. I'll give this some thought and report back.
