### ISSUE TITLE
Restart doesn't work

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#747]
**Installation method**
Traditional

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
The menubutton restart doesn't restart AzuraCast. The text remains please wait...

**Screenshots**
![image](https://user-images.githubusercontent.com/29834979/44619302-6ba62480-a884-11e8-8223-530536c87505.png)

**Additional context**
I updated last week to the latest version of AzuraCast.

**Comment by SlvrEagle23** [comment]
@RemBdev Please update to the very newest version of AzuraCast released today, as there has been a fix that will help with logging errors from API calls in the console. Then, try to restart while watching the log file via `tail -f /var/azuracast/www_tmp/azuracast.log`. Let me know if it yields any useful error messages.

**Comment by RemBdev** [comment]
@SlvrEagle23 I updated today, the fail you said is not containing an new error.

**Comment by tehcojam** [comment]
@RemBdev 

> Is there a posibility to restart azuracast via SSH?

On traditional: `php /var/azuracast/www/util/cli.php azuracast:radio:restart`
On docker: `docker-compose run --rm cli azuracast_cli azuracast:radio:restart`

http://www.azuracast.com/cli.html - more info
