### ISSUE TITLE
Sender offline although everything is online

### ISSUE THREAD

**Issue by BenMauriceKeil** [AzuraCast/AzuraCast#7472]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#a903c64 (2024-09-26 10:21) • Docker • PHP 8.3

### What happened?

Hello, I installed the update today and since then nothing has worked anymore, it shows Station Offline in the dashboard and all the stream links that are stored are invalid. I have restarted the station several times and reloaded the configuration and also restarted the entire server once, unfortunately no change.

**Comment by BusterNeece** [comment]
@BenMauriceKeil When you look at your station profile page, do you see the backend and frontend both as "Running"? If one isn't running (it's likely the backend, Liquidsoap), then it would be helpful if you could check the Liquidsoap logs (from the "Logs" sidebar menu item) and let me know what they say.

**Comment by BenMauriceKeil** [comment]
![Screenshot_20240926_224411_Opera](https://github.com/user-attachments/assets/0ce0d23d-ba92-4d5c-8ade-9d23fe3839eb)

Unfortunately I don't know how to send you the complete log, I copied it but I can't paste it here

**Comment by BusterNeece** [comment]
@BenMauriceKeil Can you just copy the bottom-most lines where it shows the error message?

Also, are you using any custom Liquidsoap code? That may be affected.

**Comment by BenMauriceKeil** [comment]
I am not using any custom code and it looks like there is no error message displayed
![Screenshot_20240927_002837_Opera](https://github.com/user-attachments/assets/3a25001d-71a0-4e19-9bf9-8abf2b01bf0c)

**Comment by BenMauriceKeil** [comment]
I have now installed the latest updates and it still doesn't work at all

**Comment by BenMauriceKeil** [comment]
@BusterNeece

**Comment by BusterNeece** [comment]
@BenMauriceKeil I realize you're having trouble with your installation, but please don't tag me directly. I am quite busy these days and will get to issues as time, energy and health permit.

**Comment by BenMauriceKeil** [comment]
I had waited several days and only then marked it because there was no response, so it wasn't direct, it doesn't matter either, it's the Strato server, I got another server from another provider and everything works there without any problems

**Comment by BusterNeece** [comment]
@BenMauriceKeil I realize it had been a while without a response, but we do not guarantee any response time as part of our community-based support. You are not entitled to a prioritized bit of my time just because I make and give away a piece of software you use.

**Comment by BenMauriceKeil** [comment]
I know that, I didn't say that

**Comment by LordHelmchen666** [comment]
@BenMauriceKeil You did not gave the informations Buster asked you for. And you really thinking he can help you? i don't think he is a clairvoyant.

**Comment by BenMauriceKeil** [comment]
I gave the information I had and no error was displayed
