### ISSUE TITLE
Modals not working on embed widgets

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#7473]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #2ac0aa8 (2024-09-27 10:16) 

### What happened?

The modals (popups) on embed widgets not working. When clicking on Albumart it just opens new browser tab instead. Podcast is the only embed widget working correctly. https://demo.azuracast.com/public/azuratest_radio/podcasts?embed=true
they are not working

- https://demo.azuracast.com/public/azuratest_radio/embed?theme=light
- https://demo.azuracast.com/public/azuratest_radio/history?theme=light
- https://demo.azuracast.com/public/azuratest_radio/embed-requests?theme=light

I tried to find reason why, but no errors and so i am not able to catch.

**Comment by BusterNeece** [comment]
@LordHelmchen666 This is actually by design; because the size of embeds varies so wildly, we can't guarantee that there will be enough screen real estate to make the enlarged thumbnail modal useful, so instead we have it open in a new window.

**Comment by LordHelmchen666** [comment]
I understand. But shouldn't it then also be removed from the Podcasts embed widget?
