### ISSUE TITLE
How Use Stereo Tool Command line version with AzuraCast

### ISSUE THREAD

**Issue by Developpeur** [AzuraCast/AzuraCast#749]
How use Stereo Tool (Command line version) before going on icecast ?
I tried http://forums.stereotool.com/viewtopic.php?t=13224 and : 
```
# Input to Processing
input = radio

# Processing
process = mksafe(pipe(process='/stereo_tool_cmd_64 - - -s /mySettings.sts -q -k "<STEREO_TOOL_LICENSE>", input))

# Processing to Output
output = process
```
but without success

**Comment by SlvrEagle23** [comment]
@Developpeur It should be possible to do:

```
radio = mksafe(pipe(process='/stereo_tool_cmd_64 - - -s /mySettings.sts -q -k "<STEREO_TOOL_LICENSE>", radio))
```

**Comment by Developpeur** [comment]
@SlvrEagle23 I tried, the station does not restart. I think he does not find _stereo_tool_cmd_64_

**Comment by SlvrEagle23** [comment]
@Developpeur What installation method are you using? Traditional or Docker? If you're using Docker, you'll have to add the path to the stereo_tool executable as a volume onto the `stations` container in your `docker-compose.yml`, i.e.:

```yaml
    volumes:
      - "/path/on/host/stereo_tool:/stereo_tool"
```

**Comment by Developpeur** [comment]
@SlvrEagle23 Should I put stereo_tool or stereo_tool_cmd_64 ?
![capture](https://user-images.githubusercontent.com/13254045/44627647-913d3780-a931-11e8-9b08-34f4d88763d9.PNG)

**Comment by SlvrEagle23** [comment]
@Developpeur Whatever the actual path to the file is. Think of it as a symlink into the Docker container; whatever's on the right side of the ":" is how you'll reference it inside the container, and whatever's on the left is where it is on the host.

**Comment by anjeleno** [comment]
@SlvrEagle23 

Incredible work on Azuracast!!! Quality product with a super clean UI. Thank you!!!

Same situation as @Developpeur, haven't quite figured out the proper syntax (even with your examples) and can't get Liquidsoap to reload. It kills the station. Working with the Docker Installation.

Pasted the following in the profile/Advanced: Custom Configuration section with my actual license key 
```
# Input to Processing
input = radio

# Processing
radio = mksafe(pipe(process='/stereo_tool_cmd_64 - - -s /1.sts -q -k "<************>", radio))

# Processing to Output
output = process
```


And added "- /var/azuracast/stereo_tool:/stereo_tool" to docker-compose.yml

Both stereo_tool_cmd_64 and 1.sts are in the working /var/azuracast host directory and stereo_tool_cmd_64 is executable. 

I've tried "- /var/azuracast/stereo_tool:/stereo_tool" with and without quotes and also - /var/azuracast/stereo_tool_cmd_64:/stereo_tool_cmd_64. but still get the following: "SPAWN_ERROR: station_1:station_1_backend." Even tried adding a path to 1.sts in docker-compose.yml...

 Any idea what I'm doing wrong? 

Thank you!!

![screenshot from 2018-08-26 05 33 25](https://user-images.githubusercontent.com/42714619/44628299-bd38c880-a8f1-11e8-8ee8-9fff7dc46bb5.png)

**Comment by anjeleno** [comment]
@SlvrEagle23 

I should also mention that I've tried reversing the order of the info in the path. 

I think I had the path reversed in the previous screen cap.

![screenshot from 2018-08-26 06 08 55](https://user-images.githubusercontent.com/42714619/44628568-f58ed580-a8f6-11e8-864c-b220b344de5a.png)

**Comment by anjeleno** [comment]
@Developpeur Any luck getting it to work?

**Comment by anjeleno** [comment]
@Developpeur Thanks for the update. Did you manage to get it working?

I should have mentioned that I've tried it both ways, including all of those lines and dropping all except for "radio = mksafe..." 

Here's the output of the docker-compose logs -f stations:

stations_1     | 2018-08-26 20:46:48,451 INFO waiting for station_1_frontend to stop
stations_1     | 2018-08-26 20:46:49,438 INFO stopped: station_1_frontend (exit status 0)
stations_1     | 2018-08-26 20:46:49,440 INFO stopped: station_1_watcher (terminated by SIGTERM)
stations_1     | 2018-08-26 20:46:49,443 INFO spawned: 'station_1_frontend' with pid 118
stations_1     | 2018-08-26 20:46:50,445 INFO success: station_1_frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
stations_1     | 2018-08-26 20:46:50,449 INFO spawned: 'station_1_watcher' with pid 122
stations_1     | 2018/08/26 20:46:50 main.go:90: Change in content: triggering web hook
stations_1     | 2018-08-26 20:46:51,523 INFO success: station_1_watcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
stations_1     | 2018-08-26 20:46:51,527 INFO spawned: 'station_1_backend' with pid 126
stations_1     | Line 70, char 29: Empty token!
stations_1     | 2018-08-26 20:46:51,598 INFO exited: station_1_backend (exit status 1; not expected)
stations_1     | 2018-08-26 20:46:52,601 INFO spawned: 'station_1_backend' with pid 127
stations_1     | Line 70, char 29: Empty token!
stations_1     | 2018-08-26 20:46:52,677 INFO exited: station_1_backend (exit status 1; not expected)
stations_1     | 2018-08-26 20:46:54,688 INFO spawned: 'station_1_backend' with pid 128
stations_1     | Line 70, char 29: Empty token!
stations_1     | 2018-08-26 20:46:54,762 INFO exited: station_1_backend (exit status 1; not expected)
stations_1     | 2018-08-26 20:46:58,348 INFO spawned: 'station_1_backend' with pid 129
stations_1     | Line 70, char 29: Empty token!
stations_1     | 2018-08-26 20:46:58,425 INFO exited: station_1_backend (exit status 1; not expected)
stations_1     | 2018-08-26 20:46:59,426 INFO gave up: station_1_backend entered FATAL state, too many start retries too quickly
stations_1     | 2018-08-26 20:47:05,160 INFO waiting for station_1_frontend to stop
stations_1     | 2018-08-26 20:47:05,467 INFO stopped: station_1_frontend (exit status 0)
stations_1     | 2018-08-26 20:47:05,470 INFO stopped: station_1_watcher (terminated by SIGTERM)
stations_1     | 2018-08-26 20:47:05,472 INFO spawned: 'station_1_frontend' with pid 130
stations_1     | 2018-08-26 20:47:06,474 INFO success: station_1_frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
stations_1     | 2018-08-26 20:47:06,478 INFO spawned: 'station_1_watcher' with pid 134
stations_1     | 2018/08/26 20:47:06 main.go:90: Change in content: triggering web hook
stations_1     | 2018-08-26 20:47:07,545 INFO success: station_1_watcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
stations_1     | 2018-08-26 20:47:07,549 INFO spawned: 'station_1_backend' with pid 138
stations_1     | Line 70, char 29: Empty token!
stations_1     | 2018-08-26 20:47:07,622 INFO exited: station_1_backend (exit status 1; not expected)
stations_1     | 2018-08-26 20:47:08,624 INFO spawned: 'station_1_backend' with pid 139
stations_1     | Line 70, char 29: Empty token!
stations_1     | 2018-08-26 20:47:08,707 INFO exited: station_1_backend (exit status 1; not expected)
stations_1     | 2018-08-26 20:47:10,718 INFO spawned: 'station_1_backend' with pid 140
stations_1     | Line 70, char 29: Empty token!
stations_1     | 2018-08-26 20:47:10,801 INFO exited: station_1_backend (exit status 1; not expected)
stations_1     | 2018-08-26 20:47:13,806 INFO spawned: 'station_1_backend' with pid 141
stations_1     | Line 70, char 29: Empty token!
stations_1     | 2018-08-26 20:47:13,896 INFO exited: station_1_backend (exit status 1; not expected)
stations_1     | 2018-08-26 20:47:14,900 INFO gave up: station_1_backend entered FATAL state, too many start retries too quickly

**Comment by anjeleno** [comment]
Thanks for the clarification @SlvrEagle23.

I should have mentioned that I've tried it both ways, including all of those lines and dropping all except for "radio = mksafe..."

Getting an odd connection error. I think I'm going to spin up a new droplet/docker and report what happens. 

Here's the output of the docker-compose logs -f stations:
stations_1     | 2018-08-26 21:11:48,592 INFO waiting for station_1_frontend to stop
stations_1     | 2018-08-26 21:11:49,466 INFO stopped: station_1_frontend (exit status 0)
stations_1     | 2018/08/26 21:11:49 main.go:54: Connnection error for uri <http://admin:MF4zHc3j@localhost:8000/admin/stats> Get http://admin:MF4zHc3j@localhost:8000/admin/stats: read tcp 127.0.0.1:55112->127.0.0.1:8000: read: connection reset by peer
stations_1     | 2018-08-26 21:11:49,473 INFO stopped: station_1_watcher (terminated by SIGTERM)
stations_1     | 2018-08-26 21:11:49,478 INFO spawned: 'station_1_frontend' with pid 69
stations_1     | 2018-08-26 21:11:50,483 INFO success: station_1_frontend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
stations_1     | 2018-08-26 21:11:50,489 INFO spawned: 'station_1_watcher' with pid 73
stations_1     | 2018/08/26 21:11:50 main.go:90: Change in content: triggering web hook
stations_1     | 2018-08-26 21:11:51,584 INFO success: station_1_watcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
stations_1     | 2018-08-26 21:11:51,590 INFO spawned: 'station_1_backend' with pid 77
stations_1     | Line 70, char 29: Empty token!
stations_1     | 2018-08-26 21:11:51,670 INFO exited: station_1_backend (exit status 1; not expected)
stations_1     | 2018-08-26 21:11:52,675 INFO spawned: 'station_1_backend' with pid 78
stations_1     | Line 70, char 29: Empty token!
stations_1     | 2018-08-26 21:11:52,763 INFO exited: station_1_backend (exit status 1; not expected)
stations_1     | 2018-08-26 21:11:54,776 INFO spawned: 'station_1_backend' with pid 79
stations_1     | Line 70, char 29: Empty token!
stations_1     | 2018-08-26 21:11:54,865 INFO exited: station_1_backend (exit status 1; not expected)
stations_1     | 2018-08-26 21:11:57,873 INFO spawned: 'station_1_backend' with pid 80
stations_1     | Line 70, char 29: Empty token!
stations_1     | 2018-08-26 21:11:57,963 INFO exited: station_1_backend (exit status 1; not expected)
stations_1     | 2018-08-26 21:11:58,964 INFO gave up: station_1_backend entered FATAL state, too many start retries too quickly

**Comment by SlvrEagle23** [comment]
@Developpeur @anjeleno In case you all haven't noticed this, I just realized there's a missing single quote in the original, and it should actually be:

```
radio = mksafe(pipe(process='/stereo_tool_cmd_64 - - -s /1.sts -q -k "<************>"', radio))
```

**Comment by anjeleno** [comment]
@SlvrEagle23 Thank you! missing single quote noted and fixed. Just finished spinning up a new droplet... I'll let you know what happens :-)

**Comment by anjeleno** [comment]
@SlvrEagle23 Making progress! Liquidsoap starts now, and I can connect to the stream in VLC, but there's no audio at all...

Added the single missing quote, renamed stereotool so there's no confusion on filename/path and updated the path as follows:
![screenshot from 2018-08-26 14 42 03](https://user-images.githubusercontent.com/42714619/44633307-8341e380-a93e-11e8-8964-aa6d4b70469f.png)

**Comment by anjeleno** [comment]
@SlvrEagle23 Also, here's the most recent output from docker-compose logs -f stations:

stations_1     | 2018/08/26 21:39:09 >>> LOG START
stations_1     | 2018/08/26 21:39:09 [main:3] Liquidsoap 1.3.3
stations_1     | 2018/08/26 21:39:09 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.3.4 dtools=0.3.4 duppy=0.7.0 duppy.syntax=0.7.0 cry=0.6.0 mm=0.3.1 ogg=0.5.2 vorbis=0.7.0 opus=0.1.2 mad=0.4.5 flac=0.1.2 flac.ogg=0.1.2 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 taglib=0.3.3 camomile=0.8.6 faad=0.3.3
stations_1     | 2018/08/26 21:39:09 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
stations_1     | 2018/08/26 21:39:09 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
stations_1     | 2018/08/26 21:39:09 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
stations_1     | 2018/08/26 21:39:09 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
stations_1     | 2018/08/26 21:39:09 [threads:3] Created thread "generic queue #1".
stations_1     | 2018/08/26 21:39:09 [threads:3] Created thread "generic queue #2".
stations_1     | 2018/08/26 21:39:09 [threads:3] Created thread "non-blocking queue #1".
stations_1     | 2018/08/26 21:39:09 [threads:3] Created thread "non-blocking queue #2".
stations_1     | 2018/08/26 21:39:09 [harbor:3] Adding mountpoint '/' on port 8005
stations_1     | 2018/08/26 21:39:09 [playlist_default(dot)m3u:3] Loading playlist...
stations_1     | 2018/08/26 21:39:09 [playlist_default(dot)m3u:3] No mime type specified, trying autodetection.
stations_1     | 2018/08/26 21:39:09 [playlist_default(dot)m3u:3] Playlist treated as format application/x-mpegURL
stations_1     | 2018/08/26 21:39:09 [playlist_default(dot)m3u:3] Successfully loaded a playlist of 10 tracks.
stations_1     | 2018/08/26 21:39:09 [decoder:3] Method "WAV" accepted "/var/azuracast/stations/y_radio/media/10_djds_-_found_-28closing-29.wav".
stations_1     | 2018/08/26 21:39:09 [playlist_default(dot)m3u:3] Prepared "/var/azuracast/stations/y_radio/media/10_djds_-_found_-28closing-29.wav" (RID 1).
stations_1     | 2018/08/26 21:39:09 [live_switch:3] Switch to fallback_5909.
stations_1     | 2018/08/26 21:39:09 [fallback_5909:3] Switch to switch_5907.
stations_1     | 2018/08/26 21:39:09 [switch_5907:3] Switch to random_5897.
stations_1     | 2018/08/26 21:39:09 [random_5897:3] Switch to audio_to_stereo_5895.
stations_1     | 2018/08/26 21:39:09 [dummy:3] Source failed (no more tracks) stopping output...
stations_1     | 2018/08/26 21:39:09 [radio_out_1:3] Connecting mount /radio.mp3 for source@127.0.0.1...
stations_1     | 2018/08/26 21:39:09 [lang:3] AzuraCast Raw Response: annotate:title="no guarantees",artist="06 djds":/var/azuracast/stations/y_radio/media/06_djds_-_no_guarantees.wav
stations_1     | 2018/08/26 21:39:09 [decoder:3] Method "WAV" accepted "/var/azuracast/stations/y_radio/media/06_djds_-_no_guarantees.wav".
stations_1     | 2018/08/26 21:39:09 [radio_out_1:3] Connection setup was successful.
stations_1     | 2018/08/26 21:39:09 [threads:3] Created thread "wallclock_main" (1 total).
stations_1     | 2018/08/26 21:39:09 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
stations_1     | 2018/08/26 21:39:09 [mksafe:3] Switch to safe_blank.
stations_1     | 2018/08/26 21:39:10 main.go:90: Change in content: triggering web hook
stations_1     | 2018-08-26 21:39:10,026 INFO success: station_1_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
stations_1     | 2018/08/26 21:39:18 main.go:90: Change in content: triggering web hook
stations_1     | 2018/08/26 21:39:36 main.go:90: Change in content: triggering web hook
stations_1     | 2018/08/26 21:39:52 main.go:90: Change in content: triggering web hook

**Comment by SlvrEagle23** [comment]
@anjeleno This is likely because the software doesn't accept the type of file you're sending it; in this case, it looks like a WAV file.

In any case, none of this has anything to do with AzuraCast, as all issues are upstream to do with the Stereo Tool command or Liquidsoap itself. I'm closing the issue as the actual issue of Liquidsoap failing to launch is fixed. Feel free to talk amongst yourselves from here on, but I have no further contributions from the project end.

**Comment by anjeleno** [comment]
Understood. Thank you for all of your input @SlvrEagle23. Really appreciated!!!
