### ISSUE TITLE
Tiempo de salida al aire es muy demorado (18 segundos), como puedo mejorar ese tiempo?

### ISSUE THREAD

**Issue by jupapeto17** [AzuraCast/AzuraCast#751]
**Installation method**
"Docker"

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
El tiempo de salida en vivo usando MIXXX con ShoutCast, es muy demorado, una vez activo la transición es de 18 Segundos aproximadamente.

**Expected behavior**
Poder cambiar este tiempo a 3 o 5 segundos.
-

**Comment by SlvrEagle23** [comment]
@jupapeto17 Lo siento, pero el soporte para AzuraCast solo se proporciona en inglés. Por favor, traduzca cualquier pregunta al inglés.
