### ISSUE TITLE
how to remove Live Broadcasting

### ISSUE THREAD

**Issue by DAMaia1989** [AzuraCast/AzuraCast#7516]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #96623e4 (2024-10-17 20:54) • Docker • PHP 8.3

### What happened?

Hi there!
Could someone help me how to remove the message "Live Broadcasting" when live source is not sending metadata?

**Comment by RadioFlamingo** [comment]
Edit station profile --> (tab) Streamers/Dj's,--> change Default Live Broadcast Message

**Comment by DAMaia1989** [comment]
hi @RadioFlamingo thanks for answer. The problem is that if I leave the field blank it still returns live broadcasting. I really want to disable any type of message when live source is not sending metadata

**Comment by DAMaia1989** [comment]
hi @mdrxy I think css does not apply to what I want, in any case it would be some configuration in liquidsoap

**Comment by BusterNeece** [comment]
@DAMaia1989 In the newer Rolling Release versions, we've made it so you can manually override this value in the custom Liquidsoap configuration. On the second config block you can edit, you can add:

```
settings.azuracast.live_broadcast_text := ""
```

...and it will remove any string used for this.

**Comment by DAMaia1989** [comment]
hi @BusterNeece ! that was exactly what I needed. thank you very much!

By the way, how can I access to the other "settings.azuracast."? is there any file here?

**Comment by BusterNeece** [comment]
@DAMaia1989 our current settings are listed here: https://github.com/AzuraCast/AzuraCast/blob/3de190842679e098f28f780cde92eccd8c79d12c/util/docker/stations/liquidsoap/azuracast.liq#L31-L101

**Comment by DAMaia1989** [comment]
Thanks a lot!
