### ISSUE TITLE
Multi-selection editing in the file library

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#752]
When using large librairies, I would need to edit multiple files at once and change their values. (Crossfade period, etc...). Also it would be interessting to use a variable such as audio lenghth to fill automatically the field for each file. Example : the length of the audio file could be entered in the crosspoint_start field as %length when multiple-selecting.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39023/bulk-editing-of-multiple-music-files
