### ISSUE TITLE
Scheduled playlists not playing at all

### ISSUE THREAD

**Issue by Zentie13** [AzuraCast/AzuraCast#7525]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

A playlist scheduled for a specific time didn't start at the scheduled time. Changing the start time, still didn't get the playlist going. Please advise. We run through Asurahosting.

**Comment by wegGehamstert** [comment]
Hey, quick question, could you send a screenshot of the scheduled playlist?

**Comment by Zentie13** [comment]
Hi

I'm not sure how this is going to help. This is what I get, since going to playback queue shows nothing:

***@***.***

I am currently looking at radio.co and Live365, as AzuraCast and Asuahosting are surely disappointing.


Regards / Groete


Hein Zentgraf

0837745609


------ Original Message ------
From "Niklas H." ***@***.******@***.***>>
To "AzuraCast/AzuraCast" ***@***.******@***.***>>
Cc "Hein Zentgraf" ***@***.******@***.***>>; "Author" ***@***.******@***.***>>
Date 2024/11/6 18:48:30
Subject Re: [AzuraCast/AzuraCast] Scheduled playlists not playing at all (Issue #7525)


Hey, quick question, could you send a screenshot of the scheduled playlist?

**Comment by Zentie13** [comment]
BTW, suddenly it seems to be playing, but it freaks out so often, that I have temporarily reverted to RadioDJ - much more reliable.


Regards


Hein Zentgraf

0837745609


------ Original Message ------
From "Niklas H." ***@***.******@***.***>>
To "AzuraCast/AzuraCast" ***@***.******@***.***>>
Cc "Hein Zentgraf" ***@***.******@***.***>>; "Author" ***@***.******@***.***>>
Date 2024/11/6 18:48:30
Subject Re: [AzuraCast/AzuraCast] Scheduled playlists not playing at all (Issue #7525)


Hey, quick question, could you send a screenshot of the scheduled playlist?

**Comment by wegGehamstert** [comment]
Azuracast has its pro and cons. But it should work normally. 
If it work now, you can close this issue

**Comment by Zentie13** [comment]
I fully agree that AzuraCast has its issues, but it surely has more pros than cons. In principle the software is great. What I find not to be great, is that it is not consistent. I'm not sure if people play around with it for improvements or other functionality, but what works today, doesn't necessarily work tomorrow. Sometimes a week goes by without a hitch, then suddenly gremlins start creeping in. One day when that is sorted, I may come back or recommend it to someone, but for now I'll pass and use something more stable.

Issue closed.


Regards


Hein Zentgraf

0837745609


------ Original Message ------
From "Niklas H." ***@***.******@***.***>>
To "AzuraCast/AzuraCast" ***@***.******@***.***>>
Cc "Hein Zentgraf" ***@***.******@***.***>>; "Author" ***@***.******@***.***>>
Date 2024/11/10 21:53:05
Subject Re: [AzuraCast/AzuraCast] Scheduled playlists not playing at all (Issue #7525)


Azuracast has its pro and cons. But it should work normally.
If it work now, you can close this issue
