### ISSUE TITLE
Liquidsoap process taking a lot of CPU usage even with Auto DJ OFF

### ISSUE THREAD

**Issue by elvisn** [AzuraCast/AzuraCast#7528]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.20.2

### What happened?

I was investigating why my Ubuntu Azure VM was taking so much CPU and using `htop `I could see the culprit are liquidsoap process running for each of stations I have enabled in Azuracast. Thing is AutoDJ for them are completely OFF.

![image](https://github.com/user-attachments/assets/e91cad49-67e8-407c-987b-221d2367079a)

Can you please assist?

Thanks and regards,
Elvis

**Comment by BusterNeece** [comment]
@elvisn Does this persist even after restarting the given stations?

**Comment by elvisn** [comment]
Hi @BusterNeece yes it does. As soon as I bring the docker up those processes are created.

EDIT: Just found out one thing. THOSE STATION NAMES ARE NOT VALID!
I have initially created radios with "starthome" and "rádio_rodin" but I have renamed the URL sufix for a better names afterwards. Those process are not even valid now.

**Comment by elvisn** [comment]
Guys found the workaround and have the steps to reproduce the issue. It happens when you have AutoDJ started and you try to disable AutoDJ in config and/or disable the whole station.

### HOW TO REPRODUCE

1. Create a new station with no media and AutoDJ + Liquidsoap enabled;
2. Start AutoDJ, you might notice Liquidsoap process with high CPU;
3. Disable AutoDJ in Station config;
4. Disable Station on Azuracast Admin.

Liquidsoap for that disabled station keeps running even after a server reboot and there is no way to stop it. The only way to solve this is reenabling Station, AutoDJ, then Stopping AutoDJ.

I think it is missing a trigger to run the "STOP AUTODJ" process when disabling AutoDJ in station config, and when disabling the Station.

Thank you,
Elvis

**Comment by BusterNeece** [comment]
I looked into this and identified that AzuraCast was actually currently doing _nothing_ if you change a station's base directory, which caused all kinds of weird/bad things to happen. In the latest Rolling Release, we now properly detect a change in the base directory, spin down old services, move relevant files over, and update Storage Locations all in one step.
