### ISSUE TITLE
WebDJ socket problem

### ISSUE THREAD

**Issue by Zentie13** [AzuraCast/AzuraCast#7529]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

20.1 stable

### What happened?

I seem to have a problem with WebDJ sockets, as per the second screenshot. It currently show no playlist selected, but even with the playlist playing, when I hit the Start streaming button, this error appears. I need to get this resolved, as the scheduled playlists still do not go out.
![Screenshot01](https://github.com/user-attachments/assets/71efbf49-f3fd-4764-9bb5-88ad2c6428ac)
![screenshot02](https://github.com/user-attachments/assets/8acd1569-de9c-4389-9ab6-6242401bf1fc)

**Comment by Yahav** [comment]
The console log would be useful here. 
Hit F12, select the console, reload the page, click the start streaming and provide the entire console output.

**Comment by CLPDevelopment** [comment]
I have the same problem! This is my output:
![Screenshot 2024-11-08 170814](https://github.com/user-attachments/assets/7e8dbc76-8032-4a4b-83fc-c754b97ec918)

**Comment by Yahav** [comment]
@CLPDevelopment anything in Liquidsoap logs?
Also, At the Station Profile form, go to Streamers/DJS, check the port under "Customize DJ/Streamer Port" and check if its actually bound. so if the port is 8005 for example:
ss -lptn 'sport = :8005'

**Comment by Zentie13** [comment]
Hi guys

It looks as though things change daily and I decided to move to a more stable platform. Thanks for everything.


Regards


Hein Zentgraf

0837745609


------ Original Message ------
From "Yahav" ***@***.******@***.***>>
To "AzuraCast/AzuraCast" ***@***.******@***.***>>
Cc "Hein Zentgraf" ***@***.******@***.***>>; "Author" ***@***.******@***.***>>
Date 2024/11/8 18:41:00
Subject Re: [AzuraCast/AzuraCast] WebDJ socket problem (Issue #7529)


@CLPDevelopment<https://github.com/CLPDevelopment> anything in Liquidsoap logs?
Also, At the Station Profile form, go to Streamers/DJS, check the port under "Customize DJ/Streamer Port" and check if its actually bound. so if the port is 8005 for example:
ss -lptn 'sport = :8005'

**Comment by CLPDevelopment** [comment]
> @CLPDevelopment anything in Liquidsoap logs? Also, At the Station Profile form, go to Streamers/DJS, check the port under "Customize DJ/Streamer Port" and check if its actually bound. so if the port is 8005 for example: ss -lptn 'sport = :8005'

Is it good if they use the same port?
