### ISSUE TITLE
Mark as Jingle

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#753]
**Is your feature request related to a problem? Please describe.**
Now my listeners see "alles-radio - Jingle" as title if there is any jingle.

**Describe the solution you'd like**
I want a features to mark Tracks as jingle, and azuracast don't send the metadata of these Tracks.

**Comment by NeddyPlays** [comment]
What you can do i leave the Artist Empty or put a "-" in front of the artist. 
If your using Shoutcast it refuses to update the Title.

**Comment by SlvrEagle23** [comment]
Song-based playlists now have a "jingle mode" that can be turned on that will:

- Hide the jingles' title/artist metadata from "Now Playing" data, including AzuraCast's Now Playing API endpoints,
- Prevent the jingles from being included in the song playback timeline and other statistics in AzuraCast, and
- Prevent web hooks (i.e. Twitter posts) from triggering on the jingles.

We accomplish this by sending the same title/artist metadata as the previously played song as the annotated title/artist for the jingle, while instructing Liquidsoap to play the actual jingle instead. Icecast doesn't register this as a change of metadata, and AzuraCast sees the same song playing.
