### ISSUE TITLE
Lyrics textbox in Media not saved when editing

### ISSUE THREAD

**Issue by mcassisa** [AzuraCast/AzuraCast#7535]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#3de1908

### What happened?

I edited a Media and wrote text* in Lyrics textbox, it doesn't get saved even though a pop up said "Changes saved"

**Comment by kphred** [comment]
This started happening to us after the AzuraCast 0.20.1 (Jun 2, 2024) rolling release update. We haven't been able to find any error messages in the log files.
