### ISSUE TITLE
Problem with Discord Webhook

### ISSUE THREAD

**Issue by TheRealMakkus** [AzuraCast/AzuraCast#7536]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #3de1908

### What happened?

I use a Discord Webhook whenever a Live DJ is connecting. This worked all the time, and it is still working. 

But - since any of the last updates, there is an issue with this. If the Live DJ disconnects after his show, another Discord Message is coming up. "Now live:" ... without any name or informations.

"Live Streamer/DJ Disconnected" is NOT checked. Only "Live Streamer/DJ Connected" is checked.

**Comment by xBengie** [comment]
I have the same issue on the same version.
