### ISSUE TITLE
Error code 403 on opening the "music files" page when managing a station.

### ISSUE THREAD

**Issue by inQntrol** [AzuraCast/AzuraCast#754]
**Installation method**
Docker

**Host OS (for Docker installations)**
Win Server 2016

**Describe the bug**
So I've just got docker installed today and then a fresh version of Azuracast, during the installation, I set the file path to all the songs I plan on using for the station, I moved on from this and when I was finished with the config and I was setting up the station, none of my songs were playing, so I went to the "music files" page and there it failed to load the page, leaving me with an error 403. I don't know if I missed giving azuracast permissions or something during installation?

**To Reproduce**
 unsure if this will change anything because its blatent this has happened to me but all I did to reproduce this was load the music files page.

**Expected behavior**
I expect it to load into the music files page.

**Screenshots**
https://puu.sh/BlmrP/3095e88ebf.png

**Desktop (please complete the following information):**
(this is my PC, not the dedicated server I am running it off)
 - OS: Windows 10
 - Chrome
 - Version 1803

**Comment by SlvrEagle23** [comment]
@inQntrol I'm definitely not sure what's causing this one. The main files page shouldn't be returning just a JSON response like that in any case, it should at least be rendering the file browser. Even then, that's not the actual format error messages use in the code, and I can't find anything in the code that specifically returns both the error 403 and message "Forbidden" like that.

Can you inspect the page and see if you can track down where that error is actually being triggered? What I'm really curious about is if it's rendering the entire page underneath that, then replacing it with the error message for some reason.
