### ISSUE TITLE
Invalid annotation response (double quote escaping missing)

### ISSUE THREAD

**Issue by RM-FM** [AzuraCast/AzuraCast#7540]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

dev-ls2.3.x

### What happened?

It appears that the annotation string is not properly escaped. Double quotes in the metadata (e.g. Title) are causing the resolution of the annotation string to fail. Possibly not only related to LS 2.3.x.

### Relevant log output

```shell
024/11/05 12:46:08 [lang:3] API nextsong - Response (200): annotate:title="A Very Bad Fun Idea (Taken From The Film "BONUS TRACK")",artist="Years & Years",duration="215.22",song_id="dc5751cba1bbab7501db0135fc932379",media_id="11924.00",playlist_id="10":media:Years & Years - A Very Bad Fun Idea (Taken From The Film BONUS TRACK).mp3
2024/11/05 12:46:08 [request.3885:4] Pushed ["annotate:title=\"A Very Bad Fun Idea (Taken From The Film \"BONUS TRACK\")\",artist=\"Years & Years\",duration=\"215.22\",song_id=\"dc5751cba1bbab7501db0135fc932379\",media_id=\"11924.00\",playlist_id=\"10\":media:Years & Years - A Very Bad Fun Idea (Taken From The Film BONUS TRACK).mp3";...].
2024/11/05 12:46:08 [request.3885:4] Resolving "annotate:title=\"A Very Bad Fun Idea (Taken From The Film \"BONUS TRACK\")\",artist=\"Years & Years\",duration=\"215.22\",song_id=\"dc5751cba1bbab7501db0135fc932379\",media_id=\"11924.00\",playlist_id=\"10\":media:Years & Years - A Very Bad Fun Idea (Taken From The Film BONUS TRACK).mp3" (timeout 20s)...
2024/11/05 12:46:08 [annotate:4] Error while parsing annotate URI "title=\"A Very Bad Fun Idea (Taken From The Film \"BONUS TRACK\")\",artist=\"Years & Years\",duration=\"215.22\",song_id=\"dc5751cba1bbab7501db0135fc932379\",media_id=\"11924.00\",playlist_id=\"10\":media:Years & Years - A Very Bad Fun Idea (Taken From The Film BONUS TRACK).mp3": Char 55-60: Syntax error
2024/11/05 12:46:08 [request.3885:4] Char 55-60: Syntax error
2024/11/05 12:46:08 [request:4] Failed to resolve "annotate:title=\"A Very Bad Fun Idea (Taken From The Film \"BONUS TRACK\")\",artist=\"Years & Years\",duration=\"215.22\",song_id=\"dc5751cba1bbab7501db0135fc932379\",media_id=\"11924.00\",playlist_id=\"10\":media:Years & Years - A Very Bad Fun Idea (Taken From The Film BONUS TRACK).mp3"! For more info, see server command `request.trace 3885`.
2024/11/05 12:46:08 [request.3885:4] Every possibility failed!
2024/11/05 12:46:08 [request.3885:4] Request destroyed.
```

**Comment by BusterNeece** [comment]
@RM-FM Are you on the latest ls-2.3.x branch version? We've updated that API to return JSON, so you should be seeing different log values on the latest version.

**Comment by RM-FM** [comment]
@BusterNeece It was the version of the day just before that change. Let me re-test it, but as far as I can see in the code, that should be solved with that improvement. I'll come back to you...

**Comment by RM-FM** [comment]
@BusterNeece It seems that this issue came back with https://github.com/AzuraCast/AzuraCast/commit/c8149993213dcf409a9a1927fbb8241d9fd38f6e

**Comment by BusterNeece** [comment]
@RM-FM that seems unlikely given the only data that changed was autocue data, not the other values, whose escaping didn't change...what's the specific error being reported?

**Comment by RM-FM** [comment]
> I can confirm it's not the _exact_ same error because I have a test file in my rotation that uses double-quotes and it's still escaped properly, so I think whatever's going on is similar but not the same.

You're right! It seems to be a similar issue to what @wegGehamstert noticed yesterday. Liquidsoap has stopped triggering Azuracast API calls (e.g., nextsong), causing the queue to run out of tracks and resulting in the error.mp3 being played. Romain is already looking into it.
