### ISSUE TITLE
No audio and webplayer asks for authentication when listen to station

### ISSUE THREAD

**Issue by ueteknik** [AzuraCast/AzuraCast#7542]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #3de1908 (2024-10-21 22:52) • Docker • PHP 8.3

### What happened?

After this morning when I logged in to the administration side it´s suddenly not possible to listen to any mp3 stream. It prompt to login to the stream. And If I go to the public site then it seems like it´s playing but no sound. I can see that the meta data is updating and the encoder software is connected and working ok.  If I go to the listen/stationname site I come to to the Icecast page (Icecast 2.4)
It´s very similar to an earlier bug reported here: "When playing the radio asks for authentication #5264" but that case is closed.

I have tried to delete a station and configured it again but no change. 
I also tried to restart it and clean up the cash but no result. 

### Relevant log output

```shell
Icecast fault log:
[2024-11-06  16:23:32] WARN slave/slave_startup process has 65536 max file descriptor limit
[2024-11-06  16:23:48] WARN source/source_client_startup Mountpoint /radio.mp3 in use
[2024-11-06  16:23:52] WARN source/source_client_startup Mountpoint /radio.mp3 in use
[2024-11-06  16:23:56] WARN source/source_client_startup Mountpoint /radio.mp3 in use
[2024-11-06  16:24:00] WARN source/source_client_startup Mountpoint /radio.mp3 in use
[2024-11-06  16:24:04] WARN source/source_client_startup Mountpoint /radio.mp3 in use
[2024-11-06  16:24:08] WARN source/source_client_startup Mountpoint /radio.mp3 in use
[2024-11-06  16:24:12] WARN source/source_client_startup Mountpoint /radio.mp3 in use
[2024-11-06  16:24:16] WARN source/source_client_startup Mountpoint /radio.mp3 in use
[2024-11-06  16:45:11] WARN slave/slave_startup process has 65536 max file descriptor limit


Icecast access logg:
92.168.5.10 - - [06/Nov/2024:19:45:42 +0100] "GET /status-json.xsl HTTP/1.1" 200 1099 "-" "Mozilla" 0
192.168.5.10 - - [06/Nov/2024:19:45:45 +0100] "GET /status-json.xsl HTTP/1.1" 200 1099 "-" "Mozilla" 0
127.0.0.1 - admin [06/Nov/2024:19:45:48 +0100] "GET /admin/stats HTTP/1.1" 200 2638 "-" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.2) Gecko/20070219 Firefox/2.0.0.2" 0
127.0.0.1 - admin [06/Nov/2024:19:45:48 +0100] "GET /admin/listclients?mount=%2Fradio.mp3 HTTP/1.1" 200 116 "-" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.2) Gecko/20070219 Firefox/2.0.0.2" 0
192.168.5.10 - - [06/Nov/2024:19:45:48 +0100] "GET /status-json.xsl HTTP/1.1" 200 1100 "-" "Mozilla" 0
192.168.5.10 - - [06/Nov/2024:19:45:51 +0100] "GET /status-json.xsl HTTP/1.1" 200 1099 "-" "Mozilla" 0
192.168.5.10 - - [06/Nov/2024:19:45:54 +0100] "GET /status-json.xsl HTTP/1.1" 200 1099 "-" "Mozilla" 0
192.168.5.10 - - [06/Nov/2024:19:45:57 +0100] "GET /status-json.xsl HTTP/1.1" 200 1099 "-" "Mozilla" 0
192.168.5.10 - - [06/Nov/2024:19:46:00 +0100] "GET /status-json.xsl HTTP/1.1" 200 1099 "-" "Mozilla" 0
```

**Comment by ueteknik** [comment]
New information. I now add a new station with a different name and then I got this station to work. The first time when I delete the station and add it again I used the same name without any result.

**Comment by BusterNeece** [comment]
@ueteknik If you see authentication prompts, that often means that you're being blocked for some reason from connecting to the radio station. Did you set a country blocklist up, or block an IP range, or block user-agents in your profile?

**Comment by ueteknik** [comment]
Hi

 

Sorry for the delay in answering. 
No, I have not set up any blocking what I know at least. I don´t know if I can see it now because the only way I got it working again was to delete the station and create a new one with another station name. 

 

Regards

Urban

 

 

 

Från: Buster Neece ***@***.***> 
Skickat: den 13 november 2024 09:51
Till: AzuraCast/AzuraCast ***@***.***>
Kopia: ueteknik ***@***.***>; Mention ***@***.***>
Ämne: Re: [AzuraCast/AzuraCast] No audio and webplayer asks for authentication when listen to station (Issue #7542)

 

@ueteknik <https://github.com/ueteknik>  If you see authentication prompts, that often means that you're being blocked for some reason from connecting to the radio station. Did you set a country blocklist up, or block an IP range, or block user-agents in your profile?

**Comment by BusterNeece** [comment]
Ah okay, well if you run into the issue again, feel free to reopen the issue or open a new one.
