### ISSUE TITLE
 Problems with UTF 8 on Live Streamers

### ISSUE THREAD

**Issue by Aealyn** [AzuraCast/AzuraCast#7546]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #3de1908 (2024-10-21 22:52) 

### What happened?

Hello everyone,

I've been using AzuraCast in conjunction with IceCast for quite some time. So far I have read out my stream information via the API (Streamer) and via the xls via the IceCast. So far so good. 

Now I have written a script that is supposed to read all the data from the API. 

I have now noticed that if I set the stream to ISO-8859-1, the data is output correctly, but not with UTF-8, then it puts strange characters there. But strangely enough with AutoDJ it shows everything correctly.

My readout script is completely designed for UTF8 and displays all characters correctly on AutoDJ (regardless of whether the stream is set to ISO-8859-1 or UTF-8). If I go to the stream with the same songs, it shows strange characters.

Since I'm currently programming a chat that does a direct stream readout for the URL stored in the admin area, I wouldn't like to add the variant via the xls again because people might not understand which links they actually need here, so I'd like to have it Centrally located in one place from the selection.

What's strange is that with the streamer he gets the umlauts. As you can see from the API!

   "streamer_name": "Sagira \u00e4t \u00f6ffi l\u00fcm",

But when it comes to artist and title, he only gets 
 "text": "Eisbrecher - Verr\ufffdckt | Sagira",
                "artist": "Eisbrecher",
                "title": "Verr\ufffdckt | Sagira",

the /uffd for any umlaut (ä, ö, ü or even ß)

Can someone take a look at my script and help me? I'm also attaching screenshots of the current output in UTF8 on the stream (both the data from the API and my display from the file)

Thank you and have a nice Saturday everyone

Image 1: AzuraCast API LiveStreamer
Image 2: My Display from the File LiveStreamer
Image 3: AzuraCast Profil Site LiveStreamer
Image 4: IceCast xls LiveStreamer
Image: 5: AzuraCast API AutoDJ
Image 6:  My Display from the File AutoDJ
Image 7: AzuraCast Profil Site AutoDJ
Image 8: IceCast xls AutoDJ

![image](https://github.com/user-attachments/assets/72a6959c-c80a-4730-a4cc-7205aded08ad)
![image2](https://github.com/user-attachments/assets/3cbd16af-9b2a-4ecc-b02f-6dfc3e8b7769)
![image3](https://github.com/user-attachments/assets/5a5595f3-8477-4d29-841a-d39a7e7c52e5)
![image4](https://github.com/user-attachments/assets/856e7473-64e8-41bd-8daf-a3dc044f718f)
![image5](https://github.com/user-attachments/assets/0bc5a9b7-5446-4a42-8f9a-45e8ad6e3f01)
![image6](https://github.com/user-attachments/assets/8f982405-3af3-4444-b510-20bbdcaae361)
![image7](https://github.com/user-attachments/assets/286d270e-22ae-41b7-ba57-d84370d87cd5)
![image8](https://github.com/user-attachments/assets/ea1ec7ff-e62e-465f-9a91-9ad259e604c5)

**Comment by Yahav** [comment]
Well, U+FFFD is the actual UTF for the question mark so the issue isn't with displaying but rather parsing.
Few missing pieces of information:
1. the output of the actual icecast server json/xml in live stream
2. which broadcast software are you using? what are the metadata settings of said software?

**Comment by Aealyn** [comment]
no, it can't be a parse error on our part, because if I set it to ISO-8859-1, everything is displayed correctly and it's definitely not a ? , because when I set the stream to UTF8 it does the \ufffd in the text / artist or title for all of them. If I set it to ISO-8859-1, it displays the umlauts correctly. Especially since it is displayed correctly on the IceCast site, so it can't be a parse error.

Regarding 1. I posted the JSON output from the LiveStreamer in the first picture

Regarding 2. It doesn't matter which software we connect with, we tried with SAM, RadioBoss, Mairlist and also VDJ. The meta data settings are set to "Auto". As I said, if I set the stream itself to ISO-8859-1, it is displayed, but not with UTF8

Regarding 3. We establish a connection via LiquidSoap because every presenter/DJ with us has their own stream data.

**Comment by BusterNeece** [comment]
I'm really not sure how we'd begin to tackle this issue on our end. I suspect it may be something worth inquiring with Liquidsoap directly about: https://github.com/savonet/liquidsoap

We work with them quite closely, and it sounds like this may be an issue with either Liquidsoap's parsing, or something in how we're instructing it to operate that we need to change; either way they could let us know specifically what's causing this and what to do.

**Comment by Aealyn** [comment]
If it were due to LiquidSoap, then it shouldn't display the UTF8 on the AutoDJ either, since the AutoDJ is the LiquidSoap or am I seeing that wrong? 

That means to me, it looks like the transfer from LiquidSoap to the API interface doesn't work if there is a LiveDJ on it. 

Because with AutoDJ the output works with both the ISO variant and the UTF8 variant. With LiveDJ it only works with the ISO variant but not with UTF8.

**Comment by Yahav** [comment]
You kind of misunderstood a lot of what i was trying to say 😊
Anyway, since Icecast config is always set to UTF-8 encoding (even if the AutoDJ setting is set to ISO) i would suggest the following.
Set your AutoDJ "Character Set Encoding" setting to UTF-8, and set your **broadcast software** to UTF-8 (make sure to reload changes)
and see if the issue still persists. 
If it does, providing the URL to the icecast server web interface as well as the AzuraCast public currently playing api url might help us understand further.

**Comment by Aealyn** [comment]
So, if I set the AutoDJ character set to UTF-8 and explicitly set it to UTF8 in the broadcast software, it works, but that can't be useful because there are enough people who have no real idea about the settings of the broadcast software Leave it on Auto in the software. Therefore, this should also be recognized correctly. (As I said, this also works wonderfully when set to ISO, but not with UTF8)

I didn't mean anything bad in what I wrote. And I'm sorry if I misunderstood something :) I'm just a little irritated because I can't understand why that is the case. And since I want to offer the chat to customers in the long term, the title display should of course work, regardless of whether UTF8 or ISO has been set. Of course I can decide for myself for my stream, but for customers it is of course the customer who decides on the character encoding and then I have no influence on it and of course it doesn't work well if the umlauts are all written as ? be shown.

API URL: https://azura.nexusradio-hosting.de/api/nowplaying_static/demo.json

**Comment by Aealyn** [comment]
Good morning, Unfortunately the error is still the same as before :( Update made last night and tested directly. The umlauts remain incorrect in both the API and my script

**Comment by Yahav** [comment]
@Aealyn Could you try to make some settings change in the channel profile and restart the service to make sure the Icecast config has been updated?
Also, so now your broadcast software is set to Automatic and the AutoDJ charset encoding is set to ISO and it still doesn't show the chars correctly within the AzuraCast API?

**Comment by Aealyn** [comment]
@Yahav 
hey, yes the Broadcast software is set to automatic and the AutoDJ in AzuraCast is set to UTF8 and the error is still there. I will make the changes to the profile in about 2 hours and then test it again and let you know.

**Comment by Aealyn** [comment]
No, even after yesterday's updates and even after various settings and restarts of the station, it remains the same as before. If I set it to ISO, everything is displayed correctly. If I set it to UTF8, the meta data is still not transferred correctly from LiveDJ. Unfortunately

UTF 8 Setting:  "now_playing": {
        "sh_id": 1386232,
        "played_at": 1731743214,
        "duration": 0,
        "playlist": "",
        "streamer": "Sagira",
        "is_request": false,
        "song": {
            "id": "6142a028e772f55f78041aeab29ff8a0",
            "art": "https://azura.nexusradio-hosting.de/static/img/generic_song.jpg",
            "custom_fields": [],
            "text": "Eisbrecher - Verr\ufffdckt | Sagira",
            "artist": "Eisbrecher",
            "title": "Verr\ufffdckt | Sagira",
            "album": "",
            "genre": "",
            "isrc": "",
            "lyrics": ""
        },
        
        ISO:
         "now_playing": {
    "sh_id": 1386258,
    "played_at": 1731743503,
    "duration": 0,
    "playlist": "",
    "streamer": "Sagira",
    "is_request": false,
    "song": {
      "id": "e954d7d34e5aba4068a5b6d30e180483",
      "art": "https://azura.nexusradio-hosting.de/static/img/generic_song.jpg",
      "custom_fields": [],
      "text": "Eisbrecher - Verrückt | Sagira",
      "artist": "Eisbrecher",
      "title": "Verrückt | Sagira",
      "album": "",
      "genre": "",
      "isrc": "",
      "lyrics": ""
    },
    "elapsed": 98,
    "remaining": 0
  },

**Comment by Yahav** [comment]
If so, the only conclusion i have on this matter is that the broadcast software's Auto encoding option decides the charset based on the file or something like this and in this case choosing ISO which is not consistant with the charset Liquidsoap/Icecast is set expecting to receive. 
If that's the case there, i don't see anything wrong with AzuraCast or Liquidsoap and you should match the charset you're streaming to the one the system is expecting.

**Comment by BusterNeece** [comment]
Looking through this issue, unfortunately I think we have very little insight into what the streaming software is looking for in its determination of the encoding to use when it is set to "Auto-detect". Without knowing exactly what it's looking for to make that determination, we couldn't make any changes to our end to accommodate those checks.

If there's anything in particular we can do to help inform the auto-detect function to use the correct encoding, please feel free to reopen this issue and let us know.
