### ISSUE TITLE
Scheduled items not interrupting other songs to play at scheduled time.

### ISSUE THREAD

**Issue by corey-harker** [AzuraCast/AzuraCast#7550]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#4ec396e

### What happened?

We have scheduled programs that need to fire at set times every week. Before the last major update, checking 'interrupt other songs to play at scheduled times' in the advanced tab of the playlist worked like a charm. Now it doesn't seem to function at all.

**Comment by corey-harker** [comment]
![Screenshot 2024-11-10 161811](https://github.com/user-attachments/assets/9d7aa579-fb2a-425c-9d55-4791eff4e00c)
![Screenshot 2024-11-10 161835](https://github.com/user-attachments/assets/59bb80c3-8aa3-4f14-ac38-3d98acfd397a)
![Screenshot 2024-11-10 161859](https://github.com/user-attachments/assets/d62c4338-3d9a-4984-aa15-83289b04a7e6)
![Screenshot 2024-11-10 161915](https://github.com/user-attachments/assets/fbbacc55-1580-4b90-b781-24f486e1a146)

Hopefully these screenshots will help :-) Thank you!!!

**Comment by wegGehamstert** [comment]
What Playlist are you interupting? It could be a problem with the priority

**Comment by darellrazk** [comment]
Please go back to this issues #7444
Scheduled items not interrupting other songs to play at scheduled time is broken at the moment. This feature will remain broken until @caturria is able to attempt a fix.

**Comment by BusterNeece** [comment]
See #7444.
