### ISSUE TITLE
Update Liqudisoap

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#756]
(or downgrade)
to fix this: https://github.com/savonet/liquidsoap/issues/496

**Comment by preterive** [comment]
I think this would be nice in the auto update script.
now i update it manually.

**Comment by SlvrEagle23** [comment]
@preterive Re-triggering a new build for the Docker image that should pick up the newest version from OPAM; not sure that there's a simple way to facilitate the auto-update from Traditional installs as they'll report already being on the same version.
