### ISSUE TITLE
After renaming the URL stub of a station mount points aren't reachable

### ISSUE THREAD

**Issue by Sella-GH** [AzuraCast/AzuraCast#7561]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #b56d6ed (2024-11-17 11:56)

### What happened?

After I renamed the URL stub of my station from "test" to "azzy" the mount points aren't reachable over the new stub. Instead I have to use the old stub to access them.

However in the "Streams" UI Widget on the Station Profile the new URL stub is shown but you can't connect to it either. Neither when pressing the "Play" button on the page.

**Comment by wegGehamstert** [comment]
Can you provide some screenshots of your mountpoint configuration?

**Comment by Sella-GH** [comment]
Simple default mountpoint:
![image](https://github.com/user-attachments/assets/cf2efa31-dcaf-4ea2-9353-77ba1b02418d)
![image](https://github.com/user-attachments/assets/309bb95a-5a86-48a8-ab83-0e26309a5d42)

**Comment by wegGehamstert** [comment]
Can you tell me from wich URL do you had before and wich you want now?

**Comment by wegGehamstert** [comment]
Please go in the mount point setting to the tab advanced and send me a screen

**Comment by Sella-GH** [comment]
Here you go:
![image](https://github.com/user-attachments/assets/d99fb69f-a625-48e4-a5fc-feae79f6c190)

**Comment by wegGehamstert** [comment]
Maybe try to paste `https://domain.tld/listen/azzy/radio.mp3` in to the "Mount Point URL"
If i remember correct, i had the same problem some time ago

**Comment by BusterNeece** [comment]
I looked into this and identified that AzuraCast was actually currently doing _nothing_ if you change a station's base directory, which caused all kinds of weird/bad things to happen. In the latest Rolling Release, we now properly detect a change in the base directory, spin down old services, move relevant files over, and update Storage Locations all in one step.

**Comment by Sella-GH** [comment]
Can't confirm the fix, sadly.
I renamed the stub again from "azzy" to "azzy_test" in the same manner than before (station was "disabled" and not running any services). When starting the station connecting to the new stub results in a 404.

**Comment by BusterNeece** [comment]
@Sella-GH Yeah, that's my bad. I thought this was the same error type as the other one (which actually should be fixed by the commit I made)...this one is similar but slightly different.

I just pushed some code up to Rolling that should force an nginx config rewrite if the short_name changes (thus rewriting the config for those `/listen/asdf` fancy URLs). Fixes it in my local testing.

**Comment by Sella-GH** [comment]
Fixed and works! Thanks for the effort. 🙂
