### ISSUE TITLE
Create Pre-Randomized Playlist To Play (Shuffle)

### ISSUE THREAD

**Issue by CodeSteele** [AzuraCast/AzuraCast#757]
Currently the algorithm used to describe playing random music picks a random song, makes sure it hasn't been played in the last 10, and then plays it.

Problem is that for large playlists you'll notice some songs play multiple times and others you won't hear at all this is due to:
- The nature of randomness with these data sets (it'll _eventually_ be fair but we'll expect duplicates, re: the birthday problem and a 50% chance of getting a duplicate song in ~23 hits)
- Possible bias in the random algorithm (haven't checked, not sure if a crypto-secure random provider was provided for _randomizing songs_)

Ultimately, IMO: the best solution to this is to shuffle the playlist up front, and play through it. This requires temporary storage of the playlist. An idea of how to handle this is:

When I can't find a cached temp playlist:
- Generate a list of song IDs
- Store the array in Redis

When getting the next song:
- Pull Redis temp playlist
- Pop record off the top
- Resave playlist

(Annoying, causes a lot of bulk writes, but still pretty light, it's all integers)

When the list is empty, regenerate.

The only annoyance is that when we add a new song either:
- The song is unavailable till we end and re-shuffle
- Pop the song somewhere in the playlist or at the end?

**Comment by SlvrEagle23** [comment]
@CodeSteele The new shuffle method has been implemented! Leaving ticket open for possible further development.

**Comment by SlvrEagle23** [comment]
Only remaining to-do item on this is to implement proper cache invalidation in the event media records are added to / removed from playlists, or outright removed.

**Comment by SlvrEagle23** [comment]
Feeling confident now about the cache invalidation and appending. If removing an item or items from a playlist, or making some substantial change to the playlist, it'll wipe the entire queue and start fresh. If adding a new song to the playlist, it'll append the new media item to the list, shuffling it in if the playlist order is "Shuffled".
