### ISSUE TITLE
AzuraCast fails to play anything after changing domain name

### ISSUE THREAD

**Issue by BusterNeece** [AzuraCast/AzuraCast#7571]
### Discussed in https://github.com/AzuraCast/AzuraCast/discussions/7570

<div type='discussions-op-text'>

<sup>Originally posted by **LunarLoony** November 21, 2024</sup>
Hello! A few days ago, I changed the domain name pointing to my AzuraCast server. All set up correctly, and I can access the admin console and public pages with no issue through my web browser. Playback also worked perfectly just after switching over.
However, since restarting broadcasting, my station just does not play a darn thing. I believe the reason I restarted was to update AC to version 0.20.3, not sure if that has any bearing.

Specifically, what I'm seeing is that the broadcasting service is not broadcasting.

On the admin console, the 'On The Air' section shows that the station is offline. There is always a song queued up (which changes when I restart broadcasting) but it never gets played.
I can press 'play' on the Local Stream. This plays the default 'station offline' sound, despite the fact I have uploaded custom audio for this.
If I go to the Icecast admin page and select 'List Mountpoints', there's nothing listed. (To clarify, there _is_ a mountpoint configured in AzuraCast.)

I should also note that AzuraCast can process and play my files if I do so manually through the admin console.

Things I have tried:

- Reload configuration.
- Restart broadcasting.
- Create new test station. (This worked very briefly, but I have tried again since with no such luck.)
- Delete and recreate playlists.
- Delete and recreate mountpoints.
- Delete and recreate entire station.
- Uninstall AzuraCast and reinstall.
- Switch to rolling release.
- Restore from backup.
- Remove all traces of AzuraCast from my server, including other installed applications, and reinstall completely from scratch.

Things I have not yet tried:

- Rollback AzuraCast to 0.20.2.
- Switch back to original domain name. (I plan to get rid of the original domain name, so this wouldn't really be a solution)

 The Application Log just shows the following lines, repeated... seems to suggest that AC can't talk to its own mount points, which seems a bit odd.

```
[2024-11-21T09:31:44.994911+00:00] AzuraCast.WARNING: Request returned status code 400. {"body":""} {"station":{"id":1,"name":"Time Twister FM"}}
[2024-11-21T09:31:44.995880+00:00] AzuraCast.WARNING: Remote server has no mount points listed. {"response":"<?xml version=\"1.0\"?>\n<icestats>\n  <admin>icemaster@localhost</admin>\n  <banned_IPs>0</banned_IPs>\n  <build>20240213100513</build>\n  <client_connections>291</client_connections>\n  <clients>0</clients>\n  <connections>292</connections>\n  <file_connections>15</file_connections>\n  <host>radio.example.com</host>\n  <listener_connections>0</listener_connections>\n  <listeners>0</listeners>\n  <location>AzuraCast</location>\n  <outgoing_kbitrate>0</outgoing_kbitrate>\n  <server_id>Icecast 2.4.0-kh22</server_id>\n  <server_start>21/Nov/2024:09:12:52 +0000</server_start>\n  <source_client_connections>0</source_client_connections>\n  <source_relay_connections>0</source_relay_connections>\n  <source_total_connections>0</source_total_connections>\n  <sources>0</sources>\n  <stats>0</stats>\n  <stats_connections>0</stats_connections>\n  <stream_kbytes_read>0</stream_kbytes_read>\n  <stream_kbytes_sent>0</stream_kbytes_sent>\n</icestats>\n"} {"station":{"id":1,"name":"Time Twister FM"}}
[2024-11-21T09:31:44.997111+00:00] AzuraCast.WARNING: Response does not contain a "source" listing; the stream may be hidden or misspelled. {"response":"{\"icestats\":{\"admin\":\"icemaster@localhost\",\"banned_IPs\":0,\"build\":20240213100513,\"host\":\"radio.example.com\",\"location\":\"AzuraCast\",\"outgoing_kbitrate\":0,\"server_id\":\"Icecast 2.4.0-kh22\",\"server_start\":\"21/Nov/2024:09:12:52 +0000\",\"stream_kbytes_read\":0,\"stream_kbytes_sent\":0}}"} {"station":{"id":1,"name":"Time Twister FM"}}
[2024-11-21T09:31:45.008122+00:00] AzuraCast.ERROR: No track to update. {"exception":"[object] (RuntimeException(code: 0): No track to update. at /var/azuracast/www/backend/src/Entity/Repository/SongHistoryRepository.php:79)"} {"station":{"id":1,"name":"Time Twister FM"}}
```

So... with all that said, any ideas? I'll have another trawl through the other log files, but I didn't see anything else that looked out of place.</div>

**Comment by BusterNeece** [comment]
@lunarloony Specifically, can you try rebuilding the queue directly by going to `System Administration`, then `System Debugger`, then scrolling to the bottom of the page, finding the station in question, and clicking `Clear Queue`. This should pop up a full debug log of the system's attempt to rebuild the queue and will tell you what's specifically causing it _not_ to be able to populate the queue at all.

**Comment by LunarLoony** [comment]
I've cleared the queue. Had a quick look at the popup log, but I didn't see anything untoward - it looks like it's picking my playlists up correctly and queueing up songs.
Is this log saved anywhere so I can easily share it?

Here is the output when I select Liquidsoap Log:

```
2024/11/21 11:07:52 >>> LOG START
2024/11/21 11:07:51 [ffmpeg.filter.bitstream:3] No valid mode found for filter pgs_frame_merge!
2024/11/21 11:07:51 [main:3] Liquidsoap 2.3.0+git@ef2a2dbfc
2024/11/21 11:07:51 [main:3] Using: alsa=0.3.0 angstrom=0.16.0 ao=0.2.4 asetmap=0.8.1 asn1-combinators=0.3.2 astring=0.8.5 base=v0.16.3 base.base_internalhash_types=v0.16.3 base.caml=v0.16.3 base.shadow_stdlib=v0.16.3 base64=3.5.1 bigarray=[distributed with Ocaml] bigarray-compat=1.1.0 bigstringaf=0.9.1 bjack=0.1.6 bos=0.2.1 bytes=[distributed with OCaml 4.02 or above] ca-certs=v1.0.0 camlp-streams camomile.lib=2.0 cohttp=5.3.1 cohttp-lwt=5.3.0 cohttp-lwt-unix=5.3.0 conduit=6.2.3 conduit-lwt=6.2.3 conduit-lwt-unix=6.2.3 cry=1.0.3 cstruct=6.2.0 ctypes=0.22.0 ctypes-foreign=0.22.0 ctypes.stubs=0.22.0 curl=0.9.2 digestif.c=1.2.0 domain-name=0.4.0 domain_shims dssi=0.1.5 dtools=0.4.5 dune-build-info=3.16.0 dune-private-libs.dune-section=3.16.0 dune-site=3.16.0 dune-site.private=3.16.0 duppy=0.9.4 eqaf=0.9 faad=0.5.2 fdkaac=0.3.3 ffmpeg-av=1.2.1 ffmpeg-avcodec=1.2.1 ffmpeg-avdevice=1.2.1 ffmpeg-avfilter=1.2.1 ffmpeg-avutil=1.2.1 ffmpeg-swresample=1.2.1 ffmpeg-swscale=1.2.1 fileutils=0.6.4 flac=0.5.1 flac.decoder=0.5.1 flac.ogg=0.5.1 fmt=0.9.0 fpath=0.7.3 frei0r=0.1.2 gd=1.1 gen=1.1 gmap=0.3.0 inotify=2.0-62-g5e58536 integers ipaddr=5.6.0 ipaddr-sexp=5.6.0 ipaddr.unix=5.6.0 irc-client irc-client-unix kdf.hkdf=1.0.0 kdf.pbkdf=1.0.0 ladspa=0.2.2 lame=0.3.7 lastfm=0.3.4 lilv=0.2.0 liquidsoap-lang=2.3.0 liquidsoap-lang.console=2.3.0 liquidsoap_alsa=rolling-release-v2.3.x-12-gef2a2db liquidsoap_ao=rolling-release-v2.3.x-12-gef2a2db liquidsoap_bjack=rolling-release-v2.3.x-12-gef2a2db liquidsoap_builtins=rolling-release-v2.3.x-12-gef2a2db liquidsoap_core=rolling-release-v2.3.x-12-gef2a2db liquidsoap_dssi=rolling-release-v2.3.x-12-gef2a2db liquidsoap_faad=rolling-release-v2.3.x-12-gef2a2db liquidsoap_fdkaac=rolling-release-v2.3.x-12-gef2a2db liquidsoap_ffmpeg=rolling-release-v2.3.x-12-gef2a2db liquidsoap_flac=rolling-release-v2.3.x-12-gef2a2db liquidsoap_frei0r=rolling-release-v2.3.x-12-gef2a2db liquidsoap_gd=rolling-release-v2.3.x-12-gef2a2db liquidsoap_irc=rolling-release-v2.3.x-12-gef2a2db liquidsoap_ladspa=rolling-release-v2.3.x-12-gef2a2db liquidsoap_lame=rolling-release-v2.3.x-12-gef2a2db liquidsoap_lastfm=rolling-release-v2.3.x-12-gef2a2db liquidsoap_lilv=rolling-release-v2.3.x-12-gef2a2db liquidsoap_lo=rolling-release-v2.3.x-12-gef2a2db liquidsoap_mad=rolling-release-v2.3.x-12-gef2a2db liquidsoap_ndi=rolling-release-v2.3.x-12-gef2a2db liquidsoap_ogg=rolling-release-v2.3.x-12-gef2a2db liquidsoap_ogg_flac=rolling-release-v2.3.x-12-gef2a2db liquidsoap_optionals=rolling-release-v2.3.x-12-gef2a2db liquidsoap_opus=rolling-release-v2.3.x-12-gef2a2db liquidsoap_osc=rolling-release-v2.3.x-12-gef2a2db liquidsoap_oss=rolling-release-v2.3.x-12-gef2a2db liquidsoap_portaudio=rolling-release-v2.3.x-12-gef2a2db liquidsoap_posix_time=rolling-release-v2.3.x-12-gef2a2db liquidsoap_prometheus=rolling-release-v2.3.x-12-gef2a2db liquidsoap_pulseaudio=rolling-release-v2.3.x-12-gef2a2db liquidsoap_runtime=rolling-release-v2.3.x-12-gef2a2db liquidsoap_samplerate=rolling-release-v2.3.x-12-gef2a2db liquidsoap_sdl=rolling-release-v2.3.x-12-gef2a2db liquidsoap_sdl_log_level=rolling-release-v2.3.x-12-gef2a2db liquidsoap_shine=rolling-release-v2.3.x-12-gef2a2db liquidsoap_soundtouch=rolling-release-v2.3.x-12-gef2a2db liquidsoap_speex=rolling-release-v2.3.x-12-gef2a2db liquidsoap_sqlite=rolling-release-v2.3.x-12-gef2a2db liquidsoap_srt=rolling-release-v2.3.x-12-gef2a2db liquidsoap_ssl=rolling-release-v2.3.x-12-gef2a2db liquidsoap_stereotool=rolling-release-v2.3.x-12-gef2a2db liquidsoap_theora=rolling-release-v2.3.x-12-gef2a2db liquidsoap_tls=rolling-release-v2.3.x-12-gef2a2db liquidsoap_vorbis=rolling-release-v2.3.x-12-gef2a2db liquidsoap_xmlplaylist=rolling-release-v2.3.x-12-gef2a2db liquidsoap_yaml=rolling-release-v2.3.x-12-gef2a2db lo=0.2.0 logs=0.7.0 logs.fmt=0.7.0 logs.lwt=0.7.0 lwt=5.7.0 lwt.unix=5.7.0 macaddr=5.6.0 mad=0.5.3 magic-mime=1.3.1 mem_usage=0.1.1 memtrace=0.2.3 menhirLib=20231231 metadata=0.3.0 mirage-crypto=1.1.0 mirage-crypto-ec=1.1.0 mirage-crypto-pk=1.1.0 mirage-crypto-rng=1.1.0 mirage-crypto-rng.unix=1.1.0 mm=0.8.6 mm.audio=0.8.6 mm.base=0.8.6 mm.image=0.8.6 mm.midi=0.8.6 mm.video=0.8.6 ndi=rolling-release-v2.3.x-12-gef2a2db ocplib-endian ocplib-endian.bigstring ogg=0.7.4 ogg.decoder=0.7.4 ohex opus=0.2.3 opus.decoder=0.2.3 osc osc-unix parsexp=v0.16.0 portaudio=0.2.3 posix-base=5a7f328 posix-socket=5a7f328 posix-socket.constants=5a7f328 posix-socket.stubs=5a7f328 posix-socket.types=5a7f328 posix-time2=5a7f328 posix-time2.constants=5a7f328 posix-time2.stubs=5a7f328 posix-time2.types=5a7f328 posix-types=5a7f328 posix-types.constants=5a7f328 ppx_compare.runtime-lib=v0.16.0 ppx_hash.runtime-lib=v0.16.0 ppx_sexp_conv.runtime-lib=v0.16.0 prometheus=1.2 prometheus-app=1.2 ptime=1.1.0 ptime.clock.os=1.1.0 pulseaudio=0.1.6 re=1.11.0 result=1.5 rresult=0.7.0 samplerate=0.1.7 saturn_lockfree=0.4.1 sedlex=3.2 seq=[distributed with OCaml 4.07 or above] sexplib=v0.16.0 sexplib0=v0.16.0 shine=0.2.3 soundtouch=0.1.9 speex=0.4.2 speex.decoder=0.4.2 sqlite3=5.1.0 srt=0.3.1 srt.constants=0.3.1 srt.stubs=0.3.1 srt.stubs.locked=0.3.1 srt.types=0.3.1 ssl=0.7.0 stdlib-shims=0.3.0 stereotool=rolling-release-v2.3.x-12-gef2a2db str=[distributed with Ocaml] stringext=1.6.0 theora=0.4.1 theora.decoder=0.4.1 threads=[distributed with Ocaml] threads.posix=[internal] tls=1.0.2 tsdl=v1.0.0 tsdl-image=0.5 tsdl-ttf=0.6 unix=[distributed with Ocaml] unix-errno=52c6ecb unix-errno.errno_bindings=52c6ecb unix-errno.errno_types=52c6ecb unix-errno.errno_types_detected=52c6ecb unix-errno.unix=52c6ecb uri=4.4.0 uri-sexp=4.4.0 uri.services=4.4.0 vorbis=0.8.1 vorbis.decoder=0.8.1 x509=1.0.5 xmlm=1.4.0 xmlplaylist=0.1.5 yaml=3.2.0 yaml.bindings=3.2.0 yaml.bindings.types=3.2.0 yaml.c=3.2.0 yaml.ffi=3.2.0 yaml.types=3.2.0 zarith=1.13
2024/11/21 11:07:51 [main:3] 
2024/11/21 11:07:51 [main:3] DISCLAIMER: This version of Liquidsoap has been compiled from a snapshot of the
2024/11/21 11:07:51 [main:3] development code. As such, it should not be used in production unless you know
2024/11/21 11:07:51 [main:3] what you are doing!
2024/11/21 11:07:51 [main:3] 
2024/11/21 11:07:51 [main:3] We are, however, very interested in any feedback about our development code and
2024/11/21 11:07:51 [main:3] committed to fix issues as soon as possible.
2024/11/21 11:07:51 [main:3] 
2024/11/21 11:07:51 [main:3] If you are interested in collaborating to the development of Liquidsoap, feel
2024/11/21 11:07:51 [main:3] free to drop us a mail at <savonet-devl@lists.sf.net> or to join the slack chat
2024/11/21 11:07:51 [main:3] at <http://slack.liquidsoap.info>.
2024/11/21 11:07:51 [main:3] 
2024/11/21 11:07:51 [main:3] Please send any bug report or feature request at
2024/11/21 11:07:51 [main:3] <https://github.com/savonet/liquidsoap/issues>.
2024/11/21 11:07:51 [main:3] 
2024/11/21 11:07:51 [main:3] We hope you enjoy this snapshot build of Liquidsoap!
2024/11/21 11:07:51 [main:3] 
2024/11/21 11:07:51 [clock:3] Using native (high-precision) implementation for latency control
2024/11/21 11:07:52 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz main.
2024/11/21 11:07:52 [frame:3] Video frame size set to: 1280x720
2024/11/21 11:07:52 [frame:3] Targeting 'frame.duration': 0.02s = 882 ticks.
2024/11/21 11:07:52 [main:3] User script loaded in 1.02 seconds.
2024/11/21 11:07:52 [sandbox:3] Sandboxing disabled
2024/11/21 11:07:52 [startup:3] DSSI plugins registration: 0.00s
2024/11/21 11:07:52 [startup:3] FFmpeg filters registration: 0.04s
2024/11/21 11:07:52 [startup:3] FFmpeg bitstream filters registration: 0.00s
2024/11/21 11:07:52 [startup:3] Loading lilv plugins from cache!
2024/11/21 11:07:52 [startup:3] Lilv plugins registration: 0.00s
2024/11/21 11:07:52 [startup:3] Frei0r plugin registration: 0.00s
2024/11/21 11:07:52 [startup:3] Loading LADSPA plugins from cache!
2024/11/21 11:07:52 [startup:3] LADSPA plugins registration: 0.03s
2024/11/21 11:07:52 [startup:3] main script hash computation: 0.06s
2024/11/21 11:07:52 [startup:3] Loading main script from cache!
2024/11/21 11:07:52 [startup:3] main script cache retrieval: 0.13s
2024/11/21 11:07:52 [startup:3] Evaluating main script: 0.43s
2024/11/21 11:07:52 [clock:3] Starting clock generic with 22 source(s) and sync: auto
2024/11/21 11:07:52 [clock:3] Starting clock generic.child.child with 29 source(s) and sync: passive
2024/11/21 11:07:52 [error_jingle:3] Content type is {audio=pcm(stereo)}.
2024/11/21 11:07:52 [error_jingle:3] annotate:liq_disable_autocue="true":/var/azuracast/stations/time_twister_fm/config/fallback.ogg is static, resolving once for all...
2024/11/21 11:07:52 [autocue.metadata:2] Override metadata detected for /var/azuracast/stations/time_twister_fm/config/fallback.ogg, disabling autocue!
2024/11/21 11:07:52 [server:3] Socket created at /var/azuracast/stations/time_twister_fm/config/liquidsoap.sock.
2024/11/21 11:07:52 [video.converter:3] Using preferred video converter: ffmpeg.
2024/11/21 11:07:52 [audio.converter:3] Using samplerate converter: libsamplerate.
2024/11/21 11:07:52 [video.text:3] Using sdl implementation
2024/11/21 11:07:54 [request:2] There are currently 100 RIDs, possible request leak! Please check that you don't have a loop on empty/unavailable requests.
2024/11/21 11:07:55 [request:2] There are currently 200 RIDs, possible request leak! Please check that you don't have a loop on empty/unavailable requests.
```

The two lines at the end just repeat over and over - looking back through previous logs, it looks like it gets up to 2600 RIDs before restarting itself.

**Comment by BusterNeece** [comment]
@LunarLoony I don't think changing the domain name caused any trouble you're experiencing there. I also think you're on the Rolling Release channel rather than Stable, since it appears you're on Liquidsoap 2.3.x.

I've relayed your error over to the Liquidsoap folks and we'll see if we can't figure out what's going on.

**Comment by LunarLoony** [comment]
Yes - sorry, should've made that clearer. I did update to Stable in the first instance, and switched to Rolling to see if that'd solve the issue. Same thing either way.

**Comment by BusterNeece** [comment]
@LunarLoony you were getting that same RID error even on 0.20.3 stable? But the queue was actually present if you looked at the Upcoming Queue, it was just not requesting them?

**Comment by BusterNeece** [comment]
@LunarLoony Since we haven't made any DB changes after 0.20.3, you can switch back to the Stable channel right now if you wanted with no ill effects; if you don't mind, could you switch back and confirm what's causing the trouble there via logs if possible?

**Comment by BusterNeece** [comment]
@LunarLoony Oh, that's quite bizarre...you definitely shouldn't be on Liquidsoap 2.3.0 on our stable branch. Can you confirm it _says_ you're on the stable branch in the footer of the site? You may need to restart the container.

I'm a little worried we had some wires get crossed in our build process and it built and packaged the `rolling` branch and shipped it out to `stable`...somehow. That would 100% explain some of the problems...will investigate.

**Comment by LordHelmchen666** [comment]
Hi Buster. I am trying to help  to track down the issue. But i am no skilled programmer so please be kind with me. :)
I am playing around with latest RR #[a360ea6](https://github.com/AzuraCast/AzuraCast/commit/a360ea68a0891f5d720b81b0c3e42e94853ce906) (2024-11-20 16:51). I get something similar when i go to "Restart Broadcast" and click "Reload Configuration".
In the GUI it reports "Liquidsoap - Running": But in console using `top` i see no liquidsoap process is running. Using iotop -o i see queue process is constantly running causing high I/O. Any idea how to find more information (logs) to find the reason why? 
LS just stops logging.
Azuracast Application Log and Now Playing Log (message repeated many times)
```
[2024-11-21T15:58:17.731054+00:00] AzuraCast.WARNING: Request returned status code 400. {"body":""} {"station":{"id":1,"name":"Eisradio"}}
[2024-11-21T15:58:17.742959+00:00] AzuraCast.ERROR: No track to update. {"exception":"[object] (RuntimeException(code: 0): No track to update. at /var/azuracast/www/backend/src/Entity/Repository/SongHistoryRepository.php:79)"} {"station":{"id":1,"name":"Eisradio"}}
```
Synchronised Task Logs - File not found.
Other Logs looking normal.

> [!NOTE] 
>Restarting Liquidsoap and everything works normally.
For now i leave my testing server in this state. So if you need more logs just tell me.

![Screenshot_20241121_165508](https://github.com/user-attachments/assets/6bd4ec65-850f-4a54-ad0e-5d6377652f12)
![Screenshot_20241121_165556](https://github.com/user-attachments/assets/239ab1b8-3fab-437b-8b2d-7d14dd39753a)

**Comment by LunarLoony** [comment]
> @LunarLoony Oh, that's quite bizarre...you definitely shouldn't be on Liquidsoap 2.3.0 on our stable branch. Can you confirm it _says_ you're on the stable branch in the footer of the site? You may need to restart the container.
> 
> I'm a little worried we had some wires get crossed in our build process and it built and packaged the `rolling` branch and shipped it out to `stable`...somehow. That would 100% explain some of the problems...will investigate.

It says AzuraCast v0.20.3 Stable on the site footer - can confirm.

![image](https://github.com/user-attachments/assets/ca94abab-90af-46d4-b2fd-25a0b9ebfc84)

> Hi Buster. I am trying to help to track down the issue. But i am no skilled programmer so please be kind with me. :) I am playing around with latest RR #[a360ea6](https://github.com/AzuraCast/AzuraCast/commit/a360ea68a0891f5d720b81b0c3e42e94853ce906) (2024-11-20 16:51). I get something similar when i go to "Restart Broadcast" and click "Reload Configuration". In the GUI it reports "Liquidsoap - Running": But in console using `top` i see no liquidsoap process is running. Using `iotop -o` i see queue process is constantly running causing high I/O. Any idea how to find more information (logs) to find the reason why? LS just stops logging.

Thought I'd check this too and see if it makes a difference. In btop, I can see a few Liquidsoap processes running (and using quite high CPU!) - not much in the way of disk I/O, though.

![image](https://github.com/user-attachments/assets/74fdeee6-1ae2-4597-8890-0e92368689d3)

![image](https://github.com/user-attachments/assets/dfc6f1de-c9f3-4dc5-a2ee-5b47ad5de249)


No joy from restarting Liquidsoap within the GUI.

![image](https://github.com/user-attachments/assets/731d0ef1-b528-400d-a564-8a627d0500b9)

**Comment by n1ce-0ne** [comment]
[just a guy reading along that takes an interest & uses the app]

@LunarLoony 
just wondering how come 4x LS are running anyways, im guessing thats 4x stations running ?
i just checked my btop & i only have 1 LS running barely using anything like yours at the bottom

mine [only 1 station]:
![Screenshot_8](https://github.com/user-attachments/assets/a1d8d91f-c6cb-4a6d-b3f8-81fd7cb5e8ba)
did you try manually killing the other 3 just to see what happens with the station(s) ?


im still running this version & i never have any issues, but i only run it at a basic setup, 
LiquidSoap is currently shuffling from 281 uploaded songs and 1 playlist. (some of these are recorded shows upto 3-4-5 h long)
Rolling Release #[a4bf4b6](https://github.com/AzuraCast/AzuraCast/commit/a4bf4b6655603f8a587400ca59fd05e3dd09c187) (2024-03-10 13:57) • Docker • PHP 8.3

**Comment by LunarLoony** [comment]
> @LunarLoony just wondering how come 4x LS are running anyways, im guessing thats 4x stations running ? i just checked my btop & i only have 1 LS running barely using anything like yours at the bottom

Four stations is correct! For what it's worth, I have also tried it with just one station (as stated above, from a completely fresh install). I also tried terminating the extra liquidsoap processes, but they just immediately respawned and started chewing up the CPU again.

**Comment by n1ce-0ne** [comment]
@LunarLoony is it possible to install old versions ?
if so you should try an older version for now at least,
im on Rolling Release #[a4bf4b6](https://github.com/AzuraCast/AzuraCast/commit/a4bf4b6655603f8a587400ca59fd05e3dd09c187) (2024-03-10 13:57) and its sweet but yea i dunno if that even possible, if it is i'd recommend it :)

**Comment by BusterNeece** [comment]
@LunarLoony @n1ce-0ne I'd recommend updating to the latest stable (0.20.4) or the latest Rolling Release. Both have rolled back the scheduler code, and the Rolling Release also incorporates other fixes that bring us to a more stable state. Everything appears to be working quite normally in my local installation.
