### ISSUE TITLE
Not sure about the new playlist priority system

### ISSUE THREAD

**Issue by BusterNeece** [AzuraCast/AzuraCast#7575]
### Discussed in https://github.com/AzuraCast/AzuraCast/discussions/7574

<div type='discussions-op-text'>

<sup>Originally posted by **Mozitux** November 22, 2024</sup>
First of all, I would like to thank the maintainers of this repo for their efforts to provide us with a complete, up-to-date and free suite for our webradios.

I recently updated to v0.20.3 Stable on Docker.
The operation of my "Jingles" playlists seems strange.

Applying a higher or lower priority than the music playlist weights does not impact the priority at all. The Jingles playlists are no longer played or without any control over them.

Initially, on the old stable version, the Jingles were played every 2 tracks randomly without repetitions (see attachment), but despite different tests by modifying the priorities and weights of the playlists (which seem to be two different things), I cannot get the jingles to work.

![image](https://github.com/user-attachments/assets/e0ccedb4-8434-4304-8910-67bde400107e)

Is this a known malfunction or a configuration error on my part?

Thank you! 😀</div>

**Comment by BusterNeece** [comment]
@mozitux There have been multiple reports of scheduling problems in 0.20.3 stable. The new scheduler was in Rolling Release for literal months with nobody reporting these problems, so I don't know why they're all popping up now, but it's definitely frustrating for us as developers.

We're working on it, but I've also been on the receiving end of some less-than-kind remarks from users as a result of this trouble, and it has sapped me of much of the desire to work on this feature. Your patience is appreciated.

As a note for all users, you can run:

```bash
./docker.sh rollback 0.20.2
```

to return to that version if needed.

**Comment by Mozitux** [comment]
@BusterNeece Thanks for your quick response

I understand the frustration this generates, and thank you for the workaround!

I will test the rolling release and will revert to the previous version if necessary. I maintain a current backup of my VM in case you need more information and logs regarding this incident.

Good luck

**Comment by gAlleb** [comment]
A bit of OFFTOPIC:

Not sure really where most of the issues come from :) Been running AzuraCast like a madman, changing, experimenting, adding tone of code — and it kept working stably like an indestructible monolith. 

So thanks, Buster!

**Comment by LordHelmchen666** [comment]
Do Not use playlist priority and it should Worm as before.
If you want to use Playlist Priority give your Jingles higher priority than your other Playlists.
For example i use

- Default Playlists 1
- Scheduled Playlists 2
- Syndicated Shows 3
- Jingles, Promos 10
- News 15

**Comment by rolradio** [comment]
Hi, First of all thank you for this great project.

Maybe it can help in the search why the playlists "x per" did not play.
Not even after the update.

I noticed that in the 'special cue' settings of the mp3 values ​​with -1 were added in the tags.
These were put in the tags of the song so that after the update from 20.3 to 20.4 they could not work.
By manually emptying these 4 fields it worked again.

![custom cue](https://github.com/user-attachments/assets/87120dfa-a59b-47e8-98b0-ab1824064f3f)

**Comment by BusterNeece** [comment]
@rolradio Good catch; if you've used an earlier version of AzuraCast that cached these AutoCue values in the database, you may have wound up with a cached value that doesn't match what you'd expect it to be (or, in this case, that prevents it from playing entirely). You can clear these fields in bulk by selecting tracks in the Media Manager, clicking the "More" dropdown at the top of the page, and clicking "Clear Extra Metadata", which will only clear the amplify/AutoCue data and none of the other metadata.

**Comment by BusterNeece** [comment]
Closing this issue; if you're experiencing an issue with your AutoCue (cue-in/out, fade-in/out, etc) values in AzuraCast being `-1` or some other erroneous value, this script contributed by community member RM-FM should resolve this:
https://github.com/AzuraCast/AzuraCast/discussions/7563

Newer versions of AzuraCast don't write AutoCue data back to the files themselves, so this shouldn't continue to be an issue moving forward.
