### ISSUE TITLE
AutoDJ can't start after updating; liquidsoap.liq not found

### ISSUE THREAD

**Issue by iceeburr** [AzuraCast/AzuraCast#7577]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #57d6649 (2024-11-23 18:09)

### What happened?

After updating to the latest version the radio suddenly broke. After utilizing my last 2 brain cells I came to the conclusion that the AutoDJ service failed to start. Pressing the start or restart buttons gives an error: "An error occurred and your request could not be completed." Liquidsoap logs below, the default configuration hasn't been altered. Those weird numbers in the path are supposed to be the letter codes for "non standard" letters (in my case that's Japanese) though I don't think it's relevant as it worked just fine before and probably used the same links. Another strange thing I found is that this isn't the only "file not found" error. Going to `radio.com/admin/logs` and trying click "AutoCue Liquidsoap Functions" at `/var/azuracast/liquidsoap/autocue.liq` shows an empty file with a "File not found." error. Again I have no idea if this is relevant or not, just mentioning it.

Everything else seems to be working other than Liquidsoap. I can't name the commit or version that I was on before the update, but if remember correctly I was "39 commits behind". Let me know if any other information is needed. I hope it's an easy fix.

### Relevant log output

```shell
At line 1, char 0-114:

Error 14: Uncaught runtime error: type: not_found,
message: "File not found! Given path: /var/azuracast/stations/iceeburr_\\227\\129\\174\\227\\131\\169\\227\\130\\184\\227\\130\\170/config/liquidsoap.liq",
stack: at line 1, char 0-114
```

**Comment by BusterNeece** [comment]
@iceeburr Well, the Unicode characters may be causing trouble, but you're right that it's unusual that it would start causing trouble now if it hasn't been before.

If you visit the `Broadcasting` tab, then `Edit Liquidsoap Configuration` page, do you have any custom Liquidsoap code there? Does that page render correctly without anything unusual?

**Comment by iceeburr** [comment]
I can try and change those to normal English characters and see what happens. I'll let you know when I do. Also as I said I haven't changed anything in the default Liquidsoap configuration. The file does show up and there is nothing unusual.
![image](https://github.com/user-attachments/assets/4cbe403d-36d7-4faa-8fbd-83ea8cc899ba)
![image](https://github.com/user-attachments/assets/b346c615-c1a4-4238-a9e5-083cb9f698cc)

**Comment by iceeburr** [comment]
I made a new radio station and there are no issues now. It is indeed strange, but I will try to rename everything in the original radio and see how it goes there.

**Comment by iceeburr** [comment]
Another quick update. Just cloned the radio with all clone options enabled. Only changed the name which also generated a new short link with a new path. It might actually be caused by the weird characters... Is there a way to change the path/name without cloning the radio? Including the media storage location & etc., just in case. It's weird that the media is there and does work, but Liquidsoap can't find its file.

![image](https://github.com/user-attachments/assets/9569458a-4105-49cd-b72b-0acff1123da2)

**Comment by BusterNeece** [comment]
@iceeburr Yeah, just disable broadcasting to spin down the services, save changes, then go back and edit the station base dir, then go into System Admin and Storage Locations and edit those paths too, then re-enable broadcasting on the station profile. It's a bit of a pain, but we generally intend those short paths to be more immutable.

It's probably worth leaving a test station around though with the Unicode characters, since we might need some help testing any fixes relating to it.

**Comment by iceeburr** [comment]
I guess that resolves the issue. Also I accidentally wiped all the songs I uploaded, ooopss...
Will close the issue in a few moments when I confirm the radio is not glitching again. Just uploading a few songs to test and see how it goes.

**Comment by iceeburr** [comment]
For anyone reading this in the future:
* Try to rename your short URL to something with standard English characters
* Media storage or any other paths in the URL to have normal characters
* If your radio name has non standard characters then don't let it auto-generate the configuration and manually set it to something else yourself.
