### ISSUE TITLE
Can not set a password for each different fixture

### ISSUE THREAD

**Issue by wacxiuz** [AzuraCast/AzuraCast#758]
Hello,
I do not use your user creation system because I have 4 mount points that they switch to when one does not work anymore. I put a user and a password by editing. (Option JSON)
Line: 
<username>user</username>
<password>password</password>

The user is different for each editing but when I give the password I want for each user in the config file, it automatically gives me the default mount point.

Thank you

**Comment by SlvrEagle23** [comment]
@wacxiuz I'm not sure what you mean. Are you specifying the username/password in the "custom mount point configuration" section of the mount point itself? This should generate a mount point with custom authentication.

**Comment by wacxiuz** [comment]
I'm using the Icecast 2.4 broadcast service because the remote radio mode does not work when I create a mount point because there is a "#"
