### ISSUE TITLE
extra metadata with wrong values

### ISSUE THREAD

**Issue by DAMaia1989** [AzuraCast/AzuraCast#7582]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #add8ee6 (2024-11-26 13:47)

### What happened?

hi, i  think the problem of the wrong values ​​that LS associates with each songs has reappeared. After the latest updates, some songs started not playing again, so I check these strange values ​​when exporting to csv.

![-1](https://github.com/user-attachments/assets/772c1e1f-1b46-4d57-bf94-25c4dfa83352)

I've already tried to clear all extra metadata but the problem persists

**Comment by BusterNeece** [comment]
@DAMaia1989 It seems you were affected by an issue with AutoCue on earlier versions of AzuraCast; there's a script contributed by the community specifically to remove the metadata from the files themselves (so it won't reappear in our own metadata once the files are reprocessed): https://github.com/AzuraCast/AzuraCast/discussions/7563

**Comment by DAMaia1989** [comment]
Hi @BusterNeece  i used the script to remove the metadata and it said "No tags to be removed in xxxxx.mp3" in all tags. 
Azuracast still assuming -1 -1 -1 on almost all tracks

**Comment by BusterNeece** [comment]
@DAMaia1989 Try updating to the latest Rolling Release and then clearing the metadata again. I've added some checks that should prevent the `-1` values from ever being set on the media once it's cleared, so even if it's somehow written itself to the file in that state it won't persist.

**Comment by DAMaia1989** [comment]
It looks like it's perfect now. in the csv file there is no record with -1 and no other track was "skipped". thank you so much @BusterNeece !

**Comment by BusterNeece** [comment]
Good to hear! :)
