### ISSUE TITLE
Liquidsoap doesn't start + station base directory issue + icecast/shoutcast adminpage 404

### ISSUE THREAD

**Issue by vineettalwar** [AzuraCast/AzuraCast#759]
**Installation method**
- I am using the docker variant for the installation method. 

**Host OS (for Docker installations)**

```
$ cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
```

**Describe the bug**
I have created a fresh ec2 instance and simply did setup azuracast on it and figured out multiple issues. 

**1. Icecast and shoutcast Admin page** 
I have configured port 8410-8412 to use for streaming and opened port using aws security groups. 
Now from backend it shows admin link as following. 
https://example.com/radio/8410/admin/
While opening that link it ** shows 404 not found**. 
Event though icecast shows its running.

**2. Liquid Soap never starts** If I click on start button for liquid soap it gives following **error**
`SPAWN_ERROR: station_1:station_1_backend`

**3. Music Files:** While clicking on Music files it shows
`{"error":{"code":404,"msg":"File or Directory Not Found"}}`

**4.  Base directory not found on docker**
Im backend, It shows base directory as 
`/var/azuracast/stations/teststation`

But after ssh to docker it doesn't find this base directory. 
```
$ docker ps  (getting volume id)
$ docker exec -it <volumename> /bin/bash
bash-4.4# cd /var/azuracast/stations/
bash: cd: /var/azuracast/stations/: No such file or directory
```
But, then I found out the station folder here.
`/home/azuracast/stations/teststation`

Now, to upload the music,  media folder field for station. 
as `music`

I am guessing the music location then should be
`/home/azuracast/stations/teststation/music`

**Now to upload the Music,** 
`5. SFTP Spin up:` When I am doing SFTP Spin up as suggested [here](https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md)

```
docker run --rm \
>     -v azuracast_station_data:/home/azuracast/stations \
>     -p 2222:22 atmoz/sftp:alpine \
>     azuracast:4zur4c457:::stations
docker: Error response from daemon: driver failed programming external connectivity on endpoint angry_mcclintock (8b6c6cf021ec94b632fc093abc8f96ec9612f669c0687abb59074bdeb8ceaaff): Bind for 0.0.0.0:2222 failed: port is already allocated.
ERRO[0000] error waiting for container: context canceled
```
 When I change 2222 to 2224 or +1 -1 port SFTP spin up works.

**6. Uploading music + 403 on Files Page** 
Now uploaded the music in 
`/home/azuracast/stations/teststation/music`

using SFTP. Then, in the backend clicked. Music Files.. It still shows

`{"error":{"code":404,"msg":"File or Directory Not Found"}}`

**7. Shoutcast Admin 404**
Checked with shoutcast as well, the admin page shows 404
**https://example.com/radio/8410/admin.cgi**

**To Reproduce**
Please test the instance on amazon ec2 linux

**Expected behavior**
1. Base directory should be correct, shows different.
2. music files should be detectable from backend.
3. liquidsoap should be able to start.

**Comment by SlvrEagle23** [comment]
@vineettalwar Please limit GitHub issues to "one issue per Issue", please, as it is not possible for me to track the individual progress of each of these sub-issues as straightforwardly as if they were standalone issues.

I have heard reports of numerous issues like this when trying to deploy AzuraCast to Amazon EC2 instances, and unfortunately I haven't been able to devote the necessary time to research these issues and develop AWS-specific installation instructions. I have also heard sporadic reports of issues with CentOS/RHEL/Fedora installations using the Docker install method, but I haven't been able to track down the cause of those issues, and others seem to be running on those host OSes without issue.

AzuraCast, unlike many projects sharing its popularity, is still a single-developer project that requires huge portions of my personal time to diagnose and resolve issues. I am not paid for this work, and as a result I struggle significantly to pay basic living expenses, the stress of which makes working on the project that much harder. I will take a look at these issues as soon as I am able, but your patience is appreciated.
