### ISSUE TITLE
Support BlueSky Social Media posts

### ISSUE THREAD

**Issue by BusterNeece** [AzuraCast/AzuraCast#7597]
### Discussed in https://github.com/AzuraCast/AzuraCast/discussions/7596

<div type='discussions-op-text'>

<sup>Originally posted by **t0mtaylor** December  1, 2024</sup>
Support BlueSky Social Media auto posts with now playing information

https://docs.bsky.app/docs/advanced-guides/posts</div>

**Comment by mdrxy** [comment]
May be worth adding [the profile](https://bsky.app/profile/azuracast.com) to the repo README

**Comment by t0mtaylor** [comment]
Amazing work @BusterNeece - thank you for adding the BlueSky Posting support :)

I shall give this new feature within the RR a test soon!
