### ISSUE TITLE
Station stops playing unexpectedly

### ISSUE THREAD

**Issue by DJMic** [AzuraCast/AzuraCast#7598]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #cd36074 (2024-11-30 0:26)

### What happened?

My station has crashed without any apparent reason.
It's the second time in 2 days.
I have seen this into log's liquidsoap (I don't know if it's the reason) :
![image](https://github.com/user-attachments/assets/4740f2d6-fa7a-49d5-b383-190579fcab6b)

After this, my station stopped playing.

**Comment by BusterNeece** [comment]
@DJMic This is likely an issue with Liquidsoap, you may want to create an issue over on their repo here: https://github.com/savonet/liquidsoap

**Comment by DJMic** [comment]
Thanks, I'm closing this issue to create one over their Github.
