### ISSUE TITLE
No data from nowplaying SSE or WebSockets

### ISSUE THREAD

**Issue by joemcmahon** [AzuraCast/AzuraCast#7604]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #e560f07 (2024-11-22 18:02) • Docker • PHP 8.3

### What happened?

No output from either SSE or WebSocket nowplaying API, but direct access to API works.

### Relevant log output

```shell
Output from WebSocket endpoint:

ubscription message sent: {"subs":{"station:1":{}}}
["connect": {
    client = "eda818ff-bcf6-4f1d-8f0b-bd10fed9028c";
    ping = 25;
    session = "ab82be59-bfbb-45e9-9e49-d7f715ba8904";
    subs =     {
        "station:1" =         {
            epoch = 1732495578;
            positioned = 1;
            recoverable = 1;
        };
    };
    time = 1733343446594;
    version = "0.0.0";
}]
[:]
[:]
[:]
[:]
[:]
[:]

Note no data.
```

**Comment by gAlleb** [comment]
Seems like a first response from Centrifugo. If you want your data to be recovered on connect you might want to send this:

```
{"subs":{"station:1":{"recover": true}}}
```

instead of 

```
{"subs":{"station:1":{}}}

**Comment by joemcmahon** [comment]
I have tried that as well, and still receive the null responses.

**Comment by BusterNeece** [comment]
@joemcmahon A few versions back, we switched the high-performance nowplaying to use station short-codes (i.e. `azuratest_radio`) instead of station numeric IDs, in an attempt to remove the numeric IDs from any public-facing API calls. It should work fine if you swap the numeric ID out for the short name.

**Comment by joemcmahon** [comment]
I'll try it out tomorrow, thanks!

**Comment by joemcmahon** [comment]
Yes, that was it! Using the proper shortcode gets me excellent data from the API now. Closing.
