### ISSUE TITLE
Cannot move more than one media folder without page refresh

### ISSUE THREAD

**Issue by batsonjay** [AzuraCast/AzuraCast#7608]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #bc976f3 (2024-06-28 20:15)

### What happened?

Steps to reproduce:
- Visit Media section. Assume > 3 folders in that section, named A, B & C for this example
- Select the checkbox adjacent to A
- Use the "Move" button to move folder A to become a subfolder under B. AzC presents a modal dialog to allow selection of B as the destination. In this sequence, it will show the "root" folder of the Media section. Click folder B in order to indicate the destination. (The dialog changes to show the contents of folder B.) Complete the move by clicking the button "Move to Directory".
- Next, from the root folder of Media, select the checkbox for folder C
- Use the Move button to attempt to move it under B.

At this point, several things are happening that are likely bugs:
1) When AzC presents the modal dialog, it (still) shows the contents of folder B, which is likely cached (or ...) from the end of the previous action (which was showing the contents of folder B when the previous move was being completed). This should likely not be the case, since this action was started from the root folder of Media. It should show the root folder - or at least the folder that was displayed when the Move action was initiated.
2) Using the "Back" button to attempt to have that modal display the previous (root, in this case) directory does nothing.
3) If the user simply clicks the "Move to directory" while the contents of B are shown, the desired folder (C) is NOT moved.

The only way to move folder C is to return to the Media root folder, reload the page (in the browser), and perform the move.

**Comment by BusterNeece** [comment]
This should now be fully resolved in the Rolling Release.
