### ISSUE TITLE
does not import locale

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#761]
> [root@web-zones AzuraCast]# docker-compose run --rm cli azuracast_cli locale:import
Starting azuracast_influxdb_1 ...
Starting azuracast_influxdb_1 ... done
Starting azuracast_redis_1 ... done
Starting azuracast_mariadb_1 ... done
Starting azuracast_web_1 ... done
2018/08/31 09:45:51 Waiting for: tcp://mariadb:3306
2018/08/31 09:45:51 Waiting for: tcp://influxdb:8086
2018/08/31 09:45:51 Connected to tcp://influxdb:8086
2018/08/31 09:45:51 Connected to tcp://mariadb:3306
Locales imported.
2018/08/31 09:45:51 Command finished successfully.

But the language file is not updated with the language.

**Comment by SlvrEagle23** [comment]
@susl16c The `locale:import` function does not add untranslated strings to the other .po files, it converts the already translated .po files from other languages into their PHP counterparts, so AzuraCast can use them. It's only for use when your translations are complete and being "imported" into the system.

This is partly why we use CrowdIn, because they automatically pull all strings from the main translation and allow you to supply translations for each of them, without needing to keep those other .po files synchronized with the strings in the main one.

**Comment by susl16c** [comment]
I finished the translation in a file. I downloaded it where the translation is and used to execute the command above and everything was added to the PHP file but now it does not work, all the files with the translation were updated, and they changed the date when I executed the command, now it does not work.
[default.zip](https://github.com/AzuraCast/AzuraCast/files/2344507/default.zip)
Here is my translation file, you can try it for yourself.

**Comment by susl16c** [comment]
How can I manually generate a translation?

**Comment by susl16c** [comment]
This is not the first time I've done this, and I'm doing everything since you write, but translations are not imported, I put the translation in a folder with my own language, I execute the command above and nothing changes in the translation folders, they were updated before and when the compilation took place files changed the date, after your changes and hyphens, nothing is imported. All that you wrote I did the result 0.

**Comment by SlvrEagle23** [comment]
@susl16c Is it a language that AzuraCast normally supports? If not, you'll want to update `/config/settings.php` and edit the supported locales before importing the new one.

**Comment by susl16c** [comment]
I come here /resources/locale/ru_RU.UTF-8/LC_MESSAGES/ I copy the file there.
I execute the command (docker-compose run --rm cli azuracast_cli locale: import )

**Comment by susl16c** [comment]
Thank you very much, now everything works as before.

**Comment by SlvrEagle23** [comment]
@susl16c Good! Thank you for your patience.
