### ISSUE TITLE
Autoupdate the Azuracast

### ISSUE THREAD

**Issue by ohld** [AzuraCast/AzuraCast#762]
@SlvrEagle23 
Being a user of Azuracast, I'm interested in all improvements and new features. That is why I want to have Azuracast autoupdate.

What is the best way to do it? Is just `crontab` a nice variant or you can add a special scheduled job inside Azuracast itself?

Thanks.

**Comment by SlvrEagle23** [comment]
@ohld I wouldn't say I'm confident enough yet that updates will always proceed without issue that I would recommend an auto-updating setup for radio stations running in production environments. For test radio stations, it's probably safe to do as you described and have a nightly crontab task that runs the traditional or docker update scripts.

**Comment by ohld** [comment]
Thanks.
