### ISSUE TITLE
Can somebody get back to me about the embed issue please?

### ISSUE THREAD

**Issue by JKRONIN** [AzuraCast/AzuraCast#7628]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

<img width="754" alt="Screenshot 2024-12-18 at 17 22 13" src="https://github.com/user-attachments/assets/ea7f6a78-2905-4745-a686-28f50f6fe7f5" />
<img width="535" alt="Screenshot 2024-12-18 at 17 22 22" src="https://github.com/user-attachments/assets/a4d96939-86d7-466b-a436-dfc1916189a0" />
As you can see, the artwork returned on the embedded player does not match the default artwork i have set

https://github.com/AzuraCast/AzuraCast/issues/7626

**Comment by Vaalyn** [comment]
You already have an issue about this topic open, you don't need to create another one.

**Comment by JKRONIN** [comment]
Ok thank you for the clarification. Could I get some assistance on that please? its very confusing. Its only the embedded player that is returning random artwork. I cant edit the player myself.
