### ISSUE TITLE
Frequent interruptions music to the player

### ISSUE THREAD

**Issue by C0dyGary** [AzuraCast/AzuraCast#7629]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

0.20.4

### What happened?

some times when playing music the sending is cut off, but the transmission is not affected, there is no error but it continues sending the music or transmission data, but there is no sound, I don't know why this happens, if you could help me, this is the playlist, in the normal radio stations, that is to say that the mp3 that is downloaded continues downloading but without sound, and after a while it comes back. my connection is stable, the sound of my listeners also cuts off.

**Comment by BusterNeece** [comment]
@C0dyGary You listed a stable version but said you're on the Rolling Release. If you're on the Stable channel, try switching to the Rolling Release and let me know if it's fixed.

If not, please include additional logs (especially logs from Liquidsoap), accessible via the left sidebar of the station menu under the "Logs" item.
