### ISSUE TITLE
Evaluate building a YuNoHost manifest

### ISSUE THREAD

**Issue by SlvrEagle23** [AzuraCast/AzuraCast#766]
YuNoHost allows packages to be included in their hosting distribution simply by providing a JSON manifest file and a series of shell scripts for installation, updating, backup/restore and removal. These scripts largely already exist for AzuraCast and could somewhat easily be adopted to fit YuNoHost's architecture.

https://yunohost.org/packaging_apps

https://github.com/YunoHost

**Comment by isAAAc** [comment]
thx @SlvrEagle23 ;)

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38917/support-deployment-via-yunohost
