### ISSUE TITLE
laut.fm

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#767]
Hello,
please Support the laut.fm api.
Please watch there: https://pastebin.com/BPMGZkB9
This script is untested but would be work with laut.fm

**Comment by SlvrEagle23** [comment]
@preterive I'm closing this issue and tagging it as "wontfix", but I want to provide a detailed explanation as to why I'm doing that:

- Laut.fm is not a large service that a majority, or even a significant portion, of AzuraCast users would be using. Building in support for this service would likely confuse the majority of users who don't or can't use laut.fm, and would not be in keeping with the goal of a simple, universally usable software solution.

- Assuming that laut.fm uses Icecast, Shoutcast, or some derivative thereof underneath the hood, there's no reason they can't just expose the native broadcasting software APIs in such a way that AzuraCast could consume them. This is the exact solution AzuraCast takes for other software looking to aggregate our stations: if you can't consume our software's API, we still expose the underlying Shoutcast/Icecast API for direct consumption.

- The code you suggested overwrites the entire functionality of the `Remote` frontend adapter, and does not meet our code quality standards.

I would recommend one of two options for your project: either fork the AzuraCast project and make the necessary changes in your project-specific fork, or contact laut.fm directly and request that they expose the native broadcasting API to the public, which AzuraCast can consume without any modifications needed.

**Comment by preterive** [comment]
There are over 4000 Stations in laut.fm !

**Comment by SlvrEagle23** [comment]
@preterive In the last month, AzuraCast has rolled out a plugin system that will allow you to modify NowPlaying data and retrieve it from whatever source you like, as well as to change listener data independent of the normal Now Playing process.

You can see an example plugin and some examples of events that can be overridden in this repository: https://github.com/AzuraCast/example-plugin

This may be a simple way to build a plugin to support laut.fm for any interested AzuraCast users, without needing to fork AzuraCast itself.
