### ISSUE TITLE
Let's encrypt certificate problem

### ISSUE THREAD

**Issue by Ficreet** [AzuraCast/AzuraCast#768]
**Installation method**
Installation using Docker

**Host OS (for Docker installations)**
Ubuntu 18.04

**Describe the bug**
I use the"./docker.sh letsencrypt-create" command to create the certificate. I follow and complete the steps correctly but once the certificate "creates" when connecting in https the certificate is not compliant. It is self-signed and issued by "localhost". I can't configure the connection correctly in https on my server, which causes me compatibility problems with my site (The player is not displayed because it is not in https unlike the website)
Your help is welcome and I thank you in advance!

**Expected behavior**
I would like my connection to the server in https to be possible, and the "Let's encrypt" certificate to be valid

Thank you in advance for your answers, hoping they will be useful for others as well.
(Ps: I also point out that I have already tried most of the solutions proposed in the Azuracast forums but without success for my part)

**Comment by SlvrEagle23** [comment]
@Ficreet The self-signed certificate is the default one which is used in the absence of a LetsEncrypt certificate being available. The fact that it's still using the self-signed certificate suggests the second step, the "linking" of the cert to nginx, isn't working properly.

Using the script, you are prompted twice for the domain name (once for the LetsEncrypt cert itself, then again to connect it to nginx), correct? Also, make sure that in both cases you aren't adding the domain scheme (https://) to the domain. If you're seeing any errors in this process, please paste them here and let me know.

**Comment by Ficreet** [comment]
Thank you for your answer, after trying what you advised me it still has not worked. So I join you the screen of the result of the command hoping to find the problem (I voluntarily hid parts of the screen, these parts are framed by a grey border)

![image](https://user-images.githubusercontent.com/42917323/44961625-8cb9e580-af14-11e8-8c81-186f072d10c1.png)

**Comment by SlvrEagle23** [comment]
@Ficreet Is AzuraCast currently serving pages on that domain, specifically the `www` subdomain? The challenge is failing because LetsEncrypt is trying to validate that domain and not finding the proper response, which would indicate AzuraCast isn't running on that domain.

**Comment by Ficreet** [comment]
@SlvrEagle23 After trying what you told me I understood my problem. I thought let's encrypt was asking for the "global" domain name so I always had the wrong address again. After registering the right subdomain (instead of www) it worked.

Thank you for helping me!
Good continuation for this project, better than paying solutions

**Comment by SlvrEagle23** [comment]
@Ficreet Happy to help. Glad you were able to get things resolved.
