### ISSUE TITLE
IceCast Admin Page Problem

### ISSUE THREAD

**Issue by djmuratb** [AzuraCast/AzuraCast#770]
**Installation method**
Traditional installation method.
Ubuntu 18.04.1 LTS

**Describe the bug**
When we log in with the password, IceCast Admin page comes out as XML.

http://test.alltimeworldhits.live:8000/admin/
Pass: h2qEwNL7

**Comment by ohld** [comment]
The same for me for my station.

**Comment by ohld** [comment]
I have some admin page on this address: 
https://phystech.tv/radio/8000/admin/stats.xsl

**Comment by SlvrEagle23** [comment]
@djmuratb @ohld Ah yes, that's my mistake. I had the wrong admin URL listed inside the app itself. The actual admin URL is `/admin.html`, i.e. http://test.alltimeworldhits.live:8000/admin.html

The link has been updated now.

**Comment by ErnestPH** [comment]
Hello,

I would like to report that the admin page for ice cast has some bugs. 

1. blank page
2. when log inside, the body text are black, you can't see the texts until you highlight them. thanks!
<img width="1440" alt="screen shot 2018-10-02 at 1 46 59 pm" src="https://user-images.githubusercontent.com/43772409/46331280-b2d4c180-c649-11e8-9f47-17cc2038e276.png">

**Comment by CodeSteele** [comment]
@ErnestPH should be tracked/fixed in #846, let me know if the issue persists though.

**Comment by ErnestPH** [comment]
This is now ok thanks!
