### ISSUE TITLE
SPAWN_ERROR: station_2:station_2_backend

### ISSUE THREAD

**Issue by JMultimidia** [AzuraCast/AzuraCast#773]
**Installation method**
Traditional

**Host OS**
Ubuntu 18.04.1

**Describe the bug**
When you try to start the auto dj service the following message "SPAWN_ERROR: station_2: station_2_backend" appears.
I did the test by sending only two mp3 audios - 128kbps - 44Khz.

**Screenshots**
`<img src="https://res.cloudinary.com/jmultimidia/image/upload/v1536196550/jmultimidia/Captura_de_tela_2018-09-05_22.13.24.png">

**Comment by SlvrEagle23** [comment]
@JMultimidia Always check the logs when reporting any issue of this nature, as there's no way I can know what's going wrong on your server unless you supply me with some details.

In this case, try `tail -f /var/azuracast/stations/(your_station_shortname)/config/liquidsoap.log` and try restarting again.

**Comment by JMultimidia** [comment]
@SlvrEagle23 
I do not have this log file on the server I run the "tail -f /var/azuracast/stations/rdfetraece/config/liquidsoap.log" command the following error message appears: "
tail: can not open '/var/azuracast/stations/rdfetraece/config/liquidsoap.log' for reading: No such file or directory
tail: no files remaining"

**Screenshot**
<img src="https://res.cloudinary.com/jmultimidia/image/upload/v1536198334/jmultimidia/Capturar.png">

**Comment by SlvrEagle23** [comment]
@JMultimidia from inside that directory, try running:
```
/var/azuracast/.opam/system/bin/liquidsoap liquidsoap.liq
```

and seeing what it returns.

**Comment by JMultimidia** [comment]
@SlvrEagle23 At line 1, char 15-14: the variable liquidsoap.liq used here has not been
  previously defined.

**Comment by JMultimidia** [comment]
At line 1, char 15-14: the variable liquidsoap.liq used here has not been previously defined.

**Comment by SlvrEagle23** [comment]
@JMultimidia That doesn't make much sense, what's actually in that file? `cat liquidsoap.liq`

**Comment by JMultimidia** [comment]
@SlvrEagle23 Excuse me. Displays the following message: "Invalid value at line 60, char 120-122:
  Maximum buffering lower than pre-buffered data."

**Comment by SlvrEagle23** [comment]
@JMultimidia The buffer should be less than 30 seconds. I should probably code that in as a protection to avoid that exact thing happening.

**Comment by JMultimidia** [comment]
Thank you, it worked. Is it possible to get a m3u8 url? I saw that there are only pls and m3u.

**Comment by SlvrEagle23** [comment]
@JMultimidia That would be a separate enhancement request. Feel free to submit it as another ticket. I'm not sure off the top of my head what M3U8 offers over plain M3U, though.
