### ISSUE TITLE
Tip: Create Packages for the auto dj.

### ISSUE THREAD

**Issue by JMultimidia** [AzuraCast/AzuraCast#774]
**Configure space-limited packages**
When I create multiple user accounts, everyone uses the same total amount of my disk space. I would like to be able to create space-limiting packages so the user does not use all my disk space.

**Comment by SlvrEagle23** [comment]
@JMultimidia Can you describe this request in more detail? I'm not sure quite what you're looking for.

**Comment by JMultimidia** [comment]
Currently an Azura user is allowed to access other users' radios.
Example user 1 should only have access to url http: // server / station / 1.
But if he accesses http: // server / station / 2 he will be able to change the settings of the other user.

My idea is to create packages with limited disk space and that I can register users by assigning an auto dj account and a package so that each owner of the radio has a limit of disk space to send mp3 and play the auto dj.

**Comment by xewl** [comment]
That would be a derivative of issue #368
