### ISSUE TITLE
Transcoding in a lower quality

### ISSUE THREAD

**Issue by tehcojam** [AzuraCast/AzuraCast#776]
**Is your feature request related to a problem? Please describe.**
Sometimes it's not necessary to storage music on server in high quality. For example, if broadcasting goes in 128kbps, but music uploaded in 320kbps. In this case music just taking excess storage amount on a server, and we might not have a lot of it already.

**Describe the solution you'd like**
Transcoding option in a lower quality on upload is really needed, aswell as a transcoding for already uploaded tracks.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38919/transcode-music-to-a-different-quality-upon-upload
