### ISSUE TITLE
Icecast remote not working

### ISSUE THREAD

**Issue by subconsciousnl** [AzuraCast/AzuraCast#778]
**Installation method**
Traditional.

**Describe the bug**
Everytime i try to use the remote connect function, it gives me a SPAWN_ERROR: station_5:station_5_backend, my remote setup works perfect which isn't the problem
error log is very vague aswell which brings up this ERROR: station_5:station_5_backend {"file":"/var/azuracast/www/src/Radio/AdapterAbstract.php","line":203,"code":0} []
[2018-09-07 18:33:11] AzuraCast.ERROR: SPAWN_ERROR: station_5:station_5_backend {"file":"/var/azuracast/www/src/Radio/AdapterAbstract.php","line":203,"code":0} []

this is the supervisor log 2018-09-07 18:37:40,855 INFO exited: station_5_backend (exit status 1; not expected)
2018-09-07 18:37:42,872 INFO spawned: 'station_5_backend' with pid 28219
2018-09-07 18:37:42,963 INFO exited: station_5_backend (exit status 1; not expected)
2018-09-07 18:37:45,969 INFO spawned: 'station_5_backend' with pid 28220
2018-09-07 18:37:46,057 INFO exited: station_5_backend (exit status 1; not expected)

Whenever i put remote station page up, whole radio page goes down with this error 
500
Cannot use object of type App\Entity\StationMount as array
Remote.php : 250

**Desktop (please complete the following information):**
OS Ubuntu 16.04
Browser all

**Additional context**
Help would be appreciated! :)

**Comment by SlvrEagle23** [comment]
@subconsciousnl Hello! I delayed a little in responding to this issue, as I was right in the middle of a fairly significant rewrite that separated remote relays into their own section on the site, allowing you to both broadcast locally and remotely from the same station.

As part of the updates, and the underlying database migrations that helped make it happen, the issue you mentioned has been resolved and should no longer be an issue. Please update your AzuraCast installation and let me know if you encounter any issues.
