### ISSUE TITLE
Can AzuraCast be used to stream to a external SHOUTCast Server?

### ISSUE THREAD

**Issue by guiscaranse** [AzuraCast/AzuraCast#781]
Imagine that I currently have a local server with AzuraCast, and a external server with SHOUTcast installed, can I make azuracast relay it's transmission to the external SHOUTcast server?

**Comment by SlvrEagle23** [comment]
@guiscaranse Your timing is excellent on this request, as I've just been working this week on an update to AzuraCast that allows stations to broadcast both locally and to remote relays at the same time.

Update to the latest codebase, and you'll see a new tab on the left side of the stations panel labeled "Remote Relays", where you can configure a remote station that you can broadcast to, or just gather statistics from.

This will allow you to connect to SHOUTcast 1, SHOUTcast 2, and Icecast external stations.

**Comment by guiscaranse** [comment]
Woah, that's amazing!!! I will check it out this week. Congrats on the amazing work!
