### ISSUE TITLE
Show Relay Password on Edit Profile

### ISSUE THREAD

**Issue by JDBlackman** [AzuraCast/AzuraCast#784]
With the addition of the Remote Relays it would be good to show the relay password for the station. 
(I'm not sure if this is an icecast only feature) 

This would make it easier when setting up slave servers you can get/edit it rather then having to find it via ssh in the configs.

**Comment by SlvrEagle23** [comment]
@JDBlackman It's an Icecast only thing, yes, but since we're now actually using the relay system it makes sense to persist and store that. Will work on getting that rolled into the profile view.

**Comment by SlvrEagle23** [comment]
@JDBlackman This is now implemented, along with a few other improvements I wanted to make to the profile page (including the remote relay URLs, adding "copy to clipboard" buttons in a few spots, etc).
