### ISSUE TITLE
Using admin pages for listener data on Remote Relays

### ISSUE THREAD

**Issue by JDBlackman** [AzuraCast/AzuraCast#785]
With the addition of remote relays it allowers for statistical tracking, however with it just using the open API pages they show up as duplicate listeners and some statistical tracking is rendered obsolete with this. 

It could be better to use the admin pages on shoutcast and icecast to grab the data such as IP so the other reporting features work better, most of them seem to run off unique listeners which listeners from a relay are not. 

The listener list of clients pages are
Shoutcast 2: /admin.cgi?sid=1&mode=viewxml&page=3
Icecast 2: /admin/listclients.xsl?mount=/live

**Comment by SlvrEagle23** [comment]
Our Nowplaying library has been using detailed listener client data (provided it's turned on in the system settings) to determine unique listeners and other statistics for several months now.
