### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by m333w** [AzuraCast/AzuraCast#786]
Hi, 

Someone can tell me how i can change the default favicon of azuracast ? 

Best regards.

**Comment by JDBlackman** [comment]
If your using the Traditional install you can find it at 

/var/azuracast/www/web/favicon.ico

**Comment by m333w** [comment]
I have change the favicon of this path, but in my browser is the same old.

**Comment by JDBlackman** [comment]
Have you tried using incognito to make sure it's not cached?

**Comment by m333w** [comment]
Yes sure, do you see any change : https://radio.geekshell.fr/public/stream ?

**Comment by JDBlackman** [comment]
Turns out I was wrong, took a quick look at the page and it references 

"/static/icons/production/....png""

Which I assume is a reference to "/var/azuracast/www/web/static/icons/production"

**Comment by m333w** [comment]
Gona take lot of time to convert/change all thoes png, they are no workaround with custom branding ?

**Comment by JDBlackman** [comment]
You can probably find favicon generators online that will take the icon and generate in all sizes

**Comment by m333w** [comment]
Yeah i gona try thx 👍

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38926/add-custom-favicon-support-to-branding-options
