### ISSUE TITLE
Adapter not found: liquidsoap

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#787]
**Installation method**
Traditional

**Describe the bug**
after an update of ubuntu in 18.04, I no longer have access to the management of my radio

**Screenshots**
![capture d ecran 2018-09-11 a 07 04 13](https://user-images.githubusercontent.com/379099/45339236-c6809100-b591-11e8-961c-a0f0c0fb2a21.png)

fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php azuracast:setup --update", "delta": "0:00:01.607546", "end": "2018-09-11 07:11:49.021536", "msg": "non-zero return code", "rc": 1, "start": "2018-09-11 07:11:47.413990", "stderr": "\nIn Adapters.php line 75:\n                                 \n  Adapter not found: liquidsoap  \n                                 \n\nazuracast:setup [--update] [--load-fixtures]", "stderr_lines": ["", "In Adapters.php line 75:", "                                 ", "  Adapter not found: liquidsoap  ", "                                 ", "", "azuracast:setup [--update] [--load-fixtures]"], "stdout": "\nAzuraCast Setup\n===============\n\nWelcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...\n * Environment: Production\n * Installation Method: Traditional\n\n ! [NOTE] Running in update mode.                                               \n\nMigrating Legacy Configuration\n------------------------------\n\nConfiguration already set up.\n\nSetting Up InfluxDB\n-------------------\n\nDatabase created.\nRetention policies updated.\nContinuous queries created.\nInfluxDB databases created.\nRouter cache file cleared.\nLocal cache flushed.\n\nRunning Database Migrations\n---------------------------\n\nLoading configuration from the integration code of your framework (setter).\n                                                                    \n                    Doctrine Database Migrations                    \n                                                                    \n\nNo migrations to execute.\n\nGenerating Database Proxy Classes\n---------------------------------\n\n\n Processing entity \"App\\Entity\\Analytics\"\n Processing entity \"App\\Entity\\StationRequest\"\n Processing entity \"App\\Entity\\StationRemote\"\n Processing entity \"App\\Entity\\StationMediaCustomField\"\n Processing entity \"App\\Entity\\Settings\"\n Processing entity \"App\\Entity\\Song\"\n Processing entity \"App\\Entity\\Station\"\n Processing entity \"App\\Entity\\RolePermission\"\n Processing entity \"App\\Entity\\StationWebhook\"\n Processing entity \"App\\Entity\\User\"\n Processing entity \"App\\Entity\\Listener\"\n Processing entity \"App\\Entity\\StationMount\"\n Processing entity \"App\\Entity\\StationStreamer\"\n Processing entity \"App\\Entity\\CustomField\"\n Processing entity \"App\\Entity\\StationMediaArt\"\n Processing entity \"App\\Entity\\SongHistory\"\n Processing entity \"App\\Entity\\StationPlaylist\"\n Processing entity \"App\\Entity\\StationMedia\"\n Processing entity \"App\\Entity\\ApiKey\"\n Processing entity \"App\\Entity\\Role\"\n Processing entity \"App\\Entity\\StationPlaylistMedia\"\n\n Proxy classes generated to \"/var/azuracast/www_tmp/proxies\"\n\nRefreshing All Stations\n-----------------------\n\nRouter cache file cleared.\nLocal cache flushed.\nRestarting all radio stations...\nRestarting station #5: Radio Deep Underground", "stdout_lines": ["", "AzuraCast Setup", "===============", "", "Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...", " * Environment: Production", " * Installation Method: Traditional", "", " ! [NOTE] Running in update mode.                                               ", "", "Migrating Legacy Configuration", "------------------------------", "", "Configuration already set up.", "", "Setting Up InfluxDB", "-------------------", "", "Database created.", "Retention policies updated.", "Continuous queries created.", "InfluxDB databases created.", "Router cache file cleared.", "Local cache flushed.", "", "Running Database Migrations", "---------------------------", "", "Loading configuration from the integration code of your framework (setter).", "                                                                    ", "                    Doctrine Database Migrations                    ", "                                                                    ", "", "No migrations to execute.", "", "Generating Database Proxy Classes", "---------------------------------", "", "", " Processing entity \"App\\Entity\\Analytics\"", " Processing entity \"App\\Entity\\StationRequest\"", " Processing entity \"App\\Entity\\StationRemote\"", " Processing entity \"App\\Entity\\StationMediaCustomField\"", " Processing entity \"App\\Entity\\Settings\"", " Processing entity \"App\\Entity\\Song\"", " Processing entity \"App\\Entity\\Station\"", " Processing entity \"App\\Entity\\RolePermission\"", " Processing entity \"App\\Entity\\StationWebhook\"", " Processing entity \"App\\Entity\\User\"", " Processing entity \"App\\Entity\\Listener\"", " Processing entity \"App\\Entity\\StationMount\"", " Processing entity \"App\\Entity\\StationStreamer\"", " Processing entity \"App\\Entity\\CustomField\"", " Processing entity \"App\\Entity\\StationMediaArt\"", " Processing entity \"App\\Entity\\SongHistory\"", " Processing entity \"App\\Entity\\StationPlaylist\"", " Processing entity \"App\\Entity\\StationMedia\"", " Processing entity \"App\\Entity\\ApiKey\"", " Processing entity \"App\\Entity\\Role\"", " Processing entity \"App\\Entity\\StationPlaylistMedia\"", "", " Proxy classes generated to \"/var/azuracast/www_tmp/proxies\"", "", "Refreshing All Stations", "-----------------------", "", "Router cache file cleared.", "Local cache flushed.", "Restarting all radio stations...", "Restarting station #5: Radio Deep Underground"]}

PLAY RECAP *********************************************************************
localhost                  : ok=15   changed=3

**Comment by SlvrEagle23** [comment]
@ckeurk It would only throw that error if it thought Liquidsoap wasn't installed. If you run `update.sh --full`, what happens when it reaches the Liquidsoap step?

**Comment by ckeurk** [comment]
Ok great it works after `update.sh --full`, but always error messages:

`fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php azuracast:setup --update", "delta": "0:00:00.317992", "end": "2018-09-11 07:35:30.255002", "msg": "non-zero return code", "rc": 1, "start": "2018-09-11 07:35:29.937010", "stderr": "\nIn Database.php line 103:\n                                       \n  Failed to created database stations  \n                                       \n\nIn Client.php line 196:\n                    \n  Query has failed  \n                    \n\nIn CurlFactory.php line 185:\n                                                                               \n  cURL error 7: Failed to connect to localhost port 8086: Connection refused   \n  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)                      \n                                                                               \n\nazuracast:setup [--update] [--load-fixtures]", "stderr_lines": ["", "In Database.php line 103:", "                                       ", "  Failed to created database stations  ", "                                       ", "", "In Client.php line 196:", "                    ", "  Query has failed  ", "                    ", "", "In CurlFactory.php line 185:", "                                                                               ", "  cURL error 7: Failed to connect to localhost port 8086: Connection refused   ", "  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)                      ", "                                                                               ", "", "azuracast:setup [--update] [--load-fixtures]"], "stdout": "\nAzuraCast Setup\n===============\n\nWelcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...\n * Environment: Production\n * Installation Method: Traditional\n\n ! [NOTE] Running in update mode.                                               \n\nMigrating Legacy Configuration\n------------------------------\n\nConfiguration already set up.\n\nSetting Up InfluxDB\n-------------------", "stdout_lines": ["", "AzuraCast Setup", "===============", "", "Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...", " * Environment: Production", " * Installation Method: Traditional", "", " ! [NOTE] Running in update mode.                                               ", "", "Migrating Legacy Configuration", "------------------------------", "", "Configuration already set up.", "", "Setting Up InfluxDB", "-------------------"]}

RUNNING HANDLER [azuracast-cron : restart cron] ********************************

PLAY RECAP *********************************************************************
localhost                  : ok=72   changed=30   unreachable=0    failed=1   `

**Comment by SlvrEagle23** [comment]
@ckeurk That's an InfluxDB problem, probably merits either a `service influxdb restart` or a system reboot.
