### ISSUE TITLE
Add Station Management API Endpoint

### ISSUE THREAD

**Issue by Just-In-Web** [AzuraCast/AzuraCast#788]
Would it be possible to add Stations and Users with the builtin API?
So I could create Stations with a simple provisioning module like for whmcs or others.

**Comment by SlvrEagle23** [comment]
@Just-In-Web The goal over time is to allow basically all functions that are currently able to be performed via the web interface to also be accessible via the API. Station creation will definitely be one of the more complex ones to implement, but it is definitely on the list. I'll update this ticket accordingly once there is new information available.

**Comment by SlvrEagle23** [comment]
@Just-In-Web Station management has been implemented via the AzuraCast REST API.
