### ISSUE TITLE
Feature Request: S3 bucket as docker volume support 

### ISSUE THREAD

**Issue by vineettalwar** [AzuraCast/AzuraCast#789]
**Idea:** 
Hi, I am not sure how easy or tough this would be or is it currently even possible ? 
But, I would like to propose following idea for AzuraCast. 
1. Right Now, if there are multiple stations, we have to upload music to the station either via backend or via ftp.
2. Take the scenario, when you have lets say 5 station. Each having own set of music may be shared music. 
3. For instance, every station holds 5 GB of music, Thats approx 25 GB So, you need to have atleast 40-50 GB of Hard drive for smooth running of the machine. What if you add more stations, and more music, you need to upgrade the hard drive storage. 
4. Wouldn't it be nice, if the docker version supports integration of an s3 bucket as a mounted volume. Please see the reference links. 
5. S3 bucket is just mounted as a docker volume and azuracast reads music from mounted volume. 
6. Benefit would be: Low hard drive costs, no need to upgrade the hard drive every time we add more stations or add more music to azuracast installation, shared music among the stations via mounted s3 bucket

**Some references,**
a) https://github.com/elementar/docker-s3-volume
b) https://docs.docker.com/registry/storage-drivers/s3/
c) https://docs.docker.com/registry/storage-drivers/s3/#configuring-cloudfront-for-distribution
d) Nextcloud as an example: Nextcloud is a self hosted storage solution and and it allows seamless s3 integration as a mounted drive. https://docs.nextcloud.com/server/12/admin_manual/configuration_files/external_storage/amazons3.html

Looking forward for your inputs.

**Comment by SlvrEagle23** [comment]
@vineettalwar Given the solutions you suggested, it seems like it may be possible to "bolt" this functionality on top of our existing AzuraCast Docker configuration, by bind-mounting in an S3 drive to `/var/azuracast/stations/(station_name)/media` on the `stations` container.

While I think the idea is overall a good one, I would want to implement something more abstracted than just supporting S3, as I don't want to create lock-in to any cloud vendor.

**Comment by vineettalwar** [comment]
Hi, @SlvrEagle23 , Thanks a lot for validating the idea. Implementation as something abstracted is indeed a greated. 
Following are further ideas and possibilities based on your inputs . 
1. Something like giving AzuraCast installation admin to mount any cloud storage. 
2. So, selects from a select box what kind of storage they would like to mount to AzuraCast installation. Add the required access key and credentials or connection details of that cloud storage and mount it . 
3. Giving the possibilities of the bucket mount to be shared across all the stations. Something, like if s3 bucket or any cloud drive is mounted then, all music storage is stored default on s3 bucket. 
4. A similar sort of implementation can be seen seen in **External Storage** app of Next Cloud. 
**For Example:** https://docs.nextcloud.com/server/12/admin_manual/configuration_files/external_storage_configuration_gui.html

5. So, Possibilities to offer hard drive mount would be for, 
- S3
- DropBox 
- Google Drive
- OneDrive
- Box
- own ftp/sftp server
- any WebDAV storage 
- Or even better, in addition, if possible to give a mount of nextcloud instance which it self is WebDAV based. 

6. Some references, 
https://github.com/cturra/docker-dropbox
https://github.com/mitcdh/docker-google-drive-ocamlfuse
http://allskyee.blogspot.com/2017/03/google-drive-as-docker-container.html

**Comment by SlvrEagle23** [comment]
Closing this issue as I've consolidated a number of requests to allow third-party storage options into a single issue so that we can easily track the progress of the implementation. You can follow that issue here: #1173
