### ISSUE TITLE
Please add voting system

### ISSUE THREAD

**Issue by 24dubstep** [AzuraCast/AzuraCast#79]
Hi please add voting system for actual played song and after vote add to up rating to most plays

**Comment by 24dubstep** [comment]
???

**Comment by SlvrEagle23** [comment]
@24dubstep I'll definitely look into it as a feature for the future. It may start off as an API-only feature, where you can submit votes for songs that are played.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38777/add-the-ability-for-listeners-to-vote-on-songs
