### ISSUE TITLE
[AzuraCast & Liquidsoap] DJ Live switching

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#790]
Hello all,
 i can´t find information about, how to integrate a custom or pre-defined liquidsoap script into azuracast, like in my case, switching from one live DJ to another, is this even possible? 
I heard about the new fallback option in Icecast.

Thanks for any hints and pointers

**Comment by SlvrEagle23** [comment]
@macbroadcast When you edit the station's profile, at the very bottom of the form you should see an option labeled "**Advanced** Custom Configuration", where you can put any custom OCaml code. It'll go directly between the setup process, where the live DJ and playlists are assembled, and the outbound broadcasts to the frontend. The variable for the signal at this point is called `radio`.

**Comment by macbroadcast** [comment]
Thanks for your reply @SlvrEagle23 found it 🚀
