### ISSUE TITLE
Account streamer/DJ on different mount

### ISSUE THREAD

**Issue by inciampa** [AzuraCast/AzuraCast#792]
Hello and thank you for the project
i am using icecast with 2 mounts and with liquidsoap i use to send a stream on one of the mounts:
BTW.. liquidsoap you see here is the source of a live configuration

......
radio = fallback(track_sensitive = false, [radio])
 # Stream it out
output.icecast(%mp3(bitrate=96,mono), fallible=true,host = "XXXXXXX", port=8005 , password="XXXXXX", mount="/radio",radio)

i am moving on azuracast  and liquidsoap can stream correctly when i send to / , as described in the instructions.

But when i send the stream on a particular mount i have 404 answer : 
2018/09/14 17:12:24 [/radio:3] Connecting mount /radio for source@XXXXXXX...
2018/09/14 17:12:24 [/radio:2] Connection failed: 404, Not found (HTTP/1.0)
2018/09/14 17:12:24 [/radio:3] Will try again in 3.00 sec.
Same answer with the other mount:
2018/09/14 17:29:32 [/soci:3] Connecting mount /soci for source@XXXXXXX...
2018/09/14 17:29:32 [/soci:2] Connection failed: 404, Not found (HTTP/1.0)

The icecast webpage in XXXX.XXXX.XXX:8000 is showingme both mounts opened and i can listen both streaming mounts with the client

I cannot see any related  problem on logs. Can someone suggest me a solution?

Thank you

**Comment by SlvrEagle23** [comment]
@inciampa It should no longer be necessary to manually configure broadcasting to either local mount points or remote streams. You can broadcast both locally and remotely from the same station just by using the web interface.

**Comment by inciampa** [comment]
Thank  you for the answer. My radio works like that:
Mount /radio is a open radio that work with a playlist 24/7
Mount /soci is a url authorize radio that resend /radio , but when there is live sessions i send on /soci, while /radio continue the normal flow.
How can i send the live session in one mount only?
Thank you

**Comment by inciampa** [comment]
I realized now that azuracast create a single liquidsoap source, sent in both radios. What i wanted to do , is to create 2 liquidsoap sources , each sent on a different mount. You think this can be possible?
Thank you

**Comment by SlvrEagle23** [comment]
@inciampa The basic idea with AzuraCast is that every station has its own combination of AutoDJ (Liquidsoap) and frontend (Icecast/Shoutcast). If you want two different AutoDJs on one station, the easy solution would be to create another station in AzuraCast that is listed as "remote only", then add the first station's second mountpoint as a remote. Then you can manage the media, playlists, etc. of that second station independently, while having both served from the same frontend.

**Comment by inciampa** [comment]
ok, i will try if it will work that way.
Thank you

**Comment by SlvrEagle23** [comment]
@inciampa Happy to help. Let me know if that works for you!
