### ISSUE TITLE
is_request on next_playing stay at false

### ISSUE THREAD

**Issue by Siriusa77II** [AzuraCast/AzuraCast#793]
**Installation method**
Docker

**Host OS (for Docker installations)**
Debian

**Describe the bug**
In API is_requested in next_playing stay to false when track is requested

**To Reproduce**
Request song
create GET request ib API with postman for exemple
Constat next_playing.is_request stay at false

**Screenshots**
On next playing
![Next playing API](https://cdn.siriushd.net/chrome_2018-09-15_06-39-45.png)
![next playing Web](https://cdn.siriushd.net/chrome_2018-09-15_06-41-14.png)

On Now playing
![Now playing API](https://cdn.siriushd.net/chrome_2018-09-15_06-41-58.png)
![Now Playing WEB](https://cdn.siriushd.net/chrome_2018-09-15_06-41-38.png)

**Comment by SlvrEagle23** [comment]
@Siriusa77II It should be fixed now.

**Comment by Siriusa77II** [comment]
it's works perfectly! Thanks you :)

![It's works :) ](https://cdn.siriushd.net/chrome_2018-09-17_06-52-15.png)

**Comment by SlvrEagle23** [comment]
@Siriusa77II Nice musical selection too /)

**Comment by Siriusa77II** [comment]
@SlvrEagle23 Ahah! Thanks xD Dream Walker is one oof my favorite 'cause it make angry a friend ahah :p (And I love Archie btw )
