### ISSUE TITLE
Start and end time

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#794]
Hello,
if i create a new Playlist on firefox, 1366x768 i can't Select the start and end time Longer.
![grafik](https://user-images.githubusercontent.com/31483348/45586800-d6370700-b8fc-11e8-99a9-c5615691604b.png)

**Comment by SlvrEagle23** [comment]
@preterive Absolutely no idea how that happened, but I could definitely reproduce the same issue on my local installation. I've updated the code to fix it. Sorry about that!

**Comment by preterive** [comment]
Thanks!
