### ISSUE TITLE
Customize Schedule Problem

### ISSUE THREAD

**Issue by djmuratb** [AzuraCast/AzuraCast#796]
**Installation method**
Traditional installation method.
Ubuntu 18.04.1 LTS

Update: Today

**Describe the bug**
Time selection does not visible.

![screenshot-test alltimeworldhits live-2018 09 15-17-50-10](https://user-images.githubusercontent.com/25807005/45587562-f15f4200-b90f-11e8-82c8-a229d8623829.png)

**Comment by djmuratb** [comment]
Sorry, same problem has already been written. :/

https://github.com/AzuraCast/AzuraCast/issues/794

**Comment by SlvrEagle23** [comment]
@djmuratb Should be fixed now!
