### ISSUE TITLE
Call to undefined method App\Radio\Adapters::listFrontendAdapters()

### ISSUE THREAD

**Issue by JMultimidia** [AzuraCast/AzuraCast#797]
**Installation method**
Traditional"

**Host OS (for Docker installations)**
Ubuntu 18

**Describe the bug**
when I try to access the url "htttp://serve/station/3/ profile to change the profile of the station appears this error.

Error 500
Call to undefined method App\Radio\Adapters::listFrontendAdapters()
station.php : 5

My Code:
https://pastebin.com/crRCqdmc

**Comment by SlvrEagle23** [comment]
@JMultimidia This function most definitely exists...have you checked to make sure you're on the latest version of the code? This kind of error suggests one part of the application updated and yet another didn't, which a second update should fix.
