### ISSUE TITLE
Web Hook info space for account in ubuntu traditional (no docker)

### ISSUE THREAD

**Issue by JMultimidia** [AzuraCast/AzuraCast#799]
I could create a "space_total" field in the station table and store a size for the client, even though I do not block it from sending files, but for it to have the space information that I have made available to the account.
In FilesController I could change
$space_total = disk_total_space($media_dir); per
$space_total = $station->space_total.

what else should I add to the code in "Station.php" namespace App\Entity;?
Is it possible to do this with webhook and how?

**Comment by SlvrEagle23** [comment]
@JMultimidia Our implementation of a storage quota has rendered this issue moot, as stations now have both the used disk space and the total quota of disk space listed in their Doctrine entity.
