### ISSUE TITLE
SPAWN_ERROR: station_13:station_13_backend

### ISSUE THREAD

**Issue by JMultimidia** [AzuraCast/AzuraCast#800]
**Installation method**
Traditional"

**Host OS**
Ubuntu 18

**Describe the bug**
When I try to connect the autodj, the following message appears:
SPAWN_ERROR: station_13:station_13_backend

**Comment by SlvrEagle23** [comment]
@JMultimidia Check the logs by running `tail -f /var/azuracast/stations/(your_station_name)/config/liquidsoap.log` to see what's going wrong. It's likely a custom configuration item that is causing the trouble. If the error isn't immediately obvious, feel free to paste the full error log here for diagnosis.

**Comment by JMultimidia** [comment]
##LOG1##
root@srv1-radios:~# tail -f /var/azuracast/stations/rdceara/config/liquidsoap.log
2018/09/17 23:46:36 [frame:3] Frame size must be a multiple of 1764 ticks = 1764                                              audio samples = 1 video samples.
2018/09/17 23:46:36 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio sa                                             mples = 1764 ticks.
2018/09/17 23:46:36 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video s                                             amples = 1764 ticks.
2018/09/17 23:46:41 >>> LOG START
2018/09/17 23:46:40 [main:3] Liquidsoap 1.3.3
2018/09/17 23:46:40 [main:3] Using: bytes=[distributed with OCaml 4.02 or above]                                              pcre=7.3.4 dtools=0.4.0 duppy=0.7.1 duppy.syntax=0.7.1 cry=0.6.0 mm=0.4.0 ogg=0                                             .5.2 vorbis=0.7.0 opus=0.1.2 mad=0.4.5 flac=0.1.2 flac.ogg=0.1.2 dynlink=[distri                                             buted with Ocaml] lame=0.3.3 fdkaac=0.2.1 taglib=0.3.3 camomile=0.8.6 faad=0.3.3
2018/09/17 23:46:41 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2018/09/17 23:46:41 [frame:3] Frame size must be a multiple of 1764 ticks = 1764                                              audio samples = 1 video samples.
2018/09/17 23:46:41 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio sa                                             mples = 1764 ticks.
2018/09/17 23:46:41 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video s                                             amples = 1764 ticks.

##LOG2##
root@srv1-radios:~# tail -f /var/azuracast/stations/rdfetraece/config/liquidsoap.log
2018/09/17 23:46:41 [clock:3] Called from file "clock.ml", line 79, characters 6-13
2018/09/17 23:46:41 [main:3] Shutdown started!
2018/09/17 23:46:41 [main:3] Waiting for threads to terminate...
2018/09/17 23:46:41 [main:3] Threads terminated.
2018/09/17 23:46:41 [threads:3] Shutting down scheduler...
2018/09/17 23:46:41 [threads:3] Scheduler shut down.
2018/09/17 23:46:41 [server:3] Closing socket.
2018/09/17 23:46:41 [main:3] Cleaning downloaded files...
2018/09/17 23:46:41 [main:3] Freeing memory...
2018/09/17 23:46:41 >>> LOG END

**Comment by SlvrEagle23** [comment]
@JMultimidia The logs don't seem to be saying much about the problem. Do you have any custom configuration in the "Advanced: Custom Configuration" section of the profile?

**Comment by JMultimidia** [comment]
##rdceara##
**Advanced: Customize Broadcasting Port**
7040

**Advanced: Customize DJ/Streamer Port**
7043

**Advanced: DJ/Streamer Buffer Time (Seconds)**
10

**Advanced: Customize Internal Request Processing Port**
7042

##rdfetraece##
**Advanced: Customize Broadcasting Port**
8010

**Advanced: Customize DJ/Streamer Port**
8013

**Advanced: Customize Internal Request Processing Port**
8012
