### ISSUE TITLE
API Auto increment a custom fields "website_api_player"

### ISSUE THREAD

**Issue by RainbowDash53** [AzuraCast/AzuraCast#801]
**Is your feature request related to a problem? Please describe.**
I use a cron to add each song that its played on my website into a table in my database of the website:
ID, Title, Artist, AzuraID.

**Describe the solution you'd like**
I want that the custom_fields that I created use auto increment that I don't have to add a value for each.

**Describe alternatives you've considered**
Show the ID of the music directly in the API.

**Additional context**
nope.

**Comment by RainbowDash53** [comment]
I think that give the ID of the song a unique ID I found sh_id I don't know what's is but it's different for two same songs, anyway to get the unique ID of one song ? thanks.

**Comment by RainbowDash53** [comment]
Fixed I can get the song id directly from the api, patched but auto increment for a value in API could be great to add.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39034/make-autoincrementing-custom-fields
