### ISSUE TITLE
Once per x Minutes (more time option)

### ISSUE THREAD

**Issue by djmuratb** [AzuraCast/AzuraCast#804]
Playlist options page: Once per x Minutes

I could choose 180 minutes in previous versions. But when I do the last update, there are no more than 120 minutes.

It would be better to have more time like 300 minutes.

**Comment by xewl** [comment]
When you need more than that given amount, it's probably better if you set it as a scheduled playlist.

**Comment by SlvrEagle23** [comment]
@djmuratb The valid options have been extended to 360 (6 hours). For longer cases than that, the "once per day" or "scheduled playlist" options should be used.
