### ISSUE TITLE
Centos 7 with Plesk

### ISSUE THREAD

**Issue by pwrj** [AzuraCast/AzuraCast#805]
Can I install Azure on Centos 7 running Plesk Onyx?

**Comment by SlvrEagle23** [comment]
@pwrj Using Docker, possibly. The traditional installation method is only for clean installations of Ubuntu 16.04 or 18.04.

**Comment by pwrj** [comment]
I have Docker already installed on Centos 7 as park of Plesk Onyx. I followed the instructions, but got some errors. It didn't work. Any pointers would be appreciated.

**Comment by pwrj** [comment]
Here's what I got from my Centos/Plesk Onyx. What does this error mean and can it be fixed? 

# ./docker.sh install
Docker is already installed! Continuing...
Docker Compose is already installed! Continuing...
Pulling letsencrypt ... done
Pulling mariadb     ... done
Pulling influxdb    ... done
Pulling redis       ... done
Pulling stations    ... done
Pulling web         ... done
Pulling cli         ... done
Pulling cron        ... done
Pulling nginx       ... done
Creating network "azuracast_default" with the default driver
ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-09cb8ec94e10 -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))
Creating network "azuracast_default" with the default driver
ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-018064abdab8 -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))
