### ISSUE TITLE
Song Listener Impact: Allowed memory exhausted

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#807]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
Blank page when i click on "Song Listener Impact". 
Log:
`[21-Sep-2018 15:26:00] WARNING: [pool www] child 10249 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 114688 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/BlobType.php on line 56"
`

**To Reproduce**
1. Go to 'Reports'
2. Click on 'Song Listener Impact'
3. Get blank page

**Additional context**
How to increase php memory_limit in docker?

**Comment by gr0ebi** [comment]
not sure if its related to the song listener. I get the same error in my log when clicking "Media"

` php-fpm[39]: [WARNING] [pool www] child 3303 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /var/azuracast/www/vendor/league/flysystem-cached-adapter/src/Storage/AbstractCache.php on line 381"`
The site still opens but shows "No results found!" in my library

php-fpm problem?

**Comment by Vaalyn** [comment]
Seems like there is so much data in the Flysystem cache that it fails to load the cache to memory on the initialization of the `CacheAdapter`. How many files does your station roughly have?

**Comment by gr0ebi** [comment]
@Vaalyn over 50K MP3 files and about 3K OGG Vorbis files
On a 2nd or 3rd try it will work btw!

**Comment by CodeSteele** [comment]
`> 100 days of continuous music`

Okay that's cool.

So yeah I mean I'd probably argue that only having 128MB per PHP process for a setup that large is a bit silly. We could _possibly_ code around that by being very memory conscious (I'm not familiar with this part of the code though), but it's probably best to just have a `docker.override.yml` file that'll set some environment variable to bump the max memory for the PHP process.

We don't support it currently, but it shouldn't be too bad to add support for.

**Comment by Vaalyn** [comment]
> `> 100 days of continuous music`
> 
> Okay that's cool. I always love seeing people do some pretty big things with AzuraCast.
> 
> So yeah I mean I'd probably argue that only having 128MB per PHP process for a setup that large is a bit silly. We could _possibly_ code around that by being very memory conscious (I'm not familiar with this part of the code though), but it's probably best to just have a `docker.override.yml` file that'll set some environment variable to bump the max memory for the PHP process.

Is it currently possible to control the memory per process through an env var or do we need to adapt AzuraCast a bit to make that possible?

If I understood the caching logic correctly when I took a quick look at it I think the main problem here could be that the current Flysystem `CacheAdapter` loads the whole cache at once into memory. If my assumption is correct we could theoretically write a `CacheAdapter` that only fetches the data for the "Media" page that is currently displayed. I'm not sure how the cached data is currently structured so that could also mean that this would need to be adapted to fit this flow.

**Comment by SlvrEagle23** [comment]
@Vaalyn That's the easy solution here, to make it a configurable env variable. We already use Dockerize, which is capable of writing environment variables to configuration files at container spin-up. That and the post max body size are probably the only two we'd need to make customizable for now.

**Comment by gr0ebi** [comment]
I gonna mount my subfolders then instead of the root directory
Just wanted to add that I think it was a redis "problem" that caused the php error
Found [this ](https://www.techandme.se/performance-tips-for-redis-cache-server/)and applied 1,2 and 3 and now my php errors are gone, even when using my 50K library

**Comment by Vaalyn** [comment]
> I gonna mount my subfolders then instead of the root directory
> Just wanted to add that I think it was a redis "problem" that caused the php error
> Found [this ](https://www.techandme.se/performance-tips-for-redis-cache-server/)and applied 1,2 and 3 and now my php errors are gone, even when using my 50K library
> PS: It's still scanning my files but without errors atm

I'm not sure that it has something to do with a huge amount of connections to redis. The Flysystem cache should only fetch data for the 5 keys / aliases in [this method](https://github.com/AzuraCast/AzuraCast/blob/master/src/Radio/Filesystem.php#L32).

[In this line](https://github.com/AzuraCast/AzuraCast/blob/master/src/Radio/Filesystem.php#L51) a new `CacheAdapter` is created for each of these keys. In the constructor of the `CacheAdapter` the `load` method is called so the cache will be populated immediately on creation. The cache is probably not big enough while the scanning is still running to trigger the error yet.

**Comment by gr0ebi** [comment]
I may have been unclear, I meant that part 2 or 3 of my link (vm.overcommit_memory = 1/THP) maybe did the job. Found the link cause my redis container was logging these warnings

**Comment by gr0ebi** [comment]
looks like you are right
`web_1       | Jan 26 02:48:50 aba54f3b928f php-fpm[38]: [WARNING] [pool www] child 23470 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/src/Controller/Stations/Files/ListController.php on line 99"
`

**Comment by SlvrEagle23** [comment]
As of the latest version of AzuraCast's new `web` Docker container, you can now pass environment variables that will customize the running PHP service's memory limits and POST body size. The modifications can be added to `azuracast.env`:

```

#
# Advanced Configuration
#

# PHP's maximum POST body size and max upload filesize.
PHP_MAX_FILE_SIZE=25M

# PHP's maximum memory limit.
PHP_MEMORY_LIMIT=128M
```
