### ISSUE TITLE
[Question] Where are the SSL renamed ?

### ISSUE THREAD

**Issue by MyTheValentinus** [AzuraCast/AzuraCast#809]
Hello,
Using Docker stack to deploy Azuracast, i launch certificates creation like documentation, work perfectly but i have a quesstion. Where the "/etc/letcscrypt/my.domain.com/fullchain.pem" was rename to "ssl.crt" and move to "/etc/nginx/ssl/" ?

By default certbot stock certificates in /etc/letsencrypt/live/.../

Thanks

**Comment by MyTheValentinus** [comment]
I find this: https://github.com/AzuraCast/docker-azuracast-nginx/blob/master/scripts/letsencrypt_connect 
But i think it was not easy to add custom certificates (not issue via docker.sh script).

I think i need to create new container, that have 2 mounts points:  1 with my custom certificates, 1 with volume containing certificates on azuracast, and create script to rename like your.

**Comment by SlvrEagle23** [comment]
@MyTheValentinus It's not actually renaming the SSL certs from LetsEncrypt, it's symlinking them into the spot that the nginx configuration is expecting, replacing the self-signed certificates that ship by default. This is one of the only ways I could find to allow LetsEncrypt certificate management to be as simple as possible, while not requiring hand-editing of configuration files.

To override this, you can either bind-mount a path directly on top of `/etc/nginx/ssl/` or mount a custom nginx configuration on top of the AzuraCast one, making sure to incorporate all of the configuration items that we include.

**Comment by MyTheValentinus** [comment]
Yes, i look for this next week, and post here my solution about this case. (i think is susceptible to interest other peoples in the same case)

**Comment by MyTheValentinus** [comment]
Hello, 
After some tests, i think it's more easy to put reverse proxy front of azuracast installation and keep default SSL(auto signed)  for local communication between containers and the reverse proxy.
I close this issue.
