### ISSUE TITLE
SPAWN_ERROR: station_9:station_9_backend

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#810]
**Installation method**
**Tradition**
When I go to create my station number 9 I get this problem!
![image](https://user-images.githubusercontent.com/22561729/45929021-605e1b80-bf4c-11e8-971c-86e2bd8e02ef.png)
![image](https://user-images.githubusercontent.com/22561729/45929025-68b65680-bf4c-11e8-87bb-acf2c03e5fbf.png)

**Comment by Ilario42** [comment]
@djmuratb not working

**Comment by djmuratb** [comment]
In station settings, make the top port number 8090 (or 8100 / 8110..)  and delete the other port numbers that are written at the bottom.

**Comment by Ilario42** [comment]
![image](https://user-images.githubusercontent.com/22561729/45929222-c8adfc80-bf4e-11e8-98c7-adcf5f81bd74.png)
Not working

**Comment by djmuratb** [comment]
Did you delete other ports to automatically create new ones?

**Comment by Ilario42** [comment]
> Did you delete other ports to automatically create new ones?

I can not delete my old stations, I have too much music now!

**Comment by djmuratb** [comment]
Edit Profile: Station Profile:

Configure Broadcasting Service: 8100

Customize DJ/Streamer Port : Delete (Leave Empty)
Customize Internal Request Processing Port : Delete (Leave Empty)
