### ISSUE TITLE
Changes to jingles and advertising

### ISSUE THREAD

**Issue by NeddyPlays** [AzuraCast/AzuraCast#811]
Hi,

Where discussing some stuff in our Radio Station that is not possible at the moment. The thing is to play ads on the full hour (and like let it randomly pick 3 or 4 ads) and a TOH Jingle.

Is it possible to make it like that?

**Comment by SlvrEagle23** [comment]
@NeddyPlays This is completely possible using a combination of Advanced Playlists and the "Custom Configuration" section under Liquidsoap in the station's profile.

You'll want to do something similar to this:

```
radio = rotate(weights=[1,5,1,1,5], [playlist_bumpers, radio, playlist_commercials, playlist_bumpers, radio])
```

This rotation plays one bumper, then 5 songs, then one commercial and one bumper directly next to each other, then 5 more songs.

This ensures that the commercial and bumper always play one after the other in perfect order every time.

**Comment by NeddyPlays** [comment]
Iam not that handy with this :p 
Can't seem to get the TOH working around the full hour....
