### ISSUE TITLE
Ubuntu 16.04 OCAML version out of date for Liquidsoap 1.3.4

### ISSUE THREAD

**Issue by FuraXx** [AzuraCast/AzuraCast#813]
Hello I get this error while installing azuracast on ubuntu without docker
can you help me ? 
thanks you very much 

`TASK [azuracast-radio : Build LiquidSoap] **************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "opam init -y && opam up                                        
date && opam install -y taglib.0.3.3 mad.0.4.5 faad.0.4.0 fdkaac.0.2.1 lame.0.3.                                        
3 vorbis.0.7.0 cry.0.6.0 opus.0.1.2 flac.0.1.2 liquidsoap.1.3.4", "delta": "0:00                                        
:57.786634", "end": "2018-09-27 10:48:34.459133", "msg": "non-zero return code",                                         
"rc": 66, "start": "2018-09-27 10:47:36.672499", "stderr": "[ERROR] liquidsoap.                                        
1.3.4 is not available because your system doesn't comply\n        with ocaml-ve                                        
rsion >= \"4.03\".", "stderr_lines": ["[ERROR] liquidsoap.1.3.4 is not available                                         
because your system doesn't comply", "        with ocaml-version >= \"4.03\"."]                                        
, "stdout": "OPAM has already been initialized.\nIn normal operation, OPAM only                                         
alters files within ~/.opam.\n\nDuring this initialisation, you can allow OPAM t                                        
o add information to two\nother files for best results. You can also make these                                         
additions manually\nif you wish.\n\nIf you agree, OPAM will modify:\n\n  - ~/.ba                                        
sh_profile (or a file you specify) to set the right environment\n    variables a                                        
nd to load the auto-completion scripts for your shell (bash)\n    on startup. Sp                                        
ecifically, it checks for and appends the following line:\n\n    . /var/azuracas                                        
t/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true\n\n\n  - ~/.ocamlinit                                         
to ensure that non-system installations of `ocamlfind`\n    (i.e. those install                                        
ed by OPAM) will work correctly when running the\n    OCaml toplevel. It does th                                        
is by adding $OCAML_TOPLEVEL_PATH to the list\n    of include directories.\n\nIf                                         
you choose to not configure your system now, you can either configure\nOPAM man                                        
ually (instructions will be displayed) or launch the automatic setup\nlater by r                                        
unning:\n\n   opam config setup -a\n\n\nDo you want OPAM to modify ~/.bash_profi                                        
le and ~/.ocamlinit?\n(default is 'no', use 'f' to name a file other than ~/.bas                                        
h_profile)\n    [N/y/f] \nGlobal configuration:\n  ~/.opam/opam-init/init.sh is                                         
already up-to-date.\n  ~/.opam/opam-init/init.zsh is already up-to-date.\n  ~/.o                                        
pam/opam-init/init.csh is already up-to-date.\n  ~/.opam/opam-init/init.fish is                                         
already up-to-date.\n\n=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=                                        
-=-=-=-=-=-=-=-=-=-=\n\n1. To configure OPAM in the current shell session, you n                                        
eed to run:\n\n      eval `opam config env`\n\n2. To correctly configure OPAM fo                                        
r subsequent use, add the following\n   line to your profile file (for instance                                         
~/.bash_profile):\n\n      . /var/azuracast/.opam/opam-init/init.sh > /dev/null                                         
2> /dev/null || true\n\n3. To avoid issues related to non-system installations o                                        
f `ocamlfind`\n   add the following lines to ~/.ocamlinit (create it if necessar                                        
y):\n\n      let () =\n        try Topdirs.dir_directory (Sys.getenv \"OCAML_TOP                                        
LEVEL_PATH\")\n        with Not_found -> ()\n      ;;\n\n=-=-=-=-=-=-=-=-=-=-=-=                                        
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n\n\n=-=- Updating packag                                        
e repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n[default: http] Co                                        
mmand started\n[default: http] Command started\n[default] synchronized from http                                        
s://opam.ocaml.org/1.2.2", "stdout_lines": ["OPAM has already been initialized."                                        
, "In normal operation, OPAM only alters files within ~/.opam.", "", "During thi                                        
s initialisation, you can allow OPAM to add information to two", "other files fo                                        
r best results. You can also make these additions manually", "if you wish.", "",                                         
"If you agree, OPAM will modify:", "", "  - ~/.bash_profile (or a file you spec                                        
ify) to set the right environment", "    variables and to load the auto-completi                                        
on scripts for your shell (bash)", "    on startup. Specifically, it checks for                                         
and appends the following line:", "", "    . /var/azuracast/.opam/opam-init/init                                        
.sh > /dev/null 2> /dev/null || true", "", "", "  - ~/.ocamlinit to ensure that                                         
non-system installations of `ocamlfind`", "    (i.e. those installed by OPAM) wi                                        
ll work correctly when running the", "    OCaml toplevel. It does this by adding                                         
$OCAML_TOPLEVEL_PATH to the list", "    of include directories.", "", "If you c                                        
hoose to not configure your system now, you can either configure", "OPAM manuall                                        
y (instructions will be displayed) or launch the automatic setup", "later by run                                        
ning:", "", "   opam config setup -a", "", "", "Do you want OPAM to modify ~/.ba                                        
sh_profile and ~/.ocamlinit?", "(default is 'no', use 'f' to name a file other t                                        
han ~/.bash_profile)", "    [N/y/f] ", "Global configuration:", "  ~/.opam/opam-                                        
init/init.sh is already up-to-date.", "  ~/.opam/opam-init/init.zsh is already u                                        
p-to-date.", "  ~/.opam/opam-init/init.csh is already up-to-date.", "  ~/.opam/o                                        
pam-init/init.fish is already up-to-date.", "", "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=                                        
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=", "", "1. To configure OPAM in th                                        
e current shell session, you need to run:", "", "      eval `opam config env`",                                         
"", "2. To correctly configure OPAM for subsequent use, add the following", "                                           
line to your profile file (for instance ~/.bash_profile):", "", "      . /var/az                                        
uracast/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true", "", "3. To av                                        
oid issues related to non-system installations of `ocamlfind`", "   add the foll                                        
owing lines to ~/.ocamlinit (create it if necessary):", "", "      let () =", "                                                
try Topdirs.dir_directory (Sys.getenv \"OCAML_TOPLEVEL_PATH\")", "                                                
with Not_found -> ()", "      ;;", "", "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=                                        
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=", "", "", "=-=- Updating package reposito                                        
ries =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=", "[default: http] Command st                                        
arted", "[default: http] Command started", "[default] synchronized from https://                                        
opam.ocaml.org/1.2.2"]}

RUNNING HANDLER [azuracast-user : send user notification] **********************

PLAY RECAP *********************************************************************
localhost                  : ok=22   changed=3    unreachable=0    failed=1`

**Comment by SlvrEagle23** [comment]
@FuraXx I've reverted a recent change that likely caused the problem. You may want to try a fresh installation again from scratch, but it's also possible (though perhaps not recommended) that restarting the installation process for your existing instance may work.

Let me know if you encounter any further issues during the installation process.
