### ISSUE TITLE
Best practice for cloudflare usage

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#814]
hello there, 
I tried several combinations using different SSL only settings in azuracast, combined with Cloudflare ON and OFF, Cloudflare only accepts connection to port 80 and 443 so currently, I turned the Orange cloud off and disabled the proxy settings in azuracast otherwise it wont let you connect with Butt-tool to the server. So guess i need to proxy the additional port with nginx ?

Thanks for this great piece of software 🚀

**Comment by SlvrEagle23** [comment]
@macbroadcast Cloudflare is intended to serve as a reverse proxy for your server, hiding the actual originating IP from most viewers and also negotiating things like SSL/TLS connections for you with relative ease.

AzuraCast is built to work with CloudFlare by always serving pages on port 443 (even with a self-signed certificate) so you can use "Full" mode, and by implementing the port 80/443 proxy for all radio signals.

When connecting inbound as a DJ, you should be connecting directly to the IP of the server itself. This should be something known only to you and your other streamers.
