### ISSUE TITLE
Now playing ajax call in public page problem

### ISSUE THREAD

**Issue by promogr** [AzuraCast/AzuraCast#815]
Installation method : Docker on Ubuntu 16.04

On public pages there is a small bug in the  javascript getting the now playing data.
If for some reason ajax call fails, it's never called again.

Some
`
function loadNowPlaying() {
	$.getJSON("/api/nowplaying/2", function (row) {
		nowPlaying.np = row;
		songHistory.history = row.song_history;
		if ("mediaSession" in navigator) {
			navigator.mediaSession.metadata = new MediaMetadata({
					title : row.now_playing.song.title,
					artist : row.now_playing.song.artist,
					artwork : [{
							src : row.now_playing.song.art
						}
					]
				});
		}
		setTimeout(loadNowPlaying, 15000);
	});
}
`

On fail event is missing.
`
.fail(function() {
   setTimeout(loadNowPlaying, 15000);
})
`

In my case, every now and then  i get a 404 error when trying to get '/api/nowplaying'. This error causes loadNowPlaying not to run until the page is refreshed.

**Comment by SlvrEagle23** [comment]
@promogr Thank you very much for the report. I have updated both the frontend of AzuraCast to be more resilient to errors coming from the NowPlaying API endpoint, and in the process of investigating why such errors were being generated in the first place, was able to fix an issue causing the cache to be improperly emptied, which was causing the actual 500/404 errors under the hood. Not only has the original issue been fixed now, but the system should overall be better equipped to handle future errors should they occur.
