### ISSUE TITLE
installation complete but not work(Cron cli Error)

### ISSUE THREAD

**Issue by Makunia** [AzuraCast/AzuraCast#816]
**Installation method**
Indicate whether you are using the "Docker" or "Traditional" installation method.

Docker
self installed, the script dont installed it (Error Version?)
```
curl -L https://github.com/docker/compose/releases/download/1.23.0-rc1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```

**Host OS (for Docker installations)**
Ubuntu 18.04

**Describe the bug**
become a Error and cant join the page

**Screenshots**

![inked9dd0cf79eca8f782c01ac530a3f145e7_li](https://user-images.githubusercontent.com/39903499/46205737-185f4000-c322-11e8-980f-89415f35ea3d.jpg)

**Comment by Makunia** [comment]
The server is for test installed, also a fresh Ubuntu

**Comment by SlvrEagle23** [comment]
@Makunia What error did the Docker installer script give you? These errors appear to be with Docker itself, not with AzuraCast.

**Comment by Makunia** [comment]
![e8fb94f7e95d1d672079668955f2eb75](https://user-images.githubusercontent.com/39903499/46208927-9b859380-c32c-11e8-82bf-c103e41f0e32.png)

**Comment by SlvrEagle23** [comment]
@Makunia Git should be installed first. `apt-get install git` and then do that process again.

**Comment by Makunia** [comment]
Git is installed the docker works but new issues
`Starting azuracast_influxdb_1_6acab3d2043a ... done
Starting azuracast_redis_1_ce0f038cab9e    ... done
Starting azuracast_mariadb_1_3eef16346740  ... done
Starting azuracast_stations                ... done
Starting azuracast_web_1_143dbf538d81      ... done
2018/09/28 13:55:46 Waiting for: tcp://mariadb:3306
2018/09/28 13:55:46 Waiting for: tcp://influxdb:8086
2018/09/28 13:55:46 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: read ud                                                                       p 127.0.0.1:58522->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:46 Problem with dial: dial tcp: lookup mariadb on 127.0.0.11:53: read udp                                                                        127.0.0.1:40341->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:47 Problem with dial: dial tcp: lookup mariadb on 127.0.0.11:53: read udp                                                                        127.0.0.1:34076->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:47 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: read ud                                                                       p 127.0.0.1:41953->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:48 Problem with dial: dial tcp: lookup mariadb on 127.0.0.11:53: read udp                                                                        127.0.0.1:60648->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:48 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: read ud                                                                       p 127.0.0.1:45794->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:49 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: read ud                                                                       p 127.0.0.1:56289->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:49 Problem with dial: dial tcp: lookup mariadb on 127.0.0.11:53: read udp                                                                        127.0.0.1:46088->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:50 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: read ud                                                                       p 127.0.0.1:32868->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:50 Problem with dial: dial tcp: lookup mariadb on 127.0.0.11:53: read udp                                                                        127.0.0.1:37387->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:51 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: read ud                                                                       p 127.0.0.1:50337->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:51 Problem with dial: dial tcp: lookup mariadb on 127.0.0.11:53: read udp                                                                        127.0.0.1:37157->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:52 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: read ud                                                                       p 127.0.0.1:45770->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:52 Problem with dial: dial tcp: lookup mariadb on 127.0.0.11:53: read udp                                                                        127.0.0.1:36381->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:53 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: read ud                                                                       p 127.0.0.1:52893->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:53 Problem with dial: dial tcp: lookup mariadb on 127.0.0.11:53: read udp                                                                        127.0.0.1:40442->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:54 Problem with dial: dial tcp: lookup mariadb on 127.0.0.11:53: read udp                                                                        127.0.0.1:37397->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:54 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: read ud                                                                       p 127.0.0.1:59794->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:55 Problem with dial: dial tcp: lookup mariadb on 127.0.0.11:53: read udp                                                                        127.0.0.1:51337->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:55 Problem with dial: dial tcp: lookup influxdb on 127.0.0.11:53: read ud                                                                       p 127.0.0.1:54036->127.0.0.11:53: read: connection refused. Sleeping 1s
2018/09/28 13:55:56 Timeout after 10s waiting on dependencies to become available: [tcp://                                                                       mariadb:3306 tcp://influxdb:8086]
azuracast_stations is up-to-date
azuracast_influxdb_1_6acab3d2043a is up-to-date
Starting azuracast_letsencrypt_1_82de821f46a1 ...
azuracast_mariadb_1_3eef16346740 is up-to-date
azuracast_redis_1_ce0f038cab9e is up-to-date
azuracast_web_1_143dbf538d81 is up-to-date
Starting azuracast_cli_1_ced1fe95651c         ... error
Starting azuracast_cron                       ...
Starting azuracast_nginx_1_34b55dd98b43       ...

ERROR: for azuracast_cli_1_ced1fe95651c  Cannot start service cli: OCI runtime create fail                                                                       ed: unable to retrieve OCI runtime error (open /run/docker/containerd/daemon/io.containerd                                                                       .runtime.v1.linux/moby/8c6572eb310e1e1501fdd7aef788776e1645ce4a3d48657165a2b8bcc33f71fa/lo                                                                       Starting azuracast_cron                       ... error
navailable: : unknown

ERROR: for azuracast_cron  Cannot start service cron: ttrpc: client shutting down: read un                                                                       ix @->@/containerd-shim/moby/1fd4407cc26c9feb34f7aa78d7e41228478df2c4213925e86a5e54828f1e2                                                                       Starting azuracast_letsencrypt_1_82de821f46a1 ... done

ERROR: for azuracast_nginx_1_34b55dd98b43  Cannot start service nginx: failed to start shi                                                                       m: fork/exec /usr/bin/docker-containerd-shim: resource temporarily unavailable: unknown

ERROR: for cli  Cannot start service cli: OCI runtime create failed: unable to retrieve OC                                                                       I runtime error (open /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/8c                                                                       6572eb310e1e1501fdd7aef788776e1645ce4a3d48657165a2b8bcc33f71fa/log.json: no such file or d                                                                       irectory): fork/exec /usr/bin/docker-runc: resource temporarily unavailable: : unknown

ERROR: for cron  Cannot start service cron: ttrpc: client shutting down: read unix @->@/co                                                                       ntainerd-shim/moby/1fd4407cc26c9feb34f7aa78d7e41228478df2c4213925e86a5e54828f1e2fb4/shim.s                                                                       ock: read: connection reset by peer: unknown

ERROR: for nginx  Cannot start service nginx: failed to start shim: fork/exec /usr/bin/doc                                                                       ker-containerd-shim: resource temporarily unavailable: unknown
ERROR: Encountered errors while bringing up the project.
`

**Comment by SlvrEagle23** [comment]
@Makunia Something is definitely wrong with your Docker installation on that server. Who is your web host?

Since we simply use Docker but aren't involved in writing or maintaining Docker, your best bet may be to search for similar issues in Docker's own repository: https://github.com/moby/moby/issues

**Comment by Makunia** [comment]
its a rootserver from Hetzner, thanks i will do it :) 👍
