### ISSUE TITLE
Display Album Name as well as or instead of Artist in Now Playing

### ISSUE THREAD

**Issue by benserwa** [AzuraCast/AzuraCast#818]
I'm using AzuraCast to make a video game music station. While I'd like to credit the artist, it's also very important that the name of the game be displayed. Right now all the game titles are in the metadata as Album Name. I'd like to display that along with or if necessary instead of the artist in Now Playing as well as in the metadata that is streamed to the client when running the playlist.

http://retrochipradio.com

**Comment by SlvrEagle23** [comment]
@benserwa AzuraCast's public player is meant to be an example of a "starter" player that you can build your own on top of. If you need more complex features, it's highly recommended to build your own static HTML page and set up the player exactly how you want it to function.

In this case, the AzuraCast API already returns the album along with other metadata on what's now playing. In your case, the API URL is http://retrochipradio.com/api/nowplaying/retro_chip_radio

**Comment by Scraticus** [comment]
We can also expand this in the configuration of the azura liq so it is exported on those formats that support it 

```
set("encoder.encoder.export",["artist","title","album","genre","year","track","comment","track","woar","on_air","source"])
```

This gives an extended selection on output, and also reminds the encoder to include it if it's there.

**Comment by SlvrEagle23** [comment]
In this case, AzuraCast's own internal API processing adds back in not only any missing metadata from Icecast/SHOUTcast, but any custom metadata set inside the AzuraCast app. The API is already fully capable of displaying album, etc. information, it just doesn't in the default public player, as this is intended as a lightweight placeholder, with any more complex radio situations likely benefiting from a custom solution.
