### ISSUE TITLE
Improve the update system

### ISSUE THREAD

**Issue by RainbowDash53** [AzuraCast/AzuraCast#819]
**Describe the solution you'd like**
It could be great to add a page to update the instance directly on the panel instead of connect to SSH and execute the update command.

**Describe alternatives you've considered**
Show the changelog on the update page, the current version of Azura and the latest version available

**Additional context**
<img width="395" alt="capture d ecran 2018-09-28 a 14 23 41" src="https://user-images.githubusercontent.com/24684510/46208152-1f8a4c00-c32a-11e8-9e1a-188dca0df7e7.png">
<img width="1142" alt="capture d ecran 2018-09-28 a 14 31 04" src="https://user-images.githubusercontent.com/24684510/46208479-26fe2500-c32b-11e8-9289-13e4f10c1b36.png">

**Comment by SlvrEagle23** [comment]
@RainbowDash53 Without a doubt, I can see the appeal of wanting to do this. The biggest problem with a self-updater like this, though, is that it requires that PHP have administrative control over not only its own software but other software on the server, including Docker or, on traditional installs, the host server's root permissions.

Updating just the web app code would be possible and fairly straightforward here, but there are often times when updates include both changes to the underlying software _and_ to the AzuraCast web app, and are intended to be updated together so you're always running the latest combination of both. This would require a significant escalation of privileges that would be difficult (if not impossible) to ensure is 100% safe.

**Comment by RainbowDash53** [comment]
I agree, with you it might be complicated to set up. Thank you for your quick response;)
