### ISSUE TITLE
MIME type ('application/json') is not executable.

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#821]
**Installation method**
Traditional install

**Host OS (for Docker installations)**
ubuntu 18.04.1 LTS

**Describe the bug**
```
To access the meta data information of the stream the status-json.xsl is not not executable 
Refused to execute script from 'http://streamurl.com/radio/8000/status-json.xsl?callback=parseMusic&_=1538158016263' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled. 
```

**To Reproduce**
1. Go to your 'http://streamurl.com/radio/8000/status-json.xsl'
2. download window will appear

**Expected behavior**
Display the file in browser and be able to execute.

**Screenshots**
<img width="1059" alt="screen shot 2018-09-28 at 19 09 47" src="https://user-images.githubusercontent.com/7961/46225763-2cbb3100-c352-11e8-8198-ac370309f96e.png">

**Desktop (please complete the following information):**
 - OSX
 - Chrome
 - Version 69.0.3497.100

**Comment by SlvrEagle23** [comment]
@macbroadcast I understand that you're trying to get your Wordpress radio player working in this situation, but it's clearly not working very well with the AzuraCast proxied connection. I didn't build the plugin and I don't know how it's managing specific HTTP requests, so I don't know how to resolve this issue. I do know for sure that the fact that the `status-json.xsl` page appears as a download in your browser is not related to this; the `application/json` content type is _correct_ for that file, and you're likely running into differences between the way browsers operated when the plugin was built and the way they're locked down now.

If possible, I'd highly recommend modifying your Wordpress script to make use of AzuraCast's own [Now Playing API](http://www.azuracast.com/api/index.html#/Now_Playing/App\Controller\Api\NowplayingController::indexAction). Not only does our API provide significantly richer metadata about the currently playing song, but we also have set up our API to respond appropriately to requests and avoid issues like the ones you're encountering.

**Comment by macbroadcast** [comment]
hello @SlvrEagle23 thanks for your reply and understanding, I wasn't aware that the proxied connection handles stuff differently and thought I could add a http://www.htaccess-guide.com/adding-mime-types/  to the .htaccess file and its all fixed 😸 I definitely check out the Now Playing API and will integrate it at a later point, if you say its more powerful. 👍

**Comment by SlvrEagle23** [comment]
@macbroadcast In this regard, it's far more powerful. It includes:
 - The artist/title/album/artwork of the current song, including custom metadata if you specify it in the system
 - How long the current song is, and how far into playback it is in seconds
 - The same info for both the next song about to play and the previous _x_ songs (usually 5)
 - The name of the live DJ if one is broadcasting
 - Detailed station information and a link to each stream the station manages
