### ISSUE TITLE
Make Access-Control-Allow-Origin on API responses configurable

### ISSUE THREAD

**Issue by VTCAKAVSMoACE** [AzuraCast/AzuraCast#826]
**Is your feature request related to a problem? Please describe.**
We use a custom website for our radio endpoint, so we need to have the ability to request from our site. We can configure most of the CORS headers in our nginx file, but the API section can cause double entry problems for our headers (clients refuse `*, *`).

**Describe the solution you'd like**
Just get rid of [these three lines](https://github.com/AzuraCast/AzuraCast/blob/master/src/Middleware/Module/Api.php#L53) or make it configurable in the interface so we can allow for requests from other sites.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Note: we have removed these three lines and configured this in nginx instead. We are using a traditional installation

**Comment by SlvrEagle23** [comment]
@VTCAKAVSMoACE Making a HTTP GET request to submit a song request for a station is always allowed per the CORS header. This is how such functionality as the embeddable requests page (visible from the station profile) can work. You shouldn't need to modify the CORS headers in order to allow for this. All other public API requests served via GET requests have the header set permissively because the vast majority of use-cases outside AzuraCast itself require this.

**Comment by VTCAKAVSMoACE** [comment]
There's a few cases that fail:
 - Preflight requests (using the OPTIONS method) sent by Chrome browsers do not succeed (no Access-Control-Allow-Origin header).
 - Failed requests (too recent/already requested) return 400, which prevents the section of code that adds the Access-Control-Allow-Origin header (or scrubs it somehow; all I know is that repeated checking of this response shows that this header is not there).

**Comment by SlvrEagle23** [comment]
@VTCAKAVSMoACE I've updated the relevant sections of code to more properly handle the CORS preflight OPTIONS request. The second item may be related to the first, as I checked repeatedly and the Access Control headers are all present even for the non-200 pages.

Please update your installation and let me know if this helps resolve the issue.

**Comment by VTCAKAVSMoACE** [comment]
Resolved. Sorry for the lack of response, I believed I responded to this thread already.
