### ISSUE TITLE
New scheduling option : play every X minutes during a customized schedule

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#827]
I would need to personalize the jingles that are played for example during
- week-end
- scheduled playlist

I would need a new scheduling option to play a jingle - every X minutes or per X songs  - during one or multiple time-ranges.

A different approach would be to attach a jingle playlist to an existing scheduled playlist.

**Comment by SlvrEagle23** [comment]
@griffon56 It's now possible to set playlists to play "once per x minutes", and to specify playlists as "jingle" playlists, which will strip the metadata so it isn't shown in the stream. This should resolve the issues you reported.
