### ISSUE TITLE
Request Song Not Working

### ISSUE THREAD

**Issue by CodeSteele** [AzuraCast/AzuraCast#830]
**Installation method**
Traditional -- Reproducible on demo though.

**Describe the bug**
Request song feature does not list songs to request.

**To Reproduce**
1. Enable request song feature on station
2. Go to public page
3. Click request song

**Expected behavior**
A list of songs to choose from should be visible

**Screenshots**

![image](https://user-images.githubusercontent.com/31152835/46329207-f68fe280-c5d9-11e8-9630-a60b588e1da6.png)

**Comment by CodeSteele** [comment]
If I had to wager a guess it was this commit:

https://github.com/AzuraCast/AzuraCast/commit/ef04117d5452c2a523df10732600611d92ae868c#diff-15b13ad1b6efb69a056824f63cc7297e

JS that loads the list form AJAX doesn't seem to be firing... digging more.

**Comment by CodeSteele** [comment]
Moving the JS to the inline call moved it to the top of the page

https://github.com/AzuraCast/AzuraCast/commit/ef04117d5452c2a523df10732600611d92ae868c#diff-99a1793b52a73a162a6c15b04213ba0bR43

`var request_dialog = $('#modal-request');` is firing before the DOM is ready, returning 0 items, all further events are bound to nothing.

**Comment by CodeSteele** [comment]
Opened PR #831

**Comment by SlvrEagle23** [comment]
That's good detective work @CodeSteele!

Merged and verified to be resolved on local.
