### ISSUE TITLE
Autoplay is not playing sounds anymore after Docker update

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#832]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
After updating, autoplay is not producing sounds but artist title, artwork and counter is still working. Just no sounds...

**To Reproduce**
http://www.radioscristianas.com - but I removed /autoplay already...

**Expected behavior**
Make the autoplay work again

**Screenshots**

**Desktop (please complete the following information):**
All Mac browsers

**Smartphone (please complete the following information):**
Hwuawei Chrome mobile

**Comment by CodeSteele** [comment]
Can confirm on https://demo.azuracast.com/public/azuratest_radio/autoplay, icon swapped to the stop button _like_ it is autoplaying but it isn't.

Possibly similar to #830?

**Comment by ErnestPH** [comment]
Thanks! In my case, it was the embedded code by the way… it seems working when browsing on a direct link… but not the embed one

**Comment by SlvrEagle23** [comment]
@ErnestPH @CodeSteele My local tests are showing that autoplay is being initiated correctly, but the browser is explicitly preventing it, as there's no user action that initiated the audio playback.

Almost all mobile browsers, and an increasing number of desktop browsers, are disabling autoplaying audio, and deliberately don't expose any API to the browser to indicate whether autoplay is enabled or not (lest it be abused by bad web sites).

While there are arguably some ways around this new prevention of autoplay, my recommendation at this point is simply not to use it. It's not a default setting for any page on AzuraCast, and anything we could implement would be against the wishes of the browser and, frankly, many of the users.

**Comment by CodeSteele** [comment]
Yeah, it explicitly calls it out in the console window:

`Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD`
