### ISSUE TITLE
Listener Stats Enhancement

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#833]
Is it possible to add a timestamp when they begin listening to listener stats?
It would also be nice if i would be able to choose in custom range the hours. e.g. from 14pm to 16pm. So i could see the stats for a specific DJ/Show.
And last one. A CSV export would be great.

Very big THANK YOU to all developers and contributors. Very good work!

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39030/allow-custom-time-hourminute-range-in-listener-stats
