### ISSUE TITLE
Highlight Newly Uploaded Songs

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#835]
Is it possible to send the songs only to the selected folder?

**Comment by SlvrEagle23** [comment]
@jonikane I'm not sure what you mean. You should be able to just click the folder name and enter the folder, then drag and drop to upload as many songs into that folder as you like.

**Comment by jonikane** [comment]
What I'm trying to say is that when we send the songs, they only show the ones that are not already in the folder.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38927/highlight-newly-uploaded-songs
