### ISSUE TITLE
After updating to latest version, throws 500 error Adapter not found: 0, Adapters.php : 48

### ISSUE THREAD

**Issue by vineettalwar** [AzuraCast/AzuraCast#836]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 16.x.

**Describe the bug**
I did a git pull, 
./docker.sh update 
After that,  it shows,
500 error 
Adapter not found: 0
Adapters.php : 48
It have shown on terminal as well as it is showing the same after login as well. 

Terminal Output:

`Refreshing All Stations
-----------------------

Router cache file cleared.
Local cache flushed.
Restarting all radio stations...
Restarting station #1: Stream

In Adapters.php line 48:
                        
  Adapter not found: 0

azuracast:setup [--update] [--load-fixtures]

2018/10/05 12:55:54 Command exited with error: exit status 1`

**Expected behavior**
Login should work . stations should work.

So, installation failed completely,  not sure what have gone wrong and looking forward to get your feedback on it. 
Regards,

**Comment by SlvrEagle23** [comment]
@vineettalwar I'm really not sure what's happened here. That error message indicates that your station has reached a state that it shouldn't have ever been able to reach, with a broadcast adapter that isn't one of the standard ones.

Did you finish the initial setup process before updating?

**Comment by vineettalwar** [comment]
I always updated, via 
./docker.sh update
and thats it no other step was needed and it worked always. 
Could you please guide on how this can be fixed ?

**Comment by SlvrEagle23** [comment]
@vineettalwar That's what I'm trying to do.

When you try to visit the AzuraCast instance, what is it doing? Is the station running? Can you log in at all?

**Comment by vineettalwar** [comment]
When I visited the Azuracast installation. The login screen was available. As soon as I hit the login button. It have shown a big black screen. 
in center of the page  with error message
"500" 
In Adapters.php line 48:

Adapter not found: 0
""

**Comment by vineettalwar** [comment]
Also, as per the message on command line,  in the first comment. 
'
azuracast:setup [--update] [--load-fixtures]
'

as,
docker-compose run --rm cli azuracast_cli azuracast:setup --update --load-fixtures

It fixed the issue of 500 adapter error. 
However, it did reset the stations I guess. Can't  login as well. 
while restarting it shows 4 AzuraCast test radio. 
However, data on docker machine for other stations exists at, /var/azuracast/stations

**Comment by SlvrEagle23** [comment]
@vineettalwar Try logging in, then immediately going to `/admin/stations` and editing your station and setting it to use an available frontend.

For some reason, your station had its frontend adapter reset to a value that isn't valid. This should reset it.

**Comment by SlvrEagle23** [comment]
@vineettalwar You also should not have manually executed the setup command with the `--load-fixtures` flag. It's listing that as an optional argument, and you shouldn't just go executing commands with all of their optional arguments.

Fortunately, load-fixtures doesn't tend to delete items; it just creates some duplicate new records.

I'm worried at this point that you've hosed your AzuraCast instance in some way or another. The only way I could know for sure would be to take a look at it personally.
