### ISSUE TITLE
Question : Statistics Overview

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#840]
If I do a new installation on my VPS server, and I make a backup of the AzuraCast folder, is it possible to retrieve my old statistics from the backup folder?

**Comment by SlvrEagle23** [comment]
@ckeurk The only official supported backup/restore method is via a Docker installation. You can migrate your existing installation from a traditional one to a Docker one using the `docker-migrate.sh` script, then back the Docker version up, which will include the database, all station media, and the statistics.
