### ISSUE TITLE
Uploading File In Context Of Playlist Doesn't Auto-Add To Playlist

### ISSUE THREAD

**Issue by CodeSteele** [AzuraCast/AzuraCast#842]
Navigating to `Playlists` > `default` and uploading a song drops it outside of the playlist you have selected.

Took a moment to realize that I had to assign a playlist because I _thought_ I was in the context of playlist.

**Comment by SlvrEagle23** [comment]
@CodeSteele That just makes so much intuitive sense that once you mentioned it, I expected it to work that way despite knowing it wasn't programmed to. Now it does!
