### ISSUE TITLE
Music Files add creation date

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#843]
For the music files page, is it possible to add the creation date in addition to the name of the modified and size?
in relation to the metadata of the mp3

**Comment by SlvrEagle23** [comment]
@ckeurk Unfortunately, because of our work preparing AzuraCast to support S3 and other remote audio sources, we switched to the Flysystem abstraction library, and can no longer easily retrieve the file creation timestamp, as it's not constant for remote filesystems, only local ones.
