### ISSUE TITLE
Icecast KH version

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#845]
**Installation method**
Traditional installation method.

**Host OS (for Docker installations)**
Ubuntu 18.04

**Describe the bug**

Hello

Is the current Icecast version not the kh 10 version?
I updated the Azuracast and here continues the version kh 7.

Is it a bug or is it right?

![icecast_kh_version](https://user-images.githubusercontent.com/7109309/46634350-825cbe00-cb48-11e8-8475-721b3b8cca19.jpg)

**Comment by CodeSteele** [comment]
We did end up forking IceCast to add proper support for x-forwarded-for headers behind Docker....

https://github.com/AzuraCast/icecast-kh-ac

I did _not_ update the version but I should be branched off of KH10, so while it won't report KH10-AC1 it _should_ report KH10, so let me look into that....

**Comment by CodeSteele** [comment]
Actually this is likely due to it being the traditional install method... 🤔 I'll look into that too.

**Comment by CodeSteele** [comment]
@jonikane is this a fresh install? If not have you been running `update.sh`? It should automatically pull KH10 (0689b13 includes the upgrade to KH10).

Also: we currently have a KH-10-AC1 fork we maintain, though I'm not sure if we care to update to that (it's mostly changes for running under Docker), going to open a PR for it anyway and let @SlvrEagle23 make a call on that.

**Comment by SlvrEagle23** [comment]
@jonikane If you update now, it should properly update to reflect that you're running our direct fork of Icecast-KH-10, which includes improvements for reverse proxy handling.

**Comment by jonikane** [comment]
It is not a fresh installation. I have run the update.sh but the version continues KH7.

Do I have to do new installation for the KH10 version?

**Comment by CodeSteele** [comment]
It _shouldn't_, I'm deploying a traditional install right now at 220a4aa which installs KH7 which I'll then upgrade to KH10 then KH10-AC2.

**Comment by CodeSteele** [comment]
Yep, I'm on  63bdc35 (should be KH10), KH7 installed. Running update does nothing. Docker task looks right.

**Comment by CodeSteele** [comment]
@jonikane I've submitted a PR that should remedy the issue. Let me know if it doesn't after it's approved and you pull/run it.
