### ISSUE TITLE
Mute button not changing when "unmuting" using the volume bar

### ISSUE THREAD

**Issue by aljaxus** [AzuraCast/AzuraCast#847]
**Installation method**
docker

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
Mute button does not change when "unmuting" using the volume bar

**To Reproduce**
1. Go to public page of any station
2. Click on mute button
3. Click anywhere on volume bar to unmute the volume
4. See error - mute button will remain the same

**Expected behavior**
mute button should get "unmuted"

**Desktop (please complete the following information):**
 - OS: Windown 10
 - Browser opera
 - Version 56.0.3051.36

**Comment by Vaalyn** [comment]
This issue can be closed. The volume slider was updated and now the buttons do not change when muting/unmuting but are both visible at the same time.

**Comment by aljaxus** [comment]
True.
