### ISSUE TITLE
API, api key missing 500 internal server error

### ISSUE THREAD

**Issue by MyTheValentinus** [AzuraCast/AzuraCast#849]
**Installation method**
Docker

**Describe the bug**
When you go to `/api/station/1/listeners` for example, if you dont send apikey, server return 500 internal server error instead of 403.

`Attribute "user" is not of type "App\Entity\User". Request.php : 191`

**Comment by Vaalyn** [comment]
This bug is not occuring anymore and was most likely fixed with 9c66beee79051426f02fc9f78ef63ff1c0edd107
