### ISSUE TITLE
Songs go not play

### ISSUE THREAD

**Issue by TorchwoodPL** [AzuraCast/AzuraCast#850]
**Installation method**
Docker

**Host OS (for Docker installations)**
 16.04.5 LTS

**Describe the bug**

**To Reproduce**
1. Go to http://radio.expij.h-y.eu/public/expijowo
2. Try to hit play

**Expected behavior**
Song start to play isntad of that it stops, also there is no cover.

**Screenshots**
---

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera
 - Version 55.0

**Smartphone (please complete the following information):**
---

**Additional context**
---

**Comment by MyTheValentinus** [comment]
Hello,
Can you send logs, please ?
I'am not abble to reproduct

**Comment by LordHelmchen666** [comment]
http://127.0.0.1:8000/radio.mp3?1539262981
This cant work. ;)
Set it to your public URL.

**Comment by MyTheValentinus** [comment]
@LordHelmchen666, not a good practice.
@TorchwoodPL Logs of your stations and nginx container

**Comment by LordHelmchen666** [comment]
???
URL should be http://radio.expij.h-y.eu:8000/radio.mp3?1539262981
127.0.0.1 = localhost

**Comment by TorchwoodPL** [comment]
Yes I know that loccalhost issue, but I do not hange anything, it just went by itself like that. Ho do I change it?

**Comment by TorchwoodPL** [comment]
Ok I disabled auto URL and that fixed the issue, error was because of reverse proxy for nginx that I set. My nginx is set to run on port 81, and in reverse proxxy it is set to localhost:81

**Comment by SlvrEagle23** [comment]
@TorchwoodPL Glad to hear the issue is fixed. :)
