### ISSUE TITLE
Auditor display blocked

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#851]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 18.04

I have a small problem with the display of the number of listeners, it remains blocked 
![capture d ecran 2018-10-10 a 05 31 41](https://user-images.githubusercontent.com/379099/46711970-0731ff80-cc4f-11e8-8934-81503eff73b5.png)
even the "Reports" page is in the same case
![ca](https://user-images.githubusercontent.com/379099/46712007-33e61700-cc4f-11e8-8172-9a1a5bca9ff5.png)
even if you do an update 😞
Thank you for your help.

**Comment by MyTheValentinus** [comment]
Hello,
Your stream still work ? Withtout interruption ?

**Comment by ckeurk** [comment]
I understood the problem, it came from "Remote Relays". I had put too much address, I only have one left and the listeners' display has gone back to normal
