### ISSUE TITLE
request api should be exclude lyrics data

### ISSUE THREAD

**Issue by Protomothis** [AzuraCast/AzuraCast#858]
<img width="547" alt="2018-10-13 6 45 55" src="https://user-images.githubusercontent.com/8805965/46903980-48106980-cf18-11e8-9611-3150acb16c78.png">
request api always bind lyrics data.
then request search too slow.
In my opinion, lyrics data should be excluded.

**Comment by SlvrEagle23** [comment]
@unbreakhyek The idea with the existing API responses is that they should be identical across multiple API endpoints, so the response you get from listing requests has the same metadata in the same arrangement as the main `/nowplaying` API response.

In this case, that results in an excess of information in one place, and while that may have some impact on performance (given the recent improvements to pagination on the requests system, I'm not entirely sure the performance impact is as significant as described), it's excellent for data type consistency in any structured application consuming our APIs.

I'll look into possible optimizations here, but the intra-API consistency is something I view as an asset for the API overall.

**Comment by SlvrEagle23** [comment]
Closing as maintaining the consistency of the API's responses across endpoints is our highest priority currently, and none of the data supplied via the song API entity significantly impacts the performance of the system.
