### ISSUE TITLE
Please Read: A Personal Update from the Developer

### ISSUE THREAD

**Issue by SlvrEagle23** [AzuraCast/AzuraCast#860]
Hello AzuraCast station operators, contributors and listeners! 

As you may have noticed, AzuraCast's popularity has continued its steady climb, with the project having almost 300 stars on GitHub right now. When I first built this software many years ago, I could never have imagined it would be seen as useful to so many people. Above all else, I want to thank everyone who has offered support in the form of encouraging words, telling your friends and colleagues about AzuraCast, and donating to keep the project running.

I wanted to take some time to update everyone on my personal situation, so that any delays in responding to new bug/error reports or enhancement requests can be better understood.

Currently, I'm in the process of filing for Chapter 7 bankruptcy. In the United States, this bankruptcy filing is the most significant one a private citizen can undertake, where almost all of their credit card and medical debt is discharged, but at a significant, 10-year penalty to their credit score.

My whole adult life, I've been living with chronic clinical depression. I've gone through medication after medication and therapist after therapist, yet despite my best efforts to treat my condition, starting in about 2014 it suddenly got significantly worse. Since then, I've only been able to work as an independent contractor for brief periods before depression episodes struck again. For a majority of the year, I'm not able to work at all. At first, I was living on my savings, then I had to withdraw my retirement early (with a steep penalty), and then I was counting on credit cards to hold me over in the gaps between employment.

Now, even that isn't working. The monthly minimum payments for my credit cards outstretch my available income almost twofold, leaving me with no choice but to be late on payments and to watch helplessly as creditors begin their harassment campaigns, calling me at all hours of the day to collect and taking huge sums of available credit away from me all at once.

The only option I have left at this point is bankruptcy. At age 31, this means I probably can't own a house or have a normal credit card again until I'm 41, and I'm not entirely confident that's an age I'll be around to see. Needless to say, I am very afraid for what the future holds, and I have lost more sleep than I care to admit as my financial world comes crumbling around me in recent months.

If you're wondering if this in any way affects AzuraCast's status as free and open-source software, let me reassure you that the answer to that is unequivocally **"no."** I have never stopped believing in the power that we developers have to make life better for people when we contribute to the public good, and AzuraCast is my contribution to the public, as small and unimportant as it may be in the big picture. This software was always meant to be a humble, free alternative to monolithic, proprietary tools that not only weren't accessible to all users but weren't evolving to meet the changing needs of the web, and it will always remain that way.

Over the next few months, however, there is a significant legal process ahead of me. Part of the bankruptcy filings include combing over every inch of your income and expenses in a very invasive way. The creditors themselves may even see fit to interrogate me or go after me further. Thankfully, I have the assistance of an attorney who has agreed to work with me pro-bono on account of my lack of income.

What this means for AzuraCast is that there will likely be long periods where you don't see the kind of constant, daily updates you've become accustomed to over the last two years. There will be times when I simply don't have the willpower or time or energy to both keep fighting my legal struggle and to respond to questions or issues on GitHub.

During this time, all I ask for is your patience. Many of you have been very generous and patient in waiting for me to get around to your issues already, and I ask that you continue this empathy and understanding as I work through my personal affairs. The next few months will be very challenging for me. There may be months where I can't afford basic living expenses. I'm hoping for the best, but the future at this point is entirely an unknown.

Donation or payment is not required, nor will it ever be, to use AzuraCast. If you want to support me during this time, however, your support would mean more than you can imagine. You can find the details of how to support both me and AzuraCast's infrastructure and continued development [on our donation page](https://www.azuracast.com/donate.html).

Thank you for reading, and thanks for being a part of my labor of love. <3

**Comment by amavarick** [comment]
Thank you so much for developing such a great piece of software that has been so helpful to all of us.  If you're ever feeling down, take solace in knowing that there are so many people who are so very thankful for your many many hours of work and thought to this project.

**Comment by ckeurk** [comment]
I sincerely hope that your future will change in the right direction and that happiness will finally share your life.
Thank you very much for your work.

**Comment by ErnestPH** [comment]
We are very grateful of your work! I am trying my best to donate monthly although I don't have big revenues… but your work is superb and it needs support. Hopefully, a big support will help you in your current status.

**Comment by Ilario42** [comment]
A story that makes you cry. Know that we are close to you, you have developed a fantastic software that everyone can afford thanks to its gratuity, including myself, one of them.

We will be here to support you, I wish you a good luck friend!

**Comment by NeddyPlays** [comment]
Its sad to see.

I want to thank the world that you developed this fantastic software and always be there for us!

**Comment by MyTheValentinus** [comment]
Thanks for the project. I wish you a good continuation in your future life
I would be happy to financially help the project by this way. You have my telegram and my email.

**Comment by MyTheValentinus** [comment]
Thanks for the project. I wish you a good continuation in your future life
If you need servers or hosting platform to help the project i can give you. I would be happy to financially help the project by this way. You have my telegram and my email.
