### ISSUE TITLE
Autologin request

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#861]
**Is your feature request related to a problem? Please describe.**
No

Request:
Like Centovacast, they have a url with the username and password, so the user can auto login. I this possible with Azuracast? But if not, it's still Ok.

Thanks!

ErnestPH
Follower

**Comment by ErnestPH** [comment]
Hi SlvrEagle23!

Can we also include an auto renewal for let's encrypt?

Thanks!

**Comment by deinstreamserver** [comment]
You can use a form like that for doing auto-login.

`<form action="AZURACAST-URL/login" method="post">
           <input type="hidden" name="username" value="AZURACAST-USERNAME/EMAIL">
           <input type="hidden" name="password" value="AZURACAST-PASSWORD">
		   <input type="submit" value="Log In">
</form>`

**Comment by deinstreamserver** [comment]
You can use a form like that for doing auto-login.

<form action="AZURACAST-URL/login" method="post">
           <input type="hidden" name="username" value="AZURACAST-USERNAME/EMAIL">
           <input type="hidden" name="password" value="AZURACAST-PASSWORD">
		   <input type="submit" value="Log In">
</form>

**Comment by ErnestPH** [comment]
> You can use a form like that for doing auto-login.
> 
> form action="AZURACAST-URL/login" method="post"
> input type="hidden" name="username" value="AZURACAST-USERNAME/EMAIL"
> input type="hidden" name="password" value="AZURACAST-PASSWORD"
> input type="submit" value="Log In"
> /form
> 
> Please add < and > every line. Code Insert doesn't working actually.

Have you tested it?

**Comment by deinstreamserver** [comment]
> > You can use a form like that for doing auto-login.
> > form action="AZURACAST-URL/login" method="post"
> > input type="hidden" name="username" value="AZURACAST-USERNAME/EMAIL"
> > input type="hidden" name="password" value="AZURACAST-PASSWORD"
> > input type="submit" value="Log In"
> > /form
> > Please add < and > every line. Code Insert doesn't working actually.
> 
> Have you tested it?

Yes, sure. I've tested it on my own AzuraCast Installation.

If you got some userdata in a database you can replace username and password automatic.

**Comment by ErnestPH** [comment]
Ahh Ok I was talking about the azuracast login page… do you have your link?

**Comment by deinstreamserver** [comment]
I think I know what you mean and for what you need it. 

If you want send me an E-Mail maybe with skype, discord or something else contact to info@just-in-web.de
I think I can help you much more  :)

**Comment by ErnestPH** [comment]
Ok thank you… Now I got it. :) - this request was simply forgotten but now I remember why I asked for it… thanks again for the tip!

**Comment by deinstreamserver** [comment]
No Problem. If you want and can send me an email :P I have an idea for you. I've seen your website and for that I think I just get something for you

**Comment by ErnestPH** [comment]
Ok sure. I will thanks for the help
