### ISSUE TITLE
Save output to file (solved)

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#865]
Hello, i need to save the output for the last two month. Because of law in Germany.
When i add the following code liquidsoap cant start anymore.
`output.file(%mp3,
 "/radioarchive/stream-%Y-%m/-%d/%Y-%m-%d-%H_%M_%S.mp3",
 reopen_when={60m},
 radio)
`
This should create one mp3 file every 60m. 
Any idea why Liquidsoap wont start with this code?

**Comment by SlvrEagle23** [comment]
@LordHelmchen666 You need to save the *actual radio signal* for 2 months? Are you sure this isn't referring to logs of the songs that were played? You can save that length of time in song logs with AzuraCast.

I don't see anything immediately obvious about that line that would cause problems, but you can run `docker-compose logs -f stations` to see what error is being produced when it tries to start up.

**Comment by LordHelmchen666** [comment]
I am sure. http://www.gesetze-bayern.de/(X(1)S(ccmoydnyeawtyi40nwjjdvzh))/Content/Document/BayMG-29?AspxAutoDetectCookieSupport=1
Translation:

> (2) Each provider must record and retain its contributions in sound and image; they are to be made available to the state headquarters on request free of charge.
(3) 1 The provider may delete records after two months from the date of the last distribution if he has not become aware of a complaint or complaint against the contribution. 2 The national center may provide for deviations. 

I try to play a bit around with it in a virtualbox image.
