### ISSUE TITLE
Icecast connections failing

### ISSUE THREAD

**Issue by suricloud** [AzuraCast/AzuraCast#866]
**Installation method**
Indicate whether you are using the "Docker" or "Traditional" installation method.
Docker
**Host OS (for Docker installations)**
Centos 7

**Describe the bug**
Streaming live radio stations keep failing using icecast although the ports are open in compose file.When switching to shoutcast it just connects en works but icecast keep connecting ( using butt stream app)

**Comment by CodeSteele** [comment]
As part of side discussion on #867 I had BUTT giving me some troubles, where stopping/restarting BUTT seemed to fix it most of the time... really quite odd.

I'll have to loop back around and pull logs on that, I _think_ some tweaks I did help resolve that, if that's the case I'll put that here.

**Comment by CodeSteele** [comment]
Checking the Icecast logs:

```2018/10/21 02:05:52 [lang:3] Authenticating DJ: steele
2018/10/21 02:05:53 [lang:3] AzuraCast DJ Auth Response: true
2018/10/21 02:05:53 [lang:3] AzuraCast DJ Auth Response: true
2018/10/21 02:05:53 [lang:3] AzuraCast Live Connected Response: ["received"]
2018/10/21 02:05:53 [threads:3] Created thread "harbor source feeding" (2 total).
2018/10/21 02:05:53 [input_streamer:3] Decoding...
2018/10/21 02:05:53 [input_streamer:2] Feeding stopped: Ogg.End_of_stream.
2018/10/21 02:05:53 [lang:3] DJ Source disconnected!```

It repeats this rapidly, sometimes, randomly, it'll work under BUTT, but this can be anything from a handful of tries to like... a hundred. Not sure what the cause is.

**Comment by CodeSteele** [comment]
Interesting detail: when it did work, I only get the auth response _once_.... so why do I get it twice under BUTT?

**Comment by suricloud** [comment]
I see, mixxx is a dj software.Would be better if someone could create a free open source stream connecter like butt just to connect live radio streaming with icecast/shoutcast.
Maybe  Azuracast can create its own streaming client for windows and other os :)

**Comment by CodeSteele** [comment]
So you're just connecting to and replying another stream?

I _think_ we can do that today natively without an application effectively proxying it, or not if I don't think it'll be a huge change, I'll have to check with @SlvrEagle23 though.

**Comment by CodeSteele** [comment]
The other option may be to hit up the BUTT issue tracker and see why their software seems to be rapidly connecting/disconnecting.

**Comment by suricloud** [comment]
> So you're just connecting to and replying another stream?
> 
> I _think_ we can do that today natively without an application effectively proxying it, or not if I don't think it'll be a huge change, I'll have to check with @SlvrEagle23 though.

Yes using Butt to connect local radio stations trough azuracast icecast streaming.

**Comment by CodeSteele** [comment]
@suricloud do you have any better luck trying to connect under Shoutcast mode? The dev instance I'm running won't let me do that AFAIK.

**Comment by suricloud** [comment]
Yes shoutcast is connecting instanty and seems to be running stable.

**Comment by CodeSteele** [comment]
OK, going to consider that a valid workaround for now. Let me know if you have any further issues.
