### ISSUE TITLE
Renaming a created folder directory got a 404 error...

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#868]
**Installation method**
Docker
**Host OS (for Docker installations)**
Ubuntu 18
**Describe the bug**
404 error when click the RENAME button under Music Files
**To Reproduce**
1. Go to 'Music Files Tab'
2. Create a New Folder
3. Rename the folder by clicking RENAME button
4. Error is 404 - [object%20Object] - The page you requested was not found.

**Desktop (please complete the following information):**
 - Safari Browser

**Comment by SlvrEagle23** [comment]
@ErnestPH Valid issue! Should be fixed as of the latest update. Thanks for the report.

**Comment by ErnestPH** [comment]
Thank you for the quick fix but unfortunately the bug now moves to the saving…

Once I change the name… click save button, the error below occurs. So the name can't be updated

500

Call to undefined method App\Http\Response::redirectToRoute()
FilesController.php : 104

**Comment by ErnestPH** [comment]
UPDATE

- the song was renamed. But the error when updating is there

**Comment by SlvrEagle23** [comment]
@ErnestPH Unrelated issue, but should now also be fixed.

**Comment by ErnestPH** [comment]
I see. Ok. thanks again. Can I closed this issue, or only you can do it?

**Comment by SlvrEagle23** [comment]
@ErnestPH Already closed :)
