### ISSUE TITLE
Text "Playlist" cut off in Safari browsers only

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#869]
**Installation method**
Docker
**Host OS (for Docker installations)**
Ubuntu
**Describe the bug**
After the recent updates… the web player text "Playlist" is cut off. All browsers except Safari is working

**Screenshots**
https://prntscr.com/l7cyzk

**Desktop (please complete the following information):**
- Mac Safari latest version for Sierra

**Comment by ErnestPH** [comment]
When I updated Azuracast to the latest version and check out safari… it's still cutting off the text…
So I went and check the file _card.scss… but I don't see the recent commit.

I did clear cache and restart

Is the changes implemented in the latest version or should I wait for an update? Thanks @SlvrEagle23

**Comment by SlvrEagle23** [comment]
@ErnestPH You're definitely not on the latest version then, as it's been showing more accurate version numbers for quite a while.

Try running

```
./docker.sh update-self && ./docker.sh update
```

**Comment by ErnestPH** [comment]
Hmm… I did that also. I think this has to do with caching from cloudflare… I guess I'll just have to wait… Thanks

**Comment by SlvrEagle23** [comment]
@ErnestPH Is your update script returning any errors? You absolutely shouldn't be seeing a version of AzuraCast that's multiple weeks old, and Cloudflare shouldn't have anything to do with that.

**Comment by ErnestPH** [comment]
Nothing at all… 

`[OK] AzuraCast is now updated to the latest version!`

I believe I have the latest one (the slider volume)

My instance is a docker uBuntu 18 one click app from Digital Ocean.

**Comment by SlvrEagle23** [comment]
@ErnestPH That's literally all it says? There should be a long log...

**Comment by ErnestPH** [comment]
Probably this one?

`2018/11/07 00:59:08 Command finished successfully.
azuracast_influxdb_1 is up-to-date
azuracast_redis_1 is up-to-date
azuracast_mariadb_1 is up-to-date
azuracast_stations is up-to-date
azuracast_web_1 is up-to-date
Creating azuracast_letsencrypt_1 ... done
Creating azuracast_cli_1         ... done
Creating azuracast_nginx_1       ... done
Creating azuracast_cron          ... done
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.
`

**Comment by ErnestPH** [comment]
Oh probably this one…

> 2018/11/07 00:58:51 Waiting for: tcp://mariadb:3306
2018/11/07 00:58:51 Waiting for: tcp://influxdb:8086
2018/11/07 00:58:51 Problem with dial: dial tcp 172.25.0.5:3306: connect: connection refused. Sleeping 1s
2018/11/07 00:58:51 Problem with dial: dial tcp 172.25.0.3:8086: connect: connection refused. Sleeping 1s
2018/11/07 00:58:52 Connected to tcp://mariadb:3306
2018/11/07 00:58:52 Problem with dial: dial tcp 172.25.0.3:8086: connect: connection refused. Sleeping 1s
2018/11/07 00:58:53 Connected to tcp://influxdb:8086
Updating AzuraCast (Environment: production)
fatal: not a git repository (or any parent up to mount point /var/azuracast)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

others are the normal logs already...

**Comment by ErnestPH** [comment]
No I have not… ok I will update the compose file based on that one and run update again. thanks!

I really think this is because of the Docker one app click from DO instead of the normal uBuntu 18 droplet...

**Comment by ErnestPH** [comment]
Or this could be a BUG? I will investigate further. thanks @SlvrEagle23
