### ISSUE TITLE
Installation on server with cPanel

### ISSUE THREAD

**Issue by tommyinnn** [AzuraCast/AzuraCast#871]
Hi I can't find any information on final installation on cPanel server, using just the ip address does not work, is there a port I can use? Thanks

**Comment by SlvrEagle23** [comment]
@tommyinnn Just so you know, I don't recommend installing AzuraCast on a cPanel server. cPanel is very opinionated about how its software stack is set up and wants to manage every aspect of the LAMP stack in particular, which AzuraCast would frequently override. If you're using Docker, there's a possibility it will work fine, but cPanel won't know about the AzuraCast installation. In either case, it's unsupported, and I would always recommend using a "clean" VPS for your AzuraCast instance.
