### ISSUE TITLE
Port 8000 stays closed

### ISSUE THREAD

**Issue by NeddyPlays** [AzuraCast/AzuraCast#873]
Hi,

I've got a problem. For some kind of reason the port 8000 stopped working.
I've checked the docker-compose file and there the 8000 port is uncommented, so it should be open. The Ubuntu Firewall itself is turned off.

**Comment by SlvrEagle23** [comment]
@NeddyPlays What do you mean it "stopped working"? If you connect to it, nothing happens? Did you recently update AzuraCast, or restart the radio stations, or the server itself, or anything?

This is not a very descriptive bug report.

**Comment by NeddyPlays** [comment]
Hi sorry for the lack of description.

When i first installed it worked. But it stopped working. I didn't update the server. 
I only restarted the whole server.

I only changed some settings to go via port 80 and 443
![image](https://user-images.githubusercontent.com/37535577/47256323-8c52bb00-d47e-11e8-8df4-1164be40ec6c.png)

**Comment by JDBlackman** [comment]
Are you sure this isn't a server config, have you allowed port 8000 through ufw or whatever firewall you are using?

Is something else already running on port 8000?

**Comment by NeddyPlays** [comment]
![image](https://user-images.githubusercontent.com/37535577/47261276-c39b8900-d4cb-11e8-8066-b51299edbbb1.png)
Can't see a V4 ip adres in there...

**Comment by ErnestPH** [comment]
Is this a VPS server? Please check the firewall configuration and add TCP open to 8000-8999.

**Comment by NeddyPlays** [comment]
I did Firewall is completely turned off.

**Comment by ErnestPH** [comment]
instead of turning off. Just open the specific TCP port… that's how I did it and it let's me connect back to ice cast setup server. but if your azuracast version is not updated. Please update and you won't need this settings anymore...

**Comment by NeddyPlays** [comment]
Thats also not working. Iam using v0.9.0-2018.10 Beta. Everything else is working fine from Streamers logging in to requesting.

**Comment by NeddyPlays** [comment]
Apparently Cloudflare was causing this problem. Disabled the Cloudflare SSL for the Radio Server and now its working!

**Comment by ErnestPH** [comment]
I really don't think there is a global error for this... as I have been using cloudflare and it's working smoothly. When I checked your post earlier... always use https was not set to yes. That could be the problem.
