### ISSUE TITLE
Question: Back Up Files and Settings

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#874]
Creates a .tar.gz backup copy of the media, statistics and metrics of every station, along with a copy of the full AzuraCast database. You can later restore from this same file in the event of data loss or corruption.

Where I can find the backup file "backup.tar.gz" ?

**Comment by SlvrEagle23** [comment]
@ckeurk If you don't manually specify an output filename, it should put the `backup.tar.gz` file right there in the same directory as your AzuraCast installation. You can specify a custom path, and it should put it there instead.

**Comment by ckeurk** [comment]
Great, thank you.
