### ISSUE TITLE
ERROR: Couldn't find env file: /opt/azuracast/azuracast.env

### ISSUE THREAD

**Issue by amavarick** [AzuraCast/AzuraCast#878]
Docker
Ubuntu 16.04.4 LTS

**Describe the bug**
ERROR: Couldn't find env file: /opt/azuracast/azuracast.env
Of course my radio does not work now.  I can only assume that during the update, the azuracast.env file was not restored?  How do I recover/resolve this?

**To Reproduce**
Just perform basic updates, don't have test environment readily to try to reproduce.  I've not made any backend changes... just regular updates.

```
ls /opt/azuracast/
docker-compose.backup.yml  docker-compose.yml  docker.sh

```
The steps I take to update my instance include:
```
cd /opt/azuracast
./docker.sh update
ERROR: Couldn't find env file: /opt/azuracast/azuracast.env
ERROR: Couldn't find env file: /opt/azuracast/azuracast.env
Update docker-compose.yml file? This will overwrite any customizations you made to this file? [y/N] y
Your existing docker-compose.yml file has been backed up to docker-compose.backup.yml.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3395  100  3395    0     0  17624      0 --:--:-- --:--:-- --:--:-- 17682
New docker-compose.yml file loaded.
ERROR: Couldn't find env file: /opt/azuracast/azuracast.env
ERROR: Couldn't find env file: /opt/azuracast/azuracast.env
ERROR: Couldn't find env file: /opt/azuracast/azuracast.env
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
```

**Comment by CodeSteele** [comment]
Looks like 5ee858f caused it, let me see what can be done to make this work.

At _first_ guess you can maybe copy `.env` to `azuracast.env` and it _may_ work, not sure if more variables need to be configured in it yet though...

**Comment by CodeSteele** [comment]
https://github.com/AzuraCast/AzuraCast/commit/5ee858f615e4104be35b45ffb64ff63bba0f2456#diff-51df7a7eb9518d36a5475c9cff55f3cbR82

Yep it looks like the default environment file was changed. Just renaming the file should work fine.

@SlvrEagle23 you okay with us detecting .env and moving it?

**Comment by SlvrEagle23** [comment]
@amavarick We announced this one on our twitter:
https://twitter.com/AzuraCast/status/1053144044203896832

The `docker.sh` utility script already _does_ create the `azuracast.env` file if it doesn't exist, you just have to update to the latest version of the utility script by running `docker.sh update-self` before the update.

This is one of those back-compatibility breaking changes that we have no real way of communicating to our users (as we don't know who they are) unless they follow our social media. Sorry about that!

**Comment by amavarick** [comment]
```
docker.sh update-self
./docker.sh update
```

This worked great, all settings there and radio is back up!  Thank you!

PS: I'll make a note to look at Twitter before submitting an issue.  I usually look through open and closed issues to see if something could be a duplicate before sending... I'll start looking on the twitter feed.  I don't have social media so I tend to be behind the times  in that area and didn't even think to look on Twitter.
