### ISSUE TITLE
Https from cloudflare?

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#881]
Hi, I've run the normal azuracast setup, so I'm having problems with lets encrypt. Can I use cloudflare for azuracast? (Https). If yes, what should I do?
Sincerely!

**Comment by tehcojam** [comment]
Enable these options in the System Settings (`azuracast.tld/admin/settings`).
![image](https://user-images.githubusercontent.com/18071040/47267173-69490980-d559-11e8-89cd-a21112da2431.png)

**Comment by Ilario42** [comment]
@tehcojam and from config nginx?

**Comment by CodeSteele** [comment]
@Ilario42 depends on your Cloudflare config, if you're Full/Full (Strict) you'll need Let's Encrypt working properly. If you have it set to "Flexible" it should be fine with just the changes @tehcojam recommends.

**Comment by CodeSteele** [comment]
You should be seeing this image:

![Cloudflare](https://support.cloudflare.com/hc/en-us/article_attachments/201814387/error522.png) if AzuraCast wasn't working for CloudFlare.

And not getting a `ERR_CONNECTION_TIMED_OUT` error on your browser. Something outside of Azuracast isn't properly configured.

**Comment by Ilario42** [comment]
The error I get is not cloudflare, it is this:

![image](https://user-images.githubusercontent.com/22561729/47270196-61449600-d568-11e8-85d3-aaea558661c9.png)

**Comment by CodeSteele** [comment]
Yeah, something is _really_ not configured correctly. I'd have to see your Cloudflare DNS config.

**Comment by ErnestPH** [comment]
> Hi, I've run the normal azuracast setup, so I'm having problems with lets encrypt. Can I use cloudflare for azuracast? (Https). If yes, what should I do?
> Sincerely!

I have been using both (Let's encrypt and Cloudflare) without any issues…

1. Install let's encrypt - in the setup always redirect all to https
2. Set cloud flare to FULL (not FULL strict)
3. In Azuracast - yes to https and web proxy
