### ISSUE TITLE
liquidsoap.log not rotated

### ISSUE THREAD

**Issue by MyTheValentinus** [AzuraCast/AzuraCast#885]
**Installation method**
Docker
**Host OS (for Docker installations)**
Ubuntu 18.04

**Describe the bug**
The file `liquidsoap.log` was not rotated and gzip in `/stations/STATION_NAME/config/` folder

**Comment by CodeSteele** [comment]
https://www.liquidsoap.info/doc-1.3.4/in_production.html

> You should not override the log.file.path setting because a logrotate configuration is also installed so that log files in the standard directory are truncated and compressed if they grow too big.

Logrotate is included with LiquidSoap but only if we don't move the log files -- which considering we have a log file per station is not an option.

We'll probably want to port the logrotate script: https://github.com/savonet/liquidsoap/blob/e6159a6ef5481c251cac7283a4e61425b43fbf40/scripts/liquidsoap.logrotate.in

**Comment by MyTheValentinus** [comment]
`start-stop-daemon --stop --signal USR1 --quiet --pidfile $liq` this scripts stop service ? Not good for H24 station ?

**Comment by CodeSteele** [comment]
Yeah, applications sometimes catch the USR1 signal to reopen log files.

As for Liquidsoap, it should obey it as of couple years ago:
https://github.com/savonet/liquidsoap/issues/363

**Comment by MyTheValentinus** [comment]
That is not real stop signal, but much a signal that stop logging for a moment and re-create file ?

**Comment by CodeSteele** [comment]
OK talked to @SlvrEagle23 about this one and he brings up a good point: Docker is going to log all these messages that come through stdout/stderr anyway, so the log is redundant.

We'll be removing the log file and depending on pulling logs from Docker, _much_ easier than us messing with logrotate/sending signals to liquidsoap/etc.

**Comment by MyTheValentinus** [comment]
Yeah, i think that is good idea, but how to separate logs by stations ? Add indicator at the begin of the line ?

**Comment by Vaalyn** [comment]
If we add a kind of "station tag" at the beginning of each log output like `[station name]` then it would be easier to identify at what entries one has to look when searching for the logs of a specific station.

This would also make it possible to use a log aggregator to parse the logs from `docker logs azuracast_stations` or use a logging driver like fluentd to process the logs, split them up and make them available for centralized logging solutions.

**Comment by SlvrEagle23** [comment]
@Vaalyn @MyTheValentinus This was already implemented in the last few days. I renamed a number of the variables used by the Liquidsoap configuration to include the station name, so the logs will be much clearer about which station is doing what when running `docker-compose logs -f stations`.

I am keeping this issue open because log rotation still needs to be set up for Liquidsoap, in order to use the web-based log viewer tool.

**Comment by MyTheValentinus** [comment]
Yeah, nice !
Thanks

**Comment by SlvrEagle23** [comment]
@MyTheValentinus The Liquidsoap log file should now be rotated hourly by AzuraCast, which will send the proper signal over to Liquidsoap itself to inform it of the rotation taking place and will ensure it rolls over smoothly without interruption.
