### ISSUE TITLE
playlist.once?

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#890]
All playlists in liquidsoap.liq are in this style 
`playlist_default = audio_to_stereo(playlist(reload_mode="watch",mode="randomize","/var/azuracast/stations/eisradio/playlists/playlist_default.m3u"))`
I like to have the ability to make a playlist `playlist_ads = audio_to_stereo(playlist.once(reload_mode="watch",mode="normal","/var/azuracast/stations/eisradio/playlists/playlist_ads.m3u"))` 
and play it at every x:45 (8:45, 9:45, 10:45, 11:45, ...)
Is it possible?

**Comment by SlvrEagle23** [comment]
@LordHelmchen666 This was implemented in recent versions of AzuraCast, though we didn't mark this enhancement as completed separately.
