### ISSUE TITLE
Volume slider instead of clicking the line (web player embed)

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#892]
Just a feature request…

Currently, volume can be controlled (increase or decrease) by clicking the line. However, it would be better to use a slider option… where we just drag the mouse or fingers sideways…

Thanks!
ErnestPH

**Comment by SlvrEagle23** [comment]
This is definitely something we want to implement across the system. The flat "progress bar" style volume selector is a leftover from several generations ago, when we used jPlayer, which we no longer need to use thanks to HTML5 audio.

**Comment by SlvrEagle23** [comment]
@ErnestPH The radio volume selectors and playback controls have finally been updated to reflect the capabilities of our new theme, and now use the `<input type="range">` selector, with 0% volume as a "mute" button at the left and 100% volume at the right. This should not only be more accessible but more intuitive.

**Comment by ErnestPH** [comment]
Wow! Thank you. I will try it once I am on my workstation.
