### ISSUE TITLE
ERROR: Couldn't find env file: /root/azuracast.env - when updating using ./docker.sh update

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#893]
**Installation method**
Docker
**Host OS (for Docker installations)**
Ubuntu 18
**Describe the bug**
When updating Azuracast using docker.sh I get an error about Couldn't find env file: /root/azuracast.env
**To Reproduce**
1. connected via SSH
2. update Azuracast using ./docker.sh update����
3. Got this error

> root@live:~# ./docker.sh update����
ERROR: Couldn't find env file: /root/azuracast.env
ERROR: Couldn't find env file: /root/azuracast.env
Update docker-compose.yml file? This will overwrite any customizations you made to this file? [y/N] y
Your existing docker-compose.yml file has been backed up to docker-compose.backup.yml.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3395  100  3395    0     0  89342      0 --:--:-- --:--:-- --:--:-- 89342
New docker-compose.yml file loaded.
ERROR: Couldn't find env file: /root/azuracast.env
ERROR: Couldn't find env file: /root/azuracast.env
ERROR: Couldn't find env file: /root/azuracast.env
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.
Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]
Remove one or more images

**Desktop (please complete the following information):**
 - OS: MacOS Sierra
 - Coda 2

**Comment by ErnestPH** [comment]
I just restore my backup… thanks

ErnestPH

**Comment by SlvrEagle23** [comment]
@ErnestPH This was mentioned on our Twitter, since we have no other real means of broadcasting updates out to every user of the software:
https://twitter.com/AzuraCast/status/1053144044203896832

The new best practice for ensuring that you have the very latest of both the updater and the software itself is to run `./docker.sh update-self && ./docker.sh update` together like so.

**Comment by ErnestPH** [comment]
Thanks! Never view twitter. I should probably view from time to time. Awesome update!

ErnestPH
