### ISSUE TITLE
Allow seeking through song in preview player

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#895]
**Is your feature request related to a problem? Please describe.**
Currently i have to Listen the complete Song

**Describe the solution you'd like**
That i can Forward and backward on the Track Preview.

**Comment by ErnestPH** [comment]
I think this would be unfair for the "other listeners" of that same station… :) So I think this would not be implemented. However, as the administrator or owner of the station, skipping could be done under Profile tab.

**Comment by preterive** [comment]
I speak about the song preview... Current there is only a Option to change the volume.

**Comment by ErnestPH** [comment]
that could be hard to implement but not impossible

**Comment by preterive** [comment]
Why hard? This is a simple Html5 audio player moving forward via JavaScript.

**Comment by preterive** [comment]
https://www.itorian.com/2012/05/using-javascript-to-control-playback-of.html?m=1

**Comment by ErnestPH** [comment]
In a sense that you might not be the only listener for "that" station. And having that feature might also affect other listener's preferences… IMO

**Comment by preterive** [comment]
I speak about the Track preview not about the live Stream.

**Comment by preterive** [comment]
If you don't understand it:
![image](https://user-images.githubusercontent.com/31483348/47954197-c09e9f00-df87-11e8-85a4-03869886463e.png)
Another Button there

**Comment by xewl** [comment]
It's a preview-player. Why would you want to use this other than listening to 1 single file?

The playlist/file pages are not real playlists for that player, so it wouldn't even know about a "next song".

When actually listening to a station from within the Profile page, this isn't a good place to add such functionality either, as it would imply that liquidsoap also needs to receive this as a command, and that's where your listeners will be affected.

It's better to be safe; to keep it as it is now.

**Comment by SlvrEagle23** [comment]
I was thinking about replacing the radio player on the file manager page with something like the fixed-width Soundmanager player at the bottom of this page:

http://www.schillmania.com/projects/soundmanager2/demo/bar-ui/

(In fact, I really like this UI in general and would consider using it elsewhere too...)

**Comment by ErnestPH** [comment]
the current player is great for simplicity… but of course, we welcome any changes from you

**Comment by preterive** [comment]
"It's a preview-player. Why would you want to use this other than listening to 1 single file?"
If i want to listen if the Track is good for a playlist or not i don't want to hear the complete track.

**Comment by preterive** [comment]
> It's a preview-player. Why would you want to use this other than listening to 1 single file?
> 
> The playlist/file pages are not real playlists for that player, so it wouldn't even know about a "next song".
> 
> When actually listening to a station from within the Profile page, this isn't a good place to add such functionality either, as it would imply that liquidsoap also needs to receive this as a command, and that's where your listeners will be affected.
> 
> It's better to be safe; to keep it as it is now.

I don't want to listen more than one file. I only want to move forward and backwards in the Song.

**Comment by SlvrEagle23** [comment]
@preterive I've renamed the issue to hopefully clear up some confusion.

**Comment by preterive** [comment]
Thanks! My english is Bad.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39031/allow-seeking-through-song-in-preview-player
