### ISSUE TITLE
Analytics bug returns

### ISSUE THREAD

**Issue by jrsarath** [AzuraCast/AzuraCast#899]
![capture](https://user-images.githubusercontent.com/29149814/47590322-9ba79c00-d989-11e8-9252-d8453f0c96f7.PNG)
![capture1](https://user-images.githubusercontent.com/29149814/47590325-9d715f80-d989-11e8-988c-b98a5f652efa.PNG)
Analytics bug returned for live listeners, it was working after i updated as suggested on this thread  https://github.com/AzuraCast/AzuraCast/issues/293 it was working after update suddenly it stopped working again.. any suggestions ? 
OS : Ubuntu 16
INSTALLATION METHOD: DOCKER

**Comment by pabpineda** [comment]
We are already two with the same problem, I use ubuntu 18.04 and it was working well for a while, until I had this same problem.

**Comment by SlvrEagle23** [comment]
@jrsarath @pabpineda From the administration homepage, you should see a "Now Playing" synchronization task near the bottom of the page. Click the button to run that manually. You should see either an error or the raw output from the Now Playing logs. Let me know what these logs say, or if there is any error message visible.

**Comment by jrsarath** [comment]
Hey, after doing what you asked for, analytics works again. whats the problem here

**Comment by SlvrEagle23** [comment]
@jrsarath If you go back to the administration page, does the Now Playing task say it was last run when you ran it, or more recently? Like, is it running every 15 seconds?

**Comment by jrsarath** [comment]
yep as i see its says it has been ran within last 15 sec

**Comment by SlvrEagle23** [comment]
@jrsarath That should be working normally then. Not sure what fixed it...

**Comment by jrsarath** [comment]
i wonder too..maybe its just my user, who must have done something sketchy, and was complaining about the analytics, thank you though, really appreciate it

**Comment by pabpineda** [comment]
This is my screenshot, I already did the aforementioned and the error continues.
![screenshot_2018-10-30 sync task output](https://user-images.githubusercontent.com/42784360/47741995-4c8b9080-dc41-11e8-925e-1071bccdd0bf.jpg)

Also if I set my bitrate to 128kbps, the system always throws me at 64kbps

**Comment by SlvrEagle23** [comment]
@pabpineda Although your issue looks similar to the other issue reported here, I think it may be different.

It doesn't look like AzuraCast is doing anything wrong in this case; it's correctly handling now playing data, but it thinks there isn't any to display.

I would likely not be able to diagnose that issue further without being able to take a look at your actual installation. If you want to go that route, you can e-mail me with your instance URL.

**Comment by pabpineda** [comment]
I have reviewed the installation in digitalocean, and I have noticed that there are no other folders that go after /var/azuracast so I think the installation not may be correct. I'm going to do everything from scratch and verify that everything is in place.

**Comment by SlvrEagle23** [comment]
@jrsarath If your installation is the Docker type, you won't see a `/var/azuracast` folder on the host computer; it will be inside the Docker containers.

**Comment by jrsarath** [comment]
@SlvrEagle23 im good now,
@pabpineda has the same problem, you have some confusion about who is talking about what. . clear it out :) 
thanks again
