### ISSUE TITLE
Slow performance when adding songs to a bigger playlist

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#901]
**Installation method**
Docker

**Host OS (for Docker installations)**
Operating System: Debian GNU/Linux 9
Kernel: Linux 4.9.0-5-amd64
Architecture: x86-64

**Describe the bug**
When adding a song to a playlist the time it takes to finish this action increases dramatically depending on the amount of songs already added to the playlist. This is due to the `reshuffleMedia()` method of the `StationPlaylistMediaRepository`. When a song was added to the playlist this method executes a query for each song that exists in the playlist. So for example when the playlist contains 600 songs and 1 song is added the `reshuffleMedia()` method will execute 601 `UPDATE` statements. To decrease the execution time of this action the queries should be send in a single transaction to the database.

**To Reproduce**
1. Go to Music Files page
2. Open network browser console
3. Add a few hundred songs to a playlist 
4. See that the response time for the action increases dramatically

**Expected behavior**
Adding songs to a playlist that contains a bunch of songs should not take over 10-20 seconds.

**Desktop (please complete the following information):**
- OS: macOS High Sierra Version 10.13.6
- Browser: Google Chrome
- Version: 69.0.3497.100 64bit

**Comment by SlvrEagle23** [comment]
@Vaalyn The problem is very likely valid, I just don't see it in local test instances as mine often don't have hundreds of songs built up. Solution looks like it does what it should. Good work again. :)
