### ISSUE TITLE
Error: No Available Stations

### ISSUE THREAD

**Issue by ohld** [AzuraCast/AzuraCast#906]
Hi again!

I don't know how to describe the error. I've done these things:

1) Everything works really fine
2) I've created the backup for the whole radio
3) I have not done anything in 1-2 months
4) I've visited my radio station site and see this error:

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/5613295/47641758-f272c880-db77-11e8-84a8-ebe12803eec4.png">

I've tried to `docker rmi` Azura's images, tried to reboot, tried to load the station from backup that I've created 1-2 months ago - still this error. What can I do?

BTW I still have the station in 'System Administration' section

<img width="731" alt="image" src="https://user-images.githubusercontent.com/5613295/47641930-61e8b800-db78-11e8-9ce9-74d2713c5b9e.png">

**Comment by ohld** [comment]
I've also tried these commands:

``` bash
./docker.sh cli orm:generate-proxies
./docker.sh cli cache:clear
docker-compose down
docker volume rm azuracast_tmp_data
docker-compose up -d
./docker.sh update
```

Nothing helped

**Comment by SlvrEagle23** [comment]
@ohld Did you disable the station? From the station administration page, click "Manage", then edit the profile and check that this setting isn't turned on.

The issue may also be permissions related. Make sure your account has the permission to view the station's page from the Permissions manager.

**Comment by ErnestPH** [comment]
Yes mostly this error occurred when a user setting has untick a permission level that is connected to a radio station.

**Comment by ohld** [comment]
Thanks1 I just enable the station in "Manage Station" -> "Edit". Thanks11
