### ISSUE TITLE
Autodj skips song and I hear the azuracast jingle?

### ISSUE THREAD

**Issue by stemvantwente** [AzuraCast/AzuraCast#907]
**Installation method**
"Traditional" installation method.

**Host OS (for Docker installations)**
Ubuntu 1804 (VPS)   |    Ubuntu 1604 same problem.

**Describe the bug**
autodj plays song sometimes few seconds. sometimes longer then a minuut, and this happens random. It skips the song and I hear the azuracast jingle, this radio station is powered by azuracast sometimes a few seconds sometimes the whole jingle. If I check in playlist is see this:

11:34:50	Roland W. - Monja
11:34:45	live  
11:31:41	Fransje Neutelings - Bij Ons Thuis Is Altijd

That *live* is when I hear the jingle, I checked the song, downloaded the mp3 file and the song plays fine "complete"

Problem is that it is a random song, so everytime this happens its not the same song.

Have updated azuracast to the latest version.

I hope my english is good enough the understand :)

Here a screenshot with another song, it says Live but the song is in playlist Nederlands.
[`screenshot`](http://piratenradio.nl/liveerrorazura.jpg)
Greets
Roy

**Comment by stemvantwente** [comment]
> @stemvantwente It sounds like something is going wrong between Liquidsoap and the AzuraCast "next song" API call.
> 
> Check the logs to see if you can find out more. There's a new "Log Viewer" page you can find under the "Utilities" section of your station; you'll want to look at `Liquidsoap Log` (liquidsoap.log) for more information.

mmmm I cannot find that option :S I can find playlists, duplicated songs etc but not the log vieuwer.

Greets

**Comment by SlvrEagle23** [comment]
@stemvantwente It is a new feature, so you may need to update your AzuraCast instance to see it.

Also, you can view the same logs by accessing the server via a shell terminal and running `tail -f /var/azuracast/stations/(your_station)/config/liquidsoap.log`.

**Comment by stemvantwente** [comment]
Found it

here a log:

2018/10/31 22:09:48 >>> LOG START
2018/10/31 22:09:48 [main:3] Liquidsoap 1.3.3
2018/10/31 22:09:48 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.3.4 dtools=0.4.1 duppy=0.7.3 duppy.syntax=0.7.3 cry=0.6.0 mm=0.4.0 ogg=0.5.2 vorbis=0.7.0 opus=0.1.2 mad=0.4.5 flac=0.1.2 flac.ogg=0.1.2 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 taglib=0.3.3 camomile=0.8.6 faad=0.3.3
2018/10/31 22:09:48 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2018/10/31 22:09:48 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2018/10/31 22:09:48 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2018/10/31 22:09:48 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2018/10/31 22:09:48 [threads:3] Created thread "generic queue #1".
2018/10/31 22:09:48 [threads:3] Created thread "generic queue #2".
2018/10/31 22:09:48 [threads:3] Created thread "non-blocking queue #1".
2018/10/31 22:09:48 [threads:3] Created thread "non-blocking queue #2".
2018/10/31 22:09:48 [harbor:3] Adding mountpoint '/' on port 8005
2018/10/31 22:09:48 [playlist_jingels(dot)m3u:3] Loading playlist...
2018/10/31 22:09:48 [playlist_jingels(dot)m3u:3] No mime type specified, trying autodetection.
2018/10/31 22:09:48 [playlist_jingels(dot)m3u:3] Playlist treated as format application/x-mpegURL
2018/10/31 22:09:48 [playlist_jingels(dot)m3u:3] Successfully loaded a playlist of 4 tracks.
2018/10/31 22:09:48 [playlist_polka(dot)m3u:3] Loading playlist...
2018/10/31 22:09:48 [playlist_polka(dot)m3u:3] No mime type specified, trying autodetection.
2018/10/31 22:09:48 [playlist_polka(dot)m3u:3] Playlist treated as format application/x-mpegURL
2018/10/31 22:09:48 [playlist_polka(dot)m3u:3] Successfully loaded a playlist of 108 tracks.
2018/10/31 22:09:48 [playlist_engelsenduits(dot)m3u:3] Loading playlist...
2018/10/31 22:09:48 [playlist_engelsenduits(dot)m3u:3] No mime type specified, trying autodetection.
2018/10/31 22:09:48 [playlist_engelsenduits(dot)m3u:3] Playlist treated as format application/x-mpegURL
2018/10/31 22:09:48 [playlist_engelsenduits(dot)m3u:3] Successfully loaded a playlist of 1062 tracks.
2018/10/31 22:09:48 [playlist_nederlands(dot)m3u:3] Loading playlist...
2018/10/31 22:09:48 [playlist_nederlands(dot)m3u:3] No mime type specified, trying autodetection.
2018/10/31 22:09:48 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/piratenradionl_247_de_beste_piratenhits/media/Jingels/Jingle - Website jingel.mp3".
2018/10/31 22:09:48 [playlist_nederlands(dot)m3u:3] Playlist treated as format application/x-mpegURL
2018/10/31 22:09:48 [playlist_nederlands(dot)m3u:3] Successfully loaded a playlist of 1599 tracks.
2018/10/31 22:09:48 [playlist_jingels(dot)m3u:3] Prepared "/var/azuracast/stations/piratenradionl_247_de_beste_piratenhits/media/Jingels/Jingle - Website jingel.mp3" (RID 3).
2018/10/31 22:09:48 [piratenradiojukebox_local_1:3] Connecting mount /jukeboxazura for source@127.0.0.1...
2018/10/31 22:09:48 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/piratenradionl_247_de_beste_piratenhits/media/Polka/Frank Novak - Peek A Booh Polka.mp3".
2018/10/31 22:09:48 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/piratenradionl_247_de_beste_piratenhits/media/Duits/Marc Andre - Die Spatzen Pfeiffen Es Vom Dach.mp3".
2018/10/31 22:09:48 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/piratenradionl_247_de_beste_piratenhits/media/Nederlands/VtotZ/Vader Abraham - Geluk.mp3".
2018/10/31 22:09:48 [lang:3] AzuraCast Raw Response: annotate:title="Rose vom worthersee",artist="Karawanken Quintett":/var/azuracast/stations/piratenradionl_247_de_beste_piratenhits/media/Duits/Karawanken Quintett - Rose vom worthersee.mp3
2018/10/31 22:09:48 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/piratenradionl_247_de_beste_piratenhits/media/Duits/Karawanken Quintett - Rose vom worthersee.mp3".
2018/10/31 22:09:48 [piratenradiojukebox_local_1:3] Connection setup was successful.
2018/10/31 22:09:48 [threads:3] Created thread "wallclock_main" (1 total).
2018/10/31 22:09:48 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2018/10/31 22:09:48 [piratenradiojukebox_live_switch:3] Switch to piratenradiojukebox_playlist_fallback.
2018/10/31 22:09:48 [piratenradiojukebox_playlist_fallback:3] Switch to switch_5937.
2018/10/31 22:09:48 [switch_5937:3] Switch to fallback_5927.
2018/10/31 22:09:48 [fallback_5927:3] Switch to delay_5925.
2018/10/31 22:09:48 [piratenradiojukebox_next_song:3] Prepared "/var/azuracast/stations/piratenradionl_247_de_beste_piratenhits/media/Duits/Karawanken Quintett - Rose vom worthersee.mp3" (RID 8).
2018/10/31 22:09:48 [piratenradiojukebox_playlist_fallback:3] Switch to piratenradiojukebox_cue_cut with transition.
2018/10/31 22:09:48 [dummy:3] Source failed (no more tracks) stopping output...
2018/10/31 22:09:48 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/piratenradionl_247_de_beste_piratenhits/media/Jingels/Jingle - Piratenradio.nl.mp3".

22:09 it failed and I hear the azuracast jingle over and over again, the jingle of this station is powered by azuracast....

What can cause this?

**Comment by SlvrEagle23** [comment]
@stemvantwente The important part of the log is what happened immediately before this in the logs...it seems that something caused Liquidsoap to crash.

Also, those log entries appear to be normal. Is the station broadcasting fine after that point?

**Comment by stemvantwente** [comment]
> @stemvantwente The important part of the log is what happened immediately before this in the logs...it seems that something caused Liquidsoap to crash.
> 
> Also, those log entries appear to be normal. Is the station broadcasting fine after that point?

When it fails and I hear the azuracast jingle sometimes it takes less then 5 seconds and I hear music from my playlist again, sometimes I hear the jingle of azuracast complete and sometimes multiple times before my own music is played again.

**Comment by SlvrEagle23** [comment]
@stemvantwente I understand what's going wrong, but I can't diagnose what's actually causing that unless I have the logs for what happens immediately as that crash is happening. If you only have the logs from after the crash recovers, that won't tell me what caused the crash.

**Comment by stemvantwente** [comment]
here a link to the complete liquidsoap_log.json 
[liquadsoap log](http://piratenradio.nl/liquidsoap_log.json)

**Comment by defcon8** [comment]
i'm afraid this issue is still alive.i just had this issue 5 minutes ago. Here is the liquidsoap log:
`2019/01/02 20:04:07 [server:3] New client: 172.18.0.4.
2019/01/02 20:04:07 [server:3] Client 172.18.0.4 disconnected.
2019/01/02 20:04:07 [the_zen_lounge_local_1:3] Performing user-requested skip
2019/01/02 20:04:07 [the_zen_lounge_next_song:3] Finished with "/var/azuracast/stations/the_zen_lounge/media/zen_music_for_balance_and_relaxation-5Bfull_album-5Dhd_-_youtube.mp3".
2019/01/02 20:04:07 [the_zen_lounge_playlist_fallback:3] Switch to switch_6356 with forgetful transition.
2019/01/02 20:04:07 [lang:3] AzuraCast Raw Response: annotate:title="Zen",artist="Zen",duration="4019.":/var/azuracast/stations/the_zen_lounge/media/best_meditation_music_.._oliver_shanti_vol._i.mp3
2019/01/02 20:04:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/the_zen_lounge/media/best_meditation_music_.._oliver_shanti_vol._i.mp3".
2019/01/02 20:04:07 [the_zen_lounge_next_song:3] Prepared "/var/azuracast/stations/the_zen_lounge/media/best_meditation_music_.._oliver_shanti_vol._i.mp3" (RID 5).
2019/01/02 20:04:07 [the_zen_lounge_playlist_fallback:3] Switch to the_zen_lounge_cue_cut with transition.
2019/01/02 21:10:50 [lang:3] AzuraCast Raw Response: /usr/local/share/icecast/web/error.mp3
2019/01/02 21:10:50 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
2019/01/02 21:11:01 [the_zen_lounge_next_song:3] Finished with "/var/azuracast/stations/the_zen_lounge/media/best_meditation_music_.._oliver_shanti_vol._i.mp3".
2019/01/02 21:11:01 [the_zen_lounge_next_song:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 0).
2019/01/02 21:11:07 [lang:3] AzuraCast Raw Response: annotate:title="Zen",artist="Zen",duration="1900.":/var/azuracast/stations/the_zen_lounge/media/best_meditation_music_oliver_shanti_vol._iii.mp3
2019/01/02 21:11:07 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/the_zen_lounge/media/best_meditation_music_oliver_shanti_vol._iii.mp3".
2019/01/02 21:11:19 [the_zen_lounge_next_song:3] Finished with "/usr/local/share/icecast/web/error.mp3".
2019/01/02 21:11:19 [the_zen_lounge_next_song:3] Prepared "/var/azuracast/stations/the_zen_lounge/media/best_meditation_music_oliver_shanti_vol._iii.mp3" (RID 2).`

Powered by AzuraCast • v0.9.1, #55011ee (2018-12-30 10:35) • Docker • PHP 7.2

**Comment by stemvantwente** [comment]
Problem happens to me still also :( its so random, and sometimes allot, problem like 3 mp3 songs good then the next song plays like 10 sec or more and it mixs another song again. Cant figure it out :(

**Comment by stemvantwente** [comment]
@Vaalyn  Thanks! works perfect!

**Comment by SlvrEagle23** [comment]
@stemvantwente I merged @Vaalyn's PR to fix the issue you mentioned. Thanks Vaalyn! :D

Let me know if this has any impact on the other issues you're experiencing.

**Comment by stemvantwente** [comment]
So far still good! no skipping or stop after few seconds mp3. But I saw an screenshot somewhere here of advanced crossfading? but cannot find this in the options at azuracast 0_o maybe the problem is in there?

**Comment by stemvantwente** [comment]
@SlvrEagle23 Have been few days now and still no problems with cut mp3 files, no idea where the problem  comes from if I use the other autodj, have one problem, sometimes a mp3 gives on the azuracast page now playing: Unknown , now did I find this section on github: https://github.com/savonet/liquidsoap/commit/56339633b1ed66bab0479a62f7b28c701e174654

No idea if this will fix it? But have no idea where that file is located, maybe you can help me?

Greets

**Comment by mikedorst** [comment]
I seem to having this issue, whenever I click on "Skip Song" it plays the jingle then continues with a normal song. How do I solve this?
