### ISSUE TITLE
The audio gets stuck, or hangs for a few seconds

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#908]
Traditional

Sometimes the adio hangs and does not start again, or other times it freezes for a few seconds. On my old vps this problem was not present, now I moved to a dedicated server and I have this problem. Can you help me?

**Comment by SlvrEagle23** [comment]
@Ilario42 As per most issues on AzuraCast, we can't diagnose this in any meaningful way without the appropriate logs from your server. In this case, the most useful log will likely be the Liquidsoap log file. You can see this file from the new Log Viewer page (under Utilities in each station's management page) or by running `tail -f /var/azuracast/stations/(station_name)/config/liquidsoap.log`. See [this page](https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#troubleshooting-by-viewing-logs) for more information.
