### ISSUE TITLE
Kick listener from the stream or limitation per IP-address

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#910]
**Is your feature request related to a problem? Please describe.**
There are people faking the listenercount with multiple connections.

**Describe the solution you'd like**
Short term solution: Kick a specific IP-address.
Long term solution: Limitation per unique IP-address.

**Comment by SlvrEagle23** [comment]
@RemBdev This functionality depends on whether your frontend of choice (Icecast/SHOUTcast) supports kicking listeners off the stream. Both pieces of software contain their own administrative interfaces where you can manage current active listeners, bans, etc.
