### ISSUE TITLE
 Digital Ocean Error

### ISSUE THREAD

**Issue by JMultimidia** [AzuraCast/AzuraCast#914]
**Installation method**
Traditional

Ubuntu 16.04

After using the script to install on the Ocean Digital droplet and setting up AzuraCast, I can not connect to the shoutcast. Are there any port locks on the firewall that need to be released?

**Comment by CodeSteele** [comment]
Port 8000 needs to be open if you don't enable web proxy for radio (System Administration > System Settings > Use Web Proxy for Radio), additional ports may need to be opened as you configure more stations.

**Comment by JMultimidia** [comment]
Connect the port, start the encoder and disconnect in 1 second.

**Comment by ErnestPH** [comment]
You have to check the logs for the errors. Utiliets > log viewer. Otherwise, it would be hard for us to guess...

**Comment by JMultimidia** [comment]
2018-11-01 23:42:44	INFO	[SRC 170.239.3.239:55314] SHOUTcast 2 source connection starting.
2018-11-01 23:42:46	ERROR	[SRC 170.239.3.239:55314 sid=1] SHOUTcast 2 source disconnected. Unable to sync to the stream. Please check the source is valid and in a supported format.

MY CONFIG IN MOUNT POINT
AAC+ (MPEG4 HE-AAC v2);
Bitrate do AutoDJ (kbps): 48:

**Comment by ErnestPH** [comment]
Ok thanks - can you verify if it works on mp3? if yes, then probably a bug for AAC+ format...
