### ISSUE TITLE
User Feedback On New Releases

### ISSUE THREAD

**Issue by CodeSteele** [AzuraCast/AzuraCast#915]
This is something we've discussed off and on before -- we have no user feedback or analytics (more on that later).

Would be nice to be able to determine you've upgraded to a new version and possibly ask administrators to provide feedback. Some kind of survey that gets sent to us? Google Forms? Lots of things are options but getting solid feedback on new releases would be good.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38924/add-feedback-collection-directly-into-azuracast
