### ISSUE TITLE
Opt-In Analytics

### ISSUE THREAD

**Issue by CodeSteele** [AzuraCast/AzuraCast#916]
An opt-in system for analytics on _our_ side would be nice. See how many installs are out there, how many stations, minutes of radio played, total listener counts, platforms that it's running on, etc. We'd need a way to call home and load this data, keep it anonymous, _could_ also be used to load support packages in the future (eg: basically pre-fill issues with their deployment setup).

Gives us an idea of our support base, how many traditional vs docker installs, how large some of our bigger instances are, allow us to know where to spend our time.

**Comment by ErnestPH** [comment]
very nice idea!

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38923/collect-better-analytics-optin-for-whos-using-azuracast
