### ISSUE TITLE
Verify Song Playlist Shuffling via Tests

### ISSUE THREAD

**Issue by CodeSteele** [AzuraCast/AzuraCast#917]
We've had a long history of song randomization performing oddly, mostly playing songs too close together when doing randomization -- we moved to a shuffling algorithm (pre-shuffles songs). People are still reporting some weird issues and it would be nice to be able to throw their cases into the suite and validate them there.

Test cases would probably be:

- [ ] Generate list, play through all songs, no songs repeated.
- [ ] Generate a list, play through a few songs, add some items, play through the rest, no songs repeated? All songs included?
- [ ] Generate multiple lists, weigh them, play them, number of playthroughs per list should match weight of the playlist.

(Feel free to keep tacking onto my list @SlvrEagle23)

**Comment by SlvrEagle23** [comment]
The move back to having Liquidsoap handle most AutoDJ situations precludes our ability to write more specialized unit tests for that functionality, but also improves its reliability overall. Closing this as somewhat of a moot issue at this point.
