### ISSUE TITLE
Error on non-x86/x86-64 systems

### ISSUE THREAD

**Issue by CodeSteele** [AzuraCast/AzuraCast#920]
User in #653 had an install fail due to being on ARM.

A check and big "no no no" message would be nice -- not sure how I'm going to test I own nothing ARM. :|

**Comment by SlvrEagle23** [comment]
@CodeSteele Added multiple checks for architecture, distro and release version to fail immediately at the start of the installation process rather than try (and fail) to make it through.

**Comment by CodeSteele** [comment]
Should this be done on Docker too (obviously no distro/release checks but at least architecture)?

**Comment by SlvrEagle23** [comment]
@CodeSteele Docker's actually where we're really close to being able to run AzuraCast on ARM processors, and we just need one or two things to fall into place to get it to work. I'd rather just wait for those.
