### ISSUE TITLE
Transfer azure between servers

### ISSUE THREAD

**Issue by JMultimidia** [AzuraCast/AzuraCast#921]
I need to transfer the azuracast from one server to another. I do not want to install everything again, because it takes a lot of time. Could someone suggest some tool that transfers using the traditional method in ubuntu?

**Comment by CodeSteele** [comment]
Using docker is super easy: https://www.azuracast.com/docker_sh.html#available-commands, so you may want to consider moving to Docker.

For traditional installs you can:
- Backup MariaDB
- Backup InfluxDB
- Backup station directories

And restore those to a new AzuraCast install (make sure to disable AzuraCast services before restoring).

**Comment by SlvrEagle23** [comment]
@JMultimidia It's true, one of the simplest ways to migrate from one instance to another is to first migrate to Docker, then run the Docker backup script to create a `.tar.gz` file, move that file to the new server, then run the Docker restore script to restore it.

**Comment by ErnestPH** [comment]
Another way, if you are using Digital ocean VPS. 

1. take a snapshot
2. create a new droplet from that snapshot.
- it would create you exactly the same azuracast version with all the same files.

optionally, you can also transfer that snapshot to another digital ocean user. So they can create a new droplet out from your snapshot.

**Comment by JMultimidia** [comment]
Thanks for the tip. Unfortunately the previous server is not OD.

**Comment by ErnestPH** [comment]
> move that file to the new server

Is there a way to get the backup from one server to another instead of downloading it to my local machine then upload the backup to the new server? Thanks!
