### ISSUE TITLE
Browser compatibility issue - Slider volume hidden in Firefox Mac

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#923]
**Installation method**

Docker latest build of Azuracast
**Host OS (for Docker installations)**

Ubuntu 18
**Describe the bug**

Volume slider is visible for both Safari and chrome but in Firefox it is hidden

**Screenshots**

[https://prnt.sc/le2um8](https://prnt.sc/le2um8) 
**Device(s):**
macOS Sierra

**Comment by SlvrEagle23** [comment]
@ErnestPH One of the unfortunate consequences of having a developer with no money is that nothing gets tested on a $2,000 Mac ;)

I'm not sure how to even test this on my end.

**Comment by ErnestPH** [comment]
By the way, the issue is only for embedded player. thanks!

**Comment by ErnestPH** [comment]
I will check it on Firefox windows later :)… my Mac is an old one less than $1200 but yeah, I got your point

**Comment by Vaalyn** [comment]
I've checked the embed of the demo installation on my MacBook Pro on `macOS High Sierra 10.13.6 (17G65)` in `Chrome 70.0.3538.77`, `Safari 12.0.1 (13606.2.104.1.2)` and `Firefox 12.0.1 (63.0.1)` and can't reproduce the problem. What Firefox version are you using?

**Comment by ErnestPH** [comment]
> I've checked the embed of the demo installation on my MacBook Pro on `macOS High Sierra 10.13.6 (17G65)` in `Chrome 70.0.3538.77`, `Safari 12.0.1 (13606.2.104.1.2)` and `Firefox 12.0.1 (63.0.1)` and can't reproduce the problem. What Firefox version are you using?

on a Sierra (not High) Firefox Quantum 63.0.1 (64-bit). Thanks! At least, now we have some other Mac users :)
I think this should be fixed if I will update to High Sierra or even Mojave. But I am just afraid my machine will become slower.

**Comment by SlvrEagle23** [comment]
Help AzuraCast work better on Mac products!

https://ko-fi.com/silvereagle

**Comment by Vaalyn** [comment]
@ErnestPH Do you have a link where you can see this bug so that I can check if it has anything to do with the installation?

**Comment by ErnestPH** [comment]
> Help AzuraCast work better on Mac products!
> 
> https://ko-fi.com/silvereagle

Always been a Petreon and Ko fi too :) But for now… just little donations since I don't have good revenues :)

**Comment by ErnestPH** [comment]
> @ErnestPH Do you have a link where you can see this bug so that I can check if it has anything to do with the installation?

Yes, it's on a Facebook page project that was abandoned :), https://www.facebook.com/artbulgariastores/app/134425496630143/?ref=page_internal

**Comment by Vaalyn** [comment]
@ErnestPH Thanks to your link I could reproduce the problem now also on the AzuraCast demo installation. This seems to be related to the `?volume=100` parameter on the embed. When I load the embed without the parameter then it works but when loading it with the parameter it does not work and throws the following JavaScript error:

```
IndexSizeError: Index or size is negative or greater than the allowed amount radio.js:5
setVolume radio.js:37:21
```

**Comment by ErnestPH** [comment]
> @ErnestPH Thanks to your link I could reproduce the problem now also on the AzuraCast demo installation. This seems to be related to the `?volume=100` parameter on the embed. When I load the embed without the parameter then it works but when loading it with the parameter it does not work and throws the following JavaScript error:
> 
> ```
> IndexSizeError: Index or size is negative or greater than the allowed amount radio.js:5
> setVolume radio.js:37:21
> ```

Yes I forgot to mention that it's the volume parameter that caused it. Thanks guys!
