### ISSUE TITLE
Not working after upgrade

### ISSUE THREAD

**Issue by br0kenlink** [AzuraCast/AzuraCast#927]
So i did upgrade, seemed everything working then got one error

> fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ www_base | dirname }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: template error while templating string: no filter named 'dirname'. String: {{ www_base | dirname }}"}

any ideas?
not sure where to look for problems

**Comment by ErnestPH** [comment]
docker upgrade or traditional?

additionally, was it a docker droplet or plain ubuntu OS…

When upgrading, did you use use update-self?

**Comment by br0kenlink** [comment]
It WAS Ubuntu 16.04 install, not a docker.
I did ./upgrade.
Don't matter anymore, I just killed and installed Centos 7 with docker now.
Setting up stations.
Hope it will be more robust than Ubuntu :)

**Comment by CodeSteele** [comment]
Docker instances in general are a bit easier to prevent from having any external influences mess them up, they are generally preferred unless you have _very specific reasons_ to run a traditional install.

This error suggests that `www_base` is _somehow_ null, no clue how that happened.
