### ISSUE TITLE
Error 500 after update

### ISSUE THREAD

**Issue by techbp** [AzuraCast/AzuraCast#929]
**Installation method**

Traditional

**Host OS (for Docker installations)**

**Describe the bug**

After updating my Azuracast to latest version, after logging in to admin, an error that says 500 then some more message below

**To Reproduce**

**Expected behavior**

I was expecting for the update to be successful without errors

**Relevant Logs**

500
An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.short_name AS short_name_3, t0.is_enabled AS is_enabled_4, t0.frontend_type AS frontend_type_5, t0.frontend_config AS frontend_config_6, t0.backend_type AS backend_type_7, t0.backend_config AS backend_config_8, t0.adapter_api_key AS adapter_api_key_9, t0.description AS description_10, t0.url AS url_11, t0.radio_base_dir AS radio_base_dir_12, t0.radio_media_dir AS radio_media_dir_13, t0.nowplaying AS nowplaying_14, t0.nowplaying_timestamp AS nowplaying_timestamp_15, t0.automation_settings AS automation_settings_16, t0.automation_timestamp AS automation_timestamp_17, t0.enable_requests AS enable_requests_18, t0.request_delay AS request_delay_19, t0.request_threshold AS request_threshold_20, t0.disconnect_deactivate_streamer AS disconnect_deactivate_streamer_21, t0.enable_streamers AS enable_streamers_22, t0.is_streamer_live AS is_streamer_live_23, t0.enable_public_page AS enable_public_page_24, t0.needs_restart AS needs_restart_25, t0.has_started AS has_started_26, t0.api_history_items AS api_history_items_27, t0.current_streamer_id AS current_streamer_id_28, t0.current_streamer_id AS current_streamer_id_29 FROM station t0': SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.disconnect_deactivate_streamer' in 'field list'
AbstractMySQLDriver.php : 80

**Screenshots**

http://www.screencast.com/t/u3zTUig4Th1
http://www.screencast.com/t/wSNQJBmxrNu

**Device(s):**
 - Device:  Macbook Pro
 - OS:  Mac OSX High Sierra
 - Browser:  Chrome
 - Version:  Version 70.0.3538.77 (Official Build) (64-bit)

**Additional context**

**Comment by Vaalyn** [comment]
Looks like the migration that add the `disconnect_deactivate_streamer` field to the `station` table was not executed. Did you use the [update script](https://azuracast.com/install.html#traditional-installation) for the traditional installation?

**Comment by techbp** [comment]
Hi thanks for your reply. Hmmmm, how can I do this _"Can you access the database with the credentials that the update script is using?"_?

**Comment by CodeSteele** [comment]
The `using password: no` part has me concerned.

You have a password set in your `env.ini` file correct? Should be called `db_password`

**Comment by CodeSteele** [comment]
Ah, it's likely that install is so old that maybe it didn't get migrated properly.

Try running: `php /var/azuracast/www/util/cli.php azuracast:config:migrate`, this should force the old `app/env.ini` file to be moved/updated to `env.ini`.

After that if you have no errors try running `php /var/azuracast/www/util/cli.php migrations:migrate` to force a migration.

**Comment by CodeSteele** [comment]
Back up your database using this from /var/azuracast/www:

```
# Dump MySQL data into fixtures folder
MYSQL_USERNAME=`awk -F "=" '/db_username/ {print $2}' env.ini | tr -d ' '`
MYSQL_PASSWORD=`awk -F "=" '/db_password/ {print $2}' env.ini | tr -d ' '`

mysqldump --add-drop-table -u$MYSQL_USERNAME -p$MYSQL_PASSWORD azuracast > azuracast-backup.sql
```

Check `azuracast-backup.sql` make sure it appears to have your data in it, it it does you can execute `php /var/azuracast/www/util/cli.php migrations:migrate` and say yes to the prompt, if there are errors we can restore from the azuracast-backup.sql file.

_Additionally_ if you can back up the entire Ubuntu machine (guessing from the username on the command prompt), do that too (snapshots or whatever is supported on the platform).

**Comment by techbp** [comment]
Nice. Thanks! I'll do this and I'll get back to you

**Comment by techbp** [comment]
Worked like a charm! No data loss. Thank you so much for all your help guys

**Comment by CodeSteele** [comment]
Awesome, glad to hear it.
