### ISSUE TITLE
Question: Where can we find the "stations_id" and station_media_id?

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#930]
I am trying yo use the API for /station/{station_id}/art/{media_id} or Returns the album art for a song, or a generic image.

I would like to learn how to use it.

Any ideas or help? thanks guys!

**Comment by Vaalyn** [comment]
Take a look at the[ API documentation page](https://www.azuracast.com/api.html#per-install-api-documentation) on the AzuraCast website. There it is mentioned that you can access the documentation for the API endpoints by visiting `/api` on your AzuraCast installation.

This will open a [Swagger UI](https://swagger.io/tools/swagger-ui/) page where you can call all the API endpoints and see the results. There you find the `Stations: General` section and the `[GET] /stations` endpoint. When you execute this API call you will get a JSON response with all your stations back. This will include the `station_id `. There is currently no API endpoint for retrieving a list of media files for a station so I think you'd need to access the database with a tool like DBeaver and take a look at the `station_media` table and look for the IDs there.

**Comment by Vaalyn** [comment]
If you only need the album art of the current or next song then you can use the `/nowplaying` endpoint to get a URL to the album art. In the response of this endpoint you will find the `now_playing` object and in there you can see the `song` object which has the `art` property. If you song has an album artwork in the ID3 tags you should get a link to that image or if the song has none you will get the default artwork from AzuraCast.

I don't know how your JS code looks like but you can generally just add a AJAX call to the `/nowplaying` API endpoint (if you are not already doing that) and then retrieve the `now_playing.song.art` value for each station. You can also call `/nowplaying/{station_id}` to only get the nowplaying data for that specific station.

**Comment by ErnestPH** [comment]
Very well explained @Vaalyn - you are a savior! Thank you very much!
