### ISSUE TITLE
Live DJ's recording

### ISSUE THREAD

**Issue by br0kenlink** [AzuraCast/AzuraCast#934]
Hi,
DJ's are asking would it be possible to auto record their streams.
Would such a feature be possible, only for Live performances?

I thought maybe could set shoutcast to record it but could end up recording 24/7, as on Live stream, when DJ isn't streaming, there's a jingle going on non stop.

**Comment by SlvrEagle23** [comment]
@br0kenlink I've definitely seen a lot of stations do this, and I absolutely want to be able to incorporate this into AzuraCast. I want to make sure it's done right, though, where the recording settings are customizable and recordings are cataloged by DJ and date/time and can be browsed via the web app.

**Comment by br0kenlink** [comment]
That sounds great!
I'm in a bid of a financial downfall at this very moment but will try to become active sponsor of AzuraCast project in a very short future.
You guys do an amazing job!
Thank you

**Comment by RemBdev** [comment]
@SlvrEagle23 @br0kenlink I'm currently using `output.file(%vorbis, "stream %H:%M:%S.ogg",fallible=true,reopen_when={0m0s}, on_stop=shutdown,live)` in the advanced Liquidsoap configuration. The files are saved in de config directory of the station.

**Comment by kazwashere** [comment]
is this pretty legit script configuration? i would like to implement this
since i want to record my live broadcast.

**Comment by macbroadcast** [comment]
Thanks, @RemBdev  for your input, would be great to have a place to put all these handy little code snippets :smile:

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38931/automatically-record-live-dj-streams

**Comment by ivellios1988** [comment]
@RemBdev can you tell how is 'live' defined in your liquidsoap.liq?

**Comment by ivellios1988** [comment]
Is it possible to force liquidsoap to create a new file each time a DJ starts streaming?
