### ISSUE TITLE
No .m3u file available

### ISSUE THREAD

**Issue by br0kenlink** [AzuraCast/AzuraCast#935]
Hi,
I recently moved my installation to docker on Centos 7 host.
When I had AzuraCast standard installation, there was possibility to download .PLS and .M3U files from Azuracast Player Page.
Now it's only .PLS available.
Same in the station profile, when I click "Download .M3U" it downloads .PLS.
Also would there be a way to to make .PLS file give http:// link instead https://,
it seems some audio players, eg. Winamp have problem connecting to https:// feed, works fine in VLC.
Would appreciate help with it

**Comment by Vaalyn** [comment]
The download of an .m3u is returning a .pls because of this [line here](https://github.com/AzuraCast/AzuraCast/blob/master/src/Controller/Frontend/PublicController.php#L55) where AzuraCast tries to retrieve a `GET` or `POST` parameter but the route itself is defined as `/public/{station}/playlist[/{format}]` so the `format` is not a parameter but a route argument which needs to be provided in the controller method that the route is calling.

**Comment by br0kenlink** [comment]
Nice one mate.
Any idea about https links causing some clients not to connect?
I'm sure Winamp and Subsonic has problem with https links, we were testing it yesterday and today.

**Comment by Vaalyn** [comment]
Sorry no idea. Currently haven't used Winamp for years and never used Subsonic. If you have a log file or error messages I could take a look at them and try to figure out what the problem could be then.

**Comment by xewl** [comment]
It's a high possibility that older versions (as there's a new one arising right now) of Winamp don't support Let's Encrypt certificates, as they're newer. It's quite normal, and you can't do much about it other than using an Extended Validation certificate from providers like eg. Comodo. (To note: Java has also suffered from this very thing, off-topic)

Those clients, you could still point towards the direct stream endpoint, eg. `{ip/domain}:port/mount`
(If you provide playlist files on a web portal for eg. "Winamp", put those endpoints as the second in the list, it should skip to it when the first in list -with https://- doesn't validate)

**Comment by br0kenlink** [comment]
Yeah, noticed it is about Lets Encrypt cert. For now using as you suggested http:// .
Can't wait for new Winamp :) Such a big fan boy, never stopped using it.
Thanks
