### ISSUE TITLE
Quick question - How can we view README.md in our domain's server?

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#938]
Just want to know if this is possible? Example my server is 

https://dumagueteindiemusic.radiocastvps.com/README.md

Or is there any specific url? or where is the root directory located?

Thanks!
ErnestPH

**Comment by xewl** [comment]
The root folder of this project, which contains this said README.md-file, is not publicly accessible.
It's not meant to be, either. The root folder that's actually publicized by nginx is `/web/`

**Comment by SlvrEagle23** [comment]
@ErnestPH It's not true that AzuraCast "has no root directory", it's true that it serves pages from one directory inside its main directory, to prevent other application files from being served. This is a modern best practice. Files like README.md are not accessible from the web by design.

**Comment by ErnestPH** [comment]
Yes this practice I believe is the best approach...
