### ISSUE TITLE
[Question] Stream with mobile client ?

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#939]
Hey yall,

I've tried several android clients without any luck, is there any mobile client to connect to azuracast that actually works? [Cool mic](https://coolmic.net/) looks quite promising, but failed to connect to azuracast.

Any recommendations welcome thanks

**Comment by Vaalyn** [comment]
I don't have an android device but [android.stackexchange.com](https://android.stackexchange.com/questions/23597/can-you-broadcast-to-a-shoutcast-server-from-android) advices to use an app called [BroadcastMySelf](https://play.google.com/store/apps/details?id=sa.broadcastmyselfpro&hl=en_US). I can't find the free version that they link to anymore but the pro version has good reviews and should be able to connect to IceCast and ShoutCast streams.

**Comment by macbroadcast** [comment]
Thanks a lot, another  candidate i am wondering how difficult it is to debug  @CoolMicApp-Android since its open-source. I had a conversation with the author and he believes it's not an issue from coolmic that it fails to connect to azuracast/icecast

**Comment by Vaalyn** [comment]
Can you try to connect via the app again and then look into the log viewer under utilities and post any errors you find? That way we can try to figure out why the connection fails.

Also how are you trying to connect to AzuraCast? Cool Mic seems to be only able to communicate via the IceCast protocol so if you are using the ShoutCast connection details this won't work.

**Comment by macbroadcast** [comment]
As soon as I hit connect coolmic displays an "Operation not permitted " Error.I am always using IceCast protocol. :wink: So I should check the coolmic logs on android, but i have no idea where they are.

**Comment by Vaalyn** [comment]
Maybe you can try a log viewer app like this one https://play.google.com/store/apps/details?id=com.nolanlawson.logcat (I can't really tell how good this is since I can't test it myself)

This "Operation not permitted" error logs like a problem from the app side. I've looked a bit at the source code from the repo you linked but I don't really know when this error get's thrown. But there are several error messages defined that would make more sense if it would be a problem from the server side. (https://github.com/CoolMicApp/CoolMicApp-Android/blob/1821ffbc0820f19cd5173faa44e90476f905f3c1/app/src/main/res/values/strings.xml#L181)

**Comment by macbroadcast** [comment]
Thanks for your investigations, the logviewer is helpful. I got a reply from the coolmic dev, he asked :

> Is Cool Mic connecting to Icecast, or LiquidSoap?

But i could not really answer this question.

**Comment by Vaalyn** [comment]
That’s actually what I wanted to find out when I asked „Also how are you trying to connect to AzuraCast?“ ^^

If you are using the Streamer Accounts then you are connecting to LiquidSoap which is then connecting to the IceCast server and processes the data send by the client. If you are using the source password from the station page then you are connecting to the IceCast server directly.

**Comment by macbroadcast** [comment]
Damn, this is exactly documented nowhere! Now I know why it doesn't connect :smile_cat: 

> If you are using the Streamer Accounts then you are connecting to LiquidSoap which is then connecting to the IceCast server and processes the data send by the client. If you are using the source password from the station page then you are connecting to the IceCast server directly

**Comment by Vaalyn** [comment]
I don't think that it is easily doable. This port already exposes the web server so you would have to map some stuff differently but I don't know if or what would break then.

Right now I'm not sure what exactly is blocking the port for you. Can you clarify of this is the device firewall or the mobile provider network that's blocking the connection? If you are not sure how to test this deactivate the mobile connection, connect to a WLAN and then try to stream. If this works then its the mobile provider if it still doesn't work then it should be the device firewall.

If it's just the mobile provider blocking this then the easiest solution would be to use a VPN to a network that does not block the connection.

**Comment by macbroadcast** [comment]
Yay !, after installing https://play.google.com/store/apps/details?id=app.greyshirts.firewall&hl=en and explicitly give coolmic permission,i am able to stream using the streamer accounts [via liquidsoap]
![screenshot_20181113-141414](https://user-images.githubusercontent.com/7961/48415919-0eb55e80-e74f-11e8-998a-1c3aa569f341.png)
