### ISSUE TITLE
Buffer overrun: Dropping 0.03s. (External URL on a Playlist)

### ISSUE THREAD

**Issue by rmacari** [AzuraCast/AzuraCast#940]
**Installation method**

Traditional 

**Host OS (for Docker installations)**

Ubuntu Bionic 18.04 latest updates

**Describe the bug**

Trying to run an external URL using a Playlist, the liquidsoap stops and got this error in liquidsoap.log:
[http_5904:3] Buffer overrun: Dropping 0.03s.

**To Reproduce**

Just create a new playlist, choose Remote URL Playlist instead of Song Based Playlist.
Insert the radio url, exemple: http://188.40.32.140:8295/stream.mp3.
Save.
reload the station, restart the liquidsoap.

**Expected behavior**

Liquidsoap dies.

**Relevant Logs**

2018/11/11 15:43:11 [radio_xxx_playlist_fallback:3] Switch to radio_xxx_95_cue_cut with transition.
2018/11/11 15:43:11 [dummy:3] Source failed (no more tracks) stopping output...
2018/11/11 15:43:11 [http_5904:3] New metadata chunk: ? -- P!nk - What About Us.
2018/11/11 15:43:13 [http_5904:3] Buffer overrun: Dropping 0.00s.
2018/11/11 15:43:13 [http_5904:3] Buffer overrun: Dropping 0.03s.
2018/11/11 15:43:13 [http_5904:3] Buffer overrun: Dropping 0.03s.

**Comment by CodeSteele** [comment]
https://github.com/savonet/liquidsoap/issues/545

Not sure if we expose this setting through the AzuraCast UI outside of the advanced configuration window... may be worth changing defaults too.

**Comment by rmacari** [comment]
Before creating this issue i've checked all over for someone with the same problem, i've ended on that thread 545, but my system has 2GB of swap memory and it only runs the azuracast, not having any problems with memory, swap or CPU consumption, definitely not related to the issue or to the solution provided on that thread.
