### ISSUE TITLE
Is this a way to change Nginx config?

### ISSUE THREAD

**Issue by ohld** [AzuraCast/AzuraCast#941]
Since the Azuracast is a large project, it require a separate machine for it. I have only one machine and I need to run other services on it. Is this a way to change NGINX config to add route for some container's port that is deployed on the same machine? 

It may be nice to have the ability to add NGINX reverse proxy routes in the admin management panel. Thanks.

So I need to add the proxy:
mysexyradio.com/service -> mysexyradio.com:3000

Thanks.

**Comment by CodeSteele** [comment]
First theory-craft of this would be to pull the docker install and modify the docker-compose to expose the Nginx instance on a non-standard port and reverse-proxy it on port 80/443.

_However_ running AzuraCast in a subdirectory has been untested as far as I know, while some changes I made to things like IceCast _should_ be okay, I'm not sure about the rest of the application, so I'd still dedicate a domain/subdomain to it.

**Comment by ohld** [comment]
Thanks. So how can I set up a reverse proxy in `docker-compose.yml`?

**Comment by CodeSteele** [comment]
You wouldn't be -- the reverse proxy would be set up on the server you already have other things configured on.

https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

To change the ports on Docker for the AzuraCast instance you'd do that here: 
https://github.com/AzuraCast/AzuraCast/blob/master/docker-compose.sample.yml#L29

https://docs.docker.com/compose/compose-file/#ports

**Comment by ohld** [comment]
But I need to add a new location to Nginx config to route for example `location /my_service` to some port. How can I do that?
