### ISSUE TITLE
Live DJ stream drops sound every few seconds

### ISSUE THREAD

**Issue by br0kenlink** [AzuraCast/AzuraCast#942]
Hi,
my friend is using MB Recaster, connected no problem and started the stream.
Every few seconds audio in the stream drops for a split second and we can hear kinda clipping.
Below are errors from log.
He is a pro DJ and used this software on many occasions, never had problems.

2018/11/11 22:36:49 [lang:3] Authenticating DJ: deshi
2018/11/11 22:36:49 [lang:3] AzuraCast DJ Auth Response: true
2018/11/11 22:36:49 [decoder:3] Method "OGG" accepted "application/ogg".
2018/11/11 22:36:49 [lang:3] DJ Source connected! [("Authorization","Basic ZGVzaGk6ZGVzaGkxMjM="), ("content-type","application/ogg"), ("ice-public","1"), ("ice-name","DeshiCraft (MB RECASTER)"), ("ice-description","Broken Link Radio DnB Live (MB RECASTER)"), ("ice-genre","Variety"), ("ice-url","http://brokenlink.xyz"), ("ice-bitrate","128")]
2018/11/11 22:36:49 [live_live_switch:3] Switch to live_live_fallback with transition.
2018/11/11 22:36:49 [live_live_fallback:3] Switch to blank_6034 with forgetful transition.
2018/11/11 22:36:49 [lang:3] AzuraCast Live Connected Response: ["received"]
2018/11/11 22:36:49 [threads:3] Created thread "harbor source feeding" (2 total).
2018/11/11 22:36:49 [live_input_streamer:3] Decoding...
2018/11/11 22:36:55 [live_live_fallback:3] Switch to audio_to_stereo_6031 with transition.
2018/11/11 22:37:04 [lang:3] Authenticating DJ: deshi
2018/11/11 22:37:04 [lang:3] AzuraCast DJ Auth Response: true
2018/11/11 22:37:26 [live_live_fallback:3] Switch to blank_6034 with forgetful transition.
2018/11/11 22:37:26 [dummy:3] Source failed (no more tracks) stopping output...
2018/11/11 22:37:32 [live_live_fallback:3] Switch to audio_to_stereo_6031 with transition.
2018/11/11 22:38:03 [live_live_fallback:3] Switch to blank_6034 with forgetful transition.
2018/11/11 22:38:03 [dummy:3] Source failed (no more tracks) stopping output...
2018/11/11 22:38:09 [live_live_fallback:3] Switch to audio_to_stereo_6031 with transition.
2018/11/11 22:38:35 [live_live_fallback:3] Switch to blank_6034 with forgetful transition.
2018/11/11 22:38:35 [dummy:3] Source failed (no more tracks) stopping output...
2018/11/11 22:38:40 [live_live_fallback:3] Switch to audio_to_stereo_6031 with transition.
2018/11/11 22:39:08 [live_live_fallback:3] Switch to blank_6034 with forgetful transition.
2018/11/11 22:39:08 [dummy:3] Source failed (no more tracks) stopping output...

**Comment by br0kenlink** [comment]
I have found this in MB Recaster log

08:37:40     <Error on BASS_Encode_CastGetstats> 1 radio.brokenlink.xyz:8035/ - some other mystery error
08:39:40     <Error on BASS_Encode_CastGetstats> 1 radio.brokenlink.xyz:8035/ - some other mystery error
08:41:40     <Error on BASS_Encode_CastGetstats> 1 radio.brokenlink.xyz:8035/ - some other mystery error
08:43:40     <Error on BASS_Encode_CastGetstats> 1 radio.brokenlink.xyz:8035/ - some other mystery error
08:45:40     <Error on BASS_Encode_CastGetstats> 1 radio.brokenlink.xyz:8035/ - some other mystery error
08:47:40     <Error on BASS_Encode_CastGetstats> 1 radio.brokenlink.xyz:8035/ - some other mystery error
08:49:40     <Error on BASS_Encode_CastGetstats> 1 radio.brokenlink.xyz:8035/ - some other mystery error
08:51:40     <Error on BASS_Encode_CastGetstats> 1 radio.brokenlink.xyz:8035/ - some other mystery error

It seems it tries to fetch statistics from shoutcast/icecast but fails.
I am testing on latest MB Recaster and sound drops now aren't that often. It seems they happen every time it tries to fetch stats.

**Comment by ivellios1988** [comment]
Similar error happens to me:

2019/05/05 21:46:54 [lang:3] Authenticating DJ: source
2019/05/05 21:46:54 [lang:3] AzuraCast DJ Auth Response: true
2019/05/05 21:46:54 [decoder:3] Method "OGG" accepted "application/ogg".
2019/05/05 21:46:54 [lang:3] DJ Source connected! [("Authorization","Basic c291cmNlOmthcGl0YW4xMTE="), ("content-type","application/ogg"), ("ice-public","0"), ("ice-name","RadioBOSS Stream"), ("ice-description"," "), ("ice-genre","Other"), ("ice-url","http://www.example.com"), ("ice-bitrate","192"), ("icy-icq"," "), ("icy-aim"," "), ("icy-irc"," ")]
2019/05/05 21:46:54 [icecast_live_switch:3] Switch to icecast_live_fallback with transition.
2019/05/05 21:46:54 [lang:3] AzuraCast Live Connected Response: received
2019/05/05 21:46:54 [threads:3] Created thread "harbor source feeding" (2 total).
2019/05/05 21:46:54 [icecast_input_streamer:3] Decoding...
2019/05/05 21:46:59 [lang:3] Authenticating DJ: source
