### ISSUE TITLE
Custom Branding

### ISSUE THREAD

**Issue by arranh11** [AzuraCast/AzuraCast#947]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 18.04

**Describe the bug**
Unable to access Customize Branding. I have tried it on two different copies.

**To Reproduce**
Do exactly that- go onto Customize Branding via the System Administration page.
http://arran.pw/files/2018-11-12_21-52-11.gif

**Expected behavior**
500 Error.
Container error while retrieving "App\Controller\Admin\BrandingController"
Container.php : 95

**Relevant Logs**
https://pastebin.com/xkqnS5kQ

**Screenshots**

**Device(s):**
 - Device: Laptop 
 - OS: Windows
 - Browser: Chrome
 - Version: Unknown

**Comment by arranh11** [comment]
Apologies- attached wrong logs.
https://pastebin.com/xkqnS5kQ

**Comment by TildeSlashC0re** [comment]
same here

**Comment by arranh11** [comment]
Maybe you could post your logs too? Might be helpful.

**Comment by SlvrEagle23** [comment]
@arranh11 @TildeSlashC0re Should be fixed now. Recent update to consolidate some shared code missed one change.

**Comment by TildeSlashC0re** [comment]
crazy fast response time, lol :D
works like intended now :smile: !

thanks a lot
