### ISSUE TITLE
Weighting Should Take Into Account The Number of Songs In It

### ISSUE THREAD

**Issue by CodeSteele** [AzuraCast/AzuraCast#954]
Eg:

One list, 100 songs
Another list, 5 songs.

A weighting of 1:1 should not play 5 songs from 100 play list song list then the 5 from the 2nd list. This _appears_ to be a major reason for people saying that songs are repeating too often.

1:1 should be on a per-song level, so that 1:1 weighting would treat this as a mega playlist with 105 songs.

1:2 would treat this as a playlist with 110 songs, with the 2nd list having it's songs twice (possibly weighted to keep them apart from each other?).

Should finally remedy all issues with playlists/randomization/etc.

**Comment by SlvrEagle23** [comment]
@CodeSteele It does now :)
