### ISSUE TITLE
NO_FILE: can't find command '/var/azuracast/.opam/system/bin/liquidsoap'

### ISSUE THREAD

**Issue by netbladenl** [AzuraCast/AzuraCast#959]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubtunu 18.0.4.1

**Describe the bug**
Liquidsoap won't run anymore

**To Reproduce**
No need to, after the update of yesterday there's no way to start the Liquidsoap service
"NO_FILE: can't find command '/var/azuracast/.opam/system/bin/liquidsoap'"

**Expected behavior**
Liquidsoap working

**Relevant Logs**
Liquidsoap log ; 
# WARNING! This file is automatically generated by AzuraCast.
# Do not update it directly!

set("init.daemon", false)
set("init.daemon.pidfile.path","/var/azuracast/stations/radio_netblade__endless_music/config/liquidsoap.pid")
set("log.file.path","/var/azuracast/stations/radio_netblade__endless_music/config/liquidsoap.log")
set("log.stdout", true)
set("server.telnet",true)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port", 8034)
set("harbor.bind_addrs",["0.0.0.0"])

set("tag.encodings",["UTF-8","ISO-8859-1"])
set("encoder.encoder.export",["artist","title","album","song"])

# AutoDJ Next Song Script
def azuracast_next_song() =
  uri = get_process_lines("curl -s --request POST --url http://nginx/api/internal/4/nextsong --form api_auth=91826579bb9585af76cd0085c25232c50afac899168383c616ebc3b28558eea01eb947c5026e83e7adc258ff9e01502ef94f")
  uri = list.hd(uri, default="")
  log("AzuraCast Raw Response: #{uri}")
  
  if uri == "" or string.match(pattern="Error", uri) then
    log("AzuraCast Error: Delaying subsequent requests...")
    system("sleep 30")
    request.create("")
  else
    request.create(uri)
  end
end

# DJ Authentication
def dj_auth(user,password) =
  log("Authenticating DJ: #{user}")
  ret = get_process_lines("curl -s --request POST --url http://nginx/api/internal/4/auth --form dj_user=#{user} --form dj_password=#{password} --form api_auth=91826579bb9585af76cd0085c25232c50afac899168383c616ebc3b28558eea01eb947c5026e83e7adc258ff9e01502ef94f")
  ret = list.hd(ret, default="")
  log("AzuraCast DJ Auth Response: #{ret}")
  bool_of_string(ret)
end

live_enabled = ref false

def live_connected(header) =
  log("DJ Source connected! #{header}")
  live_enabled := true
  ret = get_process_lines("curl -s --request POST --url http://nginx/api/internal/4/djon --form api_auth=91826579bb9585af76cd0085c25232c50afac899168383c616ebc3b28558eea01eb947c5026e83e7adc258ff9e01502ef94f")
  log("AzuraCast Live Connected Response: #{ret}")
end

def live_disconnected() =
  log("DJ Source disconnected!")
  live_enabled := false
  ret = get_process_lines("curl -s --request POST --url http://nginx/api/internal/4/djoff --form api_auth=91826579bb9585af76cd0085c25232c50afac899168383c616ebc3b28558eea01eb947c5026e83e7adc258ff9e01502ef94f")
  log("AzuraCast Live Disconnected Response: #{ret}")
end

# Fallback Playlists
playlist_default = audio_to_stereo(playlist(reload_mode="watch",mode="randomize","/var/azuracast/stations/radio_netblade__endless_music/playlists/playlist_default.m3u"))
playlist_old_podcasts = audio_to_stereo(playlist(reload_mode="watch",mode="randomize","/var/azuracast/stations/radio_netblade__endless_music/playlists/playlist_old_podcasts.m3u"))
playlist_mixes = audio_to_stereo(playlist(reload_mode="watch",mode="randomize","/var/azuracast/stations/radio_netblade__endless_music/playlists/playlist_mixes.m3u"))
playlist_soul__jazz = audio_to_stereo(playlist(reload_mode="watch",mode="randomize","/var/azuracast/stations/radio_netblade__endless_music/playlists/playlist_soul__jazz.m3u"))
playlist_chillout_sunday = audio_to_stereo(playlist(reload_mode="watch",mode="randomize","/var/azuracast/stations/radio_netblade__endless_music/playlists/playlist_chillout_sunday.m3u"))
playlist_daily_playlist = audio_to_stereo(playlist(reload_mode="watch",mode="randomize","/var/azuracast/stations/radio_netblade__endless_music/playlists/playlist_daily_playlist.m3u"))

# Standard Playlists
radio = random(weights=[3], [playlist_default]);

# Assemble final playback order
dynamic = audio_to_stereo(request.dynamic(id="radio_netblade__endless_music_next_song", timeout=20., azuracast_next_song))
dynamic = cue_cut(id="radio_netblade__endless_music_cue_cut", dynamic)
radio = fallback(id="radio_netblade__endless_music_playlist_fallback", track_sensitive = false, [dynamic, switch([ ({ 19h0m-20h30m }, playlist_old_podcasts), ({ 19h0m-5h0m }, playlist_mixes), ({ 20h30m-5h0m }, playlist_soul__jazz), ({ 5h0m-19h0m }, playlist_chillout_sunday), ({ 5h0m-19h0m }, playlist_daily_playlist), ({ true }, radio) ]), blank(duration=2.)])

# Live Broadcasting
live = audio_to_stereo(input.harbor("/", id="radio_netblade__endless_music_input_streamer", port=8035, user="shoutcast", auth=dj_auth, icy=true, max=30., buffer=10., icy_metadata_charset="UTF-8", metadata_charset="UTF-8", on_connect=live_connected, on_disconnect=live_disconnected))
ignore(output.dummy(live, fallible=true))
live = fallback(id="radio_netblade__endless_music_live_fallback", track_sensitive=false, [live, blank(duration=2.)])

radio = switch(id="radio_netblade__endless_music_live_switch", track_sensitive=false, [({!live_enabled}, live), ({true}, radio)])

# Crossfading
radio = crossfade(start_next=4.50,fade_out=3.,fade_in=3.,radio)

# Apply amplification metadata (if supplied)
radio = amplify(1., radio)

# Local Broadcasts
output.icecast(%mp3(samplerate=44100,stereo=true,bitrate=192, id3v2=true), id="radio_netblade__endless_music_local_1", host = "127.0.0.1", port = 8030, password = "WphdW97Y:#1", name = "Radio NetBlade - Endless Music", description = "Nonstop de beste Pop - Rock - Dance - Hiphop - Lounge - Jungle - Dubstep - Soul&Jazz", url = "www.netblade.nl", public = false, encoding = "UTF-8", protocol="icy", radio)
output.icecast(%fdkaac(channels=2, samplerate=44100, bitrate=96, afterburner=true, aot="mpeg4_he_aac_v2", transmux="adts", sbr_mode=true), id="radio_netblade__endless_music_local_2", host = "127.0.0.1", port = 8030, password = "WphdW97Y:#2", name = "Radio NetBlade - Endless Music", description = "Nonstop de beste Pop - Rock - Dance - Hiphop - Lounge - Jungle - Dubstep - Soul&Jazz", url = "www.netblade.nl", public = false, encoding = "UTF-8", protocol="icy", radio)

# Remote Relays
None

**Screenshots**
none

**Device(s):**
Server side issue

**Additional context**
This happend during the last update of yesterday, redo update don't solve the problem

**Comment by SlvrEagle23** [comment]
@netbladenl This should only happen if your web container's code didn't update but your Docker containers did. Try updating the `docker.sh` utility itself along with the update, like so:

```bash
./docker.sh update-self
./docker.sh update
```

This should be done with every update to ensure important fixes are included. (This is a fairly new addition to our documentation, so you weren't previously updating wrong, we've just modified the best practices in recent weeks.)

**Comment by netbladenl** [comment]
> @netbladenl This should only happen if your web container's code didn't update but your Docker containers did. Try updating the `docker.sh` utility itself along with the update, like so:
> 
> ```shell
> ./docker.sh update-self
> ./docker.sh update
> ```
> 
> This should be done with every update to ensure important fixes are included. (This is a fairly new addition to our documentation, so you weren't previously updating wrong, we've just modified the best practices in recent weeks.)

Thank you! This fixed my problem! Keep up the great work!

**Comment by SlvrEagle23** [comment]
@netbladenl Good to hear! :)
