### ISSUE TITLE
Now Playing Data Cronjob - 500: listener_user_agent cannot be null

### ISSUE THREAD

**Issue by xewl** [AzuraCast/AzuraCast#960]
**Installation method**
Traditional

**Host OS (for Docker installations)**
Ubuntu 16.04.3

**Describe the bug**
Now Playing Data had been hanging for a few hours. Seems like it couldn't run without a database error occurring.

**To Reproduce**
Most probably: having listeners without an user_agent (Icecast), and running the "Now Playing Data" cron-job.

**Expected behavior**
For the NPD-cron to be able to actually run:
``ALTER TABLE listener CHANGE listener_user_agent listener_user_agent VARCHAR(255) NULL;``

**Relevant Logs**
/ (Forgot to c/p and it doesn't do it at this very moment :P)

**Screenshots**
/

**Device(s):**
/

**Additional context**
 - Version: AzuraCast 0.8.0-2017.12 Beta (Tradional)
Yes I know I'm on a quite old version of AC atm, but I've looked at the migrations in this repo, and to me it looks like that `Migration/Version20170829030442.php` & `Migration/Version20170516073708.php` has it defining listener_user_agent as NOT NULL.

**Comment by SlvrEagle23** [comment]
@xewl This should be fixed now. Note that you'll have to update your AzuraCast codebase to see the fix!
