### ISSUE TITLE
[question] azuracast slack/IRC channel

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#961]
hello azuracasters

since I am following azuracast and its active development and great support, I am asking if its might be useful to open a slack or irc channels for all the users?  :smile:

**Comment by SlvrEagle23** [comment]
@macbroadcast @Vaalyn Good idea! I was just thinking about this earlier today, so I've gone ahead and created a Slack community for us, which I'll begin integrating with our GitHub repository.

[Here's an invite to the AzuraCast Slack group.](https://join.slack.com/t/azuracast/shared_invite/enQtNDgzNTU5NTY3MDMxLTc4YjhhNWQ2MjZiYWNmZmU5OTI2MjYzYzQ5NWExYTRlNGQzM2QzNDgwMmJkNWZlMzExMjk2MWY0YTU5ODU1ZGQ)
