### ISSUE TITLE
Use League\Flysystem for file and directory access

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#962]
**Is your feature request related to a problem? Please describe.**
Not really related to a problem but more a kind of enhancement idea.

**Describe the solution you'd like**
I'm used to have a good abstraction for file and directory operations that makes it easier to do these things without having to worry too much about the native file/directory functions and their pitfalls. 

Most projects I have worked on used the [League\Flysystem](https://packagist.org/packages/league/flysystem) package for this. I would recommend implementing this package in AzuraCast and discourage the direct use of PHPs filesystem functions. This would also make it much easier to add support for other filesystems in the future like for example AWS S3, Azure Blob Storage, FTP/S, SFTP, etc. through the many available adapters for League\Flysystem.

What do you think about this?

**Comment by SlvrEagle23** [comment]
@Vaalyn I was just talking with @CodeSteele about this a few days ago. I want to abstract out our filesystem handling specifically so that we can implement S3 and other connectors in the future without much issue. Flysystem is the gold standard for this and was exactly what I had planned on implementing.

**Comment by SlvrEagle23** [comment]
@Vaalyn It's also likely that the resolution of enhancement #953 will be the first use of Flysystem in our application.

**Comment by Vaalyn** [comment]
That's awesome =)

If you need help for replacing filesystem operations with Flysystem methods I'd like to offer my help. I'd propose creating several issues for the different parts of the app where this needs to be done so that we could share the work and keep track on what's done and what still needs to be done.
