### ISSUE TITLE
Problem when updating.

### ISSUE THREAD

**Issue by webma5ter23** [AzuraCast/AzuraCast#965]
I do not know if there are updates, I use the traditional installation.

But when you run the update commands the site goes down, if there are bug fix updates, I will not be able to update.

**Comment by SlvrEagle23** [comment]
@webma5ter23 I need more information before I can properly diagnose this issue.

Are you seeing any error messages during the update script? You can copy/paste the output of the update process here if needed.

When you try to access your site, do you see any error messages then?

**Comment by webma5ter23** [comment]
For the error to appear I must update and the service will fall, I solve it by re-establishing a backup. How can I know when there are updates to AzuraCast?

Thank you

**Comment by SlvrEagle23** [comment]
@webma5ter23 I can't diagnose or fix any issues without some details of the error you're experiencing.

To answer your question, AzuraCast has added update checks directly to the application in its most recent versions. You should update to the latest version, then you will be notified on the app's homepage when updates are available.
