### ISSUE TITLE
LAST UPDATE BROCK MY AZURACAST

### ISSUE THREAD

**Issue by unsense** [AzuraCast/AzuraCast#971]
Last Update Today broack my AzuraCast Site and admin logo , not  found ? please help

**Comment by unsense** [comment]
TASK [services : Enable and restart all core services] *********************************************************
skipping: [localhost] => (item=influxdb) 
skipping: [localhost] => (item=mysql) 
skipping: [localhost] => (item=php7.2-fpm) 
skipping: [localhost] => (item=nginx) 
skipping: [localhost] => (item=redis) 
TASK [azuracast-cron : Generate Cron Template] *****************************************************************
skipping: [localhost]
TASK [azuracast-cron : Install Cron file] **********************************************************************
skipping: [localhost]
TASK [azuracast-cron : Clean up temp Cron file] ****************************************************************
skipping: [localhost]
TASK [azuracast-setup : Ensure update script continues to be executable] ***************************************
changed: [localhost] => (item=/var/azuracast/www/update.sh)
TASK [azuracast-setup : Run AzuraCast Setup (Install Mode)] ****************************************************
skipping: [localhost]
TASK [azuracast-setup : Run AzuraCast Setup (Update Mode)] *****************************************************
changed: [localhost]
PLAY RECAP *****************************************************************************************************
localhost                  : ok=16   changed=4    unreachable=0    failed=0

**Comment by SlvrEagle23** [comment]
@unsense What exactly is wrong with your AzuraCast instance? Your log there suggests you're running a traditional installation and that the update actually succeeded without issue.

**Comment by unsense** [comment]
thank a lot realy for you kind help and software , you making dreams come true really
many thanks
just 1 more question , i need to make one stream fix number not changeable to play it in VMIX software
also can i make it possible so listener in the public page can select stream quality

thanks 100000000000000000000000 times

**Comment by unsense** [comment]
my Fault it is working again , i need to use http not https

thanks but only question "can i make it possible so listener in the public page can select stream quality"

**Comment by SlvrEagle23** [comment]
@unsense That is a separate enhancement request and should be a new issue. Make sure when creating the new issue to follow the template it gives you rather than just filling in your own details.
