### ISSUE TITLE
Easy Station Renames & Move Resources

### ISSUE THREAD

**Issue by CodeSteele** [AzuraCast/AzuraCast#973]
Currently if you rename a station it'll only change the station name and key.

It doesn't update any folders for you, so everything still has your old station name on it.

On _one_ hand, this is good because if you tie any automation to specific paths we don't want to break that by default.

On the other hand, AFAIK: making this change manually can be a pain.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38932/add-ability-for-administrators-to-move-a-stations-basemedia-directory
