### ISSUE TITLE
How change genre?

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#976]
Installation method
Traditional

Description

How i change station genre from icecast status page for it change on directories too?

Thank you

![stream_genre_azura](https://user-images.githubusercontent.com/7109309/48789578-49863c00-ece5-11e8-910d-e5b0f6bf203e.png)

**Comment by MyTheValentinus** [comment]
Hello,
You can add a parameter in the icecast config. Checkout this documentation: http://icecast.org/docs/icecast-2.4.0/config-file.html#mountsettings

**Comment by jonikane** [comment]
It is not possible to change on mount point on panel?

**Comment by SlvrEagle23** [comment]
@jonikane I have added genre to the station profile in the latest update, and it will carry this information over to your Icecast feed and any streams Liquidsoap broadcasts to.
