### ISSUE TITLE
 Scheduled playlist plays on the wrong days

### ISSUE THREAD

**Issue by JMultimidia** [AzuraCast/AzuraCast#977]
**Installation method**
Traditional

**Host OS (for Docker installations)**
Ubuntu 18

**Describe the bug**

I made a schedule to play only the "Samba" rhythm on Sundays and to my surprise the playlist played today (Tuesday).

**Comment by SlvrEagle23** [comment]
@JMultimidia What is your local time zone? For complicated reasons, the day that a scheduled playlist will play is that day in UTC, i.e. if a playlist is set to play on Monday, it will play between 00:00 (12am) and 23:59 (11:59pm) UTC on Monday.

There are a number of significant playlist changes that we have in the works that will allow more fine-tuned control of this, but those changes haven't been made yet.

Local testing on my end shows that the current scheduling playlist functionality is working, considering the UTC restriction above, so I would need more information about your installation before I could diagnose the issue further.

**Comment by JMultimidia** [comment]
utc -3. But the different is of the two days.

**Comment by SlvrEagle23** [comment]
@JMultimidia Can you send me some supporting documentation so I can at least start to diagnose the issue? I can't fix anything without some additional details. Namely, if you could include screenshots of your current playlists and how they are scheduled, along with what time you were hearing the playlist (i.e. was it at the right time, just the wrong day?) and if you have heard it on other days since then, that would be helpful.

**Comment by JMultimidia** [comment]
The playlist as attached pictures should play only on Saturday and Sunday in the evening. But she does it every day. I deleted and created the playlist and schedule again, restarted the azura but did not succeed. To temporarily fix the problem I deactivated the playlist during the week.

![capturar](https://user-images.githubusercontent.com/20319612/49189744-4ecf3080-f34e-11e8-9885-d678bdad94a9.PNG)
![capturar2](https://user-images.githubusercontent.com/20319612/49189745-4f67c700-f34e-11e8-99a4-ae280625846f.PNG)

**Comment by SlvrEagle23** [comment]
@JMultimidia I strongly suspect this is breaking because, at least from a UTC standpoint, this playlist is "overnight", and that's short-circuiting some checks in our system. I will investigate and get back to you as soon as I can.

**Comment by JMultimidia** [comment]
Thank you very much. NOTE: I use UTC-3

**Comment by macbroadcast** [comment]
Same behavior, playlist which should play only sunday beween 9 -12PM play every day 
![bildschirmfoto von 2018-11-30 09-40-05](https://user-images.githubusercontent.com/7961/49278327-ba1b1e80-f484-11e8-927f-cc3ca1215c42.png) 
![bildschirmfoto von 2018-11-30 09-40-53](https://user-images.githubusercontent.com/7961/49278338-bedfd280-f484-11e8-9473-9aa798ceb282.png)

**Comment by SlvrEagle23** [comment]
@JMultimidia @macbroadcast Few questions to help investigate:

- Are you all running Traditional installs?

- Do you have the "Manual AutoDJ" setting turned on or off?

- If you run `tail -f /var/azuracast/stations/(station_name)/config/liquidsoap.log` (Traditional) or `docker-compose logs -f stations` (Docker), does it show any errors with communicating with AzuraCast for the next song?

**Comment by macbroadcast** [comment]
hi @SlvrEagle23 i am running docker install and Manual AutoDJ is set to on 
![bildschirmfoto von 2018-11-30 17-12-16](https://user-images.githubusercontent.com/7961/49300687-23ba1d80-f4c3-11e8-8b51-cdc198447e28.png) and running docker-compose logs -f station floods my screen with 
![bildschirmfoto von 2018-11-30 17-15-24](https://user-images.githubusercontent.com/7961/49300881-9c20de80-f4c3-11e8-9f02-93c50012ee66.png) Hope this helps

**Comment by SlvrEagle23** [comment]
@macbroadcast The input.http duration issue is unrelated and should probably be a separate issue, but I've gone ahead and increased the buffer duration so hopefully it will be less of an issue.

I've also updated the Liquidsoap configuration generator to properly take into consideration both the schedule days and the play-once days, which were previously only used by the AzuraCast AutoDJ. If you have "Manual AutoDJ" turned on, the AzuraCast AutoDJ will not be used, so it will depend on LS's configuration containing the specifics.

This should fix the issue on your end @macbroadcast. I'm not sure if the same issue is affecting @JMultimidia, but I'd recommend updating and seeing if the issue persists.

**Comment by adwinter** [comment]
I am affected by this behavior as well, my station runs on GMT-8, but using the formula above (what is the day in GMT?), its working better..
