### ISSUE TITLE
Icecast trying to load an intro to mountpoints on startup.

### ISSUE THREAD

**Issue by Scraticus** [AzuraCast/AzuraCast#991]
**Installation method**

I am using Docker

**Host OS (for Docker installations)**

Ubuntu 18.04

**Describe the bug**

When the IceCast KH service starts, it appears to be looking for an introduction file/mp3 to play for streams. This is a setting in the icecast.xml, and may be triggering unexpectedly.

**To Reproduce**
1. Restart IceCast2
2. Check the log.

**Expected behavior**

Unless there is a setting toggle for 'play introduction' it should not be looking for one. It can sometimes cause odd behaviour / memory leaks. There is also a **//** in the log so that also could be a problem.

**Relevant Logs**

WARN source/source_set_intro Cannot open intro for /station.ogg "/usr/local/share/icecast/web//station.ogg": No such file or directory

**Additional context**

It's usually harmless, but can cause memory leaks over time, hence the report.

**Comment by CodeSteele** [comment]
@SlvrEagle23 did the original introduction get changed from `error.mp3` to `station.ogg`?

**Comment by SlvrEagle23** [comment]
@CodeSteele No, it's just not unsetting that value if it's empty in the config. If it passes it but with an empty string, it assumes the fallback is the same as the station mountpoint (for some silly reason), which in this case is `/station.ogg`.

**Comment by SlvrEagle23** [comment]
@Scraticus After local testing, I can confirm that AzuraCast is indeed not writing any value to the `<intro>` parameter for each mount point, nor is it writing any intro value anywhere else in the configuration.

I believe this is an upstream error in Icecast-KH that causes it to interpret no value as an empty string, which it defaults to the current mount point name.

I'm also not entirely sure how this contributes to memory leakage, as it appears to just throw the error and move on without any further issues.

In any case, this should likely be taken up with the Icecast-KH repo as an upstream bug.

**Comment by CouinCouin** [comment]
Hi 

I encounter this problem too. 

Log  : 
[2020-03-28  16:23:41] WARN source/source_set_intro Cannot open intro for /128.mp3 "/usr/local/share/icecast/web//128.mp3": No such file or directory
[2020-03-28  16:23:41] WARN source/source_set_intro Cannot open intro for /64.aac "/usr/local/share/icecast/web//64.aac": No such file or directory
[2020-03-28  16:23:42] WARN source/source_set_intro Cannot open intro for /32.aac "/usr/local/share/icecast/web//32.aac": No such file or directory

Thanks :)
Couin
