### ISSUE TITLE
Sequential playlist with set song order not working

### ISSUE THREAD

**Issue by appstersjulia** [AzuraCast/AzuraCast#999]
**Installation method**
Traditional

**Describe the bug**
I have a playlist with _Song Playback Order_ set to _Sequential_, and I have reordered the songs in the order I want. The songs still seem to shuffle. I have checked the logs, and can't find any obvious errors. Tried clearing the cache and restarting the station. Is there any way I can make it work by adding a line to the Liquidsoap Custom Configuration?

Would greatly appreciate some help! Thank you for a great service!

**Comment by SlvrEagle23** [comment]
@appstersjulia There are some things that will cause the sequential playlist to reset to its original state:

- Restarting the station during playlist updates
- Removing items from the sequential playlist, or
- Updating the entire installation

If you aren't doing any of these things and the sequential playlist still isn't following the correct order, that will be rather trickier to diagnose. It may be a matter where we'll want to look at your specific installation to see how things are set up to identify any edge cases.

**Comment by appstersjulia** [comment]
Thanks for the quick reply! Ok, so does this mean that if I do any of these things, I will have to change the Song Playback Order to Sequential again and re-save? (I did update the installation so that might be the cause – the settings for the playlist are still set to "Sequential" though). Or how do I set it to sequential again after an update/restart?

**Comment by SlvrEagle23** [comment]
@appstersjulia It will always stay as a sequential playlist, but it will reset the "pointer" of where it currently is on the sequential playlist when you update/restart, as that clears the cache that stores that position. In other words, it'll just start over from the beginning. If you're updating/rebooting frequently this will seem like duplicating songs but it's normal behavior.

**Comment by appstersjulia** [comment]
@SlvrEagle23 Ah, then that might not be the source of the problem. I'm experiencing that the play order isn't followed at all on my installation. I haven't done any of the things you listed previously now for a while, and when listening/looking in the Liquidsoap log, the play order isn't the one I've set. I understand that it might be hard to diagnose this problem, but do you have any suggestions for other fixes or would you be able to take a look at our installation? We would greatly appreciate it. Thanks a lot.

**Comment by SlvrEagle23** [comment]
@appstersjulia Sure, I can take a look at your installation and see what's going on. Send me an e-mail to the address on my account here and I will look into it further.

**Comment by SlvrEagle23** [comment]
Closing as this issue was patched in the main AzuraCast codebase after discovering the source of the problem.
